### ISSUE TITLE
[ide] signature help vs rest arguments

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10008]
Signature help doesn't work as expected for rest arguments. It's fine for the first parameter:

![image](https://user-images.githubusercontent.com/2620907/102691883-01151180-4210-11eb-90d4-1e03284b2b98.png)

But after that, we're "out-of-bounds" - the active parameter is no longer underlined because the `activeParameter` index is reported as `1`, even though the max parameter index is 0.

![image](https://user-images.githubusercontent.com/2620907/102691897-15f1a500-4210-11eb-88a9-d6e5ab02faf8.png)

---

```haxe
class Main {
	static function main() {
		foo(1, )
	}

	static function foo(...rest:Int) {}
}
```

**Comment by RealyUniqueName** [comment]
Shouldn't vshaxe underline based on `activeSignature` instead of `activeParameter`?

**Comment by Gama11** [comment]
`activeSignature` picks the _signature_, if there's multiple (in case of overloads).

**Comment by nadako** [comment]
> `activeParameter` index is reported as `1`, even though the max parameter index is 0.

I wonder if this should be handled in the language server, because at the display protocol level it might be useful to know the number of applied rest argument (to show a counter or something).
