### ISSUE TITLE
overload keyword is incompatible with module-level fields

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10006]
This sequence of events feels a bit like the compiler is trying to mock the user:

![image](https://user-images.githubusercontent.com/2620907/102689990-ad4ffb80-4202-11eb-8b11-cf089b8eabc4.png)

Ok, no problem, let's add `extern` then.

![image](https://user-images.githubusercontent.com/2620907/102690006-d83a4f80-4202-11eb-8e45-1e0597a8fae8.png)

...

-----

This should either just work, or give a better error right away ("`overload` is not supported for module-level fields on this target" or something).

**Comment by nadako** [comment]
I guess we should just allow `extern` for module-levels for force-inlining also to make overloads work.
