### ISSUE TITLE
[eval] debugging fails with Not_found

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10001]
Trying to debug with eval crashes with the following on a recent nightly (c836703):

```
Thread 1 killed on uncaught exception Not_found
Raised at file "src/context/common.ml", line 954, characters 12-27
Called from file "src/macro/eval/evalDebugSocket.ml", line 644, characters 69-120
Called from file "src/macro/eval/evalDebugSocket.ml", line 823, characters 35-43
Called from file "src/core/json/jsonRpc.ml", line 45, characters 5-9
Called from file "src/macro/eval/evalDebugSocket.ml", line 827, characters 3-10
Called from file "thread.ml", line 39, characters 8-14
```

With 4.1.4 it works fine.

**Comment by RealyUniqueName** [comment]
That looks like the compiler can't find a file to set a breakpoint in. Can you assemble a sample?

**Comment by Gama11** [comment]
There's nothing to assemble, this happens always, even with a Hello World project / HaxeRepro. Might be Windows-specific though, IIRC @nadako was also able to reproduce.

**Comment by nadako** [comment]
yeah putting a breakpoint didn't work for me last time i tried. will look into it sometime later

**Comment by RealyUniqueName** [comment]
> Might be Windows-specific

Yep, can't reproduce on linux.

**Comment by nadako** [comment]
Looks like `Common.find_file` used to work fine with absolute file paths on Windows, but not anymore. Here's what I get from the `setBreakpoints` handler (all traces except the first one is from `Common.find_file`):

```
setBreakpoints requested file: c:\Users\nadako\Code\playground\src\Main.hx
f_dir: c:\Users\nadako\Code\playground\src
> file: src/c:\Users\nadako\Code\playground\src\Main.hx
> dir: src/c:\Users\nadako\Code\playground\src
> file: c:\Users\nadako\Code\playground\src\Main.hx
> dir: c:\Users\nadako\Code\playground\src
> file: C:\Users\nadako\Code\haxe\extraLibs/c:\Users\nadako\Code\playground\src\Main.hx
> dir: C:\Users\nadako\Code\haxe\extraLibs/c:\Users\nadako\Code\playground\src
> file: C:\Users\nadako\Code\haxe\std/eval/_std/c:\Users\nadako\Code\playground\src\Main.hx
> dir: C:\Users\nadako\Code\haxe\std/eval/_std/c:\Users\nadako\Code\playground\src
> file: C:\Users\nadako\Code\haxe\std/c:\Users\nadako\Code\playground\src\Main.hx
> dir: C:\Users\nadako\Code\haxe\std/c:\Users\nadako\Code\playground\src
```

**Comment by RealyUniqueName** [comment]
I guess the reason of the issue are slashes in these lines:
https://github.com/HaxeFoundation/haxe/blob/ba193e4d8c102b21c5225cbb31e58e85b2cff7ea/src/context/common.ml#L901
https://github.com/HaxeFoundation/haxe/blob/ba193e4d8c102b21c5225cbb31e58e85b2cff7ea/src/context/common.ml#L924
Could you please check if replacing them with backslashes fixes the issue?
