### ISSUE TITLE
Tracing / Std.string()-ifying rest arguments

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#10011]
Tracing a rest argument gives you a nice clean `[1,2,3]` on some targets, but not others.

- For instance on the JVM target, you get this ugly native array representation: `[Ljava.lang.Integer;@330bedb4`
- C# is not much more helpful: `System.Int32[]`
- Python gives `(1, 2, 3)`, which you probably wouldn't expect as a Haxe user, but at least it prints the contents

JS, Neko, CPP, Eval and HL seem fine, haven't tested PHP or Lua.

```haxe
import haxe.Rest;

class Main {
	static function main() {
		foo(1, 2, 3);
	}

	static function foo(...rest:Int) {
		trace(rest);
	}
}
```

Perhaps this can be fixed by defining a `toString()` in the right place?

**Comment by nadako** [comment]
Should we just add
```haxe
public function toString():String {
	return toArray().toString();
}
```
?
