### ISSUE TITLE
Errors in diagnostics change when rerunning diagnostics.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10028]
I wanted to investigate how https://github.com/haxetink/tink_macro/pull/33 would fare in diagnostics and @RealyUniqueName suggested I also try an `if`-chain.

```haxe
import haxe.macro.*;
using haxe.macro.Tools;

class A { public function new() {} }
class B { public function new() {} }

class Run {

	static function main() {
		trace(common1(new A(), new B()));
		trace(common2(new A(), new B()));
	}

	static macro function common1(rest:Array<Expr>) {
		var ret = rest.pop();
		rest.reverse();
		for (e in rest)
			ret = macro if (true) $e else $ret;
		return macro $v{typeOrError(ret)};
	}

	static macro function common2(rest:Array<Expr>) {
		var ret = macro $a{rest};
		return macro $v{typeOrError(ret)};
	}

	#if macro
	static function typeOrError(e:Expr, ?pos:haxe.PosInfos) {
		var ret =
			try Context.typeof(e).toString()
			catch (e:Dynamic) 'Error: ' + Std.string(e);
		haxe.Log.trace(ret, pos);
		return ret;
	}
	#end
}
```

Given that setup, I get the following output:

```
Haxe print:
Run.hx:19: Error: B should be A

Haxe print:
Run.hx:24: Error: Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
```

No diagnostics errors are reported.

When I touch Run.hx, I get the following output:

```
Haxe print:
Run.hx:19: A

Haxe print:
Run.hx:24: Error: B should be A
```

And for the two `new B()` I get red squiggly lines with `B should be A` and `Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>` respectively (i.e. the caught errors from the first run). Tested with 4.1.4 and  fb67f3c.

**Comment by kLabz** [comment]
Can you still repro on 4.3 nightlies?

**Comment by back2dos** [comment]
Same with 58e0b88. I should say that the output above is from `Haxe` in the VSCode output tab
![image](https://user-images.githubusercontent.com/509501/225832874-687462c2-d034-4657-ad9e-27fa1139838d.png)
I suspect there a ways to repro it in vim too ;)

It seems like on the very first diagnostics run I can catch the error, whereas on subsequent ones the compiler tries to recover by determining `A` to be the common type and printing the error directly. I would much prefer the former behavior, but Simn did point out that errors caught from `typeof` could actually originate from different module altogether. I did not grasp how/why this is ok in normal compilation but not for diagnostics. I guess there's some risk of module A being typed first and it having a macro that does `try typeof(macro B) catch (e:Dynamic) {}` thereby suppressing error reporting in B? Or something along those lines. Still feels like it should be possible to catch errors raised directly in the current module. In any case, the error always being uncatchable in diagnostics is still better, as its consistent.

**Comment by kLabz** [comment]
Don't even need an editor to reproduce...

```
haxe build.hxml --display "src/Main.hx@0@diagnostics"
src/Main.hx:19: A
src/Main.hx:24: Error: B should be A
[{"file":"/git/_tmp/haxe-playground/src/Main.hx","diagnostics":[{"kind":2,"severity":1,"range":{"start":{"line":10,"character":25},"end":{"line":10,"character":32}},"args":"Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>"},{"kind":2,"severity":1,"range":{"start":{"line":9,"character":25},"end":{"line":9,"character":32}},"args":"B should be A"}]}]
```

**Comment by back2dos** [comment]
Interesting. So does that mean that in server mode the behaviour is different or that vshaxe doesn't run diagnostics straight away?
