### ISSUE TITLE
Enforce property initialization to avoid assignement issues

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10035]
## Description

I had one issue when trying to instanciate an object which one of its property was not initialized. During an assignement (through a method call), I ran into an issue when the compiled code was interpreted.

## Steps to reproduce

1. Go to this minimal reproductible snippet: https://try.haxe.org/#91632
2. Notice the commented line 13
3. Hit "Build + Run"
4. Notice this error

>  Uncaught TypeError: Cannot read property 'h' of undefined

## Expected result

The compiler fails to compile if at least one (non static) property is not initialized in the constructor (wether by direct assignment or by defering the assignment to a method).

## Additional info

- **Haxe version**: 4.1.4
- **OS**: Alpine (using Docker haxe:4.1-alpine image)

**Comment by RblSb** [comment]
You can use `final` instead of `var` for such case. There is also experimental null safety feature: https://haxe.org/manual/cr-null-safety.html

**Comment by khalyomede** [comment]
Thanks @RblSb for pointing out null safety. I just updated the snippet to include the meta tag for every of the classes, but it looks like the bug still remains.

When you say about using `final` instead of `var`, could you please provide an example of code? I have some compilation error when I replace it in the snippet above.

I also edited my issue description with a suggestion in the description.

**Comment by kLabz** [comment]
Note that both final and null safety are not available on try.haxe as it uses a version < 4.0

**Comment by Simn** [comment]
I don't think there's an actual issue here because the mechanisms to help with this are already available.
