### ISSUE TITLE
Use expected return type to constrain type parameters?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10036]
Currently, the compiler fails to infer these function arguments:

```haxe
class Test {
  static function main() {
    (notThis(function (x) $type(x)):Int->Void); // Warning : Unknown<0>
    (notThat(function (x) $type(x)):Array<Int>); // Warning : Unknown<0>
  }
  static function notThis<T>(f:T->Void):T->Void
    return f;
    
  static function notThat<T>(f:T->Void):Array<T>
    return [];
}
```

Tested with nightly. Seems to have been the cases since [3.4](https://try.haxe.org/#eFA7f).

When the expected return type is known, the given return type (containing monomorphs) could be unified against it *before* proceeding to type the arguments. That would solve this issue. Not sure if this could break anything, as my attempts to construct such a case have thus far only resulted in headache.

**Comment by Simn** [comment]
This is interesting, but we have to be precise here: We cannot _unify_ before because that could lead to typing that's too narrow. However, we should be able to actually constrain the monomorph so that it comes out as `Unknown<0> : Int`. This would be the same as the type parameter being constrained to `Int`.

**Comment by Simn** [comment]
One thing to note: don't forget that function argument unification is contravariant, which might somewhat hide the "too narrow unification" problem. For this feature we also have to consider the return type side of things.

**Comment by back2dos** [comment]
For one, this is not really about function types:

```haxe
function hoho<X>(a:Array<X>):Array<X>
  return a;

function main()
  (hoho([2, 3]):Array<Float>); //  error: Int should be Float ... have: Array<Int> ... want Array<Float>
```

Without the wrapping `([2, 3]:Array<Float>);` works just fine of course, but top down inference is thrown off by the parametrized call.

----

Yes, I actually meant unifying. Constraining would cover a good chunk of the cases, but not all:

```haxe
class Test {
  static function main() {
    (create(function () return 2):Array<Float>);
    (notThat(function (x) trace(x == 2)):Array<Float>);
  }
  static function notThat<T>(f:T->Void):Array<T> {
    return [];
  }
  static function create<X>(f:Void->X):Array<X> {
    return [f()];
  }
}
```

Both fail, and constraining `X` or `Y` to `Float` would not change that, because then it can still get narrowed to `Int` in further inference and the error will be the same.

When discussing this with @Aurel300, he also argued that one might want the extra "wiggle room" to infer something narrower, although he didn't provide an example.

----

I consider this strictly an ordering issue. Right now, we unify arguments in order of appearance (before doing anything with the return type):

```haxe
function main()
  glargh(function (x) trace(x == 2), 3.4);// Float should be Int ... For function argument 'x'

function glargh<X>(f:X->Void, x:X)
  f(x);
```

If the user wants `X` to be `Float`, they have to add type annotation, as is always the case when inference falls short. Our current order puts arguments first and return type last. What I'm suggesting is to move the return type all the way to the front, because I'm leaning toward thinking it more often leads to the most sensible result:

1. We know *precisely* what the type of an expression should be (in this case `notThat(function (x) trace(x == 2))` *must* be an `Array<Float>` in the end).
2. The expression doesn't "escape" anywhere else, where its narrower type could be put to use.

If the compiler knows it wants a `Foo<Base>`, is there really a point in making a `Foo<?:Base>` in the first place? If it becomes `Foo<Sub>` then that'll be a type error anyway (unless Foo's parameter is covariant - which is by far not the general case). 

I managed to construct an example of code that would break with the change I propose:

```haxe
function main() {
  var s = new Sub();
  (foo({ t: s }, x -> x.isSub) : Foo<Base>);
}

function foo<X>(v:Foo<X>, callback:(x:X)->Void):Foo<X> {
  callback(v.t);
  return v;
}

class Base {}
class Sub extends Base {
  public final isSub = true;
  public function new() {}
}
typedef Foo<T> = {
  final t:T;
}
```

If anyone can come up with something less contrived, that would be very helpful. It does require the return type to be anonymous (structure or function) to get covariance.

I guess it comes down to deciding if this is rare enough to let users handle it by constraining the return type manually (in this case as `((foo({ t: s }, x -> x.isSub):Foo<Sub>):Foo<Base>)`). I would suggest it is.

**Comment by nadako** [comment]
> Without the wrapping `([2, 3]:Array<Float>);` works just fine of course, but top down inference is thrown off by the parametrized call.

This is the same as #8186, right?

**Comment by back2dos** [comment]
Indeed.
