### ISSUE TITLE
Multitarget completion

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10045]
Currently working on multitarget project feels messy. You need to change target every time you open server/client files to get completion, target-specific stuff is red and mixes with real errors in IDE, if you hide everything in #ifs - another target code is now transparent and shows only `Inactive conditional compilation block` on hover.
Simple example:
```haxe
class Main {
	static function main() {
		#if js
		new Client();
		#else
		new Server();
		#end
	}
}
// something below will be red
class Client {
	public function new() {
		js.Browser.window.console.log(1);
	}
}
class Server {
	public function new() {
		Sys.println("1");
		php.Global.echo("1");
	}
}
```

I want to propose special target, that can be used as display configuration:
```hxml
#multitarget completion
--completion
#or filtered to specific targets
--completion js php 
```
At this point you can get both (or more) target specific completion and no more `this target is not a system platform` error, if at least one of filtered target supports sys. Another option is detect all targets divided in hxml file by `--next` and allow target packages in completion, so a separate `completion.hxml` is not required.

### There is also possibility to make it smarter:

I think it should be possible to infer for what target `function` is related by using target-specific fields (from target package of code, something hidden in `#if target`, or variables with target-specific type)
```haxe
function foo() {
	js.Browser.window.console.log(1);
	// now function is js-specific
	// next line can show error:
	php.Global.echo("1");
	// can shows error if there is no allowPackage("sys"):
	Sys.println("1");
}
```
So, common field `foo()` will infer `js` target on `js` field usage, and can't be used anymore on `php` target fields. I hope that some part of this idea can be implemented and it will make one of the main pros of the language more convenient.

**Comment by back2dos** [comment]
Alternatively, the issue could be tackled in the language server, by allowing it to work with multiple builds simultaneously? 

This would launch a compilation server *per build*, each of which would identify the files relevant to that build. Diagnostics/completion would pick the right server(s) based on that information (probably will get slightly hairy around `#if`-regions). A good question would be what to do with files not used for any build (perhaps in "multi target mode" unused files could be all greyed out and inform the user that the file is unused).

**Comment by Simn** [comment]
Honestly, this would require the most evolved haxe-evolution ever. There are lots and lots of nuances to consider here, to the point where I don't think this is feasible at all.

I'm open to suggestions for making multi-target IDE support better, but frankly, I don't think this is it.
