### ISSUE TITLE
Haxe Iterator Issue

### ISSUE THREAD

**Issue by paulsgcross** [HaxeFoundation/haxe#10054]
Calling `array.iterator()` instantiates a new iterator each time. Instead, the iterator should be instantiated during array construction. Otherwise, this leads to unnecessary garbage collection during runtime. This issue may also be found in other classes, i.e. in `map.keyValueIterator()`. As Haxe is used for video game development, this causes framerate dropping.

**Comment by back2dos** [comment]
In typical usage, iterators are never allocated, because they're inlined.

Having a single iterator per array definitely isn't a good idea, because code like this would fail quite spectacularly:

```haxe
for (x in a) 
  for (y in a) 
    trace(x, y);
```

You can implement a resettable iterator for yourself, where you take care of not messing up the state. That said, if performance is a concern, I would eliminate iterator usage altogether.

**Comment by paulsgcross** [comment]
Many thanks, I appreciate the quick reply. However, I am confused. How is it possible not to use an iterator, when the expression 
```
for(i in 0...10) {
// Do something...
}
```
Returns an integer iterator? As Haxe does not support C-style for loops, am I forced to use a while loop?

**Comment by nanjizal** [comment]
You can create your own iterator so you don't have to recreate an iterator every time.

Here is one I have been experimenting with:

```Haxe
@:access(IntIterator.min, IntIterator.max )
class IntIterStart extends IntIterator {
    public var start: Int;
    public function new( min: Int, max: Int ){
        start = min;
        super( min, max );
    }
    inline
    public function reset(): IntIterStart {
        min = start;
        return this;
    }
}
@:access( IntIterator.min, IntIterator.max )
@:forward
abstract IteratorRange( IntIterStart ) from IntIterStart {
    public inline
    function new( min: Int, max: Int ){
        this = new IntIterStart( min, max );
    }
    @:from
    static inline
    public function fromIterator( ii: IntIterator ): IteratorRange {
        return new IteratorRange( ii.min, ii.max );
    }
    @:to
    function toIterStart():IntIterStart {
        return this.reset();
    }
    public var min( get, never ): Int;
    inline function get_min(){
        return this.min;
    }
    public var max( get, never ): Int;
    inline function get_max(){
        return this.max;
    }
    inline function set_max( v: Int ): Int {
        this.max = v;
        return v;
    }
    @:op(A + B) public static inline
    function adding( a: IteratorRange, b: IteratorRange ): IteratorRange {
          return a.add( b );
    }
    public inline
    function add( b: IteratorRange ): IteratorRange {
        var begin: Int = Std.int( Math.min( this.start, b.max ) );
        var end = ( begin == this.start )? b.max: this.max;
        return new IteratorRange( begin, end );
    }
    public
    var length( get, never ): Int;
    inline
    function get_length(): Int {
        return this.max - this.start + 1;
    }
    inline
    public function contains( v: Int ): Bool {
        return ( v > ( this.start - 1 ) && ( v < this.max + 1 ) );
    }
    inline
    public function isWithin( ir: IteratorRange ): Bool {
        return contains( ir.start ) && contains( ir.max );
    }
    @:op(A += B)
    public inline static
    function addAssign( a: IteratorRange, v: Int ){
        a.moveRange( v );
        return a;
    }
    @:op(A -= B)
    public inline static
    function minusAssign( a: IteratorRange, v: Int ){
        return a+=-v;
    }
    inline
    public function moveRange( v: Int ){
        this.start += v;
        this.max += v;
    }
    inline
    public function ifContainMove( v: Int, amount: Int ): Bool {
        var ifHas = contains( v );
        if( ifHas ) moveRange( amount );
        return ifHas;
    }
}

class Test {
    static function main() {
        new Test();
    }
    var iter: IteratorRange;
    public function new(){
        iter = 5...10;
        for( i in iter ){
            trace( i );   
        }
    trace(' ');
        iter -= 1;
        for( i in iter ){
            trace( i );   
        }
        iter.start = 0;
        iter.max = 100;
    trace(' ');
        for( i in iter ){
            trace( i );   
        }
    }   
}
```

Note if you wanted nested iteration you would declare two instances. In reality haxe optimises so you may find that new creation of iterator every loop in normal haxe with an array is far less generated code than you expect. Check Haxe's output code, certainly it turns everything into while loops and applies some analytics to reduce generation often to just property values? Did you explore generated binaries.

**Comment by paulsgcross** [comment]
> Note if you wanted nested iteration you would declare two instances. In reality haxe optimises so you may find that new creation of iterator every loop in normal haxe with an array is far less generated code than you expect. Check Haxe's output code, certainly it turns everything into while loops and applies some analytics to reduce generation often to just property values? Did you explore generated binaries.

Thanks. I did not explore any binaries but I'll have a look :)

**Comment by back2dos** [comment]
> How is it possible not to use an iterator, when the expression
>
> ```haxe
> for(i in 0...10) {
> // Do something...
> }
> ```
> Returns an integer iterator?

If you look at the generated code, you will see the iterator is optimized away (check the "JS Source" tab in https://try.haxe.org/#8aA38)

The same goes for arrays or maps. The iterator creating is optimized away.

```haxe
for (key => value in map) trace(key, value);
// becomes:
var i = map.keyValueIterator();
while (i.hasNext()) {
  var next = i.next();
  var key = next.key,
      value = next.value;
  trace(key, value);
}
```

If `keyValueIterator` is `inline` and returns an iterator with an inlineable constructor (i.e. `inline function new`), then haxe is capable of inlining away everything. This requires the concrete type of collection to be known. If you iterate over `Array`, `Map`, `Vector` and such, no iterator gets allocated and often even no functions are called. 

By "not using iterors" I mean that you should avoid iterating over general types like `Iterable`, `Iterator`, `KeyValueIterator` or `KeyValueIterable`, as Haxe loses information over the concrete type and therefore cannot inline things.

**Comment by nanjizal** [comment]
This seems an interesting fairly cheap way to save and reuse an IntIterator
https://gist.github.com/nanjizal/139d52f029744915c4c2b92889090989
I presume it works similar on C++, and you can change the min and max separately between calls without problems, not checked on 4.2 only on try.haxe.

**Comment by RealyUniqueName** [comment]
Nothing to do here.
