### ISSUE TITLE
Problem with overloading of compound assignment operators

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#10066]
Example:

```haxe
abstract Foo(Array<String>) from Array<String> {
  @:op(_ += _) inline function add(string: String)
    this.push(string);
}

function main() {
  var foo: Foo = [];
  foo += 'one'; // works
  foo += (1 == 2 ? 'two' : 'three'); // errors
}
```

Error:
```
Main.hx:9: characters 20-25 : String should be Foo
Main.hx:9: characters 28-35 : String should be Foo
Main.hx:9: characters 3-36 : Cannot add Foo and Foo
```

This concerns only compound assignment operators.

**Comment by Simn** [comment]
I have always struggled to understand in which cases the lhs is supposed to influence the typing of the rhs in the context of these operators. The underlying problem here is that the rhs is typed with an expected type of the lhs, and then unification fails.
