### ISSUE TITLE
haxe.Timer uses 100% CPU on some targets

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/haxe#10069]
I have tested the code below on Eval, JVM and Java targets using Haxe 4.1.5.
```haxe
class Bug {
    public static function main() {
        var timer = new haxe.Timer(10000);
        timer.run = () -> {};
    }
}
```
On **Eval** and **JVM**, the code will consume 100% CPU. On **Java** the CPU-usage is negligible.

Is this the expected behavior for sys targets (other than Java)?

**Comment by RealyUniqueName** [comment]
This seems to be fixed in development branch. Could you check with the latest dev build?

**Comment by anissen** [comment]
Yes, it does indeed appear to be fixed for Eval and JVM on the latest nightly build (`52e7ba5`).

Thanks! 🎉
