### ISSUE TITLE
[Feature Request] Translate from other programming languages to Haxe

### ISSUE THREAD

**Issue by zurgeg** [HaxeFoundation/haxe#10061]

**Comment by zurgeg** [comment]
oops, hit enter to early

**Comment by PXshadow** [comment]
I'm working on a project doing this, I think it's supported just not that documented, esentially you can create Haxe AST in Haxe (Exprs/Fields/TypeDefintions) and then use haxe.macro.Printer to be able to print out runnable Haxe code. The main challenge is obtaining the other language's AST and then being able to translate into Haxe's syntax tree.

**Comment by zurgeg** [comment]
> haxe.macro.Parser

@PXshadow Where would this be executed?

Additionally, a Python interpreter in Haxe could also work.

**Comment by PXshadow** [comment]
Executed within a program written in haxe you can do something like this.
```haxe
var printer = new haxe.macro.Printer();
printer.printExpr(expr); //Expr printed as a string
printer.printTypeDefinition(def); //Typedef printed as a string
```
To generate an Expr for instance I'd reccomend looking at the api and reading the comments https://api.haxe.org/haxe/macro/Expr.html

**Comment by RealyUniqueName** [comment]
Closing as there's nothing to do from the Haxe compiler's perspective.
