### ISSUE TITLE
[abstracts] failing operator overloading with extern function

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#10073]
Example:
```haxe
abstract Foo(Array<Int>) from Array<Int> {
  extern public function bar(other: Int): Int;

  @:op(_ + _)
  extern public function baz(other: Int): Int;
}

function main() {
  var foo: Foo = [];
  foo.bar(1); // works
  foo.baz(2); // fails 1
  foo + 3; // fails 2
}
```

Error 1 (for `foo.baz(2)`):
```
Main.hx:11: characters 7-10 : Field baz cannot be called directly because it has no expression
```

Error 2 (for `foo + 3`):
```
Main.hx:12: characters 3-10 : Cannot add Array<Int> and Int
```

So not only an operator overload is ignored, it also messes up a direct invocation.

Edit: so looking into the code found reference to #2344, and now i understand that an operator overload without expression  simply means that you want to forward that specific operator to an underlying type and there is no physical function for it. So in this context shown errors make sense - haxe thinks that there is no `baz`, so you cannot call it, and also it removes it in output simply leaving `foo + 3` intact, which produces the second error.

But this ignores case where there is `extern` modifier, which should communicate that there is an actual physical function involved (so haxe should allow to call it and replace an operator with its call).

**Comment by RealyUniqueName** [comment]
I think existing `extern` keyword should hint compiler to use an actual function instead of picking that op from an underlying type.

**Comment by vonagam** [comment]
Also my real use case in hashlink: 

```haxe
@:hlNative('my', 'vector2_')
extern abstract Vector2(hl.Abstract<'my_vector2'>) {
  @:op(_ + _)
  public function add(other: Vector2): Vector2; // this is for my_vector2_add in c
}
```

Which would have worked perfectly if not for old forwarding convention. If it was done today i would have proposed to introduce `@:forward.op` (as we have now other `forward.` metas) in place of `@:op` when one wants to delegate an operator to an underlying type. Intention is more clear and no ambiguity...

But explicitly adding `extern` to `add` is still better than writing additional private inline method for each operator.

Also now to think about it, not only `extern` should be an indicator of a physical field, but a `public` too. There is no point in having `public` access if there is no function to call, is there?

**Comment by RealyUniqueName** [comment]
Using visibility modifier for this seems confusing to me

**Comment by vonagam** [comment]
Well it is just about framing. If you frame it as "add public to mark physicality of field" - that's confusing, but if you say "an operator forwarding function cannot be public" - that (i hope) is not hard to get. (And based on code in haxe repository there is already such convention in place, just not enforced by compiler yet.)

Anyway, i myself do not use `extern abstract` combo often, so the issue can be closed when `extern` modifier is made forbidden with operator forwarding (which will happend when the PR is merged).

**Comment by vonagam** [comment]
Damn, extern methods are removed by filters from class even before they get to a target generator, so i cannot use it - hashlink will not generate native calls for them and jit will crash...
