### ISSUE TITLE
Add new static method php.Global.random_bytes

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10097]
## Description

I am targeting PHP, and I need to generate random secure string. I would like to beneficiate from the type checking and to be able to call `php.Global.random_bytes()`.

My goal is to generate impredictible string for setting an HTTP only cookie on the browser to identify a client session.

## Expected behavior

To be able to run the following code:

```haxe
class Main {
  public static function main() {
    final randomBytes = php.Global.random_bytes(16);
    final randomString = php.Global.bin2hex(randomBytes); // php.Global.bin2hex already exist
  }
}
```

## Alternatives solutions

I can use the following code to perform the same thing:

```haxe
class Main {
  public static function main() {
    final randomBytes = php.Syntax.code("random_bytes({0})", 16);
    final randomString = php.Global.bin2hex(randomBytes);
  }
}
```

**Comment by RealyUniqueName** [comment]
It already exists in development branch and will be released with Haxe 4.2
