### ISSUE TITLE
Add something like Context.reportError

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10096]
Currently, Context.error aborts the invoking macro with an exception (side note: it seems this is now uncatchable ... not sure if that's intended). In many cases it's useful to:

- report an error at multiple locations (as the compiler does for missing/incompatible interface fields)
- report an error but continue with the macro to be able to report subsequent errors too

There are a few roundabout ways to accomplish this, but something from the compiler would be nice.

**Comment by kLabz** [comment]
Maybe adding an optional bool argument to `Context.error` to skip the "and aborts the current macro call" part could be useful?

**Comment by Simn** [comment]
> Maybe adding an optional bool argument to Context.error to skip the "and aborts the current macro call" part could be useful?

This has control flow implications because technically `Context.error` should return the bottom type, whereas something like `reportError` should not.

**Comment by haxiomic** [comment]
I've always been little confused by this, I thought the distinction between `Context.error()` and `Context.fatalError()` would be that `fatalError()` would end the compilations immediately and `error()` would allow reporting multiple errors (as you describe reportError should work). At the moment they seem to behave the same so I've just been using `Context.error()`

Avoiding adding a new error function would be nice, but it would be a breaking change to make `error()` behave like `reportError()`
