### ISSUE TITLE
Purpose of the @:struct metadata in HL?

### ISSUE THREAD

**Issue by SunDaw** [HaxeFoundation/haxe#10095]
According to https://haxe.org/manual/cr-metadata.html annotating a class with `@:struct` *"Marks a class definition as a struct."*, however it is unclear what a "struct" is in HL.
Experimenting with it the metadata seems to remove type information from the generated code (which may also be the cause of https://github.com/HaxeFoundation/haxe/issues/10075?).
In HL/C this seems to only remove the `hl_type*` member from the generated `struct`, all other functionality seems to be mostly unchanged (i.e.: no value type semantics, unlike when applying this metadata when compiling to C#).
This raises the question: What exactly is the purpose of the `@:struct` annotation when targeting HL? When would it be useful? What is the expected behavior/what kind of code will no longer work when using it?

**Comment by Aurel300** [comment]
The intended use is to be able to declare types in Haxe/HL that align exactly with `struct`s declared in C headers (for example, DirectX). Without the metadata, all allocated objects will have the extra type field, as you observed. Allocating normally, then referencing 8 bytes (1 word) into the object would not work nicely with the current garbage collector.

**Comment by SunDaw** [comment]
Thank you for the fast response
Is there any code example of such usage (I wasn't able to find anything)?
And could the documentation on the previously linked site be updated to include something about this (or link to some other page with more details)? IMO it's confusing for the HL target in the current form

**Comment by Aurel300** [comment]
You're right, I expected at least one usage in `hlsdl` or `hldx`, but no luck. I'm guessing @ncannasse would know better if this is used in any public code?

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/hashlink/wiki/Advanced-features#structs
