### ISSUE TITLE
Wrong generated output from js.html.ScrollIntoViewOptions "_inline" field

### ISSUE THREAD

**Issue by cambiata** [HaxeFoundation/haxe#10093]
The following code
```haxe 
import js.html.ScrollIntoViewOptions;
import js.html.ScrollLogicalPosition;
function main() {
	var testElement = document.createDivElement();
	testElement.scrollIntoView({
		_inline: ScrollLogicalPosition.CENTER  // <----- "_inline"
	});
}
```
...with the following typedef...
```js 
// This file is generated from mozilla\Element.webidl. Do not edit!
package js.html;

typedef ScrollIntoViewOptions = ScrollOptions & {
	var ?block:ScrollLogicalPosition;
	@:native("inline") //                <---
	var ?_inline:ScrollLogicalPosition;
}
```
...should - because of the `@:native("inline")` - generate a field with the name "inline", shouldn't it?

However, the generated code has the untransformed field name "_inline", witch of course does not work:

```haxe 
// Generated by Haxe 4.2.0-rc.1+2776f3cd4
(function ($global) {"use strict";
	function App_main() {
		var testElement = window.document.createElement("div");
		testElement.scrollIntoView({ _inline: "center" });   // <-------- should be "inline", not "_inline"
	}
});
```
It seems that the `@:native("inline")` isn't taken into account by the compiler?!

**Comment by kLabz** [comment]
> shouldn't it?

No, it doesn't work on typedef. There are several discussions about it, I'll try to find one.
Edit: this may be the main one https://github.com/HaxeFoundation/haxe/issues/5105

**Comment by cambiata** [comment]
Ah, thanks! Will try to implementera an abstract solution for now... Closing this
