### ISSUE TITLE
Override the default toString function of an enum

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10091]
Currently there seems no way to override the default `toString` behaviour of enum that would work with `Std.string()`

```haxe
class Main {
	static function main() {
		final e = Integer(16);
		trace(e.toString()); // static extension works
		trace(Std.string(e)); // but can't override the default toString impl
	}
}

class EntryValueTools {
	public static function toString(v:EntryValue) {
		return switch v {
			case Integer(i): 'Integer(0x${StringTools.hex(i, 2)})';
		}
	}
}

@:using(Main.EntryValueTools)
enum EntryValue {
	Integer(i:Int);
	
	// public function toString():String; // perhaps support toString function inside enum itself?
}
```

ref: https://github.com/HaxeFoundation/haxe-evolution/issues/10

**Comment by RealyUniqueName** [comment]
What's the point of `Std.string(e)` here instead of just tracing `e`?
I guess the only case for that is when the type of `e` is not known to be the enum at compile time.

**Comment by back2dos** [comment]
I guess the point is that as soon as you want to trace something that contains the enum, e.g. `Array<EntryValueTools>`,  the static extension isn't used.

**Comment by Simn** [comment]
`Std.string(e)` is nothing more than a run-time call so of course static extensions don't apply.

This would be a new feature where the printing implementation somehow routes to a custom function for enums. On some targets we might be able to cheat by actually injecting `toString` methods into the generated code, but eeeh...

Either way, this would require a haxe-evolution that considers all targets, and probably also the `"" + enum` situation. I agree that this would be nice to have, but it's going to require quite a bit of effort.
