### ISSUE TITLE
Null access exception and call stacks

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10109]
Using Haxe 4.0 , the following example:

```haxe
enum Stop {
	A;
}

class Test {

	static function foo( o : String ) {
		return o.length;
	}
	
	static function main() {
		try {
			foo(null);
		} catch( e : Stop ) {
		}
	}

}
```

Display this error:

```
Uncaught exception: Null access
Called from $Test.foo(Test.hx:8)
Called from $Test.main(Test.hx:13)
Called from $Test.main(Test.hx:12)
Called from fun$335(?:1)
```

Whereas in Haxe 4.1.4 it now displays:

```
Uncaught exception: Null access
Called from $Test.main(?:1)
Called from fun$382(?:1)
```

We lost the whole stack, because for some reason we don't use rethrow opcode or throw another exception when filtering the exception when checking for Stop type.

**Comment by RealyUniqueName** [comment]
Which target?

**Comment by Aurel300** [comment]
I think the `fun$...` and `rethrow opcode` refer to HashLink?

**Comment by ncannasse** [comment]
The problem is that Haxe is now generating:

```
catch( e : Dynamic ) {
    if( !Std.isOfType(e,Stop) ) throw e;
}
```

Whereas for HL it should instead of `throw` do a `hl.Api.rethrow(e)` in order not to reset the native exception stack. That was t

@RealyUniqueName could you fix this and make a 4.1 release update with the fix ? it's quite urgent as we get numerous bugs that are very hard to solve because of this issue which prevent us to get full stack frame. (there are two instances of TThrow in `filters/exceptions.ml`, I think the two in catch handling should do that)

**Comment by RealyUniqueName** [comment]
@ncannasse do you need a real release of 4.1 with the exceptions stacks fix? I'm going to release 4.2.1 later this week with fixes for MainLoop and exception stacks (already in 4.2_bugfix branch).
Patched builds of 4.1 are already available at https://build.haxe.org/

Mac installer: https://build.haxe.org/builds/haxe/mac-installer/haxe_2021-02-25_4.1_bugfix_dbace6d.tar.gz
Win64 installer: https://build.haxe.org/builds/haxe/windows64-installer/haxe_2021-02-25_4.1_bugfix_dbace6d.zip
Win64 choco: https://build.haxe.org/builds/haxe/windows64-choco/haxe.4.1.5-SNAP20210225112154.nupkg
Win32 installer: https://build.haxe.org/builds/haxe/windows-installer/haxe_2021-02-25_4.1_bugfix_dbace6d.zip
Win32 choco: https://build.haxe.org/builds/haxe/windows-choco/haxe.4.1.5-SNAP20210225112154.nupkg
Linux 64: https://build.haxe.org/builds/haxe/linux64/haxe_2021-02-25_4.1_bugfix_dbace6d.tar.gz

**Comment by ncannasse** [comment]
I still have an issue as the exception is still not correctly reported in debugger, because you're inject Ast.null_pos instead of using the catch position.

For instance the `-D dump` shows the following in `dump/hlcode.txt`:

```
		.12    @0 trap 0, 4
		.13    @1 null 3
		.13    @2 call 2, Test.foo(3)
		.13    @3 endtrap true
		.13    @4 jalways 8
	; ?:1
		.1     @5 null 4
		.1     @6 call 6, haxe.Exception.caught(0)
		.1     @7 nullcheck 6
		.1     @8 callmethod 4, 6[0]()
		.1     @9 global 7, 16
	; Test.hx:14
		.14    @A call 5, Std.isOfType(4,7)
		.14    @B jtrue 5,1
	; ?:1
		.1     @C rethrow 0
	; Test.hx:15
		.15    @D ret 1
```

The  ?:1 parts prevent the debugger from reading the stack frame, could you fix by using correct position ?

**Comment by RealyUniqueName** [comment]
@ncannasse 
Mac installer: https://build.haxe.org/builds/haxe/mac-installer/haxe_2021-02-27_4.1_bugfix_47239ca.tar.gz
Win64 installer: https://build.haxe.org/builds/haxe/windows64-installer/haxe_2021-02-27_4.1_bugfix_47239ca.zip
Win64 choco: https://build.haxe.org/builds/haxe/windows64-choco/haxe.4.1.5-SNAP20210227153259.nupkg
Win32 installer: https://build.haxe.org/builds/haxe/windows-installer/haxe_2021-02-27_4.1_bugfix_47239ca.zip
Win32 choco: https://build.haxe.org/builds/haxe/windows-choco/haxe.4.1.5-SNAP20210227153259.nupkg
Linux 64: https://build.haxe.org/builds/haxe/linux64/haxe_2021-02-27_4.1_bugfix_47239ca.tar.gz
