### ISSUE TITLE
Suggestion: cpp Int64 should not implicitly cast to Int32

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#10108]
Currently [Int64](https://github.com/HaxeFoundation/haxe/blob/b37e43d75dc0571391ecff70b6b9b07a9c12e0ae/std/cpp/Int64.hx#L25) and [UInt64](https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/UInt64.hx) on the C++ target will silently cast to Int (32 bits) which is a lossy operation

This can causes subtle problems that may only be discovered much later at runtime, for example, haxe will happily create `new Map<cpp.Int64, T>()`  but silently truncate the Int64s to Int32

Or implicitly cast to haxe.Int64 but convert to Int32 in the process ([fixed now](https://github.com/HaxeFoundation/haxe/issues/10100))

On other platforms (like [CS](https://github.com/HaxeFoundation/haxe/blob/development/std/cs/StdTypes.hx#L31)) explicit casting is required

I suggest removing the `to Int` from these types – this will be a breaking change but the new errors will hopefully point out potential bugs

If people are happy with this change I'll go ahead and make a PR + tests

**Comment by Aidan63** [comment]
I think this would be a good idea. I ran into this Int64 truncating as well in my native Int64 pr where maps with Int64 keys would get generated as IntMaps.

**Comment by RealyUniqueName** [comment]
I doubt we can change this on `haxe.Int64` or any other existing type as it would be too breaking IMO (at least until Haxe 5).
But I agree such conversions should be explicit.

**Comment by haxiomic** [comment]
Made a PR #10133 
Fortunately `haxe.Int64` already requires an explicit cast (as does eval's, CS and Java's types) so no changes there, it's just cpp and hl that are implicit
