### ISSUE TITLE
@:using typedef cascading signatures loop

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#10107]
The ability for typedefs to use @:using is extremly helpful for what I'm working on, I have run into a little restriction though. Similar to #2563

```haxe
@:using(Main)
typedef B = {
    >A,
};
typedef A = { };
```
``error: Loop found in cascading signatures definitions. Please change order/import``

The work around: 

```haxe
@:using(Main)
typedef B = _B;
typedef _B = {
    >A,
};
typedef A = { };
```

If it's to much hassle to remove the restriction, don't worry about it, cheers!

**Comment by Simn** [comment]
That looks like a very unfortunate interaction that should be fixed. It suggests that `@:using` causes some typing which it shouldn't cause. This could lead to all sorts of weird errors, so something has to be delayed here.

**Comment by Simn** [comment]
Interestingly, there's a comment in typeload.ml that says `(* delay the using since we need to resolve typedefs *)`. However, it doesn't seem to actually delay anything...
