### ISSUE TITLE
Can Haxe create native binaries for each platform?

### ISSUE THREAD

**Issue by UltraBurstXD** [HaxeFoundation/haxe#10113]
Hi, I only want to know if haxe can create native binaries for Linux distro (*.deb or *.rpm)?

**Comment by kLabz** [comment]
Hi!
Sure, you can target "native" with cpp target.
You'll have to handle the packaging (deb, rpm, etc.) yourself though

**Comment by UltraBurstXD** [comment]
OK... but are there built-in tools that help "handle" executable binaries.

**Comment by RealyUniqueName** [comment]
deb and rpm are not executable binaries, but archives containing such binaries. Haxe can produce binaries, but doesn't provide any tooling to package them into deb or rpm. You'll have to do that using whatever tooling provided by related Linux distros.
