### ISSUE TITLE
haxe crashing on macos 10.13(.6)

### ISSUE THREAD

**Issue by gepatto** [HaxeFoundation/haxe#10110]
Haxe 4.2.0 crashes on macos 10.13.6  

reproduce:

`haxe -v`

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by Aurel300** [comment]
I assume you are using a binary from the CI? We might need to use `-mmacosx-version-min` and specify a reasonable minimum version. It seems badly documented, but some resources [here](https://opensource.apple.com/source/xnu/xnu-2050.18.24/EXTERNAL_HEADERS/Availability.h.auto.html) and [here](https://stackoverflow.com/questions/2923502/what-does-macosx-version-min-imply).

**Comment by gepatto** [comment]
I used the binary from the installer from haxe.org:
https://haxe.org/download/file/4.2.0/haxe-4.2.0-osx-installer.pkg

I'm still running macos 10.13 because I can't upgrade on my older macbook 2011.
10.13 is still getting security updates so for me 10.13 would be a  reasonable minimum version.

**Comment by RealyUniqueName** [comment]
@gepatto please, try this one and let us know if it works for you: https://build.haxe.org/builds/haxe/mac-installer/haxe_2021-02-10_fix-macos-10.13_d0ac021.tar.gz

**Comment by gepatto** [comment]
Unfortunatley it doesnt:

```
haxe -v
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/haxe (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6```

[crash_report.txt](https://github.com/HaxeFoundation/haxe/files/5958642/crash_report.txt)

**Comment by RealyUniqueName** [comment]
@gepatto try this: https://build.haxe.org/builds/haxe/mac/haxe_2021-02-24_fix-macos-10.13_8d5dced.tar.gz

**Comment by gepatto** [comment]
confirming that  4.3.0-rc.1+8d5dced works again on macos 10.13(.6)

**Comment by stephensmith9** [comment]
Downloaded the 2022-03-06 4.2.5 Haxe installer for MacOS. I have 10.13.6 like the OP. It gives the same error. Was the Hotfix not applied to newer versions? (I know, I need a newer MacBookPro, just can't afford one right now)
