### ISSUE TITLE
[swf] Null object reference on trace (through swc)

### ISSUE THREAD

**Issue by Adolio** [HaxeFoundation/haxe#10117]
Hello world,

I'm trying to get familiar with Haxe (v4.1.5) by doing a simple "Hello World!" and use it in an AS3 project (through a SWC library).

I get the following error when trying to trace something:

```
Exception has occurred.
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at flash::Boot$/getTrace()
	at flash::Boot$/__trace()
	at MethodInfo-5985()
	at HelloWorld/print()
	at ch.adolio.test::HelloWorldFromHaxeTest()[c:\Users\...\Development\AIR\Starling-Sandbox\src\ch\adolio\test\HelloWorldFromHaxeTest.as:10]
	...
```

HelloWorld.hx:

```hx
package;

class HelloWorld
{
	public static function main()
	{

	}

	public function print():Void
	{
		trace("Hello World!");
	}
}
```

Haxe compiler command:

`haxe.exe -p ./src --swf ./bin/HelloWorld.swc -m HelloWorld`

HelloWorldFromHaxeTest.as:

```as3
package ch.adolio.test
{
	import starling.display.Sprite;

	public class HelloWorldFromHaxeTest extends Sprite
	{
		public function HelloWorldFromHaxeTest()
		{
			var helloWorld:HelloWorld = new HelloWorld();
			helloWorld.print();
		}
	}
}
```

I'm new here, I'm maybe doing something wrong...

Thanks for your help.

**Comment by Simn** [comment]
Check out http://old.haxe.org/manual/swc#using-a-haxe-swc-in-as3 and see if that helps.

**Comment by Adolio** [comment]
Thank you @Simn 😀

The following lines were missing in the AS3 part:

```as3
// new MovieClip is passed to haxe code to populate
// the flash.Lib.current reference. Note, if your
// Haxe code uses flash.Lib.current.stage, you may
// need to add this movieclip to the stage.
var mc:MovieClip = new MovieClip();
stage.addChild(mc);
haxe.initSwc(mc);
```

For anyone having this issue I recommend having also a look to this example: https://github.com/jcward/HaxeSWCExample
