### ISSUE TITLE
new method EReg.allMatches

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10116]
## Description

I have a string representing an URL. It can contains placeholders, and I call them "routes":

```haxe
final route = "/manufacturer/{manufacturer}/product/{product}"; // Shows the product "P" of manufacturer "M"
```

I have a system that matches any incoming URL and triggers a callback

```haxe
import Router;
import ShowProductController;

Router.addGetRoute("/manufacturer/{manufacturer}/product/{product}", ShowProductController);
```

So that this route will match these URLs for example:

- /manufacturer/12/product/15
- /manufacturer/100/product/2
- ...

In the controller, I would like to get all placeholders, so I am using this regular expression:

```haxe
final url = "/manufacturer/12/product/15";
final regularExpression = new EReg("^/manufacturer/([^;/?:@&=+$,]+)/product/([^;/?:@&=+$,]+)", "gi");
var parameters: Array<String> = [];

if (regularExpression.match(route)) {
    trace(regularExpression.matched(1)); // 12
    trace(regularExpression.matched(2)); // 15
    trace(regularExpression.matched(3)); // "Uncaught exception Invalid group"
}
```

In this case, I know how many placeholders I will have. In a real world usage, the algorithm will not know in advance how many placeholders the routes will have:

- /company/{company}
- /account/{account}/company/{company}/price-list/{price-list}
- ...

## Expected behavior

I would like to access all matches in a single call:

```haxe
final url = "/manufacturer/12/product/15";
final regularExpression = new EReg("^/manufacturer/([^;/?:@&=+$,]+)/product/([^;/?:@&=+$,]+)", "gi");

if (regularExpression.match(route)) {
   final matches = regularExpression.allMatches(); // ["/manufacturer/12/product/15", "12", "15"];
}
```

## Alternative solution

I loop through every matches untill I encounter an exception

```haxe
final url = "/manufacturer/12/product/15";
final regularExpression = new EReg("^/manufacturer/([^;/?:@&=+$,]+)/product/([^;/?:@&=+$,]+)", "gi");
var parameters: Array<String> = [];

if (regularExpression.match(url)) {
  trace("regular expression do match");

  var matchesRemains = true;
  var index = 1;

  while (matchesRemains) {
    try {
      parameters.push(regularExpression.matched(index));
    } catch (exception) {
      matchesRemains = false;

      break;
    }

    index++;
  }

  trace(parameters); // [12, 15]
}
```

**Comment by nanjizal** [comment]
I wondering can you not just abstract over EReg and provide a method to deal with an array and just put a loop in it, not really big user of EReg ported this js.
https://github.com/nanjizal/webgl-example/blob/master/src/webglExample/geometry/GeometryParser.hx
But I am wondering how useful it would really be, surely allMatches is just one of many specific use cases, and many EReg uses are more complex that just one check.
But ERegs can be a bit slow I know donaldson has been looking at other parsing approaches that will be more efficient so maybe haxe will move away from normal ERegs anyway.

**Comment by back2dos** [comment]
Could be useful, but in this case you know from the original pattern how many matches you'll have. [Example](https://try.haxe.org/#355E7):

```haxe
class Test {
  static function main() {
    var m:Matcher = '/manufacturer/{manufacturer}/product/{product}';
    trace(Std.string(m('/manufacturer/100/product/2')));// [{ name : manufacturer, value : 100 },{ name : product, value : 2 }]
  }
}

@:callable
abstract Matcher(String->Null<Array<{ name:String, value:String }>>) {
  inline function new(f) this = f;
  @:from static function fromPattern(s:String) {
    var parts = s.split('{');
    var names = [];
    for (i in 1...parts.length) {
      var part = parts[i];
      switch part.indexOf('}') {
        case -1: throw 'unclosed { in $s';
        case close: 
          names.push(part.substr(0, close));
          parts[i] = "([^;/?:@&=+$,]+)" + part.substr(close + 1);
      }
    }
    var r = new EReg(parts.join(''), 'gi');
    return new Matcher(function (url) 
      return 
        if (r.match(url)) 
          [for (i in 0...names.length) { name: names[i], value: r.matched(i + 1) }]
        else null
    );
  }
}
```

**Comment by Simn** [comment]
This would have to go through https://github.com/haxefoundation/haxe-evolution, but to be honest I doubt that we would accept it. Making changes to the regular expression API is often a rather involved effort.
