### ISSUE TITLE
confusing error message with mistaken extra bracket.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#10129]
This typo where I missed commenting out a '{' resulted in a rather criptic error message that referenced the next method.

**_public modifier is not supported for module-level fields_**

```Haxe
    public function drawTri( points:Array<Float> ){
        //if( _inFillingMode ){
            sketch.moveTo( points[0], points[1] );
            sketch.lineTo( points[2], points[3] );
            sketch.lineTo( points[4], points[5] );
            sketch.lineTo( points[0], points[1] );
        /*} else {
            pen.addTriangle( points[0], points[1]
                           , points[2], points[3]
                           , points[4], points[5] );
       */ }
    }
```
Are error messages covered in the manual, because messages like this are tricky to understand so hard to rule out as the cause. Are there a list of new haxe4.2 errors with some links to terms or something.

**Comment by Simn** [comment]
This isn't about extra brackets but about you having `public` outside a class. Not sure what else we could even say about this in the error message...

**Comment by nanjizal** [comment]
It's not uncommon for a bracket mistake of a user in haxe to be reported as a line number of a subsequent method, so the Haxe user looks at the wrong method for the mistake, would a backwards pass of the method be viable to enable the compiler to better locate user error rather than just AST ones, or using method indent details as I suspect most users indent all methods, so compiler could better bisect the closest method of the mistake rather than sometimes error on the next method.

Thanks for taking a look, feel free to close, it would be nice to have more error message information documentation, and better bracket checking but understand if this is not deemed current priority.

**Comment by back2dos** [comment]
Well, before it used to be "unexpected public", so it definitely didn't get any worse.

> Not sure what else we could even say about this in the error message...

If the offending `public` (or `private`) is preceded by a class/abstract, we could use its position (more specifically its end) to report something like "possible stray closing bracket".

Consider this:

```haxe
class Foo {
  public function whoops() {}}
  function bar() {
    // lots of stuff here
  }
  function boink() {
    // lots more of stuff here
  }
  public function hoho() {}
}
```

Being pointed to the second closing brace in `whoops` would definitely be helpful.

**Comment by Simn** [comment]
There's no way the parser could report that particular brace unless we start making whitespace assumptions, which I don't want to do. Also, in my experience such "helpful" parser errors tend to end up triggering in scenarios where they make no sense.

I'll close this as I don't think we have to take any action here.

**Comment by nanjizal** [comment]
I think that a partial reverse parse of the class would suggest the error forward, that information would allow an error on the appropriate method without use of whitespace. It seems that it should be possible to check the forwards and backwards validity of brackets and when errors exist locate the correct method. Is it feasible to reverse the parsing approach and add such a check on an error.

**Comment by nanjizal** [comment]
I think bracket mistakes are common so it would be huge win if compiler detection was improved, but I have no idea how feasible it would be to implement reverse/semi reverse parse.

**Comment by nadako** [comment]
``
