### ISSUE TITLE
Error when colon is included in a string

### ISSUE THREAD

**Issue by johndunlap** [HaxeFoundation/haxe#10126]
![image](https://user-images.githubusercontent.com/35973146/108402816-a08c5b80-71e3-11eb-8cd2-985ef13ebad7.png)
Error text:
`Error: (src/Main.hx:3: Name changed) Hamilton Osborn`

Main.hx:
`class Main {
    static public function main() {
        trace("Name changed : Hamilton Osborn");
    }
}
`
build.hxml:
`-cp src
-D analyzer-optimize
-main Main
--interp
`
Haxe version: 4.0.5

**Comment by Simn** [comment]
This is a problem with your IDE.

**Comment by johndunlap** [comment]
You are correct. Thank you for your quick response!
