### ISSUE TITLE
Assignment Overloading Is Not Supported

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/haxe#10125]
Hello,

I'm trying to use op(A=B) on an abstract. But whatever I try it does not seem to work. Is the assignment operator on abstracts still supported? How must one use it? Here is an example.

    @:forward abstract MyInt(Int) {
        public inline function new(value: Int = 0) {
            this = value;
        }
    
        @:to inline function toInt(): Int {
            return this;
        }
    
        @:op(A=B) static inline function opAssign(A: MyInt, B: Int): Int {
            // IMPLEMENTATION (this is just a test)
            // compiler says: "Assignment Overloading Is Not Supported"
            return 0;
        }
    }

I was inspired to use :op(A=B) from this link: http://haxedev.wikidot.com/article:operator-overloading don't know if it's part of your official documentation - wouldn't surprise me if it's not. Currently I'm assuming that this was maybe a feature in the past but was removed.?

Many thanks on any help on this!

-- Using haxe 4.2.0

**Comment by RealyUniqueName** [comment]
Assignment overloading is not supported atm.
And that's not a part of our official documentation.
You can read a discussion on the topic in #5738
