### ISSUE TITLE
[ide] no static extension completion for overloaded methods

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#10120]
```haxe
using Main.Tools;

class Tools {
	public static extern inline overload function getOrZero<K>(map:Map<K,Int>, key:K):Int {
		var value = map.get(key);
		return if (value != null) value else 0;
	}

	public static extern inline overload function getOrZero<K>(map:Map<K,Float>, key:K):Float {
		var value = map.get(key);
		return if (value != null) value else 0.0;
	}

}

function main() {
	var m = ["a" => 1.1, "b" => 2.3];
	m.|
}
```

The dot completion here doesn't include the `getOrZero` method, however if we change the declaration order so the `Float`-version of `getOrZero` comes first - it starts appearing. Alternatively, if the change `m` to be `Map<String,Int>` (by using int literals) - it will also show `getOrZero`. This suggests that the static extension completion doesn't consider overloads and simply checks whether the first method is suitable for the type.

**Comment by Gama11** [comment]
Duplicates #10004?

**Comment by nadako** [comment]
Hmm, probably?
