### ISSUE TITLE
Accessing private types from outside their module.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10138]
Could this be allowed with full paths in conjunction with `@:privateAccess`?

**Comment by Gama11** [comment]
I guess supporting it for `@:privateAccess` only rather than `@:allow` / `@:access` could side-step the path concerns mentioned in https://github.com/HaxeFoundation/haxe/issues/5731#issuecomment-416028070?

**Comment by RealyUniqueName** [comment]
I guess the main reason for the request is to make a type "private to package". And I agree we need something to allow that.
But `@:privateAccess` doesn't look like a good fit for that: `static var v:@:privateAccess Module.PrivateType;`.
And IIRC we don't support metas in type hints.

I think `@:allow/@:access` is a better choice, but it's already rejected as pointed by Gama11. 
Maybe we can come up with a better idea?

**Comment by Simn** [comment]
I think we can close this in favor of #11079, which has a bit more information.
