### ISSUE TITLE
[lua] String.split null-safety error

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10136]
```haxe
@:nullSafety(Strict)
function main() {
	"path".split("."); // Null safety: Cannot assign nullable value here.
}
```
`split` is kind of fat and inlined (probably bad?) and no any error inside of method. Works fine without inline.

**Comment by RealyUniqueName** [comment]
What target?

**Comment by RblSb** [comment]
Fixed in #10081, but seems like `_std` methods are not checked by NullSafety, except when they are inline, so errors showed only on call-site for such case. Not big deal for current time.

**Comment by jdonaldson** [comment]
Yeah, let me try de-inlining some of the std String methods.  That's too much code to generate.

**Comment by danielo515** [comment]
What is the status of this?
