### ISSUE TITLE
Method php.Global.mb_strlen signature does not match PHP doc signature

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10132]
## Description

The haxe signature for [`php.Global.mb_strlen()`](https://api.haxe.org/php/Global.html#mb_strlen) shows it can return Int or Bool

```haxe
mb_strlen(str: String, ?encoding: String): EitherType<Int, Bool>
```

But the PHP signature for [`mb_strlen()`](https://www.php.net/manual/en/function.mb-strlen.php) shows it can only return Int

```php
mb_strlen(string $string, string|null $encoding = null): int
```

## Expected behavior

The haxe signature is

```haxe
mb_strlen(str: String, ?encoding: String): Int
```

## Additional information

Is it something hidden in the PHP doc that this method might actually return a bool value in case of error? Or is it an old PHP behavior?

**Comment by RealyUniqueName** [comment]
It's because in PHP7 it emits `E_WARNING` and actually returns `false` on invalid encoding. But I guess we can change return type as suggested because Haxe transforms PHP warnings into exceptions.
