### ISSUE TITLE
A setting to limit multiline errors to the first line

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#10130]
https://github.com/vshaxe/vshaxe/issues/388#issuecomment-782286547

**Comment by Simn** [comment]
I guess we can close this with new rudy-mode errors?

**Comment by kLabz** [comment]
Hmm yeah we can keep track of it on vshaxe side only (even though I might have to adjust diagnostics a bit on compiler side), which I hope to handle in the coming weeks.
