### ISSUE TITLE
Dynamic false == ""

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10140]
Hi,

I know we must using Dynamic with care but is that a normal behaviour here please ? 
```haxe
class Test {
    static function main() {
        var o : Dynamic = false;
        trace( o == "" ); // true
    }
}
```

**Comment by Simn** [comment]
Yes, if you compile stupid code to stupid targets you get stupid results.

**Comment by filt3rek** [comment]
Many thanks Simon for your relevant answer
