### ISSUE TITLE
Std.parseInt(x) returns null if x is a number, but Std.parseFloat returns the number

### ISSUE THREAD

**Issue by gene-pavlovsky** [HaxeFoundation/haxe#10142]
There are two related issues for parseInt(x) return null if x is a number (not a string):
#9112
#9587

The issues were closed without action, with this reasoning given:
```
Int and String are completely unrelated types.
Std.parseInt() expects a string. A value of any other type is unspecified behavior.
It's up to you to validate your dynamic data.
And the fact you get Std.parseInt(100) == 100 in some targets is just an accident.
```

The Std.parseFloat, though, doesn't return null when given a number, it returns the number as is.
By the above logic, shouldn't haxe introduce another breaking change and return null for parseFloat as well?

Test code:
```
class Main {
	static function main() {
		var a:Dynamic = 11;
		trace(Std.parseInt(a)); // haxe 4.0.0 - 11, haxe 4.1.5 - null
		trace(Std.parseFloat(a)); // haxe 4.0.0+ - 11
	}
}
```

**Comment by RealyUniqueName** [comment]
Number is not a string. `parseInt` and `parseFloat` require strings for their arguments. Some dynamic targets may coerce types automatically. Other targets don't do that. There's nothing to change in our implementation of `parseFloat`. You have to verify your data before using it. Otherwise pray for mercy of javascript runtime.

**Comment by Gama11** [comment]
>By the above logic, shouldn't haxe introduce another breaking change and return null for parseFloat as well?

No, "unspecified behavior" simply means "you can't rely on this behavior". So the result can vary across Haxe versions, across targets, or even similar methods on the same target and same Haxe version. 

Also, it's not really a "breaking change" if the behavior was unspecified.
