### ISSUE TITLE
[null safety] Possible null safety hole with structs and/or monomorphs

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#10147]
I saw a post on reddit that suggested that using structs can sometimes evade the compile-time null safety checks.

```haxe
typedef HasAString = {
  theString : String
}
// [...]
var has : HasAString = { theString: null };  // compiles with @:nullSafety(Strict)
```

I have also been able to reproduce it without the typedef, although with a more obvious intermediate `{ text : Unknown<0> }` monomorph:

```haxe
var tmp = { text: null };
var typed_receiver: { text : String } = tmp;  // compiles with @:nullSafety(Strict)
trace(typed_receiver.text.length);  // throws at runtime: TypeError: null has no properties
```

Oddly, the follow still isn't allowed to compile, as desired:

```haxe
var typed_struct: { text: String } = { text: null };  // ERROR: Null safety: Cannot assign nullable value here.
```

Related: [r/haxe: Null safety in structs](https://www.reddit.com/r/haxe/comments/lummvg/null_safety_in_structs/)
Related: [original example, on try-haxe](https://try.haxe.org/#E075bdF3)
Related: [other examples, on try-haxe](https://try.haxe.org/#3946073f)

**Comment by RblSb** [comment]
More cases:
```haxe
typedef HasAString = {
	text:String
}
typedef HasANullString = {
	text:Null<String>
}

@:nullSafety(StrictThreaded)
class Main {
	static function main() {
		final has:HasAString = {text: null};

		final tmp = {text: null};
		final typed:HasAString = tmp;

		final tmp = {text: null};
		final typed:{text:String} = tmp;

		final tmp = {text: null};
		final arr:Array<String> = [tmp.text];

		// should pass
		final tmp = {text: null};
		final typed:{text:Null<String>} = tmp;
		final typed2:HasANullString = tmp;
		final typed3:HasANullString = typed;
	}
}
```

My solution for `nullSafety.ml`, in `method private check_expr e`:
```ocaml
| TObjectDecl fields ->
	List.iter (fun ((name,pos,_), e) ->
		begin match e.etype with
			(* Field type still Unknown *)
			| TMono r when r.tm_type = None -> ()
			| _ ->
				if not (self#can_pass_expr e e.etype e.epos) then begin
					self#error ("Cannot use nullable value as an field of type " ^ (str_type e.etype)) [e.epos; pos];
				end;
		end;
		self#check_expr e
	) fields
```
It will report it like that, which is not that good, maybe.
<img width="679" alt="image" src="https://user-images.githubusercontent.com/8753432/143490748-3bfc7f9e-5c85-465d-8f74-d5d85b0ef271.png">

**Comment by RealyUniqueName** [comment]
It happens because Haxe doesn't add `Null<>` to `tmp.text` while typing. Instead `tmp.text` becomes just a monomorph (`Unknown` instead of `Null<Unknown>`).
I remember discussing this behavior in relation to local vars (`var s = null` also typed without `Null<>`) somewhere in issues, but can't find it now.

**Comment by RblSb** [comment]
Yep, this will solve it too. Would be nice to change typing, so as example "Left operand is not nullable" warnings can be added to null coalescing, without false positive warnings for `var a = null; a ?? 0;`
