### ISSUE TITLE
[4.2.0][Neko] Casting Reflect.makeVarArgs to Rest<T> now wraps arguments in a second array

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#10153]
```haxe
import haxe.extern.Rest;
class Main {
	static function main() {
		var f:Rest<Any>->Void = Reflect.makeVarArgs(function(args:Array<Dynamic>) {
			trace(args);
		});
		f(1, 2);
	}
}
```
Output:
```
src/Main.hx:5: [[1,2]]
```

**Comment by RealyUniqueName** [comment]
This happens to all targets with `pf_supports_rest_args = false` (neko, cpp, eval, hl), cs and java/jvm. For these targets rest arguments get wrapped with an array at call site.
Maybe `haxe.extern.Rest` should not be a typedef to `haxe.Rest` in such cases.

**Comment by RealyUniqueName** [comment]
I don't see a solution for this issue.
Perhaps `makeVarArgs` was introduced to deal with the absence of rest arguments in the language.
Now that sample can be changed to 
```haxe
var f = (...args:Any) {
	trace(args);
};
```
