### ISSUE TITLE
add Map.merge()

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10158]
## Description

I would like a quick way to ask a map to merge its key/value with another map. 

## Expected behavior

When merged, a map "A" see all its value for keys shared by a map "B" to be overwritten by the associated value of map "B". Extra key present in "B" but not in "A" are added.

Example:

```haxe
final a = [
  "class" => "navbar-item",
  "href" => "https://haxe.org"
];

final b = [
  "class" => "navbar-link",
  "rel" => "follow",
];

final c = a.merge(b);

trace(c);
``` 

```
{class => navbar-link, href => https://haxe.org, rel => follow}
```

## Aditionnal data

I created this snippet which show an example of code to do this: https://try.haxe.org/#58058B0E

**Comment by Simn** [comment]
This is bad API design because it's unclear if the method would modify the map or create a new one. Even your own example code messes that up because it works with `newMap` but actually modifies the existing Map.

**Comment by khalyomede** [comment]
I changed the method regarding your comment on the fact that it modifies the target, by using Map.copy() instead of assigning it to a new variable. See : https://try.haxe.org/#128f24F3

For your remark about not being sure the method would modify or create a new map, I thought about having a MapTools.merge() instead, what do you think @Simn?

**Comment by back2dos** [comment]
I think if anything, this should be part of `IMap`, so that it can be optimized where possible (I imagine inserting one balanced tree into another could be way faster than inserting one by one and on JavaScript `Object.assign` might also speed up the process).
