### ISSUE TITLE
Unexpected behavior when using #if with an unspecified define

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#10152]
```haxe
function main () {
#if (foo != "bar")
    trace("OK");
#end
}
```

I would expect this to trace "OK" if foo is unspecified, that is, when no -D foo=whatever was included during compilation. Would that make sense?

Thanks for considering 😀

**Comment by RealyUniqueName** [comment]
@Simn do you know if current behavior is how it's meant to be?

**Comment by Simn** [comment]
Sorry, didn't notice the mention.

`foo != "bar"` should be `true` if `foo` is undefined, because in that case it's clearly not `"bar"`.
