### ISSUE TITLE
Environment variables are wrong when running code on language server

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10151]
When running code using the `--interp` flag using the language server, the `Sys.environment()` function gives the names of the environment variables in lowercase.

```haxe
class Main {
    static function main() {
        var env = Sys.environment();
        for (i => j in env)
            Sys.println(i + ": "+ j);
        }
}
```
Running this code with `haxe --interp` prints out the environment variable names correctly. However with `haxe --interp --connect 6000` (with a server running on port 6000) all of the system variables are printed out in lowercase instead.

This is also true if you are using the language server when a haxe call results in a haxelib being run. Any attempt to access the environment variables in the library's neko file gives the variable name in lowercase.

For example, when compiling an hxcpp project with the language server on Windows, the `USERPROFILE` environment variable cannot be found, because Sys.environment() only finds a variable called `userprofile`. This can cause building errors.

**Comment by Simn** [comment]
That doesn't reproduce for me. How do you launch the server?

**Comment by tobil4sk** [comment]
I was launching it with vscode. I just tried launching the server from the command line and that way it seems completely fine now...

Probably not an issue with Haxe and just the vscode extension?

**Comment by Simn** [comment]
Yeah, I'm seeing this code in vshaxe:

```haxe
	function mergeEnvs(from:DynamicAccess<String>, to:DynamicAccess<String>) {
		@:nullSafety(Off)
		for (key => value in from) {
			if (Sys.systemName() == "Windows") {
				key = key.toLowerCase();
			}
			to[key] = value;
		}
	}
```

**Comment by Gama11** [comment]
That's there to "solve" the problem of `FOO` pointing to the same env variable as `foo` on Windows... :/ I think they're "case-preserving" but not "case-sensitive".

Maybe we should just not bother with that / try to be too clever.

**Comment by Gama11** [comment]
On the other hand, this may have solved a concrete problem, I don't remember the exact specifics: https://github.com/vshaxe/haxe-language-server/commit/f9262490c18a79559ce3ba708729de0558fc1c66

**Comment by Simn** [comment]
IMO the implementation should _compare_ case-insensitive, but preserve the original casing (of whichever version comes first I guess).

**Comment by tobil4sk** [comment]
Moving this to the extension's repository: vshaxe/vshaxe/issues/482
