### ISSUE TITLE
add haxe.ds.Result

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10156]
## Description

In functional programming, we can have code that will result in failures. For example, imagine a class called Env, which is responsible for parsing a .env file.

```haxe
import sys.FileSystem;
import haxe.Exception;

class Env {
  var filePath: String;

  public function new(path: String) {
    this.filePath = path;
  }
  
  public static function fromFile(path: String): Env {
    if (!FileSystem.exists(path)) {
      throw new Exception("file does not exist");
    }

    return new Env(path);
  }

  public function get(key: String): String {
    // logic to parse and get the value
  }
}
```

To use it, this is what we could write:

```haxe
var env: Null<Env> = null;

try {
    env = Env.fromFile("foo.env");
} catch (exception) {
    // stop the program there
}

final appName = env.get("APP_NAME");
```

In a functional programming manner, instead of throwing an exception, I would use a [Result type](https://en.wikipedia.org/wiki/Result_type#:~:text=In%20functional%20programming%2C%20a%20result,value%20or%20an%20error%20code.) for this purpose. This requires introducing a new enum:

```haxe
import sys.FileSystem;

enum Result<T> {
    Ok(value: T);
    Error(message: String);
}

class Env {
  var filePath: String;

  public function new(path: String) {
    this.filePath = path;
  }
  
  public static function fromFile(path: String): Result<Env> {
    if (!FileSystem.exists(path)) {
      return Error("file does not exist");
    }

    return Ok(new Env(path));
  }

  public function get(key: String): String {
    // logic to parse and get the value
  }
}
```

And the usage would become:

```haxe
final env = switch(Env.fromFile("foo.env")) {
    case Ok(env): env;
    case Error(message):
        // stop the program here
};

final appName = env.get("APP_NAME");
```

## Expected behavior

I propose to have a new haxe.ds.Result.

```haxe
package haxe.ds;

enum Result<T> {
  Ok(value: T);
  Error(message: String);
}
```

## Additional data

If having the "message" property of the Error enum value too strict (String), we could have another monad called "Outcome" which would be more generic:

```haxe
package haxe.ds;

enum Outcome<T, E> {
  Ok(value: T);
  Error(value: E);
}
```

So that if somebody wants to provide a richer error, like a struct, it can be done through this one.

**Comment by Simn** [comment]
You can just use `haxe.ds.Either`, which is basically what you're suggesting but with less loaded constructor names.
