### ISSUE TITLE
How about getting rid of explicit, empty constructors

### ISSUE THREAD

**Issue by danielbenmergui** [HaxeFoundation/haxe#10168]
Now that Haxe is moving towards supporting styles of programming other than old school OOP like module-level functions, it would be nice for all the people that are programming with dumb classes to remove the mandatory explicit constructor.

Like:
```haxe
class ClickyButton
{
    public var bigLabel = "";
    public inline function new(){} // nasty
}

class Creature
{
    public var hp:Int;
    public var maxHP:Int;
    public inline function new(){} // nasty
}

class Player
{
    public var creature = new Creature();
    public inline function new(){} // nasty
}
```

It's just silly. If I need the feel to protect other people or myself by making methods inaccessible, I should do so explicitly instead of the other way around. These should be:
```haxe
class ClickyButton
{
    public var bigLabel = "";
}

class Creature
{
    public var hp:Int;
    public var maxHP:Int;
}

class Player
{
    public var creature = new Creature();
}
```

And default, inline, empty constructors should be created behind the scenes.

In fact, I would go as far as to say that making fields private by default is also a bad convention, but I'll leave that request for another occasion.

It may seem small, but i's one of the most cringy things about looking at Haxe right now.

**Comment by Simn** [comment]
No, not every class is meant to be constructed.

**Comment by danielbenmergui** [comment]
Can't you just private or protect the constructor in that special case instead of making the explicit constructor the default behavior?

**Comment by RblSb** [comment]
You can use `@:structInit` to get generated constructor:
```haxe
@:structInit
class Creature
{
    public var hp:Int;
    public var maxHP = 10;
}
```

**Comment by Simn** [comment]
This just doesn't work without constructor overloading. Adding an explicit constructor (with arguments) would break every usage of that implicit constructor, which is just silly.

@RblSb I don't think you can explicitly call an implicit constructor though.

**Comment by danielbenmergui** [comment]
> Adding an explicit constructor (with arguments) would break every usage of that implicit constructor, which is just silly.

This seems like the right thing to happen if you change your mind and decide there needs to be initialization with parameters in order to fully construct the object. Same thing would happen if I add a parameter into the explicit, empty constructor.

Maybe I'm missing something, but I still don't understand why the currently policy makes sense.

@RblSb I was aware of that, but it's still boilerplate code to just define one of the dozens (maybe hundreds!) of dumb structures I need in a project.

**Comment by RblSb** [comment]
@Simn Well, actually, some example with non-constructed class would be nice... Even Java has default empty constructor if there is non-static field inside of class, same for ts/c#/cpp/kotlin/dart/etc...

**Comment by Simn** [comment]
I meant "constructed without arguments", which is not a special case.

**Comment by RblSb** [comment]
I mean, in other languages "the default constructor is the no-argument constructor automatically generated unless you define another constructor". This is not about overloading, just empty default declaration if there is non-static field already. If you want constructor with args, then you write it yourself. Doesn't break private constructors too.

**Comment by Gama11** [comment]
Haxe doesn't really have a private, only protected. So you'd have to make non-constructible classes final too rather than just declare a private constructor.

If any case, changing this would **silently** change the intended behavior of a lot of existing code, since right now, "no constructor is declared" means "you shouldn't be able to construct this".

**Comment by RblSb** [comment]
@Gama11 true, except there's will be check before constructor generation for non-static fields. Or there is cases of classes with non-static fields and without constructors?

And about protected, you cannot make parent class without constructor, so i don't get what is a problem.

**Comment by danielbenmergui** [comment]
> Haxe doesn't really have a private, only protected. So you'd have to make non-constructible classes final too rather than just declare a private constructor.
> 
> If any case, changing this would **silently** change the intended behavior of a lot of existing code, since right now, "no constructor is declared" means "you shouldn't be able to construct this".

I guess it would suddenly make non-constructable classes constructable until the authors realize it's open season for construction and seal the class, yes. I don't think it would *break* stuff?

Anyway, I understand that you have a burden of legacy to deal with at this point to change this quirk, thank you for taking the time to explain, @Gama11.

**Comment by Gama11** [comment]
>true, except there's will be check before constructor generation for non-static fields

Would there be such a check though? At least four of the languages you mentioned (Java, Kotlin, TS, C#) actually don't have that.
