### ISSUE TITLE
Add Github issues templates

### ISSUE THREAD

**Issue by khalyomede** [HaxeFoundation/haxe#10165]
## Description

I notice all the issues don't always have some useful information (mine included), such as the Haxe version, ..., nor a common structure to help maintainers to get the information they need quickly.

## Proposal

I propose to have 2 new issues templates:

- Bugs
  - A description of the issue
  - The steps to reproduce the issues (including try.haxe.org snippets)
  - The errorneous behavior
  - The expected behavior
  - Any alternative solutions found to tackle the issue
  - Environment information
    - The Haxe version this issue occurs on
    - The OS
- Feature requests
  - A description of the context for why the new feature is useful
  - A description of the proposal (including code snippets for example usage)
  - Any additional information related to this proposal

**Comment by Simn** [comment]
I don't like these, they just cause noise that I have to filter through. More involved feature requests should go through haxe-evolution anyway.
