### ISSUE TITLE
Run sys test cases for hxnodejs?

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#10176]
I want to implement sys.io.Process for hxnodejs, where it currently is missing from the sys package implementation (https://github.com/HaxeFoundation/hxnodejs/issues/174). I figure the best way to test my implementation would be to run the core tests of Process, which are located in this repository and apparently don't run over any part of the hxnodejs sys implementation. Shouldn't they do that as part of Haxe's automated tests?

**Comment by RealyUniqueName** [comment]
hxnodejs is not a part of the compiler or std. Hence hxnodejs tests belong to its repo.

**Comment by NQNStudios** [comment]
Is there a DRY way for the hxnodejs repo to import the unit test code from the Haxe core repo while also conditionally passing the tests for unsupported features?

**Comment by RealyUniqueName** [comment]
I guess the only way is to obtain `tests/sys` from Haxe repo (e.g. by cloning the repo).
