### ISSUE TITLE
[error reporting] redundant "missing return" when there's an error after "throw"

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#10170]
```haxe
function f():Int {
	throw invalid;
}
```

This gives two errors:
```
src/Main.hx:2: characters 8-15 : Unknown identifier : invalid
src/Main.hx:1: lines 1-3 : Missing return: Int
```

The second one shouldn't be there, because obviously there is a `throw`, so no need for return.

**Comment by Simn** [comment]
I found a very similar issue the other day, but now I can't find it anymore... oh well, it will reappear I'm sure!

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/issues/9171

**Comment by Simn** [comment]
Ah thanks, apparently I'm really bad at locating issues!
