### ISSUE TITLE
[ide] Wrong doc for module level statics

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#10171]
![Screen Recording 2021-03-09 at 21 46 53](https://user-images.githubusercontent.com/3742992/110542898-8a5a2700-8121-11eb-9e21-e656b5db194b.gif)

Repro 
[vscode-doc-bug.zip](https://github.com/vshaxe/vshaxe/files/6111632/vscode-doc-bug.zip)

**Comment by Simn** [comment]
Debug output says that the parser sees the doc comments in reverse order, which completely defies my understanding of how parsers work:

```
*
	a random number generator (only works once)
*
*
	I'm a library!
*
```

This is probably not a problem specific to module level fields.

**Comment by Simn** [comment]
It took me several attempts to add that test because I kept realizing that I can't add doc comments into doc comments for the server/display tests...
