### ISSUE TITLE
Enum not fully matched

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10189]
```haxe
enum E {
	A;
	B;
	C( v : Int);
}

class Test {

	
	static function main() {
		var e = A;
		switch( e ) {
		case A:
		case B:
		case C(0):
		case C(x) if( x > 0 ):
		}
	}

}
```

The following only make a compilation error if there is a "return" in front of the switch. However the fact that we allow to skip `default` case should only occur when switching on a value (a String for example), not on values contained into enums parameters.

Ping @Simn

**Comment by Simn** [comment]
I swear I could find an issue where you asked for it to behave exactly like this... But I agree that this should fail so I'm happy to change it.

**Comment by Simn** [comment]
I spent some time looking at this today (longer than I care to admit...) and struggle a bit to get the definitions right. We have this notion of "toplevel" matching which doesn't require exhaustive checks, but internally that's not so easy to separate. For example:

```haxe
class Main {
	static var c = 0;

	@:matchDebug
	static function main() {
		switch (c) {
			case 1:
				"1";
			case _ if (c == 2):
				"_";
		}
	}
}
```

The decision tree for this is:

```
DECISION TREE BEGIN
 6  var ` = Main.c
 5  switch (`)
        case 1(unguarded):
 0          "1"
 1      default
 4          if (Main.c == 2)
 2              "_"
            else
 3              <fail>
DECISION TREE END
```

The recursion in the `default` case means that the guard isn't "toplevel" anymore, but we don't want this example to fail. I suppose we should redefine "toplevel" as meaning "not a nested switch" or something, but there's also some logic regarding implicit null checks which causes me a headache. I'll take another look at this tomorrow.
