### ISSUE TITLE
haxe 4.2.1 haxelib wont run

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#10180]
After installing [haxe 4.2.1](https://haxe.org/download/file/4.2.1/haxe-4.2.1-win64.exe/) on a 64bit windows PC, I get the following error when trying to run haxelib:

haxelib.exe - Application Error
The application was unable to start correctly (0x0000279).
Click OK to close the application

![haxelib_error](https://user-images.githubusercontent.com/139457/111449023-1d6b1080-8763-11eb-907c-bba89bc820cf.JPG)

**Comment by haxiomic** [comment]
I think a lot of users are on Windows 64 without issue so maybe something else is going on here

What happens when you try to run haxelib.exe in the `haxe_latest.zip` from here 
https://build.haxe.org/builds/haxe/windows64/ ?

**Comment by RealyUniqueName** [comment]
Yep. I just tried it on a clean win64 system and it works fine.

**Comment by haxiomic** [comment]
If the link I posted also failed the same way, there's some things we can try to work out what's up. Best guess is some DLLs used by haxelib.exe are missing – you could try checking the exe in this tool https://github.com/lucasg/Dependencies to see it can see any missing dependencies

**Comment by peteshand** [comment]
Hi both

Thanks for the quick response.
So I gave `haxe_latest.zip` a go, but I'm seeing the same issue.
So also downloaded `neko_latest.zip`, but didn't help.
I've also give older versions a try and again same issue, so it's obviously something to do with my system, but it's unclear what the underlying cause it.

The Dependencies application shows the Checksum for Neko is incorrect for some reason, not sure if that has anything to do with it?
![neko_incorrect_](https://user-images.githubusercontent.com/139457/111536585-89c72d80-87be-11eb-8de2-5a0815692a7a.JPG)

**Comment by haxiomic** [comment]
Thanks for the screenshot, interesting! Hopefully the incorrect neko checksum isn't an issue (I see the same when I test haxe_latest) - does anyone have more info on that?

The error 0xc0000279 is
[`STATUS_IO_REPARSE_TAG_NOT_HANDLED`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55)
> The layered file system driver for this I/O tag did not handle it when needed.

Which looks pretty fundamental - perhaps a drive issue? You could try in an admin command prompt `CHKDSK   C:   /R` and schedule it to run next restart

Did you try dragging neko.dll and gcmt-dll.dll into the same directory as haxelib.exe so it uses those? Would be interesting if that changes anything

Do you get the same issue with `haxe.exe` and `neko.exe` or do those run fine?

It's conceivable that checksum issue might cause this if there's a security flag in windows somewhere to check that but I'm not yet convinced

**Comment by peteshand** [comment]
neither haxe.exe or neko.exe have the same issue..

`RESOLVED`

dragging `neko.dll` and `gcmt-dll.dll` into the same folder as haxelib.exe stopped the `The application was unable to start correctly` error message, but did result in other issues... however it made it clear that there was an issue with the system path.

Looking at the system path, there wasn't any obvious issue. I basically ended up dumping and saving the system path and then deleted everything apart from:
`C:\Windows\system32`
`C:\Windows\`
`%NEKO_INSTPATH%`
`%HAXEPATH%`

After doing this haxelib started working.
I then added back the saved path items from before and was expecting to see the issue again then would have remove item by item, however after adding them all back it's still working... so yeah I'm not entirely sure what the issue is, but it was something to do with the path.

note:

**Comment by haxiomic** [comment]
Thanks for the update!
