### ISSUE TITLE
Compiler define flags switching dash to underscore can result in flag defined with two values

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10184]
It is possible to overwrite a define flag like this

```hxml
-D a-a=1
-D a_a=0
```
`a-a` is 1, and it auto-generates `a_a` with the same value. However, only `a_a` is overwritten by the next line. So during compilation `a-a=1` and `a_a=0`.

## Implications
As conditional compilation can only use the `a_a`, which is always updated correctly, this issue should not have any impact on code generation. However, it could end up being a problem for macros.

The changes described in #7795 seem to have been made.

When compiling with `-D a-a=1`:

```haxe
haxe.macro.Context.defined("a-a"); // true
haxe.macro.Context.defined("a_a"); // true
```

In comparison to compiling with `-D a_a=1`:

```haxe
haxe.macro.Context.defined("a-a"); // false
haxe.macro.Context.defined("a_a"); // true
```

### Hashlink C compilation
From here, the rest of this section is just about how an example of this happening can be seen when compiling to hashlink c. As far as I can tell it does not result with any functional difference in the code generated, so it isn't as big a problem here as with macros.
```hxml
-D hl-ver=1.12.0
-D hl_ver=1.10.0
```
If you compile to the hashlink c target like above, in the `"defines"` of the `hlc.json` file you get: 
```json
"hl_ver" : "1.10.0",
"hl-ver" : "1.12.0",
```

Even if you just use only `-D hl-ver=1.12.0`, you still get:
```json
"hl_ver" : "1.12.0",
"hl-ver" : "1.12.0",
```
(same thing happens in this file with `-D analyzer-optimize`, the hlc.json file contains both `analyzer-optimize`, `analyzer_optimize` ). Again, here it does not seem to make a difference but it seems wrong for it to add both of them to the json.

## Solutions

I would suggest that the changes in #7795 should not have been put in place, but I guess it's been done.

As `--help-defines` lists the flags with dashes, so it seems like it is intended that the dash versions of flags are meant to be put inside. Maybe this could be changed to suggest the underscore versions as the defaults?

The page on the haxe manual lists them mixed together with dashes for some but underscores for others: https://haxe.org/manual/compiler-usage-flags.html

**Comment by RealyUniqueName** [comment]
I agree this is a mess, but that's the legacy we have. Common convention for command line arguments is to use dashes, but we can't use dashes for identifiers in Haxe code.
And technically it's ok `Context.defined('a-a') == false` in the second example as there's indeed no such define provided. It's `-D a_a`.
Also, changing that would "break" `Context.getDefines():Map<String,String>` if somebody relies on the keys of returned map.

As for duplicating flags in `hlc.json` that could be considered a bug of the hashlink generator. @ncannasse ?

**Comment by tobil4sk** [comment]
In this file https://github.com/HaxeFoundation/haxe/blob/development/src-json/define.json
some are given using underscores and some are given with dashes. This means that the manual automatically generates them in a way that isn't consistent.

I think it would be good for the manual at least to be consistent with whether it uses underscores or dashes, and seen as `--help-defines` lists them with dashes, and as you said dashes are cli convention, I think this file should list them using dashes.

However, currently `-D no_deprecation_warnings` does not work, only `-D no-deprecation-warnings`. Same with `source_header`, and anything that has a "-" in it right now in the define.json file. I guess this is another issue which has to be resolved first, if they should be changed there.

Or the `define.json` file could have everything with underscores, and the manual just has to swap them out to dashes, like `--help-defines` does?

**Comment by tobil4sk** [comment]
The duplicate flags issue is not just in the `hlc.json` file for the Hashlink target, it is also present in the `hxcpp` target's `Options.txt` file.

**Comment by tobil4sk** [comment]
The underscore version is always more reliable as it is always the most up to date one. For example, if you do:
```hxml
-D variable-a="Old value"
-D variable_a="New value"
```
`variable-a` is still set to `"Old value"`, but `variable_a` is set to `"New value"`. This remains true if a flag is set internally by the compiler, or if a macro sets it.
```hxml
-D variable_a="Old value"
-D variable-a="New value"
```
And this way, both values are `"New value"`.
Therefore, having the dash version in `hlc.json` and `Options.txt` is redundant.

**Comment by RealyUniqueName** [comment]
What a mess... 
I guess ideally we want underscored version to be defined always and dashed version if it was explicitly defined only. And both versions should always have the same value.

**Comment by tobil4sk** [comment]
That's pretty much what my PR does currently, aside from ensuring that `flag-a` and `flag_a` always hold the same value.

However, I was thinking that the code could be much simpler if you allow for the dashed version to be defined even if the underscore version was set via `-D`. This way internally, only one flag would exist. Every time a user puts in a `-D` flag or uses one of the macro functions, that's where the conversions happen at the interface level, but inside there is only one value stored.

However, this would mean that:
```haxe
// -D flag_a=value
haxe.macro.Context.defined("flag-a"); // true
```
I don't think it would be that big an issue, because really if the compiler already converts the flag automatically then it should simply be considered as the same flag. This would remove the need for a bunch of filtering and storing of duplicate values internally, and it would end the current situation `flag-a` and `flag_a` being the same thing in every context apart from one. On the other hand, synchronising them without defining `flag-a` if it hasn't already been defined would add more complexity instead of cleaning things up a bit.

I also think that a user won't really be able to depend on the behaviour of `-D flag_a` not defining a value for `flag-a`, if having both `-D flag-a` and `-D flag_a` in the same compilation is meant to always result in the same value for both of them. I don't really see a usecase for it anyway, as the only way to tell the difference currently is using a macro. Even then, if two flags are supposed to both give different behaviours then it shouldn't be the case that the only difference between them is whether they use a `-` or an `_`, a difference which even already is in most cases ignored by the compiler.

So, while I'm happy to change my PR to be the way you described, I think it makes more sense to simply make `flag-a` and `flag_a` the same in every sense without odd exceptions, as in this way I can clean up the PR a bit and make fewer overall changes.

**Comment by RealyUniqueName** [comment]
Sounds good to me.
