### ISSUE TITLE
"Unresolved identifier" error message should include the name of the identifier that couldn't be resolved

### ISSUE THREAD

**Issue by joshtynjala** [HaxeFoundation/haxe#10181]
I was trying to filter some of the errors in my Haxe project in VSCode today. I had hoped to figure out how many were "Unresolved identifier" messages for a specific identifier. I couldn't do that because the text is simply "Unresolved identifier" without the name of the identifier that the error is referring to. It would be helpful if the compiler would include the name of the identifier in the error message too. Thanks!

**Comment by Simn** [comment]
Could you please paste the exact error you're seeing? I can't find the string "Unresolved identifier" in the compiler sources, so I'm not sure where exactly this is come from.

**Comment by joshtynjala** [comment]
Hmmm... when I compile from the command line, I get the expected identifier name in the error message:

> Unknown identifier : identifierName

It looks like this is a vshaxe issue rather than a Haxe compiler issue.

I'm sorry for incorrectly assuming that vshaxe was getting its errors from the compiler.

**Comment by kLabz** [comment]
Haxe compiler does seem to send a `DKUnresolvedIdentifier` for diagnostics, which is then printed by vshaxe (but there should be a position indicating where the issue happens?)

**Comment by joshtynjala** [comment]
Created vshaxe/vshaxe#483 instead
