### ISSUE TITLE
js-es=6 error: "Must call `super()` constructor before accessing `this`"

### ISSUE THREAD

**Issue by unclearriw** [HaxeFoundation/haxe#10193]
[Try haxe](https://try.haxe.org/#09C24f91)

```
extern class MyClass {
	public function new(?a:Int):Void;
	public var a:Int;
}

class Test {
	static function main() {
		value = 2;
		var a = new A(Test.value);
		var b = new B();
		var c = new C();
		var d = new D(Test.value);
	}

	public static var value:Int;
}

// works
class A extends MyClass {
	public function new(a:Int) {
		super();
		haxe.Timer.delay(() -> trace(this.a), 50);
	}
}

// works
class B extends MyClass {
	public function new() {
		super(Test.value);
		haxe.Timer.delay(() -> trace(this.a), 50);
	}
}

// error
class C extends MyClass {
	public function new() {
		var a = Test.value;
		super(a);
		haxe.Timer.delay(() -> trace(this.a), 50);
	}
}

// error
class D extends MyClass {
	public function new(a:Int) {
		super(a);
		haxe.Timer.delay(() -> trace(this.a), 50);
	}
}
```

it needs 3 conditions for error:
1. Extern class has constructor with parameters
2. When calling super might be local variable
3. Need to be function/callback/etc which uses "this"

Tested on 4.2.0 and nightly builds

**Comment by unclearriw** [comment]
And btw 
```
// works
class E extends MyClass {
	public function new(a:Int) {
		super(a);
	}
}
```
obviously works (Updated try haxe example)

**Comment by nadako** [comment]
Interesting...

```haxe
extern class E {
	var a:Int;
	function new(a:Int);
}

class C extends E {
	function new(a:Int) {
		super(a);
		var f = () -> this.a;
	}
}
```

The AST dump for `C.new` is:

```
[Block:Void]
	[Var _gthis(1140):C] [Const:C] this
	[Call:Void]
		[Const:E] super
		[Local a(1139):Int:Int]
	[Var f(1141):() -> Int]
		[Function:() -> Int]
			[Block:Dynamic]
				[Return:Dynamic]
					[Field:Int]
						[Local _gthis(1140):C:C]
						[FInstance:Int]
							E
							a:Int
```

Somehow `_gthis` appears before `super()` here. ~Is it always simply added to the beginning of a function rather than the first usage? @Simn?~ Nevermind...

**Comment by nadako** [comment]
Thanks for the report! This should now be fixed, leaving the issue open to add the test later!

**Comment by ConfidantCommunications** [comment]
I am still able to reproduce this error in Haxe 4.3.6: https://try.haxe.org/#360F8756

**Comment by ConfidantCommunications** [comment]
I am still able to reproduce this error in Haxe 4.3.6: https://try.haxe.org/#360F8756
I got my own project to compile by removing the "new" function from the extern and the super() calls. Not sure if it will run properly yet.

**Comment by kLabz** [comment]
This is a case of #10103
