### ISSUE TITLE
[eval] haxe.io.Input.readByte not implemented in FileInput

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10206]
Haxe Version: 4.2.1

```hx
import sys.io.File;
import haxe.zip.Reader;

function main() {
	var read = Reader.readZip(File.read("sometest.zip"));
	for (file in read) {
		trace(file.fileName);
	}
}
```

I am currently trying to read in a file with --interp, but unfortunately it is not possible.

This works:
```hx
import haxe.io.BytesInput;
import sys.io.File;
import haxe.zip.Reader;

function main() {
	var read = Reader.readZip(new BytesInput(File.read("sometest.zip").readAll()));
	for (file in read) {
		trace(file.fileName);
	}
}
```

**Comment by Simn** [comment]
That doesn't reproduce for me

**Comment by lublak** [comment]
@Simn so it works for you?
that's strange. Because it is 1:1 my code.
My buildscript is not complex either.
```
-cp src
-D analyzer-optimize
-main Main
--interp
```

**Comment by Simn** [comment]
Yeah this just works, and `readByte` is definitely implemented. What error are you getting exactly?

**Comment by lublak** [comment]
```
C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:53: characters 10-15 : Uncaught exception Not implemented in haxe.io.Input.readByte at haxe/io/Input.hx:53
C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:282: characters 13-23 : Called from here
C:\HaxeToolkit\haxe\std/haxe/zip/Reader.hx:80: characters 11-24 : Called from here
C:\HaxeToolkit\haxe\std/haxe/zip/Reader.hx:126: characters 12-29 : Called from here
C:\HaxeToolkit\haxe\std/haxe/zip/Reader.hx:196: characters 10-18 : Called from here
src/Main.hx:5: characters 13-108 : Called from here
The terminal process "C:\HaxeToolkit\haxe\haxe.exe '--connect', '6000', 'build.hxml'" failed to launch (exit code: 1).
```

**Comment by Simn** [comment]
That suggests that dynamic dispatch doesn't arrive at `FileInput.readByte`, but somehow calls `Input.readByte`. I have no idea why this would happen though because `File.read` brings in `FileInput`.

Just do be sure, could you try with `-dce no`?

**Comment by lublak** [comment]
I think it can be closed. I have completely uninstalled haxe and reinstalled it.
Now everything is great.
It was still strange.

Thank you for responding so quickly.
Haxe is and remains my favourite language.
Not only because of the language but also because of the community.

And thanks for your time <3
