### ISSUE TITLE
Properties/Methods inside enums?

### ISSUE THREAD

**Issue by ALANVF** [HaxeFoundation/haxe#10208]
I saw that https://github.com/HaxeFoundation/haxe-evolution/issues/10 was closed, but I'm not sure why it couldn't happen seeing how the change is so trivial.

I (and many others) would find this feature very helpful, as static extensions **are not a solution**, and enums are fully capable of having their own properties (even if it's just static properties and instance getters/setters) and methods.

Enums do not currently support inheritance or implementing interfaces (although I would not be against adding them), so there would be no additional overhead for allowing properties/methods.

I'll even implement it if needed, but I figured I'd ask first before working on it.

**Comment by Simn** [comment]
This proposal has been rejected and closed. Simply opening another issue with the same goal isn't going to change anything.

**Comment by ALANVF** [comment]
Well there was no reasoning as to why it was rejected. I wanted to ask because it seems very simple to implement and add to the language

**Comment by ALANVF** [comment]
It was closed nearly 5 years ago, I thought that maybe y'all would be willing to consider it again

**Comment by Gama11** [comment]
>It was closed nearly 5 years ago

>Simn closed this on Sep 21, 2018

**Comment by ALANVF** [comment]
*opened 5 years ago

Still, 3 years is a pretty long time
