### ISSUE TITLE
`@:op(A += B)` is eliminated by the analyzer

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10209]
Hej,

I think UnicodeString is broken or maybe something changed because this doesn't work anymore https://try.haxe.org/#21bC6b04 :
```haxe
class Test {
  static function main() {
    var s			= "Haxe is great!";
    var buf	: UnicodeString = "";
    for( i in 0...s.length ){
      buf += s.charAt( i );
    }
    trace( buf );	// Empty
  }
}
```

**Comment by lublak** [comment]
Since haxe 4, all targets support unicode by default.

**Comment by filt3rek** [comment]
Ok, so no need to use UnicodeString anymore ? Maybe compiler should warning a depreciated or something like that ?

**Comment by RealyUniqueName** [comment]
Looks like `buf += s.charAt(i)` is eliminated by the analyzer. As a workaround you can replace that line with `buf = buf + s.charAt(i)`.

**Comment by RealyUniqueName** [comment]
> Ok, so no need to use UnicodeString anymore ?

Here's why `UnicodeString` exists: https://github.com/HaxeFoundation/haxe/blob/3004f1862d20280cd31ea0a95455a4e1da2aa326/std/UnicodeString.hx#L29-L34

**Comment by filt3rek** [comment]
Thanks Aleksandr for the explanation !

**Comment by RealyUniqueName** [comment]
Here's a minimal sample:
```haxe
function main() {
	var s = "Haxe is great!";
	var buf:AStr = "";
	buf += s.charAt(0); // Diagnostics: This '+' operator has no effect, but some of its sub-expressions do
	trace( buf ); // Empty
}

abstract AStr(String) from String {
	@:op(A += B) @:commutative static function assignAdd(a:AStr, b:String):AStr;
}
```
And the dump for `--interp` is
```haxe
var s = "Haxe is great!";
var buf = "";
s.charAt(0);
haxe.Log.trace(cast "", {fileName : <...>});
```

**Comment by Simn** [comment]
Not the analyzer's fault:

```
<initial>
function() {
        var s<216> = "Haxe is great!";
        var buf<217> = "";
        buf<217> + s<216>.charAt(0);
        haxe.Log.trace(buf<217>, {fileName : "source/Main.hx", lineNumber : 6, className : "_Main.Main_Fields_", methodName : "main"});
}
</initial>
```

Likely some regression from my operator rework.

**Comment by RealyUniqueName** [comment]
Nope. It's a regression between 3.1.3 and 3.2.1
