### ISSUE TITLE
[js] Incomplete compilation command successfully generates a file

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10200]
Running this command, with no haxe code anywhere in the directory at all:
`haxe --js main.js -lib hxnodejs`

successfully generates this file:
```haxe
// Generated by Haxe 4.2.1+bf9ff69
(function ($global) { "use strict";
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
})({});
```

This happens no matter which directory I run it in. It seems to be something to do with the extra lib parameter. Without it, it just prints out help and doesn't generate anything as normal.

Obviously, it's not that urgent an issue, just seems a bit odd.

**Comment by Gama11** [comment]
That's a feature, not a bug: https://code.haxe.org/category/compilation/compiling-libraries-without-main-class.html

hxnodejs is not a great example though, it's just externs so there isn't really much to generate for `haxe js.node --js main.js -lib hxnodejs`.

**Comment by tobil4sk** [comment]
So is it meant to work even if you don't put any classes in as arguments?
All I'm putting in is the output file and to include the library using --lib, not any actual classes to compile. It doesn't do that with other libraries.

**Comment by Gama11** [comment]
>It doesn't do that with other libraries.

Oh, it doesn't? That might be due to the library's extraParams.hxml then.

**Comment by back2dos** [comment]
As soon as there's a `--macro` call compilation passes just fine (and hxnodejs has one in its `extraParams.hxml`).

**Comment by RealyUniqueName** [comment]
Nothing to do here
