### ISSUE TITLE
[jvm] java.lang.VerifyError on Android: "Expected initialization on uninitialized reference"

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#10213]
I'm getting a weird error when instantiating specific Haxe classes on Android. It seems to only happen on certain big-ish projects and I haven't been able to make a minimal repro case yet, but thought I'd report it anyways just in case.

Here's an example of one when it happens:

`java.lang.VerifyError: Verifier rejected class kit.creator.ui.BitmapText: void kit.creator.ui.BitmapText.new() failed to verify: void kit.creator.ui.BitmapText.new(): [0x1B] Expected initialization on uninitialized reference Reference: kit.creator.ui.BitmapText (declaration of 'kit.creator.ui.BitmapText' appears in base.apk)`

In case it helps, this seems to be where that error is emitted: https://android.googlesource.com/platform/art/+/master/runtime/verifier/method_verifier.cc#3036

**Comment by Simn** [comment]
If I'm reading that correctly this is actually about the call-site, i.e. where the constructor is being called. What confuses me is that the error seems to originate from the same constructor that is being called... I guess looking at the actual bytecode of `BitmapText.new()` would help.

**Comment by aduros** [comment]
Thanks Simn. Here's BitmapText.class: https://aduros.com/share/BnotO8Yujy0PoXo0Z8WMCw/BitmapText.class

The output from attempting to load it on desktop Java:

```
$ java kit.creator.ui.BitmapText
Error: Unable to initialize main class kit.creator.ui.BitmapText
Caused by: java.lang.VerifyError: Bad operand type when invoking <init>
Exception Details:
  Location:
    kit/creator/ui/BitmapText.new()V @29: invokespecial
  Reason:
    Invalid type: 'kit/creator/ui/BitmapText' (current frame, stack[0])
  Current Frame:
    bci: @29
    flags: { }
    locals: { 'kit/creator/ui/BitmapText' }
    stack: { 'kit/creator/ui/BitmapText' }
  Bytecode:
    0000000: 2ab2 00b7 b500 2c2a 0eb5 0036 2a0e b500
    0000010: 412a 12b9 b500 862a 0fb5 0052 2ab7 00bb
    0000020: b1
```

If it helps I can email you the complete jar.

**Comment by Simn** [comment]
Sorry for the late reply, but yes I think I'll need to look at the actual bytecode for this.

**Comment by Simn** [comment]
Closing due to lack of follow-up.
