### ISSUE TITLE
JS sourcemaps are not compatible with Firefox?

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxe#10217]
When debugging the JS target with Chrome or Edge browser, sourcemaps work as expected. But when using Firefox, I always get the following error (in the console and the debugger sources):

```
NetworkError when attempting to fetch resource.
```

It seems that Firefox doesn't honor `"sourceRoot":"file:///"` in the generated sourcemap.

![image](https://user-images.githubusercontent.com/1643950/114719279-343b5d80-9d37-11eb-89c2-1046c27e1611.png)

If I use `"sourceRoot":""`, and add the `file:///` prefix to every `"sources"` paths defined in the sourcemap (that's what [Sass](https://sass-lang.com) does for example), everything works as expected (in all three tested browsers).

![image](https://user-images.githubusercontent.com/1643950/114719149-0eae5400-9d37-11eb-8331-749e579c09de.png)

Haxe 4.1.5 on Windows 10 (i.e. the `"sources"` paths all start with something like `C:/Projets/[...]`).

**Comment by RealyUniqueName** [comment]
Works as-is for me. But maybe it's because I'm on linux.

**Comment by Simn** [comment]
This sounds like it would be a Firefox issue. Maybe check that your version is up-to-date and stuff.

**Comment by cedx** [comment]
Firefox 90 was released on July 13, 2021 and this issue is still there.

![image](https://user-images.githubusercontent.com/1643950/125823373-0c413cf8-9a69-4f18-81dd-bff3be1d891d.png)

It's clearly a Firefox issue (and only on Windows) but it can be easily avoided.
If you're OK, I can submit a PR... but I know nothing about OCaml :cry:

From what I can gather, we just have to modify these files/lines (i.e. remove `sourceRoot` and add the same prefix to every `sources`):
- [src/context/sourcemaps.ml#L128](https://github.com/HaxeFoundation/haxe/blob/development/src/context/sourcemaps.ml#L128)
- [src/generators/genjs.ml#L290](https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genjs.ml#L290)

**Comment by RealyUniqueName** [comment]
Fixed. Try it with nightly builds.

**Comment by cedx** [comment]
Tested 3f1bc02 with Chrome/Edge/Firefox and... it works! Now sourcemaps work as expected on Firefox/Windows.
Thanks a lot @RealyUniqueName.

**Comment by haxiomic** [comment]
ty :) this also fixes esbuild sourceMaps which also doesn't handle sourceRoot fully

**Comment by Misiur** [comment]
Might be the same problem with developer edition though: `unsupported protocol for sourcemap request file:///C:/HaxeToolkit/haxe/lib/lime/7,9,0/src/lime/_internal/backend/html5/HTML5Application.hx`

Works on chrome

**Comment by kLabz** [comment]
Still having the issue on developer edition too. Adding `-D source-map-content` as a workaround makes source maps work there.

**Comment by T1mL3arn** [comment]
Firefox v110.0.1, source maps don't work. Thanks @kLabz for workaround.
