### ISSUE TITLE
js.Cookie misses secure and sameSite attributes

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#10223]
Are there plans already to add `secure` and `sameSite` to `js.Cookie`?
I have added them here and could provide a PR if you want.

**Comment by haxiomic** [comment]
Hey @mockey, PR for this would be awesome as I don't think there's any immediate plan to add

SameSite and Secure headers look [reasonably well supported](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#browser_compatibility) (of course we should double check they don't cause issues for unsupported browsers, but I don't expect they would)
