### ISSUE TITLE
"Orphan" monomorphs after calls

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#10236]
As one of consequences of #10198 I've come up with the following question:
Should we disallow monomorphs spawned for a call to be unbound after the call is typed?
Currently this is possible:
```haxe
class Main {
	extern static function fn<T>():T;
	
	static function main() {
		var a:String = fn();
		var b:Float = fn();
		var c:Whatever = fn();
	}
}
```
which looks wrong to me.

**Comment by Simn** [comment]
These aren't good examples for what you mean because this should work through top-down inference anyway. The more interesting question is `var a = fn(); a = "foo";`, but even then I don't see the value in disallowing this.
