### ISSUE TITLE
opam package `luv` missing from haxe opam package.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#10235]
Noticed it when building from source on a new switch (ocaml 4.11)

**Comment by RealyUniqueName** [comment]
What do you mean?
It's here: 
https://github.com/HaxeFoundation/haxe/blob/aecf036a4fb2dea0a995b911462ed5c08efb238e/opam#L35

**Comment by 0b1kn00b** [comment]
I'm not sure if the command I used depends on local info or published. In the instructions I read on the Haxe website, it seemed to be an install from opam, and that covers installing the various dependencies, of which luv was the only one not accounted for.

**Comment by RealyUniqueName** [comment]
Did you do this?
```
$ opam pin add haxe . --no-action
$ opam install haxe --deps-only
```

**Comment by 0b1kn00b** [comment]
That's the one.

**Comment by RealyUniqueName** [comment]
I don't get what you mean )

**Comment by 0b1kn00b** [comment]
Sorry, these are the commands I issued, as per the instructions (I was on a new switch) and I noticed when I went to build, there was that package missing

**Comment by Simn** [comment]
`luv` is listed in `opam`, so this should be fine on our end.
