### ISSUE TITLE
Something like `Context.typeAndStoreExpr`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10239]
When a macro wants to do something based on an expression's type, there's a whole lot of encoding going on. 

One can:

1. just type the expression, which encodes and types it once, but then again when it's processed as part of the final expression returned by the macro. Especially the double typing can be quite expensive (because there can be another macro call in the expression, or some overloads / implicit casts that are expensive to resolve).
2.  retrieve the typed expression and then store it, which means that typing is only done once, but the typed AST needs to be encoded and decoded, without any further use. Since typed AST is usually significantly larger than untyped AST, this can also come at significant cost.

So the basic idea would be something like this:

```haxe
function typeAndStoreExpr(e:Expr):{ final type:Ref<Type>; final expr:Expr; } {
  // naive implementation based on current API
  var te = Context.typeExpr();
  return { expr: Context.storeTypedExpr(te), type: { toString: () -> TypeTools.toString(te.t}, get: () -> te.t };
}
```

The `type` is lazy, so that this function can also be used with minimal overhead to merely store an expression for duplicate use, e.g.:

```haxe
if (fooCond) {
  foo1();
  $e;
  foo2();
}
else $e;
```

**Comment by Simn** [comment]
Not sure about the naming, but I agree that this would be useful. The API looks pretty wonky with that return type, but I can see how this information could be used together nicely.

Duplicating typed expressions can get pretty dicey, but that's not a new problem given that we can already run into this through `storeTypedExpr`.
