### ISSUE TITLE
macro remove define

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10241]
Hej,

I'm sorry I don't know if it's a bug or if it's not allowed or I don't knw ohow to do, but we can't remove a defined value : 
```haxe
trace( haxe.macro.Context.definedValue( "test" ) );    // null
haxe.macro.Compiler.define( "test" );
trace( haxe.macro.Context.definedValue( "test" ) );    // 1
haxe.macro.Compiler.define( "test", null );
trace( haxe.macro.Context.definedValue( "test" ) );    // 1
```

**Comment by RealyUniqueName** [comment]
`1` is the default value for any flag defined without a value.

**Comment by filt3rek** [comment]
Ok but is there a way to remove a define please ?

**Comment by RealyUniqueName** [comment]
No. We don't even have such functionality in the compiler internals. What's your use case?

**Comment by filt3rek** [comment]
I want to use a define in a macro context but then I want to remove it in generation phase...
I know that I can play with define like that i.e: mydefine=on then mydefin=off, but it would be ccol to be able to just set it to null...

**Comment by RealyUniqueName** [comment]
You should avoid changing defines outside of initialization macros. We're aiming to completely restrict `Compiler.define` to init macros. Compiler already emits a warning if you use it anywhere else.
See #7871
