### ISSUE TITLE
Generic classes not recognizing recursive definition

### ISSUE THREAD

**Issue by Tezar** [HaxeFoundation/haxe#10245]
Normally Haxe recognizes recursive definition with `Recursive class` compile time error. When using generic it leads to  [stackoverflow error ](https://try.haxe.org/#430ae406) instead.

```
@:generic
class Foo<T> extends Foo<T> {

}
```

On win64 build  4.2.1+bf9ff69 compiler sometimes hard crashed too, but I can't reproduce that with minimal example.

According to try.haxe.org it correctly recognizes the recursion in 3.4.7 but not in any of the 4+ versions including latest dev 2021-03-31 cf61913.

**Comment by Simn** [comment]
This was fixed by https://github.com/HaxeFoundation/haxe/commit/8bce1a1b600744f556269f5137f1e6270a56f9c6
