### ISSUE TITLE
generated python code requires null check when doing comparisons

### ISSUE THREAD

**Issue by TC218** [HaxeFoundation/haxe#10240]
When comparing null value, python throws error:

> TypeError: '<=' not supported between instances of 'NoneType' and 'int'

sample haxe file:
https://gist.github.com/MT4000/9943bee6514b7be15af7c37fb8dbf95b

compilation:
```
haxe --python a.py -m A
python3 a.py

```

**Comment by RealyUniqueName** [comment]
This is a part of #8426
