### ISSUE TITLE
[haxe-cs] Compiler Failure

### ISSUE THREAD

**Issue by Skudoku** [HaxeFoundation/haxe#10250]
Haxe: 4.2.1+bf9ff69; OS type: unix;
File "src/core/tFunctions.ml", line 334, characters 16-23
Called from file "src/core/tFunctions.ml", line 336, characters 13-32
Called from file "src/codegen/gencommon/fixOverrides.ml", line 91, characters 42-99
Called from file "list.ml", line 106, characters 12-15
Called from file "list.ml", line 106, characters 12-15
Called from file "src/codegen/gencommon/fixOverrides.ml", line 162, characters 3-70
Called from file "src/codegen/gencommon/gencommon.ml", line 366, characters 12-21
Called from file "list.ml", line 106, characters 12-15
Called from file "list.ml", line 106, characters 12-15
Called from file "src/codegen/gencommon/gencommon.ml", line 360, characters 2-318
Called from file "src/codegen/gencommon/gencommon.ml", line 787, characters 18-28
Called from file "src/codegen/gencommon/gencommon.ml", line 798, characters 17-40
Called from file "src/codegen/gencommon/gencommon.ml", line 803, characters 1-35
Called from file "src/generators/genjava.ml", line 2671, characters 1-16
Called from file "src/compiler/haxe.ml", line 342, characters 2-14
Called from file "src/compiler/haxe.ml", line 1073, characters 25-72
Called from file "src/compiler/haxe.ml", line 640, characters 3-11
Called from file "src/compiler/haxe.ml", line 1238, characters 1-35
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

**Comment by Aurel300** [comment]
Did this happen with a particular code sample you can share?

**Comment by Skudoku** [comment]
This happened when I tried to compile my code into CS using `-cs`. I have not been able to trace the source where this might happen.

**Comment by RealyUniqueName** [comment]
Based on the stack trace this happened because somewhere amount of type parameters provided does not match the amount of type parameters expected. I guess it's because of a flaw in one of gencommon filters.

Could you please provide a reproducible sample?
