### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10251]
Hej !

Is it normal Haxe compiler doesn't halt on the second line here and report a strange message error at the end of the block ?
https://try.haxe.org/#0d853eC2
```haxe
class Test {
  static function main() {
    var s= "";
    s += var t;
    s += "foo";
    s += 5;
}
```
It would be cool that it halts when doing `s+= var t` I think it's not allowed, right ?

**Comment by Gama11** [comment]
https://try.haxe.org/#728BB0f1

**Comment by filt3rek** [comment]
OMG I'm sorry ...
