### ISSUE TITLE
I can't install Haxe

### ISSUE THREAD

**Issue by MikeTitan317** [HaxeFoundation/haxe#10269]
So, when I will install Haxe, the computer said to me that the editor are not verificated, and that if I install it, can contain virus, what I do?
If you asnwer, thanks : )

**Comment by jdonaldson** [comment]
Some operating systems incorrectly flag the Haxe compiler as being infected.  Keep in mind that no antivirus is perfect, and it's difficult for an open source project (like Haxe) to ensure that every antivirus system clears the executable correctly.  You can either compile the compiler yourself to be 100% sure, or you can exclude the compiler from your antivirus checks.  E.g. https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by haxiomic** [comment]
Maybe will fixed by signed binaries https://github.com/HaxeFoundation/haxe/issues/7720?

**Comment by RealyUniqueName** [comment]
Nothing to see here.
