### ISSUE TITLE
wildcard import with module level fields

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#10278]
```haxe
// Module Main.hx
import Foo.*; // `Module Foo does not define type Foo`.
class Main{
	static function main() {
		Foo.foo(); // Works.
		var a:Bar = {}; // `Type not found : Bar`.
	}
}

// Module Foo.hx
function foo() trace('foo');
typedef Bar = {};
```
Would make sense to support this now, I think.

**Comment by R32** [comment]
```haxe
import Foo.*; // is used to import all the static fields from the class
import Foo;   // imports everything from the module level
```

**Comment by Antriel** [comment]
`import Foo` works, so that's nice, thanks. But `import Foo.*` should also work for all types in a module, according to the manual. Technically `import Foo.Foo.*` should be for all static fields from a type, I think.

**Comment by RealyUniqueName** [comment]
A wildcard import is specified to "import of all modules in a package, all types in a module, or all static fields in a type"
https://haxe.org/manual/type-system-import.html#wildcard-import
I don't think we should adopt it for module level fields as such fields already get imported without `*`.
