### ISSUE TITLE
[null safety] String concatination/interpolation of nullable variable fails to compile

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#10272]
I am trying to convert a haxe lib to null safety and found a case where I cannot get the code to compile but receive the compiler error `Null safety: Cannot pass nullable value to not-nullable argument "s" of function "string".`

Here is a reproducer: https://try.haxe.org/#EeB286d6
```haxe
@:nullSafety
class Test {
    
  static function main() {
    
    var msg:Null<Dynamic>;
    msg = "foo";
    
    trace(msg);
    trace("Message: " + msg);
    trace('Message: ${msg}');
    
    doTrace(msg);
  }
  
  static function doTrace(msg:Null<Dynamic>) {
    trace(msg);
    trace("Message: " + msg); // <-- fails to compile
    trace('Message: ${msg}'); // <-- fails to compile
  }
}
```

**Comment by nanjizal** [comment]
Seems a bit unfair on Haxe compiler, it can't tell what your passing to the method so it cannot tell if it can parse to a string, my approach would to be to cast it yourself. Dynamic is something that is not tightly defined in that you should try to make something a defined type as early as possible. Not sure it's ideal to expect the compiler to be so tolerant of Dynamic. To me the first 'Message' trace should have errored as well, but I think you can't rely on the compiler too much when you rely too much on Dynamic.
https://try.haxe.org/#49B1252A

**Comment by sebthom** [comment]
This is a compiler false positive. 

The goal of null safety is to prevent potential null pointer access. However the given code is null-safe. 
Which can be demonstrated by disabling the null safety check and calling `doTrace(null)` which compiles and does not throw an error when executed.

**Comment by sebthom** [comment]
The root cause could be that `Std.string(...)` does not accept null values for some reason when null safety is enabled. So it might help to change it's signature from
```haxe
static function string(s:Dynamic):String;
```
to
```haxe
static function string(s:Null<Dynamic>):String;
```
