### ISSUE TITLE
Macro this var name

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10277]
Hej,

I'm using macro to "inject" a body function into another.
For that I use this piece of code, where `fexpr` is an ident of the function to be copied : 
```haxe
var texpr	= Context.typeExpr( fexpr );
			switch texpr.expr {
				case TField(_, FStatic(_, cf ) )	:
					if( cf.get().expr() != null ){
						switch cf.get().expr().expr{
							case TFunction(ff):
								var ee	= Context.getTypedExpr( ff.expr );
								switch ee.expr{
									case EBlock( exprs ):
										for( expr in exprs ){
											trace( expr.toString() );
										}
										return exprs;
									case _ : 
								}
							case _ :
						}
					}
				case _ :
			}
```
And the trace gives me that (I just pasted the interesting begin) : 
```haxe
var jwt:StdTypes.Null<String> = {
        var this:haxe.Constraints.IMap<String, String> = Server.instance.params;
        cast this.get("jwt");
}
```
But in PHP it's translated to : 
```php
$jwt = $this->get("jwt");
```
It seems like it doesn't take care of `var this:haxe.Constraints.IMap<String, String> = Server.instance.params;` so this represent the target class instance where the function is copied.

I am doing something wrong please or is it a bug ?

**Comment by RealyUniqueName** [comment]
`var this` should never be generated as `this` name is reserved. Normally it gets automatically renamed to something like `var _this`.
Could you provide a complete sample?

**Comment by filt3rek** [comment]
Thanks for your reply Aleksandr !
Here's the complete simplified example : https://try.haxe.org/#BF5b3595
Take a look at Compiler output

**Comment by RealyUniqueName** [comment]
That sample does not reproduce the issue.
Please, update it so that `var this` is actually generated in the target language code.
Getting `var this` from a typed expr in a macro may be ok because at this point of compilation not all filters are applied yet.

**Comment by filt3rek** [comment]
Aleksandr,

I made a zip file with 3 minimal files build, macro and test case.
Please take a look at the php output, you'll see in A.php in the foo function `$jwt = $this->get("jwt");`
Thanks a lot for your interest.
[varthis.zip](https://github.com/HaxeFoundation/haxe/files/6696044/varthis.zip)

**Comment by filt3rek** [comment]
I've done a try.haxe also in js it seems to do the same thing : https://try.haxe.org/#9501B8A5
...and if you uncomment the `trace` it will also throw "Test.hx:24: characters 5-10 : Unknown identifier : `trace" ... :confused:

**Comment by RealyUniqueName** [comment]
That's also because of missing filters.

Since we can't apply all the filters during macro execution and `Context.getTypedExpr()` is documented as it [may lose some information](https://github.com/HaxeFoundation/haxe/blob/af11f54/std/haxe/macro/Context.hx#L549) I'm leaning towards not considering this a bug.

**Comment by filt3rek** [comment]
I understand that it looses some informations but as much to transforms that into "this" ? It seems strange, if so is there another way to keep integrity of this function and "copy"/inject it into another ?

**Comment by RealyUniqueName** [comment]
You can just add a call to that function instead of injecting its body.
https://try.haxe.org/#5d139d15

**Comment by filt3rek** [comment]
Ok but it's quite stupid to define the call in the meta and using macro. I can also add the call at the top of the function by hand, it's same thing... Something is strange here...
