### ISSUE TITLE
[jvm] `@:native` does not work well

### ISSUE THREAD

**Issue by leonaci** [HaxeFoundation/haxe#10280]
```haxe
import haxe.macro.Compiler;
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Expr.Field;
​
class Main {
    static function main() OldClass.define();
}
​
#if !macro
@:build(OldClass.build())
#end
@:native("NewClass")
class OldClass {
	#if !macro
	public function new() {};
	#end
	
	macro public static function define():Expr return macro new OldClass();
	
	macro static function build():Array<Field>
	{
		var defined = false;
		
		Context.onAfterTyping(_ -> {
			if (defined) return;
			
			Context.defineType(
				macro class NewClass {
					public function new() trace('hello, world!');
				}
			);
			
			Compiler.exclude('OldClass');
			
			defined = true;
		});
		
		return null;
	}
}
```
```
haxe --jvm Main.jar -main Main
```

The above code that replaces `OldClass` with `NewClass` at compile-time causes an error: `Exception in thread "main" java.lang.NoClassDefFoundError: NewClass`

On other platforms it works well.
https://try.haxe.org/#71210eD1

**Comment by Simn** [comment]
Not sure what's going on but when I copy & paste your code I get `source/Main.hx:5: character 1 : Invalid character 0x200B`. Must be some new inclusive newline GitHub feature.

**Comment by Simn** [comment]
Having dodged whatever the hell that was, I can reproduce the issue.

There's a disconnect here between the type paths: the module ends up as `haxe.root.NewClass`, but the constructor still just does the equivalent of `new NewClass()`. I think the idea was to not rewrite anything if there's a `@:native`, so I don't know why this occurs here.
