### ISSUE TITLE
I have a problem compiling a game's code(Friday Night Funkin)

### ISSUE THREAD

**Issue by Gamerofyear** [HaxeFoundation/haxe#10286]
I'm trying to compile the game's code and it keeps showing the same error:

fatal error C1083: Cannot open include file: 'typeinfo': No such file or directory.

I searched online, but I couldn't find anything!
Please, can someone explain to me why is this happening and how to fix it?
I'm new, so go easy on me!

**Comment by Simn** [comment]
This error message comes from your C++ compiler. What happens is that Haxe generates C++ code, which is then compiled to an actual application (the game in this case). I can never remember where this typeinfo stuff comes from, but you probably have to install a newer version of Microsoft Visual Studio.

In general, issue trackers are mostly for reporting bugs. A better place for questions like yours are community forums like https://community.haxe.org/. I'll go ahead and close this issue accordingly.

**Comment by Gamerofyear** [comment]
Thanks for your help, Simn!

**Comment by Gamerofyear** [comment]
> This error message comes from your C++ compiler. What happens is that Haxe generates C++ code, which is then compiled to an actual application (the game in this case). I can never remember where this typeinfo stuff comes from, but you probably have to install a newer version of Microsoft Visual Studio.
> 
> In general, issue trackers are mostly for reporting bugs. A better place for questions like yours are community forums like https://community.haxe.org/. I'll go ahead and close this issue accordingly.

WOW! It really worked! Thank you so much!!!
