### ISSUE TITLE
Trying to use haxe 4.0.0 - got an error "Error: : unknown option '--server-connect'"

### ISSUE THREAD

**Issue by mathemaudio** [HaxeFoundation/haxe#10289]
I have an older project that uses 4.0.0 (due to its complications, it's virtually impossible to port it to newer versions of Haxe)

When I start vshaxe, I get the following:
    Haxe language server started
    Haxe Path: ./haxe.4.0.0/haxe.exe
    Using --server-connect
    Error: : unknown option '--server-connect'.
    Haxe Compiler 4.0.0 (git build development @ a018cbd8d) - (C)2005-2017 Haxe Foundation

As far as I can see in doc (https://haxe.org/manual/cr-completion-server.html), the command for the server is `haxe --connect 6000 myproject.hxml` . And with this command my 4.0.0 works fine. 
Is it possible to force the older method of connecting to a server?

**Comment by Simn** [comment]
If anything that's a vshaxe issue, please open it over there.
