### ISSUE TITLE
Breaking change macro CString backslashes

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#10285]
```haxe
public static macro function test() {
    var e = {expr: EConst(CString("\\")), pos: Context.currentPos()};
    trace("e: " + new haxe.macro.Printer().printExpr(e));
    return e;
  }
```
https://try.haxe.org/#F4e544F5

stable 4.2.2 
* e: 1 backslash

nightly a1fd2f7 
* e:  2 backslashes

This also breaks directly creating a macro string literal unicode ex: ``\u{N...}`` from https://haxe.org/manual/std-String-literals.html

**Comment by back2dos** [comment]
I've made the change in https://github.com/HaxeFoundation/haxe/commit/47ff2606f66304c8d63dd387bef248272100bb59

Two backslashes is correct, because `"\"` is an unterminated string.

Could you please elaborate on the unicode problem? It seems to work quite fine: https://try.haxe.org/#980BecD3

**Comment by PXshadow** [comment]
https://try.haxe.org/#55a66ac1

It does seem you are right that it's correct there is a distinction betweem the Printer and what the expr turns into. I was using it to print out a dynamic ``"\u{1F4A9}"`` from 
```haxe 
EConst(CString('\\u{$value}'));
```

I will simply modify the Printer, thanks for looking into this.
