### ISSUE TITLE
haxelib doesn't work under other drives

### ISSUE THREAD

**Issue by woofledev** [HaxeFoundation/haxe#10311]
haxelib works fine when i'm inside of the C:\ drive, but on other drives like D:\ etc... it doesn't seem to output anything?
![image](https://user-images.githubusercontent.com/83413563/124360352-9f574a80-dc29-11eb-9757-10c1d138b04c.png)
![image](https://user-images.githubusercontent.com/83413563/124360405-dfb6c880-dc29-11eb-9e51-bbebfd0ad89e.png)

**Comment by RealyUniqueName** [comment]
Try `haxelib list` command
