### ISSUE TITLE
[Java/Jvm] java.javax.crypto doesn't exist

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [HaxeFoundation/haxe#10327]
Problem:
Currently, java/jvm doesn't have java.javax.crypto, which breaks support for certain jars importing. 
Expected Behavior:
java.javax.crypto should exist as it is a default package for java.
How can this be fixed: 
Import java.javax.crypto (or whatever you guys do ^_^)

**Comment by Simn** [comment]
That entire package doesn't exist in `hxjava-std.jar`, but I don't know why.

**Comment by RealyUniqueName** [comment]
See https://github.com/HaxeFoundation/hxjava/issues/32

**Comment by Simn** [comment]
Ah, in that case this is fine on our end. We shouldn't include even more stuff by default.

**Comment by TheDrawingCoder-Gamer** [comment]
ah, where would i find the jar, i've tried looking for it but couldn't find it

**Comment by TheDrawingCoder-Gamer** [comment]
same place as where the other guy found it 😅
