### ISSUE TITLE
haxe --display "No completion point was found" for leading // comment

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#10322]
I'm trying to use `module-symbols` to detect the type definitions in a file., but `--display` fails if the byte specified falls within a single-line comment

I would typically inspect a file like so:

```
./haxe --display Test.hx@0@module-symbols
```

But unfortunately, a common scenario is a comment at the top of a file:

```
// Copyright something

class Test { public function new() {} }
```

Which results in:

```
>haxe --display Test.hx@0@module-symbols
Error: No completion point was found
```

**Note that all of the following do work:**

```
/* Copyright something */
class Test { public function new() {} }
```

(note leading whitespace):
```
 // Copyright something
class Test { public function new() {} }
```

I would think that `//` and `/*` comments would be treated the same.

Workaround:
----

Some less-than-ideal workarounds include:
- Detect the leading comment length N and construct my command as: `haxe --display Test.hx@${ N }@module-symbols`
- Change all my source files with leading `//` comments -- either to `/* */` comments, or simply add a `\n` or ` ` at the beginning.

**Comment by Simn** [comment]
> I would think that `//` and `/*` comments would be treated the same.

Well, that's not quite true because unlike `/*` we never interpret `//` as possible documentation comments.

However, in this situation `//` should obviously not cause any issues.

**Comment by Simn** [comment]
This is related to #7050. The special case is that the display position is `0` and thus is considered to be "in" the comment, which is pretty silly...

**Comment by jcward** [comment]
Thank you, @Simn.
