### ISSUE TITLE
[eval] uncaught exception process_run

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#10337]
I am writing a haxe program that will generate a nodejs project folder and install its dependencies. For some reason, sys.io.Process is throwing an error, specifically when I pass an argument array with the command "npm". 

This works:
```
new sys.io.Process("npm")
```

This doesn't:
```
new sys.io.Process("npm", ["install"])
```

And neither does this (which should be equivalent to the first call that works):
```
new sys.io.Process("npm", [])
```

Both cases that error, throw the same error:
>error: Uncaught exception process_run
>error: C:\HaxeToolkit\haxe\std/eval/_std/sys/io/Process.hx:1: character 1 : Called from here
>error: Called from here

I would understand if this were some kind of security feature, to stop me from writing dangerous code that installs other code? But I've done a similar thing for python project generation, and it worked fine. So I'm thinking this is more of a bug--one I can't track down, because the message is so vague.

**Comment by RealyUniqueName** [comment]
Works for me.

The error message you provide looks like an error from neko. 
Eval has no "process_run" functions or error messages in the sources.

Could you provide a complete sample?

**Comment by Apprentice-Alchemist** [comment]
This crashes on every target I have tested (eval, hl, neko, python, jvm).
```hx
function main() {
	new sys.io.Process("npm", ["help"]);
}
```

This works :
```hx
function main() {
	new sys.io.Process("npm.cmd", ["help"]);
}
```

The problem only occurs when trying to run a batch file (without the extension) or a builtin terminal command and passing arguments via the args param.
*It only occurs on windows as far as I know.*

> The error message you provide looks like an error from neko.
> Eval has no "process_run" functions or error messages in the sources.

The `process_run` error on eval comes from the native code iirc.
<https://github.com/HaxeFoundation/haxe/blob/6c2da0b8e683fa2d485789c7e2d9cfa06220dad5/libs/extc/process_stubs.c#L258-L416>

**Comment by Simn** [comment]
The fact that this also doesn't work on the Java target (which uses java.lang.ProcessBuilder) makes me think that attempting to fix this would be futile.

**Comment by Simn** [comment]
I'm closing this because I don't think there's anything here for us to fix. This just won't work on Windows without attempting to do major nonsense.

**Comment by kevinresol** [comment]
What is the correct way to do the job on windows?

I encountered this some time ago and resorted to a silly workaround: https://github.com/HaxeFoundation/haxe/issues/10363#issuecomment-907190820
