### ISSUE TITLE
Respect @:const for function type parameters

### ISSUE THREAD

**Issue by ianxm** [HaxeFoundation/haxe#10345]
It looks like support has been added for `@:const` in class type parameters (#3450), but not for functions.

This example:
```haxe
  class Test {
      static function main() {
          Test.foo("string");
      }
  
      @:generic
      public static function foo<@:const T>(val :T) {
          trace(T);
      }
  }
```
fails on the trace with `Only Const type parameters can be used as value.` But it _is_ a const.

**Comment by Simn** [comment]
This doesn't make sense because there is no syntax for specifying function type parameters explicitly.
