### ISSUE TITLE
typedef runtime validation

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxe#10355]
It would be useful. For example some compiler flag could be added to avoid regressions.

Ex. 1 - **OK**
```haxe
class Test {
  static function main() {
    var a:A = {x: 5};
  }
}

typedef A = {x:Int, y:Int};
```
```
Test.hx:3: characters 15-21 : Object requires field y
Test.hx:3: characters 5-22 : { x : Int } should be A
Test.hx:3: characters 5-22 : ... { x : Int } has no field y
```
Ex. 2 - should **fail** at least at runtime, because object doesn't have **y** field and shouldn't be assigned to **A** typedef
```haxe
import haxe.Json;

class Test {
  static function main() {
    var a:A = Json.parse(Json.stringify({a: 5}));
  }
}

typedef A = {x:Int, y:Int};
```

**Comment by kLabz** [comment]
FYI type safe json parsing is available through libs:
* https://lib.haxe.org/p/tink_json/
* https://lib.haxe.org/p/json2object/

**Comment by Simn** [comment]
Yes, this isn't the compiler's job.

**Comment by nanjizal** [comment]
For reference this seems to explain more about how json2object works, although it could be extended with more comprehensive example of typing, think it might talk about but would be nice if it demo's something like typing your example.
https://code.haxe.org/category/macros/strictly-typed-json.html
The problem I think ( please feel free to correct if technically out ) is that you have obscured the types from the compiler with a string, which haxe can't easily check given the range of possiblities, so the way round is to resolve the values at macro time, so the compiler can check them.

**Comment by CrazyFlasher** [comment]
For my current case also it would be enough to receive run time exception, that will be checked during tests.
Thanks for links you shared!

**Comment by kevinresol** [comment]
There are libs for "mere runtime validation": https://github.com/haxetink/tink_validation#validator

But I still recommend type-safe json parsers mentioned by @kLabz
