### ISSUE TITLE
Unix.Unix_error(20, "mkdir", "Program.js/src")

### ISSUE THREAD

**Issue by qrp73** [HaxeFoundation/haxe#10361]
I catch issue which is similar to https://github.com/HaxeFoundation/haxe/issues/6212

Catch the same issue in haxe-4.2.3-win.exe

Program.hx:
```
class Program {
  static function main() {
    trace('Hello World');
  }
}
```

```
haxelib install hxcs
haxe -main Program.hx -cs Program.js
```

Note: here is mistake, I forgot to change extension to *.cs and got this error:
```
Unix.Unix_error(20, "mkdir", "Program.js/src")
```
When I fixed extension to *.cs:
```
haxe -main Program.hx -cs Program.cs
```

it works fine. But it is not obvious to find mistake from such non-relevant error

**Comment by ibilon** [comment]
To reproduce create a file and use it as path for `--cs` (or any folder based output target).
Maybe it only checks that the output path exists but not that it's a folder?

@qrp73 the `--cs` command line argument take a folder as next parameter, not a file, you'd usually do something like `--cs build/`.

**Comment by qrp73** [comment]
yeah, I have Program.js file in the same folder, so it cannot create folder with the same name, but I realize it just now. :)

When I catch this error it looks for me more like unknown error in some Unix like call. 
It will be more clean to show error message which explains that it cannot create folder with such name.
