### ISSUE TITLE
-(Sys.cpuTime() - Sys.cpuTime()) returns 0.0 on occations with --interp target

### ISSUE THREAD

**Issue by PtrMan** [HaxeFoundation/haxe#10368]
expected behaviour: return something >0.0 all the time

use case: I am trying to measure time for my AI

**Comment by RealyUniqueName** [comment]
There's also `eval.luv.Time.hrTime()`

**Comment by RealyUniqueName** [comment]
Haxe's `Sys.cpuTime()` is directly mapped to Ocaml's `Sys.time()` (see https://ocaml.org/api/Sys.html) when compiling with `--interp`. 
If anything it's an issue of Ocaml.
