### ISSUE TITLE
JvmCode.EmptyStack

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10363]
```
$ haxe build.hxml -v

...

Generating java: bin/main.jar
JvmCode.EmptyStack
```

Repro:  https://github.com/kevinresol/haxe_issues/tree/issue_10363

**Comment by Simn** [comment]
Your Maven script just gives me `Uncaught exception process_run` (yes `mvn` is in my PATH).

**Comment by kevinresol** [comment]
To be frank, I have no idea how to invoke a binary via `sys.io.Process` on windows. I tried `'mvn'` and `'mvn.cmd'` and none of these worked.

**Comment by kevinresol** [comment]
Ok pushed a fix which finds the actual path with `where.exe`. But I am not sure why this is needed, perhaps a bug of the interpreter?

**Comment by kevinresol** [comment]
Updated repro with jars included, getting rid of maven completely.
