### ISSUE TITLE
`applyTypeParameters` not doing anything

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#10362]
I am not sure what the intended way of using `applyTypeParameters` is. It does work when applied on `ClassField` type, but not sure how I would use that, since I can't really convert that back to `Expr`.
I can deal with that here by returning `ComplexType` with the appropriate parameters, but I wonder if this is a bug, or intended behavior. Maybe something to do with the param already being bound to a monomorph?

```haxe
#if !macro
class Main {
    static function main() {
        var foo = new Foo<Int>();
        $type(foo.t); // Unknown<0>
        foo.t = "";
        $type(foo.t); // String
    }
}
@:genericBuild(Main.Macro.build()) class Foo<T> { }
#else
class Macro {
    public static function build() {
        var td = macro class FooT<T> {
            public var t:T;
            public function new() { }
        }
        haxe.macro.Context.defineType(td);
        var param = switch haxe.macro.Context.getLocalType() {
            case TInst(_, [p]): p;
            case _: throw "unexpected";
        }
        var type = haxe.macro.Context.getType('FooT');
        return switch type {
            case TInst(_.get() => t, _):
                // This return the same type, nothing is applied.
                haxe.macro.TypeTools.applyTypeParameters(type, t.params, [param]);
            case _: throw "unexpected";
        }
    }
}
#end
```

**Comment by lublak** [comment]
I think it is not implemented: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/TypeTools.hx#L267

**Comment by Antriel** [comment]
This is running in eval context, so it is. And as I said, it does work for class field type, but I have no way of using that.

**Comment by RealyUniqueName** [comment]
Because `var type = haxe.macro.Context.getType('FooT');` returns a type where all type params are already replaced with monomorphs.

**Comment by back2dos** [comment]
FWIW `Context.getModule` returns the types with params not applied.
