### ISSUE TITLE
[cs] Multiple underscores are not always renamed

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#10360]
Most instances of `function noop(_, _) {}` rename second underscore, but this one generates wrong code:

```haxe
class Foo<T> {
	public function new(a:T) {}
	public function noop(_, _) {}
}
```

Generates

```cs
void noop(object _, object _);
```

(sorry if I missed another duplicate..)

**Comment by RealyUniqueName** [comment]
You did :)
#10332
