### ISSUE TITLE
Add java-lib/net-lib as metadata for macro libs

### ISSUE THREAD

**Issue by piboistudios** [HaxeFoundation/haxe#10377]
It would probably be useful to be able to determine what net-lib/java-lib a given class came from based on the class's compile-time/macro metadata. 

I would think it would be possible for the compiler to insert that as metadata on the class for haxelibs utilizing macros to then inspect.

**Comment by RealyUniqueName** [comment]
What's the purpose of having such meta? Can you provide an example where that could be useful?

**Comment by back2dos** [comment]
My guess is you can use the class's `pos` where the `fileName` will point to a `jar` or `dll` (this is wishful thinking on my part, but unless the `pos` is outright `null`, I wouldn't know what else it could point to).

**Comment by Simn** [comment]
I don't think this is worth the effort, or memory.
