### ISSUE TITLE
Unicode comparison returns false

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/haxe#10370]
Given this test app:

```haxe
import haxe.io.Bytes;

class Test {
  static function main() {
    var myBytes = Bytes.ofString("\000a");
    trace(myBytes.toString() == "\000a");
  }
}
```

the output (on js target) is false. Moreover an "insane" amount of js is generated (https://pastebin.com/JWwmwHdA), is this intentional, or an oversight? Seeing as js would presumably understand these native strings it seems heavy (it also doesnt work).

Cheers,
Ian

**Comment by RealyUniqueName** [comment]
It's because `\000` is a zero byte. And `Bytes.toString()` stops string encoding at zero byte.

**Comment by ianharrigan** [comment]
Ah, ok, thanks for the clarification.

**Comment by kevinresol** [comment]
I bumped into this too in the past. But iirc instead I was doing `bytes.toString()` targeting js which does not terminate on null byte.

Back then the recommended way was `new BytesInput(bytes, 0).readUntil(0)`. I guess that would be the safe way to do null-terminated string on all platforms?

**Comment by 9Morello** [comment]
I also bumped into this when attempting to write a SQLite driver for `record-macros` when targeting node.js. This comparison returns `true` on every platform except JS and Hashlink. Interestingly enough, [the test suite](https://github.com/HaxeFoundation/record-macros/blob/aa7703f18cf5ec5af584e237fb333b4d567c478a/test/CommonDatabaseTest.hx#L421) seems to expect this:

```
#if hl
Assert.equals(haxe.io.Bytes.ofString("\000a").toHex(), cls1.bytes.toHex());
#else
Assert.equals("\000a", cls1.bytes.toString());
#end
```
This test passes on every platform supported by `record-macros` that I tested (Neko, HL, CPP).
