### ISSUE TITLE
inline function struct type not matching

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10383]
I get a `{ result : String, code : Int } should be { err : String, code : Null<Int> }` compiler error.

```haxe
abstract Test({path:String}) {
	public inline function new(path:String) {
		this = {path: path};
	}
	public inline function exec(?args:Array<String>, ?detached:Bool):{code:Int, ?err:String, ?result:String} {
		try {
			var p = new sys.io.Process(this.path, args, detached);
			var c = p.exitCode();
			if(p.exitCode() != 0) return {code: c, err: p.stderr.readAll().toString()};
			return {code: 0, result: p.stdout.readAll().toString()};
		} catch(e:Any) return {code: -1, err: e};
	}
}
```

```haxe
class Main {
	static function main() {
		var res = new Test('test').exec();
		if(res.code == 0) {
			trace(res.err);
		}
	}
}
```

**Comment by Simn** [comment]
```haxe
class Main {
	static function main() {
		exec();
	}

	static inline function exec():{a:Int, ?b:String, ?c:String} {
		if (Math.random() > 0.5) {
			return {a: 0, b: ""};
		}
		return {a: 0, c: ""};
	}
}
```

This has to do with the inliner rewriting the expression to `if (...) return else return` in order to avoid the non-final return error.

I've always wondered why we do that during inlining instead of immediately during typing. We know that the function is `inline` while typing it, so this should be a much cleaner approach anyway.

**Comment by Simn** [comment]
I disagree with myself from October because we now have expression-level `inline`, so we'll have to deal with this when inlining in the general case.

**Comment by Simn** [comment]
I noticed that this works now, so I've added a test. To be honest I'm not sure what fixed this, but oh well!
