### ISSUE TITLE
Compile Haxe project into JS files folder rather than single JS file 

### ISSUE THREAD

**Issue by AAChartModel** [HaxeFoundation/haxe#10381]
Is it possible to compile multi-files Haxe project into JS files folder rather than single JS file ?

When the Haxe project have too many class files, the final compiled single JS file code lines is too long to be managed.

Of course, Lua and python targets have the same problem.

**Comment by Simn** [comment]
This isn't possible directly. Check out projects like https://github.com/elsassph/haxe-modular.

**Comment by kLabz** [comment]
Maybe take a look at https://github.com/benmerckx/genes too

**Comment by 1226085293** [comment]
> 

Why not merge haxe-modular into haxe? Then provide the compilation configuration to choose whether to package it as a single file. It has to be said that the Bundle mechanism of the game engine cannot be realized by using a single script file at all. At least JS can still use haxe-modular, while Lua has nothing...
