### ISSUE TITLE
Restricting enum construction access

### ISSUE THREAD

**Issue by GHanehoj** [HaxeFoundation/haxe#10386]
Hi,

I've been looking for a way to restrict the construction of an enum type to a single (or few) classes. The reason is, that I want to formalize the construction of enum values of this type through a factory, that would eg. check that the parameter values are legal.

I'll give a quick (somewhat arbitrary) example. Suppose the following enum is defined
```haxe
enum SomeValue {
    PositiveFloat(v: Float);
    Integer(v: Int);
    ...
}
```
and I want to ensure that for all instantiations of `SomeValue` we ensure various constraints, eg. that the value in a `PositiveFloat` is actually positive. In essence, i want to create a factory for `SomeValue`'s, that check these constraints and only return a `SomeValue` if the inputs are legal;
```haxe
class SomeValueFactory {
    public static function newPositiveFloat(f : Float) {
        if(f == null || f <= 0) return null;
        else return PositiveFloat(f);
    }
    ...
}
``` 

As far as i can see, this pattern is not possible, as making the enum `private` makes the type inaccessible from other modules (we want to work with `SomeValue`'s from elsewhere, just not instantiate them).

As a last example, this is easily achievable with classes;
```haxe
class SomeClass {
    @:allow(SomeClassFactory)
    private function new () {}
    ...
}

class SomeClassFactory {
    public static function newSomeClass() {
        // some checks
        return new SomeClass();
    }
}
```

Here, the class type is visible to everyone, but the instantiation access is only allowed for the factory. I'm looking for something equivalent for enums. Am I missing something that makes this possible, or is it a missing language feature?

**Comment by RealyUniqueName** [comment]
You can define an abstract like this and use it instead of `Float`:
```haxe
abstract PFloat(Float) to Float {
  @:from static inline function fromFloat(v:Float):PFloat 
    return v < 0 ? throw new haxe.exceptions.ArgumentException('v') : new PFloat(v);

  inline function new(v:Float)
    this = v;
}

enum SomeValue {
  PositiveFloat(v:PFloat);
}
```
Closing as this is not an issue, but a question for https://community.haxe.org/
