### ISSUE TITLE
Can haxe be compiled directly into WebAssembly to speed up performance? Or compile to c++ first and then compile to WebAssembly to improve web side performance

### ISSUE THREAD

**Issue by WREQI** [HaxeFoundation/haxe#10390]
Can haxe be compiled directly into WebAssembly to speed up performance? Or compile to c++ first and then compile to WebAssembly to improve web side performance

**Comment by Simn** [comment]
No.

**Comment by haxiomic** [comment]
@WREQI  This question comes up often, it's a good one but presently a webassembly target wouldn't be advantagous (but perhaps will be one day as WebAssembly evolves)

Explanation: 
https://community.haxe.org/t/haxejs-webgl-wasm/2717/2?u=haxiomic
