### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by Normalhuman1475** [HaxeFoundation/haxe#10407]
I am trying to use haxe 4.1.5 for a FNF mod for linux and it wont let me install haxelib and everytime i run it, it just says this
![image](https://user-images.githubusercontent.com/89854107/134983829-9aa1b5cf-6c9d-4c1f-bb05-57b0e982f63d.png)
Please help ASAP

**Comment by RealyUniqueName** [comment]
This is a question for community channels.
[Forum](http://community.haxe.org/)
[Discord](https://discordapp.com/invite/0uEuWH3spjck73Lo)
[Gitter](https://gitter.im/HaxeFoundation/haxe)
