### ISSUE TITLE
Generic is required for valid code but compiler doesn't abort with error

### ISSUE THREAD

**Issue by PtrMan** [HaxeFoundation/haxe#10404]
```
// compile and run with
// haxe --run BUGask0 --interp

class BUGask0<T> { // SHOULD NOT BE VALID WITHOUT @:generic !
    public static function main() {}
}
```

Expectation: doesn't compile because generic isn't complete <br />
Reality: does compile and run on dynamic targets but fails to compile with static type targets <br />

**Comment by Simn** [comment]
Either your example is incomplete or I don't understand what you're reporting...

**Comment by PtrMan** [comment]
How can anything be generice with `<T>` if it doesn't have a `@generic` decorator, doesn't make any sense to me! <br />
Oh and it generated wrong code for the java target...

**Comment by Simn** [comment]
Check out [the haxe manual](https://haxe.org/manual/type-system-generic.html) to see what `@:generic` does.

Also, your example compiles to Java just fine. Closing because I don't think there's an issue here.
