### ISSUE TITLE
Sys.environment has different behaviour between platforms

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10401]
On Python and C#, the map returned by `Sys.environment()` is kept up to date if new variables are set or removed. On other platforms this is not the case.

This is the case with Python because it natively does this. However, for C# this is not done natively and the Haxe wrapper code goes out of its way to do this.

**Comment by tobil4sk** [comment]
Example to explain what is going on:
```haxe
final env = Sys.environment();
trace(env["TEST"]); // null

Sys.putEnv("TEST", "value");

trace(env["TEST"]); // still null on most targets, but "value" on python and cs
```

Rerunning `Sys.environment()` obviously gives an up to date map on each target.

Also, on python only, updating the map actually updates the environment variable as well:
```haxe
trace(Sys.getEnv("TEST")); // null

final env = Sys.environment();
env["TEST"] = "value";

trace(Sys.getEnv("TEST")); // "value" on python, still null everywhere else
```
~~This is again because python's os.environ dictionary modifies the environment when updated.~~ Replicating this behaviour on other targets would be more complicated than removing it from the python target.

EDIT: The behaviour on python is due to the haxe code not due to native python.

**Comment by RealyUniqueName** [comment]
I think `Sys.environment()` should return a fresh _copy_ of environment variables. Otherwise it's prone to subtle bugs when some remote part of a project modifies it while another part of a project does not expect that.

And `Sys.putEnv` should affect future results of `Sys.environment()`.

**Comment by tobil4sk** [comment]
That makes sense to me, so all that would take is making sure that C# and python return copies. (That would address the second python example as well, as there would be no way of updating the actual environment through a copy of the map)

The second thing you said is already the case everywhere fortunately.

**Comment by tobil4sk** [comment]
Turns out java was also returning the internal map, however as java doesn't have `Sys.putEnv()` this is only an issue because the map can be modified. (So future `Sys.environment()` calls would return the modified map which would not reflect the actual environment).
