### ISSUE TITLE
JvmCode.EmptyStack 

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10405]
0c89b91

The following code will produce `JvmCode.EmptyStack`

```haxe
extern interface Overloaded {
	overload function onEvent(v:Int):Void;
	overload function onEvent(v:String, opt:Bool):Void;
}
class Main implements Overloaded {
	static function main() {}
	public overload function onEvent(v:Int) {}
	public overload function onEvent(v:String, opt:Bool) {
		trace({v: try '' catch(_) null});
	}
}
```

However, it will compile fine if the order of the 2 onEvent implementations are reversed.

**Comment by Simn** [comment]
```haxe
class NotMain {

	public overload function onEvent(v:Int):Void {}

	public overload function onEvent() {
		trace(try '' catch (_) null);
	}
}

function main() {}
```

The overloads are relevant because, as it turns out, the analyzer doesn't run on overloads and thus doesn't clean up the code. However, this shouldn't fail regardless, so there must also be a problem related to the try/catch handling in genjvm.

**Comment by Simn** [comment]
Actually it's not specific to try/catch:

```haxe
class NotMain {

	public overload function onEvent(v:Int):Void {}

	public overload function onEvent() {
		var b = Math.random() > 0.5 ? 1 : throw "no";
	}
}

function main() {}
```

I'll rely on the analyzer transformation here because otherwise I would have to deal with this entire terminating-statements-in-value-places-situation in the generator again, which seems annoying and pointless.
