### ISSUE TITLE
Completion request on first structure fields

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10414]
Default Haxe project with this `Main.hx`:
```haxe
function main() {
	final a = 1;
	final longerName = 2;
	final obj:{
		foo:Int,
		bar:Bool
	} = {
		// If you remove `a,` and request completion, it shows `bar`:
		// foo: |
		foo: a,
		bar: true
	}
	// if you remove `a,` and start writing `longerName` completion works,
	// but you need to know existent variable name
	// (can be annoying if you want to see all enum values, as example)

	final obj:{
		foo:Int,
		bar:Bool
	} = {
		// If you remove `a` without comma and request completion,
		// it shows `a`, `longerName` and other values:
		// foo: |,
		foo: a,
		bar: true
	}
}
```

**Comment by RealyUniqueName** [comment]
This happens because what compiler sees is actually `{foo: bar: true}`. The value for `foo` is set to `bar` identifier and `: true` is discarded because at this point comma is expected.
All of that makes sense to me. I doubt we should change this. @Simn ?

**Comment by RealyUniqueName** [comment]
Hm... But the cursor is placed _before_ `bar`, so we can actually detect that it's in expr position for sure.

**Comment by RblSb** [comment]
There is still problem with good completion on `--js` and other targets, that full of types:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/8753432/139373173-f1b39f2d-d16f-4055-ab46-93481c876a8a.png">
Also example with non-basic type just as alternative check.
```haxe
class Container {
	public function new() {};
}
class Main {
	static function main() {
		final rockC = addContainer();
		addSprite({
			container: rockC,
			// container: |
			// container: |,
			frame: ""
		});
	}
	static function addContainer():Container return new Container();
	static function addSprite(obj:{
		container:Container,
		frame:String
	}):Void {}
}
```

**Comment by RblSb** [comment]
Reopen please!

**Comment by RealyUniqueName** [comment]
That looks like a different issue.

**Comment by Simn** [comment]
Yes I was a bit confused too so I reopened for clarification mostly. It does seem like the structure syntax is required to reproduce this particular case, but I'm not sure what is going on.

**Comment by RblSb** [comment]
This problem is also fixable with `"haxe.maxCompletionItems": 2000` on 4.2.5.
But on nightly you dont get same locals completion anymore on hotkey request even with this.
See https://github.com/HaxeFoundation/haxe/issues/10414#issuecomment-954410330
With `container: |` (or `container: |,`) request there is no `rockC` in completion list before you start typing it.

**Comment by Simn** [comment]
The version with the `,` works for me. It doesn't work if the `container` field is defined twice though, which is a corner case.

**Comment by Simn** [comment]
Right, without the comma this is parsed as `{ container: frame }` and then the compiler doesn't understand anymore what's going on.

**Comment by RblSb** [comment]
Hm, i'm getting different completion results on 4.2.5 vs latest commit (second)
<img width="557" alt="image" src="https://user-images.githubusercontent.com/8753432/161010479-76af7edc-23be-4f7b-89e4-52b7536ec13a.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/8753432/161010619-4033bbec-3e29-4f28-96ab-2ead6dfd83fd.png">
There is also `DisplayProcessingGlobals.Completion("[]")` permanent error in problems panel when i use nightly binary. 
```hxml
--class-path src
--main Main
-D analyzer-optimize
--dce full
--interp
```
I guess this problem means there is no completion from compiler. Error is here since ["Rework internal frontend part 2"](https://github.com/HaxeFoundation/haxe/commit/793d63d97a8d6e448184d816d49e68364cdcf419) commit. Maybe you have some suggestions about specific (platform-specific/etc) changes to revert in that commit and test firstly. I'm getting this problem on macos-arm 11.6.4.

**Comment by Simn** [comment]
I'm seeing this:

![Code_9VLkqmch53](https://user-images.githubusercontent.com/634365/161019238-b9b84777-34d9-40f4-a842-7a21057679e2.png)

I don't know why that would be different for you...

**Comment by Simn** [comment]
Thank you for the investigation, please try again now.

I couldn't reproduce the problem because it was actually avoided by having `OCAMLRUNPARAM=b` defined.

**Comment by RblSb** [comment]
It works, thanks!

**Comment by Simn** [comment]
Thank you for finding that, this one would actually have been a bit embarrassing to release like that.

I'm kinda curious why the tests haven't caught this, but oh well...

**Comment by RblSb** [comment]
There is another one case, but maybe minor one...
```haxe
typedef Foo = {
	?someField:String,
	?secondField:Int,
}

function main() {
	final foo:Foo = {
		|
		secondField: 10,
	}
}
```
If you make completion request there will be field suggestion, but if you start writing field name or make completion request at `some|` instead, there is top-level things only. Is this possible to handle?

**Comment by RblSb** [comment]
I think this latest part should be fixed... Another case:
```haxe
class Main {
	static function main() {
		foo({
			pa|
			margin: 1
		});
	}
	static function foo(s:{
		?padding:Float,
		?margin:Float,
	}):Void {}
}
```
Some ideas how to detect newline on ide/compiler level or force request to something like `{|, margin: 1}`?
