### ISSUE TITLE
Splitting string with bytes above 80

### ISSUE THREAD

**Issue by l0rb** [HaxeFoundation/haxe#10418]
This line:
`var tmp = Bytes.ofHex("806565").toString().split("");`

leads to the following error in php:
`Fatal error: Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in [...]/lib/Array_hx.php:32`

If the hex that is used to make the string is instead "796565" or any smaller hex, there is no error. If it's anything above "80----" the error reappears.

Tested with haxe4.2 and php7.4

**Comment by RealyUniqueName** [comment]
Haxe's String API is only guaranteed to work for valid UTF8 strings.
Check if bytes represent a valid UTF8 string:
```haxe
trace(UnicodeString.validate(haxe.io.Bytes.ofHex("806565"), UTF8); // false
```
You can ignore UTF8 encoding by using native PHP functions:
```haxe
php.Lib.toHaxeArray(php.Global.preg_split('//', bytes.toString(), -1, php.Const.PREG_SPLIT_NO_EMPTY));
```
but in this case you may get splits in the middle of a UTF8 character.
