### ISSUE TITLE
String.prototype alterations from Std Lib

### ISSUE THREAD

**Issue by remiX-** [HaxeFoundation/haxe#10410]
Hey guys,

We have noticed a odd issue when using raw `JavaScript` code alongside Haxe built output code. The problematic Haxe output appears to come from [Std.hx](https://github.com/HaxeFoundation/haxe/blob/6eb36b2aa38591203005ea30f8334e41de292111/std/js/_std/Std.hx) where it alters `String.prototype.__class__`

The main problem area here is a for loop over a string, which is just as simple as this:

```js
for (var s in '') console.log(s)
```

Full Test Code (https://try.haxe.org/#F2885040):
```haxe
class Test {
	static function main() {
		trace("Haxe is great!");

		var n = cast("5", String); // including this to add the code due to DCE, otherwise remove this if no DCE
		trace(n);

		js.Syntax.code("var t = '50';for (var s in t) console.log(s)"); // will log __class__
		js.Syntax.code("for (var s in '') console.log(s)"); // will log __class__
		js.Syntax.code("['1', '2'].forEach(x => console.log(x))"); // forEach is fine

		trace(' -> apply polyfill fix');

		js.Syntax.code("Object.defineProperty(String.prototype, '__class__',{value:String.prototype.__class__, enumerable: false})");
		js.Syntax.code("var t = '50';for (var s in t) console.log(s)");
		js.Syntax.code("for (var s in '') console.log(s)");
	}
}
```

In which the output is:
![image](https://user-images.githubusercontent.com/2831747/135437721-43fabb10-c467-40f0-bafe-c6140f022abd.png)

The case here is that we have Built haxe code causing this and affecting other JS that is not in our control.

**Comment by Simn** [comment]
I have applied your fix in our standard library, which should address the issue. Keeping this open to figure out how to write a test for this.
