### ISSUE TITLE
Improve display for ExprOf

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10429]
Currently i have two functions.

```haxe

typedef MatrixStruct = {
    test:String
};

public function createWithoutMacros(matrix:MatrixStruct) {
    return this;
}
public macro function createWithMacros(tthis:Exp, matrix:ExprOf<MatrixStruct>) {
    return tthis;
}
```

Without macros i get a autocomplete for fields:
![grafik](https://user-images.githubusercontent.com/44057030/137078333-a2e1c839-2b03-4212-ab09-d280e89bbbab.png)
![grafik](https://user-images.githubusercontent.com/44057030/137078563-e0a1681a-5463-4733-89ad-0123cbe83c1d.png)

With macros:
![grafik](https://user-images.githubusercontent.com/44057030/137078716-9f351efc-4f8f-41d8-a99e-2ba385e53885.png)
![grafik](https://user-images.githubusercontent.com/44057030/137078789-79c9a164-ecf2-43ae-9c19-1e63f5159259.png)

also enums do not work. etc.

**Comment by RealyUniqueName** [comment]
Please provide a complete sample. It's hard to figure out what's going on based on screenshots of incomplete expressions.

**Comment by lublak** [comment]
@RealyUniqueName its just the same wrapped in a class

```haxe
class Main {
  static function main() {
    Macro.createWithMacros(|);
    Macro.createWithoutMacros(|)
  }
}
```

```haxe
class Macro {
  public static function createWithoutMacros(matrix:MatrixStruct) {
      
  }
  public static macro function createWithMacros(matrix:haxe.macro.Expr.ExprOf<MatrixStruct>) {
    return macro {};
  }
}
```

```haxe
typedef MatrixStruct = {
    test:String
};
```

**Comment by RealyUniqueName** [comment]
Something became broken between 4.0 and 4.1. 
With 4.0 compiler emits this for signature completion on `Macro.createWithMacros`:
```haxe
public static macro function createWithMacros(matrix:String):Dynamic
```
And with 4.1:
```haxe
public static macro function createWithMacros(matrix:haxe.macro.Expr):haxe.macro.Expr
```
We have these lines which specifically erase `ExprOf` information:
https://github.com/HaxeFoundation/haxe/blob/30d639bca164e6d00dbd3a1d342f34b149c5945c/src/typing/typeloadFields.ml#L1178-L1183
But these lines are much older than 4.0 and yet during debugging session I see this is the place where the `ExprOf` is lost.

**Comment by RealyUniqueName** [comment]
Bisected to 92a707446b361bdceae6234c2dde0e6c42939236

**Comment by Simn** [comment]
Hmm yeah, interesting... this is basically the opposite of #7703.

**Comment by Simn** [comment]
This is a bit tricky because what context we want to get the type from depends on the type:

```haxe
import haxe.macro.Expr;

typedef ArgType = {
	var f:String;
}

class Main {
	public static function main() {
		foo(|);
	}

	static macro function foo(s:String, e:ExprOf<String>, o:ArgType) {
		return macro {};
	}
}
```

what | non-macro | macro
--- | --- | ---
s:String | Dynamic | **String**
e:ExprOf<String> | **String** | Expr
o:ArgType | Dynamic | **ArgType**

We could probably type `String` and such properly in non-macro context as well, but the third case still remains anyway.

**Comment by Simn** [comment]
My change now gives the correct signature. The original example still doesn't work, but I think that's just because toplevel completion doesn't work in macro arguments at all. This is a bit similar to #7699.

**Comment by Simn** [comment]
That part kinda duplicates #9421 which kinda duplicates #7699, closing here.
