### ISSUE TITLE
[jvm] `sys.FileSystem.stat()` returns incomplete data

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxe#10423]
With HashLink, JavaScript and PHP (tested on a Linux OS):

```haxe
var stat = sys.FileSystem.stat("my_file.sh");
trace(stat.mode); // 33277
trace(stat.gid); // 1000
trace(stat.uid); // 1000
trace(stat.dev); // 2050
trace(stat.ino); // 919177
```

But with JVM:

```haxe
trace(stat.mode); // 0
trace(stat.gid); // 0
trace(stat.uid); // 0
trace(stat.dev); // 0
trace(stat.ino); // 0
```

Is this an expected behavior?
Same issue on Windows: `stat.gid` and `stat.uid` are obviously `0`, but `stat.mode` is `33206` with HL/JS/PHP while it is always `0` with JVM.

**Haxe 4.2.3**

**Comment by cedx** [comment]
https://github.com/HaxeFoundation/haxe/blob/development/std/java/_std/sys/FileSystem.hx#L40
It seems that `java.io.File` does not provide this data. Could it be possible to switch to `java.nio.Files` (especially the `readAttributes` method)?

**Comment by Simn** [comment]
I have no idea, but feel free to try that!

**Comment by RblSb** [comment]
Btw, i think we should wrap such call in try-catch with current fallback, if we want support before android 8.0

**Comment by cedx** [comment]
@Simn & @RblSb done in #10442.
Probably a naive implementation because I'm a web developer: I usually code only in JS and PHP (and Haxe, of course!).
