### ISSUE TITLE
bypassAccessor  Cannot access field or identifier for writing

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10422]
Currently bypassAccessor not works ~anymore~ with `never`. ~Worked in haxe 3.2.1: https://try.haxe.org/#5dcAf7e3~

```haxe
class Test {
	public var hmm(default, never):String;
	public function new() {
		@:bypassAccessor hmm = '';
	}
}
```

**Comment by Gama11** [comment]
That seems to have been some bug related to metadata, considering `@:bypassAccessor` didn't exist back then and even `@:foobar` "works". ;)

**Comment by lublak** [comment]
@Gama11 Oh that interesting. I noticed it through the other issue: https://github.com/HaxeFoundation/haxe/issues/10421
Where I then tried to remove the warning by using bypassAccessor. Which then did not work. So I looked how it was with the old Haxe version.
I have then just assumed so. :P

**Comment by RealyUniqueName** [comment]
`@:bypassAccessor` was designed to bypass `get_`/`set_` functions. It's not supposed to bypass `never`.
The documentation of `@:bypassAccessor` says: 
> Do not call property accessor method and access the field directly.

**Comment by RealyUniqueName** [comment]
You can either set the value on the declaration site:
```haxe
public var hmm(default,never):String = 'hello, world';
```
or (not recommended) use `untyped` to bypass type system alltogether:
```haxe
untyped this.hmm = 'hello, world';
```
