### ISSUE TITLE
Allow @:to macros

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10425]
Currently it is not possible to use to macros for :to casting with Context.getExpectedType().
Sometimes it would be really handy.
The other way around (@:from) is already allowed.

**Comment by RealyUniqueName** [comment]
Please, provide a working sample and what result do you expect to see.

**Comment by lublak** [comment]
@RealyUniqueName 

currently this works with a function call:

```haxe
abstract Test(Dynamic) {
	public function new() {
		this = null;
	}
	public macro function to(tthis:haxe.macro.Expr) {
		trace(Context.getExpectedType()); // TInst(String,[])
		return macro null;
	}
}
```

```haxe
class Main {
	static function main() {
		var t = new Test();
		var r:String = t.to();
	}
}
```

what i want is "simply" that @:to also works with macro function.

```haxe
abstract Test(Dynamic) {
	public function new() {
		this = null;
	}
	@:to public macro function to(tthis:haxe.macro.Expr) {
		trace(Context.getExpectedType()); // TInst(String,[])
		return macro null;
	}
}
```

it shows me a compiler error: `to: Macro cast functions are not supported`

also this works fine:

```haxe
class Main {
	static function main() {
		var t:Test = '';
	}
}
```

```haxe
abstract Test(Dynamic) {
	public function new() {
		this = null;
	}
	@:from public static function test(arg:String) {
		return null;
	}
}
```

but this shows me a compiler error (`String should be Test`):

```haxe
class Main {
	static function main() {
		var t:Test = '';
	}
}
```

```haxe
abstract Test(Dynamic) {
	public function new() {
		this = null;
	}
	@:from public static macro function test(arg:haxe.macro.Expr) {
		return macro null;
	}
}
```

it would be useful especially for types that are generated dynamically via macros.

**Comment by Simn** [comment]
This would require a haxe-evolution. However, I'm inclined to find this a bit too magical.

**Comment by lublak** [comment]
@Simn :) okay. Sometimes it's hard to me to figure out if it is a haxe evolution or just a feature request. So   sry and thank you.

And: Haxe is a magical language after all. So it should fit perfectly :P
