### ISSUE TITLE
Abstract type with getter doesn't unify with constrained type parameter

### ISSUE THREAD

**Issue by MoritzBrueckner** [HaxeFoundation/haxe#10424]
When using an abstract type for a constrained type parameter, the compiler doesn't seem to take the fields of the abstract type into account even though they should be known during compile time.

Example:
```haxe
class Test {
	static function main() {
		var a = new MyAbstract("test");

		trace(a.length); // This works

		test(a); // This doesn't, even though `test.T` is only constrained to `length`
	}

	// Because test() is @:generic, it should work to replace the access of `length`
	// with the correct getter implementation.
	@:generic
	static function test<T:{var length(get, never):Int;}>(a:T) {
		trace(a.length);
	}
}

abstract MyAbstract(String) {
	public var length(get, never):Int;

	public function new(val:String) {
		this = val;
	}

	public function get_length():Int {
		return 4;
	}
}
```
(https://try.haxe.org/#cAd2f5ce)

Compilation fails with 
```
Test.hx:7: characters 8-9 : MyAbstract should be { length : Int }
Test.hx:7: characters 8-9 : ... For function argument 'a'
```

**Comment by RealyUniqueName** [comment]
It works as expected.
Abstract type does not exist at run time, it's just a compile-time decorator. While `<T:{var length(get,never):Int;>` requires an instance of a type, which exists at run time.

**Comment by Aurel300** [comment]
@RealyUniqueName But the method is `@:generic`: it should be possible to generate the code correctly for any abstract type.

**Comment by MoritzBrueckner** [comment]
> But the method is @:generic: it should be possible to generate the code correctly for any abstract type.

Yes, I think so as well. It should be totally possible during compile time (where the abstract type exists) to check which generic function variant to call depending on the type on which it is called. Of course this is only true as long as `@:generic` and "regular" generic functions are not required to be 100% the same feature-wise, so the above code will only work with `@:generic` then.

**Comment by RealyUniqueName** [comment]
How would you define a constrain for `var length(get,never):Int` if `test` was not `@:generic` but designed for abstracts?

**Comment by MoritzBrueckner** [comment]
That wouldn't work without additional overhead I guess. So it's by design that generic functions always behave the same, independent of whether `@:generic` is used or not? Code should always compile and don't break if `@:generic` gets removed? Why not use the full advantages of `@:generic`?

**Comment by RealyUniqueName** [comment]
It's not about `@:generic`. It's about the constrain. 

`{var something(get,never):Int;}` describes an object with `get_something` instance function. While getters of an abstract type are static functions.

When compiler sees `function test<T:{var something(get, never):Int;}>(a:T) return a.somethig;` it compiles it to `function test<T:{var something(get, never):Int;}>(a:T) return a.get_somethig();`. But a getter  of an abstract type should be compiled to `MyAbstract.get_something(a);`.

**Comment by Aurel300** [comment]
@RealyUniqueName Is `@:generic` happening too late or something? What both me and @MoritzBrueckner seem to be wondering is, why can we not generate:

```haxe
function test_Foo(a:Foo) return a.get_something();
function test_SomeAbstract(a:SomeAbstract) return SomeAbstract.get_something(a);
```
