### ISSUE TITLE
abstract function new not shows an error if its not implemented

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10426]
Currenlty if you create a abstract class like this:

```haxe
abstract class Test {
  public abstract function new();
}
```

And you use it like this:

```haxe
class AnotherTest extends Test {
  
}
```
 No compiler error is throwing.

**Comment by Geokureli** [comment]
just curious, did we forbid abstract constructors because we can't throw an error in the case above? is there plans to try and fix this later?

**Comment by nanjizal** [comment]
No if you read the comments in 'closed' they have changed behaviour to fit with java, this is a regression for me and makes my recent use of abstract class a waste of time and breaks my haxelib, pretty sure I will avoid them in future.  I think this change should have gone through evolution as it breaks users code and is not just a tweak.

**Comment by Simn** [comment]
Stop being a drama queen, the change doesn't even affect the code you pointed to. The only problem here is that the commit message is somewhat ambiguous. Abstract classes can still have constructors, they just cannot have _abstract_ constructors.
