### ISSUE TITLE
Method createWithMacros not found on

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10430]
Currenlty i have a small class

```haxe
class Test {
 public macro function createWithMacros(tthis:Exp, matrix:ExprOf<TargetType>) {
      return tthis;
  }
}
```

```haxe
var t = new Test();
t.createWithMacros();
```

i get an error: `Method createWithMacros not found on class Test`

**Comment by RealyUniqueName** [comment]
Most likely you're missing `#if macro` and/or `#if !macro` somewhere.
Anyway it's not a compiler issue. It's a question for community channels.
