### ISSUE TITLE
Consistency of `Sys.getCwd()` between platforms

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10459]
The following targets return the current working directory with a trailing slash: hl, cpp, eval, neko, php, java.

The following do not: python, cs, lua, nodejs.

This is an issue as it means that you cannot depend on stuff like this:
```haxe
Sys.getCwd() + "dir/"
```
being consistent across targets.

Would be easy to clean up, just requires a decision on which to go for.

**Comment by haxiomic** [comment]
I guess a trailing slash is preferred as the safer option?

I'd say make a PR with one of the two and we can discuss the best before merging

**Comment by Simn** [comment]
I have discussed it with myself and concluded that it's the best.
