### ISSUE TITLE
EReg named groups

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#10452]
Is there a design reason why EReg only supports numbered group matching? I can imagine named group matching being useful on targets other than NodeJS.

**Comment by Simn** [comment]
I never used named groups personally, but if there's a common syntax for it across all targets then I see no reason not to support it design-wise. Of course, somebody would have to actually implement that.

**Comment by lublak** [comment]
here a small uncomplete list (most people use: `(?<name>)` and `\k<name>`):

```
js: (?<name>)
java: (?<name>)
php: (?<name>) or (?P<name>) or (?'name')
python: (?P=name)
cs: (?<name>) or (?'name')
lua/cpp: (?<name>) or (?'name') or (?P<name>)
```

backreference named capture goup:

```
js: \k<name>
java: \k<name>
php: (?P=name) or \k<name> or \k'name' or \k{name} or \g{name} or \g<name> or \g'name'
python: (?P=name)
cs: \k<name> or \k'name'
lua/cpp:  \g{name}
```

**Comment by Simn** [comment]
See #10453
