### ISSUE TITLE
haxe.EnumFlags Toggle

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10473]
I often have to do this kind of pattern on haxe.EnumFlags:

```haxe
		if( b )
			element.flags.set(Flag);
		else
			element.flags.unset(Flag)
```

Could we add a toggle API so we can do:

```haxe
element.flags.toggle(Flag, b);
```

**Comment by Simn** [comment]
Agreed, but "toggle" suggests to me an API that sets the flag if it isn't set and unsets the flag if it is...

**Comment by nanjizal** [comment]
so it's like a switch on condition, so perhaps one of these:
```Haxe
elements.flags.tradeOn( b, Flag  );
elements.flags.swapOn( b, Flag );
elements.flags.changeOn( b, Flag );
```

**Comment by Aurel300** [comment]
```haxe
element.flags.setTo(Flag, b);
```
