### ISSUE TITLE
Type not found : flash.xml.XMLNode

### ISSUE THREAD

**Issue by fatrolls** [HaxeFoundation/haxe#10472]
Type not found : flash.xml.XMLNode

How do I get around this error, I know flash is part of haxe yet it cannot load this library.

```
package org.igniterealtime.xiff.data;

import flash.xml.*;

interface INodeProxy
{

    function getNode() : flash.xml.XMLNode;
    
    function setNode(arg1 : flash.xml.XMLNode) : Bool;
}
```

I also tried this

```
package org.igniterealtime.xiff.data;

import std.flash.xml.*;

interface INodeProxy
{

    function getNode() : std.flash.xml.XMLNode;
    
    function setNode(arg1 : std.flash.xml.XMLNode) : Bool;
}
```

still same result.

**Comment by RealyUniqueName** [comment]
Works for me.
What's the contents of your hxml file?

**Comment by fatrolls** [comment]
the contents are what I wrote in my initial post

here is `INodeProxy.hx`

```
package org.igniterealtime.xiff.data;

import flash.xml.*;

interface INodeProxy
{

    function getNode() : flash.xml.XMLNode;
    
    function setNode(arg1 : flash.xml.XMLNode) : Bool;
}


````

I attached my project if you or anyone wants to try it out yourself.

[omgpop.zip](https://github.com/HaxeFoundation/haxe/files/7531383/omgpop.zip)

**Comment by Aurel300** [comment]
> I know flash is part of haxe

The types in the `flash` package are available when you are actually targeting `swf`. In your project I see you are compiling to `html` using OpenFl. I believe the idea of OpenFl API's is to be very similar to Flash, but there probably isn't a 1-to-1 mapping for every Flash class? You should look through the [OpenFl API docs](https://api.openfl.org/) as well as the [Haxe API docs](https://api.haxe.org/). The latter can be filtered to show only types available on the `html` target. It will not be a drop-in replacement, but there is [`Xml` in the standard library](https://api.haxe.org/Xml.html), for example.

**Comment by nanjizal** [comment]
I will explain further as it can be confusing.

Haxe code can be hooked up to swf internal classes or other languages that have native implementations, the compiler uses 'extern' definitions.  OpenFL has quite good swf polyfill for non swf targets js and c++, and NME polyfills for c++ ( that can be used in browser ). But neither project support the polyfill required for E4X xml support. Perhaps AwayFL has implementation not looked.

Specifically there is no support for E4X in Haxe language, and Haxe offers other approaches to XML.
( https://help.adobe.com/en_US/as3/dev/WS5b3ccc516d4fbf351e63e3d118a9b90204-7e72.html )

Specifically if possible the support for JSON is very good in Haxe, and if you can use this format instead it will be much smoother.  But it is possible in Haxe to write your own XML parsing at character level and even implement your own E4X solution, but would imagine it would be a lot of work and hard to make it very fast.

**Comment by RealyUniqueName** [comment]
Not a Haxe issue.
