### ISSUE TITLE
Implement default type parameters

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#10483]
See https://github.com/HaxeFoundation/haxe-evolution/pull/50

**Comment by Simn** [comment]
The proposal says that this shouldn't work:

```haxe
This shouldn't: class A<B = C, C>
```

Unfortunately, the only reason given is this TypeScript discussion: https://github.com/Microsoft/TypeScript/issues/2175

We'll have to figure out if this is actually a special case because we don't have any ordering constraints on, well, constraints, and I'm not sure why defaults would be different.

**Comment by RealyUniqueName** [comment]
I don't see why that should not be allowed in Haxe. 
OTOH anything optional usually goes to the end of the list. Otherwise one would have to type in some placeholder for skipped params and that reduces the benefit of the feature.

**Comment by kLabz** [comment]
That reminds me about the `class ReactComponent<TProps = {}, TState = {}> {}` case with `ReactComponent<_, MyState>` syntax to use default type parameter for first while defining second. Would that one be acceptable? (it's already how we skip arguments when binding a function for example).

**Comment by Simn** [comment]
Good question... seems like that would make sense and be consistent, so we probably won't do it.

**Comment by benmerckx** [comment]
> Unfortunately, the only reason given is this TypeScript discussion: microsoft/TypeScript#2175

I have no clue what I was thinking linking there, sorry.

Reading this back some years later I think the reasoning for disallowing here was to avoid circular references.

**Comment by Simn** [comment]
This has been implemented in #10518. We can track further issues separately.
