### ISSUE TITLE
Python target: mangle method names using Python conventions 

### ISSUE THREAD

**Issue by iirekm** [HaxeFoundation/haxe#10485]
Use `some_method_name` not `someMethodName` as would be in `.hx` file or in most programming languages.

Unfortunately this issue and lack of copied comments (https://github.com/HaxeFoundation/haxe/issues/9621) make HAXE rather useless for writing cross-platform libraries, it makes sense only for apps (mangling and lack of comments doesn't matter there).

**Comment by Simn** [comment]
You are free to name your methods like that in your Haxe source files as well. We don't do any target-idiomatic renaming and do not plan to introduce it either.
