### ISSUE TITLE
suppress useless pattern check warning

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#10487]
https://haxe.org/manual/lf-pattern-matching-unused.html

I have a macro which tends to generate useless patterns in switch statements. So when I compile my programs, the output is cluttered with `Warning : This case is unused`. Can I suppress that warning without adding complicated logic to the macro that generates the statements?

**Comment by RealyUniqueName** [comment]
There's no way to suppress specific set of warnings in Haxe atm. Except deprecation warnings (`-D no-deprecation-warnings`)

**Comment by NQNStudios** [comment]
Could I PR this?

**Comment by kLabz** [comment]
Actually you can now with `Context.filterMessages()`. See https://try.haxe.org/#10F18962

**Comment by NQNStudios** [comment]
@kLabz That's a big quality of life improvement for me. Thanks!
