### ISSUE TITLE
Implement numeric literal suffixes

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#10481]
See https://github.com/HaxeFoundation/haxe-evolution/pull/92

**Comment by Aidan63** [comment]
I could take a look at implementing this if you'd like. I saw your comment in the separator issue about implementing it as an optional argument to `CInt` and got somewhere with it.

![image](https://user-images.githubusercontent.com/10246746/142474516-c1e33c5b-afa0-4006-a84b-ce1abc53eae1.png)

Don't want to step on anyones toes so I thought I'd put the offer out there before spending more time on it.

**Comment by Simn** [comment]
Sure, that would be appreciated!
