### ISSUE TITLE
Error reporting improvement with final properties

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#10489]
Just a little quality improvement that could help newer developers, currently if you add `get / set` to property to a `final` field you get a missing semi-colon error:

https://try.haxe.org/#02432406
```haxe
final example(get, set): Int;
```
`Test.hx:2: characters 16-17 : Missing ;`

get/set on final doesn't make sense of course but I find I run into this one often as I transition a `final` to a property while refactoring

Ideally it would say like "field must be a far to use getter and setters"

I know this is low priority but want to make a note because it could make for a good practise issue for me to learn how to contribute to the compiler again (one day ™)

**Comment by Simn** [comment]
But maybe you actually wanted a function with two arguments named `get` and `set` and just forgot the `function` keyword... :D

Ultimately, this is just invalid syntax and I don't know if I want to start parsing some invalid syntax and then make assumptions about what the user probably meant...
