### ISSUE TITLE
Unserialize Enum in CS target

### ISSUE THREAD

**Issue by aartzrc** [HaxeFoundation/haxe#10492]
I am having trouble with Unserializer in C#. I'm using Haxe 4.2.4 and Net5 to send some data around and I've hit a spot where the Unserializer always throws an exception (it's actually in a C# cast call, but I believe it's caused by the Unserializer). Here's a snippet:

```haxe
enum ArrayTest {
    Strings(strings:Array<String>);
}

var d = Strings(["s1", "s2"]);
var s = Serializer.run(d);
var d2 = Unserializer.run(s);
trace(d2);
```

During Unserializer.run I recieve this exception:
```
'Object of type 'Array`1[System.Object]' cannot be converted to type 'Array`1[System.String]'.'
```

From what I can gather via debug this is because C# is trying to cast during `haxe.lang.Runtime.callMethod` but the array data has extra values (maybe?) that cannot be converted - this seems odd because the Array appears to be all strings, but possibly there is extra 'placeholder' data that causes trouble. Screen shot showing what I mean:  
![image](https://user-images.githubusercontent.com/36048486/142505066-7c9e2e11-2fc4-4f8b-ac86-a01f27b4923c.png)

Any help would be greatly appreciated. I haven't tested all versions of Haxe but previously I was using 4.0.0 RC2 and this was working.

**Comment by RealyUniqueName** [comment]
This is broken sicne 4.0.0-rc.3

**Comment by aartzrc** [comment]
I ended up creating an `abstract` to handle the conversion to/from an 'object'. This resulted in no code changes outside of the enum definition. Old serialized data is still unreadable and this bug should definitely still be fixed, but hopefully this will help someone.

```haxe
enum ArrayTest {
    Strings(strings:StringArray);
}

abstract StringArray(Array<{g:String}>) {
    inline function new(a:Array<{g:String}>) this = a;

    @:to
    function toArray() return this.map((i) -> i.g);

    @:from
    public static inline function fromArray(a:Array<String>) return new StringArray(a.map((i) -> {g:i}));
}
```
