### ISSUE TITLE
Haxe 4.3.0-rc.1+5e0a029 doesn't support pounds symbols.

### ISSUE THREAD

**Issue by raf13lol** [HaxeFoundation/haxe#10498]
When I do 
```haxe
trace("£");
```
it outputs  ┬ú. This isn't correct.

**Comment by flashultra** [comment]
It works for me  on Javascript, Neko, Hashlink, Eval:  https://try.haxe.org/#7a647880 
What target do you test ?

**Comment by raf13lol** [comment]
windows

**Comment by raf13lol** [comment]
never mind windows powershell is country-ist
