### ISSUE TITLE
Get original expression when typing is required.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10499]
Whenever an expression requires typing before being passed to a macro (i.e. `@:from macro` or static extension macro), the original expression is lost and one receives `@:this this` instead. Would it be possible to make the original expression available, e.g. as `@:this($original) this` or if we're worried of breaking existing code then via some method in `Context`?

**Comment by Simn** [comment]
IIRC you can `Context.typeExpr` the `@:this this` thing and inspect the result. The AST representation is not available anymore at that point.

**Comment by back2dos** [comment]
Indeed, you can get the typed AST. The problem is that it will be substantially altered, as soon as the original expression does anything that goes beyond a very narrow subset of Haxe (that's basically Java), like static extension, overloaded operators, string interpolation, inlining ...
