### ISSUE TITLE
@:bypassAccessor with multiple accesses

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10500]
When doing the following the setter is still called while it feels it should not:

```haxe
@:bypassAccessor obj.field.fieldWithSetter = true;
```

**Comment by RealyUniqueName** [comment]
In that sample `@:bypassAccessor` is applied to `.field`.
I agree that looks counter-intuitive. To me it looks like every accessor in that line should be ignored.

Also there's no way to ignore a setter for `.fieldWithSetter` while keeping a call to `.field` getter without saving `obj.field` in a temp var.

**Comment by ncannasse** [comment]
>Also there's no way to ignore a setter for .fieldWithSetter while keeping a call to .field getter without saving obj.field in a temp var.

you can do `(@:bypassAccessor obj.field).fieldWithSetter = true` which would mean exactly that.

**Comment by RealyUniqueName** [comment]
I meant something like `obj.field(@:bypassAccessor .fieldWithSetter) = true`

**Comment by back2dos** [comment]
I would really expect `@:bypassAccessor` to apply to the topmost expression only (or the whole tree like `@:privateAccess`), but not this ^^

**Comment by kLabz** [comment]
Both seem weird to me, I was expecting `@:bypassAccessor (obj.field).fieldWithSetter = true`

**Comment by RealyUniqueName** [comment]
To clarify, I don't suggest implementing `(@:bypassAccessor .fieldWithSetter)`. I used that just to show what I mean :)

**Comment by Simn** [comment]
I agree that this should apply to the whole chain because that's how it is parsed.

The reason this doesn't work at the moment is because there's some wacky counter implementation that decreases when the field access is typed. It's actually a pretty clever way to handle this, but I still don't think it's a good default behavior.

**Comment by Simn** [comment]
Uhm, I just realized that metadata has lower precedence than assignments, so `@:bypassAccessor x = 1` is parsed as `@:bypassAccessor (x = 1)`. That makes my parsing argument useless because we clearly don't want to bypass anything for the rhs here. Hmm...

**Comment by kLabz** [comment]
Seems like this was fixed (by https://github.com/HaxeFoundation/haxe/commit/4379eea3d527c2866d63b52cb816fcbaa699c84b ?)

https://try.haxe.org/#A1037e81 (works with nightlies)
