### ISSUE TITLE
private access not working with abstract types in different files?

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#10512]
private access not working with abstracts in different files?

If WrapFoo abstract is private, it can only be accessed from WrapWrapFoo if they are in the same file,

uploaded a cut down simplified test, showing the problem.

https://github.com/nanjizal/fooWrapPrivateTest/blob/main/src/testAccess/WrapWrapFoo.hx
```
src/testAccess/WrapWrapFoo.hx:6: characters 23-30 : Type not found : WrapFoo
src/testAccess/WrapWrapFoo.hx:7: characters 36-43 : Type not found : WrapFoo
```

```
git clone https://github.com/nanjizal/fooWrapPrivateTest.git
cd fooWrapPrivateTest
haxe compile.hxml
```
Was unsure how to check if this is known issue, asked on discord but guess it was late so no one replied.

**Comment by nanjizal** [comment]
Haxe Compiler 4.3.0-rc.1+5f599ba on mojave.

**Comment by RealyUniqueName** [comment]
`@:access` and `@:allow` meta modify access to private _fields_.
Private _types_ are accessible only from the same module they are declared in. There's no way to workaround that.
Related issue: #10138

**Comment by nanjizal** [comment]
So private abstract types behave differently than private classes, that seems to go against least expection, since abstract types often used in place of a class, but thanks for clarifying, it's probably documented somewhere but thought access was more powerful. shame but never mind.

**Comment by kLabz** [comment]
Private classes behave exactly like that, you can't access them from outside their modules.
