### ISSUE TITLE
(Java/JVM) `java.util.function` (Functional Interfaces) do not work as in java. 

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [HaxeFoundation/haxe#10515]
Functional interfaces do not work as expected; In java they accept any function, but in haxe it only accepts something that implements it, which requires creating a dummy class. 
Example: https://github.com/TheDrawingCoder-Gamer/hxjava-functional-interfaces
Doing `Foo.doSomething(() -> 1)` in java is perfectly acceptable but the same in haxe raises a type error. 
If possible, maybe allow functional interfaces to be automatically cast to and from haxe functions?

**Comment by Simn** [comment]
#9576

**Comment by TheDrawingCoder-Gamer** [comment]
i knew my search wasn't thorough enough :sob: I can never get any use out of the search tool
