### ISSUE TITLE
[hashlink] code generation of typed catch

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10511]
The following code:
```haxe

enum Stop {
	Test;
}

class Main {


	static function bar() {
		throw "!";
	}

	static function foo() {
		try {
			bar();
		} catch( e : Stop ) {
			Sys.exit(0);
		}
	}

	public static function main():Void {
		foo();
	}

}
```

Produces the following code for Main.foo:

```
		.14    @0 trap 0, 3
		.15    @1 call 1, Main.bar()
		.15    @2 endtrap true
		.15    @3 jalways 10
		.16    @4 call 4, haxe.Exception.caught(0)
		.16    @5 nullcheck 4
		.16    @6 callmethod 3, 4[0]()
		.16    @7 global 5, 10
		.16    @8 call 2, Std.isOfType(3,5)
		.16    @9 jfalse 2,3
		.17    @A int 6,@0
		.17    @B call 1, std@sys_exit(6)
		.17    @C jalways 1
		.16    @D rethrow 0
		.18    @E ret 1
```

Looking at the way the catched exception is handled, we first call haxe.Exception.caught which will allocate a ValueException, then we check the type, then we rethrow the original exception. This lead to a lot of ValueException being allocated at each step (think like hscript which has a lot of try/catch in recursive functions).

This should be changed to something like:

```
@4 global 5, 10
@5 call 2, Std.isOfType(0,5)
@6 jfalse 2, 1
@7 rethrow 0
@8 call 4, haxe.Exception.caught(0)
...
```

So actually checking the type before doing the wrapping.
This would also fix the JIT that does detect the pattern  GLOBAL + Std.isOfType check in order to store at runtime the type that is checked so the debugger can know if the exception will be uncaught or not. With current code the exception is displayed in `foo` catch instead of original `bar` because the debugger assume a catch-all there.

**Comment by RealyUniqueName** [comment]
Actually in that sample wrapping happens at the throw site inside of `bar`.
Here's how `bar` looks after compilation:
```haxe
static function bar() {
  throw haxe.Exception.thrown("!");
}
```

**Comment by ncannasse** [comment]
Sure but if it's a native exception then it won't work, and the debugger issue still remains.

**Comment by ncannasse** [comment]
This required one more fix on HL side so it works in all cases : https://github.com/HaxeFoundation/hashlink/commit/a23b60636df7c916c58c17b4f38ab60b5f6b2b90
