### ISSUE TITLE
Bytes to Utf8 0 char Invalid result

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#10520]
```haxe
function main() {
	var bytes = haxe.io.Bytes.alloc(1); // a single 0 Byte
	trace(bytes.toString().length); // hl,js = 0, eval = 1
}
```
https://try.haxe.org/#A71a2F53 (tested on latest nightly)

On Hashlink and Js it returns a length of 0, however on Eval,Java,Cs,Python,C++,Lua it returns 1. I believe Eval's result is correct because U+0000 is the unicode null character. I tested the same code written in Golang and it also returns a length of 1.

**Comment by RealyUniqueName** [comment]
See #7904 and #8201
