### ISSUE TITLE
[js] Regression wrt accessing instance variables with super.

### ISSUE THREAD

**Issue by Apprentice-Alchemist** [HaxeFoundation/haxe#10521]
https://try.haxe.org/#27410E43
4.1.5 errors with `Normal variables cannot be accessed with 'super', use 'this' instead`.
4.2.x gives an assertion error (`File "src/generators/genjs.ml", line 412, characters 13-19: Assertion failed`).

**Comment by Simn** [comment]
Hmm yes, the check for that is inside a branch that deals with `Method` as opposed to `Var`. I probably screwed that up while refactoring that part. There's another error which shouldn't be reproducible anymore: `Cannot access superclass variable for calling: needs to be a proper method`

**Comment by Simn** [comment]
Reading this again, I have no idea what a "superclass variable" is or how that would ever come about...

**Comment by kLabz** [comment]
I don't think it makes sense for Haxe. It would make sense in languages that allow overriding variables, but we can only override methods.

**Comment by Apprentice-Alchemist** [comment]
The given example crashes most generators on 4.2.x.
Java, C++ and C# error at native compilation.
Neko, Eval, Lua give a compiler failure.
Jvm gives `Error: Invalid super access`.
Only hashlink, php and flash compile succesfully.

Whereas on 4.1.5 it gives `Normal variables cannot be accessed with 'super', use 'this' instead`.
(At least for js, neko, eval and hashlink.)
