### ISSUE TITLE
`@:op(A += B)` and `@:op(A -= B)` do not work properly

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#10539]
Hello,

Using `@:op(A += B)` and/or `@:op(A -= B)` in an abstract do not appear to work properly.

Here is a small example:

```haxe
class Test {
  static function main() {
    trace("Haxe is great!");
    var int:MyAbstract = 1;
    var int2 = 1;
    int2 += int;
    trace(int2);
  }
}

abstract MyAbstract(Dynamic) from Dynamic to Dynamic
{
  @:op(A += B) static function peInt(a:Int, b:MyAbstract):Int
  {
		var int:Int = cast b;
    return a + int;
  }
}
```
https://try.haxe.org/#eD583467

The method `peInt` appears to be called, however the value is not assigned to `int` so it remains at `1` when traced.

Thank you!

**Comment by RealyUniqueName** [comment]
I think it works as expected. Whole `int2 += int` expression is replaced with `peInt(int2, int)`.

**Comment by Simn** [comment]
Indeed, if you overload `+=` the assumption is that you want to implement your own assignment semantics. Otherwise you would just overload `+` instead.
