### ISSUE TITLE
How to ignore the Json string null values by using haxe.Json.stringify() method

### ISSUE THREAD

**Issue by AAChartModel** [HaxeFoundation/haxe#10534]
Test code as follow:

```haxe
class Person {
    public var name: String;
    public var gender: String;
    public var salary: String;
    public var location: String;
    public var company: String;
    
    public function new() {
        
    }
  }

    var testPerson: Person = new Person();
    testPerson.name = "Ada";
    testPerson.gender = "woman";
  
    var personJsonStr = haxe.Json.stringify(testPerson,"\t");
  
    trace(personJsonStr);
```

the `personJsonStr` always has null values in console as follow:

```haxe
src/Main.hx:29: {
	"gender": "woman",
	"name": "Ada",
	"company": null,
	"location": null,
	"salary": null
}
```

However, I only want to get the Json string **without null values** like this:

```haxe
 {
	"gender": "woman",
	"name": "Ada",
}
```

What should I do to get it ?

**Comment by RealyUniqueName** [comment]
You can iterate over [Reflect.fields](https://api.haxe.org/Reflect.html#fields) and use [Reflect.deleteField](https://api.haxe.org/Reflect.html#deleteField)
Anyway this is a question for https://community.haxe.org/

**Comment by RblSb** [comment]
Json class is very tiny abstraction, so there is no such feature out of box. But want to mention this simple hack for `js` target:
```haxe
final json = Json.stringify(data, filterNulls, "\t");
...
function filterNulls(key:Any, value:Any):Any {
	#if js
	if (value == null) return js.Lib.undefined;
	#end
	return value;
}
```
There is also custom haxe implementation for json parser, available with `-D haxeJSON` flag, where skipping of null fields can be implemented in [JsonPrinter](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/format/JsonPrinter.hx).
