### ISSUE TITLE
Haxeflixel games....

### ISSUE THREAD

**Issue by G4merzauce** [HaxeFoundation/haxe#10538]
games such as friday night funkin and ritz won't run on my pc. i've tried reinstalling the games, disabling my antivirus, and restarting my computer. i also tried freeing up some space (especially since i have over 400 mods on my pc). im trying to get either some extra tips for a fix on this or one of the haxe members to contact me regarding the issue.

**Comment by Simn** [comment]
Please head on over to https://community.haxe.org/ for questions like this.
