### ISSUE TITLE
Haxelib Certificate Error

### ISSUE THREAD

**Issue by purplelunamine** [HaxeFoundation/haxe#10530]
Today, while trying to install several different libraries, I got a strange error, which I have never encountered before. It says that there was a problem with certificates. 
![image](https://user-images.githubusercontent.com/77215030/146488408-59a620c3-2f14-47b1-b51c-5f1854b1c14b.png)
Why is this happening? I'm using the latest version of Haxe.

**Comment by Simn** [comment]
This is likely some temporary issue with SSL certificates, which sometimes occurs in other contexts as well. I assume that this has resolved itself, if not, please comment!

**Comment by Zoardedz** [comment]
it actually hasn't, any suggestions on what to do?
![Screenshot_363](https://user-images.githubusercontent.com/92955177/152039271-e62ef65f-4d56-4955-a961-d6a953c29cc9.png)

**Comment by c-g-dev** [comment]
Just fixed this issue on a fresh Windows install. Check this: https://github.com/HaxeFoundation/neko/issues/196

Running any curl command on haxelib installs the correct certificates:

`curl -sSLf https://lib.haxe.org/p/haxelib/4.0.3/download -o haxelib.zip`

Appears to be some kind of neko problem? Anyway it worked fine for me after running the above
