### ISSUE TITLE
`@:publicFields` does not work on abstracts

### ISSUE THREAD

**Issue by ALANVF** [HaxeFoundation/haxe#10541]
```haxe
@:publicFields
abstract Foo(Int) from Int {
    static function make(f: Float): Foo { return Std.int(f); }
}
trace(Foo.make(1.2));
```

Expected behavior:
```
1
```

Actual Behavior
```
...: Cannot access private field make
```

**Comment by Simn** [comment]
I'm not sure if I was aware of this metadata existing... From reading the code, it is actually "inherited" by child classes, which seems really strange to me.

But either way, I agree that this should work for abstracts as well.
