### ISSUE TITLE
Std.parseInt() does not parse negative hex numbers on neko/cpp target

### ISSUE THREAD

**Issue by zagortenej** [HaxeFoundation/haxe#10545]
[https://api.haxe.org/Std.html#parseInt](https://api.haxe.org/Std.html#parseInt) says:
"x may also start with a - to denote a negative value."

I'm not sure if this refers to decimal format *only* or it applies to hex too, so I'm not sure if this is a bug or just the documentation being a bit vague.

The reason why I have doubts is because this code:
```
trace(Std.parseInt("-0xa0"));
```
produces these results on following targets:
```
eval: -160
hashlink: -160
js: -160
java: -160
python: -160
neko: 0
cpp 0
```
I'm running unit tests on `eval` target, and from time to time on `neko`, and thought (based on the API docs) `-0xa0` is a valid value, but it looks like `neko` and `cpp` disagree. Maybe it's the case with some of the other targets (flash, c#, php, etc.) these are the only ones I tried.

**Comment by zagortenej** [comment]
Also:
```
Std.parseInt("+123");
```
results in:
```
eval: 123
hashlink: null
js: 123
java: 123
python: 123
neko: 123
cpp 123
```
but I think this might not be considered a bug because the documentation does not mention `+` character as a valid one.

**Comment by Simn** [comment]
Could you open a pull request that adds the failing cases (also from #10544) as a unit test? That way I can fix it directly on that branch. I'll probably also deal with the problems from #10480 while I'm there.
