### ISSUE TITLE
Dynamic getter is not inferred

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10568]
With Haxe 4.1, the getter return type was inferred according to the field it belongs to. This is no longer the case since Haxe 4.2, leading to some compilation or runtime errors, such as the following example shows:

```haxe
class Test {

	static var selected(get,never) : Dynamic;
		
	static function get_selected() {
		return (0:Dynamic);
	}


	public static function main():Void {
		$type(get_selected);
		trace(selected == "");
		$type(get_selected);
		trace(selected == 0);
	}
	
}
```

Haxe 4.1:

```
false
true
```

Haxe 4.2 (HL):
```
Test.hx:12: characters 9-21 : Warning : () -> Unknown<0>
Test.hx:14: characters 9-21 : Warning : () -> String
Test.hx:15: characters 9-17 : Don't know how to cast String to f64
```

**Comment by ncannasse** [comment]
Note: it's actually coming from a bugfix because 4.1 was not unifying at all.

**Comment by Simn** [comment]
This was closed by https://github.com/HaxeFoundation/haxe/commit/add042a117e65211bd0be03e46425ef8a71698c4
