### ISSUE TITLE
Creating folders with Umlauts in MacOSX does not work

### ISSUE THREAD

**Issue by andreasdr** [HaxeFoundation/haxe#10573]
Hi, 

creating a folder like "/Users/andreas/Documents/Tactics Manager/Drills/Doxa/Προθέρμανση vs Καστοριά" does fail without throwing an exception, also without creating the folder.

"/Users/andreas/Documents/Tactics Manager/Drills/Doxa/" exists.

I use a simple: FileSystem.createDirectory("/Users/andreas/Documents/Tactics Manager/Drills/Doxa/Προθέρμανση vs Καστοριά")

Many thanx.

I am looking for hearing from you soon.

**Comment by Simn** [comment]
What target?

**Comment by andreasdr** [comment]
MacOSX - Native

**Comment by andreasdr** [comment]
Testing right now "Windows"

**Comment by Simn** [comment]
I mean what Haxe target, like C++ or HL or what?

**Comment by andreasdr** [comment]
Oh I am using OpenFL on MacOSX natively, this compiles to C++.

**Comment by Simn** [comment]
See #8400, it doesn't mention `createDirectory` explicitly, but all these problems are likely going to have the same cause and solution.

**Comment by andreasdr** [comment]
Seems like Haxe/Windows does not have the problem!

![grafik](https://user-images.githubusercontent.com/9664312/151404800-efb0d6f6-1d0b-45a8-a84c-e547c5ce51f9.png)
