### ISSUE TITLE
regex not working in android

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/haxe#10579]
**Environment**
macos monterey 12.1
haxe 4.2.4

The constructor of the class `EReg` throws IllegalArgumentException in Android. The problem is that the class sets the flag [java.util.regex.Pattern.UNICODE_CHARACTER_CLASS](https://developer.android.com/reference/java/util/regex/Pattern#UNICODE_CHARACTER_CLASS), that is unsupported in Android. 
Is it possible to avoid the setting of the flag altogether when the target is java?

The error can be reproduced by a snippet like this when it is executed on an Android device

```haxe
package foo;
class Main {
  public static function main() {
    Sys.println(~/h/.match("hello"));
  }
}
```

The reported error is

```
java.lang.IllegalArgumentException: Unsupported flags: 256
        at java.util.regex.Pattern.<init>(Pattern.java:1394)
        at java.util.regex.Pattern.compile(Pattern.java:985)
        at haxe.root.EReg.__hx_ctor__EReg(Unknown Source:56)
        at haxe.root.EReg.<init>(Unknown Source:3)
```

**Comment by Simn** [comment]
See #7632, compile with `-D android`.
