### ISSUE TITLE
Using textalign as field name causes problems in JavaScript

### ISSUE THREAD

**Issue by Magnesus** [HaxeFoundation/haxe#10572]
There is a bit weird issue when using "textalign" in a class as a field name in JavaScript target:

public textalign:String = "center-top";

I had a line that checks if it starts with "center":

trace(textalign);
if(textalign.indexOf("center")==0)
{
// my code
}

It would build without issues and then crash at runtime (in Firefox browser, JS target of course) saying there is no indexOf function. The trace says textalign is assigned NaN (despite me not changing it in any part of the code).

My guess is the problem is that the name "textalign" is in conflict with DOM textAlign property (despite different letter size)? Seems dangerous to have such conflicts in haxe, the number of possible DOM properties is quite high and may change in time.

**Comment by Simn** [comment]
This is going to be some userland problem, but it's impossible to tell without a full example.
