### ISSUE TITLE
no output hxml addling lib force to add at least one cp even empty

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10578]
Hej !

I have a dummy lib called _mylib_
Inside this lib I have an _extraParams.hxml_ file with only this line inside : `-lib hscript`
I also have a dummy module _Foo.hx_ with that inside : 
```haxe
import hscript.Macro;
class Foo{
	public static function bar(){}
}
```
Then I have a dummy test project that only have a _build.hxml_ file with that inside : 
```haxe
-lib mylib
--macro Foo.bar()
```
This throws me `mylib/0,0,1/Foo.hx:1: characters 8-21 : Type not found : hscript.Macro` on CLI when doing `haxe build.hxml`
In order to avoid this error message you just have to create an empty directory (i.e. _foo_) inside your projet and add the `-cp foo` line inside the build file : 
```haxe
-lib mylib
-cp foo
--macro Foo.bar()
```
Just to tell that here is a minimal example but I often use a build file with `--next` param to perform some tasks in my project before the real compilation, and It always worked. Just today, I've added this _extraParams.hxml_ file, and have noticed that.

**Comment by tobil4sk** [comment]
To add a proper library dependency, instead of adding `-lib` to `extraParams.hxml`, dependencies should be added to the haxelib.json: https://lib.haxe.org/documentation/creating-a-haxelib-package. This is the intended way of adding library dependencies as it allows for automatic dependency downloads with haxelib, etc.

Also, this seems to be a duplicate of #4059?

**Comment by filt3rek** [comment]
Thx for your answer.
Yes you're right I haven't seen this issue yet it's duplicate of : https://github.com/HaxeFoundation/haxe/issues/4059
Coming to haxelib.json, I have reade, and I added the lib in "dependencies", but where should I add the param `-lib hscript` to force user when adding `-lib mylib`in his projet, it automatically adds `-lib hscript` please ?

**Comment by tobil4sk** [comment]
I understand that your question was answered over on the other thread? Do you mind closing this now in favour of the other one?

**Comment by filt3rek** [comment]
Hej @tobil4sk !

Yes, sorry, I'll close this one.

**Comment by tobil4sk** [comment]
Many thanks!
