### ISSUE TITLE
Can’t use OkHttp library

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/haxe#10589]
**Environment**
macos monterey 12.1
haxe 4.2.4
okhttp 4.9.3

[OkHttp](https://square.github.io/okhttp/) is a java library providing Http and Websocket connectivity on JavaSE and Android.
Haxe can’t generate output code when the option `--java` is used. 
The option `--jvm` works fine instead but I can’t use it because of  the issue #10571.

The error can be reproduced by the following code

```haxe
package foo;

class Main {
  public static function main() {
    var c: okhttp3.OkHttpClient;
  }
}
```

The reported error is

```
Module okhttp3.internal.connection.RealCall does not define type RealCall_timeout_1
foo/Main.hx:3: lines 3-13 : ... Defined in this class
```

**Comment by Simn** [comment]
The Java target will be put in "regression fixes only" state with the Haxe 4.3.0 release. See https://github.com/HaxeFoundation/haxe/wiki/Target-Support-Level#java-and-c-since-430 for additional information. We apologize for any inconvenience this causes!
