### ISSUE TITLE
Oversight in the Haxe parser ? Everything is an expression

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10588]
Hej,

I encountered this error : https://try.haxe.org/#9d035AEd
```haxe
class Test {
	static function main() {
		if( { 1; } != null ) trace( "ok" );	// <--- Doesn't work
		if( ({ 1; }) != null ) trace( "ok" );	// <--- Do work
	}
}
```

**Comment by Simn** [comment]
That's intentional, we don't parse "next" expressions after blocks. Doing so would parse something like this as a call:

```
{
    block;
}
(expr)
```

And there's probably other cases where silly things would happen.

**Comment by filt3rek** [comment]
Thx for the reply @Simn 
Ok, I didn't knew that, I thought ECall was different from EParenthesis...
For my needs, I do iterations in my whole expr and add EParenthesis everywhere... :/

**Comment by filt3rek** [comment]
@Simn 
Sorry to come back, I just want to understand : It happens not only on parser but I get it in my macro if you take a look please here , Line 42 in Macro Class, I surround all my expr with EParenthesis if not, in Eif it fails : https://try.haxe.org/#326943EB
😬

**Comment by Simn** [comment]
I don't understand what you mean, and line 42 is a comment...

**Comment by filt3rek** [comment]
Sorry, Line 76.
I mean that when I iter in expressions, (because I build an `if( ...)` statement every time), so I have to surround the expression in if with EParenthesis, if not , when I return this whole if, compiler complains...
So If I understand well, it's not about Parser but later, and Ecall and EParenthesis are different so It can't be confused with a call...

**Comment by Simn** [comment]
What does it complain about?

**Comment by filt3rek** [comment]
Hmm sorry, I just removed the line that surrounds the expr by a EParenthesis, so It came fro manother thing I guess.
BTW having this issue, I tried just to write `if( { 1; } != null ) trace( "ok" );` and it didn't work so I thought it was the same issue...
Nevermind, sorry for the disturbing and many thanks for your attention and your work

**Comment by filt3rek** [comment]
...and the Line 42 is about the "`" var name, in macro context, If I understand well, local var names are backtick, so I have to renames them :rofl: so my all thing works.

Is that kind of error I encouter due to the fact that I’m getting back a @:this this typed expression into an untyped one and I should try to write this kind of macros in the “typed context” with “typed” things ?
Because that’s true that I’m often writting macros in the untyped macro context…

Thanks for your advices and really I stop disturbing you now
