### ISSUE TITLE
[nightly] cast on function return value reported as recursive

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10604]
Not sure if this involves an intentional change but I'll report it anyway...

The following used to work at 4.2.3 and before but failed in nightly (8410d24)

```haxe
package ;

class Main {
	static function main() {}
}

abstract Promise<T>(Dynamic) {
	@:from static inline function ofData<T>(d:T):Promise<T>
		throw 0;
}

@:callable
abstract Next<In, Out>(In->Promise<Out>) from In->Promise<Out> to In->Promise<Out> {
  @:from static function ofSafeSync<In, Out>(f:In->Out):Next<In, Out>
	return x -> f(x); // error: Recursive implicit cast
}
```

**Comment by kevinresol** [comment]
Thanks for the update! But while the original snippet works now, the following doesn't:  (0c9d011)

```haxe
package ;

class Main {
	static function main() {}
}

typedef Error = Dynamic;

enum Outcome<Data, Failure> {
  Success(data:Data);
  Failure(failure:Failure);
}

@:transitive
abstract Promise<T>(Dynamic) {

  @:from static inline function ofOutcome<T>(o:Outcome<T, Error>):Promise<T>
    throw 0;

  @:from static inline function ofError<T>(e:Error):Promise<T>
    throw 0;

  @:from static inline function ofData<T>(d:T):Promise<T>
    throw 0;
}

@:callable
abstract Next<In, Out>(In->Promise<Out>) from In->Promise<Out> to In->Promise<Out> {

  @:from static function ofSafe<In, Out, Err:Error>(f:In->Outcome<Out, Err>):Next<In, Out>
    return x -> f(x);

  @:from static function ofSafeSync<In, Out>(f:In->Out):Next<In, Out>
    return x -> f(x);

}

@:callable
abstract Combiner<In1, In2, Out>(In1->In2->Promise<Out>) from In1->In2->Promise<Out> {

  @:from static function ofSync<In1, In2, Out>(f:In1->In2->Outcome<Out, Error>):Combiner<In1, In2, Out>
    return (x1, x2) -> f(x1, x2);

  @:from static function ofSafeSync<In1, In2, Out>(f:In1->In2->Out):Combiner<In1, In2, Out>
    return (x1, x2) -> f(x1, x2);

}
```

**Comment by kLabz** [comment]
Not sure what the official position on this is, but there is an easy workaround:

```haxe
@:callable
abstract Next<In, Out>(In->Promise<Out>) from In->Promise<Out> to In->Promise<Out> {
  inline function new<In, Out>(f:In->Promise<Out>) this = f;

  @:from static function ofSafe<In, Out, Err:Error>(f:In->Outcome<Out, Err>):Next<In, Out>
    return new Next(x -> f(x));

  @:from static function ofSafeSync<In, Out>(f:In->Out):Next<In, Out>
    return new Next(x -> f(x));
}

@:callable
abstract Combiner<In1, In2, Out>(In1->In2->Promise<Out>) from In1->In2->Promise<Out> {
  inline function new<In1, In2, Out>(f:In1->In2->Promise<Out>) this = f;

  @:from static function ofSync<In1, In2, Out>(f:In1->In2->Outcome<Out, Error>):Combiner<In1, In2, Out>
    return new Combiner((x1, x2) -> f(x1, x2));

  @:from static function ofSafeSync<In1, In2, Out>(f:In1->In2->Out):Combiner<In1, In2, Out>
    return new Combiner((x1, x2) -> f(x1, x2));
}
```

**Comment by kevinresol** [comment]
yeah, or `return x -> Promise.lift(f(x));` and a few other possible ways...

With 2+ `@:from` casts, I think when the compiler now hits a mutual recursion: `Next.ofSafe -> Next.ofSafeSync -> Next.ofSafe -> Next.ofSafeSync ...`

Would like to understand more how these casts are supposed to work nowadays...

**Comment by onehundredfeet** [comment]
I'm getting a series of warnings just by importing tink.core.Promise;

Promise.hx:319: characters 5-21 : Recursive implicit cast
Promise.hx:316: characters 5-21 : Recursive implicit cast
Promise.hx:313: characters 5-21 : Recursive implicit cast
Promise.hx:344: characters 5-33 : Recursive implicit cast
Promise.hx:341: characters 5-33 : Recursive implicit cast
Promise.hx:338: characters 5-33 : Recursive implicit cast

I'm using the latest development Haxe.


Is this a bug or a design choice?

**Comment by Simn** [comment]
IMO there's definitely some dodgy stuff going on, but I'd still prefer not to break something like this in a dot release.

**Comment by onehundredfeet** [comment]
It seems to me that tink.core is fairly widely used.  Is that the case?

**Comment by Simn** [comment]
Can somebody tell what which cast `ofSafe` is _supposed_ to pick up, and why? If we just look at `x -> f(x)`, its type would be `(x : In) -> Outcome<Out>`, which is exactly the argument type of `ofSafe` itself.

**Comment by onehundredfeet** [comment]
@kevinresol would be better able to answer that question.

**Comment by kevinresol** [comment]
In my example, the `x -> f(x)` inside Next.ofSafe should become `x -> Promise.ofOutcome(f(x))` because `Next` itself is a Promise-returning function.

I guess we can fix this by being more explicit e.g. `x -> (f(x):Promise<Out>)`, but I wish to understand the behaviour/specification first.

**Comment by onehundredfeet** [comment]
```
 @:from static function ofSafe<In, Out>(f:In->Outcome<Out, Error>):Next<In, Out>
    return x -> @:privateAccess Promise.ofOutcome(f(x));
```

That fixed it.  What are the other ones?

**Comment by onehundredfeet** [comment]
btw - The problem was introduced in the following change:

https://github.com/HaxeFoundation/haxe/commit/e134a970ff1c8fa0f106e983e9a83aa7a34d2cf1

**Comment by kevinresol** [comment]
> What are the other ones?

basically all of them should become `x -> (f(x):Promise<Out>)`

**Comment by Simn** [comment]
> In my example, the x -> f(x) inside Next.ofSafe should become x -> Promise.ofOutcome(f(x)) because Next itself is a Promise-returning function.

This would require using top-down inference when typing `x -> f(x)` so that its return type ends up being `Promise<Out>`. The compiler refuses to do so because there are two casts which are potentially applicable:

1. `from In -> Promise<Out>`
2. `ofSafeSync<In, Out>(f:In->Out)`

Technically, there's even a third one because `ofSafe` itself is also applicable, but that's what I've filtered in my original fix for this issue.

Due to the ambiguity, the function is (now) typed as-is, and then fails to unify with the return type because the only cast that would actually work at this point is `ofSafe` itself.

> btw - The problem was introduced in the following change:
 https://github.com/HaxeFoundation/haxe/commit/e134a970ff1c8fa0f106e983e9a83aa7a34d2cf1

Yes, but that's a good change because always inferring through the underlying type of an abstract breaks the abstraction.

**Comment by Simn** [comment]
This has been addressed in tink_core. I've discussed matters with @back2dos and for now we agreed that the current state is okay.  I made one more fix in https://github.com/HaxeFoundation/haxe/commit/9010c3833752f953aa35d15b4848698850f8296e to deal with a situation where we top-down inferred against type-parameters.

If anything else comes up, let me know!
