### ISSUE TITLE
Compiler reports "Expected }" error without context

### ISSUE THREAD

**Issue by te-agma-at** [HaxeFoundation/haxe#10601]
The issue: Compiler reports "Expected }" error without any warning nor additional context.
Which line it errored and/or specific characters index: line 18 | characters 74-75
How to reproduce: Put a "public var (name):(type)" before anything + then put a "override public function <name>() {" after it + problem reproduced
Haxe Version: v4.1.5

I bet this is more an issue with the compiler than anything else, as this issue is strange nonetheless.
This also happens when:
- Putting a function with proper bracket syntax after the function
- Making a var "static" too along with "public" and declaring it before the function
- Not sure if this has been tested yet, but also making a var "inline" too before the function

I am very confused as to how to fix this, this error is odd.

How to fix:
- Maybe a more "fluid-style" bracket compiling (see image below)
![Screenshot 2022-02-22 220123](https://user-images.githubusercontent.com/72958435/155255097-e97caa4e-4086-4656-a674-99e7a955f1c2.png)
- Patch issues concerning a following "unexpected" deletion-requirement chain* when trying to handle the error

*Not if a variable wasn't used anywhere, causing a "unexpected" deletion-requirement chain for a good reason

**Comment by te-agma-at** [comment]
Pretty sure this is why people who code with Haxe need to be more careful with indentation (if they haven't yet)

**Comment by kaikoga** [comment]
As a general manner, please [paste the minimal example code](https://github.com/HaxeFoundation/haxe/blob/development/CONTRIBUTING.md#things-to-check-beforewhile-filing-an-issue) here or try.haxe.org that should reproduce the compiler error, which should help the Haxe development team to investigate your problem.

Thanks!

**Comment by RealyUniqueName** [comment]
Compiler expects `}` there because keyword `public` can't be used inside of a function body. So it asks you to close the body first.
