### ISSUE TITLE
[jvm] object literal keys with dots result in runtime error

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#10600]
```haxe
function main() {
	var x = {
		"checkstyle.checks.Checker": ["CheckBase", "UnusedImportCheck"]
	};
	trace('$x');
}
```
compiled to JVM shows a runtime error: 
```
$ haxe -D jvm -java out -main Test 
$ java -jar out/Test.jar

Error: LinkageError occurred while loading main class _Test.Test_Fields_
	java.lang.ClassFormatError: Illegal field name "_hx_tmp_checkstyle.checks.Checker" in class _Test/Test_Fields_
```

works for 4.2.4 and below

**Comment by Simn** [comment]
Thanks for catching that and the minimal example!

There was a check for this which I removed in https://github.com/HaxeFoundation/haxe/commit/314975706f238f0cfdf5fb0a61389ec9bf5ec7a8 because it didn't break any tests. Turns out we were just missing the deciding test.
