### ISSUE TITLE
[jvm] Don't generate signature for primitive fields

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10608]
I tried to run [jandex](https://github.com/wildfly/jandex) over the jar generated by haxe and getting:

```
java.lang.NullPointerException
        at org.jboss.jandex.FieldInternal.hashCode(FieldInternal.java:99)
        at org.jboss.jandex.StrongInternPool.hash(StrongInternPool.java:152)
        at org.jboss.jandex.StrongInternPool.intern(StrongInternPool.java:237)
        at org.jboss.jandex.NameTable.intern(NameTable.java:117)
        at org.jboss.jandex.ClassInfo.setFields(ClassInfo.java:745)
        at org.jboss.jandex.Indexer.index(Indexer.java:1993)
        at org.jboss.jandex.JarIndexer.createJarIndex(JarIndexer.java:173)
        at org.jboss.jandex.JarIndexer.createJarIndex(JarIndexer.java:106)
        at org.jboss.jandex.JarIndexer.createJarIndex(JarIndexer.java:68)
        at haxe.root.Main.main(src/Main.hx:14)
        at haxe.root.Main.main(src/Main.hx:1)
```

After some `println` debugging and comparing javac-created jars, I guess the reason is because haxe is generating "signature" on all fields. I think the following should be done instead:
- generate only descriptor for fields not involving type parameters
- generate descriptor & signature for fields involving type parameters

Spec: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3

haxe generated this bytecode:
![Screenshot 2022-03-01 at 00 00 23](https://user-images.githubusercontent.com/1103788/156015682-a2b1ee4b-cf13-4b2a-91c8-962efb9e5114.png)

javac generated this bytecode:
![Screenshot 2022-03-01 at 00 00 01](https://user-images.githubusercontent.com/1103788/156015672-948f55c9-5427-425b-b919-85a4d5da8083.png)

repro: https://github.com/kevinresol/haxe_issues/tree/issue_10608

**Comment by Simn** [comment]
IMO this is a jandex bug, the JVM specification does not disallow generating non-generic signatures. It even says this:

> A field type signature, defined by the production FieldTypeSignature, encodes the (possibly parameterized) type for a field, parameter or local variable.

Note the "possibly".

I'm still not necessarily opposed to omitting signatures, but I think jandex should fix this regardless.

**Comment by kevinresol** [comment]
Alright, then now I think the problem is that FieldTypeSignature does not support primitives and jandex correctly handle only the 3 possible values:

```
FieldTypeSignature:
    ClassTypeSignature
    ArrayTypeSignature
    TypeVariableSignature
```


https://github.com/wildfly/jandex/blob/c4680211b556c707c664db02477f5928d0cbd3aa/src/main/java/org/jboss/jandex/GenericSignatureParser.java#L441-L451

(changing issue title accordingly)

**Comment by Simn** [comment]
Oh, that I already addressed in https://github.com/HaxeFoundation/haxe/commit/dbff5aa7eb8ec6ec953df37ac2ad145d39a64d09

**Comment by kevinresol** [comment]
Indeed working with nightly, thanks!
