### ISSUE TITLE
Howto: wrap a haxe.ds.Map?

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/haxe#10613]
Hi,

It seems impossible to wrap a haxe.ds.Map<K, V>.  this will not work:

```haxe
package test;

class MapWrap<K, V> {
    private var _map: haxe.ds.Map<K, V>;
    
    public function new() {
        _map = new haxe.ds.Map<K, V>(); // error
    }

}
```

result:

```
Abstract haxe.ds.Map has no @:to function that accepts haxe.IMap<test.MapWrap.K, test.MapWrap.V>
```

Basically  all I want is to wrap the `haxe.Constraints.IMap` interface In my own classes! Just like wrapping arrays for own usage.

Does anyone have any suggestions on how to do this?

Many Thanks.

**Comment by Simn** [comment]
The short answer is that you can't. Maps need to know their concrete key type in order to select an implementation. We do need support the notion of "any" key type because this would be huge hidden performance trap.

**Comment by ghost** [comment]
> The short answer is that you can't. Maps need to know their concrete key type in order to select an implementation.

Be that as it may, but it seems like a fundamental design-flaw. Users of a statically typed high object oriented languages usually need functionality to wrap fundamental data-storage classes like `Array<T>` and `Map<K, V>` for their own needs. So having a class like `Map<K, V>` without the possibility for users to "actually use them in their own classes"  and just making direct instances possible doesn't seem very thoughtful and only addresses some minor use-cases!

**So I would urge you to reevaluate what you are doing with this!**

> We do need support the notion of "any" key type because this would be huge hidden performance trap.

Better "low" performance than "no" performance!

For now as a little work around, I will just use the explicit classes (IntMap, StringMap, etc) directly, and - where needed - make multiple "flavors" of my classes to kinda Solve this. Here is an example:


```haxe
/**
 *   Example of how to wrap the haxe map, you can apply this 'idea' on all of your own classes!
 **/

/// implement the interface and have a refernece to a actual haxe Map. Keep it abstract so that it cannot be instantiated.
/// if it is not used by it self, than make it abstract (abstract MapCore<K, V>)
class MapCore<K, V> {

    /// private map
    private var _map: haxe.Constraints.IMap<K, V>;

    /// constructor can be called directly or by constructors of derived classes.
    public inline function new(map: haxe.Constraints.IMap<K, V>) {
        this._map = map;
    }

    public function get(key: K): Null<V> {
        return _map.get(key);
    }

    public function set(key: K, value: V): V {
        _map.set(key, value);
        return value;
    }
}

function doStuff() {
    // you can make variables or do call use super: super(new haxe.ds.IntMap<Int>());
    // in derived classes
    var mapa = new MapCore<Int, Int>(new haxe.ds.IntMap<Int>());
    var mapb = new MapCore<#MYENUM, Int>(new haxe.ds.EnumValueMap<#MYENUM, Int>());
    var mapc = new MapCore<String, Int>(new haxe.ds.StringMap<Int>());
    var mapd = new MapCore<#MYTYPE, Int>(new haxe.ds.ObjectMap<#MYTYPE, Int>());
}
```
