### ISSUE TITLE
Regex unicode sequences break completion

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10616]
```haxe
class Main {
	static function main() {
		trace("Hello, world!");
	}
	// no completion
	pu|
	// comment this to fix completion
	final ctrlCharacters = ~/[\u0000-\u001F\u007F-\u009F\u2000-\u200D\uFEFF]/g;
	// ~/\u0000/ is also enough to break
}
```

**Comment by Simn** [comment]
Can you confirm that `\u` actually works properly in regex literals in the first place?

**Comment by RblSb** [comment]
`trace(~/[\u0042-\u0044]/g.replace("ABCDE", "_"));` works mostly on js and some non-PCRE targets, like java/jvm. Not sure if it will be useful to parse or not.
PCRE-based targets does not support this, but there is support for `\x{0042}`:
`trace(~/[\x{0042}-\x{0044}]/g.replace("ABCDE", "_"));` (parses fine)

Another question: does somebody want to get \x-ranges support in js too? I this this can be done with `\\x{([0-z]+)} -> \\u$1` js-regex replace in EReg constructor (would be cool to skip that replace with constant ereg sugar someway).

**Comment by Simn** [comment]
I looked into this but had a hard time even trying to figure out where this goes wrong. At first I thought this was some kind of offset issue, but that doesn't seem to be the case because it's failing even if the cursor is before the `\u`, like in your example. I couldn't find any other code where `\u` is even relevant.

**Comment by RblSb** [comment]
Anyway, there is (maybe crossplatform) workaround:
```haxe
codepointRegex("[\\x{0042}-\\x{0044}]", "g").replace("ABCDE", "_");
...
static function codepointRegex(r:String, opt:String):EReg {
	#if js
	r = ~/\\x{([0-z]+)}/g.replace(r, "\\u$1");
	#end
	return new EReg(r, opt);
}
```
\u thing probably is not that important, some people like me can get this problem only from copy-pasting js code, i hope they will find this issue.
