### ISSUE TITLE
[php] Std.parseInt allows exponent notation

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10617]
While looking to fix some parseInt issues (PR soon), I noticed that `Std.parseInt` on php allows for the exponent notation.
```haxe
Std.parseInt("10e2"); // returns 1000
```
This does not match the other targets, which treat the `e2` as trailing text.

It may be best to document this as unspecified behaviour to avoid making the parseInt implementation too complex?

**Comment by Simn** [comment]
This should be fixed because the documentation states that the number is parsed as decimal and stops upon encountering an invalid character.
