### ISSUE TITLE
[js] Safe navigation runtime error 

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10622]
```haxe
class Main {
	static function main() {
		trace(hi()?.charAt(0));
	}
	static function hi() return "hi";
}
```
```hxml
--js bin/main.js
--cmd node bin/main
or also jvm:
--jvm bin/main.jar
--cmd java -jar bin/main.jar
```

**Comment by Simn** [comment]
This isn't exactly about the safe navigation operator because the manually expanded version fails the same way:

```haxe
class Main {
	static function main() {
		var tmp = hi();
		trace((tmp != null ? tmp.charAt : null)(0));
	}

	static function hi()
		return "hi";
}
```

```
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
                                                                                                                                                                ^

TypeError: Cannot create property 'hx__closures__' on string 'hi'
```

**Comment by RblSb** [comment]
True, but current safe navigation generation seems incorrect, 
`trace((tmp != null ? tmp.charAt : null)(0))` should be
`trace((tmp != null ? tmp.charAt(0) : null))`

Since calling `null(0)` is not safe, you should get null as result, other languages does not requests `charAt?.(0)`.
Tested on Dart and Kotlin, Kotlin generation for `println(hi()?.get(0))` is:
`println(toBoxedChar((tmp$ = hi()) != null ? tmp$.charCodeAt(0) : null));`

and Kotlin's for `println(hi()?.toLowerCase()?.get(0))`:
```js
println(
  toBoxedChar(
    (tmp$_0 = (tmp$ = hi()) != null ? tmp$.toLowerCase() : null)
    != null ? tmp$_0.charCodeAt(0) : null
  )
);
```
For reference, `println(hi()?.toLowerCase().get(0))` does not compile (still need `?.get(0)`, since Kotlin is null-safe by default).
But `println(hi()?.toLowerCase()!!.get(0))` (alternative of `@:nullSafety(Off)`) will actually generate sort of null call:
```js
println(
  toBoxedChar(
    ensureNotNull(
      (tmp$ = hi()) != null ? tmp$.toLowerCase() : null
    ).charCodeAt(0)
  )
)
```
So in Haxe, `hi()?.toLowerCase().charAt(0)` still should generate null-call, if we copy Kotlin (feels little stupid without safety filter turning on), but `hi()?.charAt(0)` does not.

But, i also checked Dart, and maybe this implementation is better:
`print(hi()?.toLowerCase()?.codeUnitAt(0));` will actually show warning on second `?.`, because first part cannot be null (even if `hi()` returns null).
So this generation in Haxe means `(tmp != null ? tmp.toLowerCase().charAt(0) : null)`
Need to mention, that Dart is in simular null-safety migration, and null-safety operators and checks are behind compiler flag. We only hide checks behind flag, so things is more complex.

Kotlin example: https://pl.kotl.in/Y_KCPSNT1
Dart example (https://dartpad.dev/?null_safety=true):
```dart
void main() {
  print(hi()?.toLowerCase().codeUnitAt(0));
}
String? hi() {
  return null;
}
```

**Comment by Simn** [comment]
> trace((tmp != null ? tmp.charAt : null)(0)) should be
> trace((tmp != null ? tmp.charAt(0) : null))

This makes me think that we should hold back on `?.` because the design is unclear. I was under the impression that it's a direct replacement for `.`. If there are other considerations here, I was not aware of them.

**Comment by RblSb** [comment]
Also [TypeScript Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWwIYzACgJSIN4BQixiECAznADYCmAdFXAOaYAWMOA-HVHADJwA7jQBOAYVTkaOOhFaoRAQSiYADNmwEAvgQKhIsBInY4AXOSgiMTRAB9EYEFSr4iJETSggRSR84Dc2kA) uses dart way for
`foo?.bar.baz` (same as `if (foo != null) foo.bar.baz; else null`),
but also okay to check
`foo?.bar?.baz` (`if (foo != null && foo.bar != null) foo.bar.baz; else null`).

There is good documentation how it works: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

> `let x = foo?.bar.baz();`
> this is a way of saying that when foo is defined, foo.bar.baz() will be computed; but when foo is null or undefined, stop what we’re doing and just return undefined.

**Comment by back2dos** [comment]
> This makes me think that we should hold back on `?.` because the design is unclear. I was under the impression that it's a direct replacement for `.`. If there are other considerations here, I was not aware of them.

Depends on what you mean by `.`, because that can also translate to `FClosure` which is basically the issue here. 

Here's a correct transformation right on the untyped AST: https://try.haxe.org/#f2972Df3

I think it should be quite possible to do this somewhere around `type_call` or something?
