### ISSUE TITLE
[macro] some kind of exception in `Context.typeExpr` cannot be caught with a try-catch statement

### ISSUE THREAD

**Issue by saharan** [HaxeFoundation/haxe#10626]
I was trying to make something using macro context and noticed that some sort of exception raised in `Context.typeExpr` cannot be caught by `try ... catch`, resulting in immediate termination of the compilation.

```hx
import haxe.macro.Context;

class Test {
	static macro function foo() {
		try {
			Context.typeExpr(macro var x:Void);
		} catch (e) {
			trace("an exception caught");
		}
		return macro trace("foo()");
	}

	static function main() {
		foo();
	}
}
```

This code tries to make a variable of type `Void`, which is not allowed and thus expected to raise some exception. The function `Context.typeExpr` does throw an exception apparently, but it's not catchable and there's no way to hold back the exception, which contradicts to the description of the function saying `Typing the expression may result in a compiler error which can be caught using try ... catch.`

I got an error `Variables of type Void are not allowed`.

Other kinds of exceptions can be caught. For example, the following code just works as expected.

```hx
import haxe.macro.Context;

class Test {
	static macro function foo() {
		try {
			Context.typeExpr(macro var x:UnknownType);
		} catch (e) {
			trace("an exception caught");
		}
		return macro trace("foo()");
	}

	static function main() {
		foo();
	}
}
```

Compilation message: `Test.hx:8: an exception caught`
Standard output: `Test.hx:10: foo()`

**Comment by Simn** [comment]
We have to update the documentation here to make it clear that not all compiler errors can be caught that way. It's just not possible in the general case, because with type inference and various delays, errors might be delayed as well.

However, this particular case could be fixed regardless, because we don't know to delay anything if we already know the type this early.
