### ISSUE TITLE
[jvm] Incorrect EReg constructor hint

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10621]
```haxe
class Main {
	static function main() {
		new EReg|;
	}
}

--jvm bin/main.jar
```
Press `(` and you will see internal `(compiledPattern:jvm.CompiledPattern) -> Void` argument hint from private overload first. `new EReg(|)` + `ctrl-space` will also suggest wrong anon structure generation for real (public) constructor.

**Comment by Simn** [comment]
This is a general problem with visibility in overloads:

```haxe
class NotMain {
	overload public function new(s:String) {}
	overload function new(i:Int) {}
}

class Main {
	static function main() {
		new NotMain;
	}
}
```
