### ISSUE TITLE
Lime is not install to haxe 4.2.5

### ISSUE THREAD

**Issue by DendyGG** [HaxeFoundation/haxe#10625]
i write in command prompt haxelib install lime
And 
Downloading lime-7,9,0.zip...
Download complete: 0KB in 0.6s (0KB/s)
Download complete: 0.13KB in 0.6s (0.2KB/s)
Download complete: 0KB in 2s (0KB/s)
Failed to download https://lib.haxe.org:443/files/3.0/lime-7,9,0.zip. (1/3)
Failed to connect on codeload.github.com:443
Download complete: 0KB in 0.6s (0KB/s)
Download complete: 0.13KB in 0.5s (0.2KB/s)
Download complete: 0KB in 2s (0KB/s)
Failed to download https://lib.haxe.org:443/files/3.0/lime-7,9,0.zip. (2/3)
Failed to connect on codeload.github.com:443
Download complete: 0KB in 0.7s (0KB/s)
Download complete: 0.13KB in 0.5s (0.2KB/s)
Download complete: 0KB in 2s (0KB/s)
Failed to download https://lib.haxe.org:443/files/3.0/lime-7,9,0.zip. (3/3)
Failed to connect on codeload.github.com:443
Error: [file_open,C:/HaxeToolkit/haxe/std/lime-7,9,0.zip]

**Comment by rafaelcdepaula** [comment]
The same thing is happening here.

**Comment by Aurel300** [comment]
This looks like it might be a Windows/git issue. Does anything mentioned [in the answers here](https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github) help?

**Comment by DendyGG** [comment]
> The same thing is happening here.

**Comment by DendyGG** [comment]
> This looks like it might be a Windows/git issue. Does anything mentioned [in the answers here](https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github) help?

![изображение_2022-03-26_130500](https://user-images.githubusercontent.com/90975531/160227095-c9b14bac-0abd-404a-b233-064bad21b5df.png)
i reinstall git and its not fix

**Comment by Aurel300** [comment]
@DendyGG Please actually read the answers I linked. (Reinstalling `git` was not suggested.)

**Comment by hafimiee** [comment]
by the way fix your grammar

**Comment by ghost** [comment]
Then try to use Haxe 4.2.4 first.

**Comment by Simn** [comment]
It't unlikely that this is an issue we have control over, so I'll go ahead and close it.
