### ISSUE TITLE
@:build seems to support Abstracts

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#10639]
``@:build`` seems to work on Abstracts however the documentation does not indicate abstracts are supported. Am I missing something here?

"Builds a class or enum from a macro"

https://try.haxe.org/#93fc54c9

another example with operator overload functions:

https://try.haxe.org/#1C39c07c

**Comment by Simn** [comment]
I'm not sure why you're reporting that something works... but yes, it works!

**Comment by Aurel300** [comment]
I think the issue was for us to update the [documentation here](https://github.com/HaxeFoundation/haxe/blob/development/src-json/meta.json#L115).

**Comment by Simn** [comment]
Ah, that documentation. I checked the manual and it talks about type building in general. But yes, the CLI part could be updated.

**Comment by PXshadow** [comment]
Thanks I didn't know where the cli info was located before, good to know :)
