### ISSUE TITLE
Class path exploration vs. nested -cp

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#10636]
I don't have a reproducible example, but basically having something like `-cp src -sp src/const` causes problems for class path exploration because packages don't match.

I've always thought that this is a bad pattern, but it's allowed, so we'll have to deal with it somehow.

**Comment by kLabz** [comment]
> I've always thought that this is a bad pattern, but it's allowed, so we'll have to deal with it somehow.

Yeah when I saw it on an issue (?) recently I was expecting it to fail. And still do, actually.

What is the expected package of `src/const/Foo.hx` with `-cp src -cp src/const` then? `package;` or `package const;`?

**Comment by Simn** [comment]
The former, because the most recent `-cp` wins.
