### ISSUE TITLE
sys.io.Process() stalling on cpp with content of more that 65535 bytes

### ISSUE THREAD

**Issue by grepsuzette** [HaxeFoundation/haxe#10645]
Target `cpp` on Linux. 
* Create 2 files, `2bytes.txt` and `100000bytes.txt`.
* Then try to read them on `stdout`.

```haxe
var p = new sys.io.Process("cat", ["2bytes.txt"]);
var code = p.exitCode(true);
trace("exit code: " + code);
trace(p.stdout.readAll().length);
p.close();
// ^-- above shows the size

var p = new sys.io.Process("cat", ["100000bytes.txt"]);
var code = p.exitCode(true);
trace("exit code: " + code);
trace(p.stdout.readAll().length);
p.close();
// ^-- this one stalls (never get the exitCode)
```
The second one stalls.

Of course it not only does this for `cat` but basically anything else, 
e.g. [curl here](https://github.com/haxetink/tink_http/issues/136).

**There is a way to "fix" this however:**

```haxe
var p = new sys.io.Process("cat", ["100000bytes.txt"]);

trace(p.stdout.readAll().length); // swapped those 2 lines
var code = p.exitCode(true);

trace("exit code: " + code);
p.close();
```
In that case, it isn't stalled anymore. 
So is it a bug?

**Comment by Simn** [comment]
Processes tend to block if some pipe is full. I don't think our abstraction level is supposed to guard against such a thing.

And yes I find this very annoying as well on a practical level.

**Comment by grepsuzette** [comment]
Yes I see what you mean.

**Comment by grepsuzette** [comment]
Just as a note,

> I don't think our abstraction level is supposed to guard against such a thing.

I wonder if there isn't a major downside to the current policy. 
Namely the fact there would be no way to retrieve stderr after a Process fails in C++.

I am not sure, but better say it in case this issue resurfaces in another discussion.

**Comment by Simn** [comment]
Typically you would read stdout in one thread and stderr in another. That's not so much our policy, it's just how unix pipes are designed.
