### ISSUE TITLE
Calling `Json.parse()` on a huge string causes heap corruption on Windows

### ISSUE THREAD

**Issue by space-nuko** [HaxeFoundation/haxe#10644]
As the title says, although the html5 target works fine. With ASAN enabled the program crashes reliably on two different setups of mine:

```xml
     <compiler id="MSVC" if="windows">
        <flag value = "/fsanitize=address"/>
     </compiler>
```

Minimal repro (`huge.json` is 20MB):

```hx
package;

import haxe.Json;

class Main {
	public static function main() {
		new Main();
	}

	public function new() {
            var s = sys.io.File.getContent("C:/path/to/huge.json");
            Json.parse(s);
	}
}
```

Also passing it a small JSON file causes no problems.

<details><summary>Traceback</summary>
<pre>
./bin/Main-debug.exe
=================================================================
==41184==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x00a1d3d0 at pc 0x00b6fc35 bp 0x00a1ce7c sp 0x00a1ce70
READ of size 4 at 0x00a1d3d0 thread T0
    #0 0xb6fc34 in hx::MarkConservative(int *, int *, class hx::MarkContext *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:5554
    #1 0xb929c0 in LocalAllocator::Mark(class hx::MarkContext *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6219
    #2 0xb71f5e in MarkLocalAlloc C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6297
    #3 0xb92f9b in GlobalAllocator::MarkAll(bool) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:4677
    #4 0xb8fc7d in GlobalAllocator::Collect(bool, bool, bool, bool) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:4847
    #5 0xb91928 in GlobalAllocator::GetFreeBlock(int, class hx::ImmixAllocator *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:3530
    #6 0xb8f473 in LocalAllocator::CallAlloc(int, unsigned int) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6156
    #7 0xb6ec17 in hx::InternalNew(int, bool) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:6487
    #8 0xa79fee in hx::ArrayBase::Realloc(int) const C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\Array.cpp:117
    #9 0xa4caf6 in hx::ArrayBase::EnsureSize(int) const C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\Array.h:358
    #10 0xadab7d in Array_obj<double>::push(double) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\Array.h:654
    #11 0xacdb1c in Array_obj<double>::__push(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\Array.h:913
    #12 0xa5ff99 in cpp::VirtualArray_obj::push<class Dynamic>(class Dynamic const &) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\cpp\VirtualArray.h:391
    #13 0xa5102f in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:252
    #14 0xa51c95 in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:372
    #15 0xa5101c in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:252
    #16 0xa51c95 in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:372
    #17 0xa5101c in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:252
    #18 0xa51c95 in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:372
    #19 0xa5101c in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:252
    #20 0xa51c95 in haxe::format::JsonParser_obj::parseRec(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:372
    #21 0xa4fea6 in haxe::format::JsonParser_obj::doParse(void) c:\Users\chii\build\testjson\bin\src\haxe\format\JsonParser.cpp:51
    #22 0xa46171 in Main_obj::__construct(void) c:\Users\chii\build\testjson\bin\src\Main.cpp:19
    #23 0xa4637b in Main_obj::__alloc(class hx::ImmixAllocator *) c:\Users\chii\build\testjson\bin\src\Main.cpp:55
    #24 0xa46bc8 in Main_obj::main(void) c:\Users\chii\build\testjson\bin\src\Main.cpp:39
    #25 0xa75ca7 in __hxcpp_main c:\Users\chii\build\testjson\bin\src\__main__.cpp:21
    #26 0xa75f15 in main C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\HxcppMain.h:93
    #27 0xc335ed in invoke_main d:\a01\_work\10\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #28 0xc335ed in _scrt_common_main_seh d:\a01\_work\10\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #29 0x76206708  (C:\WINDOWS\System32\KERNEL32.DLL+0x6b816708)
    #30 0x77677ccc  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4b2e7ccc)
    #31 0x77677c9a  (C:\WINDOWS\SYSTEM32\ntdll.dll+0x4b2e7c9a)

Address 0x00a1d3d0 is located in stack of thread T0 at offset 0 in frame
    #0 0xb916bf in GlobalAllocator::GetFreeBlock(int, class hx::ImmixAllocator *) C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:3490

  This frame has 1 object(s):
    [16, 17) 'forceCompact'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp, SEH and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\src\hx\gc\Immix.cpp:5554 in hx::MarkConservative(int *, int *, class hx::MarkContext *)
Shadow bytes around the buggy address:
  0x30143a20: 00 00 00 f1 f1 00 00 04 f2 f2 f2 f2 00 04 f2 f2
  0x30143a30: f2 f2 00 00 00 f2 f2 f2 f2 f8 f2 04 f2 f8 f2 f8
  0x30143a40: f2 f8 f2 f8 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x30143a50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x30143a60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x30143a70: 00 00 00 00 00 00 00 00 00 00[f1]f1 01 f3 f3 f3
  0x30143a80: f3 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x30143a90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x30143aa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x30143ab0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x30143ac0: 00 f1 f1 00 00 04 f2 f2 f2 f2 00 04 f3 f3 f3 f3
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==41184==ABORTING
</pre>
</details>

**Comment by Simn** [comment]
You've already reported this to hxcpp, which is actually the right place.
