### ISSUE TITLE
addGlobalMetadata/addMetadata @:expose does nothing

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10650]
Basically, all classes should actually be epxosed by this. Haxe ignores it, unfortunately.

-cp src
--dce no
-js build/test.js
--macro include('haxe', true, ['haxe.macro'])
--macro addGlobalMetadata('', '@:expose', true, true, false)
--macro addMetadata('@:expose', 'Std')
Test

```hx
class Test {}
```

**Comment by kLabz** [comment]
It does work, but not on `haxe` package because you need to swap `include` and `addGlobalMetadata` lines

**Comment by lublak** [comment]
@kLabz thanks 👍 this works fine.
Thought you "import" them first to add the meta data then.
Thanks allot.
