### ISSUE TITLE
VsCode workflow with missing library

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#10659]
When compiling a vscode project with a missing library, nothing is showing in Problems, instead you need to navigate to Output/Haxe to see the following:

```
Uncaught Error : Failure("Error: Cannot process [hlsteam]: Library hlsteam is not installed : run 'haxelib install hlsteam'\r")
Failure("Error: Cannot process [hlsteam]: Library hlsteam is not installed : run 'haxelib install hlsteam'\r")
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "src/compiler/haxe.ml", line 108, characters 32-335
Called from file "src/compiler/haxe.ml", line 125, characters 17-31
Called from file "src/compiler/haxe.ml", line 725, characters 8-25
Called from file "src/compiler/haxe.ml", line 1033, characters 1-15
Called from file "src/compiler/haxe.ml", line 645, characters 3-11
Called from file "src/compiler/server.ml", line 657, characters 4-30
Called from file "src/compiler/server.ml", line 686, characters 3-30
```

**Comment by Simn** [comment]
Works for me on latest:

![Code_0ybBi5F0FU](https://user-images.githubusercontent.com/634365/161217698-c6a10391-e4aa-423f-b910-10709229ea7c.png)

**Comment by Gama11** [comment]
That `Failure("...")` output that Nicolas has is caused by having `HAXEDEBUG` defined, I think? Which then of course makes it so that the error can't be parsed by the problem matcher.

**Comment by Simn** [comment]
Oh, haha, that's a good point...

**Comment by Simn** [comment]
I'll assume that this is indeed the reason, feel free to reopen otherwise.
