### ISSUE TITLE
Haxe on Mac OSX 10.9

### ISSUE THREAD

**Issue by Sosukodo** [HaxeFoundation/haxe#10668]
Does anybody know the last version of Haxe that supported OSX 10.9?

**Comment by nanjizal** [comment]
Did you try latest?
well pretty sure yosemite worked with haxe fine as I had to revert to that recently ( one above 10.9 ), Are you having issue with using 10.9 with latest haxe? It maybe just down to building with some flags for older mac builds or ocaml detail, but used many versions of haxe on leopard so haxe should not be tightly tied to mac os in general as ocaml is not either.  Haxe is mostly indifferent to mac versions, There is a flag in cpp haxe you may need for that target on 32bit or older macs. If you need a universal haxe build it maybe tricky, now haxe is setup just for 64 on a mac, if you osx is on 32 lightly tricky and have to resolve depenancy headers and build haxe yourself.  hxcpp is quite flexible but defaults may need xml tweaked

**Comment by Simn** [comment]
Please refer to https://community.haxe.org/ for inquiries like this.
