### ISSUE TITLE
Haxe Compile Error 

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/haxe#10679]
Hi, I'm getting the following error with the development branch:

dune build --workspace dune-workspace.dev src/haxe.exe
File "src/macro/eval/evalLuv.ml", line 95, characters 3-13:
95 | 	| `EOVERFLOW -> 78
        ^^^^^^^^^^
Error: This pattern matches values of type [? `EOVERFLOW ]
       but a pattern was expected which matches values of type Luv.Error.t
       The second variant type does not allow tag(s) `EOVERFLOW
make: *** [haxe] Error 1                

I've checked back a few changeless and it's still there, which inclines me to think it's an issue with my environment but I can't be sure. 

I'm compiling on a Mac if that matters.

**Comment by Simn** [comment]
`opam upgrade luv`

**Comment by onehundredfeet** [comment]
Thanks Simon.
