### ISSUE TITLE
Compiler failure

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#10672]
Currently its a very big project. I try to figure out how to make a smaller example for it:

```
Attach the following information:
Haxe: 4.2.5; OS type: windows;
File "src/context/common.ml", line 711, characters 28-35
Called from file "src/typing/typeloadModule.ml", line 439, characters 12-51
Called from file "list.ml", line 88, characters 20-23
Called from file "src/typing/typeloadModule.ml", line 435, characters 9-396
Called from file "src/typing/typeloadModule.ml", line 779, characters 14-54
Called from file "list.ml", line 106, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 777, characters 2-495
Called from file "list.ml", line 106, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 945, characters 1-53
Called from file "src/typing/typeloadModule.ml", line 1007, characters 1-35
Called from file "src/typing/typeloadModule.ml", line 1062, characters 11-48
Called from file "src/typing/typeloadModule.ml", line 1103, characters 4-45
Called from file "src/typing/typeloadModule.ml", line 502, characters 12-69
Called from file "src/typing/typeloadModule.ml", line 641, characters 3-24
Called from file "list.ml", line 106, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 945, characters 1-53
Called from file "src/typing/typeloadModule.ml", line 1007, characters 1-35
Called from file "src/typing/typeloadModule.ml", line 1062, characters 11-48
Called from file "src/typing/typeloadModule.ml", line 1103, characters 4-45
Called from file "src/typing/typeloadModule.ml", line 502, characters 12-69
Called from file "src/typing/typeloadModule.ml", line 641, characters 3-24
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed
```

**Comment by Simn** [comment]
This tries to call `com.basic.tnull` before it is initialized. Unfortunately, the call stack is too short to tell how this happened. If you can compile Haxe yourself, you could try changing the `21` here to a larger number so we can get the full picture: https://github.com/HaxeFoundation/haxe/blob/4.2.5/src/core/globals.ml#L109

**Comment by lublak** [comment]
@Simn i can try. Have never really done it myself.
I'll try it later with docker: https://github.com/HaxeFoundation/haxe/pull/10364 or set me up a debian machine.

**Comment by lublak** [comment]
I first found out that my script overwrites StdTypes.hx. (which it should not)
typedef Void = Void;
or typedef Null<T> = Null<T>; could be the problem here. I think such a special case must not necessarily be treated.

@Simn

**Comment by Simn** [comment]
Ah yeah, `typedef Null = Null` would do it. In that case the compiler won't find the actual `Null<T>`, so `com.basic.tnull` is never set and then crashes.

I'd like to have a different error message for this, but other than that there's nothing to fix here.

**Comment by lublak** [comment]
I know I know. That was not planned either.
An error message would have helped. Currently, the project is also built.
