### ISSUE TITLE
Context.onTypeNotFound triggered multiple times per context

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#10678]
Even a rather empty program will trigger `Context.onTypeNotFound` callback dozens of times, including for the same type multiple times (more than once per context).

```hxml
--macro Macro.init()
-x Test
```

Test.hx
```haxe
function main() {}
```

Macro.hx
```haxe
function init() {
  haxe.macro.Context.onTypeNotFound(t -> {
    trace(t); // (line 5 in logs below, didn't update after cleanup)
    return null;
  });
}
```

<details>
<summary>Output logs</summary>
<pre><code>
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.StringBuf
Macro.hx:5: haxe.String
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: std.Type
Macro.hx:5: haxe.StringBuf
Macro.hx:5: std.Type
Macro.hx:5: std.Type
Macro.hx:5: haxe.Std
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Std
Macro.hx:5: haxe.Std
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.String
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.StringBuf
Macro.hx:5: haxe.String
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.String
Macro.hx:5: haxe.Enum
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.iterators.Array
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.EnumValue
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Type
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Any
Macro.hx:5: haxe.Array
Macro.hx:5: haxe.Any
Macro.hx:5: std.Type
Macro.hx:5: haxe.StringBuf
Macro.hx:5: std.Type
</code></pre>
</details

**Comment by back2dos** [comment]
Myeah, I wonder if `null` results shouldn't be cached per callback. Because if it's going to hit the file system, that can quickly become very expensive.
