### ISSUE TITLE
Unsafe git repository error in github actions

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10689]
The git repository in the Windows environment is considered "unsafe", which prevents git commands running. This is [the error](https://github.com/HaxeFoundation/haxe/runs/6133014139?check_suite_focus=true#step:11:26) they give:
```
fatal: unsafe repository ('/cygdrive/d/a/haxe/haxe' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /cygdrive/d/a/haxe/haxe
fatal: unsafe repository ('/cygdrive/d/a/haxe/haxe' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /cygdrive/d/a/haxe/haxe
```
It is related to a recent [git for Windows patch](https://github.blog/2022-04-12-git-security-vulnerability-announced/).

Consequently, the windows nightly builds no longer have the commit revision in the version number, as this can no longer be retrieved. This breaks [hxcpp azure pipeline builds](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=9542&view=logs&jobId=e4e52a38-cda2-579e-f3f0-e0bd1a2466a5&j=e4e52a38-cda2-579e-f3f0-e0bd1a2466a5&t=52d20cea-f3d5-57a0-4c7b-3c059dd531c8), which tries to read this value.

**Comment by Simn** [comment]
Is this still a problem?

**Comment by tobil4sk** [comment]
Yes, the error still comes up, for example in the latest run: https://github.com/HaxeFoundation/haxe/runs/6769262225?check_suite_focus=true#step:11:27
