### ISSUE TITLE
`@:structInit` on abstract classes

### ISSUE THREAD

**Issue by ALANVF** [HaxeFoundation/haxe#10685]
It would be useful if `@:structInit` could be used on abstract classes for the purpose of also using it on subclasses:
```hx
@:structInit
abstract class A {
    public final x: Int;
}

@:structInit
class B extends A {
    public final y: Int;
}

var b: B = {x: 1, y: 2};
```
This is currently not allowed because abstract classes can't have `@:structInit`, which is inconvenient

**Comment by Simn** [comment]
This would require a haxe-evolution, it's not obvious how exactly this would work and why abstract classes should have special semantics here.

**Comment by ALANVF** [comment]
I'm not sure what special semantics you are referring to here, this would simply allow abstract classes to _also_ allow the `@:structInit` metadata, with the reason being that it can be used for subclasses (since duh, you can't directly create instances of an abstract class)

**Comment by Simn** [comment]
Huh, I kind of forgot that `@:structInit` can already be inherited like this, interesting... in that case I agree this should be a restriction that can be removed.
