### ISSUE TITLE
Errors on Abstract Types after 4.1.5

### ISSUE THREAD

**Issue by giuppe** [HaxeFoundation/haxe#10681]
I don't know if something changed on the syntax of abstract types, or if there is a regression in Haxe versions after 4.1.5. 
An abstract type `C(B)` could have an abstract type `B(A)` as its underlying type, getting the same concrete type of `B`; this is not recognized on Haxe 4.2.x, and `C` cannot be used anymore on places where we should use `A`, unless we force casting.

You can [see this snippet on try.haxe.org](https://try.haxe.org/#566E7E75), on haxe 4.1.5 it works flawlessly; on 4.2.5 compilation fails with `C should be A`:

```hx
class Test {
	static function main() {
		var a = new A();
		var b = new B();
		var c = new C();
		myTest(a);
		myTest(b);
		// this will fail with compiler error "C should be A" but works in Haxe 4.1.5
		myTest(c);

		// this works on 4.2.5
		myTest(cast c);
	}

	static function myTest(a:A) {
		trace("ok");
	}
}

class A {
	public function new() {}
}

abstract B(A) from A to A {
	public function new() {
		this = new A();
	}
}

abstract C(B) from B to B {
	public function new() {
		this = new B();
	}
}

```

**Comment by kLabz** [comment]
You can make it work with haxe 4.2+ by adding `@:transitive` to `B`

**Comment by giuppe** [comment]
Thanks, good to know! Searching for `@:transitive` I found the actual PR that added the checks on transitivity of abstract types and [it explains the changes](https://github.com/HaxeFoundation/haxe/pull/9698); I couldn't find any pointer on changelogs so I was a little dumbfounded by the errors.

> it was documented long ago that [implicit casts are not transitive](https://haxe.org/manual/types-abstract-implicit-casts.html) (last part), that just was not enforced consistently (now it is) and there was no way to allow it (now there is).

**Comment by kLabz** [comment]
Perfect, sorry I couldn't make the search and provide the links at the time of my comment, glad you found it all :+1:
