### ISSUE TITLE
Enum for numeric literal suffixes

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#10692]
Someone on discord mention its a bit odd that the suffixes are represented as a string instead of an enum and I think I agree. I'm trying to think back to when I added them but I think it was an ease of implementation thing, not any specific reason for using a string over an enum. Adding new suffixes to the enum at some point down the line could break some macros is about the only drawback I can think of.

If an enum over a string sounds like a good idea I can look into changing that.

**Comment by Simn** [comment]
I disagree because from a syntax point of view a suffix is just that, some string after the numeric literal. Restricting the domain is a matter of semantics, so the current approach is fine.
