### ISSUE TITLE
Better autocomplete when using `new`

### ISSUE THREAD

**Issue by nc-x** [HaxeFoundation/haxe#10698]
For cases such as the one in the screenshot, the type of the variable is already known, so the autocomplete can be improved to show only the types that can be used here, and the ranking can be such that the default type comes at the top and any subtypes are ranked after that.

![image](https://user-images.githubusercontent.com/43749640/166943305-60d7b4c9-08a5-41c8-a5b5-f071752a44a3.png)

I am on the latest stable haxe version.

**Comment by RblSb** [comment]
Same to https://github.com/HaxeFoundation/haxe/issues/9162
