### ISSUE TITLE
there is an issue when I type lime test windows

### ISSUE THREAD

**Issue by GoodOlHazel** [HaxeFoundation/haxe#10705]
Here is the issue when I type lime test windows:

Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 1703
Called from lime/tools/ProjectXMLParser.hx line 21
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 50
Called from lime/tools/ProjectXMLParser.hx line 2043
Called from lime/tools/ProjectXMLParser.hx line 1528
Called from lime/tools/ProjectXMLParser.hx line 608
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 719
Called from a C function
Called from lime/tools/ProjectXMLParser.hx line 709
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 69
Called from /Users/runner/hostedtoolcache/haxe/4.2.1/x64/std/neko/_std/sys/FileSystem.hx line 60
Uncaught exception - std@sys_file_type

**Comment by Simn** [comment]
Please report that to https://github.com/openfl/lime
