### ISSUE TITLE
Std.string generates bad code

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/haxe#10709]
When the method Std.string is applied to a map, the compiler generates code that fails when the map is null. The issue affects all the targets.

For example the following code ([Try Haxe](https://try.haxe.org/#9e1b5d6e))

```haxe
class Test {
  static function main() {
    var m: Map<String, String> = null;
    trace(Std.string(m));
  }
}
```

is transformed into

```js
class Test {
  static main() {
    console.log("Test.hx:4:",null.toString());
  }
}
```

**Comment by Simn** [comment]
This is pretty silly, but the code is also pretty silly. How did this occur in the real world? I want to make sure that we're not oversimplifying the problem here.

**Comment by acarioni** [comment]
Suppose that you have a function _foo_ that returns a value of type _Null<Map<String, String>>_ for example.
If you pass the returned value to _Std.string_, the compiler generates something like _foo().toString()_, that obviously fails when the value is _null_ ([Try haxe](https://try.haxe.org/#f66D9D7A)).
However the documentation of _Std.string_ says that _null_ is an acceptable value, thus the compiler should take into account the possibility.
