### ISSUE TITLE
Overriding files no longer works as expected in development builds

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#10711]
For the longest time I've used file overriding to resolve issues in libraries, for example, I override `three.Uniform` to have type parameters

https://github.com/haxiomic/three-toolkit/blob/master/three/Uniform.hx

This worked by giving the file the same module path and loading the libraries like:
```hxml
--library three
--library three-toolkit
```

So that three-toolkit's files override

However, testing in latest development build, this no longer works, with the compiler seeing only the original three.Uniform

Is this an intended change or a regression?

**Comment by Simn** [comment]
Could you compile with `-v` and check what the reported `Classpath` is? It should be the first line in that output. Maybe there's an unintended order change here.

**Comment by haxiomic** [comment]
@Simn good thought, yes class path has changed

**4.3.0**
`/Users/geo/Projects/toyota-imagination/.haxelib/three/0,135,0/;/Users/geo/Projects/toyota-imagination/.haxelib/three-toolkit/git/;/Users/geo/Projects/toyota-imagination/.haxelib/vector-math/2,4,0/;src/;;/usr/local/lib/lib/haxe/extraLibs/;/usr/local/lib/share/haxe/extraLibs/;/usr/local/lib/haxe/extraLibs/;/usr/local/lib/lib/haxe/std/js/_std/;/usr/local/lib/share/haxe/std/js/_std/;/usr/local/lib/haxe/std/js/_std/;/usr/local/lib/lib/haxe/std/;/usr/local/lib/share/haxe/std/;/usr/local/lib/haxe/std/`

**4.2.4**
`/Users/geo/Projects/toyota-imagination/.haxelib/vector-math/2,4,0/;/Users/geo/Projects/toyota-imagination/.haxelib/three-toolkit/git/;/Users/geo/Projects/toyota-imagination/.haxelib/three/0,135,0/;src/;;/usr/local/lib/lib/haxe/extraLibs/;/usr/local/lib/share/haxe/extraLibs/;/usr/local/lib/haxe/extraLibs/;/usr/local/lib/lib/haxe/std/js/_std/;/usr/local/lib/share/haxe/std/js/_std/;/usr/local/lib/haxe/std/js/_std/;/usr/local/lib/lib/haxe/std/;/usr/local/lib/share/haxe/std/;/usr/local/lib/haxe/std/`

I guess there's an open question on if `--library` ordering was an official feature of an accidental one to begin with

**Comment by Simn** [comment]
The last `--library` should take priority, so this is broken.
