### ISSUE TITLE
No completion with emojis in code

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10715]
Is this by design?
```haxe
class Main {
	static function main() {
		// 💇‍♀️
		"hi".
	}
}
```

**Comment by back2dos** [comment]
Of course it's by design! :D

I can confirm that for me this triggers top level completion.

Might be related to VSCode using UCS-2 which generally messes with positions:

![image](https://user-images.githubusercontent.com/509501/170812686-12c27a65-17c4-4849-8ce2-6f5c1e0d10c2.png)

**Comment by Simn** [comment]
This is likely a vshaxe issue because our internal processing uses UTF8.

**Comment by nadako** [comment]
https://github.com/vshaxe/vshaxe/issues/343
