### ISSUE TITLE
Is there a way to connect Firebase to Haxe?

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/haxe#10717]
Out of "curiosity", I was wondering if it was possible to connect Haxe to Firebase and send data there for leaderboards, multiplayer, game shutdowns, etc.
I've seen [extension-firebase](https://github.com/HaxeExtension/extension-firebase), but there is no complete tutorial.
Is there a way? I would really want to know.

**Comment by Simn** [comment]
Please refer to https://community.haxe.org/ for questions like this.

**Comment by haxiomic** [comment]
Hey @PrismLight, agreed community.haxe.org is the best place for questions like this

To answer your question however, you can try finding a typescript tutorial and using the typescript externs from haxe with dts2hx, which will translate them. Typescript and haxe will work similarly

Looks like someone has [tried this already](https://github.com/piboistudios/firebase-admin). As far as I can tell they did;

```
npm install dts2hx
npm install firebase-admin
npx dts2hx firebase-admin --modular
```
