### ISSUE TITLE
Odd restrictions on passing functions as args into build macros

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#10719]
passing in args to a build macro seems to fail in most cases, I can't reference external class's functions, even trace.
```hx
using StringTools;

@:build(Macro.test((s) -> true)) // works
class Test1 {}

@:build(Macro.test(TestFilter.filter)) // EvalContext.RunTimeException(_, 0, _)
class Test2 {}

@:build(Macro.test(
    (s) -> {
        trace(s);// Unknown identifier: trace
        return s != "bar";
    }
))
class Test3 {}

@:build(Macro.test((s) -> StringTools.contains(s, "bar"))) // Uncaught exception Cannot call null
class Test4 {}

class TestFilter {
    static public function filter(path:String):Bool
    return true;
}

class Test {
    static function main() {
    }
}
```

and the useless macro is
```hx
import haxe.macro.Context;
import haxe.macro.Expr;

using StringTools;

class Macro {
	public static function test(?filter:String->Bool) {
		trace(filter("foo"));
		var fields:Array<Field> = Context.getBuildFields();
		return fields;
	}
}
```

Is there a way to achieve this?

**Comment by player-03** [comment]
[Pasted this into Try Haxe](https://try.haxe.org/#B39A4DD0), in case it helps.

- It only shows one error at a time, sadly.
- I changed `trace()` to `Log.trace()` since that one's probably intended. Now it gives the `EvalContext` error instead.

But if someone actually wants to filter `getBuildFields()`, there's no need for a `filter` function. It's just as easy - and arguably clearer - to define custom metadata. Just tell the user "mark fields with `@:skip` to make the macro skip them."

**Comment by Geokureli** [comment]
the function isn't to filter existing fields, if that's what your suggesting. this was just the smallest possible example i could share. My actual example would look for all files in the assets folder and generate a field based on it's relative path if it met the filter criteria

**Comment by player-03** [comment]
Fair enough.

You could take a page out of OpenFL's book here. Accept arrays of filter strings and use wildcard matching. Typically that's more than enough to pick out the files you want.

```haxe
public static function test(?exclude:Array<String>, ?include:Array<String>):Array<Field> {
	function makeRegex(s:String):EReg {
		s = "^" + EReg.escape(s).replace("\\*", ".*") + "$";
		return new EReg(s, "");
	}
	var regexExclude:Array<EReg> = exclude != null ? Lambda.map(exclude, makeRegex) : [];
	var regexInclude:Array<EReg> = include != null ? Lambda.map(include, makeRegex) : [];
	
	function acceptFile(file:String):Bool {
		for(e in regexExclude) {
			if(e.match(file)) {
				return false;
			}
		}
		
		if(regexInclude.length > 0) {
			for(i in regexInclude) {
				if(i.match(file) {
					return true;
				}
			}
			
			return false;
		}
		
		return true;
	}
	
	var fields:Array<Field> = Context.getBuildFields();
	
	for(file in Lambda.filter(FileSystem.readDirectory(getDir()), acceptFile)) {
		fields.push(makeField(file));
	}
	
	return fields;
}
```

> this was just the smallest possible example i could share.

Always appreciated.

**Comment by Geokureli** [comment]
Thanks, I went with something similar. I wanted to add EReg args, but that caused errors, so instead I went with strings that will be used to create regular expressions, shown here in FlxAssets: https://github.com/Geokureli/flixel/commit/526f29e086ab9c6dc92a570a013760e26a1a6032

**Comment by Simn** [comment]
Your code gives me this on latest Haxe:

```
source/Macro.hx:8: false
source/Main.hx:10: foo
source/Macro.hx:8: true
source/Main.hx:6: characters 20-37 : haxe.macro.Expr should be Null<String -> Bool>
source/Main.hx:6: characters 20-37 : ... For optional function argument 'filter'
```

Which looks like what I'd expect.

**Comment by player-03** [comment]
@Simn As far as I can tell, the latest version of Haxe is 4.2.5, which is what Try Haxe uses, and [Try Haxe reproduces the error](https://try.haxe.org/#B39A4DD0).

**Comment by Simn** [comment]
I'm talking about the development version of course.

**Comment by Geokureli** [comment]
good to know this is fixed in dev haxe, I forgot to try those.
