### ISSUE TITLE
Abstract classes and interfaces result in a compiler failure on the cpp target

### ISSUE THREAD

**Issue by krisj07** [HaxeFoundation/haxe#10729]
The compiler shows the error below. The project is a larger one mostly tested on Neko. I now tried the cpp target, it had been working previously, but that's a while ago.

Without further information about what caused the issue it is not possible to even try to work around this. Is it possible to get from the compiler at least the information as to which source code file caused this error?

Compiler failure
Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new
Attach the following information:
Haxe: 4.2.4; OS type: unix;
File "src/generators/gencpp.ml", line 4574, characters 26-33
Called from file "src/generators/gencpp.ml", line 4574, characters 19-33
Called from file "list.ml", line 110, characters 12-15
Called from file "src/generators/gencpp.ml", line 6031, characters 3-159
Called from file "list.ml", line 110, characters 12-15
Called from file "src/generators/gencpp.ml", line 8485, characters 3-39
Called from file "src/compiler/haxe.ml", line 351, characters 2-14
Called from file "src/compiler/haxe.ml", line 1082, characters 25-72
Called from file "src/compiler/haxe.ml", line 642, characters 3-11
Called from file "src/compiler/haxe.ml", line 1247, characters 1-35
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

**Comment by krisj07** [comment]
I downloaded the latest git version of the Haxe compiler (revision b0d915211), and was able to add some contextual information to the error message (which on the latest version happens on line 4590):

### Modified src/generators/gencpp.ml line 4590:

```ocaml
| _ -> die ("ERROR_MSG " ^ "(" ^ class_name ^ "," ^ remap_name ^ ")")  __LOC__
```

With this information I was able to find out the source file where the error happened. The error seems to be related to interface methods defined later in classes inheriting from an abstract class implementing the interface. I made a minimal example to replicate the issue:

### Test program Main.hx:

```haxe
interface IA
{
    public var a(get, never):String;
}

abstract class A implements IA
{
    public function new() {}
}

class B extends A
{
    public inline function get_a() { return "a"; }
    
    public function new() { super(); }
}

class Main
{
    static function main()
    {
        var test = new B();
        trace(test.a);
    }
}
```

With the compiler version mentioned above, this program reproduces the "Compiler failure" error on the cpp target.

### Test program output:

```
Compiler failure: ERROR_MSG (A_obj,a)
Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new
Attach the following information:
Haxe: 4.3.0-rc.1; OS type: unix;
File "src/generators/gencpp.ml", line 4590, characters 83-90
Called from file "src/generators/gencpp.ml", line 4590, characters 19-90
Called from file "list.ml", line 110, characters 12-15
Called from file "src/generators/gencpp.ml", line 6047, characters 3-159
Called from file "list.ml", line 110, characters 12-15
Called from file "src/generators/gencpp.ml", line 8515, characters 3-39
Called from file "src/compiler/generate.ml", line 99, characters 2-14
Called from file "src/compiler/compiler.ml", line 318, characters 29-64
Called from file "src/compiler/compiler.ml", line 333, characters 1-5
Called from file "src/compiler/compiler.ml", line 411, characters 2-157
Called from file "src/compiler/compiler.ml", line 388, characters 2-9
Called from file "src/compiler/compiler.ml", line 602, characters 5-43
Called from file "src/compiler/compiler.ml", line 612, characters 13-22
Called from file "src/compiler/server.ml", line 633, characters 1-39
Called from file "src/compiler/haxe.ml", line 53, characters 0-56
File "src/core/globals.ml", line 120, characters 1-7: Assertion failed
```

I've updated the issue title to take into account this additional information.

**Comment by Simn** [comment]
We can simplify this further:

```haxe
interface IA {
	public var a:String;
}

abstract class A implements IA {
	public function new() {}
}

class B extends A {
	public function new() {
		super();
	}
}
```

I always forget how the `abstract` + `implements` interaction works. What does it mean if an abstract implements an interface that has a variable? We don't allow abstract variables, so this looks like it should be a compiler error.
