### ISSUE TITLE
[jvm] Pattern matching involving unicode

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#10720]
v4.2.5

```haxe
function foo() return '😀 😀';

switch (foo()) {
	case '😀 😀':
		trace('yo');
	case v:
		trace('meh');
}
```

this prints "yo" in nodejs and "meh" in jvm

**Comment by Simn** [comment]
This might be about the hashing being used. IIRC we determine a hash at compile-time and compare it to the one from run-time.

**Comment by kevinresol** [comment]
Java treats each emoji to have length 2. So I guess that's where the issue comes from:

```haxe
function foo() return '😀 😀';
function bar() return 'abc';
function baz() return '名 字';

function main() {
	trace(hashCode(foo()), ((cast foo():java.lang.Object).hashCode()), foo().length);
	trace(hashCode(bar()), ((cast bar():java.lang.Object).hashCode()), bar().length);
	trace(hashCode(baz()), ((cast baz():java.lang.Object).hashCode()), baz().length);
}

function hashCode(value:String) {
	var h = 0;
	
	if(value.length > 0) {
		for(i in 0...value.length) {
			h = 31 * h + value.charCodeAt(i);
		}
	}
	
	return h;
}
```

prints:

```
src/Main.hx:8: 1278630208, 1278630208, 5
src/Main.hx:9: 96354, 96354, 3
src/Main.hx:10: 20702212, 20702212, 3
```

**Comment by Aurel300** [comment]
Java uses a modified UTF-8 encoding, described [here](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.7). In particular, code points above `U+FFFF` are encoded using two surrogate code units instead of the standard 4-byte UTF-8 sequence representing a single code unit.

**Comment by Simn** [comment]
Fortunately, I found a `java_hash` implementation in genjava which deals with this stuff.
