### ISSUE TITLE
[php] Reading anonymous structures from session is broken

### ISSUE THREAD

**Issue by j-jzk** [HaxeFoundation/haxe#10736]
The way anonymous structures are created in PHP now (a special class instead of an instance of `HxAnon`) broke reading anonymous structures from the session.

Consider the following example:
```haxe
class Save {
	static function main() {
		php.Session.set("test", {data: 123});
	}
}

class Read {
	static function main() {
		trace(php.Session.get("test").data);
	}
}

```

The second file yields the following error:
```
PHP Fatal error:  method_exists(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;_HxAnon_Save0&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /tmp/hxtest/read/lib/php/Boot.php on line 202
```

This is because the second file doesn't see the class generated for the anonymous structure and thus cannot unserialize it.
It might look obvious from the generated code, but I still think that this is a bug, since it broke some of my code.

A workaround is to serialize the data with `haxe.Serializer`/`haxe.Unserializer` before passing them to the session, but that induces some overhead and the code then isn't very pretty.

**Comment by RealyUniqueName** [comment]
I had to revert anonymous objects optimization (#7916) because with that optimization there's no way to guarantee serialization/unserialization of anon objects across multiple apps.
