### ISSUE TITLE
Why does haxe not allow package with upper character?

### ISSUE THREAD

**Issue by DeafMan1983** [HaxeFoundation/haxe#10732]
Hey everyone, 

I don't expect that C# allows namespace with upper character like this 
`namespace Systen;`

For haxe's package:
```
package X11
       /\
```

But it looks invalid like directory like `src/X11`

That is why it is not allowed 🚫. 

I would like to have new version for package with upper character because I developed own haxelib with upper character. 
For OpenFl because current version of OpenFl looks incompatible for web version you know far since Flash Player is dead. We would like to convert to web assembly (WASM) with universal EGL.

That is why haxe's package should allow with upper character like example `package Haxe.System;`

Do you expect to write package's namespace with upper character then who moves from C# or Java coding and they don't have to worry with upper character into package.

**Comment by Simn** [comment]
This was a conscious decision when the language was originally designed and likely comes from its Actionscript 3 heritage. The compiler does use the casing to simplify some internal path handling, and there are no plans to lift this restriction.

**Comment by DeafMan1983** [comment]
Ok no problem @Simn you're right. We want forget about Actionscript 3 because it is already gone from Adobe's documentations. We would like to disinherit Haxe from Actionscript 3. But you decide that. I will respect you. And stay safe!
