### ISSUE TITLE
Abstract methods in generic, abstract classes cause compile errors

### ISSUE THREAD

**Issue by Jrayp** [HaxeFoundation/haxe#10735]
Haxe 4.2.5

I'm not sure if there is a logical reason for this, but it seems like a bug to me. See https://try.haxe.org/#b501c2DC

```haxe
class Test {
	static function main() {}
}

@:generic
abstract class A<T> {
	abstract function foo():Void;
}

class B extends A<Int> {
	function foo() {}
}

```
This causes two errors:
```
Test.hx:7: characters 2-31 : Field foo has no expression (possible typing order issue)
Test.hx:10: characters 17-23 : While building A_Int
```

**Comment by AbeGellis** [comment]
Also encountering this, I was able to work around it by removing the abstract modifier from the base class and adding a dummy implementation to the abstract method. Not ideal since I can't prevent instantiation with compile-time checks.
