### ISSUE TITLE
hlc generated code names can clash with builtin types?

### ISSUE THREAD

**Issue by robinp** [HaxeFoundation/haxe#10734]
Hello - after generating with Haxe 4.2.3 a Main.c output (using `-hl out/c/Main.c`), having a name clash.

For example, haxeui has a function named `bool`, which gets generated into some structure that has a `vclosure* bool` field. On Linux, gcc chokes on that with 
```
out/c/haxe/ui/styles/ValueTools.h:36:12: error: expected identifier or ‘(’ before ‘_Bool’
   36 |  vclosure* bool;
      |            ^~~~
```
I wonder whose responsibility would it be to avoid clashes? haxe and hlc? Or writers of libraries?
cc @ianharrigan

**Comment by kLabz** [comment]
The `bool` example has been fixed. Feel free to reopen if you have other examples.
