### ISSUE TITLE
[ide] abstract expression is displayed as `this:UnderlyingType` on hover

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#10747]
![image](https://user-images.githubusercontent.com/49749/177118138-22952d43-787d-4e16-a0b8-201165850bb7.png)

```haxe
enum abstract E(Int) {
	final A;
	final B;

	function f() {
		switch (abstract) {
			case A:
			case B:
		}
	}
}
```

**Comment by nadako** [comment]
Also, both `this` and `abstract` are shown as "argument" there, which is a bit confusing.

**Comment by RblSb** [comment]
There is disabled test about it https://github.com/HaxeFoundation/haxe/pull/10513
