### ISSUE TITLE
Inconsistency in new Vector

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#10755]
Creating empty Vector<Int> return different result for javascript and Hashlink .
Example : 
```haxe
 var vc = new Vector<Int>(4);
 trace("Vector: "+vc);
```
It will return ``` [null,null,null,null]``` for Javascript, Neko, Eval  , but will return ```[0,0,0,0]``` for Hashlink. 
 Code:  https://try.haxe.org/#D8D21c29
I think the correct behavior should be to return ```[0,0,0,0]```

**Comment by RblSb** [comment]
https://haxe.org/manual/types-nullability.html

**Comment by flashultra** [comment]
Thank you!
