### ISSUE TITLE
[JS] Binding Array<T>.push generates a T->Void instead of T->Int

### ISSUE THREAD

**Issue by vladimirvelikov** [HaxeFoundation/haxe#10754]
Hi,
I hope this is not a false positive and is not already opened.

It happens on the js-target. Also reproducible with the current nightly.

Neko and eval targets work as expected.

Here is a https://try.haxe.org/#2bDDD79b for convenience.

```
class Test {
	
	public static function main() {
		var a = [0, 1, 2];
		var boundPush = a.push.bind();
		trace("new length:" + boundPush(3));     //new length:undefined
		trace(a); //[0,1,2,3]
	}
}
```

In the generated code you find 

`function $arrayPush(x) { this.push(x); }`

which is missing a

 `return`

**Comment by back2dos** [comment]
I can confirm this fails with 4.2.5, but from what I can see on tryhaxe, it seems it was fixed between a49b191 (see https://try.haxe.org/#62Edb9E2) and 4e5e766 (see https://try.haxe.org/#0b010d5d). Also, it looks like it broke between between [3.1.3](https://try.haxe.org/#c6ba3574) and [3.2.1](https://try.haxe.org/#3f3C05f3)

**Comment by nadako** [comment]
Yeah we literally just need to add a return there

**Comment by back2dos** [comment]
Myeah ... but ... do we need to do anything if it works with a nightly from 3 weeks ago? Seems like at some point the output was changed to avoid `$bind` altogether in some cases.
