### ISSUE TITLE
Equality fails through `Dynamic`

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#10760]
```haxe
class Test {
  static function main() {
    var a = haxe.Int64.make(1, 1);
    var b = haxe.Int64.make(2, 2);
    var c = haxe.Int64.make(3, 3);
    var res = a + b;
    trace(res == c);
    trace((res:Dynamic) == (c:Dynamic));
  }
}
```

```
Test.hx:7: true
Test.hx:8: false
```

(at least JS, Eval, and HashLink)

This is causing issues e.g. if you want to `utest.Assert.eq(...)` two `Int64`s (which takes `Dynamic` arguments). Is this the intended behaviour?

**Comment by back2dos** [comment]
I suppose it's "accepted" behavior and `utest.Assert.eq` will have to add the required reflection code.

We could also have a `Std.equals` and perhaps even insert it where appropriate, or leave it to the user (or library authors) to put it in all the right places.

**Comment by Simn** [comment]
I don't particularly like this either, but it falls under the "Use Dynamic at your own risk" clause. I think something like `Std.equals` would be a good contribution either way, but even then I'd still not necessarily want to translate any Dynamic comparison operators to that.
