### ISSUE TITLE
i cant test game

### ISSUE THREAD

**Issue by nebniywolf** [HaxeFoundation/haxe#10768]
![image](https://user-images.githubusercontent.com/104686407/182683786-ced236cd-2c23-445d-9f43-f02bb2f4dc07.png)
![image](https://user-images.githubusercontent.com/104686407/182684131-f2e5b317-0053-4032-8ec4-76bb25c27385.png)
![image](https://user-images.githubusercontent.com/104686407/182684209-88043c0c-1e5c-45e7-959f-8fe2865d74dd.png)

help ;-;

**Comment by Aurel300** [comment]
This is not a Haxe issue, it is an issue with the tutorial source code (`TurnBasedRPG`?), which might be coming from `lime` or some other place, I don't know.
