### ISSUE TITLE
Effectful initializations of DCEd fields are removed too.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#10766]
Consider this code ([tryhaxe](https://try.haxe.org/#2C50F931)):

```haxe
class Test {
  static function main() {
    trace("Haxe is great!");
  }
  
  static var blargh = hoho();
  
  @:pure(false) // just to be sure
  static function hoho() {
    trace('foo');
    return 123;
  }
}
```

The whole call to `hoho` is gone. In the generated JS code, with `@:keep` on `blargh`, we get `Test.blargh = Test.hoho();` and *ideally* it would still generate `Test.hoho();` without the `@:keep`. Not sure how easy this is and I guess changing this will start generating quite a bit more code, but I thought I'd at least bring it up for discussion, because it doesn't seem correct to eliminate an effectful call like that.

**Comment by RblSb** [comment]
Also https://github.com/HaxeFoundation/haxe/issues/10433

**Comment by back2dos** [comment]
Whoop, sorry.
