### ISSUE TITLE
Restoring lua tests

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10777]
Seems like we forgot to fix the lua tests after "temporarily disabling them" in 8027d746888afb9aeeee077b737dec175417945a

We discussed this on slack a long time ago, but we need to update: https://github.com/jdonaldson/haxe-deps
as the `git:` protocol is no longer supported (which is used in the source url). I think it can just be updated to `https`.

@jdonaldson I made a PR for this, would you be able to handle making a release? https://github.com/jdonaldson/haxe-deps/pull/2

Also, it is worth considering adding `luasec` to the file, because it is now a potential dependency since: #10593. This haxe-deps project seems to be used to install all potential dependencies, even if they are not necessarily used in all haxe lua projects, so it makes sense to add it. Right now we have to install it manually for the tests: https://github.com/HaxeFoundation/haxe/blob/55f4b332022e6e84503db0f6bfa251112dcc8127/tests/runci/targets/Lua.hx#L73-L74

We should also probably mention haxe-deps in the manual, but that is an issue for that repository.

**Comment by Simn** [comment]
Looks like we'll have to fork haxe-deps and handle this ourselves. I'm not sure what "making a release" entails here exactly, are we blocked from something if Justin doesn't handle it?

**Comment by tobil4sk** [comment]
I think it has to be uploaded here: https://luarocks.org/modules/jdonaldson/haxe-deps

**Comment by inklit** [comment]
FYI, I attempted to fork haxe-deps and update it with my fork in my PR #10916 but found that simply changing the protocol to https did not seem to work, and after fiddling with it for too long I decided to just remove this dependency and manually reference the dependencies for the unit tests.

**Comment by tobil4sk** [comment]
> I decided to just remove this dependency

@inklit I think it's important to have (and use) this package, as it pins down all the lua dependencies required to run the lua target in a single location. Otherwise, we have to manually keep the unit tests and documentation in sync, which is error prone and bound to cause issues. So I think it's worth fixing this package and adding it to the documentation.

Looks like we have to use `git+https`, not just `https`: https://github.com/luarocks/luarocks/issues/1408#issuecomment-1148063894. It looks like luarocks 3.8+ autoconverts the `git` protocol to fix the errors, but since we are still dealing with older versions of luarocks we should probably just fix it properly. I've updated my PR in the haxe-deps repository to fix the protocols.

We should transfer the haxe-deps repository to HaxeFoundation (or make a fork) and figure out how we can add a new author to the luarocks package.
