### ISSUE TITLE
[jvm] Generated .class files are invalid on windows

### ISSUE THREAD

**Issue by Maaxed** [HaxeFoundation/haxe#10770]
**Environment**
OS: Windows 10
Haxe version: 2022-08-03_development_848a9a5
Target: jvm

When compiling with the option ``-jvm path\to\folder\`` on windows, the generated .class files are invalid.
The issue is that the carriage return character is added before every line feed character even tough it is a binary file.
This doesn't happen if you directly output the jar with ``-jvm path/to/file.jar``.

Looking a bit into the code I think it come from the implementation of add_entry in file_output that uses open_out instead of open_out_bin to open the .class file.
A good solution would be to add a add_entry_bin method in jvm_output that would take bytes in input instead of a string for the content. This would allow a different implementation for standard files and binary files

**Comment by Simn** [comment]
Thank you for the report and the investigation, I have fixed it like you suggested.
