### ISSUE TITLE
Operator expressions do not parse if they contain anonymous functions

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10782]
Example:
```haxe
final b = a + {final x = 10; x * x;}; // this is fine
final b = {final x = 10; x * x;} + a; // this is a compiler error: "characters 34-35 : Expected }"
final b = ({final x = 10; x * x;}) + a; // this on the other hand is fine too.
```

I discovered this by coming across a similar example to the one displayed in the example below, which is preventing ufront from compiling with haxe 4: https://github.com/ufront/ufront/issues/28

```hx
@:callable
abstract Function(Int->Int) to Int->Int from Int->Int {
	@:op(a + b)
	static function add(a:Function, b:Function):Function {
		return (i) -> a(b(i));
	}
}

class Test {
	static function main() {
		final f:Function = (a) -> a + 1;
		final g = ((a) -> {a * a;}) + f; // no issue here
		final h = (a) -> {a * a;} + f; // Test.hx:13: characters 30-31 : Expected }

		trace(g(10));
		trace(h(10));
	}
}
```

**Comment by Simn** [comment]
I can't immediately spot what you consider broken here. We don't allow any "next" expressions after a block because that leads to things like these being parsed as a call:

```haxe
{
    // exprs
}
(something).something;
```

**Comment by tobil4sk** [comment]
I guess what I consider broken is that one of these works but the other doesn't:

```haxe
final b = a + {final x = 10; x * x;}; // this is fine
final b = {final x = 10; x * x;} + a; // this is a compiler error: "characters 34-35 : Expected }"
```

It seems weird that an operation works one way round but not the other way round. It also seems weird that the current solution affects any `}`s, no matter what construct it's a part of, including lambda functions like in the original post. It's also inconvenient that it used to work and now it doesn't (specifically with regular anonymous function syntax) and as a result some libraries have broken.

It also makes it even more of an issue when operators are introduced that can either be unary or binary, like `-`, for example see: https://github.com/HaxeFoundation/haxe/issues/4767#issuecomment-1279853127.

I see why the example you gave prevents this from being a simple thing to solve, but the current solution feels slightly hacky and makes parsing more complicated. Maybe it's worth figuring out how other languages treat the case you mentioned.

**Comment by Simn** [comment]
I remember trying to continue parsing after `}` and it lead to all sorts of parsing problems. The one with the call is just the only one I remember right now, but there was plenty of other stuff going on. So this has been discussed before, and the current behavior is working as intended.

The case you point out in #4767 is going to cause a "This code has no effect" diagnostic, which I consider a good enough safety mechanism here.

**Comment by tobil4sk** [comment]
> So this has been discussed before

Was this discussed in a github issue somewhere?

I looked into it and rust manages to get this right:
```rust
// both of these are fine
let a = { 10 * 2 } + 11;
let b = 11 + { 10 * 2 };

// doesn't parse as a call
{
   let f = |i:i32| -> i32 {println!("{}", i); i + 1};
}(10);

// parses as a call because it's part of an expression
let a = {
   |i:i32| i + 1
}(10);
```

I guess it may be slightly more complicated in haxe which doesn't have a statement vs expression distinction. However, at the very least, the error message should be improved to better communicate this limitation, because this error is completely incomprehensible:
```haxe
final b = {final x = 10; x * x;} + a; // "characters 34-35 : Expected }"
```


To go back to the original issue that led me to discover this before I got caught up in all the general block stuff, this broke with haxe 4:
```haxe
@:callable
abstract Function(Int->Int) to Int->Int from Int->Int {
	@:op(a + b)
	static function add(a:Function, b:Function):Function {
		return function(i) { return a(b(i)); };
	}
}

class Test {
	static function main() {
		var f:Function = function (a) { return a + 1; }

		var g = (function(a) { return a * a; }) + f; // no issue here
		var h = function(a) { return a * a; } + f; // characters 41-42 : Expected }

		trace(g(10));
		trace(h(10));
	}
}

```
Since this is a regression and really it's about anonymous functions rather than actual blocks, perhaps it is separate from the block issue? Or was there some reason for disallowing this as well?

**Comment by Simn** [comment]
It's not a regression, this was a deliberate breaking change: #5854

**Comment by tobil4sk** [comment]
> It's not a regression, this was a deliberate breaking change: https://github.com/HaxeFoundation/haxe/issues/5854

Ah, that explains it. Thanks!

**Comment by tobil4sk** [comment]
@Simn I've done some pondering on this issue, and it seems the issue discussed in #5854 is specifically for "top-level" function declarations in a block:
```haxe
// we don't want this to parse as a call, to be consistent with other C-style langs, including JS, TS, etc
function someFunc(arg) {
    ...
}
(ident);
```

Extending this behaviour to function declarations embedded in expressions is unnecessary, and inconsistent with other ECMAScript languages.

For example, Javascript parses this as a call:
```javascript
var tmp = function(str) { return str; } ("hello");
tmp // 'hello'
```
It's possible to allow haxe to work in the same way. This way we would get the best of both worlds, because #5854 will still be fixed, but at the same time, operator overloads will still work with anonymous functions, which solves the regression, fixing all the old code that relies on operator overloads for functions.

One final case: this situation should give the same error it does currently, which is consistent with the error TypeScript gives:
```haxe
function (arg) { // Unnamed lvalue functions are not supported
    ...
}
(ident);
```

I've implemented the fix, along with all the tests (including the missing ones for the original issue #5854), see: #10855

**Comment by Simn** [comment]
> For example, Javascript parses this as a call:
> 
> ```js
> var tmp = function(str) { return str; } ("hello");
> tmp // 'hello'
> ```

But that's just another version of #5854. I don't see why we should make a distinction between `var = function` and just plain `function` at a syntactic level.

**Comment by tobil4sk** [comment]
> I don't see why we should make a distinction between var = function and just plain function at a syntactic level.

I doubt that #5854 would have been reported, much less fixed, if not for the expectation for Haxe to be consistent with C style languages. But, if we don't make this distinction, then we're not being consistent.

In C, (with a compiler that allows local functions) the following does not parse as a call. Since all C-style languages work like this, this is why #5854 was originally reported, because the expectation was that Haxe should work in the same way.
```c
void someFunc(int arg) {
    ...
}
(ident);
```

But there is no reason to break all the other cases, which have worked for most of Haxe's existence. Disallowing this does not make it more consistent with JavaScript, TypeScript, or any other language, all it does is break anonymous functions embedded in other expressions, which should really be unrelated to #5854.

This should be a call, because that is how it has been in Haxe until 4.0, and how it has always been in JavaScript:
```haxe
var tmp = function(str) { return str; } ("hello");
```

Since this is not a top level function declaration, but it's embedded in a statement (and statements generally end in semicolons), it makes sense to require a semicolon in order to end the statement here:
```haxe
var tmp = function(str) { return str; };
("hello");
```

But a regular function declaration, be it a method in a class, a local function in a block, or a module level function, does not require a semicolon, so it should not require a semicolon to assume a new line.

**Comment by Simn** [comment]
This entire regression angle is not a good argument. As I've said, this was a deliberate change in a major version, which is where breaking changes should be made.

Even if we make the assumption that there was an oversight due to the distinction of "toplevel" functions (which I don't), it's not a good argument because the perceived regression occurred four years ago and could now (three official releases later) only be replaced by another perceived regression.

We can talk about C and JavaScript and other languages as much as we want, but at the end of the day it all comes down to the fact that this variant of #5854 should not be parsed as a call:

```haxe
class Main {
	static function main() {
		var test = function(window) {
			trace(window);
		}

		// hey

		(js.Browser.window : js.html.Window).document;
	}
}
```

**Comment by tobil4sk** [comment]
@Simn it's possible to disallow calls like this by checking for `(` when a function declaration ends, and not continuing the expression if it is present. Would a patch like this be considered?

This would give symmetry for binary expressions:
```haxe
// both valid
final g = function () {} * f;
final g = f * function() {};
```

While still avoiding all cases of unwanted immediate invocation:
```haxe
// none of these would be parsed as calls
function (_) {}
("hello");

(_) -> {}
("hello");

function f(_) {}
("hello");

final g = function (_) {}
("hello");

final g = (_) -> {}
("hello");

final g = function f(_) {}
("hello");
```
