### ISSUE TITLE
completion for getter in interface

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#10795]
Completion is not working if `foo` has type `IFoo`, but works fine if I change it's type to `Foo`.
```haxe
class Bar {
	public var foobar:Int = 0;

	public function new() {}
}

interface IFoo {
	var bar(get, never):Bar;
}

class Foo implements IFoo {
	public var bar(get, never):Bar;

	public function new() {}

	private function get_bar() {
		return new Bar(); 
	}
}

function main() {
	var foo:IFoo = new Foo(); // try changing type to Foo
	foo.bar. // autocomplete here. It does not work with IFoo, but works with Foo
}
```

I'm using Haxe 4.2.5 and VS Code on Mac.
This can also be reproduced on try.haxe: https://try.haxe.org/#2b6bc6B3

I've tried using completion from command line, but it just did not work. This is a separate issue though.

**Comment by Simn** [comment]
This works for me on latest Haxe.
