### ISSUE TITLE
Http: responseHeaders missing in JS?

### ISSUE THREAD

**Issue by haath** [HaxeFoundation/haxe#10794]
Hello,

The `Http` object appears to be missing the `responseHeaders` field when targeting JavaScript.
It seems strange, since apart from this field the `Http` seems identical to that of the `Sys` targets.

Is this intended? If yes, how should I go about obtaining the response headers when targeting JavaScript?

Thanks!

**Comment by haxiomic** [comment]
I'm not sure there's a good reason preventing this as getResponseHeader() exists on XMLHttpRequest: https://xhr.spec.whatwg.org/#dom-xmlhttprequest-getresponseheader

I agree this should be added to HttpJs.hx
