### ISSUE TITLE
Missing semicolon not a problem for object litterals

### ISSUE THREAD

**Issue by flipflophhj** [HaxeFoundation/haxe#10796]
This should complain about missing semicolon but doesn't.

class Test {
  static function main() {
    var p = { x:"there" }
    trace("Hello");
  }
}

https://try.haxe.org/#C4dBA571

**Comment by Ilir-Liburn** [comment]
If I recall correctly, Haxe uses "everything is an expression" principle, therefore semicolon is not required

[https://blog.onthewings.net/2012/10/14/haxe-tips-everything-is-an-expression/](url)

**Comment by flipflophhj** [comment]
Clearly correct but it feels wrong :/

**Comment by Ilir-Liburn** [comment]
Depends how you see it: I see it as (anonymous) object block where members are separated by colons, not semicolons. Therefore, "everything is an expression" doesn't apply (uses semicolon after declared block).
But I don't have overall view, e.g. if this can bring problems elsewhere.

**Comment by Simn** [comment]
By design, semicolon is optional after `}`.
