### ISSUE TITLE
Haxe or haxelib not registering as a command

### ISSUE THREAD

**Issue by The6thelementschool** [HaxeFoundation/haxe#10798]
i open powershell (cmd does not work for some reason)
and i ran the setup
i do this
haxelib install lime
and i just keep getting a error that says The command haxelib is not recognized.

**Comment by MemeHoovy** [comment]
> i open powershell (cmd does not work for some reason) and i ran the setup i do this haxelib install lime and i just keep getting a error that says The command haxelib is not recognized.

did you make sure you installed haxe 4.2.5?

**Comment by The6thelementschool** [comment]
ill do it when i get the chance then ill update the issue

**Comment by Simn** [comment]
This is some kind of setup problem on your end, please refer to http://community.haxe.org if you have further trouble!
