### ISSUE TITLE
diagnostics/cache MacroStringTools missing return `haxe.macro.Expr`

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#10805]
Getting `haxe/versions/4.2.5/std/haxe/macro/MacroStringTools.hx:42: lines 42-46 : Missing return: haxe.macro.Expr` in my Haxe log, breaking the cache server. At one point it was even happening on fresh server restart when building cache (the project compiled fine though).

Fixed it by changing https://github.com/HaxeFoundation/haxe/blob/4.2.5/std/haxe/macro/MacroStringTools.hx#L35 to just `#if macro`. There's more of those added in https://github.com/HaxeFoundation/haxe/commit/e6f3b7d3a773598aae611338cbf225cb9e1cbfeb, not sure how that works or what would be the correct fix.

**Comment by Simn** [comment]
I think that commit was pretty much just a hack which we no longer need. I'll see what happens if we revert that.

**Comment by Simn** [comment]
It's been two weeks and nobody has yelled at me yet... well, at least not because of this change. So I suppose this is fine!
