### ISSUE TITLE
[eval] Invalid argument  Array.make

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#10804]
When testing on Windows 32-bit OS (via Github Actions) I get the following error:
```
Fatal error: exception Invalid_argument("Array.make")
Raised by primitive operation at file "src/macro/eval/evalEmitter.ml", line 99, characters 24-70
```
Here is the full log :   https://github.com/HaxeFoundation/crypto/actions/runs/3141425758/jobs/5103847307#step:11:50

**Comment by Simn** [comment]
This probably comes from something along the lines of `new haxe.ds.Vector(-1)`.

**Comment by Simn** [comment]
The underlying implementation seems to allow size 0, so I'm checking for < 0 only.

**Comment by flashultra** [comment]
I track the issue to this code : 
```haxe
		var xbuf = new Vector<Int>(mfwords);
		var vbuf = new Vector<Int>(N * mfwords);
		var xtbuf = new Vector<Int>(16);
```
where 
```  mfwords=256 , N=16384    and   N*mfwords=4194304```
There is not ```-1```  value  , when created the ```new Vector```
The problem exist only for eval target on win 32bit machine. It works on win 64 bit

**Comment by Simn** [comment]
Right, we should catch the case where we can't allocate too.

**Comment by flashultra** [comment]
Yes, the problem is on this row ```var vbuf = new Vector<Int>(4194304);``` . So this is not possible to be fixed as there not enough memory to run this on Github action ?

**Comment by Simn** [comment]
That seems to be the case, yes.
