### ISSUE TITLE
Haxe windows compilation from sources

### ISSUE THREAD

**Issue by kiroukou** [HaxeFoundation/haxe#10802]
Hello,

I'm following the setup, but I'm facing an issue I'm not sure to solve by myself.

` opam install haxe --deps-only

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[haxe.4.2.4] no changes from file://P:/haxe

The following dependencies couldn't be met:
  - haxe → camlp5 = 8.00 → ocaml < 4.13.0
      base of this switch (use `--unlock-base' to force)

No solution found, exiting`

How should I solve this?  Some config which is not up to date correctly or simply a package ocaml I need to update?

Thanks for your insights

**Comment by Simn** [comment]
Sounds like your OCaml version is too recent... Try using something that's `< 4.13.0`.

**Comment by kiroukou** [comment]
Hello Simn and thank you.

`
opam list
 Packages matching: installed
 Name          Installed      Synopsis
base-bigarray  base
base-threads   base
base-unix      base
ocaml          4.14.0          The OCaml compiler (virtual package)
ocaml-config   2               OCaml Switch Configuration
ocaml-variants 4.14.0+mingw64c Pre-compiled 4.14.0 release (mingw64)
`

Sounds correct.  I'll check how I can do that.

**Comment by Simn** [comment]
I'll assume that this helped!

**Comment by kiroukou** [comment]
In fact i haven't had time to check it. I'll let you know.

Le mer. 28 sept. 2022, 12:51, Simon Krajewski ***@***.***> a
écrit :

**Comment by Timmmm** [comment]
I also had this problem. Fixed it with this command in the Cygwin64 Terminal.

```
opam switch create 4.12.1+mingw64
```
