### ISSUE TITLE
Reflect.callMethod and function's optional/default values on static plateforms

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10810]
Hej,

I'm sorry, It's not really a bug but I would know something : 
Having this code https://try.haxe.org/#e65F9c55 : 
```haxe
class Test {
    static function main() {
        trace(foo());                                    // 0
        // trace(foo(null));                             // On static platforms, null can't be used as basic type Int
        trace( Reflect.callMethod(Test, foo, []) );      // 0
        trace( Reflect.callMethod(Test, foo, [null] ) ); // 0
    }

    static function foo(n:Int = 0) {
        return n;
    }
}
```
Tested this example with HL.
I would expect that the last call `Reflect.callMethod(Test, foo, [null] )` throws a run-time exception but it acts like passing null here, this is replaced by the default value.
So my question is : Is it something that depends on how `Reflect.callMethod` is implemented on different plateforms OR is it something whole Haxe specification that says "Reflect.callMethod" have to act like that ?

Thanks for reading me

**Comment by Simn** [comment]
This is working as intended, on static targets `null` becomes the default value for non-nullable basic types. The compiler doesn't allow it, but you can cause it via Dynamic/reflection.
