### ISSUE TITLE
Language server hangs due to duplicate --connect flags

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10813]
To reproduce:
```
haxe -v --wait 6000 
```

```
haxe --connect 6000 --connect 6000
```

The second --connect arg is passed onto the server, causing it to hang. This is the output before it becomes unresponsive:
```
Client connected
Reading 49 bytes

Processing Arguments [--cwd,/path/to/project/,--connect,6000]
```
This is a common situation, as `--connect 6000` might be found in an hxml file, as is common for lime projects. As a result, everything breaks: https://github.com/openfl/lime-vscode-extension/issues/93

This is only an issue on nightly, not on 4.2.5 (or any commit before #10629). There the server doesn't hang, and it simply outputs:
```
Client connected
Reading 49 bytes

Processing Arguments [--cwd,/path/to/project,--connect,6000]
 0,  x: Cached 0 modules
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
```

@Simn this seems to have broken after your rework of how args are handled between the frontend and the server: #10629

**Comment by Simn** [comment]
Interesting! I didn't account for duplicate `--connect`. It's a bit of a special case because it's supposed to send all subsequent arguments elsewhere.

**Comment by Simn** [comment]
I have fixed this, but I don't know how to add a test for this right now because we usually abstracts away all the `--connect` business.

**Comment by tobil4sk** [comment]
My issue has been solved now, thanks!

**Comment by Simn** [comment]
Oh well, in this case we can live without a test, I'm sure someone will quickly notice if we ever break this again for some reason.

**Comment by tobil4sk** [comment]
Well, it was quite hard to figure out this was the root cause of my issue, but yes hopefully now that the path of issues has been laid out from the vscode lime extension repository it should be fairly easy for someone to figure out. 😄
