### ISSUE TITLE
Question: Is it possible to detect DVDs inside haxe?

### ISSUE THREAD

**Issue by MemeHoovy** [HaxeFoundation/haxe#10818]
I'm helping a friend with their first haxelib https://github.com/Joalor64GH/hxDVD
and I wonder if it's possible to detect DVDs inserted into a DVD tray, or anything like that.

I also didn't know where else to ask this either btw.

Note: I'm somewhat a good Haxe coder but not a good C++ coder, but I'm still willing to try C++ though.

**Comment by Simn** [comment]
Please refer to community.haxe.org for questions like this.
