### ISSUE TITLE
[eval] No error when running a method on a null object

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10825]
On eval, this code runs without an error: https://try.haxe.org/#7f837093
```haxe
class A {
  public function new() {}
  public function run() {
    trace("running");
  }
}

class Main {
  static function main() {
    final a:A = null;
    a.run();
  }
}
```

Output:
```
Main.hx:4: running
```
On other targets (js, hashlink, neko) there is a null access error.

This only succeeds because the `run()` method doesn't actually access any member variables, and if it did, then there would be an null error when trying to access those variables, but still no error for the actual method access.

**Comment by Simn** [comment]
That's probably because the optimized call becomes `A.run(null)` since we know at compile-time that there's no dynamic dispatch. It's a bit unfortunate that this quite special case would suggest that we cannot employ this optimization...

But I thought HL would do something like this as well. Does it also not fail if you make that run method `final`?

**Comment by Apprentice-Alchemist** [comment]
Hashlink inserts an explicit nullcheck before calling `A.run`
```
	fun@221(DDh) ():void
	; Main.hx:10 (Main.main)
		r0 A
		r1 void
		.10    @0 null 0
		.11    @1 nullcheck 0
		.11    @2 call 1, A.run(0)
		.12    @3 ret 1
```

**Comment by tobil4sk** [comment]
> Does it also not fail if you make that run method final?

Yes, it still doesn't fail.

> It's a bit unfortunate that this quite special case would suggest that we cannot employ this optimization...

It is indeed a very rare case... I only discovered this by mistake because I thought something similar was happening on another target, but it wasn't in the end. It is a pain though... as are many things without null safety. 😅
