### ISSUE TITLE
Resolving multiple classes (Request)

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/haxe#10839]
This is just a request but it would be good to have resolving multiple classes.
For instance:
```haxe
static function resolveClasses(path:String):Array<Class<Dynamic>>;
```
It can be a function like this and something like:
```haxe 
Type.resolveClass("sys.io");
``` 
would return ```[File, Process...]``` etc.
If `@:privateAccess` is not used, it would ignore private classes.

**Comment by Simn** [comment]
While I can see this being useful in a few cases, the potential benefit would not warrant the effort for a feature like this. What problem are you trying to solve?

**Comment by ghost** [comment]
> While I can see this being useful in a few cases, the potential benefit would not warrant the effort for a feature like this. What problem are you trying to solve?

Well I need this for hscript parsing, I managed to make some import stuff but there is no star support yet because it is technically impossible to get multiple classes from a package path.
