### ISSUE TITLE
[PHP] Array access and Dynamic type

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10834]
Hej,

This code produces that on PHP target :
```haxe
var a : Dynamic = [];
a[ 0 ];
trace( a ); // [ null ]
```

**Comment by filt3rek** [comment]
This remember me : https://github.com/HaxeFoundation/haxe/issues/10140

**Comment by kLabz** [comment]
Yep, you can expect the same answer here x)

**Comment by filt3rek** [comment]
It comes from here : https://github.com/HaxeFoundation/hscript/pull/121#issuecomment-1294764856 :rofl:
