### ISSUE TITLE
`raise` is reserved in Python3

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#10843]
Not caught or aliased. Same for `print` in python2

**Comment by Simn** [comment]
How are you using it?

**Comment by 0b1kn00b** [comment]
Nothing I can't change easily, looking for a sensible replacement for `throw` to use.

**Comment by Simn** [comment]
Any reproducible example?

**Comment by 0b1kn00b** [comment]
I'm not trying to deceive you, it's a statement.

https://docs.python.org/3/tutorial/errors.html

```haxe
public function raise (){}

...
raise()
```

**Comment by Simn** [comment]
I was just asking because I saw it in the list of keywords in the generator, so I wondered if this required some special circumstance. Turns out there was just an extra space.

**Comment by 0b1kn00b** [comment]
I didn't know quite the circumstances then. I should have an easier way to get you bug reports quite soon.
