### ISSUE TITLE
I have a suggest

### ISSUE THREAD

**Issue by khuonghoanghuy** [HaxeFoundation/haxe#10840]
Haxe, can you build a version for zorin os version?

**Comment by Simn** [comment]
Thank you for the suggestion, but we currently do not plan to provide any additional builds.

**Comment by khuonghoanghuy** [comment]
So haxe, can you make support internet for any haxe game?

**Comment by tobil4sk** [comment]
@khuonghoanghuy I think the install process on Zorin OS should be the same as on Ubuntu, no? It is Ubuntu-based.

**Comment by khuonghoanghuy** [comment]
So here are the list:
- Zorin OS have a install system like Ubuntu
- Zorin OS it more simple than Ubuntu

That was i think about Zorin OS and ubuntu

But the system-based is differrent
