### ISSUE TITLE
Register custom metadata to completion provider

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#10844]
I'm not sure how much of an issue this would be to implement, but I think it would be a nice quality of life improvement to be able to register custom defined metadata to the provider.

![image](https://user-images.githubusercontent.com/748557/200642727-493b06ae-f24c-427b-9923-cebe6712b0a6.png)

`@` or `@:` would be allowed, an API for this could be `haxe.macro.Completion.registerMeta('property', 'description')` something "simple"

**Comment by Simn** [comment]
IMO this should be handled in some declarative way. We already have `src-json/meta.json`, so a user-defined extension of that in the same format which is picked up by the compiler seems sensible.

**Comment by kLabz** [comment]
So each lib would provide their own meta.json which compiler would "merge" with its own meta.json?

**Comment by Simn** [comment]
Yes, and we can do the same with defines (although I forget where these show outside of `--help-defines`). I think the only question is how to tell the compiler where to look for these things. I thought we could just check the class paths, but I don't really want to mix JSON files with HX files...

**Comment by kLabz** [comment]
Maybe something similar to extraParams resolution (though it would only work for libs and not user code...), but that would probably require to translate it to some init macro call registering the file (which could be used directly for user code?)

**Comment by Jarrio** [comment]
a user definable meta.json would be a nice solution! something like a .hxml param `-metafile path/to/metas.json`

**Comment by Aurel300** [comment]
Small comment on this: keep in mind that the JSON files for metadata and defines are used during the compile time *of the Haxe compiler*. We can of course try to bring a similar mechanism to the Haxe compiler runtime.

**Comment by Simn** [comment]
Yes this would require moving some things around, but that should be doable even in OCaml.
