### ISSUE TITLE
final variables raise inconsistent errors for overloaded assignment ops

### ISSUE THREAD

**Issue by saharan** [HaxeFoundation/haxe#10845]
```haxe
abstract MyInt(Int) from Int to Int {
	@:op(A += B)
	public inline function addEq(x:Int):MyInt {
		return this += x;
	}

	@:op(A++)
	public inline function increment():MyInt {
		return this++;
	}
}

class MyClass {
	final field:MyInt = 1;

	function func():Void {
		final local:MyInt = 1;
		
		// --- overriden operators ---
		
		field++; // Error: The field or identifier field is not accessible for writing
		local++;
		
		field += 1;
		local += 1; // Error: Cannot assign to final
		
		// --- raw operators ---
		
		field--; // Error: The field or identifier field is not accessible for writing
		local--; // Error: Cannot assign to final
		
		field -= 1; // Error: Cannot access field or identifier field for writing
		local -= 1; // Error: Cannot assign to final
		
		// --- method calls ---
		
		field.addEq(1);
		local.addEq(1);
		
		field.increment();
		local.increment();
	}
}
```

I think they should be able to be modified through overridden assignment operators only if the underlying type is not a primitive type (basic types + `String`), since `final` only ensures the value of the pointer to an object is immutable for non-primitive types.

**Comment by Simn** [comment]
Shouldn't all of these fail regardless of the type?

**Comment by saharan** [comment]
I don't think so, as long as the `final` attribute of an object doesn't mean that the object is immutable.
Consider the case that someone wants to write something like `list.append(a)` by `list <<= a` or `list += a`. I think this should be allowed reagardless of the object is `final` or not, because the object itself is mutable anyway.

**Comment by saharan** [comment]
Obviously just an assignment `a = b` should not be allowed to final variables in any case, but Haxe doesn't allow overloading the `=` operator so it's no problem.

**Comment by Simn** [comment]
It should fail for all cases where `this` is modified in the abstract, which we can detect after inlining.

**Comment by saharan** [comment]
Ah yes, modifying `this` directly should not be allowed. I agree to that.

**Comment by saharan** [comment]
I was thinking about something like changing variables inside `this`, so here's my opinion:
- overloaded assignment operators should be available to `final` and non-`final` varlables.
- modifying `this` diretly in any kind of function of an abstract should be disallowed for `final` variables.

**Comment by Simn** [comment]
Yes, that's what I was trying to say.

**Comment by Simn** [comment]
All of these error in some way now. I'm not closing yet because I think that `field++;` and such should actually _not_ error if the related function does not modify `this`.
