### ISSUE TITLE
Foo((o)->); is ok for Haxe compiler

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10852]
Hej,

I think this is not normal, right ?

```haxe
enum E {
	Foo(?f:Dynamic->Bool);
}
class Test {
	static function main() {
		var e	= Foo((o)->);	// it's ok
		trace(e);				// Foo(null)
	}
}
```

**Comment by filt3rek** [comment]
This also works : 
```haxe
class Test {
    static function main() {
        foo((o) ->);
    }
    static function foo(?f:Dynamic->Bool) {}
}
```

**Comment by Simn** [comment]
This took me a bit to understand: The call to `expr` raised a `Stream.Failure` here, not a `Stream.Error`. That failure was then picked up by the `psep` handler in `parse_call_params`, which simply caused it to omit the entire expression. By using `secure_expr`, we fail harder and don't recover via the always accepting `psep`.
