### ISSUE TITLE
Object literal is allowed in place of function body

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/haxe#10857]
This is a valid function returning Void:
```haxe
function main() {
  a: "test",
  b: "test"
}
```

I guess it could have something to do with this:
```haxe
function main() {}
```

**Comment by Simn** [comment]
This is consistent, Haxe doesn't require blocks for function bodies and admits any expression, and a block is an expression. Diagnostics will warn you about this code having no effect, which is sufficient here.

**Comment by tobil4sk** [comment]
Ohh! That's interesting! 😅 I guess it's not much different from this:
```haxe
function other()
    return 10;
```
Well, I guess it could come in useful for some weird macro usecase...
