### ISSUE TITLE
Structure matching through abstract

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10856]
Hej,
I don't know if it's a bug, but here `@:forward` is mandatory, if not we get : `Null<AField<{ ?tos : Null<Array<String>>, ?subject : Null<String> }>> has no field subject`
```haxe
//@:forward // Needed
abstract AField<T>(T) from T to T{}

class Test {
  static function main() {
    foo({ subject : "Hello", tos : [] });
  }
  
  static function foo( ?email : AField<{ ?subject : String, ?tos : Array<String> }> ){
    switch email {
			case null	: 
      case { subject : "Hello", tos : _ }	:	// Null<AField<{ ?tos : Null<Array<String>>, ?subject : Null<String> }>> has no field subject
    }
  }
}
```

**Comment by Simn** [comment]
To me that looks exactly like what `@:forward` should do, so unless I'm missing something I don't think there's any bugs here.

**Comment by kLabz** [comment]
I think @filt3rek expected the switch to somehow know that the `to T` should be used before matching. But uh yeah I don't think I agree that it should do it implicitly, since it's a switch on `AField<T>`, not `T`.
