### ISSUE TITLE
Missing `return` ignored after short-circuited `throw`

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#10865]
```haxe
class Main {
  public static function main():Void trace(foo());
  public static function foo():Int {
    true || throw 0;
    0;
  }
}
```

`foo` should return an integer but it does not: the `trace` outputs `null` (on Eval). If I remove the `true || throw 0` line, the error "Missing return: Int" is triggered as expected. I can also use `false && throw 0`. I wonder if this is related to #10791 (or a similar analysis).

**Comment by Simn** [comment]
Nice find!
