### ISSUE TITLE
Missing errors for class failing to implement interface variable

### ISSUE THREAD

**Issue by PHanehoj** [HaxeFoundation/haxe#10875]
The following code runs, even when it shouldn't. 

// Test.hx
```
import A;
class Test{
    static function main() {
        var b : B = new B();
    }
}

class B extends A
{
    public function new() {}
}
```
// A.hx
```
abstract class A implements I {}

interface I
{
    public var s : String;
}
```

Despite B implementing `I` but not providing a field `s`, this code still appears to compile and run for me. I'm using VScode 1.72.2 and Haxe 4.2.4. 

The missing error is only left out as long as:
- There is an abstract class which implements the interface (whether or not `B` also explicitly implements the interface doesn't matter)
- The abstract class and interface are written in a separate file(s)
- The missing thing is a variable/property. Missing functions are detected.

**Comment by Simn** [comment]
This fails with `Field s needed by I is missing` on the `A` class, so I assume that this has been fixed. You can confirm by grabbing a development build from https://build.haxe.org/.
