### ISSUE TITLE
Field null cannot be accessed for reading

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10880]
King of absurd code ? Here I am :rofl: 
```haxe
class Test {
  static function main() {
    trace(null());    // Field null cannot be accessed for reading
  }
}
```
Idk if it's a good error message even if noone will never write something sophisticated like this :rofl:

**Comment by Simn** [comment]
I'll change it to `Field null cannot be accessed for reading, filt3rek`.
