### ISSUE TITLE
How to build Haxe from source on Windows

### ISSUE THREAD

**Issue by Timmmm** [HaxeFoundation/haxe#10898]
I followed the instructions in [`BUILDING.md`](https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md) up to this point:

```
opam pin add haxe path/to/haxe --kind=path --no-action
```

Unfortunately it does not work:

```
Tim@colossus /cygdrive/d/workspace/haxe
$ opam pin add haxe `pwd` --kind=path --no-action
[ERROR] Error getting source from file://D:/cygdrive/d/workspace/haxe:
          - D:/cygdrive/d/workspace/haxe
```

I tried the `--debug` option which seems to suggest it tries to rsync some stuff?

```
$ opam pin --debug add haxe `pwd` --kind=path --no-action
00:00.013  GSTATE                 LOAD-GLOBAL-STATE @ C:/OCaml64/home/Tim/.opam
00:00.015  RSTATE                 LOAD-REPOSITORY-STATE @ C:/OCaml64/home/Tim/.opam
00:00.097  RSTATE                 Loaded C:/OCaml64/home/Tim/.opam/repo/state.cache in 0.081s
00:00.390  RSTATE                 Cache found
00:00.390  STATE                  LOAD-SWITCH-STATE @ 4.14.0+mingw64c
00:00.468  STATE                  Detected changed packages (marked for reinstall): {}
00:00.470  STATE                  Switch state loaded in 0.080s
00:00.472  FILE(switch-state)     Wrote C:/OCaml64/home/Tim/.opam/4.14.0+mingw64c/.opam-switch/backup/state-2022122214
0007.export in 0.002s
00:00.472  COMMAND                pin haxe to  file://D:/cygdrive/d/workspace/haxe
00:00.567  UPDATE                 updating file://D:/cygdrive/d/workspace/haxe
00:00.568  RSYNC                  rsync: src=D:/cygdrive/d/workspace/haxe dst=C:/OCaml64/home/Tim/.opam/4.14.0+mingw64
c/.opam-switch/sources/haxe
Processing: [haxe.4.1.1: rsync]
[ERROR] Error getting source from file://D:/cygdrive/d/workspace/haxe:
          - D:/cygdrive/d/workspace/haxe

00:00.799  SYSTEM                 rm C:/OCaml64/home/Tim/.opam/4.14.0+mingw64c/.opam-switch/backup/state-2022122214000
7.export
```

I suspect the issue is Cygwin nonsense:

```
$ rsync D:/cygdrive/d/workspace/haxe C:/OCaml64/home/Tim/.opam/4.14.0+mingw64
The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1426) [Receiver=3.2.7]
```

It's a *huge* pain that you have to use Cygwin for this. Looks like it is mostly O'Caml's fault not yours though.

**Comment by Timmmm** [comment]
Ok I found that you can't use use the full path. You have to `cd /path/to/haxe` and then `pin .` instead of `pin /path/to/haxe`. Quality stuff.

I hit another problem but I'll make a new issue. I am also writing better instructions so hopefully nobody else has to fight this.

**Comment by Simn** [comment]
Feel free to follow up on other problems you encounter in this issue, so that it's all in one place. And thank you for writing better instructions, that's greatly appreciated!

**Comment by Timmmm** [comment]
👍 Ran into #10802 but that was fairly easily fixed.

Next issue is:

```
#=== ERROR while compiling conf-perl-ipc-system-simple.3 ======================#
# context     2.0.10 | win32/x86_64 | ocaml-variants.4.12.1+mingw64 | git+https://github.com/fdopen/opam-repository-mi
ngw.git#opam2
# path        ~/.opam/4.12.1+mingw64/.opam-switch/build/conf-perl-ipc-system-simple.3
# command     C:\OCaml64\bin\perl.exe -MIPC::System::Simple -e 1
# exit-code   2
# env-file    ~/.opam/log/conf-perl-ipc-system-simple-11396-f35e91.env
# output-file ~/.opam/log/conf-perl-ipc-system-simple-11396-f35e91.out
### output ###
# Can't locate IPC/System/Simple.pm in @INC (you may need to install the IPC::System::Simple module) (@INC contains: /
usr/local/lib/perl5/site_perl/5.32/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.32 /usr/lib/perl5/vendor_p
erl/5.32/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.32 /usr/lib/perl5/5.32/x86_64-cygwin-threads /usr/share/
perl5/5.32).
# BEGIN failed--compilation aborted.


#=== ERROR while compiling conf-mbedtls.1 =====================================#
# context     2.0.10 | win32/x86_64 | ocaml-variants.4.12.1+mingw64 | git+https://github.com/fdopen/opam-repository-mi
ngw.git#opam2
# path        ~/.opam/4.12.1+mingw64/.opam-switch/build/conf-mbedtls.1
# command     dash.exe -ec  cc -I/usr/local/include test.c
# exit-code   127
# env-file    ~/.opam/log/conf-mbedtls-11396-ea46c1.env
# output-file ~/.opam/log/conf-mbedtls-11396-ea46c1.out
### output ###
# dash: 1: cc: not found
```

**Comment by kLabz** [comment]
> 👍 Ran into #10802 but that was fairly easily fixed.
> 
> Next issue is:
> 
> ```
> #=== ERROR while compiling conf-perl-ipc-system-simple.3 ======================#
> # context     2.0.10 | win32/x86_64 | ocaml-variants.4.12.1+mingw64 | git+https://github.com/fdopen/opam-repository-mi
> ngw.git#opam2
> # path        ~/.opam/4.12.1+mingw64/.opam-switch/build/conf-perl-ipc-system-simple.3
> # command     C:\OCaml64\bin\perl.exe -MIPC::System::Simple -e 1
> # exit-code   2
> # env-file    ~/.opam/log/conf-perl-ipc-system-simple-11396-f35e91.env
> # output-file ~/.opam/log/conf-perl-ipc-system-simple-11396-f35e91.out
> ### output ###
> # Can't locate IPC/System/Simple.pm in @INC (you may need to install the IPC::System::Simple module) (@INC contains: /
> usr/local/lib/perl5/site_perl/5.32/x86_64-cygwin-threads /usr/local/share/perl5/site_perl/5.32 /usr/lib/perl5/vendor_p
> erl/5.32/x86_64-cygwin-threads /usr/share/perl5/vendor_perl/5.32 /usr/lib/perl5/5.32/x86_64-cygwin-threads /usr/share/
> perl5/5.32).
> # BEGIN failed--compilation aborted.
> 
> 
> #=== ERROR while compiling conf-mbedtls.1 =====================================#
> # context     2.0.10 | win32/x86_64 | ocaml-variants.4.12.1+mingw64 | git+https://github.com/fdopen/opam-repository-mi
> ngw.git#opam2
> # path        ~/.opam/4.12.1+mingw64/.opam-switch/build/conf-mbedtls.1
> # command     dash.exe -ec  cc -I/usr/local/include test.c
> # exit-code   127
> # env-file    ~/.opam/log/conf-mbedtls-11396-ea46c1.env
> # output-file ~/.opam/log/conf-mbedtls-11396-ea46c1.out
> ### output ###
> # dash: 1: cc: not found
> ```

That's an error I've been getting too while trying to migrate our windows CI to something more optimized, I'll be interested if you find a solution I can apply there

**Comment by Timmmm** [comment]
Ok I've made some progress. I'll put my instructions so far at the bottom of this message. A lot of the steps seem to be missing for Linux/Mac too so I don't know how anyone is compiling this? Anyway here's what I've got:

1. I fixed the `Can't locate IPC/System/Simple.pm` error by installing some Perl modules. I basically took this from Github CI but you have to do this:

```
# Install the Perl package manager.
curl -L https://cpanmin.us | perl - App::cpanminus

# Install some Perl modules.
cpanm IPC::System::Simple
cpanm String::ShellQuote
```

2. I "fixed" the `cc: not found` error by symlinking:

```
cd /usr/bin
ln -s x86_64-w64-mingw32-gcc.exe cc.exe
```

Unfortunately you have to do this because Opam does not respect `CC` and there's no flag to tell it the C compiler. The only option is auto-detection. There's an old bug in the Opam Github about this somewhere if you Google it.

3. You also need to install the `mbedtls-devel` Cygwin package.

Unfortunately `conf-mbedtls` still won't compile because it assumes `mbedtls` is at `/usr/local/include/mbedtls` while it's actually at `/usr/include/mbedtls`. More symlinking to the rescue!

```
cd /usr/include/local
ln -s /usr/include/mbedtls mbedtls
```

4. The *maximum* OCaml version supported is 4.07 (otherwise you get actual OCaml compile errors) so you have to:

```
opam switch create 4.07.1+mingw64
```

4. You also need to `opam install luv`.

With all that I get stuck on this error:

```
$ make -j4 -f Makefile.win
dune.exe build --workspace dune-workspace.dev src-prebuild/prebuild.exe
_build/default/src-prebuild/prebuild.exe libparams -cclib -lpcre -cclib -lz -cclib -lcrypt32 -cclib -lmbedtls -cclib -lmbedcrypto -cclib -lmbedx509 > lib.sexp
_build/default/src-prebuild/prebuild.exe version "0" "development" "991df8cf3" > src/compiler/version.ml
dune.exe build --workspace dune-workspace.dev src/haxe.exe
File "src/context/common.ml", line 1264, characters 21-135:
Error: This expression has type Type.tclass = TType.tclass
       but an expression was expected of type 'a option
make: *** [Makefile:77: haxe] Error 1
```

It's this line:

```
			| _ -> Option.get (ExtList.List.find_map (fun t -> match t with TClassDecl c when c.cl_path = path -> Some c | _ -> None) m.m_types)
```

Ok I don't know OCaml yet but I tried changing it to this:

```
			| _ -> None (*Option.get (ExtList.List.find_map (fun t -> match t with TClassDecl c when c.cl_path = path -> Some c | _ -> None) m.m_types) *)
```

Unfortunately then you get the opposite error!!

```
$ make -j4 -f Makefile.win
dune.exe build --workspace dune-workspace.dev src-prebuild/prebuild.exe
_build/default/src-prebuild/prebuild.exe libparams -cclib -lpcre -cclib -lz -cclib -lcrypt32 -cclib -lmbedtls -cclib -lmbedcrypto -cclib -lmbedx509 > lib.sexp
_build/default/src-prebuild/prebuild.exe version "0" "development" "991df8cf3" > src/compiler/version.ml
dune.exe build --workspace dune-workspace.dev src/haxe.exe
File "src/context/common.ml", line 1264, characters 10-14:
Error: This expression has type 'a option
       but an expression was expected of type Type.tclass = TType.tclass
make: *** [Makefile:77: haxe] Error 1
```

No idea what is going on there.

-----

(Note I haven't added the symlinking to these instructions yet and they don't fully work.)

0. Download the source code using Git:

```
git clone --recursive https://github.com/HaxeFoundation/haxe.git
```

1. Install the [Cygwin/MinGW-based OPAM environment provided by fdopen](https://fdopen.github.io/opam-repository-mingw/installation/). Use the graphical 64-bit installer.

6. The OCaml64 installed installs a Cygwin environment at `C:\OCaml64` but it does not have all the packages we need. To add them download and run the Cygwin [setup-x86_64.exe](https://cygwin.com/install.html). It should automatically know to update `C:\OCaml64`. Change the `View: Pending` drop-down to `Full` to allow you to see all the packages. Install the following (double-click on `Skip` to install them; some might already be installed).

  * `make`
  * `git`
  * `zlib-devel`
  * `rsync`
  * `patch`
  * `diffutils`
  * `curl`
  * `unzip`
  * `tar`
  * `m4`
  * `perl`
  * `mbedtls-devel`
  * `libpcre-devel`
  * `mingw64-x86_64-gcc-core`
  * `mingw64-x86_64-zlib`
  * `mingw64-x86_64-pcre`

7. Copy `zlib1.dll` and `libpcre-1.dll` from `C:\OCaml64\usr\x86_64-w64-mingw32\sys-root\mingw\bin` to the checked out Haxe source directory.

8. Install Neko by either
  * Download the [Neko binaries](https://nekovm.org/download/), and add the extracted directory to the beginning of PATH.
  * Install the [Chocolatey Neko package](https://chocolatey.org/packages/neko).

4. Start the `Cygwin64 Terminal` from the Start Menu and run the following commands.

```sh
# Install the Perl package manager.
curl -L https://cpanmin.us | perl - App::cpanminus

# Install some Perl modules.
cpanm IPC::System::Simple
cpanm String::ShellQuote

# Switch to the haxe repo directory. This is how C: directories are mapped.
cd /cygdrive/c/path/to/haxe

# Select older OCaml (Haxe doesn't support later versions yet).
opam switch create 4.07.1+mingw64

# Pin Haxe to the repo directory.
opam pin add haxe . --kind=path --no-action

# Install OCaml dependencies.
# You may get an error about conf-mbedtls. You can ignore this.
opam install haxe --deps-only

# Install libuv wrapper.
opam install luv

# Compile Haxe
make -f Makefile.win -j8
```

Add the checked out Haxe source directory to the beginning of `PATH`.

**Comment by kLabz** [comment]
Alternative for 2 would be "fixing" https://github.com/fdopen/opam-repository-mingw/blob/opam2/packages/conf-mbedtls/conf-mbedtls.1/opam#L8 I guess

Depext should be able to handle the perl dependencies for you, it did on windows CI for me.

**Comment by Simn** [comment]
See #10086 for that OCaml error.

**Comment by kLabz** [comment]
Seems strange that that error would hit with a new env though :thinking:

**Comment by Simn** [comment]
That confuses me too, also because the line number is still the current one...

**Comment by Timmmm** [comment]
> See #10086 for that OCaml error.

Ah thanks, this fixed it:

```
opam update
opam upgrade extlib
```

I don't understand why I needed to do that though given that in the `opam` file it says `  "extlib" {>= "1.7.8"}`. `opam list` said I had version 1.7.7-1 installed.

Anyway after upgrading it I get all the way to linking! Unfortunately (and somewhat predictably) I get a link error:

```
$ make -j4 -f Makefile.win
dune.exe build --workspace dune-workspace.dev src-prebuild/prebuild.exe
_build/default/src-prebuild/prebuild.exe libparams -cclib -lpcre -cclib -lz -cclib -lcrypt32 -cclib -lmbedtls -cclib -lmbedcrypto -cclib -lmbedx509 > lib.sexp
_build/default/src-prebuild/prebuild.exe version "0" "development" "53f07576e" > src/compiler/version.ml
dune.exe build --workspace dune-workspace.dev src/haxe.exe
File "src/dune", line 26, characters 7-11:
26 |    (name haxe)
            ^^^^
** Fatal error: Cannot find file "-lmbedtls"
File "caml_startup", line 1:
Error: Error during linking
make: *** [Makefile:77: haxe] Error 1
```

I was expecting this, since I only symlinked the mbedtls headers from `/usr` to `/usr/local`. However even if I `cp /usr/lib/*mbed* /usr/local/lib/` I still get the same error. I also tried adding `NATIVE_LIBS += -I "/usr/lib"` to `Makefile.win` but it didn't work either (and I can't see where `NATIVE_LIBS` is used anyway).

> Alternative for 2 would be "fixing" https://github.com/fdopen/opam-repository-mingw/blob/opam2/packages/conf-mbedtls/conf-mbedtls.1/opam#L8 I guess

I'm not sure it is quite that simple - I initially tried ignoring the `conf-mbedtls` error since it looks to me like a "check mbedtls is available" dependency. However the Haxe build *also* assumes that mbedtls is in `/usr/local` not `/usr`, so you get build errors. Any idea where this `/usr/local` discrepancy is actually coming from?

> Depext should be able to handle the perl dependencies for you, it did on windows CI for me.

Ah cool, I don't suppose you could spell out the commands for me?

**Comment by Simn** [comment]
Check out https://github.com/Simn/mingw64-mbedtls for the mbedtls problem. I thought this was mentioned in the build instructions but apparently it isn't...

**Comment by kLabz** [comment]
```
opam depext haxe
```

But it would likely choke on that config-mbedtls `cc` issue, or at least it did for me

> Check out https://github.com/Simn/mingw64-mbedtls for the mbedtls problem. I thought this was mentioned in the build instructions but apparently it isn't...

Ah yeah, indeed. I use CI config as build instructions so it wasn't missing for me :laughing:

**Comment by kLabz** [comment]
> Check out https://github.com/Simn/mingw64-mbedtls for the mbedtls problem. I thought this was mentioned in the build instructions but apparently it isn't...

Ah yeah, indeed. I use CI config as build instructions so it wasn't missing for me :laughing:

**Comment by Timmmm** [comment]
Ah wait I think the pinning might not have worked (maybe I need to re-pin after `opam switch` or something?) because this `opam` looks more consistent with the behaviour I'm seeing: https://github.com/fdopen/opam-repository-mingw/blob/81667392e45a32a52c59e9cd361ef6c23bd59c9a/packages/haxe/haxe.4.1.1/opam

It depends on `conf-mbedtls` and the one in the repo doesn't, and it also depends on the old version of `extlib`.

**Comment by Timmmm** [comment]
> Check out https://github.com/Simn/mingw64-mbedtls for the mbedtls problem. I thought this was mentioned in the build instructions but apparently it isn't...

Ah yeah I saw that in CI but I couldn't see any explanation for it anywhere so I figured I'd try the official package. Do you know why the official one doesn't work?

**Comment by Simn** [comment]
When I made this one there was no official package for mingw64, and from the errors you're getting it sounds like there still isn't one. Note that the cygwin packages that start with mingw64 are essentially a different platform, namely the "native" Windows one.

**Comment by Timmmm** [comment]
Ah right, you mean if I link against the Cygwin mbedtls it's going to mean Haxe only runs in Cygwin? Whereas if I link with mingw64-mbedtls it will run as a normal Windows program?

Cygwin is such a mess. :/

**Comment by Simn** [comment]
> Ah right, you mean if I link against the Cygwin mbedtls it's going to mean Haxe only runs in Cygwin? Whereas if I link with mingw64-mbedtls it will run as a normal Windows program?

If you can even link in the first place... In my experience, `ln` is rarely the answer for problems like this, it's usually some dependency issue.

> Cygwin is such a mess. :/

Agreed!

**Comment by Timmmm** [comment]
Ah I see so we're basically using Cygwin as an environment to cross-compile to normal Windows. I wonder if it would be any easier to use WSL? Probably doesn't work in CI I guess.

Anyway I uninstalled Cygwin and tried again. Actually I didn't really uninstall it since [uninstalling is about as convenient as you would expect anything in Cygwin to be](https://cygwin.com/faq/faq.html#faq.setup.uninstall-all) so I just deleted `C:\OCaml64`.

> `opam depext haxe`

This actually did run without errors for me. Even without the `cc` symlink. However I still got the same Perl errors later so I guess it didn't really work.

Here's what I did this time:

-------

0. Download the source code using Git:

```
git clone --recursive https://github.com/HaxeFoundation/haxe.git
```

1. Install the [Cygwin/MinGW-based OPAM environment provided by fdopen](https://fdopen.github.io/opam-repository-mingw/installation/). Use the graphical 64-bit installer.

2. The OCaml64 installed installs a Cygwin environment at `C:\OCaml64` but it does not have all the packages we need. To add them download and run the Cygwin [setup-x86_64.exe](https://cygwin.com/install.html). It should automatically know to update `C:\OCaml64`. Change the `View: Pending` drop-down to `Full` to allow you to see all the packages. Install the following (double-click on `Skip` to install them).

  * `zlib-devel`
  * `libpcre-devel`
  * `mingw64-x86_64-zlib`
  * `mingw64-x86_64-pcre`

3. Install Neko by either
  * Download the [Neko binaries](https://nekovm.org/download/), and add the extracted directory to the beginning of PATH.
  * Install the [Chocolatey Neko package](https://chocolatey.org/packages/neko).

4. Start `OCaml64` from the Start Menu and run the following commands.

```sh
# Switch to the haxe repo directory. This is how C: directories are mapped.
cd /cygdrive/c/path/to/haxe

# Download and extract mbedtls to the Cygwin system.
curl.exe -fsSL -o "libmbedtls.tar.xz" --retry 3 https://github.com/Simn/mingw64-mbedtls/releases/download/2.16.3/mingw64-x86_64-mbedtls-2.16.3-1.tar.xz
tar -C / -xvf libmbedtls.tar.xz
rm libmbedtls.tar.xz

# Install the Perl package manager.
curl -L https://cpanmin.us | perl - App::cpanminus

# Install some Perl modules.
cpanm IPC::System::Simple
cpanm String::ShellQuote

# Select older OCaml (Haxe doesn't support later versions yet).
opam switch create 4.07.1+mingw64

# Pin Haxe to the repo directory. Otherwise when you run the following commands
# it will think you are talking about the version of Haxe in opam itself.
opam pin add haxe . --kind=path --no-action

# Install OCaml dependencies.
# You may get an error about conf-mbedtls. You can ignore this.
opam install haxe --deps-only

# Copy DLLs needed.
cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/*.dll .

# Compile Haxe
make -f Makefile.win -j8
```
----

It seems to have successfully compiled and run `haxe.exe` but then I get further errors in Haxe code:

```
$ make -f Makefile.win -j8
dune.exe build --workspace dune-workspace.dev src-prebuild/prebuild.exe
_build/default/src-prebuild/prebuild.exe libparams -cclib -lpcre -cclib -lz -cclib -lcrypt32 -cclib -lmbedtls -cclib -lmbedcrypto -cclib -lmbedx509 > lib.sexp
_build/default/src-prebuild/prebuild.exe version "0" "development" "53f07576e" > src/compiler/version.ml
dune.exe build --workspace dune-workspace.dev src/haxe.exe
cp -f _build/default/src/haxe.exe ./"haxe.exe"
(cd /cygdrive/d/workspace/haxe/extra/haxelib_src && /cygdrive/d/workspace/haxe/haxe.exe client.hxml && nekotools boot run.n)
src/haxelib/api/Connection.hx:9: characters 8-36 : Type not found : haxe.remoting.HttpConnection
Type not found : haxe.remoting.Connection
src/haxelib/api/Connection.hx:56: characters 16-84 : haxelib.api._Connection.SiteProxy does not have a constructor
src/haxelib/api/Connection.hx:521: characters 26-37 : haxelib.api._Connection.SiteProxy has no field postInstall
src/haxelib/api/Connection.hx:521: characters 26-37 : haxelib.api._Connection.SiteProxy has no field postInstall
src/haxelib/api/Connection.hx:198: characters 4-40 : Type not found : haxe.remoting.HttpConnection
src/haxelib/api/Connection.hx:200: characters 4-40 : Type not found : haxe.remoting.HttpConnection
src/haxelib/api/Connection.hx:352: characters 40-45 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:352: characters 40-45 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:353: characters 24-36 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
src/haxelib/api/Connection.hx:367: characters 33-38 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:367: characters 33-38 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:369: characters 88-100 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
src/haxelib/api/Connection.hx:540: characters 26-40 : haxelib.api._Connection.SiteProxy has no field checkDeveloper
src/haxelib/api/Connection.hx:540: characters 26-40 : haxelib.api._Connection.SiteProxy has no field checkDeveloper
src/haxelib/api/Connection.hx:543: characters 26-37 : haxelib.api._Connection.SiteProxy has no field getSubmitId
src/haxelib/api/Connection.hx:543: characters 26-37 : haxelib.api._Connection.SiteProxy has no field getSubmitId
src/haxelib/api/Connection.hx:445: characters 22-44 : Type not found : HttpConnection
src/haxelib/api/Connection.hx:447: characters 4-26 : Type not found : HttpConnection
src/haxelib/api/Connection.hx:546: characters 26-39 : haxelib.api._Connection.SiteProxy has no field processSubmit
src/haxelib/api/Connection.hx:546: characters 26-39 : haxelib.api._Connection.SiteProxy has no field processSubmit
src/haxelib/api/Connection.hx:453: characters 3-25 : Type not found : HttpConnection
src/haxelib/api/Connection.hx:509: characters 26-42 : haxelib.api._Connection.SiteProxy has no field getLatestVersion
src/haxelib/api/Connection.hx:509: characters 26-42 : haxelib.api._Connection.SiteProxy has no field getLatestVersion
src/haxelib/api/Connection.hx:513: characters 26-31 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:513: characters 26-31 : haxelib.api._Connection.SiteProxy has no field infos
src/haxelib/api/Connection.hx:517: characters 26-32 : haxelib.api._Connection.SiteProxy has no field search
src/haxelib/api/Connection.hx:517: characters 26-32 : haxelib.api._Connection.SiteProxy has no field search
src/haxelib/api/Connection.hx:525: characters 26-30 : haxelib.api._Connection.SiteProxy has no field user
src/haxelib/api/Connection.hx:525: characters 26-30 : haxelib.api._Connection.SiteProxy has no field user
src/haxelib/api/Connection.hx:529: characters 26-34 : haxelib.api._Connection.SiteProxy has no field register
src/haxelib/api/Connection.hx:529: characters 26-34 : haxelib.api._Connection.SiteProxy has no field register
src/haxelib/api/Connection.hx:533: characters 26-35 : haxelib.api._Connection.SiteProxy has no field isNewUser
src/haxelib/api/Connection.hx:533: characters 26-35 : haxelib.api._Connection.SiteProxy has no field isNewUser
src/haxelib/api/Connection.hx:537: characters 26-39 : haxelib.api._Connection.SiteProxy has no field checkPassword
src/haxelib/api/Connection.hx:537: characters 26-39 : haxelib.api._Connection.SiteProxy has no field checkPassword
src/haxelib/client/Main.hx:315: characters 13-14 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
src/haxelib/client/Main.hx:346: characters 13-25 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
make: *** [Makefile:105: haxelib] Error 1
```

Any ideas about that?

**Comment by Timmmm** [comment]
Ah I found the answer in #430. Well almost! You suggested `git submodule init && git submodule update` which I had already done. Turns out that is not enough to do it recursively... you'd think `git submodule update --recursive` would do it, but nooooo. You have to

```
git submodule update --init --recursive
```

Classic git.

Anyway, with that `make` succeeds! 🎉 🚀 

I haven't tried actually running it yet but hopefully it will be fine! I'll update the `BUILDING.md` if I get a chance, but in case I don't the instructions I posted in https://github.com/HaxeFoundation/haxe/issues/10898#issuecomment-1364024165 do the trick.

Happy Christmas everyone :-)

**Comment by Timmmm** [comment]
Also if you want to develop with VSCode you can get OCaml support by:

1. Run `opam install merlin ocp-indent ocaml-lsp-server` in the OCaml terminal.
2. Create a shortcut with the target `C:\OCaml64\usr\local\bin\ocaml-env-win.exe -- "C:\Users\Tim\AppData\Local\Programs\Microsoft VS Code\Code.exe"`.
3. Run the shortcut and open the Haxe repo. When it askes you to select a sandbox choose the 4.07.1+mingw64 one. You can also do this on the OCaml sidebar pane.

Thanks to https://gist.github.com/Darkle/b6fd75d8ed46a535567a6541849c075b

**Comment by Simn** [comment]
I'll go ahead and close this because I don't think there's an actual issue here, other than cygwin stuff itself being an issue.
