### ISSUE TITLE
Comparable type constraint

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10895]
```haxe
function indexOfMax<T>(arr:Array<T>):Int {
	if (arr.length == 0) return -1;
	var max = arr[0];
	var maxIndex = 0;
	for (i in 1...arr.length) {
		if (arr[i] > max) { // Error: Cannot compare indexOfMax.T and indexOfMax.T
			maxIndex = i;
			max = arr[i];
		}
	}
	return maxIndex;
}
```
You can use `T:Float` to allow ints and floats, but this does not include strings and custom abstracts.
Maybe such errors can also be improved to suggest basic type constraints.

**Comment by Simn** [comment]
This is (not) working as intended. Unless you constrain the type parameter to something, the compiler won't know what to generate from this. If you want some kind of generic "comparable" constraint, you'll have to provide some design for this in a feature request.

**Comment by RblSb** [comment]
On second thought, there is no much use cases to compare numbers or strings in methods, and with abstracts @:ops its much more complicated feature. There is also workarounds, so i will skip it.
