### ISSUE TITLE
Error makes me unable to use flixel

### ISSUE THREAD

**Issue by Minalog** [HaxeFoundation/haxe#10907]
Can someone help me fix this error? `flixel` is installed but doesn't want to work. This is detrimental to my game.
![Error](https://user-images.githubusercontent.com/119029150/209763978-1b2764d7-61f6-49e0-a135-3256987cf6b1.PNG)

**Comment by marcelEuchnerMartinez** [comment]
Hi there :)
[Flixel has its own github site](https://github.com/HaxeFlixel/flixel/issues) (just fyi, to get help quicker) and also, if you like, you can ask someone on our [haxe discord channel](https://discordapp.com/invite/0uEuWH3spjck73Lo) (then under "game frameworks"/#flixel).
Or maybe its Lime related? ([link for Lime issues](https://github.com/openfl/lime/issues))
I'm not a Flixel user but it will surely help to have some more information about your OS and other
information that might be important or helpful.
Hope your  game will work again! 👍
