### ISSUE TITLE
Build fails with "You cannot access the flash package while in a macro (for flash.display.BitmapData)"

### ISSUE THREAD

**Issue by endergreen12** [HaxeFoundation/haxe#10910]
I'm sorry if my English is not correct because I'm using a translation.
Also, I am not very knowledgeable at all about Haxe, etc., so I am sorry if I have said something strange.

I tried to compile a game for Android using flixel. However, when I tried to build it, it stopped with an error like the following picture:

![image](https://user-images.githubusercontent.com/90076182/209841070-1123aa62-d3c1-45ed-8603-187c45c11870.png)

I tried all the information I could find on the internet and it did not work at all.

How can I resolve this error?

Thank you.

**Comment by nomnomnomlol** [comment]
how did u fix?

**Comment by endergreen12** [comment]
> how did u fix?

See this, maybe it still works

https://github.com/MAJigsaws-Storage/FNF-Mobile-Porting/issues/30#issuecomment-1367104286
