### ISSUE TITLE
[neko] sys.FileSystem.exists returns false, but file exists.

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#10928]
The following code returns `false` for neko 2.3.0 but `true` for all other sys targets on Windows 10 and Haxe 4.2.5

```haxe
sys.FileSystem.exists("C:\\Windows\\System32\\OpenSSH\\ssh.exe");
```

The file exists:
![image](https://user-images.githubusercontent.com/426959/212570849-a2270b0c-6d6f-4f0b-b8f3-064b0ab5d15a.png)

**Comment by ianharrigan** [comment]
Id also add that i get quite different results:

```
hl: true
neko: true
hxcpp: false
hxnodejs: true
```

**Comment by Aurel300** [comment]
Is it specific to this file? Does it make a difference if you pass a relative path? Also backslashes vs forward slashes?

**Comment by sebthom** [comment]
Forward or backward slashes make no difference. In my case Neko reports `false` for all files under C:\Windows\System32 but works fine for files under C:\Windows\

**Comment by kLabz** [comment]
> Forward or backward slashes make no difference. In my case Neko reports `false` for all files under C:\Windows\System32 but works fine for files under C:\Windows\

Could it be because of the "Hide protected operating system files" setting? Not sure how that would affect things outside windows explorer though :thinking:

**Comment by sebthom** [comment]
Hmm, it apparently works with the 64bit version of Neko... I was still using Haxe+Neko 32bit because of some issues I had at one point with the 64bit release.
