### ISSUE TITLE
sys.io.File.getBytes doesn't work properly in C++ with image files.

### ISSUE THREAD

**Issue by furretpaws** [HaxeFoundation/haxe#10922]
Ok so apparently, the File.getBytes() function doesn't work properly in C++.

This code right here should take image bytes from a file, then send it through Discord.
`body += "\n--boundary";
 body += '\nContent-Disposition: form-data; name="files[' + i + ']"; filename="' + getJson.attachments[i].filename + '"';
 body += '\nContent-Type: ' + hxdiscord.util.MimeResolver.getMimeType(getJson.attachments[i].filename);
 body += '\n\n';
 body += sys.io.File.getBytes(getJson.attachments[i].filename.toString()).toString();`
 
 In neko, this works perfectly for some reason. Otherwise, in C++ it doesn't.
 I want to clarify that this doesn't have to do with Discord, the function isn't able to gather the bytes correctly
 
![image](https://user-images.githubusercontent.com/99131021/211150155-9cefccc3-2687-466c-a772-fabb8375bdb6.png)

**Comment by Aurel300** [comment]
(For future reference, don't use `toString` to send binary files. This can lead to malformed data due to string encoding, and I think the default is different between neko and hxcpp.)
