### ISSUE TITLE
Enable keep_inline_positions on debug?

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#10956]
I've always wondered why this flag isnt enabled by default as debugging is incredibly difficult without it. Is there a drawback or any reason why haxe shouldn't automatically enable it on debug?

**Comment by Simn** [comment]
I'm generally hesitant when it comes to flag implications. If you make a flag imply another one, you're going to need yet another flag to un-imply the implied flag.

Also, "debug" is a very broad term and doesn't necessarily mean that you care about inlining positions. So while I understand where you're coming from and acknowledge that this might make sense for you particular use case, I prefer not to make this change.

**Comment by Geokureli** [comment]
Part of me making this request was to learn more about what this flag does, and why it's not enabled to begin with. what are the drawbacks of having this flag enabled? I'm considering enabling this flag on debug by default in the flixel template Project.xml.

This flag isn't even listed in the list of [compiler usage flags](https://haxe.org/manual/compiler-usage-flags.html)
