### ISSUE TITLE
get/setproperty does not work if the setter is inline

### ISSUE THREAD

**Issue by nspitko** [HaxeFoundation/haxe#10957]
A humble try.haxe: https://try.haxe.org/#9695901B

And a repro here in case that's down/dead
```
@:structInit class TestSetter {
	public var x(default, set):Float = 0;
	public var posChanged:Bool = false;

	inline function set_x(v) {
		posChanged = true;
		return x = v;
	}
}

class Test {
	static function main() {
		var test:TestSetter = {};
		test.x = 10;

		trace(test.posChanged);
    
		test.posChanged = false;
    
		Reflect.setProperty(test, "x", 5);
		trace(test.posChanged);
	}
}

```

I realize that this is an *extremely cursed* problem, but it tripped me up in some code I was writing and should probably either work, or provide some kind of indication to the developer that it doesn't/can't work (Though it would need to happen at runtime which adds an annoying wrinkle). The silent failure case here is less than ideal

*Update*:
I've been informed that this is a function of DCE. I'm... torn here frankly. There's a clear solution (add `@:keep`) but... the behavior is hard to understand (The field is being used, so one wouldn't expect it to be DCE related), and feels like it'd be hard for anyone to naturally understand this behavior even having read the documentation.

Perhaps DCE shouldn't remove inline setters if the inlined version is in use? Or should have an option to not remove them (which is the default) with a "No really remove everything" option being opt-in?

Honestly I'm not sure there's a sane answer to this, maybe just a note in the docs on DCE and reflection pointing in both directions on this particular pit?

**Comment by Simn** [comment]
This is working as intended with regards to DCE. The fact that this is about a setter has no relevance, the same thing would happen with normal functions. That also means that I don't see what extra documentation we would add here.
