### ISSUE TITLE
JVM Target Crash (Same code does not crash in Java or other targets)

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/haxe#10965]
Hi,

I'm trying to get a relatively simple math example running in the jam target and I'm getting this:

```shell
Error: Unable to initialize main class haxe.root.Error
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    haxe/root/Error.main()V @52: invokestatic
  Reason:
    Type float (current frame, stack[0]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @52
    flags: { }
    locals: { float, float, float, float, float, float, float, float, float, float }
    stack: { float }
```

And the code is just a matrix inverse:

```haxe
class Error {
	
	static public function main() {
        var m = new Mat3(1, 0, 0, 0, 1, 0, 0, 0, 1);
        var n = m.inverse();
        trace(n);
	}
}
```

I've included the code in case it's helpful. Again it works for hash link and java targets.

[Code.zip](https://github.com/HaxeFoundation/haxe/files/10719441/Code.zip)

**Comment by onehundredfeet** [comment]
I've reduced the inverse down to just this and can still repro the same crash:

```haxe
    static public function inverse(_this : Mat3): Mat3 {
		var m:Mat3Data = _this;
        var a = m.c2.z;
        var b = 2.;
        var c = -a * b; // this fails? why? can not assign a float to an object?

        return new Mat3(c, 0.0, 0.0, c, 0.0, 0.0, c, 0.0, 0.0);
	}

```

**Comment by Simn** [comment]
```haxe
class Main {
	static public function main() {
		var a:Single = 0;
		var c = -a;
	}
}
```

Looks like it's just the minus Single. I guess I didn't pay much attention to singles.

**Comment by onehundredfeet** [comment]
well, that was a much simpler issue than I was expecting.

**Comment by Simn** [comment]
Yeah single-precision floats aren't used a whole lot. Out of curiosity, why are you using them for a math library?

**Comment by onehundredfeet** [comment]
Because it's styled after shader math, it's intended to support different precisions for speed purposes.  It supports both singles and doubles.

The irony is that I've been doing some benchmarks, and on my apple m1, the doubles are faster than singles.


I'm not sure the same is true of x86 though.

**Comment by onehundredfeet** [comment]
Thanks for fixing this so quickly Simon!!!
