### ISSUE TITLE
Feature Request : Automatic cast on if-is (like C#) 'Decorated Patterns'

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/haxe#10964]
Hi folks,

This may already be possible with some of the language features, but if not, I would love to see a very handy language feature brought over from C# that I think fits reasonably in haxe.  They call them 'Decorated Type Patterns'.

if ( OBJECT is TYPE variable) {
  // Variable is defined within the scope 
}

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast

They also use them in switch statements:

switch (Objects) {
   case Type variable:
// variable is defined in the scope.
}

If this is already possible, maybe with switch statements, sorry for the noise.

**Comment by Simn** [comment]
This would require a haxe-evolution proposal. I'm personally not a huge fan of this because it promotes bad coding, but I acknowledge that it can be useful when interacting with some API.
