### ISSUE TITLE
Java / JVM generates haxe.root.Array<java.lang.Object> for an Array<Single>

### ISSUE THREAD

**Issue by onehundredfeet** [HaxeFoundation/haxe#10967]
Is this intended functionality?

```haxe
    @:java.native public function fn_nativeArrayF(array : NativeArray<Single> ) : Void;
    @:java.native public function fn_ArrayF(array : Array<Single> ): Void;
```
turns into

```java
public native void fn_nativeArrayF(float[] array);	
public native void fn_ArrayF(haxe.root.Array<java.lang.Object> array);
```

It seems that the haxe.root.Array is capable of doing haxe.root.Array\<float\>, which would likely be much more performant.

**Comment by Simn** [comment]
I don't think `Generic<primitive>` is a thing in Java or the JVM...

**Comment by onehundredfeet** [comment]
Yeah, my mistake.

After a bit of reading, it seems there's a proposal to add universal generics to OpenJDK, but that won't be for some time if approved.

https://openjdk.org/jeps/8261529

Would it be possible to translate them to a custom class for the basic primitives?

Ie clone the array class for each basic primitive and substitute it in the translation?

**Comment by Simn** [comment]
In theory that might be possible, but you'd have to show me some very convincing benchmarks demonstrating the advantage of such an approach.

**Comment by onehundredfeet** [comment]
Roger, makes sense.

**Comment by onehundredfeet** [comment]
Ok, so, I just want to make sure there isn't a better approach.

```c++

JNIEXPORT void JNICALL Java_sample_SampleNative_fn_1nativeArrayF
  (JNIEnv *env, jobject obj, jfloatArray array) {
    //access
    float* raw = env->GetFloatArrayElements(array, nullptr);
    // Do all my processing
    ...
    //release
    env->ReleaseFloatArrayElements(array, raw, 0);
  }

JNIEXPORT void JNICALL Java_sample_SampleNative_fn_1ArrayF
  (JNIEnv *env, jobject obj, jobject array) {
    //preamble - could be cached
    	jclass haxe_array_class = p->FindClass("haxe/root/Array");
      jmethod array_get = p->GetMethodID(haxe_array_class, "__get", "(I)Ljava/lang/Object;");
      jclass float_class = p->FindClass("java/lang/Float");
      jmethod float_get = p->GetMethodID(float_class, "floatValue", "()F");

      // get length
      ...
      ///
      float *temp = new float[length];
      for (auto i = 0; i < length; ++i) {
        jobject tmpObj = (*env)->CallObjectMethod(array, array_get, i);
        temp[i] = (*env)->CallFloatMethod(tmpObj, float_get );
      }

      // do all my processing
      ...
     // release
     delete [] temp;
  }


  ```
  
  Is there a better approach than this?

btw  - Please don't feel any pressure to answer this quickly.  I can work around this.

**Comment by Simn** [comment]
I'm not very familiar with JNI stuff, but yeah, doing something like this might be necessary. 

I'll go ahead and close as there is not really an issue here.
