### ISSUE TITLE
Invalid_argument("index out of bounds")

### ISSUE THREAD

**Issue by rainyt** [HaxeFoundation/haxe#10975]
Fatal error: exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "src/macro/eval/evalMisc.ml", line 65, characters 52-65
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "ptmap.ml", line 164, characters 36-52
Called from file "src/macro/eval/evalMisc.ml", line 65, characters 15-102
Called from file "src/macro/eval/evalStdLib.ml", line 1963, characters 7-57
Called from file "src/macro/eval/evalEmitter.ml", line 254, characters 8-19
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 754, characters 13-21
Called from file "list.ml", line 88, characters 20-23
Called from file "src/macro/eval/evalEmitter.ml", line 319, characters 10-36
Called from file "src/macro/eval/evalEmitter.ml", line 255, characters 8-19
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 754, characters 13-21
Called from file "list.ml", line 88, characters 20-23
Called from file "list.ml", line 88, characters 32-39
Called from file "list.ml", line 88, characters 32-39
Called from file "src/macro/eval/evalEmitter.ml", line 300, characters 10-36
Called from file "src/macro/eval/evalEmitter.ml", line 254, characters 8-19
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 183, characters 35-48
Called from file "src/macro/eval/evalEmitter.ml", line 191, characters 6-48
Called from file "src/macro/eval/evalEmitter.ml", line 754, characters 13-21
Called from file "src/macro/eval/evalEmitter.ml", line 83, characters 23-31
Called from file "src/macro/eval/evalEmitter.ml", line 253, characters 8-19
Called from file "src/macro/eval/evalEmitter.ml", line 747, characters 9-17
Called from file "src/macro/eval/evalEmitter.ml", line 83, characters 23-31
Called from file "src/macro/eval/evalEmitter.ml", line 265, characters 8-19
Called from file "src/macro/eval/evalEmitter.ml", line 249, characters 7-18
Called from file "src/macro/eval/evalEmitter.ml", line 747, characters 9-17
Called from file "src/macro/eval/evalMain.ml", line 180, characters 11-40
Called from file "src/macro/eval/evalExceptions.ml", line 99, characters 5-8
Called from file "src/macro/eval/evalExceptions.ml", line 114, characters 10-38
Re-raised at file "src/macro/eval/evalExceptions.ml", line 167, characters 2-11
Called from file "src/typing/macroContext.ml", line 589, characters 10-84
Called from file "src/typing/macroContext.ml", line 729, characters 8-23
Called from file "src/typing/callUnification.ml", line 479, characters 10-60
Called from file "src/typing/typeloadFields.ml", line 680, characters 9-47
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 828, characters 12-73
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 502, characters 22-35
Called from file "src/typing/fields.ml", line 533, characters 9-36
Called from file "src/typing/typer.ml", line 1539, characters 9-118
Called from file "src/typing/typer.ml", line 1560, characters 10-54
Called from file "src/typing/typer.ml", line 609, characters 13-51
Called from file "list.ml", line 88, characters 20-23
Called from file "src/typing/typer.ml", line 600, characters 10-803
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typer.ml", line 1449, characters 10-56
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typer.ml", line 1449, characters 10-56
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/matcher.ml", line 595, characters 12-37
Called from file "src/typing/matcher.ml", line 1632, characters 27-77
Called from file "list.ml", line 88, characters 20-23
Called from file "list.ml", line 88, characters 32-39
Called from file "src/typing/matcher.ml", line 1630, characters 14-228
Called from file "src/typing/typer.ml", line 1739, characters 10-69
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typer.ml", line 1449, characters 10-56
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/matcher.ml", line 595, characters 12-37
Called from file "src/typing/matcher.ml", line 1632, characters 27-77
Called from file "list.ml", line 88, characters 20-23
Called from file "list.ml", line 88, characters 32-39
Called from file "src/typing/matcher.ml", line 1630, characters 14-228
Called from file "src/typing/typer.ml", line 1739, characters 10-69
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typer.ml", line 1449, characters 10-56
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typer.ml", line 1224, characters 9-84
Called from file "src/typing/callUnification.ml", line 92, characters 11-58
Called from file "src/typing/callUnification.ml", line 85, characters 3-7
Called from file "src/typing/callUnification.ml", line 195, characters 12-33
Called from file "src/typing/callUnification.ml", line 196, characters 9-21
Called from file "src/typing/callUnification.ml", line 218, characters 14-26
Re-raised at file "src/typing/callUnification.ml", line 218, characters 50-59
Called from file "src/typing/callUnification.ml", line 334, characters 5-74
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/typer.ml", line 1636, characters 13-50
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/callUnification.ml", line 329, characters 8-16
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/typer.ml", line 929, characters 13-57
Called from file "src/typing/typer.ml", line 1009, characters 12-48
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/callUnification.ml", line 518, characters 3-6
Re-raised at file "src/typing/callUnification.ml", line 522, characters 3-12
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typer.ml", line 1019, characters 10-56
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tFunctions.ml", line 463, characters 9-22
Called from file "src/typing/typer.ml", line 1593, characters 9-23
Called from file "src/typing/callUnification.ml", line 92, characters 11-58
Called from file "src/typing/callUnification.ml", line 85, characters 3-7
Called from file "src/typing/callUnification.ml", line 195, characters 12-33
Called from file "src/typing/callUnification.ml", line 218, characters 14-26
Re-raised at file "src/typing/callUnification.ml", line 218, characters 50-59
Called from file "src/typing/callUnification.ml", line 334, characters 5-74
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/core/tUnification.ml", line 502, characters 33-46
Called from file "src/core/tUnification.ml", line 601, characters 2-18
Called from file "src/context/abstractCast.ml", line 54, characters 4-44
Called from file "src/context/abstractCast.ml", line 100, characters 2-39
Called from file "src/typing/callUnification.ml", line 85, characters 3-7
Called from file "src/typing/callUnification.ml", line 195, characters 12-33
Called from file "src/typing/callUnification.ml", line 196, characters 9-21
Called from file "src/typing/callUnification.ml", line 218, characters 14-26
Re-raised at file "src/typing/callUnification.ml", line 218, characters 50-59
Called from file "src/typing/callUnification.ml", line 334, characters 5-74
Called from file "src/typing/callUnification.ml", line 408, characters 26-49
Called from file "src/typing/callUnification.ml", line 464, characters 12-62
Called from file "src/typing/typer.ml", line 749, characters 27-94
Called from file "src/typing/typer.ml", line 752, characters 9-19
Called from file "src/typing/typer.ml", line 1681, characters 10-38
Called from file "src/typing/typeloadFunction.ml", line 78, characters 2-25
Called from file "std.ml", line 26, characters 6-9
Re-raised at file "std.ml", line 28, characters 23-30
Called from file "src/typing/typeloadFields.ml", line 924, characters 13-88
Called from file "src/typing/typeloadFields.ml", line 948, characters 36-42
Called from file "src/context/typecore.ml", line 411, characters 11-14
Called from file "src/typing/typeloadFields.ml", line 1727, characters 51-64
Called from file "src/context/typecore.ml", line 397, characters 3-6
Called from file "src/typing/finalization.ml", line 83, characters 1-30
Called from file "src/compiler/haxe.ml", line 513, characters 1-301
Called from file "src/compiler/haxe.ml", line 1073, characters 3-39
Called from file "src/compiler/haxe.ml", line 642, characters 3-11
Called from file "src/compiler/haxe.ml", line 1247, characters 1-35

By Haxe4.2.5

**Comment by Aurel300** [comment]
Can you provide a minimal example that causes this error?

**Comment by rainyt** [comment]
> Can you provide a minimal example that causes this error?

Emmm, I think it's very difficult. I don't know why it happened, and it happened in my project.

**Comment by Aurel300** [comment]
Given the line reported, maybe it might be related to setting an object field (via `Dynamic`?) that doesn't exist? Anyway I'm not sure there is much to do without an example.

**Comment by rainyt** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/9693090/220098053-898ddbc2-6602-45cd-af83-2ea4b69695d1.png">
I can't reproduce it separately in other projects, but its problem is here. An error occurred in Json.parse.

**Comment by rainyt** [comment]
Is this possibly related to GC?

**Comment by Aurel300** [comment]
Does the error always happen in your project? Is it always the same JSON input that triggers it? Can you possibly share the JSON file if so?

A GC problem is unlikely: that would indicate an issue in OCaml's garbage collector.

**Comment by rainyt** [comment]
> Does the error always happen in your project?

Yes.

> Is it always the same JSON input that triggers it? Can you possibly share the JSON file if so?

But if I compile it separately, there is no error.

**Comment by rainyt** [comment]
Update to Haxe 4.3.0 Fixed it.

**Comment by kLabz** [comment]
Welcome to 2023 :tada:
