### ISSUE TITLE
Unsupported platform for haxe@5.2.1 for M1 Ventura

### ISSUE THREAD

**Issue by Beraliv** [HaxeFoundation/haxe#10989]
**What**

In private project there's a dependency that has `haxe`. When I run:

```bash
npm i
```

I see the following error:

```bash
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for haxe@5.2.1: wanted {"os":"win32,win64,darwin,linux","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    win32,win64,darwin,linux
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexey.berezin/.npm/_logs/2023-03-01T12_33_41_606Z-debug.log
```

My colleagues with the same setup don't have this error (at least 2 people)

**Reproduction**

I've created a small project where I see the same behaviour – https://github.com/Beraliv/haxe-example

Let me know if I need to share any additional information

**Comment by Beraliv** [comment]
Let me know if I've created an issue by mistake in here. I've created another one against `npm-haxe` https://github.com/HaxeFoundation/npm-haxe/issues/36

**Comment by RblSb** [comment]
This is installation tool problem, so i think you can close this.
If you want support for haxe macos-arm binaries, there is separate issue https://github.com/HaxeFoundation/haxe/issues/10190 (we will probably wait to end of this year for github arm runners)
If you want to install native haxe build, i can recommend you to use brew, or build haxe from sources.
