### ISSUE TITLE
[jvm] Overload+any change on haxe.ds.Vector breaks compilation server

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#10986]
Other targets seems fine, but if you change anything (even comments) in this project `Vector` file after first compilation and rebuild, there will be errors like:
```
haxe/ds/IntMap.hx:350: lines 350-352 : Field iterator has different type than in core type
haxe/ds/IntMap.hx:350: lines 350-352 : error: Iterator<haxe.ds.IntMap.T> should be haxe.root.Iterator<haxe.ds.IntMap.T>
haxe/ds/IntMap.hx:350: lines 350-352 : ... have: (...) -> Iterator<...>
haxe/ds/IntMap.hx:350: lines 350-352 : ... want: (...) -> haxe.root.Iterator<...>
```
If you change something like `std.StringTools`, it also breaks cache.
[bug_vector_jvm_server.zip](https://github.com/HaxeFoundation/haxe/files/10853506/bug_vector_jvm_server.zip)

Found on https://github.com/HaxeFoundation/haxe/pull/10687

**Comment by Simn** [comment]
I can reproduce this, unfortunately...

**Comment by Simn** [comment]
This does not reproduce with `--no-output`, which means this must be about something the actual generation process does. That also explains why it only fails for this specific target.

My first guess is that we have some monomorphs in the cache which end up being bound by something the generator does. Cached monos are really bad...
