### ISSUE TITLE
[eval/lua] Reflect.hasField on function reference throws exception

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#10993]
The following code works on all targets except interp/eval and lua.
```haxe
class Test {
  static function foo() {
  }
  static function main() {
    trace(Reflect.hasField(foo, "bar")); // should print `false`
  }
}
```

Eval: `Uncaught exception Unexpected value VFunction(#fun), expected object`
Lua: `attempt to index upvalue 'o' (a function value)`

**Comment by Simn** [comment]
This is kind of covered by the "This is only guaranteed to work for anonymous structures." line in its documentation, but if you look into lua then I'm happy to also fix eval and make this consistent.

**Comment by sebthom** [comment]
I submitted PR https://github.com/HaxeFoundation/haxe/pull/10994
It also includes a test case. The test is currently disabled for eval (until you had the chance to fix eval).

**Comment by sebthom** [comment]
@Simn thanks!
