### ISSUE TITLE
String should be Dynamic when using Dynamic<Dynamic>

### ISSUE THREAD

**Issue by gene-pavlovsky** [HaxeFoundation/haxe#11007]
The following code fails to compile on 4.2.5 or today's nightly (c21431d):

```
import js.lib.Date as JsDate;

class Test {
  static function main() {
    final now = JsDate.fromHaxeDate(Date.now());
    trace(now.toLocaleString("en", { month: "short", day: "numeric" }));
  }
}
```

Errors:
```
src/Test.hx:6: characters 11-71 : Overload resolution failed for (?locales : Null<String>, ?options : Null<Dynamic<Dynamic>>) -> String
src/Test.hx:6: characters 36-70 : error: String should be Dynamic
src/Test.hx:6: characters 36-70 : ... have: { day: String }
src/Test.hx:6: characters 36-70 : ... want: { day: Dynamic }
src/Test.hx:6: characters 36-70 : ... For optional function argument 'options'
```

`String should be Dynamic` is the most hilarious typing error I've seen in my years of Haxing.

Workaround:
Use `cast { month: "short", day: "numeric" }`

**Comment by Simn** [comment]
In the general case, this is a variance problem:

```haxe
class Main {
	static function main() {
		var obj = {day: "numeric"};
		var a:Dynamic<Dynamic> = cast obj;
		a.day = 12;
		$type(obj.day); // String
		trace(obj.day); // 12
	}
}
```

However, declaring the object directly against `Dynamic<Dynamic>` could be supported via top-down inference.

**Comment by gene-pavlovsky** [comment]
Well I will leave the technical details to you. As a user of the js target, what I would like to do is to be able to use the standard JS APIs in a straightforward way, without having to add `cast` or other typing stuff. E.g. if the js.lib.Date functions were declared with the `options` param as `Dynamic` instead of `Dynamic<Dynamic>`, stuff would work correctly without any tricks. Of course, it would be possible to pass something unsuitable (Int, String, whatever) as the `options` argument.

**Comment by Simn** [comment]
There's already a mechanism in place which is supposed to handle the `Dynamic<T>` case. However, the compiler confuses itself because `Dynamic<Dynamic>` is "kind of but not really" the same as plain `Dynamic`.

I guess this is a good opportunity to clean this up somehow.
