### ISSUE TITLE
@:this descrepancy from Haxe 4.1.4 to 4.2.x (only via getter) / Macro functions must be called immediately

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#11004]
I've boiled down a previously reported issue (#10025) to a simple reproduction testcase.

In the attached testcase, a class Foo has a `_bar_private:Bar` member and a `bar` getter. The Bar class has a macro member function that needs to generate code with the `@:this` identifier. A helper computes this identifier by reading the source code at the `this_expr.pos` (perhaps there is a better way of doing this? I made this up quite a while ago.)

In Haxe 4.1.4, the output of the compilation step is:

```
src/Bar.hx:27: @:this this computed this_ident as: foo.bar in Haxe 4.1.4
src/Bar.hx:27: @:this this computed this_ident as: foo._bar_private in Haxe 4.1.4
```

Those are both valid ways to access `foo._bar_private` at runtime (and at after-macro-time).

In Haxe 4.2.x, the output is:

```
src/Bar.hx:27: @:this this computed this_ident as: foo.bar.macro_func in Haxe 4.2.3
src/Bar.hx:27: @:this this computed this_ident as: foo._bar_private in Haxe 4.2.3
src/Main.hx:6: characters 5-25 : Macro functions must be called immediately
src/Main.hx:6: characters 5-25 : Invalid macro access
```

Note the extra `.macro_func` -- the `@:this` identifier, only when accessed through the getter, is being returned by position as `foo.bar.macro_func` -- including the function name, hence the invalid macro access errors.

**Workaround:** macro_func detects its own name suffix, and removes it.

---

Testcase: [issue_11004.zip](https://github.com/HaxeFoundation/haxe/files/10903808/issue_11004.zip)

**Comment by Simn** [comment]
The important detail here is that this is about positions because you use these to determine the source expression.

It looks like the pushed this-expression has a too wide range that includes the entire nadako-field-chain.

**Comment by jcward** [comment]
Thank you @Simn! I'll buy you a beer if you tell me where to send the donation. :)
