### ISSUE TITLE
Lexical package alias

### ISSUE THREAD

**Issue by hydroper** [HaxeFoundation/haxe#11015]
Is there a way to alias a package, basically lexically?

```haxe
import com.rialight.temporal.* in Temporal;

new Temporal.ZonedDateTime(...);
```

**Comment by hydroper** [comment]
Looks like I've to post that to https://github.com/haxefoundation/haxe-evolution

**Comment by PXshadow** [comment]
@hydroper I'm very interested in this feature to allow shorter calling of module functions/vars and types as well. It would improve the ability to write large code bases using only modules, let me know when you have an evolution proposal I'd love to take a look.

**Comment by hydroper** [comment]
@PXshadow [Here is a proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/105)
