### ISSUE TITLE
Can't build on MacOS by following BUILDING.md instructions (libraries not found)

### ISSUE THREAD

**Issue by kuremu** [HaxeFoundation/haxe#11012]
I think Homebrew's /opt/homebrew prefix is causing trouble with the build system. Despite installing pcre, zlib and mbedtls via homebrew, I get the following errors during build:

```
File "libs/pcre/dune", line 7, characters 9-19:
7 |             (names pcre_stubs))
             ^^^^^^^^^^
pcre_stubs.c:55:10: fatal error: 'pcre.h' file not found
#include "pcre.h"
         ^~~~~~~~
1 error generated.
File "libs/mbedtls/dune", line 7, characters 9-22:
7 |             (names mbedtls_stubs))
             ^^^^^^^^^^^^^
mbedtls_stubs.c:23:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

The first error went away when I symlinked pcre.h into libs/pcre/ but I could not do the same with mbedtls for whatever reason.

**Comment by kuremu** [comment]
OK I have managed to get it building using [this hint from pixelsyntax](https://github.com/HaxeFoundation/haxe/issues/8873).

The dune file needs to be modified to add homebrew's include directory. It also needs an explicit link to the mbedtls@2 include directory, because the default mbedtls provided by homebrew doesn't include a number of files that are required by the build process.

So changing the dune file from `(data_only_dirs extra lib std tests)` to

```
(env
        (release
                (ocamlopt_flags (:standard -ccopt -L/opt/homebrew/lib))
                (c_flags ("-I/opt/homebrew/opt/mbedtls@2/include" "-I/opt/homebrew/include"))
        )
)
(data_only_dirs extra lib std tests)
```

did the job for me.

**Comment by Simn** [comment]
I think this is no longer a problem, feel free to comment if I'm wrong about that!

**Comment by tristan-k** [comment]
This is still a [issue](https://github.com/Aorimn/dislocker/issues/321#issuecomment-2324914902) for me.

**Comment by kLabz** [comment]
> This is still a [issue](https://github.com/Aorimn/dislocker/issues/321#issuecomment-2324914902) for me.

How is that related to Haxe?

**Comment by tristan-k** [comment]
> > This is still a [issue](https://github.com/Aorimn/dislocker/issues/321#issuecomment-2324914902) for me.
> 
> How is that related to Haxe?

Sorry, wrong github project. I switched up my tabs.
