### ISSUE TITLE
[java] java.lang.IncompatibleClassChangeError: Method must be InterfaceMethodref constant

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11023]
I am generating a JAR file using `--jvm` and passing it to a target application (Minecraft's Fabric loader) to be executed. When I do so, I get this error:

```
java.lang.IncompatibleClassChangeError: Method 'java.lang.Object net.minecraft.class_2378.method_10230(net.minecraft.class_2378, net.minecraft.class_2960, java.lang.Object)' must be InterfaceMethodref constant
	at com.elitemastereric.obsidianarmor.items.ModItems.onInitialize(./src/com/elitemastereric/obsidianarmor/items/ModItems.hx:64)
	at com.elitemastereric.obsidianarmor.ObsidianArmorMod.onInitialize(./src/com/elitemastereric/obsidianarmor/ObsidianArmorMod.hx:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
```

I do not have a deep enough knowledge of Java to know what this exception is referring to specifically, but I see references to `InterfaceMethodref` among the `ml` files for JVM.

My current theory is that this issue is caused by attempting to load a JAR built with JDK 8 into an application built with JDK 16, resulting in differences in how classes interpret interfaces. Thus, #11016 may resolve this.

**Comment by Simn** [comment]
I don't really know what to do with this issue because I have no way to reproduce it.

**Comment by EliteMasterEric** [comment]
I am returning to this issue because it is currently my main blocker in migrating my project to the JVM target.

In my use case, I am generating Java JARs for use by a Java module loader added onto Minecraft by the Fabric API. All build tools recommend the use of Java 17 for compilation, and Java 17 is required to play Minecraft.

When I utilize the Java target (which is now unmaintained), I can create a set of Java source which can then be compiled and mapped by the Gradle build tool to create a valid JAR file for use with Minecraft. When I switch to the JVM target and have the Gradle build tool operate on the generated JAR to create a valid JAR, the resulting JAR throws this error:

```
Caused by: java.lang.IncompatibleClassChangeError: Method 'java.lang.Object net.minecraft.class_2378.method_10230(net.minecraft.class_2378, net.minecraft.class_2960, java.lang.Object)' must be InterfaceMethodref constant
	at com.elitemastereric.madeinhaxe.items.ModItems.register(./src/com/elitemastereric/madeinhaxe/items/ModItems.hx:33)
	at com.elitemastereric.madeinhaxe.MadeInHaxeMod.onRegister(./src/com/elitemastereric/madeinhaxe/MadeInHaxeMod.hx:9)
	at net.pickhaxe.core.CommonMod.onInitialize(E:\Programming\Game Modding\Minecraft Modding\PickHaxe\pickhaxe\src\net/pickhaxe/core/CommonMod.hx:193)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
```

Here is the relevant line of code in Haxe.

```haxe
  public static function register():Void {
    MadeInHaxeMod.LOGGER.info("Registering items...");

    var resourceLocation:ResourceLocation = new ResourceLocation(MadeInHaxeMod.MOD_ID, "glyph_haxe");

    HAXE_GLYPH.register(resourceLocation);
  }
```

Using a Java decompilation tool, I can see the resulting Java code as generated by the Java target (valid):

```java
    public static void register() {
        MadeInHaxeMod.LOGGER.info(Runtime.toString("Registering items..."));
        final class_2960 resourceLocation = new class_2960(Runtime.toString(MadeInHaxeMod.MOD_ID), Runtime.toString("glyph_haxe"));
        final class_1792 __temp_expr1 = (class_1792)class_2378.method_10230((class_2378)class_7923.field_41178, resourceLocation, (Object)ModItems.HAXE_GLYPH);
    }
```

And by the JVM target (invalid, causes crash when attempting to load):

```java
    public static void register() {
        MadeInHaxeMod.LOGGER.info("Registering items...");
        final class_2960 resourceLocation = new class_2960(MadeInHaxeMod.MOD_ID, "glyph_haxe");
        class_2378.method_10230((class_2378)class_7923.field_41178, resourceLocation, (java.lang.Object)ModItems.HAXE_GLYPH);
    }
```

My primary (and really only) theory is that the Haxe compiler is generating bytecode which is invalid for my target platform of Java 17, and thus an expert in modern Java bytecode would be required to resolve this issue.

I can provide the generated JAR files (one that is valid and one that exhibits the error when loaded by Minecraft Fabric 1.19.3) below:

[output-jars.zip](https://github.com/HaxeFoundation/haxe/files/12330688/output-jars.zip)

I can also provide a set of instructions on how to generate a new JAR yourself using my Minecraft toolset, if needed. Due to the nature of Minecraft modding, creating a minimal reproduction which does not utilize these tools is not possible (thus why the tools were necessary to develop in the first place).

**Comment by Simn** [comment]
Could you perhaps upload a big .zip with everything needed? I don't mind non-minimal examples if the dependency management isn't such a hassle.

**Comment by EliteMasterEric** [comment]
I have since found a comment that describes the problem we are experiencing here: https://bugs.openjdk.org/browse/JDK-8145148?focusedCommentId=13958798&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13958798

> The JVM has been fixed to check that the constant pool types JVM_CONSTANT_Methodref or JVM_CONSTANT_InterfaceMethodref are consistent with the type of method referenced. These checks are made during method resolution, and are checked for methods that are referenced by JVM_CONSTANT_MethodHandle.

> If consistency checks fail an IncompatibleClassChangeError is thrown.

> javac has never generated inconsistent constant pool entries, but some bytecode generating software may. In many cases, if ASM is embedded in the application, upgrading the the latest version ASM 5.1 resolves the exception. After upgrading ASM, be sure to replace all uses of deprecated functions with calls to the new functions, particularly new functions that pass a boolean whether the method is an interface method: visitMethodInsn and Handle.

**Comment by EliteMasterEric** [comment]
A minimal reproduction has been achieved.

https://github.com/EliteMasterEric/hxjvm-Issue11023

The issue occurs when attempting to execute a static method of an interface when the JVM used to compile and run is a modern version of Java (as opposed to Java 8).

Using `javap` to inspect the generated class, we can see that, in the constant pool, `Util.testStatic` is being referred to as a `Methodref` (0x0A), when it should be an `InstanceMethodref` (0x0A). This, as mentioned above, was not an error in earlier versions of Java, but was never *correct*, and the `IncompatibleClassChangeError` error to mandate these values stay consistent was introduced in Java 9 122.

**Comment by Simn** [comment]
Thanks for the investigation! Please see if this did the trick for you.

**Comment by EliteMasterEric** [comment]
Downloaded the build in the linked commit and the test workbench produces a valid JAR! Will look to test with my other projects soon.

Thank you for your patience and apologies for the inconvenience as I worked through narrowing down the root cause of this bug. It took a lot of work and research from me and my friend to figure out how to diagnose and reproduce the issue. I am now better equipped to provide more detailed information on issues in the future.
