### ISSUE TITLE
[crash bug] Bad URL for HTTP causes uncatchable error

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11031]
Take the following code:

```haxe
var url:String = "https://www.google.com/"; // This works fine
var url:String = "https ://www.google.com/"; // Typo, space in the protocol

    var request:Http = new Http(url);
    request.request(false);
    return request.responseData;
```

The first URL fetches fine, the second URL crashes the application printing `Not_found`. Not even putting a try/catch block around the call prevents this crash.

Tested on Haxe 4.2.5, happens on both Eval and C++ targets

**Comment by Simn** [comment]
I can't reproduce the problem on C++ (and it makes no sense that it would throw `Not_found`), but yeah, I can on eval.

**Comment by Simn** [comment]
Shockingly, the eval debugger worked and pointed me to `Host.resolve`:

```haxe
function main() {
	new sys.net.Host("https ://www.google.com/");
}
```

The stack trace points to a `Unix.gethostbyname`, which is surrounded by `catch_unix_error`. It appears this function doesn't unix error, but throws `Not_found` instead.

**Comment by Simn** [comment]
This now gives:

```
 ERROR  (unknown position)

   | Uncaught exception Could not resolve host https ://www.google.com/

    ->  c:/git/haxe/std/eval/_std/sys/net/Host.hx:31: characters 8-21

    31 |   init(resolve(name));
       |        ^^^^^^^^^^^^^
       | Called from here

    ->  source/Main.hx:2: characters 2-46

     2 |  new sys.net.Host("https ://www.google.com/");
       |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       | Called from here
```

I'm not adding a test because I don't like net stuff in the tests.
