### ISSUE TITLE
haxelib_src submodule

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#11035]
Shouldn't the haxelib_src submodule be updated to the latest haxelib version?

**Comment by Simn** [comment]
I'll let @tobil4sk comment on that, there are some concerns regarding this.

**Comment by tobil4sk** [comment]
The current development version of haxelib is probably not going to end up in Haxe 4.3.0, as that would be Haxelib 5.0.0 and there are still some breaking changes that aren't ready yet. So we'll have to backport the define/meta changes to a new Haxelib 4.1.0 release, and that is probably what Haxe 4.3.0 will ship with.

https://github.com/HaxeFoundation/haxelib/pull/573
