### ISSUE TITLE
[hl] hlopt vs. do-while loops

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11037]
See https://github.com/HaxeFoundation/haxe/pull/7979#issuecomment-1484016037

The failure can be caused by setting `can_do` in `analyzerTexpr.ml` to true.

**Comment by Simn** [comment]
Pinging @yuxiaomao because he's dealing with hlopt at the moment!

**Comment by yuxiaomao** [comment]
My PR https://github.com/HaxeFoundation/haxe/pull/11458 seems solve the issue, at least, the sample given in the thread (not in the expected way though).
I think the real reason behind it is some missing liveness detection in do-while loop, I'll try to see if I can find some proper way to solve this.

**Comment by yuxiaomao** [comment]
@Simn should this issue be closed?

**Comment by Simn** [comment]
Yes thank you!
