### ISSUE TITLE
Strict null safety causes compile error when using Array.slice in Python

### ISSUE THREAD

**Issue by roarosa** [HaxeFoundation/haxe#11044]
I'm getting unexpected compiler errors when calling Array.slice on an array in strict null safety mode.

```
// Test.py
@:nullSafety(Strict)
class Test {
    public static function main() {
        [1,1,1].slice(1);
    }
}
```

Run command:
`haxe --python out.py -m Test`

Error:
`Test.hx:4: characters 9-25 : Null safety: Cannot use nullable value of Null<Int> as an item in Array<Dynamic>`

Notes
* Running Haxe version 4.2.5
* Compiles fine in js and cpp
* Not specific to ints, string array also fails with the same method

**Comment by RblSb** [comment]
This is fixed in dev version

**Comment by roarosa** [comment]
Thanks, will close out then!
