### ISSUE TITLE
#if without condition

### ISSUE THREAD

**Issue by acarioni** [HaxeFoundation/haxe#11047]
Haxe compiler allows a #if block without a condition but should emit an error.

<a href="https://try.haxe.org/#1BE793d2">Try Haxe !</a>

**Comment by kLabz** [comment]
It's being parsed as
```haxe
class Test {
	static function main() {
		#if trace
		("Haxe is great!");
		#end
	}
}
```

**Comment by Simn** [comment]
Yes, this looks silly but is working as intended.

**Comment by acarioni** [comment]
But if the first token is considered as the condition of the #if block, how does the compiler parse a code like this?

```
class Test {
  static function main() {
    var x = 0;
    #if
      x = x + 1;
      trace(x);
    #end
  }
}
```

**Comment by Simn** [comment]
Try `-D x` and you'll see!

**Comment by acarioni** [comment]
My main concern is that if one forgets the condition (as I did recently in a real project), then the compiler doesn't complain but the generated code is wrong (in the sense of violating the principle of least surprise).

Wouldn't it be better if the language required that the condition of an #if block is on the same line of the #if?
