### ISSUE TITLE
[JS] class names = true Math.__name__ = true, Std.__name__ = true...

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11071]
Hej,

I noticed in the trace and output of generated Haxe JS that classes' names are set to `true`...
![image](https://user-images.githubusercontent.com/4986929/229272003-520874ba-81ed-434a-9a46-ecaa9c83c719.png)
When we trace it, it outputs `TClass({ __name__ : true })` it's not very handy
https://try.haxe.org/#a4490A45

**Comment by kLabz** [comment]
Issue here is DCE, somehow turning `{ __name__ : String }` into `{ __name__ : true }`
Happens since ~3.2.1 so no hurry there I guess

**Comment by Frixuu** [comment]
[The names get generated](https://github.com/HaxeFoundation/haxe/blob/719a298662b04160c38f5cf00663f99b9d8212ba/src/generators/genjs.ml#L1294) only if you ever use `Type.getClassName` in your project.  
Try putting `final _ = Type.getClassName(Std);` somewhere if you want to force them to appear.

**Comment by filt3rek** [comment]
Hej,

Be careful, with latests nightly build in try haxe (2023-04-08 21:47:16 (2eb7724)), even with DCE no, it doesn't work : https://try.haxe.org/#8fe00842

**Comment by kLabz** [comment]
Yeah it has not been merged

**Comment by Simn** [comment]
Am I stupid or is this a really stupid "optimization"?

**Comment by kLabz** [comment]
Well yeah we might be missing something but that optimization doesn't seem very useful at first glance..

**Comment by Simn** [comment]
This was originally implemented in https://github.com/HaxeFoundation/haxe/commit/495b718164790904a3d51d152b98e9b9ffd405d0

I understand the check against `isClass`, but the one that uses `true` seems really pointless.
