### ISSUE TITLE
Compiler failure with 4.3.0-rc.1+dd0d6a6

### ISSUE THREAD

**Issue by jobf** [HaxeFoundation/haxe#11086]
I was trying the latest nightly (as of 4th April) and see the following error.

```
Haxe: 4.3.0-rc.1+dd0d6a6; OS type: unix;
File "src/compiler/compiler.ml", line 141, characters 179-186
Called from file "src/compiler/compiler.ml", line 141, characters 172-186
Called from file "src/compiler/compiler.ml", line 294, characters 11-47
Called from file "src/compiler/compiler.ml", line 334, characters 1-5
Called from file "src/compiler/compiler.ml", line 418, characters 2-157
Called from file "src/compiler/compiler.ml", line 395, characters 2-9
Called from file "src/compiler/compiler.ml", line 614, characters 5-43
Called from file "src/compiler/compiler.ml", line 624, characters 13-22
Called from file "src/compiler/server.ml", line 973, characters 1-39
Called from file "src/compiler/haxe.ml", line 53, characters 0-56
File "src/core/globals.ml", line 156, characters 1-7: Assertion failed

```

**Comment by RblSb** [comment]
Can you provide minimized code example?

**Comment by jobf** [comment]
Main.hx
```hx
class Main{
	public static function main(){
		trace("4.3.0-rc.1+dd0d6a6");
	}
}
```

build.hxml
```
-cp .
--main Main
-hl bin/hl/out.hl
```

**Comment by Apprentice-Alchemist** [comment]
It dies here, so it appears you are missing (or the compiler cannot access) the `hl_version` file in `std/hl`. https://github.com/HaxeFoundation/haxe/blob/dd0d6a64e90f3b93b8a1be966184f51bc6d35903/src/compiler/compiler.ml#L141

**Comment by jobf** [comment]
Thank you, it's fixed by specifying HAXE_STD_PATH
```
export HAXE_STD_PATH=/path/to/nightly/std
```

Closing for real now.

**Comment by RblSb** [comment]
I think we should report useful error here instead of playing dead, can be reopened?

**Comment by jobf** [comment]
OK that's a good idea.

**Comment by Simn** [comment]
Could someone ghostwrite the error message for me?

**Comment by Aurel300** [comment]
> The file `hl_version` could not be found in the standard library directory (insert path here). This could happen if you are using an older version of the standard library with a newer version of the compiler. Please make sure `HAXE_STD_PATH` is set to the standard library corresponding to the used compiler version.

?
