### ISSUE TITLE
In eval, calling Sys.args() in macro context does not return compiler args.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#11087]
Given the addition of `Compiler.getConfiguration` I'm not sure there's really much of a point of accessing compiler args, but it still seems to be a weird inconsistency.

**Comment by Simn** [comment]
Mmh... I can see why it _could_ return the args if you consider the compiler invocation the entry point, but from a macro perspective it doesn't seem very obvious to me that it _should_. Unless this actually solves a problem, I'd prefer to not change this.

**Comment by tobil4sk** [comment]
It seems a bit broken that when using `--interp` (or any other target), `Sys.args()` in macros returns the compiler args, but as soon as you change it to `--run` it returns the runtime args. I guess `Sys.args()` could just be left unspecified in macros, but that means there is no way to get the raw compiler arguments in a macro.

Also, currently `Sys.args()` returns the compiler args at runtime when running with `--interp`, which also seems a bit odd. According to the docs, Sys.args() "does not include the interpreter or the name of the program file", so it would make more sense to return an empty array.

**Comment by back2dos** [comment]
> Mmh... I can see why it *could* return the args if you consider the compiler invocation the entry point, but from a macro perspective it doesn't seem very obvious to me that it *should*.

I don't know that it *should*. My point was rather that on every platform (e.g. [js](https://try.haxe.org/#AE0e7B71) or [hl](https://try.haxe.org/#9eB38Edc)), in macro context `Sys.args()` *does* return the compiler args, except on [eval](https://try.haxe.org/#69a0383e). I'm no fan of such inconsistencies. Now if we're saying that `Sys.args()` *should not* be returning compiler args, then sure, ok. But then let's do that, for all targets, no?

**Comment by tobil4sk** [comment]
This is the current situation:

|| Eval (--interp)  |Eval (--run)| Other targets |
|-|-|-|-|
|macro `Sys.args()`|compiler args| runtime args (--run ...) | compiler args |
|runtime `Sys.args()`|compiler args| runtime args (--run ...)| runtime args |

This is what would make more sense:

|| Eval (--interp)  |Eval (--run)| Other targets |
|-|-|-|-|
|macro `Sys.args()`|compiler args| *compiler args* | compiler args |
|runtime `Sys.args()`| *empty array* | runtime args (--run ...)| runtime args |

**Comment by Simn** [comment]
Closed by #11524
