### ISSUE TITLE
Macro static local var not working

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11096]
Hej,

Idk if I've understood well the new local static var feature but in this example it seems not working in macro context : https://try.haxe.org/#bf1DB874
`null` twice whereas with the uncommented line `null` first time, then `5`
````haxe
class Test {
    static function main() {
        Macro.foo(5);
        Macro.foo(2);
    }
}

class Macro {
  //static var i:Int;
    public macro static function foo(_i:Int) {
        static var i:Int;
        trace(i);
        i = _i;
        return macro null;
    }
}
```

**Comment by Simn** [comment]
@kLabz I'll assign all 4.3 Hotfix material to you so that it goes through one person.
