### ISSUE TITLE
Allow reverse iteration for haxe for loops in std

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#11093]
It would be a great quality of life upgrade to have a for loop that can go backwards, syntax would fit right in with the haxe style loop
```hx
for (i in 0...10) {}
for (i in 10...0) {}
```

**Comment by Aurel300** [comment]
This is something for haxe-evolution, but I don't think it's a good suggestion. It looks ok when written with literals as in your example but what does `a...b` do when `a` and `b` are variables? If you are suggesting that we should change the existing behaviour to count down from `a` if `a > b`, then this is a huge breaking change (and imo counterintuitive). Besides, there are some libraries that provide static extensions for integer ranges that allow you to say the step is e.g. `-1`.

**Comment by Jarrio** [comment]
yeah i certainly wasn't suggesting it would be easy, but that it be in the std as a backward for loop is relatively intuitive and common. I'm aware there are library approaches but it isn't necessarily the "right" answer here. 

I guess the issue here is more an issue of syntax rather than feasibility then which does step into proposal land but one way it could be written could be

```hx
for (i in 0 > 10) //0...10
for (i in 10 < 0) //10...0
```
(new syntax wouldn't break old ways)

taking a bit of inspiration from c style loops here, but yeah I did not think about the variable case at all

**Comment by back2dos** [comment]
FWIW this has been [implemented in tink_lang](https://haxetink.github.io/tink_lang/#/implementation-sugar/extended-for-loops?id=arbitrary-steps).

**Comment by Simn** [comment]
See https://github.com/HaxeFoundation/haxe-evolution/issues/104 (which I will probably close too).
