### ISSUE TITLE
[java] "Should extend by using a class" reports with unknown position

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11095]
```
 ERROR  (unknown position)

   | Should extend by using a class
```

This is what the error looks like, when pretty printing.

**Context:**
I am developing a large project which externs to a folder of Java libraries, which vary in version (and therefore what classes and methods they provide) based on the parameters provided to the build tool. The intent is to use conditional compilation to resolve these differences.

At times, I have found that some of the classes I have created externs for are incorrect, and I have to correct them (because they are correct on one version and incorrect on another, for example). The issue is that this is reported with the above quoted message, and NOTHING ELSE, no stack trace to trace the problem with, no name for the class which is struggling to extend or be extended.

My current theory is that the issue is tied to the automatic extern generation provided by Haxe (which can be browsed by using `--dump`). Haxe attempts to generate an extern internally, encounters an error (maybe the extern Haxe creates extends or implements an extern I have created, with a mismatch such as a change in type causing this error), then reports it without being able to point to a file path to (since there is none, the extern is internal).

**Suggested Solution:**

I am hoping that, by either improving the error handling of generated externs internally, or modifying [this particular error message](https://github.com/HaxeFoundation/haxe/blob/50a980e256e2164be0eb1ea7c01789ef051ff08b/src/typing/typeloadCheck.ml#L346) to at least provide the name of the class experiencing the error, I will then be able to track down the root cause and determine the specific mistake that causes this error to occur, and at that point even better error reporting can be devised.

**Comment by kLabz** [comment]
Was it any better with previous versions?
Also, how do we reproduce that position-less error?

**Comment by Simn** [comment]
I've made it print the type kind. Didn't add a test because I don't necessarily want to specify it like this, but I think it's really good to print the full type kind because this can occur from some crazy macro-generated code.

Keeping this issue open to see if the actual position information regressed.

**Comment by EliteMasterEric** [comment]
```
 ERROR  (unknown position)

   | Should extend by using a class, found TAbstract(net.pickhaxe.compat.core.Registry, [TLazy])
```

Thank you very much, this error message is vastly more informative.

It appears that there is an error message because an interface (unknown which one, since no position is provided for it) is attempting to extend another interface (net.minecraft.core.Registry<T>). However, in my code, I had replaced that interface with an abstract of that interface, in an attempt to add new compatibility functions, so the extern interface was attempting to extend an abstract.

I wonder if it would be possible to properly handle this, such as by unwrapping an abstract and using the target class instead, when it is used for extension (at least when the class extending it is automatically generated).

**Comment by EliteMasterEric** [comment]
I ended up getting another error from this line: https://github.com/HaxeFoundation/haxe/blob/d89dc0853d48a275fb6b5ccdafbc0341e3e869f5/src/typing/typeloadCheck.ml#L578

The common thread here is that I am creating externs for classes which other native classes (provided via `--java-lib`) extend or implement. Haxe's automatic extern generation for the Java target is very useful, but when an error occurs in these, error reporting is not helpful.

Some potential workarounds include:

- A proper fix to error reporting when generating Java externs
- Editing all error messages to include the extending class and the class itself
- A way to disable or limit extern generation somehow?

**Comment by Simn** [comment]
I would like to know how you got that unknown position error in the first place. If you load a .jar file via `--java-lib`, the compiler (awkwardly) uses the file name for the error position. See https://github.com/HaxeFoundation/haxe/issues/11108#issuecomment-1502234262 for an example.

**Comment by EliteMasterEric** [comment]
> I would like to know how you got that unknown position error in the first place.

Actively working on a minimal repro now

**Comment by EliteMasterEric** [comment]
I have reproduced the error in a minimal project:

[Here](https://github.com/EliteMasterEric/PickHaxe/tree/bugfix/positioning-repro/samples/repro-testbench)

The basic steps are:

- Create an extern class A but name give it some name like A_Inner
- Create an abstract A that wraps A_Inner but adds new functionality.
  - By naming the abstract A, users familiar with the original Java class will not have to change their code
- Create a function which imports and instantiates class C, which extends A.
  - There is no HX file defining C; you generally don't need one.
  - If you create an extern for C and have it extend A_Inner, this error goes away.

**Expected result:** `libs/minecraft-mapped.jar@net/minecraft/world/item/ArmorItem.class:1: Should extend by using a class`
- Easy to debug, just create an extern for ArmorItem and fix the error.

**Actual result:** `Should extend by using a class`
- No debugging information to work with because position data is gone.

**Additional notes:**
- I ended up generating the JAR myself since I didn't want to put additional steps on you, but I also don't want to leave that JAR public for too long so let me know once you've downloaded it.
- The JAR was generated with Java 17, and uses class version 61.
- EDIT: Just readded the build.hxml that got hit by gitignore

**Comment by Simn** [comment]
This now comes out as `./libs/minecraft-mapped.jar@net/minecraft/world/item/ArmorItem.class:1: character 1 : Should extend by using a class, found TAbstract(net.minecraft.world.item.Item, [])`. The legacy JAR loader is using `null_pos` quite a bit, but I'm reluctant to change it in too many places because who knows what that might cause...

Still need a test for this, which likely is a variant of #11108.
