### ISSUE TITLE
[BUG] Safe navigation for function calls throws a compile error

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11094]
> ERROR  source/funkin/play/cutscene/dialogue/DialogueBox.hx:157: characters 29-30
> 157 |     typingCompleteCallback?.();
>        |                                              ^  
>        | Unexpected (

The [accepted proposal for safe navigation](https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0017-null-safe-navigation-operator.md) provides for optional chaining to be used on function as well; if a function with a value of null would be called with `?.()`, it will not be called, and return null instead if a return value is expected.

A cursory review of #10561 finds that this functionality was not implemented in the test cases. It may be that this was never properly implemented.

**Comment by EliteMasterEric** [comment]
Just learned the feature was left unimplemented, see here:

https://youtu.be/lkpoTcHKjSE?t=454

**Comment by alexeychikk** [comment]
Is safe navigation for call expression going to be implemented at all?

**Comment by T1mL3arn** [comment]
Maybe reopen the issue to be sort of a feature request? We have now `obj?.prop`, so would be nice to have `obj.foo?.()` instead of

```haxe
if (obj.foo != null)
  obj.foo();
```

**Comment by EliteMasterEric** [comment]
> Maybe reopen the issue to be sort of a feature request? We have now `obj?.prop`, so would be nice to have `obj.foo?.()` instead of
> 
> ```hx
> if (obj.foo != null)
>   obj.foo();
> ```

See the explanation in the video. The main argument against `?.()` is that the behavior of side effects is unclear, and in most user code, it is much rarer for functions to be null as opposed to objects (you would have to be working with anonymous structures or functions using the `dynamic` keyword).

**Comment by EliteMasterEric** [comment]
I made HaxeFoundation/haxe-evolution#114 as a home for discussion around `?.[]` and `?.()`. This issue can stay closed as the syntax is unimplemented, not bugged.
