### ISSUE TITLE
Pull requests for 4.3 Hotfix

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11100]
(I can't reopen a merged PR)

* [x] #11097
* [x] #11098
* [x] #11105
* [x] #11107
* [x] #11134

Branch is there: https://github.com/HaxeFoundation/haxe/commits/4.3_bugfix

**Comment by Simn** [comment]
I have added #11134 which is a slightly larger change, but I think we should have it in 4.3 because it should improve `-w` support with regards to deprecation warnings.

**Comment by kLabz** [comment]
Adding this here to not forget about it because I currently have conflicts so will add other things first
 * [x] https://github.com/HaxeFoundation/haxe/commit/e5405a82d8e3eb69b84c33cebc6713dbcd5f808a
