### ISSUE TITLE
-D no-color=0

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11106]
I was wondering if `-D no-color=0` should turn colors off or on. This is a bit of a silly problem with negative defines, because at the moment it behaves the same way as `-D no-color=1`.

My intuition is that the compiler shouldn't just check if the define is defined, but also if it's actually something we'd consider to be `true`. However, that's not what we have been doing and I don't know if this could be changed even in a major version.

Interested in opinions!

**Comment by kLabz** [comment]
Maybe we'd actually need an argument that unset defines? Something like `-D !no-color` could even be enough.

I agree the whole "set to zero to kinda-maybe-well-it-depends-how-its-used un-define flag" really isn't great..

**Comment by Simn** [comment]
I disagree with myself from 5 days ago, the current way of handling `#if` checks is fine because we really just want to check if a value is set at all. But yes that means that unsetting a define would be a good feature.

For context, I was thinking that `-D haxe-next` should imply (among other things) `-D message-reporting=pretty -D no-color`. Coloring isn't supported everywhere so that would be a good default, but then we have the problem that we cannot get rid of the `no-color` define anymore.

**Comment by kLabz** [comment]
We added support for `--undefine no-color` in #11400
