### ISSUE TITLE
Haxe 4.3 - Rest arguments can only be used in static extensions.

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/haxe#11117]
The below line used to work:  
qs.setMany(t.left, (cast t.right : Array).map.fn('$_'));

Now it errors with  
"Rest arguments can only be used in static extensions."   
Any thoughts on how to fix?

**Comment by Simn** [comment]
Is that the exact error you're getting? I can't find that message in the compiler sources. A reproducible example would help!

**Comment by hoseyjoe** [comment]
My apology. The error is related to thx.core. I had assumed that the error was coming directly from 4.3 since that was the only change. I have notified the library owner. Thank you
