### ISSUE TITLE
Haxe 4.3 Reification $v is not allowed outside of `macro` expression

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/haxe#11113]
This used to work  
public static inline var build_version = $v{MacroTools.getDefine("ngversion")};  

In 4.3 it throws "Reification $v is not allowed outside of `macro` expression"

Is there an easy work around?

**Comment by filt3rek** [comment]
Hej,

I suppose you can write this : `public static inline var build_version = haxe.macro.Compiler.getDefine("ngversion");`
But yes, macro reification was allowed before and not with the 4.3 version, idk why...

**Comment by Aurel300** [comment]
See #10883

**Comment by kLabz** [comment]
You're not doing macro reification (which happens when using the `macro` keyword (not the `macro` function access modifier)) there, so just write `var build_version = MacroTools.getDefine("ngversion");`

**Comment by Simn** [comment]
Indeed
