### ISSUE TITLE
Indicator that error comes from macro context

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11121]
It's sometimes hard to tell if a compiler error comes from the macro context or not. With the new error reporting mode, it would be nice to add an indicator for that. In theory, we could always show the target, but that might be a bit much.

My initial idea would be something like this:

```
 ERROR (macro) source/Main.hx:1: characters 1-17

 1 | import Main.foo;
   | ^^^^^^^^^^^^^^^^
   | Class<Main> has no field foo
```

**Comment by filt3rek** [comment]
@kLabz :rofl: 

> [...] I don't know where does this error occurs exactly, in which file ...
@ Rudy maybe something for the new error reporting ?

(joke)

**Comment by filt3rek** [comment]
Or maybe add a "verbose" mode for error reporting that includes as much informations as possible ?

**Comment by kLabz** [comment]
I actually tried this this morning but was not getting the information when actually doing the error printing. If we need to store that inside the error that's a more involved change..

**Comment by kLabz** [comment]
Looking into it again it seems manageable if we move to record errors first, which we were planning to do anyway.
Sounds like the perfect brain-dead task for me tonight while I continue recovering :)
