### ISSUE TITLE
addGlobalMetaData excludeClasses filter argument "request"

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11126]
Hej,

I put it there but it's not an issue, it's a question (and I couldn't create a PR...) :
Would it be possible to add a "excludeClasses" argument to `haxe.macro.Compiler.addGobalMetaData` method please ?
I think it would not break anything, it would be an optional argument of course and  ideally an `Array<String>`
This way when using this method intesivelly (like with empty pathFilter "" and recursive = true) we could exclude some classes from that which would be handy for some use cases (please don't ask me for use cases example otherwise I'll be banned from here :rofl: ) 

Thx for reading me,

**Comment by kLabz** [comment]
I'm ok with anyone wanting to implement that themselves (with `ignore` like other Compiler functions instead of that kinda weird and inaccurate name, though).
