### ISSUE TITLE
Do not import type A in type A when using import.hx

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11124]
Sorry to annoy with this, but since https://github.com/HaxeFoundation/haxe/issues/11120 was closed without any workaround, I thought about that as a workaround.
If importing a type into this type cause this issue when building types (`@:build`meta), we can manually omit the import but not when using the `import.hx` file.
So could it be possible when using `import.hx` file, that it propagates all imports everywhere but not inside the type itself please ?
This could resolve the issue and importing the type inside itself seems also useless

**Comment by kLabz** [comment]
If I understood it properly, problem there was not really importing module `A` but importing one of its fields (while fields were not ready because of the build macro), which can be somewhat useful on module `A` too (if there are other types there where you want to write `foo` instead of `A.foo`).

**Comment by filt3rek** [comment]
IMHO in that case, If you really need to import A.foo into A, you will still be able to add it manually, I mean there is a workaround for that whereas there seems to not be any workaround for the issue that is caused when using import.hx with this kind of statement and a build macro (which is not so amazing as case at the end)

**Comment by Simn** [comment]
There is nothing actionable here on our side, this is a problem with your code. Please stop opening issues about this.

**Comment by filt3rek** [comment]
Sorry please excuse me Sir @Simn I won't disturb your majesty anymore 🙏
