### ISSUE TITLE
default value expressions (default operator and/or literal)

### ISSUE THREAD

**Issue by Jens-G** [HaxeFoundation/haxe#11138]
C# offers a `default` keyword and one of the usage scenarios is to provide a default value for whatever the type of the variable is [1] . This feature is incredibly helpful with generics and generated code.  

Can we have such a feature in Haxe as well? 

Whether the syntax would be along the first and/or the second form is a secondary issue. Whatever makes sense is fine.

   `var x : T = default(T);  // default operator` 
   `var x : T = default;  // default literal` 

[1] https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/default

**Comment by Simn** [comment]
I'm not opposed to that, but it would have to go through haxe-evolution for sure. In particular, I can see this being valuable when generating code from macros, but also for inlining.

**Comment by Aurel300** [comment]
For the record, Rust handles this with the trait [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html). This trait has one method, `fn default() -> Self;`, i.e. a method that, when called, will return the type that is implementing this trait.

To define the default for a new type, you implement the trait:

```
impl Default for MyType {
  fn default() -> Self { MyType { /* set default fields here */ } }
}
```

At a callsite, you can simply do `x.foo = Default::default()`.

Of course we don't have traits and I don't know about https://github.com/HaxeFoundation/haxe-evolution/pull/98 yet.
