### ISSUE TITLE
Homebrew haxe versions

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#11135]
```
❯ brew install haxe@4.2.5
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O#-#
Warning: No available formula with the name "haxe@4.2.5".
==> Searching for similarly named formulae and casks...
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O#-#
Error: No formulae or casks found for haxe@4.2.5.
```
Unable to install previous versions.
This is critical for CI on MacOS. The build servers just stop working.

**Comment by andyli** [comment]
Note that homebrew is never an official supported installation method listed in https://haxe.org/download/, so we don't have someone that actively maintain/improve that. Homebrew has pretty poor support of keeping old versions. It's not that it can't be done, but not trivial. 

Anyway, you may still install an old version by checking out an old commit of homebrew-core.

```sh
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
git fetch
git reset --hard a1701a69c9bcc783f4cdfdd79c5cd04d6b77c9a4
HOMEBREW_NO_INSTALL_FROM_API=1 brew install haxe
```

**Comment by Simn** [comment]
I don't think there's anything actionable here.
