### ISSUE TITLE
compiled files in source are problematic

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#11139]
There are a number of compiled files in the `tests`. They should be removed from source since they compilcate copyright matter of this repo.

tests/misc/cs/projects/Issue4151/DynamicAudioNormalizerNET.dll
tests/unit/cs_drivers/Mono.Data.Sqlite.dll
tests/unit/cs_drivers/System.Data.dll
tests/unit/cs_drivers/System.Xml.dll
tests/unit/res2.bin (looks like a renamed neko.exe or something)

One solution would be letting the test runner download the required binaries before running tests.

**Comment by Simn** [comment]
I also noticed these cs_drivers files recently and wondered what that is. Will test on a branch if they are even used.

The Issue4151 test I'm very willing to just remove as well.

And I'll check the res2.bin thing.

**Comment by Simn** [comment]
I have removed the cs_drivers DLLs because they were not used in our tests. I also removed the other test.

Regarding the res2.bin, I simply truncated that in the middle so that the test still works. Is that alright?

**Comment by andyli** [comment]
> Regarding the res2.bin, I simply truncated that in the middle so that the test still works. Is that alright?

I'm afraid not. Truncated binaries are still a product of source code (though it's still HF's).

Replace it with some random bytes, or as I suggested earlier, let the test runner download it.

**Comment by Simn** [comment]
I don't want to download it because I don't even know what exactly it is, and I always prefer to have less network dependencies in our tests. I have now recreated it by hand which I hope does the trick!

**Comment by andyli** [comment]
Perfect, thanks!
