### ISSUE TITLE
Resolve a class using reflection in macro context

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11147]
Hej,

I wonder how to do if we want to keep a class for macro context when trying to resolve a class using reflection : https://try.haxe.org/#57Bf7846 in macro context ?
Even putting the class in the build file, or with `haxe.macro.Context.getType( "Foo" );` it doesn't work
Use case : dynamically call a function in macro context
Test.hx :
```haxe
class Test {
  static function main() {
    var cl	= Type.resolveClass( "Foo" );
    trace( cl );
    Macro.get();
  }
}

@:keep
class Foo{
  public static function bar(){
     trace( "ok" );
  }
}
```
Macro.hx :
```haxe
class Macro {
  macro public static function get(){
    //Test.Foo;
    var cl	= Type.resolveClass( "Foo" );
    trace( cl );// <--- If "Test.Foo" (line 3) is uncomented, Macro.hx:5: Class<Foo> otherwaise Macro.hx:5: null 
    return macro null;
  }
}
```

**Comment by Simn** [comment]
`resolveClass` resolves classes that exist at run-time, which in the macro case means that the compiler must have seen the type at some point. I don't think any such function should perform type-loading.
