### ISSUE TITLE
Haxe will not install on Fedora 38

### ISSUE THREAD

**Issue by typhyte** [HaxeFoundation/haxe#11167]
Hello, I'm trying to install Haxe on Fedora 38. However, when I do, it gives me a Transaction test error.
`Error: Transaction test error:
  file /usr/lib/.build-id/b8/acf4f8271b78cd6dca636cb5b877c5c64f47f4 conflicts between attempted installs of haxe-4.2.5-5.fc38.x86_64 and nekovm-2.3.0-11.fc38.x86_64
`

I saw that this was an issue before on #10710 and #10683, but it seems it may have not been resolved yet.

**Comment by kLabz** [comment]
That makes 3 open issues for the same thing. Let's use #10683, the oldest of the 3.
There should be new haxe packages "soon", though I'm not sure it will fix the problem.
