### ISSUE TITLE
"Variables of type Void are not allowed" not reporting error location in a very specific case

### ISSUE THREAD

**Issue by EspeuteClement** [HaxeFoundation/haxe#11162]
Hello,
On revision 4.3.0-rc.1+389cb4706 of the haxe compiler, I triggered a very specific bug. 
The build fails with the error : `Variables of type Void are not allowed` without any indication of where the error actually is.
```
$ haxe d4x.hxml
Variables of type Void are not allowed
```
The error was due to a variable assignent from a function that returned void.

I tried to reproduce the bug in a test project, but the error was correctly reported : 
```
$ haxe --hl test.hl --main Test
Test.hx:13: characters 7-8 : Variables of type Void are not allowed
`````

<details> <summary>Code for the minimal reproduction that actually works</summary>

```haxe
class Test {
	static function main() {
		var bar = new Bar();
		bar.a();
	}
}

class Bar {
	public function new() {

	}
	public function a() {
		var c = b();
		trace("a");
	}

	public function b() {
		trace("b");
	}
}
```
</details>

@ncannasse informed me that @kLabz had access to the d4x repository, so I will include the repro steps that I used on another computer that managed to reproduce the error:

1. In the d4x project, open the src/world/WorldBase.hx file
2. In the WorldBase class, add a function 
```
static function foo() {
    trace("foo");
}
```
3. In the loadScene() function, add the following code
```
var a = foo();
```
4. Build the project using `haxe d4x.hxml`
5. Hopefully notice that there is no line or file information when the build fails.

**Comment by kLabz** [comment]
Can still repro on latest dev: https://try.haxe.org/#29E600B5

**Comment by kLabz** [comment]
Reduced too much above, here's the issue from Shiro: https://try.haxe.org/#e8B1e586

Which is different actually.  I could fix the reification one (locally, haven't pushed yet) but that one is a bit tricky as there's nowhere to pull `name_pos` from. Plus tvar decoding uses that strange `$` trick that wouldn't allow me to just pass `name_pos` from the macro.
