### ISSUE TITLE
Should default type parameters abide by imports?

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#11161]
Using absolute paths seems to be necessary atm. [online](https://try.haxe.org/#19C069CA)

```haxe
import haxe.ds.Option;

class Test {
	static function main() {
		trace("Haxe is great!");
	}
}

class TestDefaultTypeParameter<T = Option<String>> {
	final data:T;

	public function new(data) {
		this.data = data;
	}
}
```

```bash
[ERROR] Test.hx:9: characters 36-50

 9 | class TestDefaultTypeParameter<T = Option<String>> {
   |                                    ^^^^^^^^^^^^^^
   | Type not found : Option
```

**Comment by Simn** [comment]
Huh, very surprising that this fails even when everything is in the same module. Though I'd expect it to work even with separate modules.

**Comment by 0b1kn00b** [comment]
It's a great feature: proxies have 6 terms and might even be usable now.

**Comment by Simn** [comment]
This was actually pretty bad because it tried loading the type way too early. Definitely 4.3.1 material.

**Comment by kLabz** [comment]
Any chance to get this to work too? :eyes: 
https://try.haxe.org/#4a7aa8B3

**Comment by Simn** [comment]
Not here, but that does seem like it could be supported.

**Comment by 0b1kn00b** [comment]
Wait, that looks an awful lot like higher types.
