### ISSUE TITLE
Recursive inline is not supported on enum abstract constructor

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11177]
This is separated files:
```haxe
class Main {
	static function main():Void {
		// 1. Open Main.hx and Buttons.hx in VSCode
		// 2. Check Buttons.hx tab to run diagnostics on it
		// 3. Change Main.hx trace below and run build task
		// 4. Check Buttons.hx: there is error now
		trace("change this line");
	}
}

class Buttons {
	static function init(main:Main):Void {
		// Recursive inline is not supported
		trace(KeyCode.Backspace);
	}
}

enum abstract KeyCode(Int) {
	var Backspace = 8;
}

--class-path src
--main Main
--interp
```
Regression since 4.2.5. Happens on 4.3.0 and dev. Project:
[RecursiveEnum.zip](https://github.com/HaxeFoundation/haxe/files/11303828/RecursiveEnum.zip)

**Comment by RblSb** [comment]
Regression is older than 737af26bedd474dae614f998117dfe1df40aedd7. There is no dev builds to easily check older ones...

**Comment by kLabz** [comment]
Bisected to https://github.com/HaxeFoundation/haxe/commit/7321f188b :fearful:

**Comment by RblSb** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/pull/11220, but test needed

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/blob/486dfc80866173a2d57c47476e5e4590c30e3504/tests/server/src/cases/issues/Issue11177.hx
