### ISSUE TITLE
`@:nullSafety(Off)` not respected in compilation server context in `4.3.0`

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#11179]
Not got a minimal reproduction yet, but is catching me from [`haxe-strings`](https://github.com/vegardit/haxe-strings) when I use the compilation server.

```bash
/mnt/dat/i/prj/haxe/published/ballz/haxe_modules/haxe-strings/src/hx/strings/CharIterator.hx:131: characters 42-71 : Null safety: Cannot cast nullable value to not nullable type.
/mnt/dat/i/prj/haxe/published/ballz/haxe_modules/haxe-strings/src/hx/strings/CharIterator.hx:156: characters 43-72 : Null safety: Cannot cast nullable value to not nullable type.
failed
```

One of the offending lines [here](https://github.com/vegardit/haxe-strings/blob/0245bc7235fd6dd5c06787d2c2467be835bbedd3/src/hx/strings/CharIterator.hx#L131)
```haxe
final prevChar = @:nullSafety(Off) prevBuffer[prevBufferPrevIdx];
```

**Comment by kLabz** [comment]
~~Seems to work fine to me, maybe there's something else involved?~~ nvm it's about server

https://try.haxe.org/#96ED3119

**Comment by 0b1kn00b** [comment]
Try the declaration inside a function is all I can think of that might change it there. I'll dig in at a later point.

**Comment by 0b1kn00b** [comment]
That library is doing it reliably after the second build connected to the server.

```haxe
package;

import hx.strings.CharIterator;

class Main{
  static public function main(){
    trace("ok");
  }
}
```

```hxml
-lib haxe-strings
-main Main
--interp 
--connect 7070
```

```bash
haxe --server-listen 127.0.0.1:7070  
```

**Comment by kLabz** [comment]
Bisected to #10643

**Comment by Simn** [comment]
Without thinking about it too much, I think this is what happens here:

1. Null-safety runs, the meta is there and everything is good.
2. Some filter removes the metadata (this can happen easily).
3. The class is saved.
4. Somehow the `CfPostProcessed` flag gets removed.
5. The class is restored.
6. Post process with null safety runs again, but now the metadata is gone.

I'm quite curious why 4. would happen here.

**Comment by kLabz** [comment]
It doesn't seem to be about `CfPostProcessed` removal but null safety doesn't seem to respect this flag.

```patch
diff --git a/src/typing/nullSafety.ml b/src/typing/nullSafety.ml
index 7a5780be2..85fb7b181 100644
--- a/src/typing/nullSafety.ml
+++ b/src/typing/nullSafety.ml
@@ -1499,6 +1499,7 @@ class class_checker cls immediate_execution report =
                        if is_safe_class && (not (has_class_flag cls CExtern)) && (not (has_class_flag cls CInterface)) then
                                self#check_var_fields;
                        let check_field is_static f =
+                               if not (has_class_field_flag f CfPostProcessed) then begin
                                validate_safety_meta report f.cf_meta;
                                match (safety_mode (cls_meta @ f.cf_meta)) with
                                        | SMOff -> ()
@@ -1509,6 +1510,7 @@ class class_checker cls immediate_execution report =
                                                                (self#get_checker mode)#check_root_expr expr
                                                );
                                                self#check_accessors is_static f
+                               end
                        in
                        if is_safe_class then
                                Option.may ((self#get_checker (safety_mode cls_meta))#check_root_expr) cls.cl_init;
```

This fixes the repro, now checking what it breaks...

**Comment by Simn** [comment]
Oh, then it's quite funny that I wrote this long-ass comment about how important it is to check this flag, only to not check if the very first filter after that comment actually checks this flag...

**Comment by kLabz** [comment]
Yeah exactly what I thought :laughing:

**Comment by kLabz** [comment]
The minimum repro is getting _weird_ oO

```haxe
class Main {
	final prev:Null<A> = null;
	var nextChar = TriState.UNKNOWN;

	function new() {
		final prevChar = @:nullSafety(Off) prev.get(); // Null safety: Cannot cast nullable value to not nullable type.
		try {} catch (ex:String) nextChar = FALSE;
	}

	static function main() {}
}

abstract A(Bool) {
	inline public function get(index:Int):Int return _get();
	function _get():Int return 1;
}

enum abstract TriState(Null<Bool>) from Null<Bool> to Null<Bool> {
	final TRUE = true;
	final FALSE = false;
	final UNKNOWN = null;
}
```

```hxml
-main Main
--macro nullSafety("Main", Strict)
--interp
```

**Comment by kLabz** [comment]
Also if I turn `A` into a `class` the error becomes:
> Null safety: Cannot access "_get" of a nullable value.

Which seems a bit more helpful to me (although it shouldn't be happening there because it's a compilation server bug)
