### ISSUE TITLE
Void as value error disappears on second compilation

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11184]
Regression since 4.2.5.
```haxe
class Main {
	static function main() {
		// compiles fine on second build try (bad)
		// also generates empty main.js or eval null exception
		function foo():Void {}

		final arr = [
			foo(),
			// bar()
		];
	}

	// always fails (good)
	function bar():Void {}
}
```

Another related bug, output tab with `-D message-reporting=pretty` looks like this for this code:
```
Failed - try fixing the error(s) and restarting the language server:

[30;41m ERROR [0m src/Main.hx:8: characters 4-9

 8 | [2m   [0m[1mfoo()[0m[2m,[0m
   |    [31m^^^^^[0m
   | Cannot use Void as value
```
And it generates bad `Problem` info in comparison to basic reporting, so you don't see red error highlighting in file.

**Comment by kLabz** [comment]
Yeah vshaxe has not been updated for pretty errors.

**Comment by Simn** [comment]
This looks pretty bad, might suggest that some error flag isn't set correctly and the server then caches the context...

**Comment by kLabz** [comment]
I can bisect this tonight if you want (have to go for a couple hours now)

**Comment by Simn** [comment]
I'll do it

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/commit/7321f188b826e862d1eaff9cdb25e34abcd57279

Note that this only reproduces with diagnostics enabled.

**Comment by RblSb** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/pull/11220, but test needed

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/blob/486dfc80866173a2d57c47476e5e4590c30e3504/tests/server/src/cases/issues/Issue11184.hx
