### ISSUE TITLE
mbedtls 3.x support

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#11195]
A few distros pumped their mbedtls 2.x to 3.x ([see mbedtls on repology](https://repology.org/project/mbedtls/versions)) and it's beginning to affect us - [openSUSE neko package build is failing](https://build.opensuse.org/package/show/openSUSE:Factory/neko#comment-1771563).

Hopefully we can support both 2.x and 3.x, by the use of C preprocessing macros.

**Comment by alucryd** [comment]
Same thing with archlinux. We made a compat package for the time being (with headers in `/usr/include/mbedtls2`, and libs in `/usr/lib/mbedtls2`), but the dune build system does not respect CFLAGS, even though they've been added as per dune's documentation.

```
(include_subdirs no)

(library
	(name mbedtls)
	(foreign_stubs
		(language c)
		(names mbedtls_stubs)
		(flags -I/usr/include/mbdetls2))
	(c_library_flags (-L/usr/lib/mbedtls2))
	(wrapped false)
)
```

**Comment by kLabz** [comment]
> Same thing with archlinux. We made a compat package for the time being (with headers in `/usr/include/mbedtls2`, and libs in `/usr/lib/mbedtls2`), but the dune build system does not respect CFLAGS, even though they've been added as per dune's documentation.
> 
> ```
> (include_subdirs no)
> 
> (library
> 	(name mbedtls)
> 	(foreign_stubs
> 		(language c)
> 		(names mbedtls_stubs)
> 		(flags -I/usr/include/mbdetls2))
> 	(c_library_flags (-L/usr/lib/mbedtls2))
> 	(wrapped false)
> )
> ```

Thanks! I managed to get it working locally on arch with `mbedtls2` package and this `libs/mbedtls/dune`:
```dune
(include_subdirs no)

(library
        (name mbedtls)
        (foreign_stubs
                (language c)
                (names mbedtls_stubs)
                (flags -I/usr/include/mbedtls2 -fPIC))
        (c_library_flags (-L/usr/lib/mbedtls2))
        (wrapped false)
)
```

**Comment by tobil4sk** [comment]
I always search and come back to copy this when bisecting to old versions, so here is a correction to a typo in the include path:

```dune
(include_subdirs no)

(library
        (name mbedtls)
        (foreign_stubs
                (language c)
                (names mbedtls_stubs)
                (flags -I/usr/include/mbedtls2 -fPIC))
        (c_library_flags (-L/usr/lib/mbedtls2))
        (wrapped false)
)
```
