### ISSUE TITLE
[hl] -dce no breaks hl.I64

### ISSUE THREAD

**Issue by Apprentice-Alchemist** [HaxeFoundation/haxe#11196]
Using hl.I64 and `-dce no` together results in the following error:
```
[ERROR] /versions/4.3.1/std/hl/I64.hx:41: characters 12-38

 41 |  @:op(a+b) function add(v:I64) : I64;
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    | Missing function body
```

https://try.haxe.org/#8dad2c36

**Comment by Simn** [comment]
I was confused how `-dce no` could affect typing error, but that error actually comes from genhl.
