### ISSUE TITLE
LSP/macro type reification: Defining 0-ary function as a type parameter with a reified return type messes up LSP outline

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#11199]
Using the 4.0 function syntax (as opposed to the old `Void-> ...`) defining 0-ary function as a type parameter with a reified return type, as in the example below, completely messes up the LSP outline. The `var t` becomes the new root for everything that comes after it in the file.

```haxe

function test() {
  var complex = macro : foo.Bar;
  // messes up outline:
  var t = macro : Option<()->$complex>;
  // doesn't mess up outline:
  var t = macro : Option<Void->$complex>;
}

class A{}
class B{}
class C{}
```

**Comment by kLabz** [comment]
This seems fine nowadays.
