### ISSUE TITLE
[eval] local static var - Instance constructor not found: haxe.ds._Map.Map_Impl_

### ISSUE THREAD

**Issue by SomeRanDev** [HaxeFoundation/haxe#11193]
The following ~~worked~~ ran in 4.3.0:
```haxe
// haxe -cp src --macro Main.comptime()
function comptime() {
	static var m: Map<Int, String> = [];
	trace(m);
}
```
But when running in 4.3.1/nightly, the following error is printed:
```
[0] Instance constructor not found: haxe.ds._Map.Map_Impl_
```

**Comment by Simn** [comment]
This actually didn't work (correctly) before either: #11096. But yeah, it obviously shouldn't fail like this.
