### ISSUE TITLE
[ide] false `This cast has no effect, but some of its sub-expressions` report 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#11203]
Minimized from `tink.core.Future`:

```haxe
function main() {
	var future = new Future();
	future.eager();
}

abstract Future({}) from {} {
	public function new() this = {};

	public inline function eager():Future {
		trace("much side effect!");
		return this;
	}
}
```

![image](https://user-images.githubusercontent.com/49749/236549087-2a21deaa-309d-433c-b0f7-5520a6063de6.png)

PS also what's that `2` in `diagnostics(2)`?

**Comment by nadako** [comment]
Another interesting thing. If I reload vscode and open `Main.hx`, I get this instead:
![image](https://user-images.githubusercontent.com/49749/236549491-daf7b9ff-a441-4b96-bb4a-e3e897f0336f.png)

But if I save (just Ctrl+S, don't even need to modify the file!) it gets back to the original message.

**Comment by kLabz** [comment]
> PS also what's that 2 in diagnostics(2)?

You had two haxe LSP running at some point (or another extension using the source named "diagnostics"); that thing is a bit messed up atm (edit: should be fixed soon btw, can't repro anymore on my branch).

**Comment by kLabz** [comment]
Also about the unused variable, this diagnostic is ignored when there are other errors so it only shows when the bug you're reporting hasn't triggered yet.

**Comment by Simn** [comment]
But that variable isn't unused

**Comment by kLabz** [comment]
After inlining I suppose it's unused? Not sure in what order things happen there.

**Comment by RblSb** [comment]
Can be reopened

**Comment by Simn** [comment]
#11220 fixed this, or is there another issue?

**Comment by RblSb** [comment]
Ah, did you forget to remove disabled test?
https://github.com/HaxeFoundation/haxe/blob/development/tests/display/src/cases/Issue11203.hx.disabled

**Comment by Simn** [comment]
Ah yeah, that can be removed because I added a better one.
