### ISSUE TITLE
Pull requests for 4.3 Hotfix (part 2)

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11201]
* [x] #11114
* [x] #11163
* [x] #11192
* [x] #11200
* [x] #11204
* [x] #11206
* [x] #11217
* [x] Fix for #11202 (commits linked there)
* [x] #11212
* [x] #11286
* [x] #11301
* [x] #11269
* [x] #11230

**Comment by RblSb** [comment]
Want to request https://github.com/HaxeFoundation/haxe/pull/11114 in fix release
Second part of efield fix: https://github.com/HaxeFoundation/haxe/pull/11206

**Comment by kLabz** [comment]
- [x] I'd like to add https://github.com/HaxeFoundation/haxe/commit/34afe73f3cdb5e95581941504ad1db0108d764a4 too so that people can silence `@:enum abstract` deprecation warnings with `addGlobalMetadata`.
- [x] Also https://github.com/HaxeFoundation/haxe/commit/ea57ab1ef60d212228c8657b7bc5b1085c62714e to be able to target those warnings

**Comment by tobil4sk** [comment]
#11192 fixes #11005 which technically isn't a 4.3 regression, but it became worse because in 4.3 any code with a macro that uses `haxe.macro.Compiler` breaks when using `-D no-inline`.

So it may be nice to have in a 4.3 bugfix?

**Comment by kLabz** [comment]
Seems fine to me

**Comment by giuppe** [comment]
Any chance that #11249 will be added to the next hotfix?

**Comment by kLabz** [comment]
Hmm yeah, but I should make it work properly first.
Will look into that later this week or early next week.

**Comment by RblSb** [comment]
It is not too late for https://github.com/HaxeFoundation/haxe/pull/11252, https://github.com/HaxeFoundation/haxe/pull/11294?
Currently error on `float ?? 0` hurts.

**Comment by kLabz** [comment]
It kinda is too late for 4.3.2 :/

**Comment by Simn** [comment]
#11252 at least seems kind of important though...

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/commit/62bdf35ee8894cb38541db5622ac7c88a6fd501c
https://github.com/HaxeFoundation/haxe/commit/44c9abdbb176c261d42822e2e4003b4727054aff

**Comment by kLabz** [comment]
Thanks, will be tracked in #11306
