### ISSUE TITLE
`Math.round` is producing unexpected number

### ISSUE THREAD

**Issue by bosyunam** [HaxeFoundation/haxe#11209]
Can someone please explain why `Math.round(844468144559.999878)` produces `507070896` instead of `844468144559`?

https://try.haxe.org/#5a8B5C75

Works as expected for JavaScript target, but I don't want to target JavaScript. I want to target Eval.

**Comment by tobil4sk** [comment]
Integers in haxe are 32 bit integers (on most targets), so the maximum value is `2,147,483,647`. Anything above that will overflow (on most targets).

Javascript works because it is an exception since it doesn't have native integers.

**Comment by bosyunam** [comment]
Thanks.

Haxe appears to have an `Int64` type: https://api.haxe.org/haxe/Int64.html

Is there any way to `Math.round` a `Float` but get an `Int64` instead?

**Comment by tobil4sk** [comment]
There is no int64 version of `Math.round` in the Haxe standard library unfortunately. There is a `Math.fround` which returns a float instead, which would give the correct value with your original example.

**Comment by flashultra** [comment]
You can also convert to Int64 after that with ```Int64Helper.fromFloat(Math.fround(844468144559.999878));```
https://try.haxe.org/#E740ea17

You should expected ```844468144560```  , not ```844468144559```

**Comment by bosyunam** [comment]
This helps. Thank you.
