### ISSUE TITLE
PPA missing Release file

### ISSUE THREAD

**Issue by srodrigo** [HaxeFoundation/haxe#11210]
Hey,

I'm trying to install Haxe on Ubuntu 22.10 (kinetic). It doesn't look like the package is available for 22.10 and 23.04

`E: The repository 'https://ppa.launchpadcontent.net/haxe/releases/ubuntu kinetic Release' does not have a Release file.`

![image](https://user-images.githubusercontent.com/5873601/236938984-5b6dca97-7801-4b09-b5ad-ce25f4aff864.png)

Would it be possible to upload it for this versions?

**Comment by kLabz** [comment]
cc @andyli

**Comment by andyli** [comment]
Sorry for the late reply.
22.10 is EOL and ppa:haxe/releases has 23.04 packages now.

**Comment by srodrigo** [comment]
Thanks a lot @andyli
