### ISSUE TITLE
Returning function with stored TConst(TThis) in body no longer works.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#11212]
Here's a "minimal" example:

```haxe
class Test {
    #if !macro
    var value = 123;
    function new() {}
    function fail() {
        var foo:Foo = value; // on JS this generates `let foo = function() { return this.value; };` on JS
        trace(foo());// this will throw
    }
    static function main() {
        new Test().fail();
    }
    #end
}

@:callable
abstract Foo(()->Int) from ()->Int {
    @:from macro static function ofExpr(e) {
        trace(haxe.macro.Context.typeExpr(e));
        return macro @:pos(e.pos) (function ():Int return $e:Foo);
    }
}
```

This worked in Haxe 4.2.5. The problem here is that it's actually the compiler doing the storing, so it's not really avoidable.

Interestingly, if compiled to neko, it just works :D

But on HL it segfaults, on JS it generates the invalid code mentioned above (resulting in an NPE). On eval it fails to compile with `Uncaught exception Unbound variable`, which I guess is a bit of an improvement. I wouldn't mind if it failed, assuming there's some workaround.

**Comment by Simn** [comment]
Ah yeah, that's a bit of an oversight from https://github.com/HaxeFoundation/haxe/commit/d42ce55f0b80a707f36592e862c2e761dddcf8b0

**Comment by Simn** [comment]
This suggests that the same problem exists when using stored expressions explicitly. Should be reproducible for the closure situation, but I think also inside of abstract functions.

**Comment by back2dos** [comment]
> This suggests that the same problem exists when using stored expressions explicitly. 

Indeed it does. That could be circumvented by not storing expressions explicitly, which would be quite a handycap, but at least possible.

**Comment by Neverbirth** [comment]
Sorry for bumping this, but I was wondering if this is still planned in the near future, I would love to upgrade to 4.3, and this is sadly preventing me from doing it.

**Comment by Simn** [comment]
It's on the hotfix milestone so it will be looked into, but I can't give you a timeline for a fix (or a release for that matter).

I suppose a fix would be to just map the expression and replace `this` with whatever makes sense in the current context (`get_this`).
