### ISSUE TITLE
CI xmldoc produces info.json with no branch info

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#11215]
Right now `info.json` produced in the "Build xmldoc" step has missing branch info
```json
  {
    "commit": "23ef99d741a0b8eb8ccc96922fa7f0614a4228ca",
    "branch": ""
  }
```

It caused the api.haxe.org repo had its xml contents cleared. See [how previsouly the xml folder](https://github.com/HaxeFoundation/api.haxe.org/tree/08d3b56a25d48a8811bdd30b30a162f34b4e2873/xml) should look like.

I suspect this is caused by https://github.com/HaxeFoundation/haxe/commit/95a4c4de0ce25d595218e69f13c020f381dbfd82.

**Comment by kLabz** [comment]
Seems fine now: https://github.com/HaxeFoundation/haxe/actions/runs/4951782615
