### ISSUE TITLE
Willing to accept PRs to improve null safety on Lua?

### ISSUE THREAD

**Issue by danielo515** [HaxeFoundation/haxe#11223]
Today I went crazy and decided to check again what happens when you enable null safety on everything (`--macro nullSafety("", Strict)`). To my surprise, the output error fit in my screen. I made a simple line count, and this is the result:

```
╰─❯ haxe build.hxml 2>&1 |wc -l
      92
```

Not that many, so I thought: what if I create some PRs to reduce that number down to zero? Will you want to merge that or is a waste of my time?

**Comment by tobil4sk** [comment]
This issue isn't unique to lua: https://github.com/HaxeFoundation/haxe/pull/10081

**Comment by kLabz** [comment]
Adding some `Null<>` to signatures where it makes sense, sure why not.

Adding `@:nullSafety(Off)`, changing signatures, editing generated files and ending up with a PR with thousands of changes mixing all of the above would likely result in another stalled PR though.

**Comment by danielo515** [comment]
> Adding `@:nullSafety(Off)`, changing signatures, editing generated files and ending up with a PR with thousands of changes mixing all of the above would likely result in another stalled PR though.

Yes, that is what I exactly want to avoid.

> This issue isn't unique to lua: #10081

But Lua is the only target I have enough experience with, and I wanted to do a series of very focused, small as possible PRs

**Comment by kLabz** [comment]
That should be fine and welcome :)

**Comment by kLabz** [comment]
I suppose there's nothing more to be done/answered here.
