### ISSUE TITLE
Strange Analyzer behaviour

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11221]
Hej,

Idk if it's normal but I just noticed that Analyzer optimizes "a" (Test.hx:14) but not "b" (Test.hx:15) here : https://try.haxe.org/#EdcD1D3a 
```js
class Test {
    static main() {
        let _675 = Test.foo();
        let b = _675.y;
        Test.arr[1] = _675.r;
        console.log("Test.hx:14:",_675.x);
        console.log("Test.hx:15:",b);
        console.log("Test.hx:16:",Test.arr);
    }
    static foo() {
        return { x : 1, y : "bar", z : true, r : "test"};
    }
}
```

**Comment by filt3rek** [comment]
Sorry here is a minimal example : https://try.haxe.org/#513dD166
```haxe
class Test {
	static function main() {
		var o = foo();
		var a = o.x;
		var b = o.y;
		trace(a);
		trace(b);
	}

	static function foo() {
		return {x: 1, y: 2}
	}
}
```
Gives : 
```js
// Generated by Haxe 5.0.0-alpha.1+7919bbc
(function ($global) { "use strict";
class Test {
	static main() {
		let o = Test.foo();
		let b = o.y;
		console.log("Test.hx:6:",o.x);
		console.log("Test.hx:7:",b);
	}
	static foo() {
		return { x : 1, y : 2};
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
Test.main();
})({});
```

**Comment by Simn** [comment]
The analyzer refuses to move `b` past the `console.log` call because in theory it could modify `o.y`. While this looks a bit silly when using `trace`, it is the correct behavior in the general case. Here's an example to demonstrate:

```haxe
class Main {
	static var object = {x: 1, y: 2};

	static function main() {
		var o = foo();
		var a = o.x;
		var b = o.y;
		dontTrace(a);
		dontTrace(b);
	}

	static function foo() {
		return object;
	}

	static function dontTrace(a:Dynamic) {
		object.y = 3;
		trace(a);
	}
}
```

I don't want to make hacks for `trace`, and it would require some more elaborate code contract system (or interprocedural analysis) to manage this in the general case.

**Comment by filt3rek** [comment]
Ok I understand, the Analyzer is more clever than I am, I just focused on this special case of `trace` (and other where there isn't any modifications) and haven't seen the cases where there could be modifications.
Thx @Simn to taking time to answer me in an elaborate way with demonstration, and sorry for this false bug report.
Have a nice day !
