### ISSUE TITLE
Cause of this iteration emptyness??

### ISSUE THREAD

**Issue by vega0** [HaxeFoundation/haxe#11243]
![image](https://github.com/HaxeFoundation/haxe/assets/6493857/e596389b-ad06-413b-8b02-7691adc66cf8)

**Comment by kLabz** [comment]
You might not want to ignore errors when troubleshooting (line 16)

**Comment by vega0** [comment]
> You might not want to ignore errors when troubleshooting (line 16)

![image](https://github.com/HaxeFoundation/haxe/assets/6493857/b118b3b9-107b-4bc9-a02e-9ba873b421e4)

**Comment by vega0** [comment]
its looks like i can't correct iterate the array object.

**Comment by vega0** [comment]
ah wtf, now its working!
