### ISSUE TITLE
Enum pattern matching showing error on the wrong parameter

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#11254]
```
[ERROR] Test.hx:5: characters 15-20

 5 |    case C(id, other) | B(id) | C(id):
   |               ^^^^^
   | Variable other must appear exactly once in each sub-pattern
   ```
Here, we get an error highlighting `other` as the problem when the actual problem is the variable `id`

Repro: https://try.haxe.org/#Ab874E05

**Comment by Simn** [comment]
No it isn't, the problem is in fact `other`. When you capture in or-patterns, all captures must appear in all patterns because otherwise they would not have values in some of them. If you don't care about its value, use `_` instead.

**Comment by Jarrio** [comment]
Ahhh, it was late and i misunderstood the error. Thanks!
