### ISSUE TITLE
import issue and wrong error message

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11258]
Hej,

I think this is not working as expected : 
pack/Foo.hx : 
```haxe
package pack;
typedef TBar = {};
class Foo{}
```
Main.hx : 
```haxe
import pack.Foo;
class Main {
    static function main() {
        var o : Foo.TBar = null;    // Main.hx:4: characters 11-19 : Type not found : Foo
    }
}
```
And this works (look at the import statement `import pack.*;` instead of `import pack.Foo;` : 
pack/Foo.hx : 
```haxe
package pack;
typedef TBar = {};
class Foo{}
```
Main.hx : 
```haxe
import pack.*;
class Main {
    static function main() {
        var o : Foo.TBar = null;    // No compiler error, all works fine
    }
}
```
Then another weird case (now there is no typedef TBar in Foo but the error message tells `Type not found : Foo` instead of `Module Foo does not define type TBar`) : 
pack/Foo.hx : 
```haxe
package pack;
class Foo{}
```
Main.hx : 
```haxe
import pack.*;
class Main {
    static function main() {
        var o : Foo.TBar = null;    // Main.hx:4: characters 11-19 : Type not found : Foo
    }
}
```

**Comment by Geokureli** [comment]
with your first example the following all work:
```hx
import pack.Foo;
class Main {
    static function main() {
        var o : Foo = null;
        var o : TBar = null;
        var o : pack.Foo.TBar = null;
    }
}
```
I get that  `Foo.TBar` giving the error: "Type not found : Foo" is odd, but "Module Foo does not define type TBar` is also odd because TBar could be a static field of Foo or a type defined in module Foo

**Comment by filt3rek** [comment]
Yes but in my first example this `var o : Foo.TBar = null;` does'nt work.

Then for now in haxe `Module Foo does not define type TBar` is the error message getting in this kind of situations but I don't mind if we find something more appropriate but no `Type not found : Foo` which is totally wrong.

**Comment by Simn** [comment]
This doesn't work because we don't support partial paths like this. You can use `TBar`, or you can use `pack.Foo.TBar`, but you can't use what you're using. I don't want to mess with this either because our resolution mechanism is already complicated enough.
