### ISSUE TITLE
Additional possibilities!

### ISSUE THREAD

**Issue by vega0** [HaxeFoundation/haxe#11250]
Is it possible to create Nested class declaration 1.
Multiple extending class unlimited 2.
Nested typedefinitions, nested structures and all statement items nestedable.

Syntax sugar changing 3. Multiple implementation / inheritance.
Anonymous class declarations 4.
Python like syntax to change between tab indent and inbrackets blocks. 5.

```
class PreClass1
 public function new () {}

class PreClass2
 public function new() {}

class Test1 extends PreClass1, PreClass2 implements ITest1

 // add the class root object as additional type!.
 anonymousclass = class
   public inline function testInline() {return True;}

  public function new()
  {
    super.class._1(); // index firstly defined in extends row class supercall.
    super.class._2(); // or class.PreClass1() or super.PreClass1()
  }
```

**Comment by vega0** [comment]
Yes! Supported multireturns as it is in lua/python and C++ Tuples<t1, t2, t3, ...>

**Comment by vega0** [comment]
Add utf8 support for variable and file names!

**Comment by Simn** [comment]
I'm not sure what this is, but if you want to suggest language extensions you'll have to go to https://github.com/HaxeFoundation/haxe-evolution
