### ISSUE TITLE
Big numbers problem.

### ISSUE THREAD

**Issue by vega0** [HaxeFoundation/haxe#11263]
I have some algorithm that uses UInts and Floats to make readable size of number type. Is it possible to create multiple number types to make possible to work with big numbers? Big numbers problem.

112606856 after multiply by 1024 must be 115309420544, got 3640270848 on C++ target. How to solve it?

**Comment by flashultra** [comment]
Well, you expected to get (in hex)  1A D8FA 2000  , which is above 32 bits and for that in C++ target you've got only D8FA 2000 (  in hex)
You should implement correct operations for * , / , - and + using Array<Int>  for correct overflow behaviour. 
Check my PR for that  : https://github.com/HaxeFoundation/haxe/pull/10750
Maybe your question is not  a issue, so you can close it.

**Comment by vega0** [comment]
> Well, you expected to get (in hex) 1A D8FA 2000 , which is above 32 bits and for that in C++ target you've got only D8FA 2000 ( in hex) You should implement correct operations for * , / , - and + using Array for correct overflow behaviour. Check my PR for that : #10750 Maybe your question is not a issue, so you can close it.

why its not pulled into one? isn't finished?

**Comment by flashultra** [comment]
One of the tests ( for Lua - https://github.com/HaxeFoundation/haxe/actions/runs/4628159873/jobs/8186949421#step:11:386)  failed, but it's hard for me to test it on Windows. All other things work.
The only other major change that could be made is the modPow() function, which is currently slow and can be a problem for generating primes (for RSA keys for example)

**Comment by vega0** [comment]
> One of the tests ( for Lua - https://github.com/HaxeFoundation/haxe/actions/runs/4628159873/jobs/8186949421#step:11:386) failed, but it's hard for me to test it on Windows. All other things work. The only other major change that could be made is the modPow() function, which is currently slow and can be a problem for generating primes (for RSA keys for example)

must be work correctly and that enough
