### ISSUE TITLE
Typed exceptions are no longer caught on certain targets

### ISSUE THREAD

**Issue by Oxdeception** [HaxeFoundation/haxe#11265]
Appears to be a regression in 4.3.0, works correctly in 4.2.5

Minimal Example

[Online](https://try.haxe.org/#6E6E4340)
```haxe
import haxe.ValueException;
import haxe.Unserializer;

class Main {
    static function main() {
        try {
            Unserializer.run("");
        } catch (e:ValueException) {
            trace("caught ValueException");
        } catch (e) {
            trace("did not catch");
            trace(Type.getClassName(Type.getClass(e)));
        }
    }
}
```

Catches correctly in
- Java
- Jvm
- JavaScript
- Flash
- Python

Does not catch correctly in
- C++
- HashLink
- Eval
- Neko

**Comment by kLabz** [comment]
Bisected to fb52486011c01d95e2a5c510571a9203cb53783f / #10519
