### ISSUE TITLE
@:structInit and Json.parse inconsistent behaviour

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#11260]
Creating new class ```User``` and parse data ( with Json.parse )  gives wrong results for  eval and Hashlink ( for haslink crashed) .
Correct ones for Javascript and Neko.
Example code: ( https://try.haxe.org/#568689b2 )
```haxe
@:structInit class User {
	public var name:String;
	public var age:Int = 30;

	public function new(?name:String, ?age:Int) {
		this.name = name ?? 'Bob';
		this.age = age ?? 29;
	}
}


class Test {
  static function main() {
    var data:User =   haxe.Json.parse('{"name":"Lemon","age":12}');
    trace("Name: "+data.name);
  }
}
```

**Comment by kLabz** [comment]
Probably because it's not using the constructor at all and is just happily feeding `Dynamic` data into your `User` typed var. 
(notice how it gives the same result without `@:structInit`)

iirc `@:structInit` only works with object literals

**Comment by Simn** [comment]
Yes, this just assigns an object to a class, which isn't going to work on normal targets.

**Comment by flashultra** [comment]
Thank you for the comments.
~~One question, will it be accepted pull request changing Json parse to assign values to vars/methods , if user add instance class ?~~
~~For example, changing parse method in JsonParser to~~
	~~static public inline function parse<T>(str:String, instance:Class<T>):T {~~
		~~return new JsonParser(str).doParse(instance);~~

~~So this ``` var data:User =   haxe.Json.parse('{"name":"Lemon","age":12}', User );```  will works correctly ( it will assign name and age to the vars with the same names.~~
