### ISSUE TITLE
Null coalescing have different type checking behavior from "normal" null check

### ISSUE THREAD

**Issue by Kallekro** [HaxeFoundation/haxe#11279]
I would expect type checking to work the same when using null coalescing. 

However, see the following example:
```haxe
interface IMyInterface {}

class MyClass implements IMyInterface {
    public function new() {}
}

function foo(x:Null<IMyInterface>) {
    final a = x != null ? x : new MyClass(); // Works as expected
    final b = x ?? new MyClass();            // Doesn't compile
}
```
Output:
```
[ERROR] Test.hx:9: characters 12-13

 9 |  final b = x ?? new MyClass();
   |            ^
   | Null<IMyInterface> should be MyClass
```

As you can see, the "normal" null check, the type is IMyInterface, and compiles fine. 
But in the next line, using the equivalent null coalescing syntax, the resulting type is MyClass, so it fails to compile.

I'm assuming this is a bug.

**Comment by Simn** [comment]
See #11197

**Comment by Kallekro** [comment]
Sorry, only searched for coalescing so missed this. 
But great that it has been fixed :)
