### ISSUE TITLE
Is @:persistent limited to primitive types?

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#11277]
The docs [here](https://haxe.org/manual/macro-persistent-variables.html) for persistent variables say that "certain values" can be saved between compilations. They don't specify that it has to be a primitive value, or serializable, or anything like that. So I tried making an instance of a class @:persistent, and it isn't working. It's set to null at the start of every compilation with the `--connect` flag and the server `--wait`ing in another terminal.

So is there a limitation to the types/values that can be persistent? Can someone explain it to me, and can the docs be updated to show this? Or are class instances meant to be supported and there's a bug or I'm doing something wrong?

The class I'm trying to preserve looks like this:

```
import haxe.macro.Expr;

typedef CachedFile = {
    path:String,
    loadedFiles:Array<String>,
    timeLastCompiled:Date,
    compiledState:KissState, // KissState is defined by a typedef and contains maps of function pointers
    compiledCode:Null<ReaderExp>  // ReaderExp is a typedef that contains an enum value
};

class KissCache {
    var cachedFiles:Map<String,CachedFile> = [];
    var cachedExps:Map<String,Expr> = [];

    function new() {}
}
```

So I could refactor to store some of the data in other ways, but I basically need function pointers and haxe.macro.Expr to be persistable.

EDIT: This is using haxe 4.3.1

**Comment by kLabz** [comment]
I have no issues using this class as persistent data, so I'm not sure what you're doing wrong.

```haxe
import haxe.macro.Expr;

class Macro {
	@:persistent static var kiss:KissCache;

	// Called with --macro Macro.init()
	public static function init() {
		trace("Hello macro!");
		if (kiss == null) kiss = new KissCache();
		kiss.foo();
	}
}

typedef CachedFile = {
	path:String,
	loadedFiles:Array<String>,
	timeLastCompiled:Date,
}

class KissCache {
	var i = 0;
	var cachedFiles:Map<String,CachedFile> = [];
	var cachedExps:Map<String,Expr> = [];

	public function new() {
		trace("new"); // will only evaluate the first time (and every time the module is invalidated)
	}

	public function foo() {
		cachedFiles.set(Std.string(i++), null);
		for (k => _ in cachedFiles) trace(k); // will print one more item at each compilation
	}
}
```

**Comment by Simn** [comment]
Closing due to lack of response.
