### ISSUE TITLE
Uninitialized class variable in constructor causes incorrect behavior

### ISSUE THREAD

**Issue by johhnry** [HaxeFoundation/haxe#11292]
Hi,

Here is a simple example:

```haxe
// Main.hx

class Test {
  var attr: Int;

  public function new() {}

  public function plusOne() {
    return attr + 1;
  }
}

class Main {
  static public function main() {
    trace(new Test().plusOne());
  }
}
```

```shell
$ haxe --js main.js -m Main Main.hx
$ node main.js

Main.hx:13: NaN
```

Why does the above code compiles? It should warn that the `attr` variable is not assigned in the constructor isn't it? Does it makes any sense?

For example TypeScript has that feature and does not compile:

```typescript
class Test {
    attr: number;
}

// => Property 'attr' has no initializer and is not definitely assigned in the constructor.
```

But I just saw that Java has the same issue:

```java
class Test {
  Integer attr;

  Test() {}

  int plusOne() {
    return attr + 1;
  }
}

public class Main {
  public static void main(String[] args) {
    System.out.println(new Test().plusOne());
  }
}

// Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.attr" is null
// 	at Test.plusOne(Main.java:5)
//	at Main.main(Main.java:11)
```

Also a similar issue on Facebook's Flow:

https://github.com/facebook/flow/issues/650

Thanks!

**Comment by Simn** [comment]
You can get this kind of information by using `@:nullSafety`, but it's not the default behavior and probably won't be for a while.

**Comment by johhnry** [comment]
@Simn Thanks for the answer, I'll try that!

**Comment by RblSb** [comment]
You can also use `final` instead of `var` for immutable fields, since it has constructor initialization checks.
