### ISSUE TITLE
Define type with module dependency + @:build : "Type Not Found" using Context.getType()

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11297]
Hej,

I stuck with that for hours now and can't see where does it come from.

Let's say I have a `@:build( Macro.build() )` on a class.
Inside `Macro.build` I only get a type named `A` (which is a module `Test`) using `Context.getType( "A" )`
Then, in the `Context.onAfterTyping` callback, I define a new type with `Context.defineType` on which I also put `@:build( Macro.build() )`. (When I define this type, I give it module dependecy of my type `A` ... I don't know if it's important here but maybe, so they are both in the same module...)
The first time build process runs, it reachs correctly the `A` type, but the second time (for the new defined type), it throws `Uncaught exception Type not found 'A'`
It only works the second time, when I do `Context.getType( "Test.A" )` instead of Context.getType( "A" ).

Is there a reason for that please or it's a bug ?

I have a minimal example here : https://try.haxe.org/#fE9E086A

Thx for reading

**Comment by back2dos** [comment]
That's how modules work. Type `A` is defined in module `Test`, so outside of that module, you have to either:

1. refer to it by fully qualified name, i.e. `Test.A`.
2. import it (i.e. `import Test;` or `import Test.A;`)
3. use [`Context.getModule('Test')`](https://api.haxe.org/haxe/macro/Context.html#getModule) and grab it from the returned types (particularly useful if you're trying to access a private subtype).

You could also move `A` to its own module in `A.hx` and then simply refer to it as `A` from everywhere.

**Comment by filt3rek** [comment]
Hej Juraj,

I hope you're fine and thanks for taking time to answer !

I agree if `Context.getType( "A" )` didn't work at all but it does work the first time build macro context is running and just doesn't work the second time, why ?

**Comment by filt3rek** [comment]
Ok I've understood something : when using `haxe.macro.Context.defineType()` with module dependency, it doesn't "place" the new type inside this module...
How can we define a new type and place it in an existing module please ?

__Edit__ : I tried to put the module inside the `pack` on the type declaration, it seems to work a half : the module of the new type is Test but Haxe mix things then and it's not working better : https://try.haxe.org/#552C2e86

**Comment by kLabz** [comment]
> How can we define a new type and place it in an existing module please ?

`Context.defineModule(cl.module, [newT]);`
https://try.haxe.org/#7d2C7e94

(I know, this isn't intuitive at all :sweat_smile:)

**Comment by filt3rek** [comment]
Thx Rudy !
So doing that, it won't "destroy" the yet existing types in this module right ?

**Comment by Simn** [comment]
We should definitely disallow defining types into existing modules for Haxe 5, if we didn't do that yet.

**Comment by kLabz** [comment]
> We should definitely disallow defining types into existing modules for Haxe 5, if we didn't do that yet.

We didn't, but that should be easy enough:
https://github.com/HaxeFoundation/haxe/blob/development/src/typing/macroContext.ml#L505-L513

**Comment by filt3rek** [comment]
I use it with `onAfterTyping` in order to kind of "delay" the build macro when needed. 
Will Haxe 5 have something to do this ? (reorder build macros ?)

**Comment by kLabz** [comment]
Depends what you mean exactly with reorder build macros

**Comment by filt3rek** [comment]
Sometimes I need a `@:build` on a class runs after another one `@:build` ... Idk if it's more clear ...

**Comment by kLabz** [comment]
That is planned, yeah (as long as it's on the same type).

**Comment by filt3rek** [comment]
Hmm I meant on 2 or more different types... 
Let's say a build macro on A has to collect the fields that are in another type B, but B has also a build macro that add or modify its fields.. I want build macro on B runs first because if not the build that is on A will get fields from B that will not be already added/modified ...

**Comment by kLabz** [comment]
That will likely stay undefined build order.

**Comment by kLabz** [comment]
But you can make sure a type is built (entirely) before another one: https://try.haxe.org/#2Afb983e

```
Macro.hx:5: Building,TInst(B,[])
Macro.hx:5: Building,TInst(A,[])
Macro.hx:16: Done building,TInst(A,[])
Macro.hx:16: Done building,TInst(B,[])
```

**Comment by filt3rek** [comment]
Thx I'll try that ;)
