### ISSUE TITLE
Default constructors?

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/haxe#11309]
Im not sure if this is the right place as its not really an issue, more of a question / possibly feature request:

Is there a reason why default constructors dont exist in haxe? For example:

```haxe
class ReportedTime {
    @:attribute                 public var status:String;
    @:xmlName(PeriodStartDate)  public var periodStartDate:String;
    @:xmlName(PeriodEndDate)    public var periodEndDate:String;

    @:xmlName(TimeInterval)     public var timeIntervals:Array<TimeInterval>;
    @:xmlName(AdditionalData)   public var additionalData:AdditionalData;
    @:xmlName(ApprovalInfo)     public var approvalInfo:ApprovalInfo;

    public function new() {
    }
}
```
Would be nicer as just:
```haxe
class ReportedTime {
    @:attribute                 public var status:String;
    @:xmlName(PeriodStartDate)  public var periodStartDate:String;
    @:xmlName(PeriodEndDate)    public var periodEndDate:String;

    @:xmlName(TimeInterval)     public var timeIntervals:Array<TimeInterval>;
    @:xmlName(AdditionalData)   public var additionalData:AdditionalData;
    @:xmlName(ApprovalInfo)     public var approvalInfo:ApprovalInfo;
}
```
I know nothing about the internal workings of the compiler (and less about OCaml), but quite often in my own macros i add default constructors if there isnt already a constructor, the downside being that you need to an @:build macro. 

Obviously this is hugely trivial, but i suppose im more interested in if there _is_ a reason why they dont already exist.

Cheers,
Ian

PS: feel free to close / delete this issue - its really not a bother adding 3 more lines to each class :)

**Comment by kLabz** [comment]
See #10168 (tl;dr that wouldn't be added by default to all classes)

I get this could be made slightly easier to have an empty constructor be generated for specific classes with some metadata, but would it really be less hassle than adding the constructor? (especially when going back to that class later and actually implementing the constructor)

**Comment by ianharrigan** [comment]
Interesting, thanks for the link. This is a good point:

> If any case, changing this would silently change the intended behavior of a lot of existing code, since right now, "no constructor is declared" means "you shouldn't be able to construct this".

> I get this could be made slightly easier to have an empty constructor be generated for specific classes with some metadata

Yeah, i think at that point you are just basically just saying "instead of writing an explicit constructor, write explicit metadata that will create a constructor", which as you say, is basically the same thing. Also, with the "new" snippt in vscode it takes about 4 keystrokes to generate a constructor.

It was more about the "noise" (although granted there isnt exactly much), and if there is some technical reason why they dont exist already - i certainly prefer my second snippet above to the first, but its not a hill i would die on :)

Im going to close this (in the spirit of reducing noise :D )
