### ISSUE TITLE
Pull requests for 4.3 Hotfix (part 3)

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#11306]
## 4.3.3

* [x] https://github.com/HaxeFoundation/haxe/commit/62bdf35ee8894cb38541db5622ac7c88a6fd501c
* [x] https://github.com/HaxeFoundation/haxe/commit/44c9abdbb176c261d42822e2e4003b4727054aff
* [x] https://github.com/HaxeFoundation/haxe/commit/536c388f623ad55578764f3c1b7b432ba2694337 / #11307
* [x] https://github.com/HaxeFoundation/haxe/commit/3a5140e63bd5f5583f5a80ad89d5d196538683bd
* [x] https://github.com/HaxeFoundation/haxe/commit/269fef478883890e15205f5f7e5295921567f40a
* [x] https://github.com/HaxeFoundation/haxe/commit/71c41a0966cd3ee7b84c4214f0d4346ecc28ac88
* [x] #11257 (compile time fix) + https://github.com/HaxeFoundation/haxe/commit/804e27ef0004578c2d7b401ad4fad7801ce2d06c (runtime fix)
* [x] https://github.com/HaxeFoundation/haxe/commit/0fe4dd7fe414df827aa638ec8f4980659bdbd791
* [x] https://github.com/HaxeFoundation/haxe/commit/d69b67fede5d7fe747341449039bb863e06ae3c4
* [x] #11377

### Notes

Test haxe benchmarks with 4.3_bugfix before releasing

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/commit/3a5140e63bd5f5583f5a80ad89d5d196538683bd

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/commit/71c41a0966cd3ee7b84c4214f0d4346ecc28ac88

**Comment by kLabz** [comment]
> [71c41a0](https://github.com/HaxeFoundation/haxe/commit/71c41a0966cd3ee7b84c4214f0d4346ecc28ac88)

Technically not a 4.3 regression but I suppose it wouldn't hurt

**Comment by kLabz** [comment]
Guess https://github.com/HaxeFoundation/haxe/commit/0fe4dd7fe414df827aa638ec8f4980659bdbd791 wouldn't hurt either.

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/commit/44e02592ab6d49c86b5c33a491b826d05ed67630
https://github.com/HaxeFoundation/haxe/commit/c2479a0aa2aa9903790aafc4d5643214b7a841ae
