### ISSUE TITLE
TDAbstract & haxe.macro.Printer 4.3.2 regression

### ISSUE THREAD

**Issue by dazKind** [HaxeFoundation/haxe#11307]
I stumbled upon this since I generate Abstracts in a macro in https://github.com/HxGodot/hxgodot:

4.3.2 introduced a [change to haxe.macro.TypeDefKind](https://github.com/HaxeFoundation/haxe/commit/e88ed6099f7dbea832c5719d01cdf73a9e5994ca#diff-bfba04ce1ed12597d92a96797ca576a648ed7f202de925316c45c8ef16017130R1007) to include AbstractFlags as a new parameter in the enum. The param is optional and can be null(intended?), however it is [used in the Printer here](https://github.com/HaxeFoundation/haxe/commit/e88ed6099f7dbea832c5719d01cdf73a9e5994ca#diff-666b76450ba8028b53f28e60393f028d33ee467384c530873dd7bd4650d833abR393). 

If it is null there, it will fail with a Null Access.

I can fix this on my end by adding the new param but in order to support pre-4.3.2 I also need a conditional with a version check now.

I prepared a sample for you to check out here: https://try.haxe.org/#5D97B27E

**Comment by kLabz** [comment]
Damn.. I wish we had null safety enabled for std, would have covered this.

**Comment by kLabz** [comment]
Fixed with [536c388](https://github.com/HaxeFoundation/haxe/commit/536c388f623ad55578764f3c1b7b432ba2694337), will be included in 4.3.3
I don't have a great solution for 4.3.2 in the meantime..

Sorry about that :/
Feel free to reopen if you expect something more
