### ISSUE TITLE
Invalid access to 7

### ISSUE THREAD

**Issue by helpmeiguess** [HaxeFoundation/haxe#11308]
i dont use github, like ever, but this error is annoying as fuck and ive seen other people struggle with it too.
![image](https://github.com/HaxeFoundation/haxe/assets/81779430/ad6d1ebc-b4f6-471b-92d5-ee7f7ebd903f)

this is actually all the info i have on this error, there was nothing that really started it, it just. appeared. one day.
i dont think its at runtime as it shows up before the app would even have time to start (just like half a second after it shows creating library applicationmain), but idk it might be.
other people ive talked to that had this error said it disappeared after a day or two. 
also, im not sure if this error is part of haxe or lime, so i dont know if im even reporting it in the right place.
help.
thanks.

**Comment by Zoardedz** [comment]
Maybe try removing the compilation folder and then compile again? I don't know what fixed it for me when it happened honestly

**Comment by helpmeiguess** [comment]
> Maybe try removing the compilation folder and then compile again? I don't know what fixed it for me when it happened honestly

tried as per request of another person with the error, no help.

**Comment by Simn** [comment]
I can't tell if this is a run-time error or not. Is ApplicationMain.exe actually created or does it die trying to do so? It could be something arcane like the linker not being able to write the file.

**Comment by kLabz** [comment]
Also, what version of Haxe are you using?

**Comment by Simn** [comment]
Closing due to lack of response.
