### ISSUE TITLE
CLI Sys.getChar doesn't work on OSX

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#11312]
- Haxe Compiler 4.3.2 - (C)2005-2023 Haxe Foundation
- MacBook Pro, Ventura 13.5.2 (22G91)

```
class Main {
	public function new() {
		trace("Do you want to continue? (y/n)");
		var char:Int = Sys.getChar(true);
		trace(char);
	}

	static public function main() {
		var app = new Main();
	}
}
```

<img width="613" alt="Screenshot 2023-09-16 at 13 04 50" src="https://github.com/HaxeFoundation/haxe/assets/907219/457f5800-0205-4292-84df-e8b6cda22188">

https://github.com/MatthijsKamstra/haxesys/blob/master/docs/12cli_input/code/src/Main.hx

**Comment by madneon** [comment]
Have you tried running the compiled program from shell directly? (`neko app.n` or something)
It looks like invoking test run from .hxml file is buggy, see: #11424

**Comment by MatthijsKamstra** [comment]
@madneon is correct, running directly fixed the problem.

I will close this issue add a +1 to #11424
