### ISSUE TITLE
Nothing works 

### ISSUE THREAD

**Issue by RonyxDumb** [HaxeFoundation/haxe#11326]
Lately, haxe doesn't work anymore. It reports many meaningless errors, as everything is correctly programmed and imported.
I have the latest version of Haxe installed.

![burrepto](https://github.com/HaxeFoundation/haxe/assets/104029827/a3407f52-f03f-4e7a-b91a-a020a33ef58a)

Sometimes the language works, but returns the error "type not found: Main"

![errr](https://github.com/HaxeFoundation/haxe/assets/104029827/0e8ae23b-8f97-4b69-8608-8979d82a1458)

**Comment by moxie-coder** [comment]
try reinstalling haxe 4.2.5, seems like your installation might've gotten corrupted

**Comment by kLabz** [comment]
I don't think it's an issue with Haxe itself (in non-lime setup that would be an issue with hxml file selection).
Does lime have some clean build functionality?

**Comment by moxie-coder** [comment]
> I don't think it's an issue with Haxe itself (in non-lime setup that would be an issue with hxml file selection). Does lime have some clean build functionality?

yeah, try lime clean html5 @RonyxDumb

**Comment by kLabz** [comment]
Also iirc lime has a vscode extension, you might not be able to build properly without it.

**Comment by RonyxDumb** [comment]
ok thank you all
