### ISSUE TITLE
FNF SOURCE CODE

### ISSUE THREAD

**Issue by fnfusermood** [HaxeFoundation/haxe#11340]
So... i was editing my code after it told me repeatingly about errors in HScript, then i got this.

source/psychlua/CallbackHandler.hx:48: characters 18-33 : Class<llua.Lua_helper> has no field sendErrorsToLua
export/release/windows/haxe/ApplicationMain.hx:153: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/linc_luajit/git/llua/State.hx:11: characters 24-49 : You cannot access the cpp package while in a macro (for cpp.RawPointer)
C:/HaxeToolkit/haxe/lib/linc_luajit/git/llua/Lua.hx:4: characters 8-18 : ... referenced here
E:\Downloads\PsychEngine-Windows64\PsychEngine\FNF-PsychEngine-main\FNF-PsychEngine-main\source\import.hx:10: characters 8-16 : ... referenced here
E:\Downloads\PsychEngine-Windows64\PsychEngine\FNF-PsychEngine-main\FNF-PsychEngine-main\source\import.hx:4: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/media/AudioSource.hx:138: characters 53-100 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/media/Sound.hx:28: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/utils/Assets.hx:9: characters 8-26 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/text/Font.hx:4: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/text/_internal/TextEngine.hx:9: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/_internal/CairoTextField.hx:3: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/CairoRenderer.hx:11: characters 8-47 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/_internal/CairoGraphics.hx:6: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/_internal/Context3DGraphics.hx:3: characters 8-46 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/DisplayObjectRenderer.hx:4: characters 8-50 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/filters/BitmapFilter.hx:6: characters 8-44 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/BitmapData.hx:14: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/desktop/Icon.hx:4: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/filesystem/File.hx:6: characters 8-27 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/events/InvokeEvent.hx:5: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/Application.hx:15: characters 8-33 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/utils/_internal/Lib.hx:6: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/DisplayObject.hx:6: characters 8-34 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/utils/_internal/TouchData.hx:3: characters 8-36 : ... referenced here
C:/HaxeToolkit/haxe/lib/openfl/9,3,1/src/openfl/display/Stage.hx:7: characters 8-40 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/ui/Window.hx:15: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/graphics/RenderContext.hx:4: characters 8-22 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/app/Application.hx:3: characters 8-35 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/system/ThreadPool.hx:4: characters 8-28 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/app/Future.hx:4: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/utils/Bytes.hx:10: characters 8-23 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/utils/BytePointer.hx:5: characters 8-24 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/graphics/opengl/GL.hx:8: characters 8-30 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/graphics/opengl/GLBuffer.hx:5: characters 8-31 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/_internal/backend/native/NativeCFFI.hx:4: characters 8-37 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/lime/system/System.hx:4: characters 8-48 : ... referenced here
C:/HaxeToolkit/haxe/lib/lime/8,1,0/src/haxe/Timer.hx:219: characters 8-26 : ... referenced here
C:\HaxeToolkit\haxe\std/haxe/MainLoop.hx:33: characters 50-60 : ... referenced here

PLS HELP ME!!

**Comment by moxie-coder** [comment]
this isn’t the right place to make this issue

**Comment by Simn** [comment]
Indeed, please report this to https://github.com/ShadowMario/FNF-PsychEngine
