### ISSUE TITLE
compile code to java, the float will become double

### ISSUE THREAD

**Issue by colby8265** [HaxeFoundation/haxe#11348]
After i compile code to java, the float will become double, but double arithmetic is not always 100% accurate. how can i fix this?

**Comment by Simn** [comment]
Haxe's Float is specified to be IEEE 64bit float, which aligns with Java's double. I don't know what you mean by "not always 100% accurate" but either way this is not a Haxe issue.

**Comment by colby8265** [comment]
> Haxe's Float is specified to be IEEE 64bit float, which aligns with Java's double. I don't know what you mean by "not always 100% accurate" but either way this is not a Haxe issue.

I want to change double to BigDecimal, cause i remember there is calculation problem in java when two variable are double.  Like this [Retain precision with double in Java](https://stackoverflow.com/questions/322749/retain-precision-with-double-in-java)

**Comment by kLabz** [comment]
That's generally applicable to Haxe Float, though. Avoid it if you want accurate arithmetic

**Comment by colby8265** [comment]
> accurate arithmetic

Yes, i want accurate arithmetic. Do you know  how to do this?
