### ISSUE TITLE
How to do precise floating point arithmetic

### ISSUE THREAD

**Issue by colby8265** [HaxeFoundation/haxe#11349]
My source hx Function
```
    static function getPNL(markPrice:Float, avgFilledPrice:Float, filledAmount:Float):Float {
        return (markPrice-avgFilledPrice)*filledAmount;
    }
```
after compile to Java
```
	public static double getPNL(double markPrice, double avgFilledPrice, double filledAmount)
	{
		//line 59 "/Users/colby/Documents/ContractMath/src/Main.hx"
		return ( (( markPrice - avgFilledPrice )) * filledAmount );
	}
```
All float variable transfer to Double. As i know , Double can not do precise floating point arithmetic.

I read the offical document https://code.haxe.org/category/beginner/numbers-floats-ints.html.
Floating point arithmetic is not always 100% accurate
```
var value = 0.1 + 0.2; // 0.30000000000000004 
````
but here dont metion how to do precise floating point arithmetic
Who know how to fix this?

**Comment by nadako** [comment]
This is not a good place for such questions (better use community channels like Discord or the [forum](https://community.haxe.org/)). However what you're looking for is some kind of implementation of "Decimal" rather than a standard floating point number.  Here's one: https://github.com/fponticelli/thx.core/blob/master/src/thx/Decimal.hx

**Comment by colby8265** [comment]
> This is not a good place for such questions (better use community channels like Discord or the [forum](https://community.haxe.org/). However what you're looking for is some kind of implementation of "Decimal" rather than a standard floating point number. Here's one: https://github.com/fponticelli/thx.core/blob/master/src/thx/Decimal.hx

Thank you
