### ISSUE TITLE
multittype ds fail

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#11357]
following this tutorial 
https://nadako.github.io/rants/posts/2013-11-10_haxe-multi-type-abstracts.html
as I built up the complexity towards my use case which was failing, I found if fails here.
```
import haxe.ds.Vector;
function main() {
  var ai = new Array<Int>();
  for( i in 0...10 ){
		ai[i]=i;
  }
  var a = new A<ArrInt>(ai);
  trace( a );
  var vi = new Vector<Int>(10);
  for( i in 0...10 ){
		vi.set(i,i);
      }
    var a2 = new A<VecInt>(vi);
  trace( a2[3] );
  }
typedef ArrInt = Array<Int>;
typedef VecInt = Vector<Int>;
interface IA<T>
{
  public function set( index: Int, value:Int ): Int;
	public function get( index: Int): Int;
  public function zero( len: Int ): T;
}

class ArrIntA implements IA<ArrInt>
{
  var val: ArrInt;
  public function new( val: ArrInt ) {
    this.val = val;
  }
  public inline function set( index: Int, value: Int ): Int {
		val[ index ] = value;
    return value;
  }
  public inline function get( index: Int ): Int {
		return val[ index ];
  }
  public inline function zero( len :Int ): ArrInt {
    for( i in 0...len ){
			val[i] = 0;
    }
    return this.val;
  }
}
class VecIntA implements IA<VecInt>
{
  var val:VecInt;
	public function new(val:VecInt) {
    this.val = val;
  }
  public inline function set( index: Int, value: Int ): Int {
		val[ index ] = value;
    return value;
  }
  public inline function get( index: Int ): Int {
		return val[ index ];
  }
  public inline function zero( len :Int ): VecInt
  {
    for( i in 0...len ){
			val[i] = 0;
    }
    return this.val;
  }
}
@:forward
@:multiType
abstract A<T>(IA<T>)
{
    public function new(a:T);

    @:to static inline function toArrIntA(t:IA<ArrInt>, val:ArrInt, len:Int ):ArrIntA
    {
        var arr = [];
        var arrI = new ArrIntA( arr );
        arrI.zero( len );
        return arrI;
    }
    @:to static inline function toVecIntA(t:IA<VecInt>,val:VecInt, len2:Int):VecIntA
    {
        var v = new Vector( len2 );
        var vec = new VecIntA( v );
        vec.zero( len2 );
        return vec;
    }
  @:arrayAccess
    public inline function set( index: Int, value: Int ): Int {
		return this.set( index, value );
  }
  @:arrayAccess
  public inline function get( index: Int ): Int {
		return this.get( index );
  }
}
```
https://try.haxe.org/#72c9b849
 79 |     @:to static inline function toVecIntA(t:IA<VecInt>,val:VecInt, len2:Int):VecIntA
  - |       [...]
 85 |     }
    |
    | (t : IA<VecInt>, val : VecInt, len2 : Int) -> VecIntA should be (IA<Unknown<0>>, Unknown<1>) -> Unknown<2>

**Comment by kLabz** [comment]
Your `@:to` functions have incorrect arguments
You can make it work with:
```haxe
	@:to static inline function toArrIntA(t:IA<ArrInt>, a:ArrInt):ArrIntA {
		var val = 0, len = 0; // TODO

		var arr = [];
		var arrI = new ArrIntA(arr);
		arrI.zero(len);
		return arrI;
	}

	@:to static inline function toVecIntA(t:IA<VecInt>, v:VecInt):VecIntA {
		var val = 0, len2 = 0; // TODO

		var v = new Vector(len2);
		var vec = new VecIntA(v);
		vec.zero(len2);
		return vec;
	}
```
https://try.haxe.org/#273937ee

**Comment by nanjizal** [comment]
ah ok... thanks for the explaining, makes more sense now...
but my aim was to create an virtual image so some how I need to init the multitype at the correct size for ds that need this ( even array can use length on cpp to be faster ), it would be heavy to init a Vector at zero and have an abstract above to then resize it, given that there are a lots of these created in complex image manipulation.

**Comment by nanjizal** [comment]
in theory could resize(w*h) after init or pass a sized structure but both feel awkward?

**Comment by nanjizal** [comment]
was trying to wrap something like https://gist.github.com/nanjizal/e294685691ba380a78529d90b8d191aa my GenericStack code may need work it was more a prove of possibility than ideal use!

**Comment by nanjizal** [comment]
I guess to add to complexity I wanted to define abstract class instead of interface which may work and then pass an abstract type and use array access but maybe that is too tricky.

**Comment by nanjizal** [comment]
the problem that for many cases this requires ```Null<T>``` be created and a separate init method used after? So we can't avoid nulls.

**Comment by Simn** [comment]
I don't think there's a Haxe issue here.

**Comment by nanjizal** [comment]
Thanks Simn and KLabs for taking a look, and providing better understanding of the working approaches.

Thoughts..
it would be ideal for an error message to not only fail on the second `static to` method, as it suggests init prroperties can be set, currently the first use works, with second failing. This can be considered undefined behavour.. but it is misleading and suggests a strange type hole and misleads the user. Considerations, although understandable not a priority..

- Better Multitype approach.
- Ideal to allow passing the init properties.
- Less ideal to error if even the first 'static to' tries to pass additional parameters. It is just confusing that the first one compiles and runs, but second doesn't.  
- Behavour could be documented with some clarity behind reasoning, which I don't fully understand, but I guess your not keen to publicise Multitype as I suspect it has many edge cases which are likely unknown.
