### ISSUE TITLE
[jvm] Cannot extend by using an interface

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11352]
**Error message:**
```
./generated/build/minecraft/minecraft-merged-project-root-1.19.2-loom.mappings.1_19_2.layered+hash.799963873-v2.jar@net/minecraft/commands/CommandBuildContext$1.class:1: character 1 : Cannot extend by using an interface
```

This error is thrown upon including a JAR as an extern. The JAR I am importing is rather large but I have an educated guess about what the the root cause may be.

In `CommandBuildContext.class` this line of code exists:

```java
            @Override
            public Optional<? extends HolderSet<T>> get(TagKey<T> key) {
```

Notably, `HolderSet` is an interface but the `extends` keyword is used. This is apparently standard; in Java, the `implements` keyword is [expressly forbidden in type parameters](https://stackoverflow.com/questions/976441/why-is-extends-t-allowed-but-not-implements-t).

Could the fact that `extends` is being used here be messing with Haxe?

Let me know if a minimal reproduction is necessary to fix this bug.

**Comment by Simn** [comment]
I'm not sure if that's the right guess because I think we treat type parameter extensions as constraints, which should give different errors if anything. I've changed the error in the linked commit to actually print which classes are involved here. See if that reveals anything!

**Comment by EliteMasterEric** [comment]
```
Cannot extend by using an interface (net.minecraft.commands.CommandBuildContext_1 extends net.minecraft.core.HolderLookup_RegistryLookup)
```

The issue is with `CommandBuildContext_1` rather than `CommandBuildContext`

Analyzing the code more, it seems the issue MIGHT be with the line before the one I cited:

```java
        return new HolderLookup.RegistryLookup<T>(this.registryAccess.registryOrThrow(registryResourceKey)){
```

That function was defined within an anonymous subclass of the interface `HolderLookup.RegistryLookup`, which could explain why the error is in `CommandBuildContext_1`.

An anonymous class is an expression. The syntax of an anonymous class expression is like the invocation of a constructor, except that there is a class definition contained in a block of code.

If you need a bit more context I could post the whole file (but that'd be pushing it since the source jar is deobfuscated Minecraft)

**Comment by Simn** [comment]
So you're saying there's an anonymous class inside an interface, and Haxe somehow thinks it's an interface instead of a class? That sounds like it should be quite easy to reproduce.

**Comment by EliteMasterEric** [comment]
I just attempted a reproduction under that simple circumstance but didn't find an error. Will need to look harder it seems.

**Comment by EliteMasterEric** [comment]
Okay, I found the issue.

Turns out, `HolderLookup.RegistryLookup` was an interface and then I replaced the library JAR with a different version where `HolderLookup.RegistryLookup` was a class.

@Simn It would be nice to have some sort of quick check to ensure that an extern isn't created that conflicts with the underlying type (so throw a compile error when making an `extern class` when the `@:native` is known to be an `interface`, for example.)
