### ISSUE TITLE
Uncaught Sys_error in messageReporting.ml

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11364]
See https://github.com/HaxeFoundation/haxe/actions/runs/6781673295/job/18433367975#step:13:39 on this branch: https://github.com/HaxeFoundation/haxe/tree/out_of_curiosity_(don't_freak_out)

While the underlying problem is clearly something else, it should not fail like this for invalid file paths.

**Comment by kLabz** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/656f98aec440ad0f17170d41964bd0a8f2f54c10 (development) and https://github.com/HaxeFoundation/haxe/commit/2c671fb866e150c2d40787bc1581134b08db8c5e (4.3_bugfix, which was also missing a previous fix from nightlies making the issue easier to repro on 4.3.x)
