### ISSUE TITLE
[JVM] Function arguments with type parameters not generating correctly

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11362]
## Background

I am working with Minecraft modding, which relies on many quirks that result in requiring a precise output from an included JAR.

One example is the event system, which applies to functions with a specific annotation applied to them; the annotation inspects the type of the argument passed to it, and as such the argument must be EXACT. A function taking `RegistryEvent<Item>` will be called when the game tries to register an item, while taking `RegistryEvent` or `RegistryEvent<java.lang.Object>` will call it when the game tries to register ANY type.

## Problem

Exporting a module with the JVM target, containing a function, whose argument has a type parameter, omits that type parameter from the generated class.

## Example

```haxe
	static function doTheThing(input:CoolClass<String>):Void {
		trace(input.toString());
	}
```

Upon decompiling the compiled JAR, this is what I get (I use Luyten to decompile and inspect JARs)

![image](https://github.com/HaxeFoundation/haxe/assets/4635334/232257d6-175a-467b-8115-dad02992169a)

For comparison, here is the same function generated in pure Java.

![image](https://github.com/HaxeFoundation/haxe/assets/4635334/f7266ef7-55a1-4a6e-83b2-24a7b8801e37)

## Minimal Reproduction

https://github.com/EliteMasterEric/Issue-11362

**Comment by Simn** [comment]
This is about the absence of the [signature attribute](https://docs.oracle.com/javase/specs/jvms/se18/html/jvms-4.html#jvms-4.7.9). I'm never quite sure in which cases this is supposed to be generated and in which it's not. This is probably a case of "look at what Java does and do the same".

**Comment by Simn** [comment]
See if that helps with your use-case. We now generate the signature if it's different from the descriptor. This seems quite logical, so it's probably wrong.

I'd like to add a test for this, but I don't know how to trigger any actual failure. The specification mentions this:

```
Oracle's Java Virtual Machine implementation does not check the well-formedness of Signature attributes during class loading or linking. Instead, Signature attributes are checked by methods of the Java SE Platform class libraries which expose generic signatures of classes, interfaces, constructors, methods, and fields. Examples include getGenericSuperclass in Class and toGenericString in java.lang.reflect.Executable.
```

Would be good to have a small test case that fails before this commit.

**Comment by EliteMasterEric** [comment]
I tested this new build and it seems to work well, except for one edge case.

If you leave the type parameter out intentionally, so using a raw type as an argument, it should leave the parameter off in generated code instead of using `java.lang.Object`. It should only use `java.lang.Object` if the original code specified it, and exclude the "signature attribute" if the method takes a raw type as an argument.

**Comment by Simn** [comment]
Omitting the attribute doesn't sound right, you could have cases where there's a raw type and a normal parameterized type.

Also, I don't think I want to add support for something that's considered deprecated even in the Java world. The problem is that this happens at type-hint level, which makes this very difficult to handle.

**Comment by EliteMasterEric** [comment]
I was messing around and got a working build by specifying a specific type parameter so I'd say this is fixed. Will let you know if I have more problems (probably by making a new issue for it).
