### ISSUE TITLE
HL/C compilation fails with Visual Studio when Haxe field is named restrict, _restrict, or __restrict

### ISSUE THREAD

**Issue by joshtynjala** [HaxeFoundation/haxe#11378]
The C code for HashLink, when generated from the following Haxe code, cannot be compiled with Visual Studio's C compiler, cl.exe. It works with MinGW's gcc (and gcc on macOS and Linux), though.

```haxe
class HlcRestrict {
	static function main() {
		new HlcRestrict();
	}

	public function new() {
	}

	public var restrict:String;
}
```

Compiled with the following options:

```hxml
--main HlcRestrict
--hl generated/HlcRestrict.c
```

cl.exe command in Visual Studio developer shell:

```sh
 cl.exe /Ox /Fe:HlcRestrict.exe -I "<hashlink>\include" -I "generated" "generated/HlcRestrict.c" "<hashlink>\libhl.lib"
```

It results in the following error:

> generated\_std/HlcRestrict.h(22): error C2208: '_String *restrict ': no members defined using this type

Same result if you change it to `_restrict` or `__restrict` (one or two underscores).

```haxe
public var _restrict:String;
```

```haxe
public var __restrict:String;
```

However, if you change it to `___restrict` with three underscores, cl.exe can successfully compile the generated C code:

```haxe
public var ___restrict:String;
```

It looks like _src/generators/hl2c.ml_ already has some code to rewrite certain field names when they conflict with C keywords, including `restrict` actually, but I guess that this behavior is specific to Visual Studio's C compiler that appears to have been missed.

**Comment by Apprentice-Alchemist** [comment]
Looks like the escaping used by HL2C will turn `restrict` into `_restrict`.
But, `_restrict` and `__restrict` are also keywords for MSVC apparently.

The best solution here is probably to do what genccp does:
prefix reserved identifiers with `_hx_`, and do the same for any identifier that starts with `__` (since according to the C standard those are also reserved).

(This page has an overview of the exact rules: https://en.cppreference.com/w/c/language/identifier)
(For an overview of MSVC specific keywords: https://learn.microsoft.com/en-us/cpp/c-language/c-keywords)

**Comment by joshtynjala** [comment]
@kLabz 

Haxe 4.3.3 fixes the issue with a field named `restrict`. Unfortunately, `_restrict` and `__restrict` still cause compilation failure with Visual Studio's cl.exe.

As far as I can tell, I don't think that any changes were made to fix `_restrict`. That one probably needs to be added to the keywords list explicitly in the `(* MS specific *)` section.

I don't know OCaml, but I was looking at this line that should have fixed `__restrict`:

```ocaml
let ident i = if (Hashtbl.mem keywords i) || (ExtString.String.starts_with "__" i) then "_hx_" ^ i else i
```

The [`ExtString.String.starts_with` docs](https://ocaml-lib.sourceforge.net/doc/ExtString.String.html#VALstarts_with) say:

> starts_with s x return true if s is starting with x.

Again, I've never touched OCaml, except to read the Haxe compiler code, but I think that you might have gotten the two arguments backwards. Maybe it should have been this instead?

```ocaml
ExtString.String.starts_with i "__"
```

**Comment by kLabz** [comment]
ahem yeah that's possible. as for _restrict, I need to add it too indeed
