### ISSUE TITLE
extern overloads cause enum identifier resolution to fail

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11372]
```haxe
  public static overload extern inline function printValue(input:String) {
    // Do something.
  }
  public static overload extern inline function printValue(input:MyEnumAbstract) {
    var value:String = input;
    printValue(value);
  }

enum abstract MyEnumAbstract(Int) {
  var ONE = 1;
  @:to
  private function toValue():String {
    switch(abstract) {
      case ONE: "One";
    }
  }
}
```

In this example, trying to call `printValue("Three")` works, trying to call `printValue(MyEnumAbstract.ONE)` works, but trying to call `printValue(ONE)` does not work. Note that the underlying type of MyEnumAbstract does not match the argument of the main call.

Getting rid of the overload and trying to rely on the implicit casting does not work either, without explicitly referring to the MyEnumAbstract type, which isn't necessary if the argument is OF the type MyEnumAbstract, which I made the overload to try and do.

**Use Case:**

I am working with an extern function whose argument is one of a set of static final constants, whose containing class needs to be imported whenever that function is used, just to get a reference to the constant value. I wanted to see if I could make an enum abstract whose enumerations can be converted to the corresponding constants, and then adding an overload to that function which takes that enum abstract and simply converts it.

**Reproduction:**
This was reproducible in TryHaxe.
https://try.haxe.org/#02771d2A

**Comment by Simn** [comment]
There's some special handling for unknown identifiers which I tracked down across 3 refactorings to this commit: https://github.com/HaxeFoundation/haxe/commit/a438571ccff868d28f0f987b365e05d04f5d38ac

The original issue is #6765. Without this change, the error message is indeed rather lengthy when making a typo:

```
source/Main.hx:14: characters 2-16 : Could not find a suitable overload, reasons follow
source/Main.hx:14: characters 2-16 : Overload resolution failed for (input : MyEnumAbstract) -> Void
source/Main.hx:14: characters 13-15 : Identifier 'ON' is not part of MyEnumAbstract
source/Main.hx:14: characters 13-15 : ... For function argument 'input'
source/Main.hx:14: characters 2-16 : Overload resolution failed for (input : String) -> Void
source/Main.hx:14: characters 13-15 : Unknown identifier : ON
source/Main.hx:14: characters 13-15 : ... For function argument 'input'
source/Main.hx:14: characters 2-16 : End of overload failure reasons
```

However, the overload handler now already merges failures that have the same messages, so if we add more `printValue` overloads it doesn't become worse:

```
source/Main.hx:19: characters 2-16 : Could not find a suitable overload, reasons follow
source/Main.hx:19: characters 2-16 : Overload resolution failed for (input : MyEnumAbstract) -> Void
source/Main.hx:19: characters 13-15 : Identifier 'ON' is not part of MyEnumAbstract
source/Main.hx:19: characters 13-15 : ... For function argument 'input'
source/Main.hx:19: characters 2-16 : Overload resolution failed for (input : Bool) -> Void
source/Main.hx:19: characters 13-15 : Unknown identifier : ON
source/Main.hx:19: characters 13-15 : ... For function argument 'input'
source/Main.hx:19: characters 2-16 : End of overload failure reasons
```

Another option might be to remember the unknown identifier error, but only emit it after all overload resolutions have failed. I'll see how difficult that is to implement.

**Comment by EliteMasterEric** [comment]
Just wanted to chime in and say that this resolves the issue, at least during compilation. I still get the error in VSCode's error checking though.

**Comment by Simn** [comment]
Hmm I'll have to check what diagnostics runs do here.

**Comment by EliteMasterEric** [comment]
False alarm on that, I rebuilt and then closed and reopened VSCode and it resolved itself.
