### ISSUE TITLE
Safe navigation is invalid for assigning variables

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#11379]
```haxe
class Main {
  static function main() {
    final test = new Main();
    test?.foo(); // ok
    test?.bool = true; // Invalid operation
  }

  public function new() {}
  public function foo():Void {}
  public var bool = true;
}
```
I think this can be supported too, like calls? Works in kotlin

**Comment by Simn** [comment]
I actually find "assign it if it's not null" a very strange concept, but the `+=` case makes sense to me. So I guess supporting both would be fine.

**Comment by Simn** [comment]
Oh right it's not about the field being `null` but the thing we're accessing the field on. So yes both cases make sense.
