### ISSUE TITLE
Unclosed monomorphs in function signature

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11381]
I randomly found this problem today in the test for #2685:

```haxe
function main() {
	var a:Int = func1(1);
	$type(func1); // (a : Dynamic) -> Int
	var s:String = func1("foo"); // Int should be String
}

function func1(a:Dynamic) {
	return a;
}
```

The problem is that the return type of `func1` remains a monomorph because those are not bound to `Dynamic`. It is instead unified with the type of `var a:Int` and thus the function itself ends up as `(a : Dynamic) -> Int`, which is just wrong.

Very related to #3033 and I still maintain that functions should not expose their monomorphs. I'll try to see what happens if we bind leftover monomorphs to `Dynamic` (and maybe `Void` for some return types?), but I expect some friction here.

**Comment by Simn** [comment]
I thought that this might work since https://github.com/HaxeFoundation/haxe/commit/fa2faa181d4db43637eee69dbbcb8cf55a4cf0cf, but it doesn't. I suspect that we create a monomorph via `setup_args_ret` before we actually setup `ctx.e`, which means it is added to a `ctx.e.monomorphs` which is then forgotten about.

**Comment by kLabz** [comment]
Nice!

Slightly related, from the updated test:

```
 6 |   p.then(x -> 10, e -> "");
   |                   ^^^^^^^
   | (e : Dynamic) -> String should be Null<js.lib.PromiseHandler<Dynamic, Int>>
```

Would `Any` work instead of `Dynamic`?
As we want to [slowly] move away from `Dynamic`, this would be nice

**Comment by Simn** [comment]
This comes from https://github.com/HaxeFoundation/haxe/commit/fa2faa181d4db43637eee69dbbcb8cf55a4cf0cf, so the situation is that there's already a `Dynamic` in the code that was unified with the monomorph. If the code in question used `Any` instead we wouldn't run into this problem in the first place.

**Comment by kLabz** [comment]
I guess my suggestion was to use Any instead of Dynamic when closing a monomorph that has no constraints, but maybe that wouldn't happen there anyway because of expected type?

**Comment by Simn** [comment]
It doesn't have no constraints, its only constraint is `Dynamic`.
