### ISSUE TITLE
Public field fill is not part of core type

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#11380]
```sh
/usr/local/lib/haxe/std/hl/_std/haxe/ds/Vector.hx:56: characters 3-40 : Public field fill is not part of core type
```

haxe version: 4.3.2
hl version: 1.13.0

The real issue is depending on the content of the code, sometimes I get this error, and then if I comment out fill function in the location, and run different type of code I will get the error that field fill is missing from Vector.

**Comment by Simn** [comment]
Sounds like something overrides `haxe.ds.Vector` from Haxe's std, because that one definitely has the `fill` method.

**Comment by PXshadow** [comment]
> Sounds like something overrides `haxe.ds.Vector` from Haxe's std, because that one definitely has the `fill` method.

Yeah you're right, I looked again, and it was a class called VectorData that I had created that was causing it, sorry for the trouble.
