### ISSUE TITLE
Pull requests for 4.3 Hotfix (part 4)

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#11394]
## 4.3.4

* [x] https://github.com/HaxeFoundation/haxe/commit/dd28b83951356dff776c451e8201fb64577679ac
* [x] 3a9445219a023253ff4c78cdbb84262e8f6a5276
* [x] 7653f686cdff23fa650c80eb4e87030a1b154687 / #11402
* [x] 13666860eceb09a98269d07d97ebbcc6abb6405f
* [x] https://github.com/HaxeFoundation/haxe/commit/ed838d789588487e817a326b60d31c4397ce9012
* [x] https://github.com/HaxeFoundation/haxe/commit/822dd87c1e7e56caac29aa3d42eb7879edeebade
* [x] https://github.com/HaxeFoundation/haxe/commit/dbc9952adf5a7ab30c430ddca0428313dbb1e376
* [x] 4463066539cc707ee74f1e90a770d8c39458c202 / #11560
* [x] #11526

See also: 
* [Bugfix candidates](https://github.com/HaxeFoundation/haxe/issues?q=+milestone%3A%224.3+Hotfix+candidates%22+)

**Comment by RblSb** [comment]
Not sure if possible to merge, but compilation server improvements will be nice to have for stable releases before 5.0
https://github.com/HaxeFoundation/haxe/commit/486dfc80866173a2d57c47476e5e4590c30e3504

**Comment by kLabz** [comment]
> Not sure if possible to merge, but compilation server improvements will be nice to have for stable releases before 5.0 [486dfc8](https://github.com/HaxeFoundation/haxe/commit/486dfc80866173a2d57c47476e5e4590c30e3504)

I didn't include this, as it's kind of a big change (and big merge conflicts) for a patch release :/

**Comment by tobil4sk** [comment]
Could the next 4.3 release include Apple Silicon binaries as well? #11572

**Comment by kLabz** [comment]
I will try, iirc there were issues last time.

Btw, I've seen people complain about the installer not being "universal", do you think it would be easy to update?

**Comment by tobil4sk** [comment]
> Btw, I've seen people complain about the installer not being "universal", do you think it would be easy to update?

I guess we'd need Neko universal binaries too.

**Comment by kLabz** [comment]
This will have to wait for 4.3.5

**Comment by RblSb** [comment]
https://github.com/HaxeFoundation/haxe/issues/11177 is broken in release
UPD: this is https://github.com/HaxeFoundation/haxe/commit/486dfc80866173a2d57c47476e5e4590c30e3504, nevermind

**Comment by RblSb** [comment]
Null coalescing logic has not been updated in release branch:
```haxe
@:using(Main.MoneyTools)
typedef Money = Int;

class MoneyTools {
	public static function inflate(money:Money):Money {
		return money + 99;
	}
}

class Main {
	static final money:Null<Money> = 1; // ok without Null<...>

	static function main() {
		final money = money ?? return;
		$type(money); // Int
		money.inflate(); // Missing fields for this
	}
}

```

**Comment by kLabz** [comment]
What issue/PR are you talking about here?

**Comment by RblSb** [comment]
I think this is about commits from https://github.com/HaxeFoundation/haxe/issues/11425
