### ISSUE TITLE
Crash on ambiguous string interpolation expression

### ISSUE THREAD

**Issue by triplefox** [HaxeFoundation/haxe#11402]
The following code crashes the compiler when run with "haxe -x Bug_2023Nov21.hx" (Tested on Haxe 4.3.3/unix and 4.3.1/unix):

```
class Bug_2023Nov21 {
  static function test() : String {
    var cells = [1,2,3];
    var ans = "";
    ans += '${cells.length} cell${if (cells.length == 1) {return "";} else {return "s";}}.\n';
    return ans;
  }
  static function main() {
    trace(test());
  }

}
```

`File "src/optimization/analyzerTexprTransformer.ml", line 123, characters 18-25
Called from file "src/optimization/analyzerTexprTransformer.ml", line 123, characters 11-25
Called from file "src/optimization/analyzerTexprTransformer.ml", line 184, characters 13-24
Called from file "src/optimization/analyzerTexprTransformer.ml", line 285, characters 15-25
Called from file "src/optimization/analyzerTexprTransformer.ml", line 245, characters 11-47
Called from file "src/optimization/analyzerTexprTransformer.ml", line 208, characters 38-55
Called from file "list.ml", line 121, characters 24-34
Called from file "src/optimization/analyzerTexprTransformer.ml", line 204, characters 18-238
Called from file "src/optimization/analyzerTexprTransformer.ml", line 121, characters 24-53
Called from file "src/optimization/analyzerTexprTransformer.ml", line 184, characters 13-24
Called from file "src/optimization/analyzerTexprTransformer.ml", line 364, characters 16-27
Called from file "src/optimization/analyzerTexprTransformer.ml", line 632, characters 14-32
Called from file "src/optimization/analyzerTexprTransformer.ml", line 660, characters 15-39
Called from file "src/optimization/analyzerTexprTransformer.ml", line 668, characters 23-47
Called from file "src/optimization/analyzer.ml", line 951, characters 10-13
Called from file "src/optimization/analyzer.ml", line 995, characters 2-106
Called from file "src/optimization/analyzer.ml", line 1059, characters 25-37
Called from file "src/optimization/analyzer.ml", line 1097, characters 4-22
Called from file "src/optimization/analyzer.ml", line 1112, characters 2-30
Called from file "list.ml", line 110, characters 12-15
Called from file "src/optimization/analyzer.ml", line 1122, characters 2-53
File "src/core/globals.ml", line 156, characters 1-7: Assertion failed`

The string interpolation is generally considered an error by the compiler(and there are plenty of ways to rewrite it in a way the compiler agrees with), but this one fails in different ways when I move it around to slightly different contexts.

**Comment by Simn** [comment]
Nice one! Can be reduced quite a bit:

```haxe
class Main {
	static function test() {
		var ans = Std.string(return "") + "";
	}

	static function main() {
		test();
	}
}
```

The analyzer doesn't deal with the unreachable block in value binops correctly.

I'm not sure why the original code should be an error though.

**Comment by kLabz** [comment]
Can repro on 4.3.x too

**Comment by Simn** [comment]
Yeah, I already added the commit to #11394.
