### ISSUE TITLE
Using Haxe, how can I generate python code with type hints?

### ISSUE THREAD

**Issue by nhan2ca** [HaxeFoundation/haxe#11407]
I want to write a cross-platform library with Haxe. But when I compile Haxe to Python, there is no type hint in Python code.
Although I have placed type hints in the haxe code, my python code after being generated does not have them.

How to let Haxe generate type hints to Python code? This helps users use my library more conveniently.

**Comment by Simn** [comment]
This isn't possible, and it's unlikely that this will be added to the python target.
