### ISSUE TITLE
Same name function for macro and non-macro context

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11420]
Hej,

I wanted to have a function like that, which could be used on compiletime (in macro context) and also in runtime : 
```haxe
public static macro function spaces( n : Int ){
	var s	= [ for( i in 0...n ) " " ].join( "" );
#if macro
	return macro $v{ s };
#else
	return s;
#end
}
```
But because of the `macro` keyword near `function` this function isn't available at runtime. And the reverse is also not possible (I mean without the `macro` keyword, be able to get a macro expr on compile-time...)

All that said, I wonder if it would be possible to have same name function with and without `macro` keyword without getting `Duplicate class field declaration` because at the end both functions are kind of "separated", they doesn't exist in same contexts ?

Regards,

**Comment by Simn** [comment]
You might be able to hack this with `@:native` or something if you're desperate, but the actual name cannot be duplicated because the compiler can't possibly know if you're calling the macro or the non-macro version while typing it.

**Comment by RealyUniqueName** [comment]
You can have a separate module for the macro context. For example `MyModule.hx` and `MyModule.macro.hx`

**Comment by filt3rek** [comment]
@RealyUniqueName Thx very much, I didn't thought about that ! :wink:

**Comment by Simn** [comment]
If I'm understanding the issue correctly (which I might not), that won't work either because the typer will never know that a macro is even involved here. The `macro` function has to exist in non-macro context as a gateway to macroland.

**Comment by filt3rek** [comment]
@RealyUniqueName Hmmm I don't really know if it could be possible at the end because using `macro` keyword in front of `function` we aren't really (yet) in the macro context and that is all the thing here...

**Comment by RealyUniqueName** [comment]
Ah, indeed. @Simn is right.

**Comment by filt3rek** [comment]
@Simn Maybe the "solution" would be to be able to use `macro` keyword like the `inline` keyword, "also" in expressions so it will call a function in the macro context, the gateway to macroland :stuck_out_tongue_closed_eyes:

**Comment by Simn** [comment]
That wouldn't make much sense because you can't just use any function as a macro function, unlike `inline`.

**Comment by filt3rek** [comment]
I agree but you would be able to use `#if macro` directive because the macro context would be "activated", and this way build function for both compile and run time.
But it's ok, I'm not desperate as you said and I even thank you for this discussion :)
