### ISSUE TITLE
HxOverrides undefined or missing members unless --dce set to no

### ISSUE THREAD

**Issue by thomasjwebb** [HaxeFoundation/haxe#11427]
When doing operations involving modulo (because python has a non-standard implementation, I'm guessing) the haxe-generated Python code uses `HxOverrides.mod` to replace python's `%`. In one of my projects, I had to add `--dce no` to prevent this from happening when running the output using the python interpreter:

`AttributeError: type object 'HxOverrides' has no attribute 'mod'`

I tried to make a more minimal example to illustrate the problem and it instead will not even define `HxOverrides` unless I use `--dce no`.

Minimal example

Main.hx
```haxe
package;

class Main
{
    public static function main() {
        var a:Int = -5;
        a = a % 7;
        trace(a);
    }
}
```

This is with the latest haxe (4.3.3) so it should have fixes for similar issues I've seen in closed issues.

**Comment by Simn** [comment]
The problem here was that the analyzer changed this to `a %= 7` and DCE didn't check that particular pattern.
