### ISSUE TITLE
Build macro ignored when hovering abstract field

### ISSUE THREAD

**Issue by player-03** [HaxeFoundation/haxe#11438]
Since variables aren't normally allowed in abstracts, I decided I'd use them for something unique.

I wrote a macro to convert variables to properties (plus use the variable's info to do other tasks), and it works for almost all purposes. The code compiles and runs fine. But when you hover over the variable, the compiler prints "Cannot declare member variable in abstract," indicating that it skipped the macro.

```haxe
@:build(Builder.build())
abstract Something(Int) {
	public var value:Int = 5;
	private inline function get_value():Int {
		return this;
	}
}

class Builder {
	public static macro function build():Array<Field> {
		var fields:Array<Field> = Context.getBuildFields();
		var initialValue:Expr = macro 0;
		
		for(field in fields) {
			switch(field.kind) {
				case FVar(t, e):
					initialValue = e;
					field.kind = FProp("get", "never", t);
				default:
			}
		}
		
		fields.push((macro class Constructor {
			public inline function new() {
				this = $initialValue;
			}
		}).fields[0]);
		
		return fields;
	}
}
```

The weirdest thing is that while testing this, I got the correct tooltip once. So it's possible to make it run the macro, but I can't seem to reproduce it.

**Comment by player-03** [comment]
I know this is a weird use case, and if I did things the intended way it would all work, but I want to save a few characters of typing per line.

**Comment by kLabz** [comment]
I'd think this is because your module is being loaded in both macro and non macro context, and this field is not transformed in macro context.

Try separating your macro / non-macro code or at least fence `public var value:Int = 5;` in a `#if !macro`

**Comment by player-03** [comment]
That's how I do it in my test environment, but I stripped it to make the sample code shorter. Same result either way.

**Comment by kLabz** [comment]
This looks fine to me :thinking: Aside from the fact that it's printed once as `static` and once as normal..

![image](https://github.com/HaxeFoundation/haxe/assets/6101998/515d1992-a390-4730-8a9f-492b626bce47)

![image](https://github.com/HaxeFoundation/haxe/assets/6101998/1a5bd31e-9639-4f24-a6f1-13f55e01622a)

**Comment by player-03** [comment]
I'm not worried about the static/not-static thing. Abstracts sometimes make fields static under the hood. Don't know why, but I've never seen it break anything, so I just accept it.

Odd that I only got it to work once, but it works fine for you. I've tested this in Haxe 4.3.1 and 4.3.3; what are you using?

**Comment by player-03** [comment]
It seems to be working in Haxe 4.3.4. I don't know why, but there were some changes related to macros, so I'll assume one of those did it. I'll re-open this if it ever breaks again.
