### ISSUE TITLE
Update Haxe on opam registry?

### ISSUE THREAD

**Issue by poperigby** [HaxeFoundation/haxe#11430]
Do you mind updating the [haxe](https://opam.ocaml.org/packages/haxe/) package on the opam registry? It's severely out of date.

**Comment by andyli** [comment]
I created that back in the days mostly because "why not". I didn't find it very useful since setting up opam itself isn't simple enough to general people, so I didn't advertise it.

I may submit the latest version to opam if there is a good use case. How do you use it?

**Comment by poperigby** [comment]
> How do you use it?

I'm trying to setup a Flatpak runtime extension for Haxe, to allow apps written in Haxe to be made into Flatpaks. When building a Flatpak, you can't access the internet during the actual building phase, so the sources have to be fetched beforehand. 

To do that for Haxe, I run this command to get Haxe's OCaml dependencies from opam:

```bash
opam tree --json=/tmp/haxe_deps.json haxe
```

I then have a script that handles the fetching of all the sources based on that JSON file.

If `opam tree` is able to get the dependencies from an `.opam` file, instead of querying opam, then it would be unnecessary for you to update the `haxe` opam package. Do you know if this is possible?

**Comment by andyli** [comment]
I've just tried it in a container, and it prints the deps successfully:

```
docker run -it --rm ocaml/opam:latest
opam-2.2 pin add -k git -n haxe https://github.com/HaxeFoundation/haxe#4.3.3
opam-2.2 tree haxe
```

**Comment by poperigby** [comment]
Ah, that works. Thank you.
