### ISSUE TITLE
Regression wrt complex type positions

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#11431]
In current Haxe, the position is now part of the complex type. However when creating complex type with macros we don't always have this position set, in which case it will be set to `null_pos`. But the problem is that if the type is not found, Haxe compiler will simply print `Type not found  : Name` to the output without any position context, making it very hard to debug...

I can easily hit into this error by refactoring some code, without much macros involved so I think that's quite a significant issue.

**Comment by ncannasse** [comment]
I'm not sure it's the right fix but it now gives me proper position for my refactoring. Reopening so @Simn can give a deep look maybe.

**Comment by Simn** [comment]
It might be better if `decode_ast_path` doesn't put `null_pos` there in the first place. I'll take a look.

**Comment by Simn** [comment]
How exactly do you create these `ComplexTypes`s? I'm trying to understand how it's possible to have `pos` set but not `posPath`.
