### ISSUE TITLE
i did haxe -hl src/main.c -main Main

### ISSUE THREAD

**Issue by CruzoPlayz** [HaxeFoundation/haxe#11432]
Haxe: 4.2.5; OS type: unix;
File "src/compiler/haxe.ml", line 285, characters 179-186
Called from file "src/compiler/haxe.ml", line 285, characters 172-186
Called from file "src/compiler/haxe.ml", line 1040, characters 11-55
Called from file "src/compiler/haxe.ml", line 642, characters 3-11
Called from file "src/compiler/haxe.ml", line 1247, characters 1-35
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

**Comment by kLabz** [comment]
Try setting your `HAXE_STD_PATH` env var properly, this looks like a mismatch between your std lib and haxe compiler.

**Comment by Simn** [comment]
I thought we backported the better failure to 4.2, but I guess not. We encourage using 4.3 instead of 4.2, there shouldn't be any obstacles.
