### ISSUE TITLE
`Error: Could not process argument client.hxml (file not found)` while builiding

### ISSUE THREAD

**Issue by poperigby** [HaxeFoundation/haxe#11445]
I'm trying to package Haxe into a Flatpak runtime extension, but I've run into some trouble during the compilation process. I have all of the dependencies compiled, but I hit an error when trying to compile Haxe itself:

```bash
cp -f _build/default/src/haxe.exe ./"haxe"
(cd /run/build/haxe/extra/haxelib_src && /run/build/haxe/haxe client.hxml && nekotools boot run.n)
Error: Could not process argument client.hxml (file not found)
Invalid character:
make: *** [Makefile:109: haxelib] Error 1
Error: module haxe: Child process exited with code 2
```

What could cause `client.xml` to be missing?

**Comment by tobil4sk** [comment]
It's possible that you did not check out all the submodules when cloning the repository

**Comment by poperigby** [comment]
I used [this](https://github.com/HaxeFoundation/haxe/archive/refs/tags/4.3.3.tar.gz) source code archive from the 4.3.3 release page. Does that not include the submodules?

Edit: It looks like it doesn't.

**Comment by poperigby** [comment]
I ended up using the git repository as my source instead of the archive.
