### ISSUE TITLE
cf_expr_unoptimized vs. hxb

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11460]
Let me tell you the story of `cf_expr_unoptimized`. It was [introduced in 2016](https://github.com/HaxeFoundation/haxe/commit/0136ac356b099698bc7b485cc3df094cd5a3363a) in order to address [a particular issue](#5320). The summary of that issue is that we need the original, unoptimized expression in order to inline consistently, so we have to keep it around in the compilation cache.

The value itself is only important when inlining (although I think `@:generic` should make use of it too). The filters ignore it (by design), the generators don't care and to the cache it's just a harmless waste of space. Kind of like you in your 20s.

However, there is a problem with hxb, the new Haxe binary format that is going to solve all our problems. In order to retain the value, it has to be encoded like any other value. The expression encoder is (and will always be) by far the most intense part of the binary protocol, and the presence of `cf_expr_unoptimized` essentially doubles its workload.

I can think of 2 approaches here:

1. Try to find a way to encode it more efficiently, e.g. by having a binary diff against `cf_expr`. I have little experience in that area, but there's a lot of similarity between the two, which should also be the case at byte-level. If anyone has any knowledge in this regard, please share!

2. Avoid encoding it as much as possible. You might be saying that we only need this for functions that are `inline`, but there's a corner case because we now also have call-site `inline`. If somebody uses that on a function in a cached module, we need _some_ defined behavior for it, and I can't really see what good behavior there would be in such cases.

If anyone has any ideas or opinions, let me know!

**Comment by Antriel** [comment]
Since no one else is saying anything, I will ramble a bit. Disclaimer: I have no clue about the internals of this, I'm more just brainstorming here.

> presence of `cf_expr_unoptimized` essentially doubles its workload

Does it double the workload or just memory usage? It would have to be unoptimized and eventually optimized either way, how does storing the original make things slower? Is it about lookup or some O(n) things running on the whole encoded cache? I'm just wondering if this is a (possibly wrong) assumption, or a fact.

RE option 1: Not sure how similar they are, but sounds like some sort of tagged union might work? Could be iffy if most/all of the common fields can change between the optimized and unoptimized.

RE option 2: This was my first thought. Store just the optimized, invalidate the module to get the unoptimized if needed. Store that fact somewhere too, so on next invalidation it does it right away.

Sorry if all of this is nonsense!

**Comment by Simn** [comment]
Thank you for your comment!

Since hxb is a byte writer, the "duplicate" field expression is basically an additional O(n) on top. The same is true for the reader which has to process the data twice. 

> invalidate the module to get the unoptimized if needed.

The problem with this is that we're already well into the whole typing process by the time we realize this. I mused a bit about this situation here: https://github.com/HaxeFoundation/haxe/wiki/Compiler-cache-update-design#but-what-if-it-goes-wrong

For this specific case it might actually be fair to just restart compilation altogether. It should be a _very_ rare case, so something like this might be acceptable.

**Comment by back2dos** [comment]
Stupid question: should hxb even contain the *optimized* expression? 

And I guess for any answer to that I need to ask a stupider question still: what are the use cases of hxb? 

Most of the stuff I would intuitively think of would work better with unoptimized expressions, which only get optimized in "the actual build" (when a mixture of hxb and hx code is turned into target code) with the particular optimization settings of that build.

**Comment by Simn** [comment]
All this is in the context of the Haxe compilation cache, which we're changing to make use of the binary format. In that sense it's not a hxb-specific problem, but with hxb it becomes really apparent due to its nature as a byte writer.

Our compilation basically works like this:

1. type
2. store unoptimized expression
3. optimize
4. cache/save state
5. optimize some more
6. generate

Step 3 includes some quite heavy operations like the analyzer which we don't want to repeat when re-using the cache. Step 5 on the other hand includes some operations that we do not want to cache because it might destroy some information, or add some information that depend on the current compilation state.

This has been working quite well overall, but features which rely on the actual field expressions during typing (which I think is only `inline` and `@:generic`) run into problems when working with the output of step 3.

Your comment makes me think about the expression state for when we generate hxb as a standalone output though. There seem to be two use-cases for this:
1. If we want to use it as a `--hxb-lib` during typing, we would indeed likely want the unoptimized state.
2. If it is meant to be handled by `--interp`, we would want the final output state that the interpreter would receive normally as well.

Perhaps a good distinction would be the presence of `-main` and assuming "library mode" if it's absent.
