### ISSUE TITLE
hashlink try catch set bug

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#11466]
```haxe
var b = 10;

function main() {
  var x = 0;
  try {
    x = b;
    throw "hi";
  }catch(_) {
    trace(x);
  }
}
```
Returns 0, expected 10

https://try.haxe.org/#806c75c6
Haxe latest

**Comment by Simn** [comment]
Could you try with `-D hl_no_opt`?

**Comment by kLabz** [comment]
Sounds like #9174
And yeah seems to be a hl-opt issue

**Comment by Simn** [comment]
That one was about nested try/catch though, while this seems really basic... Maybe something else for @yuxiaomao to check out.

**Comment by PXshadow** [comment]
> Could you try with `-D hl_no_opt`?

Passes with `-D hl_no_opt`
