### ISSUE TITLE
Compiling seems to cause a compiled program to crash.

### ISSUE THREAD

**Issue by ElastedAlorian** [HaxeFoundation/haxe#11476]
Not sure if this is a Haxe only thing or a Flixel only thing, but when I try to compile something, the output crashes on startup, and when running the output via a terminal, it gives out "Segmentation fault: 11"
OS: Mac OS X 10.13.6 (High Sierra)

bash-3.2$ lime test macos

```
Creating /Users/apple/Desktop/SC/My Stuff/SonicBasedTest/export/macos/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch...

Compiling group: haxe
xcrun --sdk macosx clang++ -Iinclude -c -fvisibility=hidden -stdlib=libc++ -Qunused-arguments -O2 -I/Users/apple/haxelib/hxcpp/4,3,2/include -DHX_MACOS -arch x86_64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-overflow -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) ... tags=[haxe,static]
 - src/ApplicationMain.cpp 
 - src/lime/utils/AssetCache.cpp  [haxe,release]
Link: ApplicationMain

bash-3.2$ /Users/apple/Desktop/SC/My\ Stuff/SonicBasedTest/export/macos/bin/HaxeSonic.app/Contents/MacOS/HaxeSonic 
Segmentation fault: 11
bash-3.2$ 
```
Terminal output.

**Comment by moxie-coder** [comment]
> Not sure if this is a Haxe only thing or a Flixel only thing, but when I try to compile something, the output crashes on startup, and when running the output via a terminal, it gives out "Segmentation fault: 11"
> 
> OS: Mac OS X 10.13.6 (High Sierra)
> 
> 
> 
> bash-3.2$ lime test macos
> 
> 
> 
> ```
> 
> Creating /Users/apple/Desktop/SC/My Stuff/SonicBasedTest/export/macos/obj/obj/darwin64/__pch/haxe/hxcpp.h.gch...
> 
> 
> 
> Compiling group: haxe
> 
> xcrun --sdk macosx clang++ -Iinclude -c -fvisibility=hidden -stdlib=libc++ -Qunused-arguments -O2 -I/Users/apple/haxelib/hxcpp/4,3,2/include -DHX_MACOS -arch x86_64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-overflow -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=430(haxe) ... tags=[haxe,static]
> 
>  - src/ApplicationMain.cpp 
> 
>  - src/lime/utils/AssetCache.cpp  [haxe,release]
> 
> Link: ApplicationMain
> 
> 
> 
> bash-3.2$ /Users/apple/Desktop/SC/My\ Stuff/SonicBasedTest/export/macos/bin/HaxeSonic.app/Contents/MacOS/HaxeSonic 
> 
> Segmentation fault: 11
> 
> bash-3.2$ 
> 
> ```
> 
> Terminal output.
> 
> 

If you're using flixel, this issue doesn't really belong here

**Comment by Simn** [comment]
Yeah this is not much to go on. I recommend flixel or openfl/lime community,
