### ISSUE TITLE
@:bypassAccessor not working?

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#11488]
In Heaps, in h2d/TextInput.hx, I wanted to bypass the visible setter in drawRec here, I notice that we still enter the set_visible.

Try change this line to `@:bypassAccessor interactive.visible = false` for a reproduction:
https://github.com/HeapsIO/heaps/blob/2.0/h2d/TextInput.hx#L665

**Comment by Simn** [comment]
IIRC we discussed this before and the problem is that this is parsed as `(@:bypassAccessor interactive.visible) = false` or something to that effect. I'll check it again.

**Comment by kLabz** [comment]
That's also what I remember from it

**Comment by ncannasse** [comment]
Sure, expect this does not seem to work either:
```haxe
@:bypassAccessor (interactive.visible = false);
```

**Comment by Simn** [comment]
```haxe
class Parent {
	public var visible(default, set) = true;

	public function new() {}

	public function set_visible(v:Bool) {
		return visible = v;
	}

	public function drawRec() {}
}

class Child extends Parent {
	override function drawRec() {
		@:bypassAccessor visible = false;
	}
}

function main() {}
```

Generated:

```js
Child.prototype = $extend(Parent.prototype,{
	drawRec: function() {
		this.visible = false;
	}
});
```

I can't reproduce this in a reduced example, works even with the version that I thought wouldn't work.

**Comment by kLabz** [comment]
Reproduced there: https://try.haxe.org/#6c9Fe54E (so 2x field access, first one "consumes" `bypass_accessor` and when we get to 2nd one it's not set anymore)

**Comment by Simn** [comment]
Oh right, it does that counting thing which I never really understood... and I forgot who implemented that.

**Comment by kLabz** [comment]
Silly workaround:
```haxe
@:bypassAccessor @:bypassAccessor interactive.visible = false;
```

:grin: (and yeah it [does work](https://try.haxe.org/#88393dD3)...)

**Comment by Simn** [comment]
This was originally implemented in https://github.com/HaxeFoundation/haxe/pull/8259.

**Comment by Simn** [comment]
@nadako Do you have an opinion on this? I wasn't too sure about this counter-based implementation, but it gets really silly with an implicit `this` field access like here. Should we perhaps only decrease that counter if it actually came into effect?

**Comment by nadako** [comment]
Nah at this point I don't have any opinion on this :) I only vaguely remember why the counter was needed in the first place and I probably didn't think properly about the ergonomics regarding implicit access etc. Sorry for that!
