### ISSUE TITLE
[hxb] Redefinition error when hovering in shadowed module

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11480]
When hovering a shadowed type such as https://github.com/HaxeFoundation/haxe/blob/development/std/StdTypes.hx, the server now gives `Type name Void is redefined from module StdTypes`. This doesn't actually surprise me very much because I assume we load the display module, restore the cached `_std` version and then see the error. However, it doesn't happen on development, which makes me wonder why.

I think there are two layers here:

1. The server shouldn't even restore anything else.
2. It shouldn't fail like that even if it does restore something else.

This might be a quite specific problem, but could still expose a more general problem.

**Comment by Simn** [comment]
Nothing I said (including the issue title) makes much sense, but the problem is this: The module is typed normally via TyperEntry.create and put in the common context, but `check_display_file` bypasses that and looks into the cache directly. There it finds a HXB module and starts reading it, which then leads to the error. That's actually quite funny.

This is related to the TODO in server.ml: "This should go through everything Typeload.load_module (and TypeloadModule.load_module) goes through except the actual typing.". We need a function that checks the common context and the cache, but doesn't initiate any typing in case no module can be found.

**Comment by Simn** [comment]
Fixed by linked commit. A test would be good, but it's not so easy because we have to request one of the types that get loaded before `check_display_file` does its thing. It should only be reproducible on modules loaded by `TyperEntry.create`, so this was much narrower than I thought.

**Comment by kLabz** [comment]
Can try adding a test for that on Thursday or Friday.
