### ISSUE TITLE
Respect the Freedesktop.org XDG Base Directory Specification on Linux

### ISSUE THREAD

**Issue by Arrow-x** [HaxeFoundation/haxe#11499]
https://freedesktop.org/wiki/Specifications/basedir-spec/
because currently the haxe configs are cluttering the home dir, with `haxe` folder a `.haxlib` config file

**Comment by tobil4sk** [comment]
`.haxelib` is created by [haxelib](https://github.com/HaxeFoundation/haxelib). However, the `haxe` folder is not created by haxe itself, it is probably for [lix](https://github.com/lix-pm/haxeshim).

**Comment by Arrow-x** [comment]
lix already have a env var for setting the file, it's just haxlib so I should move the issue
