### ISSUE TITLE
File not found after workspace-symbols

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11497]
<img width="470" alt="dyFvYaBMcq" src="https://github.com/HaxeFoundation/haxe/assets/634365/c972eaa7-3f17-4701-a203-08c5f95c81cd">

The left file is from a workspace-symbols request (ctrl + T), the right one is from whatever ctrl + P is called. There's a leading `\` which messes something up. Probably comes from the class-path changes.

**Comment by Simn** [comment]
Huh, workspace-symbols gives us this:

```
        {
            "file": "src/unit/TestInt64.hx",
            "symbols": [
                {
                    "name": "TestInt64",
                    "kind": 1,
                    "range": {
                        "start": {
                            "line": 6,
                            "character": 0
                        },
                        "end": {
                            "line": 629,
                            "character": 1
                        }
                    },
                    "containerName": "unit"
                }
            ]
        },
```

Before the class path changes it had an absolute path:

```
            "file": "c:\\git\\haxe\\tests\\unit\\src\\unit\\TestInt64.hx",
            "symbols": [
                {
                    "name": "TestInt64",
                    "kind": 1,
                    "range": {
                        "start": {
                            "line": 6,
                            "character": 0
                        },
                        "end": {
                            "line": 629,
                            "character": 1
                        }
                    },
                    "containerName": "unit"
                }
            ]
```

Not sure who made that path absolute before the changes.

**Comment by Simn** [comment]
Reopening because I'm not sure if we should really have to do this. There might be a related vshaxe problem here that doesn't deal with paths correctly, because that must be where that leading `\` comes from.

**Comment by kLabz** [comment]
Can look into this later today or tomorrow

**Comment by kLabz** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/104341a4625fc9dea240f9d710004f75c7c0b071 maybe?

**Comment by Simn** [comment]
I still think that this should work with the relative path that we sent, but that'd be a vshaxe issue then.
