### ISSUE TITLE
[hxb] hxb vs. jvm unit test roundtrip

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11493]
Trying to roundtrip the JVM unit tests gives me this:

```
[error] [HXB] [unit.TestJava] Error while resolving type haxe.test.MyClass.MyClass: Type not found : haxe.test.MyClass
```

If I add `--java-lib native_java/native.jar` to the reading hxml:

```
[30;41m ERROR [0m C:/git/hxjava/lib/hxjava-std.jar@java/util/HashMap.class@resize

   | Too many type parameters for java.NativeArray
```

If I delete java/NativeArray.hxb from the archive:

```
[HXB] [haxe.NativeStackTrace] Error while building class java.NativeArray: java.NativeArray is not ready to be accessed, separate your type declarations in several files
```

So that looks like 3 separate questions:

1. Why is `haxe.test.MyClass` not in the hxb? Yes it's an extern from a `--java-lib`, but it is accessed and becomes a real module type, so IMO it should be there.
2. What's going on with the type parameters of `java.NativeArray`?
3. Why do we have compiler pass problems...

**Comment by Simn** [comment]
I have fixed 2. in https://github.com/HaxeFoundation/haxe/commit/9c3b3e54a2991ffade9e68f95f7b7b8f219f5b44. Type parameters were set too late, so I moved them from the module type definitions to the MTF chunk. The real typeloader does something very similarly in `init_type_params`.

Number 3 is related to the reader calling `cl_build` when trying to look up fields. I thought this would work in all cases, but when loading non-hxb types this init function might not even be set. We should then go back to something we had before, which is `CFR` and `EFR` both calling an API function to flush the correct typer pass. My initial attempt at doing so lead to an `Loop in class building prevent compiler termination` error, so there must be yet another problem.

**Comment by Simn** [comment]
One easy way to cause a typing pass problem is deleting Array.hxb from the eval roundtrip, which will give us "Could not read instance field length on Array while hxbing haxe.iterators.ArrayKeyValueIterator". I'm not sure if it's the same issue as the NativeArray one here, but the problem comes down to this:

Array.hx has `import haxe.iterators.ArrayKeyValueIterator;` on top, which triggers the loading of that module before Array's `EClass` is ever processed. When the hxb reader then reads ArrayKeyValueIterator.hxb, it does request to enable field typing mode, but because we haven't processed Array yet, we didn't call `init_class` on it and `cl_build` hasn't been set.

Replicating the real typer's behavior would mean that we initially read the hxb only to the nominal module type definitions (MTF chunk) and then delay the rest. I would prefer to not put half-read hxb readers into delay-closures, but I'm not sure if this can be avoided. While the import problem here could be worked around, I suspect that the same thing could happen from any other typeload.

**Comment by Simn** [comment]
The eval case works now. JVM compiles as well but fails at run-time with `Exception in thread "main" java.lang.NoClassDefFoundError: haxe/java/Init`. This is one of the cases where a type is only referenced via imports, in this case from JVM's Std.hx `import jvm.Jvm` and its `import java.Init`. With imports not being part of the typed expressions, the types are omitted when we hxb-restore Std.hx.

@kLabz We discussed this before, but I forget what the conclusion was. My inclination is that for .hxb we need to output a chunk which export `m_deps`, so that the consuming reader can make sure all those modules that otherwise don't appear are loaded. Does that make sense?

**Comment by kLabz** [comment]
Hmm yeah I think it does (and iirc that was your conclusion last time too). In a world with no side effects (no `__init__` etc) and with dce `full` (edit: yeah I also meant in a world without `@:keep`) this wouldn't be needed but I guess we don't have much choice.

**Comment by Simn** [comment]
In genjvm's case it's an import of a `@:keep` class, which the generator relies on. I think several targets do something like that.

**Comment by Simn** [comment]
This is pretty annoying to handle because dependencies could come from another context (mostly macro), and I don't really want the writer or the reader to deal with context signatures and such... I'll see how often this comes up in practice, the best course of action might be to tell users (which for this particular problem will be mostly us) to make sure types are properly referenced somewhere.

**Comment by Simn** [comment]
As for some good news, the timers look nice:

First:

```
name             | time(s) |   % |  p% |      # | info
-------------------------------------------------
generate         |   2.077 |  35 |  35 |      7 | 
  java           |   1.370 |  23 |  66 |      6 | 
    real types   |   1.164 |  20 |  85 |      1 | 
    preprocess   |   0.148 |   2 |  11 |      1 | 
    anons        |   0.044 |   1 |   3 |      1 | 
  hxb            |   0.707 |  12 |  34 |      1 | 
typing           |   1.030 |  17 |  17 |   5169 | 
macro            |   0.822 |  14 |  14 |   3667 | 
  add_types      |   0.025 |   0 |   3 |    103 | 
  jit            |   0.014 |   0 |   2 |   1434 | 
analyzer         |   0.651 |  11 |  11 |    247 | 
filters          |   0.588 |  10 |  10 | 122027 | 
parsing          |   0.350 |   6 |   6 |   1765 | 
jvm              |   0.206 |   3 |   3 |   5197 | 
  write          |   0.206 |   3 | 100 |   5197 | 
jar              |   0.192 |   3 |   3 |   1575 | 
  load           |   0.099 |   2 |  52 |      2 | 
  read           |   0.067 |   1 |  35 |   1091 | 
  convert        |   0.026 |   0 |  14 |    482 | 
-------------------------------------------------
total            |   5.931 | 100 | 100 | 402157 | 
```

Second:


```
name             | time(s) |   % |  p% |     # | info
------------------------------------------------
generate         |   1.310 |  58 |  58 |     6 | 
  java           |   1.310 |  58 | 100 |     6 | 
    real types   |   1.182 |  53 |  90 |     1 | 
    preprocess   |   0.083 |   4 |   6 |     1 | 
    anons        |   0.032 |   1 |   2 |     1 | 
typing           |   0.307 |  14 |  14 |     1 | 
filters          |   0.186 |   8 |   8 |  8533 | 
jar              |   0.177 |   8 |   8 |  1573 | 
  load           |   0.100 |   4 |  56 |     2 | 
  read           |   0.057 |   3 |  32 |  1090 | 
  convert        |   0.021 |   1 |  12 |   481 | 
jvm              |   0.112 |   5 |   5 |  5118 | 
  write          |   0.112 |   5 | 100 |  5118 | 
hxblib           |   0.090 |   4 |   4 |  1554 | 
  load_module    |   0.085 |   4 |  94 |  1553 | 
analyzer         |   0.031 |   1 |   1 |    58 | 
macro            |   0.023 |   1 |   1 |   678 | 
------------------------------------------------
total            |   2.246 | 100 | 100 | 17524 |
```

Even if we subtract the generate.hxb, it's much faster. In particular, the hxblib.load_module is 3x faster than parsing alone.

**Comment by kLabz** [comment]
Kinda unrelated but why are jar still parsed on 2nd build?

**Comment by Simn** [comment]
Because of the 1. issue in the initial post. But I'm glad you've asked because I just found the reason for that. 

```ocaml
let export_hxb com cc platform zip m =
	let open HxbData in
	match m.m_extra.m_kind with
		| MCode | MMacro | MFake ->
```

This ignores `MExtern`. Was that a conscious decision?

Edit: So in https://github.com/HaxeFoundation/haxe/commit/976a24af4b44f5a4756b85df2900377ac8d2f10e#diff-87bc22050e058a4e1ce1c235881f5825ad40a0fa0a2cef336247a8c40cc372a5R6 it was just `MCode`, then in https://github.com/HaxeFoundation/haxe/commit/302ceda925a64861e56fa3db2b2dc2ba8a6a0d2e#diff-87bc22050e058a4e1ce1c235881f5825ad40a0fa0a2cef336247a8c40cc372a5R26 `MMacro` was added, then in https://github.com/HaxeFoundation/haxe/commit/e1d2e394bea2b18c7a1c0de96b73a625fd48ed14 came `MFake`. Looks about as conscious a decision as most decisions we make around here. I'll add `MExtern`.

**Comment by Simn** [comment]
With that done, there's no more jar timers in the second build:

```
name             | time(s) |   % |  p% |     # | info
------------------------------------------------
generate         |   1.334 |  69 |  69 |     6 | 
  java           |   1.334 |  69 | 100 |     6 | 
    real types   |   1.185 |  61 |  89 |     1 | 
    preprocess   |   0.099 |   5 |   7 |     1 | 
    anons        |   0.036 |   2 |   3 |     1 | 
typing           |   0.186 |  10 |  10 |     1 | 
filters          |   0.178 |   9 |   9 |  8533 | 
hxblib           |   0.104 |   5 |   5 |  2035 | 
  load_module    |   0.095 |   5 |  92 |  2034 | 
jvm              |   0.093 |   5 |   5 |  5118 | 
  write          |   0.093 |   5 | 100 |  5118 | 
analyzer         |   0.024 |   1 |   1 |    58 | 
macro            |   0.020 |   1 |   1 |   678 | 
------------------------------------------------
total            |   1.948 | 100 | 100 | 16432 | 
```

There's still a typing timer, but that's just the big one from Compiler.do_type, where I guess some parts don't have their own timers.

So in summary:

1. was because the hxb generator explicitly ignored `MExtern` modules.
2. was because type parameters were read too late, they have been moved up to the MTF chunk
3. was because hxb restoration would try to restore an entire module in one go, which isn't compatible with our typing pass system. This was fixed by splitting up the reading process to align with our usual type handling.

Thank you for reading my blog.
