### ISSUE TITLE
Enum drop down completion not showing constructors

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#11515]
Ctrl+Space on an enum doesn't show its constructors in the drop down completion on nightlies, works fine on 4.3.3.

Nightly:
![image](https://github.com/HaxeFoundation/haxe/assets/10246746/f0bd8558-fa60-4825-9fd5-09d6284daa18)

4.3.3:
![image](https://github.com/HaxeFoundation/haxe/assets/10246746/0ec262a2-aec4-4c8f-82c4-eb22093661c6)

**Comment by Simn** [comment]
Well, that's a bit embarrassing...
