### ISSUE TITLE
inline constructor of abstracts

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#11526]
We recently changed our Heaps Vector implementation to use an abstract so we can have some operator overloading, but we noticed some regression due to constructor inline not being triggered anymore.

We can reproduce with the following sample:

```haxe
class P {
   public var x : Float;
   public inline function new(x=0) this.x = x;
}


@:forward
abstract PA(P) {
  public inline function new(x) this = new P(x);
}

class Test {
  static function foo(x:Int) {
    var p1 = { v : new P(x) }
    trace(p1.v.x);
    var p2 = { v : new PA(5) }
    trace(p2.v.x);
  }
  static function main() {
    foo(5);
  }
}
```

It seems inline new is not handled for abstracts ?

**Comment by Simn** [comment]
cc @basro

**Comment by basro** [comment]
A quick note:
Inlining abstracts is working, it seems the combination of abstracts and anonymous structs is what is cancelling the inlining.

This inlines everything:
```haxe
class P {
   public var x : Float;
   public inline function new(x) this.x = x;
}


@:forward
abstract PA(P) {
  public inline function new(x) this = new P(x);
}

class Test {
  static function foo(x:Int) {
    var p1 = { v : new P(x) }
    trace(p1.v.x);
    var p2 = new PA(5);
    trace(p2.x);
  }
  static function main() {
    foo(5);
  }
}
```

**Comment by basro** [comment]
I have not tested with the compiler but my bet is that the cancellation is happening [in this line](https://github.com/HaxeFoundation/haxe/blob/a2c3714582edebe09b56cb815ee517dcab04f9de/src/optimization/inlineConstructors.ml#L325).

It is likely that the type of the inlined object and the type of the field access are not strictly equal.

**Comment by Simn** [comment]
Good intuition:

```
p2<-6565>.v
  v_type: TAbstract(PA, [])
  etype: TInst(P, [])
```

I don't know where that goes wrong though because the type is initially correct:

```
 17 |   $type(p2.v);
    |         ^^^^
    | PA
```
