### ISSUE TITLE
Default type parameters vs constraints

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#11556]
We can currently define default type parameters that are not compatible with their constraints:

```haxe
class Foo<T:EnumValue = Void> {
    public var data:T;
    public final function new() {}
}
```
https://try.haxe.org/#8B325355

When used, type inference will use a monomorph there:
```haxe
    // This is fine
    var e = new Foo();
    $type(e.data); // Unknown<0> : EnumValue
```

But when explicitly using the default type parameter, it'll fail as expected:
```haxe
    // This is not fine
    var e:Foo = new Foo();
    $type(e.data); // Void
```
```haxe
[ERROR] Test.hx:7: characters 5-27

 7 |     var e:Foo = new Foo();
   |     ^^^^^^^^^^^^^^^^^^^^^^
   | error: Void should be EnumValue
   | have: Foo<Void>
   | want: Foo<EnumValue>
```

We should probably catch that early, directly in `class Foo<T:EnumValue = Void>` declaration

**Comment by Simn** [comment]
I vaguely remember us saying "this is fine", but looking at it I'd also expect this to fail.

**Comment by Simn** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/060ff565605a21c123177a7492758ece43d5f77e
