### ISSUE TITLE
hxb Unexpected BadModule

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#11559]
Started doing stuff with my macro-heavy lib, it compiles OK, but via server it does this:
```
ERROR  (unknown position)

   | Error: Compiler failure: Unexpected BadModule hxser.imperative.DataStructures 
   | Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new   
   | Attach the following information:
   | Haxe: 5.0.0-alpha.1+454d3da; OS type: windows;
   | File "src/compiler/server.ml", line 432, characters 69-76
   | Called from file "src/compiler/server.ml", line 409, characters 10-29
   | Called from file "src/compiler/hxb/hxbReader.ml", line 178, characters 3-19   
   | Called from file "src/compiler/hxb/hxbReader.ml", line 1777, characters 9-26  
   | Called from file "array.ml", line 54, characters 22-27
   | Called from file "src/compiler/hxb/hxbReader.ml", line 1775, characters 15-279
   | Called from file "src/compiler/hxb/hxbReader.ml", line 1962, characters 2-23  
   | Called from file "src/compiler/hxb/hxbReader.ml", line 1973, characters 4-24  
   | Called from file "src/compiler/hxb/hxbReader.ml", line 1977, characters 18-29 
   | Called from file "src/compiler/server.ml", line 570, characters 14-38
   | Called from file "src/compiler/server.ml", line 574, characters 20-43
   | Called from file "src/typing/typeloadModule.ml", line 806, characters 8-51    
   | Called from file "src/typing/typeloadModule.ml", line 840, characters 10-40   
   | Called from file "src/typing/typeload.ml", line 194, characters 2-33
   | Called from file "src/typing/typeload.ml" (inlined), line 203, characters 9-39
   | Called from file "src/typing/typeload.ml", line 210, characters 2-48
   | Called from file "src/context/display/importHandling.ml", line 274, characters 11-41
   | Called from file "src/context/display/importHandling.ml", line 293, characters 28-51
   | Called from file "list.ml", line 110, characters 12-15
   | Called from file "src/typing/typeloadModule.ml", line 708, characters 1-69
   | Called from file "src/typing/typeloadModule.ml", line 722, characters 13-52
   | Called from file "src/typing/typeloadModule.ml", line 840, characters 10-40
   |
```

**Comment by Antriel** [comment]
Also seeing `HxbData.HxbFailure("Could not read static field NONE on hxser.extensions._Extension.ExtensionId_Impl_ while hxbing hxser.imperative.ImperativeAst")` in the Haxe output, not sure if it's related. Also not sure why, there's nothing too special about that field.

**Comment by Simn** [comment]
One nice side-effect of hxb is that the stack traces are pretty sensible now. I can tell that we're typing a module, resolving one of its imports, type another module, find its binary representation in the cache, start decoding it and then come across an abstract that is considered dirty.

What is supposed to happen here is that `check_module` doesn't even let us start decoding the module because one of its dependencies is dirty. This in turn likely means that the dependency in question is missing. The hard part is figuring out why that would be the case.

Is the code causing this public?

**Comment by Antriel** [comment]
> Is the code causing this public?

No. :(
But I suppose I can give you and/or Rudy access, if it's the most efficient way to make progress. It's quite big and slightly crazy code base.

**Comment by Simn** [comment]
I hear Rudy loves those!

**Comment by kLabz** [comment]
Did you add a `CompilationServer.invalidateFiles` call?
We might want to restrict it to init macros :thinking:

**Comment by Antriel** [comment]
Nope, that was different project. I'm gonna fork the code and give you guys access.

**Comment by kLabz** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/342b1387e287241fac6b8300a29e7955d7bf4429
