### ISSUE TITLE
optimization tests vs. cache

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11561]
1. Open tests/optimization and compile it through the server. Observe that there are no failures.
2. Change any of the `@:js` and compile it through the server again. Observe that there's a failure now, as expected.
3. Change the `@:js` back to what it originally was and run it through the server one more time. Observe that there's _still_ a failure.

I think this must be some metadata insanity going on.

**Comment by kLabz** [comment]
does that happen with pre-hxb nightlies too ?

**Comment by Simn** [comment]
I don't think so, but I haven't tried.

**Comment by Simn** [comment]
This still reproduces.

**Comment by Simn** [comment]
I wanted to look into this but now I cannot seem to reproduce it anymore. There's a chance that I somehow changed my setup, so I would like to verify this. However, bisecting is difficult for me due to the parser situation...

@kLabz Could you try reproducing this on [this commit](https://github.com/HaxeFoundation/haxe/commit/6f20d6b0160193a4fb194bcef982294fa59009fe)?

**Comment by kLabz** [comment]
> 2. Change any of the @:js and compile it through the server again. Observe that there's a failure now, as expected.

Well... I'm not getting a failure Oo just one less test

**Comment by kLabz** [comment]
Nevermind I was doing it wrong. I don't get a failure on `3` _but_ the failure warning persists

![image](https://github.com/user-attachments/assets/09b0596c-05a6-4f9b-9311-943522418627)

**Comment by Simn** [comment]
Ah damn, now I'm not sure anymore if I actually had a failure or if I only saw the warnings too...

**Comment by kLabz** [comment]
Warning insanity (cache bound objects) sounds a bit more plausible than metadata insanity, so that's likely it :thinking:

**Comment by Simn** [comment]
To confirm, this doesn't occur on current development, right? In that case I'd be interested in a bisect because I don't know when we fixed this.

**Comment by kLabz** [comment]
Indeed. Will try to remember to bisect that after I'm done with current thing

**Comment by kLabz** [comment]
Fixed by d989ab3055850bfaf2877cdf8c801a13e783ec86

**Comment by Simn** [comment]
Huh, I can't say I necessarily expected that, but I'll take it. Thanks for checking!
