### ISSUE TITLE
Cant install package

### ISSUE THREAD

**Issue by boynfrienddv** [HaxeFoundation/haxe#11573]
I cant download any package! It says:

> haxelib --global install flixel
Failed. Triggering retry due to HTTP timeout
Failed. Triggering retry due to HTTP timeout
Failed. Triggering retry due to HTTP timeout
Failed. Triggering retry due to HTTP timeout
Failed. Triggering retry due to HTTP timeout
Failed. Triggering retry due to HTTP timeout
Error: Failed due to HTTP timeout after multiple retries

It just doesnt work with no global and global, i tried notimeout too but 0 result

**Comment by moxie-coder** [comment]
that’s due to a bad WiFi connection so it can’t successfully connect to haxelib servers, and plus there’s a [repository for haxelib issues](https://github.com/HaxeFoundation/haxelib)
