### ISSUE TITLE
Haxe error Invalid_argument("index out of bounds") on JS project compile with --connect

### ISSUE THREAD

**Issue by yuxiaomao** [HaxeFoundation/haxe#11589]
Recently (bisect tell me this is the first bad commit https://github.com/HaxeFoundation/haxe/commit/30a0163302a31214dff91ab14492530a60d80307), when I build a JS project such as [hide](https://github.com/HeapsIO/hide) for the second time and above (with `--connect`), it fail with `Invalid_argument("index out of bounds")`.

This complicates development with VSCode.

**Comment by Simn** [comment]
Could you define the environment variable `OCAMLRUNPARAM=b` and post the printed stack trace?

**Comment by yuxiaomao** [comment]
It does not show more information
```console
$ OCAMLRUMPARAM=b haxe.exe --connect 127.0.0.1:6001 hide.hxml
Invalid_argument("index out of bounds")
```

**Comment by kLabz** [comment]
Can repro locally

**Comment by yuxiaomao** [comment]
The issue is fixed for hide, but not for https://github.com/vshaxe/hashlink-debugger (Build with `OCAMLRUMPARAM=b haxe.exe --connect 127.0.0.1:6000 build.hxml`)
Same error, no additional print with `OCAMLRUMPARAM=b`, same bad commit.
@kLabz Could you please check?
