### ISSUE TITLE
Make js.html.HTMLCollection Iterable?

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#11588]
https://api.haxe.org/js/html/HTMLCollection.html

I commonly find myself trying to iterate on HTMLCollection objects. Is there a conscious design decision that would go against implementing `Iterator` for HTMLCollection?

**Comment by filt3rek** [comment]
You already can iterate on HTMLCollection : https://try.haxe.org/#e76e230b

**Comment by NQNStudios** [comment]
Oh whoops. I think @:arrayAccess might be what I was thinking of, then.
What about that?

**Comment by kLabz** [comment]
Works too? https://try.haxe.org/#34e66a6D

**Comment by NQNStudios** [comment]
Sorry I'm so disorganized & didn't write down what was actually giving me trouble when it happened. I'll close this unless I remember.
