### ISSUE TITLE
[dev] Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_

### ISSUE THREAD

**Issue by EliteMasterEric** [HaxeFoundation/haxe#11598]
When building my project for the JDK target with the `development` version of Haxe, I get the following error:

```
Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_
```

This is the full output of the compilation when using `haxe ./generated/build.hxml`. There are no line numbers or additional diagnostic information, even when using `--verbose`, thus I haven't been able to figure out what feature is causing the issue or create a minimal reproduction.

**Platform:** Windows 10 x64
**Haxe Version:** `5.0.0-alpha.1+9aae69c`
**Project Link**: https://github.com/EliteMasterEric/PickHaxe-Samples/tree/master/madeinhaxe

**Comment by Simn** [comment]
Could you try if `-dce no` makes a difference?

**Comment by EliteMasterEric** [comment]
```
haxe -dce no .\generated\build.hxml        

Field index for SSL_IS_SERVER not found on prototype mbedtls._SslEndpoint.SslEndpoint_Impl_
```

No dice it seems.
