### ISSUE TITLE
lines 23-45 Compiler failure: Failed to locate variable declaration

### ISSUE THREAD

**Issue by EgguProgramming** [HaxeFoundation/haxe#11594]
![image](https://github.com/HaxeFoundation/haxe/assets/100107293/979a1438-0b5c-4889-b364-7008a136ef99)

running flixel 5.5.0, openfl 9.3.2 and lime 8.1.1 if that helps

the line im experiencing issues on is `override public function new() {` so I dont get why its failing.

**Comment by Simn** [comment]
A bit more context would help here...

**Comment by kLabz** [comment]
Same as #11711 which has a repro
