### ISSUE TITLE
Self-contained compiler support request

### ISSUE THREAD

**Issue by top-master** [HaxeFoundation/haxe#11623]
The `Nim` language's compiler is written in pure `Nim`, no need for `OCaml`, which's what the Nim community calls "self-contained compiler".

Similarly, `Haxe` language's compiler is partialy self-contained, but `OCaml` logic is used by 35%.

Given the complexity of need to learn `OCaml`, 35% maybe is a lot, but
given the complexity of installing `OCaml` on Windows, even 1% would be too much.

However, maybe said self-contained compile support should be implemented without removing said `OCaml` logic, I mean, to make `OCaml` an optional alternative, because:
* Maybe yet another Operating-System will be invented someday,
* And maybe  `OCaml` supports said OS, hence making things easy for Haxe to migrate.
* However, it's year 2024 and `OCaml` does **not** even support Windows fully yet, hence that's unlikely.

**Comment by Simn** [comment]
#6843
