### ISSUE TITLE
Add thousand seperator for numeric format

### ISSUE THREAD

**Issue by lulunac27a** [HaxeFoundation/haxe#11639]
I want to format numeric values with a thousand separator, like the number `1234` should be `1,234` and `123456789` should be `123,456,789`. I can't find the reference how to format the string.

**Comment by filt3rek** [comment]
Hej,
This already exists, see here : https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0018-number-separators.md
You can write that `trace( 1_000 )` or `trace( 123_456_789 )`

**Comment by Simn** [comment]
What he said.

**Comment by lulunac27a** [comment]
I want to print the numeral string with commas as thousand seperator, I found some like [thx.format](https://github.com/fponticelli/thx.format), but I can't find any functions or methods in Haxe standard library. How do I write the code using functions and methods from Haxe standard library?
