### ISSUE TITLE
Accessing super from a local function

### ISSUE THREAD

**Issue by Speedphoenix** [HaxeFoundation/haxe#11672]
I have a case like this

```haxe
class A {
	function trySomething() {
		trace("tried");
	}
}

class B extends A {
	function askConfirm(onConfirm:Void->Void) {}

	override function trySomething() {
		function continueTrying() {
			trace("more stuff");
			super.trySomething();
		}
		if (true) {
			askConfirm(() -> continueTrying());
		} else {
			continueTrying();
		}
	}
}
```

but `super.trySomething()` gives me

```Cannot access super inside a local function```
[Try Haxe](https://try.haxe.org/#AF8A79E3)

So I need to create a separate same-scope function that is meant to be used exclusively inside trySomething(), which I would rather not have to do

Is there any chance we'd be able to use super in local functions in the future?

**Comment by Simn** [comment]
No, this cannot be implemented on all targets.
