### ISSUE TITLE
reading hxb chunk ABD of StdTypes

### ISSUE THREAD

**Issue by PXshadow** [HaxeFoundation/haxe#11680]
Error loading StdTypes from go2hx.hl.zip
 => Failure("Compiler failure while reading hxb chunk ABD of StdTypes: index out of bounds\nPlease submit an issue at https://github.com/HaxeFoundation/haxe/issues/new\nAttach the following information:\nHaxe: 5.0.0-alpha.1+5e4e368\n")

OS: macos
I can also try out other Haxe versions as needed.

**Comment by kLabz** [comment]
Do you know how we could repro this?

**Comment by Simn** [comment]
Is this still relevant?

**Comment by PXshadow** [comment]
Probably not.
