### ISSUE TITLE
[optimisation] For loop is not removed if variable is used

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#11691]
For loop is not removed if variable is used.
In cases where inline methods are used, an array is created in the same way, although it is possible without it.
```haxe
var m:Float = 0;
for (e in [1, 2, 3]) m = Math.max(m, e);
trace(m);
```
Compiles to js:
```js
let m = 0;
m = Math.max(m,1);
m = Math.max(m,2);
m = Math.max(m,3);
console.log("Test.hx:7:",m);
```
But
```haxe
var m:Float = 0;
var a = [1, 2, 3];
for (e in a) m = Math.max(m, e);
trace(m);
```
Compiles to js:
```js
let m1 = 0;
let a = [1,2,3];
let _g = 0;
while(_g < a.length) m1 = Math.max(m1,a[_g++]);
console.log("Test.hx:12:",m1);
```

**Comment by Simn** [comment]
This is a very specific case and this optimization is only possible as long as the assigned variable doesn't leave the scope before the loop, which requires proper data flow analysis. It _might_ be possible to train the analyzer to handle this, but then we'd have the same problem as with late inlining, i.e. expanding expressions after they've already been transformed to the CFG representation.

On balance, I don't think this is worth the effort.
