### ISSUE TITLE
Switch Abstract<Null<Int>> generation differ from Null<Int>

### ISSUE THREAD

**Issue by yuxiaomao** [HaxeFoundation/haxe#11715]
Related issue on Hashlink: https://github.com/HaxeFoundation/hashlink/issues/696

I observed that for the following code, t1 and t2 are not generated the same way by the compiler:
	
```haxe
class Test {
	static var b1: Null<Int> = null;
	static var b2: Foo = null;
	static function main() {
		var t1 = switch (b1) {
			case 0: "A";
			case 1: "B";
			default: "C";
		};
		var t2 = switch (b2) {
			case A: "A";
			case B: "B";
			default: "C";
		};
		trace(t1, t2);
	}
}
enum abstract Foo(Null<Int>) {
	public var A = 0;
	public var B = 1;
}
```

dump pretty for these switches generated by the compiler (same if we check js source generated):

```haxe
var t1;
var _g = Test.b1;
if ((_g == null)) t1 = "C" else switch ((_g)) {
	case 0: t1 = "A";
	case 1: t1 = "B";
	default: t1 = "C"
};
var t2;
switch ((Test.b2)) {
	case 0: t2 = "A";
	case 1: t2 = "B";
	default: t2 = "C"
};
```
Note: If we added a `case null : "C"` in t2, the code generated becomes the same as t1.

I can manage it at genhl side, but I don't think the dump should differ here. Maybe there is a missing abstract null check somewhere?

**Comment by Simn** [comment]
The match compiler checks for explicit `Null<T>` on match subjects. This was a compromise in order to not generate implicit null-checks for pretty much all switches except integers.

My inclination is to not change this. I don't think that an abstract over `Null<T>` is necessarily different from a simple type such as `String`: both _could_ be `null` in the general case, but that doesn't mean that the compiler has to always check that. By being explicit with `Null<T>`, the user can communicate that they want some extra safety.

**Comment by yuxiaomao** [comment]
The code above print `C,C` on JS but `C,A` on HashLink (null implicit cast to 0 and do not fall in default category).

I can add a check in genhl - however, in the case where compiler already generated a check (in the case t1 or if an explicit case null is specified) this add an additional null check cost (not much though).

**Comment by Simn** [comment]
My understanding is that `switch(null)` on a type that isn't explicitly `Null<T>` is undefined behavior if there's no explicit `case null`. Yes it's an abstract over `Null<T>`, but I don't see why the pattern matcher should break the abstraction by looking at the underlying type here.

Also, this isn't the only situation where we have a difference between static and dynamic targets with regards to null-handling. We get `C,A` on JVM as well, and I very much don't want to change the switch generation there to account for such a special case.

**Comment by yuxiaomao** [comment]
I understand it's a special case, but if we give b2 Foo's value NULL, it can be confusing (trace `A` instead of `C`)

```haxe
class Test {
	static var b2: Foo = Foo.NULL;
	static function main() {
		var t2 = switch (b2) {
			case A: "A";
			case B: "B";
			default: "C";
		};
		trace(t2);
	}
}
enum abstract Foo(Null<Int>) {
	public var A = 0;
	public var B = 1;
	public var NULL = null;
}
```

**Comment by Simn** [comment]
This makes me realizes that we're already breaking the abstraction anyway via inlining the switch constructors... this still seems strange to me, but in that case I agree it's better to check the underlying type of the abstract. I'll make a branch and see how terrible such a change is.

**Comment by yuxiaomao** [comment]
Additionally, I'm not sure if it's intended but it's not intuitive for me: if I comment out "default" case in the last example, the compiler does not generate error for unmatched pattern, even `Foo.NULL` is not in the list. And t2 will become "null"
