### ISSUE TITLE
local static in inlined function gets optimized away with analyzer

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#11725]
With analyzer turned on, and `inline` the variable won't exist. Removing `inline` or disabling analyzer makes it work. Reproducible on all Haxe versions it seems.
```haxe
function main() foo();

inline function foo() {
	static var count = 5;
	trace(--count);
}
```
Compiles down to:
```js
function Test_main() {
	console.log("Test.hx:5:",4);
}
```

**Comment by Simn** [comment]
The optimization is a symptom, the real problem here must be the inliner. Without thinking about it too much, static vars should probably not be duplicated like normal vars when inlining.

**Comment by Simn** [comment]
Actually I'm not entirely sure if static local variables should even be allowed in inline functions, but I'm basing that mostly on the fact that thinking about it makes my head hurt.

**Comment by kLabz** [comment]
Yeah it seems to be that the fix would be to disallow that.. but then what about call site inlining? Would still fail, right?

**Comment by Simn** [comment]
For cases like here we can detect it at definition-level, for call-site inlining we have to detect it during inlining.

**Comment by Simn** [comment]
I've made it error when inlining because that covers both cases and we do this for some other things like `super` and non-final return as well.
