### ISSUE TITLE
lix upgraded to 4.3.5 and haxelib throws an error 

### ISSUE THREAD

**Issue by chrisanderson** [HaxeFoundation/haxe#11728]
tested running haxelib updates for haxe 4.3.5 and get this error:

> dyld[8129]: Library not loaded: @rpath/libneko.2.dylib
>   Referenced from: <D565005C-A37F-32EB-ABAF-B61930531BAD> /Users/chris/haxe/versions/4.3.5/haxelib
>   Reason: tried: '/Users/chris/haxe/neko/libneko.2.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/local/lib/libneko.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libneko.2.dylib' (no such file), '/usr/local/lib/libneko.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libneko.2.dylib' (no such file)

used lix to revert to an older version of haxe (in my test it was 3.4.7) and haxelib worked as expected

on an m1 mac

**Comment by tobil4sk** [comment]
Lix needs to be updated to support installing arm64 builds of neko.

**Comment by RblSb** [comment]
For now you can download new neko release and patch older neko files, worked for me
https://github.com/HaxeFoundation/neko/releases/tag/v2-4-0

**Comment by chrisanderson** [comment]
roger that guys.  

@tobil4sk, makes sense to me. 
@RblSb appreciate the info, will test.

thank you both for the info and help.

**Comment by chrisanderson** [comment]
@RblSb (also thank you too @tobil4sk for the neko release),  using neko 2.4.0 worked well in my case
