### ISSUE TITLE
Code does not work after return without semicolon

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#11752]
If you forget to put a semicolon, the code will be compiled, but not part of the code will be executed. This can be a bug in a large project that will be difficult to catch.
Example:
```haxe
function isPositive(value:Null<Int>):Void {
  if (value == null) return
  if (value > 0)
    trace('Positive!');
  else if (value < 0)
    trace('Negative!');
}
```

Possible solution: make the semicolon mandatory.
First valid code example:
```haxe
function isPositive(value:Null<Int>):Void {
  if (value == null) return
  if (value > 0)
    trace('Positive!');
  else if (value < 0)
    trace('Negative!');;
}
```
;; - the compiler might throw an error if this semicolon is missing. It may seem strange, but it provides enough clarity.
Second valid code example:
```haxe
function isPositive(value:Null<Int>):Void {
  if (value == null) return;
  if (value > 0)
    trace('Positive!');
  else if (value < 0)
    trace('Negative!');
}
```
Example with brackets:
```haxe
function isPositive(value:Null<Int>):Void {
  if (value == null) return
  if (value > 0) {
    trace('Positive!');
  } else if (value < 0) {
    trace('Negative!');
  };
}
```

**Comment by tobil4sk** [comment]
The first example would also fail to compile if this change was made: #6477

**Comment by Simn** [comment]
This is simply because it's parsed as `return (if (...) ... else ...)`.

**Comment by koteelok** [comment]
> This is simply because it's parsed as `return (if (...) ... else ...)`.

Everyone acknowledges that, the problem is that this is pretty annoying behavior, and it would be very nice if the compiler could warn the developer about such things.

Debugging bugs caused by this can be very VERY annoying.

**Comment by Simn** [comment]
I see nothing actionable here, the only thing that's "weird" is the indentation. If you tab it like this:

```haxe
function isPositive(value:Null<Int>):Void {
  if (value == null) return
    if (value > 0)
      trace('Positive!');
    else if (value < 0)
      trace('Negative!');
}
```

then it very much looks like something someone might want to write. The compiler doesn't care about how you indent things, so if anything this could be caught by a tool like haxe-checkstyle.
