### ISSUE TITLE
haxe.ds.ObjectMap with null key

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#11759]
Hej,

Idk if it has already been discussed but having a `null` key on `haxe.ds.ObjectMap` works fine on some plateforms and fails with others.
And Idk if it's ok with that because the answer will be "it's (stupid) plateform dependant" or if it should work the same way on all plateforms 

Here's a minimal example : https://try.haxe.org/#0a9596a7
```haxe
class Foo {
	public function new() {}
}

class Test {
	static function main() {
		var h:Map<Foo, Bool> = [null => true];
		trace(h);
	}
}
```
Works well on Eval and HL but fails on JS and Neko (I haven't tried on other plateforms because I've done that on try.haxe.org)
```
Called from ? line 1
Called from Test.hx line 7
Uncaught exception - Invalid field access : __id__
```
Thanks for reading,
Regards,

**Comment by Simn** [comment]
This is platform-dependent indeed.
