### ISSUE TITLE
Assertion failed when using `Std.string()` with specific `toString()` function

### ISSUE THREAD

**Issue by player-03** [HaxeFoundation/haxe#11770]
When I use a build macro to generate an abstract's `toString()` function, and that function refers to a variable declared by another build macro, the completion server prints a "Failed to locate variable declaration" error.

Compilation still works (and I think the completion server is then able to locate the declaration), so this is low priority. But it said to submit an issue so I did.

<details>
<summary>Full error message</summary>
<pre>
File "src/core/globals.ml", line 156, characters 1-7: Assertion failed
test/Test.hx:4: lines 4-6 Compiler failure: Failed to locate variable declaration
test/Test.hx:4: lines 4-6 Please submit an issue at https://github.com/HaxeFoundation/haxe/issues/new
test/Test.hx:4: lines 4-6 Attach the expression example and the following information:
Haxe: 4.3.4; OS type: unix;
File "src/filters/renameVars.ml", line 336, characters 20-27
Called from RenameVars.run in file "src/filters/renameVars.ml", line 336, characters 2-27
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from TUnification.rec_stack_loop in file "src/core/tUnification.ml", line 458, characters 10-15
Called from FiltersCommon.run_expression_filters.process_field in file "src/filters/filtersCommon.ml", line 75, characters 23-71
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from FiltersCommon.run_expression_filters in file "src/filters/filtersCommon.ml", line 81, characters 2-46
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Filters.run in file "src/filters/filters.ml", line 1013, characters 1-96
Called from Compiler.filter in file "src/compiler/compiler.ml", line 305, characters 1-38
Called from Compiler.compile in file "src/compiler/compiler.ml", line 335, characters 2-17
Called from Compiler.compile_safe in file "src/compiler/compiler.ml", line 354, characters 1-5
Called from Compiler.compile_ctx.run in file "src/compiler/compiler.ml", line 441, characters 2-157
Called from Compiler.catch_completion_and_exit in file "src/compiler/compiler.ml", line 415, characters 2-9
Called from Compiler.HighLevel.entry.loop in file "src/compiler/compiler.ml", line 637, characters 5-43
Called from Compiler.HighLevel.entry in file "src/compiler/compiler.ml", line 647, characters 13-22
Called from Server.process in file "src/compiler/server.ml", line 979, characters 1-39
Called from Server.wait_loop in file "src/compiler/server.ml", line 1040, characters 3-30
Called from Compiler.HighLevel.entry.loop in file "src/compiler/compiler.ml", line 637, characters 5-43
Called from Compiler.HighLevel.entry in file "src/compiler/compiler.ml", line 647, characters 13-22
Called from Server.process in file "src/compiler/server.ml", line 979, characters 1-39
</pre>
</details>

To reproduce, you only need two files:

Test.hx

```haxe
package;

class Test {
	public static function main():Void {
		Std.string(new Abstract());
	}
}
```

Abstract.hx

```haxe
package;

import haxe.macro.Expr;

#if !macro @:build(Builder.buildAbstract()) #end
abstract Abstract(Impl) {
}

#if !macro @:build(Builder.buildImpl()) #end
class Impl {
}

class Builder {
	public static function buildAbstract():Array<Field> {
		return (macro class Abstract {
			public inline function new() {
				this = new Impl();
			}
			@:to public inline function toString():String {
				return "" + this.field;
			}
		}).fields;
	}
	
	public static function buildImpl():Array<Field> {
		return (macro class Impl {
			public var field:Int = 0;
			public inline function new() {
			}
		}).fields;
	}
}
```

**Comment by Simn** [comment]
This doesn't reproduce for me, are there any compilation parameters involved?

**Comment by player-03** [comment]
Now that you mention it, I'm not seeing it anymore either. Perhaps several rounds of revisions put the cache into an inconsistent state. Though I'm almost certain I tried restarting the language server, which normally fixes such bugs.

Closing this for now, and I'll open it back up if I ever figure out more.
