### ISSUE TITLE
X509 - Certificate verification failed, e.g. CRL, CA or signature check failed

### ISSUE THREAD

**Issue by AlexPlayzOG** [HaxeFoundation/haxe#11781]
When I try to enter this command -haxelib install *what I want to install*-, I get this error:

*X509 - Certificate verification failed, e.g. CRL, CA or signature check failed**

I don't know that to do!

**Comment by tobil4sk** [comment]
This is due to a neko bug, see here for a workaround: https://github.com/HaxeFoundation/neko/issues/196

**Comment by AlexPlayzOG** [comment]
Oh, okay. Thanks!
