### ISSUE TITLE
Iterating over Maps seems to produce buggy Python code

### ISSUE THREAD

**Issue by interstar** [HaxeFoundation/haxe#11809]
Here's a simple loop I wrote in Haxe

```
for (entry in options.keyValueIterator()) {
  defaultOptions[entry.key] = entry.value;
}
```

However, when compiled to Python, this gets turned into
```
   entry_map = _hx_map                                                                                                                                 
   entry_keys = _hx_map.keys()
   while entry_keys.hasNext():
     key = entry_keys.next()
     entry_value = entry_map.get(key)
     entry_key = key
     v = entry_value
     defaultOptions.h[entry_key] = v
```
Which fails because
```
    while entry_keys.hasNext():
          ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict_keys' object has no attribute 'hasNext'
```
Is this a bug in Haxe?

**Comment by interstar** [comment]
After a bit of experimentation I realize that this isn't something that happens when I create the Map in Haxe code.

Presumably Haxe is making a Python version of its own Map class from inside Haxe that's been compiled to Python.

The issue is when I try to pass a Python dictionary from Python code to the library I wrote in Haxe, assuming it's the same as a Haxe Map.

In a sense, this resolves the question. Perhaps we can't expect compiled Haxe to use native dictionary type data in the various target languages.

OTOH, the question still remains of how to pass a dictionary-like structure from the target language into a library written in Haxe.

**Comment by interstar** [comment]
After a bit of experimentation I realize that this isn't something that happens when I create the Map in Haxe code.

Presumably Haxe is making a Python version of its own Map class from inside Haxe that's been compiled to Python.

The issue is when I try to pass a Python dictionary from Python code to the library I wrote in Haxe, assuming it's the same as a Haxe Map.

In a sense, this resolves the question. Perhaps we can't expect compiled Haxe to use native dictionary type data in the various target languages.

OTOH, the question still remains of how to pass a dictionary-like structure from the target language into a library written in Haxe.

**Comment by tobil4sk** [comment]
If you want to take a python dict, you should use: https://api.haxe.org/python/Dict.html
