### ISSUE TITLE
haxe.exe is no longer available on Win7

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#11816]
I've found that after that since 526e57c, running haxe.exe in win7 will pop up the following error :

```
The procedure entry point "GetSystemTimePreciseAsFileTime" could not be located in the dynamic link library KERNEL32.dll
```

**Comment by moxie-coder** [comment]
Windows 7 has long since been discontinued, so of course Haxe eventually is gonna stop supporting it like everything else

**Comment by Simn** [comment]
Yes at some point we'll have to drop older versions, especially if the problem comes from a dependency, as the commit you found suggests.
