### ISSUE TITLE
Cannot compile haxe 4.3.5 from git tag

### ISSUE THREAD

**Issue by singpolyma** [HaxeFoundation/haxe#11821]
```
git clone git@github.com:HaxeFoundation/haxe.git
cd haxe
git checkout 4.3.5
make haxe
```

```
File "src/context/typecore.ml", line 297, characters 24-59:
297 | 				if not (List.exists (ExtLib.String.starts_with p.pfile) ctx.com.std_path) then begin
      				                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type prefix:string -> bool
       but an expression was expected of type 'a -> bool
make: *** [Makefile:81: haxe] Error 1    
```

**Comment by singpolyma** [comment]
It's the same with or without submodule update.

This is on debian stable.

ocaml version: 5.2.0

**Comment by singpolyma** [comment]
It seems this was fixed by 1ce738c17e6982ecedb2e5b9ba0f0f6fcbecc064 but I'm not sure how the older versions were built...

**Comment by Simn** [comment]
Thank you for the investigation! Could you try if it works when you move that line below the `let m = Abstract.get_underlying_type a pl in` line?

I'd like to extract a reproducible example for this either way, but first we have understand why this goes wrong.

**Comment by singpolyma** [comment]
@Simn I think you meant that comment to go on #11820 ?

**Comment by Simn** [comment]
Oops, indeed!

**Comment by Simn** [comment]
See #11787
