### ISSUE TITLE
Tools.hxml missing

### ISSUE THREAD

**Issue by Le-Fleurrr** [HaxeFoundation/haxe#11828]
When I try to run haxelib run lime setup flixel this error shows up and I have no idea how to fix it

Error: Could not process argument tools.hxml (file not found)
Invalid character:

**Comment by tobil4sk** [comment]
This probably a lime problem, see the issue tracker there for more help: https://github.com/openfl/lime. You probably have an issue with your lime install.

**Comment by Le-Fleurrr** [comment]
Huh thanks
