### ISSUE TITLE
-

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#11835]
hi Nicolas as a long time haxe user who you have know personally, I am worried the community is fragmenting.
I am very impressed with Chris work on the OpenFL community, he helps many people far more than I am able and he is evolving openfl forwards, maybe not to your ideals..  but certain with others to a level that may actually bring haxe to masses yet he has been banned from Haxe discord for trying to help. I have not followed why he was banned but have noted him as a good moderator and more than fair perhaps a good replacement to notbilly, chris is far more rightwing than but tolerant of others and always helpful.
I was banned a few years back and Semmi who does some cool stuff but also is quite alternative creatively, was banned. At the time I was worried it was just me... but I am less sure now.
There seems a problem and I am unsure that NotBilly is representing the wider creative community, especially the ex flash that are often the ones that take code and make it really shine and bring some excitement. Haxe is too small for such infighting some tolerance to differences is needed, from people that are autistic, adhd,  rightwing. trump, anti-trump, etc... there needs to be more tolerance to opinions and some ability to let a little steam and opinions out, and not such binary moderation? Maybe you disagree and I am sure it annoys you, but talents like you and simm are maybe not so open as say some of the openfl and young flixelers, but it takes all to make a language shine. And as an old to code user I am often excited by the young ones trying to challenge what I thought was possible even if they are gay, trans, black, obsessed with opensource and anti government or nor. Currently the haxe server is not serving all the haxe community and frankly it makes users think ok well maybe we need to use something else.  Perhaps Hugh you can talk to Nicolas but I have not used the haxe sever or even looked or interacted it for a few years and that is crazy,  I do not feel that is ideal for a language that has so much potential. Languages need to respect the users and I am not sure Haxe does well enough. Feel free to delete this issue for obvious reasons, and I know you hate conflict,   but please do consider my thoughts, I only have haxe and the ecosystem at heart I do not want to create problems, but was so shocked Chris was blocked form haxe discord I felt I needed to be vocal. Best Justin.

**Comment by ianharrigan** [comment]
Is this a joke? Can we stop with this appeal to authority? Its childish.

**Comment by nanjizal** [comment]
@ncannasse please review. Fair to close but please consider, that heaps using haxe server which so many are banned from is not ideal. Haxe need to be inclusive since many people learning haxe do so via flixel and yet haxe server bans one of the main devs of openfl for questionable reasons. Ian is biased to nobilly and maybe his reasons are correct but I would like some more consideration taken, I have not been able to use the main haxe discord for several years and that I feel is sad.
