### ISSUE TITLE
Y Combinator fails in Hashlink

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#11841]
It has worked on other platforms in the past and does have uses.

```haxe
typedef Recursive<F>         = Recursive<F> -> F;
typedef YDef<P,R>              = Recursive<P -> R>; 
```
[see here](https://try.haxe.org/?module-a=Main#5Bd65C1B)

**Comment by Simn** [comment]
#11839 is probably a simpler version of that.
