### ISSUE TITLE
Should order of froms on an abstract matter?

### ISSUE THREAD

**Issue by singpolyma** [HaxeFoundation/haxe#11858]
For example without this patch https://github.com/singpolyma/thenshim/commit/58de7ec700c357600d3b6150fa06da615ab07330 I find that haxe 4.3.2 infers `T->R` even when `R` is a `Promise<X>` resulting in type inference of `T->Promise<Promise<X>>` at the call site, which then fails to compile. Switching the order like this fixes it but I'm wondering if the order is meant to matter in haxe or if this is a bug?

**Comment by Antriel** [comment]
Possibly related: https://github.com/HaxeFoundation/haxe/issues/9980

**Comment by Simn** [comment]
Yes this is how it is specified. Whether or not that's a good specification is another question, but at this point I can't see us changing it.
