### ISSUE TITLE
Compiler doesn't allow BOOB constraints

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#11870]
```haxe
function copyValue<B:O, O:B>() {}
```

```
Fatal error: exception CamlinternalLazy.Undefined
Raised at CamlinternalLazy.raise_undefined.(fun) in file "camlinternalLazy.ml", line 22, characters 42-57
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
Called from Typeload.type_type_params.(fun).loop in file "src/typing/typeload.ml", line 769, characters 21-42
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 773, characters 4-25
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
Called from Typeload.type_type_params.(fun).loop in file "src/typing/typeload.ml", line 769, characters 21-42
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 773, characters 4-25
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 776, characters 47-71
Called from Typecore.flush_pass.loop in file "src/context/typecore.ml", line 490, characters 4-7
Called from TypeloadModule.load_module in file "src/typing/typeloadModule.ml", line 849, characters 31-93
Called from Typeload.load_module in file "src/typing/typeload.ml", line 175, characters 2-33
Called from TyperDotPath.resolve_qualified in file "src/typing/typerDotPath.ml", line 72, characters 10-48
Called from TyperDotPath.resolve_dot_path.loop in file "src/typing/typerDotPath.ml", line 122, characters 5-58
Called from Typer.handle_efield.dot_path in file "src/typing/typer.ml", line 544, characters 4-44
Called from Typer.handle_efield.loop in file "src/typing/typer.ml", line 600, characters 3-62
Called from Typer.type_call_target in file "src/typing/typer.ml", line 1673, characters 9-123
Called from Typer.type_call_access in file "src/typing/typer.ml", line 1704, characters 12-56
Called from Typer.type_expr in file "src/typing/typer.ml", line 1812, characters 14-50
Called from Std.finally in file "src/std.ml", line 24, characters 6-9
Re-raised at Std.finally in file "src/std.ml", line 26, characters 23-30
Called from Typer.type_vars.(fun) in file "src/typing/typer.ml", line 704, characters 13-118
Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
Called from Typer.type_vars in file "src/typing/typer.ml", line 693, characters 10-1023
Called from Typer.type_block.loop in file "src/typing/typer.ml", line 756, characters 27-94
Called from Typer.type_block in file "src/typing/typer.ml", line 759, characters 9-19
Called from Typer.type_expr in file "src/typing/typer.ml", line 1890, characters 10-38
Called from TypeloadFunction.type_function in file "src/typing/typeloadFunction.ml", line 63, characters 2-25
Called from Std.finally in file "src/std.ml", line 24, characters 6-9
Re-raised at Std.finally in file "src/std.ml", line 26, characters 23-30
Called from TypeloadFields.TypeBinding.bind_method.bind in file "src/typing/typeloadFields.ml", line 856, characters 13-82
Called from Typecore.make_lazy.(fun) in file "src/context/typecore.ml", line 511, characters 11-14
Called from TypeloadFields.finalize_class.(fun) in file "src/typing/typeloadFields.ml", line 1589, characters 53-66
Called from Typecore.flush_pass.loop in file "src/context/typecore.ml", line 490, characters 4-7
Called from Finalization.finalize in file "src/typing/finalization.ml", line 89, characters 1-37
Called from Compiler.do_type in file "src/compiler/compiler.ml", line 310, characters 2-275
Called from Compiler.compile in file "src/compiler/compiler.ml", line 384, characters 37-80
Called from Compiler.compile_safe in file "src/compiler/compiler.ml", line 424, characters 1-5
Called from Compiler.compile_safe in file "src/compiler/compiler.ml", line 462, characters 5-23
Called from Compiler.compile_ctx.run in file "src/compiler/compiler.ml", line 502, characters 2-135
Called from Compiler.catch_completion_and_exit in file "src/compiler/compiler.ml", line 476, characters 2-9
Called from Compiler.HighLevel.entry.loop in file "src/compiler/compiler.ml", line 705, characters 5-43
Called from Compiler.HighLevel.entry in file "src/compiler/compiler.ml", line 717, characters 13-22
Called from Server.process in file "src/compiler/server.ml", line 803, characters 1-39
Called from Dune__exe__Haxe in file "src/compiler/haxe.ml", line 53, characters 0-56
```

**Comment by kLabz** [comment]
Was that with TLazy hxb reader?

**Comment by Simn** [comment]
No it's something else entirely related to recursive constraints. Will try to repro.

**Comment by Simn** [comment]
This turned out to be very easy to reproduce.

**Comment by moxie-coder** [comment]
> ```hx
> function copyValue<B:O, O:B>() {}
> ```
> 
>  ```
> Fatal error: exception CamlinternalLazy.Undefined
> Raised at CamlinternalLazy.raise_undefined.(fun) in file "camlinternalLazy.ml", line 22, characters 42-57
> Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
> Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
> Called from Typeload.type_type_params.(fun).loop in file "src/typing/typeload.ml", line 769, characters 21-42
> Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
> Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 773, characters 4-25
> Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
> Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
> Called from Typeload.type_type_params.(fun).loop in file "src/typing/typeload.ml", line 769, characters 21-42
> Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
> Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 773, characters 4-25
> Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
> Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
> Called from Typeload.type_type_params.(fun) in file "src/typing/typeload.ml", line 776, characters 47-71
> Called from Typecore.flush_pass.loop in file "src/context/typecore.ml", line 490, characters 4-7
> Called from TypeloadModule.load_module in file "src/typing/typeloadModule.ml", line 849, characters 31-93
> Called from Typeload.load_module in file "src/typing/typeload.ml", line 175, characters 2-33
> Called from TyperDotPath.resolve_qualified in file "src/typing/typerDotPath.ml", line 72, characters 10-48
> Called from TyperDotPath.resolve_dot_path.loop in file "src/typing/typerDotPath.ml", line 122, characters 5-58
> Called from Typer.handle_efield.dot_path in file "src/typing/typer.ml", line 544, characters 4-44
> Called from Typer.handle_efield.loop in file "src/typing/typer.ml", line 600, characters 3-62
> Called from Typer.type_call_target in file "src/typing/typer.ml", line 1673, characters 9-123
> Called from Typer.type_call_access in file "src/typing/typer.ml", line 1704, characters 12-56
> Called from Typer.type_expr in file "src/typing/typer.ml", line 1812, characters 14-50
> Called from Std.finally in file "src/std.ml", line 24, characters 6-9
> Re-raised at Std.finally in file "src/std.ml", line 26, characters 23-30
> Called from Typer.type_vars.(fun) in file "src/typing/typer.ml", line 704, characters 13-118
> Called from Stdlib__List.map in file "list.ml", line 92, characters 20-23
> Called from Typer.type_vars in file "src/typing/typer.ml", line 693, characters 10-1023
> Called from Typer.type_block.loop in file "src/typing/typer.ml", line 756, characters 27-94
> Called from Typer.type_block in file "src/typing/typer.ml", line 759, characters 9-19
> Called from Typer.type_expr in file "src/typing/typer.ml", line 1890, characters 10-38
> Called from TypeloadFunction.type_function in file "src/typing/typeloadFunction.ml", line 63, characters 2-25
> Called from Std.finally in file "src/std.ml", line 24, characters 6-9
> Re-raised at Std.finally in file "src/std.ml", line 26, characters 23-30
> Called from TypeloadFields.TypeBinding.bind_method.bind in file "src/typing/typeloadFields.ml", line 856, characters 13-82
> Called from Typecore.make_lazy.(fun) in file "src/context/typecore.ml", line 511, characters 11-14
> Called from TypeloadFields.finalize_class.(fun) in file "src/typing/typeloadFields.ml", line 1589, characters 53-66
> Called from Typecore.flush_pass.loop in file "src/context/typecore.ml", line 490, characters 4-7
> Called from Finalization.finalize in file "src/typing/finalization.ml", line 89, characters 1-37
> Called from Compiler.do_type in file "src/compiler/compiler.ml", line 310, characters 2-275
> Called from Compiler.compile in file "src/compiler/compiler.ml", line 384, characters 37-80
> Called from Compiler.compile_safe in file "src/compiler/compiler.ml", line 424, characters 1-5
> Called from Compiler.compile_safe in file "src/compiler/compiler.ml", line 462, characters 5-23
> Called from Compiler.compile_ctx.run in file "src/compiler/compiler.ml", line 502, characters 2-135
> Called from Compiler.catch_completion_and_exit in file "src/compiler/compiler.ml", line 476, characters 2-9
> Called from Compiler.HighLevel.entry.loop in file "src/compiler/compiler.ml", line 705, characters 5-43
> Called from Compiler.HighLevel.entry in file "src/compiler/compiler.ml", line 717, characters 13-22
> Called from Server.process in file "src/compiler/server.ml", line 803, characters 1-39
> Called from Dune__exe__Haxe in file "src/compiler/haxe.ml", line 53, characters 0-56
> ```

lol, boob clever hehehe
