### ISSUE TITLE
[Lua] do .. while{}  is converted to while do 

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#11886]
Not sure is this is a major problem, but when we initialize a variable in the first step and check it in while() at the end , the reordering  ( passing null first before assigning ) can lead to a null error.
If this is expected behavior, please close the ticket.
Example
```haxe
var num:BigInt_;
do {
	num = random(this.bitLength());
} while (BigIntArithmetic.compare(num, BigInt.ZERO) == 0);
```
BigIntArithmetic.compare will give error as num is null (for Lua)

**Comment by Simn** [comment]
I think #11807 fixed this, but please verify!

**Comment by flashultra** [comment]
I couldn't run Haxe Lua on my local PC ( windows) , but on Github CI Lua failed ( https://github.com/HaxeFoundation/haxe/actions/runs/12349062541/job/34459213928#step:11:22058 ) . I'm not sure is this fix applied on Github actions CI or not.

**Comment by tobil4sk** [comment]
It won't have applied the change unless you've merged `development` since the other PR was merged

**Comment by tobil4sk** [comment]
> I couldn't run Haxe Lua on my local PC ( windows)

Out of curiosity, what issues did you run into when trying to run it?

**Comment by flashultra** [comment]
It was a nightmare with dependencies; trying different versions of Lua (5.1 to 5.3); unable to install packages -
( lrexlib-pcre2 )

About the current issue - it works with https://github.com/HaxeFoundation/haxe/pull/11807

**Comment by tobil4sk** [comment]
Yeah it's a bit of a pain installing all the native dependencies on windows, hopefully they shouldn't be required to run a small program with a do while loop. In case they are for whatever reason, it should be possible to disable them with the `-D lua-vanilla` flag.
