### ISSUE TITLE
haxe beginner here

### ISSUE THREAD

**Issue by austistuck** [HaxeFoundation/haxe#11900]
for a really odd reason when using flixel it will sometimes delete the whole project I'm working on and rarely the entirety of vs code.

**Comment by moxie-coder** [comment]
> for a really odd reason when using flixel it will sometimes delete the whole project I'm working on and rarely the entirety of vs code.

this isn’t the right repo for flixel issues, make this in flixels own repo

**Comment by kLabz** [comment]
Or even discord for this kind of questions.
