### ISSUE TITLE
"Invalid field access: @AnimatedSprite"

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#1896]
If you use a parameter that's the same as the package name, you get a strange crash on Neko:

<pre>package spritesheet;

import flash.display.Sprite;

class AnimatedSprite extends Sprite {
    
    
    public function new (spritesheet:Dynamic = null) {
        
        super ();
        
    }
    
    
}</pre>

<pre>Called from ? line 1
Called from ApplicationMain.hx line 67
Called from flash/Lib.hx line 109
Called from flash/Lib.hx line 106
Called from ApplicationMain.hx line 116
Called from C:\HaxeToolkit\haxe/std/neko/_std/Type.hx line 106
Called from ApplicationMain.hx line 227
Called from ApplicationMain.hx line 227
Called from Main.hx line 12
Called from spritesheet/AnimatedSprite.hx line 7
Uncaught exception - Invalid field access : @AnimatedSprite</pre>

Would it be possible to handle this case on Neko, or to throw a compile error? This was very strange to track down, and I believe it used to work (or it may be caused because the package was "com.eclecticdesignstudio.spritesheet" and now it is "spritesheet")

**Comment by scriptorum** [comment]
I still have this issue on Haxe 3.1.3, for both Neko and HTML5 targets. If the first part of the package name is also the name of the first parameter of the constructor, a runtime exception occurs complaining about the name of the class. Very odd. Have not tried it on 3.2.
