### ISSUE TITLE
Context.typeof does not work in MacroType for typedef

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#1899]
import haxe.macro.MacroType;
	class TypeOfInMacroType
	{
		public static function main():Void
		{
			// OK!
			var typeOf0:MacroType<[ haxe.macro.Context.typeof([].length) ]> = 1;
		}
	}
	// Error!
	typedef TypeOf0 = MacroType<[ haxe.macro.Context.typeof([].length) ]>;

The above code does not compile in Haxe 3.0.0:

	$ haxe -x TypeOfInMacroType.hx
	TypeOfInMacroType.hx:12: characters 56-65 : Array<Unknown<0>> has no field length

**Comment by ncannasse** [comment]
@Simn could you deprecate MacroType in 3.2 ? (and document @:genericBuild in Manual)

**Comment by Atry** [comment]
I found that Haxe 3.3 changed the resolution behavior of `typedef` https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.3.0#syscommand-and-sysioprocess

> typedef types are no longer checked eagerly. This might delay execution of some `@:build` or `@:genericBuild` macros. Note that type building order is undefined anyway.

Does that mean this issue is resolved in Haxe 3.3 ?

**Comment by ncannasse** [comment]
Uhm, I don't remember getting any warning, and I still have MacroType code in my codebase.

**Comment by Simn** [comment]
I don't understand what this issue is about, MacroType didn't change at all to my knowledge. It's still affected by standard typing order restrictions though.
