### ISSUE TITLE
3.0.0 Linux binaries dont work on Debian.

### ISSUE THREAD

**Issue by chenz** [HaxeFoundation/haxe#1928]
The 3.0.0 Linux binaries require GLIBC version 2.15. This means they don't work on Debian (eglibc 2.13) and probably other older/conservative distros.

Error message:

./haxe: /lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.15' not found (required by ./haxe)

**Comment by Simn** [comment]
ping @waneck again

**Comment by TheHippo** [comment]
glibc 2.13 was released in [February 2011](http://en.wikipedia.org/wiki/GNU_C_Library#Version_history). If you still using this you probably run into a lot of problems when downloading binaries and should be used to compile everything by hand.

I personally use a one year old ubuntu installation which uses 2.19, just for comparison. Aside from Debian 7, which should get an update to 8 [very soon](https://lists.debian.org/debian-devel-announce/2015/03/msg00016.html), the oldest glibc version used by some long term distro to this date seems to be 2.16.

**Comment by waneck** [comment]
Yeah, I'm not sure if it makes sense anymore. I still plan to do a revamp on the build system for 3.2, and build linux packages for the major distributions, and maybe add an ubuntu ppa / nightly one. But I don't think this will involve linking to an older glibc at the moment.
