### ISSUE TITLE
Unfounded lowercase class name errors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#1932]
I'm constantly getting this error whenever I type a class name plus a dot (so that auto-completion shows up) in FD 4.4.3 (also happened in earlier versions IIRC):

`Error: Class name must start with uppercase character`

([location in main.ml](https://github.com/HaxeFoundation/haxe/blob/development/main.ml?source=cc#L168))

This happens consistently across all of my projects and classes.

Interestingly enough, a similar, but not the same thing happens in Sublime Text 2 (2.0.1, Build 2217) - this is the error I get there:

`ERROR: Display file 'playstate.hx' should not start with a lowercase letter.`

([location in main.ml](https://github.com/HaxeFoundation/haxe/blob/development/main.ml?source=cc#L1122))

I am 100% sure that these errors are unfounded - **none** of the class names actually do start with a lowercase letter. The `playstate.hx` class in the error is actually named `PlayState.hx`.

I'm not the only person with this issue. Rowdeh from IRC (not a GitHub user) is having exactly the same issues in both IDEs. In his opinion, a conversion to lowercase is happening somwhere in `main.ml` which causes this issue.

My haxe version: 3.0.0
OS: Win 7 64-bit
haxelib list paste:

```
actuate: [1.6.3]
flixel: 2.0.0-alpha.2 [2.0.0-alpha.3]
HaxePunk: [2.3.0]
hxcpp: [3.0.2]
nape: [2.0.9]
nme: 3.5.6 [4.0.2]
openfl: [1.0.0] 1.0.0-rc.2 1.0.0-rc.3
openfl-html5: [1.0.0] 1.0.0-rc.2
openfl-native: [1.0.0] 1.0.0-rc.2
openfl-tools: [1.0.0] 1.0.0-rc.3
```

I have tried switching to the openfl rc's. No change.

@Simn told me in #haxe this might be related to some invalid line / argument in the .nmml (or .xml as of openfl I guess). So here's a pastie of that: [http://pastebin.com/Yv8krPhs](Click)

It's the .xml which is generated by the HaxeFlixel template, but some other HaxeFlixel users I asked don't seem to have the same issue. And Rowdeh is not using HaxeFlixel at all.

**Edit:** Might be worth mentioning @ousado thinks this is an issue regarding completion invoking.

**Comment by GimmickyApps** [comment]
I am getting this error on test case files after installing [munit](https://github.com/massiveinteractive/MassiveUnit) 2.1.2 and trying to get started with it.  It happens even on the autogenerated ExampleTest.hx if I try to add an "Assert." line to see what Assert has.  Meanwhile, the example tests themselves compile and run fine with munit.

Win7/64, FlashDevelop 5.0.2.2, Haxe 3.2.1, and haxelib list gives:

actuate: [1.8.6]
advanced-layout: 0.6.2 0.6.3 git [dev:C:\HaxeToolkit\haxe\lib\advanced-layout/git]
assetsmanager: [1.2.0]
awe6: 2.5.732 [2.6.489]
firetongue: 1.0.0 git [dev:C:\HaxeToolkit\haxe\lib\firetongue/git]
flixel-addons: 1.1.1 git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel-demos: [1.1.2]
flixel-templates: [1.0.2]
flixel-tools: 1.1.1 [1.1.2]
flixel-ui: 1.0.2 git [dev:C:\HaxeToolkit\haxe\lib\flixel-ui/git]
flixel: 3.3.12 git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]
hamcrest: [2.0.1]
haxelib_client: [3.2.0-rc.3]
hscript: [2.0.5]
hxcpp: 3.2.193 [3.2.205]
lime-tools: [1.5.7]
lime: 2.8.2 2.8.3 [2.9.0]
mconsole: [1.6.0]
mcover: [2.1.1]
mlib: [2.0.2]
monax: 1.4.0 [1.5.1]
msignal: 1.2.2 [1.2.4]
munit: [2.1.2]
nape-hacks: [2.0.1]
nape-symbolic: [2.0.1]
nape: [2.0.19]
openfl: 3.5.3 [3.6.0]
Parsex: [1.4.0]
promhx: [1.0.21]
scrollable-area: [0.0.1-alpha]
svg: 1.0.8 [1.0.9]
swf: [2.2.0]
task: [1.0.7]

**Comment by NemoStein** [comment]
I have the EXACT same problem as @GimmickyApps, in a much simpler project.
In fact, I just created a new OpenFL project directly from FD 5.1.1.3 and changed my Main.hx to this
```
package;
import openfl.display.Sprite;

class Main extends Sprite 
{
	public function new() 
	{
		super();
		x.|
	}
}
```
The pipe is where I try to autocomplete (ctrl+space) and get the error:
```
Error: Could not process argument #--macro
Class name must start with uppercase character
```

Also, I found one reference to the "#--macro" in the .hxproj file:
```<option additional="--remap flash:openfl&#xA;-debug #--macro keep(&quot;Main&quot;)" />```

Removing the sharp removed the error, but I don't know if there is any colateral effect...
But closing and opening the project again while set to debug (instead of release) adds adds the sharp again.
Besides, I found pretty similar references in .hxproj files for the following lime and openfl samples:
```
lime-samples\2,6,0\demos\HelloWorld\HelloWorld.hxproj
lime-samples\2,6,0\features\audio\SimpleAudio\SimpleAudio.hxproj
lime-samples\2,6,0\features\text\TextRendering\TextRendering.hxproj
openfl-samples\3,3,1\demos\BunnyMark\BunnyMark.hxproj
openfl-samples\3,3,1\features\events\HandlingMouseEvents\HandlingMouseEvents.hxproj
```
Didn't try those ones to see if the problem is present there too...

So, this is obviously a FD problem.
@elsassph, could you take a look, please?
