### ISSUE TITLE
Haxe 3 on Windows needs admin rights to install

### ISSUE THREAD

**Issue by gottfired** [HaxeFoundation/haxe#1954]
Not sure if really a bug. But I couldn't install Haxe on a Windows 8 machine without admin rights. After installing as admin and copying over the HAXEPATH, NEKO_INSTPATH variables over and adjusting the PATH it worked fine without admin rights.

**Comment by kkmfd-Offical** [comment]
haxelib gives me an error it says that neko.dll is missing
