### ISSUE TITLE
Reflect.isFunction produces different results for neko vs. c++ targets

### ISSUE THREAD

**Issue by bji** [HaxeFoundation/haxe#1960]
Here is a small Haxe program:

<pre>
class NekoBug
{
    public static function main()
    {
        for (f in Type.getClassFields(TestClass).concat
                 (Type.getInstanceFields(TestClass))) {
            if (!Reflect.isFunction(Reflect.field(TestClass, f))) {
                Sys.println("Field " + f + " is not a function");
                continue;
            }
            Sys.println("Field " + f + " IS a function");
        }
    }
}
</pre>

When compiled for the C++ target, it outputs:

Field aStaticFunction IS a function
Field aFunction IS a function

When compiled for the neko target, it outputs:

Field aStaticFunction IS a function
Field aFunction is not a function

Why is the neko target reporting that a function is a function only if it is static?

**Comment by hughsando** [comment]
I think this should be done properly now.
