### ISSUE TITLE
Map<Class<Dynamic>,Dynamic> not supported

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxe#1971]
Hi,

I used to use a special class (com.fermmtools.utils) to deal with maps. it supported any type of object including classes (Haxe 2)

Now with haxe 3 I started to use Map but realized that it did not support Class<Dynamic> to store the classes as key.

Any plan to support it ? or any workarround?

an example that does  not compile:

```haxe
package;

class MapTest{

  static public function main():Void{
    new MapTest();
  }

  private var map : Map<Class<Dynamic>, Bool>;
  public function new(){
    map = new Map();
  }

}
```

**Comment by thomasuster** [comment]
The keys member is a little tricky. Here's an implementation I found that seems pretty fast. https://github.com/nadako/Ash-HaXe/blob/master/src/ash/ClassMap.hx

**Comment by sbijoshj** [comment]
If you have an instance of the thing you would like to use as the key, you can do this:
```haxe
public static function getMapOfType(k:Dynamic):Dynamic {
	if( Std.is(k,Int) )
		return new Map<Int,Dynamic>();
	else if( Std.is(k,String) )
		return new Map<String,Dynamic>();
	else if( Reflect.isEnumValue(k) )
		return new Map<EnumValue,Dynamic>();
	else if( Reflect.isObject(k) )
		return new Map<{},Dynamic>();
	else
		throw "invalid map key type found!";
}
```
(Hacky and only semi-related but posting for future web searchers that end up here looking for something like this like I did.)

**Comment by back2dos** [comment]
This would seem to work: http://try.haxe.org/#501dc

@Simn I wonder, couldn't we just add `to {}` to `Class`?
