### ISSUE TITLE
[Flash] Release builds break Alchemy SWCs

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#1976]
Hi,

I'd like to use an Alchemy-based SWC with Haxe:

http://code.google.com/p/as3-jpeg-decoder/downloads/list

When I compile for debug, I can use my ported version fine, but (unfortunately) I get a VerifyError with one of the included classes when I perform a release build instead.

I suppose this is a Haxe compiler error?

Thank you

**Comment by Simn** [comment]
Closing this as unresolved. We won't be spending much resources on Flash-specific stuff unless one of our partners explicitly requests it.
