### ISSUE TITLE
Allow trailing comma in argument list

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#1989]
While it's not particularly important, I would think it would be rather comfortable to allow trailing commas in argument lists. It's allowed for array and object literals, so I think it would be rather consistent and I don't see it causing any problems.

**Comment by Aurel300** [comment]
I would like to see this, both in the argument lists and function calls.

```haxe
function a(
  arg1:X,
  arg2:Y,
):Z { ... }
```

```haxe
a(
  arg1,
  arg2,
);
```

It is just very convenient to be able to reorder or easily add/delete lines in examples like the ones above. It's also nice when you want to enable/disable arguments to functions with conditional compilation. And finally it would be consistent with our array and map literals now.

(Just realised I'm basically restating @back2dos 's points x)

**Comment by Simn** [comment]
I kinda hate how that trailing comma looks, but I acknowledge that it's very useful for copy & pasting.

**Comment by dpomier** [comment]
Could the code editor automatically add/remove the trailing comma when commenting out/transposing? It would reconcile nice-looking comma with very easy manipulations.

**Comment by back2dos** [comment]
Closing in favor of https://github.com/HaxeFoundation/haxe/pull/10159
