### ISSUE TITLE
[PHP] reflect api breaks sys.db.Manager.doUpdate when php version > 5.2

### ISSUE THREAD

**Issue by postite** [HaxeFoundation/haxe#1990]
in sys.db.Manager.doUpdate function 
this line 
https://github.com/HaxeFoundation/haxe/blob/development/std/sys/db/Manager.hx#L223
generates 
 $cache->{$name} = $v; in PHP

which seems to no longer works in new php versions  (ex 5.4 )
but it's fine with php 5.2

**Comment by RealyUniqueName** [comment]
Since it's a three years old issue without any activity for years, unit tests are ok and SPOD moved to separate library, i guess this issue is not relevant anymore. Feel free to reopen.
