### ISSUE TITLE
haxe/js: function.bind implementation doesn't work for IE8

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#1999]
the bind implementation https://github.com/HaxeFoundation/haxe/blob/development/genjs.ml#L1134
doesn't work like that for IE8. Some methods, natively implemented ones, I assume, don't support assigning attributes to them, so the caching of the closure as implemented doesn't work. 
IE8 breaks here: m.**id** = $fid++;

**Comment by aduros** [comment]
Probably too late for 3.2, pushing this to 3.3...

**Comment by ncannasse** [comment]
@aduros really ? it's been opened since July 2013

**Comment by frabbit** [comment]
i have a problem with bind on extern objects in case they override the set operation for every property (angular scopes in this case), it works fine when i replace:

```
if( o.hx__closures__ == null)
```
with
```
if(!o.hasOwnProperty("hx__closures"))
```

Can we change this or does it have any compatibility problems?

**Comment by R32** [comment]
Is there any way such as "-D js-nobind" which is used to remove all `$bind(obj, func)` for extern class,

**Comment by Simn** [comment]
Several years later, I think it's fine to no longer worry about IE8.
