### ISSUE TITLE
Generated __files__.cpp does not escape slashes in classpaths

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#2002]
When running on Windows, classpaths and haxelib paths tend to resolve with backslashes.

The C++ generator outputs the paths directly into __files__.cpp. This creates warnings when targeting Android (for the unescaped slashes) and creates errors when the final character in the classpath is a slash, since it escapes the quotation mark at the end of the line.

We need to either escape these slashes, or convert to forward slashes. Should that be done in the C++ generator, or should Haxe internally maintain the context classpaths using forward slashes?

**Comment by hughsando** [comment]
Backslash paths seem to be quoted now.
