### ISSUE TITLE
Sqlite

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/haxe#2008]
When I try Sqlite.open

It shows me that msvcr71.dll is missing

Called from C:\HaxeToolkit\haxe/std/neko/_std/sys/db/Sqlite.hx line 87
Uncaught exception - load.c(237) : Failed to load library : C:\HaxeToolkit\neko/
sqlite.ndll
Press any key to continue . . .

**Comment by andyli** [comment]
For people attempting to get sqlite works on Windows, the above info is correct. "msvcr71.dll" can be obtained by installing the .NET 1.1 runtime as suggested in http://stackoverflow.com/questions/1596167/where-to-download-microsoft-visual-c-2003-redistributable
The path to the dll would be "C:\Windows\Microsoft.NET\Framework\v1.1.4322\msvcr71.dll".
