### ISSUE TITLE
[java] Metadata on interfaces

### ISSUE THREAD

**Issue by Randonee** [HaxeFoundation/haxe#2042]
Using haxe 3 release mmvc will not compile to java.

Sample application:

-----------  Test.hx ------------

	import mmvc.impl.Context;
	class Test
	{
		static function main(){
		}
	}
	
	class ApplicationContext extends Context
	{
		public function new(){
			super(null);
		}
	}

-------------------------------------

-----------  build.hxml --------

	-cp src
	-lib mmvc
	-java out/java
	-main Test

-------------------------------------

Compiling the above app will result in 100 compilation errors for java but compiles fine for other targets.

**Comment by Simn** [comment]
Broken on PHP, but I'll check that after 3.2.
