### ISSUE TITLE
Java/C# : native annotations

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#2065]
Support native metadata declaration on Java and C#. This will need a way to typecheck them.
I can make it work using macros and special interfaces, but wouldn't it be a good time to add checked metadatas for Haxe as well?

(cc @ncannasse and @Simn )

**Comment by commel** [comment]
Especially needful for Hibernate or Servlet/Spring MVC-targets. Please implement this! :-)

**Comment by commel** [comment]
:+1:
