### ISSUE TITLE
Inconsistent behavior for haxe.io.Bytes::toString()

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#2076]
On haxe.io.Bytes, when length == 0, the behavior of toString() is not consistent across targets: on neko, this returns an empty string; on c++, the result is null. I'm not sure about other targets, though.

```haxe
public function testEmptyBytes() {
	var b = haxe.io.Bytes.alloc( 0 );
	assertEquals( "", b.toString() );
	var bb = new haxe.io.BytesBuffer();
	assertEquals( "", bb.getBytes().toString() );
}
```

**Comment by hughsando** [comment]
Fixed in hxcpp.
