### ISSUE TITLE
-D js-flatten flattens extern referenced defined in @:native("foo.Bar") metadata

### ISSUE THREAD

**Issue by jonathanhardie** [HaxeFoundation/haxe#2132]
Playing around with the new js package flattening feature, it incorrectly flattens external references defined in @:native("foo.Bar") metadata to foo_Bar - which doesn't exist in the third party lib.

**Comment by urbananimal** [comment]
I am also still seeing this issue...

**Comment by Simn** [comment]
@nadako: Could you check?

**Comment by nadako** [comment]
Installed 3.1.3 just for that:
```haxe
@:native("FOO.Bar")
extern class Bar {
    function new();
}

class Main {
    static function main() {
        var a = new Bar();
    }
}
```

`haxe -main Main -js main.js -D js-flatten` generates
```js
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	var a = new FOO.Bar();
};
Main.main();
})();
```

**Comment by urbananimal** [comment]
I am seeing the issue when using `@native` on an extern interface, could this make a difference?

**Comment by nadako** [comment]
I can confirm this bug on git haxe. Will fix that.
