### ISSUE TITLE
Explicit macros static caching

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#2143]
With compiler cache, the macro runtime context is cached, including its static variables which are kept between subsequent compilations (unless one of the macro module is modified).

This is a bit tricky for the user to deal with, we might instead have either an API or an explicit way to annotate statics that needs to be kept.

It is then necessary to have a way to reset the macro context statics before reusing it.

See related issue #2012

**Comment by back2dos** [comment]
Is it really a good time to tackle this issue? It will break all code that relies on it and create weird errors instead. Since it didn't really seem to bother anyone for two years, I propose it be delayed for Haxe 4.

**Comment by ncannasse** [comment]
I agree that while people have expressed concerns at first about the cached nature of statics in macros, I have since not actually heard anyone complaining about it. It's possible that people don't use the compiler cache with macros, but in both cases there does not seem to be a problem to fix.
