### ISSUE TITLE
Inlining not working as expected (Js target).

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#2216]
The Js target has made a lot of progress, however, Inlining seems to still not occur as much as expected.

Particularly some restriction prevent writing highly performant libraries using combinators (functional style).
I have seen this issue recently with Monax and Parsex.

Here's a shrinked example code not inlining as expected:

```C#
	static inline function foo(a : Option<Int>) {
		return switch (a) {
			case Some(x): null;
			case None: null;
		}
	}

    static function main() {
        var x = foo(Some(5)); // Not inlined
        ...
    }
```
generating:

```javascript
Main.foo = function(a) {
	switch(a[1]) {
	case 0:
		var x = a[2];
		return null;
	case 1:
		return null;
	}
}
Main.main = function() {
	var x = Main.foo(haxe.ds.Option.Some(5));
        ...
}
```

Whereas this one works :

```C#
	static inline function foo(a : Int) {
		return switch (a) {
			case 0: 1;
			default: 0;
		}
	}

    static function main() {
        var x = foo(5); // inlined
        ...
    }
```

Is it possible to allow inlining in those slightly more complex cases?
(This was installed using 'brew install haxe --HEAD' today (3.1.0))

**Comment by ncannasse** [comment]
@Simn if not done already, could you lift inlining restrictions in JS with -D analyzer ? That will give us better feedback when we want to check how it behave

**Comment by Simn** [comment]
That's done already, my example optimizes to `1` with the analyzer. It even works with enum parameter values:

```
enum Option<T> {
    Some(s:T);
    None;
}

class Main {
    static function main() {
        var x = switchSomething(Some(12));
    }

    static inline function switchSomething<T>(o:Option<T>) {
        return switch(o) {
            case None: null;
            case Some(c): c;
        }
    }
}
```

Generates JS with -D analyzer and -dce full:

```
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	12;
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```
