### ISSUE TITLE
[MotionTwin] Some specific numeric symbols stops the gcc compiler

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2221]
@gamehaxe
Using github  haxe hxcpp and hxcpp svn, we have an issues ( which is old I think ) with the compilation of : 
'''
public static inline var INT_MIN	: Int = -2147483648 ;
'''
generates cpp : INT_MIN = (int) -2147483648 ; in the cpp...
gcc then prints : error: expected unqualified-id before numeric constant
It causes an error in the cpp compile flow and not in haxe.

Expected behaviour : 

It is not very important but if the literal is incompatible. the error should arise in haxe and not in cpp...and preferably, this is a classic literal on cpp which should actually work... :)

My first guess is hxcpp should write a cpp literal like -2147483648L or something like that. 
Would be lovely to fix :)

Thanks !

**Comment by hughsando** [comment]
This should be handled by the Undefine.h code now.

**Comment by delahee** [comment]
Thanks !
Le 18 févr. 2015 15:42, "Hugh Sanderson" <notifications@github.com> a écrit
:
