### ISSUE TITLE
Cannot skip non-nullable argument xxx

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#2232]
```
function foo(x=0,y=0,w=0,h=0) {
}
var v : Float = 0;
foo(v,v,v,v);
```

If we pass a Float while an Int is expected, we get four `Cannot skip....`  errors in flash before having the actual Invalid arguments errors.

**Comment by fzzr-** [comment]
Need reopen. Reproduced in version 3.2.1. @Simn

**Comment by Simn** [comment]
Looks like my fix disappeared during some refactoring.

We have to keep overloads in mind for this...
