### ISSUE TITLE
Import completion for statics

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2263]
Since it's now possible to import static methods and varaibles in the module namespace (which I find a very useful feature!), it would be great to support their completion with --display switch (currently it returns "no classes found").

**Comment by ncannasse** [comment]
I have added module types listing in c51a36352b37192fd32ef1c3593af1ea8f8230c2. Adding statics would require to list the static fields together with the module types in main.ml (assigning to @Simn)

**Comment by ncannasse** [comment]
@Simn we also need to add an additional contextual flag in case we are completing a type ( as var x : my.path.MyModule.|) in which case we don't want to list the statics here.

**Comment by Simn** [comment]
I would kinda like to know what the second argument is before I add a third one. :P

But yes I'll look into it.

**Comment by ncannasse** [comment]
TypePath(["a","b"],None) --> package only (list the files in package)
TypePath(["a","b"],Some ("Type",flag)) --> module completion (list the types in module)

flag = true : we coulnd't resolve the Type using the local imports, so we will put the current package in the TypePath package and allow search in upper packages (parsed "Type" could be a.b.Type, a.Type or Type)

**Comment by Simn** [comment]
I have implemented it but didn't add any tests yet because that always takes me forever. Assigning to @nadako for that.

**Comment by nadako** [comment]
i've added some tests, but it seems that type completion also lists statics (see `type-completion.hxml.disabled`).

**Comment by Simn** [comment]
Haha, I went through all that trouble to add a flag and then forgot to actually check it.

**Comment by nadako** [comment]
how about importing a static from a module subtype? :)

**Comment by nadako** [comment]
i.e.
A.hx
```haxe
class B {
    public static var b:Float;
}
```

Main.hx
```haxe
import A.B.|
```

**Comment by Simn** [comment]
Try now!

**Comment by nadako** [comment]
note that original tests are broken (the main module type is not listed now)

**Comment by Simn** [comment]
I removed that on purpose because I don't see the point of completing C on pack.C.|

**Comment by nadako** [comment]
I'm not sure. What if one wants to import just that type and not the whole module.

**Comment by Simn** [comment]
Does that actually work?

**Comment by nadako** [comment]
I think so:
```haxe
import pack.A.B;

class Main {
    static function main() {
        A; // Unknown identifier : A
    }
}
```

**Comment by Simn** [comment]
I see, I didn't know that was a thing.

**Comment by nadako** [comment]
I think everything is okay now.
