### ISSUE TITLE
"Cannot inline a not final return"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#2305]
Another compiler-cache related issue:

If we have the code:

```
//Bug.hx
class Bug {

	public static inline function foo( x : haxe.ds.Option<Float> ) {
		return switch( x ) {
		case None: 0.;
		case Some(v): v;
		};
	}

}
// Test.hx
class Test {

    static function main() {
		Bug.foo(Some(1.5));
	}

}
```

It seems that we modify the "foo" expression after it's been compiled, and the resulting expression is no longer inlinable once in the compiler cache.

Easily reproducible by modifiying Test.hx only and recompiling.

@Simn how is switch translated ? Can't we do it after we have "saved" the expressions

**Comment by Simn** [comment]
That becomes something like

```haxe
switch (x) {
    case 1: return 0.
    case 0: {
        var v = x[0];
        return v;
    }
};
```

Changing filter order always makes me nervous, but it might be possible here.

**Comment by profelis** [comment]
I get same error with last stable haxe release and compile-cache

```
$ haxe -version
3.2.0
```

```
 - Running command: haxe bin/android/haxe/debug.hxml -D android -D android-9 -D HXCPP_ARMV7
/usr/lib/haxe/std/UInt.hx:281: characters 3-28 : Cannot inline a not final return
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:24: lines 24-1029 : Defined in this class
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:820: characters 98-120 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:825: characters 97-119 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:830: characters 97-119 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:835: characters 98-120 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:883: characters 98-120 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:888: characters 98-120 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:893: characters 98-120 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:898: characters 99-121 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:941: characters 104-126 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:946: characters 104-126 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:951: characters 104-126 : Recursive implicit cast
/Users/deep/dev/haxe/haxe/lib/openfl/3,1,2/openfl/display3D/Context3D.hx:956: characters 105-127 : Recursive implicit cast
```

**Comment by MintPaw** [comment]
I get the same error in 3.2.1, I also get a lot of "Cannot inline a not final return" errors, which I can prevent with --no-inline, as well as a bunch of "Missing return X" which I can prevent with --no-opt

But I cannot find a way to prevent these "Recursive implicit cast" errors, it looks like this has been going on for about 7 months. As the build server been abandoned?

**Comment by Simn** [comment]
If you want us to address something we'll need a proper issue report with a minimal example. You should also make sure the OpenFL version you're using is compatible with the Haxe version.

**Comment by MintPaw** [comment]
@Simn There's an example [here](https://github.com/MintPaw/compilationServerTest) with an empty openfl project.
Running [compile.sh](https://github.com/MintPaw/compilationServerTest/blob/master/compile.sh) starts the haxe server and does two builds, storing the results in the text files. You can see in the first file it work fine, but in the second it fails with many errors.

**Comment by Simn** [comment]
Can you get rid of the OpenFL dependency? It would also help if you could test using a development version of Haxe (from http://builds.haxe.org) to see if the issue has already been addressed.

**Comment by MintPaw** [comment]
Sadly I don't have a deep understanding of Haxe or OOP is general, I'm not sure how I'd write something with the abstract keyword. It may just be my configuration, but it looks like a fundamental feature that been broken for more than half a year and should probably be reopened.

**Comment by Simn** [comment]
Did you test with a development version of Haxe?

**Comment by MintPaw** [comment]
Testing with linux64 haxe_2016-02-22_development_bfac501

[This fails](http://pastebin.com/raw/Bqyzm990) for a different reason, possibly related to openfl.
But compiling again does skip the cached modules without failing, so it looks like this would fix the problem.

**Comment by Simn** [comment]
That happens because you don't use the latest hxcpp version. But yes, that suggests that it's not actually a problem (anymore). It doesn't even seem to be related to this issue in the first place because the related UInt code does not use a `switch`.

**Comment by MintPaw** [comment]
Ah, ok, when will the fix be available in the release version?

**Comment by Simn** [comment]
We usually have a release before the Haxe conference, probably April or May.

**Comment by ProPuke** [comment]
This bug still persists with the compilation server. Different test case:

Bug.hx

```haxe
class Bug {
    static function a() return true;
    static function b() return false;

    public static inline function trigger() return a()||b();
}
```

Main.hx

```haxe
class Main {
    static function main(){
        Bug.trigger();
    }
}
```

Make any modification to Main.hx and the cached `Bug.trigger` will error with:
`Bug.hx:5: characters 41-56 : Cannot inline a not final return`

Modifying Bug.hx will clear the cache and make the bug go away until Main.hx is modified again.

This still occurs in the latest development build.

**Comment by Simn** [comment]
This is probably quite related to what I explain in https://github.com/HaxeFoundation/haxe/issues/5320#issuecomment-226753961 and likely has the same fix.

**Comment by mastef** [comment]
Ran into this even though have set `--no-opt` and `--no-inline` : 

```
haxe: [3.3.0]
openfl: [3.6.1]
```

```
lime build cpp --connect 6000 --times -Dmacro-times -Dlegacy --no-opt --no-inline -dce=full -dce-debug -erase-generics -v -debug
```

```
 - Running command: haxe export/mac64/cpp/haxe/debug.hxml -D HXCPP_CLANG -D HXCPP_M64
/l/haxe/std/UInt.hx:137: characters 2-17 : Cannot inline a not final return
/l/haxe/lib/flixel/4,1,0/flixel/util/FlxGradient.hx:22: lines 22-214 : Defined in this class
/l/haxe/std/UInt.hx:137: characters 2-17 : Cannot inline a not final return
/l/haxe/lib/flixel/4,1,0/flixel/util/FlxGradient.hx:22: lines 22-214 : Defined in this class
/l/haxe/std/UInt.hx:285: characters 3-28 : Cannot inline a not final return
/l/haxe/std/UInt.hx:285: characters 3-28 : For function argument 'width'
/l/haxe/lib/flixel/4,1,0/flixel/util/FlxGradient.hx:22: lines 22-214 : Defined in this class
/l/haxe/lib/flixel/4,1,0/flixel/util/FlxGradient.hx:135: characters 3-32 : Recursive implicit cast
/l/haxe/lib/svg/git/format/gfx/GfxBytes.hx:234: characters 68-82 : Recursive implicit cast
/l/haxe/lib/svg/git/format/gfx/GfxBytes.hx:234: characters 68-82 : For function argument 'x'
```

When switching to neko I'm then running into 

```
/l/haxe/lib/lime/2,9,1/lime/graphics/utils/ImageDataUtil.hx:59: characters 5-10 : Local variable pixel used without being initialized
```

Tried a few things, but at the moment the cache daemon is unusable due to that :-( Any pointers on how to fix?

**Comment by Simn** [comment]
This should be resolved now.

**Comment by darmie** [comment]
So I have this problem in Haxe 4.1.1

I am trying to generate a code with macro, 

```hx
	macro static public function RETURN_VAL(value:Expr):Expr {
		// var args = macro $i{Context.getLocalVars()[1]};
		var pos = Context.currentPos();
		
		var body = macro do {
			$i{"args"}[0] = cast $value;
			return true;
		} while (true);

		return body;
	}
```

I am using it here:
```hx
@:DEF_PRIMITIVE("fn_toString")
static function fn_toString(vm:VM, args:Array<Value>):Bool {
	RETURN_VAL(CONST_STRING(vm, "<fn>"));
	return false;
}
```

Error " `Macros.hx:69: characters 4-15 : Cannot inline a not final return`

**Comment by RealyUniqueName** [comment]
Can you provide a complete sample?

**Comment by darmie** [comment]
@RealyUniqueName I have solved the problem. It was because I was trying to inline a macro function. 

```hx
static inline function BOOL_VAL(val:Value):Bool {
   return RETURN_VAL(val);
}
```

I fixed it by removing inline.
