### ISSUE TITLE
C# 2.0 (Unity3d) Reflect not support Enum

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#2308]
<pre>Reflect.callMethod(null, press, [Key.B]);
...
function press(k:Key) trace(k);
</pre>
<code>InvalidCastException: Value is not a convertible object: System.Int32 to pony.ui.Key</code>
C# 4.0 work normal.
For fix i'm write: <code>function press(k:Int) trace(k);</code> but this very bad.
Maybe can fix function callMethod for C# ?

**Comment by waneck** [comment]
Closed by 3022da4a26f9b695c968d1aaf3ed631d097b706e
