### ISSUE TITLE
Multiple inheritance with structural types

### ISSUE THREAD

**Issue by lptr** [HaxeFoundation/haxe#2364]
http://haxe.org/ref/type_advanced#extensions

This here says that I can extend my structural types like this:

``` haxe
typedef Parent = {
    var a:Int;
}

typedef Child = { > Parent,
    var y:Int;
}
```

I'd like to be able to extend from more than one type. I imagine this would work the same way as multiple inheritance works with interfaces.

Syntax could be something like this:

``` haxe
typedef ParentA = {
    var a:Int;
}

typedef ParentB = {
    var b:Int;
}

typedef Child = { > ParentA, > ParentB,
    var y:Int;
}
```

**Comment by dyarosla** [comment]
I'd like to see this re-opened @simn @lptr @ncannasse 

I don't see a good reason for not allowing typedefs to have multiple extends (like @ncannasse mentioned at the top.

One use case (that I'm personally looking at) is as follows:

```
typedef BoxParams = {
    ?x,
    ?y,
    ?w,
    ?h
}

typedef TileParams = {
    ?tileName,
    ?transform
}

typedef BoxTileParams = {
    >BoxParams,
    >TileParams
}
```
Then used as follows:

```
function setupBox(params:BoxParams):Void {
    //setup a box object
}

function setupTile(params:TileParams):Void {
    //setup a tile object
}

function setupTileBox(params:TileBoxParams):Void {
    //setup a tile/box hybrid object using these params
    //... can invoke the above functions to help
    setupBox(params);
    setupTile(params);
}
```

You can imagine that this would be a pain without multiple-extension, but useful to use these multiple-extend `typedef`s to easier form overarching declarator/initializer functions.
