### ISSUE TITLE
Short syntax for lambda expressions

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#2369]
Lambda example:

<pre>var a:Array<String> = ['1','2','3'];
var b:List<Int> = Lambda.map(a, e -> Std.parseInt(e)-1 );
//b = [0,1,2];
//translate to var b:List<Int> = Lambda.map(a, function(e) return Std.parseInt(e)-1 );</pre>

Flash event system example:
<pre>
obj.addEventListener(event:Event->openWindow()); // => obj.addEventListener(function(event:Event) openWindow());
//With return type
obj.addEventListener((event:Event):Void->openWindow());
//With body
obj.addEventListener(event:Event->{
    openWindow();
});
//With _
obj.addEventListener(_->openWindow());
</pre>

More details: http://cr.openjdk.java.net/~briangoetz/lambda/lambda-state-final.html

**Comment by sigmasoldi3r** [comment]
why the team does not want to integrate short lambdas? (The reason I mean)

**Comment by back2dos** [comment]
The topic has been tabled numerous times since this issue was closed and [has finally been added to Haxe 4](https://github.com/HaxeFoundation/haxe/pull/6209).
