### ISSUE TITLE
PHP capturing wrong variable

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#2378]
The following code:

```
class Main
{
  private function new()
  {
  }

  public static function main()
  {
    var arg = { name: "test", command:"something", aliases:["a"], description:null, kind: Flag };
    var versions = arg.aliases != null ? arg.aliases.concat([arg.command]) : [arg.command];
    versions = versions.filter(function(s) return s != null && s != "");

    var prefix = "-";
    if (arg.kind == SubDispatch || arg.kind == Message)
      prefix = "";
    trace(versions.map(function(v) return (v.length == 1) ? prefix + v : prefix + prefix + v));
  }
}

enum Kind
{
  //stub
  Message;
  //variable
  Flag;
  VarHash(key:{ name:String, t:CType }, value:{ name:String, t:CType }, ?valueIsArray:Bool);
  Var(t:CType);
  //function
  Function(args:Array<{name:String, opt:Bool, t:CType}>, ?varArgs:Null<CType>);
  SubDispatch;
}

typedef CType = String;
```

Should trace:
`[-a,--something]`

Instead, it traces:
`[{ name => test, command => something, aliases => [a], description => , kind => Flag }{ name => test, command => something, aliases => [a], description => , kind => Flag }[a,something],{ name => test, command => something, aliases => [a], description => , kind => Flag }{ name => test, command => something, aliases => [a], description => , kind => Flag }[a,something]]`

Strangely, if the enum is taken off, the code works correctly again

**Comment by Simn** [comment]
I can no longer reproduce this and it works on travis too. I also checked without -D analyzer to make sure the problem is not sanitized away.
