### ISSUE TITLE
support for ruby target

### ISSUE THREAD

**Issue by paulfitz** [HaxeFoundation/haxe#2394]
I've been working on adding a ruby target to haxe, at https://github.com/paulfitz/haxe. It is by no means complete, but is already working for a smallish library I maintain ([coopyhx](https://github.com/paulfitz/coopyhx)).  Since I knew no ocaml before starting, the generator code is in large part a patchwork from existing languages, and not something I'd be proud to submit as a PR just yet. Before spending time polishing it, I just wanted to do a sanity-check, and ask whether haxe developers would be receptive to incorporating a ruby target? Are there any particular standards or guidlines I should be paying attention to, other than just following existing style?

**Comment by scottmas** [comment]
Any update on this? Ruby would be handy.

**Comment by fullofcaffeine** [comment]
A ruby target would open some very interesting possibilities, indeed. While I do like Ruby's syntax, for large-scale projects Haxe wins hands-down. Having a Ruby target would allow potentially for leveraging the awesome Ruby eco-system, including Rails, but using Haxe and its powerful type-system.

Haxe already has a Python target, a Ruby target makes a lot of sense.

@paulfitz Do you plan on ever turning it into an official Haxe target?

**Comment by fullofcaffeine** [comment]
The fork can't be compiled anymore, @Simn do you have any hints on how I could solve this? https://github.com/paulfitz/haxe/issues/7
