### ISSUE TITLE
Feature request: index => value, key => value iteration

### ISSUE THREAD

**Issue by dpeek** [HaxeFoundation/haxe#2421]
I often find myself doing this:

```
for (i in 0...array.length)
{
    var v = values[i];
    // something with index and value
}

// or

for (k in 0...map.keys())
{
    var v = map.get(k);
    // something with key and value
}

```

It would be nice to do:

```
for (i => v in array)
{
    // something with index and value
}

// and

for (k => v in map)
{
    // something with key and value
}
```

**Comment by ncannasse** [comment]
@frabbit Sadly this would allocate an object per element iterated so it's very poor performance-wise

**Comment by nadako** [comment]
> this would allocate an object per element iterated

Not if it's fully inlined, but yeah, we can't guarantee it in general case. Stack-allocated structs would be a good use case for this. I wonder what's the outcome of that proposal @waneck wrote once...

**Comment by ncannasse** [comment]
@nadako and would that work in JS ? :)

**Comment by nadako** [comment]
@ncannasse only if we implement it through inlining and not in all cases, obviously :)

**Comment by kevinresol** [comment]
Check this out: https://gist.github.com/RealyUniqueName/2fbeb1ec17e637d6eaf50b0facde206f

**Comment by back2dos** [comment]
Can't we just just add `array.keys()` through global using and then `for (key => val in target) body;` becomes `for (key in target.keys()) { var val = target[key]; body; }`? Or just treat `Array` as a special case and otherwise allow anything that has a `keys` and a `get` method?

**Comment by nadako** [comment]
@back2dos while it's a nice idea, I think this can introduce some unnecessary performance constraints due to extra lookup by key. I imagine some e.g. Map implementations can return more efficient iterators that returns pairs directly.

**Comment by ncannasse** [comment]
Will have to go through Haxe Evolution I think.

**Comment by nadako** [comment]
Added a proposal here: https://github.com/HaxeFoundation/haxe-evolution/pull/37
