### ISSUE TITLE
[cs/java] ridiculous temp var numbers (minor)

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2447]
In Java/C# targets, there is some global counter for temp variables that seems to never reset, outputting names like: `__temp_catchall361`, `__temp_me124` and `__temp_odecl250` which look kinda stupid.

I think the same approach should be used as with Typecore.gen_local, that means saving the counter at the beginning of block and restoring at the end.

Actually can't Typecore.gen_local and friends be used instead of Gencommon.mk_temp? (maybe with a little bit of refactoring).

cc @waneck

**Comment by nadako** [comment]
This issue proves very annoying when one wants to diff how generated code has changed between haxe commits.

**Comment by Simn** [comment]
Don't use `gen_local`, it's really slow in some cases.

I agree we should improve here, but this doesn't strike me as a 3.2 priority.

**Comment by nadako** [comment]
The situation has improved since then and it's not worth having an open issue just for this. I might fix a couple more cases in my next gencommon cleanup adventure.
