### ISSUE TITLE
[CPP] Structure field access speed

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#2462]
I've noticed that accessing a structure field cause the following code to be generated:

```
x->__Field(HX_CSTRING("x"),true)
```

This is not optimal for two reasons:
 - we will allocate a String, which is very bad for performances
 - the __Field access will use string comparisons, which is again not optimal.

What about using instead what Neko does which is to hash fields names into an unique identifier ? That would only require extra hashing for Reflect.field but speedup a lot structure access.

**Comment by hughsando** [comment]
String constants have hashes built-in now, and the haxe/map has been rewritten, so I'm closing this one now.
