### ISSUE TITLE
Type constraints not checked during inheritance

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#2472]
This compiles, although it shouldn't: http://try.haxe.org/#15F62
In Haxe 3.0.1 it's rejected with `B.O should be { id : String }`.

**Comment by Simn** [comment]
Looks like this was accidentally disabled. There is a unit test which breaks when it is re-enabled:

```haxe
@:generic class RBNode<T:RBNode<T>> {
    public var rbLeft : T;
    public var rbRight : T;
}

@:generic class RBTree<T:RBNode<T>> {
    public var root : T;
    public function new() { }
}
```

```
Constraint check failure for unit.RBNode.T
unit.RBTree.T should be unit.RBNode<unit.RBTree.T>
```

We have to check that before we can fix this issue.
