### ISSUE TITLE
Pattern matching consistency

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2503]
I think this example should print tick / tock alternatively but in fact the hfr variable always triggers its case like a 'default' one.

```haxe
import flash.Lib;
import flash.display.Sprite;
import flash.events.Event;

class Main extends Sprite {

    public function new () {
        super ();
        Lib.current.stage.addEventListener( Event.ENTER_FRAME, update );
    }

    public static inline var STR = 8;
    public var fr = 0;

    public function update( _ ) {
        var hr = STR >> 1;
        switch( fr % 8 ) {
            case 0:trace('$fr tick ');
            case hr:trace('$fr tock ');
        }
        fr++;
    }
}
```

Either an error should pop OR shoud be fixed but keeping as is a very bad option.
Please don't overlook.

Thanks !

**Comment by delahee** [comment]
imvho, this shoulw be writable (and better without static support ). In cpp this is a commoner that allow lots and lots of optimising, I don't get as to why we should cripple our code with if.

```haxe
public static var STR = 8;
public static var H_STR = STR>>1;
public var fr = 0;

public function update( _ ) {
    switch( fr % 8 ) {
        case 0:trace('$fr tick ');
        case H_STR:trace('$fr tock ');
    }
    fr++;
}

```

sorry for the troll, i am shaming myself but i think there is a real issue here.

**Comment by delahee** [comment]
would have loved to have 

```haxe
switch(fr){
       case 0:...
       case ( expr ):
}
```

of something consise of the sort...

**Comment by delahee** [comment]
Parenthesis was just a bad example you get the idea ^_^, I can propose a
ton of alternatives :

```haxe
switch(e){


ecase expr: // my favorite, easy to parse and not a popular identifier
case ${}:
case | |:
case /expr/

if(expr): // eat the case in the if, explicitly state "i understand what i
do "!, easy to parse and alreayd reserved kw
with expr :
like expr :
is expr:

=> expr :
== :

[...]

| expr => //the caml way
| expr : //not so bad
| {} :

case expr ->
case expr :-
case expr >:
> expr :
# expr :
}
```

I can continue for a good long time if none suits you still:)

Thanks :)

2014/1/3 Nicolas Cannasse notifications@github.com

> Adding semantics of parenthesis seems even worse. The only thing to know
> is that variable names in cases are captured variables, not values. I agree
> this can be misleading for people which want to check against the variable
> value, but I don't have any idea how to improve this while keeping variable
> capture which is very important.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HaxeFoundation/haxe/issues/2503#issuecomment-31527004
> .

## 

David Elahee

**Comment by delahee** [comment]
@simn 

1-

```haxe
public static inline var a = 0;
public static var b = 2;
switch(c%8){
case a: foo();
case b: bar();
default: toto();
}
```

This is one of the nastiest piece of bad semantic engineering I met. How one rookie or event one grand master is suppose to cope with haxe when he has a shrodin-bug hidden within this, because forgetting what is constants and not is so easy...

I cannot be explained how letting this live is _acceptable_. Sorry.

2- Keeping pattern constant is cool case x if (expr) is just too verbose, let's take a real world example

```haxe
switch(playerState){
case SStunned: {
 foo(); foo(); foo(); foo();
}
//where next() compute the next enum in the domain
ecase SStunned.next(): {  foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo();
}
```

vs 

```haxe
switch(playerState){
case SStunned: {
 foo(); foo(); foo(); foo();
}
//where next() compute the next enum in the domain
case ps if(ps == SStunned.next()): {  foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo(); foo();
}
```

This is the 99% case of occurence, here we have a random name which will serve has capture to test equality that could have been packed in the case (or ecase) at no cost of incomprehension, a simple google haxe ecase would have done the trick. This is just the same argument as to why a?b:c was created..

I understand if for vaguely conservationnal reason the "ecase" wouldn't make it. 

_But we must address the first problem which is just plain wrong imvho._

**Comment by Simn** [comment]
Inline fields are allowed in other places where constants are expected as well, e.g.

```haxe
class Main {
    static inline var test = 1;
    static function func(arg = test) { }
    static public function main() {}
}
```
