### ISSUE TITLE
Sometime abstract don't do what *I* want...

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2504]
hi,

This one gave me nightmare. It is excerpt from something from h3d.

```
import haxe.ds.Vector;

class _Slots<T> {
	public var content : haxe.ds.Vector<T>;
	public var cur : Int;
	public var allocLength : Int;
	
	public function new(len:Int) {
		allocLength = len;
		
		//runtime value is array of null ( instead of floats )
		content = new haxe.ds.Vector<T>(len+1);
		
		//runtime value is the len
		//content = new haxe.ds.Vector(len + 1);
		cur = 0;
	}
	
}

abstract Slots<T>(_Slots<T>) {
	
	public function new(len:Int) {
		this = new _Slots<T>(len);
		$type(this.content);
		trace(this.content);
		//WTF
	}
	
	/**
	 * add data at the end of the buffer
	 */
	public inline function push(v) {
		return this.content[this.cur++] = v;
	}
}

class Main  {
	
	public function new () {
		var a = new Slots<Float>(500);
		for ( i in 0...400)
			a.push( 1.0 * roll(5,10) );
	}
	
	//rolls an int between a & b
	public static inline function roll(	min ,max  ) {
		return Std.random( max - min +1 ) + min;
	}
}
```

Please, uncomment both calls in constructor and observe runtime values differing
They differs and are wrong both time according to what is types as abstract constructor.

Changing by baking in an Array worked but is not what I wanted.

I think, that vector abstraction is disarrayed by slot child...
Honestly this one was tough, I hope you'll be able to protect user from this...

ps: if it can't be done, we need an error saying that abstract can't embedd other abstracts .. (which is very sad).

Thnaks pals !

**Comment by ncannasse** [comment]
That's too much flash specific to be addressed atm
