### ISSUE TITLE
DCE full, Js and Reflect.setProperty issue

### ISSUE THREAD

**Issue by archeide** [HaxeFoundation/haxe#2509]
Only with js target, dce full. Reproduced on latest nightly build and 3.0.,.
```haxe
class A 
{
	public function new() {}
	
	var _test:Float;
	public var test(get, set):Float;
	
	public function get_test():Float return _test;
	public function set_test(a:Float):Float { _test = a; return _test; }
}

class SimpleTest
{
	static function main()
	{
		var a:A = new A();
		a.test = 3;
		trace("test = " + a.test); 
		Reflect.setProperty(a, "test", 2);
		trace("test = " + a.test);
	}
}
```
The result is test = 3 and test = 3, it seems the setProperty doesn't change the value.
In the code i can see that the A class has no "__properties__" when dce is full while the functions are still there.
And it seems that Reflect.setProperty still check __properties__, so in fact it set a "test" field in A.

**Comment by hughsando** [comment]
Back to this example:
```
class A  {
    public function new() {}
    public var autoTrace(never, set):String;
    public function set_autoTrace(s:String) { trace(s); return s; }
}

class Test {
  static function main()   {
     var a = new A();
     // a.autoTrace = "trace me";
     Reflect.setProperty(a,"autoTrace", "hello" );
  }
}
```
Without DCE - neko + cpp trace hello
With DCE, with "trace me" uncommented - both trace hello
With DCE, no "trace me"
neko - does nothing
cpp - Invalid field:autoTrace

This is as expected?

**Comment by ncannasse** [comment]
@hughsando looks ok, people should use @:keep when doing Relfection + DCE
