### ISSUE TITLE
js.html.ProgressEvent extern : Bad constructor definition

### ISSUE THREAD

**Issue by damoebius** [HaxeFoundation/haxe#2516]
Hi all,
it seems that the constructor definition is not correct.

function new(type : String, canBubble : Bool = true, cancelable : Bool = true) : Void;

should be

new (type, {lengthComputable: aBooleanValue, loaded: aNumber, total: aNumber});

according to https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent.ProgressEvent#Arguments

**Comment by aduros** [comment]
Fixed in new externs.
