### ISSUE TITLE
Completion issue with reused variable name in different scope

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#2542]
```haxe
class Test  {
  public static function main () {
  	var x = [1,2,3];
  	var r = x.map(function (x) return x+1); // here we use x again in different scope
  	r.| // completion positon
  }
}
```

the compiler provides only `Dynamic` for completion at this position. If the function parameter name `x` is renamed to an unused variable like `y` everything works as expected.

**Comment by frabbit** [comment]
any news on this one?

**Comment by ncannasse** [comment]
Looking into it now

**Comment by ncannasse** [comment]
Uhm, I wanted to print the AST with:
```
prerr_endline (s_expr_pretty "" (s_type (print_context())) (type_expr ctx (Parser.reify_expr e) Value));
```

But it complains at runtime about
```
Test.hx:5: characters 5-6 : Identifier 'EVars' is not part of enum haxe.macro.ExprDef (Suggestion: EVars)
```

Which is indeed interesting :)

**Comment by Simn** [comment]
That can happen when you cause a `Not_found` to be raised.

**Comment by ncannasse** [comment]
@Simn that indeed means we have Not_found coming from somewhere else. Maybe we could toggle off this catch to see where it comes from ?

**Comment by Simn** [comment]
Yes, just comment out the `with Not_found` in typer.ml that have "is not part of enum" in their body. There are 3 of them.
