### ISSUE TITLE
c++ currently uses dynamic field lookup where direct call should be possible (type parameters with constraints)

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#2548]
take a look at this code:

```haxe
class Test {

	public static function bar <M:Foo1>(m:M)
	{
		// this creates the following c++ code, although cpp knows that M is of type Foo1
		// m->__Field(HX_CSTRING("doIt"),true)()->__Field(HX_CSTRING("doIt"),true)();
		m.doIt().doIt();
	}
	public static function main () {
		bar(new Foo2());
	}
}

class Foo2 implements Foo1 {
	public function new () {}
	public function doIt():Foo2 {
		return this;
	}
}

interface Foo1 {
	public function doIt():Foo1;
}
```

**Comment by hughsando** [comment]
So Simn, what is the difference here between a type-restriction-of-class and a class?  Can we just run a filter over the tree that removes the kind=KTypeParam if the param is a "normal" class/interface?
Or is there something subtle I am missing.
Other backends may benefit from this.

**Comment by Simn** [comment]
I'll let @ncannasse comment on the difference for the generators because I'm not really sure.

**Comment by ncannasse** [comment]
@hughsando if you find a KTypeParam with a single class or interface constraint, you can replace it by the class/interface in the backend. We don't do that automatically because of the way we unify things. Also, there might be several interfaces constraints, or even maybe several classes constraints which obviously can never be matched :)

**Comment by Simn** [comment]
See #2712 too.

**Comment by hughsando** [comment]
Sounds like something all typed backends will want to do.  Can we make it a pre-generation filter?

**Comment by hughsando** [comment]
As a result of the way interfaces are now implemented, this should be generating efficient code now.
