### ISSUE TITLE
No way to clear a Map<K, V> besides re-instantiation

### ISSUE THREAD

**Issue by mreshet** [HaxeFoundation/haxe#2550]
Would a clear() method would be more efficient than re-instantiation?

**Comment by wighawag** [comment]
would be cool to have as of now there is no way to clear a map without allocation (both js and cpp create a new Array for iterating over keys) Did not looked at other targets.

**Comment by romamik** [comment]
From the other hand it does not look safe to iterate keys and remove them from map in the loop. It may be safe for current js and cpp map implementation, but there is no guarantees it will work on other platform or in future. To be safe one needs to save keys in external array, and then remove keys in loop over this array.

Clear method would be great. But also stating in documentation that removing keys in loop over map is safe is also a solution.

**Comment by Aurel300** [comment]
Could we re-open this? There is `array.resize(0)` on arrays. Additionally `map.clear()` is a lot more useful for `final` map instances.

**Comment by nadako** [comment]
pls deliver:)

**Comment by sbijoshj** [comment]
🎉 Thank you!
