### ISSUE TITLE
Scientific Float notation generates invalid neko source code with -D neko-source

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#2553]
Test code:

```haxe
package;

class Main 
{
	private static var someNumber:Float = 1e-8;
	
	static function main() {}
}
```

Compiled with `-D neko-source`, running `nekoc run.neko` (compiles without errors) and `neko run.n` gets me the following stack trace:

```batch
Called from run.neko line 956
Uncaught exception - Invalid operation (-)
```

line 956: 
```neko
Main.someNumber = 1e-8;
```

Seems like neko doesn't support this scientific float notation at all, yet neko source code is generated with it.

**Comment by ncannasse** [comment]
There's several neko-source issues but I'm not planning to support them. ATM neko-source is mostly used to debug neko output, not to be compiled on its own.
