### ISSUE TITLE
C++: cast-by-copy can lead to incorrect and unexpected behaviour

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2579]
The same as #2103 for C# (see discussion). The issue is pretty hard to detect and avoid and should be either dealt with somehow or well-documented.

I know it's tricky to fix without boxing everything and the use case is quite particular, but it can lead to very hard-to-find bugs and frustration.

If there's no ways to deal with the issue, we should look into adding a compiler error on affected platforms, if possible.

Example code:
```haxe
class Main {
    static function main() {
        var house:{tenantIds:Array<Int>} = haxe.Json.parse('{"tenantIds": [1, 2, 3]}');
        var tenants = house.tenantIds;
        tenants.push(4);
        trace(house.tenantIds); // [1,2,3]
    }
}
```

Generated C++:
```cpp
Dynamic house = ::haxe::Json_obj::parse(HX_CSTRING("{\"tenantIds\": [1, 2, 3]}"));

// here's where cast by copy happens and tenants is no longer house.tenantIds
Array< int > tenants = house->__Field(HX_CSTRING("tenantIds"),true);
tenants->push((int)4);
::haxe::Log_obj::trace(house->__Field(HX_CSTRING("tenantIds"),true),hx::SourceInfo(HX_CSTRING("Main.hx"),6,HX_CSTRING("Main"),HX_CSTRING("main")));
```

**Comment by Simn** [comment]
This should have high priority because it leads to silent failures that are not always easy to detect. I would prefer if this failed at run-time.

**Comment by ncannasse** [comment]
I've been studying the issue quite closely recently, I don't have yet a definite answer to provide, still looking at possible solutions but it's hard to deal with while keeping Array of basic types efficients on native platforms.

**Comment by hughsando** [comment]
I have proto-typed up a solution that should work - along the lines of what
I ended up doing with the map class.
This involves using a "VirtualArray" in place of the Array<Dynamic> class,
which can wrap a real array of basic types (bool, string, int, float,
object).  If you ever assign this to, say, and Array<Int>, it locks the
underlying type to they refer to the same instance.  I just have been a
little scared to push forward with it, since it will almost certainly break
something.

**Comment by Simn** [comment]
Well, it _should_ break something. The question is if it also breaks something it shouldn't break. Is there anything I can do to help test?

**Comment by ncannasse** [comment]
I have also worked on a solution while working on HL, which seems similar to what hugh is proposing.

There is an ArrayDyn (which is a special wrapper type), which wraps a "base" Array (either ArrayI32/ArrayF64/ArrayObj).

If the ArrayDyn is cast to a base Array type, it will allow to rebuild it to another value only if the ArrayDyn was created directly with `new Array<Dynamic>()` (or `Array<T>`)

The source code is available here:
https://github.com/HaxeFoundation/haxe/blob/hl/std/hl/types/ArrayDyn.hx

I have not yet implemented the code that will make sure that ArrayDyn == ArrayBase

Another problem is for "length" property. At compilation I'm replacing all ArrayDyn.length by ArrayDyn.getLength() which returns the wrapped ArrayBase.length

However if the ArrayDyn is accessed as Dynamic, I don't have yet a reflection mecanism that will allow me to call ArrayBase.getLength().

@hughsando and @waneck can you look and comment at my code?

**Comment by nadako** [comment]
Can this be auto-generated to work on any parametrized types like this? c# target currently generates the `hx_cast` function that repopulates native arrays because of type change so it works for any custom class, I imagine we could instead auto-generate wrapper types like that.

**Comment by ncannasse** [comment]
@nadako yes I guess it could be generated. The case of Array is a bit particular because my underlying storage is different for pointers and numeric types

**Comment by hughsando** [comment]
I would be nice if you can have a generic solution for substituting
Array<KTypeParam> with a target specific version.

**Comment by nadako** [comment]
Didn't @Simn and @ousado experimented with some specialization for genc?

**Comment by Simn** [comment]
Yes but that was to create Arrays for types of different element sizes.

**Comment by hughsando** [comment]
Along similar lines, I would like to see a @:partialGeneric, which creates
@:generic implementations for int/float/bool/String, and "any object".  And
then enable this by default for cpp.  This would only partially solve the
problem though - still missing the parse-json case.

**Comment by ncannasse** [comment]
@hughsando the problem with @:generic is that you don't actually create a subtype. Let's solve the Array problem first and look at how we can generalize on other generics after we get feedback on the new behavior
