### ISSUE TITLE
haxe.Http class should not use Strings to represent binary data

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#2586]
We have modified the C++ String implementation to correctly support UTF-8 strings.  Our implementation does not accept improperly encoded UTF-8 strings, and we have found that when using the haxe.Http class, the representation of binary data as Strings in functions like onData and setPostData causes problems.

Using a String as a container for binary data implies that the String internal representation is in bytes; but this is a problematic assumption to make when the String internal representation is UTF-8.

Another issue is the fact that binary data used in onData and setPostData may have embedded 0 values (nulls), and embedded nulls are in general at odds with string representations.

Why don't onData and setPostData use Bytes objects instead of Strings?

**Comment by ProPuke** [comment]
I propose the addition of an `encoding` enum (`UTF8` or `BINARY`) parameter for `Http`. The default value being `HttpEncoding.UTF8`. The `onData` callback could be set to `Dynamic` and return either a `String` or `Bytes` depending on the value of this parameter.

This is backward compat, allows the addition of other future encodings, and allows differing platforms to conditionally support encodings. It does leave a slightly unsightly `Dynamic`, though.

**Comment by singpolyma** [comment]
It doesn't make a lot of sense for the user to specify the encoding, since HTTP has built-in ways for the server to specify that.

**Comment by ProPuke** [comment]
A lot of the time when requesting content specifying a format to receive in makes a lot of sense. For example, if requesting an html or json url text content is presumed. If requesting a downloadable asset a binary encoding is presumed (you may wish to request a binary encoding even if downloading an ascii file, so that it can be saved locally in a byte-identical form). In these cases explicitly stating what format to receive makes a lot of sense. If this encoding is not available for the data received, a suitable error should occur instead.

An `HttpEncoding.AUTO` could be available for letting the server dictate the encoding if you wish to dynamically handle all cases.

**Comment by ncannasse** [comment]
@Simn could you review the changes needed to have haxe.io.Bytes results for haxe.Http, VS introducing a new haxe.io.Http that works the same as haxe.Http but with binary data ?

**Comment by Simn** [comment]
Are you just talking about the results passed to onData/onError or is this also about other parts which currently use strings (responseData, responseHeaders, headers, params)?

**Comment by back2dos** [comment]
The protocol headers are supposedly "human readable", so String should do
the job there, while having a binary body would definitely would be useful.

**Comment by hughsando** [comment]
I agree the headers should be strings.
The body might be a good use case for abstract - if could return a
"ResponseData(haxe.io.Bytes)", which when assigned to a string does
utf8->string (throwing an error on invalid utf8 for security reasons), or
to a unicode (utf32?) string converts correctly, or to a Bytes passes
though automatically for maximal compatibility and performance.  Such an
object might be useful in other ways too.

**Comment by ProPuke** [comment]
For reference: I pushed an update across to [dionjwa/nodejs-std](https://github.com/dionjwa/nodejs-std) at the same as making my original suggestion, as I need the functionality on a haxe node project.

You can view the pull requests [here](https://github.com/dionjwa/nodejs-std/pull/38).

**Comment by ncannasse** [comment]
I agree we could keep headers as String, hopefully there will no UTF-8 incompatible header.

**Comment by Simn** [comment]
Well then it's just a question of what to do with the interface. We can't just change the type of onData/onError.

**Comment by back2dos** [comment]
How about just leaving `onError:String->Void` and having an additional `onBytes:Bytes->Void`. Usually when you get an error body, it's human readable or just a white screen of death, in which case bytes vs. string doesn't make much of a difference either.

Other options:

- Add an onErrorBytes callback if needed (personally I'd not add it unless someone actually asks for it)
- Make `onData` and `onBytes` and abstract with `@:from String->Void` and @:from Bytes->Void (but this is probably going to break code that relies on inference for the callback argument type)

**Comment by waneck** [comment]
If we keep any part as a string, we should still make sure that an invalid
UTF string there won't crash the Http class in an unexpected way

**Comment by Simn** [comment]
@back2dos: Are you saying Http should call both onBytes and onData?

**Comment by back2dos** [comment]
Yes, both. You could change them from `dynamic function` to `var` and check for `null` to not have to convert `Bytes` to `String` or vice versa on platforms where that's expensive.

**Comment by Simn** [comment]
I've unassigned myself because I don't feel comfortable working on this. If someone sends a pull request we can review it accordingly.

**Comment by volth** [comment]
> The String usage comes from historical reasons, where we didn't have haxe.io.Bytes, as well as the lack of binary data support on some platforms (JS only got typed arrays in Chrome 7 in late 2010 and Firefox 4 in mid 2011)

Ironically, the current (3.4.2) haxe.Http does not allow to download binary data into a string, neither in the old browsers nor in new ones.
It additionaly requires ```r.overrideMimeType('text/plain; charset=x-user-defined');``` before ```r.send(uri);```.
Then resulting string would contain only codes in 0x00..0x7F, 0xFF80..0xFFFF which could be converted to Bytes by ```s.charCodeAt(i) & 0xFF```.
Whithout ```overrideMimeType``` the binary data gets corrupted.

**Comment by cancerberoSgx** [comment]
What's the status of this issue ? is any way of requesting binary content (for example images) ? The following works on neko but breaks in cpp and java:

```haxe
  var http = new haxe.Http(url);
  http.onData = function (data:String) {
    var bytes = haxe.io.Bytes.ofString(data);      
    // I tried with Encoding.UTF8 and Encoding.RawNative but not success.
  };
  http.request();
```

Any workaround to request binary content is most appreciated. Thanks!

**Comment by Aurel300** [comment]
A small update to some of the old messages in this thread: `String` in Haxe is now only for textual, UTF-8 data, so it is not safe to use it to store binary data (which would be invalid UTF-8 in general). The only exception is `neko`, which is not Unicode-safe.

There has not been a binary-safe refactor for `Http` as of yet.

**Comment by cancerberoSgx** [comment]
This is how I accomplished to get binary content on sys targets. Unfortunately customRequest method, although it won't give compilation errors, it's not documented. (So a cheap solution could be just exposing that method or an alias and document it). Hope it help others:

```haxe
var req = new haxe.Http(url);
var responseBytes = new haxe.io.BytesOutput();
req.customRequest(false, responseBytes, null, "GET");
var bytes = responseBytes.getBytes();
```

This is a fetch() function that will work on all targets, including node.js and the browser:

```haxe

public static function fetchResource(url:String, cb:(error:Dynamic, data:haxe.io.BytesData) -> Void) {
  #if js
  untyped if ((typeof(window) == 'undefined' || typeof(window.fetch) == 'undefined') && typeof(process) != 'undefined') {
    untyped require('https').get(url, resp -> {
      var data = [];
      resp.on('data', chunk -> {
        data.push(chunk);
      });
      resp.on('end', chunk -> {
        var body = Buffer.concat(data);
        cb(null, body);
        return null;
      });
    }).on("error", (err) -> {
      cb(err, null);
    });
  } else {
    untyped js.Browser.window.fetch(url).then(response -> response.arrayBuffer().then(data -> cb(null, data)));
  }
  #else
  var req = new haxe.Http(url);
  var responseBytes = new haxe.io.BytesOutput();
  req.onError = function(err) {
    cb(err, null);
  };
  req.customRequest(false, responseBytes, null, "GET");
  cb(null, responseBytes.getBytes().getData());
  #end
}

```

I would be glad to create a cookbook example with these, but I feel it will be rejected since the method is not exposed. What do you think?

**Comment by cancerberoSgx** [comment]
Also a small feedback, you want to expose a signature based on `haxe.io.Input` and `haxe.io.Output` rather than in `haxe.io.Bytes` since they support more use cases like streams.

**Comment by Aurel300** [comment]
4.1 (hopefully) will bring streams and a more Node.JS-like API for HTTP, see https://github.com/HaxeFoundation/haxe-evolution/pull/59
