### ISSUE TITLE
Haxe generated SWC warnings Map/Xml

### ISSUE THREAD

**Issue by pshtif** [HaxeFoundation/haxe#2590]
package test;
class TestInternal {
    private var testMap:Map<String, Dynamic>;
    private var testXml:Xml;

    public function new() {
        testMap = new Map<String, Dynamic>();
    }
}

Using this simple source code inside AS3 as an SWC will throw these warnings:

The definition XmlType depended on by Xml in the SWC test.swc could not be found.
The definition Map depended on by test.TestInternal in the SWC test.swc could not be found.

Using Maps a lot this can generate huge number of warnings for moderately large project and should be adressed.

Also there is another warning that I was unable to reproduce with short example when using ERegs such as

The definition +Array depended on by EReg in the SWC test.swc could not be found

Thank you.

**Comment by Simn** [comment]
This has been addressed by the new Xml implementation.
