### ISSUE TITLE
Unable to call a protected super.method() in flash target

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#2599]
Unable to call `super.method()`, where the super class is defined in a swc (`-swf-lib`) and the child class is defined in haxe. The accessor of `method()` is `protected`. 

The following error appeared in runtime:

```
[Fault] exception, information=ReferenceError: Error #1065: Variable method is not defined.
```

Investigating the bytecode of the swf, seems that the correct way to call a protected super method is

```
callsuper Qname(ProtectedNamespace("path.to:SuperClass"),"method")
```

while haxe generated:

```
callsuper Qname(PackageNamespace(""), "method")
```

**Comment by Khaledgarbaya** [comment]
any updates on this issue is it fixed ?

**Comment by nadako** [comment]
@ncannasse are you going to do something about this?

**Comment by ncannasse** [comment]
We won't do much flash-specific fixes in the near future, closing.
