### ISSUE TITLE
Cannot use PI/NaN/Inf/-Inf as default param

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#2608]
The following cannot be compiled with error `Parameter default value should be constant`:

``` haxe
function test(
    pi = Math.PI, 
    nan = Math.NaN, 
    inf = Math.POSITIVE_INFINITY, 
    ninf = Math.NEGATIVE_INFINITY
){}
```

Since those values should never change, so I think there is no problem on allowing the above?

Would it be good to generalize to allow the use of `(default, never)` prop as default param?

**Comment by quakeboy** [comment]
After all these years, I still had this confusion right now.
