### ISSUE TITLE
[macro] Quoted fields in EObjectDecl

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2642]
When working with `EObjectDecl` expressions, fields that are not valid indentifiers are prefixed with `@$__hx__`:

``` haxe
var e = macro {"a-b": 10};
trace(e.expr); // EObjectDecl([{ expr => ..., field => @$__hx__a-b }])
```

It seems to be an accidentally exposed internal compiler thing that should be unquoted before passing to macros, because it's very inconvenient and error-prone to always have to remember to unquote this and I can't think of a situation where actually having this prefix could be useful in a macro.

**Comment by nadako** [comment]
There's a small regression now because of the quoted field preserving change. I.e. in 3.1.3 macro {"a": 1} was generated as EObjectDecl([{ field : "a", ..., but it's generated as EObjectDecl([{ field : "@$__hx__a", .... That could affect users' macro.

**Comment by Simn** [comment]
I don't have a solution for this with the current way of passing the "quoted" state.

**Comment by kevinresol** [comment]
what is the proper way to (manually) quote a field?

consider the following example:

```haxe
var name = "$type";
if(name.startsWith("$")) name = "@$__hx__" + name;
var  e = macro {$name: "value"};
```

Instead of `name.startsWith("$")`, what is the proper way to check if the field name should be quoted?

**Comment by ncannasse** [comment]
I'm not sure why I was assigned on this one :)

**Comment by Simn** [comment]
As punishment for implementing that crap. :P
