### ISSUE TITLE
hxcpp...Null<Float> schrodinbug

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2662]
In h3d branch motion twin :

https://github.com/ncannasse/h3d/issues/41

```
inline function extLeft() : Float {
	//System.trace1("m:" + Std.string(style.marginLeft) );
	return style.paddingLeft + style.marginLeft + style.borderSize;
}

```
```
style.* are Null<Float>
```

Uncommenting the trace make the calculus right otherwise something bloated is returned. I can't find how to reproduce on a small sample so you might want to insta-close this one but I thought knowing it is here lurking is a pertinent knowledge.

xoxo

**Comment by hughsando** [comment]
With this code:
```
class Test
{
    public static function main()
    {
        var a : Null<Float> = null;
        var b : Null<Float> = null;
        trace("1" + a);
        trace(a+b);
        trace(1 + a);
    }
}
```
The first trace is "1null" as expected on the targets.
The second two return 0 on cpp, crash on neko.
Do we want to specify the behaviour here?  I can track down the places and throw errors if required.

**Comment by ncannasse** [comment]
@hughsando this behavior seems ok for me, it's in-line with default Float value being 0 in C++

@delahee could you send a small reproducible example not involving any third party library ?

**Comment by delahee** [comment]
I'll close for now and reopen if I restumble on it with easy repeatable code.
