### ISSUE TITLE
[cs] equality check for Dynamic fails at runtime when comparing Float and String

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2668]
Subj. The following code crashes at runtme with `System.FormatException`. It looks like the `ToDouble` methods tries to parse given string to double. I guess we have to rewrite that `Runtime.eq` function to be more careful about `IConvertible`. cc @waneck 

``` haxe
class Main
{
    static function main()
    {
        var a:Dynamic = 1.5;
        var b:Dynamic = "s";
        a == b;
    }
}
```

Same thing with integers.

**Comment by Simn** [comment]
The test for this issue causes me some problems on As3 because it doesn't respect a cast to Dynamic. This can be reproduced like so:

```haxe
class Main {
	@:analyzer(ignore)
	static function main() {
		trace((1.5 : Dynamic) == ("s" : Dynamic));
	}
}
```

While the dump has casts in place:

```
[Binop:Bool]
	[Cast:Dynamic] [Const:Float] 1.5
	==
	[Cast:Dynamic] [Const:String] "s"
```

The generated As3 tries to do a direct comparison:

```as3
		static public function main() : void {
			(haxe.Log._trace)(1.5 == "s",{ fileName : "Main.hx", lineNumber : 31, className : "Main", methodName : "main"});
		}
```

Which fails:

```
Error: Comparison between a value with static type Number and a possibly unrelated type String.
```

I'm not sure what we can do about this though.

**Comment by Simn** [comment]
Not a regression and because user var fusion is still deactivated on Flash it shouldn't create such constructs either. Pushing to 3.4.

**Comment by Simn** [comment]
Looking at this again, I don't think we have to do anything. It's true that you can make native compilation fail by abusing Dynamic like that, but there's only so much we can do about that in general anyway.
