### ISSUE TITLE
[java] Warning : No overload found for this constructor call

### ISSUE THREAD

**Issue by singpolyma** [HaxeFoundation/haxe#2679]
What does this warning mean?  It seems to be because I'm extending a Java class and adding a constructor with more arguments -- but it works fine?  What's the "right thing" to do so this warning goes away?  My code works fine, but I'd rather not have warnings for users of my library :)

**Comment by waneck** [comment]
2b9fb237fdf029fcd7cd73cd69a74e should handle these cases. Feel free to reopen if you still see it
