### ISSUE TITLE
"Array<Int> has no field length"

### ISSUE THREAD

**Issue by singpolyma** [HaxeFoundation/haxe#2687]
The following code gives the error "Array<Int> has no field length"
    
    private enum Unit {
       Unit;
    }
    
    class AsyncTask<A> extends android.os.AsyncTask<A,Unit,Unit> {

       private var task:Array<A> -> Void;

       @:overload public function new() {
          super();
          throw "AsyncTask must be given a function";
       }
    
       @:overload public function new(tsk:A -> Void) {
          super();
          var y = function(x:Array<Int>) {
             if(x.length != 1) throw "This AsyncTask requires exactly one argument";
          };
       }
    
    }

If I remove the first (no argument) constructor, then it works fine.  What's happening here?

**Comment by waneck** [comment]
@singpolyma can you please check if that fixes it for you?

**Comment by waneck** [comment]
Feel free to reopen if it didn't solve for you. Closing for now
