### ISSUE TITLE
No automatic Linux installer

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#2708]
There should be an installer for Linux that does not require manually unzipping archives. Especially for Neko, this will result in trouble. As a full-time Linux user, I can say that "build from the source" is not always appreciated as a recommendation for an install. We have an automatic installer for Linux here:

http://www.openfl.org/haxe-3.1.0-linux-installer.tar.gz

If you would be interested in hosting this in the Haxe.org download page, or at least linking, it would be appreciated (or if you have an alternative, that is fine as well). I noticed that the link was removed.

Thanks!

**Comment by Simn** [comment]
Let's keep track of this in https://github.com/HaxeFoundation/haxe.org/issues/75
