### ISSUE TITLE
haxe.macro.Context.onTypeNotFound is called for native implementations of core types

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#2741]
I registered this handler:

	haxe.macro.Context.onTypeNotFound(function (s:String) {
		haxe.macro.Context.warning(s, haxe.macro.Context.currentPos());
		var ret = macro class {},
			path = s.split('.');
		ret.name = path.pop();
		ret.pack = path;
		return ret;
	});

It get's called an awful lot, resulting in a lot of errors:

```
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:139: lines 139-141 : Invalid number of type parameters for haxe.Array
Warning : haxe.Enum
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:41: lines 41-43 : Invalid number of type parameters for haxe.Enum
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:54: lines 54-56 : Invalid number of type parameters for haxe.Enum
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:70: lines 70-72 : Invalid number of type parameters for haxe.Enum
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:87: lines 87-89 : Invalid number of type parameters for haxe.Array
C:\HaxeToolkit\haxe\std/haxe/EnumTools.hx:99: lines 99-101 : Invalid number of type parameters for haxe.Array
Warning : neko.Array
C:\HaxeToolkit\haxe\std/neko/NativeArray.hx:34: lines 34-36 : Invalid number of type parameters for neko.Array
C:\HaxeToolkit\haxe\std/neko/NativeArray.hx:38: lines 38-40 : Invalid number of type parameters for neko.Array
C:\HaxeToolkit\haxe\std/neko/NativeArray.hx:46: lines 46-48 : Invalid number of type parameters for neko.Array
Warning : neko.String
Warning : haxe.io.String
Warning : neko.Std
C:\HaxeToolkit\haxe\std/neko/_std/String.hx:25: characters 54-59 : String should be neko.String
C:\HaxeToolkit\haxe\std/neko/_std/String.hx:25: characters 54-59 : For function argument 'lib'
```

Now this gives me funny ideas about injecting behavior into the std lib, but to be honest I don't think this is wise. Could it just be that two calls in the typer are made in the wrong order, or is this actually intended?

**Comment by ousado** [comment]
onTypeNotFound is clearly for people who know what they're doing. Please don't limit what it can do before the first 5000 or so great use-cases are well-documented and we can have an informed discussion about the trade-offs involved in limiting its power :)

**Comment by Simn** [comment]
Thinking about it again it should actually be fine to specify this as working as intended. The advantage of going through the macro for each check is that you can decide whether or not to handle a specific path. This might make compilation a bit slower but it also makes it more powerful.
