### ISSUE TITLE
Local variable x used without being initialized

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#2774]
```
class Main {
    static public function main() {
        var x;
        do {
            x = "foo";
        } while(x == null);
        use(x); // Local variable x used without being initialized
    }

    static function use(x) { }
}
```

This comes from rewriting `do ... while()` to `while()` in https://github.com/HaxeFoundation/haxe/commit/17844fd1be6c5efa573530873235759474e1d716.

I think we should do the var initialization check for starting to optimize things.

@andyli: One thing that confuses me is that this also causes a failing macro unit test: https://travis-ci.org/HaxeFoundation/haxe/jobs/21024718#L729

The relevant optimization is guarded against Cpp and Flash8 targets here: https://github.com/HaxeFoundation/haxe/blob/development/filters.ml#L1162

I also don't get the failing test locally. What's going on there?

**Comment by NekR** [comment]
@nadako

So I have code like this:

```haxe
var something = Null<Node>;

while (a < b) {
  if (okay) {
    if (something == null) {
      something = new Node();
    }
  }
}
```

And I get `Local variable something used without being initialized`. How I supposed to initialize it?

**Comment by nadako** [comment]
> `var something = Null<Node>;`

This is not valid haxe code :) You can initialize a variable with null.

**Comment by NekR** [comment]
@nadako Yeah, just a typo. I meant `var something: Null<Node>;`. Initialization with `null`: `var something: Null<Node> = null` does not help.

**Comment by nadako** [comment]
I don't know, this compiles fine for me:
```haxe
class Node {}

class Main {
    static function main() {
        var a = 1, b = 1, c = 1, d = 1, okay = false;
        function getNode():Node return null;

        var something:Null<Node> = null;
        while (a < b) {
            for (i in c...d) {
                if (okay) {
                    if (something == null) {
                        something = getNode(); // returns Node
                    }
                }
            }
        }
    }
}
```
