### ISSUE TITLE
Allow operator overloading and cast methods in classes

### ISSUE THREAD

**Issue by Herschel** [HaxeFoundation/haxe#2803]
I have seen several people on haxelang or IRC ask about operator overloading. They have some Vector2D that they want to add operators to, but then they read about abstracts and get confused. It's not trivial for a new user to create a separate wrapped type, write forwarding methods/properties, and juggle the abstract vs. underlying type. Why should this be necessary just to support addition on a vector?

It seems to me that wrapping an underlying type is orthogonal to operator overloading or casts. I don't see any reason why `@:op`, `@:from`, and `@:to` could not be allowed on classes, as well. Allowing operator methods directly on the class would simplify the common case of vectors and matrices.

This would be a big change in the compiler, so this is a longer-term issue for discussion.

**Comment by Herschel** [comment]
Just as an example of how class operator overloading might look:

```haxe
class Vector2 {

  public var x : Float;
  public var y : Float;

  public function new( x : Float = 0, y : Float = 0 ) {
    this.x = x; this.y = y;
  }

  @:op(A+B) public static function add( a : Vector2, b : Vector2 ) : Vector2
    return new Vector2( a.x + b.x, a.y + b.y );
}
```

This would be the same if ops were implemented via static extensions, too -- it would require the user to add `using Vector2` to their module.

BTW, I'm not concerned so much with implicit casts. I think they are mostly bad style anyway. I just figured they were under the same umbrella of "doesn't need to be an abstract".

**Comment by back2dos** [comment]
Any news on this? Operator overloading by means of static extensions sounds like a sound idea.

**Comment by Simn** [comment]
I don't think this is a good time to ask about long term issues.

**Comment by back2dos** [comment]
Ok, sorry, never mind then. I just ran into a situation where this would be very helpful. Also, I thought I could take advantage of the calm before the storm that'll ensue once rc.1 ships officially ;)

**Comment by Simn** [comment]
This approach might cause regressiosn in cases abstracts are used via static extensions. I had to fix some parts of `Int64` because it was using itself as static extension, which lead to operations like `Int - Int` being resolved to one of its `@:op(A - B)` methods.

This is not enough for me to dismiss the entire approach, but I'll have to think about it a bit more.

**Comment by nadako** [comment]
Now when we have #1138 implemented, this thing is actually very useful IMO!

**Comment by ncannasse** [comment]
This will have to go through Haxe Evolution process, although I'm still against it given it's covered by abstracts.
