### ISSUE TITLE
Compiler.addClassPath doesn't add the macro class path

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#2815]
The following example demonstrates the problem:
`Main.hx`
```haxe
class Main
{
	static function main()
	{
		doMacro();
	}

	macro public static function doMacro()
	{
		haxe.macro.Compiler.addClassPath('somePath');
		var type = haxe.macro.Context.getType('SecondFile');
		return macro null;
	}
}
```
`somePath/SecondFile.hx`
```haxe
#if !macro
@:build(Macro.build()) class SecondFile
{
}
#end

class Macro
{
#if macro
	public static function build()
	{
		return null;
	}
#end
}
```

Compiling this will fail with the cryptic error:
`somePath/SecondFile.hx:2: characters 2-7 : Class not found : SecondFile`

**Comment by ncannasse** [comment]
That seems fair to me, given that haxe.Compiler allows you to modify the "compilation context" which is quite different from the running macro context. I guess we would need extra API for modifying the macro context, but that might mean adding extra flags to many functions. I find it's not enough useful to justify the change.
