### ISSUE TITLE
Structural subtyping + abstracts

### ISSUE THREAD

**Issue by Herschel** [HaxeFoundation/haxe#2822]
This fails with `MyAbstract should be MyType` and `MyAbstract should be { foo : Void -> Void }`:

```haxe
abstract MyAbstract(Int)
{
    public function new()
    {

    }

    public function foo()
        trace( "Foo" );
}


typedef MyType = { function foo() : Void; };

class Main {
  static function main(){
    var a : MyType = new MyAbstract();
  }
}

```

**Comment by singpolyma** [comment]
this is a bit confusing -- should it not be possible at compile time to tell that the method is indeed present and unify?  Doing eg:

```
final x = new MyAbstract();
var a : MyType = { foo: () -> x.foo() };
```

for example already works.

**Comment by tobil4sk** [comment]
`MyType` represents a type where a `foo` method can be accessed dynamically, but the runtime `Int` type is a primitive and does not have a `foo` method.
