### ISSUE TITLE
[cpp] Single Float on cpp

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#2842]
Hey !

It would be cool to have Single implemented on cpp like in cs/java (http://api.haxe.org/Single.html). 

When I try to compile
```
 	var a : Single = 1.0; 
```

The class Single is not found

On cross platform, an abstract could emulate them efficiently. This would allow some very efficient optimisation for data passing and computing.

Thx !

**Comment by hughsando** [comment]
cpp.Float32 should solve the problem now.
