### ISSUE TITLE
[php] incorrect value using readDouble and big endian

### ISSUE THREAD

**Issue by hXJFL** [HaxeFoundation/haxe#2846]
var bytes = haxe.io.Bytes.alloc(8);
bytes.set(0,0x40);
var input = new haxe.io.BytesInput(bytes);
input.bigEndian=true;
trace(input.readDouble());//neko:2, php:3.162020133384E-322

**Comment by ncannasse** [comment]
Should be fixed in GIT

**Comment by Simn** [comment]
I would like to add a test case.
