### ISSUE TITLE
hxcpp inconsistency on dynamic property access

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#2852]
```
class Main {

	static var x(get, null):String;

	static function get_x() return "foo";

	static public function main() {
		var m:Dynamic = Main;
		trace(m.x); // foo
	}
}
```

This traces `foo` on the C++ target and `null` on all other targets I tested. The documentation states that this should not respect the getter: http://haxe.org/ref/properties#important-remarks

@ncannasse: Do you confirm that this is a bug?

**Comment by Simn** [comment]
I still don't get it...

```haxe
var d:Dynamic = somethingThatHasNativeProperties;
d.someField;
```

The real field is never seen, so the metadata is never found.

**Comment by ncannasse** [comment]
@hughsando could you confirm that hxcpp now follow the spec ?
@Simn could you add unit test for it and close the issue if it passes ?

**Comment by hughsando** [comment]
I have not done this yet.  I think you should give fair warning that all library maintainers need to add this meta to all their properties, otherwise you will break a lot of code for anyone who uses a git version of haxe.  Particularly, you need to get openfl to add this property everywhere.

**Comment by Simn** [comment]
I think we should:

1. Implement it.
2. Hide it behind a `-D 3_2_property_change` flag so people can adapt their code.
3. Communicate that properly.
4. Make it the default shortly before 3.2 release.

**Comment by ncannasse** [comment]
I prefer the "Break early, break often" :)

More seriously : if we hide that behind a flag, we will only get people to adapt this once we release, which is not good. I prefer we update right now the GIT version, so people using GIT will complain to the library maintainer which will then fix it (or fix it himself if he uses GIT).

That's IMHO the best way to ensure most of the libraries are working when we release 3.2

**Comment by andyli** [comment]
What about:
 * Default to the breaking change, and
 * Have a flag "-D deprecated_property" which hide the change
such that library authors know that there is a need to update their code, and people can temporarily use the flag to workaround until there is a proper fix to the libraries.
