### ISSUE TITLE
No stack trace in Javascript

### ISSUE THREAD

**Issue by Schipy** [HaxeFoundation/haxe#2854]
Haxe runtime uses strings in _throw_ statements, which compile to string _throws_ on Javascript. This however will lack stack trace when handled and logged which make Haxe a very hard language to debug on JS (putting developers back to the age of trace logs practically)

I have a branch with a possible solution, and I'm interested in your opinion and how you think it fits into the Haxe ecosystem and vision.

https://github.com/Schipy/haxe/tree/js_error

The idea is that the JS code generator inserts an instrumented throw statement in place of all throw statements, that will throw a proper JS Error in case the expression evaluates to string, and throws the original result if not. 

See:
https://github.com/Schipy/haxe/blob/77f34e6fe885453c0ec70f8e980a4569cadf0403/genjs.ml#L498

One of the potential problems I see is that this change is not 100% percent backward compatible, catch blocks that rely on the type are affected. However I thought that
- this fits into Haxe philosophy, most version changes so far introduced breaking changes and user code needed to be updated
- it solves the problem without the need to modify all throw statements in std or user code
- if some crossplatform Error type is planned to be introduced in Haxe, it is not incompatible with that, but offers a solution even in the meantime

I'm looking forward to hear what you think about this

**Comment by nadako** [comment]
should be fixed now
