### ISSUE TITLE
js.html.DOMFormData append() method should allow File and Blob

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#2867]
The current js.html.DOMFormData append() method allows only String values:
```
function append(name:String, value:String, filename:String):Void
```

However, [it should also allow File or Blob values](https://developer.mozilla.org/en-US/docs/Web/API/FormData):
```
void append(DOMString name, File value, optional DOMString filename);
void append(DOMString name, Blob value, optional DOMString filename);
void append(DOMString name, DOMString value);
```

See [here](http://xhr.spec.whatwg.org/#interface-formdata) for more info.

Another problem I have is that even if I wrap in a untyped { } block a call to the DOMFormData.append() method with a Blob as parameter, it won't compile:

```
haxe build.hxml 
(...) : Null<js.html.Blob> should be String
(...) : js.html.Blob should be String
(...) : For function argument 'value'
```

**Comment by aduros** [comment]
Fixed in new externs.
