### ISSUE TITLE
[bug][C++] compile error in haxe/io/Bytes.cpp

### ISSUE THREAD

**Issue by arlez80** [HaxeFoundation/haxe#2885]
Compile failed in haxe/io/Bytes.cpp:
this->b->blit(pos,src->b,srcpos,len);

corrects as follows, it worked.
haxe/io/Bytes.hx (90-91):
// #elseif cpp
// b.blit(pos, src.b, srcpos, len);

**Comment by hughsando** [comment]
I think this has been fixed by using haxelib to update the hxcpp version.
