### ISSUE TITLE
[debian] Please document compatibility of jquery javascript library

### ISSUE THREAD

**Issue by bastien-roucaries** [HaxeFoundation/haxe#2893]
Can I replace haxe/std/js/jquery  by lastest debian version aka 1.7.2 ?

It will be nice to document the compatibilty, thus we could update if needed.

The same with swfobject-1.5.js.

Bastien

**Comment by waneck** [comment]
I'd love to add some automated test for this or something, but I really don't have the time for 3.2 . Does anyone know the compatibility of the jquery externs definitions? @ncannasse / @andyli  ?

**Comment by andyli** [comment]
The jQuery source file [bundled in std](https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery-latest.min.js) is 1.6.4. There are methods being deprecated in later version, but most of them are still there, except a few have been removed in 1.9 (ctrl-f for `removed :` in [jQueryExtern](https://github.com/andyli/jQueryExternForHaxe/blob/master/jQuery/JQuery.hx)).

**Comment by waneck** [comment]
@andyli , I'm assigning to you after hearing about the work you're doing with regards to the jquery externs at the standard library! Great to know about the news :)

**Comment by andyli** [comment]
For jQuery, it will be addressed in #4377.
Keeping this open to remain me to update swfobject support.

**Comment by andyli** [comment]
I've added new SWFObject extern in #4451
It supports SWFObject 2.3, and is compatible with SWFObject 2.2.

@bastien-roucaries
I'm currently looking into the debian package and I wish I can help maintain it in the long term.
I can see that the latest debian package replaces the haxe bundled jQuery and SWFObject with symlinks to the system ones. Right now the new externs coexist with the old ones (deprecated), which means it bundle 2 versions of both jQuery and SWFObject. I'm not sure how the symlinks will work for future debian package update? Generally, what happen if haxe bundles a version of a JS lib that is incompatible with the debian version?

**Comment by andyli** [comment]
Closing since I've taken over the debian package now.
