### ISSUE TITLE
[debian] Please allow to compile with packaged libs

### ISSUE THREAD

**Issue by bastien-roucaries** [HaxeFoundation/haxe#2894]
We have package a few library under libs for debian.

We wish to use them for compiling haxe. Could be possible to add flags to compile with system one ?

It is a medium term goal

**Comment by waneck** [comment]
Summoning @ncannasse because I think he knows best what's the state of our library dependencies. As far as I know, we have made some changes on the libraries, which make our version incompatible. Am I right?

**Comment by ncannasse** [comment]
yes, most of the libraries are either ours (specific to haxe) or quite modified ones. @bastien-roucaries tell us if there's a specific lib you would like to reuse.
