### ISSUE TITLE
Method inherited from generic class is not generated

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#2902]
Consider this code

    package bbb;
    
    @:generic
    class G<T> {
    	public var t:T;
    	public function new(){}
    
    	public function f():Int{
    		trace("f");
    		return 1;
    	}
    }
    
    class G1 extends G<Int> {
    	public function new(){
    		super();
    		t = 1;
    		trace("G1");
    		trace(this.f);
    	}
    }
    
    class T {
    	public var g1:G1;
    
    	public function new (){
    		g1 = new G1();
    	}
    }
    
    class G2 extends G<T> {
    	public function new(){
    		super();
    		t = new T();
    		trace("G2");
    		trace(this.f);
    	}
    }
    
    class Main {
    	public static function main(){
    		var g2 = new G2();
    	}
    }

Compile it with `haxe -D dump=pretty -cp src -main bbb.Main -dce no -neko a.n`
Output:

    Main.hx:18: G1
    Main.hx:19: null
    Main.hx:35: G2
    Main.hx:36: #function:0

And in dump

    class bbb.G_Int{
        public new(method) : Void -> Void

         = function() = {
        };

        public t(var) : Int;

        public f(method) : Void -> Int;

    }

But if i comment `trace("f");` in G\<T\> i'll get

    Main.hx:18: G1
    Main.hx:19: #function:0
    Main.hx:35: G2
    Main.hx:36: #function:0

and

        public f(method) : Void -> Int

         = function() = {
                return 1;
        };

**Comment by Simn** [comment]
I have had an on-and-off relationship with this issue, but I still didn't manage to address it. At least I managed to reduce the example:

```
@:generic
class G<T> {
    public function f(){
		haxe.Log;
	}
}

class G2 extends G<String> { }

class G1 extends G<Int> { }

class Main {
    public static function main() { }
}
```

**Comment by ncannasse** [comment]
Sorry I've been pretty busy in the past months so I just recently got time to come back to haxe issues.

Related to the passes design : when you're in the PBuildClass pass, you're allowed to access module types (since the we are sure all depedency modules are built) but you're not allow to access their structure (because you're still at class building and you might have other classes building themselves on the stack).

That means that in theory we should NOT call type_function while we're still in PBuildClass. I guess @:generic needs to defer some of its field building with TLazy

**Comment by ncannasse** [comment]
I propose that in build_generic, we return immediately a typedef bound to a TLazy that will actually build the generic class.

**Comment by Simn** [comment]
I'm not sure if that helps because we end up at `check_extends` via `set_heritance` too early which does `follow t`.

**Comment by ncannasse** [comment]
Right, I understand better now. The problem here is that we should not start typing G before we have finished building G2 and G1. But there's still a design issue because imagine for a moment that we access G1 in G code...

Anyway, we should first make all generic fields TLazy, that's for sure.
