### ISSUE TITLE
[python] structure literal creates None fields for inexistant optional field

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2928]
An example is worth a thousand words:

``` haxe
var r:{?a:Int} = {};
```

translates to

``` python
r = _hx_c._hx_AnonObject({'a': None})
```

This is wrong IMO because it breaks `Reflect.hasField` and `Reflect.fields` and is not consistent with other targets.

**Comment by ncannasse** [comment]
@Simn: it means that we only take into account the optional flag of the structure fields when it's unified with a literal structure (a_status = Const). The reason is quite simple: if we only have a type, we can't be sure that there's not an hidden field with the same name.

Example:

```haxe
var a = { v : "hello" };
var b : {} = a; // hide v
var c : { ?v : Int } = b; // if it was allowed
trace(c.v); // typed as Int, but actually a String !
```
