### ISSUE TITLE
C#: net-lib enum problem

### ISSUE THREAD

**Issue by AxGord** [HaxeFoundation/haxe#2931]
<pre>
switch KeyCode.A {
	case KeyCode.A: trace('A');
	case KeyCode.K: trace('K');
	case _:
}
</pre>
Output:
<pre>
Main.hx:28: K
</pre>

**Comment by waneck** [comment]
I've put some thought into this, and I guess it is better to change so all -net-lib enums are actually `@:enum abstract`, and perhaps change so haxe enums are never compiled as C# enums.
There are still some annoying problems with `@:enum abstract` - for example that it doesn't support Int64 as its underlying type. This could be solved nicely with Int64 literals.

I'm a little reluctant about this anyway as it's potentially a breaking change - if anyone is depending on `Type.enum*` methods for native enums, or if anyone's depending on how Haxe generates its enums on the C# side.

cc @nadako
