### ISSUE TITLE
abstract enum: duplicate values should be dissallowed

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#2940]
this compiles without error, but in my opinion it shouldn't.

``` haxe
@:enum abstract Foo(Int) {
  var A = 2;
  var B = 2;
}

class Test {

  static function main ()  {

    var a = Foo.A;
  }
}
```

**Comment by RealyUniqueName** [comment]
This is the source of errors, which could be caught at compile time.

```haxe
@:enum abstract Wtf(Int) {
  var First = 1;
  var Second = 1;
}

class Test {
  static function main() {    
    var v = [First, Second][Std.random(2)];
    switch(v) {
        case First: 
        	trace('hello');
        case Second: 			
        	trace('world'); //never happens
    }    
  }
}
```

Let's think about this one more time.
Maybe introduce some meta to make developer to explicitly declare enum values which are intended to be the same.
I'm reopening it to get some attention. Feel free to re-close if necessary )

**Comment by Simn** [comment]
I still don't think we should do anything here, especially now that you can use implicit numbering.

Do compilers of other languages that have enums complain about duplicate values?

**Comment by RealyUniqueName** [comment]
C# complains on a `case`:
```cs
using System;
					
public class Program
{
	enum Wtf { First=1, Second=1 }
	
	public static void Main()
	{
		switch(Wtf.First) {
			case Wtf.First: Console.WriteLine("hello");
			case Wtf.Second: Console.WriteLine("World");
		}
	}
}
```
```
Compilation error (line 11, col 9): The label 'case 1:' already occurs in this switch statement
```

**Comment by Simn** [comment]
Complaining on the case is fine, but Haxe already does that as well, right?

**Comment by RealyUniqueName** [comment]
Nope

**Comment by RealyUniqueName** [comment]
Oh, Haxe emits a warning:
```
Test.hx:12: lines 12-13 : Warning : This case is unused
```
Ok, maybe that's enough

**Comment by Simn** [comment]
![code_2018-12-04_14-02-03](https://user-images.githubusercontent.com/634365/49443617-3dae7580-f7cd-11e8-8a45-e72c12331d44.png)
