### ISSUE TITLE
Spods: wrong relation id field type generated. it forces relation ids to be signed Int. But it should allow SUId and SBigId ids.

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#2965]
Hi,
The Spod relation system don't support SUId and SBigId as ids.
If i have a DBParent Spod class
and a DBChild Spod class

my DBChild has the following id field:
public var id:SUId;

and my DBParent has following relation:
    @:relation(childid) public var child: DBChild;

The macro Spod system will generate a childid of type SInt instead of SUInt.
Thats bad!

You can also get an unjustified compile error if you add to DBParent class an explicit declaration of childid field like that:
public var childid:SUId;
it will throw "Relation key should be SInt" ...

Its related to RecordMacros.hx file in function getRecordInfos. 
in the loop:
		// create fields for undeclared relations keys :
		for( r in i.relations ) {
the field is created with: t : DInt
and if field is declared it throw an error with:
if( f.t != DInt ) error("Relation key should be SInt", pos);

For the same reason, it will also make use of SBigId id for relations impossible.

Thanks
Seb

**Comment by waneck** [comment]
Closed by #2970
