### ISSUE TITLE
Java-style csv-list of interfaces to implement

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#2972]
Implementing several interfaces quickly becomes very verbose on Haxe:

```haxe
class Test implements A implements B implements C implements D {}
```

It would be nice if the following was also allowed - much more readable while not losing any information:

```haxe
class Test implements A, B, C {}
```

Considering from Haxe 2 -> 3 there was a [change](https://github.com/HaxeFoundation/HaxeManual/blob/master/md/manual/types-interfaces.md#trivia-implements-syntax) to make `implements` more similar to Java, this seems like a sensible request.

**Comment by RealyUniqueName** [comment]
It's time to think again )
