### ISSUE TITLE
[display] @position support for type hints

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2996]
```haxe
class Main {
    var a:String;

    static function main() {
        var a:Float;
    }
}
```

for field: `haxe --display Main.hx@30@position`
for local: `haxe --display Main.hx@81@position`

I don't know if it's the same for struct definitions.

**Comment by nadako** [comment]
i'll reassign it back to you then. feel free to return it when it's working properly :)

**Comment by Simn** [comment]
I can't actually find a failing case for this, so I'll consider this fixed. Feel free to reopen with a failing example.
