### ISSUE TITLE
[display] @position support for @:enum abstract constants

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#2997]
```haxe
@:enum abstract MyEnum(Int) {
    var A = 1;
    var B = 2;
    var C = 3;
}

class Main {
    static function main() {
        var a = A;
        var b = MyEnum.B;
    }
}
```

`haxe --display Main.hx@138@position`
`haxe --display Main.hx@164@position`

**Comment by Simn** [comment]
I suppose the compilation server argument can be used against adding metadata as well. So yeah I don't really see a way to fix this.

**Comment by Simn** [comment]
There's really only two options here:

1. don't inline in display mode (at least in the file we want completion for)
2. insert some metadata when inlining in display mode

In the general case there is no way to retrieve an inlined value. It might even be ambiguous (multiple "constructors" with the same value).
