### ISSUE TITLE
Regression discussion with pattern matching

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3054]
Ok, we have added the "null" as a missing check in pattern matching, but maybe that's not a good idea for the top level value.

Example of regression:

```haxe
var myValue : Null<MyEnum> = ...;
if( myValue == null ) return;
switch( myValue ) {
case A:
case B:
case C:
}
```

This will now complain that `null` is not matched.

I think it's still useful to have it for sub values, only the top level should be ignored (and yes I'm sure @Simn will not like it )

**Comment by Simn** [comment]
I want to break this, anyone disagree?

**Comment by Simn** [comment]
Never mind, this is too much of a mess.
