### ISSUE TITLE
Bytes support

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3073]
- make sure we use typed Arrays in JS, and emulate it on IE8
- allow to get a view of a sub part of the Bytes similar to JS typed arrays
- we need both DataView http://api.haxe.org/js/html/DataView.html and all the [U][Int|Float|Double][8|16|32]Array types

**Comment by ncannasse** [comment]
I'm making progress on this, will soon make a PR.
A few notes of things to do:

 - review haxe.io.BytesBuffer (should use FPHelper for instance)
 - regarding endianness : JS typed arrays are hardware dependent, and we can't change that. Only DataView as explicit endianness access, but I expect it to be slower that using Float32Array. Also, in some cases (GL buffers), native endianness is required (BE on ARM, LE on x86). I think we should have hardware endianness for static platforms as well (C++,C#,Java,etc.). Other platforms can choose between LE or hardware-specific endianness depending on their restrictions.

**Comment by ncannasse** [comment]
I made some changes today: added subarray for JS compatibility, added fromBytes to create a typed array from a low level buffer. Please review the API and ask if you need something else or if you want something to be renamed. Once confirmed I'll implement the remaining typed arrays.

CC @waneck @hughsando

**Comment by ncannasse** [comment]
Seems like my latest typed arrays additions are making cpp segfault, @hughsando could you look into it?

**Comment by hughsando** [comment]
This was a fault in hxcpp - should be fixed.

**Comment by Simn** [comment]
Moving to 3.3, we keep track of the currently known issues in #4032 and #4018.
