### ISSUE TITLE
Storing a library interface as a binary repr

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3076]
The compiler could store a library as a binary format but only the public fields without the actual implementation. This would enable to reuse a library without recompiling it, given you make sure to "link" it somehow in your compilation process.

Linking is a platform specific behavior. For instance for JS that means loading the lib js and then exposing it so it can be accessed.

**Comment by Simn** [comment]
This is not really an actionable issue, so I'll go ahead and close it.
