### ISSUE TITLE
cs: adding listeners to an event doesn't work if obj is declared as Dynamic 

### ISSUE THREAD

**Issue by npretto** [HaxeFoundation/haxe#3078]
```
var watcher:Dynamic watcher = new FileSystemWatcher();
watcher.add_Changed(myFunc);
```
Doesn't work, while
```
var watcher:FileSystemWatcher watcher = new FileSystemWatcher();
watcher.add_Changed(myFunc);
```
works

**Comment by waneck** [comment]
I'm afraid this cannot be fixed. There is some compile-time magic that needs to be made to make a Haxe function behave like a delegate. This is neither easy to achieve on the runtime, nor IMHO desirable - as it would need some dynamic code generation, which impossible on some C# targets (e.g. iOs, Xbox, Compact Framework)
