### ISSUE TITLE
[python] consider usage of __slots__

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3080]
From https://docs.python.org/3.1/reference/datamodel.html#slots:

> By default, instances of classes have a dictionary for attribute storage. This wastes space for objects having very few instance variables. The space consumption can become acute when creating large numbers of instances.
> The default can be overridden by defining `__slots__` in a class definition. The `__slots__` declaration takes a sequence of instance variables and reserves just enough space in each instance to hold a value for each variable. Space is saved because `__dict__` is not created for each instance.

This sounds like a nice thing for at least haxe enums, however even with them there are two approaches here:
 * a simple one: use `__slots__` to specify `tag`, `index` and `params` and be done with it.
 * a hard, but probably better memory and performance wise one: rework enum generation so it generates a class with `__slots__` for each constructor with arguments, so every enum value takes only the place it needs to hold its constructor arguments.

We may also want to consider usage of `__slots__` for non-Dynamic classes.

**Comment by nadako** [comment]
I added simple `__slots__` generation and unit tests seem to pass. Things to keep in mind and TODOs:

 * we need to add `"__weakref__"` to slots for weak references to work, but we must only add that if there's no such slot in base classes or python will complain.
 * right now, having a dynamic method cancels generation of `__slots__` because python will complain if method's name is both in `__slots__` and class definition (is there something we can do with this, @frabbit?)
 * generating `__slots__` for classes that have base classes with `__dict__` (or no `__slots__`) has no effect (but no harm as well).

**Comment by frabbit** [comment]
@nadako i guess you are the slots expert, i have no experience with them at all.

**Comment by nadako** [comment]
Let's close this and work on specific issues that may come up eventually.
