### ISSUE TITLE
Doc parsing - Typedef comments not parsed on members declared a certain way

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#3083]
When comments are included for documentation on members declared in the less formal method, their comment is not parsed and does not end up being exported in the -xml.

Note how the first test comments do not exist, while the ones in the second test do.

```
    /** Root level Test1. This comment will exist */
typedef Test1 = {
        /** test one (this comment will not exist) */
    ? a: Int,
        /** test other (this comment will not exist either) */
    b: Int
}

    /** Root level Test2. This comment will exist */
typedef Test2 = {
        /** test two (this comment will exist) */
    var a: Int;
}
```

**Comment by Gama11** [comment]
Hm, this is an unfortunate limitation...

**Comment by Simn** [comment]
Coming back to this I don't see what parser issues I came across. If we address #4655 we might as well fix this issue too.

**Comment by Simn** [comment]
Now I remember... Parsing the anonymous structure might actually raise `Stream.Failure`. In other words, we don't know what kind of structural notation we're parsing until after the documentation and metadata has been processed. This then skips metadata in some cases, which means we unfortunately cannot support this after all.
