### ISSUE TITLE
Haxe Exception: This mutex isn't owned by the current thread!

### ISSUE THREAD

**Issue by michelkaeser** [HaxeFoundation/haxe#3084]
This might be the correct place for it: https://github.com/HaxeFoundation/hxjava/issues/7 - Sorry.

**Comment by Simn** [comment]
See comment on https://github.com/HaxeFoundation/haxe/commit/52e71b94f758bf5e2624af1e1b32e3edf2b93f5d#commitcomment-16332305

**Comment by Simn** [comment]
#4878
