### ISSUE TITLE
Allow arbitrary type parameters on @:genericBuild types

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#3089]
Is there any reason why the type parameters must at all be declared beforehand?

Ideally, we could have types like `Or<A, B, ..., X>` or `And<A, B, ..., X>` or `Minus<T, A, B, ..., C>` etc.

Would it make sense to discuss an alternative syntax for `@:genericBuild` (which does seem a little awkward to put it mildly) or would I just be wasting everyone's time? ;)

**Comment by PDeveloper** [comment]
Would there be a way to pass generic parameters on to a superclass?

(For example, would it be possible to extend that Tuple implementation?)
