### ISSUE TITLE
Context unavailable in Context.onMacroContextReused?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#3130]
It seems that a lot of things cannot be done in `onMacroContextReused`, including:
- `error` (is like returning false)
- `warning` (no effect)
- `onTypeNotFound` (seems completely ignored)

Interrestingly `getType` works relatively well.

**Comment by Simn** [comment]
Is this still an issue?

**Comment by ncannasse** [comment]
Closing due to lack of answer.
