### ISSUE TITLE
haxejava:  Map < String, NativeArray<String> > resolves to Map<java.lang.String, java.lang.Object[]>

### ISSUE THREAD

**Issue by royag** [HaxeFoundation/haxe#3161]
Using haxe 3.1.3 with hxjava 3.1.0

Consider this program:

package ;
import java.util.Map;
import java.NativeArray;
class StringArrayTest
{
	public static function main() {
		var f : Map < String, NativeArray<String> > ;
	}
}

The resulting main-method in the generated java-source is:

	public static   void main()
	{
		java.util.Map<java.lang.String, java.lang.Object[]> f = null;
	}

The expected result should be:

	public static   void main()
	{
		java.util.Map<java.lang.String, java.lang.String[]> f = null;
	}

When trying to assign an actual java-native Map&lt;String,String[]&gt; to this variable (like the one returned from HttpServletRequest.getParameterMap()) this results in a compilation-error as Map&lt;String,String[]&gt; is not castable to Map&lt;String,Object[]&gt;

**Comment by waneck** [comment]
Seems like this is fixed already
