### ISSUE TITLE
-main doesn't support specifying classes inside modules

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3167]
Subj. It looks like it only supports specifying a class named after its module, with or without a package, but not a class inside a module.

``` haxe
class Main {
    static function main() {
    }
}
```

`haxe -main Main.Main`

Gives

```
Error: Could not process argument Main.Main
Invalid class name
```

**Comment by kaikoga** [comment]
Hi, I've found that it fails when you have a file named ```Foo.hx``` with

```haxe
class Bar {
    static function main() {
    }
}
```

and do ```haxe -main Foo.Bar```, which gives you a different message :)

```
Error: Could not process argument Foo.Bar
Package name must start with a lower case character
```
