### ISSUE TITLE
[macro] structure extension information is not available after typing

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3198]
Typer currently seems to generate a new `TAnonymous` for a `TExtend`, merging its fields and losing information about extended types. However, I find that info useful sometimes and would love to see it available somehow (maybe as metadata or AnonStatus param). For example:

In our game we have type definitions for game content JSON structures like that:

``` haxe
typedef MapItemDef = {
    name:String
}

typedef DragonDef = {
    >MapItemDef,
    elements:Int
}
```

What I want to do is macro-generate some C# classes for the Unity3D client that wraps those structures and I want to preserve inheritance hierarchy for those classes:

``` cs
class MapItemDef {
    public readonly string Name;

    public MapItemDef(JSValue o) {
        Name = o["name"].AsString;
    }
}

class DragonDef : MapItemDef {
    public readonly int Elements;

    public DragonDef (JSValue o) : base(o) {
        Elements = o["elements"].AsInt;
    }
}
```

**Comment by Simn** [comment]
Maybe this helps:

```haxe
typedef X = {
    x: Int
}

typedef Xy = {
    x: Int,
    y: String
}

class Main {
    static function main() { }

    static function opened(a) {
        // a is a monomorph here
        // field access turns it into an open anon
        a.x = 12;
        a.y = "foo";
        // note the +
        $type(a); // {+ y : String, x : Int }

        // unify with closed anon Xy
        var a2:Xy = a;
        // a is closed now
        $type(a); // { y : String, x : Int }

        // cannot add any more fields
        a.z = true;

        // can assign to less specific anon
        var a3:X = a;
    }

    static function const() {
        var a = { x: 12, y: "foo" };
        // a is const here, prints the same
        $type(a); // { y : String, x : Int }

        // unifies with closed, remains const
        var a2:Xy = a;

        // does not unify with less specific anon
        var a3:X = a;
    }
}
```

Open and closed status is quite straightforward: Open anons are only relevant when accessing fields on monomorphs. They allow additional fields to be added. Upon unification they are closed, which means they do not accept any more fields.

Const status is more peculiar and I can never remember why it exists in the first place, although it always makes sense when Nicolas explains it (again). It is relevant when working with structure declarations and as far as I can tell the distinguishing feature is that they do not unify with less specific anon types.

For your case I'd say the new status should be treated just ilke Closed.
