### ISSUE TITLE
Should not rename extern fields

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3229]
From a question posted in the group: https://groups.google.com/forum/?hl=en#!topic/haxelang/G54xtEznveQ

The following
```haxe
extern class Test {
  static function length():Void;
}

class Main {
  static function main():Void {
    Test.length();
  }
}
```
is being compiled to:
```js
(function () { "use strict";
var Main = function() { };
Main.main = function() {
 Test.$length();
};
Main.main();
})();
```

Notice `Test.length()` -> `Test.$length()`.

Renaming field is good for haxe implemented class but the class specified by extern is not implemented in haxe.

**Comment by Simn** [comment]
This makes sense to me. My guess is that the vast majority of externs are not for Haxe-generated types, so having a metadata to switch is good. I would prefer one with a less obscure name though...
