### ISSUE TITLE
DCE/Features and Compiler Cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3231]
While working on CastleDB (http://github.com/ncannasse/castle) I noticed that the JS output was changing depending on the compiler cache usage.

After two compilations with compiler cache, the ``$estr`` for enum.toString disappear (as if the feature was disabled) and the IMap class appear (while it was not in the original output).

There's also the `@:initPackage` in JQuery which is playing hide and seek.

**Comment by Simn** [comment]
I'm assuming this is a duplicate of #3508.

**Comment by ncannasse** [comment]
Might be not. Seems feature-related, whereas we fixed local variable names.
