### ISSUE TITLE
`@:forward` does not forward static members

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#3254]
The following code:
```haxe
class Main
{
  static function main()
  {
    AData.test();
  }
}

class Data
{
  public static function test()
  {
  }
}

@:forward abstract AData(Data)
{
}
```

fails with
```
Main.hx:5: characters 2-12 : AData has no field test
```

The same happens with properties and fields.

**Comment by waneck** [comment]
This seems to still not work:
```haxe
class Main
{
	static function main()
	{
		trace(Test.a);
	}
}

@:forward abstract Test(Underlying)
{
}

class Underlying
{
	public static var a(get,never):Int;
	private static function get_a()
	{
		return 10;
	}
}
```

**Comment by waneck** [comment]
Oh nevermind. I didn't realize it wasn't on upstream yet

**Comment by Simn** [comment]
Yeah I don't like it very much, but we can talk about it after 3.2.

**Comment by waneck** [comment]
I'd be grateful if this could get into 3.2 though. I plan to release a library right after 3.2 which would need this.

**Comment by waneck** [comment]
Also note that `@:forward` doesn't work with constructors as well. See #3987

**Comment by Simn** [comment]
It shouldn't, abstract constructors have wildly different semantics than normal ones.

**Comment by frabbit** [comment]
When we support this, it should be a separate feature like @:forwardStatic.

**Comment by ibilon** [comment]
I'd also like this to be added, almost same use case as @waneck: using it to support operator overloading on underlying class.

Except the underlying class in my case is an extern with function overloading so I can't just put an inline static function in the abstract proxying the underlying class' function.

@frabbit's suggestion is fine if we don't want to mess with the existing `@:forward`
