### ISSUE TITLE
Regexp feature coverage

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3257]
While we mostly use PCRE, some features might or might not be present depending on the target platform (thinking about Unicode matching for instance). We should unit test a good amount of PCRE features in order to add a feature chart into the Haxe documentation.

Another option is to find out exactly which Regexp library is used on each platform, then redirect to the platform documentation.

PS : Let's forget about testing EReg in macros for now, it's too much restricted and will be replaced by PCRE.

**Comment by Simn** [comment]
Moved to https://github.com/HaxeFoundation/HaxeManual/issues/164
