### ISSUE TITLE
`Context.defineModule` cannot create two modules that reference each other

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#3262]
I used to regester a `Context.onTypeNotFound` before some `Context.defineType` calls. This way resolves references in these macro-generated classes.

But I am not able to do the same thing if I want to create some multi-class modules.

Could you change `Context.onTypeNotFound` to `public static function onTypeNotFound(handler:String->Array<TypeDefinition>):Void`?

**Comment by Atry** [comment]
This API is still unable to create two **modules**(not type) that reference each other.

**Comment by ncannasse** [comment]
@Atry you can still define one module and then another which typedef the other, that would lead to the same types being available to the end-user
