### ISSUE TITLE
[display] no way to distinguish method from a function variable in --display field completion

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3287]
Subj. When a method has at least one argument, we can distinguish by checking if the argument has a name, but it's completely impossbile for Void->Void cases, i.e.:

``` haxe
class A {
    public static var a:Void->Void;
    public static function b():Void {};
}
```

gives

```
<i n="a"><t>Void -&gt; Void</t><d></d></i>
<i n="b"><t>Void -&gt; Void</t><d></d></i>
```

I propose adding a "k" attribute with values "method" / "var" or something, similar to how toplevel completion is done. And while we're there, i think access modifiers such as "dynamic" should be also somehow presented in --display output for IDEs.

**Comment by Simn** [comment]
We have added `--display { jsonrpc }`, so now you can get all the information you want.
