### ISSUE TITLE
-java-lib path/to/classes does not work anymore

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3296]
I was using `-java-lib path/to/classes` some weeks ago, and today I found it doesn't work anymore.
The directory structure of `path/to/classes` is:
```
-classes
  -net
    -onthewings
      -bezelgestures
        -R.class
        -R$id.class
        -R$layout.class
```

The haxe compiler complained as soon as I imported one of the classes: `import net.onthewings.bezelgestures.R;`

It works if I manually build `R` into a jar and use it with `-java-lib`.

**Comment by Simn** [comment]
I added a regression label because I see "anymore" in the title. Make sure to check before 3.2.

**Comment by waneck** [comment]
Is this working for you, @andyli ?

**Comment by waneck** [comment]
I'll consider it done. Feel free to reopen if it's not working.
