### ISSUE TITLE
[proposal] Array.contains - a method to check if element present in the array

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3323]
It's quite a common need to check if an array contains an element and it's a shame we don't have a function for that. Even tho we now have `indexOf`, checking index against `-1` looks stupid and is not error-proof. Also, performance-wise, a simple `contains` method can be faster, as it doesn't need to handle negative indices and stuff.

So I suggest adding `Array.contains` method to check whether an element present in the array by standard equality. It should be a nice complement to the `Array.remove` method we already have.

I was thinking of naming it `exists`, similar to `Map`, but then it will conflict with existing `using Lambda` code, so I think `contains` is a good alternative.

@Simn @ncannasse what do you think? I could implement that (with unit-tests of course).

**Comment by Atry** [comment]
I think we can change functions in `Lambda` to macros, to enable inline for the `it` parameter.

```haxe
class Lambda {
    @:extern private inline static function typing<A:Iterable<Dynamic>>(it:A):A return it;

    macro public static function has<A>( it : ExprOf<Iterable<A>>, elt : ExprOf<A> ) : ExprOf<Bool> return macro {
        var it = Lambda.typing($it);
        var result = false;
        for( x in it )
            if( x == $elt ) {
                result = true;
                break;
            }
        result;
    }
}
```

**Comment by nadako** [comment]
I don't know. We have `remove` already that doesn't require any `using` directives. However we could add it to standard usings similar to `EnumTools`.

**Comment by nadako** [comment]
Maybe we could even move `remove` to that extension class even.

**Comment by Simn** [comment]
That would also nicely hide the problems of issue #3330. Static extensions are already known to only work on known types.

**Comment by nadako** [comment]
See #3776

**Comment by nadako** [comment]
Note that, there's a ECMAScript proposal for this, but the name is `includes`. Maybe we should comply. See https://github.com/tc39/Array.prototype.includes

**Comment by explorigin** [comment]
Slightly off-topic but related...for the same reasons that Array.contains would be nice...so would String.contains().

**Comment by nadako** [comment]
I would still love to have this method instead of `indexOf` testing, but these questions still stand:

* Method name. ES7 will have it by the name `includes` - do we want to comply with that or not? I personally like `contains` or `has` (see https://github.com/HaxeFoundation/haxe/issues/3323#issuecomment-54731659) much more and I think we can just add `@:native("includes")`, when ES7 becomes reality.
* Implementation. If we implement it like we do for `remove` and `copy`, it'll have problems with Dynamic described in #3330, but apparently that's okay with @ncannasse (and honestly with me too). We can work that around though, using a solution @Simn proposed in #3330 (was it ever merged into development? because I think Python utilizes something like that).

**Comment by ncannasse** [comment]
Should it not be just an inline for  indexOf(v) >= 0 ?

**Comment by nadako** [comment]
Probably yeah (however there may be more efficient ways, need to benchmark that).

**Comment by Simn** [comment]
The #3330 stuff was never addressed. I'm not very happy about "use Dynamic at your own risk" because it is used very selectively (I have to pull all kinds of stunts in the pattern matcher to support Dynamic crap).

**Comment by nadako** [comment]
Hmmm, I wonder then what's that `@:runtime` meta means in Python Array implementation: https://github.com/HaxeFoundation/haxe/blob/ae6349cccff2149afade4babedefc90f3e5baa43/std/python/_std/Array.hx#L107

**Comment by Simn** [comment]
That's to allow structural sub-typing. Otherwise the compiler would yell at you because it assumes the inline field cannot be accessed at run-time.

**Comment by nadako** [comment]
But what's the point in allowing that if it's not supported by the target anyway?

**Comment by nadako** [comment]
Oh, I see, python supports that by checking hard-coded fields in Reflect.field and using proper ArrayImpl methods that are kept with `@:ifFeature("dynamic_read.map", "anon_optional_read.map")`, so I guess it's partially there after all.

**Comment by nadako** [comment]
I think tho that it wouldn't be good to go through complex reflection when working with structures in JS like that. Boy we need to review the whole Dynamic stuff for future versions.

**Comment by Simn** [comment]
Well, my approach in #3330 only affects fields which are actually defined in HxOverrides. But yes I realize that I value consistency differently than you guys do.

**Comment by back2dos** [comment]
Since we have DateTools and StringTools, how about ArrayTools? It seems
that recently there was an increasing desire to add more and more methods
to Array. If we move it to a static extension, then we can ignore all kinds
of Dynamic issues.

**Comment by Simn** [comment]
See #3776

**Comment by back2dos** [comment]
Oh, sorry, I missed that. As it was rejected, I'll assume this is as good a place as any for further comments.

I think adding it to global using is actually not such a good idea. It's just the kind of stuff that will make newcomers trip and then go rant about how awful and obscure Haxe is. I would make ArrayTools consistent with StringTools and DateTools. No magic. High visibility, since it's in the top-level (although I don't feel strongly about that). And then everyone can use it at their own peril.

**Comment by Simn** [comment]
I share that opinion, but ArrayTools was rejected in general.

**Comment by back2dos** [comment]
Experience has taught me that no rejection is general, not even when it comes from Nicolas :D

**Comment by nadako** [comment]
My opinion hasn't really changed - I'm fine with ArrayTools in general, but I would be annoyed to add `using ArrayTools` or write `ArrayTools.has(a, elem)` just for that one method. However, when #1138 will be hopefully addressed, that becomes a non-issue for me.

**Comment by Simn** [comment]
The nice thing about static extensions is that we don't have to explain whether or not `Dynamic` is supported: It is already implied that it's not supported. If we add this to global using that argument can't really be made because the fact that it's implemented like that is just an implementation detail.

**Comment by nadako** [comment]
Yeah, I understand that and can agree to the argument against global using, but for those who know what are they doing and generally avoid Dynamic (like me), it would be very handy to be able not to add `using` everywhere, that's why I really would like to see #1138 implemented.

**Comment by nadako** [comment]
So... What's our official position on extending Array at this point?

**Comment by Justinfront** [comment]
I was wondering is it not easy enough to just create your own Abstract and add what you need, what are the main drawbacks apart from not really having any clue where to put the T's, it may seem simple but in practice it can be tricky to get right.
```haxe
// untested, less T's maybe needed!
@:forward
abstract ArrayMore<T>( Array<T> ) from Array<T> to Array<T> {
    inline public function new<T>( ?v: Array<T> ) {
        if( v == null ) v = getEmpty<T>();
        this = v;
    }
    public inline static 
    function getEmpty<T>(){
        return new ArrayMore<T>( new Array<T>() );
    }
    public inline
    function has<T>( val: T ){
          return this.indexOf(v) >= 0
    }
}

```
I am sure there are drawbacks I was just wondering if abstract would be good enough for most use, also I wanted to ask about creating empty abstract arrays... since I remembered optionals were not in favour.

**Comment by RealyUniqueName** [comment]
Maybe it's time to revive this since `Array.resize()` looks like it's going to be a thing.

**Comment by ncannasse** [comment]
I would like to see that added, maybe @bendmorris wants to help with it as well?

**Comment by nadako** [comment]
Ehm, I could do it years ago if someone answered my original questions in https://github.com/HaxeFoundation/haxe/issues/3323#issuecomment-160639754

**Comment by ncannasse** [comment]
@nadako "contains" is good, and not supporting Dynamic is good too since we already do so for some other methods.

**Comment by nadako** [comment]
I'm getting a weird error on Flash: 
```
ReferenceError: Error #1069: Property http://adobe.com/AS3/2006/builtin::contains not found on Array and there is no default value. in unit.TestSpecification.testArray_unit_hx
```

The `builtin::contains` suggests that the name `contains` might have some magical meaning for the AVM and we can't use it, but I'm not sure about that. Any Flash expert here? :)

**Comment by nadako** [comment]
nevermind, i forget the special handling in genswf9
