### ISSUE TITLE
[js] array.copy() / insert() / remove() fails on Dynamic - "undefined is not a function"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#3330]
```haxe
class Test {
    static function main() {
        var array:Dynamic = [1,2,3];
        trace(array.copy()); // Uncaught TypeError: undefined is not a function
    }
}
```

The same happens with `insert()` and `remove()` - all other fields seem to work fine.

Of course this is easy to work around if it is indeed a target limitation, but I thought I'd report.

**Comment by Simn** [comment]
Since nobody likes this approach the only way I see is to document this as not being supported after all.

**Comment by nadako** [comment]
I think the idea is nice, but I doubt we should invest time on supporting this. I like the "use Dynamic at your own risk" principle.

**Comment by ncannasse** [comment]
Let's keep it as a "Dynamic at your own risk". Because even if we patch for Dynamic, we will have similar issues for Reflect.field, or accessing the array from JS, etc.
