### ISSUE TITLE
[cs] completion server seems not to cache types from a .DLL

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3350]
As we talked on IRC, C# types seem not to be cached by compilation server so they are parsed again from DLL therefore slowing down compilation and (more importantly) completion.

Main.hx

``` haxe
class Main {
    static function main() {
    }
}
```

`haxe -v --wait 6000`
`haxe --connect 6000 -main Main -cs cs`
`haxe --connect 6000 -main Main -cs cs`

Here's a compilation server log WITHOUT `-D net_loader_debug`: https://gist.githubusercontent.com/nadako/d5c5fa9064bc19eacaa6/raw/without_net_loader_debug

Here's a compilation server log WITH `-D net_loader_debug`: https://gist.githubusercontent.com/nadako/d5c5fa9064bc19eacaa6/raw/with_net_loader_debug

**Comment by nadako** [comment]
Note that with current haxe `development` version, C# can't be compiled from a compilation server twice:
```
D:\Code\haxe\std/cs/internal/HxObject.hx:80: lines 80-84 : Types that derive from a native class must have its super() call as the first statement in the constructor
D:\Code\haxe\std/cs/_std/Array.hx:56: lines 56-60 : Warning : Type Array.T_c is being cast to the unrelated type Array<Array.T_c>
D:\Code\haxe\std/cs/_std/Array.hx:56: lines 56-60 : Warning : This expression may be invalid
D:\Code\haxe\std/cs/_std/Array.hx:466: lines 466-471 : Warning : Type _Array.ArrayIterator.T_c is being cast to the unrelated type _Array.ArrayIterator<_Array.ArrayIterator.T_c>
D:\Code\haxe\std/cs/_std/Array.hx:466: lines 466-471 : Warning : Type _Array.ArrayIterator<_Array.ArrayIterator.T_c> is being cast to the unrelated type Array<_Array.ArrayIterator.T_c>
D:\Code\haxe\std/cs/_std/Array.hx:466: lines 466-471 : Warning : This expression may be invalid
D:\Code\haxe\std/cs/internal/HxObject.hx:40: lines 40-64 : Warning : No overload found for this constructor call
File "gencommon.ml", line 6445, characters 13-19: Assertion failed
```

**Comment by ncannasse** [comment]
Might be related to the fact that we cache extern types now:
https://github.com/HaxeFoundation/haxe/commit/f27a3c1e12852c6909e6b68dbb20c20bc6b44c6f

**Comment by waneck** [comment]
Yeah. I've been working on a fix at a local branch. I'll fix it soon - and
also add some completion server tests.

E.g. compile the unit tests, touch a file and compile again, and compare
the outputs.

**Comment by kLabz** [comment]
Is this supposed to be solved?

I am using latest dev and I have slow compilation (and completion) on a project with `-net-lib`s and compilation server.

I get a lot of `A file is masking the library file X` + ` 1, cs: skipping X` without `-D net_loader_debug`.

I also get ` 1, cs: Cached 1392 modules` but the cache does not seem to be used since I get exactly the same compilation time when compiling a second time (and only 0.2sec faster than without any compilation server).

**Comment by waneck** [comment]
Sounds like this got broken again

**Comment by Simn** [comment]
I think we can close this.
