### ISSUE TITLE
[cs] no way to generate events

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3357]
It would be great if we were able to generate `event Action<T> Changed` from the following (or something like that):

```haxe
@:nativeGen
interface ChangeDispatcher<T>
{
    @:event
    var Changed:cs.system.Action_1<T>;
}
```

**Comment by nadako** [comment]
I wonder if we could make `@:event` simply generate the "event" keyword in the output for now. We still can express `if (myEventDelegate != null) myEventDelegate.Invoke(data)` in haxe, and that's enough for my case of interop.

**Comment by waneck** [comment]
The only problem I see is that there will be no way to access the event (add/remove) from Haxe if we do it like that. Or will it?

**Comment by nadako** [comment]
Yeah that's the problem, but I want to ignore it for now.

**Comment by waneck** [comment]
I've just realized that we have the `+=` op for delegates. The only thing that would be missing is the private/public checks, but I guess we could add this later in the typer itself?

**Comment by nadako** [comment]
But currently, `-net-lib` events generate `add_/remove_` methods in haxe. I thought we want to be consistent and somehow add these methods to the haxe-generated events.

**Comment by waneck** [comment]
Yeah... I hate events :(
Seems like a macro would be the only way to allow it on Haxe

**Comment by nadako** [comment]
we could also hack typer and support something like e.g.:

```haxe
class A {
    @:event public var Action<Int> MyEvent;
    
    // these methods are required (checked similar to property get/set methods)
    // no body - default implementation, some body - override implementation
    public function add_MyEvent(cb:Action<Int>):Void;
    public function remove_MyEvent(cb:Action<Int>):Void;
}
```

generated (default impl):
```cs
class A {
    public event Action<Int> MyEvent;
}
```

generated (override impl), similar to `@:property`:
```cs
class A {
    public event Action<Int> MyEvent {
        add { _add_MyEvent(value) };
        remove { _remove_MyEvent(value) };
    }
}
```

tho that would require adding target-specific stuff to general code, but i don't see another way.

**Comment by waneck** [comment]
If you can convince @ncannasse  / @Simn about it, I'd be fine with implementing this

**Comment by waneck** [comment]
By the way, I think the best place to put this would be at typeload.ml

**Comment by nadako** [comment]
I'll check how much damage this thing can do to our codebase :-P
