### ISSUE TITLE
Compile error with inline @:op

### ISSUE THREAD

**Issue by cbatson** [HaxeFoundation/haxe#3370]
Given:

	import haxe.Int64;
	abstract FunInt64(Int64)
	{
		public static var NEGATIVE_ONE(default, null) : FunInt64 = FunInt64.make(0xffffffff, 0xffffffff);
		public static var ZERO(default, null) : FunInt64 = FunInt64.make(0x00000000, 0x00000000);
		
		public static inline function make(high : Int, low : Int) : FunInt64
		{
			return new FunInt64(Int64.make(high, low));
		}

		@:op(A>>B) public static inline function shrs_i(j : FunInt64, k : Int) 
		{
			if (k >= 63)
			{
				return (Int64.getHigh(j) < 0) ? NEGATIVE_ONE : ZERO;
			}
			return new FunInt64(Int64.shr(j, k));
		}
			
		public inline function new(a : Int64) : Int64
		{
			this = a;
		}
		
		@:to public inline function toInt64()
		{
			return this;
		}
	}

And later:

	var val64 : FunInt64 = FunInt64.make(0, 1);
	val64 = val64 >> 1;

You will get the error:

	Main.hx:107: characters 9-19 : haxe.Int64 should be FunInt64

Note, if you remove `inline` from the definition of `shrs_i` the error goes away.

The above code compiles with the release Haxe 3.1.3, but not the latest.

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/b2167ae7ccc4b921b2b42a8f52ee93a1db7751c8

**Comment by cbatson** [comment]
Fantastic work, thank you Simon! And with a test, to boot. :-)
