### ISSUE TITLE
[cs] redundant TCast added

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3379]
while working at making cs output nicer i noticed that there are a lot of redundant casts added presumably by `gencommon` filters, but I couldn't find where they come from, so maybe @waneck could point me at it

example code:

``` haxe
class Main {
    function new(a:Int) {}
    static function main() {
        new Main(10);
    }
}
```

gives

``` cs
public static void main() {
    unchecked {
        new global::haxe.root.Main(((int) (10) ));
    }
}
```

the `((int) (10) )` cast is redundant

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
