### ISSUE TITLE
Inconsistent Sys.command behaviour on Windows

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3402]
Subj.

Create an executable with spaces in it, e.g. `with spaces.bat`:
```bat
@echo hello
```

The following will fail (run with `haxe --run Main`):
```haxe
class Main {
    static function main() {
        Sys.command("with spaces.bat");
    }
}
```

The following will run okay:
```haxe
class Main {
    static function main() {
        Sys.command("with spaces.bat", []);
    }
}
```

The following will fail (escaped arg):
```haxe
class Main {
    static function main() {
        Sys.command("with spaces.bat", ["*"]);
    }
}
```

The error is `"with" is not recognized as an internal or external command`.

(probably related to 22b7e226ef91eed4e82fb52f382771b2e921eda5, @ncannasse could you check?)

**Comment by nadako** [comment]
I think we need to prepare some tests for that. I'll get to it when I have time.

**Comment by nadako** [comment]
there's something wrong with argument escaping on cpp/windows:

```
ERR: TestSys.hx:7(TestSys.testArgs) - expected 'a b  %PATH% $HOME c\&<>["]#{}|%$' but was 'a b  %PATH% $HOME c\&<>[]#{}|%$'
```
(note the missing `"`)

**Comment by andyli** [comment]
I will add tests for commands with spaces tonight (haven't done yet).

**Comment by andyli** [comment]
I've added tests in [TestSys](https://github.com/HaxeFoundation/haxe/blob/00346ff7af76820feb1fee8788a8ab961884a6ef/tests/sys/src/TestSys.hx#L41) and [TestProcess](https://github.com/HaxeFoundation/haxe/blob/00346ff7af76820feb1fee8788a8ab961884a6ef/tests/sys/src/io/TestProcess.hx#L47).

The file name test cases are defined in [FileNames](https://github.com/HaxeFoundation/haxe/blob/00346ff7af76820feb1fee8788a8ab961884a6ef/tests/sys/src/FileNames.hx).Two cases are commented out:
 1. Non-English file name, which I think we should support.
 2. File name that is as long as a system is allowed. Not sure we want to support this extreme case. Feel free to reduce that length.

**Comment by andyli** [comment]
let's handle this in #3603
