### ISSUE TITLE
No way to @:allow() root package

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#3404]
Because the root package has no name, there is no way to @:allow() it, which would be analogous to 'internal' for the root package other languages like as3, c#. Potential solutions are @:allow("") or naming the root namespace to something which is normally implied in a dotted name such as `__ROOT__` (which might have other uses as well)

**Comment by yar3333** [comment]
I know, what reference to root package doing by "std" package name. For example:
```haxe
package mypack;
class StringTools // you want to define your own StringTools
{
    public static function trim(s) return std.StringTools(s); // call StringTools.trim() from root package
}
```
So, may be a good solution to implement @:allow("std")?
