### ISSUE TITLE
inconsistent Sys.command behaviour across neko,java,python target

### ISSUE THREAD

**Issue by zaxebo1** [HaxeFoundation/haxe#3411]
i am running latest build of haxe from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux32/haxe_2014-09-16_development_5391c45.tar.gz on ubuntu 12.04 LTS

==========

CASE1:
Now,
when I compile 
 Sys.command( "ls -la");    //an external OS command with argument "-la" in the first parameter itself. 

Then this command runs perfectly on Neko target and Php target, but fails at runtime in java, python runtime. 

=============
==========

CASE2:
Now,
when I compile 
 Sys.command( "/bin/ls",["-la"]);    //an external OS command with argument "-la" in the second parameter 

Then this command runs perfectly on Neko target and Php and python target, but does not execute  at runtime in java.

=============================
=============================

Error log:
in case i , the python throws error log at runtime as:

Traceback (most recent call last):
  File "out1/python/out2python.py", line 1279, in <module>
    Test21.main()
  File "out1/python/out2python.py", line 1105, in main
    Sys.command("ls -la")
  File "out1/python/out2python.py", line 1094, in command
    return python_lib_Subprocess.call(args1)
  File "/usr/lib/python3.2/subprocess.py", line 471, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python3.2/subprocess.py", line 745, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.2/subprocess.py", line 1361, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 2] No such file or directory: 'ls -la'

---------------------------

NOTE: the inconsistency:
Even if "ls -la" fails to execute in hxpython , then it should fail in neko,php too. OR, If it passes in neko ,php,then it should pass in python too by implementation of Sys.command() of haxe  AS os.system() of python

**Comment by andyli** [comment]
Will be handled in #3603
