### ISSUE TITLE
[js] support creating extern classes by calling a constructor function without "new" keyword

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3441]
See https://github.com/HaxeFoundation/haxe/issues/2784#issuecomment-57943535

It seems that it's quite common in JS libraries that objects are created by simply calling a function instead of using "new SomeConstructor" syntax (e.g. `JQuery`, `express`, `socket.io`), so I think it makes sense for us to support that.

The most straightforward way is probably to use metadata for the constructor field that simply makes JS generator omit the `new` keyword, i.e.
```haxe
extern Express {
    @:noNew // we need a better name for it
    function new();
}
```

But I don't really know to what extent is it compatible with e.g. `Type.createInstance`. @aduros, @clemos, @eduardo-costa any comments?

**Comment by clemos** [comment]
I was checking [LuaXe](https://github.com/PeyTy/LuaXe), which has support for this feature (`@nonew`, through a custom generator...), 
and was wondering if it was possible to simply generate something like that using a macro : 
```haxe
public inline function new( arg ) {
   return untyped __js__('MyClass')( arg );
}
```

**Comment by nadako** [comment]
okay, now genjs supports `@:selfCall` for both fields and constructor which allows one to generate stuff like:
```haxe
@:jsRequire("myapp")
extern class MyApp {
    @:selfCall function new();
    @:selfCall function run():Void;
}

class Main {
    static function main() {
        var app = new MyApp();
        app.run();
    }
}
```

generates:
```js
(function () { "use strict";
var MyApp = require("myapp");
var Main = function() { };
Main.main = function() {
	var app = MyApp();
	app();
};
Main.main();
})();
```

@clemos @frabbit or anyone who is working on externs please confirm that it's good enough.
