### ISSUE TITLE
Property specifier which allows writing only from constructor

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3442]
This was brought up and rejected before, but this time I have a better understanding of the benefits and would like to present it again. The idea is to have a property specifier such as `new` which allows writing a field from a class constructor but nowhere else.

What's nice about this is that we can infer field immutability from it, which allows us to e.g. propagate constants even if an object leaves context. Consider this piece of code:

```
class MyVector {
    public var x(default, null):Float;
    public var y(default, null):Float;

    public inline function new(x:Float, y:Float) {
        this.x = x;
        this.y = y;
    }
}

class Main {
    static function main() {
        var vec = new MyVector(12, 13);
        leave(vec);
        use(vec.x, vec.y);
    }

    static function leave(vec:MyVector) { }
    static inline function use(x:Float, y:Float) {
        return x + y;
    }
}
```

The call to `leave(vec)` cancels constructor inlining. Now if both `x` and `y` were defined to be writable-only-from-constructor, we could still use their values and optimize the `use(vec.x, vec.y)` call to plain `25`.

**Comment by ncannasse** [comment]
Hi Dan
3) is not really easy to do : how would you do that in JS for instance ?
4) feasible but very efficient if no native Ref support (will require to allocate a reference, copy the members from local to reference, then copy them back to locals afterwards). Also, for languages that supports native references, we need to forbid them from being stored in member variables since the value might not exists after we return from the function
5) yes, I guess that will be necessary, will require some alloc/copy similar to (4)
6+7) could maybe be done with abstracts if we add support for a `destructor` method (for (7) you could have your abstracts do the heap management)

**Comment by Atry** [comment]
I think implementing an explicit type `ByValue<T>` would be easier than `@:struct` class.

```
package haxe;
@:coreType abstrace ByValue<ReferenceClass>
{
  @:to public function pack():ReferenceClass;
  @:from public static function unpack<ReferenceClass>(reference:ReferenceClass):ByValue<ReferenceClass>;
}
```

```
// Usage

class Sample
{

  public static function main()
  {
    // Explicitly pack and unpack
    var c = new MyClass(100, 50);
    var u = haxe.ByValue.unpack(c);
    var p = u.pack();

    // Implicitly unpack
    var v:ByValue<MyClass> = new MyClass(200, 100);

    trace(v.sub());
    trace(v.optimizedAdd());
  }

  static function optimizedDiv(v:ByValue<MyClass>)
  {
    return v.i / v.j;
  }

}

class MyClass
{
  public var i:Int;
  public var j:Int;

  public function inline new(i:Int, j:Int)
  {
    this.i = i;
    this.j = j;
  }

  public function sub():Int
  {
    $type(this); // MyClass
    return i - j;
  }

  @:thisByValue public function optimizedAdd():Int
  {
    $type(this); // ByValue<MyClass>
    return i + j;
  }

}

```

Will compile to:

```
class Sample
{

  public static function main()
  {
    // Explicitly pack and unpack
    var c = new MyClass(100, 50);
    var u_i:Int = c.i;
    var u_j:Int = c.j;
    var p:MyClass = {
      var temp:MyClass = new MyClass();
      temp.i = u_i;
      temp.j = u_j;
      temp;
    }

    // Implicitly unpack
    var v_i:Int = 200;
    var v_j:Int = 100;
    trace({
      var temp:MyClass = new MyClass();
      temp.i = v_i;
      temp.j = v_j;
      temp;
    }.sub())
    trace(MyClass.optimizedAdd(v_i, v_j));
  }

  static function optimizedDiv(v_i:Int, v_j:Int)
  {
    return v_i / v_j;
  }

}

class MyClass
{
  var i:Int;
  var j:Int;

  public function inline new(i:Int, j:Int)
  {
    this.i = i;
    this.j = j;
  }

  public function sub():Int
  {
    return i - j;
  }

  public static function optimizedAdd(this_i:Int, this_j:Int):Int
  {
    return this_i + this_j;
  }

}

```

**Comment by Atry** [comment]
When invoking a `ByValue<T>`'s instance method, a temporary instance `T` will be created, except the method is an inline method or a `@:thisByValue` method.

**Comment by Simn** [comment]
We have `final` now.
