### ISSUE TITLE
Make generic constant type parameters available

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#3450]
Consider [the following code](http://try.haxe.org/#fF28C)

```
class Test {
    static function main() {
        var x = new X<'foo'>();
        trace(Type.getClassName(Type.getClass(x)));//traces X_Sfoo
    }
}

@:generic class X<Const> {
    public function new() {
//         trace(Const);
    }
}
```

Trying to compile the trace statements fails saying this:

> Type parameter Const is only available at compilation and is not a runtime value

Is there any chance to make the parameter available at runtime (which it basically is if you jump through some hoops)? Could the same be accomplished for function type parameters?

**Comment by Simn** [comment]
I checked this today and while it's not terribly hard to implement, there are some design issues. The main problem I see is that we allow multiple "Const" type parameters and it's not clear what should happen if you then use `Const` as a value.

My suggestion is to wait for #3836 so we can do something like `class C<@:const T>`. We can then get rid of the whole "Const" convention and address this issue properly.

**Comment by nadako** [comment]
Sounds very clean!

**Comment by back2dos** [comment]
This is awesome!

**Comment by sledorze** [comment]
Wonderful!
