### ISSUE TITLE
DOMWindow.frames doesn't return an Array of frames

### ISSUE THREAD

**Issue by JbIPS** [HaxeFoundation/haxe#3468]
Given Haxe API, [DOMWindow](http://api.haxe.org//js/html/DOMWindow.html) frames should
 > Returns an array of the subframes in the current window.

which would be coherent with [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/Window.frames).

But instead, it's returning a DOMWindow, so I couldn't use Array access and I'm not sure of what it's actually returning.

Bug or specification interpretation?

Thanks.

**Comment by Simn** [comment]
done?

**Comment by aduros** [comment]
Fixed in new externs.
