### ISSUE TITLE
[java] feature request " -java-lib-extern "

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#3469]
Feature request for linking **"external"** (or "runtime"?) JARs who have not to be copied to build-dir/lib/ and not be mentioned in `manifest`.

Imho, it must be similar to `-swf-lib-extern`.

**Comment by garrett-hopper** [comment]
@Simn, is that `--native-lib-extern` in a released version?

**Comment by RealyUniqueName** [comment]
@Jumblemuddle Not yet. See https://github.com/HaxeFoundation/haxe/issues/7450#issuecomment-520124340
