### ISSUE TITLE
[cs] net-lib, multiple interface inheritance and property access specifiers

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3474]
Example stripped from MonoDevelop code.

Compile the following C# into a DLL:
```cs
public interface ITextFile
{
    string Property { get; }
}

public interface ITextBuffer : ITextFile
{
}

public interface IEditableTextFile : ITextFile
{
    new string Property { get; set; }
}

public interface IEditableTextBuffer : ITextBuffer, IEditableTextFile
{
}
```

Now try to use that in Haxe:
```haxe
class Main {
    static function main() {
        var a:IEditableTextBuffer;
    }
}
```

The error:
`Issue.dll @ IEditableTextBuffer:1: character 0 : Field Property has different property access than in IEditableTextFile ((get,never) should be (get,set))`

**Comment by waneck** [comment]
Thanks for the great test case!
