### ISSUE TITLE
Arrays of mixed types restriction and haxe.EitherType

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3499]
Consider the following code (real-world extern case - [expressjs](http://expressjs.com/4x/api.html#app.use)):
```haxe
typedef PathSimple = haxe.EitherType<String,js.RegExp>;
typedef Path = haxe.EitherType<PathSimple,Array<PathSimple>>;

class Main {
    static function main() {
        var a:Path = ["", new js.RegExp("")];
    }
}
```
That gives the error:
```
Main.hx:6: characters 26-43 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
Main.hx:6: characters 26-43 : js.RegExp should be String
```
Probably related to (if not the same as) #3494

**Comment by Simn** [comment]
@ncannasse: Do you have an opinion on this? The problem is that you currently cannot assign a dynamic array to `EitherType<Something, Array<Dynamic>>`. It's not clear to me if top-down inference should explore the `from` relations of the expected abstract type.

**Comment by ncannasse** [comment]
@Simn the problem with such exploration is that could lead to several possible conversions with different side effects, leading to painful error message (because we don't want to choose one of them).  Well, if it's only "from" and not "@:from" methods, it's ok since there's no side effect.

**Comment by Simn** [comment]
It can still be ambiguous because there could be multiple `from Array<X>`.

**Comment by Simn** [comment]
Let's hold back on this. A few `Array<Dynamic>` in the externs are not going to kill anyone and I would like to give this some more thought.
