### ISSUE TITLE
Instability in code output with compiler cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3508]
I had some guesses about it while working in JS, but working in C++ confirmed it : we have a significant amount of instability with our code output due to more or less recent changes.

What I mean by "instability" is that depending either in the compilation order or the usage of compilation server (which also changes compilation order), we will get a different output for the same code base.

Here's an example, the method `setAlpha` of `h2d.Drawable`, is declared as:

```
inline function set_alpha(v) {
	return color.a = v;
}
```

Color is an h3d.Vector, and the `a` component is a mapping to `w` (see https://github.com/ncannasse/heaps/blob/master/h3d/Vector.hx)

A compilation to C++ gave me the following output:

```
Float Drawable_obj::set_alpha( Float v){
	HX_STACK_FRAME("h2d.Drawable","set_alpha",0x2a19a8a5,"h2d.Drawable.set_alpha","h2d/Drawable.hx",83,0xa05adb4b)
	HX_STACK_THIS(this)
	HX_STACK_ARG(v,"v")
	HX_STACK_LINE(84)
	Float _g2;		HX_STACK_VAR(_g2,"_g2");
	HX_STACK_LINE(84)
	{
		HX_STACK_LINE(84)
		::h3d::Vector _g = this->color;		HX_STACK_VAR(_g,"_g");
		HX_STACK_LINE(84)
		Float _g1 = _g->w = v;		HX_STACK_VAR(_g1,"_g1");
		HX_STACK_LINE(84)
		Float _g3 = _g1;		HX_STACK_VAR(_g3,"_g3");
		HX_STACK_LINE(84)
		_g2 = _g3;
	}
	HX_STACK_LINE(84)
	return _g2;
}
```

And another one this one:

```
Float Drawable_obj::set_alpha( Float v){
	HX_STACK_FRAME("h2d.Drawable","set_alpha",0x2a19a8a5,"h2d.Drawable.set_alpha","h2d/Drawable.hx",83,0xa05adb4b)
	HX_STACK_THIS(this)
	HX_STACK_ARG(v,"v")
	HX_STACK_LINE(84)
	::h3d::Vector _g = this->color;		HX_STACK_VAR(_g,"_g");
	HX_STACK_LINE(84)
	Float _g1 = _g->w = v;		HX_STACK_VAR(_g1,"_g1");
	HX_STACK_LINE(84)
	return _g1;
}
```

Both are correct, but they have different code output. It is particularly important for platforms such as C++ to have a high stability since changing even a local variable name will mean recompiling the whole file.

Assigning to @Simn since this is something important to fix before 3.2 release.

**Comment by Simn** [comment]
So is this resolved now?

**Comment by ncannasse** [comment]
I will check again asap

**Comment by ncannasse** [comment]
All is good for CDB, I didn't check again for CPP but I think we did the job.
