### ISSUE TITLE
haxe.macro.ClassType needs an equals function

### ISSUE THREAD

**Issue by theor** [HaxeFoundation/haxe#3515]
Because at the moment:

    var t = Context.getType("Tabc");
    trace(t.getClass() == t.getClass()); // "false";

**Comment by Simn** [comment]
I just implemented that but I'm not sure if it's actually useful. In my macros I always immediately get rid of Ref types so I have trouble imagining cases where I could even use an equals function.

I think we should just accept the fact that physical equality on the Haxe-side is undefined for anything that comes out of the various Context functions.

**Comment by back2dos** [comment]
FWIW this has never bothered me.

**Comment by Simn** [comment]
I see no reason to act here so let's leave this alone.
