### ISSUE TITLE
[cs] generate type parameter constraints

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3526]
Subj. (i.e. `class A<T> where T : B`)

**Comment by waneck** [comment]
See #3817

**Comment by nadako** [comment]
this will be hidden behind a custom meta for 3.2 because it needs a little deeper thought (see #4002)

**Comment by kLabz** [comment]
Thanks for the fix with the meta!
Are we supposed to continue using it, or is there plans for another fix? If the meta is kept, maybe it should appear in `haxe --help-metas`.

**Comment by kLabz** [comment]
Added support for `class`, `struct`, `new()` and `unmanaged` constraints in #8311

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
