### ISSUE TITLE
Allow enum constructor recognition for abstracts.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#3528]
I had kind of hoped [this commit](https://github.com/HaxeFoundation/haxe/commit/e8715189fc055220f2f33a06c5e1331c96310a88) did the trick already, but it doesn't seem so.

Would it be possible for abstracts over enums to work the same in regards to constructors as enums do? Here is some code that I would like to see compile:

```
class Test {
    static function main() {
        trace("Haxe is great!");
        var x = test1(Some(4));
        test2(x);
        
        switch x {
           case Some(v):
           default:
        }
        
        //this could be allowed to work if a direct `from` is supported
        test2(Some(4));
        //this could be allowed to work if a direct `to` is supported
        switch test2(x) {
           case Some(v):
           default:
        }
    }
    static function test1(v:haxe.ds.Option<Int>) {
        return v;
    }
    static function test2(v:Optional<Int>) {
        return v;
    }
}

abstract Optional<T>(haxe.ds.Option<T>) from haxe.ds.Option<T> to haxe.ds.Option<T> {}
```

**Comment by Simn** [comment]
I'll add this, but there's one thing to note: The `to` has no effect here because of how we handle the pattern. We type it (`Some(v)`) against the subject type which is `Optional<Int>`. This is actually the same case as `test2(Some(4))` and is going to work for the same reason.
