### ISSUE TITLE
Object with inline constructor does not get inlined within custom iterator

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#3535]
Testcase: http://try.haxe.org/#6D0dE
Expected : no instance or anything related to IndexItemObject in generated output.
What happens : within the loop, the object does not get inlined, but when using it outside the iterator it does get inlined.

I found out it doesnt matter if the object is generic type or not.

Maybe its already fixed in the latest builds, but it would be neat if this works.

**Comment by Simn** [comment]
Dammit, I accidentally fixed this locally so it inlines... which means the behavior is wrong now.

**Comment by Simn** [comment]
PSA: I'll commit my fix for constructor inlining which is going to break this example. I'll make sure to find a solution for this before the next release, but I don't want to hold back on this otherwise very useful change.

**Comment by Simn** [comment]
This has been fixed!

**Comment by markknol** [comment]
Boom! Nice
