### ISSUE TITLE
Abstract iterator

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#3539]
Compiler does not recognize abstract types as iterators:

``` haxe
class Test {
    static function main() {
        for (i in (10 : To100)) {
            trace(i);     
        }
    }
}

abstract To100(Int) from Int {
    public inline function new(start:Int) this = start;
    public inline function hasNext() : Bool return this < 100;
    public inline function next() : Int {
        var next = this;
        this = this + 1;
        return this;
    }
}
```

result:

```
Test.hx:3: characters 18-30 : To100 has no field iterator
```

http://try.haxe.org/#8b305

**Comment by YellowAfterlife** [comment]
@soywiz: You can make an inline `forEach` function. As long as it does not contain excessive variable declarations, it will be inlined. Example: http://try.haxe.org/#7a96F

The sad truth about the for-loops with iterators here is that while they are cool and are advertised as an excellent replacement for C-style for-loops, they are merely small garbage generation machines, and in the end you just have to use while-loops everywhere.
