### ISSUE TITLE
null `cpp.Pointer` on debug mode is not null

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#3540]
The folowing code:
```haxe
		var ptr:cpp.Pointer<cpp.UInt8> = null;
		trace(ptr); // some pointer address
		trace(ptr == null); //false
```
Traces a pointer address when compiled in debug mode. In release mode however, it works correctly

**Comment by hughsando** [comment]
The default constructor should initialize to 0 now.
