### ISSUE TITLE
-swf-lib fails with "corrupted" message for any swf with non-visible movieclips

### ISSUE THREAD

**Issue by modjke** [HaxeFoundation/haxe#3549]
Any swf or swc with non-visible symbols (movieclips) (Properties tab, "Visible" checkbox is off, Flash CS6 or CS5 i guess...) will be rejected by haxe compiler with message "The swf ... file is corrupted".
Faulty swf + fla here
https://dl.dropboxusercontent.com/u/5632042/faulty.swf
https://dl.dropboxusercontent.com/u/5632042/faulty.fla

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
