### ISSUE TITLE
haxe.Http cannot retrieve multiple Set-Cookie headers

### ISSUE THREAD

**Issue by royag** [HaxeFoundation/haxe#3550]
Since the Http.responseHeaders is a StringMap, then if the server sends multiple headers with the same name, all but the last one are abandoned.

This is especially relevant in case the server sends multiple "Set-Cookie"-headers.

Even if one don't change the responseHeader-API as it is now, perhaps one at least should keep the entire header-list in some other variable (like "allResponseHeaders" or something) so that at least they are not completely abandoned.

**Comment by vbence** [comment]
Any chance this can be re-prioritized to get a hotfix? It is a pretty breaking issue. The current API can be deprecated later of course.

**Comment by Simn** [comment]
Not really, but you can easily patch this yourself if you urgently need it. That way you could also send a pull request with your changes.

**Comment by Simn** [comment]
This has been addressed in the haxe.Http rework.

**Comment by back2dos** [comment]
It has been addressed for request headers, not for response headers. On most platforms these just aren't available and on `sys` it's still a [`Map<String, String>`](https://github.com/HaxeFoundation/haxe/blob/development/std/sys/Http.hx#L30).
