### ISSUE TITLE
[neko] Bug with Std.string(float)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#3552]
```haxe
	var f:Float = 65536;
	trace((f * f) == 4294967296);  // false
	trace(Std.string(f * f));      // 0
```

This works as expected instead:
```haxe
	var f:Float = 65536.0;
	trace((f * f) == 4294967296);  // true
	trace(Std.string(f * f));      // 4294967296
```

(haxe 3.1.3, neko 2.0.0)

**Comment by ncannasse** [comment]
@Simn : I'm not planning to fix it, we need to document this as part of the overflows. Neko overflow does not depend on the Haxe type but on the actual value. If it's an operation between two int values, the overflow will be on 32 bits.

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/HaxeManual/issues/83
