### ISSUE TITLE
generating xml doc for WeakMap fails in C#

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#3555]
On the latest dev version when trying to generate doc for WeakMap I get the following error:

```
/usr/local/lib/haxe/std/cs/_std/haxe/ds/WeakMap.hx:28: lines 28-537 : Module haxe.Constraints does not define type IMap
```

**Comment by ashes999** [comment]
I'm also getting this with Haxe 3.1.3 on Linux when trying to build the Linux version of my app.

**Comment by Simn** [comment]
That's quite unlikely because the file doesn't even exist in 3.1.3.

**Comment by ashes999** [comment]
@Simn here's what I have in `/usr/lib/haxe/std/cpp/_std/haxe/ds/WeakMap.hx`: http://paste.ubuntu.com/10309504/

I installed Haxe 3.1.3 using the haxe.org installer.

**Comment by Simn** [comment]
1. That's a cpp file, not C# as originally reported here.
2. There is no 3.1.3 linux installer an haxe.org and the linux 32/64 binaries don't have that file.
