### ISSUE TITLE
Better hidding "Either"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3601]
I was about to rename "haxe.EitherType" to "haxe.Either", but I thought we might want not to have it in the "haxe" package since it's quite not typesafe and we don't want to encourage its usage.

Any suggestion ?

**Comment by Simn** [comment]
I'll move both Rest and EitherType to an extern package. Perhaps we can even enforce that they only appear in extern classes.

**Comment by Simn** [comment]
Or I don't do that because `extern` is a keyword.

**Comment by nadako** [comment]
Could it be allowed for package names similar to `macro`?

**Comment by Simn** [comment]
It could but I don't think that's worth it for a new package.

**Comment by Simn** [comment]
I'll allow "extern" as package name. All other suggestions we discussed were worse.

**Comment by waneck** [comment]
Why not "externs" ? `haxe.externs`

**Comment by Simn** [comment]
Because people would expect to find a collection of externs there.

**Comment by waneck** [comment]
Hmmm that's right
