### ISSUE TITLE
python Date.getTime() runtime error

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3604]
#2556 revealed a python bug. Back in the time the PR is made, the python unit test has not been enabled, that's why Travis was green for that PR but failed after it was merged.

Here is a reduced example.
Using latest haxe, python 3.4.1 on OSX.

```haxe
class Test {
    static function main() {
        var d = Date.now();
        trace(d.getTime());
    }
}
```
error msg:
```
Traceback (most recent call last):
  File "Test.py", line 1181, in <module>
    Test.main()
  File "Test.py", line 971, in main
    haxe_Log.trace(Date.datetimeTimestamp(d.date),_hx_AnonObject({'fileName': "Test.hx", 'lineNumber': 4, 'className': "Test", 'methodName': "main"}))
  File "Test.py", line 908, in datetimeTimestamp
    return (((dt - dt2) * 1000) / timedelta)
TypeError: can't subtract offset-naive and offset-aware datetimes
Error: Command failed with error 1
```

When fixing, please make sure the timestamp matches with other targets (at least close to). It can be checked easily with the following hxml:
```
-python Test.py
-main Test
-cmd python3 Test.py

--next 
-main Test
--interp
```

**Comment by Simn** [comment]
ping @frabbit

**Comment by nadako** [comment]
could you please look into it? i'm quite rusty with python nowadays.
