### ISSUE TITLE
File "genjs.ml", line 363, characters 13-19: Assertion failed

### ISSUE THREAD

**Issue by zhulu-mike** [HaxeFoundation/haxe#3607]
i compile a openfl project on target html5. what may be caused the problem?
if neccesasery, i can provide the code source

**Comment by sebpatu** [comment]
hi i ran into the same error.
with the env param i get trace:
     [exec] Fatal error: exception Assert_failure("genjs.ml", 363, 13)
     [exec] Raised at file "genjs.ml", line 363, characters 13-25
     [exec] Called from file "genjs.ml", line 282, characters 2-5
     [exec] Called from file "genjs.ml", line 465, characters 2-35
     [exec] Called from file "genjs.ml", line 761, characters 2-16
     [exec] Called from file "list.ml", line 73, characters 12-15
     [exec] Called from file "genjs.ml", line 542, characters 2-38
     [exec] Called from file "genjs.ml", line 551, characters 2-39
     [exec] Called from file "genjs.ml", line 950, characters 2-17
     [exec] Called from file "list.ml", line 73, characters 12-15
     [exec] Called from file "genjs.ml", line 1025, characters 2-100
     [exec] Called from file "list.ml", line 73, characters 12-15
     [exec] Called from file "genjs.ml", line 1267, characters 1-40
     [exec] Called from file "main.ml", line 1433, characters 3-21
     [exec] Called from file "main.ml", line 597, characters 3-11
     [exec] Called from file "main.ml", line 1577, characters 1-35

**Comment by sebpatu** [comment]
i found out why it did not compile, but i dont see how to reproduce....
see like: http://try.haxe.org/#71bB2

i used super.indexOf() and the function did not exist in the super class.
if i test on try haxe, or on a simple file compilation on my computer (so with same haxe verion), i get proper error.

good luck ;)

**Comment by sebpatu** [comment]
ok me again, i found something:
i had using Lamba on top of the file !!! 
now in try haxe and local simple file, compiler won't complain (which is not good anyway) but no error.

i think that as it don't complain for basic stuff, theres an internal unconsistent state, that may put the compiler in bad shape whith more complicated code.

now it gets more sens :) i think its easier to look at now :)

**Comment by nadako** [comment]
`super` vs static extensions:
```haxe
using Main.Tools;

class Tools {
    public static function f(b:Base) {}
}

class Base {}

class Child extends Base {
    function a() {
        super.f();
    }
}
```
on latest haxe:
```
Fatal error: exception Assert_failure("genjs.ml", 357, 13)
Raised at file "genjs.ml", line 357, characters 13-25
Called from file "genjs.ml", line 461, characters 2-35
Called from file "genjs.ml", line 775, characters 2-16
Called from file "list.ml", line 73, characters 12-15
Called from file "genjs.ml", line 546, characters 2-38
Called from file "genjs.ml", line 555, characters 2-39
Called from file "genjs.ml", line 964, characters 2-17
Called from file "list.ml", line 73, characters 12-15
Called from file "genjs.ml", line 1045, characters 2-100
Called from file "list.ml", line 73, characters 12-15
Called from file "genjs.ml", line 1340, characters 1-40
Called from file "main.ml", line 1563, characters 3-21
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1752, characters 1-35
```

**Comment by nadako** [comment]
It's not js-specific, as it generates invalid code on e.g. c#
```cs
global::Tools.f(base);
```
