### ISSUE TITLE
--interp fileInput.eof() bug

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3611]
The following is part of sys test, but simplified.
I discover that while trying to run the sys test for macro target.

```haxe
import sys.io.*;

class Test {
    static function main():Void {
        File.saveContent('testcase-test-file', "test\n1234");
        var file = File.read('testcase-test-file', false);
        file.seek(9, FileSeek.SeekCur);
        trace(file.eof()); //true, should be false
    }
}
```

Following will run the above code in neko and --interp, printing different results:
```
-main Test
-neko Test.n
-cmd neko Test.n

--next 
-main Test
--interp
```

**Comment by ncannasse** [comment]
Seems like the way we implemented file_eof in Interp is different than in Neko. Looking again at the `feof` documentation, it seems that it only returns true if we tried to read past the file end, not if we *just* reached it, which makes it actually quite useless imho.

**Comment by ncannasse** [comment]
Maybe removing .eof() entirely would be better. @Simn let's deprecate it for 3.2

**Comment by Simn** [comment]
I don't think we should deprecate it. It works consistently on all sys targets except our macro interpreter.

We can fix this by wrapping `in_channel`, e.g. as `AFRead of (in_channel * bool ref)`, then just set the reference to true when we get a read beyond eof from either `file_read_char` or `file_read`.

Any problems with that?

**Comment by ncannasse** [comment]
@Simn ok for me

**Comment by Simn** [comment]
@andyli: This should work now, please close this issue after confirming.

**Comment by andyli** [comment]
Confirm :)
