### ISSUE TITLE
[flash] generated enum need to be cast to string for haxe to compile

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxe#3621]
I get the following error when passing a enum like Context3DBlendFactor.ONE (which is actually a string in Flash API)
src/Main.hx:286: characters 8-81 : flash.display3D.Context3DBlendFactor should be String
src/Main.hx:286: characters 8-81 : For function argument 'value'

if I cast it, the compiler do not complain anymore and it run fine but this should not be necessary

if I use Context3DBlendFactor.ONE.getName() the compiler do not complain but I get a runtime error :
Property tag not found on String and there is no default value.
	at Type$/enumConstructor()[C:\HaxeToolkit\haxe\std/flash/_std/Type.hx:265]

any idea?

Note: tested on the latest haxe build from 25/11

**Comment by Simn** [comment]
@nadako: Can you confirm that `@:fakeEnum` is obsolete now that we have `@:enum extern abstract`?

**Comment by nadako** [comment]
I think so, it works and allows unqualified access and stuff. Though if we change flash externs from `@:fakeEnum extern enum` to `@:enum extern abstract`, it'll break macros, but as usual, I think it's for the greater good.

**Comment by Simn** [comment]
I don't want to change this right now, I just want to justify not paying any attention to `@:fakeEnum`.

**Comment by nadako** [comment]
Hmm, there's something wrong with exhaustiveness check there, unless I'm misunderstanding something again:

```haxe
@:native("lol")
@:enum extern abstract E(String) {
    var A;
    var B;
    var C;
}

class Main {
    static var a:E;
    static function main() {
        switch (a) {
            case A: trace("hello");
            case B: trace("yo");
        }
    }
}
```

**Comment by Simn** [comment]
I'll check it out.

**Comment by Simn** [comment]
The problem is that we don't know any values so it's not really possible to reason about exhaustiveness statically. I guess we could make sure all fields are matched, but that requires some internal changes.
