### ISSUE TITLE
js.html.Element matches HTMLElement interface and should match Element interface

### ISSUE THREAD

**Issue by flash42** [HaxeFoundation/haxe#3644]
In practice this means that js.html.svg.SVGElement has all the goodies what HTMLElement has so it will throw runtime exceptions potentially as it implements js.html.Element interface.
On the other hand there is no js.html.HTMLElement which is a pity as no-one is pointing to the native HTMLElement.

MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Element
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement

**Comment by Simn** [comment]
done?

**Comment by aduros** [comment]
Fixed in new externs.
