### ISSUE TITLE
Socket's accept() returns broken Socket in Java

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#3647]
.\HaxeToolkit\haxe\std\java_std\sys\net\Socket.hx's accept function fails to set the output and input properties of the newly created socket, so accepted socket's are unusable.  The function should look like this:

	public function accept() : Socket
	{
		var ret = try server.accept() catch(e:Dynamic) throw e;

		var s = new Socket();
		s.sock = ret;
		try
		{
		   s.output = new java.io.NativeOutput(ret.getOutputStream());
		   s.input = new java.io.NativeInput(ret.getInputStream());
		}
		catch(e:Dynamic) throw e;

		return s;
	}

**Comment by waneck** [comment]
Closed by 334dc343e946f4b2a70ec705a403af564c5d488e
