### ISSUE TITLE
Socket's peer() function always causes an exception in Java

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#3648]
.\HaxeToolkit\haxe\std\java_std\sys\net\Socket.hx's peer() function crashes with an failed cast from Inet4Address to InetSocketAddress.  Fixing this and any resulting issues results in a function that looks like this:

	public function peer() : { host : Host, port : Int }
	{
		var rem:java.net.InetAddress = cast sock.getInetAddress();
		if (rem == null) return null;

		var host = new Host(null);
		host.wrapped = rem;
		return { host: host, port: sock.getPort() };
	}

**Comment by waneck** [comment]
Closed by 334dc343e946f4b2a70ec705a403af564c5d488e
