### ISSUE TITLE
[php] wrong code generation for getters if type is function

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#3650]
```haxe
class Main {
    var cb (get,set) : Void->Void;
    var _cb : Void->Void;

    static public function main () trace(new Main().cb);

    function new() {}
    function get_cb() return _cb;
    function set_cb(cb:Void->Void) return _cb = cb;
}
```
This code will never trace `null` for php target, because `cb` getter translated to this code:
```php
public function get_cb() {
	return (isset($this->_cb) ? $this->_cb: array($this, "_cb"));
}
```
While on other targets i always get `null` traces as expected.

Here is for php:
```shell
$ haxe -php build -main Main
$ php build/index.php
Main.hx:7: <function>
```
Here is for neko (and other targets as well):
```shell
$ haxe -neko build.n -main Main
$ neko build.n
Main.hx:7: null
```

Haxe 3.1.3, Ubuntu 14.04 x64

**Comment by Simn** [comment]
@tml @mockey: This is another one we should look into at some point.

**Comment by mockey** [comment]
The problem here is that `isset` returns `false` when something is `null`, so it returns that `array` here. If this is used only for class/object fields, you could use `property_exists` instead, i.e.:
`property_exists($this, "cb")`. That would return `true` and then `null`. I guess this `array` that is returned otherwise is used for some reflection stuff again. But who knows?

**Comment by RealyUniqueName** [comment]
Any news about this bug? )

**Comment by Simn** [comment]
I'm not gonna touch the PHP generator for Haxe 3, sorry guys.

**Comment by RealyUniqueName** [comment]
Now when i got more experience with current php target, i think it's required to rewrite it from scratch :)
PHP itself has advanced a lot since haxe->php was been written. So performing time consuming work on current php target is probably a waste of time.

**Comment by Simn** [comment]
Well, I tried that but I gave up on it too. Whoever writes a new PHP target has to have a really good knowledge of PHP and its particularities.
