### ISSUE TITLE
Creating a Int64 array in one expression fails compilation on Java target

### ISSUE THREAD

**Issue by georgkoester** [HaxeFoundation/haxe#3653]
<code><pre>// Generates wrong java code: haxe.root.Array<java.lang.Long> _g3 = 
// new haxe.root.Array<java.lang.Long>(new long[]{max, min, __temp_stmt276, __temp_stmt277});
//for (i in [max, min, Int64.make(2147483647, -1), Int64.make(-2147483648, 0)]) {
//  trace("" + i);
//}
</pre></code>

<code><pre>// workaround
var ints = new Array<Int64>();
ints[0] = max;
ints[1] = min;
ints[2] = Int64.make(2147483647, -1);
ints[3] = Int64.make(-2147483648, 0);
for (i in ints) {
  trace("" + i);
}
</pre></code>

**Comment by Simn** [comment]
Looks like this works now.
