### ISSUE TITLE
Make C# lambda function generation deterministic

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#3659]
Right now, if you compile a Haxe class that involves a lambda function, the order in which the parameters are passed into the generated Function class can change when *other* modules change. This can cause issues with build systems or external targets like Unity, because a potentially large number of C# files can be modified by a small localized change in a single file.

Ideally, the order in which parameters are passed into generated lambdas, as well as the order they are listed/initialized within the generated lambda class, are deterministic and would not change between compilations if the associated Haxe source did not change.

**Comment by waneck** [comment]
@dogles can you give me an example of what changes in a captured function? I tried going over what could possibly change from compilation, but I couldn't find anything obvious.

**Comment by waneck** [comment]
I've added a deterministic temporary variable creation which might have solved this. Can you confirm if the RC works better in this sense for you?

**Comment by Simn** [comment]
@dogles: We are approaching the 3.2 release so it would be nice if you could test whether or not this has been addressed. The changes are part of the current RC which is available at http://haxe.org/download/version/3.2.0-rc.2/
