### ISSUE TITLE
Move RecordMacros to a library

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3676]
Let's move RecordMacros and its related files to HaxeFoundation/record-macros and provide it as a haxelib.

For now we can add `@:deprecated("This class will be removed soon, please install the record-macros library")` to the public interface and then get rid of it for 3.3.

If anyone protests he has to maintain it.

**Comment by Simn** [comment]
sigh

**Comment by waneck** [comment]
I know that `SPOD` was renamed to `Record`, but I feel that it's way less generic than `Record` library. What do you think?

**Comment by Simn** [comment]
If I think about what I would search for it should probably be active-record. I don't really mind though as long as it's gone...

**Comment by ncannasse** [comment]
Any suggestion @pperidont ? (Motion-Twin are long time SPOD users)

**Comment by waneck** [comment]
Active Record seems something Microsoft would name

**Comment by nadako** [comment]
Isn't ActiveRecord what Ruby guys use as the ORM?

**Comment by Simn** [comment]
Yes, it's described as a pattern too: https://en.wikipedia.org/wiki/Active_record_pattern
