### ISSUE TITLE
Parser admits inline for rvalue closures

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3678]
This compiles fine:

```
class Main {
	static function main() {
		var func = inline function(a:Int, b:String, c:Float) return a;
		func(1, "foo", 1.0);
	}
}
```

However, the `inline` has no effect whatsoever. We should disallow this.

**Comment by ncannasse** [comment]
Ah, right forgot it was set in the function name. Let's do as you first suggested then
