### ISSUE TITLE
[sys][db] generated queries contain TRUE/FALSE not compatible with SQLite

### ISSUE THREAD

**Issue by tiagolr** [HaxeFoundation/haxe#3691]
Trying to authentificate a user using ufront + sqlite i get the following error:

```
(Error while executing SELECT * FROM auth_permission WHERE userID = 3 OR FALSE (Sqlite error in SELECT * FROM auth_permission WHERE userID = 3 OR FALSE : no such column: FALSE))  
Called from sys.db._Sqlite.SqliteConnection::request line 40
Called from sys.db.Manager::unsafeExecute line 432
Called from sys.db.Manager::unsafeObjects line 457
Called from ufront.auth.model.User::loadUserPermissions line 80
Called from ufront.auth.model.User::can line 57
Called from ufront.auth.EasyAuth::get_isSuperUser line 173
Called from ufront.auth.EasyAuth::isLoggedIn line 59
Called from ufront.auth.EasyAuth::requireLogin line 63
Called from app.controller.HomeController::thankyou line 53
Called from app.controller.HomeController::execute line 90 
```

It seems that SQLite is not compatible with TRUE or FALSE, but 0 or 1 conditions. [http://sqlfiddle.com/#!5/a2581/130](http://sqlfiddle.com/#!5/a2581/130)

I tried this before and after commit #3044 , both have the same problem.

Honestly i don't understand much of the code here, so what i tried was to replace **_every**_ occurrence of `"TRUE" / "FALSE"` with `"0"/"1"`, both on _Manager_ and _RecordMacros_ and it worked.

On _Manager_ i used a condition like: `cnx.dbName() == "SQLite" ? "0" : "FALSE"`, on RecordMacros it does not allow me to access the database name.

I'm fixing this a bit blindly and not sure if i may be breaking code somewhere else, it would be great if someone could fix this for good.

**Comment by ProG4mr** [comment]
Hi, I've compiled using the latest haxe version from dev branch and this problem remains.

In ufront if i call:
```haxe
authApi.easyAuth.requireLogin();
```
It produces the error described at the top of this issue.
This line creates a query with ```FALSE``` witch is not supported by sqlite.
```haxe
// ufront.auth.model.User  l:80
var permissions = Permission.manager.search( $userID==this.id || $groupID in groupIDs );
```

I'm using Haxe 3.2 and neko VM.

Thanks a lot if you can confirm the problem and maybe fix it or reopen this issue.

**Comment by waneck** [comment]
@ProG4mr I've added a test, but I can't reproduce your error. Please provide us with a sample code that fails and we'll reopen the issue.
Thanks!

**Comment by ProG4mr** [comment]
Hey, thanks @waneck , i was able to create a small gist for this problem, I am not sure tho if this is caused by Ufront-orm or haxe spod.

https://gist.github.com/ProG4mr/6586f47ee9e72e073b60

I should also post this also in ufront-orm repository if its caused by it.

**Comment by waneck** [comment]
Please can you provide a code that doesn't have any dependencies? This could be indeed something to do with ufront-orm. Also your example uses `testId` which isn't declared anywhere.

**Comment by ProG4mr** [comment]
Yes, i could only isolate it using ufront-orm, it has some macro construction behind it where at some point it creates queries using ```$model.manager.unsafeObjects('SELECT * FROM ' + table + ' WHERE '+$v{relationKey}+' = '+quotedID, null);``` etc..  I'm opening an issue there since i couldn't find a way to reproduce the error on std sys.db.Object/Manager.

Thanks a lot.

**Comment by championchap** [comment]
@waneck 

I've built a small project with no dependencies that I believe shows the same issue.
https://github.com/championchap/SQLite-Example/

Using Haxe 3.2 RC2
Targeting PHP, I've not tried Neko. 

Hope this helps.
