### ISSUE TITLE
[tests] add hxBitcoin library for third-party CI tests

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3692]
This new cryptography/cryptocurrency library https://github.com/cbatson/hxBitcoin seems to have extensive tests that IMO we should add to our CI tests as it would help preventing regressions wrt optimizations like const propagation and whatnot.

**Comment by cbatson** [comment]
Please take a look now; I have a couple jobs in the Travis matrix using Haxe from git.

Will this work for your needs?

**Comment by Simn** [comment]
This fell under the radar completely so we might as well close it now. Sorry about that.
