### ISSUE TITLE
Reflect.hx Flash getProperty not working as intended

### ISSUE THREAD

**Issue by hobogenized** [HaxeFoundation/haxe#3695]
In haxe/std/flash/_std/Reflect.hx:
When I enable FlashDevelop debugging with the 32-bit Java SDK, I get an error whenever my program needs to use, at line 37,
`getProperty(o :Dynamic, field : String) : Dynamic untyped`
as the object passed in does not have a field for "get_" + field. From what I see, this should be caught by the try-catch statement:

```
    try {
        return o["get_" + field]();
    } catch( e : Dynamic ) try {
        return o[field];
    } catch( e : Dynamic ) {
        return null;
    }
```

However, the specific error I get is:
[Fault] exception, information=ReferenceError: Error #1069: Property get_y not found on flixel.util.FlxPoint and there is no default value.

Though this is making use of the library HaxeFlixel, I've found that replacing 
`return o["get_" + field]();`
with
`return o[field];`
results in no issues.

This does not happen in release mode for FlashDevelop. It only happens in debug mode when the 32-bit Java debugger is set up properly. Any suggestions?

**Comment by dangerkun** [comment]
For anyone getting here from Google, completely uninstalling Flashdevelop and reinstalling fixes this issue.

**Comment by randomnine** [comment]
FlashDevelop's Debug menu has an option labelled "Break On All Errors". If it's checked, this happens.
