### ISSUE TITLE
Reflect.getProperty inconsistency between targets

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3698]
While looking into #3695 I've found an inconsistency between Flash and JS.

```
@:keep
class Main {
	static function main() {
		var m = new Main();
		trace(Reflect.getProperty(m, "x"));
	}

	var x:Float;

	function new() {
		x = 1;
	}

	function get_x() return 2;
}
```

While JS has a mechanism in place to check if `x` is actually a property, Flash just tries to access `get_x` no matter what.

**Comment by Simn** [comment]
Python has this issue too. As3 prints `null` for some reason.

I'm a bit reluctant to fix this because I actually like this behavior. :(

**Comment by ncannasse** [comment]
I think it's ok to leave it like this, with no guarantee that it will work
