### ISSUE TITLE
Classes cannot have members named "catch"

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#3701]
I'm pretty new to Haxe so I started writing an extern for PouchDB.  For simplicity I was making a Promise typedef like this:

```
typedef PromiseCallback = Dynamic->Void;

typedef Promise = {
    public function then(onSuccess: PromiseCallback, onError: PromiseCallback):Promise;
    public function catch(onException: PromiseCallback):Promise;  // <- This is line #13
}
```

However, this results in compile error:

```
timothy@sardis:~/projects$ haxe -main HelloWorld -js HelloWorld.js
HelloWorld.hx:13: characters 20-25 : Unexpected catch
```

Of course `catch` is a keyword, but it's kinda limiting when you can't write an extern for a major Javascript construct.

**Comment by JbIPS** [comment]
Maybe I'm doing something wrong, but @:native() on extern functions does not change their names.
Check the generated code here : http://try.haxe.org/#432Bc

**Comment by Simn** [comment]
I think `@:native` is a 3.2 feature?

**Comment by JbIPS** [comment]
> I'm not sure tho whether it's possible in Haxe 3.1.3 or you need a latest build

I was hoping 3.1.3 will be OK but I'll wait for 3.2.
Thanks!
