### ISSUE TITLE
typedef + class + @:optional bug?

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#3709]
```haxe
package;
class Test {
        static public function main() {
                var test:TestType = new Test1();
                trace('hello world! ${test.test}');
        }
}

class Test1 {
        public var test(get,never):Int;
        private function get_test() { return 7; }
        public function new() { }
}

typedef TestType = {
        @:optional public var test(get,never):Int;
        @:optional public var test2:Int; // This line break compilation
};
```

@:option doesn't seems to work at least with classes and getters

```
Test.hx:4: characters 2-34 : Test1 should be TestType
Test.hx:4: characters 2-34 : Test1 should be { ?test2 : Int, ?test : Int }
Test.hx:4: characters 2-34 : Test1 has no field test2 (Suggestion: test)
```

Test1 has no field test2, but it is marked as optional, so it should work (ideally) or at least yield another more descriptive error

**Comment by Simn** [comment]
@ncannasse: Is this supposed to work?

**Comment by ncannasse** [comment]
No, we don't allow such thing on class/structure subtyping.

**Comment by clarkjones** [comment]
@ncannasse @Simn , I just came across this issue in my own code, is there a formal way to make this a feature request? 
I feel like @:optional and ?  should behave the same for classes as well, I'm not sure why the type of structure should matter here.

**Comment by ncannasse** [comment]
@clarkjones sorry but it's not sound it allow it. For instance you might have a subclass that has the test2 field with another type (String instead of Int for example) so it would create runtime errors.

**Comment by clarkjones** [comment]
Didn't think of that use case, thank you.
