### ISSUE TITLE
[cs] weird behaviour of type parameters + abstracts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3711]
```haxe
abstract A<K>(haxe.DynamicAccess<Int>) {
    public function f():Array<K> return [];
}

class Main {
    static function main() {
        var a:A<String> = null;
        var k = a.f();
    }
}
```
generates
```cs
global::Array<object> k = global::_Main.A_Impl_.f<string>(a);
```
which leads to C# compiler error

however, if we change the underlying type to something different (e.g. `Dynamic`), it will be generated properly:
```cs
global::Array<object> k = global::_Main.A_Impl_.f<object>(a);
```

moreover, if i copy-paste `haxe.DynamicAccess` into my code and use that as underlying type, it will also compile fine.

**Comment by Simn** [comment]
Not sure if 3.2 priority or not.
