### ISSUE TITLE
@:access does not work if to use a @:generic 

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFoundation/haxe#3712]
Online sample here http://try.haxe.org/#13bD6
If we have a property without access we can get it using `@:access`. But if a class is generic we are get only error.

```
Build failure
Test.hx:6: characters 8-21 : Cannot access field or identifier prop for writing
```

``` Haxe
@:access(Some)
class Test {
    static function main() {

        var some:Some<Int> = new Some<Int>();
        some.prop = 5;              // Cannot access field or identifier prop for writing
    }
}
@:generic
class Some<T> //implements ISome<T>
{
    //@:allow(Test.main)
    public var prop(default, null):T;
    public var item:T;

    public function new() {}
}
```

Without `@:generic` there is no error. Also, `@:allow` works in fine in both cases.

**Comment by jgranick** [comment]
I know this was posted a while ago, but the haxelib issue with Lime tools is resolved now, will be going out in the next release
