### ISSUE TITLE
#file support

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3730]
# line is pretty useful for compilers that translate to Haxe. Would it be possible to also support something like #file to pass the source filename?

Would be helpful for a project I'm working on, but if it's not an easy change no worries :)

Might also be useful to @tardisgo?

**Comment by ncannasse** [comment]
This requires to switch the Lexer by-file table as well, and we might get strange issues if we have several `#file` in different hx files

**Comment by markknol** [comment]
What does #line do?

**Comment by Simn** [comment]
We currently have no plans to implement this.
