### ISSUE TITLE
'haxelib setup' fails for unclear reasons

### ISSUE THREAD

**Issue by lostfictions** [HaxeFoundation/haxe#3735]
Trying to follow [these instructions](http://luxeengine.com/docs/setup.html) after having built haxe from source, the following happened to me:

```
s@tekkon:~/Code/haxe$ haxelib git
This is the first time you are runing haxelib. Please run `haxelib setup` first
s@tekkon:~/Code/haxe$ haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxelib)
Path : /home/s/.haxelib
/home/s/.haxelib: Is a directory
```

That's right, it _is_ a directory. Does that mean it worked? One question seems a bit too short to justify a whole setup command. Let's try running it again:

```
s@tekkon:~/Code/haxe$ haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxelib)
Path : /home/s/.haxelib
/home/s/.haxelib: Is a directory
```

Okay, whatever. I guess it worked? Maybe? Let's get back to what we were doing:

```
s@tekkon:~/Code/haxe$ haxelib git
This is the first time you are runing haxelib. Please run `haxelib setup` first
```

Oh.

```
s@tekkon:~/Code/haxe$ haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxelib)
Path : /home/s/sdofisdofij
/home/s/.haxelib: Is a directory
```

That's interesting, I can't even change it to anything else now. Where's that configuration being stored?

What if I just need a trailing slash for some reason...?

```
s@tekkon:~/Code/haxe$ haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/lib/haxelib)
Path : /home/s/.haxelib/
/home/s/.haxelib: Is a directory
```

Okay.  At this point I googled around and found nothing. I'm baffled. Is the leading dot confusing it? Is there something weird going on with permissions? I have no idea.

**Comment by lostfictions** [comment]
Okay, poking around a bit, `getRepository` in haxelib/Main.hx seems to be the culprit: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L712

Seems it was getting confused at my trying to name a folder the same as the config file proper. That's a bit funny to me because almost every package manager I know uses that convention: `npm` saves packages to `~/.npm`, `cabal` saves to `~/.cabal`, `gem` has `~/.gem`, `cargo` is `~/.cargo`, etc. etc.

**Comment by Simn** [comment]
Wrong repository (and issue solved?)

**Comment by lostfictions** [comment]
I think this qualifies as a pretty serious unhandled error. I'll open an issues in HaxeFoundation/haxelib.
