### ISSUE TITLE
[cs] Class not found : cs.system.Func_2

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#3736]
Class not found : cs.system.Func_2

	  haxe  -cp src -cs E:/testcsunity2015/Testcsunity2015
	   -main Main -net-lib "C:\Program Files (x86)\Unity\Editor\Data\Managed\UnityEngine.dll" 
	   -net-lib libs\df1.6dll.dll -
	   -gen-hx-classes
	    -dce no

**Comment by nadako** [comment]
That's probably because default .NET 2.0 used by Haxe which doesn't have that delegate. Try adding `-D net-ver=40`.
