### ISSUE TITLE
private access in getTypedExpr(typeExpr(expr))

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3739]
In [hxAnonCls](https://github.com/andyli/hxAnonCls), I'm using `Context.getTypedExpr(Context.typeExpr(expr))` to get a "processed" expression, which have all the `import`/`using` resolved. It works fine for most cases, but when there is an inlined private field access, the returned expression does not have `@:privateAccess` thus cannot be compiled. Following is an example that demonstrates the problem:

```haxe
import haxe.macro.*;

class A {
	inline static public function test() return _test();
	static function _test() return "a";
}

class Test {
	macro static public function typed(e:Expr):Expr {
		var te = Context.typeExpr(e);
		return Context.getTypedExpr(te);
	}
	static function main():Void {
		typed(A.test()); //Cannot access private field _test
	}
}
```

It could be solved by either:
 1. Let `Context.getTypedExpr` to generate the necessary `@:privateAccess`, or
 2. Add an optional argument to `Context.typeExpr` such that there will have no optimization (inlining) take place, or
 3. Add an @:noOpt metadata that disable optimization for an expression. Such that I can `Context.getTypedExpr(Context.typeExpr(macro @:noOpt $expr))`.

**Comment by Simn** [comment]
This might be a regression from fixing #3714.

**Comment by andyli** [comment]
Btw, I would like to know if `getTypedExpr` guarantees to return a valid compilable expression?
It is returning things like <code>`.field</code>, which should be <code>this.field</code>.

**Comment by Simn** [comment]
Yeah I don't think we can guarantee that in all cases.

**Comment by Simn** [comment]
Could you try replacing getTypedExpr with storeTypedExpr?

**Comment by andyli** [comment]
Yes, that works for me :)
