### ISSUE TITLE
Inconsistent integer division behaviors between different targets.

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#3741]
``` haxe
class Div
{
    public static function main()
    {
        var i = 1;
        var j = 0;
        var k:Int = Std.int(i / j);
        trace(k);
    }
}
```

```
$ haxe -x Div
Div.hx:8: 0
```

```
$ haxe -java java -main Div && java -jar java/Div.jar
haxelib run hxjava hxjava_build.txt --haxe-version 3200
javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at haxe.root.Div.main(Unknown Source)
        at haxe.root.Div.main(Unknown Source)
```

**Comment by ncannasse** [comment]
I think we should leave integer division by 0 unspecified.

**Comment by nadako** [comment]
Yeah, but couldn't neko throw an exception there as well?

**Comment by Atry** [comment]
``` haxe
class Div
{
	public static function main()
	{
		var i = 1;
		var j = 0;
		var k:Int = (function (f:Float):Int return Std.int(f))(i / j);
		trace(k);
	}
}
```

```
$ haxe --no-opt --no-inline -java java -main Div && java -jar java/Div.jar
haxelib run hxjava hxjava_build.txt --haxe-version 3200
javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
Div.hx:8: 2147483647
```

```
$ haxe -java java -main Div && java -jar java/Div.jar
haxelib run hxjava hxjava_build.txt --haxe-version 3200
javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at haxe.root.Div.main(Unknown Source)
        at haxe.root.Div.main(Unknown Source)
```

```
$ haxe -x Div
Div.hx:8: 0
```

How about different behaviors of `Std.int`?

**Comment by Atry** [comment]
``` haxe
class StdInt
{
	public static function main()
	{
		trace(Std.int(1.0 / 0.0));
		trace(Std.int(1 / 0));
	}
}
```

```
$ haxe -x StdInt
StdInt.hx:5: 0
StdInt.hx:6: 0
```

```
$ haxe -java java -main StdInt && java -jar java/StdInt.jar
haxelib run hxjava hxjava_build.txt --haxe-version 3200
javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
StdInt.hx:5: 2147483647
Exception in thread "main" java.lang.ArithmeticException: / by zero
        at haxe.root.StdInt.main(Unknown Source)
        at haxe.root.StdInt.main(Unknown Source)
```

**Comment by Simn** [comment]
Any operation on undefined yields undefined.

**Comment by Atry** [comment]
Is `Std.int(1.0 / 0.0)` undefined?

**Comment by Simn** [comment]
Yes because `1.0 / 0.0` is undefined.

**Comment by Atry** [comment]
How about `Std.int(Math.POSITIVE_INFINITY)`?

**Comment by Simn** [comment]
`If `x` is outside of the signed Int32 range, or is NaN, NEGATIVE_INFINITY or POSITIVE_INFINITY, the result is unspecified.`

**Comment by ncannasse** [comment]
Uhm actually I was mistaken. In Haxe, there is no integer division since the result of a division is always a Float. So it means that we shouldn't have an error here, only an unspecified result equal to  Std.int(+INF). @waneck I guess that comes from an optimization of  Std.int(A/B)

**Comment by Atry** [comment]
Every Haxe target needs to simulate AVM2 behaviors.

**Comment by waneck** [comment]
Yes; Both C# and Java optimize Std.int(a/b) to use integer division. I don't really understand why we need to specify that it doesn't throw an exception - if Std.int(someValue / 0) is already unspecified and presents different values - depending on the target.
If you'd rather fail silently, the bad thing is that we won't be able to optimize to use integer division.

**Comment by Simn** [comment]
Wasn't `Std.int(a/b)` greenlighted to be optimized as integer division anyway? I remember a discussion about that, though I think it was in the context of hxcpp.

**Comment by waneck** [comment]
I guess we've forgot about division by 0. It indeed throws an exception in this case.
I still don't understand why we'd specify that it doesn't throw an exception - if the actual value is unspecified anyway.

**Comment by ncannasse** [comment]
@waneck the main issue I can see is that will give different results:
```
trace( Std.int( 1 / 0 ) );
var x : Float = 1 / 0;
trace( Std.int(x) );
```
Which IMHO is not a good thing. We could still use integer division but we have to check for 0 I guess.
CC @hughsando

**Comment by hughsando** [comment]
Let's just add Math.idiv and be done with it.

**Comment by waneck** [comment]
Yeah, I guess `Math.idiv` is the way to go

**Comment by Atry** [comment]
Or a new operator?

**Comment by Atry** [comment]
Does every Haxe target need to behave like AVM2 or some dynamic-typed platforms?

I think we could let `/` behave like C++/Java/C# in Haxe 4

**Comment by Atry** [comment]
Flash's `/` is very quiet odd, to keep ECMAScript compatibility. I don't think Haxe need ECMAScript compatibility.

**Comment by ncannasse** [comment]
We should still optimize Std.int for people that don't know about Math.idiv I think

**Comment by hughsando** [comment]
I think you have just shown that this can't be done.

**Comment by Simn** [comment]
That's my understanding as well.

**Comment by ncannasse** [comment]
Sorry if I was not clear. What I meant was to optimize Std.int but still check for 0.

**Comment by ncannasse** [comment]
and in that case return the same result as would have Std.int(+INF)

**Comment by hughsando** [comment]
I would like to see some profile data before introducing an optimization
that trades a conditional branch for a floating point op.

On Wed, Jan 14, 2015 at 10:10 PM, Nicolas Cannasse <notifications@github.com

**Comment by Simn** [comment]
Yes that sounds like a potential pessimization more than anything else.

**Comment by ncannasse** [comment]
@hughsando if there is no allocation then it's a micro optimization that is not worth it I think. If we need to allocate a float for GC boxing that's another story.
