### ISSUE TITLE
Inline + dce + extern weirdness

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/haxe#3748]
When the argument of an `inline` method contains an expression such as `new Date()`, the function is not inlined.
This is OK when DCE is off, but with JS's default DCE, when the `inline` method is in an `extern class`, the method to inline is not generated.

**Comment by clemos** [comment]
Edited, as `extern` is also involved...

**Comment by clemos** [comment]
Closing the issue as I can't figure out a simple way to reproduce.

**Comment by clemos** [comment]
Could you please have a look at the original issue on haxe-js-kit.
I really can't figure out a simpler example...

**Comment by Simn** [comment]
Can you try with latest Haxe first?

**Comment by clemos** [comment]
You're right, it seems to work :|
Sorry for the noise, thanks a lot !
