### ISSUE TITLE
dce full can remove Haxe-generated constructors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#3749]
The following code outputs 4 when compiled regularly, and 0 with `-dce full` (well, on most targets anyway, neko just spits out a `$nargs` exception), as the `SuperClass` constructor does not seem to be called in that case.

```haxe
package;

class Main
{
	public static function main()
	{
		var child = Type.createInstance(ChildClass, []);
		trace(child.x);
	}
}

class SuperClass
{
	public var x:Int;
	
	@:keep
	public function new()
	{
		x = 4;
	}
}

class ChildClass extends SuperClass {}
```

With `-D dump=pretty` you can see that normally, Haxe generates an empty constructor for `ChildClass`:

```haxe
class ChildClass extends SuperClass{
	public new(method) : Void -> Void

	 = function() = {
		super();
	}

}
```

However, with `-dce full` that constructor is removed as there are no references to it due to the usage of `Type.createInstance()`:

```haxe
class ChildClass extends SuperClass{
}
```

The problem here is you can't exactly stick a `@:keep` in front of `new()`, as that function is generated by Haxe.

**Comment by Gama11** [comment]
This seems to apply to `@:bitmap` classes as well.

**Comment by Simn** [comment]
We could introduce `@:keepConstructor` which forces a constructor to be kept if the class is kept.

What I'm more worried about are member vars with initializations on the child class.

**Comment by Gama11** [comment]
As a metadata the programmer has to add? That seems a bit confusing, e.g. when overriding a class from a library without overriding the constructor, but the library uses `Type.createInstance()` on that class, the user would need to add that (might seem like a weird scenario, but this is the case for flixel, which in at least two cases. It can be solved with a `@:keepSub` on the super class on the library side, but that seems too broad - what's really needed in that scenario is a `@:keepSubConstructor` I guess?). 

Does it make sense that dce can remove these constructors in the first place? Member variables and functions are pretty useless without a constructor, dce doesn't remove those though if the constructor is removed even if there are references to those (except in the case of `Type.createEmptyInstance()` I guess).
And in the case of `@:bitmap`, `@:font` etc classes - I think those are entirely useless without a constructor?

With member vars in the child class, a constructor is still generated - but the super call is missing.

Could the dce algorithm detect `Type.createInstance()` calls as a constructor call?

**Comment by Simn** [comment]
No, createInstance accepts arbitrary expressions.

**Comment by Simn** [comment]
Taking a fresh look at this I don't think this is actually a bug. It is true that DCE removes the Haxe-generated constructor on the child class, but then why wouldn't it? The constructor is not used in traceable code and thus not required as far as Haxe is concerned.

If ChildClass had an explicit constructor it would be removed too. If we fixed this issue it would mean that removing the constructor from the code would suddenly cause it (the Haxe-generated one) to be kept, which is outright awkward.
