### ISSUE TITLE
add more overloads for js.JQuery

### ISSUE THREAD

**Issue by Hanmac** [HaxeFoundation/haxe#3750]
some JQuery functions does need more overloads,
like #filter does also take an function pointer,

and the animation functions like #slideUp and #slideDown also takes an option hash/object instead of the default values

might that be possible to add that in Haxe? (the functions on the javascript side already exist like that)

**Comment by Simn** [comment]
Pull request?

**Comment by Hanmac** [comment]
i dont know haxe enough to make pull requests for that

**Comment by Simn** [comment]
And I don't know JQuery enough to address it.

Also I don't really see the point of maintaining JQuery in our standard library. There are better externs available for it anyway (https://github.com/andyli/jQueryExternForHaxe) and I really don't want to waste time checking which function overloads are available on which JQuery version.
