### ISSUE TITLE
DCE / hxcpp

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3756]
The following example fails to compile with hxcpp when compiled with `-dce no`

```
class Res {
	public static var name(get,never) : String;
	@:extern static inline function get_name() {
		return "OK";
	}
}

class Test {

	static function main() {
		trace(Res.name);
    }
}
```

Gives the following error at compilation
```
./src/Res.cpp(34) : error C3861: 'get_name' : unknown identifier
```

**Comment by Simn** [comment]
I wonder if we should let DCE run and remove extern fields even in "no" mode. That way we would get consistent behavior and targets wouldn't have to worry about these fields at all.

**Comment by Simn** [comment]
Ah, `remove_extern_fields` runs before DCE anyway. So yeah I'll just let the accessor fix run in no-dce mode too.
