### ISSUE TITLE
[cpp] large resource files cause compilation error

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3758]
`Error: Buffer.add: cannot grow buffer`

**Comment by Simn** [comment]
I should qualify "large": It's only 2.8 MB.

**Comment by Simn** [comment]
Resources are generated rather verbosely:

```
static unsigned char __res_0[] = {
0xff, 0xff, 0xff, 0xff,
0x3c, 0x68, 0x61, 0x78, 0x65, 0x3e, 0x0a, 0x09, 0x3c, 0x63, 
0x6c, 0x61, 0x73, 0x73, 0x20, 0x70, 0x61, 0x74, 0x68, 0x3d, 
...
```

This multiplies the byte count by 6, which explains why we hit the ~16MB limit with a 2.8 MB file.

**Comment by ncannasse** [comment]
That max_string_length limit is the single most annoying thing in OCaml. We should create a BigBuffer that manages a list of String (we already have extLib/multiArray for big arrays)

**Comment by Simn** [comment]
Yeah but I think resource handling on hxcpp could be improved regardless.

**Comment by ncannasse** [comment]
Well, I guess once compiled by C++ compiler it doesn't make much difference

**Comment by delahee** [comment]
We have problems with some C compiler with large files ( other 120MB ), +1 for trimming the output and maybe splitting other several cpp can be an option.

**Comment by Simn** [comment]
Switching to Rbuffer might not be easy on the C++ target because it only writes out files if they actually changed: ` if (not (contents=old_contents) ) then begin`. We could add some hashing function to Rbuffer and use that for comparison, but then we also need to know the hash of the existing file.

Any other ideas?

**Comment by Simn** [comment]
Let's move onto the 64bit era and forget about this.
