### ISSUE TITLE
[cs][unity] incorrect line numbers when compiled with unity 4.6 gmcs

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3759]
If we compile the following with the gmcs shipped with Unity 4.6 and try to use that component, it will report exception at line 5 while it should be at line 4 (at least on Windows).
```haxe
@:nativeGen
class Main extends unityengine.MonoBehaviour {
    function Awake() {
        throw "hi there!";
    }
}
```

build.hxml
```
-cp src
-cs out
-D no-compilation
-net-lib C:\Program Files (x86)\Unity\Editor\Data\Managed\UnityEngine.dll
-D net-ver=40
Main
-debug
--next
-cmd "C:\Program Files (x86)\Unity\Editor\Data\Mono\bin\gmcs.bat" @gmcs
```
gmcs
```
-target:library
-recurse:out\src\*.cs
-out:..\Assets\HaxeLogic.dll
-reference:"C:\Program Files (x86)\Unity\Editor\Data\Managed\UnityEngine.dll"
-debug
```

the generated code seems fine:
```cs
public virtual void Awake() {
	#line 4 "D:\\Code\\UnityPlayground\\HaxeLogic\\src\\Main.hx"
	throw global::haxe.lang.HaxeException.wrap("hi there!");
}
#line default
```
So it's actually Unity's fault, however I think we should deal with it at haxe side as I believe they couldn't care less about compiling from haxe to unity. I propose adding something like `-D unity46-line-numbers` that will substract 1 from the generated line number (hope that'd be enough).

**Comment by nadako** [comment]
I've reported the issue to Unity, will add a link here when I get it.

**Comment by nadako** [comment]
@waneck they are saying that there's inconsistend line endings (see http://fogbugz.unity3d.com/default.asp?663903_5rou4712g9vm5vpq last comment), we may want to check it.

**Comment by nadako** [comment]
Oh, I checked the line endings and they are consistent, but with Windows line endings, unity's mono display's wrong lines. Closing this again, forwarding the issue back to Unity guys.

**Comment by waneck** [comment]
If it's a matter of outputting only LF line endings, I guess we can handle it on the generator side

**Comment by nadako** [comment]
Yeah I think so too, but then one couldn't open a file in windows notepad :-P as it only handles CRLF iirc.

**Comment by waneck** [comment]
Well, I don't really care about notepad! I'd say use notepad++ :P

**Comment by nadako** [comment]
Agreed! Let's do that (and remove my `-D unity46-line-endings` hack).

**Comment by waneck** [comment]
See if this solves it for you!

**Comment by nadako** [comment]
Yep that seems to work, I'll remove the define hack then.

**Comment by nadako** [comment]
Also, Unity QA seems to finally recognized this as Unity bug and passed it to the dev team.
