### ISSUE TITLE
Resource identifier limitations

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3760]
The current implementation of resources on at least python and java requires resource names to be valid file names because their content is copied to a file and resolved by name. This leads to rather awkward OCaml exceptions because we don't properly sanitize resource names.

If we want to go with this limitation we have to document it and add a proper check.

**Comment by ncannasse** [comment]
We could use escaping for the filename, and still have the real name in the source code. I agree it needs standardization

**Comment by Simn** [comment]
We could do that. It requires having the same escaping function is OCaml and Haxe.
