### ISSUE TITLE
Can EitherType be used with @:generic for non-extern targets?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#3761]
Hey guys,

I've been reading over the CHANGES.txt for Haxe 3.2, and I came across the new `EitherType`, and was wondering if this could be used, somehow, with @:generic, on targets that are not using externs?

A prime example of this is implementing the JS typed array specification in Haxe for use on other platforms. The constructor could take an Array, a Vector, an Int, or another typed array. Currently, I have to type this as Dynamic, and then I have to check the type at runtime.

Ideally, we would want to be able to tell people that this type will be one of the above, and if at all possible, I would like to be able to generate @:generic versions that match each kind of constructor. I suppose another option could be some combination of @:generic and <T> types, if that could be done, or multiple constructors for abstract enums. I'm not sure if either of those are planned or supported.

Under most circumstances, I feel that Haxe's simplicity regarding single constructors and such is ideal, but running `if (Std.is (dynamicValue, Array<Dynamic>))` each time seems clumsy, especially when you consider the performance difference of dynamic to static types on the C++ target:

http://community.openfl.org/uploads/default/118/3ea07760d881a1cb.png
http://community.openfl.org/t/openfl-haxe-performance-tests/253

**Comment by ncannasse** [comment]
That might be a good idea but I'll let @Simn answer. That would also require optimizing out the Std.instance checks inside the function, which is not a 100% guarantee since the runtime type might differ from the compiletime one on platforms that doesn't have "static" runtime.

Another solution for this is to do the following:
```
function foo( ?a : Array<Int>, ?b : Vector<Int>, ?c : Int ) {
    if( a != null ) ... else if( b != null ) ... else if( c != null ) ... else throw "Missing parameter";
}
```

**Comment by Simn** [comment]
In general I don't plan to do anything with `@:generic` until we/you address #2902.

Also we have to be careful with feature spam here. There's already `@:genericBuild` for the most complex cases, and there's `@:multiType` which we use for Map, and there are `@:generic` methods which allow pseudo-overloading... I'm not opposed to the idea entirely, but someone would have to design it properly so complexity doesn't get out of hand.

**Comment by Simn** [comment]
Reading this again, I don't want to implement it as suggested. We have to look into a different mechanism for such a selection.
