### ISSUE TITLE
IntMap iterator

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3762]
Now that we have a nice non-allocating StringMap with optimized iterators, we should do something about IntMap iterator()/keys() which are also a common source of GC overheat

**Comment by ncannasse** [comment]
Followup for #3743, ping @SmerkyG

**Comment by nadako** [comment]
How are new StringMap iterators optimized? They are still allocating an array and then an iterator object, pretty much like old version and current `IntMap`.

**Comment by SmerkyG** [comment]
Well the AS3 one is optimized and does no allocation. But the JS version
there was no way I had found to iterate without allocating, given the
current structure of haxe. (You need a 'native' js for loop to do so
without allocation) My admittedly poor fix for that was to cache the array
of indices. But I think Nicolas removed that questionable feature, so it
unfortunately does allocate every time.

**Comment by SmerkyG** [comment]
Btw, I'm working on the AS3 version of IntMap right now. (Just so no one else bothers to)

**Comment by ncannasse** [comment]
@SmerkyG we can use native JS for loops with untyped __js__ but I think it will not help since we need to exit the loop after each element. It would for for an iter/map with callbacks.
