### ISSUE TITLE
Copilation Error by hxcpp

### ISSUE THREAD

**Issue by parkjaeman** [HaxeFoundation/haxe#3770]
I got compilation error from haxe to cpp when I tried with following simple hello world example.

<HelloWorld.hx>
class HelloWorld {
  static public function main():Void {
    trace("Hello World");
  }
}

Follows are error messages.

parkjaeman@parkjaeman-desktop:~/dev/my_haxe$ sudo haxe -main HelloWorld.hx -cpp HelloWorld -D HXCPP_M64
haxelib run hxcpp Build.xml haxe -DHXCPP_M64="1" -Dhaxe3="1" -Dhaxe_ver="3.2" -Dhxcpp_api_level="313" -I"/usr/lib/haxe/extraLibs/" -I"/usr/local/lib/haxe/extraLibs/" -I"" -I"/usr/lib/haxe/std/cpp/_std/" -I"/usr/local/lib/haxe/std/cpp/_std/" -I"/usr/lib/haxe/std/" -I"/usr/local/lib/haxe/std/"
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/Std.cpp -oobj/linux64/b53c17ba_Std.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/HelloWorld.cpp -oobj/linux64/b53c17ba_HelloWorld.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/haxe/Log.cpp -oobj/linux64/4bb52b44_Log.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/__files__.cpp -oobj/linux64/b53c17ba___files__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/__resources__.cpp -oobj/linux64/b53c17ba___resources__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -m64 -DHXCPP_M64 -I/usr/lib/haxelib/hxcpp/3,1,48/include -x c++ -frtti ./src/__boot__.cpp -oobj/linux64/b53c17ba___boot__.o
Error: In file included from ./src/HelloWorld.cpp:4:0:
include/HelloWorld.h:27:47: error: ‘hx::PropertyAccess’ has not been declared
 Dynamic __Field(const ::String &inString, hx::PropertyAccess inCallProp);
                                               ^
In file included from ./src/HelloWorld.cpp:7:0:
include/haxe/Log.h:28:47: error: ‘hx::PropertyAccess’ has not been declared
 Dynamic __Field(const ::String &inString, hx::PropertyAccess inCallProp);
                                               ^
include/haxe/Log.h:29:73: error: ‘hx::PropertyAccess’ has not been declared
 Dynamic __SetField(const ::String &inString,const Dynamic &inValue, hx::PropertyAccess inCallProp);
                                                                         ^
./src/HelloWorld.cpp:47:60: error: ‘hx::PropertyAccess’ has not been declared
 Dynamic HelloWorld_obj::__Field(const ::String &inName,hx::PropertyAccess inCallProp)
                                                            ^
Error: Build failed

Please let me know what is problem.

**Comment by Simn** [comment]
It means you are using haxe git with haxelib hxcpp. Use git both or release both.
