### ISSUE TITLE
[cs] Closure missing compare operator?

### ISSUE THREAD

**Issue by muguangyi** [HaxeFoundation/haxe#3771]
If creating an array to maintain functions like below:
typedef Listener = String -> Void;

class Listener1
{
    public function notify(pMessage:String):Void
    {
    }
}
...
var tListener1:Listener1 = new Listener1();
var tListeners:Array<Listener> = new Array<Listener>();
tListeners.push(tListener1.notify);
var tIndex:Int = tListeners.indexOf(tListener1.notify);
trace(tIndex);    // tIndex = -1 !!!

That because when converting cs code, every calling "notify" function will change to new Closure(....), and Closure doesn't override Equals(...) function, so only compare two new Closures, they are different. But in fact they are pointing to the same function.

I don't know if need add following code to std/cs/internal/Functon.hx:
public function Equals(obj:Dynamic):Bool
@:keep @:nativeGen @:native('haxe.lang.Closure') class Closure extends VarArgsBase
{
	private var obj:Dynamic;
	private var field:String;
	private var hash:Int;

	public function new(obj:Dynamic, field, hash)
	{
		super(-1, -1);
		this.obj = obj;
		this.field = field;
		this.hash = hash;
	}

	override public function __hx_invokeDynamic(dynArgs:Array<Dynamic>):Dynamic
	{
		return Runtime.callField(obj, field, hash, dynArgs);
	}

	// ----------------- override Equals method -------------------
	public function Equals(obj:Dynamic):Bool
	{
		if (obj == null)
			return false;
		
		var c:Closure = cast obj;
		return (c.obj == this.obj && c.field == this.field);
	}

}

**Comment by waneck** [comment]
Can you send a pull-request?

**Comment by waneck** [comment]
Also note that this use of `indexOf` on functions is not portable and may not work on other targets. The correct way to compare functions is to use `Reflect.compareMethods`
Your code would then look like this:
```haxe
var tIndex:Int = -1;
for (i in 0...tListeners.length) 
  if (Reflect.compareMethods(tListeners[i],tListener1.notify)) {
    tIndex = i; break; 
  }
```

**Comment by muguangyi** [comment]
Sure, thanks for a quick response.
