### ISSUE TITLE
All platforms should enforce "Module Foobar is loaded with a different case than FooBar"

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3779]
In doing the WebIDL overhaul, I ran into this error I had never seen before (https://ci.appveyor.com/project/Simn/haxe/build/368). The error makes good sense, but why should it only happen on Windows? Users that develop on Linux/Mac should be able to safely assume that their code will compile on all platforms.

**Comment by nadako** [comment]
I had that issue with completion server and it's related to 8.3 names being disabled in windows and this code: https://github.com/HaxeFoundation/haxe/blob/fc415930a8341805f743220e3823f1b05552fe84/main.ml#L1376

**Comment by nadako** [comment]
This is annoying. I've made a PR for ocamllibs (https://github.com/HaxeFoundation/ocamllibs/pull/12) that should fix this. Please, review/merge this for 3.2.
