### ISSUE TITLE
type param constrains + enum type params + abstract casts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3781]
```haxe
enum E {
    E1<T:String>(v:T);
}

abstract Ab(String) to String {}

class Main<T:Ab> {
    static function main() {
    }

    function doStuff(v:T) {
        E1(v);
    }
}
```

```
Fatal error: exception Type.Unify_error(_)
Raised at file "typer.ml", line 193, characters 12-27
Called from file "list.ml", line 73, characters 12-15
Called from file "typecore.ml", line 365, characters 3-6
Called from file "main.ml", line 1481, characters 2-21
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1700, characters 1-35
```

**Comment by nadako** [comment]
Also, if we remove `E1` type param and use plain `String`, we get `Main.T should be String` error which is kind of unexpected, but I guess is similar to https://github.com/HaxeFoundation/haxe/issues/3777#issuecomment-70533875

**Comment by Simn** [comment]
I've made sure the thing is caught now.

As for the failing unification, constraints are checked by checking for class equality. I "think" we can allow abstract variance there, but I don't want to change this for 3.2.

**Comment by Simn** [comment]
Also feel free to add a test for the exception.
