### ISSUE TITLE
resolve enum constructors using type param constraints

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3782]
Subj. Is this possible?

Ab.hx
```haxe
@:enum abstract Ab(Int) {
    var A = 1;
}
```

Main.hx
```haxe
class Main {
    static function main() {
        f(A); // Unknown identifier : A
    }

    static function f<T:Ab>(v:T) {}
}
```

**Comment by Simn** [comment]
Does it work for normal enums?

**Comment by nadako** [comment]
Nope :-( But I don't see a reason for it not to be allowed.

**Comment by Simn** [comment]
I don't know, in theory you could have multiple constraints and with abstracts I imagine there could be situations where the identifier is not unambiguous...

**Comment by nadako** [comment]
Lol, I managed to crash haxe compiler with this:
```haxe
abstract Ab1(String) to Ab1 {}
abstract Ab2(String) from Ab1 {}
```

**Comment by nadako** [comment]
But you're right about the ambiguity, i.e.:

```haxe
@:enum abstract Ab1(String) from String to Ab2 {
    var A = "a1";
}

@:enum abstract Ab2(String) from String to Ab1 {
    var A = "a2";
}

class Main {
    static function main() {
        f(Ab1.A); // a1
        f(Ab2.A); // a2
    }

    static function f<T:(Ab1,Ab2)>(v:T) {}
}
```

**Comment by Simn** [comment]
We should fix the crash. The `from` is invalid but it is checked too late...

**Comment by Simn** [comment]
A non-invalid hanging example is

```
abstract Ab1(Ab2) from Ab2 {}
abstract Ab2(Ab1) from Ab1 {}
```

I feel like people writing code like that deserve to get crashes, but I suppose we'll have to employ a cast stack for these things as well.

**Comment by nadako** [comment]
(tho on the ambiguity note - i doubt those enum abstracts actually have any use, so maybe we could error on (very rare) ambigous cases).

**Comment by Simn** [comment]
Yeah but we can't really support this anyway. At the time of typing `A` the expected type is already monomorphed so we have no information about it.

**Comment by nadako** [comment]
> A non-invalid hanging example is
That doesn't hang for me...

**Comment by Simn** [comment]
You have to trigger the cast, e.g.

```
        var a:Ab1 = null;
	var b:Ab2 = a;
```

**Comment by nadako** [comment]
oh. well i'll just believe your word :-P

**Comment by Simn** [comment]
Didn't mean to close yet. I've fixed your crash case in a way that hopefully doesn't cause anything to explode, now I only have to figure out how to give a proper error message on my crash case.

**Comment by Simn** [comment]
Related issue #1446
