### ISSUE TITLE
Unbound variable `

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3783]
```haxe
class TestMain
{
    var field = function () {
        method();
    }

    function method ()
    {
    }

    private static function main ()
    {
    }
}
```

Flash:
```
./TestMain.hx:4: characters 8-14 : Unbound variable `
```

JS successfully compiles but the output is a syntax error.

**Comment by Simn** [comment]
Not a regression... but still quite silly.

**Comment by Simn** [comment]
Ah I see, this is not supposed to compile because member variable initializations are not allowed to access `this` which you do there implicitly by accessing `method`. The check misses this case because it's a closure which doesn't properly access `this` but the `ctx.vthis` variable.
