### ISSUE TITLE
Local array optimisation

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#3784]
Hi,

We are tracking micro allocations and try to find compromises between ergonomy and perfs. However one case is often popping to us: 

In high level code we often have micro allocations coming from such constructs : 

```
var s = 0.0;
inline function foo(r) 
    return 2.0 + r;
for ( r in [0.0,1.0] )
    s+=foo(r);
trace(s);
```

Generated code (at least in Cpp) shows that the array is fully allocated despite not being accessible to the user.

It would be incredibly awesomely super mega uber to have the local array that serves as iteration, fully inlined to get rid of the allocation.
the loop should also be inlined since every parameters from the loop is well known.

Since we have to be conservative in order not to make the inlining costy and cache missy for big arrays, I suggest limiting this aggressive inlining to array of 8 or less objects.

I strongly believe this could improve usability on low perf devices.

Thanks !

**Comment by Simn** [comment]
We currently don't do any loop unrolling at all. It might be possible to add this for simple cases such as this one.

The question is in which case it should be applied. It multiplies the function body code which can lead to other performance issues if the code is large. We also have to make sure that there's no `break` or `continue` in there.

**Comment by Simn** [comment]
P.S.: I think I can make the analyzer smart enough to optimize that example to `trace(5)`

**Comment by delahee** [comment]
There is much to say but you might want hit the people at ocaml and ask for their policy. 
As long as we get rid of that nasty constant length useless array allocation, we are fine :)

**Comment by RealyUniqueName** [comment]
Could such loops with const-length arrays be transformed like this?
```haxe
for(r in [0.0, 1.0, 2.5]) {
  doSomething(r);
}
//transformed to
var i = 0;
while(i < 3) {
  var r = switch(i) {
    case 0: 0.0;
    case 1: 1.0;
    case 2: 1.5;
  }
  ++i;
  doSomething(r);
}
```
Does it make any sense?

**Comment by ncannasse** [comment]
I don't think that we should auto unroll all loops, for instance this might
produce a lot of code with a big constant array and a big loop expression.
Maybe that should be a metadata:   `@:unroll for( i in [0,1,2] ) expr;`

**Comment by RealyUniqueName** [comment]
There is a limitation on amount of expressions in a loop body, which can be adjusted with `-D loop_unroll_max_cost=10`. By default it's 250.
That cost is calculated as follows: `array_length * loop_body_expr_count`. Expressions in a loop body are counted recursively.

**Comment by ncannasse** [comment]
Ok perfect
