### ISSUE TITLE
TObjectDecl optional field null padding

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3785]
We have null padding for optional function arguments, so it makes sense to add it for optional structure declarations as well. The most prominent example is a simple `trace` because that misses the `customParams` argument.

**Comment by ncannasse** [comment]
null padding for optional args is only done for platforms that don't have variable args support (or for inlining) we then remove the extra nulls at the end for the code to look more native.

I don't really see the point of adding nulls for TObjectDecl, actually this will be very costly if you use it as a (big) list of options, since it will create larger objects than they need to be. Accessing these fields will return null anyway, and this will change Reflect.hasField behavior.

**Comment by nadako** [comment]
> Accessing these fields will return null anyway

I live with the idea that this is unspecified.

**Comment by ncannasse** [comment]
It's not. Not for anonymous structures. Only for classes if you access an undeclared field (usually through Reflect/Dynamic).

**Comment by Simn** [comment]
The problem is that you cannot generate an efficient representation of these objects if you have to assume that they might be assigned to larger structure types. Imagine them being created as class instances in a case like this:

```
haxe.Log.trace("foo", new AnonType123("Main","Main.hx",5,"main"));
```

Here `AnonType123` was determined by sorting the fields and looking up their combined types. But then `haxe.Log.trace` itself is created with an argument type of, say, `AnonType124` because of that additional field it has, and the generated code no longer works.

I used to deal with this at the generator level, but the analyzer messes that up now because it creates a temp var for the TObjectDecl and the assignment can no longer be detected after that. This is why I have to put it _somewhere_ before the post-processing is done.

**Comment by ncannasse** [comment]
I agree we could have some backend that generates an optimized version of the structures. This would make sense only for static platforms. But I don't think this requires null padding, and only constant structures can be assigned to a larger type so it's easy to check in the generator if you have such a case.

Regarding your analyser case, maybe that would require to mutate the Constant TAnon after we successfully unify it with the TAnon having optional fields. That would be a small regression in case the same const anon is used twice for different target structures types, but I think that's a bit a rare case.

**Comment by Simn** [comment]
That would be fine too (how is that different from null-padding the TObjectDecl itself?). I'll go ahead and try this on genc and get back to you after 3.2.

**Comment by ncannasse** [comment]
It's different from null padding because we modify the type, not the value. On non static platforms this will not create any overhead. And no we couldn't have removed null fields because there's a runtime difference between {} and {a:null} (Reflect.hasField)

**Comment by ncannasse** [comment]
...so we want to keep the object as it was declared in the first place by the user.

**Comment by ncannasse** [comment]
But yes, using this method will require to have Reflect.hasField result be unspecified if the field is optional.
