### ISSUE TITLE
type constraint fields

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3789]
The following WORKS:
```haxe
interface I {
    function f():Void;
}

class C<T:I> {
    function f() {
        (null : T).f();
    }
}
```
However if we move `I` into separate module, it DOES NOT:

I.hx
```haxe
interface I {
    function f():Void;
}
```
C.hx
```haxe
class C<T:I> {
    function f() {
        (null : T).f();
    }
}
```
giving `C.hx:3: characters 8-20 : C.T has no field f`

**Comment by Simn** [comment]
Must be a missing pass flush or `c.cl_build()` somewhere.

The question is where. :)

**Comment by ncannasse** [comment]
That's weird. If we enter the typing of C.f we should already have built the interface since it's on a previous pass

**Comment by ncannasse** [comment]
if I is a class then does it works ?

**Comment by Simn** [comment]
No

**Comment by waneck** [comment]
It's actually a known limitation only on gencommon. I've still got to dix a
couple of bugs before I get this working correctly

**Comment by Simn** [comment]
Wrong issue? :P

**Comment by waneck** [comment]
Oh sorry. I totally misunderstood the bug report. I thiught it was about
type parameters with constraints being typed as dynamic on cs/java

**Comment by Simn** [comment]
Doesn't this just happen because we delay type parameter constraints? If the only reference to `I` is in a constraint it is never properly seen/loaded until the constraint pass, which is after the field typing.
