### ISSUE TITLE
Important regression

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3792]
The following used to trace 1,2,3 (loop variable capture) and is now 3,3,3 because of the loop unroll optimization.

```
class Test {
	static function main() {
		var arr = [];
		for( x in [1,2,3] )
			arr.push(function() return x);
		for( f in arr )
			trace(f());
 	}
}
```

**Comment by Simn** [comment]
Oh dear... I guess we have to abort if we have an EFunction there.

**Comment by ncannasse** [comment]
Or could we not redeclare the var each time ?

**Comment by ncannasse** [comment]
PS: I hope there's also a TBlock that prevents the variable from escaping the TFor scope ;)

**Comment by Simn** [comment]
Then we have to map the expression and replace all references to the var. I consider this a rare case so I'm fine with canceling here.

**Comment by ncannasse** [comment]
Good for me too

**Comment by ncannasse** [comment]
BTW that means we don't have this thing well unit tested

**Comment by waneck** [comment]
Actually I think that you can only cancel if the for var has `v_capture = true`

**Comment by Simn** [comment]
Yes but we don't know that yet because the optimization runs very early.

**Comment by ncannasse** [comment]
PS : I'm thinking we might have macros calls that returns EBreak/EFunction

**Comment by ncannasse** [comment]
And I think that maybe we shouldn't manipulate the AST until it's typed (for macros reasons again)

**Comment by Simn** [comment]
I'm thinking we should comment the feature out again and spend some time thinking about it after 3.2.

**Comment by ncannasse** [comment]
Well we should disable it right now for sure since it's a regression, and add unit test to remember why we did so :)

**Comment by Simn** [comment]
The feature has been disabled again, we still have #3784 open to keep track of it.
