### ISSUE TITLE
Mark overridden fields

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3797]
It would be really convenient for some generators if the compiler marked overridden fields with a metadata. It looks at these fields anyway in `check_overriding`.

**Comment by ncannasse** [comment]
That might not make compiler cache happy : depending which modules you reuse the fields would or would not be overriden. Would be better to provide a is_overriden method that look at all the classes inheriting the requested one

**Comment by Simn** [comment]
Yes, but that means looking at _all_ classes because we don't know which classes override a class from that class' point of view. I've had the same problem in DCE when finding dependent fields.

**Comment by ncannasse** [comment]
Yes, but does that cause a performance problem ?

**Comment by Simn** [comment]
We look at every class for every field we keep. It's certainly not free but I don't have code bases large enough to measure performance impact. It's just so gosh darn inelegant, especially if at generator level we have to do it again to e.g. determine which method is "virtual".

**Comment by ncannasse** [comment]
I don't think that's worth the change. We spend much more time map'ing our Expr. Limiting data duplication in the compiler is more reliable, the only exception being if that actually cause an issue with performances, which is not very likely given we will reach a few thousands classes at worst.
