### ISSUE TITLE
[swf] Bad Array<Dynamic> behavior?

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/haxe#3799]
Just try example on `swf` / `flash` target:
```
class Test {
    
    static var arr:Array<Dynamic> = [0, "Hello", " World", 0.4];
    
    static function main() {
        // expected "Hello World", got NaN traced
        trace(arr[1] + arr[2]);
    }
}
```
I sure `js` target works fine!

**Comment by Simn** [comment]
This actually looks like a core problem to me. The type of the array access is inferred as Float:

```
[Binop:Float]
	[Array:Float]
		[Field:Array<Dynamic>]
			[TypeExpr Main:Class<Main>]
			[FStatic:Array<Dynamic>]
				Main
				arr
		[Const 1:Int]
	+
	[Array:Float]
		[Field:Array<Dynamic>]
			[TypeExpr Main:Class<Main>]
			[FStatic:Array<Dynamic>]
				Main
				arr
		[Const 2:Int]
```

This is probably due to the binop defaulting to Float. The swf generator then probably coerces to Float which causes the observed behavior.

**Comment by Simn** [comment]
Is this broken in 3.1.3 too?

**Comment by ncannasse** [comment]
@Simn most likely, and we maybe don't want to change that, because we can't differenciate a TMono that comes from an untyped var (which would need to be unified as Float) from one that would come from a TDynamic being relaxed to TMono

**Comment by Simn** [comment]
Yes but I don't think there should be monomorphs here in the first place. This only happens because we do not bind `Dynamic` to them. Surely an array access on `Array<Dynamic>` should always yield `Dynamic`.
