### ISSUE TITLE
FPHelper and threads

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3800]
Some platforms that have multithreading are using static vars for no-allocation FPHelper implementation. They need to use TLS instead.

To fix for neko and cpp

**Comment by ncannasse** [comment]
This been fixed in neko, assigning to @hughsando

**Comment by hughsando** [comment]
This has been fixed by using abstracts - are we all happy with this situation?

**Comment by ncannasse** [comment]
I am :)
