### ISSUE TITLE
Suggestion regarding ... uhm ... nested implicit conversion?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#3801]
Recently, I've had this idea:

```
abstract JsonValue(Dynamic) from Int to Int from Float to Float from Bool to Bool from String to String from Array<JsonValue> to Array<JsonValue> from Dynamic<JsonValue> to Dynamic<JsonValue> {

}
```

That actually seemed like a way to constrain what a JSON value is.

Unfortunately it doesn't quite work:
- `(5 : JsonValue)` works
- `([5] : JsonValue)` works
- `({ foo: 5 } : JsonValue)` doesn't
- `([[5]] : JsonValue)` doesn't
- `({ foo: (5 : JsonValue) } : JsonValue)` does

This is honestly the one use case I have for this, for which macros will also do the trick. But it occurred to me that it might make sense for this to work anyway.

**Comment by Simn** [comment]
Variance is a beast and I'm very reluctant to feed it more. I would only look into this if someone wrote me the ultimate set of unit tests to make sure that there are no type holes introduced.

**Comment by ncannasse** [comment]
Variance of writable object fields does not work, since they are invariant.
We could only support that with top-down type inference (with_type)

**Comment by back2dos** [comment]
That would make sense, but it is not the case. For example `{ foo : Int }` does unify with `Dynamic<Int>`, as seen here: http://try.haxe.org/#F10f1

**Comment by back2dos** [comment]
Believe it or not, this started working in 3.4.7: https://try.haxe.org/#fF460f5A
