### ISSUE TITLE
Cast parsing leads to bad code

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3806]
```
using haxe.macro.Tools;

@:coreType
abstract Char from Int to Int { }

@:coreType
abstract Pointer<T> {
	@:op(A - B) public static function subP<T>(lhs:Pointer<T>, rhs:Pointer<T>):Pointer<T>;

	public inline function value() {
		return this;
	}
}

class Main {
    static function main() {
		var p:Pointer<Char> = null;
		var p2:Pointer<Char> = null;
		inspect(cast (p - p2).value());
    }

	macro static function inspect(e:haxe.macro.Expr) {
		trace(e.toString()); // (cast p - p2).value()
		return e;
	}
}
```

This leads to bad code being generated down the line because the compiler starts type inferring an open anon structure from the monomorph introduced by the cast:

```
[Call:Unknown<9>]
	[Field:Void -> Unknown<9>]
		[Parenthesis:{ value : Void -> Unknown<9> }]
			[Cast:{ value : Void -> Unknown<9> }]
				[Cast:Pointer<Char>]
					[Binop:Pointer<Char>]
						[Local p(1044):Pointer<Char>]
						-
						[Local p2(1045):Pointer<Char>]
		[FAnon:Void -> Unknown<9>] value
```

Surely the `cast` should have a lower precedence here.

**Comment by ncannasse** [comment]
I don't think we should change the cast precedence. Cast is not an operator but a function, so it should work as a function call

**Comment by Simn** [comment]
Whaaaat? Cast is clearly an operator, it doesn't require the parentheses and doesn't parse its second argument as an expression.

**Comment by ncannasse** [comment]
uhm, right it's `cast expr`. Time for bed I guess :)

**Comment by Simn** [comment]
Oh man, we actually rely on this behavior here: https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/Std.hx#L40

I still really want to fix this, but now I'm a bit reluctant.
