### ISSUE TITLE
How can I insert function-pointer of haxe function to argument of cpp library?

### ISSUE THREAD

**Issue by parkjaeman** [HaxeFoundation/haxe#3811]
I am binding EFL graphics library. On the work, I met a problem.
How can I insert function-pointer of hax function to argument of cpp library?

I used val_data() and val_get_handle().
In case of val_data(), null was returned.
In case of val_get_handle(), it failed in val_check_kind().
How can I solve this problem?

**Comment by Simn** [comment]
Sorry for being blunt, but github issues are not a helpdesk. Try the haxelang google group for questions. If you believe that you have something that should work but doesn't make a reproducible example and post it as an issue (probably to the hxcpp repository in this case).
