### ISSUE TITLE
Break inside closure inside loop

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3812]
```
class Main {
	static function main() {
		var a = 0;
		while (true) {
			++a;
			function x() {
				if (a == 3) {
					break;
				}
			}
			x();
		}
	}
}
```

* flash: compiles, errors with `At least one branch target was not on a valid instruction in the method.`
* as3: mxmlc complains `Error: Target of break statement was not found.`
* neko: `Break outside a loop`
* js: `This expression cannot be compiled to Javascript`
* cpp: fails in native compiler with `error C2043: illegal break`
* python: compiles, errors with `SyntaxError: 'break' outside loop`
* php: compiles, errors with `Fatal error: 'break' operator accepts only positive numbers`
* java: fails in native compiler with `error: break outside switch or loop`
* cs: fails in native compiler with `No enclosing loop out of which to break or continue`
* interp: compiles and runs fine (wtf Nicolas?)

I suppose we should properly disallow this at typing level?

**Comment by nadako** [comment]
what about continue? :)

**Comment by Simn** [comment]
Should be the same of course.

**Comment by ncannasse** [comment]
Yes, this is not correct. entering type_function should toggle off in_loop (from memory).

But please don't remove it in interp, i'm using this behavior !





...




...

just joking.

**Comment by Simn** [comment]
fyi, I've allowed it again for inline closures because C# actually uses that and I think it should work just fine.

**Comment by ncannasse** [comment]
@Simn I'm not sure we should allow this in that case, but it's not very important

**Comment by Simn** [comment]
I think it's fine because the inline function cannot leave the loop. If you try to assign it to e.g. an outside variable you get "Cannot create closure on inline closure". This means that you can only call it from within the loop.
