### ISSUE TITLE
document optional structure field behaviour

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3814]
this topic is bugging me often and there seems to be no conclusion on how it should work (though there are some discussion in #2928 and #3785)

case 1 - explicit structure:
```haxe
var a:{?f:Int} = {};
a.f; // is this defined? does it return null? or maybe default value (e.g. 0 for Int on c#)?
```

case 2 - dynamic:
```haxe
var a:{?f:Int} = Json.parse("{}"};
a.f; // is this defined at all? if yes, is the behaviour the same as for case 1?
```

cc @ncannasse @Simn @waneck

**Comment by ncannasse** [comment]
Optional fields are always typed as `Null<T>` so in both cases you should get null whatever the platform. The only thing that we do no guarantee is whether Reflect.hasField returns true or false

**Comment by ncannasse** [comment]
PS : if it's not already we should add unit tests for that

**Comment by Simn** [comment]
I'm fine with that specification for case 1, but case 2 worries me. It assigns Dynamic to a structure with optional fields, but how far can I take that? What if I used some native JSON parser to do the same thing? Or if I assigned `null`, or `1` or any other incompatible type?

**Comment by ncannasse** [comment]
@Simn in that case that's unspecified

**Comment by ncannasse** [comment]
But building structures by reflection should work, whatever if they have optional fields or not

**Comment by nadako** [comment]
Yeah, about Dynamic i was only talking about structures typed as Dynamic, I'm totally fine with it being unspecified if it's not a structure.

**Comment by ncannasse** [comment]
There's still some not-yet-specified things regarding how class instance upcasted to a structure with optional fields works
