### ISSUE TITLE
Serialiser issue on variable with getter and setter, on flash target => "cannot serialise Function" exception

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#3815]
Hi,
When i try to serialise a Signal Class from mSignal Library on flah target, i will get a "cannot serialise Function" exception when the Signal has a listener added. Its because the Slot class can't be serialised. The exception comes from the listener field.

in flash target the list of fields that needs to be serialised comes from function serializeClassFields. Or the listener field of Slot class is listed has variable that needs to be serialised. But as its a Function, the serialisation of the field fails just after.
I think its because in generated flash code we get that:
		public function get listener() : * { return $listener; }
		public function set listener( __v : * ) : void { set_listener(__v); }
		protected var $listener : *;

thats why the serializeClassFields consider listener as a variable that needs to be serialised. Because the list of variables is returned from flash code: var vars = xml.factory[0].child("variable");

So the issue may occure on any variable that has getter AND setter, and fantom field associated.

Solution: fix serializeClassFields to avoid the serialisation of such Function fields. I fixed it with a extend class of Serialiser and added in function 'serializeClassFields ' the line
if (Type.typeof(Reflect.field(v, f)) == TFunction) continue;
just before 
			serializeString(f);
			serialize(Reflect.field(v,f));

but it may be a bit not efficient solution. Maybe a solution based on naming of fields that starts with $ would be better??

Thanks

**Comment by ncannasse** [comment]
I don't think any of the solution is right. Ignoring functions is not a good idea since it might create issues  when people don't understand that they can't be serialized and ignoring fields starting with a $ is totally arbitrary.  I think it's up to you to add and implement hxSerialize/hxUnserialize on your class.

**Comment by sebpatu** [comment]
I don't understand.
it gives a non consistent behavior of the serialiser, because in flash 9 it already serialise by avoiding functions! with 		var vars = xml.factory[0].child("variable");
and if compiler don't create the underlying field becuase of getter AND setter, it will work fine also.
so its a combination of compiler + Serialiser that makes it not serialisable. 
thats not consistent so error is not easy to detect and to handle.

**Comment by ncannasse** [comment]
What's avoided are member functions (class prototypes) variable functions are not ignored.

**Comment by sebpatu** [comment]
ok, in that sense i undertand better.
Thanks
