### ISSUE TITLE
invalid pattern matching

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#3816]
```
enum A{
    Bump;
    Bop;
}

class Test {
    static function main() {
        trace("Haxe is great!");
        var b = [Bump,Bop];
        switch(b[0]){
                case Bump: trace("a");
                case Bump,Bop: trace("b"); //Nop...
        }
    }
}
```

Hi folks !

The pattern matcher is a bit tolerant sometimes. Bump should not be allowed to be repeated.
I believe this should be forbidden.

Bisous !

**Comment by Simn** [comment]
This is similar to https://github.com/HaxeFoundation/haxe/issues/2508

The problem is that uselessness is determined per-case and not per-pattern. I still haven't found a good way to deal with this without breaking some other patterns involving or-clauses.
