### ISSUE TITLE
[cs/java] Map implementation can cause duplicated keys

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#3818]
Tested with latest C# StringMap implementation. I assume this happens with ObjectMap and IntMap as well, with similar hash collisions. I only tested C#, but it looks like the Java map implementation is identical.

```
package;

class TestBug
{

  static function assert(b:Bool, ?pos:haxe.PosInfos) if (!b) throw 'assert $pos';

  public static function main() {
    trace('start');
    var m = new Map<String, Int>();
    var ss = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"];

    // NOTE: these three keys hash to the same value
    var s1 = "UI/fx/Materials/fx_ui_atlas_icons_additive_mat";
    var s2 = "UI/img/bg_info";
    var s3 = "art/3d/env/props/city_props/textures/cityprops_debris01";

    // prime to resize the hash array to be big enough
    for (s in ss) {
      m[s] = 0;
    }

    // make colliding entries
    m[s1] = 1;
    m[s2] = 2;
    m[s3] = 3;

    m.remove(s1);
    // colliding entries at this point: [DELETED, s2, s3]

    m[s2] = 4;
    // colliding entries at this point: [s2, s2, s3] (!!!)

    m.remove(s2);
    // [DELETED, s2, s3]

    assert(!m.exists(s2)); // ERROR OMGZ

    trace('success');
  }
}
```

It looks like the problem is that set() looks the first entry that matches the key OR is empty/deleted, but remove() simply marks the corresponding entry as deleted. That means further calls to set() for existing values that collide with the removed value will fill the deleted slot, rather than finding/updating the correct slot.

I think the fix would be to move any deleted slots to the end of the set of colliding entries, so that set() will always find the key before it encounters any deleted slots.

@waneck

**Comment by waneck** [comment]
Ouch. That's quite an overlook. I'll fix it tonight.

**Comment by waneck** [comment]
I've pushed a quick fix, but I'm going to leave this open just to make sure I didn't forget any special case

**Comment by Simn** [comment]
Anything left to do here?

**Comment by waneck** [comment]
Everything is looking good
