### ISSUE TITLE
Is there a way to create a process in Haxe and hide the console on windows?

### ISSUE THREAD

**Issue by nescribal** [HaxeFoundation/haxe#3820]
I'm trying to create a process in Haxe to run a shell based program (mplayer to be more accurate).
When I create the process, it opens the DOS console shell and runs mplayer.
I believe in c++ process creation there is a param to hide the console (shell). Is it possible in Haxe to create this process passing such params?

Thanks!

**Comment by Simn** [comment]
This is an issue tracker and not a helpdesk, try the haxelang google group.
