### ISSUE TITLE
Clarification of the `classPaths` argument of `macro.Compiler.include`

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3821]
[The doc says](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Compiler.hx#L108-L109)
```
		@param classPaths Array of additional class paths to check. This can be
		    used to add packages outside the usual class paths.
```

I wonder what does it actually do? It does not really add the `classPaths` like `Compiler.addClassPath`, but just triggers a `Class not found` error.

Example:
Test.hx
```haxe
class Test {
	static function main() {
		
	}
}
```

other/datetime/DateTime.hx
```haxe
package datetime;

class DateTime {
	
}
```

build.hxml
```
-main Test
--interp
--macro include('datetime', true, null, ['other'])
```

error:
```
--macro:1: character 0 : Class not found : datetime.DateTime
```

discovered by @R32

**Comment by nadako** [comment]
Wow that doc is confusing. it's not "additional", it does replace the search path and yet it doesn't add those paths for compiler. I wonder how did it work in 3.1.3.

**Comment by andyli** [comment]
Well, 3.1.3 gives the same error as haxe git...

**Comment by nadako** [comment]
Yeah, it seems that `classPaths` is actually a filter to look only inside specified classpaths (of all available with `-cp`).

**Comment by andyli** [comment]
Found that the `classPaths` argument was added in 73687545f0ab1eb6c47abf14779aa21139dbfd39 (3 years ago!).
So, what's that `classPaths` used for, @fponticelli?

**Comment by Simn** [comment]
I don't think we have to take any action here right now.

**Comment by fponticelli** [comment]
I updated the documentation in the PR. Just want to point out that I didn't write that documentation :)
