### ISSUE TITLE
JSON stringify inconsistency on Flash

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/haxe#3823]
The native Flash haxe.Json.stringify function doesn't seem to work correctly.

Given a map:

    var myMap:Map<String, Dynamic> = ["field1" => "something", "field2" => true];

`Json.stringify(myMap)` on flash returns `{"h":"Dictionary"}`

When compiling with -D haxeJSON, it returns the correct value of `{"field1":"something","field2":true}`

Simple solution is to use -D haxeJSON, but I understand this might be slower?

**Comment by Simn** [comment]
If you use the native JSON operation you get a native representation. I don't understand what else you expect to get from that or what we could possibly do about it. The Haxe version only works incidentally because it uses Reflect.fields on the value, which is not guaranteed to work for classes.

**Comment by bendmorris** [comment]
>I don't understand what else you expect from that

Well I certainly don't expect to get `{"h":"Dictionary"}` (an exception would be better) but if you need to use -D haxeJSON to get anonymous object serialization then that's understandable.

**Comment by nadako** [comment]
`haxeJSON` enables haxe json implementation that supports **serializing** a couple of arbitrary classes, like `StringMap`, but normally JSON objects are parsed as anonymous structures in haxe and one should use structures to serialize to json objects. If you need a handy dynamic mapping based on structures, you can try using this abstract: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/DynamicAccess.hx (it's currently available in git haxe, but i think it will work on 3.1.3 as well).

**Comment by bendmorris** [comment]
@nadako that is very useful, thanks a lot. I'll give it a try.
