### ISSUE TITLE
Old client/server example does not work on Java

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3831]
http://old.haxe.org/doc/neko/client_server

Compiling that through java kills the server with `Exception in thread "main" java.lang.NullPointerException` as soon as a client connects.

**Comment by nadako** [comment]
@waneck please review the fix. the example seems to work, but I'm not really familiar with java API so i may have done something wrong.

**Comment by waneck** [comment]
Seems fine! Thanks
