### ISSUE TITLE
Member initialization on dynamic target

### ISSUE THREAD

**Issue by yanhick** [HaxeFoundation/haxe#3835]
Hi,
I'm working on making a large codebase compiled to cpp work for js and the lack of member initialization is causing a lot of small issues.

I understand that this choice is documented and that this is a compromise made for speed for both dynamic and static targets.

I'm wondering:
* is there a compiler option to get warning/errors for missing initialization ?
* else would this be a useful feature to implement ?

Thanks

**Comment by Simn** [comment]
What "member initialization" are you talking about?

**Comment by yanhick** [comment]
Sorry, I meant class member intialization.

Basically if I have the following class:

```
class Main {
    var foo:Int;
}
```

If I target cpp, foo will have the value 0. If I target js, it will be null.

**Comment by fponticelli** [comment]
It would be nice to have a switch (-D strict ?) to make dynamic generators
act like static ones ... I have faced that issue myself and it can be quite
annoying.

Il giorno Tue Feb 03 2015 at 12:56:50 PM Yannick Dominguez <
notifications@github.com> ha scritto:

**Comment by nadako** [comment]
I remember someone on the haxelang said that it's actually better on modern js runtimes to initialize all variables/fields, so we may want to review our policy regarding that. That could be really great to have consistent default values.

We should start with measuring performance on current haxe targets.

**Comment by nadako** [comment]
@yanhick as for original issue, I think one could implement an `onGenerate` macros that checks whether all fields are initialized.

**Comment by ncannasse** [comment]
I don't think we should enable it globally because some libraries (including std) might expect it to be null. I guess the best in your case is to write a macro that adds = 0 initializers for all Int and Floats in the packages related to your application.

You can do that at compiletime, or just do a check and tell the user to fix it, or make a regexp that will do it for you, etc.

**Comment by yanhick** [comment]
@nadako, @ncannasse Thanks, I will try with a macro first to see what it does to our build time.
