### ISSUE TITLE
Metadata on type parameter declarations?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3836]
```
class Array<@:specialized T>
```

Would it be okay to add that? Type parameters are `tclass` already anyway, so it's only a matter of allowing to parse metadata in this place.

I have a use case for this in genc, but we can also use it to make our `@:multiType(K)` restriction on `Map` less clunky. There might also be interesting options with regards to variance adjustments on abstracts.

**Comment by nadako** [comment]
One could argue that you can use some special abstract like `Specialized<T>` for that, but it's much more annoying to work with than a simple metadata. And it could indeed be useful for variance settings similar to C# `in`/`out`, so I'm all for it!

It would be also useful to add support for metadata for function arguments (e.g. `function some(@:out value:Int)`)

**Comment by Simn** [comment]
Assigning for decision.

**Comment by Simn** [comment]
I'll just implement this because I need it for other things too.
