### ISSUE TITLE
Support explicit covariance

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3837]
I think we could support explicit covariance using type parameter metadata proposed in #3836, similar to how it's done in C#, for example:

``` haxe
interface IEnumerator<@:out T> {
    function getNext():T;
}

class A {}
class B extends A {}

class Enumerator_B implements IEnumerator<B> {
    public function new() {}
    public function getNext():B return null;
}

class Main {
    static function main() {
        var en:IEnumerator<A> = new Enumerator_B();
    }
}
```

Enforcing covariance rules should be quite easy - I think it's enough to check that `@:out T` is only used as a return value or a read-only property, as for extends/implements, just check that the type param in the extending class has the same `@:out` modifier as in the one it extends.

PS: in C# there's also contravariant `in` modifier we could probably support.

Thoughts @waneck @ncannasse @Simn?

**Comment by ncannasse** [comment]
Explicit variance is unsound, I don't think we should allow it

**Comment by ncannasse** [comment]
Oh, you want to enforce it ? I had this in Haxe a long time ago (in 1.x) but got rid of it because it was causing more problems that it solves

**Comment by Simn** [comment]
It wouldn't really work anyway due to the way we handle type parameter application. By the time we unify all the compiler sees are the applied types so we would have to do some stunts to relay the variance information.

**Comment by nadako** [comment]
I don't know, it works quite well for C# (invariance by default and explicit (and checked) co/contra-variance), tho they only allow it for interfaces, not sure why. It is a powerful typing tool, so I'd still like to see it in haxe. As for param application, i guess we could wrap params in special `Out<T>`,`In<T>` abstracts, as you suggested. It's not easy for sure, but I think we could at least consider it.

**Comment by Simn** [comment]
I'm gonna be the ass who says "no" on this one.

**Comment by back2dos** [comment]
I'm gonna be the ass who asks "why though?" (mostly out of curiosity), because it works just fine on anonymous types: https://try.haxe.org/#C3E38
