### ISSUE TITLE
Expression style macros in Haxe?

### ISSUE THREAD

**Issue by kkirby** [HaxeFoundation/haxe#3841]
Hello.

I've skimmed through the documentation and I wasn't able to find what I needed. Does Haxe have support for expression macros? From what I can tell it does not, and only supports call style macros.

What I mean by expression macros would be like being able to define custom syntax or operators.

Lastly, other than a Google search, where can I find some good macro examples?

Thanks,
Kyle

**Comment by Simn** [comment]
You can work some magic with build macros, but in the end all syntax has to make it through Haxe's parser. That's a conscious limitation.

**Comment by nadako** [comment]
If you need completely non-haxe syntax, you can probably hack something up like this https://github.com/andyli/CommentString, parse it and build `Expr`s yourself, but I doubt it worth it.

**Comment by kkirby** [comment]
Okay, thanks for the prompt responses!
