### ISSUE TITLE
unbound variable with -D analyzer

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3844]
extracted from generated nape code:
```haxe
typedef A = {f: A}

class Main {
    static function main() {
        var n:A = null;
        do n = n.f while (n!=null && (n!=null || n!=null));
    }
}
```

**Comment by nadako** [comment]
Note that the message seems to come not from the analyzer but from the SWF generator as it only reproduces on `-swf` target.

**Comment by ProG4mr** [comment]
Hi, i have a similar problem, i have code in separate macros, and i get a similar error:

```haxe
switch (fn.expr.expr) {
	case EBlock(exprs):
		exprs.unshift(macro {
			var __from__ = $variableRef;
		});
	case _:
}
```

and later a recursive function adds more code:
```haxe
macro {
        pack.MyClass.myFunc(this, untyped __from__); 
	return $e;
}
```

On cpp, neko and Js targets this works fine, if i use -swf i get: unbounded variable __from__.

Funny thing is if i use -as3 instead, it generates the right code.

Should i create a quick example?

**Comment by nadako** [comment]
Sure! :)

**Comment by ProG4mr** [comment]
Okay sorry if its not the most simplified example, I'm not very comfortable with macros.. this example reproduces the bug easily, its the same variable defined in one macro and set in other using `untyped`, let me know if you can confirm the bug, here only -swf target complains.

http://pastebin.com/qZxj8srj

Thanks!
