### ISSUE TITLE
Database ADO.net Error: File "ilMetaReader.ml", line 281, characters 36-42: Assertion failed error 0x2

### ISSUE THREAD

**Issue by Morvalyn** [HaxeFoundation/haxe#3847]
<a href="http://speedy.sh/JnfwS/System.Data.dll">v4.0 System.Data.dll Reference Assemblies</a>
<a href="http://speedy.sh/2N74C/System.Data.dll">v4.5 System.Data.dll Reference Assumblies</a>

Haxe version: 2015-02-09 19:30         4044670        haxe_2015-02-09_development_a696542.tar.gz

when running haxelib build.hxml
```
-main Main
-cs Main.cs
#for ado.net
-net-lib "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Data.dll"
```

**Comment by waneck** [comment]
This should be fixed now. Note however that you will need some other -net-lib definitions to make this work - as System.Transactions.Transaction is not referenced by this same assembly
