### ISSUE TITLE
This expression may be invalid warning for valid code

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3850]
```haxe
abstract A(String) {}

class Main {
    static function main() {
        var a:Array<A> = [];
        f(a); // This expression may be invalid
    }

    static function f<T>(o:Array<T>):T throw false;
}
```

**Comment by waneck** [comment]
I've added a proposed fix, but it follows all non-coretype abstracts, which may lead to following abstracts that shouldn't be followed. I'll think about a better fix later

**Comment by Simn** [comment]
Is this (still) a real issue?

**Comment by nadako** [comment]
It still reproduces here :(

**Comment by Simn** [comment]
Yes but is this "oh god the world is ending" or "well this is a bit annoying but other than that..." kind?

**Comment by nadako** [comment]
Seems to be the second one. But it's still confusing (especially for new haxers) that valid code is labeled invalid :-/

**Comment by Simn** [comment]
Do you want to look into it? Because I kind of need Caue to deal with his other issues that seem more important right now. He tends to go bikeshedding with things like this... :)

**Comment by nadako** [comment]
I can't right now, unfortunately.

**Comment by nadako** [comment]
It's not that important though, so let's deal with more critical ones.
