### ISSUE TITLE
Access to @:overload from macro

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#3851]
In my situation (I want to generate extern classes by haxe source code), I need to access @:overload metas from macro.

Cauê Waneck 	wrote:
The @:overload meta gets turned into `cf_overloads` on the compiler side, which doesn't seem to be available at the Type.ClassField definition.

**Comment by Blank101** [comment]
FYI I raised this issue a few months ago: https://github.com/HaxeFoundation/haxe/issues/3460
