### ISSUE TITLE
Weird UInt division behaviour (Flash)

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#3852]
```
var a = 10;
var b:UInt = 100;
trace(a / b); // 10 / 100 = 10, wow!
```
In 47bbd1e3ee4bc94899339ca474936106c6fb98a0 quite a lot of ops have been defined, but there's only `UInt / Int` not `Int / UInt`, maybe that's why it's turned around? Don't know...

**Comment by ncannasse** [comment]
In all cases, abstracts should not reverse the order of parameters for division

**Comment by mockey** [comment]
Apparently they do in this case somehow...

**Comment by nadako** [comment]
Oh wow, someone seems to love copy-paste too much and added `@:commutative` flags to non-commutative methods.
