### ISSUE TITLE
List.remove( object.method ) failed on neko target

### ISSUE THREAD

**Issue by cruxblack** [HaxeFoundation/haxe#3853]
```haxe
class SomeClass
{
	public function new() {}
	public function method() trace( "> updating" );
}

function test()
{
	var list = new List<Void->Void>();
	var obj = new SomeClass();
	//var method = obj.method;
	
	list.push( obj.method );
	//list.push( method );
	
	trace( "removal " + list.remove( obj.method ) );	// removal false
	//trace( "removal " + list.remove( method ) );		// removal works if obj.method is assigned to a variable first
}
```

**Comment by cruxblack** [comment]
Possibly related to this issue #3854

**Comment by ncannasse** [comment]
Functions are not guaranteed to be == , see #3854

**Comment by cruxblack** [comment]
@ncannasse
I see, thanks for clarifying
Then, for the case above, in order to remove the function from the list, I would need to do something like this?

```haxe
typedef Function = Void->Void;

function removeFx( fx:Function, list:List<Function> ) :Bool
{
	for( val in list )
	{
		if( Reflect.compareMethods( fx, val ) )
		{
			list.remove( val );
			return true;
		}
	}
	
	return false;
}
```

Would that result in the list being traversed twice, first inside the for-loop of removeFx(), and then again in list.remove()?

As an alternative, is it possible to extend the List class and then override its functions so that any comparison done when searching an element is done by Reflect.compareMethods() instead of ==?

**Comment by ncannasse** [comment]
You should be able to override list.remove to implement the way you want.
