### ISSUE TITLE
[js] enum abstract as key for Map gives runtime error 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#3855]
When I use an abstract enum as key for a Map, I get this runtime error:  
 `Uncaught TypeError: Cannot assign to read only property '__id__' of home, http://try.haxe.org/program/848ec/run?r=0.644512897124514,line:42`

Is this a bug or am I doing something wrong?
```
    class Test {
        static function main() {
            new Test();
        }
        
        function new()
        {
            var scenesClassesByName = new Map<SceneNames, Class<Dynamic>>();
            scenesClassesByName.set(SceneNames.HOME, HomeScene);
            scenesClassesByName.set(SceneNames.GAME, GameScene);
        }
    }
    
    @:enum 
    abstract SceneNames(String) to String
    {
    	var HOME = "home";
    	var GAME = "game";
    }
    
    class HomeScene{}
    class GameScene{}
```
Demo: http://try.haxe.org/#848ec

I found that if I use `new Map<String, Class<Dynamic>>();` everything works as expected.

I use Haxe 3.1.3, the error appears in Chrome 40.0.2214111m. It does not seem to happen in other browsers.

**Comment by Simn** [comment]
Our generated code is fine so this must be some chrome issue.

**Comment by Simn** [comment]
Actually it might be picking the wrong map type.

**Comment by Simn** [comment]
... but that has already been fixed on latest.
