### ISSUE TITLE
Update RecordMacros.hx to use postgres/mysql compatible limit queries

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#3858]
It looks like RecordMacros.hx uses a MySql-specific form of specifying limit queries.   A change in that file will enable postgres limit queries to work equivalently to mysql queries.

More details over here: https://github.com/jdonaldson/postgrehx/issues/8

**Comment by Simn** [comment]
Moving to 3.3 as it doesn't look that urgent.

**Comment by waneck** [comment]
Closing because record macros is not part of the Haxe standard library anymore. Feel free to submit a PR to https://github.com/HaxeFoundation/record-macros , or reopen that issue there
