### ISSUE TITLE
-cmd and output

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3859]
This bug is quite old (i think i experienced it since i started using haxe), but it's still very annoying and @Dvergar just reminded me about it, so I decided to create an issue for it.

The following code most likely will not trace full loop but will terminate at random moment:

Main.hx

``` haxe
class Main {
    static function main() {
        for (i in 0...256) trace(i);
    }
}
```

build.hxml

```
-main Main
-neko main.n
-cmd neko main.n
```

This is not specific to neko as it can be reproduced with node or whatever.
The problems seems to be related to the `run_command` function https://github.com/HaxeFoundation/haxe/blob/85545163444c26eec0e6e1c4020532efc4148947/main.ml#L440, but the flushes are there (in `com.print`) so i don't know what's the reason.

**Comment by ncannasse** [comment]
It's due to problems with buffering on the reading side, I started backporting the nekovm process API in order to fix this in #3763

**Comment by nadako** [comment]
But isn't `run_command` using only standard ocaml unix stuff? how is it related to nekovm?

**Comment by ncannasse** [comment]
It's not related to nekovm at all : because we use ocaml unix stuff, we're not able to correctly capture the process output and print it back, so we need to have access to other C primitives which are provided by the process API

**Comment by nadako** [comment]
why me? i have no idea what to do with it.
