### ISSUE TITLE
Std.is reports Enum as System.Int32 on C#

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#3860]
```haxe
enum Color { Red; Green; Blue; }

var c = Red;
Std.is(c, Color) // True
Std.is(c, Int) // True!
```

On all other targets, testing c for Int returns false.

**Comment by nadako** [comment]
this will be fixed when generation of native c# enums for "flat" enums is disabled.

**Comment by ciscoheat** [comment]
Good to know, thanks!

**Comment by ousado** [comment]
Why is this a bug? It feels much more like a feature.to me

**Comment by Simn** [comment]
I'm also a bit sad this is considered a bug. After all we do not define how enum values are represented at run-time.

**Comment by waneck** [comment]
There are many annoying subjects relating to Enums being value types - specially with regards to nullability.
For genc, we could consider the '0' a special 'null', so we don't have this problem. Also `Std.is` `Int` in this case is a C# particularity; we could make it so it returns false - even though its underlying type is an Int.

**Comment by ncannasse** [comment]
The problem here is that this optimization prevent any kind of reflection such as Type.enumConstruct, Type.getEnum, etc.  Also, comparing two pointers is the same as comparing an integer so it shouldn't be much an optimization as long as you don't allocate instances

**Comment by waneck** [comment]
It is an optimization, because you normally don't compare enums with `==`; Rather you switch on it. In order to support switch, we'd need to dereference the enum to its value.

If you have control over how to box instances, `Type.enumConstruct` and `Type.getEnum` can all be supported

**Comment by ncannasse** [comment]
I understand, didn't thought about auto boxing :)

**Comment by waneck** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/90ddbdfa14f4178c08085f87fa0d74df920cb385
