### ISSUE TITLE
no "unitialized variable use" error with -D analyzer

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3861]
```haxe
class Main {
    static function main() {
        var a;
        (function() a)();
    }
}
```
This gives an error `Local variable a used without being initialized` without `-D analyzer` but compiles silently with it.

**Comment by Simn** [comment]
I don't think that should be an error anyway. This code is perfectly fine:

```
class Main {
	static function main() {
		var a;
		var b = function() return a;
		a = 2;
		trace(b());
	}
}
```

There's still a problem with local DCE removing the assignment.
