### ISSUE TITLE
Map of generic parameter fails

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxe#3863]
```
class MapOf<T>
{
   public var items:Map<T,Int>;
   public function new() items = new Map<T,Int>();
}


class Test
{
   public static function main() new MapOf<Test>();
}
```
Generates an error: ```Abstract Map has no @:to function that accepts IMap<MapOf.T, Int>```

**Comment by Simn** [comment]
The error message is a bit strange, but that example should fail. The problem is that the compiler cannot figure out what Map specialization to use because `T` is an unconstrained type parameter. You can constrain it to e.g. `{}` to make it use ObjectMap.

**Comment by ncannasse** [comment]
Maybe we could improve the error message in case one of the parameter is a type parameter ? (tipping about @:generic usage)

**Comment by Simn** [comment]
You actually need both `@:generic` and `@:remove` for this to work. We don't remove the base versions of `@:generic` classes unless it has a constructor constraint so it would still give an error.

**Comment by hughsando** [comment]
Yes, if I constrain it ```class MapOf<T:{}>``` it works, and I can see it can't be made to work without something like the ```Array<Dynamic>``` for maps.
