### ISSUE TITLE
JS: Suggestion: Do not generate single-use variables for enum' cases

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#3866]
Currently, if you have an enum/ADT with a few constructors, such as
```haxe
enum Some {
    one(s1:String);
    pair(s1:String, s2:String);
    triad(s1:String, s2:String, s3:String);
}
```
and then you do some matching via `switch` on it,
```haxe
static function verifySome(v:Some):Bool {
    return switch (v) {
    case one(s1): verify(s1);
    case pair(s1, s2): verify(s1) && verify(s2);
    case triad(s1, s2, s3): verify(s1) && verify(s2) && verify(s3);
    }
}
```
code of the [following kind](http://try.haxe.org/#A2CA9) is generated on the JS target:
```haxe
Test.verifySome = function(v) {
	switch(v[1]) {
	case 0:
		var s1 = v[2];
		return Test.verify(s1);
	case 1:
		var s2 = v[3];
		var s11 = v[2];
		return Test.verify(s11) && Test.verify(s2);
	case 2:
		var s3 = v[4];
		var s21 = v[3];
		var s12 = v[2];
		return Test.verify(s12) && Test.verify(s21) && Test.verify(s3);
	}
};
```
Which is, generally, OK, although not necessarily. On multiple occasions (depending on code, obviously), an enum argument may only be used once, if at all (e.g last two cases - short circuiting). It would seem rather logical to not generate variables in such situations and instead insert `value[i]` in their place of usage, both for space and [minimal] performance concerns.

Curiously, while Closure will detect and optimize the first case correctly, it assumes that there might be some reason behind assigning intermediate variables in the other two, and leaves them be, even if the arguments could have not been read at all.

Perhaps, ultimately, the condition for not creating a variable declaration would be the fact of argument being used 1 or less times in all code branches inside a case, but simply checking if it's used one or less times total would be decent too.

**Comment by nadako** [comment]
There's a branch with TLocal propagation that will most likely handle that, right, @Simn ?

**Comment by Simn** [comment]
Yes, I don't want to make any specific optimizations here.
