### ISSUE TITLE
[cpp] @:headerCode metadata and abstract types

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/haxe#3867]
@:headerCode and other cpp metadata do not work for abstract types. Is this by design, or just something that has not yet been addressed?

Duplicate of https://github.com/HaxeFoundation/hxcpp/issues/114 but seems more appropriate here, if I'm not mistaken.

**Comment by hughsando** [comment]
headerCode for abstracts will now get pulled into the implementation file now.
