### ISSUE TITLE
Bytes endianness

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3868]
Makes sure we specify that endianess in Bytes is the same as CPU default.

**Comment by ncannasse** [comment]
@andyli do we have any way to unit test on a big endian CPU ? (ARM, PowerPC, SPARC etc.)

**Comment by andyli** [comment]
From a quick search, [this post](http://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html) suggests that it can be done by running a emulator inside Travis... although it could be pretty slow.

**Comment by ncannasse** [comment]
@andyli I'm quite interested in having this running. If it's too slow we could deactivate it after we have all the tests properly passing.

**Comment by Simn** [comment]
It's a bit late to take any action for 3.2.
