### ISSUE TITLE
compile-time constant string concatination optimization

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3871]
Someone on the slack chat noticed that haxe doesn't optimize constant string concatination, despite that @ncannasse talked about it at GameDuell TechTalk, hence the issue :wink:

``` haxe
class Main {
    static function main() {
        trace("hello" + "world");
    }
}
```

generates

``` js
console.log("hello" + "world");
```

I don't see a string case here https://github.com/HaxeFoundation/haxe/blob/development/optimizer.ml#L958, so I believe it was never implemented.

**Comment by nadako** [comment]
note that this may be useful with our new const propagation

**Comment by ncannasse** [comment]
I had an issue some long time ago about this because it was creating too many unique strings when some debug information was on (maybe when emulating callstack on flash8?). We had a lot of "FileName.hx" + "lineNumber" or something of this kind, and of course this creating a lot of unique combinations. But that's quite a specific case, maybe it's no longer an issue.

**Comment by Simn** [comment]
We were discussing this before and your arguments against it (constant pool spam) made sense to me at the time. The implementation went to `make_constant_expression` with a `concat_strings` argument because I needed it for the pattern matcher.

**Comment by ncannasse** [comment]
I think we should not explode constant pool.

**Comment by back2dos** [comment]
Seriously? Closure does this even in simple mode.

Also, the argument is speculative. If you have `"hello world"` in the constant pool, then not optimizing `"hello " + "world"` is what's going to increase it. The only person who can actually decide whether the optimization makes sense for a particular piece of code is the programmer responsible for it. They should be given control over it. Expression level metadata provides the necessary granularity for it.
