### ISSUE TITLE
Null<UInt> when set to null, has value 0 instead.

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#3875]
see: http://try.haxe.org/#20D35
if i set null as default value of a Null<UInt> variable, and i trace its value, i got 0 instead of null.

**Comment by nadako** [comment]
It is actually null, but is traced as 0 because of incorrect string conversion.

**Comment by sebpatu** [comment]
cool, so the trace string conversion could be fixed?

**Comment by nadako** [comment]
sure :-)

**Comment by Simn** [comment]
This is the same as #3877.
