### ISSUE TITLE
[python] typed kwargs support for extern methods

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3879]
As we talked on #haxe-dev, it would be nice to have some kind of *typed kwargs* thing that would allow us to define this:

```haxe
extern function doStuff(arg1:Int, ?opts:KwArgs<{?arg2:String, ?arg3:Bool}>):Void;
```
and then do
```haxe
doStuff(10, {arg2: "hello"});
```
which would generate
```python
doStuff(10, arg2="hello")
```

This is particularily useful for extern methods which have tons of optional arguments and are meant to be used by specifying one or two of them, like for example this one from the recent Sublime Text release:
```python
def show_popup(self, content, flags = HTML, location = -1, max_width = 320, max_height = 240, on_navigate = None, on_hide = None):
```

**Comment by frabbit** [comment]
closed by db98dbb4f8ba1fffd3f5e526147f57ecc2804ac0
