### ISSUE TITLE
[js] break from switch using labeled breaks

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3883]
Currently, JS target generates a try/catch with `throw "__break__"`  to support breaking the loop from a switch case, which is quite ugly, considering that JS supports labeled breaks (see https://msdn.microsoft.com/en-us/library/ie/3fhdxafb(v=vs.94).aspx).

So instead of try/catch wrapping we could mark a loop with a label and use labeled break instead. That's exactly what @waneck is doing in Java target and there's a filter in `gencommon` for that. I checked out that filter and it seems that it could be easily factored out of `gencommon` into `filters` or something as its code doesn't depend on any other part of `gencommon`.

So the code is already there, the only question is how to properly add that filter without making second `gencommon` :wink: which raises (again) a general question of how to handle target-specific filters that would be very useful to have (for example we have some transformations in `genpy` that should really be done before DCE).

**Comment by waneck** [comment]
It would be nice to add support for labeled break/continue statements on the typed ast - which may only be used by the Haxe compiler internally. This would allow some great optimization opportunities - for example when dealing with tail recursion optimization or pattern matching.

Of all the targets we currently support, here's the outlook of support for this feature:
 * js, java, php : supports labeled loops
 * c#, c++, neko, flash : supports goto
 * python : doesn't support ( https://www.python.org/dev/peps/pep-3136/ )

As for python, we could either emulate this with variables (e.g. `if (outer_loop_breaked) break;`), or we could go ahead and add `pf_labeled_loop` to check if certain optimizations can be performed.

**Comment by nadako** [comment]
Why don't we go further and just support labeled break/continue in the syntax as well :-P
