### ISSUE TITLE
StdTypes.Void != Void

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#3884]
found the following issue:

```
class Test {
  static function main () {
    var x : StdTypes.Void -> Int = function () return 1; 
  }
}
```

fails to compile with: Void -> Int should be (Void) -> Int

**Comment by frabbit** [comment]
i guess StdTypes.Void is added as an argument to the TFun instead of having an empty argument list.

**Comment by nadako** [comment]
I wonder if using `StdTypes` from user code should be even allowed.

**Comment by nadako** [comment]
other checks for `Void` are also failing when accessed via `StdTypes`, e.g.:

```haxe
typedef A = {
    f:StdTypes.Void
}
```

**Comment by andyli** [comment]
A similar example:
```haxe
typedef VOID = Void;

class Test {
  static function main () {
    var x : VOID -> Int = function () return 1; //Void -> Int should be VOID -> Int
  }
}
```

To me it is the `Void` checking being done wrong. `Void` is now a bit exceptional that it can't be indirectly referenced, but all other top-level types like `Int`, `String` can.

**Comment by ncannasse** [comment]
Yes we are checking the "Void" type declaration, and sadly at this step I don't think we can follow the typedefs yet

**Comment by Simn** [comment]
Indeed there are several places where we check for "Void" on a CTPath or similar. I acknowledge the issue but I don't think it's worth spending time on right now.
