### ISSUE TITLE
Proposal : Vector.copy() and friends

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#3887]
Hi,

Since vector is gaining traction because its the theoretical performance weapon of choice, we should stuff the vector a class a little.

I propose we add : 

Vector.copy
Vector.map
Vector.iter
Vector.sort

and ensure an inline function callback get adequetely inlined other those.

Thanks !

**Comment by ncannasse** [comment]
PR please :)

**Comment by delahee** [comment]
cool ! i'll schedule it !

**Comment by delahee** [comment]
Pr done !
