### ISSUE TITLE
@:jsRequire does not work with `-dce no`

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#3890]
as per subject `-dce no` removes `require()` from the output.

Example `build.hxml`:

```hxml
-js out.js
-main Main
-dce no
```

Example `Main.hx`:

```haxe
class Main {
  static function main() {
    trace(FS.statSync("out.js"));
  }
}

@:jsRequire("fs")
extern class FS {
  static function statSync(path : String) : Dynamic;
}
```

**Comment by nadako** [comment]
This should be fixed by https://github.com/HaxeFoundation/haxe/commit/ac002c6f7fee6be6c03e01008b13cfce22bfc14c
