### ISSUE TITLE
Issue with abstract inline toString

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3892]
```
abstract MyBool(Bool) {
	public inline function new(x:Bool) this = x;
	public inline function toString():String return "asString: " + this;
}

class Main {
	static function main() {
		var z = new MyBool(true);
		trace(z.toString()); // asString: asString: true
	}
}
```

```
	var z = true;
	console.log("asString: " + ("asString: " + (z == null?"null":"" + z)));
```

I think I know why that happens.

**Comment by Simn** [comment]
As I thought this is the usual `this` problem which also causes #2236, #3637 and #3713.

Here we first type the inline function which has KString + KBool:
`"asString: " + Std.string(this)`

After inlining we replace `this` with our outside variable `z`:
`"asString: " + Std.string(z)`

But `z` is typed as `MyBool`, not `Bool`. This causes the post-process check to call `z.toString()` again, leading to the observed output.

**Comment by ncannasse** [comment]
When we replace the variables in inline, should we not do an unsafe cast for "this" abstract to make sure it's correctly typed as the underlying type ?

**Comment by Simn** [comment]
That doesn't work when the this-variable is assigned to because `(cast this) = y` doesn't make any sense.
