### ISSUE TITLE
Nullability of haxe.Int64

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3894]
Our new Int64 is non-nullable on at least Java/C# because its underlying type there is not nullable. I think we should make it non-nullable on all targets.

Any opinions?

**Comment by ncannasse** [comment]
on all -statics- targets right ? I think that's the case in C++ since it's a struct. @hughsando does the struct gets initialized to 0 by default ? We might have a problem with Flash because we need to create an instance...

**Comment by Simn** [comment]
Right, and I think Flash is the only issue.

**Comment by ncannasse** [comment]
Different ways to fix it:

a) handle the null case in Int64 abstract API (flash only), considering it as 0
b) make sure member variables and uninitialized locals get set to Int64.zero static : could be done either in genswf9 or directly in our typer (analyser might optimize things out there)

**Comment by Simn** [comment]
Couldn't we just add `#if flash @:notNull #end` to Int64 and make sure that's respected for non-core-type abstracts too?

**Comment by Simn** [comment]
By the way @hughsando is the `static` flag available now or is hxcpp still using it?

**Comment by hughsando** [comment]
I changed the hxcpp version to "static_link" a while ago.
