### ISSUE TITLE
StringMap issues on PHP

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3898]
```
Issue3462.hx:30: true should be false
Issue3462.hx:30: true should be false
Issue3462.hx:63: true should be false
Issue3462.hx:63: true should be false
Issue3462.hx:63: true should be false
```

Both are indexOf checks on arrays so this might be something unrelated to StringMap itself. I don't think this is a regression.

**Comment by Simn** [comment]
Yay PHP...

```
import haxe.ds.StringMap;

class Main {
	static function main() {
		var d = new StringMap<Int>();
		var keys = ["a", "0"];
		for (i in 0...keys.length) {
			var k = keys[i];
			d.set(k, i);
		}
		for (k in d.keys()) {
			Sys.println(k);
			Sys.println(keys.indexOf(k));
		}
	}
}
```

The lookup for "a" works as intended but for "0" it returns -1.

**Comment by mockey** [comment]
It'a problem with the StringMap implementation. A key like "1" is auto-casted to 1 (int) in PHP.  Other types (float, bool) as well BTW:
http://php.net/manual/en/language.types.array.php
You need two arrays here (keys and values), like in ObjectMap.

**Comment by Simn** [comment]
You wouldn't be interested in sending a pull request by any chance? :)

**Comment by mockey** [comment]
I'll try later. Have to do some shopping now.
