### ISSUE TITLE
Enable js-flatten by default

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3903]
Are there any remaining issues with js-flatten? Is there any reason we wouldn't want it to be on by default in 3.2?

cc @nadako @andyli

**Comment by nadako** [comment]
I always add `js-es5` and `js-flatten` for production code (tho i'm only targeting node.js).

**Comment by Simn** [comment]
I think we should change this before someone gets the idea to `__js__` modify some package variable or something.

**Comment by nadako** [comment]
I think had enough issues regarding `@:native` and `js-flatten` fixed, so I believe they have tests that will run on saucelabs.

**Comment by ncannasse** [comment]
Accepted :)

**Comment by ncannasse** [comment]
@Simn please add -js-unflatten (or something else) to disable it explicitely

**Comment by andyli** [comment]
FYI, we have been testing `-D js-flatten` on node.js (See https://github.com/HaxeFoundation/haxe/blob/development/tests/RunCi.hx#L518-L521).

**Comment by Simn** [comment]
@aduros: Do you want to take care of it?

**Comment by aduros** [comment]
Can do.

**Comment by explorigin** [comment]
Note that in 3.1.3 -js-flatten breaks the Std library's jquery extern.  Using ```import jq.JQuery;``` inevitably puts 
```
var q = window.jQuery;
js.JQuery = q;
```

in the JS target.  But with js_flatten, ```var js = {}; js.Boot = {};``` is flattened to ``` var js_Boot = {};``` thus breaking the code above because ```js``` no longer exists.

**Comment by explorigin** [comment]
It's still broken when using http://lib.haxe.org/p/jquery

**Comment by nadako** [comment]
I think that was fixed in f16cb786a52de349967e73e710240d5277cd3d48. (on a side note - js.jQuery is another one i would like to see out of std library, as it's mostly outdated and there's a better alternative: https://github.com/andyli/jQueryExternForHaxe). Could we deprecate it maybe?

**Comment by Simn** [comment]
I'm all for it.

**Comment by explorigin** [comment]
Wow, didn't know about https://github.com/andyli/jQueryExternForHaxe Thanks

I don't see a problem removing jquery from Std. I'll file a separate bug for lib.haxe.org (searching for "jquery" does not yield "jqueryextern")

**Comment by ncannasse** [comment]
@nadako looks like you like deprecating :) We should upgrade it if there's a better alternative, for instance by asking @andyli to maintain the official js.JQuery

**Comment by Simn** [comment]
What's the point? We would just have an outdated version in the standard library shortly after each Haxe release.

**Comment by nadako** [comment]
It's not that I like deprecating stuff, it just bothers me to have a bunch of dead code that noone knows what to do with (or wants either). And by dead code I mean something that it's less likely to be used for any real job (when there are better alternatives) and thus not tested and maintained enough.

I don't know if jQuery is used much nowadays, but if it is, we could make andy's externs "official" and install them as a haxelib by default. That way we still have out-of-box jquery support and we can update not being tied by haxe releases.

Isn't that the best thing to do for something depending on third-party, like jQuery externs?

**Comment by andyli** [comment]
I have been observing around. The current status is kind of 50-50: some ppl use the bundled js.JQuery and some ppl use my jQueryExtern.

The major differences between the two that make them non-trivial to merge:
 1. jQueryExtern uses macros to build a "configurable" extern. The std lib favors to keep things simple.
 2. Different ways to workaround haxe/js differences (e.g. when same name being used for both instance and static methods).

Let me propose some haxe features to remove point 2. Eventually in the future I can make jQueryExtern to be fully compatible with the bundled js.JQuery, such that jQueryExtern would become a simple drop-in replacement to provide more updated signatures and additional functionality. And I will maintain both of them.
