### ISSUE TITLE
Context.getTypedExpr and inlined/macro call expressions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3906]
Consider the following example:
```haxe
class Main {
    static macro function test(e) {
        var te = haxe.macro.Context.typeExpr(e);
        return haxe.macro.Context.getTypedExpr(te);
    }

    static inline function inl() {
        untyped __js__("console.log('hello')");
    }

    static function main () {
        test(inl()); // Unknown identifier : __js__
    }
}
```
Because of `e` being inlined while typing, we get the `__js__` ECall with which we can't really return from a macro (because we'll be getting the unbound var error).

While the reason for this is quite clear, it really limits the use of `getTypedExpr`, especially in static extensions and abstract methods.

For `switch` expressions, we store original untyped AST in the `@:ast` TMeta which we then return for `getTypedExpr`, could we do the same thing for `TCall`? I think it makes sense for macros.

I actually have a good example where it breaks quite sadly (on JS) and it is from a real-world production code: https://gist.github.com/nadako/54f9cac9de1515746950, so I would very much like to see SOME solution for this.

Marking for 3.2 as I'd like this to get some attention.

**Comment by ncannasse** [comment]
If the expression is already typed, why not put a EUntyped before returning it ? what you're proposing seems overkill

**Comment by ncannasse** [comment]
@nadako or we could find a way to return a typed expression directly, but that's another story

**Comment by Simn** [comment]
... I was about to suggest the same thing. It shouldn't be too hard to do with some registry and an identifying EMeta.

I would like to deprecate getTypedExpr at some point because it's gonna get worse and worse the better we get about AST transformations.

**Comment by nadako** [comment]
The problem with returning `untyped` is that it completely disables analyzer for the function where the macro is used which is not really on an option :(

**Comment by nadako** [comment]
(maybe we could add some meta for the analyzer to ignore the untyped flag, i don't know)

**Comment by Simn** [comment]
Regardless of what we do here we should communicate the untyped state to the typed AST. We can try for a TMeta-based approach but I'm still worried about all the patterns that might fail to match with it.

**Comment by andyli** [comment]
Related issue: #3739
I think having "a way to return a typed expression directly" as suggested by @ncannasse is the most promising solution to all these problems.

**Comment by nadako** [comment]
Yeah, @Simn just gave me an idea how to implement this and I'm trying it right now.
