### ISSUE TITLE
field name completion for structures

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3907]
I just got an idea for new completion type that could be VERY useful in some cases, like when a function expects an options structure, like this:
```haxe
class Main {
    static function doStuff(options:{a:Float, b:String}) {}

    static function main () {
        doStuff({|
    }
}
```
This could complete `a` and `b`.

I believe many JS libs use options objects for function arguments (also I saw this pattern in Luxe library) so completing structure fields here would be great help.

One issue I could see right now is that curly braces also mean block, so it's ambigous. But we don't have any completion here in "normal" (not toplevel) mode right now, so I think it's fair to assume structure field name completion if the expected type is a structure.

@Simn what do you think, is it crazy tricky to implement?

**Comment by Simn** [comment]
Looks doable.

**Comment by nadako** [comment]
Looks borked.
