### ISSUE TITLE
Native XML class stuff

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3910]
Before I forget about it, Nicolas wanted to still have access to the previous native XML classes so I'll have to restore them along with their special handling in the compiler. Argh.

**Comment by Simn** [comment]
@ncannasse: There are some occurrences of `(["flash"],"FlashXml__")` in genswf9 which are all rewritten to `[],"Xml"`. You wouldn't remember what that's about?

**Comment by ncannasse** [comment]
Might be old thing
