### ISSUE TITLE
3.2; js; Modern APIs potentially missing from extern generator

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#3913]
As discussed with @aduros, 
Only few I have run into so far  :

- PointerLock API ([CR](https://dvcs.w3.org/hg/pointerlock/raw-file/default/index.html))
- Fullscreen API ([LS](https://fullscreen.spec.whatwg.org/))
- ~~Gamepad API~~ ([WD](https://dvcs.w3.org/hg/gamepad/raw-file/default/gamepad.html))

**Comment by anissen** [comment]
Vibration API ([TR](http://www.w3.org/TR/vibration/))?

**Comment by aduros** [comment]
Thanks for the feedback, I'll get those in there.

Gamepad API is already available: https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/Navigator.hx#L57

So is Vibration: https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/Navigator.hx#L53

**Comment by ncannasse** [comment]
I'm glad we can announce we added Vibration to Haxe 3.2

**Comment by waneck** [comment]
After a brief talk with @underscorediscovery , it seems that this is a regression from 3.1.3 - I'm adding the appropriate label
