### ISSUE TITLE
tvar identity

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3917]
We have to preserve it when passing it through the macro encoder because it has mutable state.

The question is how.

**Comment by ncannasse** [comment]
I guess that would mean storing a map of vars in the common context (the one used for typing, NOT the macro one !) and populate it in encode_texpr, and fetch it back from decode_texpr

**Comment by ncannasse** [comment]
another option is to have an extra field for TVar (macro side) that will keep the original tvar (ocaml one) wrapped as an abstract. That would mean making all TVar fields read-only, but would work well

**Comment by ncannasse** [comment]
I prefer the second one

**Comment by Simn** [comment]
Like this?

**Comment by ncannasse** [comment]
that's the idea. I'm glad I've made myself understood for once ;) now let's revert v_id accesses for better speed (one less indirection).

**Comment by Simn** [comment]
@nadako: Please check your codebase.

**Comment by nadako** [comment]
Looks good!
