### ISSUE TITLE
http://haxe.org and http://lib.haxe.org are down

### ISSUE THREAD

**Issue by tkawachi** [HaxeFoundation/haxe#3919]
I'm not sure where to report. Please let me know if here is not a good place to report.

Currently haxe.org and lib.haxe.org are down. I have a issue to install haxelib. Please help.

**Comment by jasononeil** [comment]
Thanks for letting us know.  I restarted apache and mod_tora on the VPS and it's back up.  

In terms of the best place to report: probably the mailing list is slightly better, https://groups.google.com/forum/?hl=en#!forum/haxelang

**Comment by tkawachi** [comment]
Thank you!

**Comment by Simn** [comment]
Does anyone watch this or get automatic notifications about server problems? Yesterday the website was very sluggish all day.

**Comment by ncannasse** [comment]
Would be nice to have an alert service indeed, and also be able to measure access time from various places in the world
