### ISSUE TITLE
Remove flash8 support?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3922]
I think it's time to remove support for Flash 8. We removed it from Travis CI and I suppose it's now broken in so many ways that noone would be willing to invest their time on fixing/supporting that target.

**Comment by ncannasse** [comment]
We will still keep it a bit more for backward compatibility, it's not like it takes us time to maintain.

**Comment by nadako** [comment]
the problem is that we don't even know whether it's completely broken or just a little, so what backward compatibility can we talk about?

**Comment by waneck** [comment]
Yeah, I don't even know if a `trace("Hello, World")` works there. From my previous experience, I have a feeling that it doesn't.

**Comment by nadako** [comment]
the `unit8.swf` generated from our tests doesn't even loads for me

**Comment by waneck** [comment]
Yep. `trace("Hello, World")` doesn't work anymore. It traces `undefined` on the canvas

**Comment by Simn** [comment]
+1 for removal. That target has been sitting on my shoulder like a bad conscience for a while now.

**Comment by Justinfront** [comment]
would 4.0 not be a better time to remove all flash8 support.

**Comment by Simn** [comment]
For me the point is that we basically have removed it already, so it's just a matter of being honest about it.

**Comment by nadako** [comment]
I agree. For someone who is working on the compiler, flash8 related stuff is just a pile of dead code. And also we lie to users that we support flash8 when we don't.

**Comment by Justinfront** [comment]
Do we know which version of Haxe worked reasonably with flash8?  I think if it's officially discontinued then some docs somewhere should have links to a version that does work.

**Comment by ncannasse** [comment]
What does @delahee thinks about it ? (I guess MotionTwin has the most Flash8/Haxe codebase)

**Comment by nadako** [comment]
ping @delahee

**Comment by delahee** [comment]
I ll get an answer with the team asap.

**Comment by delahee** [comment]
@simn @ncannasse Fine for us, let's butcher it !

2015-03-10 8:07 GMT+01:00 David Elahee <david.elahee@gmail.com>:

> I ll get an answer with the team asap.
> Le 10 mars 2015 00:15, "Dan Korostelev" <notifications@github.com> a
> écrit :
>
>> ping @delahee <https://github.com/delahee>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/HaxeFoundation/haxe/issues/3922#issuecomment-77964923>
>> .
>>
>


-- 
David Elahee

**Comment by nadako** [comment]
Yay! I'll update my branch so it passes tests.

**Comment by Simn** [comment]
The deed has been done.
