### ISSUE TITLE
toplevel completion doesn't work on unclosed braces/parens

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3923]
This gives `No completion point was found` error, however if we close the curly brace, it works.

```haxe
class Main { static function main() {
```
```
haxe --display Main.hx@37@toplevel
```

**Comment by Simn** [comment]
Top-level completion currently requires a sane block structure which is a conscious limitation. We can look into improving this later but it's not a 3.2 priority for me.

**Comment by nadako** [comment]
I see. Well okay then.
