### ISSUE TITLE
Various errors when using haxelib from 3.1.3 in Ubuntu 14.04.2

### ISSUE THREAD

**Issue by baraujo** [HaxeFoundation/haxe#3924]
Steps:
1. $ git clone --recursive git://github.com/HaxeFoundation/haxe.git && cd haxe
2. git checkout 3.1.3
3. $ make; sudo make install
4. $ haxelib

Output:
/usr/lib/haxe/std/neko/_std/sys/io/FileInput.hx:60: characters 26-29 : Invalid package : std should be <empty>
std/Type.hx:32: characters 1-30 : Invalid package : std should be <empty>
std/Type.hx:33: characters 1-28 : Invalid package : std should be <empty>
std/Type.hx:64: characters 15-65 : Invalid package : std should be <empty>
std/Type.hx:94: characters 15-68 : Invalid package : std should be <empty>
std/Type.hx:159: characters 15-86 : Invalid package : std should be <empty>
/usr/lib/haxe/extra/haxelib_src/src/tools/haxelib/Main.hx:715: characters 32-55 : Class<sys.FileSystem> has no field absolutePath

Issue #3670 says that the first error line is caused by neko missing, but I've installed the Ubuntu version (2.0.0-3) to no avail. As for the other lines, I couldn't find anything.

**Comment by Simn** [comment]
Using Haxe 3.1.3 with git haxelib is not a good idea.

**Comment by baraujo** [comment]
I was just trying to use HaxeFlixel, and they recommend using haxelib for installing, as stated in http://haxeflixel.com/download/; so, how should I proceed?

**Comment by waneck** [comment]
Can you try to run haxelib on a folder other than the haxe folder?
IIRC there was a problem when running haxelib that uses `--run` inside the haxe's `std` folder. It's got something to do with `std` folder paths.

**Comment by baraujo** [comment]
Ok, ran haxelib in another folder, the last error persists:

/usr/lib/haxe/extra/haxelib_src/src/tools/haxelib/Main.hx:715: characters 32-55 : Class<sys.FileSystem> has no field absolutePath

It seems haxelib was indeed using files from the haxe directory, somehow.

**Comment by waneck** [comment]
That's because the `haxelib_src` submodule isn't updated to the v.3.1.3 version. Please do a `git submodule update` where you've checked out haxe, and do a new `make install`

**Comment by baraujo** [comment]
Thanks, this solved the issue, now haxelib is working as intended. Since there is no problem with the code itself and it was all caused by running a git checkout 3.1.3 and "misaligning" the repos, I'll close this issue.

Also, thanks for the speedy responses, this further motivates me to use Haxe :-)
