### ISSUE TITLE
Abstract constructor return types

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3928]
Currently the return type of abstract constructors is hardwired to be the underlying type of the abstract. I've thought about this for a while and think that this is plainly wrong. After constructing an abstract type you should get an abstract type on the outside, not the underlying type.

This is probably what causes #3370, although there he even explicitly types the constructor to return the underlying type (these type-hints are completely ignored right now). The problem with having the wrong type is that inline will gladly take it over and put it in the AST.

@ncannasse: Is this just an oversight or is there some rationale behind this design?

**Comment by Simn** [comment]
After checking some more implications of this I concluded that this behavior was clearly faulty and fixed it in https://github.com/HaxeFoundation/haxe/commit/b2167ae7ccc4b921b2b42a8f52ee93a1db7751c8. Unlike normal constructors where we inline in a special way, abstract constructors are normal function calls and adhere to inline semantics. The return type is then relevant and having the wrong one leads to issues.

**Comment by ncannasse** [comment]
Most likely a mistake in using the actual good type.
