### ISSUE TITLE
Block type while inlining can be inferred to Dynamic due to TReturn

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3929]
```
class Main {
	static function main() {
		test();
	}

	static inline function test() {
		function f() {
			var x = 1;
			return x;
		}
	}
}
```

```
	static test(inline method) : Void -> Void
	 = [Function:Void -> Void]
		[Block:Void]
			[Var f(483):Void -> Int]
				[Function:Void -> Int]
					[Block:Dynamic]
						[Var x(484):Int] [Const 1:Int]
						[Return:Dynamic] [Local x(484):Int]
```

Note the `[Block:Dynamic]`. This comes from a TBlock taking over the type of its last expression. This is usually not a problem because the TReturns themselves are eliminated, but this is not true for the local function case.

I don't know if this leads to any real issue, but I think it should be fixed regardless.

**Comment by Simn** [comment]
Actually this isn't about inlining at all but occurs at typing level already. In that case I'll just assume that it works as intended.

**Comment by ncannasse** [comment]
It's intended, it allows to unify for instance     var x = if( flag ) 0 else return 1;  same for throw/break/continue I think.
