### ISSUE TITLE
Reflect.hasField broken for setter on javascript target

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#3930]
see: http://try.haxe.org/#e8AfA

testting Reflect.hasField(o, "set_fieldName") i don't get true even if the setter exists.
its because of underlying test Object.prototype.hasOwnProperty 
if you test Object.prototype.hasOwnProperty(o, "set_fieldName") you get false
even if the function is in the prototype, i don't know what is the solution...

thanks

**Comment by Simn** [comment]
hasField is only guaranteed to work on structure types.

**Comment by ncannasse** [comment]
use Type.getInstanceFields(Type.getClass(o)) instead

**Comment by sebpatu** [comment]
ok thanks, too bad its not a universal api whatever type of parameter is.
is it because of performances issues?

**Comment by ncannasse** [comment]
@sebpatu yes, methods are not normal fields and cannot be easily checked/accessed on some platforms
