### ISSUE TITLE
redundant cast on abstract binop overload

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3932]
we should lose this cast:

https://github.com/HaxeFoundation/haxe/commit/aa2c12935ac40e43cfde1608879e74c7e96128c5#diff-eb918bc546b40568ecadf7d9546c3119R2202

it adds redundant runtime checks that involve boxing and are evil

but we can't just do that because c# compiler complains because of implicit numeric type promotion:

https://msdn.microsoft.com/en-us/library/aa691330(v=vs.71).aspx

so we have to handle those at gencs side and add casts in one of its filters

**Comment by nadako** [comment]
this is actually a performance regression, as e.g. this
```haxe
var a:UInt = 1;
var b = a >= 1;
```
now generates
```cs
uint a = ((uint) (1) );
bool b = global::haxe.lang.Runtime.toBool(( a >= 1 ));
```
tho it used to generate
```cs
uint a = ((uint) (1) );
bool b = ( a >= 1 );
```
imagine these possibly-boxing casts all over the code

**Comment by waneck** [comment]
It's still generating the casts, but `toBool` is not being generated anymore for these kinds of casts. Pushing to 3.3
