### ISSUE TITLE
Map literals and mixed type values

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#3935]
import haxe.ds.IntMap;
	
	typedef MyArray = Array<Dynamic>;
	typedef MyMap = IntMap<Dynamic>;
	
	class B {
		public static function main(){
			var a:MyMap = [1=>2];
			var b:MyMap = [1=>"2"];
			var c:MyMap = [1=>2, 3=>4];
			var d:MyMap = [1=>2, 3=>"4"];
			var e:MyMap = [1=>"2", 3=>4];
			var f:MyMap = [1=>"2", 3=>"4"];
	
			var a:MyArray = [1];
			var b:MyArray = ["1"];
			var c:MyArray = [1,2];
			var d:MyArray = [1,"2",1];
			var e:MyArray = ["1",2,"1"];
			var f:MyArray = ["1","2"];
	
			var c:MyMap = [1=>"2", 3=>(4:Dynamic)];
			var d:MyMap = [1=>2, 3=>("4":Dynamic)];
		}
	}

Output:

    ./B.hx:11: characters 26-29 : String should be Int
    ./B.hx:12: characters 28-29 : Int should be String

At the same time, if I remove MyArray part of variable declaration compiler will give `Arrays of mixed types` error.

That's 3.1.3, don't have latest now.

**Comment by Simn** [comment]
This is only working if the expected type is Map, not IntMap. We could support this but that would mean hardcoding the different map types into the compiler.

**Comment by mcheshkov** [comment]
Nope, `typedef MyMap = Map<Int,Dynamic>;` give same errors.
And `typedef MyMapT<T> = Map<Int,T>;`.
And `typedef MyMapT2<T1,T2> = Map<T1,T2>;`
It works only as `var e:Map<Int,Dynamic> = [1=>"2", 3=>4];` - w/o typedefs

**Comment by Simn** [comment]
That has been fixed since 3.1.3.

**Comment by mcheshkov** [comment]
Oh, sorry for disturbance then

**Comment by Simn** [comment]
I forgive you if you fix my hxparse token-caching-ruleset-changing problem. :)
