### ISSUE TITLE
Loading Classes from Compiled Binaries at Runtime, Beyond Neko

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/haxe#3936]
Hi,

Currently, Java/C# provide the ability to compile classes into a library, load those classes at runtime, and do Interesting Things with them (eg. instantiate classes). They also provide some other metadata methods (like checking if a class implements an interface).

It seems that this is also possible in Haxe. I've [blogged about it here](http://haxers.herokuapp.com/2015/plugin-architecture-neko-reflection-and-interfaces/). The core of it depends on a couple of things:

- Compile and run against the `neko` target (only)
- Load the library `.n` file via `module = Loader.local().loadModule(...)`
- Find all classes via `module.eportsTable().__classes`
- Checking for an interface depends on `someClass.__interfaces__`

This works, but:

- It's hard to achieve (lots of reflection code required, interfaces/classes are very complex to read) and poorly documented
- It only works on `neko`, since it uses `neko.vm.Loader` and `neko.vm.Module`

My request comes down to: is it possible to:

- Simplify and reorganize the dynamic loading (eg. use static methods on `Type` to tell if a type implements a specific instance)?
- Extend this functionality beyond `neko` to other targets?

I imagine this depends a lot on metadata available at runtime. Currently, I'm stuck using Neko to build my game, since this doesn't work on any other targets.

**Comment by Simn** [comment]
#3076

**Comment by ashes999** [comment]
@Simn 3076 is about linking during the compilation process. #3936 is about reflectively loading binaries at runtime. They're not the same.

@ncannasse I asked about this on the Haxe google group about a week ago. Did you read that thread?

**Comment by Simn** [comment]
You're right, it's not the same issue.

You can already run-time load on several other targets, so you may want to look into that.

**Comment by ashes999** [comment]
@Simn I spent a lot of time looking into it. Did you read my blog post which I linked in this issue? That's the only thing I could find about runtime loading, and some of it was scavenged from old IRC logs.

Can you point me to a page that describes how to do this on, say, Windows and Linux targets? The workflow is:

- Create a main app with an interface
- Create a plugin app. It references the sources of the main app, creates a class that implements the interface, and compiles to a binary
- Drop the plugin binary into a subdirectory in the main app
- Run the app. It should load the binary, load the class that implements the interface, and instantiate it

For loading at runtime, I only found notes about Neko, using the `neko.vm.Loader` and `neko.vm.Module` classes.

**Comment by Simn** [comment]
You may want to ask that in haxelang or some other channel.

**Comment by Justinfront** [comment]
You can load swf's into swf's at runtime, works in AIR, applications domains are very important, you can also load swf's into Openfl c++ at runtime for graphics, using 'format' you can probably decode the abc but unsure if this would be hard to use?

**Comment by ashes999** [comment]
@Justinfront can you please provide me with a link that explains how to do this? I only found notes about Neko, and that took time.

Again, I'm asking for a consistent, documented (via API docs?) cross-target way to do this. There are some specific solutions per platform, like Neko, and apparently Flash.

@Simn As I mentioned in my first post, I asked on Haxelang about this. There was no response, and it's not well documented either. Can you please reopen this issue, since it's not a duplicate?

**Comment by Justinfront** [comment]
well like I said for just graphics assets it's simple in openfl there is 
https://github.com/openfl/swf
you can access the timeline assets even labels.
here is an example of reading a swf embedded as a string directly
http://markmail.org/message/4yauhmnpryonuyjh#query:+page:1+mid:4yauhmnpryonuyjh+state:results
then there is the classic using flex in haxe
http://old.haxe.org/doc/flash/flex
You can mix and match haxe and as3 swf's loading them into each other some care normally has to be taken but for instance polygonal offers haxe swc's that you could load as a swf at runtime.
 https://github.com/polygonal/ds
but actually extracting code at runtime for openfl c++ is probably more tricky you can read the ABC:
https://github.com/HaxeFoundation/format/tree/master/format/abc
I am unsure how easy it would be to create something to action the commands at runtime.

For Java I think you might be able to load a Jar in at runtime...
http://stackoverflow.com/questions/10624907/loading-jars-at-runtime
But I have not tried it.
If you want c# at runtime then you can load XAML/BAML, and from what I remember you can embed functions in XAML code fairly eaisily.
http://stackoverflow.com/questions/910814/loading-xaml-at-runtime
Then js I am sure you can load at runtime. found this
 http://www.javascriptkit.com/javatutors/loadjavascriptcss.shtml
Then python seems to have execfile command...
https://docs.python.org/2/library/functions.html#execfile
Then php seems to have stuff
http://php.net/manual/en/function.dl.php
But a all haxe approach is probably hscript
https://github.com/HaxeFoundation/hscript

Not sure if any of this is exactly what you want but maybe you can combine them into a more cross target fluid approach.

**Comment by Justinfront** [comment]
I think this would be better to move into a haxelang post than a discussion in issues, well until you get a pr together ;)

**Comment by ashes999** [comment]
@Justinfront as I keep repeating, there is a haxelang post about this. Nobody seems interested in discussing it outside of GitHub.

None of these approaches are sufficient. hscript doesn't allow you to even define new types. That's why I opened a GitHub issue: Neko works, but the API isn't cross-target.
