### ISSUE TITLE
Slow macro typing when using extractors (aggravated by reification)

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#3937]
Haxe spends ~9 _seconds_ in macro typing with the following example (~5 with `-D HALF`).

The behavior seems to depend on two factors:

 - (a) non linear complexity with the number of switch cases with extractors
 - aggravated by (b) the existence of macro reification on every case expression.

Notes:

 - (1) @waneck and I have profiled the offending code, resulting in [profile1](https://gist.github.com/jonasmalacofilho/e577fe631f20832c6571)
 - (2) @waneck has made a small change in waneck/haxe@d2f534c, resulting in significant improvements (~3 seconds, ~1 with `-D HALF`) and [profile2](https://gist.github.com/jonasmalacofilho/0ca70fd3251cede4a139)
 - (3) the complexity of the reificated expression appears to be relevant, since `macro $expr` was not significantly worse than no reification what so ever.

Code:

    import haxe.macro.Context.*;
    import haxe.macro.Expr;
    import haxe.macro.Type;

    class Test {
        static macro function slow(expr:Expr):Expr
        {
    #if HALF
            var res = macro $expr.foo();
    #end
            var t = typeof(expr); 
            return switch (t) {
            case TType(_.get() => { module : "StdTypes", name : "Null" }, [of]):  // Null<T>
                #if HALF res; #else macro $expr.foo(); #end
            case TMono(_.get() => null) if (expr.expr.match(EConst(CIdent("null")))):  // null literal
                #if HALF res; #else macro $expr.foo(); #end
            case TAbstract(_.get() => { module : "StdTypes", name : "Bool" }, []):  // Bool
                #if HALF res; #else macro $expr.foo(); #end
            case TInst(_.get() => { module : "String", name : "String" }, []):  // String
                #if HALF res; #else macro $expr.foo(); #end
            case TAbstract(_.get() => { module : "StdTypes", name : "Float" }, []):  // Float
                #if HALF res; #else macro $expr.foo(); #end
            case TAbstract(_.get() => { module : "StdTypes", name : "Int" }, []):  // Int
                #if HALF res; #else macro $expr.foo(); #end
            case TAbstract(_.get() => { module : "haxe.Int64", name : "Int64" }, []):  // Int64 FIXME haxe_ver < 3.2
                #if HALF res; #else macro $expr.foo(); #end
            case TInst(_.get() => { module : "Date", name : "Date" }, []):  // Date
                #if HALF res; #else macro $expr.foo(); #end
            case TInst(_.get() => { module : "mongodb.exprectId", name : "exprectId" }, []):  // exprectId
                #if HALF res; #else macro $expr.foo(); #end
            case TAbstract(_.get() => x, []):
                #if HALF res; #else macro $expr.foo(); #end
            case _:
                #if HALF res; #else macro $expr.foo(); #end
            }
        }

        public static function main()
        {
            trace(slow(null));
        }
    }

**Comment by Simn** [comment]
Yes it's a problem. I have committed waneck's fix (just using IntMap instead of Hashtbl) which indeed helps a bit. I also avoid replacing locals in macro-mode because the interpreter does not care about duplicate ones and the analyzer isn't run.

That doesn't address the real problem though, which is that extractors can really blow up your code due to the way they are implemented. Originally I didn't want to add them at all until I found a better way to deal with them, but they turned out to be so useful that I really wanted to have them.

I can think of nice solutions for this on targets that have goto, but we'll need a more general solution anyway.
