### ISSUE TITLE
-D doc-gen implies -dce no

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3939]
This has always bugged me a little. I would prefer if users had a choice here because the generated XMLs get unnecessarily large currently.

**Comment by ncannasse** [comment]
But then would not unused fields be DCE'ed and then not part of the documentation ?

**Comment by Simn** [comment]
Sure but that may or may not be exactly what you want. When I generate the documentation for a library I sometimes/often (?) don't want to include the entire standard library documentation. Having that in the generated XML is then just wasting space and time, but if you _do_ want it you can just compile with -dce no.

**Comment by ncannasse** [comment]
we could by default ignore all documentation of std library unless we have -D doc-std (by looking if the file is the the std class path)

**Comment by Simn** [comment]
Let's please just rely on DCE. Another problem right now is that you cannot generate XML documentation alongside your usual compilation because then the normal output is -dce noed as well.

**Comment by ncannasse** [comment]
Yes, I think it makes sense to have a different compilation pass for doc gen

**Comment by Simn** [comment]
... or we just don't overrule the DCE settings...
