### ISSUE TITLE
Change in haxe.io casing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3941]
/home/travis/haxelib/hxparse/git/src/byte/ByteData.hx:6: characters 8-48 : Class not found : haxe.io.Uint8Array

That's for you @Simn

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/pull/3791#issuecomment-74414655

Can you make up your mind? :P

**Comment by Simn** [comment]
Fixed in https://github.com/Simn/hxparse/commit/44e5ef4f2cb5e9a968fa9108f63ce36e4afda197

**Comment by ncannasse** [comment]
You requested it ;)
