### ISSUE TITLE
Neko and cpp Timer implementation:

### ISSUE THREAD

**Issue by ProG4mr** [HaxeFoundation/haxe#3943]
Hi, I have added haxe.Timer support for neko and cpp targets with these lines:

``` haxe
public  function new( time_ms : Int ) {
....
    #if neko
    neko.vm.Thread.create(function () {
        Sys.sleep( time_ms / 1000 );
        run()
    });
    #ned
```

This seems to works fine, seems a bit naive or too simple not to be implemented already, what is wrong with this implementation?

The only problem i see is if the application finishes and the thread is closed, but for programs that run on loop it works fine.

**Comment by ncannasse** [comment]
When doing this, you're assuming that the user has code that is mulithread safe, it also requires to hold the main thread from exiting. I'm thinking about adding support for this in #3075, but it will most likely be threadless.
