### ISSUE TITLE
[cs] change Array to native arrays for DynamicObject

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3945]
as we also talked on #haxe-dev, `DynamicObject` (haxe structs implementation) don't need 4 full fledged haxe arrays to store its data and can work with native arrays for speed and lesser memory footprint

**Comment by Simn** [comment]
If this is just an optimization I suggest that we leave it for 3.3. I suspect it might be a bit tricky to get right because gencommon has to know the native array type (cs.NativeArray or java.NativeArray).

**Comment by nadako** [comment]
Yeah, this can wait, although waneck made it sound like it's a 2 minute job;) maybe i'll take a look myself when i have some time

**Comment by Simn** [comment]
I actually tried it too. :) The two problems I was having was that 1) I did not know where the native class type should come from because they differ between Java and C# and 2) I didn't know how to translate a TArrayDecl to a native array initialization.

**Comment by nadako** [comment]
1. that should probably be configured by the generator
2. i think native array init is a call to `__array__`

**Comment by Simn** [comment]
https://github.com/Simn/haxe/commit/af3b8df0951aa8e2435280827fe5d9e08973d908

In that case I think all that has to be done is
1) factor out `let native_arr_cl` and `let native_array_inst t`
2) change https://github.com/Simn/haxe/blob/af3b8df0951aa8e2435280827fe5d9e08973d908/gencommon.ml#L7446

**Comment by waneck** [comment]
I've added the change to replace `Array` to `Vector` on enums here: https://github.com/HaxeFoundation/haxe/commit/90ddbdfa14f4178c08085f87fa0d74df920cb385 - `tvector` and the `__array__` bits are probably the interesting ones

**Comment by nadako** [comment]
This is only only about replacing array by vector in ocaml code: DynamicObject currently uses array methods like `splice` and `insert` which vector lacks. Constructing that code in ocaml texpr sounds very annoying, maybe we could factor out some helper class that work with native arrays that implements these methods and then use it for both Array and DynamicObject?

**Comment by waneck** [comment]
Sure. I guess we could add them to FieldLookup

**Comment by nadako** [comment]
Wouldn't it be quite strange if `Array` depended on `FieldLookup`?

**Comment by waneck** [comment]
Other improvements I can see being added is:

* From my measurements some time ago, it seems that the binary search we do only makes a difference if we have more than 15 elements (IIRC). Before that, a simple linear scan is faster.
This way we could maybe only start having the array sorted if we surpass the 15 element mark
* We could measure if it would pay to replace `__hx_hashes` and `__hx_hashes_f` with a single array, and a related indices array which would indicate in what array and what index the object is stored. This has the advantage of only looking up one time. Not sure if it will pay off though.

**Comment by waneck** [comment]
Oh I wasn't thinking about replacing `Array`'s algorithm with the one in `FieldLookup`. I'm not sure we should follow how `Array` does - while `Array` always doubles the capacity when the limit is reached, I'm not sure it's interesting for `DynamicObject` to follow that as well.

**Comment by nadako** [comment]
Good that these points are written down now. Let's change array->vector first, as it would obviously improve things, and then measure others.

**Comment by nadako** [comment]
Yeah, then `FieldLookup` sounds like a nice place.

**Comment by waneck** [comment]
Another thing to note is that I've made the hash be 31-bit only; This means that the sign bit is always free. We could use this to avoid the index array completely, if we'd like - at a penalty of a bigger object.

**Comment by waneck** [comment]
It doesn't seem like there's anything left to do in here anymore
