### ISSUE TITLE
[cs] cs.Lib.arrayAlloc fails to compile WITHOUT -D erase-generics

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3946]
Subj.
```haxe
class Main {
    static function main() {
        cs.Lib.arrayAlloc(10);
    }
}
```

```
out/cs/src\cs\Lib.cs(43,25): error CS0029: Cannot implicitly convert type `haxe.root.Array<object>' to `haxe.root.Array<T>'
```

**Comment by nadako** [comment]
Changing `untyped` to `@:privateAccess` in 086113cf0b11187aae091f2c9ea795318a77e97f seems to fix the original issue, however I now try to add `inlin` to `cs.Lib.arrayAlloc` and it works without `-D erase_generics`, but with it we get the following:
```cs
global::Array a = new global::Array(((object[]) (new int[10]) ));
```
which fails to compile. What's going on there?

**Comment by Simn** [comment]
Should this be addressed for 3.2? `erase_generics` is a new feature but I don't know how severe this issue is.

**Comment by Simn** [comment]
Oh, just noticed the "WITHOUT". In that case this is another 3.1.3 regression.

**Comment by waneck** [comment]
@nadako This seems solved? I can't reproduce this issue even when declaring `arrayAlloc` as inline
