### ISSUE TITLE
MacroType usage

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3947]
While trying to replace MacroType by genericBuild, I found the following module (CastleDB usage)

```
private typedef Init = haxe.macro.MacroType < [cdb.Module.build("data.cdb")] > ;
typedef Time = LevelData_time;
...
```

Here, we build a whole module based on `data.cdb` content, and then we reference the types from this module. However when using genericBuild, the types are not created until we build the Init class, so we cannot reference them. 

So unless I'm mistaken it seems that MacroType is still necessary for this kind of usage.

**Comment by Simn** [comment]
How are you using it? The intended usage is something like this: https://gist.github.com/Simn/8581ee291b95c6c22813

**Comment by Atry** [comment]
As @:genericBuild does not work for macro itself (https://github.com/HaxeFoundation/haxe/issues/4495), we still need MacroType for macro itself.

**Comment by Simn** [comment]
The macro argument is pretty convincing, let's keep MacroType around.
