### ISSUE TITLE
can throw anything, but can only catch class/enum/dynamic values

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3948]
Is this intended that we CAN do `throw false`, but CANNOT `catch(e:Bool)`?
```haxe
class Main {
    static function main() {
        try throw false catch (e:Bool) {} // Catch type must be a class, an enum or Dynamic
    }
}
```

**Comment by Simn** [comment]
Catching Bool (and probably Int) does not work on python.

**Comment by nadako** [comment]
the problem is that genpy generates simple `isinstance` calls instead of our complex typecheck that handles abstracts (Std.is):

```haxe
class Main {
    static function main() {
        try throw false catch(e:Bool) {}
    }
}
```

```python
def main():
	try:
		raise _HxException(False)
	except Exception as _hx_e:
		_hx_e1 = _hx_e.val if isinstance(_hx_e, _HxException) else _hx_e
		if python_lib_Builtin.isinstance(_hx_e1, Bool):
				pass
		else:
			raise _hx_e
```

**Comment by nadako** [comment]
also, ` _hx_e1 = _hx_e.val if isinstance(_hx_e, _HxException) else _hx_e` should probably also use `python_lib_Builtin.isinstance` to avoid naming conflicts

**Comment by nadako** [comment]
on the second thought, i think we should add most used builtins to list of "keywords that should be escaped for local vars", similar to how genjs does.

because dot access isn't free in python iirc

**Comment by frabbit** [comment]
@nadako can you create a new issue and add an example for what you mean exactly.
