### ISSUE TITLE
Another safe-cast parsing failure

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3950]
```
class Main {
    static function main() {
		cast ("foo" : String);
    }
}
```

`src/Main.hx:3: characters 14-15 : Unexpected :`

**Comment by ncannasse** [comment]
Uhm : we agree that this is not working as you might want it to work ?   (cast "foo" : String) will cast foo as String, while cast ("foo" : String) will do  an ECast ECheckType

**Comment by Simn** [comment]
I'm not sure what you mean.

`(cast "foo" : String)` is parsed as: `EParenthesis(ECheckType(ECast("foo", null), String))`
`cast ("foo" : String)` is parsed as: `ECast(EParenthesis(ECheckType("foo", String)), null)`

**Comment by ncannasse** [comment]
Perfect then !
