### ISSUE TITLE
[python] reserve some builtins for keywords

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3952]
Continuing #3948 discussion

Currently, genjs has two sets of "keywords":
 - `kwds`: language keywords that ALWAYS must be escaped (`if`, `function`, etc.)
 - `kwds2`: global names that are not keywords, but most likely mean something in runtime (like `Object`, `NaN` or `console`)

These global names are considered when generating a name for a local variable (as well as function arg and for/catch var), so if you do e.g. `var console = ...` it doesn't overshadow global `console` and thus doesn't break stuff that depends on it (e.g. `trace`).

At the same time, one CAN use these names for fields without escaping (so `obj.console` would still be generated as `obj.console`).

The same technique can be applied to python, for example, if we add `isinstance` to `kwds2` then we can safely generate `isinstance` calls without going through `python_lib_Builtins.isinstance` and still avoid unnecesary escaping if someone names a field `isinstance`.

Does that make any sense?

**Comment by Simn** [comment]
Makes sense to me!

**Comment by nadako** [comment]
i implemented this in 09b130d381689dff8b418fb4904f4c0f16cb178d, now we only need to replace `python.lib.Builtin` usage in hx classes.
