### ISSUE TITLE
Can not use Haxe libraries in 64 bit Windows build, not explained in getting started guide

### ISSUE THREAD

**Issue by metabench** [HaxeFoundation/haxe#3957]
I have run through a bit of the getting started material, following the instructions.

I chose the `-D HXCPP_M64` option to get 64-bit compilation. I would get the following error:

    Error : Could not load module std@file_stdin__0

I found the following information while searching: https://groups.google.com/forum/#!topic/haxelang/u01cYu0YnlI

The issue is either:

Haxe does not properly support 64 bit Windows
Haxe does not properly explain its limitation to 32 bit Windows.

While I have read an opinion on the internet saying '[32 bit] is superior in every measurable way I think (compatibility, speed, size)', this is not explained in the Haxe guide. This problem is very likely to trip up a beginner.

At the very least, problems with 64 bit Windows code should be explained or mentioned in the getting started guide.

**Comment by Simn** [comment]
What getting started guide are you referring to? Either way, this is more of an issue for the website and not the compiler, so please report to the haxe.org repository.

**Comment by metabench** [comment]
I read both the standard getting started guide, following the 'Hello World' example (http://haxe.org/manual/introduction-hello-world.html)

I got the information about compiling as 64 bit from http://old.haxe.org/doc/start/cpp

I notice that the second page is marked as 'old'.

**Comment by Justinfront** [comment]
Hi metabench,

The original haxe.org site was a wiki and is now "old.haxe.org", it has lots of valuable information added by many Haxe users and should not be dismissed and many aspects are not that old and others maybe old but still relevant. 

The new site has less information currently, but it is normally upto date on aspects that are documented and it is very accurate and consistant in style, and quality, but documentation is timeconsuming and currently incomplete.  So the old site as still a very useful and often my first point of reference, but in time, the new site should become stronger, and more consistant resource, and often the best place to find details of recent haxe aspects. 

Normally your question is best answered on 

https://groups.google.com/forum/#!forum/haxelang

or beginners questions maybe better answered by people who get points for helping users.

http://stackoverflow.com/search?tab=newest&q=haxe

Obviously many of the best answers are found by good googling the web, and certainly you get more credit, and help, in Haxe community if you do your homework before asking questions.

Haxe is an amazing language welcome to the community hope you enjoy it, I am sure it will surpass some, maybe all of your expectations, as Haxe has many facets.

Best 

Justin
