### ISSUE TITLE
[c++] inconsistent one-line unsafe cast behaviour

### ISSUE THREAD

**Issue by restorer** [HaxeFoundation/haxe#3958]
Simple haxe code:

```haxe
class A {
    public function new() {
    }
}

class B extends A {
    public function foo():Void {
        trace("foo");
    }
}

class Test {
    private static function bar(a:A):Void {
        (cast a:B).foo();
    }

    public static function main() {
        bar(new B());
    }
}
```
Although `(cast a:B)` unsafe cast syntax is not documented, it work fine for all targets except c++

php, js, swf, neko, python - work as expected (dynamic targets)
java - `((haxe.root.B)(a)).foo();`
cs - `((global::B)(a)).foo();`

but this is not working for cpp target:

```cpp
Void Test_obj::bar(::A a) {
    { a->foo(); }
    return null();
}
```

produce compiler error - `no member named 'foo' in 'A_obj'`

Proposal: support this type of unsafe cast in cpp target, like `((::B)a)->foo();`

P.S. tested either with Haxe 3.1.3 and latest Haxe from development branch

**Comment by Simn** [comment]
Confirmed for latest. The AST looks safe (despite the double TCast, but that's actually in the syntax because ECheckType adds one too):

```
			[Call:Void]
				[Field:Void -> Void]
					[Cast:B] [Cast:B] [Local a(133):A]
					[FInstance:Void -> Void]
						B
						foo
```

Not a regression, but would be nice to fix for 3.2 regardless.

**Comment by nadako** [comment]
> (cast a:B) unsafe cast syntax is not documented

isn't it? it's actually two expressions (a type-removing `cast` and a `typecheck`) and I both are documented. maybe we should mention the combination of two somewhere (e.g. in the `unsafe cast` section)

**Comment by restorer** [comment]
> maybe we should mention the combination of two somewhere
it will be just fine

**Comment by Simn** [comment]
I don't really want to start documenting expression combinations. The only important information is if it's casting the type-check or type-checking the cast.
