### ISSUE TITLE
Allow qualified metadata names

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#3959]
Following a discussion we had on #haxe: It would be nice if we could use `@:js.someName` in metadata to group them. Internally this could just become a metadata named `:js.someName`.

Our metadata is growing into a bit of a mess so I would like to address this sooner rather than later. Any objections?

**Comment by ousado** [comment]
+1 , we need something that scales with the growing number of targets and target-specific metadata.

**Comment by frabbit** [comment]
+1 and maybe we should move compiler internal metadata into it's own namespace before 3.2

**Comment by andyli** [comment]
What is the different between the proposal and using prefix (e.g. "@:jsSomeName")?

**Comment by Simn** [comment]
- We can later extract all metadata for specific namespaces which is useful for documentation.
- We can later ignore target-specific metadata when compiling to a different target.
- We currently haven standardized any prefix usage anyway.
- It looks nicer.

**Comment by Simn** [comment]
* We can later provide completion on `@:js.`.

**Comment by ncannasse** [comment]
I'm not sure about it : we have a lot of metas which are for instance cs+java, and I'm not sure how we should handle the transition from global metadata to namespaced one.

Or would that just be a filter ? for instance  @:js.meta would be the same as @:meta but would check that the metadata is available in JS ?

**Comment by Simn** [comment]
I'm not sure about the transition either but I really feel like we should enforce some naming schemes. It's getting a bit out of control.

**Comment by waneck** [comment]
I strongly agree that our metadata naming is getting out of control. It's not only untyped and unchecked (so e.g. a misspell makes the behaviour silently fail), but it needs namespacing. Many macro libraries for example use the `@:skip` metadata - each one for its own library.
I really would like to see a good solution for this.

Typed metas can always be an option :))

**Comment by nadako** [comment]
+1 for typed metas!

**Comment by waneck** [comment]
I think it would make sense. We all agree that strongly typed code is better than untyped - so I see no reason why a metadata should be untyped. We could maybe still allow the untyped metas as well - implementation still needs to be defined.

**Comment by Simn** [comment]
Alright, let's 3.3 the discussion...
