### ISSUE TITLE
[cs] build warning

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3961]
just reporting so it's not forgotten in the flow

`D:\Code\haxe\std/cs/internal/HxObject.hx:113: characters 31-60 : Warning : No overload found for this constructor call`

**Comment by dogles** [comment]
@waneck It seems there is a regression here after fixing #4001

**Comment by waneck** [comment]
Yes. This is because of #4003 . As soon as it's fixed/clarified, this will
fixed as well
