### ISSUE TITLE
[JS enhancement] Maybe Comprehensions should use [].map()

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#3963]
(3.1.3)

When using Lambda.map() on an Array, the JS output uses [].map().  However, if I use a comprehension, it generates the normal for-loop comprehension construct.

I think it would be better to use [].map() in both cases because:
- the code is smaller and more readable
- most browsers are optimized to execute this pattern faster.

If compatibility is a concern, this could be filed under the ```es5``` flag.

**Comment by Simn** [comment]
I don't understand what you mean. Comprehensions are to create arrays while mapping is done to get new arrays from existing ones. What do you want to map here?

**Comment by explorigin** [comment]
It feels immaterial to me.  Both map and comprehensions work from an iterable and output a new array. Why do we need to distinguish the source?

**Comment by Simn** [comment]
Can you post some Haxe code + what you think it should generate?

**Comment by frabbit** [comment]
map could only be used if we don't have an if-filter inside of the comprehension

**Comment by waneck** [comment]
Do you have data of `.map()` being faster? I find that hard to believe.

**Comment by explorigin** [comment]
```
using Lambda;

class Test {
    static function main() {
        var t = new haxe.Template("Hello ::name::");
        var people = [
            {name: "Thomas"},
            {name: "Susie"},
            {name: "Simon"},
            {name: "Bill"}
        ];
        trace([for (person in people) t.execute(person)].join(', '));

        trace(people.map(function(person) { return t.execute(person); }).join(', '));
    }
}
```
Produces:
```
Test.main = function() {
	var t = new haxe.Template("Hello ::name::");
	var people = [{ name : "Thomas"},{ name : "Susie"},{ name : "Simon"},{ name : "Bill"}];
	console.log(((function($this) {
		var $r;
		var _g = [];
		{
			var _g1 = 0;
			while(_g1 < people.length) {
				var person = people[_g1];
				++_g1;
				_g.push(t.execute(person));
			}
		}
		$r = _g;
		return $r;
	}(this))).join(", "));
	console.log(people.map(function(person1) {
		return t.execute(person1);
	}).join(", "));
};
```

**Comment by explorigin** [comment]
[].map() is generally faster on JITed browsers (most modern browsers) because they can optimized the isolated function into a tight loop.  Let me dig up a JSperf.

**Comment by frabbit** [comment]
for loop is faster in my chrome, see http://jsperf.com/map-vs-native-for-loop/7

**Comment by frabbit** [comment]
much faster

**Comment by waneck** [comment]
Yeah. On Firefox it's also much faster

**Comment by frabbit** [comment]
not sure about while vs. for

**Comment by waneck** [comment]
I'd say that any decent JIT internal representation will transform a for into a while-like loop, so it won't really matter.

**Comment by Simn** [comment]
Agreed.

**Comment by explorigin** [comment]
OK so I got a bad impression from a separate discussion.  Perhaps speed depends on content.  Is this worth discussing from code-brevity perspective?

**Comment by frabbit** [comment]
i don't think that this actually matters when you minify the js code.

**Comment by Simn** [comment]
P.S.: The 3.2. output with -D analyzer looks much nicer:

```
	var t = new haxe.Template("Hello ::name::");
	var people = [{ name : "Thomas"},{ name : "Susie"},{ name : "Simon"},{ name : "Bill"}];
	var tmp;
	var _g = [];
	var _g1 = 0;
	while(_g1 < people.length) {
		var person = people[_g1];
		++_g1;
		_g.push(t.execute(person));
	}
	tmp = _g;
	console.log(tmp.join(", "));
	console.log(people.map(function(person1) {
		return t.execute(person1);
	}).join(", "));
```

**Comment by explorigin** [comment]
Wait...I'm not crazy.  There is still an optimization here.  The benchmark that @frabbit posted has one element to it that the Haxe compiler does not...it specifies the array size.  This allows the for-loop to run much faster.  Without specifying the array size, ```map``` is actually faster (http://jsperf.com/map-vs-native-for-loop/35)

So the ideal scenario is to do something like:
```
var newArray = new Array(arrayLen);
```
instead of
```
var newArray = [];
```

**Comment by waneck** [comment]
The for loop is still faster for me, but I guess that preallocating the array would be a nice optimization (when the comprehension doesn't have an if condition)

**Comment by explorigin** [comment]
I'm having trouble reading today.  You're right, it's still faster.  But in spite of myself, there is an improvement to be had here.

**Comment by frabbit** [comment]
in chrome map is ~45% faster now

**Comment by frabbit** [comment]
sorry i misread the results, for loop is still faster :D

**Comment by Simn** [comment]
What are you guys smoking? testArray.map(double) is by far the slowest.

**Comment by frabbit** [comment]
:D

**Comment by Simn** [comment]
Unfortunately Haxe only comes with map and array comprehension, not reading comprehension.

**Comment by frabbit** [comment]
that's too bad...

**Comment by explorigin** [comment]
Well said.

But don't miss the ```new Array(arraySizeHere)``` enhancement that could still speed up the generated while loop.

**Comment by waneck** [comment]
Feature request: reading comprehension for Haxe 3.2

**Comment by explorigin** [comment]
I'll just move it to another issue.

**Comment by frabbit** [comment]
here are some more performance tests:
http://jsperf.com/map-vs-native-for-loop/37
