### ISSUE TITLE
sys.io.Process on macro not working on Linux :(

### ISSUE THREAD

**Issue by fserb** [HaxeFoundation/haxe#3966]
In a macro context, ```Sys.command("/bin/ls"); ``` works fine, but ```new sys.io.Process("/bin/ls", []);``` fails with: ```Process creation failure : /bin/ls```.

I have the same code running on Mac 64 (Haxe 3.1.3, Neko 2.0.0) and it works fine.
But on my Ubuntu 14.04 64 (Haxe 3.1.3, Neko 2.0.0, both 64) it fails. I got neko from the Ubuntu repo and haxe from haxe.org (I think Haxe from ubuntu is 3.0.0).

I saw issue #1189 and it seem very similar, but at that point there was a 64/32 mismatch, that I don't seem to have.

help?

**Comment by ncannasse** [comment]
Could you try to get latest haxe from http://build.haxe.org ?

**Comment by Simn** [comment]
@andyli: Could you check if this works now?

**Comment by ibilon** [comment]
I can confirm that `sys.io.Process` works on haxe 3.2.1 linux from a macro.

**Comment by andyli** [comment]
Yes, I confirm it works correctly with haxe 3.2.1 and the current dev branch.
