### ISSUE TITLE
recursive closure don't compile

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#3968]
http://try.haxe.org/#8FD8B
previous closed bug: https://github.com/HaxeFoundation/haxe/issues/332
is back in 3.1.3 

for js target reusing closure function recursivelly don't compile if closure is declared like: 
var func = function() { func(); }
but it works if declared like this: 
var func = null;
func = function () { func(); }

**Comment by Simn** [comment]
This is consistent, a variable is not available in its initialization expression. You can use `function id()` instead.
