### ISSUE TITLE
Type Hole

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#3975]
While playing with #3967 I found the following:

```
var a = ["a", "b"];
var a2 : { var pop(get,never) : Void -> Void; } = a;
```

This is allowed and should not, because "pop" is not a property in `a`

**Comment by Simn** [comment]
Looks like this was a regression from 2.10 to 3.0.0.

**Comment by Simn** [comment]
If you don't mind I would prefer leaving this for after 3.2. I know the problem is in `unify_kind`, but I can't tell why this used to give an error in 2.10 because that code didn't change. I don't want to change anything unification-related one week before release.
