### ISSUE TITLE
error "File is too big (max 16MB allowed)"

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#3976]
Beyond the technical limits of ocaml, this is very very _very_ annoying to have swf data capped to 16 MB.

In protoype phases, during ludum dare or for retail AIR distributions it just dose not make sense. It forces us to split cubemaps which is not a cool pipeline for examples.

Can we please schedule this to change (3.3 ? )  ?

Thanks

**Comment by Simn** [comment]
This is being discussed in several other issues, e.g. #3237.

**Comment by ncannasse** [comment]
Ah, that's actually a separate issue, about a single file which cannot fit into a single String it seems, can you confirm @delahee ?

**Comment by ncannasse** [comment]
@Simn that would require to be able to read our input into a Rbuffer instead of a String, then have an IO.input_rbuffer wrapper so we can parse from it

**Comment by Simn** [comment]
I'm trying to understand the context here, is this about -swf-lib?

**Comment by ncannasse** [comment]
for instance:

```
@:bitmap("20mbfile.png") class MyBigPicture extends flash.display.BitmapData {
}
```

**Comment by delahee** [comment]
@ncannasse yep single file more than 16 MB and on cpp, the android compiler going mad after multiple files more thant 24MB. So in the end we often have to "rage" shift asset loading mechanic and it doesn't seem natural to many people in the team :)

**Comment by ncannasse** [comment]
@delahee so your problem is with hxcpp, not flash ?

**Comment by delahee** [comment]
Sorry for the confusion. 

-> This problem is about flash ( >30 Mb cubemap ).

We _also have a problem on cpp but for different reasons.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
