### ISSUE TITLE
[python] double member init generation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#3978]
```haxe
class Main {
    var a = 1;
    function new() {}
}
```
generated as
```python
class Main:

	def __init__(self):
		self.a = None
		self.a = 1
```
which looks very stupid.

The problem is that python generator first generates `= None` for every variable and then come initializations added by `add_field_inits` filter. We should skip those fields in the generator but it's not clear at generator level whether field was moved to the constructor or not. Can we maybe add some `@:meta` for those fields in `add_field_inits` and then check it in `genpy`? cc @Simn

**Comment by Simn** [comment]
That wouldn't really help, you get the same behavior if you manually assign the variable in the constructor.

**Comment by Simn** [comment]
Let's do this after 3.2. It's not entirely trivial because you might have to detect control flow too in order to find all unconditional assignments.

**Comment by nadako** [comment]
I don't really understand the problem with this specific case. The `add_field_inits` filter adds unconditional inits at the top of the constructor, genpy then adds its `None` inits at the top of the constructor. If `add_field_inits` added e.g. `@:hasInit` meta to `cf_meta`, then genpy could check for it and skip generating those `None` inits.

**Comment by Simn** [comment]
Yes but that's not a general solution, it's just a workaround for a specific case. As I said the code would still look silly if you did `a = 1` in the constructor.

The solution is to detect which member fields are possibly not initialized when control flow leaves the constructor, as well as fields which are possibly used in the constructor itself before being initialized. This is not very hard, but you have to respect `return` expressions as they may cause subsequent initialization to be skipped at run-time.

**Comment by Simn** [comment]
@nadako: Any idea how we could test this?

**Comment by nadako** [comment]
How do you check js output?

**Comment by Simn** [comment]
It reads the output and checks for lines starting with ClassName.fieldName, e.g. `Main.main`.

**Comment by Simn** [comment]
Oh well, I guess we don't really need elaborate python tests.
