### ISSUE TITLE
Using haxe.Template on anonymous object: cannot iter on:..

### ISSUE THREAD

**Issue by ProG4mr** [HaxeFoundation/haxe#3980]
I'm using haxe Template on javascript target to process a simple json-like object:

```haxe
var ctx = {item : [{ a: "1", b:"b" }, { a : "2" , b : "b"}]};
new Template("::foreach item:: ::a:: ::b:: ::end::").execute(ctx);
```

i get the error:
```
Uncaught Cannot iter on [{
		a : 1, 
		b : b
	},{
		a : 2, 
		b : b
	}]
``` 

Am i doing something wrong? I though it would be common to render json objects, what would be a good alternative? Thank you

**Comment by ProG4mr** [comment]
This is a bit confusing about iterators and objects, anyway i found a workaround by passing ctx.item.iterator() so things are fine.

**Comment by Simn** [comment]
It's a DCE problem and there's not much we can do about it.
