### ISSUE TITLE
add @:jsRequire to list of compiler metas

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#3981]
It doesn't show up via ```haxe --help-metas```, or on
http://haxe.org/manual/cr-metadata.html

**Comment by Simn** [comment]
Surely it does show up with --help-metas in 3.2. We'll have to resync the manual when we release 3.2, but that's a HaxeManual issue.

**Comment by jdonaldson** [comment]
yep, I see it now.  Thanks!
