### ISSUE TITLE
"Capture variables must be lower-case" when using non-existent enum value

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#3982]
I apologize that I don't have a good code sample for this, but I basically did the following:

    @:enum abstract MyClass(String) to String {
        var HELLO_WORLD = "helloWorld";
        public var happy (get, never):Bool;
        private inline function get_happy ():Bool {
            return switch (this) {
                case HELLO: true;
                default: false;
            }
        }
    }

Instead of giving an error that "HELLO" is not a matching value, I received an error that "capture variables must be lower-case". I'm not sure if this is because the value I used resembled a real (though longer) value, or not.

I'm using 3.2 build 682a4e2

Thanks!

**Comment by Simn** [comment]
This tries to capture the match value in a local variable named HELLO, which is not allowed. Depending on your context you may want to use an if-expression or a guard. We do not resolve plain identifiers to values in patterns.
