### ISSUE TITLE
Flash target - Same variable in separate macros result in `unbound variable (varname)` error

### ISSUE THREAD

**Issue by ProG4mr** [HaxeFoundation/haxe#3984]
Hi, trying to create a macro that sets a variable inside a function and later reuse that variable in another macro i get the error `unbound variable varname` on flash target, even using `untyped`.

Here is a small example of that
http://pastebin.com/qZxj8srj

I'm trying to add a variable at the beggining of a setter to store the field initial value, and latter the walk the setter recursively dispatching the final value before any "return" statements, so far only flash target is giving me this problem. Thanks.

**Comment by Simn** [comment]
Check the generated code and read CONTRIBUTING.md. Try asking in haxelang or #haxe.

**Comment by ProG4mr** [comment]
Hey that was direct, anyway the output is fine if i compile to -as3 instead of -swf, I'll try asking it later in those channels then, thanks.
