### ISSUE TITLE
js; Source map location is incorrect on windows when building to a folder

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#3986]
On generating a js file to a folder - the map source URL becomes incorrect, but only on windows. 

Consider the hxml:

`-js bin/web/app.js`
`-D source-map-content`

Mac: `//# sourceMappingURL=app.js.map`
Linux: `//# sourceMappingURL=app.js.map`
Windows: `//# sourceMappingURL=bin\web\app.js.map`

This means source maps don't work on Windows, but work everywhere else.

cc @aduros @Simn

**Comment by Simn** [comment]
Regression?

**Comment by underscorediscovery** [comment]
It's present in 3.1.3

**Comment by Simn** [comment]
@aduros: Could you take a look for 3.2?

**Comment by aduros** [comment]
I don't have a Windows machine set up for Haxe development, so this could be tricky for me. Looking at genjs, it's probably a bug in the basename function. It should use backslashes on Windows.

Also, there's got to be a basename in the ocaml standard library that we can use instead?

**Comment by aduros** [comment]
Probably fixed, someone please test on Windows.

**Comment by underscorediscovery** [comment]
Will try it on linux/mac/windows in a bit

**Comment by aduros** [comment]
Fixed?

**Comment by underscorediscovery** [comment]
Tested with this, seems to be ok now.
If someone else wants a run at it:

`Save as App.hx`

```
class App {

    static function main() {
        trace("app");
    }

}
```

`Save as build.hxml`

```
-main App
-js bin/web/app.js
-D source-map-content
```

Run with `haxe build.hxml -debug`
Look inside the .map file in bin/web/ for no prefix on the path.
