### ISSUE TITLE
[java] "java.lang.Integer has no field valueOf"

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#3987]
Static functions seem to be missing from certain types that are generated as abstracts:

```haxe
class Test {
        static function main(){
                java.lang.Integer.valueOf(123);  
                 // Test.hx:7: characters 2-27 :  "java.lang.Integer has no field valueOf"
        }
}
```

**Comment by ousado** [comment]
Oh, and 
```haxe
var i = new java.lang.Integer(123); // java.lang.Integer does not have a constructor
```

**Comment by waneck** [comment]
This will be fixed with #3254 . We could for now make a workaround and define all statics on the abstract, and I did spend some time to do this workaround. But the amount of code needed for that to work was huge. @Simn pls fix #3254 :)

**Comment by Simn** [comment]
I don't plan to support #3254 for 3.2 and I'm not sure it's a good idea to have it afterwards either.

**Comment by Simn** [comment]
This is actually a regression from 3.1.3.

**Comment by waneck** [comment]
Ugh. The amount of code that needs to be changed because of not having #3254 is huge. This is pretty annoying.

**Comment by waneck** [comment]
@Simn, I hope this diff will make a strong case in favor of #3254 . I had to do a program that used a macro to generate these definitions. And I've just realized that since you don't have access to overloads on the macro, it still doesn't contain all definitions (waiting for #3460 ). I won't touch this anymore for 3.2 though

**Comment by Simn** [comment]
I noticed that the original example here doesn't compile anymore:

```
src/Main.hx:3: characters 28-31 : Int should be String
src/Main.hx:3: characters 28-31 : For function argument 'param1'
```

Looks like a regression?
