### ISSUE TITLE
Add a flag to prevent including js.html.compat typed arrays

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#3988]
Could we please get a -D js-has-typedarrays flag that prevents including the typed array compat layer? This could shrink apps using node-webkit, Firefox OS, and many other environments that are known to have typed array support.

**Comment by ncannasse** [comment]
Fine with me.

**Comment by aduros** [comment]
Nevermind, there's a macro for that. :)

**Comment by haxiomic** [comment]
Hey adurois, I know this was a while ago now but I'm curious how you disabled the compatibility layer for js typed arrays? I'm using `-D nodejs` which works but feels a ugly when targeting the browser (I don't think it has side effects now but it may do in the future)

I've tried `--macro exclude('js.html.compat', true)` but this leaves a significant amount of code that js.html.compat.* was using (but it no longer required).

**Comment by aduros** [comment]
That's what I ended up using, it seemed to work for me.

**Comment by haxiomic** [comment]
Thanks for the response @aduros, I guess exclude() only prevents output generation after dependencies have been resolved. Patching over the types would probably work but `-D nodejs` is good enough for the time being
