### ISSUE TITLE
C# haxe.Resource line-endings

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#3989]
When using `haxe.Resource`, the line-endings of a txt file is automatically converted to CRLF on Windows when targeting C#.

Given a text file, "test.txt", with the content `test\ntest`, compile and run the following:
```haxe
class Test {
	static function main() {
		trace(haxe.Resource.getString("test.txt").length); //10, but should be 9
	}
}
```
```
-cs bin
-main Test
-resource test.txt
-cmd bin\bin\Test.exe
```

**Comment by waneck** [comment]
This is confirmed, but I can't find a way to load the resources as a binary file. I've tried forcing a binary extension, but it doesn't work

**Comment by waneck** [comment]
Can you see if that works for you? I don't have a windows OCaml environment setup, so I can't really test if it really solved it.

**Comment by andyli** [comment]
Yes, I confirm it has been fixed! Thanks :)
