### ISSUE TITLE
[js] js.html.Promise should be js.Promise

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#3998]
The pattern is widely diffused and made into the latest nodejs so it should be more general and not just a "html" thing.

**Comment by nadako** [comment]
note that `Promise` is an ES6 global that is already available in chrome and node.js, so this makes perfect sense.

**Comment by nadako** [comment]
probably should do that before 3.2

**Comment by aduros** [comment]
Sounds good. Any other ES6 globals in there that could be moved?

**Comment by fponticelli** [comment]
`Console` is also not browser exclusive. Unfortunately not all the methods exposed in modern browsers are available in NodeJS.

**Comment by fponticelli** [comment]
the several typed arrays (ex: `Float32Array`) are also good candidates.
