### ISSUE TITLE
[cs] Erroneous "No overload found for this constructor call" warnings

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#4001]
Tested with latest Haxe from git.
Repro: Compile the following to C#:

package;

```
class BugTest {
  public function new(x:Float) {
  }

  public static function main() {
    new BugTest(0);
  }
}
```

Result: 
./BugTest.hx:8: characters 4-18 : Warning : No overload found for this constructor call

Expected:
No warning.

The generated code appears to be fine. This is a recent regression. There are other cases where this warning pops up as well, but I haven't yet found a simple repro.

**Comment by nadako** [comment]
this one actually generates `error CS0121: The call is ambiguous between the following methods or properties: 'BugTest.BugTest(haxe.lang.EmptyObject)' and 'BugTest.BugTest(double)'` for me

**Comment by waneck** [comment]
@nadako, I don't get this message. See if you can compile the test case. Maybe it's a mono/vcs problem

Anyway, it should be fixed now, @dogles. You'll still see 
```
/usr/lib/haxe/std/cs/internal/HxObject.hx:113: characters 31-60 : Warning : No overload found for this constructor call
```

But that's because of #4003 and should be dealt with soon!

**Comment by nadako** [comment]
@waneck 131d71481ee61bc3c2316f578235018ae59d7734 fixed it for me by adding a cast, if i revert that commit, there's no cast before `0` and it fails.
