### ISSUE TITLE
Exhaustive list of overloadable operators

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#4008]
Hi 

The doc ( http://haxe.org/manual/types-abstract-operator-overloading.html) is missing the exhaustive list of overloadable operators. I can't find it in google too. Maybe its related to (http://haxe.org/manual/types-numeric-operators.html)

I believe it should be in some reference page rather than the manual or did I miss something ?

Thanks !

**Comment by Simn** [comment]
I don't think there's any op other than `=` that you can't overload. Correct me if I'm wrong!

Either way this is a issue for HaxeManual.

**Comment by delahee** [comment]
@simn I was more loooking to [] or . or () yes.. obj(idx) is actually cool to have in c++ :)

**Comment by Simn** [comment]
Well, these are not exactly operators in Haxe context. Having an option to call abstracts like this would be quite interesting, but I'm a bit concerned about code readability when multiple such call-overloads are available.

**Comment by delahee** [comment]
Ok that is not a _true_ request, just an explain why I searched for the doc
:)
Le 16 mars 2015 12:55, "Simon Krajewski" <notifications@github.com> a écrit
:
