### ISSUE TITLE
Issue with JSFlatten

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4009]
I was using this kind of behavior to declare some extern class

```
package pack;
extern class MyClass {
   static function __init__() {
        untyped MyClass = myClassValueInJS;
   }
}
```

However this nows assign `pack.MyClass` instead `pack_MyClass` as jsFlatten should, because of ctx.type_accessor. Not sure how to fix this.

**Comment by nadako** [comment]
Why do you do that instead of `@:native`?

**Comment by ncannasse** [comment]
What if I want the expression to do some complex things ?

**Comment by Simn** [comment]
`__js__`?

**Comment by Simn** [comment]
P.S.: We should move away from using untyped like that, it makes so many assumptions about how the AST is treated by the generator.

**Comment by ncannasse** [comment]
Ok I could look more into the actual issue. The problem is that I'm doing the following:

```
package nodejs.webkit;

@:native('nodejs.webkit.$ui')
class UI {

	static function __init__() : Void untyped {
		__js__("nodejs.webkit.$ui = require('nw.gui')");
	}
}

extern class Clipboard {
	
	static function __init__() : Void untyped {
		Clipboard = UI.Clipboard;
	}
	
}
```

And because of flatten the nodejs package is not created so UI.__init__ fail.

Now if I use @:jsRequire for UI, Clipboard fails for the same reason.

Any idea ?

**Comment by nadako** [comment]
This should work:
```
@:jsRequire("nw.gui") extern classs UI {...}
@:jsRequire("nw.gui", "Clipboard") extern class Clipboard {...}
```
It'll generate two require calls, but I don't think that's an issue (we could look into analyzing/optimizing this in genjs).

**Comment by nadako** [comment]
also there's that `@:initPackage` meta and other hacks used in `js.JQuery` (https://github.com/HaxeFoundation/haxe/blob/development/std/js/JQuery.hx), but I find `@:jsRequire` much more appropriate for this.

**Comment by ncannasse** [comment]
Yes, I've updated to use the jsRequire with extra name. BTW it would be nice if http://haxe.org/manual/target-javascript-require.html would show the corresponding JS output
