### ISSUE TITLE
Compile Haxe Project to native library

### ISSUE THREAD

**Issue by kkirby** [HaxeFoundation/haxe#4013]
I checked all over, and I can't find an answer (or perhaps I'm not so good at searching). Anyways, is it possible to compile a project to a native library, basically exporting all classes using the language's built-in namespace paradigm and remove the requirement of the compiler's `-main <class>`. The use case would be to build a library in Haxe that could be compiled to a language and used like any other class/library native to that language. For example, compiling a PHP library and using it in a non-Haxe PHP project.

Thanks!

**Comment by Simn** [comment]
Try asking in haxelang google group or #haxe IRC on freenode.
