### ISSUE TITLE
Regression : int64 runtime detection

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#4022]
Hi, 

For some db drivers to function properly ( mongo ), we need to be able to detect int64 values. There are complex solutions but since int64 detection was possible before and now seem to no longer is, we have a problem.

Can we have some dirty but working "canonical" solution so that we can proceed and overcome the regression ?

CC @pperidont.
ref #4014
code causing problem :  https://github.com/motion-twin/mongo-haxe-driver/blob/master/org/bsonspec/BSONEncoder.hx

Thx !

**Comment by Simn** [comment]
There's Int64.is now.

**Comment by Simn** [comment]
... and I should list that in the migration guide.

**Comment by Simn** [comment]
done
