### ISSUE TITLE
3.2.0-rc1 release have 3.1.3 in some places

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#4023]
Root folder in binaries archive is haxe-3.1.3
OSX have installer-script title is "Haxe Toolkit 3.1.3" and package version is 3.1.3 both in pkg-info and in installer-script pkg-ref

**Comment by Simn** [comment]
I think I know why that happens, thanks for reporting.

**Comment by Simn** [comment]
@waneck: I have pushed again after tagging but the directories in e.g. http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux32/haxe_2015-03-16_master_a8c8e81.tar.gz are still named 3.1.3. What am I missing?

**Comment by jgranick** [comment]
This also is similar in the Windows installer

**Comment by Simn** [comment]
This has been resolved. I'm holding back on updating the binaries because we came across a small regression.
