### ISSUE TITLE
Class not found : javax.swing.JFrame

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/haxe#4027]
Class not found : javax.swing.JFrame
I have tried remap javax.swing:java.swing but will not work with haxelib's?  
The changes do not mention this and it requires re-releasing any haxelib's that use swing maybe it's only my one?  Do I need to update hxJava please clarify on release issues changes docs.

**Comment by Simn** [comment]
Shouldn't that be java.javax.swing.JFrame?

**Comment by waneck** [comment]
Can you provide more info on how to reproduce this? `javax` packages are translated to `java.javax` per haxe standard library naming requirements, if that's what you're after

**Comment by Justinfront** [comment]
haxelib install hxDaedalus
git clone https://github.com/Justinfront/hxDaedalus-Examples.git

then if you modify one of the swing hxml's ( running on mac yosemite ) eg:

https://github.com/Justinfront/hxDaedalus-Examples/blob/master/hxDaedalus-Examples/04-BitmapPathfiinding-Swing.hxml

by adding a remap line.

--remap javax.swing:java.javax.swing

The project still fails, so remapping would be nice fix but unfortunately it does not seem to help unless I got it wrong.

$ haxe 04-BitmapPathfiinding-Swing.hxml
/usr/lib/haxeLibrary/hxDaedalus/0,0,2/hxDaedalus/swing/BasicSwing.hx:3: characters 7-25 : Class not found : javax.swing.JFrame

if java.javax.swing.JFrame is the new correct package structure I can reupload the haxelib with changes, since I am not sure and other Haxelib's use swing and only our project that was effected, but obviously this is not mentioned in any breaking changes, translated standard naming or not.  But I am just reporting stuff I notice I don't really mind as so far they are easy to fix.

**Comment by waneck** [comment]
These types are accessible through `java.javax.swing.JFrame`
