### ISSUE TITLE
Bytes and nodejs

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#4028]
Some places now use explicit Uint8Array instead of BytesData, which is less usable on nodejs, where [Buffer](https://nodejs.org/api/buffer.html) is proper byte array.

Namely
js/_std/haxe/io/Bytes.hx
haxe/io/BytesBuffer.hx
haxe/io/BytesInput.hx

Maybe is does not matter, because anyway you'll need to override lots of stuff, but just had to mention - now there's more.

**Comment by ncannasse** [comment]
yes, we need to redefine Bytes as part of the https://github.com/HaxeFoundation/hxnodejs support and make a proper release for it (ping @nadako)

**Comment by nadako** [comment]
hxnodejs still needs some love (making sure that we have API fully compatible with node.js 0.12), but one could implement `Bytes` stuff for node.js already, hiding it behind `#if nodejs`, because that's what `hxnodejs` defines when used.

**Comment by lpetre** [comment]
FWIW: Some of this work has been done already [elsewhere](https://github.com/dionjwa/nodejs-std/tree/master/haxe/io).

**Comment by Simn** [comment]
What's the state here?

**Comment by nadako** [comment]
I think Bytes are safe to use with hxnodejs and node 4.0.0 now, because `Buffer` is actually a `Uint8Array` starting with that version. I remember we discussed that somewhere, but I can't find the issue now.
