### ISSUE TITLE
Macro & flat js packages

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#4030]
This is an abuse of macros, _but_, redefining a type with a build macro which has a method using a macro method returning `macro $p { ['a', 'b', 'Test', 'method'] } ('hello world')` targeting JavaScript fails to turn `a.b.Test` into `a_b_Test`.

Minimal test [code](https://gist.github.com/skial/a5dde7c3f7cd2c997168) using `3.2.0.rc.1`

**Comment by Simn** [comment]
Am I crazy or is that just because you add `@:native("a.b.Test")` to the type?

**Comment by skial** [comment]
Adding `@:native("a.b.Test")` hasn't stopped the class `a.b.Test1` from being flattened to `a_b_Test`. Even though the macro method is returning an [expression](https://gist.github.com/skial/a5dde7c3f7cd2c997168#file-test-js-L12) to a excluded type, shouldn't it still be flattened??

:confused:

**Comment by Simn** [comment]
I see, so the actual problem is that the type is being excluded?

**Comment by frabbit** [comment]
btw. i don't think that a path in native should be flattened at all.

**Comment by skial** [comment]
@Simn I don' think so, I'm expecting `macro $p{ ['path', 'to', 'random', 'Class', 'method'] }()` to generate the correct path `path_to_random_Class.method()` while targeting JavaScript, not `path.to.random.Class.method()`, see the [output](https://gist.github.com/skial/a5dde7c3f7cd2c997168#file-test-js-L12) from the test code. 

I'm assuming this is wrong as the expression is allowed without a warning/error from the compiler. Shouldn't it generate a field expression if the compiler thinks its valid?

@frabbit I haven't checked myself but does `@:native` generate different output on extern classes and/or enums? Even if the behavior changes I should, _hopefully_, be able to work around any changes.

**Comment by skial** [comment]
@Simn I've just [noticed](https://gist.github.com/skial/a5dde7c3f7cd2c997168#file-test-js-L5) it hasn't flattened the package in a method that wasn't being touch my the macro, so I reduced the [test code](https://gist.github.com/skial/b915837e6d928dacfd04).

`Compiler.exclude('a.b.Test')` prevents package flattening. Is this because of:
1. The compiler no longer knows about `a.b.Test` as soon as `Compiler.exclude` is called?
2. An internal flag is set to not generate target code for `a.b.Test` but the compiler still knows about it?

It _looks_ like __1.__ is happening, but if it was, wouldn't the compiler complain about an unknown identifier? :confused:

**Comment by Simn** [comment]
I think the problem is that Compiler.exclude makes the type extern and genjs assumes that extern paths should not be flattened.

This probably leads to a discussion about `@:nativeGen` and `@:hxGen` again. cc @waneck

**Comment by Simn** [comment]
#4418
