### ISSUE TITLE
3.2.0-rc.1; js; Bytes fastGet issue 

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#4032]
Found when using CRC32 inside it's [update](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/crypto/Crc32.hx#L44-L46): 

This output code is incorrect because of fastGet output:
(notice that b1 is used, but b1 has no .bytes?)

![screenshot 2015-03-16 14 44 35](https://cloud.githubusercontent.com/assets/236374/6671835/067941d8-cbeb-11e4-89ea-35b3c38b7cde.png)

**Comment by Simn** [comment]
The code in Crc32 looks correct to me. Bytes.fastGet expects a first argument of BytesData and that's what getData returns.

What confuses me is fastGet itself because it makes a bytes field access on BytesData, which on JS is typedeffed to js.html.ArrayBuffer. There's a comment saying `// this requires that we have wrapped it with haxe.io.Bytes beforehand` there but I don't know what that means.

@ncannasse: This manifests as a regression, could you please look at it today?

**Comment by underscorediscovery** [comment]
@Simn right, my initial assumption was the fastGet arg, but I refactored my description for what really was the cause - sorry for the confusion.

**Comment by ncannasse** [comment]
It seems that it's using fastGet while no haxe.io.Bytes has been constructed from the BytesData (which are now required to have .bytes properly initialized)

**Comment by ncannasse** [comment]
Usually one would do:

```
var b = haxe.io.Bytes.alloc(....)
var dat = b.getData();
....
haxe.io.Bytes.fastGet(dat,index);
```

**Comment by ncannasse** [comment]
Ok my bad, it seems I've changed things between different versions. working on fixing it.
PS : it seems we don't have any unit test for either Crc32 or haxe.io.Bytes.fastGet

**Comment by Simn** [comment]
We don't, but then I don't really understand why something like haxe.crypto has to exist in our standard library in the first place.

**Comment by ncannasse** [comment]
@Simn because the philisophy of haxe std lib is to come with "batteries included"

**Comment by Simn** [comment]
I'll remind you of that next time we're fighting over adding something like haxe.ds.Either.

**Comment by Simn** [comment]
P.S.: this fix is present in the latest binaries. I prefer to overwrite them so testing can continue, at least until we formally announced the release.

**Comment by underscorediscovery** [comment]
Ok, I'll test on latest download and report back shortly

**Comment by underscorediscovery** [comment]
Well, I tested and the bytes part succeeds now - but the resulting CRC check failed. It worked before with it enabled. For now, I disabled the CRC check on the png reader (from `format` btw) and it worked (the images loaded just fine).

I think that means something might still be weird there, I'll try test more in the morning.

**Comment by Simn** [comment]
Any chance to get a quick reproducible example for this? I don't mind if it uses format.

**Comment by underscorediscovery** [comment]
https://github.com/underscorediscovery/haxe_test_crc32_err

Here @Simn, you can make a test from that, I'll remove this repo when we're done with it.

**Comment by Simn** [comment]
@ncannasse: Tracing the result of `haxe.io.Bytes.fastGet(b,i);` in Crc32.update suggests that the result is always undefined in the browser (it works in node.js though).

Any hints? It might be related to how the format library creates the Bytes objects.

**Comment by ncannasse** [comment]
@Simn I have no idea why it would do so... format simply calls input.read(size) which does a Bytes.alloc

**Comment by ncannasse** [comment]
@Simn if it returns undefined it means the `.bytes` is actually initialized ? then what does it contains (or is it out of range?)

**Comment by Simn** [comment]
`trace(untyped b.bytes, untyped b.bytes.length);`
->
`Crc32.hx:47: [object ArrayBuffer],null`
->
???

**Comment by Simn** [comment]
Oh wait, it's not supposed to have a length field.

**Comment by Simn** [comment]
`trace(i, untyped b.bytes, untyped b.bytes.byteLength, untyped b.bytes[i]);`

In node:

```
Crc32.hx:47: 0,[object ArrayBuffer],13,0
Crc32.hx:47: 1,[object ArrayBuffer],13,0
Crc32.hx:47: 2,[object ArrayBuffer],13,0
Crc32.hx:47: 3,[object ArrayBuffer],13,128
etc.
```

In browser:

```
Crc32.hx:47: 0,[object ArrayBuffer],13,null
Crc32.hx:47: 1,[object ArrayBuffer],13,null
Crc32.hx:47: 2,[object ArrayBuffer],13,null
Crc32.hx:47: 3,[object ArrayBuffer],13,null
```

**Comment by Simn** [comment]
```
class Main {
	static function main() {
		var raw = haxe.io.Bytes.alloc(1);
		raw.set(0, 1);
		var data = raw.getData();
		trace(untyped data.bytes[0]);
	}
}
```

Traces 1 in node, undefined in browser.

**Comment by underscorediscovery** [comment]
Is the Bytes class trying to write properties to Native types in the browser by chance?

**Comment by Simn** [comment]
It indeed does.

**Comment by underscorediscovery** [comment]
nvm, I was testing along a different line, but I think the _instance_ can have members. static members on `ArrayBuffer` would potentially be rejected which would vary by platform/browser.

**Comment by Simn** [comment]
@ncannasse: This is the issue which blocks me from releasing another RC right now.

**Comment by ncannasse** [comment]
That was actually quite a stupid mistake on my side, it only worked on Node because it seems to allow array access on ArrayBuffer, which browser does not (sadly, that would save us the whole mess of having to store an UInt8Array view of it into itself)

**Comment by underscorediscovery** [comment]
woo!

**Comment by Simn** [comment]
I don't really understand how our CI could miss this though. I'll check the tests.

**Comment by Simn** [comment]
This fails on Safari and iphone 8 of all things:

```
Test.hx:251: ABORTED : TypeError: undefined is not an object (evaluating 'bd.bytes[i]') in unit.TestBytes.testFastGet
Test.hx:254: STACK : testFastGet@http://localhost:2000/bin/unit.js:9867:20 callMethod@http://localhost:2000/bin/unit.js:484:19 main@http://localhost:2000/bin/unit.js:9094:25 global code@http://localhost:2000/unit-js.html:11:31
```

**Comment by Simn** [comment]
Looks like this is going to be our blocking issue for 3.2.0 again.

**Comment by ncannasse** [comment]
I'll try to reproduce on the Mac at work tomorrow, since I don't have Safari at home. Anyone which can reproduce/investigate it in the meanwhile is welcome

**Comment by ncannasse** [comment]
Can't reproduce on iPad / Safari / iOS 7.0.4 
Can't reproduce on Android 5.0.1 / Chrome

**Comment by Simn** [comment]
In our CI it's specific to these:

- Requesting: safari 8 on OS X 10.10
- Requesting: iphone 8.1 on OS X 10.9

**Comment by ncannasse** [comment]
Yes, just wanted to log what I'm testing so we know how narrow the problem is. The thing is that I have not device to test against so I have to wait for CI answer after each commit. Not the must fun way to debug

**Comment by andyli** [comment]
Hey, you may use "manual testing" in SauceLabs, which is kind of an online VNC controlling a VM. With [Sauce Connect](https://docs.saucelabs.com/reference/sauce-connect/) setup properly, you can test files hosted locally - i.e. open http://localhost:2000/index.html in the VM, while you launched `nekotools server` in the local dev machine.

Just register a "Open Sauce" plan in SauceLabs: https://saucelabs.com/signup
Fill in the "Repository URL" with your github profile URL.

**Comment by Simn** [comment]
Wow, that's amazing! I just tried it out and got it working immediately following the instructions. I am now looking at unit-js.html on the Android 4.0 browser through my desktop browser and can see the failing tests.

**Comment by Simn** [comment]
Holy crap, it even automatically records a screencast of what happened so you can show it to others: https://saucelabs.com/tests/9cab36132cff4f66aef5bfc02e4559da

**Comment by ncannasse** [comment]
I have fixed then Safari bug but I'm out of solution for the Android one. I guess we should simply skip our Float64Array unit tests if it's not supported on the browser.

**Comment by Simn** [comment]
I thought the unsupported detection was the actual problem here.

**Comment by Simn** [comment]
Looks like this works fine now!
