### ISSUE TITLE
Compilation server: spurious compiler errors about missing @:native extern functions

### ISSUE THREAD

**Issue by jonathanhardie** [HaxeFoundation/haxe#4035]
Using the compilation server, I'm seeing things compile correctly the first time, and then after a short timespan, subsequent compiles are getting errors such as "Class<Glfw> has no field getTime", where getTime refers to a function tagged with @:native("glfwGetTime").

This has only broken in the last few days.

It's fine for a couple of compiles once I kill and restart the compilation server.

Targeting CPP, OSX.

**Comment by ncannasse** [comment]
@Simn when does @:native replaces the method name ? Is it something we restore as part of cl_restore() ?

**Comment by Simn** [comment]
`apply_native_paths` runs after `save_class_state` if that's what you're asking.

**Comment by Simn** [comment]
... but it doesn't actually save the `cf_name` and then rebuilds the PMap from what I can tell. I can try to fix this but I can't test it right now.

**Comment by jonathanhardie** [comment]
Everything is back to normal for me now, thanks!

**Comment by Simn** [comment]
Thanks for testing!
