### ISSUE TITLE
[flash] Can't use null as len argument for 'String.substr'

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#4036]
Flash is the only target where a 'null' length parameter to 'String.substr' behaves as 0.

I'm not sure that this is a bug, after all len is optional but typed as 'Int' (not 'Null<Int>'). However, accepting null as "missing", like the other targets do, allows cleaner wrapping of that method; I use that to allow it to be replaceable by, for instance, 'Utf8.sub'.

```
class Issue {
    static function main()
    {
        trace("abc".substr(0, null));  // "" on flash, "abc" on other targets
    }
}
```

**Comment by Simn** [comment]
Bug or not?

**Comment by jonasmalacofilho** [comment]
Note: a user-defined function works as expected.

    static function userDefined(?len:Int)
    {
        if (len == null)
            len = 0xff;
        return len;
    }
    ...
    trace(userDefined(null));  // 255

**Comment by ncannasse** [comment]
All flash String functions are using native integers instead of null'able ones, making it incompatible with EcmaScript since null will be automatically cast to 0. I don't think there's anything we can do for this.
