### ISSUE TITLE
[suggestion] haxe.Template - Macros rename

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4038]
I'm documenting `haxe.Template` for the manual. I found the execute function has a parameter called macros, which is basically a object with template functions. In the old documentation http://old.haxe.org/doc/cross/template#macros 

It has nothing to do with the known Haxe macros (you know, the _there's a macro for that™_  macros). This confused me a bit on what does (is it a compile-time thing, no). 

You may consider to rename the argument to "functionsObject" or something else creative. I think this shouldn't have to break anything.

You get nice documentation in return :wink:

**Comment by delahee** [comment]
Big big breaking change that is, my 2 cent is it cannot be scheduled for
3.2.

**Comment by Simn** [comment]
Surely changing function argument name wouldn't break anything even in the MT codebase.

But I don't like functionsObject and I don't have a good alternative suggestion. Also it has been like this for years, so while I can see that it could be mildly confusing, I don't think it's a real problem. Just document it as "Template macros".

**Comment by markknol** [comment]
Ok thanks that is a clear answer, however i still think its confusing because it conflicts with normal macros and seems a simple tweak if anyone finds a more descriptive name. Anyway, in that case i'll make sure the docs are clear.
