### ISSUE TITLE
Crash with UInt type, should have `to Float` in the enum?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4039]
I have had issues with UInt in Haxe 3.2

The latest of which, I just noticed that this progression crashes Neko:

```haxe
private static var color:UInt = 0xFFFFFF;
...
Actuate.transform (sprite, 1).color (color, 1); // color is a Float
...
var properties = { colorValue: color };
...
var color:Int = properties.colorValue
```

This chain leads to a crash on Neko ("Uncaught exception - Invalid operation (>>)"). If I change the `color` method signature to `Int` instead of `Float` (which is more appropriate anyway) the crash is fixed. However, I expect you should be allowed to pass `UInt` into a `Float` value, like above, without an error.

When I add `to Float` to https://github.com/HaxeFoundation/haxe/blob/development/std/UInt.hx#L98, there is no more crash. Perhaps that is the correct solution?

**Comment by ncannasse** [comment]
`>>` in neko will not accept a left value which is a runtime Float. But without Dynamic it's not possible to assign a Float to UInt (unless I'm mistaken)

**Comment by jgranick** [comment]
It is interesting, you do need a Dynamic to make it happen (in a simple example), though I think I hit areas where it may not have required a Dynamic, I'm not sure.

```haxe
var uintValue:UInt = 100;
var floatValue:Float = uintValue;
var dynamicValue:Dynamic = { value: floatValue };
var intValue:Int = dynamicValue.value;
trace (intValue >> 16);
```

Although it is a little convoluted, the above works in Flash, C++ and JavaScript, but Neko crashes without `to Float` in `UInt` or adding a `Std.int`

Perhaps this can be chalked up to Neko's general distaste for dynamic values

**Comment by ncannasse** [comment]
The problem is that UInt -> Float conversion will create an overflowed Int, so when you assign back to Int you are creating the same issue as you would assign a String. You need to use Std.int() for that, but that will most likely clamp to 2^31-1

**Comment by jgranick** [comment]
Thanks Nicolas, that makes sense :smile:
