### ISSUE TITLE
[macro] order of structure fields not preserved?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4041]
Subj. Looks like the order of structure fields is not preserved for macros (or in internal structures, I don't know):
```haxe
import haxe.macro.Context;

typedef A = {
    field2:Int,
    field1:Int,
    field3:Int,
}

class Main {
    static function main() {
        f();
    }

    static macro function f() {
        switch (Context.follow(Context.getType("Main.A"))) {
            case TAnonymous(_.get() => anon):
                for (f in anon.fields)
                    trace(f.name);
            default:
        }
        return macro {};
    }
}
```
outputs:
```
Main.hx:18: field1
Main.hx:18: field2
Main.hx:18: field3
```
while I'd expect it to output them in the same order as defined in the structure

**Comment by Simn** [comment]
This has always used a PMap internally which has undefined key order. I don't think it is necessary to retain the order as far as the type itself is concerned.

**Comment by nadako** [comment]
Maybe we could store order in a meta or something? I'm trying to auto-generate editor from a structure type and it would be useful output fields in the same order as defined in code.

**Comment by Simn** [comment]
Storing redundant information for such a rare use-case is not a good idea in my opinion.

**Comment by nadako** [comment]
Actually, @ousado gave me an idea - we can compare field's `pos` to retreive an order. That'll do for me.

**Comment by Simn** [comment]
Somehow the fact that he has ideas like that really scares me...
