### ISSUE TITLE
`switch` unreliable on Neko with abstract

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4049]
Okay, this one's a bit strange.

I have created two enums, one for GamepadAxis and one for GamepadButton:

https://github.com/openfl/lime/blob/master/lime/ui/GamepadAxis.hx
https://github.com/openfl/lime/blob/master/lime/ui/GamepadButton.hx

I am handling them in a project, like this:

```haxe
public override function onGamepadAxisMove (gamepad:Gamepad, axis:GamepadAxis, value:Float) {
	
	trace ("Axis: " + axis + " = " + value);
	
}


public override function onGamepadButtonDown (gamepad:Gamepad, button:GamepadButton) {
	
	trace ("Button: " + button);
	
}
```

For some reason, the `switch` for the axis `toString` falls through to "UNKNOWN" every time, even though the values are between 0 and 4. I can do `if (axis == 0)` and `true`, in the `toString` I can even use `if (this == 0)` instead of the `switch` and the return is correct.

The `GamepadButton` `toString` works properly. Compiling to C++ works properly. This occurs on Neko, and I can't see any difference between them

**Comment by Simn** [comment]
Could you please report your issues by making a reproducible example that can just be executed and shows the problematic behavior?

**Comment by jgranick** [comment]
Sorry for the false alarm, it was a rogue `alloc_float` instead of `alloc_int` in C++
