### ISSUE TITLE
[java backend] parseFloat is incorrect

### ISSUE THREAD

**Issue by exFalso** [HaxeFoundation/haxe#4051]
```Std.parseFloat("1154874.2868745863")``` returns ```1154874.2868745865``` (last digit)

I wonder, why was Std.parseFloat reimplemented in the first place? There is a standard java function to parse doubles: Double.valueOf (or Double.parseDouble).
And indeed, if I replace the implementation at https://github.com/HaxeFoundation/haxe/blob/development/std/java/_std/Std.hx#L64 with ```@:functionCode('return Double.valueOf(x);')``` it parses correctly.

Even if there are certain pre/postconditions specific to haxe that the standard java implementation doesn't satisfy I would still strongly suggest creating a wrapper around Double.valueOf instead of trying to write double parsing by hand.

**Comment by Simn** [comment]
@waneck: Can you check if we can get this in 3.2?

**Comment by waneck** [comment]
Sure. I'll fix it today

**Comment by waneck** [comment]
The test fails on Flash. I guess there's nothing to be done there, right?

**Comment by Simn** [comment]
It's quite interesting that it returns the same wrong value your implementation returned.

**Comment by exFalso** [comment]
Thank you for the fix. However ```parseFloat``` now fails on strings with '+' in them:
```parseFloat("1.0e+1")``` returns NaN. I think there is a switch case missing at Std.hx:166:
```
 				case '+'.code if (found && !hasEPos && hasE):
					hasEPos = true;
```
(and the corresponding initialization of ```hasEPos = false```)
Should i submit a new issue for this?

**Comment by Simn** [comment]
@waneck: Please check for 3.2.

**Comment by ncannasse** [comment]
Seems like we need more unit tests to cover all the cases

**Comment by exFalso** [comment]
I wrote a small tool that uses QuickCheck to check differences between backends:
https://github.com/exFalso/haxe-qc/
It only checks js/java, but it can be extended for other backends.

I ran it for Std.parseFloat, Std.parseInt and Std.int. It caught a few more differences, here are some sample inputs that behave differently.
Std.parseFloat:
"+7"
"6e"
"6E"
" 4"
"0x0"

Std.parseInt:
"0x	C"
"\v0", "\f0" (only found these two whitespaces, but there might be exotic unicode whitespace characters as well)
"0x+A"

No differences for Std.int

**Comment by nadako** [comment]
ewww, on C# `Std.parseFloat("2.426670815e+12")` returns NaN

**Comment by nadako** [comment]
@exFalso could you maybe make a pull request adding additional tests for `Std.parse*` functions similar to how it's done in 8a0460bde2ab2bf17256c52e7a55dde13a39a942?

**Comment by nadako** [comment]
The `+` case should be covered now in java/c#. But unit tests could still be improved, so leaving the issue open.

**Comment by exFalso** [comment]
@nadako https://github.com/HaxeFoundation/haxe/pull/4132

**Comment by waneck** [comment]
I think most issues about this are now fixed. Please feel free to reopen/create another issue if any other issues are still found
