### ISSUE TITLE
--gen-hx-classes incorrectly outputs module subtypes

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4052]
Subj. For example `haxe.Constraints.Function` will be outputted as `haxe.Function`.

**Comment by Simn** [comment]
I kind of expect it to do that. What's the problem?

**Comment by nadako** [comment]
The problem is that externs generated that way can't be loaded by haxe right away and one has to handle every particular case like `haxe.Function`.

It's not too important though because we have `haxe.macro.Printer` that works just right.

**Comment by Simn** [comment]
Yeah making extern of haxe classes is not really what this thing was made for. At this point I prefer to just leave it alone and focus on more advanced methods like haxe.macro.Printer as you said.
