### ISSUE TITLE
Feature request: -D no-run for --interp and --run

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4053]
I would like to have a way to just "compile" but not really run a build when using `--interp` or `--run`. Probably introduce a define `-D no-run`.

The reason:
I found myself often compile a project frequently during coding, just to type-check everything to ensure I haven't made any silly mistake. When using `--interp` or `--run`, this workflow is problematic since it would actually perform something on my system. Think writing a haxe script to delete files...

**Comment by ncannasse** [comment]
Can't you simply compile for neko with --no-output ?

**Comment by andyli** [comment]
That is close, but since there is subtle difference between nake and the macro context so I think it is not accurate.
Also since it needs changing the target flag, it is not handy as `haxe -D no-run build.hxml`.

**Comment by Simn** [comment]
Maybe --no-output should affect --interp too?

**Comment by andyli** [comment]
Yes, that sounds reasonable!

**Comment by Simn** [comment]
Let's do this later though. The internal logic for --interp actually implies --no-output but then treats it as a special case.
