### ISSUE TITLE
Getting the wrong absolute path from FileSystem.fullPath on Linux

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4055]
This just recently happened to me on Linux, using the latest development build:

    var path = FileSystem.fullPath ("Export/flash/obj/assets.swf");

The file was located at "/home/joshua/Projects/Samples/DisplayingABitmap/Export/flash/obj/assets.swf"

I was given "/storage/Projects/Samples/DisplayingABitmap/Export/flash/obj/assets.swf" which did exist, but that was a directory off a mounted Windows drive.

Is there an alternative way to get a full path, relative to the current working directory?

**Comment by Simn** [comment]
Probably with a leading ./ but this is not really an issue report.

**Comment by waneck** [comment]
I feel it's very strange that fullpath expands a non-absolute path like
that.
It seems to me that something's wrong on our side

**Comment by Simn** [comment]
Well feel free to break into his house to find out the setup, compiler arguments, environment variables, what target this is about in the first place and whatever else might be necessary to even start investigating possible causes (which are then almost certainly not a Haxe issues but something in hxcpp/neko).

**Comment by waneck** [comment]
Closing due to lack of feedback ( @jgranick )
