### ISSUE TITLE
[php] issue with Bytes.fastGet

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4060]
```
class Main {
	static function main() {
		var b = haxe.io.Bytes.alloc(10);
		var bd = b.getData();
		b.set(1,20);
		Sys.println(haxe.io.Bytes.fastGet(bd, 1));
	}
}
```

```
	static function main() {
		$b = haxe_io_Bytes::alloc(10);
		$bd = $b->b;
		$b->b[1] = chr(20);
		Sys::println(ord($bd[1]));
	}
```

This prints 0 instead of the expected 20. As usual I'm at a loss here because it "looks" like this should work by accessing `$bd[1]`. It works if I change that to `$b->b[1]` which in my mindset is equivalent.

@mockey @tml: What's my misconception here and what can we do about it?

**Comment by tml** [comment]
PHP values are "copy on write"; once you change the value in `$b->$b` (via `$b->b[1] = chr(20);`), the old value is copied into `$bd`, and they are no longer attached. You would have to do references (`$bd =& $b->b`) to make this work, but honestly, that's largely not considered very good PHP style.

**Comment by mockey** [comment]
As the underlying type for BytesData is just a (Native)String in PHP (is this really good BTW?)
`$bd = $b->b;`
is passed by value here. So a quick fix would be passing by reference as @tml described above. A better fix would be maybe using an Array<Int> for BytesData...

**Comment by frabbit** [comment]
i guess it's because string manipulation is faster in some applications (http://www.sitepoint.com/high-performance-string-concatenation-in-php/), but i'm not sure if that's the general case.

**Comment by mockey** [comment]
Is string-concatenation needed for working with Bytes? For BytesBuffer maybe...

**Comment by frabbit** [comment]
@fponticelli why did you choose `NativeString` instead of `NativeArray` for `BytesData`?

**Comment by fponticelli** [comment]
@frabbit as I could possibly remember that.

**Comment by frabbit** [comment]
hehe, ok but i guess if it's a good idea to change this now.

**Comment by mockey** [comment]
Maybe because neko uses NativeString as well?

**Comment by frabbit** [comment]
oh, i wanted to say that it's not a good idea to change this now ;)

**Comment by Simn** [comment]
So what _is_ a good idea?

**Comment by waneck** [comment]
As far as I know, normally PHP bytes manipulation is done with strings indeed

**Comment by mockey** [comment]
Uhm, just a question, is this really intended that `b.getData()` returns a reference to `b.b` (the BytesData object) and not its value (i.e. data)?

**Comment by mockey** [comment]
Here's a quick and dirty fix for this: #4064
Not really nice, but the only way I could think of (without touching OCaml).

**Comment by Simn** [comment]
Would it help if we added native code interpolation for PHP? E.g. `__php__("{0}.something", this)` where all occurrences of `{0}` get replaced with `this`.

**Comment by frabbit** [comment]
i'm working on an abstract for bytesData, and yes @Simn  interpolation would be helpful. @mockey does your hack has sideeffects depending on context?

**Comment by mockey** [comment]
Generally that would be good. It would save the `var r = this` assignment here at least.
Being able to put `__php__` code (function declarations) into the class body would be good also. It's only possible in the function body, so it needs `__init__` here. Is this possible on other targets?

**Comment by Simn** [comment]
Interpolation is supported now.

**Comment by mockey** [comment]
That's pretty cool. I can get rid of that helper function actually. PR updated.

**Comment by mockey** [comment]
@frabbit: What context do you mean exactly? Reflection?

**Comment by frabbit** [comment]
in general when multiple assignments of a bytesdata instance to other variables are done?
```haxe
var x : BytesData = ....;
var y = x;
// modify y here
// are y and x still the same?
```

**Comment by frabbit** [comment]
i'm currently creating a small wrapper as BytesData object  which wraps a nativestring as the only property. Like this:
```haxe
class BytesDataWrapper {
		public var s : php.NativeString;
		public function new (s:php.NativeString) { this.s = s;}
	}
```

**Comment by mockey** [comment]
Direct assignment with BytesData won't work that way. When it's a NativeString the value will be assigned. Maybe it's possible to hack the reference in the abstract. But maybe it's easier to just wrap the NativeString in a NativeArray and pass that around?

**Comment by frabbit** [comment]
ok, i made a pull request, would be great if someone take a look, especially performance wise.
https://github.com/HaxeFoundation/haxe/pull/4065

**Comment by frabbit** [comment]
i currently used a class as a wrapper, what would be the best choice wise?

**Comment by mockey** [comment]
Ah, that `BytesDataWrapper` is your wrapper already, now I understand. A NativeArray should have the least overhead on PHP, I think.

**Comment by frabbit** [comment]
ok, i tried with NativeArray but i reverted it because it causes to much much trouble because of call-by-value semantics.

**Comment by mockey** [comment]
Yeah, arrays are passed by value (i.e. copied) in PHP indeed. I thought that changed with PHP5.x, but it didn't. Ah, the wonders of PHP...
So the only possibility would be using a base object (stdClass), but I guess that wouldn't perform muc different to your wrapper class.

**Comment by Simn** [comment]
At this I think we should just leave it broken for 3.2. It's not a regression from 3.1.3 but whatever fix we attempt might introduce other problems. I'll go ahead and disable the related test.

**Comment by frabbit** [comment]
yes, without more extensive tests i wouldn't apply my pr now. But i think that's a solid way to implement BytesData for PHP, but the extensive and also repetitive uses of untyped in the php target are quite high, so it's hard to say if there are sideeffects. 

@mockey did you checked my pr with your codebase? I just did some tests on one project where it worked fine, the unit tests pass too. But i don't have a php-project with extensive uses of Bytes, BytesBuffer etc.. It would be nice to check such a code base.

**Comment by mockey** [comment]
@frabbit: Yes, I checked and everything seemed to work so far. But I have no real extensive usage of Bytes here, just the usual stuff, where it's used, like Http. Also I had no errors in there before, so no referencing of BytesData or so...
I agree that this is the right way for implementation (wrap the string in an object), the details could be discussed, though. Maybe instead of the wrapper and the abstract a real ByteArray class wrapping a NativeString for the data would also be possible?
Anyway, it's probably best to leave this for the new PHP target.
