### ISSUE TITLE
Completion inside interpolated string doesn't work consistently

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#4062]
Related to: https://github.com/snowkit/atom-haxe/issues/23

**Works** before `\n`:
```haxe
var arr = new Array();
var str = '${arr.|}\ntext';
```

**Doesn't work** after `\n`:
```haxe
var arr = new Array();
var str = 'text\n${arr.|}';
```
Haxe server output: `Interp.Invalid_expr`

**Doesn't work** when the string is not finished, while any other completion would work with just the code before the cursor:
```haxe
var arr = new Array();
var str = 'text\n${arr.|
```
Haxe server output: `Unclosed string error`

**Comment by nadako** [comment]
I'm surprised that completion works at all inside an interpolated string, but that's something we could probably make right. I'm not sure how complicated is it though.

**Comment by Simn** [comment]
#3974
