### ISSUE TITLE
Unconsistent #if macro #else in Display mod

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#4063]
Hi, if i'm not missing something here, it seems that 
# if macro #else #end behaves differently than #if macro #end #if !macro #end

for display mod.

Example:
if we ask display for local3.| position. when local3 is defined in #if !macro #end
see: http://try.haxe.org/#3CA70
it works as expected

if we ask display for same position but when loal3 is defined in the #else of #if macro we get "No classes found in local3"
see; http://try.haxe.org/#b12C7

**Comment by sebpatu** [comment]
Sorry try.haxe did not saved the code, because it does ot compile with #if macro.

===============
First case is:
class Test{
	function new() {}
	
	#if macro 
	var local2:String ;
	#end
	#if !macro 
	var local3:String ;
	#end
	
    static function main() 
    {
        (new Test()).test();
    }
    
   function test():Void
   {
        local3.;
   }
}

===== second case (with issue) is:
class Test{
	function new() {}
	
	#if macro 
	var local2:String ;
	#else
	var local3:String ;
	#end
	
    static function main() 
    {
        (new Test()).test();
    }
    
   function test():Void
   {
        local3.;
   }
}

**Comment by Simn** [comment]
Is this a necessary limitation?

**Comment by ncannasse** [comment]
I don't think it is.

**Comment by Simn** [comment]
We'll discuss the `#if macro` situation in another issue.
