### ISSUE TITLE
Allowing users to use @:coreApi

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4066]
I find @:coreApi to be quite useful when writing cross platform code, since it allows to make sure that all the platforms follow exactly the specification, while still keeping the code separated into several files (one per platform).

Actually that's quite similar to the restriction of an "implements", but it also enforces static vars, which implements does not. It's also more easy to use because you don't have to use a factory to create an actual implementation of the interface.

However @:coreApi is currently only available for our std library implementation, because the way it works is when a @:coreApi class is found, we will load the "reference" class using only the std lib class path and compare the methods/vars signatures.

I'm open to suggestions about the way users could use it.

I was thinking that if a module is not found, we can look in  my/package/_js/ sub directory (if we are compiling for JS), but then where do we store the original signature of the reference type ?

**Comment by Simn** [comment]
I don't like `@:coreApi` very much because you cannot share implementations unless you factor them out in other classes and manually add calls to them. If we focus on anything it should be a compile-time inheritance mechanism which forces defining methods that have no expression in the "base class" (unless "abstract" in the Java-sense?) and allows (but does not force) overriding all other fields.

**Comment by ncannasse** [comment]
we could tag "inherited" methods in our original type, but then that would require to force the original type to be loaded before we build our platform type, and then delay the structure check at a later stage. Not very hard to change, and could work also for users if we find a nice way for them to use @:coreApi

**Comment by Simn** [comment]
I would like to lose the target restriction here so it can be used for other things than target-specialization, which is usually taken care of by the -cp order or conditional compilation anyway.

If we had something like `class Bytes implements macro std.haxe.io.Bytes` that behaves like I described above you could very quickly make specializations.

**Comment by ncannasse** [comment]
@Simn that still does not allow to have a separate file per platform

**Comment by nadako** [comment]
See related discussion #3285

**Comment by Simn** [comment]
This is strangely related to #4249: In both cases we want to skip a definition for some reason and resolve to a backup definition. I think we can solve both issues more or less elegantly by keeping track which class path was used to resolve a given module, and ignoring that specific class path when we "try again".

**Comment by ncannasse** [comment]
Talking a bit more about the topic, I propose that we have the following:

 - when loading a file, we will check first if in the same directory `<platform>_MyModule.hx` exists
 - if it uses `@:coreApi`, we will resolve again with the `cross` platform, so it will hit the "common file".
 - #3285 is related but orthogonal, I'll decide on this one separately, but that seems like a good idea.

**Comment by ncannasse** [comment]
@Simn suggested using `MyModule.<platform>.hx` which is a good idea, I've updated my proposal

**Comment by ncannasse** [comment]
Actually since the `.js.hx` automatically mean there is a `.hx` as well, this automatically imply `@:coreApi`, so we shouldn't have to declare it and can directly test the implementation matching against the "core" file.

**Comment by ncannasse** [comment]
I have implemented `.js.hx` loading, it works with `@:coreApi` but only if found in std class path, because we filter the class path in core context, so libraries can't use @:coreApi.

I will have to review this part by only filtering out the platform/_std paths, 
I'm not sure if we want to automatically imply @:coreApi for platform-specific files, since it is very strict and requires explicit typing of fields.

**Comment by sonygod** [comment]
@:coreApi can not allow use in hashlink,

**Comment by Simn** [comment]
I think we can close this.
