### ISSUE TITLE
"Not_found" when compiling for js

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#4067]
I'm currently testing HaxePunk against the rc2 of haxe 3.2 and openfl 3,
when building for html5 (so js) I get this error:
```
> lime test html5 -debug
Not_found
> haxe bin/html5/haxe/debug.hxml (equivalent to the previous lines)
Not_found
```
with debug.hxml:
```
-main ApplicationMain 
-cp /home/ibilon/Code/Projects/HaxePunk
-D HaxePunk=2.5.3
-cp /usr/lib/haxe/lib/openfl/git
-D openfl=3.0.0-beta
-cp /usr/lib/haxe/lib/lime/git
-D lime=2.2.1
-cp src
-D openfl-next
-D tools=2.2.1
-D no-compilation
-D lime-opengl
-D openfl-html5
-D canvas
-D lime-html5
-D html5
-D web
--remap flash:openfl
-js bin/html5/bin/Main.js
-cp bin/html5/haxe
-D html5
--macro allowPackage("flash")
-debug
```
`bin/html5/bin/Main.js` isn't created.

I thought it could be a macro, but most likely it'd use trace, so the output wouldn't look like this.

Could this be an error printed by the compiler? If so, any ideas on how to figure out why?

**Comment by Simn** [comment]
Can you set the environment variable OCAMLRUNPARAM=b and paste the stacktrace it outputs?

**Comment by ibilon** [comment]
```
OCAMLRUNPARAM=b haxe bin/html5/haxe/debug.hxml
Fatal error: exception Not_found
Raised at file "list.ml", line 179, characters 16-25
Called from file "filters.ml", line 143, characters 12-128
Called from file "list.ml", line 84, characters 24-34
Called from file "filters.ml", line 1046, characters 22-29
Called from file "list.ml", line 73, characters 12-15
Called from file "filters.ml", line 1052, characters 2-46
Called from file "list.ml", line 73, characters 12-15
Called from file "filters.ml", line 1147, characters 2-59
Called from file "main.ml", line 1513, characters 2-27
Called from file "main.ml", line 641, characters 3-11
Called from file "main.ml", line 1747, characters 1-35
```

**Comment by Simn** [comment]
@nadako: Looks like js._Boot.HaxeError is not found. I'm guessing DCE problem of some sort.

**Comment by Simn** [comment]
Actually that filter runs long before DCE. Maybe we don't compile Boot.hx at all in this case?

@ibilon: Could you compile with -v and paste the result?

**Comment by ibilon** [comment]
I tried why `-dce no` and it printed the exact same trace.

http://pastebin.com/spCgwEFE

**Comment by Simn** [comment]
Parsed /usr/lib/haxe/lib/lime/git/js/Boot.hx

Lime issue, they override our Boot.hx. That's something they should fix.

**Comment by nadako** [comment]
Look what I found: https://github.com/openfl/lime/blob/master/js/Boot.hx

**Comment by ibilon** [comment]
Thanks for the help.
I'll report the error at lime's.
