### ISSUE TITLE
Modulo of negative number

### ISSUE THREAD

**Issue by Masadow** [HaxeFoundation/haxe#4068]
Hi guys,

I don't know if it has been fixed in the new haxe release, but if I try to get the modulo of a negative number, it gives me a negative result.

For example, `-30 % 100` returns `-30` instead of `70`

**Comment by Simn** [comment]
That's how modulo works.

**Comment by frabbit** [comment]
@simn it depends ;) http://stackoverflow.com/questions/2215318/difference-between-modulus-implementation-in-python-vs-java

**Comment by Simn** [comment]
If it's just python that's straying here we should fix it in genpy.

**Comment by Simn** [comment]
Should be done for 3.2.0.

**Comment by frabbit** [comment]
Yes, i will look at this this tomorrow.

**Comment by frabbit** [comment]
fixed in https://github.com/HaxeFoundation/haxe/commit/c3952764120511f53142966f8d3d570b3ac3c7d6
