### ISSUE TITLE
[Docs] - js.html.Element.innerText should be js.html.Element.textContent?

### ISSUE THREAD

**Issue by cathalgarvey** [HaxeFoundation/haxe#4069]
Hi all,
Had a confusing bug while trying to put together a Haxe->VanillaJS app where the compiler insisted `js.html.Element has no field innerText` while the [haxe API docs disagreed here](http://api.haxe.org/js/html/Element.html#innerText). Changing `innerText` to `textContent` fixes the compiler error and, I think, does what I mean to do.

I know "site Haxe" is by now quite outdated from "git Haxe", and I'm working from git Haxe, so maybe this has been fixed in the git docs, but in case not I couldn't find any other issues referencing these properties.

**Comment by Simn** [comment]
@aduros: Is that intentional?

@cathalgarvey: The API docs refer to the latest stable Haxe version. We will update them once 3.2.0 has been released.
