### ISSUE TITLE
public api should print the haxe version it refers too

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#4071]
I had issues with this lately and user toos. 
So it would be cool to have it

ref #4069

**Comment by Simn** [comment]
The new templates print it at the bottom: http://api.haxe.org/v/dev/

Might be better to have it in the header though @markknol.

**Comment by markknol** [comment]
Let's do both (header and footer), you can never be clear enough.

**Comment by Simn** [comment]
Fine with me.

**Comment by markknol** [comment]
It would be an extra idea to generate the api docs with the version in the `--title` too.
