### ISSUE TITLE
`null` in awkward places

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4072]
```
class Main {
	static function main() {
		makeNull(null);
	}

	static inline function makeNull(n:String) return n.toLowerCase();
}
```

The inliner causes the AST to be `null.toLowerCase()`. Similar things can happen with macros or in the static analyzer when propagating constants.

We should detect this just before the generators are called and give an error as there is nothing good that could come out of this. Several native compilers choke on constructs like this anyway.

**Comment by Simn** [comment]
#2989 has a conflicting test.

**Comment by Simn** [comment]
There are also some other tests like `Reflect.field(null, null) == null` which fail with a check like this. I still think it's worth doing this because these expressions make zero sense outside of unit tests.

**Comment by Gama11** [comment]
This causes issues in Lime / OpenFL in the cpp section of inlined functions like these:

```haxe
public static inline function bindTexture (target:Int, texture:GLTexture):Void {
    
    #if (js && html5 && !display)
    context.bindTexture (target, texture);
    #elseif ((cpp || neko || nodejs) && lime_opengl)
    lime_gl_bind_texture (target, texture == null ? 0 : texture.id);
    #elseif java
    GL11.glBindTexture (target, texture == null ? 0 : texture.id);
    #end
    
}
```

When this is called with `texture == null`, the `inline` leads to a null expression. It's questionable whether this really needs to be disallowed, since it's worked fine so far and `null.id` can never be reached anyway due to the null check.

**Comment by Simn** [comment]
Let's ignore this due to the problems that might arise from inlining and dead code. We can't rely on the analyzer to remove such dead branches because it might not perform optimizations on the field in question for various reasons.
