### ISSUE TITLE
[cs] abstracts lost in compilation server

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4073]
Consider the following example:

Main.hx

``` haxe
abstract A(Int) {}

class Main {
    function f(a:A) {}
}
```

MyMacro.hx

``` haxe
import haxe.macro.Context;

class MyMacro {
    static function run() {
        var cl = switch(Context.getType("Main")) {
            case TInst(cl,_): cl;
            default: throw false;
        }

        for (f in cl.get().fields.get()) {
            if (f.name == "f") {
                switch (f.expr().expr) {
                    case TFunction(fun):
                        trace(fun.args[0].v.t);
                    default: throw false;
                }
            }
        }
    }
}
```

Run:

```
haxe --wait 6000
```

and then 

```
haxe --connect 6000 --macro MyMacro.run() -cs cs
haxe --connect 6000 --macro MyMacro.run() -cs cs
```

The first output will be: `TAbstract(A,[])` as expected, however the second one yields underlying type: `TAbstract(Int,[])` which is going to break macros.

**Comment by waneck** [comment]
@Simn, is `cl_restore` run after macros?

**Comment by Simn** [comment]
You're asking the wrong person, try @ncannasse.

**Comment by ncannasse** [comment]
cl_restore is run when we load back the module into our context

**Comment by RealyUniqueName** [comment]
Type is replaced here in `type_map`:
https://github.com/HaxeFoundation/haxe/blob/ff4b8d48563fd9fa8216f061b41610ccd054da20/src/generators/gencs.ml#L2846
