### ISSUE TITLE
Var initialization check failure after simplifier

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4076]
https://github.com/away3d/away3d-core-openfl/issues/44#issuecomment-85544940

I'm pretty sure we want to run the var init check before the simplifier, but I would like to know what's happening there regardless.

**Comment by Simn** [comment]
Actually this is quite logical due to the way we transform `&&` into an if-expression. We wouldn't have to do that in this specific case but due to side-effect order we have to in the general case. The var initialization checker is not smart enough to figure out that i being assigned to is a post condition of the loop condition.

So yes, for 3.2 we should just check the initialization before transforming.

**Comment by Type1J** [comment]
@Simn: Thanks!
