### ISSUE TITLE
small issue with __init__ in js

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4077]
I read that @Simn is bored, so:
```
static function __init__() {
	untyped __js__("var __testObj = {};");
}
```
gives you:
`var __testObj = {};;`
```
static function __init__() {
	untyped __js__("var __testObj = {}");
}
```
gives you:
`var __testObj = {}`
You have the choice between two semicolons or none...

**Comment by Simn** [comment]
That's not about `__init__` but about `__js__`. There's some logic in genjs related to ctx.separator which I'm not very familiar with. It is set to true for a real object declaration which then causes `newline` to print a `;` which it normally doesn't do when the last character is `}`. What I don't understand is why `;` itself isn't considered there. 

Seeing how this is not a regression and how easy it would be for a small change like this to cause invalid JS output in other places I prefer to leave this for 3.3.
