### ISSUE TITLE
broken EnumValue check in js.Boot.__instanceof

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4079]
```
enum E {
	e1;
	e2;
}

class Test {
	var a = [1, 2, 3];
	trace(Std.is(a, E.e1));
}
```
=> JS exception
As `EnumValue` is an `Array` in JS, adding "Array" to the exceptions of `js.Boot.__nativeClassName` should fix this.

**Comment by Simn** [comment]
Shouldn't this also fail if you pass an array declaration as the second argument?

Also I wonder if there are targets where this doesn't cause some weird run-time or native compilation error.

**Comment by mockey** [comment]
Yes, array declaration is the same problem. Should be fixed as well now. Makes sense to me to exclude `Array` from the `__nativeClassName` check. This is meant for stuff like `Element` (in some browsers at least). There might be more exceptions needed here.
Maybe add a unit test for this?

**Comment by Simn** [comment]
Adding a unit test would mean specifying this as working-as-intended. I fail to see how anybody could defend this behavior with a straight face.

I consider this a non-issue but I'll leave it open because I know some people disagree.

**Comment by mockey** [comment]
I understand what you mean now. I'm so in php dynamic mode atm, that I don't look at any types anymore :-). Maybe adding some kind of constraint to the second parameter would make sense here. Everything except instances or values?
Nevertheless adding `Array` to the exceptions does make sense here IMO.

**Comment by Simn** [comment]
Let's not do anything here. This kind of nonsense will disappear once #2976 has been addressed.
