### ISSUE TITLE
DOM API is still pretty awkward.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4081]
After getting to compile my code with RC.2, I'm not really sure the API changes were such a good idea. Stuff like parentElement and nextElementSibling always is DOMElement. And `js.Browser.document.createElement("div")` will give me a DOMElement (despite the fact that you need createElementNS to create SVGs reliably). Still, this can be worked around by casts or using createDivElement, when possible.

This is a wild idea, but maybe we could parametrize the "DOM kind"? That would look like this:

```
class DOMElement<Element:DOMElement> {
    var parentElement(default, null):Element;
    var firstElementChild(default, null):Element;
    var nextElementSibling(default, null):Element;
}

class Element extends DOMElement<Element> {}
class SVGElement extends DOMElement<SVGElement> {}

class Document<Element:DOMElement> {
   public function createElement(tagName:String):Element;
}
class HTMLDocument extends Document<Element> {}
```

While the above API is a bit awkward to look at, it's less awkward to use. I find myself downcasting from DOMElement to Element quite a lot.

**Comment by back2dos** [comment]
Anyone? Why is `js.Browser.document` an `HTMLDocument`, while `js.Browser.window.document` is a `Document`? The current state is still rather messy and inconsistent.

My previous comments still apply. If we really want to give people first class JS for SVG support (which *nobody* asked for), then we could have a `-D js-svg` switch to determine what types `js.Browser.*` uses, giving you only the DOM api instead of the HTML one, on demand. 
But the current state is quite a PITA to use. Almost *everything* throws me back from `Element` to `DOMElement`. Event `element.querySelector` returns `DOMElement` and `HTMLCollection` implements `ArrayAccess<DOMElement>`. I have casts now all over the place. Seems to defeat the purpose of a type safe language. I understand the previous API was incorrect. But it was significantly more usable.

**Comment by ncannasse** [comment]
@aduros any feedback on @back2dos suggestions ? I also agree SVG should not be our top priority here

**Comment by ncannasse** [comment]
PS: I would not use add type parameters for DOMElement, maybe we can entirely redefine SVGElement as a separate type, not related to Element in any way ?

**Comment by aduros** [comment]
I agree completely and this was the reason I had Element and HTMLElement merged in the old externs, but people complained about it.

I don't know if we should go back to that, but we could patch the generator to replace all occurrences of IDL fields/methods/etc of type DOMElement with Element...? Same with Document into HTMLDocument.

**Comment by back2dos** [comment]
Ok, my mistake. I wasn't even aware that anyone felt strongly about having it this way. I do use SVG in one of my current projects and we dealt with the differences by "polyfilling" it. Not the cleanest solution, but it gets the job done.

@ncannasse That would also be an option. It might in fact lead to a somewhat clearer API, e.g. HTMLDocument can go back to be called Document (which is only consistent with the general naming convention), and then there would simply be an `js.html.svg.Document`.

**Comment by aduros** [comment]
This weekend I'm planning to try that IDL DOMElement to Element replacement. I really don't want to be reworking the externs at this point, but this should be a small change that could make upgrading to 3.2 more seamless.
