### ISSUE TITLE
PHP file.seek

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4082]
Currently the tests, `testSeekEofLast` and `testSeekEof` in [TestFileInput](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/io/TestFileInput.hx), fail on PHP.

**Comment by Simn** [comment]
Should be fixed. I'm not sure what our specification wants with regards to readBytes though, so I left that alone and only changed it for readByte.

**Comment by andyli** [comment]
Thanks!
Let's close this issue for now. The sys test has not been really completed anyway.
