### ISSUE TITLE
python sys.io.Process#exitCode()

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4083]
i.e. [TestProcess](https://github.com/HaxeFoundation/haxe/blob/development/tests/sys/src/io/TestProcess.hx) fails when targeting python.

minimal test case:
```haxe
class Test {
	static function main():Void {
		var p = new sys.io.Process("echo", ["ok"]);
		trace(p.exitCode()); //None
	}
}
```

**Comment by Simn** [comment]
@frabbit @nadako: It looks like we're not actually waiting for the child process to terminate. The documentation warns about using `wait` though: "Warning This will deadlock when using stdout=PIPE and/or stderr=PIPE and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use communicate() to avoid that."

Should we use `communicate`?

**Comment by frabbit** [comment]
@nadako can you take a look, i don't have time at the moment.

**Comment by nadako** [comment]
@ncannasse when we wait for process to exit? right at `sys.io.Process` construction or when calling `exitCode()`?

**Comment by ncannasse** [comment]
only at exitCode ! the whole point of Process (VS Sys.command) is to be able to run the process in the background, and to perform I/O on it (writing to stdin, reading stdout/stderr, etc.) in an asynchronous manner

**Comment by nadako** [comment]
So we shouldn't use `communicate` and let users deal with deadlocks.

**Comment by nadako** [comment]
@andyli seems to be okay now
