### ISSUE TITLE
flash not working when setting default value in Interface

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [HaxeFoundation/haxe#4087]
I had the problem, that the flash target (openfl) suddenly stopped
working while C++ still worked fine. I then found out that it was caused
by setting an default value in an Interface, like this:

```
interface Inter {
  var value : Bool = false;
}
```

The Problem occurs in haxe 3.1.3 as well as in 3.2.0-rc2.

**Comment by nadako** [comment]
Do default values on interfaces make any sense or this should be forbidden by the compiler?

**Comment by Simn** [comment]
It should just be forbidden.

But I wonder what "stopped working" means.

**Comment by RudolfVonKrugstein** [comment]
"Stopped working" in my case means, that the flash shows a white screen and nothing else happens.

**Comment by Gama11** [comment]
"Nothing happens" isn't quite true, it throws an exception:

`VerifyError: Error #1122: Interface method Inter() has illegal method body.`

I guess you're not using the Flash Debug Player?

**Comment by RudolfVonKrugstein** [comment]
Correct, I am on ubuntu linux and have no flash debugger.

**Comment by Gama11** [comment]
I'm pretty sure the debug player is available for Linux as well (I'm not talking about a debugger as in FlashDevelop's breakpoint debugging). It should be "Download the Flash Player 11.2 Projector content debugger" under the Linux section [on this page](https://www.adobe.com/support/flashplayer/downloads.html).

**Comment by RudolfVonKrugstein** [comment]
well, that one crashes on my 64 bit system as soon as the mouse enters the flash projector window. But I did not investigate yet.

**Comment by Simn** [comment]
Motion to disallow default values on interface vars.

**Comment by ncannasse** [comment]
I agree.

**Comment by Simn** [comment]
We cannot do this unless we find a solution for #6972 because otherwise it's impossible to declare optional, non-nullable interface field arguments.

**Comment by ncannasse** [comment]
How arguments are related to variable defaults in interface ? One is the variable, the other are function arguments.

**Comment by Simn** [comment]
Uhm, right, I'm retarded. For some reason I thought this was about disallowing default values on function arguments. Disregard!
