### ISSUE TITLE
function.bind binds to the static variable and not the value in flash

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4089]
Take this example:

```haxe
class Test {
    static function main() {
        function printTime(time:Float)
            trace("The time is: " + time);
        timestamp = timestampfunc();
        var t = timestampfunc();
        var p1 = printTime.bind(timestamp); 
        var p2 = printTime.bind(t); 
        var p3 = printTime.bind(timestampfunc());
        p1();
        p2();
        p3();

        haxe.Timer.delay(function() {
            t = timestamp = timestampfunc();
            
            p1();
            p2();
            p3();
        }, 1000);
    }
    public static var timestamp : Float;
    static function timestampfunc() return Date.now().getTime();
}
```

In JS all the trace are consistent. In Flash, `p1` reports a delayed value when invoked the second time.

Live example here: http://try.haxe.org/#890D2

**Comment by Simn** [comment]
I'm sure what you meant to post was something like this:

```
class Main {
	static function main() {
		function printTime(time:Float)
			trace("The time is: " + time);
		var p1 = printTime.bind(timestamp);
		p1(); // 1.0
		timestamp = 2.0;
		p1(); // 1.0 on JS, 2.0 on Flash
	}

	static var timestamp = 1.0;
}
```

**Comment by nadako** [comment]
I'm sure @Simn meant to add `haxe` after the opening ``` to enable highlighting and make the example look nice, like this:

```haxe
class Main {
	static function main() {
		function printTime(time:Float)
			trace("The time is: " + time);
		var p1 = printTime.bind(timestamp);
		p1(); // 1.0
		timestamp = 2.0;
		p1(); // 1.0 on JS, 2.0 on Flash
	}

	static var timestamp = 1.0;
}
```

:wink:

**Comment by Simn** [comment]
I... didn't know that was a thing.

Anyway, turns out our inlining sucks even more than we thought. The only reason this doesn't fail the same way on JS is because inlining is cancelled there. You will find that it gives the same wrong result with -D analyzer in place.

I'll spare us further embarrassment and just link to #1827. If you wonder why inlining is involved at all, we do this optimization thing on self calling closures...

**Comment by fponticelli** [comment]
I was so fixated on the original example that I didn't think about reducing it further ... sorry about that :)

**Comment by ncannasse** [comment]
@Simn could you confirm that's not a regression ? It's quite an important issue IMHO

**Comment by Simn** [comment]
I would not have set it to 3.3 if it was a regression.
