### ISSUE TITLE
Issue with command escaping in HXML

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4090]
Hey guys,

I have the following command in the OpenFL docs build.hxml:

```
-cmd haxelib run dox -i . -theme flambe --title "OpenFL Documentation"
```

I am getting an error about "Documentation" being a bad argument. I've tried different combinations of escaping this argument, but since updating my Linux server to the latest dev build release (post RC2) I can't shake this error

I'm pretty sure it's logic for command escaping interacting with this. Somehow "OpenFL Documentation" needs to still be treated as one argument, not two

Thanks!

**Comment by Simn** [comment]
I've always had similar issues with that and just assumed it was a necessary limitation, so I went for single quotes instead. Does that work for you?

**Comment by jgranick** [comment]
I tried single quotes, but that didn't seem to work either. It seems and strip and make it two arguments

**Comment by Simn** [comment]
This seems to have been fixed at some point, as we've been using it with Dox for a while now: https://github.com/HaxeFoundation/dox/blob/master/std.hxml
