### ISSUE TITLE
[cs] extending type parameter for @:generic doesn't work

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4092]
Subj. For example:

``` haxe
@:generic class A<T> extends T {}
```

This generates the following (which then fails to compile by C# compiler):

``` cs
namespace A {
    public class T : global::haxe.lang.HxObject {

        // snip

        public static new object __hx_createEmpty() {
            return default(T) /* This code should never be reached. It was produced by the use of @:generic on a new type parameter instance: global::A.T */;
        }


        public static new object __hx_create(global::Array arr) {
            return default(T) /* This code should never be reached. It was produced by the use of @:generic on a new type parameter instance: global::A.T */;
        }


    }
}

public class A<T> : global::A.T, global::A {
    // snip
}
```

Now when I look at the JS generated code, I think it's not a C#-specific problem, look at this (ping @Simn):

``` js
var A_T = function() { };
var A = function() { };
A.__super__ = A_T;
A.prototype = $extend(A_T.prototype,{
});
```

Unfortunately, adding `@:remove` the the `@:generic` class doesn't help, because the invalid `T` class will still be generated.

**Comment by nadako** [comment]
Seems to be the same on 3.1.3...

**Comment by waneck** [comment]
Yeah this seems to have to do with keeping the basic generic class. I've already had some trouble with `new T()` getting left into the AST.

**Comment by Simn** [comment]
Looks like an issue for me.

**Comment by Simn** [comment]
This should work now.

Leaving this issue open because I didn't add a test yet and it's very strange that a type parameter class ends up in the generator. Investigating that can wait though.

**Comment by nadako** [comment]
not so fast :-P how about
```haxe
@:generic class A<T> extends T {}
/*@:generic */class B<T> extends A<T> {}
```

**Comment by Simn** [comment]
Shoot the author?

**Comment by nadako** [comment]
:wink:

**Comment by Simn** [comment]
The non-generic version should clearly not be allowed but I can't even think of an error message for that.

**Comment by nadako** [comment]
how about "Just no."

**Comment by waneck** [comment]
I don't get why we keep the base generic class "AT ALL" in any case

**Comment by waneck** [comment]
calling the base generic class should always be a compile error

**Comment by nadako** [comment]
the type parameter class is not generated as well now.

**Comment by nadako** [comment]
@waneck i'm not sure too, maybe for statics?

**Comment by Simn** [comment]
We disallowed extending type parameters, so this is no longer a relevant issue.
