### ISSUE TITLE
Bogus empty PCData field after Xml.parse("<!--Comment-->")

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe#4096]
```haxe
using Lambda;
class Test {
    static function main() {
        Xml.parse("<element />").count(); // 1
        Xml.parse("PCData").count(); // 1
        Xml.parse("<!--Comment-->").count(); // 2!!
    }
}
```

See example at: http://try.haxe.org/#4FfaB

The bogus node is generated if Xml.parse finds *only* 1 or more comments.  If there's an element or text node it generates correctly.  

This is not a regression (at least neko had this issue in 3.1.3), but would be nice to fix anyway.

**Comment by Simn** [comment]
P.S.: Let's celebrate the last power of 2 issue we'll be seeing for a while!

**Comment by ncannasse** [comment]
@Simn you're being overly optimistic about 3.2 feedback after release :D

**Comment by jasononeil** [comment]
I have to admit I was pretty chuffed when I submitted it and saw the number.

:dancer: :dancers: :beers: :cake: :clap:
