### ISSUE TITLE
_Impl_ of @:enum abstract with static field becomes extern with dce=no 

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4103]
When compiling with `-dce no`, this code:

```haxe
package;

import haxe.macro.Expr;

class Main
{
	public static function main()
	{
		var value = IntAbstract.value;
	}
}

@:enum abstract IntAbstract(Int) from Int to Int
{
	public static var value = 5;
	
	var var1 = 1;
	var var2 = 2;
}
```

...produces the following error in flash:

```
ReferenceError: Error #1065: Variable _Main::IntAbstract_Impl_ is not defined.
	at Main$/main()[Main.hx:9]
	at boot_54a1/init()[?:1]
	at flash::Boot/start()[C:\HaxeToolkit\haxe\std/flash/Boot.hx:69]
	at boot_54a1()[C:\HaxeToolkit\haxe\std/flash/Boot.hx:38]
```

As the dump shows, that's because with `dce=no` (and only `dce=no`!), `IntAbstract_Impl_` is declared as an `extern`:

```haxe
private extern class _Main.IntAbstract_Impl_{
	static public value(var) : Int

	 = 5

	static public var1((inline,never)) : IntAbstract

	 = cast 1

	static public var2((inline,never)) : IntAbstract

	 = cast 2

}
```

On cpp, it already fails at compile time:

```
Main.cpp
./src/Main.cpp(29) : error C3083: "_Main": Das Symbol links neben "::" muss ein
Typ sein.
./src/Main.cpp(29) : error C3083: "IntAbstract_Impl__obj": Das Symbol links nebe
n "::" muss ein Typ sein.
./src/Main.cpp(29) : error C2039: 'expr': Ist kein Element von '`global namespac
e''
./src/Main.cpp(29) : error C2065: 'expr': nichtdeklarierter Bezeichner

Std.cpp
Reflect.cpp
__boot__.cpp
Error: Build failed
```

I haven't tested any targets other than flash and cpp.

This seems to be a regression (couldn't rerproduce it in 3.1.3). I've tested this against the latest dev build (a285600aa16ef5527452).

**Comment by Simn** [comment]
Try now please!

**Comment by Gama11** [comment]
Can't reproduce it anymore. :)

**Comment by Simn** [comment]
Nice!

Leaving this open to add some tests for this somehow. Related issues #2858 and #1885.

**Comment by Gama11** [comment]
My code snippet should be usable as a test.. or do you mean the other issues?

**Comment by Simn** [comment]
Yeah have to make tests so we can be sure it removes enough, but not too much.

**Comment by Gama11** [comment]
Not sure why I was so fixated on the expression-macro, that actually doesn't seem to be relevant at all, any static field in the abstract will do. Updated / reduced the code snippet accordingly.

**Comment by Simn** [comment]
Yeah well, I knew that already. ;)

**Comment by Gama11** [comment]
I thought as much, just making sure the unit test isn't more complex than it has to be. :)
