### ISSUE TITLE
Possible issue with compiler flag values

### ISSUE THREAD

**Issue by andypellucid** [HaxeFoundation/haxe#4104]
I'm seeing some strange behavior with `-D` compiler flags with values:

If I use `-D myvar=myval`, I'm getting the name of the define, but not the value.

```sh
[awhite@acw][~/temp/haxe-test][2098][0]>>> haxe -v -D myvar=myval build.hxml | head
Classpath : ./;/usr/local/lib/haxe/std/js/_std/;/usr/local/lib/haxe/std/
Defines : true;myvar;js;hxcpp_api_level;haxe_ver;haxe3;dce
Parsed /usr/local/lib/haxe/std/StdTypes.hx
Parsed /usr/local/lib/haxe/std/js/_std/String.hx
Parsed /usr/local/lib/haxe/std/js/_std/Array.hx
Parsed /usr/local/lib/haxe/std/haxe/EnumTools.hx
Parsed /usr/local/lib/haxe/std/js/_std/Std.hx
Parsed /usr/local/lib/haxe/std/js/Boot.hx
Parsed ./Main.hx
Parsed /usr/local/lib/haxe/std/Class.hx
```

**Comment by Simn** [comment]
It simply doesn't print it there. What's the actual issue?

**Comment by andypellucid** [comment]
In the code, I'm trying to check the value in an `#if`, but it does not seem to be working

```sh
haxe -D env=dev build.hxml
```

```haxe
#if (env == "dev")
... dome something
#else
...
#end
```

It doesn't seem to get into the #if block, it falls through to the #else.  I've tried various ways of quoting the command line args, and not quoting the value in the `#if`

**Comment by Simn** [comment]
Please post a complete example with a .hx and .hxml file.

**Comment by andypellucid** [comment]
Ok, I just tried it with a simple example and it's working right... not sure what's going on in my project.  Will post a new issue if I can narrow it down.  Sorry for the hassle.

**Comment by Simn** [comment]
Actually we should make -v print the values too.
