### ISSUE TITLE
string interpolation in exprs returned from macros

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4105]
No worky.
```haxe
class Main {
    static function main() {
        var a = 1;
        f();
    }

    static macro function f() {
        return macro '$a'; // Unknown identifier : a
    }
}
```

**Comment by markknol** [comment]
I'm no expert but shouldn't you use `haxe.macro.MacroStringTools.formatString` for this?

**Comment by Simn** [comment]
I think so, otherwise the string is interpolated while typing the macro itself.

In general I feel like there are way too many implementation details surfacing with regards to string interpolation.

**Comment by Simn** [comment]
Anyway, this looks like it's working as intended.
