### ISSUE TITLE
Compiler.keep not working

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#4111]
ShouldBeKept.hx:
```haxe
class ShouldBeKept
{
    public var foobar :Int = 123;
}
```

Main.hx:
```haxe
class Main
{
    public static function main ()
    {
    }
}
```

Build with `haxe -js out.js -main Main -dce full --macro "keep('ShouldBeKept')"`. In Haxe 3.1.3, `ShouldBeKept` is in the output, but not in latest. Seems like a regression? Looking at the -v output, ShouldBeKept.hx is not even parsed, so it might not be DCE related. Maybe including new modules for compilation with addGlobalMetadata broke at some point?

**Comment by Simn** [comment]
The old keep implementation was pretty crazy and incidentally caused compilation by loading modules. I'm not sure if we want to go back to something like that because it involves browsing the file system and has some problems with module sub-types anyway.

**Comment by aduros** [comment]
Fair enough. Is there a workaround that allows for including classes for compilation without specifying them on the command line?

The documentation for keep() should probably be updated if this change was intentional.

**Comment by Simn** [comment]
A simple Context.getModule(name) should do the trick. And yes we should adjust the documentation.

**Comment by underscorediscovery** [comment]
Does that mean `keep` remains broken? I thought it was an explicit way to ensure types exist? Am I misunderstanding that just implementation detail changes? Or is it now fundamentally not doing what it is for?

**Comment by Simn** [comment]
You can only keep things that you already have. It's intended as a countermeasure to DCE by adding `@:keep` metadata to types. We should keep both concepts (inclusion for compilation and omission from DCE) separate so we can have fine-grained control over it.

**Comment by underscorediscovery** [comment]
so in place of `--macro keep(name)` use `--macro haxe.macro.Context.getModule(name)` to preserve types that aren't referenced (read: documentation generators)

**Comment by Simn** [comment]
Individual types can just be added to the command line, but maybe it would be nice to support them in `--macro include` as well.

**Comment by aduros** [comment]
Hmm, Context.getModule() followed by a Compiler.keep() does not seem to work either.

**Comment by Simn** [comment]
You'll have to do keep first. Its documentation mentions that: "This operation has no effect if the type has already been loaded, e.g. through `Context.getType`."

However, I acknowledge that this is counter-intuitive. Not sure what we can do about it without reverting the keep-changes entirely...

**Comment by aduros** [comment]
That works, thanks Simn.

I think it would be fine if the only thing we do here is adjust the keep documentation to remove the part that says "and includes them for compilation", and mention this change in the release notes.
