### ISSUE TITLE
Error: Unexpected module type of 'java.lang.Double'

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4113]
Getting that when compiling hxparse. Not sure what's going on yet, I'll try to find out.

**Comment by waneck** [comment]
Why is this `@:native("")` needed? Any ideas when does this happen?

**Comment by Simn** [comment]
@waneck: I'm getting this error again and bisected it to my change here: https://github.com/HaxeFoundation/haxe/commit/25cb28edc0e1d790422ab9dc014ff77422ef365b

Seeing how you tried to address this by using `@:native` it makes sense that the errors occurs again now. I don't really know why I made that change, but your solution to this issue is a bit of a hack in the first place.

Am I correctly assuming that this is leading to a discussion about `extern abstract` again?

**Comment by waneck** [comment]
You are indeed correct ;)

2015-12-03 9:09 GMT-02:00 Simon Krajewski <notifications@github.com>:

**Comment by Simn** [comment]
I addressed the `@:native` problem in https://github.com/HaxeFoundation/haxe/commit/8d81af87cb786bd6d8556567805aa8e4f647a186.

I reckon that `extern abstract` would be more elegant, so let's leave this open for a bit.

**Comment by Simn** [comment]
So `extern abstract` is a thing now, but I don't want to touch this because gencommon doesn't actually ignore externs properly anyway.
