### ISSUE TITLE
don't generate @:genericBuild base classes

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4117]
Currently, classes marked with `@:genericBuild` end up in the output, however I wonder if it makes any sense to do so. Maybe it does, if a class has some used static fields, but otherwise, I think it's safe to remove it.

**Comment by nadako** [comment]
Just checked - it is indeed possible to use static fields of a `@:genericBuild` class.

**Comment by Simn** [comment]
Yeah because these classes are only specialized for instances, not upon normal class access. I think that closes the issue.

**Comment by nadako** [comment]
The class should still be removed if there's no instances and no static field usage.

**Comment by Simn** [comment]
Why? That's DCE's job...

**Comment by nadako** [comment]
Hmm, you're right
