### ISSUE TITLE
Memory leak with JdbcConnection

### ISSUE THREAD

**Issue by robmeek** [HaxeFoundation/haxe#4119]
The request method of java.db.JdbcConnection instantiates ResultSets and Statements without closing them. 

Looking at heap dumps I'm 99% sure this is causing a memory leak in my servlet.  Not explicitly closing ResultSets and Statements is apparently a common cause of such leaks, while explicitly closing them is considered good practice.

see:

http://stackoverflow.com/questions/4338445/memory-leak-in-jdbc4connection

and

http://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection

Note that the Resultset needs to be closed first and then the corresponding Statement. 
ResultSet has a getStatement method which could be useful for this.

If sys.db.ResultSet had a close method, explicit cleanup of the resources might be simple to implement. 
Since sys.db.ResultSet doesn't expose a close method, is there a workaround for this? e.g. a way to access the underlying java ResultSet classes and methods?

**Comment by robmeek** [comment]
Here's my spectacularly ugly workaround:

    private function closeResultSet(set:sys.db.ResultSet):Void {
        untyped __java__("
            haxe.java.db.JdbcResultSet wrapper = (haxe.java.db.JdbcResultSet)set;
            try {
                java.sql.ResultSet rs = wrapper.rs;
                java.sql.Statement stmt = rs.getStatement();
                rs.close();
                stmt.close();
            } catch (java.sql.SQLException e) {
                System.out.println(e.getMessage());
            }
        ");
    }

**Comment by Simn** [comment]
This issue went under my radar, sorry for that.

@waneck: This looks like a legitimate concern. Could we just add a close method like suggested?

**Comment by Simn** [comment]
The Java target will be put in "regression fixes only" state with the Haxe 4.3.0 release. See https://github.com/HaxeFoundation/haxe/wiki/Target-Support-Level#java-and-c-since-430 for additional information. We apologize for any inconvenience this causes!
