### ISSUE TITLE
Bool treated as enum by Type API?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4120]
I saw that implementations of `Type.getEnumName` and `Type.resolveEnum` have special cases for `Bool` which looks like a left-over from Haxe 2, but we still have it tested (see https://github.com/HaxeFoundation/haxe/blob/7eeeed0b33ad2e78075d6e4ea7220feaa69e6824/tests/unit/src/unit/TestReflect.hx#L102).

I wonder if we should remove it? (maybe it was probably kept for the sake of (un)serializer, but I'm not sure if it's relevant nowadays)

**Comment by ncannasse** [comment]
I agree it can be removed now.
