### ISSUE TITLE
@:privateAccess bypass setter

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4121]
The following is quite amusing:

```
class Window {
	public var fullScreen(default,set) : Bool;
	function set_fullScreen(b) {
		trace(b);
		return fullScreen = b;
	}
	public function new() {
	}
}

class Sys {
    public static var win : Window = new Window();
}

class Test {
    static function main() {
		var v = true;
		@:privateAccess Sys.win.fullScreen = v;
    }

}
```

I don't think that using `@:privateAccess` here should allow to directly set the variable without going through the setter.

**Comment by Simn** [comment]
This must be some general parsing/typing issue unrelated to the metadata itself.

**Comment by Simn** [comment]
Should that be parsed as `(@:privateAccess Sys.win.fullScreen) = v` or `@:privateAccess (Sys.win.fullScreen = v)`?

**Comment by ncannasse** [comment]
Uhm, even if was parsed as `(@:privateAccess Sys.win.fullScreen) = v`, we shouldn't be allowed to bypass the setter

**Comment by ncannasse** [comment]
But yes I'm expecting `@:privateAccess (Sys.win.fullScreen = v)`

**Comment by ncannasse** [comment]
Since it's EMeta expr

**Comment by Simn** [comment]
Well, with the EMeta there the EField case in `type_access` is not matched which probably leads to an AKExpr instead of AKSet somewhere. The same would happen if we had `(Sys.win.fullscreen) = v`, but this one is disallowed by `check_assign`.

I can fix the parsing but we may want to address the typing issue too as it could be triggered from macros.

To clarify, we want it to be parsed like that only for = and the OpAssignOp variants, right? That is, `@:meta a + b` should still be `(@:meta a) + b`?

**Comment by ncannasse** [comment]
That's not a good idea to treat EMeta this way.

We can either no do any change in the AST (EMeta + expr) OR we should assign a proper operand priority to EMeta and let the ordering to this. For instance = has lower priority than + , so  `a + b = c` is parsed as `(a + b) = c`.

If we give EMeta a higher priority than + then `@:meta a + b` will be `(@:meta a) + b` but then it will also have higher priority than =

**Comment by ncannasse** [comment]
Given how any change wrt EMeta parsing can affect user code, I'm reassigning to 3.2

**Comment by Simn** [comment]
See #1442

**Comment by Simn** [comment]
That change was made over two years ago so I don't think this has to have 3.2 priority.

**Comment by ncannasse** [comment]
Ok, we should get that fixed by giving proper operator precedence to EMeta.

**Comment by Simn** [comment]
Yes, it should be an easy fix but I didn't fully understand the scope yet. Is this specific to OpAssign and OpAssignOp?

**Comment by ncannasse** [comment]
It should treat EMeta just like other operators (EBinop and ETernary are handled atm in make_binop).
But there's some confusion about what should be done:

For instance I would assume that:

```
@meta a = b;  // @meta (a = b)
```

But at the same time, maybe we want:

```
a + @meta b * d; // (a + (@meta b) * c)
```

**Comment by Simn** [comment]
We already have `make_meta`, the problem seems to be that it has a case for EBinop which turns it into `(@:meta a) + b`. That's why I'm asking if we should exclude OpAssign/OpAssignOp from that.

**Comment by ncannasse** [comment]
Yes, that would make sense

**Comment by ncannasse** [comment]
But I'm not sure if that does translate to an actual precedence or if it's some kind of "ugly hack" to get the result we want

**Comment by Simn** [comment]
I'm not sure about that, it has always been like that for unops as well. We could make it more complicated by decoupling `precedence` from binops, but I think we would end up with the same results anyway.

**Comment by ncannasse** [comment]
I remember studying or precedence and documenting it here:
http://old.haxe.org/manual/operators
I think that would mean putting EMeta before or after ?:

**Comment by Simn** [comment]
Yes that seems right.

**Comment by ncannasse** [comment]
BTW I think that documentation should be part of the manual, both the precedence order and the differences with C.

**Comment by Simn** [comment]
Yes, we should make a separate list for that. Originally I wanted to imply the precedence from the [operator overview itself](http://haxe.org/manual/types-numeric-operators.html), but that doesn't express equal precedence.

The original document misses some ops too, at least `!`, `~` and `=>` from what I can tell. Perhaps we should also mention `cast`. For Haxe 4 we also have to consider `is`. And I'm still not entirely sure about the future of ECheckType.

**Comment by AdrianV** [comment]
the fix prevents access to private fields in a typedef now:

```haxe
typedef P2 = {
  @:optional var hidden(default, null): Int;
}

class Private {
    var hidden(default, null): Int = 0;
    public function new() {}
}

class Test {

    static function main() {
        var p = new Private();
        @:privateAccess p.hidden = 1; // works
        var p2: P2 = {};
        @:privateAccess p2.hidden = 1; // fails with:  Cannot access field or identifier hidden for writing
    }
}
```
this works in 3.2.1.

**Comment by Simn** [comment]
I think this only worked accidentally before, I'll check it out.

**Comment by Simn** [comment]
This indeed only worked incidentally because the parsing was weird, which lead to weird typing. I have changed it to properly respect the metadata now. Thanks a lot for catching that!

**Comment by AdrianV** [comment]
just by accident :)
