### ISSUE TITLE
[js] Browser alert/prompt/confirm

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4123]
`js.Lib.alert`, `Browser.alert` and `Browser.window.alert` are the same?

To be consistent, it would be nice to either have add `Browser.prompt` and `Browser.confirm` here too (same type of functions, also exist in `Browser.window`), or remove `Browser.alert` and force to use window.

The real issue was that I was looking for prompt but couldn't find it.

**Comment by aduros** [comment]
I think the alert() shortcut only exists at this point to be friendly to new users who haven't learned about trace().

**Comment by Simn** [comment]
Do we have to take any action here?

**Comment by ncannasse** [comment]
we could deprecate js.Lib.alert in favor of js.Browser.alert

**Comment by markknol** [comment]
Its marked as deprecated, so this can be closed.
