### ISSUE TITLE
Type.allEnums(Type.resolveEnum(...)) is typed as Array<Dynamic>

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4125]
Subj. I wonder if we could do somethng here.
```haxe
class Main {
    static function main() {
        $type(Type.allEnums(Type.resolveEnum("Something"))); // Array<Unknown<0>>
    }
}
```

**Comment by Simn** [comment]
I can't see what else that would return...

**Comment by Simn** [comment]
Closing because I still can't see what else this would return.

**Comment by back2dos** [comment]
Well, it could be `Array<EnumValue>`, although I doubt that would be a tremendous improvement.
