### ISSUE TITLE
[macro] encoding/decoding of FInstance and FClosure type parameters

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4126]
Subj. This is not implemented right now (see https://github.com/HaxeFoundation/haxe/blob/4ea7785243522f10f13d1362014c9bc93fda3d12/interp.ml#L4632)

It requires changing data structure in `haxe.macro.Type` which is a breaking change.

Do we want to break it for 3.2?

**Comment by Simn** [comment]
I'm not sure. I forgot about this and it seems a bit late now, but on the other hand this might actually cause issues. Then again I'm not sure if any backend actually utilizes the type parameters in FInstance/FClosure, in which case it wouldn't really matter.

**Comment by Simn** [comment]
Actually this might cause issues in the typing phase as well, so we should address it.
