### ISSUE TITLE
Haxelib can't submit updated lib versions in latest build.

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#4127]
After building haxe 3.2, I'm seeing this when I'm trying to update promhx:

```
File #4570440 accepted : 178521 bytes written
Processing file....
Invalid response : 'Error : Cannot serialize [file_open,out.txt]
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 515
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 534
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 105
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 81
Called from tools/haxelib/Repo.hx line 41
Called from tools/haxelib/Repo.hx line 317
Called from tools/haxelib/Repo.hx line 323
Called from ? line 1
Called from /usr/lib/haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 340
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 154
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 486'
```

I'm not sure where exactly this is happening... I'm submitting from osx, so I'm not sure about that reference to the C drive.

**Comment by adireddy** [comment]
I am facing the same issue with haxe 3.1.3

File #73093867 accepted : 302383 bytes written
Processing file.... 
Invalid response : 'Error : Cannot serialize [file_open,out.txt]
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 515
Called from C:\HaxeToolkit\haxe\std/haxe/Serializer.hx line 534
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 105
Called from C:\HaxeToolkit\haxe\std/haxe/remoting/HttpConnection.hx line 81
Called from tools/haxelib/Repo.hx line 41
Called from tools/haxelib/Repo.hx line 317
Called from tools/haxelib/Repo.hx line 323
Called from ? line 1
Called from /usr/lib/haxe/std/neko/vm/Module.hx line 52
Called from Tora.hx line 340
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 154
Called from /usr/lib/haxe/std/neko/vm/Loader.hx line 132
Called from Tora.hx line 486'

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxelib/issues/198
