### ISSUE TITLE
$type() not work correctly with compile-time-types

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4133]
Haxe 3.2.0 (RC.3)

$type() not work correctly with compile-time-Types. After processing `$type(T)` have to remove/hide usage of `T`.

```haxe
@:to 
private static inline function toOtherType<T1>(inp:IMyType<T1 -> Void>):OtherType<T1>
{
	$type(T1);
	return new OtherType();
}
```
Compiler returns error:
```log
Error:(113, 8) Type parameter T1 is only available at compilation and is not a runtime value
Warning:(113, 8) Warning : Dynamic
```
There warning (second line) is OK - it's a from `$type(T1)`.
But why I get an error `Error:(113, 8)...`?

**Comment by nadako** [comment]
What does `$type` have to do with this at all? You can't use type parameter as a value, because type parameters are erased from runtime. It would be the same if you just typed `T1`.

**Comment by fzzr-** [comment]
`$type` is buildin compile-time macro. And `$type` returns type (in my case for `T1`) normally!
But why after `$type(T1)` remains in dump `T1`? Is it right?

**Comment by nadako** [comment]
`$type` returns an expression it's given as is and prints its type.

**Comment by nadako** [comment]
https://github.com/HaxeFoundation/haxe/blob/development/typer.ml#L3892 simple as that

**Comment by fzzr-** [comment]
Thanks Dan.
