### ISSUE TITLE
[js] Enum toString function fails when using DCE

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/haxe#4136]
The [following code](http://try.haxe.org/#B6E11) fails on [try.haxe](http://try.haxe.org) (running **Haxe 3.2.0 RC2**) when using DCE (std or full).
```haxe
enum EnumType {
    AnEnum;
}

class Test {
    static function main() {
        trace(AnEnum);
    }
}
```
The error is `Uncaught ReferenceError: js_Boot is not defined`.

The JavaScript output w. DCE is as follows:
```javascript
(function (console) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
var EnumType = { __constructs__ : ["AnEnum"] };
EnumType.AnEnum = ["AnEnum",0];
EnumType.AnEnum.toString = $estr;
EnumType.AnEnum.__enum__ = EnumType;
var Test = function() { };
Test.main = function() {
	console.log(EnumType.AnEnum);
};
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```
The 2nd line, `var $estr = ...` references `js_Boot`, which has been removed by the DCE.

**Comment by Simn** [comment]
This has been fixed by https://github.com/HaxeFoundation/haxe/commit/15e8bb321dffa5671fa374d461164af213bd7044
