### ISSUE TITLE
Sys.exit() broken 

### ISSUE THREAD

**Issue by Jens-G** [HaxeFoundation/haxe#4137]
Test case

```
class Main {
    static function main() {
		Sys.exit(42);
    }
}
```

Produces:

```
./src/Sys.cpp(30) : error C2039: '__hxcpp_exit': not an element of '`global namespace''
./src/Sys.cpp(30) : error C3861: "__hxcpp_exit": identifier not found

Std.cpp
Error: Build failed
Build halted with errors (haxe.exe).
Done(1)
```

I tested this version:
http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows-installer/haxe_2015-04-05_development_cb8852d.tar.gz

**Comment by andyli** [comment]
You need to use the git version of hxcpp when using the development build of haxe.
Remember to clean the output directory after switching hxcpp version.

Probably not needed for this, but sometime you will need to rebuild hxcpp too. Follow the instruction in the [hxcpp README](https://github.com/HaxeFoundation/hxcpp).

**Comment by Jens-G** [comment]
Ok, thanks, I'll try that. Does that rule apply to official RCs as well or to nightlies only?

**Comment by andyli** [comment]
Usually for RC, if a newer hxcpp version is need, Hugh will release it to haxelib. So just grab that haxelib release for RC and use hxcpp git version for haxe nightlies.
