### ISSUE TITLE
The fallback for ArrayBuffer triggers when it shouldn't on a JS Web Worker Thread

### ISSUE THREAD

**Issue by Drakim** [HaxeFoundation/haxe#4138]
Fairly simple bug, it appears that this little rascal is causing trouble when on a web worker thread, probably because window and/or global is different in a web worker.

(std\js\html\compat\ArrayBuffer.hx, line 56)
`var ArrayBuffer = __js__('typeof(window) != "undefined" && window.ArrayBuffer') || __js__('typeof(global) != "undefined" && global.ArrayBuffer') || ArrayBuffer;`

So what happens is that js_html_compat_ArrayBuffer replacement is used instead, when the superior ArrayBuffer is available. Same might be true for other classes if they use the same code.

**Comment by andyli** [comment]
@ncannasse 
This is the same variable hoisting problem we've encountered when implementing `console` polyfill.
I think the best way to get reference from "global", as we currently used for `console` when `-D js-classic`, is as follows:
```haxe
var ArrayBuffer = Function("return typeof ArrayBuffer != 'undefined' ? ArrayBuffer : null");
```

**Comment by ncannasse** [comment]
@andyli any suggestion regarding the Float32Array case ? https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/compat/Float32Array.hx#L106 (in that case we substitute to _new static function)

**Comment by andyli** [comment]
That should be fine regarding to variable hoisting. But it is still better to remove references to `window` and `global` because of issues like #4183.

**Comment by Simn** [comment]
Are you gonna take any action here or should I make the release without it?

**Comment by ncannasse** [comment]
I can try to paste this Function code but then I have no idea if it will work or not

**Comment by Simn** [comment]
Travis is failing.

**Comment by ncannasse** [comment]
I did unit test but forgot to recompile haxe so it was not up to date, have reverted for now but I don't know how to deal with the change in the context of Uint8Array, since using the following does not work:

```
var Uint8Array = untyped __js__("Function(\"return typeof Uint8Array!= 'undefined' ? Uint8Array: null\")") || _new;
```

**Comment by Simn** [comment]
That brings us back to the question if we can make a release without fixing this.

**Comment by Simn** [comment]
@andyli: I see that travis is failing on your attempt but I can't tell why. What's going on there?

**Comment by andyli** [comment]
I haven't look into it yet, but will do so soon.

**Comment by andyli** [comment]
@ncannasse I don't quite follow the logic in `js.html.compat.Float64Array`. There we have:
```haxe
var Float64Array = __js__('typeof(window) != "undefined" && window.Float64Array') || __js__('typeof(window) != "undefined" && window.Float32Array && "notsupported"') || (__js__('typeof(global) != "undefined" && global.Float64Array')) || _new;
```
Because the `"notsupported"` String is truthy, it seems that `global.Float64Array` and the haxe implemented fallback is never used?

**Comment by andyli** [comment]
@ncannasse
Your previous fix attempt failed just because you trusted me too much :P The code I posted in [the comment](https://github.com/HaxeFoundation/haxe/issues/4138#issuecomment-90112855) missed a call to the function.

I've fixed the issue in the sense that, the test case I created passes on all our SauceLabs browsers.
Still I'm not sure about the logic of `js.html.compat.Float64Array` as I've [mentioned](https://github.com/HaxeFoundation/haxe/issues/4138#issuecomment-100979212).

**Comment by ncannasse** [comment]
@andyli some older Android browser (i think) have only support for Float32Array but not Float64Array. So in this case I was initializing Float64Array to "notsupported", so one will get an error when new'ing it, and can trace or Std.string it to detect this case

**Comment by andyli** [comment]
In the case of "there is only Float32Array but not Float64Array", why can't we use our `js.html.compat.Float64Array`?

**Comment by ncannasse** [comment]
Because it will not be compatible with the native ArrayBuffer

**Comment by ncannasse** [comment]
Also, our compat implementation have several limitations and we don't want to have these only apply to Float64Array

**Comment by andyli** [comment]
Ummm, sounds hard to find a perfect solution. 
Nevermind, I will leave it there for now :)

**Comment by ncannasse** [comment]
Yes I came to the same conclusion :)

**Comment by royag** [comment]
The fix for this bug seems to make the javascript incompatible with Content-Security-Policy.
I have filed a new bug for this: #4490
