### ISSUE TITLE
Ampersands ("&") in Xml attributes lead to duplicated trailing character when read

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/haxe#4139]
In short:

Xml that looks like this:
```'<data><thing blah="abc&def"/></data>```

Returns "abc&def**f**" when I read the attribute, inserting an additional "f".

Here's a working minimal example that uses nothing but standard Haxe libraries. This error occurs on both flash & JS targets using try.haxe, and also happens on cpp target on my local machine.

http://try.haxe.org/#1Fc7c

Here's the code right here:
```
class Test {
    static function main() {

        var fancyData = '<?xml version="1.0" encoding="utf-8" ?><data><thing blah="abc&def"/></data>';
        
        doFast(fancyData);
        doXml(fancyData);
        
        var plainData = '<data><thing blah="abc&def"/></data>';
        
        doFast(plainData);
        doXml(plainData);
    }
    
    static function doFast(data:String):Void
    {
        var xml = Xml.parse(data);
        var fast = new haxe.xml.Fast(xml.firstElement());
        var thing = fast.node.thing;
        var blah = thing.att.blah;
        trace("blah = " + blah);
    }
    
    static function doXml(data:String):Void
    {
        var xml = Xml.parse(data);
        var first = xml.firstElement();
        var thing = first.firstChild();
        trace("blah = " + thing.get("blah"));     
    }
}
```

It doesn't seem to be specific to whether or not I use Fast or Xml itself, and it happens regardless of whether I use the ```<?xml version="1.0" encoding="utf-8" ?>``` mega tag. I expect "abc&def", instead I get "abc&def**f**".

**Comment by Simn** [comment]
Note that this is invalid XML because the ampersand has to be escaped. Still, we should fix this.
