### ISSUE TITLE
[CPP/Neko] Thread.current() == Thread.current() return false

### ISSUE THREAD

**Issue by alijaya** [HaxeFoundation/haxe#4141]
Why is it?

**Comment by Simn** [comment]
Looking at the implementation the reason is obvious:

```
	public static function current() {
		return new Thread(thread_current());
	}
```

So for each call a new instance is created wrapping the native value. I find that behavior surprising too so we might want to look into that.

**Comment by ncannasse** [comment]
I've fixed it for neko, maybe something is necessary for CPP as well.

**Comment by hughsando** [comment]
Same fix - perhaps we should always @:keep __compare otherwise seems to be a bug waiting to happen.

**Comment by Simn** [comment]
Ideally we would use `@:ifFeature("neko.vm.Thread.*")` which basically reads "if Thread is kept, keep this field". However, I can't really imagine why Thread would be referenced at all without being used, so a plain `@:keep` might be good enough.

**Comment by hughsando** [comment]
I was thinking more like the magic field "__compare" should be kept if the
class is kept because the usage (operator ==) is highly likely to be
dynamic and not show up in DCE analysis.

**Comment by Simn** [comment]
I don't like naming magic very much. If anything this should be indicated via some metadata.
