### ISSUE TITLE
empty block as last expression in php target

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4149]
Works in 3.1.3 but generates invalid php code with current development version.

```haxe
class Test {
    static function main() {
        var a = "a";
        {};
        // trace("?"); //uncomment this and it will works fine...
    }
}
```
error:
```
Parse error: parse error in /Users/andy/Documents/workspace/TestHaxe/bin/lib/Test.class.php on line 6
```
generated code:
```php
<?php

class Test {
	public function __construct(){}
	static function main() {
		$a = "a"{}
	}
	function __toString() { return 'Test'; }
}
```

**Comment by Simn** [comment]
This is related to https://github.com/HaxeFoundation/haxe/commit/42be1b and https://github.com/HaxeFoundation/haxe/commit/534fd95

@nadako: What was that about?

**Comment by nadako** [comment]
I was getting those redundant blocks because of `mk_block` wrapping empty blocks in block again (so as a result there were things like `{{}}` in the output).

**Comment by nadako** [comment]
Should work now, though we could filter out empty blocks, but that's not target-specific filter.
