### ISSUE TITLE
IO.Overflow("write_ui16")

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4150]
I originally opened this issue in OpenFL (https://github.com/openfl/openfl/issues/567), but due to the lack of meaningful debug information, I think the OpenFL team may not be able to solve it. So I link it here as well.

**Comment by Simn** [comment]
Try setting the environment variable OCAMLRUNPARAM=b and see if you get a stacktrace when compiling.

**Comment by kevinresol** [comment]
```
Fatal error: exception IO.Overflow("write_ui16")
Raised at file "IO.ml", line 510, characters 35-58
Called from file "swfParser.ml", line 2026, characters 2-18
Called from file "list.ml", line 73, characters 12-15
Called from file "swfParser.ml", line 2074, characters 1-30
Called from file "genswf.ml", line 1184, characters 2-18
Called from file "main.ml", line 1548, characters 3-35
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1743, characters 1-35
Build halted with errors.
```

**Comment by Simn** [comment]
This suggests that there's a problem with a TBinaryData. The compiler tries to read its ID but the value it comes across exceeds the unsigned 16 bit range.

Unfortunately that's as far as my SWF knowledge takes me.

**Comment by ncannasse** [comment]
When we link a SWF with one or more SWC, we offset the ids based on the max id in the source SWC (genswf.ml / merge()). It is possible that this particular SWC already have ids in the 0xFFXX range so when linking we overflow. Supporting this would require find a way to allocate/remap ids in a more efficient manner.

**Comment by Simn** [comment]
I'm closing this as unresolved. Sorry about that, but I don't think we'll have the resources to investigate solutions for rare, flash-specific issues.
