### ISSUE TITLE
[cs] unable to link System.Data.dll

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4151]
build.hxml:

```
-cp src 
-cs bin 
-net-lib "C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll"
-main Main
```

results:

```
File "ilMetaReader.ml", line 577, characters 34-40: Assertion failed
error 0x2
Press enter to exit...
```

**Comment by nadako** [comment]
Can confirm it doesn't work for me as well:

```
error 0x2
Fatal error: exception Assert_failure("ilMetaReader.ml", 577, 34)
Raised at file "ilMetaReader.ml", line 577, characters 34-46
Called from file "ilMetaReader.ml", line 1477, characters 21-44
Called from file "ilMetaReader.ml", line 1961, characters 19-66
Called from file "array.ml", line 85, characters 31-51
Called from file "ilMetaReader.ml", line 2284, characters 1-347
Called from file "ilMetaReader.ml", line 2410, characters 1-14
Called from file "gencs.ml", line 4422, characters 14-64
Called from file "gencs.ml", line 4446, characters 13-22
Called from file "gencs.ml", line 4566, characters 46-62
Called from file "list.ml", line 73, characters 12-15
Called from file "main.ml", line 1450, characters 3-28
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1743, characters 1-35
```

**Comment by nadako** [comment]
Looking at the code, IL reader encounters unknown method calling convention (0x2), which seems to be an "unmanaged" call (https://msdn.microsoft.com/en-us/library/ms231596(v=vs.110).aspx)

**Comment by kevinresol** [comment]
another error found
```
-net-lib C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll
```

result:
```
PeReader.Error_message("Error reading compressed data. Invalid first byte: e5")
Build halted with errors (haxe.exe).
```

**Comment by kevinresol** [comment]
Having no knowledge to OCaml, but I just looked into the code and seems that https://github.com/HaxeFoundation/ocamllibs/blob/master/ilib/ilMetaReader.ml#L277 does handle the 0x2 to 0x4 cases. So will it work by simply adding back the cases around line 570?

**Comment by Simn** [comment]
Having no knowledge of this IL I would concur. In fact this part looks like it wants to be factored out to a function which both places can call.

**Comment by ousado** [comment]
Does this have to be a fatal error or could this be handled on a per-function/class basis?

**Comment by waneck** [comment]
Right now, all errors in net-lib are fatal errors. I could add some resilience to dll reading, but this may mean that a wrong read could add a lot of garbage to the dll without us being able to know what exactly happened. Right now I prefer to read a lot of dlls from net-lib and make sure it reads them well, and still keep this behaviour.

**Comment by waneck** [comment]
I'll make a pass on -net-lib reading for 3.3

**Comment by frabbit** [comment]
@waneck is this relevant for 3.4 or should we postpone this issue?

**Comment by lublak** [comment]
Also BouncyCastle.Crypto.dll throws an error.

[bccrypto-csharp-1.8.5-bin.zip](https://github.com/HaxeFoundation/haxe/files/2932867/bccrypto-csharp-1.8.5-bin.zip)

> Error reading compressed data. Invalid first byte: e5

**Comment by lublak** [comment]
I run also in this issue:

```
error 0x3
Fatal error: exception File "ilMetaReader.ml", line 577, characters 34-40: Assertion failed
Raised at file "ilMetaReader.ml", line 577, characters 34-46
Called from file "ilMetaReader.ml", line 1477, characters 21-44
Called from file "ilMetaReader.ml", line 1961, characters 19-66
Called from file "ilMetaReader.ml" (inlined), line 2288, characters 12-46
Called from file "ilMetaReader.ml", line 2293, characters 16-41
Called from file "array.ml", line 124, characters 31-51
Called from file "ilMetaReader.ml", line 2284, characters 1-347
Called from file "ilMetaReader.ml", line 2410, characters 1-14
Called from file "_build/src/codegen/dotnet.ml", line 1133, characters 14-64
Called from file "_build/src/codegen/dotnet.ml", line 1157, characters 13-22
Called from file "_build/src/codegen/dotnet.ml", line 1280, characters 46-62
Called from file "list.ml", line 106, characters 12-15
Called from file "_build/src/compiler/main.ml", line 252, characters 4-30
Called from file "_build/src/compiler/main.ml", line 834, characters 11-55
Called from file "_build/src/compiler/main.ml", line 383, characters 3-11
Called from file "_build/src/compiler/main.ml", line 1130, characters 1-35
```

used the dll: https://github.com/lordmulder/DynamicAudioNormalizer

**Comment by RealyUniqueName** [comment]
@lublak please, provide a direct link to dll, so that when we get to solving this issue, we know exact commit in that repo. Otherwise dll might change in future and we won't be able to reproduce.

**Comment by lublak** [comment]
@RealyUniqueName okay here We Go: https://github.com/lordmulder/DynamicAudioNormalizer/releases/download/2.10/DynamicAudioNormalizer.2017-04-14.Windows-DLL.zip
I did not think about it. Sry.
