### ISSUE TITLE
NET C++/CLI dll in Haxe/C# target

### ISSUE THREAD

**Issue by egx7** [HaxeFoundation/haxe#4154]
Hello

I've been trying to use Haxe to generate C# code that calls a method from a dll written in C++/CLI. This dll is called "TestCLR.dll", the method is testHaxe and it only prints a message to the console.

Here is an example of the Haxe code I'm trying:

    package hello;

    class HelloWorld {

        static public function main():Void {
            untyped __cs__("TestCLR.Test.testHaxe()");
        }
    }

As you can see I'm using "Haxe magic" syntax (I previously tried direct calls and Haxe extern classes that resulted pretty much in the same problems) to call the method within the TestCLR.dll. The method signature inside the dll is:

    public static void testHaxe()

However, when I try to compile this code, Haxe throws this error:

    $ haxe -cp src -cs out/CS -main hello.HelloWorld
    haxelib run hxcs hxcs_build.txt --haxe-version 3200 --feature-level 1
    src\hello\HelloWorld.cs(24,15): error CS0103: The name 'TestCLR' does not exist in the current     context
    Compilation error
    Native compilation failed
    Error: Build failed

If I try to pass the TestCLR.dll reference as -net-lib or -net-std I get these errors:

    $ haxe -cp src -cs out/CS -net-lib lib/CPP/x86/TestCLR.dll -main hello.HelloWorld
    File "ilMetaReader.ml", line 577, characters 34-40: Assertion failed
    error 0x2

    $ haxe -cp src -cs out/CS -net-std lib/CPP/x86/TestCLR.dll -main hello.HelloWorld
    Error: No .NET std lib directory with the pattern 'net-20' was found in the -net-std search path. Try   updating the hxcs lib to the latest version, or specifying another -net-std path.

Please note that this dll can be used without problems from C# projects in Visual Studio.

Thank you very much in advance.

P.S. The dll and its sourcecode can be downloaded from here:

https://drive.google.com/file/d/0B6vvavDv1dUCdFp3ZHpUdEk1aU0/view?usp=sharing
https://drive.google.com/file/d/0B6vvavDv1dUCVzhMWHEwVmR0Vm8/view?usp=sharing

**Comment by nadako** [comment]
This looks the same as #4151
