### ISSUE TITLE
Code completion within a TAnonymous ComplexType

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4155]
Not sure if it is possible to enable code completion in the example as follows?

src/Test.hx

`````` haxe
class Test {
    /**
        This is just a macro that extract `<expr>` within 
        ```
        (null:{
            function dummy():Void {
                <expr>
            }
        })
        ```
    */
    macro static function m(e) {
        return switch (e) {
            case macro (null:{
                function dummy():Void {
                    $expr;
                }
            }):
                expr;
            case _: throw "invalid input";
        }
    }

    static function main() {
        var v = m((null:{
            function dummy():Void {
                "test".|
            }
        }));
        trace(v);   
    }
}
``````

``` shell
$ haxe --interp -main Test -cp src --display src/Test.hx@0
src/Test.hx:29: characters 2-3 : Unexpected }
```

It is part of what I'm doing in hxAnonCls.
Both haxe 3.1.3 and latest development branch give the same result.

**Comment by Simn** [comment]
The problem here is not the macro but the additional parentheses:

```
class Main {
	static function main() {
		(null:{
			function dummy() {
				"test".|
			}
		});
	}
}
```

You will find that completion works fine if the parens around the expression are removed. This has to do with how the parser skips tokens for completion, but I'm not entirely sure what's going wrong yet.

**Comment by Simn** [comment]
I completely misunderstood the example here and only now realized that this is about completion inside a type-hint. That's a very unusual case and I can't promise that we'll address it, but I would still like to understand why it doesn't work.

**Comment by Simn** [comment]
This was addressed by my recent parser robustness improvements.
