### ISSUE TITLE
add "rethrow" functionality

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4159]
Extracting my comment from #3405 to bring some attention to it:

It's annoying to lose stack trace if you just want to catch exception, cleanup things and rethrow it, so I think we should support it.

I did a bit of research on cross-platform support and it seems to be supported in one way or another on all current targets:
- **JavaScript**: throw catched exception (before unwrapping)
- **Neko**: throw catched exception with `$rethrow`
- **Java**: throw catched exception (before unwrapping)
- **C#**: `throw` without argument
- **Python**: `raise` without argument

Not sure:
- **Flash**: throw catched exception (similar to JavaScript) - ?
- **C++** - throw catched exception without calling `__hx_stack_set_last_exception`  - ?
- **PHP** - throw catched exception (before unwrapping) - ?

As for the implementation, how about we make `TThrow of texpr option` (similar to `TReturn`) and support plain `throw` inside `catch` blocks. That shouldn't break any compatibility and having `TThrow` is good for analysis.

**Comment by waneck** [comment]
:+1:

**Comment by ncannasse** [comment]
For Flash, there is no way that i know. throwing the catched exception will reset the stack.

We can handle this either language-wise with throw; or explicitely through Std.rethrow by being clear in the documentation that on some platforms only throwing the caught exceptions will behave as expected.

From my own experience, these cases exists but are pretty rare so I'm more in favor of having Std.rethrow instead of adding a new specific syntax, because it's easier for users to look at what Std.rethrow does in the API than figuring out why there is no expression after the throw.

**Comment by fzzr-** [comment]
* Neko `neko.Lib.rethrow()`

Also maybe need to unify `Lib` to `haxe.Lib` or `sys.Lib`?..

**Comment by nadako** [comment]
The problem with function call is that it's awkward to analyze control flow, that's why I think it should be a proper AST node. It's too bad Flash doesn't support exception rethrow though :(

**Comment by Simn** [comment]
The control flow is going to require special handling, so I don't really see why it shouldn't be reflected in the AST in the first place. I don't really care about the user-facing syntax though.

**Comment by ncannasse** [comment]
Why does it requires control flow analysis ? I mean you can call a function, and this function can throw as well, nothing new here. And with inline you don't get the extra call (might cause stack issues)

**Comment by Simn** [comment]
I'm pretty sure this would give you a "A return is missing here" error:

```haxe
function func():String {
    try {
        return something();
    } catch(e:Dynamic) {
        log(e);
        Lib.rethrow();
    }
}
```

**Comment by Simn** [comment]
For the static analyzer it's also relevant, although not terribly important:

```haxe
class Main {
    static function main() {
        var a = 2;
        try {
            a = 3;
            throw "exit";
            a = 4;
        } catch(e:Dynamic) { }
        trace(a);
    }
}
```

The value of `a` is const-propagated to 3, which is only possible with the `throw "exit"` as that allows to determine that `a = 4` is unreachable code.

**Comment by nadako** [comment]
I added the `js.Lib.rethrow` method for now.

**Comment by yar3333** [comment]
How about PHP? For now, we haxe php.Lib.rethrow, but stack not saved:
```haxe
class Test
{
	static public function main() {
		try outer()
		catch (e:Dynamic)
		{
			Sys.println(haxe.CallStack.toString(haxe.CallStack.exceptionStack()));
		}
	}
	
	static function outer() {
		try inner()
		catch (e:Dynamic) php.Lib.rethrow(e);
	}
	
	static function inner() throw "error";
}
```

Produce output w/o "inner":
```
Called from php.Lib.rethrow
Called from Test.outer
Called from Test.main
```

**Comment by sebthom** [comment]
I wrote the following class which I am using until we have proper cross target rethrow support. Maybe it is of use for anyone.

```haxe
import haxe.CallStack;

class Exception {
    
    static inline var INDENT:String = #if java "\t" #else "  " #end;

    inline
    public static function capture(ex:Dynamic) {
        return new Exception(ex);
    }
    
    public var cause(default, null):Dynamic;
    public var causeStackTrace(default, null):Array<StackItem>; 

    function new(cause:Dynamic) {
        this.cause = cause;
        this.causeStackTrace = CallStack.exceptionStack();
    }
    
    #if (!python) inline #end
    public function rethrow() {
        #if neko
            neko.Lib.rethrow(cause);  // Neko has proper support
        #elseif python
            //python.Syntax.pythonCode("raise"); // rethrows the last but not necessarily the captured exception
            python.Syntax.pythonCode('raise Exception(self.toString()) from None');
        #else
            // cpp.Lib.rethrow(cause);  // swallows stacktrace
            // cs.Lib.rethrow(this);    // throw/rethrow swallow complete stacktrace
            // js.Lib.rethrow();        // rethrows the last but not necessarily the captured exception
            // php.Lib.rethrow(cause);  // swallows stacktrace
            throw this.toString();
        #end
    }

    public function toString():String {
        var sb = new StringBuf();
        sb.add("rethrown exception:\n");
        sb.add(INDENT); sb.add("--------------------\n");
        sb.add(INDENT); sb.add("| Exception : "); sb.add(cause); sb.add("\n");
        for (item in CallStack.toString(causeStackTrace).split("\n")) {
            if (item == "") continue;
            sb.add(INDENT);
            sb.add(StringTools.replace(item, "Called from", "| at"));
            sb.add("\n");
        }
        sb.add(INDENT); sb.add("--------------------");
        return sb.toString();
    }
}
```
Use it like this:
```haxe
class Test {
  	public static function main() {
            try {
                // code that may fail
            } catch (e:Dynamic) {
                var ex = Exception.capture(e); // first capture the exception stackitems

                // do cleanup here

                // rethrow the captured exception
                ex.rethrow();
            }
    }
}
```
Java output:
```
Exception in thread "main" Haxe Exception: rethrown exception:
        --------------------
        | Exception : hi
        | at test.TestRunner.foo2 (TestRunner.java line 85)
        | at test.TestRunner.foo (TestRunner.java line 78)
        | at testTestRunner.main (TestRunner.java line 44)
        --------------------
        at haxe.lang.HaxeException.wrap(HaxeException.java:56)
        at test.TestRunner.main(TestRunner.java:66)
        at test.TestRunner.main(TestRunner.java:12)
```

PHP output:
```
uncaught exception: rethrown exception:
  --------------------
  | Exception : hi
  | at test.TestRunner.foo2
  | at test.TestRunner.foo
  | at test.TestRunner.main
  --------------------

Called from test.TestRunner::main
```

C++ output:
```
Called from hxcpp::__hxcpp_main
Called from test.TestRunner::main test/TestRunner.hx line 43
Error : rethrown exception:
  --------------------
  | Exception : hi
  | at test.TestRunner.foo2 (test/TestRunner.hx line 60)
  | at test.TestRunner.foo (test/TestRunner.hx line 55)
  --------------------
```

**Comment by Simn** [comment]
This would have to be revived as a haxe-evolution proposal.
