### ISSUE TITLE
[macro] Defined type aren't sees the private superclass.

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4160]
I trying to create `Foo extends Bar` where Bar is a private class. Foo and Bar is __in the one module__ `test.Main` and have to see each other in it.

```haxe
package test;

import haxe.macro.Context;
import haxe.macro.Expr;


private class Bar {}

class Main
{
	static function main()
	{
		defineFooExtendsBarInLocalModule();
	}

	macro static function defineFooExtendsBarInLocalModule(?e)
	{
		var infos = Context.getPosInfos(Context.currentPos());
		var position = Context.makePosition({min:0, max:0, file:infos.file});

		var superTypePath:TypePath =
		{
			pack: ["test"],
			name: "Main",
			sub: "Bar"
		}

		var kind:TypeDefKind = TypeDefKind.TDClass(superTypePath);

		var Foo:TypeDefinition =
		{
			name: "Foo",
			pack: ["test"],
			pos: position,
			kind: kind,
			fields: []
		}

		//Context.defineType(Foo); // Bar not defined in Main
		Context.defineModule(Context.getLocalModule(), [Foo]); // Bar not defined in Main

		return e;
	}
}
```
Exception: 
`./test/Main.hx:1: character 0 : Module test.Main does not define type Bar`

**Comment by fzzr-** [comment]
It happens because `private` class moving into package named like him module. In my case it `test._Main.Bar`.

**Comment by Simn** [comment]
Yes, but I think a plain "Bar" type path should work. Not sure why it doesn't at the moment.

**Comment by fzzr-** [comment]
If as "plain Bar" you mean `...:TypePath = { pack: [], name: "Bar" }` - that's not work, yes.

**Comment by Simn** [comment]
This is going to require some effort. At the moment we don't support "type a type into an existing module" very well because we do not have the typing context available for that.

**Comment by Simn** [comment]
My fix is incomplete because it doesn't respect using/import declarations. Doing that would require keeping the module context (`typer_module`) in the typing context.

**Comment by fzzr-** [comment]
Maybe create new method in `Context` named `redifineModule(path, types:Array<TypeDefinition>)` or add opt-argument to existing method `defineType(?module, t:TypeDefinition)`?

Or make `TypeDefinition` more consistently with `TypePath`. Currently `TypePath` has an optional field `sub:Null<String>`.
```haxe
typedef TypePath = {
	var pack : Array<String>;
	var name : String;
	@:optional var params : Array<TypeParam>;
	@:optional var sub : Null<String>;
}
```

I think if the same field will be added to the `TypeDefinition` then it will be easier to find the context for the module:
```haxe
typedef TypeDefinition = {
	var pack : Array<String>;
	var name : String;
	@:optional var params : Array<TypeParamDecl>;
	@:optional var sub : Null<String>; // <---- additional field //

	var pos : Position;
	@:optional var meta : Metadata;
	@:optional var isExtern : Bool;
	var kind : TypeDefKind;
	var fields : Array<Field>;
}
```
