### ISSUE TITLE
Static extension + Macro not working as expected

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4161]
Main.hx:

```haxe
using WorksheetUtilMacro;

public function main()
{
   var ws = new Worksheet(); 
   var range1 = WorksheetUtilMacro.cells(ws,1,2); // call as normal static function
   var range2 = ws.cells(1,2); // call as static extension
}
```

WorksheetUtilMacro.hx
``` haxe
macro public static inline function cells(wsExpr, rowExpr, colExpr)
{
	return Context.parseInlineString('untyped __cs__("${wsExpr.toString()}.Cells[${rowExpr.toString()}, ${colExpr.toString()}]")', Context.currentPos());
}
```

Output Main.cs:
```cs
object range1 = ws.Cells[1, 2];
object range2 = @:this this.Cells[1, 2];
```

Is it expected to have the two outputs different?

**Comment by nadako** [comment]
That's not how you return passed expression from a macro. For the `__cs__` case you could try (not tested):
```haxe
untyped __cs__("{0}.Cells[{1}, {2}]", $wsExpr, $rowExpr, $colExpr)
```

**Comment by Simn** [comment]
Yes, that couldn't possibly work like that. See the documentation here: http://haxe.org/manual/macro-limitations-static-extension.html#since-haxe-3.1.0

**Comment by nadako** [comment]
This should work
```haxe
class WorksheetUtilMacro {
    macro public static inline function cells(wsExpr, rowExpr, colExpr) {
        return macro untyped __cs__("{0}.Cells[{1}, {2}]", $wsExpr, $rowExpr, $colExpr);
    }
}
```

**Comment by nadako** [comment]
(btw, no use for `inline` in a `macro` function, should we disallow that?)

**Comment by nadako** [comment]
Actually, you don't even need a macro here:
```haxe
    public static inline function cells(ws:Worksheet, row:Int, col:Int) {
        return untyped __cs__("{0}.Cells[{1}, {2}]", ws, row, col);
    }

```

**Comment by Simn** [comment]
Not sure about disallowing it, it's not like it does any harm. I don't really have any opinion on it though.

**Comment by nadako** [comment]
I would disallow everything that doesn't make sense, for the sake of code clearness, but I acknowledge it's a breaking change so I won't advocate for it.

**Comment by kevinresol** [comment]
@nadako, thanks very much for the solution. I didn't know about that syntax for __cs__, are there any docs around?

**Comment by Simn** [comment]
That's a good point, that thing should be mentioned in https://github.com/HaxeFoundation/HaxeManual/wiki/Haxe-C%23 @nadako

**Comment by nadako** [comment]
Agreed, I'll add it to that doc.

**Comment by nadako** [comment]
Added some info.

**Comment by kevinresol** [comment]
That wiki pages seems so isolated and hidden (I didn't expect there are actual docs inside the wiki of a "doc repo"). How about linking/moving the contents [here](http://haxe.org/manual/target-details.html)?

**Comment by nadako** [comment]
It's intended to be there, but since I hate TeX, I'm writing it in the wiki and then someone is going to move it into HaxeManual.

**Comment by kevinresol** [comment]
I understand lol, but I think at least linking to the actual haxe manual would let more ppl know about it.
