### ISSUE TITLE
different path in error msg when HAXE_STD_PATH is set

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4163]
When `HAXE_STD_PATH` is set, the file path in error messages are prepended with `./`.

Test.hx
```
asdf //just to produce an error
```
when `HAXE_STD_PATH` is not set:
```
$ haxe -main Test --interp
Test.hx:3: characters 2-8 : Missing ;
Test.hx:3: characters 2-8 : Unknown identifier : adsasf
```
when `HAXE_STD_PATH` is set:
```
$ haxe -main Test --interp
./Test.hx:3: characters 2-8 : Missing ;
./Test.hx:3: characters 2-8 : Unknown identifier : adsasf
```

I tested in Mac and Linux.
This prevents the haxe repo to switch to the TravisCI container based environment, where sudo is not allowed, thus we have to mess with `PATH` and `HAXE_STD_PATH` instead of `sudo make install`.
And our misc tests failed because of this issue ([build log](https://travis-ci.org/andyli/haxe/jobs/59189614)).

**Comment by Simn** [comment]
Can reproduce on Windows. The relevant code looks a bit strange:

```
		let parts = "" :: Str.split_delim (Str.regexp "[;:]") p in
		com.class_path <- List.map normalize_path (loop parts)
```

https://github.com/HaxeFoundation/haxe/blob/development/main.ml#L1020

@ncannasse: What's the `""` doing there? The problem seems to be that it goes through `normalize_path` which turns it into `./`.

**Comment by Simn** [comment]
Looks like the `"" ::` should just move one line down. Reading the loop implementation it is passed through anyway, so the only difference to the other branches is that the `""` goes through `normalize_path`. I'll go ahead and change it.

**Comment by Simn** [comment]
@andyli: Please confirm it works now.

**Comment by andyli** [comment]
It works now, thanks!
Your issue fixing speed is impressive as always :)
