### ISSUE TITLE
Not able to properly Reflect on InputElement

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4164]
```
class Test {
    static function main() {
        var el:js.html.InputElement = js.Browser.document.createInputElement();
        trace(Reflect.hasField(el, 'value'));
    }
}
```

Results in `false`

But in a browser console I can reference ```inputElement.value```.

In this case, 
```
Reflect.hasField(el, 'value')
```
compiles to 
```
Object.prototype.hasOwnProperty.call(el, 'value')
``` 
where as 
```
'value' in el
``` 
would work better in this case.

For easy reference:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in

**Comment by explorigin** [comment]
More specifically, this works in Chrome but not in Firefox.  Yet I would venture that Firefox has the more correct implementation.

**Comment by Simn** [comment]
"This is only guaranteed to work for anonymous structures. Refer to Type.getInstanceFields for a function supporting class instances."

**Comment by explorigin** [comment]
Round Two:

```
class Test {
    static function main() {
        var el = js.Browser.document.createInputElement();
        trace(Type.getInstanceFields(cast el));
    }
}
```
Results in 
```
[]
```
So I can't test for ```'value' in el``` that way either.

Does that mean Type.getInstanceFields() is broken for InputElement?

**Comment by mcheshkov** [comment]
You should use
`Type.getInstanceFields(Type.getClass(el))`
Just as docs say

**Comment by mcheshkov** [comment]
And that leads us to `Type.getClass(el) == null`, wow

**Comment by Simn** [comment]
I don't think our reflection functions in general are guaranteed to work on native classes like that.
