### ISSUE TITLE
[macro] created @:to-method for abstracts not work as Implicit-Cast-method

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4166]
Method with meta `@:to` added into abstract via build-macro not working as it should, i.e. meta `@:to` ignored.
See example-test: https://gist.github.com/fzzr-/941fbc4d55b5d9d89212

For reproduce in this example comment [line 12 in build.hxml](https://gist.github.com/fzzr-/941fbc4d55b5d9d89212#file-build-hxml-L12)

I think it because compiler's exception throws before macro-build-method called.

**Comment by fzzr-** [comment]
Thx @nadako. Related issue: https://github.com/HaxeFoundation/haxe/issues/3514

**Comment by Simn** [comment]
Can this be closed?

**Comment by nadako** [comment]
I don't know, but it seems related to the `@:impl` stuff that is not required for building abstracts anymore.
