### ISSUE TITLE
run @:genericBuild macro on type parameter application

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4167]
We've discussed it briefly on #haxe-dev, but it seems that it's not trivial and @Simn is not sure how to approach that, but I'll create an issue for discussion.

It would be useful to "delay" @:genericBuild macro call until after type parameter application. For example, consider some `@:genericBuild(ConstMacro.build()) class Const<T> {}` type where `ConstMacro` generates a read-only type wrapper for given `T` type.

Now consider a parametrized class like `class A<T> { var f:Const<T>; }`. With the current implementation, `ConstMacro` will receive the `A.T` type which is kind of useless for generating read-only type.

It would be useful if a @:genericBuild macro could be run on type parameter application, for example when we reference `A<MyType>`, a @:genericBuild macro is called for `Const<MyType>` field type.

Does that make any sense? :-)

**Comment by Simn** [comment]
Your class example doesn't make any sense unless the class itself is generic.

**Comment by Simn** [comment]
I'm working through some old issues related to `@:genericBuild` and such, but this one still doesn't make much sense to me. If there's still need for something like this, we would need an actual example.
