### ISSUE TITLE
[cs] Math.fround midpoint rounding is inconsistent with other targets

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4177]
Subj. Because it uses `Math.Round` which rounds to even by default (banker's rounding). I guess we need to use the same code as in `Math.round`.

**Comment by nadako** [comment]
@waneck could you please review linked commits?

**Comment by waneck** [comment]
Seems fine. But I wonder why our definition of `Math.round` conflicts with C#/Java's . Specially Java seems strange - I thought JS' `Math` definition was based on Java's

**Comment by nadako** [comment]
I don't know, I find "round midpoint to even" strategy quite weird (though it probably has some practical value). I'd like round to work similar to C#'s `AwayFromZero` strategy, but it's not like we can change that, as Haxe seems to follow ECMA in these things, so we're stuck with asymmetric rounding.
