### ISSUE TITLE
Base64.encode does not return the expected value

### ISSUE THREAD

**Issue by LordCorax** [HaxeFoundation/haxe#4181]
It seems that there is a bug in haxe.crypto.Base64.
I used Base64's decode method to convert a simple string into a byte-object.
After that I called the encode method to get my original string value back.

But that didn't work out properly. Instead of a friendly "Hello" I got a "Hell" in my output panel.

Btw the code:
```
public function new() 
{
    super();
    var bytes:haxe.io.Bytes = haxe.crypto.Base64.decode("Hello");
    Lib.trace(bytes.toString());
    Lib.trace(haxe.crypto.Base64.encode(bytes));
}
```
Result:
```
Lib.hx:145: �ée
Lib.hx:145: Hell
```

**Comment by mcheshkov** [comment]
Base64.decode expect base64-encoded string as input, which length should be multiple of 4.

Also I don't get what you want to achieve.

**Comment by LordCorax** [comment]
I'm just looking for an option to encrypt and decrypt my data. If there is a more suitable approach, I would be thankful to hear it.

**Comment by mcheshkov** [comment]
base64 is not an encryption, it's just encoding. Encryption mean that there's authority check, and base64 have none.
About encrypting and haxe - I don't know, sorry.
