### ISSUE TITLE
javascript code fails in SpiderMonkey

### ISSUE THREAD

**Issue by ktimothy** [HaxeFoundation/haxe#4183]
When running javascript on SpiderMonkey VM, it fails on accessing ```global``` variable.

```javascript
js.Boot.__resolveNativeClass = function(name) {
	if(typeof window != "undefined") return window[name]; else return global[name];
};
```

**Comment by ktimothy** [comment]
I don't think anyone will ever run SpiderMonkey to fix that, so I can suggest a solution.
```
if(typeof(global) === 'undefined') var global = this;
```
solves the issue.

**Comment by mcheshkov** [comment]
That `typeof(global)` refer to variable you introduce later, not to one you miss.

**Comment by ktimothy** [comment]
That still works in javascript.

**Comment by mcheshkov** [comment]
That works, but the condition will always be true, even if there is `global`

**Comment by ktimothy** [comment]
If there is a ```global```, the code
```javascript
typeof(global) === 'undefined'
```
returns false, at least at nodejs console.

**Comment by mcheshkov** [comment]
That's because you didn't introduce a variable in a scope that masks global.

    > typeof(global) == 'undefined'
    false
    > function(){ if(typeof(global) == 'undefined'){var global = this; return "assigned";} return "not assigned";}()
    'assigned'

**Comment by ktimothy** [comment]
I am talking about global scope.

**Comment by mcheshkov** [comment]
Oh, I thought of `__resolveNativeClass` scope.
