### ISSUE TITLE
Compiler problem inferring a string?

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#4188]
This simple example doesn't compile:

```haxe
class Test {
    static function main() {
        var toDate = function(s) return s.length == 10 ? Date.fromString(s) : null;
        trace(toDate('error'));
    }
}
```

```
Build failure
Test.hx:3: characters 73-74 : {+ length : Int } should be String
Test.hx:3: characters 73-74 : For function argument 's'
```

(Available at http://try.haxe.org/#87a4e)

Am I misunderstanding that the compiler should infer `s` as a string?

**Comment by nadako** [comment]
It seems like it infers `length(default,default)` despite it being accessed only for reading and thus it can't later unify with String which has `length(default,null)`. Just my guess

**Comment by Gama11** [comment]
Looks a bit similar to #3297?

**Comment by ncannasse** [comment]
That's perfectly normal : the type inference works in order, so first you're reading the length field, it's then assuming the type is "at least" `{ var length(default,null) : Int; }` However once a type is inferred as a structure, it can no longer be promoted by type inference as a full class instance. That's a limitation of our type inference, which I don't think can be addressed without a huge change in the way the compiler works.

**Comment by ciscoheat** [comment]
Ok, thanks for the info!
