### ISSUE TITLE
Java regex escape

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4191]
OK in cpp/c#/neko/interp/flash/php/python targets, but throw runtime exception in Java target.

``` haxe
class Test {
    static function main() {
        var re:EReg = ~/[\[]/;
        trace(re.match("[")); //true

        var re:EReg = ~/[[]/; //error in java target
        trace(re.match("[")); //true
    }
}
```

Tested with latest haxe development branch, on Windows with java version 1.8.0_31.
The regex is used in [selecthxml](https://github.com/andyli/selecthxml/blob/master/src/selecthxml/engine/RegexLexer.hx#L14).

**Comment by Simn** [comment]
This causes problems with the markdown library so a quick fix would be appreciated. Otherwise I'm forced to use the PHP target. :/

**Comment by waneck** [comment]
I wish I had a specification to follow there - of what's allowed and what's not. I'll fix this bug, but there may be others like this

**Comment by Simn** [comment]
I slightly misread the issue. I can just fix this by escaping the `[` so it's not urgent at all.

**Comment by darmie** [comment]
I am also having a problem with matching `{` and `}`, Haxe strips out the escape during compilation and Java gets pissed

`new EReg('([\\s\\S]*?){([\\s\\S]*?)*}','ig');`

```
([\s\S]*?){([\s\S]*?)*}
         ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.closure(Unknown Source)
        at java.util.regex.Pattern.group0(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at haxe.root.EReg.__hx_ctor__EReg(Unknown Source)
        at haxe.root.EReg.<init>(Unknown Source)
        at hxcss.Parser.__hx_ctor_hxcss_Parser(Unknown Source)
        at hxcss.Parser.<init>(Unknown Source)
        at hxcss.Main.main(Unknown Source)
        at hxcss.Main.main(Unknown Source)
Error: Command failed with error 1

```


Then I did this too `new EReg('([\\s\\S]*?)\\{([\\s\\S]*?)*\\}','ig');` to escape the `{` same problem.

**Comment by Simn** [comment]
Looking at this again, I don't think the original issue is valid. It's an invalid regular expression and I don't want to specify our behavior in that case.

However, the example @darmie mentions is a problem: `~/{/.match("{")`. I think this should work without escaping the `{`.

**Comment by RealyUniqueName** [comment]
I don't think we should specify `~/{/` to work. Both `[` and `{` are special characters in regexes. One has to escape them for a solid cross target behavior.
Regarding @darmie's issue with escaping - that was #3430 and that is fixed since 4.0.0

**Comment by Gama11** [comment]
Could it at least error on all targets then (compile time for regex literals)?

**Comment by RealyUniqueName** [comment]
Unfortunately, no. That would require to preprocess every EReg instance with a haxe-written regex parser. 
We can probably do that at compile time for EReg instances created with `~/pattern/` literals or with constant strings like `new EReg('pattern')`, but I'm not sure if it's worth the trouble.
