### ISSUE TITLE
[Python] add python2 support

### ISSUE THREAD

**Issue by jason-womack** [HaxeFoundation/haxe#4195]
Are there any plans to add python2 support?  I have a need to target python2, and I was hoping to leverage 3to2, but the use of nonlocal prevents this.

**Comment by Simn** [comment]
IIRC last we talked about this the conclusion was that this wouldn't be very hard to do from a code generation point of view, but quite tricky regarding the python standard library.

**Comment by jason-womack** [comment]
I wish I could have been apart of that discussion.  What about generating python3 level code that is compatible with 3to2.  I have run into the nonlocal keyword being a big sticking point for the generated code working with 3to2.  Any discussion around that possibility?

**Comment by Justinfront** [comment]
To be fair to the compiler team, very few haxe users use the python 
target for much more than experimenting, so it's hard to justify the 
time required when they have so much else, but without 3to2 it's makes 
the python target a bit limited.  I think that python 2.* has been 
discussed and there is a wish to take it further but time is always a 
constraint but they are very happy to recieve suitable pull requests, 
and have to +1  3to2 feasibility

**Comment by Simn** [comment]
@frabbit: What's your opinion on this?

**Comment by frabbit** [comment]
the api changes are the difficult part, i'm pretty sure that we can optionally get rid of nonlocal, but that means that we have to pass all context variables as parameters to closures. @nadako what do you think?

**Comment by frabbit** [comment]
@simn do we need to pass all accessed context variables as params to closures for the new php target too?

**Comment by nadako** [comment]
We should research about the best performance practices in python regarding that.
Also note that C#/Java (gencommon) have a filter that generates a class for a closure that receives its context vars in a constructor and stores them in fields.

**Comment by nadako** [comment]
I haven't worked with python for ages, but I'm actually surprised and a bit disappointed that python2 is still so relevant. I thought that every big library is now at least python3 compatible.

**Comment by frabbit** [comment]
i'm not very motivated to support python 2.7 from the api point of view. We could try to workaround the nonlocal issue to enable 3to2 conversions, but i'm pretty sure that you will run into other issues with that.

**Comment by Simn** [comment]
Alright, let's drop this idea. Nobody in the compiler team is particularly interested in working on this and there would be too much effort for too little gain anyway.
