### ISSUE TITLE
DCE too aggressive

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4197]
Sorry for reporting this so late, but I always thought this was caused by some convoluted use of macros or what not. However I found this to reproduce the problem:

http://try.haxe.org/#B2CF6

Giving me:

> Uncaught ReferenceError: js_Boot is not defined,http://try.haxe.org/program/CAC32/run?r=0.2726341183297336,line:21

In complex projects I sometimes find myself with Reflect being removed even though it is explicitly used. Disabling DCE usually fixes the issue.

**Comment by Simn** [comment]
I'm pretty sure this has been fixed by https://github.com/HaxeFoundation/haxe/commit/15e8bb321dffa5671fa374d461164af213bd7044
