### ISSUE TITLE
Function binding inconsistency

### ISSUE THREAD

**Issue by MSGhero** [HaxeFoundation/haxe#4201]
http://haxe.org/manual/lf-function-bindings.html doesn't compile inside try.haxe.org. "Cannot create closure on abstract inline method." It works when map is typed as `IntMap` but not regular `Map`.

**Comment by Simn** [comment]
Related issue #2767. I forbid it back then but I don't really know why this wouldn't work.

**Comment by Simn** [comment]
Actually there's #4201 already.

**Comment by ncannasse** [comment]
Yes, but that's the one you're closing :)

**Comment by Simn** [comment]
derp

#4165
