### ISSUE TITLE
openSUSE — Error: Unbound module ExtString

### ISSUE THREAD

**Issue by DAP-DarkneSS** [HaxeFoundation/haxe#4202]
> ocaml -version
The OCaml toplevel, version 4.01.0

[   39s] + make -j2
[   39s] make -C libs/extlib opt OCAMLOPT=ocamlopt OCAMLC=ocamlc
[   39s] ocamlopt -g -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -c ast.ml
[   39s] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[   39s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/haxe-3.1.3/libs/extlib'
[   39s] ocamlopt -g -a -o extLib.cmxa enum.mli bitSet.mli dynArray.mli extArray.mli extHashtbl.mli extList.mli extString.mli global.mli rbuffer.mli IO.mli option.mli pMap.mli std.mli uChar.mli uTF8.mli base64.mli unzip.mli refList.mli optParse.mli dllist.mli multiArray.mli enum.ml bitSet.ml dynArray.ml extArray.ml extHashtbl.ml extList.ml extString.ml global.ml rbuffer.ml IO.ml option.ml pMap.ml std.ml uChar.ml uTF8.ml base64.ml unzip.ml refList.ml optParse.ml dllist.ml multiArray.ml extLib.ml
[   40s] File "ast.ml", line 463, characters 17-40:
[   40s] Error: Unbound module ExtString
[   40s] Did you mean String?
[   40s] Makefile:183: recipe for target 'ast.cmx' failed

**Comment by Simn** [comment]
Make sure to checkout the git submodule. Also please post problems like this in the haxelang google group or ask in #haxe on freenode IRC.
