### ISSUE TITLE
Reflect.setField changes Ints to Floats on Neko + HTML5

### ISSUE THREAD

**Issue by scriptorum** [HaxeFoundation/haxe#4205]
On Neko and HTML5, using `Reflect.setField` to change an `Int` member of a class instance to a `Float` value results in changing the member's type to `Float` rather than implicit casting. Given the member field `var val:Int = 0;` I'd expect this to output **10, TInt** but instead it outputs **10.5, TFloat**.

 ```haxe
 	// public var val:Int = 0;
 	Reflect.setField(this, "val", 10.5);
 	trace(val + ", " + Type.typeof(val)); 
```

Flash and CPP do not have this issue. This problem also occurs when using `setProperty`, or when setting the property of an typed structure, such as:

```haxe
 	// typedef Stuff = { i:Int };
 	var s:Stuff = { i:0 };
 	Reflect.setField(s, "i", 10.5);
```

*Tested on haxe 3.1.3*

**Comment by Simn** [comment]
That's an expected difference between static and dynamic targets.

**Comment by scriptorum** [comment]
Ok, thanks, I was wondering if that was the reason. I guess that's what the manual was hinting at when it said, "only guaranteed to work for anonymous structures," but I thought a typed structure still counted as one.
