### ISSUE TITLE
[JS] Compile error with Haxe 3.2 JS target 

### ISSUE THREAD

**Issue by dionjwa** [HaxeFoundation/haxe#4209]
My project compiled fine before the 3.2 update but I'm now getting this error. There's no other error to indicate where this problem is:

/usr/lib/haxe/std/js/_std/EReg.hx:116: characters 1-29 : Module js.RegExp does not define type RegExpMatch

**Comment by Simn** [comment]
Are you sure your setup is correct? That type is clearly there: https://github.com/HaxeFoundation/haxe/blob/master/std/js/RegExp.hx#L42

**Comment by Simn** [comment]
Shot in the dark: Are you maybe using some library that for whatever reason has its own js.RegExp module?

**Comment by dionjwa** [comment]
You are totally right, I should have checked that myself. It was from this module: https://github.com/clemos/haxe-js-kit

**Comment by Simn** [comment]
ping @clemos

**Comment by clemos** [comment]
I see... thanks :D
