### ISSUE TITLE
Accessing a module's private class (from another module)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4210]
I'm unable to access a private class within a module (even using meta tricks like @:access/privateAccess). I'm probably doing something obviously wrong, but I can't see it... (and it doesn't seem to be a regression as far as I can tell).

Anyway I'd like to know if there is any way around it. You can try to reproduce it with this (https://gist.github.com/azrafe7/44d166d8eabc5c4e3cf3).

EDIT: be sure to use the same _paths_ as specified in the first lines.
(tested on win7 with 3.2-rc2 and 3.2)

**Comment by Simn** [comment]
I think private types can not be accessed outside of their own module by any means. ACL is field-oriented. I'll let @ncannasse confirm that though.

**Comment by ncannasse** [comment]
Yes, @:access is only for fields, not types
