### ISSUE TITLE
Installer not recognised by Windows SmartScreen

### ISSUE THREAD

**Issue by bubblebenj** [HaxeFoundation/haxe#4211]
When I try to install haxe-3.2.0-win.exe, I've an error message probably due to the absence of publisher in the exe signature:
> Windows protected your PC
> Windows SmartScreen prevented an unrecognised application from starting. Running this application > might put your PC at risk."
> 
> Publisher: Unknown Publisher
> Application haxe-3.2.0-win.exe"

Technical info:
 * Windows 8.1;
 * exe launched without explicitly stating "run as administrator"

Note:
  I don't remember having this warning on the RC

**Comment by Simn** [comment]
This is an NSIS installer. We do specify a company name here: https://github.com/HaxeFoundation/haxe/blob/development/extra/installer.nsi#L26

Maybe it's missing some other relevant information. I suppose https://github.com/HaxeFoundation/haxe.org/issues/77 is somewhat related.

**Comment by Simn** [comment]
I checked the 3.2.1 installer again and all the relevant information seems to be in place. I can't see what else we could do about this, so I'll go ahead and close the issue.

**Comment by abraaoprogramador** [comment]
Hello! I downloaded the haxe-4.0.5-win64.exe from here: https://haxe.org/download/ and the same problem is happening.
