### ISSUE TITLE
Missing class in DOMElement.hx

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe#4212]
Hi,
I got this compilation error with a fresh install of haxe 3.2 on javascript target

C:\HaxeToolkit\haxe\std/js/html/DOMElement.hx:219: characters 1-177 : Type not found : Text
Build halted with errors (haxe.exe).

haxe 3.2 from windows installer , Windows 7 , flashdevelop

**Comment by bablukid** [comment]
Text.hx is not in C:\HaxeToolkit\haxe\std\js\html\ ...
I can get them from the haxe repo, but some other elements are missing now : TableElement , TableRowElement ...

**Comment by Simn** [comment]
Setup problem? These files clearly exist: https://github.com/HaxeFoundation/haxe/tree/master/std/js/html

**Comment by bablukid** [comment]
Yes I know,  I had to copy-paste more than 10 files from the git repo ( js/html/* ) to make it compile.

There could be a bug when you build the windows installer ?

**Comment by Simn** [comment]
These files exist in the installer. This really looks like some setup issue on your end.

**Comment by ncannasse** [comment]
Could you confirm you have the file on your drive ?
That could be several issues related to ACL : the installer was not able to write the file, or the compiler is not able to read it

**Comment by bablukid** [comment]
no Nicolas, the files were NOT on my hard drive after install.
I just re-ran the installer several times, and now its OK, all the files are copied... 
It's very mysterious, my SSD hardrive is new and working perfectly.   
Moreover , I ran into this issue with rc2 installer some weeks ago, but with different files in js/html/*
https://groups.google.com/forum/#!searchin/haxelang/from$3Ame/haxelang/Hsn0SupK6RA/NCSZd6P928kJ

**Comment by andyli** [comment]
@bablukid Was it possible that you've compilation server running which was using the files during upgrade? It may be opened by an IDE, for example I know that the Sublime Text plug-in has trouble closing the compilation server when Sublime Text exits.

**Comment by Simn** [comment]
I don't think that could lead to missing files, especially not silently.

But I don't know what else to blame it on either.

**Comment by bablukid** [comment]
@andyli , yep its a good idea, during my first installation I had a prompt window and had to stop apache which was locking neko, and stop haxe.exe which was launched by FD I guess.

I tried to reproduce this in my later tries, but I failed to reproduce the bug.
