### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4213]
Haxe supports jQuery in the Standard Library. The latest jQuery version is 2.1.14 and 1.11.3 (version 1 supports Internet Explorer 6, 7, or 8). The Haxe extern classes are targeted for 1.6.4 (<a href='https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery-latest.min.js#L1'>right?</a>). Our version is old and does not contain all functions and is not documented.

It would be nice if we support the latest version or adopt/support https://github.com/andyli/jQueryExternForHaxe

**Comment by ncannasse** [comment]
@andyli could you take care of it ?

**Comment by andyli** [comment]
Ok, will look into it next week.

**Comment by andyli** [comment]
addressed in #4377
