### ISSUE TITLE
How do I store dynamically a movieclip in a array in Haxe/HTML5?

### ISSUE THREAD

**Issue by zulu12345** [HaxeFoundation/haxe#4215]
This is my code:

var buttons:Array<Dynamic> = new Array<Dynamic>();
var mc2:flash.display.MovieClip = new MovieClip();
mc2.graphics.beginFill(0xFF0000);
mc2.graphics.moveTo(50,50);
mc2.graphics.lineTo(100,50);
mc2.graphics.lineTo(100,100);
mc2.graphics.lineTo(50,100);
mc2.graphics.endFill();

buttons.push(addChild(mc2));

buttons[0].x = 1000;

And my question is why this work in Flash but not work in HTML5 when I compile it? How do I solve the problem? The last line “buttons[0].x = 1000;” is not working in HTML5… :/

Sorry for my english...

**Comment by Simn** [comment]
Try asking questions like that in the haxelang google group or in the #haxe IRC channel on freenode.
