### ISSUE TITLE
Calculate rounding of constants at compile time

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4223]
This is just a minor thing, but it seems weird to see `Math.ceil(3.6)` in the output.

**Comment by Simn** [comment]
Done, but could you do me a favor and double-check that I got the 32bit corner cases right here: https://github.com/HaxeFoundation/haxe/blob/development/tests/optimization/src/issues/Issue4223.hx

**Comment by back2dos** [comment]
Awesome!

Can't you just NOT deal with the corner case, i.e. just leave the call
untouched if the constant is outside certain bounds (e.g. -1e9 to 1e9)?
That certainly should not cause issues for anyone.

**Comment by Simn** [comment]
That's what I'm doing, I just wasn't sure if I got the bounds right.
