### ISSUE TITLE
Allow passing package paths on command line

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4227]
Recently I have seen several questions of how to include an entire package for compilation because it's not obvious from reading the command line documentation. We could allow passing a package dot path which we identify by the character after the last dot being lower-case, e.g. `haxe haxe.macro`.

Internally this would just add `--macro include(passed.dot.path)` as argument. The only part I'm not sure about if it should be recursive or not.

**Comment by ncannasse** [comment]
I think it should be more explicit, like `haxe.macro.*` because you might have `haxe.Macro` class, and yes recursive by default makes sense

**Comment by Simn** [comment]
haxe.macro != haxe.Macro so I don't see why that would be a problem.

Regarding recursive, you technically have more choice if it's not recursive because you can still decide to manually add sub-packages as another argument. But I'm also leaning towards making it recursive by default.
