### ISSUE TITLE
Array to parameterized constructor, with abstracts and interface causes mixed type error

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4231]
I have no idea how to describe what is wrong here. But this is the case:
* there is an "Action" interface 
* there are some classes that implement this interface
* there are two abstract classes which from/to a "Sequence" class. Sequence implements the interface
* there is a class called Parallel, which has a constructor that looks like this
```haxe
 public function new <A:Action> (?actions :Array<A>)
 {
        _actions = (actions != null) ? cast actions.copy() : [];
 }
```
* I directly pass an array with some actions to the Parallel class constructor. See testcase below.
* When I pass 2 abstract actions to the array I get these two errors:  
`Test.hx:13: characters 48-71 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>`  
`Test.hx:13: characters 48-71 : DelayedEffect2 should be DelayedEffect1 `

I create a actual testcase: http://try.haxe.org/#A3402

I hope this helps. 
* Note: When I change the constructor to `public function new (?actions :Array<Action>)`, it **does compile** and provide expected behavior.
* I stripped a lot for case of example; The actions classes are [part of the Flambe core](https://github.com/aduros/flambe/tree/master/src/flambe/script) (see Parallel, Sequence).
* It happens with Haxe 3.2, but also on try.haxe (3.2-rc2). 
* I compile to Javascript target.

**Comment by Simn** [comment]
What you're reporting is essentially this:

```haxe
class Main {
	static function main() {
		test(1, 2.); // Float should be Int
	}

	static function test<T:Float>(t1:T, t2:T) { }
}
```

`T` is bound to `Int` because it's the first argument. The unification of the second argument then fails because it tries to assign `Float` to `Int`.

I think this is working as intended as far as our current implementation is concerned.

**Comment by markknol** [comment]
Ok in that case there is no actual problem. I found it weird, but now it makes sense. Thanks for explaining.
