### ISSUE TITLE
Type.createInstance JS target too many arguments

### ISSUE THREAD

**Issue by urbananimal** [HaxeFoundation/haxe#4232]
The arguments parameter of the Type.createInstance method has a limited length of 8 arguments on the JS platform. Is there a good reason for this? It seems odd given that the flash target can take 14.

**Comment by Simn** [comment]
This approach seems strange to me anyway. Can't we do whatever it is Reflect.makeVarArgs is doing?

**Comment by nadako** [comment]
One can't simply `apply` constructor in JS, see http://stackoverflow.com/questions/1606797/use-of-apply-with-new-operator-is-this-possible

**Comment by Simn** [comment]
The highest rated answer there suggests that you can do it though.

**Comment by nadako** [comment]
Yeah but we still need to support IE8 and other old crap, so this may not work.

**Comment by Simn** [comment]
Bleh... fine then, let's ghetto-fix this. I'm guessing there's no particular reason behind the max number being 14 and it was just what Nicolas needed at the time.

**Comment by nadako** [comment]
We should still get rid of that nonsense. I'll reopen and assign this to myself, since I'd like to look into finding a better way to do this, at least on `-D js-es5`.

**Comment by ncannasse** [comment]
@nadako that's assuming that JS actually makes sense :)

**Comment by nadako** [comment]
According to [this](http://kangax.github.io/compat-table/es5/#test-Function.prototype.bind), `Function.prototype.bind` is supported quite well, so it should be safe to replace the nonsense with a solution from the [SO answer](http://stackoverflow.com/a/8843181/2556830), unless `js-es < 5`
