### ISSUE TITLE
Local DCE vs. global DCE

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4239]
Question: Should local (expression) DCE be allowed to affect global (type) DCE by removing field access expressions that have no effect? We have something like this in our unit tests:

```
class Main {
	static var c:Array<Dynamic> = [null, UsedReferenced];

	static function main() {
		c.length;
	}
}

class UsedReferenced { }
```

In my local analyzer version expression-level DCE gets rid of the `c.length` expression because it doesn't do anything at run-time. This causes the `c` field to be removed by DCE which in turn removes the `UsedReferenced` class.

I like this behavior but it might be observed as a regression in rare cases.

**Comment by nadako** [comment]
This sounds very logical so I think it should be implemented. I wouldn't worry too much about regressions, because people are used to deal with `dce=full` issues anyway, and for std we can fix this quickly.

**Comment by aduros** [comment]
:+1: for stronger DCE. Users always have `@:keep` if they need it.

**Comment by ncannasse** [comment]
Seems fine to me

**Comment by sledorze** [comment]
Totally agree with @aduros here, +1

**Comment by Atry** [comment]
Cool!
