### ISSUE TITLE
Possible serialization problem for js

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#4240]
The following code runs fine with `haxe -main Test --interp`:

**Test.hx**
```haxe
class Todo
{
	public var description : String;
	public var done : Bool;

	public function new(description) {
		this.description = description;
		this.done = false;
	}
}

class Test {
    static function main() {
        var list = "acy4:Todoy11:descriptiony4:testy4:donetgh";
        var ser = new haxe.Unserializer(list);
        
		trace(ser.unserialize());
    }
}
```

Output: `Test.hx:17: [{ done => true, description => test }]`

Unfortunately it seems to fail on javascript in certain circumstances. Compiling this simple example to js and running in the browser like this works:

```html
<!DOCTYPE html>
<html lang="en">
<body>
<script src="test.js"></script>
</body>
</html>
```

But on http://try.haxe.org/#e9289 it doesn't work: `Uncaught Error,http://try.haxe.org/program/e9289/run?r=0.07902561803348362,line:314`

And I've encountered the same problem in other complex situations. Any ideas?

**Comment by Simn** [comment]
DCE?

**Comment by ciscoheat** [comment]
Yes, it was a dce issue! Adding a Todo reference on try.haxe.org fixed it there as well. Sorry for the oversight.
