### ISSUE TITLE
[cpp] Name generation clash

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#4246]
This does not compile on the cpp target.
Both 'and' and '_and' haxe functions are translate to a cpp function named '_and'.

```haxe
class Main {
	public static function and() {
	}
	public static function _and() {
	}
	public static function main() {
		and();
		_and();
	}
}
```

**Comment by hughsando** [comment]
@simn - do you have any ideas on a "reserved prefix".  I know some people (Joshua, and compilers) use double-underbar.  I could use ```_hx_```.  I'm also pretty much reserving the "hx::" namespace for cpp, so maybe some official (compiler supported ?) restriction on the start of variable names would make it easier for code generators.  What do you think?

**Comment by Simn** [comment]
I would also like to see `_hx_` being reserved. It really makes it easier to code generators to deal with some naming.

**Comment by nadako** [comment]
genpy also uses `_hx_` iirc, so i guess that's a good idea

**Comment by waneck** [comment]
C#/Java targets use `__hx_`. But I'd be happy to change it to `_hx_`

**Comment by Simn** [comment]
You can use `_hx_` now.
