### ISSUE TITLE
Asking for trouble : Pattern matching

### ISSUE THREAD

**Issue by pleclech** [HaxeFoundation/haxe#4247]
Should this case be accepted by the compiler ? : 
http://try.haxe.org/#2d484

```haxe
class Test {
    static function main() {
        trace("Haxe is great!");
        var x:Dynamic;
        if (Math.random() < 0.5) x=3;
        else x = [];
        switch(x) {
           case 3 : trace(x);
           case [] : trace(x);
        }
    }
}
```
and if the answer is true, the JS code generated seems wrong : it act as x is an array and match on it's length

```javascript
(function (console) { "use strict";
var Test = function() { };
Test.main = function() {
	console.log("Haxe is great!");
	var x;
	if(Math.random() < 0.5) x = 3; else x = [];
	switch(x.length) {
	case 3:
		console.log(x);
		break;
	case 0:
		console.log(x);
		break;
	}
};
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

**Comment by Simn** [comment]
This cannot be translated to a decision tree without making a huge mess, so it is undefined behavior.

**Comment by pleclech** [comment]
Maybe generate a warning or an error ? There is an error generated when you try to match a dynamic with a structure.

**Comment by ncannasse** [comment]
It seems weird to me to qualify switch on Dynamic as undefined behavior. We should either forbid it or only allow same type for all patterns.

**Comment by Simn** [comment]
I thought you wanted to allow this:

```
switch (x) {
    case 12:
    case "foo":
}
```

I remember going out of my way to make this work.

**Comment by pleclech** [comment]
No, it was an open question, and i wanted to point out that the code generated was wrong with no way to know it.

**Comment by Simn** [comment]
@ncannasse: You're gonna have to tell me what you want and don't want to support with regards to matching on Dynamic. I'm afraid your MT friends are gonna burn my house down if we stop supporting mixed patterns in general.

**Comment by ncannasse** [comment]
Let's try to put an error if the type of the patterns are not compatible (allow Int/Float, but no String/Float), and see how much they complain about it :)

**Comment by Simn** [comment]
Let's ask @delahee first...

I'm also not sure that this would be consistent language-design. We don't unify e.g. the elements of an `Array<Dynamic>` with each other so I'm not sure we should do that for patterns.

**Comment by ncannasse** [comment]
OTOH we might want to support switch on Dynamic, but then that should be strictly equivalent to if( v == pattern1) elseif( v == pattern2 ) ... else (we might want to forbid non constant patterns here then)

**Comment by ncannasse** [comment]
But the problem is that if the patterns have a common type (for instance an enum), then in that case we should be able to switch on it even if the value is Dynamic given that it will be casted to the enum

**Comment by delahee** [comment]
Imvho Nicolas response seems fine. I am very for you house :(. I think the
truffle reference was overkill ;)

**Comment by Simn** [comment]
Related question:

```haxe
private enum MyEnum {
	SomeValue;
	DifferentValue;
}

class Main {
	static function main() {
		var val:Dynamic = MyEnum.DifferentValue;
		switch(val) {
			case MyEnum.SomeValue:
		}
	}
}
```

"Unmatched patterns" error or not?

**Comment by ncannasse** [comment]
I would say yes. In that case that's the same as switch((val:MyEnum))
