### ISSUE TITLE
Compilation server/resolveClass

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4248]
Today while I was coding a new project I experienced some issue which I think is related to DCE/features + compilation server.

I was compiling a project and when I started using haxe.Unserializer to read some file it complained at runtime with a JS error which looked like `Error Object function() {} has no method resolveClass`. 

Switching to Debug compilation solved the error, reswitching to Release bring it back. Restarting FlashDevelop made it disappear. I suppose I had some bad state in my compiler cache due to previous compilations which didn't required resolveClass or something of this kind.

Sadly, I didn't made a copy of the JS output to confirm what was missing when the error was occurring.

**Comment by Simn** [comment]
Let's file this under campfire-mystery-stories for the time being.
