### ISSUE TITLE
Skip class if empty

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4249]
Sometimes in the class path you can have some std class that you want to override depending on the flags/platform. ATM this is not possible. I propose that if the parsed class is empty (no type definition) we resume to the next class path instead of accepting this module.

Practical case : nodejs library override haxe.io.Bytes by using NodeBuffer data. I would like to be able to disable this override when I compile with a define since it breaks some other code using bytes+native typed arrays when doing NodeJSWebkit which has both HTML and NodeJS backend.

**Comment by Simn** [comment]
Doesn't that practical case require modifying the library source file, which would make it rather impractical?

It might be easier to expose `file_lookup_cache` to initialization macros so you could manually map dot paths to file paths.

**Comment by Atry** [comment]
Does it resolve #4235

**Comment by ncannasse** [comment]
@Simn might be a good idea to implement it this way, we need to warn that adding class path will clear lookup

**Comment by R32** [comment]
I have the same problem, But I noticed that if you are not using the '--macro' such as '--macro allowPackage ('sys') ',  is possible to override std class

so I am using this method to overwrite std class, but this not very friendly for IDE

extraParams.hxml
```
--macro allowPackage('sys')
--macro addClassPath('overrideClassPath') 
```

i wish i could use `import std.path.Class`  to force the std class

**Comment by nadako** [comment]
> i wish i could use import std.path.Class to force the std class

That's actually what I was trying to do first in https://github.com/HaxeFoundation/hxnodejs/issues/42, e.g.:

```haxe
package haxe.io;

#if (js && nodejs)
class Bytes { ... }
#else
typedef Bytes = std.haxe.io.Bytes;
#end
```

**Comment by ncannasse** [comment]
That's actually more an issue than I was originally thinking. As soon as a library overrides a std class, it will take precedence over the std/_std versions, which makes the class unusable from macros.
I think then that we should follow my original proposal which does not require manual macro path configuration.

**Comment by Simn** [comment]
We have to be careful with our terminology here between files and types. Do we really want to fallback on any empty type?

**Comment by ncannasse** [comment]
fallback on a module that does not define any type

**Comment by ncannasse** [comment]
...and if the fallback fails (no other matching file), we still need to accept the empty module

**Comment by Atry** [comment]
Does this related to #4626

**Comment by Simn** [comment]
This is quite awkward to implement. I got it working by having an additional `empty_files` Hashtbl in the context which `find_file` checks. This is not very elegant and requires "restarting" the lookup on empty modules. Maybe I'm missing a more obvious approach here.

**Comment by Simn** [comment]
Well, it's been more than 4 years and it doesn't look like the lack of this feature caused anyone major problems, so I'll go ahead and close it.
