### ISSUE TITLE
Structural sub-typing type hole

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4250]
```
typedef Node = { parent: Node };

class SomeNode {
	public var parent:SomeNode;
	public function new() { }
}

class Main {
	static function main() {
		var someNode = new SomeNode();
		var n:Node = someNode;
		n.parent = { parent: null };
	}
}
```

I was surprised to find that the `var n:Node = someNode` assignment is allowed. It allows writing a different type to the `parent` class field which then causes trouble if accessed via the original type. Consequentially this fails on e.g. flash with `Type Coercion failed: cannot convert Object@64d7299 to SomeNode`.

**Comment by ncannasse** [comment]
That seems weird to me as well. Could you confirm if that's a regression from older haxe ? (2.10 ? 3.0 ?)

**Comment by Simn** [comment]
Regression from 3.1.3 caused by https://github.com/HaxeFoundation/haxe/commit/cd38ec

Not release-critical in my opinion.

**Comment by ncannasse** [comment]
My bad. Let's make sure we add an unit test this time

**Comment by Simn** [comment]
I investigated this a bit and I suspect that your fix merely fixed the symptom, not the cause. Let's look at it:

```haxe
var n:Node = someNode;
```

This is `unify TInst TType` which pushes `(SomeNode, Node)` onto the stack and recurses with the applied type `unify TInst TAnon`. This iterates the fields, or in this case the single field `parent`. Your added stack-check comes into play and checks for `(classField.type, anonField.type)`, which in this case is `(SomeNode, Node)`, which is already on the stack.

It then does not recurse further, *but* the problem is that here we should check for type equality (via `unify_with_access`) instead of just unification. In other words, the fact that something is on the unify stack should not prevent an equality check.

**Comment by ncannasse** [comment]
Actually quickly looking at it I wonder if removing the unify_stack registration of my patch wouldn't help. We have no reason to register it before we enter unify_with_access

**Comment by Simn** [comment]
That doesn't matter here, the branch is never entered because the types are already on the stack from the `unify TInst TType`.

**Comment by Simn** [comment]
> Let's make sure we add an unit test this time

**Comment by Simn** [comment]
This is not RC-critical.
