### ISSUE TITLE
DataView unnecessarily included in js

### ISSUE THREAD

**Issue by daurnimator** [HaxeFoundation/haxe#4259]
I upgraded to a newer release of haxe 3, and now some of my code that compiles to js includes a compat implementation of `DataView` (`js_html_compat_DataView`), but doesn't use it.

**Comment by ncannasse** [comment]
@Simn not easy : we might need to remove DataView compat if the user does not uses typed arrays

**Comment by Simn** [comment]
How do I reproduce this?

**Comment by daurnimator** [comment]
> How do I reproduce this?

Anything that uses `haxe.io.Bytes` will pull it in.
e.g. if I want to convert a string to base 64:

```
class Main {
	static public function main() {
		var foo:String = haxe.crypto.Base64.encode(haxe.io.Bytes.ofString("testing"));
		trace(foo);
	}
}
```

**Comment by Simn** [comment]
Any other types that need DataView?

**Comment by Simn** [comment]
I'll take that as a no.

**Comment by ncannasse** [comment]
Sorry I overlooked it, but you could have search by yourself : DataView is used by haxe.io.Bytes

**Comment by ncannasse** [comment]
it is necessary for the getXXX/setXXX methods in JS.

**Comment by Simn** [comment]
But haxe.io.Bytes references it explicitly, so I don't think that's a special case for DCE?

**Comment by ncannasse** [comment]
@Simn the problem here is that we @:keep js.html.compat.DataView as long as DataView is included, even if not used (because it's a runtime fallback)

**Comment by ncannasse** [comment]
ideally we would like to DCE DataView and compat.DataView together, but since DataView is extern I don't think it's subject to DCE

**Comment by ncannasse** [comment]
PS : this also apply to all js.html.compat classes

**Comment by Simn** [comment]
I think an `@:ifFeature("js.html.DataView.*")` whould work, extern or not. This is not very easy to verify for all cases though...

**Comment by daurnimator** [comment]
What's the status on this issue? I'm unclear if it was fixed or not....

**Comment by Simn** [comment]
I seem to be too stupid to understand this issue. I have made a change that keeps the compat version if and only if the non-compat version is used. However, this means that using haxe.io.Bytes automatically pulls the Uint8Array and ArrayBuffer compats, which seems to go against what this issue was originally about.

**Comment by daurnimator** [comment]
I think that fixed it?
I compiled my testcase from earlier and it doesn't seem to include the dataview component any more.

**Comment by Simn** [comment]
The compat imports have been added to the html-externs generator: https://github.com/HaxeFoundation/html-externs/compare/cbdf7434d3...23f35bca49#diff-578cf95d83664a58577bda0df5fd6e73R363

That should conclude this issue.
