### ISSUE TITLE
[php] Problem with Float/Int equality

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4260]
```
class Main {
    static function main() {
        var f:Float = 0;
        var i:Float = 0.0;
        trace(i == f); // false
    }
}
```

genphp tries to be smart by determining that the operand types are equal and thus being able to use `===`, which evaluates to `false`. Note that it could not use `==` either because that would give incorrect equality results when `null` is involved. This is somewhat problematic because it would mean we have to go a slow equality route for _every_ numeric equality check.

We can try to detect the original assignment of `0` to Float and convert it at run-time, but I have no idea if PHP is going to play along.

**Comment by Simn** [comment]
This is kind of related to old neko issue #1282.

**Comment by RealyUniqueName** [comment]
I went a slow route for float vs float comparison. One should not check floats for equality anyway.

**Comment by back2dos** [comment]
I propose to do the following instead:

1. Any integer constant top down inferred to be a float should be generated as float, i.e. the above `var f:Float = 0` should generate `$f = 0.0`.
2. Any int expression unified with float should be wrapped in `floatval`.

**Comment by RealyUniqueName** [comment]
Such approach will not cover floats which come from dynamics (json, external php code, native functions). While current fix works for any case with the least possible overhead.
