### ISSUE TITLE
Duplicate metadata "interface" when using Haxe Compilation Server

### ISSUE THREAD

**Issue by blue112** [HaxeFoundation/haxe#4261]
When compiling a big ufront project to neko, everything come fine and my binary comes out ok.
When adding a --connect and connecting to a haxe compilation server to improve compilation time, everything is fine the first time, but every next times it throws this error an compilation unless I restart the server :

    /usr/lib/haxe/std/StdTypes.hx:119: characters 7-35 : Duplicate metadata 'interface'

Using very lastest developement branch, happens too on 3.2.

Here is the full `haxe -v --wait 6011` log : http://pastebin.com/FUewZLdk

**Comment by Simn** [comment]
Could you check if this still happens on latest development?

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/issues/4840#issuecomment-187713621
