### ISSUE TITLE
Custom pattern matching for custom enums in JS

### ISSUE THREAD

**Issue by knuton** [HaxeFoundation/haxe#4264]
I am researching the possibilities for working with tagged unions coming from external JS modules, and changing the underlying representation of Haxe enums in JS targets is one possible solution. I discussed this with @Simn a little bit and he suggested I open an issue.

While [custom JS generators allow to change the representation](https://github.com/HaxeFoundation/haxe/blob/master/std/haxe/macro/ExampleJSGenerator.hx#L170) by changing the enum type and constructor functions, this seems of little use as long as it is not possible to also customize pattern matching on enum values.

It is actually possible to [descend into expressions](https://github.com/HaxeFoundation/haxe/blob/master/std/haxe/macro/ExampleJSGenerator.hx#L65), so I was trying to see whether it is possible to do some kind of transformation on switch expressions here. But if I understand correctly, at this point in the compilation process it is too late to cleanly influence destructuring, as the pattern matcher has already transformed the switch expression. (The value switched on is the numerical tag, extracted by array access to the underlying representation of the enum value.)

While it looks like the necessary information to generate the intended destructuring could still be retrieved from the [`TSwitch`](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Type.hx#L915), I have some concerns about this:
- Even in case I find all the necessary information, this feels very much like I'd be relying on internal implementation details, and I am at the pattern matcher's whim :cold_sweat: 
- Maybe I am lucky and am able to transform the AST such that the adequate pattern matching code (in JS) is generated from a transformed AST -- if not, I'll probably have to write quite a bit of macro code to descend into the tree and generate JS code (the bulk of which now happens in [one call to the API](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/ExampleJSGenerator.hx#L66))
- I am generally unsure how future-proof custom JS generation is, considering https://github.com/HaxeFoundation/haxe/issues/2367, https://github.com/HaxeFoundation/haxe/issues/930, https://github.com/HaxeFoundation/haxe/pull/2588

What are the future plans for custom code generators in Haxe? And would it be possible to extend the [generator API](https://github.com/HaxeFoundation/haxe/blob/madter/std/haxe/macro/JSGenApi.hx) such that customizing pattern matching on enums becomes similarly straightforward as customizing enum construction?

Thank you!

**Comment by Simn** [comment]
@ncannasse: This is the prezi issue I told you about. I'm interested in your opinion on this.

**Comment by nadako** [comment]
I'm not sure I understood correctly, but this sounds like a feature I also often feel need for, not only on JS though. My use case is JSON data which is basically a tagged union but requires specific format and I would like to have a pattern matching syntax for that. For example:

```haxe
typedef SkillEffect = {
    ?Damage:{min:Int, max:Int},
    ?Dealing:Int
}; // either {Damage: {min:5, max:10}} or {Dealing: 10}
```

It would be really great to switch on this structure like this:
```haxe
switch (effect) {
    case Damage(dmg): // ...
    case Healing(amount): // ...
}
```

and generate js like:
```js
switch (Reflect.fields(effect)[0]) {
   case "Damage": var dmg = effect.Damage; // ...
   case "Healing": var amount = effect.Healing; // ...
}
```

what I thought would be a good idea is to hook up a macro for abstract type somehow, so I could define an abstract over that structure and have a macro method with e.g. `@:match` metadata that is executed when a switch is typed on this abstract.

What do you guys think? Is this even related to the original discussion?

**Comment by knuton** [comment]
@nadako Yes! Very much related to the original discussion, though not this issue (which is specifically concerned with customising the internal representation of native enums). I'll open a separate issue summarising a discussion more along the lines of your idea.

**Comment by ncannasse** [comment]
@knuton could you abstract a bit the problem you're actually trying to solve, that would help us answer it in a more efficient manner, thanks

**Comment by ncannasse** [comment]
PS : the top problem I can see atm is that changing the way enums are represented also affects some parts of the std library such as Reflect API

**Comment by Simn** [comment]
Regarding the reflect API, we should:

1. Address #4274
2. Add `getIndex()` etc. functions to EnumValue
3. Use that
4. Let the generators deal with it.

This would also allow the static analyzer to be much less awkward around enums. It would require some changes across all targets but in return we get a much cleaner AST and generators can adapt to possible changes in the enum representation.

**Comment by knuton** [comment]
@ncannasse I opened #4281 for the more general question

I still think this is a reasonable issue of its own, clarification of the intent of allowing custom enum encodings in JS would be helpful.

**Comment by nadako** [comment]
as discussed in https://github.com/HaxeFoundation/haxe/issues/4281#issuecomment-108285460, it would be also useful in some cases to have different representation for different enums (though i'm not sure if it worth the complication)

**Comment by back2dos** [comment]
@nadako I'm rather confused why you need reflection here. What's wrong with this?

```
switch (effect) {
    case { Damage : dmg } if (dmg != null):
    case { Healing: amount } if (amount != null):
}
```

Ideally the `null`-clause should be implicit if matching against optional fields, so then it comes down to:

```
switch (effect) {
    case { Damage : dmg }:
    case { Healing: amount }:
}
```

Wouldn't that work for you, without having to use Reflect or tamper with the way enums are represented?

**Comment by Simn** [comment]
Unfortunately we never reached a conclusion here.
