### ISSUE TITLE
enum abstract target inconsistency

### ISSUE THREAD

**Issue by Marc010** [HaxeFoundation/haxe#4266]
This code here prints 'int' on js/swf and nothing on cpp/neko. Doesn't seem to be affected by the analyser or dce.
```haxe
@:enum abstract Key(Int) from Int to Int
{
	var A = 1;
    var B = 2;
}

class Test {
    static function main() {
        // prevents dce, k is always 0
        var k:Key = Std.int(Math.random() * 0.1);
        switch k
        {
        	case A | B: trace('ab');
            default: trace('int');
        }
    }
}
```
The problem is that the implicit cast from int allows k to be set to values not part of the enum. Enums should be finite sets so this switch doesn't make sense but i still kind of expected the default case to catch every possible int value. If that's not possible it would be nice if the compiler could generate a warning as this inconsistency can cause hard to find bugs :)

Here is the relevant piece of c++ source:
```cpp
	Float _g = ::Math_obj::random();		HX_STACK_VAR(_g,"_g");
		HX_STACK_LINE(9)
		Float _g1 = (_g * 0.1);		HX_STACK_VAR(_g1,"_g1");
		HX_STACK_LINE(9)
		int k = ::Std_obj::_int(_g1);		HX_STACK_VAR(k,"k");
		HX_STACK_LINE(10)
		switch( (int)(k)){
			case (int)1: case (int)2: {
				HX_STACK_LINE(12)
				::haxe::Log_obj::trace(HX_CSTRING("ab"),hx::SourceInfo(HX_CSTRING("Test.hx"),12,HX_CSTRING("Test"),HX_CSTRING("main")));
			}
			;break;
		}
		HX_STACK_LINE(15)
```

**Comment by Gama11** [comment]
That prints `int` for me on all mentioned targets (cpp, swf, js). Are you on Haxe 3.2.0? Is hxcpp up to date?

[Here](http://pastebin.com/S8yv98YA)'s the cpp code it generates for me.

**Comment by Marc010** [comment]
Fixed by updating Haxe ( I thought I had already updated to 3.2.0 a while ago).
