### ISSUE TITLE
Character .code property missing from field access completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4270]
```haxe
class Main {
    static function main() {
        "8".|
    }
}
```

```
haxe --display Main.hx@0
```

The special `code` property for single-char strings is missing (full output [here](http://pastebin.com/mVuLV38J)). Tested with latest Haxe (5e154b2).

**Comment by Simn** [comment]
@nadako: Do you know if/how we can add a test for this?

**Comment by Gama11** [comment]
Couldn't you just check if the completion result for my code snippet contains `<i n="code">`?

**Comment by nadako** [comment]
how is that different from other completion tests? oh wait, you want me to do that, i got it:)

**Comment by Simn** [comment]
I just didn't want to test against the entire string specification because that is gonna break every time we adjust some documentation.

**Comment by nadako** [comment]
oh i see. well we could parse and check xml
