### ISSUE TITLE
Openfl Sockets targeting c++/neko

### ISSUE THREAD

**Issue by HaxeSerpent** [HaxeFoundation/haxe#4271]
import openfl.net.Socket;
var socket:Socket = new Socket();
socket.connect("127.0.0.1", 51432);

It connects to the server but crashes instantly with any incoming data. Is this even supposed to work on c++?

**Comment by Gama11** [comment]
> `openfl.net.Socket`

Wouldn't that make it an openfl issue?

**Comment by HaxeSerpent** [comment]
Wikipedia
>Although OpenFL is built on the Haxe language, no member of the Haxe core team has contributed to OpenFL, and they are not affiliated in any way.

Shit. I missed this line. Ok everyone, disperse there is nothing to look at.

**Comment by Gama11** [comment]
You can close issues yourself, there should be a close button next to "comment".

For OpenFL issues, there's a separate repo: https://github.com/openfl/openfl

**Comment by Justinfront** [comment]
I wondered if this project might be relevant it seems to use openfl for 
flash target and nme for c++?
https://github.com/dimanux/socket.io-openfl-client

But I have not tried it and don't know anything about this topic, so 
it's just a guess that it might be useful.
