### ISSUE TITLE
@;genericBuild and Type Param in a wrapper class

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxe#4272]
I have the following code:
and I get this error :

```
src/Main.hx:10: characters 9-21 : test.generated.AbstractTest has no field testing
```

``` haxe
class Main{

    var list : TestList<String> = new TestList();
    public static function main(){
        new Main();
    }

    function new(){
        for (elem in list){
            trace(elem.testing());
        }
    }
}

@:genericBuild(MacroTest.apply())
class Test<T>{
}

class TestList<T> extends List<Test<T>>{

}
```

``` haxe
import haxe.macro.Expr;
import haxe.macro.Context;
import haxe.macro.Type;

class MacroTest {
    public static function apply():ComplexType {
        var pos = Context.currentPos();

        var newFields = new Array<Field>();
        newFields.push({
            name:"testing", 
            access:[APublic],
            kind : FFun({
                args:[], 
                ret:macro :String, 
                expr:macro return this.substr(1)
            }), 
            pos : pos
        });

        var classPath = {pack : ["test","generated"], name:"AbstractTest"}
        var typeDefinition : TypeDefinition = {
            pos : pos,
            pack : classPath.pack,
            name : classPath.name,
            kind :TDAbstract(macro :String),
            fields:newFields
        }

        Context.defineType(typeDefinition);

        return TPath(classPath);
    }
}
```

``` hxml
-main Main
-cp src
-js bin/Main.js
```

It seems that the @:genericBuild does not get called again from type inference in the loop when the actual class with @:genericBuild is not visible in the code usage

**Comment by mcheshkov** [comment]
Have you tried marking `class TestList<T>` as `@:generic` ?

**Comment by mcheshkov** [comment]
Or returning `Type` using `ComplexTypeTools.toType()`

**Comment by wighawag** [comment]
Hi @:generic works but only if I do not use type inference :

```haxe
var list : TestList<String> = new TestList<String>();
```

if I do the following 
```haxe
var list : TestList<String> = new TestList();
```
it fails with:
```
src/Main.hx:3: characters 31-45 : Could not determine type for parameter T
```

Regarding ComplexTypeTools.toType() I am not sure what you are suggesting
if I execute this on the complexType created in MacroTest.apply() and return the haxe.macro.Type
I get the following error :
```
src/MacroTest.hx:33: characters 8-56 : Null<haxe.macro.Type> should be haxe.macro.ComplexType
src/MacroTest.hx:33: characters 8-56 : haxe.macro.Type should be haxe.macro.ComplexType
```

This is because a @:genericBuil macro is expected to return a ComplexType

**Comment by wighawag** [comment]
Actually in my use case I cannot use @:generic as I need to use type like { component : comp.TestComponent } and it might become even a String (a feature only possible with @:genericBuild

so something like TestList<"comp.TestComponent,test.AnotherComponent">

In that case would such wrapper be possible ?

**Comment by mcheshkov** [comment]
You should also remove return type of `apply`, or change it to `haxe.macro.Type` to return `ComplexTypeTools.toType` - 3.2.0 allows both `ComplexType` and `Type` from generic build macro.

About a wrapper - I thought that in `class TestList<T> extends List<Test<T>>` non-generic type will catch type params, and Test will be built with TestList.T as type param. You can use type like {foo:Bar}, at least with typedef for it, but string literal will most probably fail
