### ISSUE TITLE
Allow type param of Dynamic to be used with @:generic

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#4273]
Flambe has a @:generic Value class that wraps a value, kind of like this:

```haxe
@:generic
class Value<T>
{
    public var v :T;

    public function new (v :T) {
        this.v = v;
    }
}

var int = new Value<Int>(123); // works!
var string = new Value<String>("hi"); // works!

// Compiler error: Type parameter must be a class or enum instance (found Dynamic)
var anything = new Value<Dynamic>(666);
```

What was the reasoning behind that error message? I understand that `Value<Int>` and `Value<Dynamic>` build different classes that would not be convertible, but I really do just want a `Value_Dynamic` class that can hold a dynamic value. Is there maybe another way to do that?

**Comment by Simn** [comment]
I see no reason not to support this.

**Comment by Simn** [comment]
Forgot closing the issue, fixed by https://github.com/HaxeFoundation/haxe/commit/3c815434000305651eebd490395eaa474299ebce
