### ISSUE TITLE
Allow `@:coreType` abstract fields to omit function body

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4274]
Talking with @waneck we came up with the idea of allowing `extern abstract` to provide abstract semantics while letting the generators deal with field access. After thinking about it again I think we should simply allow to omit field expressions on `@:coreType` abstracts instead of mixing all these concepts.

Would that work for you?

**Comment by Simn** [comment]
Note that I didn't add a test because this requires generator support.

**Comment by waneck** [comment]
Thanks @Simn ! I think this will do. I'll try to play with it for a little and give you feedback in here
