### ISSUE TITLE
Treat various abstract features as pseudo-operators for the sake of consistency

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4275]
I'm thinking that `@:arrayAccess` could become `@:op([])` and `@:resolve` could become `@:op(a.b)`. This is both easier to remember and more concise.

It would also allow us to think about `@:op(())` for calls as discussed with @hughsando and @waneck dicussed.

**Comment by ncannasse** [comment]
you could allow the two, but we should keep old notations for backward compat. Also, `@:op(())` is not valid haxe syntax

**Comment by Simn** [comment]
Yeah of course we're going to keep the current ones.

You are right about the invalid syntax, so it would probably be `@:op(a())`. I would still like to see a "proper" syntax for this because I feel like language features should not be represented by metadata in this way (same for `@:enum abstract`), but I don't have a suggestion yet.

**Comment by deltaluca** [comment]
Perhaps for consistency it should be ````@:op(a[])```` instead?

**Comment by kevinresol** [comment]
`@:op(a[b])` to be even more consistent?

**Comment by Gama11** [comment]
Wouldn't you then also have to include the arguments for the function call operator? That would be a mess.

**Comment by Simn** [comment]
I'm starting to think that this was a bad idea... :/

**Comment by deltaluca** [comment]
Is ````a[b,c,d]```` valid haxe syntax? If so, that could be nice for defining a multidimensional array indexing without using function call syntax.

If so, then we'd need to do it for arrays too to be 'even more consistent' :dancer:

**Comment by nadako** [comment]
Can we just implement `operator[] (key:String):Int` syntax already?

**Comment by Simn** [comment]
Unfortunately class fields are very tricky with regards to completion.

**Comment by nadako** [comment]
i don't understand how completion is related here. could you elaborate pls?

**Comment by Simn** [comment]
If you have a broken AST such as `a.` where you're in the middle of requesting completion, the parser has to resume somehow. It does that by skipping all tokens until the next class field and then continues parsing. Detecting "the next class field" is not trivial because there are already a lot of ways to start a class field, such as all the modifiers and metadata. You can't just skip them all either because you don't want to lose that information.

I'm not saying it's impossible. It wouldn't even be very hard if we could rely on a keyword that can only appear in front of class fields, but we don't have that and we don't want to introduce new keywords at the moment.

**Comment by hughsando** [comment]
What about using "abstract function" as a synonym for "operator"? No new keywords.
ie, a normal class can define (compile time only) operator overloads via:
```
  public abstract function [] (key:String):Int return map.get(key);
```
Although I guess this is more a synonym for "inline" than "abstract"

**Comment by nadako** [comment]
Let's not confuse people by reusing the term "abstract method" for an entirely different thing

**Comment by hughsando** [comment]
just following the macro pattern :)

**Comment by jcward** [comment]
Just popping in to say I'm very excited about resolve for abstract types #3753, whether `@:resolve` or `@:(a.b)` `@:gimmieDotAccess` =)

One relevant point to consider -- it is a bit tricky to search (google, github, grep) for `@:foo`, though `@:op(a.b)` could be even harder.

**Comment by jcward** [comment]
Wait a second, why is resolve read only access. That tempers my excitement. :|

**Comment by kevinresol** [comment]
I would like to see the assignment version of @:resolve as well

**Comment by Simn** [comment]
I think we've done what we wanted to do here, at least I'm not sure what else is still actionable. If there's individual parts that are missing, please open individual issues for them.
