### ISSUE TITLE
Problems with --display file@position@type

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#4279]
If i apply haxe --display D:\projects\fd5-dev-neko\src\Main.hx@141@type for this code:
```
package;
import neko.Lib;

/**
 * @author SlavaRa
 */
class Main 
{
	
	static function main() 
	{
		var a = [1.0, 1.2, 1.4];
		a
	}
}
```
I get an answer:
<type>
Array&lt;Float&gt;
</type>

, but if i apply haxe --display D:\projects\fd5-dev-neko\src\Main.hx@141@type for this code:
```
package;
import neko.Lib;

/**
 * @author SlavaRa
 */
class Main 
{
	
	static function main() 
	{
		var a = [1.0, 1.2, 1.4];
		a.
	}
}
```
I get an answer:
src/Main.hx:14: characters 1-2 : Unexpected }
Invalid commandline class : src.Main should be Main

I think I should get the same answer

**Comment by Simn** [comment]
The parser does not resume in these display modes. We cannot change that either because then you might lose required parts of the AST like in #2991.

We should document that these modes require a sane AST which should be fair enough.
