### ISSUE TITLE
Concise notation for refining abstract union types to concrete types

### ISSUE THREAD

**Issue by knuton** [HaxeFoundation/haxe#4281]
The standard library has an [`EitherType`](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/extern/EitherType.hx) (see also HaxeFoundation/hxnodejs#15) to facilitate working with extern functions that accept either of two types in an argument position. But this is only for calling from Haxe into the outside world.

Coming the other way, calling from the outside world into Haxe, we face the difficulty of not being able to safely pass from arbitrary `EitherType`-style type unions back to concrete types in our Haxe code.

A member of a union type is a member of one of several concrete types, so it would be great if we could use pattern matching to safely transition to the concrete type of a value. For example with a value `v` of some union type `U = A | B | C`, we could write

``` haxe
// v : U
switch (v) {
    case A(vA): // vA : A
    case B(vB): // vB : B
    case C(vC): // vC : C
}
```

This idea derives from [Scala's extractor pattern](http://lampwww.epfl.ch/~emir/written/MatchingObjectsWithPatterns-TR.pdf) where it is even possible to "extract" values from the value being matched on (this part is akin to Haxe's extractors).

The best solution using current language features seems to be using Haxe extractors. Assume concrete types `FruitItem` and `BeverageItem` with union `GroceryItem`:

``` haxe
typedef FruitItem = { tag: ItemTag, name: String, count: Int };
typedef BeverageItem = { tag: ItemTag, name: String, brand: String, liters: Float };
abstract GroceryItem(Dynamic) from FruitItem to FruitItem from BeverageItem to BeverageItem {}
```

With `item : GroceryItem` we can do

``` haxe
switch (item) {
    case Fruit.unapply(_) => Some(fruitItem): // fruitItem : FruitItem
    case Beverage.unapply(_) => Some(beverageItem): // beverageItem : BeverageItem
    case _:
}
```

where `unapply` works by runtime inspection of the underlying value. The benefit is that the unsafe access is encapsulated in one operation which allows us to go back to type safety. See [@Simn's Gist](https://gist.github.com/Simn/321a0214e9fac687adca) for details.

It would be great if it was possible to improve this to read more like

``` haxe
switch (item) {
    case Fruit(fruitItem): // fruitItem : FruitItem
    case Beverage(beverageItem): // beverageItem : BeverageItem
    case _:
}
```

@Simn had some ideas on how this might be done (as well as reservations about whether it should be done). I'll omit them for the moment.

I give a brief summary of our original motivation to allow further backtracking, but the above is a general approach to concisely express operations on data based on some interesting properties. (For example, it subsumes [@nadako's example for operating on JSON data in arbitrary languages](https://github.com/HaxeFoundation/haxe/issues/4264#issuecomment-107720274).)
### Background

We use a variety of compile-to-JS languages in a modular codebase, with [an interface definition language](https://github.com/prezi/spaghetti) serving to allow communication between modules compiled from different source languages, while holding up some type-safety guarantees. We are currently evaluating possibilities for adding variant type support to our cross-module interfaces, where the goal is for any "reasonably advanced" language to be able to work with values of variant types in some form.

The natural expression of variant types in a number of languages, including Haxe, are algebraic data types ("enums" in Haxe). However, the underlying representation of algebraic data types is opaque (this is a feature of ADTs), and in effect representations differ between programming languages -- we can not rely on any one native representation if we want to directly exchange data between modules.

This means that we must find a representation that is general enough to be usable in a variety of languages, while affording (some) safety guarantees by their type systems.

As ultimately we are passing around JavaScript values, tagged objects seem to be the most reasonable general representation. You probably understand what I mean already, but as a quick example, let's consider a shopping list.

``` js
var toBuy = [
  { type: "fruit", name: "Apple", count: 5 },
  { type: "fruit", name: "Orange", count: 3 },
  { type: "beverage", name: "Sprite", brand: "Coca-Cola", liters: 2.5 }
];
```

Let's assume that we only ever need fruits and beverages, so the task is to find a type for shopping list items such that only objects of the two shapes above are permitted and such that we can tell for any value which shape we are facing in order to access its members.

Note that `{ type: "immaterial", name: "Liberty" }` is not permitted.

**Comment by nadako** [comment]
a huge +1 for this

**Comment by nadako** [comment]
a huge +1 for this, my codebase would benefit greatly from this

**Comment by Simn** [comment]
I would like to clarify that this is mostly a syntax sugar issue. I don't mean to disregard it by saying this, but in the end we're looking at these contenders:

```
case Fruit.unapply(_) => Some(fruitItem):
case Fruit(fruitItem):
```

At this point the question for me is if this difference alone is worth introducing a new language feature over. I feel like if we do that it should solve a bit more than saving keystrokes on case expressions. Even more so if this problem might go away should we be able to address #4281 in some way.

Regarding implementation, he main problem with `case Fruit(fruitItem)` is that it is indistinguishable from an enum constructor match as far as the syntax is concerned.

**Comment by nadako** [comment]
> he main problem with case Fruit(fruitItem) is that it is indistinguishable from an enum constructor match as far as the syntax is concerned.

Isn't that the whole point? I'd very much like to see "pluggable" pattern matching for abstracts, and I personally have at least two uses for that (adt-like json data, option/maybe abstract)

**Comment by Simn** [comment]
I don't think that would be a good thing. Right now you can look at `Fruit(fruitItem)` and know that it is an enum match which helps understand code you're not familiar with. If any such match could also be something entirely different it puts additional strain on a developer trying to understand it.

I believe that different concepts should have different syntax unless there's a natural mapping between them. This is not the case here because you're putting a constant value comparison (match against enum index) next to something that breaks up pattern matching to extract values using a class field which is resolved using some convention (metadata or name). This just doesn't mix.

**Comment by nadako** [comment]
Okay, how about doing the reverse - using an proper enum, but having a macro class that somehow controls its actual representation? (there are open questions about enum reflection though)

**Comment by Simn** [comment]
That's more of a discussion for #4281.

**Comment by nadako** [comment]
Well we're already here :-P

**Comment by Simn** [comment]
Oh right, for some reason I thought this was #4264. Disregard!

**Comment by mcheshkov** [comment]
I'm doing it right now for REST API - genericBuild macro, that scans through typedefs and enums, and generate class with two functions - parse and toJSON.

```
enum MyEnum {
	Foo(val:Int);
	Bar(val:Array<{inner:String}>);
}
typedef Message = {
	var id:String;
	var data:MyEnum;
};

typedef MessageTools = JsonTools<Message>;
```

That means more allocations for both enum and JSON, but it is exactly what you said - JSON, tagged with string, with different fields.

**Comment by Simn** [comment]
I was curious to see how much effort it would be to allow a compiler switch which changes the way enums are represented: https://github.com/Simn/haxe/commit/4a348e4461400ef98cfe0212843b88b7439d52b2

This uses structure notation instead of an array, so you have something like this:

```
haxe_macro_Constant.CInt = function(v) { var $x = {name: "CInt", index: 0, params: [v]}; $x.__enum__ = haxe_macro_Constant; $x.toString = $estr; return $x; };
haxe_macro_Binop.OpAdd = {name: "OpAdd", index: 0}
```

I still do the switch on the enum index instead of the name, but that would be an easy change.

I'm not sure if we really have to make this more customizable. There are only so many ways to represent a collection of data in the first place, and it's not very easy to adapt our reflection code without hacking into Type.hx and friends.

**Comment by knuton** [comment]
> I would like to clarify that this is mostly a syntax sugar issue. (...) At this point the question for me is if this difference alone is worth introducing a new language feature over. I feel like if we do that it should solve a bit more than saving keystrokes on case expressions. Even more so if this problem might go away should we be able to address [#4264] in some way.

It is, but syntax matters. At the extreme, it is also already possible to dynamically inspect and cast values in-place, but this is obviously not nice to do. Matching on data should be one mental operation, which is true of one but not the other syntactic form.

If I understand correctly, @nadako has no interest in changing native enums globally, but wants to be able to process "JSON" data of varying shapes. #4264 does not help with that.

> I believe that different concepts should have different syntax unless there's a natural mapping between them. This is not the case here because you're putting a constant value comparison (match against enum index) next to something that breaks up pattern matching to extract values using a class field which is resolved using some convention (metadata or name). This just doesn't mix.

There is a natural mapping in that pattern matching for enums is a special case of the more general idea of inspecting arbitrary properties for matching. This proposal is geared towards using `switch` to facilitate working with abstract types, and after all enums in Haxe are abstract data types. [Emir et al.'s paper](http://lampwww.epfl.ch/~emir/written/MatchingObjectsWithPatterns-TR.pdf) explains how case classes in Scala can be seen as syntactic sugar for extractors.

The next question could be whether this "naturality" is of the "A monad is just a monoid in the category of endofunctors, what's the problem?" kind. I personally don't think so, but it is something to think about.

> I was curious to see how much effort it would be to allow a compiler switch which changes the way enums are represented

I have some comments, but I feel like this is more related to #4264 again :wink: Shall we discuss it there? Can you move the comment?

**Comment by knuton** [comment]
> I'm doing it right now for REST API - genericBuild macro, that scans through typedefs and enums, and generate class with two functions - parse and toJSON.

@mcheshkov Interesting, can you show a more detailed example? I am not sure I understand from the snippet you shared.

**Comment by mcheshkov** [comment]
@knuton [gist](https://gist.github.com/mcheshkov/1d1e6f76486f86285720) It's dirty, not well tested, and non-customizable. Can handle structs, enums, abstracts, but not every case Haxe itself can handle. For JSON-representable types toJSON is no-op, parse just validates types. For other types it's actual conversion.

**Comment by nadako** [comment]
To me the conversion involving allocation is a concern unforunately, that's why I'd like to see custom representation for different enums.

**Comment by Simn** [comment]
Can't move comments. Sorry, I don't know why I'm having so much trouble telling these two issues apart.

**Comment by Simn** [comment]
Re natural mapping: Usually you match on a value the same way you create it. We do not create instances using `Class(arguments)` so we shouldn't match on it like that either. The only consistent solution would be to match on `new Class(arguments)` but that looks really weird as a case pattern.

**Comment by nadako** [comment]
Now when we have macro @:from functions, we actually can create those abstracts with Ctor(args) syntax :-P

**Comment by knuton** [comment]
@mcheshkov Wow, that's really extensive!

Unfortunately the manual conversion process doesn't match our scenario well either. Ideally, we could treat the data as first-class, not something to be inflated into first-class values. It would be best to bypass conversion in both developers' minds and runtime.

I just experimented with "classic" `@:from` a little bit to see how much of the conversion process could be made implicit. You can go quite far but not work directly with `switch` expressions. I'll document it here as another data point.

The big downside of this approach would be that it still involves conversion at runtime.

```haxe
/* Representing ADT as native enums */
enum FooEnum {
    Bar;
    Qux(num: Int);
}

/* Representing ADT as structured (product) and abstract (union) types */
typedef BarType = { tag: String };
typedef QuxType = { tag: String, num: Int };

abstract FooUnion(Dynamic) from BarType from QuxType {
    /* Convert from and to enum as needed. */
    @:from
    public static function fromEnum(f: FooEnum) {
        return switch (f) {
            case Bar: ({ tag: "Bar" } : FooUnion);
            case Qux(n): ({ tag: "Qux", num: n } : FooUnion);
        };
    }
    @:to
    public static function toEnum(b: Dynamic): FooEnum {
        return (if (b.tag == "Bar") Bar else Qux(b.num));
    }
}

class Test {
    static function mat(e: FooEnum) {
        switch (e) {
            case Bar: trace("Bar");
            case Qux(n): trace("Qux", n);
        }
    }
    static function main() {
        var foo : FooUnion = Qux(5);
        mat(foo); // this works, prints "Qux,5"
        foo.match(Bar); // this compiles appropriately
        // but the following does not compile,
        // `foo` is not converted to FooEnum
        switch (foo) {
            case Bar: trace("Bar");
            case Qux(n): trace("Qux", n);
        }
    }
}
```

It seems that maybe the type of an expression being switched on is not determined from what it is being matched against. (No idea whether that would be sensible.)

**Comment by nadako** [comment]
The switch would work if you specify enum type explicitly (i.e. `switch (foo : FooEnum) {...}`), but that involves runtime conversion again.

**Comment by Simn** [comment]
If you run-time-wrap something you'll have to run-time-unwrap it.

**Comment by knuton** [comment]
> Re natural mapping: Usually you match on a value the same way you create it. We do not create instances using `Class(arguments)` so we shouldn't match on it like that either. The only consistent solution would be to match on `new Class(arguments)` but that looks really weird as a case pattern.

I'm going to use some math talk to respond because I hope it makes clear what the abstraction is. Sorry if it doesn't!

Constructors of an enum type *E* are injective functions *C: T_1 x ... x T_n --> E*, and so their inverses are partial functions *E -/-> T_1 x ... x T_n* or total functions with an added "nothing" element, *E --> Maybe(T_1 x ... x T_n)*.

For example with

```haxe
enum Foo {
  Bar;
  Qux(num: Int);
}
```

we have `Qux : Int -> Foo` and its inverse `unQux: Foo -> Option<Int>`, and it holds that `unQux(Qux(5)) == Some(5)`.

This pattern is more general: Whenever you have a pair of functions *F: X --> T* and *unF: T --> X* for which *unF(F(x)) = x* for any *x* in *X*, you can pair them up to inject into and extract from *T*.

Enums/ADTs are just one special case of this, and I think that makes the mapping undeniably natural.

So [in Scala the decision was made to use the same syntax for the general pattern](http://lampwww.epfl.ch/~emir/written/MatchingObjectsWithPatterns-TR.pdf), not just ADTs. The reason the same syntax is also used for constructing and destructing classes in the special case of "case classes", is just because they adhere to the same pattern.

Of course it may be that you think that this special syntax SHOULD be special cased and used exclusively for enums. Then there might be another or no special syntax (as is the case now) for the more general pattern.

**Comment by knuton** [comment]
> If you run-time-wrap something you'll have to run-time-unwrap it.

Ideally there would be neither, my example is merely a makeshift attempt to arrive at a pleasant syntax for extracting from abstract union types.

**Comment by back2dos** [comment]
Like so? https://github.com/haxetink/tink_lang#type-switch

**Comment by nadako** [comment]
> If you run-time-wrap something you'll have to run-time-unwrap it.

We can compile-time wrap those now with new macro @:from functions :)

**Comment by back2dos** [comment]
Would that not still result in a runtime wrap?

**Comment by knuton** [comment]
> Like so? https://github.com/haxetink/tink_lang#type-switch

Aha! That's very interesting. We can't check for the type like this but would have to check for a tag, but there could be a syntax for that and it *could* be done as a macro.

Which brings me to ask: @Simn do you see any point to [this general kind of pattern matching](https://github.com/HaxeFoundation/haxe/issues/4281#issuecomment-110809932) at all? If the general form would not look like enum patterns but have separate syntax, could that make it more appealing?

**Comment by Simn** [comment]
Math aside it really comes down to having a construction-deconstruction pair. We do not have Scala's value classes and our normal classes have different semantics. I don't see what exactly you would like to generalize with regards to pattern matching.

**Comment by ousado** [comment]
I have to admit I didn't read everything in this thread, so this might not even be a solution, but I thought I'd throw this in anyway, just for the record: A combination of a plain generic type and a GADT allows a type-safe switch on a tag field to safely identify the (generic) type of another field, and to access it as such, as follows:

( see http://try.haxe.org/#2b017 )
```haxe

// using plain enum
enum Tag<T> {
    a:Tag<Int>;
    b:Tag<String>;
}

// also works with @:enum abstract
@:enum
abstract Tag2<T>(Int) {
    var a2:Tag2<Int> = 1;
    var b2:Tag2<String> = 2;
}


// class version
@:publicFields
class Tagged<T,U:Tag<T>> {
    var tag:U;
    var v:T;
    
    function new(v:T,tag:U){
        this.tag = tag;
        this.v   = v;
    }
}

typedef T1<T> = Tagged<T,Tag<T>>;

// anon version
typedef Tagged2<T> = {
    tag : Tag2<T>,
    v   : T
}

class Test {
    
    static function tigtag<T>(t:T1<T>){
        switch t.tag {
        	case a:
                $type(t.v);
                var i:Int = t.v;
                trace(t.v);
            case b:
                $type(t.v);
                var s:String = t.v;
                trace(t.v);
        }
    }
    
    static function tigtag2<T>(t:Tagged2<T>){
        switch t.tag {
        	case a2:
                $type(t.v);
                var i:Int = t.v;
                trace(t.v);
            case b2:
                $type(t.v);
                var s:String = t.v;
                trace(t.v);
        }
    }
    
    static function main() {
        trace("Haxe is great!");
        tigtag( new Tagged(123,a) );
        tigtag( new Tagged("stttringgg..",b) );
        
        tigtag2( {v:123,tag:a2} );
        tigtag2( {v:"string",tag:b2} );
        
        // wrong usage:
        // tigtag2( {v:1.2,tag:b2} ); // Tag2<String> should be Tag2<Float>
    }
}
```

**Comment by ousado** [comment]
Another version, same conceptual approach - but this time without a container object. Turns out the fruit/beverage example can be directly encoded in Haxe, as is:
http://try.haxe.org/#1A31d
```haxe
typedef XTag = TagE<Dynamic>; // Dynamic is required to "cancel" the recursive type definition
typedef DTag = Tag<Dynamic>;  // kind of a defeat, but OK..

@:enum abstract TagE<T>(Int) {
    var fruit:   TagE<{tag:XTag,name:String,count:Int}>                 = 1;
    var beverage:TagE<{tag:XTag,name:String,brand:String,liters:Float}> = 2;
}

typedef Tag<T> = { tag:TagE<T> };

class Test {
    
    static var data : Array<Dynamic> = 
    [
	    { tag: fruit,    name: "Apple",  count: 5 },
	    { tag: fruit,    name: "Orange", count: 3 },
	    { tag: beverage, name: "Sprite", brand: "Coca-Cola", liters: 2.5 }
    ];
    
    static function untag<T:Tag<T>>(t:T) switch t.tag {
        case fruit:
            trace('${t.count} ${t.name}(s)');
        case beverage:
            trace('${t.liters} liters of ${t.name}');
    }
    
    static function main() for (item in data) untag( (item : DTag ) );
}
```

**Comment by back2dos** [comment]
@knuton Would it not be easier to demand that all types in a union type are natively existing types (i.e. either primitives or JavaScript classes)?

I must admit I am a little confused by this:

```
switch (item) {
    case Fruit(fruitItem): // fruitItem : FruitItem
    case Beverage(beverageItem): // beverageItem : BeverageItem
    case _:
}
```

What is `Fruit`? Where is it defined? Is it a class that defines a static `unapply` method? If so, why isn't `FruitItem` a class in the first place, and you can just use `instanceof`/`Std.is` to make the distinction, which also spares you the trouble of writing a whole lot of those `unapply` functions?

**Comment by Simn** [comment]
@ousado's example inspired me to write a small macro which creates a typedef per enum constructor and automatically adds the "tag" field: https://gist.github.com/Simn/83a992ab9e970290a34d

I really underestimated the power of GADT on enum abstracts!

**Comment by Simn** [comment]
Also if you inline `untag` and compile with `-D analyzer` the optimization is quite nice:

```js
// Generated by Haxe
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("" + 5 + " " + "Apple" + "(s)");
	console.log("" + 3 + " " + "Orange" + "(s)");
	console.log("" + 2.5 + " liters of " + "Sprite");
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

**Comment by nadako** [comment]
This is very nice, however it would be great to use them inline, without writing a parametrized function somehow, i.e.

```haxe
var v = getTag(); // typed as ????????
switch (v.tag) {
    case fruit:
        trace(v.name);
    case beverage:
        trace(v.liters);
}
```

**Comment by Simn** [comment]
I'll get back to you on that once #4344 has been resolved. ;)

**Comment by knuton** [comment]
In reply to @back2dos:

> Would it not be easier to demand that all types in a union type are natively existing types (i.e. either primitives or JavaScript classes)?

What do you mean when you say JavaScript classes? Haxe classes?

Yes, it would be easier internal to Haxe to make such demands, but this request is motivated by language interoperability needs. We want to accept incoming data that may not originate from a Haxe module, so Haxe classes are not an option.

> What is `Fruit`? Where is it defined?

It is defined something like in this example: https://gist.github.com/Simn/321a0214e9fac687adca

> Is it a class that defines a static `unapply` method?

It is, but only for the purpose of bundling together some functions under a common name. It is not a class with interesting instances.

> If so, why isn't `FruitItem` a class in the first place, and you can just use `instanceof`/`Std.is` to make the distinction, which also spares you the trouble of writing a whole lot of those `unapply` functions?

We want to accept data from possibly non-Haxe modules. We can describe this data with a typedef, but it may not be implemented as a Haxe class. `instanceof`/`Std.is` only make sense for entities originating from within Haxe, I believe.

Does that explanation make sense?

**Comment by knuton** [comment]
@ousado @Simn The GADT approach is really cool!

I am not very familiar with GADTs (in any language), but my questions are similar to @nadako's:
- How much of this hinges on the parametric function?
- Can we give the union some "natural"/user-friendly (non-parametric) type? As I understand `DTag` or `AnyTag` in #4344 is meant to be that?

**Comment by Simn** [comment]
I don't think it makes much sense without type parameters. You could use AnyType but that would not specialize in the case expressions.

**Comment by ousado** [comment]
@knuton 
> How much of this hinges on the parametric function?

All of it, really. You need the type parameter _constraint_ to allow each out of the set of the possible types for `T`.
  1. you define that `{ tag:TagE<T> }` is a structural (sub-) type every given `T` adheres to
  2. due to the recursive definition for `T` you also define that `T` _is_ the type of the `tag` field's type parameter
  3. by virtue of binding one specific concrete type (parameter) to each constructor and hence runtime-determinable value of `TagE`, you allow then, within the scope of a given `case` for that constructor, to finally determine the concrete type for `T`.

That being said, the context or scope in which you specify the relationship between `T` and the type parameter of its `tag` field doesn't have to be a function. You can also parameterize a class (or abstract) in the same way:
```haxe
class TagCtx<T:Tag<T>> { /* T is usable without further qualifications here */ }
```
.. and simply use `T` in methods of that type. I think in terms of user-friendliness that's quite good already, since you don't have to deal with any casts based on the outcome of Std.is or similar reflection-based mechanisms here.

> As I understand DTag or AnyTag in #4344 is meant to be that?

Yes, it should be sufficient as a container type - but I think it won't be sufficient to capture the "multiple identities" that are required to unlock the GADT behavior.

**Comment by knuton** [comment]
@ousado Thanks for explaining!

> I think in terms of user-friendliness that's quite good already, since you don't have to deal with any casts based on the outcome of Std.is or similar reflection-based mechanisms here.

It's good for advanced users, but I don't think it is something I'd want to unleash as a recurring pattern in a large codebase. :wink: You want to be able to just assign a value to a variable with a straightforward type, and then still be free to switch on it. I guess in principle one could parametrize all types for GADTs using macros, but this sounds like a can of worms.

I really like this approach, but I feel like in the current context it is not a practical solution.

**Comment by back2dos** [comment]
@knuton I'm sorry if this is a stupid question, but are you aware that JavaScript has well defined class semantics? Semantics that both Haxe and TypeScript use (and in fact all major compile-to-js languages). What's wrong with relying on those and thus `instanceof` (as provided by `Std.is` in Haxe)?

**Comment by knuton** [comment]
@back2dos It's not, but I don't find class hierarchies to be a good encoding of variant types. Specifically I see two problems:

1. Maybe all compile-to-JS languages with class constructs compile them to compatible JavaScript "classes", but we are interested in expressing variants. Some (functional) languages don't have classes. We really just want to exchange data.
2. Type refinement from superclasses is usually awkward and manual: http://try.haxe.org/#E81cc (Is there a better way to do this in Haxe than casting after the check?)

**Comment by back2dos** [comment]
@knuton Well, I'd say awkwardness lies a bit in the eye of the beholder :D

Before this goes in all directions, could you please clarify, what exactly you are after? It seems a number of issues are intermingled in this thread, and I am not sure having a single solution is the best idea.

Your actual scenario is that in spaghetti, you want to define a variant type and when compiling to Haxe you want to convert that into something that is not quite as awkward, right?

First of all, if the syntax is to be anything like what you propose, that precludes that all the variants of that type be *named*. That is already a restriction to be aware of, because you can hardly find a nice syntax for `String->Int | { flag: Bool }` let alone for `Array<Int> | Array<String>`.

If each variant is named, e.g. the type is `A | B | C | D` then this is how one might represent it:

```
abstract Variant_83(Dynamic) {
   public function get():VariantValue_83 {
       //let spaghetti generate whatever you want here to construct 
       //the right enum on based whatever type encoding spaghetti uses
   }
}

enum VariantValue_83 {
   A(v:A);
   B(v:B);
   C(v:C);
   D(v:D);
}
```

And basically you can now write:

```
switch theValue.get() {
  case A(a):
  case B(b):
  case C(c):
  case D(d):
}
```

Would that just do the trick?

I'm also curious to know how you're tackling this in TypeScript. If you have a good solution for it, then I'm sure it will be enlightening!

**Comment by knuton** [comment]
Thanks for breaking down the problem! You capture the scenario well.

> First of all, if the syntax is to be anything like what you propose, that precludes that all the variants of that type be *named*.

I am not sure I understand this point. Are you saying that the underlying types can not be named and then combined in a union (via `abstract`)? Why not?

The actual types I have in mind have some common structure, basically they would all be `X <: { tag: String }` or something similar with a better type for `tag`. The different `X` may be named or not, I don't think it matters in principal as the union type is automatically generated. (It may matter for comprehensibility of compiler errors.)

So let's say the underlying types are named. The solution you propose is extremely close to something worth trying. It is very similar to [what I sketched above](https://github.com/HaxeFoundation/haxe/issues/4281#issuecomment-110791045). Is it maybe even close enough? I'll think about it.

Can I ask some naive questions about type inference for switch-expressions? How are the individual sub-expressions typed and how the composite? Would it be possible to unify the types of all cases with the type of the expression being switched on? Might it not be possible to use [the selection algorithm](http://haxe.org/manual/types-abstract-implicit-casts.html) to convert from the abstract union to the "companion" enum implicitly instead of calling `get` (or `toEnum` in my example).

TypeScript has had untagged union types for a while now. There is [a maintainer-sanctioned proposal](https://github.com/Microsoft/TypeScript/issues/1003) which would complete the picture to refine unions to concrete types by inspecting a tag (so, introduce new forms of type guards).

**Comment by Simn** [comment]
As with the related issue, we reached no conclusion here unfortunately.

**Comment by ciscoheat** [comment]
I just completed something similar to what was asked in the first post. It works well, but only on type identification of course, not with the full flexibility of Typescript. Identifying anonymous structures is a problem, since they don't have a defined type, so reflection is needed there. Anyway, if you're interested: [Uniontypes](https://github.com/ciscoheat/uniontypes)!

Feedback appreciated!
