### ISSUE TITLE
Proper syntax for enum abstracts

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4282]
They have their own set of semantics so they should have their own syntax instead of some metadata. Can we please use `enum abstract` for this?

**Comment by nadako** [comment]
Yes please

**Comment by Gama11** [comment]
`enum abstract` or `abstract enum`? :)

**Comment by nadako** [comment]
`enum abstract`, because it's an abstract in the first place. To me it's somewhat similar to `private class`

**Comment by back2dos** [comment]
While we're at it, what about supporting type parameters?

Here's a sketch of how file descriptors on nodejs could be made type safe: http://try.haxe.org/#78689

But we'd have to have the possibility to give an abstract enum constructor a type, which is currently not allowed, e.g.:

```
@:enum abstract FileAccess<T>(String) to String {
    var Read:FileAccess<Read> = "r";
    var Write:FileAccess<Write> = "w";
    var Append:FileAccess<Write>  = "a";
    var Readwrite:FileAccess<Readwrite>  = "rw";
    @:to static function dropWrite(fa:FileAccess<Readwrite>):FileAccess<Write> return cast fa;
    @:to static function dropRead(fa:FileAccess<Readwrite>):FileAccess<Read> return cast fa;
    @:from static function ofString() return (cast this : FileAccess<Readwrite>);//because we can't tell
}
```

That's about the only use case I have, but it strikes me as rather useful, although I probably have no idea of what issues it would create :D

**Comment by nadako** [comment]
enum abstracts support type params exactly that since 3.2 (btw great idea about file descriptor abstract)

**Comment by back2dos** [comment]
Oh, good to hear! Last time I tried to add this to the externs it didn't work.

**Comment by Simn** [comment]
Yes/no/maybe?

**Comment by Simn** [comment]
After two years, answers automatically default to "yes".
