### ISSUE TITLE
Constraint check failure for haxe.ds.ObjectMap.K ?

### ISSUE THREAD

**Issue by dimumurray** [HaxeFoundation/haxe#4283]
Ever since upgrading to 3.2.0 I've been having issues with generic types and Object Maps. I know there have been changes to the language but they shouldn't affect my use case. 

You can check out the issue here:
http://try.haxe.org/#8Ac38

**Comment by Simn** [comment]
If that worked before it was a bug. `T` could be anything if unconstrained so you would end up with, say, an Int key for it. Constrain the type parameter to `{}` to make it work.

**Comment by mcheshkov** [comment]
You should constrain `Graph` type param so it fit to `ObjectMap`: `class Graph<T : {}> {`

**Comment by mcheshkov** [comment]
oh wow

**Comment by dimumurray** [comment]
Thanks @mcheshkov & @Simn.
