### ISSUE TITLE
Postfix `!` operator

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4284]
How bad would it be to add support for that? Given that the representation for it already exists, it would only require being added in the parser and typer, similarly to `=>` unless defined on an abstract or processed by a macro.

I think I could use this to prove a point about the viability of null safety. Also it seems like adding it should neither be hard nor detrimental.

**Comment by nadako** [comment]
I guess we could add it without breaking stuff as `EUnop(OpNeg, true, _)`

**Comment by Simn** [comment]
I can't think of any parser related problems with this. And yes it shouldn't break anything because the AST structure already supports it.

**Comment by nadako** [comment]
I would use it right away with my null-safety abstracts :-P

**Comment by back2dos** [comment]
That was the idea ;)
