### ISSUE TITLE
Java fails compilation with interface Name<Const>

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#4286]
I haven't been able to make a sscce of this, but it should be simple enough to reproduce the error:

1. Clone the https://github.com/ciscoheat/buddy repo
1. Compile with `haxe buddy.java.hxml`

Should get this result:
```
src\buddy\tests\AllTests.java:6: error: cannot find symbol
public class AllTests extends haxe.lang.HxObject implements buddy.Buddy<haxe.root.Expr>
                                                                                 ^
  symbol:   class Expr
  location: package haxe.root
1 error
9 warnings
Compilation error
Native compilation failed
Error: Build failed
```

The problem seems to be in `src/buddy/Buddy.hx`:

```haxe
@:autoBuild(buddy.GenerateMain.withSuites()) interface Buddy<Const> {}
```

Which is used in `buddy/tests/AllTests.hx`.

**Comment by waneck** [comment]
Is this a regression?

**Comment by ciscoheat** [comment]
Sorry, were you talking to me? :) I haven't used this syntax before for Buddy, so I don't know.

**Comment by waneck** [comment]
Okay, this isn't a regression - it seems that `SomeType<Const>` when used will generate some very weird types on the Haxe compiler. e.g. `SomeType<10>` generates as `SomeType<I10>` - I10 being a class that doesn't actually exist
