### ISSUE TITLE
allow enum values as constants for function args

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4287]
as discussed on irc, we could probably allow enum values as function argument default values:
- constructors without arguments
- constructors with constant arguments (numeric, string, other enum constructors)

**Comment by Simn** [comment]
I would also like to have this, but it is going to require AST changes. I'm also concerned about the Flash target because of the fancy way we deal with default values there.

**Comment by back2dos** [comment]
@Simn: What's wrong with the pass-null-and-assign-the-default-in-the-function-body-approach?  That's how tink_lang already implements it already: https://github.com/haxetink/tink_lang#complex-default-arguments

So I'm a little puzzled by the issues you raise.

**Comment by Simn** [comment]
I see nothing wrong with it, but IIRC that's not what we do on Flash at the moment.

**Comment by nadako** [comment]
@ncannasse please approve/disapprove this. I believe The AST changes mentioned by Simon were `haxe.macro.Type.TFunc.args` change TConstant->TypedExpr

**Comment by ncannasse** [comment]
We can change that for Haxe 4.x

**Comment by Simn** [comment]
This requires changing either `tconstant` or `tf_args`. Both are not small changes.

**Comment by ncannasse** [comment]
I think it's possible to change tf_args without much trouble. Most operations on it (apart from codegen) should already ignore the value anyway so will not result in compilation errors.

**Comment by Simn** [comment]
> constructors with constant arguments (numeric, string, other enum constructors)

Do we really want to allow this? It bothers me that these aren't equal values as far as `==` is concerned...

**Comment by Simn** [comment]
I have changed the representation in the linked commit. It passes on all targets except cppia. @hughsando 

It doesn't support enum values yet because I expect that to cause more issues on some targets. Will look into it soon.

**Comment by Simn** [comment]
It's not as bad as expected. These targets need to be updated:

* [ ] hl
* [ ] as3
* [x] php
* [ ] cpp

I'm surprised that this works on flash, but I'm not gonna complain.

**Comment by back2dos** [comment]
>> constructors with constant arguments (numeric, string, other enum constructors)
>
> Do we really want to allow this? It bothers me that these aren't equal values as far as `==` is concerned...

Perhaps they could be promoted to static vars?

**Comment by RealyUniqueName** [comment]
Fixed php

**Comment by Simn** [comment]
Closing this in favor of #7439.

**Comment by Simn** [comment]
#7439 has been merged, but it doesn't allow `Some(1)` as default value at the moment. @ncannasse: Do we want to allow this or not? I don't really have a strong opinion on this.

**Comment by hughsando** [comment]
hxcpp will need some changes if the default value required a gc alloc

**Comment by ncannasse** [comment]
Let's forbid it for now, as doing it right would maybe require a lazy allocation.
