### ISSUE TITLE
Need a cancellable Socket select function

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#4288]
The activities haxelib that we are working on requires a cancellable version of Socket.select().

We have implemented a class called sys.net.SocketSelector which provides a cancellable select function, and provided C++, Java, and neko implementations thereof (SocketSelector only has value on multi-threaded platforms, as single-threaded platforms can't run a thread concurrently with Socket.select that would cancel the select, so there's no point to have a SocketSelector with cancellable select on single threaded platforms); would the haxe foundation be interested in that?  Or would you prefer to take the various pull requests surrounding the proposed EPoll function, and adapt cancellability to that?

**Comment by ncannasse** [comment]
Could you detail what you mean by "cancelable select" ? select() already has a timeout optional parameter so you can tell how much time is spent in the method

**Comment by bjitivo** [comment]
If I am running a select() in one thread, I would like to be able to cancel that select from another thread, so that the select() call immediately returns in the first thread.  The reason is that the activities haxelib under development can only efficiently be implemented with a cancellable select on multithreaded platforms (otherwise, every activity that has a timer scheduled or is watching a socket for events will have to run its own select call, which then implies that every activity will have to be paired with a native thread, which is much less efficient than the alternative, which is that only one or a small set of threads run select(), but in a cancellable fashion so that if another activity run in a different thread wants to add a timer or watch a socket, it can notify the main thread(s) running select() to wake up and add the new timer or socket to the select list and re-enter select).

See the java.nio.channels.Selector class for an example of one way in which a cancellable select has been implemented in another language.

**Comment by bjitivo** [comment]
By the way, an easy way to implement a cancellable select is to have a 'hidden' socketpair that the cancellable select always adds to its fd lists, and then make the 'cancel select' function be one that just writes a byte into the 'cancel' socket.  I alreadyhave this implemented and working fine in the local version of a SocketSelector() haxe class I have created.  The Java version uses java.nio.channels.Selector instead in its cancellable select implementation.  neko uses the same functionaltiy as the C++ implementation.  I believe that C++, neko, and Java are the only multithreaded haxe targets so that covers everything.

**Comment by ncannasse** [comment]
@bjitivo can I conclude that we can close the issue ? :)

Another solution is to have a single native thread that does the select() for all the FDs and then send events to other activities when data is available. But that requires more socket management since the data is not read immediately, unless you make all sockets nonblocking and then have some buffering done in this thread as well.

**Comment by bjitivo** [comment]
The solution you describe in your last message is exactly what I'm trying to enable.  In order to allow one socket to do the select() for all FDs, that select has to be interruptible so that if a thread wants to add a new socket to the list of sockets to watch for events, it can do so immediately, rather than waiting an indefinite time for the select in progress to complete.

**Comment by ncannasse** [comment]
could you not do a select with a 50ms timeout ?

**Comment by bjitivo** [comment]
Sure, that could be done.  But interruptible select is better because it does not have an unnecessary 50 ms latency and it doesn't waste CPU time calling select 20 times a second unnecessarily, which is expecially bad in haxe where numerous arrays are spewed on every call to Socket.select().

**Comment by ncannasse** [comment]
I understand, but how would you make select() interrupt'able in a cross platform manner ?

**Comment by bjitivo** [comment]
The underlying select implementation is per-platform anyway.  The only three multithreaded backends for haxe that I am aware of (correct me if I am wrong please) are C++, Java, and Neko.  C++ and neko can share the same implementation, which is to take the existing C++ code implementing select and add in a socketpair under the covers as I have already described above.  The Java implementation can use the Selector class that Java already provides.

As I mentioned, I already have a SocketSelector class created and working for all of these platforms.  This issue is just to ask whether or not you a) consider a cancellable select to be a worthwhile feature to add to the haxe standard library given the description I've given as my reason for wanting one, and b) if you would want a solution like the one I have already implemented, or would prefer to do something like take the EPoll pull request that's already been submitted and add the cancellability into that (which could be done because the EPoll pull request already includes a persistent object which manages the poll, and the socketpair could be added in to that; the existing haxe Socket class cannot support cancellability using socketpair because it's a stateless static function call that cannot hide a socketpair).

**Comment by ncannasse** [comment]
Given the way it works, I don't see any necessity of adding this to stdlib, given it can already be fully implemented using current API, by creating a socket pair and adding it to select() or poll list.

**Comment by bjitivo** [comment]
Can you point me to the haxe socketpair implementation?  I don't find it anywhere ...

**Comment by ncannasse** [comment]
I thought you would connect one socket to another on 127.0.0.1 ? Is there another way to do that ?

**Comment by bjitivo** [comment]
Doing it that way leaves a socket exposed listening on 127.0.0.1, which is weird.  Of course you could close it after connecting to it, but ... still weird.

I prefer to use the libc socketpair() function which makes a private pair of file descriptors.  My implementation uses this in the hxcpp standard library C++ code.  I think this is the best way.

An alternative I suppose could be exposing socketpair() in haxe std library, and then using that in my implementation.  Do you prefer that?  Note that socketpair() would be a hxcpp only thing I suspect.

**Comment by bjitivo** [comment]
I mean stop listening to the socket on 127.0.0.1, not close.  But I think you get the point.

**Comment by ncannasse** [comment]
I think it's better to expose socketpair(), there might be other useful cases for it and it's often better to have the high level logic in Haxe code instead of C++ (makes it more crossplatform)

**Comment by Simn** [comment]
Do we have to take any action for 3.3 here?

**Comment by ncannasse** [comment]
@bjitivo just to resume my opinion : I'm fine with you proposing a PR which adds socketpair() API for C++/Neko, you can then inject this pair into your own select() and handle it as you wish. Modifying current select() to automatically having such a pair is not a good idea.

I'll close for now, don't hesitate if you have more questions.
