### ISSUE TITLE
Standardize @:hxGen/@:nativeGen across all targets

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4289]
Waiting for @waneck input.

**Comment by waneck** [comment]
On C# and Java, `@:hxGen` and `@:nativeGen` are type attributes that determine if the generator should see it as a type that was generated by Haxe or a "native" target type. By default, all non-extern types are `@:hxGen` and all extern types are `@:nativeGen`. This can be overridden, though.
The obvious case is when you want to override an extern type to treat the type as if it were generated by Haxe. `--macro exclude` does that, for example, by adding `@:hxGen` to the excluded types.

But there is also a non-obvious case on C# and Java, which is when you want to generate a type as if it were native. On C#/Java this will not add some reflection helpers, constructor magic, and on C# it will treat type parameters differently. This comes with a price though, which is that only a subset of Haxe code will be compatible with it (for example, on C# the type parameters will be much more strict than Haxe usually is).

I think this concept can to a certain extent be extended to other targets. For example, on the case of hxcpp, this can also allow for better interop with native C++ classes/structs. This may influence some JavaScript code also, I think

**Comment by Simn** [comment]
I have opened this issue but there's not really anything actionable here so I'm going to close it again. The main point is that we can use these metadata to distinguish Haxe and native classes as @waneck has described. This might be relevant in some cases, such as externs in #3229.

**Comment by onehundredfeet** [comment]
What is best practices for Java?  I'm trying to bridge from Haxe -> JNI and it's a bit unclear atm how to do it.
