### ISSUE TITLE
Finish static analyzer

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4291]
The static analyzer requires some more work to deal with edge cases and prepare for null-safety.

**Comment by markknol** [comment]
I found a static analyzer example that doesn't give expected results http://try.haxe.org/#0F55c

**Comment by Simn** [comment]
I'm pretty sure that's directly related to `trace` because trace...

**Comment by markknol** [comment]
You are right, this does work. http://try.haxe.org/#72Ee7 Only not sure if this is better.
