### ISSUE TITLE
Duplicate type parameters

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4293]
I just noticed that we allow this:

```
class Main<T, T> {
	static function main() { }
}
```

I don't think that makes any sense. It was nice for the Const special case but we've got `@:const` for that now.

**Comment by clemos** [comment]
Is there an easier way to have `Const,Const`  in 3.3 ?
https://github.com/clemos/haxe-js-kit/commit/e3f51435a07663e4cabf601e8ca2bb3f69a4e4c9
