### ISSUE TITLE
Which debugger version to use?

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#4296]
I'm playing with HXCPP and the debugger, and I'm wondering what is the most up to date version as of now. I can see two haxelibs both by Hugh, there's also the hxcpp-debugger repo from the Haxe Foundation and the debugger, from TiVo.

Which one should I be using?

We should probably add that to the target-specific docs.

**Comment by Simn** [comment]
@bjitivo: We might want to take down TiVo/debugger to avoid some confusion. You should have full access to https://github.com/HaxeFoundation/hxcpp-debugger. Let me know if that's not working.

**Comment by Simn** [comment]
Anyway, this is not exactly a Haxe issue.

**Comment by fullofcaffeine** [comment]
@Simn Thank you, I'll use the one from the Haxe foundation.
