### ISSUE TITLE
Issues with the Python writer

### ISSUE THREAD

**Issue by zopyx** [HaxeFoundation/haxe#4299]
I tried Haxe 3.2 and found at least two issues:

- the writer must use whitespaces instead of tabs for Python indentation. Tabs are considered by Python developers as evil

- the generated Python code should specify the coding of the source files. Otherwise non-ascii literals with in the .hx file will cause a Python interpreter failure in Python 2.7 if the coding preamble is not specified.

**Comment by Simn** [comment]
@frabbit: Any opinions?

**Comment by nadako** [comment]
About tabs, yeah, pythonistas actuall use 4-space instead.
About encoding, we only support python3 which IIRC has utf-8 by default so there's no need for `-*- coding: utf-8 -*-` header.

**Comment by Simn** [comment]
I have replaced all occurrences of \t with four spaces now. I'm not sure if there's some inline python code that requires an update. Leaving that to @frabbit.

**Comment by frabbit** [comment]
I can't find any inline python code that uses tabs, feel free to open a separate issue if you encounter tabs somewhere.

**Comment by frabbit** [comment]
i found one ;)
