### ISSUE TITLE
Remove IsValueType check in Null C# constructor

### ISSUE THREAD

**Issue by dogles** [HaxeFoundation/haxe#4301]
Currently, the C# constructor for Null does the following check:
```
if (!haxe.lang.NullMetadata<T>.IsValueType && System.Object.ReferenceEquals(v, default(T)))
```

This is slow on some platforms (namely Unity's IL2CPP), because the compiler isn't smart enough to determine that NullMetadata<T>.IsValueType can be determined at compile-time, and ends up doing a hash lookup to find the proper generic instance. The other solution:

```
if (!typeof(T).IsValueType && System.Object.ReferenceEquals(v, default(T)))
```

Has non-trivial overhead in Mono. It seems to me that we could remove this check altogether and move it to the callsites for non-ValueTypes instead, e.g.

```
new Null(foo, foo != null)
```

I believe we have the information at compile-time for the callsite to determine whether it is a ValueType or not.

**Comment by waneck** [comment]
@dogles, can you see if the referenced commit helped - performance-wise?

**Comment by nadako** [comment]
TODO: remove `NullMetadata` after confirmation.

**Comment by dogles** [comment]
I think you can remove the @:functionCode entirely as well

**Comment by waneck** [comment]
Sadly, I can't. Because the generator will consider any field access to `haxe.lang.Null` to actually be an access to its `value` variable ;)

Anyway, if this helps, I can clean it up later

**Comment by dogles** [comment]
Ah, right :) 

Testing now

**Comment by dogles** [comment]
This seems to be the fastest solution. The Null constructor doesn't even appear in my profile tests anymore. :)
