### ISSUE TITLE
C# unable to compile msignal library

### ISSUE THREAD

**Issue by luboslenco** [HaxeFoundation/haxe#4302]
Hi,

I am trying to use [msignal](https://github.com/massiveinteractive/msignal) library in C# target but I am unable to compile generated code.

The error reported is as follows:
Sources/src/msignal/Signal.cs(22,245): error CS1525: Unexpected symbol `)’

__temp_me220.slots = ((global::msignal.SlotList<TSlot_c, TListener_c>) (global::msignal.SlotList<object, object>.__hx_cast<TSlot_c, TListener_c>(((global::msignal.SlotList) (global::msignal.SlotList<object, object>.NIL) ))) );

However the parenthesis are correct of course. I was told there is no fancy stuff in msignal(no macros) and it should work. Also, after switching to [hxsignal](https://github.com/zweimal/HxSignal) everything works fine.

Can anyone reproduce this issue? Let me know if I can provide more details.

**Comment by back2dos** [comment]
On Tue, Jun 9, 2015 at 11:22 AM, Lubos Lenco <notifications@github.com>
wrote:

> Hi,
>
> I am trying to use msignal <https://github.com/massiveinteractive/msignal>
> library in C# target but I am unable to compile generated code.
>
> The error reported is as follows:
> Sources/src/msignal/Signal.cs(22,245): error CS1525: Unexpected symbol `)’
>
> __temp_me220.slots = ((global::msignal.SlotList)
> (global::msignal.SlotList.__hx_cast(((global::msignal.SlotList)
> (global::msignal.SlotList.NIL) ))) );
>
> However the parenthesis are correct of course. I was told there is no
> fancy stuff in msignal(no macros) and it should work. Also, after switching
> to hxsignal <https://github.com/zweimal/HxSignal> everything works fine.
>
First of all, hxsignal uses macros:
https://github.com/zweimal/HxSignal/blob/master/src/hxsignal/Signal.hx#L33
Secondly, macros are not dangerous. Using Dynamic and casting (as msignal
does) easily causes issues on the other hand (as you can see above) ;)

Thirdly, tink_core also has a Signal implementation that uses no macros, no
casting, no Dynamic and works on C# (
https://travis-ci.org/haxetink/tink_core/jobs/65871718#L1731). Find out
more in the giant readme: https://github.com/haxetink/tink_core#signal ;)

Best,
Juraj

**Comment by luboslenco** [comment]
Hi,

I have nothing against macros:) I can use hxsignal instead and will eventually end up using your tink_core library.

I was discussing this issue on irc channel and was advised to report it anyway to discover the problem - that is my motivation behind it.

**Comment by Simn** [comment]
Any lisp programmer who can tell me what the syntax error is?

**Comment by waneck** [comment]
Strangely, there doesn't seem to be any syntax error

**Comment by Simn** [comment]
@luboslenco: Are you quite certain you got the right line?

**Comment by daisuda** [comment]
@luboslenco 
I don't think hxsignal is a good choice at C# target.
I did some random performance tests and found the codes generated for C# target were really slow.
Maybe Signal C# target implement should use some special codes(e.g. event or delegate) for better performance.

**Comment by zweimal** [comment]
Hi guys,
Could you report those issues at hxsignal repo?
I will try to solve them as soon as posible.
Also I should create test for C#.
Thanks,
Germán

**Comment by zweimal** [comment]
@back2dos 
> First of all, hxsignal uses macros:
> https://github.com/zweimal/HxSignal/blob/master/src/hxsignal/Signal.hx#L33
Yes, you are right I am using macros but to select the correct underlying type. The idea is to select Signal0, Signal1, etc according to the Function signature simulating a C++ variadic template.
> Secondly, macros are not dangerous. Using Dynamic and casting (as msignal
does) easily causes issues on the other hand (as you can see above) ;)
HxSignal is not using Dynamic and casting. It hasn't the same problem msignal has. 

@waneck 
HxSignal uses ObjectMap with Function as key to look for its related Connection. Either Java and C# targets weren't working until haxe 3.2 release. Now Java target is working but C# isn't.
Tests are failing and one of those is that:
```haxe
	public function testSlot2()
	{
		emitter.signal2.connect(slot2, Once);
		assertTrue(emitter.signal2.isConnected(slot2)); // it should be true but it returns false
		...
	}
```
isConnected method calls to this method:
```haxe
	public function has(slot : Slot<SlotType>) : Bool
	{
		return slots.get(slot) != null;
	}
```
where slot is a *callable* abstract (SlotType can be Void->Void, T1->T2->R, etc) and slots is an ObjectMap.

**Comment by zweimal** [comment]
@daisuda 
> @luboslenco 
I don't think hxsignal is a good choice at C# target.
I did some random performance tests and found the codes generated for C# target were really slow.
Maybe Signal C# target implement should use some special codes(e.g. event or delegate) for better performance.

Actually hxsignal is not working at C# target as I commented above.
However I really interested in what you think is an issue in order to get a workaround for it.
I want to avoid to write specific code as much as possible.

**Comment by daisuda** [comment]
Hi @zweimal ,  oh sorry I didn't run the Test file so didn't realize it cann't pass All tests. I just used it directly and did some performance test :) 
Maybe @luboslenco has resolved these fail as he motioned above "everything works fine".

**Comment by luboslenco** [comment]
I didn't run the Test file either, but there was no compilation errors when I used hxsignal. Only msignal was unable to compile.

The error line should be correct, but I am actually doing this using Kha Unity3D target. I am not sure if there are any differences when it comes to C#, there probably shouldn't be but I will try to setup a standalone project anyway.

**Comment by waneck** [comment]
I've just tested one of the examples and fixed it. I couldn't isolate the code into a minimal case, so I'm going to leave this open to 3.4. But it should be fixed now

**Comment by waneck** [comment]
Closing this - it's fixed and I don't think I'll be able to find a minimal case at the moment
