### ISSUE TITLE
Feature request: Context.expandMacros()

### ISSUE THREAD

**Issue by jacekszymanski** [HaxeFoundation/haxe#4304]
```Context.expandMacros(expr: Expr): Expr```

The function returns an expression which is equivalent to its parameter, but with all macros expanded. 

Rationale: 

Macros are useful both for code generation, where user-supplied arguments are inserted as-is into the generated code and code rewriting where they are significantly altered by the macro code. They are also useful for code inspection, e.g. to enforce some rule. 

It is the two latter use cases where the ability to access the supplied expression(s) with macros expanded is necessary. For example, in my library scopes I use macros for both purposes: I  replace ```return``` in the protected scopes with the throwing of control exceptions, and, in the scope exit expressions I enforce the prohibition to use ```return```. 

Without the ability to expand inside macros these and similar measures could be circumvented with macros, even inadvertently, leading to all sorts of strange bugs. In Common Lisp, where macros are used much more widely than in Haxe (the entire standard object system CLOS is in fact implemented with macros), while implementation writers are allowed to implement any macro directly in the compiler to improve performance, they still have to provide an equivalent macro implementation that can be expanded and inspected or rewritten. 

Haxe doesn’t probably need the fine-grained control over macroexpansion Common Lisp provides, and this would probably be very hard to do, as macros interfere with static typing absent from Common Lisp, but the ability to have the expression macroexpanded would greatly increase the possibilities of macros.

Haxe already allows to force macroexpansion by means of abusing ```Context.getTypedExpr(Context.typeExpr(expr))```. This is however a hack, doesn’t work every time, e.g. when the expression cannot be typed itself, but it still is legitimate where it is. So far I have managed to work around this limitation, but it would be really well if Haxe itself provided this ability with no need for ugly hacks.

**Comment by back2dos** [comment]
Macro expansion is inherently coupled to typing, when `Expr` becomes
`TExpr` in the compiler (in the macro runtime the latter is called
`TypedExpr`) and `Context.typeExpr` is essentially away to trigger that by
hand. And the reverse transformation is simply done with
`Context.getTypedExpr`. My guess is that only actually exists in the
compiler for historical reasons, i.e. the way static extentions macros were
implemented before Haxe 3.1 or so.

For pure inspection, nothing stops you from doing it on `TypedExpr` though,
other than maybe the absence of reification in pattern matching. But with
TypedExprTools things such as checking for illegal returns should be easy.

**Comment by Simn** [comment]
Yes this doesn't work with our compiler architecture.
