### ISSUE TITLE
Feature request: Context.shouldReturn()

### ISSUE THREAD

**Issue by jacekszymanski** [HaxeFoundation/haxe#4305]
```Context.shouldReturn(): Bool```

Returns ```true``` if at the place the macro is called a ```return``` is necessary, otherwise ```false```.

Rationale:

In Haxe functions that return value are required to use ```return```, otherwise the code will not compile. There is however no way for a macro writer to know whether his macro is in place where this is required or not. Code rewriting macros may be used to rewrite even the entire bodies of functions, or otherwise small blocks of code inside. Without the ability reliably to determine whether the code must end with return or not it is very hard (perhaps impossible) to do such rewrites correctly.

Now I believe the only way to attempt to determine this is to inspect the expression being rewritten whether every branch of code within ends with a ```return something``` or ```throw```. This may however give a wrong answer in case of a user error, and cause the compiler to emit misleading error messages, i.e. pointing to the macro as error source.

**Comment by Simn** [comment]
I don't understand why the macro author should have to worry about this. It's the job of the user to add a return expression if it's required.

Furthermore, it is not always possible to answer this question at the time of typing. Consider this:

```haxe
function test() {
    code();
    if (condition()) {
        moreCode();
        macroCall();
    } else {
        evenMoreCode();
        return "foo";
}
```

Clearly you need a return at `macro call()` but this only becomes apparent when the else case is typed.

**Comment by jacekszymanski** [comment]
If the macro author is enclosing the user provided code, rewritten or not, in his generated code, as I do [here](https://bitbucket.org/parensoft/scopes/src/d8cb25a337f885eee2c6fb29c5314231cde388e9/src/main/haxe/scopes/Protect.hx?at=master) (lines 71-109) it is necessary that the generated expression causes no compile errors. Now I inspect the provided code to detect whether it returns or throws everywhere, and if it is so, I throw an exception to make the compiler happy (if my macro works as expected this is never reached, but the compiler won't detect this).

**Comment by Simn** [comment]
That still doesn't make any sense to me. If a return is needed the user can add `return macroCall()` like you normally would. It is really not the job of the macro to figure out whether or not it is expected to generate a return expression and as I have shown above the compiler couldn't answer that in the general case anyway.

We could add a utility method to determine this for a given Expr argument, but this would not be a contextual thing. Manually inspecting the argument expression like you do looks like the right approach to me.
