### ISSUE TITLE
[as3] throw in inlined function - "Missing return"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4309]
This is the `InlineRelying` example from the Haxe Manual:

```haxe
class Main {
  public static function main () { }

  static function test() {
    if (Math.random() > 0.5) {
      return "ok";
    } else {
      error("random failed");
    }
  }

  static inline function error(s:String) {
    throw s;
  }
}
```

Doesn't compile to as3:

`Main.hx:8: characters 6-28 : Missing return: String`

**Comment by Simn** [comment]
That's because As3 does not inline unless you force it to. Let's just add `@:extern` to the field to force inlining.

**Comment by Gama11** [comment]
Shouldn't the `error()` function be missing from the as3 output anyway due to being inlined?

**Comment by Simn** [comment]
It's not inlined, that's the whole problem.

**Comment by Gama11** [comment]
Ah, wasn't clear to me that by As3 you meant genas3.

**Comment by Simn** [comment]
That wouldn't be accurate either because inlining happens long before any generator sees the code. But yes I was talking about Haxe/As3.
