### ISSUE TITLE
returning null for Void return type allowed on some platforms but not others

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#4312]
Returning null in a method with a Void return type is allowed on js and flash platforms, but generates invalid target code in C#.

```
class Test {
    static function main():Void {
        return null;
    }
}

**Comment by Simn** [comment]
Generating that to C# I get:

```
	public static void main() {
		object __temp_expr1 = null;
		return;
	}
```

Which seems fine? What Haxe version are you on?

**Comment by SmerkyG** [comment]
Sorry, my mistake in the example. Apparently the issue occurs only when you return null within an if statement. I'm still on one of the dev builds from the RC days right before 3.2.0.

haxe input:
 ```
class Test {
    static function main():Void {
	var a = false;
	if (!a) return null;
    }
}
```
C# output:
```
	public static void main() {
		bool a = false;
		if ( ! (a) ) {
			return null;
		}
		
	}

**Comment by Simn** [comment]
Ah yes, I can reproduce with that.

@waneck: Looks like a missing recursion somewhere, or do you expect this to be post-processed by Haxe core?

**Comment by waneck** [comment]
This is done inside gencommon, and it should indeed be a missing recursion
