### ISSUE TITLE
Allow metadata on function argument declarations

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4313]
`static function test(@:out e:Int) { }`

This is trivial on the typed side because tvar has `v_meta` already, so we only have to deal with the syntax side.

The main use-case for me right now is getting rid of cs.Ref and cs.Out. They currently present a weakness in our typing system because we cannot easily prevent people from using them in invalid places. They also cause issues with the static analyzer due to their special semantics, which is currently quite hard to detect.

@dogles also has some macro-related ideas for this feature.

**Comment by nadako** [comment]
Since we have those on the untyped AST level, I went ahead and implemented encoding/decoding for it. Forgot to link one more commit: e43164082dac114fb1fbfd05f1e385f88bc866e0

**Comment by nadako** [comment]
Anyway, here's an example of use: https://gist.github.com/nadako/8ad5f75d261fa25a7c0af56fbb0d24c1

**Comment by Simn** [comment]
I'm still not sure if this is a breaking change, but I guess we'll see!

**Comment by back2dos** [comment]
It may break code that relies too heavily on inference, but personally I
think that's well worth it ;)
