### ISSUE TITLE
Completion Bug with abstract @:from 

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4315]
this fails to provide completion:

```haxe
@:forward abstract Foo(Int) from Int {
	public function new (x) this = x;
	@:from public static function from1 (x:String):Foo {
		return new Foo(Std.parseInt(x));
	}
}

class Main {
	static function foo (d:Foo) {
		return "hey";
	}
	public static function main () {
		foo("1").| // no completion at this point
	}
}
```

the error is something like:

Main.hx:23: characters 6-9: String should be Foo
Main.hx:23: characters 6-9: For function argument 'd'
Main.hx:15: characters 0-5: Defined in this class

**Comment by Simn** [comment]
Does that still happen if you move Foo to its own file?

**Comment by frabbit** [comment]
yes

**Comment by Simn** [comment]
I'm not sure what's causing this so I'll have to investigate this a bit.
