### ISSUE TITLE
-D no-deprecation-warnings compiler define does not appear to be working

### ISSUE THREAD

**Issue by andypellucid** [HaxeFoundation/haxe#4317]
I'm using the development version of haxe (`brew install haxe --HEAD`).  `Map.IMap` is @:deprecated.

```haxe
package ;

class Main {
  public static function main() {
    Std.is("test", Map.IMap); // Map.IMap is deprecated
  }
}
```

If I run this, I want to suppress the deprecation warnings:

```sh
haxe -D no-deprecation-warnings -main Main -js main.js
```

I get this output:

```sh
Main.hx:5: characters 19-27 : Warning : Usage of this typedef is deprecated
```

Am I doing something wrong?

**Comment by Simn** [comment]
That was on oversight on our end. Typedefs require special treatment because they tend to get "lost" when types are followed, and that special treatment part didn't check the flag. Thanks for reporting!
