### ISSUE TITLE
undued closure allocation (3.1.3) on target flash  / check request

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#4320]
As discussed on irc with Simn.

I tracked down our major source of allocation in some context to this:

```
override function drawRec( ctx : h2d.RenderContext ) {
		if ( style.visibility == false ) return;
		if ( style.overflowHidden!=null&&style.overflowHidden ) {
			bgFill.afterDraw = function() {
			var px = (absX + 1) / matA;
			var py = (absY - 1) / matD;
			
			var rX = px;
			var rY = py;
			var rW = contentWidth;
			var rH = contentHeight;

			
			old = ctx.engine.getRenderZone();
			if ( old != null ){
				old = old.clone();

				rW = Math.min( rX+rW, old.x+old.z );
				rH = Math.min( rY+rH, old.y+old.w );
				rX = Math.max( rX, old.x );
				rY = Math.max( rY, old.y );

				rW -= rX;
				rH -= rY;
			}
			ctx.flush();
			ctx.engine.setRenderZone( Std.int(rX), Std.int(rY), Std.int(rW), Std.int(rH) );
		};
		}
		
		super.drawRec(ctx);
		
		if ( style.overflowHidden!=null&&style.overflowHidden ) {
			ctx.flush();
			if( old == null )	ctx.engine.setRenderZone();
			else				ctx.engine.setRenderZone( Std.int(old.x), Std.int(old.y), Std.int(old.z), Std.int(old.w) );
		}
		
	}
```

The AST is correct but scout shows that the closure is allocate 100% of the time even if control flow never ever gets in.
This is a major hidden cost.

Please check if the behaviour still exists and maybe take action. If your too short on time, i can take a look but i don't have a 3.2 environnment right here out of the box and reproducing can be complicated.

**Comment by ncannasse** [comment]
It's not the closure that is allocated but the "slot" that holds the locals that are referenced from within the closure (ctx and this). It would require some quite extensive flow analysis in genSWF in order to optimize it. I guess we could do a special case when none of the used variables are modified.

**Comment by delahee** [comment]
This is a big frequent ugly offender (90%  of runtime allocs) without even
branching on it, which made us avoid closures at very great ergonomics
costs, frankly I would prefer you just move slot allocation behind the if.
Everyone in the community might be plagued without knowing it...

Anyway thanks for the investigation :)

**Comment by ncannasse** [comment]
PS: FYI try/catch is also concerned

**Comment by delahee** [comment]
Ok good to know thanks a lot !
Le 12 juin 2015 21:26, "Nicolas Cannasse" <notifications@github.com> a
écrit :

**Comment by delahee** [comment]
closing, we'll reopen when someone can give some time to these class of problems.
