### ISSUE TITLE
Add @:autoGenericBuild or @:genericBuild in @:autoBuild

### ISSUE THREAD

**Issue by porfirioribeiro** [HaxeFoundation/haxe#4321]
Haxe have a `@:autoBuild` metadata that add's `@:build` to all its subclasses.
It was good to have  some sort of `@:autoGenericBuild` to add `@:genericBuild` to subclasses.
I tryed to add the metadata to class on `@:autoBuild` but it didn't worked:
```haxe
package;

#if !macro @:autoBuild(MainTest.buildITest()) #end
interface ITest<T> {}

//@:genericBuild(MainTest.genericBuild())
class Test<T> implements ITest<T> {
	public static var A:Test<String>;
}

class MainTest{
	
	static function main() {}
	#if macro
	static function buildITest() {
		var k = haxe.macro.Context.getLocalClass().get();
		trace('buildITest', k.name);
		k.meta.add(':genericBuild', [macro MainTest.genericBuild()],k.pos);
		return haxe.macro.Context.getBuildFields();
	}	
	static function genericBuild() {
		trace('genericBuild');
		return null;
	}
	#end
}
```
The only way to get the genericBuild to be called is uncomment 
```haxe
@:genericBuild(MainTest.genericBuild())
```

**Comment by Simn** [comment]
This could get pretty strange if there are multiple build-macros. It works for normal `@:build` because the field transformations can be chained, but it doesn't make much sense for `@:genericBuild` macros which return a type-hint.

**Comment by Simn** [comment]
I prefer not adding this for the time being.
