### ISSUE TITLE
c++; potential code generation issue with local inline function expression returning Void type

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#4323]
I have the following code:

```
var bounce_timer:...;
var bouncing:Bool; 
function Bounce() { 
...
    var startp = ...

    inline function cancel_bounce() {
        SetPosition(startp);
        if(bounce_timer != null) bounce_timer.stop();
        bounce_timer = null;
        bouncing = false;
    }

   bounce_timer = ...(time, function() {

       if ( !alive ) {
             return cancel_bounce();
       }

   }) 

} //Bounce
```

Note:
- this is the only return inside of this local Void->Void closure function 
- the return is returning "Void" type as a short hand
- I know this is maybe not viable behavior? See below.

The following code is output based on the above:

```
if ((tmp27)){
    ::phoenix::Vector tmp28 = startp;
    _g->SetPosition(tmp28);
    bool tmp29 = (_g->bounce_timer != null());
    if ((tmp29)){
        _g->bounce_timer->stop();
    }
    _g->bounce_timer = null();
    return _g->bouncing = false;
}
```

Notice that this inline function has now transformed to return the _last_ statement of the function as an expression in c++, which generates a c++ compile error, rightfully so (trying to convert to Void from bool).

```
error: no viable conversion from 'bool' to 'Void' (aka 'null')
                                                        return _g->bouncing = false;
                                                               ^~~~~~~~~~~~~~~~~~~~
/Users/sven/dev/haxelib/hxcpp/3,2,102/include/null.h:65:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'bool' to 'const null &' for 1st argument
class null
      ^
1 error generated.
```

The "fix" is obviously not to return like that, and do it this way:

```
if(!alive) {
   cancel_bounce();
   return;
}
```

But it does make me think that the case was a potential place for an error in less obvious places. 
For returning a Void type - if it's possible the compiler knows that it is Void and not Unknown<> at this point - to give an actual error message and make the behaviour explicit.

Or - if returning Void types is allowed (I have done this quite a bit in fact) this may be a generation bug.

**Comment by Simn** [comment]
```haxe
class Main {
	static function main():Void {
		return f();
	}

	static inline function f() {
		false;
	}
}
```

AST:

```
class Main{
	static main(method) : Void -> Void

	 = [Function:Void -> Void] [Block:Dynamic] [Return:Dynamic] [Const false:Bool]

}
```

We end up with a Void -> Void function that has a `return false`.

**Comment by Simn** [comment]
We should transform this early, i.e. while typing it. There's no reason to carry an invalid expression like this to later stages.
