### ISSUE TITLE
Strange Servermode Bug with inline + pattern matching

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4324]
you need two files to reproduce this bug:

Main.hx
```haxe
import haxe.ds.Option;
using Options;

class Main {

	public static function main () {
		trace(Some(1).isSome());
	}
}
```
Options.hx
```haxe
import haxe.ds.Option;

class Options {
  public static inline function isSome <T>(o:Option<T>):Bool return switch (o) 
  {
    case Some(_): true;
    case None:    false;
  } 
}
```

1) start haxe server
1) try to compile Main using servermode, it should compile fine.
2) add an empty line somewhere in Main.hx
3) trying to compile again with servermode results in errors like these:

```
Options.hx:4: lines 4-8 : Cannot inline a not final return
Main.hx:4: lines 4-9 : Defined in this class
```

To get a successful compilation again the server needs a restart. 

The problem seems to be related to pattern matching + inline because changing the implementation of isSome to `o.match(Some(_))`  or removing inline doesn't cause this behaviour.

**Comment by Simn** [comment]
This was not really related to the compilation server but to control flow with regards to exhaustive switches. It could be reproduced without the compilation server: https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue4324.hx

There were actually two seperate issues:

1. TMeta ate the `term = true` status.
2. `term` was considered to be false unless there was a default case in the switch.
