### ISSUE TITLE
Help Github ignore generated (JavaScript) files

### ISSUE THREAD

**Issue by mlms13** [HaxeFoundation/haxe#4328]
Currently, if you use Haxe to compile to a JS target and check in the generated files, there's a good chance Github will miscategorize the entire repo as JavaScript. There's [an open issue](https://github.com/github/linguist/issues/2403) relating to this in Github's Linguist project, which is responsible for language detection, but there are things Haxe could do to help. For example, if the first line of the file would have a  `// Generated by Haxe` comment, Github would automatically filter the JS file out of language stats for the repo.

This could potentially lead to some repos getting reclassified as Haxe, which would give Haxe a little bump in the language share statistics. :)

**Comment by Simn** [comment]
I don't know, are there really that many people checking in generated files in git?

**Comment by adireddy** [comment]
I think in general most of the people will not check in generated files but there will be cases where you want to checkin generated demos/samples, etc so may be it's a good idea to add `// Generated by Haxe`

Github will ignore anything in `samples` folder and JS files with `.min` suffix. [List of all directories/files excluded from language statistics.](https://github.com/github/linguist/blob/master/lib/linguist/vendor.yml)

**Comment by fponticelli** [comment]
I checkin most of my generated files (I also try to exclude them using
.gitattributes but that is not an obvious procedure) with the purpose of
letting the users test/demo the files without having to recompile. The
intent is to let non haxe user try without many issues and attract them to
the dark side. Given the effort of adding such comment I think there are
only benefits coming from it: github behavior, subtle advertisement,
clarity on the fact that it is generated code ...

Il giorno dom 14 giu 2015 alle ore 04:04 Adi <notifications@github.com> ha
scritto:

**Comment by Simn** [comment]
Somehow I think that some people will complain about this, but maybe that's just because at the moment everyone complains about everything. ;)

**Comment by nadako** [comment]
add a define for those? :)

**Comment by Simn** [comment]
-D js-do-not-generated-generated-by-haxe-comment

**Comment by andyli** [comment]
I would propose to have `-D source-header='...'`, which default to `"Generated by Haxe\n"`.
People can override it to embed license or any other instruction.
To disable it, `-D source-header=''`.

**Comment by Simn** [comment]
As usual you're thinking one step further than we do, nice!

The only question is if it should be source-header or js-source-header.

**Comment by andyli** [comment]
I prefer source-header and enable it for all the source targets. I remember that there were people using the php target wanted to add a "do not edit" statement.

**Comment by fponticelli** [comment]
-D source-header with default sounds really great to me!

Il giorno mer 17 giu 2015 alle ore 12:53 Andy Li <notifications@github.com>
ha scritto:

**Comment by ncannasse** [comment]
I like it as well :) We have to make sure it's documented in manual

**Comment by fponticelli** [comment]
Are we agreeing here? that seems too much -1 on this feature (just kidding
:) )

Il giorno mer 17 giu 2015 alle ore 13:11 Nicolas Cannasse <
notifications@github.com> ha scritto:

**Comment by Simn** [comment]
@hughsando: Could you add this to gencpp? I couldn't find the right place for it.
