### ISSUE TITLE
CPP generation error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4330]
I am trying to compile Evoland2 to CPP and got an error while generating a specific class. It has a pretty big local function, which generates the following code:

```
	HX_BEGIN_LOCAL_FUNC_S16(hx::LocalFunc,_Function_1_2,::ent::Entity,target,Float,ang,::ent::t::Fighter,dalkin,::ent::t::Fighter,ttarget,Array< Float >,time,Float,dy,::ent::t::Projectile,_g,::ent::t::Fighter,owner,Array< Float >,targetY,Float,distance,Array< bool >,hitted,Array< Float >,targetX,cpp::ArrayBase,dalkinEnd,bool,isDalkin,Array< Float >,acc,Dynamic,onEnd)
	int __ArgCount() const { return 1; }
	bool run(Float dt){
        ...
```

And MSVC complains with the following (sorry, error messages are localized in french)

```
./src/ent/t/Projectile.cpp(1022) : error C2275: 'hx::LocalFunc'ÿ: utilisation non conforme de ce type comme expression

./src/ent/t/Projectile.cpp(1022) : error C2065: '_Function_1_2'ÿ: identificateur non d‚clar‚

./src/ent/t/Projectile.cpp(1022) : error C2275: 'ent::Entity'ÿ: utilisation non conforme de ce type comme expression

./src/ent/t/Projectile.cpp(1022) : error C2275: 'Float'ÿ: utilisation non conforme de ce type comme expression
```

Tell me if you need anything else @hughsando I can send you the class in question if necessary.

**Comment by hughsando** [comment]
Looks like it had trouble defining the closure _Function_1_2 - is the
local function  defined in a unusual place - like a in a case
statement or somewhere odd - not just a normal block?  Is this
function (_Function_1_2)  in in the cpp file?

Also, is "target" of type ::ent::Entity - or maybe some related/derived type?

**Comment by ncannasse** [comment]
The closures are in the constructor (there are several of them inside each other).
I'm sending you the class by direct email, you will not be able to compile it but a least you can look at the code.

target is typed as ent.Entity.

**Comment by hughsando** [comment]
I think it was just the number of variables captured by the closure.
I have increased this number to 20 on the github version of hxcpp.

**Comment by Simn** [comment]
Has this been resolved?

**Comment by hughsando** [comment]
I think this one as it stands has been solved.  I do not have a general solution as this number of args increases.

**Comment by hughsando** [comment]
I have increased the number of captures to 62 (practical limit due to macros) with https://github.com/HaxeFoundation/haxe/commit/06309991e53b8ba7c4c4925c08624c0838712c47 and thrown an error when the number is too big.

I used this for testing:
```
class Test
{
   public static function main()
   {
      var a0 = 0, a1=1, a2=2, a3=3, a4=4, a5=5, a6=6, a7=7, a8=8, a9=9;
      var a10 = 0, a11=1, a12=2, a13=3, a14=4, a15=5, a16=6, a17=7, a18=8, a19=9;
      var a20 = 0, a21=1, a22=2, a23=3, a24=4, a25=5, a26=6, a27=7, a28=8, a29=9;
      var a30 = 0, a31=1, a32=2, a33=3, a34=4, a35=5, a36=6, a37=7, a38=8, a39=9;
      var a40 = 0, a41=1, a42=2, a43=3, a44=4, a45=5, a46=6, a47=7, a48=8, a49=9;
      var a50 = 0, a51=1, a52=2, a53=3, a54=4, a55=5, a56=6, a57=7, a58=8, a59=9;
      var a60 = 0, a61=1;

      var big = function() return
         a0++ + a1++ + a2++ + a3++ + a4++ + a5++ + a6++ + a7++ + a8++ + a9++
         + a10++ + a11++ + a12++ + a13++ + a14++ + a15++ + a16++ + a17++ + a18++ + a19++ 
         + a20++ + a21++ + a22++ + a23++ + a24++ + a25++ + a26++ + a27++ + a28++ + a29++
         + a30++ + a31++ + a32++ + a33++ + a34++ + a35++ + a36++ + a37++ + a38++ + a39++
         + a40++ + a41++ + a42++ + a43++ + a44++ + a45++ + a46++ + a47++ + a48++ + a49++
         + a50++ + a51++ + a52++ + a53++ + a54++ + a55++ + a56++ + a57++ + a58++ + a59++
         // This is too many for hxcpp: + a60++ + a61++
         + a60++ 
         ;


      trace( big()==270);
      trace( big()==331);
   }
}
```
