### ISSUE TITLE
CPP output stability wrt compilation server

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4332]
I've put my CPP output files on a GIT repo to analyze changes that were made in the output and try to explain why I often have to recompile more files than it seems necessary.

After restarting the compilation server and making a fresh compilation, I have changes in almost all the files, in the following form:

```cpp
// file that was put on GIT after several compilation with compilation server
	{
		HX_STACK_LINE(45)
		int tmp1 = ::EntityFlag_obj::FBox->__Index();		HX_STACK_VAR(tmp1,"tmp1");
		HX_STACK_LINE(45)
		int tmp2 = (int((int)1) << int(tmp1));		HX_STACK_VAR(tmp2,"tmp2");
		HX_STACK_LINE(45)
		int tmp11 = tmp2;		HX_STACK_VAR(tmp11,"tmp11");
		HX_STACK_LINE(45)
		::Game tmp3 = this->game;		HX_STACK_VAR(tmp3,"tmp3");
		HX_STACK_LINE(45)
		hx::OrEq(tmp3->state->heroFlags,tmp11);
	}
```

```cpp
// fresh file after restarting the compilation server
	{
		HX_STACK_LINE(45)
		int tmp1 = (int((int)1) << int(::EntityFlag_obj::FBox->__Index()));		HX_STACK_VAR(tmp1,"tmp1");
		HX_STACK_LINE(45)
		::Game tmp2 = this->game;		HX_STACK_VAR(tmp2,"tmp2");
		HX_STACK_LINE(45)
		hx::OrEq(tmp2->state->heroFlags,tmp1);
	}
```

It seems some AST rewriting (in filters ?) is done several times while it should only be done if the module has been modified.

Original haxe code:

```haxe
enum Flags {
     FBox;
}
class State {
     public var heroFlags : haxe.EnumFlags<Flags>;
}
class Box {
    ...
    heroFlags.set(FBox);
}

```

PS : this is not specific to EnumFlags, maybe more to inlining.

**Comment by ncannasse** [comment]
PS : assigned to @Simn in case he overlooked it :)

**Comment by Simn** [comment]
Does this still happen?

**Comment by ncannasse** [comment]
I have not looked at for some time, closing for now.
