### ISSUE TITLE
CPP print to stdout

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4333]
Not sure if it's gencpp or hxcpp, but when running the compilation server, the following is printed to the console:

```
haxelib run hxcpp Build.xml haxe -Ddebug -Dformat="3.1.3" -Dhaxe3="1" -Dhaxe_ve
="3.3" -Dheaps="0.0.1" -Dhxcpp_api_level="321" -Dhxsdl="0.0.0" -DresourcesPath=
../res" -I"D:\\Projects\\hxtools\\hxsdl\\" -I"D:\\Projects\\hxtools\\format\\"
I"D:\\Projects\\hxtools\\heaps\\" -I"D:\\Projects\\haxe\\extraLibs/" -I"" -I"D:
\Projects\\haxe\\std/cpp/_std/" -I"D:\\Projects\\haxe\\std/"
```

Instead, this should be send back to the client using ctx.com.print

The main problem with this is that once the output buffer is full, and since the output is not read by FlashDevelop, the compilation server will deadlock until it's killed.

**Comment by Simn** [comment]
@hughsando: Could we address this for the RC?

**Comment by hughsando** [comment]
I have put  a fix in for this, but the hxcpp build tool still spews quite a bit of stuff.  Is this ok?

**Comment by Simn** [comment]
I'm starting to have problems with the HaxeManual cpp tests because there's too much output. It would be nice if this could be reduced somehow.

**Comment by Simn** [comment]
Not a 3.3 priority though

**Comment by hughsando** [comment]
The default verbosity level of HXCPP has been reduced.
You can reduce it even more with -D HXCPP_QUIET or -D HXCPP_SILENT (will still prints errors).
This should give you the tools to control the level of output you require.
