### ISSUE TITLE
goto is a reserved keyword in PHP5.3+

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe#4337]
Hi, as Nicolas proposed here : https://github.com/ncannasse/dbadmin/pull/10 , I fill an issue about the keyword "goto" being reserved in php 5.3+

```
class Main{


	public static function main(){
	
		goto();
		trace("hello");
	}
	
	static function goto(){
		trace("goto");
	}
	
}
```

 haxe -php www -main Main

```
root@precise32:/vagrant/www# php index.php
PHP Parse error:  syntax error, unexpected T_GOTO, expecting T_STRING or T_VARIABLE or '$' in /vagrant/www/lib/Main.class.php on line 6
PHP Stack trace:
PHP   1. {main}() /vagrant/www/index.php:0
PHP   2. _hx_autoload() /vagrant/www/lib/php/Boot.class.php:0
```

**Comment by Simn** [comment]
Haha... [someone tried to fix this](https://github.com/HaxeFoundation/haxe/commit/329f73bd8c873f6522115bcc0d06aa610ec1642f) already but failed miserably.

**Comment by ncannasse** [comment]
:-) That was funny one

**Comment by Simn** [comment]
That should totally be an "unused pattern" warning though! :/
