### ISSUE TITLE
add_final_return loses Null<T> wrapping

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4341]
```haxe
class Main {
	static function main() {
		pop();
	}

	static function pop<T>():Null<T> {
		if (Math.random() > 0) {
			return null;
		} else {
			return null;
		}
	}
}
```

The AS3 dump:

```
	static pop<T : pop.T>(method) : Void -> Null<pop.T>

	 = [Function:Void -> Null<pop.T>]
		[Block:Void]
			[If:Void]
				[Parenthesis:Bool]
					[Binop:Bool]
						[Call:Float]
							[Field:Void -> Float]
								[TypeExpr Math:Class<Math>]
								[FStatic:Void -> Float]
									Math
									random
						>
						[Const 0:Int]
				[Then:Dynamic] [Return:Dynamic] [Const null:Null<pop.T>]
				[Else:Dynamic] [Return:Dynamic] [Const null:Null<pop.T>]
			[Return:pop.T] [Const null:pop.T]
```

Take note of the last line. There are actually two problems:

1. The TReturn node itself is typed as pop.T while it should be Dynamic like every other return.
2. The returned null constant is typed as pop.T while it should be `Null<pop.T>`.

**Comment by ncannasse** [comment]
It might be that we are not considering T to be nullable, which I remember commenting something about it in type.ml. We could still wrap it with Null for the "null" constant case.

**Comment by Simn** [comment]
Nullability of the type doesn't matter there. If the function is defined to return `Null<T>` then surely a generated return expression should have the same type.

The problem is that the followed type is being used. That's easy to fix though.
