### ISSUE TITLE
Null-variance in functions

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4342]
This is a bit hidden in #3826:

```
class Main {
    static function main() {
        var n:Null<Int> = null;
        var closure:Null<Int>->Null<Int>->Void = printA;
        closure(n, n);
    }

    static function printA(a:Int, b:Int) {
        trace(a);
        trace(b);
    }
}
```

On Java this causes an exception:

```
Exception in thread "main" java.lang.IllegalArgumentException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at haxe.lang.Runtime.slowCallField(Unknown Source)
        at haxe.lang.Runtime.callField(Unknown Source)
        at haxe.lang.Closure.__hx_invokeDynamic(Unknown Source)
        at haxe.lang.VarArgsBase.__hx_invoke2_o(Unknown Source)
        at haxe.root.Main.main(Unknown Source)
        at haxe.root.Main.main(Unknown Source)
```

**Comment by Simn** [comment]
Did we agree to disallow this?

**Comment by ncannasse** [comment]
I *think* so, but I think this is the kind of thing that might have unexpected side effects on bigger codebase, so I might revert my opinion depending on the actual impact it has.

**Comment by ncannasse** [comment]
PS: HL does support this kind of thing at runtime (with Dynamic or not).

**Comment by ncannasse** [comment]
Can you make a branch for it that I can test against our codebase?

**Comment by Simn** [comment]
Looking at it again, it's strange that we would make a special case for `Null<T>` here. If we disallow `Null<T>` to `T`, we should also disallow the `Float` to `Int` contravariance. But that raises some uncomfortable questions for other variance cases.

**Comment by ncannasse** [comment]
Same remark applies :) I'm not sure how much of some "valid codebase" would be concerned by such change. Either we drop it or you make a branch with variance on abstracts disabled for function parameters and I can in return explain you why we can't do it :) -- or eventually accept it as a sane restriction.

**Comment by Simn** [comment]
For me the question isn't about how much code breaks, but how much sense the change makes. It's inconsistent to disallow `Null<T>/T` variance for function types while it's supported for type parameters and structure fields. All these cases should be similar: We have a conversion that isn't valid as far as the run-time is concerned.

It's probably not feasible to change this now, but I'll take a look regardless.

**Comment by Simn** [comment]
Yeah this issue makes no sense. As long as type parameters, which are usually **invariant**, allow this type of assignment, it should also be allowed for function arguments which are normally contravariant.

And given that we can't change general `Null<T>` variance at this point, I prefer to not change it at all. That way it's at least still consistent.
