### ISSUE TITLE
Completion + GADTs

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4345]
See inline remarks about missing completions.

``` haxe
typedef DTag = Tag<DTag>;  // kind of a defeat, but OK..
typedef Tag1 = { tag: TagE<Tag1>, name: String, count: Int }
typedef Tag2 = { tag: TagE<Tag2>, name: String, brand: String, liters: Float};

@:enum abstract TagE<T>(Int) {
    var fruit:   TagE<Tag1> = 1; 
    var beverage:TagE<Tag2> = 2;
}

typedef Tag<T> = { tag:TagE<T> };

class Test {

    static var data : Array<Dynamic> = 
    [
        { tag: fruit,    name: "Apple",  count: 5 },
        { tag: fruit,    name: "Orange", count: 3 },
        { tag: beverage, name: "Sprite", brand: "Coca-Cola", liters: 2.5 }
    ];

    static function untag<T:Tag<T>>(t:T) switch t.tag {
        case fruit:
            t.| // completion here should suggest name and count            
            trace('${t.count} ${t.name}(s)');
        case beverage:
            t.| // completion here should suggest liters and name
            trace('${t.liters} liters of ${t.name}');
    }

    static function main() for (item in data) untag( (item : DTag ) );
}
```

**Comment by ncannasse** [comment]
Too late :) #4344

**Comment by Simn** [comment]
It's the same example code, but this one is about completion.

I'll just blame completion optimization like I usually do.

**Comment by frabbit** [comment]
it doesn't work with `-D no-copt` too

**Comment by Simn** [comment]
```
haxe --display Main.hx@0 -D no-copt
<list>
<i n="count"><t>Int</t><d></d></i>
<i n="name"><t>String</t><d></d></i>
<i n="tag"><t>TagE&lt;Tag1&gt;</t><d></d></i>
</list>
```

**Comment by frabbit** [comment]
you're right, sorry my fault.

**Comment by ncannasse** [comment]
Sorry, I thought it was the same issue :)

**Comment by frabbit** [comment]
@ncannasse No worries ;)

**Comment by Simn** [comment]
So the problem is that the completion optimizer figures it already knows `t` and throws away the entire function body. That obviously skips the GADT-semantics in the process.

**Comment by ncannasse** [comment]
Right. it's meant to do so. I think GADT is always explicit so maybe we can detect it somehow ?

**Comment by ncannasse** [comment]
or add another case for retrying with full expr

**Comment by Simn** [comment]
I don't see anything explicit there unfortunately. We also can't retry because completion doesn't fail, it just has a too general type.

**Comment by Simn** [comment]
On a related note I found that this does not complete correctly:

```haxe
class Main {
	static function main() {
		var e = macro null;
		switch (e.expr) {
			case e:
				e.|
		}
	}
}
```

The completion optimizer does not consider capture variables in patterns so it thinks we want to complete on the outside `e` which is Expr instead of ExprDef.

In general it would be hard to support capture variables properly. Maybe we just shouldn't optimize completion if the completion expression is within a `case`?

**Comment by ncannasse** [comment]
@Simn we could just remove the captured variables from the locals list when entering a case, or define them as unitialized

**Comment by Simn** [comment]
For `case e` yes, but once you have `case Ctor(_, [a, AnotherCtor(x)])` you can't really figure out what the captured variables are without understanding the pattern.

**Comment by Simn** [comment]
Unless we simply remove all identifiers there, hmm... that could potentially kill some extra locals but that would be pretty rare and not really an issue anyway.

**Comment by Simn** [comment]
... but that still wouldn't solve the GADT issue.

**Comment by ncannasse** [comment]
Let's go step by step :)

**Comment by Simn** [comment]
The thing is that the fix for the GADT case is likely solving all other switch-completion issues as a subset.

**Comment by ncannasse** [comment]
@Simn the completion optimizer should not be bypassed as soon as we enter a switch, that will greatly reduce the time to get completion results in such cases
