### ISSUE TITLE
Typo protection if there are no optional fields

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4346]
```haxe
class Main {
	static function main() {
		var a:{f1: Int} = { f1: 1, f2: "foo" };
	}
}
```

Surely this should type-check? I understand we wouldn't want to allow this if the expected type had any optional fields because you could make typos, but here I don't see any safety added.

**Comment by back2dos** [comment]
While your argument is sound, I'm not sure that this won't make things even more confusing.

```
class Main {
    static function main() {
        var a:{f1: Int} = { f1: 1, f2: "foo" };//works
        var a:{f1: Int, ?f3:Bool } = { f1: 1, f2: "foo" };//fails because it "has additional field f2" - dafuq???
    }
}
```

But maybe a clearer error message will do the job.

**Comment by Simn** [comment]
That's true, but then again we already have this wacky unification behavior of constant structure declarations anyway and this would merely shift it a little. But as you said we can improve on the error message.

**Comment by ncannasse** [comment]
The original limitation for constant structure unification is because of this:

```haxe
class Main {
    static function foo( x : { f1 : Int } ) {
    }
    static function main() {
        foo({ f1: 1, f2: "foo" }); // f2 not required !
    }
}
```

But you're right it's a bit confusing when teaching structural subtyping since basic examples doesn't work as one would expect. Maybe we should remove this constant structure limitation, and instead do a specific check for the previous case.

**Comment by ncannasse** [comment]
But yes, this also covers typos, and we don't want to have different behavior if there's an optional field or not. It's all or none.

**Comment by back2dos** [comment]
@Simn It just occurred to me that this is actually not practical. Adding an optional field really should not break code, but with people relying on this, it will.

@ncannasse Can you elaborate on what you mean by "the previous case"?

**Comment by Simn** [comment]
I don't really understand this argument, you can already break stuff by adding an optional field:

```haxe
typedef T = {
	a: String,
	//?b: Int
}

class Main {
	static function main() {
		var a = getStruct();
		test(a);
	}

	static function getStruct() {
		return { a: "foo" };
	}

	static function test(t:T) { }
}
```

Try commenting in the b-field and see what happens.

**Comment by back2dos** [comment]
In you example, you have two different types, that happen to be compatible and then you change one and then naturally, stuff breaks. If `getStruct` were typed explicitly as returning `T` then adding the field would not break anything. 

What I mean is this:

```
typedef Settings = {
   unicorns:Bool,
   rainbows:Bool,
}

function doAwesomeThing(settings:Settings) {
   //do the awesome thing
}

doAwesomeThing({ unicorns: true, rainbows: false, someExtraField: 5 });
```

If you add an `?sparkles:Bool` field now, stuff breaks. I find that currently anonymous types are a really great way to define forward compatible APIs with named parameters. One can simply add another field knowing that code *explicitly* written against that type will not break. It's the most reliable way of defining extensible signatures I know of and I'd love to see a solution that doesn't sacrifice this reliability. 

In the use case I describe, the objects happen to have optional fields anyway (e.g. `sys.db.Mysql.connect`), so the argument can be made that

1. in most cases the behavior in regards to extra fields will stay the same, and that 
2. library authors can avoid issues by always having at least one optional field. 

That doesn't feel quite right, but if you think it's more practical, then sure, let's do it.

**Comment by Simn** [comment]
I'm dropping this idea, making a distinction between optional and non-optional fields seems rather impractical after all.
