### ISSUE TITLE
wild null appears in self-calling closure

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4349]
```haxe
enum E {
    A;
    B;
}

class Main  {
    static function main() {
        (function(v:E) {
            switch (v) {
                case A:
                case B:
            }
        })(A);
    }
}
```

generates

```js
Main.main = function() {
	switch(E.A[1]) {
	case 0:
		null;
		break;
	case 1:
		null;
		break;
	}
};
```

**Comment by Simn** [comment]
We can either

1. figure out where they come from or
2. properly filter them out.

I would like to do some more block cleanup anyway.

**Comment by Simn** [comment]
The nulls come from the inliner in the `term = true` case when there's no expression. It makes sense for cases where we need a value, but looks rather silly otherwise.

**Comment by Simn** [comment]
Block-level constants are now properly filtered, so there's no more null going on here.
