### ISSUE TITLE
Push some generated unit test output to a repository

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4352]
I was thinking about this:

1. Have a HaxeFoundation/haxe-output repository
2. When compiling our unit tests, push some output files (e.g. unit.js) to that repository, referencing the commit in the commit message.

This would allow us to monitor changes in the output. We have had some situations where a minor change would have a drastic effect on the output with regards to optimization. This is very hard to automatically detect and is often only found by people (especially @nadako) diffing changes by hand.

The question is how to do this in a secure way. What are your thoughts?

**Comment by andyli** [comment]
Sounds feasible to me. It should be easy to do push the output from Travis.

I am just not sure whether the diff will be easy to read, given our unit test is a single compilation of many tests and we're keep adding new tests to it.
Maybe it would be better to store the compilation output of a separated, fixed test suite. In that case, we can automatically analysis the output file size and even runtime performance.
Anyway, it can be done as a second step.

**Comment by andyli** [comment]
For the "fixed" tests, I have been thinking to port parts of the benchmarks from [sunspider](https://www.webkit.org/perf/sunspider/sunspider.html), [octane](https://developers.google.com/octane/) or anything similar.

**Comment by Simn** [comment]
We could also commit the -D dump output of several targets. For the most part we'll have new files when adding additional tests, so that should be easy to identify.

**Comment by Simn** [comment]
Could we go ahead with this? I'm doing a lot of manual diffing locally and would really appreciate something like this. I think publishing the `-D dump` results would be sufficient and we probably don't need it for all targets. Maybe js, cpp and cs would be sufficient.

**Comment by andyli** [comment]
Sure, I will work on it later tonight : )

**Comment by Simn** [comment]
Great, thanks!

I'm not sure how related it is, but maybe you can check out https://github.com/HaxeFoundation/haxe.org/issues/104 too while you're at it.

**Comment by andyli** [comment]
Turn out git diff does not work with my previous branching method. I've now changed the branching to "${haxe_branch}_travisci_${os}_${build}" as you've suggested.

I've added a check of the commit date to prevent build output of earlier commit being pushed onto later commit. The build output of earlier commit will just be ignored.

I've already merged it into development. Let me know whether it works well for your need :)

**Comment by Simn** [comment]
That works nicely, thanks!

The only issue is that changes in unit.js and unit.py can easily get so big that github doesn't even show the diff. I guess that's good enough as a "you probably messed something up" sign though.

It would still be nice to have the `-D dump` output from at least one target. Maybe we could use flash and neko for that because they represent a static and dynamic target and don't produce any readable output?

**Comment by andyli** [comment]
I was too focus on the git stuff and forgot about `-D dump`... I've just added that to the neko and the flash builds as suggested ;)

**Comment by Simn** [comment]
Alright, I guess we can close this. Thanks! Turns out this is quite useful after all, I noticed several small changes while working on the analyzer that I wouldn't have noticed otherwise.
