### ISSUE TITLE
haxe generates invalid bytecode for Array::remove and Math::isNaN when targeting swc

### ISSUE THREAD

**Issue by ktimothy** [HaxeFoundation/haxe#4354]
Haxe does not parse Array::remove correctly when targeting swc.

I make swc with following class:

Test.hx
```haxe
package ;

class Test
{
	public static function run():Void
	{
		var array:Array<Int> = [];

		array.remove(1);
	}
}

```

Compile it with command ```haxe -cp ./ -swf lib.swc Test```. Then I use the library in flash code:
Main.as
```actionscript
package
{
	import flash.display.Sprite;

	public class Main extends Sprite
	{
		public function Main()
		{
			Test.run();
		}
	}
}
````

Compile it with command ```mxmlc -library-path+=./lib.swc -output main.swf Main.as ```.

I run main.swf in debugger player and receive an error:

```
TypeError: Error #1006: remove is not a function.
	at Test$/run()
	at Main()
```

Thats the output from decompiler (the same in main.swf and library.swf from lib.swc):
```actionscript
package
{
    public class Test
    {
        public static function run():void
        {
            var _local1:array = [];
            _local1.remove(1);
        }
    }
}
```

The same thing happens to Math.isNaN: it must be compiled to global function isNaN(), but bytecode shows that it tries to call isNaN from class Math, like in the haxe code.

**Comment by Simn** [comment]
You have to [call haxe.InitSwc](http://old.haxe.org/manual/swc#using-a-haxe-swc-in-as3), please try with that.

**Comment by ktimothy** [comment]
Yeah, It works. But patching prototypes in runtime is not what I need.

Look, you can convert Math.isNaN() to isNaN() for javascript target, but cannot do the same for flash? Sounds weird. Why was it so necessary to patch prototypes in actionscript?

**Comment by Simn** [comment]
Well, initSwc does some more things.

This is a "has always been like this" situation for me so I'm reluctant to look into changing anything unless someone comes forward with a pull request to discuss.

**Comment by ktimothy** [comment]
I understand your point.

But I believe that clearness and simplicity is always better. Patching prototypes is not clear. Bytecode, that is invalid until you run some initializer function, is not clear.

Well, I think it's time for me to learn OCaml =)

**Comment by nadako** [comment]
Actually, (at least for Math.isNaN) it's done not in OCaml, but in the initialization function in `Main.hx` itself: https://github.com/HaxeFoundation/haxe/blob/7ee34f4e2d4f7d29f1931924bf95016b961e7e89/std/Math.hx#L292.

I think it can be changed to work similar to JS version: https://github.com/HaxeFoundation/haxe/blob/7ee34f4e2d4f7d29f1931924bf95016b961e7e89/std/js/_std/Math.hx#L82,

But it seems that the only one who cares for flash nowadays is @ncannasse, so I suggest you consult with him about prototype patching cleanup (for JS we avoid prototype patching so maybe it also makes sense to do the same for Flash).

**Comment by Simn** [comment]
I'll go ahead and close this as the initSwc solution is what we currently have.

**Comment by nadako** [comment]
Yeah, there's further discussion in #4615
