### ISSUE TITLE
Cannot create a "typedef" of an interface with "Const" parameters

### ISSUE THREAD

**Issue by adamscott** [HaxeFoundation/haxe#4358]
I'm trying to create an alias, for backward-compatibility purposes, of an interface with ```Const``` type parameters.

First of all, trying to do this on normal type parameters works flawlessly.

```haxe
// http://try.haxe.org/#Ef292
interface ITarget<T1,T2> {}
typedef IAlternativeName<T3,T4> = ITarget<T3,T4>;

class Test implements IAlternativeName<String,Int> {
    static function main() {}
}
// Build success!
```

But creating a ```typedef``` of an interface with ```Const``` parameters, this fails:

```haxe
// http://try.haxe.org/#1C947
interface ITarget<Const> {}
typedef IAlternativeName<Const> = ITarget<Const>;

class Test implements IAlternativeName<"hey"> {
    static function main() {}
}
// Build failure
// Test.hx:2: characters 0-33 : Constant value excepted as type parameter
```

Here, the compiler accepts a ```typedef``` with ```Const``` as parameter, but complains about the number of type parameters if nothing is specified.

```haxe
// http://try.haxe.org/#25757
interface ITarget<Const> {}
typedef IAlternativeName<Const> = ITarget;

class Test implements IAlternativeName<"hey"> {
    static function main() {}
}
// Build failure
// Test.hx:2: characters 0-33 : Invalid number of type parameters for ITarget
```

I thought if I used the T type, it would work, but it doesn't.

```haxe
// http://try.haxe.org/#21752
interface ITarget<Const> {}
typedef IAlternativeName<T> = ITarget<T>;

class Test implements IAlternativeName<"hey"> {
    static function main() {}
}
// Build failure
// Test.hx:2: characters 0-29 : Constant value excepted as type parameter
```

There should be a way to "transfer" the value of the constant to the target.

**Comment by adamscott** [comment]
I just updated my Haxe to the head of the developement branch to use the (new) ```@:const``` meta. Unfortunately, it does not seem to work as I hoped.

```haxe
interface ITarget<@:const T1> {}
typedef IAlternativeName<@:const T2> = ITarget<T2>;

class Test implements IAlternativeName<"ho"> {
    static function main() {}
}
// Test.hx:9: characters 0-38 : Constant value excepted as type parameter
```

Shouldn't ```T2``` (in this case) be as if I typed ```"ho"``` instead? Because this builds fine:

```haxe
interface ITarget<@:const T1> {}
typedef IAlternativeName<@:const T2> = ITarget<"ho">;

class Test implements IAlternativeName<"ho"> {
    static function main() {}
}
```

Thanks!

**Comment by Simn** [comment]
T2 is not const so no this shouldn't work.

The same applies to the original example. Constant values are not forwarded in any way.
