### ISSUE TITLE
Macro to access fields of JS types causes hang

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4361]
After the brief discussion of ES6 on the mailing list, thought I'd take a stab at implementing it with macros.

I'm trying to use static extension to make 
```
    'I am a string with padding    '.trim();
```
to use ES6 String.trim like:
```
    'I am a string with padding    '.trim();
```
instead of:
```
    StringTools.trim('I am a string with padding    ');
```

So I create my own StringTools like this:
```
class StringTools {
    public static macro function trim(s:ExprOf<String>) {
        return {
            expr: ECall({
                expr: EField({expr: s.expr, pos: s.pos}, "trim"), pos: s.pos},
                []
            ), pos: s.pos
        };
}
```

But calling this code hangs haxe.  Is there any way to get output like this?
```
    'I am a string with padding    '.trim();
```

**Comment by Simn** [comment]
You're returning an expression that causes the macro to be called, which returns an expression that causes the macro to be called, which ...

**Comment by ncannasse** [comment]
`return macro ($s : Dynamic).trim()` should work

**Comment by explorigin** [comment]
Thanks, I got it without having to resort to macros actually:
```
    public inline static function trim(s:String):String {
        return ((untyped s).trim():String);
    }
```
