### ISSUE TITLE
[cs] invalid C# syntax generated and haxe warning emitted for parametrized interface+class

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4363]
The following code:
```haxe
interface I<T> {
    function f(?arg:Float):T;
}

class C implements I<C> {
    public function f(?arg:Float):C return null;
}
```
prints warning: `Main.hx:6: characters 11-47 : Warning : Cannot find matching overload`

and generates invalid C# code in the `C` class:
```cs
public class C : global::haxe.lang.HxObject, global::I<object> {
	// ...
	object global::I<object>.f(global::haxe.lang.Null<double> arg) {
		return ((object) (this.global::I<object>.f(arg)) );
	}
	// ...
}
```

according to @profelis, it works on 3.2

**Comment by nadako** [comment]
tried to bisec that only to know that it's a regression from 3.1.3 (it still emits warning there, but generates correct C# code)

**Comment by waneck** [comment]
Probably related to https://github.com/HaxeFoundation/haxe/commit/903d0ef47e7a54789a8a8261aed346f469026390

**Comment by kaikoga** [comment]
I've recently struck similar problems in C# involving parametrized interfaces and just found this github issue, so I'll post some more code which won't compile C# on Haxe 3.2, just to make sure...

http://try.haxe.org/#b02c0
http://try.haxe.org/#8A3fF

**Comment by waneck** [comment]
Can you try with the nightlies and see if it works now?

**Comment by kaikoga** [comment]
I've just grabbed a nightly from haxe.org: 
```
$ haxe -version
3.3.0 (git build development @ 4768d99)
```

The former code (with typedef) now works thankfully, but the latter one (with enum) still complained.
