### ISSUE TITLE
abstract castable to constructible + @:generic new T = Not_found exception 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4364]
```haxe
class C {
    public function new() {}
}

abstract A(C) to C {}

@:generic
class G<T:{function new():Void;}> {
    public function new() {}
    function make():T return new T();
}

class Main {
    public static function main() {
        new G<A>();
    }
}
```

```
Fatal error: exception Not_found
Raised at file "list.ml", line 179, characters 16-25
Called from file "codegen.ml", line 840, characters 17-49
Called from file "codegen.ml", line 888, characters 15-64
Called from file "type.ml", line 2035, characters 72-77
Called from file "type.ml", line 2022, characters 49-61
Called from file "list.ml", line 84, characters 24-34
Called from file "filters.ml", line 1110, characters 22-29
Called from file "list.ml", line 73, characters 12-15
Called from file "filters.ml", line 1115, characters 2-45
Called from file "list.ml", line 73, characters 12-15
Called from file "filters.ml", line 1211, characters 2-59
Called from file "main.ml", line 1508, characters 2-27
Called from file "main.ml", line 637, characters 3-11
Called from file "main.ml", line 1741, characters 1-35
```

**Comment by Simn** [comment]
The real question here is if this should unify:

```haxe
class C {
	public function new() {}
}

abstract A(C) to C {}

class Main {
	public static function main() {
		var n:A = null;
		var f:{function new():Void;} = n;
	}
}
```

That doesn't seem to make much sense, not only for the constructor case but for normal fields as well.

**Comment by nadako** [comment]
I don't know. It can be directly casted to something that unifies with that structure, so why not? The constructor case is weird tho...

**Comment by nadako** [comment]
cc @gloomybrain as this case was found and extracted from his codebase

**Comment by Simn** [comment]
Yeah thinking about it again it should be alright for normal fields, but really weird for constructors. I don't think this should unify.

**Comment by nadako** [comment]
To be honest, I find specifying `function new()` in the structure declaration very weird. Maybe we could have something like `@:coreType abstract Constructible<T> {}` and then use like `Constructible<Int->String->Void>` or even (to avoid the last Void) `Constructible<Int,String>`

**Comment by gloomybrain** [comment]
Well, from my point of view declaring `function new()` in a typedef makes sense since it is the only way to tell the compiler that exactly such function exists for the given type. See below:

```haxe
class A
{
    public function new() {}
}

class B extends A
{
    public function new() { super(); }
}

@:generic
class C<T:A>
{
    public function new(){}
    public function create():T {return new T();}
}

class Test {
    static function main() {
        var c = new C<B>();
        var a = c.create();
    }
}
```

Haxe compiler 3.2 returns the following error on this example:
> C.T does not have a constructor

The error itself can seem to be fair, but actually (since we use @:generic) compiler can prove that the given T has `function new():Void` declared in it. But it simply doesn't.

And if we use a typedef like in the @nadako 's example above, we get no errors:
```haxe
typedef Constructible = {
    public function new():Void;
}

class A
{
    public function new() {}
}

class B extends A
{
    public function new() { super(); }
}

@:generic
class C<T:(A, Constructible)>
{
    public function new(){}
    public function create():T {return new T();}
}

class Test {
    static function main() {
        var c = new C<B>();
        var a = c.create();
    }
}
```

**Comment by nadako** [comment]
The thing with explicit constructible struct requirement is that a subclass of A can make a constructor private and thus it can't be used for the `new T`, specifying `{function new():Void}` constraint makes sure that constructor is public.

My concern there is that anonymous structure type specifies fields/methods of an **object**, however constructor is more of a **type** attribute (in other words, objects don't have constructors, their classes do). That's why I find this declaration weird and I'm more in favor of a special constraint abstract.

**Comment by gloomybrain** [comment]
The idea of `Constructible<Int,String>` looks pretty good to me.

**Comment by Simn** [comment]
I'm also in favor of deprecating the structural `new` unification. It seemed convenient enough when we first added it, but that doesn't change the fact that it's not really a proper field and might lead to issues down the line.

I'll have to think about the `Constructible` idea, but I think it's a good approach.

**Comment by Simn** [comment]
Anyway, I'll fix this for now.
