### ISSUE TITLE
Cleanup typeload.ml init_class

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4366]
This function is currently a 800 line monster. While I appreciate that it "just works", it is getting harder and harder to maintain. I would like to spend some time cleaning it up.

**Comment by ncannasse** [comment]
I'm fine with it, but i didn't check all the code to see if there was some potential regression

**Comment by Simn** [comment]
I mostly just moved code around and cleaned up the "flags" for each class/field.

There are still some things I want to check. For instance I'm not sure if all our delayed functions affect the right typing context because we clone it for each class and each field. There are a lot of mutable fields there which make me a bit nervous.

**Comment by Simn** [comment]
I found this really strange check: `if (is_static || constr) && c.cl_interface && f.cf_name <> "__init__" && not is_lib then error "You can't declare static fields in interfaces" p;`

That `|| constr` doesn't make any sense so I've removed it. There's already a check for constructors on interfaces before that anyway.
