### ISSUE TITLE
Abstracts should be able to implement an Interface

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4367]
More of a feature request than a bug.

I was working on using the ES6 map as a back-end for Haxe's Map.  It would be awesome if I could use abstract for this since it's really the perfect construct for the job.  But currently only classes can implement interfaces.

```haxe
abstract StringMap<T>(es6.Map<String, T>) implements haxe.Constraints.IMap<String, T> {
    // snip
}
```

yields

```
src/haxe/ds/StringMap.hx:33: characters 42-52 : Unexpected implements
```

**Comment by Simn** [comment]
That doesn't make any sense. Abstracts are a compile-time mechanism whereas interfaces are typically involved with the run-time. Field access on an abstract is very different from field access on an interface so the compiler has to be able to detect this at compile-time.

**Comment by explorigin** [comment]
In what way are interfaces a run-time thing?  There is nothing that indicates run-time in the docs.

**Comment by Simn** [comment]
```haxe
var i:Interface = new SomeClass();
i.someField(); // I'm resolved at run-time
```

**Comment by explorigin** [comment]
There is nothing in your example that either violates an abstract.  If an abstract provides a someField method.  It gets translated at compile-time to whatever function it really is.  The interface doesn't match at run-time but that doesn't matter because we're not dynamically resolving interfaces at run-time.

Is there a platform that takes an unknown object and checks (at run-time) if a library fulfills an interface?

**Comment by Simn** [comment]
> If an abstract provides a someField method. It gets translated at compile-time to whatever function it really is.

Except the compiler can't do that because all it sees is a field access on the interface.

**Comment by explorigin** [comment]
> Except the compiler can't do that because all it sees is a field access on the interface.

But, by definition, that's at compile-time.  If the abstract provides the field and the field access is translated to a traditional function call after that step, there remains no violation and this is still technically feasible.

**Comment by nadako** [comment]
```haxe
function f(i:ISome)
    i.someField();

f(new YourAbstract());
```

how can compiler generate `f` body?

**Comment by explorigin** [comment]
OK, this example makes sense.  Thanks.

**Comment by binki** [comment]
It would be nice to have something like C#’s boxing to accomplish this. If I could define a method in my abstract which is used as an implicit conversion to an interface type, I could instantiate a class which implements the desired interface on the fly and then do things like use raw JavaScript objects as `IMap<String, TValue>`. That would be really useful for consuming partially typed deserialized JSON within which there might be an object use as a JavaScript plain-object dictionary—right now I only know how to access this using an abstract and would need to manually instantiate a wrapper if I needed to pass it to something accepting `IMap<K, V>`.

**Comment by nadako** [comment]
> If I could define a method in my abstract which is used as an implicit conversion to an interface type

But you can already do that with `@:to` methods, unless I'm misunderstanding something.

**Comment by binki** [comment]
> > If I could define a method in my abstract which is used as an implicit conversion to an interface type
> 
> But you can already do that with `@:to` methods, unless I'm misunderstanding something.

That works great! For me it was simply knowing that if I think I want to make an abstract type implement an .interface and am willing to accept a wrapper class, I should write such a class and an implicit conversion. I just didn’t realize the necessary features were there at first ;-).

Thanks!
