### ISSUE TITLE
Consider ignoring common inline rule logic for iterators.

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4368]
For some time now, if all iterator methods can be inlined, no iterator object will be created, and that is great - while iterators can be very useful, slight (or not so slight) incompetency of garbage collectors in regards of recycling small throwaway structures makes them noticeably less suitable for performance-critical sections of programs.

What is not so great is that currently iterator hasNext/next functions are inlined based on same criteria that would apply to inline functions called in the middle of an expression, which means that they will not inline unless the expressions are very simple.

For example, this will not convert the iterator into local variables:
```haxe
class Main {
	static function main() {
		var arr = [1, 2, 3, 4];
		for (k in new IndexIterator(arr)) {
			trace(k + ' -> ' + arr[k]);
		}
	}
}
class IndexIterator<T> {
	public var array:Array<T>;
	public var index:Int;
	public var length:Int;
	public inline function new(array:Array<T>) {
		this.array = array;
		this.index = 0;
		this.length = array.length;
	}
	public inline function hasNext() {
		return index < length;
	}
	public inline function next() {
		var r = index;
		index++;
		return r;
	}
}
```
but it will if you change that `next` function to
```haxe
public inline function next() {
	return index++;
}
```
Now to my actual suggestion: There is completely no reason for the code handling iterators to be "shy" about inlining their methods:
Constructor can always be inlined as the for-loop resides in it's own "block".
next() should not follow the inside-an-expression logic, but rather as if it was put into a block - as it essentially is - no user-defined code can be put before it's call to interfere, so it can do anything so long as there's a final return for variable assignment.
hasNext() is a bit trickier (it _is_ inside a expression rather than block), but that can be fixed as well - if it cannot be inlined, the loop can be safely restructured into
```haxe
it.new(...);
while (true) {
	var hasNext = it.hasNext();
	if (!hasNext) break;
	var value = it.next();
	// ...
}
```
(where method calls mark places of inline insertions)
Or, if you are an opponent of using "endless loops":
```haxe
it.new(...);
var hasNext = true;
while (hasNext ) {
	hasNext = it.hasNext();
	if (hasNext) {
		var value = it.next();
		// ...
	}
}
```
hope it helps.

**Comment by Simn** [comment]
Iterators shouldn't get special treatment. If you want to force the inlining you can make the field `@:extern`. Inline restrictions are also removed if -D analyzer is in place.

**Comment by YellowAfterlife** [comment]
I'd happily use `@:extern`, but it causes the structure to no longer be recognized as an iterator-like (because it no longer has those fields, yes).
Reproduction: add `@:extern` to hasNext/next. An error appears:
```
src/Main.hx:4: characters 12-34 : IndexIterator<Int> has no field iterator
src/Main.hx:5: characters 26-27 : String should be Int
Build halted with errors (haxe.exe).
```

**Comment by Simn** [comment]
Right, that's because for structural sub-typing you usually want to make sure the field actually exists because we cannot inline it if accessed via the structure. You might be able to get away with adding `@:runtime` too.

**Comment by YellowAfterlife** [comment]
Okay, that works a bit better (iterator sample from my original comment inlines alright), although there seem to be some problem with inlining constructor if it is returned from an abstract' method. Sample: https://gist.github.com/anonymous/ddb1e89708e44e0e18a8

**Comment by mandel59** [comment]
It looks the same as #4353.

**Comment by mandel59** [comment]
FYI, moving the `var r` to be a class member rather than a local variable would make the inlining effective, except the initialization of the variable has an issue for now.
There is a workaround for this: initializing the variable explicitly as the following code:
https://github.com/mandel59/unifill/blob/v0.3.1/unifill/InternalEncodingIter.hx#L19

**Comment by Simn** [comment]
Using the `return index++` version I'm now looking at this output:

```js
Main.main = function() {
	var arr = [1,2,3,4];
	var _g_array = arr;
	var _g_index = 0;
	var _g_length = arr.length;
	while(_g_index < _g_length) {
		var k = _g_index++;
		console.log(k + " -> " + arr[k]);
	}
};
```

Looks quite inlined!
