### ISSUE TITLE
Regression: haxeparser is broken with Haxe development branch

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#4369]
[haxeparser](https://github.com/Simn/haxeparser) does not compile any more for Java target with Haxe development branch, while it compiles with Haxe 3.2.0

See https://travis-ci.org/Atry/haxe-import-csv/builds/68450284

**Comment by Simn** [comment]
That's a haxeparser issue, which I have fixed already locally. I didn't push it yet because I have to make a haxelib release first, which I currently cannot due to https://github.com/HaxeFoundation/haxelib/issues/223.
