### ISSUE TITLE
Error in while statement of do-while loop should give explicit line error

### ISSUE THREAD

**Issue by pchertok** [HaxeFoundation/haxe#4370]
Currently if you do not have a bool as the value in a while() statement then the compiler will notify you that an error has occurred in the entire do/while block which can be confusing if your do/while statement is large. The compiler should notify you only of the line of the while() statement.

You can see an example here 

http://try.haxe.org/#16524

**Comment by Justinfront** [comment]
My original error was
.... hx: lines 545-628 : Int should be Bool
it took awhile till I realized the error was in the while condition not the do while code block. While the error is not technically wrong it is easily misleading, would be nicer to provide the line and position of the error within the while condition.

**Comment by nadako** [comment]
we want to test this
