### ISSUE TITLE
[js] use Object.create(null) for StringMap when -D js-es5

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4372]
apparently on ES5 objects created with `Object.create(null)` instead of simple `{}` has no properties at all, so we don't need to check for reserved words and can simplify/speedup StringMap on modern js.

See https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/create

**Comment by nadako** [comment]
I can do that after @andyli sets up saucelabs to actually test js-es5 on browsers that claim to be es5-compatible.

**Comment by nadako** [comment]
I think the same thing can be used for other maps as I believe objects created with `Object.create(null)` are more lightweight than `{}`.

**Comment by back2dos** [comment]
English link for the rest of us: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/create :D

**Comment by nadako** [comment]
Ouch, sorry;)

**Comment by andyli** [comment]
@nadako Since 0712dd9d769a91a31a6fd37259c4ccb79379871e, `-D js-es5` outputs are tested on SauceLabs for browsers other than IE <= 8.

**Comment by nadako** [comment]
Thanks, Andy! I just rebased the PR to test that on SauceLabs.

**Comment by nadako** [comment]
So, as discussed in #4373, there's a problem with `__proto__` key using this approach. One possible fix is to check and escape that exact key in our get/set methods, but I'm not sure whether it's any faster than our current way, I doubt it, actually, so I'm closing this.

We may look into using ES6 maps (see #4552), but it seems that they are not yet widely supported, so it's probably too early to consider that.
