### ISSUE TITLE
using macro inside a target package

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4374]
I'm facing this problem when upgrading the jQuery extern in std.
I want to avoid declaring the `@:overload`s in [`JQueryHelper.J`](https://github.com/HaxeFoundation/haxe/blob/development/std/js/JQuery.hx#L66-L72), by using a macro function as follows:
```haxe
package js.jquery;
class JQueryHelper {
	macro public static function J(exprs:Array<haxe.macro.Expr>) {
		return macro new js.jquery.JQuery($a{exprs});
	}
}
```
The compiler complains "You cannot access the js package while in a macro (for js.jquery.JQuery)".

I found out that I can workaround by putting `JQueryHelper` in the `haxe` package instead, and do a typedef as follows:
```haxe
package js.jquery;
typedef Helper = haxe.JQueryHelper;
```
But it is certainly wrong to put `JQueryHelper` outside of `js` package...
Is there a better way to workaround?

**Comment by nadako** [comment]
I think there's `@:noPackageRestrict` class metadata for that.

**Comment by andyli** [comment]
Oh, it works!
Would be good to document that in `haxe --help-metas` :)

**Comment by nadako** [comment]
I think it's meant to be for internal usage (for std lib only).

**Comment by Simn** [comment]
Yeah, it's an outrageous hack... let's not talk about it any more. ;)
