### ISSUE TITLE
default visiblity of main() is not private

### ISSUE THREAD

**Issue by raould** [HaxeFoundation/haxe#4375]
The docs say the default visibility of functions is private.

But nothing is breaking when I compile my app when I have no visibility modifier on 'static function main()'.

**Comment by raould** [comment]
haxe 3.2.0, targeting javascript, on ubuntu 14.04 lts x86.

**Comment by back2dos** [comment]
This has always been the case in pure Haxe programs. Any error messages you may know, stem from NME/OpenFl, who's build tool actually defines a new main class that calls the the `main` function on your main class.

**Comment by Simn** [comment]
Yes and I see no reason to change it. The function is still technically private in that you cannot call it manually from another class. Allowing private main functions to serve as an entry-point is pure pragmatism.
