### ISSUE TITLE
new jQuery extern

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4377]
I've just added a new set of jQuery extern. Compared to the old extern, which is incomplete and made for an old jQuery version (1.6.4), the new extern is complete and up-to-date.

The new extern is located in the new `js.jquery` package. The old extern has not been removed (but will be deprecated soon), so existing code base will still work. To use the new extern, consult the comparison table as follows:

<table>
	<tr>
		<td></td>
		<th scope="col">old extern</th>
		<th scope="col">new extern</th>
	</tr>
	<tr>
		<th scope="row">jQuery API version</th>
		<td>partial 1.6.4</td>
		<td>complete 1.12.2 / 2.2.2</td>
	</tr>
	<tr>
		<th scope="row">jQuery reference in output</th>
		<td><code>js.JQuery</code></td>
		<td><code>$</code></td>
	</tr>
	<tr>
		<th scope="row">embedding jQuery in output</th>
		<td>use <code>-D embed-js</code> (removed in haxe 3.3)</td>
		<td>use <code>haxe.macro.Compiler.includeFile</code></td>
	</tr>
	<tr>
		<th scope="row">import statement</th>
		<td><code>import js.JQuery;</code></td>
		<td><code>import js.jquery.*;</code></td>
	</tr>
	<tr>
		<th scope="row">jQuery.Event</th>
		<td><code>js.JQuery.JqEvent</code></td>
		<td><code>js.jquery.Event</code></td>
	</tr>
	<tr>
		<th scope="row">haxe helper</th>
		<td><code>js.JQuery.JQueryHelper</code></td>
		<td><code>js.jquery.Helper</code></td>
	</tr>
	<tr>
		<th scope="row">is JQuery iterable?</th>
		<td>yes, <code>Iterable&lt;JQuery&gt;</code></td>
		<td>yes, <code>Iterable&lt;Element&gt;</code></td>
	</tr>
</table>

For [jQueryExtern](https://github.com/andyli/jQueryExternForHaxe) users: You're encouraged to switch to this new std extern, if you're not using any of the [advanced functionalities](https://github.com/andyli/jQueryExternForHaxe/wiki/Haxe-3#config), which will be reimplemented to work for the new std extern. The jQueryExtern lib will eventually become a drop-in replacement to the new std extern with the advanced functionalities. However, I haven't started the work on this end yet.

Documentation in the manual and more tests will be added once the extern is finalized.

Any feedback is much appreciated!

**Comment by andyli** [comment]
The [haxe3.3 branch of jQueryExtern](https://github.com/andyli/jQueryExternForHaxe/tree/haxe3.3) now works with the new std extern.

TODO: update http://haxe.org/manual/target-javascript-external-libraries.html

**Comment by kevinresol** [comment]
Is this available in haxe 3.2.1?

**Comment by andyli** [comment]
Nop. It will be in 3.3 if there is no sudden change.

**Comment by Simn** [comment]
Can this be closed?

**Comment by andyli** [comment]
I think so.
