### ISSUE TITLE
Expose `delay PForce` to macro Context

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4379]
I have the following problem which can't really be solved without some hacks:

I have an `@:autoBuild` macro which needs to work with the built class' typed expression. I wouldn't like to type it again, specially since I want to let people that use this macro to use other macros, without one breaking another (because of this extra typing step, for example)

Because of this, I started to use `Context.onGenerate` to generate the information I wanted and stored it as a metadata. This worked fine until when I needed to use `Context.defineType` (which actually fails silently when used inside `Context.onGenerate`). This all would be solved if `delay` were exposed to macro use - in special, `delay` with `PForce`. This would allow one to register a callback when a type has just finished typing its fields.

Would it be ok to add? Can I send a PR?

**Comment by Simn** [comment]
I don't think that's the right approach. Compiler passes are an internal mechanism that should not surface to macro users in any way in my opinion.

And yes you cannot define new types in onGenerate, it's much too late for that. We have to stop adding new types at some point and that point is when the typer finalizes, before we run the post-process filters.

We could maybe allow a callback for when a field finished typing. I'm not sure how easy that would be though.

**Comment by Simn** [comment]
See #4714
