### ISSUE TITLE
type param constrainted to ArrayAccess

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4380]
```haxe
class Test {
	static function a<T:Array<Int>>(a:T)
		return a[0]; //ok
	static function aa<T:ArrayAccess<Int>>(a:T)
		return a[0]; //Array access is not allowed on AA.T
	static function v<T:haxe.ds.Vector<Int>>(a:T)
		return a[0]; //Array access is not allowed on v.T

	static function main():Void {
		trace(a([123])); //123
		trace(aa([123]));
		trace(v([123]));
	}
}
```

**Comment by Simn** [comment]
I'm okay with the ArrayAccess constraint, but Vector? What would be the semantics of constraining a type parameter to an abstract?

**Comment by andyli** [comment]
I forgot that Vector is an abstract... Please ignore that ;)

**Comment by back2dos** [comment]
@Simn Anything that has a direct `to` for `Vector` would qualify, no?

**Comment by Simn** [comment]
I realized that ArrayAccess is actually an interface. This makes this too messy to support because Array does not actually implement it. This means that even if we made the array access itself work, the constraint check would fail to unify.

In that light I think we shouldn't allow this after all.
