### ISSUE TITLE
Duplicate parameter names

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4381]
Is this expected behavior? 
```
function func(a, a) trace(a);
func("Hello", "World");
// outputs "World"
```
(http://try.haxe.org/#bdE78)

In other languages you get an error like this: `The parameter name 'a' is a duplicate`.

**Comment by Simn** [comment]
That should surely be an error. I hope this is not a regression...

**Comment by back2dos** [comment]
I think that has always been the case. Given that you can write `var a =
"Hello", a = "World";` I would say it is only consistent.

**Comment by Simn** [comment]
It would be cool if the second `a` could reference the first one though. :P

**Comment by markknol** [comment]
I think especially in case of parameters you just want an error.

**Comment by back2dos** [comment]
@markknol I would speculate that it's meant to allow for `function (_, _, theArgumentYouReallyWant) {}`

@Simn It seems it can: http://try.haxe.org/#b94fE

Slightly off-topic: why was referencing previous variables in the same declaration allowed? I would say `var x = y, y = x;` is a very clear way to swap variables. And IIRC this was still possible a couple of years ago.

I see this:

```haxe
{
   var a = exprA, b = exprB;
   somethingHere;
}
```

As this:

```haxe
(function (a, b) {
   somethingHere;
})(exprA, exprB)
```

So I've always been puzzled by the fact that `exprB` may reference `a`. It feels uncomfortably close to JavaScript's weird scoping rules.

**Comment by markknol** [comment]
@back2dos Just curious; In which case would you define a function with those underscores?

**Comment by Simn** [comment]
I find it natural in a left-to-right kind of way. It's also trivial to generate it to our targets, whereas some swapping behavior would be tricky to get right.

**Comment by back2dos** [comment]
@markknol Consider a `map` with the standard JavaScript signature. In that case you would write `[1, 2, 3].map(function (x, _, _) return x + 2)`.

**Comment by back2dos** [comment]
@Simn No doubt it is tricky, but you already got it right, given that this works already:

```haxe
{
  var x = 5, y = 6;
  {
    var x = y;
  }
  {
    var y = x;
  }
}
```

Anyway, it's nothing we can change any time soon. This thread just reminded me of how odd I find it to be, so I had to ask ^^

**Comment by ncannasse** [comment]
We could forbid same-function-parameter-name, with the exception of underscore, that sounds like a good middle ground

**Comment by Simn** [comment]
Thinking about this now I don't think it's worth disallowing this. Who knows what crazy macro-generated functions might have duplicate argument names somewhere. I also don't think this would catch any programming errors.
