### ISSUE TITLE
Throw not correctly take in count during compilation

### ISSUE THREAD

**Issue by Chlorodatafile** [HaxeFoundation/haxe#4383]
I've encounter some troubles with compilation with this little piece of code : 

    interface MyInterface {
        public function getBits(pos:Int, size:Int, signed:Bool=false):Int;
     
        public function setBits(pos:Int, value:Int, size:Int, signed:Bool=false):Int;
    }
     
    class MyClass implements MyInterface {
        public function new() {}
           
        public function getBits(pos:Int, size:Int, signed:Bool=false):Int Make.Unfinished("getBits");
     
        public function setBits(pos:Int, value:Int, size:Int, signed:Bool=false):Int Make.Unfinished("setBits");
    }
     
    enum AbstractError {
        Unfinished(name:String);
    }
     
    abstract Make(Void) {
        public inline static function Unfinished(name:String="") throw AbstractError.Unfinished(name);
    }

This is a little version of my programm, who work on [this][2] but doesn't when I compile by myself with Haxe.
Actually, I receive this compile time error when I try to compile :

    Void should be Int
    
    Missing return Int

And that, for MyClass.getBits and MyClass.setBits ...
 I read the documentation and discover `external`, to apply like that if I understand :

    abstract Make(Void) {
        @:external public inline static function Unfinished(name:String="") throw AbstractError.Unfinished(name);
    }

But it change nothing... So why it work on Try Haxe and not on my computer ? Do I make a mistake ?

Also, even that doesn't work : 
  
        public function setBits(pos:Int, value:Int, size:Int, signed:Bool=false):Int throw "error";

Or it mean to do, am I wrong ?

  [1]: http://pastebin.com/x4Fsi47U
  [2]: http://try.haxe.org/#AA334

**Comment by Simn** [comment]
What Haxe version are you on locally?

**Comment by Chlorodatafile** [comment]
Haxe 3.2.0. :) And even that doesn't work, so I think there is a big problem with the throw, do I made a mistake ?
![errorhaxe](https://cloud.githubusercontent.com/assets/10853006/8507069/31cbae72-2233-11e5-8467-47c88a46f0e2.png)

**Comment by Simn** [comment]
I don't know, but your example works for me locally on 3.2.0.

**Comment by Chlorodatafile** [comment]
What's your OS ? Personnaly I use Xubuntu 14.10. (I know, it's bad, I will put Debian 8 Cinnamon soon)
I've try for Neko, Linux and Linux 64, and everytime I get the same error. I run with OpenFl also, but I don't think it's the reason of everything. :/

**Comment by Simn** [comment]
I'm on Windows, but the OS doesn't matter here. I'm afraid I cannot help you further unless you can provide an example that fails to compile with just Haxe (no OpenFL etc.).

**Comment by Chlorodatafile** [comment]
I've just try without OpenFL, with that Main.hx : 

    package ;
   
    class Main {
         static public function main():Void {
             new MyClass().getBits(1,2,false);
         }
    }
    
    interface MyInterface {
        public function getBits(pos:Int, size:Int, signed:Bool=false):Int;
    
        public function setBits(pos:Int, value:Int, size:Int, signed:Bool=false):Int;
    }
    
    class MyClass implements MyInterface {
        public function new() {}
    
        public function getBits(pos:Int, size:Int, signed:Bool=false):Int Make.Unfinished("getBits");
    
        public function setBits(pos:Int, value:Int, size:Int, signed:Bool=false):Int Make.Unfinished("setBits");
    }
    
    enum AbstractError {
        Unfinished(name:String);
    }
    
    abstract Make(Void) {
        public inline static function Unfinished(name:String="") throw AbstractError.Unfinished(name);
    }

And it doesn't work neither, and I've use the Haxe compiler, and nothing else ...
Obviously I've try it without OpenFL to see, if I see that it only happend with OpenFL, I wouldn't knock there about the problem. ;) But it's not the case, so what the problem ?

**Comment by Simn** [comment]
Can you run `haxe -version` so we can be sure you're on 3.2.0?

**Comment by Chlorodatafile** [comment]
It looks that I'm at 3.1.3, or I've updated 2 days ago, something definitely go wrong during the installation, I remove and reinstall, and see if it correct something. :)

**Comment by Chlorodatafile** [comment]
Ok, I reinstall Haxe, and now everything work fine, so thanks you very much for the help, I wouldn't find without your recommandation ! Have a nice day. :)
