### ISSUE TITLE
Haxe 3.2 regression: switch on String type is optimizing too agressively

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#4387]
Consider this example:

```
class Statics
{
    public static var one : String = "one";
    public static var two : String = "one";
    public static var three : String = "one";
}


class Foo
{
    public static function main()
    {
        var s : String = "two";

        Statics.two = "two";
        Statics.three = "three";

        switch (s) {
        case Statics.one:
            trace("one");
        case Statics.two:
            trace("two");
        case Statics.three:
            trace("three");
        }
    }
}
```

The haxe 3.1.3 compiler properly compiles this; but haxe 3.2 does not and instead produces this error:

<pre>
bji/bug_demo$ haxe -cpp Foo-cpp -main Foo -lib mockatoo
Foo.hx:22: characters 13-24 : This pattern is unused
Foo.hx:24: characters 13-26 : This pattern is unused
</pre>

Apparently the compiler is assuming that the initial value to which the static variables Statics.one, Statics.two, and Statics.three, are assigned to, are the values that should be used in place in the switch statement, and since they all are initialized to the same value, the switch ends up with unused cases (all apparently matching "one").

Because the values in Statics.one, Statics.two, and Statics.three can all be changed at runtime, and the switch expression is supposed to compare against the runtime values, the compiler should not be attempting these optimizations.

If Statics.one, Statics.two, and Statics.three were declared inline, then the optimization would be valid, but they are not, and so, the optimization is wrong.

**Comment by Justinfront** [comment]
I don't see the problem, compiler is assuming you should deal with all 
possible Strings, so you need to add '_' to catch ones not delt with eg:

http://try.haxe.org/#1f205

**Comment by bjitivo** [comment]
That's not the error reported at all.  It's reporting that the case statements are redundant, because it believes that they are all the same value since they are all initialized to "one".  But they can and do change at runtime and the compiler should not be performing this optimization.

**Comment by Simn** [comment]
This is strange, but I'm surprised this would compile at all in 3.1.3. Usually you're only allowed to use constant patterns, which would require the field to be `inline`. I'll check what's going on.

**Comment by bjitivo** [comment]
Hm, it was never my understanding that case patterns had to be constants; I had assumed that the compiler would detect non-constant case patterns and turn them into the equivalent of if/else expressions.  That's exactly how the 3.1.3 compiler treated case expressions as it turned out.

**Comment by Simn** [comment]
That must have been only incidental, probably a relic from Haxe 2 days when case patterns were a bit more lenient.

**Comment by ncannasse** [comment]
I wonder if we couldn't turn non constant patterns to  `case _ if( _ == expr ):`

**Comment by Simn** [comment]
Maybe, but guards tend to make the output bloated...

**Comment by Simn** [comment]
This was originally caused by my fix for #4084, which is invalid for non-inline fields.

**Comment by fzzr-** [comment]
This is unexpected behaviour because `Statics` isn't `Enum` or `@:enum abstract` or because fields are not inlined.

**Comment by Simn** [comment]
This gives `Constant expression expected` errors now as it should. I'll wait and see how much existing code this breaks. If it has too much of an impact we can think about doing what @ncannasse suggested, though I can guarantee that it's not going to lead to pretty output code in many cases.

**Comment by Simn** [comment]
It's been 10 days and my house is still standing, so I suppose this is alright once #4680 has been addressed.

**Comment by bjitivo** [comment]
It's my assumption that until the change is available in a release version of haxe, you won't really know how much code it "breaks".  As for us, it is several dozen instances, but I fixed them all already.
