### ISSUE TITLE
Type parameters and @:from

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#4389]
Hi,

my example: http://try.haxe.org/#11080
it doesn't work since type parameters aren't available to static functions, I know

but since @:from functions do an instantiation couldn't the type be resolved?
in the example the types are known, it needs to build an abstract `Either<String, Int>`since that's what the function requires

so doing a "backpropagation" or something it should be possible to make the link between the `L` of the function and the `L` of the abstract, right?

Note that I'm unfamiliar with the way the compiler does that kind of things, so I may be vastly underestimating the complexity of what I'm asking.

**Comment by Simn** [comment]
Just add the type parameters to your function. I can't see any sensible semantics for them being available like you suggest.

**Comment by ibilon** [comment]
I don't think it would make sense to have a `@:from` function itself to have parameter,
bear in mind that maybe what I'm asking don't make sense either,
I just feel like the compiler should get what I mean by `L` since the way I see it `@:from` functions are closer to constructors, which can use the abstract type parameter, than static functions.

**Comment by sledorze** [comment]
is this your intend? http://try.haxe.org/#0Ce68

**Comment by ibilon** [comment]
@sledorze thanks!
It didn't worked when I tried but I must have typed something wrong.

I'm glad it works, but now I'm confused as to how since the names of the type parameter of fromLeft and fromRight doesn't have to match the ones of the abstract.

**Comment by sledorze** [comment]
these are static functions, you believe that because they're defined in the abstract they would know about the type parameters; but keep in mind, like with classes, that type parameters are bound to an 'instance', and that this 'instance' context does not exist in a static function.

**Comment by ibilon** [comment]
@sledorze Yeah but aren't `@:from` functions static only to avoid introducing another keyword,
since it would be less characters to have `from function ()` than `@:from static function ()` and pointless to call them yourself.

Well anyway, this issue was more about getting a functionality, which apparently exists, than to discuss the way abstract are defined.

**Comment by sledorze** [comment]
You confused Either and haxe.ds.Either in some places.
Also the type params of the created abstract (static just return a new abstract) are just know when callind the 'new' function.

**Comment by ibilon** [comment]
@sledorze Yeah I realized that afterward, modified the link in my first post.

If return type can be inferred you could assume that type parameters could be too, but it seems not, which may be logical or not (didn't really look into the consequences of such a thing)

**Comment by sledorze** [comment]
Keeping 'static' is more consistent with the rest of the language semantic.
I think you're confusing 'static' and 'non static' functions, the abstract type parameters only exist in context of the latter.
S in the static case; L or R are bound to nothing is not provided as parameter of the static function.
Can't really help more, reread on need.. :)

**Comment by ibilon** [comment]
No I completely get why static functions don't have access to the abstract type parameters, wouldn't make sense. I'm just questioning the need for `@:from` functions to be static and inherit this limitation.

Putting that aside, abstract aren't going to change now,
the last thing I wanted to know was how `t("a")` and `t(4)` find the right fromX function,
but I guess the fromX functions unify somehow with the expected type of the `t` function.

**Comment by ibilon** [comment]
Sorry to repost here, just found how to articulate my original thought.

For me `@:from` functions simply are overloads of a polymorphic constructor, and if you see them that way (which isn't that far fetched at all) then it make complete sense to have access to the abstract type parameters.

Anyway I'll adapt my views on them and think of them in the haxe way ;)
