### ISSUE TITLE
Can not use datetime on Android

### ISSUE THREAD

**Issue by ocpear** [HaxeFoundation/haxe#4391]
I has installed datetime on haxe (haxelib install datetime) to get timezone offset. It run ok on Neko. But when I run on Android (lime test android), it runtime error. What's wrong?
Please help me. 
Thanks.

import datetime.Timezone;
class DateHelper 
{
    public function getTimeZone():Void{
        trace(Timezone.local().getOffset(DateTime.local()));
    }
}

**Comment by Simn** [comment]
You may want to report that to the library in question.

**Comment by Justinfront** [comment]
probaby not related but may provide a clue ? https://github.com/nmehost/acadnme/issues/2

**Comment by ocpear** [comment]
I had asked library for this issue. But he said that, this issue may be haxe.crypto.Base64 does not work on Android.
https://github.com/RealyUniqueName/DateTime/issues/13#issuecomment-120654519
