### ISSUE TITLE
Allow object constraints on @:generic to work with abstracts

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4392]
It would be nice for [this](http://try.haxe.org/#62001) to work:

```
class Test {
    static function main() {
        foo(new Foo('foo'));
    }
    @:generic static function foo<T:{ var length(get, never): Int; }>(v:T) {
        
    }
}

abstract Foo(String) {
    public var length(get, never):Int;
    inline function get_length() return this.length;
    public function new(s) this = s;
}
```

Currently it doesn't, because abstracts and objects don't unify. But since the function is generic and `T` is known at compile time, could we not make an exception?

**Comment by Simn** [comment]
I don't think this would work with our implementation. We don't type each generic variant individually, but instead type it once and then expression-map it for each instance. This wouldn't really respect the treatment abstract types require.

**Comment by back2dos** [comment]
Ok, I understand. I assume that's largely because it's faster? If so, could you not add an extra case, if unification between the parameter and its constraints failed and the parameter is an abstract, that actually does the individual treatment? That should not impact any existing code in any way and would only be "expensive" in this special case.

What I actually would like would be to write code against "anything arrayish". This feels like it's halfway there. But also halfway not there, so maybe it's just a stupid idea to start with.

**Comment by Simn** [comment]
Looking at it again I still don't see how we could get this working with the current implementation of `@:generic`.

**Comment by back2dos** [comment]
I know it's less than trivial to keep all issues organized, but could we please reopen this one? I think it would give us the possibility to write adapters free of runtime overhead.

```
@:generic function processBytes<T:{ var length(get, never):Int; function get(index:Int):Int; }>(bytes:T) { ... }
```

And one can write abstracts to serve as adapters for `js.node.Buffer`, `js.html.ArrayBuffer`, `haxe.io.Bytes`, `haxe.ds.Vector<cpp.Int8>` and whatever native types one might bump into, all without having to introduce the overhead of wrapper objects.

This would expand on the power of abstracts to facilitate writing well factored code without sacrificing performance where it matters. I understand if this is not a priority now, but I would really love to see it being supported eventually.

**Comment by Simn** [comment]
This is never going to work unless we completely revise how `@:generic` is implemented, so there's really no point in reopening this issue. I have some ideas for a syntax-AST-based approach to this but that's not really related to `@:generic` either.

**Comment by back2dos** [comment]
Ok, I see.

**Comment by Simn** [comment]
Actually it might be possible to combine `@:generic` with my [`@:astSource`](https://github.com/HaxeFoundation/haxe/commit/a44caafc8bb36b178e34eb84db74694b24bc43c6) approach. If we have the original source on a `@:generic` function then we can type its specialization properly. This would not only deal with abstracts but also with inlining like in #3663.

However, that still doesn't change the fact that abstracts and structures don't unify.

**Comment by back2dos** [comment]
> However, that still doesn't change the fact that abstracts and structures don't unify.

Yes, I get that. Please note that I am not asking for abstracts to unify with structures. I want them to be applied as type parameters constrained to structures and in my mind these are two quite different things. In my little happy place, where typing can also be done *after* type parameter application, there is no need to unify the abstract with the constraint. Because of prior typing, we know that the body is "structurally compatible" with the constraint. If the abstract fails to unify with the constraint (i.e. by means of implicit conversion), but is "structurally compatible" (assuming that this can be determined with justifiable effort), then applying it as a type parameter and retyping the body against the concrete type should yield valid code.

In my head this is really bolted on *after* failed type parameter application, if the parameter is generic and the concrete type is an abstract - and it only ever happens in that particular context. It should not affect unification in any way. Anyway, I don't want to drag out this discussion. It just seemed to me that either my idea is just stupid or that I did a poor job trying to explain it and I wanted to eliminate the latter possibility ;)
