### ISSUE TITLE
C# target over-allocates in various circumstances

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#4393]
In a variety of circumstances the C# target allocates significantly more garbage than one would hope. This issue is a way of gathering these in one place so they can be addressed together.
1. Static closures currently require bind() to be called on them or they end up in a very dynamic invocation, which costs tons of allocation and is slow
2. Non-static closures cost a lot of allocation/speed every time they are called
3. Conversion of Float to String costs significantly more allocation than expected (possibly due to Mono runtime's implementation of BitConverter or something like that)
4. Generic function types `(e.g. sort<T>(a:T, b:T, comparator:T->T->Int))` cost allocation when called, possibly only in conjunction with closures, unless @:generic is set on them or they are fully inlined
5. Calling non-static methods via reflection seems to always generate garbage (e.g. `Reflect.field("methodName")(someParam);`)
6. Std.is appears to be quite slow, not sure about Std.instance

**Comment by waneck** [comment]
1. Static closures won't need bind() when #4297 is solved
2. All closures always go through `invokeDynamic`. This is indeed a problem right now. We could have specialized invoke functions for each number of arguments, but this will generate even more reflection wrappers. I'm not sure what the balance of speed/code size should be
3. Oh? Any examples? What would be expected?
4. The only way I can see this solved is if we somehow find a way to generate Haxe functions as delegates. There are some problems with that and the Haxe type system. cc @nadako

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
