### ISSUE TITLE
[php] Implementation of Compress.run()

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4394]
This should work:
```haxe
public static function run( s : haxe.io.Bytes, level : Int ) : haxe.io.Bytes {
	var c = untyped __call__("gzcompress", s.toString(), level);
	return Bytes.ofString(c);
}
```

**Comment by Simn** [comment]
Pull request?

... with tests? :D

**Comment by kevinresol** [comment]
I am not sure how to add code in this case, should I create a file like so: `std/php/_std/haxe/zip/Compress.hx`?

**Comment by kevinresol** [comment]
And where should the test file go? I am not very familiar with the file structure of the haxe repo :stuck_out_tongue:
