### ISSUE TITLE
neko Utf8.compare is broken

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4396]
Given the following code all platform succeed except for neko that returns -1 for all cases.

```haxe
Assert.equals(-1, haxe.Utf8.compare("a", "b"));
Assert.equals( 0, haxe.Utf8.compare("a", "a"));
Assert.equals( 1, haxe.Utf8.compare("b", "a"));
```

**Comment by ncannasse** [comment]
This was fixed a long time ago https://github.com/HaxeFoundation/neko/commit/558b415fdaf839be1b4c5dd34aac1676379c3d7d
