### ISSUE TITLE
[js] invalid JS generated for Float (Number) member methods

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4397]
Consider this example:
```haxe
using Test;

class Test {
    static function main() {
        0.toFixed();
    }
    
    static inline function toFixed(f:Float):String {
    	return (cast f).toFixed();
    }
}
```
The following generates `0.toFixed();` in the JS output which is invalid according to e.g. Chrome. I think we can wrap constant number expressions in parenthesis when accessing their fields (`(0).toFixed();`)

**Comment by Simn** [comment]
That reminds me of PHP!

**Comment by Simn** [comment]
Oh, there is a case for this in genjs already. The problem here is that there's a TCast in the way.
