### ISSUE TITLE
analyzer substitute initial variable value

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/haxe#4399]
http://try.haxe.org/#89c92

repro:
```
class Test {
    static function main() {
        trace(foo(2));
    }
    
    static var array:Array<Int> = [1,2,3,4,5];
    
    static function foo(value:Int):Int {
		var i:Int = 0;
		var m:Int = 0;
		while(i < array.length) {
			if(array[i] == value) {
				m = i;
			}
			++i;
		}
		return m;
	}
}
```

generated code:
```
(function (console) { "use strict";
var Test = function() { };
Test.main = function() {
	console.log(Test.foo(2));
};
Test.foo = function(value) {
	var i = 0;
	var m = 0;
	while(i < Test.array.length) {
		if(Test.array[i] == value) m = i;
		++i;
	}
	return 0;
};
Test.array = [1,2,3,4,5];
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

look at `return 0`
also reproduced for flash and etc...

**Comment by malec-palec** [comment]
Looks very dangerous and critical thing.

**Comment by Simn** [comment]
Solution: Don't use the analyzer.

I'll probably remove it for 3.3, there are too many issues with it anyway.

**Comment by eliasku** [comment]
bug is produced only when `var m:Int = 0`
`var m:Int;` and `var m:Int = {!=0}` - OK.

We are not use analyzer on production environment. There is no reason to remove analyzer at all (it's not enabled by default), I've created this bug just for sharing the issues. I hope that many of them can be wrapped by tests and we'll have stable strong analyzer.

**Comment by 7-by** [comment]
@eliasku you can try to use `@:analyzer(ignore)` for ingore this method from checking by analyzer or `@:analyzer(no_const_propagation)`
also #3938 looks like current issue

**Comment by back2dos** [comment]
@Simn Isn't that a bit of a drastic measure?

**Comment by Simn** [comment]
Perhaps, but this shows a fundamental problem with how variables in loops are treated. Implementing the analyzer was a bit of a learning process for me and I don't think the structure we ended up is going to be robust.

**Comment by back2dos** [comment]
I understand. I'm looking forward to see the future fruits of your learnings ;)
