### ISSUE TITLE
haxe.Resource.getString throws exception for inexistant resource

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4400]
Subj. However docs say it should return `null`. Looks like we don't have it tested, so maybe it's not only C#.

**Comment by nadako** [comment]
Ok, I fixed C#, but there's also a problem in PHP

**Comment by nadako** [comment]
And python.

**Comment by nadako** [comment]
Fixed Python. Could someone look into PHP as I don't have interpreter installed?

**Comment by nadako** [comment]
Thanks!

**Comment by andyli** [comment]
You're welcome :)
