### ISSUE TITLE
[hxcpp/neko] haxe.Timer does not have a constructor

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4401]
```haxe
class Main {	
	static function main() {
		var t = new haxe.Timer(100); // haxe.Timer does not have a constructor
	}
}
```

Tested with 3.2.0 and nightly marked as 2015-07-10 16:21.

Works for [js/swf](http://try.haxe.org/#9228b).

I seem to recall this working correctly, so maybe I'm doing something utterly wrong... any ideas?

**Comment by azrafe7** [comment]
Oh, and git hxcpp if it can be of help.

**Comment by Simn** [comment]
From the documentation: `The Timer class allows you to create asynchronous timers on platforms that	support events.`

**Comment by azrafe7** [comment]
Ouch... didn't know that.Sorry for the hassle.
