### ISSUE TITLE
Update documents about license

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/haxe#4402]
Neko has relicenced under The MIT License, but some documents haven't been updated.
http://haxe.org/foundation/open-source.html
[People concerning about license often hesitate to adopt Haxe](http://www.gamedev.net/topic/669947-is-haxe-used-much-professionally/), so to clearfy the neko runtime is not used for gaming consoles binary but compiler toolchains would be nice.

**Comment by Simn** [comment]
That's more of an issue for https://github.com/HaxeFoundation/haxe.org
