### ISSUE TITLE
Method not found where method is present

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4404]
In complex case Haxe lost child methods when parent class processed by build macro which load any module (even empty).
Haxe compiler show error like "method of the child class does not exists", but tracing inside macro show it exists. Beside that, compiler's autocompletion works great and show me all methods in FlashDevelop.
The problem appear in Haxe 3.2.0.

**Comment by yar3333** [comment]
Minimal code to reproduce: http://haqteam.com/LostChildMethodsBug.zip
Old haxe has a bug like this (https://github.com/HaxeFoundation/haxe/issues/2117), which I can workaround by adding constructors manually. But I don't see how to workaround the current bug. So all my complex projects is not compilable with 3.2.0. @ncannasse, please help!

**Comment by Simn** [comment]
This has got to be some compiler pass problem, so this is going to take a while to investigate.

**Comment by Simn** [comment]
A bisect suggests that this was fixed by https://github.com/HaxeFoundation/haxe/commit/eca310.

I suppose this is one of the cases @ncannasse was after.

**Comment by Simn** [comment]
Maybe we should add this as a misc-test.

**Comment by Simn** [comment]
Also it's funny how the issue number of a "not found" bug ends in 404.
