### ISSUE TITLE
allow methods on abstract T(Void) as long as `this` is not used

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4405]
The following currently fails to compile with the `Arguments and variables of type Void are not allowed` error:
```haxe
abstract Some(Void) {
    public inline function doStuff() {
        trace("Hello");
    }
}
```
However I think it makes sense to allow these methods to compile if they don't use `this` in their body.

PS: WRT usefulness, I have a (rather crazy) case where I'd like this to work. I worked-around that by making that abstract underlying type `Int` for now.

**Comment by gloomybrain** [comment]
@nadako why not just `static inline` methods instead?

**Comment by Simn** [comment]
I'm also not convinced that this is useful. The error is totally consistent considering abstract lifting, so I don't see why we should add a special case for `Void` here.
