### ISSUE TITLE
In C# if the first parameter of an enum is null, Type.createEnum fails

### ISSUE THREAD

**Issue by lpetre** [HaxeFoundation/haxe#4407]
For example: http://try.haxe.org/#0E205

That works fine on most platforms, but fails in C# with this:
Unhandled Exception:
Constructor NullParam needs parameters

I believe it is because this line: https://github.com/HaxeFoundation/haxe/blob/development/std/cs/_std/Type.hx#L199

Checks to see if the first parameter of the params array is null, which is strange.

**Comment by lpetre** [comment]
It looks like the array length used to be checked, but that was replaced with the null check for some reason here: https://github.com/HaxeFoundation/haxe/commit/ffb34803

**Comment by waneck** [comment]
Oh my. I have no idea why that was there, but it being there is clearly an error. Thanks!

**Comment by lpetre** [comment]
Thanks!
