### ISSUE TITLE
Allowing compatible types in arguments/return values of the overriden methods

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4408]
Most modern languages support this, but not Haxe:
```haxe
class A {}
class B extends A {}

class BaseTask                   {          function f() : A return null; }
class ChildTask extends BaseTask { override function f() : B return null; }
```

**Comment by andyli** [comment]
It is allowed, at least with 3.2.0.
example: http://try.haxe.org/#83e1C

**Comment by yar3333** [comment]
You right, bad example. Next example not work:
```haxe
class A {}
class B extends A {}

class BaseTask                   {          function f(p:A) : Void {} }
class ChildTask extends BaseTask { override function f(p:B) : Void {} }
```
http://try.haxe.org/#9773D

**Comment by Gama11** [comment]
That's explained [here](http://haxe.org/manual/class-field-override-effects.html):

> argument types allow contravariance (less specific types)

`B` in your example is a *more* specific type.

**Comment by Simn** [comment]
That shouldn't work because function arguments are contravariant, not covariant.

**Comment by yar3333** [comment]
You right, my bad.
