### ISSUE TITLE
invalid inlining of conditions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4410]
This snippet:
```haxe
class Main {
    static function main() {
        var a = 1, b = 2;
        (function() {
            if (a > b) {
                trace(1);
                if (a == 1)
                    return;
                trace(2);
            }
            trace(3);
        })();
    }
}
```

Generates:
```js
Main.main = function() {
	var a = 1;
	var b = 2;
	if(a > b) {
		console.log(1);
		if(a == 1) null; else console.log(2);
	} else console.log(3);
};
```

The third trace should always be called unless `(a > b && a == 1)`. This is reproduced without (as well as with) analyzer and it seems to be present in haxe 3.2.

**Comment by Simn** [comment]
That's the inline `if` rewriting @ncannasse implemented years ago.

**Comment by nadako** [comment]
Right, it's not actually about self-calling closures, but about inline in general (which is even more depressing):
```haxe
class Main {
    static var a;
    static var b;

    static function main() {
        f();
    }

    static inline function f() {
        if (a > b) {
            trace(1);
            if (a == 1)
                return;
            trace(2);
        }
        trace(3);
    }
}
```

```js
Main.main = function() {
	if(Main.a > Main.b) {
		console.log(1);
		if(Main.a == 1) null; else console.log(2);
	} else console.log(3);
};
```

**Comment by nadako** [comment]
Haxe 3.0.1 doesn't compile this with the `Cannot inline a not final return` error.

**Comment by nadako** [comment]
Breaking commit: 21d8ba684e3d6b354ffa214df4c1ade75214e052, related to #2215

**Comment by nadako** [comment]
Could someone look into this please? It's really bad that it silently generates invalid code right now.

**Comment by ncannasse** [comment]
Wow, that was quite an overlook on my part, funny how it took so long to notice.
Please review the patch, it should restrict the terminal return detection to code that is always reachable

**Comment by Hypher** [comment]
@nadako I just tried this code on try.haxe.org, and just found that (possibly related) issue:
```
class Test {
    static function main() {
        trace('ret='+test(Math.random() > 0.5)); // right
        trace(test(Math.random() > 0.5)); // wrong
    }
    
    static inline function test(a:Bool):Int {
        if(a == true) return 42;
        else if(a == false) return 43;
        else return 44;
    }
}
```
The second trace call produces wrong javascript code.
I don't know if it's related, neither if try.haxe.org is up to date in regards to Nicolas fixes above. But I prefer to mention this defect. Sorry if it's already fixed.

**Comment by nadako** [comment]
@Hypher I can confirm this produces invalid code on current dev Haxe as well, but it's probably not related to this issue. Something seems to be wrong with the analyzer and trace. I'll open an issue for that, thanks!
