### ISSUE TITLE
Selective Functions on abstracts don't work anymore

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4411]
just try to compile the sample from here http://haxe.org/manual/types-abstract-selective-functions.html

it fails with: `characters 4-5 : Int should be MyAbstract<String>`

same for haxe 3.2 see: http://try.haxe.org/#f16A7

```haxe
abstract MyAbstract<T>(T) from T {
  public function new(t:T) this = t;

  function get() return this;

  @:impl
  static public function getString(v:MyAbstract<String>):String {
    return v.get();
  }
}

class Main {
  static public function main() {
    var a = new MyAbstract("foo");
    a.getString();
    var b = new MyAbstract(1);
    // Int should be MyAbstract<String>
    b.getString();
  }
}
```

**Comment by nadako** [comment]
But you don't have a function that takes MyAbstract<Int> there?

**Comment by nadako** [comment]
The error message is still confusing though.

**Comment by nadako** [comment]
Oh, I read the manual, and it actually describes that it shouldn't compile. So what's the issue?

**Comment by frabbit** [comment]
sorry, you're totally right ;).

it seems that the abstract itself as first param is only allowed with type params, right? Because this doesn't compile: http://try.haxe.org/#f16A7

**Comment by frabbit** [comment]
btw. how can i enable static completion for an impl function, see: http://try.haxe.org/#4495c
