### ISSUE TITLE
static completion for abstract @:impl functions

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4412]
there is no static completion for an impl function, see: http://try.haxe.org/#4495c

```haxe
abstract TeamId (Int) {
	public inline function new (x:Int) this = x;


	@:impl static public function toInt (x:Int):Int
	{
		return 0;
	}
    
    static public function foo ():Void
	{
		return 0;
	}
}

class Test {
  static public function main() {
    
    TeamId.| // only completion for foo at this point
  }
}
```

**Comment by Simn** [comment]
As with #4413 `@:impl` should not be used manually.

**Comment by frabbit** [comment]
@simn so what's the alternative? This doesn't work either http://try.haxe.org/#Ab7d2

**Comment by Simn** [comment]
Why make it static in the first place?

**Comment by back2dos** [comment]
@Simn This is why: https://github.com/HaxeFoundation/haxe/issues/4413#issuecomment-122009691

That said, I am not sure it is worth the trouble. You can just use a static extension, that you can also call through the class itself.
