### ISSUE TITLE
@:impl on selective functions

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#4413]
is it by intention that this doesn't compile?

``` haxe
abstract TeamId (Int) {
    public inline function new (x:Int) this = x;


    @:impl static public function toInt (x:TeamId):Int
    {
        return 0;
    }
}

class Test {
  static public function main() {

    TeamId.toInt(new TeamId(1));
  }
}
```

**Comment by frabbit** [comment]
btw. my motivation is to use `toInt` as both instance and static method like:

```haxe
new TeamId(1).toInt();
passFunc(TeamId.toInt);
```

**Comment by Simn** [comment]
`@:impl` should not be used manually. We should change it internally so it doesn't parse.

**Comment by back2dos** [comment]
That's in discord with the spec: http://haxe.org/manual/types-abstract-selective-functions.html

**Comment by Simn** [comment]
The documentation is wrong anyway. The first argument type must be the underlying type, not the abstract.

**Comment by back2dos** [comment]
True. However, that's an issue of the documentation, not the language, I would say. 

I don't quite get what you are suggesting. Selective functions currently preclude the possibility to use `@:impl` manually and I'd say they are a really nifty feature.

OTOH I'm not really sure what @frabbit is doing here has anything to do with *selective* functions to start with. So I guess one could say that it *is* by intention that the code above does not compile.

**Comment by frabbit** [comment]
I would have actually prefered that selective static functions (not @:from and @:to) behave more like auto using, wasn't it like that some time ago??

**Comment by frabbit** [comment]
@back2dos you're right about that, selective functions are just a special case of a static impl functions on abstracts.

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/HaxeManual/issues/227
