### ISSUE TITLE
return this; fails when returning constraint parameter

### ISSUE THREAD

**Issue by adrianmm44** [HaxeFoundation/haxe#4415]
http://try.haxe.org/#8a466

**Comment by Simn** [comment]
These recursive constraints always cause me a headache. @ncannasse: Should this compile or not?

**Comment by ncannasse** [comment]
it should compile, but I'm not sure how much we can support this

**Comment by frabbit** [comment]
i guess this is related: https://github.com/HaxeFoundation/haxe/issues/4012

**Comment by Simn** [comment]
Right, it's the same issue.

**Comment by back2dos** [comment]
@ncannasse It should not compile. See the comment https://github.com/HaxeFoundation/haxe/issues/4012#issuecomment-129426463 and the following.
