### ISSUE TITLE
@:rtti extern class  fail

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#4416]
I want to add @:rtti to extern class for js target ,but throw some error

@:rtti extern class MyPerson  {
	public var 	name:String;
	
}
0): Error: Class MyPerson has no RTTI information, consider adding @:rtti

**Comment by sonygod** [comment]
use @:rtti @:extern class instead ,that's fixed.

**Comment by Simn** [comment]
This combination doesn't make much sense. Where would the RTTI information be put for an extern class?
