### ISSUE TITLE
Array of structs in macro

### ISSUE THREAD

**Issue by MSGhero** [HaxeFoundation/haxe#4417]
Related to #4196 @Simn. This time, it's an array of imbalanced structs (in a macro) instead of a map literal of structs. Tested on git haxe.

The json string
```
{
  "foo": [
	{
	  "a": 6,
	  "b": 1,
	},
	{
	  "a": 9,
	}
  ]
}
```

inside of a build macro with `Context.parseInlineString(string)` throws an error
```
test:7: lines 7-9 : Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>
test:7: lines 7-9 : { a : Int } should be { b : Int, a : Int }
test:7: lines 7-9 : { a : Int } has no field b
```

Build macro, unimportant stuff removed:
```haxe
{

var string = ( see above );
	
var o = Context.parseInlineString(string), Context.makePosition({ min : 0, max : 0, file : "test"}));

var a = [ { expr : EBinop(OpArrow, macro $v{"test"}, o), pos : Context.currentPos() } ];
		
var nf:Field = {
	kind : FVar(macro : haxe.ds.StringMap<Dynamic>, { expr : EArrayDecl(a), pos : Context.currentPos() } )
    // etc
};

fields.push(nf);
return fields;
}
```

**Comment by back2dos** [comment]
You just need to specify the right type, i.e.: http://try.haxe.org/#c7a51

So the following should work:

```
var a = macro ["test" => ($o : { foo:Array<{a:Int,?b:Int}>})];//the (<expr> : <type>) is ECheckType which is used to hint/force types at compile time
```

Or if you just want to go untyped, then why not use `EUntyped`?

**Comment by MSGhero** [comment]
The json is inside of a string (json file) that's being parsed at compile time. I can't specify the type because the incoming json file could have any structs inside of it and inside of its arrays.

This seems like the issue with 4196, it wasn't ignoring/unify_min-ing the type.

**Comment by back2dos** [comment]
If you don't care about the type (which your `StringMap<Dynamic>` seems to indicate), then why not just use `untyped`?

**Comment by MSGhero** [comment]
Because I'm not sure what that does lol. It looks more like a hack than a solution, but I'll try it later.

**Comment by back2dos** [comment]
Is it? It seems that you are writing untyped code to start with, so it's a perfect match. Why bother getting the compiler to infer the right type, if you're going to erase it anyway?

**Comment by MSGhero** [comment]
So the contents of the macro run fine (I can successfully get a `Log.trace` out just before returning) thanks to the solution from 4196. I don't need `untyped` there, but I tried it anyway and got the same error.

The typing (and thus the error) occurs AFTER or WHEN the macro returns the updated build fields. I'm not sure where I could put `untyped` in
```haxe
@:build(Macros.buildJSON())
class Files {
```

**Comment by Simn** [comment]
Why are we talking about macros here?

**Comment by MSGhero** [comment]
The issue only comes up (as far as I can tell) in macros. A regular array of structs works fine, but it errors when that array is added as a new field to a class based on the code I provided.

**Comment by MSGhero** [comment]
I should add, it's likely because you can't type an array to `Array<Dynamic>` when it's a field of a struct from inside a macro like I'm doing.

**Comment by MSGhero** [comment]
Weird little exception:
```
{
  "foo": [
    {
      "a": 6,
      "override": 1,
    },
    {
      "a": 9,
    }
  ]
}
```
works fine. In fact, "override" doesn't even show up as a field when I trace the struct, but I can still use reflection to get to it.

**Comment by Simn** [comment]
This is the same as #3132. I don't think it has anything to do with macros.

**Comment by MSGhero** [comment]
Regardless, it's still broken. That was closed in Feb, and my haxe version is from the middle of June.

This specific issue occurs in `Context.parseInlineString()` during macro execution where my array isn't being typed down to `Array<{}>`.

**Comment by MSGhero** [comment]
If anyone comes across this, there's an EUntyped exprdef that solves the problem of not being able to type the arrays directly. Good to know.
http://stackoverflow.com/questions/33907716/array-typing-issue-in-build-macro
