### ISSUE TITLE
Type.createInstance different results on different targets.

### ISSUE THREAD

**Issue by Disar** [HaxeFoundation/haxe#4420]
**Empty args:**

Passing an empty array  for the args parameter, even though the class has no default constructor, seems to be ok for targets Javascript and C++ ( tested Windows/Android-NDK).

On Java and Flash they hard crash with a null pointer exception.

**Java doesn't like null**

createInstance for Java doesn't like it when one of the args items is null.

Test case:

	package;

	class Main
	{

		public function new() {
			var test:TestCase = Type.createInstance(TestCase, []);
		}
		
		static function main() {
			new Main();
		}
		
	}

	class TestCase {
		public function new(x:Int,y:Int,test:TestCase = null,name:String) {
			trace(x);  // unidentified in javascript, but no crash
			trace(y);
			trace(test);
			trace(name);
		}
	}

**Comment by waneck** [comment]
The constructor expects four arguments but you're passing none to it. You
may want to look at Type.createEmptyInstance instead

**Comment by Disar** [comment]
I'm well aware of that. However I didn't know this was an issue until I tried Java.

But ill look into the createEmptyInstance then. The null parameter still breaks though.

**Comment by Simn** [comment]
This function is [documented](http://api.haxe.org/Type.html#createInstance) to require sane numbers and types of arguments, else the result is unspecified.

**Comment by Disar** [comment]
Passing a null parameter for args like [0,0,null,"name"] makes java crash though. I don't see anything about this in the docs.

**Comment by waneck** [comment]
@Disar , can you please include a reproducible example where this crash happens on Java?

**Comment by Disar** [comment]
package;

	/**
	 * ...
	 * @author Sidar Talei
	 */
	class Main
	{

		public function new() {
			var test:TestCase = Type.createInstance(TestCase, [0,0,new MyClass(),"sss"]);
		}
		
		static function main() {
			new Main();
		}
		
	}


	class TestCase {
		public function new(x:Int,y:Int,test:MyClass = null,name:String) {
			trace(x);
			trace(y);
			trace(test);
			trace(name);
		}
	}
	
	
	class MyClass {
		public function new(){}
	}

prints:
    Main.hx:23: 0
    Main.hx:24: 0
    Main.hx:25: haxe.root.MyClass@11d50c0
   Main.hx:26: sss

This runs fine, but when you then try this:

       var test:TestCase = Type.createInstance(TestCase, [0,0, null,"sss"]);

Java prints out:

C:\Users\Sidar\Documents\programming\haxe\creatinstancetest>java -jar Java/Main.jar
	in thread "main" java.lang.NullPointerException
        at haxe.root.Type.createInstance(Unknown Source)
        at haxe.root.Main.__hx_ctor__Main(Unknown Source)
        at haxe.root.Main.<init>(Unknown Source)
        at haxe.root.Main.main(Unknown Source)
        at haxe.root.Main.main(Unknown Source)


As for your early suggestion using createEmptyInstance for using null parameters. This worked on java, but then broke html5 and C++ builds ( on run time ). So I've resorted back to createInstance using [] for args. Even though it shouldn't work, it works for C++ targets and html5.

fyi I'm using Kha to build my project. I could try make a small isolated case for createInstance vs createEmptyInstance .
