### ISSUE TITLE
[cpp] Multi-dimensional Array fails to assign value when using generics

### ISSUE THREAD

**Issue by stbachmann** [HaxeFoundation/haxe#4424]
Found an odd bug. A multi-dim array created by the following method does not assign values on cpp targets:

```
static function CreateArray2dWithValue<T>(width:Int, height:Int, value:T):Array<Array<T>>{
        var array2d = [];

        for(i in 0...height) {
            var row = [];
            for(j in 0...width) row.push(value);
            array2d.push(row);
        }

        return array2d;
    }
```

Full working example to reproduce the bug: 

```
class Test {
    static function main() {
	var a = CreateArray2dWithValue(2,2,9);
        trace(a[0][0]);
        a[0][0] = 1;
        trace(a[0][0]);
        trace(a);
    }
    
    static function CreateArray2dWithValue<T>(width:Int, height:Int, value:T):Array<Array<T>>{
        var array2d = [];

        for(i in 0...height) {
            var row = [];
            for(j in 0...width) row.push(value);
            array2d.push(row);
        }

        return array2d;
    }
}
```

Expected output:
```
Main.hx:63: 9
Main.hx:65: 1
Main.hx:66: [[1,9],[9,9]]
```

Actual output on cpp target:
```
Main.hx:63: 9
Main.hx:65: 9
Main.hx:66: [[9,9],[9,9]]
```

Note: Adding a @:generic to the method makes this work as expected. I've tested this on js target as well, and the output is correct there without the generics annotation. Fun times :)

**Comment by MSGhero** [comment]
This might be #4187, which is more than just cpp. We found out it actually doesn't have to do with `inline` like I initially thought. I didn't try adding the `@:generic` tag because that causes dozens of lines of annoying output in FD.
