### ISSUE TITLE
[js] `@:selfCall` is not defined When passed as an argument

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#4425]
```haxe
class Main {
    static function main() {
		var zoom = new Zoom();

		zoom.selfCall();

		D3.call(zoom.selfCall);      
	}
}

extern class D3 {
	static function call(func:haxe.Constraints.Function):Void;
}

extern class Zoom {
	function new();	
	@:selfCall function selfCall():Int;
}
```
generated javascript:

```js
Main.main = function() {
	var zoom = new Zoom();
	zoom();
	D3.call($bind(zoom, zoom.selfCall));  // zoom.selfCall is undefined in extern class
};
```

**Comment by andyli** [comment]
For info, [`d3.behavior.zoom()`](https://github.com/mbostock/d3/wiki/Zoom-Behavior#zoom) is a pretty interesting type that its instances are callable...
Maybe we can allow extern types to do weird things like `implements Void->Void`...? Or I feel the need of `extern abstract` :P

**Comment by Simn** [comment]
I'm not familiar with `@:selfCall` at all. What should this do?

**Comment by ncannasse** [comment]
ping @nadako https://github.com/HaxeFoundation/haxe/commit/bae7da509003bdfd9e241fe1c6688a72bbbadd61

**Comment by nadako** [comment]
I'll have to look at it later :-P
