### ISSUE TITLE
support of ||=

### ISSUE THREAD

**Issue by andytwoods** [HaxeFoundation/haxe#4427]
Dear Haxers,
any chance of implementing support of the AS3 conditional set value operator?:  ||=
With best wishes,
Andy.

PS as discussed here: https://groups.google.com/forum/#!topic/haxelang/_2E05AFCSP0

**Comment by Simn** [comment]
We could potentially make it parse but I don't want to support it in the typer. Boolean operators have special semantics with regards to short-circuiting which would cause confusion here.

**Comment by back2dos** [comment]
@Simn: so what about parsing it?

**Comment by ashes999** [comment]
How do other people who port code from AS3 to Haxe deal with this?

**Comment by nadako** [comment]
`a ||= b` to `a = a || b`? However I think in most cases in AS3 this require special handling anyway as haxe has no implciit type coercion between boolean and e.g. empty strings and people in as3 tend to use this for null/undefined/emptystring values (e.g. `arg ||= "default"` to `if (arg == null) arg = "default"`.

**Comment by back2dos** [comment]
@ashes999 First, they complain a lot. Eventually they just accept the way things are and move on ;)

@nadako Well, the list of falsy values is quite extensive unfortunately. But with parser support, the implicit coercion could easily be added through macros.

**Comment by fullofcaffeine** [comment]
> ... have special semantics with regards to short-circuiting which would cause confusion here.

@Simn Can you elaborate with an example showing how it would confuse users?

**Comment by andytwoods** [comment]
Don't think many AS3ers use that shortcut. Prob not worth the effort :) Am liking a = a || b !

**Comment by nadako** [comment]
@fullofcaffeine `var a ||= f()`  < should `f()` be called if `a` is true? If not, it can lead to unobvious issues where one expects side-effects to be applied from the `f` call, if yes, then it can lead to unnecessary side-effects/overhead from calling `f`.

**Comment by back2dos** [comment]
@nadako I'm not sure I follow. What part of this reasoning would not apply to `a = a || f()`?

**Comment by nadako** [comment]
Well, you may be right about that. To me however, left-associative OR is pretty expected, but assignment is right-associative so it's a bit confusing when we merge those.

**Comment by fullofcaffeine** [comment]
@Simn As @back2dos mentioned, it would be nice to parse it so a macro could be added for those who like this syntax.

**Comment by Simn** [comment]
@ncannasse: Do you see any reason against allowing this to parse and making it error in the typer?

**Comment by ncannasse** [comment]
I'm fine with parsing it

**Comment by MSGhero** [comment]
I get mad when I try to ||= in haxe, but I'm slowly accepting it.

If someone does make a macro, `a ||= f()`, `f` doesn't get called if `a` is true.

**Comment by fullofcaffeine** [comment]
I'm sure that, once it's parseable, our macro wizard @Juraj would add it to
Tink :)
