### ISSUE TITLE
Enum-matching in haxe.unit.TestCase

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4428]
What are you think about an `assertEnum` or `assertMatch` method for [haxe.unit.TestCase](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/unit/TestCase.hx)

I wrote this draft: [gist.github.com/fzzr-/8909b3d3a8de1ade4096](https://gist.github.com/fzzr-/8909b3d3a8de1ade4096#file-testcase-hx-L96). See `assertMatch` method.

Currently I use it in all my tests and all works fine.

**Comment by Simn** [comment]
Let's keep haxe.unit as simple as possible. It's not really intended to be a full-featured unit testing framework anyway.
