### ISSUE TITLE
Conditional compilation flag vs. docs?

### ISSUE THREAD

**Issue by raould** [HaxeFoundation/haxe#4429]
I don't understand #if vs. what is in [the documentation](http://haxe.org/manual/lf-condition-compilation.html), what am I doing wrong? thanks.

    haxe -js out -main Util
    Util.hx:13: characters 7-9 : Unexpected ||

and if you remove nowSecondsB() then nowSecondsC() will give an error.

```Haxe
package;

class Util {
  public static inline function nowSecondsA():Float {
#if js
    return Date.now().getTime()/1000;
#else
    return Sys.time();
#end
  }

  public static inline function nowSecondsB():Float {
#if js || flash
    return Date.now().getTime()/1000;
#else
    return Sys.time();
#end
  }

  public static inline function nowSecondsC():Float {
#if flash || js
    return Date.now().getTime()/1000;
#else
    return Sys.time();
#end
  }
}
```

**Comment by raould** [comment]
Oh. Uh, well, it works if I put them inside parentheses. Maybe the docs should point that out as being required, not optional I guess.

**Comment by back2dos** [comment]
The documentation is somewhat misleading. You need to put || in parentheses, otherwise it is interpreted as `#if flash` then `|| js` which of course makes no sense.

**Comment by raould** [comment]
Ah yup, it would be a nice thing for the docs to get updated. I guess it is no longer a wiki thing, rather requires a full fork-clone-edit-pullrequest loop? I'll try to do that.

**Comment by jasononeil** [comment]
@raould you can hit "Contribute to this page" in the footer, and it will take you to the exact place in the manual on Github.  From there you can click "Edit File" which will let you edit online and do a whole pull request for you.

(The manual is written in Latex, so if you feel uncomfortable you can just create an issue on the HaxeManual repo)

**Comment by raould** [comment]
https://github.com/HaxeFoundation/HaxeManual/pull/181
