### ISSUE TITLE
[php] EReg#replace and $

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4430]
It is documented and [unit tested](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/EReg.unit.hx#L90-L97) how `$n` works in [`EReg#replace`](http://api.haxe.org/EReg.html#replace). But somehow, it fails with the case as follows:
```haxe
class Test {
	static function main():Void {
		var re = ~/a(b)c/g;
		trace(re.replace("abcabc", "$1")); // should be "bb", but php target gives "$1$1"
	}
}
```

Tested with haxe 3.1.3 and dev. For php version, I'm using
```
PHP 5.3.28 (cli) (built: Jul 12 2014 15:36:06) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2013 Zend Technologies
```

**Comment by Simn** [comment]
This seems to happen only when there's a group with a single character. The following works:

```haxe
class Main {
	static function main():Void {
		var re = ~/a(bc)/g;
		trace(re.replace("abcabc", "$1"));
	}
}
```

This is the same as #4657, someone just has to figure out what's going on in `EReg.replace`.

**Comment by mockey** [comment]
> This seems to happen only when there's a group with a single character.

Ah, good catch. Now I think I know, what's wrong. Will make a PR.
