### ISSUE TITLE
Crash in bytes.setInt32 on Neko

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4433]
Using Haxe 3.2, the following code causes a crash on Neko:

```haxe
var bytes = Bytes.alloc (4);
bytes.setInt32 (0, 0x4BFFFFFF);
```

It must be because it crosses the 31-bit boundary (0x3FFFFFFF)

**Comment by ncannasse** [comment]
This has been fixed on Neko GIT already ;)
