### ISSUE TITLE
js.html.DedicatedWorkerGlobalScope is not properly exposed

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4435]
In creating a web-worker, It's my understanding that we should be able to do:

``` haxe
DedicatedWorkerGlobalScope.onmessage = function(input) { ... };
```

In Haxe 3.2, I get

```
Class<js.html.DedicatedWorkerGlobalScope> has no field onmessage
```

which it does according to the documentation and code (https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/DedicatedWorkerGlobalScope.hx).

I don't think it's related but the scope types are all exposed natively by their name, which is incorrect.

``` haxe
@:native("DedicatedWorkerGlobalScope")
```

should probably be 

``` haxe
@:native("self")
```

**Comment by Simn** [comment]
That field is not static, so either you're using the API wrong or the API is wrong.

**Comment by explorigin** [comment]
Well this is a tough question.  The browser creates the instance and exposes it as `self` in the worker context.  From a developer (Haxe) perspective, only the instance is visible (it is not possible to arbitrarily create our own instance).  The API is correct from a browser perspective but wrong from a Haxe perspective.  I think it makes sense to change it to this:

```haxe
@:native("self")
extern class DedicatedWorkerGlobalScope extends WorkerGlobalScope
{
	static var onmessage : haxe.Constraints.Function;
	
	/** @throws DOMError */
	function postMessage( message : Dynamic, ?transfer : Array<Dynamic> ) : Void;
}
```

**Comment by aduros** [comment]
We might want a "self" field in js.Browser that exposes the worker global object, similar to how the "window" field exposes the window global object.

**Comment by Simn** [comment]
@haxiomic Can we close this?

**Comment by haxiomic** [comment]
I think @aduros's idea is a good approach – let's add a new field to `js.Browser` to represent the global scope in a worker context

Created PR #8505
