### ISSUE TITLE
inconsistent treatment of module class and classes in the same file as the module class when Using-by-proxy

### ISSUE THREAD

**Issue by makoConstruct** [HaxeFoundation/haxe#4437]
take the following example

ImportByProxySuccess.hx
```
using A;

class Main{
  var b:B;
  static public function main(){
    trace("runs fine");
  }
}
```

ImportByProxyFailure.hx
```
using A;

class Main{
  var b:BAssociate;
  static public function main(){
    trace("does not run");
  }
}
```

A.hx
```
using B;
```

B.hx
```
class B{}
class BAssociate{}
```

ImportByProxySuccess will compile, but ImportByProxyFailure will not. I would prefer both to work, I would not be surprised if neither worked, but I am astonished to find that one works and the other does not.

**Comment by Simn** [comment]
There is no proxy behavior at all here, the first one simply works because the compiler can find B.hx when looking for `B`. Even if you remove `using A` this is going to work.
