### ISSUE TITLE
libneko.so is missing from the haxe distribution

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/haxe#4438]
I downloaded the haxe package from http://haxe.org/download/file/3.2.0/haxe-3.2.0-linux64.tar.gz
Then I used tar to extract the archive to folder haxe-3.2.0

haxe
Haxe working fine

haxelib
./haxelib: error while loading shared libraries: libneko.so: cannot open shared object file: No such file or directory

find . -name libneko.so
Not able to find the library in the haxe-3.2.0 folder. That means: linux haxe package seem to be broken.

**Comment by Simn** [comment]
Haxe and neko are different things so the Haxe binaries should not come with neko files. Refer to https://github.com/HaxeFoundation/haxe.org/issues/75 and linked issues for more discussion on the subject.
