### ISSUE TITLE
[macro] Context.eval - what typing context used for it?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4443]
Subj. Because it seems that `macro` is not defined there and the following doesn't work (I think it should, no?):
```haxe
class Main {
    static function main() {
        trace(f());
    }

    static macro function f() {
        return haxe.macro.Context.eval(macro Main.f2)();
    }

    #if macro
    static function f2() return macro 1;
    #end
}
```

**Comment by Simn** [comment]
This is actually quite concerning, using a wrong context for typing is a disaster waiting to happen.

**Comment by Simn** [comment]
I had another look at this but I can't figure it out right now. Changing it to use the right context causes other errors, and addressing these ultimately lead to the compiler throwing "hd" at me.

I'll remove Context.eval for the time being and maybe look at it again in the future.

**Comment by nadako** [comment]
Hmm, too bad. I think i have used it somewhere already...

**Comment by nadako** [comment]
Should this be closed though?

Also, I remember I have caught the `hd` even without `Context.eval`, so this might not be related. I'll try  finding and reducing that case.
