### ISSUE TITLE
[python] using FileOutput.writeInt32() gives "AttributeError: bigEndian"

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4444]
Test code:

``` haxe
    var file = "output.bin";
    var output = sys.io.File.write(file, true);
    output.writeString("BM");
    output.writeInt32(0x0a0b0c0d); // <- here
    output.close();
```

python 3.3 & haxe 3.3 (@a2de181)

**Comment by azrafe7** [comment]
It seems that adding `self.bigEndian = True` directly to `python_io_NativeOutput.__init__()` method solves this particular issue.

But I really don't know how `__slots__` and inheritance play into this, and if it's a proper fix.

**Comment by nadako** [comment]
I added explicit `bigEndian` init to the NativeInput/NativeOutput constructors, however I remember genpy adding default `None` initializers for fields, but now it doesn't do that. Any idea why @frabbit?

**Comment by frabbit** [comment]
should be fixed, feel free to reopen if something is not working as expected.
