### ISSUE TITLE
Using inlined constants inside metadata

### ISSUE THREAD

**Issue by pshtif** [HaxeFoundation/haxe#4447]
Atm something like this doesn't work:

@mymeta(MyClass.CON)

Even if the MyClass.CON is inlined, so I have to use string values directly which is a pain when used all over the place and makes refactoring even worse.

**Comment by Simn** [comment]
Metadata expressions are never typed so there's no way to support inlining. We could only support this if we added typed metadata and as far as I remember that's not currently on the agenda.

**Comment by nadako** [comment]
Actually, I think @waneck had a proposal (and maybe even some implementation) regarding typed metadata. I think this would be a nice addition to the language, but it needs to be properly designed and implemented.

**Comment by filt3rek** [comment]
Hej !

Is there any news about that or it will never be implemented ?

**Comment by nadako** [comment]
I think typed metadata will be implemented at some point, but it's not in the nearest plan. You'll have to macro-process the meta for the time being, I'm afraid.
