### ISSUE TITLE
null enum instances case runtime errors in switches without null cases

### ISSUE THREAD

**Issue by ProPuke** [HaxeFoundation/haxe#4449]
see: http://try.haxe.org/#0cb31

With lines 14 and 15 commented a runtime error occurs on all targets.

I would expect `default` to include null as a possible value, but it is not until a `case null` is added, that the additional null check is performed to make the switch safe.

When unsafe is appears that haxe is still trying to read the "index" property of the enum, even when it is null. When a `case null` is added an additional null check is compiled in just before the switch case in order to ensure safety.

To me `default` includes **all** unspecified cases, *including* null. So the current behaviour feels unexpected. This also causes some slight code duplication as you can't write `case null|default:`. So if you want the same behaviour in both cases you must duplicate code or use additional logic.

**Comment by Gama11** [comment]
Regarding the code duplication: you could write `case null|_:`.

**Comment by ProPuke** [comment]
Ahh, cheers. That feels a bit better

**Comment by Simn** [comment]
Null-checks have to be explicit like everywhere else. We shouldn't make an exception for pattern matching because that would add unnecessary null-checks in a lot of places. This implies that `default` does not catch null-values.
