### ISSUE TITLE
C#: Date.now().getTime() returns a very high (wrong) value.

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4452]
Running:

```haxe
trace(Date.now().getTime());
```

I get a very high value `63573890701981.7` whereas other platforms return values around `1438315513162`.

**Comment by fponticelli** [comment]
Also `Date.fromTime()` seems to expect the same huge timestamp to work correctly and doesn't work with epoch times.

**Comment by nadako** [comment]
Yeah, it returns `Datetime.Ticks / TimeSpan.TicksPerMillisecond` which is number of ms since 12:00:00 midnight, January 1, 0001 which is A BIT earlier than unix epoch.

**Comment by nadako** [comment]
We should think of a way to test this.

**Comment by fponticelli** [comment]
Yes, just figured it out: https://github.com/HaxeFoundation/haxe/blob/development/std/cs/_std/Date.hx#L43
It is missing the epoch difference.

The way I tested it is adding a macro version of Date that is generated by neko and use that as a reference. It is not perfect but at least it keeps the platforms consistent.

**Comment by fponticelli** [comment]
Same problem here: https://github.com/HaxeFoundation/haxe/blob/development/std/cs/_std/Date.hx#L106

**Comment by fponticelli** [comment]
Now that I think about it there are two big drawbacks with my test solution, it needs to be tolerant and it only works if you just compiled the tests (at least for testing `now`). It might still work for some fixed dates.

**Comment by nadako** [comment]
I've pushed a fix for that, please test. I'm leaving this issue open because we want some kind of unit-testing for that and also I don't really understand how we specify timezone-related behaviour in Date and timestamps, I'm sure there are some issues related to that, but we gotta specify it first (cc @ncannasse).

**Comment by nadako** [comment]
@waneck there's something wrong in the `TestSpod` test now and I'm not sure what exactly (https://travis-ci.org/HaxeFoundation/haxe/jobs/75222293#L882)

**Comment by nadako** [comment]
Oh, actually this is a breaking change since e.g. Haxe Serializer use getTime/fromTime, but I guess we have to break it. We gotta check if it returns a true unix timestamp (UTC) though

**Comment by nadako** [comment]
Okay, I found and fixed the SPOD problem.

**Comment by nadako** [comment]
> this is a breaking change since e.g. Haxe Serializer use getTime/fromTime

Actually this also means that Date won't properly deserialize if serialized from other target. I think we should add some inter-target tests for things like serializing, remoting, etc.

**Comment by nadako** [comment]
I think the original issue is fixed here
