### ISSUE TITLE
php / postgre

### ISSUE THREAD

**Issue by yannsucc** [HaxeFoundation/haxe#4453]
What about support PostGre Database using SPOD ?

i only find this : 

https://groups.google.com/forum/?hl=en#!searchin/haxelang/postgre/haxelang/9ZFMeU0TdmY/PIZ6n0qjmUoJ

thx !

**Comment by yannsucc** [comment]
no news ? :'(

I'm really impatient that this feature is available on Haxe core ! :)

**Comment by Simn** [comment]
I'll go ahead and close this because these feature-request issues never go anywhere. I see that you've opened a pull request, which is the right approach in general.
