### ISSUE TITLE
[macro] Multiple @:build-macros doesn't work anymore.

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4454]
The following code used to run both `@:build`-macros, but now only runs the second one:
```haxe
#if !macro
@:build(Main.build1())
@:build(Main.build2())
#end
class Main {
    #if macro
    static function build1() {
        trace("Build1");
        return haxe.macro.Context.getBuildFields();
    }

    static function build2() {
        trace("Build2");
        return haxe.macro.Context.getBuildFields();
    }
    #end

    static function main() {
    }
}
```

Bisected to b5f326300654e58f20b2a0acc951e35779535d8d

**Comment by nadako** [comment]
This one is rather annoying. Could it be addressed sometime soon?

**Comment by MSGhero** [comment]
I'm going to have a celebratory cpp compile tonight.

**Comment by bendmorris** [comment]
![muchrejoicing](https://cloud.githubusercontent.com/assets/544977/11276850/a729deb0-8e98-11e5-9c06-f2c7a3443016.gif)

**Comment by nadako** [comment]
yay!
