### ISSUE TITLE
Reserved identifier prefix

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4462]
As discussed in #4246, it would be really nice to have a reserved identifier prefix like `__hx__`. This would allow us to generate stuff without worrying about naming clashes.

IMO this also opens some possibilities for implementing things like autogenerated get/set methods (i.e. `var v(return _v, return _v = _)` could autogenerate `function __hx__get_v() return _v;` and `function __hx__set_v(_) return _v = _;`). Or even operator overloading for classes.

**Comment by frabbit** [comment]
a double underscore is not a perfect prefix for python because of it's special meaning: https://www.python.org/dev/peps/pep-0008/#method-names-and-instance-variables

**Comment by nadako** [comment]
yeah we should take that into consideration, however this issue is more about the general idea.

**Comment by back2dos** [comment]
What exactly would "reserved" mean? That it doesn't parse? Or that its is not valid in the untyped AST at all? Or even not valid in the typed AST?

As for `var v(return _v, return _v = _)`, that is a matter of allowing it in the parser. The methods must be named `get_v` and `set_v` anyhow.

Given that `$` is not valid in identifiers in Haxe, I think it would make a good prefix that the backends could then just generate as they see fit. In most cases it could just leave the `$` as is. In PHP I think you can just use some other unicode character instead?

**Comment by nadako** [comment]
I'd say it should not be vaild in the untyped AST.

As for the property get/set, this was more about Haxe 4, I guess. Maybe I'm wrong, but I have the idea that methods aren't implicitly generated anywhere because of possible name clashes. That preserves us from e.g. implementing method/operator overloading or autogenerating get/set methods from a shorter syntax (like above). But if we had a reserved prefix, I think we could deal with this, add more features and make syntax nicer.

Speaking of properties, it would actually be great to support arbitrary expressions for `FProp`, that would allow implementation of shorter property syntax by macros.

**Comment by Simn** [comment]
I'm in favor of reserving `_hx_` as a prefix.

**Comment by Simn** [comment]
Ok, let's reserve `_hx_` by convention. I don't want to start detecting and erroring on it because that's a lot of annoying work for not really much of a benefit.

I have documented it accordingly: http://haxe.org/manual/expression.html
