### ISSUE TITLE
Incorrect argument behaviour when function is inlined 

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#4463]
*Tested on C++, JS, and Neko targets*
*Tested with release version 3.2.0 and nightly 9990279 (04/08/2015)*
*Tested with -D analyzer on and off, as well as all dce levels*
(Bug persists in all tests)

See this try.haxe for demo: [#1bcd2](http://try.haxe.org/#1bcd2)

If a unary operator is applied to the one of the arguments of an inlined function, it can affect other arguments in unexpected ways.

For example with
```` haxe
someInlinedFunction( i , i++ ); 
```

if `i` is 0, we expect the function to receive arguments `0, 1`, however instead it receives `1, 0` when it is inlined. (Removing the inline qualifier gives the expected behavior).

Does anyone know for sure if the haxe spec defines execution order in arguments? Looks like [C++ doesn't](http://stackoverflow.com/questions/621542/compilers-and-argument-order-of-evaluation-in-c), so I guess this might technically not be well defined behavior.

Explanation
-----
Say we have some function
````haxe
inline function add(a:Int, b:Int){
    return a + b;
}
````

when called like so:
````haxe
var i:Int = 0;
add( i, i++ );
````

the generated js looks something like

````javascript
var i = 0;
var b = ++i;
i + b;
````

so because argument `a` gets replaced with `i`, and `i` is altered in the function call, argument `a` ends up being incorrect. Looks like there's a bug with detecting if the arguments need to be copied out or not.

**Comment by Simn** [comment]
This is the same as famous issue #1827.
