### ISSUE TITLE
PHP : array access to a function output is a bad PHP syntax

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe#4464]
Consider the following PHP code , which illustrates that an array access after a function is considered incorrect 
```
<?
// works fine
$arr = array("toto","tata");
echo $arr[0];

//dont work
function getArr(){
        return array("toto","tata");
}

echo getArr()[0];
```

It throws : 
```
PHP Parse error:  syntax error, unexpected '[', expecting ',' or ';' in /root/test.php
```

If I write it in the same way in Haxe, the generated PHP will follow the same structure which is bad : 

```
//haxe
return headers.get( name )[0];
```
gives
```
//php
return $this->headers->get($name)[0];
```

Obvisouly the workaround is to write it like this
```
var h = headers.get( name ); 
return h[0];
```

**Comment by back2dos** [comment]
That is only the case in PHP < 5.4:
http://stackoverflow.com/questions/1459377/access-array-returned-by-a-function-in-php

Given that PHP 5.3 was dropped completely by the PHP Group a year ago (
http://php.net/supported-versions.php), I think you might want to consider
an upgrade. Not only will it fix your issue, it will also increase your
security.

The haxe output should probably be changed to check against 5.4 (rather
than 5.1) in the index.php to avoid confusion. I suggest opening an issue
on the tracker.

Best,
Juraj

**Comment by back2dos** [comment]
I mean a separate issue, since it's kind of a big move, compared to the concrete technicality raised here.

**Comment by bablukid** [comment]
Looks like its not a "so big" move since the unit tests are already run on a PHP 5.4 : https://travis-ci.org/HaxeFoundation/haxe/jobs/74304463

**Comment by Simn** [comment]
This is the same as #4384.
