### ISSUE TITLE
unitialized local variables check

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4466]
There's something wrong with the uniniitalized locals check, for example:

```haxe
class Main {
    static function main() {
        var a;
        var b = a + 1;
    }
}
```

This errors on 3.2.0 WITHOUT `-D analyzer` with `Local variable a used without being initialized` error which is correct, however if we add `-D analyzer` it compiles. That is strange considering that `check_local_vars_init` seems to be run before the analyzer.

On current development branch this example compiles both with and withoud `-D analyzer`

**Comment by Simn** [comment]
Breaking commit is https://github.com/HaxeFoundation/haxe/commit/5978d0afd5050d6e45dea328bc2b29720fc0994b

I didn't remember that TFunction is also the enclosing expression of any function field. I wish we had a separate AST node for local functions so we don't have to manually detect them in every place.

**Comment by Simn** [comment]
A better solution altogether would be to still recurse into TFunction (we may want to detect legitimate uninitialized locals there) but ignore any captured variables. The problem with that is that the local vars checker runs before the var capturer and changing the order is way too risky.
