### ISSUE TITLE
js compat: need more careful way to define Uint8Array and same types

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4467]
I have a problem with external js lib, which tests a Uint8Array class existing. Result js:
```js
// inserted by haxe.macro.Compiler.includeFile("ExtLib.js"):
if (typeof Uint8Array === 'undefined') { ... } // Uint8Array is always undefined because next lines
...
// generated by haxe compiler:
var Uint8Array = (Function("return typeof Uint8Array != 'undefined' ? Uint8Array : null"))() || js_html_compat_Uint8Array._new;
```
May be a good solution to generate compatible code `Uint8Array = ... js_html_compat` before import raw js?

**Comment by yar3333** [comment]
Or just wrap haxe generated code into `(function() { ... })();` ?

**Comment by andyli** [comment]
`includeFile` will inject the file content outside of the haxe closure by default (#4419). Does that fix your use case?

**Comment by yar3333** [comment]
Thank you, @andyli, looks your fix is the solution.
