### ISSUE TITLE
Suggestion: Handle @:native for typedefs

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4472]
This is a very small thing. While typedefs do not necessarily produce any actual code specific for them, they do exist in context of JSGenAPI as `haxe.macro.Type.TType` and can be hinted in the resulting code for ease of reading and/or debugging.
Currently, however, `@:native` metadata has no effects with them, so
```haxe
@:native("other")
typedef Some = com.pkg.ClassName;
```
will still give you TType's with name == "Some".

**Comment by nadako** [comment]
Can't you extract `@:native` metadata from the `DefType` and process it as you wish in your custom generator?

**Comment by YellowAfterlife** [comment]
Yes, that's doable. A bit hacky, but better than nothing for the time being. Thanks!

**Comment by ncannasse** [comment]
typedef being just aliases that are in general entirely eliminated at compilation, I don't think it makes a lot of sense to be able to rename them.
