### ISSUE TITLE
switch case if statement condition

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4473]
I was trying to implement a guard and found something weird behavior: 

_The manual [states](http://haxe.org/manual/lf-pattern-matching-guards.html):_ 
> It is also possible to further restrict patterns with the `case ... if(condition):` syntax.

I try this but that does not seem to include the if-statement in the output:  (http://try.haxe.org/#cA9ca)

```haxe
        var scenes = ["home","contact"];
        var index = 4;
        var x = switch(scenes[0])
        {
                case "home" if (index < 2): 1; // output points to this, but index = 4 (?)
                case "home2" if (index >= 2): 2;
        }



```

Also it seems I cannot use "home" twice, in ideal case I'd like to have this (http://try.haxe.org/#aA3c6):
```haxe
        var scenes = ["home","contact"];
        var index = 4;
        var x = switch(scenes[0])
        {
                case "home" if (index < 2): 1;
                case "home" if (index >= 2): 2;
        }
//  "Duplicate constant in switch"
```
It gives me this error: "Duplicate constant in switch";

Shouldn't the first example give a compile error (invalid syntax or something) or should it work?
I am probably using this wrong but I don't see why?

**Comment by markknol** [comment]
After small investigation I think I found how it should be written (http://try.haxe.org/#1FE28):
```haxe
        var scenes = ["home","contact"];
        var index = 4;
        var x = switch[scenes[0], index]
        {
            case [a,b] if (a == "home" && b < 2): a;
            case [a,b] if (a == "home" && b >= 2): a;
            default: null;
        }
```
Still my question remains why the first code does compile but doesn't do anything.

**Comment by nadako** [comment]
Wow that first example surely looks like a bug. cc @Simn 

BTW, second example can be rewritten using extractors, but it currently generates quite a messy/ineffective code and IMO doesn't look good either:
```haxe
        switch [scenes[0], index] {
            case ["home", (_ < 2) => true]: 1;
            case ["home", (_ >= 2) => true]: 2;
            default: throw false;
        }
```

**Comment by markknol** [comment]
You are on a roll! Thanks!
