### ISSUE TITLE
`@:overload`ed methods ignore private/public access modifiers

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4479]
The following compiles, but it shouldn't, because an overloaded constructor that takes an Int argument is private. Also it shows in the completion which can be confusing for e.g `Array` which has a private constructor taking native array.

``` haxe
class A {
    @:overload private function new(a:Int) {}
    @:overload public function new() {}
}

class Main {
    static function main() {
        var a = new A(10);
    }
}
```

**Comment by nadako** [comment]
Seems to be related to #1856

**Comment by Simn** [comment]
I'm trying to figure out what's going on with `can_access`. It has an optional `in_overload` argument which is never used in any call. Also it always returns `true` for any field that has `@:overload` metadata.

**Comment by nadako** [comment]
This seems to be some unifinished check, related to methods that are loaded with `cf_public = false` while also having public overloads.

**Comment by RealyUniqueName** [comment]
Overload check in `can_access` is just a hack to always allow access on overloaded fields despite their access modifiers (`in_overload` is always `false`):
https://github.com/HaxeFoundation/haxe/blob/19167a20e9daa6060e5c5b7e7852b482fb1a5c43/src/context/typecore.ml#L328-L330
That hack should be removed. 
Instead we should pick correct overload and pass it to `check_constructor_access` here:
https://github.com/HaxeFoundation/haxe/blob/19167a20e9daa6060e5c5b7e7852b482fb1a5c43/src/typing/typer.ml#L1779-L1781
Currently `get_constructor` returns whatever constructor was typed first. It also contains all overloaded ctors in `cf_overloads`. Argument list for `new` call is also available in that scope.

**Comment by RealyUniqueName** [comment]
```haxe
class A {
    @:overload static private function method() {}
}

class Main {
    static function main() {
        A.method(); // No error
    }
}
```
@Simn probably a 4.0 priority?

**Comment by Simn** [comment]
It's a bit dumb but doesn't strike me as mega-urgent. But if you want to look into it, sure.

We should rewrite `can_access` to something sensible for 4.1 or so.
