### ISSUE TITLE
`haxe` always outputs to stderr

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#4480]
I expect `haxe` and `haxe --help` commands to output to stdout, but look at this:

```
$ haxe | wc -l
<Usage message >
0
$ haxe &2>1 | wc -l
[1] 5181
0
<Usage message>
```

The same with `haxe --help`

**Comment by Simn** [comment]
@ncannasse: Is there any reason it does that?

**Comment by ncannasse** [comment]
Seems like OCaml behavior with Arg.parse

**Comment by Gama11** [comment]
I just wasted half an hour trying to figure out why my method of checking the `haxe -version` output in Bash / Travis wasn't working...

```bash
if [[ $(haxe -version) == "3.2.1" ]];
```

Turns out, you need to redirect stderr for this to work...

```bash
if [[ $(haxe -version 2>&1) == "3.2.1" ]];
```
