### ISSUE TITLE
HTML - Uncaught TypeError: Cannot read property 'charCodeAt' of null

### ISSUE THREAD

**Issue by smks** [HaxeFoundation/haxe#4484]
haxe_xml_Parser.doParse = function(str,strict,p,parent) {
	if(p == null) p = 0;
	var xml = null;
	var state = 1;
	var next = 1;
	var aname = null;
	var start = 0;
	var nsubs = 0;
	var nbrackets = 0;
	var c = str.charCodeAt(p); (X Error)

![image](https://cloud.githubusercontent.com/assets/4087157/9288701/87d36b68-434c-11e5-9885-b75527f21882.png)

**Comment by back2dos** [comment]
Are you absolutely positive that `str` is what it says? Because the error
suggests the opposite. Maybe you could add a plain log statement right
there, to confirm the value.

**Comment by smks** [comment]
str is null. This is relating to parsing the Project.xml right?

**Comment by back2dos** [comment]
It's unclear what "Project.xml" you referring to. Without further context,
all I can say is that if you pass `null` to the XML parser, then you get a
null pointer exception. That is not a Haxe issue though ;)

**Comment by smks** [comment]
Okay it seems this may be to do with padding Sparrow Data, part of haxeflixel. Will close :)
