### ISSUE TITLE
[Macro] Can not read file more than 16MB in Macro

### ISSUE THREAD

**Issue by daisuda** [HaxeFoundation/haxe#4485]
I am not sure it is a bug or by design, because I haven't read so big file before. I googled but could not find any solution , so open an issue here.
e.g.
`sys.io.File.getContent("more than 16MB file's path here")`
evn: Haxe 3.2.0, neko 2.0.0

**Comment by andyli** [comment]
@ncannasse May be it is related to #3976?

**Comment by ncannasse** [comment]
That's a limit of OCaml Strings on 32 bit systems that only allows up to 16MB of data in a single string. Changing this will require some significant changes in the implementation of the macro interpreter.

**Comment by daisuda** [comment]
@ncannasse But I am sure I am in Windows 7 x64 platform. Is it because neko or haxe compiler is compiled by a 32 bit system? I download haxe installer from office website. I need rebuild haxe from source in an 64 bit system?

**Comment by back2dos** [comment]
@daisuda I suppose what this really means is that you probably shouldn't load the file all at once. Instead use `sys.io.File.open` and process the resulting stream.

**Comment by daisuda** [comment]
@back2dos Thanks advice. I think I should process these stream immediately, because connect string in memory over 16MB also throw error. :(

**Comment by back2dos** [comment]
Yes, that was my point. Whatever the file, try to write a streaming parser. A good example can be found in [hscript](https://github.com/HaxeFoundation/hscript/blob/master/hscript/Parser.hx).
