### ISSUE TITLE
Add fast-get method to Map

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/haxe#4487]
I bet a .fast-get('key') method would be an easy low-level addition to the haxe language that would speed up everyones code who's using most kinds of entity components systems for games. The difference between .fast-get & .get is that fast-get doesn't perform an if(!map.exists(key)) return null; internally.

**Comment by ncannasse** [comment]
Could you tell on which platform this exits check is done ? Usually every check done in std lib is done for good reasons, which means there might be issues if it's done otherwise.
