### ISSUE TITLE
haxe --display requires a valid file

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#4488]
The documentation (http://haxe.org/manual/cr-completion-overview.html) about `--display file@position[@mode]` indicates that `file` "does not respect any class paths or libraries".

**What does that mean?**

In any case it seems to enforce that the file is in the classpath, and that the file name respects the regular file restructions (must end with .hx, must start with an underscore).

**The problem**

As a service for editors, it is a bad user experience to have to save the file everytime the compiler has to be used: we really need a way to fix that without having to resort to adding a temporary classpath.

**Comment by yar3333** [comment]
This problem was discussed several times at past. Nicolas said, what to hard to implement processing file from memory. In my experience file saving on completion is unexpected behavior only, but not a big problem.

**Comment by elsassph** [comment]
What I'm asking is to write the file in a  temporary location or with a temporary hidden file.

**Comment by yar3333** [comment]
Philippe, why you think what adding a temporary classpath is bad solution?

**Comment by elsassph** [comment]
For one, manipulating the compiler arguments is always a bit risky, and second compiler completion requires the build and completion arguments are identical.

**Comment by ncannasse** [comment]
I don't really understand how it's a bad user experience to save a file, for instance it's already done when compiling. Any insight ?

**Comment by elsassph** [comment]
For me that's just abnormal and I don't understand why we have this limitation.

**Comment by kaikoga** [comment]
:+1: to Philippe. Everything you type might be everything you want to compile (in Haxe where you must compile for completions at least), but is NOT everything you want to have on your file system to get restored when you either exit and restart your editor another day, or say, have your editor just crash at random timing.

Requiring write access for completions may have more problems, if you want some completions in read only files, or files over slow network.

**Comment by Simn** [comment]
See #4651.
