### ISSUE TITLE
3.2 final breaks Javascript ContentSecurityPolicy because of fix for 4138

### ISSUE THREAD

**Issue by royag** [HaxeFoundation/haxe#4490]
producing (as in haxe 3.2):

var ArrayBuffer = (Function("return typeof ArrayBuffer != 'undefined' ? ArrayBuffer : null"))() || js_html_compat_ArrayBuffer;

instead of (as in haxe 3.2 RC):

var ArrayBuffer = typeof(window) != "undefined" && window.ArrayBuffer || typeof(global) != "undefined" && global.ArrayBuffer || js_html_compat_ArrayBuffer;

makes ContentSecurityPolicy consider this to be use of "unsafe eval".

This makes haxe-produced javascript incompatible with ContentSecurityPolicy.

Is there maybe a way to fix bug 4138 without resorting eval() ?

Or maybe one could have a parameter for switching between the two methods ?

**Comment by royag** [comment]
direct link to the other fixed bug: #4138

**Comment by andyli** [comment]
umm... This becomes tricky again.
I've just read about ContentSecurityPolicy. [The spec](http://www.w3.org/TR/CSP/#directive-script-src) says that `Function(...)` will throw an exception... even if we're passing a constant string, which cannot be modified by an attacker.
I will propose a fix for this.

**Comment by aduros** [comment]
Would this work everywhere?

```js
(function ($hxGlobal) {
    "use strict";
    // ...
})( (function () { return this; })() );
```

eval and the Function constructor should be avoided for perf reasons as well as CSP.

**Comment by aduros** [comment]
Paging Dr. @andyli :) This is a regression for environments that use CSP: Chrome Apps, Firefox OS, Tizen, possibly others.

The above snippet seems to work... but the "use strict" gets stripped by Closure Compiler which is probably bad. Replacing "use strict" with "use strict"+"" seems to trick Closure into not stripping "use strict" while still optimizing away the +"". I propose we could put that behind a -D js-closure-compiler flag or something.

**Comment by andyli** [comment]
I will try to find a solution this week...

For `"use strict"` being stripped, can you try adding `--language_in=ECMASCRIPT5_STRICT` as suggested by http://stackoverflow.com/a/6718756/267998?

**Comment by aduros** [comment]
Unfortunately that hoists the "use strict" line out of the closure, which breaks the `return this;` which needs to run in non-strict mode.

**Comment by andyli** [comment]
@aduros I've just committed a fix to the development branch (c6597aff78be5040d192f53ce01cffa52094c1ec). Would you check to see if there is any problem there?

I crafted the commit carefully that it can be cherry-picked by the haxe-3.2.1 branch, in case you want this in 3.2.1 release.

**Comment by royag** [comment]
My CSP-enabled application at least seems to work again with haxe_2015-09-07_development_2cc8237 . Thanks! :)

**Comment by aduros** [comment]
Looks good to me too, thanks Andy, you rock!

If possible, this would be great for us to have in 3.2.1.
