### ISSUE TITLE
Compilation cache server broken

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4493]
I'm now getting an error when using compilation server with latest Haxe + Evo2:

`Type name Math is redefined from module Math`

(as soon as I try to recompile it)
Lacking the time to investigate it now, will try to bisect when I have some time.
Anyway until fixed this is a showstopper for the release.

**Comment by Simn** [comment]
As a general note, the release that's supposed to go out soon it made off the branch https://github.com/HaxeFoundation/haxe/tree/haxe-3.2.1 which only has a few select changes from 3.2.0.
