### ISSUE TITLE
Int64 are not immutable

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4496]
```haxe
using haxe.Int64;

class Test {
  static function main() {
    var a : Int64 = 1,
        b : Int64 = a;
   	a++;
    trace(b);
  }
}
```

`b` should be `1` but it is `2`. I understand why that happens but is that the expected behavior? Also, will it produce the same result on targets that support native Int64?

Live sample here: http://try.thx-lib.org/#A5e72

**Comment by nadako** [comment]
I consider this a bug.

**Comment by ncannasse** [comment]
Indeed. We should not implement ++ as a mutation of `Int64.low`

**Comment by Herschel** [comment]
I agree, we should remove ++/--. I don't think you can implement ++ naturally with reference semantics. Any abstract type should probably be immutable if it is implemented with a reference type on some platforms and a value type on others.

**Comment by Herschel** [comment]
I had forgotten that you can modify `this` in an abstract! So this shouldmake ++ act properly:

```
	@:op(++A) private inline function preIncrement() : Int64 {
		this = make( this.high, this.low+1 );
		if( this.low == 0 ) this.high++;
		return cast this;
	}
```

**Comment by ncannasse** [comment]
@Herschel could you send a Pull Request ?
