### ISSUE TITLE
[python] trace should report the line number like all the other targets

### ISSUE THREAD

**Issue by catdawg** [HaxeFoundation/haxe#4497]
The trace in python currently translates to a normal print. To align it with the other targets it should be printing the haxe file and line number.

Minor issue, but I guess it should be fixed eventually.

example:
a trace should print:
```
Main.hx:7: the print
```
it currently just prints
```
the print
```

**Comment by nadako** [comment]
I think it's because single-argument trace calls are generated simply as `print(arg)` for the sake of minimalistic hello world code, similar to JavaScript.

**Comment by Simn** [comment]
Indeed, this is one of the hello-world optimizations we make. In any serious application you should get a proper trace. You can force it by adding `haxe.Log.trace = haxe.Log.trace` somewhere.

**Comment by dmitryhryppa** [comment]
Maybe this can be done with Haxe 4? 
Because Haxe 4 can generate line number as inline string so output may be just:
`print("MyApp.hx:4: Hello world!")`
