### ISSUE TITLE
creating many process in macro

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4498]
Our unit test (misc) is failing on OSX due to this issue. (https://travis-ci.org/HaxeFoundation/haxe/jobs/76415938)

Use `--interp` to run the example as follows:

``` haxe
class Test {
    static function main(){
        for (i in 0...100) {
            var p = new sys.io.Process("true", []);
            trace(i);
        }
    }
}
```

It will trace until 82, then error:

```
/usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx:96: characters 79-84 : Process creation failure : true
<builtin>:1: character 0 : Called from
/usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx:88: lines 88-124 : Called from
src/Test.hx:4: characters 11-41 : Called from
?:1: characters 1048575-8796094070782 : Called from
Aborted
```

The same code runs fine with the neko target.

**Comment by ncannasse** [comment]
It works on Windows, I suppose this is because we're reaching the maximum number of opened file descriptors. You need to call p.close() to make sure that the FD are released.

**Comment by andyli** [comment]
Indeed manually calling `p.close()` will fix the problem.
But does it make more sense to auto close it when the process exits?

**Comment by back2dos** [comment]
Even if you autoclose (which might be the case already), then that problem
will remain.

The loop doesn't wait for any of the processes to terminate, so it will
just attempt to spawn 100 processes - probably before the OS has managed to
begin executing the first one.

**Comment by andyli** [comment]
Same error if I explicitly wait for exit before creating new Process:
```haxe
class Test {
    static function main(){
        for (i in 0...100) {
            var p = new sys.io.Process("true", []);
            p.exitCode();
            trace(i);
        }
    }
}
```

**Comment by ncannasse** [comment]
Yes, waiting for the exitCode will not close the FDs, because you might still want to read the stdout/stderr after process termination. Only close() (or garbage collection in neko) will do.

**Comment by andyli** [comment]
Is it possible to do the same in macro? That is to close the descriptor during gc? If not, we have to document that close() should always be called. Note that there are some usages of Process in haxelib without calling close().
Anyway, maybe i should help specify and document the sys APIs once i completed the debian package task this month.

**Comment by ncannasse** [comment]
We can add a call to `Gc.finalize` to setup a finalizer, but that will not solve your issue since the GC doesn't get triggered when getting out of FDs.

**Comment by ncannasse** [comment]
It is correctly documented as "release all resources" in API. If you feel like adding more precise information, feel free to do it.
