### ISSUE TITLE
Abstract @:to forced on underlying type 

### ISSUE THREAD

**Issue by IlirLiburn** [HaxeFoundation/haxe#4499]
```haxe
abstract MyMap<T>(Int)
{
	public static var arr = [];
	public function new(t:T) { this = arr.push(t) - 1; trace("new " + this + ": " + arr[this]); }

	@:impl
	public static inline function key(i:Int) { trace("key: " + cast i); return i; }

	@:impl
	public static inline function set(i:Int, t:T) { trace("set " + i + ": " + t); arr[i] = t; }

	@:to
	public inline function get<C>() { var ret:C = cast arr[this]; trace("get " + this + ": " + ret); return ret; }
}
```
```haxe
		var t:MyMap<Dynamic>;
		t = new MyMap<Int>(10);
		trace("GOT " + t.key() + ": " + t);
		t.set(15);
		trace("GOT " + t.key() + ": " + t);
		t = new MyMap<String>("test");
		trace("GOT " + t.key() + ": " + t);
		trace(MyMap.arr);
```
Main.hx:215: new 0: 10
Main.hx:224: get 0: 10
Main.hx:218: key: 10
Main.hx:273: GOT 10: 10
Main.hx:221: set 10: 15
Main.hx:218: key: 10
Main.hx:275: GOT 10: 10
Main.hx:215: new 11: test
Main.hx:224: get 11: test
Main.hx:218: key: test
Main.hx:277: GOT test: test
Main.hx:278: [10,null,null,null,null,null,null,null,null,null,15,test]

The @:impl key() function requires Int as underlying type. At the place of a key() function call, @:to function call is forced additionaly. Is this a bug, or intended to be? Workaround?

**Comment by Simn** [comment]
I'm having trouble understanding what exactly it is you're reporting. Could you reduce this to the absolute minimum?

Also note that manually adding `@:impl` is probably not a good idea to begin with.

**Comment by Simn** [comment]
Closing due to lack of follow-up.
