### ISSUE TITLE
haxe compiler infinite loops on a class inheritence loop

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/haxe#4504]
Example file, Foo.hx, that demonstrates this:

```
class Foo extends Bar
{
    public static function main()
    {
    }
}

class Bar extends Foo
{
}
```

Output:
<pre>
$ haxe -neko Foo.n -main Foo
(runs forever)
</pre>

The 3.1 compiler infinite looped but just sat there doing apparently nothing.  The 3.2 compiler interestingly also infinite loops but grows in size continuously.

**Comment by Simn** [comment]
#4671
