### ISSUE TITLE
Escape analysis

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/haxe#4505]
Is there any form of escape analysis happening? I suppose there must be something going on for inline constructors?

All targets could benefit greatly from basic escape analysis. On JS, if objects do not escape the local scope, you can avoid creating unnecessary objects, sort of like the behavior of inline constructors. On CPP, objects could simply be allocated on the stack.

https://en.wikipedia.org/wiki/Escape_analysis#Optimizations

**Comment by nadako** [comment]
There's inlining of anonymous structures and arrays:
```haxe
class Test {
    static function main() {
        var a = {x: 1, y: 2};
        trace(a.x);
        trace(a.y);

        var b = [1, 2];
        trace(b[0]);
        trace(b[1]);
    }
}
```
generates:
```js
Test.main = function() {
	var a_x = 1;
	var a_y = 2;
	console.log(a_x);
	console.log(a_y);
	var b_0 = 1;
	var b_1 = 2;
	console.log(b_0);
	console.log(b_1);
};
```

**Comment by Simn** [comment]
As @nadako says this is addressed by inline constructors in Haxe.

**Comment by nadako** [comment]
Maybe the idea of the OP to make all constructors 'inline' automatically so the object is inlined if it doesn't escape?
