### ISSUE TITLE
[python] Resource.getBytes() converts LF into CRLF

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4506]
For example using [this file](https://www.dropbox.com/s/rzuscjkxfc7wde3/res.bin?dl=0) as resource, which contains `01 0A 02 0D 03 0D 0A 04` (8 bytes), and loading it through `haxe.Resource.getBytes()` will result in `01 0D 0A 02 0D 03 0D 0D 0A 04` (10 bytes).

The expansion doesn't happen if you manually create a `Bytes` var with the same content.

Tested on win 7 with nightly 3.3.0 (git build development @ 535ca4d).

**Comment by azrafe7** [comment]
It also works properly (i.e. without the unwanted expansion) when using `sys.io.File.getBytes()`.

**Comment by nadako** [comment]
It looks like genpy itself is reading file in text mode when creating the resource.
