### ISSUE TITLE
new Process("ver",["/?"]); 

### ISSUE THREAD

**Issue by tondy67** [HaxeFoundation/haxe#4509]
fall on windows (10)
Process creation failure : ver

* ver is a standard DOS command

**Comment by yar3333** [comment]
`ver` is a cmd command, not real *.exe. So correct code is: `new Process("cmd.exe",["ver","/?"]);`. This is not a Haxe bug.

**Comment by tondy67** [comment]
sorry, of course is a built-in command :)
