### ISSUE TITLE
[python] FileInput.readFullBytes() doesn't account for current reading position

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4510]
Using `FileInput.readInt32()` and then `FileInput.readFullBytes(dstBytes, 0, len)` it will not read from the 4th byte, but from the 0th one. It seems to work correctly with the other targets (including cs/java). I think I will have time to test it more tomorrow and hopefully submit a proper test.

PS: It might be worth investigating whether this problem is reproducible while calling other _similar_ functions (f.e. `readBytes`?).

**Comment by azrafe7** [comment]
For example reusing [this file](https://www.dropbox.com/s/rzuscjkxfc7wde3/res.bin?dl=0) as test, which contains `01 0A 02 0D 03 0D 0A 04`:

```haxe
	inline function bytesToHex(b:Bytes, ?len:Int):String {
		return "[" + [for (i in 0...b.length) StringTools.hex(b.get(i), 2)].join(",") + "]";
	}
	
	var fileInput = File.read("res.bin", true);
	fileInput.readInt32();
	var readBytes = Bytes.alloc(4);
	fileInput.readFullBytes(readBytes, 0, 4);
	trace(bytesToHex(readBytes));
```

traces `[01,0A,02,0D]` in python, instead of the expected `[03,0D,0A,04]` (which works correctly in cs/java/neko).

**Comment by Justinfront** [comment]
Hi this is a regression. 
This functionality worked 2 years ago see:
https://github.com/Justinfront/crossAWD2/blob/master/python/Awd2.py
In my case I can manually fix the problem in my output python code search for
```class python_io_NativeInput(haxe_io_Input):``` 
then modify the readBytes method by commenting out lines eg:
```
	def readBytes(self,s,pos,_hx_len):
		if (((pos < 0) or ((_hx_len < 0))) or (((pos + _hx_len) > s.length))):
			raise _HxException(haxe_io_Error.OutsideBounds)
		#if self.get_canSeek():
			self.seek(pos,sys_io_FileSeek.SeekBegin)
		#elif (pos > 0):
		#	raise _HxException((("Cannot call readBytes for pos > 0 (" + Std.string(pos)) + ") on not seekable stream"))
		ba = bytearray(_hx_len)
		ret = self.readinto(ba)
		s.blit(pos,haxe_io_Bytes.ofData(ba),0,_hx_len)
		if (ret == 0):
			self.throwEof()
		return ret
```
I presume there is a problem with 
```self.get_canSeek() ```?

Specifically the issues seems to be due to this change.

https://github.com/HaxeFoundation/haxe/commit/1fc64612c00aeabdd89b07da3a1a663fb48dce18#diff-15d5b05926e940bb7d302d620515ae34

I presume it needs to be reverted or fixed, is the canSeek changing the current file pointer position to the end of the file, I had a bit of a look, and tried experimenting with tell in the output, but just been ill so won't try to find a fix right now.

**Comment by Simn** [comment]
@frabbit or @nadako, could you take a look? It's not super-high priority because the breaking change has been in the 3.2 release anyway, but it would still be nice to get this fixed.

**Comment by nadako** [comment]
Wait what, why does it even tries to seek to a given `pos`? It should read from the current position and write INTO given one.

**Comment by nadako** [comment]
I _think_ i fixed it, but I might be missing something, so maybe @frabbit would like to review that.

**Comment by nadako** [comment]
Sorry it took so long!

**Comment by Justinfront** [comment]
Well I modified the output python to match your code and it works fine for me, will post the modification here incase it's simpler for someone to hand mod the output than upgrade.
```	
def readBytes(self,s,pos,_hx_len):
		if (((pos < 0) or ((_hx_len < 0))) or (((pos + _hx_len) > s.length))):
			raise _HxException(haxe_io_Error.OutsideBounds)
		ba = bytearray(_hx_len)
		ret = self.readinto(ba)
		if (ret == 0):
			self.throwEof()
		s.blit(pos,haxe_io_Bytes.ofData(ba),0,_hx_len)
		return ret
```
So for me it's all good.  But yep maybe the seek is for edge cases.
