### ISSUE TITLE
unable to pass argument -Da=b=c via Sys.command

### ISSUE THREAD

**Issue by jozefchutka** [HaxeFoundation/haxe#4512]
as already reported on https://groups.google.com/forum/?hl=en#!topic/haxelang/LsKynTHCPXg there are serious issues with argument escaping on windows, things are getting even worse with haxe 3.2.0 as the hack that worked in haxe 3.1.3 would not work anymore.

here is my simple testing ant file (build.xml):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project default="build">
  <target name="build"><echo message="${a}"/></target>
</project>
```

executed from command line `ant "-Da=b=c"` would output:
```
[echo] b=c
```

executing `Sys.command("ant", ["-Da=b=c"]);` outputs:
```
Target "c" does not exist in the project "null".
```

executing `Sys.command("ant", ["\"-Da=b=c\""]);` outputs:
```
Target ""-Da=b=c"" does not exist in the project "null".
```

executing `Sys.command("ant \"-Da=b=c\"");` compiled with haxe 3.2.0:
```
'"ant ""-Da=b=c"""' is not recognized as an internal or external command, operable program or batch file.
```

executing `Sys.command("ant \"-Da=b=c\"");` compiled with haxe 3.1.3 outputs expected:
```
[echo] b=c
```

**Comment by andyli** [comment]
Will be addressed in #3603.
