### ISSUE TITLE
[java] slowCallField fails on functions with boolean arguments

### ISSUE THREAD

**Issue by exFalso** [HaxeFoundation/haxe#4513]
The following code

```
class Tmp
{
    public static function funBool(a:Bool):Void
    {
    }

    public static function invoke<A>(f:A->Void, a:A)
    {
        f(a);
    }

    public static function main()
    {
        invoke(funBool, true);
    }
}
```

throws an exception `Exception in thread "main" Haxe Exception: No compatible method found for: funBool`

Tracked it down to slowCallField() in Runtime.hx: https://github.com/HaxeFoundation/haxe/blob/1585b9b001d35ee1e45d65c9cfa7204635c34798/std/java/internal/Runtime.hx#L422

Which apparently doesn't account for primitive `boolean` function arguments.

Changing line 422 from
`if (!  ((isNum && allcls[i].isPrimitive()) || allcls[i].isAssignableFrom(cls[i])) )`
to
`if (!  (((o instanceof java.lang.Boolean || isNum) && allcls[i].isPrimitive()) || allcls[i].isAssignableFrom(cls[i])) )`
fixes the problem.

(Sidenote: The code in Runtime.hx seems a bit ad-hoc and brittle and the variable names aren't really helpful when trying to understand it, it might be worth reviewing)

**Comment by Simn** [comment]
This doesn't reproduce anymore.
