### ISSUE TITLE
onAfterGenerate is broken

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4515]
Right now, we can't even make a trace inside a `onAfterGenerate` function:

```
class Main
{
  public static function macroRun() {
    haxe.macro.Context.onAfterGenerate(function() trace('test'));
  }
}
```

It'd be good also if we could access types through `getType` or access previously saved `haxe.macro.Types` so we could be able to act according to post-DCE'd types

**Comment by Simn** [comment]
This works for me. Can you give a more complete example which has a .hxml so I can check how you're running it?

**Comment by Simn** [comment]
I'm just assuming that this is working.
