### ISSUE TITLE
untyped __js__ doesn't work with more than one parameter

### ISSUE THREAD

**Issue by TerryCavanagh** [HaxeFoundation/haxe#4517]
Heya,

Had a bug with a project I'm working on, and tracked it down to this:

``` haxe
class Main{
  public static function main(){  
    //This works (taken from example http://haxe.org/manual/target-javascript-injection.html)
    untyped __js__('// haxe is great!'); 
    //This doesn't work (taken from example http://haxe.org/manual/target-javascript-injection.html)
    var myVar = untyped __js__('myObject.myJavaScriptFunction({0}, {1})', "Mark", 31);
  }
}
```
Output:
``` javascript
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	// haxe is great!;
	var myVar = __js__("myObject.myJavaScriptFunction({0}, {1})","Mark",31);
};
Main.main();
})();
```

**Comment by fponticelli** [comment]
Why would you expect it to work? `__js__` takes one string literal argument and it cannot make any string interpolation on it. It is not supposed to work the way you describe it. In your specific case you can do:

```haxe
var myVar = untyped __js__('myObject.myJavaScriptFunction')("Mark", 31);
```

**Comment by nadako** [comment]
Actually we have code interpolation, so it should work

**Comment by fponticelli** [comment]
Ooops, apparently I am old school, please disregard my previous comment .... well, I will not remove it since it provides a working alternative.

**Comment by TerryCavanagh** [comment]
I expect it to work because it's copy and pasted from the haxe manual: http://haxe.org/manual/target-javascript-injection.html

**Comment by delahee** [comment]
@TerryCavanagh 

Hi chief !
Code interpolation is fairly recent to the javascript target, so you might want to use the older idiom Franco showed up.

As a side not, i took liberty to reproduce the code on try.haxe.org: http://try.haxe.org/#A1EA3

It seems to me your compiler version might be too old to support the said construct. 

1-What is your compiler version ? 
2-Can you giveout a try.haxe.org for the specific js code you want to stub ? 

Or maybe I am mistaken...

**Comment by TerryCavanagh** [comment]
Hi delahee!

Ah, it's very possible that you've fixed this already in the latest version - I'm in 3.1.3. Sorry! Thanks for the reply!

**Comment by delahee** [comment]
@TerryCavanagh no problem, feel free to ping.
