### ISSUE TITLE
Documentation confusion - fully qualified type names

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#4518]
---
The Problem: Confusing FQTN in documentation
---

The [Haxe documentation](http://api.haxe.org/) feels misleading in how it presents fully qualified type names, for example, `haxe.Constraints.Function`. The left nav, the tooltip, and even the page URL all imply `haxe.Function`:

![image](https://cloud.githubusercontent.com/assets/2192439/9614213/9bf06f06-50ad-11e5-978a-07dd6ac353d9.png)

![image](https://cloud.githubusercontent.com/assets/2192439/9614224/ae19bff2-50ad-11e5-85aa-b7258bcec191.png)

![image](https://cloud.githubusercontent.com/assets/2192439/9614231/bb96e5ba-50ad-11e5-9309-e2f6ade18cb4.png)

Even the definition information says `Package: haxe`, `Abstract: Function`, while `Defined in:` (a field foreign to non-Haxers) is a sub-note:

![image](https://cloud.githubusercontent.com/assets/2192439/9614252/d44ef1e2-50ad-11e5-8fbe-8f2ea84a1249.png)

While it may seem like a nit, extreme clarity is required in documentation for new (and even not so new!) users. I have two possible independent suggestions:

---
**Suggestion 1: Change left-nav to display fully qualified type names (more effort)**
---

Ideally the left nav would include all levels in the FQTN:

```
- haxe
  - Constraints
    - Function
```

There is a degeneracy in that CallStack is both a container and a type, but there are different icons this, so it shouldn't be a problem:
![image](https://cloud.githubusercontent.com/assets/2192439/9614357/a1928ed4-50ae-11e5-894f-db8d64b364a1.png)

Unfortunately, this also breaks the nice lowercase packages structure.

---
**Suggestion 2: Display FQTN instead of separate package, class, defined in**
---

Since suggestion 1 is likely hard, suggestion 2 is to display the FQTN on the page.

That is, instead of this:
![image](https://cloud.githubusercontent.com/assets/2192439/9614432/02c232ea-50af-11e5-97ca-02f69020cd75.png)

Display this:
![image](https://cloud.githubusercontent.com/assets/2192439/9614452/1e520648-50af-11e5-96e6-c475706c4f16.png)

Or some variation of this -- heck instead of package (which is kind of a lie), just show the import statement:
![image](https://cloud.githubusercontent.com/assets/2192439/9614539/9c34d2c0-50af-11e5-9024-33452ea45862.png)

**Comment by jcward** [comment]
FYI, I kinda lean toward this -- a user doesn't care what the package is (nor where it's defined.) A user cares about using (aka importing) the type.
![](https://cloud.githubusercontent.com/assets/2192439/9614539/9c34d2c0-50af-11e5-9024-33452ea45862.png)

**Comment by ncannasse** [comment]
we could simply change "defined in" by "import", that's what we had in old haxe documentation (http://old.haxe.org/api/haxe/stackitem for instance)

**Comment by jcward** [comment]
Ah, so technically you can import the container (module?) `import haxe.Constraints;` or the specific type `import haxe.Constraints.Function;`

Hmm, I'm all for small changes, but if I was God, I'd give the user exactly specifically the type they need, including the `<code>` style and semi-colon:

![test-09-01 16 52 16](https://cloud.githubusercontent.com/assets/2192439/9619117/da0bb8e2-50c9-11e5-8032-fa1ee1224396.png)

**Comment by Gama11** [comment]
@jcward so you'd add a copy-paste button as well? ;D

**Comment by jcward** [comment]
@Gama11 ha ha. Honestly, your users are reading your docs for one reason -- show me how to use it.

**Comment by markknol** [comment]
This is would be a good addition, but I think it should be a https://github.com/dpeek/dox/ issue, that is the official Haxe documentation generator.

**Comment by jcward** [comment]
@markknol indeed, but I presumed api.haxe.org was the major stakeholder, e.g. @ncannasse and company, even though it could be @dpeek repo that would change. Interestingly, OpenFL's documentation doesn't suffer from this issue:

![image](https://cloud.githubusercontent.com/assets/2192439/9664915/fbedd52e-5229-11e5-92c2-da7d8d1557c4.png)

@jgranick always has his users forefront in his mind - go Joshua! Perhaps he's using a modified dox?

**Comment by markknol** [comment]
OpenFL has used the old documentation tool. This all should be a simple tweak in dox.

**Comment by Simn** [comment]
I have changed it to `import`: http://api.haxe.org/v/dev/haxe/Function.html
