### ISSUE TITLE
3.2 fails to parse numbers with leading zeros

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#4519]
I ported over a project today and ran into this one. `var x = 007;` was legal in 3.1, but not in 3.2.

**Comment by Gama11** [comment]
That was disallowed in #3295 / caaa4bc48b23b79c5fcfb02371bb955b52b42fde.

**Comment by Simn** [comment]
Yes, we disallowed it so it wouldn't give people the idea that we were supporting octal notation.

**Comment by Jorjon** [comment]
So we CAN write `007`? Because Haxe 3.2.1 keeps complaining about the leading zeros.

**Comment by andyli** [comment]
We disallowed it as well because it may be considered as inputted in octal, which we do not support.
