### ISSUE TITLE
int64 neg bug

### ISSUE THREAD

**Issue by matrix3d** [HaxeFoundation/haxe#4520]
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Int64.hx#L206

**Comment by Herschel** [comment]
I might be overlooking it, but I don't see the bug? What is the input that gives an incorrect result?

**Comment by ncannasse** [comment]
It is not supposed to be a ~ for both low and high ? (there's a minus instead)

**Comment by Herschel** [comment]
I think that's correct,  two's complement of the low field (-), one's complement of high field (~), and then carrying the 1 if necessary to finish two's complement of high.

**Comment by matrix3d** [comment]
<pre></pretrace(~1);
		trace(~~1);
		
		trace(Int64.neg(Int64.ofInt(1)));
		trace(Int64.neg(Int64.neg(Int64.ofInt(1))));>

need the same of int32,but use -,not same result

**Comment by Herschel** [comment]
I think you are confusing mathematical negation `-` or `neg` with the bitwise complement `~`:

```
        var x : Int64 = -1;
        trace(~x)
        trace(~~x);
```

**Comment by matrix3d** [comment]
i do not know with this.
but just i change the hxsl int flags 2 int64 flags.and use int64 has error,so i trace the value,and find diffrent.and change the neg,it work good.i do not konw the true math.

**Comment by matrix3d** [comment]
http://try.haxe.org/#7b0Da

just try it.
the result different.

but the int64 just 1,just have the low part.so,the result need same

**Comment by Herschel** [comment]
`neg` is different than `~`, you want to use `~` with both:
http://try.haxe.org/#61152

**Comment by ncannasse** [comment]
Seems about right

**Comment by matrix3d** [comment]
& have Int64.and
| have Int64.or
and where is int64.~
the macrc use the ~Int64 ,get error

**Comment by matrix3d** [comment]
@Herschel i use your code in my proj.haxe.Int64 should be Int.
can not override the op.is it there miss a bitneg function?
