### ISSUE TITLE
`Context.getType` on a dependent @:build type causes typing errors

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4527]
The following example:

`Main.hx`:
```haxe
class Main
{
  public static function main()
  {
    var a = A.wrap('test');
  }
}
```

`A.hx`
```haxe
@:build(Macro.build())
@:autoBuild(Macro.build())
class A
{
  public function new(d:Dynamic) {
  }
}
```

`B.hx`
```haxe
class B extends A
{
}
```

`Macro.hx`
```haxe
import haxe.macro.Expr;
import haxe.macro.Context;

class Macro
{
  public static function build():Array<Field>
  {
    var cur = Context.getLocalClass().get();
    Context.getType("B"); // this line is essential
    var isA = cur.name == "A";
    var ret = if (isA) {
      macro class {
        public static function wrap(d:Dynamic) {
          if (d == null) return null;
          return new A(d);
        }

        public static function test(a:Dynamic) {
          return B.wrap(a);
        }
      };
    } else {
      macro class {
        public static function wrap(d:Dynamic) {
          if (d == null) return null;
          return new B(d);
        }
        public static function test(a:Dynamic) {
          return A.wrap(a);
        }
      };
    }
    return Context.getBuildFields().concat(ret.fields);
  }
}
```

Will fail with:
```
Macro.hx:19: characters 17-23 : Class<B> has no field wrap
A.hx:3: lines 3-7 : Defined in this class
```

Despite `wrap` being defined in the build macro

**Comment by Simn** [comment]
That might be a necessary limitation, we can't really add fields to existing types via macros.

**Comment by waneck** [comment]
I understand, but it doesn't have to force a macro build if we call `getType()` on a type - it could show up an empty type, and let the build macro to be called on a later phase, couldn't it?

**Comment by Simn** [comment]
I don't know if that would work. Compiler phases are a bit sensitive so "delaying a build macro" to some point doesn't strike me as an easy endeavor.

**Comment by ncannasse** [comment]
I agree with Simon, it's a very hard part of the compiler already to ensure related things get setup in the right order. One part can be solved by doing lazy evaluation, but that's not always the case. Especially macro can potentially perform a lot of reentrency, and we don't have ways to deal with it in a general manner. I think it's up to the developer to ensure that the macros does not cycle wrt class init.
