### ISSUE TITLE
New JQuery issues

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4528]
Hi, currently switching CastleDB from using old jquery to new @andyli one.
Issues so far:
- `Event` does not have shiftKey/ctrlKey/keyCode, making it impossible to deal with key events
- `jq.val().split(":")` does not work (because of EitherType). I guess I could assign to a String first but that is hard to guess for the user. Given it can be Dynamic, why not keep Dynamic ? 
- `jquery.click(function() {})` does not work : we should allow no-argument listeners
- iterating on Jquery with `for in` returns Elements, while the original returns JQuery. I find the later to be more convenient, JS users can still do `for( i in 0...j.length ) j[i]` as they are used to do
- are pageX, pageY really Float or is Int better ?

Thanks !

**Comment by andyli** [comment]
I'm glad to finally hear some comments for the new jquery extern!


>    - Event does not have shiftKey/ctrlKey/keyCode, making it impossible
>    to deal with key events
>
> Indeed they are missing from the jquery api doc which is used for
generating the extern. I will check with the [jquery source code](
https://github.com/jquery/jquery/blob/master/src/event.js) and add the
missing ones manually.

>
>    - jq.val().split(":") does not work (because of EitherType). I guess I
>    could assign to a String first but that is hard to guess for the user.
>    Given it can be Dynamic, why not keep Dynamic ?
>
> `EitherType` is safer in the sense that it cannot be used as an
incompatible type (without the use of untyped / Dynamic). e.g.:
```haxe
var d:EitherType<String,Int> = "abc";
(function(obj:{foo:String}){})(d); //EitherType<String, Int> should be {
foo : String }
```
What about adding `@:foward` to `EitherType`? That would allows member
access to the underlying type (Dynamic). For ppl who want strict type
checking, they can use a type-check expression or assign it to a var. For
ppl who don't care, they can access whatever they like from it.

>
>    - jquery.click(function() {}) does not work : we should allow
>    no-argument listeners
>
> `click` is expecting a event handling function according to the [doc](
http://api.jquery.com/click/). It is just in JS, functions can be called
with extra arguments, so there is no problem passing a Void->Void there.
Should we type arguments of `A->B->C` as `EitherType<A->B->C,
EitherType<A->C>, EitherType<Void->C>>>`?

>
>    - iterating on Jquery with for in returns Elements, while the original
>    returns JQuery. I find the later to be more convenient, JS users can still
>    do for( i in 0...j.length ) j[i] as they are used to do
>
> I agree it is more convenient. However, `JQuery` is an
`ArrayAccess<Element>` with a `length` field, so it is already iterable
without the added `iterator` method. Adding a `iterator` method to make it
an iterable of another type sounds strange.

>
>    - are pageX, pageY really Float or is Int better ?
>
> I've just checked with IE11, `pageX` and `pageY` are not integers.

**Comment by andyli** [comment]
I'm glad to finally hear some comments for the new jquery extern!


>    - Event does not have shiftKey/ctrlKey/keyCode, making it impossible
>    to deal with key events

Indeed they are missing from the jquery api doc which is used for
generating the extern. I will check with the [jquery source code](
https://github.com/jquery/jquery/blob/master/src/event.js) and add the
missing ones manually.

>
>    - jq.val().split(":") does not work (because of EitherType). I guess I
>    could assign to a String first but that is hard to guess for the user.
>    Given it can be Dynamic, why not keep Dynamic ?

`EitherType` is safer in the sense that it cannot be used as an
incompatible type (without the use of untyped / Dynamic). e.g.:
```haxe
var d:EitherType<String,Int> = "abc";
(function(obj:{foo:String}){})(d); //EitherType<String, Int> should be {
foo : String }
```
What about adding `@:foward` to `EitherType`? That would allows member
access to the underlying type (Dynamic). For ppl who want strict type
checking, they can use a type-check expression or assign it to a var. For
ppl who don't care, they can access whatever they like from it.

>
>    - jquery.click(function() {}) does not work : we should allow
>    no-argument listeners

`click` is expecting a event handling function according to the [doc](
http://api.jquery.com/click/). It is just in JS, functions can be called
with extra arguments, so there is no problem passing a Void->Void there.
Should we type arguments of `A->B->C` as `EitherType<A->B->C,
EitherType<A->C>, EitherType<Void->C>>>`?

>
>    - iterating on Jquery with for in returns Elements, while the original
>    returns JQuery. I find the later to be more convenient, JS users can still
>    do for( i in 0...j.length ) j[i] as they are used to do

I agree it is more convenient. However, `JQuery` is an
`ArrayAccess<Element>` with a `length` field, so it is already iterable
without the added `iterator` method. Adding a `iterator` method to make it
an iterable of another type sounds strange.

>
>    - are pageX, pageY really Float or is Int better ?

I've just checked with IE11, `pageX` and `pageY` are not integers.

**Comment by nadako** [comment]
> What about adding @:foward to EitherType?
I think we discussed that when we first introduced `EitherType` and decided not to add `@:forward` because it wasn't safe enough. Anyway this could lead to confusion like described here #3522, so I think it's better to just add typecheck to unwrap `EitherType`.

**Comment by ncannasse** [comment]
I agree we shouldn't change EitherType definition, but I also think that since JQuery val() is designed as Dynamic, we should keep it Dynamic. The current solution does not prevent typing issues, since you might actually pass a Float where a String is required (and the other way), so let's keep it simple.

For the Void arguments, we can't use EitherType, we need an @:overload because `EitherType<Void,Void> -> Void` is a function which takes one argument of type Void, it's different from `Void -> Void`. I also find EitherType much harder to read/understand, I would prefer overload to be listed in the documentation output.

Regarding that, I actually just looked at the JQuery implementation and I find strange things such as `haxe.extern.EitherType<Dynamic, String>` : since Dynamic is allowed, why not simply put Dynamic ? Forcing the user to type his variable as Dynamic when he wants to pass a Float seems overkill.

For iterator : I agree with the argument, but I would still add an iterator() method because the usefulness is more important here than the weirdness of having it.

**Comment by andyli** [comment]
I don't think `val()` is really "designed as Dynamic". The [jQuery api doc of val()](http://api.jquery.com/val/) says it "Returns: String or Number or Array", but not [Anything](http://api.jquery.com/Types/#Anything), which is one of the types used in their doc. The current signature does prevent typing issue, e.g. it would not allow passing the return value of `val()` to a function that expects a structure type, or an enum, or a specific class instance.

For function arguments, there is a different between what we're talking:
```haxe
// I said, A->B can be defined as
EitherType<A->B, Void->B>
// not as follows
EitherType<A, Void> -> B
```
Anyway, my question was, given a JS function that accept `A->B->C`, should we make its extern accepts all of `A->B->C`, `A->C`, and `Void->C`?
If so, since this is a very common scenario, what about adding a type with `@:genericBuild`, say `haxe.extern.JsFunction<T>`, where `JsFunction<A->B>` is replaced by `EitherType<A->B, Void->B>`.

For the use of `EitherType<Dynamic, String>` I agree it is somewhat redundant and I will replace that with `Dynamic`. For your info, I used EitherType there because it is how the functions are documented. Those functions (e.g. [the `data` argument of `jquery.get()`](http://api.jquery.com/jQuery.get/#jQuery-get-url-data-success-dataType)) accepts either an anonymous object or a string.

For iterator, there is one more consideration. In the upcoming jQuery 3.0, jQuery will be an iterable of Element (https://github.com/jquery/jquery/pull/2369). Would it be a valid argument of keeping our extern as an `Iterable<Element>`?

**Comment by nadako** [comment]
> Anyway, my question was, given a JS function that accept A->B->C, should we make its extern accepts all of A->B->C, A->C, and Void->C?
If so, since this is a very common scenario, what about adding a type with @:genericBuild, say haxe.extern.JsFunction<T>, where JsFunction<A->B> is replaced by EitherType<A->B, Void->B>.

That is an interesting idea and we could probably also use that in hxnodejs to ease copy-pasting js code :)

**Comment by ncannasse** [comment]
Regarding val() : I still think that String|Number|Array(of what) translates to Dynamic in Haxe. Using either type does not allow to write things such as  .val().toUpperCase() which is just annoying for the end user since you usually know what type of node you're dealing with. Typing is here to help, not to bother.

Also, I don't think we should make a specific handling for externs in JS, given that not all methods are actually meaningful if you skip their parameters. JQuery events are a specific case and I would prefer if we use an existing feature such as @:overload instead of inventing something new again.

**Comment by andyli** [comment]
> Regarding val() : I still think that String|Number|Array(of what) translates to Dynamic in Haxe. Using either type does not allow to write things such as .val().toUpperCase() which is just annoying for the end user since you usually know what type of node you're dealing with. Typing is here to help, not to bother.

I think this is a great reason to add a "proper" union type, similar to those of [TypeScript's](http://blogs.msdn.com/b/typescript/archive/2014/11/18/what-s-new-in-the-typescript-type-system.aspx). Whether it should (or can) be achieved by macros is another question. Anyway, I will just change those methods that return `EitherType` to return `Dynamic` for now.

> Also, I don't think we should make a specific handling for externs in JS, given that not all methods are actually meaningful if you skip their parameters. JQuery events are a specific case and I would prefer if we use an existing feature such as @:overload instead of inventing something new again.

In fact, I didn't mean to add special handing to all JS externs in the compiler. Instead, the `Callback` type in #4534 is just for people to use whenever appropriate.

The reason I favour `EitherType` (or `Callback` in #4534) over `@:overload` is that, the number of `@:overload` required to use can grow very fast. e.g.:
```haxe
//original JS signature
@:overload(function(i:Int, f:A->B):Void {})
function something(str:String, f:A->B):Void;

//support functions with less arguments by adding @:overload
@:overload(function(i:Int, f:Void->B):Void {})
@:overload(function(i:Int, f:A->B):Void {})
@:overload(function(str:String, f:Void->B):Void {})
function something(str:String, f:A->B):Void;

//support functions with less arguments by using Callback
@:overload(function(i:Int, f:Callback<A->B>):Void {})
function something(str:String, f:Callback<A->B>):Void;
```
Another example with 2 function arguments:
```haxe
//original JS signature
function something(f1:A->B, f2:A->B):Void;

//support functions with less arguments by adding @:overload
@:overload(function(f1:Void->B, f2:Void->B):Void {})
@:overload(function(f1:Void->B, f2:A->B):Void {})
@:overload(function(f1:A->B, f2:Void->B):Void {})
function something(f1:A->B, f2:A->B):Void;

//support functions with less arguments by using Callback
function something(f1:Callback<A->B>, f2:Callback<A->B>):Void;
```

**Comment by ncannasse** [comment]
Ok, I've change a few minor things in 8e89e62dc82040deef40ec7421bd14e58d2d69ae and have adapted CastleDB to works with new JQuery, you can see the changes I needed to make here : https://github.com/ncannasse/castle/commit/1b0779956318a120221641b03c72cc66e1d1a0bb

I would like to see resolved the optional "event" argument for click etc. I agree that overload can have many variants in general but in JQuery most (all?) of the events are taking a single argument so I guess this will limit the number of combinations while keeping the documentation / completion readable.

**Comment by andyli** [comment]
Unfortunately there are quite many such methods.
Numbers in brackets are number of arguments taken by the event handler:
 * ajaxPrefilter (3)
 * ajaxTransport (3)
 * get (3)
 * getJSON (3)
 * getScript (3)
 * post (3)
 * ajaxComplete (3)
 * ajaxError (4)
 * ajaxSend (3)
 * ajaxSuccess (4)
 * ... argh. there are so many more with 3 and 2 arguments. Just ctrl-f to search for `->` in the [extern page](https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery/JQuery.hx) to get a sense of it.

What's the problem of using `EitherType` as I've suggested in the previous comment?

**Comment by ncannasse** [comment]
We will not change things now :)
