### ISSUE TITLE
Improve the haxe.Template' `cannot iter on *` exception

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4529]
Currently, if you do
```
::foreach missing_identifier::
::end::
```
haxe.Template [will throw](https://github.com/HaxeFoundation/haxe/blob/c5166d23314f3d3357163e8625284963cc92095c/std/haxe/Template.hx#L376) "cannot iter on null", which is the least useful error possible.
The exception should at least include the `loop` object for the context.

**Comment by Simn** [comment]
I don't understand what else you want reported in this case. I agree the error message is not really helpful, but there isn't really any other information to go by. We probably won't have many improvements for haxe.Template, if you need more sophisticated features or error reporting you should use one of the many template haxelibs.

**Comment by YellowAfterlife** [comment]
As I have said, it should at least try printing the "loop" parameter for the context. I use different mechanisms in my own works, but Template is very commonly used (including openfl\lime), and it is pretty infuriating when you have to either manually remove each foreach loop in multiple files until you find the one that fails or have to recompile the toolchain with debug information inserted.

I can add position ("row:column") support (with one additional typedef and a parameter for each TemplateExpr constructor) and make a pull request. Correct me if I'm wrong, but this is very basic stuff, and there is little reason to why one would _not_ want position reporting in errors.

**Comment by Simn** [comment]
Keeping track of positions is not a no-cost operation. Template doesn't even have any notion of files so that would have to be added as well. I'm not sure we want to go down that path with haxe.Template given its rather slender overall nature.

**Comment by YellowAfterlife** [comment]
Positions are pretty low-cost -- there would be a typedef like
```haxe
typedef TemplatePos = { source : String, offset : Int };
```
and enum constructors would be made
```haxe
OpVar( pos : TemplatePos, v : String );
```
instead of the current
```haxe
OpVar( v : String );
```
Performance cost is minimal and would only apply during "compilation" (allocating a structure alongside with other values for each token). By the nature of it, during "execution" the position would only be accessed when an error occurs (which halts the execution anyway).

If additional structures are a huge concern, could even do
```haxe
OpVar( source : String, offset : Int, v : String );
```
