### ISSUE TITLE
@:forward ideally should support property accessors.

### ISSUE THREAD

**Issue by raould** [HaxeFoundation/haxe#4530]
https://mail.google.com/mail/u/0/?tab=wm#inbox/14fa6806a3594493

Expected: This would compile and Bar would have a write-only 'fourtyTwo' that would be using the implementation in Foo.

Actual: Test.hx:15: characters 9-39 : Method get_fourtyTwo required by property fourtyTwo is missing

```haxe
class Frobable {
  public var f:Int;
  public function new( f:Int ) { this.f = f; }
}

abstract Foo( Frobable ) {
  public var fourtyTwo(get,set):Bool;
  public function get_fourtyTwo():Bool { return this.f == 42; }
  public function set_fourtyTwo(_ft:Bool) { if(_ft){ this.f = 42; } return fourtyTwo; }
  public function new( f:Frobable ) { this = f; }
}

@:forward( get_fourtyTwo )
abstract Bar( Foo ) {
  public var fourtyTwo(get,never):Bool;
  public function new( f:Foo ) { this = f; }
}

class Test {
  public static function main() {
    var f = new Foo( new Frobable( 7 ) );
    var b = new Bar( f );
  }
}
```

**Comment by Herschel** [comment]
Read-only abstracts are a common use case. It would indeed be nice to have some syntax for succinctly forwarding properties with restricted access.

Maybe:
```
@:forward( fourtyTwo(get,never) ) abstract Bar(Foo)
```

**Comment by Simn** [comment]
This is not really how `@:forward" works and I don't think if it should work like that. All it does is forward field access to the underlying type if applicable. It does not copy any fields into the abstract, so the error makes sense.

I'm not closing this yet but I can't see a good solution for this at the moment either.

**Comment by Simn** [comment]
Given how `@:forward` was designed, I stick to my view that this shouldn't work. If any actual field copying is required then I recommend using macros.
