### ISSUE TITLE
Sys.command() on Neko (Haxe 3.2.0) breaks the > symbol usage in Linux evironment

### ISSUE THREAD

**Issue by maxless** [HaxeFoundation/haxe#4531]
Probably due to work on #3603 Haxe 3.2.0 cannot properly handle the following code:

```
Sys.command("git", [ "rev-parse", "--abbrev-ref", "HEAD", ">BRANCH.txt" ]);
```
It puts >BRANCH.txt in single quotes breaking the output redirection.

```
Sys.command("git rev-parse --abbrev-ref HEAD >BRANCH.txt" );
```
Puts the whole line in single quotes and shell does not found this command. 

Sys.escapeArgument() is the culprit. If that behavior is intentional then we need some kind of alternative, like a flag that skips argument escaping.

**Comment by ncannasse** [comment]
I think that's normal. ">" is a shell redirection, it's not meant to be working with Sys.command. You should be able to pass it to "sh" command for instance.

**Comment by maxless** [comment]
Okay, I forgot about that:
```
Sys.command("sh", [ "-c", "/usr/bin/git rev-parse --abbrev-ref HEAD >BRANCH.txt" ]);
```

Works fine in 3.2.0.
