### ISSUE TITLE
JS: StringMap cannot be used in __init__

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4533]
The semi-recent @ncannasse's rewrite [https://github.com/HaxeFoundation/haxe/commit/e8b96b48febbe4b21f2fa95246a93e9b67823a66] of the StringMap class is good, but there's a thing - now you can't use StringMaps in class `__init__` methods, as it is not warranted that `StringMap.__init__` will execute earlier and thus the __map_reserved may not be defined by that point. 
A 6-line sample: http://try.haxe.org/#d6d2B
```haxe
class Test {
    static function __init__() {
        new Map<String, Int>()["hey"] = 4;
    }
    static function main() { }
}
```
output:
```
TypeError: __map_reserved is undefined
```

**Comment by ncannasse** [comment]
__init__ was never meant to be used this way : it's used to perform low level init of the classes before they are used. I you want to create data structures, simply use :+1: 

```
static var myMap = {
    var m = new Map<String,Int>();
    m["hey"] = 4;
    m;
}
```
