### ISSUE TITLE
Cannot use `haxe.extern.*` in metadata.

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4535]
I wanted to place `CallbackBuilder` in the `haxe.extern` package. When using it in a `@:genericBuild` as follows:
```haxe
@:genericBuild(haxe.extern.CallbackBuilder.build()) //Unexpected extern
interface Callback<T:haxe.Constraints.Function> {}
```
There is a compiler error "Unexpected extern".

**Comment by ncannasse** [comment]
extern is a keyword :'(

**Comment by Simn** [comment]
I thought I allowed it to be parsed just like `macro`, but apparently it's still missing somewhere.
