### ISSUE TITLE
js.Promise type inference problem

### ISSUE THREAD

**Issue by dpeek** [HaxeFoundation/haxe#4540]
Check out the generated JS source here: http://try.haxe.org/#1F32b

I don't think this is a promise issue (well, perhaps an issue with the externs?)

**Comment by andyli** [comment]
For easy reference. The haxe source:
```haxe
class Test {
    static function main() {
        js.Promise.resolve(0).then(function(c:Dynamic) test(c));
        js.Promise.resolve(0).then(function(c) test(c));
    }
    
    static function test(a:{test:String}) {}
}
```
Generated JS code:
```js
(function (console) { "use strict";
var Test = function() { };
Test.main = function() {
	Promise.resolve(0).then(function(c) {
		Test.test(c);
	});
	Promise.resolve(0).then(null,function(c1) { // <---- notice the extra null
		Test.test(c1);
	});
};
Test.test = function(a) {
};
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});

```

The reason of the difference:

The return type of `js.Promise.resolve(0)` is `js.Promise<Int>`. The expected type of the `fulfillCallback` argument of its `then()` method is `Int->Whatever`.

For the first line, the input is of type `Dynamic->Void`, which is compatible with `Int->Whatever`.
For the second line, the input is of type `{ test : String }->Void`, which is incompatible with `Int->Whatever`, thus filling with `null`.

Does it sound logical to you, @dpeek?

**Comment by mcheshkov** [comment]
Maybe remove optional from `fulfillCallback`? One can still pass null by hand, as in JS.

**Comment by fponticelli** [comment]
Would it make any difference if we change the code to this?

```haxe
@:overalod(function<TOut>(fulfillCallback : PromiseCallback<T, TOut>, rejectCallback : EitherType<Dynamic -> Void, PromiseCallback<Dynamic, TOut>> ) : Promise<TOut> {})
function then<TOut>( fulfillCallback : PromiseCallback<T, TOut> ) : Promise<TOut>;
```

**Comment by andyli** [comment]
@aduros Any insight into the Promise extern?
I wonder why the `fulfillCallback` argument is optional in the `then` method?
```haxe
function then<TOut>( ?fulfillCallback : PromiseCallback<T, TOut>, ?rejectCallback : EitherType<Dynamic -> Void, PromiseCallback<Dynamic, TOut>> ) : Promise<TOut>;
```

For reference, the [jquery promise type](https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery/Promise.hx#L32) has the `then` method with its first argument non-optional.

**Comment by Simn** [comment]
@andyli: Could you take a look at the Promise extern for 3.3? Also see #4808 which might be the same issue.

**Comment by andyli** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/commit/2ff0b8534b691bd927d8a80f6ef8e2879a695b1d
