### ISSUE TITLE
Compiler option to prevent if-else with one expression in the same line on javascript

### ISSUE THREAD

**Issue by RafaelOliveira** [HaxeFoundation/haxe#4542]
The compiler on javascript takes a code like this:

if (a == 0)
      trace("aaa");
else
      trace("bbb");

and transform in this:

if(a == 0) console.log("aaa"); else console.log("bbb");

this is hard to debug because I can't put a breakpoint on the else because everything is on the same line. 
with source mapping I can see the lines separated, but I can't click on the line with the else. Google chrome put a breakpoint some lines above the else. The js file generated have the code in the same way as above (if else in the same line), so the behavior seems related.

I'd like to suggest a option to prevent this. Maybe could be enabled by default in debug mode. 

related discussion:
https://groups.google.com/forum/#!topic/haxelang/qS3LBfm0FDU

**Comment by Simn** [comment]
I think this is part of what Nicolas calls "sanitizing the AST".

**Comment by wighawag** [comment]
any update on this? I think it is quite important to have a good haxe debugging experience
