### ISSUE TITLE
Bytes/BytesOutput related crash from usage pattern

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#4544]
3.3.0 (git build development @ 2a75f0b)
Testing against **cpp.**

Code from 3.2.0 that was working stopped working against the newer builds.
I simplified the test case and found this to crash on cpp, and possibly other targets.

```
var test = new haxe.io.BytesOutput();

test.writeFloat(1);

trace(test.length);  
trace(test.getBytes().length);
trace(test.getBytes().getData());
```

```
Test.hx:42: 4
Test.hx:43: 4
Called from Test::main Test.hx line 28
Called from HDRWrite::test Test.hx line 44
Called from haxe.io.BytesOutput::getBytes /usr/local/lib/haxe/std/haxe/io/BytesOutput.hx line 131
Called from haxe.io.BytesBuffer::getBytes /usr/local/lib/haxe/std/haxe/io/BytesBuffer.hx line 212
Error : Null Object Reference
```

**Comment by underscorediscovery** [comment]
Hmm It seems this also crashes on 3.2.0, 
Tested against git hxcpp and normal hxcpp, 3.2.0 and 3.3.0 git from yesterday.

**Comment by underscorediscovery** [comment]
Apparently getBytes trashes the output, if this is expected behaviour where is it documented?

**Comment by ncannasse** [comment]
I'm not sure it's specified. In Neko getBytes() will not reset the inner buffer.

**Comment by Herschel** [comment]
I know getBytes() invalidates the BytesOutput on flash target, too. It should definitely be documented, at least. Maybe this behavior could be made consistent across platforms--BytesOutput could throw a nicer error if you try to grab it twice.

**Comment by Simn** [comment]
This is mentioned in `BytesBuffer.getBytes` which is used by all targets but flash: "Once called, the buffer can no longer be used.". I find that wording a bit harsh, it's probably more correct to just say that it's unspecified.

Either way, if that is indeed also the case on flash we should mention this on BytesOutput as well.

**Comment by underscorediscovery** [comment]
I think it should be mentioned irrespective of what flash does, as it affects a couple targets at least. The documentation being clearer (or pick an explicit behaviour for all targets with an error) seems a good things.

**Comment by Simn** [comment]
I was referring to the "can no longer be used" part.
