### ISSUE TITLE
[cpp] Array<Dynamic> uses dynamic field accessors for method lookup

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/haxe#4547]
For the code:

```haxe
package;

class Object {
	public function new () {}
}

class Main {
	public static function main():Void {
		var dynarray = new Array<Dynamic>();
		dynarray.push(0);
		var objarray = new Array<Object>();
		objarray.push(new Object ());
		var intarray = new Array<Int>();
		intarray.push(0);
	}
}
```

Haxe generates the C++ code:

```cpp
cpp::ArrayBase dynarray = Dynamic( Array_obj<Dynamic>::__new() );	
dynarray->__Field(HX_HCSTRING("push","\xda","\x11","\x61","\x4a"), hx::paccDynamic )((int)0);
Array< ::Dynamic > objarray = Array_obj< ::Dynamic >::__new();
::Object tmp = ::Object_obj::__new();
objarray->push(tmp);
Array< int > intarray = Array_obj< int >::__new();
intarray->push((int)0);
```

The obj and int arrays are there for comparison.

* Is it necessary for there to be a dynamic lookup for `dynarray`'s push method?
* Can `Array<Dynamic>` generate similar code to other object arrays, and avoid the Dynamic boxing and field access behaviors?

**Comment by james4k** [comment]
Not quite the same issue, but I have also wondered why `Array<Object>` generates into `Array_obj<::Object_obj *>` instead of `Array_obj<::Dynamic>`.

**Comment by hughsando** [comment]
The problem is that the ```Array<Dyamic>``` syntax can mean both "Any kind of array" and "An array of something that could be anything", eg:
```
   static function pushZero(someArray:Array<Dynamic>) someArray.push(0);
   public static function main()
   {
      var ints = [1,2];
      pushZero(ints);
      trace(ints);
      var floats = [1.1,2.2];
      pushZero(floats);
      trace(floats);
      var dynamics:Array<Dynamic> = [ 1, "hello", Test ];
      pushZero(dynamics);
      trace(dynamics);
   }
```
I have recently added "ArrayBase", which would allow the push function to be virtual (slower, but at least not a name-lookup), but it requires some extra reasoning about what types are where.
An array of object is fine, because you can't pass an array of ints to it and expect it to work.

**Comment by james4k** [comment]
Hmm, okay. That seems like a big caveat in the type system, that an Array<Int> or an Array<Float> can be assigned to an Array<Dynamic>. Or it is a misunderstanding on my part.

Is there perhaps another way to express Array<Dynamic> that is strictly an array of objects?

**Comment by Simn** [comment]
With `-D cppast` we now get this:

```c++
HXLINE(   9)		::cpp::VirtualArray dynarray = ::cpp::VirtualArray_obj::__new();
HXLINE(  10)		dynarray->push((int)0);
HXLINE(  11)		::Array< ::Dynamic> objarray = ::Array_obj< ::Dynamic>::__new();
HXLINE(  12)		objarray->push(::Object_obj::__new());
HXLINE(  13)		::Array< Int > intarray = ::Array_obj< Int >::__new();
HXLINE(  14)		intarray->push((int)0);
```

I don't know how to add a test for this, but the original issue seems to be resolved.

P.S.: I like the new line markers, so much more readable!
