### ISSUE TITLE
Still allowed to create new instances of private constructor in some cases

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4550]
This one was confusing:

```haxe
var test = new openfl.net.SharedObject ();
```

`openfl.net.SharedObject` has a private constructor, but this is still compiled :confused: 

If I found that if I create a duplicate `openfl.events.EventDispatcher` and rename it (such as "EventDispatcher2") and extend this instead, then the "private constructor" error appears properly.

I cannot find any reason for this. Thank you!

**Comment by jgranick** [comment]
Here's a quick sample that reproduces it:

```haxe
package;


import openfl.display.Sprite;
import openfl.net.SharedObject;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var test = new SharedObject ();
		
	}
	
	
}
```

You can `openfl create project PrivateConstructorTest` and replace Main.hx with this to test

**Comment by tienery** [comment]
I have narrowed the issue down to the following condition:

If the base class has a public constructor, the derived class constructor accessor is ignored, even if marked as `@:noPrivateAccess`.

Possible solution:

    private function new()
    {
		
    }
	
    public static function create()
    {
        return new Object();
    }

Although, `protected` behaviour shouldn't do this anyway.

**Comment by Atry** [comment]
Is this a duplication of https://github.com/HaxeFoundation/haxe/issues/3596

**Comment by tienery** [comment]
@Atry That's talking about constructor consistency, nothing to do with the behaviour of the `private` accessor.

**Comment by Simn** [comment]
I cannot reproduce the issue with this:

```haxe
class Parent {
	public function new() { }
}

class Child extends Parent {
	private function new() {
		super();
	}
}

class Main {
	static function main() {
		var c = new Child();
	}
}
```

Please post an a complete example that doesn't require libraries.

**Comment by Simn** [comment]
Feel free to reopen with an example.

**Comment by jgranick** [comment]
I apologize that I have no good way to reproduce this issue, as I mentioned in the original issue, renaming the base class does not have this issue.

Perhaps the Flash extern classes (since the original base class shares a name with Flash classes) are somehow interacting with this, forcing the constructor to be public, similar to what tienery mentioned?
