### ISSUE TITLE
[docs] sys.FileSystem (and others) should show available in java, cs and python

### ISSUE THREAD

**Issue by mrcdk** [HaxeFoundation/haxe#4553]
This http://api.haxe.org/sys/FileSystem.html doesn't show that it's available on other targets. I haven't tested it, but https://github.com/HaxeFoundation/haxe/tree/development/tests/sys tells me that they should be.

**Comment by Simn** [comment]
This is better on v/dev: http://api.haxe.org/v/dev/sys/FileSystem.html

Java is still missing for some reason, no idea why. Can you check the "others" you mentioned?

**Comment by Simn** [comment]
The class isn't part of the XML output for Java, but I have no idea why. Not critical for the RC, I'll check it out again for 3.3.0 final.

**Comment by Simn** [comment]
Accidentally fixed by https://github.com/HaxeFoundation/dox/commit/d14aa5fc228ecd2a4c4394f0665fbe6ee79e3386
