### ISSUE TITLE
haxe.CallStack.exceptionStack for js fails when DCE disabled

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/haxe#4556]
The following code (from https://github.com/HaxeFoundation/haxe/pull/3838) fails when DCE disabled.

```haxe
class Main {
    static function main() {
        try {
            throw false;
        } catch (e:Dynamic) {
            trace(e);
        }
    }
}
```

```
ryama% haxe -main Main -js main.js -dce no     
ryama% node main.js 
/Users/ryama/work/prog/haxe/test/main.js:115
		haxe_CallStack.lastException = e;
		^

ReferenceError: haxe_CallStack is not defined
    at Function.Main.main (/Users/ryama/work/prog/haxe/test/main.js:115:3)
    at console.undefined.log (/Users/ryama/work/prog/haxe/test/main.js:659:6)
    at Object.<anonymous> (/Users/ryama/work/prog/haxe/test/main.js:660:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

**Comment by nadako** [comment]
I'm not sure how to approach this properly. The `lastException` generation checks for `has_feature ctx "haxe.CallStack.exceptionStack"`, which seems to be always true when DCE is disabled, even if we didn't include `haxe.CallStack` in compilation at all.

@Simn how to deal with this?

**Comment by Simn** [comment]
Are you sure the class is compiled at all?

**Comment by nadako** [comment]
It's not, but `has_feature` still returns true because of `dce=no`, that's the problem.

**Comment by nadako** [comment]
Hm, one option is to do a check if `haxe.CallStack` is included in `types` in genjs when dce=no.

**Comment by Simn** [comment]
You could also make sure CallStack is always compiled. It wouldn't make much of a difference with DCE disabled.

**Comment by nadako** [comment]
Why? We don't need to compile it if user don't use it, but if they do - we need to generate the `lastException` assignment.

**Comment by nadako** [comment]
Oh, you mean always include it when dce=no? HM.
