### ISSUE TITLE
[js] Bug: Leaving out constructors can cause declaration values to be null

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4557]
If you extend twice without constructor and you do `private var myObject = new MyObject()`, myObject will never be instantiated (it stays `undefined`)

Unexpected result:
http://try.haxe.org/#46840

Expected result:
http://try.haxe.org/#E271B

Tried with Haxe 3.2

**Comment by nadako** [comment]
Wow that's quite a bug!
