### ISSUE TITLE
compiler -lib: ignore .dev if library version specified

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4560]
I think, if a library version specified then dev library version must not be used:
```cmd
haxe -lib mylib:1.0.0 ...
```
So, file `.dev` must be ignored by compiler in this case.

**Comment by Simn** [comment]
If anything that's a haxelib issue, please open the issue here: https://github.com/HaxeFoundation/haxelib/issues

**Comment by yar3333** [comment]
Does compiler call haxelib to detect real path to the library? If so, you are right...
