### ISSUE TITLE
js: missing ";" in output code

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4561]
Sometimes I get output js:
```js
...
var __map_reserved = {}
(function() {  // from this line - js code included by macro (includeFile)
	var fullScreenApi = {
...
```
Browser interpret this as "{}()" - calling not a function. If I change `untyped __js__("var __map_reserved = {}");` to `untyped __js__("var __map_reserved = {};");` then I get double ";" in the output js code:
```js
...
var __map_reserved = {};;
(function() {  // from this line - js code included by macro (includeFile)
	var fullScreenApi = {
...
```

**Comment by Simn** [comment]
Could you provide some Haxe code which reproduces this issue?

**Comment by Simn** [comment]
Closing due to lack of followup.

**Comment by elsassph** [comment]
Old ticket, but the current state of Haxe JS is that the semicolon has been added:
```javascript
var __map_reserved = {};
```
