### ISSUE TITLE
@:nativeGen still generating haxe code

### ISSUE THREAD

**Issue by jharrison63** [HaxeFoundation/haxe#4566]
Currently, even though I have the @:nativeGen on the class, in one of the array accessors it tries to cast the contents to an int using haxe.lang.RunTime.toInt(x). It also will strip all inheritance with haxe (this is correct, doesn't add hxobject inheritance properly) but will **still add using 'haxe.root;'.**

If nativeGen is on, it should never be inserting these especially since it's already doing the native cast. Also, this is for the C# target.

**Example:** (int) (global::haxe.lang.Runtime.toInt(someList[i])) )
**Ideal:** (int) someList[i]

**Comment by Simn** [comment]
The Java target will be put in "regression fixes only" state with the Haxe 4.3.0 release. See https://github.com/HaxeFoundation/haxe/wiki/Target-Support-Level#java-and-c-since-430 for additional information. We apologize for any inconvenience this causes!
