### ISSUE TITLE
[flash] @:hack does not allow to extend @:final class

### ISSUE THREAD

**Issue by T1mL3arn** [HaxeFoundation/haxe#4570]
http://try.haxe.org/#e0012
```Haxe
class Test {
    static function main() {
        trace("Haxe is great!");
    }
}


@:final class A
{
    public function new (){}
}

@:hack class B extends A
{
    public function new () {super();}
}
```

On js all ok. 
On flash I got error:
```
VerifyError: Error #1103: Class B cannot extend final base class.
```

**Comment by Simn** [comment]
I guess that's why it's called "hack". If the run-time doesn't like it there really isn't much we can do about it.

**Comment by Gama11** [comment]
In that case, shouldn't it be documented that it's not guruanteed to work?

**Comment by Simn** [comment]
It's kind of implied by the thing being named "hack", but I wouldn't mind mentioning it.
