### ISSUE TITLE
[neko] Can't serialize haxe.ds.Vector

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#4574]
Forwarding report from https://github.com/openfl/openfl/issues/864

>  when trying to serialize an openfl.Vector or a haxe.ds.Vector, like so:
>  
> ```haxe
var positions = new Vector(5);
var serializer = new Serializer();
serializer.serialize(positions);
```

> it throws an error:

> ```Cannot serialize [null,null,null,null,null]```

> This error persists when the vector is properly populated with instances. So far the error only happens when targetting neko. Tried it on cpp and flash, they work.

This seems due to the fact that on neko `Type.typeOf(positions);` returns `TUknown`.

**Comment by ncannasse** [comment]
haxe.ds.Vector is not supported by Serialization format, in particular because it's an abstract type that might be implemented as an Array on some platforms. See http://haxe.org/manual/std-serialization-format.html
