### ISSUE TITLE
Abstract @:from with nil value

### ISSUE THREAD

**Issue by Chlorodatafile** [HaxeFoundation/haxe#4582]
Hello everyone !

I came here for a such special things about the abstract class.

Actually, when you use a @:from metadata on a function field of an abstract, it happen that it exclude the null value, and more, if the `abstract` abstract an `Int`, `UInt` or a `Float`, in static platforms, assign a nil value throw an error.

You will say thats logical, and I understand, but, look a little. By taking that [sample](http://try.haxe.org/#97E7B) : 
I make an `Int` type to manage some flags, and I've a null value define in my abstract, who is called NONE and had for value `0xFFFFFFFF`. It's such logical for me to replace the null assignment, impossible in static platform, by this value. But actually, my code don't work, if you look closer : 

I define my from function like this : 
```haxe
@:from public static inline function fromInt(v:Null<Int>):TileFlag return new TileFlag(v);
```
And now, taking that : 
```haxe
var t:TileFlag = TileFlag.fromInt(null);
trace(t); //trace -1, the value of 0xFFFFFFFF, ok
t=1;
trace(t); //trace 1, ok
t=SCALE|RGB|MATRIX|MATRIX;
trace(t); //trace 21, still ok
t=null; //error in static platform
trace(t); //trace null, not ok
```

With that example, I hope I can show you an interesting implementation who can be done on the `Float`, `Int` and `UInt` abstract, by replace manually the null value, but how ? I've thinked about find a way with the `Null<Type>` `@:from` field, but I don't think it's the better idea, so, may a thing like this : 
```haxe
@:null var myNullField = value;
//In my case, that will give :
@:null var NONE = 0xFFFFFFFF;
```

**Comment by Chlorodatafile** [comment]
In the same way, make an equality with a `null` value from an `Int`, `UInt`, or `Float` value is actually impossible, even with a good management of the `Null` type. By the implementation of the `@:null` metadata, it would be possible to make that : 
```haxe
trace(TileFlag.RGB==null); //false
trace(TileFlag.NONE==null); //true
```

**Comment by Simn** [comment]
Could you post a complete, minimal example of your issue?

**Comment by Chlorodatafile** [comment]
Yes, here is it : http://try.haxe.org/#07Ffa

We can see that the only `Null<Int>` who didn't work is with the `@:from` metatag.

We also can see that `(b==null?-1:b)` is used many times, and with the `@:nil` metatag, it could be replaced.

**Comment by Simn** [comment]
This is consistent with how our type system works: Implicit casts are only applied if unification fails. With `null` being a monomorph which is subsequently bound to `MagicNumber` there is no need for an implicit cast. I don't think we should change this behavior.
