### ISSUE TITLE
Date timestamps are not consistent

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4584]
Are they defined with regard to time zones? If not, that's a real pity. E.g.

``` haxe
Date.now().getTime();
```

returns different numbers on e.g. JavaScript and C# targets, since JavaScript returns UTC timestamp (which I think is correct), but C# returns timestamp offsetted to current time zone.

cc @waneck @ncannasse

**Comment by fponticelli** [comment]
UTC timestamp should be universal and offsetting it is most likely the wrong thing to do.

**Comment by nadako** [comment]
I agree. If no comments will follow, I'll try fixing it at least for C#.

**Comment by nadako** [comment]
Forgot to link commit to this issue f84440d5bff59a7b364c96e767c6a6dd5482f482

**Comment by Aurel300** [comment]
This seems to be fixed.
