### ISSUE TITLE
3.2.1 Mac OSX installer doesn't install binaries to /usr/local/bin/ on latest El Capitan update

### ISSUE THREAD

**Issue by jangdan** [HaxeFoundation/haxe#4585]
Perhaps a continuation of #4483 

I've tried the new update and the installer. It worked, installing on `usr/local/` instead of `usr/`

However, I still couldn't run the `haxe` and `haxelib` commands on terminal, and I found out that the installer didn't add anything to /usr/local/bin/.
I'm new to linux and stuff, so I might've missed something, but if thats not the case:

![screen shot 2015-10-12 at 10 13 21 pm](https://cloud.githubusercontent.com/assets/1841652/10428906/9385c148-712f-11e5-911b-d2de26e74a50.png)

`/usr/local/ `right after installation
![screen shot 2015-10-12 at 10 12 41 pm](https://cloud.githubusercontent.com/assets/1841652/10428727/65f5e74a-712e-11e5-83e0-6f25a28e086a.png)

**Comment by waneck** [comment]
I will look into it tonight. Thanks for testing!

**Comment by waneck** [comment]
Can you please run `ls -al /usr/local/bin/haxe` ?

**Comment by jangdan** [comment]
![screen shot 2015-10-12 at 10 31 36 pm](https://cloud.githubusercontent.com/assets/1841652/10429091/06bd88e8-7131-11e5-8432-63beff94e332.png)

its just .... not.... there...........

**Comment by waneck** [comment]
That's weird!
Okay, I'll have a look tonight!

**Comment by jangdan** [comment]
I did some hacking hehe

Looking inside the `.pkg`, inside the `scripts.tar.gz`, I found `install.sh`, of which I'd never know if you guys are writing that shell or if an installer creator packaging program is doing that, but
![screen shot 2015-10-12 at 10 41 24 pm](https://cloud.githubusercontent.com/assets/1841652/10429330/a302a2be-7132-11e5-86e4-83933a916970.png)

there is no `cp` command directed to `usr/local/bin`, so maybe that could be the problem.

I hope this helps in any way! The problem _feels_ simple.

**Comment by waneck** [comment]
You're on the right track ;) I'll have a look! Thanks! If you found the
issue, you can submit a PR to
https://github.com/waneck/hxbuilds/tree/master/projects/haxe/platforms/mac-clang-installer-linux/scripts

Strange thing that it was reportedly working before, and I didn't make any
changes afterwards. Oh well, go figure!

2015-10-12 9:47 GMT-04:00 jangdan <notifications@github.com>:

**Comment by waneck** [comment]
Okay, I think I know what's up
Looking at https://github.com/waneck/hxbuilds/blob/master/projects/haxe/platforms/mac-clang-installer-linux/scripts/haxe-postinstall.sh#L10 , we indeed add a link; However we don't try to create /usr/local/bin if it doesn't exist (which is your case), so the script fails silently

**Comment by waneck** [comment]
@jangdan , I've updated the binaries. It will take a couple of minutes for the binaries to be updated on the Haxe website, but you can get it from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/mac-installer/haxe_2015-10-13_master_deab442.tar.gz . Please let me know if this solves it for you

**Comment by jangdan** [comment]
both `haxe` and `haxelib` work nicely, although I haven't tried compiling anything. Compile problems should be on another thread, so if I encounter one, i'll be quick to notify you on another 'Issue'.

Screenshot of /usr/local/bin/ fyi:

![screen shot 2015-10-13 at 4 31 54 pm](https://cloud.githubusercontent.com/assets/1841652/10448864/ad585efa-71ca-11e5-9ebb-c4c175aa27d8.png)

So I guess the case is closed.!

**Comment by jangdan** [comment]
@waneck 

A little error while running `haxelib setup`:

![screen shot 2015-10-13 at 5 00 46 pm](https://cloud.githubusercontent.com/assets/1841652/10449113/4aea2e2c-71cc-11e5-813b-7c2d838d0490.png)

/usr/lib/ is unwritable.
default directory should be updated!

**Comment by waneck** [comment]
Great. As for the `haxelib setup` path, can you add this as an issue on `haxelib`? We'll probably leave it to fix on the next version.

**Comment by lewislepton** [comment]
dont mean to reopen this. but just wanted to ask this question:
would the new update fix the install path, so it goes to the right path? so it ends up in `/usr/lib/`?

im staying away from el capitan for this because of the problem in the install. the 3.2.1 does install well, but doing all the other things is bad

thanks for the work on this

**Comment by waneck** [comment]
yes it's now installing on `/usr/local`

**Comment by lewislepton** [comment]
ok cool. what about the location of using haxelib etc. im sure i saw someone having trouble doing install and even running the code from sublime because it could not find haxelib

**Comment by jangdan** [comment]
@waneck okay i'll just copy and paste my comment from here and add a new issue.

**Comment by jangdan** [comment]
@lewislepton everything (well, 'everything' for me is haxe, openfl, building to neko and flash, with sublime text) is working fine for me. i assume all the directory calls in `haxelib` are relative (how nice!). no problems.

**Comment by lewislepton** [comment]
@jangdan ok. fair enough. i use openfl, sublime. thats really about it. well as long as its ok. i just went ahead and installed capitan anyhow. may as well, one way or the other it will be fixed

**Comment by stevecochrane** [comment]
Just wanted to say that as a Mac user who is just now starting to learn Haxe, seeing this fixed so openly and quickly is really encouraging. Thanks! :)
