### ISSUE TITLE
enhancement: accessing function arguments by name.

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#4589]
when a function has optional or default arguments, 
(optional can be seen as: the default argument was null)
allow passing the values by name instead of by order.
this is kind of like passing a hashtable of `<string, Object>` to the function, matching the arguments to the keys.
why is it needed?
functionally:
let's say there is a function with default values that sets some values.
you don't know what those current values are. you just want to change the third argument. how will you pass that information? It seems that currently it is not possible to do in Haxe.
``` 
class HiddenColor {
        function setColor(r:Uint = 200, g:Uint = 150, b:Uint = 0) { ... }
    }
// an instance of HiddenColor was changed externally for example, we don't know its state.
// I just want to change blue:
// here are a few options for the syntax:
setColor(_,_,35);
setColor(,,35);
setColor(b=35);
setColor( b: 35);
```
readability wise:
it helps with boolean and int arguments that are not obvious from the code itself. you have to use the documentation to get an idea about the values and what they do. 

Am I missing something that already exists in haxe?

**Comment by nadako** [comment]
It has been proposed multiple times, but @ncannasse disagrees, see this comment: https://github.com/HaxeFoundation/haxe/issues/4507#issuecomment-135796766

**Comment by back2dos** [comment]
Also, there's a macro for that:
https://github.com/haxetink/tink_lang#named-parameters

**Comment by kobi2187** [comment]
replacing function signatures with typedefs. now that's an idea
