### ISSUE TITLE
Bogus abstract chain detected on abstract<T>(T)

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4591]
```haxe
class Main {
  static function main() {
    var x:Test<Test<String>> = null;
  }
}

abstract Test<T>(T) from T to T {
}
```

Will fail with
```Main.hx:7: lines 7-8 : Abstract chain detected: Test -> Test```

Latest Haxe

**Comment by waneck** [comment]
Also shouldn't this https://github.com/HaxeFoundation/haxe/blob/development/type.ml#L1889 be `memq`?

**Comment by waneck** [comment]
I've added the `haxe-foundation-partner` since this is related to Proletariat

**Comment by Simn** [comment]
I don't remember why the stack only holds the abstracts and not the type parameters as well. This would lead to using `fast_eq` which if I recall correctly still has some issues at the moment.
