### ISSUE TITLE
PHP target does not throw error when parsing invalid JSON

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/haxe#4592]
The [API documentation](http://api.haxe.org/haxe/Json.html) for `haxe.Json.parse` states:

> Parses given JSON-encoded `text` and returns the resulting object. ...If given `text` is not valid JSON, an exception will be thrown.

The following snippet correctly throws an [error on the JS target](http://try.haxe.org/#2FBfA), but it does not throw an error when compiling to PHP:

``` Haxe
import haxe.Json;

class Test {
    static function main() {
        var string =  'hello":"world"';

        try {
            var object = Json.parse(string);
            trace(Std.string(object));
        } catch( jsonError : Dynamic ) {
            trace(Std.string(jsonError));
        }

        try {
            throw "manual-error";
        } catch( error : Dynamic ) {
            trace(Std.string(error));
        }

    }
}
```

The [`phpJsonDecode` method](https://github.com/HaxeFoundation/haxe/blob/development/std/php/_std/haxe/Json.hx#L43) makes a call to PHP's native `json_decode` and passes the resulting PHP object to a method that maps it to a Haxe datastructure:

```
    static function phpJsonDecode(json:String):Dynamic {
        var val = untyped __call__("json_decode", json);
        return convertAfterDecode(val);
    }
```

 The function should probably first call PHP's [`json_last_error` method](https://secure.php.net/manual/en/function.json-last-error.php) and throw any errors that arise.  The PHP page has a nice switch statement for descriptive error text.

There should probably be a unit test to ensure that this function works correctly on all targets.

**Comment by indolering** [comment]
Here's my workaround:

```Haxe
    public static function parseJSON(string:String){
            var val = Json.parse(string);

            #if php
            var error:Int = untyped __call__("json_last_error");

            //php5.5+
            //if(error != 0){
            //    throw "JSON Parse Error: " + untyped __call__("json_last_error_msg");
            //}

            //php 5.3.0+
            var message = "JSON Parse Error: ";

            switch error {
                case 0: return val;
                case 1: throw message + 'Maximum stack depth exceeded';
                case 2: throw message + 'Underflow or the modes mismatch';
                case 3: throw message + 'Unexpected control character found';
                case 4: throw message + 'Syntax error, malformed JSON';
                case 5: throw message + 'Malformed UTF-8 characters, possibly incorrectly encoded';
                default: throw message + 'Unknown error';
            #end
            }
            return val;
    }
```

I copied the error messages directly from the PHP website.  It's CC licensed but I think fair use will allow us to directly include it.

**Comment by indolering** [comment]
The maximum level of compatibility would actually be to do a null check against the output of `json_decode`.  I would still check for `json_last_error` and use it since it gives usable error messages.

**Comment by andyli** [comment]
Would you submit a pull request with a unit test (can be placed [here](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/TestJson.hx)) ?
