### ISSUE TITLE
String concatenation bypassing available @:to String cast 

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#4593]
```haxe
abstract Foo(Int) from Int {
	@:to function print():String
		return 'INT $this';
}

class Test {
    static function main() {
        var a:Foo = 1;
        var b = "value is " + a;
        trace(b);
    }
}
```

([on Try Haxe](http://try.haxe.org/#f69b8))

I might be forgetting something, but shouldn't the result be "value is INT 1"?

Note: if `Foo.print` is actually called `Foo.toString`, everything works as expected.

**Comment by Simn** [comment]
That's a good question. We started off with the `toString` convention for classes and then kept it for abstracts. I suppose for these we should also respect `@:to String` fields as this is an implicit cast.
