### ISSUE TITLE
@:font fails to embed some fonts

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#4596]
Hello.
I'm trying to embed fonts in flash target with `@:font` meta. 
Looks like most glyph fonts (at least of those i tried) cannot be embedded due to this error:

```
$ haxe build.hxml
IO.Bits_error
```

Here are example fonts which i am unable to use: 
https://github.com/designmodo/Flat-UI/blob/master/fonts/glyphicons/flat-ui-icons-regular.ttf
https://github.com/Keyamoon/IcoMoon-Free/blob/master/Font/IcoMoon-Free.ttf
http://www.fontsquirrel.com/fonts/download/webhostinghub-glyphs 

These font cause no troubles in other software. So i think this is a bug somewhere in Haxe.

I'm using Haxe 3.2, Ubuntu 14.04 x64

**Comment by Simn** [comment]
We currently don't have the resources to deal with `@:font` issues so you would have to look into this yourself for the time being.

**Comment by Simn** [comment]
I'll go ahead and close this. Maybe we should just remove `@:font` for Haxe 4, it's way too flash-specific anyway.
