### ISSUE TITLE
[C#] __hx_setField ignores readonly properties in native code

### ISSUE THREAD

**Issue by chipshort** [HaxeFoundation/haxe#4598]
When extending a native C# class that contains a ReadOnly-Property (e.g. System.Windows.Forms.Form), a CS0200 error (in this case many of them) is generated.

``` haxe
class Test extends cs.system.windows.forms.Form
{
}
```

This happens, because "__hx_setField" also contains code for those ReadOnly-Properties.
Example:

``` csharp
case 1158493921:
{
    this.DesignMode = global::haxe.lang.Runtime.toBool(@value);
    return @value;
}
```

**Comment by waneck** [comment]
Hmm that's unexpected. Are you using `-net-lib`? Which DLL are you using?

You can work around this for now by declaring your class as `@:nativeGen`

**Comment by chipshort** [comment]
Yes, I am using -net-lib to include Accessibility.dll, System.Windows.Forms.dll and System.Drawing.dll,
all of them from Microsoft.Net 4.0.
I added them using `@std`.
Thanks for the tip about nativeGen, this works indeed.

**Comment by nadako** [comment]
Here's a reproducible example from #4162
> Here gist : https://gist.github.com/mikicho/44d57f31f017fa5d86f8

**Comment by nadako** [comment]
I meddled with this a bit to find out that `get`-only properties are eliminated from `_hx_setField` if they are public, but not if they're protected. Really not sure what's going on here...
