### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4602]
During packaging haxe for fedora, it has been found out that the license headers used in our source files are inconsistent.

Particularly:

 * The std lib should be MIT licensed, but:
   * std/haxe/xml/Printer.hx is BSD
   * std/cs/_std/haxe/ds/IntMap.hx is BSD
   * extra/ImportAll.hx is BSD, it is not really in std but still
 * The haxe compiler should be GPLv2+, but the ocaml source files are found to be MIT/X11 (BSD like). I'm not sure if it is okay.

Detailed report of the license analysis can be found at https://bugzilla.redhat.com/attachment.cgi?id=1082101, which is an attachment in https://bugzilla.redhat.com/show_bug.cgi?id=1270554

Can I simply change those headers according to http://haxe.org/foundation/open-source.html ?

**Comment by Simn** [comment]
You can definitely change the .hx licenses. I'll make sure to pay attention to it for future pull requests.

**Comment by waneck** [comment]
Yeah my BSD one was really an error - I'm surely fine with our MIT one

**Comment by waneck** [comment]
I've taken the opportunity and committed https://github.com/HaxeFoundation/haxe/commit/e3ae3656b5b9be235fafadba5fbcc2c0950da1b4 too

**Comment by andyli** [comment]
Great! I will make the change tmr.

**Comment by ncannasse** [comment]
Feel free to change the .ml as well

**Comment by andyli** [comment]
Done ; )
