### ISSUE TITLE
haxe.remoting.ExternalConnection broken for flash target due to package name flattening

### ISSUE THREAD

**Issue by flipflophhj** [HaxeFoundation/haxe#4606]
The string litteral "haxe.remoting.ExternalConnection" needs underscores instead of dots since 3.2 due to the package name flattening.

Maybe there should be two versions since it should still be dots when the "js-unflatten" compile flag is used.

From ExternalConnection.hx

	public function call( params : Array<Dynamic> ) : Dynamic {
		var s = new haxe.Serializer();
		s.serialize(params);
		var params = escapeString(s.toString());
		var data = null;
		#if flash
			data = flash.external.ExternalInterface.call("haxe.remoting.ExternalConnection.doCall",__data.name,__path.join("."),params);

**Comment by ncannasse** [comment]
Could you test + submit a PR which changes the name based on #if js_unflatten ?
@aduros is there no rule to preserve path access when a class is @:expose ?

**Comment by flipflophhj** [comment]
Seems I can't ..

I've cloned in GitHub Desktop. Created a branch from development. Made the change and comitted. Then tried pull request like the tutorial did.

I get told I dont have permission to push changes to the repository.

**Comment by flipflophhj** [comment]
Also in an attempt to create a pull request in the web interface i accidently created a completely bogus pull request .. Sorry ..

**Comment by flipflophhj** [comment]
I closed it .. I hope thats the correct thing to do..

**Comment by flipflophhj** [comment]
Finally found out how to do a proper pull request

https://github.com/HaxeFoundation/haxe/pull/4718
