### ISSUE TITLE
unable to switch on UTF8 strings

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#4608]
Run the following, it fails in both Java and Python. I added the invalid `"a"` case just to trigger the right behavior in Python.

```haxe
class Main {
  static function main() {
    var t = "°C";
    switch t {
      case "°C":
        trace("OK");
      case "a":
        trace('also not good $t');
      case _:
        trace('cannot match $t');
    }
  }
}
```

**Comment by mandel59** [comment]
I forget to include commit messages that close this issue, so this issue needs to be manually closed.

**Comment by andyli** [comment]
Closing.
Thanks, @mandel59!
