### ISSUE TITLE
Invalid syntax on generated python code (nonlocal keyword on a closure)

### ISSUE THREAD

**Issue by vrescobar** [HaxeFoundation/haxe#4616]
Hello,

Here is the minimum code to show the error:

    package;
    
    class HxLisp {
        static function main() {
            trace("Example: " + Math.abs(10 + -2) % 10);
        }
    }

compile it:

    haxe -cp src/ -main HxLisp -python build/python/hxlisp.py -dce full

The error:

    Traceback (most recent call last):
      File "app_main.py", line 75, in run_toplevel
      File "build/python/hxlisp.py", line 580
        nonlocal l
                ^
    SyntaxError: invalid syntax

The error occurs with cpython 2.7.7 on macosx as well as with PyPy 2.4.0 (implements python 2.7.8).
I am reading the generated python code and I don't understand why that piece of code has an invalid syntax.

**Comment by vrescobar** [comment]
haxe -version
3.3.0 (git build development @ 1ae4482)

Generated code (python):
http://pastebin.com/RRHhFUeh

**Comment by andyli** [comment]
Currently the python target only support python 3. For python 2 support, follow #4195.

**Comment by vrescobar** [comment]
Is it possible to add it to the haxe --help?
    
    haxe --help 2>&1 | grep python
     Usage : haxe -main <class> [-swf|-js|-neko|-php|-cpp|-as3|-cs|-java|-python] <output> [options]
      -python <file> : generate Python code as target file

Thank you.
