### ISSUE TITLE
Reflect function not inlined

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4618]
Haxe 3.2.1: 
Windows 7

Haxe:
```haxe
class Main 
{
	static function main() 
	{
		var o = { };		
		Reflect.setField(o, "test", true);		
	}
}
```
js output:
```js
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	var o = { };
	Reflect.setField(o,"test",true);
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

This causes a `Reflect is not defined` error.

However, on Mac it is fine (i.e. it generates `o.test = true`)

**Comment by Simn** [comment]
JS Compilation is not affected by what OS you're on. There must be some compilation parameter or something else going on.

**Comment by kevinresol** [comment]
I didn't change anything but installing 3.2.1
reverting back to 3.2.0 makes it works again

**Comment by andyli** [comment]
I've heard several times this kind of windows installation issue...
I'm just guessing, that there were some processings holding the old files, such that they were not properly replaced.
See if that helps: __Before__ reinstalling haxe, reboot to make sure no active process is running and holding the haxe files.

**Comment by kevinresol** [comment]
@andyli that actually is the solution, thanks!
