### ISSUE TITLE
In particular situation, when a call to "Context.getType" happens, even if the method was defined, "has no field method" error will raise.

### ISSUE THREAD

**Issue by ryanagi** [HaxeFoundation/haxe#4622]
### Overview

​
Create the following Main.hx, A.hx, B.hx, C.hx, X.hx, Y.hx and Macro.hx program.
The following error will raise when `haxe -cp src -main Main --interp` command is executed(even with the parameter `-swf`, `-js`, etc.)
​ 

> src/C.hx:3: characters 25-33 : A has no field foobar

`Main.hx`

```
import Y;
​
class Main
{
public static function main():Void { }
}
```

​
`A.hx`

```
import C;
​
class A extends Y {
public function new() { super(); }
public function foobar():Void { }
}
```

​
`B.hx`

```
import A;
​
class B extends Y {
public function new() { super(); }
}
```

​
`C.hx`

```
class C {
private var a:A;
public function new() { a.foobar(); }
}
```

​
`X.hx`

```
@:autoBuild(Macro.build())
interface X { }
```

​
`Y.hx`

```
import B;
​
class Y implements X {
public function new() { }
}
```

​
`Macro.hx`

```
import haxe.macro.Context;
import haxe.macro.Expr.Field;
​
class Macro {
macro public static function build():Array<Field> {
Context.getType('C');
return Context.getBuildFields();
}
}
```

​
### Execution Environment

The above error occurred on the following environment.
​
Windows 7
Haxe 3.2.0, 3.2.1, 2015-10-28-development (6dea191)
​
​
### Detail

​
If we omit the following code, error will not raise.
​
`Context.getType('C');` inside Macro.hx
`import C;` inside A.hx
`import A;` inside B.hx
`import B;` inside Y.hx
​
moreover if we omit the following inheritance, error will not raise too.
`extends Y` inside A.hx
`implements Macro` inside Y.hx

NOTE : Error does not occur in 3.1.3, 3.1.2

**Comment by yar3333** [comment]
Looks like #4404.

**Comment by Simn** [comment]
#4404 has been closed, can you check if this has been resolved too?

**Comment by ncannasse** [comment]
Closing due to lack of feedback
