### ISSUE TITLE
Macro RegEx support depended on development platform

### ISSUE THREAD

**Issue by er453r** [HaxeFoundation/haxe#4625]
If RegEx is used in a macro. the RegEx implementation used is system depended - so the same code does not work on all platforms.

Tested on win x64 (works), on linux x64 (ubuntu) it does not. Both 3.2.1 installed from official binaries.

How can I fix this on linux? It is my main development platform...

More info and examples:
http://old.haxe.org/forum/thread/3395#nabble-td6680244
https://github.com/fponticelli/thx.core/issues/50
https://github.com/openfl/openfl/issues/920
http://community.openfl.org/t/macro-errors-with-shaders-filters/6867

**Comment by andyli** [comment]
Check whether this fix your issue or not => https://groups.google.com/d/msg/haxelang/EkGQw5qCR-0/BAavEcEzDAAJ

**Comment by er453r** [comment]
Yay, it fixes it! Still, I wouldn't close the issue until ppa packages fix it.

**Comment by andyli** [comment]
Good to know!
Usually we close issues when the fixes are merged in the repo (or else it would be hard to manage). And this is the case (#4604). So I will close it.

**Comment by Waynetron** [comment]
I'm still having this issue on OSX 10.11.3

**Comment by andyli** [comment]
@Waynetron How did you install haxe? Using the installer from haxe.org/download, or using homebrew? What is the Haxe and Neko version?

**Comment by Waynetron** [comment]
I can't remember how I installed it. But I checked 'brew list' and haxe and neko are both in there.
haxe: stable 3.2.1
neko: stable 2.0.0-22c49a8
I'm running El Capitan, if that helps.

**Comment by andyli** [comment]
The homebrew installed haxe and neko work properly on my Macbook with El Capitan. I would suggest you to check a few things:

```
# check if the versions match with what homebrew said
haxe -version
neko -version

# find out where haxe and neko are installed
which haxe
which neko

# find out the path to libneko.dylib
otool -L $(which neko)

# see if all the architectures are x86_64
file $(which haxe)
file $(which neko)
file $(otool -L $(which neko) | grep -Eo /.*/libneko.*.dylib)
```

For proper regex support and other things to work in macros context, the haxe compiler has to load "libneko". A few reasons will make it fail to do so:

1. "libneko" is not in PATH. On Mac, the default installation location, "/usr/local/lib", should be fine.
2. The arch of "libneko" and "haxe" do not match. On Mac, both of them should be x86_64.

It is also possible that there is an old installation of neko located somewhere such that it takes higher precedence over the newer one. So make such only one instance of neko (and haxe) is installed.

**Comment by Waynetron** [comment]
There was a haxe version mismatch as you suggested. I reinstalled Haxe and Neko through homebrew and now everything is working. Thank you!
