### ISSUE TITLE
PHP: always passing null for optional arguments is not good, especially in externs

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4628]
Optional args `?arg:Type` are always filled with `null` in PHP, when they are left out in the function call. In your own functions you can work around this but in externs this can override PHP default values or lead to errors (e.g. when an optional argument needs to be passed by reference).
Could this be fixed, at least for externs, so that unused optional args are not passed as `null`? I tried to work around this with `inline` or macros but to no avail. Closures also don't work, because we still have these terrible old closure constructs....
If someone can point me to the place in the genphp code, I could try a pull request.

**Comment by RealyUniqueName** [comment]
This is a somewhat core thing in old php generator. It will affect dynamic methods, handling arguments with default values, external code which interacts with haxe-generated one. I can't predict all the ways this change can influence existing code.
For externs you can workaround this with overloads:
```
@:overload(function ( error_handler:Function) : Dynamic {})
function set_error_handler ( error_handler:Function, error_types:Int) : Dynamic;
```
This is not going to be changed for old php generator, sorry.
You can move to new generator (`-D php7`), which does not use `null` for skipped optional arguments.
