### ISSUE TITLE
Haxe 3.2.1 Sys.stdin().readLine() inconsistency between cpp and neko on osx 10.10.5

### ISSUE THREAD

**Issue by jamiltron** [HaxeFoundation/haxe#4631]
``` haxe
class Main {
  public static function main() {
    var s = Sys.stdin().readLine();
    trace(s);
  }
}
```

When running the above code via cpp I get stuck in the readLine section, no matter how many newlines I enter. This is both when running the output as a 32bit or a 64bit binary.

However, if I run this by targeting neko the code runs as expected.

It should be worth noting that I have tried both iTerm 2.1.4 as well as the default Terminal application of version 2.5.3.

**Comment by jamiltron** [comment]
I recently updated to OSX 10.11.1, and this is still an issue.

**Comment by MatthijsKamstra** [comment]
I am still on 10.10.5 and experience the same issue, but I have it with Neko.

**Comment by hughsando** [comment]
I have removed the setbuf(stdin,0) which seemed to cause problems on windows.
It would seem that this is intended to allow readbyte to return each character as it becomes available, but it does not do this and only seems to cause problems.
Hopefully this solves your problems too.

**Comment by hughsando** [comment]
This seems to be working on the cpp targets.
Not sure if neko uses setbuf on stdin?

**Comment by ncannasse** [comment]
We don't use setbuf on stdin, I'll close. Please reopen if still reproducible.
