### ISSUE TITLE
Typedef that references itself in function arguments fails to compile in class-structure unification

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#4640]
```haxe
typedef Vector = {
	function add(v:Vector):Vector;
	function clone():Vector;
	function length():Float;
}
class Vector2{
	public function add(v:Vector2):Vector2
	public function clone():Vector2
	public function length():Float
}
```
When unifying a class with the structure Vector, the above compiles when ```add()``` is either removed or set to @:optional, otherwise compile fails.

Seems to be because Vector is referenced in a function argument in ```add```, but it's ok if Vector is referenced only in the return value (see ```clone```).

Demo http://try.haxe.org/#43d10

Tested in nightly cc13b2b

**Comment by Simn** [comment]
The error is correct because `A -> A` and `B -> B` only unify if `A == B`. Function arguments require contravariance, not covariance like the return type.

**Comment by haxiomic** [comment]
Thanks for the clarification Simn
