### ISSUE TITLE
@:jsRequire does not work for enums and interfaces

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#4641]
I'm trying to import enums from another js file with @:jsRequire metadata. While @:jsRequire works perfectly for classes, Haxe compiler just ignore jsRequire meta of enums and interfaces.
That makes impossible to do things like equality checks across js files, or implementing interfaces from other js files. Switching with enums still work across modules though, since it uses integer value of enums.

```Haxe
package openfl.display3D;

@:flatEnum @:jsRequire("openfl", "openfl_display3D_Context3DProfile") enum Context3DProfile
{
	BASELINE;
	BASELINE_CONSTRAINED;
	BASELINE_EXTENDED;
}
```

```Haxe
// @:jsRequire is ignored
var openfl_display3D_Context3DProfile = $hxClasses["openfl.display3D.Context3DProfile"] = { __ename__ : ["openfl","display3D","Context3DProfile"], __constructs__ : ["BASELINE","BASELINE_CONSTRAINED","BASELINE_EXTENDED"] };
```

I'm avoiding this issue by manually importing enums with require calls.

```Haxe
    #if (nodejs && shared_code)
    public static function __init__():Void
    {
        untyped
        {
			var openfl_display3D_Context3DProfile = require("openfl").openfl_display3D_Context3DProfile;
            var openfl_display_StageAlign = require("openfl").openfl_display_StageAlign;
            var openfl_display_StageScaleMode = require("openfl").openfl_display_StageScaleMode;
            var starling_animation_IAnimatable = require("starling").starling_animation_IAnimatable;
        }
    }
    #end
```

**Comment by Simn** [comment]
@nadako: Can you check that?

**Comment by nadako** [comment]
`@:jsRequire` only makes sense and works for `extern` classes and enums.

**Comment by vroad** [comment]
I forgot to add extern to enums in my genertor, Sorry about that.

But I don't know why this doesn't work for ```extern``` interfaces. js code generated from interfaces has constructor and prototype, aren't they same as classes?
```Haxe
package starling.animation;

@:jsRequire("starling", "starling_animation_IAnimatable") extern interface IAnimatable
{
	function advanceTime(time:Float) : Void;
}
```
```javascript
var starling_animation_IAnimatable = function() { };
$hxClasses["starling.animation.IAnimatable"] = starling_animation_IAnimatable;
starling_animation_IAnimatable.__name__ = ["starling","animation","IAnimatable"];
starling_animation_IAnimatable.prototype = {
	advanceTime: null
	,__class__: starling_animation_IAnimatable
};
```

**Comment by vroad** [comment]
@nadako Is that really bad idea to import Haxe interfaces from other js files? So far ```IAnimatable``` is working correctly for me.

**Comment by nadako** [comment]
I'll look into the issue regarding interfaces

**Comment by nadako** [comment]
Are you sure it doesn't work for extern interfaces? Because I just tried and it does: http://try.haxe.org/#923C5

I.e. `@:jsRequire("starling", "starling_animation_IAnimatable") extern interface IAnimatable` generates `var IAnimatable = require("starling").starling_animation_IAnimatable;`

**Comment by vroad** [comment]
@:nadako I think I've just found the cause of interface issue. With dce enabled, Haxe generates nothing for IAnimatable, even though I'm using a class that implements IAnimatable. If I turn off dce with -dce no,  (or refer to IAnimatable class from somewhere else), my app starts working again.

```
starling_text_ExtendedTextField.__interfaces__ = [starling_animation_IAnimatable
];
                                                  ^

ReferenceError: starling_animation_IAnimatable is not defined
```
```
var animatable:Dynamic = starling.animation.IAnimatable;
```

But on try haxe, IAnimatable is not deleted for some reason. http://try.haxe.org/#C16fc

**Comment by vroad** [comment]
@nadako I tried to reproduce this issue with simple code but couldn't. I'm not sure why ```var IAnimatable = require("starling").starling_animation_IAnimatable;``` is removed only on my app.
