### ISSUE TITLE
On cpp, Comparing Null<Float> value with NaN returns different result than js

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#4642]
This code returns different result on cpp. While js returns false if value is NaN, cpp returns true.  Perhaps because cpp is just checking if value is the same for this case?

```Haxe
class Main 
{
	static function main() 
	{
		var value:Null<Float> = Math.NaN;
		trace(value == value);
	}
	
}
```

**Comment by Simn** [comment]
@hughsando: Can you comment on that? I vaguely remember talking about this before.

**Comment by hughsando** [comment]
```Null<Float>``` causes boxing into Dynamic.  The Dynamic op== sees that the pointers are the same, so it assumes the objects are the same.  I guess you would get a similar issue if you had a custom compare function that always said the objects were different.
The pointer== optimization is quite nice - not sure how I can solve this one without potentially making other places slower.
Maybe I'll just make the fix and see if this shows up on some hot-path somewhere.

**Comment by ncannasse** [comment]
We can agree that Dynamic comparison is unspecified, but could you not bypass pointer check for `Null<Float>` only ?

**Comment by hughsando** [comment]
No, Null<Float> is implemented with Dynamic.  I have thought about doing
something else, but would need a compelling performance benchmark to
properly motivate me.
I have made the change because if you are using Null<Float> you are
probably more interested in convenience (and accuracy) than performance.
