### ISSUE TITLE
on cpp, if (!someArray) is true while it's false on js

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#4643]
If I treat some array as a Bool value and do condition check, cpp and js gives me different result.
I understand that it's bad to use expression like (!data) on Haxe, but why the result becomes different on each target?
On cpp ```(!data)``` becomes true somehow.

```Haxe
class Test {
    static function main() {
        var data:Dynamic = ["Some string"];
        if (!data)
            trace("(!data) == true");
        else
            trace("(!data) == false");
    }
}
```

**Comment by ncannasse** [comment]
! works only on actual Bool values in Haxe. When using a Dynamic which is not a Bool, the result is unspecified.
