### ISSUE TITLE
[js] HaxeError wrapping when re-throwing caught Dynamic exceptions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4644]
```haxe
try {
    throw new js.Error("EPIC FAIL");
} catch (e:Dynamic) {
    throw e;
}
```
generates:
```js
try {
	throw new Error("EPIC FAIL");
} catch( e ) {
	if (e instanceof js__$Boot_HaxeError) e = e.val;
	throw new js__$Boot_HaxeError(e);
}
```
so the `Error` object gets wrapped in a `HaxeError` object.

we should handle this by adding run-time check when dealing with throwing Dynamic/Monomorph: `throw (e instanceof Error) ? e : new HaxeError(e)`.

**Comment by nadako** [comment]
or maybe we should not wrap at all in case of `Dynamic`? cc @andyli, @aduros, @ncannasse, @clemos

**Comment by andyli** [comment]
I agree a runtime check of `instanceof Error` is appropriate.
