### ISSUE TITLE
Flash problem with Null<Int> conversion in out of bounds array references

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#4645]
Null testing for `Null<Int>` of an out of bounds array reference performs incorrectly in flash, but works properly in javascript. Please see the following code snippet, which returns 0 in flash but 5 in javascript. (Easy to test via tryhaxe)

```
class Test {
    static function main() {
        var array:Array<Int> = [];
        trace("Result " + ifnull(array[0],5));
    }
	static public function ifnull<T>(a:Null<T>, b:T):T {
		if (a == null) {
			return b;
		}
        var aa:T = a;
        return aa;
	}
}

**Comment by Simn** [comment]
What about other static targets such as C++?

**Comment by Simn** [comment]
Actually this is working as designed. See http://haxe.org/manual/std-Array.html:

> If a read access is made on a non-existing index, a target-dependent value is returned.

On static targets you can't get `null` from an `Array<Int>`, so you get `0` instead.
