### ISSUE TITLE
Reification for Const type parameter not fully supported.

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#4646]
Whereas it is possible to use reification for String const type parameter like so:

```
macro class Bar {
    function myMeth() : Foo<'$cstringName'>;
}
```

It is, to my knowledge not possible to specify it via reification for other constant expressions:
http://haxe.org/manual/expression-constants.html

Which syntax option do we have?

**Comment by Simn** [comment]
This has always been a parsing problem because it's not obvious how to distinguish type and expression parsing. A common approach is to enclose the expression in `[]`, e.g. `Foo<[$expr]>`. I can't see how we could improve on this given that any identifier is treated as part of a type.

**Comment by Simn** [comment]
What I said.
