### ISSUE TITLE
[dce] enum support code generated for @:fakeEnum extern enums

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4647]
The definition of extern fake enums, like this:
```haxe
@:fakeEnum(String)
extern enum E {
    A;
    B;
}
```
is making Haxe generate support code used by normal (non-fake) enum implementations, such as `toString`-related code on JavaScript, or `Enum` base class on Python.

This happens because of `has_enum` feature added for any enums, including fake ones, which doesn't make much sense, since fake enums are special and don't use the generated support code.

I propose adding a check for `@:fakeEnum` and not add `has_enum` feature for those.

**Comment by Simn** [comment]
The core question is if we want to make `@:fakeEnum` a proper language feature or deprecate it. Between normal enums, extern enums, `@:fakeEnum` and `@:enum` abstracts we have to be careful not to overload the language with enumesque concepts that are ultimately very similar.

**Comment by nadako** [comment]
To me, `@:enum abstract` seems to be more correct way to express a finite set of non-`enum` values such as String or Int than `@:fakeEnum(Int)` which looks hacky, but the problem is that with `@:enum abstract` we can only use constant values and we don't have a way to use some extern field as an enum abstract constructor. If there would be a way to do that, I'm all for deprecating `@:fakeEnum`.

E.g. we have some constant definitions in a JavaScript file:
```js
var HttpStatus = {
    Ok: 200,
    NotFound: 404
}
```
using `@:fakeEnum` we can have enum-like behaviour in Haxe without knowing actual values:
```haxe
@:fakeEnum(Int) extern enum HttpStatus {
    Ok;
    NotFound;
}
```
with current `@:enum abstracts` we have to basically duplicate the thing in Haxe code which is annoying and not future-proof:
```haxe
@:enum abstract HttpStatus(Int) {
    var Ok = 200;
    var NotFound = 404;
}
```
