### ISSUE TITLE
net-lib generates code for deprecated code in c# (unity3d+haxe)

### ISSUE THREAD

**Issue by krupin-maxim** [HaxeFoundation/haxe#4648]
I am trying to use haxe with Unity3d 5.1. I use recipe https://gist.github.com/nadako/9370128 but with "-D no-compilation".

Unity3d writes errors in console:

> "Main.hx(5,87): error CS0619: `UnityEngine.Component.rigidbody' is obsolete:`Property rigidbody has been deprecated. Use GetComponent<Rigidbody>() instead. (UnityUpgradable)'"

And It writes for every field: rigidbody2D, camera, light, etc., which is marked as obsolete in Unity3d 5.1: https://github.com/MattRix/UnityDecompiled/blob/master/UnityEngine/UnityEngine/Component.cs 

But haxe generates code for it like:

> case 1895479501:
>  {
>   #line 5 "/hdd/maxim/sp2/game/unity3d/src/Main.hx"
>   return ((global::UnityEngine.Component) (this.rigidbody) );
> }

It is strange that Unity3d generates errors instead warnings, but we have this fact. So, it will be good option for cancel generating code for obsolete code.

**Comment by nadako** [comment]
I tried looking into this. We could filter out fields marked with `[Obsolete]` when generating reflection helpers, but right now that information is lost when types are loaded from .NET dll, so we need to maintain it somehow.

As the practical solution to this issue. One could generate MonoBehaviours with `@:nativeGen` so no reflection helpers are created. Or use a a base class like this:
```haxe
@:nativeChildren class HaxeBehaviour extends MonoBehaviour {}
```

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
