### ISSUE TITLE
Java target: "sys.net.Socket" is not working

### ISSUE THREAD

**Issue by matulkum** [HaxeFoundation/haxe#4650]
example: 

```
package;
class Main {
  static function main() {
    new Main();
    var s = sys.net.Socket();
  }
}
```
With "-dce no" compiler exits with "Class\<sys.net.Socket\> cannot be called".
With "-dce full" compiler exits with "Type name  is redefined from module java.lang.Double" (which is probably another bug all together).

**Comment by ncannasse** [comment]
use "new sys.net.Socket()"

**Comment by matulkum** [comment]
alright.. that is kind of embarrassing. Thx Nicolas. It is working. Should stop working so late ;). Sorry for the false alarm.

I get this warning though:
"/usr/local/lib/haxe/std/java/_std/sys/net/Socket.hx:44: characters 14-35 : Warning : Usage of this field is deprecated"

Which is not to bad I guess.

The problem with "Type name  is redefined from module java.lang.Double" remains though. It starts appearing sometimes independently of using a socket. It gets resolved by restarting the Haxe competition server. I think I saw an issue about that already, so I think it is known already.

Cheers.. and close this issue quickly please.

**Comment by ncannasse** [comment]
Can you open another issue with the java.lang.Double issue with a small reproducing example, thank!
