### ISSUE TITLE
cpp.vm.Lock, can't acquire lock

### ISSUE THREAD

**Issue by wiggin77** [HaxeFoundation/haxe#4654]
Unless I'm misunderstanding the semantics of this Lock object, I would think that after creating a lock it could be immediately acquired.  For the code below, the lock.wait(5) call always times out after 5 seconds and returns false.  Same behaviour for Neko.
```haxe
package ;

#if cpp
import cpp.vm.Lock;
#elseif neko
import neko.vm.Lock;
#end

class TestSimple {
	public static function main() {
		var lock = new Lock();

		if(lock.wait(5)) 	{
			trace("Main thread aquired lock");
			lock.release();
		}
		else 	{
			trace("huh?");
		}
	}
}
```

Haxe 3.2.1, hxcpp 3.2.193, Linux Mint x64

**Comment by wiggin77** [comment]
Also tested on MacOS (El Capitan) with same result.  Thanks!

**Comment by andyli** [comment]
The doc on [neko.vm.Lock](https://github.com/HaxeFoundation/haxe/blob/development/std/neko/vm/Lock.hx#L28):
```
Creates a lock which is initially locked.
```

It is unfortunate that the doc is added a few days after 3.2.0, so it is not visible on api.haxe.org.

**Comment by wiggin77** [comment]
Thanks Andy.  I only checked the cpp source (and api.haxe.org) which didn't have that comment.  Much appreciated.
