### ISSUE TITLE
Support meta on anonymous object

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4655]
Is it possible to support meta in both ways of anonymous object declaration?

```haxe
typedef A = {
    @:myMeta // ok
    var a:Int;
}

typedef B = {
    @:myMeta // fail
    a:Int,
}
```

**Comment by Simn** [comment]
This is similar to #3083 and might have the same problems.

**Comment by Simn** [comment]
We cannot support this after all, see https://github.com/HaxeFoundation/haxe/issues/3083#issuecomment-159977193
