### ISSUE TITLE
[PHP] numbered back references don't work in Ereg.replace 

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4657]
As Andy already mentioned in #4430, numbered back references or capturing groups or whatever they are called don't work in PHP. Looking at the code from `php._std.EReg.hx` there is a lot of escaping going on in `replace` , but generated PHP-code always adds another `\`, e.g.:
`by = untyped __call__("str_replace", "\\$", "\\\\$", by);`
turns to:
`$by = str_replace("\\\$", "\\\\\$", $by);`
Don't know if this is intended nor where this comes from. Maye somebody knows...

**Comment by mockey** [comment]
So could it be that `$` is auto-escaped to `\$` somehow?
Also this line:
`untyped __php__("if(!preg_match('/\\\\([^?].+?\\\\)/', $this->re)) $by = preg_replace('/\\$(\\d+)/', '\\\\\\$\\1', $by)");`
that turns to:
`if(!preg_match('/\\([^?].+?\\)/', $this->re)) $by = preg_replace('/\$(\d+)/', '\\\$\1', $by);`
seems to be a problem. I don't quite understand it, I think it checks for non-capturing groups (starting with `(?:`) and replaces `$1` with `\\$1` or so. Anyway, either:
`if(!preg_match('/\\([^?].+?\\)/', $this->re)) $by = preg_replace('/$(\d+)/', '\\$\1', $by);`
or:
`if(!preg_match('/\\([^?].+?\\)/', $this->re)) $by = preg_replace("/\$(\d+)"', "\\\$\1", $by);`
seems to work for me. So maybe the quotes are simply wrong here?
Will do some further test...

**Comment by Simn** [comment]
I have no idea what `EReg.replace` is doing/trying to do with all these replaces. It's true that genphp escapes `$` to `\$` in `escape_bin`, but in my experiments changing that has no effect.

**Comment by mockey** [comment]
You mean this:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L280
So `\ " $` are escaped automatically, but not in `__php__` magic function it seems.
