### ISSUE TITLE
Calling super in wrong places

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4659]
It seems we can call `super` in a lot of places where I think this should give a compiler error. 

I found there should be made a difference of the cases:
 * Calling `super.foo` in an field that overrides something else.
    I would expect an error like this: _""Field 'B.bar' is marked as 'override' but doesn't allow  'super.foo' to be called. Suggestion: use 'this.foo' or 'super.bar'.""_
 * Calling `super` in a field that does not override something.
   I would expect an error like this: _"Field 'B.baz' isn't marked as 'override' and doesn't allow  'super' to be called. Suggestion: use 'this.foo'."_

Example
```haxe
class Test {
    static function main() {
		var b = new B();
		trace(b.foo());
		trace(b.bar());
		trace(b.baz());
    }
}

class A {
	public function new() {}
	public function foo() return 'expected string 1';
	public function bar() return 'expected string 2';
}

class B extends A {
	public function new() super();
	override public function foo() return super.foo();
    override public function bar() {
        // I expect an error like this:
        // "Field 'B.bar' is marked as 'override' but doesn't allow  'super.foo' to be called. Suggestion: use 'this.foo' or 'super.bar'."
        return super.foo();
    }
    
	public function baz() {
        // I expect an error like this:
        // "Field 'B.baz' isn't marked as 'override' and doesn't allow  'super' to be called. Suggestion: use 'this.foo'."
		return super.foo();
	}
}
```
http://try.haxe.org/#2cC84

I had a big refactoring which didn't renamed the super calls and it took me quite a while to spot where why some things were wrong.

Suggestion: I am aware there are cases you want to access super (when getters/setters functions in current class are involved which you want to avoid calling). It might be an idea to add a `@:access(super)` or something to allow access to any field in the super  class for the rare cases you want this.

**Comment by ncannasse** [comment]
Calling super.foo() in baz() seems legit to me

**Comment by ncannasse** [comment]
Also, what if the class is subclassed and we want to call the superclass method and not the (maybe later) overriden method?

**Comment by nadako** [comment]
For the after-refactoring situation, I think there's a macro for that (tm)! Just add a global @:build macros that checks whether `super` calls are valid for your case and if not, prints a warning with a position.

**Comment by markknol** [comment]
> Calling super.foo() in baz() seems legit to me

 Ok @ncannasse thanks! Personally I would find it elegant if `super` was more restricted by design, but if that's not plan, I think the issue can be closed.

> what if the class is subclassed and we want to call the superclass method and not the (maybe later) overriden method?

That's why I suggested `@:access(super)` or something.

@nadako I find this the other way around (and too much hazzle), but do you have such macro in your macro-library  which I can borrow :yum:
