### ISSUE TITLE
Compiler.includeFile doesn't work when called from within a macro

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4660]
Suppose we have:
```haxe
class VersionWarning {
    static function include() {
        haxe.macro.Compiler.includeFile("hxnodejs-version-warning.js");
    }
}
```
This silently doesn't work if we call `--macro VersionWarning.include()`, because `includeFile` is a `macro` method itself, so there's some mess happening with contexts.

**Comment by nadako** [comment]
I think we can simply move the `Top|Closure` part into a separate non-macro function.

**Comment by Simn** [comment]
I think it's good practice to have `macro` functions as sort of entry points and make them call a non-macro function that has the implementation. These functions can then safely be called from both macro and non-macro context.

**Comment by Simn** [comment]
The only problem is that you need two different function names.

**Comment by nadako** [comment]
For this particular function we probably could do `#if !macro macro #end function`

**Comment by Simn** [comment]
Did you try that?

**Comment by nadako** [comment]
Not really, but I will now :-P
