### ISSUE TITLE
Inheriting generic class type parameters in generic function type parameters?

### ISSUE THREAD

**Issue by Neverbirth** [HaxeFoundation/haxe#4668]
First, sorry if my explanation turns out to be not as clear as I'd like, I'll do my best.

Right now if we want to create new instances from type parameters we have to decorate a field with @:generic, but it comes with its set of limitations like not being possible to have static fields inside a generic class. I was wondering, would it be possible to have something similar to this:

    class GenericTest<T:(TestClass, {function new(arg:String):Void;})>
    {
        public function new(){}
    
        public function someTask():Void
        {
             var instance:T = getInstance("foo");
        }

        @:generic
        public function getInstance<S:T>(arg:String):S
        {
             return new S(arg);
        }
    }

This seems to compile fine:

    class GenericTest<T:(TestClass, {function new(arg:String):Void;})>
    {
        public function new(){}

        public function someTask():Void
        {
             var instance:T = getInstance("foo");
        }

       @:generic
       private function getInstance<S:(TestClass, {function new(arg:String):Void;})>(arg:String):S
       {
            return new S(arg);
       }
    }

But when running a compiled JS application there are errors like GenericTest_T is not defined. I guess that the reason behind the problem is that the class itself is not marked as generic, and it's not generating some needed code.

If this is not possible is there some other workaround? Right now there is some codebase with Class<> and Type.createInstances lines of code that could get a better look. I guess this could also be done with Macros, but I still have to learn about them and I'd say developers would expect this to be supported at the level of the language itself.

**Comment by Simn** [comment]
That's interesting. The question is if a transitive relation like that makes it sound to assume the presence of a constructor. Given that it works for normal fields I suppose we can support it for constructors as well.

**Comment by Neverbirth** [comment]
Mmm, not really sure if I completely understood your reply, because "assume the presence of a constructor" makes it sound like instance creation in this case is new for you, but surely it's not. If so, it's a known feature, for example seen [here](http://old.haxe.org/manual/haxe3/features#generic-functions).

The problem is that in order to use it, it's mandatory to use @:generic, and if doing so for a class you cannot use static fields. So my question is if we could get this work around we could have both things at once...

**Comment by Simn** [comment]
The example you link is `T -> { new }` whereas you're trying to do `S -> T -> { new }`. That's why I mention "transitive relation": `S` itself is not constrained to have a constructor, it is only via the constraints of `T` that a constructor can be found.

All I'm saying is that we have to make sure that this is sound.

**Comment by Neverbirth** [comment]
OK, thought so, it's that sentence that made me doubt. Forgot to attach some simple online sample: http://try.haxe.org/#c7752

**Comment by Simn** [comment]
That's a different example and in fact should not compile. As you see it generates nonsense, referring to `GenericTest_T` as if it was a proper class.

**Comment by Simn** [comment]
To clarify, we can support this:

```haxe
typedef Constructible = {
	function new(arg:String):Void;
}

class GenericTest<T:Constructible> {
	public function new(){}

	@:generic
	public function getInstance<S:T>(arg:String):S {
		return new S(arg);
	}
}

class Main {
	static function main() {
		var gen = new GenericTest<haxe.Template>();
		var t = gen.getInstance("my ::template::");
		trace(t.execute({template: "foo"})); // my foo

		var gen = new GenericTest<String>();
		var t = gen.getInstance("my string");
		trace(t); // my string
	}
}
```

That is, `GenericTest` is being used with a concrete type, not a type parameter like in your example.

**Comment by Neverbirth** [comment]
Of course, that would be better for me as well.

**Comment by Neverbirth** [comment]
Wow, I should look into how to get a nightly build. Thank you very much.
