### ISSUE TITLE
-cmd and stdin (mac / linux)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#4669]
When using `-cmd` in an hxml file, it doesn't appear that STDIN is being redirected properly -- the program does not respond to user input.

This may be an hxcpp or haxelib problem, not sure. Perhaps related to #3859 (a different issue, but similar regarding i/o in `-cmd` mode), except that's neko/output and this is hxcpp/input. But I assume stdout redirection should affect all runtimes?

Here's a testcase, a simple CLI:

**build.hxml**

```hxml
-main Main
-debug
-cpp export
-cmd export/Main-debug
```

**Main.hx** (note, neither readByte nor getChar work)

```haxe
class Main {
  static function main() {
    while (true) {
      Sys.stdout().writeString("Something, or (q)uit ?\n");
      var i = Sys.getChar(true);
      //var i = Sys.stdin().readByte();
      trace(i);
      if (i==113) break;
    }
    trace("Goodbye!");
  }
}
```

**Expected behavior:** hitting keys should print keycodes, q should exit.

**Observed behavior:** hitting keys does nothing, ctrl-c is required to exit.

I tested both hxcpp and neko on linux and mac, both exhibit the problem. Simon tested windows and didn't see the issue.

If you launch the program standalone, it works as expected. Just not when launched via `-cmd`

**Comment by Simn** [comment]
For what it's worth this works fine for me on Windows.

**Comment by jcward** [comment]
Thanks, @Simn. I tested mac and it's also broken there. I'll update the bug description.

**Comment by Simn** [comment]
I can reproduce the problem on Linux.

**Comment by ncannasse** [comment]
Does it works after you hit enter?

**Comment by Simn** [comment]
No.

**Comment by ncannasse** [comment]
Uhm, that seems normal: we're using Unix.open_process_full in main.ml/run_command and are not redirecting our stdin to the process stdin.

We instead need to create new pout/perr pipes and use create_process, as shown is 
http://stackoverflow.com/questions/26982027/why-is-open-process-full-not-returning-the-stdout-contents-of-the-externam-proce

I'll leave @Simn to implement + test on Windows/Linux

**Comment by Simn** [comment]
It's pretty awkward for me to test this through my Ubuntu VM. Maybe @waneck could help out here?

**Comment by jcward** [comment]
I could potentially validate a change on Ubuntu. You could send me a branch, patch, or updated main.ml.
