### ISSUE TITLE
[js] Enum is not defined

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4670]
```haxe
enum E {
    A;
}

class Main {
    static function main() {
        Std.is(A, E);
    }
}
```

`haxe -main Main -js main.js -cmd node main.js` gives:

```
D:\Code\playground\main.js:132
        if(cl == Enum && o.__ename__ != null) return true;
                 ^
ReferenceError: Enum is not defined
    at Function.js_Boot.__instanceof (D:\Code\playground\main.js:132:12)
    at Function.Main.main (D:\Code\playground\main.js:11:10)
```

The `Enum` is not present in the generated code indeed.

**Comment by Simn** [comment]
This has come up every so often and I still don't quite understand why it happens. Now that it fails in the unit test I guess I'll have to find out though!

**Comment by nadako** [comment]
Seems like f1b9d366062ebee544d85a3ccd32fab3c8026938 borked it.

**Comment by Simn** [comment]
Note for the future: On JS `Std.__init__` has some stuff like `var Enum = {};` which relies on the variable being generated as-is. This seems pretty brittle and should probably be replaced by `__js__`.
