### ISSUE TITLE
python socket shutdown error (no attribute 'SHUT_WR')

### ISSUE THREAD

**Issue by foutaise** [HaxeFoundation/haxe#4673]
Issue with socket shutdown code for python platform
(generated class sys_net_Socket, method shutdown)

```
$ cat Issue.hx 
class Issue {
    static public function main() {
        var req = new haxe.Http( "http://haxe.org/");
        req.onError = function(data) {
            trace(data);
        };
        req.onData = function(data) {
            trace(data);
        };
        req.request(false);
    }
}
```

```
$ haxe -python Issue.py -main Issue
```

```
$ python3 Issue.py
AttributeError("type object 'socket' has no attribute 'SHUT_WR'",)
```

The generated code import the socket.socket class as python_lib_net_Socket,
and try to use python_lib_net_Socket.SHUT_WR, but SHUT_WR is
defined in the socket module, not as part of the socket.socket class.
Same thing for SHUT_RDWR and SHUT_RD.

```
$ python3 --version
Python 3.4.2
```

```
$ haxe -v
Haxe Compiler 3.3.0 - (C)2005-2015 Haxe Foundation
```

**Comment by Simn** [comment]
@frabbit: Are you still alive?

**Comment by nadako** [comment]
python.lib.net.Socket is messy. i think we should follow the convention and have `python.lib.Socket` for the `socket` module and `python.lib.socket.Socket` for the class, like we do in hxnodejs (and I think agreed to do in python).

**Comment by nadako** [comment]
I fixed this particular issue by moving constants into a new class that corresponds to `socket` python module, but I still think we should clean up python.lib to follow single convention (see #3684), so I'll leave this open until we at least clean up the socket stuff.

**Comment by frabbit** [comment]
@Simn yes, alive but very busy at the moment :(, i think i will find some time in december to help fix some python bugs.

**Comment by Simn** [comment]
No problem, there's nothing urgent going on. Come hang out in #haxe-dev some time!

**Comment by foutaise** [comment]
thanks @nadako for your time!

**Comment by frabbit** [comment]
@nadako is this still a thing?

**Comment by frabbit** [comment]
@nadako should i move the SocketModule into python.lib.Socket and the net package becomes socket

**Comment by frabbit** [comment]
i adjusted the package/class names here 0b094760269cb984903bf2e02ad3c6b8c4176566.
