### ISSUE TITLE
Could not compile shader, shader.hx

### ISSUE THREAD

**Issue by jobs-git** [HaxeFoundation/haxe#4674]
I get this error when I compile windows.

**Comment by Simn** [comment]
You got the wrong repository. What library/framework are you using?

**Comment by jobs-git** [comment]
Shader.hx is from std/flash/display of Haxe 3.2.1
I think almost every library/framework depends on it.

I got everything compiled successfully but when I run it, I get this error.

**Comment by Simn** [comment]
[Our Shader.hx](https://github.com/HaxeFoundation/haxe/blob/development/std/flash/display/Shader.hx) is just a boring extern. Are you maybe using OpenFL? They have some logic in [their version](https://github.com/openfl/openfl/blob/master/openfl/display/Shader.hx).

**Comment by jobs-git** [comment]
I see. Versions is what stackoverflow was pointing too. I think I really got the wrong repository. Thanks for pointing that out.
