### ISSUE TITLE
"Cast type parameters must be Dynamic" since 3.2

### ISSUE THREAD

**Issue by vbence** [HaxeFoundation/haxe#4675]
This is probably a side-effect of the changes concerning `cast`. The following code compiles on 3.1.3 but not on 3.2.1 (or 3.2.0):

```
class Caster {

    public static function main() {
    	var m: Map<String, Dynamic> = new Map();
    	m.set("a", 1);

    	someFunction(m);
    }

    public static function someFunction(arg: Dynamic) {
    	var map: Map<String, Dynamic> = cast(arg, Map<String, Dynamic>);
    	for (i in map.keys()) {
    		trace(i);
    	}
    }

}
```

**Comment by Simn** [comment]
I think I know why this happens.

Did this really work in 3.1.3?

**Comment by vbence** [comment]
Yes, it totally did :)

In this simple example, unsafe casting works well
```
var map: Map<String, Dynamic> = cast arg;
```
... but in a real program the very same scenario results in *Cast type parameters must be Dynamic* even with the unsafe syntax.

**Comment by vbence** [comment]
Wow, thanks!
