### ISSUE TITLE
Wrong type parameter constraint checking error

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#4676]
```
typedef A = {
  var y : Int;
}

typedef B = {
  var x : Int;
}

class Test {
    

  static function foo<V, T : (V, A), U : (V, B)>(x : T) : Void {
  }

  static function main() {
    foo("toto");
  }
}
```

ouputs this error:

Build failure
Test.hx:16: characters 4-7 : Constraint check failure for foo.T
Test.hx:16: characters 4-7 : String should be B
Test.hx:16: characters 4-7 : String should be { x : Int }
Test.hx:16: characters 4-7 : String has no field x
Test.hx:16: characters 4-7 : Constraint check failure for foo.T
Test.hx:16: characters 4-7 : String should be A
Test.hx:16: characters 4-7 : String should be { y : Int }
Test.hx:16: characters 4-7 : String has no field y

Whereas 'String should be A' is correct, 'String should be B' is incorrect.

**Comment by Simn** [comment]
That looks like fun! Let's see if we can understand what happens:

Unification | Assign | To | Result
---|---|---|---
Call | `String` | `T` | `T/String`
Constraint check for `T` | `T/String` | `V` | `V/String`
Constraint check for `T` | `T/String` | `A` | "String should be A"
Constraint check for `U` | `U` | `V/String` | `U/String`
Constraint check for `U` | `U/String` | `B` | "String should be B"

This might be working as intended.

**Comment by sledorze** [comment]
Mmmm, thanks for the explanation.
I was thinking that the compiler would infer U as a subtype of both V (string) and B (typedef); a kind of type union.
From your explanation, I understand that no subtype representation exist in the compiler.

*Note: that maybe using 'String' for the example is misleading, the non shrinked version was involving only typedefs / anonymous*
