### ISSUE TITLE
`case EnumCtr(_1)` » "Capture variables must be lower-case"?

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4677]
Currently, if naming a capture variable as `_[number]`, an error being "Capture variables must be lower-case" is shown. `__` \ `___` \ ... are fine. `_[letter][number]` are also fine. What makes the numbers so upper-case? Is this the intended behaviour?

**Comment by Simn** [comment]
I'm not sure about this. It uses the same function the parser uses, which requires the first non-`_` to be lower-case. This is not true for digits, so this is technically consistent.

The original idea behind this limitation is to avoid problems with typos when matching on enums. This is under the assumption that most of the time enum constructors are upper-case.

I suppose we could allow `_1` if that makes someone happy.
