### ISSUE TITLE
Add haxe.macro.Compiler.addHaxelib()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4678]
`haxe.macro.Compiler.addHaxelib()` isn't too different from the already existing `addClassPath()` conceptually, but would be convenient to conditionalize the inclusion of a haxelib in some way. For example, you might only want to include a haxelib if it's installed (some way to check if a haxelib is installed would be handy for this use-case, like `Compiler.getHaxelibPath()`). With the `-lib` argument, you'd run into a compiler error if the lib isn't there.

**Comment by Simn** [comment]
@ncannasse: Do you see any behavioral problems with that? We would have to factor out some parts of main.ml to make them available elsewhere, but that might be a good idea anyway.

**Comment by ncannasse** [comment]
I'm a bit worried about it. Some haxelib can have extraParams.hxml which might include defines which will be changed after some code might have already been compiled...

**Comment by ncannasse** [comment]
Actually each haxelib also define its own -D as well

**Comment by Simn** [comment]
That's true, but then that's also an issue with `Compiler.define` and some of its other methods.

**Comment by Simn** [comment]
Haxelib's future is quite unclear at the moment, so let's not add features like this for the time being.
