### ISSUE TITLE
OCaml version to compile Haxe?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4682]
Can we maybe specify that? Because I'm right now on 4.02.3, which is (one of) the latest and it emits some deprecation warnings like `Warning 3: deprecated: String.create Use Bytes.create instead.`, but I reckon this should not be fixed but I should downgrade instead. Or maybe we can all upgrade to some recent version (I think @Simn said he's still on some 3.x version).

**Comment by Simn** [comment]
Yeah I'm still using OCaml 3.11 because it compiles quite nicely through MSVC.

I'm not sure we should specify this as long as the worst we're getting on OCaml 4+ are some warnings.

**Comment by andyli** [comment]
OCaml on Windows has caused me headache for a long time...

The one we're using in AppVeyor builds is discontinued: http://wodi.forge.ocamlcore.org/

The best packaged 4.x version available now seems to be https://github.com/OCamlPro/ocpwin-distrib
Its installer was buggy (https://github.com/OCamlPro/ocpwin-distrib/issues/8) and I'm waiting them to post a zip archive version (https://github.com/OCamlPro/ocpwin-distrib/issues/12).

**Comment by Simn** [comment]
> OCaml on Windows has caused me headache for a long time...

Just for the record I would like to second that. I have spent several afternoons trying to get it working and never really succeeded.

**Comment by nadako** [comment]
It gave me headaches when I was starting with haxe dev, but I'm using the "cygwin" method I described at http://haxe.org/documentation/introduction/building-haxe.html for a long time now without any problems, and it's OCaml is the recent one: http://protz.github.io/ocaml-installer/

**Comment by andyli** [comment]
The major problem I had with the cygwin version is that, the haxe compiler it produced didn't work well with FlashDevelop, in particular, I couldn't get auto-completion to work... I may try it again and I think it is good to debug that anyway.

Moreover, I think the haxe compiler produced by it depends on a cygwin dll that we will have to bundle.

**Comment by waneck** [comment]
Funny enough, it seems like the easiest way to compile Haxe for windows is
on Linux with a cross compiler. That's how the official binaries are
compiled, and it's a recent version of OCaml with mingw (which is much less
intrusive than cygwin)

2015-11-29 16:47 GMT-02:00 Andy Li <notifications@github.com>:

**Comment by andyli** [comment]
Back to the subject: If we ever define our supported ocaml versions, we should consider the [ocaml versions provided by ubuntu releases](http://packages.ubuntu.com/search?keywords=ocaml). If we do not support those versions, building haxe on those ubuntu releases would be a bit more troublesome.

 * ubuntu precise (12.04LTS, EOL date is April 2017) provides OCaml 3.12.1
 * ubuntu trusty (14.04LTS, EOL date is April 2019) provides OCaml 4.01.0

**Comment by ncannasse** [comment]
Let's keep 3.12 compatibility for now, I'm not sure if there's a way to disable these warnings, in case there is please provide a patch for Makefile.
