### ISSUE TITLE
Internal changes for Haxe 4

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4684]
This is a collection issue for internal changes we want to make for Haxe 4. Some of these might affect macro users. All these should be considered "under discussion".

### Add call type parameter mapping to the AST

We have to find a way of keeping the type parameter mapping in the AST. See https://groups.google.com/forum/#!topic/haxedev/M96qHOYCLsI for a small discussion

<strike>

### Change `Null<T>` to abstract

See #4316.</strike>

### Add proper `is` operator

See #2976. We actually already support this with `(expr is TypePath)` syntax, the question remains if `is` should be made a keyword.

<strike>

### Keep track of "quoted" status for structure declarations

See #2642. We currently do some really awkward String encoding.</strike>

### Keep track of how strings are quoted

We currently rely on some state in the lexer to determine if a field is quoted or not. I once wanted to see how much work it would be to encode this properly and the [commit](https://github.com/Simn/haxe/commit/3244eb0d8573732a844c5b2af73b798b840e14eb) was not a small one.

<strike>

### Add position information in more places

This [issue](https://github.com/Simn/haxeparser/issues/20) came up in my haxeparser port and I've come across it in core Haxe multiple times. There are several parts in the AST that do not dedicated position information.</strike> (implemented)

### Identify static closures in the AST

Static closures in the AST are currently `TField(_, FStatic)`, which is also the first argument of a static call `TCall(TField(_, FStatic),[])`. Since the typer knows it's typing a static closure it might as well set the field kind to `FStaticClosure`.

### Unify module information

We currently keep parts of it in `typer_module` which causes trouble for any operation that wants to type something into the module, such as `Context.defineModule`. It would be nice if we could retain this information.

### Get rid of TParenthesis in silly places

Generators can decide where they want parentheses, the AST shouldn't have them for `if/while` conditions and the `switch` subject.

<strike>

### Support unicode lexing properly

Currently our lexer has some problems with unicode. We should check if we can improve that.</strike>

**Comment by RealyUniqueName** [comment]
Can we drop `?arg:Type` syntax at some point? From what i see in our team it introduces a lot of confusion for newcomers. It's not clear for them what is the difference between `?arg:Int` and `arg:Int = 0` until I explain.

`?arg:Int` is actually `arg:Null<Int> = null`. But every single dev which comes to haxe thinks that `?arg:Int` is equal to `arg:Int = 0`.

**Comment by RealyUniqueName** [comment]
And this: [arrow functions VS map declaration syntax](https://github.com/HaxeFoundation/haxe-evolution/pull/8)

**Comment by Simn** [comment]
This issue is mostly about *internal* changes, i.e. stuff that doesn't really make it to the user (except for macro authors).

**Comment by RealyUniqueName** [comment]
Can i start an issue for _external_ changes? )

**Comment by Simn** [comment]
I've done most of the things I wanted to do here, and for the rest we already have open issues.
