### ISSUE TITLE
"Recursive implicit cast" error with abstract on compilation server

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4686]
I have an abstract here with a `@:from` function that is a macro. Don't know if this is supposed to work at all. It does compile fine, though. It also compiles with the compilation server on the first run. Only when I modify a file, where the absttract/macro is used, and recompile, I get `Type not found` and `Recursive implicit cast` errors. Is this an issue worth investigating or too exotic?

**Comment by Simn** [comment]
I would certainly like to know what causes that if you can come up with a small example. Don't lose any sleep over it though.

**Comment by mockey** [comment]
I'll see what I can do.
So generally a `@:from macro static function` is a valid option in an abstract?

**Comment by mockey** [comment]
Hm, interesting. These errors don't show with current development version apparently. Did you change something regarding the compilation server?

**Comment by jcward** [comment]
I can confirm -- I was just getting this error with Haxe 3.2.1 and when I just tried the 3.3.0-rc2 from haxe.org, it went away. The error never occurred on the first compile, only in compilation server mode.

**Comment by frabbit** [comment]
maybe related: https://github.com/HaxeFoundation/haxe/issues/5795

**Comment by Simn** [comment]
See #5795
