### ISSUE TITLE
Remove Error Reporting Settings from Bootclass?

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/haxe#4688]
I have a validation library written in Haxe that outputs to JS and PHP.  When we first hooked up the library to our API, it started generating a lot of unnecessary errors.  The problem was that the bootclass [had turned the error reporting up to 11](https://github.com/HaxeFoundation/haxe/blob/1ae448228d0fba1edc2c0712d71825fe0cb660a1/std/php/Boot.hx#L864):

	error_reporting(E_ALL & ~E_STRICT);
	set_error_handler('_hx_error_handler', E_ALL);
	set_exception_handler('_hx_exception_handler');

To work around the issue, I created a custom include that resets the error handling:

    restore_error_handler();
    restore_exception_handler();
    error_reporting(0);

Surprisingly, I was still able to throw and catch Haxe exceptions without any problems.  At least for my codebase, everything runs fine with the default error settings.

Is there a reason the error handling is cranked up to the maximum level?  Could it be moved to a `--debug` switch or at least disabled with one?

**Comment by RealyUniqueName** [comment]
I've faced the same problem. 
But i had to add postprocessing of generated Boot class after Haxe compilation to remove these lines.

**Comment by Simn** [comment]
I can't really comment on this, but I'm too scared to mess with these settings by default. I also don't know how we could make this configurable given that this is in a giant `__php__` block.

**Comment by RealyUniqueName** [comment]
Oh! Great! I've found it in `Boot.hx` i can edit it and make a PR.
What do you think about defining some -D flag like `dontTouchPhpErrorHandling`? :)

**Comment by Simn** [comment]
That doesn't change the fact that it's within a giant string where you can't use conditional compilation.

**Comment by RealyUniqueName** [comment]
I can break that string to logical parts into different methods

**Comment by indolering** [comment]
Unless someone can articulate a way in which Haxe itself relies on this setting, it really shouldn't be enabled by default.  Turning this off shouldn't break existing functional code, it should only cause some potential issues to fail silently.  Most of the issues raised by this higher error level are deprecated APIs and syntax.

I would lean towards a compilation flag for excluding it for a few versions and then a switch to a compilation flag for including it.

**Comment by RealyUniqueName** [comment]
Ok. Looks like it's not that simple.
After disabling error handling other test started to fail.

**Comment by indolering** [comment]
> After disabling error handling other tests started to fail.

Dammit.  Are they failing because errors aren't being reported or does it actually break functionality?

**Comment by RealyUniqueName** [comment]
I suppose it's because warnings and notices are not wrapped with Exception any more, thus not being catched by `try...catch`

**Comment by indolering** [comment]
> I suppose it's because warnings and notices are not wrapped with Exception any more

I don't understand, do you mean the test is failing because it was expecting an exception to be raised?  Sorry, I'm a newbie PHP/Haxe programmer.

What tests are failing?  Have you tried different combinations of error notifications?  I would think we could turn off E_STRICT and E_DEPRECATED safely (`error_reporting(E_ALL & ~E_STRICT & ~E_DEPRECATED`).

**Comment by RealyUniqueName** [comment]
I think, test is failing because haxe/php expects php warnings and errors to be converted to exceptions.
Since i disabled error handler, it does not happen anymore. Now php errors and warnings cannot be caught by try...catch. 
Even worse: php warnings does not break program flow, which leads to more warnings and errors.

**Comment by RealyUniqueName** [comment]
> do you mean the test is failing because it was expecting an exception to be raised? 
yes

> Have you tried different combinations of error notifications? I would think we could turn off E_STRICT and E_DEPRECATED safely (error_reporting(E_ALL & ~E_STRICT & ~E_DEPRECATED).
It does not make any difference. Warnings will still happen.

**Comment by indolering** [comment]
> It does not make any difference. Warnings will still happen.
Agreed, it's not a long-term solution; I don't think Haxe should rely on any specific error reporting setting or at least confine them to user initiated errors.  It makes the PHP target unsuitable for use in cross-platform libraries.

However, this would at least get rid of the worthless errors and could probably be slipped into a patch release.

**Comment by Simn** [comment]
Sorry guys, but I cannot take responsibility to making a change like this. In fact, I'm gonna play the "it has been fine for more than 7 years" card on this one and close it.

If someone wants to become the new Haxe/PHP maintainer then by all means speak up. Until then, however, I'll be very conservative about the changes I make to the PHP target.
