### ISSUE TITLE
Redefinition: can't import two classes if modules have same-named class

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#4691]
```haxe
// A.hx
class A {}
class C {}
```
```haxe
// B.hx
class B {}
class C {}
```
```haxe
import A.A;
import B.B;

class Main
{
}
```
Error: type name C is redefined in module A.
For me, it is a strange behavior: if I have duplicate class in two modules in the same package, then I don't have a way to import both modules...

**Comment by Simn** [comment]
That's intended. Both `C` classes have the same output path, so we don't want to have half your program use `A.C` and the other one `B.C`. The fact that they are "equal" is a special case that's not even worth detecting. Make your `C` class `private` to address this.
