### ISSUE TITLE
Dependencies in compiler cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4697]
One specific case is not detected in compiler cache invalidation, which is the addition of a new import module that would override another one.

In the dependency list we don't store if module/type was loaded without its full package so we already have the problem when loading types in such way:

```
A.hx
  |- b
      | - B.hx reference type "A"
```

We will not detect that adding b/A.hx requires recompiling B.hx because it does not reference A with its full package.

This will apply to imports.hx too

We have to be careful when fixing this, we don't want to slow down module cache check too much, or to have too big dependency tables.

One possibility would be when a module B has dependency to A, to check if there's no other A "in between" package(A) and package(B) and if there is one whih has been modified since last compilation, invalidate B: this might be a false positive invalidation but it's better than tracking which path A was loaded with in the first place.

**Comment by Simn** [comment]
Is that b/A.hx seen by the compiler at all, given that nothing really references it?

**Comment by ncannasse** [comment]
not it will not, that's why we need to look for it before reusing b/B.hx

**Comment by ncannasse** [comment]
TBH that's very rare case, didn't happen to me in years using compilation cache

**Comment by Simn** [comment]
Not only is it a rare case, it's also annoying to fix because you have to hit the file system. Can we just document this?

**Comment by ncannasse** [comment]
I'll assign myself and think a bit more about it, it shouldn't impact that much if we cache the results, I'll be able to mesure perf impact on large projects I have.

**Comment by Simn** [comment]
Ok you've had enough time to think about it.
