### ISSUE TITLE
Haxe (Un)Serializer cross-target tests

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4698]
As mentioned in https://github.com/HaxeFoundation/haxe/issues/4452#issuecomment-130222426, it would be really nice to have cross-target testing matrix of haxe serializer that checks that values serialized from one target is correctly deserialized on other targets. I suspect there are already problems with it at least with dates (see #4584).

@andyli do you think we can organize that?

PS SPOD may have same issues, but serialization system is more cruicial IMO.

**Comment by andyli** [comment]
Since serialization should be pure function, i.e. the same input should produce the same output, why not just have a list of pre-serialized values and check the targets against it?

**Comment by Simn** [comment]
Agreed with @andyli, that should cover everything.

**Comment by Simn** [comment]
I made a small demo how we could handle this. The idea is to

1. Add a named value here: https://github.com/HaxeFoundation/haxe/blob/serializer_tests/tests/unit/src/RunSerializerOutput.hx#L22
2. Add a corresponding test function here: https://github.com/HaxeFoundation/haxe/blob/serializer_tests/tests/unit/src/unit/TestSerializerCrossTarget.hx#L69

Then we can `haxe --run RunSerializerOutput` to generate the resource file, which we also keep in the repository.

Does that work for you?

**Comment by nadako** [comment]
Looks good!

**Comment by Simn** [comment]
*Of course* the PHP target is already failing with a syntax error. Goddammit @nadako!

**Comment by nadako** [comment]
Syntax error?

![WAT](http://d28mt5n9lkji5m.cloudfront.net/i/Xzfh10Tt-N.jpg)

**Comment by nadako** [comment]
Why was this `3.4`'d? Tests pass, according to https://travis-ci.org/HaxeFoundation/haxe/builds/94854870

**Comment by Simn** [comment]
I'm afraid of the results if someone adds more tests.

**Comment by Simn** [comment]
Remind me to look into this again...
