### ISSUE TITLE
js.jquery.JQuery: index() returns Float

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4700]
The return of `index()` is typed as Float:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery/JQuery.hx#L533
Is this intentional?

**Comment by andyli** [comment]
Good catch! The extern is generated from the jquery api doc, which marked the return type of `index()` as `Number`. I've made a PR (https://github.com/jquery/api.jquery.com/pull/845) to change that and will regenerate the extern after it is merged.
