### ISSUE TITLE
js.jquery.JQuery: overloads

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4701]
I just converted an old js-app of mine to use the new JQuery-extern (because of the many deprecated warnings I got).
The old extern had a couple of convenient `@:overload`-functions, e.g.:
`each()` can be also used as `Int->Void` or `Void->Void`, or `click` can be `Void->Void` also. Are you planning to add these to the new extern as well? I think it is generated so would probably make some manual additions necessary (maybe an additional file?). On the other hand, it's not such a big deal to write `function(_, _)` instead of `function()`, just asking ....

**Comment by nadako** [comment]
see #4534

**Comment by mockey** [comment]
Haven't seen that, sorry.
