### ISSUE TITLE
Reevaluation of limit in a for(i in 0...t) loop is undefined

### ISSUE THREAD

**Issue by ratkingsminion** [HaxeFoundation/haxe#4702]
http://try.haxe.org/#64bee

    class Test {
        static function main() {
            var t = 5;
            for (i in 0...t) {
                trace(i);
                t--;
            }
            trace("---");
            t = 6;
            for (i in 0...t-1) {
                trace(i);
                t--;
            }
        }
    }

The first loop counts till 2, the second one till 4. It should be the same. Tested with JS and SWF target.

**Comment by Simn** [comment]
That's interesting. The first loop does not create a temp variable because the compiler thinks it doesn't need one. We seem to have several of these invalid assumptions about `TLocal` not requiring a temp var.
