### ISSUE TITLE
Allow abstract to be iterable over custom type

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4705]
I am improving `openfl.utils.Object`, adding array access, and (I hoped) iterable support. However, the latter is simply not possible using an abstract with String array access.

I hoped I could do this:

``` haxe
public inline function iterator ():Iterator<String> {

    var fields = Reflect.fields (this);
    if (fields == null) fields = [];
    return cast fields.iterator ();

}
```

Calling `for (field in object)` results in code that calls `object.hasNext` and `object.next` -- it assumes the base object is the iterator. Could we not allow abstracts to return their own iterators?

I'm aware of `get_length` and array access for abstract iteration, but this case needs String-based keys, not Int-based keys.

**Comment by Simn** [comment]
I'm not sure I understand:

```haxe
abstract A<T:{}>(T) from T {
	public inline function new(value:T) {
		this = value;
	}

	public inline function iterator():Iterator<String> {
		var fields = Reflect.fields (this);
		if (fields == null) fields = [];
		return fields.iterator ();
	}
}

class Main {
	static function main() {
		var a = new A({ foo: 12, bar: 13 });
		for (i in a) {
			trace(i);
		}
	}
}
```

Generated JS:

```js
Main.main = function() {
	var a = { foo : 12, bar : 13};
	var tmp;
	var fields = Reflect.fields(a);
	if(fields == null) fields = [];
	tmp = HxOverrides.iter(fields);
	while( tmp.hasNext() ) {
		var i = tmp.next();
		console.log(i);
	}
};
```

What exactly is the problem here?

**Comment by jgranick** [comment]
Here's what I have currently:

```haxe
@:forward() abstract Object(Dynamic) from Dynamic to Dynamic {
	
	
	public inline function new () {
		
		this = { };
		
	}
	
	
	public inline function hasOwnProperty (name:String):Bool {
		
		return (this != null && Reflect.hasField (this, name));
		
	}
	
	
	public inline function isPrototypeOf (theClass:Class<Dynamic>):Bool {
		
		var c = Type.getClass (this);
		
		while (c != null) {
			
			if (c == theClass) return true;
			c = Type.getSuperClass (c);
			
		}
		
		return false;
		
	}
	
	
	@:noCompletion @:dox(hide) public function iterator ():Iterator<String> {
		
		var fields = Reflect.fields (this);
		if (fields == null) fields = [];
		return cast fields.iterator ();
		
	}
	
	
	public inline function propertyIsEnumerable (name:String):Bool {
		
		return (this != null && Reflect.hasField (this, name) && Std.is (Reflect.field (this, name), Iterable));
		
	}
	
	
	public inline function toLocaleString ():String {
		
		return Std.string (this);
		
	}
	
	
	public inline function toString ():String {
		
		return Std.string (this);
		
	}
	
	
	public inline function valueOf ():Object {
		
		return this;
		
	}
	
	
	@:arrayAccess @:noCompletion @:dox(hide) public inline function __get (key:String):Dynamic {
		
		return Reflect.field (this, key);
		
	}
	
	
	@:arrayAccess @:noCompletion @:dox(hide) public inline function __set (key:String, value:Dynamic):Dynamic {
		
		Reflect.setField (this, key, value);
		return value;
		
	}
	
	
}


@:keep @:native('haxe.lang.Iterator') private interface Iterator<T> {
	
	public function hasNext ():Bool;
	public function next ():T;
	
}


@:keep @:native('haxe.lang.Iterable') private interface Iterable<T> {
	
	public function iterator ():Iterator<T>;
	
}
```

and test:

```haxe
package;


import openfl.display.Sprite;
import openfl.utils.Object;


class Main extends Sprite {
	
	
	public function new () {
		
		super ();
		
		var a:Object = { foo: 12, bar: "13" };
		
		for (field in a) {
			
			trace (field);
			trace (a[field]);
			
		}
		
		
	}
	
	
}
```

Here is the relevant generated JavaScript:

```js
var Main = function() {
	openfl_display_Sprite.call(this);
	var a = { foo : 12, bar : "13"};
	while( a.hasNext() ) {
		var field = a.next();
		haxe_Log.trace(field,{ fileName : "Main.hx", lineNumber : 19, className : "Main", methodName : "new"});
		haxe_Log.trace(Reflect.field(a,field),{ fileName : "Main.hx", lineNumber : 20, className : "Main", methodName : "new"});
	}
};
```

Perhaps it's handled differently if it's an abstract over `Dynamic`?

**Comment by jgranick** [comment]
I took another look.

I first made the private `Iterator` and `Iterable` types use different names, so it would not obscure the standard Haxe `Iterator` type. I'm not sure this was necessary (but these types are needed because `Std.is (obj, Iterable)` is not possible ordinarily)

The culprit was `to Dynamic`, this takes precedence over `iterator ()` and calls `hasNext ()` and `next ()` on the actual object. Perhaps there's a way to check for the presence of an `iterator ()` before casting to Dynamic in this case?

Thanks again

**Comment by Simn** [comment]
That seems strange, I don't see why it would cast at all in this case. But then again `Dynamic` is a mystical thing. I'll check it out.

**Comment by jgranick** [comment]
Oh, I just hit another problem.

My current code compiles to JavaScript or Neko just fine (which is great), but I get the following compile error on Flash:

```
You can't iterate on a Dynamic value, please specify Iterator or Iterable
```

I'm assuming this is a wrongful error, or perhaps the `iterator ()` method is not being respected in the Flash output

**Comment by jcward** [comment]
@jgranick I think you and I are considering the same thing -- creating an abstract type that behaves as much like an ECMAScript Object as possible.

I just found today what's causing your problem -- it's the `to Dynamic`. Here's a simple of an abstract over Dynamic (without to Dynamic) that iterates great: http://try.haxe.org/#98FbF

The main problem here is that you must cast sub-objects back to the abstract type to be able to iterate over them. I believe this will be fixed when @simn fixes #5097 -- see [my comment](https://github.com/HaxeFoundation/haxe/issues/5097#issuecomment-228463714) from today. Once working, `@:resolve` should allow us to force sub-objects to the same (abstract) type.

Now, an entirely different but related question is, while I understand why Dynamic cannot be iterated over (though arguably Reflect.fields() is the obvious answer), I wonder why I cannot even specify this behavior with a static extension: http://try.haxe.org/#5b965 Shall I file this as a separate issue, or is there something I'm missing?

**Comment by jcward** [comment]
BTW, since Flash is being deprecated, I think having a Haxe Object that works just like Flash/JS objects is increasingly important.

**Comment by sbimikesmullin** [comment]
any update?
