### ISSUE TITLE
[JS] Could merge __js__ calls in haxe.ds.IntMap.keys()?

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4707]
Correct me if I'm wrong, but [this](https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/haxe/ds/IntMap.hx#L53),
```haxe
__js__("for( var key in this.h ) {");
	if( h.hasOwnProperty(key) )
		a.push(key|0);
__js__("}");
```
currently generates (valid, but suspicious)
```js
for( var key in this.h ) {;
if (this.h.hasOwnProperty(key)) a.push(key | 0);
};
```
and could be changed to use the more recently added `__js__` arguments,
```haxe
__js__("for( var key in {0} ) {1}", h, if( h.hasOwnProperty(key) ) a.push(key|0));
```
and generate the following
```js
for( var key in this.h ) if (this.h.hasOwnProperty(key)) a.push(key | 0);
```

**Comment by nadako** [comment]
I don't see much difference, but that wouldn't hurt as well. PR?:)
