### ISSUE TITLE
Completion failing in multicompilation

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4710]
Some problems when doing completion with multiple targets (with --next) :

If we try to complete a file that is only included in one target, and for instance references a target specific type, that will only work if it's the first target compiled. If it's not, it will error while compiling for the first target.

Our example:

```
(compile to js)
--next
(compile to swf)
-lib castle
```

Trying to complete a file that requires castle gives a `Type not found cdb.jq.Dom` error (since completion file is being compiled with first target parameters).

We should try to get completion with all targets before displaying an error

**Comment by Simn** [comment]
On a not entirely unrelated note, it would be nice to have a way to label `--next` sections and address them via command line. Quick example:

```
(compile to js)
--next swf
(compile to swf)
-lib castle
```

```
haxe build.hxml@swf
```

This way IDEs could pass in the current compilation target if available. For instance, FlashDevelop has a combo box "Select Target Build" which could utilize this.

I realize that doesn't solve this issue in its entirety, but it would be nice nonetheless.

**Comment by ncannasse** [comment]
I think I have an issue for it somewhere, and yes I agree.
I propose we have implicit names for the targets (flash, cpp, js, etc.)
explicit names should be set another way, since --next does not take any argument

**Comment by Simn** [comment]
Implicit targets would be nice. We have to define what happens when there are two `--next` blocks to the same target though.

Also the compiler doesn't know the current target until it processes `-js` etc.

**Comment by mcheshkov** [comment]
Even if file is referenced in all targets, it fails with syntax error in one of them, I guess in second.

Test.hx
```haxe
package;

class Test {
	public static function main(){
		var s = "";
		s.
	}
}

```

build.hxml
```
-cp .
-main Test

--next 

-cp .
-main Test
```

`Test.hx@73` is `s.|`
`haxe build.hxml --no-output --display Test.hx@73 ` works.
`haxe build.hxml --no-output --display Test.hx@73 -D display-details` fails with `Unexpected }`.
`haxe --connect 6000 build.hxml --no-output --display Test.hx@73 -D display-details` works.
`haxe build.hxml --connect 6000 --no-output --display Test.hx@73 -D display-details` fails same way.

Without `--next` all 4 commands work properly.

**Comment by Simn** [comment]
I vote to get rid of `--next` and `--each`. Will open a separate issue for that.
