### ISSUE TITLE
Inconsistent behavior of UInt in specific cases

### ISSUE THREAD

**Issue by grosmar** [HaxeFoundation/haxe#4712]
**Summary:**
Inconsistent behavior of UInt in specific cases. In some cases the compiler doesn't add the hack to imitate the overflow. We didn't test all the situations, so only mention one way to reproduce

**Version:**
3.2.0

**Reproduction:**
```haxe
class Test {
    static function main() {
        var n:UInt = -4;
        if ( n > 0 )
        	trace("positive", n);
        else
            trace("negative", n);
    }
}
```

It runs into the "positive" branch, as expected, but when you check for the number, it's different in js and flash platform:
Flash: 4294967292 (as expected)
JS: -4 (so overflow behavior is missing)

**Expected behavior:**
Everywhere should give the result: 4294967292

**Description:**
It looks like only happens when you put it as the second parameter of the trace. With the following code it works well:

```haxe
class Test {
static function main() {
        var n:UInt = -4;
        if ( n > 0 )
        	trace(n);
        else
            trace(n);
    }
}
```
We don't know which other situations it works like this, but maybe it would worth to look into other situations too, if it works well everywhere.

**Comment by ncannasse** [comment]
The issue here is different. Trace takes Dynamic parameters, so UInt is not converted to a String, so it's underlying representation is printed. If you do n.toString() it should work.

**Comment by grosmar** [comment]
I think most of the people don't need to know about you have to call toString(), it think it should be automatically done by the compiler or the trace function.

**Comment by Simn** [comment]
I think I want to fix it. It really shouldn't matter if something is the first or second argument to `trace`.

**Comment by grosmar** [comment]
Thanks guys! You are crazy fast! :)
