### ISSUE TITLE
Macro: Add callback after typing is done that can add types

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#4714]
One problem we're facing at the moment which is related to #4527: We need a callback like `Context.onGenerate` but that still allows types to be added (by `Context.defineType` or by normal typing`).
Right now we've gone at great lengths in the build system to overcome that - but it has its own drawbacks (e.g. a rigid project structure).

I've talked a little with @Simn about it and it seems like providing a `Context.onGenerate`-like callback with the currently added types would be a feasible solution for this.

This has the `haxe-foundation-partner` tag on it since it's related to proletariat

**Comment by ncannasse** [comment]
I think we need something different than onGenerate, because it's clearly done before generation, so after all typing was done.

We might call it onTypingDone (or propose another thing), and it would work that way:

```haxe
while( true ) {
  while( thingsToType ) typeThem();
  onTypingDone();
  if( !thinksToType ) break;
}
onGenerate();
generate();
```

**Comment by ncannasse** [comment]
Please note that in that case it might be called several times per compilation

**Comment by Simn** [comment]
My thinking was to have a callback which is called just before `Typer.finalize`. I was considering a loop like you suggested as well, but I'm not sure how practical that would actually be.

The other question is what we can pass to the callback. We don't have an ordered list of types yet (`com.types` is constructed by `Typer.generate`), but we could pass in the `ctx.g.modules Hashtbl`.

**Comment by waneck** [comment]
The `ctx.g.modules` Hashtbl would be great!

**Comment by ncannasse** [comment]
We definitely need to loop, in case the macro does some defineType etc.

**Comment by fzzr-** [comment]
This is a great thing.
1. But thus we will be able to generate a macro from a macro?
2. And we need a serious control loop for determining the infinity cycles and beak loop. IMO it possible crazy if seek to the safety implementation.
3. At the moment the Haxe-compiler is the fastest compiler I know (excluding coffee and css-processors). How much the loop of typing will affect the speed of compilation?

**Comment by Simn** [comment]
I know the macro might define a new type, but why would you want i to be called with that type again? You can already define it the way you want and do whatever with it. Turning this into a loop seems really impractical because you have to manually detect cycles.

**Comment by Simn** [comment]
@waneck: Do you remember what we agreed on regarding the loop-question?

**Comment by Simn** [comment]
There has been no follow-up here and now we're past our feature freeze. I'll set this to 3.4 for the time being.

**Comment by waneck** [comment]
@Simn  oops sorry for taking this time to answer!
We agreed that we should re-register the callback again, and it would only be called for the types that were added since the last callback, IIRC

**Comment by Simn** [comment]
Since it's a HF partner request I'll check it out for 3.3 after all.

**Comment by waneck** [comment]
That's great! Thank you, Simon!

**Comment by Simn** [comment]
I've made a first implementation, see the linked commit. Note that the callback receives `ModuleType` instead of `Type` which makes more sense.

I didn't go for the re-registering of the callback because I'm not convinced (anymore) that it's a better API. Since we have to figure out the "new types" anyway (which is a bit awkward to do, I don't think there's any way around filtering through all types) we might as well call the callback as long as we have new types.

Let me know if this works for you. It's not very well tested and I'm not sure how to write proper tests for it, but we can sort out whatever problems we might come across after the RC.

**Comment by Simn** [comment]
I have added this to development, we can address whatever problems might arise for 3.3.0 final.

**Comment by waneck** [comment]
It seems that `Context.onAfterTyping` is called as well for the macro context

**Comment by Simn** [comment]
I'll need some more feedback for this either way so I think it's fine to look into it after the RC.

**Comment by Simn** [comment]
@waneck: What's left to be done here?

**Comment by Simn** [comment]
No feedback here so I assume this is working as intended now.

**Comment by ncannasse** [comment]
What about compilation server ? :-)

**Comment by nadako** [comment]
Man, I should create the `awesome-simn` repository where I collect links to golden comments like that one :)

**Comment by ncannasse** [comment]
You forgot the most important world problem, which is waiting for next GoT season
