### ISSUE TITLE
Goto in the typed AST

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4715]
Don't panic, I don't want to add goto to Haxe.

However, there are situations and targets where having a goto-functionality in the typed AST would be very beneficial. My favorite example is the do-continue-problem:

``` haxe
class Main {
    static function main() {
        do {
            if (Math.random() > 0.5) {
                continue;
            }
            trace("function body");
        } while({
            trace("function condition");
            Math.random() < 0.5;
        });
    }
}
```

Generating this to targets which cannot put the conditional expression into the `while` currently causes code duplication:

``` js
Main.main = function() {
    while(true) {
        if(Math.random() > 0.5) {
            var tmp1;
            console.log("function condition");
            tmp1 = Math.random() < 0.5;
            if(!tmp1) break; else continue;
        }
        console.log("function body");
        var tmp;
        console.log("function condition");
        tmp = Math.random() < 0.5;
        if(!tmp) break;
    }
};
```

It would be much nicer to have this instead:

``` js
Main.main = function() {
    while(true) {
        if(Math.random() > 0.5) {
            goto loop_condition;
        }
        console.log("function body");
        loop_condition:
        var tmp;
        console.log("function condition");
        tmp = Math.random() < 0.5;
        if(!tmp) break;
    }
};
```

**Comment by ncannasse** [comment]
Are we sure all of our current (and future) targets have proper goto support ?

**Comment by Simn** [comment]
No, it would only be used on targets that support it. It's mostly about the C++ output.

**Comment by nadako** [comment]
See also #3883

**Comment by ncannasse** [comment]
I'm fine, the only problem I can have left with it is that we need to allocate some kind of global identifier, which will make changes into the whole file when simply changing some part of the code. Unless we use the Ast position for generating the label, but macros often use the same position for big blocks of code.

**Comment by Simn** [comment]
We can enumerate it per-field with the field name as prefix, or something to that extent.

**Comment by fzzr-** [comment]
I think it is possible but not needed in macro. Maybe it must be `-D analyzer`-related feature.

**Comment by YellowAfterlife** [comment]
On the do-continue problem, could the code also be transformed to
```js
do {
	var _break = true;
	do {
		// loop body:
		if (Math.random() > 0.5) continue;
		console.log("function body");
	} while (_break = false);
	if (_break) break;
	// condition body:
	console.log("function condition");
} while (/* condition final */Math.random() < 0.5);
```
? While this is a twisted little structure with an inline assignment (other option is increment\decrement), it does get rid of the duplicate code, and would be a suitable method of transforming larger inline blocks in conditions.

**Comment by Simn** [comment]
Probably not worth it...
