### ISSUE TITLE
Determining which functions might throw exceptions

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4716]
For static analysis it is necessary to know which expressions might throw an exception in order to determine the correct control flow. At the moment we conservatively assume that any function call might throw. Unfortunately this can easily lead to a really convoluted control flow, e.g. something like this: http://simn.de/haxe/haxe_cfg_3.png

I would like to make this smarter by automatically marking functions that definitely don't throw. Determining this conservatively is a bit iffy, so I would like some input from @ncannasse and @waneck as to whether or not this is viable at all.

My naive thinking is that a function might throw if it:
* has `throw`
* has a safe cast
* calls a function or constructor that might throw
* calls an unknown function, e.g. a closure

As far as I'm aware we do not define anything exception-related for the following:
* Invalid field or array access (e.g. on `null`)
* Invalid binary or unary operations
* Array or object declarations (by themselves, their arguments might of course still throw)

Are these safe assumptions?

**Comment by ncannasse** [comment]
> My naive thinking is that a function might throw if it:
>
>   * has |throw|
>   * has a safe cast
>   * calls a function or constructor that might throw
>   * calls an unknown function, e.g. a closure
>
> As far as I'm aware we do not define anything exception-related for the
> following:
>
>   * Invalid field or array access (e.g. on |null|)
>   * Invalid binary or unary operations
>   * Array or object declarations (by themselves, their arguments might
>     of course still throw)

We do not define anything, we means an optimized version might not 
perform runtime NULL checks and still be considered Haxe-compatible. 
However in practice most platforms will throw exceptions on null 
field/array accesses, and we surely don't want the analyzer to assume 
they don't and result in code that behaves differently in case they do.

Best,
Nicolas

**Comment by Simn** [comment]
That's sad, it means we can't optimize any function that has a `try` because control flow could jump to a `catch` from virtually everywhere within it.

**Comment by Simn** [comment]
We actually rely on invalid field access throwing in the serializer, so I guess I'll just have to assume that almost anything can throw.
