### ISSUE TITLE
Support the ISO 8601 date format

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4717]
https://en.wikipedia.org/wiki/ISO_8601

Mainly the two datetime format, e.g.:
- 2015-12-05T13:11:59+00:00
- 2015-12-05T13:11:59Z

For example, the ISO format is natively supported by js, so we can simply do:

``` haxe
var v = "2015-12-05T13:11:59+00:00";
var date = untyped __js__('new Date({0})', v);
```

ISO is more friendly in the sense that it allow specifying timezone (optionally).

**Comment by ncannasse** [comment]
I'm not a Date expert but It's the first time I hear about it. Is it something widely used?

**Comment by andyli** [comment]
Yes, it is in fact super popular. And there is this somewhat famous comic: https://xkcd.com/1179/

**Comment by kevinresol** [comment]
It is recommended by W3C: http://www.w3.org/TR/NOTE-datetime

**Comment by fponticelli** [comment]
Parsing that format is important but unfortunately you will lose the time
zone info in the Date object. thx.DateTime preserve such info.

**Comment by andyli** [comment]
Yes, timezone will be lost, but at least it will be the same time (same timestamp).

**Comment by fponticelli** [comment]
Correct.

**Comment by Simn** [comment]
I'm fine with this, but somebody is gonna have to send a pull request...

**Comment by kevinresol** [comment]
Shall we introduce a `help-wanted` label and at least keep these kind of issues opened?

**Comment by Simn** [comment]
I really prefer to not have these long-term feature request issues on my radar...

**Comment by Gama11** [comment]
The label already exists, added it in case that helps: https://github.com/HaxeFoundation/haxe/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

Whether this should be reopened, not my call.

**Comment by kevinresol** [comment]
> I really prefer to not have these long-term feature request issues on my radar...

That's exactly the function of milestones and labels

**Comment by Simn** [comment]
Yeah but I'd still find it annoying to have this underbelly of forever-open issues. Plus I don't see the benefit because nobody randomly checks for open issues with help-wanted labels. Even during events like Hacktoberfest we don't get anything.

**Comment by Gama11** [comment]
There's a lot of different approaches to issue management. For instance for the GitHub desktop client I've seen that they seem to simply close all feature requests that aren't on the immediate roadmap, but label them and come back to them later if they're good.

Seems like that could work with `help-wanted` issues too, without having them in the list of open issues.

**Comment by kevinresol** [comment]
> Plus I don't see the benefit because nobody randomly checks for open issues with help-wanted labels. Even during events like Hacktoberfest we don't get anything.

That conclusion is derived from a sample size of 5 (or 4, before this very issue is tagged), seriously?

> There's a lot of different approaches to issue management.

Yeah, I don't mind anything as long as the information is retained.

**Comment by EricBishton** [comment]
> Yeah but I'd still find it annoying to have this underbelly of forever-open issues. 

Just because you hide it, that doesn't make it go away.  You've got the same open (but marked closed) issues.  They just become (alot) harder to find.

> Plus I don't see the benefit because nobody randomly checks for open issues with help-wanted labels.

Nobody ever checks for _closed_ issues that they can help with, either.

Closing issues just so you don't have to look at them is the same as saying "Yeah, we don't care.  We don't want this fixed."  It would be quite a bit better to mark them as "help-wanted" or "waiting for community contributions" than to close them.  Then, we could add a link on the web site to a list of issues that the community could help with.  (Or, put a small banner with a link to a randomly selected help-wanted issue right under the menu bar. "Want to help?  Perhaps you can fix <issue link>?")

Keeping the closed count to zero is simply a feel-good tactic.  (Or, maybe it makes folks think that the development team is more responsive than it is...)  There are many superior ways of limiting the number and type of issues that you actually see on _your_ radar.

**Comment by Simn** [comment]
We'll just have to agree to disagree on this one. You are free to post requests like this on the forum or somewhere without them being an open issue in the haxe repository.

> Keeping the closed count to zero is simply a feel-good tactic.

And feeling good is very important in an open source world with many volunteers. It is much better when the amount of problems seems surmountable, and I'm perfectly happy to trick myself and others into thinking that they are.

**Comment by haxiomic** [comment]
I agree with Simn on feel good being an important (and maybe under appreciated) factor in open source.

If we have these issues closed I think we should mention it somewhere in the readme, as I read this issue as “help-wanted but already completed”.

Maybe adding something with the gist: 
 
### Contributing to haxe
New volenteers looking to contribute should start with the [`help-wanted`](https://github.com/HaxeFoundation/haxe/issues?utf8=✓&q=+is%3Aissue+label%3A%22help+wanted%22+) tag.
Both open and closed issues are available to work on
