### ISSUE TITLE
[C#] Add implicit conversion operators to cs.internal.Nullable<T>

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4719]
Currently, working with Haxe-generated C# code can be a bit inconvenient, particularly with optional function arguments (which are currently handled via `cs.internal.Nullable<T>`).
It would make sense to define implicit conversion operators for Nullable, so that primitive\null values assigned to it from C# code would be converted into the structure automatically.
Wrote a [blog post](http://yal.cc/csharp-implicit-conversion-from-null-to-struct/) on the matter.
It would seem that there would be no side effects to this, since Haxe code already works with `.value`\`.hasValue` directly and structs are non-nullable.
Can assemble a pull request if needed.

**Comment by waneck** [comment]
A PR would be great :)
