### ISSUE TITLE
@:deprecated help message says it has no effect

### ISSUE THREAD

**Issue by kaikoga** [HaxeFoundation/haxe#4720]
`haxe --help-metas` says `@:deprecated` has no effect on types compiled by Haxe but does have some effect and is even used in std API. The help message is misleading.

I did find some confusing behaviors in Haxe 3.2.1 release ( reproduced in nightly version 15c79eb ) though:
- Deprecation warnings won't show if types written as type annotations are deprecated.
- Deprecating `new` ed types work with classes and enums but not with abstracts.
- Deprecating getters and setters looks bit tricky.

However, for other things it appears to be working. I will attach my experiment code for reference, in case I've overlooked something.
http://try.haxe.org/#33166

After some discussion I think we can actually state in `haxe --help-metas` that `@:deprecated` is supported in Haxe types. Some fixing issues, limitations, documentations in HaxeManual, or letting it feature may be desired.

**Comment by Simn** [comment]
Ah yes, this was originally a Java-only metadata which I hijacked later and didn't update the documentation accordingly. I'll also check out the failing cases you mention and add your very nice code snippet as a test case.
