### ISSUE TITLE
[C#] @:native has inconsistent output path effects on files with multiple classes

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4722]
``` haxe
package some;
@:native("other.A") class A { }
```

will generate `/other/A.cs`.
However, adding another class,

``` haxe
package some;
@:native("other.A") class A { }
@:native("other.B") class B { }
```

causes the target to generate `/some/A.cs`, hough with the correct namespace ~

``` cs
// ...
namespace other {
    public class A { /* ... */ }
    public class B { /* ... */ }
}
```

The code will remain functional (since C# does not rely on source file paths) but it's a little strange to find the output file in different locations depending on amount of things in it.

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
