### ISSUE TITLE
[PHP] wrong code generated with empty constructor

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4723]
Check this:

```
class Test {
  static function main() {
    var t = new Test1();
    t.test();
  }
}

class Test1 {
  public function new() {}
  public function test() trace("test");
}
```

With an empty constructor the generator adds `if(!php_Boot::$skip_constructor)`, which actually belongs to the constuctor I think, to the body of the `test` function. While this still sort of works, you get an error with `dynamic function test` because the dynamic method declarations in the constructor are left out, too.

This code:

```
class Test1 {
  public function new() {}
  public dynamic function test() trace("test");
  function test2 trace("test2");
}
```

generates:

```
public function test2() {
  if(!isset($this->test)) $this->test = array(new _hx_lambda(array(&$this), "Test1_0"), 'execute');
  if(!php_Boot::$skip_constructor) {
...
```

for function `test2`. So the code that belongs  in the constructor is somehow shifted to the first real function, when the constructor is empty. The error must be somewhere here:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L1304
but I cannot figure out what's going on there OCaml-wise.

**Comment by mockey** [comment]
This is still not quite right. The code is not shifted anymore, but the code for the dynamic function is missing in the constructor when the constructor is empty, i.e.:
```
class Test {
  public function new() {}
  public dynamic function test() trace("test");
}
```
generates:
```
class Test {
  public function __construct() {}
  public function test() { ... }
  public $test = null;
}
```
`if(!isset($this->test)) $this->test = array(new _hx_lambda(array(&$this), "Test1_0"), 'execute');`
is missing in the constructor.

**Comment by mockey** [comment]
....because `ctx.constructor_block` is false here:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L1302
But the code for the dynamic function is here:
https://github.com/HaxeFoundation/haxe/blob/development/genphp.ml#L1311

**Comment by Simn** [comment]
I'm confused, what does `constructor_block` have to do with dynamic functions?

**Comment by Simn** [comment]
Oh I see, it generates the init there... argh.

**Comment by RealyUniqueName** [comment]
This issue is not reproducible with the latest development version of Haxe.

**Comment by Simn** [comment]
Hmm yes, this was supposed to be closed by https://github.com/HaxeFoundation/haxe/commit/f95d3402ba7e31b93d13b9880b3404c4aa401a29 but for some reason didn't.

**Comment by mockey** [comment]
This still seems to be broken for the old generator, also see: #4924
```haxe
class Test {
  function new() {}

  dynamic function test() {
    trace("test");
  }

  static function main() {
    new Test().test();
  }
}
```
When the constructor is empty the init code is missing, e.g.:
`if(!isset($this->test)) $this->test = ...`
It only gets generated when the constructor is not empty.
Also -debug avoids the error, maybe that's why it's not caught in the unit test?

**Comment by RealyUniqueName** [comment]
Yes, `debug` was preventing to reproduce this issue. Now it's really fixed.

**Comment by mockey** [comment]
Confirmed.
Tiny flaw: there is a redundant `;` now after the init line, it's like:
```php
if(!isset($this->test)) $this->test = array(new _hx_lambda(array(&$this), "Test_0"), 'execute');
;
```

**Comment by RealyUniqueName** [comment]
Let's leave as-is for now :)
