### ISSUE TITLE
Reflect.field inconsistency on JS target

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/haxe#4726]
This one keeps the scope:
var f = o.method;

And this one loses the scope:
var f = Reflect.field( o, "method" );

I understand that you can use Reflect.callMethod later to call the method with the scope restored, but in many cases, you don't want to call it immediately, and you can't store or pass the scope:
dispatcher.addEventListener( type, Reflect.field( o, "method" ) );

**Comment by FrancisBourre** [comment]
For now, the hack is to use lambda:
dispatcher.addEventListener( type, function( e : IEvent ) : Void { Reflect.callMethod( listener, callback, [e]);} );

**Comment by ncannasse** [comment]
Reflect.field is platform dependent, so yes it is not used to create closures but for reflection purposes. Using Reflect.callMethod is the good solution in that case.
