### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4728]
It seems that if you have a compilation server running while installing an update of Haxe through our official installer, haxe.exe cannot be overwritten on Windows but the installation still is successful. This leads to having the "std" not being in sync with the haxe.exe, which causes many troubles for the end users.

I think @waneck takes care of the installer, can you look into it?

**Comment by ncannasse** [comment]
Sorry, there is actually already an error, the issue comes from somewhere else.

**Comment by ncannasse** [comment]
Ok got the lead to the issue : in 3.2.1 we removed std/neko/_std/Xml.hx, but some people update the ZIP by simply overwriting the files. It then keeps the old Xml.xml which will error with the following

`C:\HaxeToolkit\haxe\std/neko/_std/Xml.hx:366: characters 7-19 : Constant expression expected`

**Comment by Simn** [comment]
Surely that's a user-problem?

**Comment by ncannasse** [comment]
It seems to happen on Linux too 
http://community.openfl.org/t/haxe-3-2-openfl-3-1-0-neko-2-0-0-constant-expression-expected/1686
I confirm that Windows installer is correctly removing previous files when updating.

We should confirm for other installers and our "make install" as well.

**Comment by jobs-git** [comment]
Or, we could have an installation process where in 

1. haxe checks for an old version then notifies if we want remove it (Except the `lib` folder) 

and/or 

2. install along side the old one at the users discretion with a warning that this might cause compatibility issues (Then possibly fix Extensively Stopping  compatibility issues of different haxe versions)

**Comment by Simn** [comment]
I don't see any issue here, we can't prevent users from messing up their installation like this. I'm not aware of any installer issues and `make install` seems to have all the required `rm -rf`.

**Comment by Simn** [comment]
I tested this on Ubuntu yesterday and confirm that `make install` properly cleans everything up.
