### ISSUE TITLE
Haxe --remap

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#4732]
_I thought_ `--remap a:c.d` would work, but unfortunately it doesn't, so is `--remap` only guaranteed to switch single packages, `--remap a:c`?. 

I'm using Haxe `@ 8a159b2` with the following repo https://github.com/skial/haxe-remap. Some comments can be found in [build.hxml](https://github.com/skial/haxe-remap/blob/master/build.hxml).

**Comment by Simn** [comment]
If that's how it is at the moment then I doubt anyone would want to meddle with it anytime soon. I'm not opposed to changing this, but that would only happen in the form of a pull request.
