### ISSUE TITLE
Haxelib error

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#4735]
Hi, I have some troubles with haxelib: after installing it works fine, but after several reboots I see the error "Uncaught exception - load.c(181) : Module not found : list".

Mint 17.2
haxe 2:3.2.0-16 (this error I see with haxe 3.2.1 too)
neko 2.0.0-4~ubuntu14.04.1~ppa1
neko-dev 2.0.0-4~ubuntu14.04.1~ppa1
libneko0 2.0.0-4~ubuntu14.04.1~ppa1

$ haxe
Haxe Compiler 3.2.0 - (C)2005-2015 Haxe Foundation
$ haxelib
NekoVM 2.0.0 (c)2005-2013 Haxe Foundation
$ haxelib list
Uncaught exception - load.c(181) : Module not found : list
$ cat ~/.haxelib
/usr/share/haxelib
$ openfl create project testProj
Uncaught exception - load.c(181) : Module not found : run
$ ls /usr/share/haxelib
actuateformat  HaxeUmlGen  hxcpp  ihx   lime-samples  openfl        openfl-native        openfl-samples            snow
flow     haxeui  hscript     hxcs   lime  lime-tools    openfl-html5  openfl-nativedialog
$ ls /usr/lib | grep neko
libneko.so
libneko.so.0
libneko.so.0.1
neko

helps only "# apt-get install haxe --reinstall"
but to reinstall every time - this is so badly 8(

may be somebody known solution for this situation? thanks

**Comment by ncannasse** [comment]
Your haxelib binary have been strip'ed , cc @andyli

**Comment by r3d9u11** [comment]
thanks

**Comment by andyli** [comment]
@r3d9u11
Looking at the haxe package version number, I think you're using eyecreate's PPA instead of haxe foundation's. Please remove all the haxe/neko packages, [remove eyecreate's PPA](http://askubuntu.com/questions/307/how-can-ppas-be-removed), then install again using [haxe foundation's PPA](https://launchpad.net/~haxe/+archive/ubuntu/releases).

I cannot reproduce the problem on my Mint 17.2, haxe package version 1:3.2.1+dfsg-1~ubuntu14.04.1~ppa1.

**Comment by r3d9u11** [comment]
yes, I tried it. but I saw this error and with 3.2.1 too 8(

(In addition to haxe 3.2.1, there is another problem, which forces me to work with 3.2.0: http://stackoverflow.com/questions/33577290/haxeui-projects-wont-compile-for-windows-error-c2259-cannot-instantiate-abs)

**Comment by andyli** [comment]
I will first focus on the fixing 3.2.1. Are you using 32-bit or 64-bit Mint?

**Comment by andyli** [comment]
BTW, the haxe packages we managed (not including eyecreate's) does not strip haxelib, see: https://github.com/HaxeFoundation/haxe-debian/blob/master/debian/rules#L30

**Comment by r3d9u11** [comment]
64bit

**Comment by andyli** [comment]
I've just created a fresh install of Mint 17.2 64-bit, installed haxe from HF's PPA, `haxelib install hxColorToolkit`, `haxelib list`. Everything worked correctly.

Would you double check your currently running haxe version by `dpkg -s haxe`?

**Comment by r3d9u11** [comment]
there was not error at installation time (3.2.0 and 3.2.1)
now I reinstalled haxe from haxe foundation PPA and haxelib works fine, but as I said earlier, this error show after several reboots.
so, when I see this error, I will send more detailed report.

thank you for your help!
