### ISSUE TITLE
[new analyzer] zero and empty string propagation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4739]
this is very minor, but nevertheless quite common:
```haxe
class Main {
    static function main() {
        var a = 0;
        if (Math.random() < 0.5)
            a += 2;

        var b = "";
        if (Math.random() < 0.5)
            b += "hello";

        // don't dce those
        trace(a); trace(b);
    }
}
```

generates
```js
Main.main = function() {
	var a = 0;
	if(Math.random() < 0.5) a = 0 + 2;
	var b = "";
	if(Math.random() < 0.5) b = "" + "hello";
	console.log(a);
	console.log(b);
};
```
we could get rid of those useless zero and empty string, couldn't we?

**Comment by Simn** [comment]
We can definitely concatenate empty strings. I'm not sure about strings in general, IIRC @ncannasse sent mixed messages regarding that.

**Comment by nadako** [comment]
Strings in general yeah, I remember concerns about constant string pool size or something, but empty strings should be safe. The case with empty strings is quite common because on js, StringBuilder is an inlined class that uses string concat under the hood.

**Comment by nadako** [comment]
what about integer zeroes?

**Comment by Simn** [comment]
That always worked, your example failed because it was on the right side of a variable assignment and the algorithm didn't use constant replacements there.
