### ISSUE TITLE
good christmas

### ISSUE THREAD

**Issue by Celsyum** [HaxeFoundation/haxe#4741]
just tried:
trace(Std.string(christmas()));
	
function christmas(dem:Int = 1):Int
	{ 
	   var t:Int = dem;
	   for (i in 0...10)
		  t += christmas(i);
	  return t;
	}

html5 target.
Got while compiling:
C:/HaxeToolkit/haxe/lib/lime/2,7,0/lime/utils/Float32Array.hx:7: lines 7-58 : Type not found : js.html.Float32Array

flash target:
C:/HaxeToolkit/haxe/lib/openfl/3,4,0/openfl/net/URLRequest.hx:295: characters 0-20 : Type not found : flash.net.URLRequest

**Comment by Simn** [comment]
Merry christmas to you too, but that's a lime/openfl problem.
