### ISSUE TITLE
[analyzer] Compiler flag to output warnings for dead code

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4744]
It's nice that the analyzer can detect unused local variables and remove them, but ideally dead code like that isn't part of a codebase in the first place. It would be helpful have a way to output these as compiler warnings (`-D warn-unused-local-vars`?).

Warnings for unreachable code like this would be nice too (`"Unreachable return"`):

``` haxe
function f():Bool
{
    throw "Error";
    return false;
}
```

**Comment by Simn** [comment]
I'm reluctant here because dead code/variables can be introduced for all sorts of reasons while compiling. The previous effect-checker gave silly warnings on some inline code, and it can get really crazy with macros too.

**Comment by Simn** [comment]
We report unreachable code now. I see no sane way of reporting unused variables, there's just too much going on with macros, inlining and optimization that might introduce legitimate unused variables, and cleaning them up via DCE is the better option.

**Comment by Gama11** [comment]
This also counts as dead code I guess: 3565d16f909ee4a6448c734f302e2d2abaee4903

(just creating a reference to the commit)

**Comment by Simn** [comment]
I had implemented dead code warnings, but it turned out to be rather impractical with all the generated code involved, and Nicolas ultimately decided not to have this feature.
