### ISSUE TITLE
[js] File "codegen.ml", line 29, characters 62-68: Assertion failed

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4748]
Using recent source code for Haxe (back to November 25th and up to the latest) I receive the following error when attempting to build Lime or OpenFL HTML5 projects:

    File "codegen.ml", line 29, characters 62-68: Assertion failed

I'm not really sure where this is coming from, but I am trying to dig deeper to get a better idea what is causing this. Have there been other reports of JavaScript projects failing?

Thanks

**Comment by nadako** [comment]
That's probably what @Gama11 reported before and is related to Lime/OpenFL replacing `js.Boot` which is not a good idea. We added `wrap` method to `js.Boot.HaxeError` recently, so it may be related.

**Comment by jgranick** [comment]
Let me take a look, thank you!

**Comment by jgranick** [comment]
That was it, thank you. If you do not mind, I have opened a pull request with the remaining key change we had in our boot file:

https://github.com/HaxeFoundation/haxe/pull/4749/files

The other changes are fixed in Haxe 3.2+, which we recently began requiring as a minimum version

:shipit:
