### ISSUE TITLE
StringTools.isEof and -xml compilation

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4750]
I noticed something funny in haxe.xml.Parser when compiling all.hxml:

```haxe
using StringTools;

class Main {
	static function main() {
		var str = "foo";
		var p = 0;
		var c = str.fastCodeAt(p);
		while (!StringTools.isEof(c)) {
			c = str.fastCodeAt(++p);
		}
		trace("ok"); // Warning : Unreachable code
	}
}
```

I was about to panic when I saw that StringTools.iseof has this:

```haxe
#else
return false;
#end
```

This indeed means that the while-loop is infinite. It doesn't matter because "cross" code is never actually evaluated, but it's relevant for analysis. I also wonder if there are other cases like that in the standard library.

**Comment by waneck** [comment]
Make it return true for xml?

**Comment by Simn** [comment]
It occurred to me that we don't have to run the analyzer in "cross" mode anyway.
