### ISSUE TITLE
Analyzer assertion with `var` in value place

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4754]
```haxe
class Main {
	static function main() {
		"" + var str = "";
	}
}
```

Fatal error: exception Assert_failure("analyzer.ml", 1011, 4)

I feel like this should fail much earlier...

**Comment by ncannasse** [comment]
Before, var was only allowed into a TBlock, but it could still be added at another place with macros

**Comment by Simn** [comment]
I understand that the syntax is allowed, but I don't quite see why this should make it through the typer.

**Comment by Simn** [comment]
I realized that the same could happen with other `Void` constructors such as `while`. In the end this is a matter of `everything is an expression`, so I'll just change the analyzer assertion to a proper error.
