### ISSUE TITLE
Optimizing calls involving default values

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4755]
``` haxe
class Main {
    static function main() {
        opt("bar");
    }

    static function opt(a = "foo") {
        trace(a);
    }
}
```

This currently generates this Javascript:

``` js
Main.main = function() {
    Main.opt("bar");
};
Main.opt = function(a) {
    if(a == null) a = "foo";
    console.log(a);
};
Main.main();
```

Something I've come up with in genc a while ago is the concept of "known" calls. Here's the generated C code:

``` c
void Main__hx_known_opt(String* a){
    printf("%s:%d: %s\n","Main.hx",7,String_raw(a));
}

void Main_main(){
    Main__hx_known_opt(HX_STR("bar"));
}

void Main_opt(String* a){
    if(NULL == a){
        a = HX_STR("foo");
    }
    return Main__hx_known_opt(a);
}
```

It's a bit of a trade-off: We get rid of the branching for known calls while we have an additional function call in other case. However, there are many cases where we could actually go for call-site replacement of the default value. This is true for at least all static calls, and technically also for all member calls of fields that are not overridden (though we have to be careful with that).

**Comment by delahee** [comment]
Imvho, this can dramatically increase code size...which generates lots of cache misses and generally unwanted for mobile apps. I suggest this optimisation could be hinted by author or user controllable via comp meta or something...And that is limits itself to function weighting less than X instructions ?

**Comment by Simn** [comment]
This doesn't increase code size, it just separates the default-value-branching from what the function actually does.

**Comment by delahee** [comment]
well a function entry does but...oh nevermind. let's start as is and see what happens.

**Comment by ncannasse** [comment]
I don't think that helps a lot performance wise. And it doesn't work well for member methods because of overriding

**Comment by Simn** [comment]
Not worth it...
