### ISSUE TITLE
Cannot assign a non-nullable abstract to null (even with @:from)

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4756]
I apologize in advance if there is a clever way to achieve what I want.

Here is an example of a custom enum type:

```haxe
@:enum abstract CustomEnum(Int) {
	
	var HELLO = 1;
	var WORLD = 2;
	
	@:from private static inline function fromString (value:String):CustomEnum {
		
		return switch (value) {
			
			case "hello": HELLO;
			case "world": WORLD;
			default: cast 0;
			
		}
		
	}
	
	@:to private static inline function toString (value:Int):String {
		
		return switch (value) {
			
			case CustomEnum.HELLO: "hello";
			case CustomEnum.WORLD: "world";
			default: null;
			
		}
		
	}
	
	@:op(A == B) private static inline function equals (left:CustomEnum, right:Dynamic):Bool {
		
		if (right == null && cast (left, Int) == 0) return true;
		return left == right;
		
	}
	
}
```

The idea is that it is an abstract over Int, so it is light and fast, but it can convert to and from custom Strings. The issue here is the nullability of standard Haxe enums. If I use `Null<Int>` as the base type, it fixes the problem of being able to `value = null`, but should there not be a way using `@:from` or some other form of control over assignment?

The `@:op(A == B)` helps fix the `if (value == null)` case, but `value = null` results in an array that the type cannot be null.

I'd prefer not to use `Null<Int>` due to the number of Dynamics it produces. Is morphing `value = null` into `value = 0` not possible for the current abstract implementation?

Thanks :smile:

**Comment by Simn** [comment]
Your abstract fails on current Haxe with `src/Main.hx:33: characters 15-28 : Recursive operator method`, which makes sense.

This is probably the counter-case to #3376, but you would have to post how exactly you're trying to use your abstract.

**Comment by Simn** [comment]
No followup.

**Comment by jgranick** [comment]
I am having this problem again, with another abstract.

Apologies for the lack of response, there are a lot of Github notifications, and I don't catch them all :smile:

Here's a small sample of what I'm asking:

```haxe
abstract IntPointer(Int) {
    
    public function new (ptr:Int) {
        
        this = ptr;
        
    }
    
    @:from private static function fromNull (value:Null<Int>):IntPointer {
        
        return cast 0;
        
    }
    
}
```

The @:from doesn't work, and I don't necessarily think `Null<T>` is ideal, but somehow, it would be nice to be able to handle null assignment on a non-object type abstract.

This won't work:

```haxe
var ptr:IntPointer = null;
```

...no matter what I try. Is there some "from null" conversion I'm missing, somehow?

Thank you
