### ISSUE TITLE
[PHP] inline functions are not inlined anymore?

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4760]
Has sometthing changed with regard to inlined functions? With the current compiler version I get lots of extra functions in the generated PHP code (`ClassName_0`, `ClassName_1`,...) for functions that were inlined before.

**Comment by Simn** [comment]
Not that I'm aware of. Do you have an example?

**Comment by mockey** [comment]
Hm, it's a problem with my code, it seems. I have an abstract here which turns Haxe `TObjectDecl` into php associative arrays (with a macro). It used to work quite nicely, now it's completely broken.
For a function like:
```
function checkAuthToken(token:String) {
  var res:{valid:Bool} = callFunc({authToken: token});
  authorized = res.valid;
}
```
I used to get:
```
public function checkAuthToken($token) {
  $res = null;
  {
    $args = array("authToken" => $token);
    $res = $this->call(__FUNCTION__, $args);
  }
  $this->authorized = $res->valid;
}
```
(`callFunc` is an inlined function)
now I get:
```
public function checkAuthToken($token) {
  $res = GtoSoapClient_1($this, $token);
  $this->authorized = $res->valid;
}
function GtoSoapClient_1(&$__hx__this, &$token) {
  {
    $args = array("authToken" => $token);
    return $__hx__this->call(__FUNCTION__, $args);
  }
}
```
Any idea how to avoid this extra function `GtoSoapClient_1`? It seems wherever I use my abstract these extra functions are generated now.

**Comment by Simn** [comment]
It probably has to do with the analyzer transformation creating too many temp variables at the moment. I plan to change this for PHP, but I came across a really odd test case which made me kept it for now:

```haxe
class Main {
	static function main() {
		var g = getInt();
		trace(g - g++);
	}

	static function getInt() return 5;
}
```

```php
	static function main() {
		$g = Main::getInt();
		haxe_Log::trace($g - $g++, _hx_anonymous(array("fileName" => "Main.hx", "lineNumber" => 4, "className" => "Main", "methodName" => "main")));
	}
```

This outputs `1` for PHP which I'm pretty sure is lolphp material.

**Comment by mockey** [comment]
Temp variables would be no problem (I think). These extra functions are a major problem. Especially when the code is actually supposed to be inlined. Do you happen to know when and why at all these extra functions are generated? It seems completely arbitrarily and senseless to me.
I tried to reproduce it in a simple example, but I can't get the compiler to generate the extra fucntions there.
Is the analyzer transformation on by default in the current version? There used to be a complier flag for it.. Possible to switch it off?

**Comment by Simn** [comment]
Can you post the -D dump=pretty of checkAuthToken?

**Comment by mockey** [comment]
About `$g - $g++` is  `1`: That's lolphp for sure.
http://php.net/manual/en/language.operators.precedence.php says:
> Operator precedence and associativity only determine how expressions are grouped, they do not specify an order of evaluation. PHP does not (in the general case) specify in which order an expression is evaluated and code that assumes a specific order of evaluation should be avoided, because the behavior can change between versions of PHP or depending on the surrounding code.
```
<?php
$a = 1;
echo $a + $a++; // may print either 2 or 3
```

:-)

**Comment by Simn** [comment]
Ok, so it's simply undefined... I thought I read something different, but apparently I'm wrong. So we actually need temp vars on PHP to make sure we get the right evaluation order.

**Comment by mockey** [comment]
-D dump=pretty looks like this:
```
	checkAuthToken(method) : token : String -> Void

	 = function(token:String) = {
		var res = {
			var args = @:implicitCast __php__("array(\"authToken\" => {0})",token);
			{
				var name = cast __php__("__FUNCTION__");
				var res1 = {
					var args1 = @:implicitCast __php__("array(\"args\" => {0})",args);
					{
						var args2 = {
							var args3 = @:implicitCast __php__("array({0}, {1}, {2}, {3}, {4})",name,args1,null,null,null);
							while ((cast __call__("end",cast args3) == null)) cast __call__("array_pop",cast args3);
							args3;
						};
						__call__("call_user_func_array",cast @:implicitCast __php__("array({0}, {1})","SoapClient","__soapCall"),args2);
					};
				};
				res1.out;
			};
		};
		this.authorized = res.valid;
	}
```
As far as I can tell this looks pretty much as it should. Somewhere on the way lots of extra functions are generated then...

**Comment by mockey** [comment]
About evaluation order: are the other targets perfectly aligned with Haxe there?

**Comment by Simn** [comment]
That's a terrible AST, but I know why it happens. The original function has `untyped` which causes the AST transformer to ignore it. I'll have to check what to do about that exactly.

**Comment by mockey** [comment]
Yeah right, I'm using untyped PHP functions all over the place because I have to deal with native PHP arrays. Why is the AST so terrible? The generated PHP was quite OK.

**Comment by Simn** [comment]
It has blocks in value places which are horrible for PHP.

I'm working on addressing the untyped issue over at https://github.com/Simn/haxe/tree/untyped_vs_analyzer if you want to run a test using that branch. It's not very easy to get this right because we do quite a bit of crazy untyped stuff that should be immune to the analyzer.

**Comment by mockey** [comment]
Well, the blocks come from the inlined functions/abstracts. If they would stay inlined like this, it would be fine for me. My actual problem is the generation of unnecessary extra functions in PHP, which is especially bad if the code is supposed to be inlined.

**Comment by Simn** [comment]
I know where the block come from. The problem is that genphp generates these functions for blocks in value places, which is why we have to remove blocks from value places during post-processing.

**Comment by mockey** [comment]
> The problem is that genphp generates these functions for blocks in value places

Sorry, but two things i still don't understand:
1. Why does genphp so?
2. Why are inlined functions not generating inlined blocks anymore but extra functions just as if they were not inlined?

Will try your branch, though.

**Comment by Simn** [comment]
Can you check again with most recent Haxe?

**Comment by mockey** [comment]
This looks much better at first glance. Inlined functions are really inlined now and there are no more mysterious extra functions genetrated. What did you change?

I have to switch my code back to a previous version to analyze it in full extent, though...

What about `-D analyzer`? Is it enabled by default now? I see no difference with and without...

Also, are tranformations like this intentional (and really necesssary)?
```
if (token == null && Config.app.test) {
  token = fetchAuthToken(lms);
  tokenCached = true;
}
```
becomes
```
$tmp = null;
if($token === null) {
  $tmp = Config::$app->test;
} else {
  $tmp = false;
}
if($tmp) {
  $token = $this->fetchAuthToken($lms, null);
  $tokenCached = true;
}
```
So each part of a compound condition generates its own temp var?

**Comment by Simn** [comment]
Yes analyzer is on by default now.

I agree that transformation looks ugly. I'll see if I can do something about that, but I might keep it this way for now because with PHP it's hard to tell what evaluates in what order.

**Comment by RealyUniqueName** [comment]
Evaluation order of boolean binops is determened in php and follows common sense (afaik).
Can analyzer check if such binops contain other "undefined eval order" operations, and if not - do not generate temporary vars like that in mockey's comment?

**Comment by RealyUniqueName** [comment]
Fixed this for new php generator. Changing it for old one is too dangerous :)
