### ISSUE TITLE
abstracts over @:generic

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4761]
This code currently genrerates wrong output:
```haxe
@:generic
class C<T> {
    public function new() {}
}

abstract A<T>(C<T>) {
    public inline function new() {
        this = new C<T>();
    }
}

class Main {
    static function main() {
        var v = new A<Int>();
    }
}
```
Generated js:
```js
Main.main = function() {
	var v = new C();
};
```
One would expect it to either expand the generic class to `C_$Int` or fail with an error.

**Comment by nadako** [comment]
A somewhat related issue regarding type constraint check. The `C.T` is constrained to have public construtor, however `A.T` is constrained to `S` which itself has public constructor, but its subclass may not, so this should not compile:
```haxe
class S {
    public function new() {}
}

@:generic
class C<T:{function new():Void;}> {
    public function new() {}
}

abstract A<T:S>(C<T>) {
    public inline function new() {
        this = new C<T>();
    }
}

class Main {
    static function main() {
        var v = new A<S>();
    }
}
```

**Comment by nadako** [comment]
BTW what about introducing some `Constructible<CtorType>` constraint abstract instead of weird structure unification as discussed in #4364?

**Comment by Simn** [comment]
Let's disallow abstracts over `@:generic`, I don't even want to think about what that would look like.

I don't see how the constraint check issue is related to this though.

**Comment by Simn** [comment]
Actually... why do you consider this a problem in the first place? We do allow using `@:generic` classes with type parameters in other places as well. This behavior then seems consistent to me.

**Comment by nadako** [comment]
Well, it is a problem since it silently generates invalid code, e.g. this:
```haxe
@:generic
class C<T:{function new():Void;}> {
    public function new() {}
}

class S {
    public function new() {}
}

abstract A<T:S>(C<T>) {
    public inline function new() {
        this = new C<T>();
    }
}

class Main {
    static function main() {
        var v = new A<S>();
    }
}
```
will generate
```js
// Generated by Haxe
(function () { "use strict";
var S = function() { };
var Main = function() { };
Main.main = function() {
	var v = new C();
};
Main.main();
})();
```
note the missing `C` class since it's marked as extern due to constructible constraint.


People are using abstracts to add operator overloading support to their classes, so it's actually makes sense to try using those with `@:generic`. This whole issue is actually raised from a failing code from here:

https://github.com/ktimothy/shared-logic-engine/blob/c3dc42c971d89e3ccaa04a140856c66869ec996a/src-client/sle/core/models/collections/ComplexValueMapBase.hx

https://github.com/ktimothy/shared-logic-engine/blob/9338c593f588c01643ed520626dbeb8aafb42ab1/src-client/sle/core/models/collections/ComplexValueMap.hx

**Comment by Simn** [comment]
This should result in an error "Type parameters with a constructor cannot be used non-generically". Not sure why it doesn't at the moment.

**Comment by nadako** [comment]
I thought so too, that's where it seems to be related to my 2nd comment :)

**Comment by Simn** [comment]
Right, because it checks the constraint of the applied type parameter, which is the one that doesn't have the explicit constructor constraint. In that case I suspect our problems go away once we address constructor constraints properly.

**Comment by Simn** [comment]
I have added Constructible which makes the case error properly now. Structures with `new` are deprecated now.

A type parameter can only be assigned to a Constructible type parameter if it is Constructible too. This deals with visibility and type issues on constructors in sub-classes etc.
