### ISSUE TITLE
"Inline variable ... constant value" when macro returns constant value

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#4763]
Getting _unsuspected_ error "Inline variable initialization must be a constant value" when value is constant.

```haxe
static inline var FILE:String = getCurrentPath(); // <-- HERE
static macro function getCurrentPath()
{
	var pos = Context.currentPos();
	var info = Context.getPosInfos(pos);
	var path:String = info.file;
	return macro '$path';
}
```

But if I remove `inline` then in dump will:
```haxe
static public FILE(var) : String
 = "tests/fzzr/macro/test/DumpTest.hx"
```

IMO problem in order, error throwing before macro `getCurrentPath`.

**Comment by fzzr-** [comment]
Next example not works too:
```haxe
static inline var FILE:String = getConstValue();
static macro function getConstValue()
	return {expr:EConst(CString("I'm a const. Please!")), pos:Context.currentPos()};
```

**Comment by Simn** [comment]
Could you post something I can actually compile?

Also, there's a good chance that the error occurs in macro context due to macro-in-macro.

**Comment by fzzr-** [comment]
Sorry. https://gist.github.com/fzzr-/82f70d84611e848103a9

You can compile it only if you remove `inline`. See diff on top [here](https://gist.github.com/fzzr-/7142db7b174097f6b7f0/revisions).

**Comment by Simn** [comment]
That's macro-in-macro, you will find that it compiles if you do this:

```haxe
	#if !macro
	static inline var A:String = getConstA();
	static inline var B:String = getConstB();
	#end
```

**Comment by fzzr-** [comment]
Awesome! Magic!

**Comment by fzzr-** [comment]
@Simn :+1: Thank you. It was my misunderstanding.
