### ISSUE TITLE
Some issue regarding gencommon and multitype abstracts

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4765]
I'm not entirely sure what happens yet and how to reproduce it, but I think it involves gencommon changing some `cf_type` and `unify_to_field` failing due to that because some unification no longer works.

**Comment by waneck** [comment]
I've seen that. It has to do with how gencommon changes the types temporarily. Because of that, I try to follow all abstracts before any type changes - I might have forgotten some place. Do you have any info on where it happens?

**Comment by Simn** [comment]
Well, I think the issue is that in order to follow a multitype abstract it has to go through `unify_to_field`. I think I should just store the original `cf_type` in `a_to_fields` so messing with the field type doesn't break anything.

**Comment by Simn** [comment]
P.S.: We miss you on #haxe-dev!

**Comment by Simn** [comment]
I'm closing this because I don't really know what to do with it and it's not a problem on the development branch as far as I can tell.

My plan was to change the abstract `this` type to be the abstract from the outside, but the underlying type from the inside (the variable itself). That doesn't seem to be as straightforward as I thought though, so maybe I'll revisit it for Haxe 4.
