### ISSUE TITLE
[PHP] Would it be possible to allow inlined vars with untyped code?

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4770]
It would be quite nice if something like this was allowed for dealing with PHP constants:
`public static inline var phpVersion:String = untyped __php__("PHP_VERSION");`

Right now you have to do:
```
public static var phpVersion(get,never):String;
static inline function get_phpVersion() return untyped __php__("PHP_VERSION");
```
which is OK, but doesn't work in `@:enum abstract` e.g.:
```
@:enum abstract SoapVersion(Int) {
  var SOAP_1_1 = untyped __php__("SOAP_1_1");
  var SOAP_1_2 = untyped __php__("SOAP_1_2");
}
```
You have to lookup the actual integer vaalues there.

**Comment by Simn** [comment]
I'm not sure if that's feasible with the current representation of native code. This is treated like a call which is not a constant expression, which generally makes sense. I have multiple issues with these constructs and would like to see it change, but I'm not quite sure how to go on about it.

**Comment by mockey** [comment]
There's no way to trick the compiler into treating this as a constant somehow with a macro, is there?

**Comment by Simn** [comment]
Unfortunately I see now way to support this without making internal structural changes. We can look at it again for Haxe 4 (#4684), but for the time being I might as well close the issue. Sorry!

**Comment by mockey** [comment]
Note that this was only supposed to be a workaround for using global PHP constants. Since #4925 the example above can be written as:
```
@:native("")
@:phpConstants
@:enum extern abstract SoapVersion(Int) {
  var SOAP_1_1;
  var SOAP_1_2;
}
```
A bit verbose maybe, but works. No `untyped __php__` needed, which is some improvement at least. The only problem left is that the compiler refuses to see this as a real constant. So maybe adding a value to TConstant for that could be considered, like TExtern?

Also externs for global functions can be defined in a similar way now, which eliminates the need for `untyped __call__`.
