### ISSUE TITLE
(null && true) is true in macros

### ISSUE THREAD

**Issue by pperidont** [HaxeFoundation/haxe#4772]
```haxe
class App {

	macro static function testMacro(){
		var a : Null<Bool> = null;
		if( a && true )
			throw "oops";
		return macro {};

	}
	
	static function main(){
		testMacro();
	}
}
```

**Comment by Simn** [comment]
As far as I know this isn't exactly defined, but evaluating this to true is indeed weird.

**Comment by ncannasse** [comment]
if( null ) should not execute for sure

**Comment by Simn** [comment]
I don't think it does, the problem should be specific to the && case because rhs is evaluated if lhs is not `VBool false` explicitly.

**Comment by ncannasse** [comment]
Actually in neko, everything that is not VBool true is false, so you can instead do
VBool true -> e2()
_ -> VBool false

**Comment by Simn** [comment]
Thanks, that's indeed better.
