### ISSUE TITLE
sys API and unicode

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4773]
Have to fix issues and test the sys API for non-ASCII inputs, including
- `Sys.command` and `Process` with non-ASCII `cmd`/`args`.
- `File` and `FileSystem` with non-ASCII file names.

Possibly related to #3072.

**Comment by Simn** [comment]
Is this resolved?

**Comment by andyli** [comment]
Blocked by #3072.

**Comment by Simn** [comment]
Should be fixable now!

**Comment by Simn** [comment]
Addressed by #8135.
