### ISSUE TITLE
test and document sys.io.Process

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4774]
See the comments in https://github.com/HaxeFoundation/haxe/commit/48104849b6a71303a14212b4be29104f9876194a.

**Comment by Simn** [comment]
@Aurel300 Could you check the status here?

**Comment by Aurel300** [comment]
The Unicode tests make heavy use of `sys.io.Process`, but all the uses are rather similar. It might be best to have a separate test suite for all process-related things.

**Comment by Simn** [comment]
I'm mostly interested in the documentation being somewhat accurate.

**Comment by Simn** [comment]
Closing due to focus on the new asys API.
