### ISSUE TITLE
Greater than NaN

### ISSUE THREAD

**Issue by NekR** [HaxeFoundation/haxe#4776]
This simple code `0 > Math.NaN` reports `true` on Neko and `false` on JS. Which is expected on JS, do not know about Neko.

What about others? And why it's not unified/aligned for all targets?

**Comment by Simn** [comment]
If this is part of the IEEE-specification then neko should indeed comply.

**Comment by NekR** [comment]
@Simn I believe it's, but I am not sure.

I am porting a lib from Java/C#/JS (cross complied) and its tests fails on `0 > Math.NaN` case when tested on Neko and are fine on JS. I also tested this expression explicitly on Neko to be sure that it reports `true`. So if Java/C#/JS all reports `false`, then I assume that it's standard behavior.

Can anyone test on C/C++ target?

**Comment by NekR** [comment]
Okay, I actually test this way: `trace(['nan test', Math.NaN > 0, 1 > Math.NaN]);` and both is `false` on JS and `true` on Neko. So I assume that every operation with `NaN` should be `false` (like equality).

**Comment by Simn** [comment]
This is not really a Haxe issue, but I'll keep it open because we should add tests for it. The fix itself should be made in neko though: https://github.com/HaxeFoundation/neko

**Comment by NekR** [comment]
@Simn Okay, create an issue right in Neko repository.

**Comment by ncannasse** [comment]
Could I get a report of which platforms are concerned ? Also, we need to check all operations, such as < , >= etc.

**Comment by ncannasse** [comment]
It seems indeed that IEEE specify that all comparisons on NaN returns false 
http://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values

**Comment by Simn** [comment]
Indeed, which makes it pretty likely that only neko fails here. Though I won't be surprised if PHP messes it up as well.

**Comment by Simn** [comment]
Looks like this has already been fixed on neko. It fails in the macro interpreter though.

It also fails on travis Linux PHP which is 5.3.10. It doesn't fail on OSX which uses 5.4.30, and it doesn't fail on my local Windows 5.4.7 either. Since we wanted to up the minimum supported PHP version anyway this should deal with that problem.

So there's only the macro interpreter to fix.

**Comment by NekR** [comment]
I am on latest OS X (10.11.2, 64 bit of course). Neko reports this line `NekoVM 2.0.0 (c)2005-2013 Haxe Foundation`, but I got it with Haxe install.

@Simn should I update Neko/Haxe to get the fix or it's not released yet?

**Comment by Simn** [comment]
It probably hasn't been part of a release yet. We'll make a neko release once we make a new Haxe release. In the meantime you can try the nightly builds: https://github.com/HaxeFoundation/neko#nightly-builds

**Comment by NekR** [comment]
Okay, I got it. Thanks @Simn.
