### ISSUE TITLE
Abstract as Map key

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4777]
```haxe
abstract A(String) from String to String {}

var map:Map<A, String>; //Abstract Map has no @:to function that accepts IMap<A, String>
```

Currently we cannot use abstract as Map's key type, is it possible to tell the compiler to drill down to the abstract's concrete type and use the corresponding @:to casts?

**Edit**: `to String` should be removed to produce the error.

**Comment by Simn** [comment]
This works already: http://try.haxe.org/#24D97

**Comment by ncannasse** [comment]
I understand that it breaks variance constraint, but could we allow the Map as well even if the abstract does not have the `to` ? Map selection should be based on actual underlying type since it's the reason why we have different implementation. A metadata on Map would work.

**Comment by ncannasse** [comment]
PS: I'm often hitting this issue since CastleDB generates such abstracts

**Comment by Simn** [comment]
I'm not sure about that. Why would you not have `to` in the first place?

This would not only violate variance (which it already does in the presence of `to` and `from` anyway) but also have another strange property: `Int <- Abstract` wouldn't unify, whereas `Int <- (MapKeyOut <- MapKeyIn) <- Abstract` would.

**Comment by ncannasse** [comment]
I don't want the type to auto-cast. The Map is a specific case since we want to choose based on runtime type

**Comment by kevinresol** [comment]
Oops yes im using cdb exactly.  And it missed the to

**Comment by Simn** [comment]
I'll have to think about this and don't want to make a hasty change here. If anything we should solve this via the typing system and not make a Map-specific hack.

**Comment by ncannasse** [comment]
Yes that's why I'm proposing to add a metadata for this @:followAbstracts

**Comment by Simn** [comment]
But where would you add that metadata? To Map? That would also make it follow value type abstracts which might not be what you want in some cases.

**Comment by ncannasse** [comment]
Uhm, it would need to apply to multitype, and IMap as well

**Comment by ncannasse** [comment]
I agree that's not easy: we don't want to create variance here, we just want the corresponding IMap implementation to be correctly choose based on the abstract underlying typ

**Comment by Simn** [comment]
I think the best approach is to do this:

```haxe
@:multiType(@:followWithAbstracts K)
abstract Map<K,V>(IMap<K,V> ) {
```

We can then apply `follow_with_abstracts` to the type parameter before picking a specialization.

**Comment by Simn** [comment]
... but I think the key-abstract in question should also have a say in this. Maybe `@:followWithAbstracts` should also be required to be present on the abstract that is to be used as map key?

**Comment by ncannasse** [comment]
I don't think that's a good idea to require both ways. What harm can it created if not?

**Comment by Simn** [comment]
I'm a bit worried about library design. Maybe I want to have an abstract over Int which can't be used as an IntMap key for some reason. I can't think of a concrete example though, and we can always add `@:doNotFollowWithAbstracts` later if the need arises.

**Comment by ncannasse** [comment]
Well, it should be usable as an IntMap key anyway, because it's not an Int. But it will be usable as a Map key, which will use an IntMap implementation

**Comment by ncannasse** [comment]
*NOT

**Comment by Simn** [comment]
Yeah I get that. Actually it's a bit strange to allow it as Map key but not as IntMap key. But then again we allow array access on Map and not on IntMap already, so it's not too surprising to have such a difference.
