### ISSUE TITLE
cl.exe problem compilation on windows

### ISSUE THREAD

**Issue by SergOmarov** [HaxeFoundation/haxe#4778]
Running process: C:\Program Files (x86)\FlashDevelop\Tools\fdbuild\fdbuild.exe "C:\Users\KapustinSergey\Documents\Haxe\Test\Test.hxproj" -ipc 26ed195f-67a3-4ded-a943-ecf39753f00c -version "3.2.0" -compiler "C:\HaxeToolkit\haxe" -notrace -library "C:\Program Files (x86)\FlashDevelop\Library" -target ""
Building Test
haxe  -cp src -cpp C:/Users/KapustinSergey/Documents/Haxe/Test/bin -main Main
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.201" -Dhxcpp_api_level="321" -I"src/" -I"C:\\HaxeToolkit\\haxe\\extraLibs/" -I"" -I"C:\\HaxeToolkit\\haxe\\std/cpp/_std/" -I"C:\\HaxeToolkit\\haxe\\std/"
cl.exe -Iinclude -nologo -O2 -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/Std.cpp -FoC:/Users/KapustinSergey/Documents/Haxe/Test/bin/obj/msvcxp/ae7b103b_Std.obj
cl.exe -Iinclude -nologo -O2 -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/Main.cpp -FoC:/Users/KapustinSergey/Documents/Haxe/Test/bin/obj/msvcxp/ae7b103b_Main.obj
cl.exe -Iinclude -nologo -O2 -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/__files__.cpp -FoC:/Users/KapustinSergey/Documents/Haxe/Test/bin/obj/msvcxp/ae7b103b___files__.obj
Process creation failure : cl.exe

cl.exe -Iinclude -nologo -O2 -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/__boot__.cpp -FoC:/Users/KapustinSergey/Documents/Haxe/Test/bin/obj/msvcxp/ae7b103b___boot__.obj
Sys_error("haxelib run hxcpp Build.xml haxe -Dhaxe3=\"1\" -Dhaxe_ver=\"3.201\" -Dhxcpp_api_level=\"321\" -I\"src/\" -I\"C:\\\\HaxeToolkit\\\\haxe\\\\extraLibs/\" -I\"\" -I\"C:\\\\HaxeToolkit\\\\haxe\\\\std/cpp/_std/\" -I\"C:\\\\HaxeToolkit\\\\haxe\\\\std/\": No error")
Build halted with errors (haxe.exe).
Done(1)

**Comment by Simn** [comment]
This is not a useful issue report. How did you set things up? What are you actually trying to compile? How are you trying to compile it?

Try hitting the haxelang google group with a bit more information.

**Comment by ncannasse** [comment]
If cl.exe is not found it means you don't have Visual Studio correctly setup
