### ISSUE TITLE
Allow pattern matching abstracts against constants if suitable == is available

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4784]
In essence, I would very much like [this](http://try.haxe.org/#e3B82) to work:

``` haxe
class Test {
    static function main() {
        var f = new Foo('foo');
        switch f {
                case 'foo': //does not compile because String should be Foo, but I wish it would since `==` is defined in this case
        }
    }
}

abstract Foo({v:String}) {

    public function new(v) this = { v: v };

    public inline function toString()
        return this.v;

    @:commutative @:op(a == b) static inline function equalsString(a:Foo, b:String) return a.toString() == b;
}
```

Any thoughts on that? I expect there will be reservations, but given that after long discussions, we've been able to agree that allowing getters in pattern matching would be ok, I was wondering if we might just apply the same argument here, i.e.: responsible programmers will not use `==` to cause side effects.

**Comment by Simn** [comment]
I can't see how this would integrate with the decision tree generation, so I don't think we can support this with proper pattern matching. We could only allow this if we had a switch "mode" which would treat it like an if...else chain, for which this is not even a special case.

**Comment by back2dos** [comment]
Meh. I struggle to understand what you might mean by "proper pattern matching". As for how this might be possible at all: if the types are not equal, but `==` works for them, capture the value in a variable and move the comparison with the constant out into the guard. I guess that kind of comes close to your "if...else mode"-idea.

**Comment by Simn** [comment]
I might rewrite the pattern matcher soon, especially if we go through with #4715. At the moment the problem with guards (and by extension custom equality comparison) is that it duplicates the "else" code, so I'm not very keen on extending it in the current form.

**Comment by Simn** [comment]
Looking at this again, I still don't see how we could support it and I'm not sure we want to in the first place.
