### ISSUE TITLE
Add haxe.ds.AnyMap

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4785]
The recurrent struggles of using `Map` made me think if it makes sense to add a fallback map implementation. There's small issues like #4777, but then there's also things like people stuffing keys into `ObjectMap<Dynamic, _>` that clearly do not belong there (e.g. classes, functions and what not).

For the time being I would propose a really simple implementation over two arrays (one with keys, one with values) as a fallback and then we can start optimizing from there, if anyone really cares. I can make a pull request with the changes + tests but I was wondering if this is considered worth adding at all.

**Comment by ncannasse** [comment]
Apart from functions, which are the types not working? (and no, Bool is not a real-world example :) )

**Comment by back2dos** [comment]
Interesting, I didn't know it works for classes. I'm surprised that it compiles at all, but so long as it does, I won't complain.

In that case, we're left with:

- functions
- floats - if that is a use-case (?)
- anything that is not an object, e.g. native stuff like `@:coreType abstract ResourceHandle {}`

**Comment by Simn** [comment]
I do wonder if this is worth putting time and energy into, but that might just be because I never had a use-case for any of these.

**Comment by back2dos** [comment]
Well, my biggest concern is really to not have the compiler tell you `Abstract Map has no @:to function that accepts IMap<X, Y>`. For new comers that's got to be a relatively intimidating error. And it seems weird that something as a map literal would suffice to get it.

**Comment by Simn** [comment]
If that's the main issue then we can simply improve on the error message.

**Comment by ncannasse** [comment]
I agree that improving the error message should be enough

**Comment by back2dos** [comment]
I just generally find maps should be easier to use:

```haxe
var classesNames = [
  String => 'String',
  Array => 'Array'
];
```

Fails because `Class<Array> should be Class<String>`. This actually seems fair enough. Inference cannot really know what I'm trying to achieve. Well then, let's try to be explicit:

```haxe
var classesNames:Map<Class<Dynamic>, String> = [
  String => 'String',
  Array => 'Array'
];
```

Nope. `Cannot use Class<Dynamic> as key type to Map because Class<T> is not comparable`. Meh. Ok. Well then at least this should work:

```haxe
var classesNames:Map<Dynamic, String> = [
  String => 'String',
  Array => 'Array'
];
```

But no, `Abstract Map has no @:to function that accepts IMap<Dynamic, String>`.

What I don't get is why there should be an error in the first place. As long as something is a value, it should just work as map key. Principle of the least surprise and all that.

**Comment by back2dos** [comment]
I suppose this better be a PR.
