### ISSUE TITLE
Improvement of search Haxe documentation 

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#4789]
If you have little knowledge of Haxe (target js) the search isn't helping you to fix questions you might have.

For example:

I am looking for something very specific: "querySelector" (in javascript target) because I want to know what it returns.

So first try: searchbox : "querySelector"
nothing...

So then I have to find out in what package it's in (which is strange because isn't search for that)
Okay for some reason I know this: searchbox "document"
works: get a couple of options, I choose the correct one...

http://api.haxe.org/js/html/Document.html
Lets search for "querySelector" .... wow that is long list
search won't help me here: so I use the "Find" from the browser

I currently use google to find something in haxe documentation: https://www.google.nl/#q=querySelector+haxe

it's quicker....

so here my question: should the search box help my find "querySelector"?

(http://api.haxe.org/js/html/Document.html#querySelector)

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe.org/issues/143
