### ISSUE TITLE
Invalid typed AST

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4791]
In unit tests, the following code
```
abstract MyAbstractThatCallsAMember(Int) to Int {
	public function new(i) {
		this = i;
		//bar();
	}

	inline function bar() this++;
}
```

Produces the following dump:

```
private class unit._MyAbstract.MyAbstractThatCallsAMember_Impl_{
	static public _new(method) : i : Int -> unit.MyAbstractThatCallsAMember

	 = [Function:i : Int -> unit.MyAbstractThatCallsAMember]
		[Arg:Int] [Local i(4416):Int]
		[Block:Dynamic]
			[Var this1(4417):Int] [Local i(4416):Int]
			[Binop:Void]
				[Local this1(4417):Int]
				=
				[Binop:Void]
					[Local i(4416):Int]
					+
					[Const:Int] 1
			[Return:Dynamic] [Cast:unit.MyAbstractThatCallsAMember] [Local this1(4417):Int]

	static bar(inline method) : this : Int -> Void

	 = [Function:this : Int -> Void]
		[Arg:Int] [Local this1(4418):Int]
		[Block:Int]

}
```

The error comes from the `i + 1` TBinop which type is TVoid instead of TInt. Both Binop types are invalid actually.

**Comment by Simn** [comment]
The TUnop comes out of the inliner typed as Void because of this: https://github.com/HaxeFoundation/haxe/blob/development/optimizer.ml#L636

Not sure what exactly that case is supposed to optimize.

**Comment by Simn** [comment]
This is related to #1037. Back then you said this:

> We could, but we have then to check that $type(set(1)) is still Void, or else we risk to have access to some data we shouldn't.

This seems to contradict the issue here where we don't want the expression type to be Void. We even have a test for this:

```haxe
	function testInline()
	{
		typedAs(inlineTest1([1]), var void:Void);
	}

	inline function inlineTest1<T>(map:Array<T>) {
		map[0];
	}
```

**Comment by Simn** [comment]
Never mind, it was actually about the specific case where we don't have a TBlock for the expression. I changed it so we block-wrap the function expression if we want to Void it.

I don't know how to write a test for this, but I'm sure your branch is going to cover it one way or another.
