### ISSUE TITLE
Recursive enum serialization

### ISSUE THREAD

**Issue by tanis2000** [HaxeFoundation/haxe#4794]
I'm trying to solve a problem that keeps the VSCode Haxe debugger extension from working on Mac and Windows and I noticed that this same problem is also happening with the command line debugger.

Here's a pretty long thread with all the details:
https://github.com/jcward/vscode-hxcpp-debug/issues/25

As far as I can tell, it all boils down to haxe.Serializer.run() having troubles serializing an enum. 
A good example of an enum having troubles is https://github.com/HaxeFoundation/hxcpp-debugger/blob/master/debugger/IController.hx#L55

All of the enums whose response has the same value of the enum itself are ending up in a recursive serialization even though the enum itself is different. 

I can't understand if it's an error in the serialization code of haxe.Serializer or if there's something else that I'm not understanding. 

Thanks for any help. Cheers!

**Comment by Simn** [comment]
Are you using the serialization cache?

http://api.haxe.org/haxe/Serializer.html?#USE_CACHE
http://api.haxe.org/haxe/Serializer.html?#useCache

**Comment by tanis2000** [comment]
No, I'm not setting any of them. Just default values. The test project is compiled with `openfl build mac -debug -DHXCPP_DEBUGGER`

**Comment by Simn** [comment]
I don't know how to help you with this. Recursive value serialization certainly works if the serialization cache is used. Unless you can come up with an example that shows otherwise I don't think this is a Haxe issue.

**Comment by tanis2000** [comment]
Here's how to reproduce it:

Grab hxcpp debugger
`git clone https://github.com/HaxeFoundation/hxcpp-debugger.git`

Add it to haxelib
```
haxelib dev debugger hxcpp-debugger
```

Compile and run the server
```
cd hxcpp-debugger
haxe -main debugger.HaxeServer -cpp ./Export -cp debugger
./Export/HaxeServer -host 127.0.0.1 -port 6972
```

Make sure you have lime and openfl or install them with haxelib
```
haxelib install lime
haxelib install openfl
```

Grab my repo with the test project
`git clone https://github.com/tanis2000/test-vscode-openfl.git`

Compile and run the test project
```
cd test-vscode-openfl
openfl build mac -debug -DHXCPP_DEBUGGER
Export/mac64/cpp/bin/DisplayingABitmap.app/Contents/MacOS/DisplayingABitmap
```

The client will connect to the server so switch back to the terminal running the server and issue the following command: `files`
You will see that it gets stuck there. Ctrl-C out of the server and the client will crash with the same stacktrace as mine.

**Comment by Simn** [comment]
Sorry but if this is a Haxe issue it has to be reproducible without these libraries. I might check it out if it's just the hxcpp-debugger, but once lime and OpenFL get involved I can't help you.

**Comment by tanis2000** [comment]
That's easily solved. I have the same problem with a simple command line Haxe program with no other external libraries except for hxcpp-debugger.

Just clone this repo:
`git clone https://github.com/tanis2000/test-vscode-cli.git`

Compile it in debug mode and run it:
```
cd test-vscode-cli
haxe -main Main -cpp ./export -debug -D HXCPP_DEBUGGER -cp <path/to/yout/hxcpp-debugger>
export/Main-debug
```

Again, issue the `files` command in the server console and observe it getting stuck.

**Comment by Simn** [comment]
```
Listening for client connection on 127.0.0.1:6972 ...

Received connection from 127.0.0.1.

1>
Thread 0 stopped in Main.main() at Main.hx:64.
files

C:\GitHub\haxe\std/List.hx
C:\GitHub\haxe\std/StringTools.hx
C:\GitHub\haxe\std/cpp/Lib.hx
C:\GitHub\haxe\std/cpp/Random.hx
C:\GitHub\haxe\std/cpp/_std/Date.hx
C:\GitHub\haxe\std/cpp/_std/EReg.hx
C:\GitHub\haxe\std/cpp/_std/Reflect.hx
C:\GitHub\haxe\std/cpp/_std/Std.hx
C:\GitHub\haxe\std/cpp/_std/StringBuf.hx
C:\GitHub\haxe\std/cpp/_std/Sys.hx
C:\GitHub\haxe\std/cpp/_std/Type.hx
C:\GitHub\haxe\std/cpp/_std/haxe/ds/IntMap.hx
C:\GitHub\haxe\std/cpp/_std/haxe/ds/ObjectMap.hx
C:\GitHub\haxe\std/cpp/_std/haxe/ds/StringMap.hx
C:\GitHub\haxe\std/cpp/_std/sys/io/FileInput.hx
C:\GitHub\haxe\std/cpp/_std/sys/net/Host.hx
C:\GitHub\haxe\std/cpp/_std/sys/net/Socket.hx
C:\GitHub\haxe\std/cpp/vm/Debugger.hx
C:\GitHub\haxe\std/cpp/vm/Deque.hx
C:\GitHub\haxe\std/cpp/vm/Gc.hx
C:\GitHub\haxe\std/cpp/vm/Mutex.hx
C:\GitHub\haxe\std/cpp/vm/Thread.hx
C:\GitHub\haxe\std/haxe/CallStack.hx
C:\GitHub\haxe\std/haxe/Log.hx
C:\GitHub\haxe\std/haxe/Serializer.hx
C:\GitHub\haxe\std/haxe/Unserializer.hx
C:\GitHub\haxe\std/haxe/io/Bytes.hx
C:\GitHub\haxe\std/haxe/io/Eof.hx
C:\GitHub\haxe\std/haxe/io/Input.hx
C:\GitHub\haxe\std/haxe/io/Output.hx
Main.hx
debugger/DebuggerThread.hx
debugger/HaxeProtocol.hx
debugger/HaxeRemote.hx

2>
```

Seems to work fine for me... That's on Windows by the way.

**Comment by tanis2000** [comment]
Now that's interesting. Are you using the stable Haxe 3.2.1? 
Any chance that you can run that code on an OSX box as well? I know it's not just me as both me, @jcward  and Bryan from TiVo can reproduce this same issue, but I would like to see what's different if you can make it work. Thanks!

**Comment by Simn** [comment]
I'm on git versions of everything (Haxe, hxcpp, hxcpp-debugger). I've just tried with 3.2.1 and get the same result. No OSX box here to test though.

**Comment by tanis2000** [comment]
@Simn can I kindly ask you to help me find someone from the Haxe Foundation who can try this code on OSX to understand if it's a platform problem or if there's anything else going on?

**Comment by Simn** [comment]
We're not very mac-heavy around here. Maybe @andyli can help.

Either way, this can't possibly be a serialization problem if we're talking about different platforms. I'll go ahead and close this to avoid discussion fragmentation, let's continue this at https://github.com/jcward/vscode-hxcpp-debug/issues/25.
