### ISSUE TITLE
`while (--i >= 0)` becomes `while (true) { --i; if (!(i >= 0)) break;`

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#4797]
So I've just updated to the current version (b9ccf19), and, quite suddenly,
```haxe
class Main {
	static function main() {
		var i:Int = 5;
		while (--i >= 0) trace(i);
	}
}
```
now compiles to
```js
function() {
	var i = 5;
	while(true) {
		--i;
		if(!(i >= 0)) break;
		console.log(i);
	}
};
```
`-D analyzer` makes no difference.
This is a little weird, to say at least.
The previous git version that I've used (d976532) did not show this behavior.

**Comment by Simn** [comment]
Thanks, I focused so much on properly rebuilding postfix unops that I forgot about the prefix ones.
