### ISSUE TITLE
[suggestion] argument names in function type syntax

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4799]
I keep remembering about it from time to time and finally decided to open a discussion.

Currently, our function type syntax `TArg1 -> TArg2 -> TReturn` doesn't allow specifying argument names in it, which is a bit unfortunate, because e.g. `String -> String -> Bool -> Void` doesn't describe much about what those arguments actually mean, so additional documentation is required.

One could argue that it's a bad practice to use primitives like that and we could use `typedef` for giving argument more meaning via its type, e.g. `typedef UserId = String`, and then `UserId -> Void`, but this solution has two problems:
1) it's not very handy to create extra types just for describing arguments
2) it won't help when you have several arguments of the same type (e.g. `sender:UserId, receiver:UserId`)

So I'm proposing to support parsing the syntax that we'are already using when printing function types e.g. in completion (`name1 : Type2 -> ?name2 : Type2 -> ReturnType`), so it could be used like this:

```
typedef MessageCallback = sender:UserId -> receiver:UserId -> message:String -> Void
```

Of course, argument names still shouldn't matter when unifying and serve purely for documentation and completion purposes.

---

While writing this proposal, I found out that it would require changing `complex_type.CTFunction` signature, and thus `haxe.macro.Expr.ComplexType.TFunction`, so I'm not sure if this can be implemented in 3.x without breaking macros, which is discouraging. However I'd like to know what are you guys thinking about the idea in general, maybe I'm missing something?

Also, If we talk 4.x, maybe it would be fair to change function type syntax to something that doesn't suggest auto-currying? Something like C# delegates come to mind, but I don't know how to adapt that for haxe, maybe something like `typedef MyCallback = function(a:Int, b:String):Void`?

**Comment by nadako** [comment]
This would also help a lot for IDEs to auto-generate callback functions/method. Without that we have to generate some generic `a`, `b`, `c` argument names which sucks a lot. :-(

**Comment by back2dos** [comment]
Also, I do think that generally `{ sender:UserId, receiver-> UserId }->Void` is a better signature than `Sender->Receiver->Void` because 1. order does not matter 2. adding another field to the argument object doesn't break code, adding another argument the argument list does.

Which doesn't mean that adding names to arguments in function types is a bad idea. I just personally don't see it as something worth a breaking change. 

That being said, we can have this without breaking anything.

```haxe
typedef Named<T, Const> = T;

// the following can be parsed:

sender:UserId -> receiver:UserId -> Void

// and is interpreted like so:

Named<String, "userId"> -> Named<String, "senderId"> -> Void
```

I don't think that would break anything. All that's needed is to extend the parser and then make the typer translate it to TFun nicely. Granted, it's a hack, but it seems rather innocent.

**Comment by nadako** [comment]
That is a nice idea, given that haxe 4 isn't something on the horizon yet.

**Comment by nadako** [comment]
I'm trying to implement a macro that supports node.js new [`util.promisify`](https://nodejs.org/api/util.html#util_util_promisify_original) function in a type-safe way and once again I stumble upon this issue. The fact that argument names are lost during typing is very unfortunate here, because we can't generate a new function type based on the given one, preserving nice signatures. So since we're now working on Haxe 4, I want to look into this.

**Comment by nadako** [comment]
We'll have to think about the actual syntax a bit more here, because the solution I went with in #6428 is flawed (see #6433).
