### ISSUE TITLE
You cannot use the library 'mysql' inside a macro.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#4800]
It would be somewhat useful for building types from database schema, anyone else feel likewise? haxe 3.2.1

**Comment by back2dos** [comment]
True, but I sense that including mysql in the compiler is not really going
to happen. For that particular case, you could also export the schema to a
file and process that. To get the schema automatically, you might be able
to use a mysql CLI through sys.io.Process. Hope that helps.

**Comment by Simn** [comment]
What he said.
