### ISSUE TITLE
JS output stability

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4805]
I made a first commit after working for some time with compilation server.
Then came back later for a very small fix.
The JS output differs in several places not related to my change.

https://github.com/ncannasse/castle/commit/f5cc749d0341f45eba3d2ba5b91528ec75cec85d

**Comment by Simn** [comment]
Oh boy, this is gonna be one of _these_ issues isn't it?

There's something wrong with abstract `this`:

```haxe
// Main.hx
class Main {
	static function main() {
		trace(new Test().concat("foo"));
		trace(new Test().concat("foo"));
	}
}

// Test.hx
abstract Test(String) {
	public inline function new() {
		this = "";
	}

	public inline function concat(s:String) {
		return this + s;
	}
}
```

Compiling this once:

```js
	var this1 = "";
	console.log(this1 + "foo");
	var this2 = "";
	console.log(this2 + "foo");
```

Modifying Main.hx and compiling again:

```js
	var this1 = "";
	console.log(this1 + "foo");
	var this11 = "";
	console.log(this11 + "foo");
```

What's interesting is that after modifying Test.hx and compiling again we get the original output. I'm not quite sure what this tells us though.

**Comment by Simn** [comment]
Okay I know why. We always register `this` to be renamed in `rename_local_vars`. This also applies to the constructor of `Test` in the example above, turning it into `this1`. When recompiling we use that variable at the call-site, so `rename_local_vars` receives `this1` for both variables.

Now how do we address that...

**Comment by ncannasse** [comment]
I'm not sure I follow you. What makes the second compilation of Test different than the first one ?

**Comment by Simn** [comment]
* Compile
* Inline a function: Among other things we make a copy of variables via `let v' = alloc_var v.v_name v.v_type in`. Notice the `v.v_name`.
* Post-process: `rename_local_vars` renames `this` to `this1`.
* Compile again after the inlining module changed.
* Inline the function again, but now the variable we are inlining has changed its name. We again alloc a copy using `v.v_name`, i.e. `this1`.
* Post-process again: `rename_local_vars` renames `this1` to `this11` (if there are two `this1`).

**Comment by ncannasse** [comment]
I see. And we can't do the inlining after the rename_local_vars because they might be necessary at this point.

**Comment by ncannasse** [comment]
And while we're at it, a second stability issue which has been out for some time now, is the feature detection of the enum toString generation, see 
https://github.com/ncannasse/castle/commit/a16af9e9a748d68cc252f9cfe0390df52b882b18 ($estr changes)

**Comment by ncannasse** [comment]
@Simn since we keep the original name in v_meta now, could we not start with it when looking at adding a digit ? it should work quite nicely.

**Comment by Simn** [comment]
Yes, we could basically save the `v_name` state in `rename_local_vars`, though I think that's only necessary for inline (and `@:generic`?) fields.

**Comment by Simn** [comment]
Also I feel like I fixed that `$estr` issue at least 3 times already...

**Comment by Simn** [comment]
... which means we should finally add some tests for that compilation server of yours. What's the easiest way to get a module to recompile without changing the source file?

**Comment by ncannasse** [comment]
@Simn on Unix a touch should do it

**Comment by Simn** [comment]
I think the variable names are alright now.

Regarding `$estr`: This is related to how we keep track of the features state. The intended way for single compilation is this:

1. When DCE marks an enum it sets the "has_enum" feature.
2. When genjs detects the "has_enum" feature it generates `$estr`.

The question for the compilation server is if that feature is still active in the second compilation. With features being a Hashtbl on the common context I thiiiink that should be the case? But apparently it is not for some reason that's beyond my understanding of our compiler state.

**Comment by ncannasse** [comment]
Common context is not kept between compilations in compilation server. However DCE is re-run given that might include additional code.

**Comment by Simn** [comment]
Ok, I think I figured out what's wrong. Let me know if this helped.

I'll try to add a test for this somehow.

**Comment by Simn** [comment]
I'll consider this closed.
