### ISSUE TITLE
Typer Assertion Failed

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe#4806]
(This was mentioned on the mailing list and got no response so here I am.)

I have a project that attempts to override the standard library Maps to use ES6 Map types (https://github.com/explorigin/es6-coretypes)

However, when I use map literal declaration like this:

```haxe
class Trial {
  static function main() {
    var a = [
      "hi" => "bye"
    ];
    trace(a.get("hi"));
  }
}
```

...I get a compile time error like this:

```File "typer.ml", line 3033, characters 10-16: Assertion failed```

For reference the relevant code is https://github.com/HaxeFoundation/haxe/blob/haxe-3.2.1/typer.ml#L3030

Is this a Haxe bug?  Is there something different I can do with my overlay type so I can support map literals?

**Comment by Simn** [comment]
The compiler expects Map to be an abstract and you redefine it as a class.
