### ISSUE TITLE
Specific way of definition a map cause an specific enum key to have a null value

### ISSUE THREAD

**Issue by hammeron-art** [HaxeFoundation/haxe#4807]
This is a strange issue and I not sure how to describe it.
Take a look at:
http://try.haxe.org/#18286
The output of mMneToCode[RET(null)] is null.
Now comment any line from 20 to 22, eg:
```haxe
    public static var mMneToCode(default, never):Map<OpCode, MCode> = [
        RET(null) => mk(0xF5, 8),
        RET(CNZ)  => mk(0xC0, 8),
        //RET(CZ)  => mk(0xC8, 8),
        RET(CNC)  => mk(0xD0, 8)
    ];
```
And suddenly it works.

**Comment by Simn** [comment]
This falls under "If `a` and `b` are null, the result is 0. If only one of them is null, the result is unspecified." on Reflect.compare which EnumValueMap uses. In other words, don't rely on null-values for map keys.

**Comment by back2dos** [comment]
> In other words, don't rely on null-values for [EnumValueMap] keys

Doesn't that mean by extension that you can't leave optional arguments? If so, then I think this deserves a proper solution.
