### ISSUE TITLE
Type parameters are invariant ?

### ISSUE THREAD

**Issue by pleclech** [HaxeFoundation/haxe#4813]
Hi everyone,

This test case give me an error: http://try.haxe.org/#3276C

```haxe
class Pair<A,B> {
    public function new(){}
}

interface IMatcher {}

class StringMatcher implements IMatcher {
    public function new(){}
}

class Test {
    static function main() {
        var ra:Array<IMatcher> = [];
        ra.push(new StringMatcher());
        
        var rb:Array<Pair<String, IMatcher>> = [];
        rb.push(new Pair<String, StringMatcher>());
    }
}
```
Build failure
Test.hx:18: characters 16-49 : Pair<String, StringMatcher> should be Pair<String, IMatcher>
Test.hx:18: characters 16-49 : Type parameters are invariant
Test.hx:18: characters 16-49 : StringMatcher should be IMatcher
Test.hx:18: characters 16-49 : For function argument 'x'

I don't understand why in this case the type parameter should be invariant, the first case is ok. So i expect also to be able to push whatever implements IMatcher into rb ?

**Comment by Simn** [comment]
In the general case this is not sound. You can easily construct failing examples by using a `cast` to shut the compiler up:

```haxe
class Pair<A,B> {
	public var fst:A;
	public var snd:B;
	public function new() {}
}

interface IMatcher { }

class StringMatcher implements IMatcher {
	public function new(){}
	public function match(s:String) { }
}

class NotStringMatcher implements IMatcher {
	public function new(){}
}

class Main {
	static function main() {
		var rb:Array<Pair<String, IMatcher>> = [];
		var stringMatcher = new Pair<String, StringMatcher>();
		rb.push(cast stringMatcher);
		rb[0].snd = new NotStringMatcher();
		stringMatcher.snd.match("foo"); // uh oh
	}
}
```

This could only be supported through explicit variance which is currently not planned to be included.

**Comment by pleclech** [comment]
Well, snd should be a IMatcher and i shouldn't be able to call match as it's not define into the interface ?

**Comment by Simn** [comment]
That's irrelevant, the point is that unsound code would type-check if this was allowed.

**Comment by ncannasse** [comment]
@pleclech all type parameters are invariant in Haxe. If you add a " public var b : B" to you Pair you can understand how it would produce unsound code.

**Comment by sledorze** [comment]
Actually enums type parameters (are not but) could be covariant.
I guess it could be tricky to add to the compiler.. (and maybe to support on some static targets).

**Comment by pleclech** [comment]
@simm @ncannasse  Yep i get it ;)

Well now how about some field imutability so the compiler can allow this kind of variance ;)

**Comment by sledorze** [comment]
It also involve cheking type usage position in methods ('in' or 'out').

**Comment by ncannasse** [comment]
@pleclech detecting variance is not the issue here. Correctly applying it with type inference and polymorphism is very hard. I had a branch with per parameter variance some long time ago, it was full of issues and was creating a lot of overweight for the compiler type checking. I don't think that's worth supporting it.
