### ISSUE TITLE
Java target broken with Haxe 3.3

### ISSUE THREAD

**Issue by sorka95032** [HaxeFoundation/haxe#4818]
We're using the java target to generate java code that we link into an Android app. This used to work fine with 3.1.3 but now with 3.3 it complains  about building a core class without building the core library. 

**trouble processing "java/_StdTypes/Int64_Impl_.class":**
Ill-advised or mistaken usage of a core class (java.* or javax.*)
when not building a core library.
This is often due to inadvertently including a core library file
in your application's project, when using an IDE (such as
Eclipse). If you are sure you're not intentionally defining a
core class, then this is the most likely explanation of what's
going on.
However, you might actually be trying to define a class in a core
namespace, the source of which you may have taken, for example,
from a non-Android virtual machine project. This will most
assuredly not work. At a minimum, it jeopardizes the
compatibility of your app with future versions of the platform.
It is also often of questionable legality.
If you really intend to build a core library -- which is only
appropriate as part of creating a full virtual machine
distribution, as opposed to compiling an application -- then use
the "--core-library" option to suppress this error message.
If you go ahead and use "--core-library" but are in fact
building an application, then be forewarned that your application
will still fail to build or run, at some point. Please be
prepared for angry customers who find, for example, that your
application ceases to function once they upgrade their operating
system. You will be to blame for this problem.
If you are legitimately using some code that happens to be in a
core package, then the easiest safe alternative you have is to
repackage that code. That is, move the classes in question into
your own package namespace. This means that they will never be in
conflict with core system classes. JarJar is a tool that may help
you in this endeavor. If you find that you cannot do this, then
that is an indication that the path you are on will ultimately
lead to pain, suffering, grief, and lamentation.
1 error; aborting

:app:dexUsCoreDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexUsCoreDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

The Int64.hx class is completely different in this version of haxe vs 3.1.3.

**Comment by Simn** [comment]
Are you into Java fanfiction or is that really the error message you're getting?

**Comment by back2dos** [comment]
It's a thing:
http://stackoverflow.com/questions/10157213/error-importing-jar-to-android-project
;)

**Comment by EBatTiVo** [comment]
@Simn Yes, that is the error message we are seeing.

**Comment by Simn** [comment]
@waneck: Could you check this?

**Comment by waneck** [comment]
@Simn I think it'd DCE not doing its part here. This implementation https://github.com/HaxeFoundation/haxe/blob/development/std/java/StdTypes.hx#L27 should be totally eliminated, shouldn't it?

**Comment by Simn** [comment]
I don't see why that should be eliminated if it's being used. It's a `@:coreType` abstract, if you access one of its fields we need the type to be kept.

**Comment by waneck** [comment]
Well, there's no implementation on any function. Not sure why it'd generate an empty impl class

**Comment by Simn** [comment]
Yes but that's up to the generator in my opinion. We don't eliminate used extern classes that have no implementations either.

... this is leading to `extern abstract` again isn't is?

**Comment by waneck** [comment]
It always leads to that :)

It's a little weird for me that a `@:coreType abstract` will generate an impl class
But I guess I can handle it on the generator as well

**Comment by Simn** [comment]
Well if it has code on its fields that code has to go somewhere.

I'll allow `extern abstract` by applying it to the implementation class. Do you reckon that's enough?

**Comment by sorka95032** [comment]
I pulled the change and tried it with our pre 3.3 release build:

FAILURE: Build failed with an exception.

* What went wrong:
translating haxe failed: /sandbox/moved/haxetools/mainline/dev-host/root/haxe/std/java/StdTypes.hx:27: characters 43-51 : extern abstract not allowed

**Comment by EBatTiVo** [comment]
@Simn, We assumed that the noted change would be all we would have to change in order to test.  Our sources for the compiler are about six to eight weeks old, so if there are recent changes that are likely to be required, let us know.

BTW, sorka95032 is a TiVo engineer.

**Comment by nadako** [comment]
b027f01cc90e48989a7442eb183bf8381433f77a is the commit that introduces support for `extern abstract`.

**Comment by Simn** [comment]
Sorry for not being clear about that. I allowed `extern abstract` in the commit @nadako mentions and then applied it to Java's Int64 type. This means you will have to use the very latest Haxe source to test this.

**Comment by EBatTiVo** [comment]
@sorka95032 is this fixed well enough that we can close the bug?

**Comment by Simn** [comment]
Any news on this? Our 3.3 RC is coming up so I would like to make sure this is working.

**Comment by sorka95032** [comment]
My apologies. I thought I had replied back here again but it appears I didn't. That change works fine once we pulled in other dependent. The Android product builds and runs successfully.

**Comment by Simn** [comment]
Glad to hear that, thanks for confirming!
