### ISSUE TITLE
Inline @:enum abstract value into another

### ISSUE THREAD

**Issue by aW4KeNiNG** [HaxeFoundation/haxe#4819]
Hi!

I want to reuse an enum in other enum like flags. But it is giving an error: "Inline variable initialization must be a constant value".

```
@:enum
abstract Enum1(Int) from Int to Int
{
   var AA = 1;
}

@:enum
abstract Enum2(Int) from Int to Int
{
   var BB = Enum1.AA << 4;
}
```

I consider that it is a bug because this code works:
```
@:enum
abstract Enum2(Int) from Int to Int
{
  var BB = Enum1.AA;
}
```

So, i think that Enum1.AA isn't evaluated if the right expression is composed with a binary operator or another complexity.

For now, the temporal solution that i have (thanks to basig):

```
@:enum
abstract Enum1(Int) from Int to Int
{
	static public inline var aa = 1;
	var AA = aa;
}

@:enum
abstract Enum2(Int) from Int to Int
{
	static public inline var bb = Enum1.aa << 4;
	var BB = bb;
}
```

But it has boilerplate code.

Thanks in advance.

**Comment by eliasku** [comment]
+1

Very painful. Are you ever making combined Flags definitions?
```
var DIRTY_TRANSFORM = 1 << 1;
var DIRTY_COLOR = 1 << 2;
var DIRTY_ALL = DIRTY_TRANSFORM | DIRTY_COLOR;
```
Now we should make workaround like this:
```
@:enum abstract DirtyFlags(Int) to Int from Int {
	var TRANSFORM = 0x1;
	var COLOR = 0x2;
	public static var ALL(default, null):DirtyFlags = TRANSFORM | COLOR;
}
```

**Comment by Simn** [comment]
This wasn't really about `@:enum` abstract values in general but about the specific operations you were doing. I've allowed more numeric operations as constant expressions now.

**Comment by aW4KeNiNG** [comment]
Thanks @Simn :)
