### ISSUE TITLE
@:multiType abstract new

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4823]
The multitype abstract `new` method cannot have a body, but still reach code generators with no body. I think we should tag at as @:extern automatically so it does not get generated (is_extern_field would be true) - I don't think it needs to anyway?

Ping @Simn

**Comment by Simn** [comment]
It should never reach code generators in the first place, that doesn't make any sense.

**Comment by ncannasse** [comment]
It seems it does. Maybe the class should be marked as cl_extern?

**Comment by Simn** [comment]
I think I misread the issue. I thought you said that there's a `new MultiTypeAbstract()` somewhere, but if it's just about the method itself then I agree marking it as extern makes sense.

**Comment by ncannasse** [comment]
Yes, it's the method itself

**Comment by ncannasse** [comment]
This can be reproduced by trying to compile unit/src/unit/MyAbstract.hx with HL.
Adding @:extern in front of the function new does solve the issue.
