### ISSUE TITLE
Improving syntax/completion errors handling

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4830]
It would be nice if the compiler gives warnings when we forget simple things. Now you somtimes get unexpected errors and is hard to see where the error might come from.

_Example 1:_

``` haxe
class Test {
    static animator:Animator; // << oops forgot `var` here
    static function main() {
        animator. // << request completion here
    }
}
class Animator { }
```

This will result in an error `No classes found in animator`. This is a really vague error, no hint on the position where it went wrong. It would be nicer to have an error like `Test.hx line 2: Unexpected declaration / Invalid syntax. Suggestion: add var or function.`.

_Example 2:_

``` haxe
class Test {
    static var animator:Animator // << oops forgot semicolon here
    static function main() {
        animator. // << request completion here
    }
}
class Animator { }
```

This will result in an error `No classes found in animator`. It would be nicer to have an error like `Test.hx line 2: missing ;`.

``` haxe
class Test {
    static function main() {
    // oops forgot } here
}

```

When you compile, it results in an error `Test.hx:8: character 0 : Unexpected <end of file>`. It would be nice if it gives hints about which function/var is unclosed.

These are all suggestions and I understand this might be a challenge to improve because of the parsing process, but sometimes I don't understand what the errors mean.

**Comment by Simn** [comment]
Unfortunately that's not how parsers work. For completion in particular we have to assume an invalid AST and skip parts of it. It's hard to decide which syntax errors are "intentional" and which are not.

I'm not closing this straight away because it might indeed be possible to improve this, but I'm very reluctant to meddle with parser resuming.

**Comment by markknol** [comment]
Ok thanks for not closing it. As I said I understand it is hard, still might be a very welcome improvement.

**Comment by Simn** [comment]
Nothing we can do here with the current parser.
