### ISSUE TITLE
Regexp compilation error on Linux

### ISSUE THREAD

**Issue by SunShiranui** [HaxeFoundation/haxe#4831]
Hello,
While experimenting with regexp trying to match international characters, I stumbled upon what I think might be a bug. If I try this: 
`		var pattern:EReg = new EReg("\\p{C}", "gu");
		trace(pattern.match(char));`
I get the following error on the Linux target (using openfl), but not in neko:
`Regexp compilation error : support for \P, \p, and \X has not been compiled in \p{C}`

Is this an issue with my own system setup or a Haxe bug?
Thank you.

**Comment by ncannasse** [comment]
It most likely means your pcre3 library has not been compiled with unicode support. Please report to the following repository: https://github.com/haxefoundation/hxcpp
