### ISSUE TITLE
Date.getTime documentation should be improved

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#4834]
The [Date.getTime()](https://github.com/HaxeFoundation/haxe/blob/development/std/Date.hx#L53-L56) [documentation](http://api.haxe.org/Date.html#getTime) states:

> Returns the timestamp of the date. It might only have a per-second precision depending on the platforms.

The word _might_ is not ideal in technical documents, and could turn off potential Haxe users perusing the docs. And handling time is a pretty common task.

I think the docs could be improved by stating exactly which platforms have which resolution. Running a quick test on Linux, I see:

Second resolution: cpp, neko
Millisecond resolution: php, python, java, flash, js
(I couldn't test C#)

Is it actually platform dependent (cpp on linux vs win vs iOS), or merely target language dependent?

Perhaps note Sys.time() for getting the current timestamp on cpp, cs, java, macro, neko, php, python

Thus, I might suggest something like (updated per conversation below):

> Returns the timestamp of this Date in milliseconds.
> 
> Note that in cpp and neko targets Date only supports second resolution (e.g. 1454698271000.) To obtain the current timestamp with better precision, see the Sys.time API.

**Comment by Simn** [comment]
I wonder why it is like that on neko. @ncannasse

**Comment by jcward** [comment]
Or cpp, since they both have the capability of obtaining millisecond accuracy with `Sys.time`. It's one of those things that's always seemed odd.

**Comment by ncannasse** [comment]
On Neko I am using the libc api for date, which uses an Int32 for storage and a struct tm for manipulation. http://en.cppreference.com/w/c/chrono/tm I'm not sure if there's a better way to handle them. 

I would not rely on such API anyway to perform benchmarking, you usually need some even more precise API (micro seconds) and if possible measured for the current process, not a full system time.  

For instance on windows you might use QueryPerformanceCounter https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx

**Comment by delahee** [comment]
+1 with NC

**Comment by jcward** [comment]
That's all well and good, but my issue is with the documentation, which basically states "yeah, this API kinda sucks, sorry!" with no further guidance. I'm not talking about people looking for microsecond precision benchmarking, I'm talking about people looking for simple timestamps, probably coming from JavaScript and expecting something like `new Date().getTime()`. The doc says "good luck, this might work!" And the dev says, "Ok, Haxe isn't for me!"

**Comment by ncannasse** [comment]
I am open to suggestion to improve the precision of the Date function on Cpp/Neko, as long as we rely on standardized C API that don't turn into a system-specific mess to maintain.

**Comment by andyli** [comment]
@jcward Before anyone acutally look into improving the precision of the Data function, would you suggest a doc revision that will sound better?

**Comment by andyli** [comment]
Ah, I see that there is an suggested edit in the issue description. Anyone object to that?

**Comment by Simn** [comment]
* "integer second resolution" sounds strange, we can do without the "integer".
* I don't think we have to list all sys targets manually.
* According to the Sys.time documentation it returns the "most precise timestamp value (in seconds)" so referring to it like that appears to be incorrect.

**Comment by jcward** [comment]
I'm not opposed to those suggestions. What about this:

> Returns the timestamp of `this` Date in milliseconds.
>
>Note that in cpp and neko targets `Date` only support second resolution (e.g. 1454698271000.) To obtain the current timestamp with better precision, see the `Sys.time` API.

**Comment by Simn** [comment]
Are we talking about the same `Sys.time`? Because [the one I'm looking at](http://api.haxe.org/v/dev/Sys.html?#time) is documented to return seconds as unit, which is not exactly more precise than seconds.

**Comment by jcward** [comment]
Right, seconds is the unit, but as a float, the precision is millisecond or better: 1454962095.381

**Comment by Simn** [comment]
Ah it returns `Float`, I missed that. I suppose it's fine then.
