### ISSUE TITLE
Invalid Int64.toString()

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#4835]
It seems to reproduce on targets emulating Int64 (javascript and flash confirmed). It works fine on c++ target.

```
nano Int64Bug.hx && haxe Int64Bug.hx -js Int64Bug.js -main Int64Bug && node Int64Bug.js
```

```
class Int64Bug {
        static public function main() {
                trace(haxe.Int64.make(2147483647, -1) + haxe.Int64.make(0, 1));
        }
}
```

Output:
```
--9-2-2-3-3-7-20-3-6-8-5-4-7-7-5-80-8
```

Expected:
```
-9223372036854775808
```

Probably the problem is in this function:
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Int64.hx#L127

**Comment by andyli** [comment]
Cannot be reproduced in JS. It should be fixed by #4178.
