### ISSUE TITLE
Invalid TEnumParameter

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4846]
In Issue2988.hx, the TEnumParameter value is of Dynamic type, which makes it impossible to know which was the enum which was matched. It should be wrapped with a cast, actually ideally we should create a tmp var casted to the correct type so all TEnumParameters use this typed var instead of the Dynamic one.

**Comment by Simn** [comment]
It strikes me that this is remarkably similar to GADT: We start with a generic subject type (here `Dynamic`) and specialize it depending on the pattern.

We talked about the temp var before in GADT context and you mentioned the problem of someone assigning to it. We would need per-case types for variables:

```haxe
var d:Dynamic = Something;
switch (d) {
    case Specific(t):
        var d_generated = (d : Specific); // nicely typed temp var
        var t = TEnumParameter(d_specific); // use that for TEnumParameter
        d = SomethingElse; // assign to original var
        $type(d); // This is still Dynamic, bad
        $type(d_generated); // This is Specific, fine, but we can't use it
}
```

**Comment by ncannasse** [comment]
Both seems orthogonal. I think we should always have TEnumParameter on a correctly typed expr (using an unsafe cast if necessary), then we can look at optimizing GADT

**Comment by Simn** [comment]
Yes casting is fine. You were talking about creating a temp var and I pointed out why that might not work properly.
