### ISSUE TITLE
HL passing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4850]
HL is passing all unit tests, expect some specific cases that needs to be handled, I'm opening this meta issue so we can keep track of it.

https://github.com/HaxeFoundation/haxe/issues/4823
https://github.com/HaxeFoundation/haxe/issues/4254
https://github.com/HaxeFoundation/haxe/issues/4849
https://github.com/HaxeFoundation/haxe/issues/4847
https://github.com/HaxeFoundation/haxe/issues/4846

Counting on @Simn to help with these :)

**Comment by Simn** [comment]
The tests pass for me locally now. #4849 and #4829 are issues you'll have to address. Both related tests are disabled for now.

Travis has two failures:

```
Test.hx:296: START
TestReflect.hx:120: true should be false (10000000000 is Int)
TestReflect.hx:121: true should be false (-10000000000 is Int)
Test.hx:221: DONE [6543 tests]
```
