### ISSUE TITLE
Vector problem on the SWF target.

### ISSUE THREAD

**Issue by JoanBotella** [HaxeFoundation/haxe#4854]
```
// import flash.Vector;
import haxe.ds.Vector;

class Wrapper<TElement>{

	private var storage:Vector<TElement>;

	public function new(length:Int):Void {
		storage = new Vector<TElement>(length);
	}

	public function set(index:Int, value:TElement):Void {
trace("a");
		storage[index] = value;
trace("b");
	}

}

class Main{

	static public function main():Void {
		var w:Wrapper<Float> = new Wrapper<Float>(5);
		w.set(0, 2.3);
	}

}
```

The letter "b" never shows up for this little piece of code, targeting SWF. Other targets displays them both perfectly. Using flash.Vector instead of haxe.ds.Vector do not change the result. Another example:

```
//import flash.Vector;
import haxe.ds.Vector;

class Wrapper<TElement>{

	private var storage:Vector<TElement>;

	public function new(length:Int):Void {
		storage = new Vector<TElement>(length);
trace("a");
trace(storage.length);
trace("b");
	}

}

class Main{

	static public function main():Void {
		var w:Wrapper<Bool> = new Wrapper<Bool>(5);
	}

}
```

Nothing is displayed after the "a".

**Comment by Gama11** [comment]
Are you using the Flash Debug Player to see exceptions that might pop up?

**Comment by JoanBotella** [comment]
Sorry, I'm not. Working on installing it on my system. I didn't say this before, but I'm on a 64-bit Linux, using the Haxe Compiler v3.2.1 . I think something is not right even if flash throws an exception. The Vector class should behave coherently on all targets, no?

**Comment by JoanBotella** [comment]
Using the Flash Player projector content debugger for Windows, under Wine, It shows these exceptions:

- For the first example:
```
ReferenceError: Error #1056: Cannot create property 0 on Number.
	at test::Wrapper/set()
	at test::Main$/main()
	at boot_f5c4/init()
	at flash::Boot/start()
	at boot_f5c4()
```

- For the second example:
```
ReferenceError: Error #1069: Property length not found on Number and there is no default value.
	at test::Wrapper()
	at test::Main$/main()
	at boot_f5c4/init()
	at flash::Boot/start()
	at boot_f5c4()
```

Maybe it's creating a Number instead of a Vector?

**Comment by ncannasse** [comment]
Compile using -debug to get the correct line numbers

**Comment by ncannasse** [comment]
Also, you shouldn't use haxe.ds.Vector with type parameters unless the class is @:generic : flash will most likely fail to cast vectors between types.

**Comment by JoanBotella** [comment]
- First example:
```
ReferenceError: Error #1056: Cannot create property 0 on Number.
	at test::Wrapper/set()[../../../lib/repo/test/Main.hx:20]
	at test::Main$/main()[../../../lib/repo/test/Main.hx:32]
	at boot_f5c4/init()[?:1]
	at flash::Boot/start()[/usr/share/haxe/std/flash/Boot.hx:69]
	at boot_f5c4()[/usr/share/haxe/std/flash/Boot.hx:38]
```
- Second example:
```
ReferenceError: Error #1069: Property length not found on Number and there is no default value.
	at test::Wrapper()[../../../lib/repo/test/Main.hx:13]
	at test::Main$/main()[../../../lib/repo/test/Main.hx:22]
	at boot_f5c4/init()[?:1]
	at flash::Boot/start()[/usr/share/haxe/std/flash/Boot.hx:69]
	at boot_f5c4()[/usr/share/haxe/std/flash/Boot.hx:38]
```

I'm targeting many languages, and I thought Vector would be safe enough. It does not fail for PHP, JAVA or C++. If there is a problem with haxe.ds.Vector just for flash, I think it should be warned on the haxe.ds.Vector API documentation. I know about the flash.Vector, but as I've said before, it fails too. It's interesting that the exception messages are exactly the same.

**Comment by Simn** [comment]
#4783
