### ISSUE TITLE
Static StringMap variable generate unoptimized code in haxe nightlybuid

### ISSUE THREAD

**Issue by daisuda** [HaxeFoundation/haxe#4855]
After I updated my haxe compiler from 3.2.0 to nightlybuild, I found my output swf size is bigger than before. Maybe it is due to many static stringmap var  in my codes like this:

```
 class Main  {
	static var map:Map<String,Int> = new Map<String,Int>();//static
	static function main() 
	{
		//var map:Map<String,Int> = new Map<String,Int>();	// local is ok	
		if ( map.get("hi") != null ) {
		}
	}
 }
```
Haxe Compiler 3.3.0 (git build development @ 06ccf53)

javescript code:
```
// Generated by Haxe
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	var tmp;
	var _this = Main.map;
	if(__map_reserved.hi != null) tmp = _this.getReserved("hi"); else tmp = _this.h["hi"];
};
..........
```
When use local var, the result:
```
// Generated by Haxe
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
	var map = new haxe_ds_StringMap();
	var tmp = __map_reserved.hi != null?map.getReserved("hi"):map.h["hi"];
};
.........

```
Flash target has the same problem.
Btw, how disable analyzer?

**Comment by Simn** [comment]
What exactly do you consider unoptimized here? The unused `tmp` variable looks a bit silly, but that only happens because you "then" has no code in it. The additional `_this` variable saves one `Main.map` field access and also ensures that the value of `Main.map` is not changed by some side-effect in the inlined function.

**Comment by ncannasse** [comment]
The flash String map implementation has changed for a more efficient one that does not make any allocation. If you want to get rid of the reserved identifiers check, you can use haxe.ds.UnsafeStringMap which does not have any reserved identifier check (it might cause issues if you have keys such as "contructor" or "prototype")

**Comment by Simn** [comment]
Isn't this about JS?

**Comment by daisuda** [comment]
The Main issue is the bigger swf/js size.
```
class Main 
{
	static var map:Map<String,Int> = new Map<String,Int>();
	
	static function main() 
	{
		if ( map.exists("hi") ){
			trace("do something");
		}
	}
}
```
Use haxe 3.2.0, the swf code is like this:
```
      public static function main() : void
      {
         var _this:StringMap = Main.map;
         if("hi" in StringMap.reserved?_this.existsReserved("hi"):"hi" in _this.h)
         {
            Log.trace("do something",{
               "fileName":"Main.hx",
               "lineNumber":9,
               "className":"Main",
               "methodName":"main"
            });
         }
      }
```
But after newest haxe compiler compile, it looks like this:
```
      public static function main() : void
      {
         var tmp:* = false;
         var _this:StringMap = Main.map;
         if("hi" in StringMap.reserved)
         {
            tmp = _this.existsReserved("hi");
         }
         else
         {
            tmp = "hi" in _this.h;
         }
         if(tmp)
         {
            Log.trace("do something",{
               "fileName":"Main.hx",
               "lineNumber":9,
               "className":"Main",
               "methodName":"main"
            });
         }
      }
```

PS: 
As @ncannasse  said, UnsafeStringMap is more efficient :) :
```
         if("hi" in Main.map.h)
         {
            Log.trace("do something",{
               "fileName":"Main.hx",
               "lineNumber":8,
               "className":"Main",
               "methodName":"main"
            });
         }
```
But it is not relevant to this issue?

**Comment by ncannasse** [comment]
Indeed, the if should not use a tmp var.

**Comment by Simn** [comment]
Is this really such a big problem or is this mainly about aesthetics?

**Comment by Simn** [comment]
Looks like I've underestimated how much of a difference this makes, my commit strips 9kb off of unit.js.
