### ISSUE TITLE
Issues and pull request  template

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#4859]
https://github.com/blog/2111-issue-and-pull-request-templates
Hey boys and girls, is this something useful?

**Comment by nadako** [comment]
I read about it, but I can't think of any template that wouldn't be annoying :) I think our [contribution guide](https://github.com/HaxeFoundation/haxe/blob/development/CONTRIBUTING.md) is sufficient.

**Comment by Simn** [comment]
Agreed
