### ISSUE TITLE
[cpp] compiler limit: blocks nested too deeply

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#4865]
I was compiling a large file, generated by another project. It does not compile in Visual Studio Community, reporting `compiler limit: blocks nested too deeply`

There is a long chain of "if/else if" like this:

```haxe
else if (structName == "asset") {
	return new Array<LevelOfDetail>();
}
else if (structName == "body") {
	return new Array<LevelOfDetail>();
}
else if (structName == "bodyConfig") {
	return new Array<LevelOfDetail>();
}
else if (structName == "bodyConfigSearch") {
	return new Array<LevelOfDetail>();
}
```

The Haxe generated C++ nests each subsequent step. I'm not sure if this is intentional:

```cpp
HX_STACK_LINE(2425)
											if (((structName == HX_HCSTRING("asset","\xf0","\x69","\x39","\x26")))){
												HX_STACK_LINE(2426)
												return Array_obj< ::Dynamic >::__new();
											}
											else{
												HX_STACK_LINE(2428)
												if (((structName == HX_HCSTRING("body","\xa2","\x7a","\x1b","\x41")))){
													HX_STACK_LINE(2429)
													return Array_obj< ::Dynamic >::__new();
												}
												else{
													HX_STACK_LINE(2431)
													if (((structName == HX_HCSTRING("bodyConfig","\x04","\xeb","\xee","\x0e")))){
														HX_STACK_LINE(2432)
														return Array_obj< ::Dynamic >::__new();
													}
													else{
														HX_STACK_LINE(2434)
														if (((structName == HX_HCSTRING("bodyConfigSearch","\x8c","\x19","\x53","\x67")))){
															HX_STACK_LINE(2435)
															return Array_obj< ::Dynamic >::__new();
														}
```

If there's a reason for it, perhaps we can try and guard against nesting too many times? 

I'm testing with the latest development build as of yesterday.

Thanks!

**Comment by Simn** [comment]
The nesting still happens with the new output:

```c++
HXLINE(   4)		::String structName = ::Main_obj::getStructName();
HXLINE(   5)		if ((structName == HX_("foo",06,c7,4d,00))) {
HXLINE(   6)			::Sys_obj::println(HX_("foo",06,c7,4d,00));
            		}
            		else {
HXLINE(   7)			if ((structName == HX_("bar",d3,b1,4a,00))) {
HXLINE(   8)				::Sys_obj::println(HX_("bar",d3,b1,4a,00));
            			}
            			else {
HXLINE(   9)				if ((structName == HX_("baz",db,b1,4a,00))) {
HXLINE(  10)					::Sys_obj::println(HX_("baz",db,b1,4a,00));
            				}
            			}
            		}
```

Using a `switch` on String on the other hand looks better:

```c++
HXLINE(   5)		::String _hx_switch_0 = ::Main_obj::getStructName();
            		if (  (_hx_switch_0==HX_("aoo",c1,fb,49,00)) ){
HXLINE(   9)			::Sys_obj::println(HX_("ok",1c,61,00,00));
            		}
            		else if (  (_hx_switch_0==HX_("boo",02,be,4a,00)) ){
HXLINE(   7)			::Sys_obj::println(HX_("ok",1c,61,00,00));
            		}
            		else if (  (_hx_switch_0==HX_("coo",43,80,4b,00)) ){
HXLINE(   8)			::Sys_obj::println(HX_("ok",1c,61,00,00));
            		}
            		else if (  (_hx_switch_0==HX_("eoo",c5,04,4d,00)) ){
HXLINE(  10)			::Sys_obj::println(HX_("ok",1c,61,00,00));
            		}
            		else if (  (_hx_switch_0==HX_("foo",06,c7,4d,00)) ){
HXLINE(   6)			::Sys_obj::println(HX_("ok",1c,61,00,00));
            		}
```

@hughsando: Can we unify this?

**Comment by Simn** [comment]
By the way, I'm not sure if that actually avoids the error.

**Comment by ncannasse** [comment]
I think it should, this has to be confirmed

**Comment by hughsando** [comment]
Not sure that will help.  The switch may look better, but in fact it is the same code I think.
However, it should be possible to make the switch better, but not the if-thens.  I think some kind of binary partition on the hash of the strings would work ok.
Once you get over 100, some kind of hash/map would seem better, but don't think we want to do this on the backend.

**Comment by Simn** [comment]
I want to go for what Caue suggested: https://github.com/HaxeFoundation/haxe/commit/9d361c6d14e1f6c004a4f9de0a4b8768afcc40bd#commitcomment-16358988

It should be possible to do that in the pattern matcher directly for targets that prefer it.

**Comment by hughsando** [comment]
My only real concern is with multiple values mapping the the same code.  I guess duplication is not really that much of an issue.  hxcpp could use gotos for common blocks.
As discussed with the java code gen project, having a goto in the ast might be handy - even if you can't generate one from haxe code directly.

**Comment by Simn** [comment]
I agree, see #4715.

I've been experimenting with it in the pattern matcher already but ran into some issues with capture variable scoping.

**Comment by hughsando** [comment]
nice.

**Comment by hughsando** [comment]
So I have put a fix in for this.  It is not optimal because it is a linear series of if statements, rather than a  binary tree, but it should stop the nesting limit issue.  Still be nice for a more optimize solution.

**Comment by hughsando** [comment]
Actually re-reading the original report, I have only fixed the case of "switch", not if-else.
I suggest you try "switch", and reopen the report if this does not work.
Not really sure what I can do is this case though.

**Comment by dpomier** [comment]
I ran into the if-else case today, but not sure if it is suitable to make the compiler deal with this or let the dev carry the responsibility to not violate the target limits.

For the record, this also makes C# hanging.
