### ISSUE TITLE
Unexpected TypeError

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#4866]
``` haxe
import haxe.ds.Vector;
import haxe.ds.Option;

class Main {

	public static function typeError<Element>(option:Option<String>, f:Void->Vector<Element>):Void
	{
		switch (option)
		{
			case Some(v): f();
			case _: throw "Expect Vector";
		}
	}



	static function main() {
		typeError(Some(""), function()return new Vector<String>(0));
	}
}
```

```
$ haxe -version
3.2.1
```

```
haxe -swf Main.swf -main Main
```

```
TypeError: Error #1034: Type Coercion failed: cannot convert __AS3__.vec::Vector.<String>@351f129e4c41 to __AS3__.vec.Vector.<Object>.
	at Main$/typeError()
	at Main$/main()
	at boot_ed23/init()
	at flash::Boot/start()
	at boot_ed23()
```

**Comment by Simn** [comment]
#4783

**Comment by Atry** [comment]
No, they are not the same problem.
This is a Flash-only bug, due to incorrect type erase. The `switch` statement was `typed` as `Vector<Dynamic>`, which is wrong.

**Comment by Simn** [comment]
It's Vector with unapplied type parameter, that's always the same issue. In fact, I think this simply doesn't work at all without inlining.

**Comment by Atry** [comment]
Not really. Haxe compiler should generate underlying `Object` for `Vector<Dynamic>` or `Vector<T>`. The behavior I proposed was exactly what the Haxe compiler did for most cases, (unfortunately not all cases). 

This bug is due to wrong typing for `switch` expression. The Haxe compiler created `__AS3__.vec.Vector.<Object>` (should be `*` or `Object`) for `Unknown<1>`.

**Comment by Atry** [comment]
Scala compiler can handle these situation properly.

For example:
``` scala
    def typeError[Element](option: Option[String], f: () => Array[Element]): Unit = {
        option match {
            case Some(v) => f()
            case _ => throw new Exception("Expect Vector")
        }
    }
```
becomes
``` java
  public void typeError<Element>(scala.Option<String> option, scala.Function0<Object> f) {
    if (option.isDefined) {
      f.apply();
    } else {
      throw new Exception("Expect Vector");
    }
  }
```

Note that Scala `Array[Element]` becomes Java `java.lang.Object` instead of `Element[]`.

**Comment by Atry** [comment]
The above example works for any platform except Flash. So it must a Flash specific bug.

**Comment by Simn** [comment]
I can reopen this, but don't expect any major investigation of this issue anytime soon.

**Comment by ncannasse** [comment]
You cannot use type parameters on Vector in flash, unless you use @:generic, that's a known limitation of the flash player that we can't workaround.

**Comment by Atry** [comment]
We can and we did the workaround. Simply remove the `switch` expression and it works.

**Comment by Simn** [comment]
Let me check one thing, there might be a missing `follow` in genswf9's `type_id`.

**Comment by Simn** [comment]
@ncannasse: Turns out there was code in genswf9 which was supposed to turn `Vector<TypeParameter>` to plain old `Object`, but the check was indeed missing a `follow`.
