### ISSUE TITLE
Read/Write Numeric Data in Std Input/Output

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#4868]
Hi. Can I use method writeDouble, writeFloat, writeInt32, ...etc to read numeric data from std input and write this data to std output?

this code show something unknown chars in my terminal:
...
var stdout = Sys.stdout();
stdout.writeDouble(1.28);
stdout.writeString("\n");
stdout.writeFloat(12.8);
stdout.writeString("\n");
stdout.writeInt32(128);
stdout.writeString("\n");
...

result:

{�G�z�?
��LA
�

------------------------------------
and with this code:

var stdin = Sys.stdin();

stdout.writeString("Int32: ");
var inp_int32 = stdin.readInt32();                     // 123 entered from the keyboard
trace(" --- " + Std.string(inp_int32));

stdout.writeString("Float: ");
var inp_float = stdin.readFloat();                     // 32.1 entered from the keyboard
trace(" --- " + Std.string(inp_float));

stdout.writeString("Double: ");
var inp_double = stdin.readDouble();                     // 443.445 entered from the keyboard
trace(" --- " + Std.string(inp_double));

I have this result:

Int32: 123
Main.hx:40:  --- 858927370

Float: 32.1
Main.hx:44:  --- 4.05178460227695e-11

Double: 443.445
Main.hx:48:  --- 3.21493416237534e-57

----------------------------------------------

I have haxe 3.2.1 
linux mint 17.3 x64

thanks

**Comment by ncannasse** [comment]
these read functions are using binary representation which is most likely not supported on stdin/stdout. Write to String then use Std.parseInt/parseFloat.
