### ISSUE TITLE
[Flash] inline not working in switch

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/haxe#4869]
Using latest windows nightly (haxe_2016-02-22_development).
 
In Flash target, when compiling a "switch" statement similar to the one in 
https://github.com/HaxeFoundation/haxe/issues/4387
but with inline variables, got the error "Constant expression expected".

This is the same error as declaring the variables without inline, so it looks like if "inline" is ignored.
If I write the string directly, it works OK

Thanks

**Comment by Simn** [comment]
Please post a reproducible example.

**Comment by madrazo** [comment]
Hi. Thanks.

If I write my class with static strings it works ok, but I am getting this error using OpenFL (tried with -Dlegacy and without)

This is a modified "DisplayingABitmap" sample. It compiles and runs ok on windows (cpp) target but in Flash yields "Constant expression expected":

    package;


    import openfl.display.Bitmap;
    import openfl.display.BitmapData;
    import openfl.display.Sprite;
    import openfl.Assets;


    import openfl.events.TouchEvent;


    class Main extends Sprite {

            private function switchTest (val:String):Void {


                switch (val) {

                    case TouchEvent.TOUCH_BEGIN:

                        trace("touchBegin");

                    case TouchEvent.TOUCH_MOVE:

                        trace("touchMove");

                    case TouchEvent.TOUCH_END:

                        trace("touchEnd");

                }


        }

        public function new () {

            super ();

            var bitmap = new Bitmap (Assets.getBitmapData ("assets/openfl.png"));
            addChild (bitmap);

            bitmap.x = (stage.stageWidth - bitmap.width) / 2;
            bitmap.y = (stage.stageHeight - bitmap.height) / 2;


            switchTest("touchBegin");

        }


    }

**Comment by Simn** [comment]
Ah I see, this is an instance of #4680.
