### ISSUE TITLE
ExampleJSGenerator throwing error

### ISSUE THREAD

**Issue by TomByrne** [HaxeFoundation/haxe#4871]
I'm attempting to create a custom JS generator.
I've started with the ExampleJSGenerator class, but it is unable to build my project (having trouble with haxe.Resource).

The following code throws an error when attempting to convert an init expression to JS (Line 233):
`api.generateStatement(e)`

I'm using Haxe 3.2.1, it is an OpenFL project.

It has trouble converting this expression to JS:
`{ expr => TBinop(OpAssign,{ expr => TField({ expr => TTypeExpr(TClassDecl(haxe.Resource)), t => TType(Class<haxe.Resource>,[]), pos => #pos(C:\_sdks\haxe\3.2\haxe\std/haxe/Resource.hx:92: characters 2-9) },FStatic(haxe.Resource,content)), t => TInst(Array,[TAnonymous(<anonymous>)]), pos => #pos(C:\_sdks\haxe\3.2\haxe\std/haxe/Resource.hx:92: characters 2-9) },{ expr => TCall({ expr => TLocal({ meta => [{ name => :unbound, params => [], pos => #pos((unknown)) }], name => __resources__, extra => null, $ => #abstract, t => TFun([],TMono(<mono>)), id => 58955, capture => false }), t => TFun([],TMono(<mono>)), pos => #pos(C:\_sdks\haxe\3.2\haxe\std/haxe/Resource.hx:92: characters 20-33) },[]), t => TInst(Array,[TAnonymous(<anonymous>)]), pos => #pos(C:\_sdks\haxe\3.2\haxe\std/haxe/Resource.hx:92: characters 20-35) }), t => TInst(Array,[TAnonymous(<anonymous>)]), pos => #pos(C:\_sdks\haxe\3.2\haxe\std/haxe/Resource.hx:92: characters 2-35) }`

**Comment by Simn** [comment]
What does "has trouble" entail? Also, could you `haxe.macro.TypedExprTools.toString` that expression?

**Comment by TomByrne** [comment]
By 'has trouble' I mean it throws an error and compilation fails.

I've wrapped the `generateStatement` call in a try catch to trace out failed expressions through `TypedExprTools.toString`.
A lot of expressions seem to fail, but I'll just list a few for now.

```
[Binop:Array<{ str : String, name : String, data : String }>]
	[Field:Array<{ str : String, name : String, data : String }>]
		[TypeExpr haxe.Resource:Class<haxe.Resource>]
		[FStatic:Array<{ str : String, name : String, data : String }>]
			haxe.Resource
			content
	=
	[Call:Array<{ str : String, name : String, data : String }>] [Local __resources__(59715):Void -> Unknown<0>]
```

```
[Var DataView(62329):Unknown<5>]
	[Binop:Unknown<4>]
		[Field:Dynamic]
			[Cast:Dynamic]
				[Call:Unknown<3>]
					[Local __define_feature__(62328):String -> Unknown<0> -> Unknown<2>]
					[Const "js.Lib.global":String]
					[Call:Unknown<1>]
						[Local __js__(62327):String -> Unknown<0>]
						[Const "$global":String]
			[FDynamic:Dynamic] DataView
		||
		[TypeExpr js.html.compat.DataView:Class<js.html.compat.DataView>]
```


```
[Block:Bool]
	[Binop:Bool]
		[Field:Bool]
			[TypeExpr lime.system.CFFI:Class<lime.system.CFFI>]
			[FStatic:Bool]
				lime.system.CFFI
				available
		=
		[Const false:Bool]
	[Binop:Bool]
		[Field:Bool]
			[TypeExpr lime.system.CFFI:Class<lime.system.CFFI>]
			[FStatic:Bool]
				lime.system.CFFI
				enabled
		=
		[Const false:Bool]
```

Is there an haxe implementation of the normal JS generator, or is this done entirely in OCaml?

**Comment by Simn** [comment]
What's the compilation error?

**Comment by TomByrne** [comment]
It just says "Invalid call"

**Comment by Simn** [comment]
Since there was no reproducible example here, I can only assume that this has been fixed at some point. Should that not be the case we can reopen the issue.
