### ISSUE TITLE
C# sys tests fail randomly on our CI

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4873]
Appveyor today:

```
Command: mono [C:\projects\haxe\tests\sys\bin\cs\bin\Main-Debug.exe]
Class: TestSys ...... 
Class: TestFileSystem ... 
Class: io.TestFileInput ......... 
Class: io.TestProcess .... 
 
OK 22 tests, 0 failed, 22 success
* Assertion at ..\mono\utils\mono-threads-windows.c:83, condition `res' not met
```

Travis yesterday:

```
OK 22 tests, 0 failed, 22 success
Segmentation fault (core dumped)
Command exited with 139 in 3s: mono [/home/travis/build/HaxeFoundation/haxe/tests/sys/bin/cs/bin/Main-Debug.exe]
```

**Comment by Simn** [comment]
`¯\(O_o)/¯`

**Comment by Simn** [comment]
Happened again today: https://travis-ci.org/HaxeFoundation/haxe/jobs/112599863

I think I'll just wait and hope that it goes away.

**Comment by waneck** [comment]
The only weird problem is that we're not using any unsafe code on this part. If we were, it could be an issue with memory corruption

**Comment by waneck** [comment]
Also it seems to run all tests correctly, and only crash afterwards

**Comment by Simn** [comment]
Yes that's the strangest part in my opinion. It seems to die in `Sys.exit` itself which is quite crazy.

**Comment by waneck** [comment]
That really seems to be a problem with Mono. Checking the source code, it seems to crash here on windows: https://github.com/mono/mono/blob/edb931dfb9741660fefe73528c503b17e1341f4d/mono/utils/mono-threads-windows.c#L83

The thing is - this code has changed a lot on recent versions, and it's no longer like that. Perhaps if we update mono it'll go away

**Comment by Simn** [comment]
Looks like this happens very frequently now. @andyli: Could you take a look regarding mono update?

**Comment by andyli** [comment]
I've [requested](http://help.appveyor.com/discussions/suggestions/954-upgrade-pre-installed-mono) mono to be upgraded in AppVeyor, and use choco to install the latest version for ourselves in the mean time.

But I'm not sure if it will fix the issue since our C# build is currently broken in the native compilation stage.

**Comment by Simn** [comment]
Oh, oops, I didn't notice that because I thought it was the same error. That looks like a bug in gencs related to optional fields on structures. I have made a commit to dodge that for now.

**Comment by andyli** [comment]
Well, with mono 4.2, there is another runtime error:
```
Command: mono [C:\projects\haxe\tests\sys\bin\cs\bin\Main-Debug.exe]
Class: TestSys ..poll_event_wait: mono_poll () failed, error (0)
```

Sounds like mono on Windows isn't quite stable, so I've disabled testing with mono on AppVeyor for now.

**Comment by Simn** [comment]
I guess we can close again, doesn't seem to occur anymore and even if it happens again, I doubt there's much we can do about it.
