### ISSUE TITLE
Inline new not triggered

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4874]
When working on Heaps I found that some inline new is not correctly performed in the following code:

``` haxe
class Main {
    static function main() {
       new h3d.col.Sphere().inFrustum(new h3d.Matrix());
    }
}
```

The `Sphere.inFrustum` method should be able to eliminate all allocations while it keeps allocating `Plane` instances.

I don't remember if I checked that code for memory allocation before and thus if it's a regression or not, I'ld surely like to know why it doesn't get triggered in that case and make sure that once fixed it doesn't regress :)

**Comment by Simn** [comment]
What target?

**Comment by Simn** [comment]
Oh, this is about the assignments:

```haxe
class Main {
	var i:Int;

	public inline function new(i:Int) {
		this.i = 0;
	}

	static function main() {
		var m = new Main(1);
		m = new Main(2);
	}
}
```

It doesn't inline if we assign to `m` like that. I don't think that ever worked.

**Comment by ncannasse** [comment]
Ah, right, using several var p should work better, thanks.

**Comment by Simn** [comment]
Shouldn't we try to support that though? It likely requires changing some things, but it kind of looks like it "should work".

**Comment by ncannasse** [comment]
Oh, if you could support it without breaking everything that would be nice indeed, but I guess once we're not SSA-restricted anymore it becomes harder :)

**Comment by Simn** [comment]
We just have to make sure that all assignments to the variable can be inlined (or are `null`). The only problem is that we have to keep track of the value per-assignment, not per-variable like we do now.

I'll check how many changes that requires.

**Comment by Simn** [comment]
@basro: Isn't this one of the cases your inline rework should have fixed?

**Comment by basro** [comment]
No, my rework is still limited to a single assignment per variable.

**Comment by Simn** [comment]
I don't see how we could easily support this. Closing for now.
