### ISSUE TITLE
use @:enum extern abstract instead of @:fakeEnum for flash (and other externs)

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4875]
I think we should deprecate `@:fakeEnum` enums in favor of "extern enum abstract" which is a thing now (see #4862), since they better express extern constants and prevent issues like #3621.

So for example instead of:

``` haxe
@:fakeEnum(String) extern enum BlendMode {
    ADD;
    ALPHA;
}
```

we would write

``` haxe
@:native("flash.display.BlendMode")
@:enum extern abstract BlendMode(String) to String {
    var ADD;
    var ALPHA;
}
```

Changing this can potentially break macros that were matching TEnum instead of TAbstract, but I'd say it's for the best.

**Comment by Simn** [comment]
I think I don't want to change this in Haxe 3.

**Comment by fzzr-** [comment]
What are side-effects when allowing `extern abstract` in other cases?
Imo, `extern abstract` is an oxymoron. Abstract in ideal case has no implementation and lives only in compile-time. But `extern` talks about existing native object.

For example what if:
```haxe
@:native("fooBarJs")
extern abstract MyJsExtern(Array<String>) from Array<String> to Array<String>
{
	@:from static /*inline?*/ function fromString(s:String):Array<String>;
	@:to static function toString(o:Array<String>):String;
}
```

**Comment by nadako** [comment]
`extern abstract` merely means that it's implementation class is extern. this turns out to be useful for representing extern constants (like discussed in this issue), or wrapping extern static helpers in a type where it makes sense (for example this lib is a good candidate: http://glmatrix.net/docs/2.2.0/symbols/vec2.html).

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.

**Comment by Shalmu** [comment]
WTF??? Why not provide backward compatibility? 
Updated to 4.2 and now I have to go through 30 files in lib/air3 to change it manually!!!
Guys, think twice before removing features or create some converter, will ya...
I use Haxe to save time, and you turn it into a time waster...
