### ISSUE TITLE
java.vm.Mutex has been broken

### ISSUE THREAD

**Issue by bji** [HaxeFoundation/haxe#4878]
See commit 52e71b94f758bf5e2624af1e1b32e3edf2b93f5d.

It no longer correctly works when acquired multiple times in a row from the same thread.  While I believe that recursive Mutex is a bad idea in general, it is the advertised behavior as described in the Mutex documentation:

"The same thread can acquire several times the same mutex, but must release it as many times it has been acquired."

The referenced change replaces the Mutex implemetation with one that will hang as soon as the Thread that has already acquired the Mutex attempts to acquire it again.

As an aside, this is why you never create a Mutex API that does reference counting on behalf of the locking thread.  It just leads to incorrect and not obvious mis-usages in calling code, and it also is harder to implement and guarantee the implementation on all platforms.  But, the cat's well out of the bag now.

**Comment by Simn** [comment]
@waneck: Please check!

**Comment by bji** [comment]
Dude you are FAST!

**Comment by bjitivo** [comment]
Sigh.  The annoyances of having two github accounts ... anyways, thanks again for the fast response Simn.

**Comment by Simn** [comment]
Oh it's you!

Save you thanks for @waneck for when he fixes the issue, I'm just the clown setting labels and milestones.

**Comment by back2dos** [comment]
Interesting. I've never run into this problem and for me the same binary semaphore can be acquired multiple times. It is true though that as soon as it is released, the one permit it has becomes available for acquisition and it may happen that another thread gets it, and thus mutual exclusion is no longer guaranteed and other things can go wrong too:

```haxe
m.acquire();
//locked
m.acquire();
//still locked - strangely, this works for me
m.release();
//not locked any more! some other thread is probably going to hop in here
//so if we try to m.acquire() now, we might find ourselves blocked by that other thread \o/
m.release();
//and better yet, not we've dissolved that thread's synchronization too: https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html#release()
```

Anyway, using a [`ReentrantLock`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html) should do the trick.

**Comment by back2dos** [comment]
Ok, I can confirm that ReentrantLock solves the issue. I [produced](https://github.com/haxetink/tink_concurrent/blob/master/tests/TestMutex.hx#L34) a [failing test](https://travis-ci.org/haxetink/tink_concurrent/jobs/111813705#L1792) and [it passes](https://travis-ci.org/haxetink/tink_concurrent#L1803) after using ReentrantLock instead.

**Comment by EBatTiVo** [comment]
Repo pointer and change #, please.

**Comment by waneck** [comment]
From the specs, it does seem like `ReentrantLock` is the way to solve it. Can you see if it works on your codebase now?
