### ISSUE TITLE
Compilation server broken

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4882]
I'm now getting the following trace for compilation server, making it recompile the whole project, making compilation server useless:

`Skipping cached module StdTypes(d:\projects\haxe\std\import.hx)`

**Comment by Simn** [comment]
I don't really understand why this is a problem, but I'm glad you fixed it.

**Comment by ncannasse** [comment]
You're creating modules referencing files that doesn't exist, so when the compilation server loads the module, it finds a dependency which file has disappeared, so it will force its recompilation

**Comment by Simn** [comment]
Ah okay, that actually makes sense!
