### ISSUE TITLE
Executing a template passing a class instead of an anonymous structure fails for C++

### ISSUE THREAD

**Issue by JoanBotella** [HaxeFoundation/haxe#4885]
On several [examples](http://haxe.org/manual/std-template.html) I've seen of the [haxe.Template](http://api.haxe.org/haxe/Template.html) class, it receives an [anonymous structure](http://haxe.org/manual/types-anonymous-structure.html) for the `execute` method call. However, I'm trying to and enforce the presence of the structure properties, so I'm using a simple class instead.

Check this piece of code:

```
class Context {

	public var name:String;

	public function new(n:String):Void {
		name = n;
	}

}

class Main {

	static function main():Void {
		var
			raw:String = "My name is ::name::.",
			context:Context = new Context("Joan"),
			template:haxe.Template = new haxe.Template(raw),
			output:String = template.execute(context)
		;
		trace(output);
	}

}
```

I've tested that code for neko, php, python, js, java, swf and cpp. Everyone shows the correct text but cpp, that prints: "My name is null." . I've used the Haxe compiler 3.2.1 for linux x64.

It's possible that something similar happens for other methods, and I think it's a bad thing for the Haxe "cross-platformness". I can go with a workaround by now, but it would be great to know if this would be fixed on future releases of the compiler.

**Comment by ncannasse** [comment]
Seems weird since it should be using Reflect. Any insight @hughsando?

**Comment by Simn** [comment]
> This is only guaranteed to work for anonymous structures. Refer to Type.getInstanceFields for a function supporting class instances.

http://api.haxe.org/v/dev/Reflect.html#hasField

**Comment by JoanBotella** [comment]
The haxe.Template.execute method documentation does not warn that is using Reflect. Having that it already works for almost all targets, I think is interesting to support cpp too. Could the compiler detect if the context is a class or an anonymous structure and behave properly?

**Comment by ncannasse** [comment]
@Simn yes, but why is it using hasField ? it should be using Reflect.field directly no ?

**Comment by Simn** [comment]
Don't ask me, you originally made it like that 10 years ago: https://github.com/HaxeFoundation/haxe/commit/b447431830a9348b10368312e527a1dbb36b8ca2#diff-89da2deefe56c4de2744c49788630bf7R68

**Comment by ncannasse** [comment]
I see, quite an old code indeed. It should indeed use  Reflect.field() != null || Reflect.hasField()

**Comment by Simn** [comment]
Not sure if I ranted about it this year yet, but having this difference between field and hasField is really not a good API... "Give me the value of that field that doesn't exist!"

But yes, changing this is alright.

**Comment by JoanBotella** [comment]
Meanwhile, I've found some workarounds.

Using just a typedef:

```
typedef Context = {
	name:String
}

class Main {

	static function main():Void {
		var
			raw:String = "My name is ::name::.",
			context:Context = {name: "Joan"},
			template:haxe.Template = new haxe.Template(raw),
			output:String = template.execute(context)
		;
		trace(output);
	}

}
```

Or, if the class is required in order to do something with the arguments received, a typedef or anonymous structure inside the class:

```
typedef ContextAnonymousStructure = {
	name:String
}

class Context {

	private var anonymousStructure:ContextAnonymousStructure;

	public function new(n:String):Void {
		anonymousStructure = {
			name: n
		};
	}

	public function getAnonymousStructure():ContextAnonymousStructure {
		return anonymousStructure;
	}

}

class Main {

	static function main():Void {
		var
			raw:String = "My name is ::name::.",
			context:Context = new Context("Joan"),
			template:haxe.Template = new haxe.Template(raw),
			output:String = template.execute(context.getAnonymousStructure())
		;
		trace(output);
	}

}
```

Thanks you all for your awesome work. :)

**Comment by ncannasse** [comment]
@Simn yes I agree, but we don't want to change that for Haxe 3.x
