### ISSUE TITLE
Checking for internet connection API

### ISSUE THREAD

**Issue by smks** [HaxeFoundation/haxe#4893]
I think Haxe should have an operation to check if an internet connection exists. This is important for me as I need to determine whether to show an ad or a different option if the user is offline. My suggestion would be something like this. Polling a website with good up rate. Or something better?

`class InternetConnection
{
	private static inline var ENDPOINT:String = 'http://www.google.com';

	public function new() 
	{
		throw 'Should not be instantiated';
	}
	
	/**
	* Checks to see if the internet is connected
	* by polling google for a response code
	* 
	* Catch error to deal with potential firewalls
	* 
	* @param callback
	* @return
	*/
	#if js
	public static function isAvailable(?callback:Bool->Void):Void
	#else
	public static function isAvailable(?callback:Bool->Void):Bool
	#end
	{
		var isAvailable:Bool = false;
		
		try {
			var http = new Http(ENDPOINT);

			trace("making request to " + ENDPOINT);

			http.onError = function(status) {
				if (callback != null) {
					callback(false);
				}
				isAvailable = false;
				trace(status);
			};

			http.onStatus = function(status) {
				if (callback != null) {
					callback(true);
				}
				isAvailable = true;
				trace(status);
			};

			http.request(false);
			
			#if !js
			return isAvailable;
			#end
		
		} catch (e:Error) {
			return false;
		}
	}
}`

**Comment by Simn** [comment]
I really don't think that's material for our standard library, especially because there's no universal way of doing this. Maybe consider fleshing it out and put it into a haxelib?
