### ISSUE TITLE
Type of multiplication not inferred correctly.

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxe#4896]
```
class Test
{
   public static function createX() : Dynamic
   {
      return { x : 3.5 };
   }

   public static function main()
   {
      var val = createX();
      trace(val.x*val.x);
      trace("asString:" + val.x*val.x);
   }
}
```

The plain trace of val.x*val.x gets stored in an int temp - should be Float I think.  If I remove the explicit "Dynamic" from the createX signature, it works.
It also does not use a temp for the "asString" case and works, which is nice.  But it seems that either both cases should use a temp, or neither - or maybe the string case should and the plain case should not, but not the other way around.

**Comment by Simn** [comment]
This has to do with how when we have `Unknown op Unknown` we use `unify_int` on both operands, which binds the monomorphs, This behavior is very old and I don't think we should change it right now if at all possible. I would prefer to review this for Haxe 4.

Regarding the temp, I seem to be getting temp vars in both cases:

```
	static public main(method) : Void -> Void

	 = function() = {
		var val = Main.createX();
		var _hx_tmp = val.x * val.x;
		haxe.Log.trace(_hx_tmp,{fileName : "Main.hx",lineNumber : 11,className : "Main",methodName : "main"});
		var _hx_tmp1 = "asString:" + val.x * val.x;
		haxe.Log.trace(_hx_tmp1,{fileName : "Main.hx",lineNumber : 12,className : "Main",methodName : "main"});
	}
```

**Comment by Simn** [comment]
I'm trying to check something but our unit tests throw this at me:

```
TestSpecification.cpp
./src/unit/TestSpecification.cpp(6004) : error C2039: '__SetSizeExact' : is not a member of 'hx::Object'
        C:\GitHub\hxcpp\include\hx/Object.h(75) : see declaration of 'hx::Object'
```

**Comment by Simn** [comment]
Never mind, was something wrong on my end.

**Comment by ncannasse** [comment]
@Simn that should not be the case for some time now, it should be using Float instead of Int when using Dynamic

**Comment by Simn** [comment]
For Dynamic yes, but when monomorphs get involved (e.g. from field access on Dynamic) they unify with Int.

**Comment by ncannasse** [comment]
Ah, right.

**Comment by ncannasse** [comment]
And I don't see how we can possibly change that without breaking a LOT of code by making Float priority over Int for such operations.

**Comment by Simn** [comment]
I don't see a solution here that wouldn't break a lot of code.
