### ISSUE TITLE
Overriding functions with Dynamic param

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4900]
``` haxe
class Main extends Test
{
    static function main(){}
    override function test(_, _){}
}

class Test
{
    public function new(){}
    public function test(a:Int, b:Dynamic){}
}
```

Fails with: `Field test overloads parent class with different or incomplete type` (Haxe: b0b16f2)

Compiles fine when changing type of b to non-Dynamic, or specify `(_, b:Dynamic)` in the override

**Comment by Simn** [comment]
That happens because monomorphs are not bound to Dynamic. Not worth fixing in my opinion, it's good practice to type-hint your function arguments and not doing so can lead to other inference issues as well.

**Comment by Gama11** [comment]
Would it help if there were special semantics for `_`? If the programmer says "I don't care about the argument", that includes "I don't care about the argument type", so it seems annoying that you'd have to specify it.

**Comment by Simn** [comment]
Do you mean automatically inferring `_` to be Dynamic?

**Comment by kevinresol** [comment]
btw this is a breaking change because it worked in 3.2.1

**Comment by Gama11** [comment]
Perhaps, yeah? Although that seems potentially dangerous if the compiler doesn't also make sure `_` really is unused.

**Comment by kevinresol** [comment]
Oh man... I thought `_` has a special semantic meaning from the beginning and that explains why I can put two identifiers that are the same. And just found that I am WRONG. I can make a function like `function test(a:Int, a:Dynamic){}` ....

**Comment by Gama11** [comment]
Yeah, that seems like something that can introduce subtle bugs. Maybe it's a good idea to only allow that for `_` and if `_` is unused?

**Comment by Simn** [comment]
@kevinresol: Yes, that comes from fixing #4378 which intentionally allowed Dynamic variance. I'll have to check the regression though.

**Comment by Simn** [comment]
@Gama11: See #4381.

**Comment by kevinresol** [comment]
I am not sure what I expect here, given that `_` actually doesn't has special meaning...

**Comment by Simn** [comment]
I still don't think it's worth fixing this, so I'll go ahead and close it.
