### ISSUE TITLE
private is ignored on enum abstract values

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4904]
It seems like this shouldn't compile:

```haxe
package;

class Main {
	static function main() {
		trace(EnumAbstract.VALUE);
	}
}

@:enum
abstract EnumAbstract(Int) {
	private var VALUE = 0;
}
```

Either private enum abstract values should be disallowed, or the access modifier shouldn't be ignored.

**Comment by Simn** [comment]
The access modifier shouldn't be ignored.

**Comment by nadako** [comment]
IIRC, compiler just replaces modifiers to `static public`
