### ISSUE TITLE
Variables of Class<T>

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#4909]
``` haxe
class C {
    public static function f(i:Int){ trace("f"); }
}

class Test {
    static function main() {
        C.f(1);
        C.g();

        var c = C;
        c.f(1);
        c.g();

        var c:Class<C> = C;
        c.f(1);
        c.g();
    }
}
```

```
Test.hx:8: characters 8-11 : Class<C> has no field g
Test.hx:11: characters 8-11 : Class<C> has no field g
Test.hx:14: characters 8-11 : Class<C> has no field f
Test.hx:15: characters 8-11 : Class<C> has no field g
```

Error about third `c.f` seems strange, since first and second `c.g` is referred to as `Class<C>` also.

**Comment by Simn** [comment]
Yes this is a bit strange. What you get from a plain `C` is not actually the same as `Class<C>`. It used to be printed as `#C` or something but was later changed, which I think made matters worse.

I would like to clean this up properly, but I'm not sure if that's viable for Haxe 3.

**Comment by ncannasse** [comment]
`C` (or `#C`) is the class value, it has static variables. `Class<C>` is the type of a class capable of creating C instances (it could be C or one of its subclasses). It doesn't have any static.

**Comment by Simn** [comment]
If I'm understanding correctly, this is working as intended.
