### ISSUE TITLE
Static methods via typedef vs DCE

### ISSUE THREAD

**Issue by mcheshkov** [HaxeFoundation/haxe#4910]
```haxe
//@:keep
class C {
    public static function f(i:Int){ trace("f","g"); }
}

typedef TD = {
    function f(v:Int):Void;
}

class Test {
    static function main() {
        //C.f(1);
        
        var t:TD = C;
        t.f(1);
        tf(C);
        tfd(C);
	}
    
    static function tf(t:TD){
        t.f(1);
    }
    
    static function tfd(t:Dynamic){
        t.f(1);
    }
}
```

Without keep or explicit call static method is removed by DCE, code compiles fine, but fail at runtime.

**Comment by Simn** [comment]
I have to check this, it might be a special case with how class statics work.

**Comment by Simn** [comment]
Oh, this seems to fail only on some targets.

**Comment by Simn** [comment]
That was dumb of me, the analyzer "fixed" the test by inlining the value, so it became a properly typed `C.f(1)` on most targets.
