### ISSUE TITLE
Crash on Iterator.next if no element exists

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4911]
``` haxe
class Main {
    static function main() {
        var x = new Main();
        x.iterator().next();
    }

    var a:Array<String>;

    public function new() {
        a = [];
    }

    public function iterator() {
        return a.iterator();
    }
}
```

Reduced from `haxe.xml.Fast.get_innerData`. The additional indirection seems to be required to make it crash.

**Comment by ncannasse** [comment]
I'm not sure if it's legit or not to call .next() without checking .hasNext() == true first. I wouldn't like to do twice the bounds check once in hasNext then again in next()

**Comment by ncannasse** [comment]
I'm inclined to classify this as "unspecified", most iterators are used in for loops which guards against this anyway.

**Comment by Simn** [comment]
In that case we have to fix haxe.rtti.XmlParser and haxe.xml.<strike>Slow</strike>Fast. There are several places in there which clearly assume that `next()` returns `null` if no element exists.

**Comment by Simn** [comment]
I fixed Fast in my rewrite and I don't want to touch XmlParser. Let's see if anyone ever comes across this problem.
