### ISSUE TITLE
Unbound variable tmp

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4917]
The minimal code reduced from the utest code base:
```haxe
class Test {
	static function throwing(expected:Dynamic):Bool {
		switch(Type.typeof(expected))
		{
		  case TClass(c):
			Std.string(expected);
			return true;
		  case TEnum(e) :
			Std.string(expected);
			return true;
		  case _ :
			throw "Unable to compare two unknown types";
		}
		throw "Unable to compare values: " + expected;
	}
	static function main():Void {
		throwing("testing");
	}
}
```

Compile to flash:
```
-swf Test.swf
-cp src
-main Test
```

Error:
```
src/Test.hx:14: characters 39-47 : Unbound variable tmp
```

Tested with latest haxe dev branch.
Compilation will success if I add `-D no-analyzer`.

**Comment by Simn** [comment]
That's interesting, it's clearly related to the fact that the code below the switch is unreachable. Probably comes from the syntax edges not being in sync with the CFG edges.

**Comment by Simn** [comment]
It was also related to how local DCE works: Its mark phase only considers CFG edges that are executable to avoid marking variables which are only used from dead code. The sweep phase however walks the dominator tree, which means that it visits every node and thus removed the `var tmp`.

**Comment by andyli** [comment]
Thanks for the quick fix!
I like that every time I filed an issue before dinner, it had already been fixed when I come back : )
