### ISSUE TITLE
Accept ! and ? in method names

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#4922]
I've grown to using ? and ! in method names as a a convention for defining "dangerous" methods and boolean functions respectively in Ruby. Would it be possible to parse this syntax in Haxe?

i.e: `destroy!` and `persisted?`.

**Comment by Simn** [comment]
I don't think we could add this, it gets in the way of `!` unop and `?:` ternary at parser-level.

**Comment by back2dos** [comment]
I suggest using clear naming to communicate difference between commands and queries. The latter should be called `isPersisted` to make clear it's side-effect free.

**Comment by fullofcaffeine** [comment]
@sebthom alright, fair enough. 

@back2dos Yeah, that's the alternative, thanks.
