### ISSUE TITLE
@:genericBuild on typedefs

### ISSUE THREAD

**Issue by fantoine** [HaxeFoundation/haxe#4926]
I would like to be able to dynamically create generic typedefs but it looks like the @:genericBuild is not even considered for typedefs.

My use case is very simple : I want to be able to create a single Callback typedef which would allow any number of generic parameters and convert them to a function prototype.

Something like this:
```haxe
@:genericBuild(CallbackBuilder.build())
typedef Callback<Rest> = /* something */;
```

Would be used like this:
```haxe
var type : Callback<Bool>;
/* becomes */
var type : Bool -> Void;

var type2 : Callback<String, Bool, Whatever>;
/* becomes */
var type2 : String -> Bool -> Whatever -> Void;
```

**Comment by Simn** [comment]
I don't think that makes much sense, why not simply use `class` instead?

**Comment by nadako** [comment]
This is the same as #3640, i guess.

**Comment by fantoine** [comment]
Because a `class` is not callable. :)

**Comment by Simn** [comment]
That doesn't matter, it is replaced by whatever your build macro returns anyway.

**Comment by fantoine** [comment]
@nadako I also saw this issue. The main issue is that I want to keep the 'callable' stuff.

@Simn Do you mean I can change a `ClassType` to a `DefType` in a genericBuild? Do you have some examples of this kind stuff? I never saw this before.

**Comment by Simn** [comment]
`@:genericBuild` macros can return any ComplexType.

**Comment by fantoine** [comment]
Ok sorry, I missed this part on the [documentation](http://haxe.org/manual/macro-generic-build.html). :)

> In Haxe 3.1 the return type of a @:genericBuild macro has to be a haxe.macro.Type. Haxe 3.2 allows (and prefers) returning a haxe.macro.ComplexType instead, which is the syntactic representation of a type. This is easier to work with in many cases because types can simply be referenced by their paths.

**Comment by nadako** [comment]
Even if you return `Type`, still you can return `TType` instead of `TInst` :)

**Comment by fantoine** [comment]
Thx for your help. :)

I successfully implemented it for my [auto function-prototype](https://github.com/ExternKit/extern-js/blob/master/src/js/extern/Callback.hx) and an [auto abstract-EitherType](https://github.com/ExternKit/extern-js/blob/master/src/js/extern/Either.hx).
