### ISSUE TITLE
Bad code generation in C++ with multiple interfaces

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#4927]
```
class Multiple {
	static public function main() {
		test(new A());
	}
	static public function test(a:IA) {
		trace(a.b());
		trace(a.c());
	}
}

class A implements IA {
	public function new() {
	}
	
	public function b():String {
		return 'b';
	}

	public function c():String {
		return 'c';
	}
}

interface IA extends IBB extends IC {
}

interface IBB extends IB {
}

interface IB {
	function b():String;
}

interface IC {
	function c():String;
}
```

```
./src/Multiple.cpp(62): error C2039: 'b': is not a member of 'IA_obj'
include\Multiple.h(8): note: see declaration of 'IA_obj'
```

This generates valid javascript, flash, neko, php, python, java and C#. So it just fails on C++.

This problem is triggered with multiple interfaces and one of them extending another interface. So if I remove IBB, and IA extends directly from IB, it works.

I could circumvent the problem in other circumnstances, but I'm having issues with [jtransc](https://github.com/jtransc/jtransc/) generated code and I cannot modify the source code (it fails with a interface like that in the kotlin runtime).

It fails with 3.2.1 and with latest nightly.

**Comment by Simn** [comment]
> and with latest nightly.

I have to disagree on that account, please make sure you have latest hxcpp as well.

**Comment by soywiz** [comment]
@Simn Ok. You are right. With nightly it doesn't even compile for me and I was mistakenly thought it was for the same reason.

```
> haxe -version
3.3.0 (git build development @ 1afc2c0)
> haxelib update hxcpp
hxcpp is up to date
> haxe -cp . -main Multiple.hx -cpp test.cpp
...
include\A.h(35): error C2039: 'Val': is not a member of 'hx'
C:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include\hx/Boot.h(7): note: see declaration of 'hx'
include\A.h(35): error C3646: '__Field': unknown override specifier
include\A.h(35): error C2059: syntax error: '('
include\A.h(35): error C2238: unexpected token(s) preceding ';'
```

Maybe I'm missing something, but don't know what.

I have tried with haxe 3.1.3 and in that version it works just fine, but I am using haxe.io new stuff from 3.2, so I can't use that version. And can't get nightlys working for me.

There will be a 3.2.2 with fixes but not introducing new features/possible new bugs? That would be great. Last 3.2.x version is from october and I know several bugs that are supposedly fixed, but there is no a 3.2.2 version yet.

**Comment by Simn** [comment]
You need to use the *git* version of hxcpp if you use the git version of Haxe.

**Comment by soywiz** [comment]
That was dumb for me. Got the example working using git hxcpp.

Now my big project doesn't complete the compilation phase, git haxe compiler probably got stuck in an infinite loop (100% cpu and memory growing slowly). But that's not related with c++ target anymore.

So sorry for the inconveniente, and thanks for your hints and your patience.

**Comment by Simn** [comment]
No problem!

I'm very interested in the compiler hang. Let me know if you figure out where it comes from.

**Comment by soywiz** [comment]
Not sure if it is a hang or just take ages to complete.

The generated haxe codebase I'm compiling includes 1864 files and it is 22MB in size.

I have noticed that 3.3 enabled a static analyzer. So I have performed some tests with `--times`.

Disabling static-analyzer with `-D no-analyzer` seems to complete in less than a minute (without compiling c++)

```
Total time : 41.891s
------------------------------------
  analyzer-cleanup : 0.051s, 0%
  analyzer-filter-apply : 0.069s, 0%
  analyzer-from-texpr : 0.371s, 1%
  analyzer-fusion : 0.290s, 1%
  analyzer-to-texpr : 0.113s, 0%
  filters : 11.584s, 28%
  generate cpp : 16.876s, 40%
  haxelib : 0.031s, 0%
  macro execution : 0.314s, 1%
  other : 0.308s, 1%
  parsing : 4.059s, 10%
  typing : 7.825s, 19%
```

Without disabling it, it still on it. 15min and counting. **Updated:** 30 min and counting.

![haxe_long_running](https://cloud.githubusercontent.com/assets/570848/13675589/9a0189ca-e6e2-11e5-97c9-923bfcc7feda.png)

The generated cod i'm trying to compile is pretty degenerated right now. Has tons of locals and a huge switch simulating jumps.

![degenerated_functions](https://cloud.githubusercontent.com/assets/570848/13675704/2125c18c-e6e3-11e5-81af-e7fcdb965cbf.png)

Not sure exactly which optimizations are done, but constant propagation, and register allocation probably would have some hard times with it. Even some highly optimized javascript engines are having some noticeable pauses when compiling and trying to optimize the javascript generated code for this.

In the end I will generate better code that will have already some optimizations on it.

But anyway > 30 minutes seems pretty excessive. Probably there is something wrong.

I will try (and remove one line each test):
--times
`-D analyzer-no-const_propagation`
`-D analyzer-no-copy_propagation`
`-D analyzer-no-local_dce`
`-D analyzer-no-fusion`
`-D analyzer-no-purity_inference`
`-D analyzer-no-unreachable_code` 

This is how it is supposed to work, right?

Is there anything else I can do to track this down?

**Comment by Simn** [comment]
> This is how it is supposed to work, right?

Yes, you got it. 

> Is there anything else I can do to track this down?

I can't think of anything right now. Given the amount of local variables it's probably the SSA transformation that takes so long. It can't be disabled separately because it's a dependency of the optimizations. If you disable all of the optimizations and it's still slow, it has to be that.

**Comment by soywiz** [comment]
Updated: I have tried disabling modules as noticed here: http://haxe.org/manual/cr-static-analyzer.html

I have added all these defines:
```
-D analyzer-no-const_propagation
-D analyzer-no-copy_propagation
-D analyzer-no-local_dce
-D analyzer-no-fusion
-D analyzer-no-purity_inference
-D analyzer-no-unreachable_code
```

And it hangs/or takes too much time too. So probably it's the SSA as you indicated.

**Comment by Simn** [comment]
Yeah, hmm, I'll have to check that somehow. I don't think it's realistic to assume it's just slow, it probably enters some infinite tail recursion somewhere.

Do you know how to compile Haxe? You could add a debug output `print_endline ((s_type_path c.cl_path) ^ "." ^ cf.cf_name);` at the start of `run_on_field` in analyzer.ml. This should tell you which field it dies on.

**Comment by soywiz** [comment]
I will try to do that.

(I have tried with a public example, but it seems that it is smaller and doesn't have that problem)

**Comment by Simn** [comment]
That function does indeed look fairly ugly, but that's still no reason not to terminate.

Do you get a stacktrace if you break the compilation with OCAMLRUNPARAM=b defined as an env var?

**Comment by Simn** [comment]
Can you paste the part that isn't list.ml, if that exists?

Regarding the other error, that might be related to the leading double underscore in some way. Does that happen without leading underscores too?

**Comment by soywiz** [comment]
No other entry than `list.ml` :(

<img width="795" alt="captura de pantalla 2016-03-10 a las 19 16 10" src="https://cloud.githubusercontent.com/assets/570848/13679550/994d2996-e6f4-11e5-8052-1dfbfc2d9198.png">

I will check the double underscore. It used to work, so I used __, but I can change that.

**Comment by Simn** [comment]
Damn, that's not good. I don't really know how to debug this further right now.

You could try commenting out parts of the `Ssa` module, e.g. the call to `insert_phi` and `rename_in_block`. Another suspect is `update_reaching_def` I suppose. Commenting these is gonna generate nonsense, but at least we can maybe narrow down why it doesn't terminate.

Sorry for this ghetto-debugging, it's not so easy to track down infinite tail-recursions.

**Comment by soywiz** [comment]
Ok. Then I will try first to reduce the problem to something I can send you. In the case I don't have success, I will try the commenting part. I know a little about SSA and PHIs, but my knowledge about ocaml = 0 and I can't hardly understand it right now :(

**Comment by soywiz** [comment]
I was able to reproduce it in a single file. 
```
^CFatal error: exception Sys.Break
Raised at file "sys.ml", line 87, characters 52-57
Called from file "list.ml", line 55, characters 20-23
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "list.ml", line 55, characters 32-39
Called from file "analyzer.ml", line 1854, characters 12-54
Called from file "analyzer.ml", line 1870, characters 23-42
Called from file "analyzer.ml", line 1878, characters 4-28
Called from file "analyzer.ml", line 1945, characters 10-33
Called from file "analyzer.ml", line 1954, characters 2-9
Called from file "analyzer.ml", line 2855, characters 10-13
Called from file "analyzer.ml", line 2882, characters 35-111
Called from file "analyzer.ml", line 2891, characters 15-52
Called from file "list.ml", line 73, characters 12-15
Called from file "analyzer.ml", line 2915, characters 2-53
Called from file "list.ml", line 73, characters 12-15
Called from file "filters.ml", line 1044, characters 31-71
Called from file "main.ml", line 1531, characters 2-27
Called from file "main.ml", line 639, characters 3-11
Called from file "main.ml", line 1766, characters 1-35
``` 

Adding stuff like this makes it slower and slower.
Just with about 100 lines like this it takes several seconds to complete. The whole 2100 lines takes almost forever.

```
class MyTest {
	static public function main() {
		trace(internalClassNameToName('test'));
	}

	static public function internalClassNameToName(internalClassName:String):String {
		var cn = internalClassName;
		switch (cn.length) {
			case 12:
				if (cn == "JTranscLime_") return "JTranscLime";
				if (cn == "jtransc.Mem_") return "jtransc.Mem";
				if (cn == "kotlin.Lazy_") return "kotlin.Lazy";
				if (cn == "kotlin.Pair_") return "kotlin.Pair";
				if (cn == "kotlin.Unit_") return "kotlin.Unit";
			case 13:
				if (cn == "nova.ds.DsKt_") return "nova.ds.DsKt";
				if (cn == "nova.io.IoKt_") return "nova.io.IoKt";
				if (cn == "nova.vfs.Vfs_") return "nova.vfs.Vfs";
						case 14:
				if (cn == "JTranscLime_1_") return "JTranscLime$1";
				if (cn == "java_.io.File_") return "java.io.File";
				if (cn == "java_.net.URI_") return "java.net.URI";
				if (cn == "java_.net.URL_") return "java.net.URL";
				if (cn == "kotlin.LazyKt_") return "kotlin.LazyKt";
				if (cn == "kotlin.Triple_") return "kotlin.Triple";
				if (cn == "nova.ds.Queue_") return "nova.ds.Queue";
				if (cn == "nova.io.RawIo_") return "nova.io.RawIo";
				if (cn == "nova.vfs.Path_") return "nova.vfs.Path";
```

Here is a PHP code to reproduce the problem:

```
<?php

$totalItems = 2000; // YOU CAN CHANGE THIS VALUE. 200 takes a few seconds. 2000 A LOT.

function generate_random_string($len) {
	$n = 0;
	$out = '';
	for ($n = 0; $n < $len; $n++) $out .= chr(mt_rand(ord('a'), ord('z')));
	return $out;
}

mt_srand(0);
$out = [];
for ($n = 0; $n < $totalItems; $n++) {
	$str = generate_random_string(mt_rand(12, 121));	
	$out[strlen($str)][] = $str;
}

asort($out);

ob_start();
echo "class Bug {\n";
echo "  static public function main() { get(''); }";
echo "  static public function get(a:String):Bool {\n";
echo "    switch (a.length) {\n";
foreach ($out as $len => $items) {
	echo "      case $len:\n";
	foreach ($items as $item) {
		echo "if (a == \"$item\") return true;\n";
	}
}
echo "    }\n";
echo "    return false;\n";
echo "  }\n";
echo "}\n";
file_put_contents('Bug.hx', ob_get_clean());
```

And the command line:
```php reproducebug.php && OCAMLRUNPARAM=b haxe -cp . -main Bug -js out.js```

**Comment by soywiz** [comment]
Even commenting the switch part, just a lot of ifs, takes forever.

**Comment by Simn** [comment]
Thanks! I'll check it out.

**Comment by Simn** [comment]
I have fixed one huge slowdown for this, please try again now.

The 2000 item version still spends 7 seconds in SSA/const propagation which is way too much. Gonna have to investigate this a bit more.

**Comment by Simn** [comment]
I think I got it now, please test with latest Haxe and let me know how it goes!

**Comment by soywiz** [comment]
Cool :)

I have already tested. Now it is really fast. Not just the example, but the huge program compilation. Great work. 

---

Regarding to the bad code generation (within the catch), it was indeed caused by the varable starting with `__`. I have changed it to start by `J__` and it now compiles (it crashes at runtime, but I have to investigate more and it's probably a problem in other place, not haxe itself).

In my case I could have fields starting by `__` at java or kotlin code. So I should probably change more stuff to encircle the problem, replacing variable or field names starting by __ (depending on the resolution of this issue).

At any rate, if it is going to generate bad code it should fail at the haxe parsing stage (saying for example that variables can't start by __), or not failing at all (handling that at the c++ gen). So I think I should open another issue with that part.

---

Also I have find that now it fails at as3 generation with a "Constant expression expected" that used to work (and should because that should be a constant) `switch (...) { case flash.events.TouchEvent.TOUCH_BEGIN: ... }`. So I will file another bug with that.

---

I have another question, regarding to analyzer:

```
var r0 = null;
r0 = this;
r0._init__Ljava_lang_String_I_V(p0,0);
return;
```

The analyzer should have transformed that into something like this?:

```
this._init__Ljava_lang_String_I_V(p0,0);
```

With a SSA form, that should be trivial.

I am not sure, it is disabled by default and I have to enable it?

**Comment by Simn** [comment]
1. Regarding the leading double underscore: @hughsando, what's the official status here? Should we give an error for this?

2. Constant expression expected: That's a known issue which we'll have to address for 3.3, see #4680.

3. Constant propagation: I think the problem there is that `this` is not propagated. I had some problem with promoting it into a closure or something, I don't remember right now. I might have another look at this.

**Comment by soywiz** [comment]
Ok. I'm not opening more issues then. I will wait about the decission about `__` before replacing field names, at my side.

Regarding to analyzer, that's not a big deal, just curiosity. But having those optimizations at the haxe side would allow me to focus just on CFG stuff at my side (I planned to use a SSA to do some optimizations). If it is just the `this` part, I can replace that r0 with this everywhere and that's it (in fact that works as a constant that variable never mutates). And I don't have closures, so no problem.
I will try to see if all the rest is optimized.
Tail empty `return;` could be optimized too. But I can do that easily at my side.

--

The only problem I will have with CFG generating haxe is that haxe doesn't allow labelled continues or breaks, even when that still produces a reducible CFG, and supported by most languages. So in the case I will need to break two loops I will need a temp variable and jump twice.

So for generating:
```outside: while (true) { while (true) { break outside; } }```

I will have to do something like (a simplification):
```var breakTwice = false; while (true) { while (true) { breakTwice = true; break; } if (breakTwice) break; }```

java, as3 (and AVM2 have goto) and js have labelled statements as far as i know. PHP have break 2; and now even goto. C# and C++ have goto too.
I think python is the only target that doesn't have labelled breaks that could be simulated the same way.

I never asked for it, but that would be great so I can generarate optimal code for reductible CFGs. Or maybe there is another way I don't know to break two loops in haxe without labels that generates optimal code.

**Comment by hughsando** [comment]
Hxcpp now renames all variables that start with "__", but this should not be detectable from "normal" code - ie, if you do not make assumptions about what is generated.  So it is a bug, and is probably to do with the location of the variable - inside a "catch" in this case - where it is not handled everywhere.

I have actually just been refactoring a while bunch of code, so this may already be fixed.  You can compile with "-D cppast" to test this.

As for break 2, you could use an exception, but I would expect performance to be pretty bad.

**Comment by soywiz** [comment]
@hughsando 

This reproduces the bug:
```
./src/Bug.cpp(46): error C2065: '_hx___1': undeclared identifier
```

```
class Bug {
	static public function main() {
		try {
			trace('a');
		} catch (__1:Dynamic) {
			throw __1;
		}
	}
}
```

And indeed `-D cppast` fixes the problem (at least for that minimal example).

Should I start using that define? Or it is just temporal?

--

I will use the post-condition to be able to do multiple continues and breaks instead of exceptions. Since I'm converting from generated code from a compiler, probably there will be lots of strange stuff, specially from the kotlin generated code. But probably even when that extra ifs, it will have better performance than the dumb while + switch first approach.
