### ISSUE TITLE
Error on regex escape

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/haxe#4930]
The compiler doesn't appear to care for escaping sequences:

        var cidr = new EReg("^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})(\\/|/|-)([0-9]{1,2})$", "i");

        trace(cidr.match("192.168.1.0/24"));

[Which throws](http://try.haxe.org/#3bAC3) the following:

    Test.hx:3: character 28 : Invalid escape sequence

But this is a perfectly valid regex in JS and this alternate sequence [works](http://try.haxe.org/#732AC): `([0-9]{1,3}p[0-9]{1,3}p[0-9]{1,3}p[0-9]{1,3})(\\/|/|-)([0-9]{1,2})$`

Is this a bug or am I missing some cross-platform regex parsing issue?

**Comment by yar3333** [comment]
`\.` - not possible in Haxe string literals. Just use `\\.`.

**Comment by Simn** [comment]
What he said.

**Comment by indolering** [comment]
>\. - not possible in Haxe string literals. Just use \\.

Is this documented somewhere?  I checked the current and past documentation and didn't see anything.

**Comment by indolering** [comment]
I'm getting the same error when I try to match `trace(cidr.match("192.168.1.0\/24"));`, but that's a string and I'm not attempting any interpolation.

**Comment by yar3333** [comment]
Use `\/` => '\\/'. I think, C/C++ escape sequences are possible. See http://en.cppreference.com/w/cpp/language/escape

**Comment by yar3333** [comment]
In some languages (like php) unknow sequences like "\s" treated as is. Haxe is more strict to protect you from mistake.

**Comment by indolering** [comment]
> In some languages (like php) unknow sequences like "\s" treated as is. Haxe is more strict to protect you from mistake.

Perhaps you could expand in [this documentation ticket](https://github.com/HaxeFoundation/HaxeManual/issues/244)?

**Comment by yar3333** [comment]
If you want regular expression, just use regular expression syntax!
```haxe
var cidr = ~/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})(\\/|/|-)([0-9]{1,2})$/i;
```

**Comment by indolering** [comment]
> If you want regular expression, just use regular expression syntax!

Haxe doesn't like my `/` matcher in the second group.

Also,  `trace(cidr.match("192.168.1.0\\/24"))` doesn't appear to get translated into `"192.168.1.0\/24"` on the JS target.

**Comment by yar3333** [comment]
It is a very complex problem - to escape a `/` char in your regex. I don't know, who can help you. It must be very clever man! :)

**Comment by ncannasse** [comment]
You need to look things from a different angle to solve this kind of problem

**Comment by indolering** [comment]
@yar3333 @ncannasse, could I get your input on documenting the issue in [this other ticket](https://github.com/HaxeFoundation/HaxeManual/issues/244)?  I'm pretty lost here.
