### ISSUE TITLE
Http.requestUrl fails with "Invalid chunk"

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4933]
When trying to use Docker to launch a haxelib server for testing on Ubuntu, the integration test failed with  error:
```
ERR: exception thrown : Invalid chunk

Called from /usr/lib/haxe/std/haxe/Http.hx line 782
Called from /usr/lib/haxe/std/haxe/Http.hx line 345
Called from /usr/lib/haxe/std/haxe/Http.hx line 530
Called from /usr/lib/haxe/std/haxe/Http.hx line 347
Called from /usr/lib/haxe/std/haxe/Http.hx line 784
Called from tests/integration/TestEmpty.hx line 68
Called from IntegrationTests.hx line 77
Called from tests/integration/TestEmpty.hx line 68
Called from a C function
Called from /usr/lib/haxe/std/haxe/unit/TestRunner.hx line 115
```

The only failing page is "documentation/using-haxelib". All other pages can be fetched correctly...
Firefox doesn't show any error for that page, so I suspect it is a bug in `Http.requestUrl` instead of the server.

I cannot reproduce the problem on a Mac. I will investigate further and post new info here.

**Comment by ncannasse** [comment]
Anyone willing to look at the darkness of chunked http transfer and why our implementation fails in some rare cases?

**Comment by Simn** [comment]
Is this the same as #4950 (request vs. requestUrl)?

**Comment by ncannasse** [comment]
Most likely, closing as duplicate
