### ISSUE TITLE
[Java] Failing tests in Reflect.unit

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#4934]
I enabled the Reflect.unit test for PHP and I also enabled some of the tests in there, that are commented out for some reason. These two seem to fail on Java, but seem two work on all other targets:
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/Reflect.unit.hx#L40
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/Reflect.unit.hx#L41h
They throw a NullPointerException or something like this...

**Comment by Simn** [comment]
Actually this is covered by the documentation on Reflect.getProperty: `If o or field are null, the result is unspecified.`.

**Comment by mockey** [comment]
@Simn: Maybe remove the tests then?

**Comment by ncannasse** [comment]
@Simn I would like this to be fixed, since it's inconsistent with Reflect.field which allows not-object or null in its documentation.

**Comment by ncannasse** [comment]
Reflect.getProperty should be a drop'in replacement for Reflect.field + property support (as setProperty/setField) so they should share the same specification.

**Comment by Simn** [comment]
Hmm, I wasn't aware that Reflect.field works with null. In that case I agree Reflect.getProperty should work as well, although consistency is not a very strong argument when it comes to Reflect (e.g. setField doesn't work with null).

**Comment by nadako** [comment]
I really don't like that we have to support null for `Reflect.field`. Because of that we have a try/catch JS implementation. Could we lose that specification and be consistent with `Relfect.setField`? :)

**Comment by Simn** [comment]
Actually yeah, in the big picture it's not Reflect.getProperty that's inconsistent but rather Reflect.field because it might be the only function in the standard library that checks for null like that.

With that knowledge I vote for not doing anything right now and address Reflect.field in Haxe 4.

**Comment by ncannasse** [comment]
Reflect.fields is highly used in Dynamic code, hence its specific gracefully-failing spec. I would not change its specification even in Haxe 4, so let's align getProperty
