### ISSUE TITLE
Json.stringify has an infinite recursion error while stringifying a class in neko

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#4935]
Note, @ncannasse [asked me](https://github.com/HaxeFoundation/neko/issues/115) to file the issue here and perhaps create a unit test PR, but I don't know how the unit test framework works. It seems (reading the [README](https://github.com/HaxeFoundation/haxe/blob/development/tests/README.md)) that maybe I just drop the test into [this directory](https://github.com/HaxeFoundation/haxe/tree/development/tests/unit/src/unit/issues)? And on the development branch? If someone can confirm the details, I'd be happy to submit unit tests / PR's going forward.

-----------

Json.stringify has an infinite recursion error while stringifying a class in neko. CPP doesn't have this problem.

Testcase:

```
class Main {
  public static function main() {
    trace(Main);
    trace(haxe.Json.stringify(Main));
  }
}
```

CPP output:
```
Main.hx:3: Main
Main.hx:4: {}
```

node JS output:
```
{ [Function] main: [Function] }
undefined
```

Neko output:
```
Main.hx:3: { __name__ => [Main], main => #function:0, prototype => { __class__ => ..., __serialize => #function:0 } }
Called from ? line 4
Called from Main.hx line 4
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 44
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 83
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 180
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 126
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 180
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 83
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 180
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 126
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 180
Called from /home/jward/tools/haxe/std/haxe/format/JsonPrinter.hx line 83
...
```

**Comment by nadako** [comment]
Ehm, isn't that unspecified?

Class is not really a json-serializable value and moreso, its structure target-dependent, so why you even do that? :)

I'm guessing that for fixing this we'd have to add some kind of cache to check for circular references which will slow down the whole process.

**Comment by nadako** [comment]
I wonder tho, what's the current behavour for serializing e.g. `var a = {f: null}; a.f = a; Json.stringify(a);`.

**Comment by Simn** [comment]
Isn't this what the replacer function is for?

Which by the way needs a slight documentation adjustment, it sounds a bit Russian right now.

**Comment by nadako** [comment]
Actually, @Simn is right. Maybe we need to document the unspecified behaviour regarding circular references and point user to use `replacer` to avoid this.

As for the documentation, yeah, I missed some words, lol :) Feel free to change it (but don't forget that it's also described in `haxe.format.JsonPrinter`).

**Comment by jcward** [comment]
Perhaps it's asking too much, but I could hope that "unspecified" means "unspecified Json output" and not "might crash the neko VM."

**Comment by nadako** [comment]
That's fair to ask, but I wouldn't add circular ref check to `JsonPrinter` just for that. Maybe someone with Neko knowledge could think of something?

**Comment by Simn** [comment]
I can't see how that would work given that you recurse infinitely.

**Comment by jcward** [comment]
BTW, the above shouldn't be a circular reference problem. Any class, even `Class Foo {}` crashes it.

**Comment by nadako** [comment]
I'm pretty sure it is. Looks like neko class objects reference themselves.

**Comment by jcward** [comment]
> Looks like neko class objects reference themselves.

Ah, interesting. So maybe the problem is back in Neko, but it's then unlikely to be an easy fix.

**Comment by Simn** [comment]
I kind of wish our Class behavior wasn't so loosely specified. The syntax makes it really easy to use, but there are all sorts of traps involved. Maybe we can think about that for Haxe 4.

**Comment by jcward** [comment]
Interesting, `trace(Foo)` in CPP is `Foo` while in neko is outputs:

```
{ __name__ => [Foo], prototype => { __class__ => ..., __serialize => #function:0 } }
```

So we see the prototype has a __class__ which is the circular reference. Both agree that `Type.typeof(Foo)` is `TObject` (not `TClass`? The JsonPrinter handles TClass...)  Or perhaps those fields shouldn't be enumerable?

Anyway, the replacer might check something like this:

```
#if neko
    if (Reflect.hasField(v, "prototype") && Reflect.hasField(v, "__name__") return null;
#end
```
