### ISSUE TITLE
cache loaded functions in haxe.macro.* methods

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4936]
Currently, all methods in `haxe.macro.Context/Compiler/Tools` look like this:

``` haxe
public static function follow( t : Type, ?once : Bool ) : Type {
    return load("follow", 2)(t,once);
}
```

Which mean they will `load` an interp function each time they are called. That seem like a silly overhead which is slowing down compilation and, more importantly, completion when macros are used a lot.

Personally, I tested it with my macro-heavy codebase and it saved about 0.6 sec per compilation which may not seem like much, but it's still good. However if we talk about completion, IMO this is a huge speedup.

I think we should cache `load`ed functions in static vars, like it's done in neko/hxcpp CFFI-based classes. I'm not sure whether we should make it lazy or not. (e.g. `if (_follow == null) _follow = load("follow",2); _follow(t, once);`), it seems reasonable to me to load all macro functions once and make them available without loading or even `==null` branching.

@ncannasse what do you think?

**Comment by back2dos** [comment]
What about building a cache right into neko.Lib.load? Does that still give
you the same speedup?

**Comment by ncannasse** [comment]
@nadako with completion + macros, you should use compilation server which will cache you macro context, so most likely you will not have to call any macros.
If you still want to optimize the Context methods I'm fine with it, maybe try @back2dos suggestion first to see if that does improve things already

**Comment by Simn** [comment]
Not sure if this is still relevant. I think @frabbit looked into improving this (or something similar) a while back and didn't notice any performance improvements.
