### ISSUE TITLE
Remoting proxy building vs already loaded types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4937]
The following gives error: `Main.hx:3: characters 0-50 : Type name Result is redefined from module Api`

Api.hx

``` haxe
interface Api {
    function getResult():Result;
}

typedef Result = {
    var id:Int;
    var name:String;
}
```

Main.hx

``` haxe
import Api; // load types by import

// proxy builder seems to try typing the module again and failing
class ApiProxy extends haxe.remoting.Proxy<Api> {}

class Main {
    static function main() {}
}
```

**Comment by nadako** [comment]
I wonder how this issue could remain unnoticed... Is this a known limitation of some kind or am I doing it wrong?

**Comment by nadako** [comment]
I looked a bit into it and the problem is that it copies all declarations from given module to the new one where proxy is created, while it should just import it instead...

**Comment by Simn** [comment]
haxe.remoting will be moved out of the standard library and implemented without the special compiler support, so this issue is gonna be obsolete.
