### ISSUE TITLE
wrong JS code is generated for this AST

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#4939]
the following AST generates wrong JS code:

``` haxe
            [If:Void]
                [Parenthesis:Bool]
                    [Unop:Bool]
                        !
                        Prefix
                        [Meta:Bool]
                            :pure
                            [Binop:Bool]
                                [Field:phonegap.PlatformName]
                                    [TypeExpr device:Class<phonegap.Device>]
                                    [FStatic:phonegap.PlatformName]
                                        device
                                        platform
                                ==
                                [Cast:phonegap.PlatformName] [Const:String] "browser"
                [Then:Void]...

generates
if (!device.platform == "browser")

which should be 
if (! (device.platform == "browser") )
```

I couldn't find a small example to reproduce this, but it happens regularly in a bigger project when compiled with the Compilation Server. without the server this AST is not generated and therefore not the wrong code.

**Comment by Simn** [comment]
That probably means that the expression in question does not go through `Optimizer.sanitize`. I still don't quite know at which point that filter should run. It strikes me as something that should be at the very end of our post-processing, just before we pass the AST to the generators.

**Comment by nadako** [comment]
It's really weird that parenthesis are part of typed AST instead of something handled by the generator...

**Comment by Simn** [comment]
> It's really weird that parenthesis are part of typed AST instead of something handled by the generator...

I'm undecided on that aspect. On the one hand I agree that it's weird, on the other it's also very pragmatic and avoids a lot of duplicate work in the generators.

**Comment by nadako** [comment]
I don't know, It feels like because of TParenthesis and confusion around it, we get so much parens in the output on some targets (e.g. c#, python) that they almost look like LISP.

**Comment by nadako** [comment]
Also because of genjs relies on TParenthesis I once got `ifsomevar > 0 {...}` generated on JS which is totally invalid syntax :)

**Comment by AdrianV** [comment]
Sorry can't find a reduced example. As soon as I comment something out, the problem doesn't show up

**Comment by ncannasse** [comment]
Sanitize should indeed be run at the end of compilation, just before generator, in order to avoid unsanitized AST. Maybe the TMeta here is at fault?

**Comment by Simn** [comment]
You're right, it's probably the TMeta:

```ocaml
	| TUnop (op,mode,e1) ->
		let rec loop ee =
			match ee.eexpr with
			| TBinop _ | TIf _ | TUnop _ -> parent e1
			| TCast (e,None) -> loop e
			| _ -> e1
		in
		{ e with eexpr = TUnop (op,mode,loop e1)}
```

This `loop` seems to eat the `TCast` which might not be a good idea either.

**Comment by Simn** [comment]
The code in question now checks for TMeta as well, so this is probably resolved.
