### ISSUE TITLE
[python] genpy refactoring

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4941]
I love the approach @hughsando has taken with the CPPAST, and I think this is a great way for generating languages whose syntax is very different from Haxe, like Python.

I toyed with this idea a bit this night, and found out that Python sources contain this [Python.asdl](https://github.com/nadako/python-ast/blob/master/asdl/Python.asdl) file that contains definitions of ADTs and structures used to represent the language.

So I generated some haxe data types from that: https://github.com/nadako/python-ast/blob/master/src/Python.hx and it looks very sensible to me. It's pretty easy to write a printer for that, and port this to OCaml.

I wonder how hard would it be to refactor `genpy.ml` to generate PyAST instead of directly printing stuff, but I think we should do it to ease the pain of maintaining this target in the long term.

cc @frabbit @Simn

**Comment by hughsando** [comment]
It has been very satisfying doing the rewrite - actually tracking the types
the cpp uses means I can easily see what type conversions are going on.  5
years overdue maybe.
I have also added a define "annotate_source" which sticks extra comments in
the generated code. These can then be compared to "-D dump" and this has
also been very handy and I would recommend it for and source-code output.

**Comment by Simn** [comment]
I like the idea, but let's be honest: It's not gonna happen unless somebody goes into full pet project mode.
