### ISSUE TITLE
Features page vs HaxeDevelop for Ctrl+Shift+R

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFoundation/haxe#4944]
Trying HaxeDevelop the first time as a FlashDevelop user.

http://haxedevelop.org/features.html says:

> 
> Become a fast coder; learn the shortcuts
> 
> Ctrl+Shift+R : Open a resource in the current project.

So I go to try this with my Main.hx open within my current project which is open, and I get a dialog:

> ---------------------------
>  Confirm
> ---------------------------
> Are you sure you want to reload the file? All changes get lost.
> ---------------------------
> Yes   No   
> ---------------------------

Um...what?

**Comment by Simn** [comment]
This is the wrong repository, but I'm not actually sure what the right repository is so I'll keep it open for now.

@markknol

**Comment by Simn** [comment]
Ah it's https://github.com/markknol/haxedevelop.org.

@markknol: Are we gonna transfer that to HaxeFoundation github?

**Comment by markknol** [comment]
I [fixed the issue](https://github.com/HaxeFoundation/haxedevelop.org/commit/1dfa6b0d2e482d0a899c47690e6a812f8e46eec7); I accidentally used the incorrect keyboard shortcut. It should be `CTRL+R` by default. Btw if you wish can manage/change your [keyboard shortcuts](http://haxedevelop.org/keyboard-shortcuts.html). :smile: 

More issues about the haxedevelop.org website can be reported here 
https://github.com/HaxeFoundation/haxedevelop.org/issues

Happy coding!

**Comment by GimmickyApps** [comment]
Thanks for your quick responses, that indeed is a handy shortcut, and this will make for a much better 'first impression' quotient.  :)
