### ISSUE TITLE
#if conditional compile errors (inconsistent behavior across targets)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#4945]
I can never quite recall the conditional compile syntax, and I'm so used to the compiler catching all my mistakes that when it doesn't, I'm very confused.

Is there any reason the following syntaxes (which are potentially common typos) should be allowed?

```
    // case 1: missing () around expression:
    #if cpp || neko
        trace("Is cpp or neko!");
    #else
        trace("Is neither cpp nor neko!");
    #end

    // case 2: errant elsif
    #if cpp
        trace("Is cpp!");
    #elsif neko
        trace("Is neko!");
    #else
        trace("Is neither cpp nor neko!");
    #end
```

The above successfully compiles to neko, js, and SWF (I didn't test other targets). Because of the typos, the neko output is:

```
    Main.hx:13: Is neither cpp nor neko!
    Main.hx:22: Is neither cpp nor neko!
```

The inconsistency is, if I try to compile the above to CPP, it does throw the compiler errors I'd hope for:

case 1:

```
    Main.hx:9: characters 8-10 : Unexpected ||
```

case 2:

```
    Main.hx:14: characters 4-10 : Unexpected #elsif
```

Why is this bad syntax allowed when targetting neko / js / swf, but not cpp?

**Comment by Simn** [comment]
Because this is `(#if cpp) || neko` which means it adds `|| neko` to your syntax if you are on cpp. We shouldn't change that because otherwise you couldn't do something like `if (cond #if neko || otherCond #end) { }` anymore.

**Comment by jcward** [comment]
Wow, that's a clever example, but I'll take this moment to express concern over Haxe's general bias toward supporting complex and contrived syntax, as opposed to safety for the new adopter.

Funny, that type safety is such a lauded goal, and syntax safety is not.

Aw well, Juraj would approve. ;)

**Comment by ncannasse** [comment]
@jcward I can understand how that can cause trouble, but we don't have much of a solution there. Either we require parenthesis, so users will have to write `#if (cpp) || otherCond` when they want such thing, or we could warn if otherCond is an actual define (either actual or potential), but that's also a bit random.

**Comment by ncannasse** [comment]
And yes we could forbid unsupported pragmas such as #elsif , when skipping them in parser.

**Comment by Simn** [comment]
I glossed over the second part, but yes I agree we can detect that.

**Comment by jcward** [comment]
>we could forbid unsupported pragmas such as #elsif , when skipping them in parser.

I think that would be helpful. Thanks, guys.

**Comment by jcward** [comment]
Just pondering: I think the [AS3 conditional compilation](http://help.adobe.com/en_US/flex/using/WS2db454920e96a9e51e63e3d11c0bf69084-7abd.html) system is excellent:

    // Conditional blocks
    CONFIG::DEBUG {
      trace("Conditional");
    }

    // Typed constant values (constnat values can include quotes or not)
    var port:int = SERVER::PORT;
    var host:String = SERVER::HOST;

    // As a constant part of a runtime expression
    if (localVar && !CONFIG::DEBUG) {
    }

To be honest, I don't know if I've ever tried logical combinations or expressions: `(CONFIG::DEBUG && SERVER::PORT<1024) { ... }`. But the primary things one initially wants to do are easy & obvious.

I suppose I can always slap a pre-parser in front of my Haxe build.

**Comment by jcward** [comment]
FYI, posted a gist for the [typed compile-time constants](https://gist.github.com/jcward/4669dd9f1e79948d6a5e) Simn and nadako helped me figure out.

**Comment by farteryhr** [comment]
always remembered parentheses as required, until i see this.....
it's consistent with normal `if`s and unambiguous, why not?
