### ISSUE TITLE
NPM distribution / hosting

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/haxe#4946]
@damoebius and I have been working on two Haxe NPM package.
Current version (published as `haxe`) : https://github.com/damoebius/haxe-npm
Next / dev version (published as `haxe@next`) : https://github.com/clemos/npm-haxe

We both think it would be a good idea to host the repo for this package in HaxeFoundation's organization, and maybe publish it on NPM under an official HF organization account.
I think the release of `haxe@next` on the main channel, which we plan in the next few weeks, would be a good time for that.

What do you think ?

**Comment by nadako** [comment]
If you guys are willing to support it, that might be a good idea. It shows that Haxe is not opposing against node/js world, but can be very well integrated into it, which is a good image.

Also, I believe dev version npm package building can be done by our CI.

**Comment by nadako** [comment]
I think all js transpilers (TS, Coffee) are easily installed by a single `npm` command, which attracts js developers. We should support that.

**Comment by Simn** [comment]
Agreed!

I'm fine with it as long as there's someone who updates this upon release.

**Comment by clemos** [comment]
Of course, we'll continue maintaining it.
I think it's extremely important to be on NPM, in order to compete with Typescript and other languages targetting JS.

Regarding CI:
I already have automated tests running on Travis.
The package currently doesn't need building (it's an installer, really, written in vanilla JS).
Maybe we could also use Travis / Github to automate NPM releases, rather than doing it manually on our end.

**Comment by nadako** [comment]
Let's do it! \o/

**Comment by clemos** [comment]
Fine :)
So, what's the plan ?
Do I just transfer ownership of npm-haxe to HF, or ... ?

**Comment by Simn** [comment]
@andyli: Can you handle this?

**Comment by nadako** [comment]
I'd say let's move try-haxe repo to HF while we're at it

**Comment by clemos** [comment]
@nadako try-haxe is quite unrelated ;) but you can open another issue, if you want.

**Comment by ncannasse** [comment]
Nice! Thank you for putting this together

**Comment by andyli** [comment]
@clemos @damoebius
Please go ahead to transfer the repo to HF and add my npm account ([andyli](https://www.npmjs.com/~andyli)) to contributors. I will help polish it if needed, but since you two have much more experience on node and npm packaging, I will count on you as the lead maintainers of the package ; )

It looks like npm organisation is a paid feature. I'm not sure if we really need that at the moment.

**Comment by damoebius** [comment]
We can only create a HF account on npm, it's free and we'll use it to 
publish

**Comment by andyli** [comment]
I don't think we really need a dedicated account for HF either. You just use your current personal account to publish. I see that it is how other popular npm packages (e.g. bower, express, or npm itself) work.

Also, having a dedicated HF account means we'll have to share a password... And it would be hard to figure out who actually did a release etc.

**Comment by damoebius** [comment]
You are right

**Comment by clemos** [comment]
I agree, setting up an NPM organization is not mandatory.

**Comment by clemos** [comment]
@andyli How about transferring the Github repo ownership to HF ?

**Comment by andyli** [comment]
Yes, please transfer. You will still have admin right after doing so.

**Comment by clemos** [comment]
@andyli It seems I can't transfer because I don't have admin rights on HaxeFoundation, 
so I added you as a collaborator, hoping you can do it.

**Comment by Simn** [comment]
I think the team has to exist first with you as a member.

**Comment by andyli** [comment]
Ah...
@clemos could you give me admin right to the repo? Only commit right doesn't allow me to access the setting page...

**Comment by clemos** [comment]
Personal repos don't seem to allow giving admin access to someone else.
So I transfered my repo to an ephemeral organization (with @andyli and @damoebius) : https://github.com/haxe-npm/npm-haxe
@andyli you may further transfer the repo to HF when you want

**Comment by andyli** [comment]
Sadly I still cannot access the repo setting page...
I've just created a npm team in HF, can you check if you can transfer the
repo now?
I didn't realize it is so difficult...

**Comment by clemos** [comment]
I couldn't see you in the Collaborators panel until you replied to the invitation ;)
Now I changed your rights to Admin, you should be able to do whatever you want.

**Comment by andyli** [comment]
ok... I think I have got it transferred finally... lol

**Comment by andyli** [comment]
@clemos I will let you update the url and stuff. I will see what can I do with CI tomorrow.

**Comment by clemos** [comment]
Ok, I'll do it.
There is certainly a bit of cleaning to do, as well : 
- removing all branches except `master`
- deleting current releases / tags
- maybe setup npm publication via Travis, and create a new tag / release

**Comment by nadako** [comment]
* Mention this way of getting haxe on the website in the "Download" section

**Comment by clemos** [comment]
I've updated all urls in README and package.json.
You may want to review the latter:
https://github.com/HaxeFoundation/npm-haxe/blob/master/package.json
* Does the `license` field look ok to you
* Anything to add ? (keywords ? man page ? authors ?)

**Comment by nadako** [comment]
I guess we should take inspiration from e.g. [TypeScript](https://github.com/Microsoft/TypeScript/blob/master/package.json) and [CofeeScript](https://github.com/jashkenas/coffeescript/blob/master/package.json) package.json files.
Namely, we're missing "homepage" (haxe.org?), "keywords" (compiler, language, javascript, haxe), "bugs" (haxe or npm-haxe?).

**Comment by andyli** [comment]
I've read more about the subject and updated package.json in https://github.com/HaxeFoundation/npm-haxe/commit/24df287cab3995bfc5899636bf2af387055abfd0.

My change is based on the idea that our npm package is merely a wrapper around haxe. Different from the TypeScript and the CoffeeScript packages, the Haxe package doesn't include the binaries or the source of the compiler (the binaries are downloaded at install-time). In this aspect, our package is more similar to [the Purescript package](https://www.npmjs.com/package/purescript).

**Comment by clemos** [comment]
@andyli :+1:

**Comment by Simn** [comment]
Are we done here?

**Comment by markknol** [comment]
I havent tried this but does this work? Because if so it might be a good idea to add a paragraph on the download page.

**Comment by clemos** [comment]
@andyli moved a couple of things in the repo, but I don't know if a proper NPM release has been done, or if it's ready.
I've been using my own fork for the last few weeks, but I can switch back to HF's whenever asked to test a RC.

**Comment by andyli** [comment]
See https://github.com/HaxeFoundation/npm-haxe/issues/9
