### ISSUE TITLE
List.hd exception in a macro-in-marcro case

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4947]
Here it is:

Main.hx

``` haxe
abstract A(Int) from Int {
    public macro function f(ethis) {
        haxe.macro.Context.typeExpr(ethis);
        return ethis;
    }
}

class Main {
    static function main() {
        var a:A = 1;
        a.f();
    }
}
```

`haxe --macro Main.main()` gives:

```
D:\Code\haxe\std/haxe/macro/Context.hx:368: characters 9-32 : hd
Main.hx:3: characters 8-42 : Called from
Main.hx:11: characters 8-13 : Called from
--macro:1: character 0 : Called from
Aborted
```

Though `haxe --run Main` works for some reason

**Comment by nadako** [comment]
I'd also like to know why `--macro` and `--run`/`--interp` behave differently WRT cases like this.

**Comment by Simn** [comment]
I think I shouldn't touch any macro issues until Haxe 4. It's like the PHP generator in the sense that every fix introduces two new bugs.

**Comment by ncannasse** [comment]
Could you look into having that `hd` properly caught and raised as a proper error?

**Comment by Simn** [comment]
It now errors with "Cannot type @:this this here`. I'll probably leave it at that for 3.3.

**Comment by RealyUniqueName** [comment]
Not reproducible anymore
