### ISSUE TITLE
@deprecated metadata

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#4952]
This issue is actually more an tiny enhancement proposition. 

Note: this is not about the [java target `@deprecated`metadata](http://haxe.org/manual/cr-metadata.html)

What about a adding a `@deprecated` metadata that would simply generate a warning in the compiler output like this:
```
typedef MyStruct = {
    var field01 : String,
    @:deprecated var field02 : Int,
    var field03 : Int
}

class MyApp {

    static public function main() {
        MySrv.fetchStructs(
            function(res:Array<MyStruct>) {
                for (r in res) trace(r.field02);
            }
        );
    }
}
```
When haxe-building this, we would get a warning for everywhere we reference/use MyStruct.field02:
```
$ haxe build.hxml
WARNING line XX: use of MyStruct.field02 is deprecated
```
I think this could be useful in a pretty large range of projects...

**Comment by Simn** [comment]
If you fix the syntax errors and try this with recent Haxe, you will find that this is pretty much exactly what happens.

**Comment by zabojad** [comment]
@Simn OK, where is this documented?

**Comment by andyli** [comment]
In `haxe --help-metas`.

The page at http://haxe.org/manual/cr-metadata.html needs updating though. @Simn How that's done?

**Comment by Simn** [comment]
I forget but I think either @markknol or @Gama11 were involved in that.

**Comment by zabojad** [comment]
@andyli `haxe --help-metas` gives: 
```
@:deprecated         : Automatically added by -java-lib on class fields
                        annotated with @Deprecated annotation. Has no effect on
                        types compiled by Haxe (java only)
```
Not exactly what we've described here...

**Comment by Simn** [comment]
This was changed in https://github.com/HaxeFoundation/haxe/commit/de499fcf80a133289d75a4dc22e5df2b0330698c and will be part of the next Haxe release.

**Comment by markknol** [comment]
@andyli at the time I copy/pasted the help-meta's, and created a table out of it. Afterwards, I made links to other manual pages.
