### ISSUE TITLE
import.hx: context during Context.getType?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#4956]
I need a way to ignore an import statement inside import.hx when `Context.getType()` is run. Tried `#if !macro` but doesn't seem to work.

```haxe
// import.hx

#if !macro
import test.Foo; // I want to ignore this statement during Context.getType()
#end


// Main.hx

package;

class Main
{
	static var foo:Foo;
	static function main()
	{
		$type(foo);
	}
}


// Build.hx

package;

import haxe.macro.Context;
import haxe.macro.Expr;

class Build
{
	public static function build()
	{
		// comment this line will fix the problem
		var t = Context.getType('Main');
		
		Context.defineType({
			pos: Context.currentPos(),
			pack: ['test'],
			name: 'Foo',
			kind: TDStructure,
			fields: []
		});
	}
}
```

build.hxml

```
-main Main
-cp src
-x bin/test.n

--macro Build.build()
```

Fails with: `Type not found : test.Foo`
(Haxe version 19676d1)

**Comment by Simn** [comment]
I'm terrible with contexts, but Context.getType evaluates in the outside (not macro) context so this looks like working as intended.

**Comment by kevinresol** [comment]
If that is the case, are there any workarounds for my problem? i.e. ignore some statement(s) in import.hx during `Context.getType()`?

**Comment by ncannasse** [comment]
@kevinresol that does not seem possible, as Simon said getType load things into your code context, not in your macro context, so in that context the import.hx module is already loaded and will be applied as usual. Of course you can still have these other files in another directory/classpath which does not have the import.hx in its basepath
