### ISSUE TITLE
Autocomplete popout too small on Retina / HighDPI screens

### ISSUE THREAD

**Issue by TomByrne** [HaxeFoundation/haxe#4958]
![autocompleteissue](https://cloud.githubusercontent.com/assets/274228/13895871/d9499072-edcd-11e5-96b9-3754274e7c41.jpg)

I'm running on Windows 10 (with screen scaling at 150%).
HaxeDevelop v5.1.1.1

**Comment by nadako** [comment]
Please report that to HaxeDevelop repository instead: https://github.com/fdorg/flashdevelop/issues

**Comment by TomByrne** [comment]
Oops, had both open, sorry.
