### ISSUE TITLE
@:astSource not working or disabled?

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#4959]
I thought I would experiment with`@:astSource` using Haxe `3.3.0 (git build development @ 7bc28bc)`, but my simple [example](https://gist.github.com/skial/c1e35988b853b214da39) doesnt appear to have the fields expression placed into the `@:astSource` params array.

Am I using `@:astSource` incorrectly or is it disabled/not fully implemented yet?

**Comment by Simn** [comment]
The metadata has an effect only when the field is seen by the compiler, which is not the case here. Using it on the class you are currently building is pointless because you get the syntactic representation of the fields via Context.getBuildFields anyway.

**Comment by skial** [comment]
Thanks for the clarification @Simn. This is a really powerful feature. Going on https://github.com/HaxeFoundation/haxe/commit/a44caafc8bb36b178e34eb84db74694b24bc43c6 and https://github.com/HaxeFoundation/haxe/issues/3285#issuecomment-159284300 as my only source of _documentation_, it wasnt clear my reduced example wouldnt work.

For anyone looking into `@:astSource`, the [gist](https://gist.github.com/skial/c1e35988b853b214da39) has been updated with working code.
