### ISSUE TITLE
[js] Std.is(a, Int) may call toString()

### ISSUE THREAD

**Issue by kaikoga** [HaxeFoundation/haxe#4962]
... which is not guaranteed to return, so type checking may fail.

simple example: http://try.haxe.org/#f440C
```
class Test {
    static function main() {
        trace(Std.is(new Test(), Int));
    }
    
    function new() return;
    @:keep function toString() return toString();
}
```

more real world-ish example: http://try.haxe.org/#bC2fF (DCE=no required)
```
class Test {
    static function main() {
        var a = new Map<String, Dynamic>();
        a.set("a", a);
        
        trace(Std.is(a, Int));
    }
    
    function new() return;
}
```

assume haxe could do a `typeof(o) == "number"` check before doing the `|0` int check to be safer.

**Comment by Simn** [comment]
Your first example almost made me close the issue, but the second one is more convincing.
