### ISSUE TITLE
[cs] String interpolation leads to wrong application of abstract type parameters

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4966]
I've boiled some failing code down to this:

```haxe
package ;

import haxe.unit.TestCase;
import tink.core.Either;

abstract PhysicalType<T>(Either<Class<T>, Enum<T>>) {
  
  public function toString() 
    return 
      switch this {
        case Left(c): Type.getClassName(c);
        case Right(e): Type.getEnumName(e);
      }
}
class Base extends TestCase {
  
  function throws<A>(t:PhysicalType<A>):Void {
    trace('type: $t'); // - The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?)
    //trace('type: ' + t.toString()); // - believe it or not, this works
  }
}
```

Although this is a hxcs problem, it looks like it could be solved (or at least worked around) way before generation.

**Comment by Simn** [comment]
I cannot seem to reproduce that. Could you post your haxe command line?

**Comment by Simn** [comment]
I had `-D erase_generics` in my build file, without it I can indeed reproduce the problem.

**Comment by nadako** [comment]
>  it looks like it could be solved (or at least worked around) way before generation

Indeed, I wonder what happens here, if `t.toString()` works, but not `"" + t`.

**Comment by Simn** [comment]
I know why this happens, gonna fix it.
