### ISSUE TITLE
[cpp] error: ‘Val’ in namespace ‘hx’ does not name a type

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4967]
This is a regression in 3.3. I sporadically get this for various types. It [happens for `EReg`](https://travis-ci.org/haxetink/tink_priority/jobs/117640672#L290) too:

> include/EReg.h:29:3: error: ‘Val’ in namespace ‘hx’ does not name a type
   hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);

**Comment by back2dos** [comment]
Another occurrence, if that helps: https://travis-ci.org/haxetink/tink_url/jobs/117643527#L300

**Comment by andyli** [comment]
Look like you're not using the git version of hxcpp, which is required for haxe dev.
You can get it by the command as follows:
```
haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git;
pushd $(haxelib path hxcpp | head -1);
  pushd tools/hxcpp; haxe compile.hxml; popd;
  pushd project; neko build.n; popd;
popd;
```
Note that the rebuild by default will build for both 32 and 64 bit, so the apt packages, `gcc-multilib` and `g++-multilib`, are needed.
An example travis config can be found at https://github.com/HaxeFoundation/hscript/blob/master/.travis.yml.

**Comment by back2dos** [comment]
Oh, thanks for the info. Will update my build soon and confirm that this is dealt with.

**Comment by back2dos** [comment]
Yes, that was the problem, thank you!
