### ISSUE TITLE
A class named "Include" cannot be used when targeting PHP

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#4972]
As the title says. Not exactly a showstopper. :) Error message:

```
Parse error: syntax error, unexpected T_INCLUDE, expecting T_STRING or T_VARIABLE or '$' in [file] on line [line]
```

**Comment by mockey** [comment]
That's a bit strange, because `include` is in genphp's list of reserved words. What exactly were you doing?

**Comment by ciscoheat** [comment]
Testing the Dataclass library. Here's the failed build: https://travis-ci.org/ciscoheat/dataclass/builds/117860426#L5041

And the diff for what fixed it: https://github.com/ciscoheat/dataclass/compare/90935e969fce...95e5c2790727#diff-49cffd96f77afaf1ed923d7efa331553R237

**Comment by mockey** [comment]
Hm, yes. Seems that only identifiers are taken care of, not class names.
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L316
Ouch.

**Comment by Simn** [comment]
Ouch indeed, this might have all sorts of consequences for reflection and such.

**Comment by mockey** [comment]
Yeah, strange that this went unnoticed so long (maybe iit was noticed, don't know). As far as I see the only class that gets renamed is List (to HList). And there is this (rather weird) `--php-prefix` command line opition, which puts a prefix before **all** class names (in root path I think), which also interferes with `@:netive`. In short: it's a mess. Sigh.
The best fix nowadays would be to add `@:native(prefix + className)` to such class names in the generator, wouldn't it?

**Comment by Simn** [comment]
Does this only affect `Include` or also `pack.Include`?

**Comment by mockey** [comment]
`pack.Include` becomes `pack_Include` as of now, so should not b affected.

**Comment by Simn** [comment]
We could try adding `([],"Include")` here and hope that the problem goes away: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/common.ml#L598

See the `pf_reserved_type_paths` entry for the flash target just above.

**Comment by mockey** [comment]
Ah, that makes the compiler show an error?

**Comment by Simn** [comment]
Looks like it gives a warning, which frankly might be good enough...

**Comment by mockey** [comment]
Ok, I can try that.
On a side note: This --php-prefix option really adds a prefix to **all** class names, even with package:
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L273
Now, that doesnn't make sense to me at all...

**Comment by Simn** [comment]
I never noticed that option before, I wonder if anyone uses it...

**Comment by mockey** [comment]
Maybe @skial does:
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L242

**Comment by skial** [comment]
That was something like 5 years ago!

I think my original use was to do something with wordpress, that then needed classes to be prefixed to work, I can't really remember. I've checked the original email to Franco, but I don't mention my use case in the email :/

I haven't used it in a few years, but it [looks like](https://github.com/search?l=haxe&q=--php-prefix&type=Code&utf8=%E2%9C%93) _three_ people on GitHub use it.

**Comment by mockey** [comment]
@skial:
Past comes back to haunt you :-)
I didn't know what this option does until yesterday. Thanks for checking anyway.

**Comment by mockey** [comment]
> Looks like it gives a warning, which frankly might be good enough...

Yes, you get:
Warning : Type path Include is reserved on this target
Should be good enough for now.
Maybe add some other keywords as well?
http://php.net/manual/en/reserved.keywords.php

**Comment by mockey** [comment]
Does it make sense to add all the keywords from:
http://php.net/manual/en/reserved.keywords.php
to `pf_reserved_type_paths`?

**Comment by RealyUniqueName** [comment]
Since this affects only classes in root package and is easy to workaround, but requires some work for proper fix, i'm going to close this issue.
Also new php generator (with `-D php7`) handles such naming properly.
