### ISSUE TITLE
In switch, cannot extract function if structure is a class

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#4975]
Hello,

I love the structure matching feature but I've come across a case where it isn't working and I can't see a reason why it couldn't work. If we're switching on a class instance we can extract regular fields just fine with
```haxe
switch classInstance{
    case {someField: value}: trace(value);
}
```
But if the field is a function the compiler errors `unknown identifier : value`

Here's a try haxe example http://try.haxe.org/#8d691

Is this something that could work? Or are the underlying reasons that prohibit it?

Thanks

**Comment by Simn** [comment]
This works on the current development version of Haxe, grab a nightly from builds.haxe.org.
