### ISSUE TITLE
Regression: abstracts created with inline constructors are no longer considered constants

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#4977]
Example: https://github.com/haxetink/tink_io/blob/master/src/tink/io/Progress.hx#L22

Leads to:

> Inline variable initialization must be a constant value

Not sure if this was intentional, but I'd prefer it to stay the way it was.

**Comment by Simn** [comment]
Could you post a standalone example?

I know why this no longer works, have to check how to work around this restriction.

**Comment by nadako** [comment]
That file looks quite standalone :)

**Comment by Simn** [comment]
Uhm, right, I somehow stopped processing it after `package tink.io;`.

**Comment by Simn** [comment]
This is going to be a bit of a problem. The inlined expression is now this:

```haxe
{
	var this;
	this = -1;
	cast this;
}
```

We used to employ a syntax-based heuristic to detect these "simple" cases which I removed because it lead to various problems.
