### ISSUE TITLE
[cpp] Value from a block not handled

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#4981]
```haxe
class Main {
    static var m:haxe.DynamicAccess<Int>;
    static function __init__() {
        var l = m.keys();
    }
}
```

`haxe -cpp bin Main`

```
Value from a block not handled Main.hx 4
haxelib run hxcpp Build.xml haxe -Dcppast="1" -Dhaxe3="1" -Dhaxe_ver="3.3" -Dhxcpp_api_level="330" -Dsource-header="Generated by Haxe" -I"D:\\Code\\haxe\\extraLibs/" -I"" -I"D:\\Code\\haxe\\std/cpp/_std/" -I"D:\\Code\\haxe\\std/"
cl.exe -Iinclude -nologo -O2 /WX- /fp:precise -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -FS -Oy- -c -EHs -GS- -arch:SSE -ID:/Code/haxe/lib/hxcpp/git/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/Main.cpp -FoD:/Code/playground/cpp_out/obj/msvc19xp/501f6158_Main.obj
Main.cpp
./src/Main.cpp(32): error C2275: 'Dynamic': illegal use of this type as an expression
d:\code\haxe\lib\hxcpp\git\include\Dynamic.h(14): note: see declaration of 'Dynamic'
./src/Main.cpp(32): error C2146: syntax error: missing ')' before identifier 'this1'
./src/Main.cpp(33): error C2065: 'this1': undeclared identifier
./src/Main.cpp(35): error C2059: syntax error: '}'
./src/Main.cpp(35): error C2143: syntax error: missing ';' before '}'
```

**Comment by nadako** [comment]
Generated C++:
```cpp
HXLINE(   4)		::Array< ::String > l = {
HXLINE(   4)			Dynamic this1 = ::Main_obj::m;
HXDLIN(   4)			::Reflect_obj::fields(this1);
            		}

```

**Comment by Simn** [comment]
Yep, the analyzer ignores `__init__`.

**Comment by ncannasse** [comment]
You shouldn't be using __init__ to init statics. __init__ is only meant to initialize the class value. It might be run before other classes are initialized.

**Comment by Simn** [comment]
I don't know what to do with this. Running the analyzer on `__init__` fields leads to death and destruction, so I cannot guarantee all the nice things the analyzer normally guarantees.

**Comment by nadako** [comment]
I can agree about this particular usage of `__init__`, but why "Running the analyzer on `__init__` fields leads to death and destruction"? Shouldn't it panic out on any untyped? Why `__init__` is so different?

**Comment by Simn** [comment]
It only panics out of the optimizations, but I'm pretty sure the transformation (to CFG and back) is enough to cause problems.

**Comment by Simn** [comment]
Looks like it's not so bad after all according to our unit tests. I don't know about hxcpp though because that's broken for other reasons at the moment. If that's fine then I guess we'll just go for it.

**Comment by Simn** [comment]
Let's see how it goes!
