### ISSUE TITLE
throw Void

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4982]
From hscript:

```haxe
class Main {
	static function main() {
		throw invalidChar(65);
	}

	static public function invalidChar(c) {
		throw "error";
	}
}
```

This makes it to the dump verbatim:

```
class Main{
	static main(method) : Void -> Void

	 = function() = {
		throw Main.invalidChar(65);
	}

	static public invalidChar(method) : c : Int -> Void

	 = function(c:Int) = {
		throw "error";
	}

}
```

The problem is that this puts `Void` in a value place, so we either have to error or transform this like we do for `return`.

**Comment by Simn** [comment]
The difference to `return` is that there's no `throw` without value, so I guess an error makes more sense in this case. Any opinions?

**Comment by ncannasse** [comment]
Yes, we should allow `return throw` but not `throw Void`
