### ISSUE TITLE
hscript vs. hxcpp

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#4983]
For some reason hscript seems to expose several MSVC-only problems that are not caught on our CI. I found #4982 there and after avoiding it I'm now looking at this error:

```
C:\GitHub\hscript>haxe build-cpp.hxml
haxelib run hxcpp Build.xml haxe -Dcppast="1" -Dhaxe3="1" -Dhaxe_ver="3.3" -Dhxcpp_api_level="330" -Dsource-header="Generated by Haxe" -I"C:\\GitHub\\haxe\\extraLibs/" -I"" -I"C:\\GitHub\\haxe\\std/cpp/_std/" -I"C:\\GitHub\\haxe\\std/"
cl.exe -Iinclude -nologo -O2 /WX- /fp:precise -DHX_WINDOWS -D_USING_V120_SDK71_ -GR -FS -Oy- -c -EHs -GS- -arch:SSE -IC:/GitHub/hxcpp/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/haxe/ds/_HashMap/HashMapData.cpp -FoC:/GitHub/hscript/bin/obj/msvc18xp/da53dfda_HashMapData.obj
GenericStackIterator_hscript_Token.cpp
include\haxe/ds/_GenericStack/GenericStackIterator_hscript_Token.h(50) : error C2555: 'haxe::ds::_GenericStack::GenericStackIterator_hscript_Token_obj::next': overriding virtual function return type differs and is not covariant from 'cpp::FastIterator_obj<hscript::Token>::next'
        C:/GitHub/hxcpp/include\cpp/FastIterator.h(25) : see declaration of 'cpp::FastIterator_obj<hscript::Token>::next'
```

@hughsando: Could you check out hscript and try running `compile-cpp.hxml`? I can try reducing this but it might be a bit messy.

@andyli: Could we run the hscript tests on AppVeyor?

**Comment by Simn** [comment]
Huh... I just tried in an Ubuntu VM and get the same error. Now I'm confused why our CI doesn't catch this...

**Comment by hughsando** [comment]
The problem I think is the Enum value (hscript::Token) appearing in the
type params (fast iterator) should be a "EnumBase", not a specific enum
class, since the representation is the same.  Looks like  a mixing of old
and new ast code in this case.  Or maybe being 'generic' has hidden some
information a bit.
Not sure why it has not shown up in testing earlier.

**Comment by hughsando** [comment]
Actually, without the "real" for loops, the FastIterator stuff does not get
used.  So just removing it would be one option.
