### ISSUE TITLE
[cpp] "symbol to the left of a '::' must be a type" with interface + type param

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4985]
Latest haxe + hxcpp, tested with MSVC.

```haxe
class Main<T:IDestroyable> {
	public static function main() {}
	
	public function new(obj:T) {
		obj.destroy();
	}
}

interface IDestroyable {
	public function destroy():Void;
}
```

```
./src/Main.cpp(12): error C3083: 'IDestroyable_obj': the symbol to the left of a '::' must be a type
./src/Main.cpp(12): error C2039: 'destroy': is not a member of '`global namespace''
./src/Main.cpp(12): error C3861: 'destroy': identifier not found
```

**Comment by Simn** [comment]
Are you sure you're on latest hxcpp?

**Comment by Gama11** [comment]
Yeah (seems like I was a single commit behind, but that doesn't make any difference).

**Comment by Simn** [comment]
I'm asking because I can't seem to reproduce that.

**Comment by Gama11** [comment]
Different MSVC versions maybe? Not sure how to find out which one is used by hxcpp, I have several installed..

**Comment by Gama11** [comment]
Looks like `set HXCPP_VERBOSE=1` tells you:

`Using MSVC version: 19`

**Comment by Simn** [comment]
`Using msvc cl version 18`

**Comment by Simn** [comment]
Okay I'm stupid, of course I cannot reproduce this if `-dce full` removes it.

**Comment by Gama11** [comment]
This should be reopened, fails on php and hl.

**Comment by hughsando** [comment]
This is the same one I have open still with classes (not interfaces), with single-class-template=no-template-at-all.
Can we handle this globally please?

**Comment by hughsando** [comment]
Very similar to this one: https://github.com/HaxeFoundation/haxe/issues/5026

**Comment by Gama11** [comment]
It seems like this is broken on cpp again.

**Comment by Simn** [comment]
I don't think it was fixed, it's consolidated in #5072.

**Comment by Gama11** [comment]
No, this one was definitely fixed: https://github.com/HaxeFoundation/haxe/commit/3c58eb14bccaf77f4473abb5ede28687acda88c4

This one wasn't: https://github.com/HaxeFoundation/haxe/issues/5026

**Comment by Simn** [comment]
Right, still, it's gonna be handled as part of #5072.

**Comment by hughsando** [comment]
I realized I had accidentally converted all interfaces to dynamic when I
fixed some nativeGen stuff.
The dynamic actually works - but it is sub-optimal so I need to revisit
interfaces and check the code is not how I want it.
