### ISSUE TITLE
Trouble with getModule/getType

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [HaxeFoundation/haxe#4991]
I am trying to build a class during macro time from a file formatted like this:

```
myString;String
myInt;Int
myCustomClass;CustomClass
```

For this I need to find the module if the Classes in the file. I tried:

```
        switch(haxe.macro.Context.getType(classname)) {
                case TInst(t,_): packname = t.get().pack;
                default: throw "Class not found";
            }
```

As well as using ```Context.getModule``` in my code. In both cases I get errors like  this:

```
/usr/lib/haxe/std/haxe/macro/Context.hx:249: characters 37-45 : Invalid field access : __s
Builder.hx:17: characters 19-56 : Called from
Main.hx:2: characters 2-7 : Called from
Aborted
```

I think this might be related to: #1775 but I am not sure.

Is there a workaround of how I could get the module of a class in macro time?

This is a crosspost from [here](http://stackoverflow.com/questions/36260874/building-set-of-properties-for-class-from-text-file-using-macros-in-haxe), which I did after I came to the conclusion that it might be a compiler bug.

**Comment by Simn** [comment]
Are you sure `classname` is not `null`?

**Comment by RudolfVonKrugstein** [comment]
MMh, am I sure? :-).

Now, I put this code before the code to detect which pack a class is in:

```
      trace(className);
      var type = Context.getType(className);
      trace(type);
```

And get this output:

```
Source/controllers/Builder.hx:9: VBox
Source/controllers/Builder.hx:9: VBox
Source/controllers/Builder.hx:9: VBox
Source/controllers/Builder.hx:9: PlayerListView
Source/controllers/Builder.hx:11: TInst(widgets.PlayerListView,[])
Source/controllers/Builder.hx:9: Button
Source/controllers/Builder.hx:9: Button
Source/controllers/Builder.hx:9: VBox
/usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Unsupported escaped char 's'
<builtin>:1: character 0 : Called from
```

So ... why is line 9 called so many times and line 11 only one time? Maybe this has to do with parallel execution? Or what could be the reason for that?

It is also noticeable, that the only class get to line 11, which is really part of my project (PlayerListView).

The other classes (VBox, Button) are from "stablexui". Maybe the module is not properly loaded?

**Comment by Simn** [comment]
There's no parallel execution, this is just the "call stack" because your macro is called recursively multiple times.

**Comment by RudolfVonKrugstein** [comment]
Oh, I am just realizing. It might not really be my code. When I try to compile the "PiratePig" example from openfl, I get:

```
/usr/lib/haxe/std/neko/_std/EReg.hx:33: characters 11-61 : Unsupported escaped char 's'
<builtin>:1: character 0 : Called from
/usr/lib/haxe/std/neko/_std/EReg.hx:22: lines 22-204 : Called from
/usr/lib/haxe/lib/openfl/3,6,0/openfl/_internal/macros/MacroShader.hx:29: characters 27-165 : Called from
Aborted
```

So this problem is not new, and there is a fix [here](http://community.openfl.org/t/solved-linux-macroshader-error/7240/2):

```
# cd /usr/lib
# sudo ln -s libneko.so.0 libneko.so
```

Unfortantly, that symlink already exists in my case.

I am on ubuntu 15.10 64 bit by the way.

**Comment by RudolfVonKrugstein** [comment]
Installing neko from github (https://github.com/HaxeFoundation/neko.git) solved the issue for me.

Strange, I have been using the ubuntu neko/neko-dev package without problems until now.
