### ISSUE TITLE
Swf files with "-D haxeJSON" fails to compile into adobe AIR for iOS in Flash

### ISSUE THREAD

**Issue by Skoo120** [HaxeFoundation/haxe#4992]
Hello contributors,
I came across this issue when exporting a swf from FlashDevelop, then trying to publish the exported swf into adobe AIR 20.0 for iOS using Loader(). I'm not sure what the problem is so I looked around with what I had.
Attached is a picture of the error I get on Adobe Flash when publishing (device testing) my file. 
![embed openfl error](https://cloud.githubusercontent.com/assets/17299120/14091190/ccfc0b56-f50c-11e5-88c2-f0e70da73844.PNG)
It looks like its something wrong with the haxe JsonParser.
I tried to export my swf again without `<haxeflag name="-D haxeJSON" />` in project.xml and Flash managed to compile my swf into a .ipa file.
Still unsure what was wrong with the file, I decompiled the exported swf from FlashDevelop and found that the switch/case statements are gone, but when I compile the swf in HTML5, the switch/case statements remain.
This is the decompiled code for JsonParser.ParseRec
![parse](https://cloud.githubusercontent.com/assets/17299120/14090302/763ec42a-f507-11e5-87d9-f37c6a060edb.PNG)
What can I do to solve this issue to export my swf files to have the haxe JsonParser and be able to include this when exporting to AIR for iOS?
*The swf file I'm exporting with FlashDevelop is a rectangular openfl.display.Sprite that colours the screen green.

**Comment by Skoo120** [comment]
Just wanted to leave a comment for those who skim this looking for a quick solution:
Comment out haxeJSON like so `<!--<haxeflag name="-D haxeJSON" />-->` in project.xml, compile the swf in Flash Develop, and include it in the items to export on Flash/Animate CC when exporting to Air for iOS

**Comment by Simn** [comment]
Not sure what's going on there, can you try with a recent Haxe build from builds.haxe.org?

**Comment by nadako** [comment]
This may be a bug in AIR AOT compiler.

**Comment by nadako** [comment]
Assigning to @ncannasse because of us all, he is probably the only one using AIR on mobiles and can do some research on this. Also tagging for 3.4 as this is not critical.

**Comment by ncannasse** [comment]
Looks indeed like  an AOT bug, could you open a bug at Adobe ? Also, you might want to try to upgrade to Air 21 to see if i was fixed. Anyway, there's not much to do on our side, the code looks quite clean here.

**Comment by chichilatte** [comment]
We were stumped by this in until i realised `dead code elimination` was set to 'no' in our haxe build command. That meant `haxe.format.JsonParser` was being added to the swf. I set it to 'std' and we can now build for iOS, phew.
