### ISSUE TITLE
abstract inline constructor does not generate _hx_deref() in php

### ISSUE THREAD

**Issue by adrianmm44** [HaxeFoundation/haxe#4996]
This code generates: new testing_tests_Test()->msg(); instead of: _hx_deref(new testing_tests_Test())->msg();

`class PhpTest {
	
	public static function main() {
		
		PhpTest.test().msg();
	}	
	public static inline function test() : TestAbs {
		
		return new TestAbs();
	}
}

@:forward

abstract TestAbs( Test ) {
	
	public inline function new() {
		
		this = new Test();
	}
}

class Test {
	
	public function new() {}
		
	public function msg() : Void {

		trace("Hallo World!");
	}
}`

**Comment by Simn** [comment]
I have no idea what `_hx_deref` is, but the output I'm getting is this:

```php
// Generated by Haxe
class Main {
	public function __construct(){}
	static function main() {
		$this1 = new Test();
		$this1->msg();
	}
	function __toString() { return 'Main'; }
}
```

Which looks fine to me?

**Comment by adrianmm44** [comment]
Hi Simn,
Your output looks good to me too.
But my output is different from yours, it generates: new Test()->msg();
Which fails without the _hx_deref() function
Have you any idea why my output is different?
Did you use any special compiler flags?
I’m using Haxe 3.2.1. btw.

**Comment by Simn** [comment]
Well then I suppose it is no longer an issue. Try grabbing a build from builds.haxe.org.

**Comment by adrianmm44** [comment]
Yep I got the same output now Simn.
Nice!
I’m a bit lazy sometimes when it comes down to updating :P
