### ISSUE TITLE
"Unbound variable" with unreachable code on Flash

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#4997]
```haxe
class Main {
	static function main() {
		var b = true;
		if (b) {
			return;
		}
		
		var a = [];
		a[0] = true;
	}
}
```

```
Main.hx:9: characters 2-3 : Unbound variable a
```

**Comment by Simn** [comment]
I know exactly why this happens, I just have to decide which of the 20 possible ways to address it is the best one.

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/60668b0c3b1a7135ca46a46763745e30171f0c71
