### ISSUE TITLE
[js] invalid code generation for funny anon object field names

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5000]
```haxe
class Main {
    static function main() {
        var a = {"a\n b": 1};
        trace(a);
    }
}
```

```js
Main.main = function() {
	console.log({ 'a
 b' : 1});
};
```

**Comment by Simn** [comment]
I guess this means there's an `Ast.s_escape` missing somewhere in genjs.

**Comment by ncannasse** [comment]
Ast.s_escape does not correctly handles unicode chars :   `var a = {"é": 1};`

**Comment by ncannasse** [comment]
Ah, maybe it does work for UTF8, since it doesn't escape chars > 32, sorry about the noise.
