### ISSUE TITLE
try.haxe.org -> Examples in menu fail to build

### ISSUE THREAD

**Issue by bradparks** [HaxeFoundation/haxe#5003]
Examples from try.haxe.org (the ones in the "Examples" menu), fail to build. For example, the "Drawing" and "Unit Test" examples give the following error:

![image](https://cloud.githubusercontent.com/assets/185477/14174238/91be19b2-f719-11e5-9aaa-f69c6be82207.png)

**Comment by Gama11** [comment]
Seems to work fine for me.

**Comment by Simn** [comment]
Same, also this would be the wrong repository.

**Comment by bradparks** [comment]
Here's how to duplicate it, and the reason I posted here as this was in the menu at the top of the "try.haxe.org" page for "Connect | Bug Reports"

Try this:
- Go here (linked from Justin Front email, pic attached): http://try.haxe.org/#Dc3f2
- Click "Build and Run" - it works
- Click "Examples | Drawing" 
- Click "Build and Run" - it fails with the message above

Here's a pic of Justin's email
![image](https://cloud.githubusercontent.com/assets/185477/14174495/0439d796-f71b-11e5-9508-d86625e2e733.png)

**Comment by bradparks** [comment]
Note: Problem occurs in Chrome Version 49.0.2623.87 (64-bit), on Mac El Capitan

**Comment by Gama11** [comment]
Here's the correct repo: https://github.com/clemos/try-haxe

**Comment by Simn** [comment]
@markknol: The Connect -> Bug Reports link has to be changed.
