### ISSUE TITLE
"Array<Dynamic> cannot be called" when tracing Meta.getType()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5005]
This is the reason for [some failures of the HaxeManua's Travis tests](https://travis-ci.org/HaxeFoundation/HaxeManual/builds/119763971) with Haxe dev. Isolated from the `Meta.hx` example:

```haxe
class Main {
  static public function main() {
    trace(haxe.rtti.Meta.Meta.getType(Main));
  }
}
```

Fails on js and python with:

```
Main.hx:3: characters 4-9 : Array<Dynamic> cannot be called
```

Has to be a fairly recent regression, didn't happen on the [Travis build 22 days ago](https://travis-ci.org/HaxeFoundation/HaxeManual/builds/114814712).

**Comment by Simn** [comment]
I need a wtf label.

**Comment by Simn** [comment]
Bisected to https://github.com/HaxeFoundation/haxe/commit/388206
