### ISSUE TITLE
weird type hole with abstracts (possible type ordering related)

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5008]
``` haxe
class Main {
    static function main() {
        f(null);
    }

    static function f(t:Token) {
        $type(t); // Token
        $type(t.type); // Dynamic
        if (t.type || t.type == 42)
            throw "WAT";
    }
}

abstract Token(Array<Dynamic>) {
    public var type(get,never):String;
    inline function get_type() return this[0];
}
```

If you move `Token` definition before `Main`, it complains about type errors correctly.
This is the same on 3.2: http://try.haxe.org/#e2058

**Comment by Simn** [comment]
I don't really understand how this works for the class case. The check against the accessors (`check_method`) is delayed and only run after the field access, so the relation of the accessor to the property field is never established before the field access is made.

It's not a regression so I'll leave it alone for 3.3.

**Comment by RealyUniqueName** [comment]
Not reproducible with the latest dev Haxe
