### ISSUE TITLE
Bad Javascript generated by use of inline var

### ISSUE THREAD

**Issue by tom-seddon** [HaxeFoundation/haxe#5013]
I have a static inline in the code I'm working with (which I'm afraid I can't supply):

    private static inline var DX:Float=-43;

And I use it like this somewhere:

    _panelImage = addImage(AssetData.QUESTION_PANEL, -DX, -DY);

The compiler generates the following code for that line:

    this._panelImage = this.addImage("question/panel_question01",--43,--39);

Which Chrome (quite reasonably) won't accept. I tried the obvious fix of using `-(DX)` instead, but no difference. `-(DX+0)` does work though.

I tried to narrow this down, but I couldn't make Haxe do anything wrong in a smaller test program.

Thanks,

--Tom

**Comment by Gama11** [comment]
Have you checked whether this still happens with recent dev builds of Haxe?

**Comment by nadako** [comment]
I also couldn't get it reproducing, so I think we're gonna need a reproducible example after all...

**Comment by nadako** [comment]
I'm closing this as we can't do anything without a reproducible example here. Feel free to reopen if you manage to provide one (also, don't forget to test on the dev build).
