### ISSUE TITLE
[php] Incorrect JSON encoding of empty object

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5015]
``` haxe
using haxe.Json;

class Main
{
    static function main()
    {
        trace('{}'.parse().stringify() == '{}');
        trace('[]'.parse().stringify() == '[]');
        trace('1'.parse().stringify() == '1');
        trace('"1"'.parse().stringify() == '"1"');
    }
}
```

Should print `true, true, true, true`, but php prints `false, true, true, true`

**Comment by kevinresol** [comment]
**Follow up:** Adding `-D haxeJSON` fixes it

**Comment by ncannasse** [comment]
What does `trace('{}'.parse().stringify())` print?

**Comment by kevinresol** [comment]
It prints `[]`

**Comment by mockey** [comment]
This is a problem with the conversion before encoding:
https://github.com/HaxeFoundation/haxe/blob/development/std/php/_std/haxe/Json.hx#L76
Empty objects will be converted to empty arrays and then encoded to empty arrays.
Non-empty associative arrays are encoded correctly as objects.
There was a reason, though, for turning objects into arrays before encoding, but unfortunately I don't remember it. Maybe a workaround for older PHP versions...

**Comment by kevinresol** [comment]
Will this get fixed in 3.3?

**Comment by mockey** [comment]
I can hava a look at it next week.
There is another PHP JSON issue here: #4592 
Maybe I can combine that into one PR...

**Comment by nadako** [comment]
@mockey are you still planning to do something about this for 3.3?

**Comment by mockey** [comment]
I've been on holiday. I'll try to make a PR for this next week.

**Comment by nadako** [comment]
Okay, tagging for 3.3 and assigning to @Simn, since I can't assign this to @mockey (maybe it's time to add him to HF?).

**Comment by nadako** [comment]
Or, well, not, let's move it to 3.4, just like #4592. If it'll be fixed earlier - then great :)
