### ISSUE TITLE
return Void not split for the local functions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5027]
Reduced from the promhx library:
```haxe
class Main {
    static function main() {
        var f:Void->Void = function() return null;
        f();
    }
}
```
this leads to the native compilation error on c++:
```
./src/Main.cpp(30): error C2562: 'Main_obj::main::_hx_Closure_0::run': 'void' function returning a value
./src/Main.cpp(28): note: see declaration of 'Main_obj::main::_hx_Closure_0::run'
```

generated c++
```cpp
            		HX_BEGIN_LOCAL_FUNC_S0(hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		void run(){
            			HX_STACK_FRAME("Main","main",0xed0e206e,"Main.main","Main.hx",3,0x087e5c05)
HXLINE(   3)			return null();
            		}
            		HX_END_LOCAL_FUNC0((void))
```

**Comment by nadako** [comment]
To me it seems that it should fail with a compilation error, but that'll break promhx and probably some more stuff...

**Comment by Simn** [comment]
@hughsando: I'm not quite sure if this is my problems or yours. This is the dump:

```
[Function:Void -> Void] [Block:Void] [Call:Void] [Parenthesis:Void -> Void] [Function:Void -> Void] [Block:Dynamic] [Return:Dynamic] [Const:Void] null
```

It's certainly an edge-case.

**Comment by nadako** [comment]
oh wait, not it shouln't fail, it should turn into `null; return;` I guess

**Comment by Simn** [comment]
The  problem is that at the time of typing that it's not yet Void but a monomorph. This would require doing the transformation during post-processing, which would be an option.
