### ISSUE TITLE
SecureRandom?

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5033]
It would be great if haxe would have a `haxe.crypto.SecureRandom` class so anyone can get secure random bytes easily.

I have a partially implementation for that class here (have to check c++/sys on windows and on several systems, maybe after the ssl PR, that library provides a function that could be used directly instead of trying to read from /dev/random):
https://github.com/soywiz/haxe-crypto/blob/master/src/com/hurlant/crypto/prng/SecureRandom.hx

If you find this useful I could make a PR adding that class.

**Comment by ncannasse** [comment]
I think it will be quite hard to provide large enough support for it (apart from C++/Neko), so i think it should stay in a library on its own.
