### ISSUE TITLE
haxe.Timer.stamp

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5036]
According to the "fib benchmark" sample code posted on [haxelang], haxe.Timer.stamp() resolution is not correct for several of the platforms. The absolute value is not specified but the difference should be in seconds, with as much precision as possible (at least millisec.) 

Could we test that for 3.3 ?

For instance by doing:

```
var t0 = haxe.Timer.stamp();
eq(fib(13),233);
var dt = haxe.Timer.stamp() - t0;
t( dt < 1 );
t( Std.int(dt*100)/100 != dt );
```

**Comment by Simn** [comment]
When [I used it recently](https://github.com/HaxeFoundation/haxe/issues/4549#issuecomment-198680273) the targets with problems were Java, Lua, HL and Python.

**Comment by ncannasse** [comment]
@waneck can you see if you can do something for Java?
@frabbit same for python please :)
@jdonaldson lua as well please :)

good haxe.Timer.stamp() precision is necessary to run haxe.Timer correctly with the new MainLoop feature in 3.3

**Comment by jdonaldson** [comment]
Lua doesn't have a millisecond precision timer in the base library.  If we want something accurate at milliseconds I'll need to add another c library.

**Comment by minoki** [comment]
For Java, the problem seems to be in [the implementation of `Sys.time`](https://github.com/HaxeFoundation/haxe/blob/development/std/java/_std/Sys.hx#L147) (integer division is used to convert milliseconds to seconds).

Partially reverting 0b8914e7c8e7905db6f36731f814af51c15cd57f should fix it.

**Comment by Justinfront** [comment]
I was curious I have used System.nanoTime() in my experiments, adapted from code I found online, and some googling suggests that nanoTime is actually more acurate?

> "It's important to note that System.currentTimeMillis has low resolution, on the order of 10ms for most systems. For timing the execution speed of code, it's usually best to use System.nanoTime instead. According to this excellent article by David Holmes, the typical resolution of nanoTime is on the order of microseconds. "

Sources: 
http://www.javapractices.com/topic/TopicAction.do?Id=85
https://blogs.oracle.com/dholmes/entry/inside_the_hotspot_vm_clocks

Probably not helpful but my experiment with Java timing, adapted from code I found online I did not do any form of testing to verify it was optimal, and in general I struggled to find much difference whet bothering to use a thread for timing, but perhaps useful for anyone exploring timing in java and coming accross this issue.
var elapsedTime: Int64 = System.nanoTime();
https://github.com/Justinfront/Jigsawx/blob/master/jigsawxtargets/hxjava/UpdateTask.hx
https://github.com/Justinfront/Jigsawx/blob/master/jigsawxtargets/hxjava/JigsawxJava.hx#L147

**Comment by Simn** [comment]
Assigning for python, pass on to @waneck afterwards.

**Comment by ibilon** [comment]
@Simn you can assign multiple people on an issue now ;)

**Comment by Simn** [comment]
Oh, neat!

**Comment by waneck** [comment]
This seems to be correct already on java/c#

**Comment by jdonaldson** [comment]
I've added a dependency on a cross platform implementation for millisecond timers in Lua.  So, as long as folks can install a common dependency, it should be fine there.

**Comment by frabbit** [comment]
fixed by https://github.com/HaxeFoundation/haxe/commit/e0e085392f0aee041b66d4cece2c907b98d23c3f

**Comment by Justinfront** [comment]
@waneck 
The current implemention in relation to time seems to use nanoTime() only in one place.

	```
public static function time() : Float
	{
		return cast(System.currentTimeMillis(), Float) / 1000;
	}

	public static function cpuTime() : Float
	{
		return cast(System.nanoTime(), Float) / 1000000000;
}
```
Can you clarify if this is intentional or if 'time' should be updated to use nanoTime ? Can you double check the Java target.
