### ISSUE TITLE
Dynamic + array = compiler error?

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxe#5037]
Haxe does not seem to have a problem with this, but not sure what to do in hxcpp
```
class Test {
static function main() {
   var d:Dynamic = 12.1;
   d+=[1];
   trace(d);
}
}
```

**Comment by Simn** [comment]
This is undefined behavior, or at least I hope it is.

**Comment by waneck** [comment]
I thought we were going to implement these specs https://xkcd.com/1537/ :P

**Comment by hughsando** [comment]
Probably related, but also having problems with these:
```
enum E { E0; }
class Test {
static function main() {
   var d:Dynamic = 12.1;
   d+=E0;
   d+=E;
   d+=Test;
   d+=[1];
   trace(d);
}
}
```

**Comment by ncannasse** [comment]
it should compile, but runtime behavior is undefined

**Comment by Simn** [comment]
There's nothing actionable here so I guess we can close this?
