### ISSUE TITLE
Bypass accessors and access field directly without resorting to reflection

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5039]
Well, the title says it all, I guess. Is there a way to do this? Maybe `@:privateAccess` or something like `@:privateAccess(true)` or whatever might be hijacked to that end?

Probably a bad moment to ask, but this comes up every now and then and I tend to bump into it every now and then myself, so I would appreciate if it could be taken under consideration for 3.4.

**Comment by ncannasse** [comment]
A metadata accessor would work (not @:privateAccess since it might be already used to access a private property, maybe @:directFieldAccess or something like this)

**Comment by back2dos** [comment]
Recently Simn and you have repeatedly voiced concerns over metadata proliferation, so I was looking for alternatives. Personally I much prefer adding an explicit one of course.

**Comment by nadako** [comment]
I want this too :)

**Comment by RealyUniqueName** [comment]
Which problem does this feature solve?
I thought if you need direct access to a value, you just make `(get,set)` and an additional field.

**Comment by back2dos** [comment]
Speaking for myself, I have two use cases:

1. I want this once in the constructor, while the object is not yet in a valid state and executing setters may thus cause problems. The problem with a private field is that it can be set from everywhere - even sub classes - and put the object into an invalid state yet again.

    I'd be perfectly happy with setter not executing in the constructor (one can still call the setter explicitly if so desired), but this risks to silently introduce a lot of bugs in code that relies on the current behavior.

2. Reflection free serializiation. I want to read/write the state without passing through accessors, because again they might get called while the state is not yet valid. In haxe serialization this works, because reflection can bypass accessors, but it comes with all sorts of limitations and overhead that I wish to avoid.

**Comment by nadako** [comment]
My reasons are basically the same as @back2dos's. I macro-build deserialization and default value inits.
I also transform every field into a `(default,set)` to generate some linking/change notification code, so setters are everywhere. Of course in my case I could build additional values and non-physical properties, but that would be much more complex.
