### ISSUE TITLE
[cpp] '_FileSystem': the symbol to the left of a '::' must be a type

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5043]
Another one where package names are important. Perhaps related to #5023?

```haxe
import massive.sys.FileSys;

class Main {
	public static function main() {}
}
```

```haxe
package massive.sys;

class FileSys {
	public static function isDirectory() {
		return sys.FileSystem.isDirectory("");
	}
}
```

```
./src/massive/sys/FileSys.cpp(37): error C3083: 'FileKind_obj': the symbol to the left of a '::' must be a type
./src/massive/sys/FileSys.cpp(37): error C2039: 'kdir_dyn': is not a member of 'massive::sys'
./src/massive/sys/FileSys.cpp(14): note: see declaration of 'massive::sys'
./src/massive/sys/FileSys.cpp(37): error C3861: 'kdir_dyn': identifier not found
```

Regression.

**Comment by hughsando** [comment]
@Simn This is an interesting one.  The private enum leaks out via inline, and is not generated.
https://github.com/HaxeFoundation/haxe/blob/f889418c63ab001070a302d6c686937c31d5f80f/std/cpp/_std/sys/FileSystem.hx#L72
I will fix it by removing the enum (could also remove the inline), which is pretty useless, but something to think about.

**Comment by hughsando** [comment]
Note also that the using class is also called "FileSystem", although not in the same package

**Comment by Simn** [comment]
Hmm, that is indeed quite interesting. I wonder if we should detect `inline` leaking private types like that. We already have a similar problem with type parameters being leaked.
