### ISSUE TITLE
[lua] haxe.Callstack is not implemented

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5049]
```haxe
import haxe.CallStack;

class Main {
	public static function main() {
		try {
			throw null;
		} catch (e:Dynamic) {
			trace(CallStack.toString(CallStack.exceptionStack()));
		}
	}
}
```

Lua:

```
> lua run.lua
Main.hx:8: 
```

Expected result (neko):

```
> neko run.n
Main.hx:8: 
Called from Main::main line 6
```

**Comment by jdonaldson** [comment]
I added some simplistic support for it for now, equivalent to what we have for python.

I'll look into adding something that preserves class names, etc.  But it'll involve some perf tradeoffs that I want to think about.
