### ISSUE TITLE
[python] AttributeError: '_hx_AnonObject' object has no attribute 'v'

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5051]
```haxe
class Main {
	public static function main() {
		var d:Data = haxe.Json.parse('{}');
		if (d.v == null) {
			trace("is null");
		}
	}
}

typedef Data = {
	var v:String;
}
```

Expected: should output `is null`

Actual:

```
> python3 run.py
Traceback (most recent call last):
  File "run.py", line 135, in <module>
    Main.main()
  File "run.py", line 19, in main
    if (d.v is None):
AttributeError: '_hx_AnonObject' object has no attribute 'v'
```

**Comment by nadako** [comment]
I think that's unspecified - the `v` field is non-optional, so the data is corrupted. If it was optional, a checking field access would be generated.

**Comment by Gama11** [comment]
I get the same error with `@:optional.`.

**Comment by nadako** [comment]
Eeeh, what? It's tested by this 8455f9a15adfcf71c159210a63cc40e79af59f42

**Comment by Gama11** [comment]
Oh. Nevermind, `@:optional` fixes it.

**Comment by nadako** [comment]
According to https://github.com/HaxeFoundation/haxe/issues/2928#issuecomment-41543897, the original case is undefined and should stay like this, so I'm closing this one.

**Comment by Gama11** [comment]
Fair enough! :+1:
