### ISSUE TITLE
[python] Suppress Ctrl+C KeyboardInterrupt tracebacks?

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5054]
The default behavior of python is to print a traceback when the execution is stopped with Ctrl+C:

```
> python3 run.py
^CTraceback (most recent call last):
  File "run.py", line 6, in <module>
    import inspect as python_lib_Inspect
  File "/usr/lib/python3.4/inspect.py", line 54, in <module>
    from dis import COMPILER_FLAG_NAMES as _flag_names
  File "/usr/lib/python3.4/dis.py", line 8, in <module>
    from opcode import *
  File "/usr/lib/python3.4/opcode.py", line 19, in <module>
    from _opcode import stack_effect
KeyboardInterrupt
```

Perhaps it makes sense to [suppress](http://stackoverflow.com/questions/7073268/remove-traceback-in-python-on-ctrl-c) this for consistency with other targets?

**Comment by nadako** [comment]
I'm not sure, I don't think we intentionally supress output from other targets, it just happens that python does print traceback while others don't. I'd leave it as is, because python users would expect this behaviour (e.g. for debugging) and disabling it could do more harm than good.

**Comment by Simn** [comment]
I agree, I don't think this would add any value.
