### ISSUE TITLE
[cpp] "divide or mod by zero" when dividing by zero

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5061]
Actually not a regression for once! (hapens with hxcpp 3.2.205 + Haxe 3.2.1 as well)

``` haxe
class Main {
    static function main() {
        trace(0 / 0);
    }
}
```

```
./src/Main.cpp(32): error C2124: divide or mod by zero
```

**Comment by hughsando** [comment]
What is the desired behaviour here?
Do we to burden every division with a whole bunch of extra checks?

**Comment by waneck** [comment]
Maybe detect this on the generator and generate `trace(Math.NaN)` instead?

**Comment by Simn** [comment]
Given that we default to Float division it makes sense to generate NaN in my opinion. Though this raises some uncomfortable questions about optimizing `Std.int(a / b)`...

**Comment by hughsando** [comment]
Are you only talking about the constant "0/0" or ```var x = 0.0;  1.0/x``` ?

**Comment by Simn** [comment]
The way I see it we define `/` to be a Float operation, so `anything / 0` should always be `NaN`. Only the constant case should matter here because this should already be true for anything else (right?).

However, this means that we cannot optimize `/` to integer division, which we currently do. I don't really want to think about that at the moment though...

**Comment by hughsando** [comment]
Ok, I get it now, it is a compiler error, not a runtime error.  That can be fixed.
Although, not sure what ```someFuncWithSideEffects()/0" should give, although maybe it is handled already.  I guess I will add hx::DivideByZero( someFunc() );

Is it too late for Math.idiv( ) ?

**Comment by Simn** [comment]
I agree we need something like idiv.

**Comment by NtrfAtZNS** [comment]
> so anything / 0 should always be NaN
@Simn this is is not correct. Only `0 / 0` is `NaN`. Everything else should give positive or negative infinity. Even `infinity / 0 == infinity`.

**Comment by Simn** [comment]
You're right.

**Comment by Gama11** [comment]
I can actually reproduce this again with latest Haxe + HXCPP, I guess this needs to be reopened?

**Comment by ncannasse** [comment]
Also means it requires a unit test :)

**Comment by Simn** [comment]
I confirm that this reproduces.

**Comment by hughsando** [comment]
I have a fix, but not a test: https://github.com/HaxeFoundation/haxe/commit/25f69f6f340ecf614c4e63ac8cb1d790ec7cbd9f
