### ISSUE TITLE
Invalid -cp arguments should error

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5065]
It seems sensible that `-cp some/non/existant/directory` should give a compiler error, similar to how `-lib` gives an error for haxelibs that are not installed.

**Comment by Simn** [comment]
I'm not sure if we really want that.

**Comment by ibilon** [comment]
Or at least a warning, in most cases this should happen when you make typos in the directory name I guess.

**Comment by ncannasse** [comment]
I'm not sure either, but I don't have much arguments for/against it, apart
backward compatibility

**Comment by Simn** [comment]
I'm worried that this might seem like a good idea in a small theoretical environment, but could be annoying in the complex real world of elaborate build systems and compiler invocations.

**Comment by ncannasse** [comment]
Agree: we don't know how users might have a lot of use cases for it, and it
doesn't hurt that much to keep the status quo

**Comment by Gama11** [comment]
A warning shouldn't hurt either though?

**Comment by nadako** [comment]
Keeping the status quo here, I guess...
