### ISSUE TITLE
EitherType<A,B> as a return type is very unsafe

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/haxe#5075]
And I think it might be better to forbid it ?

Consider this : 
```haxe
var either : String = SomeNodeLib.eitherStringOrArray();
either.substr(1); 
```
The compiler will be perfectly happy with that, whereas it's actually very dangerous code that may easily break at runtime if the returned value is finally an array.

I have no real solution for that, but I think it's wrong and should be avoided.
Maybe it's possible to allow auto-conversion from A or B to EitherType<A,B>, but not the other way around without a `cast` ?

**Comment by Simn** [comment]
That has nothing to do with return types and works as intended from the compiler's point of view. We cannot prevent bad usage here, just like we cannot prevent it if Dynamic is involved.
