### ISSUE TITLE
`haxe.extern.EitherType<js.html.CanvasElement, Dynamic>` has no field width

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#5081]
I'm trying the latest dev build (version 3.3.0).

I get a error on a Flambe project which comes from [the `WebGLRenderer` Flambe class](https://github.com/aduros/flambe/blob/master/src/flambe/platform/html/WebGLRenderer.hx#L111) which references to `js.html.webgl.RenderingContext`:

> flambe/platform/html/WebGLRenderer.hx:117: characters 20-35 : haxe.extern.EitherType<js.html.CanvasElement, Dynamic> has no field width

I checked, but `js.html.CanvasElement` has a `width` property. 

Is this expected behavior?

**Comment by Simn** [comment]
From Haxe's point of view yes. Though I'm not sure if that's a very good API.

cc @aduros

**Comment by nadako** [comment]
Extern code says:
```haxe
var canvas(default,null) : haxe.extern.EitherType<js.html.CanvasElement,Dynamic/*MISSING OffscreenCanvas*/>;
```

Mozilla docs says `OffscreenCanvas` is experimental, so maybe we should get rid of it for the time being. Or properly add it, but it may make sense to provide an `EitherType`-like abstract that forwards width and height fields from both classes.

**Comment by nadako** [comment]
This is a regression.
