### ISSUE TITLE
Issue on Android with serialization

### ISSUE THREAD

**Issue by narayank** [HaxeFoundation/haxe#5083]
I work on the Android Platform team and we've run into a handful of user reported crashes on Android N with the TiVo app (which appears to use the haxe framework). The crashes look something like this : 

03-08 15:51:49.397  5296  5296 E AndroidRuntime: java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at java.net.URLDecoder.decode(URLDecoder.java:177)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.root.StringTools.urlDecode(ProGuard:58)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.Unserializer.unserialize(ProGuard:398)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.Unserializer.unserialize(ProGuard:461)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.Unserializer.unserializeObject(ProGuard:238)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.Unserializer.unserialize(ProGuard:520)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at haxe.Unserializer.run(ProGuard:77)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at bhj.getObjectByKey(ProGuard:64)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at bwk.loadHistory(ProGuard:122)
03-08 15:51:49.397  5296  5296 E AndroidRuntime:        at bwk.__hx_ctor_com_tivo_haxeui_model_search_SearchListModelImpl(ProGuard:28)

We have concluded that this most likely isn't a platform issue. The serialized string (pasted below) contains a sequence of the form "%3Acl.820779%22%er" and "%er" isn't a valid hex encoding. It looks like a part of the serialized form was truncated, or has several characters missing.

We've gotten in touch with the Authors of the TiVo app as well, but wanted to bring this to your attention in case you'd seen something similar. Thanks.

-------- SERIALIZED OBJECT PASTED BELOW ---------
cy56:com.tivo.haxeui.model.search.SearchListHistorySerializedy13:mUnifiedItemsay661:%7B%22title%22%3A%22College+Swimming+%26+Diving%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Swimming+and+Diving%22%2C%22categoryId%22%3A%22tivo%3Aca.413881%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Playoff+Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.10916223%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.51290878%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy521:%7B%22title%22%3A%22Swimming%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Swimming+and+Diving%22%2C%22categoryId%22%3A%22tivo%3Aca.413881%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.179220%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy881:%7B%22title%22%3A%22Women%27s+College+Basketball%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Basketball%22%2C%22categoryId%22%3A%22tivo%3Aca.413788%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports+Non-Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916240%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Spanish%22%2C%22categoryId%22%3A%22tivo%3Aca.413875%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Playoff+Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.10916223%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.40980%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy403:%7B%22title%22%3A%22Grease%3A+Live%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Special%22%2C%22categoryId%22%3A%22tivo%3Aca.413876%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Musical%22%2C%22categoryId%22%3A%22tivo%3Aca.413846%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.316430679%22%2C%22collectionType%22%3A%22special%22%2C%22type%22%3A%22collection%22%7Dy203:%7B%22levelOfDetail%22%3A%22medium%22%2C%22personId%22%3A%22tivo%3Apn.423%22%2C%22last%22%3A%22DeGeneres%22%2C%22first%22%3A%22Ellen%22%2C%22nameId%22%3A%22tivo%3Anm.423%22%2C%22type%22%3A%22person%22%7Dy529:%7B%22title%22%3A%22The+Great+British+Baking+Show%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reality%22%2C%22categoryId%22%3A%22tivo%3Aca.413855%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Cooking%22%2C%22categoryId%22%3A%22tivo%3Aca.413803%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.326552342%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy667:%7B%22title%22%3A%22Property+Brothers+at+Home+on+the+Ranch%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reality%22%2C%22categoryId%22%3A%22tivo%3Aca.413855%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+Improvement%22%2C%22categoryId%22%3A%22tivo%3Aca.10916203%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+and+Garden%22%2C%22categoryId%22%3A%22tivo%3Aca.413830%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.336241312%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy4178:%7B%22image%22%3A%5B%7B%22height%22%3A53%2C%22width%22%3A70%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-70%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A67%2C%22width%22%3A89%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-89%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A70%2C%22width%22%3A93%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-93%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A75%2C%22width%22%3A100%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-100%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A78%2C%22width%22%3A104%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-104%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A89%2C%22width%22%3A119%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-sm%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A90%2C%22width%22%3A120%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-120%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A104%2C%22width%22%3A139%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-med%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A113%2C%22width%22%3A150%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-150%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A125%2C%22width%22%3A167%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-167%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A150%2C%22width%22%3A200%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fhdui-showing%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A150%2C%22width%22%3A200%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-lg%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A180%2C%22width%22%3A240%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-240%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A270%2C%22width%22%3A360%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-270%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%5D%2C%22title%22%3A%22CFL+Football%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Football%22%2C%22categoryId%22%3A%22tivo%3Aca.413818%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports+Non-Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916240%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.820779%22%erty+Brothers+at+Home%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reality%22%2C%22categoryId%22%3A%22tivo%3Aca.413855%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+Improvement%22%2C%22categoryId%22%3A%22tivo%3Aca.10916203%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+and+Garden%22%2C%22categoryId%22%3A%22tivo%3Aca.413830%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.324348445%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dy624:%7B%22title%22%3A%22Dawson%27s+Creek%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Drama%22%2C%22categoryId%22%3A%22tivo%3Aca.413811%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Thanksgiving%22%2C%22categoryId%22%3A%22tivo%3Aca.4008753%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Drama%22%2C%22categoryId%22%3A%22tivo%3Aca.413901%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.19366%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7Dhg

**Comment by Simn** [comment]
Some debug output:

```
Unserializer.hx:235: (0) c
Unserializer.hx:235: (1) y
Unserializer.hx:453: (60) y: com.tivo.haxeui.model.search.SearchListHistorySerialized
Unserializer.hx:235: (61) y
Unserializer.hx:453: (77) y: mUnifiedItems
Unserializer.hx:235: (78) a
Unserializer.hx:235: (79) y
Unserializer.hx:453: (744) y: %7B%22title%22%3A%22College+Swimming+%26+Diving%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Swimming+and+Diving%22%2C%22categoryId%22%3A%22tivo%3Aca.413881%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Playoff+Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.10916223%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.51290878%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (745) y
Unserializer.hx:453: (1270) y: %7B%22title%22%3A%22Swimming%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Swimming+and+Diving%22%2C%22categoryId%22%3A%22tivo%3Aca.413881%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.179220%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (1271) y
Unserializer.hx:453: (2156) y: %7B%22title%22%3A%22Women%27s+College+Basketball%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Basketball%22%2C%22categoryId%22%3A%22tivo%3Aca.413788%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports+Non-Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916240%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Spanish%22%2C%22categoryId%22%3A%22tivo%3Aca.413875%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Playoff+Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.10916223%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.40980%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (2157) y
Unserializer.hx:453: (2564) y: %7B%22title%22%3A%22Grease%3A+Live%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Special%22%2C%22categoryId%22%3A%22tivo%3Aca.413876%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Musical%22%2C%22categoryId%22%3A%22tivo%3Aca.413846%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.316430679%22%2C%22collectionType%22%3A%22special%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (2565) y
Unserializer.hx:453: (2772) y: %7B%22levelOfDetail%22%3A%22medium%22%2C%22personId%22%3A%22tivo%3Apn.423%22%2C%22last%22%3A%22DeGeneres%22%2C%22first%22%3A%22Ellen%22%2C%22nameId%22%3A%22tivo%3Anm.423%22%2C%22type%22%3A%22person%22%7D
Unserializer.hx:235: (2773) y
Unserializer.hx:453: (3306) y: %7B%22title%22%3A%22The+Great+British+Baking+Show%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reality%22%2C%22categoryId%22%3A%22tivo%3Aca.413855%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Cooking%22%2C%22categoryId%22%3A%22tivo%3Aca.413803%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.326552342%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (3307) y
Unserializer.hx:453: (3978) y: %7B%22title%22%3A%22Property+Brothers+at+Home+on+the+Ranch%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reality%22%2C%22categoryId%22%3A%22tivo%3Aca.413855%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+Improvement%22%2C%22categoryId%22%3A%22tivo%3Aca.10916203%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Home+and+Garden%22%2C%22categoryId%22%3A%22tivo%3Aca.413830%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Interests%22%2C%22categoryId%22%3A%22tivo%3Aca.413896%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.336241312%22%2C%22collectionType%22%3A%22series%22%2C%22type%22%3A%22collection%22%7D
Unserializer.hx:235: (3979) y
Unserializer.hx:453: (8162) y: %7B%22image%22%3A%5B%7B%22height%22%3A53%2C%22width%22%3A70%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-70%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A67%2C%22width%22%3A89%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-89%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A70%2C%22width%22%3A93%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-93%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A75%2C%22width%22%3A100%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-100%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A78%2C%22width%22%3A104%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-104%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A89%2C%22width%22%3A119%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-sm%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A90%2C%22width%22%3A120%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-120%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A104%2C%22width%22%3A139%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-med%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A113%2C%22width%22%3A150%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-150%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A125%2C%22width%22%3A167%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-167%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A150%2C%22width%22%3A200%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fhdui-showing%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A150%2C%22width%22%3A200%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fbravo%2Fbanner-lg%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A180%2C%22width%22%3A240%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-240%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%2C%7B%22height%22%3A270%2C%22width%22%3A360%2C%22imageType%22%3A%22showcaseBanner%22%2C%22imageUrl%22%3A%22http%3A%2F%2Fi.tivo.com%2Fimages-production%2Fos%2Fbanner-270%2F56%2F83%2F56831c362d5e646e8b7692e00e5866ab.jpg%22%2C%22type%22%3A%22image%22%7D%5D%2C%22title%22%3A%22CFL+Football%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Sports+Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916239%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Football%22%2C%22categoryId%22%3A%22tivo%3Aca.413818%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports+Non-Event%22%2C%22categoryId%22%3A%22tivo%3Aca.10916240%22%2C%22type%22%3A%22category%22%7D%2C%7B%22label%22%3A%22Sports%22%2C%22categoryId%22%3A%22tivo%3Aca.413905%22%2C%22type%22%3A%22category%22%7D%5D%2C%22collectionId%22%3A%22tivo%3Acl.820779%22%erty+Brothers+at+Home%22%2C%22category%22%3A%5B%7B%22label%22%3A%22Reali
Unserializer.hx:235: (8163) t
Unserializer.hx:453: (8163) t: true
Unserializer.hx:235: (8164) y
```

It ultimately goes wrong at `y4178` which reads a String up to `Reali`. The `t` is then processed as `true` and finally the `y` tries to parse another string and fails.

Not easy to tell what's cause and what's symptom here.

**Comment by Simn** [comment]
The implementation of `serializeString` is pretty straightforward:

```haxe
buf.add("y");
s = StringTools.urlEncode(s);
buf.add(s.length);
buf.add(":");
buf.add(s);
```

It adds `y`, then the length of the string, then a `:` and finally the string itself. Interestingly the string here seems to be *longer* than its assumed length. If it was shorter I'd suspect something related to UTF8, but I can't think of a reason why `s.length` would be inaccurate here.

@ncannasse: Any ideas?

Also I have to ask: Are you sure you use Haxe's stock serializer and not some custom/patched implementation?

**Comment by narayank** [comment]
I can't really speak for the authors of the TiVo app - I work on the android platform team. I reported things here in case this was a Haxe issue. Feel free to close it out if you don't believe it is.

I'm a bit surprised by your debugging info however. How did you conclude that y4178 reads up to "Reali" ? On Android, It fails because the URLDecoder.decode() call fails. This is because y4178 contains a string of the form "%er" ("...............%3A%22tivo%3Acl.820779%22**%er**t................."). 

You should've seen an exception from the URLDecoder for that string... which platform did you run this on ?

**Comment by Simn** [comment]
I tested this on neko which I assume doesn't care about bad URL formatting.

**Comment by kaushikprajapati** [comment]
As far as I know we (TiVo) is using stock  serializer.

**Comment by narayank** [comment]
Have you had any reports from your users about this ? We had precisely one report (and it was 100% reproducible on that device), but that person took an update and found that the issue disappeared.

**Comment by Simn** [comment]
This is the first and only time I've seen this issue and I still can't fathom what would cause it.

**Comment by narayank** [comment]
Yeah, same here....

**Comment by nadako** [comment]
So, this was some mystical one-time data corruption, it seems. I don't see what we could do about it, so I'm closing this. Feel free to reopen if it comes up again.
