### ISSUE TITLE
[js] Cannot extent haxe.io.Output

### ISSUE THREAD

**Issue by wiggin77** [HaxeFoundation/haxe#5086]
When extending Output and overriding Output.writeByte(c:Int), the overridden method is called with c=undefined for JavaScript target.  Java, C#, CPP work fine.   Haxe 3.2.1 (also reproduced with haxe_2016-04-08_development_ee25cd9).  Tested with Linux and Mac.

[http://try.haxe.org/#8C51e]

```haxe
import haxe.io.Output;

class Test {
    static function main() {
        
        var so = new StringOutput();
        so.writeString("Hello.  I think Haxe is great!");
        
        trace(so.toString());
    }
}

class StringOutput extends Output {
	private var   m_buffer:StringBuf;

	public function new() {
		m_buffer = new StringBuf();
	}

	override public function writeByte( c : Int ) : Void {
        trace("ch=" + c);
		m_buffer.addChar(c);
	}

	public function toString() : String	{
		return m_buffer.toString();
	}
}
```
Result:
ch=undefined
...

**Comment by nadako** [comment]
Wow, what a shame, thanks for reporting, I'll fix this and look whether we can have more unit-tests for `Input`/`Output`.
