### ISSUE TITLE
[Java] Using haxe generated jar using -java-lib

### ISSUE THREAD

**Issue by chipshort** [HaxeFoundation/haxe#5087]
I am trying to compile my haxe code to a jar file and use it from another haxe project using -java-lib parameter.
Of course, compiling my haxe code to a jar file works, but when trying to link the generated jar using the -java-lib, I get the following error:

```
addon_java/Addon.jar@haxe/root/Addon.class (%__hx_create):1: character 0 : Invalid number of type parameters for Array
```

When looking at the generated __hx_create method in the java code, there indeed are no type parameters for Array:

``` java
public static java.lang.Object __hx_create(haxe.root.Array arr)
{
    //line 32 "/usr/share/haxe/std/java/_std/Array.hx"
    return new haxe.root.Array<java.lang.Object>();
}
```

When adding "@:nativeGen" to the classes in the jar, the error disappears, but I get this instead:

```
File "gencommon.ml", line 2513, characters 63-69: Assertion failed
```

I'm using Haxe 3.2.1 btw.

**Comment by nadako** [comment]
I remember @waneck did some special fixes for that to work on C#, maybe there's need for the same for Java.
