### ISSUE TITLE
String has no field Log

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#5089]
```Haxe
package;

class Main {
	
	public var haxe:String = 'oops';
	
	public function new() {
		trace( haxe );
	}
	
	static function main() {
		new Main();
	}
	
}
```

`build.hxml`
```
-cp src
-neko bin/test.n
-D dump=pretty
-main Main
```

Output
```
haxe build.hxml
src/Main.hx:12: characters 2-7 : String has no field Log
```

Tested with `3.3.0 (git build development @ f57d4af)` and `3.3.0 (git build development @ 782e277)` with same result.

The only two targets that compile are JavaScript and Python, the others produce the same output as above.

**Comment by Simn** [comment]
It's a bit silly, but entirely within reason given that resolution order allows fields to hide packages. I don't think there's anything we can do about that.

**Comment by skial** [comment]
My bad, I should've checked the docs, its [all](http://haxe.org/manual/type-system-resolution-order.html) [documented](http://haxe.org/manual/type-system-import.html).

Thanks @Simn
