### ISSUE TITLE
[Flash] abstract on haxe.ds.Vector<T> confuses Vector with Int

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#5093]
[try.haxe](http://try.haxe.org/#eb35e) | code:

``` haxe
import haxe.ds.Vector;
class Main {
    static function main() {
        new AbsVector<Int>(42);
    }
}

abstract AbsVector<T>(Vector<T>) {
    public function new(size:Int) {
        this = new Vector<T>(size);
        trace(this);
        trace(Std.is(this, Int));
        trace(this.length);
    }
}
```

outputs

```
Main.hx:11: 42
Main.hx:12: true
[Fault] exception, information=ReferenceError: Error #1069: Property length not found on Number and there is no default value.
```

which suggests that `this = new Vector<T>(size)` in the abstract's constructor somehow compiles into `this = size`.
What's going on?

**Comment by nadako** [comment]
Sounds like #4783

**Comment by Simn** [comment]
Right, I forgot about the Flash part of #4783. I know that using Vector with type parameters like that causes problems, but that error is still really strange.

**Comment by synek317** [comment]
It is even easier to reproduce without having to use abstract:
http://try.haxe.org/#6C006

How can it even happen?

**Comment by ncannasse** [comment]
Ah right, it seems that `Vector<KTypeParam>` is compiled as `Object` by genSWF, which is normal for type safety (because the vectors are not compatible between them) but should throw an error when used with `new` because we don't know which vector class to construct.

```
function construct : 
	   0 this
	   1 scope
	   2 findpropstrict Object
	   3 reg 1
	   4 true
	   5 constructproperty Object 2
	   6 cast Object
	   7 setreg 2
	   8 findprop xxx
	   9 reg 2
	  10 initprop xxx
```
