### ISSUE TITLE
feature request: suggest imports when haxe compiler cannot find a called function

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#5094]
when typing code and the function cannot be found, 
it's a nice convenience when the compiler can suggest to add the import of the missing library.

for example, can be implemented like so:
$ haxe scan (or whatever command name you choose)

1. find haxe paths (folders haxe, haxelib).
2. scan them for changed files by comparing the modified time with those in an internal structure. (a serialized dictionary or something like it)

3. for changed files, parse and find their functions, remove the previous functions in the hash tables, and insert the new ones.

I think that 3 hashtables will be needed:
a) file => mtime
b) file => Array of function signatures
c) function => Array of file
these last two are synced. 

the algorithm is basically so: 
for each changed file,
- removePrevious: go to filedict, get functions, for each function, go to funcDict, remove filename from the value (type Array), remove key (filename) in fileDict.
- addFile: parse the changed file and get its functions, add filename => functions to fileDictionary, for each function add them with value filename to functionDict.
- setTime: update modified time in timeDict.

related to this feature are more helpful error messages when forgetting to include a library (-lib switch) in hxml files.

**Comment by Simn** [comment]
I don't think this makes much sense for Haxe. This is not C where it's common to have unqualified global functions. In Haxe every function belongs to a type and you can only access them in an unqualified way by importing statics. This in turn is rarely used and not worth any elaborate lookup.

If anything we could look for types but I'm not convinced that's a good idea either. *Maybe* the compilation server could check the files it knows about in case of an unknown identifier, but then we would have different errors for compilation server vs. normal compilation.

Feel free to experiment with what you have in mind and send a pull request for further discussion. There's always the chance that I'm just missing the point.

**Comment by kobi2187** [comment]
Hi Simn, when working with an advanced IDE, it can be a nice feature.
I saw this in visual studio when working with C#, you can remove unused "usings" or import a missing one, based on your code.
Since the compiler is now also the service for such ide's, I suggest it as an idea for all users, command line included.
