### ISSUE TITLE
Conflict between abstract @:forward and @:resolve ?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5097]
@simn asked me to file an issue for my question regarding @:resolve on abstract, see #3753

> <Simn> I think this is a @:forward vs. @:resolve case.
> <Simn> That's currently not really defined, please open an issue.

My question is: I'm trying to create a `@:resolve` `abstract` that's also `@:forward` over a concrete class -- I expected the abstract `@:resolve` to catch any "missing field" errors on the concrete, but it's not.

Here is the testcase: http://try.haxe.org/#20d5f

(I realize try.haxe.org probably doesn't have this feature yet. I tried this code with a nightly build and got the same error.)

If I remove the @:forward, the example does compile and work.

So the question is, what should the relationship between @:forward and @:resolve. I believe @simn and I agree on this behavior of resolution, in priority order:
- 1) abstract method, falls back to 2) @:forward, falls back to 3) abstract @:resolve

Note that: this does imply that if the concrete class `implements Dynamic`, that @:forward will always catch the behavior. But this is expected. To override a concrete resolve(), don't use @:forward.

I believe the current implementation, as of today, @:forward fully overrides @:resolve, so it leaves out step 3) above.

**Comment by jcward** [comment]
@Simn - here's a simpler testcase: http://try.haxe.org/#C59f3 unrelated to OpenFL's displaylist.

I believe this would be the only way to describe an abstract over `Dynamic`, whereby accessing elements of the `Dynamic`, those elements maintain the abstract typing, if you know what I mean.

Real use case: if I want to create an Object abstract over Dynamic that makes it behave like an ECMAscript object, it needs this behavior.

I peeked in the typer.ml at the `Not_Found`'s related to forward and resolve, but can't make any sense of the ocaml syntax. :)

**Comment by vonagam** [comment]
Fixed.
