### ISSUE TITLE
sys.ssl support for neko and cpp breaks hxssl support in haxe.Http

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#5099]
The changes to `haxe.Http` merged in #5014 broke hxssl support.

Compilation fails with `sys.ssl.Socket should be sys.net.Socket`.  This happens because there's no longer a `AbstractSocket` typedef, and hxssl's `sys.ssl.Socket` doesn't extend `sys.net.Socket`.

Changing hxssl might be viable, but it's non trivial: it uses custom `SocketInput` and `SocketOutput` streams.

**Comment by Simn** [comment]
Any suggestions?

**Comment by ncannasse** [comment]
I think the idea is that hxssl is no longer useful with native ssl support, ping @pperidont

**Comment by pperidont** [comment]
With native support for ssl on both neko and cpp targets, I think hxssl is no longer useful.

But if you need to keep using it, you can also change hxssl's `sys.ssl.Socket` : there's a new `init()` function in `sys.net.Socket` that you can override to use custom SocketInput and SocketOutput.

**Comment by thomasuster** [comment]
I'm running into an issue on neko/ubuntu.

This line crashes the program, no error is thrown.
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Http.hx#L703

Trying to find sys.ssl._Socket.SocketInput to narrow down, but I can't find it in source code.
