### ISSUE TITLE
cpp error in Xcode/clang with interfaces

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/haxe#5102]
Recent revisions (tried two days ago and now with 844a7db) create a line ala "__mClass->mCanCast = hx::TIsInterface< 0xed915bd3 >;" in the __register method for interfaces. Seems to be fine in VS and GCC but Xcode won't compile it.

**Comment by hughsando** [comment]
XCode 6 works, installing xcode 7....zzzz

**Comment by RobDangerous** [comment]
Tested some more - error only happens when C++ Dialect is set to C++11 or higher.
