### ISSUE TITLE
Pattern matching on extended class regression?

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#5106]
This last worked for me on `3.3.0 (git build development @ 7bc28bc)`, but fails on `3.3.0 (git build development @ f8ce87e)`, the latest from build.haxe.org. I've also tried `3.3.0 (git build development @ 782e277)`, which fails. 

Haxe `3.2.0` works fine on [try.haxe.org](http://try.haxe.org/#58A0F).

```Haxe
package;

class Main {
	
	static function main() {
		//var i = new Ref( ['a', 'b', 'c', 'd'] );	// Works
		var i = new InstructionRef( ['a', 'b', 'c', 'd'] );	// Fails => src/Main.hx:17: characters 11-12 : Unknown identifier : t
		
		trace( i, Reflect.hasField( i, 'tokens' ) );
		
		switch (i) {
			case { tokens:t }: trace( t );
			case _:
		}
	}
	
}

class Ref<Child> {
	
	public var tokens:Child;
	
	public function new(tokens:Child) {
		this.tokens = tokens;
	}

	
}

class InstructionRef extends Ref<Array<String>> {
	
	public function new(tokens:Array<String>) {
		super(tokens);
	}
	
}
```

**Comment by Simn** [comment]
Interestingly, this is documented to not work:

> A limitation with regards to class instances is that you cannot match against fields of their parent class.

http://haxe.org/manual/lf-pattern-matching-structure.html

**Comment by skial** [comment]
Ok, that sucks. Out of interest, why does the compiler enforce this limitation?

**Comment by back2dos** [comment]
Uhm, fair enough. But: why? :D

**Comment by skial** [comment]
Wait, I knew something seemed familiar about this, you implemented this back in 2014 in #3507

**Comment by skial** [comment]
The code from [`Issue3507.hx`](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue3507.hx) works, until you try to capture a value using `3.3.0 (git build development @ f8ce87e)`.

```Haxe
package;

private class A<T1> {
	public var t1:T1;
	public function new(t1:T1) {
		this.t1 = t1;
	}
}

private class B<T1, T2> extends A<T1> {
	public var t2:T2;
	public function new(t1:T1, t2:T2) {
		super(t1);
		this.t2 = t2;
	}
}

private class C<T1, T2, T3> extends B<T1, T2> {
	public var t3:T3;
	public function new(t1:T1, t2:T2, t3:T3) {
		super(t1, t2);
		this.t3 = t3;
	}
}

class Main {
	
	static function main() {
		var c = new C("foo", 12, false);
		var s = switch (c) {
			case { t1:a, t2:12, t3:false } : a;
			case _: "not ok";
		}
		
	}
	
}
```

**Comment by Simn** [comment]
Yes there's definitely something wrong.

**Comment by Simn** [comment]
This should work again now. Leaving this issue open to update the documentation.

**Comment by skial** [comment]
Thats great, thanks @Simn

**Comment by Simn** [comment]
Not RC-critical because it's just about documentation.
