### ISSUE TITLE
Crash on Galaxy Tab S / android browser 4.4 js target in haxe.Callstack class / Error object don't have stack member

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#5107]
Hi,
i got a crash when testing in crossbrowsertesting.com the Galaxy Tab S / android browser 4.4.
other browsers worked fine on the same device.
other devices worked fine on the same browser version.

the crash comes from the haxe.Callstack class line 82:

```
try {
    throw untyped __new__("Error");
} catch( e : Dynamic ) {
   var a = makeStack(e.stack);
```

the Error objects seems to have no stack member, and program stopped when trying to read .stack
strange thing is that e.hasOwnProperty("stack") returned true.

the fix i used was to check presence of member in class with a for loop inspection in pure js code. but its a bit ugly, and hope you would have better solution, thats why i did not made a pull request.

```
try {
    throw untyped __new__("Error");
} catch( e : Dynamic ) {

var foundMember = false;

untyped __js__('
for ( var prop in e ) {
    if(prop == "stack")
        foundMember = true;
}
');
var a = foundMember?makeStack(e.stack):null;
```

Thanks

**Comment by Simn** [comment]
Nothing we can do about this.
