### ISSUE TITLE
Very long compilation time with analyzer for nape example

### ISSUE THREAD

**Issue by thealgebraist** [HaxeFoundation/haxe#5111]
If I try to compile this nape example:

https://github.com/deltaluca/www.napephys.com/blob/gh-pages/samples/BasicSimulation/BasicSimulation.hx

using "-D analyzer" with Haxe 3.2.1 the compilation seems to take a long time -- I stopped it after
5 minutes.

**Comment by Simn** [comment]
Please try with a current build from builds.haxe.org.

**Comment by thealgebraist** [comment]
Yes, the newest version fixes this so that it works with the neko target.

However, when using the cpp target with the newest version I get these errors:

Error: In file included from ./src/zpp_nape/util/ZPP_Set_ZPP_SimpleSeg.cpp:5:
include/zpp_nape/geom/ZPP_SimpleSeg.h:35:7: error: no type named 'Val' in namespace 'hx'
                hx::Val __Field(const ::String &inString, hx::PropertyAccess inCallProp);
                ~~~~^
include/zpp_nape/geom/ZPP_SimpleSeg.h:37:7: error: no type named 'Val' in namespace 'hx'
                hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
                ~~~~^
include/zpp_nape/geom/ZPP_SimpleSeg.h:37:57: error: no type named 'Val' in namespace 'hx'
                hx::Val __SetField(const ::String &inString,const hx::Val &inValue, hx::PropertyAccess inCallProp);
                                                                  ~~~~^

**Comment by Gama11** [comment]
Are you still on hxcpp 3.2.205? You need a development version of hxpp as well.

**Comment by thealgebraist** [comment]
@Gama11 yes I was, and I just tested that using the git version of hxcpp fixes it - thanks!
