### ISSUE TITLE
Important nulls

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#5112]
Is this expected result of output?  
http://try.haxe.org/#a19CE

**Comment by Simn** [comment]
Yes, that's what Javascript does.

**Comment by back2dos** [comment]
To be fair, it's not really a JavaScript thing. As soon as bools are
nullable, that's the behavior you get and flash is no different for
example: http://try.haxe.org/#F04aB

But in JavaScript it's actually a common pattern (the code of Node.js is
littered with it):
http://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript

**Comment by markknol** [comment]
:smile:  I was just looking at this !! operator in JavaScript, I wondered if this worked in Haxe too, then stumbled into this. But I'm glad Haxe don't have these weird falsiness of javascript. But I didn't expect this result (or to be more specific, I expected the analyzer to fold it).
