### ISSUE TITLE
[cpp] covariant return types

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5113]
More of a clarification on how to amend code like this so that it works for all targets.

This snippet
```haxe

class TestNode {
    
    static public function main() {
        var childEl = new Element();
        var parentEl = new Element();
        var parentNode = new Node();
        
        parentEl.addChild(childEl);
        trace(childEl.getParent().children); // []
        
        parentNode.addChild(childEl);
        trace(childEl.getParent().children); // null
    }
}


class Node {

    var parentNode:Node;
    
    public function new() { }
    
    public function getParent():Node {
        return parentNode;
    }
    
    public function addChild(node:Node) {
        node.parentNode = this;
    }
}


class Element extends Node {
    
    public var children:Array<Node> = [];
    
    public function new() {
        super();
    }
    
    override public function getParent():Element {
        if (Std.is(parentNode, Element)) {
            trace("parent is element");
        } else if (Std.is(parentNode, Node)) {
            trace("parent is node");
        }
        return cast parentNode;
    }
}
```

compiles and runs on neko and js, while cpp fails to build it with: `./src/TestNode.cpp(41) : error C2039: 'children' : is not a member of 'Node_obj'`.

I'm probably missing something obvious, so I'm asking if there's a way to avoid to check/cast to `Element` in `main` and make cpp behave like js and neko?

(Tested on win with haxe nightly from two days ago, and latest hxcpp)

**Comment by Simn** [comment]
Is this a regression?

**Comment by azrafe7** [comment]
Just tested and yes, it seems a regression. It works for me using hxcpp 3.2.205 and a haxe build from mid january.

BUT... also found out that if I omit the return types and cast the result, like in:
```haxe
class Node {
    ...
    public function getParent() {
        return cast parentNode;
    }
}

class Element extends Node {
    ...
    override public function getParent() {
        if (Std.is(parentNode, Element)) {
            trace("parent is element");
        } else if (Std.is(parentNode, Node)) {
            trace("parent is node");
        }
        return cast parentNode;
    }
}
```

then it compiles with both old and new hxcpp. (maybe it can be of help)

**Comment by Simn** [comment]
@hughsando: I think we have two options here:

1. I bring back lots of temp vars.
2. You detect the required cast.

**Comment by Simn** [comment]
I'll just temp var some more, this is better for debuggers as well.

**Comment by hughsando** [comment]
I think the correct answer might be to static-cast (reinterpret) the return value in hxcpp.
The backend is in much better to do this now I have refactored it.
I also have some work to do to remove the temps from the debugger variable list.

**Comment by hughsando** [comment]
I have added the static cast in this case - should at least make the tmp version faster, but we might be able to do it without the temps now.

**Comment by Simn** [comment]
Cool, I'll try removing my change and see how it goes.
