### ISSUE TITLE
[display] more info on the @type completion

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5127]
I'm not sure how easy is to implement this, but it would be nice to have features like this for our hover hints:

![](http://i.imgur.com/QAn6VRG.png)
![](http://i.imgur.com/xjakYPZ.png)
![](http://i.imgur.com/722Bmh4.png)
![](http://i.imgur.com/wBUU9Ha.png)

This may require a way to encode the actual expression though.

**Comment by nadako** [comment]
or well, we could at least add "local", "argument", "field", "method" kinds to the type completion for now

**Comment by Gama11** [comment]
Shouldn't the type of get and set access be reported too for "property"?

**Comment by Simn** [comment]
Is that really useful? Seems kinda obvious what's what from the context... Properties I understand because that's not visible from syntax, but why do you want the compiler to tell you that you're hovering a function parameter when you're obviously doing do?

**Comment by nadako** [comment]
Well, considering that haxe can import statics, access methods/fields without `this`, shadow any names including arguments, etc., etc. I think this hint would help reading code.

**Comment by nadako** [comment]
Another useful feature with TypeScript hints in VSCode it that it shows documentation on hover:
![](http://i.imgur.com/897Fiu6.png)

**Comment by nadako** [comment]
I think we talked about it before and agreed to introduce the `@info` display mode that returns structured info such as: kind, type, doc.

**Comment by nadako** [comment]
Setting to 3.4, because it doesn't looks like we'll be able to introduce this in 3.3 (and we should be in a feature-freeze for month already, anyway:))
