### ISSUE TITLE
Provide official tmLanguage

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5130]
Currently every single editor uses custom grammar file probably derived from some other with different scope names, bugs and inconsistencies.

We should totally provide an official, accurate and well-tested grammar definition for use in all editors supporting that format (Sublime, Atom, VS Code, TextMate, and many others).

A great example is Microsoft's repo for Typescript: https://github.com/Microsoft/TypeScript-TmLanguage. It's auto-tested using this tool: https://github.com/Microsoft/vscode-textmate.

Besides syntax highlighting, I'd like to research the possibility of using grammar file for tokenizing sources in haxe-languageserver, so it's easier to find proper positions for haxe display calls.

**Comment by Justinfront** [comment]
Really interested to have completion etc... on textmate2.  Allan is on textmate IRC quite often, so if we can make some progress then we can quizz him on advanced hookup, happy to help where I can but not sure how it all works.

**Comment by nadako** [comment]
Sorry, but this issue is only about universal grammar file, so completion is out of scope.

**Comment by underscorediscovery** [comment]
@jeremyfa has been working on a complex and decent grammar based on TS I think, including sub string xml coloring and more.

**Comment by nadako** [comment]
I would like to provide a simple grammar really, coloring xml is out of scope of this, but this grammar should be a good base for custom modifications that add stuff like xml string coloring etc.

BTW, @jeremyfa @underscorediscovery do you guys know any good tools for creating those grammars? I'm thinking about something that visualizes the results as you edit the `tmLanguage` file. I even considering writing one myself if there are none.

**Comment by underscorediscovery** [comment]
I use sublime dev which eats yaml and converts to <other>. It has numerous in/out formats, but I prefer the clarity of the yaml structure, and it's include features.

https://github.com/SublimeText/PackageDev

Writing a language grammar usually takes a few minutes when you've done it a few times. From there atom has a converter for their `cson` ones.

[See simpler example](https://github.com/snowkit/sublime_flow/blob/master/flow-build-output.YAML-tmLanguage) but I know @jeremyfa had something he was showing me recently while working on a much more complete haxe grammar.

Even without xml specifics, the grammar he has been working on is extensive and close to the level of TS from what I understand, it would be a good idea to have a look.

**Comment by nadako** [comment]
Yeah, I think I'll use YAML too, because then I don't have to do regex escaping, and I'll surely will check  out Jeremy's grammar, thanks!

**Comment by jeremyfa** [comment]
_(sorry in advance for the long reply)_

The grammar @underscorediscovery is talking about is there: https://github.com/jeremyfa/language-haxe

It is based on official js grammar for atom (not ts). The reason for that is that haxe is pretty close to javascript syntax, js grammar is one of the most comprehensive grammar files for atom, and I didn't see any reason why haxe syntax highlighting should be much poorer than the javascript one. I kept all js constructs relevant to haxe (and there are quite a bunch) and added the ones specific to haxe (types, enums, ...). Also removed js-specific constructs. It needs some polishing (on switch with enum values for instance) but works pretty well already.

@nadako I don't know if it is relevant if you are looking for a "simpler" grammar file, but you can still take a look at it if you are interested. Also note that the xml formatting can easily be removed from the grammar file as it is independant from the rest, code-wise. The rest of the grammar file is very close to what exists for js. Regarding the tools, I simply used Atom and a local package to preview the result on a haxe project with enough code examples (as you just need to do ctrl+alt+cmd+L to refresh the display). I also used the chrome inspector inside atom to see which classes were associated with each token for debugging.

I think ultimately it's a good idea to have an official base grammar file, no doubt about it. That said, we should keep in mind that there is very low chance that everybody will be happy about a single grammar file to fit all purposes unless it's very comprehensive and well maintained. There may be easily some developers wanting to change/add something on it for their own workflow or some editor features. The xml formatting inside strings is still a good example of that, for let's say, a use with [haxe-react](https://github.com/massiveinteractive/haxe-react). I could also mention string interpolation highlighting: would it be handled by a "simple" grammar file? These have already been done for js or jsx grammars, I personally see absolutely no reason why I should avoid enjoying these features if they are valid for haxe as well and can be ported easily.

Some captures of the grammar with atom's _One Dark_ syntax theme (note that you just have to use another theme with less colors to have less noise if you prefer, like _monokai_, but _One Dark_ is good to visually see the different tokens):

<img width="512" alt="capture_d___e__cran_2016-03-20_a___02 38 35_1024" src="https://cloud.githubusercontent.com/assets/164094/14680641/3f815de8-071e-11e6-8bfe-35c3a3ef0c07.png"><img width="320" alt="capture_d___e__cran_2016-03-21_a___01 16 25" src="https://cloud.githubusercontent.com/assets/164094/14680640/3f815780-071e-11e6-85fc-085fd589b9b3.png"><img width="512" alt="capture_d___e__cran_2016-03-20_a___02 39 34_1024" src="https://cloud.githubusercontent.com/assets/164094/14680644/3f87c32c-071e-11e6-94d5-56343b11f046.png"><img width="260" alt="capture_d___e__cran_2016-03-20_a___02 39 10_1024" src="https://cloud.githubusercontent.com/assets/164094/14680643/3f85ad6c-071e-11e6-88ce-d34847b61ffe.png">

**Comment by nadako** [comment]
That looks good, I'll check it out for sure, thanks!

As for the string interpolation coloring - sure, because it's a haxe feature and we should provide support for that.

Btw about that xml highlighting? Are you just matching on the called function name (`jsx`)?

**Comment by jeremyfa** [comment]
It is disabled on regular strings but enabled if the string is preceded with `@dom`, `@xml`, `@tpl`, `@template`, `@html`, `@jsx`, or inside a `jsx(' ... ')` / `_(' ... ')`. I know it's a very pragmatic approach with hardcoded/framework-dependant values (here I am limited by the grammar syntax). But at least it doesn't overlap with default syntax and lets the developer explicitly request xml syntax highlighting inside strings, just by adding a metadata (the `jsx()` call exists to be compatible with haxe-react).

**Comment by underscorediscovery** [comment]
Oh since I forgot to note, I use "ScopeAlways" from package control, to show the scope selector in the status bar. Sublime reloads the grammar as soon as you change it, so for me hitting cmd b emits the tmLanguage from packagedev and sublime reloads it automatically and I typically work with 2 column when iterating quickly.

**Comment by Gama11** [comment]
The vshaxe grammar files are now extracted into their own repository: https://github.com/vshaxe/haxe-TmLanguage
