### ISSUE TITLE
[PHP] Uncontrolled Cast

### ISSUE THREAD

**Issue by TheoSabattie** [HaxeFoundation/haxe#5135]
Hi,

```
var lObj:Object1 = new Object1();
var lObj2:Object2 = cast(lObj, Object2);
```

Object2 does not extend Object1 but I don't have any errors. 
So I can undestand error only when I use a method of Object2 which does not exist on Object1.

Can you manage cast, check inheritance and show errors if necessary?

Thanks,

Théo S.

**Comment by mockey** [comment]
I sthis only a PHP issue?

**Comment by TheoSabattie** [comment]
Invalid casting displays errors in javascript output. I didn't try other code.

**Comment by RealyUniqueName** [comment]
I've added a test case https://github.com/HaxeFoundation/haxe/blob/d5be8c5ac190ea67646641cd84916432aede28b8/tests/unit/src/unit/issues/Issue5135.hx
And now cpp tests are failing on travis: https://travis-ci.org/HaxeFoundation/haxe/builds/183831522
Tests passed on appveyor.

**Comment by RealyUniqueName** [comment]
@hughsando Is this fixed somehow? That test is not failing anymore.

**Comment by hughsando** [comment]
Yes, it was fixed by this:
https://github.com/HaxeFoundation/hxcpp/commit/ab8e1af4318b5e37e85073caf5feff4422ecfbbe
