### ISSUE TITLE
[PHP and others ?] Write extern constants

### ISSUE THREAD

**Issue by TheoSabattie** [HaxeFoundation/haxe#5137]
Hi,

I was completing PDOClass but there is problem with constant `PDO::ATTR_DEFAULT_FETCH_MODE`
etc...  

If I write  
`public static var ATTR_CASE:Int;`

It writes
`PDO::$ATTR_DEFAULT_FETCH_MODE` 
(normal)

if I write 
`public static inline var ATTR_CASE:Int;` 
I am forced to set a value.  

So how can we write constant for extern of php or any other language?  
There are any macro or Built-in Compiler Metadata ?  

Thanks,

Théo S.

**Comment by Simn** [comment]
I think @mockey addressed this recently.

**Comment by yar3333** [comment]
```php
class JsonNatives
{
	public static var JSON_ERROR_NONE(get, never) : Int; private static inline function get_JSON_ERROR_NONE() : Int return untyped __php__("JSON_ERROR_NONE"); 
}
```

**Comment by yar3333** [comment]
For regular extern class:
```php
extern class MyExtern
{
    public static var MY_CONST(get, never) : Int; private static inline function get_MY_CONST() : Int return untyped __php__("MyExtern::MY_CONST"); 
}
```

**Comment by mockey** [comment]
With current dev version, global constants can be defined like this:
````haxe
@:phpGlobal // use global namespace
@:phpConstants("\\JSON_ERROR_") // can add common constant prefix
@:enum extern abstract JsonError(Int) {
  var NONE;
  ....
}
```
PDO with its class constants is a bit special, especially when these class constants are used in many different ways, like e.g. as keys in a native array of options and so on...
It might make sense to define an own enum here, like:
```haxe
@:native("\\PDO")
@:phpConstants
@:enum extern abstract PDOConst(Int) {
  var ATTR_CASE;
  ....
}
```
But I haven't really tried this yet.

**Comment by TheoSabattie** [comment]
Thanks @Simn , @yar3333 , @mockey :)

@mockey 
`@:native("\\PDO")
@:phpConstants
@:enum extern abstract PDOConst(Int) {
  var ATTR_CASE;
  ....
}`

It seems complex, 3 Built-in Compiler Metadata to get constant of class are required?
Constants of a class may be string, int, float etc... do you have to set enum for all of them?
Can we declare a constant with another way?

Théo S.

**Comment by mockey** [comment]
Well, I made this to be able to define global constants in externs, like the `SOAP_*` ones, e.g. These are almost always ints and it makes sense to group them in enums as they are mostly used as option flags. It's only a first step towards better PHP externs. Before there was only `untyped __php__`...

I agree that class constants like the PDO-ones are kind of different, It might be useful to have an additional metadata for extern fields here, like `@:phpConst` or so.

For another way, there is good old  `untyped __php__` like described above which is even more complicated and ugly IMO.
Or you can look up all the constant values and define a class like:
```haxe
class PDOConst {
  public static inline var ATTR_DEFAULT_FETCH_MODE = 19;
  ...
}
```
:-)

That's actually how it's done in cpp quite often:
https://github.com/ncannasse/hxsdl/blob/master/sdl/GL.hx#L427

**Comment by TheoSabattie** [comment]
> Or you can look up all the constant values and define a class like:

> ```
> class PDOConst {
>   public static inline var ATTR_DEFAULT_FETCH_MODE = 19;
>   ...
> }
> ```

It is pity to redefine something which is already define.

> I agree that class constants like the PDO-ones are kind of different, It might be useful to have an additional metadata for extern fields here, like @:phpConst or so.

I think it's the better way.
There is @:native metadata for class but there is nothing for functions or properties.
If some people want to translate obfuscation they are blocked.

Is there metadata planned for next version of haxe for this kind of issue? :3

Théo S.

**Comment by mockey** [comment]
> It is pity to redefine something which is already defined.

Sure. But it's not so easy to pass **real** native constants from Haxe. As you see even Nicolas puts redefinitions in his code for this.

> There is @:native metadata for class but there is nothing for functions or properties.

You can use `@:native` on functions and properties already. Something like:
```haxe
@:phpGlobal extern class Var {
  @:native("isset") static function isSet(val:Dynamic):Bool;
  @:native("\\var_dump") static function dump(val:Dynamic):Void;
  @:native("_SERVER") static var SERVER:php.NativeArray;
}
```
should work in current dev version.

I'll try to add`@:phpConst` metadata next time I poke around in genphp.

**Comment by Simn** [comment]
Since there is a solution already I'll close this issue. I acknowledge that the current solution is slightly awkward, but it's still PHP we're talking about so some awkwardness is to be expected. I'm not opposed to a simplified approach, but if it involves new metadata I would prefer if we waited for #3959.
