### ISSUE TITLE
[PHP] hx (private) to php (public)

### ISSUE THREAD

**Issue by TheoSabattie** [HaxeFoundation/haxe#5143]
Hi'

`private var something:Int`

becomes

`public $something;`

Can you respect access?

Thanks,

Théo S.

**Comment by mockey** [comment]
This is done on purpose, maybe because of Refection, not sure. I think it is similar on other targets, though.

**Comment by TheoSabattie** [comment]
Ok,

Why don't you use native reflexion object? If I want create php api for people who don't know haxe and use only php, we loose access notion // protection.

**Comment by mockey** [comment]
> Why don't you use native reflexion object?

I don't know. Maybe some things were not possible with it. Haxe reflection is surely quite different from PHP reflection. Also I don't know if that's the reason for having all fields public. I did not write the generator.

> If I want create php api for people who don't know haxe and use only php, we loose access notion // protection.

Well first of all, Haxe `private` is more like PHP `protected`. There is no equivalent to PHP `private`.
There is `@:protected` metadata. Maybe it works on PHP. haven't tried it.

**Comment by back2dos** [comment]
Haxe has it's own semantics for access control. It is possible to access private fields by use [access control metadata](http://haxe.org/manual/lf-access-control.html) or by prefixing the expression that accesses the private fields with `@:privateAccess`.

If you want to have a decent PHP API for haxe/php code, then your best bet is to use interfaces, as they will hide all the noise generated by the Haxe backend.

**Comment by TheoSabattie** [comment]
Thanks @mockey @back2dos :)

> There is @:protected metadata. Maybe it works on PHP. haven't tried it.

Unfortunately, it doesn' work :/

@back2dos 

>  then your best bet is to use interfaces, as they will hide all the noise generated by the Haxe backend.

I don't see, can you explain?
How do interfaces hide noise?

**Comment by back2dos** [comment]
Define the interface:

```haxe
package mylib;

interface Foo {
  public function publicMethod():Void;
}
```

And make your implementation:

```haxe
package mylib.internals;

class MyFoo implements Foo {
  public function publicMethod():Void { ... }
  private function privateMethod():Void { ... }
}
```

The interface is really all your PHP devs have to know about or code against. Another plus is that they won't have to look at the rather horrific function bodies.

Alternatively, you can go one step further and define the interface in plain PHP and make an extern for it in Haxe. That way the API itself will be native for all intents and purposes.

**Comment by TheoSabattie** [comment]
We talked about php output, I know interface, but I didn't undestand why do you talk about.

**Comment by Simn** [comment]
As @mockey says this is done in order to simplify reflection handling among other thing. I don't see this changing unless someone rewrites the PHP target, so I'll go ahead and close this.
