### ISSUE TITLE
Interface reification broken?

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#5145]
There seem to be multiple issues related to interface reification.  First, `iface = macro interface IA extends IB extends IC { };` gives the error `Unexpected implements` on the second `implements`.  Inserting a comma like this, `iface = macro interface IA extends IB, extends IC { };`, eliminates this error, but produces the resulting TDClass looks like this:

`kind => TDClass
   (
      { 
         name => IC, 
         pack => [], 
         params => [] 
      },
      [],
      true
   )`

As seen here, the IC gets placed into the 'superClass' field, and the IB interface gets dropped leaving the `interfaces` array empty.  Changing the code to `iface = macro interface IA implements IB, implements IC { };`, creates a correct looking TDClass:

`kind => TDClass
   (
      null,
      [
         { 
            name => IB, 
            pack => [], 
            params => [] 
         },
         { 
            name => IC, 
            pack => [], 
            params => [] 
         }
      ],
      true
   )`

However, this AST highlights the second issue, as it causes a compiler error, `Interfaces cannot implement another interface (use extends instead)`, which means that we can't work around this reification issue by manually creating the AST.

Either I'm seriously missing how to define an interface in AST, or interface reification and interface TDClass error checking is broken.

**Comment by ousado** [comment]
Regarding reification - actually the only toplevel declaration that is supported is class - the compiler wont directly complain if you use abstract or interface, but it still assumes the declaration to be a class and only support class syntax there - hence it complains about the second extend, something classes don't do - in the same way it complains about `from` or `to` declarations for abstracts. 

Then, it looks like it's "correct" about using the super class field for the first extend - it's also "correct" that interfaces only extend and don't implement each other, in haxe parlance.

The actual oversight here is that this API indeed doesn't allow to define multiple extends for an interface, which could be circumvented by interpreting the interfaces parameter differently when isInterface is set to true.

**Comment by ousado** [comment]
fix: https://github.com/HaxeFoundation/haxe/pull/5213
test with
```haxe
import haxe.macro.Context;
import haxe.macro.Type;
import haxe.macro.Expr;
using haxe.macro.Tools;

interface IA {}
interface IB {}
interface IC extends IA extends IB {}

class Issue5145 {

    static function main() test();

    macro static function test() {

        function get_type_path(ct:ComplexType) return switch ct {
            case TPath(tp):tp;
            case _:throw("bad");
        };

        var td = macro class ID {};
        var ia = macro : Issue5145.IA;
        var ib = macro : Issue5145.IB;
        var ic = macro : Issue5145.IC;
        td.kind = TDClass(null,[ia,ib,ic].map(get_type_path),true);
        Context.defineType(td);
        return macro null;
    }
}
```
