### ISSUE TITLE
haxe.ds.Vector missing some operators?

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#5146]
See : http://try.haxe.org/#5bB89

Basically:

`++array[0];` works
`++vector[0];` doesn't

> Invalid assign

Not sure if that's expected 🍰

**Comment by nadako** [comment]
Looks like #3702. Are you on dev?

**Comment by underscorediscovery** [comment]
3.2.1 here, could be related.

**Comment by nadako** [comment]
Ah, then it should be fixed by 453b88bed8e4ab988f514a2581f08ca2248b0915
