### ISSUE TITLE
[cpp] Native class names are prefixed with `::`

### ISSUE THREAD

**Issue by ntrf** [HaxeFoundation/haxe#5147]
A regression. When compiling this haxe code

```
@:include("list")
@:native(' ::std::list< int >')
extern class SomethingCpp {
}

@:unreflective
class Test {
    var var1 : SomethingCpp;
    
	function changeVar1(v : SomethingCpp) {
		var1 = v;
	}
	
    static function main() {
    }
}
```

haxe compiler generates types with `::` prefix, even for native types that already contain such prefix

```
:: ::std::list< int > var1;
void changeVar1(:: ::std::list< int > v);
::Dynamic changeVar1_dyn();
```

this leads to compiler errors `error C2589: '::' : illegal token on right side of '::'`

haxe 3.2.1 generates code as expected:
```
 ::std::list< int > var1;
virtual Void changeVar1(  ::std::list< int > v);
Dynamic changeVar1_dyn();
```

**Comment by PDeveloper** [comment]
I can confirm this issue. Happens to me as well with the latest Haxe nightlies.

**Comment by hughsando** [comment]
@Simn At some stage the @native was changed to parse into class path, rather than just a meta string.
This is a bit weird for cpp, when native uses "::" instead of ".".
I think the best fix here is for me to check for leading "::".  I don't think this is necessarily a bad thing, but is there some discussion of the logic here.

**Comment by ntrf** [comment]
I guess you don't have any other choice, if native tag parser does not check class path validity. Spliting class path by `.` without checking sounds wrong, esp for targets like java where you can have `java.util.ArrayList<org.example.mylib.Event>`. Doesn't seem to affect c++, though.

**Comment by Simn** [comment]
Hmm, has this really changed? I thought it has always been parsed as a dot path. If there are no dots you end up with `cl_path = ([], "::std::list< int >")`.

**Comment by Simn** [comment]
I rummaged through the archives and the dot-based parsing has been there since `@:native` was introduced: https://github.com/HaxeFoundation/haxe/commit/9f3cdd8eb4c0daf379c628f8dad3e3e7ba0174e5

**Comment by ntrf** [comment]
Is it usefull to parse it? I think bouncy castle is the only library that has same namespaces for two targets: Java and C#. Everything else is probably always target specific.

**Comment by hughsando** [comment]
hmm.  I don't know what has changed.  Maybe I used to simply ignore what
was in the cl_path and use the @:native meta directly.  Or maybe I just did
not add "::".  I actually used "hx.EnumBase" in a native for c++ just for
fun. Either way, it should be working now.
