### ISSUE TITLE
Possible bug in `parse_call_params`

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5154]
There is a loop going on which has an inner exception handling like so:

```ocaml
let rec loop acc =
	try
		match s with parser
		| [< '(Comma,_); e = expr >] -> loop (e::acc)
		| [< >] -> List.rev acc
	with Display e ->
		display (ECall (ec,List.rev (e::acc)),punion (pos ec) (pos e))
in
```

If I'm not misreading it this is stacking exception handlers because the `try ... with` encloses the inner `loop` call. This means if an inner iteration raises an `Display` exception, that exception is caught and rethrown at every iteration before it, creating... something strange.

**Comment by nadako** [comment]
Not sure what's this about, but setting this to 3.3 since obviously this is something @Simn left as a reminder to himself :-P

**Comment by Simn** [comment]
This is very old code and not critical for 3.3.
