### ISSUE TITLE
"Type not found" without position

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5159]
Using ca94cda, I suddenly encountered a strange thing that the compiler reported `Type not found: SomeType` without a filename and line number. It worked on 3.2.1 though. I am not sure how to isolate a minimal example at this moment... I may try it later

**Comment by kevinresol** [comment]
Ok I got it.

Requires `-lib react`

```haxe
package;

import api.react.ReactMacro.*;
import api.react.ReactComponent;

class Main
{
	static function main() 
	{
		jsx('<MyComp/>');
	}
}

class MyComp extends ReactComponent
{
	var a:NotExist;
}
```

**Comment by Simn** [comment]
ReactComponent.hx has this:

```haxe
typedef ReactComponent = ReactComponentOf<Dynamic, Dynamic, Dynamic>;

@:autoBuild(api.react.ReactMacro.setDisplayName())
extern class ReactComponentOf<TProps, TState, TRefs>
```

This is probably the same problem as https://github.com/HaxeFoundation/haxe/issues/4825#issuecomment-206583773 which is documented here: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.3.0#typing

I wonder why there's no error position though.

**Comment by Simn** [comment]
Actually this might be different because it's an `@:autoBuild` macro.

**Comment by kevinresol** [comment]
@Simn I would like to kindly request a blog post about *"type building order is undefined and how it affects macro-based codes"*. Because after going through the whole #4825 conversation I simply find that I can't wrap my head around it, especially when the behavior has changed in 3.3.

**Comment by Simn** [comment]
I don't know what to say about it other than "it's undefined, don't rely on it". It's not related to this particular issue anyway.
