### ISSUE TITLE
[cpp] Incorrect type generated for extern function calls

### ISSUE THREAD

**Issue by luboslenco** [HaxeFoundation/haxe#5165]
Hi,

I am the maintainer of Haxebullet physics repository located at https://github.com/luboslenco/haxebullet. The externs are unified to work the same in both JS and C++. Migrating to latest Haxe I started to experience issues in C++ builds. The tests are performed using OSX 10.11 and XCode 7.2.

Does not work:
```hx
pickConstraint = BtGeneric6DofConstraint.create(b.body.value, tr.value, false);
pickConstraint.value.setLinearLowerLimit(BtVector3.create(0, 0, 0).value);
```

Generated C++ code, fails to compile - btVector3  is not wrapped in cpp::Pointer:
```cpp
this->pickConstraint = (new btGeneric6DofConstraint(_hx_tmp3,_hx_tmp4,false));
::btGeneric6DofConstraint _hx_tmp5 = this->pickConstraint->get_value();
::btVector3 _hx_tmp6 = (new btVector3((int)0,(int)0,(int)0))->get_value(); // Error: No member named 'get_value' in 'btVector3'
_hx_tmp5.setLinearLowerLimit(_hx_tmp6);
```

By doing random things to figure out what is going on, I discovered that separating BtVector3 creation fixes the issue:
```hx             
pickConstraint = BtGeneric6DofConstraint.create(b.body.value, tr.value, false);
var btVec =  BtVector3.create(0, 0, 0);
pickConstraint.value.setLinearLowerLimit(btVec.value);
```

Generated C++ code:
```cpp
this->pickConstraint = (new btGeneric6DofConstraint(_hx_tmp3,_hx_tmp4,false));
::cpp::Pointer< ::btVector3 > btVec = (new btVector3((int)0,(int)0,(int)0));
::btGeneric6DofConstraint _hx_tmp5 = this->pickConstraint->get_value();
::btVector3 _hx_tmp6 = btVec->get_value();
_hx_tmp5.setLinearLowerLimit(_hx_tmp6);
```

**Comment by hughsando** [comment]
Yes.  The problem with this, is that "new" does not in fact return a cpp.Pointer, but instead a cpp.RawPointer.  This used to work because the compiler generated a lot of temp variables, and these did the conversion, but now it is more efficient.  This should be a good thing, but it needs a bit more work.

Consider this example:
```
@:native("std::string")
extern class StdString
{
   @:native("new std::string")
   private static function _new() : cpp.RawPointer< StdString >;
   inline public static function create() : cpp.Pointer<StdString> return cpp.Pointer.fromRaw( _new() );
}
```
If you follow this pattern, you should get it to work.
1. Make "_new" private and external, returning a raw pointer.
2. Do a simple conversion in the public "create" command.

**Comment by luboslenco** [comment]
Thanks Hugh, I appreciate your work. Haxebullet works again - your example did the trick.

I had to fix a few more issues here and there, which were my own miss-steps. Last pitfall I encountered is checking cpp.Pointer for null no longer works:
```hx
var body : cpp.Pointer<BtRigidBody> = null;
if (body == null) {
    // Not working
}
```
Is there any other way to check this?
