### ISSUE TITLE
[Java] Std.is() fail at java compilation stage

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5168]
The following code compiles fine in haxe but fail at java native compile stage. Other targets compiles fine though (e.g. cpp, cs)

``` haxe
trace(Std.is(1, String));
```

Error:

```
src/haxe/root/Main.java:34: error: unexpected type
        haxe.Log.trace.__hx_invoke2_o(0.0, ( 1 instanceof java.lang.String ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Main", "Main.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (8) )) )}));
                                             ^
  required: reference
  found:    int
1 error
Compilation error
Native compilation failed
Error: Build failed
Build failed
```

I am not sure if this is a bug. But it is inconsistent across targets.
Maybe we can consider doing some compile-time check at haxe level such that `Std.is(1, String)` should fail at haxe already?

**Comment by kobi2187** [comment]
I guess it has to do with structs vs. classes. primitive (on stack) types, vs. reference (by pointer) objects.

**Comment by nadako** [comment]
Yeah, as mentioned in https://github.com/HaxeFoundation/haxe/issues/5204#issuecomment-220776390, Java's `instanceof` expects a reference type (e.g. `Object`), so for this to work, a boxing cast should be added.

Is this the same on Haxe 3.2?

**Comment by nadako** [comment]
Not a regression (same thing on 3.2), so pushing it to 3.4...
