### ISSUE TITLE
Find unused import/using statements

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5170]
I want to investigate if we can find and report these.

**Comment by Simn** [comment]
Not very easy I'm afraid: The import/using information is not actually part of a module but instead kept in the typing context, which means we don't have access to it after typing.

**Comment by jdonaldson** [comment]
Just commenting to keep tabs on this.  Unused import detection is one of the last few things missing for modern IDE workflows for haxe.  Most refactoring work in Haxe is fairly easy, except for cleaning out unused imports.

**Comment by Simn** [comment]
![vsc_haxe_unused_import](https://cloud.githubusercontent.com/assets/634365/14836203/aee4f466-0c0e-11e6-9985-7f184151fd4c.png)

Got something working, but I'll have to test it a bit more.

**Comment by nadako** [comment]
Found one false-positive when importing an enum abstract without referencing the type directly, but using its "constructors".

**Comment by nadako** [comment]
wrong repo to report that, but still - these diagnostics should be "warnings", and it currently clears the line, leaving an empty newline in place, while it would be nice to remove the whole line.

**Comment by nadako** [comment]
it's also painfully slow on my work's project. it takes about 10 seconds to analyze the module...

**Comment by Simn** [comment]
> and it currently clears the line, leaving an empty newline in place, while it would be nice to remove the whole line.

Yes, but I didn't know how to actually do that.

> it's also painfully slow on my work's project. it takes about 10 seconds to analyze the module...

The problem is that we have to wait till the end of compilation before we can be sure that everything has been typed. This is especially true for macros, which might make this whole feature impractical...

**Comment by Simn** [comment]
Please try again now, I've changed it to check the module right after typing it. I'm not 100% certain that this works because we have to flush the field-building pass, but I *think* it works out like this.

I also fixed the imported enum/@:enum constructor checks.

**Comment by nadako** [comment]
Nope, still very slow, also I'm getting this:
```
src/rambo/DefData.hx:90: lines 90-101 : Type name plamee.macro._const.rambo.AdviceConditionDef is redefined from module plamee.macro._const.rambo.AdviceConditionDef
```

**Comment by nadako** [comment]
I guess that can be helped with disabling/simplifying some macros when `#if display`...

**Comment by Simn** [comment]
What does --times look like?

**Comment by nadako** [comment]
Hmm, compilation server doesn't seem to support `--times`...

**Comment by nadako** [comment]
Also I keep getting those "type is redefined" errors...

**Comment by nadako** [comment]
> Hmm, compilation server doesn't seem to support --times...

That's not about compilation server, just calling haxe from command line also doesn't report anything.
