### ISSUE TITLE
[display] @position queries return only first line of class declaration, instead of the whole span

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5171]
```haxe
class Main {
    static function main() {
        Main;
    }
}
```

`haxe --display Main.hx@52@position`

```xml
<list>
<pos>d:\code\playground\src\main.hx:1: characters 0-5</pos>
</list>
```

Results in vscode preview showing only the first line:
![](http://i.imgur.com/LLqcU4N.png)

**Comment by Simn** [comment]
This is something really weird in the parser related to `do_resume()` which I couldn't figure out yet.
