### ISSUE TITLE
enhancement: forbid repeated declaration for vars in the same function.

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#5176]
right now haxe (3.2.1) allows for 
```
var x = 3;
var x = 2;
```
imagine there were 8000 lines in between, and you just wanted to add a little feature. this could lead to confusing behaviour for the developer, and wasted time in debugging.
- I suggest only assignment `x = 2;` will be allowed, but not repeated declaration.
- the rule may be relaxed in scopes like if, while, inner functions etc, when it can be guaranteed not to influence the original value.

**Comment by Simn** [comment]
This is an intended language feature. Also, if you write functions with 8002 lines you have other problems than variable names.

**Comment by kobi2187** [comment]
hehe, true. but.. can you say a little about the rationale behind that language feature?
the only advantage I can think of is that there are no name collisions when you add code or "macro-expand" it.

**Comment by Simn** [comment]
Frankly, it's just convenient not to have this restriction.

**Comment by kobi2187** [comment]
Then I suggest it as a compiler warning, or an error when there is a special compiler flag.
this could really lead to confusion. forget 8000 lines. 8 lines with hard to understand logic, can just as well make you scratch your head for half an hour before you find it. it's just not necessary.

**Comment by andyli** [comment]
I see this situation of using variable of the same name in a different way. When this happens, it is usually better to contain the variables in their own block. And since Haxe is block-scoped, there wouldn't be any interference between the two same named variable.

For example, we can do:
```haxe
{
    var x = 3;
    // some calculation based on x
}
{
    var x = 2;
    // some other calculation based on x
}
```
In this way, the scope of `x` would be obvious to the reader.
