### ISSUE TITLE
Support @:jsRequire on vars

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#5178]
[It seems that `@:jsRequire` works on abstracts which is pretty cool](https://github.com/HaxeFoundation/haxe/issues/4862). 

However, it doesn't work on vars and I think it would be useful. `require()` can be used on json files, I've tested it successfully with browserify and [it is supported on Node.js since version 0.5](http://blog.gvm-it.eu/post/8175813806/nodejs-052-load-json-files-with-require).

A obvious case where I would use it is with React Intl i18n files. I have a json file for each language supported by my app and this file is just a "key": "value" set of messages.

In that case, it would be more logic to have:
```
class MyApp {
	@:jsRequire('../i18n/fr.json')
	static var frMsgs : DynamicAccess<String>;
	@:jsRequire('../i18n/en.json')
	static var enMsgs : DynamicAccess<String>;
}
```
instead of current:
```
@:jsRequire('../i18n/fr.json')
extern class FrMsgs {}
@:jsRequire('../i18n/en.json')
extern class ErMsgs {}

class MyApp {
	// ...
}
```

Something cool would then be to define an abstract enum once:
```
@:enum extern abstract I18nMsg(String) {
    var Msg01;
    var Msg02;
    // ...
}
```
With i18n json files looking like:
```
{
    "Msg01": "blablabla",
    "Msg02": "blablabla",
    ...
}
```
And being able somehow to then define vars with jsRequire to the right json file and type those vars to some kind of DynamicAccess type where the keys are of type I18nMsg...

**Comment by nadako** [comment]
You should be able to do that with normal static vars already:
```haxe 
static var frMsgs:I18nMsg = js.Lib.require("../i18n/fr.json");
```
