### ISSUE TITLE
Structs wont get correctly cast into references

### ISSUE THREAD

**Issue by jefvel** [HaxeFoundation/haxe#5180]
If you look at these bindings to c++ code:
https://github.com/jefvel/pointertrouble/blob/master/Libraries/pointers/sources/fart/Fart.hx

And the code where I call it:
https://github.com/jefvel/pointertrouble/blob/master/Sources/Empty.hx

You see that I want to convert the value into a reference before calling the function.
It seemed to work correctly at a earlier version of haxe, but the current one I'm compiles it into incorrect code.

At an earlier version of haxe the compiled code looks like this:

    cpp::Struct<fart::CoolStruct> f = null();		HX_STACK_VAR(f,"f");

	HX_STACK_LINE(12)

	f->a = (int)3;

	HX_STACK_LINE(13)

	f->o = (int)0;

	HX_STACK_LINE(14)

	cpp::Reference<fart::CoolStruct> tmp = ((cpp::Reference<fart::CoolStruct>)(f));	

	HX_STACK_VAR(tmp,"tmp");

	HX_STACK_LINE(14)

	bool tmp1 = fart::TestFunc(tmp);		HX_STACK_VAR(tmp1,"tmp1");

But the current version will compile it into this:

    HXLINE(  11)		::cpp::Struct<fart::CoolStruct> f = null();

    HXLINE(  12)		f->a = (int)3;

    HXLINE(  13)		f->o = (int)0;

    HXLINE(  14)		Bool _hx_tmp = fart::TestFunc(f);

This code doesn't create a reference, which is incorrect.

Have I done something incorrectly?

**Comment by hughsando** [comment]
It does not explicitly create a reference from the struct, but c++ should be able to cast from the Struct to the Reference.  What does "fartfile.h" look like?  If I try either:
```
inline bool TestFunc(cpp::Reference<CoolStruct> cs)
inline bool TestFunc(CoolStruct &cs)
```
It seems to work.

**Comment by jefvel** [comment]
TestFunc looks like this:

     bool TestFunc(CoolStruct* a)

So I'd want to call the function like this

    TestFunct(&var);

Is this possible?
