### ISSUE TITLE
javascript sourcemap has an old copyright

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#5191]
```
...
"sourcesContent":["/*\n * Copyright (C)2005-2012 Haxe Foundation\n
...
```

perhaps version should be 3.2.1
```
"version":3,
```

**Comment by markknol** [comment]
I searched for 2012, I think this is solved already? https://github.com/HaxeFoundation/haxe/search?utf8=%E2%9C%93&q=2012&type=Code

**Comment by MatthijsKamstra** [comment]
perhaps... I still use: `Haxe Compiler 3.2.1 - (C)2005-2015 Haxe Foundation`

**Comment by nadako** [comment]
That's not about source-map, that's actual hx file content, but I think @andyli recently updated all copyright headers, so I'm closing this one.

**Comment by ibilon** [comment]
The link @markknol added shows one file still has an out of date header https://github.com/HaxeFoundation/haxe/blob/development/std/cs/_std/haxe/ds/WeakMap.hx2 and a weird extension too

**Comment by nadako** [comment]
I have no idea what that file is. cc @waneck

**Comment by Gama11** [comment]
Sounds like the extension was changed to disable it: https://github.com/HaxeFoundation/haxe/commit/67d74cdaa69554282314e960236044e2bac6fed5

>Disable WeakMap for now since it's broken (hxgeneric error)
