### ISSUE TITLE
[cpp] Visual Studio freaks out when seeing __readgsqword

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/haxe#5197]
When I try to compile a 64 bit executable Visual Studio 2013 and 2015 just crash when trying to compile Tls.h. They don't like the __readgsqword thing, when I take out that line it works. Only tested with Kha's build system, but msdn says about that function "These intrinsics are only available in kernel mode" which doesn't sound good to me.

**Comment by nadako** [comment]
This `Tls.h` thing is new, so I suppose this is a regression.

**Comment by hughsando** [comment]
I have been compiling with the for quite a while, so I'm not sure what is different.
My understanding was the the kernel mode comment was out of date.
What do yo mean by crash - internal compiler error?

**Comment by RobDangerous** [comment]
Yes, internal compiler error. Did you try to compile for 64 bit?

**Comment by hughsando** [comment]
Yes, I've used it quite a bit.
Have you tried a simple test with ```haxe -main Test -cpp cpp -D HXCPP_M64``` ?
I suspect it might be some build flags, or possibly an include path with the windows kit being different to what I'm expecting.

**Comment by RobDangerous** [comment]
Finally had a closer look and it turns out msvc only crashes in specific, unspecified circumstances when seeing __readgsqword - I could solve the issue for Kha by putting it in a separate function (see https://github.com/KTXSoftware/khacpp/blob/68875509d1e1a2d0b436858bdf03bc62eede9493/include/hx/Tls.h#L55) so I guess it's fine as it is.

**Comment by hughsando** [comment]
Wow, that is really odd.
Is it worth a PR, or it it mixed with other kha specific stuff?

**Comment by RobDangerous** [comment]
Can certainly send a pull request but as long as it doesn't actually happen without the Kha specific stuff I'd consider it a needless complication. But your call - you want one, I send one.

**Comment by hughsando** [comment]
Do you have some idea of why this only happens in kha?  Some compile flags maybe or completely different usage?

**Comment by RobDangerous** [comment]
No idea, guess the reason is just about as random as the fix. I use standard VS2015 compiler options with the one exception that I link the C/C++ libraries statically, also no different usage of that part of hxcpp.
