### ISSUE TITLE
macro typing time accumulating like crazy

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5198]
In my macro-heavy work project, compilation (and completion) times are very slow, and judging by `--times` output, `macro typing (+init)` takes really long (about 43% of time).

I managed to figure out that `Typer.load_macro` does a lot of work for EACH macro call, which accumulates the bigger project grows, so there should be some caching that will speed up things alot.

**Comment by nadako** [comment]
@back2dos @fponticelli could you guys check if everything is okay with your macro libs after this change?

**Comment by back2dos** [comment]
This is great news. I had the same problem, but I had accepted it as the type of thing that can't just be fixed. 

FWIW it seems this has no effect for the tink_lang tests, which are really quite macro-heavy. I imagine this might cause bugs in server mode, but I can't check right now.

**Comment by back2dos** [comment]
Sorry, let me put that clearer: if there are any bugs, I imagine they might occur only in server mode and I didn't yet have the occasion to check that.
