### ISSUE TITLE
support multiple @:overload methods for externs

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5201]
The current `@:overload` mechanism for externs is:

``` haxe
@:overload(function(path:String, ?connectListener:Void->Void):Socket {})
@:overload(function(port:Int, ?connectListener :Void->Void):Socket {})
@:overload(function(port:Int, host:String, ?connectListener:Void->Void):Socket {})
static function connect(options:EitherType<NetConnectOptionsTcp,NetConnectOptionsUnix>, ?connectListener:Void->Void):Socket;
```

It's not only hard to write and read, but also can't be documented properly since there's only one doc-comment. Also you can't specify different metas (like e.g. `@:pure`) for different overloads.

Can we please support this instead:

``` haxe
@:overload static function connect(path:String, ?connectListener:Void->Void):Socket;
@:overload static function connect(port:Int, ?connectListener :Void->Void):Socket;
@:overload static function connect(port:Int, host:String, ?connectListener:Void->Void):Socket;
@:overload static function connect(options:EitherType<NetConnectOptionsTcp,NetConnectOptionsUnix>, ?connectListener:Void->Void):Socket;
```

IIRC, this syntax is already supported (even for non-externs) for C# and Java, so this shouldn't be hard to do.

I'd even say it would be great to have for 3.3, so extern libraries like `hxnodejs` can migrate to the new syntax earlier and discard the old one when haxe 3.4 is release (supporting two haxe minor releases sounds reasonable).

**Comment by jdonaldson** [comment]
Yeah, the overload syntax is definitely better than nothing. However, it looks awful, is awkward to write, and even more awkward to try and document.

**Comment by nadako** [comment]
I would LOVE to see this implemented for 3.3, but it doen't seem real, unfortunately, so pushing to 3.4 :(

**Comment by nadako** [comment]
@waneck maybe you could look into this for 3.3? I'm currently making some lua externs and doing the current overload thing is really awkward.

**Comment by nadako** [comment]
can we have this in less than another year plox? writing documented externs is quite painful without it...

**Comment by waneck** [comment]
I can do it for 3.3 but I'd need documentation on overload selection for anonymous types and function types

**Comment by Simn** [comment]
Function types should be straightforward with distance being the sum. Anon I have no idea.

**Comment by waneck** [comment]
You're right. We kinda already deal with function types overload selection, if you think that any function is *actually* a function type anyway :)
The problem with anons is that there are missing fields, optional fields, and there might even be some variance issues.
Nothing unsolvable, but we'd have to think about that

**Comment by nadako** [comment]
Hm? I thought it was just about mergin several syntax-level `@:overload` fields in `cf_overloads`, like it's done in C#/Java already.

**Comment by Simn** [comment]
Oh, I thought we were in a different issue. In that case you're right, it's just about that.

**Comment by waneck** [comment]
IMHO this would only add to the confusion about overload selection in Haxe. We already support two syntaxes, it would be nice if the overload selection algorithm were consistent between them

**Comment by ncannasse** [comment]
I think it's ok to support an alternative syntax for overload definition, without actually changing the way they are implemented for now. In general overload selection is hard to get right, and even harder for users to actually understand what will happen (unless they try it).

**Comment by Simn** [comment]
Thinking about it again, I wonder if it's necessary to find the correct overload field even for externs on some targets (hxcpp?).

**Comment by jdonaldson** [comment]
One possible caveat is that with @nadako's syntax, the ordering of method definitions becomes important.  That could be problematic in some cases (e.g. refactoring tools).

Possible fixes might be to implement some sort of selector specificity for the function argument types (e.g. like a css style selector, Dynamic arguments would be the lowest priority for an override)
Another option might be to pass in a manually specified override "importance" argument... that would be a total pita, but might be a good idea in a few cases.

**Comment by nadako** [comment]
Please, can we do something about this soon-ish? Every time I encounter an overloaded function in js/lua externs I wanna kill myself (or at least stop bothering with Haxe externs). It's painful to merge/rephrase the documentation and it still sucks in the end, e.g. http://hxdefold.github.io/hxdefold/defold/Vmath.html#slerp

**Comment by Simn** [comment]
This has been resolved, we can now use `extern overload function` on all targets.
