### ISSUE TITLE
type issue in abstracts

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#5205]
see: http://try.haxe.org/#BB35A

``` haxe
abstract Val<T>(T) from Int {        // should not be possible, obviously
    public inline function new(v:T)
        this = v;
    public inline function value():T return this;
}

class Test {
    static function main() {
        var v:Val<{a:{b:Int}}> = 42;
        trace(v.value().a.b);
    }
}
```

**Comment by Simn** [comment]
@ousado: Could you do me a favor and check which of the issues you opened are regressions?

**Comment by nadako** [comment]
This is obivously not a regression :)

**Comment by nadako** [comment]
@Simn what are we doing with type-holes like this? It's not a regression, so it's not critical for 3.3, but still it's quite bad and I personally think should be fixed for the new release.

**Comment by Simn** [comment]
This requires too much thought to make hasty decisions for the RC.

**Comment by RealyUniqueName** [comment]
Emits "You can only declare from/to with compatible types" with the latest dev Haxe
