### ISSUE TITLE
Wrong Utf8 constructor in hxcpp?

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5211]
https://github.com/HaxeFoundation/haxe/blob/dd5d9a1d9879c5283ef06d619ad07665c95dd06c/std/cpp/_std/haxe/Utf8.hx#L31

I think this is wrong. As fas as I know, the optional `size` of the constructror is used to preallocate an array size to avoid growing stuff on supported targets.

But it is used to left pad with zeroes (since addChar doesn't use the buffer, but appends to the end of the array)

So if you call `var utf = new Utf8(1);` and then add a character `utf.add(64)`, you will get a string of two characters `"\0\x64"` which I think is wrong, or at least not that useful.
Furthermore in other targets that ignore the `size` argument, same code would create the string "\x64". So the behaviour is not the same right now.

**Comment by hughsando** [comment]
I see your point - it's pretty useless.  But then again, the whole api is pretty useless (no way to cache anything useful).  Perhaps if it was called "reserve" rather than "size" it would make sense.

**Comment by soywiz** [comment]
I know that access operations could be linear. Utf8 is like that unless you keep an index.
In firefox they opted to support latin1 / unicode with a flag specifying the kind of the pointer instead utf8 to totally avoid the complexity and size of an index:
https://blog.mozilla.org/javascript/2014/07/21/slimmer-and-faster-javascript-strings-in-firefox/

Right now I'm using it just for building from a list of codepoints (constructor + add) and generating a list of codepoints (iter).
Maybe if that API is not that useful, it could be limited to convert an array of ints to a utf-8 string and a utf-8 string into an array of ints.

In my case it would be great if hxcpp just used UTF-16 (not needed UTF-32) to totally avoid having to do that. As Java Strings are encoded as 16-bits per character and higher codepoints are handled with surrogate pairs and just used when required.

But I suppose that if it was not done before, there was a good reason, for example being to call APIs expecting char* with zero copy.

EDIT: I was thinking about that: what about wrapping strings into a struct with two pointers: one for utf-8 (initially NULL) and other for utf-16 (or latin-1) with a flag as it does mozilla or just utf-16. And handling everything with the second pointer (charAt, indexOf, concat...) and generate utf-8 pointer once on demand when having to cast to char*. Internal hxcpp calls would totally avoid generating that pointer because would be using the second pointer.

**Comment by hughsando** [comment]
hxcpp was originally utf16, but it kept on failing the unit tests, so I
just converted it over.
I have thought about a dual/pointer arrangement, or maybe putting utf16
data at the end of the string if required, or some other version.
But I think the answer is a "WString" class with all the same functions as
String (member functions, not static functions!) and you can use abstracts
to convert between the two.  Then some "file open" functions etc that take
WStrings etc.  But that is another story.
