### ISSUE TITLE
[Mac] Homebrew fail

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5216]
`brew install haxe --HEAD` fails with the following error:

```
Last 15 lines from /Users/kevin/Library/Logs/Homebrew/haxe/01.make:
make -C libs/swflib OCAMLOPT=ocamlopt.opt OCAMLC=ocamlc native
make[1]: Nothing to be done for `native'.
make -C libs/xml-light OCAMLOPT=ocamlopt.opt OCAMLC=ocamlc native
make[1]: Nothing to be done for `native'.
make -C libs/ttflib OCAMLOPT=ocamlopt.opt OCAMLC=ocamlc native
make[1]: Nothing to be done for `native'.
make -C libs/objsize OCAMLOPT=ocamlopt.opt OCAMLC=ocamlc native
make[1]: Nothing to be done for `native'.
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/json.ml
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/syntax/ast.ml
File "src/syntax/ast.ml", line 1:
Error: libs/extlib/extString.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make: *** [src/syntax/ast.cmx] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by Justinfront** [comment]
From my historic experiments a few years back Ocaml4 no longer has some libraries built in that Haxe requires and Haxe has been very recently switched to Ocaml4, the dependancies would need to be installed separately and I expect this script references Ocaml 3.2 or similar.  I tend to favour MacPorts over Home Brew, and have not installed bleeding edge Haxe for awhile so can't offer more detailed advise, I originally found building on mac against Ocaml 4 problematic but expect manually now it should be a lot easier, maybe don't bother with HomeBrew just look at the linux install instructions.
https://github.com/HaxeFoundation/haxe/issues/5174

**Comment by andyli** [comment]
It could happens when you upgraded ocaml. It is not really a problem of homebrew. Just `make clean` it and it will works fine.

In short:
```
cd /Library/Caches/Homebrew/haxe--git
make clean
brew reinstall haxe --HEAD
```

**Comment by kevinresol** [comment]
@andyli yes it worked. Thanks.

**Comment by kevinresol** [comment]
Today I see something like this...

```
==> Reinstalling haxe
==> Cloning https://github.com/HaxeFoundation/haxe.git
Updating /Library/Caches/Homebrew/haxe--git
==> Checking out branch development
==> make OCAMLOPT=ocamlopt.opt ADD_REVISION=1
Last 15 lines from /Users/kit/Library/Logs/Homebrew/haxe/01.make:
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/typing/typer.ml
File "src/typing/typer.ml", line 2275, characters 4-31:
Warning 57: Ambiguous or-pattern variables under guard;
variable x may match different arguments. (See manual section 8.5)
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/typing/matcher.ml
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.version_extra -s --no-print-directory ADD_REVISION=1 BRANCH=development COMMIT_SHA=b9d8372 COMMIT_DATE=20160518104122 > src/version.ml
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/version.ml
ocamlopt.opt -g -w -3 -I libs/extlib -I libs/extc -I libs/neko -I libs/javalib -I libs/ziplib -I libs/swflib -I libs/xml-light -I libs/ttflib -I libs/ilib -I libs/objsize -I src -I src/generators -I src/macro -I src/optimization -I src/syntax -I src/typing -I src/display -c src/main.ml
ocamlopt.opt -o haxe -cclib libs/extc/extc_stubs.o -cclib libs/extc/process_stubs.o -cclib -lz -cclib libs/objsize/c_objsize.o   unix.cmxa str.cmxa libs/extlib/extLib.cmxa libs/xml-light/xml-light.cmxa libs/swflib/swflib.cmxa libs/extc/extc.cmxa libs/neko/neko.cmxa libs/javalib/java.cmxa libs/ziplib/zip.cmxa libs/ttflib/ttf.cmxa libs/ilib/il.cmxa libs/objsize/objsize.cmxa src/json.cmx src/syntax/ast.cmx src/typing/type.cmx src/syntax/lexer.cmx src/typing/common.cmx src/generators/genxml.cmx src/syntax/parser.cmx src/typing/typecore.cmx src/display/display.cmx src/optimization/optimizer.cmx src/typing/typeload.cmx src/generators/codegen.cmx src/generators/gencommon.cmx src/generators/genas3.cmx src/generators/gencpp.cmx src/generators/genjs.cmx src/generators/genneko.cmx src/generators/genphp.cmx src/generators/genswf9.cmx src/generators/genswf.cmx src/generators/genjava.cmx src/generators/gencs.cmx src/generators/genpy.cmx src/macro/interp.cmx src/generators/genhl.cmx src/generators/genlua.cmx src/optimization/dce.cmx src/optimization/analyzerConfig.cmx src/optimization/analyzerTypes.cmx src/optimization/analyzerTexpr.cmx src/optimization/analyzerTexprTransformer.cmx src/optimization/analyzer.cmx src/optimization/filters.cmx src/typing/typer.cmx src/typing/matcher.cmx src/version.cmx src/main.cmx
(cd /private/tmp/haxe-20160518-65638-g6m9do/extra/haxelib_src && /private/tmp/haxe-20160518-65638-g6m9do/haxe client.hxml && nekotools boot run.n)
Called from tools/Tools.nml line 46
Called from core/Args.nml line 62
Called from tools/nekoboot.neko line 158
Exception : Neko_error(load.c(357) : Primitive not found : std@elf_update_section_header_for_bytecode(3))
make: *** [haxelib] Error 255
```

**Comment by andyli** [comment]
Sadly, my Mac is out of order right now so I cannot check. Would you test with both the homebrew neko versions 2.1.0 and --HEAD?

**Comment by kevinresol** [comment]
After that error i tried to run neko, it showed 2.1.0

**Comment by nadako** [comment]
This is more of a Neko issue it seems (related to latest nekoboot changes?), but this is quite important, so I'm labeling this for 3.3 to deal with.

**Comment by kevinresol** [comment]
Just realized that it only happens in another mac machine than mine own one.
I myself is on El Capitan and the problematic one is on Yosemite (need double check, that machine is not nearby right now). Does that matter?

**Comment by kevinresol** [comment]
Confirmed the failing machine is on Yosemite 10.10.5

Here is the error when I run `brew install neko --HEAD`
```
Last 15 lines from /Users/kit/Library/Logs/Homebrew/neko/02.make:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmariadbclient.a(strtoll.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmariadbclient.a(strtoull.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmariadbclient.a(thr_mutex.c.o) has no symbols
[100%] Built target mariadbclient
cd /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-build && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E touch /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-stamp/MariaDBConnector-build
[ 86%] Performing install step for 'MariaDBConnector'
cd /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-build && echo skip install
skip install
cd /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-build && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E touch /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-stamp/MariaDBConnector-install
[ 87%] Completed 'MariaDBConnector'
/usr/local/Cellar/cmake/3.5.2/bin/cmake -E make_directory /tmp/neko-20160525-9779-100lxh3/CMakeFiles
/usr/local/Cellar/cmake/3.5.2/bin/cmake -E touch /tmp/neko-20160525-9779-100lxh3/CMakeFiles/MariaDBConnector-complete
/usr/local/Cellar/cmake/3.5.2/bin/cmake -E touch /tmp/neko-20160525-9779-100lxh3/libs/src/MariaDBConnector-stamp/MariaDBConnector-done
[ 87%] Built target MariaDBConnector
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by kevinresol** [comment]
Confirmed the failing machine is on Yosemite 10.10.5

**Comment by kevinresol** [comment]
I tried to `brew install neko --HEAD` first, neko gets installed, but `brew install haxe --HEAD` still fails

**Comment by andyli** [comment]
Ok, this is really weird. I cannot reproduce it on 10.11, so I guessed it is indeed a 10.10 issue. Now I set up a 10.10 VM and did `brew install neko` then `brew install haxe --HEAD`, and everything works fine...

**Comment by kevinresol** [comment]
hm..... Maybe just forget it, because I have used the 3.3 installer on the problematic machine, which worked fine.

**Comment by andyli** [comment]
Alright. If there is anyone still having this issue, let me know :)

**Comment by Justinfront** [comment]
Andy what's your position on Macports, I just feel that haxe should not be biased to Homebrew, it can be problematic to run Macports and Homebrew at the same time and it is rather arogant for Haxe to assume that it is the most important aspect of a users toolkit, it is possible that some users may have Macports dependancies in a project where they may just want to use haxe as some side helper like to generate lua or something.
From my perspective I have moved away from compiling my own Haxe because I use Macports over Homebrew, but actually prefer to use neither.
But if you look at some other projects they do support both Macports and Homebrew workflows.
https://github.com/textmate/textmate
One of the main reasons to give up on compiling my own Haxe was when latest ocaml dropped some dependancies from what Haxe expected, it started to get very tricky.  
But I really feel it would be nice to look into Mac support for compiling from source without having to rely on Homebrew, I mean that's how it works on linux and mac should not need to be different, to me Homebrew and Macports are nice additions but dependancy on Homebrew for compiling haxe from source on mac is not needed and really seems a bit wrong?  Happy to help where I can but probably need help on the missing ocaml aspects.

**Comment by andyli** [comment]
To clarify: Haxe (and Neko) can always be built from source on Mac without homebrew.

I guess you are missing [camlp4](https://github.com/ocaml/camlp4), which was removed from ocaml 4.01.0. If so, install it in whatever way you want (e.g. build from source). If you still have issue regarding to building haxe on Mac, open an issue, or ping me on Gitter or something.

**Comment by kevinresol** [comment]
I can't build on lastest commit: c4825bed472b4bebdbe83f14d7cae273bdbc1155
```
File "src/typing/type.ml", line 2376, characters 40-57:
Error: This expression has type 'a * 'b
       but an expression was expected of type Ast.complex_type
make: *** [src/typing/type.cmx] Error 2
```

**Comment by Gama11** [comment]
Have you tried a clean build (`make clean`)?

**Comment by kevinresol** [comment]
yes i did

**Comment by andyli** [comment]
Try something more powerful than `make clean`: `git clean -fdx`

**Comment by kevinresol** [comment]
That worked! thanks!

**Comment by frabbit** [comment]
i'm trying to build haxe from source on linux 64 (ubuntu), but haxelib fails with:

```shell
(cd /media/frabbit/data/work/projects/open-source/github/haxe/extra/haxelib_src && /media/frabbit/data/work/projects/open-source/github/haxe/haxe client.hxml && nekotools boot run.n)
Called from tools/Tools.nml line 46
Called from core/Args.nml line 62
Called from tools/nekoboot.neko line 156
Exception : Neko_error(load.c(357) : Primitive not found : std@elf_update_section_header_for_bytecode(3))
Makefile:106: recipe for target 'haxelib' failed
make: *** [haxelib] Error 255
~/work/open-source/github/haxe$ cd extra/haxelib_src/
~/work/open-source/github/haxe/extra/haxelib_src$ ../../haxe client.hxml 
~/work/open-source/github/haxe/extra/haxelib_src$ nekotools boot run.n
Called from tools/Tools.nml line 46
Called from core/Args.nml line 62
Called from tools/nekoboot.neko line 156
Exception : Neko_error(load.c(357) : Primitive not found : std@elf_update_section_header_for_bytecode(3))
```

any idea? i tried `make clean` and also `git clean -fdx`

**Comment by andyli** [comment]
Probably you're using an old version of neko. Try upgrade it to Neko 2.1.

**Comment by frabbit** [comment]
it is 2.1 ;)

**Comment by frabbit** [comment]
just installed neko from source, but it's the same issue

**Comment by frabbit** [comment]
nekotools is v1.0

**Comment by andyli** [comment]
Well, double check there is only one copy of std.ndll in your system. e.g. try rename std.ndll and there should be another error msg.

**Comment by frabbit** [comment]
ok, i deleted everything related to neko, installed everything with `make install` and now nekotools -v fails with 
`Uncaught exception - load.c(237) : Failed to load library : std.ndll (std.ndll: cannot open shared object file: No such file or directory)`

**Comment by frabbit** [comment]
the std.ndll file is located here /usr/local/lib/neko, but it seems that nekotools cannot find it

**Comment by frabbit** [comment]
i created a symbolic link from /usr/lib/neko to /usr/local/lib/neko manually and now i get a segmentation fault...

```shell
(cd /media/frabbit/data/work/projects/open-source/github/haxe/extra/haxelib_src && /media/frabbit/data/work/projects/open-source/github/haxe/haxe client.hxml && nekotools boot run.n)
Segmentation fault (core dumped)
Makefile:106: recipe for target 'haxelib' failed
make: *** [haxelib] Error 139
```

**Comment by andyli** [comment]
Maybe you've set `NEKOPATH` to somewhere else? It should not be set when using the default location.

For the record, I've just `make install` neko and then `make` haxe successfully on ubuntu.

**Comment by frabbit** [comment]
in my case it's installed to /usr/local/lib/neko (not sure why) and no environment variable is set.

**Comment by frabbit** [comment]
and haxe is installed to /usr/lib/haxe.

**Comment by andyli** [comment]
Ummm.. Everything sounds good. The default locations are correct. I am out
of idea right now.

**Comment by frabbit** [comment]
i realized that this `/media/frabbit/data/work/projects/open-source/github/haxe/haxe client.hxml` causes the segmentation fault. Which ocaml version do you use?

**Comment by andyli** [comment]
I just apt-get install ocaml. I am using ubuntu 16.04 x86_64.

**Comment by frabbit** [comment]
hmm, i'm currently out of ideas, the compiled haxe executable does segfault even when running without arguments, i have the same ocaml version

**Comment by frabbit** [comment]
it seems that `find_exe_in_paths` in nekotools only finds neko in /usr/bin when it's running as sudo, but why?

**Comment by frabbit** [comment]
my $PATH variable definitely contains folders which includes the neko executable.

**Comment by frabbit** [comment]
btw, it's funny that the compiler crashes with a segmentation fault when the neko installation is corrupt, even when i don't pass any arguments to the executable.

This is the `strace` output of a regular call of just `haxe`, you can see that various neko libraries are loaded even for this: https://gist.github.com/frabbit/467f7dd5481666f23cac9e4ac5b4be9e

**Comment by frabbit** [comment]
it seems that file_contents fails on the file `/usr/bin/neko` when running as user although it has the following permissions: rwxrwxrwx.

**Comment by frabbit** [comment]
i mean read permission should be enough

**Comment by frabbit** [comment]
that was a nightmare to debug ;)

**Comment by thoughton** [comment]
For anyone still banging their head against the `Neko_error(The bootable executable file was not found : neko)` exception (especially if like me you install all Homebrew to local folders), try changing/adding the following in your `.profile` (or equivalent):
```
export NEKOPATH="$HOME/local/lib/neko/":"$HOME/local/bin/"
```
(Note that it contains both a `lib` path and a `bin` path. And of course you may need to modify these paths to point to your own locations.)

Then open a new terminal and do a `brew reinstall haxe`. This worked for me.
