### ISSUE TITLE
python issue with UTF-8 characters

### ISSUE THREAD

**Issue by fponticelli** [HaxeFoundation/haxe#5217]
Given:

```haxe
class Main {
  static function main() {
    var s = "𩸽あëa";
    trace(s);
  }
}
```

The file compiles just fine in Haxe but the execution fails in Python with the following error: `SyntaxError: Non-ASCII character '\xf0'`

The solutions seems to be prefixing the generated file with `# -*- coding: utf-8 -*-` (it can be put after the haxe generated header). Another local solution is to prefix string literals with `u`.

**Comment by nadako** [comment]
Haxe generates code for Python 3, however you seem to be using Python 2 (since py3 doesn't have unicode literals and uses utf8 for sources by default, and thus doesn't need `-*- coding` comment).

**Comment by fponticelli** [comment]
I am not using Python 2:

```sh
python3 bin/python/tests.py
  File "bin/python/tests.py", line 22806
SyntaxError: Non-UTF-8 code starting with '\xe0' in file bin/python/tests.py on line 22806, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by nadako** [comment]
Hmm...

**Comment by nadako** [comment]
I can't reproduce this with the original given example (well, it fails to print on my windows console, but that's not related to code encoding). Please, open a new issue with something reproducible :-P
