### ISSUE TITLE
Using keywords as field names in anon obj

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5219]
This is mainly for externs.

I can create such object by wrapping the field with quotes
`var o = {"new":1};`

though the compiler doesn't like it. It ignores the keyword field:
`$type(o); // {}`

Would it even be possible to define field names with invalid haxe identifiers? (e.g. keywords, start with numbers, etc)

**Comment by nadako** [comment]
I believe there are several issues on that topic already (e.g. the `@:native` discussion and whatnot), but I'm not sure if this is a duplicate or not. Why does it ignore quoted keyword fields? What's going on here? :-)

**Comment by nadako** [comment]
Setting to 3.4 as it's not a regression

**Comment by kevinresol** [comment]
I believe the compiler ignores it because it won't get typed-checked anyway, because:

```haxe
var o = {"enum":1};
o.enum = 2;
```

fails with "Unexpected enum" in line 2 anyway. So typing `o` as `{enum:Int}` won't get any benefits.
That's what I am guessing how the compiler works.

So in order to make the typing meaningful, first of all the compiler should support field access with keywords. i.e. `o.enum = 2;` should compile.

At this point, I am not sure if that worth the change. Does anyone (except externs) really use keywords as field name?

**Comment by ncannasse** [comment]
As you guessed, while we allow such keyword identifier, we exclude them from typing for obvious reasons. We have no plan to allow `o.enum` access.
