### ISSUE TITLE
[lua] no visible label '_hx_continue' for <goto>

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5222]
I've tried to isolate the issue and create a minimal example replicating it, but unfortunately my efforts weren't successful ([gist](https://gist.github.com/azrafe7/83156bce722fc955676b917d2afa325b)).

The issue is visible by trying to run the tests of [this lib](https://github.com/azrafe7/hxPako) (ugly nested while/switch involved!).

It compiles fine, but running with lua 5.2.4 results in the message reported in the title.

I have no experience with lua, but from what I can see in the generated code, it seems that the `::_hx_continue::` label is put outside the `while` scope, so the compiler doesn't see it. I've also tried to patch it manually, but that didn't go anywhere.

Sorry for the poor report, but maybe you already know where the problem could be.

**Comment by jdonaldson** [comment]
I can repro, thanks for the heads up.

**Comment by jdonaldson** [comment]
There's a couple of layers of errors here... still working on it.

**Comment by jdonaldson** [comment]
This particular case should be fixed.  I also fixed an order of initialization issue with __init__ and static blocks.  Let me know if this helps.

**Comment by azrafe7** [comment]
Hey @jdonaldson, thanks for taking a look into it!

I was willing to test your fix on my end, but I'm having problems with the setup: can you guide me into how to correcly install lua 5.2 with pcre on windows (not familiar with lua and luarocks, sorry)? 

Currently I have 5.2.4 installed (just the minimal bin version - 4 files), and trying to download and launch luarocks' `install` results in 

`Note that the %APPDATA% element in the paths above is user specific and it MUST
be replaced by its actual value.
For the current user that value is: C:\Users\[Edited]\AppData\Roaming. `

Can you help me fix this?

(it would be great to have a single installer that takes care of all the depencies, but that's probably more on the lua people's side)

**Comment by azrafe7** [comment]
I've edited the previous post.

**Comment by jdonaldson** [comment]
Try to use [LuaDist](http://luadist.org/) to install lua and the required packages.  I updated the "Hello Lua" blog post with some of those details.

**Comment by azrafe7** [comment]
Thanks @jdonaldson!

I've managed to install pcre 20 minutes ago (through a lengthy process involving compiling it from source, and put the right files in the right places), and now it no longer complains about the original issue. \o/

But another problem popped up when running testAll.lua: `GenerateMain.hx:182: testAll.lua:14162: attempt to call upvalue 'error' (a string value)`. 

Am I correct in saying that `error` is a lua keyword and cannot be used as a var name?

**Comment by azrafe7** [comment]
I'm going to try if I can reduce it to a minimal example.

**Comment by azrafe7** [comment]
Ok, found a simple way to reproduce it (maybe not _exactly_ the same error but...).

Posted as a new issue (#5234).
