### ISSUE TITLE
[cpp] Compiler crash when processing big array

### ISSUE THREAD

**Issue by luboslenco** [HaxeFoundation/haxe#5223]
I am embedding a big array straight into source. For JS, everything works as expected. For CPP, the whole compiler goes to ground:

```
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```hx
// Haxe
class ConstData {
    // 16384 items
    public static var ltc_mat = [0.000200, - 0.000000, 1.000000, - 0.000000, 0.000504, ...];
}
```

```cpp
// Cpp
ltc_mat = ::Array_obj< Float >::__new(16384)->init(0,((Float)0.000200))->init(1,((Float)-0.000000))->init(2,((Float)1.000000))->init(3,((Float)-0.000000))->init(4,((Float)0.000504))->...
```

(For reference, complete array data: http://blog.selfshadow.com/sandbox/js/ltc_tables.js)

If there is no way around this, is there a preferred solution to handle this?

**Comment by hughsando** [comment]
This change fixes the problem when you have a big array of constant data, but not if you throw variables in there.
But I think constant data most likely, so I will call it fixed until someone reports a realistic case where it breaks.
