### ISSUE TITLE
Using does not work with @:forward abstracts to other abstracts

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#5231]
The following example:
```haxe
using Main;

class Main {
  static function main() {
    trace(getTest().doesItWork(getTest()));
  }

  public static function getTest():Test {
    return cast {};
  }
}

abstract Test2(Dynamic) {
}

@:forward
abstract Test(Test2) {
}

class Utils {
  public static function doesItWork(t:Test, t2:Test):Bool {
    return true;
  }
}
```

Fails with:
```
Main.hx:5: characters 10-30 : Test2 has no field doesItWork
```

This works if either:
 * `Test` is not defined with `@:forward`
 * `Test`'s underlying type is not an abstract (if it is e.g. a class)
 * Strangely, if `doesItWork` first argument is of type `Test2`

**Comment by Simn** [comment]
@jcward: Is this the case we discussed recently?

**Comment by jcward** [comment]
@simn, no my issue #5097 is the interoperability of @:forward and @:resolve.

**Comment by Simn** [comment]
Right, thanks, I remember now!
