### ISSUE TITLE
[js] Problem with prefixes on fullscreen functions.

### ISSUE THREAD

**Issue by Horsetopus** [HaxeFoundation/haxe#5233]
Hi,

This code builds and should work, but the prefixes don't seam to be added:
```
if ( Browser.document.fullscreenElement == null )
	Browser.document.documentElement.requestFullscreen();
else
	Browser.document.exitFullscreen();
```
IT doesn't work on Chrome or Firefox, other browser untested.

This works on Chrome:
```
untyped if ( Browser.document.webkitFullscreenElement == null )
	untyped Browser.document.documentElement.webkitRequestFullscreen();
else
	untyped Browser.document.webkitExitFullscreen();
```

**Comment by andyli** [comment]
Haxe doesn't provide shim to these properties. You need to deal with that on your own.
The properties exist in the Haxe extern merely means they are in the spec, it doesn't guarantee the runtime (browser) will support them properly.
