### ISSUE TITLE
 Unrecognized pattern regression

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#5236]
I remember this works in 3.1.3,  Note: all parameters are constant

`src/Main.hx:10: characters 8-20 : Unrecognized pattern: addr(10, 10)`

``` haxe
class Main {
    static function main() {
        var a = addr(10, 10);
        switch (a) {
            case addr(10, 10):
            case addr(1, 1):
            default:
        }
    }
    static inline function addr(x:Int, y:Int):Int{
        return  x | (y << 7);
    }
}
```

**Comment by nadako** [comment]
Well, technically, `addr(...)` is a function call, so it's not a constant in general case. And it's like this in 3.2 too (http://try.haxe.org/#a6c3D), but I'm not 100% sure if it shouldn't work, so I'm gonna leave this for @Simn to decide.

**Comment by Simn** [comment]
I'm not sure about this either, I'm a bit scared of the consequences if we allow arbitrary typing like that. I think I prefer to leave it as-is for now, given that it doesn't work in 3.2 anyway.

**Comment by ubald** [comment]
But shouldn't the result be inlined?
I have a similar issue with 3.3.0-rc1 concatenated regarding inline strings used as patterns:
```haxe
class Test {
    static inline public var A = 'a';
    static inline public var AB = A + 'b';
    
    static function main() {
        var t = 'a';
        switch (t) {
            case A:
            case AB:
            default:
        }
    }
}
```
I get an ```Unrecognized pattern``` error.

**Comment by Simn** [comment]
Looking at this again, I don't think we should support arbitrary typing in patterns.
