### ISSUE TITLE
[cpp] cpp.Pointer array access generating Dynamic calls (Haxe 3.3)

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/haxe#5239]
cpp.Pointer array access seems to now generate Dynamic calls (__SetItem, __GetItem), of which there is no implementation in C++. (edit: expected behavior would be to use static calls, like Haxe 3.2 does)

Tested with a development build of Haxe from May 14th (haxe_2016-05-14_development_97f5882.tar.gz), and https://github.com/HaxeFoundation/hxcpp/commit/89d48ed1341c7a41654205166a939dcee5997c79

Sample:

```haxe
package;

class Main {
	public static function main():Void {
		var array = new Array<cpp.UInt32>();
		array.push(1);
		var ptr = cpp.Pointer.arrayElem(array, 0);
		ptr[0] = 2;
		Sys.println (ptr[0]);
	}
}
```

Output:

```
./src/Main.cpp(35) : error C2039: '__SetItem' : is not a member of 'cpp::Pointer<T>'
        with
        [
            T=unsigned int
        ]
./src/Main.cpp(36) : error C2039: '__GetItem' : is not a member of 'cpp::Pointer<T>'
        with
        [
            T=unsigned int
        ]
```

**Comment by nadako** [comment]
By description I assume it's a regression, so I added the tags.
