### ISSUE TITLE
Makefile.win overriding package_bin

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5240]
It gives a warning everytime, because you're usually not allowed to override a Makefile rule, and after searching I have not found a way to disable the warning.

@andyli could we instead use package_win ? I'm not sure for which automated process it's required

**Comment by andyli** [comment]
It's funny that I didn't find a proper way of overriding Makefile rules either. But just a moment ago I found the solution at http://stackoverflow.com/a/1645332/267998

**Comment by ncannasse** [comment]
It seems that in that case it runs both rules (the old one + the overridden one) is that ok?

**Comment by andyli** [comment]
Umm... indeed. ddf9af1b9829925b6d8e0d7805b5ccc29b133ad7 should do the trick.
