### ISSUE TITLE
[lua] too many local variables

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5243]
Having a class with more than 110 functions (inherited or not) results in the error reported in the title. Searching online on what might be the cause lead me to http://lua-users.org/lists/lua-l/2015-04/msg00376.html.

To repro (a bit convoluted maybe):

`TestBigClass.hx`

``` haxe
class TestBigClass {
    static public function main() {
        var bigClass = new BigClass();
    }
}

@:build(TypeBuildingMacro.build(120)) // add 120 dummy functions to BigClass
class BigClass {
    public function new() { }
}
```

`TypeBuildingMacro.hx`

``` haxe
import haxe.macro.Context;
import haxe.macro.Expr;

class TypeBuildingMacro {
    macro static public function build(count:Int):Array<Field> {
        var fields = Context.getBuildFields();
        for (i in 0...count) {
            var newField = {
                name: "function" + i,
                doc: null,
                meta: [],
                access: [APublic],
                kind: FFun({
                    args: [],
                    expr: macro null,
                    ret: null
                }),
                pos: Context.currentPos()
            };
            fields.push(newField);
        }
        return fields;
    }
}
```

(for me - on win with lua 5.2.4 - the limit is around 118 before I get an error)

This can also be reproduced by running the tests for the polygonal-ds lib (if I recall correctly).

**Comment by azrafe7** [comment]
The link about lua... I meant another one but can't find it right now.

**Comment by jdonaldson** [comment]
This is a nasty one, and I don't have a great solution for it.  Lua has a hard limit of 200 variables per scope, and I'm guessing you're hitting some form of that.

There's not really a way to completely eradicate this problem, but there might be some tweaks that can give more headroom.  I'm still investigating.

FWIW I regularly hit this limit with inline abstracts.  I had to change several of them to non-inline in order to keep certain operations from generating dozens of new variables.

**Comment by azrafe7** [comment]
I've found this: http://stackoverflow.com/questions/22433839/how-to-unpack-table-into-function-arguments

Do you think it could work for this case, i.e. using a temp table to store the values and then unpack it when calling `_hx_anon(unpack(tmpTable))`?

**Comment by jdonaldson** [comment]
I'm not sure about the unpack approach.  However, it would be possible for the compiler to emit variables as table fields instead.  That would be a fairly big performance hit, but maybe it would be better than other alternatives in certain cases.

The other alternative would be to count variable declarations, and switch over to table references once the compiler has seen more than ~100 in the current scope.  There's no guarantee that the compiler even sees all variable declarations (some may be declared through magic, etc.).  Also, it'll be messy to track which form a given variable needs to take.  But, it may be the best tradeoff.

**Comment by azrafe7** [comment]
Don't know much about lua internals, but your alternative seems a reasonable compromise (maybe also output a warning at compile time when such action is necessary).

**Comment by frabbit** [comment]
@jdonaldson this is a milestone 3.3 issue, is this still relevant for a release?

**Comment by jdonaldson** [comment]
No, this falls too far down my list of priorities.

**Comment by jdonaldson** [comment]
Side note here:  This is a problem that surfaces at lua script _parse_ time, not _run_ time.  Lua will not even execute the script until the variable count is reduced.  It's just a good idea to reduce the variable count in that situation, regardless of how I end up working around this.  The workaround is going to involve aliasing local variables to table values, and the lookup time between the two is drastically different.

**Comment by jdonaldson** [comment]
quick update : I've pushed a change that should address this particular case.  We run into this issue a lot faster with prototype fields, since I was declaring them all inside a wrapper function.  Now they're declared as plain table field declarations, so we no longer hit a limit.

Note that the variable limit issue can still occur, but it's much less likely to happen now.  I'll close this and reopen once we have a concrete case where that is a problem.

**Comment by elnabo** [comment]
We have this problem when we run the tests of [json2object ](https://github.com/elnabo/json2object) on lua with the latests Haxe.

`lua: testout/test.lua:329: too many local variables (limit is 200) in main function near '='`

At first we just removed some tests case but with every new features this problem regulary shows up.
