### ISSUE TITLE
[lua] Sys.sleep(): command not recognized (win 7)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5244]
Calling `Sys.sleep()` on win 7 results in:

`"ping" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.`

(Italian for what amounts to `"ping" is not recognized as a valid command`)

It can be just a problem with `Os.execute()` (as running `ping` in the shell works fine for me) but, in case it's worth using them, I've found these workarounds: http://lua-users.org/wiki/SleepFunction.

**Comment by jdonaldson** [comment]
I don't think windows 7 has a ping method, or at least one that's available to lua.

I'm debating whether to try and keep adding os specific hacks for this, or replace the whole thing with another required extern.

**Comment by frabbit** [comment]
@jdonaldson this is a milestone 3.3 issue, is this still relevant for a release?

**Comment by jdonaldson** [comment]
This should get fixed with some pending sys module work.

**Comment by jdonaldson** [comment]
This is fixed with the latest sys updates.
