### ISSUE TITLE
[lua] read file after writing to it

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5245]
Reading a file after it has been written (programmatically) results in 0 bytes:
```haxe
    static var ouputFileName:String = "out.dbg";
	
    static public function main() {
 
        var currentDir = Sys.getCwd();
        trace('cwd: $currentDir');
        
        var ouputFilePath = Path.join([currentDir, ouputFileName]);
        trace('ouputFile: ${ouputFilePath.toString()}');

        var bytes = Bytes.ofString("bytes\n");
		
        var output = File.write(Path.join([currentDir, ouputFileName]));
        output.writeString("string\n");
        output.write(bytes);
        output.close();

        var exists = FileSystem.exists(ouputFilePath.toString());
        trace('exists: $exists');
        
        var input = File.read(ouputFilePath);
        var bytes = input.readAll();
        trace(bytes.length);     // <- 0
        trace(bytes.toString());
        input.close();
    }    
```

**Comment by jdonaldson** [comment]
FWIW this is part of that same readBytes problem.  I've got a branch with a fix across the base haxe.io.Input under test right now.

**Comment by azrafe7** [comment]
Let me clarify: with the temp fixes the file gets correctly written to disk, but reading it back gives 0 bytes. Maybe a filehandle issue?!

**Comment by jdonaldson** [comment]
Nah, it's just that reading a file relies on readbytes at the moment.  Reading anything fails at the moment.  I believe I have a good fix, but I'm going to have @Simn look at it once it passes the test suite.

**Comment by azrafe7** [comment]
Ok. I'll wait for it then.

2016-05-19 23:49 GMT+02:00 Justin Donaldson <notifications@github.com>:

**Comment by jdonaldson** [comment]
Should be live now, your example passes for me.  

I'll continue trying to add better haxe level support for sys/process/io.

**Comment by jdonaldson** [comment]
I see one more thing to fix...

**Comment by jdonaldson** [comment]
Ok, we're still sorting out some issues on Input.  I'm fixing this in lua FileInput for now.  Check this when you get a chance.

**Comment by azrafe7** [comment]
Great! I'l probably test it further tomorrow with the latest changes.

**Comment by azrafe7** [comment]
Yep, this works now. Feel free to close it.
