### ISSUE TITLE
C# match + if() fails on latest

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#5247]
This is a regression

**Comment by waneck** [comment]
This is not a regression. And actually comes from the pattern matcher

@Simn I really wish the pattern matched didn't generate expressions like `if (Type.enumIndex(e) == 3)`, and instead would generate `e == SomeEnum`.
This is much cleaner and allows the underlying external dependencies (dll, jar, etc) to change without Haxe having to know about this

**Comment by Simn** [comment]
We decided to use direct matching on extern enums that do not have `@:hxGen` metadata.

**Comment by Simn** [comment]
I'm reluctant to make this change for 3.3, is it okay to move it to 3.4?
