### ISSUE TITLE
[lua] bind/closure issue

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5248]
This one took a bit to find out and isolate in the original codebase, as the big closures obj in that case would hang on printing and I wasn't even expecting to be it since the data passed around was a big object too.

Code:
```haxe
class Bind {

	var processData:Array<Int>->Void;
	
	static public function main() {
		new Bind();
    }
	
	function new():Void {
		var arr = [0, 1, 2];
		trace(arr);
		this.processData = _processData;
		processData(arr);
	}

	function _processData(arr:Array<Int>):Void {
		trace(arr.length);
		trace(arr);
	}
}
```
Expected:
```
Bind.hx:11: [0,1,2]
Bind.hx:17: 3
Bind.hx:18: [0,1,2]
```
Actual result:
```
Bind.hx:11: [0,1,2]
Bind.hx:17: null
Bind.hx:18: { hx__closures__ : { <function> : <function> }, processData : <function> }
```

Other targets seem to be fine.

**Comment by jdonaldson** [comment]
There's a lot of nastiness surrounding the binding of instance functions.  Try it again, I just pushed a fix and a test for this issue.

**Comment by jdonaldson** [comment]
here's another one to try... I think this is the last "easy" fix for a problem you found.  The rest will require some experimentation.

**Comment by azrafe7** [comment]
Ah, forgot to reply about this: tested and working.
