### ISSUE TITLE
[C#] cs.Internal.Function.Equals throws Exception if argument is not a Closure?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5251]
I don't know why this function is using unsafe cast(which should be impossible on C#). Even if you try, compiler just generates normal cast expression.
Changing arg type to Closure from Object seemed to have fixed this. Probably because passing non-Closure make "as" cast fail?

https://github.com/vroad/haxe/commit/dcea79848517d354396571c0d91f3b87319ab0dd

**Comment by nadako** [comment]
I think `Equals` should still receive `object` (aka `Dynamic`) as its first argument, however its implementation should indeed use `as` cast instead of failing in a safe-cast.

**Comment by nadako** [comment]
cc @waneck
