### ISSUE TITLE
writing Infinity to a BytesBuffer

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/haxe#5252]
Here is a test case : 
http://try.haxe.org/#988f0

I create a BytesBuffer, write `Math.POSITIVE_INFINITY` to it, 
then get its bytes, read the first double, 
which I would expect to be equal to `Math.POSITIVE_INFINITY`.
It behaves correctly in Flash, but fails in JS (the value is just 0).

**Comment by ncannasse** [comment]
I correctly get true on Chrome/Wndows. Which browser are you testing with?

**Comment by clemos** [comment]
I'm on Chrome on Ubuntu 64. The test also fails on nodejs.
It also fails on Chrome / Windows XP (tested on Browserstack).
The link I gave defaults to SWF, which works. Here is a JS link:
http://try.haxe.org/#06368

**Comment by nadako** [comment]
Both try.haxe.org example on JS and latest haxe on node.js fails return false for me.

**Comment by nadako** [comment]
Not a regression, so I'm gonna tag this for 3.4. If using some dark arts we'll be able to deal with 3.3 issues in time, we might as well look into this one.

**Comment by clemos** [comment]
FYI, I have the following workaround, using `Bytes`, in my code : 
```haxe
// reads a double correctly from an Input
				var low = input.readInt32();
				var high = input.readInt32();
				var b = haxe.io.Bytes.alloc(8);
				b.setInt32(0,low);
				b.setInt32(4,high);
				var double = b.getDouble(0);
// write a double correctly into an output
				var b = haxe.io.Bytes.alloc(8);
				b.setDouble(0,double);
				output.writeInt32(b.getInt32(0));
				output.writeInt32(b.getInt32(4));
```
