### ISSUE TITLE
[C#] Optimizing Bytes on C#

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5254]
Current bytes implementations is slow at converting floating-point values, We can make this much faster by using BitConverter and unsafe code(if available). Unsafe is much faster than BitConverter, but needs changes to project settings.
I also think that we should use System.Buffer.BlockCopy for blittng. It does less amount of checks than ArrayCopy, so it runs slightly faster if you call this method many times.

Should we check if current system is running on little-endian computer every time we call these methods? I want to skip this check for performance, if possible. Or, is it possible to add a haxedef that skips this check?

I have a test implementation in my fork.

Source code of BlockCopy and ArrayCopy:
https://github.com/dotnet/coreclr/blob/9a67ab7affc527168578a6749410c64ec3233f55/src/vm/comutilnative.cpp#L1420-L1423
https://github.com/dotnet/coreclr/blob/ee683a09634c967240bd63b3c925d6a99e0ac014/src/classlibnative/bcltype/arraynative.cpp#L999

My Bytes implementation:
https://github.com/vroad/haxe/blob/edd215fa903f57fe798f6957b23a9b97def779be/std/haxe/io/Bytes.hx

**Comment by ncannasse** [comment]
Could you instead submit a pull request?

**Comment by vroad** [comment]
Created a pull request. https://github.com/HaxeFoundation/haxe/pull/5259
