### ISSUE TITLE
@:generic and typedefs don't work together

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#5255]
The following example:

``` haxe
class Main {
  static function main() {
    TestImpl.test(1);
  }
}
```

`TestImpl.hx`:

``` haxe
typedef TestImpl<T> = TestImpl_<T>;

class TestImpl_<T> {
  @:generic public static function test<T>(arg:T){
    trace('works');
  }
}
```

Fails with:

```
Main.hx:3: characters 4-20 : Type not found : TestImpl_
```

On latest Haxe. If I take the typedef off, it works again. I think this is a regression

**Comment by nadako** [comment]
Does adding the new `@:eager` thing helps?

**Comment by Simn** [comment]
This is _not_ a regression.

**Comment by ibilon** [comment]
Think I have a variation of that error, or at least something very similar, with the following code https://gist.github.com/ibilon/e1f2e530449e2a52f24fb70a343fc47f

It finds the class but says `Test.hx:6: characters 2-11 : TestImpl does not have a constructor`.

Adding the `@:eager` to the typedef makes it work.
