### ISSUE TITLE
[C#] Cannot compile classes with static UInt fields

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5258]
This code compiles in Haxe, but fails to compile with Visual C#, because uv becomes -1 in C# source and static fields will not be wrapped in unchecked block.
Why does this become -1 in C# source? Is Haxe storing this value as a signed integer?

``` hx
class Test {
    static var uv:UInt = 0xFFFFFFFF;

    static function main() {
        trace(uv);
    }
}
```

**Comment by ncannasse** [comment]
-1 and 0xFFFFFFFF are the same in-memory value, I guess it's just a problem of printing the value correctly.

**Comment by wiggin77** [comment]
Also, see here (related):  https://github.com/HaxeFoundation/haxe/issues/4870

**Comment by nadako** [comment]
This compiles for me on the latest haxe to:
```cs
global::Main.uv = ((uint) (-1) );
```
And running it prints:
```
Main.hx:5: 4294967295
```

So the only issue is that it generated as `-1` in the C# code which could be improved for the sake of beauty, but it's a minor one, so I'm setting this to 3.4.

**Comment by vroad** [comment]
@nadako I've found that `0xFFFFFFFF` is generated as `-1` on js as well.

**Comment by vroad** [comment]
Doesn't this cause strange behavior? For example, this expression gives no warnings, but the result is different from what people usually expect, as `0xFFFFFFFF` becomes `-1`. Or is this just not guaranteed to work?

```hx
class Main {

	static function main () {
		
		var a:Float = Math.random() * 0xFFFFFFFF;
		trace (a);
		
	}
	
}
```

**Comment by vroad** [comment]
You'll get the correct result on all targets if you assign UInt to some var first.

```hx
class Test {
    
    static function main () {

        var b:UInt = 0xffffffff;
        var a:Float = Math.random() * b;
        trace (a);

    }

}
```

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
