### ISSUE TITLE
[lua] bitwise operators issue

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5265]
I've been able to reproduce this using xor, but probably other operators are affected too:

``` haxe
    static function main():Void {
        var expected = -1;
        var actual = calc(0);
        trace(repr(actual) + " equals " + repr(expected) + " ? " + (actual == expected));
    }

    static function calc(i:Int):Int {
        return i ^ 0xFFFFFFFF;
    }

    static function repr(i:Int):String {
        return "(0x" + StringTools.hex(i) + ") " + i;
    }
```

Output:
`(0xFFFFFFFF) 4294967295 equals (0xFFFFFFFF) -1 ? false`

This is probaby related to lua not having a proper Int (as I recall @jdonaldson mentioning it somewhere).

**Comment by jdonaldson** [comment]
yeah, most likely.  Overflow behavior on base Int type is undefined.  Can you try with Int32?

**Comment by azrafe7** [comment]
Tried with Int32, and actually the posted example works with that. But f.e. this doesn't:
```haxe
	static function main():Void {
		var expected:Int32 = 0x80000000;
		var actual:Int32 = calc2(0x80000000);
		trace(repr(actual) + " equals " + repr(expected) + " ? " + (actual == expected));
	}
	
	static function calc2(i:Int32):Int32 {
		return i >> 32;
	}
```
With:
`(0xFFFFFFFF) -1 equals (0x80000000) -2147483648 ? false`

Anyway I first stumbled into this while using the `format` lib (but applies to other code/libs too).

**Comment by azrafe7** [comment]
Oh wait... testing with other targets my 2nd example gives mixed results.
 - should the sign be extended or not? 
 - what would the expected output be?

Running more tests now, I'll report back.

**Comment by azrafe7** [comment]
Ok, it seems that the 2nd example is undefined behaviour (and I'm fine with it). 

Next logical step would be to try whether changing Int to Int32 in `format` fixes it (a bit impractical though, but maybe I'll experiment with it tomorrow).

**Comment by ntrf** [comment]
Why are you shifting by 32 bits? You should shift by 31 if you wanted to extend sign.

**Comment by jdonaldson** [comment]
shifting 32 bits on a 32 bit integer is usually unspecified behavior (in C anyways).  I can adjust the int32 version so that it matches, but I still wouldn't rely on this behavior in your program logic.

**Comment by azrafe7** [comment]
To clear up on this: we agree shifting 32 bits is undefined behaviour.

However these two fail only in lua for Int, but are ok using Int32:
```
  [FAIL] test: [ Int ]  0 ^ 0xFFFFFFFF
         expected: (0xFFFFFFFF) -1  vs actual: (0xFFFFFFFF) 4294967295
  [ OK ] test: [Int32] 0 ^ 0xFFFFFFFF
         expected: (0xFFFFFFFF) -1  vs actual: (0xFFFFFFFF) -1
  [FAIL] test: [ Int ]  0x80000000 >> 31
         expected: (0xFFFFFFFF) -1  vs actual: (0xFFFFFFFF) 4294967295
  [ OK ] test: [Int32]  0x80000000 >> 31
         expected: (0xFFFFFFFF) -1  vs actual: (0xFFFFFFFF) -1
```

(swf, neko, cpp, js, cs, java, python and php work correctly even with Int)

[tests gist](https://gist.github.com/azrafe7/4641ba524286afc3419b769fc7e504d7)

**Comment by frabbit** [comment]
@jdonaldson this is a milestone 3.3 issue, is this still relevant for a release?

**Comment by jdonaldson** [comment]
This is not really a bug, if we consider Int to be "platform precision".   

Making lua Int behave like other platforms means taking a runtime hit on most relevant operations. Not sure I want to do that.  I might add a flag or something as an additional feature down the road.

**Comment by jdonaldson** [comment]
Closing this for now, I consider it working as designed.
