### ISSUE TITLE
Comparison of two types is slow on cs

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5266]
Using profiler, I found that comparison of two types on cs is slower than on js, but can this be fixed in the future?
On js, this is implemented with just "==" so it's fast.

https://github.com/HaxeFoundation/haxe/blob/ec3afeec422559833f74cf244fa37843433c0146/std/cs/internal/Runtime.hx#L772

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
