### ISSUE TITLE
Can't put a build macro file inside js package

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5267]
The following code:

```haxe
// Main.hx
@:build(js.Macro.build())
class Main {
	public static function main() {
		
	}
}

// js/Macro.hx
package js;

class Macro {
	public static function build() {
		return null;
	}
}
```

fails with `You cannot access the js package while in a macro (for js.Macro)`

We can use other packages of course but that somehow breaks module organization (related files are forced to locate in separate places). There are [quite](https://github.com/HaxeFoundation/hxnodejs/blob/master/src/_hxnodejs/VersionWarning.hx) [a few](https://github.com/clemos/haxe-js-kit/blob/develop/npm/Package.hx) [examples](https://github.com/clemos/haxe-js-kit/blob/develop/util/Mongoose.hx) out there.

I am not sure, but seems it worth a discussion about relaxing the restriction.

**Comment by ncannasse** [comment]
It's a lot more easy to have this error than `js.Browser not defined` and wondering why for hours until you understand it's some macro code. I think the per-platform package restriction makes it much more easy to separate code.

**Comment by back2dos** [comment]
That chain of arguments is not conclusive. Adding `@:require(js)` to `js.Browser` would give you the same error and solve this problem at the same time.
