### ISSUE TITLE
[lua] Problem with arg macro

### ISSUE THREAD

**Issue by pperehozhih** [HaxeFoundation/haxe#5272]
I generate test class with two files
Test.hx
<pre>
import src.Point;
class MyClass 
{
    public var names = ["ted", "fred", "tim"];
    public function new(){}
    public function iterator ()
    {
        return names.iterator();
    }
}

class Test
{
    public function main ()
    {
        var m = new MyClass();
        for (i in m)
            trace(i); // ted, fred, tim
        var p = new Point(-1, 65);
        trace(p.toString());
    }
}
</pre>
and src/Point.hx
<pre>
package src;
class Point {
  var x : Int;
  var y : Int;
  public function new(x,y) {
    this.x = x;
    this.y = y;
  }
  public function toString() {
    return "Point("+x+","+y+")";
  }
}
</pre>

and run haxe from terminal
<pre>
haxe Test -lua test.lua --macro "include('src')"
</pre>
generated test.lua is not valid
<pre>
> lua test.lua 
lua: test.lua:2: attempt to call global '_hx_o' (a nil value)
stack traceback:
	test.lua:2: in function <test.lua:2>
	test.lua:2: in main chunk
	[C]: in ?
</pre>
head of invalid file
<pre>
local _hxClasses = {}
Int = (function() _hxClasses.Int = _hx_o({__fields__={__name__=true},__name__={"Int"}}); return _hxClasses.Int end)();
....
</pre>
lua version - Lua 5.2.2  Copyright (C) 1994-2013 Lua.org, PUC-Rio
If run haxe without arg macro, haxe generate valid file
<pre>
haxe Test -lua test.lua
</pre>

haxe build from source, last commit -
f57fcdbbbe0de40bd6daf4d03da5d6a21d4d364b
<pre>
Author: Simon Krajewski <simon@haxe.org>
Date:   Mon May 23 14:19:46 2016 +0200

    [python] do not recurse into branches when determining initialized fields (closes #5053)
</pre>

**Comment by jdonaldson** [comment]
Looks like I'm not getting the order of includes quite right.  I've adjusted things on the latest commit, and can get your example to pass.  Give it a shot when you get a chance.

**Comment by pperehozhih** [comment]
Сommit 84d9a626bfe1ffe867aa2af86776d5bb4da227c3 solved the problem, Thanks
