### ISSUE TITLE
Switching with "case null"

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5274]
(First of all, I have read through the changes in https://github.com/HaxeFoundation/haxe/pull/4940)

```haxe
class Main {
	public static function main() {
		switch getString() {
			case null: trace('null');
			case _.split(",") => [s1, s2]: trace(s1, s2);
			default: trace('default');
		}
	}
	
	static function getString():String return null;
}
```

This code fails with `null has no field split`, because the pattern `_.split(',')` is eagerly evaluated. Is it possible to treat null as a special case such that it does a null check first, before evaluating the following statements?

**Comment by Simn** [comment]
I'll have to check that.

**Comment by Simn** [comment]
My initial idea is to come up with a way to make the check lazy. Right now we get this JS output:

```js
	var _g = Main.getString();
	var _hx_tmp = _g.split(",");
	if(_g == null) {

	} else if(_hx_tmp.length == 2) {

	} else {

	}
```

What we could do instead is this:

```js
	var _g = Main.getString();
	var _hx_tmp;
	if(_g == null) {

	} else if((_hx_tmp =  = _g.split(",")).length == 2) {

	} else {

	}
```

Makes sense?
