### ISSUE TITLE
[C#] Haxe always uses slowCallField to call overridden functions with closure

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5278]
This is the code generated from lime's code. I noticed that slowCallField is often used when invoking methods of this class dynamically, but is this really necessary? In what situations are they needed?
Isn't this unnecessary when arguments are known at compile time?

For exmple, `onPreloadComplete` is always called with slowCallField when invoking dynamically.
https://github.com/vroad/lime/blob/78bf85b7665cdcf1f09319ae22b55f58e8072833/lime/app/Application.hx#L449

Why are many methods getting called with slowCallField? Are these any different from other functions like `__onJoystickConnect`?

https://gist.github.com/vroad/b8ab43ce5d1b5110fadc28a3b58eb50a#file-applicationmain-cs-L1719

**Comment by vroad** [comment]
Looks like Haxe generates `slowCallField` calls whenever you try to call overridden methods via `haxe.lang.Closure` class, but why is this needed? Could somebody explain that to me?

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
