### ISSUE TITLE
[C#] Is it possible to remove double parameters from Closure?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5280]
C# target often generates code like this for closure. To avoid boxing when passing numeric arguments, perhaps? But is that really faster?

In here, NDLLFunction.Call1 actually takes arg1 as object to accept any type of argument.

https://github.com/vroad/lime/blob/fb2a93165a43f7b8f8b07a14d79c98a65a6cfa69/templates/cs/src/cs/ndll/NDLLFunction.cs#L181

Converting argument to double is redundant in this case, so I want to turn it off if it's possible. This will also disallow you to pass integer argument as it is. You don't lose any information when converting from Int32, though.

``` cs
#pragma warning disable 109, 114, 219, 429, 168, 162
namespace lime.system {
    public class CSFunctionLoader_load_37__Fun : global::haxe.lang.Function {

        public CSFunctionLoader_load_37__Fun(global::cs.ndll.NDLLFunction func1) : base(1, 0) {
            this.func1 = func1;
        }


        public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
            object arg1 = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
            return this.func1.Call1(arg1);
        }


        public global::cs.ndll.NDLLFunction func1;

    }
}
```

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
