### ISSUE TITLE
feature request: string concatenation of constants

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#5282]
same as math expressions, it make the output look cleaner

``` haxe
class Main{
    static inline var PREF = "#";
    static function main() {
        trace(PREF + "foo");
    }
}
```

js output:

``` js
console.log("#" + "foo");
```

but i would like to get:

``` js
console.log("#foo");
```

**Comment by kevinresol** [comment]
Check out the discussions here https://github.com/HaxeFoundation/haxe/issues/4706

**Comment by R32** [comment]
Well, I just hope that can only be applied to JavaScript

**Comment by Simn** [comment]
#4706
