### ISSUE TITLE
babylonhx mac build problem ( ExternalBuildToolExecution Build\ Haxe )

### ISSUE THREAD

**Issue by gregorycollette** [HaxeFoundation/haxe#5285]
Hi,
i am trying BabylonHx (http://babylonhx.gamestudiohx.com/) but i got a build error on Mac

I tried to install Haxe 3.2.1 and 3.2.0 (manually) versions

It works great with:
sudo haxelib run lime test project.xml html5 

but fails with:
sudo haxelib run lime test project.xml ios 

I use:
Mac El capitan 10.11.5
Xcode 7.3.1

haxelib list
actuate: [1.8.6]
hxcpp: [3.3.47]
lime-samples: [2.6.0]
lime: [2.9.1]
poly2trihx: [0.1.4]

I appreciate your help.

Please find my log:
 

sudo haxelib run lime test project.xml ios 

Build settings from command line:

    PLATFORM_NAME = iphoneos

    SDKROOT = iphoneos9.3

 

=== BUILD LEGACY TARGET Build Haxe OF PROJECT BabylonHx_Lime WITH CONFIGURATION Release ===

 

Check dependencies

 

ExternalBuildToolExecution Build\ Haxe

    cd /Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/BabylonHx_Lime/haxe

    export ACTION=

    export ALTERNATE_GROUP=wheel

    export ALTERNATE_MODE=u+w,go-w,a+rX

    export ALTERNATE_OWNER=root

    export ALWAYS_SEARCH_USER_PATHS=NO

    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer

    export APPLE_INTERNAL_DIR=/AppleInternal

    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation

    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library

    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools

    export APPLICATION_EXTENSION_API_ONLY=NO

    export APPLY_RULES_IN_COPY_FILES=NO

    export ARCHS="armv7 arm64"

    export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"

    export BITCODE_GENERATION_MODE=marker

    export BUILD_ACTIVE_RESOURCES_ONLY=NO

    export BUILD_COMPONENTS="headers build"

    export BUILD_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export BUILD_ROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export BUILD_STYLE=

    export BUILD_VARIANTS=normal

    export BUILT_PRODUCTS_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-iphoneos

    export CACHE_ROOT=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode

    export CLANG_CXX_LANGUAGE_STANDARD=gnu++0x

    export CLANG_ENABLE_OBJC_ARC=YES

    export CLANG_MODULES_BUILD_SESSION_FILE=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/org.llvm.clang/ModuleCache/Session.modulevalidation

    export CLANG_WARN__DUPLICATE_METHOD_MATCH=YES

    export CLASS_FILE_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/JavaClasses"

    export CLONE_HEADERS=NO

    export CODE_SIGNING_ALLOWED=NO

    export CODE_SIGN_IDENTITY="iPhone Developer"

    export COLOR_DIAGNOSTICS=YES

    export CONFIGURATION=Release

    export CONFIGURATION_BUILD_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-iphoneos

    export CONFIGURATION_TEMP_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos

    export COPYING_PRESERVES_HFS_DATA=NO

    export COPY_HEADERS_RUN_UNIFDEF=NO

    export COPY_PHASE_STRIP=YES

    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO

    export DEAD_CODE_STRIPPING=YES

    export DEBUGGING_SYMBOLS=YES

    export DEBUG_INFORMATION_FORMAT=dwarf-with-dsym

    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0

    export DEFAULT_KEXT_INSTALL_PATH=/System/Library/Extensions

    export DEFINES_MODULE=NO

    export DEPLOYMENT_LOCATION=NO

    export DEPLOYMENT_POSTPROCESSING=NO

    export DERIVED_FILES_DIR=

    export DERIVED_FILE_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/DerivedSources"

    export DERIVED_SOURCES_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/DerivedSources"

    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications

    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin

    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer

    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks

    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks

    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library

    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs

    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools

    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr

    export DEVELOPMENT_LANGUAGE=English

    export DO_HEADER_SCANNING_IN_JAM=NO

    export DSTROOT=/tmp/BabylonHx_Lime.dst

    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain

    export DWARF_DSYM_FILE_NAME=.dSYM

    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO

    export DWARF_DSYM_FOLDER_PATH=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-iphoneos

    export EMBEDDED_PROFILE_NAME=embedded.mobileprovision

    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO

    export ENABLE_BITCODE=YES

    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES

    export ENABLE_HEADER_DEPENDENCIES=YES

    export ENABLE_ON_DEMAND_RESOURCES=NO

    export ENABLE_TESTABILITY=NO

    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"

    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"

    export FILE_LIST="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/Objects/LinkFileList"

    export FRAMEWORK_VERSION=A

    export GCC3_VERSION=3.3

    export GCC_C_LANGUAGE_STANDARD=gnu99

    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0

    export GCC_WARN_ABOUT_RETURN_TYPE=YES

    export GCC_WARN_UNINITIALIZED_AUTOS=YES

    export GCC_WARN_UNUSED_VARIABLE=YES

    export GENERATE_MASTER_OBJECT_FILE=NO

    export GENERATE_PKGINFO_FILE=NO

    export GENERATE_PROFILING_CODE=NO

    export GID=0

    export GROUP=wheel

    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES

    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES

    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES

    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES

    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES

    export HEADERMAP_USES_VFS=NO

    export HIDE_BITCODE_SYMBOLS=YES

    export HOME=/var/root

    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES

    export INFOPLIST_OUTPUT_FORMAT=binary

    export INFOPLIST_PREPROCESS=NO

    export INSTALL_DIR=/tmp/BabylonHx_Lime.dst

    export INSTALL_GROUP=wheel

    export INSTALL_MODE_FLAG=u+w,go-w,a+rX

    export INSTALL_OWNER=root

    export INSTALL_ROOT=/tmp/BabylonHx_Lime.dst

    export IPHONEOS_DEPLOYMENT_TARGET=5.1.1

    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub

    export JAVA_ARCHIVE_CLASSES=YES

    export JAVA_ARCHIVE_TYPE=JAR

    export JAVA_COMPILER=/usr/bin/javac

    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources

    export JAVA_JAR_FLAGS=cv

    export JAVA_SOURCE_SUBDIR=.

    export JAVA_USE_DEPENDENCIES=YES

    export JAVA_ZIP_FLAGS=-urg

    export KEEP_PRIVATE_EXTERNS=NO

    export LD_DEPENDENCY_INFO_FILE=//_dependency_info.dat

    export LD_GENERATE_MAP_FILE=NO

    export LD_MAP_FILE_PATH="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/-LinkMap--.txt"

    export LD_NO_PIE=NO

    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES

    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer

    export LIBRARY_FLAG_NOSPACE=YES

    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions

    export LINKER_DISPLAYS_MANGLED_NAMES=NO

    export LINK_WITH_STANDARD_LIBRARIES=YES

    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities

    export LOCAL_APPS_DIR=/Applications

    export LOCAL_DEVELOPER_DIR=/Library/Developer

    export LOCAL_LIBRARY_DIR=/Library

    export MAC_OS_X_PRODUCT_BUILD_VERSION=15F34

    export MAC_OS_X_VERSION_ACTUAL=101105

    export MAC_OS_X_VERSION_MAJOR=101100

    export MAC_OS_X_VERSION_MINOR=1105

    export OBJECT_FILE_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/Objects"

    export OBJROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export ONLY_ACTIVE_ARCH=NO

    export OS=MACOS

    export OTHER_CFLAGS=-DNS_BLOCK_ASSERTIONS=1

    export OTHER_CPLUSPLUSFLAGS=-DNS_BLOCK_ASSERTIONS=1

    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/greg/Documents/Dispofi/Sites/Auto/phantomjs-2.0.0-macosx/bin:/usr/local/mysql/bin:/opt/subversion/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/greg/Documents/Dispofi/Sites/Bases de Données/Mongo/mongodb/bin:/Users/greg/Documents/Dispofi/Mobile/android-sdk-macosx/tools:/Users/greg/Documents/Dispofi/Mobile/android-sdk-macosx/platform-tools"

    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"

    export PLATFORM_NAME=iphoneos

    export PLIST_FILE_OUTPUT_FORMAT=binary

    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES

    export PRECOMP_DESTINATION_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build/PrefixHeaders"

    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO

    export PRODUCT_NAME=

    export PROFILING_CODE=NO

    export PROJECT=BabylonHx_Lime

    export PROJECT_DERIVED_FILE_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/DerivedSources

    export PROJECT_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios

    export PROJECT_FILE_PATH=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/BabylonHx_Lime.xcodeproj

    export PROJECT_NAME=BabylonHx_Lime

    export PROJECT_TEMP_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build

    export PROJECT_TEMP_ROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export REMOVE_CVS_FROM_RESOURCES=YES

    export REMOVE_GIT_FROM_RESOURCES=YES

    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES

    export REMOVE_HG_FROM_RESOURCES=YES

    export REMOVE_SVN_FROM_RESOURCES=YES

    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO

    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk

    export SEPARATE_STRIP=NO

    export SEPARATE_SYMBOL_EDIT=NO

    export SHARED_DERIVED_FILE_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-iphoneos/DerivedSources

    export SHARED_PRECOMPS_DIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/C/com.apple.DeveloperTools/7.3.1-7D1014/Xcode/SharedPrecompiledHeaders

    export SKIP_INSTALL=YES

    export SOURCE_ROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios

    export SRCROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios

    export STRINGS_FILE_OUTPUT_ENCODING=binary

    export STRIP_BITCODE_FROM_COPIED_FILES=YES

    export STRIP_INSTALLED_PRODUCT=YES

    export STRIP_STYLE=all

    export SUPPORTED_PLATFORMS="iphonesimulator iphoneos"

    export SUPPORTS_TEXT_BASED_API=NO

    export SYMROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities

    export SYSTEM_APPS_DIR=/Applications

    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices

    export SYSTEM_DEMOS_DIR=/Applications/Extras

    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications

    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin

    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"

    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer

    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"

    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"

    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"

    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"

    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"

    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools

    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"

    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"

    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr

    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities

    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation

    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions

    export SYSTEM_LIBRARY_DIR=/System/Library

    export TAPI_VERIFY_MODE=ErrorsOnly

    export TARGETED_DEVICE_FAMILY=1,2

    export TARGETNAME="Build Haxe"

    export TARGET_BUILD_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-iphoneos

    export TARGET_NAME="Build Haxe"

    export TARGET_TEMP_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build"

    export TEMP_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build"

    export TEMP_FILES_DIR=

    export TEMP_FILE_DIR="/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/BabylonHx_Lime.build/Release-iphoneos/Build Haxe.build"

    export TEMP_ROOT=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build

    export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain

    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO

    export UID=0

    export USER=root

    export USER_APPS_DIR=/var/root/Applications

    export USER_LIBRARY_DIR=/var/root/Library

    export USE_HEADERMAP=YES

    export VALIDATE_PRODUCT=YES

    export VALID_ARCHS="armv7 arm64 i386"

    export WATCH_BUILT_PRODUCTS_DIR=/Users/greg/Documents/Greg/Haxe/BabylonHx/bin_lime/ios/build/Release-watchos

    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO

    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode

    export XCODE_PRODUCT_BUILD_VERSION=7D1014

    export XCODE_VERSION_ACTUAL=0731

    export XCODE_VERSION_MAJOR=0700

    export XCODE_VERSION_MINOR=0730

    export ZERO_LINK=NO

    export arch=arm64

    export diagnostic_message_length=162

    export variant=normal

    /Applications/Xcode.app/Contents/Developer/usr/bin/make

Haxe device build: Release-iphoneos-v7

haxe Build.hxml -D HXCPP_ARMV7 -cpp build/Release-iphoneos-v7 

cd build/Release-iphoneos-v7; export HXCPP_NO_COLOR=1; haxelib run hxcpp Build.xml -Dios -Diphone -DHXCPP_ARMV7 -DHXCPP_CPP11  -DHXCPP_CLANG -DOBJC_ARC `cat Options.txt | while read LINE; do printf " -D$LINE"; done`

This is the first time you are runing haxelib. Please run `haxelib setup` first

make: *** [build-haxe-armv7] Error 1

Command /Applications/Xcode.app/Contents/Developer/usr/bin/make failed with exit code 2

 

** BUILD FAILED **

 

 

The following build commands failed:

ExternalBuildToolExecution Build\ Haxe

(1 failure)

**Comment by Justinfront** [comment]
This is probably not a Haxe specific problem I suggest you post you question in the Openfl/Lime issues here first and they will post the issue here later if it's not a lime related issue.
https://github.com/openfl/lime/issues

**Comment by Justinfront** [comment]
Suggest you also test Babylon with NME and Snowkit. If you need help with snowkit the gitter channel is very active.

**Comment by ibilon** [comment]
> This is the first time you are runing haxelib. Please run haxelib setup first

Do it with sudo if you want to build with sudo, which I'd recommend against.

**Comment by Simn** [comment]
What he said.
