### ISSUE TITLE
@:to Int masks @:to Float, if it is declared first

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5286]
```haxe
class Main {
	public static function main() {
		var d:Decimal = getFloat();
		var i:Float = d;
		trace(i);
	}
	
	static function getFloat():Float return 0.2;
}

abstract Decimal(Float) from Float {
	@:to
	public inline function toInt() return Std.int(this);
	@:to
	public inline function toFloat() return this;
}
```

This generates the following wrong code (`@:to Int` is being used):
```js
var d = Main.getFloat();
console.log(Std["int"](d));
```

But if the declaration of the implicit casts are reversed like so:
```haxe
@:forward
abstract Decimal(Float) from Float {
	@:to
	public inline function toFloat() return this;
	@:to
	public inline function toInt() return Std.int(this);
}
```

It compiles correctly as:
```js
var d = Main.getFloat();
console.log(d);
```

**Comment by back2dos** [comment]
I'm pretty sure this works as intended. The first compatible conversion found will take effect, as that avoids ambiguity.

OTOH I do think that the compiler should give a warning if an implicit cast is following one that shadows it ... like `This pattern is unused` in `switch` statements.

**Comment by Simn** [comment]
Yes this works as (currently) intended. We were discussing changing it to a type distance-based selection algorithm like in Java, but that would be Haxe 4 material.
