### ISSUE TITLE
PHP type issue with integer literal edge case

### ISSUE THREAD

**Issue by Jens-G** [HaxeFoundation/haxe#5289]
In PHP, the integer constant `-2147483648 = 0x80000000`  is not an integer, but a double:

```
<?php
$a = gettype(-2147483647);
$b = gettype(-2147483648);
echo "typeof(-2147483647) = $a,  typeof(-2147483648) = $b";
```

[prints this quite surprising result](http://codepad.org/wZ3OxUxv)

```
typeof(-2147483647) = integer,  typeof(-2147483648) = double
```

In theory, this looks not as a big issue, but unfortunately it breaks comparison, if the value is indeed stored as an integer, [which is not really hard to achieve](http://codepad.org/jW55kfj9), because Haxe uses the `===` and `!==` operators:

```
<?php
$a = gettype(-2147483647);
$b = gettype(-2147483648);
$c = gettype(1 << 31);
$d = (-2147483648 === (1 << 31)) ? "true" : "false";
$e = (-2147483647 === ((1 << 31)+1)) ? "true" : "false";
echo "types a = $a, b = $b, c = $c \nequal? -2147483648 = $d, -2147483647 = $e";
```

gives

```
types a = integer, b = double, c = integer 
equal? -2147483648 = false, -2147483647 = true
```

Although using `==` and `!=` would solve the actual problem, but I'm not sure about the consequences, so this is probably not really the right way to fix it.

**Comment by Jens-G** [comment]
Here's a workaround:

```
#if php
value = value & 0xFFFFFFFF;  // force integer type for PHP
#end
```

Of course one must ensure that value is in the correct range.

**Comment by oprudkyi** [comment]
it seems this is related only to 32bit architecture, 
on x86_64 it works properly 
php -r 'echo gettype(-2147483648) . "\n";'
integer

**Comment by Jens-G** [comment]
Possible. The machine where I tested this is 32 bit.

**Comment by Jens-G** [comment]
Someone pointed out [this PHP bug #14134](https://bugs.php.net/bug.php?id=14134) to me, unfortunately on status "WONT FIX".

**Comment by Simn** [comment]
I don't really see how we can fix this, especially if it is a 32bit-only problem...

**Comment by Jens-G** [comment]
First, the problem only apples to exactly one well-known value. I could imagine a special treatment for this case that applies the workaround above automatically:

```
#if php
value = value & 0xFFFFFFFF;  // force integer type for PHP
#end
```
Of course I'm aware of the fact that this is an hack. but since (a) the PHP bug will not be fixed (meaning there wikll be no help from that end), and (b) 32 bit is still not dead it is worth to be considered.

**Comment by Simn** [comment]
Yes but doing that for every integer constant is very intrusive. Or am I misunderstanding the scope of this problem?

**Comment by Jens-G** [comment]
I repeat it: From what we know, the problem only applies 

- to  exactly one well-known value, 
- and only if it is used as a literal
- and (as it Looks) only on 32 bit

No other case is affected. Only this specific one.

**Comment by Simn** [comment]
Ah, I didn't realize it was about the literal itself as opposed to the run-time value in general. In this case I agree it's possible to detect this at compile-time and fix it accordingly.
