### ISSUE TITLE
[js][neko] Compiler optimizes object away when it must not

### ISSUE THREAD

**Issue by jonnydee** [HaxeFoundation/haxe#5290]
The following code snippet fails to compile with Haxe 3.3.0-RC1 but it does compile with 3.2.1. 

```
class Main {
    static function main() {
        createFromPrototype({month: 0});
    }

    public static inline function createFromPrototype(
        options: { ?year: Int, ?month: Int })  {

        if(null == options.year)
            options.year = 2016;

        // if (null == options.month)
        //    options.month = 5;
    }
}
```

The error message reported by the compiler is:

```
Main.hx:3: characters 8-39 : Local variable options_year used without being initialized
```

If 'inline' modifier is removed from function `createFromPrototype` that code also compiles with the release candidate. It seems like the 'options' object is optimized away. I could reproduce this error message with JavaScript and with Neko target (I only tested those two targets).

**Comment by Simn** [comment]
Hmm yes, this is a bit of an issue. The behavior matches that of our variable initialization checks, but obviously conflicts with the normal field access rules.

I see two options here:

1. Mark inline variables somehow and ignore initialization checks for them.
2. Always allow `v == null` and `null == v`, even for uninitialized variables.

I'll go for 1. for now, but 2. might make sense in the future.
