### ISSUE TITLE
Inconsistency on Date for Neko target, for Java it fails due to a deprecated API

### ISSUE THREAD

**Issue by JoanBotella** [HaxeFoundation/haxe#5294]
Hi. Please, check this code:

```
class Main {
  static public function main():Void {
    var date:Date;

    date = new Date(1983, 8, 26, 10, 0, 0);
    trace(date.toString());

    date = new Date(2008, 2, 30, 14, 1, 1);
    trace(date.toString());
  }
}
```

Something happens with the hours for the Neko target. It prints the following for me:

Neko.-

> Main.hx:8: 1983-09-26 10:00:00
> Main.hx:11: 2008-03-30 15:01:01

PHP.-

> Main.hx:8: 1983-09-26 10:00:00
> Main.hx:11: 2008-03-30 14:01:01

Python.-

> 1983-09-26 10:00:00
> 2008-03-30 14:01:01

C++.-

> Main.hx:8: 1983-09-26 10:00:00
> Main.hx:11: 2008-03-30 14:01:01

I would like to mention that months in a range 0-11 and days in 1-31 seems pretty weird to me.
Also, when checking on Java, the Date API seems to be deprecated:

Java.-

> haxelib run hxjava hxjava_build.txt --haxe-version 3201 --feature-level 1
> javac "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
> Note: src/haxe/root/Date.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.

My system is a Linux Mint 17.1 x64, Haxe Compiler 3.2.1, and my Java is:

> java version "1.7.0_101"
> OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
> OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**Comment by Blank101** [comment]
Looks like Neko is using daylight savings time whereas the other targets arn't.

**Comment by JoanBotella** [comment]
I agree, but it's a consistency problem between platforms. It could cause several errors, and quite difficult to identify.

**Comment by waneck** [comment]
On Java, thr API is deprecated but it should still work properly.

**Comment by JoanBotella** [comment]
But it is impossible to compile Haxe programs that uses Date on modern Java versions. I think that should be fixed.

**Comment by JoanBotella** [comment]
Others having problems with dates should check this library: http://lib.haxe.org/p/datetime/ . It has really saved my day.

**Comment by Aurel300** [comment]
Assuming the system timezone is specified correctly, this should not be an issue anymore (#8508). Feel free to reopen if there is still something wrong with neko specifically.
