### ISSUE TITLE
Cannot build for C++

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5296]
When I attempt to build for C++, I get the following error (Haxe 3.3-rc1)

    Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/src/hx/libs/regexp/Build.xml"

I don't see these files in HXCPP in the repository, either. Is this expected behavior?

**Comment by ibilon** [comment]
Maybe haxe 3.3 requires a 3.3+ hxcpp.

**Comment by Simn** [comment]
Indeed it does.
