### ISSUE TITLE
User variable removal

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5298]
Since we apparently had the equivalent of PETA for variables at WWX, multiple people complained about the analyzer removing user variables, which makes it harder to debug.

The only question here is if we should make a distinction between release/debug or if there should be a distinct compilation flag.

**Comment by ibilon** [comment]
I like g++'s `-Og` optimization level which do anything but things that would prevent debugging.
Maybe that should be the behavior of debug, since debugging a debug version is kind of the point.

**Comment by Simn** [comment]
I'm not sure because there are these "only fails in release mode" kind of errors. Then again I doubt the removal of a variable would make the difference there.

**Comment by delahee** [comment]
Maybe add a com flag --analyzer-debug or something ? It would help
discriminate -debug and -debug with analyzer ?

2016-05-31 10:22 GMT+02:00 Simon Krajewski <notifications@github.com>:

> I'm not sure because there are these "only fails in release mode" kind of
> errors. Then again I doubt the removal of a variable would make the
> difference there.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HaxeFoundation/haxe/issues/5298#issuecomment-222622965>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAnVXJSJwiprDKkopy0oagCPgLeDedNOks5qG-_fgaJpZM4IqR7s>
> .
>



-- 
David Elahee

**Comment by ncannasse** [comment]
Could you give some example of such removal? I'm not sure I understand how it can affect debugging.

**Comment by Simn** [comment]
```haxe
var x = doSomething();
if (x) { }
```

Can become:

```haxe
if (doSomething()) { }
```

Which makes it harder to set breakpoints and see live values.

**Comment by ncannasse** [comment]
Ah, I think that if possible we should not remove such vars. The target platform has very high chances of optimizing this anyway.

**Comment by Simn** [comment]
I feel like this should depend on the target. unit.js gains 16kb when this feature is disabled and some other targets don't appreciate unnecessary variables either.

**Comment by Simn** [comment]
I went for the debug/release difference with an additional flag to control it, see commit message.
