### ISSUE TITLE
[js] "TypeError: undefined is not an object" in macro generated function

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5307]
The following code executes on all targets except JavaScript:
```haxe
package tests;

import haxe.macro.Context;
import haxe.macro.Expr;

#if !macro
@:build(tests.MacroTest.generateMethodThatInvokesMyPrint())
#end
class MacroTest {
  
    public static function main() {
        new MacroTest();
    }

    function new() {
        Reflect.field(this, "generatedMethod")();
    }

    function myPrint(msg:String) {
        trace(msg);
    }

    #if macro
    static function generateMethodThatInvokesMyPrint():Array<Field> {
        var methodDef = {
            name: 'generatedMethod',
            meta: [{ name:":keep", pos: Context.currentPos()}],
            kind: FFun({
                ret:null,
                args:[], 
                expr: { expr: EBlock([ macro { myPrint("hi"); } ]), pos: Context.currentPos()}
            }),
            pos: Context.currentPos()
        };

        return Context.getBuildFields().concat([methodDef]);
    }
    #end
}

```

Result in JavaScript:
```
TypeError: undefined is not an object (evaluating 'this.myPrint')

  phantomjs://code/MacroTest.js:22 in generatedMethod
  phantomjs://code/MacroTest.js:12 in tests_MacroTest
  phantomjs://code/MacroTest.js:15 in main
  phantomjs://code/MacroTest.js:25
```

**Comment by Simn** [comment]
Yes that doesn't work on Javascript, you'll have to use Reflect.callMethod to pass a this-object.

**Comment by sebthom** [comment]
Why doesn't the Haxe compiler work around this or throw an compiling error? It is working for all other targets and it is very surprising to only encounter the issue during runtime.

**Comment by Simn** [comment]
Once you use Reflect that compiler has no idea what you're doing. That's kind of the idea behind reflection.

**Comment by sebthom** [comment]
Even on Java something like getting a  method of an object and invoking it without explicitly passing the "this" object doesn't exist. But the code generated by Haxe works around it. 

I had a look at the generated JavaScript code, there the `Reflect.field` function is defined as follows:
```js
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		return null;
	}
};
```

If the `Reflect.field` function is changed to the following, the Haxe code will also work on JavaScript targets as expected.
```js
Reflect.field = function(o,field) {
	try {
		var f = o[field];
		if (typeof(f) == "function")
			return function() { f.apply(o,arguments); }
		return f;
	} catch( e ) {
		return null;
	}
};
```

**Comment by nadako** [comment]
I always thought that `Reflect.field` can't have that because additional branching will hurt speed, but that's a bit awkward to talk speed here, when we have a `try/catch`. :)

But anyway, I think implicitly wrapping a function into another binding function is not we want in a general case with `Reflect.field`, so it's better to keep the current behaviour.

For example, I'm dealing with that explicitly like this: https://github.com/nadako/hxmustache/blob/master/src/mustache/Context.hx#L86-L87

**Comment by sebthom** [comment]
Shouldn't this
```haxe
var m:Function = Reflect.field(this, "myMethod");
m("foo");
```
do exactly the same like this: 
```haxe
var m:Function = this.myMethod;
m("foo");
```
It actually does so on all other targets: static (incl. CPP) and dynamic.

In both cases we are working on a method reference that is bound to "this". 
We are not reflecting on the class but the object instance.

**Comment by Simn** [comment]
It's not the same. In the latter case everything is properly typed and the compiler can tell what you want to do. It's similar to how property accessors can be resolved there, whereas that's not possible in the reflection case.

**Comment by ncannasse** [comment]
You can use `Reflect.callMethod(this,Reflect.field(this,"myMethod"),[])` if you want to be able to call such method. Reflect uses native field access, and in JS (and potentially other platforms) this does not create a closure.

You can write your own getField if you want, for instance:
```haxe
function getClosure( obj : Dynamic, field : String ) : Dynamic {
     var f = Reflect.field(obj,field);
     if( Reflect.isFunction(f) )
         return Reflect.makeVarArgs(function(args) return Reflect.calMethod(obj,f,args));
    return f;
}
```
