### ISSUE TITLE
Invalid AST

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5309]
When compiling `hxd.Math.f2b` from heaps with HL using `-dce no` I get a `Don't kown how to cast void to f64` which seems to indicate an invalid AST is produced by some inlinings.

Reproducible with:

```
class Test {
	public static inline function clamp( f : Float, min = 0., max = 1. ) {
		return f < min ? min : f > max ? max : f;
	}
	public static function f2b( v:Float ) : Int {
		return Std.int(clamp(v) * 255.0);
	}
   static function main() {
      trace(f2b(0.1));
   }
}
```

**Comment by Simn** [comment]
You and your untyped...

**Comment by ncannasse** [comment]
No `untyped` here, HL simply <3 nicely typed AST :)

**Comment by Simn** [comment]
```haxe
	@:extern public static inline function int( x : Float ) : Int {
		return untyped $int(x);
	}
```

Right!

**Comment by ncannasse** [comment]
Ah, this one :) One of the rare cases in HL, but since we don't have any other way of creating unbound globals...
