### ISSUE TITLE
Copyright (C)2005-2015 Haxe Foundation installer haxe 3.3.0-rc.1 osx

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#5310]
Copyright (C)2005-2015 Haxe Foundation

should be 2016?

![screen shot 2016-06-02 at 17 27 22](https://cloud.githubusercontent.com/assets/907219/15750807/1c580e48-28e8-11e6-8330-9adab29ea939.png)

**Comment by kevinresol** [comment]
And it shows rc2 in the header
(btw, I swear I saw rc2 in the main area as well, for a flash second when I click continue)

**Comment by Simn** [comment]
We'll address this for the next release but it's not worth re-making the binaries over.

@waneck: Can you check the license file date?

**Comment by andyli** [comment]
Hint: check the installer stuff in https://github.com/HaxeFoundation/haxe/tree/development/extra

**Comment by Simn** [comment]
This should be obsolete.
