### ISSUE TITLE
[js]  Json.stringify adds top-level key "h" for Map

### ISSUE THREAD

**Issue by wiggin77** [HaxeFoundation/haxe#5311]
When passing a Map to Json.stringify it adds a top-level key "h" with the actual map contents as its value.  Only happens in JavaScript target without "-D  haxeJSON".

http://try.haxe.org/#C1d86
```haxe
class Test {
    static function main() {
        
        var map = new Map<String,String>();
        map.set("key1", "val1");
        map.set("key2", "val2");
        
        var str = haxe.Json.stringify(map);
        
        trace(str);
    }
}
```
JavaScript without "-D haxeJSON":
 ```{"h":{"key1":"val1","key2":"val2"}}```

JavaScript with "-D haxeJSON":
```{"key1":"val1","key2":"val2"}```

java, cs, ccp:
```{"key1":"val1","key2":"val2"}```

**Comment by mrcdk** [comment]
That's correct and documented:
http://api.haxe.org/haxe/Json.html
http://haxe.org/manual/std-Json-implementation-details.html
