### ISSUE TITLE
[hl] Sys.exit() not working as expected

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5313]
On HL execution continues after call to Sys.exit(). The following example will print `2` on HL, but not on C++, PHP, Python, Neko, Java, C#.

```haxe
class Test {
    static function main() {
        trace("1");       
        Sys.exit(0);
        trace("2");
    }
}
```

**Comment by nadako** [comment]
Note that this prevents tests failing on Travis, e.g. https://travis-ci.org/HaxeFoundation/haxe/jobs/151090378#L1568
