### ISSUE TITLE
[hl] Missing interp system api

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5314]
The following code

``` haxe
class Test {
    static function main() {
        trace(Sys.systemName());
    }
}
```

results in

```
Uncaught exception Genhl.Runtime_error("Unresolved native std@sys_string")
C:\apps\dev\haxe\haxe-3.3.0-rc1\std/hl/_std/Sys.hx:113: Called from fun(260)@0
haxe/strings/Test.hx:20: Called from fun(442)@8
<startup>:1: Called from fun(527)@1100
```

**Comment by ncannasse** [comment]
Please note that the HL sys API is far from being complete into the HL interpreter embedded in Haxe compiler which is experimental to check the HL bytecode validity

**Comment by sebthom** [comment]
I realized that in the meantime. :-) Sys.environment doesn't work too. So I won't open more issues against HL regarding the Sys API for now.

**Comment by Simn** [comment]
Can this be closed?

**Comment by ncannasse** [comment]
HL interp is still missing the full sys API

**Comment by ncannasse** [comment]
Closing for now, as we now use the eval target for macros.
