### ISSUE TITLE
[3.3-rc1] duplicate type parameters error also when used with 'Const'

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe#5316]
This generates an error:

```haxe
class Foo<Const,Const> {}
````
Having several Const(s) can be very useful for macros and I don't think this case should be restricted.

**Comment by nadako** [comment]
This should probably be allowed, but also deprecated, since there's a better way to do this now with type parameter metadata: `class Foo<@:const Arg1, @:const Arg2>`

**Comment by Simn** [comment]
Didn't we talk about that and decide that it's fine because there's `@:const` now?

**Comment by nadako** [comment]
Maybe we did, but probably it should go thru a deprecation process...

**Comment by kevinresol** [comment]
Maybe at least mark it as [breaking change](https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.3.0)

**Comment by Simn** [comment]
Good call, I have added it in the macro section. I have also added a specific deprecation message for it to the compiler which is good enough.

**Comment by sledorze** [comment]
@Simn have you already pushed the compiler change? (not seeing it linked to that issue nor in your history)

**Comment by nadako** [comment]
What change are you talking about? The disallow was added here: 71ce0545ebf8b56dd1375aa3b318fe2c7218f060, and type param meta was added long before I think.

**Comment by sledorze** [comment]
From Simn "I have also added a specific deprecation message for it to the compiler which is good enough." @nadako

**Comment by kevinresol** [comment]
@sledorze Here you are: 3953d07b034d174de6645bf0008ef23763223206

**Comment by sledorze** [comment]
Sweet! Thanks @kevinresol
