### ISSUE TITLE
[PHP] Wrong call with default param

### ISSUE THREAD

**Issue by TheoSabattie** [HaxeFoundation/haxe#5318]
Hi,

There is a wrong output:

```
extern class Test
{
    public function new(?hello:String = "Hello world");   
}
```

```
class Main 
{
    static function main() 
    {
            new Test();
    }
}
```

output:

```
class Main {
    public function __construct(){}
    static function main() {
        new Test(null);
    }
    function __toString() { return 'Main'; }
}
```

`new Test(null);`

Should be:

`new Test();`

like js output : 

```
(function (console) { "use strict";
var Main = function() { };
Main.main = function() {
    new Test();
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}});

```

Thanks,

Théo S.

**Comment by mockey** [comment]
Shouldn't `new Test()` result in `new Test("Hello world")` here?
I know that this is a problem, though: #4628

**Comment by TheoSabattie** [comment]
> Shouldn't new Test() result in new Test("Hello world") here?

No, in normal class, there is : 
```
class Test2
{
    public function new(?hello:String = "hi") 
    {
    }
}
```
```
class Test2 {
	public function __construct($hello = null) { 
            if(!php_Boot::$skip_constructor) {
		if($hello === null) {
			$hello = "hi";
		}
            }
      }    
}
```

Same thing for js output.
So a generated call mustn't have optional parameters.

> I know that this is a problem, though: #4628

Ok'', sorry, I didn't see your report

**Comment by RealyUniqueName** [comment]
Closing this issue, because it's just a particularr case of #4628 and cannot be fixed separately.
