### ISSUE TITLE
mix between Class and Enum name

### ISSUE THREAD

**Issue by benjaminsoule** [HaxeFoundation/haxe#5321]
With 3.3 I can't pass enum without full path as 2nd argument if its name is the same than a class.

In this example https://gist.github.com/benjaminsoule/5aa83eb8b3b6cdabd2fb1002908b14e9 

The enum CHEST is mistaken with the class Chest
Either changing the enum name or changing the argument orders solve it

This example compile in 3.2.1

**Comment by Simn** [comment]
The first question here is if it should find the module at all given the different casing. If no, problem solved. If yes, it seems to get tricky.

**Comment by Simn** [comment]
The 3.2.1 behavior suggests to me that it was not only recovering from unification errors but also from `Typecore.Error` in general. I'll change this accordingly.
