### ISSUE TITLE
[CPP] Set executable file name

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/haxe#5326]
Currently it's not possible to set executable file name and it's always match main class name. There should be flag similiar to `file-extension` but redefining the file name.  
Something like `-D file-name=outputFile` resulting in `outputFile.exe` on windows instead of `Main.exe` (in case main class is Main).

**Comment by Simn** [comment]
If we do that we have to do it for various targets. I'm not sure this is worth the effort...
