### ISSUE TITLE
[lua] ugly closures generated for += on fields

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5327]
``` haxe
class Main {
    static var pos = 1;
    static function main() {
        pos += 10;
    }
}
```

``` lua
Main.main = function() 
  (function() return (function() 
  local fld = 'pos';
  local obj = Main;
  obj[fld] = (obj.pos) + (10);
  return obj[fld] end)() end)();
end
```

Not sure if it's for Simon or Justin, but surely this should generate simply `Main.pos = Main.pos + 10`

**Comment by jdonaldson** [comment]
These things are ugly, agreed.

I'll take a look, it's not a huge priority now though.

**Comment by jdonaldson** [comment]
@Simn are there other platforms that don't support "+="?   This seems like a job for the static analyzer if it serves more than one target.  Even if Lua is alone here, it might be nice to put the logic for this there anyways (behind a flag or config value of some sort).

**Comment by Simn** [comment]
Yeah I'll look into it.

**Comment by nadako** [comment]
@jdonaldson python also doesn't support that I think, so yeah, you're right about analyzer responsibility

**Comment by ibilon** [comment]
@nadako python supports `+=` but doesn't support `++`

**Comment by nadako** [comment]
Oh, right, sorry then :)

**Comment by Simn** [comment]
This is actually not so easy to handle in a general manner and I don't want to make any changes like that for 3.3.

**Comment by nadako** [comment]
Maybe something could be done on genlua level then? This kind of generated code will be hard to present to lua crowd :-P

I'll try looking into it when I have a minute.

**Comment by Simn** [comment]
I'll probably accidentally fix this as part of my work on #5477.

**Comment by jdonaldson** [comment]
Thanks @Simn

**Comment by Simn** [comment]
Any idea how we could add a test for this?

This has a pretty strong impact on our unit tests, unit.lua loses almost 20kb with this addressed.

**Comment by jdonaldson** [comment]
There's some small things I have in mind, but nothing that'll clear this up completely.  Any other ideas?

**Comment by nadako** [comment]
there's a similar issue with Array.push generated like this (due to unops):

(this is quite bad because Array.push is a frequently used method, but if it's hard to fix in the analyzer, I guess we could/should at least rewrite Array.push in a way it generates some sane lua code)

```lua
  'push', function(self,x) 
    self[(function() 
    local _hx_obj = self;
    local _hx_fld = 'length';
    local _ = _hx_obj[_hx_fld];
    _hx_obj[_hx_fld] = _hx_obj[_hx_fld]  + 1;
     return _;
     end)()] = x;
    do return self.length end
  end,
```

source:
```haxe
    public function push(x : T) : Int {
        this[this.length++] = x;
        return this.length;
    }
```

ast
```
    public function push[Function:x : Array.T -> Int]
        [Arg:Array.T] [Local x(9):Array.T]
        [Block:Dynamic]
            [Binop:Array.T]
                [Array:Array.T]
                    [Const:Array<Array.T>] this
                    [Unop:Int]
                        ++
                        Postfix
                        [Field:Int]
                            [Const:Array<Array.T>] this
                            [FInstance:Int]
                                Array<Array.T>
                                length
                =
                [Local x(9):Array.T]
            [Return:Dynamic]
                [Field:Int]
                    [Const:Array<Array.T>] this
                    [FInstance:Int]
                        Array<Array.T>
                        length
```

**Comment by jdonaldson** [comment]
This looks like @simn adjusted some ast code to fix this, thanks!

**Comment by nadako** [comment]
The second example is still relevant, but it's the same as #5080 and is related to analyzer, so I won't reopen it.
