### ISSUE TITLE
Lib, SDK separation

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#5328]
First off, this isn't really a bug.. I'm really just interested in hearing what other think about this..
So when dealing with other languages and their respective SDKs I'll often jump between SDK versions for various reasons, maybe a new SDKs has deprecated a features that I need, or there has been a breaking change that means we need to stick with an old version for old projects. This is sometimes the case with Haxe, but because the haxe sdk folder also stores all the libs downloaded from haxelib it means I always have to duplicate all the libs between to 2/or more SDKs, which isn't a huge deal, but after doing this, this afternoon I thought to myself... "wouldn't it be nice if the Libs folder wasn't contained within the SDK folder", this would allow us to easily switch between SDKs while accessing the same libs. Maybe there are some reasons why this is a bad idea... but yeah just interested in what others think.

**Comment by ibilon** [comment]
Are you referring to the default haxelib setup path which is within the haxe folder?

**Comment by peteshand** [comment]
yeah, actually you can change can't it can't you?... I seem to remember doing that ages ago

**Comment by peteshand** [comment]
What's the syntax again?

**Comment by ibilon** [comment]
`haxelib setup`

**Comment by peteshand** [comment]
Awesome, cheers
