### ISSUE TITLE
java.Web and python.Web

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#5330]
I recently wrote a tutorial/documentation for `PHP` and for the first time used `Neko` for backend.
Powerfull! and easy to switch!.

So I assumed (and I know: **assumption is the mother of all f\* ups** ) it would work also for `Java` and `Python`. 
It didn't ... but I would like to ask **why**?

One of the arguments for using Haxe is the freedom of choices. 
Let's say a startup creates their backend with PHP. Starts to grow and needs more speed so wants to switch to java. It would be awesome if switching was as easy as switching from PHP to Neko.
A very compelling reason to use Haxe?

Maybe it's to difficult and I am simplifying everything but I'm curious why it doesn't exist (yet). 

> It seems to be an old discussion (https://github.com/HaxeFoundation/haxe/issues/1855), and the "answer" was that Ufront was the solution.
> Currently Ufront supports: PHP, Neko and Node.js.

**Comment by kevinresol** [comment]
Although it is not fully complete yet, you may be interested in [tink_web](https://github.com/haxetink/tink_web/)

**Comment by Simn** [comment]
This is too high-level for the standard library.
