### ISSUE TITLE
Provide haxe compiler as a maven package + SSL

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5331]
Hey @andyli , JLM suggested it for you :)

https://groups.google.com/forum/?hl=en#!topic/haxelang/ys14iAJIJgI

Also I have another concern: Right now Haxe releases are downloaded under http (haxe.org + nightly) which is pretty unsecure because the could be potentially tampered.

Nowadays having a SSL certificate is completely free: https://letsencrypt.org/ so I would suggest having the whole website under https.

**Comment by Simn** [comment]
The SSL issue was addressed at some point, and there are no plans for maven packages.
