### ISSUE TITLE
Combination of Type Parameters and Static methods can cause value of 'this' in an object to change 

### ISSUE THREAD

**Issue by clarkjones** [HaxeFoundation/haxe#5337]
The title of the issue probably isn't totally accurate as I'm not really sure whats causing the issue, but it seems like the scope of the function being called is wrong. I have found a few work arounds documented in the haxe-dom repo.

I originally pointed this out in the haxe-dom repo here https://github.com/Blank101/haxe-dom/issues/34
because I wasn't able to reproduce this issue outside of that library but I can't really see how this isn't a bug in the latest release, unless there is a documented breaking change that I missed.

Here is an example of the error I'm seeing, you'll need the hxdom library to run it.
https://gist.github.com/clarkjones/e2f8e1638b49930596b74120f0e45746

The line of code causing the exception:
https://github.com/Blank101/haxe-dom/blob/master/src/hxdom/DomTools.hx#L266

**Comment by Simn** [comment]
I somehow missed this issue. Could somebody reduce this to something smaller?

**Comment by clarkjones** [comment]
@simn I finally was able to repro with out the library. I'll update the title to something more accurate to what is happening in the example below.

The comments are  for when running in neko
An error is thrown when target JS on try.haxe.org
```Haxe
package;

class Issue{
	static public function main() {
		var tw = new TracerWrapper<Tracer>(new Tracer());
		logThis(tw,'some string value');
	}

	static public function logThis<T:TracerWrapper<Dynamic>>(e:T, val:Dynamic){
		//'this' is whatever called logThis - not expected
		e.tracer.traceThis(Std.string(val));	 
		
		//'this' is Tracer - expected
		var str:String = Std.string(val);
		e.tracer.traceThis(str);	 
	}

}

class Tracer  {
	public function new(){}

	public function traceThis(value:String) {
		trace(this);
	}
}

class TracerWrapper<T:Tracer>  {
	public var tracer:T;
	//setting the actual type will also make it work separate from Std.string  cases above
	// public var tracer:Tracer;

	public function new (element:T) {
		this.tracer = element;
	}
}
```

**Comment by Simn** [comment]
This no longer reproduces.
