### ISSUE TITLE
Type of field is lost when using inline constructors

### ISSUE THREAD

**Issue by ntrf** [HaxeFoundation/haxe#5340]
This issue happens with luxe engine in haxe 3.3-rc1, but does not happen in haxe 3.2.1. Here is my lengthy piece of code demonstrating it.
```
class Vector{
    public var x : Float = 0;
    
    public var inverse(get, never) : Vector;
    
    public inline function new(?x : Float = 0) {
        this.x = x;
    }
    inline function get_inverse() return new Vector(-x);
    public function toString() return 'Vec($x)';
}

class Matrix {
    public var m : Array< Float > = [0.11, 0.33];
    
    public function new() {}
    public inline function back() return new Vector(m[0]);
    public inline function fwd() return back().inverse;
}

class Test {
    public static function main() {
        var m = new Matrix();
        m.m[0] = 0.22;
        var dir = m.fwd();
        
        trace('dir = $dir');
    }
}
```
Class `Vector` has inline costructor. Class `Matrix` has inline methods, that generate objects of class `Vector`. Notice how method `fwd` uses call chaining to generate result.

Result of the program, when used with Haxe 3.3 and C++ target, is zero vector `Vec(0)`. For Java and C# this program doesn't even compile. Dynamic targets on haxe 3.3 and all targets on haxe 3.2.1 give correct result `Vec(-0.22)`.

The problem can be seen in AST. Intermediate variable, used to hold value of `back()` call has type `Int` instead of `Float`. If you change initializer of member variable in class `Vector` to
```
public var x : Float = 0.0;
```
program works correctly on every target with haxe 3.3. I can conclude, that type of temporary variable is taken from initializer and not variable definition.

**Comment by Simn** [comment]
The problem here is related to the fact that an assignment that has operand types `Float = Int` should be typed as `Float`, not `Int`.
