### ISSUE TITLE
Package name called enum

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#5341]
Would it be possible to allow a package name called "enum"? 

In the current setup weird errors happen when you do that.

**Comment by Simn** [comment]
I don't think we should do that. Unlike `macro` and `extern`, `enum` is actually a keyword in some of our target languages as well which might lead to problems with code generation and reflection.

**Comment by nadako** [comment]
Actually, `extern` is a keyword in e.g. C#, but it's handled at the generator level by prefixing it with a `@`.
