### ISSUE TITLE
Cannot install haxe from repository Ubuntu 16.04

### ISSUE THREAD

**Issue by desttinghim** [HaxeFoundation/haxe#5344]
I am trying to install Haxe on my laptop running Ubuntu 16.04 Xenial. However, I cannot get apt to use the Haxe repository. This is the error I am getting:
```
E: The repository 'http://ppa.launchpad.net/haxe/releases/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
I asked on the IRC and waneck asked me make an issue. He thinks that there is no release yet, and after looking through the packages, that seems correct.

**Comment by andyli** [comment]
In fact, there is already haxe 3.2.1 in the default ubuntu repo, so I didn't duplicate that for our HF PPA. I will upload a haxe 3.3 package to there once it has been released.

I will keep this open before I updated the doc on the download page.

**Comment by andyli** [comment]
Thinking about it again, may be it would be simpler to have packages for all ubuntu versions. I've uploaded a version for 16.04, and will do so for later ubuntu versions as well.
