### ISSUE TITLE
[php/php7/cs] EReg.matched() doesn't throw exception for non-existing group

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5352]
The Haxe API documentation at http://api.haxe.org/EReg.html#matched states:

```
If no such sub-group exists, an exception is thrown
```

On C#/PHP targets however no exception is thrown, but null is returned.

Example:

``` haxe
class Test {
    static function main() {
        var pattern = ~/test/g;
        pattern.match("test");
        trace(pattern.matched(1));  // prints "null" on PHP, but should throw an exception
    }
}
```

**Comment by RealyUniqueName** [comment]
It's impossible to get number of subgroups on php. I propose to change API instead :) Let's make it "returns null for non-existent subgroups" instead of throwing.

**Comment by RealyUniqueName** [comment]
Oh, wait

**Comment by RealyUniqueName** [comment]
It's possible using [preg_match_all](http://php.net/manual/en/function.preg-match-all.php), but it will introduce performance penalty because this function always try to find all matches.

**Comment by sebthom** [comment]
Same issue with C#

**Comment by RealyUniqueName** [comment]
According to [the test](https://github.com/HaxeFoundation/haxe/blob/68edc60526f461147f945f5a85789413bf0c86ef/tests/unit/src/unit/TestEReg.hx#L25) this is unspecified. 
@ncannasse What is the correct spec: the doc or the test?

**Comment by ncannasse** [comment]
The test is correct, we need to update the documentation
