### ISSUE TITLE
Code completion broken for some projects in 3.3.0-rc2

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5354]
Hi @Simn,

When I switched to Haxe 3.3.0-rc2, I hit the assertion at https://github.com/HaxeFoundation/haxe/blob/3.3.0-rc1/src/display/display.ml#L305 while using code completion with the vscode-haxe plugin (in a mildly complex project. A trivial project worked fine.)

The function seems to be related to imports, and it seems to be an unexpected condition. Is it related to the import statements themselves, or something else?

I'm able to change the .ml and recompile to test things if it helps.

Thanks,
-Jeff

**Comment by Simn** [comment]
I tried to blind-fix this, let me know if it helped.

**Comment by jcward** [comment]
@Simn this appears to have resolved the issue as far as I can tell.

Given your commit comment, is it possibly related to something like this upper-case right-hand argument of this "as" statement?

```
import pkg.Class as OtherClass;
```

**Comment by Simn** [comment]
I think it was a static import of an uppercase field, e.g. `import Module.Type.CONST`.
