### ISSUE TITLE
Uncaught ReferenceError: DOMPoint is not defined in Chrome, Internet Explorer

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#5355]
Please try http://try.haxe.org/#e1a0d or http://try.haxe.org/#DecB8
Chrome - there is an error
Internet Explorer - there is an error
Opera 38.0 - there is an error
Safari 9.1.1 - there is an error
FireFox - no error

**Comment by Simn** [comment]
This doesn't look like something we could fix.
