### ISSUE TITLE
Problem with class exclude macros and compilation server

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5357]
I'm working on a Haxe/JS modular build system that makes heavy use of the class exclusion macros in `haxe.macro.Compiler`. When I try to use the compilation server with this build system, classes are missing from the output.

I have a simplified testcase with a more detailed description here: https://github.com/jcward/haxe_server_exclude_test

The test is very simple and there's a difference in output between `haxe build.hxml` (no server) and `haxe --connect 6000 build.hxml` (using a server), so hopefully it can help identify the issue.

Looking forward to faster builds, thanks!

**Comment by ncannasse** [comment]
The problem might be that you're reusing the same compilation context because the compilation parameters are the same, but they end up giving different results depending if the class is ignored or not. Adding a specific define for each compilation step should do the work.

**Comment by jcward** [comment]
Indeed, adding a define unique to each step did the trick. Thanks!
