### ISSUE TITLE
[cs] Fails to compile cs.Pointer.add on Visual C# with -dce no

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5360]
https://github.com/HaxeFoundation/haxe/blob/1c79168a33163acb82ed6d26ab59dc8d11768287/std/cs/Pointer.hx#L91-L94

I got error CS0214 here because unsafe code cannot be used without unsafe context. Simply adding `@:unsafe` to this method doesn't fix the problem. I got CS0208 instead (because it tries to take pointer from unknown type 'T'?).

https://msdn.microsoft.com/en-us/library/30ews7ac.aspx
https://msdn.microsoft.com/en-us/library/x2estayf.aspx

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
