### ISSUE TITLE
python tests failing

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5366]
Some recent change must have caused this, but since python is the only target failing it's most likely something genpy-specific:

```
Command: python3 [bin/unit.py]
Test.hx:294: Generated at: 2016-06-11 17:35:05
Test.hx:296: START
TestSerialize.hx:66: null should be 2
TestSerialize.hx:67: null should be -465
```

@nadako: Could you take a look?

**Comment by nadako** [comment]
This is a case of evaluation order differences.

The generated code is this:
```python
h1.h[self.unserialize()] = self.unserialize()
```

The problem here is that the second `self.unserialize()` is evaluated before the first one, unline e.g. JavaScript, so it sets values as keys and vice-versa.

So you need to add some case for Python in your fusion stuff :)

**Comment by nadako** [comment]
This makes me think we should have some per-platform function that returns whether we should tempvar an expression to preserve evaluation order.

**Comment by Simn** [comment]
I have hack-fixed this by adding a special case to the analyzer which clearly shouldn't be there. The problem is that what we have at that point is a mere `TCall(arraySet, [e1;e2;e3])` which natively has an evaluation order of `e3 -> e1 -> e2`. This goes against the usual semantics so it's not a good way to encode this.

We should really look into this after 3.3.

**Comment by nadako** [comment]
I can't find the hack-fix in our codebase anymore, it seems to be removed in 055801388839d1935b96f94fa0e3e1566130b272 and tests still pass now, so I'm considering this fixed.
