### ISSUE TITLE
haxe/Int32.hx multiplication performance on javascript

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5367]
I think haxe should polyfill Math.imul and use it.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul

```
Math.imul = Math.imul || function(a, b) {
  var ah = (a >>> 16) & 0xffff;
  var al = a & 0xffff;
  var bh = (b >>> 16) & 0xffff;
  var bl = b & 0xffff;
  // the shift by 0 fixes the sign on the high part
  // the final |0 converts the unsigned value into a signed value
  return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
};
```

Using Math.imul V8 is one order or magnitude faster.

## Benchmark results:
```
current Int32.mul: 178
using Math.imul: 9
```

## Benchmark code:
```
import haxe.Int32;

class Mul32 {
    static private function now() return Date.now().getTime();

    static public function main() {
        MathPolyfill.ensure();

        benchmark('current Int32.mul', function() {
            var a:Int32 = 0;
            for (n in 0 ... 10000000) {
                var m:Int32 = n;
                a = a * m;
            }
            return a;
        });

         benchmark('using Math.imul', function() {
            var a:Int32 = 0;
            for (n in 0 ... 10000000) {
                var m:Int32 = n;
                a = Math2.imul(a, m);
            }
            return a;
        });
    }

    static private function benchmark(name:String, callback: Void -> Int) {
        var start = now();
        callback();
        var end = now();
        trace(name + ': ' + (end - start));
    }
}

class MathPolyfill {
    static public function ensure() {
        untyped __js__("
            Math.imul = Math.imul || function(a, b) {
              var ah = (a >>> 16) & 0xffff;
              var al = a & 0xffff;
              var bh = (b >>> 16) & 0xffff;
              var bl = b & 0xffff;
              // the shift by 0 fixes the sign on the high part
              // the final |0 converts the unsigned value into a signed value
              return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
            };
        ");
    }
}

@:native("Math") extern class Math2 {
    static public function imul(a:Int32, b:Int32):Int32;
}
```

**Comment by Simn** [comment]
I agree we should have imul instead of the current optimization we're doing, which is not completely sound anyway.

**Comment by nadako** [comment]
But haxe should use `Math.imul` if it's available since e2d30484fa1445402a98558a40bf1269e648065e. Isn't that enough?

**Comment by soywiz** [comment]
It is included/works on haxe 3.3? Or maybe that part is stripped out because a optimization?

```
haxe -version && haxe -main Mul32 -js out.js && node out.js
3.3.0
current Int32.mul: 182
using Math.imul: 9
```

**Comment by nadako** [comment]
Wow, that's SUPER WEIRD. If I comment this from the output of your test (so it uses haxe's implementation of imul which is the same as the polyfill):
```js
if(Math.imul != null) {
	haxe__$Int32_Int32_$Impl_$.mul = Math.imul;
}
```
I'm getting
```
current Int32.mul: 47
using Math.imul: 23
```

However if I test this (which _should_ be the same as the `haxe__$Int32_Int32_$Impl_$.mul = Math.imul`):
```haxe
class A {
    public static var imul = untyped Math.imul;
}
```

I'm getting:
```
current Int32.mul: 289
A.mul: 21
using Math.imul: 23
```

Could it be that V8 has something against `$` symbols here, or wtf is going on?

**Comment by nadako** [comment]
We might want to look into it for 3.3, since it's a ~10x performance regression.

**Comment by nadako** [comment]
Also note, that the benchmark isn't very accurate: probably because of some JIT-warmups, the first loop will always be slower.

But anyway, if I comment out the original implementation of `Int32.mul` like this:
```js
var haxe__$Int32_Int32_$Impl_$ = {};
// haxe__$Int32_Int32_$Impl_$.mul = function(a,b) {
// 	return a * (b & 65535) + (a * (b >>> 16) << 16 | 0) | 0;
// };
if(Math.imul != null) {
	haxe__$Int32_Int32_$Impl_$.mul = Math.imul;
}
```
I get:
```
current Int32.mul: 20
using Math.imul: 23
```
So looks like v8 doesn't like overriding methods like that at all... Hm. Any JS experts here?

**Comment by soywiz** [comment]
Maybe it has already optimized the benchmark function, and deoptimizes it because you have changed one of its constraints: haxe__$Int32_Int32_$Impl_$.mul.

Ideally you could select implementation with a compiletime metadata, which could select the implementation while generating types:

```
var haxe__$Int32_Int32_$Impl_$ = {};
haxe__$Int32_Int32_$Impl_$.mul = function(a,b) {
	return a * (b & 65535) + (a * (b >>> 16) << 16 | 0) | 0;
};
```

-->

var haxe__$Int32_Int32_$Impl_$ = {};
if (Math.imul) {
haxe__$Int32_Int32_$Impl_$.mul = Math.imul;
} else {
haxe__$Int32_Int32_$Impl_$.mul = function(a,b) {
	return a * (b & 65535) + (a * (b >>> 16) << 16 | 0) | 0;
};
}

For example "a proposed @:jsbody meta" could be:
```
@:jsbody(cond="Math.imul", body = "Math.imul")
@:op(A * B) private static function mul(a:Int32, b:Int32):Int32
	return clamp( (a : Int) * ((b : Int) & 0xFFFF) + clamp( (a : Int) * ((b : Int) >>> 16) << 16 ) );
```

**Comment by soywiz** [comment]
Another option could be this one (easier and already works):

```haxe
abstract Int32(Int) from Int to Int {
    @:op(A * B) private #if js inline #end static function mul(a:Int32, b:Int32):Int32 
        #if js
        return untyped __js__("Math.imul({0}, {1})", a, b);
        #else
        return clamp( (a : Int) * ((b : Int) & 0xFFFF) + clamp( (a : Int) * ((b : Int) >>> 16) << 16 ) );
        #end

    inline static function clamp( x : Int ) : Int return x | 0;

    static public function __init__() {
        #if js
        untyped __js__("
            Math.imul = Math.imul || function(a, b) {
                var ah = (a >>> 16) & 0xffff;
                var al = a & 0xffff;
                var bh = (b >>> 16) & 0xffff;
                var bl = b & 0xffff;
                return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
            };
        ");
        #end
    }
}
```

**Comment by mcheshkov** [comment]
Here's some tips for v8 runtime (de)optimizations checking [link](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers)

On my machine (linux, node 4.4.5, v8 4.5.103.35) none of this actually deoptimize. But, if I replace field `haxe__$Int32_Int32_$Impl_$.mul` with variable `haxe__$Int32_Int32_$Impl_$_mul` it work like it should. And if i make a local var before loop, like `var haxe_mul = haxe__$Int32_Int32_$Impl_$.mul;` it;s also fast. So, IMHO, that's just field access in tight loop that slows down.

**Comment by Simn** [comment]
> I agree we should have imul instead of the current optimization we're doing, which is not completely sound anyway.

Ignore me, for some reason I was thinking of idiv.

**Comment by nadako** [comment]
Alright, I've [fixed this in a quite ugly way](https://github.com/HaxeFoundation/haxe/commit/9b08358c17a5f74b1b8eaff5bbac4de566d7d040), but from the generated code standpoint it's pretty idiomatic JS code :-) Like this:
```js
var haxe__$Int32_Int32_$Impl_$ = {};
haxe__$Int32_Int32_$Impl_$._mul = Math.imul != null?Math.imul:function(a,b) {
	return a * (b & 65535) + (a * (b >>> 16) << 16 | 0) | 0;
};
```

Now the test outputs:
```
current Int32.mul: 21
using Math.imul: 23
```
Should be fine.

**Comment by nadako** [comment]
And thanks for reporting this @soywiz!

**Comment by nadako** [comment]
Also, I kind of like this idea:
```haxe
@:jsbody(cond="Math.imul", body = "Math.imul")
@:op(A * B) private static function mul(a:Int32, b:Int32):Int32
```
However, I'm not sure how much uses will it have in Haxe std lib and if it's really worth it to introduce yet another metadata for that.
