### ISSUE TITLE
Double the speed of haxe:js Std.is/instanceof?

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5368]
I am doing some research regarding to javascript performance in jtransc. One subject of test is instanceof / Std.is:

https://github.com/jtransc/jtransc/blob/a0f98f1ee6c1132f0f3ae19973a1b2397bdfd776/benchmark/src/Benchmark.java#L69
I'm working on an alternatie pure-js target and comparing performance: https://github.com/jtransc/jtransc/tree/a0f98f1ee6c1132f0f3ae19973a1b2397bdfd776/jtransc-gen-js

plain-js:
```
:runPlainJs
Benchmarking:
plain loops...8
call static mult...14
call instance mult...13
call instance div...74
instanceof classes...316
write int[]...28
write float[]...31
simd...30
```

haxe-js:
```
:runJs
Benchmarking:
plain loops...8
call static mult...13
call instance mult...13
call instance div...73
instanceof classes...662
write int[]...32
write float[]...34
simd...30
```

How I did that? https://github.com/jtransc/jtransc/commit/a0f98f1ee6c1132f0f3ae19973a1b2397bdfd776

When building types I create an integer unique id for that type: including classes and interfaces. Then I create a table (a plain javascript object) with those ids as keys. Then when performing an instanceof, I check that table instead.
That works for interfaces too, so it is just a single existence lookup.
So the instanceof function looks like this:
```
N.is = function(i, clazz) { return (i != null) ? (typeof clazz.$$instanceOf[i.$JS$CLASS_ID$] !== "undefined") : false; };
```

Not sure if it is easy to backport to haxe, or if it is interesting or not, but I wanted to notice it, so you can evaluate it.

**Comment by back2dos** [comment]
I think we'll still want Std.is to work with native types too. Particularly for `Array` and `String` this is going to get a little messy (I guess in the end we'd just have to add the additional field `$JS$CLASS_ID$` there).  At the same time I would argue that code that does a lot of Std.is is not very Haxe idiomatic to start with, so I'm not sure this is worth such an invasive change.

More importantly, this doesn't strike me as an optimization that would be hard to implement right in any JavaScript runtime, in which case it's only a matter of time until the native operator becomes faster. Have you considered raising an issue with the most popular ones? That way everybody gets to benefit from the improvement.

**Comment by nadako** [comment]
I agree with @back2dos here, this doesn't sound like a worthy investment.

**Comment by soywiz** [comment]
Ok. Was just a suggestion :)

You can still use instanceof for native types on direct Std.is, and 
"a instanceof type || trick" on dynamic cases.

But I think that detecting interfaces is done by iterating:
https://github.com/HaxeFoundation/haxe/blob/development/std/js/Boot.hx#L174
Which probably must be slower.

And these are haxe specific and are not going to get improved by javascript engines improving instanceof which if not optimized that much already, is probably because it is complex.

Anyway I do not really need this on haxe. It was just a suggestions based on my experiments. Generally instanceof is used on patternmatching, that in some cases is heavyly used.

**Comment by back2dos** [comment]
Oh, right, I forgot all about `Boot.__interfLoop`! Indeed, we could speed that one up this way and leave the rest of `Std.is` as it was. Thanks for the hint ;)

**Comment by Simn** [comment]
I don't see much of a point discussing things that could be done and maybe speed up something, so this should probably be turned into a pull request.
