### ISSUE TITLE
[php] Add haxe source file line number on -debug

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#5376]
Hej !

As the title of the topic suggest, It would be great to add haxe source file line number when an excpetion in thrown in -debug mode on PHP target.

Thanks

**Comment by Simn** [comment]
Frankly, this is probably not something that can just be switched on and would require some work which currently nobody could really do. I'm not opposed to the idea, but we might as well close this issue because the likelihood of it being implemented (by us) is very low.
