### ISSUE TITLE
[cpp] Non final inlined returns in a static variable generate invalid C++

### ISSUE THREAD

**Issue by MrCoft** [HaxeFoundation/haxe#5378]
I encountered this error by assigning a `{ call(); }` expression to a static variable, where the call was a static inlined function with multiple returns.
`A ? B : C` achieves the same:
```
static function bool():Bool return true;
static var CONSTANT = bool() ? 1 : 0;
```
It passes the Haxe compiler and cl.exe gives this error:
```
./src/Main.cpp(130) : error C2059: syntax error : 'if'
./src/Main.cpp(130) : error C2143: syntax error : missing ';' before '{'
./src/Main.cpp(133) : error C2181: illegal else without matching if
```
The C++ in question:
```
CONSTANT = if (::Main_obj::_hx_bool()) {
    (int)1;
}
else {
    (int)0;
}
```
Neko, flash and html5 targets are fine.
It does not occur for class variables and local variables in functions, it is static only.

**Comment by Simn** [comment]
This is the same as #5358.
