### ISSUE TITLE
Haxe API compatibility test suite for targets

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5381]
I developed multiple Haxe libraries in the last months that are extensively unit tested. While testing my libraries against the different targets I encountered a lot of situations where functions of the standard library are either broken on some targets or don't behave as documented.

I would therefore suggest the development of a compatibility test suite (something like a [TCK](https://en.wikipedia.org/wiki/Technology_Compatibility_Kit)) that contains extensive unit tests of the Core Haxe API spec and that can be used ensure the correct implementation of Haxe targets.

I would also suggest to embody an approach like Python's doc testing - which I implemented for Haxe in this library: [haxe-doctest](https://github.com/vegardit/haxe-doctest). Doc testing has the advantage that the assertions specified in the Haxedoc function as user documentation and actual unit tests at the same time. And since the assertions are extracted from the Haxedoc it basically tests the Haxedoc as well, ensuring that the documented behavior is always in sync with the actual method implementation.

**Comment by nadako** [comment]
Ooh, nice I've been wanting to implement doctests for haxe for a long time, but never had time for it, we should definitely look into this.

**Comment by ncannasse** [comment]
We have a lot of unit tests already here:
https://github.com/HaxeFoundation/haxe/tree/development/tests/unit/src/unitstd

We should aim to have them covering 100% of the API specification, but we lack the manpower to do it. If there's anybody wanting to help with that by pushing the corresponding PR we would be glad to have them merged.

**Comment by sebthom** [comment]
So if man power is the problem than maybe the "process" of creating unit tests should be improved in a way that makes unit testing less time-consuming/annoying/boring and better integrating it into the coding flow by reducing context switches that are occur when unit testing is performed with separate test classes and methods. Hence my suggestion to introduce doctest style unit testing. 

If someone has time to introduce a new function he must at least have the time to document it and then certainly also finds the twenty seconds to add some inline doctest assertions. Also, doctest assertions can be used instead of free text documentation. Say for example atm you write "if arg1 is null, then null will be returned", with doctest you instead something like "MyClass.myFunction(null) == null" to your Haxedoc. Same effort, users understand the API usage by reading the API doc, and the scenario is unit tested.

With doctests you also can directly see in source code which functions are still missing test cases and you don't have to go to some other directory and dig throw dozen of unit files trying to figure out if a particular scenario has been tested.

**Comment by nadako** [comment]
I should say I love the idea of doctests and I have used it very successfully in my Python days (e.g. https://pypi.python.org/pypi/z3c.sharedmimeinfo/) and would love to see how it works for Haxe. I have a concern about testing of edge cases which should be done somewhere, but the method doc aren't a good place IMO. Also Haxe by nature leaves many things (like e.g. passing `null`) unspecified and we can't really doctest this, unfortunately.

**Comment by sebthom** [comment]
Of course, things that are currently left unspecified should be documented as such - which already is done in a lot of places.

I actually find doctests a great place for documenting/testing edge cases because those are questions a developer has when working with APIs. He needs to decide if he has to do bound checks or add guards before invoking a function or if he can be confident the function behaves reasonable with "invalid" input values.

**Comment by Simn** [comment]
I'm not opposed to the idea, but somebody would have to get this started. Fair warning that it's a very annoying task.

**Comment by ncannasse** [comment]
I'm fine with any process as long as someone actually contributes it :)

**Comment by Simn** [comment]
Closing this issue as it's not actionable.
