### ISSUE TITLE
[js] Invoking reflected instance method does not work like on all other targets

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5382]
This is a follow-up to #5307. 

I am asking for clarification why the following code 
```haxe
var m = Reflect.field(this, "myMethod");
m("foo");
```
should not behave exactly the same as
```haxe
var m = this.myMethod;
m("foo");
```
Which it does so on all targets, except JavaScript, where a "TypeError: undefined is not an object" is thrown.

**Comment by Simn** [comment]
Please don't open the same issue twice, that only fragments the discussion.
