### ISSUE TITLE
Unexpected "String must be Bool" when using inline try catch

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5384]
The following code fails in the last assignment with "String should be Bool". I guess it is some type interference related to try catch blocks, but isn't that too strict?

``` haxe
class Test {
    static function main() {
        var a:Dynamic = true;
        a = "string";

        var b:Dynamic = if (myFunc()) true else "string";

        var c:Dynamic = myFunc() ? true : "string";

        var d:Dynamic = myFunc() ? myFunc() : "string";

        var e:Dynamic = try myFunc() catch(e:Dynamic) "string";
    }

    static function myFunc():Bool {
        return true;
    }
}
```

I of course could rewrite it in the following way but that seems unnecessarily verbose:

``` haxe
class Test {
    static function main() {
        var e:Dynamic = null
        try {
           e = myFunc();
        } catch(e:Dynamic) {
           e ="string";
        }
    }

    static function myFunc():Bool {
        return true;
    }
}
```

**Comment by nadako** [comment]
this looks like it should indeed unify since the expected type is Dynamic

**Comment by sebthom** [comment]
When compiling the following code:
```haxe
class Test {
    static function main() {
        var result:String = try true catch(e:Dynamic) "string";
    }
}
```
I get the expected error `Test.hx:3: characters 8-63 : Bool should be String` for the invalid assignment of a Bool value to a String variable, but I also get the unexpected error `Test.hx:3: characters 54-62 : String should be Bool` which complains about the value in the catch block needing to be a Bool.

It get's even clearer if I am using another type for the result variable:
```haxe
class Test {
    static function main() {
        var result:Int= try true catch(e:Dynamic) "string";
    }
}
```
Here I would have expected that the compiler complains about a Bool not being an Int and a String not being an Int, but it complains about a String not being a Bool instead.

**Comment by nadako** [comment]
Well, those actually make sense because because that's the result of unification of a `catch` type with the `try` type, but I agree we could be a bit smarter and consider expected type here. Not sure how easy is to change this, though.

**Comment by Simn** [comment]
Should be easy, but I still don't want to risk it for 3.3.
