### ISSUE TITLE
Cannot unify Dynamic with Const

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5387]
```haxe
class A<Const> {}
typedef B = A<Dynamic>;
```

This worked in 3.2 but not 3.3

**Comment by Simn** [comment]
I think that shouldn't work. What are you trying to do here?

**Comment by kevinresol** [comment]
I tried to compile [dodrugs](https://github.com/jasononeil/dodrugs/blob/master/src/dodrugs) with Haxe 3.3 and it failed [here](https://github.com/jasononeil/dodrugs/blob/master/src/dodrugs/InjectorMapping.hx)

Maybe @jasononeil can have a look.

**Comment by jasononeil** [comment]
I guess if I'm going to experiment with crazy macro ideas I should be trying it on the most recent version of Haxe...

I'm really not sure of the semantics of using a `Const` type parameter outside of a genericBuild like you did here.  So I have no comment on the issue and whether or not it is a regression or a fix.  (Though I will say, nearly invariably, when I think I think I see a regression between Haxe versions Simn usually correctly points out that it is in fact a fix).

For that code of mine, [I've just commited a change][0] for that typedef, it now points to the underlying type and skips the genericBuild macro altogether. Hopefully that fixes it in Haxe 3.3.

[0]: https://github.com/jasononeil/dodrugs/commit/5aba3fedb05c6242b19da95b37cdfa9e621a9cda

**Comment by kevinresol** [comment]
@jasononeil it still doesn't compile on Haxe 3.3 and I think any further discussions should go back to the repo 
@Simn Please feel free to close this if it is considered as a fix rather than a regression.
