### ISSUE TITLE
Rest not as last argument

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5393]
In javascript, functions are often written as `function(arg1, arg2, ..., argN, callback)` where the number of arguments varies. So it would be nice if the "Rest must be last argument" can be relaxed.

For the compiler I hope it is not very different from now. It can first type-check the non-rest arguments (either in the beginning of the list or the end or both), and then remove them from the argument list. Then the remaining args can be checked against the Rest type.

**Comment by Simn** [comment]
Really?

**Comment by kevinresol** [comment]
"really" common in JS? Yes.
"really" easy to implement in compiler? I am not sure. 😛

**Comment by kevinresol** [comment]
Examples:
https://github.com/reactjs/reselect#createselectorinputselectors--inputselectors-resultfunc
https://github.com/NodeRedis/node_redis#sending-commands

**Comment by nadako** [comment]
I remember we discussed that a little but decided not to mess with argument processing then, but I agree it would be useful for JS externs.

**Comment by back2dos** [comment]
Is it actually common though?

As @kevinresol  said, in the two examples you can just use an array. Otherwise you're not doomed though, you just have to resort to something like this:

```haxe
@:overload(function(arg1:String, arg2:String, arg3:String, arg4:String, arg5:String, callback:Xyz->Void) {})
@:overload(function(arg1:String, arg2:String, arg3:String, arg4:String, callback:Xyz->Void) {})
@:overload(function(arg1:String, arg2:String, arg3:String, callback:Xyz->Void) {})
@:overload(function(arg1:String, arg2:String, callback:Xyz->Void) {})
function(arg1:String, callback:Xyz->Void) {}
```

Agreed, it's not pretty, but it gets the job done and if we're just talking about a couple of edge cases here, then I think it should do. 

But FWIW neither ES6 nor TypeScript support this.

**Comment by kevinresol** [comment]
@back2dos Make me think of something like this:
```haxe
@:build(RestMacro.build()) // macro that generates all the overloads
extern class Foo {
  function bar(rest:MacroRest<String, 20>, callback:X->Void); // max 20 String args
}
```

**Comment by Simn** [comment]
This is too crazy for me, tell the JS libraries that do this to stop goofing around.
