### ISSUE TITLE
[lua] compiler conditional "#if lua" not working

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5395]
I am trying to use the following statement in https://github.com/vegardit/haxe-doctest/blob/master/src/hx/doctest/DocTestGenerator.hx
```haxe
    #if lua
        static inline var MAX_ASSERTIONS_PER_TEST_METHOD = 10; // to avoid "too many local variables" with Lua target
    #else
        static inline var MAX_ASSERTIONS_PER_TEST_METHOD = 100; // to avoid "error: code too large" with Java target
    #end
```
But in Haxe 3.3.0RC1 it compiles the second and not the first variable assignment when targeting Lua.

Trying to specify "-D lua" when compiling results in 
```
Error: : lua is a reserved compiler flag and cannot be defined from command line
```

**Comment by Simn** [comment]
Somehow I doubt that... please double-check.

**Comment by sebthom** [comment]
Maybe it is related to the fact that it's a macro. That's what I get:
![lua](https://cloud.githubusercontent.com/assets/426959/16268235/df682ddc-388d-11e6-976d-e1da00c6b1cb.png)

**Comment by Simn** [comment]
Yes you don't have lua defined in macro environment. Check out http://api.haxe.org/haxe/macro/Context.html?#defined to get defines from the outside context.

**Comment by sebthom** [comment]
I changed my code to:
```haxe
    static var MAX_ASSERTIONS_PER_TEST_METHOD = Context.defined("lua") ?  40 : 100;
```
This still doesn't work with Lua.

However trying the same with e.g. neko or java, works as expected.
```haxe
    static var MAX_ASSERTIONS_PER_TEST_METHOD = Context.defined("neko") ?  40 : 100;
```
