### ISSUE TITLE
Escape `</script>` in JS string literals

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5396]
This is not particularly important, but if you want to embed haxe generated JS into HTML, then it shouldn't contain the character sequence `</script>`, which can occur in string literals as demonstrated here: http://try.haxe.org/#Cdb3e

```html
	<!-- snip -->
		<script>(function (console) { "use strict";
var Test = function() { };
Test.main = function() {
	console.log("</script>"); //<-- kaboom
};
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});
</script>
   <!-- snap -->
```

Escaping it as `<\/script>` would do.

Slightly amusing observation: the code highlighting on GitHub seems to get it right.

**Comment by fponticelli** [comment]
Another way of escaping the output might be `"</"+"script>"`

**Comment by nadako** [comment]
not sure if we should do something about it or not. one option would be to provide some optional genjs feature that processes every string and escapes this.

**Comment by back2dos** [comment]
If we want to do something about it (which I'm not sure about either), then I think it should be the default.

**Comment by Simn** [comment]
Let's not mess with this by default, it's easy enough to handle this manually or using some onAfterGenerate post-processing.

**Comment by back2dos** [comment]
For future reference: Closure in white-space only mode solves these types of issues.
