### ISSUE TITLE
import.hx breaks compilation server cache?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5397]
Reproducible code and steps here: https://github.com/kevinresol/test-compilation-server/tree/cache

Seems import.hx prevent some compilation cache to be used.

**Comment by Simn** [comment]
I don't really know what I'm doing but please try now.

**Comment by kevinresol** [comment]
Yeah it seems to work now.

**Comment by ncannasse** [comment]
MImport seems fine as-it. To be perfectly valid, it would require to check if we have inserted new import.hx in one of the subdirectories that might shadow it, but I guess we can live without it.

**Comment by Simn** [comment]
They shouldn't shadow each other but aggregate... at least that's how I wanted to implement it.

**Comment by ncannasse** [comment]
Yes, but aggregation might lead to shadowing the definitions, and in all cases this require to recompile the whole files in the affected directories

**Comment by Simn** [comment]
What definitions, we only allow import and using there anyway.

**Comment by ncannasse** [comment]
the imported type definitions. let's say that I have  "import Math.*" in    a/import.hx and that I add a new "import MyClass.*" in a/b/import.hx, MyClass having a function cos, it should use this one instead of the Math one.

**Comment by Simn** [comment]
Ah that's what you mean. That's probably a variant of #4697.
