### ISSUE TITLE
[neko] [tora] First query-string parameter in url incorrectly parsed?

### ISSUE THREAD

**Issue by rb1147x** [HaxeFoundation/haxe#5408]
Hello,

It appears that `neko.Web.getParamsString()` incorrectly parses the first query-string parameter.

Given a URL: `http://mywebsite.com/index.n?test=1&test2=323` the result shows below:

```
Hello from Tora!
Main.hx:9: {test2 => 323, q => /tora/test/index.ntest=1}
```

If this URL is used: `http://mywebsite.com/index.n?&test=1&test2=323` (notice the & in front of the first query-string) the result shows correct:

```
Hello from Tora!
Main.hx:9: {test => 1, test2 => 323, q => /tora/test/index.n}
```

I don't think I've ever seen an initial & after the ?, but just to double check I referenced https://en.wikipedia.org/wiki/Query_string

Thanks!

**Comment by R32** [comment]
but my results seem to be correct :)

screenshot: 
![result](https://cloud.githubusercontent.com/assets/6825113/16358045/999443ae-3b3a-11e6-8655-3dfac4b35040.png)

**Comment by rb1147x** [comment]
Hmm, my results are below. The error is from `neko.Web.getURI()`

![capture](https://cloud.githubusercontent.com/assets/17628197/16358822/e68efa6e-3ae5-11e6-8200-577a0789ff3f.PNG)

**Comment by R32** [comment]
May be caused by `-dce full`, like this https://github.com/HaxeFoundation/tora/pull/9

**Comment by rb1147x** [comment]
No change in my results when changing the flag ;/

**Comment by Simn** [comment]
Probably not a Haxe issue, please report to https://github.com/HaxeFoundation/tora/issues
