### ISSUE TITLE
Make install does not work on OSX El Capitan

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5409]
Because the OS no longer allow writing to `/usr/lib`. We have to use `/usr/local/lib`
http://stackoverflow.com/questions/33309005/sudo-mkdir-in-usr-operation-not-permitted-el-capitan

**Comment by andyli** [comment]
Really, the default install prefix should be `/usr/local` on Unix system (including both Mac and Linux). The `/usr/bin` and `/usr/lib` directories are for softwares managed or shipped by the OS. i.e. The Linux packages from the official distro repositories should install into `/usr`; all other software's default installation prefix should be `/usr/local`.

However, I'm not sure it is the right time to change the default installation location. We probably should do it after 3.3 release.

**Comment by andyli** [comment]
For now, one may set the `INSTALL_DIR` variable to change the install destination:
```
make install INSTALL_DIR=/usr/local
```

**Comment by mastef** [comment]
Changing https://github.com/HaxeFoundation/haxe/blob/development/Makefile#L13 to `INSTALL_DIR=$(DESTDIR)/usr/local` works

Would be good to make a note here about @andyli's solution meanwhile : https://haxe.org/documentation/introduction/building-haxe.html
