### ISSUE TITLE
Adding WebGL2RenderingContext to extern?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5410]
Currently `WebGLRenderingContext `is available as `js.html.webgl.RenderingContext`. In what name `WebGL2RenderingContext` should be available? Maybe `js.html.webgl.RenderingContext2`?

This is still an experimental feature, though, I think it should be available once its spec is stabilized.

https://developer.mozilla.org/en/docs/Web/API/WebGL2RenderingContext

**Comment by Simn** [comment]
This is an issue for https://github.com/HaxeFoundation/html-externs
