### ISSUE TITLE
[swf] Injected Array methods doesn't work with a loader

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#5411]
Haxe:

```
class Test {
        static public function main() {
                var array = [];
                array.push(1);
                array.insert(0, 2);
                trace(array);
        }
}
```

AS3:

```
package {
import flash.display.Loader;
import flash.display.Sprite;
import flash.net.URLRequest;
import flash.system.ApplicationDomain;
import flash.system.LoaderContext;
import flash.utils.setTimeout;

public class Main extends Sprite {
    public function Main() {
        setTimeout(test, 0);
    }

    private function test():void {
        var loaderContext:LoaderContext = new LoaderContext();
        loaderContext.applicationDomain = new ApplicationDomain(); // FAILS
        //loaderContext.applicationDomain = new ApplicationDomain(ApplicationDomain.currentDomain); // WORKS
        var loader:Loader = new Loader();
        loader.load(new URLRequest('out.swf'), loaderContext);
        addChild(loader);
    }
}
}
```

It should work, even without a parent ApplicationDomain. And we cannot change the loader code.

Compiling haxe:
`haxe -swf-version 15 -main Test Test -swf out.swf`

<img width="1263" alt="screen shot 2016-06-24 at 11 03 20" src="https://cloud.githubusercontent.com/assets/570848/16333399/540ea918-39fb-11e6-8048-3033ac1bd2d6.png">

I'm attaching binary files:

[swf_files.zip](https://github.com/HaxeFoundation/haxe/files/331501/swf_files.zip)

I have seen pretty nasty stuff:
https://github.com/HaxeFoundation/haxe/blob/development/std/flash/Boot.hx#L235

Generated as3 seems to be like this:

<img width="485" alt="screen shot 2016-06-24 at 11 05 15" src="https://cloud.githubusercontent.com/assets/570848/16333446/94267a1c-39fb-11e6-855e-74b154c8056e.png">
<img width="427" alt="screen shot 2016-06-24 at 11 05 22" src="https://cloud.githubusercontent.com/assets/570848/16333445/942543b8-39fb-11e6-8156-887c05241ceb.png">

Not sure if that's incompatible with the loader (that kind of initialization). Maybe it would be better call init methods directly in the boot__file?

**Comment by soywiz** [comment]
I have done a further investigation. I have changed the Test.hx with this:

```
package flash;

class Test implements Dynamic {
	static public function main() untyped {
		var aproto = Array.prototype;
		aproto.copy = function() {
			return __this__.slice();
		};
		aproto.insert = function(i,x) {
			__this__.splice(i,0,x);
		};
		aproto.remove = function(obj) {
			var idx = __this__.indexOf(obj);
			if( idx == -1 ) return false;
			#if flash19
			__this__.removeAt(idx);
			#else
			__this__.splice(idx,1);
			#end
			return true;
		}
		aproto.iterator = function() {
			var cur = 0;
			var arr : Array<Dynamic> = __this__;
			return {
				hasNext : function() {
					return cur < arr.length;
				},
				next : function() {
					return arr[cur++];
				}
			}
		};
		aproto.setPropertyIsEnumerable("copy", false);
		aproto.setPropertyIsEnumerable("insert", false);
		aproto.setPropertyIsEnumerable("remove", false);
		aproto.setPropertyIsEnumerable("iterator", false);

		var array = [];
		array.push(1);
		array.insert(0, 2);
		trace(array);
	}
}
```

And it doesn't work either. So it seems that the .prototype hack doesn't work with an empty ApplicationDomain. So my suggestion is totally avoid using that prototype, and change them to static method calls.

**Comment by Simn** [comment]
I'm not sure if this can be fixed, the SWF output relies on some initialization taking place.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
