### ISSUE TITLE
type safe exceptions

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#5412]
Hey,

What are your thoughts on "type safe" exceptions, like java's `throws`?
Do you think it could be a good addition for haxe? (4 I guess).

Because `catch (e:Dynamic)` isn't very good,
also if you think it returns a String, but doesn't, then you'll "silently" catch nothing.

Side thing it the usage of strings in the std (or neko's?) is this pattern: `catch (e:String) switch (e)`.
Also string seems heavy, what about enums? `enum IoError { NoSuchFile; CantOpen; }`

Not sure what's a good solution, but I think we need something,

sorry if that was already discussed and I missed it :)

**Comment by Simn** [comment]
I'm ambivalent about this. On the one hand I quite like the concept that Java has here, but on the other hand i find the need to deal with it very obnoxious.

**Comment by nadako** [comment]
I don't use exceptions much, but I sometimes feel like it would be useful to have catch work like pattern matching, e.g. `catch (NoSuchFile(filename)) if (fileName.endsWith(thisFile)) {...}`. This would require type matching functionality though.

**Comment by Simn** [comment]
This would require an evolution proposal.
