### ISSUE TITLE
Autocomplete broken for packages started from underscore

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#5417]
Autocomplete inside class from package like "_pack" say "Error: Display file was not found in class path".

Open _bad/MyBad.hx in FlashDevelop and try autocomplete.
[UnderscoreIssue.zip](https://github.com/HaxeFoundation/haxe/files/335895/UnderscoreIssue.zip)

**Comment by Simn** [comment]
I think that's by design, but I let @ncannasse confirm that to be sure.

**Comment by ncannasse** [comment]
Are packages starting with underscore actually allowed in language spec?

**Comment by Simn** [comment]
Given our "specification is implementation" approach, kinda...

**Comment by RealyUniqueName** [comment]
ping @ncannasse

**Comment by ncannasse** [comment]
if the packages are allowed and compilation is successful, then it should work with --display as well
