### ISSUE TITLE
Optional Arguments break when going through iOS AOT conversion

### ISSUE THREAD

**Issue by TomByrne** [HaxeFoundation/haxe#5421]
When building AIR for iOS, there seems to be an issue that only occurs when AOT conversion is done on the SWF.

This example should trace "0", and it does with a debug build.
When I do an Adhoc build though, it traces "NaN".

The issue does not occur with AIR SDK 19, but it does with 20 & 22beta.
Close the ticket if you think it's Adobe's issue.

```
class OptArgsIssue extends openfl.display.Sprite
{

	public function new() 
	{
		super();
		
		var testObj:IInterface = new TestType();
		testObj.func();
	}
	
}

interface IInterface
{
	function func(arg1:Float = 0):Void;
}

class TestType implements IInterface
{
	public function new() 
	{
		
	}
	public function func(arg1:Float = 0){
		trace(arg1);
	}
}
```

**Comment by Simn** [comment]
Unless someone shows that we're somehow generating invalid/unspecified bytecode I'll have to assume that it is indeed an Adobe issue.
