### ISSUE TITLE
[flash] Access errors with protected method and properties in SWC

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe#5422]
Hello, 

I met theses issues when I override a method declared in AS3 class embedded in a SWC, and between the AS3 class, and the class that override I have another Haxe class. 

With an example, it will be more understandable ;)

**In SWC**

``` actionscript
public class ClassA
{
    protected function init() : void
    {
    }
}
```

**In Haxe project**

``` haxe
class ClassB extends ClassA
{
    public function new() 
    {
        super();
    }   
}
```

``` haxe
class ClassC extends ClassB
{
    public function new() 
    {
        super();
    }

    override private function init() : Void
    {
    }
}
```

**Runetime issue**

``` console
[Fault] exception, information=VerifyError: Error #1053: Illegal override of init in ClassC.
[Fault] exception, information=ReferenceError: Error #1065: Variable boot_5fbf is not defined.
```

Same result with haxe 3.2.1, 3.0.0-rc1 and nightly build. 
Target Flash 11.5, run on Flash Player 22.

Find in attachment swf and HaxeDevelop project. 

[swf.zip](https://github.com/HaxeFoundation/haxe/files/343016/swf.zip)
[haxedevelop-project.zip](https://github.com/HaxeFoundation/haxe/files/343017/haxe-189.zip)

**Comment by Simn** [comment]
Does using `@:protected` on ClassC.init change anything?

**Comment by aliokan** [comment]
The same result, if I decompile swf without @:protected, the definition of ClassC.init is correct.

Result With SWFDecompiler : 
```actionscript
package 
{
    import ClassA.*;

    public class ClassA extends Object
    {

        public function ClassA()
        {
            return;
        }// end function

        protected function init() : void
        {
            return;
        }// end function

    }
}
```
```actionscript
package 
{

    public class ClassB extends ClassA
    {

        public function ClassB() : void
        {
            return;
        }// end function

    }
}
```
```actionscript
package 
{
    import ClassC.*;

    public class ClassC extends ClassB
    {

        public function ClassC() : void
        {
            return;
        }// end function

        override protected function init() : void
        {
            return;
        }// end function

    }
}
```

**Comment by aliokan** [comment]
I can avoid #1053 error message if classB override init. 
But if I try to execute init in ClassB or ClassC, I get : 
```
TypeError: Error #1006: init is not a function.
	at ClassC()
	at Main$/main()
	at boot_5fbf/init()
	at flash::Boot/start()
	at boot_5fbf()
```
And `Type.typeof(this.init)` return `TNull` in ClassB and ClassC.

**Comment by aliokan** [comment]
I still have issue with protected in SWC. 

New example : 
ClassA in SWC (actionscript) 
```actionscript
public class ClassA
{
	private var stringPrivate:String = "stringPrivate";
	protected var stringProtected:String = "stringProtected";
	public var stringPublic:String = "stringPublic";
}
```
ClassB in haxe
```haxe
class ClassB extends ClassA
{
	public function new() 
	{
		super();
		trace(this.stringPublic);
		trace(this.stringProtected);
	}
}
```
in console
```
ClassB.hx:14: stringPublic
ClassB.hx:15: null
```

SWC : builded with FlexSDK 4.12 compc to swf version 23
haxe 3.3.0-rc1 use to compile

Note that HaxeDevelop proposes protected method and properties in autocomplete

Find bellow haxeDevelop project with all sources : [haxe-189-b.zip](https://github.com/HaxeFoundation/haxe/files/358959/haxe-189-b.zip)

**Comment by aliokan** [comment]
@Simn @ncannasse little up guys :)

**Comment by ncannasse** [comment]
Are you using `-D swf-protected` ? try to disable it maybe

**Comment by aliokan** [comment]
Ì don't use ```-D swf-protected```
If I use it on [haxe-189-b.zip](https://github.com/HaxeFoundation/haxe/files/358959/haxe-189-b.zip), I get error : 
```
[Fault] exception, information=TypeError: Error #1006: start is not a function.
Fault, boot_5fbf() at Boot.hx:38
```

**Comment by Deirel** [comment]
Little up. Is here some progress?

**Comment by aliokan** [comment]
The only solution found was to put all protected in public. ;)

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
