### ISSUE TITLE
Haxe XML is Slow

### ISSUE THREAD

**Issue by championchap** [HaxeFoundation/haxe#5423]
Hey everyone,

I had some large XML files to parse at work, so I thought it might be smart to write it in Haxe/CPP instead of using PHP for the job. 

To check my assumptions before starting I wrote a little benchmark and was surprised by the results. 

[Here's the Repo](https://github.com/championchap/XMLBenchmark) so you can try for yourself. 

On my machine PHP is fastest, Haxe using Fast XML came second, and Haxe using Native XML was the slowest by far. What gives? 

    PHP took 0.27717399597168 seconds.
    Haxe/CPP (Fast XML) took 1.46754002571106 seconds.
    Haxe/CPP (Native XML) took 6.52165985107422 seconds.

I am using PHP 7.0.7 and Haxe 3.2.1.

**Comment by back2dos** [comment]
Many optimizers skip constructors for various reasons, so my advice is to not trust benchmarks from constructors as it may skew the results.

But in any case I wouldn't be surprised if the result stays the same. So if you need speed in XML, I suggest trying to compile for nodejs or java. They tend to perform best for anything string related.

**Comment by Simn** [comment]
Please try with 3.3.0-rc1.

**Comment by Simn** [comment]
No followup.
