### ISSUE TITLE
Macro JSON parsing generating invalid code (missing quotes / prefix)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5424]
When generating a structure from a macro (specifically returning a structure with a key that's not allowed unless quoted) by parsing JSON, it returns invalid code (missing a prefix).

Aka, this returns invalid code:

```
  static macro function foo_from_json()
  {
    var str = "{\"$something\":123}";
    var obj = haxe.Json.parse(str);

    return macro $v{ obj };
  }
```

While this works:

```
  static macro function foo_from_macro()
  {
    return macro { "$something":123 };
  }
```

Tracing the difference, you can see that there's a magic prefix that the JSON version isn't adding:

```
Main.hx:33: { expr => EObjectDecl([{ expr => { expr => EConst(CInt(123)), pos => #pos(Main.hx:33: characters 19-26) }, field => $something }]), pos => #pos(Main.hx:33: characters 19-26) }
Main.hx:34: { expr => EObjectDecl([{ expr => { expr => EConst(CInt(123)), pos => #pos(Main.hx:34: characters 32-35) }, field => @$__hx__$something }]), pos => #pos(Main.hx:34: characters 17-37) }
```

Note the field name, **`@$__hx__$something`**

Example: http://try-haxe.mrcdk.com/#e934B

The JSON parser has done the right thing -- presumably the `$v{ }` is missing the prefixing?

**Comment by Simn** [comment]
It might not be possible to fix this unless we completely revise the way we're dealing with quoted object fields.

**Comment by jcward** [comment]
@Simn - ah, well I don't think it's very critical -- I believe as a workaround you can return a String and parse the JSON at runtime. But it's just one of those weird corner cases.

**Comment by back2dos** [comment]
You can patch it up by hand: http://try-haxe.mrcdk.com/#125Cd ;)
