### ISSUE TITLE
why flashdevelop auto close when open openfl project which use [thx,core] library?

### ISSUE THREAD

**Issue by Liu-GuangYong** [HaxeFoundation/haxe#5428]
Hi, today i reinstall the operating system and i found some old project is not work.
now my computer system : Win7 64bit

flashdevelop version :5.1.1.1
java version "1.6.0-rc"
haxe version : 3.3.0
haxe libs version :
actuate: [1.8.6]
format: [3.2.1]
lime: [2.9.1]
nme: [5.6.4]
openfl: [3.6.1]
thx.core: [0.40.1]

when i create new openfl project complier by lime ,generate swf ,everything is ok.
but when i add haxelib "thx.core" in the project.xml,the flashdevelop is auto close :
i found the Exceptions.log :
2016/7/3 星期日 下午 9:16:36
Unhandled exception:
System.Exception: System.IndexOutOfRangeException: 索引超出了数组界限。
在 ASCompletion.Model.ASFileParser.ParseSrc(FileModel fileModel, String ba, Boolean allowBaReExtract)
在 ASCompletion.Model.ASFileParser.ParseFile(FileModel fileModel)
在 HaXeContext.Context.GetFileModel(String fileName)
在 ASCompletion.Model.PathExplorer.GetFileModel(String filename)
在 ASCompletion.Model.PathExplorer.ParseFoundFiles()
在 ASCompletion.Model.PathExplorer.BackgroundRun()
在 ASCompletion.Model.PathExplorer.ExploreInBackground()
在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
在 System.Threading.ThreadHelper.ThreadStart()

i think this problem is will inevitabely appear, anyone can help me?

**Comment by Simn** [comment]
This is not a Haxe issue, try asking on the FlashDevelop forums.
