### ISSUE TITLE
Allow to selectively specify rules for transitive implicit conversion

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5433]
I am very often in a situation where I have conversion rules like this:

``` haxe
I @:from A
I @:from B
I @:from C

J @:from D
J @:from E
J @:from F

X @:from I
X @:from J
```

And what I really want is `X` from any of `A` to `F`, which is why I end up spelling out quite a lot of stuff. Years ago reasons were outlaid why supporting transitivity is impractical (IIRC mostly because the space of possible conversions grows exponentially).

But what if this were an opt-in? 

What I would like to be able to do is `X @:transitive @:from I` and `X @:transitive @:from J` and the compiler then treats it accordingly. To further prevent complexity from exploding, there could be a limit defaulting to a sensible number (2? 3?), that users could override with `@:transitive(limit)`.

Also please note that I excluded `@:to` on purpose. My thinking here is that if the graph is unidirectional, it will stay smaller, because it won't create massive "hubs" in types like `String` or `Int`.

**Comment by ibilon** [comment]
Isn't there an issue in case of multiple transformation routes?

**Comment by back2dos** [comment]
The compiler has a well-defined order for looking for casts and uses the first compatible one, which is a very predictable way of resolving ambiguity. It's probably a good idea to put transitive casts last in that order.

**Comment by Simn** [comment]
I'm not very keen on extending variance options, it's already bad enough as it is. But I'll think about it "later".

**Comment by Simn** [comment]
This would have to go through haxe-evolution.
