### ISSUE TITLE
[js] inlined StringMap functions lead to quite a lot of duplicated code

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#5436]
Looking at some generated JS, I was wondering if inlining the StringMap functions (as of 6b9e45f) on JS is really such a good idea. Especiially with `set` it leads to duplicate declarations for all map keys like this:

```
if(__map_reserved.ended != null) {
    _g.setReserved("ended",function() {
        if(!_gthis.endReached) {
            _gthis.endReached = true;
            _gthis.onEnded.emit(true);
        }
    });
} else {
    _g.h["ended"] = function() {
        if(!_gthis.endReached) {
            _gthis.endReached = true;
            _gthis.onEnded.emit(true);
        }
    };
}
```

and thus to a pretty bloated JS file. Removing `inline` from `set` saved me like 4kB on a 40kB JS file. No big deal, but anyway...

**Comment by nadako** [comment]
It seemed to be a good idea when it was doing `"$"+key`, now I'm not sure... I'd be interested in looking at some benchmarks, but I think it'll be all for removing the `inline`.

**Comment by nadako** [comment]
Hmm, the inlined `set` is working much faster in general case, but much slower in case of this duplicated anonymous functions. However if I introduce a temp var there by adding stupid `var value = value;` in the inlined set function, it works faster than non-inlined.

@Simn the function is not tempvared automatically because function declaration has no side effects, so it's propagated, right? maybe it's a good idea not to propagate anon functions.

**Comment by Simn** [comment]
It should only be propagated if it's used exactly once, so that shouldn't make a difference.

**Comment by nadako** [comment]
Well, it's propagated twice here. I assume because it's considered const or something.

**Comment by Simn** [comment]
I don't really understand why we talk about propagation at all. What is propagated to where? I thought the issue here is that `set` and friends are declared to be inlined.

**Comment by nadako** [comment]
The `set` function is faster when it's inlined (I benchmarked), but if you pass a closure to it like in the original example, it gets duplicated that not only leads to generated code size increase, but also this particular case is slower than non-inline version. But if we tempvar it, it's still faster.

**Comment by Simn** [comment]
Ah, so this isn't about StringMap at all.

```haxe
class Main {
	static function main() {
		test(function() { });
	}

	static inline function test(f:Void -> Void) {
		trace(f);
		trace(f);
	}
}
```

Generated:

```js
Main.main = function() {
	console.log(function() {
	});
	console.log(function() {
	});
};
```

**Comment by Simn** [comment]
And yes that's a serious regression.

**Comment by Simn** [comment]
Actually it's not a regression: http://try.haxe.org/#54db1

Hmm, it still strikes me as pretty terrible, but if we fix it in the inliner we have to make up for it in the analyzer to not lose any self-calling-closure optimizations. That gets too messy for 3.3 though.

**Comment by mockey** [comment]
@nadako 
> The set function is faster when it's inlined (I benchmarked)

How did you benchmark it? And is the speed improvement really worth the JS output increase? I agree that my case is kind of special (a large map of events mapped to rather extensive closures), but consider adding some large strings or array declarations instead.

**Comment by Simn** [comment]
@ncannasse: What's your opinion on this? I remember talking to you about TFunction duplication which would lead to multiple closure instances being allocated. I think that was in the context of static inline variables, but we have a similar situation if a TFunction is passed as argument to an inline function directly.

**Comment by ncannasse** [comment]
Regarding the general issue, our policy in JS is to keep the code output clean, so inlining of such methods should be disabled.

Regarding the duplication of TFunction in inline, we should maybe only substitute it if there is only one reference for it (not counting the places where it's directly called)

**Comment by mockey** [comment]
@Simn: Did you consider removing inline for `set` here?

**Comment by elsassph** [comment]
@nadako @Simn could we avoid the `__map_reserved` test for literal strings? It makes some sense for unknown values but I think the compiler could know the unsafe tokens and optimise the output.

**Comment by nadako** [comment]
Not sure we really want to add a special case in the compiler for that. I'd rather have a `-D` flag that disables `__map_reserved` altogether, because in reality it's rarely useful. However if we talk define flags, I think using ES6 Maps when `-D js-es=6` would be even better.
