### ISSUE TITLE
Feature request: interactive -cmd

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/haxe#5437]
Currently it isn't interactive. Try this:

```haxe
class Main {
    static public function main() {
        new debugger.Local(true);
        trace("---");
    }
}
```

build.hxml:
```hxml
-main Main
-D HXCPP_DEBUGGER
-lib hxcpp-debugger
-debug
-cpp ./bin/
-cmd ./bin/Main-debug
```

__Run `haxe build.hxml` and try type `help` when debugger is inited.__

(this is example code from [hxcpp-debugger wiki](https://github.com/HaxeFoundation/hxcpp-debugger/wiki/Getting-started).)

**Comment by Simn** [comment]
We currently have no resources for feature requests like this. I'm not opposed to the idea in general but it would have to come as a pull request.
