### ISSUE TITLE
Error when saying String implements a locally defined interface

### ISSUE THREAD

**Issue by rvion** [HaxeFoundation/haxe#5438]
I have an error when trying to say string implement a locally defined interface.
I don't understand why it's not possible. Indeed, the interface is defined locally, so this is not an orphan instance. The implementation could be statically checked to be unique. 
I was expecting to be able to define interface implementation both near the interface definition or the class definiition.

code: 

```haxe
interface Cool {}

class String implements Cool {}
class Int implements Cool {}

class Test<A:Cool> {
  static function main() {
    new Test<String>("foo");    
    new Test(12); // use type inference
  }

  function new(a:A) {
        trace('Haxe is great!');
  }
}
```

error:

```error
Type name String is redefined from module String
```

(I was trying to restrict the list of possible types of Test)

------------

Do you know how I can solve my problem ?

**Comment by Simn** [comment]
No idea what you're trying to do, but as the error message suggests you cannot redefine a type like that. Try making your String class private if you think it's a good idea.

**Comment by rvion** [comment]
@Simn I'm just trying to say String implement my interface Cool.
I don't want to redefine String, but just say that it implements the locally define interface.
Documentation isn't clear if it is possible or not.

**Comment by kevinresol** [comment]
@rvion You are trying to redefine String with your code, which is not possible, unless you make your String class private.

If you want to make let the compiler knows that String conform to some "interface", you can use structural subtyping.

```haxe
class Test {
    static function main() {
        var i:CanIndexOf = "my string";
        var index = i.indexOf("str");
        trace(index);
    }
}
typedef CanIndexOf = {
    function indexOf(s:String, ?startIndex:Int):Int;
}

```
