### ISSUE TITLE
Sys.programPath() in __init__

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#5442]
```haxe
class Test {
    static function __init__ () {
        trace(Sys.programPath());
    }

    public static function main () {
    }
}
```

traces `null` on neko and fails with `Error : Null Function Pointer` on hxcpp.

**Comment by andyli** [comment]
I'm not sure if we can/should fix this. According to the [old doc](http://old.haxe.org/doc/advanced/magic), `__init__` is very limited by design:

> Note that try/catch() exception blocks cannot be used inside __init__ methods and that static variables have not yet been initialized; these functions should only be used to perform very low level initializations.

I would use some form of lazy initialization instead of `__init__` if possible. e.g.
```haxe
class Test {
    static public var foo(get, null):String;
    static function get_foo() return foo != null ? foo : foo = Sys.programPath();
}
```

Or, do the init logic within a variable definition as follows:
```haxe
class Test {
    static var initialized:Bool = {
        trace(Sys.programPath());
        true;
    };
}
```

**Comment by ibilon** [comment]
Use case (https://github.com/openfl/openfl/blob/develop/templates/haxe/ApplicationMain.hx#L208) is to configure neko before we do any kind of ndll loading.

Although I'm not sure if these line are still required, I'll test without them in a vm without haxe (since somehow ndll are also loaded from their haxelib folder, but that's another issue).

**Comment by Simn** [comment]
Yes `__init__` is special and things like this not working is to be expected.
