### ISSUE TITLE
[js] typed array externs are incorrectly generated

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#5445]
The get and set methods on typed arrays are generated incorrectly. `get` doesn't exist and `set` does something else. the below code compiles, but shouldn't, and fails at runtime. 
```haxe
class Test {
    static function main() {        
        var arr = new js.html.Uint8Array(16);
        arr.set(0,0);
        var p0 = arr.get(0);
    }
}
```
see http://try.haxe.org/#ccb56

**Comment by nadako** [comment]
@aduros could you look into it?

**Comment by nadako** [comment]
I looked into the IDL file and the specificiation - it actually defines `get` and `set` functions that are also array indexers unless I misunderstood the IDL itself:
```
    getter octet get(unsigned long index);
    setter void set(unsigned long index, [Clamp] octet value);
```
Which means we're generating it correctly, but runtimes apparently ignore this. Maybe I'm wrong, will research further.

**Comment by nadako** [comment]
oh well, I hacked the webidls and regenerated externs...
