### ISSUE TITLE
structInit and default values?

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#5449]
``` haxe
package;

@:structInit
private class Struct1 {
    var x:Int = 100;
    var y:Int;
    public function test() {
        trace(x, y);
    }
}

class Main {

    static function main() {
        test();
    }

    static function test() {

        //compiles, output: 100, 0
        var s:Struct1 = {}; 
        s.test();           

        //does not compile: 
        //  { y : Int, x : Int } has extra field y
        //  { y : Int, x : Int } has extra field x
        var s:Struct1 = {x:200, y:100}; 
        s.test();           

        //does not compile: 
        //  { y : Int } has extra field y
        var s:Struct1 = {y:100}; 
        s.test();           
    }

}
```

**Comment by Simn** [comment]
I don't think this should compile unless the x field is made `@:optional`. But yes there's a conflict going on here with constructor generation.

**Comment by Simn** [comment]
I'm not quite sure if we should insert the values at call-site or branch in the constructor. The former would give better performance, the latter might be more robust in some weird cases. Then again `@:structInit` probably doesn't work properly in weird cases anyway.

**Comment by Simn** [comment]
Not 3.3 priority for me because it requires some thought and is a new feature.

**Comment by ncannasse** [comment]
Is it not required to add a constructor to Struct1 ? If the constructor is automatically generated, we might insert `if( x != null ) this.x = x;`

**Comment by RblSb** [comment]
It seems that it works as it should:
http://try-haxe.mrcdk.com/#44D31
Removing @:optional produces a compilation error.

**Comment by ousado** [comment]
It's very questionable whether it behaves like it should - the intent of `var s:Struct1 = {y:100};` couldn't be more obvious, there's a default value, there's a type annotation, so why force people to spell out the default value again, if that's the common case? This behavior clearly violates the principle of least surprise and limits the usefulness of @:structInit a lot.

**Comment by RblSb** [comment]
@ousado Do you mean that `var x:Int = 100;` without `@:optional` should work? I like this idea too.

**Comment by ousado** [comment]
@RblSb Yes, I think so. Not allowing it would be an artificial limitation for no reason I can think of. And it's perfectly safe, unlike `@:optional` which enforces nullability, which is inherently unsafe.

**Comment by RealyUniqueName** [comment]
Fields with default values are now optional even if not annotated with `@:optional`.
