### ISSUE TITLE
Macro for PreCompile tostring

### ISSUE THREAD

**Issue by willstdueswissen** [HaxeFoundation/haxe#5450]
Hey ho,
today i found no solution to precompile code with macro like:
[paste](http://paste42.de/01a6ce84bd5152aa12af2b5ca19332cf/10824/)

is there any chance to get it work?
Thanks for the answere!

**Comment by Simn** [comment]
This is not an Haxe issue, try asking in the haxelang google group or on the #haxe IRC (see http://haxe.org/foundation/contact.html).
