### ISSUE TITLE
Use haxe on mips cpu.

### ISSUE THREAD

**Issue by xwafish** [HaxeFoundation/haxe#5451]
Hi, I write some code like this:

-----------------------------------
var a1:Int = -1;
var b1:Int = -268435456;  // 0xf0000000
var result1:Int= a1+b1;

----------------------------------

then I compile it:

--------------------------------------
-main Test
-swf bin/Test.swf
-swf-version 10

--------------------------------------
then I open Test.swf in the browser, I found that, on a x86 cpu, it works ok, result is -268435457.
but on a mips cpu (Loongson3A), the result is 268435455.(tip: 268435455 + 268435457 = 0x20000000).

If I compile the code with -as3 srcdir. the as3 code will be:

----------------------------
var a1 : int = -1;
var b1 : int = -268435456;
var result1 : int = a1 + b1;

------------------------------
then I compile as3 code to swf use flex builder (I only copy this three lines code), and open swf file in browser, both x86 and mips work fine, so I do not think it is the flash vm 's problem. But only flash target have this problem.

I also have try Int64, it is also have the wrong result on mips cpu.
So what is the issue. If somebody like, I can send you all the test code.
Thank you.

**Comment by xwafish** [comment]
And -30000 0000 + ( -5000 0000) works right on mips cpu, result is -350000000.
But  -20000 0000 + (-15000 0000) get a wrong value on mips cpu. （result is -350000000 +0x20000000）

**Comment by xwafish** [comment]
I have try haxe-3.2/window7/x86  and haxe-2.1/window7/x86 and haxe-3.2/linux/x86 and haxe-3.2/linux/loongson3a
all have the same result.

**Comment by xwafish** [comment]
Ok, I found something, haxe compiler will generate as3_add_i, but flex compiler will generate as3_add.
If I just change the AS3OIAdd from 0xC5 to 0xA0, in file libs/swflib/as3code.ml,
so haxe replace all IAdd to Add, It works ok on both x86 and mips.

It looks like it is my flash vm's problem? 
I do not know how to get the flash vm's soure code , and I do not think adobe will help. :(

**Comment by ncannasse** [comment]
as3_add_i is the correct opcode to add two integers. Please report the bug to Adobe so they fix their JIT/AOT in order to support it correctly.
