### ISSUE TITLE
[swf] StringMap.iterator() wierd behavior: next() does not move internal pointer

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#5452]
If i store `StringMap.iterator()` to a variable and call `next()` on that var several times, it always returns the first item.
This bug is reproducible on swf target only.

I think following example sums it up:
```haxe
class Test {
    static function main() {
        trace("Haxe is great!");
        var m = ["1" => 1, "2" => 2, "3" => 3, "4" => 4, "5" => 5];        
        var iterator = m.iterator();        
        
        //next() does not move internal pointer
        trace(iterator.next());     //1
        trace(iterator.next());     //1
        
        //looks like hasNext() moves internal pointer
        iterator.hasNext();
        trace(iterator.next());		//2
        trace(iterator.next());		//2
        
        //nope. More like sequential calls to hasNext() and next() together move pointer.
        iterator.hasNext();
        iterator.hasNext();
        trace(iterator.next());     //3
        trace(iterator.next());     //3
    }
}
```
http://try.haxe.org/#Ae33E

Tested with Haxe 3.2.1 and 3.3

**Comment by Simn** [comment]
@ncannasse has recently decreed that `hasNext` is to be called before `next` for consistent behavior.

**Comment by RealyUniqueName** [comment]
Where can i find that statement and argumentation?

http://api.haxe.org/Iterator.html#next
> Returns the current item of the Iterator and advances to the next one.
But it does not advance on swf target. Unlike other targets.

**Comment by Simn** [comment]
It was in some similar issue but I can't find it right now.

**Comment by nadako** [comment]
This is such a mess. We should consider .NET-like iterators, like this:
```haxe
interface Enumerator<T> {
    /**
        Value at current position, unspecified before the first `moveNext` call and when
        `moveNext` returns `false`.
    **/
    var current(default,null):T;

    /**
        Move the iterator to the next position, return whether there's a value there.
        Returning `false` means that iteration is stopeed and accessing `current` is
        unspecified.
    **/
    function moveNext():Bool;
}
```

**Comment by ncannasse** [comment]
calling next() without checking hasNext() is considered undefined behavior.
So the correct way to use iterators is to do `while( it.hasNext() ) it.next()`
