### ISSUE TITLE
ReferenceError: js__$Boot_HaxeError is not defined 

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/haxe#5453]
Hi.

I got this error on my last unit tests with Travis with JS target:
ReferenceError: js__$Boot_HaxeError is not defined 

Installing Haxe
0.00s$ mkdir -p ~/haxe
0.32s$ curl -s -L --retry 3 'http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/haxe_latest.tar.gz' | tar -C ~/haxe -x -z --strip-components=1 -f -
0.00s$ export PATH="${PATH}:${HOME}/haxe"
0.00s$ export HAXE_STD_PATH="${HOME}/haxe/std"
0.00s$ mkdir -p ~/haxe/lib
0.03s$ haxelib setup ~/haxe/lib
haxelib repository is now /home/travis/haxe/lib
$ echo $(haxe -version)
3.3.0 (git build development @ d08c194)

**Comment by FrancisBourre** [comment]
![jsbooterrorpng](https://cloud.githubusercontent.com/assets/14309646/16804740/8b06a8fa-490d-11e6-929e-d9d44680e013.png)

**Comment by nadako** [comment]
Uh oh. I've pushed something that "should" fix that, could you try with latest Haxe?

**Comment by FrancisBourre** [comment]
Yeah, that's perfect, thank you so much!

**Comment by nadako** [comment]
Nice, and sorry that I broke it in the first place :)
