### ISSUE TITLE
Analyzer inlines a variable without considering side-effects

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#5455]
For
```
class Main {
	static function protect<T>(v:T):T return v;
	static function main()
	{
		var s = protect('"foo"');
		var p = protect(0);
		var c = s.charAt(p++);
		var n = s.substring(p, s.indexOf(c, p));
		trace(n);
		if (n != "foo") Sys.exit(1);
	}
}
```
the analyzer inlines `c` and generates the equivalent to
```
var n = s.substring(p, s.indexOf(s.charAt(p++), p));
```
which doesn't result in the correct value for `n`.

BTW, this issue appears in Tora's FCGI multipart parsing.

**Comment by Simn** [comment]
I suppose this answers the question asked here: https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/analyzerTexpr.ml#L453
