### ISSUE TITLE
Error caused by retrieving fields of superclass in macro

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFoundation/haxe#5456]
The files detailed below will produce the following error:
`source/Test.hx:14: characters 20-26 : Class<test.C> has no field func`

It seems that simply trying to get the fields of a superclass (`classType.superClass.t.get().fields.get();`) will cause the imported class to be missing the field.

There is no issue if you get the fields of the current class, it is only an issue in the super class. There is no issue if C is in the same package as Test. It is only an issue if it is in a different package.

In TestBuilder.hx:

```
package;

import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type;

class TestBuilder {
    public static function build():Array<Field> {
        var fields:Array<Field> = Context.getBuildFields();
        var classType:ClassType;
        switch (Context.getLocalType()) {
            case TInst(r, _):
                classType = r.get();
            case _:
        }
        classType.superClass.t.get().fields.get();

        return fields;
    }
}
```

In Test.hx

```
package;

import test.C;

@:build(TestBuilder.build())
class Test extends B {
    public function new() {
        super();
    }

}

class B {
    public var c:Int = C.func();
    public function new() {}
}
```

In test/C.hx:

```
package test;
class C {
    public static function func():Int {return 0;}
}
```

**Comment by nadako** [comment]
This is related to type building order, but I don't really understand how it works. Maybe this can't be easily fixed.

**Comment by ncannasse** [comment]
That is reproducible with 3.3 but will be quite hard to fix.
