### ISSUE TITLE
[C++] Haxe outputs code that uses Reflection when you access private fields of abstract data with untyped

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5457]
I didn't see this behavior on Haxe 3.2. This code compiles, but runs slower than Haxe 3.2 at least on hxcpp.
I could avoid this issue by casting abstract to AbstractData.  (`(a:AbstractData).b`);

```hx
class AbstractData {
    private var f:Int;
    
    public function new() {
        f = 1;
    }
}

abstract Abstract(AbstractData) from AbstractData to AbstractData {
	public function new(data:AbstractData) {
		this = data;
	}
}

class Main {
    static function main() {
        var a:Abstract = new AbstractData();
        trace(untyped a.f);
    }
}
```

```cpp
void Main_obj::main(){
            	HX_STACK_FRAME("Main","main",0xed0e206e,"Main.main","Main.hx",16,0x087e5c05)
HXLINE(  17)		HX_VARI(  ::AbstractData,a) =  ::AbstractData_obj::__new();
HXLINE(  18)		::haxe::Log_obj::trace( ::Dynamic(a->__Field(HX_("f",66,00,00,00),hx::paccDynamic)),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),18,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            	}
```

**Comment by Simn** [comment]
Yeah that can happen if you use untyped. If you subvert the compiler's typing you shouldn't be surprised that the compiler doesn't know how to type stuff properly.

**Comment by vroad** [comment]
Strangely, untyped just works fine with private fields. It only has problems with abstracts for some reason. Maybe compiler is no longer thinking that they are the same type. I think it's okay if this change is intended.
