### ISSUE TITLE
Code generated for properties in Flash and reflection

### ISSUE THREAD

**Issue by Neverbirth** [HaxeFoundation/haxe#5460]
This one seems a quite serious issue to me, because it can make a lot of business logic and dynamic code to not work correctly. It was found while working on [this](https://github.com/DoclerLabs/hexUnit/commit/a05ab18b70b12d6247b18e458a064606d175675e).

Having this simple code:

```
private class WhatTheFuck
{
    private var yeah:Bool = false;
    @:isVar public var fuck(get, set):Bool;
    function get_fuck():Bool
    {
        return yeah;
    }

    function set_fuck(value:Bool):Bool
    {
        if (value)
        {
            throw "lol at you";
        }
        return yeah;
    }

    public function new(){}
}
```

And then using `Reflect.setProperty(new WhatTheFuck(), "fuck", true);` won't work as expected. The thing is that this code is compiled to this:

```
package _Test
{
   import flash.Boot;
   import haxe.Log;

   public class WhatTheFuck
   {

      public var yeah:Boolean;

      public var fuck:Boolean;

      public function WhatTheFuck()
      {
         if(Boot.skip_constructor)
         {
            return;
         }
         yeah = false;
      }

      public function set_fuck(value:Boolean) : Boolean
      {
         if(value)
         {
            Boot.lastError = new Error();
            throw "lol at you";
         }
         return yeah;
      }

      public function get_fuck() : Boolean
      {
         Log.trace("you n00b",{
            "fileName":"Test.hx",
            "lineNumber":19,
            "className":"_Test.WhatTheFuck",
            "methodName":"get_fuck"
         });
         return yeah;
      }
   }
}
```

And then Reflect.setProperty is like this:

```
      public static function setProperty(o:*, field:String, value:*) : void
      {
         try
         {
            o["set_" + field](value);
         }
         catch(_loc5_:*)
         {
            o[field] = value;
         }
      }
```

It is eating any possible error you throw on purpose! it's really bad for some cases where you may want to throw different errors for some invalid arguments, null arguments, invalid states, etc, and then it's setting some public var that Haxe generated and matches the original property name and that it wouldn't be used anywhere else.

JS implementation is better, and a similar code could be used in AS:

```
if(a.__properties__ && (tmp = a.__properties__["set_" + "fuck"])) a[tmp](true); else a.fuck = true;
```

Still, that public var with the property name seems a bit strange in this cases, is it meant to swallow some errors with dynamics and the like or to avoid other code taking over the name? at any rate, it wouldn't be meant to be used at all.

**Comment by nadako** [comment]
> Still, that public var with the property name seems a bit strange in this cases

which one?

**Comment by Neverbirth** [comment]
```
package _Test
{
   import flash.Boot;
   import haxe.Log;

   public class WhatTheFuck
   {

      public var yeah:Boolean;

      public var fuck:Boolean;

      public function WhatTheFuck()
      {
         if(Boot.skip_constructor)
         {
            return;
         }
         yeah = false;
      }

      public function set_fuck(value:Boolean) : Boolean
      {
         if(value)
         {
            Boot.lastError = new Error();
            throw "lol at you";
         }
         return yeah;
      }

      public function get_fuck() : Boolean
      {
         Log.trace("you n00b",{
            "fileName":"Test.hx",
            "lineNumber":19,
            "className":"_Test.WhatTheFuck",
            "methodName":"get_fuck"
         });
         return yeah;
      }
   }
}
```

That `public var fuck:Boolean;`. Ok, in Haxe we have `@:isVar public var fuck(get, set):Bool;` but it's not the same...

**Comment by nadako** [comment]
i don't really get it, it's an explicit `@:isVar` so the field is generated :)

**Comment by Neverbirth** [comment]
/me runs away whistling like nothing happened...

My bad, I didn't notice at all! Anyway, the main problem with consuming the original error is still true and really bad.

**Comment by nadako** [comment]
Yeah, that's an issue
