### ISSUE TITLE
[neko] Socket.select fails with 'Invalid Call' on latest release.

### ISSUE THREAD

**Issue by 5Mixer** [HaxeFoundation/haxe#5461]
With version 2.1.0 of Neko and Haxe 3.2, `socket.select` fails on the neko platform. This was brought up in a comment by @kevinresol some months ago with the same problem on [this commit](https://github.com/HaxeFoundation/haxe/commit/52aeb180fd233f400d997e1d57bfb13c6e878ada), which introduced the bug. I have made a simple example of the bug [at this repo](https://github.com/5Mixer/HaxeSocketIssue).

Running the platform on Neko gives:
    
    Called from ? line 1
    Called from Main.hx line 28
    Called from Main.hx line 7
    Called from Main.hx line 17
    Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/net/Socket.hx line 241
    Called from C:\HaxeToolkit\haxe\std/neko/_std/sys/net/Socket.hx line 235
    Uncaught exception - Invalid call
    Error: Command failed with error 1

Running on the C++ platform works as expected. This bug was originally raised at https://github.com/5Mixer/mphx/issues/34, but this appears to be a Haxe related bug.

Thanks very much for any assistance, much appreciated :smile:.

**Comment by Simn** [comment]
@nadako: Has this been fixed by https://github.com/HaxeFoundation/haxe/commit/2e80842218b7e1cc0c761e38844406d1702ba90f?

**Comment by nadako** [comment]
Yes, sorry, I missed this one.
