### ISSUE TITLE
Extern for interfaces generating weird code

### ISSUE THREAD

**Issue by tienery** [HaxeFoundation/haxe#5463]
I have the following code in my repo (I'm not sure if it's a specific case scenario or if it is a problem in all things regarding `interfaces`):

``` haxe
package sfml.graphics;

import sfml.system.Vector2.Vector2i;
import sfml.system.Vector2.Vector2f;
import sfml.graphics.Rect.IntRect;
import sfml.graphics.RenderStates.RenderStatesConst;

interface RenderTarget {

    public function clear(color:Color):Void;
```

Which generates weird code in Haxe 3.3 (to C++) by adding `::` before keywords such as `const`, causing compiler errors. I reverted back to 3.2.1 to see if it was a Haxe-specific or hxcpp-related error, but it compiles successfully suggesting it is specifically a Haxe-level problem.

Now, I could always present the generated code if you so desire but currently I am sticking with 3.2.1 at least until these issues are resolved.

**Comment by nadako** [comment]
Could you point to those sfml packages or better provide a minimal reproducible example?

**Comment by tienery** [comment]
https://github.com/tienery/hxsfml Clone and set as dev, `haxelib dev hxsfml ./`. Try building the `tests\01 Blank Window\build.bat` in Windows.

I am using the latest git of `hxcpp` and (was) Haxe 3.3.

I'm not sure if the same error is brought up with a minimal example because I never tried it. Although, from past experience with OpenFL with Haxe 3.3, I wouldn't have that so. It might just be a very specific problem with my particular extern implementation. I wouldn't be 100% sure what causes the code to generate the way it does.

**Comment by nadako** [comment]
Can reproduce! Will try reducing

**Comment by nadako** [comment]
Well the problem is with `@:native`:

```haxe
@:native("const sf::Color&")
extern class Color {
```
so it generates `::const sf::Color& _hx_tmp4`.

I'm not sure it's correct to use `const` like that here, but I'll leave it to @hughsando to clarify.

**Comment by tienery** [comment]
The `const` usage is to stay consistent with the core API of SFML, because SFML is very stack-oriented, which is the opposite to SDL, which is more heap-oriented.

**Comment by Simn** [comment]
This is a bad usage of `@:native`, we really cannot account for all the possible strings you might put in there, especially on C++.

**Comment by tienery** [comment]
No offence, but I don't think you are fully aware of the implications. Please take the [following link](http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1RenderTarget.php#a6bb6f0ba348f2b1e2f46114aeaf60f26) as reference for the issue at hand.

I need a way to reference that exact parameter type signature in order for Haxe to generate the correct code. It was working perfectly fine in 3.2.1, but in 3.3 I get compiler errors.

If there is an alternative method to create a signature like that in an interface without running into multi-inheritance issues in those classes implementing it, then by all means, please provide me a solution. But I would ideally like to not have to resort to telling people to sticking with version 3.2.1 because 3.3 doesn't work.

If you don't want to resolve it, fair enough. I guess anyone using SFML will have to make do with 3.2.1, if at all.

**Comment by ibilon** [comment]
Bad choice of link, `sf::RenderTarget::clear` can take a non const `Color`, which some aren't http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1Color.php#af39790b2e677c9ab418787f5ff4583ef
Adding `const` to the native expression is a bad idea.

Though true hxcpp doesn't have anything to express that an object is const, or a class function.

**Comment by nadako** [comment]
let's be constructive here:

1. adding "const" into `@:native` is a hack, since const isn't a property of a type. so having a hack broken is to be expected.
2. we indeed need a proper way to express that, so this issue shouldn't be closed until @hughsando provides some solution :-)

**Comment by tienery** [comment]
> adding "const" into @:native is a hack, since const isn't a property of a type. so having a hack broken is to be expected.

Well, I didn't know that. I just assumed that because the function signature required that type, that I should make a type to match it.

**Comment by nadako** [comment]
Yeah, constness is a property of a local/argument/field, not the type itself. Is there really no way to use SFML with 3.3 right now?

**Comment by tienery** [comment]
I've never tried without `const`, but I can always give it a go.

**Comment by hughsando** [comment]
Not 100% sure this is what you are trying to achieve, but you can often
just tell hxcpp that the function (say, renderTrarget::clear) takes just a
"color", not a "const color &".  This is enough for haxe to type-check the
expression, and enough for the c++ compiler to match.
The typical usage would be to have a function that returns a "Color"
externed as a "cpp::Struct<Color>", or perhaps a local variable of this
type.
By externing the function without the "const &", haxe will correctly think
it can just pass the colors instances to function and things should work as
expected.
I guess I am saying you  can lie about the extern type to trick haxe into
working in a straight forward way.
Also, for the native default parameters, using "@:overload" to define two
version of the function, with different arg counts,  is currently the best
way of respecting the values defined in the c++ header file.

**Comment by frabbit** [comment]
@hughsando is this issue relevant for 3.3 release?

**Comment by hughsando** [comment]
This should not hold the release up.

**Comment by tienery** [comment]
I'm no longer testing this issue on SFML. I've moved on to other things. If anyone has the same issue with other interfaces, then by all means reopen.
