### ISSUE TITLE
typing weirdness

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5464]
extracted from #5420. not a regression but still silly

```haxe
class Main {
    static function main() {
        var a:Array<Int> = [];

        function f(v) { return ""; }

        // funny: uncommenting this (not actually using) fixes it
        // function f2(v) return "";

        (a.map(f)); // parenthesis are important too
    }
}
```

**Comment by nadako** [comment]
Forgot to add the actual compilation error:
```
src/Main.hx:10: characters 9-17 : Array<String> should be Int
src/Main.hx:10: characters 9-17 : For function argument 'v'
```

**Comment by Simn** [comment]
Is that parsed as a call? If so, that's not necessarily unexpected...

**Comment by nadako** [comment]
Ooh haha, i guess it is indeed. I thought it should only be parsed as the call if we wrap function definition in parentheses tho (e.g. `(function(v) return "")()`).

**Comment by Simn** [comment]
It's a side-effect of optional semicolons, but I think it's fine the way it is. Any change has the potential to break code.

**Comment by nadako** [comment]
alright

**Comment by ncannasse** [comment]
We could avoid that by not use parse_next after EFunction

**Comment by Simn** [comment]
We could, but that might break some parsing. Who knows what crazy things people do in their macros, e.g. with binops after a function...
