### ISSUE TITLE
[flash] weird @:protected behaviour

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5473]
``` haxe
class C {
    public function new() {}

    var publicV:Int;
    public function setPublicV(v) publicV = v;
    public function getPublicV() return publicV;

    @:protected var protectedV:Int;
    public function setProtectedV(v) protectedV = v;
    public function getProtectedV() return protectedV;
}

class Main {
    static function main() {
        var c1 = new C();
        c1.setPublicV(1);
        c1.setProtectedV(1);

        var c2 = new C();
        c2.setPublicV(2);
        c2.setProtectedV(2);

        trace('c1.public', c1.getPublicV());
        trace('c1.protected', c1.getProtectedV());

        trace('c2.public', c2.getPublicV());
        trace('c2.protected', c2.getProtectedV());
    }
}
```

This outputs: `1, 2, 2, 2` while it obviously should output `1, 1, 2, 2`.

See http://try.haxe.org/#1331a (it's the same on latest development).

I didn't look at the bytecode, but if I decompile with Sothink SWF decompiler, the only difference between these fields is that `protectedV` is protected, not public, so this maybe a flash player issue (but that doesn't sound likely).

**Comment by Simn** [comment]
Ehm... what?

**Comment by nadako** [comment]
My reaction exactly.

**Comment by nadako** [comment]
It's either the FP bug which sounds pretty stupid and unlikely, or very specific bytecode issue which isn't even surfacing when decompiling to AS3.

**Comment by nadako** [comment]
On a side note, the [documentation](https://haxe.org/manual/cr-metadata.html) for `@:protected` suggests that it's available on all targets, which is a lie :)

**Comment by ncannasse** [comment]
I haven't read this issue, let's forget about it

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
