### ISSUE TITLE
[analyzer] expression fusion doesn't happen within if branches

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5477]
As title says (and as we discussed on Slack),

```haxe
class Main {
    @:pure // inferred
    static function f() return 2;

    static function main() {
        var v = f();
        trace(if (Math.random() > 0.5) 1 else v);
    }
}
```

```js
Main.main = function() {
	var v = Main.f();
	console.log(Math.random() > 0.5?1:v);
};
```

The `v` here could be fused into branch body to gain free performance boost

**Comment by Simn** [comment]
That might not be the best example because it requires knowing that `Math.random()` has no side-effect either. But I do see your point.

In order to support this we have to treat branching expressions (TIf, TSwitch) as having a side-effect, else we might change control flow. This requires some investigation as to the implications of doing so.

**Comment by Simn** [comment]
This made me realize that there's a problem with side-effect detection still: A pure function is not allowed to cross an impure one because it could depend on its state changes.

```haxe
class Main {
	static function main() {
		var a = g(); // should be 1
		var b = f() + a; // should be 2 + 1 = 3
		trace(b); // is 4...
	}

	static var x = 1;

	static function f() {
		return x = 2;
	}

	static function g() {
		return x;
	}
}
```

This is currently generated as `console.log(Main.f() + Main.g())` which is incorrect.

**Comment by nadako** [comment]
Uh oh, this is a regression!

**Comment by Simn** [comment]
I know, this is gonna take a while to fix in a way that you don't get temp var PTSD from it.

**Comment by Simn** [comment]
Working on a new movie for nadako:

![tempvars](https://cloud.githubusercontent.com/assets/634365/17849931/4c1b80c6-685b-11e6-80b1-4bb971dd18f1.png)

**Comment by nadako** [comment]
har har har :)
