### ISSUE TITLE
[cs] support .NET Core

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5480]
Microsoft is reworking the .NET infrastructure and now there's a new version of .NET called ".NET Core". 

Basically it's an overhaul and cleanup of the framework, but it introduces a new core API library that is incompatible in some parts with older one. For example, `Thread` doesn't have `CurrentCulture` field anymore - it was moved somewhere else.

To support .NET Core, Haxe should support `-D netcore` or something and based on that we need:
- use proper APIs in the standard library
- use proper APIs in the compiler-generated stuff (not sure if there's any)
- think about how to integrate compilation (hxcs) and extern loading with the `dotnet` tool and other .NET Core stuff.

**Comment by Neverbirth** [comment]
From what I understood, .NET Standard will be released during the first or second quarter of 2017, and it will bring greater and better parity with the standard .NET framework, so maybe it will be easier to wait for that? I haven't played enough with both (hxcs and Core) to really know if in this case the wait would be worth it,

**Comment by robinrodricks** [comment]
What's the status on this?

**Comment by nanjizal** [comment]
robinrodricks, you can check the std library for cs here and watch for changes:

https://github.com/HaxeFoundation/haxe/tree/development/std/cs
https://github.com/HaxeFoundation/haxe/tree/development/std/cs/_std
https://github.com/HaxeFoundation/haxe/tree/development/std/cs/internal

You will see mostly changes are only related to improvements in Haxe language in stabliity and features, or target edge cases. 
If you look at hxcs changes there have not been many recently.

https://github.com/HaxeFoundation/hxcs/commits/master

but Haxe Mono always works well for me, Jonas (https://twitter.com/cambiatajonas) has some nice graphics music notes stuff with c# target.

**Comment by nadako** [comment]
I don't think anyone worked on .NET core support, but I also think it's mostly a matter of changing some API usages in standard lib.

**Comment by kLabz** [comment]
I have been using .NET core with haxe for a year now (started with 2.1.0, now using 2.1.7). It's actually supported, but you have to define it yourself in a hacky way (some randomly picked version > 35 for `-net-ver` and a custom `--net-std`).

I'll try to make it into something like this for .NET core 2.1.11 (current LTS):
```hxml
-net-target=netcore
-netcore-ver=2.1.11
```

**Comment by kLabz** [comment]
Not quite ready yet; making some progress while writing a new tool to manage net-libs but haxe still cannot compile .NET core apps

**Comment by VictorioBerra** [comment]
Any movement on this?

Ideal DX would look like this:

```
sudo add-apt-repository ppa:haxe/releases -y
sudo apt-get update
sudo apt-get install haxe dotnet6 -y
mkdir ~/haxelib && haxelib setup ~/haxelib
```

Then simply run `haxe build.hxml` and it should work.

**Comment by kLabz** [comment]
None, I'm finally free from dotnet )

**Comment by VictorioBerra** [comment]
Does this mean haxe will no longer support transpiling to C# in the future?

**Comment by kLabz** [comment]
No, though that makes it one less people to bother Simn with this target whenever he feels like we should drop it

**Comment by kLabz** [comment]
I guess that won't get better support than what's already been added.

**Comment by mesheets** [comment]
Are there any particular blockers to this moving forward?  In addition to this issue thread, there has been…
* Pull request #8391 against this repo
* Open Issue HaxeFoundation/hxcs#42 in the “[hxcs](https://github.com/HaxeFoundation/hxcs)” project
* Unanswered [community question related to targeting .NET Standard](https://community.haxe.org/t/3425)

The “hxcs” Haxe support library, which is a [prerequisite for compiling Haxe to C#](https://haxe.org/manual/target-cs-getting-started.html), was [last updated 4 years ago](https://lib.haxe.org/p/hxcs) (version 4.2.0).

Somewhat inherent to this is also supporting the [.NET SDK-style project file format](https://learn.microsoft.com/en-us/nuget/resources/check-project-format) that is now standard.

**Comment by kLabz** [comment]
The main issue is that C# target [has been removed](https://github.com/HaxeFoundation/haxe/pull/11551).

So such a thing would only work on Haxe 4, and would require no (or really minor) changes on the compiler side.

**Comment by mesheets** [comment]
This would seem to imply a past tense, yet presently,
* The current version listed on the [Haxe homepage](https://haxe.org/) is in the version 4 series (4.3.6)
* C# is listed on the [Haxe homepage](https://haxe.org/) as a supported target (both in the text and the [graphic](https://haxe.org/img/targets/all-targets.svg))
* C# is also listed on the [Compiler Targets](https://haxe.org/documentation/introduction/compiler-targets.html) page linked to from the above
* There is still a [C# target section in the documentation](https://haxe.org/manual/target-cs.html)

Does this perhaps mean C# will only work with Haxe "for now", with C# still supported in the (current) latest v4.3.6 release (and any potential future v4.* releases) but will no longer be included in a pending Haxe 5 that has not yet been released?

At the least, though, it would appear to be safe to say to not launch a new project using Haxe if C# is a key target?  ([Reflaxe](https://lib.haxe.org/p/reflaxe/) and [Reflaxe.CSharp](https://github.com/SomeRanDev/reflaxe.CSharp) don't appear to be very active at the moment.)

**Comment by kLabz** [comment]
Yes, C# target is available in currently released Haxe version, but next major Haxe version won't support it anymore.

The website being based off latest Haxe release, it doesn't reflect the removal yet. I agree we should make it clearer there that C# target is being removed, though.

**Comment by mesheets** [comment]
I'm sorry to hear of C# support being dropped but appreciate the insight.
