### ISSUE TITLE
[cs] Reflect.setField(obj, fieldName, null) throws an error on c# with @:nativeGen

### ISSUE THREAD

**Issue by Muxeu** [HaxeFoundation/haxe#5481]
Hi, i use some kind of injection in my project and sometimes i need to clear class fields from data (e.g set them to null). Simple code work well on ActionScript, but throws an exeption on c# if i add `@:nativeGen` to class

```
//this line works well
Reflect.setField(this, "foo", bar);
//this line throws an error on C#
Reflect.setField(this, "foo", null);
```

Than I got  `"NullReferenceException: Object reference not set to an instance of an object"` error because Runtime class can't call getType on null object. Simply adding nullcheck to Runtime.slowSetField sovles problem.

I use Haxe 3.3.0.

**Comment by Simn** [comment]
I don't think reflection is supposed to work on `@:nativeGen` types.

**Comment by Muxeu** [comment]
Why not ? All work fine, only "null" produces an error. I can't create all classes without @:nativeGen because code becomes to heavy. Only perfomance critical parts have this tag.

**Comment by nadako** [comment]
Reflection for `@:nativeGen` classes goes the "slow way" through native .net reflection, so non-nativeGen classes are supposed to actually be faster when it comes to reflection and structural typing.

**Comment by Muxeu** [comment]
Yes, i know this. I used `@:nativeGen` with reflection very carefully. But question is not in use or not `@:nativeGen`, i think that this case is bug. Simple adding `value != null` solves the problem.

**Comment by nadako** [comment]
i'll look into it
