### ISSUE TITLE
Inline constructors and recursion

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5483]
The following:

``` haxe
class Point {

    public var x : Float;
    public var y : Float;

    public inline function new(x,y) {
        this.x = x;
        this.y = y;
    }
}

class Triangle {

    var a : Point;
    var b : Point;
    var c : Point;

    public inline function new(a,b,c) {
        this.a = a;
        this.b = b;
        this.c = c;
    }

    public inline function area() {
        return ((a.y * b.x - a.x * b.y) + (b.y * c.x - b.x * c.y) + (c.y * a.x - c.x * a.y))*0.5;
    }

}

class Test {

    static function main() {
        var t = new Triangle(new Point(0,2), new Point(5,4), new Point(6,-1));
        trace(t.area());
    }
}
```

Is currently optimized as:

``` haxe
var a = new Point(0,2);
var b = new Point(5,4);
var c = new Point(6,-1);
trace((a.y * b.x - a.x * b.y + (b.y * c.x - b.x * c.y) + (c.y * a.x - c.x * a.y));
```

Whereas we should be able to inline the `Point` instances as well. I tried to add a recursion in `inline_constructors` (since the Triangle needs to be first inlined before the Point can be) but I didn't work out.

**Comment by Simn** [comment]
I wonder if it would be feasible to run parts of our optimization stage multiple times. We've had issues with missed optimizations for a while now and I think a more general approach is to repeat running them until convergence. I've had a good experience with this in the analyzer where I use this technique on a smaller scale.

The obvious risk is that compilation time might increase. We would have to measure the impact here on some real world cases.

**Comment by basyg** [comment]
There is a similar case:
```haxe
class Point {
    public var x : Float;
    public var y : Float;

    public inline function new(x,y) {
        this.x = x;
        this.y = y;
    }
}

class Rectangle {
    public var x : Float;
    public var y : Float;
    public var sizeX : Float;
    public var sizeY : Float;

    public inline function new(x,y,sizeX,sizeY) {
        this.x = x;
        this.y = y;
        this.sizeX = sizeX;
        this.sizeY = sizeY;
    }
	
	public inline function getPosition():Point return new Point(x, y);
}

class Main {
    static function main() {
        var r = new Rectangle(10, 10, 40, 20);
        trace(r.getPosition().x);
    }
}
```

main() compiled in this:
```haxe
var r_x = 10;
var r_y = 10;
console.log(new Point(r_x,r_y).x);
```

**Comment by Simn** [comment]
That's not really related. Right now constructor inlining is strictly tied to variable initialization, which is a bit unfortunate for cases like that.

**Comment by ncannasse** [comment]
@Simn yes traditional optimizations are run until it reached a fixed point. Sadly a lot of our passes are implemented as map which means a lot of memory I/O even for 0 changes. We could however have more specialized loops, such as:
  * optimize as now
  * try to inline_constructor again - this should be fast if we don't find any candidate we can abort it
  * if we did inline constructors, loop

**Comment by Simn** [comment]
Could you elaborate what you mean by "implemented as map"?

I guess we'll have to take a good look at filters.ml for 3.4 and sort out our optimization stage.

**Comment by ncannasse** [comment]
"implemented as map" = means that we map the whole expression, even if most of the AST does not change

**Comment by Simn** [comment]
Any thoughts on using hash-consing for texpr?

**Comment by Simn** [comment]
This now generates the following:

```js
Main.main = function() {
	var t_a_x = 0;
	var t_a_y = 2;
	var t_b_x = 5;
	var t_b_y = 4;
	var t_c_x = 6;
	var t_c_y = -1;
	console.log("source/Main.hx:34:",(t_a_y * t_b_x - t_a_x * t_b_y + (t_b_y * t_c_x - t_b_x * t_c_y) + (t_c_y * t_a_x - t_c_x * t_a_y)) * 0.5);
};
```

@basyg's version gives:

```js
Main.main = function() {
	var r_x = 10;
	var r_y = 10;
	var r_sizeX = 40;
	var r_sizeY = 20;
	var inlPoint_x = r_x;
	var inlPoint_y = r_y;
	console.log("source/Main.hx:30:",inlPoint_x);
};
```

This was probably fixed by @basro's inline constructor changes.
