### ISSUE TITLE
NativeArray.reserve() is not implemented for VirtualArray

### ISSUE THREAD

**Issue by basyg** [HaxeFoundation/haxe#5484]
Haxe compiles this, but cpp isn't:
```haxe
package;
using cpp.NativeArray;

class Main {
	static function main() {
		var arr:Array<Dynamic> = [{}];
		arr.reserve(10);
		trace(arr[0]);
	}
}
````

**Comment by hughsando** [comment]
Not sure how I feel about requiring the NativeArray methods to work on VirtualArray.
In this case it was easy enough - at least if there are some values in the array already. If the array is empty, then hxcpp does not actually have anywhere to store this reserve information, so I would need some extra storage space somewhere..
