### ISSUE TITLE
[cs] Obtaining pointer to the middle of C# Array and converting it to float*?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5492]
I'd like to do this without using `untyped __cs__` in my code, but is that possible now?
`cs.Lib.pointerOfArray` only supports obtaining pointer to the beginning of array, and returns the pointer of input type.

``` hx
var bytesData:BytesData = @:privateAccess targetRawData.toByteArray().toBytesData();
cs.Lib.fixed({
    var dst:UInt8Ptr = cs.Lib.pointerOfArray(bytesData); // only works correctly with local variable?

...

    untyped py = untyped __cs__("(float*)&dst[pos + 4]");

....

```

**Comment by Simn** [comment]
On a side note, we have to tell the analyzer about these things (beginning of array or not) so it doesn't do any invalid optimizations when pointers are involved.
