### ISSUE TITLE
Array iterating on flash is slower than manual loop.

### ISSUE THREAD

**Issue by basyg** [HaxeFoundation/haxe#5494]
I think it is a regression.

``` haxe
package;
import haxe.Timer;

class Main {

    static function main() {
        var ints = [for (i in 0...10000000) i];

        Timer.measure(function() {
            var s = 0;
            for (i in ints) {
                s += i;
            }
            trace(s);
        });

        Timer.measure(function() {
            var s = 0;
            for (i in 0...ints.length) {
                s += ints[i];
            }
            trace(s);
        });
    }

}
```

Release on jit (release) player:
0.102s
0.075s

Release on no jit (debug) player:
0.431s
0.090s

Debug on no jit (debug) player:
1.170
0.687

**Comment by nadako** [comment]
I'm getting 0.145 vs 0.114 on FP 22,0,0,209 (on chrome). Judging by the js output, the difference is probably array length being cached when used in an int iterator (`0...ints.length`), but anyway that difference is not that huge as in your tests...

**Comment by basyg** [comment]
>
**nadako**
Judging by the js output, the difference is probably array length being cached when used in an int iterator

You are right. This is has same perfomans:
```haxe
Timer.measure(function() {
    var s = 0;
	var i = 0;
	while (i < ints.length) {
        s += ints[i++];
	}
    trace(s);
});
```

**Comment by ncannasse** [comment]
@Simn is it somehow related to analyzer ? I don't think we have changed much here.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
