### ISSUE TITLE
"Primitive not found" error while compiling

### ISSUE THREAD

**Issue by fulopm** [HaxeFoundation/haxe#5501]
I tried to compile the following source code: https://gist.github.com/anonymous/1b5d4ece61f475df9722930d1bf1ce11 (making a Server socket, the problem is with **`sys.net.Socket.bind()` function**), with command `haxe -main Server.hx --interp`, but the compiling process was aborted.

The exact error message was this:
**`/usr/share/haxe/std/neko/_std/sys/net/Socket.hx:168: characters 2-33 : Primitive not found std@socket_bind:3
Server.hx:4: characters 8-51 : Called from
?:1: characters 1048575-8796094070782 : Called from
Aborted`**

My Haxe version is `3.2.1` and Neko is `2.1.0`. I installed it from the official PPA. I'm using Ubuntu x64.

**Comment by ncannasse** [comment]
The interpreter does not come with services to run a server, you can use it using Neko:

``` 
haxe -neko server.n -main Server
neko server.n
```

**Comment by fulopm** [comment]
Yes, I'm using this way now. Sorry for the unnecessary issue.

Thanks!



2016. aug. 8. dátummal, 13:00 időpontban Nicolas Cannasse <notifications@github.com> írta:
