### ISSUE TITLE
[cs] Issue3383 failing with -D erase-generics without -D fast-cast

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5503]
I'll #if it for now, but something has to be done.

**Comment by nadako** [comment]
See 10eeeb277cb9f5392df780abfd6bf5760362b77c

**Comment by waneck** [comment]
I've battled with this issue a little bit, and it seems to me that there is nothing we can do with it on erase_generics. First of all, we're using `cast null` which is not really specified. I've tried making it so `null` and the default values are declared equal with `erase_generics`, but then issues like #3094 and #4842 fail. In fact, #3094 and this issue seem to be mutually exclusive on erase_generics platforms.
If you're curious on how the fix looked like, see https://github.com/waneck/haxe/commit/5c480ba2298d465c339dd44b0b67b452c78cb7c8
