### ISSUE TITLE
StringTools.urlEncode() corrupting url in Java

### ISSUE THREAD

**Issue by Phineas7** [HaxeFoundation/haxe#5505]
In ver 3.3.0 the Java url encoded string is post processed.
"%21" is converted to "!"
"%27" is converted to "\"
"%28" is converted to "("
"%29" is converted to ")"
"%7E" is converted to "-" <-- This is causing problems.

In the first four cases the hex value is replaced with the character it represents.
However 0x7E is not a '-' it is a '~'.

Was the intention to convert "%7E" to "~"?
Or was it to convert "%2D" to "-"?

The prior version of Haxe we were using did no post processing. What is the purpose of this?

**Comment by Simn** [comment]
@waneck: 0x7E should indeed be `~`, why has it been added to generate `-`?

**Comment by waneck** [comment]
Oh my, I think this was me being blind and seeing `~` as `-`

**Comment by Phineas7** [comment]
What is the purpose of converting URL encoding back to ASCII characters in the first place?

Based on the reply, I assume changing the '~' to a '-' is the correct fix.

**Comment by waneck** [comment]
Because of this: https://github.com/HaxeFoundation/haxe/issues/4564
