### ISSUE TITLE
@:pure vs parenthesis

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5508]
```haxe
class Main {
    static var i:Int;

    static function main() {
        trace(~f(i));
    }

    @:pure
    inline static function f(i:Int):Int {
        return 0x1 << i;
    }
}
```
this generates incorrect code:
```js
Main.main = function() {
	console.log(~1 << Main.i);
};
```
but if we disable `@:pure`, the code becomes correct:
```js
Main.main = function() {
	console.log(~(1 << Main.i));
};
```

Thanks @eliasku for reporting.

PS shouldn't this function be inferred as pure anyway?

**Comment by Simn** [comment]
In my opinion this should be handled in genjs... That's what you'll have to do if you remove TParenthesis anyway.

**Comment by nadako** [comment]
makes sense

**Comment by nadako** [comment]
one more proof that TParenthesis is problematic :-P

**Comment by nadako** [comment]
okay, reworking generator for that is easier said than done and quite dangerous right now. i found out that TMeta's were simply not handled in the "sanitizer" function that adds them parens to unops/binops, so I added missing looping there and it seems to be fixed. could you review since i'm not very familiar with that code?

**Comment by nadako** [comment]
Another one:
```haxe
class Main {
    var f:Int;

    static inline function n(a:Main):Main {
        return if (a == null) cast a else null;
    }

    @:pure
    static inline function nPure(a:Main):Main {
        return if (a == null) cast a else null;
    }

    static var a:Main;
    static function main() {
        trace(n(a).f);
        trace(nPure(a).f);
    }
}
```

generates:
```js
	var a = Main.a;
	console.log((a == null?a:null).f);
	var a1 = Main.a;
	console.log(a1 == null?a1:null.f);
```

**Comment by Simn** [comment]
I've fixed this in the sanitizer now so we shouldn't come across it anymore. Will have to deal with it in the generators if we ever remove this kind of sanitation.
