### ISSUE TITLE
[analyzer] var name is lost with some abstract casts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5510]
while playing with the new Any type, i stumbled upon this:
```haxe
abstract A(Dynamic) {
    @:to inline function to<T>():T return this;
}

abstract B<T>({}) {}

class Main {
    static function main() {
        var niceVarName = (get() : B<Int>);
        f(niceVarName, niceVarName);
    }

    static function get():A return null;

    static function f(v:B<Int>, v:B<Int>) {}
}
```
generates
```js
Main.main = function() {
	var tmp = Main.get();
	Main.f(tmp,tmp);
};
```

If we disable local DCE, we get pretty good idea of what's going on:
```js
Main.main = function() {
	var tmp = Main.get();
	var niceVarName = tmp;
	Main.f(tmp,tmp);
};
```
If we disable copy propagation, it's generated properly:
```js
Main.main = function() {
	var niceVarName = Main.get();
	Main.f(niceVarName,niceVarName);
};
```

This is not too important, but maybe if it's an easy fix, it would be nice to preserve the good output here.

**Comment by Simn** [comment]
Hmm well, that's how copy propagation works... Maybe it's possible to detect that we have a redundant non-temp variable and make the temp variable assimilate its name.
