### ISSUE TITLE
Typeload typedef assert failure with the compilation server

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#5511]
```
import sys.db.Object;

typedef A = Int;

class Main {
    static function main()
    {
        trace('hi');
    }
}
```

Results in:

```
File "src/typing/typeload.ml", line 3302, characters 15-21: Assertion failed
```

To reproduce, compile using the compilation cache twice and update the file (i.e. comment the trace) before the second run.

Note:
- the typedef is obviously necessary for that assert to fail, but what the typedef defines does not seem to matter

**Comment by jonasmalacofilho** [comment]
Update: the issue seems to be caused by the changes introduced in 7e9e0e9 and f21f47e.

**Comment by Simn** [comment]
This still reproduces.

**Comment by RealyUniqueName** [comment]
Not reproducible with the latest Haxe
