### ISSUE TITLE
haxe untyped __php__ / __var__ create tmp vars in code

### ISSUE THREAD

**Issue by willstdueswissen** [HaxeFoundation/haxe#5523]
Issue: Php create $tmp var for unytped stuff example:

```
// Some class
import php.Lib;

class Some {
    public static inline function print(v:Dynamic) {
        Lib.print(v);
    }
    public static function hi():String {
        return untyped __php__("'test'");
    }
}
```

```
// test class
class Test {
    private var _val:String;

    public function new(val:String) {
        _val = val;
    }

    public function get():String {
         return _val;
    }
}
```

```
// main class
public static function main() {
    Some.print(new Test(Some.hi()).get());
}
```

```
// php code

<?php

// Generated by Haxe 3.3.0
class Main {
    public function __construct(){}
    static function main() {
        $tmp = de_malublu_haxe_Some::hi();
        $v = _hx_deref(new de_malublu_haxe_Test($tmp))->get();
        php_Lib::hprint($v);
    }
    function __toString() { return 'Main'; }
}
```

**Comment by Simn** [comment]
Yes that can happen because `untyped` is unpredictable and the compiler is then very conservative about doing any kind of syntax transformations. I'm not sure if we can do something about this without causing a huge mess.

**Comment by nadako** [comment]
hmm, but that's not about the `untyped` in `hi` method, right? because that one isn't even inlined.

**Comment by Simn** [comment]
You're right, this seems to be a different problem.

I'm very reluctant to mess with the AST here, PHP's "parser" is really hard to get under control.

**Comment by RealyUniqueName** [comment]
Php generator indeed introduces temp vars to workaround PHP 5.x parser weaknesses. And this is not going to be changed for old php generator, sorry.
New php generator (with `-D php7`) targets PHP 7.x which has much better parser,  so generator does not need to create additional temp vars.
