### ISSUE TITLE
Inline iterator and @:coreApi

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#5527]
Probably a known issue:
I just learned that it's not possible to have a fully inlined iterator when its return type is `Iterator<T>`, which is enforced by `@:coreApi` on `Array`. Is there a workaround without dropping `@:coreApi`?

**Comment by Simn** [comment]
If this is only about `@:coreApi`, then we'll deal with it on a case-by-case basis. Iterators on `Array` have seen some improvements already, so let us know if there's still a concrete problem on some target.
