### ISSUE TITLE
@:genericBuild type parameter passthrough

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5530]
``` haxe
@:genericBuild(Macro.build())
class Generic<T>{}

typedef Object<T> = {
  value:Generic<T>
}

static function main() {
  var obj:Object<String>;
}
```

For the above code, I will get `Object.T` as the type parameter inside `Macro.build()`. Is it possible to let the type parameter "pass through" the typedef, so I can get `String` in the generic build macro?

**Comment by Simn** [comment]
I don't think that's viable. Basically, `@:genericBuild` runs on each occurrence of a type, which in this case is `Generic<T>`. We would have to somehow delay this process which adds too much complexity for the potential gains.
