### ISSUE TITLE
Position completion: report positions for get / set keywords in properties

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5533]
For instance:

```haxe
var time(get, set):Float;
```

For `get`, the position of `get_time()` should be reported, for `set` the position of `set_time()`. This would allow `Go To Definition` to work for these in VSHaxe, like it already does in FD.

**Comment by Simn** [comment]
Should it really do that by default? You might want the position of the
get/set identifier themselves, e.g. to replace them with a different
accessor.

**Comment by Gama11** [comment]
Wouldn't that fall under a separate (renaming) display mode?
