### ISSUE TITLE
Manually execute an expression macro

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5534]
I would like to see something like the following inside `haxe.macro.Context`

``` haxe
public static function resolveExpressionMacro(expr:Expr):Expr;
```

What it does is to type the given `expr`, execute any expression macros it founds, then return the transformed expression.

`Context.getTypedExpr(Context.typeExpr(expr))` is close to what I need, but some information will be lost (e.g. metadata tags)

Is it possible? Or I should post this to the proposal repo?

**Comment by Simn** [comment]
This is not going to work. Macros are executed as part of the typing process, so there is no transformed AST state at any point. The macro result is instead immediately typed, so `Context.typeExpr` is the best you can get.

**Comment by kevinresol** [comment]
Sorry, but I don't quite get this. The proposed function takes `Expr` as input and any expression macro inside it must be returning `Expr` as well...

**Comment by Simn** [comment]
Yes, but there is no individual "expression-expanding" mode while typing, so the compiler never sees the original expression with all macros executed.

Imagine a block like so:

```haxe
{
    expr1;
    expr2;
    expr3;
}
```

The typer walks that block expression by expression and types them. You could say that after typing `expr1` you have this:

```haxe
{
    typedExpr1;
    expr2;
    expr3;
}
```

Let's say `expr2` is a macro call. We don't know yet that it's a macro call, so we have to type it first:

```haxe
{
    typedExpr1;
    typedExpr2;
    expr3;
}
```

Now we know it's a macro call, so we can execute the macro:

```haxe
{
    typedExpr1;
    expr2' = call macro typedExpr2;
    expr3;
}
```

And then we can type `expr2'`:

```haxe
{
    typedExpr1;
    typedExpr2';
    expr3;
}
```

At no point do we have this, which I believe is what you're looking for:

```haxe
{
    expr1;
    expr2';
    expr3;
}
```

**Comment by kevinresol** [comment]
Got it. 
The macro returned expression may contain some macro call as well. So the compiler need to type it immediately and resolve macro calls recursively. 
However,  is it possible for the compiler to store the "last expr" during the recursive process and reconstruct the "final expr"?
