### ISSUE TITLE
Missing return values in std.haxe.web.Request class for Flash target

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/haxe#5535]
Excerpt from Travis build with latest haxe version:

/home/travis/haxe/std/haxe/web/Request.hx:29: lines 29-45 : Missing return: Map<String, String>
/home/travis/haxe/std/haxe/web/Request.hx:50: lines 50-58 : Missing return: String
/home/travis/haxe/std/haxe/web/Request.hx:63: lines 63-71 : Missing return: String

**Comment by Simn** [comment]
This class is simply not supported on Flash. However, the way we handle the conditional compilation there is not ideal. Also, I wonder why this doesn't fail in our tests.

**Comment by FrancisBourre** [comment]
Thanks for the feedback Simn. We found it finally, it was an accidental import on our side.
