### ISSUE TITLE
[display] signature completion with argument default values instead of just "?"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5538]
This is basically another instance of #2561 as a reminder:

According to @nadako, this info should be easy to provide in his new Json-based display output.

**Comment by Simn** [comment]
This requires an appropriate structure to be defined in vshaxe first so I know what to target. Note that JsonFunctionSignature does not contain default values.

**Comment by Gama11** [comment]
Could we just add `@:optional var value:String` to `JsonFunctionArgument` to match what `haxe.rtti.CType.FunctionArgument` / dox has? Haxe doesn't have more info than that anyway, right?

**Comment by Simn** [comment]
It's a syntax expression, but we don't have a generate function for that yet.

**Comment by Gama11** [comment]
You mean for sending the default value as a proper expression structure rather than just a String? Hadn't really considered that, but that would probably be a good idea, especially if more complex default values such as enum values are allowed in the future..

**Comment by Gama11** [comment]
This is now fixed! \o/

![](https://i.imgur.com/5wKMaAa.png)
