### ISSUE TITLE
Commas in command paths truncate paths on Windows (Sys.command, sys.io.Process)

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/haxe#5541]
If you have commas anywhere in the path of a command, say in a directory name like haxelib does with its version directories, Sys.command and sys.io.Process seem to truncate said paths at the comma.

In the wild I encountered this when trying to execute a command that was installed via haxelib, thus the comma delimited version as a directory name.

Here is an example to reproduce:
https://github.com/james4k/haxe-command-issue

**Comment by andyli** [comment]
What versions of Haxe and Neko are you using?
It could have been fixed in Haxe 3.3 + Neko 2.1.

**Comment by james4k** [comment]
Oops, I forgot to give that critical info.

```
haxe -version
3.3.0 (git build development @ f38ca15)
```

This is using the night build from here: http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows-installer/haxe_2016-08-22_development_f38ca15.tar.gz

**Comment by andyli** [comment]
I've committed a partial fix in 494b409c093bad5bd67133b77e770e181385f1c6, which makes the following works:
```haxe
class Main {
	public static function main():Void {
		trace(Sys.command(sys.FileSystem.absolutePath("some,script,name.bat"), []));

		var p = new sys.io.Process("some,script,name.bat", [""]);
		trace(p.stdout.readAll());
		trace(p.exitCode());
		p.close();
	}
}
```

The fix is only partial because `Sys.command` requires using absolute path of the file. I'm not sure whether we can support relative path with funny characters since I've just found out even Python doesn't support that correctly:

```python
import subprocess
p = subprocess.Popen(["some,script,name.bat"], shell=True)
print(p.wait())
```
prints:
```
'some' is not recognized as an internal or external command,
operable program or batch file.
1
```

**Comment by james4k** [comment]
Hmm, as far as I knew it is a problem with absolute paths as well, but need
to test

**Comment by james4k** [comment]
Oh, I misread. I see you fixed the absolute path case. This looks good. The remaining problem seems to occur when executing via the shell in general, even when you do it directly in Command Prompt. 

What might be nice in the docs is to have more clarity on when the shell is involved, and when it isn't. Intuitively, it feels like Sys.command would use the shell, and sys.io.Process would not, but it seems that sys.io.Process does use it for Windows. But I don't know, maybe on Windows it can't quite get away from the shell?

Regardless, I think this closes the issue. Thanks!
