### ISSUE TITLE
Local variable names keep getting longer and longer in compilation server mode and C#

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5542]
When compiled with compilation server feature, Haxe renames arguments if they don't seem to be referenced. This caused some of my untyped code not to compile. `length` is referenced, but its name also got changed for some reason.

https://github.com/openfl/starling/blob/9e52d5b52bb45067f3471b54af23db11045359a3/starling/utils/Float32ArrayWrapper.hx#L90

```cs
public virtual unsafe void writeBytes(global::openfl.utils.ByteArrayData bytes, global::haxe.lang.Null<uint> __temp___temp_offset11131113, global::haxe.lang.Null<uint> __temp___temp_length11141114) {
			uint __temp___temp___temp_length111411141114 = ( ( ! (__temp___temp_length11141114.hasValue) ) ? (((uint) (0) )) : ((__temp___temp_length11141114).@value) );
			uint __temp___temp___temp_offset111311131113 = ( ( ! (__temp___temp_offset11131113.hasValue) ) ? (((uint) (0) )) : ((__temp___temp_offset11131113).@value) );
			((global::openfl.utils.ByteArrayData) (this.data) ).__resize(((int) (((uint) (( __temp___temp___temp_length111411141114 + this.data.position )) )) ));
			fixed(byte *dst = this.data.b, src = bytes.b){;
			byte *d = dst + this.data.position, s = src + offset.@value;
			{
				int _g1 = 0;
				int _g = ((int) (__temp___temp___temp_length111411141114) );
				while (( _g1 < _g )) {
					int i = _g1++;
					*d = *s;
					d++;s++;
				}
				
			}
			
			};
			this.data.position = ((int) (((uint) (( __temp___temp___temp_length111411141114 + this.data.position )) )) );
		}
```

And why variable names start with lots of `__temp`?? `__temp___temp___temp_length111411141114` looks weird.
I compiled to C# this time, but I'm not sure if this is something specific to C#.

**Comment by Simn** [comment]
You should not rely on the names of local variables or function arguments.

**Comment by vroad** [comment]
Maybe you are right, but there are things that cannot be done without untyped...

**Comment by Simn** [comment]
You can use interpolation, e.g. `untyped __cs__("code code {0} code code", offset)`.

**Comment by vroad** [comment]
Thanks, I don't know about that.

This should have been reported as a bug that makes variable names very long. Why do variable names get longer every time application is built?

**Comment by Simn** [comment]
Does that stop at some point or does it keep getting longer and longer?

**Comment by vroad** [comment]
Looks like it keeps getting longer and longer.

**Comment by Simn** [comment]
Probably related to #5320.

**Comment by Simn** [comment]
Can you check if this is still a problem with latest Haxe?

**Comment by vroad** [comment]
Tried again with latest development version, and looks like the problem has gone. It does not seem to improve compilation performance by a large margin on C# though.
