### ISSUE TITLE
[cs] C# takes long time to generate source code than C++?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5546]
I compared C# compilation speed of a simple starling-openfl based application, and found that its performance is worse than C++ for some reason. In total C# target is faster because C++ compilation is slow at generating final executable, but why does C# take longer time to generate source code?

JavaScript is fastest of all targets I tested, but I don't know why it's very first. Maybe because it only need to generate single file?

C#

```
Total time : 12.532s
------------------------------------
  analyzer : 0.188s, 1%
  expression to string : 0.909s, 7%
  filters : 1.110s, 9%
  gencommon_filters : 5.449s, 43%
  generate cs : 1.445s, 12%
  haxelib : 0.059s, 0%
  macro execution : 0.377s, 3%
  other : 1.403s, 11%
  parsing : 0.550s, 4%
  typing : 1.042s, 8%
```

C++

```
Total time : 8.779s
------------------------------------
  analyzer : 0.205s, 2%
  filters : 0.563s, 6%
  generate cpp : 4.581s, 52%
  macro execution : 0.285s, 3%
  other : 1.043s, 12%
  parsing : 1.293s, 15%
  typing : 0.809s, 9%
```

JavaScript

```
Total time : 4.116s
------------------------------------
  analyzer : 0.197s, 5%
  filters : 0.600s, 15%
  generate js : 0.140s, 3%
  macro execution : 0.411s, 10%
  other : 0.839s, 20%
  parsing : 0.986s, 24%
```

**Comment by nadako** [comment]
gencommon filters...

**Comment by ncannasse** [comment]
C# is based on the (in)famous gencommon, which apply a great number of incremental "filters" (map over the AST). As a result it's less efficient. I think @waneck has plans to remove gencommon sometime this century.

**Comment by vroad** [comment]
I've found that my Haxe build runs faster than one in build server. Perhaps because my build is 64bit?

C# (32bit Haxe)
```
Total time : 12.513s
------------------------------------
  analyzer : 0.285s, 2%
  expression to string : 0.822s, 7%
  filters : 1.155s, 9%
  gencommon_filters : 5.365s, 43%
  generate cs : 1.556s, 12%
  haxelib : 0.058s, 0%
  macro execution : 0.353s, 3%
  other : 1.358s, 11%
  parsing : 0.407s, 3%
  typing : 1.156s, 9%
```

C# (64bit Haxe)
```
Total time : 7.797s
------------------------------------
  analyzer : 0.201s, 3%
  expression to string : 0.277s, 4%
  filters : 1.216s, 16%
  gencommon_filters : 2.396s, 31%
  generate cs : 0.748s, 10%
  haxelib : 0.055s, 1%
  macro execution : 0.348s, 4%
  other : 1.277s, 16%
  parsing : 0.410s, 5%
  typing : 0.868s, 11%
```

**Comment by Gama11** [comment]
Wow, that's a huge difference.

**Comment by jobs-git** [comment]
Time to do 64bit?

**Comment by vroad** [comment]
I'm not sure what filter actually does. I can see that generated C# source code has many casts, is that one of the things filters do?

Transforming constructor to a static method might also be.
https://github.com/HaxeFoundation/haxe/issues/2805#issuecomment-242884149

**Comment by vroad** [comment]
Why doesn't Haxe have 64bit builds on Windows? Does that have issues?

**Comment by nadako** [comment]
Last time I checked, there was some issue with loading neko modules for macros, but that might because neko isn't 64-bit as well. @ncannasse is there a problem running neko on 64bit?

**Comment by vroad** [comment]
I know that you can't mix 64bit binary and 32bit binary in the same process, but is that what Haxe may do when executing certain kind of macros?

**Comment by Simn** [comment]
Haxe 64 bit works now.
