### ISSUE TITLE
[lua] Date.now() error

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#5547]
If i use Date.now() in lua

```
public static function main() {
	trace(Date.now());
}
```

it generate this code:
```
 local t = _G.os.time();
  local d = _hx_empty();
  
  _G.setmetatable(d,_hx_o({__fields__={__index=true},__index=Date.prototype}));
  d.t = (t) / (1000);
  d.d = _G.os.date("*t",d.t);
```

And an exception:
`bad argument #2 to 'date' (number has no integer representation)`

This is the line:
`d.d = _G.os.date("*t",d.t);`

**Comment by malublu** [comment]
call musst be also

`fromTime(lua.Os.time()*1000)`

Std.int() only protects against exception

**Comment by jdonaldson** [comment]
Thanks for this, merged.
