### ISSUE TITLE
Reusing source files from previous build on C++/C# for shorter compilation time?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5550]
I want to reuse source files from previous build for testing things quickly, but is this impossible with Haxe?
Haxe always generate all source files on C++/C# even when you change single line of your code.
Time stamp of other files remains unchanged, but Haxe compilation takes the same amount of time as first build. So I guess Haxe always generates all source files.
Compilation performance can be a big problem as a project gets larger, even on targets that have relatively good performance, such as js.

Compilation server may help in reducing compilation time, but it looks still buggy, and I'm not sure if it really helps in reducing the time of final source code generation.

Another thing I've tried was macro based extern-generator, which generates extern class definition from Haxe-generated js library. I was using nodejs at that time.
It worked at some degree and allowed me to improve compilation performance, but it was very hard to create a generator that can understand any kind of Haxe code. It had problems with private classes, abstract classes, built-in types, etc. I needed to work around these issues to make this work without errors. So I gave up improving compilation performance in this method.

**Comment by vroad** [comment]
I started implementing this new option by myself... As I'm new to haxe code base and OCaml, it was harder than doing it on other environments.
It parses all hx files normally, but only overwrites a file you specified. You could reduce compilation time further by using hxml that imports that class.

Compiling fewer number of files helped in reducing total time. Compilation server may also help, but it's a bit unstable now.

```
Total time : 7.797s
------------------------------------
  analyzer : 0.201s, 3%
  expression to string : 0.277s, 4%
  filters : 1.216s, 16%
  gencommon_filters : 2.396s, 31%
  generate cs : 0.748s, 10%
  haxelib : 0.055s, 1%
  macro execution : 0.348s, 4%
  other : 1.277s, 16%
  parsing : 0.410s, 5%
  typing : 0.868s, 11%
```

After reducing number of files Haxe need to parse/write:
```
Total time : 5.683s
------------------------------------
  analyzer : 0.183s, 3%
  expression to string : 0.006s, 0%
  filters : 0.825s, 15%
  gencommon_filters : 1.909s, 34%
  generate cs : 0.158s, 3%
  haxelib : 0.082s, 1%
  macro execution : 0.344s, 6%
  other : 1.275s, 22%
  parsing : 0.331s, 6%
  typing : 0.569s, 10%
```

**Comment by Simn** [comment]
There have been various improvements to hxcpp building and I think this is possible now, so I'll go ahead and close this issue.
