### ISSUE TITLE
[cs] --remap does not work with classes loaded with -net-lib

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5552]
`--remap flash:openfl` doesn't seem to have effect on classes loaded with `-net-lib`. Haxe fails to find any types that start with `flash`.

```
C:/HaxeToolkit/haxe/lib/starling/git/starling/events/Touch.hx:12: characters 7-23 : Type not found : flash.geom.Point
```

**Comment by Simn** [comment]
I'm not sure if --remap is supposed to work like that...
