### ISSUE TITLE
Running tests locally

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#5554]
Trying to run the tests locally, most targets work without issues and their tests succeed :)

First one I had to comment the `requireAptPackages` function since I don't have apt (opensuse), so  I had to install one or two things manually, but nothing unusual when you don't have debian/ubuntu ;)

**For lua**
in `getLuaDependencies` had to add to the luarocks call (line 477 and 478) `"--local"` because the normal user can't write to `/usr/local`.
And have to run it with `TRAVIS_OS_NAME=linux TRAVIS_BUILD_DIR=$(pwd)/../ TEST=lua neko RunCi.n .`

**For java**
I need to do `rm -rf unit/bin/java-lib-tests/` before or the clone fails (if I've run it before)

**For cpp**
I get the error `Error: Could not find build target "by"`
And if I add `"-D", "source-header=haxe"` to fix it I get `Error: Could not find build target "Files\The"`
Same for 64 (if 32 is commented).
For cppia host (if commenting cpp 32 and 64) the source-header allows it compile, cppia client compiles normally and runs.
The sys test still has the error `Error: Could not find build target "by"` even with the `source-header` define.

**For as3**
No error, open a flashdebugger but don't closes it, nothing too problematic.
It ends up adding `flashplayerdebugger`, `LGPL/` and `apache-flex-sdk-4.14.1-bin` to my home, same not a huge problem but if there's an easy fix I'll take it ;)

**For flash9**
Same as as3 without flex.

Haven't looked too much into third-party yet, first error is:

```
Changing directory to /usr/lib/haxelib/hxtemplo/3,2,0/src/..
Command: haxe [build.hxml]
Error: Could not process argument build.hxml (file not found)
invalid character:  
Command exited with 1 in 0s: haxe [build.hxml]
test third-party failed
```

There are some files that aren't cleaned, like the flashplayer.tar.gz (I've got 6 now :))
but also some build dir like cpp's sys `bin/cpp`.

**Comment by Simn** [comment]
I don't really know what to do with this issue...

**Comment by ibilon** [comment]
Yeah this is more of a situation report than an issue,
I'll make a pr about the small issues I mentioned.

**Comment by jdonaldson** [comment]
FWIW, I'm using "hererocks" for managing the lua environments for the tests.  It should sidestep the permission issues.

**Comment by Simn** [comment]
I'll go ahead and close this for now. If there's anything actionable, feel free to open new issues.
