### ISSUE TITLE
import.hx with #if !macro + build macro + --macro addMetadata() = extension method not found

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5559]
This one is spread over a few files, couldn't seem to isolate it any further:

`build.hxml`:

```hxml
-main Main
-cp source
--macro addMetadata('@:build(Build.build())', 'Main')
-neko run.n
```

`Main.hx`:

```haxe
class Main {
	public static function main() {
		OtherClass.foo();
	}
}
```

`OtherClass.hx`:

```haxe
class OtherClass {
	public static function foo() {
		"".endsWith("");
	}
}
```

`import.hx`:

```haxe
#if !macro using StringTools; #end
```

`Build.hx`:

```haxe
class Build {
	public static function build() {
		trace("build macro executed");
		return null;
	}
}
```

_______________________________________

Error:

```
source/Build.hx:3: build macro executed
source/OtherClass.hx:3: characters 2-13 : String has no field endsWith
```
______________________________________

Not idea sure what's going on here... I thought this may be related to #4956, but it seems different after all? No `Context.getType()`, in fact the build macro is _empty_.

Observations:
- compiles if there's no `--macro`
- compiles if `import.hx`'s `using` isn't wrapped in `#if !macro`
- compiles if the `OtherClass` type is included in `Main.hx`
- compiles if the `@:build` meta is added to `OtherClass` instead

Thanks to @ousado for helping me isolate this one.

**Comment by Gama11** [comment]
Another observation: if you move `Build` into `Main.hx`, the error turns into:

```
?:1: characters 2-7 : Build failure
```

**Comment by Simn** [comment]
This happened because we were caching the import.hx contents at parser-level but didn't create a new lookup for the macro context. The non-macro and macro contexts were then sharing the same lookup, so the empty import.hx affected the non-macro compilation too.
