### ISSUE TITLE
Failing lua Math tests

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5560]
I just found a few failing Math tests which are currently not actually checked:

```
Math.unit.hx:54: false should be true
Math.unit.hx:56: false should be true
Math.unit.hx:279: false should be true
Math.unit.hx:281: false should be true
```

Fortunately, it looks like Lua is the only target failing so we can activate these tests after fixing.

**Comment by jdonaldson** [comment]
I might have fixed this on an earlier commit.  They're passing now.
