### ISSUE TITLE
[analyzer] inline functions that end up fused into their call place

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5566]
not a priority of course, but maybe we should move the self-calling anon function inline optimization after fusion:

``` haxe
class Main {
    static function main() {
        // explicit self-calling function - inlined
        trace((function(a, b) return a+b)(1,2));

        // fused self-calling function - not inlined
        trace({
            function f(a, b) return a+b;
            f(1,2);
        });
    }
}
```

``` js
Main.main = function() {
    console.log(3);
    console.log((function(a,b) {
        return a + b;
    })(1,2));
};
```

**Comment by nadako** [comment]
This might help with real-world cases, when user prefer to define a named callback first (i saw @Simn doing this in haxe-languageserver)
```haxe
class Main {
    static function main() {
        function processReply(value) {
            trace(value);
        }
        doStuff(processReply);
    }

    static inline function doStuff(cb:Int->Void) {
        cb(15);
    }
}
```

**Comment by Simn** [comment]
This would be solved if we ran `Optimizer.reduce_expressions` again after the analyzer. The problem is that this kind of inlining might introduce bad code in value places again, so we would have to run the entire analyzer again to clean this up.

We'll have to sort this out somehow after 3.3.

**Comment by Simn** [comment]
#9228
