### ISSUE TITLE
[php] Direct call on a value of Map<?, Function>

### ISSUE THREAD

**Issue by TheoSabattie** [HaxeFoundation/haxe#5569]
Hi everyone ,

There is a little issue with map in php:

```
        var namesToFunctions:Map<String, Function> = new Map<String, Function>();
        var key:String = "sayHelloWorld";

        namesToFunctions.set(key, function() {
            trace("Hello World ! :D");
        });

        namesToFunctions.get(key)();
```

-> Result in web :

`Parse error: syntax error, unexpected '(' in //...`

-> Generated code:

```
        $namesToFunctions = new haxe_ds_StringMap();
        $namesToFunctions->set("sayHelloWorld", array(new _hx_lambda(array(), "MainServer_0"), 'execute'));
        $namesToFunctions->get("sayHelloWorld")(); // ERROR HERE
```

we can fix that with a temporary variable :

```
        var namesToFunctions:Map<String, Function> = new Map<String, Function>();
        var key:String = "sayHelloWorld";

        namesToFunctions.set(key, function() {
            trace("Hello World ! :D");
        });

        var func:Function = namesToFunctions.get(key); // HERE
        func();
```

but everyone couldn't find/understand php error/synthaxe so it should be better if you fix that
(There is no issue with Array<Function>)

Thanks ! :)

**Comment by Simn** [comment]
@RealyUniqueName: Does this work with your generator?

**Comment by RealyUniqueName** [comment]
My generator will generate the same line:
```php
$namesToFunctions->get("sayHelloWorld")();
```
Which is only supported by PHP7+

**Comment by RealyUniqueName** [comment]
Old genphp could generate this expression as a workaround:
```
($tmp = $namesToFunctions->get()) ? $tmp() : $tmp()
```

**Comment by TheoSabattie** [comment]
Why could genphp generate ternary?

```
$tmp = $namesToFunctions->get();
$tmp();
```

**Comment by RealyUniqueName** [comment]
I just proposed simple solution which can be inlined instead of original expression without the need to handle parent expressions.
Take a look at this example:
```haxe
var e = 2 + (q = w.some()() + 1 + w.other()(w.antoher()()));
```
You will need to take care about a lot of things happening here to be able to resolve it with your solution.

**Comment by RealyUniqueName** [comment]
Implemented using `call_user_func`:
```
$namesToFunctions->get("sayHelloWorld")();
//now generated as
call_user_func( $namesToFunctions->get("sayHelloWorld"));
```
