### ISSUE TITLE
[cs] Interface with Function type parameter causes compilation errors on cs?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5570]
Some of `FunctionVector` methods from OpenFL don't compile on cs because generated code doesn't implement interface methods in a way C# compiler expected. Why do these methods (`splice()`, `slice()`, and `copy()`) have return value of `IVector` instead of `IVector<object>`?

`pop()` and `shift()` also fail to compile on cs because it returns `object` instead of `Null<object>`. Not sure how we can handle this properly on cs.

https://github.com/openfl/openfl/blob/8e776de75415eb1033724e81d3ab65af7674882b/openfl/Vector.hx#L850
https://gist.github.com/vroad/c79cde1b9cc599feee004e6c4f719cd8#file-vector-cs-L1538-L1550
https://gist.github.com/vroad/c79cde1b9cc599feee004e6c4f719cd8#file-vector-cs-L1652
https://gist.github.com/vroad/c79cde1b9cc599feee004e6c4f719cd8#file-vector-cs-L1690

``` cs
        global::openfl._Vector.IVector global::openfl._Vector.IVector<object>.splice(int pos, int len) {
            return ((global::openfl._Vector.IVector) (this.splice(((int) (pos) ), ((int) (len) ))) );
        }


        global::openfl._Vector.IVector global::openfl._Vector.IVector<object>.slice(global::haxe.lang.Null<int> pos, global::haxe.lang.Null<int> end) {
            return ((global::openfl._Vector.IVector) (this.slice(pos, end)) );
        }


        global::openfl._Vector.IVector global::openfl._Vector.IVector<object>.copy() {
            return ((global::openfl._Vector.IVector) (this.copy()) );
        }
```

**Comment by Simn** [comment]
Could you provide a proper minimal example of this issue?

**Comment by RealyUniqueName** [comment]
Not reproducible in the latest dev:
```cs
public virtual global::_Main.IVector<object> slice(global::haxe.lang.Null<int> startIndex, global::haxe.lang.Null<int> endIndex) {
```
