### ISSUE TITLE
[cs (/java?)] possible hashing clash in FieldLookup

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5572]
The following fails:

``` haxe
class Main {
    var baseReward:String;
    static var f = "user_3235_65290";
    static function main() {
        var o = {};
        Reflect.setField(o, f, "");
        Reflect.fields(o);
    }
}
```

```
Необработанное исключение: haxe.lang.HaxeException: Field not found for hash -1665817185
   в haxe.lang.FieldLookup.lookupHash(Int32 key) в d:\Code\playground\cs_out\src\haxe\lang\FieldLookup.cs:строка 137
   в haxe.lang.DynamicObject.__hx_getFields(Array`1 baseArr) в d:\Code\playground\cs_out\src\cs\internal\HxObject.cs:строка 358
   в Reflect.fields(Object o) в d:\Code\playground\cs_out\src\Reflect.cs:строка 45
   в Main.main() в d:\Code\playground\cs_out\src\Main.cs:строка 36
   в EntryPoint__Main.Main() в d:\Code\playground\cs_out\src\Main.cs:строка 7
```

I'm not sure if this is a regression or not, but this is critical for my production code, so could you please look into this @waneck? I'll be checking it too.

**Comment by nadako** [comment]
```haxe
class Main {
    static function main() @:privateAccess {
        trace(cs.internal.FieldLookup.doHash("user_3235_65290"));
        trace(cs.internal.FieldLookup.doHash("baseReward"));
    }
}
```
traces
```
Main.hx:3: 1665817184
Main.hx:4: 1665817184
```

**Comment by nadako** [comment]
@waneck see slack discussion pls

**Comment by nadako** [comment]
@ncannasse I added a test for this in cb4a571c4babb7eff8703cf7f98ab337b8044538, but disabled it for Neko since it fails because of the same hash clash. You might want to fix it somehow.

**Comment by ncannasse** [comment]
I will not change how fields are hashed in neko, that would break things such as native serialization. I will however look at it for HL :)

**Comment by nadako** [comment]
not sure if it's really breaking. what we eventually did for C# is not changing the hashing algorithm, but detecting collisions and using an additional container for fields with coflicted hashes.

**Comment by ncannasse** [comment]
Yes I saw the change, but there might be much more code involved for neko, and it also adds an extra entry in all objects (there is no static object in neko) which will increase memory footprint

**Comment by nadako** [comment]
Just tested it, this is a problem on HL too, please do something :)

**Comment by Gama11** [comment]
@ncannasse Did you forget to enable the test for HL? Still disabled there:

https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue5572.hx#L9

**Comment by Gama11** [comment]
Btw, I think a Flixel user just ran into this on Neko:

![](http://i.imgur.com/xICPdHw.png)

If this is not going to be fixed, could there at least be a more helpful error message? Something along the lines of "please change one of the field names"...
There also isn't any position reported, so the user is left with potentially no clue where the error came from.

Another realization: it looks like the identifiers don't even have to be in the same file, so you could imagine a really unlucky situation where two specific libraries cannot be included in the same project together because they produce a hashing conflict...

**Comment by back2dos** [comment]
> Another realization: it looks like the identifiers don't even have to be in the same file, so you could imagine a really unlucky situation where two specific libraries cannot be included in the same project together because they produce a hashing conflict...

The way I understand it a hashing conflict is only an issue if the two fields are supposed to be stored in the same object. If you have convertFoodCat on one object and squadMemberDetail on another, everything should be fine.

**Comment by Gama11** [comment]
Looks like you're right. I thought I had tested this earlier with the vars split over two files - but apparently I made a mistake when doing that, since it works fine now. :)

**Comment by ncannasse** [comment]
The actual problem is not accessing the object, it's more printing it. You will already get some error at compilation time in case the two fields are colliding.

Please note that using such generated names is a bad idea since it will quickly fill the field names cache and somehow case memory leaks. It would maybe be necessary to have some kind of GC of such names.

**Comment by mastef** [comment]
Just ran into this when serializing some external JSON data. 

The script is compiled with `import openfl._internal.symbols.SpriteSymbol;` and `import openfl._internal.swf.SWFLite;`, and when I try to `haxe.Json.parse()` a json string that contains a key called `CC_Cloud_Large` it will error out at runtime : `Uncaught exception - others.c(440) : Field conflict between setInt16 and CC_Cloud_Large`.

When trying to compile it with the json data embedded the error changes to `Error: Field hashing conflict setInt16 and CC_Cloud_Large` at compile time ( related project : [testneko.zip](https://github.com/HaxeFoundation/haxe/files/1505279/testneko.zip) )

From the thread I have these notes : 
A) The objects/fields don't seem to be related in this example
B) When we remove the 2 `openfl` imports, the issue goes away
C) The colliding field in this case is a static extended method on lime's ArrayBuffer, but `var b = haxe.Json.parse(jsonStringBAD);` would be cast to `Dynamic` ( or another type ) which would not extend lime's ArrayBuffer, right? So those 2 should not be related
