### ISSUE TITLE
ADD_REVISION=1 only works for clean builds

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5576]
The commit ID in `haxe -version` is only updated for me when I build Haxe locally if I do a `make clean` first.

It seems like `version.ml` isn't updated if I just check out a different commit and then run `haxe ADD_REVISION=1 -f makefile.win haxe`.

I'm not very familiar with make files, so I'm not sure what the best solution would be. I guess ideally a version mismatch should be detected, and `version.ml` should only be updated in that case. One could also always update `version.ml`, but that would probably increase build times unnecessarily?

**Comment by Simn** [comment]
My biased 10 second test suggests that this works fine now.
