### ISSUE TITLE
Unit testing for non-macro / --interp projects

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5579]
`tests/misc/projects` is great, but has an unfortunate limitation: it expects `--interp`, meaning it can't be used to test other targets. As a result, there is no way to unit-test issues that need a specific project structure or compiler argument (for instance a define).
I've reported several cpp regressions that I couldn't add tests for because of this:
#5549
#5043
#5023

**Comment by Simn** [comment]
I don't get what you mean. The misc tests are a collection of directories that have .hxml files which are picked up and executed. What do you mean "it expects --interp"?

**Comment by Gama11** [comment]
Running a simple, empty `Main` with `-cpp cpp` there reults in the macro target failing with `Error: Library hxcpp is not installed`:

https://github.com/Gama11/haxe/commit/3b3b58826f7e195e48ec7ab8862b39ce8d392f80
https://travis-ci.org/Gama11/haxe/jobs/157575888#L3082

**Comment by Gama11** [comment]
#5740 also can't be tested without this I think, since it requires multiple files.

**Comment by Simn** [comment]
Ah, right... cpp is the only one which can't be used in the misc tests because it runs in its own CI bubble.

**Comment by Simn** [comment]
I think this is obsolete.
