### ISSUE TITLE
Increment / decrement reported as having no effect on property with setter

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5581]
```haxe
class Main {
	public static function main() {
		i++;
		i--;
		
		i += 1;
		i -= 1;
	}

	static var i(default, set):Int = 0;

	static function set_i(i:Int):Int {
		return Main.i = i;
	}
}
```

The unops are highlighted as having "no effect":

![](http://i.imgur.com/ylC12d2.png)

**Comment by Simn** [comment]
The typer transform these in a way that it inserts the local at the end. If this happens in value-place that local has no effect, but we obviously shouldn't report it to the user.
