### ISSUE TITLE
For a class implementing an interface function, compiler is not enforcing exact arg type

### ISSUE THREAD

**Issue by andywhite37** [HaxeFoundation/haxe#5591]
See example below.

I'm not sure if this is the desired or expected behavior, but it was confusing that when I changed the interface function's `options` type, the compiler did not require me to update my `options` type in the implementing class.

```haxe
interface IThing {
    public function test(options: { key: String }) : Void;
}

class Thing implements IThing {
    public function new() {}
    
    // note: options type differs from interface options type
    public function test(options: { }) : Void {
        trace('hi');
    }
}

class Test {
    static function main() {
        var thing = new Thing();
        thing.test({});
    }
}
```

**Comment by Simn** [comment]
Variance allows this because the additional field doesn't do any harm. You can use Thing through an IThing reference and call it with the additional field, but that's just like calling it with a child class instance instead of a base class one.

**Comment by fponticelli** [comment]
I would understand the opposite. There is no additional field in `options`, there is a missing one. I agree that if this is the expected behaviour, it is very confusing.

**Comment by Simn** [comment]
Function arguments are contravariant, not covariant:

```haxe
var thing:IThing = getThing();
thing.test({key: "foo"}); // ok, the actual implementation simply ignores it
```

If you had the opposite you could call `thing.test({})` there, but the actual implementation would expect `{key: String}`.
