### ISSUE TITLE
Haxelib creates ~ folder on Ubuntu

### ISSUE THREAD

**Issue by PeyTy** [HaxeFoundation/haxe#5595]
Tested on 3.2.1

```php
peyty@peyty-U16041:~$ haxelib setup
Please enter haxelib repository path with write access
Hit enter for default (/usr/share/haxelib)
Path : ~/.haxelib           
haxelib repository is now /home/peyty/~/.haxelib/
```

It *really* creates `/home/peyty/~/.haxelib/`:

![image](https://cloud.githubusercontent.com/assets/3642643/18222487/598da780-71a1-11e6-9365-2ce434956f3d.png)

---

Expected behavior: ~ is same as /home/peyty, so I expect /home/peyty/.haxelib folder to becreated.

```php
peyty@peyty-U16041:~$ ls ~
~                 mm.cfg        Документы    Музыка         Шаблоны
Dropbox           stencylworks  Загрузки     Общедоступные
examples.desktop  Видео         Изображения  Рабочий стол
peyty@peyty-U16041:~$ ls /home/peyty/
~                 mm.cfg        Документы    Музыка         Шаблоны
Dropbox           stencylworks  Загрузки     Общедоступные
examples.desktop  Видео         Изображения  Рабочий стол
```

**Comment by ibilon** [comment]
That's a haxelib issue could you reopen over there https://github.com/HaxeFoundation/haxelib/issues

Also you can't do ~/.haxelib/ (even if ~ was correctly detected) because haxelib use a ~/.haxelib file to store data.

**Comment by PeyTy** [comment]
@ibilon my bad! https://github.com/HaxeFoundation/haxelib/issues/351
