### ISSUE TITLE
Static extension and @:overload

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5596]
The following code does not compile:
Tried on 3.3.0-rc.1: http://try-haxe.mrcdk.com/#BC5F6
and on 3.2.0: http://try.haxe.org/#829fe

``` haxe
import js.JQuery;
using Test.Extension;

class Test {
    static function main() {
        var j = new JQuery('.selector');
        j.ext({success: true});
        j.ext('success');
        j.ext('success', 'fail'); // Error: Too many arguments
    }
}

extern class Extension {
    @:overload(function(j:JQuery, params:haxe.extern.Rest<String>):JQuery {})
    public static function ext(j:JQuery, options:{}):JQuery;
}
```

**Comment by kevinresol** [comment]
Oh well, it is nothing about `Rest`, but seems like `@:overload` isn't doing its job.

**Comment by andyli** [comment]
It is indeed an issue an issue of "static extension and @:overload and Rest". A slightly less confusing example without the use of jQuery:

```haxe
using Test.Extension;

class Test {
	function new():Void {}

	static function main() {
		var t = new Test();
		t.ext('success', 'fail'); // Error: Too many arguments
	}
}

extern class Extension {
	@:overload(function(t:Test, params:haxe.extern.Rest<String>):Void {})
	public static function ext(t:Test):Void;
}
```

**Comment by kevinresol** [comment]
I think it is not about Rest, but the overload is not respected at all.

**Comment by Simn** [comment]
Yes they are currently ignored. It shouldn't be a problem to add this because static extension resolution is a trial & error algorithm anyway.

**Comment by kLabz** [comment]
Cannot reproduce since 4.2.0
