### ISSUE TITLE
generated code should match haxe project's file layout better

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#5597]
Please separate the main generated file, from all the haxe "support" code (stdlib translation).
Ideally, match the generated code to the haxe code's file structure.
benefits: easier to understand/debug, preferable when collaborating with others in target language.
for example, in javascript generation.

**Comment by Simn** [comment]
This is not an actionable issue, if you have any concrete suggestions please write a proper proposal for https://github.com/HaxeFoundation/haxe-evolution
