### ISSUE TITLE
js target + dce full still generates a lot of unneeded code

### ISSUE THREAD

**Issue by kobi2187** [HaxeFoundation/haxe#5598]
when compiling to js, even a simple hello world, brings with it multiple unrelated classes and functions - all the haxe support.
in other words, -dce doesn't seem to work.

**Comment by Simn** [comment]
What code are you compiling?

**Comment by nadako** [comment]
That's not true, e.g. look at the generated code in http://try.haxe.org/. I had no issues whatsoever with DCE keeping unnecessary things. Please provide a concrete example.
