### ISSUE TITLE
@:commutative only works for static functions

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#5599]
``` haxe
class Test {
    static function main() {
        var i:I = 1;
        trace(i == '1');
        trace('1' == i); // error: I should be String
    }
}

abstract I(Int) from Int to Int {
    @:op(A==B)
    @:commutative
    public function eqString(s:String):Bool
        return Std.string(this) == s;
}
```

The [doc on operator overloading](https://haxe.org/manual/types-abstract-operator-overloading.html) uses an instance method in the example and mentions the use of `@:commutative`. It suggests that `@:commutative` will work for instance methods but `@:commutative` works only for static methods. I think it make sense to support using `@:commutative` on static methods.

**Comment by R32** [comment]
ah, I know this,  it's can be auto static-extension.

```haxe
abstract I(Int) from Int to Int {
    @:op(A == B)
    @:commutative
    public static function eqString(i:I, s:String):Bool 
        return Std.string(i) == s;
}
```

**Comment by Simn** [comment]
Could you verify that this is not a regression from 3.2?

**Comment by Simn** [comment]
There's a piece of code that explicitly prevents this:

```ocaml
loop (if left then a.a_ops else List.filter (fun (_,cf) -> not (Meta.has Meta.Impl cf.cf_meta)) a.a_ops)
```

This reads: if we are not in left mode (i.e. we're in commutative mode), filter all abstract implementation fields. This was part of my abstract operator overloading rewrite (#3341) from almost two years ago, so this is not a regression. Our unit tests still compile if we remove this filter, but I'll have to investigate what effects this might have in detail after 3.3.

**Comment by Simn** [comment]
I still don't remember why that code is there, so I removed it. What could possibly go wrong...
