### ISSUE TITLE
[PHP] Reflection

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#5608]
Hej,
I get this error at runtime :

> Class haxe_remoting_HttpConnection does not have a property named __dynamics

When doing that :
`trace( Reflect.fields( haxe.remoting.HttpConnection ) );`
Maybe it's related to this issue ? https://github.com/HaxeFoundation/haxe/issues/5383

**Comment by RealyUniqueName** [comment]
Actually `Reflect.field()` is [only guaranteed to work on anonymous structures](http://api.haxe.org/Reflect.html#fields)

**Comment by filt3rek** [comment]
Hej,
Yes I know that, but here I've written a reduced simple example to show the error I got. It only occurs on PHP target.
I mean It should return an empty array or at least "null" but not throw this kind of exception...

**Comment by RealyUniqueName** [comment]
Ah, ok. I can do that )
