### ISSUE TITLE
[display] @type "throw" is unknown

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5619]
![](http://i.imgur.com/citusuz.png)

```haxe
class Main {
	public static function main() {
		throw "Test";
	}
}
```

**Comment by Simn** [comment]
That's actually accurate as far as our typing system is concerned. Not sure what else you'd want here, `throw` doesn't exactly carry a value...

**Comment by nadako** [comment]
Maybe it would make sense to not to return a type for some expressions, like `throw` and `return`, but I don't know, this could be useful for haxe compiler debugging :)

**Comment by Gama11** [comment]
I think `unknown` just looks a bit broken, outputting nothing would be better.

**Comment by Simn** [comment]
That's something vshaxe should take care of, I see no reason to hide information from the Haxe-side.

**Comment by nadako** [comment]
The language server shows monomorphs as `unknown`.

**Comment by Gama11** [comment]
Wouldn't `Unknown<0>` be "more correct" there? That's what it does for arrays anyway:

![](http://i.imgur.com/mgShhni.png)

**Comment by nadako** [comment]
I deliberately changed that to return `unknown`, because I thought it'll be more user friendly, but I'm not so sure now.

**Comment by Gama11** [comment]
`Unknown<0>` is at least somewhat documented here: https://haxe.org/manual/type-system-type-inference.html

`unknown` is just .. well, unknown. And makes things inconsistent with compound types.
