### ISSUE TITLE
[display] enum constructors use k="var" instead of k="enum" in field completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5623]
In toplevel completion, enums use `k="enum"`:

``` xml
<i k="enum" t="RegularEnum">Constructor</i>
```

This allows vshaxe to display the correct icon:

![](http://i.imgur.com/pFmLptC.png)

In field completion, this is not the case:

![](http://i.imgur.com/ZbGthsa.png)

``` xml
<i n="Constructor" k="var"><t>RegularEnum</t><d></d></i>
```

``` xml
<i n="AbstractConstructor" k="var"><t>EnumAbstract</t><d></d></i>
```

Would be nice if this was consistent across the two display modes.

---

``` haxe
class Main {
    public static function main() {
        RegularEnum.|
    }
}

@:enum abstract EnumAbstract(String) {
    var AbstractConstructor = "";
}

enum RegularEnum {
    Constructor;
}
```

**Comment by Simn** [comment]
Can't fix this without reworking parts of the display code.

**Comment by Gama11** [comment]
This is actually still an issue with reworked completion. Vshaxe shows the "property" icon rather than the "enum member" icon:

![](https://i.imgur.com/nTCshjW.png)

`Constructor` is reported as `"kind": "Member"`, which is odd, since there's an `"EnumField"` kind. Same issue with the enum abstract.

It looks like the `"EnumField"` and `"EnumAbstractField"` kinds are currently only used in toplevel completion, but not field completion. I do wonder if we need those kinds at all, since we could probably just check the `type` for `TEnum` or `TAbstract` with `@:enum` meta.
