### ISSUE TITLE
[display] workspace symbols filter should be case-insensitive

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5624]
These are usually case-insensitive (see IntelliJ, Visual Studio, etc).

Example: searching for `list` outputs this:

![](http://i.imgur.com/crS8Wx5.png)

Searching for `List` this:

![](http://i.imgur.com/BRQGOdi.png)

If the search was case-insensitive, all of those should show up in the same result set no matter the case of the filter.
However, for _sorting_, the case should still be taken into account - if you search for "List", `List`, `ListNode`, etc should rank higher than `list` ("best match").

**Comment by nadako** [comment]
Ideally it should be even smarter than that and support working with camelcase, e.g. `LN => ListNode`, but yeah, it should at least be case-insensitive.

**Comment by Simn** [comment]
If Haxe has to figure out the sorting we'll have to change the JSON again. Right now it groups reports by file which saves a *lot* of characters. A flat, sorted list would require the file information for each entry...

**Comment by nadako** [comment]
Let's do sorting in the language server then?
