### ISSUE TITLE
[display] field completion & inferred field types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5630]
Can I also make a [display] issue? :)

![](http://i.imgur.com/tSB5gTA.png)

**Comment by Simn** [comment]
Only if you paste the code sample too, I'm terrible at copying code from images.

**Comment by nadako** [comment]
Haha, sure :)
```haxe
class Main {
    static var m = new Main();

    static function main() {
        Main.|
    }
}
```

**Comment by nadako** [comment]
oh, that code is actually invalid because I forgot to add a ctor for Main, but it doesn't get to it anyway and returns a monomorph early.

**Comment by Simn** [comment]
This works as expected now.
