### ISSUE TITLE
[display] unresolved import doesn't appear with "new"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5634]
This is an example of unresolved import diagnostics working fine:

```haxe
class Main {
    public static function main() {
        BalancedTree
    }
}
```

![](http://i.imgur.com/EdyzxQ5.png)

However, it seems very fickle. For a very common use case looks like this, diagnostics only replies with `source/Main.hx:4: characters 4-5 : Unexpected }`:

![](http://i.imgur.com/ZLWFAyT.png)

Even with "valid syntax" (apart from the missing import), there is just `"Type not found : BalancedTree"` in the diagnostics response.

![](http://i.imgur.com/3qlpqEV.png)

**Comment by Simn** [comment]
These are separate issues and both are not that easy to deal with. I'll take a look though.
