### ISSUE TITLE
[display] type completion on :

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5642]
This is probably very annoying to implement, but what I often miss is completion for field and argument types, e.g.

```
var a:| // vars, both local and fields
{f:| // short structure notation fields (long is covered by the previous example)
(a:| // typecheck
function(v:| // function arguments
```

Ideally, these should return a filtered version of toplevel completion that only lists available types and packages.

**Comment by Simn** [comment]
I'll have to check that. It's easy to detect this in the parser, but I'm not sure what it should actually parse in that case. We would have to use some internal `complex_type` variant which when loaded provides toplevel completion.

**Comment by Simn** [comment]
Also we would need access to ToplevelCollecter (sic) from typeload.ml. If you figure out that part we can handle the rest. And fix the name while you're at it...

**Comment by Simn** [comment]
Addressed in https://github.com/HaxeFoundation/haxe/commit/ae157326c9bb7461dcac358d8c35d434d0fefb82
