### ISSUE TITLE
Compiler doesn't catch type errors

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5644]
```haxe

// Main.hx
class Main {
  static function main() {
    return Gen.gen(Main, User);
  }
}

extern class Gen {
	public static function gen(type:Dynamic, ?attrs:Dynamic, children:haxe.extern.Rest<Dynamic>):Void;
}

// User.hx (Make sure this is a separate file)
class User extends ThisObviouslyDoesntExist<T> {}
```

Boom! It compiles! (while obviously it should not, as User extends some non-existent class)

Haxe version: 0d5c46f

The following is the js output, may give some insights

```js
// Generated by Haxe 3.3.0 (git build development @ 0d5c46f)
if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	Gen.gen(Main,null,User);
	return;
};
var User = function() { };
Main.main();
})();

```

**Comment by Simn** [comment]
That's funny, I guess the class is never actually built properly when its structure is not accessed. Is this a regression?

**Comment by kevinresol** [comment]
Yes, regression.
Worked on 3.2.1 and 3.3.0-rc1
http://try-haxe.mrcdk.com/#4Adf1

**Comment by Simn** [comment]
That's interesting, I didn't expect it to be a regression from the RC. If anyone finds the time, a bisect would be appreciated, else I'll do it later.

**Comment by kevinresol** [comment]
well it seems ok in latest commit c4825be

**Comment by kevinresol** [comment]
I am not sure why, maybe I built the wrong thing? Or this bug appears randomly?
But it is not working for me again now c4825be, I rebuilt the compiler from source and this is confirmed.

**Comment by Simn** [comment]
Bisected to https://github.com/HaxeFoundation/haxe/commit/47ef5635f2ab

**Comment by Simn** [comment]
This was actually broken in two different places, which is why it was so hard to track down.
