### ISSUE TITLE
[js] `js.Browser` statics

### ISSUE THREAD

**Issue by clemos** [HaxeFoundation/haxe#5657]
I think it would make sense to have `js.Browser.console` resolve to just `console` instead of current `window.console`. Same for `navigator` and `location`.
This would allow `console`, `navigator`, and `location` to work also in (Service)Worker contexts.

Eventually, regarding `console`, I think it would make sense to move it to `js.Lib` because it's usually available in all JS contexts (windows, workers, node, ...).

Regarding `navigator` and `location`, they have not the exact same type in worker contexts, though:
https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope
So maybe it would make even more sense to provide a `js.Worker` class similar to `js.Node`, `js.Browser`, with properly typed `navigator`, `location`, `caches`, etc.

**Comment by markknol** [comment]
Regarding your first question: you could achieve this with import statements already:
```js
import js.Browser.*;
import js.Browser.window;

class Test {
    static function main() {
       console.log(location.href);
       alert(navigator.onLine);
    }
}
```

**Comment by clemos** [comment]
Thanks for the insight, @markknol, though I was aware of that.
My point is, `js.Browser.location` in Haxe generates `window.location` in JS, which makes it impossible to use in a (Service)Worker context where there is unfortunately no `window`. Same for `console` and `navigator`.
That's why I propose for `js.Browser.location` and such to generate either just `location` in JS, or `self.location` so they are suitable for both browser window and (service) worker contexts.

**Comment by nadako** [comment]
we'll have to look into it wrt name clashes (e.g. local var `location`) and IE8 support.

**Comment by Simn** [comment]
@haxiomic Could you check if we can close this?

**Comment by haxiomic** [comment]
yep, this is resolved now (https://github.com/HaxeFoundation/haxe/pull/9167)
