### ISSUE TITLE
[display] import suggestions after extends / implements

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5658]
```haxe
class Main extends BalancedTree {
    public static function main() {}
}
```

Would be cool if diagnostics suggested an import for `haxe.ds.BalancedTree` instead of failing with `source/Main.hx:1: characters 19-31 : Type not found : BalancedTree`.

**Comment by Simn** [comment]
I'm a bit concerned that this would cause a lot of folllow-up errors.

**Comment by Gama11** [comment]
What do you mean?

**Comment by Simn** [comment]
If the type is unresolved we'll have to use something (or nothing) in its place. Whatever we decide to use is probably not compatible with code that appears later, such as a `super()` call. I guess you usually get this error when you start writing a new class though, so it's probably fine.
