### ISSUE TITLE
[display] workspace symbols vs hxargs

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5660]
```
-lib hxargs
-main Main
-js test.js
```

```haxe
import hxargs.Args;

class Main {
    public static function main() {
        Args.generate([]);
    }
}
```

Getting workspace symbols for this fails with `haxe\std/neko/NativeString.hx:24: lines 24-42 : Invalid call`.

However, no issues with the following:

```haxe
class Main {
    public static function main() {
        hxargs.Args.generate([]);
    }
}
```

**Comment by Simn** [comment]
I'm avoiding the forced macro typing in this mode now because it causes too many issues. This might miss out on the occasional macro-only document symbol, but should be much more robust overall.
