### ISSUE TITLE
Haxe ignores environment variables when compiling with the compilation server

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#5662]
There are some environment variables that can influence how e.g. the HXCPP code is compiled. For example, `CXX` defines the C++ compiler to be used; `HXCPP_AR` defines the assembler to be used, and so on. When compiling through the compilation server, all these environment variables are ignored, which leads to an unexpected behaviour

**Comment by Simn** [comment]
Do you mean they are ignored when you change their values or they are ignored in general?
