### ISSUE TITLE
[display] @position doesn't work in meta argument fields

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5663]
#5635 now works nicely, but only for types, not fields within them:

```haxe
class Main {
	@:access(haxe.io.Path.unescape)
	public static function main() {}
}
```

F12 on `unescape` doesn't work (empty response).

Hover also returns a monomoprh:

![](http://i.imgur.com/qMkhs8h.png)

**Comment by nadako** [comment]
how does it work with types? is there a special handling of @:access/@:allow to know that those exprs are actually a type path?

**Comment by Simn** [comment]
It's a normal expression so we can attempt to type them if the display position happens to be there.
