### ISSUE TITLE
cppia vs. OpAssignOp evaluation order

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5670]
```haxe
private class C {
	public var hash:Array<Int>;
	public function new() {
		hash = [1, 2, 3];
	}

	public function add(x) {
		hash[0] = x;
		return x;
	}
}

class Main {
	@:analyzer(ignore)
	static public function main() {
		var c = new C();
		c.hash[0] += c.add(4);
		trace(c.hash[0]); // 8, should be 5
	}
}
```

As you can see this requires `@:analyzer(ignore)` because I dodged the problem in https://github.com/HaxeFoundation/haxe/commit/cbd3c0b9bafa478debb2a8ec4ef2a3d08659db3b. This also means it's not terribly important, but you might still want to get this right.

What _should_ happen in a `+=` case is this:

1. read the left side
2. evaluate the right side
3. assign to the left side

As such, `a += b` is exactly the same as `a = a + b`. It looks like cppia does not read the initial left side value and instead reads it only after it has been modified by the right side.

**Comment by hughsando** [comment]
And I thought I was being clever.
