### ISSUE TITLE
Crazy macro vs. compilation server issue

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5676]
```haxe
// Main.hx
class Main {
	static public function main() { }
}
```

```
// Define.hx
class Define {
	static public function run() {
		haxe.macro.PositionTools.here();
	}
}
```

```
# build.hxml
-cp src
-main Main
--connect 6000
--macro exclude('whatever')
--macro Define.run()
```

Compiling this twice on a compilation server results in this error:

```
C:\GitHub\haxe\std/haxe/macro/Compiler.hx:212: lines 212-226 : Invalid field access : __a
```

I have investigated this a bit and it looks like something is seriously fucked up in the macro context. Even calling `trace("foo")` fails with an `Invalid call` exception that is positioned at `<header>`, which comes from genneko.ml.

The order of the two `--macro` arguments is important and swapping them works just fine. The nature of `PositionTools.here` seems to be irrelevant, any macro-in-macro call will reproduce this.

Co-assigning @ncannasse here in hopes that he immediately spots what's wrong and has a quick one-line fix, as I am currently totally clueless.

**Comment by Simn** [comment]
Turns out this is not actually about macro-in-macro at all: The presence of that merely avoided the caching and the issue can instead be reproduced by changing Define.hx after the first compilation.

That's both good and scary because it's turning into a really trivial scenario.

**Comment by Simn** [comment]
Here's a debug diff from first to second compilation:

```diff
   0: call_init_macro exclude('whatever')
   0:   call_macro haxe.macro.Compiler.exclude("whatever")
   0:     load_macro haxe.macro.Compiler.exclude
 0,1:       create_macro_interp
-0,1:         init_macro_interp
-0,1:           flush_macro_context
 0,1:       flush_macro_context
   0: call_init_macro Defines.run()
   0:   call_macro Defines.run()
   0:     load_macro Defines.run
 0,1:       flush_macro_context
+0,1:         init_macro_interp
+0,1:           flush_macro_context
   0: on_generate
```

The two red ones come from `create_macro_interp` finding a `macro_interp_cache`, so it doesn't have to create one again.

The green ones are interesting because this hits the section marked as `(* if one of the type we are using has been modified, we need to create a new macro context from scratch *)`. I'm staring at this thinking that this seems to completely discard the current interpreter context along with all its types. Indeed, the original problem goes away if I comment out `Typer.macro_enable_cache := true` in server.ml.

Really need your help here @ncannasse.

**Comment by Simn** [comment]
More debug, this time with IDs on the interpreter context:

```
Created 1
Selected 1
Selected 1
Evaluating on_generate in 1
Next compilation
Selected 1
Created 2
Selected 2
Evaluating on_generate in 1
```

That can't be good, but it's probably not the only issue here.

**Comment by Simn** [comment]
So I wouldn't exactly say what I'm doing, but I consider this addressed by https://github.com/HaxeFoundation/haxe/commit/9ad781c71f37fae61a50b594c48397ab345e876c. It occurred to me that having multiple interpreter contexts around is really not a good idea. Any `let ctx = get_ctx()` could bind the current context and potentially capture it, which is indeed what happened in the `on_generate` case. This would lead to an all around messed up state.

So instead we're now clearing the existing context, preparing it for another round of `add_types`. I confirmed with @nadako and @Gama11 that this fixed usage of the completion server in their previously broken codebases.

**Comment by ncannasse** [comment]
In which case the previous macro context was actually captured in the broken codebases ? if `on_generate` is the only cultprit, maybe addressing it is a better solution ?

**Comment by Simn** [comment]
I'm not sure, but changing that alone didn't fix all the issues I was having. I don't see why we should have to create a new instance of the interpreter context when it's enough to reset the neko context and re-generate the static inits again.

**Comment by ncannasse** [comment]
This is not a very "functional" approach. Both should be equivalent unless you have pending references to the previous context which I think could do extra trouble if it try to access the (now empty) context without all the necessary classes being there

**Comment by Simn** [comment]
Are you sure you want to talk about functional approaches on a record that has like 25 mutable fields?

How would we address the context capturing anyway? We could do `get_ctx()` again within closures, but that's just gonna give us the currently selected (i.e. newest) context, which is no different state-wise than what we have now.

**Comment by ncannasse** [comment]
Well, it depends what get_ctx() does, we could maintain at some point a per signature macro context, but let's say we will deal with it at this time for now

**Comment by ncannasse** [comment]
The fact that we run on_generate within the macro context 1 while we have switched to context 2 is not really a problem - in theory - since we have guarantees from our cache that it's actually the same neko code. I'll investigate if this creates some specific problems with on_generate implementation.

**Comment by ncannasse** [comment]
That was not that hard to find actually, there was some problems when calling something in context 1 while context 2 was selected

**Comment by Simn** [comment]
I still don't think this is right. All future `on_generate` callbacks are gonna be typed in context 1, so if any state changes in the modern macro context that change is not seen in the old context. Or am I just misunderstanding what e.g. `context.globals` is?

**Comment by ncannasse** [comment]
@Simn macros should NOT rely on static data, because they might be reset in the middle of compilation or even have two different versions of them (in this case when we have two macros context). However because we have used already context 1 it means that the code that contains the onGenerate callback is exactly the same as it is in context 2 so it should provide the same result since both are referencing the same typer context.

In case we really want "per compilation static data" then this will require a specific macro API to read/write such data which will be stored in the typer context instead of the macro one.

**Comment by Simn** [comment]
> macros should NOT rely on static data, because they might be reset in the middle of compilation

Wait, what? Are we talking single-compilation here?

**Comment by ncannasse** [comment]
Yes

**Comment by ncannasse** [comment]
In macro context, static variables:
a) can be kept in the state they were in the previous compilation (reusing macro context)
b) can be reset the their default value during compilation (discarding + creating a new macro context)
