### ISSUE TITLE
[display] inside the abstract

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#5684]
```haxe
abstract Test(Int) {
	public function hi(){
		this.|
	}
}
```
![is](https://cloud.githubusercontent.com/assets/6825113/18613524/7a2b0f5e-7daf-11e6-93ad-937e69876a42.png)

**Comment by Gama11** [comment]
I'm confused.. That screenshot show FlashDevelop / HaxeDevelop, yet I cannot reproduce this issue there, only in vscode...

**Comment by R32** [comment]
```haxe
abstract Test(Int) { public function hi(){ this.
}}
```
`haxe --display Test.hx@49`.  in addition to 49,   25~50 The same can

**Comment by Simn** [comment]
Thanks, I expected some problems like that with the new position-based system.

**Comment by R32** [comment]
I found that if you add a `@:dce`, the problem will happen again

```haxe
@:dce abstract Test(Int) { public function hi(){ this.
}}
```
