### ISSUE TITLE
Switch doesn't report incorrect enum constructor name

### ISSUE THREAD

**Issue by KeyMaster-** [HaxeFoundation/haxe#5685]
I noticed some strange behaviour with switches over an enum instance when using a non-existent enum constructor name.

Here's a try.haxe to demonstrate a simple case: http://try-haxe.mrcdk.com/#1bf85

In the first case of the switch, the not_real seems to act as a capture variable, as demonstrated by the print output, and causes all following cases to be ignored.
In the 3.3 rc this compiles without error, in 3.2.1 the second case gets reported as an unused pattern.

I was wondering if this behaviour is intended, as it can cause problems easily when you mistype a constructor name. I really expected an error in this case.

**Comment by Simn** [comment]
On latest Haxe it reports the second case as unused, which is exactly what I expect it to report. Is that what this is about?

**Comment by KeyMaster-** [comment]
Ah okay, I didn't test this on the newest haxe. What I was wondering if instead it should warn me that the given pattern is not an enum constructor, but I suppose it's working as intended.
Out of interest, what's the purpose of just capturing the switch variable as is? I don't really see a use, since that value is available in the switch as the variable that was passed in anyway?

**Comment by Simn** [comment]
```haxe
switch (calculateMe()) {
    case MatchMe:
    case captureMe: useMe(captureMe);
}
```
