### ISSUE TITLE
[display] first macro is reported as more expensive with -D macro-times

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5686]
Enabling `--times` and `-D macro-times` in a Flixel project, I got the following results:

![](http://i.imgur.com/sJ4XeNG.png)

There are two initlization macros, `--macro keep('IntIterator')` and `--macro flixel.system.macros.FlxDefines.run()`. The rest are build macros.

The naive (and apparently incorrect assumption) would be that `--macro keep` is crazy expensive for some reason, even though it doesn't do very much. However, This is what happens with `--macro keep` commented out:

![](http://i.imgur.com/SscTrcS.png)

Now `FlxDefines` is suddenly the expensive one... In fact, just _swapping_ the two init macros (so that `FlxDefines` is run before `keep`) leads to almost the same result - so it appears that the first init macro that is run takes a lot longer, maybe because of some initialization logic that has to happen there, but not subsequent ones. Either way, this is misleading.

**Comment by Gama11** [comment]
This is actually not limited to init macros, commenting out both of them, the first build macro suddenly becomes the expensive one.

**Comment by Simn** [comment]
The main problem is the `finalize` call which basically does all the remaining typing. The other one is `flush_macro_context` which should have its own timer anyway.

**Comment by ncannasse** [comment]
We should remove the `(+init)` and only account for the macro execution, without the typing involved

**Comment by Simn** [comment]
Addressed in https://github.com/HaxeFoundation/haxe/commit/4300270b0a6b62cf0dbbcec2315eaf7385898fc2
