### ISSUE TITLE
[lua] BytesOutput.writeDouble issue

### ISSUE THREAD

**Issue by MahiruInami** [HaxeFoundation/haxe#5693]
```
    var original:Float = 0.012755102040816;
    var btOutput:BytesOutput = new BytesOutput();
    btOutput.writeDouble(original);

    var byteArray:Bytes = btOutput.getBytes();

    var btInput:BytesInput = new BytesInput(byteArray);
    var copyVal:Float = btInput.readDouble();

    trace(original);
    trace(copyVal);
```

That code gives me same values(original == copyVal) on neko and java targets.
But on lua target copyVal = 0.012755098999763 for some reason.

**Comment by jdonaldson** [comment]
fixed this, and added a test case for it.

**Comment by Simn** [comment]
The test is failing for me locally:

```
C:\GitHub\haxe\tests\unit\bin>lua -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio

C:\GitHub\haxe\tests\unit\bin>lua unit.lua
TestMain.hx:36: Generated at: 2016-10-12 14:55:51
TestMain.hx:38: START
Issue5693.hx:14: 0.012755102040816 should be 0.012755100672342
Test.hx:220: DONE [6838 tests]
Test.hx:221: SUCCESS: false
```

**Comment by execrable42** [comment]
There is some problem with doubleToI64 function. Here is example:

`var fl_1:Float = 0.012755102040816;
  var i_64:Int64 = haxe.io.FPHelper.doubleToI64(fl_1);
  var fl_2:Float = haxe.io.FPHelper.i64ToDouble(i_64.low, i_64.high);

  trace("Compare : " +  fl_1 + "   " + fl_2);`

Result: "Compare : 0.012755102040816   0.012755098999763"

**Comment by jdonaldson** [comment]
Closing this ... I can't repro.  I'm seeing the same number for both lua 5.2 and luajit.
