### ISSUE TITLE
Make global display modes compilation-server compatible

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5696]
The global display modes modes (statistics, diagnostics, reference finding, toplevel completion) are currently either not compatible with the compilation server or are implemented in a sub-optimal way. Some of them rely on per-context information, which is discarded between compilations and only restored for the modules that are re-typed again.

In order to get this right, the display information has to be added to the module definitions themselves (`m_extra`). This allows them to persist in the cache and be re-used properly. However, we have to be careful not to post-process a cached module, e.g. through `Diagnostics.prepare`. For this we can probably use a similar mechanism like filters.ml is using for its `is_cached`.

The other problem is that we have to obtain a state which is "as global as possible". This is problematic for both server- and normal compilation:
1. In non-server compilation, we are only going to see modules which are reachable using the given compiler arguments. We don't have a lot of options here and the best we can do is browse the class-path for .hx files and load modules. This is going to be slow, to the point where we might want to consider supporting global display modes only when the compilation server is run.
2. In server compilation, cached modules might not make it into the context for various reasons. It is then necessary to re-populate the context from the cache before we do `Typer.generate`. In this case we have to make sure not to duplicate any modules. It should be noted that server compilation also suffers from the problem described in 1. However, on the server, it's feasible to occasionally browse the class paths which can even be done after sending a response to the client.

This is going to require some thought and some work. It should be well worth it though and together with my ideas in #5689 I'm seeing display times improved by an order of magnitude on my current experiments.

My main concern is that we don't really have any good tests for these display modes and that it's a pain to write them, especially considering the compilation server.

**Comment by ncannasse** [comment]
So you're proposing to have the context (and not only the modules) survive between compilation-server queries? And also, potentially half-typed (and sometimes error'ed) modules? It seems quite hard to put in place.

**Comment by Simn** [comment]
That's not what I'm proposing at all. I want to store display information on the modules instead of the context so it persists.

**Comment by ncannasse** [comment]
I'm not sure I understand then. What kind of "display information" is currently being not stored / lost at end of compilation in the modules ?

**Comment by Simn** [comment]
Let's take a global diagnostics run as an example. When run that on an uncached file, the compiler types it and logs all problems with the file in the context. If that file is cached and you make another diagnostics run, it is not re-typed again so there are no problems logged, so they effectively disappear.

The same applies to all the other things I added to the context: https://github.com/HaxeFoundation/haxe/blob/development/src/context/common.ml#L220

**Comment by ncannasse** [comment]
Ah, I see, you're running diagnostics on untyped AST (or while typing), not on final typed AST (in which case there would be no problem).

**Comment by ncannasse** [comment]
Any idea how much time/space that would take to store for every compilation?

**Comment by Simn** [comment]
> Ah, I see, you're running diagnostics on untyped AST (or while typing), not on final typed AST (in which case there would be no problem).

Yes it's while typing, we hook into `display_error` and such to collect errors and warnings that come up. There is also some auxiliary information collected, like `type_hints` so we can make find references pick these up. The typed AST does not have all the information required for some display modes.

> Any idea how much time/space that would take to store for every compilation?

Time is fine, space I'll double-check again but it seemed fine too last I checked.

**Comment by Simn** [comment]
Let's go through the list:

* `import_positions`: This is required to a) detect unused import and b) find type references. Could be addressed by properly storing import/using in the module to begin with, which is something I wanted to discuss anyway (we have some issues with macro-defined types not knowing about imports of the module they are defined into).
* `diagnostics_messages`: We can split these up and only keep the ones that come from typing. That way we don't have to keep the ones we can infer from the typed AST.
* `type_hints`: This I think we need because the information is completely lost in the typed AST.
* `document_symbols`: It occurred to me that I don't have to keep these around. It would potentially save some processing time, but I don't think that would be significant. Document symbols can be inferred from the cache's `c_files`, with the exception being the current display file because that's not cached. We can keep that information on the context though.
* `removable_code`: Can be removed because it's inferred at the end anyway.
* `unresolved_identifiers`: This is a special case of diagnostics messages, has to be kept because it occurs during typing.
* `interface_field_implementations`: This is currently used for reference finding and I have plans to provide some field generation support using this information, so it should stay.
