### ISSUE TITLE
Vector is slower than Array

### ISSUE THREAD

**Issue by PDeveloper** [HaxeFoundation/haxe#5697]
Judging by this gist example:
https://gist.github.com/PDeveloper/6b88834082111f2852198fbdc89148d6

Vector is consistently slower than Array in the second set of functions, and randomly slower in the first set.

Any thoughts/ideas?

**Comment by Simn** [comment]
@hughsando: I can confirm that Vector is slower than Array for this test. Haven't checked it in detail, but the generated code doesn't look like it should make much of a difference.

**Comment by Simn** [comment]
I just tested your example again and get similar results between Array and Vector now.

**Comment by PDeveloper** [comment]
Nice, will try to upgrade everything and start converting to Vector again.
