### ISSUE TITLE
[js] Wrap generated immediately invoked functions in brackets

### ISSUE THREAD

**Issue by Blank101** [HaxeFoundation/haxe#5699]
See https://github.com/nolanlawson/optimize-js for an explanation of why this is useful.

Generated IIF such as those to maintain "this" reference could be wrapped in brackets. For example:

	//Generated now
	(function($this) {
		//Code
	}(this))

	//With function wrapping
	((function($this) {
		//Code
	})(this))

Seems like an easy change that could yield some nice performance benefits.

**Comment by Simn** [comment]
We barely generate these anymore anyway...

**Comment by Blank101** [comment]
Barely generate any IIFs or just for the "this" case?

**Comment by Simn** [comment]
Definitely the "this" case. Not sure about the general case, don't we usually inline this?

**Comment by Blank101** [comment]
Well I'm unfamiliar with other cases, but compiling some sample server code of mine I still see $this coming up every now and then. Taking a quick glance it appears to show up for closures and inlined functions mostly. Compiling with Haxe 3.2.1 with static analyser on btw.

**Comment by Simn** [comment]
> Haxe 3.2.1 

That might be your problem.

**Comment by Blank101** [comment]
Alright will check out the new RC and see how that affects things.

**Comment by Simn** [comment]
I'd grab a nightly from builds.haxe.org instead, there have been some fixes since the RC.

**Comment by Blank101** [comment]
You're right. Compiling with the nightly build gets rid of all the previous IIF code that was occurring before. Seems this change probably won't affect generated code all that much.

**Comment by Simn** [comment]
That's reassuring to hear, thanks for checking!
