### ISSUE TITLE
Unbound variable on haxe 3.3.0

### ISSUE THREAD

**Issue by caiopsouza** [HaxeFoundation/haxe#5701]
The following code gives a compiler error on haxe 3.3.0. On 3.2.1 it compiles without any problems.

``` haxe
package;

class A
{
    public static var instance: A;
    public inline function new() instance = this;
}

class Test
{
    public static function main() var a = new A();
}

```

The error:

```
Unbound variable, please report this
{
        v_id = -504;
        v_name = a;
        v_type = A;
        v_capture = false;
        v_extra = None;
        v_meta = [];
}
While analyzing Test.main
dot graph written to dump/js/Test.main
File "src/optimization/analyzerTypes.ml", line 221, characters 3-9: Assertion failed
```

**Comment by caiopsouza** [comment]
I just notice what is causing it is the `inline`.

**Comment by Simn** [comment]
@ncannasse: Any opinion on this? Seems like usage of `this` as a value in an inline constructor is quite contradictory. It brings the variable we want to inline away right back.

**Comment by ncannasse** [comment]
It should either error when trying to inline or when typing the new() method.

Another possibility is to cancel inline if the `this` survives branch elimination (but I don't think we allow complex new inline such as the following):

```haxe
inline function new( store = false ) {
    if( store ) instance = this;
}
...
new A(); // can inline
new A(true); // don't inline 
```

**Comment by Simn** [comment]
This has been fixed by https://github.com/HaxeFoundation/haxe/commit/1ab45f49919d167b1de4abedbc04bbe13bd132d5
