### ISSUE TITLE
Static variable initialization

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5702]
I'm still getting what I think is a wrong AST when initializing static variables, such as #5358 is showing:

```
	static var example:Int = [If:Void]
		[Parenthesis:Bool]
			[Binop:Bool]
				[Call:Int]
					[Field:Void -> Int]
						[TypeExpr unit.issues.Issue5358:Class<unit.issues.Issue5358>]
						[FStatic:Void -> Int]
							unit.issues.Issue5358
							veryRandom
				>
				[Const:Float] 0.5
		[Then:Int] [Const:Int] 1
		[Else:Int] [Const:Int] 2;
```

I think that we should have `[If:Int]` here, as we would if we were assigning `example = expr` somewhere else.

**Comment by Simn** [comment]
Best I can offer right now is self-calling closures by adding HL to the guard here: https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/analyzer.ml#L1167

For anything prettier you'll have to talk to my future self who hopefully has a better understanding of how assignments without assignment targets are supposed to be post-processed.

**Comment by ncannasse** [comment]
Works for me
