### ISSUE TITLE
Error:Could not found the target "by"    

### ISSUE THREAD

**Issue by hpgood** [HaxeFoundation/haxe#5703]
using haxe 3.3.0
openfl build ios -Dv2 -x -v

Error:Could not found the target "by"

and i found the error in Options.txt
....
source-header=Generated by Haxe 3.3.0
...

src/context/common.ml   L714
   PMap.add "source-header" ("Generated by Haxe " ^ s_version) (
should be
  PMap.add "source-header" ("Generated_by_Haxe_" ^ s_version) (

can not has the space in the middle!

**Comment by Simn** [comment]
That sounds more like an issue with the gencpp Options.txt handling. I'd expect it to be reproducible with something like `-D "with spaces" as well.

**Comment by hughsando** [comment]
I have a feeling this might be a haxelib quoting error.
Can you upgrade the haxelib version?

**Comment by ibilon** [comment]
I actually also get this on a hello world, and I'm using dev haxelib.

It doesn't happen with haxe 3.2.1, if this is coming from haxelib maybe it wasn't updated for the 3.3 changes in command escaping?

**Comment by hpgood** [comment]
run fine in  3.2.1,but run error  in 3.3.
I guess add one line:
<haxeflag name="-source-header haxe_3_3_0" />
to the project.xml ,should pass the bug.

**Comment by hughsando** [comment]
I think this is a versioning issue that has been solved now.
