### ISSUE TITLE
Type parameters do not unify

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5706]
This was originally reported as https://github.com/ciscoheat/buddy/issues/60
and now gets posted here since it seems to be a regression of the compiler itself.

**Comment by kevinresol** [comment]
btw, I think I encountered a use case that buddy is not involved. I will try to reduce it.

By the way I have

**Comment by kevinresol** [comment]
very similiar to https://github.com/HaxeFoundation/haxe/issues/9058

**Comment by RealyUniqueName** [comment]
Can you check if it's fixed with the latest Haxe?

**Comment by kevinresol** [comment]
#9058 is fixed by [you](https://github.com/HaxeFoundation/haxe/issues/9058#issuecomment-570786918) already

As for this one, let's close it as there was no repro code snippet
