### ISSUE TITLE
AST difference with @:generic

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5713]
Two bugs with the following example:

``` haxe
class Foo {
    public function new() {
    }
    public function foo() {
    }
}

@:generic
class A<T:Foo> extends T {
    public override function foo() {
        super.foo();
    }
}

class B extends Foo {
    public override function foo() {
        super.foo();
    }
}

class Main {

    static function main() {
        var a = new A<Foo>();
        a.foo();
    }

}
```

a) The `super` in A_Foo is still typed as `A.T` instead of `Foo` (not like in `B`)
b) removing the `public` before `override` does not correctly inherit visibility

**Comment by ncannasse** [comment]
PS: this makes HL output crash

**Comment by Simn** [comment]
I think we should remove or at least deprecate support for extending type parameters. It's an annoying special case which doesn't really have much practical usage.
