### ISSUE TITLE
No way to distuingish RCs from stable releases

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5719]
`haxe_ver` for 3.3.0-rc.1 is just `3.3.0`, and `haxe -version` only outputs `3.3.0` as well, so for all intents and purposes, it looks like a stable release.
This is problematic, because that means there's no way to distuingish it from the real release (for instance during support when trying to figure out what Haxe version somebody is running - "Are you using the RC or not? It had some bug that was fixed in the stable release.").

**Comment by Simn** [comment]
I'll probably fix this by not having any more RCs, which has the added benefit that people stop crying about the RCs being the default on haxe.org/download.

**Comment by Simn** [comment]
This is important to address.

**Comment by back2dos** [comment]
> "Are you using the RC or not? It had some bug that was fixed in the stable release."

Sounds like another reason to use lix ;)

**Comment by ncannasse** [comment]
RC should be displayed in command line, not sure if it should be testable with #if haxe_ver

**Comment by Gama11** [comment]
You could theoretically write an init macro that parses `haxe --version` output and adds some define based on it - there might be a risk of people creating hacks like that if they need to check for preview releases in a define.

**Comment by back2dos** [comment]
It'd be great to have a define that's holds the time stamp of when the commit was made that the compiler was built from. Assuming that development stays relatively linear, one could rely on it like so:

```haxe
#if (haxe_buildtime >= $timeStampOfWhenThatAwesomeNewThingWasAdded && haxe_ver >= 4)
  Context.doThatAwesomeNewThing();
#else
  doMyWeirdQuirkyWorkaround();
#end
```

It would help, because right now `haxe_ver >= 4` on its own doesn't mean much. And even once things stabilize again, it wouldn't hurt to have a way to use new features from nightlies without breaking things for people who stick with the latest official release.

**Comment by Gama11** [comment]
I'm not sure if that's a good idea or not, but one thing to note is that it would make Git a hard dependency for building Haxe (right now it only is with `ADD_REVISION=1`).

**Comment by Gama11** [comment]
You could always download a `.zip` from GitHub instead of cloning the repo with its history. But yeah, probably not a big concern, and you could still have an inverted version of that flag to _disable_ Git date checks.

**Comment by andyli** [comment]
I believe the point of RCs is that they are meant to become releases. i.e. The final RC would be exactly the same as the upcoming release.

Having a way to distinguish RCs from release, in haxe code, would invalidate the point of having RCs. e.g. If there were  a `rc` define, and a piece of code:
```haxe
#if rc
//do something
#else
//do other thing
#end
```
There would be no way to test whether the code above is haxe-next ready until trying it out with the actual haxe-next release.

Moreover, I want to point out what we have right now are haxe 4 "previews", which are not even alpha/beta/rc. Users and library authors should not try too hard to support all these non-releases but focus on the actual releases.

To conclude, I support printing out preview/alpha/beta/rc in command line, but please don't add a define.
