### ISSUE TITLE
[display] metadata completion in functions

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5720]
There's metadata completion (as part of field completion) on type and field level, but it doesn't work within functions right now (just responds with `Unexpected }`).

```haxe
class Main {
	public static function main() { @| }
}
```

**Comment by Simn** [comment]
closed by https://github.com/HaxeFoundation/haxe/commit/a2a6439c2489fab90bcbdfe8cc27d2c6071fb194 (wrong issue number)
