### ISSUE TITLE
Cpp socket error 

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#5721]
I have a very simple socket program and I tried to compile to cpp.  The program is :
         var socket:Socket = new Socket();
          socket.setFastSend(true);
          var port = 4028;
          socket.bind(new sys.net.Host(Host.localhost()), port);
          socket.listen(10);
          socket.setBlocking(false);
          while( true ) {
            var client : Socket = socket.accept();
            client.close();
          }

The error which I received is :

Called from hxcpp::__hxcpp_main
Called from Main::main Main.hx line 23
Called from sys.net.Socket::accept /usr/lib/haxe/std/cpp/_std/sys/net/Socket.hx line 182
Error : Blocking

Line 23 is : var client : Socket = socket.accept();

**Comment by Simn** [comment]
See http://api.haxe.org/sys/net/Socket.html#setBlocking, `accept` is a blocking operation and your socket is set to be non-blocking.
