### ISSUE TITLE
JavaScript target not fully closure compiler compatible anymore

### ISSUE THREAD

**Issue by derRaab** [HaxeFoundation/haxe#5724]
I did it. I Upgraded to the latest Haxe version (haxe-3.3.0-rc1-dev-3df5463.pkg) and started porting our existing projects to 3.3.0.

But I found out that the the new JavaScript output is not fully Google Closure Compiler compatible anymore. I use a lot of reflection to access properties within a loaded JSON object. This works as expected without using closure compiler - but fails IN SOME CASES after beaten up by closure compiler.

This is how to reproduce:

Use this haxe code
```
package ;

import js.Browser;
import haxe.Json;

class ApplicationJsMain {

	static function main() {

		_testClosureCompilerSupport();
	}

	public function new()
	{
	}

	static function _createDynamic() : Dynamic {

		var json : String = '{"key":"value","key2":"value2"}';
		return Json.parse( json );
	}

	static function _testClosureCompilerSupport() : Void {

		Browser.console.log( "_testClosureCompilerSupport()" );

		var o : Dynamic = _createDynamic();
		Browser.console.log( "Dynamic object:", o );

		_testReflectionA( o );
		_testReflectionB( o );
	}

	static function _testReflectionA( o : Dynamic ) : Void {

		Browser.console.log( "_testReflectionA()" );
		var value = Reflect.getProperty( o, "key" );
		var value2 = Reflect.getProperty( o, "key2" );
		Browser.console.log( "value:", value );
		Browser.console.log( "value2:", value2 );
	}

	static function _testReflectionB( o : Dynamic ) : Void {

		Browser.console.log( "_testReflectionB()" );
		var key : String = "key";
		var key2 : String = "key2";
		var value = Reflect.getProperty( o, key );
		var value2 = Reflect.getProperty( o, key2 );
		Browser.console.log( "value:", value );
		Browser.console.log( "value2:", value2 );
	}
}
```

Compile this code using these hxml flags

```
-D js_flatten
-dce full
```

Look at this correct working output:

```
// Generated by Haxe 3.3.0 (git build development @ 3df5463)
(function () { "use strict";
var ApplicationJsMain = function() { };
ApplicationJsMain.main = function() {
	ApplicationJsMain._testClosureCompilerSupport();
};
ApplicationJsMain._createDynamic = function() {
	return JSON.parse("{\"key\":\"value\",\"key2\":\"value2\"}");
};
ApplicationJsMain._testClosureCompilerSupport = function() {
	window.console.log("_testClosureCompilerSupport()");
	var o = ApplicationJsMain._createDynamic();
	window.console.log("Dynamic object:",o);
	ApplicationJsMain._testReflectionA(o);
	ApplicationJsMain._testReflectionB(o);
};
ApplicationJsMain._testReflectionA = function(o) {
	window.console.log("_testReflectionA()");
	var tmp;
	var tmp1;
	if(o == null) {
		tmp1 = null;
	} else {
		var tmp2;
		if(o.__properties__) {
			tmp = o.__properties__["get_" + "key"];
			tmp2 = tmp;
		} else {
			tmp2 = false;
		}
		if(tmp2) {
			tmp1 = o[tmp]();
		} else {
			tmp1 = o.key;
		}
	}
	var value = tmp1;
	var tmp3;
	var tmp4;
	if(o == null) {
		tmp4 = null;
	} else {
		var tmp5;
		if(o.__properties__) {
			tmp3 = o.__properties__["get_" + "key2"];
			tmp5 = tmp3;
		} else {
			tmp5 = false;
		}
		if(tmp5) {
			tmp4 = o[tmp3]();
		} else {
			tmp4 = o.key2;
		}
	}
	var value2 = tmp4;
	window.console.log("value:",value);
	window.console.log("value2:",value2);
};
ApplicationJsMain._testReflectionB = function(o) {
	window.console.log("_testReflectionB()");
	var key = "key";
	var key2 = "key2";
	var tmp;
	var tmp1;
	if(o == null) {
		tmp1 = null;
	} else {
		var tmp2;
		if(o.__properties__) {
			tmp = o.__properties__["get_" + key];
			tmp2 = tmp;
		} else {
			tmp2 = false;
		}
		if(tmp2) {
			tmp1 = o[tmp]();
		} else {
			tmp1 = o[key];
		}
	}
	var value = tmp1;
	var tmp3;
	var tmp4;
	if(o == null) {
		tmp4 = null;
	} else {
		var tmp5;
		if(o.__properties__) {
			tmp3 = o.__properties__["get_" + key2];
			tmp5 = tmp3;
		} else {
			tmp5 = false;
		}
		if(tmp5) {
			tmp4 = o[tmp3]();
		} else {
			tmp4 = o[key2];
		}
	}
	var value2 = tmp4;
	window.console.log("value:",value);
	window.console.log("value2:",value2);
};
ApplicationJsMain.main();
})();
```
Use the latest closure compiler with

`--compilation_level ADVANCED_OPTIMIZATIONS`

Which gives you this code (prettified)

```
(function() {
    function b() {}
    b.h = function() { b.c() };
    b.b = function() {
        return JSON.parse('{"key":"value","key2":"value2"}') };
    b.c = function() { window.console.log("_testClosureCompilerSupport()");
        var a = b.b();
        window.console.log("Dynamic object:", a);
        b.f(a);
        b.g(a) };
    b.f = function(a) {
        window.console.log("_testReflectionA()");
        var d;
        if (null == a) d = null;
        else {
            var c;
            c = a.a ? d = a.a.get_key : !1;
            d = c ? a[d]() : a.key }
        var b;
        null == a ? a = null : (c = a.a ? b = a.a.get_key2 : !1, a = c ? a[b]() : a.i);
        window.console.log("value:", d);
        window.console.log("value2:",
            a)
    };
    b.g = function(a) { window.console.log("_testReflectionB()");
        var b;
        if (null == a) b = null;
        else {
            var c;
            c = a.a ? b = a.a.get_key : !1;
            b = c ? a[b]() : a.key }
        var e;
        null == a ? a = null : (c = a.a ? e = a.a.get_key2 : !1, a = c ? a[e]() : a.key2);
        window.console.log("value:", b);
        window.console.log("value2:", a) };
    b.h()
})();
```
Which gives us this output in the browser console:

```
_testClosureCompilerSupport()
Dynamic object: – {key: "value", key2: "value2"}
_testReflectionA()
value: – "value"
value2: – undefined
_testReflectionB()
value: – "value"
value2: – "value2"
```

**Value2 in test A is undefined** (which is not the case). I looked at it quite some time and don't really get it. But I think a macro does something wrong.

**Comment by Simn** [comment]
I don't get it either, the code we generate looks sane to me, or at least as sane as anything using `Reflect.getProperty` can look.

**Comment by frabbit** [comment]
this is not related to 3.3.

```haxe
class Test {
    static function main() {
        var a:Dynamic = haxe.Json.parse("{ 'foo' : 1 }");  
        trace(a.foo);
    }
}
```

which generates the following js code:

```js
(function (console) { "use strict";
var Test = function() { };
Test.main = function() {
	var a = JSON.parse("{ 'foo' : 1 }");
	console.log(a.foo);
};
Test.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

and also fails with advanced optimization.

**Comment by derRaab** [comment]
@frabbit I think your example will of course fail because you don't use reflection at all. :) I compiled the above code again with 3.2.1 and everything is fine again.

@Simn It might have something to do with the inlined reflect method. See this 3.2.1 compiled version:

```js
(function (console) { "use strict";
var ApplicationJsMain = function() { };
ApplicationJsMain.main = function() {
    ApplicationJsMain._testClosureCompilerSupport();
};
ApplicationJsMain._createDynamic = function() {
    var json = "{\"key\":\"value\",\"key2\":\"value2\"}";
    return JSON.parse(json);
};
ApplicationJsMain._testClosureCompilerSupport = function() {
    window.console.log("_testClosureCompilerSupport()");
    var o = ApplicationJsMain._createDynamic();
    window.console.log("Dynamic object:",o);
    ApplicationJsMain._testReflectionA(o);
    ApplicationJsMain._testReflectionB(o);
};
ApplicationJsMain._testReflectionA = function(o) {
    window.console.log("_testReflectionA()");
    var value = Reflect.getProperty(o,"key");
    var value2 = Reflect.getProperty(o,"key2");
    window.console.log("value:",value);
    window.console.log("value2:",value2);
};
ApplicationJsMain._testReflectionB = function(o) {
    window.console.log("_testReflectionB()");
    var key = "key";
    var key2 = "key2";
    var value = Reflect.getProperty(o,key);
    var value2 = Reflect.getProperty(o,key2);
    window.console.log("value:",value);
    window.console.log("value2:",value2);
};
var Reflect = function() { };
Reflect.getProperty = function(o,field) {
    var tmp;
    if(o == null) return null; else if(o.__properties__ && (tmp = o.__properties__["get_" + field])) return o[tmp](); else return o[field];
};
ApplicationJsMain.main();
})(typeof console != "undefined" ? console : {log:function(){}});
```

Which compiles closure to 

```js
(function() {
    function c() {}

    function b() {}
    b.i = function() { b.f() };
    b.c = function() {
        return JSON.parse('{"key":"value","key2":"value2"}') };
    b.f = function() { window.console.log("_testClosureCompilerSupport()");
        var a = b.c();
        window.console.log("Dynamic object:", a);
        b.g(a);
        b.h(a) };
    b.g = function(a) { window.console.log("_testReflectionA()");
        var b = c.a(a, "key");
        a = c.a(a, "key2");
        window.console.log("value:", b);
        window.console.log("value2:", a) };
    b.h = function(a) {
        window.console.log("_testReflectionB()");
        var b = c.a(a, "key");
        a = c.a(a,
            "key2");
        window.console.log("value:", b);
        window.console.log("value2:", a)
    };
    c.a = function(a, b) {
        var c;
        return null == a ? null : a.b && (c = a.b["get_" + b]) ? a[c]() : a[b] };
    b.i()
})("undefined" != typeof console ? console : { log: function() {} });
```

And this works just fine.

**Comment by Simn** [comment]
That's probably it, so the problem is that our inlining got better...

**Comment by Simn** [comment]
If Reflect.getProperty was indeed not inlined in 3.2 then the "fix" might be to remove the `inline` from it. It's still a quite silly situation, but I don't see what we could do if the closure compiler acts like that.

I'm not even sure this should be considered a regression, as far as I'm aware we make no promise to generate advanced closure-compliant code. However, I understand that this might hinder 3.3 adoption in practice...

**Comment by derRaab** [comment]
I think I understood it (and hopefully can explain it):

Inlining the Reflect methods in JavaScript seems to be a bad idea regarding closure compiler. That is, because the closure compiler does not only remove whitespace and stuff, but also analyses the whole JavaScript tree and then changes variable-, field- and methodnames throughout the whole JavaScript file. So if you set or access a field using dot syntax or execute methods using dot syntax this might end up being changed everywhere to very short versions of the code you wrote - but still works since it will be changed everywhere. So

```js
var myObject = {};
myObject.myField = "myString";
var result = myMethod( myObject.myField );
```

might be converted to

```js
var a = {};
a.a = "myString";
var r = m(a.a);
```

The result is very short and that's the whole point about it - of course closure compiler also removes even more code fragments like unnecessary semicolons and a lot more.

But now let's say we load our object as external JSON file

`{ "myField":"myString"}`

So here the key "myField" is still "myField" and has not changed to "a" - therefore the code will break since the closure compiled JavaScript is looking for value accessible through key "a", not "myField".

To avoid this effect in JavaScript you simply would use

```js
var a = JSON object loaded from somewhere;
var r = m(a["myField"]);
```

and can still access the field value, since closure compiler will not change the string used in the "array accessor".

Since it's not possible to write

`var r = a["myString"];`

in Haxe we need to use the Reflect API like this

`var result = myMethod( Reflect.getProperty( myObject, "myField" ) );`

which in Haxe 3.2.1 was not inlined and therefore worked fine.

If you look at https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/Reflect.hx it  seems the code itself would work inlined as well - BUT - it looks like Haxe compiler is very, very smart, so since it knows what value "field" has - it doesn't use

`o[field]`

anymore but rather changes the code to

`o.myField`

again.

And this plain field access then will be renamed by closure compiler. So now I use the Reflect API to avoid this effect but since the compiler inlines everything and optimizes the hell out of it, this will actually break again after closure compiling.

You can see the effect in the compiled Haxe code above. Version A (not working) has this line

`tmp4 = o.key2;`

but Version B has this line (because it uses a variable instead of a string while calling Reflect.getProperty())

`tmp4 = o[key2];`

So there are two possible ways to fix this:
1. Avoid inlining all (since this effect applies to more) Reflect methods for JavaScript target
2. Stop optimizing the hell out of Haxe code

I think number 2 is no option - so if possible avoid inlining on JavaScript target only. And I think this is more than urgent since for example all OpenFl release builds are compiled using closure compiler and I think closure compiler is industry standard. Not supporting it is not an option.

Since I don't know how to avoid inlining on only a specific target I hope you guys can make these changes soon? Otherwise I'd create a pull request just removing "inline" on a couple of methods in this class: https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/Reflect.hx

**Comment by Simn** [comment]
I'd be fine with removing the `inline` on `getProperty` and `setProperty` because I'm pretty sure the `var tmp` was preventing these from being inlined on 3.2 anyway. What I'm still not sure about is `field` and `setField` because these look like they would be inlined even on 3.2. That makes me wonder if the problem reproduces on 3.2 and if you were just lucky to not come across it.

Another option would be to let the Haxe compiler collect all known fields and generate `o.field` only for these, `o["field"]` otherwise. Do you think that would help?

**Comment by derRaab** [comment]
I remember having problems using `field` and `setField` and I think that's why I switched to `set/getProperty`! I had a quick look at the GIT history and to my understanding I would love to see these changes:

Do not inline the methods `field`, `setField`, `setProperty`, `getProperty` for the JavaScript target.

This will avoid all problems with closure compiler because it will truly separate the access to unknown fields and properties. I don't know about obfuscating tools for other platforms, but they might break access to dynamic fields as well?

And since I now know the actual implementation - I'll switch to field and setField methods afterwards - seems to be faster.

What do you think?

**Comment by back2dos** [comment]
I don't think that's such a good idea. Reflection is quirky to start with
and obfuscation often breaks it (not just in Haxe, mind you). Since giving
the guarantees you seek yields less optimized code, I don't think it's a
good default.

At the same time, if inlining is the only problem, it should be trivial for
you to have your own reflection class and that gives you the behavior you
wish for where you want it. If you want to use it globally, you can put
`import der.raab.ClosureResilientReflection as Reflect` into an `import.hx`
in your project root and everything will work as before.

**Comment by derRaab** [comment]
Well I could do that - but since closure compiler is kind of an industry standard (don't you agree?) and some projects (e.g. OpenFl) rely on using closure compiler in advanced mode anyway I think it is a must have to support it - and reflection is the only area where we need to worry about it.

Reflection should be used only if necessary anyway - will say for accessing fields of unknown (loaded) structures only. It is fine to use inlining when it's done in a way closure compiler won't break anything. :)

I'm not into macros (but you are @back2dos ) - so the only thing necessary seems to use "array access" with keys as an variable holding the actual key as a string or just inject the string as key:

`var result = Reflect.field( object, "key" );`

will work fine if translated to
```
var result = object[ "key" ];
```
or
```
var key = "key";
var result = object[ key ]
```
but break if resolved to 
```
var result = object.key;
```

Please - just avoid dot syntax for unknown fields and everything is just fine. :)

In the meantime I'll just use this kind of syntax:

```
var key = "key";
var result = Reflect.field( object, key );
```

And closure compiler will be supported - but I think that is something we need to have out of the box.

**Comment by Simn** [comment]
> ```
> var key = "key";
> var result = Reflect.field( object, key );
> ```

Careful with that, Haxe might still optimize your `key` variable away via constant propagation or the fusion optimization. If you notice things breaking between debug/release compilations, it's probably that. In which case you might want to use `-D analyzer-no-const-propagation` and `-D analyzer-no-user-var-fusion`.

**Comment by derRaab** [comment]
Ok - so what is the best way to avoid dot syntax in code generated from the Reflect class in JavaScript target? That's all we need in this particular class. :D This is way to deep for me. ;)

**Comment by Simn** [comment]
I have disabled this optimization for now and will probably keep it that way unless somebody shows that this actually has any measurable effect. I agree that it's more important to be closure-compliant, and if this is indeed the only problem with that (to be verified) it's not worth the hassle.

**Comment by derRaab** [comment]
Just to understand that: Your changes only apply to the Reflect class in JavaScript - yes? And it will be available in the next development release (tonight)? I'd love to double check if this fixes all issues in my projects. :)

**Comment by Simn** [comment]
It applies to any `object["field"]` code, and it will be available as soon as the build server decides to build (there might be an issue with that right now, will check).

**Comment by frabbit** [comment]
it seems that only safari is slower when using bracket instead of dot access: http://stackoverflow.com/a/30975165

**Comment by derRaab** [comment]
I think that's fine because usually you don't need to use reflection at all and if needed - we need bracket access anyway.

But again - does this also apply to other targets? No? (I'm just trying to understand...)

**Comment by Simn** [comment]
This is only about JavaScript.

**Comment by derRaab** [comment]
Ok - thanks! So I hope everybody is happy with this solution. This was a nice discussion. Thanks

**Comment by Simn** [comment]
Looks like [linux64](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/) and [mac](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/mac/) builds are up. Windows seems to have some problem though.

**Comment by back2dos** [comment]
For starters I reject the premise of closure being anywhere near an
industry standard. Its nodejs support is practically non-existent. Its
documentation is pretty bad (and I say that as a Haxe user, mind you).

Maybe I don't quite see what the underlying use case here might be. But I
would point out that in order to prevent closure from renaming certain
fields in advanced mode, the officially suggested approach is to use
closure's externs / exports. Instead trying to leverage Haxe's reflection
in hopes of generating code that closure will transform in some particular
manner is inappropriate usage or both closure and Haxe - and highly fragile
as a result. I really don't think its an approach that should govern how
Haxe generates JavaScript code.

**Comment by mockey** [comment]
Closure with ADVANCED_OPTIMIZATIONS is surely no "industry standard". There are warnings all over the place, that your JS-code might not run. So I was not really surprised that it didn't work with mine.

**Comment by derRaab** [comment]
Well - on one side you might be correct - even if I think closure compiler is the most effective tool out there - so ok - let's not call it industry standard but most brutal version which is used widely.

The usual HaxeJs project generates one single JavaScript file which is completely encapsulated (unless you're working with modules at runtime) - for example OpenFl does just that. So it's totally save to let closure compiler rename everything since it has no dependencies outside. Almost.

The only dependency from outside is loaded data - so even if I repeat myself - I think it's very important to have the default way to access untyped data dealing with that. Because accessing unknown structures is the only case where I would use reflection...?

**Comment by Simn** [comment]
I suppose we're done here.

**Comment by back2dos** [comment]
The premise is completely wrong: @derRaab's code is not "accessing unknown structures". If it were accessing *unknown* structures, the field name couldn't possibly be a constant and therefore the optimization couldn't possibly be done. There would be no issue.

It's borderline crazy to bend the genjs around such a highly specific use case for which the closure compiler actually has a **proper** solution. Why should everyone get worse code if one single user just refuses to leverage what is actually closure's officially suggested way to deal with it? This is so infuriating.

**Comment by Simn** [comment]
What's with the drama? You only get this kind of code using reflection/untyped anyway, and optimizing that strikes me as a questionable idea regardless.

**Comment by ncannasse** [comment]
That's a hard choice to make. It was indeed necessary to fix something here because Reflect.field (which is not inline) and Reflect.getProperty (which is) might lead to different code.

BTW I noticed that Reflect.getProperty does not try/catch as Reflect.field does. If I remember correctly, this try/catch was necessary on some older browsers since accessing some native objects with unknown fields was throwing errors. Does anyone know if it's still necessary?

**Comment by nadako** [comment]
@ncannasse We discussed that try/catch in some other issue arguing about removing it, but I can't find it now... I think your position was that Reflect.field should handle `Reflect.field(null, "field")` and return null instead of throwing, because it was used a lot. At the same time, Reflect.setField doesn't need to handle that, because... reasons? I'm pretty sure this is already inconsistent across targets though.

**Comment by nadako** [comment]
@ncannasse I think it's this one #4934

**Comment by back2dos** [comment]
@Simn The proposal is based on ignorance, as is the concluding decision. If this is how the language should evolve, then I'm alarmed by it.

**Comment by nadako** [comment]
To be honest, I too don't see a problem here. It was rather surprising anyway that Haxe was rewriting `o["some"]` to `o.some` in JavaScript. It looks cool, but also a bit pointless to me. Or am I missing something and this can lead to actual performance benefits?

**Comment by back2dos** [comment]
The way I see it there were three options:

1. Inform the user about the fact that Closure presents the solution to his problem. In that case he can create the required Closure externs and can rewrite his Haxe code to just access his data in a typed manner.

2. Even better: actually care about Closure support and generate Closure exports for anything that has `@:expose` and closure externs for all extern classes and all types aliased by an `@:extern` metadata.

3. Do what happened: disable some optimization only to give particular guarantees about Reflect. Yay. Because who cares about introducing guarantees about previously unspecified behavior regarding reflection. And who cares that the transformation also applied to all code of the form `untyped map[key]`, thereby affecting also `DynamicAccess`, `StringMap` and any other code anyone might ever write in this particular manner.

Will it make a difference performance wise? I don't know and I don't care that much. Most things are fast enough anyway and this is the kind of optimization that any decent JS runtime should include eventually. 

But *committing* to support such clumsy misuse of both Haxe and Closure, that tries to bypass both of their static analyzers instead of just leveraging their features appropriately, is a liability we should not take on. Before you would get away with such a hack, now you won't. It's not the language that should have to revert, it's the hack that should be removed.

**Comment by derRaab** [comment]
Hi - I was busy but now I’d like to comment on this.

Well, maybe calling closure compiler „industry standard“ is not the correct term. But I think it is the most powerful and effective tool to minify JavaScript. Won’t you agree on that?. With it’s advanced mode is exactly what’s needed to make a really big JavaScript application quite small. Games or applications created with Haxe for JavaScript usually result in one single file only and closure compiler works in that single file context perfectly - at least in my experience. Of course I expect it to be much more fragile if used with a lot of modules and external JavaScript files - I wouldn’t do that.

@back2dos: It’s not about ignorance, but for my use case using externs for closure compiler, or exporting symbols I wanna keep could just be a part of a solution (and for my specific implementation not really an option).

It all comes down to this: The easiest way is to just avoid dot syntax on loaded data. That’s all. Nothing more, nothing less.

And I thought that’s basically a job for the Reflect API as well. But maybe I was wrong.

I already wrote my own little ReflectUtil which uses untyped JavaScript or forwards to Reflect API on other platforms, just to make sure I’ll always be safe (hopefully).

At least we all can agree on the inconsistence regarding the output in my examples. :)

And now that I read about No. 3 I think @back2dos has a good point. I think I might not get all the implications that kind of change has - but at least the inconsistent behavior has to be fixed.

So I hope you guys make the correct decision! :)

P.S.: I love the fact that you guys care a lot about what has to be done or not. Cool community!
