### ISSUE TITLE
Array#sort() in hscript fails in PHP

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#5728]
It fails with both Haxe 3.2.1 and Haxe development (11d218ffdc67cfd3976127b271cf68d07b017d26). Tested with PHP 5.5.36.

``` haxe
import hscript.*;

class Test {
    static function main() {
        var parser = new Parser();
        var interp = new Interp();
        var ret = interp.execute(parser.parseString("
            var a = [1, 2, 3];
            a.sort(function(a,b) return b - a);
            a;
        "));
        trace(ret);
    }
}
```

```
uncaught exception: usort(): Array was modified by the user comparison function (errno: 2)

in file: /Users/andy/Documents/workspace/hscript/bin/lib/php/Boot.class.php line 149
#0 [internal function]: _hx_error_handler(2, 'usort(): Array ...', '/Users/andy/Doc...', 149, Array)
#1 /Users/andy/Documents/workspace/hscript/bin/lib/php/Boot.class.php(149): usort(Array, Array)
#2 [internal function]: _hx_array->sort(Array)
#3 /Users/andy/Documents/workspace/hscript/bin/lib/Reflect.class.php(50): call_user_func_array(Array, Array)
#4 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(797): Reflect::callMethod(Object(_hx_array), Array, Object(_hx_array))
#5 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(794): hscript_Interp->call(Object(_hx_array), Array, Object(_hx_array))
#6 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(390): hscript_Interp->fcall(Object(_hx_array), 'sort', Object(_hx_array))
#7 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(328): hscript_Interp->expr(Object(hscript_Expr))
#8 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(219): hscript_Interp->expr(Object(hscript_Expr))
#9 /Users/andy/Documents/workspace/hscript/bin/lib/hscript/Interp.class.php(215): hscript_Interp->exprReturn(Object(hscript_Expr))
#10 /Users/andy/Documents/workspace/hscript/bin/lib/Test.class.php(9): hscript_Interp->execute(Object(hscript_Expr))
#11 /Users/andy/Documents/workspace/hscript/bin/index.php(11): Test::main()
#12 {main}
```

It is more of a PHP bug than a Haxe bug according to http://stackoverflow.com/questions/3235387/usort-array-was-modified-by-the-user-comparison-function.
A simple workaround is suggested by the accepted answer above - use `@usort()` instead of `usort()`, but I'm not sure if we want to do this. If so, it is just changing [one line in php/Boot.hx](https://github.com/HaxeFoundation/haxe/blob/development/std/php/Boot.hx#L167-L169). Throwing exception in the compare function will still work as expected. I'm just not sure if there is any other hidden implications.

@mockey and @RealyUniqueName: Do you have any opinion?

**Comment by mockey** [comment]
It seems to be an old PHP bug, that only got fixed in PHP7:
https://bugs.php.net/bug.php?id=50688
So using `@usort` might be a viable workaround.

**Comment by RealyUniqueName** [comment]
It should be safe to prepend `usort` with `@`, but in `_hx_error_handler` we need to check `error_reporting()` value. And if it is zero, don't throw an exception.
http://php.net/manual/en/language.operators.errorcontrol.php

**Comment by RealyUniqueName** [comment]
After thinking a little bit more i came to conclusion that proposed solution may affect error handling in other situations.
The only real solution is to migrate to PHP7 runtime.
