### ISSUE TITLE
php://stdout is not available on Google App Engine

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5733]
On GAE's PHP standard environment, `php://stdout` is not available but [should use `php://temp` instead](https://github.com/shpasser/GaeSupportL5/issues/2#issuecomment-197718912)

And this line will fail:
https://github.com/HaxeFoundation/haxe/blob/c4ee4ab/std/php/_std/Sys.hx#L121

Can we make that configurable? Or use a try/catch to handle it?

**Comment by RealyUniqueName** [comment]
Do STDIN/STDOUT/STDERR constants work there?
http://php.net/manual/en/features.commandline.io-streams.php

**Comment by kevinresol** [comment]
Nope

```
exception 'HException' with message 'Use of undefined constant STDOUT - assumed 'STDOUT' (errno: 8)'
```

**Comment by RealyUniqueName** [comment]
I've changed `Sys` to use predefined constants, so now you can define `STDIN`, `STDOUT`, `STDERR` with `fopen('php://temp')` somewhere at the start of your app.
