### ISSUE TITLE
HTML InputElement valueAsDate property

### ISSUE THREAD

**Issue by ahoyet** [HaxeFoundation/haxe#5736]
Hi,

Since haxe 3.2 version, InputElement has no longer valueAsDate field so, the value can't be interpreted as a date.

The file InputElement says `// This file is generated from mozilla/HTMLInputElement.webidl line 24:0. Do not edit!` so I refered 6 months ago to [https://github.com/HaxeFoundation/html-externs](https://github.com/HaxeFoundation/html-externs).
I notice in 3.3rc version the field is missing yet.

Could this field be add or maybe there is a reason to avoid using it ?

Thanks

**Comment by Simn** [comment]
You already opened an issue in the correct place.

**Comment by nadako** [comment]
Meh, I wish @aduros was here... I remember having a headache after working with html-externs, but I'll try again...
