### ISSUE TITLE
[enhancement] REST / SPREAD operator

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#5741]
[ES6 has a REST and SPREAD operator usable on arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator).

[The latest ES6 proposal has even REAST/SPREAD on objects](https://github.com/sebmarkbage/ecmascript-rest-spread). This is already usable and largely used with transpilers like Babel.

This `...` operator is very useful especially with libraries like Redux and React that require the developer to implement pure functions very often (it eases the duplication of objects/arrays for example)...

I would love to use it with my favourite language... Would that be something hard to add to the Haxe syntax?

**Comment by nadako** [comment]
I don't particularly like that `...` syntax, but speaking of object copying, I'd love to see some syntax support for persistent data structures similar to OCaml's `{ myObj with field1=value1; field2=value2 }`.

**Comment by zabojad** [comment]
@nadako have you been using the spread operator on real projects? It is very handy...

The OCaml syntax you propose is very verbose when duplicating fields from objects having many fields... I do not say it's bad but it would be suitable for different use cases... Maybe both would be welcome in the haxe syntax though :)...

**Comment by dstrekelj** [comment]
Both rest and spread are nice to work with, from my (limited) experience. I think they'd fit in nicely with the functional aspect of Haxe. But who knows how much work it would take for the implementations to be consistent and efficient on all supported languages.

The macro context is, of course, pretty powerful and can realise some of the other ES2015 features such as [destructuring](https://medium.com/@sa_su_ke/assignment-destructuring-in-haxe-74fa8f28e6a4#.b42sa9us5). However, the problem then is that it only works in the macro context.

I'd love to see Haxe's syntax evolve as ECMAScript's various proposals mature and become standardised, but it's easier said than done.

**Comment by fullofcaffeine** [comment]
Just as a reminder, syntax changes should be proposed through the evolution process: http://haxe.org/blog/haxe-evolution-process?utm_source=haxe.io.

But yes, I do agree, would be nice to see the operator... since we're into it, can we get short lambdas too? Seriously!

**Comment by zabojad** [comment]
Guys, I just did not hear about this haxe evolution process until now. Thank you for pointing it to me!

I think this ticket can be closed and handled right in the evolution tracker... I'll reference the new ticket here.

**Comment by zabojad** [comment]
https://github.com/HaxeFoundation/haxe-evolution/pull/7
