### ISSUE TITLE
[C#] Perfomance issues with Map<> in C#

### ISSUE THREAD

**Issue by Muxeu** [HaxeFoundation/haxe#5743]
Hi all ! I have a problem with Map class in my projects. Almost impossible to use maps in perfomance critical parts. Due Runtime.\* them has huge time overhead and GC allocation if Map has a lot of objects. Also same problem with Dynamic Array.

Simple code:

```haxe
class Bar {
    private var testMap:Map<String, Foo>;
    private var typedArray:Array<Foo>;
    private var dynamicArray:Array<Dynamic>;

    public function new() {
        testMap = new Map();
        typedArray = [];
        dynamicArray = [];

        for(foo in testMap) {
            trace(foo.x);
        }

        for(key in testMap.keys()) {
            trace(testMap[key].x);
        }

        typedArray.push(new Foo());
        dynamicArray.push(new Foo());
    }
}

class Foo {
    public var x:Int;
    public function new() {

    }
}
```

Produces c# code full of Runtime.*:

```haxe
public class Bar {

    public Bar() {
        unchecked {
            this.testMap = new global::haxe.ds.StringMap<object>();
            this.typedArray = new global::haxe.root.Array<object>(new object[]{});
            this.dynamicArray = new global::haxe.root.Array<object>(new object[]{});
            {
                object tmp = ((object) (new global::haxe.ds._StringMap.StringMapValueIterator<object>(((global::haxe.ds.StringMap<object>) (this.testMap) ))) );
                while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(tmp, "hasNext", 407283053, null))) {
                    global::haxe.Log.trace.__hx_invoke2_o(((double) (((global::Foo) (global::haxe.lang.Runtime.callField(tmp, "next", 1224901875, null)) ).x) ), global::haxe.lang.Runtime.undefined, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"new", "HaxeMain", "HaxeMain.hx"}, new int[]{1981972957}, new double[]{((double) (25) )}));
                }

            }

            {
                object tmp1 = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<object>(((global::haxe.ds.StringMap<object>) (this.testMap) ))) );
                while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(tmp1, "hasNext", 407283053, null))) {
                    global::haxe.Log.trace.__hx_invoke2_o(((double) (((global::Foo) ((this.testMap.@get(global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(tmp1, "next", 1224901875, null)))).@value) ).x) ), global::haxe.lang.Runtime.undefined, default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"new", "HaxeMain", "HaxeMain.hx"}, new int[]{1981972957}, new double[]{((double) (29) )}));
                }

            }

            this.typedArray.push(new global::Foo());
            global::haxe.lang.Runtime.callField(this.dynamicArray, "push", 1247875546, new global::haxe.root.Array<object>(new object[]{new global::Foo()}));
        }
    }

    public global::haxe.ds.StringMap<object> testMap;

    public global::haxe.root.Array<object> typedArray;

    public global::haxe.root.Array dynamicArray;

}

public class Foo {

    public Foo() {
    }


    public int x;

}
```

Also problem appears in Array<Dynamic> types. What i am doing wrong ? Why Array/Map interfaces doesn't have "hasNext", "next", "push", "length" etc declarations ?

**Comment by ousado** [comment]
It might help to be more specific about where the overhead occurs, and to file separate issues for the Map<T> case and the Array<Dynamic> case, although regarding anything Dynamic, it's pretty simple: don't use it, and most definitely not in performance critical code.

**Comment by nadako** [comment]
I think this is the same as #2089. I proposed this idea for parametrized methods: #4475.

**Comment by nadako** [comment]
But anyway, the general rule is not to use Dynamic :)

**Comment by Muxeu** [comment]
In case of Dynamic Array is ok, i am avoding them.

I created two test to show issue about maps (for example IntMap):
http://pastebin.com/BaezbRxZ - this is haxe code
http://pastebin.com/aurLu7DM - this is C# code

And the results are (in unity profiler):
http://take.ms/tKQct

As you can see iterating thu map generates a lot of GC memory, when c# Dictionary doesn't. And iterations is about 40% slower with "Best" ones.

**Comment by nadako** [comment]
Oh, so this is about iterators. Yeah, that's the sad truth about the fact they are defined as structures instead of interfaces, so it requires some dynamic dispatching. Add here some redundant casting added by the C# generator...

We should really rethink the whole iterator-related stuff for the sake of performance on static targets and it's a shame that such basic thing as Map is that bad.

Meanwhile, I wonder if using StringMap/IntMap directly will help here a bit, since those are inlined methods that return classes (not sure if it's like that in 3.2.1 or only since 3.3 tho).

Maybe @ncannasse or @waneck have some ideas how to improve situation without breaking things?

**Comment by Muxeu** [comment]
Oh, it's bad. As our game is in pre release state and Maps are bottle neck (due GC spikes at gameplay) i created temp solution with custom Dictionary for C#.
Here is haxe code: 
http://pastebin.com/zbQnVx2z

And C# implementation

**Comment by ncannasse** [comment]
@nadako please note that while Iterator itself is a structure, nothing prevents returning a class instance that matches the signature.

**Comment by nadako** [comment]
@ncannasse This is the case here - it returns a class, but then it accesses it through dynamic dispatching because the concrete type is lost, since it's typed as `Iterator<T>`, so yeah, it's better than anon object used for an iterator, but it's still bad because it accesses its with reflection, basically.

@Muxeu So you basically caching NativeIterator's iterators here. I wonder how that helps since you still allocate enumerators from a c# side. I guess the real problem isn't the iterator allocation but these dynamic calls I'm talking about (I think they allocate too). We really have to do something here...

**Comment by Muxeu** [comment]
@nadako, yes, chaching generates extra allocation (around 32bytes each), but when i use custom iterator like this:
```
@:native("haxe.HaxeIterator")
extern class NativeIterator<T> {
    function hasNext() : Bool;
    function next() : T;
}
```
haxe generates good code without Runtime.* calls even if my dictionary has <Dynamic, Dynamic> type.
