### ISSUE TITLE
Good plugin for Intellij IDEA

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxe#5744]
The main reason, that stops me porting my AS3 code base to Haxe, is that there is no good IDE support.
I work with Intellij IDEA. It is really mature and cool, I and don't want to make one step backwards and return to FlashDevelop.
Currently there is a Haxe plugin, but it is still very raw.
The question is: do plan to make a better integration with Intellij IDEA? If yes, then approximately when?

**Comment by Simn** [comment]
See https://github.com/tivo/intellij-haxe
