### ISSUE TITLE
HTTP customRequest crashes

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/haxe#5753]
I'm running into an issue on neko/ubuntu.

This line crashes the program, no error is thrown.
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Http.hx#L703

**Comment by thomasuster** [comment]
Any ideas @pperidont ?

**Comment by thomasuster** [comment]
I narrowed it down, it crashes in `haxe/std/neko/_std/sys/ssl/Socket.hx`
Inside `function readBytes( buf : haxe.io.Bytes, pos : Int, len : Int ) : Int {`
It dies on `r = ssl_recv(  @:privateAccess __s.ssl, buf.getData(), pos, len );`
inside that ssl_recv function
And it will print `Custom(ssl@ssl_recv)`

**Comment by ncannasse** [comment]
@thomasuster this might be an error inside ssl_recv C function, try to check here.

**Comment by thomasuster** [comment]
https://github.com/HaxeFoundation/neko/blob/77d1ec9cc00bb90de2b5c66364641d954defab5f/libs/ssl/ssl.c#L229

Only way I can think to proceed is to build neko from source on a remote machine.

**Comment by thomasuster** [comment]
The buffer inside Socket.hx contains 100% of the response, I'm able to print it. It's JSON so it's easy to see that the data is complete.

**Comment by thomasuster** [comment]
Opened a PR for neko. https://github.com/HaxeFoundation/neko/pull/150
