### ISSUE TITLE
Feature request: exclusive range syntax.

### ISSUE THREAD

**Issue by adrianvoica** [HaxeFoundation/haxe#5758]
First of all, hats down to all the devs and contributors of Haxe! 

Now, some questions: 
- Why the triple dot notation for ranges in loops; `for (i in 0 ... 10)` ?
- Why not the (more standardized) double dot notation? `for (i in 0 .. 10)` ?

And, as a feature request, how about adding exclusive range syntax like Crystal's **a|..|b** : 
`for (i in 0|..|10) { // this iterates from 1 to 9 }`
or even better, if we don't use the index variable: 
`for (0|..|10)`
or make only one of the sides exclusive: 
`for (i in 0..|10) { // this iterates from 0 to 9 }`

Just my 2 cents (and feature request). Cheers!

**Comment by andyli** [comment]
I don't think there is a "standard" range operator. I can't see there is a "common" range operator among popular programming language either.

Haxe is at least consistent with [Ruby](http://ruby-doc.org/core-2.3.1/Range.html#M000695) in the sense that, `0...3` means 0, 1, 2 in both language.

**Comment by adrianvoica** [comment]
I won't argue on the origins / inspiration for Haxe - it is already a great language. What I suggest is useful for allowing exclusiveness/inclusiveness in either direction from a clean syntax point of view.

**Comment by adrianvoica** [comment]
I don't see this coming into the language, so I am just going to close this down.

**Comment by nadako** [comment]
I don't have any opinion on the exclusive range operator, but I think I like the `for (0...10)`, since often you just need to "do this thing several times" and you don't care about the loop variable at all. Right now I do `(for _ in 0...10)`. However, I don't think it's worth considering adding `for(iter)` to the language just for this.

**Comment by adrianvoica** [comment]
Yeah. I can live with that. It was just a suggestion worth discussing. Cheers!

**Comment by yar3333** [comment]
As for me, `for(iter)` looks dangerous: in most cases such construction is a error by developer. So, I think what explicit `for (_ in iter)` is better way.
