### ISSUE TITLE
Why is "use" a reserved keyword in JavaScript output?

### ISSUE THREAD

**Issue by deanm** [HaxeFoundation/haxe#5761]
As far as I know "use" is not / has never been a keyword or reserved word in JavaScript, but it's listed in kwds2 in genjs.ml.  Any reason?

**Comment by andyli** [comment]
It was first added in 782ecc6ee3a24c29b896dc18ed1f1973f9cf4379.
@ncannasse: Do you still remember why?

**Comment by deanm** [comment]
BTW, this is a pretty good writeup that saves you digging through the specs, as this has changed throughout the years:

https://mathiasbynens.be/notes/reserved-keywords

**Comment by ncannasse** [comment]
We might want to check/refresh our keywords list, if it's not one it's safe to remove

**Comment by Simn** [comment]
@haxiomic I'm co-assigning you here because you know something about JavaScript!

**Comment by nadako** [comment]
It was removed in cdb468bd090d52df9057741163b69ee563dbe296
