### ISSUE TITLE
Math constants like PI and optimization

### ISSUE THREAD

**Issue by deanm** [HaxeFoundation/haxe#5762]
Is there a reason that when you use Math.PI that it actually generates JavaScript code of "Math.PI" ?  If it was just the numerical constant, things like Math.PI / 2 could be calculated at compile time, etc.

**Comment by ncannasse** [comment]
We leave this kind of optimization to the JS compiler, and this keep the code smaller.

**Comment by deanm** [comment]
A normal JavaScript compiler is not able to make this optimization without some additional system/assumptions or annotation.  Math.PI is not a constant in JavaScript, so the lookup needs to happen at runtime, because both Math or Math.PI could have been replaced.  However, this is not the case in Haxe, it has the opportunity to mark and treat it as a constant.  If you wanted to access the actual JavaScript Math object (which could be replaced / shim / whatever at runtime) from Haxe, it could be made an option via js.html / whatever interface... Now there is a runtime cost both due to opportunity loss on not constant folding, and to the lookup of the Math object, and then the lookup of the PI property on the Math object.

**Comment by back2dos** [comment]
@deanm consider declaring your own FastMath class that defines PI as a static inline var and you should get what you're after ;)
