### ISSUE TITLE
[neko] MathImpl not found

### ISSUE THREAD

**Issue by aW4KeNiNG** [HaxeFoundation/haxe#5769]
Hi!

I have an error when i use the last version from git. I am getting the next error with openfl and haxeui-v2:

```
haxeui-core/haxe/ui/Toolkit.hx:153: characters 4996-5009 : Class<Math> has no field MathImpl
haxeui-core/haxe/ui/Toolkit.hx:33: characters 8-37 : Called from macro here
```

Here a simple project. It only calls the `Toolkit.init()` method.

https://dl.dropboxusercontent.com/u/7551055/haxeui-neko.zip

I am tried `-dce no` or `--macro keep('MathImpl')` and it didn't work.

The code works correctly with Haxe 3.2.1.

Any idea?

Thanks in advance.

**Comment by Simn** [comment]
How does one compile that?

**Comment by ibilon** [comment]
`haxelib run openfl test neko -debug`

When I looked at it with Ian the conclusion was that the native on MathImpl was responsible for the error
https://github.com/HaxeFoundation/haxe/blob/development/std/neko/_std/Math.hx#L24

**Comment by Simn** [comment]
The error message suggests that something does `Math.MathImpl`. I wonder if this is a problem with private types in general due to some haxeui macro generating a path like that.
