### ISSUE TITLE
Bug: JS flatten obscures reference to extern base class when getter/setter properties are used

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5772]
Here is an example of the issue:

http://try.haxe.org/#E0cBC

The following output is generated for the "Font" class:

``` js
Font.__name__ = ["Font"];
Font.__super__ = $hx_export.OtherFont;
Font.prototype = $extend($hx_export.OtherFont.prototype,{
    get_fontName: function() {
        return this.name;
    }
    ,set_fontName: function(value) {
        return this.name = value;
    }
    ,__class__: Font
    ,__properties__: $extend($hx_$export_OtherFont.prototype.__properties__,{set_fontName:"set_fontName",get_fontName:"get_fontName"})
});
```

The `@:native("$hx_exports.OtherFont")` reference is preserved until it extends the properties of the base class, where the `@:native` reference is improperly flattened.

Thanks :smile:

**Comment by nadako** [comment]
Sorry that such a trivial fix took so long, I was MIA :)

**Comment by jgranick** [comment]
Appreciated :smile:
