### ISSUE TITLE
Feature Proposal: Improvements to "exclude" behavior on JS

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5773]
Using the proper combination of `Compiler.exclude` and `Compiler.addMetaData`, it is possible to divide Haxe output between multiple JavaScript files. This is working quite well, but there are a few issues that prevent it from working better.

First, I was wondering if `Compiler.exclude` should default differently on JS?

For a type called `my.external.ClassName`, `Compiler.exclude` defaults to `my.external.ClassName` in the output. However, using `$hx_exports.my.external.ClassName` instead actually enables use from another file. This seems like a more sensible default.

Between Haxe 3.2.1 and the current development release, this breaks support for putting haxe.ds.StringMap in another module:

https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/haxe/ds/StringMap.hx#L145

(This could perhaps be resolved by attaching the object to the `StringMap` type?)

It would also be nice if were possible to allow the output for generated abstract classes to be compatible with `Compiler.exclude` and `Compiler.addMetadata` ... in other words, to push them into a different file. I understand that abstracts are inlined (by definition), but it seems like some of this could be skipped if the abstract is marked extern.

As-is, I can generate the following files separately:
- haxe.min.js: 93 KB (25 KB gzipped)
- lime.min.js: 293 KB (68 KB gzipped)
- openfl.min.js: 638 KB (147 KB gzipped)
- BunnyMark.js: 12 KB (5 KB gzipped)

Approximately 30% of the "BunnyMark.js" output is boilerplate, but I think this is still quite good, considering.

You can imagine the benefit of being able to push the Haxe standard library, or in this case, additional common Haxe libraries, into different files in order to promote code sharing -- especially as a project becomes more modular, and relies upon multiple Haxe projects (such as a collection of games)

One other thing, it seemed like I could not use `Context.onGenerate`, because by then, an class I want to extern might already be typed. Am I wrong in that assumption?

**Comment by Simn** [comment]
JS splitting is being discussed in another issue.
