### ISSUE TITLE
[display] field completion returns metadata in string interpolation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5775]
``` haxe
class Main {
    static function main () {
        var a = [];
        trace('${a.}');
    }
} 
```

```
haxe --display Main.hx@85
```

This returns metadata instead of the fields of `a`:

![](http://i.imgur.com/edDs0EP.png)

See also https://github.com/vshaxe/vshaxe/issues/56.

**Comment by Simn** [comment]
I hate our string interpolation implementation...

**Comment by Simn** [comment]
Any chance this is actually about trace arguments?
