### ISSUE TITLE
[C#] extending extens with property generates get/set in __hx_getField/__hx_setField with "never" access identifier

### ISSUE THREAD

**Issue by Muxeu** [HaxeFoundation/haxe#5778]
Simple code:

```
extern class Foo {
    var someProperty (default, never):Bool;
    var someProperty2 (never, default):Bool;
}


class Bar extends Foo {

}
```

Generates wrong C# code for Bar class. Function __hx_setField and __hx_getField always has read/write for all properties no matter what access modifer you use.

Result code is here:
http://pastebin.com/ehNJhSup

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
