### ISSUE TITLE
Parsing a JSON into a Map compiles but doesn't work

### ISSUE THREAD

**Issue by NemoStein** [HaxeFoundation/haxe#5779]
Per title, the following code doesn't work.
```haxe
import haxe.Json;
class Test
{
	static function main()
	{
		var map:Map<String, Int> = Json.parse('{"a": 1}');
		var keys = map.keys();
	}
}
```
This compiles just fine but doesn't work at runtime.

JS throws: `Uncaught TypeError: map.keys is not a function`
SWF throws: `Error #1034: Type Coercion failed: cannot convert Object@84848c9 to haxe.IMap.`
Neko throws: `Uncaught exception - Invalid call`

**Comment by Muxeu** [comment]
As aspected, please read https://haxe.org/manual/std-Json-parsing.html

**Comment by Simn** [comment]
Yes this is not sound, you cannot assign a dynamic value to some instance and expect it to just work like that.
