### ISSUE TITLE
HXCPP: Comparing a callback pointer to null results in an (unecessary?) dynamic object

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/haxe#5786]
I was profiling Defender's Quest with Very Sleepy and noticed some bottlenecks:

![2016-11-02 09_54_16-very sleepy cs - c__users_larsdo 1_appdata_local_temp_fb6 tmp](https://cloud.githubusercontent.com/assets/739064/19933760/8004658c-a0e2-11e6-8e62-383ea1828d1a.png)

The top 4 function calls, responsible for > 95% of the time, all terminate in one function, [flixel.animation.FlxAnimationController.set_frameIndex](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/animation/FlxAnimationController.hx#L720). The child calls of that function look like this:

![2016-11-02 09_58_23-very sleepy cs - c__users_larsdo 1_appdata_local_temp_fb6 tmp](https://cloud.githubusercontent.com/assets/739064/19933905/f0defdf8-a0e2-11e6-934f-fc9d11843e0a.png)

The trouble is inside an inlined function that can be found here:
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/animation/FlxAnimationController.hx#L640

And here's the relevant snippet of the generated cpp code (HX_STACK_LINE and HX_STACK_VAR removed for clarity):
```c++
Dynamic tmp10 = this->callback_dyn();
bool tmp11 = (tmp10 != null());
if ((tmp11)){
	::flixel::animation::FlxAnimation tmp12 = this->_curAnim;
	bool tmp13 = (tmp12 != null());		
```

The `tmp10` dynamic is created solely to create the `tmp11` boolean whose sole purpose is check if the callback is null.

Later on, when the callback itself is actually fired, the generated c++ just does this:

```c++
this->callback(tmp18,tmp19,tmp20);
```

The `tmp10` dynamic is used nowhere else in the generated c++.

So presumably in the case where you're directly comparing a callback variable against null, there's no need to create a Dynamic object?

Here's a sample minimal reproduction case:

```haxe
package;

import cpp.Lib;

class Main 
{
	static var testPtr:String->Void = null;
	static var nullPtr:String->Void = null;
	
	static function main() 
	{
		if (testPtr == null){
			trace("testPtr == null");
		}
		if (testPtr == nullPtr){
			trace("testPtr == nullPtr");
		}
	}
	
}
```

This outputs:
```
Main.hx:17: testPtr == null
Main.hx:20: testPtr == nullPtr
```

And here's the relevant generated c++ (sans HX_STACK_LINE, STACK_VAR, STACK_FRAME):

```c++
Dynamic Main_obj::testPtr;

Dynamic Main_obj::nullPtr;

Void Main_obj::main( ){
{
		Dynamic tmp = ::Main_obj::testPtr_dyn();
		bool tmp1 = (tmp == null());
		if ((tmp1)){
			Dynamic tmp2 = hx::SourceInfo(HX_HCSTRING("Main.hx","\x05","\x5c","\x7e","\x08"),17,HX_HCSTRING("Main","\x59","\x64","\x2f","\x33"),HX_HCSTRING("main","\x39","\x38","\x56","\x48"));		::haxe::Log_obj::trace(HX_HCSTRING("testPtr == null","\xe3","\xad","\xee","\xef"),tmp2);
		}
		Dynamic tmp2 = ::Main_obj::testPtr_dyn();
		Dynamic tmp3 = ::Main_obj::nullPtr_dyn();
		bool tmp4 = (tmp2 == tmp3);
		if ((tmp4)){
			Dynamic tmp5 = hx::SourceInfo(HX_HCSTRING("Main.hx","\x05","\x5c","\x7e","\x08"),20,HX_HCSTRING("Main","\x59","\x64","\x2f","\x33"),HX_HCSTRING("main","\x39","\x38","\x56","\x48"));		::haxe::Log_obj::trace(HX_HCSTRING("testPtr == nullPtr","\xcb","\xfb","\x03","\x29"),tmp5);
		}
	}
return null();
}
```

It makes sense that you might need to generate dynamics to compare two function pointers to eachother, but it looks like you don't need to when comparing a function pointer against a simple `null` value.

I decided to test this, and it seems to work.  If you change the haxe check to this:

```haxe
if (untyped __cpp__("testPtr == null()")) {
	trace("testPtr == null");
}
```

you get this in the c++

```c++
Dynamic Main_obj::testPtr;

Dynamic Main_obj::nullPtr;

Void Main_obj::main( ){
{
		if ((testPtr == null())){
			Dynamic tmp = hx::SourceInfo(HX_HCSTRING("Main.hx","\x05","\x5c","\x7e","\x08"),20,HX_HCSTRING("Main","\x59","\x64","\x2f","\x33"),HX_HCSTRING("main","\x39","\x38","\x56","\x48"));		::haxe::Log_obj::trace(HX_HCSTRING("testPtr == null","\xe3","\xad","\xee","\xef"),tmp);
		}
		Dynamic tmp = ::Main_obj::testPtr_dyn();
		Dynamic tmp1 = ::Main_obj::nullPtr_dyn();
		bool tmp2 = (tmp == tmp1);
		if ((tmp2)){
			Dynamic tmp3 = hx::SourceInfo(HX_HCSTRING("Main.hx","\x05","\x5c","\x7e","\x08"),23,HX_HCSTRING("Main","\x59","\x64","\x2f","\x33"),HX_HCSTRING("main","\x39","\x38","\x56","\x48"));		::haxe::Log_obj::trace(HX_HCSTRING("testPtr == nullPtr","\xcb","\xfb","\x03","\x29"),tmp3);
		}
	}
return null();
}
```

Which eliminates the first dynamic entirely, but still prints the same results.

The dynamics probably don't have a large cost in and of themselves, but in particularly hot inner loops that get called lots and lots of times in a single update (such as a callback in an animation update system as my profiling results seem to indicate are bottlenecked), it seems like it could be a nice boost to performance.

**Comment by larsiusprime** [comment]
(Thanks to Patrick McCarthy (mauvecow on twitter) for all the help with this.)

**Comment by larsiusprime** [comment]
Just tested with latest hxcpp and haxe 3.3.0-rc.1, definitely get different results:

```c++
void Main_obj::main(){
            	HX_STACK_FRAME("Main","main",0xed0e206e,"Main.main","Main.hx",15,0x087e5c05)
HXLINE(  16)		Bool _hx_tmp = hx::IsNull( ::Main_obj::testPtr );
HXDLIN(  16)		if (_hx_tmp) {
HXLINE(  17)			::haxe::Log_obj::trace(HX_("testPtr == null",e3,ad,ee,ef),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),17,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            		}
HXLINE(  19)		if (hx::IsEq( ::Main_obj::testPtr,::Main_obj::nullPtr )) {
HXLINE(  20)			::haxe::Log_obj::trace(HX_("testPtr == nullPtr",cb,fb,03,29),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),20,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            		}
            	}
```

I'll see if there's any obstacles to me using the latest haxe compiler in production, and re-profile.

**Comment by Simn** [comment]
If you migrate anyway, try grabbing a nightly from http://builds.haxe.org because there have been some fixes since the RC. Also, I'd be interested to know what problems you come across doing that so we can make the upgrade experience as smooth as possible.

**Comment by larsiusprime** [comment]
The RC wouldn't compile my project, had some weird issues with my version of lime. Upgraded to the nightly.

Tested the minimal repro app, got these results:

```cpp
void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_15_main)
HXLINE(  16)		if (hx::IsNull( ::Main_obj::testPtr )) {
HXLINE(  17)			::haxe::Log_obj::trace(HX_("testPtr == null",e3,ad,ee,ef),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),17,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            		}
HXLINE(  19)		if (hx::IsEq( ::Main_obj::testPtr,::Main_obj::nullPtr )) {
HXLINE(  20)			::haxe::Log_obj::trace(HX_("testPtr == nullPtr",cb,fb,03,29),hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),20,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            		}
            	}
```

Which looks even slightly cleaner.

Now I'm testing my app.

- Seems to rebuild lime okay.
- Can't build Defender's Quest. Same error as with the RC:

```
T:\git\DefendersQuest1>lime test windows -debug -Dnext -Dangle -Dsteam -clean
T:/git/lime/lime/app/Event.hx:77: characters 4-9 : false
T:/git/lime/lime/app/Event.hx:312: characters 6-11 : Called from
Aborted
```

I'm on a weird personal fork of lime at the moment that might be a bit out of date (stability purposes from my release a few months ago).

Here's the line in question:
https://github.com/larsiusprime/lime/blob/allfixes3/lime/app/Event.hx#L77

**Comment by larsiusprime** [comment]
Ah, that explains it. My fork of lime has some extra macro hooks added for crashdumper support. So I probably broke something? Weird it only breaks in the new Haxe.

https://github.com/larsiusprime/lime/blob/allfixes3/lime/app/Event.hx#L312

**Comment by larsiusprime** [comment]
Okay, found a workaround

**Comment by larsiusprime** [comment]
Defender's Quest compiles and runs with latest hxcpp from git and latest nightly haxe release.

Profiling with Very Sleepy aaaaand.....

...similar results?

My bottlenecks seem to remain:
![2016-11-02 11_18_23-very sleepy cs - c__users_larsdo 1_appdata_local_temp_18e1 tmp](https://cloud.githubusercontent.com/assets/739064/19937162/1ac001fc-a0ee-11e6-8d66-fca8d6521321.png)

Digging down a `Dynamic::operator()` still seems responsible for nearly everything:

![2016-11-02 11_18_58-very sleepy cs - c__users_larsdo 1_appdata_local_temp_18e1 tmp](https://cloud.githubusercontent.com/assets/739064/19937179/2b0bebc0-a0ee-11e6-9f1b-4b78e2587c65.png)

Relevant generated c++ is here:
```
int FlxAnimationController_obj::set_frameIndex(int Frame){
	HXLINE( 727)		if (hx::IsNotNull( this->_sprite->frames )) {
	HXLINE( 729)			Frame = hx::Mod(Frame,this->_sprite->numFrames);
	HXLINE( 730)			 ::flixel::FlxSprite _hx_tmp = this->_sprite;
```

the `if (hx::IsNotNull( this->_sprite->frames )) {` line is singled out as the sole terminal function taking up the majority of the time in my bottlenecked calls.

**Comment by Simn** [comment]
@hughsando: Can you make sense of that?

**Comment by larsiusprime** [comment]
Poking through hxcpp I think I may have found something?

https://github.com/HaxeFoundation/hxcpp/blob/5d3f85072516e7a86968ae1c3b133981cf5b3811/include/hx/Operators.h#L23

```cpp
namespace hx {
template<typename T> Null<T>::operator Dynamic() { if (isNull) return Dynamic(); return value; }
}
```

**Comment by hughsando** [comment]
The main overhead associated with a callback is to do with the boxing of args.
If you do not do any boxing (eg, passing objects), you should be ok.
For a proper test, you should compile for release, but with the HXCPP_DEBUG_LINK so the symbols actually work.
You should also be checking the "exclusive" time if you are looking at overhead, to avoid the time actually spent doing the work.

**Comment by Simn** [comment]
Do we have to do something here?

**Comment by hughsando** [comment]
I think the original problem was solved (using testPtr instead of testPtr_dyn).
It could be that this routine is legitimately where the time is taken - eg "updateAll", and this therefore expected.
