### ISSUE TITLE
Full DCE in JS Removing Private Field's init

### ISSUE THREAD

**Issue by cmandlbaur** [HaxeFoundation/haxe#5787]
Ran into an issue with building for JS with DCE set to full. Not sure if it's expected behaviour, I did a quick search to see if its been mentioned and didnt see anything.

Setting a private field's initial value in the constructor with full DCE causes the equivalent code to be excluded from the generated js.

```
class Mapper<StateE: EnumValue> {
    
    private var map: EnumValueMap<StateE, String>;

    public function new() {
        map = new EnumValueMap<StateE, String>();
    }
}
```

Setting the value in line works fine

```
class Mapper<StateE: EnumValue> {
    
    private var map: EnumValueMap<StateE, String> = new EnumValueMap<StateE, String>();

    public function new() {
    }
}
```

**Comment by Simn** [comment]
#4839
