### ISSUE TITLE
Cannot include Haxe class by name if package includes underscore

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5788]
In some projects, we include a direct class name reference to force the inclusion of a class.

In an HXML, for example, we might use:

```
-main TestMain
-cp Source
com.included.ClassName
-D mydefine
```

This appears to throw an error when the package path has an underscore:

```
Error: Could not process argument openfl._internal.swf.SWFLiteLibrary
Package name must start with a lower case character
```

Tested in Haxe 3.2.1 and a recent development build. I am guessing "_" fails some "isLowercase" test in the compiler, when it should be allowed by exception. Thanks :smile:

**Comment by yar3333** [comment]
Looks like related to #5417.

**Comment by Simn** [comment]
See related issue
