### ISSUE TITLE
calling match on an abstract leads to runtime error

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#5790]
```haxe
import haxe.ds.Option;

abstract A<T>(T) from T to T {
  public function new (x:T) this = x;
}

class Test {
    static function main() {
        var a = new A(Some(1));
        trace(a.match(Some(1)));
    }
}
```
Output:
```
Called from ? line 1
Called from Test.hx line 12
Uncaught exception - Invalid field access : match
```

see:
http://try-haxe.mrcdk.com/#6104E

**Comment by Simn** [comment]
It picks up this function as a static extension: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/EnumTools.hx#L201

That's very silly... Part of the problem if your `to T` which allows the cast to `Option<Int>`, which in turn unifies with `EnumValue`. I'm not sure right now how we could tame this.

**Comment by Simn** [comment]
This properly fails at compile-time now.
