### ISSUE TITLE
Analyzer inserts null

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5794]
In some cases which I wasn't able to isolate, the analyzer will transform `text.substr(cursorIndex-1)` into `text.substr(cursorIndex-1,null)`.

While this would not cause issue if the parameter is a nullable value, since for this case (any many others) it is not nullable, genswf will cast the null to Int and at runtime this will be the same as doing `text.substr(cursorIndex-1,0)` which produces a very different result.

**Comment by Simn** [comment]
I don't think that's the analyzer doing that. Try adding `@:analyzer(full_debug)` to the function where this happens, it prints to stdout some output that shows how the function code arrives at and leaves the analyzer.

**Comment by ncannasse** [comment]
You can reproduce by looking at Heaps h2d/Console.hx handleKeys method, it has several substr calls that get this specific behavior.

**Comment by ncannasse** [comment]
PS: using @:analyzer(full_debug) did output several files but nothing on stdout

**Comment by Simn** [comment]
Can you add `-debug`? I have to fix that it's required for that...

**Comment by ncannasse** [comment]
`haxe -lib heaps -swf test.swf h2d.Console -debug -swf-version 12`

```
after filter-apply
tf.text.substr(cursorPos);
...

after to-texpr
var pos<43249> = this.cursorPos;
var b<43247> = cast this<43248>.substr(pos<43249>, null);
...

**Comment by ncannasse** [comment]
Maybe that's because the text is typed as `hxd.UString` ?

**Comment by ncannasse** [comment]
Ok it seems to come from an invalid definition of substr in hxd.UString.
