### ISSUE TITLE
Compiler swallows helpful error message during macro execution and shows a strange not catchable error

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#5795]
It's important to have three different files. The following code (which of course does not compile) produces this error:

`Test.hx:2 Recursive implicit cast`

which is not very helpful. The strange thing is that this error occurs in this line:

`cl.get().statics.get();`

Uncommenting that line produces a good and helpful error message:
```
String should be { x : String }
String has no field x
For function argument 'x'
Defined in this class
Int should be { x : Int }
For function argument 'x'
```

The problem is that i know where this error occurs and i cannot even catch the error with a try...catch, which is a big problem, because my macro lib relies on helpful error messages :(.

TestMain.hx
```haxe
class TestMain {
	public static function main () {
		new IssueTest();
	}
}
```

Test.hx
```haxe
class Test  {
	public static var z2:Implicit<{ x : Int }> = 1;

	public function new () {
		var z:Implicit<{ x : String}> = "foo";
	}
}
```
Implicit.hx
```haxe
abstract Implicit<T>(T)  from T to T {
  
  public function new (x:T) this = x;
 
  @:from 
  macro static function fromExpr (e:haxe.macro.Expr) {
	var cl = haxe.macro.Context.getLocalClass();
	var t = haxe.macro.Context.getExpectedType();
	
	var t1 = switch t {
		case TAbstract(_.get() => { name : "Implicit"}, [t]): t;
		case _ : throw "error";
	}
	var ct = haxe.macro.TypeTools.toComplexType(t1);
        
	cl.get().statics.get(); // this line causes the strange error
	return macro new Implicit( ($e:$ct) );
  }
}
```

**Comment by Simn** [comment]
I'm getting the same error output with and without the line you mention, so I assume this to be fixed.
