### ISSUE TITLE
Haxe-based threads have no API for stopping them

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5800]
Once Haxe-based code relies more upon multiple threads, the need for being able to kill or stop a thread becomes more important.

For example (in pseudo-code):

```
var backgroundURLRequest = request ("site.png");

Timer.delay (function () {
    if (backgroundURLRequest.loaded) {
        backgroundURLRequest.cancel ();
    }
}, 30000);
```

Is there any way to safely interrupt a Haxe created thread?

**Comment by Simn** [comment]
I was under the impression that you can just Sys.exit out of your threads...

**Comment by ibilon** [comment]
I think @jgranick means from outside of the thread,
for instance if you launched a background calculation but don't need it anymore.

**Comment by Simn** [comment]
Right... Interestingly, the matching function on Java has been deprecated: https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#stop(). I think it's safe to assume that they put more thought into this problem than we did, so following their approach is probably a good idea.

**Comment by back2dos** [comment]
Killing a thread from outside is almost certain to leave behind a big mess. Whatever task the thread performs should have a mechanism built in to safely abort it and clean up any associated resources. In that case there is no doubt some input stream that should be closed and also buffers for the decompression and the resulting image data to be discarded.

As for building such mechanisms one could consider adding an API for interrupts, but I would advise against opening that can of worms. Dequeues provide a suitable messaging abstraction and Haxe is not assembly.

**Comment by jdonaldson** [comment]
I remember running into that deprecated method.  Here's what they suggest as a workaround:
https://docs.oracle.com/javase/7/docs/technotes/guides/concurrency/threadPrimitiveDeprecation.html

**Comment by ncannasse** [comment]
I don't think it's "safe" to stop a thread by simply killing it. You might be in the middle of a sys call with some native resources allocated that will never be freed (like opened files). Using existing threads communication primitives + non blocking or timeout syscalls is the best way to deal with it.  For instance haxe.Http does have a timeout if no data is received after some time it will throw an exception.

**Comment by Simn** [comment]
I'll go ahead and close this then.
