### ISSUE TITLE
string interpolation/reification issue

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#5803]
```
class Test {
    static function main() macro function (a) 'a: $a';
}
```
Test.hx:2: characters 57-58 : Unknown identifier : a

**Comment by RealyUniqueName** [comment]
This is by design. Since you're in a macro reification mode all dollar-identifiers are interpreted as references to a scope where `macro` keyword is used.
You can use `$$` instead:

```haxe
macro static function test() return macro function (a) return 'a: $$a';

static function main() {
	var f = test();
	trace(f('hi'));
}
```
This sample prints `a: hi` as expected.

**Comment by Gama11** [comment]
Hah, so `$$$$` is needed to get a literal `$`... :D

This is actually awkward for syntax highlighting, which assumes that one `$` = unescaped and `$$` = escaped.
