### ISSUE TITLE
Don't treat Bool as an enum in tests.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#5804]
Bool is an abstract.
```haxe
@:coreType @:notNull @:runtimeValue abstract Bool {
}
```
 and yet it is required to be an enum in tests:
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/TestReflect.hx#L102

**Comment by ncannasse** [comment]
Could you make a PR without this test that we can push to in order to fix all platforms?

**Comment by RealyUniqueName** [comment]
I can do it later today
