### ISSUE TITLE
Multiple declarations of a `var` with the same name and different types is not an error

### ISSUE THREAD

**Issue by ttencate** [HaxeFoundation/haxe#5805]
Using Haxe 3.3.0:

```
class Test {
  public static function main(): Void {
    var a = 42;
    $type(a); // "Int"
    var a = "forty-two";
    $type(a); // "String"
  }
}
```

I think this should be a compile-time error, rather than silently shadowing or overriding the former declaration. The potential to use this for good is virtually zero, whereas the potential for confusion and/or accidents is significant.

Note that this even happens if different types are explicitly given for both declarations.

**Comment by Simn** [comment]
This works as intended and there are no plans to change that.

**Comment by ttencate** [comment]
Understood, thanks for the quick response! I would love to know why, though. Is there a previous discussion/issue that I can read? I searched before posting this, but failed to find any.

**Comment by Simn** [comment]
I know that is was discussed several times before, but I can't find that discussion right now either.

**Comment by Gama11** [comment]
Here's one for function parameters, which is similar I guess: #4381

**Comment by nadako** [comment]
Let's not touch [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing), this is a very useful feature that prevents polluting local namespace.

**Comment by ttencate** [comment]
Usually, shadowing is only allowed from nested scopes, not from the very same scope. The only language I know that allows that, apart from Haxe, is JavaScript (whose scoping rules are not exactly a great example in general).

One situation where such shadowing could be confusing:

```
public function foo(y: String) {
  // Do something with y
}

public function bar(x: String) {
  // Lots of code...
  foo(x);
}
```

If the `Lots of code...` happens to shadow the `x` with a different type, the programmer is left scratching their head, wondering "`foo` expects a `String`, I'm passing a `String`, why won't it compile?!" And in cases where `foo` is more liberal (e.g. it takes `Dynamic`), this could even result in runtime errors rather than compile time.

But since I seem to be in the minority here, I will shut up now :)

**Comment by Simn** [comment]
> If the Lots of code... happens to shadow the x with a different type, the programmer is left scratching their head, wondering "foo expects a String, I'm passing a String, why won't it compile?!"

In any decent IDE you can just "Go to definition" on the variable and see where it's defined nowadays.

**Comment by kevinresol** [comment]
> The potential to use this for good is virtually zero

I would disagree that. This shadowing mechanism is very useful in macro, where codes are generated, not written.

**Comment by ncannasse** [comment]
variable shadowing is very common in functional languages since you don't have mutability:

For instance in OCaml
```ocaml
let l = List.map (....) l in
let l = List.filter (...) l in
```

I don't understand why it should be forbidden. If you have different parts of your method that each needs an array of something, naming it  xxx, xxx2, xxx3 is stupid, and reusing the same variable seems to indicate that you have a shared state between these parts while you don't. 

For example:

```haxe
var pl = getPlayers();
// do something with it

var pl = me.getOpponents();
// do something with it

var pl = ia.getOppenents();
// do something with it
```
