### ISSUE TITLE
hxcpp var shouldn't be inlined

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#5808]
Doing
```haxe
var ptr:Pointer<Something> = t.reinterpret();
return fn(ptr.ptr.someFunction());
```

will result in
```c++
return ::Cl_obj::fn(t1->reinterpret()->ptr->someFunction());
```

which fails with
```
error: member reference type 'cpp::AutoCast' is not a pointer; did you mean to use '.'?
error: no member named 'ptr' in 'cpp::AutoCast'
```

tricking the compiler/analyzer with
```haxe
var ptr:Pointer<Something> = null;
ptr = t.reinterpret();
```
works.

The variables shouldn't be inlined since reinterpret is templated from the type of the variable it's stored into.

**Comment by Simn** [comment]
We have to figure out how to communicate to the analyzer which variables we don't want to fuse away.

**Comment by AdrianV** [comment]
maybe a rule would be to keep the var,  if the var has an explicit type and this type is an external type

**Comment by Simn** [comment]
Unfortunately, we don't internally if a type-hint is explicit or not.

**Comment by AdrianV** [comment]
then the only way is to use some metadata. either on the var like @:keep, or maybe better on the type itself  (or the function return type) if it is critical for removal of temp vars like @:keepvars. So the designer of the library can choose, and the user does not need to care
