### ISSUE TITLE
[documentation] < characters not escaped for documentation 

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe#5812]
In the documentation the `<` is not escaped and shows the actual html 

For example `<iframe>`:
http://api.haxe.org/js/html/HTMLDocument.html#createIFrameElement

But this is generated: 
https://github.com/HaxeFoundation/haxe/blob/development/std/js/html/HTMLDocument.hx
so it needs to be fixed in the generator

**Comment by Simn** [comment]
That would be a HaxeFoundation/dox issue.

**Comment by MatthijsKamstra** [comment]
done: https://github.com/HaxeFoundation/dox/issues/207
