### ISSUE TITLE
[C#] Sharing haxe array/map implementation between multiple .NET assemblies?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/haxe#5814]
There are many Haxe classes that seems to come with any Haxe program. Is it possible to compile this into single .NET assembly and share it across multiple assemblies? I think I cannot pass Haxe arrays/maps between assemblies without sharing those classes. Even if I compile some program with `-D dll_import`, these classes are always generated. Can I prevent them from being generated?

On js, Haxe uses built-in JavaScript type for arrays/maps, so I didn't have much problems as C#.

Maybe some Haxe classes cannot be shared between assemblies. Can I prepend some namespace to such classes so that class names don't conflict each other?

**Comment by waneck** [comment]
Did you add `-net-lib <path-to-first-haxe-generated-library.dll>` together with `-D dll_import`? Together with `-dce no`, it should not generate the base Haxe classes. See for example https://github.com/HaxeFoundation/haxe/blob/development/tests/misc/csTwoLibs/compile-1.hxml#L1

**Comment by vroad** [comment]
I thought Array implementations were generated because Array.cs was there, but I've found that only Iterators were generated.

So these classes are still generated even with `-D dll_import~, which may cause name conflicts.

- NativeArrayIterator, StringMapKeyIterator, StringMapValueIterator
- Vector_Impl_ (because not included in `cs.Boot`?)
- Int32, Int64, UInt (do we need this on C#?)
- haxe.lang.EmptyObject, cs._Flags.EnumUnderlying_Impl_, NativeArray, Type

ObjectMap and IntMap is not included in `cs.Boot` either.

**Comment by Simn** [comment]
Closing old C# issue that won't be addressed.
