### ISSUE TITLE
Math unit tests failed on AppVeyor

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#5819]
Not sure why, suddenly, the Math unit tests are failing on Appveyor:
```
test macro
Changing directory to C:\projects\haxe\tests/unit/
Command: haxe [compile-macro.hxml,-D,appveyor]
TestMain.hx:36: Generated at: 2016-11-14 06:23:48
TestMain.hx:38: START
Math.unit.hx:8: false should be true
Math.unit.hx:149: false should be true
Math.unit.hx:151: false should be true
Math.unit.hx:233: false should be true
Math.unit.hx:376: false should be true
Math.unit.hx:378: false should be true
Test.hx:220: DONE [6839 tests]
Test.hx:221: SUCCESS: false
Command exited with 1 in 2s: haxe [compile-macro.hxml,-D,appveyor]
```

It happens since 4a387f9445140a2903909e6b630c615cdb3d5b8e, but clearly the commit is innocent since it is just a documentation change.

I cannot reproduce the failure locally on a Windows machine.

I also tried to switch to another OCaml distribution (df1a7c442dcedd525bac8705259d89bced846d29), but that doesn't help either.

If anyone wants to debug that, remote-desktop into AppVeyor's build by following https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
example: https://github.com/andyli/haxe/commit/b2c390e93d6dc3f058124ed5da2b5990654058c4
The cloned repo is at C:/projects/haxe

**Comment by Simn** [comment]
Nicolas fixed this in https://github.com/HaxeFoundation/haxe/commit/478febcbd5.
