### ISSUE TITLE
Genswf speedup potential

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#5830]
We have a big project. Here are timings for second compilation through compilation server (without any sources changed):
```
name             | time(s) |   % |     # | info
------------------------------------------
analyzer         |   0.210 |   1 | 18208 | 
filters          |  10.990 |  30 |     1 | 
generate         |  22.330 |  61 |     1 | 
  swf            |  22.330 |  61 |     1 | 
haxelib          |   0.060 |   0 |     2 | 
macro            |   0.000 |   0 |     4 | 
other            |   0.770 |   2 |     1 | 
server           |   0.250 |   1 |  6283 | 
  module cache   |   0.250 |   1 |  6283 | 
    add modules  |   0.180 |   0 |     8 | 
    changed dirs |   0.000 |   0 |  6259 | 
    check        |   0.070 |   0 |     8 | 
typing           |   0.000 |   0 |     1 | 
write            |   1.780 |   5 |     1 | 
  swf            |   1.780 |   5 |     1 | 
------------------------------------------
total            |  36.390 | 100 |     0 |
```
As you can see swf generation takes 22 seconds. It varies from time to time, but usually it's 20-30 seconds.
Did some profiling and found that ~60% of that time generator spends in `As3hlparse.lookup_class` after finishing `Genswf9.generate`. Did not check whether `lookup_class` is is called earlier, but after `Genswf9.generate` is finished it's called twice for each class.

**Comment by Simn** [comment]
Did you try creating a Hashtbl for these classes and look up using the index?

**Comment by RealyUniqueName** [comment]
I tried with index, but then haxe compiler fails with assert. I tried using full class structure as hashtable key, and everything worked fine, but it gave no speedup.

**Comment by Simn** [comment]
Can you push your implementation to some branch?

**Comment by RealyUniqueName** [comment]
Unfortunately, no. At least not today )
I accidently reverted it.

**Comment by nadako** [comment]
git reflog?

**Comment by RealyUniqueName** [comment]
it was not commited

**Comment by RealyUniqueName** [comment]
Since flash is low priority now, maybe this issue should be closed?

**Comment by Simn** [comment]
Fine with me.
