### ISSUE TITLE
Abstract enums improvments

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5833]
Currently abstract enums behave quite similarly as Haxe enums expect in two cases:
 - when a constructor is not found, there is no proposed suggestion for a replacement
 - ~~using `.match(pattern)` is not supported~~

**Comment by ousado** [comment]
Support for "open" @:enum abstracts would be very useful. Currently we have no way to tell the compiler to force us us to either use a default or a catch-all clause. Only by accident, not by design, the following works: http://try-haxe.mrcdk.com/#3eca1 
If we'd be able to specify that we have an enum abstract that can potentially hold all possible values of its underlying type, a default/catchall case could be made mandatory without relying on the current treatment of the special identifier `_`.

**Comment by kevinresol** [comment]
> using .match(pattern) is not supported

Given abstract enums have no parameters, isn't a `==` check is sufficient? Or did I miss anything?

**Comment by frabbit** [comment]
@kevinresol it's more about consistency, which is very helpful, if you change the enum implementation at some point.

**Comment by Simn** [comment]
I'm not sure that's worth introducing a potential conflict, given that abstract enums may very well have a field named `match`.

**Comment by frabbit** [comment]
true, you can achieve the same with the following. Maybe we add that function implicitly when there's no such function defined?
```haxe
@:enum abstract X(Int) {
    var Y = 1;
    public inline function match (other:X) {
        return this == other.impl();
    }
    inline function impl() return this;
}
```

**Comment by frabbit** [comment]
not sure if implicitly is such a good idea.

**Comment by ncannasse** [comment]
My case was trying to do `if( e.match(A|B|C|D) ) ....` which behaves differently if it's an enum or abstract enum

**Comment by Simn** [comment]
That in turn raises questions what should happen if your abstract overloads `|`.

**Comment by frabbit** [comment]
maybe we should disallow some things on abstract enums like overloading | or adding match method, but that should wait for 4.0.

**Comment by nadako** [comment]
do we really want to go that way? @:enum abstracts are different beasts than enums, I'd say let's keep it simple.

**Comment by frabbit** [comment]
Yes true, maybe we can tag the enum when op | and match are not defined, which would allow match on those types.

**Comment by ibilon** [comment]
> maybe we should disallow some things on abstract enums like overloading |

This is very useful for some extern, at least for c++, where the enum values are flags you xor together.

**Comment by frabbit** [comment]
Yes, my second suggestion is far better, best of both worlds.

**Comment by ncannasse** [comment]
I have removed the request for `.match`, could we have the suggestions for constructor when it's not a valid one?
