### ISSUE TITLE
Adding an option to get js source map without -debug

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/haxe#5836]
Currently the only way to get source map in js is to use -debug
Unfortunately sometimes you want source map for a release build 
For example you might want to report issue from live build with haxe code position

If we could add an option --source-map that would be great

**Comment by kevinresol** [comment]
That's why I don't use the `#if debug` inside my code. I will just define `-D release` and use `#if release`

**Comment by nadako** [comment]
@kevinresol but they you don't get the non-debug mode optimizations that are disabled for better debugging experience e.g. on JS.

**Comment by kevinresol** [comment]
Yeah that's just workaround until there is proper support :(

**Comment by jeremyfa** [comment]
Just like in cpp, you can enable stack traces/lines with -D HXCPP_STACK_TRACE/LINE, it makes sense to me to have something similar in js, like -D source-map, indeed. That would be a nice improvement!

**Comment by nadako** [comment]
Hope I didn't mess it up, try `-D js-source-map` :)

**Comment by wighawag** [comment]
Great, that was fast :) I ll have a look when I get a chance to try the latest. Thanks

**Comment by nadako** [comment]
@markknol could you please update that?

**Comment by RealyUniqueName** [comment]
`-D source-map` was introduced to be consistent across targets because Haxe also can generate source maps for php now. 
Prefer it over `js-source-map`.

**Comment by RealyUniqueName** [comment]
But afair `-D source-map` was introduced in one of previews of 4.0.0. It's not yet available with 3.4

**Comment by mastef** [comment]
I have some early `4.0.0` version, but it didn't work there yet. In any case, the docs should mention that.
