### ISSUE TITLE
Can Haxe add the support for compiling into TypeScript?

### ISSUE THREAD

**Issue by nykevinwong** [HaxeFoundation/haxe#5840]
Typescript is very popular as well. Can Haxe support typescript transpiring so that typescript users can also benefit from Haxe?

**Comment by Simn** [comment]
No and there are no plans to support that. Typescript can consume JavaScript anyway, so I'm sure Haxe's JavaScript target can be used.

**Comment by nadako** [comment]
Haxe could generate `.d.ts` files for TypeScript though, but we have no resources to implement that right now (and this can be done as a macro library), so PRs welcome.

**Comment by nykevinwong** [comment]
How Haxe transpire Haxe source code (*.hx) into its corresponding Javascript, C#, or C/C++ code?
Where can I find the information/documentation regarding writing such translation rules? 
Where are the specific sets of classes or syntax translation rule files in haxe source code I can look into?

**Comment by nadako** [comment]
it's much more complicated than "translation rules". there's a lot going on. source->ast->typed ast->optimizer->generator. what one can do is macro-hook on the last step and generate something else from the resulting optimized typed AST structures (using `haxe.macro.Context.onGenerate`).

**Comment by kevinresol** [comment]
@nykevinwong you may want to start from the generator https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genjs.ml

**Comment by fullofcaffeine** [comment]
You are forgetting about other use-cases. There are many javascript frameworks that officially use TypeScript nowadays. A TS target would make it very easy to integrate with these frameworks, without a lot of boilerplate macros or custom generator code, it'd be possible to just use the frameworks build pipeline (like `ionic-cli` for example). Ionic is an example of such a framework, as is Angular 2.
