### ISSUE TITLE
Autocomplete is not working with libraries added as -swf-lib-extern

### ISSUE THREAD

**Issue by dkolyesnik** [HaxeFoundation/haxe#5841]
Autocomplete is not working with libraries added as -swf-lib-extern. 
I thought that it was Flash Develop bug and created an issue there, but they found that compilation server is not returning classes from swf added as -swf-lib-extern.
@SlavaRa  tested it:

compiler args with -swf-lib-extern:
-main ApplicationMain --macro "openfl._internal.utils.ExtraParams.include()" -cp "C:/HaxeToolkit/haxe/lib/openfl/4,4,1" -D openfl=4.4.1 --macro "lime.Lib.extraParams()" -cp "C:/HaxeToolkit/haxe/lib/lime/3,4,1" -D lime=3.4.1 -cp "src" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/flash" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/openfl" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/extras" -D tools=3.4.1 -D no-compilation -D openfl-flash -D web -swf-lib-extern lib/as3corelib.swc -swf-lib-extern lib/mx.swc -swf-version 11.2 -swf bin/flash/release/bin/OpenFLApp.swf -swf-header 800:480:60:000000 -cp "bin/flash/release/haxe" -D display --display "C:\projects\OpenFLApp\src\Main.hx"@262 -D use_rtti_doc -D display-details -D display-stdin
result: No classes found in mx\n\u0002\n

compiler args with -swf-lib:
-main ApplicationMain --macro "openfl._internal.utils.ExtraParams.include()" -cp "C:/HaxeToolkit/haxe/lib/openfl/4,4,1" -D openfl=4.4.1 --macro "lime.Lib.extraParams()" -cp "C:/HaxeToolkit/haxe/lib/lime/3,4,1" -D lime=3.4.1 -cp "src" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/flash" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/core/openfl" -cp "c:\HaxeToolkit\haxe\lib\openfl/4,4,1/externs/extras" -D tools=3.4.1 -D no-compilation -D openfl-flash -D web -swf-lib lib/as3corelib.swc -swf-lib lib/mx.swc -swf-version 11.2 -swf bin/flash/release/bin/OpenFLApp.swf -swf-header 800:480:60:000000 -cp "bin/flash/release/haxe" -D display --display "C:\projects\OpenFLApp\src\Main.hx"@262 -D use_rtti_doc -D display-details -D display-stdin
result: "<list>\n<i n=\"accessibility\" k=\"package\"><t></t><d></d></i>\n<i n=\"containers\" k=\"package\"><t></t><d></d></i>\n<i n=\"controls\" k=\"package\"><t></t><d></d></i>\n<i n=\"core\" k=\"package\"><t></t><d></d></i>\n<i n=\"effects\" k=\"package\"><t></t><d></d></i>\n<i n=\"events\" k=\"package\"><t></t><d></d></i>\n<i n=\"messaging\" k=\"package\"><t></t><d></d></i>\n<i n=\"modules\" k=\"package\"><t></t><d></d></i>\n<i n=\"netmon\" k=\"package\"><t></t><d></d></i>\n<i n=\"printing\" k=\"package\"><t></t><d></d></i>\n<i n=\"rpc\" k=\"package\"><t></t><d></d></i>\n<i n=\"skins\" k=\"package\"><t></t><d></d></i>\n<i n=\"utils\" k=\"package\"><t></t><d></d></i>\n</list>\n"

Haxe Compiler 3.3.0 (git build development @ 956db6f)
FD Completion Mode: Completion Server, Compiler

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
