### ISSUE TITLE
Assertion failed in typeload.ml

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5843]
Version: b4aa19f

Source to reproduce:
https://github.com/kevinresol/haxe_issues/tree/issue_5843

In a nutshell, the compiler fails when a typedef of generic-built type is used in an optional field in an anon type.

```haxe
// file 1
@:genericBuild(...)
class Generic<T> {}

// file 2
typedef TheTypedef = Generic<Data>;

// file 3
typedef Item = {
  ?fail:TheTypedef, // assertion fail
  ok:TheTypedef, // because the absence of `?`
  ?alsoOk:Generic<Data>, // because not typedefed
}
```

Sidenote: It will also compile if all the above are put in the same file.

**Comment by RealyUniqueName** [comment]
Works with the latest dev Haxe
