### ISSUE TITLE
Syntax changes for Haxe 4

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5844]
This is a collection issue for syntax changes we want to make for Haxe 4. Unless otherwise noted, all of these are "under discussion".

### Short Lambda

See https://github.com/HaxeFoundation/haxe-evolution/blob/master/proposals/0002-arrow-functions.md (accepted)

### `is` operator

See https://github.com/HaxeFoundation/haxe/issues/2976 (accepted)

### Improved asynchronous programming

Look into generators and async/await to find a good solution for Haxe.

### Key-value iteration

See https://github.com/HaxeFoundation/haxe/issues/2421

**Comment by Venryx** [comment]
Yes please! All four of these are great--especially the short lambdas. : D

(-dev interested in Haxe, coming from the world of C# and ES6)

**Comment by frabbit** [comment]
Not sure if it's a syntax change but typed meta (https://github.com/HaxeFoundation/haxe/issues/3959) comes to my mind.

**Comment by Montycarlo** [comment]
Short Lambdas would be amazing.

Re: Asynchronous async/await: [tink_await](https://github.com/haxetink/tink_await) works really nicely

**Comment by RealyUniqueName** [comment]
Would be great to have something like this:
```haxe
var value = getSomeValue();

if(value is MyType) {
    //value is typed as MyType in this block
    value.methodOfMyType();
}

switch(value) {
    case is MyType: //don't treat as syntax proposal :)
        //value is typed as MyType in this case
        value.methodOfMyType();
    case is AnotherType:
        //value is typed as AnotherType in this case
        value.methodOfAnotherType();
}
```

**Comment by jdonaldson** [comment]
We need a better way of handling overloads for extern methods.  The overload definitions are awkward to write out because of how they're treated as attached metadata:

```haxe
	@:overload( function (dst : Dynamic, str : String)  : Dynamic {})
	public static function copy(dst : Dynamic, src : Dynamic, len : Int) : String;
```

It would be nice to just have the overload given as a free metadata on a given method:

```
	@:overload 
        public static function copy(dst : Dynamic, str : String)  : Dynamic;
	[...]
        public static function copy(dst : Dynamic, src : Dynamic, len : Int) : String;
```

In the presence of that metadata (and for externs only) the compiler won't care about the duplicate definition.

**Comment by Simn** [comment]
See #5297

**Comment by jdonaldson** [comment]
Regarding async programming mentioned above, I think we should build a first class shared api off of [libuv](https://github.com/libuv/libuv).

Having an easily externable cross platform c library goes a long way towards unifying a lot of behavior quirks across platforms and languages.

**Comment by jdonaldson** [comment]
We should look into better support for continuations.

```haxe
// Something.hx
import Foo;
[...]
doSomething(function(a,b){
  Foo.bar(a,b);
});

```

becomes

```haxe
import Foo;
[...]
async k = doSomething();
Foo.bar(k.a, k.b);
```
The ``async`` keyword here functions a bit like ``using`` in that it automatically takes the last (typically callback) argument of a function, and then types itself as if it were a anonymous object of those arguments. (The Lua multireturn pattern should help here)

I think it should be possible to handle this with try/catch support as well... each callback method body is wrapped in an error handler, which are all wired together.

This pattern won't work for all cases (including methods with more than one callback), but it should get rid of a good chunk of the indentation and error handling problems that crop up with async code.

**Comment by jdonaldson** [comment]
Introduce a ``val`` keyword for immutables.

**Comment by jdonaldson** [comment]
A data class type with tuple-style accessors (e.g. access by name or by position).

```haxe
tuple Dog(name : String, age : Int);
[...]
var d : Dog = new Dog('fido', 4);
trace(d.val1); // fido
trace(d.name); // fido
```

**Comment by hughsando** [comment]
I would like inline-properties, like:

```haxe
public var prop(function() return 3,null):Int
```
Should be easier now the name is fixed ('get_') and short lambdas.

**Comment by Justinfront** [comment]
jdonaldson should indexes start at 0 your example looks incorrect? Should it be?
```
var d : Dog = new Dog('fido', 4);
trace(d[0]); // fido
```

**Comment by nadako** [comment]
> public var prop(function() return 3,null):Int

I think I like, this. Actually I proposed changing those get/set specifiers from simple idents to expressions, so stuff like this could be possible.

**Comment by fponticelli** [comment]
I like the prop proposal. Maybe there is no need for a full function? The signature of Getters/Setters is very well known so we could put in there just the body expression. In the case above:

```haxe
public var prop(3,null):Int
```

One with a private var:

```haxe
private var _prop: 
public var prop(_prop,_prop = _):Int
```

The `_` is for `value` in the setter.

**Comment by Gama11** [comment]
I don't think using `_` for that is a good idea, it's used for "ignored values" in other places. Maybe just `value` as a contextual keyword like in C#.

**Comment by jdonaldson** [comment]
@Justinfront you're right, start from 0. Too much time spent with Lua :)

**Comment by nadako** [comment]
> I don't think using _ for that is a good idea, it's used for "ignored values" in other places. Maybe just value as a contextual keyword like in C#.

I'd say it's more correct to read that not as "ignored value", but as "some value here", considering how we use it in extractors within patterns (`case _.toUpperCase() => "HI"`). With this thinking, using `_` like @fponticelli proposed makes sense IMO.

**Comment by Simn** [comment]
I would appreciate if you could handle discussions of a _specific_ change in a distinct issue, else this issue is going to turn into a huge mess over the next weeks and months.

**Comment by jdonaldson** [comment]
Yeah, that's a good idea.  But let's also give some kind of overview somewhere in a wiki page or something.

**Comment by Simn** [comment]
I'll just mention it in the entry-post here, it's intended as an overview anyway.

**Comment by harold-b** [comment]
> Key-value iteration

Something to generate native javascript `for( key in object )` loops without any additional overhead would be awesome.

This is the hack I've been using so far: https://gist.github.com/harold-b/df24fc5f77e316e2a3c684097256fc8c
Demo: http://try.haxe.org/#E9BC4

**Comment by back2dos** [comment]
@harold-b FWIW you can simplify that significantly: http://try.haxe.org/#453bA

**Comment by harold-b** [comment]
@back2dos Ooh, very nice! Didn't know it would inline a function body like that. Thanks for the tip. Think I'll use it like that instead.

Would still need an abstract for combined String/Int key array access though. Not to mention property deletion.

**Comment by RealyUniqueName** [comment]
Consider changing
```haxe
class MyClass implements IFace1 implements IFace2 implements IFace3 {...
```
to
```haxe
class MyClass implements IFace1, IFace2, IFace3 {...
```
E.g. I have a project, where such things is a common case:
```haxe
class Joint extends Effect
    implements IBrightness
    implements IContrast
    implements ISaturation
    implements IHue
    implements IVertexColor
    implements IColorOffset
    implements IMask
    implements IYuvConversion
    implements IMultiTexture
    implements ISupplementedAlphaMerge
{
```

**Comment by delahee** [comment]
I love everyone of those things.

On a more strategical side, imvho the 'async' is really a very important thing to secure in a very near future, it often floats in migrations discussions and other modern use cases.
Thanks!

**Comment by Simn** [comment]
There are distinct issues for the individual items here (except async which isn't gonna happen), so might as well close this.
