### ISSUE TITLE
Allow macros to accept typed expressions

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5846]
In some cases it makes more sense for a macro to consume a typed expression. Would it be possible for the compiler to examine which parameters are `TypedExpr` and type them already? 

Building on that, could we have a `TypedExprOf<T>` that would type the expression against `T` (unlike `ExprOf` which only seems to affect static extension targets for understandable reasons).

**Comment by Simn** [comment]
I wonder if there could be a more general solution using abstract casts, given that there's already an API to type an `Expr` as `TypedExpr`.

**Comment by back2dos** [comment]
It's an interesting idea indeed, although I wonder in what exactly it would generalize.

**Comment by elsassph** [comment]
It would be amazing to have bidirectional conversion of `TypedExpr` to and back from `Expr`.

**Comment by kevinresol** [comment]
Here they are already:
`Context.typeExpr(expr)` is `Expr->TypedExpr` and
`Context.getTypedExpr(typed)` is `TypedExpr->Expr

But during the process some information is lost (e.g. metadata).

(Read more: https://github.com/HaxeFoundation/haxe/issues/5534)

**Comment by nadako** [comment]
The typing process is lossy (e.g. pattern matching transformations, inlining, even var declaration), so you can't just convert `TypedExpr` "back" to `Expr`, they are just different structures.

And IIRC `getTypedExpr` is unreliable because of the reasons above. I think one should use the new `storeTypedExpr` instead.

**Comment by back2dos** [comment]
> The typing process is lossy (e.g. pattern matching transformations, inlining, even var declaration), so you can't just convert TypedExpr "back" to Expr, they are just different structures.

And macros are applied too, which basically mutilates everything.

My motivation here is this: some macros operate based on expression structure. They take what is otherwise non-sense for the compiler and turn it into something that will pass the typer. There are also macros that operate on the type of an expression instead, and then just wrap other code around it, without ever inspecting the structure of the expression itself. These two kinds are obviously just two points of a wide spectrum, but the closer you get to the latter category, the more useful it would be to just get the typed expression. Or possibly even something less cumbersome such as:

```haxe
typedef TypedExpr2 = {//TODO: pick a better name
  type: haxe.macro.Type,
  pos: Position,
  stored: Ref<Expr>, // <-- this could basically produce what storeTypedExpr yields
  typed: Ref<TypedExpr>, //<-- 95% of the time nobody needs this and creating it only wastes memory
}
```

I guess for Haxe 4 we could simplify things down to this:

```haxe
typedef TypedExpr = {
  var type(default, null):haxe.macro.Type;
  var pos(default, null):Position;
  var expr(get, null):TypedExprDef;//this is lazy
}
```

Maybe we could even do it earlier, but there's an off chance to break some arcane macro in a very subtle way.

In any case we would give programmers the ability to automatically run the typer before calling the macro and to avoid creating expensive Expr trees that only serve as arguments for `Context.typeof`.

**Comment by Simn** [comment]
I acknowledge that this would be a bit more elegant than manually running Context.typeof, but I'm not sure that's enough to justify a feature like this. But we can certainly talk about the macro interface for Haxe 4.

**Comment by Simn** [comment]
Let's keep the macro interface as it is. I don't see too much of a benefit from supporting typed expressions here, given that you can already explicitly type them.
