### ISSUE TITLE
Incorrect JS events externs

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#5849]
It looks like some externs have regressed between Haxe 3.2.1 and Haxe 3.3.

For example, the `MouseEventInit` typedef:
https://github.com/elsassph/haxe-react-mmvc/issues/1

**Comment by nadako** [comment]
Could you please try now? I _think_ I made the extern generator output extended dictionaries from webIDLS properly, but I may be wrong, since the whole thing is still a mystery to me.

**Comment by elsassph** [comment]
Thanks that's looking correct now - `MouseEventInit` was missing properties from `UIEventInit`.
