### ISSUE TITLE
3.4-rc.1 cpp code/type issue

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#5850]
Trying the new RC to no avail (yet!).
Not sure if this is for hxcpp repo or here.
hxcpp `3.4.2`
haxe `3.4-rc.1` 

I have the following code:
```haxe
var _joystick : sdl.Joystick = joysticks.get(e.jdevice.which);
SDL.joystickClose(_joystick);
```

The call itself is an extern to a native library:
```haxe
@:native('SDL_JoystickClose')
static function joystickClose(joystick:Joystick):Void;
```

The joystick type is an opaque extern class to `SDL_Joystick*`
```haxe
@:native("SDL_Joystick")
@:include('linc_sdl.h')
extern private class SDL_Joystick {}
typedef Joystick = cpp.Pointer<SDL_Joystick>;
```

And the map, is just a map:
```haxe
var joysticks : Map<Int, sdl.Joystick>;
```

[The code is here](https://github.com/snowkit/snow/blob/master/snow/modules/sdl/Runtime.hx#L675-L677). I added an explicit type to see if type inference was playing a role.

### The problem

The problem lies in the generated code.
```c++
HXLINE( 677) SDL_JoystickClose(::haxe::IMap_obj::get(this->joysticks,e->jdevice.which));
```

Which due to the way it's generated, creates a c++ error:
```
error: no matching function for call to 'SDL_JoystickClose'
no known conversion from '::Dynamic' to 'SDL_Joystick *'
```

I have no ideas to try work around it, I can't see any way to force it not to make the change or to interpret the type any differently. Ideas appreciated. 

cc @hughsando 

---

The AST:
```
[Then:Void] [Block:Void]
    [Call:Void]
        [Field:joystick : sdl.Joystick -> Void]
            [TypeExpr sdl.SDL:Class<sdl.SDL>]
            [FStatic:joystick : sdl.Joystick -> Void]
                sdl.SDL
                SDL_JoystickClose
        [Call:Null<sdl.Joystick>]
            [Field:k : Int -> Null<sdl.Joystick>]
                [Cast:IMap<Int, sdl.Joystick>]
                    [Cast:IMap<Int, sdl.Joystick>]
                        [Field:Map<Int, sdl.Joystick>]
                            [Const:snow.modules.sdl.Runtime] this
                            [FInstance:Map<Int, sdl.Joystick>]
                                snow.modules.sdl.Runtime
                                joysticks
                [FInstance:k : Int -> Null<sdl.Joystick>]
                    haxe.IMap<Int, sdl.Joystick>
                    get
```

### 3.2.1 code

3.2.1 worked as intended, code generated (without hxcpp debug):

```cpp
::haxe::ds::IntMap tmp4 = this->joysticks;      
int tmp5 = e->jdevice.which;        
::cpp::Pointer< SDL_Joystick > tmp6 = tmp4->get(tmp5);
::cpp::Pointer< SDL_Joystick > _joystick = tmp6;        
::cpp::Pointer< SDL_Joystick > tmp7 = _joystick;
SDL_JoystickClose(tmp7);
```

3.2.1 AST
```
[Then:Void] [Block:Void]
    [Var tmp4(60816):haxe.ds.IntMap<sdl.Joystick>]
        [Field:haxe.ds.IntMap<sdl.Joystick>]
            [Const this:snow.modules.sdl.Runtime]
            [FInstance:haxe.ds.IntMap<sdl.Joystick>]
                snow.modules.sdl.Runtime
                joysticks
    [Var tmp5(60817):Int]
        [Field:Int]
            [Field:::cpp::Struct<SDL_JoyDeviceEvent>]
                [Local e(14587):::cpp::Struct<SDL_Event>]
                [FInstance:::cpp::Struct<SDL_JoyDeviceEvent>]
                    SDL_Event
                    jdevice
            [FInstance:Int]
                ::cpp::Struct<SDL_JoyDeviceEvent>
                which
    [Var tmp6(60818):Null<sdl.Joystick>]
        [Call:Null<sdl.Joystick>]
            [Field:key : Int -> Null<sdl.Joystick>]
                [Local tmp4(60816):haxe.ds.IntMap<sdl.Joystick>]
                [FInstance:key : Int -> Null<sdl.Joystick>]
                    haxe.ds.IntMap<sdl.Joystick>
                    get
            [Local tmp5(60817):Int]
    [Var _joystick(14688):sdl.Joystick] [Cast:Null<sdl.Joystick>] [Local tmp6(60818):Null<sdl.Joystick>]
    [Var tmp7(60819):sdl.Joystick] [Local _joystick(14688):sdl.Joystick]
    [Call:Void]
        [Field:joystick : sdl.Joystick -> Void]
            [TypeExpr sdl.SDL:Class<sdl.SDL>]
            [FStatic:joystick : sdl.Joystick -> Void]
                sdl.SDL
                SDL_JoystickClose
        [Local tmp7(60819):sdl.Joystick]
```

**Comment by hughsando** [comment]
I think this is going to need a compiler fix.
Technically, the JoystickClose function takes a cpp.RawPointer, but the cpp.Pointer should be doing this conversion for you.
Here is a simple test case:
```@:native("SdlJoystick")
extern class SdlJoystick { }

typedef Joystick = cpp.Pointer<SdlJoystick>;

@:cppFileCode('
   struct SdlJoystick { };

   void print(SdlJoystick *) { printf("Hello\\n"); }
')
class Test
{
  @:native("print")
  @:extern static function print(j:Joystick) : Void { }


  public static function main()
  {
     var map = new Map<Int, Joystick>();
     map.set(1,null);
     print( map.get(2) );
  }
}
```

You can get your variable back using the 'haxe.extern.AsVar' on the Joystick type arg, like:
```
@:extern static function print(j:haxe.extern.AsVar<Joystick>) : Void { }
```
This will fix the problem be forcing a variable to be used when passing the arg (good solution for references with the new compiler).
Since this is newer, you may need a typedef for this backwards compatibility.
But I will see what i can do in the compiler.

**Comment by Simn** [comment]
This is basically the same as #5808. I guess we really need a metadata that we can add to types like cpp.Pointer.

**Comment by Simn** [comment]
@hughsando: Are there types other than cpp.Pointer that should have their variables kept?

I didn't add a test for this yet, I suppose this should be added to the hxcpp tests because it's target-specific.

**Comment by hughsando** [comment]
I have some "auto cast" code in gencpp, and it should be able to detect that I'm actually passing a Dynamic to cpp.Pointer function call.  So think it should probably be fixed here - or at least I should have a look and see where it falls down - there might be other cases.
I have a spot in the hxcpp tests for this kind of thing.

**Comment by underscorediscovery** [comment]
@hughsando @Simn on `3.4.0 (git build development @ 865aa86)` nightly this appears to be working as expected for now. 

I'm trying to get all my projects running to do more thorough testing before I am confident of anything, but have run into a `map.get` failing when using a variable so when I isolate it further will open a separate issue for that one.

Thanks
