### ISSUE TITLE
haxe-3.4 compiler crash

### ISSUE THREAD

**Issue by VsevolodZakharov** [HaxeFoundation/haxe#5851]
It is crashing on this case:
Test,hx file:

```
class Test {
	public static function fun() : String {
		try {
			return "";
		} catch ( s : Dynamic ) {
			return "";
		}
		return "";
	}
	public static function main() : Void {
	}
}

```
C:\Users\User\Documents\GitHub\flow>haxe -main Test.hx -js test.js
While analyzing Test.fun
dot graph written to dump/js/Test.fun
Not_found

dot file content:
digraph graphname {
n273 [shape=box,label="(273)\nreturn \"\""];
n272 [shape=box,label="(272)"];
n271 [shape=box,label="(271)\nreturn \"\""];
n270 [shape=box,label="<function-end>
(270)"];
n269 [shape=box,label="<function-begin>
(269)"];
n269 -> n271[style="dashed",color="gray",label="try"];
n269 -> n273[style="dashed",color="gray",label="catch"];
n269 -> n0[style="dashed",color="gray",label="next"];
n1 [shape=box,label="<root>
(1)"];
}

haxe 3.3 works fine

**Comment by Simn** [comment]
Thanks for the nicely reduced example!
