### ISSUE TITLE
haxe 3.3: Old JS Notifications are missing.

### ISSUE THREAD

**Issue by VsevolodZakharov** [HaxeFoundation/haxe#5852]
In the haxe 3.3 js.html.DesktopNotificationCenter is used. However it is supported only in FireFox it seems. What about other browsers? Why was js.html.Notification removed?

**Comment by Simn** [comment]
Who knows anything about this? @ncannasse @aduros @nadako @frabbit @andyli

**Comment by nadako** [comment]
Not me, but I guess we need to regenerate externs from updated IDLs...

**Comment by nadako** [comment]
Hmm, notification is in our webidls... https://github.com/HaxeFoundation/html-externs/blob/master/webidl/mozilla/Notification.webidl

**Comment by frabbit** [comment]
No idea
