### ISSUE TITLE
Analyzer code output

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5853]
I was quickly looking at difference in JS code output between 3.3 and 3.4, I'm writing here some things that could be improved.

The diff can be seen here:
https://github.com/ncannasse/castle/commit/665f0c7d41712076f7ce60195713a949f16b12ba#diff-7fa1bac66ad1b6ddb0aec71c47628405

```
result({ color : getColor(vcol1), done : false});
(or)
change.ref(Std.parseInt("0x" + c.toHex()));
```
This now creates a tmp var to store call result whereas it should not

```
jc[0].click(TClosure(jc,field))
```
This will create also a tmp, maybe harder to deal with

All `++` are rewritten to `+=1` which is not very good.

**Comment by Simn** [comment]
Not 4.0-critical, can be improved later.

**Comment by Simn** [comment]
This should be fine now. If not, feel free to reopen.
