### ISSUE TITLE
Compiler parses function call after function definition even when multiple lines are in between

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#5854]
```haxe
class Test {
    static function main() {
        	
        function test (window) {
            trace(window);
            
        }
        
        // hey 
        
        (js.Browser.window);
    }
}
```

**Comment by frabbit** [comment]
This leads to ugly errors like this:
```haxe
class Test {
    static function main() {
        	
        function test (window) {
            trace(window);
            
        }
        
        // hey 
        
        (js.Browser.window:js.html.Window).document; // Test.hx:11: characters 26-27 : Unexpected :
    }
}
```

**Comment by nadako** [comment]
As discussed on slack, this is due to `expr_next` being called from `parse_function`, which most likely have no other effect than this confusing behaviour. But we have to experiment with disabling it and find out for sure. Let's do that after the 3.4 release.

**Comment by kevinresol** [comment]
I remember this has been discussed before

**Comment by kevinresol** [comment]
here: https://github.com/HaxeFoundation/haxe/issues/5464

**Comment by nadako** [comment]
Oh yeah that's the same indeed. But this time we might want to experiment with "breaking" it, after all...

**Comment by Simn** [comment]
Still need to decide here if we want to break this.

**Comment by back2dos** [comment]
You cannot remove the parens here:

```haxe
(function (v) trace(v))("hello");
```

FWIW the parens are always mandatory in AS3/JS and I'd say it would be pretty sane for us to handle it the same way. I think it's reasonable to assume that this will affect a lot less code than our change of `;` rules and `,` in `implements`/`extends` clauses from 2 to 3.

**Comment by Gama11** [comment]
Does hxparser behave the same way? We could run it over all Haxelibs with the change and see what breaks.

**Comment by ncannasse** [comment]
I'm fine with the breaking. I'll complain if I find I have a lot of code
relying on it but I doubt it :)

**Comment by sledorze** [comment]
For feedback, typescript just insert a ';' after the function declaration in such case (only). This saves a character, and so is totally a game changer :)

**Comment by kevinresol** [comment]
> For feedback, typescript just insert a ';' after the function declaration in such case (only). This saves a character, and so is totally a game changer :)

You can do so in haxe already
