### ISSUE TITLE
3.4-rc.1 toString issue

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/haxe#5856]
haxe `3.4.0 (git build development @ 865aa86)`
hxcpp `329e23aef9715a93c491bf2800bbf602f229ccc9`

I was looking for a consistent ruling on the behaviour of toString in the documentation but can't find it. **What is the required/ideal access level for toString?**

I was under the impression it was a bit ~magic, and therefore always gets called regardless of access. Because of that, almost every time I've ever used toString since using Haxe I have made it a private function (and often make it inline). 

While testing 3.4, all my projects (whole game engine included) have compiled successfully except for one or two cases. The error is that of `Cannot access private field toString`. **But** the weirder part is that the exact same code worked fine on cpp target, only the js target is complaining about this particular access, in these particular cases. Only 2 / 36+ projects have complained about this now.

I'd be fine to go make all the 100's of times I've used toString public if need be, but I feel like this inconsistency and undefined nature of the facility needs to be made more explicit, or at the very least documented as best practice as public to avoid the inconsistent behavior.

Here is a reproducible case. 
It should compile and run fine on hxcpp (at least on mac),
but js will error before even compiling with the access complaint.

**This code works on both with 3.2.1**

```
class Test {
    static function main() {
        var hmm = new Hmm();
        trace(hmm);
    }
}

class Hmm {
    public function new() {}
    function toString() return 'Hmm!';
    // public function toString() return 'Hmm!';
}
```

hxml
```
-main Test
-cpp bin/
#-cmd bin/Test

--next

-main Test
-js test.js
```

side note: I have seen similar inconsistency with regards to inherited access, i.e parent declares a function as public, child overrides it without the public keyword. Sometimes a change to the compiler will make some very specific code paths complain, and others it (continues) to not matter. I'd prefer if the behaviour was explicit so that it doesn't break occasionally when nothing has changed, but I haven't been able to narrow this down ever, it's sporadic and unclear as to what triggers it and why.

**Comment by Simn** [comment]
I probably broke that with https://github.com/HaxeFoundation/haxe/commit/3882069e8bfbd065090b24bf873643a1f8cee41d because I indeed didn't consider the visibility limitations.
