### ISSUE TITLE
Suggestion for abstract casts for functions

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5857]
```haxe
package;

class Main {
	static function main() {
		var e:Expr = function(e) return 1; // doesn't compile
	}
}

abstract Expr(String) from String to String {
	@:from
	public static function ofInt(i:Int):Expr
		return Std.string(i);
	@:from
	public static function ofFunc(f:Expr->Expr)
		return f('bar');
}
```

I wish it would work somehow like the below:
Compiler sees it is trying to cast `Unknown->Int` to `Expr`. While the compiler search down the `@:from` list for compatible casts, if it sees 1-argument function cast with non-identical type signature, don't skip right away but try to cast each of the arguments and return type accordingly
   i.e. `Unknown` to `Expr` & `Int` to `Expr` respectively. If all the casts succeed, use that cast.

**Comment by Simn** [comment]
I never really looked at this issue and now that I am looking at it I don't understand it. Sounds like some black magic, so whatever you want to do here would require a haxe-evolution.
