### ISSUE TITLE
[js] Using `trace` on a null object has an error

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5858]
This is the error:

```
Uncaught TypeError: Cannot read property 'toString' of null
```

It results from the following generated JavaScript:

```js
haxe_Log.trace(this.stage.stage3Ds.get(0).context3D.toString(),{ fileName : "PiratePig.hx", lineNumber : 35, className : "piratepig.PiratePig", methodName : "new"});
```

It looks like this needs a quick null check before calling `toString()`. There is no custom `toString` method on this object, to my knowledge.

**Comment by Simn** [comment]
Looks like my original fix for trace-consistency (https://github.com/HaxeFoundation/haxe/commit/3882069e8bfbd065090b24bf873643a1f8cee41d) caused more problems than it solved. As usual I forgot about null-values...

I don't think inserting conditionals in this case is a good solution as it might also require binding the traced expression to a temporary variable. The best course of action is to revert the original change and figure out how to deal with #4864 at a later time.
