### ISSUE TITLE
Bad dir name in archive

### ISSUE THREAD

**Issue by dmouton** [HaxeFoundation/haxe#5861]
Hi all,
When i download haxe archive 3.3.0-rc.1 or 3.4.0-rc.1, the archived dir name is 3.3.0-rc1 and 3.4.0-rc1
It's not the same as the release version.

btw, haxelib has not the same problem.

Is it possible to use the release version name?

**Comment by Simn** [comment]
I don't really want to change that because I have no idea what parts of the build process might rely on the current naming scheme. Does this cause any actual issues?

**Comment by dmouton** [comment]
It was for downloading haxe from npm.
I fixed it but it's quite strange to have different names.
