### ISSUE TITLE
Private constructor isn't always respected

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#5871]
This example can call `new Framedelay()` while Framedelay has a private constructor. 

Example: http://haxe.stroep.nl/issues/private.zip

**Expected:** `error: cannot call private constructor`  
**Got:**  just compiles

Haxe 3.3 and Haxe 3.4rc1 notes: In the generated source the `new Framedelay()` is also eaten by dead code elimination / analyzer, while that shouldn't be the case. I have no idea why this happens, it also is specific to the setup; when I reduce it to a smaller minimum example it does give the expected error.  This does not seem to happen in Haxe 3.2.1, there is the new FrameDelay also in the generated source.

Happy debugging!

Seen in Haxe 3.4rc1, Haxe 3.3, Haxe 3.2.1

**Comment by nadako** [comment]
Reduced to this:
```haxe
class Base {
    var v = 0;
}

class Child extends Base {
    private function new() {}
}

class Main extends Base {
    static function main() {
        new Child();
    }
}
```

**Comment by ncannasse** [comment]
Private is Haxe means "protected" in Java, which mean the subclasses can always access your private var or functions. That goes with the constructor to.

**Comment by nadako** [comment]
Yes, but `Main` is not a subclass for `Child` and yet it can access its private constructor.

**Comment by romamik** [comment]
Duplicate? https://github.com/HaxeFoundation/haxe/issues/5643

**Comment by Simn** [comment]
Indeed. I'll close the old issue though because this one has the shorter example and more discussion.

**Comment by cmandlbaur** [comment]
Just ran into this issue now. Has there been any changes to the status of this?

**Comment by mrmonday** [comment]
The test case appears to be fixed when testing against 0920d2352e90f734c55c2642d377fc537f0cfc21.

**Comment by ncannasse** [comment]
@mrmonday wrong issue ?

**Comment by mrmonday** [comment]
```
$ git rev-parse HEAD
0920d2352e90f734c55c2642d377fc537f0cfc21
$ cat Main.hx 
class Base {
    var v = 0;
}

class Child extends Base {
    private function new() {}
}

class Main extends Base {
    static function main() {
        new Child();
    }
}
$ ./haxe -version
4.0.0
$ ./haxe -main Main.hx -java output
Main.hx:11: characters 9-20 : Cannot access private constructor
```

**Comment by mrmonday** [comment]
OK, weird - when I try with other backends, I get different results.

* Java: Error, as expected
* C#: Error, as expected
* C++: No Error
* JavaScript: No Error
* Lua: No Error
* SWF: No Error
* AS3: No Error
* Neko: No Error
* PHP: No Error

Haven't tested others.

**Comment by bendmorris** [comment]
Issue here is that Base has a `@:compilerGenerated` constructor field. When Main attempts to access Child's constructor it looks through Child's parents and finds a generated constructor on Base that it does have access to, ergo this is allowed.

Checking for `@:compilerGenerated` is a potential solution, but what's the actual correct behavior here?

Option 1: If base explicitly declares a constructor, then Main should have access to Child's constructor, as it was declared in a common ancestor that Main can access.
Option 2: If base explicitly declares a constructor, Child's constructor is still private; their shared ancestry is irrelevant.

Based on the comment `(* if our common ancestor declare/override the field, then we can access it *)` I was assuming the first, but is this specified? It seems unintuitive.
