### ISSUE TITLE
haxe.macro.CompilationServer API broken

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5872]
Trying to use the new `haxe.macro.CompilationServer` API, for instance with:

```haxe
--macro server.setModuleCheckPolicy(['DefaultAssetLibrary'], [CheckFileContentModification])
```

results in the following error:

```
C:\HaxeToolkit\haxe\std/haxe/macro/CompilationServer.hx:75: characters 18-142 : Invalid input value
--macro:1: character 0 : Called from
Aborted
```

I bisected this to 9101843f040cf3bd2ad42e17883629550c573252.

**Comment by Simn** [comment]
Not technically a regression, but if this means the CompilationServer API doesn't work at all we should either fix it or remove the API for the next release.

**Comment by Simn** [comment]
@ncannasse: You might want to look into this because it could suggest a more general regression.

**Comment by Gama11** [comment]
@ncannasse Are you sure this is fixed? I still get the same error on latest dev.
