### ISSUE TITLE
Pattern match fails to compile with `Invalid_argument("List.fold_left2")`

### ISSUE THREAD

**Issue by m22spencer** [HaxeFoundation/haxe#5873]
Haxe version 3.3.0 rc1.

http://try.haxe.org/#0f4F2

Compilation fails with:
```Invalid_argument("List.fold_left2")```
Commenting case A,B, or C will allow the code to compile.

```haxe
class Main {
    static function main() {
    }

    static function foo(prev, next) {
        return switch([prev,next]) {
        case [_, 'eot']           : true;   //A
        case ['LF', _]
           | [_, 'LF']            : true;   //B
        case ['LV' | 'V', 'V'|'T']: false;  //C
        case _:
        }
    }
}
```

**Comment by Simn** [comment]
Yeah I expected the tuple handling to get me in trouble here. I'll have to see what I can do about that.

**Comment by Simn** [comment]
There's something wrong with the uselessness checks in general. If we emulate the tuples by using enums instead, the compiler falsely complains about the `"V" | "T"` part on case 3 being unused:

```haxe
enum Tuple {
	T2<S, T>(s:S, t:T);
}

class Main {
	static function main() {
		trace(foo(T2("V", "V")));
	}

	static function foo(t:Tuple) {
		return switch(t) {
			case T2(_, "eot"): 1;
			case T2("LF", _) | T2(_, "LF"): 2;
			case T2("LV" | "V", "V" | "T"): 3;
			case _: 4;
		}
	}
}
```
