### ISSUE TITLE
No `README` file in Linux packages

### ISSUE THREAD

**Issue by AldoMX** [HaxeFoundation/haxe#5874]
Hi people, I'm in the process of learning Haxe and I wanted to let you know that the current version (3.4.0-rc.1) requires some effort for a Linux newcomer to get it running.

For starters, the archives at http://haxe.org/download don't include any kind of documentation (not even a `README` file), and the download website doesn't link you to a "how to install" section of the documentation, you have to dig deeper to find out this page which lives in an old website: http://old.haxe.org/manual/haxe3#manual_installation

Second, when running `haxelib`, it returns the following error:

```
haxelib: error while loading shared libraries: libneko.so: cannot open shared object file: No such file or directory
```

I figured out that I had to install the `libneko` dependency, so no big deal, I proceeded to install it with `sudo apt-get install libneko0`, but the issue was still happening.

Checking the contents of `/usr/lib/` I noticed there were no `libneko.so`, but there were two files: `libneko.so.0` and `libneko.so.0.1`, so I figured out I had to create a symlink: `sudo ln -s /usr/lib/libneko.so.0.1 /usr/lib/libneko.so`

After that I got the following error:

```
Uncaught exception - load.c(237) : Failed to load library : std.ndll (std.ndll: cannot open shared object file: No such file or directory)
```

I supposed it was an outdated version, so I repeated the process installing Haxe's PPA and installing `libneko2`, but I got the same error at the end.

So I decided to install the whole `neko` package, and it finally worked, and for the sake of completeness, I removed Haxe's PPA and I installed the `neko` package from launchpad with the same success.

At the end of the day all of this hassle could have been easily avoided with a `README` file telling you to install `neko` beforehand, which for a person accustomed to Haxe may be obvious, but not for a newcomer like me.

OTOH, I suggest you to link `haxelib` against `libneko.so.${MAJOR}` rather than against `libneko.so`.

**Comment by jdonaldson** [comment]
This all is spelled out here : http://haxe.org/download/linux, which is directly linked from the main download page.  Did those steps work?  It's hard to miss that page if you do a relevant search, and the web page there is pretty informative (and preferable to a README imho).
