### ISSUE TITLE
Override DCE'ed w/ compiler cache

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5875]
Happened a few times during Ludum Dare, to me and other devs as well:

An override was not triggered, recompiling didn't help, until the class was modified, which meant something was wrong in the compiler cached version

**Comment by ncannasse** [comment]
This could also explain why some fields are disappearing from completion when they are DCE'ed

**Comment by ncannasse** [comment]
Yes, I can confirm DCE'ed fields are no longer appearing in completion :'(

**Comment by ncannasse** [comment]
Also confirmed the first problem : an empty method is not triggered when it's overriden until the cache is reset

**Comment by Simn** [comment]
It would probably help if you told me how to actually reproduce this...

**Comment by ncannasse** [comment]
@Simn one of the symptom which was reported was the following : when creating a subclass of hxd.App in a flash project (using heaps library), overriding the onResize method was not working until HaxeDevelop was restarted. I didn't investigate myself but got twice the report during Ludum Dare from different developers using a recent GIT version

**Comment by RealyUniqueName** [comment]
> Yes, I can confirm DCE'ed fields are no longer appearing in completion :'(

> when creating a subclass of hxd.App in a flash project (using heaps library), overriding the onResize method was not working until HaxeDevelop was restarted. I didn't investigate myself but got twice the report during Ludum Dare from different developers using a recent GIT version

@ncannasse I cannot reproduce none of that with the latest Haxe.

**Comment by Simn** [comment]
Pretty sure this is fixed, and there's no reproducible example anyway.
