### ISSUE TITLE
Parser resuming in structure and array declarations

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#5878]
We currently resume past array and structure declarations when resuming, which leads to bad display results in cases such as this:

```haxe
class Main {
	static function main () {
		var o:Array<{k:{a:Float, b:String}}> = [{|
	}
}
```

In order to fix this we have to catch Display exceptions when parsing these declarations. That in turn requires changing the implementations because they currently rely on the call stack as accumulator, which makes it hard to deal with exceptions properly. That should be a good idea regardless because it might make the parsing functions tail-recursive.

**Comment by abhi18av** [comment]
@Simn , hey since you've mentioned Tail Recursive here I'm curious whether Haxe supports Tail / Mutual Recursion
