### ISSUE TITLE
AS3 generating Math["isNaN"], should be just isNaN

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5883]
This haxe code:

```
   return Math.isNaN(Math.POSITIVE_INFINITY);
```

Generates this AS3 code:

```
    return Math["isNaN"](Math["POSITIVE_INFINITY"]);
```

Which results in a runtime error (because Math["isNaN"] is null, in AS3, isNaN is a global function): TypeError: Error #1006 value is not a function

The correct AS3 code is:
```
    return isNaN(Math["POSITIVE_INFINITY"]);
```

Hmm, between this and #5882 - maybe I'm confused about namespacing or versions or somthing I'm unaware of. I'll ask other channels.

**Comment by Simn** [comment]
How are you compiling the AS3 code? You're supposed to compile `__main__.as`.

**Comment by jcward** [comment]
Ah. Yes, I'm trying to use the generated AS3 in another project, so I'm not using the __main__.as.

I see that it's decorating the Flash classes. Interesting. Alright, well, I'll close these issues. Thanks.
