### ISSUE TITLE
Split out types from haxe.Constraints in Constraints.hx to their own files: IMap.hx, Constructible.hx

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5887]
It is quite confusing that to use `IMap<K, V>` I must `import haxe.Constraints;` and can’t just write `haxe.IMap<String, String>`. Also, when using `--gen-hx-classes`, the compiler emits code that references uses `IMap<K, V>` as `haxe.IMap<String,String>` and also writes `haxe/IMap.hx` instead of `haxe/Constraints.hx`.

I am trying to [get haxe to generate definitions for my module](http://stackoverflow.com/q/41166200/429091). This issue basically prevents me from being able to use `IMap<K, V>` in my public API without post-processing the output of `--gen-hx-classes` which gets quite ugly quite fast.

**Comment by binki** [comment]
Note that in my particular API it doesn’t make sense to use `Map<K, V>`. I need `IMap<K, V>` so that I can either pass in a concrete map *or* a translation layer that implements `IMap<K, V>`.

Is there any reason the standard library needs to have a different layout than is generated by `--gen-hx-classes`?

**Comment by Simn** [comment]
You will have to deal with that anyway because Haxe allows having multiple public types in a .hx module, which means you could come across the same situation in other places.

I'm not sure yet what we'll do with the Map interface in Haxe 4, but I doubt we'll make IMap more prominent then it is right now.

**Comment by binki** [comment]
Actually, I find it weird that both these work:

    import haxe.Constraints;
    class MyClass {
        public var things(default, null):haxe.IMap<String, String>
    }

and:

    class MyClass {
        public var things(default, null):haxe.Constraints.IMap<String, String>
    }

Doesn’t this make it easy to declare multiple same-named types in the same package which would be quite confusing?

OK, I’ll alter my system to put in `import haxe.Constraints;` and other things as I find them then…

**Comment by Simn** [comment]
That's how Haxe modules work, see http://haxe.org/manual/type-system-modules-and-paths.html

**Comment by binki** [comment]
Ah. So am I right to say, based on

> In fact, addressing `haxe.ds.StringMap<Int>` can be considered shorthand for `haxe.ds.StringMap.StringMap<Int>`.

means that this is a bug in `--gen-hx-classes` because it collapses the module name out of the type name? Or is this intentional? Is there an alternative to `--gen-hx-classes` that preserves modules?
