### ISSUE TITLE
Parametrized constraints choke on inheritance

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5890]
Consider [this example](http://try.haxe.org/#0871e):

```haxe
interface Foo<T> {
    function blargh<S:T>(v:S):Void;
}

class Bar<T> implements Foo<T> {
    public function blargh<S:T>(v:S):Void {}
}
```

I fails saying that:

> Field blargh has different type than in Foo
> Constraints differ
> Bar.T should be Foo.T

However in this context `Bar.T` is `Foo.T`, or is it not? I mean technically `Foo.T` is `Bar.T` but that seems close enough to me.

**Comment by Simn** [comment]
I think you're right, type parameter application should indeed make these types equal.
