### ISSUE TITLE
3.4-rc1 & Nightly - Problem with cpp.NativeArray.setData being called through a Dynamic

### ISSUE THREAD

**Issue by dazKind** [HaxeFoundation/haxe#5893]
Hi folks,

I was looking into housekeeping some of the libs I worked on(e.g. https://github.com/snowkit/linc_enet) in terms of the new 3.4 release and I noticed some strange issue/regression concerning some externs I got.
Namely I use cpp.NativeArray.setData is some occasions to deal with unpacking native data. It used to work with 3.2 splendidly and with 3.4 rc1 and nightly it fails with a `Null Function Pointer` error being thrown.

Luckily I was able to distill the problem into a simple sample:

```haxe

/*
build.hxml:

-main Main.hx
-cpp cpp/
-debug
*/

import cpp.UInt8;
import cpp.Int32;
import cpp.Pointer;

@:native("::SomeStruct")
extern class Native_SomeStruct {
    var data:Pointer<UInt8>;
    var dataLength:Int32;

    inline function getDataBytes():haxe.io.Bytes {
        var bdata:haxe.io.BytesData = [];
        cpp.NativeArray.setData(bdata, cast data, dataLength);  // Null Function Pointer
        return haxe.io.Bytes.ofData(bdata);
    }
}
@:native("::cpp::Reference<SomeStruct>")
extern class SomeStructRef extends Native_SomeStruct {}
@:native("::cpp::Struct<SomeStruct>")
extern class SomeStruct extends SomeStructRef {}

@:headerCode("
    struct SomeStruct {
        char *data;
        int dataLength;
    };
")
class Main {
    static function main() {
        var ss:SomeStruct = null;
        ss.dataLength = 0;
        var b = ss.getDataBytes();
    }
}
```
generated code:
```cpp
HX_VARI(  ::cpp::Struct<SomeStruct>,ss) = null();
ss->dataLength = (int)0;
HX_VARI( ::Array< unsigned char >,bdata) = ::Array_obj< unsigned char >::__new(0);
{
    ::cpp::Pointer< unsigned char > inData = ss->data;
    int inElementCount = ss->dataLength;
    HX_VARI_NAME(  ::Dynamic,bdata1,"bdata") = bdata->__Field(HX_("setData",ec,96,e7,07),hx::paccDynamic);
    bdata1(inData->get_raw(),inElementCount);
}
```
Notice the `bdata1` above. It looks like haxe is trying to resolve the NativeArray call through a dynamic and fails when being passed the native pointer returning from `get_raw()`. 

You guys got any idea what might be causing this?

**Comment by dazKind** [comment]
Forgot to add the 3.2 cpp output for comparison, here you go:

```cpp
::cpp::Struct<SomeStruct> ss = null();      HX_STACK_VAR(ss,"ss");
HX_STACK_LINE(39)
ss->dataLength = (int)0;
HX_STACK_LINE(40)
::haxe::io::Bytes tmp;      HX_STACK_VAR(tmp,"tmp");
HX_STACK_LINE(40)
{
    HX_STACK_LINE(40)
    Array< unsigned char > bdata = Array_obj< unsigned char >::__new();     HX_STACK_VAR(bdata,"bdata");
    HX_STACK_LINE(40)
    {
        HX_STACK_LINE(40)
        ::cpp::Int32 tmp1 = ss->dataLength;     HX_STACK_VAR(tmp1,"tmp1");
        HX_STACK_LINE(40)
        bdata->setData(((::cpp::Pointer< unsigned char >)(ss->data))->get_raw(),tmp1);
    }
    HX_STACK_LINE(40)
    tmp = ::haxe::io::Bytes_obj::ofData(bdata);
}
HX_STACK_LINE(40)
::haxe::io::Bytes b = tmp;      HX_STACK_VAR(b,"b");
```

**Comment by Simn** [comment]
@hughsando: I think this one is yours.

**Comment by hughsando** [comment]
I think the 'untyped' is preventing the correct inlining now, whereas 3.2 was less paranoid about what had to be put in a temp.

**Comment by underscorediscovery** [comment]
@hughsando is there a another commit somewhere with a fix? Adding some tests doesn't appear to close the issue on the user end...

**Comment by hughsando** [comment]
Yes - I should have referenced this one that fixed it: https://github.com/HaxeFoundation/haxe/commit/ebe8229281e92d3ec6d2171402b6d4111e36ff9c

And this one that fixes the fix:
https://github.com/HaxeFoundation/haxe/commit/104f4f17e465265bbbb311891c9a3f07ab803113

Problem spanning 2 repos.

**Comment by dazKind** [comment]
Thx Hugh! Glad to report that linc_enet's server/client-test compiles and runs again.
