### ISSUE TITLE
Urgent regression

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#5894]
A lot of code we have start not working with recent haxe change wrt analyzer:

```
function foo() {
     function local(o) {
          for( e in o ) {
             if( ... ) local(e);
          }
      }
      local(...);
}
```

Looking at the output, the compiler introduce local loop vars for the for loop `_g_i` and  `_g_l` (for array pos and length) but then the analyser move them outside of the local() function into the foo() scope, which messes up recursion since our locals should be not be modified !

**Comment by Simn** [comment]
This is fixed, keeping it open to add a test.
