### ISSUE TITLE
[std] Sys.getEnv() should accept a default value as optional parameter

### ISSUE THREAD

**Issue by bschramke** [HaxeFoundation/haxe#5895]
Currently Sys.getEnv() returns null if the requested environment variable was not found. With this you often have to write boilerplate like 
```
var v = Sys.getEnv("MY_VAR");
if (v == null) v = "SomeDefaultValue";
//do something usefull with v
```
If Sys.getEnv() would accept an default value as second optional param, this would reduce to 
```
var v = Sys.getEnv("MY_VAR", "SomeDefaultValue");
//do something usefull with v
```
I know this is not a big deal, but I think it would be a nice improvement.

**Comment by ncannasse** [comment]
It could be misleading and would require to change on all platforms, I think it's not necessary to have this changed.

**Comment by binki** [comment]
Might be better to have a null coalescing feature in Haxe itself…

**Comment by Simn** [comment]
I agree, let's not change the API like this.
