### ISSUE TITLE
Prohibit the use of Void as type parameter

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5899]
```haxe
class Test {
  static function main() {
    var p:Promise<Void> = null;
    // p.then(function() {}); // doesn't compile
    p.then(function(v:Void) {}); // compiles, but Void as value is super weird
  }
}

typedef Promise<T> = {then:(T->Void)->Void};
```

This is weird that `function(){}` is not "Void->Void" but `function(v:Void){}` is.

It is somehow understandable because a type parameters should describe the type of a value, so the compiler is expecting an arugment in the handler function. However, while `Void` by its nature means "no value", it shouldn't really be used to describe a value. Also, that `v:Void` argument leads to weird compiler errors when it is used as a value (say, as function arguments).

What I am suggesting here is to add a type that describe a value of nothingness:

```haxe
@:enum abstract Nothing(Dynamic) {
  var Nil = null;
}
```

**Comment by back2dos** [comment]
Notice that if you have a `Promise<Nothing>`, you're forced to define an argument you'll never handle. Currently `function (v:Void) {}` is `(Void)->Void` while `function () {}` is `Void->Void`. I kind of wish they were the same, although I guess there's no sane way to make it work on many platforms (with enough type parameter voodoo you could easily wind up calling a niladic function with a single `null` parameter, which will throw an exception).

**Comment by kevinresol** [comment]
> Notice that if you have a Promise<Nothing>, you're forced to define an argument you'll never handle.

I understand that, and I feel that is necessary. Because it is impossible to distinguish the existent of argument when the type parameter is still in its generic form.

```haxe
// one must put an argument (x:T) in the callback
function foo<T>(promise:Promise<T>) promise.then(function(x:T) {});
```

**Comment by Simn** [comment]
We have an issue for that here: #3463. Closing this one to avoid fragmentation.
