### ISSUE TITLE
JavaScript target Map.get() implementation returns undefined instead of null for nonexistent keys

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5905]
The [documentation for `Map.get()`](http://api.haxe.org/Map.html#get) states:

> If no such mapping exists, null is returned.

In my experience, this is not the case. I get `undefined`. I thought I could rely on `null` being returned because the documentation said so, but I guess not. For example, given this code:

http://try.haxe.org/#B7B0d

```haxe
class Test {
    static function main() {
        var map = ['y' => 2,];
                   trace('${null}');
                   trace('${map['z']}');
               
        trace(null+1);
                   trace(map['z']+1);
    }
}
```

I get output:

```
null
undefined
1
NaN
```

I thought I could rely on observing the behavior that `null + 1` evaluates to `1`, but because this is only sometimes true on Haxe because sometimes a documented `null` is actually `undefined`, I guess I have to write more code to achieve the same thing ;-).

**Comment by Simn** [comment]
We don't distinguish `null` and `undefined`, and the difference only shows up when tracing, for which there's already an open issue somewhere.

**Comment by RealyUniqueName** [comment]
If i understand correctly, the issue is different results for `null + 1` and `undefined + 1`

**Comment by back2dos** [comment]
The result of `null + 1` is unspecified. On neko it throws. On most static platforms the LHS is coerced to `Int` first, which makes it `0` and thus results in `1`. The simple answer is: don't add `Null<Int>` and `Int`. The compiler might want to warn about that though.

**Comment by binki** [comment]
@Simn You don’t have to trace. You just have to do addition, which on JavaScript will mean you get `NaN` if the underlying JavaScript type is `undefined` whereas if the Map.get() actually returned `null` as documented it would be `1`.

Or if `null + 1` is really unspecified, it’d be great if it were illegal or at least documented. The docs seem to say that on static platforms `Map.get()` would return `0`. It’d be a nice shortcut to take when you want to use the default value if it hasn’t been set yet because calling `exists()` or manually checking `== null` gets verbose. Or if `Map.get()` cannot be fixed to conform to the docs, it’d be nice to at least have a null-coalescing operator or something.
