### ISSUE TITLE
csharp unable to generate correct code for extern accepting a callback

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5907]
Given this csharp:

```csharp
using System;

namespace CallbackConsumer
{
    public static class Class1
    {
        public static string consume(string x, Func<string, string> f)
        {
            return f(x);
        }
    }
}
```

and this extern:

```haxe
@:expose
@:native('CallbackConsumer.Class1')
extern class Class1 {
    public static function consume(x:String, f:(String->String)):String;
}
```

and this client haxe:

```haxe
class Run {
    static function main() {
        trace(Class1.consume('asdf', function (s) {
            return 'x${s}';
        }));
    }
}
```

yields:

```
C:\Users\ohnob\OneDrive\Documents\Visual Studio 2017\Projects\CallbackConsumer>haxe -main Run -cp CallbackConsumer/externs -cs bin/Run.cs -net-lib CallbackConsumer/bin/Debug/CallbackConsumer.dll
haxelib run hxcs hxcs_build.txt --haxe-version 3400 --feature-level 1
src\Run.cs(27,59): error CS1502: The best overloaded method match for 'CallbackConsumer.Class1.consume(string, System.Func<string,string>)' has some invalid arguments
src\Run.cs(27,109): error CS1503: Argument 2: cannot convert from 'Run_main_3__Fun' to 'System.Func<string,string>'
Compilation error
Native compilation failed
Error: Build failed
```

This is because Haxe generates some `Function` class instead of trying to actually pass the delegate around directly. The generated `Function` class does not inherit from `Delegate` because [you can’t do that in csharp](http://stackoverflow.com/q/752466/429091). In csharp code, you would just let the compiler automatically generate a delegate for you instead. For example, if the delegate needs to access state, you can just write it as an instance method of a class and pass `classInstance.MethodName`. If you want to pack RTTI, you can access the object the delegate is attached to via [`Delegate.Target`](https://msdn.microsoft.com/en-us/library/system.delegate.target%28v=vs.110%29.aspx), check if it is Haxe-generated object or not, and go from there.

**Comment by nadako** [comment]
Haxe/C# function objects are not .NET delegates, if you want to hand-write externs for delegates, you need to use e.g. `cs.system.Func_1<String,String>`. Haxe will support passing callbacks for those types directly though.

**Comment by binki** [comment]
As indirectly suggested (to use `-net-libs`’s automatic type parsing), if I update my `CallbackConsumer/externs/Class1.hx` to be:

```haxe
#if cs
typedef Class1 = callbackconsumer.Class1;
#else
extern class Class1 {
    public static function consume(x:String, f:(String->String)):String;
}
#end
```

I still get a failure—from haxe this time:

```
C:\Users\ohnob\OneDrive\Documents\Visual Studio 2017\Projects\CallbackConsumer>haxe -main Run -cp CallbackConsumer/externs -cs bin/Run.cs -net-lib CallbackConsumer/bin/Debug/CallbackConsumer.dll
Type not found : cs.system.Func_2
Run.hx:1: lines 1-7 : Defined in this class
```

**Comment by binki** [comment]
This is one case where Haxe seems to treat `externs` inconsistently with itself. If I build a .net library with a kept type for the code

```haxe
class CallbackConsumer {
    public static function consume(value:String, f:String->(String->Void)->Void):String return 'hi';
}
```

I get C# like this:

```
```

**Comment by nadako** [comment]
> Type not found : cs.system.Func_2
That's probably you're using the default .NET 2.0 dlls which don't have these delegate types. Try adding `-D net-ver=40`.

**Comment by waneck** [comment]
Closing for lack of feedback. Feel free to reopen
