### ISSUE TITLE
visibility modifiers should not be ignored in extern class definitions

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5908]
I understand that in Haxe there is no such thing as private fields. This is of particular importance because the Haxe JavaScript target does not support private fields because it stores all fields in the same namespace when doing class inheritance, so allowing same named but distinct fields in subclasses (which is the point of private fields) [is an unsolved problem on that target](https://groups.google.com/forum/#!topic/haxelang/0zZxmELJuEY). To guard against this (so that Haxe does not have to solve this namespace problem on targets like JavaScript), Haxe does not allow you to declare a function with the same name as a function in a super class unless if you use the `override` keyword. If Haxe did not do this and the JavaScript target were kept unchanged, the developer could accidentally override a super class’s method just by accidentally reusing the same name as a super class’s internal implementation method. Then the developer would be confused as to why the base class started being broken when all the developer did was add a new, non-overriding method to his sub class.

Also, even though Haxe does not have private fields, it does have protected semantics for its fields. This allows a minimal amount of encapsulation. For example, [trying to access a non-`public` field field results in a compilation error](http://try.haxe.org/#9697F).

Thus, I am confused that extern classes do not have the notion of protected (haxe “private”) fields. If an external instantiable class has internal implementation methods, you would want to list those in the extern definition to prevent accidentally overriding them without intending to. Also, you would want to be able to include overridable functions in your extern definition in case if the external class is intended to be subclassed by the consuming code. However, you would still want such functions to get the encapsulation protection that Haxe provides “private” fields by not being allowed to access them except form within subclasses.

For example, say I have this JavaScript:

```javascript
'use strict';

const ExtensibleExternClass = function () {
}

/**
 * Override this to change the greeting. Intended for subclasses only.
 */
ExtensibleExternClass.prototype.coreGetGreeting = () => 'hi';

/**
 * Access the greeting.
 */
ExtensibleExternClass.prototype.getGreeting = function () {
    return this.coreGetGreeting();
};

module.exports = ExtensibleExternClass;
```

and this Haxe:

```haxe
@:jsRequire('./extensibleExternClass.js')
extern class ExtensibleExternClass {
    public function new();

    function coreGetGreeting():String;

    public function getGreeting():String;
}

class SubClass extends ExtensibleExternClass {
    override function coreGetGreeting() return 'yo';
}

class Test {
    static function main() {
        // The usual polymorphic stuff.
        var instance = new ExtensibleExternClass();
        trace(instance.getGreeting());

        instance = new SubClass();
        trace(instance.getGreeting());

        // Should be illegal—private function, encapsulation
        // violation.
        trace(instance.coreGetGreeting());
    }
}
```

By including the protected (“private”) function in the extern, I have enabled it to be consumed as a superclass for `SubClass` which can override the private functions. And if I didn’t write `override`, Haxe would throw an error which would make me realize I’m trying to re-declare a field already in the base class (in case I didn’t intend to override it). However, Haxe allows my code `instance.coreGetGreeting()` to compile even though for non-extern classes Haxe would prohibit me from doing so. Thus, Haxe fails to enforce the encapsulation that it is willing to enforce for “real” types.

I think Haxe should respect visibility modifiers for externs. I didn’t realize that it didn’t right away because [the manual page on externs](http://haxe.org/manual/lf-externs.html) doesn’t document that. I remembered that [the interfaces manual page](http://haxe.org/manual/types-interfaces.html) does mention that everything in an interface is implicitly public. That makes sense to me. But if externs document environment-provided extensible types, then it would be very helpful if the protected/“private” members could be included and marked private to protect the developer from accidentally overriding them, to protect the developer from accidentally violating encapsulation, and to enable the developer to override functions that are meant to be overridden.

**Comment by Simn** [comment]
Can you give a TL;DR of what you're actually reporting with all this text? As far as I'm aware, an explicit `private` on externs is respected.

**Comment by binki** [comment]
> As far as I'm aware, an explicit private on externs is respected.

I did not know that. That is sufficient to achieve what I want and appears to work.

It’d be great if either this inconsistency with non-extern classes were documented. IMO, it’d be better if the compiler were to treat omission of `public` and `private` exactly the same for extern classes as it did for non-extern classes (and that would bring it to behave more inline with the existing manual).

**Comment by Simn** [comment]
I disagree, you want extern fields to be public almost always because they usually describe a public API of sorts, whereas you don't want default public visibility on normal classes.

This is also documented here: https://haxe.org/manual/class-field-visibility.html
