### ISSUE TITLE
use array comprehension body as Iterable<T> (adopt expression generators from Python)

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5909]
I saw #5844 and wondered if this could be added to the list. Or maybe it exists somehow and I’m just missing the syntax on how to use it.

Python allows you to take the body of an array comprehension and use it as a “generator expression”/iterator. See the following interactive session where I examine how it behaves like `Iterator<T>`:

```
>>> y = (2*x for x in range(0,4) if x % 2 == 0)
>>> for i in y:
...     print(i)
...
0
4
>>> for i in y:
...     print(i)
...
>>> y
<generator object <genexpr> at 0x000002672C05B468>
```

As you can see, I can only iterate it once—so it’s an `Iterator<T>` rather than an `Iterable<T>`.

I think that being able to, in haxe, have the code I wrote in [this try](http://try.haxe.org/#04a15) work as one would expect it to would be very helpful for implementing the `Iterable<T>` interface. Or providing a quick way to do a lazy form of array comprehension. Being able to emit an iterator is nice for situations where you’re not sure the whole array will be consumed or even iterated over more than once, so it can save a bit of memory thrashing supposedly.

```haxe
class Test {
    static function main() {
        for (i in iter()) {
             trace(i);
         }
    }

    static function iter():Iterator<Int> {
        return for (i in 0...4) if (i % 2 == 0) 2 * i;
    }
}
```

In fact, after reading [Array Comprehension](https://haxe.org/manual/lf-array-comprehension.html) in the manual, I just assumed that haxe would have this feature. But I’m convinced it doesn’t exist because I can’t find any documentation like “the body of the comprehension is really just an `Iterator<T>` and you can easily build `Iterator<T>`s by just using these expressions in parens”. I’m pretty sure that, in Python, array comprehension is just a thin wrapper around its generator expressions. Instead, in Haxe, the [Iterators manual page](https://haxe.org/manual/lf-iterators.html) just says “With Haxe it is very easy to define custom iterators”—but it would be *soooo* much easier if you could use the array comprehension syntax! :-p .

**Comment by Simn** [comment]
This would have to go through https://github.com/HaxeFoundation/haxe-evolution
