### ISSUE TITLE
Unexpected variable elimination when calling function with side-effects

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5911]
Haxe-3.4 seems to consistently emit incorrect code for this snippet on at least JavaScript and neko. 

http://try.haxe.org/#93297 , using non-var function yields same: http://try.haxe.org/#c6025

```haxe
class Test {
    static function main() {
        var x = 5;
        var advance = function () {
            x++;
        };
        var cur = x;
        advance();
        trace(cur);
    }
}
```

Compilation removes `cur` and replaces `trace(cur)` with `trace(x)` even though I call `advance()` which has side-effects between my assignment to `cur` and access or `cur`.

I get this JavaScript (with analyzers turned off according to try.haxe.org):

```javascript
// Generated by Haxe 3.3.0
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	var x = 5;
	(function() {
		x += 1;
	})();
	console.log(x);
};
Test.main();
})();
```

This even shows up when running it with `haxe -x Test` and `haxe --run Test` with 3.4rc1. I’m not turning on analyzers.

**Comment by Simn** [comment]
Thanks for the very concise report, that's how I like them!
