### ISSUE TITLE
Chinese string constant in .hx file not compile OK when target to windows

### ISSUE THREAD

**Issue by xiangjiabanana** [HaxeFoundation/haxe#5914]
public function new() 
	{
		super();
		
		// Assets:
		// openfl.Assets.getBitmapData("img/assetname.jpg");
		
		textField = new TextField();
		textField.text = "你好Chinese！";
		textField.y = 30;
		textField.x = 30;
		textField.width = 600;
		
		var textFomart:TextFormat = new TextFormat("微软雅黑", 16, 0xffffff, true);
		textField.setTextFormat(textFomart);
		
		Lib.current.stage.addChild(textField);
		
		this.textField.addEventListener(MouseEvent.CLICK , onCLick );		
	}

----------------------------------------------------------------------
my code is like that .I am compile the OpenFL project target to windows C++.
![image](https://cloud.githubusercontent.com/assets/3771519/21543382/af744a3a-ce00-11e6-96c2-9e054ba9e907.png)

$ haxelib list
actuate: [1.8.7]
dox: 1.0.0 [1.1.0]
flixel: [4.2.0]
hxcpp: 3.3.49 [3.4.2]
lime-samples: [3.4.0]
lime: [3.5.2]
nme: [5.6.4]
openfl: 4.5.1 [4.5.2]
polygonal-ds: [1.4.1]
polygonal-printf: [1.0.2-beta]

haxe version :3.2.1
neko version:2.0.0
lime version:3.5.2

I am new to haxe. I don't know how to solve it.

**Comment by nadako** [comment]
That looks like an OpenFL issue regarding fonts, meaning it has nothing to do with Haxe itself. I use cyrillic letters in my haxe code and it works fine, so it's not a compiler fault. Try asking on OpenFL/Flixel forums.
