### ISSUE TITLE
With -d php7 compiler completion can't see user defined php.* namespace

### ISSUE THREAD

**Issue by szczepanpp** [HaxeFoundation/haxe#5921]
I've got custom "php.std" package under which I defined some PHP externs. When using new "-D php7" compiler flag '--display' completion can't see this namespace.

E.g. I've got 'php.std.core.StdClass' extern class and when invoking completion at 'php.std.core.|' I get compiler error 'No classes found in php.std.core'.

I'm using official 3.4.0-RC2 build.

**Comment by RealyUniqueName** [comment]
As a temporary workaround you can rename your `php` directory to `php7` without changing any content in your files.

**Comment by szczepanpp** [comment]
Well, it's good enough for the time being. Thanks!

Btw. this reminded me of '--remap' compilation directive but it didn't work. ;)

**Comment by RealyUniqueName** [comment]
Btw, `StdClass` is included in php7 std lib, so you probably don't need custom extern for it.

**Comment by szczepanpp** [comment]
Yes, I know that - it's simply carried over from an existing source code and I'm planning on adding on to this namespace more externs not covered by Haxe's std. :)

**Comment by RealyUniqueName** [comment]
You can make pull requests with such externs ;)
