### ISSUE TITLE
freezed process (OS Windows)

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#5929]
Hi. When I try to launch external application with GUI and wait until this will be done, and then read result output, then application GUI don't be displayed (can't see these window).

This trouble was detected for **Windows**, when I tried to launch similar code for **Linux, then it works fine**.

Example:

```
import sys.io.Process;

class Main {
	public static function main () {
		var p = new Process("C:/Program Files (x86)/zenity/bin/zenity.exe", ["--info", "--text='qwe'", "--title='asd'"]).stdout.readAll();
	}
}
```

```
import sys.io.Process;

class Main {
	public static function main () {
		var p = new Process("C:/Program Files (x86)/zenity/bin/zenity.exe", ["--info", "--text='qwe'", "--title='asd'"]);
		while (true) Sys.sleep(1); // process zenity.exe exists until this program don't be closed
	}
}
```

Window's task manager will be executed, but main window don't be displayed and tray icon **will be show**
```
import sys.io.Process;

class Main {
	public static function main () {
		var p = new Process("taskmgr", []).stdout.readAll(); // run and wait until process don't be closed
	}
}
```
and notepad don't be displayed, too
```
import sys.io.Process;

class Main {
	public static function main () {
		var p = new Process("notepad", []).stdout.readAll(); // run and wait until process don't be closed
	}
}
```

Target: NekoVM

neko 2.1.0
haxe 3.2.1 and haxe 3.4.0 (both versions have a similar result):
Windows 7 x64 - the target application don't be displayed
Linux Mint 18.1 x64, Linux Mint 18 x64, Ubuntu 16.04 x64 - works fine

Thanks.

**Comment by Simn** [comment]
This will be addressed as part of the new asys API.
