### ISSUE TITLE
Nightly builds (windows, windows-installer, source, linux32) stuck?

### ISSUE THREAD

**Issue by binki** [HaxeFoundation/haxe#5930]
I was looking at http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows-installer/ to see if there was a build with the commit that fixes #5911 in it (just out of curiosity, I don’t need a release rolled for me). I am expecting to see de17354 and newer commits listed there but the latest build I see is e08d018. I can see more recent builds in http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/ , `mac-installer`, `mac`, but not in `linux32`, `windows-installer`, `source`, or `windows`. I have made sure to issue a cache-flushing refresh in my browser, so I’m pretty sure I’m viewing the most up-to-date list.

**Comment by Simn** [comment]
@waneck: please check

**Comment by andyli** [comment]
We have moved to using Travis/AppVeyor for the builds. I don't think we will keep supporting "source" and "linux32" though.

**Comment by jonasmalacofilho** [comment]
@andyli where are the new travis/appveyor builds exported to?

**Comment by andyli** [comment]
build.haxe.org

**Comment by jonasmalacofilho** [comment]
Oh, I thought it could have changed.

Thanks!
