### ISSUE TITLE
Nullsafe . (dereference / property access) operator

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#5933]
I hope this is not a duplicate, but I couldn't find this. Any chance Haxe could support a nullsafe dereference operator? This exists in e.g. Groovy (http://docs.groovy-lang.org/latest/html/documentation/index.html#_safe_navigation_operator) and allows you to write code like:

    def parent_name = person?.parent?.name

Which will result in `parent_name` equal to `null` if `person` is null, or `person.parent` is null (or `person.parent.name` is null). To achieve this in Haxe (and many OOP languages), the code would have to be:

    var parent_name:String = (person != null && person.parent != null ? person.parent.name : null);

And you can surely imagine this can get a bit messy when accessing a particularly deep property. As far as I can see `?.` should not conflict with either the ternary operator or the normal property access operator.

**Comment by nadako** [comment]
Personally, I'd rather have real null-safety than this kind of syntax sugar.
Also there's a macro that analyzes given dot path and transforms it into series of null checks: https://github.com/fponticelli/thx.core#nulls

**Comment by Aurel300** [comment]
Now I also found this issue https://github.com/HaxeFoundation/haxe/issues/1306, which seems more like complete null safety. This issue is maybe redundant, but it is a lot simpler to implement, IMHO realistic as a short-term target.

**Comment by Simn** [comment]
This is subsumed by #1306, for specific operators it would have to go through haxe-evoluation (but I can pretty much guarantee that it would be turned down).
