### ISSUE TITLE
switch(case) issue

### ISSUE THREAD

**Issue by Snky** [HaxeFoundation/haxe#5934]
Hello there, I'm hoping this is the right place to mention this. 
I'm not completely sure if I've found something interesting here...
I probably should go and read the manual...

    trace("hello");

    var a:String = "0";
    var b:UInt = 10;

    switch(a){
        case "0": 
            if (10 == b) break;
            doStuff();
        case "1":
            doStuff();
        case "2":
            doStuff();
    }

    function doStuff():Void{
        trace("pewpew");
    }

    trace("bye");

    output: 
    1. hello
    2. N/A
    3. N/A

"3." should output "bye", but it will not since I used a break - In AS3 (Adobe AIR), the code will still execute after the switch(case), is this possible in Haxe? What can I write to break out of the switch(case) (ignore the doStuff() function) and still execute things after the switch(case)?

The only thing I've thought of, is doing:

    switch(a){
        case "0": 
            if (10 == b) {
                //do nothing...
            } else doStuff();
        case "1": 
    }

But to me, this feels like it's eliminating the whole point of using a switch(case).

**Comment by RealyUniqueName** [comment]
In Haxe [`switch` does not support `break`](https://haxe.org/manual/expression-switch.html). You are probably breaking the outer loop.
Try [guards](https://haxe.org/manual/lf-pattern-matching-guards.html):
```haxe
switch(a) {
    case "0" if (10 != b):
        doStuff();
    case "1":
        doStuff();
}
```
And questions like this should be asked in [google group](https://groups.google.com/forum/#!forum/haxelang) :)
