### ISSUE TITLE
[SOLVED] recpie for target 'haxelib' not found (Linux Fedora 25)

### ISSUE THREAD

**Issue by Buttmoist** [HaxeFoundation/haxe#5937]
Trying to compile Haxe from source. I cloned the git repo as per the instructions. OCaml was installed using OPAM. When entering my haxe directory (located in my /home directory) and running the make command I get these errors:

`/bin/sh: nekotools: command not found`
`Makefile:108: recipe for target 'haxelib' failed`
`make: *** [haxelib] Error 127`

No idea how to move forward.

Note: The haxe package in the Fedora 25 repos (v. 3.2.1) works. Was able to play around and compile an OpenFl project.

**Comment by andyli** [comment]
haxelib depends on neko so you have to install neko first.
I've added this missing info in the building haxe page recently, but we haven't merge it to master yet. It's on staging at the moment: https://staging.haxe.org/documentation/introduction/building-haxe.html

**Comment by Buttmoist** [comment]
Is it best to install neko from my repos or should I get it from git?

**Comment by Buttmoist** [comment]
I installed neko from my repo but I still get an error

`Exception : Neko_error(load.c(357) : Primitive not found : std@elf_update_section_header_for_bytecode(3))`
`Makefile:108: recipe for target 'haxelib' failed`
`make: *** [haxelib] Error 255`

**Comment by andyli** [comment]
I think I've come across that in the past..
Most likely it was due to an old libneko / std.ndll not being removed. Try these:

 * `neko -version` should prints 2.1.0.
 * The output of `ldconfig -p | grep libneko` (or `/sbin/ldconfig -p | grep libneko`) should be something similar to `libneko.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libneko.so.2`. The important part is the `.2` suffix implying Neko version 2.x.
 * `find /usr/lib/ -name std.ndll` should output only 1 line.
 * `readelf -d $(find /usr/lib/ -name std.ndll)` should contain a line similar to `Shared library: [libneko.so.2]`.
 * `echo $NEKOPATH` should output nothing.

**Comment by Buttmoist** [comment]
This is the output of all of those commands

```
neko -version
2.1.0

```
```
ldconfig -p | grep libneko
	libneko.so.2 (libc6,x86-64) => /lib64/libneko.so.2
	libneko.so (libc6,x86-64) => /lib/libneko.so
	libneko.so (libc6,x86-64) => /lib64/libneko.so
```

```
find /usr/lib/ -name std.ndll
/usr/lib/neko/std.ndll
```

```
readelf -d $(find /usr/lib/ -name std.ndll)

Dynamic section at offset 0x1dc60 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libneko.so]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000010 (SYMBOLIC)           0x0
 0x000000000000000c (INIT)               0x6770
 0x000000000000000d (FINI)               0x180a8
 0x0000000000000019 (INIT_ARRAY)         0x21dc48
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x21dc50
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x35b0
 0x0000000000000006 (SYMTAB)             0xb38
 0x000000000000000a (STRSZ)              5904 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x21e000
 0x0000000000000002 (PLTRELSZ)           4104 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x5768
 0x0000000000000007 (RELA)               0x50f0
 0x0000000000000008 (RELASZ)             1656 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x5050
 0x000000006fffffff (VERNEEDNUM)         2
 0x000000006ffffff0 (VERSYM)             0x4cc0
 0x000000006ffffff9 (RELACOUNT)          53
 0x0000000000000000 (NULL)               0x0
```

`echo $NEKOPATH` returned nothing

**Comment by Buttmoist** [comment]
I deleted the `/usr/lib/neko` directory and ran `make` again. It compiled and installed ( I had to run the install as `sudo` ). Everything seems to be working for now. Thank you so much for your help in solving this issue. I appreciate it

**Comment by andyli** [comment]
Glad to hear the problem is solved!
