### ISSUE TITLE
[regression] JSGenApi not working

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5944]
I am at revision 9097448 and [modular-js](https://github.com/explorigin/modular-js) fails with some "Invalid input value" errors while calling the JSGenApi functions (e.g. `setTypeAccessor`, `setCurrentClass`)

It works on 3.2.0 & 3.3.0-rc.1 though.

Code to reproduce: https://github.com/kevinresol/haxe_issues/tree/issue_5944

**Comment by Simn** [comment]
That is almost certainly going to be the same as #5872.

**Comment by kevinresol** [comment]
I would really appreciate if this can be fixed asap.

**Comment by kevinresol** [comment]
Thanks!
