### ISSUE TITLE
[display] no import suggestions for class field type hints

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5950]
```haxe
class Main {
    static var tree:BalancedTree;

    static function main() {}
}
```

Diagnostics should suggest an import for `haxe.ds.BalancedTree` there.

**Comment by Simn** [comment]
Why do you mention class fields in particular? We don't have this feature in general, right?

**Comment by Gama11** [comment]
We do, actually: https://github.com/vshaxe/vshaxe/wiki/Code-Actions#import-actions
