### ISSUE TITLE
[display] trailing dot breaks display

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5951]
For this code, diagnostics reports a suggestion to import `haxe.Int64` as expected:

```haxe
class Main {
    static function main() {
        Int64.add
    }
}
```

But with an added dot after `add`, this is no longer the case:

```haxe
class Main {
    static function main() {
        Int64.add.
    }
}
```

```
Invalid -main : Main does not have static function main
```

**Comment by Gama11** [comment]
Another example for this is goto declaration (`@position`) on `foo.` here:

```haxe
class Test {
    var foo : Int;
    function new() {
         foo.
    }
}
```

(from https://github.com/vshaxe/vshaxe/issues/192)

**Comment by Simn** [comment]
This is not about the dot but about the first expression in a block because we're still in that special state between block and object parsing.
