### ISSUE TITLE
Binding on functions in switch cases inconsistent across targets

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#5952]
So this might be somewhat of a weird bug (can't think of any project that would ever need to use code like this, but nonetheless, here's the problem:

    class Main {
        public static function foo<T>(v:T):T return v;

        public static function main():Void {
            var a = foo;
            doSwitch(a);
        }

        public static function doSwitch<A, T:A->A>(a:T):Void {
            switch (a){
                case _.bind("asdf", "foo") => b: trace(b());
            }
        }
    }

The above doesn't compile with `doSwitch<A>(a:A->A):Void` but like this it does.

On the js target, the above compiles and traces `"foo"`. Not `"asdf"` as expected. The generated js source includes this

    _hx_tmp = a.bind("asdf","foo");

Which is the native javascript bind, meaning "asdf" is bound to `this` in the scope of that function. This can then be used in a variety of ways, including accessing the static fields of a class in a local context, etc etc.

On the cpp, php, and neko targets the above compiles, but produces a runtime error.

Switching on a function seems to be useless in general (because patterns cannot be functions), and the above code should probably detect at compilation time that the .bind with two arguments should only work on T:A->A->A, which, as I understand, should not be able to unify with T:A->A.

**Comment by Simn** [comment]
I know why this happens but I'm not sure how to fix this without breaking everything. The problem is that we monomorph contextual type parameters when typing the pattern, which is necessary for GADT. This causes a field access "bind" on the monomorph, which should obviously not be allowed.

I'll have to check the scope of this issue because it's not going to be just about `bind`.

**Comment by Simn** [comment]
```haxe
class Main {
	public static function main() {
		doSwitch("foo");
	}

	public static function doSwitch<T>(a:T) {
		switch(a) {
			case _.iDontExist() => b:
		}
	}
}
```
