### ISSUE TITLE
[cpp] Lone haxe.Int64.is() call fails to compile

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5955]
This fails to compile (regression compared to 3.2.1):

```haxe
class Main {
	static function main() {
		// haxe.Int64.make(1, 1);
		haxe.Int64.is(0);
	}
}
```

```
./src/Main.cpp(29): error C3083: 'Int64Struct': the symbol to the left of a '::' must be a type
./src/Main.cpp(29): error C2039: 'is': is not a member of 'cpp'
C:\HaxeToolkit\haxe\lib\hxcpp\git\include\cpp/Variant.h(647): note: see declaration of 'cpp'
./src/Main.cpp(29): error C3861: 'is': identifier not found
Error: Build failed
```

But curiously, when you uncomment the `make` call it compiles fine! (Initially I was a bit confused that [this test](https://github.com/HaxeFoundation/haxe/blob/3.4.0-rc2/tests/unit/src/unit/issues/Issue4014.hx#L10) didn't catch it, but that explains it) Seems like using `make()` adds an include or something?

Note that I tested this with 3.4.0-rc.2 instead of dev because I can't compile Haxe right now.

**Comment by ibilon** [comment]
Same on latest haxe dev.
