### ISSUE TITLE
[cpp] weird issue with json and array

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5958]
Someone reported this on haxe gitter:
```haxe
class Main {
    static function main() {
        var arr:Array<Array<Array<Int>>> = haxe.Json.parse("[ [ [0,0], [0,0], [0,0], [0,0] ] ]");
        trace(arr.length); // 1 - ok
        trace(arr[0].length); // 7 - should be 4
        // trace(arr[0][0].length); // segfault :(
    }
}
```

**Comment by s3rcan** [comment]
haxe version newer than 3.2.1 has this issue.

**Comment by hughsando** [comment]
This looks like it might have been the same issue as the serialization one, and been fixed by:
https://github.com/HaxeFoundation/hxcpp/commit/6f68ab592b397e8ad929135e411e801e64fb6a01

**Comment by s3rcan** [comment]
Passes my tests after @hughsando's fix.

**Comment by nadako** [comment]
noice ^^
