### ISSUE TITLE
Json parser of Hex

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#5959]
Hi. Is it possible to parse hexadecimal numbers from json-string with standard parser?

For example:
`var i:Int = haxe.Json.parse('{"background": 0xFFFFFF}').background;`

will except with error:
```
error: Called from ? line 1
error: Called from IhxProgram_8146.hx line 12
error: Called from /usr/share/haxe/std/haxe/format/JsonParser.hx line 83
error: Called from /usr/share/haxe/std/haxe/format/JsonParser.hx line 249
error: Uncaught exception - Invalid char 120 at position 16
error: Error: Command failed with error 1
```

Thanks.

**Comment by nadako** [comment]
JSON standard doesn't have hexadecimal numbers, so this is not a valid JSON string, so no.

**Comment by ncannasse** [comment]
You can use HScript which can parse hexadecimal values
