### ISSUE TITLE
Nightly builds failing since Jan 9, linux64 and mac

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#5962]
Related forum discussion: https://groups.google.com/forum/#!topic/haxelang/5RCtciNtMnI

[Nightly builds](http://builds.haxe.org)

Hmm, I cannot seem to build (Ubuntu, 64-bit) after this set of PCRE updates from about the 9th:

![selection_999 257](https://cloud.githubusercontent.com/assets/2192439/22306283/e0d54fa6-e2fb-11e6-907a-33cdbd1a0025.png)

The error I get is PCRE related:

```
make[1]: Entering directory `/home/jward/dev/haxe/libs/pcre'
ocamlc  -I pcre pcre_stubs.c
ocamlopt -a -o pcre.cmxa  pcre.ml
File "pcre.ml", line 27, characters 26-45:
Error: Unbound value Buffer.add_subbytes
make[1]: *** [pcre.cmxa] Error 2
make[1]: Leaving directory `/home/jward/dev/haxe/libs/pcre'
make: *** [libs] Error 2
```

I can build if I go back to the highlighted commit.

**Comment by RealyUniqueName** [comment]
I'm building latest dev without any issues on Ubuntu 16.04 x64. Did you try `make clean`? Do you have libpcre-dev installed?

**Comment by jcward** [comment]
I do `make clean` and `git submodule update --init --recursive` every time I checkout different revs. I'm on Ubuntu 14.04.

But I was just noting my own experience -- perhaps the nightly build server is experiencing the same issue as I am.

**Comment by Simn** [comment]
> But I was just noting my own experience -- perhaps the nightly build server is experiencing the same issue as I am.

I think they are. Try updating your OCaml version.

**Comment by jcward** [comment]
```
>ocaml -version
The OCaml toplevel, version 4.01.0
```

```
>sudo apt-get update
...
>sudo apt-get install ocaml
ocaml is already the newest version.
```
Hmm... What's your ocaml version, @RealyUniqueName ?

**Comment by Simn** [comment]
https://caml.inria.fr/pub/docs/manual-ocaml/libref/Buffer.html

```
val add_subbytes : t -> bytes -> int -> int -> unit
add_subbytes b s ofs len takes len characters from offset ofs in byte sequence s and appends them at the end of buffer b.
Since 4.02
```

So yes, that's the problem. Maybe we should just modify the bindings after all...

**Comment by RealyUniqueName** [comment]
I'm using Ocaml 4.02

**Comment by Simn** [comment]
Try now...

**Comment by jcward** [comment]
Got the update, slightly different error now:
```
ocamlopt -a -o pcre.cmxa  pcre.ml
File "pcre.ml", line 276, characters 16-38:
Error: Unbound module Bytes
make[1]: *** [pcre.cmxa] Error 2
make[1]: Leaving directory `/home/jward/dev/haxe/libs/pcre'
make: *** [libs] Error 2
```

**Comment by Simn** [comment]
Ah crap, I hadn't realized Bytes is also 4.02...

**Comment by jcward** [comment]
I'll try either building ocaml from source, or installing a ppa.

**Comment by Simn** [comment]
Hold on...

**Comment by Simn** [comment]
Try again please

**Comment by jcward** [comment]
It works! (And I know it's new, the JsGenApi is working, too.) Thanks, Simon!

**Comment by ncannasse** [comment]
Another example that we should stick to 4.01 for at least one more year :)

**Comment by RealyUniqueName** [comment]
http://nooooooooooooooo.com/

**Comment by jcward** [comment]
Yeesh. I tried downloading [ocaml 4.04 source](http://caml.inria.fr/pub/distrib/ocaml-4.04/ocaml-4.04.0.tar.gz) and building / installing was as easy as the typical:

```
./configure
make
sudo make install
```

**BUT**, that left me in an unclean state (with both 4.01 and 4.04 installed?), where my Haxe build was failing with (even after `make clean` / etc):

```
File "as3.mli", line 1:
Error: ../extlib/multiArray.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
make[1]: *** [as3.cmi] Error 2
```

And ocaml `Makefile` doesn't provide uninstall. :(

Thankfully I was able to detect the timestamp of all installed files and [remove them](https://hastebin.com/abiyepelap.bash).

**Comment by Simn** [comment]
That's odd, make clean is supposed to get rid of the cmi files.

**Comment by jcward** [comment]
There were no .cmi files left, but somehow the versions were being crossed during the build.

**Comment by RealyUniqueName** [comment]
You can switch ocaml with opam without building anything manually:
```
$ opam switch 4.02.3
$ opam switch 4.01.0
```

**Comment by andyli** [comment]
For the record, actually I've updated the [build instruction](https://haxe.org/documentation/introduction/building-haxe.html) last week to mention that we need ocaml 4.02+:

> Install OCaml (4.02 or above), camlp4, pcre, and zlib.

**Comment by andyli** [comment]
And if Ubuntu Trusty is the reason to keep OCaml 4.01 compatibility, we will have to support 4.01 for 2 more years since its EOL date is April 2019.

**Comment by RealyUniqueName** [comment]
Please, let's not stick with ancient soft )

**Comment by jcward** [comment]
Huh, ~24 hours later, and I don't notice a new build up on the nightlies server yet...

**Comment by madrazo** [comment]
Hi, I want the Windows nightlies. They sopped updating on Christmas.. Is the issue the change of branch from "master" to "development" ? Thanks 😄

**Comment by waneck** [comment]
They should all be working now. Unfortunately I wasn't able to make mingw static link the pcre libraries, so we now need some dlls to be bundled together. I was able to do it on mac and linux, though
