### ISSUE TITLE
[display] unreliable metadata completion in typedef blocks

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5966]
```haxe
typedef T = { @ var foo:Int; }
```

Meta completion works as expected here (`haxe --display Main.hx@15`).

Comment out the var declaration, and it stops working:

```haxe
typedef T = { @ /*var foo:Int;*/ }
```

```
Error: No completion point was found
```

Note: it also doesn't work _after_ the variable declaration.

**Comment by Simn** [comment]
I think structure parsing in general doesn't resume very well. Let's add this to #5878.
