### ISSUE TITLE
[display] @signature's activeParameter can go out of bounds

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5967]
```haxe
class Main {
    public static function main() {
        foo(1, )
    }

    static function foo(a:Int) {}
}
```

`foo` has one parameter, the max possible `activeParameter` index should be `0`, but here it goes out of bounds:

```
> haxe --display Main.hx@65@signature
{"signatures":[{"label":"(a:Int):Void","parameters":[{"label":"a:Int"}]}],"activeParameter":1,"activeSignature":0}
```

**Comment by Simn** [comment]
I mean, it's not technically wrong... Should we really omit this information? Seems better to let the consumer deal with this.

**Comment by Gama11** [comment]
Using that logic, you'd have to return `activeParameter: 2` for `foo(1,,)` (which doesn't happen right now, it's still 1)?

**Comment by Gama11** [comment]
Although I guess that's more of an issue with two commas, for `foo(1,2,)` it's indeed 2... Still, I didn't really expect that the index could be invalid.

**Comment by Simn** [comment]
There's also the `Rest` case where we don't know how many arguments there are.

But it might indeed make sense to fix the `,,` situation.

**Comment by Gama11** [comment]
Hm.. maybe this "feature" could be used for "Function foo has no second parameter of type Int, want to add it?"-type refactorings... although vshaxe of course still couldn't figure out where exactly to add that parameter on its own, so that maybe would've to be done on the Haxe side anyway.
