### ISSUE TITLE
Autocompletion doesn't work in macro-generated constructor

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#5968]
As the title says, there seems to be a problem with autocompletion for parameters in a macro-generated constructor, especially for anonymous types. Minimal example:

**Main.hx**
```haxe
class Main 
{	
	static function main() {
		// Autocompletion works fine with a normal constructor:
		new AnotherPerson(...
		
		// But autocompletion doesn't work in a 
		// macro-generated constructor with an anonymous type
		new Person(...
		
		var p = new Person({birthYear: 1978, name: "Andreas"});		
		// But it works in a macro-generated method:
		p.ageInYear(...
	}	
}

@:build(AddConstructor.run())
class Person
{
	public var birthYear : Int;
	public var name : String;
}

class AnotherPerson
{
	public var birthYear : Int;
	public var name : String;
	
	public function new(data : { birthYear: Int, name: String }) {
		this.birthYear = data.birthYear;
		this.name = data.name;
	}
}
```

**AddConstructor.hx**
```haxe
import haxe.macro.Context;
import haxe.macro.Expr;

class AddConstructor
{
	static public function run() {
		var fields = Context.getBuildFields();
		
		var constructor = {
			name: 'new',
			doc: null,
			meta: [],
			access: [APublic],
			kind: FFun({
				args: [{
					meta: null,
					name: 'data',
					opt: false,
					type: macro : {birthYear: Int, name: String},
					value: null
				}],
				expr: macro {
					this.birthYear = data.birthYear;
					this.name = data.name;
				},
				params: null,
				ret: null
			}),
			pos: Context.currentPos()
		};

		var ageInYear = {
			name: 'ageInYear',
			doc: null,
			meta: [],
			access: [APublic],
			kind: FFun({
				args: [{
					meta: null,
					name: 'year',
					opt: false,
					type: macro : Int,
					value: null
				}],
				expr: macro return year - birthYear,
				params: null,
				ret: macro : Int
			}),
			pos: Context.currentPos()
		};

		fields.push(constructor);
		fields.push(ageInYear);
		
		return fields;
	}
}
```

I've tested on sublime 3 with the latest Haxe package, and HaxeDevelop 5.2.0.3. For anonymous types, it doesn't work in any of them. In sublime, a simpler type like `macro : Int` works.

**Comment by nadako** [comment]
What kind of autocompletion are you talking about?

Signature completion seems to work, but I can't get `@toplevel` completion, which looks like a bug (it returns the "old" signature response) cc @Simn

**Comment by ciscoheat** [comment]
This is what I get in HaxeDevelop when I'm about to instantiate an `AnotherPerson`:

![anotherperson constructor](https://cloud.githubusercontent.com/assets/130450/22352014/b0f97f44-e41a-11e6-92ed-60090b513507.png)

But for the generated `Person`, nothing at all.

**Comment by ciscoheat** [comment]
Testing the same in Sublime, and I get nothing there! So for a normal class, an anonymous type gets autocompletion in HaxeDevelop, but not in Sublime. Maybe this isn't a compiler problem...? Unfortunately I haven't debugged the autocompletion server, so I don't know how and what to expect.

**Comment by nadako** [comment]
That doesn't look like a compiler issue, since I can get signature completion by invoking haxe manually (i found [another unrelated bug](https://github.com/HaxeFoundation/haxe/issues/5969) though)...

**Comment by nadako** [comment]
For non-macro case, HaxeDevelop probably gets that info without compiler, but it obviously can't do that for macro-generated class.

**Comment by ciscoheat** [comment]
I see, I've posted an issue in the FD repo as well, so maybe it'll get fixed. And now I found https://haxe.org/manual/cr-completion-overview.html which I'll dig into. Thanks. :)
