### ISSUE TITLE
Feature request: Add `implementsDynamic` to `haxe.macro.ClassType`

### ISSUE THREAD

**Issue by Misiur** [HaxeFoundation/haxe#5970]
Currently there is no way if class implements Dynamic. It doesn't show up on `interfaces`, and only way is to check if class has `resolve` method, which is not a reliable way of doing this. That's why I want to ask you to add `#implementsDynamic` (or any other name) to `haxe.macro.ClassType`. 

http://try-haxe.mrcdk.com/#D2f5D

Test.hx
```haxe
class Test {
  static function main() {
    var a = new Foo();
    trace(a.hello);
  }
}

@:build(Macro.build())
class Foo implements Dynamic
{
  public function new() {}
}
```

Macro.hx
```haxe
import haxe.macro.Context;
import haxe.macro.Expr;

class Macro {
  macro static public function build():Array<Field>
  {
    var cls = Context.getLocalType();
    var t = switch(cls) {
        case TInst(_.get() => t, _): t;
      	default: throw 'Nope';
    }

    trace(t.implementsDynamic); //true
    
    return Context.getBuildFields();
  }
}
```

Thank you.

**Comment by Simn** [comment]
That looks like a good opportunity for a pull request.

**Comment by Simn** [comment]
We are going to remove `implements Dynamic` for Haxe 4, so this issue is going to be obsolete.
