### ISSUE TITLE
Create 3.1_bugfix branch to support Flash 8

### ISSUE THREAD

**Issue by demurgos** [HaxeFoundation/haxe#5977]
Hi,
There was [a recent bug between Haxe and the latest version of zlib](https://github.com/HaxeFoundation/haxe/issues/5941).
This issue is now solved and merged to the `development` branch so everything works fine when building the latest Haxe version from source.

My issue is that this issue is still there in Haxe 3.1 and it prevents any compilation of Flash 8 files. I recently inherited from an old code base using AVM1 files so I need to use Haxe 3.1 during the transition (Haxe 3.1 is the last branch support Flash 8 / AVM1). 

I was able to compile my own working version by checking out [the 3.1.3 tag](https://github.com/HaxeFoundation/haxe/tree/3.1.3) and updating the `libs` and `haxelib_src` submodules to their latest version since there seem to be no breaking change. Even if I am able able to compile my own patched version, I still need to work with other persons and it is cumbersome to make it work currently. **It would be great if the zlib fix was backported to the `3.1` branch and if there were patched binaries on the website (`haxe 3.1.4` ?)**.

You can see the way I updated my `3.1` version on [my `3.1_bugfix` branch](https://github.com/demurgos/haxe/tree/3.1_bugfix). I did not submit a Pull Request yet because I do not know very well Haxe's deployment process currently (where to increment the patch version ? where to add the changelog ?).
I've also seen that there seem to be some recent commits still improving things for Haxe 3.1.3 so I am not sure if I was right by forking from the `3.1.3` tag or if I should have used a more recent version. (The recent commits are from last year in the `haxelib_src` submodule so I guess that ensuring that Flash 8 is not completely broken is still a goal even if new features are no longer added)

To recapitulate my issue: would it be possible to provide patched binaries for the 3.1 version of Haxe in order to keep the Flash 8 target working ?

**Comment by Simn** [comment]
This is not worth the effort, especially given that you easily fixed this yourself. I'm willing to have this on a branch, but making a proper release is way too much work for this.

**Comment by demurgos** [comment]
Ok, thank you for your quick reply. Then I'll simply submit a PR so at least it's on the main repo and I'll make sure that the persons I work with are able to compile it.

**Comment by demurgos** [comment]
I don't know exactly how to send a PR for a _new_ branch with Github. I guess it requires write access, so could you pull my `3.1_bugfix` branch ?

**Comment by Simn** [comment]
Does 3.1 really compile with ocamllibs updated like that?

**Comment by demurgos** [comment]
Yes. As I mentioned in my first post, it seems that there even were some commits in the libraries to ensure that it still compatible. I had no issue by simply updating it.

To be extra sure, I just removed Haxe from my system, downloaded my branch and ran `make && sudo make install`: it compiled and installed without any issue. I was able to use it to compile some Flash 8 and Flash 11 files.

I would still recommend you to try, but it should be OK.

**Comment by demurgos** [comment]
I started having some issues with haxelib yesterday. Please wait a bit until adding this branch: I am not sure if it is related to my version or something else.

**Comment by demurgos** [comment]
Hi,
I updated my branch yesterday: I ended up only updating the OCaml libraries (and keeping the old version of Haxelib).

With this branch, I was able to configure Haxe for Flash 8 on Arch Linux and Debian. I sent [the following guide](https://github.com/demurgos/notes/blob/master/tools/languages/haxe/flash8.md) to two other persons and they were able to use Haxelib and build my Flash 8 sources without any issue. They were using Linux Mint and macOS. (So it works on 4 systems, at least for the Flash 8 part but I feel that this is the only reason to use this old version)

**Comment by demurgos** [comment]
@Simn 
I am successfully using [a Docker image](https://github.com/demurgos/docker-haxe/blob/master/haxe-3.1/Dockerfile) using this branch since a month (see lines 69-70). What should I do for you to pull my branch ?

**Comment by demurgos** [comment]
Hi,
It's been a few months now. Both the Github branch and Docker image are still working fine: could it be possible to get the bugfixed 3.1 version into this repo?

**Comment by Simn** [comment]
Thanks, I have pushed your branch to https://github.com/HaxeFoundation/haxe/tree/3.1_bugfix.

**Comment by demurgos** [comment]
Thank you, I am still maintaining some very old Flash files so I first need to convert everything to Haxe 3.1, switch the target language and then update to the latest Haxe version. Even if it's easier to work with the Docker image, I sometime need to reinstall my system or help another developer install it so I'll try to regularly build this branch to ensure that it works: it shouldn't be a burden for you.
Now that this branch is on the official repo I'll be able to update my configurations.
