### ISSUE TITLE
[Flash] Define for Flash Player version?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#5978]
There does not appear to be any defines for which version of Flash you are compiling against.

Having a compiler define does not guarantee the runtime version of Flash, but it would be very helpful for enabling/disabling access to features that require newer SWF versions, without enforcing the newer version.

The newest version of Flash Player on Linux is much older than the versions released elsewhere, so being able to straddle both versions (when it is not important to require the newest version only) would be much easier with this support.

Thanks :smile:

**Comment by ibilon** [comment]
Isn't `-swf-version` doing that? It does complain if you have a version too low for some features.

And if you want to support two versions I guess you'll have to use reflection to check if the feature is available.

**Comment by jgranick** [comment]
You can use `-swf-version` to request a specific version, but you cannot do `Compiler.getDefine ("swf-version")`, based on my testing.

It would be valuable if we could do something like `#if (swf_version >= "11.6")`

**Comment by back2dos** [comment]
[It seems](https://github.com/HaxeFoundation/haxe/search?p=1&q=require&utf8=%E2%9C%93) that `-swf-version` is broken down to a lot of `flash<MAJOR>_<MINOR>` vars, so you'd have to do `#if flash11_6` I guess.

**Comment by jgranick** [comment]
Oh, duh.

Perhaps this should be under `haxe --help-defines` or in the documentation of the website somewhere? :smile:
