### ISSUE TITLE
Enhancement idea: multiple switch arguments

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#5980]
Simple:
```
switch (var1, var2) {
	case (0, 1):
		trace("wuuhhh var1 is 0 and var2 is 1");
	case (0,2):
		trace("wuuhhh var1 is 0 and var2 is 2");
	case (2, 8):
		trace("wuuhhh var1 is 2 and var2 is 8");
	case (3, 8):
		trace("wuuhhh var1 is 3 and var2 is 8");
}
```

could be simple parse to:

if(var1 == 0) {
	if(var2 == 1) trace("wuuhhh var1 is 0 and var2 is 1");
	elseif(var2 == 2) trace("wuuhhh var1 is 0 and var2 is 2");
} else if(var1 == 2) {
	if(var2 == 8) trace("wuuhhh var1 is 2 and var2 is 8");
} else if(var1 == 3 && var2 == 8) trace("wuuhhh var1 is 3 and var2 is 8");

switch case is more readable.
good or bad idea?

**Comment by Simn** [comment]
You can do `switch [var1, var2] { case [pat1, pat2]: }`

**Comment by malublu** [comment]
oh okay thanks. That was fast and helpful.

**Comment by back2dos** [comment]
FYI: http://haxe.org/manual/lf-pattern-matching-tuples.html ;)

**Comment by malublu** [comment]
@back2dos oh sorry i didn't see it.
But hey its was a cool idea :P but haxe was faster ^^

**Comment by back2dos** [comment]
There's no need to apologize. What I really meant to point out is that reading the manual is time well spent.  Who knows what other ideas you might discover? ;)

**Comment by malublu** [comment]
all the rainbow power of haxe ^^.
No really i read the complete manual. But i think i forget the feature.
Thanks ;)
