### ISSUE TITLE
When compiling with cache, string constants seem to become empty

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#5984]
For example, I get this:

```
std/neko/Lib.hx:35: characters 17-68 : Invalid call (expected [VString, VInt], got [VNull, VInt])
std/haxe/macro/Context.hx:587: characters 9-41 : Called from
std/haxe/macro/Context.hx:406: characters 9-26 : Called from
std/haxe/macro/TypeTools.hx:210: characters 78-87 : Called from
```

Which is caused by [`load("follow", 2)`](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Context.hx#L406). I have seen this issue crop up sporadically, also in other places, i.e. `String` instances with `__s` having become `null` for some completely inconceivable reason. IIRC I also saw this happen with strings that I stored in `Context.onGenerate` and tried to access in `Context.onAfterGenerate` but I'm having trouble to produce a concise example now.

**Comment by Gama11** [comment]
I also see this one occasionally, I think it originated somewhere in Lime.

**Comment by back2dos** [comment]
Ok. No Lime on my end. 

I wanted to add that I'm pretty sure the problem existed in 3.2.1 already.

**Comment by ncannasse** [comment]
I have been trying to isolate the issue as well but couldn't find a way. It seems related to some macro context invalidation.

**Comment by nadako** [comment]
I just noticed I'm getting this in my work project too, will try to reduce.

**Comment by waneck** [comment]
I've just got this as well, I'm going to try to reduce it later

**Comment by Simn** [comment]
See https://github.com/HaxeFoundation/haxe/issues/5886#issuecomment-504534559 (for some reason the comment didn't link back).
