### ISSUE TITLE
[c++] Socket issue in 3.4.0 release

### ISSUE THREAD

**Issue by datee** [HaxeFoundation/haxe#5987]
For using UDP, the following works fine in RC2, but throws "unresolved host" in 3.4.0 release version (c++) :
**`socket.bind(new Host("0.0.0.0"), port);`**

(last working version was haxe_2016-12-25_development_e08d018.tar.gz - 25/12/2016)

**Comment by bmfs** [comment]
The same is happening for the sys.net.Socket.

**Comment by datee** [comment]
Hm. This is not working for UdpSocket. Binding to "::" also fails. So is UdpSocket (and socket?) broken in 3.4.0 release? For now if you need udp sockets on c++ you have to roll back to haxe_2016-12-25_development_e08d018. Hope someone can look at this!
