### ISSUE TITLE
[display] "Function body required" error shoud be ignored

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5988]
I think it's safe to lift the "function body required" restriction in completion.

```haxe
class Main {
    static function f(); // created by macro, for example

    static function main() {

    }
}
```

```
haxe --display Main.hx@103@toplevel
```

```
> src/Main.hx:2: characters 11-24 : Function body required
```

I'm not sure how, but I got these errors in the completion server in a class that has a body-less function populated by build-macro.

**Comment by ncannasse** [comment]
I would prefer that we keep it that way. It's not correct syntax to simply forget the function body.

**Comment by Gama11** [comment]
What's the point of an error like this during completion? It basically just prevents it from working. Other similar errors were disabled during display for this reason as well, which makes completion more robust: #5972

**Comment by ncannasse** [comment]
Ah, if it's only disable during completion I don't have any issue with it :)
