### ISSUE TITLE
[display] include macro times in @statistics

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5990]
Originally suggested in https://github.com/vshaxe/haxe-languageserver/issues/25, and I agree that this would be a pretty handy feature to have.

Additionally, it would be nice if this worked even without `--times` and `-D macro-times` explicitly enabled.

**Comment by Simn** [comment]
That requires adding a "collect but not report" mode for --times, but that shouldn't be too hard.

**Comment by Simn** [comment]
I don't want to work on anything specific to statistics display because I don't think anyone actually uses it. This would have to come in as a pull request.
