### ISSUE TITLE
[display] No toplevel completion for iteration var in bracket-less for-loop

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5992]
Consider this scenario where you want to get completion for `foo`:

```haxe
class Main {
    static function main() {
        for (foo in 0...10) {
            |
        }
    }
}
```

Running `haxe --display Main.hx@0@toplevel` works fine and contains what we're after (`foo `).

However, if you remove the brackets, this doesn't work anymore - `foo` is missing from the list:

```haxe
class Main {
    static function main() {
        for (foo in 0...10)
    }
}
```

```
haxe --display Main.hx@76@toplevel
```

Not using `@0` / `|` in the second example since that doesn't seem to work.

**Comment by Simn** [comment]
I think toplevel completion has always required <strike>brackets</strike>braces.

**Comment by Gama11** [comment]
Hm.. I guess it's the same with bracket-less function declarations.

If it's a necessary limitation, it's a bit unfortunate.

**Comment by nadako** [comment]
>I think toplevel completion has always required <strike>brackets</strike>braces.

Apparently you improved something regarding that (#3923).
