### ISSUE TITLE
@:native vs compilation server

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5993]
Main.hx
```haxe
@:native("some")
abstract A(Int) {}

@:native("some")
abstract B(Int) {}
```

```
haxe --wait 6000
```

```
$ haxe --connect 6000 -js main.js --no-output Main
$ haxe --connect 6000 -js main.js --no-output Main
Type name some is redefined from module Main
```

**Comment by nadako** [comment]
Note that using `@:native` with the same name like that isn't wrong, it's actually very useful to represent different parts of the same extern module with separate types (e.g. extern class w/functions + extern abstract enum).

**Comment by nadako** [comment]
Random thought: why do we mess with type path on this level at all? Can't `@:native` be handled by the generator?

**Comment by nadako** [comment]
Looks like name is not restored for abstract declarations, but I don't really understand why they are renamed instead of their implementation classes in the first place.

**Comment by nadako** [comment]
Okay, I *think* I fixed it by simply disabling renaming of abstracts, because they are not restored, and `@:native` is only matters for generated implementation class, and it's already forwarded to it on creation.

This issue is kind of bad because it completely breaks compilation and completion server when there are multiple extern abstracts that point to the same native name, like e.g. I do in hxdefold (to group native constants into nice abstract enums), so I would REALLY appreciate if this one goes into 3.4.1.

**Comment by mockey** [comment]
FYI:
I had this problem (multiple types with the same @:native) some time ago in PHP here:
https://github.com/HaxeFoundation/haxe/pull/5006#issuecomment-204098161
Changing that behaviour was rejected then.
