### ISSUE TITLE
[lua] lua.Table.create doesn't always work 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6001]
The following fails to compile:
```haxe
class Main {
    static function foo() return 1;

    static function main() {
        var t = lua.Table.create({a: foo()});
    }
}
```

Giving this error:
```
src/Main.hx:5: characters 16-44 : __lua_table__ only accepts array or anonymous object arguments
```

This is due to the analyzer trying to be safe and extracting the `hsh` argument into a temp var:
```
[Var hsh(9592):Null<Dynamic<Int>>]
	[ObjectDecl:{ a : Int }]
		a: [Call:Int]
			[Field:Void -> Int]
				[TypeExpr Main:Class<Main>]
				[FStatic:Void -> Int]
					Main
					foo
[Var t(9594):_G.table<Unknown<1>, Int>]
	[Call:_G.table<Unknown<1>, Int>]
		[Local __lua_table__(9593):Null<Array<Int>> -> Null<Dynamic<Int>> -> Unknown<0>]
		[Const:Null<Array<Int>>] null
		[Local hsh(9592):Null<Dynamic<Int>>]
```

I wonder why it does that, because I don't see any reasons to tempvar object declaration, cc @Simn.

**Comment by jdonaldson** [comment]
yeah this is strange, let me check it out.

**Comment by jdonaldson** [comment]
Looks like fusion kicks in and turns anonymous object declarations into locals.  I just need to disable it: https://github.com/HaxeFoundation/haxe/commit/42eed8b04c03658051de233d03d1137a9f1fea05

**Comment by jdonaldson** [comment]
Also, check this test for basic usage :https://github.com/HaxeFoundation/haxe/commit/9047be8cf8b8fdf1e0a5a8f2ca470d23b0371d5a

Note that you can interleave array and anonymous object declarations.  So, any type of simple lua table can be created this way, the arrays are indexed from 1, and the table will carry no overhead from haxe metadata.   It's useful for externs in a few cases.

**Comment by Simn** [comment]
Fusion is the opposite: It moves the local initialization to its usage if possible.

**Comment by jdonaldson** [comment]
Hmm... well should I have used a different analyzer flag?  ``@:analyzer(no_fusion``) cleared it up.
