### ISSUE TITLE
Need Haxe 2.4 Linux Download and Instructions

### ISSUE THREAD

**Issue by Shadowsych** [HaxeFoundation/haxe#6002]
Hi, I'm trying to build a fairly old Haxe program in my Ubuntu 14.04 Linux Machine. Sadly, I cannot build it because I don't know how to get the Haxe 2.4 linux binaries to install on my Ubuntu virtual machine.

Here was the download link:
https://haxe.org/download/version/2.4.0/

I need the version 2.4 because I'm trying to build an old Haxe project that has deprecated methods/functions that are no longer supported in the 3.0+ versions. 

Could anyone tell me how to install Haxe 2.4 onto my Ubuntu 14.04 virtual machine?

**Comment by Simn** [comment]
This is the wrong channel for questions like that, try one of the other community options listed at https://haxe.org/foundation/contact.html.
