### ISSUE TITLE
[display] struct completion without type hint hangs compiler

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6005]
```haxe
class Main {
	public static function main() {
		var foo = {|

		}
	}
}

typedef Struct = {
	integer:Int
}
```

I ran into this when trying to enable struct completion in more places in vshaxe. Invoking field completion in this file seems to hang the compiler. The process stays at around 25-30% CPU usage, never exiting. Memory usage doesn't grow though.

```
haxe --display Main.hx@0
```

However, if a type hint is added to `foo` (`var foo:Struct`), then results appear pretty much instantly:

```xml
<list>
<i n="integer" k="var"><t>Int</t><d></d></i>
</list>
```

**Comment by Gama11** [comment]
Actually, same situation here, so you can already hang vshaxe's Haxe process if you want (struct completion is currently only triggered in method calls)...

```haxe
class Main {
	public static function main() {
		foo({|});
	}

	static function foo(s) {}
}

typedef Struct = {
	integer:Int
}
```

**Comment by nadako** [comment]
Ouch... We might want to disable this feature in haxe-LS, since it's uncertain if there'll be a 3.4.1 update fixing this.

**Comment by Gama11** [comment]
Meh, I doubt people will be happy about features being removed...

**Comment by nadako** [comment]
Well, I doubt people knew about structure field completion (even I always forget about it because it always doesn't work for me :))

**Comment by Gama11** [comment]
Alternatively, we could solve the halting problem to check if Haxe is stuck in an endless loop on the vshaxe side.

**Comment by back2dos** [comment]
> Alternatively, we could solve the halting problem to check if Haxe is stuck in an endless loop on the vshaxe side.

That's generally advisable I think. From my experience the likelihood of such a loops increases with macros ;)

**Comment by nadako** [comment]
I agree, this is a good idea to check if the display request is taking too long and restart the server, I'll create an issue in the haxe-ls repo.
