### ISSUE TITLE
[display] no toplevel completion for types in same package

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6009]
Assume you have a project structure like this:

```
source/
    Main.hx
    foo/
        Foo.hx
        FooTest.hx
```

```
-cp source
-main Main
```

`FooTest` and `Foo` share the same package, so they don't need explicit imports to be able to reference each other. However, when you invoke toplevel completion in `FooTest.hx`, `Foo` is missing:

![](http://i.imgur.com/Pw1Fugd.png)

Using field completion / the fully qualified path, it appears as expected:

![](http://i.imgur.com/QKlLVHq.png)

It _also_ works if `Foo` is imported explicitly:

![](http://i.imgur.com/JpjUlv9.png)

However, of course then diagnostics warns you about the unused import...

**Comment by Simn** [comment]
I don't think this is a special case, just an instance of #7004.

**Comment by Gama11** [comment]
I think there's something more going on here. Checking out this test case again, and making sure `Foo` is in the cache, I get this in toplevel completion in `FooTest.hx`:

![](https://i.imgur.com/EtuJUKV.png)

Effectively, this means we're auto-generating imports that are completely redundant because the type wouldn't need to be imported / is already available. Looks like diagnostics doesn't understand that either, so you don't get an "unused import warning" once the import is added at least.

**Comment by Simn** [comment]
Well, that will be hard to fix because the compiler does actually use these imports. This follows from the resolution order.

We could only detect this for toplevel completion by checking if the unqualified identifier resolves to the same type. I'm not sure this is feasible. Fixing this for diagnostics is not possible.

**Comment by Gama11** [comment]
I'd be ok with only having it fixed for toplevel and not diagnostics, but fixing it for toplevel seems rather important.

**Comment by Simn** [comment]
I'm tempted to argue that such imports are good practice. Though I'd probably argue that mostly because I don't want to fix it.

**Comment by Gama11** [comment]
How are they good practice? That you don't need to import the modules explicitly here is a Haxe feature. I just see this as bad IDE support making you write your code differently, which is always super-annoying.

It's a bit like having to explicitly type-hint / declare iterator variables like this back in FlashDevelop because it doesn't understand type inference properly (and shadowing, but that's what made the workaround work x)). I think they recently fixed that, but still:

```haxe
var something:Something;
for (something in listOfSomethings) {}
```
