### ISSUE TITLE
[display] "unnecessary property declaration" diagnostic for private (default, null)

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6010]
Would be nice if diagnostics reported a warning for cases like these...

```haxe
private var foo(default, null):Int;
```

...where there isn't really any point to having the `(default, null)` because it's `private` / only writable within the class anyway.

I guess it might make sense to not show a warning in case the property is required by an interface (although it would be quite silly for an interface to do that in this case).

**Comment by Simn** [comment]
I think this is more suited for checkstyle.

**Comment by Gama11** [comment]
Fair enough. Or maybe a hxparser-based diagnostics analyzer in haxe-languageserver.
