### ISSUE TITLE
Broken bulk var instantiation?

### ISSUE THREAD

**Issue by championchap** [HaxeFoundation/haxe#6011]
Hey all, 

A bit worried this might be a silly question seeing as it's such a simple looking thing, but I think assigning variables in a group is broken? Every time I try this I get "Local variable a used without being initialized". 

```haxe
var a, b = 2; 
trace(a, b); // 2,2 expected 
```
As seen here: https://haxe.org/manual/expression-var.html

I've tried it on TryHaxe which says it's running 3.4.0.

My system is running Haxe 3.2.1 on a x64 Xubuntu VirtualBox install.

**Comment by Simn** [comment]
This is parsed as `(a),(b = 2)` and is working as intended.

**Comment by championchap** [comment]
@Simn so it's the docs that are wrong?
If so I'll go open an issue on the HaxeManual.

**Comment by nadako** [comment]
Well, docs mean "variable e initialized to value 2", not "d", but I can see it can be confusing, so maybe we should reword that indeed.
