### ISSUE TITLE
Allow optional arguments in implicit casts, especially `haxe.PosInfos`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6017]
I often find myself writing this:

```haxe
abstract Foo {
  @:from static function fromBar(bar:Bar) return ofBar(bar);
  static public function ofBar(bar:Bar, ?extra:Whatever) { ... }
}
```

It would be nice to just declare `fromBar` as public with an optional argument. Not being able to do that is just a little inconvenience. What I'm really after though is this:

```haxe
abstract Foo {
  @:from static function fromBar(bar:Bar, ?pos:haxe.PosInfos) { ... }
}
```

That way, when a `Foo` is implicitly created from a `Bar` I can capture some contextual information that would be very helpful when debugging.

**Comment by grepsuzette** [comment]
Getting this one up too.
Asked something like that on gitter today:

    in a abstract @:from method it's impossible to use ?pos:PosInfos
    (Error: @:from cast functions must accept exactly one argument).
    Is it then impossible to gather the caller?
    ( For debugging purpose I would like to transmit a pos to something inside
    as in @:from static function fromFoo(f:Foo) { someCall(pos); }

Abstract are very powerful but without PosInfos in @:from methods it can sometimes become difficult to debug things, so I too would love to see ?pos:PosInfos usable there
