### ISSUE TITLE
[display] no field completion for type-inferred function argument

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6020]
```haxe
class C {
    function g(s) {
        (s : String);
        s.|
    }
}
```

```
$ haxe --display Main.hx@0
<list>
</list>
```

however `@type` and `@toplevel` queries report tha `s` is a `String`.

**Comment by Simn** [comment]
Is that a `-D no-copt` situation?

**Comment by Gama11** [comment]
Yes, enabling `-D no-copt` fixes it.

**Comment by nadako** [comment]
Oh man. Does this flag bring anything but problems? Should we enable hardcode it into vshaxe?

**Comment by Simn** [comment]
This should be a simple fix in optimizer.ml `optimize_completion_expr`. Try adding a case for ECheckType that sets `typing_side_effect := true`.

**Comment by nadako** [comment]
It wasn't a typecheck originally, but an assignment.
