### ISSUE TITLE
Feature request: @:genericBuild on a function

### ISSUE THREAD

**Issue by ktimothy** [HaxeFoundation/haxe#6023]
I would be great to have such feature. Though there are ways to achieve similar behavior (see http://www.kevinresol.com/2016-11-23/genericbuild-function-haxe/), they are not straightforward.

**Comment by nadako** [comment]
If you have an idea of how you think this should work, I'd suggest you start drafting a [formal proposal](https://github.com/HaxeFoundation/haxe-evolution), otherwise this is not an actionable issue.

**Comment by nadako** [comment]
@Simn I remember we (or was it just you?) talking about method-level build macros, do you still think that would work?

**Comment by Simn** [comment]
I don't really see how that would work on fields. What would that macro return, where would the field be added, what about reflection etc.
