### ISSUE TITLE
[display] unused code diagnostics for while / if / etc expressions

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6025]
```haxe
class Main {
	public static function main() {
		true;

		if (Math.random() > 0.5) true;
		while (true) true;
	}
}
```

There's only an unused code diagnostic being reported for the lone `true` on method body level here, but not for the other two cases:

![](http://i.imgur.com/cojHIVM.png)

**Comment by Simn** [comment]
They aren't exactly unused in the sense that if you remove them, your code no longer compiles. They are still being removed from the actual output, which I find a better solution than giving a warning.

**Comment by nadako** [comment]
Well the value is unused so an IDE could provide a "change to empty block" feature or something, but yeah, this requires more compiler services interop design.

**Comment by Gama11** [comment]
This wasn't about the lack of braces specifically, the following doesn't report anything for me either:

```haxe
while (true) {
    true;
}
```
