### ISSUE TITLE
[api] broken "View Source" links for some java / cs types

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6027]
For instance:

- http://api.haxe.org/java/lang/Class.html
- http://api.haxe.org/java/lang/AbstractStringBuilder.html
- http://api.haxe.org/java/lang/IllegalAccessException.html
- etc

It might just be that there _is_ no source to show for these (@ibilon noted that these might be from a `.jar`), but in that case, the `View Source` button probably shouldn't be visible.

**Comment by Gama11** [comment]
C# has the same issue:

- http://api.haxe.org/cs/system/collections/ArrayList.html
- http://api.haxe.org/cs/system/collections/IList.html
- ...

**Comment by Simn** [comment]
I don't think that's a Haxe issue?

**Comment by Gama11** [comment]
Is there any way for dox to tell that there's no source available for these? If these are indeed from `.dll` / `.jar` files, it might need some flag in the xml.

**Comment by Simn** [comment]
Are you saying it has a valid file entry in the XML for these?

**Comment by Gama11** [comment]
`cs.system.collections.IList` has the following:

```
file="C:\HaxeToolkit\haxe\lib\hxcs/3,2,0/netlib/net-20/mscorlib.dll @ cs.system.collections.IList"
```

For Java, the format seems slightly different (no spaces around that `@`).

```
file="C:\HaxeToolkit\haxe\lib\hxjava/3,2,0/lib/hxjava-std.jar@java/lang/CharSequence.class"
```

I guess dox could analyze that and make sure `file` ends with `.hx`? Doesn't seem particularly elegant, but should work...

**Comment by Simn** [comment]
I find that elegant enough. :P
