### ISSUE TITLE
js.Promise.Thenable should return Thenable

### ISSUE THREAD

**Issue by wiggin77** [HaxeFoundation/haxe#6028]
haxe/std/js/Promise.hx
```haxe
typedef Thenable<T> = {
	function then(resolve:T->Void, ?reject:Dynamic->Void):Void;
}
```
I believe this should return a `Thenable` instead of `Void` to match the underlying JavaScript Promise, and to allow chaining.

**Comment by nadako** [comment]
Note to self: read on how js promises work and make those externs as complete as possible.
