### ISSUE TITLE
Unbound variable, capturing this in a closure initialized in the class body and stored in a property

### ISSUE THREAD

**Issue by feeddageek** [HaxeFoundation/haxe#6030]
When creating a closure that access class members from the class body the following error occurs
```
Unbound variable, please report this
{
        v_id = 100792;
        v_name = `this;
        v_type = Main;
        v_capture = false;
        v_extra = None;
        v_meta = [];
}
File "src/optimization/analyzerTypes.ml", line 221, characters 3-9: Assertion failed
```
If the closure is created inside a method of the class or if it does not interact with the instance fields or methodes, everything work perfectly
```haxe
class Exemple{
    public var ok(default,null):Void->Void;
    public var stillOk(default,never) = function(){return function(){trace("This works.");};}();
    //public var notOk(default,never) = function(){return function(){trace("This does not work. "+this);};}();

    public function new(){
        ok = function(){return function(){trace("This works. "+this);};}();
    }
}
```

Honestly, I'm not sure this bug is worthy of correction (I'm not even sure it's really a bug since what I'was trying to do stunk of bad code) but the error message asked nicely and I was able to reproduce it, so i reported it anyway.

**Comment by Simn** [comment]
Interesting, I think the compiler is supposed to yell at you for the usage of `this` there, but for some reason doesn't do that and dies instead.

**Comment by ncannasse** [comment]
@Simn it should allow "this" since we allow local vars, but it should be the one inside the "new" scope

**Comment by Simn** [comment]
I'm confused, didn't we want to disallow `this` access for member field inits due to ordering concerns?

**Comment by jcward** [comment]
Note, commit 36edba4 made this code invalid:

```
  private var self = this;
```

This currently works on (an older compiler on) try.haxe.org: https://try.haxe.org/#80BC7

I'm trying to imagine the order concerns around this, member vars, and static member vars -- and why static vars are treated differently than vars, they [can reference each other](https://try.haxe.org/#eEf73) -- but perhaps someone could enlighten me.

**Comment by Simn** [comment]
I don't really remember, but when we originally added the feature Nicolas insisted on this limitation. I'll try to find the discussion about that.
