### ISSUE TITLE
Unify structure with one that requires more fields if all of them are read only and optional.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6031]
Basically I would like [this](http://try.haxe.org/#16840) to compile:

```haxe
class Test {
  static function main() {
    var l:Less = { foo: 42 };
    var m:More = l;
  }
}

typedef Less = {
  var foo(default, never):Int;
}
    
typedef More = {
  @:optional var foo(default, never):Int;
  @:optional var bar(default, never):Int;    
}
```

The compiler tells me `Less should be More` but I would argue that in this case `Less` indeed *is* `More` ;)

**Comment by Simn** [comment]
If I recall correctly, @ousado has shown that this is not sound.

**Comment by back2dos** [comment]
Upon second though I realize now that this requires special treatment on some static targets when the object is actually an instance. Right now it can just blow up: http://try.haxe.org/#Fd4A1 - that said, an additional check could be performed before accessing `@:optional` fields through anonymous types. That makes this a bigger deal than I initially though, but short of a counter example I still think it would be a good idea to add eventually.

**Comment by ousado** [comment]
Yes, it's not sound - the following would compile:
```haxe
class Test {
  static function main() {
    var m2:More2 = {foo:1,bar:"2"};
    var l:Less = m2;
    var m:More = l;
  }
}

typedef Less = {
  var foo(default, never):Int;
}
    
typedef More = {
  @:optional var foo(default, never):Int;
  @:optional var bar(default, never):Int;    
}
typedef More2 = {
  var foo(default, never):Int;
  var bar(default, never):String;    
}
```

**Comment by back2dos** [comment]
Well, I suppose it's generally a fair question whether `More2` and `More` should unify only in one direction (going from non-optional to optional) in the first place, but I see now that my request would require quite a few changes on anonymous types. Thanks for the info ;)
