### ISSUE TITLE
[php] Web.getPostData inconsistent behaviour in 3.4

### ISSUE THREAD

**Issue by Talaween** [HaxeFoundation/haxe#6033]
send a POST request using application/json, then on php server code use Web.getPostData() it will attach a null to the beginning of the json string, for example try to send {"username":"test"} , at server the method returns:  null{"username":"test"} 
this prevents correct parsing of the json string
in Haxe 3.3 this issue is not there. only appeared on 3.4

**Comment by nadako** [comment]
Thanks for the report!

I wonder how this worked before, since it initialized `data` with `null` and then does `+=` which seems totally wrong: https://github.com/HaxeFoundation/haxe/blob/development/std/php/Web.hx#L252-L255.

@RealyUniqueName could you look into this?

**Comment by RealyUniqueName** [comment]
Because compiler now replaces `data += value` with `data = data + value`. And php generator doesn't take into account `null` for `+=` operations.

**Comment by RealyUniqueName** [comment]
Fixed in 0cb0098f989e5dc58169de76f4bcfbbbc422e48f
