### ISSUE TITLE
Static extensions shadow abstract's own variables

### ISSUE THREAD

**Issue by MrCoft** [HaxeFoundation/haxe#6036]
Code example:
```haxe
using Lambda;
class Test {
    static function main() {}
}
class TYPE {
    public function new() {}
    public function iterator():Iterator<Int> return new IntIterator(0, 1);
}
abstract ABSTRACT(TYPE) {
    public var array(get, never):Bool;
    function get_array() return true;
    
    public function new() {
        this = new TYPE();
        $type(array);
        $type(this.array);
    }
}
```

Output:

```haxe
Test.hx:15: characters 14-19 : Warning : Void -> Array<Int>
Test.hx:16: characters 14-24 : Warning : Void -> Array<Int>
```
It is the Lambda.array<A>(it:Iterable<A>):Array<A> function.
As a result, the abstract can't access its own variable in its definition.

I'd have to downgrade to confirm this but I think I started getting these bugs of getters not working with the 3.4 version.

**Comment by Simn** [comment]
Please note that `this.array` still resolves to `Lamda.array` because `this` resolves to `TYPE`, not `ABSTRACT`.
