### ISSUE TITLE
[lua] Type.enumParameters doesn't work

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6037]
```haxe
class Main {
    static function main() {
        trace(Type.enumParameters(haxe.ds.Option.Some(10)));
    }
}
```

```
main.lua:116: attempt to call method 'slice' (a nil value)
```

I wonder how this is not caught by our unitstd tests [here](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/Type.unit.hx#L156-L160).

**Comment by jdonaldson** [comment]
There's an untyped argument on that Array.slice method.  The compiler drops it through dce.  I have to be extra careful with Lua since Arrays aren't native.

**Comment by jdonaldson** [comment]
Here's the way I'm avoiding allocation now : https://github.com/HaxeFoundation/haxe/commit/db3ce7ecbdb44361c6c9becbdfeb96b988f8d335
