### ISSUE TITLE
[lua] Lua imports via Haxe externs and @:luaRequire are not in scope when main() is called

### ISSUE THREAD

**Issue by zajrik** [HaxeFoundation/haxe#6045]
Before I start, I should point out that I can simply solve the problem by moving the generated `require`s and package table declarations higher in the generated Lua file. However, this is obviously not optimal and should be left to the compiler itself.

When running code defined by an extern I've written:
```haxe
package oc;

@:luaRequire('robot')
extern class Robot
{
...
```
And then importing the package and utilizing it:
```haxe
import oc.Robot;

class Main
{
	public static function main(): Void
	{
		Robot.turnLeft();
...
```
I get the following error
```bash
lua: main.lua:109: attempt to index global 'oc' (a nil value)
stack traceback:
        main.lua:109: in function 'main'
        main.lua:337: in main chunk
        [C]: in ?
```

My `main()` function is defined on line 108 in `main.lua`, the code for the required module is called on line 109, and the package table and import
```lua
local oc = {}
oc.Robot = _G.require("robot")
```
are not defined until lines 322 and 323, respectively.
Local variables are not hoisted and thus not in scope as globals are, despite being declared before `main()` is actually called.

I imagine a good place to put imports to solve this would be around where the different Haxe types are defined, like:
```lua
local Array = _hx_e()
local Main = _hx_e()
local String = _hx_e()
local Std = _hx_e()
local Util = _hx_e()
local haxe = {}
...
local oc = {}
oc.Robot = _G.require("robot")
```

**Comment by jdonaldson** [comment]
Thanks for the overview.  You're right, the declaration for this belongs in the type definitions.  This should be fixed with : https://github.com/HaxeFoundation/haxe/commit/aa9dd364f73ab6c2207b2929f34e3a5b4035382b
