### ISSUE TITLE
Collection of samples for a novice users

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#6053]
Hi. As the study of Haxe I created and published a [little collection](https://github.com/r3d9u11/haxe-basics) of samples for a novice users. Hope this can be useful for someone.

**Comment by Simn** [comment]
That is nice, but not a Haxe-issue. See if you want to contribute something to https://github.com/HaxeFoundation/code-cookbook!

**Comment by r3d9u11** [comment]
@Simn sorry for that, thanks for notice and this link!
