### ISSUE TITLE
[php] FileSystem.stat() fails on directories

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#6057]
When using `FileSystem.stat()` on directories with the old PHP target. It fails with the following exception:

`'HException' with message 'fopen(<DIRECTORY_NAME>): failed to open stream: Permission denied (errno: 2)`

**Comment by RealyUniqueName** [comment]
This is already fixed in 0264e9eecdbb3690808db5e0cc0e00d8616ecb49
