### ISSUE TITLE
`to_complex_type` messes up field access on anonymous types

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6063]
Basically every `FieldKind.FVar` becomes a `FieldType.FVar` (even when it should become `FieldType.FProp`). Note that the [pure Haxe implementation handles it propertly](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/TypeTools.hx#L44) while [the version in the compiler is just a hint to naive](https://github.com/HaxeFoundation/haxe/blob/875ad19432abc2cec6b345cc49a880f5c7f3c98a/src/typing/type.ml#L2464). 

[Here](http://try-haxe.mrcdk.com/#615eD)'s a minimal example:

```haxe
import haxe.macro.Context;
import haxe.macro.Expr;
using haxe.macro.Tools;

class Macro {
  macro static public function roundtrip(e:Expr) {
    var type = Context.typeof(e).toComplexType();
    return macro @:pos(e.pos) ($e : $type);
  }
}

class Test {
  #if !macro
  static function main() {
    var o:{ var x(default, null):Int; } = cast {};
    Macro.roundtrip(o);//<--- Inconsistent setter for field x : null should be default
  }
  #end
}
```

**Comment by RedHairHead** [comment]
It also messes up types of arguments for arrow functions, making all arguments non-optional and unnamed.

Haxe 4.2.1
```haxe
import haxe.macro.Context;
import haxe.macro.Printer;

using haxe.macro.Tools;

class Macro {
	public static macro function printType() {
		var t = Context.getExpectedType().toComplexType();
		trace(new Printer().printComplexType(t));
		return macro null;
	}
}

class Main {
	#if !macro
	static function main() {
		var foo:(?a:String) -> Void = Macro.printType(); // String -> StdTypes.Void
	}
	#end
}
```

**Comment by back2dos** [comment]
I wonder if we should simply deprecate `toComplexType` in favor of [`storeType`](https://github.com/HaxeFoundation/haxe/issues/6770), because the former is incorrect (which is fixable, but only to a point) but also inherently slower.

**Comment by Simn** [comment]
I agree `storeType` should be preferred, but we should fix this regardless.

**Comment by Simn** [comment]
Interestingly, the pure Haxe implementation actually turns everything into `FProp`. Given that `FVar` is essentially just the special case `FProp(default, null)`, I suppose that makes sense.
