### ISSUE TITLE
[display] @signature completion and unnamed arguments

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6064]
Haxe returns the following for `@signature` completion for callback types (and thus empty argument names):
```
"{"signatures":[{"label":"(:Int, :Int):Void","parameters":[{"label":":Int"},{"label":":Int"}]}],"activeParameter":0,"activeSignature":0}"
```

Not technically wrong, but looks ugly and makes VS Code go crazy:
![](http://i64.tinypic.com/30sk5ci.png)

Before `@signature` was a thing, I solved that by adding generic `a`,`b`,`c`,etc. names to unnamed arguments. Maybe we should do the same for `@signature` too. Thoughts? @Simn @Gama11

**Comment by nadako** [comment]
I guess I'll work this around by injecting argument names on haxe-languageserver for now.

**Comment by Simn** [comment]
I don't think Haxe should invent names here. It's up to the IDE how it wants to display this case.

**Comment by nadako** [comment]
In that way I'd argue that the output should be properly structured instead of spitting out weird concatenated strings, which is not much better than we had before format-wise.

**Comment by nadako** [comment]
People really shouldn't have to do this: https://github.com/vshaxe/haxe-languageserver/commit/942470dc08509e6b0641093e09e26ff5dc4364db#diff-bdfa664c96d8ab764d530048de8ed45dR47

**Comment by Simn** [comment]
What's wrong with `s.charAt(0) == ":" ? invented + s : s`?

**Comment by Gama11** [comment]
That works for the parameters, but not the label:

```
"label":"(:Int, :Int):Void"
```

**Comment by Simn** [comment]
Yes I agree that requires more structure. If only we had JSON output for types...
