### ISSUE TITLE
[display] signature completion should only work for callable things

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6068]
It's confusing that these work, since you can't "call" a class or a structure:

![](http://i.imgur.com/W1MxLb1.png)

![](http://i.imgur.com/UYdT1Fa.png)

![](http://i.imgur.com/gGEaPOr.png)

**Comment by nadako** [comment]
Looks like we need to do some filtering [here](https://github.com/HaxeFoundation/haxe/blob/d3955c6796ab8e400dc7a36e3713b9a80d60261a/src/typing/typer.ml#L3710), but I'm not sure what exactly should we match for. `TFun` and `@:callable abstract`?

**Comment by nadako** [comment]
Oh, there's already `follow_with_callable`, so it's probably safe to do that and then check if it's TFun \o/
