### ISSUE TITLE
[js] source maps vs array comprehension

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6069]
```haxe
class Main {
	public static function main() {
		trace([for (i in 0...10) {
			var r = Math.random();
			var f = Math.random();
			r + f;
		}]);
	}
} 
```

Setting breakpoints on the `var r` and `var f` lines works fine, but not on the final `r + f`.

This is how VSCode's Node debugger behaves with this:

![](http://i.imgur.com/T62IFIP.gif)

The breakpoint is moved to line 3 when launching the debugger.

Checking with the [source map visualizer](https://sokra.github.io/source-map-visualization/), it looks like the issue may be that the "real" line starts with `_g.push()`, which maps back to line 3:

![](http://i.imgur.com/leYR9Qp.png)

`-D no-analyzer` doesn't make a difference (doesn't change how the generated code looks, either)

**Comment by RealyUniqueName** [comment]
Fixed in the latest dev

![img](https://i.imgur.com/6YNs3Zh.png)

But now a breakpoint being placed at line 3 jumps to line 6 on debug :)
```
 47- 145 	    TVar _g
 134- 139 	      TArrayDecl
  48- 144 	    TBlock
  48- 144 	      TVar _g1
  58-  62 	        0
<...>
 134- 139 	          TCall
 134- 139 	            TField push
 134- 139 	              TLocal _g
 134- 139 	            TBinop +
 134- 135 	              TLocal r
 138- 139 	              TLocal f
```
That `TArrayDecl` position should be `47- 145`

**Comment by Simn** [comment]
Is that with or without `-D analyzer-optimize`?

**Comment by RealyUniqueName** [comment]
Without. 
Here is with analyzer:
```
  47- 145 	    TVar _g
 134- 139 	      TArrayDecl
  48- 144 	    TBlock
  48- 144 	      TVar _g1
  58-  62 	        0
  48- 144 	      TVar _g2
  62-  75 	        TCall
  62-  72 	          TField random
  62-  65 	            TTypeExpr Std
  73-  74 	          3
  48- 144 	      TWhile
  48- 144 	        TParenthesis
  48- 144 	          TBinop <
  48- 144 	            TLocal _g1
  62-  75 	            TLocal _g2
  48- 144 	        TBlock
  48- 144 	          TUnop ++
  48- 144 	            TLocal _g1
 134- 139 	          TCall
 134- 139 	            TField push
 134- 139 	              TLocal _g
 134- 139 	            TBinop +
  90- 103 	              TCall
  90- 101 	                TField random
  90-  94 	                  TTypeExpr Math
 116- 129 	              TCall
 116- 127 	                TField random
 116- 120 	                  TTypeExpr Math
```

**Comment by RealyUniqueName** [comment]
But with analyzer breakpoint on line 6 (`r + f`) also works fine

**Comment by nadako** [comment]
I wonder if we could/should use these position output for tests, althought it might be annoying because any change to TAST will break them.

**Comment by RealyUniqueName** [comment]
We need to find a way to test them without hardcoding exact numbers. 
Maybe read an initial position with a build or expression macro and then find a corresponding expression in typed syntax tree and compare positions.

**Comment by nadako** [comment]
Right, it should be somewhat similar to display tests, I guess.
