### ISSUE TITLE
Field#doc and ClassField#doc are always null?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6072]
Revision: aebea96

```haxe
// Main.hx
@:build(Macro.printDoc())
class Main {
	
	/**
	 *  My nicely written doc
	 */
	static function main() {
		
	}
}

// Macro.hx
class Macro {
	public static function printDoc() {
		for(f in haxe.macro.Context.getBuildFields()) trace(f.name + ': ' + f.doc);
		return null;
	}
}
```

and it prints `main: null`. Am I using it incorrectly or what?

**Comment by RealyUniqueName** [comment]
You need `-D use-rtti-doc`

**Comment by kevinresol** [comment]
Oh well, that works.
But I think it would be nice to include that inside the said fields' doc...

**Comment by nadako** [comment]
I think that's performance-related. You don't need documentation for building most of the time, so compiler doesn't spend time on parsing/handling it, so this requires explicit flag.

**Comment by Simn** [comment]
I'm pretty sure it's more memory-related.

**Comment by kevinresol** [comment]
Well I think this should be at least mentioned in the doc field itself. This would be easier for users to know that such a meta exists.
