### ISSUE TITLE
[cs] Overriding methods of properties with (get,never) access, generate method without "virtual" keyword

### ISSUE THREAD

**Issue by dkolyesnik** [HaxeFoundation/haxe#6073]
Overriding methods of properties with (get,never) access, generate method without "virtual" keyword causing an error in C#:
"cannot override inherited member `A.a' because it is not marked virtual, abstract or override"
Also there other issues with properties
In case of (get, set) "virtual" keyword is added but for some reason private _b becomes public _b in C#. But at least no errors
In case of adding @:isVar combined with @:property, variable is generated but property is not generated at all in class implementing method

Haxe:
```
interface I {
	@:property
    var a(get, never):Bool;
	@:property
	var b(get, set):Bool;
	@:property
	var c(get, set):Bool;
}

class A implements I {
	public function new(){}
    @:property
	public var a(get, never):Bool;
	function get_a():Bool{
        return true;
    }

	@:property
	public var b(get, set):Bool;
    var _b:Bool;
	function get_b():Bool{
		return _b;
	}
	function set_b(value:Bool):Bool{
		return _b = value;
	}
	@:property
	@:isVar
	public var c(get, set):Bool;
	function get_c():Bool{
		return c;
	}
	function set_c(value:Bool):Bool{
		return c = value;
	}
}

class B extends A 
{
    override function get_a():Bool {
        return false;
    }
	override function get_b():Bool{
		return false;
	}
	override function get_c():Bool{
		return false;
	}
}
```
C#:
```
public interface I {
    bool c { get; set; }
    bool b { get; set; }
    bool a { get; }
}
public class A : global::I {
    public A() {
    }
    public virtual bool b {
        get { return _get_b(); }
        set { _set_b(value); }
    }
    public bool a {
        get { return _get_a(); }
    }
    private bool _get_a() {
        return true;
    }
    public bool _b;
    private bool _get_b() {
        return this._b;
    }
    private bool _set_b(bool @value) {
        return this._b = @value;
    }
    public bool c;
    public virtual bool get_c() {
        return this.c;
    }
    public virtual bool set_c(bool @value) {
        return this.c = @value;
    }
}
public class B : global::A {
    public B() : base() {
    }
    public override bool a {
        get { return _get_a(); }
    }
    public override bool b {
        get { return _get_b(); }
    }
    private bool _get_a() {
        return false;
    }
    private bool _get_b() {
        return false;
    }
    public override bool get_c() {
        return false;
    }
}

```

**Comment by nadako** [comment]
Thanks for the report! Some notes about the other issues you mentioned:

> In case of (get, set) "virtual" keyword is added but for some reason private _b becomes public _b in C#. But at least no errors

That's not related to properties, since everything is generated as public. This is required to make things like method inlining work. There's a way to make fields `protected` with the `@:protected` metadata. Be aware though that this can break native compilation in some cases, where public access is required (for example, a public inline method accessing private field).

> In case of adding @:isVar combined with @:property, variable is generated but property is not generated at all in class implementing method

Yes, `@:isVar` is not really compatible with `@:property` because C# won't allow having a backing field with the same name. Haxe should fail with a proper error in this case, instead of outputting C# that won't compile further.

**Comment by dkolyesnik** [comment]
Thanks for explanation
