### ISSUE TITLE
Property call loses field type

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6075]
```haxe
class Main {
	static public function main() {
		test("foo");
	}

	static var test:Null<String->Void>;
}
```

Dump:

```
	public static function main[Function:Void -> Void]
		[Block:Void]
			[Call:Void]
				[Field:String -> Void]
					[TypeExpr Main:Class<Main>]
					[FStatic:String -> Void]
						Main
						test
				[Const:String] "foo"
```

The `Null<T>` disappears from the output and the call is made on `String -> Void` directly.

**Comment by Simn** [comment]
Actually, this is not even a property.

**Comment by nadako** [comment]
That reminds me of https://github.com/HaxeFoundation/haxe/issues/5517, could they be related?

**Comment by Simn** [comment]
I don't think so, this issue here is about field types.

**Comment by Simn** [comment]
This was fixed by https://github.com/HaxeFoundation/haxe/commit/e421f8ddb57f0bff82e350a92bd0d967c7c218ce

I'd love to add a test for this, but I'm not sure how.
