### ISSUE TITLE
[display] @type on custom metadata in structure with extension 

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6077]
```haxe
class Main {
    static function main() {}
}

typedef Named = {
    var foo:String;
}

typedef Struct = {
    >Named,
    @:default("") var bar:String;
}
```

As you can see here, a `@type` request on the `@:default` metadata returns the extended structure (`Named`) and an incorrect range (the entire `Struct` type):

![](http://i.imgur.com/F2hngZY.png)

A `@position` requests also returns you on the `Named` type, so this may be related to #6029.

Some observations:

- removing the inheritance makes the `@type` request fail with "No completion point was found" instead (which is the expected result I guess, since the compiler doesn't know the meta)
- this only happens with custom metadata, with e.g. `@:optional` it works as expected:

  ![](http://i.imgur.com/s1x00Aa.png)

**Comment by Simn** [comment]
I didn't add a test for this particular issue because there's no expected output in case of custom metadata. It should really be the same as #6029 though.
