### ISSUE TITLE
[java/cs] @:structInit does not work on extended class

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6078]
Revision: 84bf7e5

```haxe
class Main {
	
	static function main() {
		var foo:Foo = {bar: 1};
		trace(foo);
	}
}

@:structInit
class Foo extends Bar {}

class Bar {
	var bar:Int;
	public function new(bar:Int) {
		this.bar = bar;
	}
}
```

Compiling this in java/cs fails with some weird error: `{ bar : Int } has extra field bar`
But fine in other targets

**Comment by nadako** [comment]
Eh, isn't that a pre-generation error?

**Comment by nadako** [comment]
Looks like `get_constructor` behaves differently and returns a constructor with no arguments, huh.

**Comment by frabbit** [comment]
for java/c# the function `check_struct_init_constructor` branch into the None case which generates a new constructor based on the fields of the current type, which doesn't check the super type at all. For Neko/Eval the function branches into the Some case, i guess in that case the constructor is already a copy of the superclass, which of course works.

**Comment by frabbit** [comment]
it's exactly this line https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typeload.ml#L2897
which causes this issue, the constructor is not generated for `pf_overload` platforms. Inside of check_struct_init_constructor it's generated but the super constructor is not reused.
