### ISSUE TITLE
Array splice() doc does not match lib behavior

### ISSUE THREAD

**Issue by sbijoshj** [HaxeFoundation/haxe#6081]
In the doc it says that Array.splice modifies this array in place. Then it says later that if the second parameter is negative, the result is an empty array. On the js target this appears to be false. 

```
var someArray:Array<Int> = [1, 2, 3, 4];
someArray.splice(0,-1);  // should make someArray an empty array
trace(someArray);  // someArray is unchanged!
```

Stepping through the resulting javascript shows that someArray is unaffected by the splice call.
The documentation should be corrected to match the actual code behavior.

**Comment by sbijoshj** [comment]
I did search around for any already existing issues, but let me know if I missed it somewhere. Thanks!

**Comment by R32** [comment]
result is the return value of the `.splice()`

**Comment by sbijoshj** [comment]
Ah I see, I will modify the PR to add clarification instead then. Thanks!
