### ISSUE TITLE
[php] Class 'Std' not found

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#6083]
Recently some change caused the php target to actually generate `_hx_cast` calls when using a `cast(obj, Class)`. The `php.Boot` code defines `_hx_cast` as:
```php
function _hx_cast($v, $type) {
	if(Std::is($v, $type)) {
		return $v;
	} else {
		throw new HException('Class cast error');
	}
}
```
The reference to `Std` is not updated when using `--php-prefix`. 

The `Boot` class itself gets replaced here: https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp.ml#L266
But adding to that doesn't seem like a good idea :)

**Comment by RealyUniqueName** [comment]
`--php-prefix` value should be passed to generated code and used accordingly.
E.g. genphp7 writes prefix to `php.Boot::PHP_PREFIX` constant: https://github.com/HaxeFoundation/haxe/blob/development/std/php7/Boot.hx#L74

**Comment by RealyUniqueName** [comment]
Since `Std.is()` is just an alias for `_hx_instanceof()`  i changed `_hx_cast()` to use `_hx_instanceof()`  directly.
