### ISSUE TITLE
[cpp] Issue with @:native in 3.4

### ISSUE THREAD

**Issue by Piercen** [HaxeFoundation/haxe#6086]
Before updating from 3.2.1 to 3.4 I used simple extern classes to access native types like this:
```
@:native("short")
extern class Short{}

@:native("short*")
extern class ShortPointer{}

// I also heavily used this for interfacing with obj-c
@:native("id<ObjCObject>")
extern class ObjCObject{}
```
But now each of those is resulting in the compiler error "error: expected unqualified-id" because all of the native type names are being prepended like this: "::short".

Is there an easy way to revert that?  

Edit: It looks like this is addressed in #5147, only that my problem is that these native types shouldn't be prefixed with "::" at all.

**Comment by Simn** [comment]
We really have to define what we support when `@:native` is used, seeing how people try to use it in various creative ways...

**Comment by hughsando** [comment]
At some point, a year or two ago, it changed the the hxcpp backend replacing native to the haxe compiler putting it in the cl_path (see cpp_class_name klass).  I guess I can skip the "::" easily enough if native is specified.

**Comment by hughsando** [comment]
I think I have fixed this.
For these cases specifically, in 3.4.2, you can use:
```haxe
cpp.Star<cpp.Short>
```
and
```
@:objc extern class...
```
