### ISSUE TITLE
[target-lua] Trace in constructor fails when invoked in static var.

### ISSUE THREAD

**Issue by zlash** [HaxeFoundation/haxe#6087]
A Trace in a constructor fails when invoked in static var due a wrong order in the generated code. When the constructor is run, `__hx_print` is still undefined.

Minimal test case: 

```haxe
class Test {

    public function new() {
        trace("test");
    }

    public static var instance = new Test();
}
```

this generates the following init excerpt (rest of the file redacted):

```lua
[...]
Test.instance = Test.new()
do

end
_hx_print = print or (function() end)
[...]
```

Moving `_hx_print` def before calling static initializations should do the trick.

**Comment by jdonaldson** [comment]
it's tough to sort out feature dependencies and execution order, especially with __init__ logic thrown in.  My thought is to:

1. capture static var initialization and __init__ declarations in ctx.inits as is done now.
2. generate the generated output for this code inside a temp function body (e.g. local _hx_static_init = function() <inits> end) .  This will have the nice effect of generating the entire AST for inits, and detecting any features, but it won't evaluate anything yet. The order of generation will be static var initialization *then* __init__ generation, as it is now.
3. generate the code for any detected features (e.g. _hx_print for trace)
4. generate the _hx_static_init() method evaluation that will trigger all of the static var init and __init__ logic.

Any other thoughts on an approach @nadako?
