### ISSUE TITLE
[macro] haxe.Json disppears with addClassPath() + include() + expr macro

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6089]
This is a fun one. The following application produces this error when compiled with `haxe build.hxml`:

>source/foo/Foo.hx:6: characters 8-17 : Module haxe.Json does not define type Json

Notes:

- doesn't seem to matter which path is used for `addClassPath()`
- replacing the expr macro for `Compiler.include` with `--macro include()` doesn't reproduce the issue
- this compiles fine fine 3.2.1, so it appears to be a **regression**
- the error seems JS-specific - other targets produce other, Json-related errors. Here's cpp for instance:
  > haxe\std/cpp/_std/haxe/Utf8.hx:24: characters 0-23 : You cannot access the cpp package while in a macro (for cpp.NativeString)
  >haxe\std/haxe/format/JsonPrinter.hx:195: characters 18-27 :     referenced here

  And Python:

  > haxe\std/python/_std/haxe/Json.hx:29: characters 9-24 : You cannot access the python package while in a macro (for python.lib.Json)

  With `-swf`, it even compiles fine!

________________

`source/Main.hx`:

```haxe
import haxe.Json;

class Main {
    static function main() importFoo();

    macro static function importFoo() {
        haxe.macro.Compiler.include("foo");
        return macro null;
    }
}
```

`source/foo/Foo.hx`:

```haxe
package foo;

class Foo {
    function foo() {
        exprMacro();
        haxe.Json;
    }

    static macro function exprMacro() return macro null;
}
```

`build.hxml`:

```
-cp source
-main Main
--macro addClassPath('something')
-js Main.js
```

**Comment by nadako** [comment]
No need to use `Compiler.include` too, simply `haxe.macro.Context.getModule("foo.Foo");` is enough to trigger this.

**Comment by Simn** [comment]
Can you confirm that this was fixed by https://github.com/HaxeFoundation/haxe/commit/5db1d5ecb6e4f77737564b1fd13f100904a9baa8?

**Comment by Gama11** [comment]
Yes! :)
