### ISSUE TITLE
Compiler hangs with self-referencing typedef in EitherType

### ISSUE THREAD

**Issue by harold-b** [HaxeFoundation/haxe#6092]
I was experimenting a little bit with the online haxe compiler and accidentally typed in the name of the declaring typedef in an EitherType, which caused the compiler to hang. Please see here:

[http://try.haxe.org/#f3597](http://try.haxe.org/#f3597)

Line 16: `typedef Component = haxe.extern.EitherType<Camera, Component>;`

If *<Camera, **Component**>* is switch with  *<Camera, **Mesh**>* it doesn't hang anymore (sure there's get a compiler error, but that's beside the point).

**Comment by Simn** [comment]
Probably the same as #6038 or any of the linked issues there.
