### ISSUE TITLE
[display] completion vs #if macro

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6094]
Main.hx
```haxe
#if macro
#else
import Other.C;
#end

class Main {
    static function main() {
        C.|
    }
}
```

Other.hx
```haxe
class C {
    public static function f() {}
}
```

```
$ haxe --display Main.hx@0
No classes found in C
```

This is specific to `macro`, it seems, as any other define works as it should:
```
$ haxe --display Main.hx@0
<list>
<i n="f" k="method"><t>Void -&gt; Unknown&lt;0&gt;</t><d></d></i>
</list>
```

**Comment by Simn** [comment]
Yes, `#if macro` is special in the parser. We can't change that without breaking everything though.

**Comment by Simn** [comment]
I still have no idea what to do with this. `#if macro` is always going to be an issue thanks to its special treatment, but there's no other solution for the "display in macro" problem.

**Comment by RealyUniqueName** [comment]
I think, `macro` should be ignored for display mode. And in this case both branches of `#if macro ... #else ... #end` should be handled as there is no `#if`. Because we can't distinguish whether method `main` will or will not be used in a macro context.

**Comment by Simn** [comment]
This is still a huge problem.
