### ISSUE TITLE
[lua] Haxe 3.4.0 and Array.slice

### ISSUE THREAD

**Issue by Drabuna** [HaxeFoundation/haxe#6098]
In my generated code, the only place where slice is used is in EnumValueMap:

`haxe.ds.EnumValueMap.prototype = _hx_a(
  'compare', function(self,k1,k2) 
    local d = k1[1] - k2[1];
    if (d ~= 0) then 
      do return d end;
    end;
    local p1 = k1:slice(2);
    local p2 = k2:slice(2);
    if ((p1.length == 0) and (p2.length == 0)) then 
      do return 0 end;
    end;
    do return self:compareArgzs(p1,p2) end
  end,`

And for some reason Array.prototype doesn't have slice function anymore.

My quick workaround was to invoke slice on Array somewhere in the code and after that Array.prototype got the slice function.

**Comment by nadako** [comment]
This is fixed already, I think, see #6037.
