### ISSUE TITLE
[lua] Array and 0-index

### ISSUE THREAD

**Issue by Drabuna** [HaxeFoundation/haxe#6100]
As you might know it's common that in Lua array index stars from 1 but not from 0. I'm using haxe to write logic-heavy code, and then just integrate it into existing logic-light client (done in lua). Haxe-Lua array implementation uses 0 as the the initial index, and this causes a lot of problems if you use standard lua iterators to loop over the arrays in lua code. 

Suggestion: Should lua generated code use 1 as initial index of the array, because it's expected behaviour for lua developers?

**Comment by nadako** [comment]
> Should lua generated code use 1 as initial index of the array

Don't think so, that would mean adding and substracting 1 all over the generated code which is heavy and error-prone. 

Maybe @jdonaldson could add a couple more hints about haxe<->lua interop, but I think you'll need to expose `lua.Table` instead of `Array` in your API for Lua consumers.

**Comment by Simn** [comment]
It would be very awkward if Haxe arrays were indexed differently depending on the target.

**Comment by jdonaldson** [comment]
As @nadako mentioned, you're going to have to treat arrays and tables separately in your api.  Check out lua.Table.create() for a convenience method specific for tables.

Also check out lua.PairTools and Lambda for some utilities that are useful for mapping/folding haxe/lua iterators into other useful datatypes.

**Comment by gerardsmit** [comment]
@jdonaldson @nadako Is it maybe an idea to add `@:luaIndex` or something in those lines for external API's? 

For example:
```haxe
/**
    Gets the RGB value of the color in the palette at the specified index.
**/
@:luaDotMethod
public function getPaletteColor(@:luaIndex index: Int): Int;
```

Otherwise I have to always do `index + 1` in the my code because the external API starts at 1.

**Comment by andyli** [comment]
You may try this:

```haxe
abstract LuaIndex(Int) {
    function new(v:Int) {
        this = v;
    }
    @:from static function fromInt(i:Int):LuaIndex {
        return new LuaIndex(i + 1);
    }
}

class Test {
    static function luaFunction(i:LuaIndex) {
        trace(i);
    }
    static function main() {
        luaFunction(0); //1
    }
}
```

But I doubt its usefulness...

**Comment by gerardsmit** [comment]
Actually it's quite usefull, this way I don't have to check if it's a Lua function, for example in a for-loop.

Thanks for the hint. 😄

**Comment by jdonaldson** [comment]
Andy's technique will work fine for this situation.  I don't use this technique because I prefer to keep the lua apis "raw", and work around index offset issues with inlined haxe function apis.
