### ISSUE TITLE
TypedExprTools.toString convert interface property call to get_x resulting in I has no field get_x after Context.parse

### ISSUE THREAD

**Issue by dkolyesnik** [HaxeFoundation/haxe#6101]
I'm creating a macro static extension and in case if I convert expression to string and back to code like this:
TypedExprTools.toString(Context.typeExpr(value), true);
I do this because in case of static extension ExprTools.toString(value)  retune  @:this this and I need to get code.
If called not as static extension
ExprTools.toString(value)       returns a.a
and 
TypedExprTools.toString(Context.typeExpr(value), true);      returns a.get_a();

here is an example
http://try-haxe.mrcdk.com/#7EaA8

I did it using Haxe 3.4 and on flash target it is working in some cases even though get_x is returned by TypedExprTools.toString.

**Comment by Simn** [comment]
Yes that can happen if you re-type expressions like that. What exactly do you consider broken here?

**Comment by dkolyesnik** [comment]
I'm talking about the fact that parsing a.get_a() string using Context.parse returns an error:
I has no field get_a
or TypedExprTools.toString is not supposed to be used with Context.parse ?

**Comment by Simn** [comment]
The typed expression may look very different from the original syntax. Imagine inline function calls, or even previously expanded macro calls. There is no guarantee that the typed expression can be converted back to something that parses again. That's the very reason the compiler passes the `@:this this` expression, and by circumventing that you're basically bringing back all the problems that originally caused its introduction.

Why do you need the structure of the argument expression?

**Comment by nadako** [comment]
You might want to use `http://api.haxe.org/haxe/macro/Context.html#storeTypedExpr` if you want to return a part of typed expression.

**Comment by dkolyesnik** [comment]
For a macro to convert a call chain to series of if(x != null) checks.
Ok, thank you for the explanation about TypedExprTools.toString

Also I was surprised that get_x() method, which is generated in the result code for an interface is causing an error. But It looks like it may not be present at this time yet.

Adding get_x method into interface manually removes the error. 
@nadako thank you for the link, it is also works in case of an my example, but not in my real case.

**Comment by back2dos** [comment]
@dkolyesnik My advice: rather than `using Nullsafe;` and then `the.long.path.nullsafe()` do `import Nullsafe.*;` and then `nullsafe(the.long.path)`.

I really wouldn't mind if there were a simple way to get the original `Expr` from `@:this this`. It's not an existential need, but in some cases it would simply allow for code that sounds less awkward when read out loud.

**Comment by dkolyesnik** [comment]
@back2dos yes, thank you for the advice, guess I would use import after all.

**Comment by back2dos** [comment]
@Simn Wanting to get the original expression is a thing - as evidenced in this issue, or here: https://groups.google.com/d/msg/haxelang/9sgeYvrz88A/qF975NFBAQAJ ... and I'm sure I can find others. There's even [pretty horrible code](https://github.com/HxJointForces/usingHack/blob/master/src/main/macros/UsingHack.hx) published to deal with it. 

You can close this, but I'm sure it's going to come back ;)

**Comment by Simn** [comment]
It is not going to work with our current typer, the original expression is simply long gone before the macro call is made.
