### ISSUE TITLE
Compilation server - Warn+continue instead of error+stop

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6102]
Haxe does fatal error when it cannot connect to compilation server. 
```
Fatal error: exception Failure("Couldn't connect on 127.0.0.1:6000")
```
Can this be changed to a warning and continue making the build? 

This would help in productivity because sometime I now have either to manually remove the `--connect 6000` from my build.hxml or start the compilation server. When in rush or when colleagues want a build this can be slightly annoying.

**Comment by Simn** [comment]
I don't think this would be good behavior. Stating `--connect` very clearly conveys the intent to connect to a server, and if that doesn't work an error should be given.
