### ISSUE TITLE
[c#/java] closure with type parameters

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6106]
Revision: 84bf7e5

```haxe
class Main {
	
	static function main() {
		var code = 0;
		function assertEquals<T>(expected:T, actual:T) {
			if(expected != actual) code++;
		}
		
		var f = function() assertEquals(1, 1);
	}
	
}
```

Fails with `src/Main.cs(77,38): error CS0103: The name 'code' does not exist in the current context`

Removing the type parameter `T` makes it compiles.

By looking at the output, seems that the compiler omitted the closure for `assertEquals` when assigning the anonymous closure to `f`.

**Comment by kevinresol** [comment]
Similar in Java.

**Comment by frabbit** [comment]
i cannot reproduce this anymore, is this fixed? @kevinresol can you check?

**Comment by kevinresol** [comment]
yeah seems fixed

**Comment by nadako** [comment]
Reopening to add test to make sure this doesn't come back again.
