### ISSUE TITLE
[display] module-symbols should only depend on syntax

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6107]
`@module-symbols` should work on _any_ `.hx` file, that is, as long as the syntax is valid (since that's all that's needed for symbols). However, in practice this isn't the case.

Here, we get the expected symbols list:

```haxe
class Main { static function main() {} }
```

```
haxe --display Main.hx@0@module-symbols
```

Now, add `import foo.Bar;` to the file - the result is a "type not found" error:

>Main.hx:1: characters 7-14 : Type not found : foo.Bar

I'd expect it to not try to resolve any types and still get a proper response, since module-symbols is only supposed to care about syntax.

**Comment by Simn** [comment]
I'll not work on module symbols in Haxe and probably even remove it entirely. This is better suited for hxparser.
