### ISSUE TITLE
[lua] Simpler/Sandboxed Lua target support needed (not allowed: pcall, setmetatable)

### ISSUE THREAD

**Issue by mikesmullin** [HaxeFoundation/haxe#6108]
I wish I could use Haxe -> Lua for making game mods, but as-is the the thousand-line boilerplate that comes out right now is centered around the use of `pcall()` and `setmetatable()`. In this game, the mods are run in a sandbox, where those global functions are restricted for security reasons. This is not an uncommon scenario. I fear others will be equally disappointed. :(

Any way to reduce the boilerplate dependency? Seems like we'd have to re-implement the Haxe support for Lua target. Maybe calling it SimpleLua target, or something...

**Comment by jdonaldson** [comment]
Wow, that is extremely restrictive.  I worked pretty hard to get basic haxe features working on a very minimal set of instructions.  However, lua is also easy to embed and limit, and there's always going to be some crazy situation to work around.

In particular, pcall is required for the try/catch functionality, in addition to some situations involving loop management.  The setmetatable method is also irreplaceable for managing OOP inheritance chains.

Neither of those methods is inherently unsafe.  Can you tell me the name of the game mod you were interested in?  Maybe there is a mechanism/workaround for some of the limitations they're imposing.

**Comment by mikesmullin** [comment]
the game is Don't Starve Together. and ya you're right thx for that suggestion.
further searching revealed
http://forums.kleientertainment.com/topic/69343-solved-playerid-length-fixed/?do=findComment&comment=800780

they expose those functions through a variable called GLOBAL

right now i am manually adding the following to the top of the output and it will run

```
local pcall = GLOBAL.pcall
local getmetatable = GLOBAL.getmetatable
local setmetatable = GLOBAL.setmetatable
local rawset = GLOBAL.rawset
local select = GLOBAL.select
local _G = GLOBAL
```

so now the only problem is this is a post-processing step right now for me. is there a way to get it to happen automatically via haxe?

**Comment by nadako** [comment]
> is there a way to get it to happen automatically via haxe?

I think it's possible via macro. You register a `onAfterGenerate` callback, in which you do `Compiler.getOutput()` to get the output lua file path, and then just modify it using `sys.io.File` api. I've done something like that before for the JS target.

**Comment by Simn** [comment]
You could register an [onContextGenerate](http://api.haxe.org/haxe/macro/Context.html#onAfterGenerate) callback which [gets the output file name](http://api.haxe.org/haxe/macro/Compiler.html#getOutput) and does some simple string operations to add that.

**Comment by mikesmullin** [comment]
nice! thx all! this solution working for me now:

```haxe
# Macro.hx
package;

import sys.io.File;

class Macro {
	public static macro function dontStarvePreInit()
	{
		// Dont Starve mods operate in a sandboxed environment
		// where global functions are all moved into a GLOBAL variable.
		// Here we restore common functions to local script scope
		// so the Haxe Lua target boilerplate works as expected.		

		haxe.macro.Context.onAfterGenerate(function() {
			var mainFile = haxe.macro.Compiler.getOutput();
			var compilerOutput = File.getContent(mainFile);
			File.saveContent(mainFile, 
				"local pcall = GLOBAL.pcall\n"+
				"local getmetatable = GLOBAL.getmetatable\n"+
				"local setmetatable = GLOBAL.setmetatable\n"+
				"local rawset = GLOBAL.rawset\n"+
				"local select = GLOBAL.select\n"+
				"local _G = GLOBAL\n\n" +
				compilerOutput);
		});
		
		return macro null;
	}
}
```

```haxe
# Main.hx
package;

class Main
{
	public static function main() 
	{
		Macro.dontStarvePreInit();
	}
}
```

**Comment by Simn** [comment]
Glad to see you worked it out!

**Comment by nadako** [comment]
BTW you could also have that as an init macro, specifying `--macro Macro.dontStarvePreInit()` as a command-line argument.
