### ISSUE TITLE
[php] New source_map define does not seem to do anything

### ISSUE THREAD

**Issue by aftokinito** [HaxeFoundation/haxe#6111]
When using Haxe 3.4.1 and -D source_map, the compiler does not seem to generate any source map.
Am I missing something?

Info:

- PHP 7.0.16 (cli) (built: Feb 14 2017 11:53:40) ( ZTS )

- Haxe 3.4.1 (git build master @ 5c44548)

**Comment by RealyUniqueName** [comment]
It generates `.php.map` file near each `.php` file.
Can you show your hxml?

**Comment by aftokinito** [comment]
I double checked and I am indeed not getting those .php.map files generated.
My hxml:
-cp ./src
-main my.super.duper.kool.package
-php ./target
-xml ./target/doc/doc.xml
-D haxeJSON source_map
-debug

**Comment by Simn** [comment]
You have to use `-D haxeJSON -D source_map`.

**Comment by aftokinito** [comment]
Unfortunately, separating the defines into two different arguments did not solve the issue, the compiler is still not generating the source maps.

**Comment by ibilon** [comment]
The source map is only done for the php7 target, not the old one.
You need to add `-D php7` to your hxml.

**Comment by aftokinito** [comment]
That did indeed work, thank you very much!
