### ISSUE TITLE
call at ExternalInterface doesn't work

### ISSUE THREAD

**Issue by hopewise** [HaxeFoundation/haxe#6118]
It seems that method call in External Interface is not working: http://api.haxe.org/flash/external/ExternalInterface.html

**Comment by kevinresol** [comment]
I am afraid this kind of issue report will be closed immediately. So, before that happens, please provide more details or reproducible example.

**Comment by Justinfront** [comment]
There seems to be an example use here Hopewise, so it should work fine, please test example and report back.
http://www.dango-itimi.com/blog/archives/2013/001192.html

**Comment by hopewise** [comment]
Thanks, I will report very soon

**Comment by hopewise** [comment]
I have tested it using OpenFL samples, it worked fine.
