### ISSUE TITLE
`function foo(i:Int = null)` works on static platforms

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#6124]
```haxe
class Main {
	
	static function main() {
		foo();
	}
	
	static function foo(i:Int = null) {
		trace(i); // null
		bar(i);
	}
	
	static function bar(i:Int) {
		trace(i); //0
	}
}
```

haxe 3.3.0-rc-1, 3.4.0, 3.4.1, 3.4.2
Proven targets: flash(http://try.haxe.org/#d3F06), cpp

**Comment by Simn** [comment]
Yes this is automatically changed to `Null<Int>` in such a case. I find this quite strange as well, but I'm not sure it's worth breaking.

**Comment by SlavaRa** [comment]
http://try.haxe.org/#76c6A
```haxe
class Test {
    static function main() {
		bar((null:Null<Int>));
    }
	
	static function bar(i:Int) {
		trace(i); //0
	}
}
```
ok?

**Comment by nadako** [comment]
I don't think this is really specified right now, and I think it's worth breaking for Haxe 4, if we want some sensible null handling.

**Comment by nadako** [comment]
Oh, I didn't know that. It's specified to become a target-specific default value?

**Comment by Simn** [comment]
Yes, see https://haxe.org/manual/types-nullability.html

**Comment by Simn** [comment]
Per #6972, there is nothing to fix here.
