### ISSUE TITLE
[display] inline local functions prefixed by "inline_" in module-symbols

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6129]
```haxe
class Main {
    public static function main() {
        inline function foo() {}
    }
}
```

The `inline_` prefix here is quite strange, I guess it's an implementation detail that's getting leaked?

![](http://i.imgur.com/4ucxWXQ.png)

**Comment by Simn** [comment]
That's what happens when you encode meta information in strings... I guess the parser could instead emit `@:inline function foo() { }` or something like that.
