### ISSUE TITLE
Inlining of dynamic arrays crashes compilation in C# target.

### ISSUE THREAD

**Issue by basro** [HaxeFoundation/haxe#6135]
``` haxe
class Test {
    static function main() {
        var x:Array<Dynamic> = [1];
        x[0] = "hi";
        trace(x[0]);
    }
}
```
Compiling that to C# will fail, the haxe compiler prints `Compilation error Native compilation failed`. I haven't tested in any other static platform but I suspect they will break in some way too.

**Comment by nadako** [comment]
Hmm, it indeed generates:
```
int x_0 = 1;
x_0 = "hi";
```

This probably means that array inlining types `x_0` as `Int` instead of `Dynamic`, so yeah, this is most likely an error on other static targets too.

**Comment by Simn** [comment]
I guess we should just not do this when the variable is `Array<Dynamic>`.

**Comment by nadako** [comment]
Why? Can't we just type inlined vars as Dynamic and be done with it?

**Comment by basro** [comment]
Null<T> will also create problems like this:
``` haxe
class Test {
    static function main() {
        var x : Array<Null<Int>> = [1];
        x[0] = null;
        trace(x[0]);
    }
}
```

**Comment by ncannasse** [comment]
We should use the array type and not the value type.
