### ISSUE TITLE
Compiler assertion fails when targetting HashLink

### ISSUE THREAD

**Issue by basro** [HaxeFoundation/haxe#6136]
``` haxe
class Test {
    static function main() {
        var x:Dynamic = null;
        x = [-101.5];
        x[0] %= 100;
    }
}
```
Trying to compile this code to hashlink will fail:
`File "_build/src/generators/genhl.ml", line 2065, characters 6-12: Assertion failed`

**Comment by ncannasse** [comment]
Closed with b402fa3e3b51c7181fda740d21c9467c793a3ea7
