### ISSUE TITLE
getChar is blocking

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6139]
http://api.haxe.org/Sys.html#getChar says that the function is not blocking, but calling it blocks waiting for input.

**Comment by nadako** [comment]
@ncannasse is it really supposed to be non-blocking? Given that other stdio APIs are blocking.

**Comment by ncannasse** [comment]
I think the documentation is misleading, the original meaning is that you don't have to wait until enter is pressed to get the result.

**Comment by madneon** [comment]
Is there any way of "true" non-blocking input?

**Comment by ncannasse** [comment]
in a terminal app I don't think it make senses, in a windowed / interactive application there are specific apis for this.

**Comment by ncannasse** [comment]
Assigning to @Simn to have documentation fixed

**Comment by madneon** [comment]
This basically means, one can't create terminal app **with user input without implementing threads**, right?
How difficult would it be to have non-blocking getChar (on all platforms)?
