### ISSUE TITLE
Allow local paths in -lib command-line option

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/haxe#6140]
In my case I have a set of projects with a references to my own libraries (with dependencies). Local haxelib repo looks like a not good solution:
1. haxelib don't search for repo in parent folders (so I must copy `.haxelib` to every project;
2. links to my sources in `.dev` (inside `.haxelib`) are absolute and 
3. must be finely maintained.

So, I think, `haxe -lib path_to_the_library` is a good solution...

**Comment by Simn** [comment]
Isn't that what -cp is for?

**Comment by back2dos** [comment]
The difference is that a lib can have dependencies and an extraParams.hxml and also sets a -D flag.

In any case, the issue should be on the haxelib tracker ;)

**Comment by Simn** [comment]
Well, if we're talking `-D` flags it would have to be a Haxe change as well because that happens in the `-lib` handling there.

**Comment by yar3333** [comment]
Moved to https://github.com/HaxeFoundation/haxelib/issues/377

**Comment by Simn** [comment]
Now I'm confused because Haxe clearly does it as well:

```haxe
("-lib",Arg.String (fun l ->
	cp_libs := l :: !cp_libs;
	Common.raw_define com l;
),"<library[:version]> : use a haxelib library");
```

The `raw_define` defines whatever the argument to -lib was. I guess that makes it redundant?

**Comment by yar3333** [comment]
@Simn Looks like @back2dos write about -D from `extraParams`.

**Comment by yar3333** [comment]
@Simn You are right: this is a problem - now haxe do a define = library name...

**Comment by Simn** [comment]
Yes, we would have to remove that if we want to add this feature to haxelib.

**Comment by yar3333** [comment]
>May be, we can take a last folder in path as a library name?

**Comment by Simn** [comment]
> May be, we can take a last folder in path as a library name? (To define it.)

Haxelib knows the library name from haxelib.json, so if it already sends the `-D` flag to Haxe all we should have to do on the Haxe-side is remove that `raw_define`.

**Comment by back2dos** [comment]
You can run `haxelib path your_favorite_lib` and you'll see everything is in the output.

> Yes, we would have to remove that if we want to add this feature to haxelib.

Is it a real problem if a variable of the name `"./some/path"` is defined? I think the first thing to solve is implement it in haxelib path properly and then see about the rest.

**Comment by Simn** [comment]
> Is it a real problem if a variable of the name "./some/path" is defined? I think the first thing to solve is implement it in haxelib path properly and then see about the rest.

I was thinking that `-lib macro` would be pretty bad, but then again that would be an issue for the `-D` flag received from haxelib as well. So I guess it's not a huge deal.

**Comment by kevinresol** [comment]
.dev contents doesn't need to be absolute.

**Comment by yar3333** [comment]
Now I think, what `-lib path_to_lib` feature is not intuitive and brings the unnecessary complexity to haxe. If nobody think else, I close this issue.
