### ISSUE TITLE
Haxe OCaml setup

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6143]
Following yesterday conversation on Slack, I have work on making easier to setup ocaml/mingw to get started with Haxe.

My goal is to build "OCamlHaxe", a an simple zip with a configure script that handles all the cases so in the end you get everything setup correctly without breaking your current cygwin/mingw implementation.

I started from OCaml32, could setup and install OPAM (only at home). Today I wrote the Config script that setup all env vars and paths etc.

I wanted to be able to download OPAM and make it work but I can't make it work on this computer using either the mini-cygwin toolchain that is part of OCamlHaxe or the normal cygwin install on my computer. It keeps complaining about missing tools "rsync etc." on `opam init` while they are available from both windows and cygwin shell. Maybe it checks for an additional tool that is not listed as part of the required tools? see [here](https://github.com/ocaml/opam/issues/2896)

As a consequence, this "OCamlHaxe" version ships with an already setup OPAM repository with OCaml 4.04, ocamlfind and camlp4 installed.

**If you don't have Cygwin** then the config script will add (OcamlHaxe/mingw/bin) to your user PATH, it should have everything you need to compile haxe and its libraries

**If you have Cygwin** then the config script will not add (OcamlHaxe/mingw/bin) to your user PATH. You can either do it manually or install the required packages to compile haxe : `make`, `mingw64-i686-gcc-core`, `mingw64-i686-zlib` and `mingw64-i686-pcre`

To run OPAM, we need to resolve why it doesn't detect tools already installed, and we might need additional tools in our mini cygwin/mingw (see https://github.com/fdopen/opam-cygwin-installer/blob/master/opam.nsi for what fdopen installer do).

Anyway, if you could give it a try, you can download OCamlHaxe from here:
http://build.haxe.org/bin/ocamhaxe.zip

You unzip where you want, then you start `config.bat`

Then you can start compiling Haxe by following https://haxe.org/documentation/introduction/building-haxe.html

I'm interested in any error that occurs during config.bat or when trying to compile haxe

**Comment by nadako** [comment]
I could compile haxe.exe successfully with that setup on a fresh machine without cygwin and/or existing ocaml installation, however it's missing libpcre-1.dll and zlib1.dll, so haxe.exe won't run.

Also, please provide ocamlmerlin in this package, because it's a pain to work without it once you try :)

And finally, I'd like to have 64-bit version as well. I used fdopen's Ocaml64 and compiled 64-bit haxe.exe successfully, so it does work fine.

**Comment by nadako** [comment]
oh, and we need a proper uninstall script that will clean up those vars, or at least a README on what is what and what to remove.

**Comment by hughsando** [comment]
I love this initiative.
Lets fix the toolchain to use the one provided (no config differences).  Also, a static libpcre and libz would be really real nice.  Again, fix and ship the version / source code / headers.
Can you skip opam and just copy everything a "bin" directory, fix the lib and include paths and make everything relative to one variable - which defaults to c:/something.  So "unzip to c:/something, run buildwindows.bat" is the install instructions.  This would save days of my life.

**Comment by ncannasse** [comment]
@nadako for libpcre-1 and zlib1 yes they need to be in the PATH, so I guess we would need to move them from mingw\usr\i686-w64-mingw32\sys-root\mingw\bin to mingw\bin

Does OPAM works for you in this setup?

As for the uninstall script yes this could be done easily, it's just a matter of removing a few env vars.

@hughsando I would also like static pcre/zlib like we used to have on ocaml/msvc but this requires to build them from source since they are not distributed this way as part of mingw toolchain. Not sure if that's worth it.

Also, the current OCamlHaxe is designed to "unzip + run config.bat and get started" , the fact that config.bat does or does not run OPAM is just a matter of how much time the config.bat will run vs how much zip you will download :)

**Comment by ncannasse** [comment]
BTW I'm looking for more testers with a Cygwin already installed, ping @waneck @andyli @jdonaldson

**Comment by hughsando** [comment]
HXCPP distributes and builds zlib and pcre in no time.  If the compiler is
fixed, you can ship a precompiled .a no trouble at all.
Not sure how to point ocaml at the lib.

**Comment by ncannasse** [comment]
Note : we also need to ship mv.exe that is required to "make haxelib"

**Comment by ncannasse** [comment]
Note: setting OCAMLRUNPARAM=b in config would be nice too

**Comment by ncannasse** [comment]
I have setup https://github.com/HaxeFoundation/ocamhaxe, uploading 1.0 version as we speak

**Comment by Justinfront** [comment]
Is this only for windows, it looks very windows based, sorry reading through the thread above and on the repository there is nothing explicitly specifying target but...
-cmd copy bin\build.exe .
could this be adapted for mac/linux as well, I think exe are going to be picked up by virtualbox windows rather than mac mono.  I don't like using macports, fink, homebrew etc... they always need updating and fixing.  If it's only for windows fair enough but nice stuff for mac without package managers would be nice, or is it just easier to use the Kha haxe, not sure if it has -> in yet.

**Comment by hughsando** [comment]
Here are my adventures trying to use opam:
```
Download and extract 
   http://build.haxe.org/bin/ocamhaxe.zip  -> c:/HaxeToolkit/ocamhaxe

Cygwin Shell:
   cd c:/HaxeToolkit/ocamhaxe
   ./config/Config.exe

   2 UAC prompts (this is ok - I did not want to run .bat again), then success:


Cygwin found in C:\cygwin64\bin\
Querying environment...
> regedit /E C:\cygwin64\tmp\env.txt HKEY_CURRENT_USER\Environment
Updating Environment...
> regedit /S C:\cygwin64\tmp\env.txt
> setx OCAMLLIB C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/lib/ocaml

SUCCESS: Specified value was saved.
> setx OCAMLFIND_CONF C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/lib/findlib. conf

SUCCESS: Specified value was saved.
> setx OCAMHAXE C:\HaxeToolkit\ocamhaxe/bin;C:\HaxeToolkit\ocamhaxe/.opam/4.04.0 +mingw32c/bin


$ echo  $OCAMHAXE
C:\HaxeToolkit\ocamhaxe/bin;C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/bin


$ echo $OCAMLLIB
C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/lib/ocaml

$ echo  $OCAMLFIND_CONF
C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/lib/findlib.conf

cd ~/dev/code.google/haxe

make clean

make
make -C libs/extlib-leftovers native && make -C libs/extc native && make -C libs/neko native && make -C libs/javalib native && make -C libs/swflib native && make -C libs/ttflib native && make -C libs/ilib native && make -C libs/objsize native && make -C libs/pcre native && true
make[1]: Entering directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extlib-leftovers'
ocamlopt -safe-string -g -a -o extlib-leftovers.cmxa multiArray.mli rbuffer.mli uChar.mli uTF8.mli multiArray.ml rbuffer.ml uChar.ml uTF8.ml
File "_none_", line 1:
Error: C:\HaxeToolkit\ocamhaxe/.opam/4.04.0+mingw32c/lib/ocaml\pervasives.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.

$ which ocaml
/cygdrive/c/OCaml/bin/ocaml

mv c:/OCaml c:/OCaml-hidden

$ which ocaml
/cygdrive/c/HaxeToolkit/ocamhaxe/.opam/4.04.0+mingw32c/bin/ocaml

$ make
make -C libs/extlib-leftovers native && make -C libs/extc native && make -C libs/neko native && make -C libs/javalib native && make -C libs/swflib native && make -C libs/ttflib native && make -C libs/ilib native && make -C libs/objsize native && make -C libs/pcre native && true
make[1]: Entering directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extlib-leftovers'
ocamlopt -safe-string -g -a -o extlib-leftovers.cmxa multiArray.mli rbuffer.mli uChar.mli uTF8.mli multiArray.ml rbuffer.ml uChar.ml uTF8.ml
make[1]: Leaving directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extlib-leftovers'
make[1]: Entering directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extc'
ocamlfind ocamlc -safe-string  extc_stubs.c
extc_stubs.c:26:18: fatal error: zlib.h: No such file or directory
compilation terminated.

$ PATH=c:/HaxeToolkit/ocamhaxe/mingw/bin/:$PATH
 - same result, try cygwin path...
PATH=/cygdrive/c/HaxeToolkit/ocamhaxe/mingw/bin/:$PATH
make
...
ocamlfind ocamlopt -safe-string -a -o extc.cmxa -package extlib extc.ml process.ml
ocamlfind: Package `extlib' not found

$ which ocamlfind
/cygdrive/c/HaxeToolkit/ocamhaxe/.opam/4.04.0+mingw32c/bin/ocamlfind

ls .opam/packages

????????????????????????

$ which opam
/cygdrive/c/HaxeToolkit/ocamhaxe/bin/opam


$ opam config env
[ERROR] The current switch (system) is an unknown compiler switch.

$ OPAMROOT=c:/HaxeToolkit/ocamhaxe/.opam
$ export OPAMROOT
make 
$ OPAMROOT=c:/HaxeToolkit/ocamhaxe/
make 
$ OPAMROOT=/cydrive/c/HaxeToolkit/ocamhaxe/.opam
make 

$ ocamlfind list
bigarray            (version: [distributed with Ocaml])
bytes               (version: [distributed with OCaml 4.02 or above])
camlp4              (version: 4.04.0)
camlp4.exceptiontracer (version: 4.04.0)
camlp4.extend       (version: 4.04.0)
camlp4.foldgenerator (version: 4.04.0)
camlp4.fulllib      (version: 4.04.0)
camlp4.gramlib      (version: 4.04.0)
camlp4.lib          (version: 4.04.0)
camlp4.listcomprehension (version: 4.04.0)
camlp4.locationstripper (version: 4.04.0)
camlp4.macro        (version: 4.04.0)
camlp4.mapgenerator (version: 4.04.0)
camlp4.metagenerator (version: 4.04.0)
camlp4.profiler     (version: 4.04.0)
camlp4.quotations   (version: 4.04.0)
camlp4.quotations.o (version: 4.04.0)
camlp4.quotations.r (version: 4.04.0)
camlp4.tracer       (version: 4.04.0)
compiler-libs       (version: [distributed with Ocaml])
compiler-libs.bytecomp (version: [distributed with Ocaml])
compiler-libs.common (version: [distributed with Ocaml])
compiler-libs.optcomp (version: [distributed with Ocaml])
compiler-libs.toplevel (version: [distributed with Ocaml])
dynlink             (version: [distributed with Ocaml])
findlib             (version: 1.7.1)
findlib.dynload     (version: 1.7.1)
graphics            (version: [distributed with Ocaml])
num                 (version: [distributed with Ocaml])
num-top             (version: 1.7.1)
num.core            (version: [internal])
ocamlbuild          (version: 0.11)
ocamldoc            (version: [distributed with Ocaml])
stdlib              (version: [distributed with Ocaml])
str                 (version: [distributed with Ocaml])
threads             (version: [distributed with Ocaml])
threads.posix       (version: [internal])
unix                (version: [distributed with Ocaml])


$ ls /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/packages
base-bigarray  base-threads  base-unix  camlp4  conf-m4  ocamlbuild  ocamlfind

$ find  /cygdrive/c/HaxeToolkit/ocamhaxe/.opam -name extlib
/cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/mingw/packages/extlib

set something = /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/mingw/packages ?

OPAMROOT=/cygdrive/c/HaxeToolkit/ocamhaxe/.opam
opam init
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg
    command on your system.
  - you won't be able to use darcs repositories unless you install the darcs
    command on your system.

[WARNING] No external solver found, one of aspucd, packup and mccs is
          recommended (see
          http://opam.ocaml.org/doc/Install.html#ExternalSolvers for details)
[WARNING] Recommended dependencies -- most packages rely on these:
            - cc


=-=- Fetching repository information =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[default: git]
[default: git]
[default: git]
[default: git]
[default: git]
[default: git]
[default] git+https://github.com/fdopen/opam-repository-mingw.git updated
[ERROR] Initialisation failed
"cp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/default/compilers//3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/compilers/3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp" exited with code 1 "/usr/bin/cp: cannot stat '/cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/default/compilers//3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp': No such file or directory"
[ERROR] Command "cp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/default/compilers//3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/compilers/3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp" failed:
"cp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/default/compilers//3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp /cygdrive/c/HaxeToolkit/ocamhaxe/.opam/compilers/3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp" exited with code 1 "/usr/bin/cp: cannot stat '/cygdrive/c/HaxeToolkit/ocamhaxe/.opam/repo/default/compilers//3.12.1/3.12.1+mingw32/3.12.1+mingw32.comp': No such file or directory"
a
$ make
make -C libs/extlib-leftovers native && make -C libs/extc native && make -C libs/neko native && make -C libs/javalib native && make -C libs/swflib native && make -C libs/ttflib native && make -C libs/ilib native && make -C libs/objsize native && make -C libs/pcre native && true
make[1]: Entering directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extlib-leftovers'
make[1]: Nothing to be done for 'native'.
make[1]: Leaving directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extlib-leftovers'
make[1]: Entering directory '/cygdrive/c/Hugh/dev/code.google/haxe/libs/extc'
ocamlfind ocamlopt -safe-string -a -o extc.cmxa -package extlib extc.ml process.ml
make[1]: ocamlfind: Command not found

$ find /cygdrive/c/HaxeToolkit/ocamhaxe -name "ocaml*"
/cygdrive/c/HaxeToolkit/ocamhaxe/bin/ocaml-env-win.exe
/cygdrive/c/HaxeToolkit/ocamhaxe/bin/ocaml-env.exe

no ocamlfind!

```

So there were a couple of little problems with and old ocaml installation - easy enough.
And with an old gcc path taking priority, also easy enough.

Then ocamlfind simply can not find the opam packages.  I had not idea how to make this work.
So I ran "opam init" and this deleted ocamlfind, so problem solved I guess.

**Comment by ncannasse** [comment]
@hughsando if you are using your own cygwin install (which you should) , it means you need to install zlib-mingw32 and pcre-mingw32 packages. I've opened https://github.com/HaxeFoundation/ocamhaxe/issues/4

**Comment by ncannasse** [comment]
PS: by using ocamhaxe distribution, it does not seems possible to use OPAM because it does not support relocation to a different directory (there seem to be several hardcoded paths), it should however allow you to compile haxe since all the required packages are already installed

**Comment by ncannasse** [comment]
PPS: anyway this ocamhaxe build is outdated, I will remove it, please clone https://github.com/haxefoundation/ocamhaxe and run haxe/Build.exe instead
