### ISSUE TITLE
PCRE bindings vs. matched spec

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6145]
```haxe
class Main {
	static public function main() {
		var r = ~/(a)/;
		r.match("a");
		r.matched(2);
	}
}
```

This is supposed according to the [specification](http://api.haxe.org/EReg.html#matched): "If no such sub-group exists, an exception is thrown". I thought I could rely on the length of the array `pcre_exec` returns, but that is [documented](https://github.com/mmottl/pcre-ocaml/blob/master/src/pcre.mli#L367) to "also contains additional workspace needed by the match engine". That's why it works with 2 but fails with 20 or something.

[Neko uses `pcre_fullinfo`](https://github.com/HaxeFoundation/neko/blob/master/libs/regexp/regexp.c#L122) to calculate the number of groups, but that function is not part of the OCaml bindings. I guess the best solution is to use [exec](https://github.com/mmottl/pcre-ocaml/blob/master/src/pcre.mli#L392) and work with the substrings API the bindings provide.

**Comment by Simn** [comment]
This also fails on C# and both PHPs.

**Comment by RealyUniqueName** [comment]
I think this is closed accidently. Feel free to reclose )

**Comment by Simn** [comment]
That was fixed.
