### ISSUE TITLE
Python Type.getInstanceFields causes _hx_fields aliasing and breaking with subclasses.

### ISSUE THREAD

**Issue by IdanDor** [HaxeFoundation/haxe#6147]
Hello,
It seems like if you use Type.getInstanceFields on a subclass all its _hx_fields are added to its superclass in python. The problem seems to be caused by aliasing _hx_fields of the superclass and then pushing all the subclass' _hx_fields into it.
To replicate this problem all you really need is:
A.hx
```haxe
	class A {
		public var a: Int;
	}
```
B.hx
```haxe
	class B extends A {
		public var b: Int;
	}
```
Main.hx
```haxe
	class Main {
		static public function main():Void {
			trace(Type.getInstanceFields(A));
			trace(Type.getInstanceFields(B));
			trace(Type.getInstanceFields(A));
		}
	}
```
The expected output is of course ['a'] ['a', 'b'] ['a'] but it will be ['a'] ['a', 'b'] ['a', 'b']

The problem seems to originate from these lines in haxe/std/python/Boot.hx
```haxe
	static function getInstanceFields( c : Class<Dynamic> ) : Array<String> {
		var f = if (Internal.hasFields(c)) Internal.fieldFields(c) else [];
		if (Internal.hasMethods(c))
			f = f.concat(Internal.fieldMethods(c));

		var sc = getSuperClass(c);

		if (sc == null) {
			return f;
		} else {

			var scArr = getInstanceFields(sc);
			var scMap = new Set(scArr);
			//var scMap = [for (f in scArr) f => f];
			var res = [];
			for (f1 in f) {
				if (!scMap.has(f1)) {
					scArr.push(f1);
				}
			}

			return scArr;
		}
	}
```
Specifically, the problem seems to be that the translated code is:
```python
	@staticmethod
	def getInstanceFields(c):
		f = (c._hx_fields if (hasattr(c,"_hx_fields")) else [])
		if hasattr(c,"_hx_methods"):
			f = (f + c._hx_methods)
		sc = python_Boot.getSuperClass(c)
		if (sc is None):
			return f
		else:
			scArr = python_Boot.getInstanceFields(sc)
			scMap = set(scArr)
			_g = 0
			while (_g < len(f)):
				f1 = (f[_g] if _g >= 0 and _g < len(f) else None)
				_g = (_g + 1)
				if (not (f1 in scMap)):
					scArr.append(f1)
			return scArr
```
This is a problem because getInstanceFields returns an alias of c._hx_fields. This might not usually be a big issue (one doesn't usually attempt to change such arrays) but when the function is called on a subclass, all the subclass' _hx_fields are appended to the superclass' aliased _hx_field.

Proposed solution:
Change `Internal.fieldFields(c)` to `(Internal.fieldFields(c): Array<String>).copy()` in the haxe code. I have checked this solution manually on my computer and it worked as expected.

For the record, I have ran into this issue while on the latest haxe version 3.4.2 on windows.

P.S. I have some problems with the preview button of the issue so I might have screwed up the formatting a bit. Sorry if I did.

Thank you,
Idan

**Comment by nadako** [comment]
Thanks for the detailed report, I'll look into it!

**Comment by IdanDor** [comment]
Thank you for the very quick fix.

nadako: about commit 8de200f, my own testing seems to show that it doesn't compile well to python (it compiles to c._hx_fields.copy() which is not a method of list) because the type inference doesn't do its job there. That's why my proposed solution included the casting to Array.

Idan

**Comment by nadako** [comment]
Oh my. I should get some sleep after all, you're right!

**Comment by nadako** [comment]
Interesting though that it actually works because `list` has a `copy` method in my Python.
