### ISSUE TITLE
Constraint error after direct call

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6148]
_I_ have a constraint on parameterized function, and when I directly use the function, it gives a constraint error. I dont know if the current example should compile but I would be really nice because if it works we could change some functions in Haxe/JavaScript to make it more convenient working with DOM elements, which now requires lots of cast.

```haxe
import js.html.*;

class Test {
    static function main() {
        // add an id for testing
        js.Browser.document.body.id = "test";
        
        // good:
        
        // try with explicit type definition. works great!
        var body:BodyElement = getElementById("#test");
        body.bgColor = "red";
        
        // fail:
        
        // Edit properties directly. Constraint error. 
        // I would expect getElementById to return as Element here.
        getElementById("#test").innerHTML += "<div>Make my day</div>";
    }
    
    // wouldnt this be nice?
    static function getElementById<T:Element>(id:String):T
    {
        return cast js.Browser.document.getElementById(id);
    }
}
```

http://try.haxe.org/#CCCE0

Tested in haxe 3.4 js target but I think it was always like this.

**Comment by Simn** [comment]
We specifically delay constraint checks in order to avoid early binding of unknown types. It looks silly in your example, but changing this would look silly in other examples (when the caller context wants to bind a type-parameter to a more specific type later).
