### ISSUE TITLE
genjs, "arguments" and "eval" are absent in kwds for custom js generator

### ISSUE THREAD

**Issue by Pr05p3ro** [HaxeFoundation/haxe#6152]
Additional ES5 strict mode keywords are added to `kwds` in `generate` method:
`List.iter (fun s -> Hashtbl.replace kwds s ()) [ "arguments"; "eval" ];`
Custom js generator overrides `generate` and there is no way to extend `kwds` via `JSGenApi`

Can you add possibility to extend reserved keywords to JSGenApi or move code mentioned before out of native `generate` implementation?
Thanks.

**Comment by Simn** [comment]
I think this has been addressed in https://github.com/HaxeFoundation/haxe/commit/cdb468bd090d52df9057741163b69ee563dbe296
