### ISSUE TITLE
SyntaxError when using a const string with space as generic parameter

### ISSUE THREAD

**Issue by gogoprog** [HaxeFoundation/haxe#6153]
Hi,

This sample code :

```haxe
@:generic
class MyGenericClass<@:const Text> {
    public function new() {
        trace(Text);
    }
}

class Issue {
    static function main() {
        new  MyGenericClass<"Hello World">();
    }
}
```

Will generate wrong output code, see example with JavaScript target:

```js
// ...
var MyGenericClass_$SHello World = function() {
// ...
```

Maybe a safer naming rule would be useful?

**Comment by NuclearCookie** [comment]
Same issue using negative numbers:
```js
// ...
var MyGenericClass_$I-1$SHello_world = function() {
// ...
```

**Comment by gogoprog** [comment]
Hi,
I just tried to reproduce the issue on the current haxe development branch (64e57cc41) and the string space issue seems to be fixed.

So only the negative numbers issue is left

**Comment by Gama11** [comment]
@bendmorris seems to be the expert on fixing these `@:generic` + `@:const` issues.

**Comment by bendmorris** [comment]
I'm not the expert on anything 😛 but this: https://github.com/HaxeFoundation/haxe/issues/6978 is probably worth considering vs. trying to handle all of these edge cases ad hoc.

**Comment by Simn** [comment]
This now generates `var MyGenericClass_$_$34_$Hello_$32_$World_$34_$`.
