### ISSUE TITLE
[php] syntax error, unexpected '::'

### ISSUE THREAD

**Issue by TzA-0x000000001** [HaxeFoundation/haxe#6155]
Hello.
When I import classes that are not included in any package, I have this error: 
> Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting variable (T_VARIABLE) or '$'

It happens when I have a code like that : 

**Main.hx**
```haxe
package;
import Foo;
class Main {
    static public function main() {
        Foo.bar();
    }
}
```

**Foo.hx**
```haxe
package;
class Foo {
    statuc public function bar() {
        trace("bar");
    }
}
```

**Folder**
```
My Project
| -- Main.hx
| -- Foo.hx
```
---
To solve it, I have to do: 

**Main.hx**
```haxe
package;
import some.Foo;
class Main {
    static public function main() {
        Foo.bar();
    }
}
```

**Foo.hx**
```haxe
package some;
class Foo {
    statuc public function bar() {
        trace("bar");
    }
}
```

**Folder**
```
My Project
| -- Main.hx
| some
  | -- Foo.hx
```

Thank you for you attention.

**Comment by RealyUniqueName** [comment]
Do you compile with or without `-D php7`?

**Comment by TzA-0x000000001** [comment]
I compile without. Is it a problem ? If so, I have to check if my host is supporting php 7.

**Comment by RealyUniqueName** [comment]
It's not a problem. I just need to know your setup to reproduce this issue.

**Comment by RealyUniqueName** [comment]
Also wich haxe version do you use?

**Comment by RealyUniqueName** [comment]
@TzA-0x000000001 I can't reproduce this issue neither with Haxe 3.4.2 nor with latest development version.

**Comment by TzA-0x000000001** [comment]
@RealyUniqueName Sorry. I had some issues. I use Haxe 3.4.2 on Windows, from the official package.

**Comment by RealyUniqueName** [comment]
What's your hxml setup?

**Comment by RealyUniqueName** [comment]
I'm closing this because i can't reproduce it. Feel free to reopen if it still exists.
