### ISSUE TITLE
autoBuild static macro function

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#6156]
Create static macro function not works in autoBuild:

```haxe
#if !macro @:remove @:autoBuild(ObjectImpl.build()) #end
extern interface Object {}
 
class ObjectImpl {
#if macro
   
    public static function build() {
        var fields = Context.getBuildFields();
       
        fields.push({
            name: 'test',
            access: [Access.APublic, Access.AStatic, Access.AMacro],
            kind: FFun({
                args: [],
                expr: macro {
//                        return macro {
//			        trace('hello world');
//		        };
                },
                params: [],
                ret: null
              }),
            pos: Context.currentPos()
        });
       
        return fields;
    }
#end
}

class Test implements Object {
	public static macro function hi() {
		return macro {
			trace('hello world');
		};
	}
}
 
// Error Message: Method test not found on class Test
class Main  {
    public static function main() {
        Test.hi();
        Test.test();
    }
}
```

Also this:
```haxe
//                        return macro {
//			        trace('hello world'); // <- Unknown identifier : __mk_pos__
//		        };
```

Not works: Unknown identifier : __mk_pos__

I think is it not a bug, i think haxe don't support something like this.
I'm right?

**Comment by kevinresol** [comment]
This looks like macro in macro, which won't work.
```haxe
expr: macro {
//                        return macro {
//			        trace('hello world');
//		        };
```

**Comment by malublu** [comment]
@kevinresol 
You missread the issue:
I would generate a macro function in autoBuild:
`Access.APublic, Access.AStatic, Access.AMacro`


But i get the error:
`// Error Message: Method test not found on class Test`

The other issue: Unknown identifier : mk_pos

comes because i try to create the macro function content like this:
https://haxe.org/manual/macro-arguments.html

but both are not working.
create a macro function and create the function expression.

**Comment by RealyUniqueName** [comment]
It's impossible to generate macro methods from build macros. Perhaps compiler should throw an error in such cases.

**Comment by RealyUniqueName** [comment]
Creating macro methods in build macro is impossible. 
I think, the only thing we can do is emit an error in a build macro returns a field with `AMacro` accessor.

**Comment by RealyUniqueName** [comment]
Regarding `__mk_pos__` I think `parse_macro_expr` should emit a syntax error if it's a second call to it in a current call stack. Something like `Cannot use macro reification in macro reification`.
https://github.com/HaxeFoundation/haxe/blob/51bdcb8da149aa25b7b4c632dab18a0644ac5b8d/src/syntax/grammar.mly#L1075-L1088

**Comment by RealyUniqueName** [comment]
Closing in favor of #9080
