### ISSUE TITLE
@:impl doesn't work when underlying type is class with type parameter

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6157]
Modified from the [example in the manual](https://haxe.org/manual/types-abstract-selective-functions.html) (changed the underlying type from `T` to `Array<T>`), the following code fails with `First argument of implementation function must be Array<Unknown<0>>`. Same behavior from 3.2.1 to 3.4.0.

http://try.haxe.org/#1806A
```haxe
class Test {
    static public function main() {
    var a = new MyAbstract(["foo"]);
    a.getString();
  }
}
abstract MyAbstract<T>(Array<T>) from Array<T> {
  public function new(t) this = t;

  function get() return this[0];

  @:impl
  static public function getString(v:MyAbstract<String>):String {
    return v.get();
  }
}
```

change to `v:Array<String>` makes it go through, but loses all the abstract niceties. (e.g. `@:from` casts)

**Comment by Simn** [comment]
The manual is wrong and the compiler is right. The first argument of an abstract member-function is the underlying type, not the abstract itself.

This actually causes a lot of internal special cases and I might look into the implementation for Haxe 4. We should probably just remove the manual entry on selective functions though.

**Comment by kevinresol** [comment]
> The manual is wrong and the compiler is right.

Code is the spec? :joy:

Anyway,

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/HaxeManual/issues/227
