### ISSUE TITLE
[php] Static var of type Dynamic holding a function

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6158]
Haxe revision: 84bf7e5
If a static var is typed as `Dynamic` and holds a function, making a call to such var will fail.

```haxe
class Main {
	static function main() {
		Sys.println(Foo.make(1,2,3) + "Text");
	}
}

class Foo {
	// this doesn't work
	public static var make:Dynamic = function(a, b, c) return '$a,$b,$c';
	
	// this works
	// public static var make:Int->Int->Int->String = function(a, b, c) return '$a,$b,$c';
	
}
```

without `-D php7`

**Comment by Simn** [comment]
We have to decide if we want to maintain the old PHP generator and make bugfixes for it. It feels like a lot of duplicate work... though I don't really mind as long as @RealyUniqueName is happy.

**Comment by RealyUniqueName** [comment]
Simple fixes don't hurt me. Though i'm trying to fix all issues, i'd like to avoid any complex work regardless old genphp.

**Comment by ncannasse** [comment]
One middle ground possibility is to detect the invalid forms not supported
by old php generator and give errors at generation time for it (instead of
having runtime php errors)

On Thu, Apr 6, 2017 at 9:18 AM, Alexander Kuzmenko <notifications@github.com

**Comment by kevinresol** [comment]
> We have to decide if we want to maintain the old PHP generator

Does "old" and "new" means php5 and php7 respectively? Or the "new" generator can still generate php5 code? I don't think dropping php5 support is a good idea...

**Comment by RealyUniqueName** [comment]
New generator generates php code for PHP 7.0 and higher.
