### ISSUE TITLE
Build macro compile-time `:metadata` spillout rubbish on Haxe 3.4.

### ISSUE THREAD

**Issue by Glidias** [HaxeFoundation/haxe#6162]
On Haxe 3.4, some classes utilizing build macros will spill out rubbish compile-time  metadata listings in the type-completion box, instead of delivering the correct type completion fields for the given class. 

eg. `@:abi, @:abstract, @:access ......@:volatile`

This is fine in 3.3. Only 3.4 has this issue. 

https://github.com/eliasku/ecx/issues/11

**Comment by Simn** [comment]
Any example?

**Comment by nadako** [comment]
I often get metadata completion instead of expected one. As we talked before it's probably because of macro-generated metadata at completion position, but that's super-annoying nevertheless.

**Comment by Glidias** [comment]
Example can be found in the link, though it's not concise.  I figured out how to "fix" it in the 2nd post.

Ok, how about this example: (not sure if it trigger it though..)

Use a build macro for a class, add a `Field` with added metadata:  `meta:{ pos:Context.getLocalClass().get().pos, name:"blahblah" }` . 

The typehinting on your class goes haywire for Haxe 3.4. Instead, consider using `Context.currentPos()` to avoid this issue.

Ok, now I think I know the underlying issue (even though I'm not sure why in Haxe 3.3, it's ok, so something changed in Haxe 3.4). It's probably due to `Context.getLocalClass().get().pos` having a `min` line and `max` location. Thus, type-hinting will occur within that entire range of the class name and body, resulting in metadata completion popups for the entire range of text due to the cursor falling within the `min`/`max` range.. Likewise, for ECX's case, the `update` function field has a `from` and `to` within the entire function body and name, that's why the typehinting within the `update` function for ECX's case will go "haywire".

**Comment by Simn** [comment]
Positions of generated metadata have to be accurate. If you use the position of the entire class or field then it might be picked up by the compiler, because the requested display position is enclosed there. I don't see what we can do about that really.
