### ISSUE TITLE
[neko] Issue with Utf8.charCodeAt() and delete character (0x7F)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6166]
This code:
```haxe
import haxe.Utf8;

class TestDel {
  public static function main() {
    var del = String.fromCharCode(127);
    trace(del);
    var code = Utf8.charCodeAt(del, 0);
    trace(code);
  }
}
```

Fails on neko with this output:
```
TestDel.hx:6: ⌂
Called from ? line 1
Called from TestDel.hx line 7
Called from C:\HaxeToolkit\haxe\std/neko/_std/haxe/Utf8.hx line 76
Uncaught exception - std@utf8_get
Error: Command failed with error 1
```

But works ok for cpp/js/swf.

Neko 2.1/Haxe 3.4.2/Win7 64

**Comment by Justinfront** [comment]
Neko till 4.0 does not support unicode, fromCharCode is not really supported for Neko, I guess not much point changing documents if will be fixed quite soon and only a few notice ;)
https://github.com/HaxeFoundation/neko/issues/161#issuecomment-291847459

**Comment by azrafe7** [comment]
Thanks for the heads-up @Justinfront, didn't know about that! :)

I was mainly concerned about the other targets working differently, and at the same time me using neko for faster iterations. 

Really looking forward to cross-target support for unicode in haxe 4.0 though! (...but it would be nice to have this particular issue fixed in the mean time - if it can be confirmed it's a neko-only specific that is!)

As a sidenote: the unifill lib doesn't seem to work with hl currently.

**Comment by azrafe7** [comment]
Oh... And 127 is still in ASCII range! ;p

**Comment by skial** [comment]
Consider looking at https://github.com/mandel59/unifill which handles
unicode across all platforms.

**Comment by azrafe7** [comment]
@skial, I'm happily using it (also mentioned it in the first post). Unfortunately this specific case is an issue there too, as unifill uses haxe.Utf8 for neko in its implementation of uCharCodeAt.

**Comment by skial** [comment]
My bad ;)

**Comment by R32** [comment]
In https://github.com/HaxeFoundation/neko/blob/master/libs/std/utf8.c#L171, 

maybe can replace:
```hx
if( c < 0x7F )
``` 
to 
```hx
if( c <= 0x7F )
```

**Comment by RealyUniqueName** [comment]
This is fixed in https://github.com/HaxeFoundation/neko/commit/77ab0bda58368a029cdce68e704b7963ebd46d19
