### ISSUE TITLE
[dce] do not remove overriden methods of an extern class when class is used

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6168]
Imagine this situation:
```haxe
extern class Base {
    function f():Void;
}

extern class BaseUser {
    static function callF(b:Base):Void; // calls b.f()
}

class Child extends Base {
    public function new() {}
    override function f() {}
}

class Main {
    static function main() {
        BaseUser.callF(new Child());
    }
}
```

Currently, `dce=full` removes the overriden `f` method from the `Child` class since it's not used anywhere directly in the code, but that's not what we want (I think almost 100% time), so I think we should keep overriden methods in subclasses of extern class if those subclasses are already kept (I think this is similar to how we keep overriden methods of non-extern class subclasses).

**Comment by nadako** [comment]
(this is a real-world case I encountered with hxnodejs `Readable` stream subclasses)

**Comment by Simn** [comment]
I didn't add a test for this because tests related to externs are always a mess.
