### ISSUE TITLE
Feature request: add array.clear method

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/haxe#6173]
Haxe currently lacks a good way to clear the entire contents of an array, a basic and common task. Various libraries tend to implement their own "clearArray" helper methods to remedy this (HaxeFlixel, spinehaxe, HaxePunk...) Here are some examples:

```
// runtime scales linearly with length of the array
while (array.length > 0) array.pop();
```

```
// platform-specific untyped hacks
#if cpp
untyped array.__SetSize(0);
#else
untyped array.length = 0;
#end
```

```
// allocates an array for a return value which is then not used
array.splice(0, array.length);
```

Assuming you don't need the contents of the array returned, you want to clear them as quickly as possible, and you don't want to generate unnecessary allocations, none of these existing methods is ideal.

I propose adding a standard `clear()` method to Array:

```
/**
 * Remove all elements from the array.
 */
function clear() : Void;
```

If this is generally acceptable, I'll begin working on it ASAP.

**Comment by jdonaldson** [comment]
can't you use splice here?

**Comment by bendmorris** [comment]
I mentioned that one specifically above:

>// allocates an array for a return value which is then not used

This results in extra GC activity. For games this is a nonstarter.

**Comment by Justinfront** [comment]
arr.length works in as3 but not in flash haxe. Splice in flash for instance would likely result in a memory allocation that you don't get back, rather than clear, perhaps some thought on pooling arrays and lists for all haxe would be useful, ideally something you can use in place of a normal arrays.

**Comment by jdonaldson** [comment]
Yep, I skipped over that comment, my bad.

I'd be really cautious about adding a standard library method on the assumption of optimal cross-platform performance for this.  In some targets, it's faster to iterate through the array and clear everything.  In other targets, it's faster to internally dereference the cells and let the GC clean up on the next cycle.  In other targets, the best choice changes depending on the size of the array.  In other targets, in certain scenarios, the array allocation from splice is negligible and/or jitted away anyways.

If you're shooting for speed, the best bet is to try a bunch of approaches for your platform(s).  I'd like to read a trip report on the outcome on that.  

Haxe has that "using" import declaration that lets you attach methods to standard types as well, so you can start coding with your "clear" method right away as if it were in the standard library.

**Comment by ncannasse** [comment]
I would prefer a `.resize(length)` which allows both .resize(0) to clear and .resize(6000) to expand.

**Comment by Justinfront** [comment]
My concerns are js and c++ targets, as a user I don't want to port complex maths and then make it unreadable by having a pooling not generic solution, I really want to typedef to pooling array and not specifically manage it much.  I think that would be a good feature to add to Haxe like the ds classes. But it's probably hard but Haxe needs to keep adding advantages and there are arguments that pooling should be at language level as a choice, because it's hard to get right at the library level without ending up with multiple versions in a large project.

**Comment by bendmorris** [comment]
`resize` works for me if that's what people prefer. How do the semantics of array expansion work, would it fill the new slots with a default value based on the type? Is that undefined or target dependent?

>I'd be really cautious about adding a standard library method on the assumption of optimal cross-platform performance for this.

I'm not making such a strong claim here. Basically I just want a method to clear arrays that doesn't involve iterating over the array and doesn't do unnecessary allocations, and we currently lack one. It's entirely possible that for different arrays on different targets/platforms some approach or other might be faster or various tradeoffs might be worth it, but this option is completely missing right now.

**Comment by RealyUniqueName** [comment]
It could be `function resize(newSize:Int, ?defaultValue:T)` using platform specific defaults if `defaultValue` is not provided.

**Comment by Aurel300** [comment]
@bendmorris I assume `resize` to a larger array would behave the way the `Vector` constructor does.

> Initially `this` Vector contains `length` neutral elements:
>  - always `null` on dynamic targets
>  - `0`, `0.0` or `false` for `Int`, `Float` and `Bool` respectively on static targets
>  - `null` for other types on static targets

**Comment by Simn** [comment]
I'll look into adding resize.
