### ISSUE TITLE
[php7] @:enum abstract properties

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#6175]
An enum abstract's properties are defined as `const` but the code will still try to set those same properties in `__hx_init`.

(The `test` method here has no other use than to force php to load `Method_Impl_` because the property itself would get inlined.)

```haxe
@:enum abstract Method(String) {
    var GET = 'GET';
    public static function test()
        return Method.GET;
}

class Main {
    static function main() {
        Method.test();
    }
}
```

Will result in:
```php
final class Method_Impl_ {
	const GET = "GET";
	static public function test () {
		return "GET";
	}
	static public function __hx__init ()
	{
		// ....
		self::$GET = "GET"; // This should not be generated for const properties
	}
}
```

Which errors with:
```
Fatal error:  Uncaught Error: Access to undeclared static property: _Main\Method_Impl_::$GET
```

**Comment by RealyUniqueName** [comment]
I cannot reproduce this issue with your example. 
Which Haxe version do you use?

**Comment by benmerckx** [comment]
That's weird, just tested it on 3.4.0, 3.4.2 and ada466c and it's the same behaviour on all three.
By the way, it doesn't happen if `-dce full` is on (the const gets stripped).
