### ISSUE TITLE
Sys.print generates invalid Python 2 code

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6183]
In Python 2, `print` is a reserved word, so this code fails:

```
class PrintFail {
  static public function main() {
    Sys.print("Hello, World");
  }
}
```

```
> haxe -main PrintFail.hx -python printfail.py

>py "PrintFail.py"
  File "PrintFail.py", line 61
    Sys.print("Hello, World")
            ^
SyntaxError: invalid syntax
```

The solution is to use `print_` as a generated method name.

**Comment by nadako** [comment]
Haxe only generates Python 3-compatible code, so this is expected.

**Comment by techtonik** [comment]
I understand, but could there be an exception just for this particular change?

**Comment by nadako** [comment]
Then I think Python3 would complain. Why would we do it anyway? The generated code won't work in python 2 anyway.

**Comment by techtonik** [comment]
Python 3 will not complain, because print() is a ordinary function there. My generated code works in Python 2 so far.
