### ISSUE TITLE
Ship with shallow .git repo

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6185]
It will help to prepare patches easier if haxe dist/ also included shallow .git repo for easy patching and sending PRs. I don't know if it is possible to keep file layout identical, though,

**Comment by Simn** [comment]
I prefer to keep user/developer-related stuff separate and I think it's easy enough to send PRs via GitHub.

**Comment by techtonik** [comment]
@Simn easy for experienced people, who have a lot of time on their hands, but the process could be better.
