### ISSUE TITLE
Abstracts with implicit cast to Bool or Float can't be used with operators

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#6190]
Abstracts with implicit cast to Bool or Float can't be used with operators. Example:

    abstract Foo(Null<Float>) from Null<Float> {
        @:to function toBool() {
            return this != null;
        }
        @:to function toFloat() {
            return this != null ? this : 0xDEAD;
        }

    }

    class Test {
        
        static function testF(b: Bool, f: Float): Void {
            
        }
        
        static function main() {
            var foo: Foo = null;
            testF(foo, foo); // ok
            var test0 = (foo:Bool); // ok
            var test1 = (foo:Float); // ok
            var test2 = foo && true; // Foo should be Bool
            var test3 = foo + 100.0; // Foo should be Float
        }
    }

**Comment by kevinresol** [comment]
You need to define operator overloads:

```haxe
abstract Foo(Null<Float>) from Null<Float> {
    @:to function toBool() {
        return this != null;
    }
    @:to function toFloat() {
        return this != null ? this : 0xDEAD;
    }
    @:op(A&&B) static function andBool(l:Foo, r:Bool):Bool
    	return l.toBool() && r;
    @:op(A+B) static function plusInt(l:Foo, r:Float):Float
    	return l.toFloat() + r;

}

class Test {
    
    static function testF(b: Bool, f: Float): Void {
        
    }
    
    static function main() {
        var foo: Foo = null;
        testF(foo, foo); // ok
        var test0 = (foo:Bool); // ok
        var test1 = (foo:Float); // ok
        var test2 = foo && true; // Foo should be Bool
        var test3 = foo + 100.0; // Foo should be Float
    }
}
```

**Comment by romamik** [comment]
Yes, it works with operators. But should not this work without defining operator overloads?

**Comment by nadako** [comment]
Haxe does not try to implicitly convert abstracts for operators, i think because that could lead to a lot of confusion when there are multiple transitive to/from are involved. Not sure if this is something to be reconsidered for Haxe 4 (cc @Simn).

**Comment by Simn** [comment]
I kinda hate implicit casts and wish I never added them, so I doubt I'll look into extending their range anytime soon.

**Comment by kevinresol** [comment]
> I kinda hate implicit casts and wish I never added them

I hope that is regarding the implementation difficulties. The feature itself is very useful!

**Comment by Simn** [comment]
I'll go ahead and close this as I don't see myself wanting to work on this anytime soon. Implicit casts are pretty dangerous and mixing them with other implicit features like operator overloads would just lead to a lot of confusion.
