### ISSUE TITLE
haxe --display -h

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6192]
How to see `--display` command syntax?
```
>haxe --display -help
Error: Invalid format: -help
>haxe --display -h
Error: Invalid format: -h
>haxe --display --help
Error: Invalid format: --help
>haxe -help --display 
>haxe --help --display  
>haxe help --display  
```
???

```
>haxe -version
3.4.2 (git build master @ 890f8c7)
```

**Comment by Gama11** [comment]
Some (not all) display modes are documented here: https://haxe.org/manual/cr-completion.html

**Comment by Simn** [comment]
In my opinion it's good enough to have this on the manual. These features can't really be properly described on command line anyway, and "normal" users don't use --display manually.

**Comment by techtonik** [comment]
> These features can't really be properly described on command line anyway

Is it because `haxe` support for documenting command line options requires significant effort?
