### ISSUE TITLE
haxe --run %TEMP%\FileName.hx fails

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6193]
3.4.2
```
>haxe --run %TEMP%\ProgramName.hx
Error: Could not process argument C:\Users\user\AppData\Local\Temp\ProgramName.hx
Package name must start with a lower case character

>haxe --run ProgramName.hx
ProgramName.hx
```
Can `haxe` assume that path is a filename if it ends with `.hx`?

**Comment by Simn** [comment]
That's not how --run works. You can use `--cwd %TEMP% --run ProgramName` instead.

**Comment by techtonik** [comment]
@Simn so how's that different from `--iterp` then? If `--run` is just for class autodetection, it doesn't work.

**Comment by Simn** [comment]
--run accepts arguments from the command line, and doesn't require you to specify -main.

**Comment by techtonik** [comment]
@Simn it still assumes a lot of things about filename and class naming, so it is incomplete.
