### ISSUE TITLE
haxe --run --

### ISSUE THREAD

**Issue by techtonik** [HaxeFoundation/haxe#6194]
It will be useful if `haxe --run` could accept input from stdin.

**Comment by Simn** [comment]
This was discussed before and the conclusion was that it's tricky to get right. I don't think anyone is particularly opposed to the idea in general, but someone would have to be willing to look into it.

**Comment by techtonik** [comment]
@Simn can you link to arguments in those discussion. The only thing that needs to be implemented is auto-detection of main class. If there is only one class, why it is so hard?

**Comment by Simn** [comment]
It's not about the class, it's about reading from stdin. I don't know where this was discussed, might have been our slack. For the time being, I'm closing this as we don't have any resources to put towards this feature at the moment.

**Comment by techtonik** [comment]
@Simn so the only arguments for closing this are basically "we don't have any resources for that". Maybe leave it open for other people then?
