### ISSUE TITLE
Unsupported property combination `(get,default)`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6195]
Compiler complains about `(get,default)` properties:
```haxe
class Test {    
    static var foo(get, default):Int;
    static function get_foo() return foo;
    
    static function main() foo = 10;
}
```
https://try.haxe.org/#b2669
```
Test.hx:2: characters 11-37 : foo: Unsupported property combination
```
Why `(default,set)` is allowed, but `(get,default)` is not?
Either a valid reason should be provided in some doc (e.g. [manual](https://haxe.org/manual/class-field-property-rules.html)) or `(get,default)` should be allowed for consistency.

**Comment by Simn** [comment]
Valid reason: It's not implemented.

Solution: Implement it.

**Comment by mundusnine** [comment]
Oddly enough this is supported: 
```
class Test {    
    static var foo(get, null):Int;
    static function get_foo() return foo;
    
    static function main() foo = 10;
}
```
And isn't the behavior of null the same as default ?(i.e. by making it a physical field)

**Comment by filt3rek** [comment]
Hej all,

Is there any chance this to be implemented for Haxe 4 release please ?

**Comment by Simn** [comment]
no

**Comment by filt3rek** [comment]
Will it be implemented one day so ? I'm just asking because I don't know if this should be closed and it will let like that with "Unsupported property combination" or maybe it will be done one day ?

**Comment by Gama11** [comment]
Simn already stated in 2017 that it should be implemented. Otherwise the issue would already be closed.

**Comment by filt3rek** [comment]
Ok I just ask for a date maybe, when about ? Because as you mentionned it's opened since 2017.

**Comment by Gama11** [comment]
The date is "some unknown amount of time after Haxe 4". And two years really isn't a long time for an issue to be open, there's plenty of more important ones that have been open for much longer.

**Comment by filt3rek** [comment]
Ok. I just thought it was a "little thing" to implement that since all others combinations are done and I though it could be done "quickly". Writing setter and setting `@:isVar`is annoying.
But once again, It's certainly over my understanding.
Thanks for your answer ! :)

**Comment by Gama11** [comment]
Well, even "little things" add up - there's almost 800 open issues, but at some point Haxe 4 has to release. :)

**Comment by filt3rek** [comment]
I understand of course, and really apreciate all your work guys because I really love Haxe and work with it daily since 2006/2007 now and will never change for nothing else !

Now, is there a notation or label which defines the complexity of resolving some issues ? Maybe it could be great to have something like that, little guys like me would maybe try to help to eliminate "little issues" like that, so we would decrease number of issues faster. Because if we stuck on complex issues for long time, the number won't decrease quickly. 
Please don't take this badly, I really would like to help but I don't know OCaml and can't help this side.

Regards,

**Comment by RealyUniqueName** [comment]
Unfortunately in general case complexity of a bug to fix is unknown until the bug is actually fixed :)

**Comment by kLabz** [comment]
As for the labels, just avoid strong belgian ale :P

I guess in this case it's just a matter of a contributor having a sudden need or curiosity for implementing/fixing this over another issue.

**Comment by filt3rek** [comment]
Aleksandr,

Yes for bugs it's a bit complicated, but for features to implement it could be done.
Anyway, thanks all, thanks also Rudy for your contribution, it will be very good to have it working !

**Comment by kLabz** [comment]
Note that even if this PR is merged, it probably wouldn't be available in haxe 4.0 (which should [almost] only get bugfixes now).

**Comment by filt3rek** [comment]
I understand !
Thanks anyway for taking time to do that ! ;)

**Comment by filt3rek** [comment]
Hej !

Sorry to ask again for that, is there a reason that it's not "merged" ? I always work with nightly builds and if I understand well even it's not in the Haxe 4 release, it will be available in nightly builds right ?
(I'm not really familiar with PR so that's why I ask)

**Comment by kLabz** [comment]
It's a little hacky, I need to do it differently (and find some time to do so).
You can grab a "release" for the PR on azure, [here](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=1230&view=artifacts) if you really need this now.

**Comment by filt3rek** [comment]
Ah ok ! Thanks Rudy ;)
