### ISSUE TITLE
Infinite loops in compilation

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6199]
While investigating a compiler infinite loop, I have added acaa3ec060589e138c97512c8df4910c00400dce which mitigates the issue but doesn't really fix it.

Further investigation shows the usual culprit which are a loop in typing because of build macros. While I think this is unavoidable when doing some Context.typeOf because you might end up typing a class you're currently building, it could be avoided for other Context methods by setting `need_type = false` in macroContext/typing_timer calls.

As a result the class returned is not guaranteed to be initialized (fields might be empty / inheritance chain as well), but since we are doing a cl_build() before feeding the class to the macros I guess this should be enough.

**Comment by RealyUniqueName** [comment]
This workaround caused #6873
