### ISSUE TITLE
Sneaky issue with `Void` parameter

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#6201]
This just came up with a developer I was working with:

```haxe
private function method(param:Void = null) {

}
```

This hits a funny edge-case in the compiler, where using `Void` as a parameter would _normally_ throw an error either because you are A.) trying to pass a void parameter (which will not work) or B.) because your code does not match the number of required parameters for the method.

However, since the above code is given a default `null` value, this appears to be typed as `Null<Void>` behind the scenes. If you do not pass a parameter into the method, it will compile. At runtime, JavaScript appears to work, but the project we were testing is only targeting Flash Player at the moment. Here's what happens at runtime:

> VerifyError: Error #1014: Class Void could not be found.

This was very confusing, because it occurs the first the parent class was referenced, not when this method is called.

I am not sure if there should be an extra case in the compiler to throw an error?

Thanks :smile:

**Comment by mrcdk** [comment]
This looks like a regression, the compiler throws the following error in Haxe 3.2.1

`Test.hx:4: lines 4-5 : Arguments and variables of type Void are not allowed`
