### ISSUE TITLE
[java] -java-lib fails with modern rt.jar

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6205]
Try adding a `rt.jar` file from a modern JDK with `-java-lib` and you'll get the `Type not found : T__CONS` error.

Quick googling suggests that there's a `T_CONS` type parameter name somewhere in the std lib: https://docs.oracle.com/javase/8/docs/api/java/util/PrimitiveIterator.html, so this might be the case of java extern loader overescaping the name (note that Haxe complains about `T__CONS`, not `T_CONS`).

**Comment by foiorina** [comment]
On Ubuntu 18.04:

class Main {
	static public function main() {
		Sys.println("Hello World");
	}
}

haxe -java bin -main Main -java-lib /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar
haxe -java bin -main Main -java-lib /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar

Type not found : T__CONS

**Comment by waneck** [comment]
What version have you got? Try `haxe -version`

**Comment by foiorina** [comment]
3.4.7

**Comment by waneck** [comment]
Hmm it seems this was done on the Haxe 4 branch. I think you'll have to do a binary install of Haxe 4

**Comment by foiorina** [comment]
Ok. I will try. Thanks.

**Comment by waneck** [comment]
Post back if you still have issues

**Comment by foiorina** [comment]
Perfect. It works! Thanks!!!

I followed: https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md

1) Installed OCaml: ... The OCaml toplevel, version 4.05.0
2) Donloaded haxe: ... git clone --recursive https://github.com/HaxeFoundation/haxe.git
3) Start the main.hx: ... haxelib run hxjava hxjava_build.txt --haxe-version 4000 --feature-level 1
