### ISSUE TITLE
Use of String interpolation for structure field names has unspecified behavior

### ISSUE THREAD

**Issue by szczepanpp** [HaxeFoundation/haxe#6213]
Using this:
```
static inline var FIELD = "field_name";
(...)
var fieldName = '$FIELD'; // this works
var struct = { '$FIELD': someVar }; // this fails at runtime with "Undefined variable"
```
failing expression generates:
```
var $struct = new HxAnon([
"$FIELD" => $someVar,
])
```

Compiled with PHP7 and latest official Haxe release.

**Comment by Simn** [comment]
String interpolation for field names is not supported. I'm not sure if we should detect this.

**Comment by szczepanpp** [comment]
Alright, I thought that issue is caused by the use of inlining - got confused by the fact it's kind of working on php7 target.

[https://try.haxe.org/#e72b4](https://try.haxe.org/#e72b4)

If you look at line 16, it's working on php7 target - so it's clearly possible to handle it, question being if it should. If shouldn't - there at least could be some info in docs (that's where I looked first and didn't find anything against using it). Currently this behavior seems to be unspecified (js won't fail but generates incorrect field name, php7 non-inlined var works, php7 inlined var doesn't work).

Personally, I think it should - it lets you define structure with dynamic (possibly invalid Haxe identifier) name without resorting to the use of Reflect, as @mrcdk mentioned.
