### ISSUE TITLE
[hl] assertion failed from Sys.getPath

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6214]
1. https://github.com/HaxeFoundation/haxe/tree/development/tests/benchs/mandelbrot
2. `haxe -main Mandelbrot -hl bin/Mandelbrot.hl -D interp`
3. Grab a book or watch some netflix.
4.
```
File "_build/src/generators/hlinterp.ml", line 1754, characters 10-16: Assertion failed
C:\GitHub\haxe\std/hl/_std/Sys.hx:42: Called from fun@270 @x7
C:\GitHub\haxe\std/hl/_std/sys/io/File.hx:65: Called from fun@368 @x4
C:\GitHub\haxe\std/hl/_std/sys/io/File.hx:53: Called from fun@239 @x1
Mandelbrot.hx:107: Called from fun@26 @x119
?:1: Called from fun@373 @x13A
```

P.S.: This buffered output is annoying...

**Comment by ncannasse** [comment]
Works with latest HL, although does not terminate in a decent amount of time.
