### ISSUE TITLE
[display] "Recursive operator method" with overloaded operators

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6227]
On `@type` or `@position` requests on the `>` in line 3, an error is thrown:

```haxe
class Main {
    public static function main() {
        new Foo(4) > new Foo(3);
    }
}

abstract Foo({i:Int}) {
    public function new(i) this = {i: i};
    @:op(a > b) function f(other:Foo):Bool return true;
}
```

```
haxe --display Main.hx@70@position
```

>Main.hx:3: characters 8-31 : Recursive operator method
Main.hx:3: characters 8-31 : Cannot compare { i : Int } and { i : Int }

Interestingly, when the explicit `Bool` return of `f` is removed, it works fine (`@position` results pointing to `f` as expected etc). Tested with 27ff0a2 and 3.4.2.

**Comment by Simn** [comment]
This seems a bit crazy with the type hint making a difference... will have to investigate.
