### ISSUE TITLE
Sedlex regression

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6237]
I found that files encoded in CR (\r) line endings now give an `Invalid character 0x0D` error. Both CRLF and LF seems to works fine.

**Comment by andyli** [comment]
Ummm... But is there any system that uses only CR without a LF for line ending...?

**Comment by nadako** [comment]
I *think* the ancient Macs (like before OSX) used CR, but yeah, nowadays noone really supports that, I think.

**Comment by nadako** [comment]
Did it work in the pre-sedlex though? I'm pretty sure i copied all the regexes.

**Comment by ncannasse** [comment]
I had one file encoded as CR, and I didn't notice at all until I updated Haxe, so it requires fixing since it took me some time to understand what's wrong

**Comment by nadako** [comment]
Turns out old lexer supported this indeed, so I added it back. Beware tho, it's a thing from 1999 macos days, and I'm pretty sure you'll have issues with that in other tools.
