### ISSUE TITLE
Have any of the 3.4.* windows releases been built with newer OCaml versions?

### ISSUE THREAD

**Issue by asciiascetic** [HaxeFoundation/haxe#6238]
Hey all

I know next to nothing about OCaml so bear with me.  Some of my team mates are getting a strange error when they build our project:

    Invalid_argument("String.create")

I do not experience this problem on Linux with haxe 3.4.0, but they are seeing it on windows with 3.4.2.

grepping for clues lead me to `genswf.ml` where that exact text appears, and to a few other files (`main.ml`, `server.ml` among them) that make use of the `String.create` function, which is, I guess, [deprecated](http://caml.inria.fr/pub/docs/manual-ocaml/libref/String.html) somewhat recently?  

I don't expect the issue is straighforward b/c my team mates have only very recently been experiencing it.  We are now all using the same versions of all libraries and projects, the only differences seem to be the compiler version and the operating system.

*(update)*
Additionally, we are using OpenFL and I have checked that none of the assets we're loading are larger than 16mb, which seems to be the `Sys.max_string_length` value on 64bit systems. But because I can't reproduce this error myself I can't say much more.   

Any clues?

**Comment by ncannasse** [comment]
Most likely you're running into a limit of OCaml maximum string length in 32 bits which is quite low (~16MB). You can get a bit more information by setting the env var OCAMLRUNPARAM=b this will give you compiler stack trace

**Comment by Simn** [comment]
The related OpenFL issue was closed, so I guess we can close here as well.

**Comment by mastef** [comment]
Just adding a comment for anybody finding this issue: Updating your haxe to a 64bit build should solve this. Issue should come up when your built .js file exceeds 16MB and hits the 32bit limit for String length.

This mainly comes up on Windows systems, as even if they're 64bit, the shipped haxe binary is 32 bit for some reason.
