### ISSUE TITLE
allow casting to generic class with constrainted type argument

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#6239]
See https://groups.google.com/d/msg/haxelang/MNJCJJoXE5o/pMLcEQ3wAAAJ

For
```
class Bucket<T:Content> {
    var content:T;

    public function getContent():T { }
    public function setContent(val:T):  { }
}
```

allow casting with one of the type constraints

```
cast(obj, Bucket<Content>);
```

but not with it's possible sub-types:

```
cast(obj, Bucket<SubType_Of_Content>);
```

So probably
"Cast type parameters must be Dynamic"
must then say something like
"Cast type parameters must be Dynamic or on of their declared type constraint."

**Comment by Simn** [comment]
I don't really want to extend safe casts because they are one of the most misused features we have. People don't realize that they basically have a builtin Std.is.

**Comment by Simn** [comment]
I'm not sure why I left this open, but I still don't want to extend safe casts!
