### ISSUE TITLE
ocamlopt.opt

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#6242]
It used to be possible to use the .opt-versions that come with ocaml-native-compilers for compilation by adding `OCAMLOPT=ocamlopt.opt OCAMLC=ocamlc.opt` to make.
That gives errors now with ocamlfind, like:
`ocamlfind ocamlc.opt -safe-string  extc_stubs.c`
which is not valid. `ocamlfind ocamlc -safe-string  extc_stubs.c` works.
Is there a way to use the .opt-versions with ocamlfind?

**Comment by Simn** [comment]
I think ocamlfind always uses the opt versions.

**Comment by mockey** [comment]
Yes, apparently.
I have the following lines in my `~/.opam/system/lib/findlib.conf`:
```
ocamlc="ocamlc.opt"
ocamlopt="ocamlopt.opt"
ocamldep="ocamldep.opt"
ocamldoc="ocamldoc.opt"
```
