### ISSUE TITLE
@:getter function removed by -dce full

### ISSUE THREAD

**Issue by chatziko** [HaxeFoundation/haxe#6243]
```
import flash.display.Sprite;
class Main extends Sprite {
	public function new () {
		super ();
		trace("height: ", height);
	}

	@:getter(height)
	public function get_height():Float
		return 10;
}
```

The above outputs 0 with ```-dce full```, and 10 with ```no|std```.

There is no reflection/dynamic in this code. I guess the simplest solution would be to imply ```@:keep``` for ```@:getter```'s.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
