### ISSUE TITLE
[nekotools] neko.Web.getPostData() is null when method is other than POST

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6245]
Haxe 3.4.2

```haxe
class Main {
    static function main() {
        Sys.print(neko.Web.getPostData());
    }
}
```

Build and run server:
```bash
haxe -main Main -neko index.n
nekotools server
```

Then run `curl` against it:
```
curl -X POST --data a=b localhost:2000/index.n
a=b
curl -X DELETE --data a=b localhost:2000/index.n
null
curl -X PUT --data a=b localhost:2000/index.n
null
curl -X PATCH --data a=b localhost:2000/index.n
curl: (52) Empty reply from server
```

Note that except `POST`, the return data is null, and for `PATCH`, the server simply dies with `Invalid char reveived`

Also note that this code works with `php.Web`

**Comment by ncannasse** [comment]
That seems the right behavior to me (apart from the unsupported PATCH which is another issue).

**Comment by kevinresol** [comment]
So how does one get the body for PUT and PATCH?
