### ISSUE TITLE
macros not opimized

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#6246]
```
public static macro function test() {
	return macro trace('test' + 'test2');
}
```

js generated code:

`
haxe_Log.trace("test" + "test2",{ fileName : "Test.hx", lineNumber : 462, className : "mlb.Main", methodName : "onRequest"});`

But it should be:

`haxe_Log.trace("testtest2",{ fileName : "Test.hx", lineNumber : 462, className : "mlb.Main", methodName : "onRequest"});`

This is only an example.

Currently i fix it with a bad solution:
```
private static function _optimize(expr:Expr) {
	return Context.parse(~/' +\+ +'/gi.replace(~/"([^"]*)"/gi.map(ExprTools.toString(expr), function(e) {
		return '\'' + e.matched(1).replace('\'', '\\\'') + '\'';
	}), ''), Context.currentPos());
}

```

because the pos information would be lost.
(I have a complex macro with pos information for errors)

**Comment by Simn** [comment]
#5282

**Comment by nadako** [comment]
For constant strings like that you can do `macro $v{"test" + "test2"}`

**Comment by malublu** [comment]
I said it is a small examples ;)
Something like this (a little more complex that's generate something from a user expression).

```
public static function subtest1(e:Expr) {
    return macro testvar + 'hallo';
}

public static function subtest2(e:Expr) {
    return macro 'hallo' + testvar;
}

public static macro function test(e:Expr) {
    var e1 = subtest1(e);
    var e2 = subtest2(e);
    return macro $e1 + $e2;
}
```

Also only a simple test

'hallo' + 'hallo' => 'hallohallo'
