### ISSUE TITLE
closing timers is very costly

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6251]
This is about --times. Common.close has this piece of code:

```
(* because of rounding errors while adding small times, we need to make sure that we don't have start > now *)
List.iter (fun ct -> ct.start <- List.map (fun t -> let s = t +. dt in if s > now then now else s) ct.start) !curtime
```

This means that whenever we close a timer, we walk through all other open timers and update their starting time. I think this has a cost of O(N!) with N being the depth of timers.

We usually don't have a very high timer depth and I only really noticed this when I tried using timers per-method in my interpreter. Still, I think our timer implementation could do with a review, or perhaps be replaced with an existing solution.

**Comment by Simn** [comment]
I think we should do something here for 4.0. I tried adding some more timers to the compilation cache handling and noticed a difference in overall processing time. I understand that timers can't be 100% free, but what we have at the moment is too expensive.

**Comment by RealyUniqueName** [comment]
Why do we even run timers when `--times` flag is not provided?

**Comment by RealyUniqueName** [comment]
We can delay all calculations to the `report_times` and on new_timer/close just store start/stop times

**Comment by Simn** [comment]
We could optimize the case where we don't care about timers at all, but I'm not sure if it's worth it. Timers should have minimum influence either way because otherwise they skew the results.
