### ISSUE TITLE
[lua] Lua 5.1 vs regex flag "m"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6258]
This was isolated from dox -> [markdown](https://github.com/dpeek/haxe-markdown).

```haxe
class Main {
	public static function main() {
		~//m;
	}
}
```

In Lua 5.1, this errors with the following:

```
attempt to index upvalue '_hx_bit' (a nil value)
stack traceback:
        export/run.lua:119: in function 'super'
        export/run.lua:102: in function 'new'
        export/run.lua:133: in function 'main'
        export/run.lua:356: in main chunk
        [C]: ?
```

Working fine with Lua 5.2 and LuaJIT.

```bash
> haxe -version
4.0.0 (git build HEAD @ fedbe2c)
> lua5.1 -v
Lua 5.1.5
```

**Comment by jdonaldson** [comment]
Lua 5.1 doesn't ship with bit operators, you need to use a special library.  Here's the full list:

   luarocks install lrexlib-pcre
   luarocks install environ
   luarocks install luasocket
   luarocks install luv
   luarocks install luabitop

**Comment by jdonaldson** [comment]
I'll add a warning about the missing bitop library.
