### ISSUE TITLE
"Conditional inline" directive

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6260]
```haxe
class Test {
    static function main() {
        var code = 1;
        trace(f(code));
        trace(f(1));
        trace(f(getCode()));
    }
    
    static function getCode() {
        trace(''); // make it not pure
        return 1;
    }
    	
    inline
    static function f(code:Int)
    	return switch code {
            case 1: "A";
            case 2: "B";
            case _: "C";
        }
}
```

In the above code, Haxe is capable of inlining `trace(f(1))` into `trace("A")` directly because `f` is pure and the input (1) is known at compile time. But for `trace(f(getCode()))` it inlines the whole function body in place because the result of getCode() is not known at compile time.

What I would like to do is to inline only when the input is known at compile time, thus "conditional inline". But that probably requires some metadata or new keywords.

**Comment by Simn** [comment]
This would require some design, and would have to go through haxe-evolution.

**Comment by kevinresol** [comment]
Just for reference: https://github.com/HaxeFoundation/haxe-evolution/pull/45
