### ISSUE TITLE
[js] Class<haxe.Log> has no field clear

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe#6262]
On nightly build, js target lose `haxe.Log.clear()` method. 
HaxeFoundation@699214947f3a4d8ed93dc80e7f7b85623bff8b29

**Comment by andyli** [comment]
May be we can use https://developer.mozilla.org/en-US/docs/Web/API/Console/clear
But the `haxe.Log.clear()` will probably never be available to all targets anyway.

**Comment by Simn** [comment]
I don't see any benefit in adding a target-specific function like that.
