### ISSUE TITLE
[display] wrong signature shown in string interpolation method call

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6265]
Originally reported here: https://github.com/vshaxe/vshaxe/issues/115

```haxe
class Main {
	public static function main() {
		trace('${main()}')
	}
}
```

```
haxe --display Main.hx@64@signature
```

Signature completion shows the signature for `trace()`, rather than `main()`:

![](http://i.imgur.com/GQWfG4v.png)

**Comment by Simn** [comment]
I don't think we can fix this with how string interpolation is implemented.
