### ISSUE TITLE
[python] Reflect.field() on String

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6266]
```haxe
class Main {
	public static function main() {
		var foo = "foo";
		trace(Reflect.field(foo, "length"));
	}
}
```

This traces `3` on all targets I've tested, except Python, where it's `None`. Interestingly, there doesn't seem to be a test case for this in `Reflect.unit.hx`.

This breaks any `String#length` access in hxtemplo templates.

Haxe version: e0a28b3

**Comment by frabbit** [comment]
closed by 1500b893cd29bb05d0a1575e1fdc8e54a3b56e7a
