### ISSUE TITLE
[hl] haxe.rtti.XmlParser access violation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6269]
Running the following on HL/JIT crashes, other targets are fine.

```haxe
class Main {
	static function main() {
		new haxe.rtti.XmlParser().process(Xml.parse('
<class path="Foo" params="T">
	<field>
		<f a="x">
			<x path="Int"/>
			<x path="Int"/>
		</f>
	</field>
</class>'), "");
	}
}
```

>Uncaught exception: Access violation
Called from haxe.rtti.XmlParser.xtype(std/haxe/rtti/XmlParser.hx:573)
Called from haxe.rtti.XmlParser.xclassfield(std/haxe/rtti/XmlParser.hx:404)
Called from haxe.rtti.XmlParser.xclass(std/haxe/rtti/XmlParser.hx:381)
Called from haxe.rtti.XmlParser.processElement(std/haxe/rtti/XmlParser.hx:324)
Called from haxe.rtti.XmlParser.xroot(std/haxe/rtti/XmlParser.hx:317)
Called from haxe.rtti.XmlParser.process(std/haxe/rtti/XmlParser.hx:90)
Called from $Main.main(Main.hx:3)
Called from fun$445(?:1)

Haxe version 21f7f61, HL version HaxeFoundation/hashlink@337e3e2. Isolated from dox.

**Comment by Simn** [comment]
This is #4911.
