### ISSUE TITLE
Documentation inheritance

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6270]
Is there a way to "inherit" documentations from parent classes / impl class (for abstracts) or even arbitrary field?

```haxe
class Parent {
    /**
     *  The very informative documentation
     */
    function test() {}
}

class Child extends Parent {
    /**
     *  [Inherit documentations from `super.test`]
     *  Plus additional note
     */
    override function test()
        super.test();
}

abstract Abstract(Parent) {
    /**
     *  [Inherit documentations from `this.test`]
     *  Plus additional note
     */
    public function test()
        this.test();
}

class Arbitrary {
    /**
     *  [Inherit documentations from `Parent#test`]
     *  Plus additional note
     */
    public function any() {}
}
```

**Comment by Gama11** [comment]
I don't think there is. Something like [JavaDoc's `@inheritDoc`](https://docs.oracle.com/javase/6/docs/technotes/tools/solaris/javadoc.html#@inheritDoc) would be very useful.

**Comment by Simn** [comment]
I don't think this should be done at compiler-level. The information is available and can be picked up by whatever tool is processing the data. This should be fixed in dox or other tools that process documentation.

**Comment by Gama11** [comment]
How would that work for the display queries that include docs?

**Comment by Simn** [comment]
It has bothered me for a while that we send the documentation of entire classes on every completion request. Would be much better if this was a 2-step operation where the IDE can explicitly request documentation for a list of types/fields.
