### ISSUE TITLE
[cs/java/php7] Reflect.callMethod() on String#indexOf()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6276]
This was isolated from Dox -> hxtemplo (and is the reason why Dox is incompatible with the C# / Java targets).

```haxe
class Main {
	public static function main() {
		var s = "foo";
		var indexOf = Reflect.field(s, "indexOf");
		trace(Reflect.callMethod(s, indexOf, ["."]));
	}
}
```

On Java, this errors with:

```
Exception in thread "main" Haxe Exception: No compatible method found for: indexOf
        at haxe.lang.HaxeException.wrap(HaxeException.java:43)
        at haxe.lang.Runtime.slowCallField(Runtime.java:455)
        at haxe.lang.StringRefl.handleCallField(StringRefl.java:140)
        at haxe.lang.Runtime.slowCallField(Runtime.java:382)
        at haxe.lang.Runtime.callField(Runtime.java:524)
        at haxe.lang.Closure.__hx_invokeDynamic(Closure.java:27)
        at haxe.root.Reflect.callMethod(Reflect.java:81)
        at haxe.root.Main.main(Main.java:41)
        at haxe.root.Main.main(Main.java:13)
```

C#:

```
Unbehandelte Ausnahme: haxe.lang.HaxeException: Invalid calling parameters for method indexOf
   bei haxe.lang.Runtime.callMethod(Object obj, MethodBase[] methods, Int32 methodLength, Object[] args) in haxe\std\cs\internal\Runtime.hx:Zeile 499.
   bei haxe.lang.Runtime.slowCallField(Object obj, String field, Object[] args) in haxe\std\cs\internal\Runtime.hx:Zeile 635.
   bei haxe.lang.StringRefl.handleCallField(String str, String f, Object[] args) in haxe\std\cs\internal\StringExt.hx:Zeile 219.
   bei haxe.lang.Runtime.slowCallField(Object obj, String field, Object[] args) in haxe\std\cs\internal\Runtime.hx:Zeile 595.
   bei haxe.lang.Runtime.callField(Object obj, String field, Int32 fieldHash, Object[] args) in haxe\std\cs\internal\Runtime.hx:Zeile 643.
   bei haxe.lang.Closure.__hx_invokeDynamic(Object[] dynArgs) in haxe\std\cs\internal\Function.hx:Zeile 78.
   bei Reflect.callMethod(Object o, Object func, Array args) in haxe\std\cs\_std\Reflect.hx:Zeile 87.
   bei Main.main() in Main.hx:Zeile 5.
   bei EntryPoint__Main.Main() in Main.cs:Zeile 8.
```

While testing a few other targets, I noticed that there are also errors on Lua and PHP7. In both cases, it already fails during `Reflect.field()` (returns `null`).

Haxe version: acc026c

**Comment by RealyUniqueName** [comment]
I wonder if `Reflect.field()` should only guarantee to work on anonymous structures as documented for `Reflect.hasField()` and `Reflect.fields()`.
Ping @simn

**Comment by Simn** [comment]
I'm afraid not...

**Comment by RealyUniqueName** [comment]
Looks like inconsistency )

**Comment by Simn** [comment]
It's an intentional inconsistency. I'm guessing the reason is that it is much simpler to support than the inspection reflections: You already have to support field access through Dynamic anyway, so the following should be the same complexity-wise:

```haxe
var d:Dynamic = yourClass;
d.yourField;
```
```
Reflect.field(yourClass, "yourField");
```

**Comment by RealyUniqueName** [comment]
While we're at it, should this work as well?
```haxe
var s = 'hello';
assertTrue(Reflect.compareMethods(Reflect.field(s, 'indexOf'), Reflect.field(s, 'indexOf'));
```

**Comment by Simn** [comment]
If it works through Dynamic, it should work through Reflect.field. Otherwise I have no idea.

**Comment by jdonaldson** [comment]
Whoops, leaving this open for the other platforms.

**Comment by RealyUniqueName** [comment]
I've fixed it for php7, but i don't want to do it for php :)
If someone absolutely need it for old php generator, let me know.

**Comment by Gama11** [comment]
@RealyUniqueName I think it already works with the old generator?

**Comment by RealyUniqueName** [comment]
not for all string methods

**Comment by nadako** [comment]
Ehm... This is not guaranteed or supposed to work on any target:

```haxe
var charAt = s.field("charAt");
eq(s.charAt(0), charAt(0));
```

... mainly due to missing `this` binding.  One has to call those with `Reflect.callMethod`.

**Comment by jdonaldson** [comment]
Yeah, unfortunately I had to disable this test.  Lua in particular has issues with extracting fields from instances and applying them as anonymous functions.

For Lua, the current logic is:

1. Function fields extracted through reference and assignment are bound to the instance
2. Function fields extracted through Reflect are **not** bound to the instance.

E.g.
```haxe
var t = s.substr; // substr bound to "s"
var t = Reflect.field(s, "substr"); // substr is the raw function reference.
```

This allows ``Reflect.callMethod()`` to bind a function to a new instance,  while also allowing for easy auto-binding when working with anonymous types.

I'm not seeing a compelling reason to support other reflection use cases with different behavior.  So, I really hope we can leave it to that.

**Comment by nadako** [comment]
Isn't the original issue was about calling with `Reflect.callMethod`? Why the test tries to call raw functions? This is unspecified and a target maintainer doesn't have to thru hell to support it, I think :)

**Comment by RealyUniqueName** [comment]
My bad. I'll fix it today.

**Comment by jdonaldson** [comment]
Thanks, more fodder for the Lua FAQ.

**Comment by RealyUniqueName** [comment]
Reenabled this test

**Comment by Simn** [comment]
Fails on python now. Please fix or disable somewhat quickly.

**Comment by RealyUniqueName** [comment]
Fixed python.

**Comment by RealyUniqueName** [comment]
> Simn removed platform-cs platform-java labels

Aren't this going to be fixed fo cs and java?

**Comment by Simn** [comment]
I didn't see it fail so I assumed it was working. Feel free to re-label.

**Comment by frabbit** [comment]
@RealyUniqueName not a good python fix, look at length array handling.

**Comment by waneck** [comment]
The issue there is that `indexOf` takes 2 parameters: `str`, and `startIndex`. If you provide the `startIndex` value, it works on both Java and C# (test incoming)

**Comment by ncannasse** [comment]
@waneck is there no way to support reflection for optional arguments ?

**Comment by waneck** [comment]
Are Java and C# the only targets that do not support that? I could potentially add this feature, but it isn't supported right now

**Comment by ncannasse** [comment]
Can you make a PR with a unit test so we can see ? :) If the feature can be added that would be good. So far all the platforms I have been personally using (JS, HL, Neko, Flash) have support for it.

**Comment by Simn** [comment]
This is tracked in #7524.
