### ISSUE TITLE
How to override a generic method?

### ISSUE THREAD

**Issue by thronecode** [HaxeFoundation/haxe#6284]
My understanding about generic types in Haxe is yet limited and I can't find any clear explanation on how to do it. (OOP in general isn't a problem for me, but I'm still a toddler in Haxe..)

```haxe
typedef Group = TypedGroup<Basic>;
class TypedGroup<T:Basic> extends Basic {

    public function Foo(Object:T):T {
        // Do something with "Object"
        return Object;
    }

};
```

```haxe
class Layer extends Group {} ???
```

How would you go about 'overriding' the Foo method in a child class?

p.s: If you're a HaxeFlixel user, you probably know TypedGroup (FlxTypedGroup). I just removed the Flx'es to make the code more readable. 
I'm extending it to create a layering functionality.

TIA.

**Comment by Simn** [comment]
This is not the right place to ask Haxe questions. Please refer to one of the community channels listed at http://haxe.org/foundation/contact.html
