### ISSUE TITLE
Full DCE getting rid of supercalls in JS

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#6288]
Is it normal for `dce=full` to get rid of supercalls?

I have this code:

```haxe
package xene;

import js.Promise;

 @:jsRequire('@xene/core', 'Dialog')
 extern class Dialog {
   public static var match: String -> Bool;

   public function new(
       ?bot: Dynamic,
       ?chat: String
   );

   public function message(message: Dynamic):Promise<Dynamic>;
   public function talk(): Promise<Dynamic>;
}
```

Then this concrete class:

```haxe
 package dialogs;

 import js.Promise;
 import xene.Dialog;

 using helpers.StripIndent.StripIndentExtender;

 class Default extends Dialog {
   static var isDefault = true;
   var avengerOath = "
     > This is a dialog from the Haxe bot!
   ".stripIndent();

   public override function talk(): Promise<Dynamic> {
     return this.message(avengerOath);
   }
 }
```

If I use `dce=full`, I get this in the output, which brakes app:

```javascript
var dialogs_Default = function() { };
```

Otherwise, if dce is the default, then it works correctly:

```javascript
 var dialogs_Default = function(bot,chat) {
   this.avengerOath = helpers_StripIndentExtender.stripIndent("\n    > This is a dialog from the Haxe bot!\n  ");
   xene_Dialog.call(this,bot,chat);
 };
```

If I put a `@keep` in the `Default` class, it works, but I’d like to avoid that, and firstly, understand why this is happening at all.

**Comment by back2dos** [comment]
It's hard to tell without context, but I assume it's because you never instantiate the class. If you do, the super call is kept (see generated JS code of https://try.haxe.org/#7AB89). 

The constructor is not needed, so it is thrown away. The class still has to be a function, because you want `Std.is` to work, which [relies on instanceof](https://github.com/HaxeFoundation/haxe/blob/development/std/js/Boot.hx#L173), and that throws a TypeError of the right operand is not a function.

**Comment by fullofcaffeine** [comment]
@back2dos You nailed it. The instance of the `Dialog` class is created by the TS lib, so Haxe is not aware of that. Makes total sense now. I guess the only way to avoid using `@keep` would be a total rewrite of the used lib in Haxe, right? 

So it's not a bug at all. Thank you for clarifying!

**Comment by back2dos** [comment]
One option is to [add `@:keepSub` on `Dialog`](https://try.haxe.org/#dd0CD) which keeps all of the subclasses, if that is what you want ;)

**Comment by fullofcaffeine** [comment]
Oh! That's perfect! Thanks!

**Comment by RealyUniqueName** [comment]
Duplicates https://github.com/HaxeFoundation/haxe/issues/6062
