### ISSUE TITLE
Enum abstract field overshadows class name

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/haxe#6296]
This was reported in HaxePunk (https://github.com/HaxePunk/HaxePunk/issues/486). It seems that fields in enum abstracts will overshadow class names when that abstract is imported. For example:

```
@:enum
abstract MyAbstract(Int)
{
    var Math = 123;
}

class Main
{
    public static function main()
    {
        trace(Math.round(1.5));
    }
}
```
>Test.hx:11: characters 14-24 : MyAbstract has no field round

In the case reported on HaxePunk, the user had a root level `G` class and imported an abstract defining a `G` field. Since the user's `G` class isn't namespaced I'm not aware of another way to reference it.

Is this expected behavior? For a class in the root namespace, is there any workaround?

**Comment by Gama11** [comment]
You can use `import .. as` as a workaround:

```haxe
import Math as Math2;

trace(Math2.round(1.5));
```

**Comment by nadako** [comment]
This is expected behaviour as per [resolution order](https://haxe.org/manual/type-system-resolution-order.html), but I gotta say I find it rather annoying as well, recently had to use full package path (or `std.` prefix for toplevel types) to work that around without importing with different name.

**Comment by bendmorris** [comment]
I guess the case I'm hitting is "Imported enum as constructor 'i'"? I'm surprised that this would apply to `@:enum` values, which aren't really "constructors".

**Comment by Simn** [comment]
We try to make `enum` and `@:enum abstract` behave the same for consistency. The documentation could perhaps be updated to mention the latter explicitly. Other than that, this is working as intended and I don't think we should change it. Resolution order always has the potential to be annoying.
