### ISSUE TITLE
Wrong reconstruction of Map inline

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6307]
I was trying to understand why IntMap accesses are triggering Dynamic Int allocation, and I found the following:

```haxe
class Main  {

	var m : Map<Int,String>;

	function new() {
		m = new Map();
	}

	inline function get( bits : Int ) {
		var v = m.get(bits); 
		return v == null ? "kkk" : v;
	}
	
	static function main() {
		var m = new Main();
		var x = m.get(55);
		trace(x);
	}

}
```

Here's the Main.get dump which correctly uses a Field on FInstance haxe.ds.IntMap

```
	inline function get[Function:bits : Int -> String]
		[Arg:Int] [Local bits(4290):Int]
		[Block:Dynamic]
			[Var v(4295):Null<String>]
				[Call:Null<String>]
					[Field:key : Int -> Null<String>]
						[Cast:haxe.ds.IntMap<String>]
							[Cast:IMap<Int, String>]
								[Field:Map<Int, String>]
									[Const:Main] this
									[FInstance:Map<Int, String>]
										Main
										m
						[FInstance:key : Int -> Null<String>]
							haxe.ds.IntMap<String>
							get
					[Local bits(4290):Int]
```

But the inlined version in Main.main uses a Field on FInstance haxe.IMap which is an interface, so the field is called dynamically (through interface dispatching) AND trigger a dynamic wrapping (because of the type parameter):

```
		[Block:Void]
			[Var m(4296):Main] [New:Main] Main
			[Var v(4301):Null<String>]
				[Call:Null<String>]
					[Field:k : Int -> Null<String>]
						[Cast:IMap<Int, String>]
							[Cast:IMap<Int, String>]
								[Field:Map<Int, String>]
									[Local m(4296):Main]
									[FInstance:Map<Int, String>]
										Main
										m
						[FInstance:k : Int -> Null<String>]
							haxe.IMap<Int, String>
							get
					[Const:Int] 55
```

This is a huge problem, not sure if it's a regression or not.

**Comment by ncannasse** [comment]
Actually the error is again the double-cast which instead of recasting to IntMap does a double IMap cast

**Comment by Simn** [comment]
This was fixed by https://github.com/HaxeFoundation/haxe/commit/7e4cba6fcd6155e7b367794ab961c3a08d41169c. I'd love to add a test for it, but I don't know how. Instead, we should "test" this by having some benchmarks.
