### ISSUE TITLE
Eval issue

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6308]
While investigating the current Eval issue with Northgard, I'm getting another (unrelated) error at runtime:

```
hl.types.ArrayAccess does not have field length

Called from $Reflect.setField (D:\Projects\haxe\std/hl/_std/Reflect.hx line 40)
Called from haxe.Unserializer.unserializeObject (D:\Projects\haxe\std/haxe/Unserializer.hx line 196)
```

It's related to compilation server and it seems that after a few changes the Serializer is no longer able to detect that we are serializing Arrays and instead serialize them as objects.

**Comment by ncannasse** [comment]
I didn't find a good way to reproduce, but I think we should add "macro" (or eval) to the #if in haxe.Serializer when checking the class name instead of checking the class value. Because of context change we might serialize some Array coming from another context so the classes values are no longer ==

**Comment by Simn** [comment]
Ah that sucks. I was hoping that I could rely on physical equality for this, but with the compilation server I can't in cases such as this. I guess I'll resort to comparing their paths then.

**Comment by back2dos** [comment]
Might I suggest this:

```haxe
@:coreType @:runtimeValue abstract Class<T> {
  #if macro
  @:op(a == b) static public function eq<T>(a:Class<T>, b:Class<T>) 
    return a == b || Type.getClassName(a) == Type.getClassName(b);
  #end
}
```

Plus use it in [`__interfLoop`](https://github.com/HaxeFoundation/haxe/blob/development/std/neko/Boot.hx#L57):

```haxe
if (Class.eq(cc, cl)) 
  return true;
```

That way it should be dealt with not just for Serializer. People using classes as keys in `ObjectMap` might still bump into that, but that's not really supposed to work I guess.

**Comment by Simn** [comment]
@ncannasse: See if that helped.

**Comment by ncannasse** [comment]
The thing is that I was not able to reproduce :'( It often occurred while I was working at fixing #6308 but I couldn't turn it into an actual reproducible step-by-step example
