### ISSUE TITLE
Windows development builds are broken

### ISSUE THREAD

**Issue by mrcdk** [HaxeFoundation/haxe#6309]
I've downloaded the latest windows haxe build from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/haxe_2017-05-28_development_a4fc3cc.zip and I get a weird problem:

![http://i.imgur.com/stvQN2c.png](http://i.imgur.com/stvQN2c.png)

The error says:
`The application was unable to start correctly (0xc000007b). Click OK to close the application.`

It works when using the git bash but it doesn't when using the windows cmd.

I've tracked down the last working version to this http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/haxe_2017-05-18_development_6f71e98.zip which the last build before this commit was made https://github.com/HaxeFoundation/haxe/commit/11cb619d7d4c9274520e7fbd3956cd3ecf3ba3a5 It looks like this commit fixed the appveyor builds https://github.com/HaxeFoundation/haxe/commit/9e1aa16e82e57e84ebc801893dff6debe0eaf9f4 but it doesn't fix the packaged ones.

I'm not 100% sure if it's my problem or not, but this hashlink appveyor test fails with the same error code https://ci.appveyor.com/project/HaxeFoundation/hashlink/build/192/job/nagx4mlya72d1b6i

`0xc000007b` is `-1073741701`

**Comment by andyli** [comment]
Looks like you have a copy of 32-bit zlib1.dll or libpcre-1.dll in PATH.
We recently switched to producing 64-bit compilers, and it should load the dll files we bundle them (if there is no such dll in PATH, which should be the case).

**Comment by mrcdk** [comment]
Right, I checked where the zlib and pcre dlls are on my system:

![http://i.imgur.com/hTrSaOI.png](http://i.imgur.com/hTrSaOI.png)

Which should take the ones in the same directory like it seems to do

![http://i.imgur.com/8nqWB9P.png](http://i.imgur.com/8nqWB9P.png)

But it looks like zlib1.dll is a x86 dll so it doesn't load it

![http://i.imgur.com/cOGO15h.png](http://i.imgur.com/cOGO15h.png)
![http://i.imgur.com/a7hhXkm.png](http://i.imgur.com/a7hhXkm.png)
![http://i.imgur.com/s409w0S.png](http://i.imgur.com/s409w0S.png)

**Comment by mrcdk** [comment]
I've copied the mingw zlib1.dll because I could run the executable from it and it works now

![http://i.imgur.com/aWQpCVI.png](http://i.imgur.com/aWQpCVI.png)

I guess the bundled zlib1.dll isn't the correct one

**Comment by andyli** [comment]
Indeed! Our `make package_bin` uses `which` to locate the dll, and since it doesn't check the bitness, it picked the 32-bit ones since they are the first ones to be found.
