### ISSUE TITLE
HL unit test failures

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6311]
HL is still allowed to fail, and by now we have missed a few new problems:

```
Command: haxe [compile-hl.hxml]
TestMain.hx:37: Generated at: 2017-05-29 09:35:14
TestMain.hx:39: START
Test.hx:275: ABORTED : Hlinterp.Runtime_error("Unresolved native std@dyn_op") in unit.TestOps.testOps
Test.hx:278: STACK :
Called from module unit/TestOps.hx:70: Called from fun@1301 @x4EB
Called from module /home/travis/build/HaxeFoundation/haxe/std/hl/_std/Reflect.hx:85: Called from fun@341 @x49
EReg.unit.hx:112: false should be true
UInt32Array.unit.hx:13: -2 should be 4294967294
Issue2735.hx:8: 4294967295 should be -1
Test.hx:221: DONE [6842 tests]
Test.hx:222: SUCCESS: false
Test.hx:275: ABORTED : Hlinterp.Sys_exit(1) in unit.hxcpp_issues.String
Test.hx:278: STACK :
Called from module unit/Test.hx:236: Called from fun@1109 @x8C
Command exited with 0 in 4s: haxe [compile-hl.hxml]
test hl succeeded
```

This should be sorted out so we can actually run the tests properly.

**Comment by ncannasse** [comment]
Should be ok now, still the issue with Hlinterp.Sys_exit, but it seems to be exactly the same handling as the one in Haxe macros so I'm not sure what to change here

**Comment by Simn** [comment]
I fixed that in https://github.com/HaxeFoundation/haxe/commit/e5576893a206ac6dc9e5a85c41e1490c5ab65c62, but there's still one more failure: `EReg.unit.hx:112: false should be true`

**Comment by Simn** [comment]
Oh man, haha. I thought HL was on some allowed-failures list, but it turns out that botched Sys.exit was what made the tests pass. So now they actually fail due to that EReg issue.

**Comment by ncannasse** [comment]
EReg.escape is something new, there seem to be something wrong with HL support for it here

**Comment by ncannasse** [comment]
After latest commit, all HL unit tests are passing on my computer. Are they correctly enable on CI ?
