### ISSUE TITLE
assert statement for haxe

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#6317]
I often want to have an assert statement which is part of the std lib. Something like `haxe.Assert.isTrue(expr, msg)` which translates to something like:

```haxe
if (!expr) {
    throw msg;
}
```

The expression should only be generated if `-D assert`. If `-debug` implies `-D assert` is open for discussion.

I know that everyone can use their own asserts based on macros, but having a common base allows other more sophisticated libraries to build their own specialized asserts on top of this.

Any opinions on this??

**Comment by frabbit** [comment]
i should add that this assert statement is not intended for unit tests, it's mostly to check pre- and postconditions of functions.

**Comment by back2dos** [comment]
> I know that everyone can use their own asserts based on macros, 

Why would one require macros for it?

```haxe
class Assert {
  static inline function isTrue(expr:Bool, msg:String) {
     #if assert if (!expr) throw msg; #end
  }
}
```

> but having a common base allows other more sophisticated libraries to build their own specialized asserts on top of this.

Can you explain this bit? What exactly does this allow?

**Comment by frabbit** [comment]
ok with inline this can be solved, but my pr is more about having a common building block, that everyone can build on.

**Comment by back2dos** [comment]
> having a common building block, that everyone can build on.

Again: what does one build on it and how? You're insisting it is useful, but I would very much like to hear some explanation of why you would think that.

**Comment by frabbit** [comment]
well you can build other asserts on top of it like Assert.size(array, 5) or Assert.isNotNull(x) and all of them can rely on the same define to be enabled. In general it helps to discover errors during development and it's inconvenient to add a library just for this. My argument is that it's a minor helpful addition without much cost. 

And when it's implemented as a macro it can actually show the raw expression like:
```
Assert.isTrue(a > b);
```
which can lead to the default error message "assertion failed, a > b is not true" with some more implementation effort we can show errors like "assertion failed, a > b but it is 0 > 2", this can be done for some common cases like x > y or x == y etc.

**Comment by back2dos** [comment]
Sorry, but this doesn't make it any clearer.

If you're suggesting that there should be an actual first class "assert statement", as you did in the title, it's highly unlikely to be an "addition without much cost".

If OTOH you're suggesting that the implementation `if (!expr) throw msg;` is a sensible basis to build assertions on, I cannot agree for a number of reasons:

1. throwing exceptions is not an option in asynchronous tests
2. termination is not necessarily desirable when an assertion fails - particularly in a production environment
3. even in synchronous test scenarios, terminating the test case on failed assertion suppresses any further output that might help in understanding why the test failed

**Comment by ousado** [comment]
- OMG someone used the term "assert statement" - let's organize protests at @frabbit's door.

**Comment by frabbit** [comment]
it's not for tests, it's to make sure that pre and post conditions are met and to discover invalid state that you do not expect. It's just more helpful than something like throw "assert". like the good old assert in c or java or ocaml or haskell or rust or ...

**Comment by markknol** [comment]
It could be something like this: http://code.haxe.org/category/macros/assert-with-values.html

**Comment by frabbit** [comment]
Indeed

**Comment by Simn** [comment]
Closing due to lack of traction.
