### ISSUE TITLE
[eval] "Error: process_run" can't be caught

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6333]
```haxe
class Main {
    public static function main() {
        runProcess();
    }

    macro static function runProcess() {
        try {
            new sys.io.Process("foo", []);
        } catch (e:Any) {
            trace("caught it!"); // doesn't trigger with eval
        }
        return macro null;
    }
}
```

With eval, this prints `Error: process_run` rather than `"caught it!"`. Working as expected with the old macro interpreter, which makes this a regression.

_Background:_ Flixel has a macro that tries to run `git` - so even though I locally tested eval before merge, and Flixel's Travis runs Haxe dev builds, so this didn't come up until a user reported it (https://github.com/HaxeFlixel/flixel/issues/2078).

**Comment by Simn** [comment]
I fixed this specific case. Leaving this issue open because I should probably do that for the other Process API as well.
