### ISSUE TITLE
Building Haxe 3.4.2+ on Ubuntu 14.04 64-bit (requires OCaml 4.02 PPA)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6337]
I'm not sure where to put this info, so I'll just file and close this issue. This is my log for installing OCaml 4.02 and building Haxe (latest as of now) on Ubuntu 14.04.

FYI, some background reading on [this version requirement](https://github.com/HaxeFoundation/haxe/issues/5962), and recent [ocaml dependency work](https://github.com/HaxeFoundation/haxe/issues/6143).

The [documentation](https://haxe.org/documentation/introduction/building-haxe.html) says to install OCaml 4.02. For this to work on 14.04, you need to install a [PPA repository](https://launchpad.net/~avsm/+archive/ubuntu/ocaml42+opam12).

```
sudo add-apt-repository ppa:avsm/ocaml42+opam12
sudo apt-get update
sudo apt-get install ocaml opam
```

Then run opam init, and probably easiest to allow it to modify `~/.bash_profile`. I ran the eval command to make opam work in the shell I was already using:

```
opam init
eval `opam config env`
```

Then install the ocaml dependencies required to build Haxe (I'm not sure why the Haxe makefile doesn't handle some of this?):

```
opam install ocamlfind extlib sedlex xml-light extlib rope ptmap
```

I ensured I had a clean haxe repo with submodules intialized:

```
git clone --recursive https://github.com/HaxeFoundation/haxe.git
```

Then the build worked:

```
cd haxe
make
```

Feel free to add comments if it works / doesn't work for you.

**Comment by Simn** [comment]
Yeah the documentation is outdated. Should be a haxe.org issue, but I'm lazy so I'll just reopen this one.

**Comment by jcward** [comment]
I dunno, I'm not sure the documentation needs to specify instructions for every possible OS. It's fine to just say "install ocaml 4.02" -- and it's up to you to figure out how to do that. I merely wanted to jot down exactly how I did that for the OS that I use most often. :)
