### ISSUE TITLE
[display] top-level completion must check for duplicates

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6341]
```haxe
import Main.E.a;

enum E {
    a;
}

class Main {
    static var a:Int;
    function new(a) {
        |
    }

    static function main() {
    }
}
```

Invoking toplevel completion here returns 4 instances of `a`: ![](http://i.imgur.com/ML7wzCj.png) while it must return only one with respect to resolution order.

**Comment by Simn** [comment]
Should they really be completely omitted? I'm thinking the compiler could tell the IDE how to disambiguate them.

**Comment by nadako** [comment]
I thought about that, but decided that it's a toplevel identifier completion after all, and the idea of completing anything with auto-disambiguation is a different feature...

**Comment by Simn** [comment]
(How) do other IDEs handle that?

**Comment by nadako** [comment]
Well in most advanced IDEs you just type some letters without even switching language, press a key and get an identifier resolved, imported and a call generated. :)
