### ISSUE TITLE
eval.Lib - implementation?

### ISSUE THREAD

**Issue by derRaab** [HaxeFoundation/haxe#6343]
While running automated test on travis ci I discovered this issue:

`You cannot access the neko package while targeting eval (for neko.Lib)`

Here's the build failing: https://travis-ci.org/derRaab/de-superclass-haxe/jobs/240257451 .

Since the development Haxe version switched from neko to the new eval target, I understand the problem - but now I wonder if I should just hold my breath until eval.Lib will be implemented?

Or might that never happen?

https://github.com/derRaab/de-superclass-haxe/blob/master/dev/flash/Install.hx line 97 is the problem:  `neko.Lib.rethrow(e);`

How could I change that in the meantime?

**Comment by Simn** [comment]
I don't like these rethrow functions very much because the compiler doesn't respect them for control flow analysis. Not sure if this is really worth it, especially considering that we have debugger support built-in. Maybe just use a plain old `throw e` instead?

**Comment by derRaab** [comment]
Well, this is used in a catch statement so wouldn't it be cool to "keep the previous exception stack"?

**Comment by Simn** [comment]
Yes I know why you want it, but that doesn't really address my concerns. I might dig up #5001 again to deal with this properly.

Reading through that issue also reminded me that it's a very strange API. Targets don't usually support re-throwing something other than the exception most recently caught, so having the option to provide an argument to rethrow doesn't make any sense.

**Comment by derRaab** [comment]
Ok, so I simply changed the line to
```
#if neko
neko.Lib.rethrow(e);
#else
// Only neko handles proper rethrowing.
throw e;
#end
```

That's fine for me. I just copied the implementation from https://github.com/andyli/HaxeCI/blob/master/flash/Install.hx.

**Comment by Simn** [comment]
I'll close this as I don't plan on adding rethrow as a library function at the moment. I'll see what we can do about rethrow-detection.
