### ISSUE TITLE
[cs] invalid cast methods generated

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6352]
reduced from our test suite, which compiles only because we have a name clash between a type parameter name and some class name

```haxe
class Base<T> {}
class Child1<A, B> extends Base<B> {}
class Child2<T> extends Child1<T, T> {}
```

```
error CS0246: The type or namespace name 'A' could not be found (are you missing a using directive or an assembly reference?)
```

problematic generated code:
```cs
public class Child2<T> : global::Child1<T, T>, global::Child2 {

	// ...snip...
		
	public override object Base_cast<T_c>() {
		return this.Child2_cast<A>();
	}

	// ...snip...
	
}
```

**Comment by nadako** [comment]
I spent several hours trying to understand what's going on there in `RealTypeParamsModf.create_stub_casts` but type parameter handling is just beyond my comprehension.
It seems that when it's processing `Child1<A,B>` while generating cast for the `Child2<T>`  there's only `Child1.A` in `reverse_params`, but when it tries to process further and gets to `Base<T>`, it tries to find a mapping from `Child1.B` to `Base.T` and fails because `reverse_params` only has `Child1.A`... So to say, I don't even understand what did I just write :-P

@waneck pls halp

**Comment by nadako** [comment]
Note that 94809e3dc69500a3cbfad4bd28f499a689571f4f surfaced this issue in our unit tests (because some types were eliminated by DCE that accidentally had the same name as type params), so I added `#if !cs` at `TestOverloads.hx` with a TODO note for now. Please, don't forget to remove that after fixing this issue :)

**Comment by waneck** [comment]
Yeah that type parameter handling gave me a headache :P The issue was that reverse_params should store the type parameters that the current cast function should be called, when in reference to the current parent class
