### ISSUE TITLE
Date.fromTime( 0.0 ).getHours() != 0 -> detection for timezone offset?

### ISSUE THREAD

**Issue by derRaab** [HaxeFoundation/haxe#6353]
While writing some unit test I discovered, that on some targets this line of code actually becomes true:

```
( Date.fromTime( 0.0 ).getHours() != 0 )
```

So we all know unix timestamp 0 does represent 1970-01-01T00:00:00Z, but in Haxe I might get an Date with the local time but - without an api regarding timezone handling or utc time - no chance to know about the current timezone. Except for this line?

I also tried to fiddle around a bit at https://try.haxe.org/#70DdE . There you can see, that at least in Javascript the trace output contains the timezone. But on neko it won't contain any information regarding the timezone.

So while I'm writing this I wonder if this line of code couldn't be the base for adding utc specific apis to the core haxe date object? Or has this already been done somewhere?

After a view test I identified php as a target which doesn't work the same but always returns 0 for getHours(). But on PHP might be some methods that would return the timezone offset as well.

So what do you think? I guess you've all been at this point already?

**Comment by RealyUniqueName** [comment]
Old php generator defaults to UTC time. To change it you need to add timezone settings to php.ini or use `date_default_timezone_set`: https://github.com/HaxeFoundation/haxe/issues/4118
New php generator defaults to your local timezone.

**Comment by derRaab** [comment]
Ok, thanks, I'll keep that in mind and will hopefully setup php7 for testing as well. But it still means I could at least always figure out UTC time.
