### ISSUE TITLE
[php7] function named "empty" triggers syntax error on HHVM

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#6355]
triggered by thx.StringOrderedMap in this case, when running on hhvm:
Fatal error: syntax error, unexpected T_EMPTY in `.../lib/thx/StringOrderedMap.php on line 76`

**Comment by RealyUniqueName** [comment]
Looks like it's the bug in HHVM you mentioned on slack: https://github.com/facebook/hhvm/issues/7354
I'll look into it later.

**Comment by RealyUniqueName** [comment]
I found that HHVM is not fully compatible neither with old genphp nor with new genphp7 :)
It has several issues, and this one is not the worst )

**Comment by RealyUniqueName** [comment]
I don't think we need to stick to HHVM. Since PHP7 (and planned PHP8) improvements it's becoming less and less important in php world.
