### ISSUE TITLE
Slow asset embedding with large swf in -swf-lib

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFoundation/haxe#6356]
The more large the swf file is when used with the flag -swf-lib, the longer it takes to embed it.
About half of the time is spent in the compiler. Can anything be done Haxe-side?

The issue is described in more detail here (Haxe 3.4.2):
https://github.com/openfl/openfl/issues/1594

**Comment by Simn** [comment]
I doubt we can do anything here. The problem is likely that `-swf-lib` does a bit more than just concatenate two swf files together. I'd look for swf-specific tools to handle large resource files like that.
