### ISSUE TITLE
XML iteration issue with modify-while-iterate

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6359]
Our haxe.org manual generator has this piece of code:

```haxe
var h = Xml.parse('<${xml.nodeName}><a href="#$bookmarkID"></a></${xml.nodeName}>').firstElement();
for (child in xml) {
	h.firstElement().addChild(child);
}
```

And this is the implementation of Xml.addChild:

```haxe
public function addChild( x : Xml ) : Void {
	ensureElementType();
	if (x.parent != null) {
		x.parent.removeChild(x);
	}
	children.push(x);
	x.parent = this;
}
```

As you can see, it removes an element from its parent given that is has one. That means that using `addChild` while iterating children modifies the children array it is iterating.

**Comment by back2dos** [comment]
As strange as it may sound, this is pretty much *expected* when dealing with DOM-like APIs: https://try.haxe.org/#58135

You get very similar although slightly more broken behavior for display lists: https://try.haxe.org/#5eA08

More importantly, if you change this, you risk breaking other XML mutation stunts, hidden in the darkest of corners where only programmers with *very* long beards will venture. 

The answer here is to (encapsulate all that beauty in a function and) use a while loop to implement it:

```haxe
function moveChildren(src:Xml, dest:Xml) 
  while (true)
    switch src.firstChild() {
      case null: break;
      case v: dest.appendChild(v);
    }
```

(well, the real answer is not to use the std lib's `Xml` like that, or - better yet - not at all)

**Comment by Simn** [comment]
I thought this behavior came from our optimization to a while loop, but looking further it indeed behaves like that even for a native `for (let c of _g11)`. So I suppose there's nothing broken here and the problem lies with the generator code.
