### ISSUE TITLE
Haxe 3.4.2 Neko 2.1 Mysql Invalid call

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#6365]
Simple:

```
Mysql.connect({
	user: user,
	pass: password,
	host: host,
	port: port,
	database: database
})
```

Errorline: https://github.com/HaxeFoundation/haxe/blob/development/std/neko/_std/sys/db/Mysql.hx#L203

Exception : Neko_error(Invalid call)

How to fix it?

**Comment by Simn** [comment]
This is not a valid Haxe issue, please refer to one of the community channels listed here: http://haxe.org/foundation/contact.html
