### ISSUE TITLE
the new std lib install location on unix systems is wrong

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#6367]
By convention standard libraries tend to live in `lib` folders on unix systems, this change violates the principle of least surprise, breaks setups that use local haxe installations, and is entirely unnecessary. 
Please revert the relevant parts of this commit https://github.com/HaxeFoundation/haxe/commit/a9ca4be338db28cb675e074c2f642f3b8becbcfb

**Comment by ousado** [comment]
Quoting from the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-opersys.html)
> The FHS requirement that architecture-independent application-specific static files be located in /usr/share is relaxed to a suggestion. In particular, a subdirectory of /usr/lib may be used by a package (or a collection of packages) to hold a mixture of architecture-independent and architecture-dependent files. However, when a directory is entirely composed of architecture-independent files, it should be located in /usr/share

That's exactly our case. But if this change is still deemed necessary - @andyli mentioned automated review tools that reject the current structure (I'd be interested which tools/distributions do that), I'll close the issue.

**Comment by ousado** [comment]
actually, closing this

**Comment by andyli** [comment]
Maybe my changelog entry may suggested that this is a new change, but in fact for Debian, Fedora, and openSUSE, the Haxe package std lib location is already in `/usr/share`. My recent commit is an update to the Makefile such that it matches with what is done in the Linux distros. The Linux packages were reviewed automatically and manually to make sure the installation is sensible, particularly it should not violate The  Filesystem Hierarchy Standard (FHS), which the latest version can be found at http://refspecs.linuxfoundation.org/FHS_2.3/fhs-2.3.html

For record, the Debian Python std library is indeed installed in `/usr/lib` (`dpkg-query -L libpython2.7-stdlib`), but do notice there contains native shared objects in `/usr/lib/python2.7/lib-dynload/`. Similarly, for PHP, its std lib is in `/usr/lib`, but they are again native shared objects (e.g. `/usr/lib/php/20151012/sysvsem.so`). The Haxe std lib is different that it doesn't contain any native binaries, so storing it in `/usr/share` makes sense which is not the case for Python and PHP.

I'm not sure if it is acceptable to place the Haxe std lib in `/usr/lib`, but `/usr/share` is the accepted location at the moment.

I realize that it could breaks users who uses the Makefile, or having custom setup in someway, so the change of Makefile default is done now, for Haxe 4.*, but not earlier.

Let me know if there is any other concern. I'm open to discuss this.

**Comment by ousado** [comment]
@andyli Thanks for the thorough answer, if this already is the package structure for the various linux distribution packages I agree it makes sense to adjust it at the source for coherence. And looking at the debian policy manual, when followed to the letter, the std directory indeed should be in `shared`.
