### ISSUE TITLE
String interpolation expressions breaks if closing brace is followed by single quote

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6369]
[Minimal example](https://try.haxe.org/#3E53c) shows that `'${{} + 'whoops'}'` the single quote preceding whoops terminates the string. Reversal of both operands parses correctly.

**Comment by Simn** [comment]
I think that means we have to count braces in `code_string`.

**Comment by Simn** [comment]
I have fixed this in hxparser because that's easier to debug: https://github.com/vshaxe/hxparser/commit/d83916a7ba3ce9c32c43ad0c73c0fcf9bbcc7d17

I think we have to apply the same fix to the Haxe lexer, but I'll have to think about corner cases with escapes or something like that.

**Comment by Simn** [comment]
@ncannasse: Does my fix look right to you?

**Comment by ncannasse** [comment]
Seems good

**Comment by Simn** [comment]
Note that the original example still won't parse because `{} + 'whoops'` is not a valid expression. Took me a while to figure this out, but we don't allow binops after `}`.
