### ISSUE TITLE
Problem with eval, abstract and untyped PHP

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#6374]
I have an abstract which used to work with the old PHP generator before eval.
It looks like this:
```haxe
@:coreType abstract NativeArray<T> {
  public inline function new()
    this = (untyped __call__)("array");
}
```
Actually it's more complicated with another abstract over this one that has a `@:from macro` function and so on (can't really remember why I built something crazy like this...)
Anyway, this gives me a compile error now: `Uncaught exception Unbound variable` for the `this=...` line above. Any quick idea why and does this have to do with eval?

Also something like this:
```haxe
@:phpGlobal
private extern class Arr {
  @:native("\\array")
  static function create<T>():NativeArray<T>;
}
```
which used to work (old PHP gen), gives me an error now:
`Field index for \array not found on prototype Arr`
Any idea what that means?

**Comment by Simn** [comment]
I mention this at the bottom in the eval article: http://haxe.org/blog/eval/

You have target-specific code which ends up being "compiled" in the macro interpreter context. The old interpreter used to silently ignore that, whereas eval fails during its JIT stage.

The solution is to add some conditional compilation.

**Comment by mockey** [comment]
So the error comes from the `@:from macro` function actually?

**Comment by Simn** [comment]
Well if you have any macro function in a module, the compiler types the entire module in macro context. That's likely the issue here.

**Comment by mockey** [comment]
I see. But where do I put my `#if php` then? Should I do `this = #if php (untyped __call__)("array") #else null #end;`?

**Comment by mockey** [comment]
OK, I made it compile, by simply adding `#if php ... #else null #end` everywhere. Is there a better way maybe?

**Comment by Simn** [comment]
I don't think so. It's the same problem we always had if you accessed `php.Something` in a module that has macros.

**Comment by mockey** [comment]
OK, I can live with that, thanks for the quick answer.
