### ISSUE TITLE
Setting a field from a closure within a setter generates setter call instead of writing the field

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6375]
Subj. But not for statics:

```haxe
class Main {
	var memberField(default,set):Int;
	static var staticField(default,set):Int;

	static var rollbacks:Array<Void->Void>;

	function set_memberField(v) {
		memberField = v;
		rollbacks.push(() -> memberField = 42);
		return v;
	}

	static function set_staticField(v) {
		staticField = v;
		rollbacks.push(() -> staticField = 42);
		return v;
	}
}
```

```js
var Main = function() { };
Main.set_staticField = function(v) {
	Main.staticField = v;
	Main.rollbacks.push(function() {
		return Main.staticField = 42;
	});
	return v;
};
Main.prototype = {
	set_memberField: function(v) {
		var _gthis = this;
		this.memberField = v;
		Main.rollbacks.push(function() {
			return _gthis.set_memberField(42);
		});
		return v;
	}
};
```

I expected it to generate a field write in both cases, because that would be the most useful, so I guess it's a bug?

**Comment by Simn** [comment]
Agreed

**Comment by nadako** [comment]
Looks like this has something to do with the `_gthis` tempvaring, that makes `match e.eexpr with TConst TThis -> true` check at https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typer.ml#L1056 fail.

**Comment by ncannasse** [comment]
I think that for transitioning code from Haxe 3 to Haxe 4 it would be nice to have warnings about the behavior change here (if the user compiles with -D haxe3-warning or something) because these cases are quite hard to find in code.

**Comment by nadako** [comment]
Note that if we look at the code, affected by 833e3a2c370d2d0fabd8d65a671bf36d575c6d1b, we can see that the previous behaviour was merely a bug, not an intended behaviour. But yeah, maybe some help with finding these cases would be nice.

**Comment by ncannasse** [comment]
Well, I would not qualify it as a bug, the status of either calling the setter or setting directly the field when you're into a set function depends if you take into account the fact that you're in a lambda or not. It is a little ambiguous.

Just found I have about 142 of them in the whole Evoland 2 code, that introduces random bugs

**Comment by ncannasse** [comment]
@Simn what's your opinion ? It is ambiguous, and given it introduces silent hard to spot bugs when moving from haxe 3 to haxe 4 I'm not sure if we should have it or not... -- I have code for the warning btw don't bother with it

**Comment by Simn** [comment]
I consider the previous behavior to be a bug. If you call the closure from within your setter you'd get infinite recursion, which comes as a surprise because setter assignments usually deal with this kind of stuff.

**Comment by ncannasse** [comment]
Well, in our case we have a lot of this:

```haxe
function set_state(v) {
    state = v;
    switch( state ) { 
    case Hurt:   wait(0.5, function() state = Default);
    case Attack : wait(1, function() state = Attacking);
    ...
    }
}
```

So it makes it no longer possible to use setter for such a state machine triggering behavior changes with some delay.

**Comment by ncannasse** [comment]
And I don't think there's much case where you would declare lambda to call them immediately, no ?

**Comment by ncannasse** [comment]
Maybe we should entirely forbid it, that would at least make clean errors on Haxe 3 to 4 transition

**Comment by nadako** [comment]
> Well, I would not qualify it as a bug, the status of either calling the setter or setting directly the field when you're into a set function depends if you take into account the fact that you're in a lambda or not. It is a little ambiguous.

But it is, look at the change - there were specific checks to generate field assignment instead of setter call and it worked like that for closures inside static setters and it wasn't working for instance fields _only_ because `this` was tempvarized.

**Comment by Simn** [comment]
Don't see much of a reason to forbid it. It might be useful in some cases, and the current behavior looks fine to me.

I don't mind adding some warning behind a flag though. Although I won't be surprised if you're the only one relying on this behavior...

**Comment by nadako** [comment]
Please, don't forbid it. I have a specific use case for it, as illustrated in the original post: adding "rollback" closures when setting the value.

**Comment by ncannasse** [comment]
It is ambiguous, the fact that moving some lambda code inside or outside the setter changes the behavior IS problematic.

**Comment by ncannasse** [comment]
inside the setter : it sets the field, outside : it calls the setter. That is very error prone if you have some code you want to refactor in some way

**Comment by nadako** [comment]
But that can be said for any code inside a setter, how lambda is different?

**Comment by Simn** [comment]
I can't follow the argument, the same could be said about moving the assignment inside or outside the setter. I consider it accepted facts that if you're in the setter of field x and assign to field x, it does not call the setter.

**Comment by nadako** [comment]
The current behaviour is only logical, according to haxe spec: any *code* inside a setter function that assigns to the field bypasses the setter.
