### ISSUE TITLE
[lua] haxe breaks the string metatable if you use more than one haxe-compiled module.

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#6377]
if you have more than one haxe-compiled module and run them on the same lua context, the string library is completely broken if you call functions in the form `(""):foo()` (this is extremely common in lua libs, so it breaks nearly all of them)

ran into this when trying to use love2d, with both `conf.lua` and `main.lua` compiled by haxe.

please don't patch global stuff like this. 😢

#6347 looks like it'd address this.

test case (works with love, but requiring both output files into the lua repl should crash too)

```haxe
// Foo.hx
class Foo {
	static function main() {
		trace("words");
	}
}
```

```haxe
// Bar.hx
@:luaRequire("argh")
extern class Argh {
	static function run(str: String): Void;
}

class Bar {
	static function main() {
		Argh.run("hi");
	}
}
```

```lua
-- argh.lua
return {
	run = function(s)
		local foo = "argh "
		print(foo:rep(5))
	end
}
```

`haxe -main Foo -lua conf.lua --next -main Bar -lua main.lua -cmd "love .`

**Comment by jdonaldson** [comment]
I agree, I don't want to alter the string prototype here.  That other branch is a fairly sophisticated effort to avoid that. However, that branch has significant drawbacks as well.  If a string instance is not explicitly typed (common in type inference contexts for function arguments), the compiler is not able to handle it correctly.  I think this can happen a lot, it cropped up a few times in our unit tests.

Let me see how far I can get by just patching the existing logic.  String is such a special case, and string behavior is likely to change in Haxe 4 anyways (moving to unicode).
