### ISSUE TITLE
try.haxe.org is not compiling

### ISSUE THREAD

**Issue by 7h3w4rd0c70r** [HaxeFoundation/haxe#6378]
Hi, I just wanted to test some haxe code, but it seems like try.haxe.org is not working. There is my screenshot with error in console:
![screen shot 2017-06-19 at 14 25 18](https://user-images.githubusercontent.com/14906262/27284997-52e8f216-54fb-11e7-9e68-8102484b5295.png)

**Comment by markknol** [comment]
I reported it here https://github.com/clemos/try-haxe/issues/135

**Comment by clemos** [comment]
FYI it's back online, sorry for the inconvenience ;)
