### ISSUE TITLE
[php7] Lib.getClasses() not implemented

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe#6384]
Today I tried to compile a basic website with haxe 3.4 & php7 ( this one :  https://github.com/bablukid/sugoi-demo )

It happens that the supercool dbadmin lib cannot compile because php7.Lib.getClasses() is not implemented.
Is there any reason for this ? Will it be implemented one day ?

BTW a big thank you for the new php7 target :-)

**Comment by Simn** [comment]
IMO the new target doesn't have to support all the old Lib static functions. These are often quite specific to a target (generator). Maybe the functionality can be achieved otherwise?

**Comment by RealyUniqueName** [comment]
Php7 uses lazy class loading, so specified method is impossible to implement.
I suggest to build a list of classes for dbadmin with a macro.

**Comment by RealyUniqueName** [comment]
Oh, some methods left in php7.Lib with `throw "Not implemented"` i'll try to implement some of them. Maybe i'll find a solution for `getClasses()` after all.

**Comment by RealyUniqueName** [comment]
I've added missing implementation.
`Lib.getClasses()` tries to find and load all generated php files and then returns a structure representing loaded types.

**Comment by masood1349** [comment]
App iran
