### ISSUE TITLE
VSCode command start

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6392]
A typical Haxe/VSCode task looks like this:

```
{
    "version": "2.0.0",
    "command": "haxe",
    "args": ["--connect","6000","myproject.hxml","-cmd","start myproject.hl"],                
    "showOutput": "never",
    "problemMatcher": "$haxe"
}
```

(it can be myproject.hl or myproject.exe or different output)

Using `start` is mandatory in order to have the task immediately return when starting an interactive application (not commandline). However it's windows only.

I propose we add for this `-cmd-detach` that does spawn a new process in detached mode, and while we're at it we could add a few macro so for instance you can do the following:

```
{
    "version": "2.0.0",
    "command": "haxe",
    "args": ["--connect","6000","myproject.hxml","-cmd-detach","${Output}"],                
    "showOutput": "never",
    "problemMatcher": "$haxe"
}
```

**Comment by ibilon** [comment]
> and while we're at it we could add a few macro so for instance you can do the following

Another format should be used, that's the bash variable substitution syntax, so writing it on linux (since it can be used manually too) would require escaping.

**Comment by ncannasse** [comment]
Actually it seem "start" only exit and returns on Windows 7. On Windows 10 it does keep the task from finishing. This make this issue a bit more urgent.
