### ISSUE TITLE
Type parameter overhaul

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/haxe#6397]
I'm thinking about making a big change on how we deal with type parameters on C# and Java for Haxe 4.0 . We are currently riddled with issues like #3398 , #3399, #3703 - among others. They all come from a common issue - java and c# perform some type changes when a type is used as a type parameter.

Some of these changes are not optional - for example, in Java we need to change `Int` to be `java.lang.Integer`, which is the boxed counterpart of the basic `int` type. This is needed because e.g. `Array<int>` is not valid on Java.
This change however has some inherent problems. In the Haxe's typer's eyes, we are accessing an `Int`, but as far as Java is concerned, we are accessing an Integer. For example, if we try to access Array's underlying native array, it's typed as `java.NativeArray<Int>` - which is `int[]`, while Java's vm sees it as `Integer[]`.

Similarly, we can run on multiple issues with C# when dealing with Haxe created types vs native types and type parameters, since they are changed differently according to if the type was declared as nativeGen or hxGen.

I don't think there is a definite solution for Java. Since it mostly happens with Java's NativeArray, we could perhaps do what Atry has suggested here https://github.com/HaxeFoundation/haxe/issues/3398#issuecomment-56786441 . I think this is a nice solution, although it hurts `Vector<>` performance - making it box the basic types while it wasn't boxing in the past. So it then becomes a question of what we want to prioritize on Vector.

For C#, I think the solution will be to not change the type parameters at all. We currently change type parameters of any reference type on Haxe-generated class to be `object`. We do that both to avoid triggering the cast-by-copy semantics of types like Array, but also that there was no real benefit other than added strictness (which makes C# generated code more strict and less likely to run) - as the performance was the same. We will solve the cast-by-copy on #4872, and thus making an error if someone casted an Array twice (e.g. to overcome variance limitations) - which I think is a fair error state. We still also need to understand the impact of eliminating cast-by-copy completely on other classes other than Array - since I don't think #4872's solution can be generalized to any generic class.
Also doing this will probably make changing variance in Haxe pretty much impossible, and the C# target will suffer even more for any new feature that involves type parameters.

I'd love to hear your thoughts about this

**Comment by Simn** [comment]
I read your post but am not quite sure what you actually want to change. Could you make some short bullet points?

**Comment by nadako** [comment]
Generating fair type params on C# would be nice for interop, but other than that I don't care much about it if the performance is the same :) I'd love to know though what's our general position wrt type params and variance in Haxe? E.g. are we interested in explicit co/contra-variance settings (like in c#, scala, etc)?

**Comment by hughsando** [comment]
C++ solves the Array<typeParam> issue by having a "virtual array", which uses an extra level of indirection for the generic access  so the access falls through to a "real array" underneath.  When strongly casting, you can return the real array.  This avoid boxing and  ensure the generic and real parts share the same data.
Being able to pass any array to `Array<Dynamic>` is a huge hole in the type system, so you can use the virtual array there too.
I ended up retying things with the cppast to work out some of this stuff.

**Comment by Simn** [comment]
This is not going to happen for Java or C#.
