### ISSUE TITLE
[java] Failing tests

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6398]
So we don't forget:

https://github.com/HaxeFoundation/haxe/commit/6a25dffd198a100fe686d5a2bc4f37d4984f4e65
https://github.com/HaxeFoundation/haxe/commit/cda973f5c332276d04c7619f7a6969fdd6b71c59

**Comment by Simn** [comment]
Another one for Java: https://github.com/HaxeFoundation/haxe/commit/e17e87354295507ba919cb67167c695d85f18c6b

**Comment by waneck** [comment]
Are you writing new tests?

**Comment by Simn** [comment]
No, that's fallout from your recent changes.

**Comment by waneck** [comment]
That's strange - the tests weren't failing when I pushed them

**Comment by Simn** [comment]
Yes they were.

**Comment by RealyUniqueName** [comment]
All mentioned tests are currently enabled
