### ISSUE TITLE
Diagnostics false report

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6405]
```haxe
import haxe.macro.Expr;
import haxe.macro.Context;
using haxe.macro.ExprTools;

class Macros {

	public static macro function makeTypeDef( e : Expr ) {
		var t = Context.getType(e.toString());
		trace(t);
		return macro {};
	}

}
``` 

Diagnostics complain about `Unused import/using using haxe.macro.ExprTools`

(btw we should have two different messages, unused import and unused using)

**Comment by ncannasse** [comment]
Adding the following also breaks:

```haxe
	#if macro

	static function buildTypeDef( t : haxe.macro.Type ) : Expr {
		Context.error("Unsupported type "+Std.string(t),Context.currentPos());
		return null;
	}

	#end
```

Context has no field error + currentPos.

These errors also gets mixed with actual compilation errors, getting quite hard to understand (even for me) what errors are coming from diagnostics and which are coming from actual "real" errors.

I propose that until all of these are fixed we should disable diagnostics by default in VSHaxe, as this provide a very poor user experience.

**Comment by Gama11** [comment]
That one is from https://github.com/HaxeFoundation/haxe/issues/6000.

>I propose that until all of these are fixed we should disable diagnostics by default in VSHaxe

I strongly disagree, I couldn't work without diagnostics anymore.

**Comment by ncannasse** [comment]
If there are false reports all over the place, then I think it's only viable if you understand how to deal with these, which only works if you have good knowledge of the intrinsic of the system. Who would want to work with a compiler that keep reporting false positive errors ?

**Comment by Gama11** [comment]
In my experience, the false positives practically only appear in macros, which most Haxe users don't use that much. Everywhere else, diagnostics are extremely helpful.

**Comment by ncannasse** [comment]
Well my experience is very early for now but clearly this prevent for correctly working when doing macro code, maybe we should have some kind of workaround for now, such as ignoring all diagnostics if you have a macro function in the class, or something that allows me to turn diagnostic on again and keep reporting errors :)

**Comment by Gama11** [comment]
I thought about doing a hack along the lines of https://github.com/jeremyfa/haxe-languageserver/commit/8de6b832dd227d0e75dc167c99ad8b82702ea343, but quickly realized that that only creates more confusion (because diagnostics / errors that _follow_ from the "has no field" ones are then the only ones, and it's not clear where they're coming from).

**Comment by Simn** [comment]
The problem with `#if macro` is this beauty that you put in the parser years ago:

```
if is_true (eval ctx e) || (match fst e with EConst (Ident "macro") when Path.unique_full_path p.pfile = (!resume_display).pfile -> true | _ -> false)
```

It's always true in the current display file.

**Comment by ncannasse** [comment]
=If I remember correctly, is was necessary to allow completion to correctly work within the macro, but I don't remind exactly why it was.

**Comment by Simn** [comment]
Yes I get the intent. The problem is that this leads to the display file being parsed in macro-mode, while everything else is being parsed in non-macro mode. So it's no big surprise you're getting these errors.
