### ISSUE TITLE
[lua] No way to prevent code generator from generating ":" as accessor for function calls.

### ISSUE THREAD

**Issue by martinluetke** [HaxeFoundation/haxe#6411]
Given some **external** lua object that was created like this:

```lua
local obj = {}
local value = "foo"
function obj.printValue() -- note that "." is used and not ":"
   print(value)
end 

```
and a external class declaration

```haxe
extern class SomeObject {
  public function printValue(): Void;
}
```

then there is no way to prevent the code generator from turning haxe code like this

```haxe
myobject.printValue();
```
into output like this.
```lua
myobject:printValue()
```
instead of the required
```lua
myobject.printValue()
````
My idea would be that somthing like @:structAccess (cpp only) would exist for the lua generator.
So that I could write

```haxe
extern class SomeObject {
  @:structAccess
  public function printValue(): Void;
}
```

**Comment by jdonaldson** [comment]
Try something like this:

```haxe
@:native("obj")
external class SomeObject {
  public static function printValue(): Void;
}
```
Since that method is not accessing a leading "self" argument, it might as well be a static method anyways.  You can reference the table itself as the argument for "@:native", and Haxe will generate proper dot-access methods there.  Anything with a self argument can become an instance method.

**Comment by martinluetke** [comment]
Indeed. I already use this method for global objects. 
My problem is, that the "obj" I described is actually a dynamic object, similar to a class instance. It is created deep within an external api, f.i. in response to an event. Like this:
```
ExternalAPI.onObjectCreated(function(newObj:SomeObject) {
    newObj.printValue();
}
```
Lua, as a multi-paradigm language, gives its api designers different ways to model object-oriented behaviour, with its implicit "self" syntactic sugar accessor ":" being one option. That HAXE chooses this method to model its own classes onto lua is a sound and straight forward approach, but for an external api this is also completly ok:

```
MyFactory = {} -- global object with static methods

function MyFactory.createObject(initialName)
   local obj = {}  -- dynamic object with private state hidden in clojure 
   local _name = initialName

   function obj.getName()
     return _name
   end

  function obj.setName(newName)
    _name = newName
  end

  return obj
end
```

Another thing to consider is that lua is often used as a scripting layer on top of an c/c++ engine, wich is the case in my situation (I am working on a Factorio mod). Here the object's fields, both members and methods, map directly on c/c++ code.

I am atm considering workarounds, all of wich are labourious and/or inefficient, like wrapping the external lua objects in a haxe proxy class, and use `untyped __lua__("self.externalObj.printValue()")`.

That is slightly irritating, considering that the problems stems from a single choice of character during the code generation ;).

**Comment by Simn** [comment]
@jdonaldson: Is this the same problem I was having a while ago? I don't remember what exactly it was...

**Comment by jdonaldson** [comment]
@Simn yeah, I recall that conversation.  My issues are fairly minimal at the moment (*code* issues), so let's take a stab at it.  I opened a pull request.

**Comment by jdonaldson** [comment]
@martinluetke thanks for the overview, this casts more light on the issue.

**Comment by jdonaldson** [comment]
This is now handled through the new @:luaDotMethod metadata.
