### ISSUE TITLE
Pattern Matching + GADT bug

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#6413]
The following code executes the wrong branch, it's interesting that the other branch is not even generated to js.
```haxe
enum N {
	N1;
}

class PR {}
class VR {}

enum C<X> {
	P:C<PR>;
	V:C<VR>;
}

class Main {

	static function main () {
		add(N1, P);
	}

	public static function add <X>(n:N, c:C<X>) {
		switch [n, c] {
			case [N1, P]:
				trace("correct");
			case [N1, _]:
				trace(Std.string(n));
				trace(Std.string(c));
				trace("false");

		}
	}
}
```

generated js for `add`:

```js
Main.add = function(n,c) {
	switch(c[1]) {
	default:
		console.log(Std.string(n));
		console.log(Std.string(c));
		console.log("false");
	}
};
```

**Comment by frabbit** [comment]
it works as expected if you change the signature of add to
`public static function add (n:N, c:C<Any>)` for example

**Comment by frabbit** [comment]
removing `n` from pattern matching leads to the execution of the correct branch.

**Comment by frabbit** [comment]
when `P` and `V` have the same type, `C<PR>` for example, it also works correctly.

**Comment by Simn** [comment]
@frabbit: Did your fix for this work?
