### ISSUE TITLE
[display] @position on escaped var in macro function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6417]
```haxe
class Main {
	static function main() {}

	macro function foo(body:Expr) {
		macro function() $body;
	}
}
```

No result when requesting the `@position` of `$body`:

```
> haxe --display Main.hx@100@position
<list>
</list>
```

When you hover over it, the range of the entire function is used:

![](http://i.imgur.com/opj0fkz.png)

**Comment by Gama11** [comment]
`@position` is now fixed, but on hover I get `Dynamic` instead of `Expr`...

![](http://i.imgur.com/9EWlJu7.png)

**Comment by Gama11** [comment]
Hm, actually, hovering hover `expr`'s declaration it also shows `Dynamic`..

![](http://i.imgur.com/gacY2wO.png)

**Comment by Simn** [comment]
That's a separate issue (probably) related to macro context state. Any `Expr` argument is actually `Dynamic` from the outside, i.e. the non-macro context. This is probably related to #6405 in some way.

**Comment by Gama11** [comment]
Actually, I think I'm just dumb.. `Expr` isn't even imported.. If it is, it works.

Still, kind of confusing that it shows up as `Dynamic` when unimported?

**Comment by kLabz** [comment]
It's `Dynamic` because `load_complex_type` fails there: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typeload.ml#L644-L648

See #11760
