### ISSUE TITLE
not generate redundant final return for `return voidExpr`

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6420]
```haxe
class Main {
	static function f(fn:Void->Void) fn();

	static function voidFunc() trace("hi");

	static function main() {
		f(function() return voidFunc());
		f(() -> voidFunc());
	}
}
```

This generates:
```js
Main.main = function() {
	Main.f(function() {
		Main.voidFunc();
		return;
	});
	Main.f(function() {
		Main.voidFunc();
		return;
	});
};
```

That happens because we rewrite `return voidExpr` to `{voidExpr; return;}`. However if that's a final expression there's no need to generate the final return.

While this is a minor issue that was pretty rare in real-world code, it occurs more often now with arrow functions that just call some void function (like in the example above), so we might want to get rid of that final `return` for the sake of nicer code generation.

I'm not sure if it's possible to check at the point when we rewrite `return voidExpr`, maybe it should be done in the analyzer CFG builder or some cleanup module...

**Comment by Simn** [comment]
The question here is if we only want to avoid that `return` in the `return void` case or if we always want to remove redundant returns, even if written by users.

**Comment by nadako** [comment]
> want to remove redundant returns

fwiw we remove some of them already due to CFG building and unreachable blocks

**Comment by Simn** [comment]
> fwiw we remove some of them already due to CFG building and unreachable blocks

That's not specific to `return` though, it just prunes dead code (which is actually necessary for some targets).
