### ISSUE TITLE
[lua] Unused `__lua_lib_lrexlib_Rex = _G.require("rex_pcre")` in output leads to "module rex_pcre not found" error

### ISSUE THREAD

**Issue by martinluetke** [HaxeFoundation/haxe#6425]
Haxe Compiler 4.0.0 (git build development @ 085f38e6d)

I found this unsused line in my main.lua:
```lua
__lua_lib_lrexlib_Rex = _G.require("rex_pcre")
```
It breaks my script as I dont have that requirement around.
`__lua_lib_lrexlib_Rex` is apparently not used anywhere within my result lua script and removing that line fixed my problem. My actual workaround is to add an empty "rex_pcre.lua" file next to my script.

I dont know what that module does (please excuse my ignorance), but if it references `libpcre-1.dll` in my haxe installation folder, I can not have it! Factorio does not allow anything but plain lua imports.

**Comment by jdonaldson** [comment]
I might need @Simn 's help on this.  It looks like a dce issue.  (the require for rex_pcre will get generated even with a simple "hello world" application).

I poked around on dce.ml for a bit, but didn't find anything obvious.

**Comment by Simn** [comment]
DCE doesn't remove extern classes, so your `@:luaRequire("rex_pcre")` on the Rex class always makes it to the generator. Maybe put it on EReg instead?

**Comment by nadako** [comment]
Hmm. If `@:directlyUsed` is added even though the type doesn't appear in the output, then there's surely something wrong with the DCE. Maybe it's some processing order issue, e.g. it first marks `Rex` as directly-used when it encounters that `static var FLAGS : Table<String,Int> = Rex.flags();` and then it removes the `FLAGS`. I can try looking into that when I get a minute.

**Comment by jdonaldson** [comment]
Good catch.  I could've dropped the reference in this case, but I imagine this can happen when folks try to do custom inline constructors/builders for their externs.
