### ISSUE TITLE
[display] no completion in <platform>.hx files

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6435]
With an empty `Main` named `Main.js.hx`, and `-js` specified, no display modes seem to work:

```haxe
class Main {
	static function main() {}
}
```

```
> haxe -js main.js --display Main.js.hx@0@diagnostics
Error: Display file was not found in class path
```

Original issue: https://github.com/vshaxe/vshaxe/issues/147

**Comment by Yanrishatum** [comment]
Regression: Completion no longer provided at least since 4.0.0. Tested on Haxe 4.0.0, 4.0.3 and 4.0.5. (Windows x64)
Output on reproduction sample:
```json
[{"file":null,"diagnostics":[{"kind":2,"severity":1,"range":null,"args":"File \"_build/src/compiler/displayOutput.ml\", line 338, characters 6-12: Assertion failed"}]}]
```
@Simn
