### ISSUE TITLE
Sys.systemName returns "Linux" on Android

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/haxe#6437]
I built an Android Lime app, which uses the `cpp` target internally. When I build it against `android` and evaluate `Sys.systemName()`, it tells me `Linux`.

Context: I'm trying to report the OS and platform of my users. Because the `cpp` target is used, I can't easily distinguish between Android (`Linux` system name and `cpp` target) and Linux Desktop (`Linux` system name and `cpp` target).

Also, if there's some alternative way to detect that I'm on Adroid, I would appreciate hearing about it.

**Comment by RealyUniqueName** [comment]
AFAIK lime adds some defines. 
Try this:
```haxe
var os = #if android 'android' #elseif ios 'ios' #else Sys.sytemName() #end;
reportOs(os);
```

**Comment by ashes999** [comment]
@RealyUniqueName I just discovered the same thing myself, and it works great.  It was be nice if these were documented somewhere ... (I googled. A lot. And couldn't find an exhaustive list.)

Cheers.

**Comment by RealyUniqueName** [comment]
This is a lime feature. And since Sys.systemName() works as documented, i think this issue can be closed now.
