### ISSUE TITLE
Constant folding not working in same cases for JS target

### ISSUE THREAD

**Issue by gene-pavlovsky** [HaxeFoundation/haxe#6438]
Consider the following sample code:
```
package;

class Main
{
	static inline var ONE = 1;
	static inline var TWO = 2;
	static inline var DEFAULTS = ONE | TWO;

	static inline var ONE_U:UInt = 1;
	static inline var TWO_U:UInt = 2;
	static inline var DEFAULTS_U = ONE_U | TWO_U;


	static function main()
	{
	}

	// Compiles to JS and AS3 targets.
	static function generate(flags:UInt = DEFAULTS):Void
	{
	}

	// Compiles to AS3, but gives an error on JS.
	//static function generateU(flags:UInt = DEFAULTS_U):Void
	//{
	//}
}
```

The reason for it not working on JS is obvious here:
```
// Generated by Haxe 3.4.2 (git build master @ 890f8c7)
(function () { "use strict";
var Main = function() { };
Main.main = function() {
};
Main.generate = function(flags) {
	if(flags == null) {
		flags = 3;
	}
};
Main.ONE = 1;
Main.TWO = 2;
Main.DEFAULTS = 3;
Main.ONE_U = 1;
Main.TWO_U = 2;
Main.DEFAULTS_U = 1 | 2;
Main.main();
})();
```

Why `1 | 2` is not folded to `3`?

With AS3 target, it compiles, but is also a bit weird
```
// Compile __main__.as instead
package  {
	public class Main {
		static protected var ONE : int = 1;
		static protected var TWO : int = 2;
		static protected var DEFAULTS : int = 3;
		static protected var ONE_U : uint = 1;
		static protected var TWO_U : uint = 2;
		static protected var DEFAULTS_U : uint;
		static public function main() : void {
		}
		
		static protected function generate(flags : uint = 3) : void {
		}
		
		static protected function generateU(flags : uint = 3) : void {
		}
		
		static static_init function init() : void{
			Main.DEFAULTS_U = uint(3);
		}
	}
}
namespace static_init;
Main.static_init::init();
```

Both functions have `3` as default value for `flags`, however the value is assigned to `DEFAULTS_U` at a different time than to `DEFAULTS`.

I expected code folding optimization in both cases here, on both targets, and, as a consequence of that, being able to use either of `DEFAULTS` and `DEFAULTS_U` as default values for function arguments.

As a more general complaint, it's really inconvenient (with regards to auto-generated docs / IDE code completion) that a function can't have a default argument that can be calculated at compile-time, e.g. `function generate(flags:UInt = ONE | TWO)`. Hopefully you will consider improving this situation.

**Comment by back2dos** [comment]
It would seem like the issue is caused by `UInt` vs `Int`.

**Comment by gene-pavlovsky** [comment]
Seems like. Question is "why"

**Comment by Simn** [comment]
UInt is pretty complicated. In order to optimize it correctly, we would have to implement the entire semantics in the compiler. This is not worth the complexity.

**Comment by gene-pavlovsky** [comment]
So, workaround is explicitly specifying Int, right?

**Comment by Simn** [comment]
Int is the default, so you don't have to specify any type. But yes, always use Int unless you actually need UInt semantics.

**Comment by gene-pavlovsky** [comment]
Ok, perhaps I should drop the habit of specifying explicit types for constants.
