### ISSUE TITLE
Inconsistent typing in setter

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#6439]
I ran into this issue when trying to detect casts from class to structural type instances.  I was seeing in some cases the AST would report that an instance would have Unknown<0> types for the params in the method body, but externally the method signature would have concrete types.  This was happening on setters.  E.g.:

```haxe
class Main {
    public var foo(default, set) : String;
    function set_foo(x){
        $type(x); // Unknown<0>
        this.foo = x.toUpperCase();
        $type(x); //  {+ toUpperCase : Void -> String }
        return this.foo;
    }
    public function new(){}
    static public function main(){
        var m = new Main();
        $type(m.set_foo); // x : String->String

    }
}


```

**Comment by nadako** [comment]
I think the `Unknown<0>` at the point where `$type` is called is to be expected, however when it gets to the generator, all monomorphs are supposed to be already resolved...

**Comment by jdonaldson** [comment]
Yeah, by itself the set_foo method type behavior makes sense.  However, when it's defined as the setter... seems like the argument/return types should have been resolved by the time you generate the method body.

If this isn't likely to get fixed, is there another way of determining that a given method has monomorph types in its arguments?

**Comment by nadako** [comment]
I don't think the compiler knows whether a function is used as a setter or not, it just happens that it's automatically called for properties because of its naming.

> Is there another way of determining that a given method has monomorph types in its arguments?

That sounds a bit like an XY problem, why'd you need that?

**Comment by jdonaldson** [comment]
I'm trying to avoid patching the prototype for string types in lua.  To do that, I have to inline everything.  If a string is passed as a Monomorph/structural type in a function argument (Unknown<0>, {length : Int} etc), I lose the special field handling inside the method body.

I was trying to work around this by detecting when strings are passed as monomorphs.  When I detect that a string is getting passed as a structural type, I can wrap it in a helper function to convert it to something appropriate for plain field access.  I have a branch I'm working on here : https://github.com/HaxeFoundation/haxe/tree/lua_clean_string 

Situations like this prevent that from working.  The generator at the callsite (m.set_foo in the above example) doesn't know that the function arguments for set_foo end up being treated as structural types, so it can't wrap the string argument, and plain field access on the string instance in the method body will fail.

**Comment by nadako** [comment]
But in this particular case there's no reason to wrap the string since it's known to be `String` inside the `set_foo` method. I'm pretty sure you can just trust argument type.

**Comment by jdonaldson** [comment]
Well, that's not really what I'm seeing though... the generator thinks ``x`` is a monomorph inside the ``set_foo`` method.  That's what the ``$type`` calls are showing above.  The generator doesn't have ``x`` listed as a string instance, but some kind of monomorph.  I added another method call to show what type the generator thinks it's dealing with at different points in the method.

The other thing I'm noticing now is that compiler completions for ``x`` get it right, it correctly shows it as a string type.  :/

**Comment by nadako** [comment]
> The generator thinks x is a monomorph inside the set_foo method

It's probably a bound monomoprh, so if you `follow` it, you'll get the actual type.

> That's what the $type calls are showing above. 

$type is handling when typing and it prints out the current state of the monomorph at the point it was encountered by the typer. In your example it's before the unification happens, so it shows "unknown". If you place another `$type` call right after `foo = x`, it'll report `String` since the monomorph will become bound.

**Comment by nadako** [comment]
Oh I see you edited the original example. This indeed binds the monomorph to a structure type (because of field access), but that won't work for a setter. It will now complain about type not being String.

**Comment by jdonaldson** [comment]
Whoops, yeah I need to return a known string type.  Updated once more.

I found a way to work around this issue... you can look for monomorphs  inside the instance type being invoked, rather than the etype defined by the TCall itself.

If I were being stubborn, I'd say that the arguments inside that setter should not be typed as monomorphs... ever.  However, this ends up being a very very minor nit.  I don't think it's worth anybody's time for now, so i'll close it out.
