### ISSUE TITLE
field initializers vs monomorphs

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6440]
Haxe requires class fields to either have a type hint or an initializer expression to infer the type from,
however it seems to allow unknown types for initializer expressions, e.g.

```haxe
class Main {
	static var a = null;
	static var b = [];

	static function main() {
		$type(a); // Unknown<0>
		$type(b); // Array<Unknown<0>>
	}
}
```

This looks quite inconsistent to me and I'm wondering if it's intended or we should provide additional check that field type doesn't contain monomorph types?

**Comment by ncannasse** [comment]
Does that solve any problem ? If not, I would not try to fix it :)

**Comment by Simn** [comment]
> Haxe requires class fields to either have a type hint or an initializer expression

That is only true for non-static fields.

**Comment by nadako** [comment]
> That is only true for non-static fields.

This makes me wonder about the reasoning for this decision. Why we check whether field type is known only partially and only for instance fields? To me this still looks like a weird inconsistency :-/

As for the practical issues, it's a bit annoying in macros because you can't be sure that type is safe to use for some cases, so you have to check if it contains monomorphs (which is also slower in macros than it would be in the compiler).

I assume this can also lead to confusing error messages at usage places because of wrong inferred types (e.g. anon structs vs classes), but since I don't write code like this, I'm not sure if it happens often. :)

**Comment by Simn** [comment]
I'm not sure about this. On the one hand I think field types should be fully known after typing their expression, but on the other hand not being able to have `static var a = [];` would be pretty annoying.

Let's err on the side of not being annoying.

**Comment by back2dos** [comment]
@nadako has a point about consistency though. Why is that [`var foo = null;` is fine and `var bar;` isn't](https://try.haxe.org/#F25dE)?

**Comment by Simn** [comment]
If you assign `null` you at least make an explicit choice to leave the type unknown. I don't think we should allow `var bar;` just to be consistent.

**Comment by back2dos** [comment]
Ok, how about disallowing `static var bar;`? As far as I can tell, that'd align the rules for static and instance vars. Sacrificing the possibility to declare an untyped unitialized static var seems an ok price to pay ^^

**Comment by Simn** [comment]
Yes I think we should do that.

**Comment by Simn** [comment]
Requires a decision.

**Comment by ncannasse** [comment]
I'm fine with forbidding `static var x;` without an initializer
