### ISSUE TITLE
[display] @type not working on extern function declarations

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6442]
```haxe
class Main {
	static function main() {}
}

extern class Foo {
	/** some docs **/
	var foo:Int;

	/** some docs **/
	function bar():Void;
}
```

`@type` doesn't work on the names of extern function declarations:

```
> haxe --display Main.hx@135@type
Error: No completion point was found
```

At the same time, on variables it somehow works fine:

```
> haxe --display Main.hx@94@type
<type p="..\main.hx:7: characters 6-9" d=" some docs ">
Int
</type>
```

Works fine on _usages_ of `foo` too.

**Comment by nadako** [comment]
What I could figure out so far is that the display check is done in the `bind_type` callback, which is not called because `fctx.do_bind` is `false`.
