### ISSUE TITLE
[eval] EvalExceptions.Break

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6443]
Isolated from complex code, but I still wish this to be smaller! Sorry about it :stuck_out_tongue: 

https://gist.github.com/azrafe7/166480f327a013551884aaba7428342f

Running this code with `haxe -main EvalBreakLoop -neko bin\evalbreakloop --macro EvalBreakLoop.test()`, it fails with `EvalExceptions.Break`. Works if compiled regularly.

Additional note: in the big project this was extracted from I didn't get any error in the output (no `EvalExceptions.Break`), but could only notice that it was returning a different result.

I'm on haxe 4.0.0 (git build development @ 266848f52), please let me know if this has already been fixed in a more recent version.

**Comment by nadako** [comment]
Reproduces on latest `development` with the following code run with `haxe --macro Main.main()`, but not with `-main Main --interp`:

```haxe
class Main {
	static function main() {
		var first = true;
		do {
			if (first) {
				first = false;
				continue;
			}
			break;
		} while (true);
	}
}
```

Stacktrace:
```
Fatal error: exception EvalExceptions.Break
Raised at file "_build/src/macro/eval/evalEmitter.ml", line 389, characters 21-32
Called from file "_build/src/macro/eval/evalEmitter.ml", line 264, characters 35-48
Called from file "_build/src/macro/eval/evalEmitter.ml", line 312, characters 16-58
Called from file "_build/src/macro/eval/evalEmitter.ml" (inlined), line 1346, characters 9-17
Called from file "_build/src/macro/eval/evalEmitter.ml", line 1387, characters 3-34
Called from file "_build/src/macro/eval/evalExceptions.ml", line 116, characters 10-13
Re-raised at file "_build/src/macro/eval/evalExceptions.ml", line 147, characters 2-11
Called from file "_build/src/macro/macroContext.ml", line 554, characters 10-123
Called from file "_build/src/macro/macroContext.ml", line 774, characters 8-41
Called from file "list.ml", line 77, characters 12-15
Called from file "_build/src/compiler/main.ml", line 776, characters 2-73
Called from file "_build/src/compiler/main.ml", line 387, characters 3-11
Called from file "_build/src/compiler/main.ml", line 911, characters 1-35
```

**Comment by azrafe7** [comment]
@nadako, hey, quite the reduction!

Can I ask how you manage to do it?
And the stack trace (I tried setting `ocamlparam=b`)?

**Comment by nadako** [comment]
> Can I ask how you manage to do it?

Well just simplify/remove bits of code until it stops giving an error :)

> And the stack trace (I tried setting ocamlparam=b)?

It's `OCAMLRUNPARAM=b`
