### ISSUE TITLE
[error spam] unification error within anon function body prevents further type inference

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6453]
Consider the following code:
```haxe
class C {
	public function new() {}
	public function f(v = false) {}
}

class Main {
	static function main() {
		var c = null;
		cb(function() {
			// 1 + false; // doesn't inference
			("" : Int); // prevents inference
			c = new C();
		});
		$type(c); // Unknown<0>
		c.f();
		c.f(true); // ERROR: Too many arguments (obviously)
	}

	static function cb(f:Void->Void) {}
}
```

The type of `c` stays unknown because of the `("":Int)` error, which potentially leads to different further errors (like too many arguments in this case).

Interestingly, if we comment the `("":Int)` and uncomment `1+false`, type of `c` is inferred correctly.

Moreover, both errors don't prevent inference if we don't use anon function and insert its body at the place of the `cb` call.

**Comment by Simn** [comment]
The problem is that this is a unification error in a call argument. In the general case, we have to error out of these in order to support `@:overload` functions.

I'm not sure if this is worth fixing, especially because it's gonna risk making overload selection even more complicated than it already is.

**Comment by Simn** [comment]
Looking at this again I still don't think it's worth fixing it. Unification errors (or any errors for that matter) can always bring some follow-up errors. We have to do error handling early to deal with overloads, and I don't think it's worth introducing a special case for non-overloads here.

Unless I'm missing how this can lead to larger problems, I prefer to not address this.
