### ISSUE TITLE
[display] include enum constructors in toplevel completion if applicable

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6454]
```haxe
class Main {
    public static function main() {
        f(|);
    }

    static function f(t:Type.ValueType) {}
}
```

```
> haxe --display Main.hx@0@toplevel
```

If you request toplevel completion at `|`, the constructors of `Type.ValueType` are not listed in completion.  This is despite Haxe allowing to use the unqualified constructor names here, because `Type.ValueType` is the expected type at this position.

The only way around this is to add an import for `Type.ValueType`, which is somewhat annoying because it's not necessary. Also, the import will be marked as unused:

![](http://i.imgur.com/MOjjmip.png)

**Comment by Simn** [comment]
Part of the problem is that toplevel-completion is block-based. Fixing this might require some work.
