### ISSUE TITLE
[lua] slow code generated for Math.min & Math.max

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#6455]
`Math.min`/`Math.max` generate inline functions instead of just calling Lua's own `math.min`/`math.max`. I call these a lot, so several of my intersection and vector functions take about twice the amount of time they should... Is there a reason they need to be this way? My math code has turned to `#if`-soup trying to get better performance.

if it needs to be this way to pass tests, it'd at least be nice to not be spitting out new functions every single time it gets called, it's a lot of extra code and luajit doesn't seem to like it.

output with standard math:
```lua
__math__Vec3_Vec3_Impl_.max = function(a,b) 
  local a1 = a[0];
  local b1 = b[0];
  local x = (function() 
    local _hx_1
    if (Math.isNaN(a1) or Math.isNaN(b1)) then 
    _hx_1 = (0/0); else 
    _hx_1 = _G.math.max(a1, b1); end
    return _hx_1
  end )();
  local a2 = a[1];
  local b2 = b[1];
  local y = (function() 
    local _hx_2
    if (Math.isNaN(a2) or Math.isNaN(b2)) then 
    _hx_2 = (0/0); else 
    _hx_2 = _G.math.max(a2, b2); end
    return _hx_2
  end )();
  local a3 = a[2];
  local b3 = b[2];
  local z = (function() 
    local _hx_3
    if (Math.isNaN(a3) or Math.isNaN(b3)) then 
    _hx_3 = (0/0); else 
    _hx_3 = _G.math.max(a3, b3); end
    return _hx_3
  end )();
  local this1 = ({length = 3});
  local this2 = this1;
  this2[0] = x;
  this2[1] = y;
  this2[2] = z;
  do return this2 end;
end
```

output with lua's math:
```lua
__math__Vec3_Vec3_Impl_.max = function(a,b) 
  do return __math__Vec3_Vec3_Impl_._new(_G.math.max(a[1], b[1]), _G.math.max(a[2], b[2]), _G.math.max(a[3], b[3])) end;
end
```
using latest haxe (e3a022dd4)

**Comment by jdonaldson** [comment]
Weird, I inlined these thinking they'd be faster.  The reverse is the case.  Check the latest commit on your end when you get a chance.

**Comment by jdonaldson** [comment]
Also note : I had to add some extra checks for NaN in the std math lib.  But, if you can avoid passing NaN some other way, you could use the faster base lua math methods.

**Comment by jdonaldson** [comment]
I'm going to close this, as I believe the changes in the commit addressed the speed hit.
