### ISSUE TITLE
[cs] IntMap bug

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6457]
```haxe
class Main {
	static function main() {
		var m = new haxe.ds.IntMap<Int>();
		m.set(24, 1);
		m.set(0, 1);
		m.remove(24);
		m.set(0, 1);
		trace(m);
	}
}
```

traces
```
Main.hx:8: {0 => 1, 0 => 1}
```

**Comment by nadako** [comment]
Looks like this `_keys[idx] = 0` on removal is screwing up the `_keys[i] == key` check in `set` for actual `0` keys. I wonder if setting `-1` there will solve the issue or there can be more clashes in some cases...

**Comment by nadako** [comment]
I also see that the [original implementation](https://github.com/attractivechaos/klib/blob/master/khash.h#L325) does the "isdel" check in that loop, maybe we're missing it? I don't really understand yet what's going on here, have to read a bit more...

**Comment by nadako** [comment]
Hm, we had that check originally, but it was reworked for "optimizations" in a2894a93ff691e9ed8fc1ca2da524e51347b2c1e... Is it really equivalent?

**Comment by nadako** [comment]
cc @jonasmalacofilho - maybe you remember something about this?

PS sorry to bother you guys, but it's a bit urgent for me since it's a bug in production and I'd love to fix it ASAP

**Comment by jonasmalacofilho** [comment]
:+1:

FYI: here's the implementation mentioned in the comment: [IntDict.hx (aka artifact 887b531)](https://gist.github.com/jonasmalacofilho/cf38e8e670c29e07b067b91e337ee3c1)

**Comment by jonasmalacofilho** [comment]
Disclaimer: I can't say I really understand the entire thing yet!

It looks to me that the [while condition](https://github.com/HaxeFoundation/haxe/blob/679e657839742f60559e442d297af19aa68df505/std/cs/_std/haxe/ds/IntMap.hx#L83) should be

```haxe
!( flagIsEmpty(flags, i) || (!flagIsDel(flags,i) && _keys[i] == key) )
```

... we should only compare the keys if "del" has not been set.

Does this make any sense?

---

(err, how do I locally run the Haxe unit tests these days?)

**Comment by nadako** [comment]
Yeah, that's what basically done in [khash implementation](https://github.com/attractivechaos/klib/blob/master/khash.h#L325) and was done in IntHash before a2894a93ff691e9ed8fc1ca2da524e51347b2c1e, but since the code we have now is quite different from both sources, I can't say for sure if it's safe to add the check back...

**Comment by nadako** [comment]
> (err, how do I locally run the Haxe unit tests these days?)

cd tests/unit
haxe compile-cs.hxml
bin/cs/bin/TestMain-Debug.exe
