### ISSUE TITLE
wrong throw in JS

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6458]
The following Haxe code:

```haxe
class Main {
    static function foo() throw [];
    static function main() {
         try foo() catch( e : String ) {};
    }
}
```

Produces the following output:

```js
Main.main = function() {
        try {
                Main.foo();
        } catch( e ) {
                if (e instanceof js__$Boot_HaxeError) e = e.val;
                if( js_Boot.__instanceof(e,String) ) {
                } else throw(e);
        }
};
```

As you can see, the error being rethrow is the Array itself, so we are losing the stack in that case. I think we should either throw the original HaxeError before unwrap or a new HaxeError using the previous error stack as parameter, the idea is to keep the foo() stack information.

Might be a regression from @nadako changes in cc0a1a71b4ae7bbd938845c6f2e3499a336f8db9, not sure.

**Comment by nadako** [comment]
Yep, we should throw original error here. Also I should look into re-using TryCatchWrapper filter now when it doesn't depend on gencommon...

**Comment by nadako** [comment]
I have a spec question here, should this work?
```haxe
try throw "not js.Error" catch (e:js.Error) trace("CAUGHT");
```

It does currently in C#/Java (substitute js.Error with corresponding base exceptions), but it doesn't in JS, because HaxeError is unwrapped before the type check.

Personally I feel like it'd be more useful if it worked. OTOH it can be a bit surprising in a simple example like this.

**Comment by ncannasse** [comment]
I'm fine with both, whatever is ok for you

**Comment by nadako** [comment]
This now compiles to:
```js
Main.main = function() {
    try {
        Main.foo();
    } catch( e ) {
        if(typeof((e instanceof js__$Boot_HaxeError) ? e.val : e) != "string") {
            throw e;
        }
    }
};
```
:-)
