### ISSUE TITLE
typing order vs inline

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6460]
```haxe
class Other {
    public static inline function callMainF() {
        Main.f();
    }
}

class Main {
    public static function f() {
        Other.callMainF();
    }
}
```

generated js:

```js
Main.f = function() {
	Other.callMainF();
};
```

however if we move `Other` below `Main`, we get `callMainF` proprely inlined:

```js
Main.f = function() {
	Main.f();
};
```

It's a bit of an issue for me because in my case I define that `Other` in a build-macro for `Main`, so I can't easily fix the declaration order.

Also if we add `@:extern` to `Other.callMainF`, it won't be generated, but the call for it will be generated without any errors.

**Comment by nadako** [comment]
If this is too hard or impossible to fix, maybe we could have some macro API to delay new type definitions to make them happen after current class is built?

**Comment by ncannasse** [comment]
Seems indeed like a bug, maybe even a regression against an olddddd version of haxe. Letting @Simn look into it first.

**Comment by Simn** [comment]
I have no idea what to look for here. The build order is what I would expect:

```
out 0 add build-module ()
out 0 add build-class (Main)
out 0 flush final(final)
out 1         run build-module ()
out 1         run build-class (Main)
out 2                 init_class_done Main
out 2                 add type-field (Main:main)
out 2                 init_class_done Main
out 2                 add type-field (Main:f)
out 1         run build-class (Main.Other)
out 2                 init_class_done Other
out 2                 add type-field (Main.Other:callMainF)
out 1         run type_fun (Main.Other:callMainF)
out 2                 run type_fun (Main:f)
out 1         run type_fun (Main:main)
out 0 flush-done
```

Isn't this basically lottery? If the inline field is typed first, we're good because we only need the type of the non-inline field, which we can substitute with a monomorph at first. If the non-inline field is typed first, we're out of luck because we need the _expression_ of the inline field in order to inline it. We don't have that yet and cannot substitute it.

**Comment by ncannasse** [comment]
That's a chicken-and-macro-egg problem here.

Generating that should maybe work maybe?

```
class Other {
    public static inline function callMainF() {
        if( false ) Main.f();
        realCallMainF();
    }
    static inline function realCallMainF() {
          Main.f();
    }
}

class Main {
    public static function f() {
        Other.realCallMainF();
    }
}
```

**Comment by nadako** [comment]
Oh my... I'll try that when I get back to that code.

**Comment by Simn** [comment]
This doesn't seem to reproduce any longer. I'm seeing this output for both cases:

```js
Main.f = function() {
	Main.f();
};
```
