### ISSUE TITLE
Complete Sys unit tests

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6461]
Following a recent discussion with @nadako we badly need complete "sys" package unit tests for Haxe 4.0 release if we want to ensure common behavior for all cases (invalid file path, etc.).

Current sys unit tests are quite mangled and don't do much, we should rewrite from scratch, and directly include them in our common unit tests #if sys

**Comment by ncannasse** [comment]
Any volunteer?

**Comment by andyli** [comment]
Related: #4773, #4774, and possibly more.

I wanted to do that last year, but I found out we have to deal with unicode (#3072) first since the platform APIs depend on encoding a lot.

**Comment by darmie** [comment]
@andyli @ncannasse  concerning Unicode, what's the update so far?

**Comment by andyli** [comment]
Read the discussion at #3072.

**Comment by Simn** [comment]
#8135
