### ISSUE TITLE
Can @:hack be allowed to override a @:final function?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6462]
The [docs](https://haxe.org/manual/cr-metadata.html) say that `@:hack` allows overriding `@:final` **_classes_**. That's nice.

It seems natural, then, that `@:hack` on a member function would allow overriding a base class's `@:final` _**function**_, but this seems not to be the case: https://try.haxe.org/#23a42

Is there some reason it works only for classes? Or is this difficult to implement for functions?

**Comment by Simn** [comment]
I don't like `@:hack` very much. It is nice enough as long as it's a simple ignore-flag, but `@:final` actually influences code generation on some targets (C# and Java, maybe others). Usage of `@:hack` would then lead to native compilation errors.

Let's move towards less hacks, not more.
