### ISSUE TITLE
ptmap woes

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/haxe#6465]
Trying to build haxe. Since ptmap 2.0.1 isn't installing I did...

```
git clone https://github.com/backtracking/ptmap
opam install ptmap.1.0.0
opam pind add ptmap ptmap
cd haxe
make
```
I then get the following error...

```
File "_build/src/optimization/inlineConstructors.ml", line 518, characters 4-18:
Error: Unbound value IntMap.for_all
make[1]: *** [_build/src/optimization/inlineConstructors.cmx] Error 2
make: *** [haxe] Error 2
```

**Comment by Simn** [comment]
How did you resolve this?

**Comment by thomasuster** [comment]
@Simn I did `opam switch 4.04.2`. I could modify travis to get the working if you guys want, but not sure what @andyli 's plan is.

**Comment by andyli** [comment]
The ptmap issue will be fixed by https://github.com/backtracking/ptmap/pull/4.

But even if ptmap is fixed, there are still some remaining issues. For one, opam failed to install [ocaml-migrate-parsetree](https://github.com/let-def/ocaml-migrate-parsetree) for multiple versions of OCaml... at least that's the result of my fix attempts a few days ago.

@thomasuster: If you manage to fix our Travis somehow, please do.

**Comment by andyli** [comment]
Oh, I think I fixed the Mac builds. Turn out the problem I had with ocaml-migrate-parsetree was that, I missed an `opam config env` before `opam install ...`.

**Comment by tanis2000** [comment]
Any idea when the ptmap patch will be merged upstream? Trying to work with the git version of Haxe with Homebraw is near to impossible at the moment

**Comment by thomasuster** [comment]
Did you try open switch I mentioned above? Not perfect but worked for me

**Comment by andyli** [comment]
I've just pinged the upstream again https://github.com/backtracking/ptmap/pull/4#issuecomment-321714618

**Comment by tanis2000** [comment]
@thomasuster it looks like it's working but I'm having troubles fixing the homebrew formula on macOS. The same steps that work in the shell aren't working from the script which is weird.

**Comment by tanis2000** [comment]
I opened a PR on homebrew in the meanwhile so that people like me can still use the git version of haxe while thigns move forward :)
https://github.com/Homebrew/homebrew-core/pull/16672
