### ISSUE TITLE
Haxe throwing errors on CentOS 6.8

### ISSUE THREAD

**Issue by binhbui** [HaxeFoundation/haxe#6468]
Hi

I'm trying to compile a Haxe project on a CentOS 6.8 server. 

We're using nvm/npm to install haxe: npm install -g haxe

At that point running 'haxe' throws the following errors:

`/var/lib/jenkins/nvm/versions/node/v4.5.0/lib/node_modules/haxe/downloads/haxe/haxe: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /var/lib/jenkins/nvm/versions/node/v4.5.0/lib/node_modules/haxe/downloads/haxe/haxe)
/var/lib/jenkins/nvm/versions/node/v4.5.0/lib/node_modules/haxe/downloads/haxe/haxe: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/lib/jenkins/nvm/versions/node/v4.5.0/lib/node_modules/haxe/downloads/haxe/haxe)`

Is there no support for GLIBC_2.12?

**Comment by ibilon** [comment]
glibc 2.12 is very old, the build server uses a more recent version,
you'll have to build haxe from source if you want support for it. (you may have issues with ocaml being too old too)

**Comment by Simn** [comment]
What he said.
