### ISSUE TITLE
why allow implicit cast String to `{}`

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6469]
```haxe
var obj: {} = "hallo";
```

**Comment by Simn** [comment]
Because `String` is a class. But yes, this tends to be a problem because String doesn't really follow class semantics everywhere. Not sure if it's worth a special case to disallow this though...

**Comment by R32** [comment]
I found that i can use `Dynamic<Any>` instead of `{}` as the type of Object of javascript. even it's not very readable.
