### ISSUE TITLE
Breaking `if (cond) expr; else expr;` for haxe 4?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6477]
I would like to propose disallowing a special syntax that is currently supported:

```haxe
if (expr1)
    expr2;
else
    expr3;
```

The problem is the `;` after `expr2`. There's currently a hack in the parser to look ahead 2 tokens in order to support this:

```ocaml
	| [< '(Kwd If,p); '(POpen,_); cond = expr; '(PClose,_); e1 = expr; s >] ->
		let e2 = (match s with parser
			| [< '(Kwd Else,_); e2 = expr; s >] -> Some e2
			| [< >] ->
				match Stream.npeek 2 s with
				| [(Semicolon,_); (Kwd Else,_)] ->
					Stream.junk s;
					Stream.junk s;
					Some (secure_expr s)
				| _ ->
					None
		) in
```

I'm not a grammar expert or anything, but I believe this makes the Haxe syntax a LL(2) grammar due to the 2 lookaheads being required. This has given me a lot of trouble trying to support Haxe syntax in other parser generators.

Given that this doesn't really add anything to the syntax, could we disallow it for Haxe 4?

**Comment by back2dos** [comment]
Arguably, this looks somewhat better with the semicolon:

```haxe
{
  if (condition) consequence;
  else alternative;
}
```

But it can look weird just as quickly:

```haxe
var a = [4, if (condition) 5; else 6, 7];
var o = {
  foo: if (condition) 5; else 6, 
  bar: 12,
}
```

Personally I'm for it, if it makes parsing easier. It's certainly more consistent, given that `try expr; catch (ident:ComplexType) expr;` doesn't parse.

**Comment by nadako** [comment]
While it might come as a surprise for people used to languages with statements, I agree this is a weird special case that's not consistent with other similar constructs as Juraj noted. And people nowadays advocate using curly braces for if/else expressions, in which case semicolons in blocks are parsed as expected.

It'll still break a lot of code, I think, but if we can provide a migration tool, I think we can do it.

**Comment by jcward** [comment]
I'll admit, I don't use that syntax often, but sometimes my OCD side likes how the 2-liner looks:

```haxe
  if (cond) something();
  else nevermind();
```

I warn that you may force us to go ternary. Once you go ternary, you never go, err, LL(2), I guess.

```haxe
cond ? something() : nevermind();
```
So... you can't just say that `/;\s*else/` is the token? :grin:

**Comment by Simn** [comment]
> So... you can't just say that /;\s*else/ is the token? 😁

Unfortunately not. There can be cases like this:

```haxe
  if (cond) something(); // do something
  else nevermind();
```

There can even be this, although that's probably more of an argument against removal:

```haxe
  if (cond) something();
  #if js
  else nevermind();
  #end
```

**Comment by back2dos** [comment]
@jcward So how does your inner OCDemon deal with:

```haxe
var a = [
  entry,
  andAnotherOne,
  if (cond) something(); //<---- muaharhar!!! ... sorry ;)
  else nevermind(),
  whatever(),
];
```

**Comment by jcward** [comment]
My inner OCDemon had 1) stripped comments, and 2) processed compiler flag blocks, before parsing. 😋 Err, and he also accounted for file position in all of that by leaving whitespace in his terrifying wake.

**Comment by ncannasse** [comment]
I don't like much breaking things just for the sake of compiler implementation details. I can tell you how annoyed I would be by the change if I try to compile my codebase with this not allowed.

Let me try to run it...

That's about 800 breaking changes, way too much.
Maybe another approach, were if we find a "else" <expr> in a block, we append it to the previous "if" or error if there was none.

Also all C languages have it, so there should be a way to define it in most cases. I'm fine if it's only in blocks and if we don't allow @back2dos example, which should be quite minor compared all other changes.

**Comment by Simn** [comment]
> That's about 800 breaking changes, way too much.

That seems a lot... are you sure you broke it correctly?

**Comment by ncannasse** [comment]
Just added a prerr_endline in the parser code after the npeek, then count the output lines.

**Comment by Simn** [comment]
Meh, I really don't like this one, it looks so wrong... :(
