### ISSUE TITLE
Function.bind does not work with non-constants

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6480]
[Here](https://try.haxe.org/#92C03)'s an example:

```haxe
class Test {

    static function main() {
        var o = {
            blub: blub.bind({ counter: 0 })
        }
        trace(o.blub(true));//1 - as expected
        trace(o.blub(true));//1 - whoops
    }

    static function blub(o:{ counter: Int}, increment:Bool) {
        if (increment) o.counter++;
        else o.counter--;
        return o.counter;
    }

}
```

That's because at every call of `o.blub` it gets a new `{ counter: 0 }`.

The generated JS shows that:

```js
var o_blub = function(a1) {
	return Test.blub({ counter : 0},a1);
};
```

This is a regression introduced by 3.3.0-rc.1 (behavior was correct in 3.2.1).

**Comment by Simn** [comment]
I'm seeing this output:

```js
Main.main = function() {
	var o_blub = (function(f,o) {
		return function(increment) {
			return f(o,increment);
		};
	})(Main.blub,{ counter : 0});
	console.log(o_blub(true));
	console.log(o_blub(true));
};
```

Are you on 3.4.2?

**Comment by back2dos** [comment]
The output I gave above is the one produced by try.haxe.org, so yes, that's 3.4.2 (according to `// Generated by Haxe 3.4.2`). 

For further comparison:

- 3.3.0-rc.1: http://try-haxe.mrcdk.com/#6c8eE --> nope
- 3.2.1 with analyzer: http://try-haxe.mrcdk.com/#a8c60  --> nope
- 3.2.1 without analyzer: http://try-haxe.mrcdk.com/#cb047  --> wohooo!

Only the last one works correctly. Beyond 3.2.1 disabling analyzer (whatever that radio button does exactly) does not correct the problem.

**Comment by Simn** [comment]
Well, it seems to work with latest Haxe, so I'll just assume that @basro's changes to inlining fixed this.

**Comment by nadako** [comment]
Huh, for me it generates
```js
Main.main = function() {
	var o_blub = function(increment) {
		return Main.blub({ counter : 0},increment);
	};
	console.log(o_blub(true));
	console.log(o_blub(true));
};
```
regardles of `-D analyzer-optimize`

**Comment by Simn** [comment]
wtf, I had `-D no-copt` in my hxml and apparently that fixes it...

**Comment by Simn** [comment]
Turns out `-D no-copt` disables optimizations, so that explains that...
