### ISSUE TITLE
[SWF] Safe cast doesn't throw exception in case of a failing cast 

### ISSUE THREAD

**Issue by wolfhoundgelert** [HaxeFoundation/haxe#6482]
In the haxe manual https://haxe.org/manual/expression-cast-safe.html

> The Haxe compiler guarantees that an exception of type String is thrown in this case.

But nothing happens on SWF-target https://try.haxe.org/#9c38D

**Comment by Simn** [comment]
Are you testing this in a debug flash player? Check if a `throw` does something I guess.

**Comment by wolfhoundgelert** [comment]
![image](https://image.prntscr.com/image/sZZOCmIFT9S3hefnE0BJqw.png)

**Comment by back2dos** [comment]
You're not using the result of the cast, so it's just optimized away:

- result unused, no exception: https://try.haxe.org/#eCeBc
- result used, exception: https://try.haxe.org/#1914E

Related: #5774

**Comment by nadako** [comment]
#5774 was about unsafe cast, this is a safe cast tho, so it shouldn't be optimized away, I think.

**Comment by Simn** [comment]
> You're not using the result of the cast, so it's just optimized away

That shouldn't be the case because a safe-cast is not side-effect free. I see the cast in the dump...

**Comment by nadako** [comment]
This condition looks suspicious https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genswf9.ml#L1318, but i'm pretty sure it was there for ages...

**Comment by wolfhoundgelert** [comment]
@back2dos 

> result used, exception: https://try.haxe.org/#1914E

Ok, but we have different behavior on JS (exception) and on SWF (null) if we do cast with null
https://try.haxe.org/#fAaDd

**Comment by Simn** [comment]
This is indeed a (very old) SWF generator bug.

**Comment by wolfhoundgelert** [comment]
@nadako 
> but i'm pretty sure it was there for ages...

I've caught this bug on some big real project after huge amount of error-reports in our log-system))

**Comment by wolfhoundgelert** [comment]
Thanks a lot!)

**Comment by Simn** [comment]
Nice, the test I added fails on C++, C#, Java and lua.

**Comment by hughsando** [comment]
Maybe you should just change the documentation.

**Comment by wolfhoundgelert** [comment]
@Simn 
Which behaviors are correct?

1) JS: trace(cast(null, Int));
uncaught exception: Error: Cannot cast null to { __name__ : [Int] },,line:0

2) SWF: trace(cast(null, Int));
Class cast error

3) JS:  trace(cast(null, haxe.Timer));
uncaught exception: Error: Cannot cast null to { __name__ : true },,line:0

4) SWF:  trace(cast(null, haxe.Timer));
null

**Comment by SlavaRa** [comment]
Java:
``` haxe
trace(cast(null, haxe.Timer)); //null;
trace(cast(null, Int)); //0;
```

CSharp:
```haxe
trace(cast(null, haxe.Timer));//null;
trace(cast(null, Int));//0;
```

CPP:
```haxe
trace(cast(null, haxe.Timer));//null;
trace(cast(null, Int));//null;
```

**Comment by wolfhoundgelert** [comment]
@SlavaRa 
So 1, 2, 3 in my question are wrong and must be with none-exception result?
And only SWF: trace(cast(null, haxe.Timer)) works correctly?)

**Comment by hughsando** [comment]
I'm guessing it should throw.  I'm happy enough to define cast(a,b) as the "throwing cast".  I don't like the terms safe/unsafe since these have a loaded definition in c++, but as long as I understand.  This is always and only the TCast(a,b) ast node?

The "other" cast,  is a bit less well defined.  As far as the ast goes, I can't trust it in terms of just reinterpreting the type.  But it is also used by abstracts which is a potential slowdown if I don't trust it.  I would like to see TCast(a,b,mode) where mode is Throwing/User/Trusted.

**Comment by Simn** [comment]
See #3848 for a lengthy related discussion...

> I would like to see TCast(a,b,mode) where mode is Throwing/User/Trusted

I had that idea before because we insert casts very liberally in the compiler.

**Comment by ncannasse** [comment]
`cast(null, T)` should be the same as doing `var x : T = cast null;`  on static targets, so it should be null for object, an default value for core types.

**Comment by waneck** [comment]
AFAIK that's exactly how Java/C# work already

**Comment by jdonaldson** [comment]
Revisiting some of my lua bugs and found this page turner.  I'm not sure what to do here after reading through it.  Do dynamic targets throw errors for cast()?

**Comment by RealyUniqueName** [comment]
All targets should throw on failed casts with two arguments. E.g. `cast("foo", Int)`.

**Comment by RealyUniqueName** [comment]
> AFAIK that's exactly how Java/C# work already

Cs and java are still failing on unit.issues.Issue6482.hx

**Comment by nadako** [comment]
> Do dynamic targets throw errors for cast()?

Yep, JS basically does `if (Std.is(a, B)) cast a else throw "invalid cast"` for safe-casts.
