### ISSUE TITLE
Compiler can't read multiple line of variable with same access type

### ISSUE THREAD

**Issue by DQvsRA** [HaxeFoundation/haxe#6483]
I like to write my code with less duplication, so I usually removing multiple access type for variables like this:
private var 
		_graphics	:Graphics,
		_position	:Point,
		_colorInner	:UInt,
		_colorOuter	:UInt
	;

But Haxe compiler does not allow that construction:
Source/Main.hx:18: characters 13-21 : Missing ;

Could you please make it possible?

**Comment by Simn** [comment]
We currently do not plan to introduce such syntax.
