### ISSUE TITLE
Java interface issue

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6486]
See #5062

**Comment by nadako** [comment]
```haxe
interface IY {
	function getY():Float;
}

class Point implements IY {
	public function new() {}

	public function getY():Int {
		return 10;
	}
}
```

```
src\haxe\root\Point.java:26: error: getY() in Point cannot implement getY() in IY
        public int getY()
                   ^
  return type int is not compatible with double
```

**Comment by nadako** [comment]
C# uses explicit interface method implementation to work this around:
```cs
	double global::IY.getY() {
		return ((double) (this.getY()) );
	}
```

not sure what can be done for Java...

**Comment by nadako** [comment]
@waneck I assume Java doesn't support return-type overloads, so we can't even make a non-explicit implementation here, right?

**Comment by waneck** [comment]
I really feel like this shouldn't be allowed by Haxe

**Comment by Simn** [comment]
It looks silly in a Float/Int scenario, but it is sound from the type system point of view because variance allows it.

**Comment by Simn** [comment]
I'm coming back to this issue wondering if this kind of variance is actually sound in the case of interfaces. The way Haxe/Java dodges this is by rewriting the implementation to return `double` instead of `int` if one of the interfaces mandates that. However, we can easily make conflicting demands here:

```haxe
class Main {
	static public function main() {
		var iy:IYFloat = new Point();
		trace(iy.getY());

		var iy:IYInt = new Point();
		trace(iy.getY());
	}
}

interface IYFloat {
	function getY():Float;
}

interface IYInt {
	function getY():Int;
}

class Point implements IYFloat implements IYInt {
	public function new() {}

	public function getY():Int {
		return 10;
	}
}
```

This doesn't compile through javac:

```
src\haxe\root\Point.java:7: error: Point is not abstract and does not override abstract method getY() in IYInt
public class Point extends haxe.lang.HxObject implements haxe.root.IYInt, haxe.root.IYFloat
       ^
src\haxe\root\Point.java:26: error: getY() in Point cannot implement getY() in IYInt
        public double getY()
                      ^
  return type double is not compatible with int
2 errors
```

genjava tries to rewrite the implementation to please one of the interfaces, but in doing so violates the constraint of the other interface. This can not be fixed either because return type overloading is thankfully not a thing in sane languages, and not in Java either.

IMO variance between implementation return and interface return should not be allowed.

**Comment by Simn** [comment]
Note that this might be specific to Float vs. Int variance.

**Comment by back2dos** [comment]
> IMO variance between implementation return and interface return should not be allowed.

This'll be awkward:

```haxe
class A {}
class B extends A {}

interface Foo {
  function foo():A;
}

class Fooish {
  public function foo():A;
}
class FooishSub {
  override public function foo():B;//works, because it makes sense
}

class RealFoo implements Foo {
  public function foo():A;
}
class RealFooSub extends RealFoo {
  override public function foo():B;//should this work or not?
}
```

Unless you're suggesting to also disallow narrowing return type when overriding. Let's please not do that.

**Comment by Simn** [comment]
See my subsequent comment, this is specific to Int vs. Float because that relationship is not reflected at Java run-time. I don't think we can generate this code to the Java target.

**Comment by back2dos** [comment]
Well, there's always `java.lang.Number` but I guess that'll introduce more problems than it solves.

**Comment by Simn** [comment]
We could indeed rewrite both the interfaces and the implementation to that, yeah. I think that would work, but I don't like the idea that implementing an interface silently rewrites my implementations... This would also have to spread: Other implementations of these interfaces would have to be patched to use `java.lang.Number` as well.

**Comment by RealyUniqueName** [comment]
Moving to "Bugs" milestone as it works in JVM target, which is our primary "java" target now.

**Comment by nadako** [comment]
Let's add `#if !java` test then \o/

**Comment by RealyUniqueName** [comment]
I think [it's already added](https://github.com/HaxeFoundation/haxe/pull/5062#issuecomment-319665168)

**Comment by Simn** [comment]
I guess there's nothing left to do here then. It works on the JVM target because a bridge function is generated on the implementing class:

```
  public synthetic bridge getY()D
   L0
    ALOAD 0
    INVOKEVIRTUAL haxe/root/Point.getY ()I
    I2D
    DRETURN
```
