### ISSUE TITLE
`FileSystem.exists ("/")` fails on macOS

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#6489]
I'm not sure if this is expected behavior or not, but `FileSystem.exists` (and then `FileSystem.isDirectory`) fails on Neko if the argument is the root filesystem or hard-drive. I have a report that this occurs for "D:\" on Windows, for example, and confirmed it occurs for "/" on macOS.

If this expected, we should probably document it

Thank you :smile:

**Comment by back2dos** [comment]
Try-catching readDirectory generally is the most reliable. IIRC it's the only thing that works for certain UNC paths.

**Comment by Simn** [comment]
@Aurel300 Could you check that?

**Comment by Aurel300** [comment]
Can confirm this still fails on neko, cpp, HL.
