### ISSUE TITLE
[js] return in __init__

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6490]
```haxe
class Main {
    static function main() {
        trace('foo');
    }
    static function __init__() {
        return;
    }
}
```

is generated as

```js
// Generated by Haxe 3.4.2
(function () { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("foo");
};
return;
Main.main();
})();
```

We can see that `__init__` is not generated as an actual function. So writing `return` inside it becomes a global `return` in the output. Causing the program to terminate before `main` is even run.

**Comment by Simn** [comment]
That is exactly what `__init__` is supposed to do. The only question is why it is a function and not a var field, but at this point I don't think we should change that...

**Comment by kevinresol** [comment]
I don't think this should be closed without doing anything.
Anyone who writes `return` inside a function expects to return from the current function (`__init__` in this case) and the current behavior is obviously confusing.

**Comment by Simn** [comment]
Yes but `__init__` is one of these low-level things where you kind of have to know what you're doing. For instance, it's very sensitive with regards to static initialization order, exception handling probably doesn't work, expressions aren't cleaned up by the analyzer and so on.

Basically, don't use `__init__`. Why do you think you need it?

**Comment by back2dos** [comment]
Agree with Kevin. The simplest thing would be to wrap the code in a self-executing anonymous function.

**Comment by back2dos** [comment]
Sorry, missed your comment @Simn. I tend follow "don't use `__init__`" and I just realized that `Compiler.includeFile` actually would in some cases not work as intended in `__init__` if it were wrapped.

That said, if disallowing `return` in `__init__` were possible, I think it would prevent one of the thousand ways to shoot yourself in the foot. It's not too far fetched to write code like this:

```haxe
static function __init__() {
  #if !debug return; #end
  //set up some debug stuff
}
```

This would work just fine on some platforms, but switch to JS and things just silently do nothing.

**Comment by kevinresol** [comment]
I think it would be good enough to give a warning on "return in __init__() is used to terminate the whole program on js platform". Who knows if someone really intended to do that, given he "knows what he is doing"
