### ISSUE TITLE
[lua] Coroutine.wrap returns a Coroutine instead of a Function

### ISSUE THREAD

**Issue by karai17** [HaxeFoundation/haxe#6495]
https://github.com/HaxeFoundation/haxe/blob/development/std/lua/Coroutine.hx#L76

Looking at the above code, it is apparent that `wrap` is returning a coroutine. However, wrap is supposed to wrap a coroutine in a resumer function that resumes the coroutine every time it is called.

```lua
local co = coroutine.wrap(function()
   print "1"
   coroutine.yield()

   print "2"
   coroutine.yield()

   print "3"
end)

co() -- 1
co() -- 2
co() -- 3
co() -- error, coroutine is dead
```

**Comment by karai17** [comment]
unsafe casting the return of Coroutine.wrap to a function works, but I am also running into the static function bug with my code, so I ended up having to do the following to get my code to work:

```
	public static function init(e: Entity, f: (Float->Void)->Void) {
		var routine: Routine = {
			resume: untyped __lua__("coroutine.wrap(function(_, ...) {0}(...) end)", f),
			entity: e,
			delay:  0
		};
		routines.push(routine);

		routine.resume(function(delay: Float) {
			routine.delay = delay - Math.abs(routine.delay);
			Coroutine.yield();
		});
	}
```

**Comment by jdonaldson** [comment]
I have a fix up for this here : https://github.com/HaxeFoundation/haxe/commit/6269d844f5cee3029bc7a2d79a5987f293ff42cf
