### ISSUE TITLE
metadata not apply on generated @:generic classes

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe#6500]
On my case, I try to apply `@:keep` on `@:generic` classe, and keeping is not apply on generated classes. 

with Haxe Compiler 3.4.2 (git build development @ ada466c), target JS

@back2dos provide a workaround by macro, but could be better if its support directly by the Compiler. :)
```haxe 
/**
 * Copy metadata in from generic class to concrete class
 * @example in hxml --macro com.utils.DCEMacroUtil.transplantMetaToGenericInstances()
 * link: http://try-haxe.mrcdk.com/#1b5E0
**/
macro static public function transplantMetaToGenericInstances() {
    haxe.macro.Context.onGenerate(function (types) {
        var marker = ':already transplanted';
        for (t in types)
            switch t {
                case TInst(_.get() => { meta: meta, kind: KGenericInstance(_.get() => original, _) }, _) if (!meta.has(marker)):
                    meta.add(marker, [], original.pos);
                    for (m in original.meta.get())
                        meta.add(m.name, m.params, m.pos);
                default:
            }
    });
    return macro null;
}
```

**Comment by nadako** [comment]
Hmm, could you provide a reproducible example of a problem? @:keep on a @:generic file works as expected (as in - it adds @:keep meta to generic instance classes).

**Comment by aliokan** [comment]
Base on discussion, meta are not copied on generic instance classes, at lease on Javascript target.

**Comment by nadako** [comment]
Well, looks like it's about @:keepSub, not @:keep.

**Comment by aliokan** [comment]
true, @:keep looks working
