### ISSUE TITLE
[dce] Not all interfaces in "cl_implements" checked when looking for a field

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6502]
```haxe
class Test implements IChild {
    public var field(get,never):Int;
    
    function get_field() return 1; //this getter is not generated
    
    public function new() {}
    
    static function main() {
        var t:IChild = new Test();
        trace(t.field);
    }
}

interface IParent1 {
    var field(get,never):Int;
}

interface IParent2 {}

//swap IParent1 and IParent2 to make it work
interface IChild extends IParent1 extends IParent2 {}
```
Result in js:
```
Uncaught TypeError: (intermediate value).get_field is not a function
```
https://try.haxe.org/#8AAe0

The problem is this line (function `field`): https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/dce.ml#L286
`Not_found` is not thrown on checking the first interface, so the rest of interfaces are not checked.

**Comment by Simn** [comment]
> Not_found is not thrown on checking the first interface, so the rest of interfaces are not checked.

I don't think that's the problem because that line catches `Not_found` immediately and recurses.

**Comment by RealyUniqueName** [comment]
That's the problem. Because `Not_found` is NOT thrown thus skipping other interfaces.

**Comment by Simn** [comment]
It is only not thrown if the field is found. Otherwise the recursion ultimately has `cl = []` which leads to the exception being thrown in the first match case.

**Comment by RealyUniqueName** [comment]
Well... It works fine with development version of compiler.
However i don't know which commit to cherry-pick to 3.4.2_bugfix.

**Comment by Simn** [comment]
We would probably have to backport your cl_descendants change...

**Comment by RealyUniqueName** [comment]
I already have a 3.4.2 branch with cl_descendants which i use daily at work: https://github.com/RealyUniqueName/haxe/tree/dce-opt-3.4.2

**Comment by Simn** [comment]
Is this issue fixed on that branch?

**Comment by RealyUniqueName** [comment]
No, it's not.

**Comment by RealyUniqueName** [comment]
I don't know how, but this commit fixes this issue: https://github.com/HaxeFoundation/haxe/commit/a03477e59e88c59af985283d1065ad037770198f
Should i cherry-pick it to 3.4.2_bugfix branch?

**Comment by Simn** [comment]
That suggests to me that something isn't typed correctly. Can you diff the -D dump with/without that commit? Would be interesting to see what changes.

**Comment by RealyUniqueName** [comment]
Broken version:
```
[Call:Int]
	[Field:Void -> Int]
		[Local t(505):IChild]
		[FDynamic:Void -> Int] get_field
```
Fixed version:
```
[Call:Int]
	[Field:Void -> Int]
		[Local t(505):IChild]
		[FInstance:Void -> Int]
			IParent1
			get_field
```

**Comment by Simn** [comment]
This might be an instance of #6225

**Comment by RealyUniqueName** [comment]
That issues seems to be fixed in 3.4.2, while this one is not.

**Comment by RealyUniqueName** [comment]
So what should be done? Cherry-pick that commit to 3.4.2_bugifx?

**Comment by Simn** [comment]
I'm a bit uncomfortable because I would like to understand what's going on here... But I guess we can cherry pick https://github.com/HaxeFoundation/haxe/commit/a03477e59e88c59af985283d1065ad037770198f anyway.

**Comment by RealyUniqueName** [comment]
> But I guess we can cherry pick a03477e anyway.

Cherry-picked to 3.4.2_bugfix
