### ISSUE TITLE
Void functions vs return dynamic

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6503]
dbbafc09c03f443049d66f096ef8444ca91c121b surfaced an issue with returning Dynamic from void-returning functions. Native compilers like AS3 and C++ ones are chocking on this:

```haxe
class Main {
    static function main() {
        f(() -> ("hi" : Dynamic));
    }

    static function f(cb:Void->Void) cb();
}
```

which generates the following AST:
```
[Call:Void]
	[Field:cb : (Void -> Void) -> Void]
		[TypeExpr Main:Class<Main>]
		[FStatic:cb : (Void -> Void) -> Void]
			Main
			f
	[Function:Void -> Void] [Block:Dynamic] [Return:Dynamic] [Cast:Dynamic] [Const:String] "hi"
```

as you can see, even tho the function is `Void->Void`, its body contains a `return "hi"` expression which is then generated like this in e.g. AS3:

```as3
Main.f(function() : void {
	return Main.dyn();
});
```

which is rejected by the AS3 compiler with `Error: Return value must be undefined`

C++ compiler fails similarly: `error: return-statement with a value, in function returning 'void'`

**Comment by hughsando** [comment]
I was just looking at this.  There is a difference here:
```haxe
class Test
{
   public static function exc(func:Void->Void) { }

   public static function main()
   {
     exc( function() haxe.format.JsonParser.parse('{}') );
     exc( () -> haxe.format.JsonParser.parse('{}') );
   }
}
```
where I guess there should not be.

**Comment by nadako** [comment]
@hughsando that's #6420

**Comment by hughsando** [comment]
I have a feeling its exactly the same issue.

**Comment by nadako** [comment]
They are related but different. #6420 is about removing redundant `return`. While this `return` is not needed, it shouldn't break generation like described in this issue, because in Haxe we allow `return someExpr` from a void function, it's just translated to `someExpr; return;`, just not in this case with Dynamic.

**Comment by Simn** [comment]
This is another instance of the "Dynamic does not bind to monomorphs" problem, aka "I don't know how to fix this".

**Comment by hughsando** [comment]
We got rid of the return-void a few years ago, eg:
```haxe
class Test {
   public static function main():Void return ("x":Dynamic);
}
```
does not compile.  I'm pretty sure that returning a value from a void function could be a compile-time error.
I guess if you are talking about transforms that insert the return and then  remove it for simplicity, that would be different.
I can put the check back into hxcpp - but really it should be done for all the targets.

**Comment by RealyUniqueName** [comment]
This issue also affects non-anon functions:
```haxe
class Main {
	static function main() {
		f(parse);
	}

	static function f(cb:String->Void) cb('{hello:"world"}');

	static function parse(data:String) return haxe.Json.parse(data);
}
```
Emits a c++ compilation error:
```
Error: ./src/Main.cpp: In static member function ‘static void Main_obj::parse(String)’:
./src/Main.cpp:50:87: error: return-statement with a value, in function returning 'void' [-fpermissive]
 HXDLIN(   8)  return  ::haxe::format::JsonParser_obj::__alloc( HX_CTX ,data)->doParse();
```

**Comment by RealyUniqueName** [comment]
We have multiple options to deal with this:

*1.  Allow binding monomorph to Dynamic for function return type*
(Branch with implementation: https://github.com/RealyUniqueName/haxe/tree/bugfix/6503-void-return-dynamic)
* Allows to use arrow functions returning Dynamic and omit return type hints for normal functions when returning a dynamic value;
* But violates our "never bind monomorph to Dynamic" rule.

*2.  Emit a Haxe compilation error*
This would requre creating a new filter, which will look through the code for `->Void` functions with `return dynamicValue` expressions.
This would make impossible to use arrow functions in such situations, but that's probably not a big deal.

*3.  Rewrite `return dynamicValue` to `{ dynamicValue; return; }` in `->Void` functions*
This would requre creating a new filter too.

**Comment by hughsando** [comment]
IMO, the function should not be Void if you are actually returning something.  So either not Void, or don't return something.  Option 3 is going to solve the problem in the most efficient and expected way - and would be what I would effectively do from hxcpp gen if I really really had to.  Option 2 would be odd if you did something like 'trace(parse...)' and then converted it to 'parse...' and suddenly got an error.
