### ISSUE TITLE
Out of memory in runtime on windows

### ISSUE THREAD

**Issue by SergeyLabutin** [HaxeFoundation/haxe#6504]
I have problem with memory on build, haxelib use more 1G and crash with `out of memory` without other information. On mac and linux with 64bit i have not any problem.

1. How get information, stacktrace or any other method for find class and function where crach happens?
2. How get information where oom happens. In haxe or maybe hxcpp or other haxelib module?
3. I recompile hxcpp for 64 bit, but haxe and haxelib 32 bit, how make manual build for 64bit?

P.S. Sorry, i am new guy for haxe. Please, help me.

**Comment by nadako** [comment]
are you sure it's haxelib taking 1G+ memory, not haxe compiler itself? because we recently had a memory leak in the compiler that can crash with OOM errors. @RealyUniqueName can tell more about this

**Comment by RealyUniqueName** [comment]
Yes, we have similar problem with Haxe 3.4.2 and comiler server on windows. But in our case it's compiler fails with OOM, not haxelib. 
Recent changes to development version of Haxe fixed it.

**Comment by SergeyLabutin** [comment]
@nadako @RealyUniqueName Very big thanks! i try use last code from gitlab, and write about result here.

**Comment by back2dos** [comment]
I'm quite certain there's nothing in `haxelib path` that can allocate 1G of memory and that's the only thing that's called while building.

**Comment by SergeyLabutin** [comment]
@nadako @RealyUniqueName @back2dos Thanks.

I test more, yes haxe crached. Looks as working version is `2017-03-23 05:39:01 >> 4876859 >> haxe_2017-03-23_development_ada466c.tar.gz` [from here](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/)

P.S. I will test more 2-3 days on other my windows computers with different configurations, and close it ticket after success.

**Comment by SergeyLabutin** [comment]
Confirmed. With this version haxe use 1.4G but not crash.
