### ISSUE TITLE
Add any argument with haxe.macro.Compiler

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#6509]
I was wondering if I can use a macro function to specify the size of SWF output. There is the `-swf-header` option of course, but for my uses I would really prefer if it was specifiable from within a macro. I discovered that `haxe.macro.Compiler` only offers `define(flag, ?value)`, which is equivalent to `-D flag[=value]`. There are other functions `addNativeArg` and `addNativeLib`, but neither can accomplish this.

1. It would be nice if there was an `addArg(arg)` function, which would simply add `arg` verbatim to the compilation options.

(This is what one would do in AS3.0, but I'm not suggesting a @:swf-header metadata:

    [SWF(width="800", height="600", backgroundColor="#000000", frameRate="60")]
    public class Main extends Sprite {
      // ...

)

2. Another little thing I noticed was that `Compiler` has no way to overwrite what target should the code ultimately be compiled as (equivalent to specifying `-swf`, `-js`, `-cpp`, etc) … I don't see any reason to limit what `Compiler` can modify, especially while processing macros. As it is, it can modify the output directory, modify flags passed to the generator / native compiler, stop compilation with an error, etc.

**Comment by ncannasse** [comment]
Unless you provide a PR for this I don't think we will invest much time in SWF/Flash given its current state. Arguments processing affects several things that can't be safely modified mid-compilation
