### ISSUE TITLE
[Lua] Cast namespace is not getting flattened

### ISSUE THREAD

**Issue by gerardsmit** [HaxeFoundation/haxe#6511]
Since MR #6313 the namespaces are getting flattened, however doing a cast:

```haxe
import example.Class;

cast(VAR, Class);
```
results into
```lua
__lua_Boot.__cast(VAR, example.Class);
```

which is not flattened thus Lua complains:  `attempt to index global 'example' (a nil value)`

**Comment by gerardsmit** [comment]
In addition, the class in my project is an extern class. Maybe this causes the issue.

**Comment by gerardsmit** [comment]
Seems like this was a mistake from me, since I should of used `typedef` here.

Although, it seems still wrong that it's not getting flattened. Should I close this?

**Comment by jdonaldson** [comment]
Let me take a look, thanks

**Comment by jdonaldson** [comment]
Could you try this again on a new nightly?  I'm seeing the desired behavior per my local test:

```haxe
# Main.hx
import foo.Foo;
class Main {
    public static function main(): Void {
        var f  = new Foo();
        var k = cast  (f, Foo);
    }
}
```

```haxe
# foo/Foo.hx
package foo;
class Foo {
    var x : Int;
    public function new(){}
}
```
compiles to :

```lua
...
Main.main = function() 
  local f = __foo_Foo.new();
  local k = __lua_Boot.__cast(f , __foo_Foo);
end
...
```

**Comment by gerardsmit** [comment]
Like I said in my previous comment; it happens when the class is extern:

```haxe
package foo;

extern class Foo {
    var x : Int;
    public function new(){}
}
```

would compile to

```lua
Main.main = function() 
  local f = foo.Foo.new();
  local k = __lua_Boot.__cast(f , foo.Foo);
end
```

but I don't know if this is an issue; however foo is most likely not defined with the method `new`

**Comment by jdonaldson** [comment]
Ah, that's actually intended behavior then.  Some externs do have tables that behave like modules.  I'd rather leave it as-is.  In all likelihood you'll need to do some tweaking for extern path names with ``@:native``.
