### ISSUE TITLE
Template helper error

### ISSUE THREAD

**Issue by zaynyatyi** [HaxeFoundation/haxe#6522]
Using template helper from docs triggers runtime error

> Uncaught Error: Macro call display(function (){ return f.method.apply(f.scope, arguments); },[object Object],15) failed (TypeError: Cannot read property 'apply' of undefined)

Here is example

https://try.haxe.org/#AB662

My haxe version is 3.4.2

**Comment by zaynyatyi** [comment]
Error happens only with DCE full

**Comment by ibilon** [comment]
The display function isn't mentioned in the code and therefore dce will remove it.
You need to add the `@:keep` metadata to it to prevent dce from removing it.

**Comment by zaynyatyi** [comment]
yeah, totally forgot about that. thanks.
