### ISSUE TITLE
[flash] Cannot create Vector without knowing runtime type

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#6529]
The following code does not execute with Flash:

```haxe
class Container<V> {

    var buffer:haxe.ds.Vector<V>;

    public function new(size:Int) {
        buffer = new haxe.ds.Vector<V>(size);
    }
}

class Test {
    static function main() {
        trace(new Container<Int>(2));
    }
}
```

but throws a runtime error `Cannot create Vector without knowing runtime type`

Tested with Haxe 3.4.2, 4.0.0 nightly on Windows 10 (FlashPlayer24) and Linux Ubuntu 14.04 (FlashPlayer11)

**Comment by back2dos** [comment]
It works if you mark `Container` as `@:generic`. Without it, the code shouldn't compile.

**Comment by sebthom** [comment]
The example works on all other platforms except Flash.

**Comment by sebthom** [comment]
When wrapping an abstract around the Container class @:generic does not seem to help anymore:

```haxe
@:forward
abstract Container<V>(ContainerImpl<V>) {

    inline
    public function new(size:Int) {
        this = new ContainerImpl<V>(size);
    }
}

@:generic
class ContainerImpl<V> {
 
   var buffer:haxe.ds.Vector<V>;
 
   public function new(size:Int) {
        buffer = new haxe.ds.Vector<V>(size);
    }
}

class Test {
    static function main() {
        trace(new Container<Int>(2));
    }
}
```

**Comment by Simn** [comment]
This is a limitation of Flash itself and there is nothing we can do about it. Could maybe try to catch it at compile-time...

**Comment by sebthom** [comment]
It seems to work with Array<V>. Couldn't haxe internally fallback on using an array instead on flash?

**Comment by Simn** [comment]
No, that would lead to stupid things like `Std.is(vec, Vector)` being false and probably other problems.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
