### ISSUE TITLE
Precedence of `OpIn` changed from `EIn`

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#6531]
While fixing some [record-macros](https://github.com/HaxeFoundation/record-macros) issues with Haxe 4 I noticed that the order of precedence of the following expression has changed:

```haxe
var s = [ for (c in MySpodClass.manager.search( $anEnum == SecondValue || $theId in ids )) c.theId ];
```

Before, the search condition was equivalent to `($anEnum == SecondValue) || ($theId in ids)`.  Now, it is `($anEnum == SecondValue || $theId) in ids`.

Related: #6471, HaxeFoundation/record-macros#12

**Comment by frabbit** [comment]
Has that any effect on 

```haxe
for (x in 0...6)
````

or is for in special?

**Comment by nadako** [comment]
Somehow it's parsed correctly, probably because of https://github.com/HaxeFoundation/haxe/pull/6471#issuecomment-319611210
