### ISSUE TITLE
Small casting/optimization issue

### ISSUE THREAD

**Issue by iCore-ua** [HaxeFoundation/haxe#6534]
When exported to JS, this:
```
class Test 
{
    static function main()
    {
        var a:Float = Math.random();
        
        var b:Int = cast( a + 1 );
        trace( b );
        
        var c:Int = cast( a + 1, Int );
        trace( c );
    }
}
```

Will give this result:
```
1.149828834197749

uncaught exception: Error: Cannot cast 1.149828834197749 to { __name__ : [Int] },,line:0
```

Looks like due to some haxe optimization cast threats Float like if it was Int already.

This on try.haxe: https://try.haxe.org/#d2139

**Comment by Gama11** [comment]
It's generally not a good idea to use casts for `Float` -> `Int` conversion. Use [`Std.int()`](http://api.haxe.org/Std.html?#int) instead.

**Comment by Simn** [comment]
This should fail because a Float is not an Int.

**Comment by Gama11** [comment]
Note that there's actually a semantic difference between those two casts - they're _not_ merely different syntaxes for the same thing. [safe casts](https://haxe.org/manual/expression-cast-safe.html) carry a performance overhead. In return, they are specified to throw an exception if the cast fails (like in this case). As a rule of thumb - if you don't intend to catch the exception, use an [unsafe cast](https://haxe.org/manual/expression-cast-unsafe.html) instead.

**Comment by iCore-ua** [comment]
My bad, thought cast acts same way Int( ... ) in AS3 would do.
