### ISSUE TITLE
Int cast error ( js  and flash)

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#6535]
When tried the code bellow JS return error, flash give result. Which one is correct ?

**Example:**
```
class Test {
    static function main() {
        var t =  cast( 444.5, Int);
        trace("T = "+t);
    }
}
```

**Result:**

 _1) Javascript_ 
    Uncaught Error: Cannot cast 444.5 to { __name__ : [Int] }

 _2) Flash_ 
    444

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/haxe/issues/6534#issuecomment-324564777

**Comment by Simn** [comment]
The SWF generator specifically allows this for some reason. I wonder if it's worth breaking that at this point...

**Comment by flashultra** [comment]
I use Std.int , so to keep SWF generator as it work now is good for me.

**Comment by ncannasse** [comment]
static targets (not only flash) might allow these casts because they don't make a difference between (cast x : Int) and cast(x,Int), I wonder if we should change that or not.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
