### ISSUE TITLE
[SWF] ObjectMap&WeakMap key iteration on AS build

### ISSUE THREAD

**Issue by itouh2** [HaxeFoundation/haxe#6538]
ObjectMap key iteration failed on AS build

```
    public function testObjectMap():Void {
        var map = new ObjectMap<A,String>();
        map.set(new A(),"one");
        map.set(new A(),"two");
        var count:Int = 0;
        var iterator = map.keys();
        for( a in iterator){
            trace( iterator.hasNext() ); // iterator index is counted up.
            count++;
        }
        assertTrue(count == 2); // count == 1
    }

```

JS is OK
https://try.haxe.org/#5482F

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
