### ISSUE TITLE
[lua] Overwriting global Enum can interfere with hosted environment

### ISSUE THREAD

**Issue by lordio** [HaxeFoundation/haxe#6544]
I'm experimenting with using Haxe's Lua output to write a World of Warcraft addon, and I noticed that, using only my addon, waypoints no longer show up on maps.

I went poking through the generated Lua, and found a set of code that appears to set up classes used by the Haxe environment: 
`local _hxClasses = {}`
`Int = _hx_e();`
`Dynamic = _hx_e();`
`Float = _hx_e();`
`Bool = _hx_e();`
`Class = _hx_e();`
`Enum = _hx_e();`
(Generated from Haxe 4.0.0; 3.4.2 generated a more complex passage with the same effect.)

If I cut down the Lua code to just this section (replacing "_hx_e()" with a blank object "{}"), the effect remains, but if I mark Enum as a local, it resumes correct behavior.

It seems the game is using the global identifier Enum within the default UI code, and Haxe overwrites it, leading to errors.

Is anything lost by making the generated code set these classes locally rather than globally?

**Comment by jdonaldson** [comment]
I made a small patch for this here : https://github.com/HaxeFoundation/haxe/commit/31884f7bc7a6a70f7f4b4f49731692ff7c39caad

Unfortunately, lua has a 200 local variable limitation.  I've had to remove local declarations from namespaces that are highly likely to not conflict (e.g. flattened namespaces like __haxe_io_Output). 

I've gone through and added exceptions to top-level classes, these will be declared as local.  Give a nightly a shot and let me know if this works.

**Comment by lordio** [comment]
This does work, but your mention of the local variable limit made me wonder if one would run into the same problems making a (global?) __haxe object of which the boilerplate objects and functions are members? I understand it would be kind of an overhaul.

I also wonder if making the boilerplate subject to DCE might help somewhat? I tried setting it to full and it only removed sections of my own code that didn't appear to be called (they were, but that's not really relevant).

**Comment by jdonaldson** [comment]
I might add this as an option, sure.

**Comment by jdonaldson** [comment]
The other problem is that some game frameworks alias the global context as well... So, `_G` becomes `GLOBAL`.  I'm trying to get a better picture of how many variations like this there are in the wild.
