### ISSUE TITLE
EnumConstructor/ Switch Trouble in HAXE 3-4-2

### ISSUE THREAD

**Issue by hereticByte** [HaxeFoundation/haxe#6547]
Dear HAXE team,

I have just updated to HAXE 3-4-2. 

Regrattably some switches do not work anymore.

The problem is, that the variable nested within the enum constructor is not recognized as such if it has the same name like the constructor.

It can be observed here:
[https://try.haxe.org/#82A7F](url)

Thanks again, Dan Korostelev, for your reply.

It would be great, if it would be fixed, as it would be quite a heck to change the massive amount of switches I already have implemented.

Thank you in advance.

Kind regards
Arnijm

**Comment by Simn** [comment]
This is not a bug. Identifier resolution in patterns is now consistent with normal typing, so it is expected to be resolved like that. You will have to rename your variables.

**Comment by hereticByte** [comment]
Sorry, after Dan's reply I thaught there is a slim chance...
;-)
But it's ok this way.
