### ISSUE TITLE
Something is rotten in the grouping of extractors.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6548]
So [this](https://travis-ci.org/back2dos/dumpster/jobs/270763348#L599) gets reported for matching against `Type` with `case TInst(_.toString() == name => true, _)` after `case TInst(_.toString() == name => true, [v])` in [tink_macro](https://github.com/haxetink/tink_macro/blob/cc009b2026703749dc69ac2bb4a0da7c8ad4c0ee/src/tink/macro/BuildCache.hx#L118
): 

> Bool has no field constructor
> Bool has no field doc
> Bool has no field fields
> Bool has no field init
> ... (it goes on listing what other fields of `ClassType` are not defined on `Bool`)

As far as I can tell the culprit is e533c12c974c2cca39cbb65cfd67abea8497e4e8.

**Comment by Simn** [comment]
Oh man...

**Comment by Simn** [comment]
```haxe
class Main {
	static function obj(_) return { pos: 12 };

	static public function main() {
		switch 1 {
			case _ * 2 => 2:
			case _ * 2 => 3:
			case obj(_) => { pos: pos }:
			case _:
		}
	}
}
```

The problem itself is quite obvious in the debug output:

```
DECISION TREE BEGIN
_hx_tmp<636> = Main.obj(1); _hx_tmp<635> = 1 * 2; switch (_hx_tmp<635>) {
        case 2(unguarded) :
        case 3(unguarded) :
        default: switch (_hx_tmp<635>) {
                case { pos }(unguarded) : pos<634> = _hx_tmp<635>.pos;
                default:
        }
}
DECISION TREE END
```

It picks up the wrong extractor variable (635 instead of 636).
