### ISSUE TITLE
inline function returns assume singular type even if specified to return Either/Dynamic

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#6555]
**Description:** If an inline function has multiple return paths with multiple types, the compiler seems to assume that it can return only one type, raising an error for the other-typed return(s).
**Platform:** JS
**Sample:**
```haxe
class Test {
	static inline function test(z:Bool):Dynamic {
		if (z) {
			return [];
		} else return 0;
	}
	static function main() {
		var v:Dynamic = test(true);
		trace(v);
	}
}
```
**Output:**
```
src/Test.hx:8: characters 19-29 : Int should be Array<Dynamic>
```
**Workarounds:** Add a `cast` into the "questionable"-typed return.
**Additional info:** If you're wondering as to why would one do such a thing, original use case was having a function either populate a provided (pre-allocated) array with returned values and return the number of modified entries, or have it allocate a new (results-sized) array and return it instead.

**Comment by nadako** [comment]
Looks similar to #6406, are you sure this reproduces in latest development build?

**Comment by Simn** [comment]
It does...

**Comment by back2dos** [comment]
FWIW typing against `Any` "fixes" the problem \o/
