### ISSUE TITLE
Call Bytes.ofData change bytes  in the array

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#6556]
When call Bytes.ofData , I can't read correct bytes anymore. I expected to read 18, 28, TEST , but as result get 18, 7168  and error.  Method Bytes.ofString works correctly. 
I'm testing on flash target, but maybe problem occurs on other platforms too.
 
Example: ( [https://try.haxe.org/#0b19a](https://try.haxe.org/#0b19a) )
```
import flash.utils.ByteArray;
import haxe.crypto.Base64;
import haxe.io.Bytes;

class Test {
    static function main() {
        var bt:ByteArray = new ByteArray();
		bt.writeByte(18);
		bt.writeShort(28);
		bt.writeUTF("TEST");
		
		trace("B1: " + Base64.encode(Bytes.ofData(bt)));
		bt.position = 0;
		
		var r1:Int = bt.readByte(); 
		trace(r1);
		var r2:Int = bt.readShort();
		trace(r2);
		var r3:String = bt.readUTF();
		trace(r3);
    }
}
```

**Comment by Simn** [comment]
Bytes constructor has this:

```haxe
#if flash
b.endian = flash.utils.Endian.LITTLE_ENDIAN;
#end
```

We use the ByteArray object without making a copy, so the constructor ends up modifying its endianess.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
