### ISSUE TITLE
[display] diagnostics sometimes suggest changing calls to true / false / null

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6557]
If you have a `trace` call with a missing letter, you get a diagnostics suggestion to replace it with `true`:

```haxe
class Main {
	public static function main() {
		trce("Test");
	}
}
```

![](https://i.imgur.com/SttsPEK.png)

```
> haxe --display Main.hx@0@diagnostics
[{"file":"Main.hx","diagnostics":[{"kind":1,"severity":1,"range":{"start":{"line":2,"character":2},"end":{"line":2,"character":6}},"args":[{"kind":1,"name
":"true"}]}]}]
```

This is obviously a bit silly.. Could Haxe check whether the suggested replacement is valid in that position? Or in this particular case, whether the replacement is even callable?

**Comment by Simn** [comment]
I'm not sure if we should start going down that road... The next guy is gonna ask to only show identifiers which would type-check, and at some point we'll run into problems. I mean, why should we hide `true` here, but not some `trze` variable which resolves to a String? And supporting that would probably require quite a bit of work...

**Comment by Simn** [comment]
Still not sure about this one. Not urgent though.

**Comment by Simn** [comment]
The suggestions here now also actually include `trace`, which I find good enough. Anything else would be a bit too crazy.
