### ISSUE TITLE
Short match+extract syntax?

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#6563]
While updating a CustomJSGenerator based project to work with current nightly, I've noticed that an awful lot of code ends up looking like this:
```haxe
switch (mainExpr.def) {
	case SfCall(_, _.def => SfStaticField(_, _, field), []):
		// ...
		switch (field.classField.kind) {
			case FMethod(MethInline):
				mainExpr = field.expr;
				field.isHidden = true;
			default:
		}
	default:
}
```
so you have a single match pattern, some code that applies to properties extracted from it (with things like AST, going few layers deep as you unpack-check expressions and make sure to not read nullable ones), maybe an else-branch. Usual stuff.

For single-case expressions (e.g. matching if an AST branch is a good candidate for transformations) use of switch-blocks proves slightly redundant, however, as you end up with +4 lines / +2 indent levels per each unpacking "level", and the final code 

Therefore I'd like to ask if a more compact expression match+extract syntax exists or was considered, e.g. 
```haxe
if (mainExpr.def => SfCall(_, _.def => SfStaticField(_, _, field), [])) {
	// ...
	if (field.classField.kind => FMethod(MethInline)) {
		mainExpr = field.expr;
		field.isHidden = true;
	}
}
```
(operator choice strictly for example - I don't think it fits that well semantically)
where captured fields would be extracted into then-block much like they are for switch-cases.
# Existing workarounds
## match + getParameters
`EnumTools.match` provides functionality fairly akin to what is desired here, but does not offer expression extraction. `EnumTools.getParameters` can be used for that part, but is slightly less convenient for complex/nested expressions. The fact that getParameters emits a copy of parameters-array on each call also makes it unfit for larger-scale use cases.

## Refactoring
Ever-growing indentation level can be partially mitigated through reworking matcher structure, e.g.
```haxe
do {
	var field = switch (mainExpr.def) {
		case SfCall(_, _.def => SfStaticField(_, _, field), []): field;
		default: continue;
	};
	// ...
	switch (field.classField.kind) {
		case FMethod(MethInline):
		default: continue;
	};
	mainExpr = field.expr;
	field.isHidden = true;
} while (false);
```
unfortunately, while this takes care of indentation level, this amounts for even more lines of code.

Regardless, this is the approach that I currently take, causing readability of some functions to heavily rely on code folding.

## Macros
It is possible to write a few-line macro to get yourself a nice `ematch(expr, pattern, thenExpr, ?elseExpr)` function and be able to do
```haxe
ematch(mainExpr.def, SfCall(_, _.def => SfStaticField(_, _, field), []), {
	// ...
	ematch(field.classField.kind, FMethod(MethInline), {
		mainExpr = field.expr;
		field.isHidden = true;
	});
});
```
but - alas - nested macros are not a very good idea, particularly when executed in other macros (which is the case for CustomJSGenerator).

## Code style sacrifices

It is also possible to "save" indentation/lines by placing `case` onto `switch`'s line and `default:` on closing bracket's line, but that's... just not very good.

---
Subject of discussion.

**Comment by Simn** [comment]
This should already work:

```haxe
switch (mainExpr.def) {
	case SfCall(_, _.def => SfStaticField(_, _, field = { classField:{ kind: FMethod(MethInline) }}), []):
		mainExpr = field.expr;
		field.isHidden = true;
	default:
}
```

**Comment by kevinresol** [comment]
Looks exactly like my amazement here
https://twitter.com/kevinresol/status/905802008048820232

**Comment by back2dos** [comment]
Yeah, this is totally awesome and went by me entirely. There's so many cases I've written with wacky guards or extractors to achieve just that ^^

**Comment by YellowAfterlife** [comment]
@Simn I'm aware of that syntax for cases that permit it, I should have been a bit more clearer that "// ..." meant "other logic regarding **field** variable".

Use cases get a bit more complex - for example, to match a specific iterator for target-specific optimizations, you need to match AST being
```haxe
{
	var iter = someIter(...);
	while (iter.hasNext()) {
		var value = iter.next();
		// 0+ other statements
	}
}
```
which is done by matching it in multiple steps - first you match for `{ var v = vx; while (c) { ... }; }`, then you check that the variable is initialized (since AST contains `null` for value-parameter when it's just `var v`) and that the while-loop' body is not empty prior to matching on first expression and making sure that it's the same variables and right calls everywhere. Each step is a single-case match+extraction, but you get a pile of switch statements out of it.

**Comment by Simn** [comment]
This would have to go through https://github.com/HaxeFoundation/haxe-evolution

I'm not strictly against it, but it would require a syntax that's "just right" (which `=>` isn't).
