### ISSUE TITLE
Weird behaviour extending typedefs

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6572]
I find the following code a bit surprising, but am not sure if it's intended or not. 
I would expect the compiler to throw an exception when `sub` defines the `0k` field, but it's not the case.

Unofficial [try.haxe test](http://try-haxe.mrcdk.com/#9DE49).

```haxe
typedef BaseAnon = {
  real:Bool
}
  
typedef SubAnon = {
  > BaseAnon,
  name:String
}

class Test {
  static function main() {
    var sub:SubAnon = {
      real: true,
      name: "sub",
      //err: "compiler error",
      "0k": "weirdly works!",
    };
    
    trace(Std.string(sub));
  }
}
```

**Comment by Simn** [comment]
This is by design for fields that are not valid Haxe identifiers. It has nothing to do with extending structures either because it behaves the same for normal structures. I don't remember the reason for this design, but maybe @ncannasse does.

**Comment by azrafe7** [comment]
Thanks for the clarification Simon. 

Any plan to change this for haxe 4? @ncannasse, what does this involve, why it was chosen that way (just curious)?
