### ISSUE TITLE
Incompatible Nightly builds on win7x86

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6576]
Downloaded .exe cannot be run in win7x86..

```cmd
G: \>haxe
This version of G: \haxe. EXE is incompatible with the version of Windows that you are running. Check your computer's system information to see
Whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```

**Comment by Simn** [comment]
@andyli: I don't know how to solve this without running everything twice on AppVeyor. I'm also not sure if it's worth keeping 32bit builds around. What's your opinion?

**Comment by andyli** [comment]
I think it is still nice to keep providing 32-bit Windows binaries - because there are ppl asking for that.
The AppVeyor build time isn't too bad compared to Travis Mac... So I will just add a build and only test the eval target there.

**Comment by Simn** [comment]
In that case we'll need some build server adjustments from @waneck I think.

**Comment by andyli** [comment]
I've just added a 32-bit build in https://github.com/HaxeFoundation/haxe/commit/66df92eae7281a9b84ceade4d5ac8dbf74d6e3df
Haven't set up uploading to build.haxe.org yet.

**Comment by Simn** [comment]
I think this has been completed.
