### ISSUE TITLE
sys.db.ResultSet.getFieldsNames() don't work with SQLite

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#6577]
Hi. I noticed a little defect of method ResultSet.getFieldsNames() with SQlite. It always return "null" (but it works fine with MySQL).

This [sample for SQLite](https://github.com/r3d9u11/haxe-basics/blob/master/3_StdLibExtraFeatures/3.7_DataBase/3.7.2_SQLite/3.7.2.2_UsageSimpleData/Source/Main.hx#L45) will throw exception (because method will return "null").
But same [sample for MySQL](https://github.com/r3d9u11/haxe-basics/blob/master/3_StdLibExtraFeatures/3.7_DataBase/3.7.1_MySQL/3.7.1.2_UsageSimpleData/Source/Main.hx#L53) works fine.

Thanks.

**Comment by Simn** [comment]
The implementation probably explains that:

```haxe
	public function getFieldsNames() : Array<String> {
		return null;
	}
```

We have no capacity to work on this, but would accept a pull request. If you want to look into it, the relevant files are in std/[target]/_std/sys/db/Sqlite.hx.

**Comment by r3d9u11** [comment]
@Simn thanks for hint!
