### ISSUE TITLE
Haxe 3.4.3 for macOS is incompatible

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#6579]
Installed Haxe 3.4.3 official using the macOS package installer. At runtime, it triggers this error and exits:

```bash
dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/haxe
  Reason: image not found
```

I believe it would work if I used Homebrew (and had libpcre installed), but I do not. This is a normal, Homebrew-free macOS system. Thanks guys! :smile:

**Comment by andyli** [comment]
Would you check to see this new build is working for you or not?
http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/mac-installer/haxe_2017-09-16_three_four_three_7519399.tar.gz

**Comment by aliokan** [comment]
no more error message on my mac with this version. 
osx 10.12.5

**Comment by Simn** [comment]
Thanks Andy!

**Comment by jgranick** [comment]
Confirmed that it is working here, thanks for your help guys :smile:

**Comment by smorimoto** [comment]
Since the current version didn't seem to work, so we worked around this problem by providing our own solution with the haxe and neko plugins of asdf version manager.
https://github.com/asdf-community/asdf-haxe#troubleshooting

**Comment by smorimoto** [comment]
Also, if you're looking for a version manager for Haxe, this might be a good option.
