### ISSUE TITLE
haxe.CallStack.callStack(); crash on ie11

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#6580]
Hi,
On haxe 3.1.3 in HttpAsyncConnectionWithTraces.hx the call to haxe.CallStack.callstack(); crash on ie11 only (not chrome, fireforx, or edge)
it crashes on a.shift();
seems that 
a = getStack(e); returns undefined value.
In fact the issue is that the e argument passed to getStack (from catch) has no stack field in ie11 in some cases.

To fix it, it would require to safe test in getStack function if e has the "stack" field, and return [] if its not the case, like its done when e arg is null.

Thanks

**Comment by Simn** [comment]
Feel free to send a pull request as we don't have the capacity to deal with this at the moment.

**Comment by sebpatu** [comment]
i will try to give pull requets, but why closing a bug that is not fixed.
"we don't have the capacity to deal with this at the moment" is really ,not a good reason to close an issue
