### ISSUE TITLE
[java] Negative Float is Int in anonymous structures

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#6587]
```haxe
typedef Consts = { //does not affect
	friction:Float
}

class Main {
	static var consts:Consts = {
		friction: 0.5
	}
	
	public static function main() {
		if (0 == consts.friction) {} //0 != 0.5, correct
		if (0 == -consts.friction) {} //-consts.friction is Int
		trace(-consts.friction); //0
	}
}
```
In java code it looks like
`boolean tmp1 = (0 == (- (((int) (haxe.lang.Runtime.getField_f (haxe.root.Main.consts, "friction", true))))));`

**Comment by Simn** [comment]
There's indeed an int cast in the generated code:

```java
((double) (( - (((int) (haxe.lang.Runtime.getField_f(haxe.root.Main.consts, "friction", true)) )) )) )
```

@waneck: Any idea where that comes from?

**Comment by waneck** [comment]
I've looked into it and it doesn't come from the typed AST sent to java. My
guess is that the `unop -` is thought to exclusively act on ints, like the
bit operations. Should be a simple fix

2017-09-18 4:41 GMT-03:00 Simon Krajewski <notifications@github.com>:

**Comment by waneck** [comment]
It's probably this https://github.com/HaxeFoundation/haxe/blob/development/src/generators/gencommon/dynamicOperators.ml#L168 . I'll fix it tonight

**Comment by RblSb** [comment]
Thanks for fix @waneck!

**Comment by waneck** [comment]
Whoa, nice catch! I forgot to add `Closes` to the commit message, that issue would probably be forgotten otherwise
