### ISSUE TITLE
[request] final variables (const)

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#6590]
We need a way to declare non mutable variables.

I'm not qualified to describe all the semantics, but the goal is that `const` variables can not be re-assigned, which (I assume) would correspond to Java `final` or ECMAScript `const`. A `const` Array or object would not be immutable.

Haxe being openly inspired by ECMAScript it wouldn't hurt to follow what people are now used in ES6/TypeScript, that is using `const`.

```javascript
class Foo {
    const a:Int; // must be initialised in ctor, then is final
    const b = 'a const'; // variable is final and can be inlined
    static const c = 'also const'; // equivalent to 'static inline var'

    function new() {
        a = 42; 
        a = -1; // compiler error, already assigned
        const d = 123;
        d = 0; // compiler error
        const  e = [];
        e = ['no']; // compiler error
        e.push('yes'); // ok, only the Array reference is final
    }
}
```

**Comment by ibilon** [comment]
Is that the same idea as https://github.com/HaxeFoundation/haxe/issues/6584?

**Comment by Simn** [comment]
Yes

**Comment by mastef** [comment]
Watch out, you can't redeclare a `const` in js, but you can shadow a `final` in haxe/java.
