### ISSUE TITLE
Map comprehensions tied to toplevel `Map`

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6593]
[Minimal example](https://try.haxe.org/#b495e):

```haxe
import String in Map;
class Test {
    static function main() {
        var x = [for (i in 0...10) i => Std.string(i)];//String has no field set
    }
}
```

This is a bit silly of course, but there may be cases where you wish to define something like `openstreet.Map` and as soon as you import it, your comprehensions blow up. I therefore wonder if we could move `Map` into `haxe.ds` (and alias it from the toplevel) and let the compiler rely on the fully qualified name?

**Comment by Simn** [comment]
Makes sense to me

**Comment by ncannasse** [comment]
Don't agree. It shouldn't be affected by any local type. The same as
literal arrays, strings or numbers.

**Comment by Simn** [comment]
I think that means you agree...

**Comment by ncannasse** [comment]
Does it have to imply moving "Map" to haxe.ds ? This might break some macro
code when doing some follows.
Given we have Array at toplevel, I'm keen to keep Map as well as a proper
definition.
For the fix itself you can use ["std"],"Map" as the path.

**Comment by waneck** [comment]
What if someone has a variable called `std`? We should really support an unequivocal way to define type paths

**Comment by ncannasse** [comment]
Yes, I agree looks like a good change for Haxe 4

**Comment by Simn** [comment]
I don't know, feels pretty correct to have something like Map in haxe.ds, especially considering that all the actual implementations are there as well. I don't really have a strong opinion about this, so if you want to keep Map at toplevel that's fine with me too.

**Comment by back2dos** [comment]
@waneck has a good point in general, but because the generated code is actually `new std.Map()` the `std` variable wouldn't cause any conflict in this particular case.

**Comment by ncannasse** [comment]
I prefer that we keep Mapt at toplevel.

And yes we need to find a way to explicitly access to classes statics with absolute path without clashing with locals/etc. Or do we not need it?

**Comment by Simn** [comment]
As a user, you can cheat by using `import Map as RealMap`. What's really stupid though is that the compiler itself can't refer to toplevel Map if the type is shadowed. So yes, we do need something for this I think.

**Comment by Simn** [comment]
The original issue has been addressed and we talk about the `std` problem in some other issue that I can't find right now.
