### ISSUE TITLE
API to get line and columns numbers from `haxe.macro.Position`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6599]
I have to parse `Std.string(Context.currentPos())` pretty often to retreive line number and columns numbers.
It would be great to have an api like `Context.getPosInfos()` but with an additional field `lineNumber`

**Comment by RealyUniqueName** [comment]
I suggest something like `Context.getLineInfos()`

**Comment by Simn** [comment]
It should return `{ file: String, lineNumber: Int, columnNumber: Int}`

**Comment by RealyUniqueName** [comment]
`Std.string(Context.currentPos())` produces lines like `"#pos(Test.hx:9: characters 9-21)"`, so i think result should contain min and max column numbers.

**Comment by Simn** [comment]
Hmm, if we go down that road we actually need two line numbers as well...

**Comment by nadako** [comment]
it can also span into multiple lines, so maybe something like `getFilePos(file:String, pos:Int):{line:Int, col:Int}`?

**Comment by RealyUniqueName** [comment]
I think it's better to have full info with both line numbers and both column numbers. That might be useful in tasks, where you need to retreive all text in provided position.
Or maybe result can containt just line, column and amount of bytes/characters?

**Comment by Simn** [comment]
I'm inclined to use VS Code's structure for this:

```haxe
typedef Position = {
    var line:Int;
    var character:Int;
}

typedef Range = {
    var start:Position;
    var end:Position;
}

typedef Location = {
    var uri:DocumentUri;
    var range:Range;
}
```

Except uri would be a String.

**Comment by RealyUniqueName** [comment]
Looks a bit bloated )
Maybe stick to file,line,column and length?

**Comment by Simn** [comment]
Again, in the general case you have two lines and two columns. That's 4 values, plus the file name is 5, which is what above structure represents. Don't see how that is bloated...

**Comment by RealyUniqueName** [comment]
Start line, start column and lengh allows to calculate missing values.

**Comment by RealyUniqueName** [comment]
But i'm fine with VSCode solution too. Just suggesting.

**Comment by ibilon** [comment]
You need to load the source file to get the line's length though.

**Comment by Simn** [comment]
Yes, length doesn't help you unless you know where the line breaks are.

**Comment by RealyUniqueName** [comment]
You're right. Let's go for VSCode-like solution )

**Comment by nadako** [comment]
My suggestion was complementary to getPosInfos, so you first get the `min` and `max` and then translate it into `line/col` using a new function, but vscode-like structure seems to be better because it saves macro function calls and encoding/decoding which is always great!

**Comment by Simn** [comment]
I tested this for 20 seconds in total, so please test it. :)

**Comment by nadako** [comment]
I don't like the uri field, because its values aren't actual uris, but file paths. Maybe rename that to 'file'?

**Comment by Simn** [comment]
You're right, done!
