### ISSUE TITLE
Unbound variable reported instead of Cannot access this or other member field in variable initialization

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#6603]
Got the following error using 3.4.0:

Unbound variable, please report this
{
	v_id = 372;
	v_name = `this;
	v_type = Main;
	v_capture = false;
	v_extra = None;
	v_meta = [];
}
File "src/optimization/analyzerTypes.ml", line 221, characters 3-9: Assertion failed

Repro code:

```
class Main 
{
	var a = 4;
	var xx = new X().x(function() { return a; });
}
class X {
	public function new() {}
	public function x(v:Void->Int) { return 1; }
}

**Comment by Simn** [comment]
This has been fixed for 4.0 already. And yeah I could have pulled that on the bugfix branch, but I forgot about it. Oh well...
