### ISSUE TITLE
Why do we need package statements?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6607]
I've discussed this with Nicolas before I think, but I can't remember the reasoning. It feels like `package` statements are little more than a confirmation of the file path in relation to its class path. Why do we need them?

**Comment by aliokan** [comment]
That helps a lot, when auto-import in IDE is broken, a simple copy-past package does the job! ^^

**Comment by jdonaldson** [comment]
Shouldn't it help when defining package-level overrides and additions?  E.g. in a third party library or something.  Granted, I've never actually done that.

**Comment by ibilon** [comment]
Maybe for the horrible case of classpath overlapping?

**Comment by Justinfront** [comment]
It's useful when you open a single file in a basic editor to know which package your in, but really I agree I don't feel it's needed it's just an as3 influence that is not really needed in Haxe, I guess if your sharing code with gists or pastebins it can be useful.  I don't see how removing the package line from a haxe file will change any classpath overlap the complier will in effect be aware of the package.  I think people may want to keep it till they get used to not needing it, but you could always put it as a comment at the top.  I guess if you get stuff like cp wrong it maybe that the compiler can guess and give you a useful suggestion by checking sub folders but that should be feasible with class names alone.

**Comment by ibilon** [comment]
For overlapping I mean we have `-cp src -cp src/inside`
and the files `src/A.hx` with `package;` and `src/inside/B.hx` with `package;` too.

**Comment by jcward** [comment]
> Shouldn't it help when defining package-level overrides and additions? E.g. in a third party library or something. 

Overriding works fine, the last `-cp` wins, so you're still fine without package statements.

Nested classpaths (`-cp src -cp src/inside`) could be problematic, but that's just crazy project setup. :)

> I guess if your sharing code with gists or pastebins it can be useful.

> I guess if you get stuff like cp wrong it maybe that the compiler can guess and give you a useful suggestion

Those are good reasons to keep package statements. They're a name that gives code a sense of place, even when disconnected from a codebase.

**I'm fine if they simply become optional**. Their main uses seem not to be for the compiler, but for humans.

**Comment by ncannasse** [comment]
I think we could try to make them optional and see what kind of horrible
class paths issues people come up with. Should be a lot of fun.

**Comment by remcohuijser** [comment]
Just bumping this thread to see if there is any decision made on this yet.

I tried to see whether this could be auto generated or something in macros but I noticed that if you leave out the package definition in a module it actually has the pack and module correctly set. Still the compiler gives an "Invalid package: x.y should be <empty>" error.

**Comment by Simn** [comment]
I'm now using the `package` value for some completion stuff, so I no longer want to remove it.

**Comment by Aurel300** [comment]
Bump again – you say you're using it for completion, but is that the only way to do it? I would also be happy not to have it :)

If nothing else, the error messages generated when the package is specified wrong are really confusing, e.g.:

    Main.hx:3: characters 4-22 : Invalid package : test.pkg should be <empty>

Looks like an error in `Main.hx` when it is actually hidden in the file `test/pkg/Something.hx`, which is missing `package test.pkg`.

**Comment by ncannasse** [comment]
@Aurel300 please post a new issue for that

**Comment by Aurel300** [comment]
https://github.com/HaxeFoundation/haxe/issues/7460

I am still interested in why `package` is required though.
