### ISSUE TITLE
.hxml build configuration for whole directory

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxe#6617]
Hi,

It's suggestion or question: is there possible to build whole directory setting only once .hxml? I mean I have directory src where I have multiple files (main files ofc.) and I want to simple run 'haxe build.hxml' and magic should happen. If It's not possible I think this feature could be implemented.

**Comment by wiggin77** [comment]
That feature is documented here:  https://haxe.org/manual/macro-initialization.html
See "include macro" section on that page.

**Comment by Simn** [comment]
This doesn't make any sense to me. Having several main files is one thing, but you'll at the very last have to specify where they should be generated. It's also very likely that you need different compilation parameters for your projects anyway, so I really don't see the point of such a feature.

But yes, you can always use an init macro that scans your file system and spawns several haxe compilation process in any way you like.
