### ISSUE TITLE
Abstract: forward constructor of underlying type

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6619]
Is it possible to make this code work?

```haxe
class Test {
    static function main()
        var a = new A(1); // fails: sadly @:forward doesn't forward the constructor for now
}

class C {
    public function new(i:Int, b=true) {}
}

@:forward
abstract A(C) {}
```

I don't think `@:forward` should automatically forward the constructor. Maybe we need `@:forwardConstructor` or something.

**Comment by RealyUniqueName** [comment]
@simn, why is this moved to "Bugs" milestone? Should `@:forward` also forward the constructor?

**Comment by Simn** [comment]
We have to design `@:forward` somehow. I don't know if it's good to have 10 different metadata for this stuff...

**Comment by nanjizal** [comment]
Is that code really complete, what is the full intention,  for instance this works fine?
```haxe
class Test {
    @:access( C )
    static function main(){
        var a = new A(1);
        trace( a.i );
	}
}

class C {
    var i: Int;
    public function new(i:Int, b=true) { this.i = i; }
}
@:forward
abstract A(C) { 
public function new(i:Int ) { this = new C(i);  }
}
```
It seems like it's expecting too much and is not clear enough?
However I do believe the constructor should be possible to leave out, so this should work fine?
```haxe
class Test {
    @:access( C )
    static function main(){
        var a = new A(1);
        trace( a.i );
	}
}

class C {
    var i: Int;
    public function new(i:Int, b=true) { this.i = i; }
}
@:forward
abstract A(C) { 

}
```
A missing constructor in this case should be inherited not error?
// Test.hx:4: characters 16-24 : A does not have a constructor

**Comment by nanjizal** [comment]
'this' in abstracts of abstract is rather an unpredictable character and it's annoying the amount of this needed in abstracts compared to classes, not intending to go off topic it's all related to getting consistant and logical abstract behaviour, certainly I feel an abstract should have internal access to private var of parent which it doesn't at the moment.

**Comment by vonagam** [comment]
Use case when absence of a way to forward constructor complicates things - creation of abstract for an extern class to support operators when said class has constructor overloads. Example:

```hx
extern class PointData {
  @:overload(function(x: Int, y: Int): Void {})
  function new(coords: {x: Int, y: Int});
}

abstract Point(PointData) {
  // how to support new(1, 2) and new({x: 1, y: 2})?
  // here are operators overloads...
}
```
