### ISSUE TITLE
Type propagation issue in haxe/java

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/haxe#6626]
Hey Haxe Java Team <3

I stumbled on a type propagation issue on this :
https://github.com/HaxeFoundation/hscript/pull/68#issuecomment-333365255

It seems the duplicate<T>() stuff return type is badly inferred only in java.
Should be either the one inferred from T or the one inferred from the affected variables but here it was demoted to <Object>

I haven't toyed with haxe java yet so if you need a reproducible examples let me know.

Cheers.

**Comment by kevinresol** [comment]
Is this related? https://github.com/HaxeFoundation/haxe/issues/5953

**Comment by Simn** [comment]
The original PR unfortunately has conflicts, so I cannot check if it works.
