### ISSUE TITLE
[hl]  Assertion failed when using untyped

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6632]
I had this code somewhere:  
 > `(untyped __js__("console")).info(message);` 

I know this is shitty code and should not be written at all, but just wanted to mention I got this error:

 > `File "_build/src/generators/genhl.ml", line 2721, characters 2-8: Assertion failed`

Suggestion: The error reporting could be nicer or maybe point to the position on where it failed. I now put `return` statements of my project after each block/line until it didn't break anymore 😄 

I used Haxe 4.0.0 preview

**Comment by nadako** [comment]
I just made that an `Unbound identifier` error with proper position. @ncannasse might want to look into different way of handling these, but this is still better than `assert false`.
