### ISSUE TITLE
Add watcher to haxe compiler

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxe#6633]
Hi,

How about simple file watcher and compiler for Haxe CLI? It could get info about which file should watch from .hxml file.

**Comment by markknol** [comment]
You can do add this easily yourself.

Install from command line (assuming you have node/npm installed)
```
npm install -g fast-live-reload
```

If you want to compile on file change:
* Create a _dev-server.hxml_ `-cmd fast-live-reload -ns src/ -e "build.hxml"` 

If you want to build on file change + refresh website:
* create a _dev-server.hxml_ `-cmd fast-live-reload -s bin/website/ -sp 7000 src/ -e "haxe build.hxml"`

Run the hxml. It assumes your source is in `/src`/ 

This tool is very configurable for multiple type of projects, give it a go. More info: <https://github.com/bmustiata/fast-live-reload>
