### ISSUE TITLE
Feature Request: Support `object.toJSON` in `Json.stringify` by default

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#6636]
On the HTML5 target, calling `haxe.Json.stringify` calls `object.toJSON` in order to convert object instances to JSON, if that method is defined:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON()_behavior

Since this is how `haxe.Json` behaves on JavaScript, it seems like it would be sensible to handle this in the default `JsonPrinter` script for other targets as well, and making it a documented behavior.

This is important for helping us allow abstract types to convert to JSON properly

**Comment by Simn** [comment]
This would have to go through an haxe-evolution, but I don't think we have any plans to add more magic methods like that.
