### ISSUE TITLE
Forwarded fields lose information about abstract type.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6639]
```haxe
@:forward abstract NativeStructArray<T:{}>(T) from T {}
typedef AnonOptions = NativeStructArray<{hostt:String}>;

class Main {

    static var tmp:Dynamic;

    static function main() {
        var options:AnonOptions = {hostt:'example.com'};
        tmp = options;
        tmp = options.hostt; //see dump for this line below
}
```
-D dump=ast
```
<....>
[Field:String]
    [Local options(1206):AnonOptions]
    [FAnon:String] hostt
```
Add this to any generator:
```ocaml
match expr.eexpr with
    | TField (fexpr, FAnon ( { cf_name = "hostt" } )) ->        
        (match fexpr.etype with
            | TMono _ -> print_endline "TMono"
            | TEnum _ -> print_endline "TEnum"
            | TInst _ -> print_endline "TInst"
            | TType _ -> print_endline "TType"
            | TFun _ -> print_endline "TFun"
            | TAnon _ -> print_endline "TAnon"
            | TDynamic _ -> print_endline "TDynamic"
            | TAbstract _ -> print_endline "TAbstract"
            | TLazy f ->
                print_endline "TLazy";
                (match !f with
                    | LProcessing _ -> print_endline "LProcessing"
                    | LWait _ -> print_endline "LWait"
                    | LAvailable etype ->
                        print_endline "LAvailable";
                        (match etype with
                            | TMono _ -> print_endline "TMono"
                            | TEnum _ -> print_endline "TEnum"
                            | TInst _ -> print_endline "TInst"
                            | TType _ -> print_endline "TType"
                            | TFun _ -> print_endline "TFun"
                            | TAnon _ -> print_endline "TAnon"
                            | TDynamic _ -> print_endline "TDynamic"
                            | TAbstract _ -> print_endline "TAbstract"
                            | TLazy _ -> print_endline "TLazy"
                        )
                )
        )
    | _ -> ()
```
Expected output:
```
$ haxe build.hxml
TLazy
TAvailable
TAbstract
```
Current output:
```
$ haxe build.hxml
TLazy
TAvailable
TAnon
```
That means generator cannot recognize `NativeStructArray` behind `AnonOptions` in `options.hostt` expression.

**Comment by nadako** [comment]
As I mentioned, this is not related to `TLazy`, but field `@:forward`ing. When you access `@:forward`ed fields, the object is re-typed as the underlying type (see https://github.com/HaxeFoundation/haxe/blob/2ab958eb5f351e9695b9dafb90d84248e57af3cf/src/typing/typer.ml#L1536-L1537).

I see two ways of fixing this:

 * have a `FForwarded of tabstract * field_access` variant for `field_access` or something like that
 * generate `(cast obj : Underlying).field` expression that can be matched in the generator

**Comment by RealyUniqueName** [comment]
I think `FForwarded` is the proper way to go.

**Comment by Simn** [comment]
I don't really understand why you guys expect this to resolve to the abstract. The whole idea of `@:forward` is the pass through the abstract and use the underlying type.

**Comment by nadako** [comment]
> I don't really understand why you guys expect this to resolve to the abstract. The whole idea of @:forward is the pass through the abstract and use the underlying type.

I think it's certainly fine if `FInstance`/`FAnon`/etc. contains the underlying type information, but suddenly changing the type of an object expression (in case of TLocal also making it inconsistent with `v_type`) without introducing a cast sounds wrong to me.

**Comment by Simn** [comment]
I think this can happen with inlining too because it's a very similar situation. We can insert a cast, but then we might run into problems with `(a : T) = c` kind of stuff.

**Comment by nadako** [comment]
What about not touching types and adding casts and introduce `FForward of field_access` variant that would be used for forwarded `TField`s?

**Comment by Simn** [comment]
I don't see the point given that inlining already generates these casts. This would just introduce another special case you have to deal with.

**Comment by RealyUniqueName** [comment]
Here is my motivation:
PHP api utilizes a lot of associative arrays with limited set of well-documented sets of keys (e.g. http://php.net/manual/en/function.proc-get-status.php)
I want to add type safety to such arrays. My idea is to create an abstract which will fowrard all fields of an anon structure:
```haxe
@:forward
abstract NativeStructArray<T:{}>(T) {<...>}
```
And then in genphp i generate all field access to `NativeStructArray` as array access.
This approach will allow type checking, code completion and documentation hints. Otherwise it feels like coding php with Haxe syntax )
Unfortunately due to current issue i can't detect `NativeStructArray` in generator.

**Comment by back2dos** [comment]
Well, one way would be to use `@:enum abstract` based GADTs: https://try.haxe.org/#cdC7D

Another one might be something like:

```haxe
@:native("array")
extern class ProcGenStatus {
  var command(default, null):String;
  var pid(default, null):Int;
  // ...
}
```

Or you can use some explicit metadata (yay, more metadata \o/) or a marker interface or something.

**Comment by RealyUniqueName** [comment]
Ye, i'm trying to avoid unnecessary metas )
Your solution looks interesting, but not too convenient. I'd like std lib to be more "fluid".
Marker interface may be a way to go if this issue will be considered wontfix.
But `function procGetStatus():NativeStructArray<{pid:Int, command:String>` feels so much better.

**Comment by RealyUniqueName** [comment]
Can we have this for Haxe4?

**Comment by Simn** [comment]
This was fixed in https://github.com/HaxeFoundation/haxe/commit/9e7a820a587fb08d3ad385d4a329f80e3977c81e, the typed AST now has a cast:

```
[Field:String]
	[Cast:{ hostt : String }] [Local options(0):AnonOptions:AnonOptions]
	[FAnon:String] hostt:String
```
