### ISSUE TITLE
Int64Helper.parseString() accepting (under|over)flowing values

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6640]
I was fuzzy testing the function with random strings and I bumped into this.

This affects haxe both before and after https://github.com/HaxeFoundation/haxe/pull/5493.

To reproduce:
```haxe
import haxe.Int64;
import haxe.Int64Helper;

class Test {
  static public function main() {
    var minInt64Str = "-9223372036854775808";
    eq(minInt64Str, Int64Helper.parseString(minInt64Str)); // OK
    
    var maxInt64Str = "9223372036854775807";
    eq(maxInt64Str, Int64Helper.parseString(maxInt64Str)); // OK
    
    var invalidStr = "25820638775033977492";
    var i64:Int64 = Int64Helper.parseString(invalidStr);
    eq(invalidStr, Int64Helper.parseString(invalidStr)); // ERR
  }
  
  static public function eq(str:String, i64:Int64) {
    var i64Str = Std.string(i64);
    var values = ['str($str)', 'int64($i64Str)'];
    
    if (str != i64Str) {
      trace("[ERR]: " + values.join(" != "));
    } else {
      trace("[OK ]: " + values.join(" == "));
    }
  }
}
```

Looking into it, it seems that the problem _mainly_ presents when `multiplier` overflows (and flips to negative).

Some more invalid values that may be helpful to investigate the issue:
```
"-5518926151087227722779",
"18484280858095180538",
"-425386078818862309697",
"-576944185342198403634548",
"74817639777751565309",
```

**Comment by azrafe7** [comment]
I think I've found a simple way to fix it.
Testing is a bit more involved though. :stuck_out_tongue: 

(will try and make a PR if no one has started working on it)

**Comment by grepsuzette** [comment]
> I think I've found a simple way to fix it.
> Testing is a bit more involved though. stuck_out_tongue
> 
> (will try and make a PR if no one has started working on it)

@azrafe7 Interested in a fix here :)

**Comment by azrafe7** [comment]
Hey @emugel, the PR was rejected in the end, but you can still find it here (https://github.com/HaxeFoundation/haxe/pull/6644).

**Comment by grepsuzette** [comment]
Thanks :) 
Better to close the issue I guess.
