### ISSUE TITLE
Incorrect behavior of EReg.split in eval

### ISSUE THREAD

**Issue by shohei909** [HaxeFoundation/haxe#6641]
In Haxe 4.0.0.preview.1 (and nightly 0ecf104c0) eval target, EReg.split with parenthesises causes following behavior.

```haxe
class Test {
	static function main() {
		trace(~/b/.split("abc"));   // Test.hx:3: [a,c]
		trace(~/(b)/.split("abc")); // Test.hx:4: [a,b,c]
	}
}
```

I think `~/(b)/.split("abc")` should be `[a,c]`.

**Comment by nadako** [comment]
(maybe we should have `platform-eval` issue tag)

**Comment by Simn** [comment]
Huh, I'm calling PCRE split. I guess some argument is wrong there...

**Comment by Simn** [comment]
Did this work correctly in 3.4?

**Comment by shohei909** [comment]
Yes. In Haxe 3.4.2, `~/(b)/.split("abc")` returns `[a,c]`.
