### ISSUE TITLE
extern class with build macro: Function body required

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#6646]
Hello,

i have a simple class:

```
@:build(npm.test.TestBuild.build())
@:require(js) @:jsRequire("test") extern class Test {}
```

and in the macro i create a function field:

```
buildFields.push({
	name: 'test',
	access: [APublic, AInline],
	pos: Context.currentPos(),
	kind: FFun({
		args: [],
		expr: null,
		params: [],
		ret: macro :Void
	})
});
```

But the compiler want a function body: expr: null

how to fix that?

**Comment by ibilon** [comment]
If it's inline it needs a function body, the compiler error isn't wrong.
Alternatively if it's an extern function don't make it inline.

**Comment by malublu** [comment]
Oh .... 😭 my brain bug.
What a beginner's fault....

Sorry
