### ISSUE TITLE
something wrong with typedef&enum

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#6651]
Hi. Does it possible to use enum as type of field at typedef?
Main.hx:
```
package;

enum MyEnum {
	Type1,
	Type2,
	Type3
}

typedef MyType = {
	param1:String,
	param2:Int,
	param3:MyEnum
}

class Main {
    static function main() {
        var cfg:MyEnum = {
        	param1: "qwe",
        	param2: 123,
        	param3: MyEnum.Type1
        }
    }
}
```
will return compilation error: `Source/Main.hx:4: characters 1-6 : Missing ;`
what I'm doing wrong?

Haxe 3.4.0
Linux Mint 18.2 x64

Thanks.

**Comment by Simn** [comment]
Enum syntax uses `;` instead of `,`, as the error message tells you.

**Comment by r3d9u11** [comment]
@Simn Sorry, my bad %)
Thanks.
