### ISSUE TITLE
How to terminate/kill child process?

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/haxe#6653]
Hi. I have some troubles: child processes don't close until exe-application not be closed.
```
package;

import sys.io.Process;

class Main {
	static function main () {
		var dfp = new Process("df", ["-h", "/"]);
		//trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp = null;
		
		dfp = new Process("df", ["-h", "/"]);
		//trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp = null;
		
		dfp = new Process("df", ["-h", "/"]);
		//trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp = null;
		
		trace("processes 'df' will alive until key not be pressed and application not be closed");
		Sys.getChar(true);
	}
}
```
3 processes 'df' displayed in htop o_O
![htop](https://user-images.githubusercontent.com/15020827/31339778-a848c04c-ad0c-11e7-9e0e-3584e45d6bc3.png)

Somebody have ideas, what I'm doing wrong?

Haxe 3.4.3
Linux Mint 18.2 x64
Target: hxcpp (3.4.188)

Thanks.

**Comment by r3d9u11** [comment]
I think that these issues are related: https://github.com/HaxeFoundation/haxe/issues/5929

**Comment by R3D9477** [comment]
wow...
```haxe
var dfp = new Process("df", ["-h", "/"]);
dfp.kill();
```
Exception:
`Error : Not implemented`

I think needed some temporary workaround :(

**Comment by r3d9u11** [comment]
Also processes created by haxe-application can't be killed simply by command `kill -9 <pid>` O_o

**Comment by R3D9477** [comment]
This works for me (process df will be closed):

```haxe
package;

import sys.io.Process;

class Main {
	static function main () {
		var dfp = new Process("df", ["-h", "/"]);
		trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp.exitCode();

		dfp = new Process("df", ["-h", "/"]);
		trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp.exitCode();

		dfp = new Process("df", ["-h", "/"]);
		trace(dfp.stdout.readAll().toString());
		
		dfp.close();
		dfp.exitCode();

		trace("processes 'df' will alive until key not be pressed and application not be closed");
		Sys.getChar(true);
	}
}
```

The process will be closed when I call both methods `.exitCode()` and `.close()`.
Is it defect of sys.io.Process?

**Comment by r3d9u11** [comment]
hope it will be improved in future...
