### ISSUE TITLE
[Haxe 4 Preview 2] Generic build is not called for `Dynamic->Void` type

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#6657]
This is a change/regression since Haxe 3.2 and Haxe 3.4

When using `Dynamic->Void` as a type parameter for a generic build class, the build macro is not being called. As a result, our subsequent code fails to run.

We have a macro that defines classes for each type parameter combination, to make the number of parameters and types strictly typed.

```haxe
var event = new Event<Dynamic->Void> ();
event.add (function (value) { trace (Std.string (value)); }
event.dispatch ("hello");
```

Non-dynamic function types (such as `Int->Void`) still call the build macro

**Comment by Simn** [comment]
Please provide a reproducible example.

**Comment by jgranick** [comment]
Sorry, false alarm. I thought that I had two unrelated errors, but the first issues (#6656) appears to have been breaking our macro in the `Dynamic->Void` case.

The result was an error, "Unknown<0> cannot be constructed", but no traces were available inside the build macro, which was a bit confusing
