### ISSUE TITLE
Haxe 64-bit performance

### ISSUE THREAD

**Issue by jozefchutka** [HaxeFoundation/haxe#6658]
Hi, I wonder if there is any benefit of using 64-bit haxe (3.4.4) compiler for javascript projects on windows. Quickly testing my project 32-bit version compiles in 11sec, while 64-bit compiler takes 14sec. Shouldnt it compile faster?

**Comment by andyli** [comment]
It's not Haxe specific, you may try google "64-bit vs 32-bit performance".

Short answer: Unless you use 4GB+ memory, 64-bit programs are actually usually slightly slower.
