### ISSUE TITLE
[js] `haxe.StackItem.FilePos` is not enough to locate a place in js code

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6662]
`FilePos` constructor of `StackItem` enum does not contain column number. But without column locating position in uglified js file is really hard.

**Comment by ncannasse** [comment]
Please submit a PR with optional Column range and corresponding changes to
haxe.Callstack for JS target.

**Comment by RealyUniqueName** [comment]
Have you seen this PR? https://github.com/HaxeFoundation/haxe/pull/6665

**Comment by Simn** [comment]
We should check on which targets we can support it.

**Comment by RealyUniqueName** [comment]
PHP doesn't support column numbers.
Quick search gave me following results:
C# - no
Python - no
Java - no
C++ - no
Flash - no
Lua - no

@ncannasse neko, hl?

**Comment by ncannasse** [comment]
There's not runtime column information in neko or hl

**Comment by RealyUniqueName** [comment]
Let's assume there are no more targets with columns in call stack.
