### ISSUE TITLE
haxe.macro.Expr.QuoteStatus

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6668]
As we agreed (I think) in #6627 it probably does not make sense to distinguish single quotes from double quotes on the `haxe.macro.Expr` level, which is supposed to be _abstract_ syntax tree, so maybe we should get rid of `QuoteStatus` and change `ObjectField.quotes:QuoteStatus` to `ObjectField.quoted:Bool` or something.

**Comment by Simn** [comment]
I think having that enum is fine, even if it only has two options. It's more explicit and can be extended in case we want to.

**Comment by nadako** [comment]
Alright. Still I think we should rename variants here to `Quoted`/`Unquoted` or something.

**Comment by Simn** [comment]
Yes that makes sense. `Quoted` is good because that still leaves the option to add `SingleQuoted` later if we change out minds.
