### ISSUE TITLE
Regression - enum cannot be called

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6675]
The following used to work but breaks with latest Haxe:

```haxe

enum E {
	Int( v : Int );
	Add( a : E, b : E );
}

class Test {

	static function op( op : E ) {
	}

	static function main() {
		inline function foo(bop,a,b) {
			return op(bop(a,b));
		}
		foo(Add,Int(0),Int(1));
	}
	
}
```

**Comment by Simn** [comment]
When you say "used to work", how long ago are we talking? (I don't disagree it should work, just trying to understand when this was broken)

**Comment by ncannasse** [comment]
I am not sure when was my last haxe git build, a few days ago not much more, I guess you can easily bisect it.

**Comment by ncannasse** [comment]
MMh there's a lot of issues with inline functions...

**Comment by Simn** [comment]
This issue isn't about inline functions though

**Comment by ncannasse** [comment]
I'm getting other errors since updating today...
Can't reproduce yet but it goes like this:

```haxe

class Test {

	var x(get,never) : Float;
	var y(get,never) : Float;
	var curPos = { x : 0, y : 0, z : 0 };
	
	inline function get_x() return curPos.x;
	inline function get_y() return curPos.y; // error { x : Float } has no field y

	static function main() {
	}
	
}
```

**Comment by ncannasse** [comment]
it disappear if I explicitly type `curPos`

**Comment by ncannasse** [comment]
Opened a separate issue here https://github.com/HaxeFoundation/haxe/issues/6676
