### ISSUE TITLE
Regression - wrong typing order

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6676]
inline function being typed before the member variable initializer.

The following example showcase the problem but does not reproduce it
```haxe
class Test {

	var x(get,never) : Float;
	var y(get,never) : Float;
	var curPos = { x : 0, y : 0, z : 0 };
	
	inline function get_x() return curPos.x;
	inline function get_y() return curPos.y; // error { x : Float } has no field y

	static function main() {
	}
	
}
```

Reproducing can be done when trying to compile `h3d.scene.CameraController` in Heaps/GIT

**Comment by Simn** [comment]
That probably comes from https://github.com/HaxeFoundation/haxe/commit/1c9d096745de9edc910ce9b64d8f875bd079c6f9

Looks like I still didn't get it right...

**Comment by Simn** [comment]
See if that helped.

**Comment by RealyUniqueName** [comment]
If it does, don't forget to cherrypick it to 3.4_bugfix, because 1c9d096745de9edc910ce9b64d8f875bd079c6f9 is there already.

**Comment by ncannasse** [comment]
It did work, leaving it open until you confirmed it's been cherrypicked

**Comment by Simn** [comment]
The cherrypicking has been confirmed!
