### ISSUE TITLE
Regression - Array comprehension

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6677]
The following example prints `Array<A>` while it should be `Array<B>`

```haxe
class A {
}

class B extends A {
}


class Test {


	static function main() {
		var arr = new Array<A>();
		var ab = [for( x in arr ) cast(x,B)];
		$type(ab);
	}
	
}
```

**Comment by nadako** [comment]
That says 'Array<B>` for me.

**Comment by Simn** [comment]
I'm seeing `Array<B>`

**Comment by ncannasse** [comment]
No worry, maybe because I went a bit too back in the history, will reopen if reproducible again.

**Comment by RealyUniqueName** [comment]
@nadako You're probably looking at try-haxe.mrcdk.com where angle brackets are not properly escaped and <B> is interpreted as html tag.
