### ISSUE TITLE
Abstract Type parameters are invariant

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#6684]
```haxe
class Parent {
    public var int:Int;
    public function new() {}
}
class Child1 extends Parent {
}
@:forward(int)
abstract Abstract<T>(T) {
    public function new(t:T) { this = t; }
}
class Main {
    public static function main() {
        var a:Abstract<Parent> = new Abstract(new Child1());
        trace(a.int);
    }
}
```
Main.hx:3: characters 8-60 : Abstract<Child1> should be Abstract<Parent>
Main.hx:3: characters 8-60 : Type parameters are invariant
Main.hx:3: characters 8-60 : Child1 should be Parent

**Comment by Simn** [comment]
That should fail, because type parameters are in fact invariant.

**Comment by Ilir-Liburn** [comment]
I don't get it. At https://haxe.org/manual/type-system-variance.html there is a typedef (structural subtyping) used as a guard against invariance. Isn't @:forward used for that in case of abstract types? So that we could say: "There is no field defined on Abstract which could be used to add incompatible types, it is thus said to be covariant".
