### ISSUE TITLE
Imprecise error message

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6686]
The following code:

```haxe
typedef User = haxe.io.Bytes;

typedef NetworkApi = {
	private function onConnectionRequest( u : User ) : Bool;
	private function onConnectionError( u : User, status : {} ) : Void;
	private function onData( u : User, data : haxe.io.Bytes ) : Void;
}

class Test {

	static function foo( n : NetworkApi ) {
	}


	static function main() {
		foo({ 
			onData : function(user, data) trace(user, data),
			onConnectionRequest : function(user) { trace(user); return true; },
			onConnectionError : function(err) trace(err),		
		});
	}

}
```

Produces the following error message:

```
Test.hx:16: lines 16-20 : err : Unknown<0> -> Void should be u : User -> status : { } -> Void
Test.hx:16: lines 16-20 : For function argument 'n'
``` 

It uses to specify which field of the TAnonymous had invalid type, now it doesn't anymore.

**Comment by nadako** [comment]
> It uses to specify which field of the TAnonymous had invalid type, now it doesn't anymore.

It's the same on 3.2.1 (http://try-haxe.mrcdk.com/#130Ef), so I wonder when was it broken.

**Comment by Simn** [comment]
Is this really necessary if the position points at the correct expression? I would like to rely more on positions in general when it comes to (error) messages.

**Comment by ncannasse** [comment]
Yes I think in this case since we can know that only one expression is invalid among all the fields we should point at the correct one.

**Comment by ncannasse** [comment]
Note: in case there are several invalid expressions (wrong object type passed) it would be better to point at the whole expression as we do now.

**Comment by Simn** [comment]
This now points out the expression which causes the problem:

![Code_MHycABiPgY](https://user-images.githubusercontent.com/634365/83901213-ae37a900-a75a-11ea-9013-b40c0c1c3360.png)
