### ISSUE TITLE
Win binary 3.4.2 zip file corrupted

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6688]
The 3.4.2 window zip files cannot be unzipped, I think it is corrupted: 
https://haxe.org/download/file/3.4.2/haxe-3.4.2-win.zip/

**Comment by andyli** [comment]
Umm... indeed. Interestingly there was no one noticed.
I will just take the build from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/haxe_2017-03-20_master_890f8c7.tar.gz and rezip and replace the broken one.
The new zip's sha256sum is `02683fe91f781fdf73872dc562ad2be575e95b1eb7af9918ba76ed48b1de055f`.

**Comment by andyli** [comment]
Done.
