### ISSUE TITLE
Missing "should be declared override" check

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6699]
Don't have a reproducible example yet, but there's some regression since preview.2 that is skipping the "should be declared 'override'" check.

**Comment by ncannasse** [comment]
Confirmed, I just got a similar report from one of my developers

```haxe

class A {
	function foo() {
	}
}

class B extends A {
	function foo() {
	}
}

class Test {

	static function main() {
	}

}
```
