### ISSUE TITLE
Operator Overloading and extern class

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxe#6701]
Hi, here's my code:

```haxe
abstract Vector2(Vector2Base) from Vector2Base to Vector2Base {
  
  public inline function new(x: Float, y: Float) {
    this = new Vector2Base(x, y);
  }

  @:op(A + B)
  public function __add(rhs: Vector2): Vector2 {
    var __add = untyped getmetatable(this).__add;
    return __add(this, rhs);
  }
}

extern class Vector2Base {
  var x: Float;
  var y: Float;

  @:native('create')
  public function new (x: Float, y: Float);
}
```

Problem is that when I use:
```haxe
var v = new Vector2(x, y);
trace(v.x);
```

I got an error
```
Vector2 has no field x
```

I need those mathematical operators and also I need all those functions and fields from base class. Please help.

**Comment by nadako** [comment]
This is not related to operator overloading, the type has no field because you neither define it, not forward it from the underlying type. Try adding `@:forward` metadata to your abstract. See https://haxe.org/manual/types-abstract-forward.html
