### ISSUE TITLE
Inline regression

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6706]
The following seems to be a regression, since it doesn't "uplift" the value to a Dynamic, leading to compilation errors, for instance in HL:  can't compare f64 an bool.

```haxe

class Main  {

	static inline function foo( d : Dynamic ) {
		return d == true;
	}

	static function bar(v:Float) {
		return foo(v);
	}
	
	static function main() {
		trace(bar(1.5));
	}

}
```

**Comment by ncannasse** [comment]
FYI @pperidont

**Comment by Simn** [comment]
I don't think it's a regression. 3.4 also gives me this dump:

```
		[Block:Dynamic]
			[Return:Dynamic]
				[Binop:Bool]
					[Local v(506):Float]
					==
					[Const:Bool] true
```

Should still be fixed.

**Comment by ncannasse** [comment]
Actually it could safely be optimized out with a "false" result
