### ISSUE TITLE
Allow var ?x : Int

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6707]
I propose we should allow the following for Haxe 4:

`typedef T = { var ?x : Int; }`

Which would be the same as doing (currently): 

`typedef T = { @:optional var x : Int; }`

Edit: the ? must be next to the variable name

**Comment by nadako** [comment]
I proposed similar thing in https://github.com/HaxeFoundation/haxe/issues/6615#issuecomment-332866069 (see second part), and I'm still not sure where the `?` should be:

```
{ var ?x:Int; } // your example
{ var? x:Int; } // the same from the parser perspective, a matter of code style
{ ?var x:Int; } // alternative
```

**Comment by ncannasse** [comment]
If you're not sure then keep my version because I don't like other alternatives :)

**Comment by ncannasse** [comment]
and actually, `?` being a token, you can write it `var? x : T` or `var ?x : T` or `var ? x : T`, I don't think we enforce the no-space for short syntax either.

**Comment by ncannasse** [comment]
Thinking about again, I would prefer we enforce the no-space for both short and long syntax in the form I proposed. I agree this prevents alternate syntax as nadako requested, but it makes the language syntax less user-specific, which I think is a good goal to keep in mind.

**Comment by Simn** [comment]
> Does haxe have any space enforced rules?

You can't do `"foo". charAt(0)`
