### ISSUE TITLE
Export Lua standalone function

### ISSUE THREAD

**Issue by pawel-miczka** [HaxeFoundation/haxe#6709]
Hi,

I have problem. Framework I am using dont allow use require function so if I want to use function or variable from other source file I can normally use it by calling it via his name. I want to export some of Haxe function to "normal" function declaration without any return table (like using @:expose). Is this possible?

**Comment by jdonaldson** [comment]
before loading your haxe generated code, do something like this in your loading script.

```lua
_hx_exports = _G
```

In your haxe code, use @:expose to selectively export the functions you're interested in.  They'll be exported directly to the global namespace.
