### ISSUE TITLE
[eval] Type.enumEq

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6710]
is wrong

**Comment by Simn** [comment]
Test fails on python

**Comment by Simn** [comment]
I have disabled the test because it seems to be a more general problem:

```haxe
class Main {
	static function main() {
		var a = [];
		var b = [];
		trace(eq(a, b)); // true
	}

	static function eq<T>(t1:T, t2:T) {
		return t1 == t2;
	}
}
```

No idea how this isn't covered in our tests...

**Comment by ncannasse** [comment]
Wow, yes we need a unit test, and platforms fixes. Does [1] == [1] as well or is it just the empty Array having some kind of specific treatment ?

**Comment by nadako** [comment]
Yes, in python `==` is almost always overriden to be the structural equality check. For the identity check we have to generate `is`, although I'm not sure what other problems will this bring :)
