### ISSUE TITLE
[lua] sys.net.Socket is not implemented

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6712]
7c6b4688862bd709a7061e4314318a4109c4578b

**Comment by jdonaldson** [comment]
Fixed in : https://github.com/HaxeFoundation/haxe/commit/0f1633503d9e856763602354278ca4b5075616e7

**Comment by jdonaldson** [comment]
err... maybe not.

**Comment by bendmorris** [comment]
Maybe not...?

**Comment by jdonaldson** [comment]
This should do it : https://github.com/HaxeFoundation/haxe/commit/3dba4725e54edd83ab519c8ef052356b23f0f3ff
