### ISSUE TITLE
Support scheme

### ISSUE THREAD

**Issue by zaoqi** [HaxeFoundation/haxe#6716]
There is my scheme compiler
https://github.com/zaoqi/zscheme

**Comment by SlavaRa** [comment]
```Racket/R7RS Sources to Souces Compiler that is implemented in 71 languages.```
Maybe
```Racket/R7RS Sources to Sources Compiler that is implemented in 71 languages.```
? :)

**Comment by zaoqi** [comment]
@Simn ?
