### ISSUE TITLE
Instance method access in binop is typed as `FInstance` instead of `FClosure`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6719]
```haxe
class Test {
  function test() {}
  function new() {}
  
  static function main() {
    var t = new Test();
    trace(t.test == t.test); //this is typed as `FInstance(...) == FInstance(...)`
  }
}
```
http://try-haxe.mrcdk.com/#A1044
In 3.4.4 it is correctly typed as `FClosure`. But in latest dev it becomes `FInstance`.
The same issue with `FStatic`.

**Comment by abeaumont** [comment]
Does this still happen? I haven't been unable to reproduce it with current development branch.
A `dump=record` shows the following, which I think it's the expected thing:

```
[Binop:Bool]
	[Field:Void -> Void]
		[Local t(15):Test]
		[FClosure:Void -> Void]
			Test
			test
	==
	[Field:Void -> Void]
		[Local t(15):Test]
		[FClosure:Void -> Void]
			Test
			test
```

**Comment by nadako** [comment]
Same here, ping @RealyUniqueName

**Comment by RealyUniqueName** [comment]
Yep, seems fixed in latest dev
