### ISSUE TITLE
[PHP] missing parentheses in generated output of switch case

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#6720]
Isolated from a bigger sample, so it's a bit convoluted.

```haxe
    var x = "test";
    var a:Int = 0;
    var b:Int = 1;
    
    var xor = switch (x) {
      case "test":
        (a != 0) != (b != 0);
      default:
        true;
    }
```

generates this php code:
```php
  $x = "test";
  $a = 0;
  $b = 1;
  $xor = ($x === "test" ? $a !== 0 !== ($b !== 0) : true);
```

which results in `Parse error: syntax error, unexpected '!==' (T_IS_NOT_IDENTICAL)`.

**Comment by RealyUniqueName** [comment]
Which haxe version? 
Do you compile with `-D php7`?

**Comment by azrafe7** [comment]
haxe 4.0.0 (git build development @ c76e38aec)

Yes, compiled `-D php7`.

**Comment by RealyUniqueName** [comment]
@Simn that `(a != 0) != (b != 0)` comes to generator without the first parens:
```
[Binop:Bool]
	[Local a(1208):Int]
	!=
	[Const:Int] 0
!=
[Parenthesis:Bool]
	[Binop:Bool]
		[Local b(1209):Int]
		!=
		[Const:Int] 0
```
Is it a bug in analyzer?

**Comment by Simn** [comment]
Try adding `@:analyzer(full_debug)` to the function and check stdout. It tells you how the expression arrives at the analyzer (in `<initial>`), so we can tell if it's an analyzer problem or comes from another part of the compiler.

**Comment by RealyUniqueName** [comment]
Oh, i guess it's fine for normal languages to have expressions like `a != b != c` because all binops have the same prescedence. Looks perfectly valid. But not for PHP interpreter.

**Comment by azrafe7** [comment]
That was fast... thanks! :+1:
