### ISSUE TITLE
-cmd no longer pipe output to the console ASAP

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#6726]
Consider the command `haxe -cmd "echo ok && sleep 3"`.

In Haxe 3.4.4, it will print "ok" and then block for 3 seconds.

In current development (db5a1e4ddd2899befaaa5535124c518e581255d0), it will block for 3 seconds then print "ok".

It is annoying when running a long process with `-cmd`.

**Comment by kevinresol** [comment]
Any chance this is a quick fix?

**Comment by sayore** [comment]
this is still problem :lab_coat:

**Comment by RealyUniqueName** [comment]
Related issue: #4669
