### ISSUE TITLE
[flash features] Can add flash.Syntax just like the js.Syntax？

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6727]
I have seen this syntax in js and php, it seem to make the untyped underlying methods into be pure.

Because I have a lib that relies heavily on `__vmem_set__` and `__vmem_get__`.

**Comment by Simn** [comment]
We would probably accept a PR for this, but don't have the capacity to work on this ourselves. So I might as well close this issue.

Note that flash.Syntax would be a bit strange for a bytecode target. This should probably be on some other class.
