### ISSUE TITLE
Compiler allows / ignores consecutive return statements?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6729]
I was surprised to find this typo in our codebase today, and more surprised that the compiler accepts it:

```
function foo() {
  var bar = "something";
  return return bar;
}
```

In fact, any number of `return` statements works: https://try.haxe.org/#5ff56

The far RHS values is indeed returned, so it's not a critical issue.

I assume what's happening is that `return` is passing the RHS value to the left (like a setter)... But allowing this specific syntax (given that you should only ever hit one return statement in a function) gives me the heebie jeebies.

Is this an intentional or accidental feature?

**Comment by nadako** [comment]
This is a consequence of "everything-is-expression" feature described here https://code.haxe.org/category/principles/everything-is-an-expression.html (there's a paragraph about `throw`/`continue`/`return` expressions).

In particular cases like this, when it comes from the actual syntax, it would be indeed nice to have a warning/error. But this expression could be formed as a result of macros/inlining and Haxe currently can't tell them apart.

**Comment by jcward** [comment]
Fair enough. Given that there's even a paragraph about `return` expressions, I suppose it should be perfectly expected. Closing.
