### ISSUE TITLE
Completion fails in some cases

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6740]
This is a case where the compiler will not be able to correctly infer the type:

```
class A {
	function new(v:Array<String>) {
	}
}
	
class Main extends A {

	function new(v) {
		super(v);
		v.|
	}

	static function main() {
		new Main();
	}
	
}
```

This might be because the completion optimizer removes the super that is otherwise necessary to infer the correct type of `v`.

**Comment by nadako** [comment]
https://github.com/HaxeFoundation/haxe/issues/6020
