### ISSUE TITLE
[js] some source map issue at function end

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6741]
when stepping through functions in a debugger, at the end of a function it jumps to the generated code, which is a bit annoying:

![](https://i.imgur.com/5RF1HVb.gif)

**Comment by RealyUniqueName** [comment]
Not reproducible with the latest Haxe anymore.
I suppose it was fixed by some pos-related commit.

**Comment by nadako** [comment]
Hmm, I probably found some other issue while fixing this one, so I didn't close the ticket, however I didn't report it here and I don't remember it anymore, so yeah, this should be closed :)
