### ISSUE TITLE
[display] @type on abstract method leaks `this` argument

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6756]
The `this` argument here seems like an implementation detail that shouldn't surface to the user:

![](https://i.imgur.com/8adL1mk.png)

```haxe
class Main {
    public static function main() {}
}

abstract Result(String) {
    function foo() {}
}
```

```xml
> haxe --display Main.hx@98@type
<type p="main.hx:6: characters 14-17">
this : String -&gt; Void
</type>
```

Similar to #5631, although `this` doesn't appear in field completion this time.

**Comment by nadako** [comment]
Looks like a missing `prepare_using_field`, but I'm not sure where exactly should it be added here.
