### ISSUE TITLE
Haxe silently infers Dynamic

### ISSUE THREAD

**Issue by ousado** [HaxeFoundation/haxe#6757]
```haxe
import haxe.ds.Option;

class Test {
  static function which(v:Int) return 
    v > 1 ? Some("abc") : Some(true);
  
  static function main() {
    var r = which(1);
    $type(r); // Option<Dynamic>
    trace(r);
  }
}
```
Observed behavior: silently infers Dynamic, no error. 
Expected behavior: Appropriate error message.

**Comment by nadako** [comment]
It seems to be intentionally added in 41c80ba1d325fd6598f09c97d108f4298dc653b9, but I have no idea why. Reverting the change doesn't break any sense and make the code above fail with a proper error message, so I think I'll just do that.
