### ISSUE TITLE
Conditional compilation in compiler flags that are invalid identifiers.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6758]
I was wondering if there's a way we could make this work.

Currently *some* libraries [add extra variables by hand](https://github.com/fponticelli/thx.core/blob/master/extraParams.hxml#L1), but that seams a little tedious.

Options:

1. `haxelib path` should normalize non-ident variables somehow, e.g. replace any invalid char by `_` or something. If we go this way, then I suppose a slightly more intricate normalization might be in order.
2. the compiler actually performs that normalization for a vars, i.e. `-D foo.bar` always winds up as `foo_bar` being set.
3. we allow referring to such variables somehow. Anything I could come up with looks a little ASCII-arty.

**Comment by ncannasse** [comment]
2 has already been implemented in the compiler for some time now, dashes
are replaced by underscores so -D a-b also defines a_b

**Comment by back2dos** [comment]
Can we do the same for dots then?

**Comment by EricBishton** [comment]
Dashes being replaced by underscores makes some sense because the parser always sees it as subtraction in code (you can never use the dashed version in the code -- only on the command line or in the project files).  However, it's obvious that the dash-separated name should be a normal string value.  

Doing the same for dots is not so obvious, because values are allowed to be floats (and multiple dots are ignored, so that 1.2.1 becomes 1.21 for comparison purposes).  Non-numeric characters are interpreted as 0 so that comparisons like "my_ver > 2.0" (where -D my_ver=2.1.1.rc.1) continue to work.  That said, it seems we could allow for an automatic substitution of a dot on the left-hand side of the equals sign, or if one does not exist.

**Comment by RealyUniqueName** [comment]
> we allow referring to such variables somehow. Anything I could come up with looks a little ASCII-arty.

I thinkg `Compiler.getDefine()` is enough for such a task: https://github.com/HaxeFoundation/haxe/blob/3.4.4/std/haxe/macro/Compiler.hx#L46
Or did you mean something different?

**Comment by back2dos** [comment]
@EricBishton I'm talking about variable *names*, not values, so I think we agree here.

@RealyUniqueName How does `Compiler.getDefine()` help me with conditional compilation? And sure, one could use a `--macro` to normalize by hand, but it may run too late.

**Comment by kevinresol** [comment]
Check this out: https://stackoverflow.com/questions/47171908/haxe-defines-with-dot

**Comment by back2dos** [comment]
@kevinresol Yeah, I thought of something like that, but as said above, it may run too late.

**Comment by kevinresol** [comment]
Oh, I quoted the post for people who don't understand the problem. I didn't accept any of the answers in SO anyway.

My 2cents here is to have a generic replacement for various special characters into underscores. Especially those allowed as haxe library name, the dot `.` for example.

**Comment by EricBishton** [comment]
@back2dos We are talking about the same thing: the name _can_ be normalized, but the value can't.  

That said, it's haxelib (or lix, in your case?) that creates the dotted library definition in the first place: https://github.com/HaxeFoundation/haxelib/blob/development/src/haxelib/client/Main.hx#L1343
and it doesn't have to.  It can just as easily (and probably ought to) create a definition that is acceptable to the compiler.

The compiler normalizes the name/key here: https://github.com/HaxeFoundation/haxe/blob/development/src/core/define.ml#L266

**Comment by kevinresol** [comment]
Any chance we can actually support dots in a define, just like meta already does so (https://github.com/HaxeFoundation/haxe/issues/3959)?

so that one can write this:

```haxe
#if foo.bar

#end
```

While this is a breaking change, I doubt how much code will actually be affected.

**Comment by Gama11** [comment]
I guess this is solved with https://github.com/HaxeFoundation/haxe/pull/8005 and https://github.com/HaxeFoundation/haxe/issues/8032?

**Comment by RealyUniqueName** [comment]
Indeed
