### ISSUE TITLE
(HL) Error when checking nullable 

### ISSUE THREAD

**Issue by pperidont** [HaxeFoundation/haxe#6760]
The following example no longer works as expected since commit 6fa1600abe0c4d45099c3e69748085b2aed91cac

```haxe
class Main  {
	static function main() {
		trace( test(1) == 1 ); // true expected
	}

	static function test(a:UInt, ?b:UInt) {
		return b == null ? a : b;
	}
}
```

**Comment by ncannasse** [comment]
This is a Haxe abstract bug issue, not a HL one.

`trace(b)` in test produces the following AST:

```[Cast:Float] [Cast:UInt] [Cast:Int] [Cast:Int] [Cast:Int] [Local b(3686):Null<UInt>]``` 

Which leads to converting `b` from `null` to `0` before the check is performed.
Using `Int` as optional parameter does not exhibit this behavior.

**Comment by ncannasse** [comment]
PS: you might want to biject haxe compiler before https://github.com/HaxeFoundation/haxe/commit/6fa1600abe0c4d45099c3e69748085b2aed91cac to see if that's a recent regression or not

**Comment by ncannasse** [comment]
PPS: before this rev, Hashlink was here allowing comparison of `null` and `i32` which is not sound and should not have made past the checker. It was working in 32 bits because 0 == NULL at runtime.
