### ISSUE TITLE
Wrong function typedefs type inference

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/haxe#6764]
This isn't compiling even on latest build.
```haxe
typedef Func1<T,R> = T-> R;
class Test {
    static function main() {
        var map:Map<String, Func1<Void, ParentClass>> = [
          "item1" => ChildClass1.new, 
          "item2" => function() { return new ChildClass2(); },
          "item3" => function():ParentClass { return new ChildClass2(); }
        ];
    }
}

    
class ParentClass {
    public function new() {
        
    }
}

class ChildClass1 extends ParentClass { 
	public function new() { 
		super(); 
	}
}

class ChildClass2 extends ParentClass { 
	public function new() { 
		super(); 
	}
}
```

If we change map declaration to 
```haxe 
Map<String, Void->ParentClass>
``` 
that is definitely the same as previous - it'll be successfully compiled.

**Comment by nadako** [comment]
Same on 3.4.4 https://try.haxe.org/#09a53, probably a missing `follow` somewhere.

**Comment by nadako** [comment]
Oh wait, this is not a bug, actually, this is a `Void` behaviour, the same will reproduce with `Map<String, (Void)->ParentClass>` instead of typedef - this is a different function type indeed, so it complains. Hopefully the new function type syntax will help with this kind of surprising behaviour.

**Comment by mayakwd** [comment]
Ehm, "surprising behavior" is a bug in my opinion. There should be no place for ambiguous `Void` behavior in programming...

**Comment by RealyUniqueName** [comment]
I don't see how the new syntax will allow to specify `()->R` with such a typedef?

**Comment by nadako** [comment]
Well yeah, the whole `Void->Void`/`(Void)->Void` situation is confusing and wasn't designed greatly from the start.

**Comment by nadako** [comment]
> I don't see how the new syntax will allow to specify ()->R with such a typedef?

It won't and it shouldn't, these are function types with different argument count.

**Comment by RealyUniqueName** [comment]
So you can't use `Void` with aliased function types.
I think, it's a "design bug", which should be fixed somehow.

**Comment by nadako** [comment]
> So you can't use Void with aliased function types.

I'm not sure what are you talking about? You can, but it'll end up being `(Void)->Void` which is not something you want.

You can't change the number of function arguments using a typedef, and this is not a bug.

What could be called a "design bug" is the confusion `Void->T` special case in function parsing, which was kind of fixed by the new function type syntax.

**Comment by RealyUniqueName** [comment]
Thanks, now i understood.

**Comment by mayakwd** [comment]
Eh, thanks.
