### ISSUE TITLE
jQuery error messages are excessive / counter-productive (perhaps a more general problem)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6765]
**Given:** A core value of a typed language like Haxe is good compiler error messages that help the programmer quickly identify mistakes.

A simple typo in the JQuery helper function results in 32 lines of useless "overload resolution failed" error messages before simply pointing out: `Unknown identifier : my_typo`

I don't know technically whether there's a general way the complier could improve these situations (or whether they occur for other popular libs/externs), or if the JQuery macro / extern definitions themselves are to blame, but both are (currently) in this repo.

**Thought:** Would an undefined check in the macro [here](https://github.com/HaxeFoundation/haxe/blob/development/std/js/jquery/Helper.hx#L6), before the return statement, head off all these overload resolution errors (presumably from the extern)?

<hr>

Here's a sample: https://try.haxe.org/#c0a5c

```haxe
import js.jquery.Helper.J;
import js.Browser.*;

class Test {
    static function main() {
        trace("Haxe is great!");
        var my_div = document.createElement('div');
        
        // A simple typo results in 35 lines of confusing error
        // message, burying the error: Unknown identifier : my_typo
        J(my_typo).css('color','#fff');
    }
}
```

Spotting the relevant error message is harder than finding a needle in a haystack:

![selection_999 1523](https://user-images.githubusercontent.com/2192439/33460286-aeeef1d0-d5ea-11e7-999e-f79d209bdd9b.png)

**Comment by jcward** [comment]
Interesting, simply trying to type the incoming expressions does, indeed, cause the compiler to fail with a nice, single error message. But will this have any other unexpected consequences?

```haxe
	macro public static function J(exprs:Array<haxe.macro.Expr>) {
		for (e in exprs) haxe.macro.Context.typeof(e);
		return macro new js.jquery.JQuery($a{exprs});
	}
```

Error message simply becomes:

```
Test.hx:11: characters 10-17 : Unknown identifier : my_typo
```

**Comment by nadako** [comment]
A reduced example would be:

```haxe
extern class J {
	@:overload(function(s:String):Void {})
	public function new():Void;
}

class Main {
	static function main() {
		new J(my_typo);
	}
}
```

So there's no help applying a hack to a macro, the compiler should simply filter out overload resolution errors when there's `Unknown_ident` or similar error.

**Comment by jcward** [comment]
Awesome, thanks @nadako, I had a hunch perhaps there was a more general fix. :+1:
