### ISSUE TITLE
Error running openfl setup for first time on MacOS: Uncaught exception - Could not find NekoAPI interface.

### ISSUE THREAD

**Issue by tomcam** [HaxeFoundation/haxe#6766]
Installing on a 2015 Macbook with 150 GB free and 8 GB RAM. Running MacOS Sierra, aka v 10.12.6, per instructions at https://haxe.org/download.

Installing openfl went fine:
$ haxelib install openfl

But running this command yields in the error message "Uncaught exception - Could not find NekoAPI interface:"
$ haxelib -notimeout run openfl setup

What should I do at this point?

**Comment by EricBishton** [comment]
It's been a year since I've installed Haxe on my MacBook, but I think I had to install Neko from it's web site: http://nekovm.org.

**Comment by ncannasse** [comment]
Please report to OpenFL, this is not an haxelib message but something specific to the openfl run command.
