### ISSUE TITLE
Give proper position for errors in case of non-hx files 

### ISSUE THREAD

**Issue by grosmar** [HaxeFoundation/haxe#6767]
When using non-hx files and macro reports error in them then it always points to the first line with long character number, instead of the proper line. In long files it can be really frustrating to debug 

According to @back2dos reply [here](https://github.com/haxetink/tink_hxx/issues/8), I would like to ask you to look into this problem.

If you need further details or example let me know.

**Comment by ncannasse** [comment]
Could we get a minimal reproducible example of the issue?

**Comment by Simn** [comment]
Closing until follow-up.
