### ISSUE TITLE
Confusing final field initialization error message

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6772]
```haxe
class Main {
    public static function main() {
        new Main();
    }

    final i:Int = 0;

    function new() {}
}
```

This fails to compile with:

>source/Main.hx:6: characters 5-21 : final field i must be initialized immediately or in the constructor

This is confusing, as the field _is_ initialized immediately. Moving the initialization into the constructor fixes it. Bug, or just a misleading error message?

**Comment by markknol** [comment]
I think that is a bug, which Haxe version is this?

**Comment by Gama11** [comment]
Latest dev (37f6b2a9b).

**Comment by nadako** [comment]
Looks like some typing/build order issue

**Comment by abeaumont** [comment]
Yes, it's a typing order issue, if typing goes with the final before the constructor it's fine, but otherwise, it's not. My guess is that it's related to having final variables create a constructor with the assignment instead of having initialization in the class field entry, but not sure where that's done and if it's intended.

**Comment by ncannasse** [comment]
I think the order of the fields is not relevant here, it's the order of the typing that creates this issue, see for instance:

```haxe
class Main {

	static function main() {
		new A();
	}
}


class A {

	public final i = 0;
	public function new() {
	}
	
}
```

**Comment by abeaumont** [comment]
It's a typing order issue, but the typing order is not completely independent of the order of the fields, some field ordering causing the final variable being typed before the constructor and some causing it to be typed after. What would be a better approach to solve this (and the related double initialization issue)?
