### ISSUE TITLE
doc entry for ModuleCheckPolicy is empty

### ISSUE THREAD

**Issue by mastef** [HaxeFoundation/haxe#6774]
[setModuleCheckPolicy](https://api.haxe.org/haxe/macro/CompilationServer.html?#setModuleCheckPolicy) requires the second param to be of type `Array<ModuleCheckPolicy>`, but the options are not referenced [in the linked doc entry](https://api.haxe.org/haxe/macro/ModuleCheckPolicy.html).

Maybe they're not extracted properly from [the source](https://github.com/HaxeFoundation/haxe/blob/3.4.4/std/haxe/macro/CompilationServer.hx)? It's correctly explained [in other docs](http://docs.w3cub.com/haxe/haxe/macro/modulecheckpolicy/).

**Comment by nadako** [comment]
@markknol could be a dox bug?

**Comment by markknol** [comment]
I think this is fixed with https://github.com/HaxeFoundation/dox/commit/db226f889cdb0ea2f2e1eb3e1b253d2cb6b9731a 
(It's not live because this dox version with this fix released)

**Comment by Gama11** [comment]
Hm, looks like dox is a submodule of api.haxe.org, somebody should update that: https://github.com/HaxeFoundation/api.haxe.org/tree/master/libs

**Comment by markknol** [comment]
Done
