### ISSUE TITLE
[display] signature completion for array access

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6775]
Array access should support signature completion similar to function calls (showing possible overloads for abstracts too), e.g. `myArray[|` should show `index:Int -> T` signature or something.

**Comment by Simn** [comment]
My main concern with this is that it might get in the way of normal signature completion if you have something like an array access in a call argument.

**Comment by Simn** [comment]
Any opinion on this @Gama11?

**Comment by Gama11** [comment]
I would like to see this too (and even signature help for type params #7030). In what way do you think it'd get in the way?

**Comment by Simn** [comment]
I was thinking that it might be confusing to get array signature on something like `call(arg1, arg2, myArray[elt1, el|t2])`. But now that I actually type the example out I'm not sure if that's confusing.
