### ISSUE TITLE
[HL] Haxe 3.4.4. Infinite loop

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#6777]
Please check https://github.com/HaxeFoundation/haxe/blob/development/std/sys/Http.hx#L357

**Comment by ousado** [comment]
Which target?

**Comment by SlavaRa** [comment]
sorry, HashLink

**Comment by ncannasse** [comment]
Please detail more exactly the exact problem and how to reproduce it

**Comment by ncannasse** [comment]
Closed by 19f27d0202e3ad11ce44057bcb4f365db7822c9b

**Comment by RealyUniqueName** [comment]
Shouldn't we also add a test for this case?

**Comment by ncannasse** [comment]
It's quite hard because it requires a server socket closing the connection.
That goes under all these Sys tests that we should be doing
