### ISSUE TITLE
@:privateAccess completion

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6779]
Completion should display private members when you use `@:privateAccess myGame.|`

I use haxe 3.4.2 but don't seem to get completion on it.

> **haxe-dev:**
> nadako ¯\\_(ツ)_/¯
> mark.knol oh well :slightly_smiling_face:
> nadako report it :)

here you go!

**Comment by nadako** [comment]
```haxe
class Some {
	static function f() {}
}

class Main {
	static function main() {
		@:privateAccess Some.|
	}
}
```
