### ISSUE TITLE
Flash target - protected getters and setters

### ISSUE THREAD

**Issue by naviator** [HaxeFoundation/haxe#6781]
The following code should create a protected getter:

```
private var foo(get, never):Int;
@:getter(foo)
private function get_foo():Int {
    return 0;
}

private var bar:Int;
```

However the produced *.swc file is a little different:

```
native public function get foo():int;
native protected var bar:int;
```

The same result was with setters. The swf-protected flag was used.

**Comment by markknol** [comment]
Hi! You can compile with `-D swf-protected`. 

According [Haxe Manual](https://haxe.org/manual/compiler-usage-flags.html): 
> _swf-protected:_ Compile Haxe private as protected in the SWF instead of public

Let me know if this helps!

**Comment by markknol** [comment]
Ill close the issue for now.

**Comment by naviator** [comment]
As I mentioned in my original post, the swf-protected flag was used.

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
