### ISSUE TITLE
Invalid base character index in haxe.display.Position

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6782]
Despite doc says it's zero-based, it looks like it's actually 1-based.
Doc: https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/display/Position.hx#L36
Demo (see `range.start.character` in "Compiler output" tab): http://try-haxe.mrcdk.com/#a539b

**Comment by ncannasse** [comment]
Yes, this is a change in Haxe 4.0+

**Comment by RealyUniqueName** [comment]
Comments on [commit](https://github.com/HaxeFoundation/haxe/commit/2c4df243d39738422c247168eea498b2e1ca818d#commitcomment-26734459)

> Hmm, this isn't right, it should be consistent...

so maybe we should `-1` on ocaml side instead?

**Comment by Simn** [comment]
I'm not really sure what this is about. IIRC, columns have always been zero-based and the only thing we changed was the printing.
