### ISSUE TITLE
unify toplevel + field completion output format and provide EDisplayToplevel

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6786]
Imagine we have a macro function `get`, that parses the given path expression and generates some code based on it.

Now when we do `get(|` and invoke toplevel completion, we would like to get some completion specific to this function. This could be implemented if there was some `EDisplayToplevel` node inserted which could then be processed by the `get` macro and transformed into e.g. `EDisplay` that returns some field completion instead.

This would require unification of the toplevel and field completion output format which makes sense anyway.

Also we might want to think about providing some macro-control for completion, so one could return custom completion directly from a macro.

**Comment by Simn** [comment]
Completion and toplevel are unified now. Not sure what else we want to do here.

**Comment by nadako** [comment]
Don't close this for now, I'll check out what changed when I get some time and comment more on this :)

**Comment by nadako** [comment]
Alright, the unfication of completion is now done, awesome!

Regarding the toplevel completion AST node for macros and whatnot - this would be a completely separate issue to discuss, let's not bother with it for now.
