### ISSUE TITLE
Std.parseInt(0) throw error

### ISSUE THREAD

**Issue by ukt** [HaxeFoundation/haxe#6788]
Uncaught TypeError: s.charCodeAt is not a function

Example https://try.haxe.org/#35C39

**Comment by Gama11** [comment]
This is not particularly surprising - `value` is already an `Int`, not a `String`, so it can't be parsed.

**Comment by nadako** [comment]
Yeah, with Dynamic you're on your own

**Comment by ukt** [comment]
:(
i got this from closed framework.
i can't fix it.
for my mind, fix for that's is very simple;
just check on int;

**Comment by Justinfront** [comment]
Gleb you can use Std.string( value ) it's more tolerant, you will notice it's use is suggested in StringBuf add method, and it seems to work fine
https://api.haxe.org/Std.html#string
https://try.haxe.org/#CcC97
