### ISSUE TITLE
Incoherence with Std.parseInt and Std.parseFloat

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/haxe#6789]
The following code run differently depending on the target and sometimes yields incorrect values.

```haxe
class Test {
    static function main() {
        trace(Std.parseInt("1e2"));
        
        trace(Std.parseFloat("1e2"));
        trace(Std.parseFloat("1e2.5"));
        
        trace(Std.parseInt("32foo"));
        trace(Std.parseInt("-32foo"));
        
        trace(Std.parseFloat("-32foo"));
        trace(Std.parseFloat("32foo"));
    }
}
```
https://try.haxe.org/#C9cf9

| | cpp/neko/js/lua  | python | java |
| ------------- | ------------- | ------------- | ------------- |
|`Std.parseInt("1e2")` | 1  | 100  | 1 |
|`Std.parseFloat("1e2")` | 100  | 100  | 100 |
|`Std.parseFloat("1e2.5")` | 100 | 1 | NaN | 
|`Std.parseInt("32foo")` | 32 | 32 | 32 |
|`Std.parseInt("-32foo")` | -32 | None | -32 |
|`Std.parseFloat("-32foo")` | -32 | nan | -32 |
|`Std.parseFloat("32foo")` | 32 | 32 | 32 |

Parsing "e" as `Int` seems to only work only in python, while in the other tested target it default to ignoring trailing character (as specified in the doc).

Parsing expression with a float exponent yield varying results depending on the target but all seems incorrect.

Python fail to parse int/float with trailing character if it is not composed only of digits and at most a dot.

**Comment by Simn** [comment]
There was a discussion a while back where Nicolas said that the parsing functions are only consistent for valid input. I don't necessarily agree, but that's our policy.
