### ISSUE TITLE
Haxe(?) does not maintain float precision (Json.stringify probably)

### ISSUE THREAD

**Issue by kevansevans** [HaxeFoundation/haxe#6791]
I am currently working on an open source game clone aimed to be backwards and forwards compatible with the original game. The game uses 4 float values to define a "line" the user makes in game, an x1, y1, x2, y2, and they need to be their exact values, and the smallest difference renders whatever the user made broken, even if it's as small as 0.00000000001. The issue I am running into is whenever I call any of these float values, they get rounded from the second decimal place. For example, 40.0499999999 will become 40.05 when called, I absolutely can not have this. I originally thought this was Json.stringify ruining the variables (I originally noticed this issue when i started adding code to save games), as original saves from the main game would go from this:

"x1": 1127.55,
"y1": 427.75,
"x2": 1198.25,
"y2": 357.04999999999995, 

To This:

"x1": 1127.55,
"y1": 427.75,
 "x2": 1198.25,
"y2": 357.05,

To double check that it was or wasn't json.stringify, I had my game trace out every important value in memory, and it's definitely rounding them off https://pastebin.com/iXmZzw8W

So this confuses me, as when my program reads these values from Json.parse, they come in correctly, as the game functions as expected. But as soon as I do anything else with the values afterwards, they lose the precision I need for them to function correctly.

EDIT: I even went as far as checking the values of the data being loaded from the .json, and it even reported those as wrong, despite the save working as expected after the values get put through. https://pastebin.com/AxmudWA3

EDIT 2: For easy code, I wrote an openFL project here https://github.com/kevansevans/lrjson_comparitor to compare two saves. included is a windows executable set up to read the two very specific saves. The saves are before and after, and you can even see the float rounding in the trace logs when it catches something that doesn't sync up. https://pastebin.com/jdaujmVS

**Comment by back2dos** [comment]
Haxe certainly doesn't round anything, as you can see here: https://try.haxe.org/#92B65. Floating point arithmetics come from the runtime, which *might* do some rounding. I'm only speculating here, but what I suspect is though that it's rather the Float -> String comparison that decides to *display* `357.04999999999995` as `375.05` (which is arguably a sensible default for the vast majority of cases). Please check if `y2 != 375.0` and `y2 == 357.04999999999995`. If so, the string conversion is the culprit. In either case this seems more like an openfl (or perhaps hxcpp?) issue to me.

**Comment by kevansevans** [comment]
Okay, so then the trace statements are only rounding and the numbers are correct in memory. This just puts the problem back into Json.stringify, because the saves are coming out incorrectly. This was reproduced by another user on the HaxeFlixel discord, he made a reader/writer from hand and encountered the same issues.

**Comment by Justinfront** [comment]
http://try-haxe.mrcdk.com/#9DdFd

**Comment by shalmu** [comment]
It's runtime. Hardware floating point numbers may work this way. That's the nature of floating point numbers, It's in all languages, not only Haxe. If you really need that kind of precision u described - floats are not for u. What u need to do is to create your own class, called "LongNatural" or "BigNumber"... Something similar to this: https://www.npmjs.com/package/big-integer , but for natural number... Actually you can use this "big int" with some modifications, like your own defined floating point, for example, at 20th position (or any other u like).

**Comment by ncannasse** [comment]
It correctly compiles to the following, so not on our side:
console.log("Main.hx:4:",357.04999999999995);

**Comment by ncannasse** [comment]
I think that's very hard to get the exact same string representation of double precision floats on all architectures, especially on thing such as JSON which uses native implementation in JS that we don't control. Also, keep in mind that many operations implemented in Math might have platform specific approximation/rounding leading to slightly different results depending on the architecture.

If you want to get exact same results, you should use some kind of fixed point calculus which operates on integers.
