### ISSUE TITLE
Missing "array access is not allowed" error in function call

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6796]
I made a typo that resulted in something like this (array access on a function instead of a map):

```haxe
class Main {
    public static function main() {
        Sys.println(main["foo"]);
    }
}
```

The error message for this is quite confusing, because it misses the usual "array access is not allowed":

```
source/Main.hx:3: characters 26-31 : String should be Int
source/Main.hx:3: characters 26-31 : For function argument 'v'
```

If you remove the `Sys.println()` so you're only left with `main["foo"]`, you get the proper error (although the `String should be Int` part is still weird):

```
source/Main.hx:3: characters 14-19 : String should be Int
source/Main.hx:3: characters 9-13 : Array access is not allowed on Void -> Unknown<0>
```

Haxe version: 37f6b2a9b

**Comment by nadako** [comment]
Huh, it shouldn't even care about Int/String stuff...

**Comment by Simn** [comment]
In theory we can delay the `unify_int`, but we have to be very careful to do it in a way that the error can be recovered from (for overloads).

**Comment by Simn** [comment]
#6674 has a nice test case for that.
