### ISSUE TITLE
Multithreading API for eval's interpreter mode.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#6797]
I asked Simn about this during the summit and he said it shouldn't be a problem. For context: I'm trying to get the hxcpp build tool to run on the interpreter and it's surprisingly hard to do without the multithreading API.

**Comment by Simn** [comment]
Exposing the API is indeed not a problem and I've done this before. The issue is that debugging is not going to work, and I got a headache trying to support it back then. However, I'm fine with just stating that debugging multithreaded applications is not supported for the time being.

**Comment by ncannasse** [comment]
I think that we should avoid this until we are totally happy with
compilation server stability and we have a good idea of what we want. We
could have multithreaded "tasks" that we wait for completion until the
compilation ends, but I don't think we should allow creating threads and
running code without any other restriction.

**Comment by back2dos** [comment]
I was specifically interested in threads for `--interp` and not macros. The latter is interesting too, but the former has various applications. Among other things making hxcpp run on interpretation would be possible ;)
