### ISSUE TITLE
Different behaviours for JsonPrinter depending on target

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/haxe#6801]
```haxe
class Main {
	public function new() {}
	var h:Int = 1;
	public var i(get,set):Int;
	function get_i(): Int {
		return h;
	}
	function set_i(v:Int) : Int {
		return h = i;
	}
	@:isVar var j(get, set):Int;
	function get_j () { return j; }
	function set_j(v:Int) { return j = v; }

	var k(default, set):Int;
	function set_k (v:Int) {
		return k = v;
	}

	public static function main(){
		var a = new Main();
		trace(JsonPrinter.print(a));
		trace(Reflect.fields(a));
	}
}
```

|  | neko | cpp | js | python | lua | cs | java | php |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| json | {"h":1} | {"h":1,"i":null,"j":0,"k":0} | {"h":1} | {"h":1,"j":null,"k":null} | {"h":1} | {"k":0,"j":0,"i":1,"h":1} | {"k":0,"j":0,"i":1,"h":1} | {"h":1,"j":null,"k":null} |
| fields | ["h"] | ["h", "i", "j", "k"] | ["h"] | ["h", "j", "k"] | ["h"] | ["k","j", "i", "h"] | ["k","j", "i", "h"] | ["h", "j", "k"] |

~~with php failing.~~

Only the PHP and Python target seems to yields the correct results. The other target either save extra fields or miss some.

If `j` and `k` are initialized neko, js and lua targets will yield correct results.

**Comment by back2dos** [comment]
This is pretty much expected. [`Reflect.fields()` is only guaranteed to work on anonymous structures](https://api.haxe.org/Reflect.html#fields), but more importantly since JSON doesn't have any notion of classes, it's not even clear what a correct representation would look like - for example whether `i` belongs in the output or not doesn't seem self-evident to me, in particular when considering clients that fetch the data and cannot replicate the (potentially complex) computation performed in the getter. 

My advice is to consider the behavior undefined and therefore avoid it. Consider using Haxe serialization instead. It will treat classes properly, because it can assume that the decoding side shares the same semantics.

**Comment by RealyUniqueName** [comment]
You need to install "mbstring" extension for PHP.
I've got these with php:
```
Main.hx:24: {"h":1,"j":null,"k":null}
Main.hx:25: [h,j,k]
```

**Comment by elnabo** [comment]
@back2dos From my point of view, if there is no real variable behind, it shouldn't be in the json/serialization, as you should theoretically be able to rebuild an object from its json


I don't know if the behaviour should be changed or just have a note saying that using JsonPrinter on classes yields undefined results.

**Comment by nadako** [comment]
There's no standard way to represent non-anonymous objects in JSON, so we can't do much about it except maybe noting about undefined result indeed.

**Comment by RealyUniqueName** [comment]
We can try to `Type.getClass()` and `Type.getInstanceFields()` [instead of `Reflect.fields()`](https://github.com/HaxeFoundation/haxe/blob/b3cc1d79495acafa0ceabc985cd663efc00a28a5/std/haxe/format/JsonPrinter.hx#L164) to make it consistent at least for Haxe-based classes.

**Comment by nadako** [comment]
nah, let's not try encoding stuff that we can't decode into the same object. we should instead have a good library similar to C#'s Json.NET, but macro-based

**Comment by RealyUniqueName** [comment]
We already can't decode it back  with the current version of JsonPrinter. At least we can reduce "surprise" effect of using it. And I think improving cross-target consistency in std lib is a good thing to do regardless of having a good Json library.
