### ISSUE TITLE
Private setters is not working properly

### ISSUE THREAD

**Issue by alexey-kolonitsky** [HaxeFoundation/haxe#6802]
According to the documentation I can use 'null' property modifier to 
> Allows access only from within the defining class

```haxe
class Test {
    
    public static var a(get,null):String;
    static var _a:String;
    
    static function main() {
        a = "10";
        trace('a = ' + a);
    }

    static function get_a() return _a;
    static function set_a(value:String) return _a = value;
}
```
I'm trying to set 'a' property from static method 'main' within the Test class but when I get the value it is 'undefined' in JS and 'null' in AS

JS output:  `a = undefined`
Swf output: `a = null`

https://try.haxe.org/#21902

**Comment by RealyUniqueName** [comment]
Your `a` does not have a setter. Defining `set_a` does not mean it will be used as a setter for `a`. You need to replace `(get,null)` with `(get,set)` to make it work.
Or you need to change your getter to `return a` instead of `return _a`.
