### ISSUE TITLE
Bitwise operators missing for type Bool

### ISSUE THREAD

**Issue by Danielku15** [HaxeFoundation/haxe#6805]
# Description
It appears that the logical and, logical or and logical xor operators are not defined for the type bool. I think all Haxe target platforms support this natively (maybe neko and hashlink not?). 

It's not really a big deal as there is as you can expand the logical to conditional operators. But for the xor operator it is sometimes a bit an overhead. When using bool settings and checking various combinations an XOR is less overhead.

# Environment

* Version used: 3.4.4
* Platform used: JavaScript
* Operating System and version: Windows 10, 64bit

# Example
```haxe
package test;
class Main 
{
	static function main() 
	{
		var a:Bool = true;
		var b:Bool = false;
		var c:Bool;
		c = a & b;
		c = a | b;
		c = a ^ b;
	}
}
```

```
src/test/Main.hx:10: characters 6-7 : Bool should be Int
src/test/Main.hx:10: characters 10-11 : Bool should be Int
src/test/Main.hx:10: characters 2-11 : Int should be Bool
src/test/Main.hx:11: characters 6-7 : Bool should be Int
src/test/Main.hx:11: characters 10-11 : Bool should be Int
src/test/Main.hx:11: characters 2-11 : Int should be Bool
src/test/Main.hx:12: characters 6-7 : Bool should be Int
src/test/Main.hx:12: characters 10-11 : Bool should be Int
src/test/Main.hx:12: characters 2-11 : Int should be Bool
Build halted with errors (haxe.exe).
```

# Current workaround

```haxe
package test;

class Main 
{
	static function main() 
	{
		var a:Bool = true;
		var b:Bool = false;
		var c:Bool;
		c = a && b; // c = a & b;
		c = a || b; // c = a | b;
		c = (a && !b) || (!a && b); // c = a ^ b;
	}
}
```

**Comment by back2dos** [comment]
Uhm, `&&` is the logical and and `||` is the logical or. The operators that don't work as you seem to expect are bitwise operators and they operate only on integer types. In Haxe booleans are not integer types, maybe that's what creates the confusion? Also, XOR for bools is simply `a != b`.

**Comment by Danielku15** [comment]
Coming from the C# (ECMA-334) world the terminology is that  `&&` is the conditional AND and `||` is the conditional OR whereas `&` is the logical AND and `|` is the logical OR. Even if you see them as "bitwise" operators, a bool is nothing but a bit (0/1, true/false)

**Comment by back2dos** [comment]
FYI the terminology "as I describe" is a C thing: https://www.cs.auckland.ac.nz/references/unix/digital/AQTLTBTE/DOCU_059.HTM
It'is the same in C++, Java, Ruby, PHP, JavaScript etc. I'm surprised C# would diverge from it, but hey, why not ^^

Down the line everything is just bits. That doesn't mean that `"hello" ^ function () trace("world")` should just apply XOR to the addresses of both operands. All operators are defined for specific types (except `==` and `!=`). Haxe separates bools and ints entirely, so that `if (alert = RED) launchNukes()` doesn't compile. If that doesn't suit your preference, you could define a custom boolean type that [has these operators](https://haxe.org/manual/types-abstract-operator-overloading.html), if that helps.

**Comment by kaikoga** [comment]
By the way, sometimes I do want "bitwise" operators for `Bool`s, when both operands doSomething:tm: which must be actually evaluated, and we just want to aggregate the `Bool` results without using temporary variables:

https://try.haxe.org/#1c20B

However living with `&&` `||` and `!=` seems possible, especially if having `+` overloaded for `Int` and `String` is too much.

And if side effects are evil. :wink:

**Comment by Danielku15** [comment]
> If that doesn't suit your preference, you could define a custom boolean type that has these operators, if that helps.
Sure, as highlighted already it isn't a big deal and there are workarounds. But on the other hand it is and will stay a workaround for something that appears to be available everywhere. That's why I thought of raising the topic. 

The point highlighted by @kaikoga is also legit and I totally forgot about that. Bitwise operators have a slightly different behavior on evaluating the operators.

**Comment by markknol** [comment]
As alternative you could create a abstract over Bool that does some operator overloading https://try.haxe.org/#1042E
