### ISSUE TITLE
DCE not working correctly?

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6807]
Thanks to @markknol  I checked the output of the following Heaps empty project:

```haxe
class Main extends hxd.App {
   static function main() new Main(); 
}
```

`haxe -lib heaps -main Main -dce full`

Some unused shaders are kept by the DCE, such as `h3d.shader.VolumeDecal` , that might have to do with macros, to investigate further.

**Comment by ncannasse** [comment]
Same with `h2d_Graphics` which is not produced by macros.

**Comment by nadako** [comment]
One of (?) the issues i reduced from this is the following:

```haxe
class C {
	public var a = 0;
	public var b(get,never):Int;
	function get_b() return 0;
}
```

compiling this with `-dce full` keeps the `C` class:

```js
// Generated by Haxe 4.0.0 (git build development @ 392806ae8)
(function () { "use strict";
var C = function() {
};
})();
```

the `-D dce-debug` says `[DCE] Entry point: C.new`

**Comment by RealyUniqueName** [comment]
That `C` example indeed looks like a consequence of my changes.

**Comment by RealyUniqueName** [comment]
However my DCE changes already exist in 3.4.4, which doesn't have this issue. The only change not released yet is https://github.com/HaxeFoundation/haxe/pull/6181

**Comment by RealyUniqueName** [comment]
I've checked 3.4.4 + that change and I confirm it is the reason of this issue.

**Comment by ncannasse** [comment]
Could you either look into it soon or revert your changes until the breaking examples are fixed ?

**Comment by nadako** [comment]
It's probably a little too late to revert because of further dce work done on top of it, we should just look into it.

**Comment by RealyUniqueName** [comment]
I'll take a look today

**Comment by RealyUniqueName** [comment]
Ok, i was on 4.0.0 when i thought i was using 3.4.4+my changes.
Now i've checked 3.4.4+#6181 for sure and the bug is not reproducible with such setup.
I keep looking.

**Comment by RealyUniqueName** [comment]
The bug was introduced in this commit: 2ee49deb4c6fd9bc48a36288cb4bb02669899e99

**Comment by nadako** [comment]
Well, the original sample still produces 20kloc javascript output, so there's more to it.

**Comment by nadako** [comment]
or wait, you didn't commit to `development` yet, ignore me then :)

**Comment by nadako** [comment]
`haxe -dce full -lib heaps hxd.App -js main.js` this one produces 2kloc, while it should probably eliminate everything, gotta investigate further.

**Comment by nadako** [comment]
Here's another snippet. `E` is marked as used even though it's really not.

```haxe
enum E {}

class C {
	static var e(get,never):E;
	static inline function get_e():E return null;
}
```

**Comment by nadako** [comment]
@RealyUniqueName if you're gonna look into this, could you also add more info to `-D dce-debug` (e.g. why something is kept)

**Comment by nadako** [comment]
That happens because the field `e` is kept because it's non-physical (not sure why it's like that), so then its `cf_type` is also marked, so `E` is kept...

**Comment by RealyUniqueName** [comment]
I can't reproduce your sample with my last fix.

**Comment by RealyUniqueName** [comment]
As for heaps, it looks like shaders get kept just like @ncannasse said.

**Comment by ncannasse** [comment]
Looks better now, closing.
