### ISSUE TITLE
[Display][Diagnostics] Multi file support?

### ISSUE THREAD

**Issue by Neverbirth** [HaxeFoundation/haxe#6808]
Would it be possible to make diagnostics support passing a list of files? Right now, and unless I'm wrong, there is only support for passing either one file or checking a project globally. Being able to pass a list of files would save time on multiple calls, and would make sure that every desired file is checked, as global diagnostics doesn't check for files that are in the classpath but not directly referenced.

**Comment by Simn** [comment]
@Gama11: This is something to consider for when we port diagnostics to the json protocol.

**Comment by Simn** [comment]
Will track this in #9134 which I plan to resolve for 4.1.
