### ISSUE TITLE
Abstract `this` assignment vs read-only fields.

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6812]
The following compiles while it should error with `Cannot access field or identifier f for writing`:

```haxe
class C {
	public var f(default,never):A;
	public function new() {}
}

abstract A(Int) {
	public inline function change() this = 42;
}

class Main {
	static function main() {
		var c = new C();
		c.f.change();
	}
}
```

**Comment by RealyUniqueName** [comment]
I don't understand why it should fail. `never` means you can't assign to that field, but doesn't mean you can't invoke methods of that field.

**Comment by nadako** [comment]
It should fail because after the inlining it becomes an assignment to a field that has `never` write access.

**Comment by nadako** [comment]
The readonly field check should probably be done after typing any expression, not just in `type_binop`...

**Comment by back2dos** [comment]
Should it fail though? Isn't the abstract about hiding the fact that the method call on it performs its side-effect by reassigning the whole value? I'm not sure how this-assignment is supposed to work, but I think the way it's now kind of makes sense.

**Comment by nadako** [comment]
Oh well, I'll just assign this to nicolas to make a decision.

**Comment by ncannasse** [comment]
I don't think it should fail, and there is no actual way for the type system to detect such cases anyway :)

**Comment by nadako** [comment]
> there is no actual way for the type system to detect such cases anyway :)

I think there is - we should check whether the field can be assigned to after typing the expression, instead of doing the particular check when typing `EBinop(OpAssign, ...)`.

But design-wise - oh well, if you think it's fine, so be it.
