### ISSUE TITLE
String interpolation when using `case '$key'` doesnt work

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6813]
The following test logs "unexpected", but I would expect "valid". 

```haxe
var key = 'hello'; 
var value = switch "hello world" {
    case '$key world': "valid"; // << see generated source
    case "hello world": "redundant"; // << redundant because should be same as previous
    case other: "invalid";
}

trace(value);
```
demo: https://try.haxe.org/#D91Af

The generated JavaScript code contains like this switch:
```
switch(_g) {
	case "$key world":
		value = "valid";
		break;
	case "hello world":
		value = "redundant";
		break;
	default:
		var other = _g;
		value = "invalid";
	}
```

It seems string interpolation when using `case '$key'` doesnt work, I would either expect it to work, or a warning / error.

**Comment by nadako** [comment]
> I would either expect it to work

I wouldn't, case patterns are always constant, interpolated strings aren't :) So this ideally should be an error.

**Comment by back2dos** [comment]
Well, it could also capture `key` as `"hello"` ;)

**Comment by markknol** [comment]
Ok well if it isn't constant / there is no way to support it (I don't have a preference tbh), then I would love an error/warning 👍

**Comment by ncannasse** [comment]
This should definitely give an error

**Comment by kevinresol** [comment]
There is another place where string interpolation doesn't work, object key:

```haxe
var x = '123';
trace(Json.stringify({'$x':'$x'})); // {"$x":"123"}
```

**Comment by RblSb** [comment]
Fixed with https://github.com/HaxeFoundation/haxe/pull/10496

**Comment by Simn** [comment]
This now gives

```
 4 |   case '$key world': "valid"; // << see generated source
   |         ^^^^^^^^^^
   | String interpolation is not allowed in case patterns
```
