### ISSUE TITLE
[dce] recent change is too optimizing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6819]
The following code fails to compile because of b44fdfa91f05ec5c202a6105fb33caf2144166e7, so I have reverted it for now:

```haxe
// haxe -dce full -main Main -lib nape -hl main.hl
class Main {
	static function main() {
		new nape.shape.Circle(1);
	}
}
```

It removes too many member vars from some classes, it seems the constructor is not properly scanned.

**Comment by RealyUniqueName** [comment]
Can this sample be minimized to exclude nape?
And preferably without hashlink, because last time i had troubles running it on linux.

**Comment by ncannasse** [comment]
@RealyUniqueName I tried but didn't manage to reproduce with a more simpler example. For hashlink you only need to compile it, not run it, as it requires the accessed member variables to be declared (that is not the case for JS output for instance)
