### ISSUE TITLE
Compiler cache and smart strings

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6820]
While compiling a JS project using the compiler cache, there was a build were all smart strings (single quoted '...') were entirely ignored, leading to many runtime errors.

**Comment by back2dos** [comment]
I assume you mean no interpolation was performed? I had that happen to me sporadically.

Maybe something like this could solve it? https://github.com/HaxeFoundation/haxe/pull/6627

**Comment by ncannasse** [comment]
Haven't had the issue for a while now
