### ISSUE TITLE
Community Support page, does not mention community.haxe

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#6821]
When googling Haxe and community:

https://haxe.org/community/community-support.html

But this page needs re-thinking to include:

http://community.haxe.org/

Reported on community and Mark Knol requested I post as issue here.
"Please report site issues at GitHub haxe.org repo, that makes it easier to pickup for contributors.
I agree that page should have links to new forum + gittr."

**Comment by markknol** [comment]
Time traveling is a wonderful thing. I fixed this 6 hours ago 😉 Will go live in next site update.
https://github.com/HaxeFoundation/haxe.org/commit/c2c636569954098f30eb563154bd770fea44c5ad

Btw, we have different repository for the website https://github.com/HaxeFoundation/haxe.org

**Comment by Justinfront** [comment]
Ah ok sorry haxe != haxe.org.  I would have looked deeper and considered a pull if I was sure on exactly how it should look.

**Comment by nanjizal** [comment]
Ah ok sorry haxe != haxe.org. I would have looked deeper and considered a pull if I was sure on exactly how it should look.

**Comment by markknol** [comment]
No problem 👍
