### ISSUE TITLE
[java] `Std.is(value, SomeType)` breaks java compilation

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6823]
```haxe
class Test {
	static public function main() {
		trace(Std.is("hello", Test));
	}
```
```
$ haxe tests.hxml -java bin/java
haxelib run hxjava hxjava_build.txt --haxe-version 4000 --feature-level 1
javac "-sourcepath" "src" "-d" "obj" "-g" "@cmd"
src/haxe/root/Test.java:38: error: incompatible types: String cannot be converted to Test
                haxe.Log.trace.__hx_invoke2_o(0.0, ( "hello" instanceof haxe.root.Test ), 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"Test", "Test.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (5) )) )}));
```
Reproducible with both 3.4 and development Haxe.
```
$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by nadako** [comment]
This actually looks like a good error to me :) Maybe we should check stuff like this in the Haxe type system for all targets.

**Comment by nadako** [comment]
Assigning to @ncannasse to hear his thoughts.

**Comment by RealyUniqueName** [comment]
Currently this is an inconsistency across targets.
Also I think if Haxe compilation completed successfully, then native compilation should not fail.

> Maybe we should check stuff like this in the Haxe type system for all targets.

I doubt this is the right solution. 
I got this error because of inlining:
```haxe
var s = 'hello';
checkType(s); //this function is inlined, and is optimized to `Std.is('hello', MyType)`
```
This code doesn't look like Haxe should abort compilation.

**Comment by nadako** [comment]
> Currently this is an inconsistency across targets.
Also I think if Haxe compilation completed successfully, then native compilation should not fail.

sure, that's why I'm thinking about having this check in haxe itself

> I got this error because of inlining:

Still sounds quite correct to error here, because a known `String` will never be `MyType`. I think other languages do the right thing erroring on this. Even Haxe has a similar check for `Std.instance`, so maybe we should add one for `Std.is` too (it already have special treatment in the compiler code anyway).

**Comment by ncannasse** [comment]
The code is perfectly normal and should not error. It can be optimized as "false" if necessary, but should not create any compilation error in either Haxe or the target platform.

**Comment by RealyUniqueName** [comment]
Duplicates #5168
I suggest to continue discussion in that issue.
