### ISSUE TITLE
[js] extern `js.html.Location` is missing `toString` method

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6824]
https://developer.mozilla.org/en-US/docs/Web/API/Location

**Comment by RealyUniqueName** [comment]
@nadako are those externs autogenerated?

**Comment by nadako** [comment]
yes they are, but noone really wants to support that, so we might just switch to hand-writing them

**Comment by RealyUniqueName** [comment]
Where should i look for autogeneration tools?

**Comment by nadako** [comment]
https://github.com/HaxeFoundation/html-externs

(note that we might have made modifications by hand before earlier, so if you go with the tool - diff the externs to be sure).
