### ISSUE TITLE
Compiler crashes with nothing but Pervasives.Exit -- on empty interpolation

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#6826]
I'm getting a crash of `Pervasives.Exit` with this simple example with an empty interpolation:

```Haxe
class Main
{
  public static function main()
  {
    trace('Hello ${ } world!');
  }
}
```

```sh
> haxe -x Main.hx
Pervasives.Exit
```

The real-world scenario is that I was rapidly developing a feature, put in a placeholder in my template variable (`var url = '/foo?token=${ }';`), but forgot to come back and filled in the variable. Perhaps a common scenario. Debug was an unhappy "binary search, deleting code until the compiler starts working again" situation.

Related or duplicate (though that title implies newlines): #5985

Observed in Haxe 3.4.2 (sorry I can't currently test other versions.)

**Comment by nadako** [comment]
> Debug was an unhappy "binary search, deleting code until the compiler starts working again" situation.

Sorry, should be better now!

**Comment by nadako** [comment]
reopening because it apparently shouldn't be an error (see https://github.com/HaxeFoundation/haxe/commit/c00559c995f3c3a4b14d89b626c5f1e12c9d77cd#commitcomment-27260840, thanks @Gama11!)

**Comment by ncannasse** [comment]
We should not allow ${} in the first place, an error is ok and previous issue test should be disabled

**Comment by Gama11** [comment]
What's gained by disallowing `${}`?

**Comment by ncannasse** [comment]
@Gama11 simplification. `${ expr }` should contain an expression. Also, if someone mistakenly uses quotes instead of double quotes for `return '${}';` he might be surprise with the result.

**Comment by Simn** [comment]
I agree this shouldn't parse. So it's working as intended now.
