### ISSUE TITLE
Bad error message for broken syntax of meta in `Compiler.addGlobalMetadata()` & `Compiler.addMetadata()`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6828]
```haxe
Compiler.addGlobalMetadata('', '@:build(BuildMacro.build()'); //closing parenthesis is missing
```
Compilation error:
```
$ haxe test.hxml
Unexpected typedef
```
Expected something like this:
```
$ haxe test.hxml
MyModule.hx:123: Malformed metadata string
```

**Comment by nadako** [comment]
Should be better now. The error position points to the macro call instead of the addMetadata call though, but that's the general issue with `MacroApi` functions there...

**Comment by player-03** [comment]
Note to self, and to anyone else searching for this error message: remember to include the `@` at the beginning of the string.

(I'm used to working with the AST, which splits metadata into names and params, omitting the `@`. But I guess it's better to think of this as inserting a string into the .hx file.)
