### ISSUE TITLE
Dependency fails silently with malformed json

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/haxe#6829]
```json
"dependencies":
  {
    "hexinject": "git:https://github.com/DoclerLabs/hexInject.git",
  }
```
Because of the comma addition, the application will be compiled without the haxelib dependency.
On a big project, believe me, it takes time to catch this error. I would expect to get an error message, or at least a warning somewhere.

**Comment by RealyUniqueName** [comment]
I think this issue should go to [haxelib repo](https://github.com/HaxeFoundation/haxelib)

**Comment by nadako** [comment]
Indeed, moved to the haxelib repo.
