### ISSUE TITLE
Concrete type parameter conversion from Type to ComplexType fails

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#6830]
As an example I start from 
````haxe
typedef VarChar<@:const L> = String
````
Reading an occurence of this type through a macro becomes:
````haxe
trace(Context.typeof(macro (null: VarChar<123>)));

=> TType(VarChar,[TInst(I123,[])])

// TInst stores this expr info with
kind => KExpr({ expr => EConst(CInt(123)), ...})
````
When converting this to a `ComplexType` through `TypeTools.toComplexType` this becomes:
````
TPath({ name => Test, pack => [], params => [TPType(TPath({ name => , pack => [], params => [], sub => I123 }))], sub => VarChar })
````
So it uses `TypeParam.TPType` instead of the expected `TypeParam.TPExpr`.

Using the `ComplexType` in a macro afterwards results in hard to debug errors like the following:
````
Macro.hx:23: characters 17-33 : Type not found : 
````
You can follow the example here (see compiler output): http://try-haxe.mrcdk.com/#21F9a

(Original issue https://github.com/haxetink/tink_json/issues/40)

**Comment by nadako** [comment]
good catch, thanks!
