### ISSUE TITLE
StringTools.htmlUnescape should handle HTML5 &apos; too

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/haxe#6832]
Hello,
Very simple fix to do: but can make dev gain some debug time:
Today haxe StringTools.htmlUnescape only handle &amp;#39; for single quote html entity.
in fact in HTML5 its now &amp;apos; value.
So when we use htmlUnescape to unescape a text escaped from other platform than haxe, for example php, &amp;apos; won't be unescaped.

doc says: single quote: "&amp;#039; (for ENT_HTML401) or &amp;apos; (for ENT_XML1, ENT_XHTML or ENT_HTML5)"

the fix should be: 
.split("&amp;#039;").join("'")   
becomes:
 .split("&amp;#039;").join("'").split("&amp;apos;").join("'")

no need to change htmlEscape.

the code is 100% retro compatible.

Thanks
Seb

**Comment by RealyUniqueName** [comment]
Should we also encode backtick to `&apos;` in `StringTools.htmlEscape()`?
Otherwise escape+unescape will return a different string instead of an original one.

**Comment by RealyUniqueName** [comment]
Anyone? )
@ncannasse @nadako

**Comment by nadako** [comment]
I don't know much about escaping, but that sounds right

**Comment by RealyUniqueName** [comment]
After a bit more googling i've came to conclusion Haxe should not support &apos in htmlEscape/htmlUnescape because that char is not in the HTML standard. It comes from XML.

**Comment by sebpatu** [comment]
sorry, but you googled wrong.
its XHTML and HTML5 official standard.
As i say in my request, php doc refers to &#apos; as HTML5 standard: specifying : (for ENT_XML1, ENT_XHTML or ENT_HTML5)
here: http://be2.php.net/manual/en/function.htmlspecialchars.php
i found that more official HTML5 doc: https://dev.w3.org/html5/html-author/charref
or here: http://w3c.github.io/html/syntax.html#named-character-references

in https://dev.w3.org/html5/html-author/#single-quote-attr
it says "To include a single-quote (or apostrophe) character within the value, either use a character reference (&apos;), or use a double-quoted attribute value instead."
its logical they included this to standard as $39; is not consistent special named char. as is double quote &quote; and other sepcial characters.

**Comment by sebpatu** [comment]
> Otherwise unescape+escape will return a different string instead of an original one.

Its not an issue as &apos; is only an alias of unicode characters, like other html special characters.
If you use  &#x00022;  or  &#34; in your encoded string, unescape+escape will already give a different 
result, replacing &#34; by &quote;

the only thing is that &apos, being a html5 standard, it is not supported by old HTML4 browsers, even if a lot of old HTML4 browsers already supports it.  at least ie8 dont.

but we could add an argument to StringTools.htmlEscape

Anyway, what i suggested was only about StringTools.htmlUnescape being able to unescape html5 standard. So its perfectly retro compatible, even for ie8, as the reverse action StringTools.htmlEscape wich will give data to browser, still use the previous value &#39; that ie8 understand well.

**Comment by ncannasse** [comment]
That's a bit tricky. If we want to do "proper" escape/unescape, then we should correctly implement the whole HTML5 entities and escaping chars... which requires UCS2 Strings by default.
I think before that we should not modify these functions with a half-baked change.

**Comment by sebpatu** [comment]
"proper" escape/unescape would be better of course.
But those functions already handles double quote, and single quotes. so its expected to handle the HTML5 single quote properly, even if it does not handle all entities.
If so, it would mimic what the php unescape function 'htmlspecialchars', which also handles only quotes single and double, ampersand, less than, more than, and thats it.
even with such a name, the function dont unescape all html entities.

**Comment by ncannasse** [comment]
I think that given the proper solution is to handle all entities, I would prefer to break only once these String functions and not just add one case that might cause some issues for users, later to be changed again.

**Comment by ncannasse** [comment]
Closing. Doing proper all-entities escaping should be done with a 3rd party library, and we already specify well what htmlEscape does.
