### ISSUE TITLE
Unix.Unix_error(21, "open_proc", "haxelib path perf.js")

### ISSUE THREAD

**Issue by pypmannetjies** [HaxeFoundation/haxe#6835]
This issue occurs if using bash on Windows.

Unix.Unix_error(21, "open_proc", "haxelib path perf.js")

The haxelib path perf.js resolves to:

haxelib path perf.js
C:\<path>\.haxelib\perf,js/1,1,8/src/
-D perf.js=1.1.8

The same issue does not occur from a normal command prompt.

This is on version 4.0.0-preview.2

Probably related to https://github.com/HaxeFoundation/haxe/issues/6768

**Comment by cmandlbaur** [comment]
Running into this too on 3.4.4.

**Comment by elsassph** [comment]
Which Bash environment? What is the bin path of Haxelib/Haxe?
Msysgit comes with Bash and can run Windows apps, Windows has native Bash but is a separate Linux environment - in this case did you install Linux version of Haxe?

**Comment by pypmannetjies** [comment]
This is happening for me in the following:

Powershell
Git bash (packaged with Git for windows)
VS Code integrated debugger and completion server
Running gulp tasks inside IntelliJ
Haxe versions: 3.4.0 up to 4.0.0-preview.2

The installed version of Haxe is the Windows version.

**Comment by pypmannetjies** [comment]
Haxe Library Manager 3.3.0 - (c)2006-2016 Haxe Foundation
Haxe Compiler 3.4.4 - (C)2005-2017 Haxe Foundation

**Comment by back2dos** [comment]
Ok, so `haxelib path perf.js` gives you the right output, but `haxe -lib path.js` fails with `Unix.Unix_error(21, "open_proc", "haxelib path perf.js")`? If so, which of the two do you get if you run `haxe -cmd "haxelib path perf.js"`?

**Comment by pypmannetjies** [comment]
Yes, there's no issue with path's output (except for maybe some inconsistent path separators)

I get this: 

```
 MINGW64 
$ haxe -cmd "haxelib path perf.js"
Unix.Unix_error(21, "open_proc", "haxelib path perf.js")
```

**Comment by pypmannetjies** [comment]
The issue seems to be the slash at the end of the path. There was a similar issue with mkdir: https://github.com/HaxeFoundation/haxe/issues/6768

**Comment by axelmm** [comment]
it looks like environment path/variables problem
what for `haxelib config`
or 'SET HAXEPATH'

**Comment by pypmannetjies** [comment]
Haxelib config seems normal. It points to my global folder, or the .haxelib folder of my current project.

**Comment by axelmm** [comment]
any difference under bash/shell or haxe -cmd ? gives proper values everwhere?

**Comment by back2dos** [comment]
Hmm. Well, it seems very much like this is the source of the error: https://github.com/lucasaiu/ocaml/blob/master/otherlibs/win32unix/unix.ml#L809

That would indicate that the COMSPEC env variable is not set for some strange reason. Is it set in the calling shell? If so, can you try `haxe --macro Dump.env()` with:

```haxe
class Dump {
  static function env() 
    Sys.println(Sys.environment());
}
```

Just to see if the env vars make it correctly into haxe?

**Comment by pypmannetjies** [comment]
So COMSPEC is not set in either Powershell or Git Bash, but I suspect that's normal. COMSPEC points to cmd.exe, which is not used in either of those terminals?

**Comment by back2dos** [comment]
I'm not sure which setup is "normal", but what I can tell you is that on my Windows it's set in all shells and as a result "it works on my machine" ;)

**Comment by pypmannetjies** [comment]
Ok, thanks. Seems something has gone belly up with my system. I tried to set COMSPEC in those terminals but that makes things break terribly.

**Comment by pypmannetjies** [comment]
This was fixed by expicitly setting the COMSPEC environment variable. Thanks so much @back2dos :)
