### ISSUE TITLE
Inconsistent typing of ternary operator when `Null<T>` is invloved

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6836]
With any Haxe version
```haxe
var v:Null<String> = 'a';
$type(Std.random(2) == 1 ? 'hello' : v); // String
$type(Std.random(2) == 1 ? v : 'hello'); // Null<String>
```
https://try.haxe.org/#5ee54

**Comment by nadako** [comment]
i think this is expected as per inference rules, but yeah, the whole Null<T> situation is confusing to say the least

**Comment by Simn** [comment]
I think this should use `unify_min` to get a consistent result. Does it work properly with `if`?
