### ISSUE TITLE
[proposal] provide methods to Class/Enum

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#6839]
Just an idea, feel free to close it if you don't like it.

Since Class and Enum are abstracts nowadays, we could provide methods on them that would actually call static methods of Type passing `this`, which would allow for nicer api:

```haxe
var className = cls.getName();
var instance = cls.createInstance(args);
var superCls = cls.getSuperClass();
for (field in cls.getInstanceFields()) {
    // ...
}
```

**Comment by back2dos** [comment]
I like it. However, there might be a slight confusion about something like this:

```haxe
class Foo {
  static public function getName() return "blarghwlarghdragh";
}

var foo = Foo;
trace(foo.getName());//blarghwlarghdragh
var foo:Class<Foo> = Foo;
trace(foo.getName());//Foo
```

Perhaps it's worth explaining in the docs?

**Comment by RealyUniqueName** [comment]
We have tests which check that accessing a field on a variable of type `Class<T>` is actually a reference to a static field of that class. The same for `Enum<T>`

**Comment by ncannasse** [comment]
What would be the gain for it? If it's purely aesthetic, I think we have more important things to do :)

**Comment by nadako** [comment]
i guess you're right, also what juraj mentioned is concerning, closing for now.
