### ISSUE TITLE
ListIterator terminates early when new elements added during visit to last item

### ISSUE THREAD

**Issue by rkspsm** [HaxeFoundation/haxe#6840]
This code : 

```
class Main {

  static public function main () : Void {

    var l1 = new List<Int> () ;
    l1.add (1) ;
    l1.add (2) ;
    l1.add (3) ;

    trace ('---------') ;
    for (i in l1) {
      if (i == 2) {
        l1.add (10) ;
      }

      trace ('l1: $i') ;
    }


    var l2 = new List<Int> () ;
    l2.add (1) ;
    l2.add (2) ;
    l2.add (3) ;

    trace ('---------') ;
    for (i in l2) {
      if (i == 3) {
        l2.add (10) ;
      }

      trace ('l2: $i') ;
    }

    trace ('---------') ;
  }

}

```
Basically i create a list twice, populating with [1,2,3], then iterated over them, and during iteration, added a new element : 10. In the first list, I added it during the visit to second last element : 2.
In the second list, I added it during the visit to last item : 3.

The output however was : 
```
---------
l1: 1
l1: 2
l1: 3
l1: 10
---------
l2: 1
l2: 2
l2: 3
---------

```
You can see that "l2:10" was never printed.

Looking at the code of ListIterator<T> in development branch : 

```
private class ListIterator<T> {
	var head:ListNode<T>;

	public inline function new(head:ListNode<T>) {
		this.head = head;
	}

	public inline function hasNext():Bool {
		return head != null;
	}

	public inline function next():T {
		var val = head.item;
		head = head.next;     // <----- Here is the problem
		return val;
	}
}
```
I commented the problem line. The this.head becomes null when last item was tail.... and this is used in the check for hasNext ().... all the while, in actual list, the tail actually got a new item.

**Comment by jdonaldson** [comment]
Adding elements during iteration is undefined behavior.

**Comment by rkspsm** [comment]
[https://haxe.org/manual/std-List.html](https://haxe.org/manual/std-List.html)
The manual of the list explicitly says that you can freely modify/add/remove elements while iterating over them.

**Comment by ncannasse** [comment]
This is working as expected. You can modify/add/remove elements but if you add an element just after the one currently being iterated, it's already skipped and will not show in iteration. it doesn't change if it's in the middle or the end of the list.

**Comment by rkspsm** [comment]
Well, I was aware that its already skipped because of the way the ListIterator is implemented. But imho, shouldnt this be mentioned in the manual ?
