### ISSUE TITLE
3.4.6 : Invalid_argument("index out of bounds")

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#6844]
I get an error with new haxe version (and not with 3.4.5): `Invalid_argument("index out of bounds")`

Minimum example:
```haxe
class Main {
    public static function main() {}
}
```

```sh
$ haxe -js /tmp/346.js -main Main 
Invalid_argument("index out of bounds")
```

**Comment by markknol** [comment]
I can confirm it only happens when path starts with backslash. Not sure why you ever do that :)

**Comment by kLabz** [comment]
I use Arch Linux
Haxe 3.4.6 (official release)

**Comment by mastef** [comment]
Our builds broke due to this after updating to latest `haxe:latest` docker base image. Reverting to `haxe:3.4.5-stretch` fixed it for now.
