### ISSUE TITLE
Parametrized class static variable inconsistency between platforms (cs vs cpp/js)

### ISSUE THREAD

**Issue by dyarosla** [HaxeFoundation/haxe#6845]
Creating a static variable in a templated class results in inconsistencies between platforms.

```haxe
class Sample<T> {
    public static var n:Int =0;
    public function new() {
        n++;
    }
}

class Test {
    public static function main(){
        var a = new Sample<Float>();
	var b = new Sample<Bool>();

	trace(Sample.n); // cpp: 2,   js:2,   cs: 1
    }
}
```

As I understand it

cs: 
Creates a static variable `n` for each new `T`,
So each of `Sample<Float>` and `Sample<Bool>` have its own static var `n`.

cpp:
Creates a static variable `n` for all `T`
So `Sample<Float>` and `Sample<Bool>` share the same static var `n`.

I don't know which is the correct result, but the inconsistency is real and definitely a bug in one of these platforms. 

Thoughts: I'm guessing because I can only reference `n` through `Sample.n` and not through 
`Sample<Float>.n` or `Sample<Bool>.n` (which is invalid syntax), cpp has the "correct implementation"- HOWEVER, if `Sample<Float>` and `Sample<Bool>` are to be treated as different classes, each should have its own static variable as in cs.

So 

1) What should be the expected result?
2) Which platform implementation needs to be changed?

**EDIT:** Tested in javascript as well (https://try.haxe.org/#B36FD). Result is consistent with cpp. Guessing cs has the wrong implementation?

**EDIT 2:** 
So it seems like cs treats it correctly:
https://stackoverflow.com/questions/14748569/is-a-static-member-variable-common-for-all-c-sharp-generic-instantiations

And in fact, cpp implementation (and thus js too) are wrong:
http://www.fayewilliams.com/2014/12/23/static-variables-in-template-classes-and-methods/

I'm thinking cpp and js need to be modified! But moreover; `Sample.n` should result in an error and the correct access should be ` Sample<Float>.n` or ` Sample<Bool>.n`

**Comment by RealyUniqueName** [comment]
This is probably can be accountd as a bug of C# target.

**Comment by dyarosla** [comment]
The more I read into this, the more I am convinced that cs handles this correctly internally. This is definitely implemented wrong in cpp and js, as well as requires changes to haxe to disallow accessing `Sample.n` if `Sample` is a template class and instead allow `Sample<T>.n`.

**Comment by nadako** [comment]
In Haxe, static vars of parametrized classes (it's not templates) are shared, so C++/JS behaviour is correct and it really looks like a C# generator bug indeed.

**Comment by dyarosla** [comment]
Sure- I may be wrong with the naming, but still leads me to ask: why are static vars of parametrized classes shared? Should they?

Different classes don't share static vars. And instances of a parametrized class with different parameters don't share the same class type... so why should they share the same static vars? Other languages seem to agree with this line of reasoning (and the cs implementation).

**Comment by nadako** [comment]
> instances of a parametrized class with different parameters don't share the same class type

they actually do, an instance is a pair of class + type params (which are actually erased at run-time on most targets), so it's actually class instances which are parametrized, class is always the same, so static vars are shared.

>  Other languages seem to agree with this line of reasoning

**Comment by nadako** [comment]
> instances of a parametrized class with different parameters don't share the same class type

they actually do, an instance is a pair of class + type params (which are actually erased at run-time on most targets), so it's actually class instances which are parametrized, class is always the same, so static vars are shared.

>  Other languages seem to agree with this line of reasoning 

not e.g. Java, or, say TypeScript

**Comment by dyarosla** [comment]
Ah! I see. Then yes, cs implementation needs to be fixed to reflect this.

**Comment by waneck** [comment]
I think this is a regression, unless the `Sample` class is a `@:nativeGen` class. It should always access the static variables of the `Sample<object>` in that case

**Comment by dyarosla** [comment]
Can you confirm the above sentence? That:

If `Sample` is a `@:nativeGen`, it should access a different `Sample<T>.n` per type `T`

If `Sample` is NOT a `@:nativeGen`, it should access the same `Sample.n` across any type `T`

**Comment by waneck** [comment]
That's correct, @dyarosla

**Comment by dyarosla** [comment]
I can confirm that, currently (and incorrectly), `Sample` without `@:nativeGen` is accessing a different `Sample<T>.n` per type `T`
