### ISSUE TITLE
Revert #6825

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6847]
I think #6825 does more harm than good. Having different typing for something as used as Array depending on the platform creates more issues, we want to avoid platform-specific typing as much as possible.

@RealyUniqueName please revert

**Comment by RealyUniqueName** [comment]
Too bad )
This will be a big problem when/if we decide to implement null safety in the compiler.

**Comment by nadako** [comment]
> This will be a big problem when/if we decide to implement null safety in the compiler.

I think null safety would require unspecifying out-of-bounds array access. It's already an issue for a lot of targets, they have to check bounds on each array access.

**Comment by RealyUniqueName** [comment]
I don't think it's ok to deal with type holes and inconsistencies by unspecifying them )

Another Haxe issue is that we have too many things unspecified. That makes developers in our team face inconsistencies pretty often (I guess it's applicable to any Haxe user).
I'd like to avoid introducing even more unspecified things.

**Comment by nadako** [comment]
> Another Haxe issue is that we have too many things unspecified. 

that's the cost of overhead-less code generation, we're keeping fragile balance, not overspecifying too much to avoid run-time wrapper/checker code

**Comment by RealyUniqueName** [comment]
Yes, I understand. But that is also one of the reason I usually hear when devs are reasoning "why I left Haxe" )

**Comment by RealyUniqueName** [comment]
Maybe having "unsafe" things for perforamnce-demanding code and "overspecified" things for cross-target consistency code would be a solution.
