### ISSUE TITLE
Language feature request : multiple extends in typedef

### ISSUE THREAD

**Issue by dyarosla** [HaxeFoundation/haxe#6851]
I'd like to see this feature re-evaluated: https://github.com/HaxeFoundation/haxe/issues/2364  @Simn @lptr @ncannasse. (I've opened up this new issue as the old one was stale)

I don't see a good reason for not allowing typedefs to have multiple extends, whereas I do see use cases for it. One use case (that I'm personally looking at) is as follows:

```
typedef BoxParams = {
    ?x,
    ?y,
    ?w,
    ?h
}

typedef TileParams = {
    ?tileName,
    ?transform
}

typedef BoxTileParams = {
    >BoxParams,
    >TileParams
}
```
Then used as follows:

```
function setupBox(params:BoxParams):Void {
    // setup a box object
}

function setupTile(params:TileParams):Void {
    // setup a tile object
}

function setupTileBox(params:TileBoxParams):Void {
    // setup a tile/box hybrid object using these params
    // can invoke the above functions to help
    setupBox(params);
    setupTile(params);
}
```

You can imagine that this would be a pain without multiple-extension, but useful to use these multiple-extend typedefs to easier form overarching declarator/initializer functions.

**Comment by kaikoga** [comment]
FYI: There's a template to propose language enhancements: https://github.com/HaxeFoundation/haxe-evolution

**Comment by dyarosla** [comment]
I'm unsure about sections **Detailed design** and **Impact on existing code** so I want to just start the conversation here first, and go from there (although @ncannasse mentioned in the previous issue that he believes it would not be a breaking change)

This is less of a **Haxe change** so much as it is a *feature completion*.

**Comment by RealyUniqueName** [comment]
It's already implemented: https://try.haxe.org/#E6eAB

**Comment by dyarosla** [comment]
I see. Specifically, I didn't know I required a trailing `,` at the end

```
typedef BoxTileParams = {
    >BoxParams,
    >TileParams,   // <- right over here
}
```

It's not documented in `https://haxe.org/manual/types-structure-extensions.html` that a trailing comma is **required** for this to work. It's also a little inconsistent with the regular `typedef` format where a trailing comma is left off and still works for fields in a `typedef`. Perhaps this trailing comma requirement needs to be re-evaluated?

**Comment by RblSb** [comment]
Related to #6565
