### ISSUE TITLE
[js] sourceMappingURL isn't encoded as a URL

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/haxe#6852]
The sourceMappingURL needs to be encoded as a url instead of directly copying the filename.

For example, `haxe -js "my game.js"` (with a space) leads to `//# sourceMappingURL=my game.js.map` in the generated file. It should be `//# sourceMappingURL=my%20game.js.map` for a valid source map.

**Comment by RealyUniqueName** [comment]
We already have url_encode implemented in ocaml here: https://github.com/HaxeFoundation/haxe/blob/b3cc1d79495acafa0ceabc985cd663efc00a28a5/src/macro/eval/evalStdLib.ml#L2067
We just need to move it to some common module and reuse.

**Comment by nadako** [comment]
Thanks for the report!
