### ISSUE TITLE
Multiple extends in typedef should not require a trailing comma to compile

### ISSUE THREAD

**Issue by dyarosla** [HaxeFoundation/haxe#6853]
If you want to use multiple extends on a `typedef`, without adding more fields to a `typedef`, a trailing comma is required. For example:

```
typedef BaseAndMoreParams = {
    >BaseParams,
    >MoreParams,   // <- comma required here, else won't compile
}
```
This is inconsistent with the regular `typedef` spec for fields where a trailing comma can be left off after the last field with no issue:
```
typedef Params = {
    x:Float,
    y:Float    // no trailing comma, a-ok!
}
```
This may cause confusion as to why the program cannot compile. The requirement for a trailing comma is also not documented in https://haxe.org/manual/types-structure-extensions.html.

Perhaps this trailing comma requirement needs to be re-evaluated?

**Comment by nadako** [comment]
agreed

**Comment by dyarosla** [comment]
Duplicate of https://github.com/HaxeFoundation/haxe/issues/6565

**Comment by RblSb** [comment]
Oh, I did not see. I think it's better decorated and i can close my old issue?

**Comment by dyarosla** [comment]
Either or. I hadn’t seen your issue until you posted it, so I decided to mark mine as duplicate.
