### ISSUE TITLE
Extern for js.Date

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#6855]
Maybe I've missed it but I do not see any extern for the [js Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date).

The haxe Date is very limited in comparison making the js Date very helpful in some cases...

Could we add a js.Date extern?

**Comment by RealyUniqueName** [comment]
Actually Haxe's Date is JS's Date when targeting Javascript.
While there is no complete extern, you can use `untyped` as a workaround:
```haxe
var now = Date.now();
var year:Int = untyped now.getFullYear();
trace(year);
```
https://try.haxe.org/#4F20C

**Comment by zabojad** [comment]
@RealyUniqueName yes I already user `untyped` to use it but it's not really a solution...

Maybe there should be some extended type definition of `Date` when targetting js? We need a type safe solution here...

**Comment by nadako** [comment]
I'm not sure what approach is better here. One option is to add `js.NativeDateTools` which would be a static extension collecton that provides additional methods for regular top-level `Date` class. This approach is used in some places, e.g. `python.NativeArrayTools` or `cpp.NativeString`.

**Comment by R32** [comment]
I feel it should avoid using `untyped` to help the optimizer work better.

```
var year:Int = (now: Dynamic).getFullYear();
```

**Comment by RealyUniqueName** [comment]
> One option is to add js.NativeDateTools

I think complete extern at `js.Date` would be consistent with other js externs we have.

**Comment by zabojad** [comment]
For now, I think it would be very fast and easy to add a `js.Date` extern (btw no need to call it `NativeDate` in my opinion as it is already "isolated" to the js context, being part of the js haxe package).

**Comment by ncannasse** [comment]
I agree that adding a js.Date class makes sense.
