### ISSUE TITLE
Class php.Global Seems To Be Placed Into The Wrong Package 

### ISSUE THREAD

**Issue by hereticByte** [HaxeFoundation/haxe#6856]
_Concerns compiling with **Haxe 3.4.4**_

Dear HAXE team, 

as I am probably not the only one who uses HAXE for PHP, I assume, that this is actually not an issue.

Most likely there is a finesse, that I did not understand correctly.

BUT:

The compiler stops as it finds the the class **_'Global'_** in the **_'php7'_** package, as it resides in the 'php' package, although the class itself has the package information _**'package php;'**_

For experimental reasons, I have also tried simply to change the package information to **_'package php7'_**. Of cause, this did not work.

....

I am new to compiling HAXE to PHP. And I want to use the **_'php7.Global'_** class to get the **_'echo()'_** function as the Lib.println() does not print the lines with a linebreak.

So is it an issue? 

And if not, what am I doing wrong?

Thank you in advance.

Kind regards
Arnim

**Comment by RealyUniqueName** [comment]
It's not an issue. Prior to Haxe 4.0.0 we have two php generators: an old one (which targets PHP 5.3+) and a new one (for PHP 7.0+).
All the types located in `php7` directory of std library belong to the latter. 
If you are using Haxe 3.4.x you can enable a new php generator by adding `-D php7` to compiler flags. E.g. `haxe -main Main -php bin -D php7`. And all types from `php7` directory will become available under `php` package.
Since Haxe 4.0.0-preview.2 an old generator is removed, and `-D php7` is not needed anymore.

**Comment by RealyUniqueName** [comment]
As for `Lib.println()` it explicitly prints new line character `\n` when invoked. It's unlikely to be broken.
Here is my quick test:
```haxe
class Main {
	static function main() {
		php.Lib.println("hello");
		php.Lib.println("world");
	}
}
```
```
$ haxe -main Main bin/php && php bin/php/index.php
hello
world
```
As you can see linebreaks are printed.

**Comment by hereticByte** [comment]
Thank you for your answer, @RealyUniqueName.

It works well now.

But the trouble with the missing linebreaks persists. I will have to look for another cause of this. Maybe I will re-insall HAXE.

Kind regards
Arnim

**Comment by RealyUniqueName** [comment]
I don't think it's because of haxe. Maybe some php setting, but i don't
remember any which affects linebreaks.
How do you run compiled php? Browser or cli?


17 февр. 2018 г. 7:01 PM пользователь "Arnim" <notifications@github.com>
написал:

**Comment by hereticByte** [comment]
Thanks for taking care of the other part of my problem, Alexander.

I test the code within a browser via WAMP as an appache server emulator.

I have compiled the code in PHP7 and I have switched to PHP 7 in WAMP as well.

So, thanks to your suggestion, I will skip re-installing HAXE and look intensively for the settings in WAMP tomorrow.
