### ISSUE TITLE
Add support for source-header-template 

### ISSUE THREAD

**Issue by Danielku15** [HaxeFoundation/haxe#6857]
## Description
Haxe currently supports the `source-header` parameter to add a special comment to the head of all generated source files. The feature was mainly added to help GitHub not to confuse on what language is used in the repository (see #4328) . If you want to use this feature to actually add a project specific source header you are a bit lost as it is hardly possible to specify a proper header comment all via command line. 

## Use Cases
The most obvious use case could be that you want to generate a typical license header. 

Advanced usages might be code injection with the goal to:  

* Adding polyfills to support older browsers. 
* Adding markup-comments that are used by bundeling tools. 
* Use custom module system registrations

## Solution Proposal 1

It would be great if developers could specify a file name instead of a raw string that should be placed in all files as header:

**Command line:** haxe.exe -cp src -js output.js -main Main -D source-header-template=Header.js
**Header.js:**
```javascript
/*
 * Copyright (C)2005-2017 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 */
```
**Output.js**
```javascript
/*
 * Copyright (C)2005-2017 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 */
<JavaScript Code>
```

## Solution Proposal 2

By specifying a template file developers can specify the structure of each file. Template variables can be used to have a more dynamic output and to specify where the actual source should go. 

**Command line:** haxe.exe -cp src -js output.js -main Main -D source-template=Template.js
**Template.js:**
```javascript
/*
 * Copyright (C)2005-{{year}} Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 */
// polyfills
Math.log2 = Math.log2 || function(x) { return Math.log(x) * Math.LOG2E; }
(function() {
   var exports = MyApp.exports;
   {{source}}
})();
```
**Output.js**
```javascript
/*
 * Copyright (C)2005-2018 Haxe Foundation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 */
// polyfills
Math.log2 = Math.log2 || function(x) { return Math.log(x) * Math.LOG2E; }
(function() {
   var exports = MyApp.exports;
   <JavaScript Code>
})();
```

**Proposal for template variables:** 
- {{year}} the year of the time when the compiler was running
- {{month}} the month (1-12) of the time when the compiler was running
- {{day}} the day (1-31) of the time when the compiler was running
- Any conditional define like -D version=1.0 becomes available as {{version}}

## Current Solution
Currently you can only use a manual custom script after compilation to rewrite the compiler output.

**Comment by back2dos** [comment]
You can use `Context.onAfterGenerate` to manipulate the output any way you see fit, so I'm not sure this is all that useful - if you need help with macros, feel free to ask on stackoverflow, [discord](https://community.haxe.org/) or [gitter](https://gitter.im/HaxeFoundation/haxe). 

In any case, for the 2nd proposal, I think you should be more specific about what template variables there should be.

**Comment by RblSb** [comment]
Article about this:
https://blog.onthewings.net/2015/07/22/including-external-js-lib-in-haxe-output/
The function itself:
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Compiler.hx#L415

**Comment by Danielku15** [comment]
@back2dos 
> In any case, for the 2nd proposal, I think you should be more specific about what template variables there should be.

I added some more details to my proposal. 

@RblSb  The example shown in the article is quite close to what I proposed. This should allow an injection of code at most places achieving a custom header/footer. Still it is a bit strange to me that a `source-header` parameter which is hardly usable for anything, makes it into the compiler while this code injection is added as macro. Unfortunately the macro seems to be focusing on JavaScript only. I could imagine that there are also UseCases for other languages like PHP or C++.

**Comment by back2dos** [comment]
Frankly, I don't know why the parameter exists. Quite possibly it's older than macro support. As said before though, you can use `Context.onAfterGenerate` to hook in any postprocessing logic you feel like having.

**Comment by bendmorris** [comment]
Sort of related: I would love to see better support for documenting the generated code in general. Some comments may have target-specific significance (module or function docstrings in Python for example) or some other reason to preserve them (copyright/license notices, links to issues or README) and if I'm generating a library to be consumed by those targets, it's useful to have the option to preserve these comments in the output.

**Comment by RealyUniqueName** [comment]
That's a separate topic. And it's generator-specific. Compiler has built-in define `-D use-rtti-doc` which allows a generator to access doc blocks. Currently only php7 generator uses that to generate doc blocks in the target code.

**Comment by ncannasse** [comment]
I think the current way of injecting with Context.onAfterGenerate is good enough to justify closing the issue, is that ok @Danielku15 ?

**Comment by Danielku15** [comment]
@ncannasse : Yes, I think we can close this issue. with `Context.onAfterGenerate` and `includeFile` most usecases should be covered. 

Thanks to everybody for the discussion.
