### ISSUE TITLE
Extern for js.Object

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#6864]
Also in the theme of missing js externs :), here comes the [Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) one.

Now I know we have Reflect in Haxe but Object does much more (and differently) than Reflect and for those who work only with js, it would be better to have a `js.Object` fresh and ready extern right within Haxe rather than making and maintaining its own...

**Comment by nadako** [comment]
[We have it](https://github.com/HaxeFoundation/haxe/blob/development/std/js/Object.hx) already :-3
