### ISSUE TITLE
Invalid_argument("index out of bounds")

### ISSUE THREAD

**Issue by rakuten** [HaxeFoundation/haxe#6866]
Haxe 3.4.6
OS: Mac 10.13.3
Target: Flash
Command :haxe debug.hxml

I have 2 projects, when buil projects,  one everything is ok, the other got a **Invalid_argument("index out of bounds")** error, but in haxe 3.4.5, the 2 projects is everything ok

debug.hxml
-main ApplicationMain 
--macro lime.Lib.extraParams()
-cp /Users/Rakuten/haxelib/lime/6,2,0
-D lime=6.2.0
-cp /Users/Rakuten/haxelib/away3d/git
-D away3d=5.0.5
-cp /Users/Rakuten/haxelib/fairygui/git/src
-D fairygui=1.4.0
--macro openfl._internal.utils.ExtraParams.include()
-cp /Users/Rakuten/haxelib/openfl/7,1,2/src
-D openfl=7.1.2
-cp /Users/Rakuten/haxelib/msignal/1,2,4
-D msignal=1.2.4
-cp src
-cp ../XY-API/src
-cp ../XY-Core/src
-cp ../XY-Common/src
-cp ../XY-Editor/src
-cp /Users/Rakuten/haxelib/openfl/7,1,2/src/externs/core/flash
-cp /Users/Rakuten/haxelib/openfl/7,1,2/src/externs/core/openfl
-D native-trace
-D tools=6.2.0
-D flash-use-stage
-D no-compilation
-D openfl-flash
-D verbose=1
-D web
-cp /Volumes/HaxeExport/flash
-swf-lib obj/assets.swf
-swf-version 26
-swf /Volumes/HaxeExport/flash/bin/xyscene.swf
-cp /Volumes/HaxeExport/flash/haxe
-debug

**Comment by andyli** [comment]
Same as #6844. Please use 3.4.5 until 3.4.7 is released, or avoid using absolute path for the output file argument (e.g. `-swf`).
