### ISSUE TITLE
Sign Haxe installers

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#6867]
Windows Defender and various antivirus software blocks Haxe installers because of unknown distributor.
Perhaps Haxe Foundation can acquire a certificate to sign installers.
@ncannasse @andyli

**Comment by ncannasse** [comment]
I can do it if someone tell me how to do that exactly :)

**Comment by andyli** [comment]
I've no idea either.

**Comment by RealyUniqueName** [comment]
Me too )
But i have found these pages:
https://developer.apple.com/support/code-signing/

**Comment by gene-pavlovsky** [comment]
I have some hands-on experience with this stuff, commented here
https://github.com/HaxeFoundation/haxe/issues/7720#issuecomment-472476113

**Comment by Simn** [comment]
#7720
