### ISSUE TITLE
Type loss in generic static extension + abstract with @:forward

### ISSUE THREAD

**Issue by restorer** [HaxeFoundation/haxe#6870]
https://try.haxe.org/#444e5

```haxe
using Test.Tools;

class Tools {
    public static function foo<T>(v : T) : T { return v; }
}

class A {
    public function new() {}
}

@:forward
abstract B(A) {}

class Test {
    static function main() {
        var b : B = cast new A();

        $type(Tools.foo(b)); // "B": Ok
        $type(b.foo()); // "A": Type loss
    }
}
```
Is it intented to be? I searched for similar issues:

- https://github.com/HaxeFoundation/haxe/issues?utf8=%E2%9C%93&q=is%3Aissue+abstract+static+extension
- https://github.com/HaxeFoundation/haxe/issues?utf8=%E2%9C%93&q=abstract+static+extension+forward

But not found anything related. Tested on Haxe 4.0.0 (git build development @ 3018ab1)

---
P. S. without `@:forward` everything is ok - https://try.haxe.org/#31971

**Comment by vonagam** [comment]
Fixed now.
