### ISSUE TITLE
setProperty/getProperty implementations on flash target silence exceptions within the getter/setter

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#6871]
The Reflect.setProperty and getProperty implementations on the flash target uses a try catch block to detect missing getter/setters, but do not differentiate between kinds of exceptions. This leads to it catching any exception, even ones that are thrown within the getter/setter.

Maybe a better way would be to catch only exceptions of type `flash.errors.ReferenceError`, to at least limit the scope of improperly caught (and therefore silent) exceptions.

See #5460

**Comment by RealyUniqueName** [comment]
It also makes incorrect assumption that `set_*` and `get_*` methods are always setters and getters:
```haxe
@:keep class Test {
    var field:String; //no setter for this field
    
    function set_field(v) field = 'set_field was invoked';
    
    function new() {}
    
    static function main() {
        var t = new Test();
        Reflect.setProperty(t, 'field', 'hello');
        trace(t.field); // "set_field was invoked", but should be "hello"
    }
}
```
https://try.haxe.org/#99BA8

**Comment by RealyUniqueName** [comment]
> It also makes incorrect assumption that set_* and get_* methods are always setters and getters

This  is still not fixed. PR is welcome, but i doubt it worth the effort given the state of flash as a technology.
