### ISSUE TITLE
Null<UInt> does not work as expected

### ISSUE THREAD

**Issue by zasmarkany** [HaxeFoundation/haxe#6880]
https://try.haxe.org/#43BCC
var i:Null<Int> = null;
trace('Nullable Int: $i', i);    // Nullable Int: null,null
var j:Null<UInt> = null;
trace('Nullable UInt: $j', j);     // Nullable UInt: 0,0

In this case j variable should be null

**Comment by RealyUniqueName** [comment]
It is `null` actually.
If you compare it to `null` it will evaluate to `true`:
```haxe
var j:Null<UInt> = null;
trace(j == null); // true
```
The problem is `toString()` method of `UInt` that method is automatically invoked when you pass `j` to `trace`.

**Comment by zasmarkany** [comment]
No. It is not null. Check other target -> cpp.

**Comment by RealyUniqueName** [comment]
It is `null`: https://try.haxe.org/#6C7d9

**Comment by RealyUniqueName** [comment]
On cpp it's also `null`:
```haxe
class Main {
	static function main() {
		var j:Null<UInt> = null;
		trace(untyped j);
	}
}
```
```
$ haxe -main Main -cpp bin
$ ./bin/Main
Main.hx:4: null
```

**Comment by zasmarkany** [comment]
My results - now I'm confused :)

`
class Main {
	static function main() {
        var j:Null<UInt> = null;
        var isNull:Bool = j==null;
        trace('test: $j', j, (j==null), isNull, untyped j);
	}
}
`

`$ haxe -main Main -cpp bin
$ ./bin/Main
Main.hx:5: test: 0,0,false,false,null`

**Comment by RealyUniqueName** [comment]
I guess cpp generator also contains a bug. On a comparison with null value is casted to int and becomes `0`, which is not equal to `null` obviously hence we get `false` for comparison. But `j` is still `null` at runtime.

**Comment by RealyUniqueName** [comment]
ping @hughsando

**Comment by hughsando** [comment]
Looks like I need a traits entry in https://github.com/HaxeFoundation/hxcpp/blob/master/include/hx/LessThanEq.h#L59 for the case of `hx::Null<T>`
