### ISSUE TITLE
Feature request: static methods inside interfaces

### ISSUE THREAD

**Issue by mayakwd** [HaxeFoundation/haxe#6881]
It's very useful to have a static methods with implementation inside interfaces.
They will reduces the need to declare classes as public which are better to be private.

Example:
```haxe
interface Stream<T> {
   public function filter(predicate:Predicate<T>):Stream<T>;
   public function map<R>(mapper:Mapper<T,R>):Stream<R>;
   ...

   // hiding implementation behind this factory
   public static function of<T>(collection:Iterable<T>):Stream<T> {
      return new StreamImpl<T>(collection);
   }
}

private class StreamImpl<T> implements Stream<T> {
  public function new(collection:Iterable<T>) {
    ...
  }
}
```

**Comment by jdonaldson** [comment]
This really muddies up a classic OOP component.  I doubt it will fly because there are so many other better options.

Why not turn Stream into an [abstract](https://haxe.org/manual/types-abstract.html) that auto casts from Iterables?  Why not a [static extension helper class](https://haxe.org/manual/lf-static-extension.html)?

**Comment by mayakwd** [comment]
Aren't haxe abstracts "muddies up" a classic OOP?
Is haxe following classic OOP principles?

- Abstracts can't have their own fields.
- Iterable is just an example, exploding extensions module with StringStreamImpl, RangeStreamImpl with one static method - is not best solution in my opinion.

**Comment by mayakwd** [comment]
I think this feature intersects with overloading of static extensions methods.

If overloading of static methods will be allowed then instead of bloating module with one-method classes - methods defined in the interfaces could be used only as extension methods.

Either their real implementation could be hidden behind creating of helper class during code generation, then it could be used not only as static extensions, also as regular static methods.

```haxe 
interface Stream<T> [
  public static function of<T>(it:Iterable<T>):Stream<T> { ... }
  public static function of(it:String):Stream<String> { ...  }
}
```

vs

```haxe
class StringStreamImpl {
   public static function of(it:String):Stream<String> {
      return  new StringStreamImpl(it);
   }
}
class IterableStreamImpl {
   public static function of(it:String):Stream<String> {
      return  new StringStreamImpl(it);
   }
}

```

**Comment by bendmorris** [comment]
https://github.com/HaxeFoundation/haxe-evolution/issues/35 seems like a more general solution for this

**Comment by jdonaldson** [comment]
> Aren't haxe abstracts "muddies up" a classic OOP?

How so?  They don't have anything to do with OOP.

**Comment by mayakwd** [comment]
Abstracts have ambiguous naming, abstract is the term tightly related to abstract classes and methods, that is the part of OOP paradigm. Haxe abstracts as far from it as it possible.

I generally do not understand how the classical OOP is related to the haxe and specifically to this issue.

**Comment by mayakwd** [comment]
Or I can use static fabric/extension method inside interface, that could be easily implemented in the same way as static extension or any method declared inside haxe abstracts. It's just a sugar, that reducing amount of code.

**Comment by mayakwd** [comment]
Anyway - streams a bit more complex thing and they can't be implemented upon abstracts (or I just can't do so), it doesn't matter. I don't see nothing criminal in static methods inside interfaces.

**Comment by ncannasse** [comment]
interfaces are pure definition, from a design point of view they should not contain any implementation. If you want to push forward your proposal please resubmit it here https://github.com/haxefoundation/haxe-evolution

**Comment by khalyomede** [comment]
Sorry to bump this up after so many times, I found my issue quite related to the title (wether the actual need is a bit far from what I would like to suggest).

I would like to know if there is any "technical" limitation to why we cannot define static methods as part of an interface?

For the moment, trying to specific static methods in an interface gives this compilation error:

```haxe
interface CanStoreSession {
  public static function get(key: String): String;

  public static function set(key: String, value: String);

  public static function flash(key: String, value: String);

  public static function has(key: String): Bool;

  public static function delete(key: String);

  public static function pull(key: String): String;
}
```

> You can't declare static fields in interfaces

**Comment by kLabz** [comment]
Static fields in interfaces in haxe don't make sense because interface compatibility is inherited while static fields are not.
