### ISSUE TITLE
Function binding question

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#6892]
Hi there!

Just for curiosity, would it be easy to add to the function binding feature the possibility to do this:

```
myCustomEventDispatcher.onChange = myFunc.bind(_.value);
```

if yes, it would be awesome.

If not, do you have any suggestion on how to avoid using a intermediate function (anonymous or not)?
```
myCustomEventDispatcher.onChange = function(e){ myFunc(e.value); }
```

**Comment by Gama11** [comment]
An arrow function is actually just as concise as your suggested syntax:

```
myCustomEventDispatcher.onChange = myFunc.bind(_.value);
myCustomEventDispatcher.onChange = e -> myFunc(e.value);
```

**Comment by zabojad** [comment]
True... From which version of Haxe can we use arrow functions?

**Comment by Gama11** [comment]
Haxe 4 preview 1.

**Comment by markknol** [comment]
I think this issue can be closed, if there are further more questions, let us know!
