### ISSUE TITLE
Haxe PHP: Resource Management fails on runtime

### ISSUE THREAD

**Issue by hereticByte** [HaxeFoundation/haxe#6895]
HAXE Version: 3.4.4, 3.4.7

Dear HAXE team,

as far as I can see, addressing the 'res' folder (holding the resources as files), fails on runtime.

Assumingly this is caused by the hardcoded path. On compileTime it is not equivalent to the path on runTime.

I have prepared a simple example under the following repository. 

[Click here to get to the repository](https://github.com/hereticByte/Issue-Haxe-Php---Resource-Management-failed)

Kind regards
Arnim

**Comment by RealyUniqueName** [comment]
This happens because you use colon `:` in resource name:
```
-resource testResource.txt@:testResource
```
Removing colon fixes it:
```
-resource testResource.txt@testResource
```

**Comment by hereticByte** [comment]
Ah, thank you, Alexander.

I've totally overseen this.
