### ISSUE TITLE
[eval] Unicode issue when splitting string

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#6897]
```haxe
var inChars   = 'àáâãäçèéêëìíîïñòóôõöùúûüýÿ'.split('');
var outChars  = 'aaaaaceeeeiiiinooooouuuuyy'.split('');
trace(inChars.length, outChars.length);
```
Test case online https://try.haxe.org/#9B7E2 (works as expected)
In Haxe 3 --interp it logs `26,26` (works as expected)
In Haxe 4 Preview 3  --interp it logs `52,26` (unexpected length of first array)

**Comment by ncannasse** [comment]
Should be straightforward now with dual string implementation

**Comment by Simn** [comment]
Yes this works fine on the unicode branch. I still have no idea why it worked on the old interpreter, but whatever...

**Comment by axelhuizinga** [comment]
Are anywhere unicode builds available?

**Comment by Simn** [comment]
Not yet, but I'll merge the branch soon.

**Comment by Simn** [comment]
The branch has been merged and the test passes now.

**Comment by markknol** [comment]
Thanks for this! You rock!
