### ISSUE TITLE
Import cs.Lib "Type not found" Error

### ISSUE THREAD

**Issue by Doppp** [HaxeFoundation/haxe#6898]
The moment I do an import for the `cs.Lib` library in my class, I get the following error:

![code_2018-03-09_00-38-44](https://user-images.githubusercontent.com/627410/37163289-56da3f64-2332-11e8-89ac-47ea65fce80a.png)

The `Lib.hx` library imports `cs.system.Type` but somehow cannot find it.

**Comment by nadako** [comment]
This type is supposed to come from .NET system libraries. Could it be that you're trying to import `cs.Lib` when not compiling for C# (one common example would be to try using it in a macro context).

**Comment by Doppp** [comment]
Ah okay. So if I don't intend to compile for C# this is unnecessary?
