### ISSUE TITLE
Enum generation on C# should have C# enum tags

### ISSUE THREAD

**Issue by jonigata** [HaxeFoundation/haxe#6899]
In #6119, enum constructer ideitifiers(`getTag()`) are string and indices are int.
From the viewpoint of interoperability, I think it's type weakness is vulnerable to future modification and code readability.

It would be robust if generated code is:
```
public class E {
      enum Tags {
           A = 0,
           B = 1,
      }
}

public class A : E {
      Tags getTag() { return (Tags)index; }
}
```

**Comment by nadako** [comment]
Something like this might make sense for the sake of better interop indeed, although the `getTag` method is specifically used for `Type.enumConstructor`, so it should be something different. BTW I'm pretty sure one can generate this kind of native c# enum with macros and have that `(Tags)index` as an extension method. So I'm not sure whether we should implement this in the compiler.

**Comment by Simn** [comment]
Let's not mess with that, we have enough other problems already.
