### ISSUE TITLE
[php7] "untyped _thing" still used in std 

### ISSUE THREAD

**Issue by postite** [HaxeFoundation/haxe#6900]
hello ! 
testing the php7 target on 4 preview3.

compiler warn for deprcated use of untyped __call__ that still remain in the std lib like in :
std/DateTools.hx:147: characters 19-47 : Warning : untyped __call__ is deprecated. Use php.Syntax instead
and 
std/sys/Http.hx:40: characters 26-79 : Warning : untyped __call__ is deprecated. Use php.Syntax instead.

**Comment by postite** [comment]
@RealyUniqueName  great!

**Comment by RealyUniqueName** [comment]
Thanks for the report!
