### ISSUE TITLE
[js] [4.0.0-preview.3] Compilation error with if-statement inside Promises + arrow function

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#6902]
Hey ;)
Oh, so sad, but something broken with short lambdas + Promises. 

Here is an example:
http://try-haxe.mrcdk.com/#f5750

But if replace arrow function with default anonymous syntax, then example will be correctly compiled.

**Comment by nadako** [comment]
Funnily this is kind of expected, because `(args)->body` is is the same as  `function(args) return body`, so it treats the empty block in the `if` as an empty object being returned. Then it stumbles upon `else` body which is a block with an expression and its last expression (the trace) is indeed `Void`, not an empty object, hence the error.

> But if replace arrow function with default anonymous syntax, then example will be correctly compiled.

Not if you do the same as the compiler: http://try-haxe.mrcdk.com/#b9E78

Not sure right now if we can/should do something about it.

**Comment by dmitryhryppa** [comment]
Well, I have similar problems without empty if-block:
![image](https://user-images.githubusercontent.com/4466595/37338697-e4dfba32-26c0-11e8-9876-afbe0d1b201e.png)

Here is Promise inside Promise cause the same problems:
http://try-haxe.mrcdk.com/#4D3Af

It is a bit strange, because this kind of code work fine in JS/TS with Promises. So.. Why Haxe can't? 
It is important, because short lambdas is useful on JS traget, because JS code and libraries are full of Promises.

**Comment by montibbalt** [comment]
In the screenshot above, on line 23, change the last part to `.then(function(doc:DocumentSnapshot) return {`  

I suspect you'll have the same type error _without_ the short lambda; from what I can tell it looks as though the if-block is returning `Void`, but then the else-block is returning `Promise<Void>`.

Conceptually `Promise<Void>` makes little sense (to me) anyway but that's a separate topic altogether

**Comment by dmitryhryppa** [comment]
Sorry, I don't get it. Promises works fine without short lambdas:
http://try-haxe.mrcdk.com/#7c99B

**Comment by montibbalt** [comment]
Those are not the same thing: http://try-haxe.mrcdk.com/#608a2

**Comment by dmitryhryppa** [comment]
Yes, I understand this.
But I can't understand why do I need to use `function(v:Dynamic):Void return { }` to fix this issue if I can use regural anonymous function syntax? I know that I can just use something like:
```
.then(function(v:Dynamic):Void { 
    ....
});
```
But I use lambdas to avoid this syntax. And they not works as I expected. I created issue about this. 

I understand that lambdas returning some expression. 
But I don't understand why lambdas works fine with any expression in TS, JS, C# and C++, and don't work with Haxe. 

This will work in JS:
```
let promise = new Promise((resolve, reject) => {
    if (some instruction) {
        setTimeout(() => {
            resolve("result");
        }, 1000);
    } else {
         reject();
    }
});
```
And the same code with lambdas will not work in Haxe. I dont want to use full syntax, I want short lambdas.
And this is a problem that described in this issue.

**Comment by back2dos** [comment]
> But I can't understand why do I need to use `function(v:Dynamic):Void return { }` to fix this issue if I can use regural anonymous function syntax?

The point is this: `(v:Dynamic)->body` is equivalent to `function (v:Dynamic) return body`. So using the arrow syntax is equivalent to putting the return statement there, which will not fix anything, but rather yield the exact same error you're experiencing.

Perhaps we could not make an implicit `return` if the body is a block? FWIW that's how JavaScript does it.

**Comment by Simn** [comment]
This is failing as expected as @nadako explained.
