### ISSUE TITLE
Overloading assignment and compound assignment operators is silently ignored

### ISSUE THREAD

**Issue by matrefeytontias** [HaxeFoundation/haxe#6903]
https://try.haxe.org/#D769b

**Comment by RealyUniqueName** [comment]
duplicates #5738

**Comment by back2dos** [comment]
Well, not quite. This issue could quite easily be resolved by issuing an error message that `=` cannot be overloaded. The other one is less trivial.

**Comment by matrefeytontias** [comment]
I'd rather have it allow overloading the different assignments operators really. I didn't know about the other issue, but I guess that while I do agree with what has been said in it, this one can become a different one (the fail shouldn't be silent).

**Comment by Justinfront** [comment]
@matrefeytontias I believe also the 'precedence of operators' is also predefined so if you where to try abstracting around a float and swap `+` and `*` around it would not work as you might expect, because `*` would still have precedence.
