### ISSUE TITLE
Bug with pattern matching & final

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/haxe#6905]
The following code does not compile

```haxe
class Main {
	static final i = 1;
	static function main() {
		switch ("test") {
			case "b": trace("B");
			case i: trace(i);
		}
	}
}
```

`Main.hx:6: characters 9-10 : Int should be String`

It behaves the same with `static inline var i = 1`

Using `case var i` fixes it but seems weird with GADT ( `case A(var i)`).

**Comment by RealyUniqueName** [comment]
I think it's by design. It's allowed to use an identifier of a `static inline` (and now `final`) variable in a `case`.

**Comment by Simn** [comment]
Indeed, this works as designed.
