### ISSUE TITLE
Implicit weird unification?

### ISSUE THREAD

**Issue by FrancisBourre** [HaxeFoundation/haxe#6911]
Interface goal is not only to define a contract but to define a unique type as well.
So, I would not expect this code to compile. 
https://try.haxe.org/#50358

**Comment by back2dos** [comment]
This is valid. Any subtype, i.e. a subclass of a class or (as in this case) the implementor of an interface may choose to accept "wider" types in its methods, see [contravariant method argument types](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Contravariant_method_argument_type). It is therefore valid for `LogContainer` to accept `LoggerDef` even though `ILogContainer` accepts only `ILogger`.

Now, if you upcast `LogContainer` to `ILogContainer` then it fails as you would expect: https://try.haxe.org/#6ad1d

**Comment by nadako** [comment]
Hmm, shouldn't the wider type still be constrained to `ILogger` as a requirement for `ILogContainer` implementation? @ncannasse

**Comment by back2dos** [comment]
Why though? ```LoggerDef->Void``` unifies with ```ILogger->Void```, so the [LSP](https://en.wikipedia.org/wiki/Liskov_substitution_principle) is honored and all is fine.

**Comment by aliokan** [comment]
Interesting question :)

**Comment by Simn** [comment]
Unfortunately, the original try.haxe is no longer available and I can't infer from the description what this was actually about, so I'll close the issue. If anyone remembers what the problem here was, feel free to comment and I'll reopen.
