### ISSUE TITLE
IE8 does not support Object.defineProperty on non DOM objects

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#6918]
The HaxeError uses `Object.defineProperty` to define the `message` property, but it cannot work in IE8, 

[js/Boot.hx#L40-L42](https://github.com/HaxeFoundation/haxe/blob/development/std/js/Boot.hx#L40-L42)

**Comment by back2dos** [comment]
Perhaps this should depend on the `js-es` flag.

**Comment by RealyUniqueName** [comment]
@ncannasse Do we support IE8? It's not tested in our CI.

**Comment by Simn** [comment]
I'm making an executive decision to not support IE8. \o/

**Comment by back2dos** [comment]
FFR, there's a [polyfill for IE8](https://gist.github.com/afuggini/85b02644491f130879a8e789a5b1cea8) (and other browsers).

**Comment by ncannasse** [comment]
I think a simple fix would be to test whereas Object.defineProperty is defined before calling. Doesn't hurt much and prevents breaking backward compatibility.

**Comment by R32** [comment]
I feel that it is not simple, becourse the IE8 has `Object.defineProperty` but when uses on non-dom object you will get an error and then exit

In my `IWebBrowser2` project, I actually found that `js.Boot` can be overwritten from outside, So I could copy `std.js.Boot.hx` to the outside and do some hacks:
 
> Note: this hack still has problems in errors catching.

```haxe
#if (js_es == 3 || no_stack_trace)
@:native("Error")
private extern class HaxeError {

	var val:Dynamic;
	
	function new(val:Dynamic);

	public static inline function wrap(val:Dynamic):js.lib.Error return new js.lib.Error(val);
}
#else
// origin HaxeError
#end
```
example:

```haxe
class Main {
	static function main() {
		try {
			throw "hello world!";
		} catch(e: Dynamic) {                // must be keep :Dynamic type
			var e = js.Syntax.code("e"); // prevent compiler wrap something.
			trace(e);
		}
	}
}
```
Compile it with `-D js-es=3`:

```js
(function (console, $global) { "use strict";
var Main = function() { };
Main.main = function() {
	try {
		throw new Error("hello world!");
	} catch( e ) {
		console.log("src/Main.hx:7:",e);
	}
};
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}}, {});
```
