### ISSUE TITLE
current Http implementation: Chaining doesn't work as it used to

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#6919]
Using current git version on PHP target.
This used to be possible:
```haxe
var req = new Http(url).addHeader("Content-Type", "bla");
req.request();
trace(req.responseHeaders);
```
In current implementation `addHeader` is defined only in ` haxe.http.HttpBase` with `return this` for chaining. So you get a `HttpBase` which has no `responseHeaders` field (defined in `sys.Http`), resulting in error.

**Comment by Simn** [comment]
The chaining API will be deprecated in Haxe 4.
