### ISSUE TITLE
[display] position of field access in calls off by one

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6923]
```haxe
class Main {
    static function main() {
        trace("test".length);
    }
}
```

When you hover over the first character of the field (`l`), it highlights the string instead:

![](https://i.imgur.com/Rooy5KI.png)

```
>haxe --display Main.hx@65@position
<list>
</list>
```

When you hover over the closing `)`, it's also off by exactly one:

![](https://i.imgur.com/o68HHNb.png)

This affects `@position` as well as `@type`, and it only happens within calls, so this works fine:

![](https://i.imgur.com/XEcC4yo.png)

The positions might be handled incorrectly in the parser - Simn fixed a bunch of issues like this back in the day, e.g. https://github.com/HaxeFoundation/haxe/commit/86f789131acf6ffda373d0fdf06f02a5d1c5d8c8#diff-d46072963fbbe4703dc5678c36e89603.

**Comment by Simn** [comment]
This seems to reproduce outside calls as well. Hovering the `l` on `"test".length` displays String instead of Int.
