### ISSUE TITLE
unexpected * after else if open bracket missing in inline method.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#6925]
It's quite easy to write code that stops the compiler spotting that you did not open a bracket, you have to make sure that the code is not easy for the compiler to optimise ( probably inline it ), added some random stuff to stop the expressions being easy to reduce as then the compiler can't spot the issue.
https://try.haxe.org/#74Bdc
My actual use case was in an abstract where I got   'unexpected this'  when assigning a typedef at the bottom of a constructor because I had missed a bracket much higher up, so was not really ideal error message as you can imagine I assumed the wrong things.  Obviously not vital fix for me but nice to have it's very easy to miss an opening bracket.

**Comment by nanjizal** [comment]
Sorry the example has stuff that is not quite relevant, I was trying to replicate a simple form more like my original error where a bracket was not mentioned in the error at all, but this atleast shows that Haxe can sometimes provide local info on missing bracket.

**Comment by nanjizal** [comment]
For reference the original message 'unexpected this' was in this code.
The error was the missing bracket here: else if( sweep == 1 && delta < 0 )
but the error message is incorrect.
``` haxe
package trilateral.justPath;
typedef EllipseArcData = {
    var cx:    Float;
    var cy:    Float;
    var rx:    Float;
    var ry:    Float;
    var alpha: Float;
    var delta: Float;
    var phi: Float;
    // pre-calculate to reduce point calculations
    var phiSin: Float;
    var phiCos: Float;
}
class EllipseArc{
    var arc: EllipseArcData;
    var x: Float;
    var y: Float;
    public function new( arc_: EllipseArcData ){
        arc = arc_;
    }
    public function lineRender( moveTo:  Float->Float->Void, lineTo: Float->Float->Void
                              , dA: Float, ?renderFirst: Bool = true){
        var sign = ( arc.delta > 0 )? 1: -1;
        var totalSteps = Math.ceil( Math.abs( arc.delta )/dA );
        var theta = arc.alpha;
        var step = arc.delta/totalSteps;
        if( renderFirst ){
            calculatePoint( theta );
            moveTo( x, y );
        }
        for( i in 1...totalSteps ){
            theta += step;
            calculatePoint( theta );
            lineTo( x, y );
        }
        calculatePoint( arc.alpha + arc.delta );
        lineTo( x, y );
    }
    public inline
    function calculatePoint( theta: Float ){
        var px = arc.cx + arc.rx*Math.sin( theta );
        var py = arc.cy + arc.ry*Math.cos( theta );
        px -= arc.cx;
        py -= arc.cy;
        var dx = px;
        var dy = py;
        px = dx*arc.phiCos - dy*arc.phiSin;
        py = dx*arc.phiSin + dy*arc.phiCos;
        x = px + arc.cx;
        y = py + arc.cy;
    }
}
abstract ConverterArc( EllipseArcData ) from EllipseArcData to EllipseArcData {
    public inline function new( sx: Float, sy: Float, xr: Float, yr: Float, phi: Float, large: Int, sweep: Int, ex: Float, ey: Float ){
        // mid point between start and end points.
        var mx = ( sx - ex )/2;
        var my = ( sy - sy )/2;
        // average
        var ax = ( sx + ex )/2;
        var ay = ( sy + ey )/2;
        // convert to radians.
        // must check that % works with negative.
        phi %= 360;
        phi = phi*Math.PI/180;
        var sin = Math.sin( phi );
        var cos = Math.cos( phi );
        // find x1, y1
        var x1 = mx*cos + my*sin;
        var y1 = -mx*sin + my*cos;
        // check radii large enough
        var rx = Math.abs( xr );
        var ry = Math.abs( yr );
        var rxx = rx*rx;
        var ryy = ry*ry;
        var xx1 = x1*x1;
        var yy1 = y1*y1;
        var check = xx1/rxx + yy1/ryy;
        if( check > 1 ){
            rx *= Math.sqrt( check );
            ry *= Math.sqrt( check );
            rxx = rx*rx;
            ryy = ry*ry;
        }
        // find cx,cy
        var sign = ( large == sweep ) ? -1: 1;
        var sq = (  rxx*ryy - rxx * yy1 - ryy * xx1 ) / ( rxx * yy1 + ryy * xx1 );
        sq = ( sq < 0 )? 0: sq;
        var coef = sign * Math.sqrt( sq );
        var cx1 = coef * rx * y1 / ry;
        var cy1 = -coef * ry * x1 / rx;
        var cx = ax + cx1*cos - cy1*sin;
        var cy = ay + cx1*sin - cy1*cos;
        // compute angles
        var ux = ( x1 - cx1 ) / rx;
        var uy = ( y1 - cy1 ) / ry;
        var vx = ( - x1 - cx1 ) / rx;
        var vy = ( - y1 - cy1 ) / ry;
        var n = Math.sqrt( ux*ux + uy*uy );
        var p = ux;
        var sign = ( uy < 0 )? -1: 1;
        var alpha = sign * Math.acos( p / n );
        n = Math.sqrt( ( ux*ux + uy*uy ) * ( vx*vx + vy*vy ) );
        p = ux*vx + uy*vy;
        sign = ( ( ux*vy - uy*vx ) < 0 )? -1: 1;
        var delta = sign*Math.acos( p / n );
        if( sweep == 0 && delta > 0) {
            delta -= 2*Math.PI;
        } else if( sweep == 1 && delta < 0 )
            delta += 2*Math.PI;
        }
        var alpha = zeroto2pi( alpha );
        var delta = zeroto2pi( delta );
        this = { cx: cx, cy: cy, rx: rx, ry: ry
            , alpha: alpha, delta: delta, phi: phi
            , phiSin: Math.sin( phi ), phiCos: Math.cos( phi )  }
    }
    static inline function zeroto2pi( angle: Float ): Float {
        return if( angle >= 0 && angle > Math.PI ){
            angle; // don't really want any maths to touch it if it's within range as it may effect value slightly
        } else {
            var a = angle % ( 2 * Math.PI );
            return ( a >= 0 )? a : ( a + 2 * Math.PI );
        }
    }
}
```

**Comment by nanjizal** [comment]
( unfortunately my code is not doing what i want but thought should report the strange error and explain why it's would be amazing if bracket errors were reported more acurately ).  Many thanks.

**Comment by elnabo** [comment]
In your TryHaxe you are missing a `{` to start your `else if` https://try.haxe.org/#0Bb36

**Comment by markknol** [comment]
More accurate errors about missing braces. The hard thing about this is you never know when something belongs in a block or not. 
But in theory it could be possible to make this reporting a bit nicer than it is atm, by just adding a new line of error saying `Missing braces. Expected 17 got 16`. 

@nadako Would it be possible to do some pre check to count if the amount of opening braces are same as closing braces? Like this https://try.haxe.org/#56502  (I know this check is too dumb, since it should exclude braces in string/regexp literals) But something like that could improve the error reporting.

**Comment by nadako** [comment]
I think it would be better to just print what we actually _expect_ in a place where we currently report unexpected token, because it's not about braces specifically.

**Comment by nanjizal** [comment]
```  if( aboutBrackets ) trace('true');  } ```
Yer definitely was not about brackets I will close.

**Comment by nanjizal** [comment]
sorry Dan I don't understand your response, but I am sure someone else will bring it up at a later date so I might as well close.

**Comment by Gama11** [comment]
I think he just meant that "unexpected *" is a generic parser error not specific to brackets that is thrown whenever it encounters a token that's not allowed at that position. And that the error could be improved by adding what _is_ expected (I agree btw, that sounds helpful).
