### ISSUE TITLE
Empty switch default has null_pos

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6932]
When doing the following:

```haxe
enum E {
   A;
   B;
   C;
}

class Main {
     static function foo( v : E ) {
          switch( v ) {
          case A,B: trace(v);
          default:
          }
     }
}
```

The "default" expression is a TBlock [] with `null_pos` instead of the Main.hx correct line, which makes us lose the cursor when debugging with HL (or JS source maps I suppose).

**Comment by Simn** [comment]
I'm not sure which position this should have because the block doesn't exist in syntax. There used to be issues with this because the position was too wide and then caused buggy hover-highlighting in IDEs. I think I changed it to `null_pos` to prevent that.

**Comment by ncannasse** [comment]
The block does exists, since EMatch as a Some (EBlock[]) parsed I think (or else it would complain about missing default)

**Comment by RealyUniqueName** [comment]
It's not `null_pos` anymore (with latest dev haxe):
```
 107- 154 	      TSwitch
 114- 115 	        TParenthesis
 114- 115 	          TEnumIndex
 114- 115 	            TLocal v
 125- 126 	          0
 127- 128 	          1
 130- 135 	            TCall
 130- 135 	              TField trace
 130- 135 	                TTypeExpr haxe.Log
 136- 137 	              TLocal v
 130- 135 	              TObjectDecl
  -1-  -1 	              fileName
 130- 135 	                "src/Main.hx"
  -1-  -1 	              lineNumber
 130- 135 	                11
  -1-  -1 	              className
 130- 135 	                "Main"
  -1-  -1 	              methodName
 130- 135 	                "main"
 142- 149 	            TBlock // this block
```
So, I assume this is fixed.
