### ISSUE TITLE
Abstracts, inlining and properties

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#6940]
More a question than an actual issue:

If I declare an abstract type with a property and I inline its accessors:
```
abstract MyAbstract(Array<Int>) from Array<Int> to Array<Int> {
	public var state (get,set) : Int;
	private inline function get_state() : Int {
		return this[0];
	}
	private inline function set_state(v : SystemIndex) : Int {
		this[0] = v;
		return this[0];
	}
}
```
I would expect the generated js not to define any getState nor setState method. However, what it generates in js is:
```
var MyAbstract_$Impl_$ = {};
MyAbstract__$Impl_$.get_state = function(this1) {
	return this1[0];
};
MyAbstract__$Impl_$.set_state = function(this1,v) {
	this1[0] = v;
	return this1[0];
};
```
Erf... Why couldn't we inline accessors at least in an abstract type?

**Comment by zabojad** [comment]
@nadako maybe you would have an answer to that :)...

**Comment by zabojad** [comment]
Actually, I'm realising it is worse than what I thought...

If I declare:
```
abstract Toto(Array<Int>) from Array<Int> to Array<Int> {
	public inline function getState() : Int {
		return this[0];
	}
}
```
So.... Without property getters/setters involved,

It translates in js to:
```
var Toto_$Impl_$ = {};
Toto_$Impl_$.__name__ = ["Toto_Impl_"];
Toto_$Impl_$.getState = function(this1) {
	return this1[0];
};
```
Is it me or is it a bug?

I'm still using haxe v3.4.4

**Comment by zabojad** [comment]
And indeed @Gama11, it actually inlines only if I tag the methods with `@:extern`... Not really obvious :confused:

**Comment by nadako** [comment]
I don't get what's the problem here? The methods should be inlined properly on the calling side? And they are of course also normally generated in the output when you don't DCE it with `-dce=full` or a `@:dce` metadata.

**Comment by zabojad** [comment]
@nadako Actually you are right, they are inlined in the calling side. Then I do not understand we do not clean automatically their generated code but require to use those dce instructions...

But in the end, my bad, inlining is actually working fine here...

**Comment by ncannasse** [comment]
Are you compiling with `-dce full` ? If not, only std code is optimized/removed by default.
