### ISSUE TITLE
Generated code are wrong

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#6942]
```haxe
class Test {
    static function main() {
        trace(-First);
    }
}

@:enum private abstract ColorRectangleQuadrant(UInt) from UInt to UInt {
 var First = -1;
}
```
results:
```javascript
// Generated by Haxe 3.4.4
(function () { "use strict";
var Test = function() { };
Test.main = function() {
 console.log(--1);
};
Test.main();
})();
```
```javascript
// Generated by Haxe 4.0.0 (git build master @ 2344f23)
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	console.log("Test.hx:4:",--1);
};
Test.main();
})();
```

**Comment by RealyUniqueName** [comment]
It's not js-specific issue. Happens for any target.

**Comment by ncannasse** [comment]
I think we had an optimizer to take care of this. I guess this has been
moved to analyzer, hence the regression.
Anyway, this should maybe be done at sanitize_expr time

**Comment by Simn** [comment]
We cannot rely on the optimizer as long as `--no-opt` exists. So I agree this should be fixed in `sanitize_expr` by changing it to `-(-1)`.

I don't want to make any other change here for the time being.
