### ISSUE TITLE
[lua] FileSystem.exists() does not work with directories.

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#6946]
Executing FileSystem.exists() on a directory always returns false (on Windows, don't know about other OSes).  This affects Haxe 3.4.7 and Haxe 4 nightly.

I guess the problem is that the exists method tries to open the path as a [regular file](https://github.com/HaxeFoundation/haxe/blob/development/std/lua/_std/sys/FileSystem.hx#L35) which apparently fails. 

On StackOverflow I found some entries that suggest to abuse Os.rename() and use the same value for old and new name. The method will fail if the file/folder to rename does not exist and will report success otherwise but actually don't do anything on the FS. I don't know if this would also works for read-only files.

So the exists() function could be changed to either:

```haxe
	public inline static function exists( path : String ) : Bool {
                return path == null ? false : lua.Os.rename(path, path).success == true;
        }
```

or

```haxe
	public static function exists( path : String ) : Bool {
		if (path == null) return false;
		else {
			var f = Io.open(path);
			if (f == null)
                             return lua.Os.rename(path, path).success == true;
			else {
				f.close();
				return true;
			}
		}
}
```

**Comment by sebthom** [comment]
This bug is also the reason why FileSystem.createDirectory() does not working recursively on Lua .

**Comment by jdonaldson** [comment]
I just pushed a fix for this that should be more general.  Can you try out a nightly and see if it works for you?

I'm trying to get Lua tested properly on windows, but that is not likely to get solved in the near term.

**Comment by sebthom** [comment]
Works! Thanks!!
