### ISSUE TITLE
`?final` parses as the first field but not as subsequent fields

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6947]
Tested haxe version: e3568be

```haxe
{
  ?final x:Int; // fine
  ?final y:Int; // unexpected ?
}
```

**Comment by ncannasse** [comment]
What's  `?final` ? is that a thing ? Do we allow `?var` as well ?

**Comment by ibilon** [comment]
Surprisingly `?var` parses https://try.haxe.org/#a9d0B, though it doesn't do anything.

**Comment by nadako** [comment]
`?var/final` shouldn't parse as per current grammar, but there's an intention of adding `var?` and `final?` for specifying optional fields using the class notation.

**Comment by ncannasse** [comment]
We should no allow either, the official "long syntax" for optional fields is  `@:optional [final|var] name : Type`. We could eventually add the following for Haxe 4 `var ?name : Type` but not a `?` before `var` :)

**Comment by nadako** [comment]
Yes, that's what I'm talking about, see #6707
