### ISSUE TITLE
Bool as const type parameter

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6948]
Per the manual: https://haxe.org/manual/macro-generic-build.html

> Haxe allows passing _**constant expression**_ as a type parameter if the type parameter name is Const.

and "constant expression" links to https://haxe.org/manual/expression-constants.html listing Bool as one of them. But in fact `value:MyType<true>` won't pass the parser. Not sure which one (implementation or doc) is wrong.

**Comment by Simn** [comment]
That should work.

**Comment by kevinresol** [comment]
I think it is a parser problem:

http://try-haxe.mrcdk.com/#0a620

```haxe
class Test {
  static function main() {
    var gen:Gen<'true'> = null; // ok
    var gen:Gen<true> = null; // Unexpected =
  }
}

@:generic
class Gen<@:const T>{}
```

**Comment by Simn** [comment]
Yes it is, the parser only considers Const but true/false are Kwd. Should be easy to fix.
