### ISSUE TITLE
[neko] Reflect.setProperty silently ignores setters removed by DCE

### ISSUE THREAD

**Issue by ttencate** [HaxeFoundation/haxe#6949]
Minimal example:

```haxe
class Test {

  public static function main() {
    var test = new Test();
    trace("Setting f");
    Reflect.setProperty(test, "f", 37);
    trace("Done!");
  }

  public function new() {
  }

  public var f(default, set): Int;

  private function set_f(value: Int): Int {
    trace("set_f", value);
    return value;
  }
}
```

When running with standard DCE, the output is as expected:

    $ haxe -main Test -neko Test.n && neko Test.n
    Test.hx:5: Setting f
    Test.hx:20: set_f,37
    Test.hx:7: Done!

But when enabling full DCE on neko, the setter call just _silently_ doesn't happen:

    $ haxe -main Test -neko Test.n -dce=full && neko Test.n
    Test.hx:5: Setting f
    Test.hx:7: Done!

I'm okay with DCE + reflection resulting in a crash if you're trying to call eliminated functions, but ignoring the call silently is rather unexpected and can be a source of hard to find bugs.

In contrast, the cpp build crashes loudly and clearly:

    $ haxe -main Test -cpp test -dce=full && ./test/Test 
    haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.407" -Dhxcpp_api_level="331" -Dsource-header="Generated by Haxe 3.4.7" -I"" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/share/haxe/std/"
    Test.hx:5: Setting f
    Error : Invalid field:f

---

[edit] In fact, on neko, `Reflect.setProperty` silently ignores _any_ missing property. If I read the [docs](https://api.haxe.org/Reflect.html#setProperty) correctly, the behaviour is not defined for this case. So causing an exception or abort on neko would still be according to the contract.

**Comment by Simn** [comment]
This looks like a normal difference between static and dynamic targets. You can set any field on dynamic targets, whereas static targets typically yell at you.

**Comment by ncannasse** [comment]
Yes, Reflect.setProperty implies Reflect.setField is the field is not a property, so it works as intended here.

**Comment by filt3rek** [comment]
Could there be a warning or something like that please ?

**Comment by Gama11** [comment]
There couldn't really be a warning without changing the specification of `setProperty()`, and that seems like a bad idea.
