### ISSUE TITLE
Invalid code generation with @:const type parameters and some literals

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#6952]
```haxe
class Main {
	public static function main() {
		new Test<"hello world">().foo();
	}
}

@:generic class Test<@:const T> {
	public function new() {}
	public function foo() {
		trace(T);
	}
}
```

This breaks on multiple targets. JS:

```
        new Test_$Shello world().foo();
                         ^^^^^

SyntaxError: Unexpected identifier
```

Java:

```
javac: invalid flag: src/haxe/root/Test_Shello
Usage: javac <options> <source files>
use -help for a list of possible options
Compilation error
Native compilation failed
Error: Build failed
```

Etc.

**Comment by Gama11** [comment]
This is not just an issue with strings, regex literals are causing issues too:

```haxe
class Main {
	public static function main() {
		new Test<~/a/>().foo();
		new Test<~/b/>().foo();
	}
}

@:generic class Test<@:const T> {
	public function new() {}
	public function foo() {
		trace(T);
	}
}
```

On JS, this prints:

```
source/Main.hx:11: EReg { r: /a/ }
source/Main.hx:11: EReg { r: /a/ }
```

**Comment by Gama11** [comment]
The first code example here now works, but the second one is still broken, so this should probably be reopened?

**Comment by bendmorris** [comment]
Added a test locally which is passing; I'm seeing `unit_issues_Issue6952TestClass_Expr` for the regex case, which is valid code. It's not a reasonable way to name that generic variant, but that seems like a separate issue.

**Comment by Gama11** [comment]
The second issue is more about the incorrect trace output of the second instance (`/a/` instead of `/b/`).

**Comment by bendmorris** [comment]
Yeah, they would both map onto a name ending with `_Expr` so they'd be sharing the same underlying instance, I guess whichever was generated first.

**Comment by Simn** [comment]
Maybe we should just disallow regexes as type parameters.

**Comment by bendmorris** [comment]
Nah, I'll just fix them :wink:
