### ISSUE TITLE
haxe.Http not using onError for some errors

### ISSUE THREAD

**Issue by chrisgordon** [HaxeFoundation/haxe#6954]
It seems like this class is not always passing errors through onError when the request() method is called.
For example, if given a hostname that isn't valid OR user is disconnected, an exception is thrown in the console, eg net::ERR_NAME_NOT_RESOLVED. Yet, the onData() callback is still called, with an empty string

**Comment by Simn** [comment]
What target are you using?

**Comment by chrisgordon** [comment]
Sorry, forgot to mention: javascript.

**Comment by Simn** [comment]
Not sure what we can do here. There's already a [try catch](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpJs.hx#L101) around the request opening which calls onError.

**Comment by chrisgordon** [comment]
It's actually line 121 where the exception occurs

**Comment by Simn** [comment]
Ah, then I guess we should expand the range of that try catch.

**Comment by chrisgordon** [comment]
Note that this is still an issue in Haxe 4.x, and now, if OFFLINE when sending the request, an exception is thrown instead. Thus onData/onError are never called.

3.x behavior:
onData callback is called with empty string as the parameter, so it's somewhat easy to deal with
4.x:
An exception is thrown during onreadystatechange:
```
Uncaught TypeError: Cannot read property 'hxBytes' of null
    at Function.haxe_io_Bytes.ofData
    at XMLHttpRequest.onreadystatechange 
    at XMLHttpRequest.sentryWrapped 
```

**Comment by RealyUniqueName** [comment]
@chrisgordon 
That exception stack points to the line, which already contains a null check in the latest development Haxe. But there is no null check in the release version.
Could you please check if the latest nightly build fixes it for you? https://build.haxe.org/builds/haxe/

**Comment by RealyUniqueName** [comment]
Closing due to lack of feedback.
