### ISSUE TITLE
Top down inference for abstract "from" (not @:from)

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#6961]
http://try-haxe.mrcdk.com/#8113e

```haxe
// Test.hx
class Test {
  static function main() {
    var t:T = {e:A}; // ok, top-down inference figured out what is "A"
    var t:ET = {e:A}; // Unknown identifier : A
    var t:ET = [{e:A}]; // but this works...
  }
}

typedef ET = haxe.extern.EitherType<T, Array<T>>;

// T.hx
enum E {A;}
typedef T = {e:E};
```

Follow up https://github.com/HaxeFoundation/haxe/issues/3499#issuecomment-75466248 : Could it do top-down inference for each of the `from` according to the declaration order?

**Comment by Simn** [comment]
I'm still not sure if we want to do this. This kind of type choice gets pretty complicated.

**Comment by vonagam** [comment]
`A` in `var t:ET = {e:A};` is correctly identified as part of `enum E` for me on version 4.1.

**Comment by kevinresol** [comment]
OP worked since `4.0.0-preview.5`. Closing.
