### ISSUE TITLE
[Suggestion] A way for requesting a function to be inlined at call location

### ISSUE THREAD

**Issue by YellowAfterlife** [HaxeFoundation/haxe#6964]
A pretty common thing, even for [standard library](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/io/Input.hx#L229-L247) - you have a pair of functions of similar purpose and one does what other does plus a little extra (like handling sign bit in that case). Or have functions that are actively used inside of other functions (potentially benefiting from being inline there) while being used normally from "external" code.

But you cannot - a function is either inline (hinted or forced with `@:extern`) or it isn't - the best you can do is making a separate "this one function but inline" function, then have the "normal" version to call the inline version, and have other functions call either normal or inline version. Or, well, duplicate the code, and hope that no one forgets to update both versions down the line.

So I would like to propose a syntax structure to nudge the compiler towards inlining a function call at place of it's use. Considering the current syntax, I think having `inline <TCall>` as a prefix "operator" would have worked - `inline` keyword never occurs in this context so this wouldn't be ambiguous, and I think it would be clear enough what's happening on a glance. Thus the above could be written as
```haxe
	public function readInt16() : Int {
		var n = inline readUInt16();
		if( n & 0x8000 != 0 ) ...
```

Further considerations:

- Also allowing this with instantiation could allow for an interesting setup where small classes could be conditionally inlined in places of intensive use instead of having to utilize pooling (or carelessly throwing instances straight into GC each call)

   As far as I know, the only two existing ways of doing this are [having a non-inline-able function in your class](https://try.haxe.org/#Ee0DC) that is called to prevent it from being inlined (this smells of hacks) or having separate normal/inline-able versions of the class (this also smells of hacks).

**Comment by bendmorris** [comment]
IMO this would be very nice to have. It's apparently a feature of Jonathan Blow's [Jai language](https://github.com/BSVino/JaiPrimer/blob/master/JaiPrimer.md). Another problem it would solve is that methods that are overridden can never be inlined; the call site may have specific knowledge of which version of the function is being called and can inline something that couldn't be done generically. I think using the `inline` keyword for this makes perfect sense.

The process for suggestions like this is to open a [proposal](https://github.com/HaxeFoundation/haxe-evolution) with the details of how this should be implemented, which would be discussed and voted on. You've touched on most of the proposal sections in your post here.

**Comment by Simn** [comment]
I like this too, but as @bendmorris says, this would have to go through https://github.com/HaxeFoundation/haxe-evolution
