### ISSUE TITLE
Optional, non-nullable arguments without default value

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#6972]
Coming from #2431, it is currently not possible to declare a function argument as optional, but non-nullable unless a default value is used.

In particular, the compiler overrules the explicit type hint `?x:Int` to `?x:Null<Int>`, which I don't think we do in any other place. I would like to change it so that explicit type hints in function arguments remain untouched.

These are the table. Bold things would change.

Without `?`:

syntax | optional | nullable
------  | ---------- | --------
`x` | no | inferred from usage
`x:Int` | no | no
`x:Null<Int>` | no | yes
`x = null` | yes | yes
`x = notnull` | yes | no
`x:Int = null` | yes | **error on static targets**
`x:Int = notnull` | yes | no
`x:Null<Int>` = any | yes | yes

With `?`:

syntax | optional | nullable
------  | ---------- | --------
`?x` | yes | inferred from usage
`?x:Int` | yes | **no**
`?x:Null<Int>` | yes | yes
`?x = null` | yes | yes
`?x = notnull` | yes | yes
`?x:Int = null` | yes | **error on static targets**
`?x:Int = notnull` | yes | **no**
`?x:Null<Int>` = any | yes | yes

**Comment by ncannasse** [comment]
I would go a bit further and make the "?" optional, so both syntaxes would have the same result.
That consists in changing as well the following:

?x = notnull | yes | **no**

**Comment by Simn** [comment]
I didn't notice how similar both tables were with regards to nullability. In that case I agree, let's change it like you suggest so we can say that `?` has no effect on nullability.

**Comment by Simn** [comment]
I've implemented this, but it's too annoying. We end up replacing virtually all `?x: Int` with `?x : Null<Int>`, which doesn't make for a good experience.

There are also some other problems related to inlining of `null` values which I don't want to think about at the moment. So let's keep it as it is.

**Comment by ncannasse** [comment]
Maybe we should imply that   `?x` (with no default value) is the same as `x=null`, so that would then be:

Without `?`:

syntax | optional | nullable
------  | ---------- | --------
`x` | no | inferred from usage
`x:Int` | no | no
`x:Null<Int>` | no | yes
`x = null` | yes | yes
`x = notnull` | yes | no
`x:Int = null` | yes | **yes**
`x:Int = notnull` | yes | no
`x:Null<Int>` = any | yes | yes

With `?`:

syntax | optional | nullable
------  | ---------- | --------
`?x` | yes | inferred from usage
`?x:Int` | yes | yes
`?x:Null<Int>` | yes | yes
`?x = null` | yes | yes
`?x = notnull` | yes | yes
`?x:Int = null` | yes | **yes**
`?x:Int = notnull` | yes | **no**
`?x:Null<Int>` = any | yes | yes

**Comment by Simn** [comment]
Unfortunately, that wouldn't even address the original issue.

**Comment by ncannasse** [comment]
Maybe, but at least that gives a clear language definition of optional parameters. ATM the fact that "?" defines nullability is not very good. Now it will be the value that defines nullability - and "?" without default value implies null.

**Comment by ncannasse** [comment]
I think my proposal does improve significantly the current situation wrt optional arguments and nullability and is the best way for Haxe 4.0 and should be implemented and tested against if I haven't overlooked some issue.

**Comment by farteryhr** [comment]
I think we need to be careful here, maybe considering deleting and unifying something will be better....

- `?`/(absent)
- `T`/`Null<T>`/(absent)
- `=null`/`=notnull`/(absent)
- static/dynamic target

I wonder we gotta revive the `IsMissing` in VB6...

**Comment by Simn** [comment]
I still think `x:Int = null` should be an error on static targets... That's what happens in all other assignment cases.

Other than that I'm fine with your changes, but it still bothers me that we don't address the original issue because that means we cannot fix #4087.

**Comment by ncannasse** [comment]
@Simn regarding `x:Int = null`, I would agree but then `?x:Int = null` would work, which mean that `?` makes a difference while in the new specification the whole idea is that it doesn't (when there's a default value)

Please move forward with the changes

**Comment by Simn** [comment]
I think I got it right, let's see what the CI says.

One case I'm not sure about is this:

```haxe
	function f01(x) {
		x = null;
		// t(n(x)); // nullable or not
	}
```

That's not strictly about function arguments though.

**Comment by ncannasse** [comment]
Yes if we assign null I think we should infer the type as `Null<TMono>`.
But OTOH we don't do that for local var:

var x = null;
x++;
$type(x); // Int
