### ISSUE TITLE
rtti data in xml vs json

### ISSUE THREAD

**Issue by jozefchutka** [HaxeFoundation/haxe#6973]
Hi everyone,
this is rather a question / feature request then a real issue, as I was wondering why rtti data are stored in xml instead of json?
```
Test.__rtti = "<class path=\"Test\" params=\"\">\n\t<main set=\"method\" line=\"4\" static=\"1\">\n\t\t<f a=\"\"><x path=\"Void\"/></f>\n\t\t<meta><m n=\":keep\"/></meta>\n\t</main>\n\t<meta>\n\t\t<m n=\":keep\"/>\n\t\t<m n=\":directlyUsed\"/>\n\t\t<m n=\":rtti\"/>\n\t</meta>\n</class>";
```

With XML data, [compiling even the simplest example](https://try.haxe.org/#dF84E) from [doc](https://haxe.org/manual/cr-rtti.html) would result in 50Kb javascript. I guess the major part of that is xml parser and referenced utils. Having data as json (or a compiler option to switch to json) could potentially save a lot of output. 

Eventually what happens inside Rtti.getRtti is a conversion from xml string into a Classdef structure. That could happen for free (without any parser involved) if data are already stored in json.

**Comment by nadako** [comment]
I agree, that JSON is a better storage format, although I would get rid of compiler-managed RTTI and move the functionality to macros.

**Comment by Simn** [comment]
I agree that JSON would be better, but I don't think we are going to change this. The problem with touching this is that our documentation generation is based on the XML output, and redoing that would be a major effort.

However, if we get a JSON generator anyway (hey @nadako), we could provide a convenient way of accessing its output.

**Comment by back2dos** [comment]
> That could happen for free (without any parser involved) if data are already stored in json.

Yes, there would be far less massaging to be done on the parsed data, but since there is no canonical representation for haxe enums in JSON, it would not work for free.

**Comment by jozefchutka** [comment]
Right, I just realized there are some enums with arguments in use (CType, Rights, TypeTree), so it will not be as smooth. 

So maybe it can be set of simple structures describing JSON, which can be then passed into some process that would create the more advanced structure (if needed)?

**Comment by Simn** [comment]
I'm waiting for someone to pick up https://github.com/nadako/haxe/tree/genjson so I don't have to do it eventually...

**Comment by Simn** [comment]
I see no reason to change the RTTI data for Haxe 4 given that there's already a working parser for it. We have `--json` now which we will stabilize until the actual Haxe 4 release.
