### ISSUE TITLE
String interpolation issue

### ISSUE THREAD

**Issue by shalmu** [HaxeFoundation/haxe#6981]
Something happened and string interpolation shut off.
Here is what I use:
`trace('my loc pos is ${p(loc)}\n my glob is ${p(me)}\n tap on ${p(pos)}\n===$isNowOver============\n');`
And the result is:

> Cell.hx:1: my loc pos is ${p(loc)}
>  my glod is ${p(me)}
>  tap on ${p(pos)}
> ===$isNowOver============

Strange, it worked ok before, always, and a month ago it started sometimes to compile like this. Maybe once a week. Today it always compiles like this.
Also, for some reason, see, it shows me as if it's on Cell.hx line 1, though in actuality it's on a line in the middle of the class!

**Comment by kevinresol** [comment]
Are you using compilation server? https://github.com/HaxeFoundation/haxe/issues/6820

**Comment by Simn** [comment]
Must be #6820.
