### ISSUE TITLE
Short lambda block syntax

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6987]
Currently when using short lambdas you can do the following:

`(_ -> true)` 

But you can't do the following:

`(_ -> var x = Std.random(2); x == 0)`

Would it not make sense to parse the expression enclosed in short lambda parenthesis as potential EBlock with optional semicolon on the last expression ? This would also allow this:

```
(_ ->
     var x = Std.random(2);
     x == 0;
)
```

**Comment by back2dos** [comment]
@ncannasse apparently someone hacked into your account :P

How about:

```haxe
_ -> {
     var x = Std.random(2);
     x == 0;
}
```

**Comment by frabbit** [comment]
Seems like short lambdas are not short enough for @ncannasse ;)

**Comment by ncannasse** [comment]
My first try at them and it's already annoying :D

**Comment by ncannasse** [comment]
@back2dos yes I know I can use {} , thank you. But there is no need for a block here given the scope is already defined by the parenthesises

**Comment by Simn** [comment]
The point is that you don't need the parentheses. I don't understand why we would support a special `( )`-based syntax here if you can just use braces instead. That seems to just trade a brace for a parenthesis.

**Comment by ncannasse** [comment]
The parenthesizes are because you have a call :  `map(_ -> ...)` but yes in
general case you might not have them.

**Comment by back2dos** [comment]
Well, that's an argument list though (as opposed to actual `EParens`). What if it has multiple arguments? Should the syntax still be valid that? 

I'm still stumped that out of the blue you seem to care about brace count now :D

**Comment by back2dos** [comment]
Hmm, how about `() -> Std.random(2) == 0` in this case? :P

More to the point though: what makes `(function() var x = Std.random(2); x == 0);` better than `function() { var x = Std.random(2); x == 0); }`?

**Comment by markknol** [comment]
(Hey that wasn't my example, I just copy/pasted that 😋)

I sometimes have a oneliner that should do two things and suddenly I have to add braces to make it work. That takes some effort. It's all lazyness of course, not a very big deal I guess.

**Comment by ncannasse** [comment]
Closing this, I agree it was not very on point.
