### ISSUE TITLE
[js.html] wrong return type for MediaElement.play()

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#6989]
The `play()` function of the HTMLMediaElement
https://api.haxe.org/js/html/MediaElement.html#play
returns a `Promise` instead of `Void` as of late.
This is important for dealing with autoplay blocking in Chrome 66, e.g.

Once again my question: Is it possible to make a PR for changes in the (generated) JS-API?

**Comment by haxiomic** [comment]
Hey @mockey, it's fixed in the newer WebIDLs – when js.html is re-generated this issue should be resolved. In the meantime you can create a file `js/html/MediaElement.hx` in your project and fill it with the newer externs: https://gist.github.com/haxiomic/511e2e801fc82b791a0d44ef1f99b161

**Comment by haxiomic** [comment]
Resolved in #7354
