### ISSUE TITLE
double Std.string conversion when joining a Vector

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/haxe#6990]
```haxe
class Test {
    static function main() {
        var a = new haxe.ds.Vector<Int>(1);
        trace(a.join(","));
    }
}
```
We get code containing  `b_b += Std.string(Std.string(a[i]));`.

------ below are just miscellaneous thoughts ------

The ultimate question: how to properly model the implicit and explicit toString() conversions everywhere in the code?

btw, on Python target, joining `Vector` simply raises `TypeError: unicode argument expected, got 'str'`.

btw2, while reading the generated code, I feel like `join` is something fun. It looks overly verbose.
When we joining an array, we make another Array and push converted strings into it, then "join" that Array with a StringBuf. And on some platform, internally StringBuf is another (dynamic) Array or another internal string builder, knowing nothing other than strings fed in one by one, waiting for the last getValue, and this call seems to do everything above again....

Of course it's not infinite recursion, and it works fine, but just tbh it looks kinda silly....

What I think is the point, is whether the Array is of unknown objects or of all pure strings, and whether we know the number of the elements to join.

Since we're already on such powerful type system, we can be able to determine whether something is iterable, measurable, container of string (but there may be nulls "on dynamic targets", lol), or container of stringifiable objects(?).

And, essentially, it's related too toString() calls, because, especially on dynamic targets, the "native" join will take another try to convert elements to string. And this may cause errors like a `nil` in a table in lua.
We'd probably standardize where and when to call toString and where not to do so, and whether to `Std.string` or `.toString()`?

Also the DCE problem removing some internal toString functions when using `trace`, `console.log`-like functions with implicit conversion.

though yes, i think toString results on non-primitives shouldn't be relied on in serious usage like serialization, but i see all string_rec implementations in xx_Boot, it seems intended to be kept consistent..

Maybe we need specialized StringArray, and a special joiner (with or without separator?) for it?
Maybe force `Null<T>` for all targets when T is primitive type? (I think type system should prevent us from `if(x==null)`s, at least on primitive types) (maybe i'm going too far...)
Much of the time we use an typed array of length 0 to indicate something doesn't exist?

Any idea?

**Comment by Simn** [comment]
This is a variant of #5440.
