### ISSUE TITLE
Haxe 3 to 4 transition

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6991]
We have several deprecation warnings for Haxe 4.0 .

We should have a way for users to smooth transition for 3.x to 4.x.
Compiling with `-D haxe3-syntax` should disable all these warnings. Whereas compiling with `-D haxe4-syntax` would turn them into errors. I think this should be independent from using `-lib hx3compat`

**Comment by Simn** [comment]
This is not limited to syntax so if anything it should be `haxe3` and `haxe4`.

**Comment by back2dos** [comment]
Whatever the flag, don't forget to add it to the extraParams.hxml of hx3compat ;)

**Comment by kevinresol** [comment]
Can we have class path filter?

**Comment by ncannasse** [comment]
I think we already use `haxe3` for saying we're at Haxe 3+ (maybe we want haxe4 as a shortcut for haxe_ver >= 4.0 btw)

**Comment by ncannasse** [comment]
I guess that's too late for this now :)
