### ISSUE TITLE
[regression] inline recursive function crash

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#6992]
Calling the following function make the compiler crash because of infinite inlining in b0d2d56234c7f719ba92be0b6fbe85dbaff87757

`inline function foo( b ) { foo(b); }`

**Comment by ncannasse** [comment]
Boosting the priority because it might affect other people code (leftover inline = 100% crash)

**Comment by Gama11** [comment]
This has indeed affected openfl (workaround pushed + released though) + flixel-tools (maybe something in the mcsonole depedency) for me so far.
