### ISSUE TITLE
Math.floor on Python returns float

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/haxe#6995]
```haxe
var a = [1,2,3];
trace(a[Math.floor(Math.random()*a.length)]);
```
`TypeError: list indices must be integers, not float`

It may also be undistinguished in other languages, please check them.

*python is so strict.gif*

But we have type signature: `static floor (v:Float):Int`.

**Comment by ncannasse** [comment]
@frabbit Math.ceil/floor/round uses int32, only fceil/ffloor/fround keeps the float

**Comment by frabbit** [comment]
hmm, i can't reproduce this bug, which python version are you using? @farteryhr

**Comment by farteryhr** [comment]
@frabbit oh i just found it returns `float` on python 2(.7) but changed to `int` on python 3+...
(btw, strictly speaking, it produces precise value for big integral floats, not restricted to int32 (because it's python))
seems we didn't specify which version of python is our target?

**Comment by Simn** [comment]
We target Python 3.
