### ISSUE TITLE
haxe4: enum abstracts @:from changed?

### ISSUE THREAD

**Issue by sh-dave** [HaxeFoundation/haxe#6999]
The following code used to work in haxe3, but doesn't anymore in haxe4 (preview3). Is this an intentional change?

```haxe
@:enum abstract Foo(Int) {
    var Value1 = 0;
    var Value2 = 1;

    @:from public static inline function ofInt( i: Int ) : Foo
        return switch i {
            case 0: Value1;
            case 1: Value2;
            case other: Value1;
        }
}

class Main {
    static function one() : Int
        return 1;

    static function main() {
        var a: Foo = one(); // << haxe4: Int should be Foo
        trace(a);
    }
}
```

**Comment by Gama11** [comment]
Is this with Haxe 4 preview 3 or latest Haxe dev? There was a fix related to `@:from` recently.

**Comment by sh-dave** [comment]
Haxe 4 Preview 3 downloadable from [haxe.org](https://haxe.org/download/version/4.0.0-preview.3). I'll try again with a nightly later.

**Comment by mrcdk** [comment]
It's working correctly http://try-haxe.mrcdk.com/#7ad3e using https://github.com/HaxeFoundation/haxe/commit/3cb7cd198ef882649612d4590a8d302ef06f8fed

**Comment by sh-dave** [comment]
Yup, can confirm it works with this version.
