### ISSUE TITLE
New function syntax in error messages

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7001]
ATM the compiler still display function types using Haxe 3.x function notation `x:Int  -> y:Int -> Void should be XXX` for instance.

For Haxe 4 we are moving the official function notation to `(x:Int,y:Int) -> Void` so we should change the display type accordingly.  There's something to be done when we don't have an argument name, that can be using `_` or using `arg0...X` or `a...z`

**Comment by nadako** [comment]
> There's something to be done when we don't have an argument name,

We actually support this in the new function type syntax but simply specifying the type, e.g. `(Int,Int)->Void`

**Comment by ncannasse** [comment]
This should be documented (if not already) ;)
