### ISSUE TITLE
Default values for basic types on dynamic targets

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7002]
We should add a global define that initialize all member vars to 0 for Int/Float and false for Bool on dynamic targets. That could be forced or done smart by looking only at the uninitialized vars in constructor (although there's still the case where a member var is tested against 0 before being set, which is rare but possible because of subclassing).

**Comment by Simn** [comment]
If we do this, it should be the default behavior.

**Comment by back2dos** [comment]
For JS we could "simply" do it on the prototype, for PHP we can emit something like `public $intField = 0;`. No idea about Lua and Python though.

**Comment by nadako** [comment]
A bit off-topic, but I can't help myself but ask:
 
> We should add a global define

I am really confused by your position on global defines that change behaviour like that. I remember you were strictly against them due to possibility of library compatibility and whatnot. What's the system here?

**Comment by farteryhr** [comment]
Yes!

Also consistent `T` and `Null<T>` for basic types (all types?) for all targets?

btw also note when constructing `Vector<T>` (and all containers about allocation?)

(maybe we'll need optional null guard code generator for dynamic targets?)

---
Although the impact is minor, there are situations like this:
```haxe
// may be class members, may be local variables
var a:Int;
var b:Int; 

if(blah){
    //lots of work
    a = x; b = y;
}else{
    //another lots of work
    a = z;
    if(moreblah)
        b = w;
    else
        b = 0;
}
```
Performance is one aspect, what if we want to utilize the "uninitialized variable checking" for completeness? (though I admit the use case may be not so common...)

**Comment by ncannasse** [comment]
Reopening for further discussion. Warnings might be interesting, I'm afraid of many false positive.
@Gama11 in JS for instance, performance is not main concern, but output code size is. Having a lot of  initializers might be perceived badly by JS developers starting with Haxe and looking at its output.

**Comment by Simn** [comment]
If we're going for consistency here, this would have to go beyond basic values because issues like #5897 show that JavaScript behaves differently between assigning a `null` value an not assigning it.

**Comment by jdonaldson** [comment]
FWIW Lua can follow a prototype approach.

**Comment by ncannasse** [comment]
I don't want to change the default behavior here, and a compilation flag is not good either because it affects too much the runtime. 

The best choice IMHO is to go with a compiler flag that warns about uninitialized member/static vars when compiling on a dynamic platform. This will help porting applications from a static platform to a dynamic one.

This can eventually wait post Haxe 4.0 as it's not a breaking change.

**Comment by SmerkyG** [comment]
@ncanasse Regarding your concern that JS developers new to Haxe might see excessive initialization: For variables that get set after initialization, I would think that static analysis would permit them to be initialized to their default values only when absolutely necessary: 

a) For a member variable, only when it is not manually assigned in the constructor prior to the first time it is read during the constructor (or by the end of the constructor, if unread)
b) For a local variable, only when not manually assigned in its defining method before it is read (or by the end of the method, if unread)

This would cause local variables to get initialized only very rarely, and member variables to get initialized in a manner that IMHO looks like good code style. Setting up member vars in the constructor is generally good practice in JS anyway, and self-documents the class's members.

**Comment by RealyUniqueName** [comment]
For now I don't think automatic generation of default values is a good approach because we can't make it consistent:
```haxe
class Value<T> {
  public var field:T;
  public function new() {}
}

trace(new Value<String>().field); //???
trace(new Value<Int>().field); //???
```

And if we implement warnings/errors by package or module (like it's implemented for null safety) it's still not clear what to do with type parameters. The only default value, which makes sense in this case is `null`, but only until `@:generic` is involved.

**Comment by Gama11** [comment]
I'm not sure it's a big issue if type parameters are an exception. I would consider those "advanced usage" anyway, where users should know what they're doing. The other 99% with regular old int / float / bool fields that are actually the source of most problems and confusion for newcomers would still be covered.

**Comment by Gama11** [comment]
And actually, doesn't your code illustrate that this _would_ make the behavior consistent across targets? That currently already seems to trace `null` on all targets, including static targets like JVM and C++. So type parameters are already an exception?

**Comment by Simn** [comment]
C# can/should trace this as `0`.

**Comment by SmerkyG** [comment]
If it can cover normal usage cases that would go a long way towards
fulfilling the promise of haxe as a way to write code that can used (and
therefore never rewritten) across platforms and languages! Currently,
taking haxe code that works in c# target, for example, and trying to run it
on say js requires a ton of fixing of default value related bugs you can't
even know existed in your code.

**Comment by Gama11** [comment]
>C# can/should trace this as `0`.

Hm, ok... Well, anyway, it seems like type parameters are already quite inconsistent in this regard then and probably won't ever be fully consistent across targets. So that shouldn't be an argument against this.

**Comment by nadako** [comment]
> Currently, taking haxe code that works in c# target, for example, and trying to run it on say js requires a ton of fixing of default value related bugs you can't even know existed in your code.

I can confirm that was probably the main pain point for me on my haxe->c#+js projects.

**Comment by ncannasse** [comment]
The idea of reopening the issue was to add a way for warnings to be inserted, see here https://github.com/HaxeFoundation/haxe/issues/7002#issuecomment-418723657. Maybe a new issue should be opened instead.

**Comment by RealyUniqueName** [comment]
@ncannasse What about enabling default values generation per package/module?

**Comment by RealyUniqueName** [comment]
@Simn @ncannasse so, what do you think about that idea (implemented in #9265)?

**Comment by Simn** [comment]
I'm in favor of it, but it's totally pointless if it isn't made the default.

**Comment by SmerkyG** [comment]
I think you'd want control over what the starting value is for floats and
ints. If your code was developed for a platform where floats start as NaN,
and move to one where they start as zero, that's very different than if you
moved in the opposite direction. I think the two common situations that
cause nearly all of the problems when changing destination platforms are
'check for NaN sentinel' and 'mathematical operations performed on
uninitialized value'. In both cases, the desired initialization value is
going to depend on which platform the code was originally written for. I
would hope we could find a 'normal' default initialization value, but allow
divergent ones.

**Comment by RealyUniqueName** [comment]
Won't making it the default be a breaking change?

As for `NaN` I think it's a very rare case when you would want initial value of floats to be `NaN`.

**Comment by Gama11** [comment]
>Won't making it the default be a breaking change?

Sure, but I doubt a lot of code relies relies on values _not_ being initialized. It would probably silently _fix_ more code than it breaks. :D

**Comment by RblSb** [comment]
@Gama11 it is really easy to write variable like `Int` without `Null<>` and null check it for initialization after when null safety is disabled and you only use target like js.

I think it is fine to be default behavior (or behind flag for some time), but there is should be null-check [compile-time errors for basic types](https://haxe.org/manual/types-nullability.html#define-default-values) on all targets then (without enabled null safety). Maybe as warnings on dynamic targets for start, but still.

**Comment by ncannasse** [comment]
Ok I'm closing this discussion because we already stated that we don't want to change the current default behavior.

The one solution I can see is a compiler flag to give warnings, so one can enable it and look at the code for which places needs to be handled with either = 0 or Null<T>. But that's only necessary when you are cross compiling for several platforms with at least one Static and one Dynamic.

Please reopen a new issue if you want to discuss this point.
