### ISSUE TITLE
Deprecate --next and --each

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7010]
They are nice for hello world programs, but unusable for IDEs.

**Comment by jdonaldson** [comment]
Theyre not so bad.  I kind of like having a multi target hxml.

**Comment by back2dos** [comment]
Deprecate them **in favor of what**?

**Comment by ncannasse** [comment]
I think we should keep them, even if we clearly state/document that IDE does not support them.

**Comment by Simn** [comment]
Works for me. Changed to documentation issue.

**Comment by pchertok** [comment]
Fixed in
