### ISSUE TITLE
HashLink Travis tests

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7011]
HashLink still missing in travis.yml, but there might be additional steps required to download + compile it before testing. Could we have that soon @andyli ? thanks :)

**Comment by andyli** [comment]
I'm working on it, but looks like something is broken right now:
```
~/Documents/haxe/tests/unit$ haxe compile-hl.hxml
Error:
unit/issues/Issue6560.hx:9: Check failure at fun@2587 @1E - Register 4(i32) should be dyn and not i32
```

https://github.com/HaxeFoundation/haxe/issues/6560

**Comment by ncannasse** [comment]
@andyli all green now

**Comment by Simn** [comment]
I think we can close this.
