### ISSUE TITLE
flash.Vector is hard-coded into the compiler, and cannot be overridden

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#7012]
Hey guys,

`openfl.Vector` and `flash.Vector` are currently different types in OpenFL, but we override other core Flash types in order to make minor changes to improve the overall consistency of the OpenFL framework.

`openfl.Vector` is a Haxe abstract, which includes utility features outside the stock `flash.Vector` type. We tried (in the past) to override the type, but came up against limits due to the nature of the current `genswf9.ml` code.

We'd like to be able to do the following:

```
package flash;

abstract Vector<T>(VectorData<T>) { ... }

#if flash
@:native("flash.Vector") private extern class VectorData<T> { ... }
#else
...
#end
```

I'm wondering if the core logic within `genswf9.ml` could be modified somehow to not be based specifically on the `flash.Vector` classpath (since we would override it) but the underlying native type of the class instead?

**Comment by Simn** [comment]
At this point I don't think we want to change anything related to flash.
