### ISSUE TITLE
[display] goto definition not working on types "imported as"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7020]
```haxe
import haxe.macro.Expr.Access as ExprAccess;

class Main {
    public static function main() {
        var access:ExprAccess;
    }
}
```

```xml
>haxe --display source/Main.hx@122@position
<list>
<pos>(unknown)</pos>
</list>
```

This seems to be a regression compared to 3.4.7, where it reported the import line as the definition. I guess that actually makes sense, since that's where the `ExprAccess` type is introduced?

**Comment by Simn** [comment]
This means something has a null pos.
