### ISSUE TITLE
[display] goto definition gives weird output in failure cases

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7021]
In failing cases, `@position` / `textDocument/definition` should give a saner output. As you can see in the case of https://github.com/HaxeFoundation/haxe/issues/7020, the XML contains some `(unknown)` entry - instead it should probably simply be an empty list. Similarly, for JSON-RPC it reports `[null]` right now rather than `null` or `[]`.

**Comment by Simn** [comment]
Probably exact same issue as #7020. It doesn't exactly fail, it's just that something which is supposed to have a position doesn't have a position.

**Comment by Gama11** [comment]
But even if something doesn't have a position (which tends to happen now and then I guess), shouldn't the output be a bit saner so vshaxe can handle such cases gracefully?

**Comment by Simn** [comment]
For debugging purposes, it is better to see these `null` values so we can go and find them. We can change this for Haxe 4 release by filtering them out, but let's keep them for a while.

**Comment by Simn** [comment]
Thinking about it again, let's not filter anything. If something still has a null position we want to know about it, so it's good to have the consumer error in that case. I don't think this can be reproduced with anything anyway.
