### ISSUE TITLE
Std.parseInt on a hexadecimal string followed by \n returns null when targeting neko

### ISSUE THREAD

**Issue by vwr0527** [HaxeFoundation/haxe#7028]
The expression Std.parseInt("0xff000000\n") returns null on Neko. Other target platforms tested were fine.

I don't think it's intended behavior. I tried to reduce this to the most basic example and got this:

```
class Main
{
	public static function main() 
	{
		trace(Std.parseInt("1234"));
		trace(Std.parseInt("1234\n"));
		trace(Std.parseInt("0xff000000"));
		trace(Std.parseInt("0xff000000\n"));
	}
}
```
The resulting output was:
```
Main.hx:5: 1234
Main.hx:6: 1234
Main.hx:7: -16777216
Main.hx:8: null
```
So, it seems that parseInt should work even if there's a "\n" at the end of the number. But it produces null when fed a hexadecimal string followed by "\n".

Just for additional information:

Compiling to javascript:
```
Test.js:3340 Main.hx:5: 1234
Test.js:3340 Main.hx:6: 1234
Test.js:3340 Main.hx:7: 4278190080
Test.js:3340 Main.hx:8: 4278190080
```
Compiling to Flash:
```
Main.hx:5: 1234
Main.hx:6: 1234
Main.hx:7: 4278190080
Main.hx:8: 4278190080
```

**Comment by Simn** [comment]
We are not going to look into fixing neko-specific problems. However, we still review pull requests.
