### ISSUE TITLE
[display] implements / extends completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7029]
It would be nice if Haxe only showed things that can be implemented after `implements` (i.e. interfaces). Right now it's just regular type completion it seems:

![](https://i.imgur.com/oJTMxbT.png)

Same for `extends`.

**Comment by Gama11** [comment]
There's two mores issues with this as far as I can tell:

`@:final` classes and interfaces should be filtered out, as that would lead to a `Cannot extend a final class` error:

![](https://i.imgur.com/3ZSSGu1.png)

"Basic classes" such as `Array` should be filtered out too, whatever that means (error is `Cannot extend basic class`):

![](https://i.imgur.com/kmJlZgp.png)

Note that `Array` itself is also declared `@:final`.

**Comment by Gama11** [comment]
Oh, and conversely, final types should _not_ be filtered out when there's `@:hack` meta on the current type - basically the behavior should match the way the error message works.

**Comment by Simn** [comment]
Addressed in https://github.com/HaxeFoundation/haxe/commit/8cff76fd23537176387da8df9de63e2d2bad513d
