### ISSUE TITLE
optional argument default value lost when inlining a function call 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7032]
```haxe
class Test {
    static function main() {
        f(null);
    }
    
    static function f(p) {
        trace(f2(p));
    }
    
    static inline function f2(p = 10) {
        return p;
    }
}
```

generates:

```js
Test.f = function(p) {
	console.log("root/program/Test.hx:7:",p);
};
```

although it should insert the null-check for the `p` argument at the call site.

so this snipped traces `null` instead of `10` as it would if we remove the `inline` modifier

**Comment by nadako** [comment]
not a regression btw

**Comment by Simn** [comment]
This is related to #3826 and possibly #6972.

**Comment by Simn** [comment]
Note that this currently doesn't deal with the `p = 10` case, only `?p = 10`. This is a bit of a mess on static targets so I would like to think about it some more.

**Comment by Simn** [comment]
This now generates this:

```js
Main.f = function(p) {
	var p1 = p;
	if(p == null) {
		p1 = 10;
	}
	console.log("source/Main.hx:7:",p1);
};
```

Which looks correct to me.
