### ISSUE TITLE
[cpp] modulo zero can't be caught / causes a hard crash

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7034]
The following code causes a hard crash on the cpp target that can't be caught, which is a problem for tools like [crashdumper](https://github.com/larsiusprime/crashdumper):

```haxe
class Main {
    public static function main() {
        var zero = 0;
        try {
            trace(1 % zero);
        } catch (e:Dynamic) {
            trace(e);
        }
    }
}
```

```
Error: Command failed with error -1073741676
```

![](https://i.imgur.com/4HsgFsx.png)

`-debug` and the usual defines (`-D HXCPP_CHECK_POINTER`, `-D HXCPP_STACK_TRACE`) don't seem to help.

Other targets either don't throw an exception at all, or one that can at least be caught:

- Java: `source/Main.hx:7: System.DivideByZeroException: Attempted to divide by zero.`
- C#: `source/Main.hx:7: java.lang.ArithmeticException: / by zero`
- Neko: `source/Main.hx:7: Invalid operation (%)`
- JavaScript: `source/Main.hx:5: NaN`

Haxe version: eecfbebb084f5faf6d08c68b020162c1f221816f
HXCPP version: https://github.com/HaxeFoundation/hxcpp/commit/8753da50bb642214c28a63294eca8a2afa39a420

**Comment by ousado** [comment]
This is expected, divide and modulo by zero are undefined behavior in C++, this would require an explicit check and throwing an exception. If that's what a user wants, let them handle it themselves.

**Comment by Gama11** [comment]
By that logic, a division by zero should hard-crash as well, yet it doesn't even throw an exception.

```haxe
class Main {
    public static function main() {
        var zero = 0;
        trace(1 / zero); // source/Main.hx:4: inf
    }
}
```

Possibly related: #5061

**Comment by ousado** [comment]
That's because it's not integer division, division of floating point types is handled differently in C++

**Comment by Gama11** [comment]
I see, I guess you'd have to use `cpp.NativeMath.idiv()` for that, which does exhibit the same hard-crash behavior. 

The use case here with crashdumper is to have a generic error reporting tool that catches as many errors as possible, which is why it automatically defines e.g. `HXCPP_CHECK_POINTER` when included.

>If that's what a user wants, let them handle it themselves.

Given those requirements, I'm not sure this is really an option - as far as I know, there's no way to override the default behavior of the modulo operator. So I guess you're proposing to have some custom `safeModulo()` function and use that instead? That only really works as long as the crash you're trying to catch happens in your own code rather than third-party libraries (and if you manage to remember to use it everywhere).

For integer division this isn't really a big problem, as you have to explicitly opt-into that by using `cpp.NativeMath.idiv()`.  For modulo, the "default" `%` operator exhibits this behavior.

**Comment by ncannasse** [comment]
Haxe should not crash on divide/modulo by 0, we need unit tests for it.

**Comment by Gama11** [comment]
Just to clarify, you aren't including `cpp.NativeMath` with that statement, just the regular division / modulo operators, right? Because the use case for the former just seems to be to get as much raw native performance as possible, to which additional checks would probably be detrimental.

**Comment by hughsando** [comment]
There should now be additional checks to force int/int to be done as double
to avoid this.
idiv is for unsafe/fast/non-haxe-standard/c++standard operations.
If you really need speed, you should work out a bit-shift because every
thing else is slow (even c++ int/int, relatively speaking).

**Comment by Gama11** [comment]
Yes, it seems fine for division, this issue is about modulo (but the discussion drifted a bit).

**Comment by Simn** [comment]
This doesn't seem to crash anymore.

**Comment by Gama11** [comment]
Are you sure? I'm not seeing any trace output, just "Error: Command failed with error -1073741676" (when running it from VSCode).

**Comment by Simn** [comment]
I'm getting `source/Main.hx:5: -nan(ind)`

**Comment by Gama11** [comment]
Hmm, not sure why we're getting different results... I assume you're just pasting the snippet into HaxeRepro? Latest hxcpp?

**Comment by Simn** [comment]
Yes and yes.

```c++
::haxe::Log_obj::trace(hx::Mod(1,zero),hx::SourceInfo(HX_("source/Main.hx",91,d3,a7,40),5,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
```

**Comment by Simn** [comment]
Ok it fails without `-debug`.

**Comment by Simn** [comment]
Fails without `-debug` as well. I don't know wtf I was doing yesterday.

**Comment by hughsando** [comment]
Added test https://github.com/HaxeFoundation/haxe/commit/bfe1db55e8a29f734a82595f26b15b095daca6ca

**Comment by Simn** [comment]
Test fails on python. It also causes native C# compilation to fail. I think because the analyzer moves the constant 0 to the divisor.

**Comment by Simn** [comment]
I have added a <strike>hack</strike>optimization to gencs so any `TBinop(%, _, 0)` generates `System.Double.NaN`.

**Comment by ncannasse** [comment]
The test is not correct, it should never throw an exception

**Comment by Simn** [comment]
Right, I didn't notice that try/catch. So the problem on python is that it raises an exception that cannot be caught.

I've removed the try/catch, let's see how terrible it is.

**Comment by Simn** [comment]
Another one of these issues where I can just assign everyone:

* [ ] neko
* [x] hl
* [ ] php
* [ ] flash (succeeds on as3)
* [ ] java
* [ ] python

**Comment by RealyUniqueName** [comment]
Can we leave it unspecified?
The only way to avoid 'Modulo by zero' exception on PHP is to check the second argument for `0` for each operation.

**Comment by hughsando** [comment]
So what is the answer?  It can't be inf, because integer mod is typed as 'int', which can't be inf.
So 0 ?  max_int?   I am happy to do anything here because basically I had to put the check in.

**Comment by ncannasse** [comment]
There is no integer division in Haxe, so it should give the following:

```haxe
class Main {

	static function div(x:Int,y:Int) {		
		return x / y;
	}

	static function fdiv(x:Float,y:Float) {		
		return x / y;
	}

	static function mod(x:Int,y:Int) {		
		return x % y;
	}

	static function fmod(x:Float,y:Float) {		
		return x % y;
	}

	static function main() {
                // [+Inf,NaN,+Inf,NaN]
		trace(div(1,0),div(0,0),fdiv(1,0),fdiv(0,0)); 
                // #if static [0,0,NaN,NaN]  else [NaN,NaN,NaN,NaN]
		trace(mod(1,0),mod(0,0),fmod(1,0),fmod(0,0)); 
	}
}
```

**Comment by ncannasse** [comment]
@Simn And HL is not failing, maybe it's hlinterp ?
(actually I get good results with hlinterp as well)

**Comment by Simn** [comment]
`$type(1 % 2)` prints `Int`...

**Comment by RealyUniqueName** [comment]
[The manual](https://haxe.org/manual/types-numeric-operators.html#arithmetic) says there is integer modulo in Haxe.
I cannot support neither `a % 0 == NaN` nor `a % 0 == 0` on PHP without penalizing performance of all `%` operations.

**Comment by ncannasse** [comment]
Yes, we don't have int division but we have int modulo ;) I thought at first it was about divide by zero, still my tests should be added to unit tests. I'm not 100% sure about the #if static check, maybe that could be done by doing ((Int % Int) | 0) in JS

**Comment by ncannasse** [comment]
But right, maybe we should leave the %0 unspecified , either 0 or NaN or exception

**Comment by Simn** [comment]
`0` seems wrong...

**Comment by ncannasse** [comment]
@Simn that's NaN cast to Int

**Comment by Simn** [comment]
I don't think "never fail at run-time" is a good policy here. IMO if you do nonsense with numbers, you should get proper exceptions, not silent 0-values...

**Comment by hughsando** [comment]
The sha256 test fails if you return a Float (since it is then used in a
shift).

0 makes sense in so much as the limit as the divisor approaches zero, and
is "between 0 and x" like other modulo, so it is really the only single
value that might make sense. Like how "sinc(x)"is defined at 0 to be 1
since it makes everything else work better.  So I guess it might not be
"silently" failing but doing the most logical thing/least surprise if that
is how we choose to define it.

**Comment by Simn** [comment]
Pushing back, shouldn't be urgent.
