### ISSUE TITLE
Don't require ugly comma for structural extensions

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7036]
```haxe
typedef T1 = {
    > T2, // <--
    var x:String;
}
```

I don't think we need that comma for the parser.

**Comment by nadako** [comment]
random thought: what would _maybe_ look cool asthetically in the long notation is `extends T2` instead of `>T2` :)

**Comment by back2dos** [comment]
How about we parse this as `TExtend`:

```haxe
typedef T1 = T2 & {
  var x:String;
} & T3 & {
  var y:Int;
}```

This could be considered equivalent to:

```haxe
typedef T1 = {
  >T2, >T3,
  var x:String;
  var y:Int;
}
```

Beyond that point we would treat "base types" the same, i.e. it wouldn't work for classes or enums (at least not for now).

Or we could substitute `TExtend` by `TIntersect(t:Array<ComplexType>)` and have it work only for the cases when it currently works. Does that stand a chance as a haxe-evolution proposal?

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe-evolution/pull/46

**Comment by back2dos** [comment]
Ah, well, ignore me then ;)
