### ISSUE TITLE
haxelib 'The application was unable to start correctly (0xc000007b)'

### ISSUE THREAD

**Issue by hedgehog90** [HaxeFoundation/haxe#7040]
The latest version of haxelib (3.4.7-64bit) doesn't work.
I just get this error prompt.

![haxelib_2018-05-18_13-56-44](https://user-images.githubusercontent.com/5526342/40235823-54ecd556-5aa3-11e8-9f2c-d970bd03077c.png)

I checked the dlls, there are no interferences in the Path variable, but while the dlls and haxe.exe are 64 bit, haxelib.exe is 32 bit.

**Comment by andyli** [comment]
Haxelib is indeed distributed as 32-bit binary, so it needs to load a 32-bit libneko. I suspect you installed a 64-bit neko.

**Comment by hedgehog90** [comment]
So I did.
Thanks!

**Comment by retsyo** [comment]
I met this problem too. but why there is no 64-bits haxelib.exe? Since haxe.exe is for 64 bits, how to keep both 32 and 64 bits neko to work together?

**Comment by andyli** [comment]
64-bit Haxe can work with 32-bit Neko/haxelib without any issue, so just keep Neko as 32-bit.

Note that Neko only supports 32-bit JIT, so it is actually faster than the 64-bit version.
