### ISSUE TITLE
Type error not correctly reported in @:overload

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7041]
In the following example:

```haxe
class Main {	
	static var x = 0;
	static function main() {
		var j = new js.jquery.JQuery();
		j.blur(function(e) {
			if( x == "" ) trace("OK");
		});
	}
}
```

The error display is:
```
Main.hx:5: lines 5-7 : Could not find a suitable overload, reasons follow
Main.hx:5: lines 5-7 : Overload resolution failed for Void -> js.jquery.JQuery
Main.hx:5: lines 5-7 : Too many arguments
Main.hx:5: lines 5-7 : Overload resolution failed for handler : (js.jquery.Event -> Void) -> js.jquery.JQuery
**** Main.hx:6: characters 8-15 : String should be Int  *****
Main.hx:6: characters 8-15 : For function argument 'handler'
Main.hx:5: lines 5-7 : End of overload failure reasons
```

The actual real error is wrapped with a lot of false positive leading to time lost understand what is the problem with overloading.

**Comment by Simn** [comment]
#4803

**Comment by ncannasse** [comment]
See my comment on #4803

**Comment by Simn** [comment]
I still don't know what to do with this. Yes the error is invariant to the overload, but in the general case we can't know that. See [my comment](https://github.com/HaxeFoundation/haxe/issues/4803#issuecomment-186628918) on #4803.

**Comment by ncannasse** [comment]
If we are not strictly sure that the error comes from unifying the expression with the overload argument (which we can know by looking if the error position is equal to one of the call arguments expression position) then we should avoid the wrapping that adds "suitable overload" error.

**Comment by Simn** [comment]
I have no good solution here and while it's inconvenient, it's not exactly a regression. Pushing back to after 4.0.

**Comment by Simn** [comment]
DeJQueried:

```haxe
class Main {
	static var x = 0;

	overload extern static function test(f:Int->Void):Void;

	overload extern static function test(f:String->Void):Void;

	static function main() {
		test(function(e) {
			if (x == "")
				trace("OK");
		});
	}
}
```

This now errors like so:

```
 ERROR  source/Main.hx:10: characters 8-15

 10 |    if (x == "")
    |        ^^^^^^^
    | String should be Int
    | For function argument 'f'
```
