### ISSUE TITLE
Questionable recursion in `load_type_def`

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7042]
Simplified version of that function:

```ocaml
let rec load_type_def ctx p t (* <- the path we're looking for *) =

	let no_pack = t.tpackage = [] in
	let tname = (match t.tsub with None -> t.tname | Some n -> n) in

	let path_matches t2 =
		let tp = t_path t2 in
		tp = (t.tpackage,tname) || (no_pack && snd tp = tname)
	in

	(* 1. Check if one of our current module's types matches the path. *)
	List.find path_matches ctx.m.curmod.m_types;

	(* 2. Check if one of our current module's imports matches the path *)
	List.find (fun (t2,pi) -> path_matches t2) ctx.m.module_types;

	(* 3. lookup in wildcard imported packages *)
	let rec loop l = match l with
		| [] -> raise Exit
		| (wp,pi) :: l ->
			(* Recursion with wildcard package as new package *)
			load_type_def ctx p { t with tpackage = wp }
	in
	if no_pack then loop ctx.m.wildcard_packages;

	(* 4. lookup in our own package - and its upper packages *)
	let rec loop = function
		| [] -> raise Exit
		| (_ :: lnext) as l ->
			(* Recursion with parent package as new package *)
			load_type_def ctx p { t with tpackage = List.rev l }
	in
	if no_pack then loop (List.rev (fst ctx.m.curmod.m_path));

	(* 5. Try loading module using current path *)
	ctx.g.do_load_module ctx (t.tpackage,t.tname) p	
```

The attention here is on the two lines after the `(* Recursion` comments. In both cases, we recurse into `load_type_def` with a changed package. Unless I'm misreading this, here's what should happen if we resolve an unqualified identifier `Type` from within `pack1.pack2.Module`:

1. Check if `Type` is defined in `pack1.pack2.Module`.
2. Check if `Type` is imported in `pack1.pack2.Module`.
3. Let's say we have no wildcard packages, so nothing happens there.
4. Enter the package loop, recurse using `pack1.pack2.Type`.

At this point, we arrive back at the top of the function. Starting over:

1. Check if `pack1.pack2.Type` is defined in `pack1.pack2.Module` (**We already know it's not**)
2. Check if `pack1.pack2.Type` is imported in `pack1.pack2.Module` (**We already know it's not**)
3. Still no wildcard package, skip.
4. Package loop is skipped because `no_pack = false`.
5. Try to load `pack1.pack2.Type` as a module.

Let's say the module doesn't exist, which brings us back to the original recursion call. We move up another package, so now having `pack1.Type`, we start over again:

1. Check if `pack1.Type` is defined in `pack1.pack2.Module` (**What does this even mean?**)
2. Check if `pack1.Type` is imported in `pack1.pack2.Module` (**What does this even mean?**)
3. Still no wildcard package, skip.
4. Package loop is skipped because `no_pack = false`.
5. Try to load `pack1.Type` as a module.

That should be sufficient to get my point across. I don't see why we are recursing into `load_type_def` itself. Checks 1-4 are always going to fail, either because they have already been checked, because they make no sense, or because there is a package which causes checks to skip. It seems that the only thing we're actually interested in is the `do_load_module` check, so it makes sense to just call that instead.

**Comment by ncannasse** [comment]
Yes, it might not be correctly optimized when we have a package already. But we might need some kind of recursion to look for `[my.current.pack.Type, my.current.Type, my.Type, Type]` (in that order) when loading `Type`

**Comment by Simn** [comment]
Experimenting on a branch I'm getting

Before:

```
load_module: 20753
load_module ([],Array): 758
path_matches: 559504
```

After:

```
load_module: 20753
load_module ([],Array): 758
path_matches: 337238
```

The operation isn't expensive enough to measure a timing difference, but 40% less calls is a good improvement regardless.
