### ISSUE TITLE
Compiler problem when using extern / constructors with default value / @:hxGen

### ISSUE THREAD

**Issue by ochalouhi** [HaxeFoundation/haxe#7043]
A is a class implemented in haxe, compiled to java (.jar)
B extends A, however via an extern definition of A
if B's constructor defines a default value for its parameter, then B's compilation fails with : 
"Super call must be the first call when extending native types"

Please see https://github.com/ochalouhi/haxe-bug for a snippet of code that fails : 
module2 will build, but not module3. difference is the default value.

**Comment by Simn** [comment]
Test fails on python. It also causes native C# compilation to fail. I think because the analyzer moves the constant 0 to the divisor.

**Comment by Simn** [comment]
Err... wrong issue

**Comment by Simn** [comment]
The Java target will be put in "regression fixes only" state with the Haxe 4.3.0 release. See https://github.com/HaxeFoundation/haxe/wiki/Target-Support-Level#java-and-c-since-430 for additional information. We apologize for any inconvenience this causes!
