### ISSUE TITLE
[display] "new |" completion includes abstracts without constructors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7051]
```haxe
package cases;

class Issue7051 extends DisplayTestCase {
	/**
	class Main {
		static function main() {
			new {-1-}
		}
	}
	**/
	function test() {
		eq(false, hasToplevel(toplevel(pos(1)), "type", "Any"));
	}
}
```

Completion shouldn't ever produce code that doesn't compile:

![](https://i.imgur.com/da7DJ9V.png)

**Comment by Simn** [comment]
This is gonna be messy for the types we only get at syntax level. We have no way of finding e.g. a `@:forward'ed` constructor that way. The same applies to classes which don't have their own constructor, but inherit one from a parent class (while typing).

This makes me question my entire approach again. It seems we simply don't have enough information if we only rely on the syntactic representation.

**Comment by Gama11** [comment]
Hm... forwarded constructors in abstracts don't seem that common / like that big of an issue, but with class hierarchies, it seems quite problematic indeed...
