### ISSUE TITLE
[display] package / import / using keywords missing from completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7053]
Similar to #7052, there's no completion point here:

![](https://i.imgur.com/4dzOybE.png)

We should get the `import`, `using` and `package` keywords.

```haxe
|

class Main {
	static function main() {}
}
```

**Comment by Simn** [comment]
If you want to do down that route, we would also have to show `private` `extern` `class` `interface` `enum` `abstract` `typedef`. And after that you would want all the class field tokens when completing within a class.

I'm still not sure how I feel about this.

**Comment by Gama11** [comment]
That's all already on my TODO-list. ;)

I think it's ok to show _more_ keywords than are technically allowed in some specific location, but we probably should make sure that an allowed keyword is _missing_.

**Comment by Simn** [comment]
What keywords to show is not really the issue. Finding the completion points is.

**Comment by Simn** [comment]
Alright let's try this. I have added this kind of completion as a delayed check, which means it's only going to trigger if nothing else triggers. That should prevent situations where it's too eager, such as `class C implements |`.

I've also taken the liberty to add completion after type-level flags: `final`, `extern` and `private`. This one is not delayed because I don't think it could get in the way of anything. And yes, it only shows the flags that aren't present already. <strike>And yes, it only shows `class` and `interface` if there's a `final` in the flags.</strike> And yes, if there's `final` in the flags it only shows `class` and `interface` (and `extern` and `private` if they aren't there yet).

**Comment by Gama11** [comment]
Nice! This seems to suffer from the same problem as `extends` / `implements` keyword completion did initially: mid-word completion fails, e.g. when it's triggered on `imp|`.

**Comment by Gama11** [comment]
Also, `import` and `using` are correctly filtered out after a type, but `package` is still suggested.

**Comment by Simn** [comment]
I'll fix the package problem.

And uuuurgh about that mid-word completion. That is so annoying to handle and never happens in real life. :(

**Comment by Gama11** [comment]
It happens all the time - the _other case_ almost never happens in real life. ;)

When I type an import, I don't press Ctrl+Space and wait for completion to pop up to then select `import` from the list - I start typing the `import` keyword, and then VSCode triggers completion while I'm typing that. Somewhere along the way after a few characters, I'm probably going to press enter instead of bothering to type out the rest.

In this example, the first time completion is invoked is at `e|`:

![](https://i.imgur.com/MGXDP9n.gif)

**Comment by Gama11** [comment]
>And yes, it only shows class and interface if there's a final in the flags.

Hm.. that only seems to work if there is nothing else in the file, neither of these cases work (before or after another type):

![](https://i.imgur.com/KM3zVgJ.png)

![](https://i.imgur.com/6tyb7HF.png)

**Comment by Simn** [comment]
That's the same resuming problem as in that other issue of yours.

**Comment by Gama11** [comment]
Ah, I see. Would it be hard to avoid showing these keywords while we're inside of a type? I guess that's sort of equivalent to handling field-level keywords?

![](https://i.imgur.com/3xFOEPd.png)

**Comment by Simn** [comment]
That's a compiler state problem. x)

**Comment by Simn** [comment]
Fixed the state thing and your incomplete identifier situation.

What's next in this quest-chain?

**Comment by Gama11** [comment]
Another minor thing: it works at `| class`, but not `|class`. I think we had a similar issue with metadata completion before `var` / `function` once.

**Comment by Gama11** [comment]
And `abstract` should still be suggested after `enum`. ;)

**Comment by Simn** [comment]
> And abstract should still be suggested after enum. ;)

As discussed, this isn't going to work well.

**Comment by Simn** [comment]
Wow this issue is a mess... any idea what was left to do here?

**Comment by Simn** [comment]
I'll just consider this resolved. Feel free to reopen if there are still problems.
