### ISSUE TITLE
[display] display should ignore missing HXML files

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7054]
There's no reason completion can't work here, but it unnecessarily fails because the HXML file isn't there:

```
> haxe --display Main.hx@43 nonExistantHxml.hxml
Error: Could not process argument nonExistantHxml.hxml (file not found)
invalid character:
```

```haxe
class Main {
	static function main() {
		
	}
}
```

That error should probably be ignored during display.

**Comment by Simn** [comment]
It seems wrong to me to randomly ignore this in display mode. We don't ignore invalid command line arguments in general, and I don't see why we should make an exception for missing hxml files.

Ultimately, we should work towards passing all arguments via the json-rpc protocol anyway and can then make it more lenient.

**Comment by Gama11** [comment]
>Ultimately, we should work towards passing all arguments via the json-rpc protocol anyway and can then make it more lenient.

I don't think that's gonna work (without parsing the HXML files). The directly referenced HXML file could be valid, while some indirectly referenced one (referenced from that HXML file) could still be invalid.

**Comment by Simn** [comment]
I have no idea what you're talking about, so you're basically scaring me into reopening the issue.

**Comment by Gama11** [comment]
Well, imagine you have a `build-debug.hxml` that only has this, and that `build.hxml` doesn't exist:

```hxml
-debug
build.hxml
```

Right now the language server doesn't know anything about that second, "indirect" HXML file, and would have to actually recursively parse the HXML files to find out about it.

**Comment by Simn** [comment]
The whole idea is that hopefully there's a future where nobody has to parse hxml files.
