### ISSUE TITLE
[display] implements keyword should not show up for interfaces

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7062]
Follow-up for https://github.com/HaxeFoundation/haxe/issues/7052 - only `extends` is valid here:

![](https://i.imgur.com/OAM9huo.png)

**Comment by Simn** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/f486b3440bf16f4c3b2ee9cbefa0f2b82f32cee8
