### ISSUE TITLE
[display] signature help should not pop up with commas in structures

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7063]
```haxe
class Main {
	public static function main() {
		trace({
			foo: 1,
		});
	}
}
```

In the case of `wasAutoTriggered` (currently always true in the language server), there should be no signature results here:

![](https://i.imgur.com/H206T5g.png)

Probably can't add a test for this because it requires `wasAutoTriggered` and whatnot.

**Comment by Simn** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/be6f08ed67ae30839c67ebde862c227c29da7f14
