### ISSUE TITLE
[display] signature help not working properly anymore

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7065]
After https://github.com/HaxeFoundation/haxe/commit/5d529f23fb617d4b2080999585642fc332d17134, there's a regression where signature help doesn't appear to work anymore for `trace`. It seems it can only be reproduced with the new protocol, i.e. this works as expected:

```haxe
package cases;

class IssueTemplate extends DisplayTestCase {
	/**
	class Main {
		static function main() {
			trace({-1-}
		}
	}
	**/
	function test() {
		trace(signature(pos(1)));
	}
}
```

The failure message is `Message: source/Main.hx:4: characters 3-8 : Unknown identifier : trace`. Interestingly, triggering signature help at `trace(|"")` works, while `trace(|)` doesn't.

**Comment by Gama11** [comment]
Actually, this doesn't seem trace-specific after all, I was just testing that fix at the time... Maybe related to the fix for https://github.com/HaxeFoundation/haxe/issues/7063...

**Comment by Simn** [comment]
I couldn't reproduce this with `trace(|`, only with `trace(|)`.
