### ISSUE TITLE
[display] haxe.Int64 incorrectly reported as shadowed

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7073]
![](https://i.imgur.com/N0EpAFa.gif)

The qualified name is inserted here instead of generating an import because `importStatus` is 2 (shadowed).

**Comment by Simn** [comment]
That doesn't reproduce for me, it is being reported as auto-import.

**Comment by Gama11** [comment]
Huh.. This in in HaxeRepro on the C++ target. It seems to depend on the selected target. It's fine in Java for instance.
