### ISSUE TITLE
use singleton companion because haxe=>java compile has a bug with static function call wrapped on Dynamic.

### ISSUE THREAD

**Issue by wiltonlazary** [HaxeFoundation/haxe#7079]
When call a static function Dynamic wrapped.
c++: pass
js: pass
java: returns null object

**Comment by Simn** [comment]
Please provide a minimal, reproducible example that does not depend on any libraries or external code.

**Comment by wiltonlazary** [comment]
//java android problem: HaxeJavaTestEngine.execute();

typedef CommandLocal = {
	payload: Dynamic
}

class HaxeJavaTestBase {
    public static function create(engine:Dynamic, payload:Dynamic) : HaxeJavaTestBase {
        return null;
    }

    public function new(){
    }

    public function runTest():String{
       return "OK";
    }
}

class HaxeJavaTestBaseCompanion {
    public function new(){
    } 

    public function create(engine: Dynamic, payload:Dynamic): HaxeJavaTest{
        return HaxeJavaTest.create(engine, payload);
    }
}

class HaxeJavaTest extends HaxeJavaTestBase {
    public static var companion = new HaxeJavaTestBaseCompanion();

    public static function create(engine: Dynamic, payload:Dynamic): HaxeJavaTest{
        return new HaxeJavaTest();
    }

    public function new(){
        super(); 
    } 
}

class HaxeJavaTestEngine {
    public var categories: Map<String, Dynamic>;
    public var categoriesByCompanion: Map<String, Dynamic>;

    public function new(){
        categories = [
			"createTest" => HaxeJavaTest.create
        ]; 

        categoriesByCompanion = [
			"createTest" => HaxeJavaTest.companion.create
        ]; 
    }

    public function runTest(command: CommandLocal){
        var payload = command.payload;
        
        var componentByCompanion = categoriesByCompanion[payload.category]({});
        trace("componentByCompanion create => HaxeJavaTestEngine.runTest:", componentByCompanion.runTest());
        
        var component = categories[payload.category]({});
        trace("component create => HaxeJavaTestEngine.runTest:", component.runTest());
    } 

    public static function execute(){
        (new HaxeJavaTestEngine()).runTest({payload:{category : "createTest"}});
    }
}
