### ISSUE TITLE
[display] struct field completion vs. object literal return #2

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7081]
```haxe
package cases;

class Issue7081 extends DisplayTestCase {
	/**
	typedef Struct = {
		?fieldA:Int,
		?fieldB:String
	}

	class Main {
		static function main() {}
		function foo():Struct {
			var item = {
				fieldA: 5,
				{-1-}
			}
			return item;
		}
	}
	**/
	function test() {
		var results = fields(pos(1));
		eq(1, results.length);
		eq("fieldB", results[0].name);
		eq("var", results[0].kind);
		eq("Null<String>", results[0].type);
	}
}
```

Same as #7066, except that the object literal is assigned to a var before returning it.

**Comment by Simn** [comment]
This isn't valid because there's no expected type here. It works if you type-hint `var item:Struct`.

**Comment by Gama11** [comment]
I know that fixes it, but I dislike having to redundantly declare the type on the var too. There _is_ an expected type, just on the return.. Does type inference during completion not "think that far ahead", or why does this work in regular compilation and not here?

**Comment by Simn** [comment]
The expected type plays no part in normal compilation either. You create a normal structure which just happens to be assignable to the return type structure. None of the other features of declaring a structure against an expected type work here either.

**Comment by Gama11** [comment]
Oh well... more explicit type hints in the code it is.
