### ISSUE TITLE
[display] ClassFieldOrigin isn't set properly in static import completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7087]
![](https://i.imgur.com/25GPqB0.png)

Notice the `from ''` which is caused by all the `origin.args` on the right (except `class`) being undefined (empty strings + null_pos).

**Comment by Simn** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/commit/33bbdf5c82843c2c1c28ab6e4a7c3c16617a53a8
