### ISSUE TITLE
[display] missing import diagnostics outside of type hints

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7088]
Somehow it seems we now need to be in a type-hint position to get import suggestions, while it also worked fine in this case in 3.4.7:

![](https://i.imgur.com/5bkqvEr.png)

With latest:

![](https://i.imgur.com/LSXbyMY.png)

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/77c8f75f0d6866b35b07db4d67cb7ccb8db30bae
