### ISSUE TITLE
[display] ClassFieldOrigin for structures

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7090]
![](https://i.imgur.com/gtpF1Mf.png)

I think the `origin` here should be `Self` / `0`, so it shows "from Iterable" rather than "from anonymous structure".

**Comment by Simn** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/commit/60e4983b31e44718e27d479429fb1a3b31078a27
