### ISSUE TITLE
[js] polyfills consistency

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#7091]
Following closed issue #6478, partly duplicate of another issue, however the case of some compat classes has still to be discussed:

- `js.Promise` doesn't come with a polyfill,
- `haxe.Json` doesn't come with a polyfill by default, but you can force using a Haxe version with `-D haxeJSON`
- `ArrayBuffer`, `UInt8Array`, etc. come with a (relatively heavy and [mostly useless][1]) polyfill.

The position of most JS libraries nowadays is to target "evergreen" browsers and let adding polyfils the responsibility of the developer, so at the very least, it should be possible to disable/enable the compat classes with a compiler flag. Maybe for Haxe 4?

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

**Comment by back2dos** [comment]
Perhaps at least `-D js_es=6` or something should get rid of the polyfills.

**Comment by ncannasse** [comment]
I'm fine with disabling ArrayBuffer IE9 polyfill by default, we simply need a flag to enable it back

**Comment by elsassph** [comment]
Putting them behind a flag is what I suggest indeed, but I'd suggest a flag to enable them and default to no polyfill by default.

Maybe `-D html_compat`?

**Comment by nadako** [comment]
Isn't that what @ncannasse meant? :)

**Comment by elsassph** [comment]
If the flag is agreed, someone (me?) can pick it up and a PR ;)

**Comment by RblSb** [comment]
Maybe already existing `old_browser` flag?

**Comment by elsassph** [comment]
Oh, what does it do?

**Comment by RblSb** [comment]
At the moment, this replaces the json parsing with the haxeJSON version, if the browser does not support JSON.
https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/haxe/Json.hx#L41

**Comment by R32** [comment]
what about `-D polyfill-typedarray` for `ArrayBuffer`?

**Comment by Simn** [comment]
I don't think this is 4.0-critical, unless somebody feels responsible.

**Comment by ncannasse** [comment]
It's quite a small thing to do actually. Lets make it happen in 4.0

**Comment by haxiomic** [comment]
Given TypedArray support is at [95.6%](https://caniuse.com/#search=typedarray) and rising, I think we should drop the polyfill in favor of leaving it up to the developer to handle. When targeting old browsers it would be better to use one of the popular and a fully fleshed out polyfills like [typedarray.js](https://github.com/inexorabletash/polyfill/blob/master/typedarray.js)

**Comment by ncannasse** [comment]
@elsassph what would be your recommandation ?

**Comment by elsassph** [comment]
Honestly, just drop all polyfills for Haxe 4. All the JS polyfills exist and we shouldn't have to maintain special ones.

**Comment by Simn** [comment]
Yes let's please do that! We're still having DCE issues with our polyfills anyway.

**Comment by haxiomic** [comment]
Here's a PR to removed the TypedArray polyfill https://github.com/haxiomic/haxe/pull/1 (it's done on top of the externs update)

I tested heaps, openfl/lime, flixel and kha and only found 1 reference to js.html.compat which I've fixed in this PR
https://github.com/openfl/lime/pull/1234

**Comment by elsassph** [comment]
Awesome @haxiomic!

Next would be to hunt these `#if old_browser`. Requiring a JSON polyfills is so last century :D

**Comment by haxiomic** [comment]
The TypedArray polyfill has been removed however I've left one part required for IE10 support https://github.com/HaxeFoundation/haxe/pull/7444 but it'll only be emitted if `ArrayBuffer.slice` is used in ≤ ES5

**Comment by haxiomic** [comment]
`old_browser` is only used in `std/js/_std/haxe/Json.hx`, here's the [diff with it removed]( https://github.com/HaxeFoundation/haxe/pull/7477/files).

I agree it's not required because you can just pass `-D haxeJSON` if you target Firefox 3 and IE 7

@elsassph Does that close this issue?

**Comment by elsassph** [comment]
@haxiomic happy to close the issue of course, though strictly speaking `-D haxeJSON` polyfill should probably be dropped from Haxe 4, IMHO.

**Comment by haxiomic** [comment]
I think keeping `-D haxeJSON` is ok because it provides extra features like support for haxe enums and StringMaps which users might want to enable

**Comment by elsassph** [comment]
@haxiomic oh that's a good argument. If it adds value then it's useful - is that clear in the doc?

**Comment by haxiomic** [comment]
It's not in the `--help-defines` doc but it should be, it's just [here: haxe.Json](https://api.haxe.org/haxe/Json.html) at the moment

**Comment by Gama11** [comment]
It's also mentioned in the manual: https://haxe.org/manual/std-Json-implementation-details.html

**Comment by elsassph** [comment]
Cool, the details are there indeed. Old browsers mention will have to be removed though.

**Comment by haxiomic** [comment]
Agreed – added to todo list
