### ISSUE TITLE
[feature request] Retain hex values in the output (if so-specified in the source)

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#7095]
Currently haxe auto-converts any hex value in the source code to the proper _int_ representation in the target language. This may make for less-than-optimal debugging (generated code is harder to read than the original representation), especially when bit juggling.

I guess there may be some issues with this (32 vs 64 bit comes to mind), but I still think this would be a nice and useful feature to have.

PS: not really fair (as it only translates to js, which only has the Number type), but for example TypeScript leaves the hex values unchanged in the output.

**Comment by Simn** [comment]
I'm not against it from any design point of view or anything, there's just no practical way to implement this in our architecture. It would require changing the type of `tconstant.TInt`, which is not a change I am willing to make at the moment.
