### ISSUE TITLE
Lambda utility functions should return Arrays

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#7097]
For Haxe 4, we want to change the `Lambda` class methods to return `Array<T>` instead of `List<T>`.

e.g.
```haxe
filter<A> (it:Iterable<A>, f:A ‑> Bool):Array<A>
```

**Comment by kevinresol** [comment]
Maybe add `ArrayTools` and deprecate `Lambda`?

**Comment by elsassph** [comment]
Makes sense, this may be quite a breaking change.

**Comment by back2dos** [comment]
That's what `-lib hx3compat` is for ;)

**Comment by Simn** [comment]
I agree, we can move current Lambda to hx3compat and add better Lambda to the standard library.

Accepting PRs!
