### ISSUE TITLE
[display] goto definition not working on enum abstract value until diagnostics have run

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7098]
This seems to require two modules to reproduce, so no test `DisplayTestCase` for this one. With the following two files, `display/definition` on `Value` in `Bar.foo(Value);` returns no results:

```haxe
class Main {
	public static function main() {
		Bar.foo(Value);
	}
}
```

`Bar.hx`:

```haxe
@:enum abstract Foo(Int) {
	var Value = 0;
}

class Bar {
	public static function foo(f:Foo) {}
}
```

The reason why it requires two modules is that it only seems to reproduce _when `Bar.hx` hasn't been opened yet_ (doing so would run diagnostics on it, which seems to resolve the problem).

This is _not_ a regression (same behavior in 3.4.7). `-D no-copt` also doesn't help.

**Comment by Simn** [comment]
```
PS C:\GitHub\HaxeRepro> haxe --display source/Main.hx@59@position
<list>
<pos>C:\GitHub\HaxeRepro\source\Bar.hx:2: characters 6-11</pos>
</list>
```

Are you sure about it not being a regression?

**Comment by Gama11** [comment]
Yeah... this _does_ seem like the sort of issue that only reproduces in server mode / within the IDE.
