### ISSUE TITLE
[display] completion inside single quote strings should only work in interpolation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7104]
```haxe
package cases;

class Issue7104 extends DisplayTestCase {
	/**
	class Main {
		public static function main() {
			'${-1-}';
			'${{-2-}}';
			'$${-3-}';
			'foo{-4-}bar';
		}
	}
	**/
	function test() {
		eq(true, toplevel(pos(1)).length > 0);
		eq(true, toplevel(pos(3)).length > 0);
		eq(false, toplevel(pos(2)).length > 0);
		eq(false, toplevel(pos(4)).length > 0);
	}
}
```

**Comment by Simn** [comment]
I've decided that this is too annoying to be worth looking into. It doesn't show completion when it's auto-triggered, which is good enough. If you explicitly request completion there then you'll have to live with the nonsense.

**Comment by Gama11** [comment]
>It doesn't show completion when it's auto-triggered, which is good enough

That's exactly why this is a problem though: I'd really like to auto-trigger on `$`...
