### ISSUE TITLE
Small DCE regression maybe

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7107]
I was comparing the Haxe 3 and 4 versions of https://github.com/damoebius/HaxeBench and while the overall size is smaller, there's this thing that for some reason shows up:

![](https://i.imgur.com/Lq1ZJhz.png)

It's not referenced anywhere, so I wonder where it comes from.

**Comment by Simn** [comment]
It goes `Timer.stamp()` -> `Date.now()` -> `return js.Syntax.construct(Date)`. That causes `Date` to be kept and then its `fromString` pulls `HxOverrides.strDate(s)`.

I'm not sure why this behaves differently from 3.4.7 which also used `Date` as an expression.

I'm also not sure what to do about this.

**Comment by RealyUniqueName** [comment]
Shouldn't it keep `Date` class but not its fields?

**Comment by RealyUniqueName** [comment]
Especially taking into account `fromString` is an inline field of an extern calss.

**Comment by Simn** [comment]
I think we keep all fields of `extern` classes. Maybe we should only keep those that don't have expressions, i.e. are truly extern.

**Comment by RealyUniqueName** [comment]
I cannot reproduce this with the latest development:
```haxe
class Main {
	static function main () {
		trace(Date.now());
	}
}
```
```
$ haxe -main Main -js test.js
```
```js
// Generated by Haxe 4.0.0-rc.4
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("Main.hx:5:",new Date());
};
Main.main();
})({});
```

**Comment by Simn** [comment]
Could you also check https://github.com/damoebius/HaxeBench?

**Comment by RealyUniqueName** [comment]
Also doesn't contain `strDate`. 
Problem solved!
