### ISSUE TITLE
Why does it not work for -java-lib with external jar files with haxe?

### ISSUE THREAD

**Issue by sourceskyboxer** [HaxeFoundation/haxe#7109]
Hello everyone, I really want test.

But it doesn't get success.

Stop forcing me with stupid errors.

It looks like old example:
```
package;

import java.lang.System;
import javax.swing.JPanel;
import javax.swing.JFrame;
import java.awt.Color;

class Graphics2DExample extends JFrame
{
    
    public static function main() 
    { 
        new Graphics2DExample(); 
    } 
    
    public function new()
    {
        // The view windows title.
        super('Graphics 2D Example');
        // Specify to use Hardware rendering.
        System.setProperty("sun.java2d.opengl","True");
        // Set window size to 700 pixels wide by 500 pixels high.
        setSize( 700, 500 );
        // Add a close button to window.
        setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        // Set the background to black.
        setBackground( Color.black );
        // Centre the view window in centre of users screen.
        setLocationRelativeTo(null);
        // Show the view window.
        setVisible( true );
    }
    
}
```

I have tried with command:
`haxe -java java -java-lib rt.jar -main Graphics2DExample`

Than it gives result:
`Graphics2DExample.hx:4: characters 7-25 : Type not found : javax.swing.JPanel`

I have already tried no success.... i have copied and pasted to root directory of Graphics2DExample.hx 

And no successful compilation

**Comment by andyli** [comment]
Haxe moves the `javax` package to `java.javax`. I think the idea is to group all Java APIs under the `java` package. So, instead of `import javax.swing.JPanel;`, do `import java.javax.swing.JPanel;`. Similar for `JFrame`.

**Comment by sourceskyboxer** [comment]
Thanks I will try

and it works fine. Wow! Why does haxe make wrong package's path? I really don't understand tutorials explain bad adn please fix and improve haxe's getting starteds website! Thanks

I don't know import java.javax.* before - I thought that old version works with import java.javax.* and it is same too.

Thanks for explanation!

**Comment by kevinresol** [comment]
@sourceskyboxer which tutorial in particular?

**Comment by sourceskyboxer** [comment]
It is very old tutorial from haxe's tutorials
