### ISSUE TITLE
<@:const T> is not working somitemes as expected. 

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#7113]
Hi,
here is two cases when <@:const T> generates wrong code:
https://try.haxe.org/#9EFd8
https://try.haxe.org/#e8C7b

It is by design or it is an issue? 
Thanks.

**Comment by Simn** [comment]
The first case works fine on current development.

The second one uses `untyped` which apparently takes priority over type parameters. That's something we should fix.
