### ISSUE TITLE
Incorrect completion, only when code is generated by a macro

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7114]
I'm getting incorrect completion for code generated by a macro. If I literally type out the same expressions that the macro generates, completion works fine.

Here's a simple code example (completion fails in both vshaxe and try-haxe): http://try-haxe.mrcdk.com/#5F6f0

The goal of the macro is wrapping an expression in a block, and attempting to redefine the type of the variables in the inner, wrapped block. It tries three different ways to accomplish this, and they have three different results. Here's a GIF of the issue:

![completion](https://user-images.githubusercontent.com/2192439/40801819-1fab6316-64d1-11e8-80ea-bdafcb6ce92c.gif)

- **macro_injected:**  macro injects a new variable :arrow_right:  completion works :heavy_check_mark: 
- **macro_override_var:** Macro redeclares variables from the outer block with a different type :arrow_right: completion recognizes the proper inner type `String`, but then typing `.` it shows member functions of the type in the outer scope (`oh_no__wrong_completions`). :x: 
- **macro_override_cast:** Macro swaps the identifier with a cast :arrow_right: completion shows the type from the outer scope. :x:

And, as I mentioned, if I literally write the same expression the macro generates, completion works for all three strategies, recognizing the types in the inner block as `String`:

![selection_999 2417](https://user-images.githubusercontent.com/2192439/40802027-b3bad0aa-64d1-11e8-9c27-f8e3426ae7df.png)

FYI, mentioned this to @Gama11 and @back2dos

**Comment by jcward** [comment]
@Gama11 Is there a way I can try vshaxe with `-D no-copt` ?

**Comment by Gama11** [comment]
Assuming this is a pure Haxe project, just add it to your HXML? :) If OpenFL, the usual `<haxedef>` will do.

**Comment by jcward** [comment]
Ah, I forgot the display call uses the same parameters as the project.

Interesting, adding `-D no-copt` fixed the second case (creating a variable in the inner scope with same name, different type), but it did not fix the third case, which replaces:

  `EConst(CIdent(ident))` ==> `((cast ident):InnerType)` 

Hmm.

**Comment by Simn** [comment]
With `-D no-copt`, they all work for me on current development.

The problem is that completion optimization optimizes the call away, which doesn't work with macro arguments for obvious reasons. I don't think it should optimize away the call anyway if the display position is within the call arguments.

**Comment by jcward** [comment]
> With -D no-copt, they all work for me on current development.

Ah, good to know. Sorry, I was testing on 3.4.7.

> The problem is that completion optimization optimizes the call away...

If that were true, I wonder why the first case is working, though -- the macro introduces a new var that completion is aware of, so it must be being called, right? I wonder... if it is being called, perhaps the optimization is that it's not re-typing idents it's already typed (from the outer scope)? Just hypothesizing...

**Comment by Simn** [comment]
Unfortunately, keeping the call is not even enough: The syntax-based optimization figures that `macro_override_var` is already defined and assumes that you mean to complete on it, so the variable injected by the macro is never seen by the display logic. This is very similar to #4345.

I think it's time to retire this identifier-based optimization. It causes various issues like this and I refuse to believe that it has any measurable impact on completion speed.
