### ISSUE TITLE
Updated specification for Std.is / safe cast

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7115]
Given there was a disagreement over the specification of Std.is / safe cast, I'm using my dictatorship power to move forward for Haxe 4.0:

`Std.is(null,T)` should be false : `null` value has no runtime type information attached so while it's a valid value for a variable of type T it's not an object instance of T either, which is what Std.is is checking.

`cast(null,T)` should be null (not throw), because in that case we convert the value `null` to type T and it's valid value for this type. Also both `(null : T)` and `(cast null : T)` works. That's the way type casting works in C#, Java, and many other languages.

Requirements:
- write corresponding unit tests
- ensure platforms compliance
- document platform changing behaviors for release notes

Additional checks:

- null can only be caught by `catch( e : Dynamic )`
- `cast(null,Int|Float|Bool)` : on static platforms, return the default value (same as unsafe cast). on dynamic platorms, returns null.
- `Std.is(null,Int|Float|Bool|Dynamic)`: should be `false` on all platforms as well

**Comment by ncannasse** [comment]
The new one will be `if (Std.is(v, T) || v == null ) cast v else throw "Class cast error"`

**Comment by Simn** [comment]
Sure, but `Std.is(cast(null, T), T)` being false is still ridiculous.

**Comment by ncannasse** [comment]
I don't want another discussion topic, thanks

**Comment by Simn** [comment]
Closing in favor of #7532.
