### ISSUE TITLE
Cannot compile try/catch as a right-side expression in Flash9

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#7117]
This is a time-traveling zombie from the list/past (https://groups.google.com/forum/#!topic/haxedev/_Msdk5u7QJM).

I know this is flash-only, but is there any walkaround?

**Comment by Simn** [comment]
The example I posted there doesn't reproduce the issue. If you have a reproducible example, please share it.

**Comment by azrafe7** [comment]
Yes, I though it was the same issue but it wasn't.

Here's how I can reproduce it on my machine:
```haxe
class Main {
  static function main() {
    switch (USED_IMPL) {
        case ONE: trace('impl $ONE');
        case TWO: trace('impl $TWO');
        default: throw "unreachable";
    }
  }
  
  static public var USED_IMPL(default, null):Impl = {
    var impl:Impl = null;
    
    try {
      throw "something";
    } catch (e:Dynamic) {
      trace('something catched');
      impl = ONE;
    }
    return impl;
  }
}

@:enum abstract Impl(String) to String
{
  var ONE = "one";
  var TWO = "two";
}
```

**Comment by Simn** [comment]
First of all: http://www.sscce.org/

```haxe
class Main {
	static function main() { }

	static public var x = {
		try { } catch (e:Dynamic) { }
		null;
	}
}
```

Then, this definitely falls under the "obscure flash bug" category. Something must be wrong with genswf's stack handling in static inits or something. There's no rhs try/catch in the dump.

That's as far as I'm willing to investigate this. The workaround is to not have try/catch in your static inits I suppose. You can always wrap your inits in a function.

**Comment by azrafe7** [comment]
@Simn that link is a bit offending, please don't do that.

My bad for assuming the issue was the same from the list, but wasn't the example I posted afterwards SSCC enough? Sure it could have been reduced further (as you've done), but that's why I asked for more expert eyes on the matter.

Yes, no hard feelings and thanks for re-looking at it, but your answer just put me somewhat off.
