### ISSUE TITLE
Regression in [dev]

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7120]
Travis reported me a strange bug in my latest Heaps commit (against Haxe dev).

See https://travis-ci.org/HeapsIO/heaps/jobs/386641757

the incriminated line is:

`var t = try inlineThatReturnsFloat() catch( e : Dynamic ) -1;`

I have fixed it there for now: https://github.com/HeapsIO/heaps/commit/7fb1beeeb76956a1cf2b498f5e0459b49874665c

**Comment by Simn** [comment]
Bah, I always forget that `WithType` can be a monomorph...
