### ISSUE TITLE
macro $b vs $a

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/haxe#7122]
http://try-haxe.mrcdk.com/#e2d59 works.

http://try-haxe.mrcdk.com/#3aCC8 fails.

http://try-haxe.mrcdk.com/#C788F not even about array comprehension.

why it needs `$a{${[]}}`?

------
btw I really hope this can be added as a built-in utility (probably with an even shorter name).

or in the code cookbook.

"remember the day you type `trace("a+b="+(a+b))`?"

it's so sweet for making debug info readable while typing less, being both simple (no much reasonable variant) and powerful.

------
or even `trace('$${a+b})'`?

**Comment by Simn** [comment]
`$a` when used as a call argument expands its array as the argument list. This is a bit inconsistent, but at this point I don't think we should change it.
