### ISSUE TITLE
Arrays of objects becames Array<Dynamic> on many targets. 

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/haxe#7125]
Hello.
If we declare an Array as:
`var entities:Array<Entity> = new Array<Entity>();`
where Entity is a regular Haxe class, then it will be generated as below for cpp target:
`::Array< ::Dynamic> entities = ::Array_obj< ::Dynamic>::__new();`
Also, on Java and C# this array will contains `Object` (aka Dynamic) too. Not sure about other targets.

The problem is that `Dynamic` is pretty slow in many cases, especially on cpp target. 
Just imagine situation when you have 2 millions triangles in array (discribed as `class Triangle {var x:Float; var y:Float; var z:Float;}`) and you iterate through it every frame. So, this will proveke unnecessary casting from `Dynamic` item inside array to the `Triangle`. 
 
Would be nice if Haxe could generate propertly typed arrays.

Thank you ;)

**Comment by ncannasse** [comment]
The fact that it generates an Array of Dynamic does not mean it's slow. If everytime an element is read from the Array it's cast to the proper type before access you will not have extra cost (in cpp) and it will actually save code size by not having many different versions of the Array template class generated.

**Comment by dmitryhryppa** [comment]
Well, here is what I've got:
![Image](https://i.imgur.com/vIdsBHy.png)

The result from Timer.measure is:
```
App.hx:24: 0.19065934270529s        //array as is
App.hx:25: 0.0807505839888986s    // unsafeGet
App.hx:26: 0.0391371858809978s    //without Dynamic and casting
```
So, strictly typed Array is about 6 time faster then Array of Dynamic.

There is still a problem with Array of Dynamic is that it is not very nice when you use generated by Haxe code as external lib, for example, in Java. Because in that case you can push anything to this kind of array and then broke something inside the lib.

**Comment by Simn** [comment]
What Haxe version is that? Can you test using a [nightly build](http://build.haxe.org/builds/haxe/)?

**Comment by dmitryhryppa** [comment]
That was Haxe 4 preview 3. 
But with 3.4.* I had the same behaviour (casting was even slower). 
Here is results from latest nightly build, I've executed it three times:
```
src/App.hx:24: 0.181781284055676s
src/App.hx:25: 0.0816914205142081s
src/App.hx:26: 0.0396159823053225s

src/App.hx:24: 0.189500984278845s
src/App.hx:25: 0.0792533754682461s
src/App.hx:26: 0.0388942191925686s

src/App.hx:24: 0.187337246452004s
src/App.hx:25: 0.0791202557883788s
src/App.hx:26: 0.0371323228236018s
```

**Comment by Simn** [comment]
I didn't expect it to make such a difference. Could you post your benchmark code?

I wonder if this regressed at some point because I seem to remember it working just fine with the Dynamic being cast away.

**Comment by dmitryhryppa** [comment]
Sure, here is it:
```
package;
import haxe.Timer;
using cpp.NativeArray;

class Vec3 {
    public var x:Float;
    public var y:Float;
    public var z:Float;
    public inline function new(x:Float, y:Float, z:Float) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
    
    public inline function add(vec:Vec3):Vec3 {
        return new Vec3 (x + vec.x, y + vec.y, z + vec.z);
    }
}

class App {
    static var MAX_OBJECTS:Int = 2000000;

    public static function main():Void {
        Timer.measure(() -> testFunc1());
        Timer.measure(() -> testFunc2());
        Timer.measure(() -> testFunc3());
    }
    
    private static function testFunc1():Void {
        var arr:Array<Vec3> = new Array<Vec3>();

        for (i in 0...MAX_OBJECTS) {
            arr.push(new Vec3(0, 0, 0));
            arr[i].add(new Vec3(i, i, i));
        }
    }
    //unsafe get
    private static function testFunc2():Void {
        var arr:Array<Vec3> = new Array<Vec3>();
        for (i in 0...MAX_OBJECTS) {
            arr.push(new Vec3(0, 0, 0));
            arr.unsafeGet(i).add(new Vec3(i, i, i));
        }
    }

    //without Dynamic
    private static function testFunc3():Void {
        untyped __cpp__('
        ::Array< ::Vec3> arr = ::Array_obj< ::Vec3>::__new();
        for (int i = 0; i < {0}; ++i) {
            arr->push({1});
            ::Vec3 _this = arr->__get(i);
            Float vec_x = ( (Float)(i) );
            Float vec_y = ( (Float)(i) );
            Float vec_z = ( (Float)(i) );
            Float _hx_tmp = (_this->x + vec_x);
            Float _hx_tmp1 = (_this->y + vec_y);
            ::Vec3_obj::__alloc( HX_CTX ,_hx_tmp,_hx_tmp1,(_this->z + vec_z));
        }
        ', MAX_OBJECTS, new Vec3(0, 0, 0));
    }
```

**Comment by hughsando** [comment]
Yes. Reversing the order of the tests reverses the result (it is always the first one that is slower).
This is probably because a GC is triggered somewhere in the middle of the first test.

**Comment by Simn** [comment]
Ha, tricky tricky benchmarks! I can confirm these findings.

**Comment by dmitryhryppa** [comment]
Oh, that's interesting. 

But there is still a problem with Array of Dynamic when you use generated classes from Java, C# or Cpp...
In Java and C# you can pass into this arrays anything, which is not good (and most people use this targets exactly for sharing logic). 
So, this is still important to have stricly typed arrays.

**Comment by hughsando** [comment]
There are 2 problems with this (it actually used to be this way). 1 the
code size increases - about 20k per array class - possibly not that bad.
and 2. Some real problems with Array<Dynamic> and casting from things like
Json.parse.  If Array<X> is typed, then Array<Array<X>> and
Array<Array<Array<X>>> is too.  So if you assign a 3-deep array from
Dyanmic (eg, Json.parse)  you need to traverse all the elements and cast
them to their appropriate array types.
The use case of writing raw hxcpp is not enough for me to want to deal with
the other complications.

**Comment by dmitryhryppa** [comment]
I thought generated Array is generic, so why it should increase in size?
Also, usually people parse Json on startup and once, so it's not a big cost... But maybe I'm wrong. 

Anyway, for usability I'm wondering about this more for Java and C# targets. 
For example, here is implementation of the generated Array for Java target:
```
public final class Array<T> extends haxe.lang.HxObject {
	public final int push(T x)
	{
           (.....)
        }
}
```
It is generic and already works perfect with any Java class and there is no necessary to generate a lot of classes for each type separately.
And there is not too much sense of this generic implementation if it is always generated for class fields as Array<Object>.
