### ISSUE TITLE
Type hint of static inline var being ignored

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7132]
```haxe
static inline var GAME_TIME:Float = 20;
$type(GAME_TIME); // Int
```

**Comment by Simn** [comment]
Whaaat...

**Comment by Simn** [comment]
Fix wasn't good. There's already some code which tries to convert int to float, but it ends up with something insane like a TFloat being typed as Int...

**Comment by Simn** [comment]
Actually that fix might still be good for the non-Int/Float case because we don't want to lose the field type in these situations either. But we definitely shouldn't have float constants that have integer types.
