### ISSUE TITLE
[display] structure field order for expectedType

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7135]
This is basically the same issue as #7072, except for the `expectedType` / `expectedTypeFollowed` APIs. In regular structure field completion, the order of fields now matches the order they're declared in:

![](https://i.imgur.com/8D3fJtC.png)

For the expected type APIs, this is not the case - they're still missing the sorting. Code generated based on that will have a seemingly random order because of that:

![](https://i.imgur.com/OQy65La.png)

Ideally, the sorting should be done everywhere, not just for `expectedType` / `expectedTypeFollowed`?

**Comment by Simn** [comment]
Wouldn't it make more sense to let the IDE handle this? We only need the sorting once we actually generate code, so it's better to sort the fields at that point. Otherwise we would need an extra pass over all types that may need sorting.

**Comment by Gama11** [comment]
You mean by only sorting them for `resolve`? That would technically clash with the spec again, I think...

>However, properties that are needed for the inital sorting and filtering, like `sortText`, `filterText`, `insertText`, and **`textEdit`**, must not be changed during resolve.
