### ISSUE TITLE
Unclear instructions for manual installation

### ISSUE THREAD

**Issue by pypmannetjies** [HaxeFoundation/haxe#7140]
I want to install Haxe from the Linux binaries distributed here: https://haxe.org/download/ 

So far the steps I have followed are:
1. Download and extract the tar.gz file
2. Add extracted folder to path
3. Install neko
4. Export the HAXE_STD_PATH environment variable
...?

None of this is documented anywhere and has led to a lot of trial and error. The official process should be provided somewhere for others to reference.

**Comment by Simn** [comment]
That's something for https://github.com/HaxeFoundation/haxe.org
