### ISSUE TITLE
[js] why Class.__name__ is an array?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7141]
```haxe
class Test {
    static function main() {
        Type.getClassName(Test);
    }
}
```
generates
```js
Type.__name__ = ["Type"];
```
and
```js
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) {
		return null;
	}
	return a.join(".");
};
```

I wonder why we don't just store the `String` in the `__name__` field?

I don't see it used for anything other than null checking and `getClassName`, so I think if we store the dot-path directly it would improve the performance for `Type.getClassName` which is I believe a quite often used function across haxe code bases.  

If no answer will follow, I'll just change it :)

Ping @ncannasse

**Comment by ncannasse** [comment]
It's meant to avoid having one string in memory per full class name. Instead you have one string per name and then package strings are reused. That works well on platforms that doesn't have some kind of smart substring indexing in JIT/compiled code. I am not sure how it applies to JS

**Comment by nadako** [comment]
That makes sense, but I wonder if the benefit covers the overhead of allocating these strings for each `Type.getClassName` call.

Of course we usually wouldn't call `getClassName` for all the classes in the compilation, so maybe it makes sense to somehow cache the dot path? Although this is getting more complex now...

**Comment by kevinresol** [comment]
I wish there are some ways (a define?) to know that it is changed because it is going to [break hxgenjs](https://github.com/HaxeFoundation/haxe/issues/7141)

**Comment by ncannasse** [comment]
I think it's go for these operations to be slightly not as optimized as they could be, because it's more related to Reflection etc. Please close if you agree :)

**Comment by nadako** [comment]
Normally I wouldn't care too much about reflection, but since I have to deal with a large codebase that uses it a lot at the moment, I'll probably do some benchmarks and see if non-array version performs any better.

**Comment by nadako** [comment]
So the non-array version is much faster:

```
src/Main.hx:21: Array
src/Main.hx:22: 1.441999912261963s
src/Main.hx:28: String
src/Main.hx:29: 0.01900005340576172s
```

I think we should just generate dot path strings, since they will be allocated by `getClassName` anyway (not for every class though, but still). And this functions is used a lot, especially in the code ported from another languages. My current case is the AS3/Flash codebase that uses Dependency-Injection framework for everything. So `getClassName` is called *a lot* here and it shows up in the profiler. And I think that's quite a typical example. 

Also if one doesn't use `getClassName` in their code, the `__class__` is not even generated, so reflection-free code is not affected.

---
Benchmark code:
```haxe
class Some {
	public static var array = ["my", "pack", "Some"];
	public static var string = "my.pack.Some";
}

class Main {
	static function main() {
		measure(Some);
	}

	static function getArrayName(cls):String {
		var arr = cls.array;
		return if (arr == null) null else arr.join(".");
	}
	inline static function getStringName(cls):String return cls.string;

	static function measure(cls:Dynamic) {
		var N = 10000000;
		var v = null;

		trace("Array");
		haxe.Timer.measure(function() {
			for (_ in 0...N)
				v = getArrayName(cls);
		});
		if (v != "my.pack.Some") throw "assert";

		trace("String");
		haxe.Timer.measure(function() {
			for (_ in 0...N)
				v = getStringName(cls);
		});
		if (v != "my.pack.Some") throw "assert";
	}
}
```

**Comment by back2dos** [comment]
I agree. If you use reflection, it usually goes both ways so the dot path is in the output anyway.

Ideally we'd also have `$hxClasses[TheClass.__name__] = TheClass` if both `resolveClass` and `getClassName` are used.

**Comment by jdonaldson** [comment]
+1 for me since I like to keep super exotic datastructures like arrays out of the static initialization step for Lua.  :)

**Comment by nadako** [comment]
I would rather not add a flag for this, because Haxe 4 is supposed to be breaking anyway, but I can do it if there's no workaround for this...

**Comment by kevinresol** [comment]
Is there some way to guard things at a finer level?

**Comment by Gama11** [comment]
No.
