### ISSUE TITLE
consider taking out some member functions from standard Array and move them into ArrayTools

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/haxe#7145]
Like `StringTools`, just preserve those essentials as member functions, and let the rest be imported on-demand. (of course not so bad like c or lua, let's find a good point.)

I think this will help with bloating binary size and compilation time when targetting C++ (if someday we stop letting everything `::Array<Dynamic>`).

Also consider letting others be `@:generic`. Generate functions selectively and let them run efficiently, why not? I don't think all those fancy array operations will be called on Arrays of each type, and in fact many of them are not frequently used.

**Comment by Simn** [comment]
This would break usages of Array through Dynamic, which would mean pointless regressions.
