### ISSUE TITLE
Feature request: Haxe compiler --color option

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7146]
Has colorized compiler output already been suggested? Does it exist and I just don't know about it?

It could be hidden behind a `--color` option like `ls`, or whatnot.

Here's the situation: Normally, my build script colorizes the output of Haxe:

![color](https://user-images.githubusercontent.com/2192439/41123129-e3fcb4ca-6a5a-11e8-9725-a091b9c2c3a2.png)

But I ran it by hand today and was shocked at the unreadability without colorization. Especially when developing macros that trace stuff, and errors mixed in with output, etc, etc. 

![bw](https://user-images.githubusercontent.com/2192439/41123139-e88e230c-6a5a-11e8-8504-b0e0a1401b0c.png)

Thoughts:
- Ideally warnings / errors would be colored differently.
- Should apply to:
  - Compiler-generated errors
  - Context.error
  - Context.warning
  - `#error "uh oh"` pragma
  - Are there others? Why does there not exist a corresponding `#warning` pragma?

Apparently [ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code), which work in Linux and OSX, are now supported (maybe have to be enabled) [in Windows 10 TH2 (v1511)](https://superuser.com/a/1050078/112532)?

**Comment by jgranick** [comment]
In addition to the example C++ code I shared on the linked topic, here's an open-source project that appears to be doing something similar for OCaml

https://github.com/ocaml/opam/blob/master/src/core/opamConsole.ml#L240-L263

I'd like to ask for ANSI color support on the "eval" target

**Comment by nanjizal** [comment]
Noticed this Ocaml library - perhaps also relevant:
https://github.com/pqwy/notty

**Comment by Simn** [comment]
This would be somewhat nice to have, but I'll be honest and say that we don't have the time to look into something like this at the moment. Pull requests are obviously always welcome though.
