### ISSUE TITLE
[display] sort static extension methods below other fields in dot-completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7149]
I think it would be preferable if the order here was reversed (first all fields, then static extension methods at the bottom):

![](https://i.imgur.com/ltLdbLc.png)

```haxe
using Main.Main;

class Main {
	public static function main() {
		var s:Struct;
		s.
	}

	static function staticExtension(s:Struct) {}
}

typedef Struct = {field:Int}
```

Right now, it seems the order is rather random, here's a real-world example:

![](https://i.imgur.com/Fw8YVmB.png)

**Comment by EricBishton** [comment]
I don't necessarily agree.  But I do think that sorting them is IDE dependent and not something that the compiler should be worried about.

**Comment by Gama11** [comment]
The IDE would be free to sort things however it wants if it chooses to do so, but I think it makes sense for Haxe to apply some sensible "default sorting", especially in positions where there's an expected type.

**Comment by EricBishton** [comment]
I get where you're coming from.  It's a cost trade-off.  Sorting in the compiler may (will!) be unnecessary work if the IDE is going to re-process them.  Every client will pay the price (in every request), whether it's minimal or not.

**Comment by Gama11** [comment]
I'm fairly confident that cost is negligible compared to how long a requests takes due to protocol overhead and whatnot. If you think there's a good chance that's it's actually noticable, we could measure how long exactly sorting takes usually, I guess.

**Comment by Gama11** [comment]
Hm.. sometimes the order is reversed?

![](https://i.imgur.com/JQP1Rcd.png)

But this case is as expected onw:

![](https://i.imgur.com/eiqCWg2.png)
