### ISSUE TITLE
[display] sort accessors below other functions in override generation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7150]
Similar to #7149, the sorting of methods in override completion seems a bit random at the moment:

![](https://i.imgur.com/O5Glcy7.png)

I think the following order would be better:

- (all other functions)
- `get_` functions
- `set_` functions

And maybe sort alphabetically within those groups?

**Comment by EricBishton** [comment]
Second verse. Same as the first!

Sort it in the language server, if you like.  Don't put the burden (or the runtime cost) on the compiler.

**Comment by Simn** [comment]
I'm ambivalent about this. They should definitely at least be sorted alphabetically, but from Haxe's point of view these accessors are just normal methods.
