### ISSUE TITLE
[display] not enough info for valid code generation with module subtypes

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7152]
If you have a function such as `function foo(value:Type.ValueType) {}`, Haxe currently reports the following in override completion:

```json
"args": {
    "path": {
        "pack": [],
        "name": "ValueType",
        "importStatus": 1
    },
    "params": []
}
```

This is not enough information to generate valid code, as `import ValueType` or `value:ValueType` is not valid - basically, we're missing the module name (`Type`), and it doesn't make sense to add it to `pack`.

After some discussion, @Simn and I agreed that `JsonPath` in the protocol should probably be redesigned into four different structures to cover all possibilities:

```haxe
typedef PackagePath = {pack:Array<String>};
typedef ModulePath = PackagePath & {moduleName:String};
typedef TypePath = ModulePath & {typeName:String};
typedef StaticFieldPath = TypePath & {fieldName:String}
```

**Comment by Simn** [comment]
You forgot about `importStatus`.

**Comment by Gama11** [comment]
Oh, right. :)
