### ISSUE TITLE
[Static extension] Cannot have two static extensions with the same name and different arguments

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#7157]
One cannot have multiple functions used as static extensions and accepting different arguments:

```haxe
using Test;

class Test {
    static function main() {
        "a".helper("a"); // Will fail with "Too many arguments"
    }
}

class Helper1 {
    public static function helper(a:String, b:String):Void {}
}

class Helper2 {
    public static function helper(a:String):Void {}
}
```

While this particular situation is avoidable, it is not always the case. In the original subject of this issue, I had the same problem with dlls loaded with `-net-lib` for the cs target, which are defined as seen below.

I looked into the sources and found what was going on: the first possible candidate for static extension is used, regardless of its compatibility regarding arguments other than the first one.

I couldn't get far in trying to change this, since the code responsible for this doesn't seem to know anything about the current arguments (`["a"]` here) so it doesn't seem to be able to check against the function's arguments.

Also, if we continued to look for a compatible function when we only found one with the first argument matching, one would end up with a "X has no field Y" error instead of a typing error. That doesn't seem too easy to handle; at least I can't do anything about it myself.

---
## Old description:

When loading dlls with `-net-lib`, we can have static extension classes with `@:overload`, but cannot use the overloaded ones.

Like for example `Microsoft.Extensions.Configuration.JsonConfigurationExtensions` from https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/2.1.0
```haxe
@:realPath("microsoft.extensions.configuration.JsonConfigurationExtensions") @:nativeGen @:abstract @:final @:libType @:csNative @:native("Microsoft.Extensions.Configuration.JsonConfigurationExtensions")
extern class Microsoft.Extensions.Configuration.JsonConfigurationExtensions {

	@:final @:overload
	static function AddJsonFile(builder:Microsoft.Extensions.Configuration.IConfigurationBuilder, path:String):Microsoft.Extensions.Configuration.IConfigurationBuilder;

	@:final @:overload
	static function AddJsonFile(builder:Microsoft.Extensions.Configuration.IConfigurationBuilder, configureSource:cs.system.Action_1<Microsoft.Extensions.Configuration.Json.JsonConfigurationSource>):Microsoft.Extensions.Configuration.IConfigurationBuilder;

	@:final @:overload
	static function AddJsonFile(builder:Microsoft.Extensions.Configuration.IConfigurationBuilder, provider:Microsoft.Extensions.FileProviders.IFileProvider, path:String, optional:Bool, reloadOnChange:Bool):Microsoft.Extensions.Configuration.IConfigurationBuilder;

	@:final @:overload
	static function AddJsonFile(builder:Microsoft.Extensions.Configuration.IConfigurationBuilder, path:String, optional:Bool, reloadOnChange:Bool):Microsoft.Extensions.Configuration.IConfigurationBuilder;

	@:final @:overload
	static function AddJsonFile(builder:Microsoft.Extensions.Configuration.IConfigurationBuilder, path:String, optional:Bool):Microsoft.Extensions.Configuration.IConfigurationBuilder;
}
```

I use it like this (similar to how I did it in C# before porting to Haxe):
```haxe
using microsoft.extensions.configuration.JsonConfigurationExtensions;

builder.AddJsonFile('appsettings.json', true, true);
```

But Haxe doesn't resolve to the correct static extension, and fails with `Too many arguments`.

I am using haxe 4 e6a1ae9 build from yesterday (June 7th), building with `-D net-ver=45`

**Comment by kLabz** [comment]
@nadako @waneck can you think of any workaround to make it work until this is fixed within haxe?

**Comment by kLabz** [comment]
Any idea what could be done or where to look at?

**Comment by kLabz** [comment]
FYI, to reproduce this without -net-lib, this code is enough (will need to be compiled with a compatible target, cs for example):

```haxe
using Test;

class Test {
	public static function test() {
		"test".helper(); // Not enough arguments, expected b:String
	}
}

extern class Helper {
	@:overload
	public static function helper(a:String, b:String):Void;

	@:overload
	public static function helper(a:String):Void;
}
```

**Comment by kLabz** [comment]
Actually that can somehow be applied to other targets as well: https://try.haxe.org/#cf117
Not sure if this one is worth it, though.

**Comment by kLabz** [comment]
While it is more problematic with cs, this is not a cs-only issue and is linked to static extension.

I updated the description accordingly. Could the labels be updated?

**Comment by Simn** [comment]
#5596
