### ISSUE TITLE
[regression] inline change

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7163]
I was comparing the output of Northgard code before/after inlining changes.
In heaps h3d.scene.Renderer, we do the following call:

```
haxe.ds.ListSort.sortSingleLinked(passes, function(p1, p2) return p1.depth > p2.depth ? 1 : -1);
```

New inlining correctly inline the comparison function but also keep it in a local var in the final AST while it's unused.

**Comment by ncannasse** [comment]
Everything else seems to be generating exact same code, good job ;)

**Comment by nadako** [comment]
Normally those local vars are eliminated by local DCE, but I see some cases where it isn't while also causing the "ref-array" wrap of the captured var, like this:

```haxe
class Main {
	static inline function call(f) {
		trace(f());
		trace(f());
	}

	static var array = [1, 2, 3];

	static function main() {
		for (o in array) {
			call(() -> o);
		}
	}
}
```

js:

```js
Main.main = function() {
	var _g = 0;
	var _g1 = Main.array;
	while(_g < _g1.length) {
		var o = [_g1[_g]];
		++_g;
		(function(o1) {
			return function() {
				return o1[0];
			};
		})(o);
		console.log("src/Main.hx:3:",o[0]);
		console.log("src/Main.hx:4:",o[0]);
	}
};
```
