### ISSUE TITLE
[display] display/references not working on static field import

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7168]
Find references here finds no results - I'd expect to find all usages of the field in the current module (and maybe only those in the current module?):

![](https://i.imgur.com/sd0P342.png)

**Comment by Gama11** [comment]
(note: hover and goto definition _are_ working from there)

**Comment by Simn** [comment]
It occurred to me that the entire implementation relies on the assumption that field names start with a lower-case character, which isn't correct...

**Comment by Gama11** [comment]
Syntax highlighting relies on that as well. :D
