### ISSUE TITLE
[display] new protocol should return file name paths with proper casing on Windows

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7173]
The file paths returned by display requests on Windows has traditionally always been all-lowercase (rather than what they actually are on the file system). In vshaxe, we need a very ugly workaround for this to avoid files getting opened twice with different cases:

https://github.com/vshaxe/haxe-languageserver/blob/970219041d33cf3fe44446f7a0fd60b8f7c8e9be/src/haxeLanguageServer/HaxePosition.hx#L71

![](https://i.imgur.com/XfYfUdo.png)

Haxe would probably need something similar, but it could maybe be more optimized than whatever vshaxe currently does. We should look into fixing this at least for the new display protocol. I'm not sure if editors other than VSCode have this issue, but it seems quite likely that some would.

**Comment by nadako** [comment]
`Path.get_real_path` does this and is implemented in C so should be quite fast (it still does FS queries tho).

**Comment by Simn** [comment]
I thought we were doing that already. How do I reproduce this?

**Comment by Gama11** [comment]
Just look at the output of e.g. workspace symbols, the paths are all-lowercase:

![](https://i.imgur.com/vLIuPU6.png)

Interestingly, you may be right - it seems some display methods may already return the proper file name case. I'm getting the correct file path in `display/definition` at least.

**Comment by Simn** [comment]
But workspace-symbols is old protocol

**Comment by Gama11** [comment]
True... and I definitely did need to fix it for the new protocol's goto definition at some point, so I'm a bit confused: https://github.com/vshaxe/haxe-languageserver/commit/dd83a4a4a09206ee8f6c682e1b25e7331c859b5c#diff-636a434b81caaae61489f407f03f157b

I wonder if Haxe's behavior changed since then...

**Comment by Simn** [comment]
The `get_real_path` has been there from the start: https://github.com/HaxeFoundation/haxe/commit/464e59cb64ce6967a157ec0e7943e82b69835a4e#diff-9cbf30a8ea6d37085d49fc730e25f898R72

So I think this is resolved.
