### ISSUE TITLE
[typer] Void should probably not be allowed in type hints

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7174]
It seems funny the following compiles, because you can't really _do_ anything with the `Void` argument ("Void is not a value", you can't even assign it to Dynamic!):

```haxe
class Main {
	public static function main() {}
	function foo(v:Void) {}
}
```

While it otherwise isn't seem too problematic, CPP for instance (unsurprisingly) actually fails with native compilation errors on this:

```
./src/Main.cpp(28): error C2182: 'v': illegal use of type 'void'
```

**Comment by Gama11** [comment]
Hm, perhaps a duplicate of https://github.com/HaxeFoundation/haxe/issues/3463.

**Comment by Simn** [comment]
It is indeed.
