### ISSUE TITLE
Add "Hello World tests" for all targets to CI

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7176]
Right now there's a bug where (only) Hello-World-projects fail to compile on C# and Java. It's scary that something like this can slip through CI - rather than just a huge test suite, there should probably also be decidated "Hello-World-tests" to find issues specific to Hello-World-optimizations.

CC @nadako @andyli

(note: the issue is not quite as bad as I made it sound, this seems specific to compiling through the compilation server with caching - those specific scenarios should probably be covered by these tests too!)

**Comment by Gama11** [comment]
The mentioned issue ended up being about disabling module checks with the `initialize` --display method, so that should probably be tested too.

**Comment by Simn** [comment]
I don't think anyone would actually look into this, so I'll just close it.
