### ISSUE TITLE
Array declaration after inner function treated as array access

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#7180]
```haxe
class Test {
  static function main() {
    function func():String {
      return "foo";
    }
    // remove the semicolon to break this:
    ;
    [
      "hello",
      "world"
    ].map(Sys.println);
  }
}
```

([try online](http://try-haxe.mrcdk.com/#972e0))

I'm not sure whether this is intended or not, though it did trip me up. It seems that inner function declarations do not require a semicolon like other expressions / statements. So in the above, if I just have an array with a single string / value, it warns me that array access is not possible on a `Void->String` function.

I've also just discovered that an inner function declaration like the above can have a name, and can be later reused:

```haxe
class Test {
  static function main() {
    trace([1, 2, 3].map(function double(n) return n * 2));
    trace(double(6));
  }
}
```

Which is why in the above code the function declaration is treated as a value I suppose.

Considering variable declaration is never usable as a value (or rather, is of type `Void`), and inner function declaration should surely just be syntactic sugar over variable declaration, is this not an inconsistency?

**Comment by Simn** [comment]
Huh, I thought we fixed that...

**Comment by Simn** [comment]
This works fine on Haxe 4.
