### ISSUE TITLE
Extensions with macro generics over abstracts

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7184]
We used to have an extension in the form:

```haxe
class Ext {
    public static function find<T>( it : Iterable<T>, f : T -> Bool ) : Null<T> { ... }
}
```

With 4.0-preview 4, these does not work anymore with types such as `hxbit.Proxy<Array<Int>>` which are macro generics evaluating to abstract `hxbit.ArrayProxy<T>`.

Is that intended or an unexpected regression?

**Comment by Simn** [comment]
That's #5924, so it's not working anymore as intended. Note that this has nothing to do with macro generics, it's about abstracts and their `@:to/@:from` casts.
