### ISSUE TITLE
Static extension method not resolved in haxe 4.0.0 preview 4

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#7190]
If I have a static extension called `SaveModelExtension` that extends the `app.Model` type like this one:

```haxe
package app;

import app.Model;

class SaveModelExtension {

    public static function loadSaved(model:Model, key:String):Bool {
        // Do save stuff
        return true;
    }

}
```

Then, in a subclass of the `app.Model`, say `MyModel`, I call `loadSaved('someKey');`:

```haxe
package app;

import app.Model;
using app.SaveModelExtension;

class MyModel extends Model {

    public function new() {
        loadSaved('root'); // Error
    }

}
```

I get an error in latest haxe 4.0.0 preview 4 version and it fails to compile/generate completion cache:

```
/Path/to/MyModel.hx:9: characters 9-18 : Unknown identifier : loadSaved
```

I need to prepend the static extension method call with `this.` to make haxe resolve it, like this:

```haxe
package app;

import app.Model;
using app.SaveModelExtension;

class MyModel extends Model {

    public function new() {
        this.loadSaved('root'); // Works
    }

}
```

The regression appeared on latest haxe 4.0.0 preview 4. It used to work fine up to preview 3 and versions below.

**Comment by Gama11** [comment]
This is mentioned in the changelog:

```
all : [breaking] disallow static extensions on implicit `this` (#6036)
```

**Comment by jeremyfa** [comment]
Ah, I see. Then I guess I will go with prepending ``this.``.
