### ISSUE TITLE
[display] Sometimes js/_std/Math is used

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7192]
![image](https://user-images.githubusercontent.com/576184/41376801-98820d42-6f5a-11e8-812a-bb3128b2fe2f.png)

When I hover/go to definition on some standard library classes in vscode, then it points to `js/_std/Math.hx` 
I expected the _real_ Math class, since that has API documentation.

Seen in Haxe 4.0.0 preview 4 / JS target

**Comment by Simn** [comment]
I'm not sure about this. It should certainly show the documentation, but I think go to definition should go to the actual implementation.

**Comment by nadako** [comment]
> Perhaps this is a case where we should report multiple definition locations?

I thought that was already the case, at least with the old protocol?

**Comment by Gama11** [comment]
Not that I'm aware. I don't think we have / had multiple definition locations anywhere so far.

**Comment by Simn** [comment]
Now I'm confused too because it's `DisplayPosition of pos list`

**Comment by nadako** [comment]
yep, I think I saw multiple locations before

**Comment by Simn** [comment]
Oh, actually that might be because it's used for references as well...

**Comment by Gama11** [comment]
Yay, much better now! :)

Funnily enough, it seems this is now fixed for all but Mark's `js/_std/Math` example, since `@:coreApi` is commented out there:

```haxe
// Can't enable @:coreApi because some fields are now inline getters
// @:coreApi
```

I'm guessing the inconsistent `get` access for some of these fields also causes https://github.com/HaxeFoundation/haxe/issues/6088, so that's problematic in multiple regards.
