### ISSUE TITLE
[display] Idea: hover hints for arguments

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7193]
Was trying vscode with Haxe 4.0.0 preview.4 today and had this idea to improve hover a bit:

Lets say I have this code:
```
function manyArgs(value:Int, position:Point, explode:Bool) {

}
```
And I call it like this:
![image](https://user-images.githubusercontent.com/576184/41377192-9d4fd68c-6f5b-11e8-9cad-20f986652ac0.png)

It would be nice if `Int` had bit more info and had something like:
```
Int
for argument `value:Int`
```

Also, from chat:
> _"@nadako this reminds me of my idea about parsing `@param` documentation and showing it on function call arguments hover"_

**Comment by Gama11** [comment]
Right now Haxe sends a `DisplayItemKind.Literal` for that... perhaps we should introduce a `DisplayItemKind.Argument`, which would allow us to still get whatever is under the cursor, e.g. a `Literal` like here, but also the argument itself (`DisplayItemKind.Local`).

**Comment by Gama11** [comment]
`CallArgument` is probably a better name actually.

**Comment by Simn** [comment]
I don't think this should be a distinct `DisplayItemKind`. It's more like a context of some sort...

It's also quite tricky to implement because Haxe doesn't really know the context either.

**Comment by Simn** [comment]
This works now!

**Comment by markknol** [comment]
That's so awesome. Good job!
