### ISSUE TITLE
Context.getBuildFields speedup

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7196]
`hxbit` is a macro library that is only inspecting fields metadata and generating some extra code based on it. It does not need (most of - expect @:rpc tagged) functions expressions, yet Context.getBuildFields takes the most CPU of it.

We should find a way to lazily encode (and memoize) Function.expr field access in eval.

**Comment by Simn** [comment]
I have added VLazy in https://github.com/Simn/haxe/tree/VLazy. Not quite sure if this is really the best approach. Also I didn't actually test if this helps with performance.

**Comment by ncannasse** [comment]
Looks good, please merge in haxe/development, I'll do the speed testing on Function.expr

**Comment by Simn** [comment]
You didn't complain yet so I assume this is working fine now.
