### ISSUE TITLE
[display] package completion broken for Hide

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7201]
Using latest Haxe + VSHaxe 2.0.1, top level completion on Hide is broken for package `hide.view`:

![image](https://user-images.githubusercontent.com/1022912/41400102-73186f58-6fbc-11e8-8e3c-e5ac9978458b.png)

I also get some other errors when asking field completion:

```haxe
[Error - 10:08:22] Request textDocument/completion failed.
  Message: hide/ui/Keys.hx:5: characters 13-41 : haxe.ds.Map does not have a constructor
hide/ui/View.hx:205: characters 34-119 : haxe.ds.Map does not have a constructor
hide/comp/Scene.hx:60: characters 17-55 : haxe.ds.Map does not have a constructor
Not_found
```

**Comment by ncannasse** [comment]
This is the `hide.view` package content:
![image](https://user-images.githubusercontent.com/1022912/41400499-9b5e1aca-6fbd-11e8-89a9-ecc8b70fe5f4.png)

**Comment by Simn** [comment]
Works for me:

![code_2018-07-30_07-49-56](https://user-images.githubusercontent.com/634365/43379521-3fc27eac-93cd-11e8-9780-e5893c2d3de9.png)

So either this was fixed or requires more specific circumstances to reproduce. I'll be assuming the former, please reopen if you can still reproduce somehow (with latest everything).
