### ISSUE TITLE
Top down inference with privateAccess

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7204]
```haxe
class Foo {
     var bar : Type.ValueType;
}

class Main {
     static function main() {
            var x : Foo = null;
            x.bar = TNull;
     }
}
```

Here the correct error should be `Cannot access private field bar`. But it gives `Unknown identifier TNull`

**Comment by Simn** [comment]
worksforme: `source/Main.hx:8: characters 13-18 : Cannot access private field bar`
