### ISSUE TITLE
Invalid Float optimization

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7205]
```haxe
function foo(x:Float) {
   if( !(x >= 0) ) trace("OK");
}
foo(Math.NaN);
```

This used to work in Haxe, but no longer because the compiler optimized it to `if( x < 0 )`. Such change in comparison operators should not be applied for Float values because every operation with `NaN` will return `false`.

**Comment by Simn** [comment]
I cannot reproduce this with the code you provide. Any special flags that might be relevant?

Furthermore, I looked at the implementation and it clearly has `is_int` checks for this case.

**Comment by ncannasse** [comment]
That was the fix I had to make:
https://github.com/HeapsIO/heaps/commit/f44628f33cef76f4d82515eee924faff88af740d

**Comment by ncannasse** [comment]
But that seems weird, since it's an Array<Int> there was no Float there in the first place...

**Comment by Simn** [comment]
I was about to say, those are integer operations...

**Comment by ncannasse** [comment]
Ah, I see, that was about a comparison between X and undefined (on Integer types)

**Comment by ncannasse** [comment]
```haxe
class Test {
	

	static function main() {
		var a : Array<Int> = [];
		function foo(x:Int) {
			if( !(a[x] > 0) ) trace("OK");
		}
		foo(0);
	}

}
```

Here's the code : it works on HL but not on JS.  But since everything can be undefined there, I think we should leave it as-it.
