### ISSUE TITLE
(Suggestions : xxxx) doesn't lookup super class

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7207]
That's quite fun we haven't noticed yet, but field names suggestions does not look at super classes.

**Comment by Simn** [comment]
It would help if you posted some example because I don't know what you mean.

**Comment by ncannasse** [comment]
```haxe
class A {
    public var longIdentifier : Int;
}
class B extends A {
     function foo() {
        return this.longIndentifie;
     }
}
```

If foo is in `A` it displays (Suggestion : longIdentifier), but not in `B`
