### ISSUE TITLE
[JS] Type.allEnums() exhibits inconsistent behavior

### ISSUE THREAD

**Issue by James1P** [HaxeFoundation/haxe#7209]
`Type.allEnums()` has inconsistent behavior on the JS target when compared to other targets. 

When `Type.allEnums()` is invoked on other targets, a new array instance is constructed with each call. But invoking `Type.allEnums()` on the JS target always returns a reference to the same underlying array, `e.__empty_constructs__`.  If the returned array is mutated in any way, all future callers of `Type.allEnums()` will now access the same mutated array.

Is this the intended behavior, or should this function always return a new array instance?

**Comment by nadako** [comment]
assigning to @ncannasse for spec clarification

**Comment by ncannasse** [comment]
I agree we should return a copy. When extra performance is required, developers can cache that copy in a static var. Let's add a unit test for it to make sure that removing something from that array does not affect the next Type.allEnums call.
