### ISSUE TITLE
[display] no field completion for switch subject

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7211]
I assume this is compiler fault.

![](https://i.imgur.com/YsOVBFq.gif)

```haxe
class Main {
	static function main() {
		var s:{f:String} = null;
		switch s.|
	}
}
```

**Comment by Jarrio** [comment]
I was having problems with vshaxe being extremely slow in completion, after downgrading to haxe preview 3, it fixed my issues. It appears like it also works for the current issue, so it may be an issue between haxe preview 3 and 4

![gif](https://user-images.githubusercontent.com/748557/42046682-4fa30674-7af6-11e8-86f1-6eeefcc7fe04.gif)
