### ISSUE TITLE
JSON regression ( Haxe 4, preview 4)

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#7212]
I'm using Haxe 4.0.0-preview.4 with the following code (https://try.haxe.org/#b22FD)
```haxe
import haxe.Json;

class MData 
{
	public var n:Int;
	public var v:Int;

	public function new(n:Int, v:Int ) 
	{
		this.n = n;
		this.v = v;
	}
	
}

class Test {

    public static function updateM(md:Array<MData>) : Void
	{
        for ( mValue in md) {
             trace(mValue.n);
        }
    }

    static function main() {
        var d:String = '[{"n":0,"v":0},{"n":1,"v":0},{"n":2,"v":0},{"n":3,"v":3},{"n":4,"v":0},{"n":5,"v":0},{"n":6,"v":0},{"n":101,"v":0}]';
        var jsn:Array<MData> = Json.parse(d);
        updateM(jsn);
    }
}
```
With Haxe 3.4.4 everything works. For latest preview 4 ( Haxe 4) get the following error:
  Uncaught exception Unexpected value VObject({v: 0,n: 0}), expected instance
src/Main.hx:  .. : characters 9-21 : Called from here

Error on updateM(jsn)

**Comment by nadako** [comment]
This is most probably related to the new eval interpreter being more strict, but this code is not supposed to work anyway, because `haxe.Json.parse` produces anonymous structure objects, not class instances, so you can't just use it like this.
