### ISSUE TITLE
try without catch doesnt generate try

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7213]
`try trace(1)` (without  `catch(e:Any) {}`) generates just `console.log(1)` (without being wrapped in try/catch blocks) in Haxe/JavaScript. (example: https://try.haxe.org/#2cc95)

Q: Is this intended behavior?

Expectation: Personally I expected `try { console.log(1); } catch(e) {}` in the output because of everything-is-an-expression™.

Seen in Haxe 3.4.7

**Comment by Simn** [comment]
> Q: Is this intended behavior?

A: Yes

I don't understand how "everything is an expression" relates to this. Allowing empty `try` can be useful in some conditional compilation cases.

**Comment by markknol** [comment]
Ok, clear. Could it be considered for Haxe4 to actually generate the `try` or does that have downsides Im missing?

**Comment by back2dos** [comment]
Not sure catch all and ignore is the best default here. In fact it contradicts "everything is an expression".

Example:

```haxe
var worked = try {
  somethingUnsafe();
  true;
}
catch (e:Dynamic) {
  false;
}
```

This is still valid, currently:

```haxe
var worked = try {
  somethingUnsafe();
  true;
}
```

Either worked becomes `true` or the stack gets unwound. 

Consider the case that the above would implicitly mean this:

```haxe
var worked = try {
  somethingUnsafe();
  true;
}
catch (e:Dynamic) {
}
```

This would error with `{} should be Bool` (could also be `Void should be Bool` if we'd make the compiler assume it's an empty block).

See https://try.haxe.org/#63F0b
