### ISSUE TITLE
Haxe doesn't properly recognize large integer values when specified as inline constants 

### ISSUE THREAD

**Issue by rwthompsonii** [HaxeFoundation/haxe#7216]
MVCE:

import haxe.Int64;
​
@:rtti 
class Hello 
{
    public static function main() : Void 
    {
        trace("Hello world" + Sys.args());
        var myInt1 : Int64 = 1;
        var myInt2 : Int64 = 3;
        var myInt3 : Int64 = myInt1 + myInt2;
        trace('value of myInt3: $myInt3');
        // var myInt4 : Int64 = 2654435769;
        // src/Hello.hx:14: characters 8-40 : Float should be haxe.Int64
        // WTF?
        var myInt4 : Int64 = 1327217884;
        myInt4 <<= 1;//double it and test bit shift simultaneously, since we need it 
        myInt4 += 1;
        trace('value of myInt4: $myInt4');
    }
}

//Haxe version 3.4.2

**Comment by haxiomic** [comment]
I believe haxe only supports 32 bit integer literals at the moment (which has caused quite a few headaches in the past)

However 64 literals are on the roadmap :)

https://github.com/HaxeFoundation/haxe/issues/5150

**Comment by rwthompsonii** [comment]
Thanks, just wanted to make sure you guys knew about it. And yeah, that workaround is cleaner than the one I used.

**Comment by Simn** [comment]
This is working as (currently) intended. Will be easier once we have proper Int64 literals.
