### ISSUE TITLE
[eval] Sys.exit stops build.hxml execution when used with `-x` or `--run` 

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#7217]
Using Sys.exit inside eval code run through an `-x` or `--run` option from a build.hxml will end execution of build.hxml, regardless of exit code.

The following sample prints `hello` when run with Haxe 3.4.7, nothing when running with Haxe dev build:
```
class Main {
    public static function main() {
        Sys.exit(0);
    }
}
```
```
-x Main
--next
-cmd echo "hello"
```

**Comment by Simn** [comment]
I'm not entirely sure if this is unexpected behavior...

**Comment by AlexHaxe** [comment]
yeah, I think I can understand why it happens (without looking at the actual code), but it's a new behaviour that might break build scripts (not sure how many though - might be a small number).

Of the two solutions
1. implement a fix for eval (wild guess: run it in a separate process)
2. document it as a breaking change

the second one is probably much easier, but it's not really obvious that a call to exit will also stop your build script.

**Comment by Simn** [comment]
Is that really new behavior? I remember adjusting some test build script to run the macro tests lasts because of this.

**Comment by AlexHaxe** [comment]
checkstyle's buildTest.hxml has used that behaviour for a few years now.
After fixing checkstyle to compile in dev builds, I noticed that it didn't run any `-cmd` after `-x TestMain`.
(it does now, because I simply skip `Sys.exit(0)` in case of `eval`)

So it's definitely a difference between 3.x and current dev.

**Comment by Simn** [comment]
Have to check this if it is a regression.

**Comment by Simn** [comment]
Are we talking about `-x` or `--run` here with regards to this being a regression? In 3.4, `-x` would run actual neko, so a Sys.exit would not be an issue. However, I'd still assume that `--run` would exhibit the same behavior. In 4.0, we changed `-x` to work like `--run` which would explain the changed behavior.

**Comment by AlexHaxe** [comment]
You are correct, `-x` prints `hello` in my example while `--run` does not, on Haxe 3.4.7.
So it's only a change in behaviour for `-x`.

**Comment by Simn** [comment]
In that case let's solve it via documentation.

**Comment by RealyUniqueName** [comment]
Is this ok?
```haxe
	/**
		Exit the current process with the given error code.
		
		(macro)(eval) Being invoked in a macro or eval context (e.g. with `-x` or `--run`) 
		immediately terminates 	the compilation process also preventing 
		the execution of any `--next` section of compilation arguments.
	**/
	static function exit( code : Int ) : Void;
```

**Comment by Simn** [comment]
Sounds good!
