### ISSUE TITLE
[display] Not_found error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7218]
When triggering completion in `hide/view/Model.hx` in function init(), I often get `Not_found` error. I am not sure how to get the stack in these conditions.

**Comment by ncannasse** [comment]
Maybe we could force stack trace to be displayed in completion server with `-v`

**Comment by Simn** [comment]
Can't you set HAXEDEBUG=1 or something?

**Comment by ncannasse** [comment]
Yes, works. I had `OCAMLRUNPARAM=b` but it was not enough.
