### ISSUE TITLE
[display] enum completion for `match` magic function is with "pattern" completion mode

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7223]
The following will be completed as `match(A(v):)` with current vshaxe, which is wrong :)

```haxe
enum E {
    A(v:Int);
}

class Main {
    static function main() {
        A(10).match(A|
    }
}
```

**Comment by Simn** [comment]
Even worse, I'm getting `AA(v)` when completing there so something is wrong with the replace range as well.

**Comment by Simn** [comment]
@Gama11 What mode do we want here?

**Comment by Gama11** [comment]
Originally I thought that we should maybe have a special `CompletionModeKind.Match` and insert `A(_)` instead, but that doesn't feel quite right either.. (what if you want `A(0)`?). Maybe just reporting regular toplevel completion here is best for now.

The other option would be to have the snippet insertion you have after `case` everywhere where an enum instance is expected (so `Pattern(var1, var2, var3)`). But that's kind of inconsistent with how we treat function calls and raises question what to do with optional arguments...
