### ISSUE TITLE
Wrong type parameter unification

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7227]
```haxe
class Test {
    static function main() {
        var struct:Struct = {url: 'www.example.com', method: 'GET'};
        var promise:Generic<Struct> = new Generic({url: struct, method: 'GET'});

    }
}

class Generic<T> {
  public function new(v:T) {}
}

typedef Struct = {
    url:String,
    method:String,
}
```

This COMPILES, but it should not.

This is a regression, worked in 3.2.1 and broken in 3.3.0-rc.1

**Comment by Simn** [comment]
I'm a bit nervous about this, but the code we had didn't make any sense to me: Unification of `TAnon` and `TAnon` should not be a special case. The only way to get into recursive problems there is through typedefs, which is the case that is already handled.

The concrete problem here was this: The unification handled `{url:String}` vs. `{url:Struct}`, pushed the pair `(String,Struct)` onto a stack and then proceeded to ignore it when recusing into `String` vs. `Struct` unification.
