### ISSUE TITLE
[display] wrong code completion for build macro (FunctionArg)

### ISSUE THREAD

**Issue by malublu** [HaxeFoundation/haxe#7228]
Not an important bug, but a bug. Version 3.4.7

![grafik](https://user-images.githubusercontent.com/14329224/41974126-52ceb710-7a17-11e8-9a26-1cfc1ffa49cf.png)
![grafik](https://user-images.githubusercontent.com/14329224/41974155-68117540-7a17-11e8-89e9-1caf508648c2.png)
```haxe
@:build(TestBuild.build())
class Test {
	public function new() {
		
	}
	public function test() {
		
	}
}
```
```haxe
class TestBuild {
	#if macro
	public static function build() {
		var fields = haxe.macro.Context.getBuildFields();
		for (field in fields) {
			if (field.name == 'new') continue;
			switch (field.kind) {
				case FFun(fn):
					fn.args = [{
						name: 'test',
						type: macro :String
					}];
				default:
			}
		}
		return fields;
	}
	#end
}
```
```haxe
class Main {
	static function main() {
		var t = new Test();
		t.test(|
	}
}
```

**Comment by Gama11** [comment]
What's the bug here? The hover without the argument in the second screenshot?

That's mosty likely a FlashDevelop issue. FD doesn't use the compiler for hover, but its own internal completion engine. In vshaxe, this looks correct even with Haxe 3.4.7:

![](https://i.imgur.com/gwBhpho.png)

![](https://i.imgur.com/MNXavmi.png)

**Comment by malublu** [comment]
Yes the hover.

Okay, that surprised me now.
I thought FlashDevelop (HaxeDEvelop) use the completion engine.

Thanks for the answer. I think I should try vshaxe.
Thanks for the answer.

**Comment by Gama11** [comment]
Well, it does, but not for everything. :)

If you do, maybe try with Haxe 4 preview 4, it works much better with that. ;)
