### ISSUE TITLE
Allow `...` as a unary prefix operator.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7234]
No default behavior. Must either be processed by macro or defined on an abstract.
The main motivation is of course to support ES6 spreads in inline markup. Current solutions support it anyway, since they all parse strings, but since we want to make inline markup a language feature, it'd help if the compiler were able to parse `...props`.

**Comment by back2dos** [comment]
@Simn: Well, perhaps we can deduce the "philosophy" by observing its past manifestation: We added `EIn` for SPOD, we added `OpArrow` for map literals and comprehensions, we added postfix `!` because it has interesting applications. Hell did not break loose. Well ... one could argue that `OpArrow` restricted our freedom in choosing an arrow function syntax. But in this case we're not adding a new token to the grammar.

So instead of applying some slippery slope argument, I'd say any such request will have to be evaluated per use case. As far as this one is concerned, it's definitely a thing - especially in conjunction with inline markup, which to the best of my understanding is something that's going to be added in one form or another.

**Comment by Simn** [comment]
> We added EIn for SPOD

That was merely a restructuring of something that already was an operator in all but name.

> we added OpArrow for map literals and comprehensions

Which almost prevented us from adding short lambdas, but we were lucky to find a different arrow (although we had to dodge a syntactic problem with that one as well).

> we added postfix ! because it has interesting applications

Which already was a unary operator, we just allowed it as a postfix version.

I don't think there has been a new unary operator since Haxe 1, and the only new binary operator in all this time was `=>`. I'm still not against adding `...`, but it remains a language design decision, which is why I'm asking Nicolas.

**Comment by back2dos** [comment]
>> We added EIn for SPOD
>
> That was merely a restructuring of something that already was an operator in all but name.

No, it was a deliberate choice to add new syntax for the only purpose of being able to interpret it in the SPOD macros: https://github.com/HaxeFoundation/haxe/commit/7f2e75e6d107dbfdcc9fe0ce4ebf047bdc009344#diff-91fbcb4b4bf054fec45bec21296f4f64

>> we added OpArrow for map literals and comprehensions
>
> Which almost prevented us from adding short lambdas, but we were lucky to find a different arrow (although we had to dodge a syntactic problem with that one as well).

Well, that's a bit dramatic. Also, what was the syntactic problem and more importantly: how would the option to use `=>` have avoided it?

>> we added postfix ! because it has interesting applications
>
> Which already was a unary operator, we just allowed it as a postfix version.

You can't "just allow a postfix version". Try with `OpNeg` and you'll see what I mean.

----

Of course it's a language design decision. It should be decided based on the use case that's behind and the potential issues it creates, not the fear of the pitchfork and torch wielding masses demanding ever more macro-interpreted operators, nor arbitrary "philosophy" that is tossed aside whenever it pleases the powers that be.

**Comment by back2dos** [comment]
Nope. My justification for adding this operator is the use case I gave and as pointed out twice already, that's what I would prefer to be discussed.

You've voiced your concern over setting a precedent and I'm merely showing that this most certainly wouldn't be one. And also that quite obviously no clear overarching philosophy has been practiced thus far on the grounds of which an addition like this is *categorically* wrong.

**Comment by ncannasse** [comment]
I'm not sure about it. 

This introduces some syntax that doesn't have any specific meaning/semantics in the Haxe language, so while I can see how some macros could expand it, it seems a very narrow usage. Not counting that it will require quite a lot of changes in many parts of compiler code because of handling (even as assert) of this new unop operator. I want that we close this one.

**Comment by Simn** [comment]
FWIW the amount of work to add this should be manageable. I've made changes that were way worse.

**Comment by frabbit** [comment]
How about  `..` which already exists?

**Comment by Gama11** [comment]
Where does `..` already exist?

**Comment by frabbit** [comment]
whats so bad about `{ ..x }` instead of `{ ...x }`

**Comment by ibilon** [comment]
> Iterators 1..10

are you sure? that doesn't seem to compile for me unless there's three dots

**Comment by frabbit** [comment]
oh, it is actually three dots, sorry i thought it was two ;), ignore my comments :D

**Comment by back2dos** [comment]
> This introduces some syntax that doesn't have any specific meaning/semantics in the Haxe language, so while I can see how some macros could expand it, it seems a very narrow usage. 

Well, deciding whether this is "narrow usage" or not is actually at the heart of the matter. This is needed for properly supporting JSX-ish markup and my position is that that's quite the use case. The ability to transparently pass properties through deeply composed UI is a real need and it's a matter of semantics much more than of syntax (unlike the ability to use `$name in ["a","b","c"]` in SPOD, rather than say `$in($name, ["a","b","c"]))`). It would be achievable otherwise (e.g. metadata \o/), but there's already an established notation at hand and supporting it would be no harder than the `EIn` to `OpIn` change.

**Comment by jdonaldson** [comment]
Cross-linking a related feature request : https://github.com/HaxeFoundation/haxe/issues/7306

**Comment by fullofcaffeine** [comment]
Cross-linking a related forum discussion: https://community.haxe.org/t/how-to-pattern-match-an-array-with-unknown-length/1367/5.

**Comment by back2dos** [comment]
Resolved via https://github.com/HaxeFoundation/haxe/pull/9961
