### ISSUE TITLE
[display] endless loop with diagnostics in _std file

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7236]
```haxe
class Main {
	public static function main() {
		[].concat([]);
	}
}
```

When I invoke goto definition on `concat()` here, the compiler gets stuck in an endless loop. In the output channel, it keeps repeating this line:

```
 2,  n: parsed c:\users\jens\github\haxe\std\neko\_std\array.hx (not cached, is display file)
```

At first I thought the problem was with goto definition, but it actually seems to be the diagnostics request that's fired as soon as the file is opened, so this can be reproduced by simply opening the file directly as well (`std\neko\_std\Array.hx` in this case). This doesn't seem limited to `Array.hx` either, opening other `_std` files like `Date.hx` also hangs the compiler (just without the repeating output).

This is a regression compared to Haxe 3.4.7, although opening a `_std` file there simply produced a `Display file was not found in class path` error. So the underlying issue might have been there already, with the error masking it.

___

Note: goto definition on `concat()` there should probably take you to the "API doc version" of `Array.hx` instead of the one in `_std` anyway?

**Comment by Gama11** [comment]
Adding a print here [reveals](https://github.com/HaxeFoundation/haxe/blob/6a0c87671816875cedd38be1fe37b6acf069cb9f/src/compiler/server.ml#L119) that the full loop looks like this:

```
 2,  n: parsed c:\users\jens\github\haxe\std\neko\_std\array.hx (not cached, is display file)
parsing c:\users\jens\github\haxe\std\neko\nativearray.hx
parsing c:\users\jens\github\haxe\std\neko\_std\string.hx
parsing c:\users\jens\github\haxe\std\enumvalue.hx
parsing c:\users\jens\github\haxe\std\enum.hx
parsing c:\users\jens\github\haxe\std\type.hx
parsing c:\users\jens\github\haxe\std\class.hx
parsing c:\users\jens\github\haxe\std\neko\lib.hx
parsing c:\users\jens\github\haxe\std\haxe\io\bytes.hx
parsing c:\users\jens\github\haxe\std\haxe\io\bytesdata.hx
parsing c:\users\jens\github\haxe\std\haxe\int64.hx
parsing c:\users\jens\github\haxe\std\haxe\int32.hx
parsing c:\users\jens\github\haxe\std\std.hx
parsing c:\users\jens\github\haxe\std\haxe\int64helper.hx
parsing c:\users\jens\github\haxe\std\stringtools.hx
parsing c:\users\jens\github\haxe\std\intiterator.hx
parsing c:\users\jens\github\haxe\std\ereg.hx
parsing c:\users\jens\github\haxe\std\stringbuf.hx
parsing c:\users\jens\github\haxe\std\math.hx
parsing c:\users\jens\github\haxe\std\haxe\io\error.hx
parsing c:\users\jens\github\haxe\std\haxe\io\fphelper.hx
parsing c:\users\jens\github\haxe\std\neko\boot.hx
parsing c:\users\jens\github\haxe\std\neko\_std\stringbuf.hx
parsing c:\users\jens\github\haxe\std\stdtypes.hx
parsing c:\users\jens\github\haxe\std\string.hx
parsing c:\users\jens\github\haxe\std\array.hx
parsing c:\users\jens\github\haxe\std\haxe\enumtools.hx
parsing c:\users\jens\github\haxe\std\neko\_std\stringbuf.hx
parsing c:\users\jens\github\haxe\std\neko\_std\string.hx
parsing c:\users\jens\github\haxe\std\neko\_std\array.hx
2,  n: parsed c:\users\jens\github\haxe\std\neko\_std\array.hx (not cached, is display file)
```

This endlessly repeats itself until `haxe.exe` runs out of memory.

**Comment by Gama11** [comment]
Stacktrace: https://pastebin.com/9q3HaKm5

**Comment by Simn** [comment]
This took me an hour and I don't even know why because it's really obvious. The problem was that the core API context inherited the `dms_check_core_api` flag from the real context. It then registered a core class check while loading the core class, which caused a core class check while loading the core class, which ...
