### ISSUE TITLE
Invalid parsing of untyped `cast` + new function type syntax

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7238]
```haxe
class Test {
  static function main() {
    var fn = (a, b) -> a + b;
    cast (a, b) -> a + b; //Error: Unexpected )
  }
}
```
http://try-haxe.mrcdk.com/#0eE89

**Comment by nadako** [comment]
The error message could be better, but the error is legit - it tries to parse `cast(value,Type) here, but since type must start with an uppercase letter, it thinks that `b` is a package name, so it expects a dot, not closing paren :)

**Comment by RealyUniqueName** [comment]
I understand that.
But maybe parser can figure out that this is a `cast functionDecl` since Haxe has no `expr -> expr` syntax.

**Comment by nadako** [comment]
Don't think it's easily achievable with current parser, but let's wait for @Simn to comment on that :)

**Comment by Simn** [comment]
Can't fix this for the reasons @nadako mentioned. It tries parsing the `b` as a type path and after that it's too late to recover.
