### ISSUE TITLE
Failing code completion inside closure on most recent Haxe

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#7240]
Not sure if this is the only pattern that makes it fail, but I can consistently get code completion error with code inside a closure like this sample:

```haxe
package;

class Main {

    function autorun(cb:Void->Void):Void {

    } //autorun

    public function new() {

        function test(name:String) {
            trace(name);
        }

        autorun(function() {
            test(|)
        });

    } //new

    public static function main() {

        new Main();

    } //main

} //Main
```

```
[Error - 12:17:22] Request textDocument/signatureHelp failed.
  Message: src/Main.hx:16: characters 13-19 : Call expected
  Code: -32603 
```

The code completion fails (no type hint when opening parenthesis of ``test()`` call).

Reproduced with haxe4 preview 4 and on latest nightly build as well, with latest vshaxe extension.

**Comment by ncannasse** [comment]
Similar to #7252, closing because my example is shorter :)
