### ISSUE TITLE
[js] inline functions of abstracts generate leftover functions 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7244]
I have an abstract with some `inline function`s. At call side they are nicely inlined, so that's not the issue.
But there are leftover _impl_ functions generated in the output, would be nice if those could be left out from the .js output.

![image](https://user-images.githubusercontent.com/576184/42286719-3a07451a-7fb4-11e8-87b2-69b5dc38558e.png)

Haxe 4.0.0-preview.4+1e3e5e016 
JavaScript target

**Comment by Simn** [comment]
Do you have DCE enabled?

**Comment by markknol** [comment]
Ill can double check, but normally I always turn all optimisations on :)

**Comment by markknol** [comment]
Ok I'm sorry, but I indeed forgot to add `dce=full`.

Everything is shiny again 💎
