### ISSUE TITLE
[display] Void->Void overload missing from display/signature

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7249]
(originally reported at https://github.com/vshaxe/vshaxe/issues/260)

```haxe
package cases;

class Issue7249 extends DisplayTestCase {
	/**
	class Main {
		public static function main() {
			q({-1-})
		}
	
		@:overload(function():Void {})
		@:overload(function(foo:Int, bar:Int):Void {})
		static function q(foo:Int) {}
	}
	**/
	function test() {
		eq(3, signature(pos(1)).signatures.length);
	}
}
```

The `Void->Void` overload is missing from the signature help results for some reason. Interestingly, it shows up in regular completion (notice the "+2 overloads"):

![](https://i.imgur.com/pdgrZl7.png)

**Comment by jcward** [comment]
Thank you! :+1:
