### ISSUE TITLE
Pseudorandom generator implementation 

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#7256]
At the moment in Haxe have two ways to get random number : Std.random(...) and Math.random()
Is it acceptable to be created new package Random ( or  part of haxe.crypto  )  with implementation of some pseudorandom generators such as : pcg , xorshift , splitmix , Mersenne Twister  ?
 I think strong algorithm such as PCG ( http://www.pcg-random.org/ ) is useful.

**Comment by flashultra** [comment]
Ok, I just wanted to know what other thinks, because from one side Crypto also  can be separate library , but it's essential part of  development ( security, base64 ...) . Maybe pseudorandom generator too ? 
For me, I almost always generate random numbers .

**Comment by Simn** [comment]
What Kevin said.
