### ISSUE TITLE
Detecting generated variables

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7258]
I'm trying to eliminate generated variables from inlined vars and other compiler generated things.
Up to now I did a check on variable name, but it did not work with inlined vars.

I now also check for both CompilerGenerated and ForLoopVariable but I still get many `_g` prefixed variables that I need to filter by name. Are there other metadata to check ?

**Comment by Simn** [comment]
This was addressed by Nicolas' tvar change.
