### ISSUE TITLE
[lua] lua.Lib.tableTo* functions (misleadingly) operate in place

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#7261]
I spent some hours today debugging something which turned out to be `lua.Lib.tableToArray(t)` changing my source data, which was completely unexpected given the array return.

To spare someone else the trouble, it'd be nice if this either returned a *new* array or had a doc comment that indicated this behavior, or maybe fail if the object is already using `_hx_array_mt`.

**Comment by jdonaldson** [comment]
I agree, this was not well documented.  These functions operate on a copy of the table now.  Docstrings have been added accordingly.
