### ISSUE TITLE
[display] TTypes in type params not followed for expectedTypeFollowed

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7262]
For a typedef to a structure, `expectedType` is a `TType`, while `expectedTypeFollowed` is a `TAnonymous` (this is the desired behavior and lets us generate object literals in vshaxe):

![](https://i.imgur.com/pNGj09I.png)

However, it seems that types within type parameters, such as `EitherType<PosInfos, Void->Void>` are _not_ followed, so we can only offer to generate a function here:

![](https://i.imgur.com/OiX7U3T.png)

**Comment by Simn** [comment]
I suppose there's a question here: Do we want to apply the "followed" state recursively, or do we want to have the followed/notFollowed distinction at each level? The latter is more general, but I'm not sure it's necessary.

**Comment by Simn** [comment]
To clarify: Instead of `JsonType` you'd get `{ type: JsonType, typeFollowed: JsonType }`.

**Comment by Simn** [comment]
... maybe `?typeFollowed` if it's `== type` to save some data. Not sure

**Comment by Gama11** [comment]
>Instead of JsonType you'd get { type: JsonType, typeFollowed: JsonType }

You mean everywhere where a type is reported? Or just in this specific case?

**Comment by Simn** [comment]
I mean for expected type only.

**Comment by Gama11** [comment]
Hm.. maybe, although I can't think of a use case for that right now.
