### ISSUE TITLE
Sys.io.File can't read and write

### ISSUE THREAD

**Issue by cjmxp** [HaxeFoundation/haxe#7263]
I hope you can increase the support for file read and write, similar to c++ fopen (path,"r+").

**Comment by jcward** [comment]
I'm confused what you're asking. The [sys.io.File](https://api.haxe.org/sys/io/File.html) API has lots of methods for read and writing files, both binary and String content.

Are you using one of the supported targets (cpp, hl, java, lua, macro, neko, php, python) or perhaps an unsupported one (js, as3, flash)?

Perhaps you are referring to nodejs? In this case, you need to run `haxelib install hxnodejs` and then add `-lib hxnodejs` to your commandline or .hxml file.

**Comment by jcward** [comment]
Nevermind, I see what you mean, `r+`, read and update. Hmm, I gotta admit, I don't really see the benefit of "read and update" in one operation. I suppose "read and update" is technically safer / faster than "read" followed by "append"?

**Comment by Simn** [comment]
To be honest, a feature request like this is probably not going to go anywhere. If you want to look into implementing it on a specific target, feel free to ask for directions.

The first step would be to determine which of our targets support such an operation.
