### ISSUE TITLE
import.hx and import stf.* on gitlab runner 

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/haxe#7270]
Sorry if this is not an issue

We started using gitlab because of free private repos and attempted to use the built in CI. To do that we put haxe and haxelibs into repo. We got around most issues (ln -s haxehaxelib /usr/bin/haxelib;) but for some reason the imports brought in with import.hx and import path.* do not resolve.

My guess is they rely on the os to resolve?  Or maybe it is a linux issue, or...?

**Comment by Simn** [comment]
The only special thing about import.hx is that it's filesystem-based, not package-based. However, it's not really any different from normal .hx files in that regard, so I don't see why it would cause any issues like this.

**Comment by hoseyjoe** [comment]
I created a custom runner and did not have an issue. Must be something weird in their shared runner
