### ISSUE TITLE
[macro] bug in eval read file

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7277]
I'm not sure exactly what's the reason, but here's a 100% reproducible bug that is triggered in eval interpreter when using sys.io.File.read instead of a BytesInput + sys.io.File.getBytes, while the two should have the same result.

- Get latest Heaps GIT
- In hxd/fs/Convert.hx replace `var input = new haxe.io.BytesInput(sys.io.File.getBytes(srcPath));` (working) by `var input = sys.io.File.read(srcPath);`
- go in samples, run `gen.hxml` to generate vscode projects
- delete `samples/res/hxlogo.png` and instead put the TGA file contained in this zip 
[hxlogo.zip](https://github.com/HaxeFoundation/haxe/files/2197823/hxlogo.zip)
- delete `samples/res/.tmp` (if the png as already been created, force the tga to be re-read and converted to png)
- open in VSCode build/base3D
- compile : you will get an `Eof` error in eval when using `sys.io.File.read` instead of the bytes workaround.

**Comment by Simn** [comment]
I tried following these steps but ended up getting `C:\GitHub\hl\libs\sdl\haxe/EntryPoint.hx:74: characters 3-15 : Class<sdl.Sdl> has no field loop`

**Comment by Simn** [comment]
Please see if that helped. The `binary` flag wasn't handled properly (wrong default value).
