### ISSUE TITLE
How can I send a HEAD request using haxe.Http?

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/haxe#7278]
How can I send a HEAD request using haxe.Http?

- https://api.haxe.org/haxe/Http.html
- https://github.com/HaxeFoundation/haxe/blob/3.4.7/std/haxe/Http.hx

It looks like only GET/POST methods are possible right now.

**Comment by Simn** [comment]
You can use `customRequest`.

**Comment by ovidiugabriel** [comment]
Thanks!
