### ISSUE TITLE
[display] Type name xxx is redefined from module yyy

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7279]
This error message is not prefixed by a file/line and thus does not appear in IDE. It only displays `Defined in this class` error (second line in terminal output)

**Comment by Simn** [comment]
This is another one of these issues where I have no idea what to do with it...

**Comment by ncannasse** [comment]
In what sense ? I think that's an error with a null_pos , we should give it a proper position so it gets displayed in VSCode.

**Comment by Simn** [comment]
Yes but I have no idea where it comes from and how to reproduce it.

**Comment by ncannasse** [comment]
Well, it surely comes from the compiler :) In order to reproduce you need two modules that each declare the same type name, then import them both.

**Comment by Jarrio** [comment]
I'm not sure if this helps or not but it seems like reverting to P5 seems to fix this issue. I haven't spent a long time testing P5 with this particular error as it's quite sporadic but switching between P5 and *anything* after RC1-RC2 latest shows this error message.

![gif](https://user-images.githubusercontent.com/748557/58599571-c4be4100-8278-11e9-9331-2972bcb92071.gif)
The code in the project is very minimal, I am using [Kevin's EXP-ECS](https://github.com/kevinresol/exp-ecs/) but I can't seem to isolate it into another project at all. I hope this at least provides some clues.

**Comment by Simn** [comment]
I guess we track this in #8368 now.
