### ISSUE TITLE
[display] unused pattern variables should be marked as unused

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7282]
Similar to #7267 - `value` should have a "this code has no effect" diagnostic so vshaxe can gray it out.

```haxe
import haxe.ds.Option;

class Main {
	public static function main() {
		switch ((null:Option<Int>)) {
			case Some(value):
			case None:
		}
	}
}
```

**Comment by Simn** [comment]
I don't know how I feel about that. It might be somewhat impractical, especially if you consider code-generation for `switch` expressions. It's also not exactly true to say that the code has no effect: It's actually required to match the structure and the only way to avoid warnings would be to use `_` everywhere.

**Comment by Gama11** [comment]
The idea here is that we need the diagnostic to be able to gray the variables out in vshaxe, like we do for other unused code. You wouldn't even normally see the "this code has no effect" message, and that could be something else.

**Comment by Gama11** [comment]
We would probably also want to offer a "replace with _" code action for these, so it should probably be a different message / type, so we can properly distuingish it.

**Comment by Gama11** [comment]
Oh, and also note that we don't present any of the "unused" diagnostics as actual warnings anymore (so they also don't show up in the problems view). That would show green underlines in addition to the grayed-out-effect, which kind of destroys the subtlety.

https://github.com/vshaxe/haxe-languageserver/blob/38553fd756de2a194e53647348ae93adddf68256/src/haxeLanguageServer/features/DiagnosticsManager.hx#L152-L154

**Comment by Gama11** [comment]
Huh, was this accidentally fixed somehow? Now seems to be working:

![](https://i.imgur.com/2TDwcKw.png)

I guess I'll add a test and close this.

**Comment by Gama11** [comment]
Oh, this is reported as `DKRemovableCode`, and the range on that is pretty off..

![](https://i.imgur.com/fXt42Xj.gif)

**Comment by Simn** [comment]
This is easy to fix but requires syncing with vshaxe which I currently cannot compile.

**Comment by Simn** [comment]
This (alongside https://github.com/vshaxe/haxe-language-server/commit/0f3418b7725d48e053c53b805b51f58ce372378f) now gives a more useful code action:

<img width="286" alt="Code_tUwOSwbyRm" src="https://github.com/HaxeFoundation/haxe/assets/634365/984f6c93-bfde-4fea-9703-69c2742238f9">

Adding a proper test is blocked on #9134.

**Comment by kLabz** [comment]
@Simn do you want the test to do something more here?

**Comment by Simn** [comment]
The replace range should always be tested for these.

**Comment by kLabz** [comment]
Should this be closed now or is there something still missing ?
