### ISSUE TITLE
[display] Use of --remap obscures class completion

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#7283]
Here's an example:

https://i.imgur.com/zcMD6LU.gifv

If you attempt to lookup a type (like using `var hi = new ...` in Visual Studio Code) types that match a standard package type (such as `flash.display.Bitmap` with `--remap flash:openfl`) will be hidden from the list when not targeting Flash.

Here's a basic example (without use of OpenFL) that reproduces the issue:

https://cdn.discordapp.com/attachments/428306479930540042/469198928462479370/Test2.zip

Adding `var hi = new Bitmap` in the `Test` `main` method does not provide completion, but if I comment or remove the `--remap flash:openfl` statement from the HXML, then re-open the project, I do get class completion

**Comment by Gama11** [comment]
A few things I discovered while looking into this so far:

- it's important that the remapping is from _flash_, this doesn't occur with e.g. `--remap foo:openfl`
- this doesn't happen in "offline mode" without a server / cache
- in the example, `openfl.display.Bitmap` is missing in the cache's list of files, despite being in the list of modules (this explains why it's missing from toplevel, as that uses the file list)
