### ISSUE TITLE
[display] replaceRange is sometimes missing when needed

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7296]
When invoking completion on `impl|`, there is no `replaceRange` in the `display/completion` result, even though the previous `impl` has to be replaced:

![](https://i.imgur.com/2ArA1MW.png)

(that's also the reason why `extends` isn't already filtered out there)

**Comment by Gama11** [comment]
This goes further than that, even in this case there's no `replaceRange`:

```haxe
class Main {
	public static function main() {
		Pos|
	}
}
```

![](https://i.imgur.com/mHw2llK.png)

I think Haxe should be changed to always report a `replaceRange`, even if the range is empty (start == end). That makes handling in the language server easier, since `replaceRange` isn't optional according to LSP spec either.

**Comment by Simn** [comment]
We can finish this in #8669.
