### ISSUE TITLE
[display] Map typedef is filtered out of new completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7305]
Two `Map` types should appear here - the toplevel `Map` typedef and the actual `haxe.ds.Map` type:

![](https://i.imgur.com/CyFoour.png)

The former should come first in the list, because the latter adds a (redundant) auto-import. It's good in regular completion:

![](https://i.imgur.com/tzfV4yn.png)

No test case here because I don't think they can currently cover this (seems they don't have the full doth-path for types).

Related: https://github.com/HaxeFoundation/haxe/issues/7224 / https://github.com/vshaxe/vshaxe/issues/255

**Comment by Simn** [comment]
I struggle to consistently reproduce this and so does my test before my fix. I think that depending on what else is going on, the class may or may not be built and the constructor lookup may or may not work. With the additional `cl_build()` call this should now be consistent.
