### ISSUE TITLE
haxe executable doesn't work well when it's not on PATH (relative paths issue)

### ISSUE THREAD

**Issue by orthoxerox** [HaxeFoundation/haxe#7307]
Haxe version: 3.4.7-win

Let's say I have the following file structure:

```
c:\somefolder\Hello.hx
c:\somefolder\haxe\
```

If I'm in `c:\somefolder`, I cannot invoke `haxe\haxe -main Hello -hl Hello.c Hello.hx`, because `haxe` looks for `haxelib` on the PATH only, and doesn't check its own location.

```
'haxelib' is not recognized as an internal or external command,
operable program or batch file.
Error: Build failed
```

If I move to `c:\somefolder\haxe`, I cannot invoke `haxe -main Hello -hl ..\Hello.c ..\Hello.hx`

```
Error: Could not process argument ..\Hello.hx
Package name must start with a lower case character
```

**Comment by ncannasse** [comment]
That's a perfectly normal that haxelib is called using PATH and not haxe executable directory.
You can either use   set PATH=c:\somefolder\haxe;%PATH%   or use   -cp .. when calling from haxe directory.
