### ISSUE TITLE
[display] field completion subject is named "$tmp_1"

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7317]
While looking into #7276 I noticed this curiosity:

![](https://i.imgur.com/pitW5IM.png)

```haxe
class Main {
	public static function main() {
		var obj = {};
		obj.
	}
}
```

Actually seems like it's not related to `obj` having no fields or being an anon structure at all, it might just always report that as the name currently.

Having the proper name might be useful for guessing variable names, e.g. with `.for` postfix completion (right now it's based on the type name, but I've been wondering if basing it on the name wouldn't be better).

**Comment by Simn** [comment]
This comes from the completion optimization...
