### ISSUE TITLE
[display] completion in identifier locations

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7320]
It's silly to have completion pop up while typing out a variable name:

![](https://i.imgur.com/dNv7VAs.gif)

I think there should simply be zero results here.

For types on the other hand, it might actually be convenient to suggest the current module's name. Say you're completing on `class |` in `Main.hx`, and the module doesn't have a type named `Main` yet, it would be nice to suggest that. Might require `DisplayItemKind.Identifier` or something like that.

**Comment by nadako** [comment]
> it might actually be convenient to suggest the current module's name

I wanted to suggest just that yesterday but forgot about it. It'd be nice - you create a file, it adds the package statement automatically and then suggests the type name.

**Comment by Simn** [comment]
This doesn't happen for me. I have to request completion manually to get anything there...
