### ISSUE TITLE
sys.io.Process()  with lua target will fail if bash doesn't exist.

### ISSUE THREAD

**Issue by cliffordjefferies** [HaxeFoundation/haxe#7331]
A small embedded system my not have bash.
I've created a fix which uses sh instead on pull request #7330.

A better fix would be to allow the shell to be specified or perhaps a shell is not needed to spawn a process.

**Comment by akbcode** [comment]
On the C++ target, /bin/sh is used only if the args array is null.

**Comment by cliffordjefferies** [comment]
I'm very new to the haxe code base but in my version of haxe/std/cpp/_std/sys/io/Process.hx I see no reference to bash or sh at all. it seems to be a thin layer on top of  cpp.NativeProcess and that seems a thin layer over something else.
A search for "bash" through the code base doesn't find anything apart from the lua file I changed.

I can confirm that my usage below has many parameters and works fine with sh

       var curl = new sys.io.Process("curl",
                [
                    "-i", "-s","--tlsv1.2",
                    "--capath", ".",
                    "--cacert", certDir + "/sas_ca.cert",
                    "--key", certDir + "/device_a.key",
                    "--cert", certDir + "/device_a.cert",
                    "-H", "Content-Type:", "application/json",
                    "--data", dataFile,
                    server + url
                ]
        );

**Comment by akbcode** [comment]
The actual C++ code for Process is in hxcpp library. Anyway, I was just observing that a shell is not required to run a process when an args array is provided(on C++). So maybe the same should be the case on Lua platform.

**Comment by jdonaldson** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/commit/d5f700dd38ed83dc44563d76ae04e49cd93cf9e9
