### ISSUE TITLE
[hl] "Uncaught exception: assert" with function types in type params

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7334]
```haxe
class Main<T> extends BaseSignal<T->Void> {
	static function main() {
		new Main<Int>(i -> trace(i)).dispatch(0);
	}

	function new(handler:T->Void) {
		this.dispatch = value -> handler(value);
	}
}

class BaseSignal<T> {
	var dispatch:T;
}
```

This crashes on HL/JIT with:

```
Uncaught exception: assert
Called from $Main.main(Main.hx:3)
Called from fun$349(?:1)
```

Isolated from `FlxSignal`. Latest Haxe and HL from source.

**Comment by ncannasse** [comment]
Can't reproduce using latest Haxe, can you confirm?

**Comment by ncannasse** [comment]
Right. And by replacing 0 by 456 I get an Access Violation even without -debug, which means the assert is correct ;)

**Comment by ncannasse** [comment]
Seems like genHL trust  BaseSignal.dispatch from being Int->Void whereas constructor wraps the Int->Void as a Dynamic->Void which is correct. GenHL shouldn't trust function type parameters from being what they are typed in.
