### ISSUE TITLE
[heisenbug][notice me senpai] x64 haxe.exe loads x86 zlib1.dll and crashes

### ISSUE THREAD

**Issue by Dimous** [HaxeFoundation/haxe#7342]
http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows64-installer/

Compiler builds **after 2018-08-01 11:28:58**      5933629        haxe_2018-08-01_development_2aed680.zip aren't running.

`C:\HaxeToolkit\haxe> haxe.exe -v` returns nothing, it is not starting.
I have no antivirus/firewall and again -- 2aed680 is working 🤷

**Comment by Gama11** [comment]
Hm.. seems to work ok for me with `haxe_2018-08-03_development_9db8cf1.zip` from that page:

```
> haxe -version
4.0.0-preview.4+9db8cf171
```

It's strange that the `_build` directory is included in the builds though.

**Comment by Dimous** [comment]
Just installed haxe_latest
IDE shows "Haxe version check failed" warning

When I try to compile my project:
```
Warning: OpenFL expects Haxe 3.4.3 or greater, but version 1 is being used
Error: Lime 7.0.0 is not compatible with Haxe 1 (version 3.2.0 or higher is required)
```

**Comment by Dimous** [comment]
I ran Sysinternals Process Monitor and found out that haxe.exe exits with STATUS_INVALID_IMAGE_FORMAT (C000007B), then I ran dependency walker and found out that it loads zlib1 of x86 architecture.

haxe.exe queries file system for zlib1.dll, finds a bunch and tries to load every one of them. Its clear, that 2aed680 checks only haxe directory, but this behaviour changed in recent versions.

**Comment by Dimous** [comment]
Removing Gtk Sharp's zlib1.dll is not an option. Workaround is to install 32-bit version.

**Comment by ncannasse** [comment]
@waneck we should ship proper zlib1.dll with the installer.

**Comment by FlorianBT** [comment]
I've been pointed to this issue on the haxe forums (thread : http://bit.ly/2Q6MVTQ)
Just to confirm the issue and note that it still happens with nightly builds 28ab3ce && 3da30c3

**Comment by waneck** [comment]
I've added a fix to it at https://github.com/HaxeFoundation/haxe/commit/67103d2ffe4455205621660f586e761356c73a28 , but the appveyor CI is failing right now so I'm not sure it really fixes it. As soon as we have the CI working again, I'll test it

**Comment by Simn** [comment]
It's not quite there yet:

```
Changing directory to C:\projects\haxe/
Cleaning up the 32-bit DLLS
runci/Deployment.hx:163: characters 4-9 : Uncaught exception The DLL at path C:\Program
Files
(x86)\Mono\bin\zlib1.dll was not found
runci/Deployment.hx:133: characters 11-26 : Called from here
runci/Deployment.hx:119: characters 3-31 : Called from here
runci/Deployment.hx:236: characters 7-25 : Called from here
runci/Deployment.hx:374: characters 4-21 : Called from here
RunCi.hx:105: characters 4-12 : Called from here
Command exited with code 1
```

**Comment by waneck** [comment]
I tested it using DEPLOY_NIGHTLIES on the C++ tests, so I've just submitted that change as well

**Comment by waneck** [comment]
I believe this is fixed now. Feel free to reopen if you still see any issues
