### ISSUE TITLE
Can't cast to DynamicAccess

### ISSUE THREAD

**Issue by praleks** [HaxeFoundation/haxe#7343]
```
var PF_SUB_IMG:DynamicAccess<Dynamic> = state.root.PF_SUB_IMG;
var spriteSettings = PF_SUB_IMG[sprite.name];
```
this works.

`var spriteSettings = cast(state.root.PF_SUB_IMG, DynamicAccess<Dynamic>)[sprite.name];`
this is error "Cast type must be a class or an enum"

**Comment by benmerckx** [comment]
You want to use an unsafe cast here: https://haxe.org/manual/expression-cast-unsafe.html

```haxe
var spriteSettings = (cast state.root.PF_SUB_IMG: DynamicAccess<Dynamic>)[sprite.name];
```

**Comment by praleks** [comment]
Thanks
