### ISSUE TITLE
Warnings for macro-in-macro.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7348]
Until macro-in-macro is properly supported, we should warn when it's used (personally I wouldn't mind an error). It would go a long way to make things easier for newcomers. I've lost count of how many times I saw some variant of this problem: https://community.haxe.org/t/injecting-a-local-variable-with-macro/953

**Comment by Simn** [comment]
We have an option to show macro-in-macro by using `-D macro-debug`. Of course that doesn't actually help you unless you know that macro-in-macro is your problem in the first place.

**Comment by Simn** [comment]
If we add a warning for this we also need a way to avoid the warning in case you genuinely want to have a macro-in-macro call.

**Comment by back2dos** [comment]
Ok, more drastic then: How about forbidding it to see if anybody complains? Since macro-in-macro busts the cache, I doubt anybody would "genuinely want to have a macro-in-macro call" other than for some funky experiments. It creates way more problems than it solves.

**Comment by Simn** [comment]
I'm experimenting with this, but our mutual friend haxelib gets in the way because of this:

```haxe
class Main {
	static var VERSION:SemVer = SemVer.ofString(getHaxelibVersion());
	static var VERSION_LONG:String = getHaxelibVersionLong();

	macro static function getHaxelibVersion() {
		var haxelibJson:Infos = Json.parse(File.getContent("haxelib.json"));
		return macro $v{haxelibJson.version};
	}

	macro static function getHaxelibVersionLong() {
		var version:String = VERSION;
```

**Comment by back2dos** [comment]
How about `#if`-fencing it in haxelib then?

**Comment by Simn** [comment]
That won't be enough because there's some legit macro-in-macro handling going because `macro getHaxelibVersionLong` works with `VERSION` which is initialized using a macro call.

**Comment by back2dos** [comment]
Without further ado I present to you: `#if !macro macro #end`

**Comment by Simn** [comment]
That still won't do because.... you know what, how about you just fix it? :P

**Comment by back2dos** [comment]
I'll do my best, but I have no way of knowing if it's fixed, do I? :P

**Comment by Simn** [comment]
`-D check-macro` should not give warnings.

Although the way it's implemented right now is not ideal. It warns when _typing_ a macro-in-macro, which is not necessary. We only care about it if we actually _call_ such a macro.

**Comment by Simn** [comment]
I meant `-D macro-debug`
