### ISSUE TITLE
ES6 Map vs. haxe.ds.ObjectMap

### ISSUE THREAD

**Issue by jozefchutka** [HaxeFoundation/haxe#7349]
Hi everyone,

what are the plans with using ES6 build in [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) instead of haxe implementation of [ObjectMap](https://github.com/HaxeFoundation/haxe/blob/development/std/js/_std/haxe/ds/ObjectMap.hx) (and others). I tried to benchmark and compare these two, it seems the access time is similar but custom haxe implementation consumes 15%+ retained memory (in chrome).

Tested with following implementation:

```haxe
@:multiType(@:followWithAbstracts K)
abstract Map2<K,V>(IMap<K,V>) {
    // ... copy of haxe.Map
    @:to static inline function toObjectMap<K:{ },V>(t:IMap<K,V>):IMap<{ },V> {
        return NativeMap.isSupported() ? new NativeMap<{ },V>() : new ObjectMap<{ }, V>();
    }
    // ... rest of haxe.Map
}

class NativeMap<K,V> implements haxe.Constraints.IMap<K,V> {
    var source:Dynamic;
    
    public function new(){
        source = untyped __js__('new Map()'); 
    }
    
    public static function isSupported():Bool{
        return Reflect.hasField(js.Browser.window, "Map");
    }
    
    public function get(k:K):Null<V>{
        return source.get(k);
    }
    
    public function set(k:K, v:V):Void{
        source.set(k, v);
    }
    // ...
}
```

**Comment by nadako** [comment]
Yeah, the plan is to implement ES6 `Map`-based haxe maps, hopefully I'll find time for Haxe 4.

**Comment by Simn** [comment]
@nadako Could you remind me (again) what the outcome was here?

**Comment by nadako** [comment]
Well, I have a WIP PR #9303 that I have no time to work on.
