### ISSUE TITLE
Can't use Iterable abstract with Lambda...

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#7351]
This code does not compile:
```haxe
@:forward(iterator)
abstract MyArray(Array<Dynamic>) from Array<Dynamic> {
}

class Test {
    static function main() {
        var a: MyArray = [1, 2, 3];
        
        //MyArray should be Iterable<Unknown<0>>
    	Lambda.find(a, function(i) return i==3);
    }
}
```

This also does not work with the same error:
```haxe
abstract MyArray(Array<Dynamic>) from Array<Dynamic> {
     public inline function iterator(): Iterator<Dynamic> return this.iterator();
}
```

**Comment by back2dos** [comment]
[This works](https://try.haxe.org/#aD2C6):

```haxe
@:forward(iterator)
abstract MyArray(Array<Dynamic>) from Array<Dynamic> to Iterable<Dynamic> {
}

class Test {
    static function main() {
        var a: MyArray = [1, 2, 3];
        
        //MyArray should be Iterable<Unknown<0>>
    	Lambda.find(a, function(i) return i==3);
    }
}
```

**Comment by romamik** [comment]
This actually is not a bug. According to manual
> Structural sub-typing in Haxe is allowed when unifying
> - a class with a structure and
> - a structure with another structure.
so it should not work with abstracts. 

And I think this is not even possible in general. Because we cannot pass abstract to some code that was generated without knowing it is abstract. Theoretically it can be possible in some situations like `for` statements or inlining.
