### ISSUE TITLE
Bug in generated Java code when having final fields in (Java) Base-Class

### ISSUE THREAD

**Issue by bergm** [HaxeFoundation/haxe#7360]
When trying to inherit from a Java class, which has protected final member variables, then in the generated Java code the compiler creates for instance the __hx_setField_f method where setting the final field is attempted, so the Java compilation fails.

Minimal code would be:

(Java)
```
package test;
public class FinalTest {
    protected final int protFinalField = 0;
}
```

(Haxe)
```
class FinalTest2 extends FinalTest {}
```

Then in the generated file for FinalTest2.java, code like the following will be found:
```
 .....
public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
{
	{
		boolean __temp_executeDef1 = true;
		switch (field.hashCode())
		{
			case -612101141:
			{
				if (field.equals("protFinalField")) 
				{
					__temp_executeDef1 = false;
					this.protFinalField = ((int) (value) );
					return value;
				}
					
				break;
			}
		}
.....
```

**Comment by nadako** [comment]
As a workaround I think it's possible to use `@:skipReflection` metadata on fields to omit them from this helper method. Another option is to use `@:nativeGen` on the whole class to skip all reflection helper methods generation.
