### ISSUE TITLE
Errors on instance field initiation with nested Maps.

### ISSUE THREAD

**Issue by TheBilbo** [HaxeFoundation/haxe#7369]
On this:
`private var _field:Map<String, Map<String, Dynamic>> = [ "'key'" => new Map<String, Dynamic>() ];`
I have errors:
> key : String -> value : Map<String, Dynamic> -> Void should be String -> haxe.ds.StringMap<Unknown<0>> -> Void
> Cannot unify argument 2
> haxe.ds.StringMap<Unknown<0>> should be Map<String, Dynamic>
> haxe.ds.StringMap<Unknown<0>> should be haxe.ds.Map<String, Dynamic>

it works fine at any function body though.
But this (modifed) works with instance fields:
`private var _field:Map<String, StringMap<Dynamic>> = [ "'key'" => new Map<String, Dynamic>() ];`
**Haxe 4.0.0-preview.4**

**Comment by Simn** [comment]
I cannot reproduce this on HEAD, so I assume this has been fixed.
