### ISSUE TITLE
static analyzer bug on js platform

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#7370]
If compiling with `-D analyzer-optimize` haxe can generate invalid js code.
This code can reproduce this error:
```haxe
class Test {
    static function main() {
        var map: Map<String, Dynamic> = ["hello"=>"world"];
        for(key in map.keys()) {
        	var value = cast(map[key], String); 
        	trace(key);
        	//dont use value to reproduce bug
        }
    }
}
```
Generated js for line `cast(map[key], String)` is this:
```js
		js_Boot.__cast(if(__map_reserved[key1] != null) {
			_g.getReserved(key1);
		} else {
			_g.h[key1];
		} , String);
```
which is not valid js syntax. For example chrome gives `Uncaught SyntaxError: Unexpected token if` error.

**Comment by Simn** [comment]
Funny how both the analyzer and genjs had very obvious bugs related to safe-casts. These must have been around for years and nobody noticed.
