### ISSUE TITLE
[hl] closure equality variance breaks == comparison

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7375]
```haxe
class Main {
	static public function main() {
		function f1(x:Float) { }
		var f2:Int -> Void = f1;
		trace(f1 == f2);
	}
}
```

```
source/Main.hx:5: characters 9-17 : Don't know how to compare (f64):void and (i32):void
```

**Comment by ncannasse** [comment]
Please note that it trace false, the reason being that genhl generate a compile time closure wrapper that is the equivalent of ` var f2 = (function(f:Float->Void,x:Int) f(x)).bind(f1);` . ATM I have no way to distinguish such wrapper at runtime.

**Comment by Simn** [comment]
Are you saying this is unspecified?

**Comment by ncannasse** [comment]
For `==` yes, comparisons of functions should use Reflect.compareMethod . Note that it will still give false for this particular case, I have to work on it if we want to support it.

**Comment by Simn** [comment]
My CI fails with `unit/issues/Issue6705.hx:71: Check failure at fun@2637 @5 - Register 1((f64):void) should be (i32):void and not (f64):void`

**Comment by Simn** [comment]
In other bad news for you, HL is the only target where this test fails...

**Comment by ncannasse** [comment]
The CI will no longer fail, but result is still false because of the wrapper creation. I have taken care of dynamic wrappers, not static ones (the one we generate at compile time).
