### ISSUE TITLE
Arrow function: invalid return type inference with `try...catch `

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7376]
```haxe
class Test {
	static function main() {
		var fn:()->Void = () -> {
			try { //Test.hx:4: lines 4-6 : Int should be Void
				intJob(); 
			} catch(e:Dynamic) {
				voidJob();
			}
		}
		fn();
	}
	
	static function intJob():Int return 0;
	static function voidJob():Void {}
}
```
Latest development branch.
http://try-haxe.mrcdk.com/#6b5Cc

**Comment by Simn** [comment]
There should be no difference between arrow functions and normal functions here...

**Comment by frabbit** [comment]
It's because of the implicit return

**Comment by Simn** [comment]
Ah yeah, this is failing as intended because Int and Void don't unify.

**Comment by back2dos** [comment]
This behavior is suboptimal. The compiler knows the return type to be `Void`, in which case not expecting a return value is the most sane choice and would thus not even attempt a unification and therefore not produce the error.

**Comment by nadako** [comment]
I agree with @back2dos, I think we could make use of the known return type to allow this.

**Comment by kevinresol** [comment]
Same for `switch`, it is very irritating because I use `tink.core.Promise#handle` so much....

```haxe
class Main {
    static function main() {
        foo(bool -> switch bool {
            case true: int();
            case false:
        });
    }
    static function int():Int return 1;
    static function foo(f:Bool->Void) f(true);
}
```

`src/Main.hx:3: lines 3-6 : Void should be Int`

**Comment by RealyUniqueName** [comment]
Can we change the typing of `switch`, `if`, `try` expressions from the type of the first branch to the most "wide" type of all branches? That will eliminate these confusing errors.
```haxe
$type(try int() catch(e:A) void() catch(e:B) string()); // Void
```

**Comment by nadako** [comment]
But `Void` is not a wider type :)

**Comment by Simn** [comment]
We shouldn't treat `Void` as a wider type by default. This would lead to really confusing errors down the line where you stare at "Cannot use Void as value" errors and can't tell where it comes from.

This can only be solved via top-down inference: if the expected type is `Void` (which should really only happen for function returns), we can avoid the unification of all "branches" and type the if/switch/try as `Void`.

I'll have to check if that plays well with all our targets though. JVM for instance has to emit `pop` instructions if there is an unused value on the stack. I think this is already handled though.

**Comment by Simn** [comment]
Actually, the problem here seems to be that top-down inference isn't even applied. The expected type is unknown...

**Comment by Simn** [comment]
Right, we still want this to fail:

```haxe
class Main {
	static public function main() { }

	static function returnVoid():Void {
		return 1;
	}
}
```

That's why we don't use `Void` as the expected type for local function return values.

**Comment by back2dos** [comment]
Given the expected type `A->B->...->N->Ret` the arrow function `(a, b, ..., n) -> body` should be processed as:

- `function (a, b, ..., n) body` if `Ret` is `Void`
- `function (a, b, ..., n) return body` otherwise

AFAIK the problem is that we have no way of telling apart "normal" and arrow function. As suggested before, [adding a flag to `Function` would be the least intrusive solution](https://github.com/HaxeFoundation/haxe/issues/8128#issuecomment-495485461). We may want to explicitly disallow `FieldType.FFun({ arrow: true })`, because it makes no sense.

**Comment by Simn** [comment]
Adding that to `Function` is weird though. You could get combinations like named local arrow functions which makes no sense. I prefer [nadako's suggestion](https://github.com/HaxeFoundation/haxe/issues/8128#issuecomment-495339124) but it's a breaking change...

**Comment by RealyUniqueName** [comment]
Can we do it on ml side only and keep macro API intact for now?
