### ISSUE TITLE
special char breaks CommentString - version 4.0.0-preview.4+1e3e5e016

### ISSUE THREAD

**Issue by axelhuizinga** [HaxeFoundation/haxe#7377]
the ü special char in this var seems to result in a wrong Context.currentPos causing the str used by CommentString to start with ( and then failing with "No comment was found."

private static var pay_history_fields = 'buchungsanforderungID,Mandat-ID,Betrag,Termin,tracking_status,Textschlüssel bzw. Zahlart'.split(',');

the hx file is utf8 and compiled well with a release version

**Comment by Simn** [comment]
That's probably #6897

**Comment by Simn** [comment]
Assume fixed, please reopen otherwise.

**Comment by axelhuizinga** [comment]
I still get the same error once I use a special char anywhere in a hx file using the CommentString lib

**Comment by Simn** [comment]
How do I reproduce this?

**Comment by axelhuizinga** [comment]
for me any usage of comment as in:
		var activateTrigger = comment(unindent, format) /**
		SELECT audit.audit_table('$tableName');
		**/;	
from a haxe file which contains some special char like an ü in string assign or even within a comment produces this error

**Comment by Simn** [comment]
Could you please provide some simple Haxe code that I can copy and paste to reproduce this problem?

**Comment by axelhuizinga** [comment]
import comments.CommentString.*;
```
/*ü*/

class Hello {
  static public function main():Void {
	var greeting:String = comment(unindent, format) /*
	  Hello World
	  */;
	trace(greeting);
  }
}
```
tested with haxe -lib CommentString -main Hello --interp
remove the ü in the comment and it works
