### ISSUE TITLE
Cannot skip not-nullable argument

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7378]
Due to change in #6972 we are now getting a lot of `Cannot skip not-nullable argument`, such as in the following example:

```haxe
class Main {
    static function foo( ?x = true, ?color = 0 ) {
    }
    static function main() {
        foo(0);
    }
}
```

It used to work in 3.x but now fails in 4.0.

There are two possibilities here:
 * require the user to change `foo` with `function foo( ?x : Null<Bool> = true, ?color : Null<Int> = 0 )` which I personally find very verbose.
 * enable insertion of default value at call site, so `foo(0)` gets compiled to `foo(true,0)` . This will not work in the most general case since values are no part of the function type, but it will work when we know the method implementation (static or member function). As a side effect, this imply forbidding to change the default value in a method override, but I think this is a good thing anyway.

I'm in favor of the second proposal.

_Note : Please avoid discussion about removing argument skipping here as while it's related I don't think we can make it happen for Haxe 4.0 without delaying too much the release as it would also imply adding overloads with all the problems that comes with them._

**Comment by ncannasse** [comment]
Alternative is to revert #6972 and keep the difference between `?x=0` and `x=0` wrt nullability, but I'm not in favor of it.

**Comment by Simn** [comment]
I say let's revert. The change didn't address what I originally wanted to address, and all we really got here is a false sense of consistency.

**Comment by ncannasse** [comment]
Maybe that's indeed better to revert, but then I'ld trade that for giving more explanation on the following manual page: https://haxe.org/manual/types-nullability-optional-arguments.html

**Comment by Simn** [comment]
Reverted, keeping track of the documentation changes in https://github.com/HaxeFoundation/HaxeManual/issues/307
