### ISSUE TITLE
Sys.environment() crash in Lua

### ISSUE THREAD

**Issue by cliffordjefferies** [HaxeFoundation/haxe#7380]
static public function main():Void {
		Sys.putEnv("PATHX","XX");
		Sys.print(Sys.getEnv("PATHX"));
		var env = Sys.environment();
		Sys.print(env);
	}
produces
 XXlua: ./www/cgi-bin/webSrvr:636: attempt to index global 'lua' (a nil value)
 stack traceback:
        ./www/cgi-bin/webSrvr:636: in function 'environment'
        ./www/cgi-bin/webSrvr:645: in function 'main'
        ./www/cgi-bin/webSrvr:877: in main chunk
        [C]: ?

I added the putEnv() because it uses similar code and it works.
I've done a sudo luarocks install environ

**Comment by jdonaldson** [comment]
fixed with https://github.com/HaxeFoundation/haxe/commit/9d75becbe1c52dc6e2d33574ea80a004d4fec9e8

**Comment by cliffordjefferies** [comment]
Hi Justin.
Thanks for the quick fix.
A few questions about your fix if I may.
1) Does the "var p = new sys.io.Process(cmd,[]);" require a p.close() or is this implicit?
2) Can I "sudo luarocks uninstall environ"
Regards
Cliff
