### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7382]
One extra refactoring that might be worth is to store booleans into a single bit flag (cf_public/cf_extern/cf_final) : it will save a few bytes of memory per class field which is quite good, and also allows us to add additional flags without breaking macros etc.

Same remark for tclass

**Comment by Simn** [comment]
Meh...

**Comment by Simn** [comment]
Are you sure the OCaml code generation doesn't already do something here?

**Comment by ncannasse** [comment]
I'm quite sure about that, that would break C interop

**Comment by Simn** [comment]
I'll do this after we release an RC.

**Comment by Simn** [comment]
Reading your post I'm only now noticing the "add additional flags without breaking macros" comment. Was the idea to expose these flags to macros as well? I thought we would still encode it as real fields for them, and we kinda missed our chance to change that now.

**Comment by ncannasse** [comment]
Well that was the idea, but I have no strong opinion about it.
