### ISSUE TITLE
Huge performance issues with haxe.ds.Vector setter with HXCPP 

### ISSUE THREAD

**Issue by velochy** [HaxeFoundation/haxe#7385]
Suppose the following simple program that has an array which is read from and then written back into, a very common use case.

```
import haxe.ds.Vector;

class Test {
		public static function main () {
			var N = 100000;
			var vec: Vector<Int> = new Vector(N);

			for(i in 0...N) {
				var v1 = vec[i];
				vec[i] = i+v1;
			}
		}
}
```

When run with HaXe 3.4.7 and HXCPP 4.0.4, the generated CPP code for main is:
```
void Test_obj::main(){
                HX_STACKFRAME(&_hx_pos_df13cafffbed243f_4_main)
HXLINE(   5)            int N = (int)100000;
HXLINE(   6)            ::Array< int > this1 = ::Array_obj< int >::__new(N);
HXDLIN(   6)            ::Array< int > vec = this1;
HXLINE(   8)            {
HXLINE(   8)                    int _g1 = (int)0;
HXDLIN(   8)                    int _g = N;
HXDLIN(   8)                    while((_g1 < _g)){
HXLINE(   8)                            _g1 = (_g1 + (int)1);
HXDLIN(   8)                            int i = (_g1 - (int)1);
HXLINE(   9)                            int v1 = ( (int)(_hx_array_unsafe_get(vec,i)) );
HXLINE(  10)                             ::Dynamic vec1 = vec->__Field(HX_("__unsafe_set",e9,ea,a4,60),hx::paccDynamic);
HXDLIN(  10)                            vec1(i,(i + v1));
                                }
                        }
                }
```

This means that on every iteration of the for loop, the setter is re-calculated - which is VERY expensive relative to what else is going on.

Since getter does not have this issue, my guess is that it might just be due to the setter not being inlined, but this is a huge performance hit on a class whose description reads:
"It can be faster than Array on some targets, and is never slower."
i.e. which is mainly there to be more performant than the standard choice.

PS: for those who need a quick workaround until this gets resolved, you can cache the setter yourself, i.e.
```
			var vec_set = vec.set;
			for(i in 0...N) {
				var v1 = vec[i];
				vec_set(i,i+v1);
			}
```
But considering the hit on readability this creates, it should only be used in bottlenecks with lots of computation..

**Comment by Simn** [comment]
Current dev generates this correctly:

```c++
HXLINE(   9)				int v1 = ( (int)(_hx_array_unsafe_get(vec,i)) );
HXLINE(  10)				vec->__unsafe_set(i,(i + v1));
```
