### ISSUE TITLE
retrieving Data from CDATA in response XML

### ISSUE THREAD

**Issue by iffi101** [HaxeFoundation/haxe#7386]
> <?xml version='1.0' encoding='utf-8'?>
> <soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/'>
>     <soapenv:Body>
>         <res:ResultMsg xmlns:res='http://cps.huawei.com/cpsinterface/result'>
>             <![CDATA[
>             <?xml version='1.0' encoding='utf-8'?><Result><ResultParameters><ResultParameter><Key>FailedReason</Key><Value>The value 611015125123 of the CNIC parameter is incorrect, failed to authenticate the parameter.</Value></ResultParameter></ResultParameters><ResultCode>2002</ResultCode><ResultType>0</ResultType><OriginatorConversationID>20180904165750</OriginatorConversationID><ResultDesc>Transaction information is invalid.</ResultDesc><TransactionID>000000000000</TransactionID><ConversationID>AG_20180904_00007be9004e56992e5f</ConversationID></Result>]]>
> </res:ResultMsg>
> </soapenv:Body>
> </soapenv:Envelope>

This is the XML I am getting, I have tried numerous ways to get CDATA from it but failed.

Got that into String 
```
$xml = simplexml_load_string($xml_string, "SimpleXMLElement", LIBXML_NOCDATA);
$json = json_encode($xml);
$array = json_decode($json,TRUE);
exit (var_dump($array));
```

Tried to remove CDATA tags and many more. 
How can I get CDATA content as Object or Array using Php

**Comment by Simn** [comment]
You seem to have taken a wrong turn somewhere. This is the repository of the [Haxe](https://haxe.org) programming language, while you seem to be having a [PHP](http://php.net) problem.
