### ISSUE TITLE
Assign a field with default value creates a constructor

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7388]
I think this is a bug, in our current codebase we don't have constructors for some base classes. But I notice when I add a field with a default value, secretly a constructor is added. I could reduce this to a simple test case:

**Correct behavior**: 
Got error "A does not have a constructor"
```haxe
class Test {
    static function main() {
       A.new;
    }
}

class A {
}

```
**Incorrect behavior**: no error. 
Expected: get a "A does not have a constructor" error.
```haxe
class Test {
    static function main() {
       A.new;
    }
}

class A {
    public var x = 1; // notice lack of constructor
}
```
Test: https://try.haxe.org/#e32C1 (toggle comment to reveal/hide error)

Haxe: 3.4.7

**Comment by Simn** [comment]
That's the expected behavior. Where else would the initialization go?

**Comment by markknol** [comment]
If its needed to create a constructor, it might be an idea to make it private.

I would expect if there is no constructor function, you cannot construct a class. 

In theory the initialization could also be done in the extended classes that do have a constructor(?)

**Comment by ncannasse** [comment]
I agree with the default-private constructor here

**Comment by markknol** [comment]
Unless the class already extends something else _with_ a constructor, then it should take over that visibility.

**Comment by Simn** [comment]
I got sidetracked here because I didn't realize this problem was specific to `A.new`. `new A()` already behaves as expected.

**Comment by markknol** [comment]
Thanks! That was quick 🥇
