### ISSUE TITLE
final inference of struct literals vs. abstract implicit casts

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7391]
```haxe
class Main {
	public static function main() {
		var a:Foo = {i: 0};
		var b:Bar = {i: 0};
	}
}

typedef Foo = {
	final i:Int;
}

abstract Bar(Foo) from Foo {}
```

```
source/Main.hx:4: characters 3-22 : { i : Int } should be Bar
```

This doesn't compile anymore due to the [`final` changes](https://github.com/HaxeFoundation/haxe/commit/660aaafe9a74c65226d565e56e67be530847187e). For a simple assignment (`a`) this now works since https://github.com/HaxeFoundation/haxe/commit/3a76be2d03b259f344c0561b0bf5ae84fc55b808, but not if implicit casts are involved (`b`).

**Comment by Simn** [comment]
@ncannasse: This is supposed to be top-down inferred and typed against `Bar` here due to your `get_abstract_froms` handling, right?

**Comment by Simn** [comment]
Ah, that doesn't work because of https://github.com/HaxeFoundation/haxe/commit/49ac2695f7f36dd5673e1974d8eabeafe11c5d88
