### ISSUE TITLE
Literal object typing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7396]
In the following example:

```haxe
typedef Foo = { x : Int, ?y : Int };

class Main {
    static function main() {
        var o : Foo = { x : 0, y : 1 };
        trace(o);
    }
}
```

This will give the following dump:

```
[Var o(7403):Foo]
	[ObjectDecl:{ y : Int, x : Int }]
		x: [Const:Int] 0
		y: [Const:Int] 1
```

Which makes the literal object somewhat incompatible with the actual variable type.
I would expect instead:

```
	[ObjectDecl:{ y : Null<Int>, x : Int }]
		x: [Const:Int] 0
		y: [Cast:Null<Int>] [Const:Int] 1
```

This lead to falling back on dynamic field access on HL (see https://github.com/HaxeFoundation/hashlink/issues/178)

**Comment by Simn** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/903c46cdc0520e7c35e2f7133e5c3efd518b0f6e
