### ISSUE TITLE
[minor] improve deprecation message for "redirection typedefs"

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7397]
> extracted from #7390

At the moment it outputs the default `Warning : Usage of this typedef is deprecated`, not pointing the user to the type they should use instead, so I have to manually pass the warning message. I'm just wondering if it makes sense to generate one if we do `@:deprecated typedef Name = some.Type.Path` so it emits `Warning : Usage of this typedef is deprecated. Use some.Type.Path instead.`

**Comment by Simn** [comment]
Uhm, this isn't giving me any warning whatsoever:

```haxe
@:deprecated typedef A = B;
typedef B = String;

class Main {
	static public function main() {
		var x:A = null;
		trace(x);
	}
}
```
