### ISSUE TITLE
[hxcpp] encoding parameter not respected in Bytes.getString/ofString

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7399]
This got a bit lost in the recent branch and issue mess, so as a reminder: hxcpp does not respect the `encoding` argument to `haxe.io.Bytes.ofString` and `haxe.io.Bytes.getString`. The functions `__hxcpp_bytes_of_string` and `__hxcpp_string_of_bytes` always encode as UTF8:

```haxe
class Main {
	static public function main() {
		var rawBytes = haxe.io.Bytes.ofString("éあ😂",RawNative);
		trace(rawBytes.toHex() == "e90042303dd802de"); // false, should be true
		trace(rawBytes.getString(0, rawBytes.length,RawNative) == "éあ😂"); // true, should still be true after fixing ofString
	}
}
```

**Comment by hughsando** [comment]
Can't I just use utf8 for RawNative format?  Otherwise, I'm going to need to add a byte to say if it ascii or uft16 and then the encoding are not going to match anyhow.
If by "RawNative" you mean utf16, then I think the name needs to change.

**Comment by Simn** [comment]
@ncannasse

**Comment by Simn** [comment]
Hmm, I also need to know what exactly `RawNative` means:

```haxe
import haxe.io.Bytes;

class Main {
	static public function main() {
		var s1 = "abc";
		var s2 = 'äbc';
		var sub1 = s1.substr(1);
		var sub2 = s2.substr(1);
		trace(sub1 == sub2); // true
		var b1 = Bytes.ofString(sub1, RawNative);
		var b2 = Bytes.ofString(sub2, RawNative);
		trace(b1.toHex() == b2.toHex()); // false
	}
}
```

That's because of the dual representation: `s1` is represented as ASCII string while `s2` is UCS2, and the `substr` operations don't change that. That means when they are converted to Bytes, `sub1` is represented as `6263` but `sub2` is `62006300`. Is that acceptable?

**Comment by ncannasse** [comment]
@hughsando either you are an "utf16" platform and then you have the surrogate pairs etc. just like JS/HL/etc. or you are a "full unicode platform" (`utf16` not defined), in which case you can use any kind of internal encoding that you want, and yes in that case you can add a test with RawNative being utf8 in a `#if cpp` section.

**Comment by ncannasse** [comment]
@Simn seems weird, because how you would differentiate then between a single byte string having 0x6263 char and two ascii chars 0x62 and 0x63 ?

**Comment by ncannasse** [comment]
@Simn if we want it be really RawNative maybe you need one byte prefix or another way to tell if it's a ASCII or UCS2 string

**Comment by Simn** [comment]
Right, I have to think about this again because at the moment this doesn't hold:

```haxe
import haxe.io.Bytes;

class Main {
	static public function main() {
		var s1 = "abc";
		var b1 = Bytes.ofString(s1, RawNative);
		var s2 = b1.getString(0, b1.length, RawNative);
		trace(s1 == s2);
	}
}
```

**Comment by Simn** [comment]
... which also means the tests suck.

**Comment by hughsando** [comment]
I have defined cpp RawNative format as UTF8, which solved the problem one way or another.
