### ISSUE TITLE
Run haxe-formatter on std for the Haxe 4 release

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7404]
I'm labeling this as "discussion", but I don't really want to discuss it much. Unless somebody has serious reservations about this... Our coding styles are already very similar, so there shouldn't be much friction here.

Some TODOs:

* [ ] We need the hxformat.json. @Gama11 could you handle that?
* [ ] We have to synchronize this with https://github.com/haxiomic/html-externs. It shouldn't matter if we do this before or after merging #7354. (@haxiomic)
* [ ] I'm not sure if it's still used, but `--gen-hx-classes` has to be adapted. (@simn)
* [ ] haxe.macro.Printer should probably adhere to our coding style. (@simn)

Anything I'm forgetting?

**Comment by Simn** [comment]
Paging @AlexHaxe as well.

**Comment by Gama11** [comment]
>We need the hxformat.json

What adjustments would you want to make over the formatter's default style? (if you use the default style, you don't really need a `hxformat.json`)

**Comment by AlexHaxe** [comment]
I think it makes sense to have a `hxformat.json` even if you are using default style. You never know how and where that folder gets used, someone might end up puttting it inside their workspace. Having a `hxformat.json` makes sure the correct style is used, even if it only contains `{}`.

But I guess we might need an exclude or two for files where formatter produces a "less good" format.

**Comment by AlexHaxe** [comment]
I've created an initial `hxformat.json` config (latest dev version of formatter recommended). 
```
{
    "indentation": {
        "character": "tab"
    },
    "emptyLines": {
        "externClassEmptyLines": {
            "afterVars": 1
        }
    },
    "sameLine": {
        "functionBody": "keep",
        "ifBody": "keep",
        "elseBody": "keep",
        "elseIf": "keep",
        "ifElse": "keep",
        "expressionIf": "keep",
        "comprehensionFor": "keep",
        "expressionTry": "keep",
        "forBody": "keep",
        "caseBody": "keep",
        "expressionCase": "keep",
        "anonFunctionBody": "keep",
        "whileBody": "keep",
        "catchBody": "keep",
        "tryBody": "keep",
        "tryCatch": "keep"
    },
    "whitespace": {
        "typeHintColonPolicy": "around"
    }
}
```
It's probably not perfect, but then again it's not really clear what exact style to use when there are so many to choose from.

**Comment by Simn** [comment]
Does anyone feel destined to look into this?

**Comment by Simn** [comment]
Closing due to general lack of interest.

**Comment by markknol** [comment]
Side note: I think haxe sources should use an empty hxformat.json, because that should be the "standard".
