### ISSUE TITLE
EReg#matchedPos(BOM) target inconsistency

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#7408]
```haxe
class Test {
    static function matchedPos(str) {
        var r = ~/::/;
        if (r.match(str)) {
            var m = r.matchedPos();
            return m;
        }
        return null;
    }
    static function main():Void {
        // create a String with leading BOM
        var p = matchedPos(String.fromCharCode(65279) + "::test::");

        // neko 2.2.0 / node 8.11.4 / java 1.8.0_181 / python 3.5 / C# mono 4.2.1 / Flash Player 26.0.0.131: {pos:1,len:2}
        // eval / lua 5.1: {pos:3,len:2}
        // hxcpp 668c004: {pos:4,len:2}
        trace(p);
    }
}
```

Tested with Haxe 27a7a4927bd42ba8ba3759d0528dc12f963850d5 on a Ubuntu machine.

**Comment by Simn** [comment]
I think this is about wide strings in general, not the BOM in particular.

**Comment by Simn** [comment]
I'm trying to figure out how to interface with PCRE for this. It wants UTF8 strings but its substring results are byte offsets. So while I can easily implement `matched`, `matchedLeft` and `matchedRight`, I'm having trouble with `matchedPos` because I'd have to go from byte offset to character offset.

On a related note, how does the `u` regex flag play into all this?

**Comment by ncannasse** [comment]
For HL I am using an UCS2 version of PCRE (pcre16* api) which should handle everything smoothly. "u" regexp flag should be deprecated I think, as we now always match on unicode.

**Comment by Simn** [comment]
Well shit, I can't find any OCaml bindings for that... T_T

**Comment by Simn** [comment]
This issue is probably superseded by #7419, but I'll keep it open in case the BOM situation is special after all.

Fixed eval in https://github.com/HaxeFoundation/haxe/commit/8a2517e2aeb79729bf2cc4afe105de7ab118acfa

**Comment by Simn** [comment]
I'm not sure why my tests from #7419 miss this, but the following doesn't match on hxcpp still:

`trace(~/::/.match("😂::test::"))`

**Comment by Simn** [comment]
Never mind, it passes after deleting my export/cpp directory.

Also confirmed the original BOM example to work now!
