### ISSUE TITLE
[display] -java-lib types don't show up in completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7417]
It seems `-java-lib` doesn't work for code completion anymore. Since hxjava [includes some standard library types via that argument](https://github.com/HaxeFoundation/hxjava/blob/master/extraParams.hxml#L1), this is easy to test:

![](https://i.imgur.com/dIqT9DI.png)

With 3.4.7:

![](https://i.imgur.com/dhmGaAl.png)

This appears to be specific to completion in "online mode" with a server, a simple `haxe -java foo --display Main.hx@52` on the command line works as expected.

**Comment by Simn** [comment]
My understanding is that these native libs serve as a lazy type lookup source, so I have some trouble understanding how this is supposed to work for completion. In fact, I also don't understand why this works in non-server mode.

**Comment by Simn** [comment]
Note that this works for import-completion because `read_type_path` iterates over `com.java_libs`.

**Comment by Simn** [comment]
The problem here is that we now use toplevel completion in these cases and the `java_libs` content is not respected there. That's also not something we could easily change because it would lead to either the entire java lib being dumped into the server context, or being looked up on every toplevel request.

**Comment by Simn** [comment]
I have no solution for this but it shouldn't block a release.

**Comment by Simn** [comment]
Pushing this to 4.1. It's a regression but I don't have a solution. I think we have to review `-java-lib` on a larger scale.

**Comment by Simn** [comment]
Consolidating this in #7450.
