### ISSUE TITLE
Warnings in haxe.Json

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#7421]
/haxe/std/js/_std/haxe/Json.hx:31: lines 31-33 : Warning : Extern non-inline function may not have an expression
/haxe/std/js/_std/haxe/Json.hx:36: lines 36-38 : Warning : Extern non-inline function may not have an expression
Actually these make sense...

```haxe
#if haxeJSON inline #end
public static function parse( text : String ) : Dynamic #if !haxeJSON ; #else {
  return haxe.format.JsonParser.parse(text);
} #end
```
Not pretty, but no warning.

**Comment by Simn** [comment]
I was thinking about just duplicating the entire class instead of having this conditional compilation insanity there... Not sure that's better.

**Comment by mockey** [comment]
To DRY or not to DRY...
Tough decision.
