### ISSUE TITLE
[eval] OCaml error on unknown std function

### ISSUE THREAD

**Issue by elnabo** [HaxeFoundation/haxe#7424]
Adding a function to a Std base class such as Array.hx and compiling to eval will result on a `Not_found` being thrown without being catched.

It is fixed once the function is declared to the OCaml std `builtins`

**Comment by Simn** [comment]
Given that normal people don't do this kind of thing, I find this an acceptable behavior. In fact, it's usually better to get real OCaml exceptions in these cases because it helps understand what's going on better than some user-friendly error message.
