### ISSUE TITLE
Allow [] for empty Map

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7426]
I think that we should allow [] for empty Map when using top down inference, given we allow [key=>value].

**Comment by RealyUniqueName** [comment]
Does it make sense to support `[=>]` as a map initializer?
```haxe
var map = [];
map.set(key, value); //Error: Array does not have method `set` 

var map = [=>];
$type(map); //Map<?,?>
map.set(key,value); //Ok
```

**Comment by Simn** [comment]
Heh, I thought you were against this last time it came up. But I'm happy to support it.

**Comment by cambiata** [comment]
Using Haxe Compiler 4.0.0-rc.2+77068e10c, this does't seem to work for` haxe.ds.StringMap`, `haxe.ds.IntMap` etc. Is this expected behaviour?

**Comment by Gama11** [comment]
You're meant to use the `Map` abstract, not the implementation classes.
