### ISSUE TITLE
Compilation should failed when there is a typo in a macro name

### ISSUE THREAD

**Issue by MangelMaxime** [HaxeFoundation/haxe#7431]
When there is a typo in a macro name the compilation should fail. It seems to not be the case when the macro is affected to a variable.

**Macro code**
```haxe
class Async {
	public static macro function async(expr:haxe.macro.Expr) {
		return macro untyped __js__("(async {0})", ${expr})();
	}

	public static macro function await(expr:haxe.macro.Expr) {
		return switch (haxe.macro.Context.typeof(expr)) {
			case TInst(_.toString() => "js.Promise", [t]):
				var ct = haxe.macro.TypeTools.toComplexType(t);
				return macro(untyped __js__("await {0}", ${expr}) : $ct);

			default:
				throw 'await() is only available for promises';
		}
	}
}
```

**Main code**
```haxe
class Test {
	static function main() {
		trace("Start the program");
		new Runner().run();
	}
}

class Runner {
	public function new() {}

	public function run() {
		Async.async(function() {
			var now = Async.await(resolveAfter2Seconds());

			// This line should not compile
			// We are missing the `c` letter to Asyn
			var now2 = Asyn.await(resolveAfter2Seconds());

			// This line doesn't compile and this is correct method resolveAfter2 doesn't exist
			var now3 = Async.await(resolveAfter2());
		});

		// This line doesn't compile and this is correct
		Async.async(function() {});
	}

	static function resolveAfter2Seconds() {
		return new js.Promise(function(resolve, reject) {
			untyped __js__("setTimeout")(function() {
				resolve(Date.now().toString());
			}, 2000);
		});
	}
}
```

Tested with **haxe 3.4.4**
[Try haxe](http://try-haxe.mrcdk.com/#d8Efc)

**Comment by nadako** [comment]
That happens because you're generating `untyped __js__(...)`, so compiler doesn't care about typos when typing the resulting expression of your macro call.

One option here would be to force typing of the incoming expression and referencing it later in the `untyped` section like this:

```haxe
	public static macro function async(expr:haxe.macro.Expr) {
		expr = Context.storeTypedExpr(Context.typeExpr(expr));
		return macro untyped __js__("(async {0})", ${expr})();
	}
```

> PS you would want to type the expression anyway to get the function's return value so you can add a `Promise` type-hint to the result of your `async` expr.

**Comment by MangelMaxime** [comment]
I see thank you for the explanation :)

**Comment by MangelMaxime** [comment]
About this part:

> PS you would want to type the expression anyway to get the function's return value so you can add a Promise type-hint to the result of your async expr

Is the `Context.storeTypedExpr` enough to get the hint or do I need to add another instruction?

I am asking because I know I can't do that:

```haxe
	public static macro function asyncPromise(expr:haxe.macro.Expr):js.Promise<T> {
		expr = Context.storeTypedExpr(Context.typeExpr(expr));
		return macro untyped __js__("(new Promise(async {0}))", ${expr});
	}
```

because I am in a macro and cannot access the `js` package.
