### ISSUE TITLE
Externs for interfaces with static fields? 

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#7434]
Hi,

Currently, Haxe does not allow to declare static variables in interfaces. 
But in Java it is allowed and writing externs is a bit painful for that kind of interfaces.

Here is an example of Java interface which contains static vars: 
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/ActionCodeResult

Would be nice if Haxe will allow to declare static vars for interfaces if they marked as `extern`.

Thank you :)

**Comment by Simn** [comment]
Seems fair to allow this for externs.
