### ISSUE TITLE
High cpu in handle_decoding_error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7435]
Today we experimented what seems at first a compiler infinite loop which was giving the following stack:

```
Fatal error: exception Sys.Break
Raised at file "sys.ml", line 102, characters 52-57
Called from file "_build/src/macro/eval/evalMain.ml", line 468, characters 12-28
Called from file "list.ml", line 88, characters 24-34
Called from file "_build/src/macro/eval/evalMain.ml", line 466, characters 17-171
Called from file "_build/src/macro/eval/evalMain.ml", line 508, characters 15-30
Called from file "_build/src/macro/eval/evalMain.ml", line 515, characters 16-34
Called from file "_build/src/macro/eval/evalMain.ml", line 454, characters 12-46
Called from file "pMap.ml", line 157, characters 9-27
Called from file "_build/src/macro/eval/evalMain.ml", line 447, characters 11-502
Called from file "_build/src/macro/eval/evalMain.ml", line 468, characters 12-28
Called from file "list.ml", line 88, characters 24-34
Called from file "_build/src/macro/eval/evalMain.ml", line 466, characters 17-171
...
```

This is actually a loop into `EvalMain.handle_decoding_error` after a build macro error over a >4000 lines file.

I thought it came from an infinite recursion but I was not able to find it, and after some checks I noticed that it was indeed progressing, but at a decreasing speed. It seems to build a very very large String at a very slow rate. It eventually returns and prints the error after a few minutes of loop (about 225.000 loops) which is a ~5MB String, all for a single error.

This can be trim down to a simple example that still outputs way too much errors:

```haxe
// haxe -lib hxbit -main Main
class Main implements hxbit.NetworkSerializable {
	
	@:rpc(server) function foo( ?x = true ) {
		return true;
	}
	
	static function main() {
	}
	
}
```

Here's also a suggested patch for returning such errors as part of the error message instead of printing them to stdout, which is useless when using compilation server.

[handle_error.diff.txt](https://github.com/HaxeFoundation/haxe/files/2388513/handle_error.diff.txt)

**Comment by Simn** [comment]
I didn't send it through error because then every line is prefixed with `source/Main.hx:2: character 1 :`, which is stupid... Maybe I should just dump the content to a file and mention it in the error message.

**Comment by ncannasse** [comment]
@Simn depends how much error lines there are. Usually there shouldn't be too many if done right - which does not seem the case right now. In which case all having the same position is good enough for me.

**Comment by ncannasse** [comment]
This does not close the issue : minutes to get the error result is way too much :)

**Comment by ncannasse** [comment]
Maybe using a proper String buffer instead of string concat would help

**Comment by Simn** [comment]
Oh, I thought the slowdown came from the console output.

**Comment by Simn** [comment]
See if that helped.

**Comment by ncannasse** [comment]
Works perfectly. I'm still not fan of the output, sending you on slack what I got

**Comment by Simn** [comment]
I kind of forgot what we wanted to do here...

**Comment by ncannasse** [comment]
Well, I don't want anymore the debug output to be part of error messages, so I'll close.
