### ISSUE TITLE
Warning: private structure fields are deprecated

### ISSUE THREAD

**Issue by sh-dave** [HaxeFoundation/haxe#7436]
This code in haxe's std library will generate a `characters 2-9 : Warning : private structure fields are deprecated` warning when compiling for python:

https://github.com/HaxeFoundation/haxe/blob/4bdba50da8e7e25c909c6ef9500d59752bf2c846/std/python/NativeIterable.hx#L47-L49

**Comment by frabbit** [comment]
what's the best approach here, i can make it public, but i'm not sure if that's nice.

**Comment by ncannasse** [comment]
If it's internal use only I don't see any problem to make it public.

**Comment by Simn** [comment]
Well, that changes unification behavior.

**Comment by Simn** [comment]
Moved to 4.1 because it's not urgent.

**Comment by Gama11** [comment]
Honestly, I think it would be quite unfortunate if final 4.0 spits out a compiler warning on every compilation for a specific target, that makes it look like it's no longer maintained or something.

A hack to work around it might not be the worst alternative here, considering there's nothing like a `@:noDeprecation` meta as of yet as far as I can tell. https://github.com/HaxeFoundation/haxe/pull/7865

**Comment by Simn** [comment]
We have a nice terrible hack for this now and I don't think the python target is going to get any more attention than that in the foreseeable future.
