### ISSUE TITLE
Wrong Unicode length

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#7437]
"éあ😂".length will return 4 (development ) . Previous Haxe 4.0.0-preview.4 will give  9 
Target:  Interp

On https://mothereff.in/byte-counter for éあ😂 get 3 characters and 9 Bytes as result.

Here is hex representation:
é = c3a9
あ = e38182
😂 = f09f9882

What should return lenght ?  Bytes or characters  ?

**Comment by Simn** [comment]
4 is correct given UCS-2 encoding. You get the same result on JavaScript.

**Comment by ncannasse** [comment]
#if utf16 you will get 4 chars, #else 3 
In all cases you will get 9 utf8 bytes

**Comment by Simn** [comment]
Backwards
