### ISSUE TITLE
Nested anonymous structures will fail to autocast?

### ISSUE THREAD

**Issue by ciscoheat** [HaxeFoundation/haxe#7446]
Is there any reason this shouldn't work?

```haxe
class GameObjectFactory {
    public function new() {}
    public function text(s : String) trace(s);
}

class Game {
    public function new(factory) this.add = factory;
    public var add : GameObjectFactory;
}

typedef TextAdder = {
    var add : { 
        function text(s : String) : Void;
    }
}
    
class Test {
    static function main() {
        var factory = new GameObjectFactory();
        var game = new Game(factory);
        
        // Works
        game.add.text("Trace 1");
        
        // This typedef autocasting doesn't work
        var adder : TextAdder = game;
        adder.add.text("Trace 2");
    }
}
```

It works by changing `TextAdder` to

```haxe
typedef TextAdder = {
    var add : GameObjectFactory;
}
```

...but that goes against the point to have a generic typedef. Link to code: https://try.haxe.org/#eBCd8

**Comment by Simn** [comment]
This violates variance because `TextAdder.add` is writable. If the assignment was allowed, you could assign something to `adder.add`, but that would effectively modify `game.add` as well, while it should remain an instance of `GameObjectFactory`.

Work if you change `TextAdder.add` to `var add(default, never)`.

**Comment by ciscoheat** [comment]
Thank you Simon, obvious now that you've explained it. Nice work supporting this scenario with (default, never)!

**Comment by jcward** [comment]
Just when I was about to lose faith in typedef...

> Work if you change `TextAdder.add` to `var add(default, never)`

Gold! :+1: :+1: :+1: Three thumbs up! https://try.haxe.org/#2c463

```haxe
typedef TextAdder = {
    var add (default,never) : { 
    	function text(s : String) : Void;
    }
}
```
