### ISSUE TITLE
Uninitialized variables not checked

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7447]
```haxe
class Main {
		
	static function main() {
		var x : String;
		trace((function() return x)());
	}
	
}
```

Not a regression, but this seems like a serious issue (can crash HL/HxCPP/etc.)

I remember allowing it because there was some valid code such as:

```haxe
class Main {
		
	static function main() {
		var x : String;
		function foo() {
			return x;
		}
		x = "55";
		trace(foo());
	}
	
}
```

One easy option is to only do the uninitialized vars check for unnamed local functions. 

That still leaves crash potentials for named functions.
We could as well force their check for uninitialized vars the first time we access its identifier.

**Comment by ncannasse** [comment]
Note that this change might introduce new errors at compilation. Better have it settled for Haxe 4.0

**Comment by Simn** [comment]
The named function distinction makes sense.

**Comment by Simn** [comment]
How do you feel about the inverse case where the local function initializes the variable?

```haxe
class Main {
	static public function main() {
		var x:String;
		function f() {
			x = "foo";
		}
		f();
		trace(x);
	}
}
```

This currently is admitted even if the `f()` call is missing.

**Comment by Simn** [comment]
Thinking about this again, I'm not sure anymore if I like the named function distinction. There's no semantic difference between assigning a local function to a local variable and passing the local function as some call argument. Both can cause aliasing and lead to the function being called at any point.

The more I think about this, the more I feel like we should just follow normal lexical order here. I doubt there are many cases where we have `var v; function f() { v; }; v = e;`. Plus it's easy to fix by adding some neutral initialization to the variable in question.

**Comment by ncannasse** [comment]
Uhm. maybe. One "smarter" way of doing would be to delay (for named function) the check at the first time the function is actually referenced, but I'm not sure it's easy to do.

**Comment by Simn** [comment]
I took a look at this and tried to make it smarter, but came across a problem. We currently handle control flow terminators like `return` by setting all known variables to initialized. This means that the following two functions are indistinguishable as far as the initialization state of `y` is concerned:

```haxe
function foo () {
    y = "1";
}

function foo() {
    return;
}
```

Changing this would require a more elaborate approach to branch handling that only joins blocks that actually terminate.

**Comment by Simn** [comment]
Moving to 4.1 as I don't think this is going to break any sane code.

**Comment by RealyUniqueName** [comment]
Let's just prohibit the usage of uninitialized locals in closures and named function.
```haxe
var v:Array<Int>;

function pushToV() v.push(1));

schedule(() -> v.push(1));
schedule(pushToV);

v = []; // no way to find out if `schedule` will execute our function before or after this line.
```

**Comment by RealyUniqueName** [comment]
So, what's the decision?
How about just emitting a warning in such cases?

**Comment by ncannasse** [comment]
I'm fine with proposed warning as transition, which should become an error in another haxe version.
