### ISSUE TITLE
Hex escape sequences in strings greater than 127

### ISSUE THREAD

**Issue by rhacking** [HaxeFoundation/haxe#7449]
The following code:
```Haxe
class Test {
    static function main() {
        var x = "Haxe is great! \xdc";
        trace(x.charCodeAt(x.length-1));
    }
}
```

when compiled to JavaScript and run with node outputs `Test.hx:4: 65533`, instead of the expected `220`. It appears the code still works as long as the hex value is <= 127. For example:
```Haxe
class Test {
    static function main() {
        var x = "Haxe is great! \x7f";
        trace(x.charCodeAt(x.length-1));
    }
}
```

Outputs `127`, but it increasing it by 1 again results in `65533`. I tried with both Haxe 3.4.7 and Haxe 4.0.0-preview.4+1e3e5e016 and got the same results.

**Comment by Aurel300** [comment]
The issue is that Haxe puts the string into the Javascript output essentially as binary data, i.e. instead of `\xDC` it puts a byte with the value `0xDC`. This causes a problem because UTF-8 expects more data do follow `0xDC`.

I guess the compiler should not output the byte directly in JS, if it is not a valid Unicode sequence?

**Comment by Simn** [comment]
I don't really know what behavior to expect from something like this...

**Comment by rhacking** [comment]
I would expect Haxe to output something like this for Javascript:
```JavaScript
// Generated by Haxe 3.4.7
(function () { "use strict";
var HxOverrides = function() { };
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
var Test = function() { };
Test.main = function() {
	var x = "Haxe is great! \xdc";
	console.log(HxOverrides.cca(x,x.length - 1));
};
Test.main();
})();
```

Which would result in `220` being outputted

**Comment by Simn** [comment]
That's not how escaping works though...

**Comment by Aurel300** [comment]
If you had `"C is great \xdc"` in C code, the string would include the byte `0xDC` just before the null byte. In general I would expect any binary data you put in a string to be preserved in the output, which may involve keeping the escape sequence on the JS target.

Internally, Javascript stores its strings as UTF-16, and it has both `\x` and `\u` escape sequences, so:

```javascript
"\xDC\x80".length === 2
"\u0700".length === 1
// 0xDC 80 is the UTF-8 representation of the Unicode codepoint 0x070:
encodeURIComponent("\u0700") == "%DC%80"
```

If Haxe preserves the escape sequence for anything above `0x7F` (i.e. non-ASCII, potentially multi-byte sequences), then the result of `charCodeAt` in the original issue will work fine. As it is, there is an inconsistency in behaviour:

```
$ haxe -main Main -neko out.n
$ neko out.n
Main.hx:4: 220
$ haxe -main Main -js out.js
$ node out.js
65533
$ xxd out.n | grep "foobar"
00001e0: 0003 0800 666f 6f62 6172 20dc 016f 3a31  ....foobar ..o:1
$ xxd out.js | grep "foobar"
0000110: 2266 6f6f 6261 7220 dc22 3b0a 0963 6f6e  "foobar .";..con
```

Both outputs represent the string the same way, but Javascript first has to parse it as a UTF-8 string, neko (I guess) just treats it as raw bytes.

**Comment by Simn** [comment]
But `\x` means byte, not character. The inconsistencies come from the fact that the targets have different string representations at run-time. If you start modifying at byte-level then that's only expected and you can achieve the same behavior through the Bytes API.

**Comment by Aurel300** [comment]
To be honest, I can't see an easy way to 100% resolve this either. Perhaps issue a warning when using such an escape? Why allow it at all when it produces different results on different platforms?

**Comment by Simn** [comment]
We certainly have to do something because right now this causes issues on various targets.

**Comment by ncannasse** [comment]
"\xDC".charCodeAt(0) should be 220, so yes haxe compiler need to UTF8-encode the String

**Comment by Simn** [comment]
Changing this breaks this test:

```
eq( haxe.Resource.getBytes("re/s?!%[]))(\"'1.bin").sub(0,9).toString(), "MZ\x90\x00\x03\x00\x00\x00\x04" );
```

**Comment by Simn** [comment]
So this is a breaking change and I'm still not convinced it's the right thing to do. `\x` is a byte thing, not a character thing.

**Comment by ncannasse** [comment]
Yes but Strings contain chars not bytes.
The test should be changed using  toHex() instead of toString()

**Comment by Simn** [comment]
This suggests to me that we should error for all char != byte cases, i.e. \x > 127. On the other hand, that seems pragmatically annoying, so I've changed it to treat the character as unicode character.
