### ISSUE TITLE
Compile for non-GC platforms

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#7451]
Slightly related to https://github.com/HaxeFoundation/haxe/issues/1649

I understand the problem is that Haxe can easily target GC platforms (i.e. Python, JS, AS3.0, PHP, Java …) since the language itself assumes garbage collection. `hxcpp` only works because it has a lot of custom GC code (as far as I understand).

Would it be at all beneficial to develop a framework / IR of some sort where Haxe emits code and stubs which then plug into platform-specific GC code? I.e. indicate which variables are used in functions, reference counting, closure scopes …

This could be useful for targetting `asm.js` or simplifying C / C++ / Objective-C compilation.

Thoughts?

**Comment by ncannasse** [comment]
I have no idea exactly what you're requesting exactly. Each platform have its own GC and require specific treatment wrt memory allocation.

**Comment by Aurel300** [comment]
@ncannasse Yes, GC platforms like Python, JS, etc. already have their own GC implementations, this issue is not about those.

However, targetting (Objective-)C(++), assembly code, or `asm.js` (can't think of others) seems to have a lot in common with regards to what information Haxe can provide to the specific generator. The generator would obviously have to process this further.

Consider a simple allocation in a function:

```haxe
function makeStruct():{x:Int, y:Int} {
  return {x: 1, y: 2};
}
```

Regardless of which target this is compiled for, the struct needs to be allocated some space in memory, and if it is to be correctly garbage collected at some point, the GC needs to know about it, i.e. it could extend this allocation with a reference counter, or add it to its instance pools, depending on the type of GC.

Currently `hxcpp` is the only target that does all of this. If there ever were e.g. a dedicated `hxasmjs` target, it would have to do a lot of the same work.

Here https://github.com/HaxeFoundation/haxe/issues/1649#issuecomment-27342491 you say it is not feasible to target `asm.js` due to the absence of GC. Would that not have eliminated `hxcpp` as a feasible target?

**Comment by Simn** [comment]
> If there ever were e.g. a dedicated hxasmjs target, it would have to do a lot of the same work.

And it would be great if it did that work in a re-usable way. The author of such a target should certainly be encouraged to look into similarities to hxcpp and factor things out accordingly. However, there's nothing actionable for us here because we cannot invest resources into supporting hypothetical future targets.

Still, if you want to look into this and require our support in some way, don't hesitate to ask.
