### ISSUE TITLE
Defining a parametrised typedef in a macro

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#7459]
I am trying to reproduce the `typedef` in the following snippet using a macro:

```haxe
typedef NumericVector<T:Float> = haxe.ds.Vector<T>;

class Main {
  public static function main():Void {
    var vec:NumericVector<Float> = haxe.ds.Vector.fromArrayCopy([1.0, 2, 3]);
    trace("my numeric vector: " + vec);
  }
}
```

If I dump the module types using `haxe.macro.Context.getModule`, I get:

    [TType(NumericVector,[TInst(NumericVector.T,[])]),TInst(Main,[])]

Which seems to indicate that `T` is not a real type and is only present in the `params` array of the `NumericVector` type definition. And indeed, if I create a type without actually using the type parameter on the "right-hand side", i.e. to reproduce the following:

```haxe
typedef MacroVector<T:Float> = Bool;
```

Then the following macro works fine:

```haxe
public static function defineMacroVector():Void {
  Context.defineModule("MacroVector", [{
       fields: []
      ,kind: TDAlias(TPath({name: "Bool", pack: []}))
      ,name: "MacroVector"
      ,pack: []
      ,params: [
          {name: "T", constraints: [TPath({name: "Float", pack: []})]}
        ]
      ,pos: Context.currentPos()
    }]);
}
```

If I dump the module defined with the above, I get:

    [TType(MacroVector,[TInst(MacroVector.T,[])])]

But if I want to use the type parameter:

```haxe
public static function defineMacroVector():Void {
  Context.defineModule("MacroVector", [{
       fields: []
      ,kind: TDAlias(TPath({name: "Vector", pack: ["haxe", "ds"], params: [
          TPType(TPath({name: "MacroVector", pack: [], sub: "T"}))
        ]}))
      ,name: "MacroVector"
      ,pack: []
      ,params: [
          {name: "T", constraints: [TPath({name: "Float", pack: []})]}
        ]
      ,pos: Context.currentPos()
    }]);
}
```

Then I get the error:

    --macro:1: character 0 : Module MacroVector does not define type T

Is this intended behaviour? Should the type system recognise that the typedef's type parameters are valid types when resolving types? Should I define a stub type `T`?

**Comment by nadako** [comment]
I see why it can be confusing, but remember, everythin in `haxe.macro.Expr` is pure syntax, so `TPath({name: "MacroVector", pack: [], sub: "T"})` is literally the same as if you'd type `MacroVector.T`, which I think will give you the same error. Try doing `TPath({name: "T", pack: []})`, or simply `macro : T`

**Comment by Aurel300** [comment]
Yep, `TPath({name: "T", pack: []})` works fine. I thought I tried that :/

Thanks!
