### ISSUE TITLE
Confusing error message when the wrong package is specified

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#7460]
The error messages generated when `package` is specified wrong are really confusing, e.g.:

    Main.hx:3: characters 4-22 : Invalid package : test.pkg should be <empty>

Looks like an error in `Main.hx` when it is actually hidden in the file `test/pkg/Something.hx`, which is missing `package test.pkg`. A better error message would be:

    test/pkg/Something.hx:1: Missing package statement

Or:

    test/pkg/Something.hx:1: Invalid package : <empty> should be test.pkg

**Comment by Gama11** [comment]
I think this should be covered by https://github.com/HaxeFoundation/haxe/commit/d415a7d8f18a08c6e253e38057b165392173d6dc, didn't know there was an issue for it. :)
