### ISSUE TITLE
Macro broken

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7465]
by this commit: 97c236d7f7cb766ae7d5f35a36e71ffe8c43dac1

Steps to reproduce:

```bash
git clone https://github.com/kevinresol/ecs
cd ecs
haxelib dev ecs .
haxelib git tink_macro https://github.com/haxetink/tink_macro
haxe playground.hxml
```

error: `Type not found : ecs.node.Node0`

If it is too complex I might try to reduce it, but I am not sure if I can...
The main problem is the lack of the position, rendering me totally lost....

**Comment by frabbit** [comment]
try to compile with -v

**Comment by kevinresol** [comment]
```
...
Typing macro tink.macro._BuildCache.Group.counter
Typing macro tink.macro.BuildCache.getTypeN
Typing macro tink.macro.BuildCache.getType2
Typing macro ecs.util.Macro.buildNode
Typing macro ecs.util.Macro.isComponent
Typing macro ecs.util.Macro.COMPONENT_TYPE
Typing macro ecs.util.Macro.buildSystem
Typing macro ecs.util.Macro.toTypeParams
Calling macro ecs.util.Macro.buildNode (tests/RunTests.hx:185)
Type not found : ecs.node.Node0
```

Not much help, before the broken commit the "Type not found" line is replaced by:
`Exiting macro ecs.util.Macro.buildNode`

**Comment by Simn** [comment]
I'm only getting this:

```
C:\GitHub\ecs>haxe playgound.hxml
tests/Playground.hx:68: lines 68-71 : You can only implement an interface
```

**Comment by kevinresol** [comment]
Sorry I made some changes since then, maybe you can change implement to extends, or let me fix it later.

**Comment by kevinresol** [comment]
Updated, please git again.

**Comment by kevinresol** [comment]
Reduced version: https://github.com/kevinresol/haxe_issues/tree/issue_7465

```
haxelib git tink_macro https://github.com/haxetink/tink_macro
haxe build.hxml
```

**Comment by Simn** [comment]
The debugger points me here: 

https://github.com/haxetink/tink_macro/blob/13d11f4f66c7fd868b666567be6c97b484407245/src/tink/macro/Types.hx#L20-L22

And indeed, the error message format changed from `Type not found 'ecs.node.Node0'` to `Type not found : ecs.node.Node0`.

The related haxe source is easy to determine:

https://github.com/HaxeFoundation/haxe/blob/36c470f889ede626c07f04ef6419ad53e533a18f/src/typing/macroContext.ml#L154-L158

That check has been there from the beginning:

https://github.com/HaxeFoundation/haxe/commit/275788da4c19cff71f81c159c14d48dc7ef538bd#diff-eb918bc546b40568ecadf7d9546c3119R1809

I don't like this position-based error handling very much, but I guess we'll have to deal with it.
