### ISSUE TITLE
[eval] BytesBuffer problem

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#7468]
According to documentation after call  bytesBuffer.getBytes(), the buffer won't be accessible anymore and should throw error (  "Once called, the buffer can no longer be used. " )
But in the example below trace will return:
```
Data: 0a0c
Data: 0a0c0c
```

Should be a error after the second .addByte(12); 

Target :  interp 
haxe : 4.0.0-preview.4+5fc66d086

Example:    https://try.haxe.org/#67F74  or the code below: 

```haxe
   var bytesBuffer = new BytesBuffer();
   bytesBuffer.addByte(10);
   bytesBuffer.addByte(12);
   var data = bytesBuffer.getBytes();
   trace("Data: "+data.toHex());
   bytesBuffer.addByte(12);
   data = bytesBuffer.getBytes();
   trace("Data: "+data.toHex());
```

**Comment by Simn** [comment]
wtf, why...

**Comment by flashultra** [comment]
I don't know. I think   bytesBuffer.clear() method and  dispose()  are more suitable . 
Now if you want to reuse buffer you should create new one every time.

**Comment by Simn** [comment]
@ncannasse: Is that a flash thing? Can we change the spec (even if it's broken on flash)?

**Comment by ncannasse** [comment]
We can specify _should no longer be used_ instead of _can no longer be used_, it that helps
