### ISSUE TITLE
[feature request] OrderedMaps

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#7469]
Maps/Dicts on which you could retrieve key->values in the order of insertion.

It happens quite frequently to write code that needs them. In the past I've used a slightly modified implementation from @underscorediscovery (https://gist.github.com/underscorediscovery/84341491930a5df325e7), but it would be a very nice addition to the haxe.ds package.

Can we have this?

(well maybe also Sets, but using Maps works just fine to emulate them)

**Comment by Simn** [comment]
Seems fine, please send a PR!
