### ISSUE TITLE
[eval] anti-string-optimization pattern

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7474]
It is currently possible to subvert my UTF-8 optimization by alternating access to early and late positions:

```haxe
import haxe.Timer;

class Main {
    public static function main () {
		var timeStart : Float = Timer.stamp ();

		var data : String = StringTools.lpad("", "a", 50000);
		for (i in 0...data.length) {
			StringTools.fastCodeAt (data, i);
			StringTools.fastCodeAt (data, data.length - i);
		}

		var timeEnd : Float = Timer.stamp ();
		trace ('total runtime: ${timeEnd - timeStart}s');
    }
}
```

This takes 7 seconds to execute on my machine.

I'm not sure how artificial something like this is, but I'd like to address it. I think it requires having an additional working pointer.

**Comment by Simn** [comment]
That's a bad timer because it includes the `lpad`. Moving that out, it takes about 5.2 seconds.

**Comment by Simn** [comment]
... and the reason I mention that is because now it takes 0.005 seconds.

**Comment by back2dos** [comment]
Does indexOf/lastIndexOf also update these "cursors"?

**Comment by Simn** [comment]
Yes, as does substr and substring, and StringBuf.addSub.

And thanks, "cursor" is the term I've been looking for.
