### ISSUE TITLE
sys: Log.trace uses println(), and thus stdout, when all diagnostic output should go to stderr

### ISSUE THREAD

**Issue by Osndok** [HaxeFoundation/haxe#7475]
Concerning:
* https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Log.hx#L68

The ```Log.trace()``` implementation for system targets uses ```println()```, and thus ```stdout```, when all diagnostic output must go to ```stderr```. This makes writing a proper command line utility quite precarious, because any debugging/logging statements (even in a 3rd party library) will get munged into the programs output (making the output incorrect), and hidden from the user (as the logging statements will enter the next program in the pipe chain).

**Comment by jcward** [comment]
The default trace / puts / console output of most scripting languages is stdout. In Haxe, you are specifically allowed to override the trace function, which will override it globally (for all included libraries, etc.)

_However_, there could be a "static initialization order" race condition wrt when the haxe.Log.trace function gets overridden vs when the first trace statement happens. Like this: https://try.haxe.org/#70583

How might that be solved?

1) arguably, authors should send errors to stderr on sys platforms... but presumably they won't / haven't.
2) arguably, Haxe could provide some error logging feature (haxe.Log.error?) alongside trace?
3) could a compiler macro ensure a certain static function gets run first? I dunno.
4) a class-path override can override haxe.Log at compile-time
5) a new [compiler flag / define](https://haxe.org/manual/compiler-usage-flags.html) could send trace to stderr, e.g. `trace-to-stderr`:

```haxe
		#elseif (sys && trace_to_stderr)
		Sys.stderr().writeString(str+"\n");
		#elseif sys
		Sys.println(str);
		#else
```

If Haxe std lib doesn't accept this idea, then 4) is still viable for scripting purposes.

**Comment by Simn** [comment]
As @jcward says, there are easy ways around this. I don't think we can change our standard behavior at this point, so I'll go ahead and close the issue.

I'm not sure about additional API for this. I usually use `Sys.stderr().writeString("out")`, but I acknowledge that that's a bit awkward.

**Comment by Osndok** [comment]
* https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)

To jcward's points:
a. "everyone else is doing it" - Even if that were true, it would not matter. This is literally in the definition of unix/C since the 70s, and is the very foundation for your ```system``` target. Even a quick check of ```man stderr``` will show that, and ```man logger``` has a flag for stderr, but not stdout. See:
b. "you can override it" - It must be the default. I cannot think of a reason that I would ever want to send diagnostic output to stdout, as it would (at BEST) still go to the terminal, and at worst (or even, the expected case) would be for it to lost forever and malforming the programs counterparts.
1. Yes, all errors **AND** diagnostic output should be sent to STDERR; this is literally done by 99% of the linux world, excepting the odd beginner shell-scripter that log only with ```echo```
2. No, having a ```Log.error``` indicates that you are "logging an error-level message", and does not help the ```trace()``` function
3. ...4,5 - I really don't think there is any reason for adding complexity, much less making this an opt-in option.

I was thinking about something very similar to your code bit (```Sys.stderr().writeString(str+"\n");```) could be substituted for the line in question as a least-cost fix, but was unsure how "performance-or-memory centric" the haxe devs might be (that it introduced a string concatenation, and they might want to add another path into stdlib).

To Simn:
* "it's too late" - **WOW**... really? This is hard to believe...
    * Surely it can't be for tradition... as being "incorrect" would be an odd tradition indeed.
    * Is it for danger of breakage? I hope you know that (for any case where it really counts) stdout and stderr are **connected** at the terminal, this literally effects only those cases where stdout diagnostics would be the one to cause breakage. In the worst case, this might trip up 'noobs' trying to grep a usage report, and serve to educate them concerning output redirection.
   * Is it for lack of organization? This would match my other observations from my limited experiments with haxe... widescale versioning breakage. In the absolute worst case, if this were to be considered a breaking change, I would expect it to be treated as such (between a major version number increment). Early mistakes must be dealt with as early as possible, and accruing technical/design debt will only make the problem worse down the road.
* "I usually use... a bit awkward" - I appreciate your admission that it **is** a problem, and one that you have had to work around yourself, no less.

I must say, I am surprised by this decision. Such a simple (yet foundational) error... an early mistake enshrined forever... devs knowing its incorrectness but being afraid of touching the code base as if it's a house of cards... I shudder to think of what would happen for a 'big problem'.

This does **not** fill me with confidence towards investing in the haxe ecosystem.

**Comment by jonasmalacofilho** [comment]
While I agree that having `trace` output to `stderr` is, err, sub-optimal, I don't necessarily agree with how @Osndok is laying out his arguments.

Still...

A lot else is already changing with Haxe 4, maybe it's a good time to revisit `trace` and also consider a more complete standard logging API, that can unify all the ad-hoc implementations we currently have/use.

Having a standard way of filtering and redirecting log messages of different levels and modules is really useful; custom `trace` implementations can already do some of that with `PosInfos`, but many libraries don't use it, and I would guess that is _because_ it defaults to `stdout`.

**Comment by Simn** [comment]
I'm not interested in drama so I'm gonna ignore all that.

@jonasmalacofilho: I'm not saying you're wrong, I just can't see what exactly we would do here. Standardizing something is often a good idea, but in order for us to do that, "something" has to exist in the first place.

Note however that I still don't think we have to do anything with `trace` itself because it should be considered a lightweight debugging feature. You are free to connect it to some logging framework, but that's not really its purpose. Or what exactly do you think is missing here, other than a good logging library?

**Comment by jcward** [comment]
> I cannot think of a reason that I would ever want to send diagnostic output to stdout

Your arguments about what is "right" assume 1) a platform where stderr even exists, and 2) that trace is specifically for "diagnostics". Haxe is cross-platform, and as the docs clearly say, trace(v) "Outputs `v` in a platform-dependent way." I would guess many consider `output` == `print`, and in a cross-platform sense, rightly so.

For the purposes of this bug "trace should use stderr" -- I think that's all we need to say.

Separately -- should Haxe provide some standard logging API? Beyond what exists today? Haxe:

1) Guarantees that `trace` will "output" on all platforms (even those which do not distinguish stdout / stderr)
2) Separately, for `sys` platforms which do recognize stdout/stderr, Haxe provides `Sys.stdout` and `Sys.stderr`.
3) Allows you to disable trace (`--no-traces` compiler flag) if it causes you a problem.
4) Allows you to override `haxe.Log`, either at compile-time, or at runtime.

> what exactly do you think is missing here

Indeed.

**Comment by jcward** [comment]
Here's a cross-platform aware possibility:

Haxe shouldn't go full "logging library" -- there are too many opinions about it (modules, log levels, etc). But since Haxe makes `trace` globally available, it _should_ provide better access to platform-specific output capabilities.

**Proposal:** Add a target parameter to `trace`, which would allow STDERR to be targeted on sys platforms (or other platforms to target custom logging, e.g. JS's `console.error`). Also, with a static var default, it could easily be set project-wide.

**What it would break:** any existing overrides of `haxe.Log.trace` would require the target parameter to be added (because PosInfos must be last.)

`snip haxe.Log.hx`
```haxe
...
	public static dynamic function trace( v : Dynamic, ?tgt:TraceTarget, ?infos : PosInfos ) : Void {
		if (tgt==null) tgt = default_trace_target;
		var str = formatOutput(v,infos);
		#if js
		if( js.Syntax.typeof(untyped console) != "undefined") {
			// Binding console.log may not work like this, but you get the idea:
			var func:String->Void = tgt==CONSOLE_ERROR ? (untyped console).error : (untyped console).log;
			if (func!=null) func(str);
		}
		#elseif lua
		untyped __define_feature__("use._hx_print",_hx_print(str));
		#elseif sys
		tgt==PLATFORM_DEFAULT ? Sys.println(str) : Sys.stderr().writeString(str+"\n");
		#else
		throw "Not implemented"
		#end
	}

  public static var default_trace_target:TraceTarget = PLATFORM_DEFAULT;
}

enum TraceTarget {
  PLATFORM_DEFAULT;
  #if sys
    // PLATFORM_DEFAULT is STDOUT
    STDERR;
  #end
  #if js
    // PLATFORM_DEFAULT is CONSOLE_LOG
    CONSOLE_ERROR;
  #end
  // #if flash
  //   // PLATFORM_DEFAULT is trace
  //   e.g. ON_SCREEN_TEXTFIELD, for example
  // #end
}

```

But this should probably be posed as an official Haxe evolution proposal.
