### ISSUE TITLE
[js] Move jquery and swfobject to haxelib

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#7478]
I'm not sure these belong in std, they assume you're targeting the web not node.js and they assume you have the right version of jquery or swfobject loaded – I think they're probably better moved to haxelib for haxe 4

I'm happy PR these to hx3compat if we're in favour of removing from std

**Comment by Simn** [comment]
Go for it

**Comment by andyli** [comment]
[jQueryExtern](https://lib.haxe.org/p/jQueryExtern/) has been a drop-in replacement of the js.jquery extern in std, so there is no need to create a new one for that.

Just create one for swfobject.
