### ISSUE TITLE
Loop in class building prevent compiler termination

### ISSUE THREAD

**Issue by Dimous** [HaxeFoundation/haxe#7479]
Hello
The latest **working** build is 4.0.0-preview.4+dd1c8fd89 

Next builds, for example 4.0.0-preview.4+0a357a596, 4.0.0-preview.4+f9f38589e are throwing:

> C:/HaxeToolkit/haxe/lib/openfl/git/src/openfl/_internal/renderer/context3D/Context3DMaskShader.hx:13: lines 13-70 : Loop in class building prevent compiler termination (openfl.display.Shader)

on the same code

**Comment by Simn** [comment]
Any way to reproduce this?

**Comment by Dimous** [comment]
|  |  |
| --- | --- |
| Windows | 10 x64 |
| Haxe | 4.0.0-preview.4+0a357a596 |
| Lime | git 9cefba1354f36618a40561eedc8cc9cae8b6b833 |
| Openfl | git 55cfcf285c99c39c503eb218ba651daa754bb536 |

I ran https://github.com/openfl/openfl-samples/tree/master/haxelib/demos/BunnyMark with `C:\HaxeToolkit\haxe/haxelib" run lime build "project.xml" neko -release -Dfdb -clean`
