### ISSUE TITLE
[eval] int switch optimization

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7481]
Eval currently does not optimize switches on int, which can be noticed in constructed examples such as this:

```haxe
class Main {
	static public function main() {
		var K = 5000000;

		var t = Timer.stamp();
		for (i in 0...K) {
			switch (i) {
				case 0, 1, 2, 3, 4, 5, 6, 7, 8, 9:
				case 10, 11, 12, 13, 14, 15, 16, 17, 18, 19:
				case 20, 21, 22, 23, 24, 25, 26, 27, 28, 29:
				case 30, 31, 32, 33, 34, 35, 36, 37, 38, 39:
			}
		}
		trace(Timer.stamp() - t);
	}
}
```

Each of these `case` lines adds about 0.5s to execution. This is due to the sequential equals checks the implementation does.

We can instead do the following:

* For smallish number ranges (< 256?), we can create an `(env -> value) array` and index into it.
* For larger ranges, we can try using a `(env -> value) IntMap.t` and look up there.

There might be some Map-usage potential for this in general, not just for ints.

**Comment by ibilon** [comment]
Note that your example is an even more special case, where the number are sequential,
which could be optimized further with two comparison per case.
Though that's probably rare enough to not bother.

**Comment by Simn** [comment]
This works much better now. I doubt anyone is gonna notice this in real life, but I still like to have this out of the way.

I also tried using map lookups for string matches, but that only becomes more efficient after a certain number of cases. There's probably a better approach to deal with string switches. I think I discussed that with @waneck long ago, but I don't remember what our conclusion was.
