### ISSUE TITLE
CI log is still noisy

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7482]
Are there some more silent flags we can add?

Some offenders:

* `Command: sudo [apt-get,-o,dir::cache::archives=/home/travis/apt-cache,install,-y,mono-devel,mono-mcs]`
* `Command: wget [https://bitbucket.org/pypy/pypy/downloads/pypy3-2.4.0-linux64.tar.bz2]` (note that this shows up in both `macro` and `python`, which another thing we should look into)
* `Command: wget [http://apache.osuosl.org//flex/4.16.0/binaries/apache-flex-sdk-4.16.0-bin.tar.gz]`
* `Command: luarocks [help,--lua-incdir]` (the problem with this one is that it is run 5 times)

**Comment by andyli** [comment]
I added `-qq` to apt-get that should make it slightly less noisy, but it will still output tons. It doesn't have a "actually quiet" option.

wget: easy, added -nv.

The luarocks commands were somehow wrong and I've fixed that and their output is much shorter (and correct).

Let me know if there is anything unsatisfactory.

**Comment by Simn** [comment]
Much better, thank you!
