### ISSUE TITLE
Cannot build development branch (can 3.4.7) on Linux, ocamlfind: package extlib not found

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7486]
Like the title says, I can build `3.4.7` tag, but not `develpoment` branch.

From Ubuntu 16.04, 64-bit linux, 16.04, ocaml 4.02.3 and extlib 1.7.5:

![image](https://user-images.githubusercontent.com/2192439/46181940-f57f4e00-c285-11e8-963c-c0f19ef12259.png)

@andyli - have the requirements changed?

**Comment by andyli** [comment]
Our CI built it without problem and I also built it my Ubuntu machine.
Double check your submodules and also clean everything (`git clean -fdx` in both the project root and each of the submodule dir).

**Comment by jcward** [comment]
Interesting, peeking in .travis.yml, running [these lines](https://github.com/HaxeFoundation/haxe/blob/development/.travis.yml#L88-L92) did build haxe successfully:

```
make package_src -s
opam config exec -- make -s STATICLINK=1 libs
opam config exec -- make -s -j STATICLINK=1 haxe
opam config exec -- make -s haxelib
make package_bin -s
```

Perhaps the [instructions in BUILDING.md](https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md#compile) need to be updated? I'll close this bug.

**Comment by andyli** [comment]
Probably you didn't run 
```
eval `opam config env`
```

Normally opam asks if you want to add this line to your .bashrc/.profile when you install opam. Maybe you've said no, in which case you have to run it manually run it whenever you want to use opam.
