### ISSUE TITLE
[Java] NPE when using Type.createInstance and null constructor params

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/haxe#7505]
Hi there,

So there is an issue currently in hxJava whereby if you try to pass a `null` value as a constructor param it causes an NPE and the whole app crashes. eg:

```haxe
Type.createInstance(SomeClass, [1, null, 2]);
``` 

This is because the code in Type.java attempts to get the class from the params passed, one of which is `null`

Extract from Type.java:

```java
Object o = args.__get(i);
objs[i]= o;
cls[i] = o.getClass(); // <--------------- this is the issue
boolean isNum = false;
```

I had a quick go at patching it and its a little more involved than i originally assumed (hence no PR).

Cheers,
Ian

PS: i also opened the issue here (https://github.com/HaxeFoundation/hxjava/issues/24) possibly erroneously.

**Comment by nmamaev-tivo** [comment]
I believe it's fixed by commit b760ddc22c2436a44dc686c4d81070f3e29fbb58

**Comment by RealyUniqueName** [comment]
Indeed, this is not reproducible anymore.

**Comment by ianharrigan** [comment]
Great.

Cheers guys,
Ian
