### ISSUE TITLE
Lambda.filter casting wrong on nightlybuild

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe#7508]
Hello :)

```haxe
class Test {
  static function main() {
    var a = [1,2,3];
    var l = Lambda.filter(a, function( e ) return true);
    trace(l.first());
  }
}
```
Working on stable version, and failing on nightly
```
Test.hx:5: characters 11-18 : Array has no field first
```
http://try-haxe.mrcdk.com/#e4201

**Comment by Simn** [comment]
Lambda functions return `Array` now instead of `List`. You can use `-lib hx3compat` to preserve the old behavior.
