### ISSUE TITLE
Jquery status

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7510]
ATM jquery is part of hx3compat, and jqueryExtern does rely on it.

So there's no way for instance to use jquery without all the old compatibility libraries, which might be breaking some things (for instance Lambda changes).

**Comment by haxiomic** [comment]
I've updated my PR (https://github.com/andyli/jQueryExternForHaxe/pull/24) to get the jQueryExterns working with the latest haxe without `hx3compat` dependence so jQueryExterns should be ready to use once merged.
