### ISSUE TITLE
enhanced inline constructor / inline class / struct-like class

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/haxe#7513]
- when passed as an argument, expand it in the argument list. (those graphic API of x, y, this is the need)
- when declared in argument list, expand it too.
- when declared as a class field, expand it tooooo.
- for an Array / other data structure `of`(VB.NET) it... (column array?) (as key?)
- when appeared as a type parameter....
- automatic packing/unpacking across (specified) bounds? (when stored, create a structure; when `arrayAccess`ed, extract fields)
- per-field copy on assignation
- at some status of customization, perfect match C struct?
- towards C++ class ...

**Comment by Simn** [comment]
If you want a feature like that, please head on over to https://github.com/haxefoundation/haxe-evolution and make a proper proposal for it.
