### ISSUE TITLE
Bad unification when static fields are involved

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#7526]
## Overview

Invalid unifications are passing if static fields are involved

For example, this compiles:

http://try-haxe.mrcdk.com/#d2d21
```haxe

class C {
	
	static private var member: Int = 42;

}


// unification should fail because member is private
trace((C: { member: Int }).member); // 42
```

(The same issue applies for abstracts and enum statics)

This is the same bug as reported #4910 but the fix from then didn't solve the underlying problem.

Not a regression

## Explanation

When unifying haxe first executes `type.ml: type_iseq` to check for a direct match, if false then it tries `type.ml: unify`. The bug is in `type_eq`: when testing `TAnon` against `TAnon` it doesn't check `TAnon.a_status` (and maybe other things it should check...) and so the type check can pass without properly unifying

`type.ml: unify_anon` seems to work correctly – if you add an extra field to `class C` in the example, it'll fail the `type_iseq` direct match test and then correctly fail `type.ml: unify_anon`.

## Proposed Fix

Check that `TAnon.a_status` matches in `type_eq`, we might also want to add other checks to prevent future bugs but that change solves the specific issue without changing much.

**Comment by Simn** [comment]
This isn't valid because `member` is _not_ private. Structure fields default to public visibility. In fact, we deprecated private structure fields.

This also suggests that your change in #7527 is too wide and breaks _public_ unification.

**Comment by haxiomic** [comment]
Surely we shouldn't be able to coerce a private static field to a public field when unifying? – I'm not aware of any languages that allow that

To illustrate the bug, if you add another unused field to the example you get the expected access error:
*The field 'member' is not public*

http://try-haxe.mrcdk.com/#90F25
```haxe
class C {
	
	static private member: Int = 42;
	static private anotherMember: Int = 84;

}

trace((C: { member: Int }).member);
```

I'm not convinced the change breaks public unification (tests all pass and I can't think of an example that would break it)

**Comment by Simn** [comment]
Right, I shouldn't look at pull requests before my first coffee. I thought you meant the structure field was private, but it's about the class field. So the issue is valid, I'll comment more on the PR.
