### ISSUE TITLE
FileSystem.lstat

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7530]
Same as `FileSystem.stat()` but doesn't follow symlinks.

**Comment by ncannasse** [comment]
I think this would be better by adding an optional parameter `followSymLinks:Bool` to `stat()`
But tbh we have many platforms to update when we change something in Sys API, so I guess some discussions are required first to know exactly what we should add. We will raise the topic after 4.0 final is release.

**Comment by Simn** [comment]
We aren't going to make additions like this to the current sys API and instead focus on a new sys API.

**Comment by Aurel300** [comment]
It's a part of the new sys APIs already.
