### ISSUE TITLE
HaxeDevelop: Out of date HSS Rules.nml

### ISSUE THREAD

**Issue by dmcblue** [HaxeFoundation/haxe#7538]
I am getting the following compilation error: 
```
AppComponent.hss:3: Invalid 'display' value 'table-cell'
```
I checked the [current HSS rules](https://github.com/ncannasse/hss/blob/master/hss/Rules.nml) and it seems like 'table-cell' should currently be valid. I assume the Rules that HaxeDevelop has are a bit out of date.

The questions are: 

+ How can I update it?
  + Can I edit/replace a file? Or add a user specific file?
  + I don't see a way to edit rules in the UI but maybe I'm missing it (or it should be a feature)
+ Can this be updatable in the future? Like via AppMan or something?
+ Temp Solution: How can I disable the validation for HSS (in HaxeDevelop) without disabling transpilation to CSS?

**Comment by Simn** [comment]
This is the issue tracker for the Haxe programming language, so you got the wrong address.

**Comment by dmcblue** [comment]
Sorry one of the links on the HaxeDevelop site came here.  I'll let them know. Thanks
