### ISSUE TITLE
[cs] Missing sys.ssl.SslSocket impl for C#

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7543]
As titled

**Comment by Simn** [comment]
I'm leaving this open but I think somebody has to step up and address this.

**Comment by MatthijsKamstra** [comment]
and perhaps change the error message into something like "https is not implemented for this target"

https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/std/sys/Http.hx#L98

```
Unhandled Exception:
Https is only supported with -lib hxssl
```

**Comment by theJenix** [comment]
Are y'all accepting pull requests for this?  I implemented SslSocket in c# using [System.Net.Security.SslStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream) as suggested in #8841 and it seems to work well.  I'm happy to throw up a pull request for review if it would be helpful!

**Comment by Aurel300** [comment]
@theJenix PRs are generally welcome, yes!

**Comment by theJenix** [comment]
> @theJenix PRs are generally welcome, yes!

Awesome :). I have a pretty full week but I will try and package up a PR this weekend. Is there a style guide or "minimum viable PR" guide I should read, e.g. standards around code style, test coverage, logging standards, etc?

**Comment by Simn** [comment]
We're very easygoing on all that PR stuff. Generally, if it doesn't make our CI red, there's a good chance that we'll accept it.

I'll close this issue though because I don't see much of a point in keeping it open.
