### ISSUE TITLE
haxe.io.Path.normalize turns relative path into absolute one

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7548]
... if it begins with `'.//'`

```haxe
trace(haxe.io.Path.normalize('.//dir/foo.txt')); // prints: /dir/foo.txt
``` 

I expect it to remove the double slash to `./dir/foo` then resolve `./` to become `dir/foo.txt`

**Comment by Simn** [comment]
Any chance for a PR?

**Comment by kevinresol** [comment]
I would like to, but can anyone update the readme teaching me how to run the unit test suite?
Maybe here? https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md

fun fact: this actually caused me to accidentally run the equivalent of `rm -rf /` in my system, spent me a night to restore from backup.

**Comment by Simn** [comment]
Yes I can see how this can be really bad... sorry about that, I'm making this issue urgent for Haxe 4.

As for running the test suite, doing so across all targets is pretty involved and we usually rely on the CI for that. If you just want to run it for a specific target, you can navigate to `tests/unit` and do `haxe compile-macro.hxml` or any of the other targets.

But you're right, we should document this somewhere.
