### ISSUE TITLE
[js] js.Date needs an implicit cast to std.Date

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7549]
(or move these native std types into `js.global` package)

Version: 4p5

Due to https://github.com/HaxeFoundation/haxe/issues/7260, every API inside the `js` package that reference `Date` means `js.Date` now. I think this breaks a lot of code that expects the std `Date` (which is a very significant impact IMO)

```haxe
var date:Date = js.node.Fs.statSync('').atime;
```
```
js.Date should be Date
```

**Comment by Simn** [comment]
IMO we should move these types to a separate package. `js.global` sounds good to me.

Any opinions @nadako @haxiomic?

**Comment by haxiomic** [comment]
@nadako has a WIP PR to do just that: https://github.com/HaxeFoundation/haxe/pull/7390

On js.global vs js.lib, I like js.lib but either is fine I guess

**Comment by haxiomic** [comment]
@Simn I think we should bump fixing this (which requires #7390) to the 4.0 milestone – seems like it could come up a lot and if the js modules are moving around I think best to do it for 4.0 so it's not an unexpected change in 4.1.

Completing #7390 is firmly on my todo list so if no one else gets to it eventually I'll complete it.

**Comment by ncannasse** [comment]
I would close #7390 and rename both js.Map and js.Date to js.NativeMap and js.NativeDate

**Comment by RblSb** [comment]
Probably `js.Map` doesn't break too much https://github.com/search?q=language%3Ahaxe+%22package+js%22+%22new+Map%22&type=Code (`[=>]` case not included)
Maybe it's better to leave it as it is by adding `package js; typedef Map = std.Map;` in hx3compat (same for `Date`)?
Any option looks okay, but for js lib devs `import js.lib.Map` is little better than `import js.NativeMap as Map`.

**Comment by RealyUniqueName** [comment]
Moved to `js.lib.Date`
