### ISSUE TITLE
XML literal strings improvements

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/haxe#7558]
XML literal strings should support tags starting with an uppercase letter and '$' symbol  in order for it could be used in haxe-react lib.
[https://github.com/kLabz/haxe-react/issues/8 ](https://github.com/kLabz/haxe-react/issues/8)

**Comment by Simn** [comment]
It actually supports that for the opening tag, but not for the closing one.

**Comment by Simn** [comment]
Reopening this as it seems dollar symbols are not allowed in XML names. See #7764.

**Comment by Simn** [comment]
So the dollar is indeed not allowed in the XML spec, but it is allowed in the JSX spec (via the ECMA 6 identifier spec).
