### ISSUE TITLE
@:structInit extending another @:structInit ignores @:optional metadata

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#7559]
If one class extends another and both have `@:structInit` metadata, and one of the base class fields have `@:optional` metadata, this `@:optional` metadata is ignored in derived class constructor.

```haxe
@:structInit
class Base {
    @:optional var foo: Int;
}

@:structInit
class Derived extends Base {
    var bar: Int;
}
    
class Test {
    static function main() {
      var base: Base = {}; // ok, we can skip optional fields
      var derived: Derived = {foo: 200, bar: 100}; // ok, we can extend one @:structInit with another
      var derived2: Derived = {bar: 100}; // but this fails: Object requires field foo
    }
}
```
Tested with Haxe 4.0.0-preview.5+8698281

**Comment by RblSb** [comment]
Same for `public var foo = 1;` in `class Base`
Related to https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typeloadFields.ml#L122

**Comment by RblSb** [comment]
Also, `@:optional var foo:Int;` in `@:structInit` class should be `null` or `0` on static targets? At the moment it is `0` on hxcpp.

**Comment by danbrakeley** [comment]
I just hit this as well, but with 3.4.7.
