### ISSUE TITLE
Issues with @:commutative for Operator Overload

### ISSUE THREAD

**Issue by DonSkeleton** [HaxeFoundation/haxe#7566]
Following the Haxe Manual for [Operator Overloading](https://haxe.org/manual/types-abstract-operator-overloading.html) I tried to use the @:commutative tag to work like this (https://try.haxe.org/#1C6c1):

```
abstract ForcedInt(Int) from Int to Int 
{
    inline function new (i:Int) 
    {
        this = i;
    }      
    
    @:op(A / B) 
    @:commutative
    public function divide(b:Int):ForcedInt
    {
       trace("this: " + this);
       return new ForcedInt( Math.round(this / b ) );
    }
    
}

class Test 
{
    static function main() 
    {
        var foo : ForcedInt = 31;
        var bar : ForcedInt = 2;

        trace("ForcedInt / ForcedInt: " + foo / bar);       
        trace("ForcedInt / Int: " + foo / 2);
        trace("Int / ForcedInt: " + 31 / bar);
    }
}
````

I get an Error saying '@:commutative is only allowed if the right argument is not Int'.

If it's not clear what I'm trying to do, I'm basically trying to overload the '/' operator so that when I divide two Int values I want the result to be automatically rounded and cast to Int.

I also tried, after a suggestion from Robert, to change the type of the b parameter to ForcedInt but I got different results depending on the Haxe Version and none worked.
In Haxe 3.4.4 (try.haxe.org): In case of trying to 'Int / ForcedInt' the abstract function divide() is never used. I get '15.5' as output for doing 'Int (31) / ForcedInt (2)'.
In Haxe 4 - Preview 4 or 5: I get an error saying that 'this / b' is a 'Recursive Operator Method', which I'm not sure what that means.

I also tried to use a static method based on an example I saw on the web
```
static public function divide(a:ForcedInt, b:Int):ForcedInt
{
   trace("this: " + a);
   return new ForcedInt( Math.round(a / b) );
}
```
but it's still saying that 'a / b' is a 'Recursive Operator Method'.

Not sure if I'm doing something wrong or this is maybe related to what @Simn did at [Issue 5599](https://github.com/HaxeFoundation/haxe/issues/5599) or if the Haxe Manual needs an update?

**Comment by haxiomic** [comment]
This approach works

```haxe
@:op(F / I)
static public inline function divideFI(a: ForcedInt, b: Int): ForcedInt {
   return new ForcedInt(Math.round( (a:Int) / b ));
}
@:op(I / F)
static public inline function divideIF(a: Int, b: ForcedInt): ForcedInt {
   return new ForcedInt(Math.round( a / (b: Int) ));
}
```

The recursive operator method error is because the `this / b` is another `ForcedInt / Int` operation (because `this` has type `ForcedInt`). You can get around that by casting `a` to Int – `(this: Int) / b`, however in this case I think the right approach is to use static operator overloads

I don't think `@:commutative` works in this case because it's always mapping to a single type order, so if you have in code `(a: Int) / (b: ForcedInt)` and you write your overload in the order `ForcedInt / Int`, then it'll always execute `b / a`, but allow either `a` or `b` to be Int or ForcedInt. I don't know if that's a clear explanation but it's a little hard to get your head around!

It doesn't look to me like there's a haxe bug but maybe the manual needs some tweaks

(tested on haxe 3.4.4 and 4 dev branch)

**Comment by DonSkeleton** [comment]
Thanks for the help, your suggestion works fine.

This sentence from the Haxe manual
> While MyAbstract * Int works, Int * MyAbstract does not. If this should be allowed as well, the @:commutative metadata can be added.

had me thinking that it will take care of the type order so that I don't have to write out two methods, one for each type order.

Your explanation really helped with understanding it more clearly.

Will close the issue.

**Comment by azrafe7** [comment]
Mmmhh...

**Comment by azrafe7** [comment]
(commenting on a closed issue, I know. But maybe it will be helpful to others.)

I was having a hard time understanding why this didn't work, as at first glance the original post seemed to make sense. 

Then I realized that algebra-division is NOT commutative (while multiplication is), and here the same reasoning applies:

`(A / B) != (B / A)`   (while `(A * B) == (B * A)`)
