### ISSUE TITLE
Add haxe4 flag

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7570]
If we have `-D haxe3`, adding `-D haxe4` also makes sense. It should behave like  `haxe_ver >= 4`

**Comment by Simn** [comment]
I don't really like these flags because it's not clear to me if Haxe 4 should still define haxe3. If you use `haxe3` to transition your code from Haxe 2 to 3, it's stupid if your code breaks because Haxe 4 no longer defines it...

**Comment by markknol** [comment]
I think it just means "this major version and higher". So no removal of `#if haxe3`; I would suggest to use this: 

* `#if haxe3` is `haxe_ver >= 3`
* `#if haxe4` is `haxe_ver >= 4`
* `#if haxe5` is `haxe_ver >= 5`
* `#if haxe6` is `haxe_ver >= 6`

No code will break.

**Comment by back2dos** [comment]
Do we actually have `-D haxe3`? It's certainly not listed in `haxe --help-defines` for 3.4.7. 

I think `haxe_ver` is adequate and we shouldn't add any more flags unless they cover new use cases.

**Comment by markknol** [comment]
Oh okay I thought it was fairly known..

in that case lets remove `-D haxe3` in Haxe 4? 😄 What can go wrong 😋

**Comment by back2dos** [comment]
Well, there's `-D haxe3compat` but I haven't seen `-D haxe3` show up in `--help-defines` anywhere (not even 4p5).

**Comment by Gama11** [comment]
Even if it's not documented there, it's still defined:

```haxe
trace(haxe.macro.Context.getDefines());
```

```
source/Main.hx:3: {
    true => 1,
    sys => 1,
    source-header => Generated by Haxe 4.0.0-preview.5+26f9041f5,
    interp => 1,
    haxe_ver => 4.000,
    haxe3 => 1,
    eval => 1,
    dce => std
}
```

**Comment by back2dos** [comment]
My point was mostly that because it's not documented, removing it should not be an issue. A code search seems to confirm that it's not really in use: https://github.com/HaxeFoundation/haxe/search?q=haxe3&type=Code

**Comment by markknol** [comment]
9k results here https://github.com/search?q=%23if+haxe3&type=Code (not sure how relevant they all are)

**Comment by back2dos** [comment]
I really need to take a computer course ...

**Comment by ncannasse** [comment]
-D haxe4 should be added and we should keep -D haxe3 as well.
