### ISSUE TITLE
Haxe 4 preview 5 ( from Kha repo ) breaking changes.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#7572]
When I got latest Kha from git I had to rename the haxe submodule because Haxe 4.0.0 preview5 was breaking my abstracts in my cross toolkit code and go back to Haxe 3.4.7

The problems are 
**Pi2pi.hx:22: characters 24-32 : Recursive operator method**
https://github.com/nanjizal/Trilateral/blob/master/src/trilateral/angle/Pi2pi.hx#L22
**ZeroTo2pi.hx:22: characters 24-32 : Recursive operator method**
https://github.com/nanjizal/Trilateral/blob/master/src/trilateral/angle/ZeroTo2pi.hx#L22

The code is pretty similar in both cases?
```haxe 
    @:op(A > B) static function gt( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A < B) static function lt( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A == B) static function et( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A >= B) static function gte( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A <= B) static function lte( a:Pi2pi, b:Pi2pi ) : Bool;
@:op(A + B)
    public function additionPi( b: Pi2pi ): Pi2pi {
        var f: Float = this + b;  // <- line 22
        var p: Pi2pi = f;
        return f; 
}
```

The other problems I have are warnings this one was new.
**Contour.hx:380: characters 18-21 : Warning : Potential typo detected (expected similar values are end). Consider using `var end` instead**
https://github.com/nanjizal/Trilateral/blob/master/src/trilateral/geom/Contour.hx#L380
( End is just an abstract enum:
https://github.com/nanjizal/Trilateral/blob/master/src/trilateral/geom/Contour.hx#L16 )

Also still getting...
**Contour.hx:382: lines 382-384 : Warning : This case is unused**
Which I have had for sometime and don't understand.

Please let me know if I should split these into separate issues, probably I should test more of my other libraries as I use a lot of abstracts in libraries like triangulations and hxspiro.

**Comment by azrafe7** [comment]
Hey @nanjizal,
_maybe_ I've found out why you're getting those errors/warnings.

**1.** For the ones related to `@:ops`, I think you can substitute them with empty static methods (since you're "abstracting/extending" Float (without side-effects)**\***, and already have a `@:from` method). So what I'm proposing is to have for example this for `Pi2pi`:

```haxe
@forward
abstract Pi2pi( Float ) to Float {
    // private can't create directly
    inline
    function new( f: Float ){
        this = f;
    }
    @:from
    static inline public
    function fromFloat( f: Float ) {
        return new Pi2pi( Angles.pi2pi( f ) );
    }
    @:op(A > B) static function gt( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A < B) static function lt( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A == B) static function et( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A >= B) static function gte( a:Pi2pi, b:Pi2pi ) : Bool;
    @:op(A <= B) static function lte( a:Pi2pi, b:Pi2pi ) : Bool;

    // here just static empty functions
    @:op(A + B) static function additionPi( a:Pi2pi, b:Pi2pi ) : Pi2pi;
    @:op(A - B) static function subtractionPi( a:Pi2pi, b:Pi2pi ) : Pi2pi;
    @:op(A / B) static function dividePi( a:Pi2pi, b:Pi2pi ) : Pi2pi;
    @:op(A * B) static function timesPi( a:Pi2pi, b:Pi2pi ) : Pi2pi;
    //end

    public var degrees( get, set ): Float;
    public inline
    function get_degrees(): Float{
        var f: Float = this;
        return f*180/Math.PI;
    }
    public inline
    function set_degrees( val:Float ): Float {
        this = Math.PI*val/180;
        return val;
    }
    @:from
    inline static
    function fromFraction( val: Fraction ):Pi2pi {
        return new Pi2pi( val.toFloat()*Math.PI );
    }
    @:to
    inline function tofraction(): Fraction {
        var f: Float = this;
        var frac: Fraction = this/Math.PI;
        return frac;
    }
    @:from
    inline static
    function fromString( val: String ):Pi2pi {
        var frac: Fraction = val;
        return new Pi2pi( frac.toFloat()*Math.PI );
    }
}
```

Same for `Zero2pi` and `ZeroToMinus2pi`.

**\*These should be tested as maybe you intended them to work differently from what I assume!?** :smiley: 

 **2.** About `Contour` and the potential typo warning: I think that it complains because there's a function named end() that name-clashes with the `EndLineCurve.end` enum. It can be fixed by using `EndLineCurve.end` in the switch, or renaming things in a way or another.

**Comment by nanjizal** [comment]
they are in a separate repo that is setup better for experimentation no sure if it's up to date. https://github.com/nanjizal/fracs I am not sure empty static methods will cover all cases, this is something I can look into.  Also may well remove most of them from Trilateral. But still these errors are new and if they effect my code likely they can effect others, normally very little of my code is effected by Haxe changes as I don't use macros, and the errors seem to suggest bugs that may effect other code I have. Azrafe7 thanks for taking time to look.

**Comment by nanjizal** [comment]
Azrafe7 changing to empty statics does work for some situations but not this one:
```haxe
var q: Pi2pi = Math.PI/2;
var r: Float = q*3.;
trace( r + 'pi' );
```
It's important that in a calculation mixing Float and Pi2pi that the result is always properly mapped to the range irrespective of if the result required is Float or Pi2pi.

**Comment by nanjizal** [comment]
In regard to 'end' although I can try changing in the switch statement.  The problem is that it could be quite common for a abstract enum to have the same name as a method in a class and considering the abstract enum and method name could be decided by different developers it seems a real shame for Haxe to loose the abilty.
Please core developers let me know if you would like these two issues split up, there seems to be two regressions, but it's unclear if you regard them as important, certainly calling the constructor when refering to 'this' in a method within an abstract seems serious, there needs to be a way to get access to the raw data type within a method.

**Comment by nanjizal** [comment]
Have worked round the end issue, by providing full abstract enum name.
https://github.com/nanjizal/Trilateral/commit/6df4f7d7fbce354ff376754945a08412bdbb9786
Unsure how to approach Recursive Operator issue.

**Comment by haxiomic** [comment]
For tracking purposes following up gitter discussion:

- Recursive operator error is a correct error and the resolution is `(this: Float) + (b: Float);`
- `end` name clash warning is fine – I think because the type of `endLineCurve` was nullable (from the `?` in the signature, it's harder for the to determine if there's a clash or not. Best solution is to change names or use `EndLineCurve.end`
