### ISSUE TITLE
[java] @:functionCode in the standard library

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7573]
If we ever want to have a JVM target we'll have to get rid of these.

**Comment by nadako** [comment]
I think most of the `@:functionCode` usages are in "support" classes like `Runtime`, right? They will have to be replaced/reworked heavily anyway for a real JVM target...

**Comment by Simn** [comment]
I was mostly looking at `StringExt.hx` and `Type.hx`.

**Comment by waneck** [comment]
I think we could replace everything with real code now. I think only
Std.string might need special functionCode support

**Comment by Simn** [comment]
No manpower for this, might as well close.
