### ISSUE TITLE
cannot use @:const type parameter with haxe 4 preview 5

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#7574]
With 4.0.0-preview.5 this example does not compile with error: `Only Const type parameters can be used as value`. With haxe 3.4.4 it compiles fine.

```haxe
@:generic
class Foo<@:const FOO:Dynamic> {
	var foo = cast(FOO, String);

	public function new() {}

	public function test() {
		trace(foo);
	}
}

class Test {
	static function main() {
		var foo = new Foo<"Y">();
		foo.test();
	}
}
````

**Comment by Simn** [comment]
I didn't intend to break it, but now that it's broken I wonder if we should remove this feature altogether. I'm fine with macros processing constant type parameters, but supporting this in the typer as some sort of silly dependent type seems like it's not worth the complications.

Is this actually useful for anything in the real world?

**Comment by romamik** [comment]
I used this like this. I have some gui-system, and have two classes VBox and HBox, that differ only by the axis they use. This feature allowed me to make one class with type parameter. Together with analyzer-optimize this approach gives very clean output. Here is very basic example: http://try-haxe.mrcdk.com/#D725e 
Note code in `LinearBox.applyLayout()` function. It's axis-agnostic and I don't know better approach to do this. Currently I'm doing this with calling inline function defined in base class but this does not look that good.
