### ISSUE TITLE
dart support 

### ISSUE THREAD

**Issue by AttSee** [HaxeFoundation/haxe#7576]

**Comment by Simn** [comment]
no

**Comment by AttSee** [comment]
fuck

**Comment by nanjizal** [comment]
I am sure HaxeFoundation would be happy consider any quality pull requests in regard to Dart, but from a new language perspective I am sure you will understand that the Ocaml fork is an area that is much more interesting to the wider Haxe community. Irrespective of Googles marketing of Flutter with Dart, it offers nothing special over the raw capabilities that Haxe community have had for many years which can be evolved to fit use cases rather than fancy spin.

**Comment by martin-braun** [comment]
@Simn Have you ever thought about a concept of "lite-targets" that allow to program non-target-specific libraries in haxe for much more targets?

Haxe has many use-cases which I really appreciate. One of its champion-alike attributes is its high portability, so it's also a valid candidate to build libraries that feature only non-platform-specific logic (i.e. complex math logic, cryptography, data-driven logic, etc.). So in general you build a library in haxe that features useful base logic and you can add it to any target language project, thus using haxe only as library and not as project language. 

For this case only a lite-target approach would be necessary, i.e. only having the language transpilation as well as the standard library support. In the case of dart, no Flutter specific elements as well as UI classes would require support. It would just need to support the default stuff.

The reason I bring this up is in my work I often program in many different projects that use different technologies. I'm out of choice regarding the selected technology, but I have to extend the products nonetheless. I had written the same helper logic in many languages and I seek the best library language to target them all. Haxe is a great candidate, base support of dart is what I miss, though.

**Comment by nanjizal** [comment]
This article discusses mixing C++ with flutter, I presume you could do this with haxe.
https://levelup.gitconnected.com/port-an-existing-c-c-app-to-flutter-with-dart-ffi-8dc401a69fd7

I notice a Rust library that reads serialized haxe, I have no idea if this is complete or works well.
https://gitlab.com/eternaltwin/tools/haxeformat

@martin-braun Could you make a haxeformat version for Dart that could serialize and unserialize ?
https://haxe.org/manual/std-serialization.html
then you could maybe embed a hashlink player in Flutter and pass serialized commands back and forth.  ( also see hxBit and varients ).
