### ISSUE TITLE
increamental building

### ISSUE THREAD

**Issue by ck7colin** [HaxeFoundation/haxe#7578]
the haxe will typecheck the haxe file and build the ast to get class info everytime even if I don't change anything. should we make the haxe building into increatmental building which just update and build the outdate file and refernce file.So that we can save huge time in building the 100k lines projects.

**Comment by Simn** [comment]
See https://haxe.org/manual/cr-completion-server.html

**Comment by ck7colin** [comment]
it seems that there's nothing help for me as we build the codes in several parts which as libs. in the site you recommended, the advantage of cr-completion-server  is only available in building one project. however we build several lib projects which will dependence on other lib. eg. lib A dependence on lib B , when I build the lib B's haxe file, it will typecheck and get class info of lib A's external haxe files.Is there any way to get the completion info of lib A which is generated while building the lib A project. @Simn

**Comment by back2dos** [comment]
It depends quite a bit on the target. But if you precompile a library with `--gen-hx-classes` then you will get externs for it, that you can use for completion.

**Comment by ck7colin** [comment]
yeah, we have precompiled a library with  `--gen-hx-classes`  before. But it will parse the externs each time while building  each top level lib, so that it will take lot of time in building the whole project of exe from the beginning. as a result of this, we try our best to promoted the speed of compilation in some way such as get the info of last time compilation of lib B project and use it in latest compilation of lib A project which depends on lib B. @back2dos

**Comment by back2dos** [comment]
Frankly, I can't imagine parsing (let alone parsing of externs) to ever be a bottleneck. Can you compile with `--times` and show the numbers you get?

**Comment by ncannasse** [comment]
@ck7colin Compilation server will not help for first-compilation-of-they-day but will give you a very good cache for all other compilations. I think that's a good answer to what you asked for?
