### ISSUE TITLE
Neko-specific type parameters error

### ISSUE THREAD

**Issue by tbrosman** [HaxeFoundation/haxe#7579]
Haxe version: 4.0.0-preview.5+7eb789f54

I am getting an error resolving type parameters when compiling to neko:

```
src/Main.hx:14: characters 9-21 : (key : Int, value : B.T) -> Void should be (Int, A.T) -> Void
src/Main.hx:14: characters 9-21 : Cannot unify argument 2
src/Main.hx:14: characters 9-21 : A.T should be B.T
```

A minimal-ish repro:

```haxe
package ;

class A<T>
{
    private var value:T;

    public function new()
    {
    }

    public function toB():B<T>
    {
        var b:B<T> = new B<T>();
        b.set(value);
        return b;
    }
}

class B<T>
{
    private var hash:Map<Int, T>;

    public function new() 
    {
        this.hash = new Map<Int, T>();
    }

    public inline function set(item:T):Void
    {
        hash.set(0, item);
    }
}

class Main
{
    public static function main():Void
    {
        var b = new B<Int>();
    }
}
```

This works fine for HashLink and cpp builds. Note that `Map` does need to be present to reproduce this issue. When `B` is as follows, the code compiles:

```haxe
class B<T>
{
    private var value:T;

    public function new() 
    {
    }

    public inline function set(item:T):Void
    {
        value = item;
    }
}
```

**Comment by romamik** [comment]
This also does not compile to javascript...

**Comment by Simn** [comment]
Trying to find a pattern here...

## Works:

* HL
* python
* cpp
* Java
* C#
* eval

## Fails:

* JS
* neko
* flash
* PHP
* lua

The failing targets have in common that their `IntMap.set` function is `inline`, so this is about the special multitype-abstract-inline case.

Unfortunately, this is a regression.
