### ISSUE TITLE
Assertion failed in evalJit.ml

### ISSUE THREAD

**Issue by polygonal** [HaxeFoundation/haxe#7580]
using Haxe Compiler 4.0.0-preview.5+7eb789f54

File Main.hx:
```haxe
@:build(Test.build())
class Main {
	static function main() {}
}
```
File Test.hx:
```haxe
class Test {
	macro public static function build():Array<haxe.macro.Expr.Field> {
		var val:Dynamic = "";
		val =
		switch (val) {
			case 1 | "1" | "true": true;
			case _: val;
		}
		return null;
	}
}
```
Usage:
```
haxe -main Main -js main.js
```

fails with:

>File "_build/src/macro/eval/evalJit.ml", line 242, characters 11-17: Assertion failed

**Comment by Simn** [comment]
Uh... something must go wrong during typing because this enters the `| TSwitch(e1,cases,def) when is_int e1.etype ->` case in evalJit, which it obviously shouldn't because the subject type is not `Int`.
