### ISSUE TITLE
[eval] Sys.args returning build arguments in 4.0.0-preview.5

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#7582]
Hello, since the 4.0.0-preview.5 release `Sys.args()` returns the build arguments as well as any user arguments when targeting eval.

```
package;

class Test
{
    static function main()
    {
        trace(Sys.args());
    }
}
```
When running `haxe -main Test --interp` with the above file `Test.hx:7: [-main,Test,--interp]` is printed to the console. When actually providing program arguments with `haxe -main Test --interp -- myArg myOtherArg`, `Test.hx:7: [-main,Test,--interp,--,myArg,myOtherArg,myArg,myOtherArg]` is printed to the console.

This also occurs when using a build file.

```
-main Test
--interp
```

When using the above build file `Test.hx:7: [-main,Test,--interp]` is output.

Running all of the above on preview.4 you get either no arguments or the two custom arguments as expected. I'm running Ubuntu 18.04 but will test Mac and Windows some time tomorrow.

**Comment by RealyUniqueName** [comment]
It was a regression in preview.4: https://github.com/HaxeFoundation/haxe/issues/7185
