### ISSUE TITLE
[eval] Runtime arguments are added twice to `Sys.args`

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#7584]
When using `Sys.args` on the eval target, the runtime arguments (after the `--`) are reflected twice in the command output:

```
 - Running command: haxe -cp C:\Users\Joshua\AppData\Local\Temp/temp_5826 -cp D:\Development\Haxe\openfl Script Script -main hxp.Script -D hxp=0.0.0 -cp D:/Development/Haxe/hxp/src -D hxp-interp --interp -- default -verbose Script D:\Development\Haxe\openfl/
hxp/Script.hx:55: [-cp,C:\Users\Joshua\AppData\Local\Temp/temp_5826,-cp,D:\Development\Haxe\openfl,Script,Script,-main,hxp.Script,-D,hxp=0.0.0,-cp,D:/Development/Haxe/hxp/src,-D,hxp-interp,--interp,--,default,-verbose,Script,D:\Development\Haxe\openfl/,default,-verbose,Script,D:\Development\Haxe\openfl/]
```

Is this a bug, or is there some way for us to get the passed runtime arguments separately from the build arguments, in a clean fashion?

Thank you :smile:

Related to issue: https://github.com/HaxeFoundation/haxe/issues/7582

**Comment by Gama11** [comment]
Considering that `--` was newly added in Haxe 4, this should probably be fixed before the final release?

I general, I would expect that _only_ the arguments after `--` show up in `Sys.args()`, so that the behavior is consistent with `haxe --run` (so no `-cp`, `--interp` etc...).

**Comment by Simn** [comment]
To be honest I didn't really notice that we added `--` in the first place. I'm inclined to just remove it because it seems redundant.

**Comment by Gama11** [comment]
Yeah, it doesn't seem strictly necessary considering you can do the same with `--run`. I think the motivation was mostly that `--` is a flag that a lot of tools support.

Agree it's better to remove it than to release it in a broken state.
