### ISSUE TITLE
[lua] json (and maybe other things?) does not respect -D lua-vanilla

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#7589]
using the vanilla lua flag and json still results in generating requires for lua-utf8, which I do not have available.

I actually do have a utf8 library: the one love2d ships (require name "utf8", compatible with lua 5.3's built in), but I'd really like if it actually spit out vanilla lua code as preview 4 did.

**Comment by jdonaldson** [comment]
Yeah, this is a fairly common occurrence with certain libraries and frameworks.  It can be a bit risky patching in another library and expecting it to work exactly the same, but I suppose in some cases this is the only option.

**Comment by nadako** [comment]
As a temporary workaround I think it should be possible to replace the offending type from std with a fixed version in your class path!

**Comment by nadako** [comment]
Should be fine now, leaving this open so we don't forget to add test for `-D lua-vanilla` (should run on travis similar to how we test different flags for js, but with unicode tests excluded i guess).

**Comment by shakesoda** [comment]
@nadako thanks! latest nightly works, and workaround in my classpath works for rc1 too. now I, too, can get with the times 👍

**Comment by jdonaldson** [comment]
json should support vanilla now in the development branch.

**Comment by Gama11** [comment]
I thought nadako kept this open to remember adding a test?

**Comment by jdonaldson** [comment]
Oh, didn't realize that.  @nadako feel free to reopen this if it's helpful.
