### ISSUE TITLE
[eval] String.indexOf with invalid index aborts with `Invalid_argument("index out of bounds")`

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#7601]
Both lines throw an  `Invalid_argument("index out of bounds")` error, with no further info when running on eval target:
```haxe
class Test {
	static function main() {
		trace("Haxe is great!".indexOf(" ", -1));
		trace("Haxe is great!".indexOf(" ", 100));
	}
}
```

**Comment by Simn** [comment]
That means we don't specify the negative value case at the moment...

**Comment by Simn** [comment]
Added test fails on PHP.

**Comment by Simn** [comment]
... and on lua:

```
src/unitstd/String.unit.hx:71: 5 should be 6
src/unitstd/String.unit.hx:72: -1 should be 6
```

**Comment by Simn** [comment]
@RealyUniqueName and @jdonaldson: Could you look into this? The branch is https://github.com/HaxeFoundation/haxe/compare/issue_7601/

**Comment by Simn** [comment]
bump

**Comment by RealyUniqueName** [comment]
I'll do it, I just don't know when )

**Comment by ncannasse** [comment]
@Simn could you merge your eval changes ? we don't really need to block RC with the fix

**Comment by Simn** [comment]
I have pushed the fixes without the tests.

**Comment by Simn** [comment]
Superseded by #8365.
