### ISSUE TITLE
Obscure error message for an unexpected keyword.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7602]
```haxe
class Test {
  var operator:Int;
}
```
Error:
```
Test.hx:2: characters 7-15 : Unexpected operator
```
It took me a few moments to grasp the error message for this line: https://github.com/mikestead/hamcrest-haxe/blob/master/src/org/hamcrest/core/ShortcutCombination.hx#L15
It's not immediately clear what's so "unexpected" in this code. Especially for users, which are not familiar with the recent changes.
Maybe a better message would be:
```
Test.hx:2: characters 7-15 : Unexpected keyword "operator"
```

**Comment by khalyomede** [comment]
I could reproduce the issue with [try.haxe.org/#787E344b](https://try.haxe.org/#787E344b):

```haxe
enum WhereStarter {
  Where;
  And;
  Or;
}

enum SqlOperator {
  Equal;
  Like;
}

typedef WhereClause = {
  starter: WhereStarter,
  column: String,
  operator: SqlOperator, // <--- "characters 3-11 : Unexpected operator"
};
  
class Test {
  static function main() {
    final whereClause = {
      starter: Where,
      column: "name",
      operator: Like,
    };
  }
}
```

**Comment by kLabz** [comment]
Should we just use 
```ocaml
| Unexpected t -> "Unexpected \""^(s_token t)^"\""
```

Here? https://github.com/HaxeFoundation/haxe/blob/fe5adc1dfa195f9264259c5b42b94b27762d5e42/src/syntax/parser.ml#L70

It's not mentioning "keyword" but at least it should cover most cases at once and sounds better than current situation.
