### ISSUE TITLE
neko md5.make return wrong value

### ISSUE THREAD

**Issue by dzw** [HaxeFoundation/haxe#7610]
public function md55test() {
		var bitmapData = new BitmapData(64, 64, true, 0);

		var png_output_name = "E:\\wangwei\\tptest\\idle\\S\\00000_0_0.png";
		trace("write:" + png_output_name);

		var png_bytes:ByteArray = bitmapData.encode(bitmapData.rect, new PNGEncoderOptions());
		File.saveBytes(png_output_name, png_bytes);

		var md5sum_from_png = Md5.make(png_bytes).toHex();
		trace("md5sum from png endoce:" + md5sum_from_png); // wrong

		var file_bytes = File.getBytes(png_output_name);
		var md5sum_from_file = Md5.make(file_bytes).toHex();
		trace("md5sum from file:" + md5sum_from_file); // correct
	}

md5sum_from_png and md5sum_from_file are different

SpriteSplit.hx:52: md5sum from png endoce:521212c2640c450cd9af0fb0de27b0eb
SpriteSplit.hx:58: md5sum from file:28b45dc5da12aa945b75407a7142680f

cpp is ok
neko is wrong
i don't known where to report

**Comment by dzw** [comment]
openfl.display.BitmapData

**Comment by ncannasse** [comment]
Are you sure you have the same exact png_bytes ? (just in case)

**Comment by dzw** [comment]
just run the test code i have updated

**Comment by dzw** [comment]
neko target

**Comment by ncannasse** [comment]
Given that the MD5 gives a good result with file bytes, it does not seem to be a problem with Neko.
Seems instead like a bug with OpenFL, please report it here https://github.com/openfl/openfl/issues

**Comment by nanjizal** [comment]
dzw, I normally find https://github.com/azrafe7/hxPixels an easy way to work with pixels it abstracts over frameworks like openfl, java, canvas etc... ( my mandelbrot example shows kha use ) and helps with issues like ARGB etc... so to save image as png in openfl, I don't remember any specific issues targetting neko.
var pixels: hxPixels.Pixels = bitmapData;
then you can save it ie:
https://github.com/hxDaedalus/hxDaedalus-simpledrawing/blob/master/src/TestGraphics.hx#L82
I can't comment on MD5.
