### ISSUE TITLE
Serializer JS/PHP7

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7612]
Hej,

I just found a difference between serializer on JS and PHP7. I have not tested on others target, sorry.
When I serialize "d' Estrec" it gives :
-y11:d'%20Estrec on JS
-y13:d%27%20Estrec on PHP7

The ' is not escaped on JS, is it normal ?

(Damn, issue number 666 !!! :D )

**Comment by ncannasse** [comment]
Both are allowed for me, unless you have some idea @RealyUniqueName ?

**Comment by filt3rek** [comment]
Thanks for your answer Nicolas.
In fact, I sometime use the Serializer to pass objects from HTML to JS and the ' is annoying when written inside something like onclick="myFunc( 'mySerializedStringWithApostrophe' );".
I don't know if it's clear and how it can be improved. Maybe just have the same serialized string on every target would be good ?
Thanks for your attention,
Regards,

**Comment by back2dos** [comment]
The Haxe serialization format uses percent encoding, which is aimed at URLs and HTTP, while what you want is html escaping, which is provided by `StringTools.htmlEscape`.

**Comment by filt3rek** [comment]
Hej Juraj,
The percent encoding is good for my needs and I think it would be just good to have strictly the same serialization string on all targets.

**Comment by RealyUniqueName** [comment]
Haxe serialization spec does not guarantee to produce the same string on all targets. It guarantees that you can deserialize on another target and get a value you serialized.
And it works. PHP serialization result deserialized on JS: : https://try.haxe.org/#8E54E

**Comment by RealyUniqueName** [comment]
As for the single quote produced by JS serializer, it's also not specified to be url-encoded. 
So, either Haxe should specify the encoding of single quotes or a developer should escape a serialized string if needed.
@ncannasse ?

**Comment by ncannasse** [comment]
I don't think we can ensure the same serialization on all targets, they will be other drawbacks such as field/map ordering etc.

I agree that it's not ideal to leave special chars such as single quotes in encoded urls if other platforms correctly escape it, for security reasons when switching platforms, but after checking JS does not escape quotes either so I guess we should leave it this way.
