### ISSUE TITLE
VSCode cut error messages

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7615]
See original reported issue here: https://github.com/Microsoft/vscode/issues/62914

In case the issue can be fixed in VSCode, the question is that if we could fix it in Haxe instead, by appending a space at the beginning of each line after we have print the maximum terminal width:

```
File.hx:55: (long error message ......)
 continued with a space
```

This would require detecting terminal width using https://gist.github.com/jtriley/1108174

**Comment by Simn** [comment]
I don't think we should do something like this...

**Comment by Simn** [comment]
I discussed this with myself and still don't think we should do something like this.
