### ISSUE TITLE
Unhelpful error: Custom property accessor is no longer supported, please use set

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#7616]
## Unhelpful / ambiguous error message: 
**_"Custom property accessor is no longer supported, please use set"_**
Moving from **Haxe3** to **Haxe4** this error is provided breaking old code.
```
var foo( default, set_foo ): Foo;
```
Strictly speaking set_foo method itself is not a custom property accessor, and the error is breaking libraries that don't need to be broken? 

I understand semantically the error message may seem to be technically correct, only from a compiler developers viewpoint, english can be vague in it's intepretation.  This sentence can be also read to mean the method signature is incorrect and the user is left checking aspecs of the _set_foo_ method and not realizing the error is that you can no longer use 'set_foo' and have to write 'set', while removing custom accessors is probably a good idea enforcing the change from 'set' to 'set_foo' is patantic?

My request is that Either
- allow _set_foo_ as a special case to reduce broken code, does it really need to be changed by the user, they are not using a custom method just old notation.

- modify the error message for this specific case to be more explicit, perhaps:
FooHolder.hx:100: characters 5-52 : Foo: Custom property accessor is no longer supported, please swap 'set_foo' for 'set'

**Comment by Simn** [comment]
I think the only real problem here is that the position is not accurate. If it points to the `set_foo` it should be much more obvious.

I'm still fine with breaking this because `get` and `set` work in both Haxe 3 and 4.

**Comment by nanjizal** [comment]
the characters are not from the actual error message - I had the error in different code it was just to provide suggested error change.
