### ISSUE TITLE
C# cast regression

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7617]
https://github.com/HaxeFoundation/haxe/commit/c0ced01d76c1b8b1fcd8bb54e10aa0275a9f981a caused the C# tests to fail:

```
src/unit/Test.hx:276: ABORTED : System.InvalidCastException: Specified cast is not valid.
   at unit.TestCSharp.testEnumFlags() in c:\GitHub\haxe\tests\unit\src\unit\TestCSharp.hx:line 333
   at unit.TestCSharp.__hx_invokeField(String field, Int32 hash, Object[] dynargs) in c:\GitHub\haxe\tests\unit\src\unit\TestCSharp.hx:line 23
   at haxe.lang.Runtime.callField(Object obj, String field, Int32 fieldHash, Object[] args) in c:\GitHub\haxe\std\cs\internal\Runtime.hx:line 642
   at haxe.lang.Closure.__hx_invokeDynamic(Object[] dynArgs) in c:\GitHub\haxe\std\cs\internal\Function.hx:line 78
   at Reflect.callMethod(Object o, Object func, Array args) in c:\GitHub\haxe\std\cs\_std\Reflect.hx:line 87
   at unit.TestMain.main() in c:\GitHub\haxe\tests\unit\src\unit\TestMain.hx:line 141 in unit.TestCSharp.testEnumFlags
src/unit/Test.hx:279: STACK :

Called from unit.TestCSharp.testEnumFlags (c:\GitHub\haxe\tests\unit\src\unit\TestCSharp.hx line 333)
Called from unit.TestCSharp.__hx_invokeField (c:\GitHub\haxe\tests\unit\src\unit\TestCSharp.hx line 23)
```

**Comment by Simn** [comment]
I have no idea what to do with this, to the point where I consider to just comment out the test.

**Comment by Simn** [comment]
I'm ignoring C# regarding the https://github.com/HaxeFoundation/haxe/commit/c0ced01d76c1b8b1fcd8bb54e10aa0275a9f981a change for now. This is "okay" because #7579 isn't failing on C#, but ultimately some unknown entity should try to figure out what the actual problem here is...

**Comment by Simn** [comment]
Never mind, #6833 reproduces the original issue...

**Comment by Simn** [comment]
@waneck: I'm gonna need some help on this one. The first problem here is that I don't really understand TestCSharp.hx:

```
var flags = new Flags(TFBA) | TFBC;
t(flags.has(TFBA));
```

Where does all this stuff come from?

The dump diff tells me that there are 3 new casts inserted after my change:

![merge_2018-11-21_09-34-34](https://user-images.githubusercontent.com/634365/48828722-c4e0ff80-ed70-11e8-8669-3fa3c0af9735.png)

Any pointers to where these come from and why they cause run-time errors?

**Comment by nadako** [comment]
The interesting thing is that a cast to `TEnumWithFlag` is suddenly inserted there, while the value is actually is of `TEnumWithBigFlag` type. If you disable the analyzer you'll get a warning (from gencommon i think): `Type haxe.test.TEnumWithBigFlag is being cast to the unrelated type haxe.test.TEnumWithFlag`

Here's a smaller code (requires `-net-lib native_cs.dll` to reproduce the runtime error, as haxe cannot generate C# enums with different underlying types, but even with normal haxe enum the invalid cast will be generated, just without the run-time error)

```haxe
import cs.Flags;
import haxe.test.TEnumWithFlag;
import haxe.test.TEnumWithBigFlag;

// @:nativeGen enum TEnumWithFlag {
// 	TFA;
// }
// @:nativeGen enum TEnumWithBigFlag {
// 	TFBA;
// }

class Main {
	static function main() {
		var flags = new Flags(TFA);
		use(flags.has(TFA));

		var flags2 = new Flags(TFBA);
		use(flags2.has(TFBA));
	}

	@:pure(false) static function use(v) {}
}
```

```cs
global::haxe.test.TEnumWithFlag this4 = ((global::haxe.test.TEnumWithFlag) (((object) (global::haxe.test.TEnumWithBigFlag.TFBA) )) );
```

**Comment by Simn** [comment]
Thank you so much for looking into this! Of the remaining 4.0 issues this one worries me the most.

**Comment by nadako** [comment]
It seems not to be C#-specific after all. Try compiling this to whatever target without optimize on:

```haxe
enum E1 { A; }
enum E2 { B; }

abstract Flags<T>(T) {
	extern inline public function new(initial:T) {
		this = initial;
	}

	extern inline public function has(flag:T) {
		return new Flags(flag).underlying();
	}

	extern inline function underlying():T
		return this;
}


class Main {
	static function main() {
		new Flags(A).has(A);
		new Flags(B).has(B);
	}
}
```

Getting this AST for the second `main` expression:
```
[Block:E2]
	[Var this5(378):E2]
		[Field:E2]
			[TypeExpr E2:Enum<E2>]
			[FEnum:E2]
				E2
				B
	[Var this6(381):E2] [Cast:Flags<E2>] [Local this5(378):E2:E2]
	[Block:E2]
		[Var this7(383):E1]
			[Field:E2]
				[TypeExpr E2:Enum<E2>]
				[FEnum:E2]
					E2
					B
		[Var this8(384):E2] [Cast:Flags<E2>] [Local this7(383):E1:E2]
```

Note how `this7` is typed as `E1` for some reason. And this only happens if the expression above it (with `E1`) is there, which suggests some monomorph binding issue?

**Comment by nadako** [comment]
Stripped down the example bit further:

```haxe
enum E1 { A; }
enum E2 { B; }

abstract Flags<T>(T) {
	inline public function new(v:T)
		this = v;

	inline public function f():Void
		new Flags(this).g();

	inline function g():Void {}
}

class Main {
	static function main() {
		var a = A, b = B;

		new Flags(a).f();
		new Flags(b).f();
	}
}
```

still getting E1 instead of E2 in the second `f` call:
```
[Block:Void]
	[Var this4(378):E2] [Local b(365):E2:E2]
	[Var this5(382):E1] [Cast:E1] [Cast:E1] [Cast:Flags<E2>] [Local this4(378):E2:E2]
	[Var this6(383):E2] [Cast:Flags<E2>] [Local this5(382):E1:E2]
```
