### ISSUE TITLE
js.Promise .catchError() issue

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#7618]
Hi!
This code:
```
			// ...
			function(res : js.html.Response) {
				if (res.ok) {
					res.json()
					   .then(onSuccess)
					   .catchError(parseErrorStr.bind('PosApiPostResp',_));
			// ...
```
generates this with haxe 3.4.4
```
function(res) {
		if(res.ok) {
			res.json().then(onSuccess)["catch"](function(a2) {
				return parseErrorStr("PosApiPostResp",a2);
			});
```
I haven't seen any closed issue regarding this...

**Comment by ncannasse** [comment]
Does it still happens with haxe 4-0-preview 5 ?

**Comment by zabojad** [comment]
@ncannasse not tested yet. I'll update the ticket if I find some time to do so.

**Comment by nadako** [comment]
What is the issue here exactly? The code looks fine to me.

**Comment by zabojad** [comment]
@nadako it works indeed but the `["catch"]()` looks a little bit ugly doesn't it? It could translate rather to `.catch()`...

**Comment by nadako** [comment]
Probably, I wonder if all the engines we support can parse keyword-fields, but I would assume so, given that `Promise` with it's `catch` is the part of the JS standard library nowadays.

Anyway that makes it a minor JS generator issue, I can look into it later!

**Comment by nadako** [comment]
I created a separate issue about that with a more appropriate title: #7645
