### ISSUE TITLE
Error on compiling with hashlink

### ISSUE THREAD

**Issue by flamendless** [HaxeFoundation/haxe#7622]
Hi, im running this command `haxe -cp src -lib heaps -lib hlsdl -hl hello.hl -main Main -debug` but it gives this error `File "_build/src/context/common.ml", line 410, characters 21-27: Assertion failed`.

Using `haxe 4.0 preview 5`, got from `binary`

**Comment by ncannasse** [comment]
Run with  `haxe -v ...` and check what gets printed in first lines (class path including std library). Most likely you are using haxe 4.0 compiler with a 3.4 standard library.

**Comment by flamendless** [comment]
Yes I get haxe 4.0 and std 3.
Whats the problem?

**Comment by haxiomic** [comment]
The std library has been written to work with the version of haxe it’s bundled with - you need std 4 and haxe 4 for it to work correctly

**Comment by flamendless** [comment]
std is a folder, where do i put that in my system?

**Comment by flamendless** [comment]
Okay, I've managed to compile a simple heaps project with haxe 4.0 and run it with hashlink, but a window opens and then closes immediately, no output in my terminal whatsover.
