### ISSUE TITLE
"operator" is now a keyword, what should we do if it is used in externed code?

### ISSUE THREAD

**Issue by Dimous** [HaxeFoundation/haxe#7625]
Hello!
For example: https://github.com/firefalcom/haxe-babylon/blob/master/src/BABYLON.hx#L796

**Comment by posxposy** [comment]
I think the simplest solution is to use native meta. For example:
```haxe
@:native('operator') public var _operator : Float;
```

**Comment by Dimous** [comment]
@dmitryhryppa got it, thank you!
