### ISSUE TITLE
[display] EnumValue.match() is missing from completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7627]
With current dev builds, `.match()` is not shown in completion anymore (also no info when hovering over it etc):

![](https://i.imgur.com/HGhV6U4.png)

Works fine with both preview 4 and 3.4.7:

![](https://i.imgur.com/z70s4Ay.png)

There's a good chance this was caused by #7416.
____

```haxe
import haxe.ds.Option;

class Main {
	public static function main() {
		var option = Some(1);
		option.match(None);
		option.
	}
}
```

**Comment by Simn** [comment]
I'm not quite sure how to approach this. It worked nicely while `match` lived on EnumValueTools, but now that it's on EnumValue the compiler just won't pick it up. We could treat it as a special case, but it would still be nice to pull the actual documentation.

**Comment by Simn** [comment]
I wasn't sure what the origin of this field should be. It's technically a built-in, but it also exists on `EnumValue`, so I don't know what we want to expose to the user here.
