### ISSUE TITLE
JsonParser.parse() errors when BOM is present.

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#7629]
In response to discussion in #6930, here's a separate issue for the modifications to JsonParser. To allow parsing JSON directly from UTF-8 encoded files, JsonParser.parse() should be modified to detect a potential BOM at the start of the given string, and ignore it if present.

**Comment by NQNStudios** [comment]
I just want to clarify before I get started, since I haven't contributed before:

The [implementation details](https://haxe.org/manual/std-Json-implementation-details.html) page says:
> The haxe.Json API automatically uses native implementation on targets where it is available, i.e. JavaScript, Flash and PHP and provides its own implementation for other targets.

I initially took this to mean that Haxe provided alternate native implementations of the API in some languages (i.e. an implementation in C++ where Haxe's compiled C++ version would be slower). I was totally wrong about that, right? It actually just means that for JavaScript, it'll call `JSON.parse`, etc.

So my PR should only really have to touch `std/haxe/format/JsonParser.hx`, and I can put the unit test in `tests/unit/src/unit/TestJson.hx`, also only implemented once, in Haxe?

**Comment by NQNStudios** [comment]
I'm also wondering if I should implement for any other byte-order-marks other than UTF-8. [List here](https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding)

**Comment by ncannasse** [comment]
@NQNStudios yes, you only need to touch JsonParser, we will see in the PR if some other native JSON parsers are concerned with the issue. You only need UTF8 BOM, as the parser doesn't support other encodings for now.

**Comment by ncannasse** [comment]
Closing, focusing discussion on original #6930
