### ISSUE TITLE
[js] Broken js output for "if-else" expression used as String.fromCharCode argument

### ISSUE THREAD

**Issue by pecheny** [HaxeFoundation/haxe#7630]
Code example:
```
class Test {
  static function main() {
    var flag = Math.random() > 0.5;
    var code = String.fromCharCode(if (flag) 43 else 53);
    trace(code);
  }
}
```
produces following js:
```
console.log("root/program/Test.hx:5:",String.fromCodePoint(if(flag) {
		43;
	} else {
		53;
	})); //  SyntaxError: expected expression, got keyword 'if'
```
Seems the bug had been introduced with adding body for  String.fromCharCode() in std\js\_std\String extern. 
However, incorrect "if-else" expression inlining when it passed as direct argument of calls ```js.Syntax.code()```/```__js__()```/```__feature__()``` seems to be existent for a while

**Comment by nadako** [comment]
I guess that's coming from the inlined `untyped`, which is quite bad, probably introduced in 885a35b06f044e27b06d39019d7eebe1ba0abaa9

**Comment by pecheny** [comment]
Had checked, prev version of the function:
```return js.Syntax.code("String.fromCodePoint({0})",code); ```
gives the same broken result.

**Comment by haxiomic** [comment]
This seems to be an analyzer issue, it can be reproduced without `fromCharCode`:
http://try-haxe.mrcdk.com/#10323

The code compiles correctly with any of the following:
- analyzer optimize is disabled
- inline is removed
- js.Syntax.code is not used
