### ISSUE TITLE
[Java] Haxe 4 preview 5, IllegalArgumentException on Android

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#7632]
Hi there. 

I got crash and exception  `java.lang.IllegalArgumentException: Unsupported flags: 256` on that line on Android, when Http class is used to make http request:
https://github.com/HaxeFoundation/haxe/blob/776c4f2e3d1b3f948f26337531ca35703dea0348/std/java/_std/EReg.hx#L49

It is happens, because:
`Field requires API level 24 (current min is 16): java.util.regex.Pattern#UNICODE_CHARACTER_CLAS`
So, it is supported only by Android 7.0+, which is means that it will not work on 50% of all devices.

Here is what documentation says:
`This flag has no effect on Android, unicode character classes are always used.`
https://developer.android.com/reference/java/util/regex/Pattern

I'm not sure what solution should be here, but maybe this line can be just wrapped by `android` define?

Thanks :)

**Comment by Simn** [comment]
That's annoying. I guess we really need a define here.
