### ISSUE TITLE
[php7] Serialize a SPOD relation fails

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7635]
Hej,

I don't really know if it's haxe/php7 related or records-macro but I get an error when I want to Serialize a relation on a SPOD object :
Uncaught ErrorException: Undefined property: user\User::$rights in /lib/Reflect.php:96
"rights" is a "relation" to UserRights class.
In the error output, I see Reflect.field is used, maybe it should do a Reflect.getProperty ?
But when I force Reflect.getProperty in the Manager instead of a Reflect.field, I get Memory Overflow.

Any ideas please ?

**Comment by filt3rek** [comment]
Oh, it's my fault, the object was not initialized yet by SPOD when I wanted to serialize it.
Is there a way to avoid that behaviour please ? I had the same issues on PHP 5...

**Comment by RealyUniqueName** [comment]
Which behavior do you want to avoid exactly?

**Comment by filt3rek** [comment]
Hej Alexander,

Thanks for your reply.
Yes, I haven't explained well.
In my DB I have a session table and a userID relation to the user table. In Haxe I have a session and a user relation.
When I first get the session from the DB and I want just after that Serialize it, it fails with the error.
To avoid that, I have to explicitly get the right user from DB, User.manager.get( 2 ) even if I do nothing with that then It works fine, no errors.

Is it more clear please ?

**Comment by filt3rek** [comment]
Note that I do that before all :

Manager.initialize();
Manager.cleanup();

**Comment by RealyUniqueName** [comment]
It sounds like a SPOD responsibility, not the compiler.

**Comment by filt3rek** [comment]
Thanks Alexander.
Yes and maybe my fault again since I've forgotten "lock" in my relation.
