### ISSUE TITLE
[macro] Incorrect error positions for build macros

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7636]
```haxe
#if !macro
@:build(Main.build())
class Main {
	static function main() {}
}
#else
class Main {
	public static function build() {
		var arr:Array<Int> = null;
		for(i in arr) trace(i);
		return null;
	}
}
#end
```

In haxe 3, the error correctly points to the `for` loop.
But in haxe 4 it is pointing at the `@:build` meta.

**Comment by kevinresol** [comment]
This is a regression, can we have it in haxe 4 release?

**Comment by Simn** [comment]
I don't really understand what's wrong here because the errors look like I expect them to:

```
source/Main.hx:10: characters 13-16 : Uncaught exception Null Access
source/Main.hx:2: characters 1-8 : Called from here
```

**Comment by kevinresol** [comment]
Aha, I just tested with haxe4rc1 and it reports this:

```
src/Main.hx:2: characters 1-8 : Uncaught exception Unexpected value VNull(null), expected Array
```

But with 4f3881b it is working as you described. 

Ready to close. Thanks!

**Comment by Simn** [comment]
Right, I probably fixed this during my recent eval-debugger adventures.
