### ISSUE TITLE
unexpected value VFloat when (unsafe) casting from Int to Float in macro

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#7647]
This code **(executed at compile time in a build macro)** broke after updating to Haxe 4 preview 5 (it worked on preview 4):

```haxe
var name = 'some name';
var baseAtIndex = 3;
var dotIndex = 2;
var baseName = name.substr(0, cast Math.min(baseAtIndex, dotIndex));
```

Haxe prints an error like this:

```
Uncaught exception Unexpected value VFloat(6), expected int
```

Replacing cast with Std.int() as a workaround "fixes" it, but still reporting as I believe cast should also work in that case.

**Comment by kevinresol** [comment]
I don't think it should work. For example, what should happen with this code?

```haxe
var baseName = name.substr(0, cast 6.5);
```

**Comment by jeremyfa** [comment]
I would expect it behave the same as:

```haxe
var baseName = name.substr(0, Std.int(6.5));
```

That actually seemed to work like this until haxe 4 preview 4

**Comment by Simn** [comment]
I don't think that's how casts generally behave, at least not on non-static targets.

**Comment by haxiomic** [comment]
It would be nice if `Math.min()` could return `Int` for `Int` arguments,  maybe we need a 'numeric' constraint – something like,
```haxe
function min<A: Numeric, B: Numeric>(a: A, b: B) {
    return a < b ? a : b;
}
```

**Comment by kevinresol** [comment]
@simn I guess you mean static targets

**Comment by jeremyfa** [comment]
That's actually ok for me to use Std.int(), I was mostly pointing out that something that used to work (at least for rounded floats) stopped working.

Anyway, if casting from float to int is not supposed to work, why not just forbid it then?

**Comment by pecheny** [comment]
@jeremyfa, it works as it supposed: you can treat unsafe cast as disabling type check and inference rather than making types compatible. It can work in some cases on dynamic targets and behavior differs from Std.int().
You can run on try-haxe/js target following example:
```
    var f = 6.5;
    var i:Int = cast f;
    trace("cast to Int " + f + "; Std.int: " + Std.int(f));
```
and see the difference: 
``` Test.hx:6:,cast to Int 6.5; Std.int: 6 ```

**Comment by jeremyfa** [comment]
Alright, I believe it also works on C++ target because of implicit conversion between floats and ints that come from C/C++ world.

Anyway, closing this. Thanks for the explanations, Std.int() it is!
