### ISSUE TITLE
Completion is much slower when targeting C# / Java

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#7651]
Let's assume a project with a single class in which we type `Timer.`:

```haxe
package;

import haxe.Timer;

class Main {

    static public function main():Void {

        trace("Hello World");
        
        Timer.|
      
    } //main
}
```

Using vshaxe, if the hxml is targeting js, like so:

```
-js out.js
-main Main
```

Code completion is **instant**.

However, if I target C# with, say, this hxml:

```
-cs out
-main Main
```

The same code completion is much slower, it takes about one second. I believe something is going wrong with cache.

In both cases, haxe server logs seem to have computed cache and vshaxe "Haxe" output is showing this:

```
Building Cache...
Parsing Classpaths...
Done.
```

Tested on Haxe 4 preview 5 but I recall having this issue on previous versions as well.

**Comment by Gama11** [comment]
Not quite a second for me, but indeed noticably slower. Mostly "other", not sure what that means:

![](https://i.imgur.com/vlsIBQj.png)

JS is indeed instant:

![](https://i.imgur.com/21vg3TM.png)

**Comment by jeremyfa** [comment]
Yea, I guess that varies depending on the machine. Sometimes it's a bit faster, the delay is not completely constant but always noticeable. Probably worse on bigger codebases.

**Comment by Simn** [comment]
It's something in `Dotnet.before_generate`.

**Comment by Simn** [comment]
Looks like it rummages through the file system to find the .net std on every compilation. I suppose we should cache something here, but I'm not very familiar with the architecture.

**Comment by Gama11** [comment]
I guess it's the same with Java? There's a similar slowdown there, but not quite as bad:

![](https://i.imgur.com/Na3S1Eg.png)

**Comment by Simn** [comment]
Java's `before_generate` doesn't seem to to much. However, java calls `close()` on its `java_libs` which probably does something.

We should really add more timers in these areas...

**Comment by Simn** [comment]
Consolidating this in #7450.
