### ISSUE TITLE
setModuleCheckPolicy() breaks haxe server cache when targeting C# or Java

### ISSUE THREAD

**Issue by jeremyfa** [HaxeFoundation/haxe#7652]
On large codebases, I take advantage of `--macro server.setModuleCheckPolicy()` to improve code completion speed. It works fine with JS or C++ target, but breaks on C# target.

I reproduced the issue on a minimal project:

_Main.hx_
```haxe
package;

import somepack.SomeClass;

class Main {

    static public function main():Void {

        trace("Hello World");
        
        var someInstance = new SomeClass();
        someInstance.hello('World');
      
    }
}
```

_somepack/SomeClass.hx_
```haxe
package somepack;

class SomeClass {

    public function new() {
        //
    }

    public function hello(name:String) {
        trace('HELLO $name (SomeClass)');
    }

}
```

build.hxml
```
-cs out
-main Main
--macro server.setModuleCheckPolicy(['somepack'], [NoCheckShadowing, NoCheckDependencies], false)
```

Equivalent with js or cpp target works as expected, but completion server fails with C# target with errors:

```
Building Cache...
Parsing Classpaths...
Main.hx:3: characters 8-26 : Type name String is redefined from module String
Done.
[Error - 13:25:15] Request textDocument/completion failed.
  Message: Main.hx:3: characters 8-26 : Type name String is redefined from module String
  Code: -32603 
[Error - 13:25:18] Request textDocument/completion failed.
  Message: Main.hx:3: characters 8-26 : Type name String is redefined from module String
  Code: -32603 
```

Completion stops working at that stage.

Currently, I have no way to make code completion reasonably fast on large projects when targeting C# because of this issue.

**Comment by ncannasse** [comment]
@jeremyfa are some other targets concerned or is it C#-specific?

**Comment by jeremyfa** [comment]
@ncannasse After trying every other target I thought about, it works as expected on cpp, hl, js, lua, php and python targets, but breaks when targeting **c# or java**

**Comment by jeremyfa** [comment]
Forgot to mention that the error is the same (Type name String is redefined from module String) on both C# and Java target

**Comment by RealyUniqueName** [comment]
I cannot reproduce this with Haxe 4.0.0-rc.2 or latest development.

**Comment by jeremyfa** [comment]
That's sounds like good news, I guess? Did this get fixed somehow?

**Comment by jeremyfa** [comment]
I just tried to reproduce the issue again on Haxe 4.0.0-rc.2, and indeed I don't have the error anymore.

It doesn't seem to happen on rc.1 as well. It seems something has changed since when I posted this issue.

**Comment by Simn** [comment]
Looks like this is resolved.
