### ISSUE TITLE
[js] analyzer-optimize breaks exception handling

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#7653]
When using `try…catch` to catch a specific exception, but then a different exception is thrown inside `try`, code after `catch` is sometimes executed and `catch` code for the actual exception isn't in JS target.

see: http://try-haxe.mrcdk.com/#1e8A5 (try with latest dev and compare with neko or 3.x or preview1 or turn off analyze optimize)
or:
```haxe
class Test {
	static function doSomething() {
		try {
			throw new Exception();
		}
		catch (e:Exception2) {}
		trace("should not print!");
	}

	static function main() {
		try {
			doSomething();
		}
		catch (e:Exception) {
		      trace("why don't you call me?");
		}
		trace("Haxe is great!");
	}
}

class Exception {
	public function new() {}
}

class Exception2 {
	public function new() {}
}
```

Issue only occurs, if body of catch is empty. 

Haxe generates the following JS code:
```js
if(!((e instanceof js__$Boot_HaxeError) ? e.val : e instanceof Exception)) {
	throw e;
}
```
It probably should be 
```
if(!(( ( e instanceof js__$Boot_HaxeError) ? e.val : e )  instanceof Exception)) {
	throw e;
}
```
because of operator precedence.

**Comment by nadako** [comment]
Good catch, it's a general problem with `js.Syntax.instanceof` - it should just generate parens there.
