### ISSUE TITLE
type params vs abstract implicit casts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7656]
```haxe
class C<T> {
	public function new() {}
}

abstract A<T>(Dynamic)
	from C<T>
	from T
{}


class Main {
	static function main() {
		var v = f(new C<Int>());
		$type(v); // C<C<Int>>, but should be C<Int>
	}

	static function f<T>(v:A<T>):C<T> return null;
}
```

**Comment by Simn** [comment]
This is actually a bit bad, you should have nagged me about it every day.

I've fixed it because it's clearly wrong, but we might be breaking some code which relies on this and it's annoying to transition...

**Comment by nadako** [comment]
Hm, I should look into cleaning the promice stuff now when the issues are fixes...
