### ISSUE TITLE
Haxe server cache eventually fails to get fields of superclass in build macro

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFoundation/haxe#7666]
It's a similar issue to #5456, but now only for the haxe server and only after some time after building the cache. It's pretty hard to reproduce consistently as I haven't figured out when exactly it begins to fail. It's often like 15 minutes after rebuilding the cache. At first getting fields of a superclass in a build macro is fine and completion works great.

At some point, it fails, and won't work again until restarting the haxe server. I haven't determined if it is failing to get the field or if it thinks there is no superclass at all, but it could also be the latter.

Haxe 4 preview 5

**Comment by Simn** [comment]
Since there never was a way to reproduce this, I'll go ahead and close. There's a good chance that this has been fixed at some point.
