### ISSUE TITLE
Compilation server leak

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7667]
When (trying to) compile this example, the haxe process memory will keep growing.

```haxe
class Main {
    static function main() {
		new Map();
    }
}
```

**Comment by ncannasse** [comment]
Simply marking the `ctx.has_error <- true` reproduces the leak, as long as an error occurred

**Comment by ncannasse** [comment]
server.ml
```
				if ctx.has_error then begin
					measure_times := false;
					write "\x02\n"
				end else maybe_cache_context ctx.com;
```

If we add && false to has_error it doesn't leak anymore.

**Comment by ncannasse** [comment]
So the leak is not fun. When the context is not cached/reused, it's still kept somewhere in memory (referenced from a global variable) and they accumulate.

**Comment by back2dos** [comment]
Like every other problem, this one can be solved with macros. Add enough of them and the compiler server will require a restart long before you run out of memory. Bam!

**Comment by ncannasse** [comment]
Ok if I assert before filters it doesn't leak. Let's hunt the bad filter

**Comment by ncannasse** [comment]
Ok, it's the AbstractCast.cast_stack that is leaking in case of error

**Comment by Simn** [comment]
Right, that needs some `Std.finally` I guess...

**Comment by ncannasse** [comment]
Doesn't seem to be enough to erase the leak

**Comment by ncannasse** [comment]
Still leaks, there might be several of them
