### ISSUE TITLE
extension method called instead static method

### ISSUE THREAD

**Issue by ryzed** [HaxeFoundation/haxe#7668]
```haxe
class MyExtension {
    public static inline function equals(a:Dynamic, b:Dynamic):Bool {
        return true;
    }
}
```
```haxe
using check.MyExtension;
class EqCheck {
	public static function test(left:EqCheck, right:EqCheck):Bool {
		return EqCheck.equals(left, right); // characters 30-35 : Too many arguments
	}
}
```
Actual result: characters 30-35 : Too many arguments
Expected result: Error: Class<check.EqCheck> has no field equals

**Comment by back2dos** [comment]
That behavior is correct. You can do `check.MyExtension.equals(EqCheck, EqCheck)` and should get `true`.

Better to avoid static extensions for `Dynamic` ... perhaps we should consider disallowing them?

**Comment by back2dos** [comment]
Addendum: you may use `@:noUsing` on methods that you don't actually wish to be applied as static extensions.
