### ISSUE TITLE
write JQuery static plugin extern

### ISSUE THREAD

**Issue by varadig** [HaxeFoundation/haxe#7675]
There is option to write plugin extern for js.jquery.JQuery like this:
```
extern class Select2 {
    static inline function select2( j:js.jquery.JQuery, ?arg:Dynamic ):Dynamic {
        return untyped j.select2(arg);
    }
}

```

and I can use on this way:
```
using class.path.of.the.plugin.Select2;
new js.jqery.JQuery(selector).select2();

```

But I cant figure out how can I write a static plugin extension like [blockUI](http://malsup.com/jquery/block/)

I tried on this way:
```
inline static public function blockUI( j:js.jquery.JQuery, ?arg:Dynamic ):Dynamic {
        return untyped j.blockUI(arg);
    }
    inline static public function unblockUI(j:js.jquery.JQuery):Dynamic {
        return untyped j.unblockUI();
    }
```

and
`        JQuery.blockUI.defaults.message = '<div class="sk-folding-cube sk-primary"><div class="sk-cube4 sk-cube"></div>';
`

but I got this error:

> Class<js.jquery.JQuery> has no field blockUI

**Comment by Simn** [comment]
I'm not quite sure what you're reporting here, but it seems like you want `JQuery.blockUI()` because it's a function.

Please use the [forums](https://community.haxe.org) for general questions.
