### ISSUE TITLE
Macro using package allow access

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7678]
Hej all,
First, happy new year for everyone !
I don't know how to title this issue because I don't really know what's going on, I just success in having a minimal example that show the issue :
Let's say I've a class Main.hx like that : 
```
//using Macro2; 	// build works
using pack.Macro;	// build fails : Cannot access private field _foo

class Main {
	static function main() {
		"foo".foo();
	}
}
```
And a Macro2.hx class on the same level as Main and a pack.Macro.hx that is the same class as Macro2.hx but in a package "pack" : 
Macro2.hx:
```
#if macro
import haxe.macro.Context;
import haxe.macro.Type;
import haxe.macro.Expr;
#end

class Macro2{
	@:access( _Macro2._foo )
	public static macro function foo( expr : ExprOf<String> ) : Expr {
		return _Macro2._foo( expr );
	}
}

class Macro2Iterable{
	@:access( _Macro2._foo )
	public static macro function foo( expr : ExprOf<Iterable<String>> ) : Expr {
		return _Macro2._foo( expr );
	}
}
 
class _Macro2 {
#if macro
	static function _foo( obj:Expr ):Expr {
		return macro null;
	}
#end
}
```
pack.Macro.hx:
```
package pack;
#if macro
import haxe.macro.Context;
import haxe.macro.Type;
import haxe.macro.Expr;
#end

class Macro{
	@:access( _Macro._foo )
	public static macro function foo( expr : ExprOf<String> ) : Expr {
		return _Macro._foo( expr );
	}
}

class MacroIterable{
	@:access( _Macro._foo )
	public static macro function foo( expr : ExprOf<Iterable<String>> ) : Expr {
		return _Macro._foo( expr );
	}
}
 
class _Macro {
#if macro
	static function _foo( obj:Expr ):Expr {
		return macro null;
	}
#end
}
```

So as you can see, when using Macro2 it builds fine but if using pack.Macro, it complains : Cannot access private field _foo.
Note : Tested with Haxe 3.4.4 and Haxe 4-preview 5

**Comment by filt3rek** [comment]
Oh sorry, I just have seen that I have to put the full classpath in compiler meta @:allow and @:access in order to make it work.
Could we have maybe another compiler message for that please ? Or at last an exception saying that "_Macro._foo" not found ?

**Comment by haxiomic** [comment]
I think an error / warning if the class path doesn't exist would be a good idea – could you open a separate issue for that and close this one?
