### ISSUE TITLE
Error/Warning when an ident doesn't exist

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7679]
Hej,
I openend this issue from this one : https://github.com/HaxeFoundation/haxe/issues/7678 and having an error / warning if the class path doesn't exist would be a good idea (for @:allow or @:access or maybe there is others meta like that which accepts an ident and doesn't throw any error if the ident exist or not)

**Comment by Simn** [comment]
Access control works a bit like regex pattern matching: It checks if the path you have matches your `@:allow`/`@:access` paths and then admits access accordingly. In that context it doesn't make any sense for such a path to "not exist" because we don't really know that.

**Comment by filt3rek** [comment]
It's about the full class path package including, I've past 1 day to "debug" that and at the end I realized that because of imports, it was "good for my eyes", it matched for me, no warning and anything to help me understanding why it doesn't work.
I don't think it's a lot of work, maybe I'm wrong, but if not, I find this useful as warning/error, don't you ?
