### ISSUE TITLE
Possible Serialization issue

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#7685]
Hej !

I tried to isolate a strange bug that occurs when I try to serialize objects with dynamic fields to serialize and recursive objects...
I use a similar way to serialize fields of an object as in Ufront, telling it which property of an object to serialize "on, the fly".
To do that, I have to serialize an array of the properties that are serialized in order the Unserializer know which properties to "unpack".
The problems occurs when I serialize the array of the properties to serialize (xfields) as is, so as an array AND the object to serialize is recursive (contact that has company that has contacts and so on...)
If only I transform the "xfield" array into a string separated by comas, it works fine. 
@kevinresol told me that if he sets "USE CACHE" not on the serializer's instance (in hxSerializer function) but on the global static USE_CACHE, it works fine again.

You can find an example here : http://try-haxe.mrcdk.com/#A0F40
If you take a look at the Source 2, in hxSerialize and hxUnserialize, just switch the commented 2 lines

Can anyone tell me please if it could be a bug or maybe I'm doing something wrong ?

Thanks for reading,
Michal

**Comment by filt3rek** [comment]
Ok I think I've got it.
Looking in the Serializer class https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Serializer.hx#L385
It seems that it's vain to set any property to the serializer instance given as argument in a hxSerialize custom function because "useCache" is used before it enters this function.
The only thing to do is to set the global static USE_CACHE

**Comment by filt3rek** [comment]
Maybe it should be added in the documentation about custom serialization because it can bring confusion ?

**Comment by ncannasse** [comment]
I don't understand well what's going on and it seems quite an implementation detail, so hard to document.
