### ISSUE TITLE
haxe 4.0.0-preview.5 Input, BytesBuffer, Output Too many arguments with access Bytes

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#7687]
C:\_sdks\haxe\4.0.0-preview.5\haxe\std/haxe/io/Input.hx:309: characters 30-38 : Too many arguments
C:\_sdks\haxe\4.0.0-preview.5\haxe\std/js/_std/haxe/io/BytesBuffer.hx:58: characters 24-32 : Too many arguments
C:\_sdks\haxe\4.0.0-preview.5\haxe\std/haxe/io/Output.hx:282: characters 29-37 : Too many arguments

**Comment by Simn** [comment]
Sounds like something overrides haxe.io.Bytes.

**Comment by peteshand** [comment]
Yeah, that sounds very logical. Thanks
