### ISSUE TITLE
`has_feature` in common.ml always returns `true` with `-dce no`.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7693]
https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/src/context/common.ml#L508-L533
Because of line 531 this function always returns `true` even for non-existent features.

**Comment by Simn** [comment]
I think that's by-design. If you don't DCE anything, all features are considered enabled by definition. What problem does this cause?

**Comment by RealyUniqueName** [comment]
It triggers this block:
https://github.com/HaxeFoundation/haxe/blob/945461390b774b761f57777365b1e0cbb3ac26be/src/generators/genphp7.ml#L2004-L2005
which causes a runtime exception in projects, which don't use `haxe.CallStack`, because that class is not generated.

**Comment by Simn** [comment]
Ah I see. If the class is never even compiled in the first place, it should not be considered featured I suppose.

In that case we should move that `has_dce` check next to the `Meta.has Meta.Used` checks. Can you try if that works for you?

**Comment by RealyUniqueName** [comment]
I'll check it
