### ISSUE TITLE
[js] @:expose should imply @:keep

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#7695]
When exposing Haxe classes to the outer world, DCE will remove public code, e.g.:

```haxe
@:expose
class Menu {
    static public function render(dom: js.html.Element) {
        dom.innerHTML = 'Menu';
    }
}
```

Compiling this class with full DCE:
```
haxe -dce full -js out.js Menu
```
will literally result in an empty JS file, and the workaround is to add `@:keep` to each `@:expose`'d class.

**Comment by bary12** [comment]
Another workaround would be to write a global build macro, [something like this](https://gist.github.com/bary12/99c328a27db5ea28b2f60e3da9fa3361). Though it should definitely be in the compiler as well.

**Comment by elsassph** [comment]
Thanks but no, macros shouldn't be the solution to every limitation. This is a huge source of confusion and WTF.

**Comment by nadako** [comment]
I agree it's only logical to keep the exposed things.

**Comment by nadako** [comment]
So I wonder how to better implement this:
 - as a pre-dce type JS-only filter: check for `@:expose` add `@:keep`
 - as a DCE check (also check for JS+`@:expose` when we check for `@:keep`)

The first one looks much cleaner, what I'm not sure is the performance impact - we either add an additional loop over all types and fields or we do additional `Meta.has` search for each type and field processed by DCE.

Opinions?

**Comment by Simn** [comment]
I think we should just add `Meta.has_one_of [strict_meta list]` and then use that in `keep_whole_class` and `keep_field`.

**Comment by elsassph** [comment]
Option 2 opens to consider that maybe some other meta should also imply `:keep`

**Comment by sonygod** [comment]
I don't think it's good idea to @:keep every thing when add @:expose

I use same code write server/client  code ,what I want to expose only client side .

but now..everything was expose. I have to write a extra class to do the same thing keep the expose 

as short as possible.

@elsassph

**Comment by Gama11** [comment]
You could just have some `-D client` define, and then do `#if client @:expose #end`.

**Comment by elsassph** [comment]
Maybe a compiler bug is that `:expose` shouldn't include "unrelated" code like server code if you're doing a client build without referencing the exposed classes?

**Comment by Gama11** [comment]
I don't think it does, he must be importing them somewhere.
