### ISSUE TITLE
[display] package completion fails if it contains 'function'

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#7697]
Example:
```haxe
import java.util.function. //Fails here
```

Error:
```
[Error - 9:00:44 PM] Request textDocument/completion failed.
  Message: Index.hx:3: characters 18-26 : Unexpected function
  Code: -32603 
```
:)

**Comment by nadako** [comment]
It's not just about the completion, I don't think you can do fully-qualified access like that as well. We need to escape the keyword package names (and maybe other identifiers) when loading JARs, the question is what the best way to do it while still avoiding potential name clashes with other java packages (like `function` and `_function`).

**Comment by RealyUniqueName** [comment]
We should think about a general "cross-target" mechanism to use keywords as identifiers which will eliminate this type of issues (e.g.  https://github.com/HaxeFoundation/haxe-evolution/issues/22, #7220 and #7645) 
Haxe has multiple targets each with their own sets of keywords and each target allows a subset of Haxe keywords to be used in identifiers.
I believe this should be addressed at the core compiler level, not at the generator level.

**Comment by nadako** [comment]
We have to fix this somehow, since now JVM is getting traction, and `java.util.function` is in the standard lib...

**Comment by Simn** [comment]
`function` is supported now.

@RealyUniqueName Do you think it's okay to pull this into the 4.1 bugfix branch? It's again not strictly a bugfix, but it's pretty limiting for native .jar consumption.
