### ISSUE TITLE
[Hashlink] Stream.hx - Uncaught exception: Eof

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#7700]
For hl.uv classes, when try to call tcp.listen(...)  where  ( var tcp : hl.uv.Tcp ) get the following error 
```haxe
Uncaught exception: Eof
Called from hl.uv.Stream.listen(....\haxe\std/hl/uv/Stream.hx:25)
Called from $Main.main(Main.hx:47)
Called from fun$399(?:1)
Error: Command failed with error 1
```
This is because Tcp class extends Stream  and function  listen(...)  throw error when `!stream_listen(handle, n, onConnect)`  , but  stream_listen is always false , so it will throw error every time .
 Do I miss something or listen(...) it's not implemented ?

**Comment by ncannasse** [comment]
Are you sure you have called bind() before listen ? it's normal it returns false because it's a native function, the implementation is actually in C

**Comment by flashultra** [comment]
yes, here is the code
```haxe
		var loop = Loop.getDefault();
		var tcp = new Tcp(loop);
		var host = new sys.net.Host("localhost");
		var port = 7003;

		
		log("Starting server");
		tcp.bind(host, port);
		tcp.listen(1,  function() {
			log("Client connected");
		} );
```

**Comment by flashultra** [comment]
I was testing with hashlink byte code. When compile to C everything works
