### ISSUE TITLE
Extended class doesn't have static methods

### ISSUE THREAD

**Issue by prnxdev** [HaxeFoundation/haxe#7701]
Hi, I have code:

```haxe
class Model {
    private static var table:String;

    public static function query():QueryBuilder {
        return QueryBuilder.table(Model.table);
    }
}
```

and another class:

```haxe
class User extends Model {
    private static var table:String = 'users';
}
```
when I type:
```haxe
User.query()
```
compiler throws that 'query' is not found in class 'User'. Why?

**Comment by nanjizal** [comment]
Static's belong to a class and are not inherited this is a design decision of Haxe, really it should be clarified here better.
https://haxe.org/manual/class-field-static.html

**Comment by nanjizal** [comment]
Suggest closing if you need more clarity then best discussed on discord, it's not something that is likely to change, so maybe simpler to accept.
https://discordapp.com/channels/162395145352904705/162395145352904705
