### ISSUE TITLE
[display] types in macro function signatures are shown as Dynamic

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7703]
```haxe
class Main {
	public static function main() {
		foo("");
	}

	static macro function foo(s:String) {
		return macro {};
	}
}
```

In hover / signature help / etc, `foo()` shows up as a `Dynamic->Dynamic`:

![](https://i.imgur.com/EX4kLQ3.png)

This is a leak of compiler internals and can be confusing for the user, since the function is actually properly typed in his code.

**Comment by Simn** [comment]
We might be able to get away with only rewriting `Expr` to `Dynamic`, but I'm not sure. Too risky for 4.0 for sure.

Another fix would be to show the macro-version of the function, which should have the correct types. However, that's not exactly easy to do either.
