### ISSUE TITLE
Incorrect transformation of postfix increment with array access

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7704]
```haxe
class Main {
	static function main() {
		var i = 0;
		var a = [];

		a[i] = i;
		i++;
		a[i] = i;

		trace(a);
	}
}
```

This traces `[1]` instead of `[0, 1]`. The generated code looks like this:

```js
var i = 0;
var a = [];
a[i] = i;
a[i] = ++i;
```

Considering that `a[++i] = i` would've been correct, it seems that the compiler fails to take into account that `i` is also used in the array access on the LHS of the assignment.

Note that it doesn't reproduce with `-D analyzer-optimize` since `i` is then inlined. This is a regression, but not a very recent one, according to http://try-haxe.mrcdk.com the first broken version is 3.4.0.

Credit goes to @nanjizal for originally discovering this.

**Comment by nanjizal** [comment]
It may seem rather obscure but actually can be quite a common problem if your setting shader vertices and colors and I think it messed with my head a few times before finally realized. If you point me in the right direction I can try to look through the ocaml.
