### ISSUE TITLE
[feature request] @:structInit by default

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#7705]
Hello there :)
Why `@:structInit` is implemented as meta? 
Why not just allow it by default, to optionally init classes as structs instead of using `new`?
Is there any limitations for this?

**Comment by Simn** [comment]
Sorry but this is not something we could "just allow". You would have to make a compelling case for something like this as a haxe-evolution proposal, but I can tell you that it has virtually no chance of being accepted.

**Comment by back2dos** [comment]
Main issue: constructors can (and should) guarantee that the object is in a valid state upon constructions. If you allow the caller to just set all your fields to any values of their choosing (so long as the type is respected), it becomes impossible to make guarantees about validity.

**Comment by posxposy** [comment]
@back2dos 
> Main issue: constructors can (and should) guarantee that the object is in a valid state upon constructions. If you allow the caller to just set all your fields to any values of their choosing (so long as the type is respected), it becomes impossible to make guarantees about validity.

But you still can use constructor with `structInit`. Like this:
```haxe
@:structInit
class Test {
    public var a:Int;
    public function new (a:Int) {
        if (a < 0) throw "Bam!"; //validate input data
        this.a = a;
    }
}

var t:Test = { a: 10 }; // the same as var t:Test = new Test (10); 
```
Or you meant something else?

---------
I just thought about the Java target. And there is one thing which is not playing good in Haxe side. 
Java supports inline initialization for classes, and it gives flexibility for work with callbacks. Like this:
```java
obj.onClickListener(new Listener () {
   public void onClick () {
        //do stuff here ...
   }
});
```
But in Haxe, when you work with Java target and Java externs, you need to create a separate class for this kind of callbacks (or extends\implements your current class and pass it as `this`), which is annoying. 
I thought it would be much easier to do something like this in Haxe:
```haxe
obj.onClickListener( { // parse it as new Listener ()
    onClick: function ():Void { // and init a function 
          //do stuff here.
    }
})
```
This example will not work in current `@:structInit` implementation, but I thought that it may be possible to implement something like this it in the future. 
I just suggested... :)

Probably I can do it with macros.
