### ISSUE TITLE
Decoding error missing position information

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7710]
When a macro error with "There was a problem decoding (see dump/decoding_error.txt for details)"
It's not possible to tell which macro caused the issue, and no position is provided to tell which part of the code is concerned with the problem.

**Comment by Simn** [comment]
This isn't specific to decoding. You likely have an init macro which calls `make_macro_api` with a `null_pos`, and then `Context.defineType` causes the error.

Not sure which position to use for errors that come from internal API calls. Eval doesn't really track calls to stuff that doesn't have frames...

**Comment by ncannasse** [comment]
When I have an error within --macro they are now correctly reported by VSCode (they show in Problems), which is not the case for this issue.

**Comment by Simn** [comment]
I don't really know what to do with this because I don't know how to reproduce this.

**Comment by ncannasse** [comment]
Don't remember how to reproduce either so will close for now.
