### ISSUE TITLE
Installing Haxe 4.0 on Linux - No Instructions

### ISSUE THREAD

**Issue by kewp** [HaxeFoundation/haxe#7711]
I can't find instructions on installing Haxe 4.0.

So far I do the following with the binary:

- Copy haxe and haxelib to /usr/bin (using cp -a)
- Copy std to /usr/share/haxe

Now haxe runs but I still don't have haxe-stdlib. Is there a version 4 for this? Where can I find it?

**Comment by jdonaldson** [comment]
You'll need to recursively clone the repo, which should pull in the haxelib submodule: https://github.com/HaxeFoundation/haxelib

```
git clone --recursive https://github.com/HaxeFoundation/haxe.git
```
Next I'd recommend installing the opam libraries, and then a full build:

```
make opam_install
make all
```
You should see the ``haxelib`` executable there when you're done.

Moving forward, you'll only need to ``make haxe`` for the compiler itself.

**Comment by kewp** [comment]
Right but this just builds the haxelib binary which you can download from the haxe website. What I’m talking about is haxe-stdlib which is a package that haxe depends on when you install from apt-get or dnf. It installs shared libraries

**Comment by kewp** [comment]
Hmmm looks like I might be wrong - I just opened a haxe-stdlib rpm and it just contains the /usr/share/haxe/std files (which are in the haxe4 release binaries). I was sure I saw other things in there on Fedora....

**Comment by Simn** [comment]
This is already documented at https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md
