### ISSUE TITLE
[cpp] Generated code contains variables which conflicts with MSVC keywords

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#7715]
Hello,
I recently ran into a problem where one of my test classes would not compile with MSVC, but was fine with GCC and Clang. The generated c++ from the following code does not compile with MSVC.
```haxe
class Main
{
	static function main()
	{
		var _w64 = 4;
		trace(_w64);
	}
}
```
The problem seems to be that _w64 is a synonym for __w64 which is a MSVC keyword (https://docs.microsoft.com/en-us/cpp/cpp/w64?view=vs-2017) so you get the following error.
```
 - src/Main.cpp
Error: Main.cpp
./src/Main.cpp(32): error C2513: 'int': no variable declared before '='
./src/Main.cpp(33): error C2143: syntax error: missing ')' before '__w64'
./src/Main.cpp(33): error C2143: syntax error: missing ';' before '__w64'
./src/Main.cpp(33): error C2059: syntax error: ','
./src/Main.cpp(33): error C2059: syntax error: ')'
```
While its easy to avoid in the above example, in my actual project I had an inline function with an argument _w which was being called enough times that _w64 was being generated as a variable name which got me the error.

**Comment by Simn** [comment]
> I had an inline function with an argument _w which was being called enough times that _w64 was being generated as a variable name

That's actually quite amusing... :P
