### ISSUE TITLE
[php] Unable to load classes with same name

### ISSUE THREAD

**Issue by dmcblue** [HaxeFoundation/haxe#7716]
Using Haxe 4.0.0-preview.5+7eb789f54 currently.

If two classes have the same name (even if they have different packages) and are used in the same file, PHP will not load the generated classes.

For example: 
```
// src/test/testA/ModelUuid.hx
package test.testA;
class ModelUuid 
{
	public function new() {}
	
	public function value() {
		return 5;
	}
}

// src/test/testB/ModelUUID.hx
package test.testB;
import test.testA.ModelUuid;
class ModelUUID 
{
	public function new() 
	{
		var m = new ModelUuid();
	}
}

// src/test/Test.hx MAIN CLASS
package test;
import test.testB.ModelUUID;
class Test 
{
	static function main() 
	{
		var m = new ModelUUID();
	}
}
```

Transpiling to PHP and running `bin/index.php` will result in:
```
Fatal error: Cannot declare class test\testB\ModelUUID because the name is already in use in [project location]\test\bin\lib\test\testB\ModelUUID.php on line 15
```

As you notice, I'm running on Windows so classes with different cases can cause problems as well.  I ran into this while creating a wrapper class Uuid for functions from com.hurlant.crypto.extra.UUID.  

I believe the easiest fix would be to add a check for similar names (regardless of case) and then use the `as` statement appropriately in PHP.

For example, the resulting PHP might look like:

```
/**
 * Generated by Haxe 4.0.0-preview.5+7eb789f54
 */
namespace test\testB;
use \php\Boot;
use \test\testA\ModelUuid;
class ModelUUID {
	public function __construct () {
		$m = new ModelUuid();
	}
}
Boot::registerClass(ModelUUID::class, 'test.testB.ModelUUID');
```
and could be changed to:
```
namespace test\testB;
use \php\Boot;
use \test\testA\ModelUuid as TempName;
class ModelUUID {
	public function __construct () {
		$m = new TempName();
	}
}
Boot::registerClass(ModelUUID::class, 'test.testB.ModelUUID');
```

Making this kind of transformation by hand resolved my issue (as did just totally renaming classes, which is not ideal).  Even using alias with `in` like `import test.testA.ModelUuid in TempClass;` did not seem to work, so a fix in the transpiler would be very helpful.

**Comment by RealyUniqueName** [comment]
This is already implemented, but it's case sensitive.
Looks like I forgot that PHP classes are case insensitive :)
