### ISSUE TITLE
RFC genericBuild on generic types

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe#7719]
Example: https://github.com/massiveinteractive/haxe-react/blob/master/src/lib/react/Partial.hx

Using `genericBuild` to construct a new type (in this case where all the fields are optional) doesn't work with generic types because the `genericBuild` is evaluated against `T` while it should ideally be evaluated for each concrete type.

**Comment by ncannasse** [comment]
The idea would be to keep the `TInst("Partial",[T])` inside the @:generic class, and replaces it by running (once) the genericBuild when we create an type specific version of the generic class.

**Comment by Simn** [comment]
There's a better version of this issue here already: #6287
