### ISSUE TITLE
[php] set_include_path For multiple included builds

### ISSUE THREAD

**Issue by dmcblue** [HaxeFoundation/haxe#7725]
I have a project where multiple Haxe => PHP builds are called.  The autoloader is then unable to find classes, particularly Haxe classes that would be used in all builds, even when I prefixed the namespaces with `-D php-prefix=SomePrefix`.

The error:

```
"Class 'SomePrefix\\haxe\\Json' not found"
```
I've traced this down to the build's `index.php` file with the use of `set_include_path` which currently reads as:

```
set_include_path(__DIR__.'/lib');
```

When changed, as suggested on the [functions documentation page](http://php.net/manual/en/function.set-include-path.php#example-570) to:

```
set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__.'/lib');
```

multiple builds can exist together and the problem is resolved. 

Can this be added to the generated template?

**Comment by RealyUniqueName** [comment]
I've pushed the suggested fix.
leaving this issue open till I figure out how to properly setup a test for it.

**Comment by dmcblue** [comment]
Thanks so much!
