### ISSUE TITLE
[Flash] `switch` to access interface fields of arguments causes crash.

### ISSUE THREAD

**Issue by leonaci** [HaxeFoundation/haxe#7727]
Haxe 4.0.0-preview.5 on windows(64 bit) causes Flash to crash for this code:
```hx
enum E {
	A;
	B;
}

interface I {
	var e:E;
}

class Test implements I {
	public var e:E;
	
	function new() {
		this.e = A;
	}
	
	static function run(i:I):Void {
		switch(i.e) {
			case A:
			case B:
		}
	}
	
	static function main() {
		run(new Test());
	}
}
```
but preview.4 didn't reproduce it.

Replacing
```hx
switch(i.e) {
	case A:
	case B:
}
```
with
```hx
var e = i.e;
switch(e) {
	case A:
	case B:
}
```
, it runs properly.

**Comment by Simn** [comment]
Bisected to https://github.com/HaxeFoundation/haxe/commit/e9266713665cec02

**Comment by Simn** [comment]
Before the change we get this dump:

```
		var _g = i.e;
		switch ((@:exhaustive enumIndex _g)) {
			case 0: {};
			case 1: {};
		};
```
After it's this:

```
		switch ((@:exhaustive enumIndex i.e)) {
			case 0: {};
			case 1: {};
		};
```

What likely happens is that the change causes the switch variable to be considered "compiler-generated" and then some code transformation inlines it.

The _actual_ issue must be specific to the flash generator though.
