### ISSUE TITLE
[nullsafety] false-positive error for final field access

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7729]
This is a special case of #7723 that should be easier to solve:

```haxe
@:nullSafety
class Main {
	static function main() {
		var s:{ final ?f:Int; } = {};

		if (s.f != null) {
			f(s.f); // error!
		}
	}

	static function f(v:Int) {}
}
```

Since the field is immutable, it's nullability is invariant.

**Comment by Simn** [comment]
I agree we can utilize the constraints `final` comes with here.
