### ISSUE TITLE
[nullsafety] Emit an error when trying to enable safety on a single field

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7730]
```haxe
class Some {
    @:nullSafety //only @:nullSafety(false) is allowed on fields
    function method() {}
}
```

**Comment by Gama11** [comment]
Why not just allow it? :)

**Comment by RealyUniqueName** [comment]
Hm... Maybe it should be allowed. I just don't see any value in per-field null safety. If all other types and fields stay unsafe, it's not a big difference in safety to check local vars.

**Comment by nadako** [comment]
That's what I also tried to do when I was toying with the feature :)

**Comment by ncannasse** [comment]
If you only allow @:nullSafety(false), maybe there should be a single @:nullUnsafe metadata instead.

**Comment by RealyUniqueName** [comment]
Allowed for fields in 50ab2f631c2d193c4a5df39d2e98e561ca6f049f
