### ISSUE TITLE
[nullsafety] alt name for haxe.Unsafe?

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7731]
haxe.Unsafe makes sense when presented in the context of null safety, but as part of the whole std library it seems not specific at all to null safety.

Could we have an alternate name for it?

haxe.NullUnsafe ?
haxe.MaybeNull ?

Please contribute your preferred naming.

**Comment by RealyUniqueName** [comment]
I'm ok with `NullUnsafe`

**Comment by frabbit** [comment]
UnsafeNull sounds better :D

**Comment by RealyUniqueName** [comment]
Changed to `NullUnsafe`

**Comment by RealyUniqueName** [comment]
Removed in favor of `@:nullSafety(false) expr`
