### ISSUE TITLE
confusing error message for invalid argument types in function type

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7732]
```haxe
class Main {
	static function main() {
		var f:String->Void = function(a:Bool) {}
	}
}
```

```
src/Main.hx:3: characters 3-43 : error: String should be Bool
src/Main.hx:3: characters 3-43 :  have: (String) -> ...
src/Main.hx:3: characters 3-43 :  want: (Bool) -> ...
```

This is reversed: it should be `Bool should be String (have: Bool, want: String)`.

**Comment by Simn** [comment]
Note that it still says `String should be Bool`. I think that's fine because that's the accurate unification message. It's just the have/want that was confusing here in my opinion.
