### ISSUE TITLE
[eval] no position reported even with eval-stack

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7744]
```haxe

class Macro {
	public static function build() {
		var a : Array<Int> = null;
		var x = a[0];
		return null;
	}
}

#if !macro
@:build(Main.Macro.build())
#end
class Main {
	
	static function main() {
	}
	
}
``` 

This gives an error at line 11 (build macro call), but does not report the line 5 invalid array access, even with `-D eval-stack`

**Comment by ncannasse** [comment]
Putting that in 4.0-final because it's quite a show stopper when debugging big macros.

**Comment by Simn** [comment]
Too bad there isn't a debugger or something!
