### ISSUE TITLE
Null safety strictness levels

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7745]
Something like 
```
--macro nullSafety("pack", Weak)
```
For TypeScript-like null safety.

And
```
--macro nullSafety("pack", Strict)
```
For Kotlin level of strictness.

Rough example to showcase the difference:
```haxe
function example(o:{field:Null<String>}) {
  if(o.field != null) {
    mutate(o);
    var notNullable:String = o.f;
  }
}

function mutate(o:{field:Null<String>}) {
  o.field = null;
}
```
The `Weak` null safety would not complain about such code, while the `Strict` one will emit an error on `var notNullable:String = o.f;` because `o.f` could be changed to `null` in `mutate(o)` call.

If different modes are used in the same build, a warning should be emitted and the least strict mode used.

**Comment by Gama11** [comment]
What about `@:nullSafety` meta? Would `@:nullSafety(false)` become `@:nullSafety(Off)` so you can have `@:nullSafety(Weak)` and `@:nullSafety(Strict)`?

**Comment by RealyUniqueName** [comment]
I don't want to support mixed modes )

**Comment by Gama11** [comment]
The ability to set it per package doesn't count as "mixed modes"?

**Comment by Simn** [comment]
> I don't want to support mixed modes )

Any technical reason for that? If we configure this per-field anyway I don't see much of a problem with it.

We could have this:

```
@:nullSafety(false) // no null-safety checks
@:nullSafety == @:nullSafety(true) == @:nullSafety(Weak) // TypeScript
@:nullSafety(Strict) // Kotlin
```

**Comment by RealyUniqueName** [comment]
I'm scared that in the end I'll have to support different modes for different expressions in the single method body :)

**Comment by Gama11** [comment]
@Simn Hm, supporting both `Bool` and a strictness "enum" seems unnecessary / confusing.. If there's ever typed meta that would turn into something like `EitherType<Bool, NullSafetyStrictness>`?

("null safety off" also sounds a bit better in my head than "null safety false")

**Comment by RealyUniqueName** [comment]
That can be like `Strict, Weak, Off`

**Comment by RealyUniqueName** [comment]
But then again, if it's supported per package/field, then why not per expression? )

**Comment by Simn** [comment]
I guess we don't need the bools. I treated it like it's the existing way to configure, but I suppose we are still free to change it.
