### ISSUE TITLE
[display] expansion of env vars in JSON-RPC

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7748]
Auto-completion fails in VSCode with this because env vars are auto-expanded in arguments and we send the file contents via JSON-RPC on the command line:

```haxe
/** %HAXEPATH% **/
class Main {
	public static function main() {
	 	
	}
}
```

```
[Error - 4:51:55 PM] Request textDocument/completion failed.
  Message: Invalid escape sequence
```

**Comment by Simn** [comment]
I don't really know how to fix this... We run the env expansion very early, i.e. before we look at the arguments.

**Comment by ncannasse** [comment]
Maybe a hack would be be not to expand env vars for multiline strings...

**Comment by Simn** [comment]
That might be a good hack.

**Comment by Gama11** [comment]
Hm, I still get the same error with the code example from this issue:

```json
Completion Response =
{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Invalid escape sequence"}}
```

Also note that `"id": null` there, that's not good (but might be a separate issue).. I think that's what leads to completion hanging forever:

![](https://i.imgur.com/VKv5tas.png)

**Comment by Simn** [comment]
I tested your example and it works for me. Are you sure you updated properly?

**Comment by Simn** [comment]
... or maybe the problem is that I don't actually have HAXEPATH defined.

**Comment by Simn** [comment]
I guess the problem is that we don't actually have line breaks, but escaped `\n` instead. 💩

**Comment by Simn** [comment]
Any other clever ideas for hacks?

**Comment by Gama11** [comment]
Is it that hard to just not expand anything in the argument after `--display`?

**Comment by Simn** [comment]
I... don't know why I thought this was so complicated. You're right of course, we can simply not expand the argument after `--display`...
