### ISSUE TITLE
[display] hover doesn't work on `new():Void`

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7751]
```haxe
extern class Foo {
	function foo():Void;
	function new():Void;
}
```

Hovering over the first `Void` works as expected, for the second one it gives "no completion point found".

**Comment by Gama11** [comment]
This one isn't specific to externs, also happens with this:

```haxe
class Main {
	function new():Void {}
}
```

**Comment by Simn** [comment]
I wonder if we should discourage type-hints on constructors. The compiler probably doesn't even look at them, which would explain the issue here. Also, them being typed to return `Void` looks quite confusing.

**Comment by nadako** [comment]
Maybe we could even make it a compile-time error for 4.0?

**Comment by Gama11** [comment]
At least a warning perhaps? There's a couple of these in hxnodejs btw, which is how I found this.

**Comment by Simn** [comment]
A warning makes sense to me. We have to check the situation in externs though.

**Comment by ncannasse** [comment]
Why discouraging or warning? For sure, it should error if it's not Void,
but adding : Void is perfectly valid and should not give any prompt.

**Comment by Gama11** [comment]
If `:Void` is the correct return type, why does this compile (and `return;` doesn't)? ;)

```haxe
class Main {
	public static function main() {
		new Test(0);
	}
}

abstract Test(Int) from Int {
	public function new(i:Int):Void {
		this = i;
		return i;
		// return; // Void should be Test
	}
}
```

**Comment by ncannasse** [comment]
Wait what ? Seems like a bug with abstract new, they should not be allowed to return any value, since we assign "this" instead. Dont't hijack the thread and open a new issue :D
