### ISSUE TITLE
[display] hover doesn't work on arguments of extern functions

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7752]
```haxe
class Foo {
	extern function foo(test:Int):Void;
}
```

In this example hover works on everything but the `test` identifier, there it throws "no completion point was found". It works ok if it's not `extern`:

![](https://i.imgur.com/PQ0xtZO.png)

**Comment by Simn** [comment]
The compiler never really looks at the arguments for externs. This is the code non-extern arguments go through:

```ocaml
	let fargs = List.map2 (fun (n,c,t) ((_,pn),_,m,_,_) ->
		if starts_with n '$' then error "Function argument names starting with a dollar are not allowed" p;
		let c = type_function_arg_value ctx t c do_display in
		let v,c = add_local_with_origin ctx TVOArgument n t pn , c in
		v.v_meta <- v.v_meta @ m;
		if do_display && DisplayPosition.encloses_display_position pn then
			DisplayEmitter.display_variable ctx v pn;
		if n = "this" then v.v_meta <- (Meta.This,[],null_pos) :: v.v_meta;
		v,c
	) args f.f_args in
```

So there is:

1. The `$` check
2. Typing of the default value (hover for those also doesn't work on externs)
3. The display check of the argument itself

I think we want all three of these for extern functions as well. That would also fix this code passing the typer: `extern function foo(test:Int = "foo"):Void;`

**Comment by Simn** [comment]
@haxiomic: I had to push this change to a branch because the HTML externs have some code like this:

```haxe
function createSession( ?sessionType : MediaKeySessionType = "temporary" ) : MediaKeySession;
```

Which now fails with `C:\GitHub\haxe\std/js/html/eme/MediaKeys.hx:44: characters 63-74 : String should be Null<js.html.eme.MediaKeySessionType>`. We should fix this in the externs generator.

**Comment by Simn** [comment]
@RealyUniqueName: Found something for you too: https://github.com/HaxeFoundation/haxe/blob/development/std/php/Global.hx#L1145

```
haxe/std/php/Global.hx:1145: characters 71-92 : Parameter default value should be constant
```

**Comment by haxiomic** [comment]
Thanks for the heads up @Simn

**Comment by haxiomic** [comment]
@Simn, to clarify on this one: do you want me to remove all the inline default values from the externs?

**Comment by Gama11** [comment]
In the example above, it should work to generate the enum abstract value rather than a string literal?

```haxe
function createSession( ?sessionType : MediaKeySessionType = TEMPORARY) : MediaKeySession;
```

**Comment by haxiomic** [comment]
@Gama11 thanks for the clarification, I've made a PR :) #7775

**Comment by Simn** [comment]
3 errors left in the HTML externs:

```
/home/travis/build/Simn/haxe/std/js/html/Window.hx:438: characters 94-96 : Parameter default value should be constant
/home/travis/build/Simn/haxe/std/js/html/ServiceWorker.hx:54: characters 75-77 : Parameter default value should be constant
/home/travis/build/Simn/haxe/std/js/html/URLSearchParams.hx:39: characters 46-48 : String should be Array<Array<String>>
```

**Comment by haxiomic** [comment]
~~I've created a PR (#7797), hopefully that should do it (otherwise let me know the branch name and I'll iterate on it)~~

Made mistakes in that PR – will revisit tomorrow

**Comment by RealyUniqueName** [comment]
> @RealyUniqueName: Found something for you too: https://github.com/HaxeFoundation/haxe/blob/development/std/php/Global.hx#L1145
> 
> ```
> haxe/std/php/Global.hx:1145: characters 71-92 : Parameter default value should be constant
> ```

Fixed in 5aa3289d35df31fbe480d71e7e4a753cd7751b22

**Comment by haxiomic** [comment]
@Simn PR #7798 up to remove the disallowed default values

Seems like there should have been more than 3 errors judging by the number lines affect – would be good to double check that we're not missing anything (like default values in `@:overloads`)

**Comment by nadako** [comment]
@Simn / @ncannasse I'm afraid it looks like there's more to that (from Travis): [`std/flash/events/KeyboardEvent.hx:10: characters 173-174 : Int should be flash.ui.KeyLocation`](https://travis-ci.org/HaxeFoundation/haxe/jobs/495134413#L1319)

In our flash externs there are signatures like:
```haxe
function new(..., keyLocationValue : flash.ui.KeyLocation = 0, ...) : Void;
```
while `KeyLocation` is:
```haxe
@:fakeEnum(UInt) extern enum KeyLocation {
	D_PAD;
	LEFT;
	NUM_PAD;
	RIGHT;
	STANDARD;
}
```

I wonder if we should just re-generate enums like this to enum abstracts with from/to (U)Int?

**Comment by Gama11** [comment]
Interesting, I hadn't noticed that because OpenFL's custom Flash externs [already use enum abstracts](https://github.com/openfl/openfl/blob/df061e16129531500754381d0a446602bc5c17c3/externs/flash/flash/ui/KeyLocation.hx#L4-L13).

**Comment by Simn** [comment]
Meh, that didn't fail on my branch. I guess because we don't run dox there...
