### ISSUE TITLE
[display] hover on overloaded function call doesn't show correct signature

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7753]
```haxe
class Main {
	static function main() {
		Foo.foo(0);
		Foo.foo("");
	}
}

extern class Foo {
	@:overload(function(s:String):Void {})
	static function foo(i:Int):Void;
}
```

Hovering over the calls always shows the "primary" `Int -> Void` signature, which is incorrect for the second one:

![](https://i.imgur.com/6xQneui.png)

**Comment by Simn** [comment]
I don't have a good strategy for fixing this as it requires the call context to resolve correctly. We would have to type the entire call and then extract the field from it.

**Comment by Gama11** [comment]
Hm... I just saw that the C++ extension shows this neat "+N overloads" in hovers:

![](https://i.imgur.com/FiBz2Rw.png)

Perhaps we should actually report the signatures of _all_ overloads in hover requests, and then the client can decide what to do with that - render all of them, show some "summary" like that, or whatever...

Later on we could add some "active overload" property that indicates which overload in the list is actually "active" for the current hover.
