### ISSUE TITLE
[display] ? is lost in signature help of overloaded functions

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7754]
```haxe
class Main {
	static function main() {
		Foo.foo()
	}
}

extern class Foo {
	@:overload(function(?s:String):Void {})
	static function foo(?i:Int):Void;
}
```

It seems the overload's `?` is lost in signature help, while it works for the "primary" overload:

![](https://i.imgur.com/Ixxq34C.png)

![](https://i.imgur.com/btA9sUs.png)

The `Null` wrapper is missing in the JSON, so it's not just a vshaxe presentation / printing problem. Hover on the overload is correct though:

![](https://i.imgur.com/ByBJLIN.png)

**Comment by Simn** [comment]
@RealyUniqueName I'm assigning this to you because I think this is very similar to that metadata function argument problem you were having the other day.
