### ISSUE TITLE
haxe.http.HttpMethod

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#7758]
I just saw that there is an enum abstract now for HTTP request methods under `haxe.http.HttpMethod`.
Any chance of having the values upper-case, i.e. `POST` instead of `Post`?
I think that's usual notation. I know that there is CamelCase for enum values, but this one feels quite strange to me.
Also, woludn't `haxe.http.RequestMethod` be better?

**Comment by Gama11** [comment]
>I think that's usual notation.

That's debatable, if you do a search for `enum abstract` in standard lib, pretty much all results that aren't externs use CamelCase.

**Comment by mockey** [comment]
Sure, no big deal. I have an own abstract for this anyway.
