### ISSUE TITLE
Dash in XML literal node name not parsing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7764]
The following does not parse:

```haxe
class Main {

	static var xml = <player-widget></player-widget>
	
	static function main() {		
	}
	
}
```

**Comment by Simn** [comment]
Argh, in that case I have to rewrite the way we parse this a bit.

**Comment by Simn** [comment]
If anyone with stronger feelings about XML wants to help, I need the correct definition of `xml_ident` here:

```
let idtype = [%sedlex.regexp? Star '_', 'A'..'Z', Star ('_' | 'a'..'z' | 'A'..'Z' | '0'..'9')]

let integer = [%sedlex.regexp? ('1'..'9', Star ('0'..'9')) | '0']

let xml_ident = [%sedlex.regexp? Opt('$'), (ident | idtype)]
```

**Comment by Simn** [comment]
According to the [xml specification](https://www.w3.org/TR/xml/#sec-common-syn), `$` is not a valid character for names. What spec am I supposed to follow here?

**Comment by Simn** [comment]
Tentative result of our slack discussion: We allow names according to the XML spec with the addition of the `$` character. This should be somewhat sane.
