### ISSUE TITLE
Implicit casts not applied for abstract of abstract

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/haxe#7766]
Given the following code:
```haxe
abstract Inner(Int) from Int to Int
{
    @:to
    function toBool()
    {
        return this > 0;
	}
}

@:forward
abstract Outer(Inner)
{
    public inline function new(a:Int)
    {
    	this = a;
	}
}
class Test {
    static function main() {
        var o:Outer = new Outer(5);
        
        if (o)
        {
		}
    }
}
```

It will fail to compile the if (o) unless the @:to is placed on the Outer abstract. Is this expected or is there a way to follow the implicit cast operator for abstracts of abstracts?

**Comment by Gama11** [comment]
Abstract casts are not transitive as documented here:

https://haxe.org/manual/types-abstract-implicit-casts.html

**Comment by Simn** [comment]
Yes and we shouldn't make `@:forward` influence this either.
