### ISSUE TITLE
[eval] stepping over should give "about-to-leave-function" indication

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7767]
When stepping over code, debuggers usually indicate in some way that they're about to leave a function. Node debugging in VSCode for instance highlights the function headers, I've seen other debuggers move the the closing `}` of the function.

![](https://i.imgur.com/YiYKbio.gif)

Eval doesn't do this, it just exits after the `if` (IMO it's also way too granular there, but that's a separate issue):

![](https://i.imgur.com/Tm3M8LW.gif)

**Comment by ncannasse** [comment]
For HL I'm emitting the HRet opcode on the pmax of the function.
