### ISSUE TITLE
php target 4.0.0-rc.1+1fdd3d59b complains

### ISSUE THREAD

**Issue by axelhuizinga** [HaxeFoundation/haxe#7768]
C:\HaxeToolkit\haxe\std/php/_std/String.hx:32: characters 10-30 : Class<php.Global> has no field mb_strtoupper (Suggestion: strtoupper)
C:\HaxeToolkit\haxe\std/php/_std/String.hx:36: characters 10-30 : Class<php.Global> has no field mb_strtolower (Suggestion: strtolower)
C:\HaxeToolkit\haxe\std/php/_std/String.hx:62: characters 10-23 : Class<php.Global> has no field mb_chr
C:\HaxeToolkit\haxe\std/php/Boot.hx:54: characters 3-30 : Class<php.Global> has no field mb_internal_encoding (Suggestion: mb_convert_encoding)
C:\HaxeToolkit\haxe\std/php/Boot.hx:689: characters 10-30 : Class<php.Global> has no field mb_strtoupper (Suggestion: strtoupper)
C:\HaxeToolkit\haxe\std/php/Boot.hx:693: characters 10-30 : Class<php.Global> has no field mb_strtolower (Suggestion: strtolower)
C:\HaxeToolkit\haxe\std/php/Boot.hx:730: characters 4-20 : Class<php.Global> has no field mb_strpos
C:\HaxeToolkit\haxe\std/php/Boot.hx:749: characters 4-21 : Class<php.Global> has no field mb_strrpos
C:\HaxeToolkit\haxe\std/php/Boot.hx:798: characters 10-23 : Class<php.Global> has no field mb_chr
C:\HaxeToolkit\haxe\std/php/_std/sys/net/Socket.hx:127: characters 59-66 : php.NativeStructArray<{ usec : Int, sec : Int }> should be Bool
C:\HaxeToolkit\haxe\std/php/_std/sys/net/Socket.hx:127: characters 59-66 : For function argument 'val'
C:\HaxeToolkit\haxe\std/php/_std/sys/net/Socket.hx:129: characters 55-62 : php.NativeStructArray<{ usec : Int, sec : Int }> should be Bool
C:\HaxeToolkit\haxe\std/php/_std/sys/net/Socket.hx:129: characters 55-62 : For function argument 'val'

**Comment by Simn** [comment]
Please double-check that you're actually using the correct standard library.

**Comment by axelhuizinga** [comment]
Sorry - my bad - I forgot I used to override some signatures - shouldn't be the driver_options in PDO::prepare be optional?
