### ISSUE TITLE
[js] WebGL2Context does not inherit from RenderingContext

### ISSUE THREAD

**Issue by ncbray** [HaxeFoundation/haxe#7771]
@haxiomic

WebGL2's interface is a superset of WebGL:
https://github.com/KhronosGroup/WebGL/blob/master/specs/latest/2.0/webgl2.idl#L601
But js.html.webgl.WebGL2Context does not inherit from js.html.webgl.RenderingContext.  Supporting both versions of WebGL in an app requires some amount of code duplication because Haxe's type system sees them as separate types.

**Comment by haxiomic** [comment]
Thanks for the report @ncbray, looks like the `WebGLRenderingContextBase` type is a bit of a fudge to overcome IDL overload issues – WebGL2 can directly extend WebGL1 without issue. I've made a workaround in the externs generator: #7774
