### ISSUE TITLE
Abstract @:from macro displays false? warning

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#7777]
It seems since the release of `4.0.0-preview.4` the following [code](https://gist.github.com/skial/1e351a80f59f1a538d55540dab9218e2) started causing the compiler to warn that `Thing should be Foo<String>`.  Testing with `4.0.0-preview.3` no warnings are reported by the compiler.

![preview](https://user-images.githubusercontent.com/379926/52557252-bf7ed880-2de6-11e9-9ce1-8ca77f5a6c87.png)

**Comment by markknol** [comment]
Did you also test `4.0.0-preview.5` or `4.0.0-rc.1` ?

**Comment by skial** [comment]
Yep and the most recent nightly build `1229db0`.

**Comment by skial** [comment]
I've just tested the issue code with the `fe0802f` nightly build and the warnings no longer appear.

**Comment by Gama11** [comment]
As far as I can tell, this was actually just an issue with diagnostics, not with compilation? I'll add a test for this.
