### ISSUE TITLE
Huge compilation time when using Map with typedef key

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#7781]
Code like this (but with more types and fields) takes very long time to compile.
Time grows non-linearly: 
7 types/fields - 0.170 sec
8 types/fields - 0.902 sec
9 types/fields - 9.642 sec on my machine
10 types/fields -  392.284 sec, used more then 10GB RAM 
```haxe
typedef A0 = {
	var a0: A0;
	var a1: A1;
	var a2: A2;
}

typedef A1 = {
	var a0: A0;
	var a1: A1;
	var a2: A2;
}

typedef A2 = {
	var a0: A0;
	var a1: A1;
	var a2: A2;
}

class Test3 {
	static function main() {
		var m: Map<A0, Int> = new Map();
	}
}
```
Here are test generator and generated tests: [test-map-slow.zip](https://github.com/HaxeFoundation/haxe/files/2856657/test-map-slow.zip)
This fails on try haxe due to timeout: http://try-haxe.mrcdk.com/#7139d

**Comment by Simn** [comment]
Setting this to 4.0 because it's quite bad.

**Comment by Simn** [comment]
This is related to (and probably caused solely by) https://github.com/HaxeFoundation/haxe/commit/858f28ea0536d60a3509fcd3e3900ee7a999f6f5

**Comment by ncannasse** [comment]
@simn restricting the stack depth here might be good enough

**Comment by Simn** [comment]
It occurred to me that we don't need an actual stack for this kind of check. We only care about revisiting types, not doing so in a recursive way. I've moved the stack outside of the check loop (which technically means it's not a stack but more like a lut) to make sure we look at every type exactly once.
