### ISSUE TITLE
Class initialization + serialization in JS target

### ISSUE THREAD

**Issue by aartzrc** [HaxeFoundation/haxe#7783]
Hopefully not a redundant issue, but I have an odd case where I am trying to serialize some data during class initialization. It works in `--interp` but `-js` target fails. Here's a sample to reproduce the problem:

```haxe
import haxe.Serializer;

class InitSerializeTest  {
    static function main() {
        trace(Serializer.run(Defaults.defaults));
    }
}

class Defaults {
    static public var defaults:DefaultVals = buildDefaults();

    static function buildDefaults() {
        var d:DefaultVals = {
            someVal: "someVal"
        };
        trace(Serializer.run(d)); // This breaks in JS target
        return d;
    }
}

typedef DefaultVals = {
    someVal:String
}
```
It fails on `js` target with 
```
var name = js_Boot.__toStr.call(o).slice(8,-1);
TypeError: Cannot read property 'call' of undefined
```
Looking at the bottom of the javascript output:
```javascript
haxe_Serializer.USE_CACHE = false;
haxe_Serializer.USE_ENUM_INDEX = false;
haxe_Serializer.BASE64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%:";
Defaults.defaults = Defaults.buildDefaults();
js_Boot.__toStr = ({ }).toString;
InitSerializeTest.main();
```
It's apparent that the `js_Boot.__toStr` function is defined after class initialization which causes the problem. There may be other related side effects of this.

**Comment by nadako** [comment]
Thanks for the report and the awesome reproducible example! The magic helper `__toStr` function should be of course already available when statics are initializing, I fixed it \o/
