### ISSUE TITLE
DOMElement.requestFullscreen missing

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7784]
I noticed `DomElement` doesnt have `requestFullscreen()` anymore in Haxe 4.0.0. It 

3.4.7 api doc https://api.haxe.org/js/html/DOMElement.html
4.0 api doc https://api.haxe.org/v/development/js/html/DOMElement.html

MDN: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

cc @haxiomic Maybe you want to take a look at this?

**Comment by haxiomic** [comment]
Good spot @markknol, looks like a new flag "nsDocument::IsUnprefixedFullscreenEnabled" was added in the WebIDLs, will PR to fix
