### ISSUE TITLE
Std.int() return negative value when the input float > 2147483647 (JS target)

### ISSUE THREAD

**Issue by MiloHX** [HaxeFoundation/haxe#7791]
As captioned.

**Comment by ncannasse** [comment]
That's perfectly normal, it's a 32 bit integer overflow.

**Comment by MiloHX** [comment]
@ncannasse Thanks for the explanation. I am using Krom, and It actually worked before (converted correctly with > 2147483647 value), but after the latest update it stopped working. Maybe Krom changed to use 32 bits internally, I will check further.

**Comment by MiloHX** [comment]
I am wrong, it never converts correctly, please ignore this one.
