### ISSUE TITLE
Context.defined / Context.definedValue keys should translate dashes to underscores

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7795]
**Description**
In current setup, If I use `-D haxe-is-great` then
-  `Context.defined("haxe-is-great")`  is false
-  `Context.defined("haxe_is_great")`  is true

Same goes for `Context.definedValue`.
This is because `#if haxe-is-great` doesn't work, which makes sense. 

The `Context.defined` docs now say  
> Compiler directives are set using the `-D` command line parameter

This is confusing because the -D parameter does contains a dash, but its translated somewhere in the process. I would expect both to work.

**Question:**
Can we allow `Context.defined("haxe-is-great")` and `Context.defined("haxe_is_great")` to both return `true` if `-D haxe-is-great` is set?

**Comment by elsassph** [comment]
What about just making `-D haxe-is-great` work? And I guess for backwards compatibility both would have to work.
