### ISSUE TITLE
Metadata seems to be broken on arrow function arguments

### ISSUE THREAD

**Issue by wartman** [HaxeFoundation/haxe#7800]
Arrow functions seem to break if you use metadata on their first argument (in 4.0.0-rc.1).

```haxe
// This works:
function foo(@bar bar:String) return bar;

// This also works:
var foo = (a:String, @bar b:String) -> a + b;

// This will result in an error along the lines of "Unexpected ;"
var foo = (@bar bar:String) -> bar; 
```

**Comment by Simn** [comment]
The lambda parsing code gives me a headache. Can we remove short lambdas? :P

**Comment by RealyUniqueName** [comment]
Submit a proposal )

**Comment by Simn** [comment]
Honestly, can we simply document that metadata on short lambda function arguments isn't supported? This is a bit of a parsing nightmare and IMO also doesn't really suit the short notation to begin with.

**Comment by Gama11** [comment]
Shouldn't it at least _not_ work _consistently_ then? Right now it seems to work as long as it's not on the first argument.

**Comment by Simn** [comment]
Yes that's what I'm suggesting.
