### ISSUE TITLE
[c#/java] Cannot find field enumIndex in class Type

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7805]
Looks like C# / Java don't compile more than once through the compilation server right now:

```haxe
class Main {
	static function main() {}
}
```

```
>haxe --wait 7000
```

```
>haxe -main Main -java java --connect 7000
C:\Program Files\Java\jdk1.8.0_121/bin/javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"

>haxe -main Main -java java --connect 7000
Error: Cannot find field enumIndex in class Type
```

This is obviously a regression, but 4.0.0-rc.1 is already affected. Preview 5 is fine.

**Comment by nadako** [comment]
Since `Type.enumIndex` is marked with `@:ifFeature("has_enum")` it means that the `has_enum` feature is lost during the second compilation, so the method gets eliminated by DCE. A quick band-aid fix of course is to comment out the `@:ifFeature`, but looks like there's something wrong with state recovering and it might cause other issues.

**Comment by Simn** [comment]
I think I know why this happens.

**Comment by Simn** [comment]
See if that helped!

**Comment by Gama11** [comment]
Yep!

Aren't there some compilation server tests that should've caught this? I guess they don't test all targets?

**Comment by Simn** [comment]
We don't run any compilation server tests. Our CI in that regard consists of Nicolas and you.

**Comment by Gama11** [comment]
But... https://github.com/HaxeFoundation/haxe/blob/development/tests/server/src/Main.hx

**Comment by Simn** [comment]
Yah but all these just fail so we don't run them. :D

**Comment by Gama11** [comment]
Oh... :(

**Comment by nadako** [comment]
ae0ab793ad40a935e70c66464952210ec4b3e8c1 somehow breaks some feature detection in [js](https://travis-ci.org/HaxeFoundation/haxe/jobs/495134414#L2598) and [python](https://travis-ci.org/HaxeFoundation/haxe/jobs/495134414#L3317).

the js issue seems to come from this: https://github.com/HaxeFoundation/haxe/blob/5333a5817f3c5625c550758eb092164af70f22c0/std/js/_std/Std.hx#L65-L68

and it already gives me headache

**Comment by nadako** [comment]
OK, the issue seems to be that `Common.has_feature` actually checks for `Meta.Used`, which is now cleared out, so the `__feature__` and friends fail.

**Comment by nadako** [comment]
I reverted @Simn's fix for now, sorry but I need travis to do some work :)

**Comment by Simn** [comment]
Seems strange that `has_feature` would check that. Without the `@:used` meta and with DCE enabled, the type in question wouldn't be in `com.types` in the first place.

**Comment by Simn** [comment]
I guess it does make a difference for `extern` classes, argh.

**Comment by Simn** [comment]
Alright this should work: It now removes the `@:used` during DCE's entrypoint collection. This means it's going to be there between DCE and the end of compilation 1, but then gets removed at the DCE stage of compilation 2. I "think" this is what we want here.
