### ISSUE TITLE
[typer] abstract constructors shouldn't be allowed to return a value

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7809]
(extracted from #7751)

This compiles, despite the `:Void` type hint on `new`:

```haxe
class Main {
	public static function main() {
		new Test(0);
	}
}

abstract Test(Int) from Int {
	public function new(i:Int):Void {
		this = i;
		return i;
		// return; // Void should be Test
	}
}
```

**Comment by Simn** [comment]
I'm removing the 4.0 milestone from this because I don't find this clear cut. Why should class constructors be allowed to return early but abstract constructors not? I think the actual problem here is with the typing.

**Comment by Gama11** [comment]
I don't think anybody wanted to disallow returns, but it should probably be `return;`, not `return value;`? Quoting @ncannasse:

>they should not be allowed to return _any value_

**Comment by Simn** [comment]
I see, I misread that. Still not 4.0 priority though, and also not easy to fix because this becomes a very normal function to the typer...

**Comment by Gama11** [comment]
Agreed, doesn't seem urgent.

**Comment by Gama11** [comment]
Worryingly, a `return` also seems to bypass the `missing this = value` check.

```haxe
class Main {
	public static function main() {
		new Test(0);
	}
}

abstract Test(Int) from Int {
	public function new(i:Int):Void {
		return i; // compiles!
	}
}
```

I'm not sure what the implicaitons of this are, but that might make it Haxe 4 priority after all?

It at least seems to break with `inline`, which results in a confusing `Cannot inline a not final return`.
