### ISSUE TITLE
Final function as fully private

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#7812]
At the moment, with this code, Haxe gives errors concerning the `missed override declaration` and `Cannot override final method` (which is logical):
```haxe
class Test {
  final function myFunc():Void {}
}
class Test2 extends Test {
  function myFunc():Void {}
}
```
I'm interested in your opinion in case this code can be considered valid. `final function` will be a "fully private" function, with the ability to create a personal function with the same name in the subclasses and without access/completion to `super.myFunc`.

**Comment by Geokureli** [comment]
I don't see why you would want the final keyword to make these methods more private? I foresee cases where I would want private final methods to be visible to derived classes.

It sounds like you want haxe to distinguish between private and protected, which is a decent argument to make, but really has nothing to do with final.

**Comment by Simn** [comment]
There currently is no true `private` in Haxe, which can be a problem in some cases. However, we definitely don't want to sneakily introduce it through `final`.
