### ISSUE TITLE
[display] display randomly uses extern arguments

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7814]
I've been having random issues with hover and goto definition not working properly. It reproduces perfectly, but seems a bit tricky to isolate, so I bisected it instead, to 308d19ceb19af91c9dbaa6ee882c571eaeccbe7f.

Example, I hover over this `html` field and it reports some `fromIndex` argument instead:

![](https://i.imgur.com/czUcZ1h.png)

Looking at the JSON, this is actually from a completely different file:

```
"pos": {
    "file": "C:\\Users\\Jens\\GitHub\\haxe\\std/js/html/Uint8Array.hx",
    "min": 3025,
    "max": 3034
}
```

Sure enough, here's our `fromIndex` (and that's also where goto definition on `.html` takes me)...

https://github.com/HaxeFoundation/haxe/blob/22494d769d862945d2cae6858bf90fd3eba7a34c/std/js/html/Uint8Array.hx#L56

Seems like there's a check missing for whether we're even in the correct file when displaying?

**Comment by Simn** [comment]
Haha, oops

**Comment by Gama11** [comment]
I really wanted to blame nadako at first, since I remembered that he messed with positions (9a8ab5979bf007f635e861cde8df63965bc18d94), but reverting that locally didn't help.. :P
