### ISSUE TITLE
[PHP] Web.getClientHeader

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#7815]
This function uses `getallheaders` (if available). I have one server where the header names are returned in lowercase and another one where their case is kept.
So I get `x-requested-with` on one server and `X-Requested-With` on the other. Maybe because of different php versions (7.2 vs. 7.0)? I read that header names are case insensitive. Maybe convert them all to lowercase?

**Comment by RealyUniqueName** [comment]
The old php generator did it in the upper case. So maybe the new one should do the same?
Also `Web.getClientHeader(name)` should be case insensitive too.

**Comment by mockey** [comment]
> The old php generator did it in the upper case. So maybe the new one should do the same?
Also Web.getClientHeader(name) should be case insensitive too.

Yes, this would be best, I think. Using upper or lower case internally wouldn't matter then, if the conversion is done in the function call.
BTW: `getClientHeaders()` returns a List, which is out of fashion nowadays. Maybe switch this to Array or Map (a Map is already created)?

**Comment by RealyUniqueName** [comment]
fixed in 64fc139bb7141493b18857b7d3da63f0593ce25f
