### ISSUE TITLE
Crc32 unit test failure on eval on AppVeyor Windows

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7826]
This currently fails on AppVeyor:

```
src/unitstd/haxe/crypto/Crc32.unit.hx:2: -1051745479 should be 1095738169
```

**Comment by Simn** [comment]
I'm using the zlib implementation here:

```ocaml
module StdCrc32 = struct
	let make = vfun1 (fun data ->
		let data = decode_bytes data in
		let crc32 = Extc.zlib_crc32 data (Bytes.length data) in
		vint crc32
	)
end
```

No idea how that can fail.

**Comment by Simn** [comment]
```c
// extc_stubs.c
CAMLprim value zlib_crc32( value src, value len ) {
	uLong crc = crc32(0L, (Bytef*)(String_val(src)), Int_val(len));
	return Val_int(crc);
}
```

```c
// mlvalues.h
#define Val_long(x)     ((intnat) (((uintnat)(x) << 1)) + 1)
#define Long_val(x)     ((x) >> 1)
#define Max_long (((intnat)1 << (8 * sizeof(value) - 2)) - 1)
#define Min_long (-((intnat)1 << (8 * sizeof(value) - 2)))
#define Val_int(x) Val_long(x)
#define Int_val(x) ((int) Long_val(x))
#define Unsigned_long_val(x) ((uintnat)(x) >> 1)
#define Unsigned_int_val(x)  ((int) Unsigned_long_val(x))
```

@ncannasse: `Val_int` looks like the wrong thing to use here, but I'm not sure what else to use. Any advice?

**Comment by ncannasse** [comment]
Yes Val_Int will overflow on 31/63 bits depending on the platform. You need to return an actual Int32.t, I'm not sure which C call is necessary for this, look at caml api H

**Comment by Simn** [comment]
I was concerned about breaking ocamllibs compat with Haxe 3.4, but as it turns out we've only exposed zlib's crc32 after 3.4 anyway: https://github.com/HaxeFoundation/ocamllibs/commit/5396ed3306f5a10be138d309d3f9dbf90b8ee07f

So this isn't even your fault, dammit.

**Comment by Simn** [comment]
Possibly fixed by https://github.com/HaxeFoundation/ocamllibs/commit/101516896900a046e19e32737b9a09a870da2f94. With any luck AppVeyor should tell us before the end of the month.

**Comment by Simn** [comment]
passed
