### ISSUE TITLE
Bug interface with finals and extended types

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#7827]
This should work, but doesn't.
```haxe
class Base {}

class Child extends Base {
    public function new() {}
}

interface I {
    final x:Base;
}

class Main implements I {
    public final x:Child = new Child();

    static function main() {
    }
}
```
Demo: http://try-haxe.mrcdk.com/#e10ea

**Note:**  
Changing `final x:Base;` to `var x(default,never):Base;` in interface I makes it work http://try-haxe.mrcdk.com/#a5d95

Found in Haxe 4.0.0-rc-1

**Comment by Simn** [comment]
This is nice-to-have but not really 4.0-critical.

**Comment by Simn** [comment]
Let's fix this too while I'm looking at this stuff anyway.
