### ISSUE TITLE
[eval] macro call location in callstack

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7840]
Eval-debugger's call stack doesn't give a lot of indication as to where a macro call came from. It seems like at least theoretically, it should be possible to have this info for all different kinds of macros:

- **Expression Macros**: Right now the call site doesn't seem to be part of the call stack. This is probably the most straighforward one to fix.

    ![](https://i.imgur.com/23WIc0H.png)

- **Build Macros**: When debugging build macros, would it be possible to add the location of the `@:build()` / `@:autoBuild()` meta the call came from to the top of the callstack? I guess in some cases it might come from a `Compiler.addMetadata()` / `Compiler.addGlobalMetadata()` call, not sure if it'd still be possible then.
- **Initialization Macros**: Similarly, it would be even cooler if this was possible with expression macros too, in this case the location of `--macro` in HXML. But that's probably a lot more involved (since it would require keeping track of HXML positions), and only possible if the `--macro` is even _in_ a HXML rather than a command line argument. Not to mention `extraParams.hxml` which Haxe never sees because Haxelib pre-processes those.

**Comment by Gama11** [comment]
Something still needs to be done about entry points coming from `Compiler.add(Global)Metadata("@:build")` / `"@:autoBuild"`. Either the proper location of the `Compiler` call should be used (if it happened in an init macro), or the adapter should disable / grey out the call stack item so you can't click on it and get an error as is currently the case:

![](https://i.imgur.com/gNRnLl4.png)

**Comment by Simn** [comment]
This sounds like something the adapter has to handle. Or what position does it report here?

**Comment by Gama11** [comment]
Well, depends on whether or not it's possible to obtain the location of `Compiler.addMetadata()` calls I guess?

According to the "copy call stack" context menu item, it just sends `.` as the file name right now. I'm guessing `Source.path` should be set to `null` for invalid positions instead.

```
entrypoint (c:\Users\Jens\.vscode\extensions\haxe-test-adapter\samples\buddy\.:1)
```

**Comment by Simn** [comment]
Interesting, I have no idea where such a position comes from...

**Comment by Simn** [comment]
Please test with https://github.com/Simn/haxe/tree/eval_stack_improvements and latest eval-debugger and tell me if that behaves as expected now.

I've changed it so that all entry-point stack items are now considered "artificial" (which causes a `label` display in vscode), but still use the source if available. Normal stack items should be unaffected by this. It also now prints the expression of `--macro` calls as the name of the stack item.

**Comment by Gama11** [comment]
Awesome, it finds the correct location now. :) But is it normal that it shows the full path here instead of a dot path?

![](https://i.imgur.com/WuplPHd.png)

It should at least be a properly-cased path instead of all-lowercase?

**Comment by Gama11** [comment]
For init macros it seems perfect. :)

![](https://i.imgur.com/jjD3HIS.png)

**Comment by Gama11** [comment]
Interesting, for this expression macro the file name casing is correct:

![](https://i.imgur.com/bUMn4uI.png)

Still, seems like a `flixel.input.keyboard.FlxKey` style dot-path would be nicer.

**Comment by Simn** [comment]
I use positions for this so I can't transmit a dot path.

Don't know why the casing is wrong, I use `get_real_path` in all these cases. Does the file actually exist?

**Comment by Gama11** [comment]
Sure, it even takes me to it when I click the call stack item.

**Comment by Simn** [comment]
Oh I see why

**Comment by Simn** [comment]
That should be better.

I could potentially show dot paths for expression macros, but I'm not sure if it's worth it. Also, it doesn't look like vscode would show this correctly anyway because we already provide the correct source with line and column: `{"id":1,"name":"C:\\GitHub\\HaxeRepro\\source\\Main.hx","source":"C:\\GitHub\\HaxeRepro\\source\\Main.hx","line":4,"column":3,"endLine":4,"endColumn":12,"artificial":true}`.

**Comment by Gama11** [comment]
Yep, that fixed that case.

Not sure I follow.. is the dot path determined automatically by VSCode? I thought that would be something the adapter has to provide.

**Comment by Simn** [comment]
Yes my point is that it wouldn't look like the other dot paths anyway. And arguably that's a good thing because it's not a real stack item. Plus it would introduce inconsistencies with expression macros showing dot-paths and all other entry-points showing files.

**Comment by Gama11** [comment]
I think my main issue is that it's such a long path that you have to expand the sidebar to see what file that even is.. Normally the file name is shown on the right there like `Injector.hx`:

![](https://i.imgur.com/WKlL20v.png)

I'm guessing we couldn't show a relative path either because if we knew how to do that we could show a dot path? Maybe something like `Macro.hx (full path)` would make things more readable.

**Comment by Simn** [comment]
Eval's frames use the unique path, which is generally necessary to deal with breakpoints correctly. I can either keep both the original and unique path, or try to find the relative path from the unique path. I think the latter sounds worse though.

**Comment by Simn** [comment]
I think I finally got this right now.

## Macro call from --macro

![code_2019-02-26_09-15-14](https://user-images.githubusercontent.com/634365/53397305-19ff6380-39a7-11e9-8117-95d49241ed05.png)

## `@:build` via addGlobalMetadata via --macro

![code_2019-02-26_09-16-14](https://user-images.githubusercontent.com/634365/53397351-356a6e80-39a7-11e9-945b-2bf356d0b407.png)

## normal `@:build` in syntax

![code_2019-02-26_09-17-01](https://user-images.githubusercontent.com/634365/53397379-4d41f280-39a7-11e9-9151-889688cbfef0.png)

## Expression macro

![code_2019-02-26_09-18-21](https://user-images.githubusercontent.com/634365/53397443-7a8ea080-39a7-11e9-9c79-8d7587f81a93.png)

## `@:build` via addGlobalMetadata via expression macro

![code_2019-02-26_09-18-50](https://user-images.githubusercontent.com/634365/53397514-96924200-39a7-11e9-9cdb-b8a04f43ad83.png)

**Comment by Simn** [comment]
hopefully closed by #7870

**Comment by Gama11** [comment]
Urm... so I'm meant to see relative paths now? Not seeing much of a difference:

![](https://i.imgur.com/kQtzM5b.png)

**Comment by Simn** [comment]
It uses the original path. If that's not relative then you won't see a relative path.
