### ISSUE TITLE
[js] do not generate __interfaces__ (and maybe interface definitions) if Std.is is not used

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7843]
I want to look into skipping generation of interfaces and `__interfaces__` field when run-time type checking that requires it is not present in the output.

**Comment by ncannasse** [comment]
`catch( e : Interface )` might be involved too

**Comment by nadako** [comment]
yes, but that is actually transformed into `Std.is` so it should automatically work. i'll make sure to test cases like this

**Comment by nadako** [comment]
I made it so `__interfaces__` is only generated when `js.Boot.__instanceof` is present. This covers both `Std.is` and typed `catch`.

Also I made actual interface declarations only generate when needed, in the following cases:
 - interface type is directly accessed (thanks DCE and the `@:directlyUsed` mark)
 - `Type.resolveClass` is used because we can resolve it (not sure why would we tho)
 - `js.Boot.__instanceof` is present, so we need add the interface to `__interfaces__`. we could actually make it smarter and only add interfaces to `__interfaces__` if the first two conditions are met :)

Leaving this open so I don't forget to add a test for this.

**Comment by RealyUniqueName** [comment]
> This covers both `Std.is` and typed `catch`.

What about typed cast to an interface?

**Comment by Simn** [comment]
Could you also deal with #7834 while you're at it?

**Comment by nadako** [comment]
> What about typed cast to an interface?

That will keep `__cast` (due to `typed_cast` feature) and thus `__instanceof`  and thus everything else :)

**Comment by nadako** [comment]
> Could you also deal with #7834 while you're at it?

Welp, I can certainly look into it :)

**Comment by Simn** [comment]
What's the status here?

**Comment by nadako** [comment]
Meh.
