### ISSUE TITLE
[nullsafety] null check doesn't work in local function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7853]
For some reason, the following only compiles with loose null safety if the code isn't wrapped in a local `bar()` function:

```haxe
@:nullSafety
class Main {
	static function main() {
		foo();
	}

	static function foo(?callback:() -> Void) {
		function bar() {
			if (callback != null) {
				callback(); // Null safety: Cannot call a nullable value.
			}
		}
		bar();
	}
}
```

**Comment by RealyUniqueName** [comment]
Because in strict mode `callback` is not guaranteed to stay unmodified between the check and the usage. 
E.g. in a multithreaded environment. And we don't have a code analysis yet to detect if `bar` is passed somewhere outside of `foo`.

**Comment by Gama11** [comment]
But this is in loose mode. I don't think it should matter what happens with `bar` there.

**Comment by Simn** [comment]
Agreed, in loose mode this should be same as the `obj.field` case.
