### ISSUE TITLE
[eval] EReg presentation in eval-debugger

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7858]
It would be nice if the debugger could show a string formatted in regex literal style (`~/regex/`), rather than just the class name:

![](https://i.imgur.com/90lwB40.png)

```haxe
class Main {
	static function main() {
		var regex = ~/[0-9]+/g;
		var regex2 = new EReg("[0-9]+", "g");
		trace(regex.match("1"), regex2.match("1"));
	}
}
```

**Comment by Simn** [comment]
I can't find a PCRE function for this so I would have to store the string explicitly...

**Comment by Gama11** [comment]
Is that an issue?

I guess it could be done only when debugging? But it might be neat if it worked for a `EReg.toString()` too.
