### ISSUE TITLE
Macro haxe.Json.parse(string_with_unicode) throws - dump/decoding_error.txt

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7868]
Seems like there's a unicode / utf-8 problem decoding JSON from a macro. Using Haxe 4-RC1 on linux:

Test.hx:
```haxe
class Test
{
  public static function main()
  {
    // The runtime version works:
    // var t = '{"desc":{"foo": "Has unicode 2 × 2"}}';
    // var obj = haxe.Json.parse(t);

    // The macro version throws:
    var obj = gen();

    trace('Hello: '+obj.desc);
  }

  private static macro function gen()
  {
    var t = '{"desc":{"foo": "Has unicode 2 × 2"}}';
    return haxe.Json.parse(t);
  }
}
```

```
>haxe --version
4.0.0-rc.1+1fdd3d5

>haxe -x Test
Test.hx:10: characters 15-20 : There was a problem decoding (see dump/decoding_error.txt for details)

>cat dump/decoding_error.txt
{
	expr: null <- expected value
	pos: null <- expected value
}
line 2: expected value
line 3: expected value
```

This is a smaller testcase from my full JSON file, in which `haxe.Json.parse` throws: `Uncaught exception Invalid char null at position 279329` -- but there is an ASCII character at that (byte) position in the file. Maybe it's not counting correctly due to unicode characters?

**Comment by nadako** [comment]
What does this return with a non-unicode JSON? Because you have a mistake here - you have to return an expression (`{expr: ..., pos: ...}` as the compiler complains) from a macro function, not a value. Try `return macro $v{haxe.Json.parse(t)}` - that will try to convert a macro-time value into an expression.

**Comment by Simn** [comment]
Yep this is a pebcak situation. :P

Still, I've changed the error message to mention the expected type so it's hopefully a bit clearer now:

```
source/Main.hx:8: characters 13-18 : Expected Expr but got {desc: {foo: Has unicode 2 × 2}} (see dump/decoding_error.txt for details)
```

**Comment by jcward** [comment]
Hmm, seems I typoed in trying to isolate the issue from my greater project. Ah well, I don't have any more time to spend on it.
