### ISSUE TITLE
[js][es6] Unexpected "Must call `super()` constructor before accessing `this`"

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#7869]
Hey @nadako, just want to say absolutely _loving_ the new es6 class output! It's been working well for me so far but I've run into an issue with a class like this:

```haxe
class Subclass extends js.html.Uint8Array {

	var member: Float;

	function new() {
		super(1);

		js.Browser.window.addEventListener('mousemove', () -> {
			member = 5;
		});
	}

}
```

The error is 
```
src/Main.hx:13: lines 13-19 : Must call `super()` constructor before accessing `this` in classes derived from an extern class with constructor
```

It seems to happen when a member is accessed within a closure

For example, it also happens with
```haxe
	var member: Float;
	function new() {
		super(1);

		function x() {
			member = 2;
		}
         }
```
(Haxe build 4eefb9795903f30bfb77dc27a5ed6c4bced548ff)

**Comment by nadako** [comment]
Err, `var _gthis = this` gets in the way here. @Simn why is that generated at the very top of the function instead of before the first place where it's needed?

**Comment by Simn** [comment]
Because that's how it's implemented at the moment.

**Comment by Simn** [comment]
I'm a bit nervous about changing this in the typer. While we can easily detect the place where it's needed at the time of typing, I'm not sure if there could be transformations which require a `this` variable earlier. It then makes sense to handle this during post-processing, at a point where we can be sure that nothing inserts itself before our `this` variable.

We might even want to handle this in the generator itself to avoid an extra filter.

**Comment by Simn** [comment]
Then again, given that this is a normal variable, I don't think anything could be inserted there anyway.

**Comment by Simn** [comment]
That should do it. Assigning to nadako to clean up after me and add a test.

**Comment by sonygod** [comment]
https://community.haxe.org/t/js-es6-must-call-super-constructor-before-accessing-this-in-classes-derived-from-an-extern-class-with-constructor/2870
