### ISSUE TITLE
[analyzer] local dce is not perfect :-)

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7874]
```haxe
class Main {
	static var v = false;
	static function main() {
		if (v && v) {
		}
	}
}
```
generates
```js
Main.main = function() {
	Main.v && Main.v;
};
```

**Comment by Simn** [comment]
That has nothing to do with the analyzer or local DCE.

It also only holds in a single-threaded environment because your field is mutable.

**Comment by nadako** [comment]
I think this should still be removed because the check is pure and the then block is also pure (empty in this case).

**Comment by Simn** [comment]
I see, I thought your point was that you check the same thing twice.

**Comment by nadako** [comment]
Yeah, sorry I wasn't very clear. I actually noticed this because of google closure warnings for a chain of useless pure checks of different things, which originally had a block with a `trace` which was removed by `--no-traces`, but I reduced to this minimal sample :)
