### ISSUE TITLE
[js] do not add abstract impl classes to $hxClasses

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#7879]
There's no need for abstract impls to be accessible via `Type.resolveClass`, right?

```js
$hxClasses["_Test.A_Impl_"] = _$Test_A_$Impl_$;
```

**Comment by nadako** [comment]
Same with `__name__` I think.

**Comment by nadako** [comment]
In general I think we should generate abstract impls as simple objects:

```
var A_Impl = {
    someFunc: function() ...,
    get_someVar: function() ...
}
```

**Comment by nadako** [comment]
@Simn it should be safe to use the abstract type's own pathname in the generators, right?

So if I have `abstract A(Int) { function f() }` I can just generate `var A = { f: function(this1) {} }` in JS and don't fear name clashes?

**Comment by Simn** [comment]
Not sure about `@:coreType`. Probably depends on the generator...

**Comment by nadako** [comment]
`@:coreType` are the ones without haxe-generated implementation at all, right?

**Comment by Simn** [comment]
Not necessarily, they can have an implementation.

**Comment by nadako** [comment]
OK let's talk about it more when I get home:)
