### ISSUE TITLE
Expression macro doesn't get called in display mode, even when containing completion point.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7885]
Here's a pretty minimal example:

![completion](https://user-images.githubusercontent.com/509501/53466473-6c498e80-3a52-11e9-8aef-bb0fe6f38dd5.gif)

As you can see, diagnostics trigger the macro just fine, but for completion it's skipped.

**Comment by Simn** [comment]
I think I was too quick to fix #7699. The question is if this should give any completion if the macro doesn't type it. And considering our typing rules for macro arguments, I'm thinking that it should not.

**Comment by back2dos** [comment]
Well, the example is a bit contrived. I think the correct behavior would be to:

1. call the macro
2. give completion iff the macro returns an `EDisplay`.

**Comment by Simn** [comment]
Yes but the question was if we should do anything special for arguments to the macro-call. The problem here occurs because I've changed it to check for `EDisplay` in the call arguments, but thinking about it now that seems to be wrong.
