### ISSUE TITLE
Haxe 4 - Compiler.getDefine() in macro throws Uncaught exception macro-in-macro

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7893]
I'm going to assume this is as-designed, so I'll go ahead and close this bug. But file it as a cookie crumb for others facing the issue in Haxe 4 migration.

In Haxe 3.4.7, you could call `Compiler.getDefine()` from inside a macro, or from regular code.

In Haxe 4.0.0, you can no longer call `Compiler.getDefine()` from inside a macro -- it results in `Uncaught exception macro-in-macro`.

**Resolution:** From within a macro, instead of `Compiler.getDefine("foo")`, you now need to call `Context.getDefines().get("foo")` for an equivalent result. Outside a macro, you still use `Compiler.getDefine()`.

I assume this is due to more strict rules wrt macro-in-macro calls.

**Comment by Gama11** [comment]
>`Context.getDefines().get("foo")`

That seems a bit awkward, there's `Context.definedValue()`. In fact, `Compiler.getDefine()` is just a macro that calls that.
