### ISSUE TITLE
Get all values of enum abstract.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7896]
It would be nice to have a way to extract all values of an `enum abstract`. 

My suggestion would be `static public final allValues:haxe.ds.ReadOnlyArray<TheEnumAbstract> = [...];`. Simn said something about it being useful, but it shouldn't be relying on "random names", so I'm putting this out here for discussion.

My other idea was to explicitly allow `for` loop over `enum abstract`, where the compiler could even decide to unroll the loop, but it's perhaps a bit too far on the magic end of things.

**Comment by Gama11** [comment]
If that does happen, `values` seems like a much nicer name than `allValues`.

**Comment by kevinresol** [comment]
FYI, I have a library but it is macro-based https://github.com/kevinresol/list-enum-abstract

**Comment by nanjizal** [comment]
Recently was interested in all in a typedef's with ability to list **optional** ones separately, would be good to have something like this added to https://api.haxe.org/Type.html also I be nice to allow **clone** of typedef. Only mention incase if enum abstracts are consider the api is considered to make it consistant.  I realize you can do this stuff with macros or rtti but seem quite useful.

**Comment by kevinresol** [comment]
Btw, does that mean we cannot have an enum entry named `values`/`allValues` if this is implemented?

**Comment by Simn** [comment]
Yes that's what I mean when I say that we shouldn't use random names like that.

**Comment by back2dos** [comment]
Not sure what makes a name "random", but the choice here was quite deliberate:

1.  it is lower case, which enum values shouldn't be
2.  I did pick `allValues` because `values` (being much nicer) seems a much more likely name in general

**Comment by nanjizal** [comment]
following getClassFields convention the following would be useful on the Type class
```
getAbstractEnumFields
getTypedefFields
getClassFields
getAbstractFields
```

**Comment by Simn** [comment]
I'm not criticizing your ability to name things, but I question if it's okay to use _any_ magic name like that. I don't think this is good API design, and it's also not in-line with anything else we have.

**Comment by RblSb** [comment]
It is not possible to create compiler supported `EnumAbstractTools` class with `getName/getIndex/getValues/etc`? Can `Abstract` be generic type like `Enum` for static extensions and other things? (sorry for stupid question)

**Comment by nadako** [comment]
I just wanted to add that I'm against having a magic name (at least not prefixed with `_hx_` or something), because this is not always possible:

> 1. it is lower case, which enum values shouldn't be

For example sometimes it is desired to follow some specific naming rules when writing an extern library, so people can easily find stuff and/or port their code. When working with lua/python it's often the case that the naming rules are `lower_snake_case`.

---

What exactly is wrong with compiler/macro supported `Type.getAbstractEnumVariants`?

**Comment by Simn** [comment]
> What exactly is wrong with compiler/macro supported `Type.getAbstractEnumVariants`?

That would also be my preferred solution, but we'll need a new constraint type for that first.

**Comment by ncannasse** [comment]
I think that we should keep this feature for macros, and not generate extra metadata for each enum abstract. Unlike traditional enums, the enum abstract have a very high number of allowed runtime values, much more than what their definition actually allows.

Also, this would not make sense for instance with the semantics of some special definitions such as:

```haxe
enum abstract Special(Int) {
    var None = 0;
    var A = 1;
    var B = 2;
    var Both = 3;
}
```

**Comment by Simn** [comment]
<strike>I don't think the idea is to generate anything, but instead query it from the compiler statically.</strike>

I'm not making any sense.

**Comment by nanjizal** [comment]
Can we pass the abstract type to a function, how do we type it, see commented out wishful code.
http://try-haxe.mrcdk.com/#96a5A

**Comment by nanjizal** [comment]
It's quite useful to be able to extract abstract enum names for use in user API's and also to setup so they could be called via hScript, similar with Typedef'd structures as I mentioned earlier, sure the runtime would be heavy used this way.  Obviously with more boiler plate it can be worked round.

**Comment by ncannasse** [comment]
I think this should be turned into a language proposal or closed. I'm personally in favor not to generate anything here and let the macro deal with it.

**Comment by Simn** [comment]
Agreed, this would have to come as an evolution proposal.
