### ISSUE TITLE
What happend to genericBuild?

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#7905]
```haxe
#if !macro
typedef Huh = GenericBuild<Int>;
@:genericBuild(Test.GenericBuild.build())
#end
class GenericBuild<T> {
  #if macro
  static var counter = 0;
  static function build() {
    var name = 'Cls${counter++}';
    var ret = macro class $name {
      public function new() {}
    }
    haxe.macro.Context.defineType(ret);
    return haxe.macro.Context.getType(name);
  }
  #end
}

class Test {
  static function main() {
    #if !macro
    $type(Huh.new);// Void -> Cls0
    #end
  }
}
```

In haxe 3, this correctly reports `Void -> Cls0` ... in 4.0.0-rc.1 this fails saying that `Cls0 does not have a constructor`. And to top it all off, diagnostics with preview.3 gives me this:

![huh](https://user-images.githubusercontent.com/509501/53639652-19c2ca80-3c2a-11e9-8494-290dc55533bb.png)

All that said, I have projects with rc.1 / recent nightly that use far more complex genericBuild macros just fine (via tink_json for example). I'm confused.

**Comment by Simn** [comment]
That looks like some regression from the `@:eager` change.

**Comment by Simn** [comment]
This is probably not about `@:genericBuild` but about `defineType`. There's a pass problem involved here because we trigger the build while in PTypeField, but after the type has been added, nobody ever flushes PBuildClass before trying to look up the field.

Our pass handling makes my head hurt a bit.

**Comment by Simn** [comment]
@ncannasse: Is this supposed to work? If so, who is supposed to flush the `PBuildClass` pass? This used to be done in `typing_timer` on the `Context.getType` call, but now it only does that if `need_type = true`, which isn't the case for `getType`.

**Comment by ncannasse** [comment]
Before we return from the generic build call we need to flush our context based on the current pass. Here we're in a PExpr pass so all the PBuildClass should have been done already before returning from `Hue` resolution.

**Comment by Simn** [comment]
> Here we're in a PExpr pass so all the PBuildClass should have been done already before returning from Hue resolution.

That's not really how this works though because we set `ctx.pass` and define a new type. I wonder if we should do something here:

```ocaml
	let exit() =
		t();
		ctx.com.error <- old;
		ctx.pass <- oldp;
		ctx.locals <- oldlocals;
	in
```

Specifially, how about after setting `ctx.pass <- oldp` we flush whatever pass `oldp - 1` represents? In fact, shouldn't we always do that when setting `ctx.pass`?

**Comment by Simn** [comment]
Never mind, that doesn't actually fix the issue...

**Comment by ncannasse** [comment]
I think new types have their separate ctx anyway

**Comment by Simn** [comment]
My original analysis was correct: While it's true that we trigger all this in `PTypeField` (on the `Huh.new`), we're entering `PBuildModule`/`PBuildClass` via `load_instance` and then nobody ends up flushing this. So ultimately it's the same old problem we've always had where we don't flush `PBuildClass` before accessing the type's structure.

And I'm still not quite sure how to address this properly...

**Comment by ncannasse** [comment]
That's why I'm saying : when we call defineType, before we return, let's just flush according to our current context pass.

**Comment by Simn** [comment]
Yes but our current context pass is `PBuildClass` because that's where we entered the macro. We can of course always flush that, but I'm not sure if that's correct.

**Comment by ncannasse** [comment]
I meant, when we call the genericBuild macro, we are in PTypeField, so we should flush the previous pass (in order of priority) which I think is PBuildClass after returning from the macro and before getting back at typing.

**Comment by Simn** [comment]
I know what you mean, what I don't know is where to actually do this. The typing order isn't clear to me because the typedef delays evaluation of its rhs because of the `@:eager` change. However, the `GenericBuild<Int>` is still executed before we type the expression. It's just that after defining a new type we never flush the structure building pass.

**Comment by Simn** [comment]
I have a question about the compiler pass design: If we're currently running task F1 of pass P1 and we call `delay` for task F2 of pass P0 (higher priority), should we really finish F1 first or should we execute F2 immediately?

**Comment by ncannasse** [comment]
@Simn this should not really happen. 

The fact that we delay a task of pass P0 means that we are actually already in "P0 mode", so our current context should have been cloned and set to P0. 

Here's what should happen:

running F1 (context A in P1) --> loading type --> create context B in P0 --> load other types --> delay P0 tasks --> done all P0 delays --> return to loading type --> flush all P0 tasks --> return to running F1

**Comment by Antriel** [comment]
I'm seeing a similar issue in 4.2.5, is it possible the flush also needs to happen on `Context.followWithAbstracts(t)`?
