### ISSUE TITLE
[server] [memory] some modules are reported as using a lot of memory

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7908]
When compiling vshaxe once, the memory overview shows some std files as rather large:

![code_2019-03-03_11-02-09](https://user-images.githubusercontent.com/634365/53693657-ea37cd80-3da3-11e9-9e79-915854382411.png)

There are two possible causes here:

1. They actually are this fat
2. Memory diagnostics are broken

**Comment by Simn** [comment]
I suspect it's 2. because the total reported cache size is only 161.4 Mb, and that includes all other contexts.

**Comment by Simn** [comment]
The js.Boot problem is caused by `@:ifFeature` because the memory exploration doesn't ignore that. BalancedTree, Type and Reflect are still fat though.

**Comment by Simn** [comment]
Never mind, that just causes it to ignore its own classes... So there's some other problem altogether.

**Comment by Simn** [comment]
Something is broken:

![code_2019-03-03_14-25-32](https://user-images.githubusercontent.com/634365/53695784-3c86e780-3dc0-11e9-8151-ae1b1c4f1451.png)

Look at the memory for `__string_rec`, `remove` and `enumEq`. They have one thing in common: They are the only functions in their respective classes that have a `try ... catch`.

**Comment by Simn** [comment]
It's `JsExceptions.inject_callstack` adding a reference to `haxe.CallStack` without adding a proper module dependency.

**Comment by nadako** [comment]
Uh-oh...

**Comment by nadako** [comment]
Wait, but how that allocates so much memory? It's a single compilation even, right?

**Comment by Simn** [comment]
It doesn't allocate that much. The problem is that the missing dependency causes memory detection to go wrong because it doesn't stop when coming across the `haxe.CallStack` module, and then goes on to pick up everything `haxe.CallStack` references (recursively). However, I "think" any missing reference could leak, so it's still important to fix.

**Comment by Simn** [comment]
There are still other problems like this:

![code_2019-03-03_15-25-11](https://user-images.githubusercontent.com/634365/53696564-8c69ac80-3dc8-11e9-856b-21ca50f0e1b3.png)

I have no idea how this small class can cause such memory diagnostics...

```haxe
package adapter;

import protocol.debug.Types;

extern class ProtocolServer {
	function sendEvent<T>(event:Event<T>):Void;
	function sendResponse<T>(response:Response<T>):Void;
}
```

Its dependencies are `StdTypes`, `String` and `protocol.debug.Types`, which seems fine (though I don't know where `String` comes from).

**Comment by Simn** [comment]
Now I cannot reproduce this anymore...

**Comment by Gama11** [comment]
Some of these also seem a bit fishy:

![](https://i.imgur.com/qLJFZxm.png)

**Comment by Simn** [comment]
Any particular types or fields there that are reported as too big?

**Comment by ncannasse** [comment]
There was a leak detection at some point that could say which modules were
referenced in memory but not in dependencies, maybe you could allow to list
these using a simple command so it's more easy to track them down?

**Comment by Gama11** [comment]
For instance here, there's two methods with ~1 MB each.. isn't that a bit much? They're not exactly the shortest ones, but still?

![](https://i.imgur.com/3GJNq3v.png)

Does inlining play a role maybe?

**Comment by Simn** [comment]
I wanted to port the leak detection but I didn't understand how it works. Will look at it again tomorrow.

**Comment by Simn** [comment]
These problems no longer occur, so I'll go ahead and close here.

**Comment by Gama11** [comment]
So a single type using 5.9 MB is normal? That file isn't that big (1.7 kLoC), there's definitely similar ones that use a lot less in this example.

**Comment by Simn** [comment]
I cannot comment on that if all I have is an image. If anything the problem is likely that the <strike>error</strike>memory detection is wrong. This stuff is hard to get right with all the possible references, and I currently don't have time to look into this.

**Comment by Gama11** [comment]
Well, I'm assuming this sort of thing can't really be isolated, so not sure what to provide other than an image. :) It's just a standard Flixel project FWIW.
