### ISSUE TITLE
Everything depends on you, String

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7909]
I noticed that every single module has a dependency on String, which I found curious. It comes from this piece of code in typeloadModule.ml `type_types_into_module`:

```
(* this will ensure both String and (indirectly) Array which are basic types which might be referenced *)
ignore(load_core_type ctx "String");
```

I get that we want to make sure String (and Array) is loaded, but I don't see why we would have to load it from every module.

**Comment by Simn** [comment]
> every single module

I lied, `StdTypes` is the one module that does not depend on String.

**Comment by ncannasse** [comment]
The problem is that we might have constant Strings that are typed without the dependency to String module actually being set (we directly use tstring/tarray). Not sure if that's a real problem or not, but the comment seems to indicate that was a fix for something.

**Comment by Simn** [comment]
You originally added it here: https://github.com/HaxeFoundation/haxe/commit/7671ee3860851e4b4306b109bbafa1edeadf3461

And then moved it here: https://github.com/HaxeFoundation/haxe/commit/fdd0872a7e5160b14443d007a3ec7bf8e598e911

Unfortunately, it doesn't reference any issue. But yes, I can see why simply grabbing `tstring` could lead to issues here. It is even used by some generators, so we couldn't just fix our dependencies easily. I guess it's better to not touch this then.
