### ISSUE TITLE
Type inference not [always] working with @:overload fields

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#7913]
I first had this issue when using the new `js.html` externs in haxe 4 rc1, when using `DOMElement.scrollIntoView` [[0]].

The issue can be reproduced without JS externs too, like that ([[1]] for a try-haxe):

```haxe
class Test {
  static function main() {
    A.test({foo: Bar}); // Unknown identifier : Bar
  }
}
```

```haxe
class A {
  @:overload( function(a:{foo:Foo}) : Void {} )
  public static function test(a:Bool) : Void {}
}

// This needs to be in a different module than `Test`
enum Foo { Bar; }

// Same error with:
// enum abstract Foo(String) { var Bar = "bar"; }
```

This works fine if the primary signature is `function(a:{foo:Foo}) : Void` and the overloaded one is `function(a:Bool) : Void`.

This issue makes using modified js.html externs problematic (although not impossible, it works by either importing the enum types or adding a `ECheckType`, but it's annoying to do). While this issue is not a regression in itself, the js.html extern update generates regression(s) because of this.

[0]: http://try-haxe.mrcdk.com/#627F3
[1]: http://try-haxe.mrcdk.com/#78748

**Comment by haxiomic** [comment]
I agree this should be fixed at the compiler level but given there's a lot in the queue I'll tweak the extern generator to reorder overloads (this won't fix 100% of cases but should fix most :))

**Comment by Simn** [comment]
Part of the problem here is this commit by @nadako: https://github.com/HaxeFoundation/haxe/commit/a438571ccff868d28f0f987b365e05d04f5d38ac

This specifically prevents overload recovery in the case of unknown identifiers.

**Comment by Simn** [comment]
This was fixed in https://github.com/HaxeFoundation/haxe/commit/7fdac0a2381f636aeddfdcd345e5eaea3725469c
