### ISSUE TITLE
[Haxe 3.4.7] Std.is behaves differently depending on the 'generic' meta tag

### ISSUE THREAD

**Issue by kro13** [HaxeFoundation/haxe#7914]
```haxe
class Test {
    static function main() {
        var a:A<Int> = new A();
        trace(Std.is(a, A));//false
        
        var b:B<Int> = new B();
        trace(Std.is(b, B));//true
    }
}

@:generic class A<T> {
    public function new() { }
}

class B<T> {
    public function new() { }
}
```
It seems to be the result of that the compiler creates distinct classes per type, when the 'generic' meta tag is used. But it also seems right that both cases should behave the same way. [Haxe 3.4.7]

**Comment by Simn** [comment]
Yes this is expected because it indeed creates a distinct instance per type-parameter combination. I suppose we should clarify in the docs.

**Comment by kro13** [comment]
I agree, if this behaviour was stated in the docs there would be no questions. Otherwise it could seem as a bug from user perspective.

**Comment by nadako** [comment]
Yeah it looks like it should work, but mostly because `Std.is` is stupid. We really need a proper syntax that handles complex types with type parameters, like `cast` does.

**Comment by benjamin-stern** [comment]
Is there any workaround for this issue of Std.is? I've got an issue with this now.

**Comment by RealyUniqueName** [comment]
You can create an empty interface and check for it:
```haxe
interface IA {}

@:generic class A<T> implements IA {
    public function new() { }
}

var a:A<Int> = new A();
trace(Std.is(a, IA)); //true
```

**Comment by benjamin-stern** [comment]
Ok thanks that's a nice idea.
