### ISSUE TITLE
[php] Improve the generation of anonymous objects declarations

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7916]
```haxe
var i = 2;
var o = {hello:1, world:i}
```
Currently generates
```php
$i = 2;
$o = new HxAnon(["hello" => 1, "world" => $i])
```
But this performs 50% faster:
```php
$i = 2;
$o = new class($i) extends HxAnon {
  public function __construct(&$i) {
    $this->hello = 1;
    $this->world = $i;
  }
}
```
PS: don't forget to remove constructor declaration from `php.Boot.HxAnon`

**Comment by nadako** [comment]
does this also support random field adding/deleting? _IIRC_ it has to be supported by anon object values (which is unfortunate).

**Comment by Simn** [comment]
Yeah Reflect.deleteField is a real party-pooper...

**Comment by RealyUniqueName** [comment]
> does this also support random field adding/deleting?

Yes adding/deleting fields is supported.
