### ISSUE TITLE
The display tests are retarded

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7917]
We start a new haxe process for every request, which is stupid and slow. I don't really know how to change this for the old protocol though because we rely on `-D display-stdin`.

**Comment by Simn** [comment]
Hoping for some @nadako advice because I feel like I'm missing something obvious again.

**Comment by nadako** [comment]
I'm not sure what is the issue? Doesn't it work like described in #5120?

**Comment by Simn** [comment]
> For the compilation server this introduces a (backward-compatible) protocol feature. To pass the stdin file to a comp server, one should send \x01 after the hxml parameters, then contents of a file, then the final \x00.

That may have been the information I was looking for.

**Comment by Simn** [comment]
I can't get this working with our Process API, so I guess we'll have to port this nodejs again. In that case I'll just keep the display tests disabled until we have a usable solution for this.
