### ISSUE TITLE
[nullsafety] recursive local function vs. null safety

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7918]
I don't think there's any logical reason why this shouldn't compile:

```haxe
@:nullSafety
class Main {
	public static function main() {}

	var foo:Null<String>;

	function new() {
		function recurse() {
			if (foo != null) {
				recurse();
			}
		}
	}
}
```

The error position here is really confusing:

![](https://i.imgur.com/2D9K2pY.png)

I'm assuming this is related to the access through `_gthis`. It's fine if the local function isn't recursive, presumably because `recurse`'s assignment isn't delayed then. Dump:

```haxe
function new() {
	var recurse = null;
	var _gthis = this;
	recurse = function() {
		if ((_gthis.foo != null)) recurse();
	};
}
```

**Comment by Gama11** [comment]
(even if it turns out this is just a duplicate of https://github.com/HaxeFoundation/haxe/issues/7853, the confusing error reporting is still a problem here)

**Comment by RealyUniqueName** [comment]
Are you sure you are using the latest dev Haxe? 
I cannot reproduce this.

**Comment by Gama11** [comment]
Wait, what, now I can't anymore either (still an issue in the code I isolated it from though)... I wonder if the compilation server was involved in breaking my repro case somehow.

**Comment by Gama11** [comment]
Wtf, this only reproduces on JS with `-D js-es=6`... @nadako!?

**Comment by RealyUniqueName** [comment]
I got it with `-D js-es=6` too.

**Comment by nadako** [comment]
it's probably related to @Simn's `_gthis` change for #7869

**Comment by RealyUniqueName** [comment]
I hacked it by detecting expression sequence `var fn = null; var _gthis = this; fn = function() ...`, but the proper way is probably to add a special `tvar_kind` for variables generated by local named functions.

**Comment by Simn** [comment]
> the proper way is probably to add a special tvar_kind for variables generated by local named functions.

But it already does that, these vars should be `TVOLocalFunction`.

**Comment by RealyUniqueName** [comment]
Didn't know that. Thanks!
