### ISSUE TITLE
Assigning another function to local named function should error

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#7920]
```haxe
public static function main() {
    function local() {}
    local = () -> trace('wtf'); //no compilation error
}
```
3.4 also doesn't emit a compilation error here.

**Comment by Aurel300** [comment]
Shouldn't this only error if the function is declared with `final`? ^^

**Comment by Gama11** [comment]
Why? It's not like you can do that at field level.

If anything, it should only not error if declared as `dynamic`. ;)

**Comment by RealyUniqueName** [comment]
If you want to alter local function declare it like `var local = function() ...`

**Comment by Aurel300** [comment]
I suppose I was thinking of a local `function` declaration as being equivalent to `var (name) = function ...`, then `final` would make it a `final (name) = function ...`. But I can see how it's maybe more useful to think of it similarly to field-level functions.
