### ISSUE TITLE
Match on variable name

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7921]
Today I was asked why the following now gives a warning:

```haxe
enum E<T> {
   None;
   Some( v : T );
}

class Test {

static function foo( v : E<Int> ) {
    var a = None;
    return v.match(a); // warning
}

static function main() {
    trace(foo(None)); // true
    trace(foo(Some(55)); // true too !!!
}

}
```` 

I think the match should actually be an error here, given it's always true and can induce the confusion between match and equals (which is the original cause of the problem here)

**Comment by ncannasse** [comment]
And I'm glad it's not a regression : the match was always returning true since 3.4.x ;)

**Comment by Simn** [comment]
I'm pretty sure this actually is a regression from some Haxe version.

**Comment by Gama11** [comment]
3.2.1 gives this:

```
Main.hx:9: characters 9-16 : This pattern is unused
Main.hx:9: characters 17-18 : Capture variables are not allowed
```

**Comment by ncannasse** [comment]
By "regression", I meant that it never worked as Type.enumEq would have.
