### ISSUE TITLE
[display] Invalid package error position spans entire class

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7929]
This might be bit specific to haxe/std, but it's quite stupid:

![code_2019-03-06_09-19-04](https://user-images.githubusercontent.com/634365/53866048-e77de800-3ff0-11e9-94a0-1c724ee1e148.png)

We have to check why it thinks the error position is on the class because that seems very random.

Note that I'm fine with the error showing up due to the special semantics of our std package structure. I just don't want it to underline my entire code.

**Comment by Simn** [comment]
I don't remember why exactly but this doesn't happen anymore.

**Comment by Gama11** [comment]
I think you fixed that in 25cae7b?
