### ISSUE TITLE
[display] diagnostics miss errors from Haxe's post-processing

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7931]
```haxe
class Main {
	static function main() {
		var s:String;
		s += "test";
	}
}
```

This fails to compile with `Local variable s used without being initialized`, but there's no diagnostics error for it.

Seems like this is not a regression / has always been this way.

**Comment by Simn** [comment]
Any error from our post-processing is missed because we don't run it for diagnostics.

We can explicitly run the var init check and null-safety in diagnostics mode. They are early filters, so it should be fine.

**Comment by Simn** [comment]
By the way, do we have diagnostics tests now?

**Comment by Gama11** [comment]
Yep, although just a single one that checks that there are _no_ diagnostics. So no `hasDiagnostics()` helper function or anything like that yet.

https://github.com/HaxeFoundation/haxe/commit/b20cb70290da8ae78bebcf75442d06dad9613752#diff-d56e6b80704188e7ea0e5d667a79876b

**Comment by Simn** [comment]
Not easy to fix because we don't have access to a good error function in post-processing. This is going to require some refactoring.

**Comment by Gama11** [comment]
I assume "Type name should start with an uppercase letter" is one of these too?

**Comment by Simn** [comment]
No, that's a parser error. But it might be a hard error still.

**Comment by Simn** [comment]
I kinda want to solve this for 4.1, but it's not so easy. I think we can do something like `try check_local_vars_init with Error _ (* turn into diagnostics *)` in the diagnostics preparation step. That way we at least get one error per method.

However, the more general problem here is there is various post-processing that could cause errors and we don't want to run all of that for diagnostics. Unfortunately, this then means that diagnostics will never 100% match compilation errors.

**Comment by Gama11** [comment]
>However, the more general problem here is there is various post-processing that could cause errors and we don't want to run all of that for diagnostics.

We don't? What's an example of something that would be too expensive to run?

**Comment by Simn** [comment]
The analyzer for sure, but this is more about the sum of the parts. Our post-processing is not designed to just detect errors, it's a huge AST transformation framework which just happens to spit out some errors in the process.

We should go through the individual steps and check which ones might report user-facing errors (not the `assert false` kind of stuff that comes from internal problems). Then we can maybe look into isolating these out and run them as part of diagnostics.

**Comment by Simn** [comment]
This has been addressed by #11220. I'll go through the filters and see that I add some tests.

**Comment by Simn** [comment]
Adding sane tests for this is kind of blocked by #9134.

**Comment by RblSb** [comment]
Filters like null safety not yet here, this or https://github.com/HaxeFoundation/haxe/issues/7933 should be reopened?

**Comment by kLabz** [comment]
> Filters like null safety not yet here, this or https://github.com/HaxeFoundation/haxe/issues/7933 should be reopened?

Is that still a thing ? Do you have a way to repro ?

**Comment by RblSb** [comment]
I think it is, see this example, but for diagnostics check
https://github.com/vshaxe/vshaxe/issues/509

**Comment by kLabz** [comment]
Indeed, thanks!

**Comment by kLabz** [comment]
Interestingly, it reaches the error but the reporting isn't working properly.
