### ISSUE TITLE
[display] diagnostics miss some parser errors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7932]
Diagnostics are now meant to report parser errors, but they don't in this case:

```haxe
class Main< {
	public static function main() {
		
	}
}
```

On compilation, there's a proper error:

```
source/Main.hx:1: characters 13-14 : Unexpected {
```

**Comment by Simn** [comment]
This fails now.

Would be nice to have a test for it...

**Comment by Gama11** [comment]
I'll look into adding one. That's even a much better compiler error than before! :)
