### ISSUE TITLE
[parser] empty error message for missing )

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7935]
```haxe
class Main {
	public static function main() {
		trace(;
	}
}
```

```
>haxe -main Main --interp
Main.hx:3: characters 9-10 :
```

This used to error with:

```
Main.hx:3: characters 9-10 : Unexpected ;
```

**Comment by Simn** [comment]
wat...

**Comment by Simn** [comment]
Fixed, needs test.

There are some different code paths for display/non-display mode in the parser, so we'll have to fiddle a bit to make sure compilation and diagnostics give the same error message.

**Comment by Simn** [comment]
Actually, I don't want to insist on them being equal in all cases. Compilation parsing is optimized for performance, so if it gives less ideal (but still correct) messages in some cases I'm fine with that.

**Comment by Gama11** [comment]
Sure, as long as there aren't cases where you get an error on compilation that doesn't happen in diagnostics or vice-versa.
