### ISSUE TITLE
[js] $fid value sharing

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7936]
I hit into some weird and very hard to debug error that was related to `$bind` function counter `$fid` being reset, this occured while loading some scripts dynamically. As the result, two methods on same object had the same __id__, leading to $bind returning the wrong closure.

I fixed it in js-classic here: 91dac26cb95dfb891c9bc46fff81d6927e402cc9

However I think the error can still reproduce without -D js-classic. The problem being that when you have several modules, while they cannot call each other directly they can exchange instances (through interfaces or other mechanisms), and thus having for each module its own `$fid` can make things go wrong. I think this is a particular case that would require to put $fid in "exports" so all modules $bind implementations references the same variable.

Ping @nadako @elsassph

**Comment by nadako** [comment]
yeah if we want multiple haxe modules to interop between each other we have to make them share `$fid` and maybe some other global support context. it should be possible but might require some design.

alternatively we could use module-specific field instead of `hx_closures__` and such (also `__id__` for objectmap?), but it's dirty and can lead to some unnecessary data duplication.

**Comment by elsassph** [comment]
Maybe `hx__closures__` could be an array and `$bind` would use the length of it.

**Comment by elsassph** [comment]
My project works with this `$bind` implementation:

**Edit: this doesn't work sorry :D**

```javascript
function $bind(o, m) {
    if (!m) return null;
    var f;
    if (!o.hx__closures__) {
        o.hx__closures__ = [];
        m.__id__ = 0;
    } else {
        if (m.__id__ === undefined) m.__id__ = o.hx__closures__.length;
        else f = o.hx__closures__[m.__id__];
    }
    if (f === undefined) {
        f = function () { return f.method.apply(f.scope, arguments); };
        f.scope = o;
        f.method = m;
        o.hx__closures__[m.__id__] = f;
    }
    return f;
}
```
Edit: optimised for 1st instance bind, 1st method bind, and other cases.

**Comment by nadako** [comment]
Right, or we could get rid of global state :)

**Comment by elsassph** [comment]
What do you mean about the global state?
My proposed reimplementation doesn't use a counter so it will work for multiple JS files, with and without js-classic.

**Comment by elsassph** [comment]
Oh wait there's a problem. The ID is shared across instances. That's doesn't work... I'm probably lucky that it works for my project - and it's a real complex project :D

**Comment by elsassph** [comment]
That's silly but indeed we depend on a global counter if we want to be completely safe when sharing code between different Haxe JS modules... The right way to do it I think is to attach `$bind` to the global state (if not already defined) as a closure with a private counter.

**Comment by elsassph** [comment]
What about:
```
var $bind = $global.$bind = $global.$bind || (function(){
	var $fid = 0;
	return function $bind(o, m) {/*current code*/};
})();
```
It makes `$bind` global without risking to expose the counter variable.

**Comment by ncannasse** [comment]
As a reminder, haxe.ds.ObjectMap.count is also a problem. I think it's better to expose a global $hx_counter and use it for both $bind and ObjectMap.

**Comment by elsassph** [comment]
Yuk then yes code you be using a `$global.$hx_counter`. I'd only suggest the reference to be qualified to avoid scope climbing.

**Comment by Simn** [comment]
This sounds like something we should do for 4.0.
