### ISSUE TITLE
[display] "Can only extend structures" false positive on hover

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7937]
```haxe
class Main {
	static function main() {}
}

typedef FoldingRangeServerCapabilities = {
	var foldingRangeProvider:FoldingRangeProviderOptions & {};
}

typedef FoldingRangeProviderOptions = {}
```

Hovering over `foldingRangeProvider` gives this error:

```
[Error - 13:58:08] Request textDocument/hover failed.
  Message: source/Main.hx:6: characters 27-59 : Can only extend structures
  Code: -32603 
```

Yet the code compiles just fine. It's not a regression, this happens since at least preview 4.

**Comment by nadako** [comment]
> not a regression, this happens since at least preview 4.

i thought we consider anything that appeared after 3.4 a regression :-P

**Comment by Gama11** [comment]
I mean, this syntax didn't even exist then. :)

**Comment by Gama11** [comment]
Oh, the error is even more fun with the old syntax:

```haxe
class Main {
	static function main() {}
}

typedef FoldingRangeServerCapabilities = {
	var foldingRangeProvider:{>FoldingRangeProviderOptions,};
}

typedef FoldingRangeProviderOptions = {}
```

```
[Error - 14:11:13] Request textDocument/hover failed.
  Message: source/Main.hx:6: characters 27-58 : Loop found in cascading signatures definitions. Please change order/import
  Code: -32603 
```

And that one also reproduces with 3.4.7.

**Comment by Simn** [comment]
Works if the two typedefs are swapped.

**Comment by Gama11** [comment]
Hm, I may have isolated this too much, but I still get this error hovering over _anything_ in [this file](https://github.com/vshaxe/language-server-protocol-haxe/blob/master/src/languageServerProtocol/protocol/FoldingRange.hx). The fun part is that the error points to a different file:

```
[Error - 14:58:33] Request textDocument/hover failed.
  Message: server/protocol/src/languageServerProtocol/protocol/Protocol.hx:513: lines 513-838 : Can only extend structures
  Code: -32603 
```

**Comment by Simn** [comment]
I cannot seem to reproduce that...

**Comment by Gama11** [comment]
Hm, that's strange.. I assume you just open `FoldingRange.hx` from the vshaxe workspace and the hover over stuff?

**Comment by Simn** [comment]
Ah, I was in `FoldingRangeFeature.hx`.

**Comment by RealyUniqueName** [comment]
I hovered every symbol in [this file](https://github.com/vshaxe/language-server-protocol-haxe/blob/master/src/languageServerProtocol/protocol/FoldingRange.hx) and couldn't reproduce this issue with the latest dev.
I suppose it's fixed.

**Comment by Gama11** [comment]
Still reproduces for me (on Windows).

**Comment by Simn** [comment]
Does this still reproduce in 2020?

**Comment by Gama11** [comment]
Hmm... can't seem to reproduce it anymore, but that doesn't necessarily mean it's fixed, something in the setup might've changed. Anyway, this seems to be closely linked to https://github.com/HaxeFoundation/haxe/issues/8177, which still reproduces.
