### ISSUE TITLE
[display] more missing diagnostic parser errors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7938]
```haxe
class Main {
	public static fuction main() {}
}
```

Compilation fails with this, but no diagnostics:

```
source/Main.hx:2: characters 16-23 : Unexpected fuction
```

**Comment by Simn** [comment]
This relates to class field resuming and is therefore nothing I want to touch right now/ever.

**Comment by Gama11** [comment]
Hm.. I guess all parser errors on field level are related to that? Such as:

```haxe
class Main {
	public static function main( {
	}
}
```

**Comment by Simn** [comment]
Yes, and there are at least two problems here: One is to get the error when resuming, the other is to get to a state where we report diagnostics in the first place. I think we have to put an exception handler around our entire typing to do this.

**Comment by Simn** [comment]
I realized that we already handle this for the most part. The main problem was the same as in #5306 because we never reached a point where we would emit diagnostics.

I'm now catching `Error.Error` and raise the `Diagnostics` exception if we're in diagnostics mode.
