### ISSUE TITLE
[typer] unhelpful multi-line error ranges for switches in value places

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7947]
If a switch is used in a value place, and one of the cases doesn't return anything, the resulting error spans the entire range of the switch, which is not very helpful.

```haxe
class Main {
	public static function main() {
		var either = haxe.ds.Either.Left(123);
		return switch either {
			case Left(_):
				trace('Some logic...');
				trace('Some logic...');
				trace('Some logic...');
				true;
			case Right(_):
		}
	}
}
```

This affects error reporting both on the command line and in diagnostics:

![](https://i.imgur.com/7KHh835.png)

I think the best-case would be if only the `case` that's missing a return value was marked (`case Right(_):` in this case). The error message could probably even stay the same.

Original issue: https://github.com/vshaxe/vshaxe/issues/267

**Comment by Simn** [comment]
It now uses `case Right(_)` as the position. That's the best we can do because it's the only position we have if there is no case expression.

As a bonus, if you swap the cases it now errors on the `true` instead of the entire case.
