### ISSUE TITLE
[display] missing parser error diagnostic for nested classes

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7948]
Don't laugh, this happened as a result of a copy-paste fail. 🙃 

```haxe
class Main {
	class Main {
	
	}
}
```

This doesn't diagnost, but compilation fails with a parser error obviously.

**Comment by ncannasse** [comment]
@Simn don't trust him, I'm sure he wrote a bot to generate random code and report the cases where parser fail but not diagnostics :D

**Comment by Gama11** [comment]
You're gonna laugh, but that's actually something I considered... should be fairly straightforward...

**Comment by Simn** [comment]
This is going to require adjustments to the field resuming, which I don't want to touch for 4.0.

**Comment by Gama11** [comment]
I'm assuming that this issue also causes no diagnostics to be reported for this (there should be one with `Unexpected }` ):

```haxe
class Main {
	static function main()
		trace("Test");
	}
}
```

**Comment by Simn** [comment]
That one should be much easier to fix because to the parser it's just an extra `}` at a place where a type declaration is expected.

**Comment by Simn** [comment]
I was wrong. The resuming parser skips everything until it finds the next type declaration (because it cannot rely on `{ } ` balance), so it is indeed the same issue.
