### ISSUE TITLE
[display] find references on $type returns strange results

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7961]
```haxe
class Main {
	static function main() {
		$type("");
	}
}
```

When invoking find references on `$type` _twice_ (somehow the first time it returns nothing), some strange / random results are returned:

![](https://i.imgur.com/aczIXBe.png)

**Comment by Simn** [comment]
I kinda want to wontfix this but at the same time I am very curious wtf is happening here...

**Comment by Gama11** [comment]
This doesn't seem specific to `$type` at all actually, it seems that inovking it on any keyword will have the same result.
