### ISSUE TITLE
Metadata doesn't work on Enums

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#7963]
The docs (https://haxe.org/manual/lf-metadata.html) specifically state the metadata can by applied to both the enum declaractions and enum constructors. However, only a `class` is shown in the example code on that page.

If I copy that example to try.haxe.org (https://try.haxe.org/#F8faa), and add an enum with various metadata, I can see in the **JS Source** tab that the metadata specified on the enum simply does not exist in the generated JavaScript. Only the metadata on the MyClass class shows up:

![image](https://user-images.githubusercontent.com/2192439/54048474-264da280-4197-11e9-9aee-a392a0e875c1.png)

I expect to see something like:

```
 Foo.__meta__ = { ... }
```

**Comment by Gama11** [comment]
What you added there is _compile-time_ metadata (prefixed with a `:`), which won't show up in the output.

**Comment by jcward** [comment]
Huh, ok then.

**Comment by Gama11** [comment]
Documented here:

https://haxe.org/manual/lf-metadata.html#compile-time-metadata

**Comment by jcward** [comment]
Perhaps I'll submit a PR for a better example, including Enums, and maybe even a comment about compile-time metadata.
