### ISSUE TITLE
using ClassField as map key hangs compilation on js target

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#7967]
```haxe
class Main {
        static function main() {
                var m = new Map<haxe.macro.Type.ClassField, Array<Int>>();
                trace(m);
        }
}
```

Hangs only on js target compilation.

**Comment by Gama11** [comment]
Not a regression, it seems, I can reproduce it all the way back to 3.2.1.

**Comment by elnabo** [comment]
It might be related to #5785.

**Comment by Simn** [comment]
I don't think it's related because there are no type parameters involved here. It is however very likely the same as #7781.

**Comment by Simn** [comment]
It's not the same after all. This issue reproduces with `ObjectMap`, whereas #7781 doesn't.

**Comment by Simn** [comment]
I'm retarded, it doesn't reproduce with `ObjectMap`.
