### ISSUE TITLE
Profiling data

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#7970]
I found the following when looking at gprof output for haxe:

```
                0.00    0.03  122688/298794      camlAnalyzerTexpr__create_1398 [28]
[17]     3.4    0.00    0.07  298794         camlHashtbl__create_1046 [17]
```

This means that AnalyzerTexpr.create allocates `a lot` of Hashtbl (122688 in my case compared to a total of 298794 for the whole compilation). I'm not sure if they are all used or not, maybe some kind of optim would help here, for instance having a static shared empty Hashtbl until first insert is done (if they are most often empty)

**Comment by Simn** [comment]
We can try using `StringMap` instead.

**Comment by Simn** [comment]
See if that did anything

**Comment by Simn** [comment]
I'll just assume that it did something.
