### ISSUE TITLE
[display] positions of switch subject are off

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7972]
Hover / goto declaration etc don't seem to work properly on complex switch subjects anymore. For instance in this example, hover always highlights the entire expression and doesn't provide docs for the individual components (`Std`, `int()`...).

![](https://i.imgur.com/MgQdwYF.gif)

```haxe
class Main {
	static function main() {
		var foo = 0.0;

		switch (Std.int(foo)) {
			case _:
		}
	}
}
```

It actually seems to have been this way for quite a while (at least since preview 4). However, it does work properly in 3.4.7, so it is a regression.

**Comment by Simn** [comment]
Probably caused by https://github.com/HaxeFoundation/haxe/commit/b3a6dc1824b418c7008718f216b6255a9a0b994f
