### ISSUE TITLE
[display] find references on overriden methods

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#7977]
```haxe
class Main {
	static function main() {
		(null : Parent).update();
	}
}

class Parent {
	public function update() {}
}

class Child extends Parent {
	override public function update() {}
}
```

When "find references" is invoked on `Child`'s `update()` declaration, no results are returned, which is somewhat annoying.

IntelliJ, at least for Java, has a "Do you want to find usages of the base method?" popup for situations like this. I don't think the LSP supports this, but it seems like the sort of thing that might be added in the future, so for future-proofing it would be nice if Haxe accepted a flag to control the behavior here (defaulting to "include base method usages").

**Comment by EricBishton** [comment]
Yes, that is implemented for the intellij-haxe plugin.

**Comment by Simn** [comment]
@RealyUniqueName Is this within the scope of the recent changes you've made?

**Comment by nadako** [comment]
That still doesn't work.

**Comment by nadako** [comment]
Oh wait, VSCode doesn't use the latest changes, so maybe it does :)

**Comment by Simn** [comment]
Yes that's why I'm asking. I see `1 reference` in code lens so this might work if vshaxe sends the correct request.

**Comment by nadako** [comment]
@Gama11 what should we do on vshaxe side regarding this, given that we can't easily ask the user? to me it looks like just requesting all usages through hierarchy is the most useful.

**Comment by nadako** [comment]
Also what still bugs me is that even if we could ask the user it would be very annoying for people that don't use inheritance (much). IIRC it is done right in IntelliJ, where it only asks what to show when there is any difference. I expressed this concern before in https://github.com/HaxeFoundation/haxe/pull/9315#issuecomment-614220102, but it looked like you guys have an idea how to handle that.

**Comment by Gama11** [comment]
>Yes that's why I'm asking. I see 1 reference in code lens so this might work if vshaxe sends the correct request.

Did we even add the parameter to code lens? I thought it was "find references" only...

>to me it looks like just requesting all usages through hierarchy is the most useful.

Agreed.

**Comment by RealyUniqueName** [comment]
This is covered by  #9315

**Comment by RealyUniqueName** [comment]
> Also what still bugs me is that even if we could ask the user it would be very annoying for people that don't use inheritance (much)

I think it's up to IDE to decide on this. IDE could request for decendants by default and provide additional commands for other modes, so that users would use the command they need.
One thing we can do on the compiler side is provide a request kind like "Does this symbol has descendants/parents?" or even a request, which would return full hierarchy.

**Comment by nadako** [comment]
Tested this with the [latest language server](https://github.com/vshaxe/haxe-language-server/commit/2c7aab63c9d99469ce7e9d87a4ce388dda1bfc9e) and it works! \o/ I'll close this one and create separate issues if more stuff comes up.
