### ISSUE TITLE
Socket flags lost after calling connect() on ipv6 address

### ISSUE THREAD

**Issue by realcraig** [HaxeFoundation/haxe#7978]
[This code](https://github.com/HaxeFoundation/haxe/blob/52862239942262c3f83fa8ff00703d7b99cdb6f0/std/cpp/_std/sys/net/Socket.hx#L159-L171) in Socket.hx connect() determines if an ipv6 connection is needed. If so, it destroys the current socket and creates a new socket. In doing so, any flags that were set on the socket prior to the connect() call are lost, specifically, the flags set by these methods:

```haxe
   public function setTimeout( timeout : Float ) : Void {
      NativeSocket.socket_set_timeout(__s, timeout);
   }

   public function setBlocking( b : Bool ) : Void {
      NativeSocket.socket_set_blocking(__s,b);
   }

   public function setFastSend( b : Bool ) : Void {
      NativeSocket.socket_set_fast_send(__s,b);
   }
```

**Comment by ncannasse** [comment]
Hi, I heard you fixed the problem on your side, could you submit a Pull Request ?
