### ISSUE TITLE
private class in haxe 4.0 disallows @:access

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#7980]
In Haxe 4.0 using the private modifier on a class makes that class impossible to get at via @:access. Not sure if this is desirable or not, but it sure makes extending some parts of Heaps tricky! e.g. @:access(h2d.Graphics.GraphicsContent) does not allow it to become visible for use as a superclass, for example. I think if @:access is allowed for private fields it should also be allowed for private classes.

**Comment by Gama11** [comment]
I don't think that's specific to Haxe 4, it's always been that way:

- https://github.com/HaxeFoundation/haxe/issues/4210
- https://github.com/HaxeFoundation/haxe/issues/5731

**Comment by SmerkyG** [comment]
Gotcha. Yeah looks like this was considered and decided against in 2018.

**Comment by SmerkyG** [comment]
Just to point out, though: you cannot even use @:access a private class's members! So for example @:access(h2d.TileGroup.TileLayerContent) will not allow you to access myTileGroup.content.tmp

Effectively, private classes are entirely beyond the scope of @:access, even on a member basis.

**Comment by SmerkyG** [comment]
Oh very odd indeed! It actually DOES allow access to the members of the private class if you don't qualify the name with the file that it's in:

@:access(h2d.TileLayerContent)
instead of
@:access(h2d.TileGroup.TileLayerContent)

The module namespaces sure are confusing in this situation!

**Comment by Gama11** [comment]
There's also some related issues for that one. :)

- #3590
- #3638
