### ISSUE TITLE
[eval] Improve capture variable handling

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7983]
The current implementation of handling captured variables is not ideal. In fact, it kinda falls apart in certain scenarios. By now I have a fairly clear idea of how I want to do this, but it is going to require some effort so I'm not sure I'll be able to do it for Haxe 4.0.

**Comment by Simn** [comment]
I might have to do it for 4.0 after all. I've come across some cases where this causes problems, at the very least with the debugger. I think there might be run-time issues as well in certain situations.

@ncannasse: What did you end up doing with capture var handling in HL? I remember you having some problem with `this`-closures being indistinguishable from normal one-capture closures, so that's a problem I'd like to avoid.

**Comment by ncannasse** [comment]
In HL a closure is a function ptr + a captured value. The value can be any pointer value or a "single contructor enum" that holds several values (when capturing multiple vars).

And yes I don't think I can distinguish between the two, but that's quite easy actually you should just tag your closure with a given "kind" marker.

**Comment by Simn** [comment]
It occurred to me that I don't actually have to carry the environment around on my values because the jit-function already knows which variables are captured and where they are captured from. The problem is that it captures way too much, i.e. everything from the parent scope that is captured (even from other closures).

I've designed it like this so I wouldn't need `CPWrapRef`, but looking at it now it's very clearly not worth it. The debugger shows the problem:

![Code_2019-03-19_14-54-22](https://user-images.githubusercontent.com/634365/54611288-efa93f00-4a56-11e9-9f09-e29e25b7e6f4.png)

The `capturedByG` variable should _not_ be on the stack here. This could actually have some pretty negative consequences for the GC as well because values live longer than they should.

**Comment by ncannasse** [comment]
Yes, you need to manage the copy of the captured vars only so the closure
scope does not reference the parent function scope
