### ISSUE TITLE
[eval] String encoding looks inconsistent

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#7986]
```haxe
class App {
    static function main(){
        var isUTF16 = #if utf16 true #else false #end;
        var str = "益";
        var bytes = haxe.io.Bytes.ofString(str, RawNative);
        trace('isUTF16: $isUTF16, code: ${str.charCodeAt(0)}, bytes.length: ${bytes.length}');
        // eval : isUTF16: false, code: 30410, bytes.length: 3
        // other platforms:
        // hl   : isUTF16: true,  code: 30410, bytes.length: 2
        // js   : isUTF16: true,  code: 30410, bytes.length: 2
        // neko : isUTF16: false, code:   231, bytes.length: 3
        // hxcpp: isUTF16: true,  code:   231, bytes.length: 3   (??also a bit weird)
    }
}
```
The strange thing is that the String encoding of `eval` looks like `UTF16`, but when write string to bytes with `RawNative` which String encoding is like `UTF8`.

**Comment by Simn** [comment]
I don't understand what you think is wrong here. Eval uses UTF-8 encoding, why do you think UTF-16 is involved?

**Comment by R32** [comment]
I think if it's UTF8, then the example above should not return `30410` by `str.charCodeAt(0)`

**Comment by Simn** [comment]
What else would it return? That's the correct code for that character, no?

**Comment by R32** [comment]
Ok, I am a bit confused, But I think if UTF8, then the value returned by `string.charCodeAt(0)` should be consistent with `bytes.get(0)`

**Comment by Simn** [comment]
That's not correct. Bytes is the raw bytes representation with a range of 0x00-0xFF, i.e. 8 bits, which is where the 8 in UTF-8 comes from.

**Comment by back2dos** [comment]
The behavior is correct. I understand the need for consistent representations, but I think `RawNative` quite clearly implies that that's not what you get. 

There may be a case for supporting uc2/utf16 encoding of course, but implementing it would be quite tedious, so I think it's going to be the kind of thing that's considered not worth adding until somebody comes forward with a PR ;)

**Comment by ncannasse** [comment]
RawNative means "whatever the platform internal string representation might want it to be". There is no guarantee. #if utf16 however gives some guarantee such as out of BMP chars taking one single char.
