### ISSUE TITLE
es6 output does not work properly with heaps

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#7988]
Compile the base3D sample in Heaps with -D js-es=6 and you'll see it has no visual output.

@nadako It doesn't show any runtime errors, just no visual output... I did see visual output with other things. Wasn't easily able to tell if it's related to normals, textures, or other... but I was getting some models that looked white.

**Comment by nadako** [comment]
"interesting". i'll check it out, thanks!

**Comment by SmerkyG** [comment]
By the way, is there a reason why members are all initialized to the value 'null' even for things like int, bool in the js target? One of my biggest pet peeves with Haxe's cross platform support is the lack of standardized initializers for member values across targets. This could be something to change in 4.0... just saying!

**Comment by nadako** [comment]
> lack of standardized initializers for member values across targets

Yeah I agree it's super annoying. Maybe it'll change in the future with the adoption of null-safety, fingers crossed :) Regarding the `null` values - they are actually generated only `Type.getInstanceFields` is used and that was like this when I found it :-P

**Comment by SmerkyG** [comment]
There's one other interesting js specific issue I ran into recently as well - Reflect.field(someInstance, 'someMemberFn') does not return you a function bound to 'this', like it would on other targets! So if you then call that function, thinking it's a normal this-bound Haxe function, you end up with big problems. Not sure there's an elegant solution for that one though... it'd at least require some (slower) testing code in the Reflect.field implementation.

**Comment by nadako** [comment]
Yeah, that's kind of expected. You're supposed to do `Reflect.callMethod(obj, Reflect.field(obj, meth), [...])`. But of course you should think of some reflectionless alternative.

**Comment by nadako** [comment]
Interesting, `-dce full` fixes that example.

**Comment by Gama11** [comment]
>lack of standardized initializers for member values across targets

There's a discussion on that here: https://github.com/HaxeFoundation/haxe/issues/7002

**Comment by nadako** [comment]
Found it!

```haxe
class Root {
	public function new() {}
}

class Child extends Root {
	public function new(a) {
		super();
		trace(a);
	}
}

class GrandChild extends Child {
	public function new() {
		trace(this);
		super(42);
	}
}
```

This will trace `undefined` because the arguments are never passed to `_hx_constructor`.

**Comment by SmerkyG** [comment]
Nice, that was quick!!!
