### ISSUE TITLE
Macro: Invalid character '`'

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#7990]
```haxe
class Macro {
	public static macro function express( e:Expr ) {
		var f = e.toString();
		trace(f);
		trace(e.pos);
		trace(e.expr);
		var object = Context.getLocalClass().get();
		var method = object.statics.get().find(function(s) return s.name == f);
		var ext = Context.getTypedExpr(method.expr());
		var r = ext.toString();
//		r.replace("`", ""); // this line can fix erroneous character `
		return Context.parse(r, Context.currentPos());
	}
}
class Main {
        static function main() {
                var c = Macro.express(callb);
        }
	static function callb() {
		var a = null;
		trace("What");
        }
}
```
Call to macro gives:
Main.hx:6: characters 11-31 : Invalid character '`'
 
Haxe Compiler 4.0.0-rc.1+40365dad5

**Comment by Simn** [comment]
I'm not sure if this is a real issue. `Context.getTypedExpr` is a huge source of problems in general because it tries to convert the typed AST back to syntax which does not always make sense. It can easily expose compiler internals (like the escape character for generated variables here), so my advice would be to stay away from it.

**Comment by Ilir-Liburn** [comment]
Here is what I get, target is Javascript (including js-es=6), after changing last line in macro to return macro null and tracing r;

Macro.hx:96: function():StdTypes.Void {
	var a = null;
	`trace("What", { fileName : "Main.hx", lineNumber : 25, className : "Main", methodName : "callb" });
}

Erroneous ` comes before trace. I can fix that in my code, but I would prefer to see such errors fixed. One day, hopefully.

**Comment by Simn** [comment]
The point is that we don't guarantee that you can go typed AST -> print -> AST. You should _not_ rely on something like this. If we change anything here it's likely going to be a `@:deprecated` on `getTypedExpr`.

**Comment by Ilir-Liburn** [comment]
Well, trace(method.expr().toString()) gives:
```Macro.hx:107: [Function:Void -> Void]
	[Block:Void]
		[Var a(5930):Unknown<1>] [Const:Unknown<0>] null
		[Call:Void]
			[Ident:Dynamic] `trace
			[Const:String] "What"
			[ObjectDecl:{ methodName : String, lineNumber : Int, fileName : String, className : String }]
				fileName: [Const:String] "Main.hx"
				lineNumber: [Const:Int] 22
				className: [Const:String] "Main"
				methodName: [Const:String] "callb"
```
TypedExpr is corrupted (there is ` in front of trace). However, return Context.storeTypedExpr(method.expr()) generates correct JavaScript result:

```js
var c = function() {
	var a = null;
	console.log("Main.hx:22:","What");
};
```

**Comment by Simn** [comment]
There's nothing to fix here for the reasons I already stated.

**Comment by Ilir-Liburn** [comment]
That's bad. Fortunately, there is a workaround for this as I stated, but I would prefer to see such things fixed
