### ISSUE TITLE
[display] Problems if keyword 'macro' appears at start of type path

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#7995]
I often want to organise my macros in a package named `macro`, so when building types I use the metadata `@:build(macro.TypeBuildingMacro.build()`, while this compiles, diagnostics says "unexpected ." and completion for macro-generated fields stops working.

This didn't compile at all in haxe 3 so it's been fixed in some parts of the compiler, but not all

**Comment by Simn** [comment]
Could you please post a complete example of this?

**Comment by haxiomic** [comment]
Attached a test project with comments
[macro-path-issue.zip](https://github.com/HaxeFoundation/haxe/files/2973220/macro-path-issue.zip)

Interestingly the problem doesn't occur if the meta is on the `Main` class, only the other class in the same file

**Comment by haxiomic** [comment]
Related
- [Package name "macro" problem #8323](https://github.com/HaxeFoundation/haxe/issues/8323)
- [List of keywords which can be used in package names #319](https://github.com/HaxeFoundation/HaxeManual/issues/319)

**Comment by nadako** [comment]
This works for me.

**Comment by haxiomic** [comment]
Yep, works for me now in development branch, thanks for testing @nadako 🌟
