### ISSUE TITLE
Wrong environment variable Path on installation

### ISSUE THREAD

**Issue by barraganlazlo** [HaxeFoundation/haxe#8002]
I runned the Windows 64bit installer for haxe 4.0.0rc1 and it tried to wrote the path of the commands in the PATH variable but windows 10 on my computer use the Path variable not PATH so it didn't worked 
i added it by hand but i just wanted to signal you this 

My version of windows 10 : 
Windows 10 Professional 
1809 
17763.379

**Comment by Gama11** [comment]
Huh, apparently this is a thing, the casing of `PATH` can be _whatever_ on Windows... https://github.com/cucumber/aruba/issues/291

**Comment by Simn** [comment]
Not sure I follow, if it's case-insensitive then why does it matter that we use PATH instead of Path?

**Comment by Simn** [comment]
Closing because I don't know what else to do with this.
