### ISSUE TITLE
[flash] Runtime error while implementing both generic and specific interfaces (i.e.IMyFloat and IMy<Float>)

### ISSUE THREAD

**Issue by pecheny** [HaxeFoundation/haxe#8015]
>VerifyError: Error #1053: Illegal override of Bar in Bar.

Not sure if it should work at all and how if it does. At least we can show warn while compiling to flash.

```haxe
class Test {
  static function main() {
    var b:Boo<Float> = new Bar(); // to avoid erasind due to dce. not required if dce is off 
    var a:BooFloat = new Bar();
    trace("Haxe is great! "+ a.getT() + " " +b.getT());
  }
}

class Bar implements Boo<Float> implements BooFloat{
  public function new(){}
  public function getT():Float {
    return 0;
  }
}
interface Boo<T> {
  function getT():T;
}
interface BooFloat {
  function getT():Float;
}
```

http://try-haxe.mrcdk.com/#e1543

**Comment by R32** [comment]
Every time flash causes this kind of issue, it seems that you can solve it by adding `@:generic` in the appropriate place. 

for your example:
```haxe
@:generic
interface Boo<T> {
  function getT():T;
}
```

**Comment by pecheny** [comment]
@R32 Thanks! (for now i use simplified solution since my  `@:autoBuild` used for method generation should be rewritten to be compatible with `@:generic`)

**Comment by Simn** [comment]
Since it's 2023 and this is a flash issue, I'll close it.
