### ISSUE TITLE
[feature request] inline function in typedef

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8018]
is there any chance to make typedef function inline?

example:
https://try.haxe.org/#003aa

```haxe
{
    on: function() {
        trace('test');
    }
}.on();
```

generates:

on haxe 4:

```js
(function() {
    console.log("Test.hx:30:","test");
})();
```

on haxe 3:

```js
({ on : function() {
    console.log("test");
}}).on();
```

but it could be better:
```js
console.log("test");
```

**Comment by skial** [comment]
Checkout the output of nightly builds http://try-haxe.mrcdk.com/#5aCFD, which reduces this down to the following:

```javascript
// Generated by Haxe 4.0.0-rc.1+4d426db
(function () { "use strict";
var Test = function() { };
Test.main = function() {
	(function() {
		console.log("root/program/Test.hx:14:","test");
	})();
	(function() {
		console.log("root/program/Test.hx:30:","test");
	})();
};
Test.main();
})();
```

**Comment by lublak** [comment]
@skial but it could be cleaner only have
```js
console.log("root/program/Test.hx:30:","test");
```

its just an idea.
Because if i create a class or an abstract i can just say: You are inline. And it is possible.

if you see, i also test it with haxe 4


> on haxe 4:
> 
> ```js
> (function() {
>     console.log("Test.hx:30:","test");
> })();
> ```

**Comment by Simn** [comment]
This isn't safe to do because of sub-typing.
