### ISSUE TITLE
Expressions in `trace` are omitted with `--no-traces`

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#8021]
This Haxe code:
```haxe
var x = 0;
trace(x += 5);
var y = x;
js.Browser.alert(y);
```
With `--no-traces` in compile arguments generates this JavaScript output.
```js
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var x = 0;
	var y = x;
	js_Browser.alert(y);
};
```
Note the absent of `x += 5`. 

According the docs (https://haxe.org/manual/debugging-trace-log.html) it might be correct:
> "This will remove all trace calls as if they were not present in the program."

Is this intended behavior?

**Comment by Simn** [comment]
I didn't really know `--no-traces` was a thing, but reading the documentation this seems to be working as intended.
