### ISSUE TITLE
"@:using" is not working on interfaces. 

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#8022]
Hello! :)
```haxe
//using Test.TestTools; //Works
class Test implements ITest {
  static function main() {
        new Test().test();
  }
  
  function new(){}
}

@:using(Test.TestTools) //Not works
interface ITest {}

class TestTools {
    public static inline function test(v:ITest):Void {
        trace("Test!");
    }
}
```

Error: `Test.hx:3: characters 9-24 : Test has no field test`
http://try-haxe.mrcdk.com/#7Cd23

Haxe 4. RC1

**Comment by Gama11** [comment]
At this point I'm wondering, what _does_ `@:using` work on? :D

**Comment by Simn** [comment]
This shouldn't work. `@:using` on a type only has an effect when a field access is made on that type. The compiler doesn't explore all related types to find all possible static extensions.

We will document this accordingly.

**Comment by nadako** [comment]
I don't know, this looks like a somewhat legit use-case and it looks like it should work. And we don't have to _explore_ anything here, right? We can inherit `@:using` when processing class heritage.

**Comment by Simn** [comment]
We can, but I don't think we should because this gets very magical.

I'm inclined to go the opposite way and restrict `@:using` to enums. That's why I originally added it, and because enums don't have sub-types we don't have to worry about complexity.

**Comment by nadako** [comment]
> restrict `@:using` to enums

Well, I can live with that. If we error on other types it'll at least look as something actually designed and not randomly (not) working :-) And we can revisit this some time in future.

**Comment by posxposy** [comment]
> I'm inclined to go the opposite way and restrict @:using to enums. 

Please, noooo :(
It is very useful for class types too. I'm using it in my project and I really like this feature.

**Comment by nadako** [comment]
But you can just add your `using`s to `import.hx`...

**Comment by posxposy** [comment]
> But you can just add your usings to import.hx...

Yes, but you can do the same for enums... Why do you need `@:using` then?
It is just good when you have a syntax sugar and different solutions for one problem.
`import.hx` doing it in a bit implicit way.

**Comment by back2dos** [comment]
Dunno. When I proposed this, I [specifically mentioned interfaces as a use case](https://github.com/HaxeFoundation/haxe-evolution/issues/35). And quite frankly, I don't get it: if you can apply the same extensions via using "globally" in `import.hx`, then what different kind of problem arises when applying them via `@:using`?

As for "why not just use `import.hx`":

![](https://i.imgflip.com/2wpgu7.jpg)

**Comment by Gama11** [comment]
#8188
