### ISSUE TITLE
Hidden ThreadHandle type does not unify for documentation

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#8023]
```
Joshuas-MBP:openfl joshua$ hxp docs
Parsing xml/Flash.xml
Parsing xml/AIR.xml
Parsing xml/Neko.xml

Called from ? line 1
Called from dox/Dox.hx line 146
Called from dox/Dox.hx line 139
Called from C:\GitHub\haxe\std/haxe/rtti/XmlParser.hx line 90
Called from C:\GitHub\haxe\std/haxe/rtti/XmlParser.hx line 317
Called from C:\GitHub\haxe\std/haxe/rtti/XmlParser.hx line 284
Uncaught exception - Incompatibilities between sys.thread.ThreadHandle in Flash,AIR and Neko (could not merge definition)
Error: Command failed with error 1
```

I believe this is breaking the job for generating api.haxe.org as well:

https://travis-ci.org/HaxeFoundation/api.haxe.org/jobs/508915723#L857

**Comment by Simn** [comment]
I noticed that too but thought it would be solved by making the type private. Guess I was wrong about that.

**Comment by Gama11** [comment]
Now it's about `Deque`:

>Error : Incompatibilities between sys.thread.Deque in neko,macro,cpp and hl (documentation is different)

**Comment by Simn** [comment]
Argh that's bad. I completely forgot that the documentation generator requires types to be equal even without `@:coreApi`. This isn't going to work because these types are abstracts on HL but classes everywhere else.

**Comment by Simn** [comment]
I think we need some hack here.
