### ISSUE TITLE
Docs report features are available that are not

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/haxe#8025]
There are a number of features within Haxe that report as "Available on all platforms" or as available on a number of platforms (such as sys platforms) but are implemented on fewer platforms.

For example:

https://github.com/HaxeFoundation/haxe/search?q=not+implemented+for+this+platform&unscoped_q=not+implemented+for+this+platform

It would be helpful if these were documented to be available only where it is implemented

https://github.com/HaxeFoundation/dox/issues/249

**Comment by NQNStudios** [comment]
I think this is a duplicate, or at least generalized version of the same issue in #6540

**Comment by Simn** [comment]
This is indeed a duplicate.
