### ISSUE TITLE
[std] use map literal syntax in Map's toString()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8030]
In the context of modern Haxe with its map literal syntax, `Map`'s string representation feels a bit unnatural, as it uses `{}` instead of `[]`:

```haxe
class Main {
	static function main() {
		trace([1 => "one"]); // {1 => one}
	}
}
```

I'm assuming that this is from a time before Haxe had map literals?

Changing it might be considered a minor breaking change.

**Comment by uvtc** [comment]
Seeing this inconsistency surprised me. I think it gives prospective new users the impression, "if low-hanging fruit like this hasn't been fixed yet, what bigger bugs will I stumble over down the road?".

**Comment by Simn** [comment]
I agree that this should be fixed, but invoking the confused new users trope just makes me less likely to look into something.

**Comment by uvtc** [comment]
Cool. Though, I didn't say that it confused new users.
