### ISSUE TITLE
Extract infos from from define.ml and meta.ml into JSON files

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8035]
@simn and I talked about how it might be a good idea to extract the desscriptions / "used on" info etc of defines into a JSON file. That seems more natural for something that's essentially just data than a source file.

If it's done for `define.ml`, it only makes sense to do the same for `meta.ml`. Technically we even have a JSON structure defined already for metadata due to the display API.

This would have the nice side-effect that other tools could parse it and do something with it, for instance auto-generating some Haxe Manual pages that always seem to be slightly outdated <sup>[[1]](https://haxe.org/manual/lf-metadata.html)</sup> <sup>[[2]](https://haxe.org/manual/compiler-usage-flags.html)</sup>. @markknol said he added some additional infos to some of those things, perhaps the JSON could have "extended descriptions" in a separate field, or use markdown in the description that is post-processed away for the command line output.

**Comment by kLabz** [comment]
Yeah!

I planned to do something similar, although only for `meta.ml`: generate `HaxeMeta.hx`, an `@:enum abstract to String` to be used in macros. Maybe such an abstract could be included in haxe std (in `haxe.macro` maybe?).

**Comment by Gama11** [comment]
That does seem like an interesting idea! I currently also maintain a (very incomplete) list of constants for metas in the language server because I wanted to avoid repeating string literals everywhere.

**Comment by kLabz** [comment]
Yeah, plus it avoids typos and provides some documentation on autocomplete.
