### ISSUE TITLE
[display] no hover/position for the super property access

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8037]
```haxe
class A {
	var x(never,set):Int;
	function set_x(v) return v;
}

class B extends A {
	override function set_x(v) {
		return super.x = v;
	}
}
```

here if you hover or try to goto-definition the `x` in the `super.x` nothing happens :)

**Comment by Gama11** [comment]
Something does happen:

```
[Error - 12:07:16] Request textDocument/hover failed.
  Message: Normal variables cannot be accessed with 'super', use 'this' instead
  Code: -32603 
```

**Comment by Simn** [comment]
This isn't specific to hover.

**Comment by Simn** [comment]
This is a larger problem because we lose the `MSet` mode while handling the display. This requires piping the mode through the display functions which means some rework. Pushing to 4.1.

**Comment by Simn** [comment]
This has been fixed by https://github.com/HaxeFoundation/haxe/commit/4b9939e09cba83fa8530109ed3090850c32b6294
