### ISSUE TITLE
[feature request] macro Compiler nativeType

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8042]
Allows from Macro Context compile stuff like:

```haxe
class Compiler { // or Context.nativeType?
    public static function nativeType(type:Type):String; // java: haxe.Int32 -> int
}
```

it helps for native code injection.

currently i do it myself (uncomplete) like (based on genjava real_type https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genjava.ml#L1213:

```haxe
type = TypeTools.followWithAbstracts(type);
switch (type) {
    case TInst(t, params):
            var tg = t.get();
             switch([tg.pack, tg.name, params]) {
                  case [['haxe'], 'Int32', []]: return 'int';
    case TAbstract(t, params):
            var tg = t.get();
            switch([tg.pack, tg.name, params]) {
                 case [[], 'Bool', []]: return 'boolean';
// .....
}

**Comment by lublak** [comment]
@Simn should at be at haxe code or ocalm code?

I mostly rewrite the code for (currenlty only) java and it works fine.
If it should haxe i can work more on it if it needed. For ocalm i have no time to learn ocalm.

Also the most time it difficult to figure it out how it can be created in haxe code.

(I think ocalm is the right place genjava/genphp/gen....)

**Comment by Simn** [comment]
If this targets strings it would be useless at OCaml-level, so I'm gonna say Haxe.

... in which case you don't really need this on the Compiler/Context API.

Also I would stay away from syntax-based code injection in general. What are you trying to do?

**Comment by lublak** [comment]
@Simn i want to create a auto "clone" build macro.
The most part a simple and the other part are the new "@:final" for fields.
At this i use the Reflection api.

But i want to optimize for java. (clone constuctor).
So i additional add a construtor via:

```haxe
var clstype = TPath({
    name: cls.name,
    pack: cls.pack
});
var nativeType = TypeUtil.nativeType(ComplexTypeTools.toType(clstype));
cls.meta.add(':classCode', [macro 'public $clsname($nativeType clone) {' + toclone + '}'], Context.currentPos());
```

i don't find any simpler solutions for this.

java also supports multiple constructor and haxe not.

but i come more to more to the options to use only reflection for it.
I also dislike syntax-based code injection (only like the new js.Syntax.code()/etc... for some external stuff)
And it is more and more a mess.

The biggest Problem is "@:final" which only can created in the construtor (before i used `Type.createEmptyInstance()`)

Also possible solution would be that all haxe objects are cloneable by haxe itself (so it can be optimized by target).
But i think its a lot of work.

**Comment by Simn** [comment]
I don't really follow, but if you're looking for a Java-specific solution then why not simply do something along the lines of `(cast yourObject : java.lang.Object).clone()`?

**Comment by lublak** [comment]
@Simn I give up. My brain burns. I I use reflection for final fields for all targets.
(cast yourObject : java.lang.Object).clone()
Only supports shallow clone.
But I want deep clone so ist recommend for java targets to use a Java constructor for it.
(Manual clone but auto created by autoBuild)

But now my brain says: No!

I now create for each field a clone expression and for @:final I use the reflection api.
If I want optimization in my own code I should now manually create the clone function.

But otherwise. It could be very helpful to add to all haxe classes a deepClone and shallowClond function.
But this should I add to haxe-evolution?
