### ISSUE TITLE
language server getting stuck on "Parsing Classpaths..."

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#8043]
This is an odd one that took some time to track down.
In a certain configurations, an empty project with `-lib coconut.vdom` targeting js (most probably unrelated, didn't test), will cause the language server to get stuck "Parsing Classpaths...". I should also note that the project compiles at any point. It's just about language server being stuck.

It doesn't happen with latest versions of the libraries, and it only happens with newer haxe versions. Specifically `436ef40d2` is the first build that has this issue, `08791f5e3` works.
I had the listed versions of dependencies, and I started updating and testing them one by one:

Library | Initial version | Updated to latest
------- | ------ | -------
coconut.vdom | 6d0fa1b9e24a824682b1e80cfbdfe9503aa1cf12
coconut.diffing | 649a87451cfdcc753798f03d7fc518088bc67ba4 | 017e36fb4d6942df3f65e38c790b4acf4490ebfb
coconut.ui | 68e16ccd856ca9de5830f37f1e2185d8dec7bde7
tink_lang | 0.6.2
tink_syntaxhub | 8b928af11fb39170dcb7254d02923777cddcc678
tink_priority | 0.1.4
tink_anon | eca9a364bf838e87c731d1c74d10a057edebd49c | 3c7180d3eec5bb983de893d5bfac6390a7c69e19
tink_hxx | 1a9bdf4ddef7e4cabaa5e8a6f8a5920364a7117e | da190820ffb6e798ed13c68d99d4cf9f840a6fe0
tink_parse | 0.2.0|12e4341729b8f8789590fc55aacef615480fe869
tink_core | 76a1e82db507edd79440b5dab91fe3bbd88c9e6c
tink_macro | 6f5eba983ea17de6b14ab5d8aa13278da2845f47 | 53868cc6f3d5e69f8d91c38a6ce7fff63fb9eab0
coconut.data | 809f57493b7258a24d3375ceebf3e16b351239b3 | aa30009958ab4661d65b9ce9300a8583ffab6fb2
tink_state | 0.10.0 | 0.10.1
tink_pure | 0.4.0
tink_slice | 0.1.0
xDOM | a3e3f092cd62db94a06edf40f1c819cf38fe27c1
tink_domspec | 7f569d6c59ddc68868dda3988ae7080939d753e2 | 356f08161df21371b8d4b36a475785e3335abae4
pick.first | 533af8000b87079c66fb6128f40403b2a5178f81

The issue got finally solved after updating tink_domspec. Concretely it was this [commit](https://github.com/haxetink/tink_domspec/commit/20f44723549f992ea3d863f7b6e1f78c6278aea3) that fixed the issue. I added traces to the macro call and it does return, so there's no infinite loop inside of that. It can be reproduced with an empty haxe project with `-lib coconut.vdom` and the latest versions of all dependencies except the tink_domspec being 0.1.4.

I'm not sure what to make of this, or if this is even Haxe issue or not.

**Comment by Simn** [comment]
Well, that makes some sense. e0ddd85fbc3d75e5e8749cc704f1ac9a9719f4ab fixed an issue where macros would not be run again on the server (#8042), so if the vdom change fixed a potential hang in the macro execution that might explain something (@back2dos).

Note that we still send the full compilation argument to Haxe for class path exploration, including `--macro` and everything. We have to do that so Haxe where knows to look for class paths. So if an init macro causes a hang, this would result in the observed behavior.

**Comment by back2dos** [comment]
Mhh, I guess if it really hangs in a `--macro` it should do so while "Building Cache", no? In any case, the change I made simply shaves off a fewhundred ms (because most projects use no more than 10% of all available html tags). It should definitely not make a difference between hanging indefinitely, and working just fine.

Perhaps the cause of the observed behavior is what I "fixed" here: https://github.com/haxetink/tink_hxx/commit/d581f19291ac99ddbd05c119a6f0bf0674b202de

**Comment by Simn** [comment]
> Mhh, I guess if it really hangs in a --macro it should do so while "Building Cache", no?

That's hard to say with the compilation server involved.

**Comment by Antriel** [comment]
I have this issue again. It's a bit odd one too. Different project, also using coconut.ui. Everything was fine until I added my macro based serialization. Updating all coconut/tink dependencies didn't help.

Weird part is that the project builds (with either haxe build) using `haxe build.hxml`. Using haxe build https://github.com/HaxeFoundation/haxe/commit/19c2778eaf8e108aa047dc45228ae52acdf2e5c1 the language server would quit when parsing classpath with the `Infinite loop in Haxe server detected.` error message.  
Using latest, or build after this commit https://github.com/HaxeFoundation/haxe/commit/af7b3f853ef7974286278a6ff22ad8267925cd99, will again get stuck parsing.

I removed all the code in my macro and ended up with single line, that causes the issue:
```hx
static var utfResultType = (macro :tools.Utf8Encoder.Utf8DecodeResult).toType();
```
The module only has the 2 classes `Utf8Encoder` and `Utf8DecodeResult`. It imports only `js.lib.Uint8Array`.

I'm at loss as to what could cause this or how to further debug the issue.

**Comment by back2dos** [comment]
I *think* I now "understand" the original issue and what "fixed" it. There's a `tink.domspec.Macro.tags` property, that holds information about the DOM. Populating it causes typing (among other things of the element classes from `js.html`) and [this was done eagerly way back when](https://github.com/haxetink/tink_domspec/blob/7f569d6c59ddc68868dda3988ae7080939d753e2/src/tink/domspec/Macro.hx#L22) and is now lazy. The class was imported into a module that also contained not only a build macro that leverages this data, but also an init macro invoked via `extraParams.hxml`. This basically forced some eager typing during init macro, which probably is not a good idea in general (and certainly failed in this case). 

Or perhaps the problem is with doing typing in the static initialization of a macro module?

For @Antriel, it seems to be similar. The offensive line causes typing of js code during initialization of a macro module.

**Comment by RealyUniqueName** [comment]
@Antriel 
Can you try with Haxe from commit ff1e2215e25bec2cf7b2562c58eaab1e22c1281d or later?
And if it still happens, could you please provide a sample?

**Comment by Antriel** [comment]
@RealyUniqueName 
See my previous comment. After that change server gets stuck parsing. Before it, it complains about infinite loop.
Now that we mostly know what causes it, I can try making a sample. It seems to come down to two macro modules initializing the same classes.

**Comment by RealyUniqueName** [comment]
So that commit doesn't help, I see.
I tried to follow instructions in your previous comment and issue doesn't happen for me. So I need a complete sample.

**Comment by Antriel** [comment]
Using Haxe build https://github.com/HaxeFoundation/haxe/commit/98d86711ba7e5e2579511db1baa4344547660679, latest tink/coconut (at least I hope I updated everything), I can reproduce the issue with following hxml:
```hxml
-cp src
-main Main
-lib coconut.ui
-lib coconut.vdom
--js build/test.js
```
and following Main.hx:
```hx
class Main {
    static function main() {
        coconut.Ui.hxx(<div />);
        MyMacro.foo();
    }
}
class MyMacro {
    public static macro function foo() return macro { };
    #if macro
    static var jsType = haxe.macro.ComplexTypeTools.toType(macro :js.lib.Uint8Array);
    // ^ the offensive line, comment out and problem goes away
    #end
}
```
Maybe @back2dos could further simplify the coconut/tink side of things? Probably also comes down to just initializing something somewhere.

To reiterate: it does compile from cmd, but using the language server, it gets stuck parsing classpaths. If it was already initialized before, and the problematic line was added after, it would also get stuck when trying to compile it.

**Comment by RealyUniqueName** [comment]
Thanks, I've managed to reproduce it. Now to the exciting stuff: debugging...

**Comment by RealyUniqueName** [comment]
Reduced a bit more:
```
-cp src
-main Main
-lib tink_syntaxhub
--js build/test.js
```
```haxe
class Main {
    static function main() {
        MyMacro.foo();
    }
}
class MyMacro {
    public static macro function foo() return macro { };
    #if macro
    static var jsType = haxe.macro.ComplexTypeTools.toType(macro :js.lib.Uint8Array);
    // ^ the offensive line, comment out and problem goes away
    #end
}
```
