### ISSUE TITLE
[display] no completion in string interpolation block with escape sequences

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8045]
Invoking completion at the `|` here yields toplevel completion results instead of field completion for the string literal:

```haxe
class Main {
	static function main() {
		'Foo:\n
		${
			"".|
		}';
	}
}
```

![](https://i.imgur.com/pdtGVKE.png)

If the `\n` is removed, it works:

![](https://i.imgur.com/qTumoB6.png)

**Comment by Simn** [comment]
This is an instance of #3974.

**Comment by Gama11** [comment]
Oh, really. I thought there should be an assertion failure then.

**Comment by Simn** [comment]
#3974 doesn't assertion fail anymore, so the issue title should be updated.
