### ISSUE TITLE
[matcher] null-checked pattern is not tempvared

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8050]
```haxe
class Main {
	var field(get,never):Null<Int>;

	function get_field() {
		trace("i'm a side effect!");
		return 10;
	}

	function new() {}

	static function main() {
		switch new Main() {
			case {field: 42}: trace("yes");
			case _: trace("no");
		}
	}
}
```

generates

```js
Main.main = function() {
	var _g = new Main();
	if(_g.get_field() == null) {
		console.log("src/Main.hx:14:","no");
	} else if(_g.get_field() == 42) {
		console.log("src/Main.hx:13:","yes");
	} else {
		console.log("src/Main.hx:14:","no");
	}
};
```

The result of `_g.get_field()` should be stored in a temp var before null-checking.

---

Originally I found this because of null-safety checker complaining about code like this:

```haxe
// @:nullSafety
class Main {
	static var x:Array<Null<{value:Int}>> = [{value: 10}];
	static function main() {
		switch x {
			case [{value: 10}]: trace("hi");
			case _: trace("bye");
		}
	}
}
```

With the `@:nullSafety` disabled it generates:
```js
Main.main = function() {
	var _g = Main.x;
	if(_g.length == 1) {
		if(_g[0] == null) {
			console.log("src/Main.hx:7:","bye");
		} else if(_g[0].value == 10) {
			console.log("src/Main.hx:6:","hi");
		} else {
			console.log("src/Main.hx:7:","bye");
		}
	} else {
		console.log("src/Main.hx:7:","bye");
	}
};
```
If we enable the check, it will complain with `src/Main.hx:5: characters 10-11 : Null safety: Cannot access "value" of a nullable value.`, pointing to the `x` in `switch x`. It looks like the same issue, because `_g[0]` is copied instead of being stored in a temp var and null-safety doesn't remember the array access (which is fair, I guess). The position of an error seems to be incorrect too. Shouldn't it point to the `{value: 10}` pattern here instead?

**Comment by Simn** [comment]
This now generates

```js
Main.main = function() {
	var _g1 = new Main().get_field();
	if(_g1 == null) {
		console.log("source/Main.hx:16:","no");
	} else if(_g1 == 42) {
		console.log("source/Main.hx:14:","yes");
	} else {
		console.log("source/Main.hx:16:","no");
	}
};
```

We should add a test for this. I didn't realize this was a behavioral problem or I would have 4.0ed it earlier. Sorry about that.

**Comment by kevinresol** [comment]
The null check is generated implicitly? Is this behaviour documented anywhere?

**Comment by nadako** [comment]
I think it was there for a while now (since 4b086437709a44b18c05e646248522e16f4ce05d?), but I'm not sure it's documented.
