### ISSUE TITLE
How to get request from https addresses

### ISSUE THREAD

**Issue by mailsoza** [HaxeFoundation/haxe#8052]
I am trying to make a `haxe.Http.requestUrl("https://www.google.com")` but it says it needs `-lib hxssl`. So i add it and then i receive the error `type not found: Lib`. In which platforms can I request Https addresses or how do i solve this?

**Comment by kevinresol** [comment]
What target are you using?

**Comment by mailsoza** [comment]
I'm using `--interp` and `-python`, but both present errors.

interp result
![image](https://user-images.githubusercontent.com/44980731/55101180-4a1f4c80-50a2-11e9-81f7-c3bbca235f45.png)

python result
![image](https://user-images.githubusercontent.com/44980731/55101094-1ba17180-50a2-11e9-80c4-445134a9061a.png)

**Comment by mailsoza** [comment]
Okay, it's just that hxssl is not compatible with macros, so one solution is to use `curl` with sys.io.Process. How exactly can i use it in code? I tried to pass `sys.io.Process("curl https://google.com > file.temp")` and then `sys.io.File.getContent("file.temp")`, but it only reads the second time the program is run. Is passing the content to a file a good option or are there better ones? Thanks in advance.

**Comment by RealyUniqueName** [comment]
Try `new Process("curl", ["https://google.com"]).stdout.readAll().toString()`

**Comment by Gama11** [comment]
IIRC, it's a bad idea to use `Process` like that? `close()` is never called, I think that once led to processes being leaked whenever code completion was invoked with FD / Flixel...

**Comment by RealyUniqueName** [comment]
That was more of a "show api in one line" :)

**Comment by Gama11** [comment]
Yeah, but then people copy it as-is and only notice that there's a problem until it's too late. ;) (that's what happened with Flixel)

**Comment by mailsoza** [comment]
It worked. Thank you!
