### ISSUE TITLE
Cannot use Reflect with empty string name on eval

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#8053]
```haxe
class Test {
	static function main()
	{
		var a:Dynamic = {};
		var b = "";
		Reflect.setField(a, b, 1);
		trace(Reflect.field(a, b) == 1);  // expected true, but false on eval
	}
}
```

I don't think this is right, an empty string should be just as valid as any (non-null) field name.

Personally I use this to differentiate between `/` and default routes when using the old `haxe.Dispatch` (or, more accuratelly, [`eweb.Dispatch`](https://github.com/jonasmalacofilho/eweb.hx/blob/master/lib/eweb/Dispatch.hx)).

But I can also see this causing issues when dealing with JSON data.

**Comment by jonasmalacofilho** [comment]
Clarifying...  Assuming you agree that

> an empty string should be just as valid as any (non-null) field name

this is a regression from 3.4.x.  See [slightly adapted example](http://try-haxe.mrcdk.com/#8400C) on try-haxe.mrcdk.

**Comment by Simn** [comment]
That's quite the corner case...

**Comment by Simn** [comment]
PHP dies:

```
unit.issues.Issue8053
  test: ERROR E
    Error: Cannot access empty property in /home/travis/build/HaxeFoundation/haxe/tests/unit/bin/php/lib/Reflect.php:375
```
