### ISSUE TITLE
PCRE Error 2 in macro

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8057]
I have the following code that runs in macros:

```haxe
	/**
		Returns the raw local user environment without the %VALUE% expanded
	**/
	public function getRawEnv() {
		var p = new sys.io.Process("reg.exe", ["QUERY", "HKCU\\Environment"]);
		var out = StringTools.trim(p.stdout.readAll().toString()).split("\r\n");
		out.shift();
		var env = new Map();
		for( l in out ) {
			var parts = ~/[ \t]+/g.split(StringTools.trim(l));
			var key = parts.shift();
			var type = parts.shift();
			var value = parts.join(" ");
			env.set(key.toUpperCase(), value);
		}
		return env;
	}
```

This used to work well (requires to run as Admin), it now fails on some computers when some env var contains non ascii chars (a `ï` in my case) with `Pcre.Error(2)` (not catchable)

**Comment by Simn** [comment]
I cannot reproduce that:

```
source/Main.hx:20: NICOLAS=ï
```

What OCaml version are you on?

**Comment by ncannasse** [comment]
OCaml 4.03.0

**Comment by ncannasse** [comment]
Ok, the error was actually something else entirely : a big binary file that we were trying to pass (by accident) through haxe.Template.
