### ISSUE TITLE
[display] constructor docs missing from signature help, but showing in hover 

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8061]
```haxe
class Main {
	static function main() {
		new sys.io.Process()
	}
}
```

Hovering over `new` shows the constructor's docs as expected:

![](https://i.imgur.com/O5tKqIu.png)

But they're missing from signature help:

![](https://i.imgur.com/upq9RQC.png)

This is also not consistent across targets... on Python, neither has any docs, presumably because `@:coreApi` is missing from the implementation for some reason. And Flash/JS show docs for both, funnily enough.

**Comment by Simn** [comment]
Fixed, not sure how to test this though.
