### ISSUE TITLE
sys.thread.Thread.current() returns different objects on each call on some targets

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#8063]
This actually is also true for some of the pre-haxe 4 implementations (e.g. `cpp.vm.Thread.current()`). But since we now have get a generic threading API it hopefully is the right time to address this.

It would be extremely helpful if either:
- for all thread-supporting targets the following evaluates to true (per some spec definition):
    ```haxe
    sys.thread.Thread.current() == sys.thread.Thread.current()
    ```
- OR if sys.thread.Thread gets an additional id() method (like the eval target has) and so we can do:
    ```haxe
    sys.thread.Thread.current().id() == sys.thread.Thread.current().id()
    ```

Currently we are doing fancy things like this as a workaround:
https://github.com/vegardit/haxe-concurrent/blob/e823e0fe8cca164aa7d9ba0b891d0f71c74db9b8/src/hx/concurrent/thread/Threads.hx#L22-L50

would be nice to replace this with a reliable one-line.

**Comment by Simn** [comment]
I actually noticed this too during the rework but forgot about it. This was supposed to be fixed for hxcpp and neko in #4141, which would make this a regression.

Not sure how to best solve this without weird compare magic though. Using a Tls?

**Comment by ncannasse** [comment]
I agree this should be part of the spec.

**Comment by back2dos** [comment]
FWIW tink_concurrent sidesteps this by having `Thread` be an `abstract` over the native handle / thread and thus `==` just works as expected for free (and even if it didn't `==` could be defined to do the comparison correctly).

**Comment by Simn** [comment]
I agree that abstracts are a good fit here, but I want to keep things classy for now. So we need a solution for this.

**Comment by back2dos** [comment]
Pick your poison. You can make it an extern class with inline methods then ;)

**Comment by RealyUniqueName** [comment]
Maybe some special `ThreadHandle` type would solve this issue without comparison magic and abstracting `Thread`?

```haxe
class Thread {
  public var handle(get,never):ThreadHandle;
  inline function get_handle() return new ThreadHandle(/* the code from @sebthom's repo */);
}

abstract ThreadHandle(Dynamic) {
  @:allow(sys.thread.Thread)
  inline function new(handle:Dynamic) this = handle;

  @:op(A == B) inline function compare(b:ThreadHandle):Bool {
    return this == b;
  }
}
```
And then comparing threads is just `thread.handle == thread.handle`

**Comment by Simn** [comment]
I don't think we should fix the comparison. What we should fix is the two `Thread` objects not being equal in the first place.

**Comment by Simn** [comment]
Maybe we should go for abstracts after all. Given that we're moving the types to a new place anyway, it seems like a practical choice.

**Comment by Aurel300** [comment]
After discussion with @Simn, it seems that abstracts alone can't solve the problem completely. They seem like a good idea for targets where the underlying handle is just a primitive anyway, e.g. `handle` in `cpp`.

But for e.g. `eval`, this won't work, since `current()` in the stdlib just calls `StdThread.self()` which just generates a new instance:

https://github.com/HaxeFoundation/haxe/blob/development/src/macro/eval/evalStdLib.ml#L2662-L2665

To solve this we could have a `static var currentInstance:Tls<Thread>` on the `Thread` classes, give it a value the first time `current()` is called and make sure to clean up (even in the case of an exception) after the thread callback finishes execution.

**Comment by back2dos** [comment]
Let's please not add further overhead to context switching. For all targets except eval, there's actually a call that returns the same value for the same thread. As for eval, we have full control, so I'd suggest fixing it there (could also be via opaque thread handles wrapped in abstracts).

**Comment by Simn** [comment]
> For all targets except eval, there's actually a call that returns the same value for the same thread.

I don't think that's true. There's a hack to make it _appear_ like it's the same value. See #4141.

**Comment by back2dos** [comment]
That hack is to make it appear like *the wrapper instances* are identical. I don't see how that's still relevant in light of the agreed upon solution.
