### ISSUE TITLE
[matcher] Temp-var TEnumParameter

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8064]
The pattern matcher currently does not temp var enum parameters, which can lead to the same access being made multiple times. This is particularly bad on targets that use something like nadako-enums where casts actually matter.

We should try changing it so every access that occurs more than once is temp-varred. This is not going to make the code any prettier, but it will be more efficient on most targets.

I'm not brave enough to do this for 4.0 though.

**Comment by nadako** [comment]
This is not related to https://github.com/HaxeFoundation/haxe/issues/8050, right?

**Comment by ghost** [comment]
sa
