### ISSUE TITLE
Reflect.isObject specification clarification

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8065]
This is the current documentation:

```haxe
	/**
		Tells if `v` is an object.

		The result is true if `v` is one of the following:

		- class instance
		- structure
		- `Class<T>`
		- `Enum<T>`

		Otherwise, including if `v` is null, the result is false.
	**/
	public static function isObject( v : Dynamic ) : Bool;
```

We have to clarify this with regards to `Null<Int>` and such because there's a disconnect between our view and the run-time view: While from our point of view it is not an object, it very well might be on several targets. The documentation should clarify that "object" here refers to Haxe point of view.

The reason this can be confusing is that on e.g. Java, we get `false` for all these tests:

```haxe
class Main {
	static public function main() {
		var i:Int = 12;
		var ni:Null<Int> = 12;
		var ji:java.lang.Integer = java.lang.Integer.fromInt(12);
		Sys.println(Reflect.isObject(i)); // false
		Sys.println(Reflect.isObject(ni)); // false
		Sys.println(Reflect.isObject(ji)); // false
	}
}
```

It's fair enough for the `Null<Int>` case because that's clearly a "Haxe view" situation. But the `java.lang.Integer` case can be somewhat surprising. I understand why it happens, but that's only because I know our `Null<Int>` is represented as `java.lang.Integer`.

**Comment by ncannasse** [comment]
I think specifying that it returns true if it's platform runtime object value seems fair. Would that break some unit tests?

**Comment by Simn** [comment]
Never mind, changing this likely wouldn't improve anything.
