### ISSUE TITLE
[display] range of parameterized types in hover

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8073]
This is essentially the same issue as #7975, but for types. Only `Array` should be highlighted here, instead the entire `Array<Int>` type hint is:

![](https://i.imgur.com/BM85acy.png)

This makes it so you have to "cancel" the hover first before you can hover over the `Int` type parameter.

**Comment by Simn** [comment]
So we have this structure:

```ocaml
type type_path = {
	tpackage : string list;
	tname : string;
	tparams : type_param_or_const list;
	tsub : string option;
}

and placed_type_path = type_path * pos
```

The position covers the entire thing, including the type parameters. This is consistent with how we handle position tuples for other structures.

The problem is that it means we don't have the exact position of the dot path itself.

**Comment by RealyUniqueName** [comment]
Can't we calculate position using total length of `tpackage` + `tname`?

**Comment by Simn** [comment]
Well... technically `var k:haxe . ds . StringMap<Int>;` is valid syntax...

**Comment by RealyUniqueName** [comment]
Ouch....
We can revert that, but I doubt such syntax is ever used.

**Comment by Simn** [comment]
Maybe we could even consider disallowing this. I've been thinking that `.ds` should be  lexed as a single token anyway. But that's a somewhat more involved change.
