### ISSUE TITLE
Allow-function with `_` argument in iterp

### ISSUE THREAD

**Issue by terurou** [HaxeFoundation/haxe#8076]
I tried this code in 4.0.0-rc.2.

```haxe
class Main {
    static function main() {
        var fn1 = _ -> _ * 10;
        var fn2 = (_, _) -> _ * _;

        trace(fn1(5));
        trace(fn2(1, 2));
    }
}
```

```hxml
-main Main
--interp
```

result
```
Main.hx:6: 50
Main.hx:7: 4
```

Is it expected behavior?

**Comment by Gama11** [comment]
Not sure what you'd expect to happen there, the second `_` shadows the first. That's how it works on every target, not just `--interp`.

**Comment by nadako** [comment]
I think there was already discussion about same-argument-name though. IIRC `function f(a, a)` is also allowed with the same behaviour which can be surprising.

**Comment by terurou** [comment]
Thank you. I understand.
I assumed the `_` argument to be ignored like the pattern match.

**Comment by terurou** [comment]
I also write C#, so I might have confused this:
https://docs.microsoft.com/en-US/dotnet/csharp/discards

**Comment by Gama11** [comment]
I also find it a bit strange that "ignored" parameters can still be used (I know that it's just a convention for function parameters, with no special semantics). It might be reasonable to turn that into a compiler error? Then again, you'd probably have to do the same with locals for consistency.

**Comment by terurou** [comment]
I do not think this should be a compiler error. There is almost no problem in practice. (In the first place, I just misunderstood.)
However, I think that it is kinder when it becomes a compiler error.
