### ISSUE TITLE
[java] assertion failed in completion related to overloads

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8078]
```haxe
class Main {
	static function main() {
		var b = new java.lang.StringBuilder("hi");
		b.|
	}
}
```
gives
```
File "_build/src/codegen/overloads.ml", line 236, characters 11-17: Assertion failed
```

**Comment by Simn** [comment]
I think this happens because the wrong overload is selected due to the typer being error-tolerant in display-mode.

**Comment by Simn** [comment]
In fact, this is probably a regression from https://github.com/HaxeFoundation/haxe/commit/949d0b8e949c0efd4124e011efd8085867065723#diff-67cfd4dd32c0945ddf80065ea37ce65fR166

**Comment by nadako** [comment]
Nice, thanks!
