### ISSUE TITLE
"Cannot access field or identifier timeout for writing" with call before assignment

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8079]
The following used to compile with Haxe 4.0.0-rc.2, but no longer does on dev (probably related to #8011):

```haxe
class Main {
	static function main() {}

	static function foo(state:Dynamic) {
		var instance = state.instance;
		instance.timeout.stop();
		instance.timeout = null; // Cannot access field or identifier timeout for writing
	}
}
```

The above code is isolated from Lime 7.2.1. Is this an intentional breaking change, or a regression?

**Comment by Simn** [comment]
¬_(*&!"*)£&!"$(£&)"(*$_"£($_"£$£"}~~}£"?$

**Comment by nadako** [comment]
what if you type-hint `var instance` with `Dynamic`?

**Comment by Simn** [comment]
Yes that works, it's an instance of the dynamic inference issue.
