### ISSUE TITLE
Cannot read + write with type inference

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8081]
```
class Main {
    static function foo(o) {
        if( o.x == null ) o.x = 0;
    }
    static function main() {
    }
}
```

This used to work and now gives `Cannot access field or identifier x for writing`

**Comment by Gama11** [comment]
Probably a duplicate of #8079?

**Comment by Simn** [comment]
Let's revert #8011.

**Comment by ncannasse** [comment]
@Simn what's exactly the problem here? We can first infer null write then update it to default write since the anon is still open

**Comment by Simn** [comment]
That's what I thought it was doing, but apparently it's not what it's actually doing.
