### ISSUE TITLE
[PHP] slow Xml.parse with large input on Haxe 4rc2

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#8083]
Working with large XML data structures on PHP target is almost impossible due to a huge slowdown in latest Haxe 4 versions compared to Haxe 3 generated output. Haxe 4's PHP code is orders of magnitude slower, than its Haxe 3 equivalent.

Sample code with a very flat XML structure takes about 1s with Haxe 3 and 100s with Haxe 4. 
With real world XML files using more complex data structures it's even worse. Also doubling the number of items from 5000 to 10000 doubles the runtime of Haxe 3 generated code to around 2s, while Haxe4 code takes about 400s (measured on a slow NUC-like system, so absolute values may vary).
```haxe
import haxe.Timer; 

class XmlMain {
    public static function main () {
        var data = "<parent>\n";
        for (i in 0...5000) {
            data += '<child attr="value1">textnode</child>\n';
        }
        data += "</parent>\n";
        var start = Timer.stamp();
        var xml = Xml.parse(data);
        trace ("duration: " + (Timer.stamp() - start));
    }
}
```

Also affected is `Json.parse` when using `-D haxeJSON` especially on larger files.

**Comment by RealyUniqueName** [comment]
@AlexHaxe could you please check the latest dev with your real data?

**Comment by AlexHaxe** [comment]
I only ran some basic tests, but it looks like Xml.parse is now working at almost identical speed to Haxe 3. 
Same goes for json parsing with `-D haxeJSON`, it might even be slightly faster than Haxe 3 - of course both are not as fast as without `-D haxeJSON`.

I will try to get more test runs in, but so far it looks great!

Thanks for the quick fix and good job!

**Comment by RealyUniqueName** [comment]
@AlexHaxe  any news?

**Comment by AlexHaxe** [comment]
I haven't encountered any slow downs during my tests, so I would call it fixed.
