### ISSUE TITLE
Can't read then write JSON field without explicit typing

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#8093]
Something changed in the last week:

```haxe
class Test {
	static function main()
	{
		var obj = haxe.Json.parse('{ "answer": 42 }');
		trace(obj.answer);  // required
		obj.answer = 3.14;
		// FAILS: Cannot access field or identifier answer for writing
	}
}
```

This is related to what type `obj` is inferred to be:

```haxe
var obj = ({ answer: 42 }:Dynamic);  // $type(obj): Unknown<T>; field access fails
trace(obj.answer);  // $type(obj): {+ answer : Unknown<0> }

// alternatively
var obj:Dynamic = { answer: 42 };  // $type(obj): Dynamic; field access succeeds
```

Honestly, since the spec says that monomorphs don't bind to Dynamic, I'm not sure why this used work in the first place.  Still, this should be fairly common when dealing with `haxe.Json`.

---

Note: pattern found in [haxe-version](https://github.com/ypid/haxe-version/blob/f3b927942db57c81f372ba3eed09b2e2831f040a/lib/Version.hx#L21-L24).

**Comment by Gama11** [comment]
This is likely the same as #8081 and #8079.

**Comment by Simn** [comment]
Could someone open a PR that adds a test for this and reverts #8011?

**Comment by RealyUniqueName** [comment]
Here: https://github.com/HaxeFoundation/haxe/pull/8096
