### ISSUE TITLE
Please separate build logic from travis.yml

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/haxe#8100]
Hxcpp uses the bleeding edge haxe build from source.  The procedures for building haxe - particularly the difficulties with ocaml - are a moving target and can cause travis to break.
haxe has these precious steps inside travis.yml, but I would appreciate these steps being put in something like "build_linux.sh"  so they can be shared with hxcpp (and other projects).

**Comment by Simn** [comment]
@andyli Is there anything from the azure pipelines config that we could expose here?

**Comment by andyli** [comment]
I've just set up Azure Pipelines for hxcpp. It uses the haxe nightly builds instead of building haxe from scratch, so I think I can close this.
