### ISSUE TITLE
[std] move arg quoting functions out of StringTools

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8109]
It doesn't seem like the `StringTools` additions from https://github.com/HaxeFoundation/haxe/commit/767b3fb4021124276741473ee2185f70b8508a92  (`quoteUnixArg()`, `winMetaCharacters`, `quoteWinArg()`) really belong there. It's especially awkward to have those functions show up in String dot completion with `using StringTools`.

According to @ncannasse `StringTools` shouldn't even have a regex dependency... https://github.com/HaxeFoundation/haxe/pull/7608#issuecomment-480388097

I think long-term these should be moved elsewhere (`sys.SysTools` or something?). For now it seems sensible to at least annotate these with `@:noCompletion`.

**Comment by Gama11** [comment]
`isEof()` also seems slightly unusual, and already has `@:noUsing`, likely because of that.

**Comment by ncannasse** [comment]
I agree these should be moved somewhere else.

**Comment by Gama11** [comment]
Including `isEof()`? In that case, they can't be moved into some `sys` package module as that is used outside of sys targets too.

I guess that only leaves the option of creating a new module in the `haxe` package? Perhaps it would fit into `haxe.io`?

What would the module be called, and do we need a `@:deprecated` redirect for `isEof()` in `StringTools`?

**Comment by ncannasse** [comment]
We will keep fastCodeAt/isEof for backward compatibility
