### ISSUE TITLE
Issues in other repos to be fixed till Haxe 4.0 release

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8111]
- [x] https://github.com/HaxeFoundation/hxcpp/issues/772
- [x] https://github.com/HaxeFoundation/haxelib/issues/448
- [x] https://github.com/HaxeFoundation/hxnodejs/issues/122
- [x] https://github.com/HaxeFoundation/hashlink/issues/250
- [x] https://github.com/HaxeFoundation/hxcpp/issues/797
- [x] https://github.com/HaxeFoundation/dox/issues/256
- [x] https://github.com/vshaxe/vshaxe/issues/349
- [x] https://github.com/HaxeFoundation/neko/issues/198
- [x] https://github.com/HaxeFoundation/haxelib/issues/458

**Comment by Simn** [comment]
I think https://github.com/vshaxe/vshaxe/issues/349 is not an issue anymore, but let's wait for confirmation I guess.

**Comment by Simn** [comment]
I guess we can close this.
