### ISSUE TITLE
neko startsWith/endsWith empty string test failures

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8115]
In the `neko` unit tests at the moment:

```
unit.spec.TestStringTools
  test: FAILURE .........F....FF..........................................................................................
    line: 18, expected true
    line: 25, expected true
    line: 26, expected true
```

The failing lines are:

```haxe
StringTools.startsWith("", "") == true;
StringTools.endsWith("foo", "") == true;
StringTools.endsWith("", "") == true;
```

Might be a regression after https://github.com/HaxeFoundation/haxe/pull/8062

**Comment by Aurel300** [comment]
Difference is caused by inconsistent behaviour of `indexOf` and `lastIndexOf` on neko:

```haxe
trace("".lastIndexOf(""));
trace("foobar".indexOf("", "foobar".length - "".length));
```

Outputs `-1` and `-1` on neko, `0` and `6` on other targets.

**Comment by Simn** [comment]
I think we should just patch that in neko's String.hx. Not worth going into the C code over this.

It's surprising that this isn't caught by our unit tests though.
