### ISSUE TITLE
@:nullsafety(false) annotation is ignored

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#8116]
when a class is annotated with @:nullSafety, you cannot disable checks for single expressions:

```haxe
@:nullSafety
class Test {
  
  @:nullSafety(false)
  static function foo(x: Null<Float>) {
    return x + 1.0; // error here: Null safety: Cannot perform binary operation on nullable value.
  }
  static function main() {
    trace("Haxe is great!");
    var x: Null<Float> = null;
    foo(x);
    @:nullSafety(false) x += 1.0; // same here.
    trace(x);
  }
}
```

**Comment by Gama11** [comment]
It's now `@:nullSafety(Off)`: https://github.com/HaxeFoundation/haxe/pull/7811

**Comment by Gama11** [comment]
@RealyUniqueName Do you think invalid values as `@:nullSafety()` arguments should give a compile time error?

**Comment by RealyUniqueName** [comment]
I think yes

**Comment by AdrianV** [comment]
Hm with my simple example @:nullSafety(Off) works. In my projects I tried both @:nullSafety(Off) and@:nullSafety(false) but had no success -  i will check again. BTW sometimes it is very hard to figure out which operation triggers the null safety error

**Comment by AdrianV** [comment]
I have checked now: @:nullSafety(Off) works as expected - sorry for the wrong report, but I am complete dizzy now, because of so many null problems in my code...

**Comment by RealyUniqueName** [comment]
You can add `@:nullSafety` meta class-by-class instead of `--macro nullSafety("whole.app")` to migrate gradually.

**Comment by Simn** [comment]
Is there anything left to do here?

**Comment by Gama11** [comment]
Yes, making invalid `@:nullSafety` arguments error.
