### ISSUE TITLE
"\xFF" notation produces wrong string literals

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8119]
E.g.:
```haxe
trace("\xf0\xa9\xb8\xbd\xe3\x81\xc3\xab\x61");
```
Passing that string through this code:
```ocaml
match e.eexpr with
	| TConst TString s ->
		let bytes = Bytes.of_string s in
		Bytes.iter (fun c -> Printf.printf "%02x" (Char.code c)) bytes
``` 
produces following sequence:
```
c3b0c2a9c2b8c2bdc3a3c281c383c2ab61
```
while it should be 
```
f0a9b8bde381c3ab61
```

**Comment by RealyUniqueName** [comment]
Seems it's an intended behavior: https://github.com/HaxeFoundation/haxe/issues/7449
Though, idk why do we need `\x` to behave like this since we also have `\u`

**Comment by Simn** [comment]
IMO we should discuss this again because the longer I look at this the wronger it seems.

**Comment by ncannasse** [comment]
Our strings are now unicode so we don't allow anymore arbitrary byte injection in it.
`\xFF` now means the unicode character "255", so we should have:

```
"\xFF".length == 1
"\xFF".charCodeAt(0) == 255
```

**Comment by Aurel300** [comment]
> `\xFF`.length == 1

But, to be clear, its length *in unicode codepoints* is 1, not in bytes.

**Comment by RealyUniqueName** [comment]
> Our strings are now unicode so we don't allow anymore arbitrary byte injection in it.
> `\xFF` now means the unicode character "255", so we should have

But why do we need it now since we have `\u00FF` which does exactly the same thing?

**Comment by Simn** [comment]
> Our strings are now unicode so we don't allow anymore arbitrary byte injection in it.

That's exactly why I think values > 127 should be disallowed...

**Comment by ncannasse** [comment]
We can either disallow > 127 or make sure >127 outputs unicode characters.
The first option tells people they need to update their code, the second
assume that that's what they intended from the start.

**Comment by back2dos** [comment]
Could anyone please come forward with a good use case for `\x` escape sequences beyond char 127? Short of that, my suggestion would be just to disallow it for the time being, as it's unlikely to break any significant amount of code.
