### ISSUE TITLE
[as3] spec tests failures

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8120]
```
src/unit/TestMain.hx:42: Generated at: 2019-04-05 19:18:50
src/unit/TestMain.hx:44: START
utest/ui/text/PrintReport.hx:52: 
assertations: 8215
successes: 8213
errors: 1
failures: 1
warnings: 0
execution time: 1.314
results: SOME TESTS FAILURES (success: false)
test as3 failed
```
https://github.com/HaxeFoundation/haxe/pull/8107#issuecomment-480499518

**Comment by RealyUniqueName** [comment]
```
unit.issues.Issue8075
  test: FAILURE F
    line: 10, expected 0 but it is null
```
I'm not sure what to do with this one.
It's
```
var a = [];
a.push(1);
a.pop();
a[2] = 2;
eq(0, a[0]);
```
compiled to exactly the same as3 code.
Either as3 generator should generate a cast of `a[0]` to int or this test should be disabled for as3 to leave the generator intact.
@ncannasse

**Comment by ncannasse** [comment]
seems like in AS3 the array is not correctly typed as `Array.<int>` or else reading from it should be 0.

**Comment by RealyUniqueName** [comment]
But arrays are not parametrized in as3. Or is there a way to do it, which I'm not aware of?

**Comment by Simn** [comment]
Let's disable the test, nobody uses the AS3 target anyway and this is not a regression.

**Comment by nadako** [comment]
the only parameterized type in as3 is vector

**Comment by ncannasse** [comment]
Ah right, my flash days are getting far. The correct fix would have been to cast after each typed Array read.
