### ISSUE TITLE
[flash] swc extern loader vs uppercase-first packages

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8129]
We have an SWC with this code: https://github.com/shin10/Starling-FFParticleSystem/tree/master/src/de/flintfabrik/starling/extensions

And it's not possible to import anything from the `de.flintfabrik.starling.display.FFParticleSystem` package, because (obviously) it's also a module within Haxe type system.

One solution would be to lowercase the first package letter, like (I think) it's done in the .NET extern loader.

If noone has complains and/or better ideas about this, I'll change this some time in the near future.

**Comment by ncannasse** [comment]
Good for me
