### ISSUE TITLE
[display] invalid positions in `replaceRange.end`

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8136]
Invoking completion here:

```haxe
class Main {
	static function main() {
		var test:String;
		test.foo|
	}
}
```

returns this replace range:

```json
"replaceRange": {
    "start": {
        "line": 3,
        "character": 5
    },
    "end": {
        "line": 0,
        "character": -1
    }
}
```

I think the only reason why this hasn't caused issue so far / isn't passed onto the LSP by the language server is that there happens to be a check that makes sure `replaceRange` isn't multi-line...

It's also a rather recent regression, this works even with RC2.

**Comment by Gama11** [comment]
I must either be very lucky or very unlucky to run into this already, but this regression is in fact _very_ recent - it's from #8133. :)

**Comment by Simn** [comment]
Right, I forgot about `cut_pos_at_display`
