### ISSUE TITLE
Utf.iter8 throws for 0x7F on Neko

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8139]
```haxe
class Main {
  public static function main():Void {
    var str = "\x7Fa";
    haxe.Utf8.iter(str, cp -> trace(cp));
  }
}
```

Expected output: `127` and `97` (works on Python, JS, Java, eval, C++, …)

Neko v2.2.0:

```
Called from ? line 1
Called from Main.hx line 4
Called from /.../haxe/std/neko/_std/haxe/Utf8.hx line 72
Uncaught exception - std@utf8_iter
```

**Comment by Aurel300** [comment]
This line is the culprit:

https://github.com/HaxeFoundation/neko/blob/master/libs/std/utf8.c#L362

(should be `<= 0x7F`)

There is a similar problem in HashLink, though it does not throw:

https://github.com/HaxeFoundation/hashlink/blob/master/src/std/string.c#L89

Additionally neither `C0`, `C1` (overlong sequence start), nor `F5` – `FF` (codepoints higher than allowed in Unicode) are rejected.

**Comment by ncannasse** [comment]
I have fixed the 0x7F in HashLink.
I'm not sure what to do with C0-C1 and F5-FF, you can submit a PR for
hashlink string.c if you want to improve things here
I will not fix Neko but you can submit a PR there as well.

**Comment by ncannasse** [comment]
@Aurel300 can you submit a PR for Neko?

**Comment by ncannasse** [comment]
Nevermind I fixed it directly online.
