### ISSUE TITLE
Unable to use private class in the same module as static extension

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#8145]
```haxe
using Main.Helper; // Error: Module Main does not define type Helper

class Main {
	function new() {}
	static function main() {
		new Main().foo();
	}
}

private class Helper {
	public static function foo(main:Main) {}
}
```

**Comment by RealyUniqueName** [comment]
This happens because internally in the compiler `Main.Helper` is generated into a special package for private types: `_Main.Helper`.
Would be great to have private types available in userland code as subtypes of their modules like `Main.Helper`.
