### ISSUE TITLE
Unused variable warning for-loop

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#8147]
```haxe
for (i in 0...16) {
  trace("hello");
}
```
I get `Warning: Unused variable`

Would be nice to suppress this kind of errors, because there is no other alternative.

I tried underscore but that didn't help
```haxe
for (_ in 0...16) {
  trace("hello");
}
```

> Windows 10
> Haxe 4.0.0-rc.2

**Comment by Gama11** [comment]
Are you talking about diagnostics in FlashDevelop? In VSCode these are just grayed out instead of displaying as an actual warning.

![](https://i.imgur.com/JnwPUCT.png)

Seems like this would need to be a setting on FD's end?

**Comment by markknol** [comment]
cc @SlavaRa  Is there something HaxeDevelop can do here?

Some idea's from @Gama11 on the chat:

- > It should be easy for FD to check if the unused range is a `_`. 

- > IMO unused code shouldn't be displayed as warnings to begin with, much nicer to gray it out

**Comment by SlavaRa** [comment]
@markknol Hi, I'll be in the chat after the main job :)

**Comment by Simn** [comment]
Let's never warn about unused variables if the variable is named `_`.

**Comment by markknol** [comment]
Thanks! Nice solution!
