### ISSUE TITLE
()->T shows up as Void->T in error messages

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8148]
```haxe
function g(f:()->Void) {
	g(1);
}
```

gives `Int should be Void -> Void`, but should give `Int should be () -> Void`

**Comment by ncannasse** [comment]
I'm sure you can fix this one yourself ;)

**Comment by Simn** [comment]
Careful with the misc tests though.

**Comment by Simn** [comment]
Any reason your fix never made it to development?

**Comment by nadako** [comment]
I think it was about the old display protocol that would potentially break if we just change the printing.

**Comment by Simn** [comment]
So this is a wontfix or what?

**Comment by nadako** [comment]
As said in #8161, we either break it (maybe it won't break if non-vscode IDEs don't depend on that) or have two different variants for printing: one for display API and one for everything else.
