### ISSUE TITLE
[java] TestThreads fails on Windows

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8154]
```
Command exited with 0 in 5s: haxe [build.hxml,-java,export/java]
Command: java [-jar,export/java/Main.jar]
Running DequeBrackets
Running WeirdTreeSum
Running Issue8063
Running TestThreads
utest/ui/text/PrintReport.hx:52: 
assertations: 807
successes: 805
errors: 1
failures: 1
warnings: 0
execution time: 41.009
results: SOME TESTS FAILURES (success: false)
cases.TestThreads
  testSort: ERROR ..............................................................................................................................................................................................................................................................................................................F..................................................................................O
    line: 235, expected true
    missed async calls: 1
```
https://ci.appveyor.com/project/HaxeFoundation/haxe/builds/23764812/job/nimuxakvuxc37fa3#L2378

**Comment by Simn** [comment]
I think this is a legit timeout.

**Comment by RealyUniqueName** [comment]
There is also an actual failure:
```
line: 235, expected true
```

**Comment by Simn** [comment]
That's a wait timeout, so there's a good chance this is another legit timeout.

TestThreads is a bit of a stress test which is not really suitable to be run on CI I think.

**Comment by ncannasse** [comment]
Can we have CI-compatible parameters there maybe?

**Comment by RealyUniqueName** [comment]
I've played a bit with timings and still think something is wrong besides the timeouts.
Maybe it's the test is not correct, idk.
Here is one of my attempts (just increased the @:timeout):  https://ci.appveyor.com/project/RealyUniqueName/haxe/builds/23865119#L1155
As you can see there's plenty of errors.

**Comment by Simn** [comment]
Yes but look at what line 235 actually tests: `Assert.isTrue(l.wait(1.));`. The `wait` is supposed to finish normally (returning true), but it timeouts after 1 second and returns false.

You can try increasing that 1 second and see if that makes a difference. But still, if that doesn't complete within 1 second there's probably simply too much load in the thing.

You can also try running with `creatorLoad` only being `false` and see if that helps.

**Comment by RealyUniqueName** [comment]
> You can try increasing that 1 second and see if that makes a difference. But still, if that doesn't complete within 1 second there's probably simply too much load in the thing.

I already did: https://ci.appveyor.com/project/RealyUniqueName/haxe/builds/23795717/job/aetspwort5buugyq#L2391

**Comment by RealyUniqueName** [comment]
Besides the timeout erros there are these:
```
line: 47, Error No value found for 906 and 0 for para\meters: 0.02, true, 0.02, true, QLockFree, LockSemaphore, DequeSemaphore
    line: 47, Error Same value detected for 906 and 906 for para\meters: 0.02, true, 0.05, false, QDeque, DequeSemaphore, LockSemaphore
```

**Comment by Simn** [comment]
My assumption is that those are follow-up errors.

Can you try without creatorLoad? If that also fails then we can be fairly certain that something isn't working right.

**Comment by RealyUniqueName** [comment]
Waiting: https://ci.appveyor.com/project/RealyUniqueName/haxe/builds/23870592

**Comment by RealyUniqueName** [comment]
Still fails.
Btw, C# target fails with the similar errors on appveyor: https://ci.appveyor.com/project/RealyUniqueName/haxe/builds/23857848/job/ou0en2e7bj9ubyjm#L2389 while on travis C# passes this test.

**Comment by Simn** [comment]
Well, shit...

That means it could be something in the test or something in the thread implementation.

**Comment by Simn** [comment]
I'm removing the 4.0 milestone from this because this has likely been broken for a long time already, and I don't think it's high priority.

**Comment by Simn** [comment]
I think TestThreads is just broken and should be removed. I have no idea what's wrong though.

**Comment by sonygod** [comment]
any progress?

**Comment by RealyUniqueName** [comment]
nope

**Comment by RealyUniqueName** [comment]
Since old test suite for threads is abandoned now let's pretend this was an issue of the test rather than an issue of our threads implementation.
