### ISSUE TITLE
[display] macro generated object is dynamic

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8157]
```haxe
public static macro function args():ExprOf<coral.util.HaxeArgs> {
  // .....
}
```
![grafik](https://user-images.githubusercontent.com/44057030/56039015-9b327000-5d33-11e9-9b9a-43d7202cf7d7.png)
![grafik](https://user-images.githubusercontent.com/44057030/56039027-a38aab00-5d33-11e9-8b3b-e87b840ae016.png)
![grafik](https://user-images.githubusercontent.com/44057030/56039232-1562f480-5d34-11e9-96c8-3074473bcf26.png)
![grafik](https://user-images.githubusercontent.com/44057030/56039257-23b11080-5d34-11e9-9e06-f05e92d95302.png)

also it shows error if you use an enum that assign to a field of this class (Unresolved identifier).
(but it compiles fine, only on display)

currently i fix it with:
![grafik](https://user-images.githubusercontent.com/44057030/56039189-fc5a4380-5d33-11e9-862c-b54f8a205848.png)

**Comment by Gama11** [comment]
I think this is just compiler internals leaking through, nothing to be concerned about / which would actually have an impact on type safety.

(I'm going to interpret this as proof that random `Dynamic` hovers are harmful ;) https://github.com/HaxeFoundation/haxe/issues/8008, https://github.com/HaxeFoundation/haxe/issues/7703)

**Comment by lublak** [comment]
@Gama11 it also shows erros in the console:

> also it shows error if you use an enum that assign to a field of this class (Unresolved identifier).

but now (i don't know why.... i can't recreate this issue anymore) it works all fine.
![grafik](https://user-images.githubusercontent.com/44057030/56082604-07d46a00-5e1b-11e9-8b5a-e8da154a2d98.png)

i think it was just a cache error.
