### ISSUE TITLE
[java] Dynamic field generation is not always valid

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8160]
```haxe
class Main {
	static public function main() {
		var m = new Main();
		var d:Dynamic = m;
		Sys.println(d.dontRebindMe(m.iRebindYou())); // 2, should be 1
	}

	function new() { }

	function iRebindYou() {
		dontRebindMe = function(_) return 2;
		return 0;
	}

	dynamic function dontRebindMe(arg:Dynamic) {
		return 1;
	}
}
```

Evaluation order mandates that `d.dontRebindMe` is evaluated before `d.iRebindYou()`, but the way genjava generates this code violates that:

```java
haxe.lang.Runtime.callField(d, "dontRebindMe", new java.lang.Object[]{m.iRebindYou()})
```

I think `Runtime.callField` can only be used is the arguments don't have side-effects. The alternative would be to delay the argument evaluation until the call is made, but I don't think there's a good way of achieving that in Java.

**Comment by nadako** [comment]
I'm pretty sure this is also an issue on C#

**Comment by RealyUniqueName** [comment]
Something like `Reflect.call(Reflect.field(d, "dontRebindMe"), [m.iRebindYou()]);`?

**Comment by nadako** [comment]
The whole point of `Runtime.callField` is to avoid dynamic closure creation when we just want to call a method. So it's more like: `Runtime.callField(d, "dontRebindMe", () -> [m.iRebindYou()])` but then it might be not worth it since we have to allocate another closure...
