### ISSUE TITLE
[suggestion] `self` for abstracts

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#8162]
I would love to have `self` for abstracts, I'm basically copy/pasting this quite a lot.

```haxe
private var self(get, never):MyAbstract;
private inline function get_self() return (cast this:MyAbstract);
```

I need this if you have an enum abstract and want to switch on the values, or when using a abstract with custom operators. One random example is https://github.com/markknol/hx-vector2d/blob/master/src/geom/Vector2d.hx#L82-L110

This might be breaking since we need to have `self` as reserved keyword.

**Comment by Simn** [comment]
I acknowledge the issue but I don't want to randomly add a keyword like `self` to the language, so this is going to require some thought and probably a haxe-evolution.

**Comment by Gama11** [comment]
Hm.. if abstracts were simply generated with a `self` field like in Mark's snippet, it wouldn't necessarily have to be a keyword (though likely still break existing `self` fields). Not sure if that's a sane option at all.

**Comment by RealyUniqueName** [comment]
@nadako suggested `self` to be an arbitrary identifier like this:
`abstract MyAbstract(selfIdent:MyType) {}`

**Comment by Simn** [comment]
That seems wrong, the whole idea is that you want to reference the abstract type, not the underlying one which is already referenced by `this`.

**Comment by Gama11** [comment]
Yeah, I think nadako was saying that that _would've been_ an option if the semantics of abstract `this` were different, but that ship has sailed now.

**Comment by nadako** [comment]
Yes, I was talking _hypothetically_, like if we are to design abstracts again, it would be nice if `this` was typed as the abstract itself (so, consistent with classes), but `someIdent` (that comes from `abstract A(someIdent:T)` was typed as the underlying type.

**Comment by RealyUniqueName** [comment]
Something like `abstract MyAbstract(MyType) in selfIdent {}` or `as selfIdent`? :)

**Comment by Simn** [comment]
That (the `as` version) was also my first thought.

**Comment by Antriel** [comment]
I might be way off, but what about `this()`? It's already a keyword, it's normally invalid usage (I think?), so it handles this case nicely. Apart from using function call syntax, which is a bit awkward.
Edit: I suppose `this` could be a function, so this is all stupid. Disregard.

**Comment by Simn** [comment]
As I said, this has to be haxe-evolutioned.

**Comment by markknol** [comment]
Let's do this! https://github.com/HaxeFoundation/haxe-evolution/pull/62
