### ISSUE TITLE
Enum value comparison check

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#8167]
When I do `if (enumValue == enumValue)` and I get `You cannot directly compare enums with arguments. Use either 'switch' or 'Type.enumEq'`

But when I do `if (obj.enumValue == obj.enumValue)` everything suddenly compiles. I would expect the same error here.

It's odd that I can hide the first error by enabling another line of code (?)

When uncommenting line 12 the difference can be seen.
```haxe
class Test {
    static function main() {
        var c1:Shape = Box(1);
        var c2:Shape = Line(1);
        trace(c1 == c2);
      
      var x1 = new Obj(c1);
      var x2 = new Obj(c2);
      
      // resolve all errors by uncommenting this line
      // trace(x1.shape == x2.shape); 
    }
}

class Obj {
	public var shape(default, null):Shape;
	public function new(s) this.shape = s;
}

enum Shape {
	Box(i:Int);
	Line(i:Int);
}
```
http://try-haxe.mrcdk.com/#bb4A0

From chat:

> Could be a missing `follow` as usual
> Probably the field type isn't followed and it ends up checking `TLazy` or something

**Comment by Gama11** [comment]
Also, the error message should mention `.match()`.

**Comment by RealyUniqueName** [comment]
Shouldn't it be a warning? How do I compare two enum instances for physical equality?

**Comment by Simn** [comment]
There's no point because this will always be `false`.

**Comment by nadako** [comment]
No they won't. :)

**Comment by nadako** [comment]
> No they won't. :)

Ah you mean, when directly invoking constructors...

**Comment by Simn** [comment]
Not an issue, see slack for details.

**Comment by Wesss** [comment]
Could we please post the rational for this not being an issue here? Those of us coming from google would like to know.
