### ISSUE TITLE
js.Promise#catchError incorrect typing

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#8170]
At the moment, `js.Promise#catchError` is typed as
```haxe
@:native("catch")
function catchError<TOut>( onRejected : PromiseHandler<Dynamic, TOut> ) : Promise<TOut>;
```

However, in JS, the resulting promise will resolve with the previous result if the `catch` handler return nothing. Also, the promise may just resolve without error, so the catch handler is never called.

Consider the Haxe code as follows,

```haxe
import js.Promise;

class Test {
    static function main() {
        var p1 = Promise.resolve("calling next").catchError(function(error) {
            //This is never called
            trace(error);

            //return nothing
        });
        $type(p1); // print js.Promise<Void>, but it is actually js.Promise<String>

        var p2 = Promise.resolve("calling next").catchError(function(error) {
            //This is never called
            trace(error);

            return 123;
        });
        $type(p2); // print js.Promise<Int>, but it is actually js.Promise<String>
    }
}
```

**Comment by nadako** [comment]
Is this a regression?

**Comment by kLabz** [comment]
Nope, can reproduce with both 3.4.4 and dev

**Comment by andyli** [comment]
BTW, I have an idea for the fix:

```haxe
@:native("catch")
@:overload(function<VOID:Void>( onRejected : Dynamic->VOID ) : Promise<T> {})  // make sure Dynamic->NotVoid wouldn't match this
@:overload(function<TOut>( onRejected : PromiseHandler<Dynamic, TOut> ) : Promise<EitherType<T, TOut>> {})
function catchError( onRejected : PromiseHandler<Dynamic, T> ) : Promise<T>;
```

But it doesn't work due to #6065.
Moreover, the use of `<VOID:Void>` and the return type of `Promise<EitherType<T, TOut>>` is a bit questionable...

JS Promise is so hard to correctly type in Haxe...

**Comment by kevinresol** [comment]
advertisement: [wrap js promise into a tink promise](https://github.com/haxetink/tink_core/blob/650acb4d9834a66212fdd71887d627485cb9219c/src/tink/core/Promise.hx#L162-L165) and get rid of the weird typing.

**Comment by nadako** [comment]
> JS Promise is so hard to correctly type in Haxe...

Yeah, it's far more straightforward in TS with type unions. But hey, maybe there's a macro for that \o/

**Comment by nadako** [comment]
This is assigned to me, but I don't know what I can do about this. We enforce the same "out" type for `onFulfilled` and `onRejected` callbacks of `then`, which works and is a fair thing to do.

But when it comes to just `catchError`, the new promise type should be a type union of original promise type and the return value of `catchError` callback. The best thing Haxe can offer here is `haxe.extern.EitherType`, but I worry about ergonomics of that in the sane usage cases:

```haxe
var p = Promise.resolve(42)
	.then(v -> "success")
	.catchError(v -> "error");
p.then(v -> trace(v.toUpperCase())); // haxe.extern.EitherType<String, String> has no field toUpperCase
```

So, unless someone has nice ideas, I'm going to unassign myelf and consider this "blocked-by-type-system".

**Comment by nadako** [comment]
Hmm, actually this seems to work nowadays:
```
@:overload(function<TOut>(onRejected:PromiseHandler<Dynamic, TOut>):Promise<EitherType<T, TOut>> {})
function catchError(onRejected:PromiseHandler<Dynamic, T>):Promise<T>;
```

I'll play around with it a bit more and add a test.
