### ISSUE TITLE
Weird modifier combinations with `final` methods

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8173]
As @Aurel300 pointed out, `final` can be combined with some modifiers that make for a questionable combination:

```haxe
class Main {
	static function main() {
		bar = function() {}; // can be reassigned
	}

	// makes no sense, you can't override statics in Haxe
	final static function foo() {}

	// isn't dynamic more or less the opposite of final?
	final dynamic static function bar() {}
}
```

Perhaps both of these cases should simply be a compiler error? It makes sense that it didn't before, since metas are untyped and usually don't cause errors, but now `final` is a proper keyword / modifier.

**Comment by Simn** [comment]
I'm not sure about `final dynamic`. For methods, `final` usually means that you cannot `override` them in sub-classes, which is a different concept than `dynamic` which allows rebinding. There could be use-cases for allowing rebinding of the function without allowing override, so I'd hold back on disallowing this for now.

I agree that `final static function` makes no sense.

**Comment by Gama11** [comment]
Looks like `final` is also silently ignored on `new`:

```haxe
class Main extends Parent {
	static function main() {}

	public function new() {
		super();
	}
}

class Parent {
	public final function new() {}
}
```

Not sure if this should be respected (is this even really an "override" technically?) or error with something like "final not allowed on new".
