### ISSUE TITLE
[display] hang during readClassPaths since rc.2

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8174]
Opening an issue for this despite not having an isolated repro case despite since it seems like a rather important regression.

If you open the [vshaxe-build](https://github.com/vshaxe/vshaxe-build) workspace in VSCode, haxe.exe hangs during Haxe: Parsing Classpaths. This happens with both latest dev and rc.2, but not rc.1 (the latter may require downgrading to hxnodejs 6.9.0).

Doesn't seem like a typical hang where haxe.exe's RAM usage grows continously like in #8110, instead it stays at roughly 80 MB (but 100% CPU).

**Comment by RealyUniqueName** [comment]
> when building vshaxe _twice_, I now get that new `Server.ServerError("Infinite loop in Haxe server detected`

**Comment by RealyUniqueName** [comment]
This should be fixed with #8284.
@Gama11  could you check it please?

**Comment by Gama11** [comment]
I thought #8196 was the fix for this one? Or is that fix now obsolete?

**Comment by RealyUniqueName** [comment]
If #8284 fixes this issue (which it should), then #8196 is obsolete.
With #8284 compiler simply should not recurse into the modules, which are already on "stack of dependency checking".

**Comment by Gama11** [comment]
Ah, I was a bit confused about which issue you're even talking about, since there were two:

1. hang in vshaxe-build during "parsing classpaths"
2. infinite loop detection false positive in vshaxe (caused by the workaround for the first issue)

The second issue can't be reproduced even before #8284 because of the reversal of the check in 63f63ec.

I can reproduce the first issue before #8284, and it's fixed afterwards. So I guess we're good here. :)
