### ISSUE TITLE
haxe.Utf8

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8175]
* `encode`, `decode` and `validate` should be either deprecated or replaced with bytes
* we keep the other API, by default they should iterate on charCodeAt but in case the platform is #if tf16, they should correctly decode the surrogate pairs
* `haxe.Ucs2` should be moved to hx3compat
* Lua should not have a static char method as String.fromCharCode already does the same
* compare should be removed

**Comment by Simn** [comment]
Note that haxe.iterators.StringIteratorUnicode already has the iteration with surrogate pair handling implemented.

**Comment by ncannasse** [comment]
@Simn is that iterator used somewhere atm ?

**Comment by RealyUniqueName** [comment]
@ncannasse 
> Lua should not have a static char method as String.fromCharCode already does the same

Which method are you talking about?

**Comment by Aurel300** [comment]
> Which method are you talking about?

[This one](https://api.haxe.org/v/development/lua/NativeStringTools.html#char) I assume?

**Comment by RealyUniqueName** [comment]
> This one I assume?

Why should lua drop it if it's a native extern method?

**Comment by Aurel300** [comment]
@ncannasse do you want to drop the Unicode iterators from the standard library?

**Comment by Simn** [comment]
I don't really understand why we would drop these. They are easier to use and probably generate better code as well because everything is inlined.

**Comment by RealyUniqueName** [comment]
I'd prefer not to drop them too. Instead we should drop `Utf8.iter()` just like `Utf8.compare()`

**Comment by Simn** [comment]
Can somebody explain to me why we should keep Utf8 at all?

**Comment by RealyUniqueName** [comment]
For consistent UTF8 handling?

**Comment by Simn** [comment]
I'm not sure something like that `charCodeAt` should even exists. Code like `for (i in 0...Utf8.length(s)) Utf8.charCodeAt(s, i)` should never be written...

**Comment by RealyUniqueName** [comment]
But `decode`, `encode`, `length` and `validate` make sense.

**Comment by Simn** [comment]
Well, `encode` and `decode` are just (in)convenience methods for the Bytes API. But yes I suppose we have `length` and `validate` which can be useful.

**Comment by ncannasse** [comment]
> @ncannasse
> 
> > Lua should not have a static char method as String.fromCharCode already does the same
> 
> Which method are you talking about?

That was showing in haxe api documentation but was outdated, forget about it.

**Comment by ncannasse** [comment]
We need something that hides the differences between #if utf16 or not (surrogate pairs handling).
So:

```haxe
class Utf8 {
     public function validate( bytes : haxe.io.Bytes, start = 0, len = -1 ) : Bool;
     public function length( str : String ) : Int; // utf16 aware
     public function iter( str : String, f : Int -> Void ) : Void; // utf16 aware
     public function sub( str : String, pos : Int, len = -1 ) : String; // utf16 aware
}
```

**Comment by ncannasse** [comment]
But maybe there are two separate problems, and these 3 (length/iter/sub) should be in some `Unicode` class since they don't have much to do with Utf8 encoding at all.

**Comment by ncannasse** [comment]
Another option:

```haxe
class Unicode {
     public function validate( bytes : haxe.io.Bytes, encoding : Encoding, start = 0, len = -1 ) : Bool;
     public function length( str : String ) : Int; // utf16 aware
     public function iter( str : String, f : Int -> Void ) : Void; // utf16 aware
     public function sub( str : String, pos : Int, len = -1 ) : String; // utf16 aware
}
```

**Comment by RealyUniqueName** [comment]
What's that `Encoding`? Is it `haxe.io.Encoding`? If so, then what's the difference validating `UTF8` and `RawNative`?

**Comment by ncannasse** [comment]
Yes, it's haxe.io.Encoding. I think we should throw "Not supported" on
validating RawNative, but this opens up the possibility to add additional
encodings support such as UTF16 or UTF32

**Comment by RealyUniqueName** [comment]
That sounds like we actually want `haxe.Utf8`, `haxe.Utf16` and `haxe.Utf32` with the corresponding `length()`, `iter()` and `sub()` api based on Bytes :)

**Comment by Aurel300** [comment]
`haxe.io.EncodingTools` ?

**Comment by ncannasse** [comment]
We don't need these to operate on bytes, only validate() is bytes then you
can work on Unicode String that gives you operations on String directly.
Actually this is only required because of UCS2 API (JS, HL, etc.) that does
not take care of out of BMP chars (surrogate pairs instead).

**Comment by Aurel300** [comment]
On a `utf16` target:

```haxe
var a = "😂";
trace(a.length); // == 2 ???
var b = a.split("");
trace(b[0]); // surrogate ???
trace(String.fromCharCode(b[0])); // invalid character ???
```

It would be a lot nicer if these (target-inconsistent) problems were hidden away and dealt with properly in the `String` API, rather than a separate Unicode class.

**Comment by ncannasse** [comment]
If I am not mistaken that's the JS behavior and we don't want to change it.
So yes on utf16 targets there is still some issues with out of bmp chars.
That is why I was proposing an Unicode API to deal with it.

Actually it could be an abstract UnicodeString that would provide a 1:1
mapping of String API. But would be a lot slower for several operations.

**Comment by RealyUniqueName** [comment]
@ncannasse So, what's the decision here?

```haxe
class Utf8 {
     public function validate( bytes : haxe.io.Bytes, start = 0, len = -1 ) : Bool;
     public function length( str : String ) : Int; // utf16 aware
     public function iter( str : String, f : Int -> Void ) : Void; // utf16 aware
     public function sub( str : String, pos : Int, len = -1 ) : String; // utf16 aware
}
```
or
```haxe
class Unicode {
     public function validate( bytes : haxe.io.Bytes, encoding : Encoding, start = 0, len = -1 ) : Bool;
     public function length( str : String ) : Int; // utf16 aware
     public function iter( str : String, f : Int -> Void ) : Void; // utf16 aware
     public function sub( str : String, pos : Int, len = -1 ) : String; // utf16 aware
}
```
or
> an abstract UnicodeString that would provide a 1:1
mapping of String API. But would be a lot slower for several operations.

**Comment by ncannasse** [comment]
An abstract UnicodeString that would provide a 1:1 mapping of String API 
which also has a `static function validate` that takes an encoding as parameter
