### ISSUE TITLE
[display] @:deprecated typedefs in completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8178]
It's rather annoying to have the now deprecated types (#7390) show up in completion, and _before_ the ones you're meant to use:

![](https://i.imgur.com/s4R1yjg.png)

I think there's no reason to show `@:deprecated` typedefs in completion at all? At least as long as they're just simple aliases, typedefs to anon structs should probably still be shown. I think there's already some detection for the difference for nicer auto-generated deprecation messages.

**Comment by EricBishton** [comment]
Filter this in vsHaxe or vsCode, not the compiler.  IDEs should be able to make their own decisions.

**Comment by Gama11** [comment]
I guess that might be preferable. But in either case something needs to change in the compiler, because the protocol currently doesn't seem to include metadata for types (even though the data structure has a `meta` field).

It looks like metas are only sent during `resolve` right now, and they're rather heavy since they include a `pos` for some reason..

**Comment by EricBishton** [comment]
I agree the metadata should be included in the protocol response. A flag set for common metadata would be Ok, if we want something lightweight. (Still need all of the metadata to be present, though.)

**Comment by Gama11** [comment]
The thing I'm concerned about is this `pos` stuff, which seems rather useless in this context:

![](https://i.imgur.com/C4PJGyG.png)

We probably don't even need that during resolve requests.

**Comment by EricBishton** [comment]
We could use a file dictionary to remove the duplicate — very long — names.

**Comment by Gama11** [comment]
I don't think we need the positions of the metadata at all. There's already a position on the type.

**Comment by EricBishton** [comment]
That may be true for this use case.  The question becomes whether the code that puts out the metadata is common and the position is required for (an)other use case(s).  For instance, Is this code part of the compiler trying to expose full fidelity parsed data?

Or, is it, perhaps, trying to give ordering of the metadata so that an IDE can re-order based upon the user's/IDE's rules?

**Comment by Simn** [comment]
Never thought I'd see the day where @gama11 wants _less_ positions in the display output...

**Comment by RealyUniqueName** [comment]
What about an opt-in argument for display requests to add meta positions. By default, metadata won't contain pos infos.

**Comment by Gama11** [comment]
As I said, I don't think there's any point to including these positions at all, so a flag seems like overengineering. A list of metas to include in responses might make sense though, to reduce bandwidth if we only look at e.g. `:deprecated` anyway.

**Comment by ncannasse** [comment]
I agree @:deprecated should imply @:noCompletion, on both types and fields. No flag required.

**Comment by RealyUniqueName** [comment]
> I agree @:deprecated should imply @:noCompletion, on both types and fields. No flag required.

That means the decision about hiding it from completion would be made by the compiler. While the original issue (and I agree with it) suggested to let IDE decide whether a type should be listed in completion.

**Comment by Gama11** [comment]
Well, originally I suggested hiding it compiler-side, but then @EricBishton complained. :) It would be pretty consistent with what's done with `@:noCompletion` already though (the compiler makes the decision there, as it should so that lib authors can rely on it / some editor doesn't decide to show it anyway).

**Comment by RealyUniqueName** [comment]
I have no strong opinion on that. It just feels right to make this decision on IDE side.
`@:noCompletion` is a different story - it denotes a user explicitly wants to hide something from completion, while `@:deprecated` is not about completion at all. If that was a case one could manually add `@:noCompletion`.
