### ISSUE TITLE
Sys.command / sys.io.Process don't seem to use same env as cmd

### ISSUE THREAD

**Issue by mundusnine** [HaxeFoundation/haxe#8193]
Env:
- Haxe version: 4.0.0-rc.2
- Hashlink 1.9(only used for debugging because the library uses macro target)

In cmd:
![image](https://user-images.githubusercontent.com/29337013/56471961-b03f8b00-6426-11e9-957f-3fa486b1a7ee.png)

In Sys.command/ sys.io.Process:
![image](https://user-images.githubusercontent.com/29337013/56472002-3fe53980-6427-11e9-81fb-a77bb74ddb76.png)

For context: 
I am trying to get the path to a library installed with haxelib within that library( that I am developing).I want the library to have an image that will be added to the projects using it.

**Comment by Gama11** [comment]
>Hashlink 1.9(only used for debugging because the library uses macro target)

Fyi, the macro target has debugging support too. :) https://github.com/vshaxe/vshaxe/wiki/Debugging

**Comment by mundusnine** [comment]
Upon further testing; When I set `Sys.command("haxelib setup path/to/my/libs")` it fixed the issue. But I think the issue should not be present from the get go; Because logically, if cmd.exe is using a haxelib with the right config why does the Sys.command/haxe.io.Process use a haxelib with a different config ?

This could be an issue with haxelib but Sys.command/haxe.io.Process does not function in a logical manner with other commands.

For example, when trying to call `Sys.command("scoop install haxe-dev")`, the command process returns that the manifest is not present; while in cmd.exe `scoop install haxe-dev` has the manifest without issue.

**Comment by RealyUniqueName** [comment]
That may be caused by the settings of your OS.
What happens if you run your program in the same terminal, where you run `haxelib config`?

**Comment by ncannasse** [comment]
I'm not sure I understand the first screenshot. on windows the syntax to display an env var is `echo %HAXE_LIBRARY_PATH%`,  $ is Linux syntax

**Comment by ncannasse** [comment]
Closing due to lack of feedback.
