### ISSUE TITLE
[display] nonsense field completion subject in nested switch

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8194]
```haxe
class Main {
	static function main() {
		switch (nodeName) {
			case "p"
				switch (a) {}
		}
	}
}
```

When typing the `:` after the `"p"` here, Haxe returns field completion (?) with 0 items and this range as the subject:

```json
"range": {
    "start": {
        "line": 3,
        "character": 3
    },
    "end": {
        "line": 4,
        "character": 17
    }
},
```

This then leads to some rather strange postfix completion:

![](https://i.imgur.com/jbx5I8B.gif)

When the inner switch is commented out, Haxe doesn't give a completion response at all (as expected, since completion was auto-triggered with `:` after a `case`).

Doesn't seem to be a regression (on the Haxe side at least). Original issue at https://github.com/vshaxe/vshaxe/issues/337. Should be able to work around it by not allowing postfix completion if the completion was auto-triggered with a `:`.

**Comment by Simn** [comment]
Has nothing to do with nesting, the problem is this code in matcher.ml:

https://github.com/HaxeFoundation/haxe/blob/1ce52fa9e1218f4de2f0e2da572369c9843906b4/src/typing/matcher.ml#L574-L578

This came from fixing #5656. I cannot reproduce that anymore after removing these lines though, so I guess I'll just optimistically do that.

**Comment by Gama11** [comment]
Btw, I think we can test this by checking that completion after `:` doesn't return [type hint completion](https://i.imgur.com/YhXOiz2.png), since we cannot test ranges yet. Or maybe that's a separate issue?

**Comment by Simn** [comment]
Not sure how to test this because it depends on `wasAutoTriggered: true`.

**Comment by Simn** [comment]
Simplest test case is this:

```haxe
class Main {
	static function main() {
		switch ("p") {
			case "p":
				"foo";
		}
	}
}
```

This gave string completion from the `"foo"` before my fix.
