### ISSUE TITLE
Output.writeString issue with Unicode strings on Python

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8197]
```haxe
class PyWrite {
  public static function main():Void {
    Sys.stdout().writeString("čýžé");
  }
}
```

Expected output is `čýžé` (U+010D U+00FD U+017E U+00E9 = UTF-8 C4 8D C3 BD C5 BE C3 A9), actual output is (garbage):

```bash
$ python3 PyWrite.py | xxd
0000000: c384 c28d c383 c2bd c385 c2be c383 c2a9  ................
```

Which as it turns out decodes to U+00C4 U+008D U+00C3 U+00BD U+00C5 U+00BE U+00C3 U+00A9, so each of the UTF-8 bytes is encoded again into a Unicode codepoint. Examining the Python output it seems the issue is `haxe_io_Output.writeBytes`, which does: 

```python
while (k > 0):
  self.writeByte(b[pos])
  pos = (pos + 1)
  k = (k - 1)
```

And then in `python_io_NativeTextOutput`:

```python
def writeByte(self,c):
  self.stream.write("".join(map(chr,[c])))
```

Perhaps `Sys.stdout()` should use `python.io.{File,Native}BytesOutput`?

**Comment by ncannasse** [comment]
@frabbit can you fix this ?

**Comment by frabbit** [comment]
i will give it a try, maybe on friday or next week
