### ISSUE TITLE
Input.readString should be in characters

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8199]
`(some:haxe.io.Input).readString(x, UTF8)`

I think it would make more sense for this to read `x` characters rather than bytes. I don't really see a reason to read an exact number of bytes as a string (if need be this can be done with a simple `read(x)` and then `getString`), with Unicode strings this is just making it more likely to decode badly.

**Comment by RealyUniqueName** [comment]
That depends on a protocol used to encode Bytes. If your protocol tells you that a string is encoded in the next N bytes, then it's more convenient to `readString` using the number of bytes.

**Comment by Aurel300** [comment]
Again, if that's the case, you can do:

```haxe
var str = input.read(nBytes).getString(0, nBytes); // or .toString() if we're keeping it
```

My concern is mostly that there currently no method to read N _characters_ apart from reading bytes until you get a valid Unicode string that is of the correct length.

**Comment by ncannasse** [comment]
We can't read N characters, that would be quite inefficient as we would have to read byte by byte. 
Also, in binary protocols the string length is usually in bytes not in characters. Finally, that would be a very huge problem wrt backward compatibility.

Please update the unit tests accordingly and close this issue.
