### ISSUE TITLE
abstract from Dynamic vs arrays of mixed types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8203]
```haxe
abstract Any2(Dynamic)
	from Dynamic
	from Dynamic
{}

class Main {
	static function main() {
		var x:Any2 = [1,true,"hi"];
	}
}
```

this will give `Arrays of mixed types are only allowed if the type is forced to Array<Dynamic>`, unless you comment out one of the `from Dynamic`s.

And of course I didn't have two `from Dynamic` originally, the second one was a typedef to `Dynamic`.

**Comment by nadako** [comment]
Not a regression.

**Comment by nadako** [comment]
Could this be looked into sooner by any chance?

**Comment by Simn** [comment]
Eh, I think applying top-down inference when there are multiple `from` on an abstract isn't sound.

**Comment by nadako** [comment]
Related case from my latest adventures:

```haxe
abstract A(Dynamic)
	from Dynamic
	from Array<Dynamic>
{}

class Main{
	static function main() {
		var a:A = [1, false];
	}
}
```
