### ISSUE TITLE
UTF16 surrogate pairs in constant strings

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8205]
Given than \u takes 2 bytes hex charcode point, atm the only way to insert out of bmp char escape sequence is to use UTF-16 encoding, for instance "\ud83d\ude09" == "😉"

This might be misleading as the runtime string does not always uses UTF-16 encoding.
We need to decide whereas we forbid or not these character ranges in Haxe compilation.
- if we forbid, we need another "long" 8 bytes escape sequence for out of bmp chars
- if we allow, we need to make sure that the utf16 is correctly decoded/rencoded into the target platform representation (utf8 or other)

**Comment by Aurel300** [comment]
We also allow `\u{...}` syntax, e.g. `\u{1F404}`.

**Comment by ncannasse** [comment]
Right, so I think we should forbid surrogate pairs range in \u
@Aurel300 can you submit a PR for this?
