### ISSUE TITLE
Difficult to get going with visual studio 2015 [docs]

### ISSUE THREAD

**Issue by jspashett** [HaxeFoundation/haxe#8206]
I wanted to build for a Visual studio 2015, I couldn't find any examples to select a specific version of visual studio, so the build failed with:
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
Error: Build failed

I found a solution, but I had to look though the haxlib source to find an answer:
-D HXCPP_MSVC_VER=140

It would be helpful if this sort of thing could be found somewhere. I couldn't find the answer after searching around the Internet / haxe website.

**Comment by Simn** [comment]
I don't really know what to document here, but I also never had any issues with it.

**Comment by ncannasse** [comment]
@hughsando is not the VSStudio detection supposed to be automatic ?

**Comment by Simn** [comment]
I'm closing this because I don't see anything actionable here.
