### ISSUE TITLE
[php7] lowercase and uppercase same variable declaration

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8219]
Hej,

Haxe lets me declare 2 functions with the same name (one lowercase and second uppercase) but on runtime PHP complains.

**Comment by RealyUniqueName** [comment]
I think Haxe should not allow that. @ncannasse ?

**Comment by nadako** [comment]
IMO, we could rename the locals, but for fields yeah, considering reflection and stuff it might be a reasonable target-specific limitation.

**Comment by RealyUniqueName** [comment]
Why target specific? I think any sane code should not contain such field pairs.

**Comment by Gama11** [comment]
I'm not sure about that. I could see that happening especially with C# externs and native properties (convention is to capitalize the name) and regular fields.

**Comment by RealyUniqueName** [comment]
But there is no such convention in Haxe. It could be allowed for externs only.

**Comment by ncannasse** [comment]
Haxe is case sensitive and we should not annoy all developers on other
targets because of one target specific limitation, so I am fine doing a
target specific check.
I think we had it already actually.

Le ven. 26 avr. 2019 18:36, Alexander Kuzmenko <notifications@github.com> a
écrit :

**Comment by RealyUniqueName** [comment]
Ok. I'll check if I can support such fields on the generator side before disallowing it completely.

**Comment by RealyUniqueName** [comment]
I think I can support it in all cases except dynamic access, in which case it's most likely the first field in declaration order will be accessed.

**Comment by RealyUniqueName** [comment]
After some trials I've decided to prohibit such fields pairs for PHP target. It turns out to be a lot of trouble for little gain.
This issue only affects methods. Variables and "var" class fields are case-sesnsitive in PHP runtime.
