### ISSUE TITLE
[abstract] `iterator()` method is ignored when there's a resolve overload

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8221]
```haxe
abstract A(Dynamic) {
	public function iterator():Iterator<String> return null;
	@:op(a.b) function resolve(name:String) return null;
}

class MyHaxeMain {
	static function main() {
		var o:A = null;
		for (k in o) {
		}
	}
}
```

generates

```js
MyHaxeMain.main = function() {
	var o = null;
	var _g = o;
	while((_$MyHaxeMain_A_$Impl_$.resolve(_g,"hasNext"))()) {
		var k = (_$MyHaxeMain_A_$Impl_$.resolve(_g,"next"))();
	}
};
```

**Comment by nadako** [comment]
This is a regression from at least 4.0.0.preview.1 (i bet it has stuff to do with the iterable reworks)

**Comment by nadako** [comment]
Also if the abstract has `@:to function toDynamic():Dynamic` it will be used instead of the `iterator` field. Marking the `iterator` method with `@:to` helps tho :)

**Comment by nadako** [comment]
I've made a quick fix for it in 05420d3f153ed96db47f70df73ec3886cdfd1398 by doing the "iterator" field lookup again but this looks very dirty... Reopening for @Simn to review/change.

And regarding the `@:to Dynamic` I guess that's expected, because we first check whether it unifies with `Iterator` and only then `Iterable`? I'm not sure if it's documented though, but it should be!

**Comment by Simn** [comment]
That fix doesn't look right because it changes priorities: We usually check `next`/`hasNext` before we check `iterator`.

I think the clean fix here is to change the `resume` on `type_field` into some sort of configuration structure, which then has an `allow_resolve` entry.

**Comment by nadako** [comment]
I guess you're right. But also why do we check for `get_length` before both Iterator and Iterable protocols then?

**Comment by Simn** [comment]
We're kind of doing both:

```ocaml
let cf_length = PMap.find "get_length" c.cl_statics in
if PMap.exists "iterator" c.cl_statics then raise Not_found;
```

Which doesn't seem to make much sense in that order...
