### ISSUE TITLE
ocaml error with coconut data

### ISSUE THREAD

**Issue by francescoagati** [HaxeFoundation/haxe#8225]
hi,
with this example that i have created https://github.com/francescoagati/coconut-data-error with haxe 4 rc2 i get this error ocaml

Typing tink.core.SignalTrigger.new
Typing tink.core.SignalTrigger.asSignal
Typing tink.core._Signal.Signal_Impl_.trigger
Typing Store.update
Calling macro tink.macro.Types.resolveDirectType (C:\HaxeToolkit\haxe\lib\tink_macro/git/src/tink/macro/Types.hx:233)
Exiting macro tink.macro.Types.resolveDirectType
File "_build/src/macro/eval/evalContext.ml", line 342, characters 2-8: Assertion failed

**Comment by francescoagati** [comment]
with coconut.ui all go good. but after have added the redux example make it with coconut.data finded in gitter chat of coconut i have get this error

**Comment by nadako** [comment]
Pretty sure that's #8039

**Comment by francescoagati** [comment]
i try to compile with last dev build

**Comment by nadako** [comment]
any news?:)

**Comment by francescoagati** [comment]
not yet. i try tomorrow

**Comment by kevinresol** [comment]
I'm pretty sure this is fixed

**Comment by Gama11** [comment]
Closing since there hasn't been any followup.
