### ISSUE TITLE
haxe.Json and unicode

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8228]
Found that the following does not work in HL, and maybe other targets:

haxe.Json.stringify("👽")

**Comment by ncannasse** [comment]
I made a fix for hl, @Aurel300 could you add unit tests and see if the fix needs to be applied for other platforms as well ? (most likely, platforms returning split surrogate pairs in String.fastCodeAt, but not allowing such char in StringBuf).

**Comment by Aurel300** [comment]
What do we actually want the output to be? There are differences in behaviour between JavaScript and Python, for example:

JavaScript:

```javascript
> JSON.stringify("👽")
'"👽"'
> JSON.parse('"\\ud83d\\udc7d"')
'👽'
> JSON.parse('"👽"')
'👽'
```

Python3:

```python3
>>> import json
>>> json.dumps("👽")
'"\\ud83d\\udc7d"'
>>> json.loads('"\\ud83d\\udc7d"')
'👽'
>>> json.loads('"👽"')
'👽'
```

`parse` and `json.loads` seem to be ok with both surrogates and full characters. `stringify` in JS outputs the character "directly" (although the string is still UTF-16...), `json.dumps` splits it into `\u` surrogates. (Related: https://stackoverflow.com/questions/38463038/why-does-json-encode-utf-16-surrogate-pairs-instead-of-unicode-code-points-direc)

**Comment by ncannasse** [comment]
Since is seems to be the JSON spec, I think we can allow both "\ud83d\udc7d" and "👽" as they are the same string. But that means we must check for \u support in all our Json.parser as well.
