### ISSUE TITLE
Conditional breakpoints not working with eval-debugger

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#8230]
_Originally reported here: https://github.com/vshaxe/vshaxe/issues/342, but I'm cross-posting here because @Simn thinks it might be a Haxe issue. Feel free to close this or the one reported @ the vshaxe repo depending on where the problem is (I honestly don't have a clue at the moment)._

### Steps to reproduce:

1) Correctly configure your [launch.json](https://github.com/fullofcaffeine/pwa-ts-haxe-sample/blob/master/.vscode/launch.json) with the eval target;
2) Create a conditional breakpoint somewhere where eval can pick it up (any macro context, AFAIK), to make things simpler for this scenario, we'll add a `false` as the condition, meaning that when triggering the eval debugger, it __should not__ stop at it.
3) Start the debugging session;
4) The debugger stops at the aforementioned breakpoint.

### Version info:
* Linux Mint `18.3`;
* Haxe version: `Haxe 4.0.0-rc.2+77068e1 through Lix`;
* Lix version: `15.3.12`;
* vscode version: `1.33.1 (linux mint)`;
* vshaxe version: `2.9.2`.

__Also reported on the Haxe Gitter channel, see full transcript [here](https://www.pastiebin.com/5cc74a08158d6).__

**Comment by Gama11** [comment]
Hm, I wonder if this is a regression.. I feel like I must've tested this before.
