### ISSUE TITLE
JsGenApi bug or missing functionality when dealing with js reserved keywords as identifiers

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#8231]
Originally reported on the Haxe Gitter channel. See full transcript [here](https://www.pastiebin.com/5cc75a665d701).

I had an issue with a third-party lib ([tink_core](https://github.com/haxetink/tink_core)) that uses `finally` as a variable name in its Haxe code when using [hxgenjs](https://github.com/kevinresol/hxgenjs) to compile the project. `finally` is a [reserved JS keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) so it can't be used as an identifier in raw JS (or TS) code.

Here's a small project to isolate and reproduce the issue: https://github.com/fullofcaffeine/haxe-jsgenapi-reserved-keyword-issue. Please read the `README` as there's some additional information there that complements this issue report.

For your convenience, here are the links to both js programs:

1) Output by haxejs: https://github.com/fullofcaffeine/haxe-jsgenapi-reserved-keyword-issue/tree/master/out/haxejs/main-haxejs.js
2) Output by hxgenjs: https://github.com/fullofcaffeine/haxe-jsgenapi-reserved-keyword-issue/blob/master/out/hxgenjs/Main.js

Here's the error when running the hxgenjs version:

```
Main.js:32
	var finally = "Hello World";
	    ^^^^^^^

SyntaxError: Unexpected token finally
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
makefile:9: recipe for target 'run-hxgenjs' failed
```

**Comment by RealyUniqueName** [comment]
Perhapse theese functions should be exposed to JsGenApi:
https://github.com/HaxeFoundation/haxe/blob/a659d1c5e0a18101667fa235a76b699aa34c6fed/src/generators/genjs.ml#L132-L133
https://github.com/HaxeFoundation/haxe/blob/a659d1c5e0a18101667fa235a76b699aa34c6fed/src/generators/genjs.ml#L120-L130

**Comment by kevinresol** [comment]
I think they should be incorporated into the generateStatement method

**Comment by fullofcaffeine** [comment]
And or `generateValue()`, right?

Although I'm not sure what's the diff. between then and when to use one or another.

**Comment by fullofcaffeine** [comment]
@RealyUniqueName We discussed this problem a bit more today on the Haxe Gitter. The general consensus was that the solution should be encapsulated in the `JSGenAPI.generate*` functions, in the compiler. 

Here's the transcript: https://www.pastiebin.com/5cca7dd8d4bbf.

**Comment by fullofcaffeine** [comment]
@RealyUniqueName Could you let us know if any decision has been made regarding this issue? I think this is a somewhat big issue for the JSGenAPI. The workaround I have now is kind of hacky and ugly, since I'm searching and replacing the code generated. 

As a related question - in order to avoid the search and replace in the code generated by the `generate*` funcs, is there a way to get the expr in JSGenAPI and modify the `name`? I tried it but since they all seem to be typed, I couldn't really change the field names.

**Comment by RealyUniqueName** [comment]
Sorry, no decision yet. I'll try to figure out what to do, when I'm back from the Haxe Summit.
