### ISSUE TITLE
Add a warning for conditions in `#if` containing dots, but not enclosed in parens

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8234]
I find myself to tend to forget that `#if target.flag` requires parens, because it's so natural to treat `target.flag` as a single entity.
I guess, once namespaced conditionals go into a wild, it will cause a lot of confusion among haxe users.

```haxe
#if myLib.flag
  doSomething();
#end
```
That branch will never get into compilation without any sign of possible mistake at compile time.
And looking at that code is not immediately obvious what's wrong.

So, I propose to add a warning if a condition of `#if` is immediately followed by a dot without parentheses.
I guess it's a rare case to fence a field access with conditional compilation, and it will be trivial fix to avoid a warning: just add a space before a dot.

**Comment by Gama11** [comment]
I think the actual plan there is to make it work: https://github.com/HaxeFoundation/haxe/issues/8032 (though that's not on the 4.0 milestone)

**Comment by RealyUniqueName** [comment]
Yes, #8032 looks like not so simple to implement, but we need something to prevent Haxe users shooting their legs.

**Comment by Simn** [comment]
If I could detect this I could parse it, so this is covered by #8032.
