### ISSUE TITLE
[flash] Illegal override when overriding protected method defined in a grandparent

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8248]
```haxe
class Base {
	@:protected function f() {}
}

class Child extends Base {
	// uncomment to make it verify
	// override function f():Void {}
}

class Main extends Child {
	override function f() {}

	static function main() {}
}
```

This will compile but fail at run-time with `VerifyError: Error #1053: Illegal override of f in Main.`

I'm not sure what exactly is wrong here...

*UPD: this doesn't even require as3 extern swc and works with haxe-generated `@:protected` method*

**Comment by nadako** [comment]
@ncannasse any idea? this is probably the last `VerifyError` we're still getting with our code base at @innogames

**Comment by nadako** [comment]
Turns out this is not specific to SWC, I updated the example to be pure Haxe.

**Comment by nadako** [comment]
One possible reason for this might be invalid class initialization procedure. Looks like `mxmlc` puts all the inheritance chain on the stack before doing `newclass`, while Haxe only puts the immediate parent on scope...

**Comment by nadako** [comment]
> One possible reason for this might be invalid class initialization procedure. Looks like `mxmlc` puts all the inheritance chain on the stack before doing `newclass`, while Haxe only puts the immediate parent on scope...

Looks like it's not the case, I made Haxe output the same init script, but it still reproduces... Searching further.

**Comment by nadako** [comment]
I managed to build AVM and debugged this a bit, it fails [here](https://github.com/adobe-flash/avmplus/blob/65a05927767f3735db37823eebf7d743531f5d37/core/Traits.cpp#L2173). I think because `baseBinding` is not found [here](https://github.com/adobe-flash/avmplus/blob/65a05927767f3735db37823eebf7d743531f5d37/core/Traits.cpp#L2119), because we don't set a `protectedNamespace` for `Main`'s base class (`Child`), since it itself does not have any protected methods. I still don't quite understand how this works, but always setting `hlc_namespace` here https://github.com/HaxeFoundation/haxe/blob/19c2778eaf8e108aa047dc45228ae52acdf2e5c1/src/generators/genswf9.ml#L2220 seems to fix the issue. It looks like we need to set the protected namespace for  any class that descends from a parent that has protected?

**Comment by ncannasse** [comment]
I think the best here is to check what flash AS3 compiler outputs and try
to get the same. We had problems with flash protected and good reasons for
make everything public at runtime so I didn't dealt with all the namespace
stuff much.

**Comment by nadako** [comment]
Well I don't care if everything is public at run-time, but the problem here is that Haxe-generated SWF cannot verify because of a valid method override.

**Comment by nadako** [comment]
I `As3parse.dump`'d the SWF compiled with mxmlc and it looks like the AS3 compiler indeed always adds protected namespace to the classes that extend (directly or not) anything with protected fields.

**Comment by nadako** [comment]
Something's still not right here. It works in the test case, but fails on my work project. Maybe that's because I'm relying on the `com.types` to be in the correct order.

**Comment by nadako** [comment]
It just came to my mind that it has nothing to do with the type order. I rely on `:has_protected` being added to parent classes, but it's not the case with extern classes, because we don't generate them, so they are not processed and the `:has_protected` is not added. That's why it reproduces with our codebase (the parent class in in an SWC). I'll fix it later today or tomorrow.

**Comment by nadako** [comment]
I was right, fixed now. There's another issue with overriding protected fields, will report shortly.
