### ISSUE TITLE
[eval] Reflect.setField() doesn't work.

### ISSUE THREAD

**Issue by terurou** [HaxeFoundation/haxe#8252]
This code doesn't work in Eval. I think that it should print "point".

Input: 

```
haxe -main Test --interp
```

```haxe
class Test {
    static function main() {
        final p = new Point(1, 2);
        Reflect.setField(p, "name", "point");
        trace(Reflect.field(p, "name"));
    }
}

class Point {
    public final x: Int;
    public final y: Int;

    public function new(x: Int, y: Int) {
        this.x = x;
        this.y = y;
    }

    public function toString(): String {
        return '[$x, $y]';
    }
}
```

Result:

```
Test.hx:5: null
```

Environment:

* Haxe 

* Haxe 4.0.0-rc.2+032d95957
* Windows 10

**Comment by Gama11** [comment]
https://api.haxe.org/Reflect.html?#setField

>If `o` has no field named `field`, this function is only guaranteed to work for anonymous structures.

**Comment by terurou** [comment]
Oh, Thanks.
I misunderstood it because it works in JavaScript and Neko.

**Comment by Gama11** [comment]
Yeah, there's quite a few targets where this would fail (probably any statically typed target).
