### ISSUE TITLE
try-catch vs @:to 

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8257]
```haxe
abstract Dyn(Dynamic) from Dynamic {
	@:to function toDynamic():Dynamic return this;
}

class Main {
	static function main() {
		var value:Dyn = "s";
		(try value catch (pokemon:Dynamic) null : String);
	}
}
```

will fail with `Main.hx:8: characters 8-13 : Dyn should be String`

**Comment by nadako** [comment]
This is specific to `try/catch` because `(if (Math.random() < 0.5) value else null : String)` compiles!

**Comment by Aurel300** [comment]
Interestingly enough the above code compiles in 3.4.4.

**Comment by nadako** [comment]
try-haxe says it also compiles in 4.0.0-preview.1, so this is a 4.0 regression

**Comment by nadako** [comment]
Thanks a lot, that was quick!
