### ISSUE TITLE
genericBuild add support for universal expr with @:expr?

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8262]
Currently we only have const for generic classes.
But it could be helpful also support expression for @:genericBuild (macro level)
We have the `KExpr` so it could be possible?

Currently:
```haxe
@:genericBuild(TestDynamicBuilder.build())
class TestDynamic<@:const T> {}
```

```haxe
public var events:TestDynamic<{test: 'test'}>(); // impossible Unexpected "test" <- only for example
```

It could be usefull to have something like this only for @:genericBuild:

```haxe
@:genericBuild(TestDynamicBuilder.build())
class TestDynamic<@:expr T> {}
```

**Comment by nadako** [comment]
If i remember correctly `@:cost` already supports expressions, but due to syntax ambiguities (with the actual type syntax) you have to wrap more complex expression in array brackets, like `[<expr>]`.

**Comment by lublak** [comment]
@nadako yes you are right it works with sourrounding `[]`.
Should i keep the issue open for the syntax problem?

**Comment by nadako** [comment]
I don't think this problem is solveable, because type syntax is conflicting with expression syntax. We're able to make exceptions for literals and array brackets here, but trying to figure out other ones is too much pain to be worth it (and probably not possible anyway).
