### ISSUE TITLE
cache server connection error message could be friendlier

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8266]
```
PS C:\Users\nadako> haxe --connect 100
Fatal error: exception Failure("Couldn't connect on 127.0.0.1:100")
```

I think we should catch this error and print something like `Could not connect to the Haxe compilation server at 127.0.0.1:100. Please start the server with haxe --wait 100` (where `haxe` and `100` is actually `args[0]` and the port number supplied to `--connect`)

**Comment by Simn** [comment]
Meh, I don't think many people manually start compilation servers these days. If this fails in the IDE for some reason the new error message would only confuse users more because it tells them to manually start some server, while it should be the IDE doing that. So I prefer to leave this as-is.
