### ISSUE TITLE
[feature request] Macro methods property accessor

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8267]
Currently it is impossible to have a property with a macro method.
But for some reason it would be better to have a variable that calls a macro instance of a function.

```haxe
public var dateString(get, never):ExprOf<String>;
private macro function get_dateString():ExprOf<String> return macro $v{Date.now().toString()};
```

**Comment by ncannasse** [comment]
I'm not sure this would work, as here dateString is not a "real" variable.

**Comment by lublak** [comment]
@ncannasse i know. It calls automatically get_ evertime you access it.
With the macro property it also call every time the macro.

The same for set_ with a expression argument:
```haxe
private macro function set_dateString(str:ExprOf<String>)
```

**Comment by Simn** [comment]
I don't really like the idea of "hidden" macro calls and prefer them to be explicit. It would be quite irritating if every `field.access` could potentially execute some macro.
