### ISSUE TITLE
httpjs class returns 200 status on non 200 responses when responseText is not null

### ISSUE THREAD

**Issue by BigPhilCombo** [HaxeFoundation/haxe#8268]
https://github.com/HaxeFoundation/haxe/blob/0f9bb3edd351db290c2ba0460b191b43a1d38e6a/std/haxe/http/HttpJs.hx#L55-L63

It's particularly line 61. Why is it assumed that just because there is responseText that the status is OK?

**Comment by Simn** [comment]
This was changed in https://github.com/HaxeFoundation/haxe/pull/3353 and discussed further in https://github.com/HaxeFoundation/haxe/pull/3993. The reasoning makes sense to me, so I'm not sure why we should change something here.

**Comment by RealyUniqueName** [comment]
I agree, no change is required here. 
And in my experience current approach is the correct way to deal with local requests.

**Comment by BigPhilCombo** [comment]
So this is actually a situation when using the http class inside of Electron. We are making a remote request but it's running in a local environment, so isLocal is actually incorrect.

**Comment by RealyUniqueName** [comment]
Can you give an example URL and request+response headers?

**Comment by zhaoterryy** [comment]
I've created a simple example [here](https://github.com/zhaoterryy/haxe-issue-8268-example)

Unless I'm misunderstanding something, this shouldn't be the correct behavior.
