### ISSUE TITLE
'haxe' command not recognized in command prompt

### ISSUE THREAD

**Issue by RuiCuco** [HaxeFoundation/haxe#8270]
I installed the latest feature update to Windows 10, and then ran the Haxe installer (Windows 64-bit). Everything worked fine. After a reboot, whenever I type 'haxe' in the command prompt, I get the following error:

'haxe' is not recognized as an internal or external command, operable program or batch file.

Things worked fine before the Windows 10 feature update.

**Comment by Simn** [comment]
This is not a Haxe issue. Make sure haxe.exe is in a directory that is part of your PATH environment variable.

**Comment by reversed3829** [comment]
what does that mean
