### ISSUE TITLE
Non-exhaustive switches in value places are sometimes allowed with analyzer-optimize

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8277]
This only fails to verify with `-D analyzer-optimize`. Looking at `dump=pretty`, the only difference seems to be the lack of an `@:exhaustive` in the switch.

```haxe
class Main {
	static final Up = new Point(0, -1);
	static final Down = new Point(0, 1);

	static function main() {}

	function opposite(direction:Point):Point {
		return switch (direction) {
			case Up: Down;
		}
	}
}

class Point {
	public final x:Int;
	public final y:Int;

	public function new(x, y) {
		this.x = x;
		this.y = y;
	}
}
```

```
java.lang.VerifyError: Method expects a return value
Exception Details:
  Location:
    Main.opposite(LPoint;)LPoint; @13: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2b4d 2cb2 000c a600 07b2 000f b0b1
  Stackmap Table:
    append_frame(@13,Object[#17])

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
```

**Comment by Simn** [comment]
wtf is that code...

**Comment by Gama11** [comment]
What do you mean?  Isn't it perfectly valid to switch on read-only vars? There's that "Only inline or read-only (default, never) fields can be used as a pattern" error after all. Maybe that should mention `final` nowadays..

**Comment by Simn** [comment]
Am I missing something here or is this invalid code because the switch isn't exhaustive?

**Comment by Gama11** [comment]
Aren't non-exhaustive switches allowed by design in some cases? For instance switches on `String`.

Looks like that may only be the case in `Void`-places though?

```haxe
// compiles
switch "" {
	case "":
}

// Unmatched patterns: _
var foo = switch "" {
	case "": "bar";
}
```

In which case maybe there's an oversight here where non-exhaustive switches are sometimes allowed even in value places?

**Comment by Simn** [comment]
Well that's what I'm saying. There should never be non-exhaustive switches in value-places, no matter how French your patterns are. The JVM target needs a sound control flow and so does the analyzer.

**Comment by Gama11** [comment]
Makes sense.
