### ISSUE TITLE
[cpp] sys tests crash in _hx_std_sys_read_dir() on Windows

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8280]
AppVeyor currently fails when running the sys tests' `Main-debug.exe`:

https://ci.appveyor.com/project/HaxeFoundation/haxe/builds/24469620/job/lb5bk2s5uvegu65s?fullLog=true#L2797

This also reproduces locally, the debugger stops here:

![](https://i.imgur.com/4K6m65F.png)

**Comment by Simn** [comment]
@hughsando: Could you look into this some time soon?

**Comment by Simn** [comment]
@Aurel300 Is this covered by your sys endeavours?

**Comment by Aurel300** [comment]
I'm waiting for the CI in #8424, but I cannot reproduce this locally anymore.
