### ISSUE TITLE
Compiler conditional blocks completely ignored sometimes when targeting hl

### ISSUE THREAD

**Issue by twilson90** [HaxeFoundation/haxe#8281]
This code will produce different results when compiled for hl:

```haxe
#if true
//do stuff
#end
```

It's literally like rolling a dice. I compiled my app for hl 15 times in a row with no alterations to the source files, this was the result I got (0 = conditional blocks ignored, 1 = conditional blocks ran):

001001001110011

Whether or not the conditional blocks were considered by the compiler appears to be random. Really bizarre...

I'm using the latest release of Haxe 4.0 (rc2).
I've attached an example project which demonstrates the bug (uses OpenFl, can be simplified further but I'm not all that familiar with compiling Haxe based applications outside of Lime).

[bug.zip](https://github.com/HaxeFoundation/haxe/files/3170455/bug.zip)

You'll notice sometimes you see text in the top left corner, sometimes you don't.

**Comment by Gama11** [comment]
I can't reproduce this, neither with the .zipped project, nor with an empty pure Haxe or OpenFL project.

**Comment by nanjizal** [comment]
Sometimes different targets behave differently are you on a mac or linux? I don't understand why you would do this, it seems a bit strange surely true is reserved so behaviour is not defined? 
I think it's right to close as I see no reason this is important, but useful to specify your platform when submitting a bug.

**Comment by Gama11** [comment]
This is defined, `true` is always true / 1.

**Comment by nanjizal** [comment]
so it selects always so I see no point.

**Comment by twilson90** [comment]
> so it selects always so I see no point.

Except it doesn't for me!
I used #if true to prove a point that it wasn't due to any defines that were changing.
#if true is always true, and yet the code inside the conditional block doesn't run more than half the time I try to compile.
I don't get this for any other targets, just hl. And it happens for all projects.

Edit: Apologies, just realised this is an issue regarding OpenFl and text not rendering on the hl target.

**Comment by nanjizal** [comment]
Depending on your needs/targets OpenFL packages can be remapped to NME, Hugh made a feature of stability, reducing targets, but I have no knowledge of current relative stability but certainly you should experiment with both, NME is setup to provide Cppia ( alternative to HL ) see Hugh talk this year.
Obviously if you can pull fixes to OpenFL even better.
