### ISSUE TITLE
[nullsafety] `?pos:PosInfos` argument

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8291]
The last optional argument `?pos:PosInfos` should not be treated as nullable, because compiler always generates a value for it.
However, user can manually pass `null` there. Maybe safety checker should complain in this case.

**Comment by Gama11** [comment]
How could that work? `?` implies nullability.

Are you suggesting to create an exception / special case so that `?` does _not_ imply nullability for this one very specific case only?

**Comment by Simn** [comment]
Not sure what's best here. Technically, it's no different from any other optional argument.

**Comment by RealyUniqueName** [comment]
Yes, special case for an identifier, which is the last optional argument in current function and the type is `Null<PosInfos>`.

**Comment by RealyUniqueName** [comment]
> Technically, it's no different from any other optional argument.

Technically, yes. But at run time it's never `null`.

**Comment by Simn** [comment]
> Technically, yes. But at run time it's never null.

You don't know that. I have some code which manually forwards pos infos, and I could mess it up and accidentally use a null value. Not an explicit `null` value, but something that just happens to be `null` at run-time.

**Comment by RealyUniqueName** [comment]
Hm... You're right. It's easier to do something like this manually in the beginning of a function, which handles positions:
```haxe
if(pos == null) throw 'Invalid pos';
```
