### ISSUE TITLE
[php7] extern and include path

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8292]
Hej,

I see that when Haxe generates php 7 extern, it put it in a folder _MyExternClass.
But in this class, in the `__init__` function  I do an include but the path doesn't match because it misses the generated folder level.

I don't know if it's clear enough or maybe I'm doing it in wrong way ?

**Comment by RealyUniqueName** [comment]
Could you provide a sample, please?

**Comment by filt3rek** [comment]
Hmmm Sorry, I probably confused with `__init__`, `include` and `@:native`
So I can't see how to do that, let's say this is my directory tree : 

* src
  * common
    * Test.hx
  * Main.hx
* www
  * lib
    * (...)
  * ext
    * Test.class.php

common.Test is the haxe extern class
ext/Test.class.php is my real php class
All the haxe files are generated in __lib__ dir.

What is the correct way to link my extern haxe class with the php one please when the real php class is outside __lib__ dir,  in __ext__ ?

**Comment by filt3rek** [comment]
Using `@:native`meta, I can't target __ext__ because it's outside of __lib__ dir

**Comment by RealyUniqueName** [comment]
Here is an example of `Main.hx`, which will do the job:
```haxe
import php.Const.*;
import php.Global.*;

class Main {
	static public function main() {
		var extPath = dirname(__DIR__) + '/ext';
		spl_autoload_register(className -> {
			var fileName = '$extPath/$className.class.php';
			if(file_exists(fileName)) {
				require_once(fileName);
			}
		});

		common.Test.hello();
	}
}
```
and then in `common/Test.hx`:
```haxe
package common;

@:native('Test')
extern class Test {
	static public function hello():Void;
}
```
This setup works for me.
Note: I've added extern for `spl_autoload_register` function in recent commit b6221e4e782f6e10e7e8552a6caf6374ef91d7d2, but if you don't want to update Haxe, you can use `spl_autoload_register` with `untyped __php__(...)` or `php.Syntax.code(...)`

**Comment by filt3rek** [comment]
Thx Aleksandr !
Maybe it could be good to have an option/directive in haxe/php in order to include other paths ? As it's done in generated index.php ?

**Comment by RealyUniqueName** [comment]
I'll get back to this question when I'll be working on tighter integration of PHP ecosystem into Haxe/PHP development process.

**Comment by filt3rek** [comment]
Aleksandr,

I'm back to my initial question, I think I understand better now but there is still a strange thing.
Let's say I don't use `spl_autoload_register`, I want to use `__init__` function in an extern class like that :
common/Test.hx :
```haxe
package common;

@:native( "Test" )
extern class Test {
	public static function foo():Int;
	
	public static function __init__() : Void {
		php.Global.require_once( untyped __php__( "__DIR__" ) + "/../../ext/Test.class.php" );
	}
}
```
Main.hx : 
```haxe
class Main {

	static function main() {
		//php.Global.require_once( untyped __php__( "__DIR__" ) + "/../ext/Test.class.php" );
		trace( common.Test.foo() );
	}
}
```
As you can see, when there is an `__init__` function in an extern class, Haxe generates a folder `_Test`with the extern class `_extern_Test.php`
But when I write my haxe extern, I'm not inside this nested folder so my include doesn't match, and I have to take care of that in the path (I've to add another `../`).
Can we just generate the extern class as is without putting it in a nested folder ?
