### ISSUE TITLE
@:using constants

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8293]
It would be nice to be able to refer to external constants as if they were declared at the place of use. Sorry, my english is bad, here is a small practical example:

```haxe
class SomeEvent extends EventCase {
	inline static public var FLAG_1:Int = 1;
	inline static public var FLAG_2:Int = 2;
	inline static public var FLAG_3:Int = 4;
	...
}

class Listener<T:EventCase> {
	public function new(bitmask:Int, handler:(event:T) -> Void) ...
}
```

I have an event model based on bit masks and to create a listener, I have to write

`var listener = new Listener<SomeEvent>(SomeEvent.FLAG_1 | SomeEvent.FLAG_3, handler);`

Too much SomeEvent and the readability of the code would greatly increase if I could write

`var listener = new Listener<SomeEvent>(FLAG_1 | FLAG_3, handler);`

We have static extensions that allow us to refer to methods of external classes as if they were native. We can also import enum and reference its constructors without specifying the enum type itself. If this is a flat listing, then in fact we can refer to external constants as our own. So why not give the same functionality for class constants, because it looks quite logical?

**Comment by nadako** [comment]
This is already possible with `import SomeEvent.*` (or specific static field name).

**Comment by RedHairHead** [comment]
Cool. Haxe is great! Sorry for my stupid question, I just started to learn this wonderful language.
