### ISSUE TITLE
ListIterator Inline

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8294]
If we make a `List` wrapper, we will lose the inline iteration. This is easy to fix if the `ListIterator` class is made public.

```haxe
class ListWrapper<T> {
	var _list = new List<T>();
	inline public function iterator():Iterator<T> { //you can return ListIterator if it is not hidden as private
		return _list.iterator();
	}
}
```

Is there a way to get the same result without editing the STD library?

**Comment by nadako** [comment]
> Is there a way to get the same result without editing the STD library?

I think if you remove the `:Iterator<T>` type hint and leave it to type inference, it will be inferred to `ListIterator<T>` and thus will be inlined. But your use-case shows that maybe we indeed should make the iterators public...

**Comment by RedHairHead** [comment]
Thanks, it really works. Haxe is a simple language in a good way, but this method does not seem intuitive.

**Comment by Simn** [comment]
The iterator problem is tracked in #7379.
