### ISSUE TITLE
Open questions regarding the `>= version()` syntax

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8297]
This behavior is rather confusing:

```haxe
#if (haxe_ver >= version("4")) // true
#if (haxe_ver >= version("4.0")) // true
#if (haxe_ver >= version("4.0.0")) // false
```

`haxe_ver` is a float, so a version like `4.1.2` is actually represented as `haxe_ver = 4.102` under the hood (two digits for the patch). I'm not quite sure what implications this has for `>= version()` checks.

**Comment by Gama11** [comment]
Hm, this suggests that the patch version is somehow ignored entirely?

```haxe
#if (haxe_ver == version("4")) // false
#if (haxe_ver == version("4.0")) // true (?!)
#if (haxe_ver == version("4.0.0")) // false
```

**Comment by Gama11** [comment]
I think there's an open question here of what exactly this is meant to be / meant to be used for.

I would argue that instead of simply splitting a string by dots, `version()` should respect SemVer semantics, since most of the time you're probably going to comparing versions that come from Haxelib defines (and those use SemVer). This includes properly comparing versions with pre-releases such as `-rc.2` (https://semver.org/).

>identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

It might then make sense to introduce a new `haxe_ver` define with a different name that includes the pre-release and avoids any issues by it currently being a float?

Also, I don't think it's allowed to omit the patch and / or minor version in a SemVer. That would mean that the current `hl_ver` value `1.10` would _not_ be valid.

**Comment by Gama11** [comment]
It's also worth thinking about whether it would be better to use `semver()` instead of `version()` in that case.

**Comment by ncannasse** [comment]
We still don't handle the -alpha etc.

**Comment by Gama11** [comment]
It's actually probably not correct to support `version("4")` and `version("4.0")` if this is intended as SemVer, since minor and patch versions are not optional (so `hl_ver` doesn't follow SemVer either).

**Comment by ncannasse** [comment]
We should support full semver comparison, but I think we should allow
"short semver" creation.

**Comment by ncannasse** [comment]
One reason for that is that it should actually even be forbidden to use
version("4.1.5") because you're not supposed to check against a minor
revision (according to semver it should not affect the runtime)

**Comment by Gama11** [comment]
The problem is that since the SemVer spec doesn't allow "short versions", any version that doesn't have three components also doesn't _look_ like a semantic version, which can lead to confusion. For instance, to this day I'm not really sure if HL follows SemVer or not, as the release page only has major and minor (e.g. 1.9), but on the command line, it outputs 1.9.0.

The way I see it, this is mostly a readability vs. brevity argument - "abbreviated" versions might be slightly shorter, but potentially confusing to the reader. We already went with the more readable `version()` over `ver()`, even though it's longer.

>it should actually even be forbidden to use version("4.1.5")

That seems like a bad idea, it's perfectly reasonable to check against patch versions if you depend on a particular bugfix of some library. You can even already do this with the old string comparisons, so people would just continue to use that (which we don't want).

Also, I don't think the SemVer spec implies this? It specifies how patch versions should be compared, after all.

>according to semver it should not affect the runtime

I don't think that's the correct interpretation of the spec? A bugfix release of some software would obviously affect the runtime behavior, otherwise it hasn't fixed anything. "Backwards-compatible" refers to the API only:

> Bug fixes not affecting the **API** increment the patch version [...]

**Comment by Gama11** [comment]
I guess the actual / most reasonable definition of backwards-compatibility in SemVer is "don't break _expected_ behavior": https://github.com/semver/semver/issues/256#issuecomment-348799884

**Comment by RealyUniqueName** [comment]
> One reason for that is that it should actually even be forbidden to use version("4.1.5") because you're not supposed to check against a minor revision (according to semver it should not affect the runtime)

This is not pragmatic. It's quite often to have a workaround for bugs in libraries.
E.g.
```haxe
//there were a bug in text size calculation, which was fixed since openfl 1.2.3
#if (openfl < "1.2.3")
  textField.height += 2;
#end
```

**Comment by Gama11** [comment]
I think there's still an open question here that there wasn't a final answer for:

 ### Should we really support "short semvers" (which violate the spec)?

Versions such as `version("4")`, `version("4.0")` or `version("4-rc.2")` are not valid according to SemVer, but currently are valid on the dev branch.

#

So far, it seems that both @ncannasse and @RealyUniqueName are in favor of this. However, @Simn, @ibilon  and @Aurel300 and I myself have voiced concerns over this:

>@Simn In general I don't like this "almost sticking to specs" that we keep doing

>@ibilon it's indeed not something you'd type often anyway, probably not worth it

>@Aurel300 My intern non-vote goes towards supporting proper SemVers only

I think it's best to err on the side of being less permissive here. If short SemVers give an error for now, it's still possible to permit them at a later date if it turns out it's really needed. The inverse of making it less permissive on the other hand is not easily possible, since that would be a breaking change.

Curious to hear more opinions on this.

**Comment by RealyUniqueName** [comment]
I don't have strong opinion on that. Count me as abstained from voting.

**Comment by RealyUniqueName** [comment]
OTOH specs are invented for a reason :)
I vote against short versions, after all.

**Comment by ncannasse** [comment]
We should support full semver syntax and comparison, which includes the -alpha etc.

But I think we should allow as well "short ver" where 4 stands for "4.0.0" and 4.1 stands for "4.1.0". Only these two cases, and nothing more. That does not break anything, and allows to actually use  version(4.1) without the quotes which I find more neat than version("4.1.0"). We could restrict that to Int/Float constants only if you want to have only semver for strings.

**Comment by Gama11** [comment]
There could also be SemVer literals in `#if` if this is only about saving characters / avoiding quotes. Then you technically wouldn't even need `version()`, though that would feel a lot less explicit.

Allowing floats in `version()` sounds messy to me...

**Comment by Simn** [comment]
Let's please go for clarity over saved keystrokes here. This isn't even something that is frequently used, so sticking to the established standard without trying to have clever exceptions is better.
