### ISSUE TITLE
haxe_ver format

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8302]
Starting from haxe4 , we should use `haxe_ver=4.x.y` now that we have `#if version()`
I don't think this will cause problem when using old 3.x compiler, but it's late so I'm not 100% sure

**Comment by Gama11** [comment]
I guess it should also include pre-release suffixes like `-rc.2` if that is supported in comparisons?

**Comment by kevinresol** [comment]
This version thingy should really be fully semver compliance. 

Dislike half-baked, non-standard solutions.

**Comment by Gama11** [comment]
One thing that's a bit unfortunate is that `#if version()` won't be useful for a while, because it can't be used to guard against Haxe versions that didn't support it yet (would fail with `Invalid conditional expression`).

**Comment by ncannasse** [comment]
Yes we should support full semver, that's why I reopened
And yes I'm aware of the backward compatibility issue, but there's not much
we can do expect release an updated 3.4.x with the feature added.

**Comment by R32** [comment]
I found that `(haxe_ver >= "4.0.0")` is already available.  and the `(my_haxelib >= "0.1.0")` is the same

**Comment by Gama11** [comment]
@R32 Yes, but that's a string comparison, meaning that checks like `(my_haxelib >= "0.10.0")` will fail in unexpected ways. And it doesn't account for the aforementioned suffixes.

**Comment by Gama11** [comment]
It looks like version checks like this will continue to work fine if `haxe_ver` is a SemVer:

```haxe
#if (haxe_ver >= "4.0.0")
```

But checks like this will start failing:

```haxe
#if (haxe_ver >= 4)
```

Both of these are being used, so I'm not sure what to do about that. Would it be acceptable to break the latter and tell people to switch to the former syntax (or `#if haxe4`)?

**Comment by Gama11** [comment]
Alternatively, perhaps breaking changes could be avoided by making `haxe_ver` / `Float` comparisons a special case in the compiler?

**Comment by RealyUniqueName** [comment]
Maybe compiler should provide new version value in just "haxe" like it's done for libraries?
```haxe
//works for libraries 
#if (utest <= "1.9.0")
#end

//doesn't work for the compiler :(
#if (haxe >= "4.0")
#end
```
Also, I think, we can emit a deprecation warning for string version comparisons, but keep them working too.
```haxe
#if (utest <= "1.9.0") // Warning: string version comparison is deprecated. Use `utest <= version("1.9.0")` instead.

#if (utest <= version("1.9.0")) // Ok!
```

**Comment by Gama11** [comment]
I agree that `haxe` would sound more natural than `haxe_ver`, and it would also nicely side-step the compatibility issues (and the `haxe` define should probably be reserved anyway). `haxe_ver` could still be kept around for a while for backwards compatibility.

A deprecation warning would be rather annoying for library authors though, at least for the moment, because most libraries want to stay backwards-compatible with Haxe 3.4 for a while. It's the same issue as we had with deprecation warnings for `@:enum` and such. Maybe a deprecation warning for this could be introduced later.
