### ISSUE TITLE
 File "_build/src/typing/typeload.ml", line 760, characters 2-8: Assertion failed

### ISSUE THREAD

**Issue by axelhuizinga** [HaxeFoundation/haxe#8307]
my php project compiles fine on windows with 4.0.0-rc.2+77068e10c but on 
debian with 4.0.0-rc.2+77068e1 I get only
File "_build/src/typing/typeload.ml", line 760, characters 2-8: Assertion failed

**Comment by RealyUniqueName** [comment]
Can you provide a sample?

**Comment by axelhuizinga** [comment]
> Can you provide a sample?

looks like the import php.Web is the culprit
```haxe
package;

import php.Web;

class Main
{
	static function main() 
	{
		trace('hello :)');
	}
}
```

**Comment by RealyUniqueName** [comment]
I cannot reproduce it with that sample.
Have you tried with the latest dev haxe (77068e1 is two months old)?
What's your hxml settings?

**Comment by RealyUniqueName** [comment]
Also, did you make any changes to std on your linux machine? It looks like something is wrong with core classes.
Try reinstalling Haxe.

**Comment by axelhuizinga** [comment]
> Also, did you make any changes to std on your linux machine? It looks like something is wrong with core classes.
> Try reinstalling Haxe

yes - deleting the /usr/share/haxe/std before reinstalling solved the issue
