### ISSUE TITLE
[feature request] Unique name generation for macro

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8312]
Somtimes you need temp variables in macros.
But its difficult to declare it.

For example:
http://try-haxe.mrcdk.com/#1cA5a

(Yes, you can rename the variable in the macro, but if you work for a library, you can not know what name the developer is using.)

Currently i loop through the expression. Store all names in a array.
Create a name and count up a counter if this name exists in this array.

**Comment by RealyUniqueName** [comment]
That's quite easy to solve with something like this:
```haxe
class UniqueTmp {
  static var id = 0;
  static public function next():String {
    return '__tmp${id++}__';
  }
}

// and then in a macro:
var tmp = UniqueTmp.next();
return macro {
  var $tmp = 0;
  trace($i{tmp});
};
```

No need to add anything to the compiler or std.

**Comment by Simn** [comment]
I agree, this should be easy with a custom prefix.

**Comment by lublak** [comment]
@RealyUniqueName 
But if you use this method you always comes to the point that other developers use the variable __tmp0__. (If he also needs a temp variable).

http://try-haxe.mrcdk.com/#B9A40

**Comment by RealyUniqueName** [comment]
You can use whatever name teplate you want. E.g. I doubt you will face any collisions using `__lublakTmp__` instead of `__tmp__`  :)

**Comment by lublak** [comment]
@RealyUniqueName and if the developer use this variable? :P
okay okay xD it's was just an idea.
I think it is very unlikely.
