### ISSUE TITLE
[bug] Inline with type parameter

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8317]
The compiler reports an error when inlining method from a superclass using a type parameter.

Haxe 4.0.0-rc.2

```haxe
class Event {}

class Dispatcher<TEvent:Event> {
	private function dispatchObject(event:TEvent) {}
}

class SomeEvent extends Event {
	public function new() {}
}

class SomeDispatcher extends Dispatcher<SomeEvent> {
	public function new() {}

	public function dispatch():Void {
		dispatchObject(new SomeEvent()); // It`s OK

		inline dispatchObject(new SomeEvent()); // SomeEvent should be Dispatcher.TEvent

		inline dispatchObject(cast new SomeEvent()); // error: Dispatcher.TEvent should be SomeEvent

		var event:Dynamic = new SomeEvent();
		inline dispatchObject(event); // It`s OK
	}
}
```

**Comment by RealyUniqueName** [comment]
If `dispatchObject` is declared `inline`, then `dispatchObject(new SomeEvent());` still works. 
I guess it's a bug in the new feature of call-site inlining.

**Comment by RedHairHead** [comment]
> If `dispatchObject` is declared `inline`, then `dispatchObject(new SomeEvent());` still works.

But in this case inline has no effect. At least for js target

**Comment by RedHairHead** [comment]
I apologize, my previous message is incorrect (I forgot to delete --no-inline flag). But then it seems strange to me that despite this flag the  call-site inlining is still working.
