### ISSUE TITLE
Dynamic-typed expression got typed...

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#8319]
Here is a bug that occurs in Travis CI Xenial environment, but not Trusty/Mac, nor my local Ubuntu Xenial Docker container on Mac. Haxe version is `4.0.0-rc.2+30f0228`. Somehow it didn't occur with Haxe 3.4.7, but I doubt it is a regression.

The [build log](https://travis-ci.org/HaxeFoundation/format/jobs/535588574):
```
../../format/agal/Writer.hx:76: characters 14-23 : format.agal.Reg should be format.agal.Tex
../../format/agal/Writer.hx:76: characters 14-23 : format.agal.Reg has no field flags
../../format/agal/Writer.hx:76: characters 14-23 : For function argument 't'
../../format/pex/Reader.hx:23: characters 18-22 : Warning : This typedef is deprecated in favor of haxe.xml.Access
../../format/pex/Reader.hx:102: characters 16-20 : Warning : This typedef is deprecated in favor of haxe.xml.Access
The command "haxe all.hxml" exited with 1.
```

The [relevant lines of code](https://github.com/HaxeFoundation/format/blob/cb67bd5d073f69ea74430a19125641c835d9aabc/format/agal/Writer.hx#L75-L78):
```haxe
 if( idx == idTex ) 
 	writeTex(params[2]);  // This line is Writer.hx:76. `params` is `Array<Dynamic>`.
 else 
 	writeSrc(params[2]); 
```

`writeTex` is `Tex->Void`; `writeSrc` is `Reg->Void`. So it looks like the compiler got the `Reg` type for `params[2]` and used it...

**Comment by andyli** [comment]
I know one can workaround it, but I guess the error isn't expected behaviour. Should we reopen?

**Comment by Simn** [comment]
We don't propagate `Dynamic` in our type system, so if I understand correctly this behavior is expected.

**Comment by andyli** [comment]
But then why the build failure only occurs in Travis's Xenial env but not any other?

**Comment by ncannasse** [comment]
Might be a question of haxe compiler version. Did we changed the behavior somehow?
