### ISSUE TITLE
 [bug] Context.defineType compiler cache: Type is redefined (genericBuild)

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8320]
The compiler reset the static variable of my macro. That is fine. But somtimes (not everytime) the Type is cached.

```haxe
private static var _arity = new Array<Int>();
public static function build() {
    return switch (Context.getLocalType()) {
        // .......
        if(_arity.indexOf(arity) == -1) {
            // defines the Type here
            _arity.push(arity);
        }
        // .......
    }
}
```

Sometimes in display somtimes also in the build and somtimes it works.

**Comment by Simn** [comment]
Sorry, what?

**Comment by ncannasse** [comment]
You need to use `@:persistent static var ...` to have your statics not reset by macro context.

**Comment by lublak** [comment]
@ncannasse sorry for my issue and thank you :).
