### ISSUE TITLE
`_obj` appended to extern enums

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#8325]
For example, I have a native C++ enum

```c++
typedef enum rs2_stream
{
    RS2_STREAM_ANY,
    RS2_STREAM_DEPTH   
...
```

To access this in haxe I try to use an `extern enum abstract`
```haxe
@:native("rs2_stream")
extern enum abstract StreamType(Int) {
    var RS2_STREAM_ANY;
    var RS2_STREAM_DEPTH;
...
```

Which very nearly works, but the generated code looks like `rs2_stream_obj::RS2_STREAM_DEPTH`. So `_obj` is being appended preventing the code from compiling. I know this was mentioned a little in https://github.com/HaxeFoundation/hxcpp/issues/769 but I don't fully understand the reason for `_obj` (I've run into this issue with classes to). Shouldn't the `@:native` ident be used as-is?

If the resolution is that this is a bug then I'm happy to attempt to fix

-----

Just want to add that I am _loving_ hxcpp! It's been an absolute breeze to use it for native interfacing

**Comment by RealyUniqueName** [comment]
It's because `@:native` meta is on an abstract and not on an implementation class, which is generated at compile time.
I guess we can copy `@:native` meta to impl class. 
Could it opentially break something if auto-generated class name will be changed?
OTOH if someone is using `@:native` on an abstract he probably should not be surprised if implementation class gets renamed.

**Comment by RealyUniqueName** [comment]
We have a code, which rely on auto-generated names in compiler.
E.g.:
https://github.com/HaxeFoundation/haxe/blob/8f2538b0a77c1f71c33b205d40aafdac9adc6b75/src/optimization/dce.ml#L459-L468
OTOH if someone is using `@:native` on an abstract he probably should not be surprised if implementation class gets renamed.

**Comment by haxiomic** [comment]
That makes sense @RealyUniqueName – I can see why it could cause issues to copy the `@:native` to the implementation class. It seems like adding `@:native` to all fields seems to works so I'll close this in favour of doing that :)
```haxe
extern enum abstract StreamType(Int) {
    @:native("rs2_stream::RS2_STREAM_ANY")
    var RS2_STREAM_ANY;
    @:native("rs2_stream::RS2_STREAM_DEPTH")
    var RS2_STREAM_DEPTH;
...
```
