### ISSUE TITLE
Using static functions on strings points to Iterable version resulting in Compiler failing

### ISSUE THREAD

**Issue by remiX-** [HaxeFoundation/haxe#8328]
Hey guys, seems like String being an iterable now is causing compiler to look at class for extending a class with a generic for iterable usage... ?

Have no idea how to explain this but is this issue known? Seems to be occurring on latest dev build. Example is buddy @ https://github.com/ciscoheat/buddy/blob/master/src/buddy/Should.hx#L310 ... doing "my string".should.contain(x); breaks compiler saying String should be Int For function argument 'o' but is fine on haxe 4 preview 4 .. Tested it in an isolated proj too

So I have a Banana<T> class which 2 classes extend, one for String and another for Iterable being class StringBanana extends Banana<String> and class IterableBanana<T> extends Banana<Iterable<T>> which both have a static public function banana (like buddy's should)  and a 'contain' function.

Now if I have a Main.hx that does something like this: "this is not a t3st".banana.contain("test"); it point's to IterableBanana<T> and not StringBanana

Full code:
Main.hx
```haxe
package ;

import haxe.PosInfos;

using Banana;

class Main
{
    static function main()
    {
        "this is not a t3st".banana().contain("test");
    }
}
```

Banana.hx
```haxe
package ;

import haxe.PosInfos;

class Banana<T>
{
    var value:T;
    
   	public function new(value:T)
	{
		this.value = value;
	}
}

class StringBanana extends Banana<String>
{
    static public function banana(str:String)
	{
		return new StringBanana(str);
	}
    
   	public function new(value:String)
	{
		super(value);
	}
    
    public function contain(substring : String, ?p : PosInfos)
	{
        trace(value.indexOf(substring) >= 0);
	}
}

class IterableBanana<T> extends Banana<Iterable<T>>
{
    static public function banana<T>(value:Iterable<T>)
	{
		return new IterableBanana<T>(value);
	}
    
   	public function new(value:Iterable<T>)
	{
		super(value);
	}
    
    public function contain(o : T, ?p : PosInfos)
	{
        trace(o);
	}
}
```

Error:
>String should be Int For function argument 'o'

**Comment by RealyUniqueName** [comment]
Minimal sample:
```haxe
class Test {
	static function main() {
		$type(banana("hello")); // Iterable<Int>
	}

	static function banana<T>(value:Iterable<T>):Iterable<T> {
		return value;
	}
}
```
There is nothing wrong here, because in Haxe 4 `String` is actually `Iterable<Int>` - an iterable over char codes.
To workaround your issue, you can move `StringBanana` declaration below `IterableBanana` to make It picked first on resolving `"".banana()` field access.
