### ISSUE TITLE
Make String non-Iterable again!

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#8329]
From slack:

> question: do we really want `String` to be `Iterable`?
> wouldn't it be better to add `@:using(StringTools.StringIteration)` (or wherever the code should go)?
> I still think `String` should become an abstract in some distant future and the less types we let if unify with, the less painful this transition will be

Alex likes it:

> I like the idea.
> The need to deal with String as a class instance in dynamics and structure unification requires > a lot of hacks in generators and at run time.

And Simn didn't hesitate to express his unrestrained love for this proposal:

> Yes that doesn't sound like the worst idea you've ever had...

So, how about it?

**Comment by RealyUniqueName** [comment]
Thought, it's probably a too big change for 4.0 at this point.

**Comment by Simn** [comment]
If we change it we have to change it now.

**Comment by Gama11** [comment]
@RealyUniqueName might mean the "String should be abstract" change? It seems only the "make string not iterable" part should / could happen now.

**Comment by back2dos** [comment]
Yeah, I'm not proposing to make `String` an abstract now. Simn said the timing is bad for that, so I guess that's what it is. I would however prefer to keep the barrier for such a change low.

**Comment by RealyUniqueName** [comment]
Oh, right. Then it should be ok for now.

**Comment by fullofcaffeine** [comment]
So, if I understood it right, to make `String` iterable on `nightly`, I need to do add a `using StringTools.StringIteration` at source file or `import.hx` level?

**Comment by Aurel300** [comment]
@fullofcaffeine No, with #8331 `@:using` is added onto `String`, so all `StringTools` methods are available on `String` by default. `StringTools` will also have `iterator`, making `String` iterable.

**Comment by fullofcaffeine** [comment]
@Aurel300 Got it, thanks 👍

**Comment by ncannasse** [comment]
I've commented on #8331. For a similar reason, I'm not in favor of String being an abstract. Yes I understand it requires some extra platform support but that's as much the haxe developer doesn't have to deal with on a daily basis.
