### ISSUE TITLE
Completion issue with tink_web's Remote

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#8333]
I'm not getting any completion for the `tink_web` `Remote` proxy object:

```haxe

typedef Some = {
  a: Int,
  b: String
}

var remote = new Remote<Root>(new JsClient(), new RemoteEndpoint(new Host('localhost',         // Completion works for the var below. If you try
// bar. <-- it will correctly show the popup with `a` and `b`
var bar: Some = {a: 1, b: 'Foo'};
trace(bar.a);
       
// Completion *does not work* for the remote object though:
remote.  // <-- nothing happens, no completion

remote.hello().handle((o) -> {
   o. // <--- nothing happens, no completion
   trace(o);
});
```

Full sample project here: https://github.com/fullofcaffeine/tink-web-proxy-sample/tree/completion-issue. Just open it in vshaxe and try getting intellisense completion for the `remote` instance here: https://github.com/fullofcaffeine/tink-web-proxy-sample/blob/completion-issue/Client.hx#L26. Also, type inference/completion is not working for the `o` param passed to the `handle` callback in the same code linked above.

### Env

* OS: Linux Mint
* Haxe `4.0.0-rc.2+92c7833`  (managed by [lix](https://github.com/lix-pm/lix.client));
* vshaxe `2.11.0`;

**Comment by fullofcaffeine** [comment]
Ping... does anyone know if this is a Haxe issue or if I should close this and create an issue @ the tink_web repo instead? Thanks!

**Comment by RealyUniqueName** [comment]
Sorry, I tried to assemble your sample, but failed. Then got distracted and forgot about it. I'll try again tomorrow.

**Comment by fullofcaffeine** [comment]
@RealyUniqueName Oh, no worries, thanks for looking into it! What issues did you have while trying to set it up? If you need help setting the sample up, let me know. Thanks!

**Comment by RealyUniqueName** [comment]
I had some troubles with lix and my custom Haxe setup

**Comment by fullofcaffeine** [comment]
@RealyUniqueName Created a branch that uses local haxelibs here: https://github.com/fullofcaffeine/tink-web-proxy-sample/tree/without-lix.

As a side note, compiling this project takes almost 3 seconds. For such a small sample project, this is way too much time, no? 

```
(without-lix)$ time haxe build.hxml               [2.5.0]
haxe build.hxml  2.84s user 0.21s system 100% cpu 3.055 total
```

Should I create an issue for that as well?

**Comment by RealyUniqueName** [comment]
Yes, please

**Comment by RealyUniqueName** [comment]
Here is the response from completion server:
```json
{
	"jsonrpc": "2.0",
	"id": 5,
	"error": {
		"code": 0,
		"message": "Compiler error",
		"data": [{
			"severity": 1,
			"location": {...},
			"message": "Variables names starting with a dollar are not allowed"
		}, {
			"severity": 1,
			"location": null,
			"message": "Cannot represent Result in JSON because tink.json.Representation<tink.macro.DirectType<2>> cannot be converted to Result"
		}]
	}
}
```

**Comment by RealyUniqueName** [comment]
The second error comes from `tink_json`: https://github.com/fullofcaffeine/tink-web-proxy-sample/blob/a872f3b/.haxelib/tink_json/0,9,0/src/tink/json/macros/Macro.hx#L142
