### ISSUE TITLE
MacroStringTools.toComplex confuse

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8342]
How about changing the implementation of the `haxe.macro.MacroStringTools.toComplex` method? It cannot return the correct path for subclasses in modules, but this does not seem to be normal behavior. In addition, the method has no documentation, so you must read its code to understand that it will never return the correct path for the subclass. And, perhaps, it would be worth changing the method name to `toComplexType` so that the API is more uniform with the `Context` and `TypeTools` classes.

**Comment by Simn** [comment]
Right, that's a bit of a poor implementation...
