### ISSUE TITLE
Code completion for extended interfaces does not work

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8345]
Starting from version 4.0.0-preview.4, code completion for extended interfaces does not work. It shows only those fields that were declared in the interface itself, but not those that were extended.

**Comment by Gama11** [comment]
Sample code:

```haxe
class Main {
	static function main() {
		var i:Test2;
		i.
	}
}

interface Test {
	var foo:Int;
}

interface Test2 extends Test {}
```
