### ISSUE TITLE
Simple sample project using tink_web takes almost 3s to compile with Haxe 4RC2

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#8346]
This sample project: https://github.com/fullofcaffeine/tink-web-proxy-sample/tree/without-lix takes almost 3 seconds. For such a small sample project, this is way too much time, no?

```
(without-lix)$ time haxe build.hxml               [2.5.0]
haxe build.hxml  2.84s user 0.21s system 100% cpu 3.055 total
```

I'm not sure if that's a Haxe or tink_web issue, though. I'll gladly close this issue and re-report @ the tink_web repo if it's not related to Haxe 4, just let me know.

### Env
* OS: Linux Mint
* Haxe `4.0.0-rc.2+92c7833`  (managed by [lix](https://github.com/lix-pm/lix.client));
* vshaxe `2.11.0`;

**Comment by back2dos** [comment]
It's best to compile with `--times -D macro-times` than just to report the total time ;)

**Comment by fullofcaffeine** [comment]
@back2dos Oh right, I totally forgot about those compiler flags. Here you go:

```
haxe --times -D macro-times build.hxml
name                    | time(s) |   % |  p% |     # | info
-------------------------------------------------------
parsing                 |   1.225 |  42 |  42 |  1368 | 
macro                   |   0.887 |  31 |  31 |  3585 | 
  typing                |   0.565 |  20 |  64 |    17 | 
    apply               |   0.259 |   9 |  46 |     2 | tink.web.macros.Routing
    merge               |   0.116 |   4 |  21 |     1 | tink.Anon
    compact             |   0.114 |   4 |  20 |     2 | tink.json.macros.Macro
    allowPackage        |   0.067 |   2 |  12 |     2 | haxe.macro.Compiler
    remote              |   0.007 |   0 |   1 |     1 | tink.web.macros.Proxify
    expect              |   0.002 |   0 |   0 |     1 | tink.json.BasicParser
  jit                   |   0.146 |   5 |  16 |  3402 | 
  add_types             |   0.112 |   4 |  13 |    19 | 
  flush                 |   0.038 |   1 |   4 |    19 | 
  execution             |   0.027 |   1 |   3 |   126 | 
    buildWriter         |   0.011 |   0 |  42 |     2 | tink.json.macros.Macro
    buildParser         |   0.007 |   0 |  27 |     1 | tink.json.macros.Macro
    apply               |   0.002 |   0 |   8 |     2 | tink.web.macros.Routing
    merge               |   0.002 |   0 |   6 |     1 | tink.Anon
    resolveDirectType   |   0.001 |   0 |   5 |    39 | tink.macro.Types
    remote              |   0.001 |   0 |   5 |     1 | tink.web.macros.Proxify
    allow               |   0.001 |   0 |   5 |    47 | tink.json.BasicParser
typing                  |   0.419 |  15 |  15 |    71 | 
filters                 |   0.177 |   6 |   6 |    20 | 
analyzer                |   0.146 |   5 |   5 | 49938 | 
generate                |   0.028 |   1 |   1 |     2 | 
  js                    |   0.028 |   1 | 100 |     2 | 
other                   |   0.005 |   0 |   0 |     1 | 
null safety             |   0.003 |   0 |   0 |     2 | 
-------------------------------------------------------
total                   |   2.890 | 100 | 100 | 54989 | 
```

**Comment by back2dos** [comment]
So, well, looks like the bulk of it all is parsing and macros. Something is definitely off with the parsing, but I have no idea how to even investigate that. But the time you're getting is just not normal.

As for macros, their actual execution is 27msecs, which is not ideal, but at least in a reasonable proportion with the project size. The rest is simply the time needed to init all that stuff. When compiling with the server, this should disappear once the cache is hot. I've already asked about the possibility to somehow precompile macros: https://github.com/HaxeFoundation/haxe/issues/8275. Unfortunately, this seems to be quite the challenge.

**Comment by Simn** [comment]
Could you checked if this improved in recent Haxe versions?

**Comment by Simn** [comment]
Closing due to lack of followup.
