### ISSUE TITLE
[cs]  assembly strict/meta support

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8347]
Haxe supports: `@:strict` and `@:meta`

Is there any support for `@:assemblyStrict` and `@:assemblyMeta`?

"assembly annotations" needs to be over the namespace.

```cs
[assembly: ...]
```

`...` = the same content as @:strict and @:meta

**Comment by RealyUniqueName** [comment]
Doesn't `@:meta("assembly: ...")` already work?

**Comment by lublak** [comment]
@RealyUniqueName no because @:meta build it into the namespace:
Also strict is impossible

```cs
namespace a.package.of.haxe {
	[assembly: ...]
```

"assembly annotations" needs to be over the namespace.

```cs
[assembly: ...]
namespace a.package.of.haxe {
```

a hacky solution 

create a file without package and add keep (it's create a extra c# class, so its very ugly)

```haxe
@:meta('assembly: System.Reflection.AssemblyVersionAttribute("0.0.1")')
@:keep class VersionInfo {}
```

**Comment by RealyUniqueName** [comment]
Lookuing at C# generator I cannot find anything related. Most likely it's a new feature to implment.

**Comment by kLabz** [comment]
Working on this! (still need to find more information about `@:strict` and `@:assemblyStrict`)

**Comment by lublak** [comment]
@kLabz nice 👍 what information do you need about @:strict?
In https://github.com/HaxeFoundation/haxe/pull/3954 it was added to haxe.
