### ISSUE TITLE
[Macro] Get Type from the string like 'haxe.ds.StringMap<Int>'

### ISSUE THREAD

**Issue by RedHairHead** [HaxeFoundation/haxe#8356]
The parser is able to process a string of the form `'haxe.ds.StringMap<Int>'` and get a path with type parameters, but the user does not have this option.
Tools such as `Context.getType()`, `Context.parse()`, `MacroStringTools.toComplex()` do not work.
But you can use a simple trick:

```haxe
var strPath = 'haxe.ds.StringMap<Int>';
var e = Context.parse('var fake:$strPath', Context.currentPos());
var complex:ComplexType = e.expr.getParameters()[0][0].type; // Exactly what is needed
```

Why not get the existing functionality and not give it to the programmer? This would be very useful, especially since we cannot store such types in the pure form of metadata.

**Comment by nadako** [comment]
Why are you trying to go the long/heavy way of string parsing here, instead of just constructing the `ComplexType` yourself, by either using one of its [constructors](https://api.haxe.org/haxe/macro/ComplexType.html) or by [reification](https://haxe.org/manual/macro-reification-type.html)

**Comment by RedHairHead** [comment]
In my situation, I need to pass the full type for the macro through the metadata, but I can't just specify it, because `<>` characters are defined as operators.

I considered different options, but passing a string value was the easiest solution. Then I saw that the parser was able to process this value and decided that it would be useful to publish this function, since it is already ready.

**Comment by RedHairHead** [comment]
If you need a more specific example, then I can describe it, but sorry for my english. 

I use an event model and the events in the classes are set as follows:
```haxe
class Observable {
    @:eventu.dispatcher(dispatchValue)
    public final onValueChanged:IQueueOfListeners<ValueEvent<T>> = new EventDispatcherImpl();
}
```
The macro creates the `dispatchValue` method, which has the same signature as that of the event constructor and generates the dispatching process itself, based on the specific `EventDispatcherImpl` class.

Next, I want to send a descendant of the `ValueEvent` class through the same dispatcher. It looks like this:

```haxe
class Observable {
    @:eventu.dispatcher(dispatchValue)
    @:eventu.dispatcher(dispatchValueWithError, 'ValueEventOrError<T, Error<String>>')
    public final onValueChanged:IQueueOfListeners<ValueEvent<T>> = new EventDispatcherImpl();
}
```

Or in the descendant of the class containing the dispatcher through the class metadata

```haxe
@:eventu.dispatcher(onValueChanged, dispatchValueWithError, 'ValueEventOrError<T, Error<String>>')
class ExtraObservable extends Observable{}
```

As I said, the created method copies the event constructor signature. Thus, I got rid of the need to create an event instance even when there are no listeners and the need to check the presence of listeners manually each time. So I can't just create one method through which different types of events will be sent. Therefore, I specify types through metadata, and as a result this question has arisen. If the mechanism that turns a string into a type is difficult or impossible to allocate, then you can close the topic, but if it is possible, then why not?

**Comment by Gama11** [comment]
Possibly related to https://github.com/HaxeFoundation/haxe-evolution/pull/44 and https://github.com/HaxeFoundation/haxe/issues/7763?

**Comment by RealyUniqueName** [comment]
As a workaround, you can do this:
```haxe
@:eventu.dispatcher(dispatchValueWithError, type:ValueEventOrError<T, Error<String>>)
```
It is represented as `ECheckType` constructor of `haxe.macro.Expr.ExprDef`

**Comment by RealyUniqueName** [comment]
I don't think we have anything to do here.
I'll go ahead and close this issue. Feel free to reopen if you think there is something to address.
