### ISSUE TITLE
[display] "code has no effect" false positive for named local function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8359]
Original issue reported at https://github.com/vshaxe/vshaxe/issues/331 by @Ghouly-The-Ghost:
____

My (tested) working code is being grayed out and labeled as "code has no effect.

**Preview:**
![image](https://user-images.githubusercontent.com/29788070/54745262-537e5580-4b86-11e9-9415-e76a9825661d.png)

**Snippet**:
```haxe
var active = false;
var callback: ()->Void;  // Can't even declare it on the same line . . . (language issue)
callback = function original(){
    if( active ){ return; }
    active = true;
    // Do any sort of mutation here ( 'active = true' already is one )
    callback = function(){
        active = false;
        callback = original;
    };
};

callback();
callback();
```

*Note*: This snippet is very dirty and is a result of quickly prototyping some code.

Thanks!

**Comment by RealyUniqueName** [comment]
Here is what comes to diagnostics:
```haxe
{
	var active = false;
	var callback;
	callback = {
		@:mergeBlock {
			var original = null;
			original = function() {
				<...>
			}
			original; //this one has no effect
		}
		original;
	}
	<...>
}
```

**Comment by RealyUniqueName** [comment]
I wonder if named local function declaration should be prohibited to be used as a value. @Simn?

**Comment by Simn** [comment]
I thought they were...

**Comment by Gama11** [comment]
Why? That can be pretty convenient.

**Comment by Simn** [comment]
Right, this keeps coming up and you always throw some obscure event listener example at me...

**Comment by Aurel300** [comment]
@simn It might even be used in the stdlib eventually :D

https://github.com/Aurel300/haxe-sys/blob/60aa913ff4971cf1fa11913b2ec48e65555845d0/haxe/async/Event.hx#L11-L14

**Comment by kevinresol** [comment]
Yes I always do what @Aurel300 posted. It is convenient to declare a named function right in place, for type inference for example.
