### ISSUE TITLE
error: ‘class String’ has no member named ‘utf8_str’; did you mean ‘c_str’?

### ISSUE THREAD

**Issue by sgalland** [HaxeFoundation/haxe#8362]
Hello,

I am getting this error when compiling C++ targets on Linux and I am not sure what projects purview this problem falls under(whether its Haxe, HXCPP or even OpenFL's) but I am thinking its a transpiler issue.

My build environment:
OpenFL: 8.9.1
HXCPP: 4.0.8
Haxe: 4.0.0-rc.2

Actual error message:
```
Error: ./src/cpp/Prime.cpp: In static member function ‘static Dynamic cpp::Prime_obj::_loadPrime(String, String, String, hx::Null)’:
./src/cpp/Prime.cpp:33:46: error: ‘class String’ has no member named ‘utf8_str’; did you mean ‘c_str’?
HXLINE( 40) const char* this1 = signature.utf8_str();
^~~~~~~~
c_str
```

Replication steps:
run "openfl create project <name of project>"
run "cd <name of project>"
run "openfl build linux"

**Comment by RealyUniqueName** [comment]
I can reproduce with hxcpp 4.0.8, but it's not reproducible with the latest git hxcpp. 
Seems fixed.
