### ISSUE TITLE
Test `String.indexOf(s, startIndex)` for negative `startIndex`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8365]
Currently we don't have tests for negative `startIndex` of `String.indexOf` and `String.lastIndexOf()`.

**Comment by Simn** [comment]
I think we do, but I forget where. Maybe some issue test.

**Comment by RealyUniqueName** [comment]
Negative `startIndex` is not even mentioned in the doc of `String.lastIndexOf()`

**Comment by RealyUniqueName** [comment]
Now I'm confused.
Why is `String.indexOf` documented to work with negative `startIndex`? Even flash and js don't support that.
@ncannasse should we change the doc or implementations?

**Comment by RealyUniqueName** [comment]
I'd like to align all targets with JS here, but that would definitely break some projects.

**Comment by ncannasse** [comment]
Yes I understand the need for alignment.

**Comment by RealyUniqueName** [comment]
I suggest to change the doc in 4.1 from
```
If `startIndex` is given, the search is performed within the substring
of `this` String starting from `startIndex` (if `startIndex` is posivite
or 0) or `max(this.length + startIndex, 0)` (if `startIndex` is negative).
```
to
```
If `startIndex` is given, the search is performed within the substring
of `this` String starting from `startIndex`.
If `startIndex` is negative the behavior is unspecified.
```
and specifically mention it in 4.1 release note.

And then in 4.2 (or even in 5.0) change the doc and targets behaviors to be the same as JS.
Which is like this:
```
If `startIndex` is given, the search is performed within the substring
of `this` String starting from `startIndex`.
If `startIndex` is negative the search is performed using the whole string (same as `startIndex = 0`).
```

**Comment by RealyUniqueName** [comment]
Unspecified.
