### ISSUE TITLE
[hl] Comparing `null` to `0`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8367]
```haxe
class Main {
	static function main() {
		function check(?i:Int) {
			trace(i == 0); // false
			trace(i < 0);  // false
			trace(i > 0);  // false
			trace(i <= 0); // true
			trace(i >= 0); // true
		}
		check();
	}
}
```

**Comment by ncannasse** [comment]
Uhm. Seems like there is a  null-to-int cast being done here.

**Comment by Simn** [comment]
genhl just determines a common type between the operands and then casts both to that type. This is fine for most cases but breaks semantics when `Null<T>` gets involved because we don't want to unwrap.

**Comment by Simn** [comment]
Also I'm mildly shocked that our tests don't cover this.

**Comment by Simn** [comment]
This is pretty much superseded by #8426, but I just 4.1ed that due to gencommon cancer. Feel free to 4.1 or close this one as well if you don't want to look into it for HL at the moment.

**Comment by RealyUniqueName** [comment]
I'm closing this because it's a part of #8426 indeed.
