### ISSUE TITLE
Failing to parse `function () {} >> 1`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8372]
```haxe
class Test {
  static function main() {
    function(){} >> 1;
  }
}
```
http://try-haxe.mrcdk.com/#b391c
With 4.0-preview.1:
```
Test.hx:3: characters 5-17 : Void -> Void should be Int
```
With the latest dev:
```
Test.hx:3: characters 18-19 : Expected }
```
This breaks macros.
E.g. ufront (used in haxelib server): https://travis-ci.org/HaxeFoundation/haxelib/jobs/541299298#L661

**Comment by Simn** [comment]
IIRC that was a parser bugfix and this isn't supposed to parse.

**Comment by RealyUniqueName** [comment]
Both left and right expressions of a binop are valid. Why isn't it supposed to parse?

**Comment by Simn** [comment]
I think the problem was that this would be parsed as a call otherwise:

```haxe
function () {
    // code
}
(expr);
```

**Comment by Simn** [comment]
Hang on, I'm going off my memory here so we should at least verify and document it. Preferably here: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0

**Comment by nadako** [comment]
The ufront usage looks kinda legit though:

https://github.com/ufront/ufront-mvc/blob/65c61d79cebe72ce38f5d60b956980c96aded806/src/ufront/app/HttpApplication.hx#L470-L478

**Comment by Simn** [comment]
Uh, isn't most of that parsed as `function() (expr >> function() { })`?

**Comment by RealyUniqueName** [comment]
> I think the problem was that this would be parsed as a call otherwise:
> 
> ```hx
> function () {
>     // code
> }
> (expr);
> ```

That's a completely different case.
Now it's not possible to even overload operators on abstracts. And something like this is not possible anymore:
```haxe
class Test {
  static function main() {
    var callbacks = function() trace('initial');
    callbacks = function() { trace('second'); } + callbacks;
    callbacks();
  }
}

@:callable
abstract CallbackChain(Void->Void) from Void->Void {
  @:op(a + b) @:commutative
  static inline function chain(a:CallbackChain, b:Void->Void):CallbackChain {
    return function() { 
        a();
        b();
    }
  }
}
```
http://try-haxe.mrcdk.com/#Afe4e

**Comment by Simn** [comment]
> That's a completely different case.

To the parser it's the exact same case.

I don't understand the problem here, just add `( )` around your `function` and you're good. This addresses the inherent syntactic ambiguity of this as well.

**Comment by nadako** [comment]
> Uh, isn't most of that parsed as `function() (expr >> function() { })`?

Doesn't look so :)

**Comment by Simn** [comment]
Mentioned here: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0#function-expressions-as-operands
