### ISSUE TITLE
[RFC] cast/downcast

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8375]
In Haxe 4.0 we have deprecated Std.instance and renamed it to Std.downcast. A few comments on this:

**Deprecation Warnings**

First, I think we need some kind of special treatment wrt deprecation for this particular function. The reason is that unlike other renames (like haxe.xml.Access instead of Fast) it can apply to many different files of the code, making it hard to transition.

For instance in Heaps I have 68 calls to Std.instance in about as many different files. And I want to support Haxe 3.4 for at least until 4.1 is released, so it would require me to either `#if haxe4` all these calls or introduce my own "heaps cast" that wraps the call, both being not very nice solutions.

So I propose that instead of `@:deprecated` Std.instance we instead use `@:noCompletion`, and we will add `@:deprecated` at a later release (4.1 or later).

**Syntax**

Haxe has the following casts:

```haxe
var x : T = cast v; // unsafe cast, might exc on some static platforms only
var x = cast(v,T); // safe cast, will exc if type does not match
var x = Std.downcast(v,T); // downcast, will return null if type does not match
```

I think that `downcast` should become a keyword like `cast` so we don't have to use `Std.` for this particular cast.

In compiler: ECast would become ECast(expr,Unsafe | Safe of t | Downcast of t). That would be the same for TCast and we would implement it directly in codes generators.
In macros : for backward compatibility, I propose it should be ECast(expr,?t:ComplexType,?isDowncast:Bool)

**Comment by RealyUniqueName** [comment]
> I think that downcast should become a keyword like cast so we don't have to use Std. for this particular cast.

I think it's fine to have it as a method of `Std`. It's not so frequently used as `cast`. E.g. it's just about 500 usages in the code hosted on Github: https://github.com/search?l=&p=1&q=%22Std.instance%22+language%3AHaxe&type=Code
No need to introduce another keyword. And it's always possible to add `import Std.downcast` to `import.hx`

**Comment by Gama11** [comment]
>First, I think we need some kind of special treatment wrt deprecation for this particular function. The reason is that unlike other renames (like haxe.xml.Access instead of Fast) it can apply to many different files of the code, making it hard to transition.

I think you're _greatly_ overestimating how popular this function is. Personally, I wouldn't have noticed if it was removed entirely, as I don't think I've ever used it myself. It might be common in Heaps, but there's **not a single usage of it** across all of Flixel, OpenFL, Lime, Kha, vshaxe... Deprecation-wise, the `js.lib` or `haxe.Utf8` changes were far more problematic.

In fact, I once installed all of Haxelib for this sort of analysis. That's 55705 .hx files across 1201 libs. There's only 213 matches for `Std.instance()` across 102 files. Most of them seem to be in Heaps and an abandoned lib called json-stream. Tink has a few usages here and there. [Full results here](https://gist.github.com/Gama11/ac73f46d1bcdedf254526b8c2c8013eb).

Also, there's always `-D no-deprecation-warnings`.

**Comment by ncannasse** [comment]
Well, deprecation is one thing, and it it's only Heaps I can surely make the effort to deal with it.

However, the keyword thing is quite important, because this way it will come with proper manual documentation in cast section, and thus allow people to learn/use it correctly instead of using other forms of cast.

**Comment by Gama11** [comment]
I guess I don't quite understand why you would use `Std.downcast()` over `Std.is()` + `cast` in the first place. Is the implementation more efficient somehow..?

Looking through the usages in Heaps, most of them seem to be immediately followed by a `null` check, such as:

```haxe
var m = Std.instance(this, Mesh);
if( m != null ) out.push(m);
```

Is that really better than the following?

```haxe
if (Std.is(this, Mesh))
    out.push((cast this : Mesh));
```

#

There's also usages without null checks:

```haxe
return Std.instance(ambientShader,h3d.shader.AmbientLight).additive = b;
```

But again, you could just unsafe cast + type check here:

```haxe
return (cast ambientShader : h3d.shader.AmbientLight).additive = b;
```

**Comment by Aurel300** [comment]
> However, the keyword thing is quite important, because this way it will come with proper manual documentation in cast section, and thus allow people to learn/use it correctly instead of using other forms of cast.

I don't think this is much of an argument – It can be documented next to `cast` even if it is not a keyword.

**Comment by ncannasse** [comment]
@Gama11 : Std.is + cast performs two casts on several static targets. Also, it requires storing the expression into a local variable if you don't want double evaluation. And for the the second case, you want to trigger a null access in case the type does not match, but that would work with `cast(ambientShader,h3d.shader.AmbientLight)` as well.

@Aurel300 my suggestion was that because it's not documented as part of language documentation it's not used by many people. 

Actually instead of looking at the low amount of Std.instance, we should look into all cases where there is a `try cast(e,T) catch( e : Dynamic ) null` or `if( Std.is(e,T) ) cast(e,T)` and these should all be replaced by a proper `downcast`

I think that while `cast` can be used to do some kind Dynamic/Any checks (or for low level platform implementation), the actual most legitimate kind of cast in everyday OO programming is the downcast the way it's currently implemented through Std.instance. So it deserves a keyword on its own.

Actually my preference would be to replace `cast(e,T)` with downcast behavior, but that might break too much existing code relying on exceptions for control flow.

**Comment by Gama11** [comment]
The safe cast syntax doing something that's actually useful would indeed be nice. Safe casts as they're specified today are almost always misused (doing a `Std.is()` check and then a safe cast / never checking any exceptions / `cast(float, Int)` instead of `Std.int()` / etc)...

**Comment by ncannasse** [comment]
At least we could error when cast(e, T) and it's not possible in the type
system for e to be of type T in any way.

**Comment by Simn** [comment]
I've moved this to 4.1 because I honestly see nothing actionable here. We cannot introduce a random keyword like `downcast` for a fringe feature like this, and the deprecation warnings can easily be worked around.

**Comment by Simn** [comment]
I still see nothing actionable here, closing.
