### ISSUE TITLE
[display] hover on function in structure reports Expression instead of ClassField

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8381]
```haxe
class Main {
	static function main() {
		var f:Foo;
		f.foo();
		f.bar;
	}
}

typedef Foo = {
	/** Test **/
	function foo():Void;

	/** Test **/
	var bar:Int;
}
```

Hovering over the `foo()` call here doesn't show the docs, only the type:

![](https://i.imgur.com/by6XAnq.png)

This is because Haxe returns an expression instead of a class field. Interestingly, it works in completion or for variables, so something about functions in structures seems to be special.

**Comment by Simn** [comment]
Fixed, don't know how to add a test for it...
