### ISSUE TITLE
[display] duplicated enum abstract values in completion

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8396]
When requesting completion within an enum abstract, the values are duplicated and appear once as inline class fields, and once as enum values:

```haxe
class Main {
	static function main() {
	
	}
}

enum abstract Test(String) {
	var Foo;
	var Bar;

	function foobar() {
		
	}
}
```

![](https://i.imgur.com/oamErOZ.png)

From outside, the values only appear once as expected:

![](https://i.imgur.com/gnqwWl2.png)

**Comment by Simn** [comment]
Note that it's hiding the enum abstract field instead of the class field because that's how resolution prioritizes.
