### ISSUE TITLE
Fighting compilation server memory leaks

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8415]
The compilation server is still leaking, so I propose a general solution for this:
- use an ocaml parser in order to read our source code AST (I think @nadako did something of this kind when we experimented with ocaml-to-haxe)
- find all global mutable values ( ref [] , Hashtbl.create, etc. ) and error on them
- make sure we all replace these with something like   Global.register "name" (ref []) , so it doesn't error anymore
- add a way to dump the global names + memory size for each using `haxe --connect 6000 --display globals`

This should give us the tools we need to track and eliminate these issues, and should significantly improve the compilation server performances as 9 GB of memory takes some time to scan when doing a full GC :-/

**Comment by ncannasse** [comment]
Ping @Simn @nadako @RealyUniqueName

**Comment by nadako** [comment]
Can't say much about the strategy, but reading OCaml AST is no problem at all, you just use OCaml as an OCaml library: https://github.com/nadako/ml2hx/blob/552d5cdf2b6560c5223ba3e27b9043810fbca48c/src/main.ml#L508-L509

**Comment by RealyUniqueName** [comment]
Sounds ok to me.
Also, we already have some display request to report memory usage (I don't remember exact command). Did you try it?

**Comment by Gama11** [comment]
Yeah, the cache view in vshaxe can display memory usage:

![](https://i.imgur.com/w4jYmUN.png)

**Comment by Simn** [comment]
I've spent some time on investigating the memory situation and while I fixed various small problems, there still seems to be some sort of leaking going on. A more scientific approach like suggested here might be required.

I'm comparing the size of the cache with the memory reported used by the GC, and there's an interesting correlation. These values are from our unit tests:

target | total cache | GC heap size | factor
--- | --- | --- | ---
C# | 130 MB | 268 MB | 0.48
Java | 299 MB | 577 MB | 0.51
Js | 97 MB | 209 MB | 0.46
Eval | 81 MB | 158 MB | 0.51
Flash | 96 MB | 208 MB | 0.46
Neko | 88 MB | 182 MB | 0.48

For whatever reason, the GC heap size is roughly twice the reported total cache size. The process explorer agrees with the reported GC size, so I can see two possible causes:

1. The memory reported for the total cache is wrong.
2. We're somehow wasting a linear amount of memory.

Regarding 1., we use the `objsize` library which on the OCaml-side looks like this:

```ocaml
external internal_objsize : Obj.t -> Obj.t list -> Obj.t list -> info = "ml_objsize"

let objsize obj exclude reach = internal_objsize (Obj.repr obj) exclude reach

let size_with_headers i = (Sys.word_size/8) * (i.data + i.headers)
```

I also checked `Obj.reachable_words` from the OCaml standard library and got equal values, so it really looks like this is correct. Maybe @RealyUniqueName can double-check this on Linux to make sure we're not having some insane Windows-specific problem here.

Regarding 2., I'm a bit clueless as to what kind of data we could even persist by accident. There's some megabytes in `Lexer.all_files`, but that's not nearly enough to explain such a difference. The macro interpreter is also persisted, but again doesn't use nearly enough memory.

**Comment by ncannasse** [comment]
Just checking : did the calculus from objsize library matches
`Obj.reachable_worlds v * (Sys.word_size / 8)` ?

**Comment by Simn** [comment]
Yes, I tried `let mem_size v = Obj.reachable_words (Obj.repr v) * (Sys.word_size / 8)` and got the same results.

**Comment by ncannasse** [comment]
Another guess : GC.compact requires double size, because it needs to copy from A to B, and maybe the pages used during compaction are not immediately released at the end of it. This is something that can be easily reproduced with a standalone ocaml sample.

**Comment by Simn** [comment]
That would be so dumb I almost want it to be true... but unfortunately, doing a `Gc.full_major()` after the `compact` changes nothing.

**Comment by Simn** [comment]
I found the problem. Turns out that `Gc.compact()` isn't the diligent GC cleanup operation that we thought it was. While it does reorganize the heap, it does not necessarily shrink it. The shrinking is governed by the `space_overhead` setting, which by default sits at 80% of the live data.

In the commit I set it to a hard 0, but only for the server/memory inspection for now. This allows us to test this and verify that it indeed has the desired impact. @nadako please check with your codebase.

I suppose we'll have to measure a bit here to find good values. It might actually be legit to use a value of 0 if we trigger an explicit compaction. This way, the strategy would be to not care too much (keep the 80%?) during requests, then perform some cleanup afterwards. It might also makes sense to be a bit adaptive here because the first compilations should require much more working memory than the compilations where we pull most of the content from the cache.

**Comment by nadako** [comment]
After 456434674efae188514903163f703d1de33145c2, expanding memory view makes process memory usage go down from 1544mb to 880mb. Memory view data is:

![](https://i.imgur.com/ngEvO2w.png)

**Comment by ncannasse** [comment]
What's current status on compilation server leaking memory?

**Comment by Simn** [comment]
I'm not aware of any leaks and we clean up the cache as a "background" server task regularly.

**Comment by Simn** [comment]
I'm still not aware of any leaks, so I'll close this issue for now.
