### ISSUE TITLE
Windows 64 builds containt 32bit haxelib

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8419]
We need to fix it.

**Comment by ncannasse** [comment]
Is it an problem with installer build script ? or travis ?

**Comment by Simn** [comment]
I'm a bit confused here, hasn't haxelib always been 32bit because it's still a neko exe?

**Comment by nadako** [comment]
The problem is that if you have 64-bit neko installed, haxelib.exe won't work, presumable due to incompatible 64-bit neko.dll.

**Comment by RealyUniqueName** [comment]
Can we pack both 32bit and 64bit haxelib executables into installers and install required version based on a system neko arch?

**Comment by ncannasse** [comment]
I think we could drop Windows 32 bit installer support.

**Comment by RealyUniqueName** [comment]
Currently 64bit windows installer installs 32bit neko, so haxelib works. Which means this issue should affect only a few people who do compiler development or installed 64bit neko manually.

**Comment by ibilon** [comment]
What's the reason to have 32 bit neko installed by the 64 bit haxe installer, shouldn't it install 64 bit neko and keep the haxelib executable 64 bits?

**Comment by RealyUniqueName** [comment]
I think it just happens. Probably no one ever bothered to make sure 64bit windows installer installs 64bit neko too.

**Comment by andyli** [comment]
I will work on it today.

**Comment by RealyUniqueName** [comment]
Done. See #8587 and 5607da98f07129b596b1b9d689c2f1a58fd3252d
