### ISSUE TITLE
Uninitialized `final` var prevents completion from working

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8420]
```haxe
class A {
	final x:Int;

	function f() {
		this.|
	}
}
```

no worky: getting `This class has uninitialized final vars, which requires a constructor`, which I guess should be ignored for completion

**Comment by nadako** [comment]
I've added a quick fix for this for now, because I want completion to work for my tomorrows presentation :)
Someone please look into this and fix it properly, because I'm not sure why there's both `display_error` AND `error` used.

**Comment by Simn** [comment]
I think using `display_error` for both lines is fine in this case. We should actually avoid `error` where we can for display reasons. But that's not always so easy when we require some sort of value, and might cause some follow-up problems.
