### ISSUE TITLE
wrong position for the abstract incompatible from/to type error

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8423]
```haxe
abstract A(Int)
	from Float
{}
```

This will fail with:
```
src/Main.hx:1: lines 1-3 : You can only declare from/to with compatible types
```

Note that the position points to the whole abstract definition. Instead it should point to the `from Float`. I guess the position is lost a that point, but maybe we could preserve it?

**Comment by kLabz** [comment]
The position is available and I have something to make it throw the error on the `Float` of `from Float`. Should I make a PR?
