### ISSUE TITLE
abstract from Dynamic vs another abstract

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8425]
```haxe
abstract A(Dynamic) from Dynamic {}
abstract B(Int) {}

class Main {
	static function main() {
		var a:A = {}; // works
		var a:A = 3; // works
		var a:A = "hello"; // works
		var a:A = (null : B); // doesn't work: B should be A
	}
}
```

**Comment by nadako** [comment]
This is not a regression, but still would be very nice to fix for 4.0

**Comment by ncannasse** [comment]
This should work

**Comment by Simn** [comment]
To the compiler, this is basically a transitive cast because we go B to Dynamic to A. But I agree this looks stupid in context of what works.

I'll fix it, but we'll have to see if this creates a type-hole somehow. Then again, Dynamic is pretty much a designed type-hole, so I guess it's fine...
