### ISSUE TITLE
[hl/c] Resources are broken (compile fails or crashes)

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#8429]
Any usage of `haxe.Resource` seems to just plain crash (msvc) or fail to compile (gcc) on rc3 (no problems on rc2). works w/jit.

repro:

`build.hxml`
```
-resource hello.txt@hello
-main Test
-hl output/test.c
-cmd "gcc -o test -Ioutput output/test.c"
```

`Test.hx`:
```haxe
class Test {
	static function main() {
		trace(haxe.Resource.getString("hello"));
	}
}
```

`hello.txt`:
```
Hello, World!
```

output (linux/gcc):
```
$ haxe build.hxml 
Code generated in output/test.c automatic native compilation not yet implemented
In file included from output/test.c:40:0:
output/hl/init.c: In function ‘$init’:
output/hl/init.c:319:5: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  r3 = bytes$99831d7;
     ^
In file included from output/test.c:43:0:
output/hl/globals.c: At top level:
output/hl/globals.c:197:7: error: conflicting types for ‘bytes$99831d7’
 vbyte bytes$99831d7[] = {72,101,108,108,111,44,32,87,111,114,108,100,33,10,0};
       ^~~~~~~~~~~~~
In file included from output/test.c:40:0:
output/hl/init.c:105:14: note: previous declaration of ‘bytes$99831d7’ was here
 extern vbyte bytes$99831d7;
              ^~~~~~~~~~~~~
Error: Command failed with error 1
```

msvc builds w/warnings, then subsequently crashes in a utf8<->16 conversion function.

**Comment by Aurel300** [comment]
Does that solve the problem?

**Comment by shakesoda** [comment]
@Aurel300 that fixes it for clang, however on gcc i still get build errors. haven't tried msvc yet.

lots of this kind of stuff when building `_std/String.c`
```
/tmp/cclozvdP.s: Assembler messages:
/tmp/cclozvdP.s:76: Error: junk `(%rip)' after expression
/tmp/cclozvdP.s:76: Error: operand type mismatch for `lea'
/tmp/cclozvdP.s:111: Error: junk `(%rip)' after expression
```

**Comment by Aurel300** [comment]
Can you confirm the assembler errors only show when using resources?

I wonder if it is related to the `$` in the variable name: https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html#Dollar-Signs

@ncannasse Can we simply use `bytes_xxxxxx`?

**Comment by shakesoda** [comment]
@Aurel300 it seems to happen with all use of strings (...oh no!!)

`trace("test")` was enough to get the errors.

**Comment by Aurel300** [comment]
Ok, I think this is a separate issue, and I can reproduce it locally on Ubuntu. There was indeed a problem with the resources, because the type of the `extern` was wrong (not an array of bytes). That is now fixed.

See #8430.

**Comment by ncannasse** [comment]
Regarding `/tmp/cclozvdP.s: Assembler messages` , I would be interesting to know which exact identifier makes GCC fails like that :-/
