### ISSUE TITLE
[HL/C] Cannot compile on Linux

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8430]
(From #8429)

```haxe
class Main {
  public static function main():Void trace("test");
}
```

```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
$ haxe --main Main --hl output/test.c
$ gcc -o test -Ioutput output/test.c
/tmp/ccWBboZZ.s: Assembler messages:
/tmp/ccWBboZZ.s:2834: Error: junk `(%rip)' after expression
/tmp/ccWBboZZ.s:3403: Error: junk `(%rip)' after expression
/tmp/ccWBboZZ.s:3697: Error: junk `(%rip)' after expression
/tmp/ccWBboZZ.s:3712: Error: junk `(%rip)' after expression
# etc, etc
```

The compilation fails with hundreds of messages similar to the ones above. As far as I can tell, this might be due to the usage of `$` in `hl2c.ml` to mark every single variable. GCC manual suggests this is allowed but may trip up some assemblers:

> However, dollar signs in identifiers are not supported on a few target machines, typically because the target assembler does not allow them.
> (https://gcc.gnu.org/onlinedocs/gcc/Dollar-Signs.html#Dollar-Signs)

According to the previous issue, this may also be a regression from rc2.

**Comment by ncannasse** [comment]
I had $ in identifiers since the first initial release of HL/C I think. Could you try to pinpoint what's exactly causing the issue by looking at the assembler output at the given line ? Maybe a specific word with $ is triggering the failure.

**Comment by ncannasse** [comment]
Waiting for CI confirmation

**Comment by ncannasse** [comment]
Fix confirmed
