### ISSUE TITLE
== vs ternary and conditional if on Dynamic type

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8437]
During my test on -1 value, I found that == true and == false are returning false. Is this official Haxe strategy? If it is, please update documentation like this;

-1 == true -> -1 == 1 -> false

== converts true to a number (1), so every negative number and every positive number greater than 1 will return false.

-1 ? true : false -> true ? true : false -> true

:? converts -1 to true, so every number which is not zero will return true. Same goes for conditional if. 

http://guideto.rf.gd/dynamic.html

**Comment by ncannasse** [comment]
Dynamic types comparison, and in particular == or != between true, 1 and "true" etc, rely on native platform comparison, so they are not enforced by any specification.

**Comment by Ilir-Liburn** [comment]
Ok, but behavior I described could still go to documentation, so there are no questions asked afterwards. For example

```haxe
        untyped __cpp__("float f = 2");
        var d:Dynamic = 0.0;
        untyped __cpp__("d = f");
        trace(untyped __cpp__("f == true")); //false
        trace(d == true); // false
        trace(untyped __cpp__("f? true: false")); // true
        trace(d? true: false); // true
```

**Comment by Simn** [comment]
You've already opened #8405 for that.

**Comment by Ilir-Liburn** [comment]
@Simn, actually, I wanted that to be fixed, not documented. I fixed Dynamic type issues for myself. Feel free to use it

http://try-haxe.mrcdk.com/#8d048

**Comment by Aurel300** [comment]
@Ilir-Liburn As explained above by Nicolas, these will not be "fixed". Doing so would technically be possible (?) but would mean sacrificing a lot of performance. `Dynamic` (and in particular various binary operations on it) should not be relied upon as something consistent across target platforms.

**Comment by Ilir-Liburn** [comment]
@Aurel300, that's why I built another type abstracting Dynamic. For myself, but I shared it here if someone want to use it.
