### ISSUE TITLE
[display] completion replaceRanges are broken since rc.3

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8438]
Invoking completion after the `char` here returns no results with rc.3:

```haxe
class Main {
	static function main() {
		"".char|
	}
}
```

![](https://i.imgur.com/wKlKfOq.png)

This is because the `replaceRange` reported by Haxe is too big:

```json
"replaceRange": {
    "start": {
        "line": 2,
        "character": 0
    },
    "end": {
        "line": 2,
        "character": 9
    }
}
```
___

It works fine with rc.2:

![](https://i.imgur.com/qNg4mad.png)

```haxe
"replaceRange": {
    "start": {
        "line": 2,
        "character": 5
    },
    "end": {
        "line": 2,
        "character": 9
    }
}
```

**Comment by Simn** [comment]
I'm awkwardly bisecting this via CLI because vshaxe-debug-tools isn't working anymore for me...

**Comment by Simn** [comment]
https://github.com/HaxeFoundation/haxe/commit/4f82f3d71b4d18c5363b3943f1bcf68efd4bc1a2

**Comment by Simn** [comment]
Fixed, don't know how to test this though.

**Comment by kLabz** [comment]
I should be able to test it, I just need some time on the computer..

**Comment by Gama11** [comment]
I think he means how to unit-test it, because #8355. :)

**Comment by kLabz** [comment]
Meh, I don't know enough about these display tests for now :(
