### ISSUE TITLE
[nullsafety] Null safety + inline regression between RC2 and RC3

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#8443]
Might be related to #8442 

In RC3 the `inline` keyword seems to affect null safety unexpectedly, the following example should compile without error, however it fails to compile with null safety errors in RC3. The code will compile if the `inline` keyword is removed from `method`.

In RC2 the code compiles with or without `inline`

```haxe
class Main {
    static function main() {
        trace(new AExample());
    }
}

@:nullSafety
abstract AExample(Int) {
    public function new() {
        this = method();
    }

    static inline function method(?map: Int->Int) {
        return map != null ? map(0) : -1;
    }
}
```

Run with `haxe --run Main`

Error is `Main.hx:35: characters 16-24 : Null safety: Cannot call a nullable value.`

(tested latest nightly 8494952649b3574ccc9342847beb49ef78083bd7)

**Comment by RealyUniqueName** [comment]
This was caused by propagation of `null` constant on inlining.
The compiled code looked like this:
```haxe
this = if(null != null) {
  null(0);
} else {
  -1;
}
```
I disabled `null` propagation in 977ac29bca91805918bdc9eb6babd53d929b051a
