### ISSUE TITLE
scratching my head over this

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8447]
```haxe
        var s1 = {value:Dynamic, type:Int};
        s1.type = 0;
        trace(s1.type);

Main.hx:75: characters 9-20 : Int should be Abstract<Int>
```

From where is this Abstract type coming? Let's look at CS code after adding cast to 0

```cs
			object s1_value = typeof(object);
			object s1_type = typeof(int);
			s1_type = ((object) (((object) (0) )) );
```

It is a dynamic, initialized by typeof. Now we go to Java

```java
		java.lang.Class s1_value = java.lang.Object.class;
		//line 74 "C:\\Users\\Admin\\Documents\\Haxe\\Abstract\\Main.hx"
		java.lang.Class s1_type = int.class;
		//line 75 "C:\\Users\\Admin\\Documents\\Haxe\\Abstract\\Main.hx"
		s1_type = ((java.lang.Class) (((java.lang.Object) (0) )) );
```
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Class

I even tried this

```haxe
abstract Abstract<T>(T) {
    public inline function new(v:T) { this = v; }
       // I remember V:T worked some time in the past?
//    @:from public static inline function fromV<V:T>(v:V) { return cast v; }
}

        var s1 = {value:Dynamic, type:Int};
        s1.type = new Abstract<Int>(0);
        trace(s1.type);

Main.hx:75: characters 9-39 : Abstract<Int> should be Abstract<Int>
```

Is this something new to be used or upcoming in Haxe?

**Comment by RealyUniqueName** [comment]
You're actually storing a _type_ `Int` into a field `type` here: `var s1 = {value:Dynamic, type:Int};`
Is it really what you want to do?
Maybe, you want to do this isntead?
```haxe
var s1:{value:Dynamic, type:Int} = {value:1, type:2}
s1.type = 0;
trace(s1.type);
```

**Comment by Ilir-Liburn** [comment]
No, that's not what I want, or to use typedef. I wanted to have anonymous structure of types initialized to default values. Anyway, what is purpose of allowing such definition besides using as constraint?

**Comment by RealyUniqueName** [comment]
You definitely not going to get a default value by using a type as a value in Haxe.
I think the only reliable way to get a default value for a type using type name is a macro.
