### ISSUE TITLE
Is /libs not a submodule anymore?

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8449]
I got some error when trying to merge current version.

**Comment by Aurel300** [comment]
No, it was recently merged into the main repository (#8440). Your best bet is probably to `rm -rf libs` and pull again.

**Comment by mockey** [comment]
OK, thanks. With removing the old /libs I could merge.
I had some warnings about line-endings, thouigh:
`warning: CRLF will be replaced by LF in libs/ttflib/main.ml.`

**Comment by Simn** [comment]
Oooh so that's the problem I'm having... hang on

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/493446bea84e9f4d7d56d78c8221b9cbea3091fd

Thanks for pointing out the line end message, I was stuck trying to figure out what the problem was!
