### ISSUE TITLE
Please add @:op(A = B) if there is no other way

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8453]
Suppose I have code like this

```haxe
@:allow(Wrapper)
class Wrap {
    public function new(v:Dynamic) {
        value = v;
        type = Type.typeof(v);
    };
    var value:Dynamic;
    var type:Type.ValueType;
}

abstract Wrapper(Wrap) {
    public function new(v:Dynamic) this = new Wrap(v);
    @:from public static function from(v:Dynamic) return cast new Wrap(v);
//    @:op(A = B) public static function assign(lhs:Wrap, rhs:Dynamic) {
//     lhs.value = rhs; lhs.type = Type.typeof(rhs);
//  }
}
```

Assignment using @:from is forcing me to instantiate Wrap because there is no "this" in a static function, while using @:op(A = B) I could set fields using "lhs" reference.

Or there is other way I'm not aware of?

BTW, I used @:from prefix before the constructor by mistake, compiler was not complaining

**Comment by RealyUniqueName** [comment]
Duplicates https://github.com/HaxeFoundation/haxe/issues/5738

**Comment by Ilir-Liburn** [comment]
Please note that in @:op(A = B) I used inner type Wrap, opposite to other @:op operators which expect abstract type, because it is covered by @:from

**Comment by Ilir-Liburn** [comment]
Actually, @:op(A = B) will not help on what I'm working. I need @:op(=B) like this
```haxe
@:op(=B) public inline function assign<T>(rhs:T) {
    this.value = rhs;
    this.type = Type.typeof(rhs);
}
```
