### ISSUE TITLE
PHP TestSocket sometimes fails

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#8455]
e.g. https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=16

```
unit.spec.sys.net.TestSocket
  test: FAILURE ...............F...
    line: 52, expected 0 but it is 1
```

Not always, just sometimes...

**Comment by RealyUniqueName** [comment]
I don't see a failure on that link

**Comment by andyli** [comment]
That's because I restarted the job.... In the old UI there is a drop down menu to see the previous failed attempts, but I'm not sure how to do it in the new UI.

But there is nothing interesting except the lines I already included above.

**Comment by andyli** [comment]
Here is another example of that: https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=20&view=results
