### ISSUE TITLE
problem with js.lib.Promise<Void>

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8461]
I get the error:
`src/Video.hx:97: lines 97-98 : Arguments of type Void are not allowed`
with current version and code like:
```haxe
var prom = video.play();
if (prom != null) prom.then((_) -> ...
```
`js.html.VideoElement.play()` returns a `Promise<Void>`, it used to compiled like this.

When I remove the arg, like `prom.then(() -> ...`, I get:
`src/Video.hx:97: lines 97-98 : Void -> Void should be Null<js.lib.PromiseHandler<Void, Unknown<0>>>`

When I return something, like `prom.then(() -> null)`, I get:
`src/Video.hx:97: characters 33-43 : Void -> Unknown<1> should be Null<js.lib.PromiseHandler<Void, Unknown
<0>>>`

How to deal with that?

**Comment by nadako** [comment]
Pretty sure this comes from 1d924317a813005afd0e0083741ff2b641223c8c.

We have to think about what to do with this in general (we need some notion of Unit type for this), but I would propose disabling that check for 4.0 not to break much code.

cc @Simn, @RealyUniqueName, @ncannasse

**Comment by mockey** [comment]
I see. I went with `untyped` for now.

**Comment by RealyUniqueName** [comment]
I agree, we need to disable it for 4.0

**Comment by RealyUniqueName** [comment]
This doesn't fail anymore
