### ISSUE TITLE
[display] Wold be nice to cache native libraries classes (java, c#)

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#8468]
Hello :)
Currently, classpaths autocompletion is a bit painful thing when you work with native libraries. 
For example, you are writing code like this:
```haxe
function something(variable:CharSequence) ...
```
And in that point, we getting an error that `CharSequence` is `Unresolved identifier`.
But when we click to autocomplete it, then it fails, because it cannot find `java.lang.CharSequence` automatically so you need to import it manually by hands.

But it is not easy to remember all the classpaths of all native types.
So would be nice if Haxe's autocompletion server may cache all native libraries classes, which is added to the project.

Thank you!

**Comment by Simn** [comment]
#7417

**Comment by posxposy** [comment]
Oh, I think it is a different issue. 

This autocompletion is working for me fine:
![image](https://user-images.githubusercontent.com/4466595/60032489-5621a700-96af-11e9-99b8-0344c6c1950c.png)

This is not:
![image](https://user-images.githubusercontent.com/4466595/60032534-72254880-96af-11e9-9da6-0cbc5e9f4cc8.png)
So it is not possible to automatically fill `import java.lang.CharSequence` from native lib.
