### ISSUE TITLE
EnumValue same as class name throws an error

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8470]
If i use the same EnumValue Name as the class the i can not use the class anymore.

```haxe
private enum Hello {
  Test; // if i remove it all works fine
}

class Test {
  public function new() {}

  public function test() {
    Type.createEmptyInstance(Test); // throw _Test.Hello should be Class<Unknown<0>>
  }
}
```

**Comment by Simn** [comment]
Yes but that's just how resolution works.

**Comment by lublak** [comment]
@Simn "Test" as EnumValue is not a class also i never say i need the EnumValue.
I know if you use the type as argument like:

```haxe
function aFunction(hello:Hello) {}
```
you can just write `aFunction(Test);`
but for other stuff it makes no sense. Also what is if i have two enums?
It works fine:

```haxe
private enum Hello {
  Test;
}

private enum Hello2 {
  Test;
}


class Test {
  public function new() {}

  public function aFunction(hello:Hello) {}
  public function aFunction2(hello2:Hello2) {}

  public function test() {
    aFunction(Test);
    aFunction2(Test);
  }
}
```

Is there any workaround this like a simple dot? `.Test`.

**Comment by nadako** [comment]
A workaround for type paths is use fully-qualified paths (use `std.` prefix if your type is top-level).

Tho I'm curious why enum constructors have priority over types in identifier resolution.

**Comment by lublak** [comment]
@nadako thanks for the tip with std.
I was thinking std is only for the haxe "std" library.

**Comment by nadako** [comment]
Yeah the name is a bit misleading, but it's actually used to refer any top-level class. I wonder if it's documented anywhere :)

**Comment by Aurel300** [comment]
@nadako Not yet (:

**Comment by lublak** [comment]
@nadako but something else:
`std.Module.AnyClass` is impossbile. => `Class<Module> has no field AnyClass`
So also here is a problem. If you use `AnyClass` as enum name.
Is there also some trick for it? (i automatically create exprs via macro)

**Comment by nadako** [comment]
> `std.Module.AnyClass` is impossbile. => `Class<Module> has no field AnyClass`

That sounds like an actual bug :)

**Comment by lublak** [comment]
@nadako hmmm you also can name a class field "AnyClass".
When do we use a field and when we use a class?
So there is the same problem for: use function name before class name?
use enum value name before class name?

**Comment by Aurel300** [comment]
@lublak Does the diagram here answer some of your questions?

https://haxe.org/manual/type-system-resolution-order.html

**Comment by lublak** [comment]
@Aurel300 hmmm it would a better option if you can force the compiler to use a class type.

with std. you can force a top level type.
But if you have a type in a module (not the same name) it is impossible to access it. If you have a enumvalue with the same name or or field with the same name. or a static with the same name.

(Currently i dynamicly create a typedef with macros if i come to this point. To never get into this problem. But i think if you use a Ident at a ComplexType it should resolve it by this ComplexType first `Class<T>`)

But on ther other hand you should not use uppercase names for fields. (so this should never collide)
