### ISSUE TITLE
`macro` keyword detected while inside a comment

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/haxe#8473]
There is an issue using Haxe version: 3.4.4 (from try.haxe.org for example). 

Actual: The compiler detects the word `macro`  inside a comment as being a macro related syntax. 

Expected: I expected such syntax to be detected only outside comments. Please correct me if this expectation is wrong for Haxe context.

You can try it yourself: https://try.haxe.org/#a38bf

```haxe
class Test {
    static function main() {
        // TODO: use macro
        trace("Haxe is great!");
    }
}
```

The compiler output is  

``` Build failure
Unauthorized macro : macro
```

**Comment by nadako** [comment]
This is a `try.haxe` specific issue. Haxe itself doesn't care about your comment contents :D

**Comment by ovidiugabriel** [comment]
Ok, I understand. Is the source of try.haxe.org available on github?

**Comment by nadako** [comment]
Yep, see https://github.com/clemos/try-haxe/issues/55
