### ISSUE TITLE
Warnings do not take into account #if (haxe_ver <= 4.0 ), Low Priority Issue.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#8475]
When I have errors irrelvant depreciated warnings clutter the output.

``` haxe
#if js
#if (haxe_ver <= 4.0 )
import js.html.Float32Array;
#else
import js.lib.Float32Array;
#end
#end
```
```
Warning : This typedef is deprecated in favor of js.lib.Float32Array
```
This is not relevant error and should not be reported ( ideally ), I know this is not high priority but raised since I am sure it could be very fustrating when debugging large codebases.

**Comment by Simn** [comment]
`<= 4.0` applies to every Haxe version currently available.

**Comment by nanjizal** [comment]
Opps sorry :( my mistake.
