### ISSUE TITLE
haxe.Serializer and haxe.Unserializer

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8480]
Hej !

I often use haxe.Serializer and Unserializer with remoting and I sometimes get "Class not found " (without the class name) and it occurs when on server side there are mistakes but why does it send "hxrxcy0:g" please ?
Could it be some other informations or at least not the "Class not found" without any classname because it's confusing ?

**Comment by Aurel300** [comment]
It's hard to say what's happening without a reproducible example. Based on the [serialisation format](https://haxe.org/manual/std-serialization-format.html), your string (fragment?) seems to have some exceptions in it - the `x` characters. Could it be that your serialisation code is throwing errors? As for the class not found, it really cannot tell you anything else – the `cy0:` part literally means a class with the name `""`.

**Comment by filt3rek** [comment]
Thanks for your answer !
It's not a fragment it's the whole string. And yes I saw it means exception, class, "". But I get this always from server side when an error occurs (not linked at all with any class...)

**Comment by filt3rek** [comment]
Here the problem was an exception trying to get a property on null on server side...

**Comment by Simn** [comment]
This must be something wrong in your serialization code. As @Aurel300 says, there's nothing the deserializer can do with the information available to it.

I'm gonna have to close this unless you manage to provide some code which suggests this to be a Haxe problem.

**Comment by filt3rek** [comment]
Hej Simn,

I've found the error, it comes form hx3compat, remoting, HttpConnection.hx : https://github.com/HaxeFoundation/hx3compat/issues/12
