### ISSUE TITLE
[Flash] Some functions create errors when used

### ISSUE THREAD

**Issue by KenshiK** [HaxeFoundation/haxe#8481]
Hello everyone, 
I come to you to signal that when using Haxe and translating it to a swc file, some functions return an error.
For instance when I try to use Data.now() I receive the error
`[Fault] exception, information=TypeError: Error #1006: now is not a function.`

I have the same problem with functions filter and map in arrays.

Any idea how to deal with this ?

**Comment by Simn** [comment]
Please provide some code which reproduces the problem.

**Comment by nadako** [comment]
This is probably a case of `haxe.initSwc` not being called at the very beginning, because Haxe Flash target uses some prototype patching that is done when you call that method.

Please confirm if adding `haxe.initSwc(yourMainMovieClip)` helps.

**Comment by KenshiK** [comment]
It happens every time I call the function in the final swc file wherever I put the call to the function.

`public static function main(): Void
    {
        var t = Date.now();
    }`

EDIT : I will try `haxe.initSwc(yourMainMovieClip)` but as I am working in a really complex environment I might not be able to access it

EDIT 2 : So... I do not have a main movie clip. We are using DisplayObjects as our containers and the first MovieClip instance I can find is way further down the line.

**Comment by ncannasse** [comment]
You can try using a new MC, it will only affect flash.Lib.current value in Haxe code.
