### ISSUE TITLE
[java] indexOf not found for Dynamic

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#8484]
```haxe
class Main {
	static function main():Void {
		Assets.loadEverything(function (asset:Dynamic) {
			if (asset.name.indexOf("music_") != -1) return false;
			return true;
		});
	}
}

class Assets {
	public static function loadEverything(fn:Dynamic->Bool) {
		trace(fn({name: "music_foo"}));
		trace(fn({name: "foo"}));
	}
}
```
`Exception in thread "main" Haxe Exception: No compatible method found for: indexOf`

**Comment by Ilir-Liburn** [comment]
You have to cast asset.name

```haxe
if ((asset.name:String).indexOf("music_") != -1) return false;
```

because {name: ""} turns fields into Dynamic. You can fix that like this (without using cast)

```haxe
typedef AssetData = {name:String};

		Assets.loadEverything(function (asset:AssetData) {
```

**Comment by RblSb** [comment]
Thanks, i know it. My issue about that current code probably should works. If this is not specified i'm fine.

**Comment by Gama11** [comment]
Seems similar to https://github.com/HaxeFoundation/haxe/issues/3330#issuecomment-69922247.

**Comment by RealyUniqueName** [comment]
Yeah, let's not add more hacks to support Dynamic. Instead you are encouraged to properly type your code.

And because of the comment referenced by Gama11 I'm closing this.
