### ISSUE TITLE
[cpp] `this++` in inlined abstract method doesn't increment on CI

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8485]
I had to disable the test for #4649 (https://github.com/HaxeFoundation/haxe/commit/c16d2a69c3d1f79c5d98a39702413b5d05c963a6)
```haxe
package unit.issues;

class Issue4649 extends unit.Test {
	static var v:Val<Float> = 10.5;
	function test() {
		v.incr();
		eq(11.5, v); // v is still 10.5
	}
}

abstract Val<T:Float>(T) from T to T {
	public inline function incr():Void
		this++;
}
```
https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=109&view=logs&s=f9470183-172f-5c6e-886f-44d8edfa16d2&j=10654482-0d50-5bac-d18d-e5edded7ece7
Locally generated code looks like this:
```cpp
HXLINE(   7)		::unit::issues::Issue4649_obj::v++;
HXLINE(   8)		this->eq(((Float)11.5),::unit::issues::Issue4649_obj::v,hx::SourceInfo(HX_("src/unit/issues/Issue4649.hx",73,ca,d9,62),8,HX_("unit.issues.Issue4649",f6,e1,e1,90),HX_("test",52,c8,f9,4c)));
```
I have no idea why does it not work on CI.

**Comment by Simn** [comment]
Setting this to 4.0 as it seems bad.

**Comment by Simn** [comment]
@Aurel300 noticed that this is actually cppia failing, not cpp.

**Comment by RealyUniqueName** [comment]
Maybe merge this PR and create an issue for cppia?

**Comment by Aurel300** [comment]
Fixed in https://github.com/HaxeFoundation/hxcpp/commit/577d88f5bf8ce8872359a584de3f4293ef491503 by Hugh.
