### ISSUE TITLE
Argument skipping hides type error

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8488]
```haxe
class Main {
  public static function main():Void {
    function foo(?a:haxe.ds.Option<Int>->Bool, b:Int):Void {}
    foo(
      o -> o.match(haxe.ds.Option.Some(_ => "3")),
      1
    );
  }
}
```

Fails with:

```
Main.hx:5: characters 40-41 : Unknown identifier : _
Main.hx:5: characters 40-41 : For function argument 'v'
Main.hx:5: characters 7-50 : (o : { match : Unknown<0> }) -> Unknown<1> should be Int
Main.hx:5: characters 7-50 : For function argument 'b'
```

The actual error is the `_ => "3"`, trying to match `Int` against `String`. That fails so it tries to unify the function with the second argument, which is where the errors come from, I believe.

If I make the first argument mandatory, the (correct) error is:

```
Main.hx:5: characters 45-48 : String should be Int
Main.hx:5: characters 45-48 : For function argument 'a'
```

**Comment by RealyUniqueName** [comment]
This is also related to #8476 because `Unknow identifier : _` error is issued during testing the arrow function against the second argument and since it fails all errors emitted by that test should be discarded.
