### ISSUE TITLE
`Recursive inline is not supported` is too restrictive

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8489]
The following gives `Recursive inline is not supported`, but I don't understand why. We're not calling it immediately, so it's not a case of recursive inlining, and the function is not `extern inline`, so it can be generated, so we can have a reference to it. Am I missing something?

```haxe
class Main {
	inline static function fun() {
		call(fun);
	}

	static function call(f:()->Void) f();

	static function main() {
	}
}
```

**Comment by Ilir-Liburn** [comment]
```haxe
	inline static function fun():Void {
		untyped __java__('haxe.root.Main.call(((haxe.lang.Function) (new haxe.lang.Closure(haxe.root.Main.class, "fun")) ))');
	}

	static function call(f:()->Void):Void f();

    public static function main() {
        fun();
    }

Main.hx:66: haxe.lang.Closure@14b68da
Exception in thread "main" Haxe Exception: java.lang.StackOverflowError
Caused by: java.lang.StackOverflowError
```

**Comment by nadako** [comment]
@Ilir-Liburn what's your point? of course there are ways to go untyped, but I think my example should work.

**Comment by Ilir-Liburn** [comment]
At first sight, it is visible you are creating recursion there. What do you think what should happen there?

**Comment by nadako** [comment]
I think it should compile, because `call` could as well be some delayed call mechanism (e.g. event listener registration or something).

**Comment by Ilir-Liburn** [comment]
And what is a purpose of fun function? It looks like a caller to listener with callback.

**Comment by Simn** [comment]
Yeah there's something wrong in the compiler. `acc_get` changes behavior based on the expression of the function in its `AKInline` case, but I don't think it should. The two significant cases here should be between the class field being a `Method` or a `Var`, because in the former case we don't have to care about the expression at all (we can just `TField` it because what else would we do).
