### ISSUE TITLE
[Haxe4-rc.3] Trojan:Win32/Fuery.C!cl

### ISSUE THREAD

**Issue by SlavaRa** [HaxeFoundation/haxe#8492]
Windows defender message:
Trojan:Win32/Fuery.C!cl
Alert level: Severe
Status: Removed
Date: 6/28/2019 12:41 PM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
Affected items: file: C:\Users\User\Downloads\haxe-4.0.0-rc.3-win64.exe

**Comment by ncannasse** [comment]
This is most likely a false positive.

**Comment by Simn** [comment]
Will be handled as part of #7720.
