### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8496]
```haxe
typedef MyType = {value:Dynamic, type:ValueType, toString:Void->String};

        var m1:MyType = {value:null, type:TNull, toString:null};
        m1 = {value:"test", type:ValueType.TObject, toString:function() return "test"};
```

Is there a possibility to keep destructuring after reassignment? Above code will turn everything into dynamic object although m1 is not referenced.

**Comment by RealyUniqueName** [comment]
I don't understand your question.
Everything is typed as expected: http://try-haxe.mrcdk.com/#42e78 (see "Compiler output" tab)

**Comment by Simn** [comment]
It's about inlining both structure declarations. I'm not sure how artificial this is but I also don't immediately see why this wouldn't work.

@basro Do you think that would be possible?

**Comment by Ilir-Liburn** [comment]
Here is a workaround which copies one structure to another (unnecessary slowing down)

```haxe
        var m1:MyType = {value:null, type:TNull, toString:null};
        {value:"test", type:ValueType.TObject, toString:function() return "test"};
        m1.value = untyped inlobj_value; // cs forbids assignment without __cs__
        m1.type = untyped inlobj_type; // cs forbids assignment without __cs__
        m1.toString = untyped inlobj_toString; // cs forbids assignment without __cs__
```

**Comment by Simn** [comment]
Dude pls, my eyes...

**Comment by Ilir-Liburn** [comment]
Yeah, that is how eyes of the newcomer to Haxe might look a like after looking at the generated code. Which is only showing there is a potential for optimization, Even copy would be sufficient if there is no direct assignment. Furthermore, there is a hint to compiler in a structure to directly use toString() for the trace, yet even trace will force dynamic structuring.

**Comment by basro** [comment]
@Simn I think it conflicts with supporting multiple aliasing variables for the same inlined object. 
````haxe
var m1:MyType = {value:null, type:TNull, toString:null};
var m2:MyType = m1; // This is currently supported (and is important since allows constructor inlining to go through transformations done by abstract's functions)
m1 = {value:"test", type:ValueType.TObject, toString:function() return "test"}; // it would be incorrect to allow inlining this after m2 was created as an alias if m2 is ever used again.
````

@Ilir-Liburn why not use a new variable instead of the untyped magic?

```haxe
var m1:MyType = {value:null, type:TNull, toString:null};
var m2:MyType = {value:"test", type:ValueType.TObject, toString:function() return "test"};
m1.value = m2.value;
m1.type = m2.value;
m1.toString = m2.toString;
```

**Comment by Ilir-Liburn** [comment]
@basro, at first, I'm trying to look at things from a view of the Haxe newbie, For example, your example m2 = m1, will create only m2 inline (m1 will not be generated), but right after you reassign m1, everything turns into dynamic . While it is clear that m2 should be inline m1, and m1 should be inline reassignment in this case. It is confusing even for more experienced users.

Why not a new variable? Because of this

```haxe
abstract Abstract({ value : Dynamic, type : Type.ValueType }) {
    inline function new(v) this = { value:v, type: Type.typeof(v) };
    @:from public static inline function from(v) {
        return new Abstract(v);
    }
    @:to public inline function to() return this;
}

var a1:Abstract = 0;
a1 = 1; // my inline abstract turns into dynamic structure

// or another example

var a1:Abstract = 0;
var a2:Abstract = 0;
a2 = a1; // everything turns into dynamic structure
 
```

**Comment by Ilir-Liburn** [comment]
From my perspective, structure should be dynamic only if it is referenced (sent to another scope or stored in some array, etc.). And even then, inline structure could turn into dynamic only in place of reference (call to other function, trace, or push to array, etc.)

**Comment by Ilir-Liburn** [comment]
So, in a nutshell, confusion comes from this

```haxe
var m1:MyType = {value:null, type:TNull, toString:null};
var m2:MyType = m1;
```
which generates (Java)

```java
		java.lang.Object m2_value = null;
		haxe.root.ValueType m2_type = haxe.root.ValueType.TNull;
		haxe.lang.Function m2_toString = null;
```

m1 is not generated, and m2 contains copy of m1. In other words, newbie might think, inline structure operate as copy-by-value.

But as soon code is changed via reassignment of m1

```haxe
var m1:MyType = {value:null, type:TNull, toString:null};
var m2:MyType = m1;
m1 = {value:"test", type:ValueType.TObject, toString:function() return "test"};
```

we get

```java
java.lang.Object m1 = new haxe.lang.DynamicObject(new java.lang.String[]{"toString", "type", "value"}, new java.lang.Object[]{null, haxe.root.ValueType.TNull, null}, new java.lang.String[]{}, new double[]{});
java.lang.Object m2 = m1;
{
	haxe.root.Main_main_121__Fun __temp_odecl1 = ( (( haxe.root.Main_main_121__Fun.__hx_current != null )) ? (haxe.root.Main_main_121__Fun.__hx_current) : (haxe.root.Main_main_121__Fun.__hx_current = ((haxe.root.Main_main_121__Fun) (new haxe.root.Main_main_121__Fun()) )) );
        m1 = new haxe.lang.DynamicObject(new java.lang.String[]{"toString", "type", "value"}, new java.lang.Object[]{__temp_odecl1, haxe.root.ValueType.TObject, ((java.lang.Object) ("test") )}, new java.lang.String[]{}, new double[]{});
}
```

reference to m1. The only way I know to reassign structure (copy-by-value) in previous Abstract example would be to use @:op(A = B). Which doesn't exists.
