### ISSUE TITLE
[cs] issues with Dynamic type parameters on interfaces

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8497]
```haxe
interface I<T> {
	function f():I<T>;
}

class C implements I<Any> {
	public function f():I<Any> return null;
}

class C2 implements I<Dynamic> {
	public function f():I<Dynamic> return null;
}
```

---

`C` gives this native compilation error:
```
error CS0539: 'global::I<...>.f' in explicit interface declaration is not a member of interface
```
because it generates
```cs 
global::I global::I<object>.f() {
```
while `I<object>.f` is required to return `I<object>`, not `I`

---

and `C2` gives this:

```
error CS0738: 'C2' does not implement interface member 'I<object>.f()'. 'C2.f()' cannot implement 'I<object>.f()' because it does not have the matching return type of 'I<object>'
```

which is a similar error (using `I` instead of `I<object>`), just the `f` is not using explicit interface implementation, so the error message is different.

---

What I don't quite understand yet is why generated code for `Dynamic` is different from `Any`, but I guess it's related to Dynamic variance?

I'm not hopeful, but maybe @waneck has some time to look into this? :)

**Comment by nadako** [comment]
(this is NOT a regression - same result on 3.4.7)

**Comment by kLabz** [comment]
Note: works fine if `I` is `@:nativeGen`
