### ISSUE TITLE
Unbound variable for empty switch on a field

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8506]
```haxe
class Main {
	static var s = "hi";
	static function main() {
		switch s {}
	}
}
```
this gives a position-less warning:
```
{
        v_id = 393;
        v_name = `;
        v_type = String;
        v_capture = false;
        v_extra = None;
        v_meta = [];
}
```

further behaviour depends on the generator, e.g. Flash complains about ``Unbound variable ` `` (now with position), JS generates some invalid code: ``switch(`) {}``

**Comment by Aurel300** [comment]
`switch` without any cases should probably fail to compile?

**Comment by nadako** [comment]
> `switch` without any cases should probably fail to compile?

Maybe. I found this bug only because I commented out the whole switch body :D

**Comment by nadako** [comment]
Hmm, this is actually a regression, Haxe 3 (on try.haxe) gives `Test.hx:4: characters 2-13 : Unmatched patterns: _`.

**Comment by Simn** [comment]
That's... odd.
