### ISSUE TITLE
Supply constant parameter as "null" doesn't get conditionally block optimized

### ISSUE THREAD

**Issue by Glidias** [HaxeFoundation/haxe#8514]
The expression in Haxe:
```
var abc = new AbsStringMap<Int>({hello:1});
```

The abstract class constructor method
```
abstract AbsStringMap<T>(
#if js
Dynamic<T>
#else
StringMap<T>
#end
)
{

	inline public function new(
		#if js
		data:Dynamic<T> = null
		#else
		data:StringMap<T> = null
		#end
	) 
	{
		if (data != null) { // potential exclusive block
			this = data;
		} else {  // potential  exclusive block
			#if js
			this = {};
			#else
			this = new StringMap<T>();
			#end
		}
	}
```
By supplying an absolute Null expression to the parameter of the function, shouldn't the conditional block that fails to meet the constant null equality check be elimintaed out ? BUt the below output results though.. (JS):.

```
var data = { hello : 1};
	var this1;
	if(data != null) {
		this1 = data;
	} else {
		this1 = { };
	}
```

 THe conditional expression is still exported out instead of eliminated. (It works if i use something else like Boolean constant expression for the parameter (eg. `true/false`).  But according, to the documentation in https://haxe.org/manual/expression-constants.html , `null` is also considered an expression.

**Comment by RealyUniqueName** [comment]
Here is a reduced sample:
```haxe
class Test {  
  static function main() {
    testString('hello');
    testObject(null);
    testObject({hello:1});
  }
  
  inline static function testString(data:String) {
		if (data != null) {
			trace(data);
		} else { 
			trace('hello');
		}
	}
  
  inline static function testObject(data:{hello:Int}) {
		if (data != null) {
			trace(data);
		} else { 
			trace({});
		}
	}
}
```
generated js:
```js
	console.log("root/program/Test.hx:10:","hello");
	console.log("root/program/Test.hx:20:",{ });
	var data = { hello : 1};
	if(data != null) {
		console.log("root/program/Test.hx:18:",data);
	} else {
		console.log("root/program/Test.hx:20:",{ });
	}
```
http://try-haxe.mrcdk.com/#d2e1c
As you can see string and `null` are properly propagated removing `if` expressions.
I think `{hello:1}` is not considered a constant expression and ignored by that optimization.

**Comment by Glidias** [comment]
oh yes, constant expr required and object doesn't count, even though it might be easy to derive that a direct object value expression cannot be an Int/Boolean null, etc. (intuitively for a human), that requires far more advanced thinking no doubt for a compiler. To begin with, it could consider a direct curly brace {}  Expr(object) (not a variable expr) as a constant expression? But yea, that isn't a constant in a strict data sense because the "value" of it is runtime dependant.
