### ISSUE TITLE
Int can be re-assigned when returned from extern inline function

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8517]
```haxe
extern class Foobar {
	static var a:Int;
	static inline function foo():Int return a;
}
class Test {
	public static function main():Void {
		Foobar.foo() = 2;
	}
}
```

This should fail to compile with `Test.hx:7: characters 3-15 : Invalid assign`, but it does not. This could cause a runtime exception instead, e.g. on Python:

```haxe
var a = Date.now();
a.getFullYear() = 3;
```

(Throws `AttributeError: attribute 'year' of 'datetime.date' objects is not writable`.)

**Comment by nadako** [comment]
Ouch. That's actually pretty bad, because my converter can currently generate code like `a.getFullYear() = 3` in some cases, and my plan is/was to catch these cases by looking at Haxe compile errors :)
