### ISSUE TITLE
[java] can not cast haxe.lang.Dynamic Object to StringMap?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8521]
var map:Map<String,Dynamic> = [];

     map["key"] = 1234;

     map["b"] = "hello world";

j

**Comment by sonygod** [comment]
var map:Map<String,Dynamic> = [];
		
		map["b"] = "hello world";

		map["a"] = 1;

		var result :Map<String,Dynamic>= Json.parse(Json.stringify(map));

java target throw error!

**Comment by Aurel300** [comment]
If you want an "object" in JSON, you should use an anonymous structure.

```haxe
var myObject = {
  b: "hello world",
  a: 1
};
var result = Json.parse(Json.stringify(myObject));
```

If you need a map-like interface (e.g. to set keys based on other variables), use `haxe.DynamicAccess`:

```haxe
var myObject:haxe.DynamicAccess<Dynamic> = {};
myObject["b"] = "hello world";
myObject["a"] = 1;
var result = Json.parse(Json.stringify(myObject));
```

**Comment by nadako** [comment]
Or you can use one of the more "featureful" JSON libraries like json2object or tink_json that support Map, because `haxe.Json` doesn't.
