### ISSUE TITLE
Tests in `tests/unit/compiler_loops` are never executed on CI

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8522]
@andyli  Is it possible to run them, but interrupt the process if it hangs for some time?

**Comment by andyli** [comment]
I guess so. Just set use `sys.io.Process` and then a `Timer` in `RunCi`.

BTW, there is an existing issue for this #6200.

**Comment by RealyUniqueName** [comment]
Thanks
