### ISSUE TITLE
jvm: implementing interface method by covariant return type causes AbstractMethodError

### ISSUE THREAD

**Issue by saharan** [HaxeFoundation/haxe#8528]
The following code causes `java.lang.AbstractMethodError` when compiling for Java target with `-D jvm` option:
```hx
class Main {
	static function main() {
		var a:A = new A();
		a.foo(); // ok

		var i:I = a;
		i.foo(); // AbstractMethodError
	}
}

interface I {
	public function foo():I;
}

class A implements I {
	public function new() {
	}

	public function foo():A { // implementation using covariant return type
		return this;
	}
}
```

```
Exception in thread "main" java.lang.AbstractMethodError: Method A.foo()LI; is abstract
        at A.foo(src/Main.hx)
        at Main.main(src/Main.hx)
        at Main.main(src/Main.hx)
```

Note that this code has no problem without `-D jvm` option, or when using other targets (tried C++, Python, C#, JavaScript) as far as I know.

**Comment by Simn** [comment]
`javac` generates a helper function for this on A.class:

```
 public haxe.root.I foo();
    Code:
       0: aload_0
       1: invokevirtual #9                  // Method foo:()Lhaxe/root/A;
       4: areturn
```

We'll have to comply with that.

**Comment by Simn** [comment]
We now generate bridge methods whenever we implement an interface method with a different, variant-unifying type. There might still be cases where this breaks apart in the context of overloads, but I struggle to come up with such a case.
