### ISSUE TITLE
Regression in switch unification

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8529]
This is a regression in switch unification:

```haxe
import js.lib.*;

class Main {
	static function main() {
		var buffer = switch( Std.random(3) ) {
		case 0: new Float32Array(0);
		case 1: new Uint16Array(0);
		default: null;
		}
	}
}
```

This should type buffer as `js.html.ArrayBufferView` (no need to type `buffer` explicitely)

**Comment by nadako** [comment]
> This should type buffer as js.html.ArrayBufferView (no need to type buffer explicitely)

Not sure about that, see https://github.com/HaxeFoundation/haxe/pull/8422#issue-288185969

**Comment by ncannasse** [comment]
Oh, I see, the bug is related to ArrayBufferView being an abstract.
I fail to see the actual benefit of the patch, and since it causes regression I'm in favor of reverting it.

**Comment by haxiomic** [comment]
@ncannasse I agree, I can't see an advantage of switching to abstract here

The PR #8422 included some other changes like adding BufferSource which it would be nice to keep so I've made a new PR to revert just the ArrayBufferView change 

#8566
