### ISSUE TITLE
Inconsistent position of haxe.macro.PositionTools.make

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#8533]
In the GIF, the `hi.txt` is a copy of `src/Main.hx`, but the resulting position is different:

`[7-15]` in `src/Main.hx` 
`[7- 1]` in `hi.txt`
![issue_pos_gif](https://user-images.githubusercontent.com/6825113/60988689-b0408e80-a376-11e9-8ab9-5c454fc139a3.gif)

[reproduce.zip](https://github.com/HaxeFoundation/haxe/files/3378589/inconsis_make_pos.zip)

**Comment by Aurel300** [comment]
Is the encoding of the two files the same?

**Comment by R32** [comment]
Both are UTF8
