### ISSUE TITLE
[jvm]: haxe classes conflict with java classes.

### ISSUE THREAD

**Issue by ghost** [HaxeFoundation/haxe#8544]
Before compiling with `-D jvm` I could have `haxe.root.Array` class in my code but now using Array which is in root directory of compiled jvm code It can not be accessed anymore.

**Comment by RealyUniqueName** [comment]
Can you provide a sample?
I didn't spot any issues with custom `Array` class.

**Comment by Simn** [comment]
It might be a good idea to follow genjava here and put everything in a haxe.root package.

Unfortunately, that's a somewhat finicky change and I'm not sure how many places it affects.

**Comment by ghost** [comment]
We used `import haxe.root.Array` to access haxe Array in java now because Array does not have namespace it can't be used to access haxe generated code in java.

Haxe Code:
```haxe
public var attendees:Array<Attendee>;
```

Java Code:
```java
challenge.attendees = new Array<Attendee>();
```

If we build it without -jvm flag there is no problem but with -jvm flag Java compiler complains about `haxe.root.Array` not found.
