### ISSUE TITLE
abstract new vs from

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8554]
```haxe
abstract Under(Dynamic) {

    public inline function new(v) this = v;

    @:from public static inline function fromInt(v:Int) { trace("Int"); return new Under(v); }
}

    var r1 = new Under(null); // On static platforms, null can't be used as basic type Int
    var r2 = new Under(null); // On static platforms, null can't be used as basic type Int
```

After I change fromInt(v:Int) to fromInt(?v:Int), above example compiles, but CS is producing code which I don't see on other static platforms

```C#
			object this1 = (default(global::haxe.lang.Null<int>)).toDynamic();
			object r1 = ((object) (this1) );
			object this2 = (default(global::haxe.lang.Null<int>)).toDynamic();
			object r2 = ((object) (this2) );
``` 
vs Java
```java
		java.lang.Object this1 = null;
		java.lang.Object r1 = ((java.lang.Object) (this1) );
		java.lang.Object this2 = null;
		java.lang.Object r2 = ((java.lang.Object) (this2) );

``` 
vs CPP
```cpp
HXLINE( 240)		 ::Dynamic this1 = null();
HXDLIN( 240)		 ::Dynamic r1 = this1;
HXLINE( 241)		 ::Dynamic this2 = null();
HXDLIN( 241)		 ::Dynamic r2 = this2;
 
``` 

If I comment fromInt, all platforms produce same result. Question remains: how is and why fromInt related (but never called) to a new in this case?

**Comment by RealyUniqueName** [comment]
That happens because `v` in the constructor has a [monomorph](https://haxe.org/manual/types-monomorph.html) type. Which means it is "morphed" into the first type it is unified to. And when you add your `fromInt` that type happens to be either `Int` or `Null<Int>` (depending on an absence or presence of `?`).
Change your constructor to `new(v:Dynamic)` and the generated code will always be the same.

**Comment by Ilir-Liburn** [comment]
But isn't that just wrong? Underlying type is Dynamic, so this = v in constructor should mean this = (v:Dynamic)?

From documentation
```
Whenever a type other than Dynamic is unified with a monomorph, that monomorph becomes that type: it morphs into that type.
```

@Simn?

**Comment by Ilir-Liburn** [comment]
I changed constructor into

```haxe
   public function new() { var t = null; $type(t); this = t; }

var r1 = new Under();

Main.hx:85: characters 49-50 : Warning : Unknown<0>
```

and it compiles just fine while fromInt is declared. @Simn?

**Comment by RealyUniqueName** [comment]
> From documentation
> 
> ```
> Whenever a type other than Dynamic is unified with a monomorph, that monomorph becomes that type: it morphs into that type.
> ```

Unless the type is `Dynamic`. It's not applied to limit `Dynamic` propagation: https://haxe.org/manual/types-dynamic.html
> Dynamic behaves in a special way when being unified with a monomorph. Monomorphs are never bound to Dynamic

**Comment by Ilir-Liburn** [comment]
So, only Dynamic won't unify to monomorph, while any other type will:

```haxe
abstract Str(String) {
    public function new(v) { $type(v); this = v;  $type(v); }
    @:from public static function from(v:Int) return new Str(v);
}
Main.hx:220: characters 36-37 : Warning : Unknown<0>
Main.hx:220: characters 57-58 : Warning : String
Main.hx:221: characters 62-63 : Int should be String
``` 

Basically, what I was getting can be reduced to
```haxe
        var n = null;
        var d:Dynamic = n;
        n = 1;
        $type(n);
        $type(d);

Main.hx:257: characters 15-16 : Warning : Int
Main.hx:258: characters 15-16 : Warning : Dynamic
Main.hx:254: characters 17-21 : On static platforms, null can't be used as basic type Int
Main.hx:254: characters 17-21 : On static platforms, null can't be used as basic type Int
```
