### ISSUE TITLE
[hxcpp] haxe 4.0.0 rc3 doesn't support Chinese animal biscuits

### ISSUE THREAD

**Issue by guangjingxu** [HaxeFoundation/haxe#8559]
Compiling c++ When running Chinese, running on xcode 

![image](https://user-images.githubusercontent.com/51730635/61363062-ea012000-a8b5-11e9-81b2-42a330c017aa.png)

**Comment by RealyUniqueName** [comment]
Please, provide a reproducible sample.

**Comment by rainyt** [comment]
Is there any progress in this? Xcode cannot compile Chinese.

**Comment by RealyUniqueName** [comment]
We need a sample to reproduce. Screenshot cannot be fixed :)

**Comment by rainyt** [comment]
[Demo-haxe4.0.zip](https://github.com/HaxeFoundation/haxe/files/3518146/Demo-haxe4.0.zip)
Hi, I am willing to provide this sample. This is a sample of OpenFL. After running the command "lime build ios", you can see the error in XCode. @RealyUniqueName 

Thank you.

**Comment by rainyt** [comment]
The compiled library version is:
openfl:8.9.1
lime:7.5.0
hxcpp:4.0.19

**Comment by rainyt** [comment]
I wander if my demo can help you? @RealyUniqueName

**Comment by RealyUniqueName** [comment]
Thanks for the demo. I didn't have a chance to check it yet.
Also, I don't have a mac atm. Maybe @Aurel300 could check this issue before I setup a mac box.

**Comment by Aurel300** [comment]
Stripping away the lime stuff, i.e.:

```haxe
class Main {
  public static function main():Void trace("我的dome");
}
```

This compiles fine for me on OS X. The C++ output includes:

```cpp
::haxe::Log_obj::trace(HX_W(u"\u6211\u7684dome",59e5,94e0),/* etc */);
```

Which is what seems to be causing the error in the original post. The error itself complains about an invalid token: `u"\x5742"`. Unicode string literals were added in C++11. I wonder if your Xcode is set up correctly? See [this answer](https://stackoverflow.com/a/7791906).

**Comment by rainyt** [comment]
After testing, this bug has disappeared in hxcpp4.0.56. @Aurel300 @RealyUniqueName

**Comment by RealyUniqueName** [comment]
Alrighty then
