### ISSUE TITLE
Deprecate or remove `haxe.Template`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8562]
I think `haxe.Template` should be deprecated or moved to `hx3compat`.
It's the same story as `haxe.unit` and `haxe.remoting`.
@ncannasse ?

**Comment by ncannasse** [comment]
I don't think it's a big problem keeping it there. I don't see much want we gain at moving it elsewhere except annoying users.

**Comment by ibilon** [comment]
What's different between `haxe.Template` and `haxe.unit` or `haxe.remoting` though?
If there are reasons to keep it then the same apply to the others.

**Comment by ncannasse** [comment]
@ibilon other classes were more like "framework" oriented. Template is just a small helper class.
