### ISSUE TITLE
[cs, java] @:generic @:from failure

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8573]
```haxe
abstract Abstract(Dynamic) {
    public function new(v) { this = v; }

    @:generic
    @:from public static inline function from<T>(v:T) { return new Abstract(v); }
}

        var a:Abstract = { value:null, type:TUnknown };

src\Main.cs(8,29): error CS0246: The type or namespace name 'T' could not be found (are you missing a using directive or an assembly reference?)
```

Other targets working fine (including JVM)

**Comment by Ilir-Liburn** [comment]
Huh, by removing inline, @:from function is not generated (all targets), build fails.

**Comment by Ilir-Liburn** [comment]
OK, I got first issue fixed by changing abstract into

```haxe
abstract Abstract<T>(T) {
    public function new(v:T) { this = v; }

    @:generic
    @:from public static function from<T>(v:T) { return new Abstract(v); }
}
```

Obviously, CS and Java are expecting T declared on abstract. Second issue can't be solved because compiler always inserts a call to from function, never to from_anon_value_Int_type_ValueType function or such. Thus, @:generic should be forbidden in pair with @:from, I think.

**Comment by Simn** [comment]
Huh, I didn't realize `@:generic inline` was even allowed. That seems a bit incompatible.

As for `@:generic @:from`, I don't see why that shouldn't work, so that's something we can probably fix.

**Comment by Ilir-Liburn** [comment]
Isn't inline always about inlining code instead of calling a function? In this case, inlining a code of function which takes dynamic parameters like there is no generic meta?

What I can't foresee is what happens if @:generic @:from is declared first, and then other from(s) are declared

```haxe
@:generic @:from public static function from<T>(v:T) { return cast v; } 
@:from public static function fromFloat(v:Float) { return cast v; } // this one will never be reached?
@:from public static function fromBool(v:Bool) { return cast v; } // this one will never be reached?
```

**Comment by Simn** [comment]
Covered by #4599 and #3033.
