### ISSUE TITLE
[java] Native int is absent

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/haxe#8576]
haxe type &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; java type
java.StdTypes.Int8   -->  byte  
java.StdTypes.Int16 -->  short
java.StdTypes.Int64 -->  long
               ?               -->  int
Where can I find native java primitive int type?

**Comment by Aurel300** [comment]
I would think it's just the basic `Int` type you get in Haxe?

**Comment by djaonourside** [comment]
yep, thanks)
