### ISSUE TITLE
Date.toJSON

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8578]
The common format for a Date in JSON seems to be an ISO 8601 string in UTC wiith milliseconds, i.e.: `2019-07-25T15:36:34.959Z`.
At least that's what you get when you `JSON.stringify` a `Date` in JS or use `Date.toJSON`. Wouldn't a `Date.toJson` method be useful that does the same on other platforms?

**Comment by Aurel300** [comment]
The problem with that is that even though it is nice from a "user looking at the JSON output" perspective, it is a lossy conversion – there is no proper way to express dates in JSON, and if you receive a ISO 8601 string from JSON parsing, you still need to manually change it into a `Date`. So I don't think a `toJSON` method would provide much value compared to manually converting a `Date` to that format.

Additionally, there has already been a suggestion to have a general `toJSON` magic method, similar to `toString`, which was rejected: https://github.com/HaxeFoundation/haxe/issues/6636

**Comment by mockey** [comment]
I know this is not ideal. But it's about having some standard JSON output for Date cross-platform. Right now I get the said ISO string from JS while I get an object `{__t: $timestamp}` from PHP e.g.

**Comment by Aurel300** [comment]
Well, `Date.toString` is consistent, but there is nothing specifying that the JSON module should stringify `Date` using its `toString` method. Ideally you should pre-process the input to `Json.stringify` to only contain JSON primitives, i.e. anonymous objects, arrays, integers, floats, booleans, strings, nulls.

**Comment by mockey** [comment]
`Date.toString` might be consistent but gives you local time without any timezone info.

**Comment by Aurel300** [comment]
That is true. For the time being I would suggest something like `using DateJsonTools;`, then define `DateJsonTools.toJSON` to use the `Date.getUTC*` methods and/or `Date.getTimezoneOffset`.

**Comment by mockey** [comment]
I have something like that, no worries. I just thought it might make sense in Haxe DateTools,
