### ISSUE TITLE
pattern matching allows values of abstract underlying types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8579]
This compiles even though `A` has not `from`/`to` `Int`:

```haxe
abstract A(Int) {
	public static final instance:A = cast 42;
}

class Main {
	static function main() {
		switch 42 {
			case A.instance:
				trace("YES");
			case _:
				trace("NO");
		}
	}
}
```

**Comment by nadako** [comment]
[Not a regression](http://try-haxe.mrcdk.com/#D52b7)

**Comment by RealyUniqueName** [comment]
It's explicitly implemented here:
https://github.com/HaxeFoundation/haxe/blob/bdddb588cbb99e2bb0428a79e6a6aef614715225/src/typing/matcher.ml#L244-L248
I didn't find any clue to why it is done. Disabling it doesn't break any tests.
@Simn ?

**Comment by Simn** [comment]
IIRC it was some OpenFL problem. But we can try breaking it.

**Comment by RealyUniqueName** [comment]
Removing that hack breaks this: https://github.com/openfl/openfl/blob/develop/src/openfl/display/ShaderParameterType.hx#L208-L234
But IMO that should be fixed on the OpenFL site

**Comment by nadako** [comment]
yes, it breaks a lot of these enum abstracts in OpenFL, but arguably that code is incorrect and should be fixed

**Comment by RealyUniqueName** [comment]
@jgranick ^
