### ISSUE TITLE
static @:to for non-multiType abstracts

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8580]
This compiles, while it probably should not:

```haxe
abstract A(Int) {
	@:to public static function toString(value:Int):String {
		return "hello";
	}
}

class Main {
	static function main() {
		var a:A = null;
		trace(a.toString()); // wat
	}
}
```

Looks like there are some missing checks for `@:impl` and friends (or they are done at the wrong time).

Maybe static `@:to` methods shouldn't be allowed at all for non-`@:multiType` abstracts?

**Comment by nadako** [comment]
[Not a regression](http://try-haxe.mrcdk.com/#2627A)

**Comment by RealyUniqueName** [comment]
It's explicitly implemented here:
https://github.com/HaxeFoundation/haxe/blob/bdddb588cbb99e2bb0428a79e6a6aef614715225/src/typing/matcher.ml#L244-L248
I didn't find any clue to why it is done. Disabling it doesn't break any tests.
@Simn ?

**Comment by nadako** [comment]
are you sure it's about this issue and not #8579? :)

**Comment by RealyUniqueName** [comment]
Oh, right :)

**Comment by back2dos** [comment]
There's been some kind of "selective methods" or whatever they're termed. IIRC it was even in the manual at some point in time, but I can't find it anymore.

For `@:to` casts, it allows you to specialize on type parameter: http://try-haxe.mrcdk.com/#c0c9D

I guess it would look less weird if the argument were the abstract instead of the underlying type.

**Comment by Simn** [comment]
Checklist for any change regarding `@:multiType`:

1. Does it break `Map`?
2. If not, change it.
3. Make a mental note that one day we'll implement `Map` differently.

**Comment by RealyUniqueName** [comment]
Static `@:to` is actually intended to work with non-multitype abstracts to allow specialization of `@:to` methods based on type parameters: #1419
https://github.com/HaxeFoundation/haxe/blob/c60166a8272726b42fdc9f7858b3337ed8151f6e/tests/unit/src/unit/MyAbstract.hx#L107-L115
