### ISSUE TITLE
[display] shows first, compiles second function from static extension

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8584]
```haxe
class OverloadHelper {
}

class Overload1 extends OverloadHelper {
    public static inline function test(o:Overload) Overload.test(0);
}

class Overload2 extends OverloadHelper {
    public static inline function test(o:Overload, i:Int) Overload.test(i);
}

using OverloadHelper;

        var o = new Overload();
        o.| // only test() shown, test(i:Int) not (but will compile)
```

**Comment by Ilir-Liburn** [comment]
Another issue is that o.test() will not compile. If I swap test functions, it will. Meaning, only last extension will compile, but display will show only first.

Adding missing Overload class, although I think it's clear how it looks like

```haxe
class Overload {
    public function new() {}
    public static function test(i:Int) {
        trace("test");
    }
}
 ```

**Comment by Ilir-Liburn** [comment]
BTW, if using static extension in this way can compile only last extension, how do I compile them both? If I try 'using OverloadHelper.*", compiler complains that I have to specific

```haxe
using OverloadHelper.Overload1;
using OverloadHelper.Overload2;
```

while 'import OverloadHelper.*" allows wildcard. And even I'm specific like above, display shows only first extension, but compiles second. Obviously, second is shadowing first.

**Comment by Gama11** [comment]
>how do I compile them both?

I don't think that's possible, overloads are only supported for externs after all.

**Comment by Simn** [comment]
This is not how static extensions work. The display is correct.

**Comment by Ilir-Liburn** [comment]
If display is correct, then compiler is wrong. Display will show test() function, while compiler will throw error (compiles only second test(i:Int) function)

**Comment by Simn** [comment]
Oh that's what you're reporting. Your comments confused me.

**Comment by Ilir-Liburn** [comment]
Same happens with auto-using, e.g. @:using(Overload.Overload1, Overload.Overload2)
