### ISSUE TITLE
Latest dev build, haxelib doesn't work on Windows x64

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8585]
Won't start, something about not valid executable. Latest I found working is

haxe_2019-07-26_development_c65439d.zip

**Comment by Aurel300** [comment]
https://github.com/HaxeFoundation/haxe/commit/f3a86e39b263a0ec67e8ac20a286b79aa0bbaa4f probably wouldn't cause this.  https://github.com/HaxeFoundation/haxe/commit/12870fe4a7ca87bb2e24e3671e7cd314728f1214 might have. @RealyUniqueName

**Comment by RealyUniqueName** [comment]
Yeah, see the comment on 12870fe4a7ca87bb2e24e3671e7cd314728f1214
