### ISSUE TITLE
Compiler hanging on invalid `@:from`

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8588]
```haxe
typedef Abstract = Under<{}>;

@:multiType abstract Under<T>(T) {

    function new(v:T);

    @:from public static inline function from<T>(v:T) { return /*cast*/ v; } // { return new Under(v); }
//    @:to public inline function to(v:T) { return v; }
}

        var a1:Abstract = { value:(null:Dynamic), type:TUnknown };
```

Casting return of @:from function or using new-@:to combination works without hanging

**Comment by Simn** [comment]
This isn't about multitype abstracts at all and the example can be simplified:

```haxe
abstract Under<T>(T) {
    function new(v:T) {
		this = v;
	}

    @:from public static function from<T>(v:T) {
		return v;
	}
}

class Main {
	static public function main() {
		var a1:Under<{}> = { };
	}
}
```

The code is clearly invalid and errors without the assignment in `main`, but something hangs before we get to that error. The type parameter on `Under` is required to reproduce this.

**Comment by RealyUniqueName** [comment]
Infinite loop happens because `fast_eq` does not hold here:
https://github.com/HaxeFoundation/haxe/blob/004b3b48fcc458651550a020936933530a9464d7/src/typing/typer.ml#L1613
It compares `Under<{}>` and `Under<{}>`, but since `TAnon`s have different origin they are not physically equal and `fast_eq` does not compare `TAnon`s structurally.

Edit: anons are not equal because they are duplicated here: 
https://github.com/HaxeFoundation/haxe/blob/004b3b48fcc458651550a020936933530a9464d7/src/typing/typerBase.ml#L206

**Comment by Ilir-Liburn** [comment]
I stay on multitype abstract here because of another issue

```haxe
typedef Abstract = Under<{}>;

@:multiType abstract Under<T>(T) {
    function new(v:T);
    @:from public static inline function from<T>(v) { return (v:Under<T>); }
    @:to public inline function to(v:T) return v;
}
        var a1:Abstract = {value:(null:Dynamic), type:TUnknown};
```

 Return by ```(v:Under<T>)``` hangs compiler, while regular abstract throws: Recursive implicit cast

EDIT: after adding missing v:T, return (v:Under<T>) compiles just fine. So, I removed T at v:T for regular abstract, and it is hanging too.  So both are hanging actually if v:T is not declared

**Comment by RealyUniqueName** [comment]
Fixed that in #8592 too

**Comment by Ilir-Liburn** [comment]
Probably is the same issue, but just in case...

```haxe
abstract Under<T>(T) {

    public inline function new(v:T) { this = v; };

    @:from public static function from<T>(v:Under<T>) { return v; }
    @:from public static function from<T>(v:T) { return new Under(v); }
    @:to public static function to(v) { return v; }
}
```

From abstract type hangs compiler (second from is irrelevant). Same goes for multitype abstract

**Comment by RealyUniqueName** [comment]
It's the same issue

**Comment by Ilir-Liburn** [comment]
Compiler still hanging on

```haxe
    @:from public static function from<T>(v:Under<T>) { return v; }
```

**Comment by Simn** [comment]
@RealyUniqueName Can you try adding `ignore(follow t)` here: https://github.com/HaxeFoundation/haxe/blob/development/src/typing/typerBase.ml#L202 I think that should detect this case.

**Comment by Ilir-Liburn** [comment]
You can reproduce it by

```haxe
        var a1:Under<Dynamic> = {value:0.0, type:TFloat};
//        var a1:Under<{}> = { }; this one works
```

**Comment by RealyUniqueName** [comment]
@Simn It happens because monomorphs from `get_abstract_froms` are not bound to `Dynamic`.  But returning `true` from `fast_eq_anon` for `TMono None, TMono None` is not correct. Idk what would be a correct solution here. The whole approach of `get_abstract_froms` seems invalid now.
