### ISSUE TITLE
[suggestion] oneliner function syntax

### ISSUE THREAD

**Issue by vypxl** [HaxeFoundation/haxe#8594]
I know there is the shiny new arrow function syntax which I do like, but it can't really be used for class member functions.

Currently, to create a short, one-line function returning something, you end up like this:
```haxe
function foo() [: String] return "bar";
// or, with an arrow function
var foo2 = () -> "baz";
```

In my opinion that `function bar() : Type return ..;` looks weird.
So I propose a little syntactic sugar to enhance this:
```haxe
function foo3() = "yay";
```

Took that from Scala btw

**Comment by Simn** [comment]
Thank you for the suggestion, but we have no plans to add more syntax for functions at the moment.

**Comment by Aurel300** [comment]
```haxe
var foo = () -> "foo";
function foo() = "foo";
```

The first one is shorter also :)

**Comment by kLabz** [comment]
Don't you need `final foo` though?
