### ISSUE TITLE
Move haxe-js-kit under the Haxe Foundation umbrella

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe#8595]
Sorry if this is not the right place to discuss this, but I think this is a relevant topic and directly related to Haxe.

The `haxe-js-kit` (https://github.com/clemos/haxe-js-kit) suite of externs is slowly falling apart, and started failing with Haxe 4. It's a pity because it's got a LOT of useful externs for popular js libraries and frameworks. I'd compare it to TypeScript's https://github.com/DefinitelyTyped/DefinitelyTyped. 

Would it be possible for the Haxe Foundation to take ownership of it, together with `hxnodejs` or even, perhaps, merge both?

**Comment by back2dos** [comment]
I don't think that's realistic to expect, as js-kit is barely used by anyone on the team, if at all.

I also believe that the time and energy required for this would better be spent on a proper dts2hx solution, as that means we can effectively outsource the tedious task of creating and maintaining externs.

**Comment by ncannasse** [comment]
Haxe Foundation could host an official repository for community-contributed JS externs, so that there is a single point where various efforts are gathered instead of being split among each contributor own's repository. 

But we would need a maintainer for this, that takes care of:
- managing the PR and other contributions
- inviting current scattered externs authors to contribute their work there
- promoting the repo to users as a the default option (through changes in haxe.org website, etc.)
- making releases, through haxelib and other if needed

Regarding dts2hx, given the actual complexity of TS, I think that even when done well this would not result in good quality Haxe externs, the best solution being to write them by hand to get the best out of Haxe own type system.

**Comment by nadako** [comment]
BTW there's https://github.com/HaxeFoundation/hxnodelibs basically maintained by two guys, but I think it's only for node.js modules.

**Comment by ncannasse** [comment]
Yes, that would be in the same spirit we did
https://github.com/HaxeFoundation/hxnodejs as well.

**Comment by nadako** [comment]
> Regarding dts2hx, given the actual complexity of TS, I think that even when done well this would not result in good quality Haxe externs, the best solution being to write them by hand to get the best out of Haxe own type system.

I agree with that. Converting d.ts is possible to some extent, but some TS type system concepts are just not compatible with Haxe (e.g. mapped types, type queries, non-trivial unions/intersections).

**Comment by fullofcaffeine** [comment]
Oh nice, I did not know hxnodejs included externs for Express among other frameworks. I'll look into it.

**Comment by fullofcaffeine** [comment]
Apologies, I misunderstood. `hxnodejs` has externs only for the nodejs std lib. The externs for `expressjs` that `js-kit` provides still works with Haxe 4 (albeit with warnings), though. It'd really nice to have readily available externs for popular js libs like Express / Koa, Mongoose, etc.

**Comment by fullofcaffeine** [comment]
> Oh nice, I did not know hxnodejs included externs for Express among other frameworks. I'll look into it.

Woopsie, I meant https://github.com/HaxeFoundation/hxnodelibs not `hxnodejs`. I had no idea `hxnodelibs` existed. Could we list them somewhere in the manual?

**Comment by fullofcaffeine** [comment]
However, the express externs from `js-kit` are actually much more elegantly typed (in terms of typing completeness) than the ones in `hxnodelibs` (which seems to rely on `Dynamic` too much at the moment, just compare the express' `Middleware.use` func from both to have an idea of what I'm talking about). I'll keep using the ones from `js-kit` for now.

**Comment by kLabz** [comment]
> which seems to rely on `Dynamic` too much at the moment

That's the kind of impression I have (or had, at least) for many externs in js-kit. If it's not a false impression then I don't think I'd want those externs to be "officially promoted" or something.

**Comment by fullofcaffeine** [comment]
@kLabz I haven't used any other externs from `js-kit` apart from the ones for `expressjs` and in this case, the externs in js-kit *are* more complete type-wise than the ones in `hxnodelibs`.

**Comment by kLabz** [comment]
Yeah if my impression was (and still is maybe) justified it certainly didn't/doesn't apply to every externs in js-kit. I'm sure there are some (many?) high quality ones in there.

**Comment by fullofcaffeine** [comment]
@ciscoheat used to be an active contributor to `js-kit` and his Haxe code is top-notch from my experience, so I'm sure there are other good gems there. 

**We're getting off track here though**. From what I see, there's no chance of `js-kit` being ever moved / maintained by the HF officially. **I think this issue could still be useful as a trigger [of further discussion] to either of the following routes, which are not mutually exclusive:**

1) Improve the `hxnodelibs`, perhaps rename it to `js-externs` or something and call for volunteers or hire people under the HF umbrella to help;
2) Focus on getting a `d.ts -> hx` externs transpiler to generate good-enough externs. Maybe the quirks could be worked upon so that eventually the generated output would be high-quality, but even if it's not, it could still help save time on #1. See: https://community.haxe.org/t/wip-d-ts-hx-project/1761.

**Comment by Simn** [comment]
If somebody wants to contribute, I'll be happy to give the required access to repositories. Until then, there's nothing actionable here, so I'll go ahead and close this.
