### ISSUE TITLE
[js] add Clipboard API to the HTML externs

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8597]
I'd like to try out the new [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) and maybe use it where it's available, but it seems that we don't have externs for that at the moment. Probably just a matter of enabling the flag in the extern generator?

IIUC it's just two additions the `Clipboard` class and `Navigator.clipboard` field.

**Comment by haxiomic** [comment]
Flags are `dom.events.asyncClipboard` and `dom.events.asyncClipboard.dataTransfer`

There's a number of updates required to the generator to account types that have moved to `js.lib` but for now I can generate the new files and merge them in manually
