### ISSUE TITLE
Functions in macro parameters are not correctly processed

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFoundation/haxe#8605]
haxe 4rc3, target HTML5

Example (using dev flixel):
```haxe
@:build(flixel.system.FlxAssets.buildFileReferences("assets/sounds", false, null, function(s) {return ~/\.ogg$/.replace(s, "");}))
class SoundAssets {}
```

Produces this error:
```
characters 103-127 : Field index for r not found on prototype EReg
```

It works fine on flash, windows, neko. If I move the function into the body of the `buildFileReferences` function then it is also fine.

**Comment by haxiomic** [comment]
@JoeCreates could you create and attach a minimal example project to reproduce the issue?

**Comment by JoeCreates** [comment]
@haxiomic http://try-haxe.mrcdk.com/#84Cd2

**Test.hx**
```haxe
class Test {
  static function main() {trace("Haxe is great!");}
}

@:build(Macro.func(function() {return ~/abc/.replace("abc", "123");}))
class MacroBuiltClass {
  public function new() {}
}
```

**Macro.hx**
```haxe
import haxe.macro.Expr;
import haxe.macro.Context;

//use this for macros or other classes
class Macro {
  public static function func(reg:Void->String):Array<Field> {
    return Context.getBuildFields();
  }
}
```

Apparently it builds if you don't actually try to use the EReg. I had to add the `.replace(...)` for it to break.

**Comment by haxiomic** [comment]
Perfect, thanks @JoeCreates !

**Comment by haxiomic** [comment]
Hmm seems like there's a bigger issue than just EReg, using trace doesn't work either
```haxe
@:build(Macro.func(function() {
  trace('hmmm');
}))
```
```Test.hx:8: characters 3-8 : Unknown identifier: `trace```
For JS and `EvalContext.RunTimeException(_, 0, _)` on Neko

Compiles in haxe 3 but not haxe 4

**Comment by haxiomic** [comment]
From @Aurel300 on slack

> It looks like the function there is not properly post-processed
e.g. on JS that backtick-trace should turn into console.log

I've renamed this issue to indicate the root cause

Also occurs in regular macros 
`Macro.test(() -> trace('test'));`

http://try-haxe.mrcdk.com/#96bB7

**Comment by Simn** [comment]
This has been fixed by https://github.com/HaxeFoundation/haxe/commit/6ae54f52c0bd10c4fc0899c70572256b3e58d6a4 and https://github.com/HaxeFoundation/haxe/commit/9cd32278ae65d448ba6eedc604098346d77ea7f2
