### ISSUE TITLE
Relaxed read/write access requirement in interface

### ISSUE THREAD

**Issue by JoeCreates** [HaxeFoundation/haxe#8606]
Consider the following example ([http://try-haxe.mrcdk.com/#a8Aba](http://try-haxe.mrcdk.com/#a8Aba)): 

```haxe
class Test {
    static function main() {
        trace(new A().description);
	trace(new B().description);
    }
}


// An interface which only requires read access on a "description" field
interface Describable {
    //public var description:String;
    //public var description(get, dynamic):String;
    //public var description(default, never):String;
    //public var description(dynamic, dynamic):String;
    //public var description(read, _):String; // Something like this?
}

// Has a var description
class A implements Describable {
    public var description:String;
  
    public function new() {
       description = "This has an absolute description";
    }
}

// Has a property description
class B implements Describable {
    public var description(dynamic, dynamic):String;
    private function get_description():String return 'Some $age year old thing.';
   
    public var age:Int; 
  
    public function new() {
    	age = 20;
    }
}
```

We have an interface which only cares that an implementing class provide read access to a `description` field. Unfortunately it seems that haxe presently requires that the interface define whether it is expecting a var or a property, even though this would have no practical implication.

I have run into an issue on some occasions whereby I wish to add an interface to a subclass of a class from a third party library which provides the field I access need, but it is inconsistent with other classes which also need to implement the interface with respect to whether a var or property is used. Because it is in a third part library is is not possible to simply change everything that needs to implement the interface to either a property or field.

I have previously used a build macro to add in a proxy field (for example `getDescription()`) but this isn't ideal.

I don't see any reason why this shouldn't be possible in principle, seeing as we really don't care what kind of field it is, only what kind of access we have.

Perhaps a solution might include introducing a getter/setter rule which means effectively "any readable" and "any writable", which can be used only in interfaces?

**Comment by RealyUniqueName** [comment]
This is not possible. Haxe compiler needs to know what to generate - a call `obj.get_description()` or a field access `obj.description`.
```haxe
function doSomething(obj:Describable): {
  return obj.description; //Should this call `get_description()` or read a field `description`?
}
```

**Comment by Gama11** [comment]
I guess techincally it could be possible by generating a `Reflect.getProperty()` call? Hidden reflection like that seems like a bad idea though.
