### ISSUE TITLE
Flash: removing an item from an Array fails

### ISSUE THREAD

**Issue by danielbenmergui** [HaxeFoundation/haxe#8612]
class Test
{
	public function new(){}
}
var test = new Test();
var array = new Array<Test>();
array.push(test);
array.remove(test); <-----

This code fails at runtime with 
"TypeError: Error #1006: removeAt is not a function."

This is the problematic code at Boot.hx:
		aproto.remove = function(obj) {
			var idx = __this__.indexOf(obj);
			if( idx == -1 ) return false;
			#if flash19
			__this__.removeAt(idx);<--------
			#else
			__this__.splice(idx, 1);
			#end
			return true;
		}

Compile command:
haxe  -lib air4haxe -cp src -swf C:/dev/shooter/bin/shooter.swf -swf-header 800:600:30:FFFFFF -swf-version 32.0 -main Main

Haxe Version: 4.0.0rc3 (didn't happen in rc2)

**Comment by nadako** [comment]
Not sure why this wouldn't happen in RC2 as this optimization was added years ago: https://github.com/HaxeFoundation/haxe/commit/0b8b09147562033fa7a06f90fe123fe6cef926a7

Anyway the problem is that you're compiling with swf-version 32, but seems to be using an older run-time version which doesn't have `Array.removeAt` (should be there since Flash/AIR 19)

**Comment by RealyUniqueName** [comment]
Indeed.
It did work in RC2 because flags for flash versions above 17.0 were not defined in the compiler and `#if flash19` branch was never compiled unless `-D flash19` flag was explicitly used. 
In RC3 that was fixed.
You have to either update your runtime or use `-swf-version 18.0` or use `Array.splice()` instead of `Array.remove()`

**Comment by danielbenmergui** [comment]
Are you positive it's a problem on my side? because when it fails:

- my flash runtime is 32.0.0.116 (I printed it out at the start of my app)
- haxe command line has -swf-version 32.0
- generated swf is version 43 (=32.0 AIR), checked with swfdump
- application.xml has <application xmlns="http://ns.adobe.com/air/application/32.0">

The program fails when I run "adl.exe application.xml" (adl reports it's version 32 as well) with this stack:
TypeError: Error #1006: removeAt is not a function.
	at MethodInfo-125()[C:\haxe4rc3\haxe\std\flash\Boot.hx:259]
	at Main()[C:\dev\shooter\src\Main.hx:105]
	at Main$/main()[C:\dev\shooter\src\Main.hx:319]
	at boot_54ac/init()[C:\dev\shooter\?:1]
	at flash::Boot/start()[C:\haxe4rc3\haxe\std\flash\Boot.hx:70]
	at boot_54ac()[C:\haxe4rc3\haxe\std\flash\Boot.hx:38]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()

**Comment by nadako** [comment]
Could you please test if `Array.removeAt` is there for you if you access it from AS3 code? It might be a bytecode generation issue...

**Comment by nadako** [comment]
Ok, I can reproduce this, sorry for dismissing the issue too hastly

**Comment by nadako** [comment]
I also found an issue with cache server: when compiling through it, `flash19` is not there :-/

**Comment by danielbenmergui** [comment]
I tried this on an AIR AS3 project with the same environment and it worked fine:

> package
> {
> 	import flash.display.Sprite;
> 
> 	public class Main extends Sprite
> 	{
> 		public function Main()
> 		{
> 			var t:Test = new Test();
> 			var array:Array = new Array();
> 			array.push(t);
> 			array.removeAt(0);
> 			trace(array.length);
> 		}
> 	}
> }

On a minimal Haxe project with the same environment this fails at runtime:

> package;
> 
> class Test
> {
> 	public function new(){}
> }
> 
> class Main
> {
> 	static function main()
> 	{
> 		var t = new Test();
> 		var array = new Array<Test>();
> 		array.push(t);
> 		array.remove(t);
> 		trace(array.length);
> 	}
> }

**Comment by nadako** [comment]
Yes, I think I know the reason. I'm now curious if it ever worked even if you do `-D flash19` manually...

**Comment by nadako** [comment]
The issue has the same roots as #8536. I'm going to quickfix it and maybe look into a properly typed solution later.

**Comment by nadako** [comment]
Should work now! I'll leave the issue open because we want to set up CI testing for `flash19`.

**Comment by nadako** [comment]
Thanks for the report BTW, this is quite important!
