### ISSUE TITLE
Error: Could not process argument client.hxml (file not found)

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8613]
https://community.haxe.org/t/build-haxe-recipe-for-target-as3-cmi-failed/1953

after compile haxe source ,it's throw this error.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/62609333-26172600-b934-11e9-9106-ec99b0f17f83.png)

**Comment by Simn** [comment]
`git submodule init && git submodule update`.
