### ISSUE TITLE
[java]compile error?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8617]
only java target error.

https://github.com/ianharrigan/hxWebSockets/tree/6f3300dcfe275336340deded7f3298416e65f498

```
haxelib run hxjava hxjava_build.txt --haxe-version 4000 --feature-level 1
javac "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
src/hx/ws/WebSocketServer_start_54__Fun.java:21: error: illegal character: '`'
                `this.tick();
                ^
1 error
Compilation error
Native compilation failed
Error: Build failed
```

**Comment by Simn** [comment]
Please provide a small, reproducible example.

**Comment by Aurel300** [comment]
Isn't backtick the character the compiler puts in some "internal" variables it generates?

**Comment by sonygod** [comment]
@Simn 
try to build java target 

https://github.com/ianharrigan/hxWebSockets/tree/6f3300dcfe275336340deded7f3298416e65f498/Examples/sys-server

**Comment by sonygod** [comment]
haxe git version 

linux and windows both error?

**Comment by ianharrigan** [comment]
This seems to be a pretty minimal example (i just basically stripped out most of the stuff from hxWebSockets):

```haxe
package;

import haxe.Constraints.Constructible;
import haxe.MainLoop;

class Handler {
    public function new(s:String) {
    }
}

@:generic
class WebSocketServer
    #if (haxe_ver < 4)
    <T:(Constructible<String->Void>, Handler)> {
    #else
    <T:Constructible<String->Void> & Handler> {
    #end
    
    public var sleepAmount:Float = 0.01;
    
    public function new() {
    }
    
    public function start() {
        MainLoop.add(function() {
            tick();
            Sys.sleep(sleepAmount);
        });
    }
    
    private function tick() {
    }
}

class MyHandler extends Handler {
    public function new(s:String) {
        super(s);
    }
}

class Main {
    public static var sleepAmount:Float = 0.01;
	static function main() {
        new WebSocketServer<MyHandler>();
	}
}
```

result:
```
src\haxe\root\WebSocketServer_start_25__Fun.java:21: error: illegal character: '`'
		`this.tick();
		^
src\haxe\root\WebSocketServer_start_25__Fun.java:23: error: illegal character: '`'
		haxe.root.Sys.sleep(`this.sleepAmount);
		                    ^
src\haxe\root\WebSocketServer_start_25__Fun.java:23: error: ';' expected
		haxe.root.Sys.sleep(`this.sleepAmount);
		                     ^
src\haxe\root\WebSocketServer_start_25__Fun.java:23: error: illegal start of expression
		haxe.root.Sys.sleep(`this.sleepAmount);
		                         ^
src\haxe\root\WebSocketServer_start_25__Fun.java:23: error: ';' expected
		haxe.root.Sys.sleep(`this.sleepAmount);
		                                     ^
5 errors
Compilation error
Native compilation failed
Error: Build failed
Build halted with errors (haxe.exe).
Done(1)
```

**Comment by Aurel300** [comment]
The error seems very similar to #8605, but there are no macros here?

**Comment by Simn** [comment]
The Java target will be put in "regression fixes only" state with the Haxe 4.3.0 release. See https://github.com/HaxeFoundation/haxe/wiki/Target-Support-Level#java-and-c-since-430 for additional information. We apologize for any inconvenience this causes!

**Comment by ianharrigan** [comment]
Fair point - i havent tried hxWebSockets with jvm yet, but i have used jvm with much more complex things (native haxeui-android for example) and its working fine - so i my guess is hxWebSockets will work fine. Thanks for the info!

Offopic(ish): 

> While the C# target does not have a proper successor (yet?)

Can I infer from that there _might_ (maybe one day, possibly) be a CLI type target (similar to the jvm one)?

**Comment by Simn** [comment]
> Can I infer from that there might (maybe one day, possibly) be a CLI type target (similar to the jvm one)?

There have been some efforts in that regard, but it didn't materialize into anything substantial yet. There does seem to be a certain level of interest for a CIL target though, so who knows!
