### ISSUE TITLE
add compiler error for ternary operator with null condition

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#8634]
I can't imagine following code being written intentionally:
```haxe
class Test {
  static function main() {
    var b: String = null;
    trace(b = null ? "null" : "not null"); // note the =/== typo, traces "not null"
    trace(b); // traces "not null"
  }
}
```
I propose add compiler error, when ternary operator condition is `null` identifier to help users avoid such typos.

**Comment by nadako** [comment]
wtf, this should give `String should be Bool` error...

**Comment by Simn** [comment]
It's stupid but consistent because this is handled as `b = (null ? "null" : "not null")` and `null` is typed as a monomorph which unifies with `Bool`.

**Comment by nadako** [comment]
Right, not even stupid if you think about it :) I guess that errors with the null-safety checks?

*UPD: yes, it does: `Null safety: Cannot use nullable value as condition in "if".`*

**Comment by back2dos** [comment]
The error seems easy enough to:

- make on the writer's part (as a typo of `expr == null`)
- spot on the compiler's part (check against `TConst TNull`)

Therefore I would argue to guard against it directly, instead of deferring it to null-safety (which is disabled by default).

**Comment by RblSb** [comment]
If that error can be added, why not make it in such cases too:
```haxe
if (foo = false)
if (foo = null)
foo = false ? _ : _;
```
Basically just prohibit assignments in conditions. I guess this is problematic because `if` is expression?

**Comment by Aurel300** [comment]
`if (x == false)` seems like bad style anyway. `if (foo = null)` can only compile if `foo` is `Null<Bool>` (or `Bool` on dynamic targets) I guess?

**Comment by kLabz** [comment]
> `if (x == false)` seems like bad style anyway.

Not for `Null<Bool>` values when absence of value is treated like `true`.

**Comment by back2dos** [comment]
Not sure how this debate around `if` is related, because for `if (x = null)` there's no ambiguity, while `x = null ? a : b` is not what one might think at first sight. When it's a typo for `x == null ? a : b` it will still compile, because it parses as something completely different from what was intended.

**Comment by Aurel300** [comment]
@back2dos 

```haxe
class Main {
  public static function main():Void {
    var a:{?x:Bool} = {};
    if (a.x = true)
      trace("true!");
  }
}
```

**Comment by back2dos** [comment]
Is `lhs = true` as a typo for `lhs == true` really something to worry about? There's a better syntax for that (i.e. `lhs`), while for `lhs == null` there isn't. It's true that in your example one might accidentally write `if (a.x = null)` but that only compiles for `Bool`, not for **every type** as it does in the original issue. That said, I don't mind guarding against any of these typos. It's just that the one above seems definitely likely enough to do something about it, while for the rest I'm not so sure.

**Comment by RblSb** [comment]
Agree that `if (foo = false)` mostly useless, but `if/while` for `(foo = bar)` bool comparison is fine case?

**Comment by EricBishton** [comment]
This is why old-time programmers learned to invert their tests (e.g. `if (false = foo)` obviously fails compilation).

IMO, this is a tool issue (e.g. `lint`), not a compiler issue.  The reason being that it is valid syntax, and by adding such a warning, you will be adding [potentially, a ton of] warnings that then will require a mechanism to suppress.  While it's nice for the compiler to find a bug for you, it's almost as bad to have to invent an `@(suppressWarning:assignmentWhereTestExpected)`  just to turn it off in working code.
