### ISSUE TITLE
Listing files with FileSystem.readDirectory on Windows 10 and cpp:

### ISSUE THREAD

**Issue by peppydip** [HaxeFoundation/haxe#8641]
I wrote a short program:

import sys.FileSystem;

```
class Main {
  static public function main():Void {
    trace("Hello World");
    trace(FileSystem.readDirectory('.'));
    trace(FileSystem.readDirectory('c:/'));
    trace(FileSystem.readDirectory('c:/my_storage'));
  }
}
```
Compiling like this:

`haxe -main Main -cpp .`

I got:

Main.hx:5: Hello World
Main.hx:6: [,,,,,,,,,,]
Main.hx:7: [,,,,,,,,,,,,,,,,,]
Main.hx:8: [,,,,,,,,,,,,,,,,,,,,]

The amount of items in the array matches the amount of files in each directory.
What happened to the names?

**Comment by RealyUniqueName** [comment]
What are your Haxe and hxcpp versions?

**Comment by peppydip** [comment]
haxe -version
3.4.4

haxelib version hxcpp
3.3.0

Is that the problem? 

Hi RealyUniqueName :)
I like your name, it's very meta.
I'm returning to Haxe after a while.

**Comment by peppydip** [comment]
I am confused?

C:\my_storage\work>haxelib install hxcpp 4.0.19
You already have hxcpp version 4.0.19 installed

C:\my_storage\work>haxelib version hxcpp
3.3.0

C:\my_storage\work>haxelib update hxcpp
hxcpp is up to date

**Comment by peppydip** [comment]
Also, if there is a workaround or a solution please let me know. This is not critical to my project but it can make my code much more flexible.

**Comment by RealyUniqueName** [comment]
> I am confused?
> 
> C:\my_storage\work>haxelib install hxcpp 4.0.19
> You already have hxcpp version 4.0.19 installed
> 
> C:\my_storage\work>haxelib version hxcpp
> 3.3.0
> 
> C:\my_storage\work>haxelib update hxcpp
> hxcpp is up to date

This is very strange.
Try `haxelib remove hxcpp` and `haxelib install hxcpp`

**Comment by RealyUniqueName** [comment]
Oh, wait. `haxelib version` just gives a version of haxelib itself. There is an issue: https://github.com/HaxeFoundation/haxelib/issues/451
To get a version of `hxcpp` you need to `haxelib list hxcpp`

**Comment by peppydip** [comment]
C:\my_storage\work>haxelib list hxcpp
hxcpp: [4.0.19]

Thanks! I haven't used Haxe in a while. I love it though. Especially appreciate, respect and full of gratitude for OpenFL.

**Comment by RealyUniqueName** [comment]
Try `haxelib install hxcpp 3.4.188`.
4.0.19 is probably for Haxe 4 only.

**Comment by peppydip** [comment]
Thank you so much! That was the reason.

Oh, oops. That is what I got ([4.0.19]) with the default Haxe install.
It seemed to work okay. :)
