### ISSUE TITLE
version() comparison with non-semver defines

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8650]
`#if (haxe >= version("foo"))` fails with `Invalid version string. Should follow SemVer` as expected. However, there's no such check for the LHS of the comparison.

Let's say somebody confuses the `haxe_ver` define with `haxe` (something which is probably going to happen a lot), all `version()` checks just seem to fail silently:

```haxe
class Main {
	static function main() {
		#if (haxe_ver >= version("4.0.0-rc.3"))
		trace(">=");
		#end

		#if (haxe_ver < version("4.0.0-rc.3"))
		trace("<");
		#end

		trace("test"); // only this traces
	}
}
```

So there should be an error for when the define used in the comparison isn't formatted as a SemVer as well.

**Comment by Gama11** [comment]
I wonder if there should be a special case for the `haxe_ver` / `haxe` case so something like "use the `haxe` define instead" can be added to a more general error message.

**Comment by Simn** [comment]
There's some wonky code in parserEntry.ml `eval`:

```ocaml
		let compare op =
			try TBool (try op (cmp v1 v2) 0 with _ -> false)
			with Invalid_argument msg -> error (Custom msg) p
		in
```

That inner `try` swallows the error which is raised by `cmp`. I tried fixing that but then I get a bad position for the error message.
