### ISSUE TITLE
[display] completion filtering doesn't work at the start of a function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8651]
As expected, Haxe returns only 33 items in the `display/completion` request when invoking completion after `buffer` here (JS target):

```haxe
class Main {
	static function main() {
		trace("");
		buffer
	}
}
```

However, at the start of a function, filtering doesn't seem to work at all, and it returns 1000 items.

```haxe
class Main {
	static function main() {
		buffer
	}
}
```

This is possibly related to the `replaceRange` missing from the response in this case. @Simn had to work around something related to this earlier already.

**Comment by Simn** [comment]
The problem is that compiler understands this as a structure declaration:

```
  54-  67 EDisplay DKStructure
  54-  67   EObjectDecl
  58-  64   buffer
  -1-  -1     null
```

**Comment by Simn** [comment]
Fixed, needs a test still. It's a bit messy to test because it requires checking if filtering occurred.

**Comment by Gama11** [comment]
Couldn't you just set a limit and check if the max number of items has been hit?

**Comment by Simn** [comment]
Yes that should work. Though we'll have to make sure that we use a filter name which is specific enough.
