### ISSUE TITLE
[display] null items in CompletionResponse.items

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8652]
Requesting completion outside of a class results in a response with `null` items:

```json
"result": {
    "items": [
        {
            "kind": "Keyword",
            "args": {
                "name": "private"
            },
            "index": 0
        },
        {
            "kind": "Keyword",
            "args": {
                "name": "extern"
            },
            "index": 1
        },
        null,
        null,
        null,
        null,
        null,
        {
            "kind": "Keyword",
            "args": {
                "name": "final"
            },
            "index": 7
        }
    ],
    "isIncomplete": false,
    "mode": {
        "kind": 14
    }
}
```

@Simn Was this perhaps intentional to preserve the index for `resolve` requests? If so, we never properly typed it as `Null<DisplayItem>` in `CompletionResponse`:

https://github.com/HaxeFoundation/haxe/blob/72ef1d389e1f1ae3fdbf8a9f6bf76d39774db23b/std/haxe/display/Display.hx#L434

However, rather than just changing the type, we should probably just not send any `null` items anymore now that there's an explicit `index` anyway.

**Comment by Simn** [comment]
This isn't intentional. Those are supposed to be `class interface enum abstract typedef`.

**Comment by Simn** [comment]
@RealyUniqueName Could I hire your debug services for this one? The compiler is supposed to emit [this list](https://github.com/HaxeFoundation/haxe/blob/development/src/compiler/displayOutput.ml#L755) of keywords. They are [converted to `CompletionItem.t`](https://github.com/HaxeFoundation/haxe/blob/development/src/compiler/displayOutput.ml#L775) and then (via `fields_to_json`) [printed to JSON](https://github.com/HaxeFoundation/haxe/blob/development/src/core/display/completionItem.ml#L591). What really confuses me is that `to_json` has no control flow where `JNull` is returned, so I don't underestand where these null values even come from.

**Comment by Gama11** [comment]
Hmmm... I just remembered the language server internally replaces some display items with `null` to provide snippets for those keywords instead. So this might simply be a bug in the methods view (showing the data _after modification_ rather than what we actually got from Haxe).

**Comment by Simn** [comment]
Ah I see. I thought they were legit missing from completion, but there are indeed snippets for `class` etc.  showing up. I simply ignored those because that's what I usually do with snippets. In that case there's no Haxe problem here.

**Comment by Gama11** [comment]
Yeah, in the output channel the response looks good, sorry for the false alarm.
