### ISSUE TITLE
Multiple interface extension with conflicting methods

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8656]
```haxe
interface Foo {
  function boo(a:Int):Void;
}
interface Bar {
  function boo(a:String):Void;
}
interface Foobar extends Foo extends Bar {}
class FoobarImpl implements Foobar {
  public function boo(a:Int):Void {}
}
```

In the above, `FoobarImpl` causes an error: `Field boo has different type than in Bar`. Likewise, with `boo(a:String)`, the error is `Field boo has different type than in Foo`. There is no way to fulfill the requirements of both interfaces (maybe in `extern`s with overloads?) – perhaps the error should be reported at the location of `interface Foobar`?

**Comment by RealyUniqueName** [comment]
Maybe we should also consider `class FoobarImpl implements Foo implements Bar` while we're at it.

**Comment by Simn** [comment]
This actually works fine on the JVM target:

```haxe
interface Foo {
	function boo(a:Int):String;
}

interface Bar {
	function boo(a:String):String;
}

interface Foobar extends Foo extends Bar {}

class FoobarImpl implements Foobar {
	overload public function boo(a:Int):String {
		return 'boo(Int): $a';
	}

	overload public function boo(a:String):String {
		return 'boo(String): $a';
	}

	public function new() {}
}

function main() {
	var c = new FoobarImpl();
	trace(c.boo(1));
	trace(c.boo("2"));
	var foo:Foo = c;
	trace(foo.boo(1));
	var bar:Bar = c;
	trace(c.boo("2"));
}
```

This tells me that the assumption that the interface requirements cannot be fulfilled is not generally correct, and in that case I'd prefer to not have any additional errors here.
