### ISSUE TITLE
[display] not enough stuff

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8657]
With completion filtering, the following doesn't include `Stream`-related types (Java target):

![](https://i.imgur.com/Th6ay3p.png)

Somehow it works fine with `Stream` capitalized though, even though filtering should be case-insensitive:

![](https://i.imgur.com/Irt2A6Z.png)

Most likely it doesn't work here at all (similar to #8651).

**Comment by Simn** [comment]
This is a general problem with the parser not accepting lower-case identifiers as type-hints.
