### ISSUE TITLE
[server] Lookup keys

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8667]
The server currently has multiple hash tables which are indexed by using the context signature:

```ocaml
c_files : ((string * string), cached_file) Hashtbl.t; (* file path * signature *)
c_modules : (path * string, module_def) Hashtbl.t; (* dot path * signature *)
c_removed_files : (string * string,unit) Hashtbl.t; (* file path * signature *)
```

I wonder if this is ideal for various reasons:

* Tuple keys use more memory
* Performing lookups requires allocation to create the tuple key ~They are stack-allocated, so there's no true allocation happening.~
* Obtaining all information of a specific signature requires iterating the entire content

The only advantage I see is that we have to perform only a single lookup.

What we could do instead is have an additional hash table which is indexed with the signature and resolves to `{ c_files; c_modules; c_removed_files }`. We can avoid the duplicate lookup by caching the reference to this hash table in the common context, so that we only look it up once per context (or more accurately, once per signature because at the moment signatures might change mid-compilation (#7871)).

Any thoughts?

**Comment by RealyUniqueName** [comment]
Sounds good. I have nothing to add. Except maybe common context is not the right place for it semantically since common context is not aware of compilation server.

**Comment by ncannasse** [comment]
While we're at it we could maybe have a int type for the signature index (into all signatures found so far) so the lookup by signature is even faster. That should not leak much.

**Comment by ncannasse** [comment]
or another way is to store the "latest" found cache (with current signature) and only fetch it if the signature has changed

**Comment by Simn** [comment]
We now reference the cache in the `common` context. This goes through a lookup while we're setting up (reading CLI args and executing init macros), and is then locked in place once we're sure that the signature doesn't change anymore.
