### ISSUE TITLE
UnicodeString.fromCharCode()

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8673]
Should handle codes even outisde of BMP.
But first check if `String.fromCharCode()` already does that.

**Comment by RealyUniqueName** [comment]
It's even tested
https://github.com/HaxeFoundation/haxe/blob/40f43c957480753001e69802d08b0f0dcf95d491/tests/unit/src/unitstd/Unicode.unit.hx#L4-L12

**Comment by Gama11** [comment]
Hm... does that mean that some `String` methods have full unicode support, while others don't? If so, that should probably at least be mentioned in the `fromCharCode()` docs.

**Comment by RealyUniqueName** [comment]
> some String methods have full unicode support, while others don't

That depends on a target. E.g. for php all String methods have full unicode support.

Maybe `UnicodeString.fromCharCode()` still should exist as an alias for `String.fromCharCode()`

**Comment by Gama11** [comment]
So there's no `fromCharCode()` with full unicode support on PHP?

**Comment by RealyUniqueName** [comment]
`String.fromCharCode()` has full unicode support on all targets

**Comment by sebthom** [comment]
@RealyUniqueName 
> `String.fromCharCode()` has full unicode support on all targets

That does not seem to be true at least for `neko`.

**Comment by Gama11** [comment]
https://haxe.org/manual/std-String-unicode.html

>All Haxe targets **except Neko** support Unicode in strings by default.

**Comment by sebthom** [comment]
So for Neko I would need a UnicodeString.fromCharCode() then?

**Comment by RealyUniqueName** [comment]
For neko there's `neko.Utf8`

**Comment by sebthom** [comment]
Nice, that's what I need. Using this prevents the deprecation warnings I get with `haxe.Utf8`.
Thanks!!
