### ISSUE TITLE
[display] parserEntry errors are missing from diagnostics

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8687]
I noticed that there's various errors in `parserEntry` that diagnostics don't show, such as:

```haxe
#if ("foo" == version("4.0.0")) // Invalid version string "foo". Should follow SemVer.
#if (version(false)) // Invalid version string "foo". Should follow SemVer.
```

So full diagnostics coverage requires more than just https://github.com/HaxeFoundation/haxe/issues/7931 after all.

**Comment by Gama11** [comment]
Something strange is happening here. This now reports a parser error diagnostic as expected:

```haxe
class Main {
	static function main() {
		#if ("foo" == version("4.0.0"))
		#end
	}
}
```

However, this does not:

```haxe
class Main {
	static function main() {
		trace("test");
		#if ("foo" == version("4.0.0"))
		#end
	}
}
```

For some reason the trace being there makes a difference.

**Comment by Simn** [comment]
The initial build request has the error in the console:

```
> source/Main.hx:4: characters 8-13 : Invalid version string "foo". Should follow SemVer.
```

The subsequent diagnostics request then only has this:

```
 4, js: parsed c:\git\haxerepro\source\Main.hx (cached, is intact display file)
```

The problem is that `block_with_pos'` has this catch:

```ocaml
| Error (e,p) when !in_display_file ->
```

I'll have to check why that's there because it looks very wrong...
