### ISSUE TITLE
performance  is very  slowly  when use Regular Expressions ?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8693]
when I run this code to js target, it uses less than 210MS, but hl target is freezing. 

```haxe
package;


import haxe.Json;

/**
 * ...
 * @author sonygod
 */
class Main 
{
	
	static function main() 
	{
		//trace(Date.now().toString());
		var t = Date.now().getTime();
		var gen = gen();
		trace(Date.now().getTime()-t);
		
	}
	public static function gen():Array<Array<Int>> {
		var _array:Array<Array<String>> = [];
		var array:Array<Array<Int>> = [];

		for (i in 10...100000) {
			var arr:Array<String> = Std.string(i).split('');
			if (arr.length == 2) {
				arr.unshift('0');
				arr.unshift('0');
				arr.unshift('0');
			}
			if (arr.length == 3) {
				arr.unshift('0');
				arr.unshift('0');
			}
			if (arr.length == 4) {
				arr.unshift('0');
			}
			var insert = true;
			var limit = 3;

			for (j in 0...2) {
				var count = 1;

				for (k in j + 1...5) {
					if (arr[j] == arr[k]) {
						count++;
					}
				}
				if (count > limit) {
					insert = false;
				}
			}
			if (insert) {
				_array.push(arr);
			}
		}
		trace("gen ok");
		var str = Json.stringify(_array);
		trace("to json ok");
		var r = ~/"/g;
		str = r.replace(str, '');
		trace("replace ok");
		array = Json.parse(Std.string(str));
		trace("covert to ok");
		return array;
	}
}
```

**Comment by sonygod** [comment]
@ConstNW , will you look at this issue?

**Comment by RealyUniqueName** [comment]
FYI this sample is trying to perform `EReg.replace()` on a 2MB string.
Until hashlink performance is improved you can use `str = StringTools.replace(str, '"', '');` instead of a regular expressions as a workaround.

**Comment by RealyUniqueName** [comment]
Reduced sample:
```haxe
class Main {
	@:analyzer(ignore)
	static function main() {
		var str = StringTools.lpad('', '"  ', 100 * 1024);
		var r = ~/"/g;
		haxe.Timer.measure(() -> r.replace(str, ''));
	}
}
```
I've added a test to Haxe benchmarks: https://github.com/HaxeFoundation/haxe/blob/2067554/tests/benchs/src/cases/Regexp.hx#L6
Here are the results for our targets:

| Target     | Ops per 0.5s |
|------------|--------------|
| Hashlink   |            7 |
| Cpp        |           10 |
| Eval       |           10 |
| Python     |           83 |
| Neko       |          122 |
| C#         |          293 |
| Javascript |          836 |
| Jvm        |         1776 |
| Java       |         1816 |
| Php        |         2192 |

More than half of our targets have poor performance of `EReg.replace`. At leat for this case.

**Comment by ncannasse** [comment]
Is it my eyes or PHP gets the fastest benchmark result ?

**Comment by Simn** [comment]
I didn't want to believe it, but I'm getting similar results running this locally...

**Comment by sonygod** [comment]
why my code for js target so fastest?
@RealyUniqueName , you test is difference result from my code.

**Comment by Simn** [comment]
Probably because you're benchmarking a whole lot of other stuff.

**Comment by RealyUniqueName** [comment]
PHP is fast here because regexps are just bindings to C implementation there.

**Comment by RealyUniqueName** [comment]
> Probably because you're benchmarking a whole lot of other stuff.

Myabe I don't understand how to use our benchmark suite. I think I only test `ereg.replace()`: 
https://github.com/HaxeFoundation/haxe/blob/20675543720a3abe862bb6237f6f32e5d698ad1b/tests/benchs/src/cases/Regexp.hx#L10-L12
With this command:
```
tests/benchs$ haxe build.hxml -D test=Regexp.measureReplace -neko bin/test.n && neko bin/test.n
Case: Regexp
  Suite: ~/"/g.replace(string, "")
    10Kb string: 122 (100.00%)
```

**Comment by Simn** [comment]
I wasn't talking to you. :P

**Comment by Simn** [comment]
Eval went from a score of 10 to ~460 with this change. Might want to use this for hxcpp as well.

**Comment by Simn** [comment]
We updated HL and hxcpp as well, they are at 170 and 270 now respectively (probably a bit more on @RealyUniqueName's computer). This should also have a positive effect on other regex operations. Global replace was most affected because it is implemented as a loop which would then perform the UTF8 check on every iteration.

That should conclude this issue.

**Comment by RealyUniqueName** [comment]
Yeah, on my laptop eval scores 663 now.

**Comment by Simn** [comment]
That feeling when your targets get beaten by PHP and your computer gets beaten by a laptop...

**Comment by RealyUniqueName** [comment]
13'' laptop btw...

**Comment by sonygod** [comment]
why close?

https://gist.github.com/sonygod/f92881c07d3cd2312c4c8959b019d15f

I retest this case and found Hashlink still slowy than Neko or other target.

![image](https://user-images.githubusercontent.com/748320/64394834-8d86d980-d08a-11e9-9418-e115647f8d48.png)

![image](https://user-images.githubusercontent.com/748320/64394860-a5f6f400-d08a-11e9-8db2-24480e1425ff.png)

![image](https://user-images.githubusercontent.com/748320/64394900-e48cae80-d08a-11e9-9ed7-43b9039d5626.png)

@RealyUniqueName @ncannasse  @Simn 

hashlink still 17x slowly than node.js


![image](https://user-images.githubusercontent.com/748320/64396056-fc663180-d08e-11e9-9ba4-6afb84241204.png)

php was broken,can't  test

**Comment by Simn** [comment]
This issue was about regular expression performance which has been addressed for HL. Your benchmark tests array creation and manipulation more than it tests regular expressions, and I don't want to muddle this issue with different performance problems.

If you can isolate another problem, feel free to open a new issue.

**Comment by RealyUniqueName** [comment]
> php was broken,can't test

@sonygod what was the error for php?
