### ISSUE TITLE
Feature Request: Function Signature Overloading

### ISSUE THREAD

**Issue by Joncom** [HaxeFoundation/haxe#8695]
Would be nice to be able to write Haxe like:

```haxe
class Foo {
    var image:js.html.Image;

    public function new() {}

    function setImage(imagePath:String) {
        var image = new js.html.Image();
        image.src = imagePath;
        return setImage(image);
    }

    function setImage(image:js.html.Image) {
        return this.image = image;
    }
}
```

And to have compile-time type safety that ensures only valid arguments (either a `String` or an `Image`) get passed to `setImage`.

Probably this would compile to two separate `setImage` functions, and the compiler would decide (at compile time) which function gets called based on the signature, so there shouldn't be any runtime performance penalty.

**Edit:**

There is a way to achieve [something like this](http://www.kevinresol.com/2016-11-23/haxe-method-overloading/), but it's hacky, not elegant, and worst of all, doesn't produce clear type errors when the wrong value gets passed to the function (instead of saying the argument must be a `String` or an `Image`, it says the value must be a `NameOfCustomType` which isn't very clear, even if you name that type something like `StringOrImage`).

**Comment by Simn** [comment]
This would have to go through https://github.com/HaxeFoundation/haxe-evolution. Note that we are unlikely to add overload support in general as it comes with a huge complexity. What could be considered is inline-only overloads.

**Comment by Gama11** [comment]
Note that there already was a proposal for this: https://github.com/HaxeFoundation/haxe-evolution/pull/14
