### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by eminfedar** [HaxeFoundation/haxe#8698]
For example in C#, you can copy the text of a textbox to the Clipboard by this command:
```
Clipboard.SetText(txtClipboard.Text);
```

I couldn't find a thing about it in haxe.

How to copy a text or something in haxe to OS's Clipboard?
Or is there anything for it?

**Comment by Aurel300** [comment]
I guess this is technically a sys API, but I don't know that many of our sys targets support it without additional libraries. Python has OS-specific solutions or e.g. TkInter. Java has awt. C++ would need OS-specific implementations. I don't think PHP has anything … etc.

So this is not easily supportable.

**Comment by Simn** [comment]
This is out-of-scope for the Haxe standard library.
