### ISSUE TITLE
Optional params on inline constructor gives odd error on classes with Type Parameters

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#8702]
The following works in 3.4.7 but fails in 4rc3 and the latest nightly build.
```haxe
class Test
{
    static function main()
    {
        var foo  = new Foo();             // works
        var bar1 = new Bar<String>();     // fails
        var bar2 = new Bar<String>(true); // works
        var baz  = new Baz<String>(true); // works
        var qux  = new Qux<String>();     // works
        var fum  = new Fum<String>();     // fails
    }
}
class Foo    { inline public function new (someBool  = true){} }
class Bar<T> { inline public function new (someBool  = true){} }
class Baz<T> { inline public function new (someBool:Bool   ){} }
class Qux<T> {        public function new (someBool  = true){} }
class Fum<T> { inline public function new (?someBool = true){} }
```
Getting the error:
```Test.hx:6: characters 17-34 : (?someBool : Bool) -> Void should be Void -> Void```

**Comment by Aurel300** [comment]
I think it should be:

```haxe
class Bar<T> { inline public function new (?someBool = true){} }
```

For that call to work. (Note the question mark.)

**Comment by Geokureli** [comment]
@Aurel300 That works in the latest nightly build here: http://try-haxe.mrcdk.com/#58fE7
it does not work on rc3, and this still seems like a bug. why is the `?` needed when the constructor is inlined?

**Comment by Geokureli** [comment]
Wait, my last statement was wrong, it fails with the `?` on the latest nightly as well

**Comment by Gama11** [comment]
@Aurel300 Optional arguments and arguments with default values are not the same thing.
