### ISSUE TITLE
Neko trace not support utf-8?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8703]
Neko trace not support utf-8?

![image](https://user-images.githubusercontent.com/748320/63733652-bef1ef00-c8ab-11e9-8366-ce401739bd24.png)

this character  is wrong.

**Comment by sonygod** [comment]
maybe this priority is low.

**Comment by Aurel300** [comment]
We can't tell which characters are wrong there, and it would be better if you had a simpler example with a code sample. Is it simply a `trace` with a constant Unicode string argument? Does the string come from the database?

Neko is officially not meant to be Unicode compliant. However, it's strings are binary, which means if you get a valid Unicode string and print it, it should probably work. You might also want to make sure you are using a Unicode-ready terminal, which is not true by default on Windows.

**Comment by sonygod** [comment]
```haxe
class Main 
{
    
    static function main() 
    {
        //trace(Date.now().toString());
        
        trace("支持中文");
        trace("日本語サポート");
        trace("支持國語");
        
    }
}
```

![image](https://user-images.githubusercontent.com/748320/63906756-a4567c00-ca4b-11e9-97b9-6dc4776c825b.png)

**Comment by RealyUniqueName** [comment]
Afaik, cmd.exe is not unicode-aware by default.
Try executing `chcp 65001` in the same terminal window before running your haxe-compiled programm.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/63918652-ab8f8100-ca6f-11e9-9845-d467cb0cf861.png)
