### ISSUE TITLE
Compiler hanging on invalid @:from (2) and a feature proposal

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8704]
```haxe
abstract Under<T>(T) {
    public function new(v:T) { this = v; } 
    @:from public static function from<T>(v):Under<T> { return v; }
}
        var u1 = Under.from({value:0.0, type:TFloat});
```

Related to #8588. Opening new issue because of the proposal. Notice use of inference to resolve a type by calling @:from function directly. Would be possible to have this for implicit cast? 

```haxe
        var u1:Under = {value:0.0, type:TFloat};
```

So that type could be resolved without using a type parameter. That could "justify" why Dynamic can be used without type parameter and possible have other uses in a future.

**Comment by Aurel300** [comment]
Why not

```haxe
var u1:Under<Float> = 0.0;
```

?

**Comment by Ilir-Liburn** [comment]
You mean
```haxe
var u1:Under<{value:Float, type:ValueType}> = {value:0.0, type:TFloat};
```
?

**Comment by Aurel300** [comment]
Oh right, I thought you were suggesting `{value: ..., type: ...}` as a special syntax. `Under.from(...)` doesn't seem to me to be too much to write, might not be enough of a reason to introduce a new feature for this.

**Comment by RealyUniqueName** [comment]
I agree with @Aurel300 it doesn't worth introducing a new feature.

**Comment by Ilir-Liburn** [comment]
Just crossed my mind while thinking about multitype abstract

```haxe
interface IA<T>
{
}

@:multiType
abstract Above<T>(IA<T>) {
    public function new();
    @:from static inline function fromInt(t:Int) return null;
    @:to static inline function toInt(t:IA<Int>) return {value:0, type:TInt};
    @:to static inline function toFloat(t:IA<Float>) return {value:0.0, type:TFloat};
}

        var a1 = new Above<Int>();
        a1 = 1;
        var a2 = new Above<Float>();
```

Made me wondering why is @:multiType used to mark abstract as multitype, while it's enough to use new() without a body to do so. Then I was wondering why is @:to used to return multitypes,  why not @:from (cast will work). And finally, why is @:from always just casting a value of the argument, even if null is returned like in above example.

And then came idea of using @:from inference like new() was called

 ```haxe
abstract Above<T>(IA<T>) {
    public function new();
    @:from static inline function fromIntType<T:Int>(t:IA<T>):Above<Int> return cast {value:0, type:TInt};
    @:from static inline function fromFloatType<T:Float>(t:IA<T>):Above<Float> return cast {value:0.0, type:TFloat};
    // regular from(s)
    @:from static inline function fromInt(v:Int) return cast {value:v, type:TInt};
    @:from static inline function fromFloat(v:Float) return cast {value:v, type:TFloat};
}
        var a1 = new Above<Int>();
        a1 = 1; // regular @:from called
        var a2 = new Above<Float>();
```

Which leaves space for @:to to be used for various conversions. In case of constructor having  arguments, @:from would have additional arguments like @:to.
