### ISSUE TITLE
[js] Trace on Haxe 4 

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#8713]
Would it be possible (or preferable make this default again) to not put position information in the first argument of `console.log` when using `trace`?

When doing: `trace("Haxe is great!")`  :
* Haxe 4 does `console.log("root/program/Test.hx:3:","Haxe is great!");`
* Haxe 3 did `console.log("Haxe is great!");`,

Haxe 4 traces can become unnecessary long if you have deep packages.  
I consider the clean log better, because if you have sourcemaps enabled, the browser should bring you to correct source file positions anyway.

![image](https://user-images.githubusercontent.com/576184/63932632-e08fd980-ca57-11e9-97e0-ad1af05b92ca.png)

**Comment by kLabz** [comment]
> or preferable make this default again

I disagree with this, I prefer current default over haxe < 4 behavior.

**Comment by markknol** [comment]
> I prefer current default over haxe < 4 behavior

I disagree because you now see the same information double, at least in my browser. This is exactly where sourcemappings are for.

![image](https://user-images.githubusercontent.com/576184/63863105-f648c480-c9ad-11e9-96ae-c8bc856c80f8.png)

**Comment by kLabz** [comment]
Not everyone use sourcemaps, and what about nodejs? Other browsers?

**Comment by dpomier** [comment]
Maybe we could have something like the following in `hxml`?
```haxe
-trace verbose
-trace concise
-trace no
```

**Comment by markknol** [comment]
> Not everyone use sourcemaps, and what about nodejs? Other browsers?

Firefox devtools supports it too
![image](https://user-images.githubusercontent.com/576184/63863551-b46c4e00-c9ae-11e9-9e21-0b44371bc1c6.png)

For nodejs, in chrome you can use `chrome://inspect` (or Edge uses `edge://inspect`) and run node with `--inspect`, I thought that also just uses sourcemapping.

**Comment by nadako** [comment]
I really like the current behaviour when writing for node.js because I can click on the trace and have my editor go to its call point :)

**Comment by markknol** [comment]
I wouldn't mind if this was a flag, so that extraparams.hxml of nodejs have `-D trace_positions` or something.

**Comment by kLabz** [comment]
It's the default behavior for all targets so I would expect a flag to _disable_ positions, not to enable them. As for extraparams of hxnodejs, again, not everyone use sourcemaps.

**Comment by ncannasse** [comment]
I don't think we want to change that. You can always have your own haxe.Log.trace binding that does exactly what you want.

**Comment by markknol** [comment]
> your own haxe.Log.trace

That doesn't work, because it, breaks the sourcemapping paths, every trace points to that custom trace function. That's why I propose to do it the other way around. 
I mean, the current Haxe 4 logging is a custom trace to me.

**Comment by kLabz** [comment]
Could we make `haxe.Log.formatOutput` dynamic too so that it could be easily overridden for this kind of use? (or any other trace format modification)

**Comment by nadako** [comment]
> That doesn't work, because it, breaks the sourcemapping paths, every trace points to that custom trace function. That's why I propose to do it the other way around.

BTW we randomly discussed several times the alternative way to override `trace` behaviour by overshadowing some `Trace.hx` module and providing a custom implementation for the `public static function trace`. I have a branch with a prototype of this idea and it could help with your source mapping issue: https://github.com/nadako/haxe/commit/963285f7d6012d9e56ec3c47eb1d5ee98042d719

**Comment by derRaab** [comment]
@markknol How did you manage to get the correct location output on the right?

**Comment by Gama11** [comment]
Simply compiling with `-debug` to get a source map should already do the trick.

**Comment by kLabz** [comment]
But position is set inside trace, not to trace call site

**Comment by derRaab** [comment]
`inline haxe.Log.trace( "output" )` would give the correct source map output.

`inline haxe.Log.trace( "output", null )` would be a great activatable behavior? (-D trace-console-log or something)

**Comment by Simn** [comment]
I don't think there's anything to fix here.
