### ISSUE TITLE
[jvm] Type.createInstance causes WrongMethodTypeException

### ISSUE THREAD

**Issue by malony0** [HaxeFoundation/haxe#8717]
In 4.0.0-rc3, `Type.createInstance(Foo)` causes `java.lang.invoke.WrongMethodTypeException` when compiled for Java target with `-D jvm` option, **if the class Foo:**
- is extending class
- calls non-static method as an argument of super()

For instance, the following code causes the exception:

```Haxe
class Main{
	public static function main(): Void
	{	
		var instance = Type.createInstance(Foo, []); //WrongMethodTypeException
	}
}

class Base
{
	public var name(default, null):String;
	
	public function new(name:String)
	{
		this.name = name;
	}
}

class Foo extends Base
{
	public function new()
	{
		super(createName());
	}
	
	private function createName():String
	{
		return "foo";
	}	
}
```

---

Also, such class seems to affect subsequently declared classes, even if the class itself is not used.
For instance, the following code also causes the exception:

```Haxe
class Main{
	public static function main(): Void
	{
		var instanceOK = Type.createInstance(BarOK, []); //OK
		var instanceNG = Type.createInstance(BarNG, []); //WrongMethodTypeException
	}
}


class Base
{
	public var name(default, null):String;
	
	public function new(name:String)
	{
		this.name = name;
	}
}

// class declared BEFORE Foo
class BarOK extends Base
{
	public function new()
	{
		super("bar");
	}
}

// Calls non-static function in super(), but not used in this code
class Foo extends Base
{
	public function new()
	{
		super(createName());
	}
	
	private function createName():String
	{
		return "foo";
	}
}

// class declared AFTER Foo
class BarNG extends Base
{
	public function new()
	{
		super("bar");
	}
}
```

Note that these codes work fine without `-D jvm` option.

**Comment by Simn** [comment]
Looks like I don't understand the Java reflection API:

![cmd_2019-08-30_11-16-39](https://user-images.githubusercontent.com/634365/64009351-0086d200-cb18-11e9-9076-e9300c839124.png)

Any pointers?

**Comment by Simn** [comment]
There were some issues with `Void` not actually being `java.lang.Void`, but even after fixing that I'm not getting a result here. Something else must be off.

**Comment by Simn** [comment]
I must be blind or something, the problem was quite obviously that the lookup was using `Void` instead of `void`, which isn't the same thing. This should work now, thanks for reporting!
