### ISSUE TITLE
neko UInt cast error

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8726]
it's seem all cast between ( Int,Uint) and Bool all wrong .
    
     package;

    import neko.Lib;

    /**
    * ...
    * @author sonygod
    */
    class Main 
    {
        
        static function main() 
        {
                
            var b = false;
            
            var c:UInt = cast(b, UInt);//neko target still error
            var d:Int = cast(b, Int);//neko target still error
            trace(c);
        }
        
    }

**Comment by sonygod** [comment]
related https://github.com/HaxeFoundation/haxe/issues/8716
@RealyUniqueName

**Comment by RealyUniqueName** [comment]
It's the designed behavior of safe cast. Trying to cast to an unrelated type (`Bool` to `UInt` or `Int` in your sample) should throw an error: https://haxe.org/manual/expression-cast-safe.html

**Comment by sonygod** [comment]
why close? @RealyUniqueName 

but Hashlink can safe cast from bool to int

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/64061616-dfa1a800-cc0f-11e9-87fc-dd5df73380b5.png)

**Comment by Aurel300** [comment]
That last picture looks more like the error to me @sonygod. `Bool` and `(U)Int` are not compatible, you should need something like `someBool ? 1 : 0` in general.

**Comment by RealyUniqueName** [comment]
Yeah, that's a bug in Hashlink.
