### ISSUE TITLE
Sqlite bug in neko and hashlink

### ISSUE THREAD

**Issue by nc-x** [HaxeFoundation/haxe#8728]
(Latest haxe development version.)
  
Neko
====
Build project with `haxe build.hxml`.
Run multiple times with `neko main.n`
The table contains 230 rows, but the output shows incorrect number of rows. Sometimes, it works fine.

```
λ neko main.n
src/Main.hx:7: 68
```  
  
HashLink
======
Modify `build.hxml` to build with `hl`.
Build and Run.
Garbage Output.

```
src/Main.hx:7: 230
src/Main.hx:10: 䙨Ń
src/Main.hx:10: 䡨Ńxs
src/Main.hx:10: 䙨Ń
src/Main.hx:10: 䡨Ńxs
src/Main.hx:10: 䙨Ń
src/Main.hx:10: 䡨Ńxs
src/Main.hx:10: 䙨Ń
src/Main.hx:10: 䡨Ńxs
src/Main.hx:10: 䙨Ń
src/Main.hx:10: 䡨Ńxs
src/Main.hx:10: 䙨Ń
etc..
```

Other Platforms
==========
Untested. Bug may or may not be present there.

[dbBug.zip](https://github.com/HaxeFoundation/haxe/files/3562618/dbBug.zip)

**Comment by RealyUniqueName** [comment]
Using slightly modified sample:
```haxe
import sys.db.*;

class Main {
	static function main() {
		var con = Sqlite.open("db.db");
		var rs = con.request("select * from tbl");
		trace(rs.length); // line 7

		// var rs = con.request("select COUNT(*) as cnt from tbl");
		// for (row in rs) {
		// 	trace(row.cnt); // line 11
		// }
	}
}
```
Prints 
```
src/Main.hx:7: 43
```
but if uncomment the second request:
```
src/Main.hx:7: 230
src/Main.hx:11: 230
```
I was unable to run on Hashlink because of my local issues.

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/64147496-069bec00-ce53-11e9-8510-3339671ca10e.png)

![image](https://user-images.githubusercontent.com/748320/64147534-2e8b4f80-ce53-11e9-9a0a-68e69472acd1.png)


it's work fine for me both Neko and Hashlink  ,Haxe version :4.0 rc3

**Comment by RealyUniqueName** [comment]
Could it be OS dependent? I'm using Linux.

**Comment by ConstNW** [comment]
neko on Windows got 230, on linux 46

**Comment by nc-x** [comment]
@sonygod That is not the expected output on hashlink. All the values inside the table are `abxs`.  And on neko, the output is sometimes correct, sometimes wrong. So maybe you were lucky there.
 
@RealyUniqueName 
On HL, the bug goes away after removing `rs.length` from the code. If you look at the value of cache around this line using either the hashlink debugger or print debugging, you will see that the values in the list get corrupted in an alternating fashion. 
https://github.com/HaxeFoundation/haxe/blob/ef9f3706bafa43da80052ea52837106cf8cac2bf/std/hl/_std/sys/db/Sqlite.hx#L168

Most probably, the `Reflect.setField` (used in `doNext()` down in the code) implementation is wrong for hashlink? I haven't debugged any further so I am not sure.

**Comment by sonygod** [comment]
@nc-x ,yes you're right .it's got wrong result return, Mayb be @ConstNW  can fix this bug.

**Comment by ConstNW** [comment]
neko result depends on build flag ```-D analyzer-optimize```

**Comment by RealyUniqueName** [comment]
Not analyzer's fault.
This also yields incorrect result without analyzer
```haxe
import sys.db.*;

class Main {
	static function main() {
		// var con = Sqlite.open("db.db");
		// var rs = con.request("select * from tbl");
		var rs = Sqlite.open("db.db").request("select * from tbl");
		trace(rs.length); // 43
	}
}
```
As you can see - the only difference is connection object used directly instead of storing it into a var.
Even worse - depending on the code around `rs.lengh` the result could be different.
E.g.
```haxe
var rs = Sqlite.open("db.db").request("select * from tbl");
trace('wtf');
trace(rs.length); // 37
```
```haxe
var rs = Sqlite.open("db.db").request("select * from tbl");
trace('wtf');
trace(rs.length); // 36
trace('wtf');
trace(rs.length); // 36
```
```haxe
var rs = Sqlite.open("db.db").request("select * from tbl");
trace('wtf');
trace(rs.length); // 32
Sys.sleep(1);
```
Currently I think it's a crazy neko runtime bug.

Didn't check hashlink yet.

**Comment by ConstNW** [comment]
i got that results:
```
neko | windows | analyzer-optimize    | 230
neko | linux   | analyzer-optimize    | 46
neko | windows | analyzer-no-optimize | 230
neko | linux   | analyzer-no-optimize | 230
```

**Comment by Simn** [comment]
Can you compare the output with `-D dump=pretty` (dump subdirectory).

**Comment by ConstNW** [comment]
[8728.dump-pretty.zip](https://github.com/HaxeFoundation/haxe/files/3574914/8728.dump-pretty.zip)

looks like 'analyzer-optimize' remove local variable of sqlite connection and GC delete it as unused.

**Comment by Simn** [comment]
That looks like some neko bug to me. The variable should not be necessary, and the broken code can be written by hand anyway.

**Comment by ConstNW** [comment]
make `var con` as `static var` then error disappear.

**Comment by Simn** [comment]
We will probably not fix the neko-specific bug. I recommend not using the analyzer on neko in this case.

We should figure out what's going on with HL though.

**Comment by RealyUniqueName** [comment]
After https://github.com/HaxeFoundation/neko/pull/200 is merged this issue will need a test.

**Comment by nc-x** [comment]
It seems to be fixed now on both Neko and Hashlink. Tested on Latest haxe and hashlink development builds.

**Comment by Simn** [comment]
I was told to close this!
