### ISSUE TITLE
Reduce memory consumption of local variables

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8735]
We currently have this structure for local variables:

```ocaml
tvar = {
	mutable v_id : int;
	mutable v_name : string;
	mutable v_type : t;
	mutable v_kind : tvar_kind;
	mutable v_capture : bool;
	mutable v_final : bool;
	mutable v_extra : tvar_extra;
	mutable v_meta : metadata;
	v_pos : pos;
}
```

There are two obvious points of attack to reduce memory consumption a bit:

1. Merge `v_capture` and `v_final` into ` v_flags : int` like we did with class fields. This saves 1 word per variable and is easily extensible if we want to add more per-variable flags at some point.
2. Fold `v_meta` into `v_extra`, which is already an `option`. The overwhelming majority of local variables has no metadata (and none of the other content in `tvar_extra`), so having an additional level of indirection for those that do is acceptable. This would save another word per-variable.

While 2 words isn't that much, the number of local variables can go into the millions. so this change would reduce memory consumption by some megabyte.

**Comment by RealyUniqueName** [comment]
I wonder if we could change `pos.pfile` to `int` and store a table of files somewhere.

**Comment by Simn** [comment]
The `v_meta` change is not worth it given that the analyzer uses `v_extra` to handle its marking.

**Comment by Simn** [comment]
One option would be to add a `v_mark : int`. That way the memory difference would be neutral for variables without metadata, but the transient memory profile would be a lot better during analysis because there's no longer a need to abuse the heavier `v_extra`.

**Comment by Simn** [comment]
I've made the meta change [on this branch](https://github.com/HaxeFoundation/haxe/tree/v_meta_in_v_extra) but my checks suggest that it is not worth it. I'll keep the branch but not merge it for now.

I'll also experiment with `v_mark` in a separate branch. It won't reduce memory consumption but might speed up the analyzer a bit.
