### ISSUE TITLE
Typed AST state

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8736]
While looking into #8734, I realized that we spend quite a bit of memory on keeping various states of the typed AST. At the end of a compilation, we can identify 3 different versions of the typed AST per class field:

1. The initial AST before optimization is stored in `cf_expr_unoptimized`. We need this version to ensure inlining works in subsequent compilations.
2. An intermediate state just before what we label "destructive" filters is captured in `cl_restore`. This is the state we return to when retrieving the module from the cache.
3. The final product that is passed to the generator is in `cf_expr`.

I would like to suggest an opt-in mode where we save the class state earlier, specifically at the point where we're currently saving `cf_expr_unoptimized`. This has some advantages and disadvantages:

### Disadvantages

* We have to run all the filters on all types when doing an actual compilation. This will obviously increase the time for a full compilation and is the reason why I want to make this opt-in.

### Advantages

* We can ignore `cf_expr_unoptimized` completely because it matches our saved class state. This saves around 10 MB on our JS unit tests (95 MB vs. 85 MB).
* We can unset `cl_restore` after calling it once because it will be set again if we reach the filter stage again. This is currently not possible because it is only set for new types. This saves another couple MB on the JS tests, and potentially some milliseconds on completion requests.

Overall, this would be more completion-friendly and less build-friendly, and I think having the option would be nice.

**Comment by ncannasse** [comment]
I think that's a very specific trade-off that is not very user-friendly, in the sense that it's very hard even for compiler devs such as myself to know exactly which impact this change will have on day-to-day usage.

Maybe a different approach would be to have some kind of "smart expr map", that would only create new AST nodes iff one the sub expressions has been changed, since I think most of the time the AST are ~95% similar between the different versions?

that would be like this for instance:

```ocaml
let rec smart_map f e =
    match e.eexpr with
    | TIf (cond, eif, eelse) ->
        let cond2 = smart_map f cond in
        let eif2 = smart_map f eif in
        let eelse2 = (match eelse with None -> None | Some e -> let e2 = smart_map f e in if e == e2 then eelse else Some e2) in
       if cond == cond2 && eif ==eif2 && eelse == else2 then e else { e with TIf(econd2,eif2,eelse2) }
...
```

**Comment by nadako** [comment]
> Maybe a different approach would be to have some kind of "smart expr map", that would only create new AST nodes iff one the sub expressions has been changed

Funny, I've done exactly this for my AS3->Haxe converter at work: ![](https://i.imgur.com/3ZVRfrq.png)

This helped a lot on at least node.js, but I was thinking that OCaml is smart enough to optimize this itself?

**Comment by Simn** [comment]
The problem here isn't that the values are redundant. The AST is probably quite different in a lot of cases (otherwise our optimization stage would be pointless). The problem is that we need to keep both the early and semi-optimized versions around due to our design.

And yes I also cannot tell what impact this would have, which is why I suggested it as an option.

**Comment by ncannasse** [comment]
> The problem here isn't that the values are redundant. The AST is probably quite different in a lot of cases (otherwise our optimization stage would be pointless). The problem is that we need to keep both the early and semi-optimized versions around due to our design.

I'm curious whereas this is actually true. For most code I write I think there's very little optimization actually necessary or possible. Not saying that I write highly optimized code, but just standard OO code is just plain function calls and if tests, with not much maths etc involved.

**Comment by Simn** [comment]
I realized that we can just unset `cf_expr` after compilation as it will be restored by `cl_restore` anyway. We don't have to keep the optimized state around in memory at all. This reduces persistent memory by about 5% on our unit tests.

Note that we're only doing this kind of maintenance if we have a non-blocking socket connection, so I'll likely be the only one benefiting from this until IDEs upgrade to `--server-connect`.

Either way, I think this is good enough for this issue.
