### ISSUE TITLE
Compilation server cache (leak?)

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8738]
Today I got a new error when dealing with compilation server cache:

I had a remove() method, then I changed some base class to use `h2d.Object` which has an inline remove. Later I removed the remove method (I'm not sure I compiled in between).

But when I was compiling I kept having this error message at a specific .remove() call: 
`Cannot force inline-call to remove because it is overridden`

The error kept showing at every compilation while the `remove` override method was no longer present.  Restarting VSCode did fix the issue.

**Comment by Simn** [comment]
Hmm yes, we never clear that `CfOverridden` flag after it has been set once. Have to find a good place to check if that needs an update. That might require checking all parent classes whenever a child class changes...

**Comment by Simn** [comment]
```haxe
// Base.hx
class Base {
	public function new() { }
	public function test() { }
}
```

```haxe
// Main.hx
class Child extends Base {
	public override function test() { }
}

class Main {
	static public function main() {
		var base = new Base();
		inline base.test();
	}
}
```

Compile, delete `Child` class, compile again, error.

**Comment by Simn** [comment]
Actually this requires an extra first step to remove the `inline base.test()` call. We need to compile without error in order to cache anything at all.

**Comment by Simn** [comment]
Unless I'm missing something obvious, this is pretty hard to fix. It requires checking for each removed `override` field if any of the ancestors now have fields which are no longer overridden. This means going up the inheritance chain to find overridden fields, then back down again to check if they are still overridden.

This would be manageable if we still had `cl_descendants` to work with, but that one is emptied when restoring the class from the cache. We then don't know a classes' descendants and can't do the "is this field still overridden" check.

I think we have to drop the `CfOverridden` flag and handle this differently. An option is to store all forced-inline-called-fields in the context, then (after post-processing set `cl_descendants`) manually check if such a field is overridden.

**Comment by Simn** [comment]
I had to disable the test because there are issues with the test implementation of `touchFile`. The underlying issue is fixed but we have to look into getting this test working properly.

**Comment by Simn** [comment]
Test is back up, will deal with the bad touch in #8761.
