### ISSUE TITLE
Constrained monomorphs

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8746]
This idea has been floating around for a while, so I would like to finally conceptualize it. Currently, our monomorphs are represented like so:

```ocaml
TMono of t option ref
```
This is equivalent to:

```ocaml
TMono of { mutable contents : t option }
```

I would like to propose adding an additional `constraints` option so that it becomes:

```ocaml
TMono of { mutable contents : t option; mutable constraints t list }
```

The idea is to distinguish the structure of unknown types from their identity. We define the following operations:

* `add_constraint mono t`: Adds the type `t` as a constraint to monomorph `mono`. This is only allowed if `contents = None`.
* `bind mono t`: Sets the `contents` of monomorph `mono` to type `t`. This is only allowed if `contents = None`. This operation unifies `t` which each of the monomorph's constraints.
* `unbind mono`: Unsets the `contents` of monomorph `mono`. We can utilize this for operations where we have to re-try typing, such as overloads.

### Field Access

This is the current situation:

```haxe
	static function infer(arg) {
		trace(arg.charAt(0));
		$type(arg); // {+ charAt : Int -> Unknown<0> }
		var s:String = arg; // {+ charAt : Int -> Unknown<0> } should be String
		$type(arg); // {+ charAt : Int -> Unknown<0> }
	}
```

With constrained monomorphs it would instead be:

```haxe
	static function infer(arg) {
		trace(arg.charAt(0));
		$type(arg); // TMono(T, [{+ charAt : Int -> Unknown<0> }])
		var s:String = arg; // ok, T = String
		$type(arg); // String
	}
```

Instead of binding the monomorph to the open structure, we add the open structure as a constraint to the monomorph. This maintains the structural constraints while keeping the monomorph identity intact. Upon assigning to `String`, we unify `String` with the open structure. This works, so we bind and continue.

### Map

Current situation:

```haxe
	static public function main() {
		var map = new Map();
		$type(map); // haxe.ds.Map<Unknown<0>, Unknown<1>>
		map.set(0, "foo");
		$type(map); // haxe.ds.Map<Int, String>
	}
```

There's this whole messy `@:multiType` architecture in place to resolve `Map` to its specializations (`IntMap` here). With constrained monomorphs, we could instead spawn Map instances with unknown key types as monomorphs constrained to the `IMap` interface:

```haxe
	static public function main() {
		var map = new Map();
		$type(map); // TMono(T, [IMap<TKey, TValue>])
		map.set(0, "foo"); // TKey = Int, TValue = String
		$type(map); // IntMap<String>
	}
```

### Type parameters

Type parameter constraints map directly onto the proposed structure:

```haxe
static function test<T:Float>(t:T) { }
```

Whenever we call that function, we turn `T` into a monomorph constrained to `[Float]`. This automatically takes care of constraints checks as soon as the monomorph is bound.

## Considerations

Some considerations and potential problems that have to be resolved:

### Inlining

With delayed binding, we might miss out on some `inline` calls. This requires performing some inlining on constrained monomorphs during post-processing, which shouldn't be a problem. Note that the `TMono` remain in the typed AST and can easily be detected.

### Type parameters

It might be necessary to also have a `t list` for type parameters on constrained monomorphs. There can be cases where we know our type parameters, but might not yet now our base type, so we essentially have something like `?<String>`. Here's a contrived example using `Map`:

```haxe
	static public function main() {
		var map = new Map();
		var s:String = map.iterator().next();
		$type(map); // haxe.ds.Map<Unknown<0>, String>
	}
```

In the case of Map we would have the type parameters as part of the `IMap` constraint anyway, but I'm not sure if that would apply to all cases. More research is required.

### Type inference and transitive constraints checks

There's nothing stopping us from using a constrained monomorph as a constraint for another constrained monomorph: `TMono(T1, [TMono(T2, [Constraint])])`. An open question is what exactly should happen if we bind `T1`. Going with the natural recursion, we'd get:

```ocaml
bind T1 String
  unify String T2
    bind T2 String
      unify String Constraint
    T2 = String
T1 = String
```

At a first glance, that looks correct. However, we probably have to consider the possibility of a subsequent constraint check failing. If `T1` was additionally constrained to `Constraint2` which would not be compatible with `String`, we would fail the unification after the `T2 = String` binding. This requires some more thought.

----

Note that this is a bit of a longer-term issue. I do think that we have to improve this in our type system though, in particular due to the `Map` situation. Hoping for some comments from @frabbit on this one!

**Comment by RealyUniqueName** [comment]
Would it be possible to make a recursive constraints chain? Or should that throw an error on `add_constraint`?

**Comment by Simn** [comment]
That should probably be allowed, but unification on `bind` might fail like it already does if you have a self-referencing `TMono`.

**Comment by Simn** [comment]
I'll make a change to `development` in preparation for this (see linked commit). Even if we decide to not go through with this, changing the architecture a bit is better for debugging:

```ocaml
type t =
	| TMono of tmono

and tmono = {
	mutable tm_type : t option;
}
```

This is exactly the same we have right now.

```ocaml
module Monomorph = struct
	let create () = {
		tm_type = None;
	}

	let bind m t =
		m.tm_type <- Some t

	let unbind m =
		m.tm_type <- None
end
```

Transition:

* `ref None` become `Monomorph.create()`
* `!r` becomes `r.tm_type`
* `r := Some a` becomes `Monomorph.bind r a`
* `r := None` becomes `Monomorph.unbind r`

Ultimately, we may want to hide the exact structure so that random parts of the compiler can't just mutate `mono.tm_type`. That's not super important right now though.

I've also tested memory impact of adding `tm_constraints : t list`. Our unit tests go from 81.4 MB to 81.5 MB.

**Comment by RealyUniqueName** [comment]
Maybe move `tmono` into `Monomorph.t` and hide `tm_type` behind the `Monomorph` interface. That would be cleaner and easier to maintain imo.

Edit: I should have read your message before looking into the commit :)

**Comment by Simn** [comment]
We can't move `tmono` because it's recursive to `t` and you can't have mutually recursive types and modules in OCaml.

**Comment by Simn** [comment]
Some more thoughts on how to handle this:

### Overall approach

* We collect all constrained monomorphs of a function inside the typing context, like we currently do for `ctx.opened`.
* When we're done typing the function, iterate all monomorphs and check:
  * If the monomorph is already bound, we generally don't have to do anything. We can look into checking something for #3033 though.
  * If the monomorph is unbound and has no contraints: Not quite sure. We might want to bind the momorph to `Dynamic` to avoid weird binding during post-processing.
  * If the monomorph is unbound and has constraints: Go to the interesting part.

### The interesting part

* If we have one of these multi-type things (not sure yet how to identify these exactly): Perform concrete type selection by whatever algorithm we fancy.
* If we have (possibly multiple) field constraints: Create an intersection `TAnon` to deal with #5225. We may have to do some additional checks here to make sure our field constraints work together.
* If we have a single constraint otherwise: It should be safe for the monomorph to be bound to that constraint now. I don't have a good intuition for this yet though.
* If there are multiple constraints: Maybe `unify_min`? Also not sure yet how this would happen exactly.

----

Something else I just thought of is that we could look into addressing this very old inference issue:

```haxe
class Main {
	static public function main() {}

	static function infer(arg) {
		var x = arg + arg;
		$type(arg + arg); // Int
		x = 1.; // Float should be Int
	}
}
```

Instead of inferring `arg` to `Int` like we do now, we could constrain it to `Float`. This way it can still become either `Int` or `Float`, depending on which it unifies with (both satisfy the `Float` constraint).

**Comment by RealyUniqueName** [comment]
Could it be useful for inliner? E.g. #7379?
I mean if something is typed as an anonymous structure it actually becomes a monomorph with a cosntraint to that structure. And then actual type is applied on inlining. It could make `Iterator<T>` return type and `Lambda` methods great at last.

**Comment by Simn** [comment]
The approach in my previous comment isn't going to quite work. The problem is that we don't want to deal with these monomorphs when we're done typing a function, we actually want to deal with them earlier. In case of the type parameter merge, we want to "close" the monomorphs after the call has been processed.

This is gonna be messy in our architecture because there are various paths into `unify_call_args'`. There is no single "start of a call" point in the compiler where we could determine which monomorphs have to be processed after unifying the call arguments. The basic pattern _should_ be:

1. Save current context monomorphs
2. Type call subject
3. Unify call arguments
4. Close open monomorphs
5. Reset context monomorphs

I'm not sure if we can do this without major refactoring. And I'm not even considering overloads yet...

**Comment by Simn** [comment]
## New idea: Binding callbacks

### Type parameter merging

Let's look at #5225:

```haxe
class Main {
	static public function main() {
		$type(merge({foo: 5}, {bar: "bar"}));
	}

	static function merge<A:{}, B:{}, C:A & B>(a:A, b:B):C {
		return null;
	}
}
```

The call to `merge` spawns monomorphs:

* `A` becomes a mono and is constrained to `{}`
* `B` likewise
* `C` becomes a mono and is constrained to both `A` and `B`

What we ultimately want here is to "close" `C` once both `A` and `B` are bound. The call unification would then proceed like so:

* `{foo: Int}` is bound to `A`'s monomorph (`{}` constraint is checked and holds).
* `C`'s monomorph is informed. It doesn't do anything yet because only one of its two constrained monomorphs is bound.
* `{bar: String}` is bound to `B`'s monomorph (`{}` constraint is checked and holds).
* `C`'s monomorph is informed. At this point, both of its constrained monomorphs are bound to concrete values, so we can bind it to the intersection type.
* Peace and harmony ensues.

### Map

With `Map` we have a total of 3 type parameters and monomorphs:

* Key type
* Value type
* Map monomorph

The definition of `Map` already communicates that only the key type parameter is relevant for the selection:

```haxe
@:multiType(@:followWithAbstracts K)
abstract Map<K, V>(IMap<K, V>)
```

This means that we add a binding callback to `K`'s monomorph which, when the monomorph is bound, informs the Map monomorph. The latter can then make its type selection.

**Comment by Simn** [comment]
I'll keep using this issue as my public diary because this is at such a large scale.

## Type specialization

When I'm mentioning `Map`, I'm actually talking about a more general problem of type specialization. For `Map`, the specializations are defined inside the abstract, which is bad. It would be much better to have 3 distinct parts:

1. The abstract definition which gives the structure (basically an interface that can also be constructed).
2. Concrete implementations which are compatible with the structure.
3. The mapping between the two.

For example, it could look like this:

```haxe
// Abstract definition
@:multiType
extern class MyMap<K, V> {
	public function new();
	public function set(k:K, V:V):Void;
}

// Concrete implementation, can be put anywhere
class MyIntMap<V> {
	public function new() {}

	public function set(i:Int, v:V) {
		trace('Setting $i = $v');
	}
}

// Mapping
using MyIntMap<T> as MyMap<Int, T>;
```

(Please don't discuss the actual syntax, I don't care about that at the moment).

Remarks:

* When processing the mapping, the structural compatibility has to be checked. Alternatively, we could require that both abstract and concrete classes implement a common interface. However, it makes sense for the concrete class to exist in its own right, so the mapping might be the better place to check this.
* When a monomorph which is constrained to an abstract type (in the sense presented here) gets a constraint satisfied (see previous comment), we check if there's a mapping that unifies. If so, we bind the concrete type to the monomorph.
* If we have leftover abstract types that haven't been mapped, we give a sensible error.
* Mappings can be imported via import.hx (and via `@:using`?) to give some default options.
* Users are free to create their own mappings.

**Comment by Aurel300** [comment]
How will you make sure the the `using ...` part is loaded? Which module does it belong to?

> If we have leftover abstract types that haven't been mapped, we give a sensible error.

Types that are just loaded, not instantiated? I imagine it might be useful to use the abstract type as an "interface", even though it will never be used due to e.g. conditional compilation.

**Comment by Simn** [comment]
> How will you make sure the the using ... part is loaded? Which module does it belong to?

It should use existing mechanisms, which is why I mentioned import.hx and `@:using`.

> Types that are just loaded, not instantiated? I imagine it might be useful to use the abstract type as an "interface", even though it will never be used due to e.g. conditional compilation.

Not sure what you mean, this is by definition about type instances. We can't have leftover abstract definitions in the output. We already error when this happens: `Type parameters of multi type abstracts must be known (for haxe.IMap<Unknown<0>, Unknown<1>>)`.

**Comment by Aurel300** [comment]
> It should use existing mechanisms, which is why I mentioned import.hx and @:using.

Right, but if I do:

```haxe
var myMap:MyMap<String, Int> = ...
```

Without any additional imports, how will the compiler find the mapping which is in a separate module? Requiring a `using` clause (per-file or in `import.hx`) for basic `StringMap`s is a breaking change and seems generally annoying.

> Not sure what you mean, this is by definition about type instances.

Right, my bad.

Also, how is the order resolved? How do you select which of these comes first:

 - `MyMap<Dynamic, V>` specialisation
 - `MyMap<Float, V>` specialisation
 - `MyMap<Int, V>` specialisation

All three would fit for `Int` keys.

**Comment by Simn** [comment]
> Without any additional imports, how will the compiler find the mapping which is in a separate module? Requiring a using clause (per-file or in import.hx) for basic StringMaps is a breaking change and seems generally annoying.

... which is why I keep mentioning `@:using`. Mappings would follow a similar handling.

> Also, how is the order resolved?

First match wins, following normal import order (latest first).

**Comment by Simn** [comment]
In my prototype I just managed to get the mapping to affect itself, so the `using MyIntMap<T> as MyMap<Int, T>;` became `using MyIntMap<T> as MyIntMap<T>;`, which causes everything else to not find the mapping.

That... is a really stupid problem to have.

**Comment by Simn** [comment]
After some more deliberation I've decided to drop this entire idea. I think the approach is sound in theory, but incompatible with our compiler architecture. I'll keep the branch around in case I want to come back to this.
