### ISSUE TITLE
HttpJs and http request with r.status == 0

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#8749]
when I do a http request and the server is not reachable then `r.status == 0`  and `r.response == null` in `onreadystatechange` (at least on Chrome in my tests). This case is not covered and the code takes the `default` route:
```haxe
    default:
	req = null;
	responseBytes = Bytes.ofData(r.response); // throws an exception here
	onError("Http Error #" + r.status);
```
but since `r.response == null` `Bytes.ofData(r.response)` throws an exception.

I think this case should be covered in the check for `s == null` :

```haxe
    } else if (s == null || s == 0) { // add check for s == 0 here
        req = null;
        onError("Failed to connect or resolve host");
    }
```

**Comment by haxiomic** [comment]
@AdrianV Thanks for reporting

I think `s == 0` for failed-to-resolve is fine

I think assuming [`r.response` is non-null in the default error case](https://github.com/HaxeFoundation/haxe/blob/bd87d4447d85094fdcfc60a3876c7dc548fed200/std/haxe/http/HttpJs.hx#L90) is problematic too. Maybe we should just guard with a null check here

Would you be up for making a PR?

**Comment by AdrianV** [comment]
yes no problem. I will prepare a PR
