### ISSUE TITLE
Context.defineType broken

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8750]
Due to recent changes, `Context.defineType({ pack : ["hxd","_res"], name : "_Ui_skills" ... })` does not work anymore. Seems like we check the module path on `hxd._res` only instead of `hxd._res._Ui_skills`

**Comment by ncannasse** [comment]
Putting back my comment from merged PR:

Please note that the error message is unhelpful : we often need the full module path to actually understand what's going wrong in macros.

**Comment by RealyUniqueName** [comment]
But it points to the position of module declaration.

**Comment by ncannasse** [comment]
Which was the build macro call for me... Not very helpful when your macro process thousands of files and one of it is actually triggering an invalid module name.

**Comment by Simn** [comment]
It's fine to include the full path in the message, but it also sounds like you could use a better position for that definition. Might help in other situations too.
