### ISSUE TITLE
sys.Http doesn't work anymore with SSL in PHP 

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8755]
After #8646 `sys.net.Socket` is used for http, but `php.net.SslSocket` (which extends `php.net.Socket`) is still used for https. The `setTimeout` functions are not compatible, one uses a socket resource, the other one a stream resource. Also extending `sys.net.Socket` for ssl does not work. No idea, how to get a ssl connection with `create_socket` in PHP...
What does seem to work is putting the `setTimeout` further down, after `sock.connect`, because after that a stream resource is used in `php.net.Socket`.

**Comment by Simn** [comment]
@Aurel300 Could you check this with priority?
