### ISSUE TITLE
Strange vars in PHP output

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8756]
In the current PHP output appear some redundant vars set to `null`, e.g.:
`$encoding = null;` or `$t = null;`
that are not in the source and are not used anywhere.

**Comment by Simn** [comment]
This comes from the changes to how default values are handled while inlining. Do these variables go away with `-D analyzer-optimize`?

**Comment by mockey** [comment]
Yep, that makes them go away.

**Comment by RealyUniqueName** [comment]
Doesn't look like we need to act here. Feel free to reopen if you have something to add.
