### ISSUE TITLE
Need a better touch

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8761]
The current implementation of [Vfs.touchFile](https://github.com/HaxeFoundation/haxe/blob/development/tests/server/src/Vfs.hx#L18) sucks and is causing a lot of CI instability:

```haxe
	public function touchFile(path:String) {
		var path = getPhysicalPath(path);
		FileSystem.createDirectory(path.dir);
		var file = Fs.openSync(path.dir + "/" + path.file + "." + path.ext, 'a');
		var last = Fs.fstatSync(file).mtime;
		var notNow = last.delta(1000);
		Fs.futimesSync(file, notNow, notNow);
		Fs.closeSync(file);
	}
```

I'm pretty sure I originally copied that from somewhere, but maybe I made some modifications that made it worse or something.

The issue is that the resolution (at least on Windows) of the file time modification is not small enough to support differences at the speed we're running our tests at. If there's no way to handle this properly, we might want to replace the filesystem-based touching with an [server/invalidate](https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/display/Server.hx#L37) request to Haxe. However, that way we'd technically lose some test coverage because we no longer check if Haxe handles file modification changes correctly.

Assigning to @Aurel300 for investigation.

**Comment by RealyUniqueName** [comment]
Why not using native system `touch` command? It exists in Mac & Linux. According to google Windows analogue is `type nul >> your_file.txt`

**Comment by ibilon** [comment]
How many tests like these are there? If it's small a sleep of like 0.5s might be enough for the difference to matter, and it's simple to add.

**Comment by Aurel300** [comment]
After some cursory debugging with Simon, I don't it is a problem with touch. `fstat` (and `stat`) confirm that the file indeed changes its mtime. `delta(2000)` adds two seconds, but it still fails on my system consistently, even though I'm pretty sure HFS+ has (sub-?) second precision in file timestamps.

A server invalidate request does fix the problem, so it is still *somehow* related to checking file modifications …

**Comment by Simn** [comment]
I've changed it to explicit server/invalidate requests for now because this is hurting my head, and the CI failures are hurting everyone else's heads.

**Comment by Simn** [comment]
Well, the tests still fail. Time to panic.

**Comment by Simn** [comment]
Note to self: Writing file contents does not necessarily update the modification time.

**Comment by ncannasse** [comment]
Yes, this depends on filesystem configuration

**Comment by back2dos** [comment]
> we might want to replace the filesystem-based touching with an server/invalidate request to Haxe. However, that way we'd technically lose some test coverage because we no longer check if Haxe handles file modification changes correctly.

Perhaps that can be quite interesting in that one could tie in a watcher and the server could thus forego all file system checks upon recompilation.

**Comment by Gama11** [comment]
We already do that for display requests in the language server (that's why `server/invalidate` exists in the first place).

**Comment by Simn** [comment]
The original issue occurred due to resolution problems plus me not knowing that writing to a file doesn't automatically update the modification time. So I don't think there's anything we have to actually do here.
