### ISSUE TITLE
`StringIteratorUnicode` on neko target seems buggy

### ISSUE THREAD

**Issue by akitsu-sanae** [HaxeFoundation/haxe#8763]
This code produces different output on JS and Neko target.
```haxe
import haxe.iterators.StringIteratorUnicode;
class Test {
    static function main() {
        for (code in StringIteratorUnicode.unicodeIterator("あああ")) {
            trace(code);
        }
    }
}
```
as follows:
```
$ haxe -main Test -js test.js
$ node test.js 
Test.hx:6: 12354
Test.hx:6: 12354
Test.hx:6: 12354
$ haxe -main Test -neko test.n
$ neko test.n
Test.hx:6: 227
Test.hx:6: 129
Test.hx:6: 130
Test.hx:6: 227
Test.hx:6: 129
Test.hx:6: 130
Test.hx:6: 227
Test.hx:6: 129
Test.hx:6: 130
```
On JS target, this iterate over unicode code points. On the other hand, on neko target, it looks iteraring over utf-8 code units.  

haxe version: 4.0.0-rc.3
node version: 8.9.1
neko vm version: 2.2.0

**Comment by ncannasse** [comment]
Given than StringIteratorUnicode is a replacement for previous haxe.Utf8, we should support Neko even if the platform has only partial unicode support.

**Comment by RealyUniqueName** [comment]
`StringIteratorUnicde` and such were not supposed to work with neko as neko strings don't support unicode.
We still have `haxe.Utf8`.

**Comment by ncannasse** [comment]
I understand but since StringIteratorUnicode is the new standard replacing haxe.Utf8 (if I understood correctly), maybe it should work with Neko as well ?

**Comment by RealyUniqueName** [comment]
Neko got `neko.Utf8` instead.

**Comment by akitsu-sanae** [comment]
So should `StringIteratorUnicode` on neko be implemented with `neko.Utf8` to behave same as on other targets?
