### ISSUE TITLE
[lua] malformed lua code in benchmarks

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8766]
```
$ cd tests/benchs && haxe build.hxml -D test=Regexp.measureReplac -lua bin/test.lua && lua bin/test.lua
/home/alex/lua_env-l5.1/bin/lua: bin/test.lua:1314: 'end' expected (to close 'function' at line 748) near '<eof>'
```

**Comment by jdonaldson** [comment]
This is no longer reproducible on lua 5.3 or luajit 2.0

**Comment by RealyUniqueName** [comment]
Do you mean we don't support 5.2 and lower?

**Comment by jdonaldson** [comment]
No, I just ran your example on those two runtimes.  It was broken before, but after a recent pull I can’t reproduce.

**Comment by RealyUniqueName** [comment]
But nothing has been changed in genlua. That means the bug is still there. It's just the Haxe code changed and it doesn't hit "bad" branch in genlua.

**Comment by RealyUniqueName** [comment]
And I still can reproduce it on the latest development.

**Comment by jdonaldson** [comment]
Ah I see.  I’ll take another look.

**Comment by jdonaldson** [comment]
This should be fixed in https://github.com/HaxeFoundation/haxe/commit/c396e0bd02d6b0719fee6198c9cf3651462cc11a
