### ISSUE TITLE
[js] var t = null 

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8770]
Looking at JS output changes, I noticed the following:

Several `var t = null;` are now inserted into various code parts - `t` being unused in the whole function - it comes from new Map() in member variables with auto generated constructors I think.

```haxe
class A { public function new() {} }
class Main extends A {
    var m : Map<Int,Bool> = [];
    public static function main() trace(new Main());
}
```

In JS output:

```js
var Main = function() {
        var t = null;
        this.m = new haxe_ds_IntMap();
        A.call(this);
};
```

**Comment by ncannasse** [comment]
Actually it's maybe all new Map, everywhere

**Comment by Ilir-Liburn** [comment]
Yes, I noticed that too making my own multitype abstract. However, analyzer-optimize removes t.
