### ISSUE TITLE
Python error when setting stdout – UnsupportedOperation('fileno')

### ISSUE THREAD

**Issue by botsman** [HaxeFoundation/haxe#8772]
```
~|⇒ haxe --version
4.0.0-rc.4+97f1e1a9d
```

I am not even sure if this should be fixed on the Haxe side. So feel free to close this issue if you think that it is on the VSCode side.

This error is mostly related to my setup/VS Code.
I use pytest in my project.

First, I compile my project to Python.
Then I run test discovery in VSCode, and I get such error:
```
sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1)
io.UnsupportedOperation: fileno
```

I checked test discovery in vscode, and it has the following code:
```
from io import StringIO

@contextlib.contextmanager
def hide_stdio():
    """Swallow stdout and stderr."""
    ignored = StdioStream()
    sys.stdout = ignored
    sys.stderr = ignored
    try:
        yield ignored
    finally:
        sys.stdout = sys.__stdout__
        sys.stderr = sys.__stderr__

if sys.version_info < (3,):
    class StdioStream(StringIO):
        def write(self, msg):
            StringIO.write(self, msg.decode())
else:
    StdioStream = StringIO
```

Looks like that the problem is in
```
ignored = StdioStream()
sys.stdout = ignored
```
Because after sys.stdout replaced with StdioStream, it gives an error if you try to call `sys.stdout.fileno()`

**Comment by RealyUniqueName** [comment]
Doesn't look like we have something to fix here.
Does that happen with a simple "hello world" project compiled to python?

**Comment by botsman** [comment]
Yes, that also happens with simple "Hello, world!" project.

The problem is that `sys.stdout` is redefined by `StringIO` before tests discovery starts.
Then during tests discovery this is executed from compiled python code:
```
if sys.stdout.encoding != 'utf-8':
    sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf8', buffering=1)
```
Which produces the error.

I thought maybe you would see some good solutions to this problem.
I guess you can close this issue as not related to Haxe.

**Comment by RealyUniqueName** [comment]
Try the latest change. Binary builds can be found here: https://build.haxe.org/builds/haxe/

**Comment by botsman** [comment]
Now it works. Thanks!
