### ISSUE TITLE
array.map Cannot use Void as value

### ISSUE THREAD

**Issue by axelhuizinga** [HaxeFoundation/haxe#8773]
With rc4 I have to rewrite
classes.map(function(cN:String) el.classList.remove('is-tooltip-$cN'));
to
classes.map(function(cN:String) {el.classList.remove('is-tooltip-$cN');return null;});
in order to compile

is this intended?

**Comment by kLabz** [comment]
Yes, although you should replace it with `for in` loops or with Simn's solution.

**Comment by Simn** [comment]
Or you can just add `using Lambda` and use `classes.iter(function(cN:String) ... )`.
