### ISSUE TITLE
File "_build/src/typing/typeloadFields.ml", line 802, characters 15-21: Assertion failed

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#8774]
Hey there

After upgrading to 4.0.0-rc.4 I'm getting the following error when compiling a large project:
File "_build/src/typing/typeloadFields.ml", line 802, characters 15-21: Assertion failed

Unfortunately it doesn't give any detail on which class it's failing on.. Any suggestions on troubleshooting this?

typeloadFields.ml
```
801							unify ctx e1.etype a.a_this e1.epos
802						| _ ->
803							()
```

**Comment by Simn** [comment]
Thank you for the report. This has already been addressed by https://github.com/HaxeFoundation/haxe/commit/58f54b372df85f42ee856212158c7799a2303439. Please try with the latest nightly from https://build.haxe.org/builds/haxe/ to confirm.

We'll announce our plan regarding this soon as it is a quite critical bug. Unfortunately, I still don't know which code causes it, so it's difficult to recommend workarounds.

**Comment by RealyUniqueName** [comment]
Given that we've reverted cast reduction in 4.0_bugfix branch I think this can be closed.
Feel free to reopen if you can still reproduce it with development version of Haxe.
