### ISSUE TITLE
Json.stringify is very very slowly ....

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8775]
Json.stringify is very very slowly ....

it seems all of haxe target is slowly, only the total length of array is 1000.

hl :9000ms

neko :14000ms

js:326ms

hxcpp:861ms

php: broken,JsonTest.hx:26: finish array 2
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 266240 bytes) in /root/test/jsonphp/lib/haxe/Json.php on line 36

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 266240 bytes) in /root/test/jsonphp/lib/haxe/Json.php on line 36

	package;
	import haxe.Json;

	/**
	 * ...
	 * @author sonygod
	 */
	class JsonTest 
	{

		static function main() 
		{
			var t1 = Date.now().getTime();
			var arr:Array<Array<String>> = [];
			var arr2:Array<String> = [];
					for (i in 0...1000) {
						
						for (j in 0...5){
							arr2.push(Std.string(j+i));
						}
					arr.push(arr2);
					}
					
					
			trace('finish array ${Date.now().getTime()-t1}');
			var t2= Date.now().getTime();
			Json.stringify(arr);
			trace('Json.stringify finish ${Date.now().getTime()-t2}');
			trace(Date.now().getTime() - t1);
		}
		
	}

![image](https://user-images.githubusercontent.com/748320/64406235-e5860600-d0b3-11e9-89b9-fe96090dbfd8.png)

![image](https://user-images.githubusercontent.com/748320/64406950-aeb0ef80-d0b5-11e9-8f91-840f1af617aa.png)

@RealyUniqueName

**Comment by RealyUniqueName** [comment]
That PHP error indicates that you hit a memory limit set in `php.ini` file (128Mb by default) change `memory_limit` setting in php.init to `512M` or `1024M`.

**Comment by sonygod** [comment]
also test this  cpu cost

neko :120%

hl:100%

node:<3%

hxcpp :<8%

php :~99%

	package;
	import haxe.Timer;
	/**
	 * ...
	 * @author sonygod
	 */
	class TimerTest 
	{

		static function main()
		
		
		
		{
			
				 
				 
				 var t = new Timer(1000);
				 
				 t.run = function(){
					 
					 var a = 0;
					 for (j in 0...10000000){
						 a+=j;
					 }
				 }
			 
			 
			 
		}
		
		
	}

**Comment by back2dos** [comment]
I guess that means neko can squeeze an extra 20% out of your CPU? :D

**Comment by Gama11** [comment]
Neko probably has some secret overclocking code...

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/64467799-064f6980-d14f-11e9-8511-696d13bbe16b.png)

@back2dos  4 cores

**Comment by sonygod** [comment]
maybe first fixed string performance.

**Comment by sonygod** [comment]
https://github.com/HaxeFoundation/haxe/issues/8780
