### ISSUE TITLE
macro @:from broken in rc4

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#8779]
This used to work in rc3:

```haxe
class Main {
    public static function main() {
        var suite:Suite = new BasicSuite();
    }
}

@:forward
abstract Suite(SuiteObject) from SuiteObject to SuiteObject {
	@:from
	public static macro function ofAny(expr:haxe.macro.Expr) {
		return expr;
	}
}


interface SuiteObject {}

class BasicSuite implements SuiteObject {
	public function new() {}
}
```

error: `BasicSuite should be Suite`

ref: https://github.com/haxetink/tink_unittest/issues/20

**Comment by Simn** [comment]
That's odd, it's not supposed to look at the `@:from` function here because the assignment should be allowed via the `SuiteObject` interface.

**Comment by Simn** [comment]
Did this call the `ofAny` in rc.3?

**Comment by Simn** [comment]
By the way, that `ofAny` is still going to fail with types that are legit incompatible. This is a deliberate breaking change because macro `@:from` used to be a type-hole which didn't check how the returned expression was typed at all. You'll probably have to make it `return macro cast $expr` now.
