### ISSUE TITLE
switch(this) stops working when default: is added

### ISSUE THREAD

**Issue by m0rkeulv** [HaxeFoundation/haxe#8781]
In previous  RC versions of Haxe 4 (RC3 and below)  it was possible  to do a switch case without a default statement. i have some code that performs a switch using a class `this` value, and up untill now it has been working fine.

After a bugfix in RC4 that forces `default:` my switch case logic no longer works and it looks like adding `default:` to previous RC versions also breaks the code.

```haxe
package;
class ComplexEnum
{

	public static final FIRST:ComplexEnum = new ComplexEnum("first", 0);
	public static final SECOND:ComplexEnum = new ComplexEnum( "second", 1);
	public static final THIRD:ComplexEnum = new ComplexEnum( "third", 2);

	var name(null, default):String;
	var value(null, default):Int;

	public function new (name:String, value:Int )
	{
		this.name = name;
		this.value = value;
	}

	public function getPrefix():String
	{
		switch (this)
		{
			case FIRST:
				return "first_";
			case SECOND:
				return "second_";
			case THIRD:
				return "third_";
			//default: throw "Unknown";
		}
	}

}

class Main
{
	static function main()
	{
		trace("value: "+ComplexEnum.SECOND.getPrefix());
	}
}
```

RC3:
running main with `default:` commented out will result in what i expect`value: second_`
if default is included in the code unknown is thrown
RC4:
code will not compile without  `default:`
if default is included in the code unknown is thrown

**Comment by Simn** [comment]
That's funny, the entire switch gets taken out by optimization in `reduce_control_flow`:

```ocaml
	| TSwitch (e1,cases,def) ->
		let e = match Texpr.skip e1 with
			| {eexpr = TConst ct} as e1 ->
				let rec loop cases = match cases with
					| (el,e) :: cases ->
						if List.exists (Texpr.equal e1) el then e
						else loop cases
					| [] ->
						begin match def with
						| None -> e
						| Some e -> e
						end
				in
				loop cases
			| _ ->
				e
		in
		e
```

Unfortunately, `this` is typed as `TConst TThis` so this branch is entered.

@RealyUniqueName Any idea what we changed here that could be related? I wonder why this didn't fail in rc.3 and before. The switch subject must have been temp-varred I suppose, but I don't remember changing anything in that regard for rc.4.

**Comment by Gama11** [comment]
It did fail before as well, just not when there was no `default` case. And the `default` case is now required.

**Comment by Simn** [comment]
Thanks for clarifying, I misread that a bit. It's good that the `default` is required now, but that optimization is obviously nonsense.
