### ISSUE TITLE
Make -debug more useful

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8784]
(Just a reminder following the Slack discussion.)

It would be nice if `-debug` was more useful. It changes behaviour for some targets (hxcpp in particular), but has next to no uses in the stdlib. Perhaps whenever the docs say `the behavior when X is unspecified` we should have a snippet like:

```haxe
#if debug
if (X)
  throw "unspecified behavior: X";
#end
```

At the beginning of the function. Maybe it would also be useful to introduce `haxe.DebugException` for these exceptions. Some possible applications: reading outside the bounds of `Vector`, passing `null`s anywhere in the filesystem classes, doing operations on closed files or sockets.

**Comment by ncannasse** [comment]
That would require some additional changes, for instance I think you only get source maps output in JS when compiling with `-debug`

**Comment by Aurel300** [comment]
We could have separate defines for specific "debug-like" features to allow more customisation. Still, I think `-debug` should by default turn on all these features – JS source maps, hxcpp `-g -Og` optimisation level during compilation, additional errors, etc. `-debug` is opt-in anyway.

**Comment by Gama11** [comment]
There's already `-D source-map`, though `--help-defines` says "php only".

**Comment by RealyUniqueName** [comment]
But it's also supported  by js:
https://github.com/HaxeFoundation/haxe/blob/202ef67a510e73021c0525e9f2661a4c0f33bf3e/src/generators/genjs.ml#L1511
`-D js-source-map` should be deprecated in favor of unified `-D source-map` as I'd like to bring source mapping to other targets someday.

**Comment by Simn** [comment]
I don't want to litter function code with such checks. Let's instead focus on #8905 and solve this as a subset.
