### ISSUE TITLE
Abstract ignores @:from when initialized from null

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8785]
```haxe
abstract Abstract(Float) {
    public function new(v:Dynamic) this = v == null ? 0.0 : cast v;
    @:from public static function from(v:Dynamic) { return new Abstract(v); }
}

    var n = new Abstract(null);
//  var n:Abstract = null; // On static platforms, null can't be used as basic type FNull
```

and here is why

```haxe
abstract Abstract(Dynamic) {
}
        var n:Abstract = null; // works
```

Compiler assigns null to underlying type implicitly even abstract type doesn't say so. This is making a problem to use abstract type without a constructor, like basic types do.

**Comment by RealyUniqueName** [comment]
`null` ignores `@:from` because it has no own type. So, when assigned to `Abstract` it's assumed to be of that type instead of `Dynamic`. I don't think we will ever change that.
You can "workaround" it like this: `var n:Abstract = (null:Dynamic)`

**Comment by Ilir-Liburn** [comment]
And what in this case?

```haxe
    @:from public static function from(v:Null<Float>) { return new Asbtract(v); }
```

Isn't logical to accept null implicitly where Null\<T\> is expected?

**Comment by Ilir-Liburn** [comment]
This works

```haxe
        var v:Null<Float> = null;
        var n:Abstract = v;
```

**Comment by RealyUniqueName** [comment]
> Isn't logical to accept null implicitly where Null<T> is expected?

No it's not. It's not correct to assume that `null` is of an underlying type or of a `@:from` type, because abstract itself is also nullable.

**Comment by Ilir-Liburn** [comment]
I agree to disagree
```haxe
        var u = null;
        $type(u); // Warning : Unknown<0>
        var v:Null<Float> = u;
        $type(u); // Warning : Null<Float>
```

Anyway, if constructor taking dynamic value accepts null, why not @:from?

**Comment by RealyUniqueName** [comment]
When you have `var v:Abstract = null` that `null` is typed as `Abstract`. When you have `var v:Null<Float> = null` that `null` is typed as `Null<Float>`. That's all. You can manually call your `from` function or explicitly type `(null:Dynamic)`.

**Comment by Ilir-Liburn** [comment]
I rest my case. For me, @:from is about converting of other types to underlying type of abstract type. Even null is other type (Unknown at beginning) which can be converted to underlying type of abstract type or Null type like I demonstrated. 

Anyway, I can use Null\<Float\> as underlying type to solve this problem, but that is having a performance issues which I'm trying to avoid.
