### ISSUE TITLE
Update "Breaking changes in Haxe 4" and "Haxe 4 migration" pages

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8786]
https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0

**Comment by ncannasse** [comment]
- FNamed for EFunction
- limitation in identifiers (keywords/valid fields identifiers + uppercase module name)

**Comment by Gama11** [comment]
- `StringLiteralKind` for `CString`
- `Cannot use abstract as value` error

**Comment by kLabz** [comment]
* `arr.map(cb:T->Void)` no longer accepted by compiler

**Comment by RealyUniqueName** [comment]
I've updated "Haxe 4 Breaking Changes".
Not sure if updating "Haxe 4 migration guide" makes sense because it's going to be a copy of "breaking changes". So, I'm closing this issue. Feel free to reopen if somebody has another opinion.

**Comment by ncannasse** [comment]
As long as each Breaking Change comes with instructions to "fix" it when
moving from Haxe 3.4 to Haxe 4.0 there's no need for a separate migration
guide.
