### ISSUE TITLE
Conversion between basic types - static platforms issues

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8788]
If this is not going to be fixed, at least use it for documentation

```haxe
        var b:Bool = true;
        var d:Float = cast b;
        b = cast d;
        trace(b);
        trace(d);
```

[cpp] all ok
[cs] failing on b = cast d
[java] all casts failing
[flash] all ok
[hl] all ok

and here are native solutions if anyone cares

```haxe
    var b:Bool = true;
#if cs
    var d:Float = untyped __cs__("System.Convert.ToDouble(b)");
    b = untyped __cs__("System.Convert.ToBoolean(d)");
#elseif java
    var d:Float = untyped __java__("Boolean.compare(b, false)");
    b = untyped __java__("Double.isFinite(d)");
#end
    trace(b);
    trace(d);
```

**Comment by Simn** [comment]
This is already [documented](https://haxe.org/manual/expression-cast-unsafe.html) to be undefined behavior:

> These casts are called "unsafe" because the runtime behavior for invalid casts is not defined. While most dynamic targets are likely to work, it might lead to undefined errors on static targets.

**Comment by RealyUniqueName** [comment]
I don't think we have something to do here.
If you're using untyped cast or pass a value through `Dynamic` you're disabling Haxe's type system. In this case you're on your own with target runtime behavior.

**Comment by Ilir-Liburn** [comment]
Sometimes I feel like I'm in a parallel universe. For example (CS)

```cs
	double f = ((double) (global::haxe.lang.Runtime.toDouble(((object) (b) ))) );
	b = global::haxe.lang.Runtime.toBool(((object) (f) ));
```

Obviously CS is not generating runtime behavior which is not defined, yet it is failing at toBool(). And then I give a solution for the generator, but it is my fault because I used untyped keyword demonstrating what should be generated, or at least used in toBool().

I could argue then that compiler should not implicitly accept null if abstract doesn't say so, because documentation is saying: "An abstract type is a type which is actually a different type at run-time. It is a compile-time feature which defines types "over" concrete types in order to modify or augment their behavior".

**Comment by kLabz** [comment]
> and here are native solutions if anyone cares

You don't need `untyped` there, this works fine:
```haxe
var b:Bool = true;
var d:Float = cs.system.Convert.ToDouble(b);
b = cs.system.Convert.ToBoolean(d);
trace(b);
trace(d);
```

**Comment by Ilir-Liburn** [comment]
@kLabz, I used untyped as demonstration what could be generated, not what user should write because it doesn't make sense to generate code which fails at runtime. However, I understand Haxe policy to rely on native behavior, although Haxe is a cross-platform tool.

BTW, there is no Double.isFinite in Haxe API,  so I was forced to use untyped anyway

**Comment by Simn** [comment]
Haxe being cross-platform doesn't imply that you can cast arbitrary types to each other and expect a consistent result.

I'm thinking that Haxe might not be the right tool for you altogether and that you should maybe look into some cross-platform VM which entirely abstracts the native behavior away. Alternatively, a more dynamic language might be better suited for your efforts.

**Comment by Ilir-Liburn** [comment]
Thanks @Simn, but I won't give up from Haxe just because I have different opinion. It's like with a human relationships: we have to learn to compromise.
