### ISSUE TITLE
[java] code too large

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#8792]
when running `haxe testJava.hxml` with Haxe 4rc4 (and latest git) for latest checkstyle, I get a Java compilation error:
```
src/haxeparser/HaxeParser.java:14412: error: code too large
	public java.lang.Object parseField(java.lang.Object e1, java.lang.Object p)
```

**Comment by Simn** [comment]
Could you check this with a nightly build from https://build.haxe.org/builds/haxe/?

**Comment by AlexHaxe** [comment]
I've tried latest git locally and TravisCI used 4.0.0-rc.4+8663dea0e (see 
 https://travis-ci.org/HaxeCheckstyle/haxe-checkstyle/jobs/583124248)

**Comment by Simn** [comment]
This is the same as #8793.
