### ISSUE TITLE
[jvm] Fatal error: exception IO.Overflow("write_ui16")

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#8793]
when running `haxe testJava.hxml` with `-D jvm` on Haxe 4 rc4 (and latest git) I'm presented with a fatal error:
```
Fatal error: exception IO.Overflow("write_ui16")
Raised at file "IO.ml", line 669, characters 30-59
Called from file "array.ml", line 80, characters 31-48
Called from file "array.ml", line 80, characters 31-48
Called from file "_build/src/generators/jvm/jvmAttribute.ml", line 200, characters 2-50
Called from file "list.ml", line 67, characters 20-23
Called from file "_build/src/generators/jvm/jvmMethod.ml", line 904, characters 19-100
Called from file "_build/src/generators/jvm/jvmMethod.ml", line 919, characters 14-28
Called from file "_build/src/generators/jvm/jvmClass.ml", line 162, characters 26-42
Called from file "list.ml", line 85, characters 12-15
Called from file "_build/src/generators/jvm/jvmClass.ml", line 158, characters 2-243
Called from file "_build/src/generators/genjvm.ml", line 2628, characters 11-26
Called from file "_build/src/generators/genjvm.ml", line 2159, characters 2-6
Called from file "list.ml", line 85, characters 12-15
Called from file "_build/src/generators/genjvm.ml", line 3056, characters 1-48
Called from file "_build/src/compiler/main.ml", line 342, characters 2-14
Called from file "_build/src/compiler/main.ml", line 1065, characters 25-62
Called from file "_build/src/compiler/main.ml", line 632, characters 3-11
Called from file "_build/src/compiler/main.ml", line 1226, characters 1-35
```

**Comment by Simn** [comment]
This is probably the same as #8792. The stack map has more than 2^16 entries, which is insane. We'll have to check the `-D dump=pretty` output to see what Haxe is doing there. My first guess is that there are thousands of @RealyUniqueName's inline default value branches being inserted.

**Comment by Simn** [comment]
He's innocent, it's some pattern matching code explosion. We should probably fix this in hxparse/haxeparser for now.

**Comment by RealyUniqueName** [comment]
This could happen even with "correct" code due to (ab)usage of inlining or just because of bad code (I've seen methods taking over 4k lines). There probably should be an inlining limit to workaround the former when targeting genjava.

**Comment by Simn** [comment]
It's not inlining, it's some combination of awful macros and pattern matching.

@AlexHaxe: I've updated haxeparser to remove these guards. This is technically not correct because the grammar now accepts too much, but I doubt that matters in practice. Please check if it works now.

I'm not sure if we have to take any action on the Haxe-side here. I don't think we can cause this kind of code explosion without macros, so this is basically a user problem (where user = me).

**Comment by Simn** [comment]
On the other hand, I'm not sure what changed here, so there may be some lingering problem in the pattern matcher code still.

**Comment by AlexHaxe** [comment]
TravisCI seems happy https://travis-ci.org/HaxeCheckstyle/haxe-checkstyle/jobs/583124248, local test run works too, thanks!

**Comment by Simn** [comment]
I don't see anything we have to do here on the Haxe-side at the moment. The original problem was caused by bad macro code, and there's nothing I can do in such cases. If we find a problem in the pattern matcher transformation, we'll fix it accordingly.
