### ISSUE TITLE
ClassType.fields.get() returning missing function fields for properties with getters

### ISSUE THREAD

**Issue by remiX-** [HaxeFoundation/haxe#8794]
Hey guys... So I'm going to try explain this as best as possible...

There seems to be an issue that occurred somewhere between 19th and 26th August. A build I am sure of on 19th works fine and then another build around 26th is where this issue started happening but left it until new RC came out.

Testing RC4 now and trying to debug it, I have isolated it to `ClassType.fields.get()` returning missing function getters for properties.

I'm not 100% how to explain this as I am not sure if I'm understanding it 100% but at least the expected output seems incorrect. So I'll just give an example and how to reproduce it easily... Maybe api changed and just need to use a different method possibly?

**Expected output:**
`Main.hx:20: [{name: get_name, isFinal: false, namePos: #pos((unknown)), isPublic: true, doc: null, params: [], pos: #pos(IThing.hx:4: characters 2-28), kind: #unknown(#unknown), meta: {get: #fun, remove: #fun, has: #fun, extract: #fun, add: #fun}, overloads: overloads, isExtern: false, type: TFun([],TInst(String,[])), expr: #fun},{name: set_name, isFinal: false, namePos: #pos((unknown)), isPublic: true, doc: null, params: [], pos: #pos(IThing.hx:4: characters 2-28), kind: #unknown(#unknown), meta: {get: #fun, remove: #fun, has: #fun, extract: #fun, add: #fun}, overloads: overloads, isExtern: false, type: TFun([{name: value, t: TInst(<...>,<...>), opt: false}],TInst(String,[])), expr: #fun},{name: name, isFinal: false, namePos: #pos(IThing.hx:4: characters 6-10), isPublic: true, doc: null, params: [], pos: #pos(IThing.hx:4: characters 2-28), kind: #unknown(#unknown,#unknown), meta: {get: #fun, remove: #fun, has: #fun, extract: #fun, add: #fun}, overloads: overloads, isExtern: false, type: TInst(String,[]), expr: #fun}]`

**Incorrect output:**
`Main.hx:20: [{name: name, isFinal: false, namePos: #pos(IThing.hx:4: characters 6-10), isPublic: true, doc: null, params: [], pos: #pos(IThing.hx:4: characters 2-28), kind: #unknown(#unknown,#unknown), meta: {get: #fun, remove: #fun, has: #fun, extract: #fun, add: #fun}, overloads: overloads, isExtern: false, type: TInst(String,[]), expr: #fun}]`

**How to reproduce**
So run as the code is below with `haxe -m Main --interp` and it will give incorrect output. Uncomment the explicit import for `IThing` interface and it will give expected output

**Sample code to reproduce**
Main.hx
```
package;

import haxe.macro.Context;
import haxe.macro.Type;
// import IThing;

class Main {
	public static function main() {
		var type:haxe.macro.Type = Context.getType("IThing");
		var classType:haxe.macro.ClassType;

		switch (Context.follow(type)) {
			case TInst(t, _):
				classType = t.get();

			default:
				throw "not implementend";
		}

		trace(classType.fields.get());
	}
}
```

An amazing interface
IThing.hx
```
package;

interface IThing {
	var name(get, set):String;
}
```

Another thing I found which seems to allow it to provide correct output is to declare a var of type `IThing` like `var thang:IThing;` anywhere within `main` function

Let me know if any other info may be required :)

**EDIT:**
`...between 19th and 26th July.`

I meant 19th and 26th August not July! Sorry

**Comment by RealyUniqueName** [comment]
I doubt `Context.getType()` is supposed to work outside of a macro. @simn?

**Comment by remiX-** [comment]
Ah interesting...

So this was found mainly from [mockatoo using it](https://github.com/misprintt/mockatoo/blob/master/src/mockatoo/macro/MockMaker.hx#L71) but that seems to be in macro context with the `#if macro`.

But seemed to have narrowed it down to `Context.getType()` but like I said maybe I am misunderstanding something.

So I tried nightly `525b38c` which I know it worked previously for a bigger project but it actually seems to not work for the example code, which makes me wonder.

**Comment by qwertykg** [comment]
Hi @Simn just to add a little context, @remiX- is on the same team as me and working on trying to get the latest haxe version working with our codebase so our team can all update to the latest changes :)

**Comment by Simn** [comment]
Thanks for the context!

I'm a bit confused that this apparently used to work because as @RealyUniqueName says, the `haxe.macro.Context` API should not be used outside macros. Does the field in question maybe just get dead-code-eliminated now?

**Comment by cmandlbaur** [comment]
This is within the macro context. As @remiX- mentioned we are encountering the issue using mockatoo which is using macros to generate mock objects to testing.

**Comment by Simn** [comment]
Alright, now I see what you mean.

Haxe indeed auto-generates these accessor methods on interfaces, but the exact timing of that is not defined. In previous Haxe versions, this would happen quite early, which lead to various other issues. We delayed the generation of this, which now causes the observed behavior.

So in my opinion you're relying on undefined behavior here and I don't think we could easily fix this anyway. This might be something that has to be fixed in mockatoo instead.

**Comment by Simn** [comment]
I just checked when this change was made. We originally delayed this [almost 2 years ago](https://github.com/HaxeFoundation/haxe/commit/1c9d096745de9edc910ce9b64d8f875bd079c6f9) and then delayed it a bit less [shortly after](https://github.com/HaxeFoundation/haxe/commit/9018960e7cbb1be722a74f9919ff9b3e5f90f8e7). So if this worked for you until now, you've either been very lucky with type loading order or something else changed that influences this.

**Comment by cmandlbaur** [comment]
Ok, thanks for the feedback. We will attempt a fix within our Mockatoo fork.

**Comment by remiX-** [comment]
Should have a solid enough solution in our fork, so will close this. Thanks!
