### ISSUE TITLE
[display] Code generation is executed on autocomplete if hxml contains --next

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#8795]
- I have some .hxml files that use hxpp and contain multiple targets separated with `--next`
- When I try to use autocomplete hxcpp starts compiling and generating output and autocomplete fails
- Autocomplete works when I remove the `--each` and `--next` flags

Maybe the solution is only pick the first batch for display and ignore the rest

Tested with latest git build https://github.com/HaxeFoundation/haxe/commit/de61358efb411ad199b54c58fb8468f5b514becd

In RC2 the behavior seems better – autocomplete works and code is only generated when vscode is building the cache

I've attached a minimal repo project:
[display-next-bug.zip](https://github.com/HaxeFoundation/haxe/files/3596901/display-next-bug.zip)

**build.hxml**
```hxml
-main Main
-lib hxcpp
-cpp bin

# Add some batches to trigger the bug
--each

-D HXCPP_X86

--next

-D HXCPP_ARM64
```
**Main.hx**
```haxe
class Main {

    static function main() {
        trace('Hello World!');
        // try autocomplete:
        // notice that bin/ gets created and autocomplete fails
        // Main.
    }

}
```

(Originally opened on vshaxe: https://github.com/vshaxe/vshaxe/issues/378)

**Comment by RealyUniqueName** [comment]
@Simn does this qualify for regression? Both behaviors (rc2 and rc4) seems wrong.

**Comment by Simn** [comment]
I think the problem here is that the `--no-output` which vshaxe sends alongside the cache build doesn't apply to the next `--next`.

... which would actually make this a vshaxe issue after all. I think it could just send `--no-output --each`.

But we can probably revert https://github.com/HaxeFoundation/haxe/commit/82bd2c8afce872db026d5bb6fc19b1449ec24296 anyway. I added it because our unit test `compile-java.hxml` and `compile-jvm.hxml` have some native compilation step which prevents completion from working. That's not very important though and can be fixed in our unit tests instead.

**Comment by Gama11** [comment]
>I think it could just send `--no-output --each`

Oh, can you have multiple `--each`?

**Comment by haxiomic** [comment]
@Gama11, multiple `--each` doesn't seem to work – haxe seems to ignore previous `--each` and its flags

I tried manually prepending `--no-output -D display-details` and it works but only _before_ https://github.com/HaxeFoundation/haxe/commit/82bd2c8afce872db026d5bb6fc19b1449ec24296 so I'd be in favor of reverting that one

Maybe the solution is:
- Revert https://github.com/HaxeFoundation/haxe/commit/82bd2c8afce872db026d5bb6fc19b1449ec2429
- In the haxe language server: **prepend** rather then **append** the display flags `--no-output -D display-details` so they're always attached to the first batch (which is the only one used when haxe is in display mode)
[Relevant language server code](https://github.com/vshaxe/haxe-language-server/blob/916cee2b1b0d49afc2547438d01c877ded3dd767/src/haxeLanguageServer/Context.hx#L359)

**Comment by Simn** [comment]
I agree, let's revert that. Assigning to our branch manager.

**Comment by haxiomic** [comment]
Thanks @RealyUniqueName :)

**Comment by haxiomic** [comment]
Added a [PR to the language server](https://github.com/vshaxe/haxe-language-server/pull/44/files)  that puts `--no-output` at the front rather than the end which fixes the autocomplete issue

To fix the cache builds I had to use a trick: `--no-output --each --no-output`, which makes sure `--no-output` is applied to all `--next` sets, whether or not the user uses `--each`. After that everything works correctly – so if that merges then this issue is fixed

A nicer way to fix the cache builds would be to only compile the first compilation set (like `--display` does) – is there a way to do this?

**Comment by haxiomic** [comment]
With 82bd2c8 reverted haxe now behaves correctly with `--next` so I'll close this issue and reopen the one on vscode
