### ISSUE TITLE
[Suggestion] Structures for enum types with parameters

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#8796]
My first language feature suggestion. Meant to reduce the need for switches to access enum parameters. I know nothing of what it takes to implement this, but I just thought I would throw it on the issues page.

Suggested syntax:
```haxe
enum Tree<T>
{
    Leaf(value:T);
    Node(left:Tree<T>, right:Tree<T>);
}

class Test
{
    static function main()
    {
        var tree = Tree.Node(Leaf(5), Leaf(7));
        
        if (tree.match(Leaf(_)))
        {
            // typecheck or cast as Leaf to treat as {value:T} typedef
            logLeaf((tree:Tree<Int>.Leaf));
            
            // Full type name not necessary, since tree is already typed as a Tree<Int>
            logLeaf((tree:Leaf));
            
            // inferred as leaf inside if blocks when Leaf is matched
            logLeaf(tree);
        }
        
        switch(tree)
        {
            case Leaf(_):
                // in switches too
                logLeaf(tree);
            case _:
        }
    }
    
    function logLeaf(leaf:Tree<Int>.Leaf):Void
    {
        trace(leaf.value);
    }
}
```

The main idea is that `Tree<Int>.Leaf` can be considered a structure, allowing leafs parameters to be accessed without using a switch. EnumType.SubType could behave similar to module SubTypes in terms on importing/referencing.

**Comment by Gama11** [comment]
>`case Node(left:Leaf(_), _):`

You can already do `case Node(left = Leaf(_), _)`, see https://haxe.org/manual/lf-pattern-matching-variable-capture.html.

**Comment by Geokureli** [comment]
@Gama11, Thanks, updated the example.

**Comment by Simn** [comment]
This is mostly #5167. The rest would have to go through https://github.com/HaxeFoundation/haxe-evolution, though I don't think we'll add any features just so that you can use `if` instead of `switch` to achieve the same thing.

Also note that you cannot cast to `Leaf` because that isn't a type.

**Comment by Gama11** [comment]
I think part of the suggestion was to _make_ `Leaf` a type.

**Comment by Geokureli** [comment]
looking at #5167
```
function isCat(a: Animal): a is Cat {
  return a.name === 'kitty';
}
```
what I really want is the ability to access parameters of enums by specifying that it is a certain enum type. the rest of my example was fluff as I thought about the possibilities of this move and I probably got way ahead of myself. The TS example above achieves most of what I want to see. Assuming that it would apply when Animal is an Enum and Cat is an Animal value with parameters

My proposal has ambiguity between `MyEnum.Foo` as an instance value and as a type. something like `MyEnum is Foo` is a nice solution.

**Comment by Geokureli** [comment]
Seems I mistook Nadako's proposal. and @Simn 's response so let me try and be more clear.
```haxe
enum Tree<T>
{
    Leaf(value:T);
    Node(left:Tree<T>, right:Tree<T>);
}
```
`Tree.leaf(5)` is essentially a `{ value:Int }` or `{ value:T }` but without the ability to access except by using a switch. I think it would be extremely helpful if we could cast or typecheck an instance of Tree to an instance of `{value:T}` by declaring that it is a Leaf-type Tree.

Consider the following example

**Comment by Ilir-Liburn** [comment]
You won't get Leaf as a type if you don't make it a type

```Haxe
typedef Tree_Leaf<T> = Tree<T> 

enum Tree<T>
{
    Leaf(v:T);
    Node(left:Tree<T>, right:Tree<T>);
}

class Test
{
    public static function main()
    {
        var tree = Node(Leaf(5), Leaf(7));
        if (tree.match(Node(_))) {
            logLeaf(tree.getParameters()[0]);
            logLeaf(tree.getParameters()[1]);
        }
        var tree = Leaf(0);
        if (tree.match(Leaf(_))) logLeaf(tree);

    }

    static function logLeaf(tree:Tree_Leaf<Int>):Void
    {
        trace(tree);
    }
}
```

**Comment by Gama11** [comment]
@Ilir-Liburn I don't really get what that code example is meant to show. That doesn't make `Leaf` a type either, it just gives `Tree` another name.

**Comment by Ilir-Liburn** [comment]
@Gama11, it was just a hint how to get access to Leaf as a type, not a real solution. I don't want to go under the hood this time, no way.

**Comment by Geokureli** [comment]
@Ilir-Liburn something like this is a little more in line with what I'm looking for
```haxe
abstract Tree_Leaf<T>(Tree<T>) to Tree<T>
{
    public var value(get, never):T;
    inline function get_value():T
    {
        return this.getParameters()[0];
    }
    
    public function new(value:T)
    {
        this = Leaf(value);
    }
}

enum Tree<T>
{
    Leaf(value:T);
    Node(left:Tree<T>, right:Tree<T>);
}

class Test
{
    public static function main()
    {
        var tree = Leaf(5);
        if (tree.match(Leaf(_)))
            logLeaf(cast tree);
    }
    
    static function logLeaf(tree:Tree_Leaf<Int>):Void
    {
        trace(tree.value);
    }
}
```
To clarify, my goal is to not have to manually create a type like `Tree_Leaf<T>` in order to handle instances already identified as leaves but to have types automatically generated based on the enum parameters.

**Comment by kLabz** [comment]
It seems strange to me to consider enum values as types =/

Your approach with abstracts can be achieved with macros; a starting point: http://try-haxe.mrcdk.com/#303aA (with a few TODOs to make it work with all enum values)

**Comment by nadako** [comment]
> It seems strange to me to consider enum values as types =/

FWIW I think that's how they work in some other languages, like "case class" in Scala, or "sealed" class in Kotlin.

**Comment by Geokureli** [comment]
@kLabz thanks for the head start, I've been looking for a reason to start messing with macros!
