### ISSUE TITLE
Completion via --display not working with compilation server (development)

### ISSUE THREAD

**Issue by kuremu** [HaxeFoundation/haxe#8798]
Given the following code (Main.hx):

```haxe
package;

class Main
{
    static function main()
    {
        var arr = new Array();
        arr.
    }

}
```

The command `haxe -main Main --display Main.hx@99  2>&1` gives expected completion output.

But if I try to connect to a compilation server with `haxe --connect 6000 -main Main --display Main.hx@99  2>&1` I get **"Main.hx:9: characters 5-6 : Unexpected }"**

Couldn't find much documented, hopefully it isn't some super obvious thing.

I'm using the dev version of Haxe on Debian testing

**Comment by RealyUniqueName** [comment]
I cannot reproduce this.

**Comment by kuremu** [comment]
> I cannot reproduce this.

The sample code was missing a newline - but after pulling the latest changes I can no longer reproduce it either! Closing.
