### ISSUE TITLE
[C#] Reflect.fields() / Reflect.field() on Array

### ISSUE THREAD

**Issue by marek-jelo-jelinek** [HaxeFoundation/haxe#8800]
Reflect.fields / Reflect.field behaves differently on arrays for C# target:

For example:
```haxe
var array:Array<String> = ["A", "B", "C"]; 
var object:{} = {"0":"A", "1":"B", "2":"C"};
trace("Array fields: " + Reflect.fields(array).join(","));
trace("Object fields: " + Reflect.fields(object).join(","));
trace(Reflect.field(array, "0"));
trace(Reflect.field(object, "0"));
```

Result for javascript and flash target is the same:
```
Array fields: 0,1,2
Object fields: 0,1,2
A
A
```
but for C#:
```
Array fields: __a,length
Object fields: 0,1,2
null
A
```

I understand that Array is not anonymous structure, but you must admit, it is little bit special e.g. it is used in JSON

Haxe v4.0.0-rc.2+77068e1

**Comment by kevinresol** [comment]
Doc: This method is only guaranteed to work on anonymous structures.

**Comment by RealyUniqueName** [comment]
`Reflect.field` doesn't have such doc and it works.
We need to unspecify it for `Array`.

**Comment by Simn** [comment]
I think this is actually supposed to work...

**Comment by Simn** [comment]
Oh wait no, lookup by `"0"` is certainly not supposed to work. But something like `Reflect.field(array, "length")` is.

**Comment by Simn** [comment]
In fact, there isn't even anything to document here. The documentation of `fields` already covers that it's not guaranteed to work for class instances, so whatever you get as a return from that function is already unspecified behavior. As far as Haxe is concerned, Array isn't all that special and fields like `"0"` simply don't exist.
