### ISSUE TITLE
[C#] Array.remove() not working for closures

### ISSUE THREAD

**Issue by marek-jelo-jelinek** [HaxeFoundation/haxe#8802]
It looks like **Array.remove** cannot compare closures correctly:

```
class Test
{
    public function new():Void { }
    
    public function foo():Void { }
    
    public function runTest():Void
    {
        var array:Array<Dynamic> = [];
        array.push(this.foo);
        array.remove(this.foo); // foo is not removed
        trace(array.indexOf(this.foo)); // this returns 0, so foo is definitely there
    }
    static function main() {
        var test:Test = new Test();
        test.runTest();
    }
}
```

Haxe v4.0.0-rc.2+77068e1

**Comment by Simn** [comment]
This is undefined behavior, you have to use `Reflect.compareMethods` to reliably compare closures.

**Comment by marek-jelo-jelinek** [comment]
Yes, I know that! Shouldnt it be handled in `Array.remove` then? Array should work on all platforms and in documentation is nothing special about using functions with arrays... And second thing - `indexOf` is working as expected, problem is only with `remove` method.

**Comment by Simn** [comment]
The documentation says:

> If x is found by checking standard equality

And with standard equality being undefined behavior for closures, it follows that this extends to `Array.remove`. The same applies to `indexOf`.

**Comment by marek-jelo-jelinek** [comment]
Indeed, you are right. It's a little bit sad tho. Thanks for reply.
