### ISSUE TITLE
[build]Error: Uninterpreted extension 'sedlex.regexp'

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8803]
/json.ml _build/src/prebuild/main.ml
    findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /root/.opam/4.04.0/lib/ocaml, /root/.opam/4.04.0/lib/ocaml/compiler-libs
    File "_build/src/core/json/json.ml", line 229, characters 15-28:
    Error: Uninterpreted extension 'sedlex.regexp'.
    Makefile:144: recipe for target 'prebuild' failed
    make: *** [prebuild] Error 2

**Comment by Gama11** [comment]
see https://github.com/HaxeFoundation/haxe/issues/8692
