### ISSUE TITLE
[C#] Invoke performance issues

### ISSUE THREAD

**Issue by marek-jelo-jelinek** [HaxeFoundation/haxe#8804]
```haxe
class Test
{
    public function new():Void { }
    
    public function sortFunc(a:Int, b:Int):Int { return a - b; }
    
    public function runTest():Void
    {
        var array:Array<Int> = [for (i in 0...10000) { Math.floor(Math.random() * 10000); }];
        
        array.sort(sortFunc);
    }
    
    static function main() {
        var test:Test = new Test();
        test.runTest();
    }
}
```
Test results (Unity mono):
time: ~400ms
allocated memory: ~17MB

Result from Unity Profiler:
![image](https://user-images.githubusercontent.com/26201241/64793727-c4258e00-d57b-11e9-9344-7c9a5cbeb786.png)

The problem seems to be in invocation of closure functions. In this case is `sortFunc` invoked 10002 times which should normally execute in no time and without allocations...

**Comment by Simn** [comment]
This is the same as #7441.

**Comment by nadako** [comment]
also same as #4393 and #3025

**Comment by nadako** [comment]
BTW I once worked on improving this a bit: https://github.com/nadako/haxe/compare/gencommon_faster_method_closures

**Comment by nadako** [comment]
anon function that calls the static function is an okayish workaround for the time being:

```
static function myCompare(...) ...;

array.sort((a,b) -> myCompare(a,b));
```

**Comment by dyarosla** [comment]
Anon function that calls a non-static function is also an okayish workaround for the time being.

    function myCompare(...) ...;
    array.sort((a,b) -> myCompare(a,b));

In some cases, it may even be faster to not use `static` because of #4297
