### ISSUE TITLE
[java] "Fatal error: out of memory" when building dox

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8808]
Dox Travis builds have started failing for the Java target: https://travis-ci.org/HaxeFoundation/dox/jobs/584721351

I can also reproduce this locally:

```
> haxe runBase.hxml -java bin/java
Fatal error: out of memory.
```

Considering it was still working yesterday at e552bdc57 (dox' Travis has daily cronjob), this must be a regression from https://github.com/HaxeFoundation/haxe/commit/7f02724c91e2e9fec05ea63263d6a529ae086878.

**Comment by RealyUniqueName** [comment]
Waiting for CI before merging into 4.0_bugfix
