### ISSUE TITLE
4.0.0-rc.4~5 regression? Std.is(myvar,AbstractType) no longer compiles.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/haxe#8810]
http://try-haxe.mrcdk.com/#Fa1ee
```haxe
class Test {
  static function main() {
    var myMap = new Map<Int,Int>();
    trace(Std.is(myMap, Map));
  }
}
```
On latest dev builds (checked 9/9/19 and forward): Error is: 
> `Test.hx:4: characters 25-28 : Cannot use abstract as value`

On 3.4.0, 3.4.4, 4.0.0-rc.1 and 4.0.0-rc.3, this compiles and runs just fine.

**Comment by Gama11** [comment]
That's not a regression, that's a bugfix. That never actually worked at runtime, since abstracts don't exist at runtime. See https://github.com/HaxeFoundation/haxe/issues/8550.

**Comment by EricBishton** [comment]
I was just noticing that the return value was always 'false'.  :/  Thanks.
