### ISSUE TITLE
[js] haxe_EntryPoint not support node.js

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8811]
package;
	import haxe.MainLoop;

	

	class Main {

		static function calc(){

				
			var i=100%10;

	}
		static function main() {
			trace("Hello, world!");

			MainLoop.add(function() {
				calc();
			
				
			});
		
		}
	}

I want to test in Node.js , it's throw  window is not defined

**Comment by ncannasse** [comment]
Did you compile with `-lib hxnodejs` ?
