### ISSUE TITLE
std/haxe/zip/Reader.hx:202: characters 11-39 : haxe.zip.Uncompress does not have a constructor

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/haxe#8818]
Hey there
I'm getting the following error after upgrading to haxe 4.0.0-rc5
std/haxe/zip/Reader.hx:202: characters 11-39 : haxe.zip.Uncompress does not have a constructor

haxe.zip.Reader.hx
////////////////////////////////////////////////////////////

line: 202
var c = new haxe.zip.Uncompress(-15);

haxe.zip.Uncompress.hx
////////////////////////////////////////////////////////////
package haxe.zip;

class Uncompress {

	public static function run( src : haxe.io.Bytes, ?bufsize : Int ) : haxe.io.Bytes {		
		var buffer = js.node.Zlib.inflateSync(js.node.Buffer.hxFromBytes(src),bufsize == null ? {} : {chunkSize : bufsize});
		return buffer.hxToBytes();
	}

}

**Comment by mikkelmr** [comment]
I'm pretty sure the error you encountered is related to https://github.com/HaxeFoundation/hxnodejs/issues/118

**Comment by peteshand** [comment]
👍thanks, will take a look
