### ISSUE TITLE
Questions about Class<T>

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8822]
Hej all,

I know there is not possible to have static fields on interfaces in Haxe, we can achieve many things related to statics using typedefs.
But when I find that Haxe has a strong typing for instances, I find there is less for statics fields.
I'm sorry It's a bit hard to explain, I mean for example `Type.getClass<T>( o : T ) : Class<T>` gives a kind of "generic" Class type where T represents more the instance than the class itself. By this I mean that It could be fine to have a kind of representation of the Class itself especially for its static fields.
I don't know if it's understandable, I'll try to make a little sample :

```haxe
typedef TEditable = {
    editable : Bool
}
    
interface IEditable{}
    
class A implements IEditable{
    public static var editable : Bool;
    
    public function new(){}
}

class B implements IEditable {
    public function new(){}
}

class Test {
    static function main() {
       var a = new A();
        var b = new B();
        foo( b );
    }
    
    static function foo<T:TEditable>( o : IEditable ){
        var cl	: T = cast Type.getClass( o );                    // <---
        trace( cl.editable );
    }
}
```
Here I must use `cast` in order to make it compile but then Haxe compiler lets `b`even it doesn't have the static `editable`.
The only solution to make it strictly typed is to give this `foo`function the class itself as argument like that : 
```haxe
typedef TEditable = {
    editable : Bool
}
    
interface IEditable{}
    
class A implements IEditable{
    public static var editable : Bool;
    
    public function new(){}
}

class B implements IEditable{
    public function new(){}
}

class Test {
    static function main() {
       var a = new A();
        var b = new B();
        foo( B, b );
    }
    
    static function foo<T:TEditable>( cl : T, o : IEditable ){
        trace( cl.editable );
    }
}
```
Even if we could here write `foo( A, b )` it's not really important because it's just to tell the compiler about the common for `A` and `B` static field.

So my question is : Could something like that be done, maybe in the future ? Or there is something really importnat that I don't see, I don't understand and It's definitly not possible ?
I just want to say that I achieve doing what I want doing it using Reflection/Dynamics but what could be the best way to write something clean and strictly typed please ?

Thanks for reading me,
Regards

**Comment by RealyUniqueName** [comment]
This works
```haxe
typedef TEditable = {
    editable : Bool
}

interface IEditable{}

class A implements IEditable{
    public static var editable : Bool = true;

    public function new(){}
}

class B implements IEditable {
    public function new(){}
}

class Main {
    static function main() {
        var a = new A();
        var b = new B();
        foo(A, a); // Ok!
        foo(B, b); // Error: Class<B> has no field editable
        foo(B, a); // Error: Class<B> has no field editable
        foo(A, b); // Error: Class<A> should be Class<B>
    }

    static function foo<I, T:Class<I> & TEditable>(cls:T, o:I){
        trace( cls.editable );
    }
}
```

**Comment by filt3rek** [comment]
Hej Aleksandr,

Thanks for your answer !
Yes it works fine.

But as said I have to pass the class as argument.
Is there a way to do the same, without passing the class as argument and just get the class from the instance ? As in the first sample upper.
That's why I write about `Type.getClass<T>`

**Comment by RealyUniqueName** [comment]
I don't think it's possible without passing a class directly.

@simn should this work?
```haxe
typedef TEditable = {
    editable : Bool
}

interface IEditable{}

class A implements IEditable{
    public static var editable:Bool;
}

class Main {
    static function main() {
        foo((null:A)); // Currently errors: Constraint check failure for foo.T
    }

    static function foo<I, T:Class<I> & TEditable>(o:I){}
}
```

**Comment by filt3rek** [comment]
Yes I know it's not possible without passing the class, that's why I ask maybe we could have something more strict, more verbose than `Class<T>` ? Something that could maybe be implemented in the future ?
That's pitty not having something like that.

**Comment by Ilir-Liburn** [comment]
Make it simple

```haxe
typedef TEditable = {
    editable : Bool
}

interface IEditable {
    function getEditable():TEditable;
}

class A implements IEditable {
    public static var editable : Bool = true;

    public function getEditable():TEditable return cast A;
    public function new(){}
}

class B {
    public function new(){}
}

class Editable {
    public static function main() {
        var a = new A();
        var b = new B();
        foo(a); // Ok!
//        foo(b); // Error: B should be IEditable
    }

    static function foo<I:IEditable>(o:I) {
        var cls:TEditable = o.getEditable();
        trace( cls.editable );
    }
}
```

**Comment by filt3rek** [comment]
Hej @Ilir-Liburn !
Thanks for your answer.
Yes it's simple as you say but It doesn't fit my need, it doesn't answer my question.
I don't want to have this field on every instances but only on the class, as static. Because it's not an instance information but a global static one.
On instances, it can be easier than your answer. I get my instance and I access the instance field, that's all. And compiler does the type checks on instances as usual.
Here I especially speak about having this kind of type check from the compiler on statics as it does with instances fields.

**Comment by filt3rek** [comment]
I know I could also use macros, something like that for constrain, to get a guard : 
Test.hx : 
```haxe
typedef TEditable = {
  editable : Bool
}

@:autoBuild( Macro.constrainStatic( editable ) )
interface IEditable{}
    
class A implements IEditable{
  @:keep
   public static var editable = true;
   public function new(){}
}

class B implements IEditable{
    public function new(){}
}

class Test {
    static function main() {
        var a = new A();
        var b = new B();
        foo( a );
    }
    
    static function foo( o : IEditable ){
      var cl : TEditable = cast Type.getClass( o );
      trace( cl.editable );
    }
}
```
Macro.hx :
```haxe
import haxe.macro.Context;
import haxe.macro.Expr;
class Macro {
  public static function constrainStatic( e : Expr ){
    var fields	= Context.getBuildFields();
   var clName	= Context.getLocalClass().toString();
    
    var has	= false;
    var fieldName	= switch e.expr {
      case EConst( CIdent(s)) : s;
      default : null;
    };
    for (field in fields){
      if( field.name == fieldName && field.access.indexOf(AStatic) != -1 ){
        has = true;
        break;
      }
    }
    if( !has ){
      Context.fatalError( clName + ' doesn\'t have static field $fieldName', Context.currentPos() );
    }
    return fields;
  }
}
```
But could there be this kind of feature on compiler, by native please ? Maybe in the future ?
I don't want to annoy anybody, just asking,
Thanks again for reading me,

**Comment by RealyUniqueName** [comment]
I think static interfaces were discussed and rejected somewhere in issues. Can't find it now.
You can submit a proposal to [Haxe-Evolution](https://github.com/HaxeFoundation/haxe-evolution/)

**Comment by filt3rek** [comment]
Thx Aleksandr,
Sorry, I didn't knew there was an Haxe-Evolution thing, I should write it over there yes.
But since it was yet ejected, I don't know if my little person would change anything ^^
And maybe it's heavily linked with static interfaces, I don't now but I maybe don't need a big thing like this, only having a type guard for a Class static fields, but once again, maybe it's over my understanding.

**Comment by kLabz** [comment]
"**only** having a type guard for a Class static fields" can't be a thing, as said on discord this wouldn't work for example: http://try-haxe.mrcdk.com/#23bB4 It could be possible, but you would need more than that.

Either static fields in interface where every subclass has to implement those, or static field inheritance, or something else I haven't thought about would be needed too.

**Comment by filt3rek** [comment]
@kLabz ,

Thx for your answer but as said on discord too, I think we misunderstood each other, that is not what I need, I probably don't explain correctly, and I don't purpose a concrete thing like you suggested many times and which never fit what I was talking about.

Thanks others for your understanding,
Regards,

**Comment by RealyUniqueName** [comment]
I'm closing this as it doesn't look like we have to do something here.
Feel free to reopen if needed.

**Comment by filt3rek** [comment]
Sorry guys to come back, I've just a last question if you could answer me.
When I pass a Class<T> as a function's argument, then in my body function, if I want to target a field of this class, how can I do that in a clean way ? Let's say I still want target "editables" field of this class, should I use untyped ? Reflection ?, should I cast the class as { editables : Bool } ?
Thanks for your answer,
Michal

**Comment by RealyUniqueName** [comment]
AFAIR `Reflect.field(cls, 'editable'`)` should work for all targets.

**Comment by filt3rek** [comment]
Thanks Aleksandr,

I won't rewrite about all what was yet said, I try at most avoid Dynamic and Reflection as Haxe suggest, but if it's the only way so ok.

Thanks again

**Comment by filt3rek** [comment]
Aleksandr,

Sorry I've another case more important that illustrates my question about how to do it clean :
```haxe
public static function fillRelations<T:Object>( cl : Class<T> ){
	var _cl	: { _editablesArrayInfos : Iterable<TEditable>, _editablesMapInfos : Iterable<TEditable> } = cast cl;
	for( editables in [ _cl._editablesArrayInfos, _cl._editablesMapInfos ] ){
```
Is it the right way, the cleanest one to access static fields of a Class<T> please ?

Thanks

**Comment by RealyUniqueName** [comment]
Yeah, probably. Can't think of a better way.
But be careful to keep those static fields from dce. If you don't use them directly, they will be removed with compilation flag `-dce full`.
