### ISSUE TITLE
Sumulate user keyboard input during -cmd command

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxe#8824]
I have `resolve-libs.hxml` file with content:
```
-cmd haxelib install openfl
-cmd haxelib run openfl setup
-cmd haxelib git spine-hx https://github.com/jeremyfa/spine-hx.git 3.7
-cmd haxelib git feathersui https://github.com/BowlerHatLLC/feathersui-openfl.git y
-cmd haxelib git update
-cmd haxelib install actuate
-cmd haxelib install openfl-spine
-cmd haxelib install spritesheet
-cmd haxelib install openfl-texturepacker
-cmd haxelib install as3hx
-cmd haxelib install hexinject 1.0.0-alpha.7
-cmd haxelib install hxp
```
if I run `haxe resolve-libs.hxml`, if freezes on command
`-cmd haxelib git spine-hx https://github.com/jeremyfa/spine-hx.git 3.7`
Because this lib is already installed, and if I run it manually, it waits for user keyboard input:
```
You already have spine-hx version git installed.
Overwrite branch: <unspecified> with "3.7" [y/n/a] ?
```
Is it possible to pass option via -cmd command?

**Comment by CrazyFlasher** [comment]
Ok I found parameters `--always` and `--never`.
But what to do in this case?
```
C:\Users\CrazyFlasher\Documents\work\git\projects\haxeslot>haxelib git update
Git path :
```
I mean, when I need some custom input?

**Comment by RealyUniqueName** [comment]
```
haxelib git update
```
Do you have a library called "update"? If yes - just provide a git link in hxml file just like you have for `spine-hx` and `feathersui`. If no - what do you expect `haxelib git update` to do?

**Comment by CrazyFlasher** [comment]
Ok, bad example with `haxelib git update`.
For example I call something like:
```
mycoolapp -dosmth
Please, enter some shit:
```
Is it possible to pass custom keyboard input?

**Comment by kLabz** [comment]
Not what you're asking for, but it could help you simplify this a little:

You can do `haxelib install --always install.hxml` with install.hxml being:
```hxml
-lib openfl
-lib spine-hx:git:https://github.com/jeremyfa/spine-hx.git#3.7
-lib feathersui:git:https://github.com/BowlerHatLLC/feathersui-openfl.git
-lib actuate
-lib openfl-spine
-lib spritesheet
-lib openfl-texturepacker
-lib as3hx
-lib hexinject:1.0.0-alpha.7
-lib hxp
```

And you'd end up with:
```
$ haxelib list
actuate: [1.8.9]
as3hx: [1.0.6]
feathersui: [git]
hexannotation: [1.0.0-alpha.7]
hexcore: [1.0.0-alpha.7]
hexinject: [1.0.0-alpha.7]
hexlog: [1.0.0-alpha.7]
hexreflection: [1.0.0-alpha.7]
hxp: [1.1.3]
openfl-spine: [1.4.7]
openfl-texturepacker: [1.0.0]
openfl: [8.9.5]
spine-hx: [git]
spritesheet: [1.2.0]
tink_core: [1.24.0]
tink_macro: [0.16.4]
```

You'd still have to run `haxelib run openfl setup` separately, and this wouldn't help with your keyboard input issue.

**Comment by haxiomic** [comment]
> ```
> mycoolapp -dosmth
> Please, enter some shit:
> ```
> 
> Is it possible to pass custom keyboard input?

`-cmd` in haxe executes on the system's shell so how you do this depends on your system and not something haxe controls (it'll be different between windows and mac)

For bash there seems to be some techniques using the `expect` command:
https://askubuntu.com/a/338870
Your example would be something like this:
```bash
spawn mycoolapp -dosmth
expect "Please, enter some shit:"
send "something"
```

For the original question, @kLabz suggestion is the way to go for installing the required libs

Another trick you might find handy is to create a folder named `.haxelib/` in the same place as your hxml files. Now when you install libs they will all be installed locally into that folder (just like a local `node_modules` folder)
