### ISSUE TITLE
Non-extern enum abstracts with run-time values

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8828]
While working on the libuv integration, I realized that we have a bit of a special situation with regards to enum abstracts. Take this file for example: https://github.com/Aurel300/haxe/blob/feature/eval-libuv/std/asys/FileOpenFlags.hx

For all intents and purposes, this can act as an enum abstract. The only issue is that we don't actually know the precise values because they depend on the run-time environment (in this case which platform we're running on).

We already support `extern enum abstract`, but that's not exactly what we want here because we have implementation on the abstract. What we're looking for is a non-extern enum abstract with extern concrete values.

My suggestion would be to allow `extern var Append;` with the following properties:

* no auto-numbering
* allowed as argument default value
* run-time initialization is responsible for assigning values to the implementation class

There might be places in the compiler which currently assume a constant value on non-extern enum abstract fields, so we'd have to check that when implementing this. Other than that, it should be quite straightforward.

Any thoughts?

**Comment by nadako** [comment]
If I understood you correctly, you can already have something like this with some `@:native` magic:

```haxe
class FlagsImpl {
	static var Append:Int;
}

@:native("FlagsImpl")
extern enum abstract Flags(Int) {
	var Append;
}
```

**Comment by Simn** [comment]
I can't make the abstract itself extern because then I can't put any implementations on it.

**Comment by nadako** [comment]
> I can't make the abstract itself extern because then I can't put any implementations on it.

Yes, you have to put the implementations in the `FlagsImpl` class.

**Comment by Simn** [comment]
But I can't put `@:from` and `@:op` there.

**Comment by ncannasse** [comment]
I would prefer a metadata than a keyword, as it's mostly for std library. I think it will be quite rare for users to be able to use it as an actual language feature.

**Comment by nadako** [comment]
> But I can't put `@:from` and `@:op` there.

You can have `@:from`:
```haxe
class FlagsImpl {
	static var Append:Int;

	static function fromString(s:String):Int {
		return Std.parseInt(s);
	}
}

@:native("FlagsImpl")
extern enum abstract Flags(Int) {
	var Append;

	@:from static function fromString(s:String):Flags;
}
```

but with the `@:op`, the underlying op exposing features comes in the way indeed...

**Comment by Simn** [comment]
> I would prefer a metadata than a keyword, as it's mostly for std library. I think it will be quite rare for users to be able to use it as an actual language feature.

`extern var` already parses anyway, it's just being ignored at the moment. It would also be really awkward to allow it (and deprecate `@:extern`) on class fields and do the opposite on abstract fields.

**Comment by nadako** [comment]
> but with the `@:op`, the underlying op exposing features comes in the way indeed...

that's fine for your specific case though :)

**Comment by Simn** [comment]
Right, and why implement this cleanly when we can just use massive hacks instead. I'll throw in some `untyped Error` for good measure. This entire "it's just for the standard library so hack something together" thinking really annoys me.

**Comment by nadako** [comment]
Yo I'm not arguing that we should not have a proper way for this, I'm just saying that it is possible if you need it right now.

**Comment by Simn** [comment]
Yeah sorry, I guess I'm building a strawman out of the combination of Nicolas' and your remarks.

I'll see if your approach works for my case.

**Comment by Simn** [comment]
> allowed as argument default value

I'll still make this change because that's good regardless.

**Comment by Simn** [comment]
Well, nadako enums work fine for my case so I no longer care about making this a feature. I find it quite strange that we just ignore an `extern` modifier, so I guess we should at least give an error on that.
