### ISSUE TITLE
toUpperCase()/toLowerCase() fails for Cyrillic strings. Also their length is doubled and charAt() returns undesired values

### ISSUE THREAD

**Issue by www0z0k** [HaxeFoundation/haxe#8833]
```
trace('ASD'.toLowerCase()); //outputs asd
trace('qwe'.toUpperCase()); //outputs QWE
trace('ФЫА'.toLowerCase()); //outputs ФЫА
trace('йцу'.toUpperCase()); //outputs йцу
trace('йцу'.length);	//outputs 6
trace('йцу'.charAt(0));	//outputs ?
```

Seems like they have more bytes than `String` can understand :)

Is there a workaround for this?
For now I just prepare my string assets in a very special way.

**Comment by Aurel300** [comment]
This is not a completely trivial issue, most of our targets simply don't have the Unicode maps for lowercase/uppercase integrated yet. It should be quite easy to add into e.g. Javascript though.

As for the length and charAt stuff, which target are you using? Is it Neko by any chance?

**Comment by RblSb** [comment]
I think all targets already support `toLowerCase/toUpperCase` except neko:
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unitstd/Unicode.unit.hx#L176

**Comment by www0z0k** [comment]
I am using neko for testing
However the length/charAt problem is also present on ios and android (haven't tested case changing yet)

**Comment by www0z0k** [comment]
here is the mac output
```
		trace('ASD'.toLowerCase()); //outputs asd
		trace('qwe'.toUpperCase()); //outputs QWE
		trace('ФЫА'.toLowerCase()); //outputs ФЫА
		trace('йцу'.toUpperCase()); //outputs йцу
		trace('йцу'.length);		//outputs 6
		trace('йцу'.charAt(0));		//outputs null
```

**Comment by RealyUniqueName** [comment]
Which Haxe version do you use?

**Comment by www0z0k** [comment]
> Which Haxe version do you use?

3.4.7
and `openfl -version` outputs `8.9.4-LohrnK`

**Comment by www0z0k** [comment]
ios ouput
```
		trace('ASD'.toLowerCase()); //outputs asd
		trace('qwe'.toUpperCase()); //outputs QWE
		trace('ФЫА'.toLowerCase()); //outputs ФЫА
		trace('йцу'.toUpperCase()); //outputs йцу
		trace('йцу'.length);		//outputs 6
		trace('йцу'.charAt(0));		//outputs pow
```

**Comment by sebthom** [comment]
@www0z0k depending on how fast you need a solution, you can try to use the toLowerCase8/toUpperCase8 methods of the [hx.strings.Strings](https://github.com/vegardit/haxe-strings/blob/master/src/hx/strings/Strings.hx) in the meantime.

**Comment by www0z0k** [comment]
@sebthom I created my own StringWrapper for char-by-char manipulations
And I prepare strings with an external js script, so I don't need it so fast ;-)

**Comment by RealyUniqueName** [comment]
> > Which Haxe version do you use?
> 
> 3.4.7
> and `openfl -version` outputs `8.9.4-LohrnK`

Strings in Haxe 3.4.7 are not unicode-aware. You need to look for third-party library like https://lib.haxe.org/p/unifill/
Since Haxe 4.0 strings support unicode by default.
