### ISSUE TITLE
Cyrillic text issue after updating to haxe 4.0.0-rc.5 (in openfl TextField)

### ISSUE THREAD

**Issue by www0z0k** [HaxeFoundation/haxe#8835]
After upgrading haxe I get correct traces of Cyrillic strings’ lengths and values, but the TextField itself looks like:
![Screenshot 2019-09-21 at 20 21 43](https://user-images.githubusercontent.com/951595/65377013-93e29b80-dcaf-11e9-83aa-d3f87eb494c7.png)
However the tracing the `textField.text` gives a correct result in the console.

This is on mac/ios targets. `toUpperCase()` and `length` work as expected for Cyrillic strings.

On neko target `toUpperCase()` and `length` don't work correctly, but the text is displayed ok.

Should I downgrade back to 3.4.7 version or there might be another way around?

**Comment by ncannasse** [comment]
Please report to OpenFL directly as it's not an Haxe compiler issue. You might need to upgrade openfl as well so it's compatible with Haxe 4.0

**Comment by www0z0k** [comment]
reported
I am using the last openfl version
