### ISSUE TITLE
[php] php-prefix not persisted in docblock types

### ISSUE THREAD

**Issue by benmerckx** [HaxeFoundation/haxe#8836]
Haxe's std types are namespaced correctly with `-D php-prefix` but the namespace does not show up in the generated docblock comment types.
For example `-D php-prefix=Test` currently generates docs with properties/return types like these:
`@var Array_hx`
where ideally it would generate:
`@var \Test\Array_hx`

**Comment by RealyUniqueName** [comment]
Just checked. It works just fine.
It generates a `use` statement.
E.g this (with `-D php-prefix=test`)
```haxe
class Main {
    static public function test(a:pack.Test) {}
}
```
becomes
```php
use \test\pack\Test;

class Main {
    /**
     * @param Test $a
     *
     * @return void
     */
    static public function test ($a) {
    }
}
```
`use` statement for `Array` is not generated because it is located in the same or upper package which following PHP interpreter's rules doesn't require `use` to be discovered.
