### ISSUE TITLE
[cs] [bug] Incorrect autocast on unary minus : Float to Int (double to int in cs)

### ISSUE THREAD

**Issue by dyarosla** [HaxeFoundation/haxe#8837]
Repro case: 

```haxe
var arr = [ { f : 1.5 } ];
var a = arr[0];
trace(-a.f); // traces -1, not -1.5
```

Above, the cs code autocasts a.f (1.5) to an int (1) and then negates (-1).

Note, this is not an error with casting and toString. Another repro case:

```haxe
function timesTwo(a:Float):Float {
    return a*2.0;
}
var arr = [ { f : 1.5 } ];
var a = arr[0];
var b = timesTwo(-a.f);
trace(b); // traces -2, not -3
```

Bug has to do with the cs code generated for a unary minus on an object field doing an auto cast to (int).

The repro cases require the array/object access instead of the simpler

```haxe
var a = { f : 1.5 };
trace(-a.f); // correctly traces -1.5
```

The above code only works because the cs code generated does not actually create a field to access for a.f but optimizes the code and creates a variable a_f instead.

**Comment by RealyUniqueName** [comment]
I set this to 4.0 milestone because being unable to do basic math seems pretty bad to me. But there is a big chance it will require to change cast handling too deep to be regression-safe and will be moved to 4.1.

**Comment by Simn** [comment]
No way we're touching this for 4.0.

**Comment by ncannasse** [comment]
I propose we could try to look at fixing this in development, and eventually merge the fix in 4.0 branch if we are really sure it only affects this specific case (highly unlikely)

**Comment by RealyUniqueName** [comment]
I cannot reproduce this.
@dyarosla Could you please provide a complete sample and compilation arguments?

**Comment by RealyUniqueName** [comment]
It's reproducible with 3.4.7.
Did you try latest Haxe 4.0.0-rc.5?

**Comment by dyarosla** [comment]
@RealyUniqueName You're right. I was running into it in 3.4.7.

Just tried with latest Haxe 4.0.0-rc.5 and can't reproduce.
