### ISSUE TITLE
Invalid position in member macro method

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8838]
```haxe
console = new h2d.Console(null);
console.add("test", function() {
   trace("Hello world");
});
```

The `console.add` method is a macro member method, that does inspect the arguments of the callback function to generate a `console.addCommand` call.

However it seems all the positions of the callback function argument are set to the macro call instead of being kept as part of the original source code when compiled.

As a result, it's not possible to put breakpoints or debug the callback functions (in HL target for example).

**Comment by RealyUniqueName** [comment]
```haxe
class Main {
    public static function main() {
        var console = new h2d.Console(null);
        console.add('test', function() { // line 4
            trace('hello');		 // line 5
        });
    }
}
```
Generated js:
```js
Main.main = function() {
	new h2d_Console(null).addCommand("test",null,[],function() {
		haxe_Log.trace("hello",{ fileName : "src/Main.hx", lineNumber : 5, className : "Main", methodName : "main"});
	});
};
```
As you can see `trace` receives correct position. 
Could you assemble a complete sample?

**Comment by ncannasse** [comment]
Yes, the trace is correct and if you have some error in the callback it will be displayed correctly. But for some other reason, the position is indeed set to the macro call position (at generation time). You can check that by compiling to HL with `-D dump` and look at `dump/hlcode.txt` for line numbers

**Comment by RealyUniqueName** [comment]
Positions on the typed syntax tree are still correct right before passing it to generators:
```haxe
import haxe.macro.Context;

class Macro {
#if macro
  static public function init() {
    Context.onGenerate(types -> {
      for(type in types) {
        switch type {
          case TInst(t, params) if(t.toString() == 'Main'):
            var main = t.get();
            switch main.statics.get()[0].expr().expr {
              case TFunction({ expr: { expr: TBlock([e])} }):
                switch e.expr {
                  case TCall(_, [_, _, _, e]):
                    switch e.expr {
                      case TFunction({ expr: { expr: TBlock([e])} }):
                        trace(e.pos);
                      case _:
                    }
                  case _:
                }
              case _:
            }
          case _:
        }
      }
    });
  }
#end
}
```
```
$ haxe -main Main -hl test.hl -lib heaps -D analyzer-optimize --macro "Macro.init()"
Macro.hx:17: #pos(Main.hx:5: characters 4-9)
```
It's definitely something wrong is happening in genhl.

**Comment by ncannasse** [comment]
Seems like it works now.
