### ISSUE TITLE
Please implement or remove @:const for abstracts

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#8843]
```haxe
typedef Statics = { first : Bool };

class A { public static var first : Bool = true; public function new(){} }
class B { public static var first : Bool = true; public function new(){} }

abstract Abstraction<T>(T) {
    public function new(v:T) { this = cast v; }
@:generic
    @:to public static function to<@:const T>(t:T):Statics return cast T;
}
```

Constant parameters are currently allowed for abstracts, but above example doesn't generate @:to function, leading to runtime failure.

```haxe
@:directlyUsed @:used
private class _Test.Abstraction_Impl_ {

	@:impl @:noCompletion
	public static function _new(v:Abstraction.T) {
		var this1;
		this1 = cast v;
		return cast this1;
	}
}
```

Making @:to inline improves situation, but again it fails because T can not be found, even if whole abstract is generic. Or to better say, to.T is not replaced by type A in this case.
```haxe
		var a = new A();
		var aa = _Test.Abstraction_Impl_._new(a);
		Test.stat(@:implicitCast cast to.T);
```

Thus, my attempt to replace toA and toB specializations by single @:to returning constant type has failed. Please implement @:const for abstracts so that it is working, or remove it by design choice

https://github.com/HaxeFoundation/haxe/issues/7574

BTW, if @:const remains, it would be nice to have something like this

```haxe
@:generic
abstract Abstraction<@:const T>(T) {
    public function new(v:T) { this = cast v; }
    @:to public inline function to():Statics return cast T;
}
```

so that @:to doesn't have to be generic once again and T not redefined as a constant again (for non-static @:to)

**Comment by Simn** [comment]
As usual I can't tell what you're actually trying to do here, but if you want more errors we can certainly provide that.

**Comment by Simn** [comment]
Actually, this is just a really obscure variant of #7574.

**Comment by Ilir-Liburn** [comment]
It is simple, I don't want toA and toB specializations returning A and B, but single to function returning constant type which is either A or B depending on the type of the parameter.

**Comment by Simn** [comment]
If you're asking for dependent types then no, we have no plans to add that.

**Comment by Ilir-Liburn** [comment]
What I'm asking is along this lines

```haxe
class MyClass<T> {
    public var type:Dynamic;

    @:generic public function new<@:const T>(type:T) {
        this.type = Std.is(T, A) ? A : B;
    }
}
        var a = new A();
        var c = new MyClass(a);
        trace(c.type);
```

which generates (CS)

```cs
__hx_this.type = ( (( T is global::A )) ? (((global::System.Type) (typeof(global::A)) )) : (((global::System.Type) (typeof(global::B)) )) );

```

What I want to have is a T which is a constant itself (A or B in above example), so that T is replaced by A or B depending on the parameter type

```haxe
class MyClass<T> {
    public var type:Dynamic;

    @:generic public function new<@:const T>(type:T) {
        this.type = T;
    }
}
```

because all the above can be compiled, but it is failing at runtime.

**Comment by kLabz** [comment]
I don't really see how it's a variant of #7574 
This issue was reported again on discord, with this:

```haxe

class SuperComponent {
	public function new() {}

	public function helloWorld() {
		trace('Hello from SuperComponent');
	}
}

@:forward
abstract Entity(EntityImpl) {
	public function new() {
		this = new EntityImpl();
	}

	@:to @:generic public function toComponentType<@:const T>():T {
		for (comp in this.components) {
			if (Std.is(comp, T)) {
				return cast comp;
			}
		}
		return null;
	}
}

class EntityImpl {
	public var components:Array<Any> = [];

	public function new() {}
}

class Test {
	static function main() {
		var e = new Entity();
		e.components = [new SuperComponent()];

		// Compiles fine but at runtime Entity.toComponentType doesn't exist
		// var sc: SuperComponent = e;

		// File "src/typing/calls.ml", line 369, characters 89-95: Assertion failed
		var sc:SuperComponent = e.toComponentType();

		sc.helloWorld();

	}
}
```

Edit:
The difference here is that it's a `@:to` function so first argument is `this` and it generates an assertion error in `type_generic_function`. But if this assertion error is dodged then the `Only Const type parameters can be used as value` error is generated.

**Comment by Ilir-Liburn** [comment]
If toComponentType is hard-coded, we get

```haxe
    @:to @:generic public function toComponentType<T>():T {
        for (comp in this.components) {
			if (Std.is(comp, SuperComponent)) {
				return cast comp;
			}
        }
        return null;
    }

    Field index for toComponentType not found on prototype _Test.Entity_Impl_
```

In general, first problem is that @:const T parameter is holding a value of null in previous example. Second problem is that users are expecting to use Std.is as usual, but actually @:const T can hold only a ValueType, therefore Type.typeof should be used instead.

EDIT: Field index not found error is actually reproducible after adding following function to Entity

 ```haxe
    public static macro function getComponentType<T>(e) { return macro null; }
```
