### ISSUE TITLE
[python] Wrong result of modulo by negative numbers

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8845]
```haxe
class Main {
    @:analyzer(ignore)
    public static function main() {
        trace(255 % (-8));
    }
}
```
Python gives `-1`, other targets - `7`

**Comment by Aurel300** [comment]
Is this really a "bug"? Also for this one, the manual does say:

> In Haxe, the result of a modulo operation always keeps the sign of the dividend (the left operand) if the divisor is non-negative. The result is target-specific with a negative divisor.

**Comment by RealyUniqueName** [comment]
It's only python does not comply. I'll fix it.
Genpy already uses custom `%` implementation instead of a "native" one, so it won't be a big performance hit.
