### ISSUE TITLE
Optimize for lua versions (where possible)

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#8852]
There are a few opportunities for optimizing lua code based on certain version/feature availability using the `lua_ver` flag. This would optimize speed/performance at the cost of compatibility.  So far this includes bitwise operations as discussed in https://github.com/HaxeFoundation/haxe/pull/8850.

**Comment by Simn** [comment]
Unfortunately, this is unlikely to happen anytime soon.
