### ISSUE TITLE
Array clone bug.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8855]
var a1=[{a:1,b:1}];

    var b1=a1.copy();

    b1[0].a=0;
    b1[0].b=0;

    trace(a1);//[ { a: 0, b: 0 } ] ?why not [{a:1,b:1}];

**Comment by Simn** [comment]
Because it's a shallow copy, which is the standard implementation.

**Comment by nanjizal** [comment]
sonygod - There are some deep clone libraries around which you can utilise, quick google found this recent one. 
https://github.com/thomasuster/cloner
I think you could simply make your own version using an abstract wrapper that recurses an @from with a type switch statement and some further abstract wrappers and some for loops, an approach I think I have used for some slightly deep structures, but probably some limitations.
