### ISSUE TITLE
Adobe AIR3 library incompatible with Haxe 4 RC3+

### ISSUE THREAD

**Issue by SmerkyG** [HaxeFoundation/haxe#8857]
Various changes have made the air3 haxelib library (and therefore AIR) no longer compatible as of Haxe 4 RC3+. It was working as of RC2. One such issue is the disallowance of fakeEnum. But even once I replaced all of those, there are problems where Haxe is now looking for get/set functions that don't exist in externs. (I imagine those shouldn't be required for externs in at least some cases?) Example flash.filesystem.FileStream:

Field endian has different property access than in flash.utils.IDataOutput (var should be (get,set))
Field get_endian needed by flash.utils.IDataOutput is missing
etc.

**Comment by nadako** [comment]
Hi, yes we should document this better, but the Flash property support was reworked in #8241. You now have to specify a proper Haxe property and its accessor functions in the extern class as well as mark it with the `@:flash.property` metadata.

Check out this one for a quick example: https://github.com/HaxeFoundation/haxe/blob/development/std/flash/accessibility/ISimpleTextSelection.hx

On the bright side overriding native Flash properties in Haxe is much easier now!

PS Can we generate AIR externs from an SWC file similar to how we do it for the basic Flash API?

**Comment by SmerkyG** [comment]
Neat change in #8241. Yeah, if the AIR externs could get auto-regenerated that would be ideal!

**Comment by RealyUniqueName** [comment]
Documented here: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0#native-properties-for-flash-target

**Comment by nanjizal** [comment]
SmerkyG are you able to get AIR3 working again do you need some help from Haxe community?

Is AIR still relevant? Can Harman be contacted to help provide some support of AIR target?
https://services.harman.com/partners/adobe

Is SmerkyG interested to take over ownership of AIR3, Jan left Haxe several years ago, I think the current repo is not suitable anymore:
https://code.google.com/archive/p/haxeair3/
Andy could be contacted if AIR3 needed transition of ownership on haxelib - that seems a tricky subject?

Is it better that Haxe blog tries to cover something on transitioning to AIR or is Haxe not yet able to fully cover all the AIR use cases from the current developers, certainly stage3d users are not fully aware if AIR can be replaced by say OpenFL.
https://www.facebook.com/groups/stage3d/

I really don't feel this issue can be closed without more follow up, if Java target stopped working you would not just close an issue saying the haxelib needs updating it's documented!

**Comment by RealyUniqueName** [comment]
I don't think we have anything to do regarding AIR3 in the compiler. And this is the compiler repo :)
As for the compiler the issue was about the changes to native flash properties. That was addressed.

**Comment by SmerkyG** [comment]
@RealyUniqueName the compiler change made to improve the Flash target is what caused the problem for the AIR target. I think it's reasonable to say that AIR is now a significantly more important target than Flash now, not less. It's still being supported, and it allows people to easily migrate their flash projects to something actually usable in the future. Not to mention that it's a great ecosystem for outputting cross platform compatible desktop apps. As @nanjizal points out, it's more that a bit odd to break an entire target (especially in order to improve a LESS important target whose manufacturer is discontinuing support) and just say it has been addressed by noting that it's a breaking change!

I'll repeat @nadako 's good question, since I don't know the answer: "can we generate AIR externs from an SWC file similar to how we do it for the basic Flash API?" I don't know how that's done, but presumably it would be really easy and would allow AIR support to continue to work.

That or else the air3 lib would need to be manually fixed up for the new regime, which is certainly possible but sounds rather annoying to do by hand.

**Comment by RealyUniqueName** [comment]
AIR is not a target for the Haxe compiler. SWF bytecode is a target. The target is not broken, it's AIR externs need to be updated. And to address that an issue should be created in a relevant repo (which is not this repo as AIR externs are not part of this repo).

I agree AIR3 is useful, but it's a separate 3rd-party library and its issues should be discussed in a relevant place (not here) unless it's something in the Haxe compiler prevents AIR3 to be updated.

**Comment by nadako** [comment]
We certainly can generate externs from an SWF, and I might even have to work on this in future, but I don't have time to work on this right now, unfortunately.
