### ISSUE TITLE
Missing fields errors on js target

### ISSUE THREAD

**Issue by ConfidantCommunications** [HaxeFoundation/haxe#8858]
4.0.0-rc.5+4a745347f

I am experiencing the following errors:
Class<js.html.Window> has no field location
Class<js.html.HTMLDocument> has no field location
Class<js.html.Document> has no field location
Class<js.html.Location> has no field reload

All of these seem to contradict the documentation and what I can discern viewing the source code for this version. Sorry if I'm missing something.

Simply trying to reload a page like so:
js.html.Window.location.reload(true);

**Comment by terurou** [comment]
Please see `js.Browser.location` or `js.Browser.window.location`.

https://api.haxe.org/v/development/js/Browser.html

**Comment by kLabz** [comment]
> Class<js.html.Window> has no field location

> All of these seem to contradict the documentation

But it doesn't. These are instance fields, not class fields (statics). Use `js.Browser.window` to get a `Window` instance.
