### ISSUE TITLE
PHP EReg and unicode

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8861]
Is `EReg` supposed to fully work with utf-8 strings in PHP? I have a problem here using a (quite complicated) `map` function.
In the code I see that the `/u` option is always added by default:
https://github.com/HaxeFoundation/haxe/blob/97d365b7f9dca506e8d6b61616148778186a44e7/std/php/_std/EReg.hx#L176-L178
And then there's a fallback to non-unicode, when there's an error:
https://github.com/HaxeFoundation/haxe/blob/97d365b7f9dca506e8d6b61616148778186a44e7/std/php/_std/EReg.hx#L109-L113
I have added `u` in my regex as well, so the fallback would be still unicode, I guess...
Removing `u` in my regex gets me an endless loop.

Then there are some commented utf-8 errors:
https://github.com/HaxeFoundation/haxe/blob/97d365b7f9dca506e8d6b61616148778186a44e7/std/php/_std/EReg.hx#L68-L72
When I uncomment these, I get the offset error.

Also in some places php `mb_*`-functions are used and in some not:
https://github.com/HaxeFoundation/haxe/blob/97d365b7f9dca506e8d6b61616148778186a44e7/std/php/_std/EReg.hx#L102-L103
https://github.com/HaxeFoundation/haxe/blob/97d365b7f9dca506e8d6b61616148778186a44e7/std/php/_std/EReg.hx#L96-L97

**Comment by mockey** [comment]
Hm, it seems the `offset` parameter of `preg_match` is expected in bytes and also the offset that is returned with `PREG_OFFSET_CAPTURE` is in bytes, see:
https://www.php.net/manual/en/function.preg-match.php

Probably that's why non-mb functions are used when dealing with `matches` (see above). Still, in `map` the values from `matchedPos` are passed to `matchSub`/`preg_match`. That doesn't work. I was able to fix the map function by adding a second (byte) offset to it. Not sure if this is the best way...

**Comment by RealyUniqueName** [comment]
Could you please provide a sample?

**Comment by mockey** [comment]
Something like this:
```haxe
~/foo/g.map("foo – foo", (rgx) -> "bar");
```
leads to an endless loop (any multi-byte char between replacements should do).
If you uncomment `PREG_BAD_UTF8_OFFSET_ERROR` you should get an exception.
The problem is  `matchedPos` is calculating in chars but the `preg_match` call in `matchSub` expects bytes.I use a a second (bytes) offset in `map` now for `matchSub`. I can provide a PR but I'm not sure if that's the best solution...

**Comment by RealyUniqueName** [comment]
Which Haxe and PHP versions are you using?
With the latest dev Haxe and PHP 7.3.6 I cannot reproduce the issue.

**Comment by mockey** [comment]
I have latest dev Haxe also and PHP 7.3.4, but I doubt that that would make a difference.
Do you really have a multi-byte char between replacements, like "–" instead of "-"?
Maybe try a russian letter?
Did you run the php script on the command line?
Can you maybe uncomment the `PREG_BAD_UTF8_OFFSET_ERROR` exception?
Maybe try something more complicated:
```haxe
var str = ~/[äöü]/gu.map("väter, söhne, mütter", (rgx) -> switch rgx.matched(0) {
  case "ä" : "ae"; case "ö" : "oe";
  case "ü" : "ue"; case _ : "";
});
trace(str);
// should output: vaeter, soehne, muetter
// for me it outputs: vaeter, söhne, mütter and never finishes
```

**Comment by mockey** [comment]
:+1:  Seems to work now, thanks.
One more thing:
When `u` is added as an option the non-unicode fallback doesn't work. Maybe `u` should be removed from options like `g`?

**Comment by RealyUniqueName** [comment]
Done
