### ISSUE TITLE
js.lib.Float32Array has no js.lib.Float32 - RC5 breaks WebGL code.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#8864]
I am getting errors passing Floats into a Float32Array due to changes in Haxe4 RC5 but worked fine on previous Haxe4 and Haxe 3.4.7, most of my code is fairly invariant to Haxe version changes so I am guessing it will break lots of peoples code.

_The practical issue is that WebGL often requires Float32Array for shaders and it is very common to convert from Array<Float> every frame so it's impractical to have any conversion checks._

There does not seem to be a **Float32** for Javascript in the development build or did I miss that I checked the API online? - So it seems rather cruel to not allow implicit conversion on the JS target.  _( Kha has an approach from my understanding FastFloat - rather a confusing term for using Float32 on JS and Float64 on C++, Haxe does not supply any solution )._

So I am unhappy with this recent change, the error refers to 'Int' and the error message I feel is confusing as this relates to Floats, I understand there are some lower level links between Int's and Float's but that requires compiler understanding and so should be hidden from the user.

```
/usr/local/lib/haxeLibrary/geom/git/src/geom/Matrix4x3.hx:838: lines 838-841 : Could not find a suitable overload, reasons follow
/usr/local/lib/haxeLibrary/geom/git/src/geom/Matrix4x3.hx:838: lines 838-841 : Overload resolution failed for (array : Array<Int>, ?offset : Null<Int>) -> Void
/usr/local/lib/haxeLibrary/geom/git/src/geom/Matrix4x3.hx:838: lines 838-841 : Float should be Int
```

While I understand the aim to make Haxe more typesafe as a language, but the change in RC5 just breaks code and seems to require users to hack in some casts when using WebGL without providing a safe and efficient solution ( I am assuming Float64Array.from() may add overhead ).

Given that **Shaders** and **WebGL** are very important JS consideration I am flagging this change as it stands as **'un-pragmatic'** and **'un-userfriendly'**.

My context
[https://github.com/nanjizal/geom/blob/master/src/geom/Matrix4x3.hx#L836](https://github.com/nanjizal/geom/blob/master/src/geom/Matrix4x3.hx#L836)

I am also getting many errors for my bug, where ideally I should just get one or two.
[https://gist.github.com/nanjizal/f9cb4b1d1c865f426ce0639159860e16](https://gist.github.com/nanjizal/f9cb4b1d1c865f426ce0639159860e16)

**Comment by RealyUniqueName** [comment]
Could you please reduce it to a self-contained sample? That would speed up issue resolution a lot.

**Comment by RealyUniqueName** [comment]
Found it here: https://github.com/HaxeFoundation/haxe/pull/8464
That PR changed signature from `Array<Float>` to `Array<Int>` instead of adding an overload for `Array<Int>`. Fix incoming...
