### ISSUE TITLE
Compilation with unitialized fields order

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#8865]
Should not be allowed?
```haxe
class Sides {
	public static var ALL = LEFT | RIGHT;
	public static var LEFT = 1;
	public static var RIGHT = 2;
}
class Test {
    static function main() {
        trace(Sides.ALL); // js: 0 instead of 3
    }
}
```
http://try-haxe.mrcdk.com/#0d41e

**Comment by Simn** [comment]
I'm not sure I want to go there. I agree that it looks like a low-hanging fruit in this particular example, but static initialization order in general is tricky. Solving this for simple cases such as this might give a false sense of security when you extend the example to multiple classes with multiple statics, some of which maybe even mutually depending on each other.

**Comment by RblSb** [comment]
For accuracy, i don't requested initialization order checks, i thought that maybe:
```haxe
static var A = 0;
static var B = A;
```
Should be not allowed, but i don't know: does all Haxe targets will resolve static vars in right order (top to bottom)? If it is, probably there is nothing to do (and such restriction will break a lot of code).

**Comment by Simn** [comment]
Yes, statics are guaranteed to be initialized in order of their appearance. If that's not the case in some scenario, we're looking at a bug.

Let's not touch this.

**Comment by RealyUniqueName** [comment]
Can't we just emit an error/warning if static var init expression refers to other static fields of the same class?

**Comment by Simn** [comment]
No, that would be a nuisance and break everyone's code.
