### ISSUE TITLE
Return statements are allowed in variable assignment (`var x = return new X()`)

### ISSUE THREAD

**Issue by tbrosman** [HaxeFoundation/haxe#8866]
The following is legal code (Haxe 4 rc.5): `var x = return new X()`

This can lead to interesting bugs involving unreachable initialization code:

```haxe
package ;

import haxe.ds.StringMap;

class Main
{
    public static function buildMap():Dynamic
    {
        var mapAsDynamic:Dynamic = return new StringMap<Dynamic>();
        cast(mapAsDynamic, StringMap<Dynamic>).set("cat", { i: 0 });
        return mapAsDynamic;
    }
    
    public static function main():Void
    {
        var map:Map<String, Dynamic> = buildMap();
        trace(map["cat"].i);
    }
}
```

On first inspection this code looks like it builds a Map and then populates it. Instead, after the first return statement we break out of buildMap and return the empty Map instance. Then, in trace() we see a null ref exception.

I accidentally hit this when inlining a function that had a switch statement that looked like this:

```haxe
            switch (keyType)
            {
                case StringMapKey:
                    return new StringMap<Dynamic>();
                case IntMapKey:
                    return new IntMap<Dynamic>();
                default:
                    throw "Unsupported key";
            }
```

When writing the minimal repro, I realized that if I could return from anywhere in the switch statement, it was probably possible to write something weird like `var x = return new X()` and it would compile without issue as long as the return type of the function that contained it matched.

**Comment by Simn** [comment]
This is a language feature, and the rest is covered by #8670.
