### ISSUE TITLE
Constraint on constructible

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8869]
I was trying to to the following:

```haxe
public function toggleWindow<T:(haxe.Constraints.Constructible<Void->Void> & Window)>( cl : Class<T> ) {

}
```

However I get an error `Can only extend structures` from compiler, which is not very helpful. Both Window and Constructible works individually, I thought that constraints where independent.

**Comment by kLabz** [comment]
I think you still need `<T:(haxe.Constraints.Constructible<Void->Void>, Window)>` when combining constraints and not defining an intersection type.

**Comment by nadako** [comment]
The problem here is parenthesis. It works without them.

**Comment by RealyUniqueName** [comment]
So, the error should report parentheses.

**Comment by nadako** [comment]
Ideally it should work with parenthesis too :)

**Comment by nadako** [comment]
Until we have "proper" intersection types, I guess it's a matter of skipping the CTParent while processing constraints?

**Comment by RealyUniqueName** [comment]
> Ideally it should work with parenthesis too :)

But parens have no meaning here :)

**Comment by ncannasse** [comment]
If parents are allowed at syntax, they should be ignored. Especially since Haxe 3 syntax required them.

**Comment by Simn** [comment]
I accidentally removed the change here because I thought it was a leftover from Haxe 3. Reopening here because the special treatment of parentheses when parsing constraints looks wrong to me. It means that we cannot use function types as constraints unless we use redundant parentheses, which is really weird.
