### ISSUE TITLE
Invalid huffman exception when reading .png via format via heaps

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8875]
I don't have a small reproducible example yet, but something seems to be wrong in haxe.zip or format:

![Code_2019-10-14_11-16-23](https://user-images.githubusercontent.com/634365/66740696-1c4df980-ee74-11e9-83b5-ed5749d6c916.png)

I'm using this via a heaps texture, but I doubt that matters. The .png I'm trying to load works fine in other programs.

**Comment by Simn** [comment]
The problem is in `HuffTools.make`:

```haxe
return treeCompress(NeedBit(treeMake(bits, maxbits, 0, 1), treeMake(bits, maxbits, 1, 1)));
```

This assumes that there is more than 1 entry, but in my case `nlengths` is `1`, which means that there is no right-part of the tree. The call to `treeMake(bits, maxbits, 1, 1)` then recurses indefinitely (well, until the `maxbits` check fails) because `bits` has no corresponding entry, which means the exit condition is never fulfilled.

I can fix this by replacing the code with this:

```haxe
var left = treeMake(bits, maxbits, 0, 1);
var right = nlengths > 1 ? treeMake(bits, maxbits, 1, 1) : Found(0);
return treeCompress(NeedBit(left, right));
```

However, I have no idea what I'm doing and using `Found(0)` seems very random.

@ncannasse: Any advice?

**Comment by Aurel300** [comment]
`nlengths` passed to `Huffman.make` is 1? Meaning there is only one symbol? That might be a special case for the `make` function, it could just return `NeedBit(Found(0), Found(0))` immediately. Then `InflateImpl.applyHuffman` consumes at least one bit for the symbol.

**Comment by Simn** [comment]
Right, I suppose we don't have to recurse at all in that case.

**Comment by ncannasse** [comment]
BTW that's a very slow way to read PNGs ;)

**Comment by Simn** [comment]
Well, it's what heaps does. When targeting JS anyway.
