### ISSUE TITLE
@:structInit vs getter

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8876]
```haxe
class Main {
  public static function main():Void {
    var foo:Person = {fullName: "John Smith"};
    trace(foo.firstName);
  }
}

@:structInit
class Person {
  public var fullName:String;
  public var firstName(get, never):String;
  function get_firstName():String return fullName.split(" ")[0];
}
```

Fails with `Object requires field firstName`. I think `structInit` should only cover physical variables.

**Comment by RealyUniqueName** [comment]
I agree vars with `never` write access should be skipped
But what about vars with setters? E.g. `var firstName(get,set):String`. 
Don't we have a meta to ignore certain fields already?

**Comment by RealyUniqueName** [comment]
> Don't we have a meta to ignore certain fields already?

That's `@:optional` meta.

**Comment by RealyUniqueName** [comment]
I've changed `@:structInit` to ignore fields with `never` setters. For other cases `@:optional` could be used.
