### ISSUE TITLE
[feature request] Optimization of constant string lengths

### ISSUE THREAD

**Issue by lublak** [HaxeFoundation/haxe#8880]
Sometimes i use `'somestring'.length` in my code to make it more readable instance of just a number.
Example: 
```haxe
if(line.startsWith('###### ')) line.substring('###### '.length);
```

Instance of:
```haxe
if(line.startsWith('###### ')) line.substring(7);
```

It is possible to optimize the output as a number?

**Comment by Simn** [comment]
#5459

**Comment by lublak** [comment]
Sorry for the duplicate issue.
