### ISSUE TITLE
sys.net.Socket.shutdown() is crashing the app

### ISSUE THREAD

**Issue by eminfedar** [HaxeFoundation/haxe#8881]
Hi, I have a `sys.net.UdpSocket` object and I want to shutdown it.

```
var udpSocket:UdpSocket = new UdpSocket();
...
...
// I want to shutdown socket's read&write completely
// so blocking `accept()` function will give error and continue:

udpSocket.shutdown(true,true);
```
But it crashes my app:
```
SysError(shutdown() failure)
Called from sys.net.Socket.shutdown (haxe/std/hl/_std/sys/net/Socket.hx line 153)
```

I don't know why it doesn't work. Maybe a bug in the haxe's core codes? (I've tried to see the C/C++ code but I didn't find them.)

Thanks, have a nice day!

**Comment by ncannasse** [comment]
Udp is connection-less so there's no accept() at all , and I don't think shutdown makes sense either in UDP.

**Comment by eminfedar** [comment]
Yeah you are right, I wrote it wrong, not with `accept()` but with `readFrom()`.

readFrom blocks so I want to make it don't listen and continue because I shut down the socket.

Is there any way to break the readFrom blocking from another thread?
