### ISSUE TITLE
[js] $haxeUID is NaN, breaks bind etc

### ISSUE THREAD

**Issue by gene-pavlovsky** [HaxeFoundation/haxe#8882]
I've been tracking down some intermittent issue which reproduces only under very specific conditions. In the end it is related to bind/haxeUID, I suppose it could be caused by a Chrome bug.

Environment: Chrome 77.0.3865.120 on macOS 10.14.6
DevTools open, mobile mode, responsive device selected in the device toolbar, network cache disabled.

The application is a 2.7 Mb JS file (minification disabled for debugging), generated by haxe 4.0.0-rc.3. We're planning to update to rc.5 but I've checked our "older brother" project which is already on rc.5 and the JS output with regards to bind/haxeUID is the same.

The issue happens to me every time I recompile the project and reload, and only on the first reload. I was checking the issue by adding some nonsense code at the end of the file, then removing it. Every time I add the nonsense code (just one line, some variable declaration), and reload the page, the bug reproduces. When I remove the line and reload, most of the times it doesn't reproduce (but rarely it does). So I did this cycle of "add line, reload, debug, remove line, reload, repeat".

The issue itself is that when a function bound using `.bind` is being called, a different function than expected is actually executed. Turned out `$global.$haxeUID` was `NaN`, so the `m.__id__ = $global.$haxeUID++` code was setting all the bound functions ids to `NaN`.

I then set a breakpoint on the code that is supposed to set this UID to 0: `if (typeof $global.$haxeUID == "undefined") $global.$haxeUID = 0;`

On the times the issue is reproducible, `$global.$haxeUID` was already `NaN` by that point, and `typeof` returned `"number"`, hence the assignment is not performed.
Interestingly, on the times when the issue is not reproducible, `$global.$haxeUID` is 0, not undefined.

There's a bunch of other JS code running on the website as well - but none of it is generated by Haxe or contains a string `haxeUID`, so I think the possibility that some of the other code is somehow responsible for this is very remote.

More likely it's some sort of Chrome bug? I think it would be quite reasonable to assume that a global variable should disappear when a page is reloaded but in my case it doesn't disappear, instead it gets reset to either 0 or NaN.

Advices? :)

**Comment by gene-pavlovsky** [comment]
By the way I made some tests by adding some more variables to $global, with various names (including no special chars like `$`), and types (tried numbers and strings), and sometimes they also exist after a reload...

**Comment by RealyUniqueName** [comment]
I think I've encountered similar situation. Or maybe someone told me about it... I don't remember.
Anyway I've pushed a fix into 4.0_bugfix branch. It will be used for the final 4.0 release.

**Comment by gene-pavlovsky** [comment]
@RealyUniqueName 
Thanks, that was fast. Didn't know you could use `|=` like this in JS, looks like a space-efficient solution :)
I was gonna propose `isNaN()` check instead of comparing `typeof` with `undefined`.
