### ISSUE TITLE
Problem with Map

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/haxe#8883]
I have a code like this 

```hx
var valueRelocs:Map<TyValueID, TyValueID> = [];
```

I am getting a compiler error in Haxe verion 4.0 (rc3 and rc5)

`characters 47-49 : Abstract haxe.ds.Map has no @:to function that accepts haxe.IMap<cabasa.compiler.ssa.TyValueID, cabasa.compiler.ssa.TyValueID>
`

What could be the problem?

**Comment by darmie** [comment]
I tried to wrap it in an abstract, but it didn't solve the problem.

**Comment by RealyUniqueName** [comment]
Haxe's Map only accepts keys of these types: `Int`, `String`, any object type.
For `cs.UInt64` you can create your own implementation of `haxe.Constraints.IMap` interface. But it still won't be 100% interchangable with `Map`. It will have the same methods as `Map`, but you won't be able to pass it to places where `Map` is expected.

**Comment by darmie** [comment]
This is seriously inconvenient. 

C# Dictionary class is not available  in Haxe, only IDictionary interface which is useless. Dictionary would have been a suitable alternative.

**Comment by RealyUniqueName** [comment]
> C# Dictionary class is not available in Haxe

It is available like this:
```haxe
var d = new cs.system.collections.generic.Dictionary_2();
d.Add(key, value);
```

**Comment by darmie** [comment]
Replacing Map with Dictionary for C# target solved my problem.
