### ISSUE TITLE
@:structInit with fields (default:never) don't compile

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#8887]
with commit 34306222ff3d906bf988fe4c8118254db24c651d code like this does not compile anymore
and errors with:

src/Main.hx:9: lines 9-12 : { lastName : String, firstName : String } has extra field lastName
src/Main.hx:9: lines 9-12 : { lastName : String, firstName : String } has extra field firstName

looks like a regression.

```haxe
@:structInit
private class Person {
	public var firstName(default, never):String;
	public var lastName(default, never):String;
} 

class Main {
	static function main() {
		var person: Person = {
			firstName: "Sam",
			lastName: "Smith",
		};
		trace(person);
	}
}
```

**Comment by Aurel300** [comment]
This seems like a bit of an anti-pattern that should not have worked in the first place. Consider the same code without the `@:structInit`:

```haxe
class Main {
  public static function main():Void
    new Person("a", "b");
}
class Person {
  public var firstName(default, never):String;
  public var lastName(default, never):String;
  public function new(f:String, l:String) {
    firstName = f;
    lastName = l;
  }
}
```

This fails to compile with "Cannot access identifier firstName for writing", and `never` should precisely mean that – never written to. Why not use `(default, null)` to allow the class to write to its own fields? Or perhaps use `final` and no property accessors?

**Comment by RealyUniqueName** [comment]
Yeah, `final` fits best here.

**Comment by AdrianV** [comment]
in this case a class with a `field(default, never):Type` without an initialization makes no sense and should not compile!? 
Anyway the tink library uses fields declared like this - so it is a bit of a problem of portability between haxe versions. 
But it should be Ok to declare the fields as (default,null) there @back2dos ?  because final is not portable between haxe versions either - or you get a bunch of ugly #if all over.

**Comment by AdrianV** [comment]
I will close the issue here and open it there
