### ISSUE TITLE
Custom properties no longer supported EVEN if same, * not documented as breaking change.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#8891]
Haxe4 breaks code that for me seems valid, I understand I don't need to specify the name in the property but it tends to break a lot of user code by insisting it does not specify the name. 

Surely it should be acceptable to still use the name in the getter/setter ( optionally ) because this is not really custom ? 

_Any library wanting to support older versions of Haxe this change is rather an ugly to implement?_  

Surely warning would be better, and the haxe compiler remap get_prop to get and set_prop to set?

**Well anyway just raising issue as a reminder to added to breaking changes, many thanks :)**
http://try-haxe.mrcdk.com/#Bc456
``` haxe
class Test {
  static function main() {
    new Test();
  }
  var _prop: String = '';
  public var prop( get_prop, set_prop ): String;
  function get_prop(): String{
    return _prop;
  }
  function set_prop( val: String ): String{
    _prop = val;
    return _prop;
  }
  function new(){
    prop = 'Test property';
    trace( prop );
  }
}
```
``` haxe
Test.hx:6: characters 20-28 : prop: Custom property accessor is no longer supported, please use `get`
Test.hx:6: characters 30-38 : prop: Custom property accessor is no longer supported, please use `set`
```

**Comment by Simn** [comment]
This was already deprecated in Haxe 3 and is now removed in Haxe 4. You can use `get` and `set` in both Haxe 3 and 4, so this shouldn't be an issue for libraries.
