### ISSUE TITLE
js.Syntax.code generates invalid JS when missing arguments

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#8892]
Haxe versions tested: 4.0.0.rc5, rc3

The following uses [`js.Syntax.code`](https://api.haxe.org/v/development/js/Syntax.html#code), where I forgot to supply the extra args:

```
    var is_element = js.Syntax.code('{0} instanceof Element');
```

It generates the following line of JavaScript, passing the `{0}` directly through:

```
	var is_element = {0} instanceof Element;
```

I would think that Haxe would detect that the {0} argument is missing and throw a compile-time error.

**Comment by nadako** [comment]
BTW you probably should use `js.Syntax.instanceof` here instead :)

**Comment by jcward** [comment]
> BTW you probably should use `js.Syntax.instanceof` here instead :)

Yeah, I knew that existed, but forgot where it was defined... I was looking over in `js.Lib`.
