### ISSUE TITLE
[php] no arrayAccess in php.NativeStructArray

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#8893]
`php.NativeStructArray` proves really quite useful for defining types of function parameters in extern php functions. Is there any reason why it's missing `arrayAccess` (opposed to `php.nativeAssocArray`)?

**Comment by RealyUniqueName** [comment]
It is supposed to be used for externs arguments just to provide type safety for options declarations.
Do you have a use case for `NativeStructArray` in a Haxe code?

**Comment by mockey** [comment]
Yes.
I have an extern function `getcliplist` which can accept an `id` or a `name`.
It's typed like this (simplified):
```haxe
typedef ClipListRequest = ArrayS<{
  ?id:String,
  ?name:String,
  login:String
}>;
extern public function getcliplist(req:ClipListRequest):ClipListResponse;
```
Then I like to call it like thiis:
```haxe
function getClip(id:Int, ?name:String) {
  var req:ClipListRequest = {
    login: "login"
  }
  if (name != null && id == 0) req["name"] = name;
  else req["id"] = id;
  var res = F.getcliplist(req);
}
```
Adding:
```haxe
@:arrayAccess
inline function get<V>(key:String):V return this[key];

@:arrayAccess
inline function set<V>(key:String, val:V):V return this[key] = val;
```
to `php.NativeStructArray` seems to allow this.

**Comment by RealyUniqueName** [comment]
Ideally I'd like to implement a proper typed field access to `NativeStructArray`. Currently it's blocked by #6639.

**Comment by mockey** [comment]
I see. Thanks for adding it.
