### ISSUE TITLE
float in array error

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8898]
target:hashlink

	static function main() {
		var a:Float = 19.96;
		trace(a);

		var dd = [];

		for (i in 0...10) {
			dd.push({a: a});
		}

		trace(dd); //19.9600000000000001?
      }

![image](https://user-images.githubusercontent.com/748320/67617975-51b2f980-f81b-11e9-9698-92b34eafa9f4.png)
@ncannasse

**Comment by haxiomic** [comment]
@sonygod this is somewhat expected – 19.96 stored as a float in memory isn't exactly 19.96. Try this in JavaScript `(19.96).toPrecision(20)`. You should get `19.960000000000000853`

The difference between `trace(a)` and `trace(dd)` is the float is printed with differing levels of precision, but it's still printing the same value

You can read more about why floats do this here
https://floating-point-gui.de/
