### ISSUE TITLE
4.1 Version

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#8902]
Now that 4.0 is released (yay!) we should close 4.0 milestone, move issues there either to 4.1 or other milestones (back to backlog etc.)

We should also upgrade haxe prompt to 4.1-rc1 (right now it's still 4.0-rc5 I think)

**Comment by nadako** [comment]
Also try.haxe pl0x

**Comment by Simn** [comment]
I've dealt with the milestone and the version.

Nothing I can do about try.haxe. I think we'd need a volunteer to take that over and maintain it.

**Comment by RealyUniqueName** [comment]
We should've probably left 4.0 milestone to get those issues fixed for 4.0.1

**Comment by Simn** [comment]
None of these issues looked like something I'd necessarily want to do in a patch release though.

**Comment by RealyUniqueName** [comment]
Create a maintainable alternative to `@:multiType`.

**Comment by RealyUniqueName** [comment]
issues moved, version bumped
