### ISSUE TITLE
socket error on cs target

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8904]
haxe 4.0 
 
   std\cs\_std\sys\net\Socket.hx :Line 70

 fixed  

    sock.Connect(host.ipAddress, port);  //host.ipAddress should change to host.host

![image](https://user-images.githubusercontent.com/748320/67730377-d6766100-fa2f-11e9-8019-4d1f7c0d59bd.png)

		 
		 public function connect(host:Host, port:Int):Void {
				sock.Connect(host.ipAddress, port);  //host.ipAddress should change to host.host?
				if (sock.Connected) {
					this.output = new cs.io.NativeOutput(new NetworkStream(sock));
					this.input = new cs.io.NativeInput(new NetworkStream(sock));
				} else {
					throw "Connection failed.";
				}
			}

**Comment by RealyUniqueName** [comment]
That would be super helpful if you could provide a complete sample.

**Comment by sonygod** [comment]
@RealyUniqueName  sample is here

https://github.com/ianharrigan/hxWebSockets/tree/master/Examples/sys-client

**Comment by sonygod** [comment]
https://github.com/ianharrigan/hxWebSockets/issues/13
