### ISSUE TITLE
Haxe 4 installer for Windows 64bit bundles Neko 2.2

### ISSUE THREAD

**Issue by mikkelmr** [HaxeFoundation/haxe#8906]
The official Haxe 4 installer(https://haxe.org/download/file/4.0.0/haxe-4.0.0-win64.exe/) installs neko 2.2 (at least the windows 64bit installer, don’t know about the other platforms).

![image](https://user-images.githubusercontent.com/16362939/67782406-0726bc80-fa69-11e9-8513-1c84f93f11f5.png)

![image](https://user-images.githubusercontent.com/16362939/67780888-012fdc00-fa67-11e9-882a-a206feca046e.png)

It should bundle Neko 2.3 I believe.

**Comment by RealyUniqueName** [comment]
Fixed in aef3be8d764a7f481d278d8aac572e1f8f506e7f
Leaving this open until we actually release it.

**Comment by 0x3224B088** [comment]
Shouldn't NEKO_VERSION in extra/installer.nsi be updated too and maybe update the copyright year in LegalCopyright there too? :)

**Comment by RealyUniqueName** [comment]
Addressed in 4.0.1
