### ISSUE TITLE
Title of the Haxe 4 installer contains build/commit hash

### ISSUE THREAD

**Issue by mikkelmr** [HaxeFoundation/haxe#8907]
The title of the Haxe 4 installer(https://haxe.org/download/file/4.0.0/haxe-4.0.0-win64.exe/) includes a build/commit hash, which I believe is not intended.

![image](https://user-images.githubusercontent.com/16362939/67781496-d42ff900-fa67-11e9-8f68-8fe8c67d0491.png)

**Comment by RealyUniqueName** [comment]
I guess for this to fix we need to restore our CI to build on tags.
@andyli ?

**Comment by andyli** [comment]
Right. It's also needed for deploying docs to api.haxe.org (https://github.com/HaxeFoundation/api.haxe.org/issues/7).
I will work on it.

**Comment by andyli** [comment]
Fixed in 24b0b89d5e4c95728af77f7fe25539f0c71ec13f, also cherrypicked it to 4.0_bugfix.
