### ISSUE TITLE
SauceLabs disabled?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8910]
Looks like SauceLabs is not working since Jun 20 (https://saucelabs.com/open_sauce/user/haxe/builds)?

I need it running for https://github.com/HaxeFoundation/haxe/pull/8909

**Comment by andyli** [comment]
Looks like my commit at https://github.com/HaxeFoundation/haxe/commit/b20434e1ad9d4ac8dad01ff8a6e94b311ca35a7b broke it... Going to find a fix.

**Comment by andyli** [comment]
Bad news:
```
src/unit/TestMain.hx:42: Generated at: 2019-10-30 15:48:57
src/unit/TestMain.hx:44: START
TEST ERRORS
9604 tests, 9602 passes, 2 errors performed on javascript, executed in 2.472 sec.
unit
3847 tests, 3845 passes, 2 errors
TestHttp
2 tests, 2 errors
ERROR
testPostBytes: 1 test, 1 error
missed async call(s): 1
ERROR
testPostData: 1 test, 1 error
missed async call(s): 1
```

And, oh god...
https://github.com/HaxeFoundation/haxe/blob/24b0b89d5e4c95728af77f7fe25539f0c71ec13f/tests/unit/src/unit/TestMain.hx#L131

**Comment by Aurel300** [comment]
Isn't the "success state" something you can decide with an `onProgress` callback?

**Comment by RealyUniqueName** [comment]
@andyli Could you please submit to a branch? I'll work on fixing reported failures and the utest issue.

**Comment by andyli** [comment]
I'm still working on a fix of the detection of `$(SAUCE_ACCESS_KEY)`. Will push it to development.

**Comment by RealyUniqueName** [comment]
Resolved
