### ISSUE TITLE
Confusingly bad performance with HL/Neko targets vs node

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [HaxeFoundation/haxe#8911]
Im using Haxe 4.0.0+ef18b627e, with hashlink 1.10

This simple code
```haxe
package;
import sys.io.File;
import sys.FileSystem;

class Main {
	public function new() {
		var start = Sys.time();
		Sys.print('Starting\n\n');

		var total = 100000;
		var current = 0;
		for(i in 0...total){

			var s = Std.string(i);
			if(s.length < 5){
				while(s.length < 5){ s = "0"+s; }
			}

			var a = s.split("");
			var file = a.pop() + ".json";
			var path = a.join("/");
			current++;
		}

		var end = Sys.time()-start;
		Sys.print('\n\nDone in ${end} seconds\n\n');
	}

	static public function main() {
		var app = new Main();
	}
}
```
Takes 9.8 _seconds_ to execute on my machine, when compiled to the hashlink target, and run via `hl output.hl`. First surprise, when compiled to the neko target, and run via `neko output.n` it takes 6.5 seconds, still really slow, but somehow better than hashlink?

Comparatively, this plain js code
```javascript
var start = new Date()
console.log('start')

var total = 100000;
var current = 0;
for(var i = 0; i<total; i++){

	var s = i.toString();
	if(s.length < 5){
		while(s.length < 5){ s = "0"+s; }
	}

	var a = s.split("");
	var file = a.pop() + ".json";
	var path = a.join("/");

	current++;
}

var end = new Date() - start
console.info('Execution time: %dms', end)
```
Run via `node file.js` executes in **63 _milliseconds_**

Ive tested this on a Macbook, as well as a reasonably powerful desktop running Ubuntu, similar results.

I dont understand what the deal is here? This doesnt seem right at all, surely hashlink/neko cant be hundreds of times slower than node? This seems like a bug?

**Comment by kLabz** [comment]
See https://github.com/HaxeFoundation/haxe/issues/8780 for a similar issue (and a workaround)

**Comment by matthewjumpsoffbuildings** [comment]
Yep that was it. It seems that ANY basic string stuff like `split()`, concatenation etc - my execution time goes from a few hundred ms to 9 seconds...

How can I use the full range of string features with a StringBuf?

**Comment by Simn** [comment]
Closing in favor of #8780.
