### ISSUE TITLE
Abstract Float loses various functionality, even with @:forward

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#8916]
```haxe
class Test
{
    static function main()
    {
        var value:FancyFloat = 5;
        trace(value / 5.0); // FancyFloat should be Int
        trace(value + 5.0); // works
        trace(value + 5); // FancyFloat should be Int
    }
}

@:forward
abstract FancyFloat(Float) to Float from Float from Int {}
```

Not sure why it expects Int here, but I expect the above code to work. Also, I'm aware of static extension but that doesn't fit my intended use that well.

**Comment by RealyUniqueName** [comment]
You have to explicitly define, which operations are allowed for `FancyFloat` with operators overloading: https://haxe.org/manual/types-abstract-operator-overloading.html

**Comment by Gama11** [comment]
Relevant feature request: https://github.com/HaxeFoundation/haxe/issues/5035

**Comment by Geokureli** [comment]
Thanks for the link, Gama.

@RealyUniqueName why don't I have to define the `Float+Float` operator? This seems really inconsistent.

**Comment by ibilon** [comment]
It's not about the `@:forward`, if you remove the `to Float` then `Float+Float` fails too.
If you do `$type(value + 5.0);` you'll get `Test.hx:7: characters 14-25 : Warning : Float` not `FancyFloat`.

**Comment by Geokureli** [comment]
I'm fine with `(value + 0.5)` resulting in a Float rather than FancyFloat, in fact, I expect this. I'm confused why `FancyFloat + Float` works but not any other operator of Float. as a lesser question, I'm wondering why `FancyFloat + Int` doesn't work, but mostly because it gives the same error as `FancyFloat / Float`
