### ISSUE TITLE
Arch linux repository not updated

### ISSUE THREAD

**Issue by demacedius** [HaxeFoundation/haxe#8920]
Hi i'm on Arch linux and i've see the community repository as not updated for haxe 4.0 release . Have you see that?

**Comment by andyli** [comment]
From the [package's page](https://www.archlinux.org/packages/community/x86_64/haxe/) you can see that it has already been flagged as outdated. The package maintainer (Alexander Rødseth) should have noticed. He is a volunteer AFAIK, so please be patient.

You may want to compile Haxe for yourself in the mean time. See https://github.com/HaxeFoundation/haxe/blob/4.0.0/extra/BUILDING.md
