### ISSUE TITLE
File "src/context/common.ml", line 501, characters 21-27: Assertion failed

### ISSUE THREAD

**Issue by thief-sty** [HaxeFoundation/haxe#8921]
When trying to use the (Linux 64) Haxe binaries available on the website or attempting to `make` by myself, I get the following error:

`File "src/context/common.ml", line 501, characters 21-27: Assertion failed`
which refers to ` tnull = (fun _ -> assert false);` in the following snippet:

```
		basic = {
			tvoid = m;
			tint = m;
			tfloat = m;
			tbool = m;
			tnull = (fun _ -> assert false);
			tstring = m;
			tarray = (fun _ -> assert false);
		};
```

I have no idea where the problem could come from.

**Comment by Simn** [comment]
Try defining the environment variable `OCAMLRUNPARAM=b` and post the stack trace.

The position suggests that something tries to do typing before `Typer.create` has finished, which populates these record fields.

**Comment by thief-sty** [comment]
Here are the logs for `$ OCAMLRUNPARAM=b make`:

```
dune build --workspace dune-workspace.dev src-prebuild/prebuild.exe
_build/default/src-prebuild/prebuild.exe libparams -cclib -lpcre -cclib -lz > lib.sexp
_build/default/src-prebuild/prebuild.exe version 0 development b3b7695f5 > src/compiler/version.ml
dune build --workspace dune-workspace.dev src/haxe.exe
cp -f _build/default/src/haxe.exe ./haxe
(cd /home/algorythmis/haxe/extra/haxelib_src && /home/algorythmis/haxe/haxe client.hxml && nekotools boot run.n)
Fatal error: exception File "src/context/common.ml", line 501, characters 21-27: Assertion failed
Raised at file "src/context/common.ml", line 501, characters 21-33
Called from file "src/typing/typeloadModule.ml", line 645, characters 14-53
Called from file "list.ml", line 92, characters 20-23
Called from file "list.ml", line 92, characters 32-39
Called from file "list.ml", line 92, characters 32-39
Called from file "src/typing/typeloadModule.ml", line 641, characters 11-403
Called from file "list.ml", line 110, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 619, characters 2-1023
Called from file "list.ml", line 110, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 886, characters 1-35
Called from file "src/typing/typeloadModule.ml", line 942, characters 11-48
Called from file "src/typing/typeloadModule.ml", line 983, characters 4-45
Called from file "src/typing/typeloadModule.ml", line 390, characters 12-69
Called from file "list.ml", line 110, characters 12-15
Called from file "src/typing/typeloadModule.ml", line 886, characters 1-35
Called from file "src/typing/typeloadModule.ml", line 942, characters 11-48
Called from file "src/typing/typeloadModule.ml", line 983, characters 4-45
Called from file "src/compiler/haxe.ml", line 506, characters 32-93
Called from file "list.ml", line 110, characters 12-15
Called from file "src/compiler/haxe.ml", line 506, characters 2-113
Called from file "src/compiler/haxe.ml", line 505, characters 1-182
Called from file "src/compiler/haxe.ml", line 1056, characters 3-39
Called from file "src/compiler/haxe.ml", line 633, characters 3-11
Called from file "src/compiler/haxe.ml", line 1226, characters 1-35
make: *** [Makefile:101: haxelib] Error 2
```

**Comment by RealyUniqueName** [comment]
This means the compiler was built successfully, but building haxelib with that compiler fails.
Normally that shouldn't happen. I still suspect some quirks of your local environment.
Try to build a "hello world" sample.
Do you have `HAXE_STD_PATH` environment variable? If not, then try setting it to `/path/to/haxe/std`

**Comment by thief-sty** [comment]
`HAXE_STD_PATH` is set to `/usr/share/haxe/std`, which does contain a Haxe library, although I'm not sure if it's the correct version of it.

What do you mean by "hello world" sample?

**Comment by RealyUniqueName** [comment]
```haxe
class Main {
  static public function main() {
    trace('hello, world');
  }
}
```
```
$ haxe -main Main --interp
```

**Comment by thief-sty** [comment]
It works.
```
Main.hx:3: hello, world
```

**Comment by RealyUniqueName** [comment]
> HAXE_STD_PATH is set to /usr/share/haxe/std, which does contain a Haxe library, although I'm not sure if it's the correct version of it.

Ensure it's the correct std bundled with the compiler you are running.

**Comment by thief-sty** [comment]
I replaced it with the one bundled with the compiler just before testing.

**Comment by RealyUniqueName** [comment]
Sorry, I'm out of ideas.
Maybe try adding this line
```ocaml
print_endline (Lexer.get_error_pos (Printf.sprintf "%s:%d:") tp);
```
before line 645 in typeloadModule.ml. It will print the positions in haxelib code. Post the last one here. I hope it will give a hint.

**Comment by RealyUniqueName** [comment]
I get very similar issue using Haxe 4 compiler and std lib from Haxe 3

**Comment by thief-sty** [comment]
This?
```
/usr/share/haxe/std/haxe/zip/Huffman.hx:28: characters 24-38
mv extra/haxelib_src/run haxelib
```

**Comment by RealyUniqueName** [comment]
Yeah, nothing suspicious.

But as I said, I have exactly the same error when trying to build haxelib using Haxe 4 compiler and Haxe 3 std lib.
Try removing `/usr/share/haxe/std` completely and then restore it from Haxe 4 binaries archive https://github.com/HaxeFoundation/haxe/releases/download/4.0.1/haxe-4.0.1-linux64.tar.gz

**Comment by thief-sty** [comment]
It looks like it works. Weird, I'd swear I checked it more than twice.

Thank you for your time.
