### ISSUE TITLE
Haxe 4 regression: Variables cannot be named "operator"

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/haxe#8924]
The following works in Haxe 3.4.4: 
```haxe
class Test {
    static function main() {
        var operator = 42;
        trace(operator);
    }
}
```

In Haxe 4.0.0, it results in the following error: `Test.hx:3: characters 9-12 : Missing variable identifier`.

![image](https://user-images.githubusercontent.com/879967/68053826-2fbee880-fced-11e9-87a6-fad9cb49285d.png)

---

EDIT:

It seems like `operator` is a new [keyword](https://github.com/HaxeFoundation/haxe/blob/3c2f7b867014ecc79d95654e38d94fb3577a5138/src/syntax/lexer.ml#L449). However, there's nothing in https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0 or https://github.com/HaxeFoundation/haxe/wiki/What's-new-in-Haxe-4 about it.

**Comment by Aurel300** [comment]
FWIW there is a [list of keywords](https://haxe.org/manual/expression.html) in the manual, but it should indeed be added into the breaking changes.

**Comment by RealyUniqueName** [comment]
It's a new keyword: https://github.com/HaxeFoundation/haxe/issues/7413

**Comment by varadig** [comment]
@anissen 
And can't use 'operator' as package name too.

**Comment by anissen** [comment]
I'll close this issue as `operator` is simply a new keyword as documented in the manual.

Feel free to reopen as a reminder to add this change to https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0.

**Comment by RealyUniqueName** [comment]
Added: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0#operator-keyword

**Comment by Gama11** [comment]
That's not the only new keyword, there's also `overload`: 545867168432f7017a4b0b3734a54fc75f4c59aa

**Comment by RealyUniqueName** [comment]
Thanks. Added that too.
