### ISSUE TITLE
Haxe 4: Macro causes compilation failure on externed Definitions

### ISSUE THREAD

**Issue by turbo** [HaxeFoundation/haxe#8926]
This seems to be related to #6543. I'm using Lua as the target and this command to compile:

```bash
haxe --lua out.lua --main Main -D luajit
```

However, the target doesn't matter at all here, same thing happens with other targets. Here's the complete code:

```haxe
@:nullSafety
class Main {
	static function main() {
		var strfind = NativeString.find("fizzbuzz", "bu44z");
		trace(strfind.begin);
		trace(strfind.end);
		trace("人".length == 1);
		Reflect.callMethod(Main, Reflect.field(Main, "f"), []);
		var dom = jsx(<hi/>);
		trace(dom);
	}

	static macro function jsx(expr) {
		return switch expr.expr {
			case EMeta({name: ":markup"}, {expr: EConst(CString(s))}):
				macro $v{"XML MARKUP: " + s};
			case _:
				throw new haxe.macro.Expr.Error("not an xml literal", expr.pos);
		}
	}

	static function f() {
		trace("Called");
	}
}

@:native("string")
extern class NativeString {
	public static function find(str:String, target:String):StringFind;
}

@:multiReturn extern class StringFind {
	var begin:Int;
	var end:Int;
}
```

This will fail to compile with this message:

```text
Field index for find not found on prototype string
```

Comment out either the macro or externed function invokation and it compiles again.

**Comment by RealyUniqueName** [comment]
This happens because of `NativeString` is also leaking into a macro context.  
You should either fence your code with `#if macro` and `#if !macro` or move `macro function jsx` to a separate file like this:
```haxe
//Main.hx
@:nullSafety
class Main {
	static function main() {
		var strfind = NativeString.find("fizzbuzz", "bu44z");
		trace(strfind.begin);
		trace(strfind.end);
		trace("人".length == 1);
		Reflect.callMethod(Main, Reflect.field(Main, "f"), []);
		var dom = jsx(<hi/>);
		trace(dom);
	}

	static macro function jsx(expr:haxe.macro.Expr):haxe.macro.Expr

	static function f() {
		trace("Called");
	}
}

@:native("string")
extern class NativeString {
	public static function find(str:String, target:String):StringFind;
}

@:multiReturn extern class StringFind {
	var begin:Int;
	var end:Int;
}
```
```haxe
//Main.macro.hx
import haxe.macro.Expr;

class Main {
	static function jsx(expr:Expr):Expr {
		trace(expr);
		return switch expr.expr {
			case EMeta({name: ":markup"}, {expr: EConst(CString(s))}):
				macro $v{"XML MARKUP: " + s};
			case _:
				throw new haxe.macro.Expr.Error("not an xml literal", expr.pos);
		}
	}
}

**Comment by Aurel300** [comment]
Well, `@:native("string")` is probably the culprit. Macro compilation, which runs in the Eval target, will fail there, and report that there is no such "native" class with the error you are seeing. If this is intended to access some Lua functionality, you need to make sure the macro runtime does not see it. And why not use code injection and an inline function?

Oh no, @RealyUniqueName was faster :)

**Comment by turbo** [comment]
Thanks! I gotta say, the error message could be a lot more informative. Maybe include the current evaluation context in the message? That would have helped me narrow it down.
