### ISSUE TITLE
Static extension on Nullable types

### ISSUE THREAD

**Issue by Geokureli** [HaxeFoundation/haxe#8928]
As far as I know, the following should be valid. `getSpeed` takes and handles null, yet `Null<Direction>` does not have a getSpeed method. I could understand if null safety was enabled and getSpeed took non-nullable types, but neither is the case, here.

```haxe
package test;

class Test
{
    static function main()
        handle(Forward);
    
    static function handle(?dir:Direction)
        // Error: Null<Direction> has no field getSpeed
        trace(dir.getSpeed());
}

@:using(test.DirectionTools)
enum Direction { Forward; Backward; }

class DirectionTools
{
    inline static public function getSpeed(dir:Null<Direction>)
    {
        return switch dir
        {
            case Forward | null: 10;
            case Backward: -10;
        }
    }
}
```

**Comment by RealyUniqueName** [comment]
I agree this should work.

**Comment by RealyUniqueName** [comment]
And it works with normal `using` directive.

**Comment by Geokureli** [comment]
Also want to point out that it works with `using` when `getSpeed` doesn't specify a nullable type.

This makes sense unless null safety is enabled(?)

**Comment by RealyUniqueName** [comment]
The precense of `Null` should not change behavior here despite the null safety state.
Currently null safety is implemented as just a post-processing step and doesn't affect typing.
