### ISSUE TITLE
[Haxe 4.0.1] Sys_error("Not enough space") on Windows 7

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxe#8935]
It happens when I install multiple haxelib in one script, or even when I build project.

Example:
**build-web.hxml**
`-cmd haxelib run openfl build project.xml html5 -final -Dwebgl -verbose -dce full -minify`
```
C:\Users\CrazyFlasher\Documents\work\git\projects\shibainuhx>haxe scripts/build-web.hxml
 .d88 88b.                             888888b 888
d88P" "Y88b                            888     888
888     888                            888     888
888     888 88888b.   .d88b.  88888b.  8888888 888
888     888 888 "88b d8P  Y8b 888 "88b 888     888
888     888 888  888 88888888 888  888 888     888
Y88b. .d88P 888 d88P Y8b.     888  888 888     888
 "Y88 88P"  88888P"   "Y8888  888  888 888     "Y888P
            888
            888

OpenFL Command-Line Tools (8.9.5-LoqcFr)

Initializing project...
Using project file: project.xml
Reading Lime config: C:\Users\CrazyFlasher\.lime\config.xml

Running command: UPDATE
 - Detecting font name: export/web/html5/obj/webfont/NotoSans-Medium.ttf -> "Noto Sans Medium"
 - Writing file: export/web/html5/bin/manifest/default.json

Running command: BUILD
 - Running command: haxe export/web/html5/haxe/final.hxml
 - Detecting font name: export/web/html5/obj/webfont/NotoSans-Medium.ttf -> "Noto Sans Medium"
 - Copying template file: C:/Users/CrazyFlasher/Documents/work/git/projects/shibainuhx/.haxelib/casinohx/git/templates/web/html5/output.js -> export/web/html5/bin/Main.js
 - Running command: java -Dapple.awt.UIElement=true -jar C:/Users/CrazyFlasher/Documents/work/git/projects/shibainuhx/.haxelib/lime/7,6,3/templates/bin/compiler.jar --strict_mode_input false --js export/web/html5/bin/Main.js --js_output_file C:\Users\CRAZYF~1\AppDa
ta\Local\Temp/temp_3627947.js
Fatal error: exception Sys_error("Not enough space")

C:\Users\CrazyFlasher\Documents\work\git\projects\shibainuhx>
```

**Comment by Simn** [comment]
I have no idea what to do with this and you seem to be the only one having this problem. Maybe try on a different machine.

**Comment by nanjizal** [comment]
Rather a long shot, not really getting why Java is used but...
Is Java requiring a larger heap size the default set is often very small especially in relation to AIR projects which is what triggered when I saw memory error and java together?  
Do you need to increase the default size from 128 to something larger... -Xmx512m, -Xmx1024m, -Xmx2048 - perhaps something to google.
The only other long shot would be path issues I would generally avoid tricky paths like "CRAZYF~1" avoid spaces and funny characters in file paths ( until atleast your sure that's not the problem ), and also try not to have really excessively long paths as that used to be a hxcpp issue I once encountered.
Sorry if my wild guesses are not useful just adding incase they are.

**Comment by RealyUniqueName** [comment]
We need more data to be able to do something here.
Moving this to "Backlog" milestone (due to lack of a more suitable milestone) until we have something to act upon.

**Comment by CrazyFlasher** [comment]
@nanjizal but how it's relased to java? Anyways I've increased default heap size in env vars `_JAVA_OPTIONS: -Xmx1g`, but that didn't help as expected.
I receive this error even when run simple script, that resolves haxelibs:
```
-cmd haxelib newrepo
-cmd haxelib --never install lime 7.6.3
-cmd haxelib --never install openfl 8.9.5
-cmd haxelib --never install munit
-cmd haxelib --never git zame-particles https://github.com/CrazyFlasher/zame-haxe-particles.git 992761cf500db8e005900ebf18f8219cf99a6e5e
-cmd haxelib --never git hamcrest https://github.com/mikestead/hamcrest-haxe.git master src
-cmd haxelib --never git feathersui https://github.com/BowlerHatLLC/feathersui-openfl.git d880200deef40b5d2d331ada720c4ed8b2a9a298
-cmd haxelib --never git spritesheet https://github.com/CrazyFlasher/spritesheet.git 08f7987b2f069efb7a5a1d40463ee43ff0239145
...
```
Error can be received immediately or during some time.
There are no problems on Linux or Windows 10.
Does anyone know, Is it possible to get some extra logs about error?

**Comment by RealyUniqueName** [comment]
I don't see anything suspecious there.
Have you tried it on a different machine with Windows 7? Could it be your HDD dying?

**Comment by Simn** [comment]
Closing due to lack of followup.

**Comment by CrazyFlasher** [comment]
Though I still get this error on Windows 7 :) 
May be someone can connect to my PC via TeamViewer?
