### ISSUE TITLE
texpr-based display modes

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#8939]
Requested by InnoGames via @nadako. We need a solution for #8596.

Since my approach there didn't work, we can try something else: Don't invalidate the display file at all if the content didn't change and then provide display information by analyzing the typed AST instead of the syntax AST.

This requires a completely different approach to how we handle display requests. Currently, we invalidate the display module and then figure out what to display while typing it. This is achieved by inserting `EDisplay` nodes into the AST, which are then picked up and processed by the typer.

Instead we want skip the typing step completely. This requires 3 steps:

1. Detect that we can use this mode: This is the case if the current (unsaved) content of the file is equal to the saved content. This can be done at IDE-level or by Haxe.
2. Figure out what we want to display: We know the module, now we have to find the type -> field -> expression. We can detect type and field with a simple position-contains check like we do already. For the expression, we need a bottom-up traversal of the typed AST similar to what `ExprPreprocessing.find_before_pos` does (but less complicated).
3. Output the display result: Ideally, this comes down to calling one of the functions in `displayEmitter.ml`.

----

Now that I've written this down, it actually sounds less scary than I thought it would be. I'll work on this and post updates here.

**Comment by Simn** [comment]
Encountered a problem: We don't have positional information for type-hints in the typed AST. The only information we retain is a position-to-position mapping which encodes which definition positions are referenced from which usage positions.

It may be possible to dig up the referenced type by its position, but I don't know how robust that is. I can't see much of an alternative though.

**Comment by Simn** [comment]
This approach might end up not helping at all due to diagnostics. We need to run the typer in order to get diagnostics, so we're back to the original problem.

**Comment by nadako** [comment]
But running the typer when most modules are cached is faster than on invalidated by some hovers?

**Comment by Simn** [comment]
You don't even  get the chance to invalidate via hover if your IDE invalidates via diagnostics as soon as you open the file.

**Comment by Simn** [comment]
The basics for this are implemented. There are probably some issues and oversight, but we can address these as we go.

**Comment by nadako** [comment]
thanks, will test!
