### ISSUE TITLE
[jvm] crash if main() returns something

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#8940]
```haxe
class Main {
  static function main() {
    return 0;
  }
}
```

```
Exception in thread "main" java.lang.NoSuchMethodError: haxe.root.Main.main()V
        at haxe.root.Main.main(src/Main.hx)
```

**Comment by Simn** [comment]
Can't you just... not do that? :P

**Comment by Aurel300** [comment]
Shouldn't this be caught before generators anyway? Check that the `main` method is `()->Void`.

**Comment by Simn** [comment]
I'm wondering about that too, it's not like that return value magically becomes the exit code...

**Comment by Aurel300** [comment]
To be fair allowing an `Int` return from `main` could be convenient to actually make it the exit code :D

**Comment by ncannasse** [comment]
with haxe.MainLoop and on many platforms, returning from main() does not
exit, and there's actually no notion of "exit code" so I would keep the
main return as Void.

**Comment by Simn** [comment]
I have a feeling that this might be annoying, but the good news is that it only affects actual `main` functions and thus won't have much of an impact on libraries.
