### ISSUE TITLE
Recursive function returning Dynamic dooms runtime values

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#8941]
I confess I shouldn't use Dynamic, `Any` doesn't have this problem. Feel free to close if not suppose to fix.

```haxe
class Main {
  static function main() {
    trace(rec(0));
  }
  
  static function rec(v:Int):Dynamic {
    return switch v {
      case 0:
        var value = rec(1);
        $type(value); // Unknown
        trace(value, Std.is(value, Float)); // output (0, true) on cpp; crash on java (java.lang.String cannot be cast to java.lang.Number); 
        -value;
      case 1:
        'val';
      case _:
        2;
    }
  }
}
```

I suppose the expression `-value` causes type inference to determine the type to be Float, in turns causes the weird errors.

Type hinting explicitly fixes it:
`var value:Dynamic = rec(1);`

**Comment by RealyUniqueName** [comment]
There's nothing to fix here. 
`value` is typed as an integer (because of `-value`) hence a runtime exception. Java just doesn't allow storing strings in integer variables.
