### ISSUE TITLE
haxe.Unserializer performance issue on PHP

### ISSUE THREAD

**Issue by ngrebenshikov** [HaxeFoundation/haxe#8943]
I experience a significant performance decrease using haxe.Unserializer for PHP target. It's because it relies on StringTools.fastCodeAt that uses multibyte strings now. So now it's O(n) instead of O(1). 

The example code to test StringTools.fastCodeAt:
```haxe
class Main {
	public static function main() {
		for (k in 10...21) {
			var prevTime: Float = Date.now().getTime();
			var size = 1 << k;
			trace(k);
			var b = haxe.io.Bytes.alloc(size);
			b.fill(0, size, "a".code);
			var s = b.toString();
			for (i in 0...size) {
			 	StringTools.fastCodeAt(s, i);
			}
	        trace(Date.now().getTime() - prevTime);
    	}
	}
}
```

And its output:
```
Main.hx:6: 10
Main.hx:13: 6
Main.hx:6: 11
Main.hx:13: 11
Main.hx:6: 12
Main.hx:13: 42
Main.hx:6: 13
Main.hx:13: 179
Main.hx:6: 14
Main.hx:13: 1023
Main.hx:6: 15
Main.hx:13: 3297
Main.hx:6: 16
Main.hx:13: 14865
Main.hx:6: 17
Main.hx:13: 46878
Main.hx:6: 18
Main.hx:13: 190567
...
```

My environment:
Haxe: 4.0.1
PHP: 7.3.8 (cli) (built: Aug 24 2019 19:38:14) ( NTS )
Platform: OSX

**Comment by ncannasse** [comment]
Maybe fastCodeAt should not be Unicode aware, so O(1) ?

**Comment by ngrebenshikov** [comment]
The solution makes my app working fast but it breaks the deserialisation of data serialised on JS target.

**Comment by ngrebenshikov** [comment]
Great! It works for me. Thanks!
