### ISSUE TITLE
Empty flag values evaluate to false for conditional compilation

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/haxe#8946]
Flags with empty values (e.g `haxe -D FLAG= ...`) evaluate to false in `#if/#elseif` conditions, even though `Context.defined("FLAG") == true`.

Also, flag values are not otherwise taken into account and `-D FLAG=0` evaluates to true.

```haxe
class Main {
	static function main() {
		#if FLAG
		trace("ok");
		#else
		trace("branch discarded");
		#end
	}
}
```

```
$ haxe -D FLAG --run Main
Main.hx:4: ok

$ haxe -D FLAG=0 --run Main
Main.hx:4: ok  # still

$ haxe -D FLAG= --run Main
Main.hx:6: branch discarded
```

**Comment by jonasmalacofilho** [comment]
A different approach from #8947 would be to change `FLAG=0` and `FLAG=false` to also evaluate to false.

But it could break some code...

**Comment by RealyUniqueName** [comment]
This is "by design" currently. Because defines are declared as a `string => string` structure in the compiler:
https://github.com/HaxeFoundation/haxe/blob/1e77f62999fbe43682034f27778b7a57e6282d5b/src/core/define.ml#L4-L5
Maybe that should be changed to `string => string option`
@Simn ?
