### ISSUE TITLE
Windows Sees Installer as Trojan

### ISSUE THREAD

**Issue by dmcblue** [HaxeFoundation/haxe#8951]
Hi, I just downloaded the 64-bit installer for Windows. Windows Security sees it as a potential Trojan for some reason.
![trojan](https://user-images.githubusercontent.com/5190228/68534331-64402f00-0301-11ea-8cb5-18fbfef68ade.png)
It immediately quarantined the .exe file.

I'm not sure if there is much to be done about this or just useful to report. 

Is there anyway to validate that the download has not been hijacked in anyway and that what I downloaded is the legit installer?

**Comment by ncannasse** [comment]
This is most likely a false positive from your A/V
We are working on solution to sign our binaries.

**Comment by Aurel300** [comment]
The related issue is #7720

**Comment by lucyllewy** [comment]
also once Haxe 4.0.1 is installed after bypassing the initial message above, smartscreen shows:

![image](https://user-images.githubusercontent.com/147548/68589717-91691a80-0484-11ea-9578-bb15caa959fc.png)

VirusTotal report for the installer: https://www.virustotal.com/gui/file/400e39aff07749ca2ed523839c8a1a267a9684a454fcafd6c30f774b8fa1dc3a/detection
VirusTotal report for the `haxesetup.exe` once Haxe is installed: https://www.virustotal.com/gui/file/8e6592f0433657d27baf6eef7e5ae3213cafbde540c7d6a6b0a537eb4b289253/detection

**Comment by RealyUniqueName** [comment]
We should provide checksums for our downloads.

**Comment by jonasmalacofilho** [comment]
> We should provide checksums for our downloads.

We absolutely should.

Unfortunately the results for `400e39aff07749ca2ed523839c8a1a267a9684a454fcafd6c30f774b8fa1dc3a` match the checksum from the binary installer at haxe.org/download or [releases/tag/4.0.1](https://github.com/HaxeFoundation/haxe/releases/tag/4.0.1).

```
$ curl -L https://github.com/HaxeFoundation/haxe/releases/download/4.0.1/haxe-4.0.1-win64.exe | sha256sum -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0    979      0 --:--:-- --:--:-- --:--:--   977
100 5779k  100 5779k    0     0  2210k      0  0:00:02  0:00:02 --:--:-- 4483k
400e39aff07749ca2ed523839c8a1a267a9684a454fcafd6c30f774b8fa1dc3a  -
```

: \

**Comment by Simn** [comment]
Checksums are a bit of a neckbeard thing, but I suppose in cases like this it's good to be able to double-check.

Regarding signed binaries, does this actually help here? I'd expect the virus signature to still match the executable, and I don't know if signing automatically prevents that.

**Comment by dmitryhryppa** [comment]
Once Haxe 4.0.1 is installed after bypassing antivirus warning I've checked installed Haxe executables. And here is a result of a `haxesetup.exe`:
https://www.virustotal.com/gui/file/8e6592f0433657d27baf6eef7e5ae3213cafbde540c7d6a6b0a537eb4b289253/detection
But `haxe.exe` and `haxelib.exe` seems clean. Hope it helps.

**Comment by SlavaRa** [comment]
4.0.2 https://www.virustotal.com/gui/file/27a39072603e55d5a0505688d586118a62f13082a63f3d32e8b5fccc9ecac87c/detection

**Comment by RealyUniqueName** [comment]
We can try to get rid of haxesetup.exe https://github.com/HaxeFoundation/haxe/issues/8870#issuecomment-547321975
