### ISSUE TITLE
[tre] remove redundant `continue`

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8952]
```haxe
function f() {
	trace("hi");
	f();
}
```
```js
f: function() {
	while(true) {
		console.log("src/Main.hx:6:","hi");
		continue;
	}
}
```
we don't need `continue` if the recursive call is the last expression

**Comment by nadako** [comment]
Also looked into this a bit and it's a bit tricky because we have to analyze branches, and since we do this anyway in the analyzer later, maybe it makes sense to clean up redundant `continue` (and `return` while were at it, see #6420) in a later pass, because, just like in https://github.com/HaxeFoundation/haxe/issues/8950#issuecomment-552621764, this can be written by hand as well, e.g:

```haxe
function f() {
	while (true) {
		trace("hi");
		if (g()) continue;
	}
}

inline function g() return true;
```

**Comment by RealyUniqueName** [comment]
Yes, it makes sense to do all kind of cleanups in the analyzer. However, see https://github.com/HaxeFoundation/haxe/issues/8953#issuecomment-552830065
