### ISSUE TITLE
Old extends Dynamic approach can't be accomplished with Abstract

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#8957]
I'm migrating Haxe 3 code to Haxe 4. Previously, I was extending Dynamic, which enabled me to call a function on a descendant class with just a reference to the parent.

Now I try to accomplish the same thing using an abstract, and it almost works, but not for calls. The problem is that I'm directly calling the object returned by `_getValue()` so it has no context for execution, causing an error when I try to access a local class member.

I think I would have no problem if I could overload the call `()` operator somehow. Then I could use `Reflect.callMethod()`. I can't find a way to do this, however.

Hopefully the following code is self explanatory. I'm duplicating this error on Haxe 4.0.1 on the JS target.

Running the following code on Chrome throws the error ```Uncaught TypeError: Cannot read property 'count' of undefined```

```haxe
abstract Abstract(Base) from Base to Base
{
   @:op(a.b) function get(field:String):Dynamic
   {
      return this._getValue(field);
   }
}

class Base
{
   public function new() { }

   public function _getValue(name:String):Dynamic
   {
      return Reflect.getProperty(this, name);
   }
}

class Extension extends Base
{
   private var count:Int = 0;

   public function echo():Void
   {
      count++;
      trace('Hello world! x $count');
   }
}

class Main
{
   public static function main()
   {
      var thing:Abstract = new Extension();

      thing.echo();
   }
}
```

**Comment by RealyUniqueName** [comment]
I don't think we have something to do here.
`Reflect.getProperty`/`Reflect.field` do not make any promises regarding binding a context if requested field is a method.
You can change your code like this:
```haxe
   public function _getValue(name:String):Dynamic
   {
      var value = Reflect.getProperty(this, name);
      #if js
      //$bind is generated by Haxe compiler in the compiled js file.
      if(Reflect.isFunction(value)) {
        value = untyped __define_feature__("use.$bind", js.Syntax.code("$bind({0}, {1})", this, value));
      }
      #end
      return value;
   }
```
But that could also affect `var` fields with function values like `var fn:Int->Void`.
In the end it's always better to avoid reflection.

**Comment by ckentgeorge** [comment]
Hey, this actually works well in my situation and is a truly Haxe-unique kind of solution. Thanks for the quick response!
