### ISSUE TITLE
Can't download haxe 4.0.1, windows 10 antivirus didn't like 64-bit installer

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#8958]
Hi there, 
Windows 10 antivirus do not allow me to download the 64-bit version of Haxe 4.0.1 installer:

![image](https://user-images.githubusercontent.com/4466595/68601681-7959c100-04ad-11ea-96a6-29a1f8d833f2.png)

![image](https://user-images.githubusercontent.com/4466595/68601667-6f37c280-04ad-11ea-876e-ab84936d6e28.png)

Haxe 4.0.1 -> 32-bit installer downloads ok
Haxe 4.0.0 -> 32 & 64 ok too

**Comment by Simn** [comment]
#8951
