### ISSUE TITLE
[analyzer] over-optimization of not-really constant locals

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8959]
```haxe
enum List<T> {
	Cons(element:T, next:List<T>);
	Nil;
}
class Main {
	static function main() {
		var list = Cons(1, Cons(2, Cons(3, Nil)));
		var acc = 0;

		while (true) {
			switch list {
				case Cons(element, next):
					list = next;
					acc = acc + element;
				case Nil:
					break;
			}
		}

		trace(acc);
	}
}
```

with `-D analyzer-optimize` will generate:
```js
var list = List.Cons(1,List.Cons(2,List.Cons(3,List.Nil)));
var acc = 0;
while(true) {
	list = list.next;
	++acc;
}
```

**Comment by nadako** [comment]
Also if we change the `while` condition to something like `a < 10`, we'll get even more optimized version (now with a `trace` \o/):
```js
var acc = 0;
while(acc < 10) ++acc;
console.log("src/Main.hx:43:",acc);
```

**Comment by nadako** [comment]
Haxe 3 [behaves the same](https://try.haxe.org/#e68d8)

**Comment by Simn** [comment]
I'm very surprised that this hasn't come up before. I suppose nobody is actually using `-D analyzer-optimize`. Normal people would conclude that bugs like this suggest that we shouldn't make it the default yet, but let's not be normal.

**Comment by nadako** [comment]
I mean, this is quite an artificial example with constant enums. But yeah I guess people who use enums extensively and people who use the optimizer are different sets of users :)
