### ISSUE TITLE
[hl ] Uncaught exception Bytes.alloc(1024 * 1024*1024)

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8960]
Bytes.alloc(1024 * 1024*1024)

hxcpp:test ok

hl: required memory allocation too big

**Comment by ncannasse** [comment]
HL max memory for a single block is little less than 1GB ( 255 * 2^22 ), this will be changed with a new GC or can be manually edited in alloc.c to increase GC_SIZES
