### ISSUE TITLE
[cs ]Type not found : cs.system.data.IDbConnection

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8961]
/usr/local/share/haxe/std/cs/_std/sys/db/Sqlite.hx:26: characters 24-52 : Type not found : cs.system.data.IDbConnection

   .net 2.0

![image](https://user-images.githubusercontent.com/748320/68646727-f12ff600-0556-11ea-8669-350d67997f5f.png)

**Comment by RealyUniqueName** [comment]
I don't see any references to `IDbConnection` in cs Sqlite implementation.
What's the text on line 26 in file `/usr/local/share/haxe/std/cs/_std/sys/db/Sqlite.hx` in your system?

**Comment by kLabz** [comment]
What do _you_ have?

https://github.com/HaxeFoundation/haxe/blob/4.0_bugfix/std/cs/_std/sys/db/Sqlite.hx#L26

**Comment by RealyUniqueName** [comment]
Oh, I was looking into cpp implementation :)

**Comment by kLabz** [comment]
Hmm, seems like we missed some C# issues.
See #11551
