### ISSUE TITLE
Refactor ++/-- typing

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8963]
> I'm fine with merging this, though I think we should look into cleaning this up a bit at some point. It should be possible to abstract all this decrement/increment stuff into some subject; get; op; set; framework and use that for all access modes.

Simn ([here](https://github.com/HaxeFoundation/haxe/pull/8932#issuecomment-552856796))

**Comment by Simn** [comment]
I actually did this at some point! The code in `operators.ml` is now much cleaner.
