### ISSUE TITLE
No string interpolation after some macro manipulations

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#8966]
String interpolation does not occur if I use `ExprTools.iter` to modify `expr.pos`.

```haxe
package;

#if macro
import haxe.macro.Expr;
import haxe.macro.ExprTools;
import haxe.macro.MacroStringTools;
#end

class Main {
	
	static macro function test<T>(e: Expr): Expr {

		var r = macro $e;
		
		function traceCString(a: Expr): Void {
			switch(a.expr) {
				case EConst(CString(s, kind)):
					trace(ExprTools.toString(a), s, kind, MacroStringTools.isFormatExpr(a));
				default:
			}
		}
		
		function setPos(a: Expr): Void {
			traceCString(a); // 'foo$i',foo$i,SingleQuotes,true
			a.pos = e.pos;
			traceCString(a); // "foo$i",foo$i,SingleQuotes,false
			ExprTools.iter(a, setPos);
		}
		setPos(r);
		
		return r;
	}
	
	static function foo(t: String): String {
		return t;
	}
	
	static function main(): Void {
		
		var i: Int = 10;
// note that just `test('foo$i')` works as expected
		var t: String = test(foo('foo$i')); 
		trace(t);
	}
	
}
```
And this is the resulting js:
```js
	var t = Main.foo("foo$i");
	console.log("src/Main.hx:42:",t);
```
Tested with haxe 4.0.2.

**Comment by Aurel300** [comment]
Unfortunately string interpolation is currently determined by examining the expression position. I may be mistaken but I think this is because until recently we did not have the single/double quote string kinds.

**Comment by Simn** [comment]
Indeed

I tried changing that a while ago but ran into some issues with interpolated strings in macro arguments. The current implementation uses a hack to temporarily disable string interpolation there, which is not so easy to do when relying on the AST-level distinction of single/double-quotes.

**Comment by vladimirvelikov** [comment]
Hi all, 
Using 4.0.5, I just stumbled upon a similar issue (or is it the same?), where an expression created using SingleQuotes, appears with double quotes.
There's no manipulation through iter, whatsoever - just an attempt to manually create the following:

`function test(anInt:Int) trace('$anInt');`

using `EConst(CString("$anInt", SingleQuotes)) `

results in an expression with double quotes:

`function test(anInt:Int) trace("$anInt");`

Reading the discussion above I couldn't figure out whether this is a separate issue. I have a minimal repro case and I'm happy to open an issue, if so. If it's the same, sorry for bothering.

Thanks in advance!

**Comment by romamik** [comment]
> `function test(anInt:Int) trace('$anInt');`
> using `EConst(CString("$anInt", SingleQuotes)) `

You should use `MacroStringTools.formatString` for this. `isFormatExpr` is also of your interest.
