### ISSUE TITLE
Type.typeof (Refelct .filed ) is wrong. 

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8976]
![image](https://user-images.githubusercontent.com/748320/69021605-6128fb00-09f3-11ea-8c97-edfb510c07db.png)

  	@:struct
	class Player{
		
		public var id:Int;
		
		public function new(){
			
		}
		
	}

	class Main {
		static function main() {
		   
			
			var p = new Player();
		
			p.id = 1;
			var fs = Reflect.fields(p);
			
			for (f in fs){
				
				var v = Reflect.field( p,f);
				trace('f=$f v=$v type=${Type.typeof(f)}');
                      trace('f=$f v=$v type=${Type.typeof(v)}');//it's wrong , respect  Int got String.
			}
			
			
		}
	}

May be it's not a bug ,but how to get Int  instead of String?
target:hl ,cs

**Comment by back2dos** [comment]
Are you getting the same without `@:struct`?

**Comment by sonygod** [comment]
yes ,the result is same as without @:struct 

@back2dos

**Comment by back2dos** [comment]
In your code you trace `Type.typeof(f)`. However `f` is a field *name*, which is *always* a string. If you use `Type.typeof(v)`, it's more likely to work, but it's possible that `'f=$f v=$v '` makes the compiler infer `v` to be a string. You can use `var v:Dynamic = Reflect.field(p,f);` to avoid that.
