### ISSUE TITLE
[cs ]-D erase-generics is not support Null<T>

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8977]
[cs ]-D erase-generics is not support Null<T>

is this for design purpose?

**Comment by RealyUniqueName** [comment]
Provide a sample and error messages or detailed description of what's wrong

**Comment by sonygod** [comment]
package;



	@:struct
	class Player{
		
		 public var id:Null<Int>;
		
		public function new(){
			
		}
		
	}

	class Main {
		static function main() {
		   
			
			var p = new Player();
			
			p.id = 1;
			
			
			var p2 = new Player();
			
		
			
			
			
		
			
			
		}
	}

**Comment by sonygod** [comment]
-D erase-generics

![image](https://user-images.githubusercontent.com/748320/69053984-95c5a280-0a45-11ea-8a71-8da405abcc5e.png)

**Comment by sonygod** [comment]
without   -D erase-generics

![image](https://user-images.githubusercontent.com/748320/69054150-f654df80-0a45-11ea-9eeb-cab547ae8c77.png)

**Comment by RealyUniqueName** [comment]
I don't understand what do you mean by "not supported". It works fine with and without `-D erase-generics`. 
`Null` is needed here only to box an integer to make it possible to store a null value. 
With `-D erase-generics` it's just replaced with `object`, which doesn't change anything in terms of `Null<Int>` behavior at runtime.

**Comment by sonygod** [comment]
it's just replaced with object

I don't think it's good idea replace object 
because we use native csharp with haxe gen source ,we want to keep Null information

**Comment by Simn** [comment]
We are unlikely to fix this as the C# target currently doesn't have an active maintainer.

**Comment by kLabz** [comment]
Why would you use `-D erase-generics` if you intend to work with generated C# code? It seems obvious to me (maybe wrongly) that it wouldn't work perfectly.

**Comment by nadako** [comment]
fwiw for interoperating with C# one should use `cs.system.Nullable_1` anyway
