### ISSUE TITLE
[cs] >>= not work if without -D erase-generics

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8978]
```haxe
class Main {
		static function main() {
		   
			
			
			var value:cs.types.Int64= 1;
			value >>= 7;//-D erase-generics will compile ok 
			
			
		}
	}
```

**Comment by RealyUniqueName** [comment]
This is compiled to
```cs
long @value = ( (long) (1) );
@value >>= ( (long) (7) );
```
which is wrong, because `1` and `7` are typed as `Int` in AST. Removing those `(long)` fixes native compilation.

**Comment by sonygod** [comment]
https://github.com/darmie/binary128/blob/master/src/binary128/internal/cs/Leb128.hx#Line=35

**Comment by RealyUniqueName** [comment]
Works fine in 3.4.7, so it's a regression
