### ISSUE TITLE
[cs] cs  target Json. parse not support array.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#8979]
@:struct
        class Player{
            
            public var id:Null<Int>;
            
            public var arr:Array<Int>;
            
            public function new(){
                
            }
            
        }

        class Main {
            static function main() {
            
                
                var p = new Player();
                p.id = 1;
                p.arr = [1];
                
                var jp=Json.stringify(p);
                
                var rp2 = Json.parse(jp);//will throw error
                var p2 = new Player();
            
            }
        }

**Comment by RealyUniqueName** [comment]
Please, use markdown to format your messages: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

**Comment by RealyUniqueName** [comment]
Array is not an issue here. It throws an exception even if `Player` doesn't have any fields at all. But removing `@:struct` fixes it. 
Also it works if compiled with Haxe 3.4, so it's a regression.
