### ISSUE TITLE
Map is unifiable with Iterable as a cosntraint

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8984]
```haxe
class Main {
	static function main() {
		var m = [1 => 'hello'];
		iter(m);
	}

	static function iter<T:Iterable<String>>(m:T) {}
}
```
```
$ haxe -main Main
Main.hx:4: characters 3-7 : Constraint check failure for iter.T
Main.hx:4: characters 3-7 : haxe.ds.Map<Int, String> should be Iterable<String>
```

**Comment by Simn** [comment]
Abstracts don't unify with structures in general. It makes no sense because abstract field access has to be resolved at compile-time, which isn't possible if you hide it behind a structure.

**Comment by RealyUniqueName** [comment]
But if an abstract has `@:to Iterable` this works:
```haxe
class Main {
	static function main() {
		var m = [1 => 'hello'];
		iter(m);
	}

	static function iter<T>(m:Iterable<T>) {}
}
```

**Comment by RealyUniqueName** [comment]
Also, it works with and without a constraint for non-multiType abstracts with `to Iterable`

**Comment by Simn** [comment]
I'm confused what exactly you're reporting here because `Map` has no `@:to Iterable`.

**Comment by RealyUniqueName** [comment]
but it has `@:to IntMap` and friends which unify with `Iterable`.

I'm reporting that `function iter(m:Iterable<String>)` works, but `function iter<T:Iterable<String>>(m:T)` does not.

**Comment by Simn** [comment]
> but it has `@:to IntMap` and friends which unify with `Iterable`.

That would be a transitive cast.

> I'm reporting that `function iter(m:Iterable<String>)` works, but `function iter<T:Iterable<String>>(m:T)` does not.

This is due to the delayed nature of both constraints checks and multitype-selection. Field-casts require transforming the expression early, which conflicts with delayed unification. I wouldn't try to change this with the current way of handling constraints. Maybe we can resolve it if I ever get around to implementing constrained monomorphs properly.

**Comment by RealyUniqueName** [comment]
> That would be a transitive cast.

I don't think so. `IntMap` does not require a cast to unify with `Iterable`

**Comment by Simn** [comment]
Yes but `Map` isn't `IntMap`. You would have to go `Map` to `IntMap` and then `IntMap` to `Iterable`, which is transitive.

I strongly encourage not touching this with the current implementation of `Map`, but if you like to suffer I won't stop you.

**Comment by Simn** [comment]
This works with #9549.

I... guess that's good?

**Comment by RealyUniqueName** [comment]
That's super great!
It would allow me to finish the work I mentioned in https://github.com/HaxeFoundation/haxe/pull/8848 :
> If this PR is accepted I'll make another one which will make Lambda methods allocation-free
