### ISSUE TITLE
tre gens endless loop on self modifying dynamic function

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#8989]
I use this pattern very often for lazy loading of library function.

```haxe
class Main {
	static dynamic function morph(): Int {
		morph = function () return 1;
		return morph();
	}

	static function main() {
		trace(morph());
	}
}

```

this creates an endless loop now

```js
Main.morph = function() {
	while(true) {
		Main.morph = function() {
			return 1;
		};
		continue;
	}
};

```

**Comment by AdrianV** [comment]
same problem when I use a var instead of a dynamic function

```haxe
	static var morph2 = function () {
		morph2 = function () return 1;
		return morph2();
	}
```

**Comment by RealyUniqueName** [comment]
Out of curiosity: what kind of a target/library do you use, which makes sense to load it lazily?

**Comment by AdrianV** [comment]
mainly in neko to bind to native code in the host application. But I found this in a JS code where the code adopts depending where the target runs: Browser, Phonegap or internal viewer. So i need lazy loading because I can only decide at runtime what to do.

**Comment by RealyUniqueName** [comment]
Thanks

**Comment by Simn** [comment]
That's an interesting pattern, for some reason I never had the idea to have a dynamic function that modifies itself.

**Comment by AdrianV** [comment]
I thought this is the main reason why dynamic functions exists :)
