### ISSUE TITLE
Function name is not reported in error

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8997]
Many errors will show a line like:

```
Main.hx:3: characters 10-14 : For function argument 'v'
```

This is not very helpful. Many standard library functions have single-letter argument names, which makes the error a bit more cryptic still. The error should at least include the name of the function, i.e.:

```
Main.hx:3: characters 10-14 : For function argument 'v' of function 'trace'
```

**Comment by Simn** [comment]
We can look into this but it should be low priority. I'm worried that this might require some architectural changes because the call argument resolution doesn't generally know what the call subject is.

**Comment by RealyUniqueName** [comment]
I believe this is no longer relevant after  48d5e79f8c211c590b5056f25af8a7e9cd3696af
