### ISSUE TITLE
Unable develop with Xamarin.Android with cs target

### ISSUE THREAD

**Issue by joydance** [HaxeFoundation/haxe#8998]
I want to try to develop an app with Xamarin.Android and haxe cs target. But when I add all the neccessary --net-lib and compile it, the compiler tell me an erorr that it can't access java package in cs target, which is referenced in the Xamarin.Android. Is there any solution to ignore this compiler limitation?

**Comment by Gama11** [comment]
`--macro allowPackage('java')` might help.

**Comment by joydance** [comment]
> `--macro allowPackage('java')` might help.

Yes, it's passed! Thank you! :)
