### ISSUE TITLE
allowPackage("java") but java.lang.Comparable not found

### ISSUE THREAD

**Issue by joydance** [HaxeFoundation/haxe#8999]
I want to develop a Xamarin.Android with haxe cs target, and there are many java refrences, so I add --macro allowPackage("java") in the hxml file. But the compiler complaint like this: "Type not found : java.lang.Comparable", is there any solution I can accesss the java classes freely without any limitation when I want cs target?

**Comment by RealyUniqueName** [comment]
`java.lang.Comparable` is a part of `hxjava` library. Try `-lib hxjava`. But it was created for the java target. I'm not sure if it won't throw compilation errors while targeting cs.

**Comment by RealyUniqueName** [comment]
That sounds wrong.
How does Xamarin allow you to access java classes in C# code? If `hxjava` won't rok for you, you will need to create correct externs by yourself.

**Comment by Gama11** [comment]
There's probably some C# .dll that has the Java type definitions, if it needs those?

**Comment by joydance** [comment]
> That sounds wrong.
> How does Xamarin allow you to access java classes in C# code? If `hxjava` won't rok for you, you will need to create correct externs by yourself.

I've try to add -lib hxjava, but the compiler throw an exception "PeReader.Error_message("MZ magic header not found: Is the target file really a PE?")" :(

**Comment by joydance** [comment]
> There's probably some C# .dll that has the Java type definitions, if it needs those?

Yes, that's true.

**Comment by RealyUniqueName** [comment]
Then you need to `--net-lib path/to/dll` instead of `-lib hxjava`

**Comment by joydance** [comment]
> Then you need to `--net-lib path/to/dll` instead of `-lib hxjava`

Actually, all the definition is defined in Mono.Android.dll, and they are something externs, which have the native class name in the meta like this: 

`[Android.Runtime.Register("java/lang/Comparable", "", "Java.Lang.IComparableInvoker", ApiSince=1)]
[Java.Interop.JavaTypeParameters(new System.String[] { "T" })]
public interface IComparable : Android.Runtime.IJavaObject, IDisposable`

(https://docs.microsoft.com/en-us/dotnet/api/java.lang.icomparable?view=xamarin-android-sdk-9)



So the problem is that when add allowPackage("java"), the haxe compiler seem to use the interface from hxjava, not from Mono.Android.dll? Because the compile throw an exception like this: "Type not found : java.lang.Comparable".

**Comment by RealyUniqueName** [comment]
If you have `-lib path/to/Mono.Android.dll` and don't have `-lib hxjava` then that should not be the case.

**Comment by Simn** [comment]
`-lib hxjava` should only be used in conjunction with `-java`. It's not going to work when targeting something else.

**Comment by joydance** [comment]
> `-lib hxjava` should only be used in conjunction with `-java`. It's not going to work when targeting something else.
the error is like this: 

/usr/local/lib/haxe/std/java/lang/Character.hx:35: characters 72-93 : Type not found : Comparable

And the code in  /usr/local/lib/haxe/std/java/lang/Character.hx: 
@:native("java.lang.Character") extern class CharacterClass implements Comparable<Character>

Maybe it's beacause Character.hx refrence Comparable, but Comparable exists only in hxjava, but not in haxe std?

Or becase it's not include in haxe installer?
https://github.com/HaxeFoundation/haxe/blob/development/std/java/lang/Comparable.hx

**Comment by RealyUniqueName** [comment]
Have you added `-lib path/to/Mono.Android.dll` to compilation arguments?

**Comment by Gama11** [comment]
@RealyUniqueName I think you mean `--net-lib`?

**Comment by joydance** [comment]
> @RealyUniqueName I think you mean `--net-lib`?

Yes, I have.

**Comment by RealyUniqueName** [comment]
That may be related to the order of classpaths/libs. Perhaps `java.lang.Character` should be taken from your dll, but the one in std shadows it.
If you could assemble a minimal sample, I could try to find the reason.

**Comment by joydance** [comment]
> That may be related to the order of classpaths/libs. Perhaps `java.lang.Character` should be taken from your dll, but the one in std shadows it.
> If you could assemble a minimal sample, I could try to find the reason.

Yes, here is the sample project:
https://github.com/joydance/HXmarinAndroid

**Comment by RealyUniqueName** [comment]
Meanwhile as a workaround you can remove or rename "java" directory in the standard lib while working with that project.

**Comment by RealyUniqueName** [comment]
Also, instead of `--net-lib /usr/local/lib/haxe/lib/hxcs/3,4,0/netlib/net-40/mscorlib.dll` you can do just `-D net_ver=40`

**Comment by RealyUniqueName** [comment]
As I suspected dll is used only if file system does not contain the requested module:
https://github.com/HaxeFoundation/haxe/blob/322f9cdcae45cd5673dc6d63d18df98ba0243325/src/typing/typeloadModule.ml#L971-L974
https://github.com/HaxeFoundation/haxe/blob/322f9cdcae45cd5673dc6d63d18df98ba0243325/src/typing/typeloadModule.ml#L981-L983

I tried following things to workaround the issue:

### Change resolution order
Try native libs before classpaths.

This works, but breaks `haxe.macro.Context.onTypeNotFound()` because it relies on the current resolution order.

### Load all types from `--net-lib` into a custom package 
E.g. `--net-lib libs/Java.Interop.dll@mypack`.

This doesn't work because any other lib loaded via `--net-lib` is not aware about the package change:
```hxml
--net-lib libs/Mono.Android.dll
--net-lib libs/Java.Interop.dll@mypack
```
`Mono.Android.dll` refers to `java.lang.Character` this breaks the compilation because it's `mypack.java.lang.Character` now.

**Comment by kLabz** [comment]
Could `--remap` be updated to support `--remap std.java:stdjava`?

**Comment by RealyUniqueName** [comment]
I don't understand how would that solve shadowing of dll types by std types.

**Comment by joydance** [comment]
> I don't understand how would that solve shadowing of dll types by std types.

I try to rename "java" directory in the standard lib, and add  -D net_ver=45, and the compiler finally passed. 
But when I continue to extends an Activity class, other issues come out. So I think I should stop to try to develop Xamarin with haxe now. :)  
Anyway, many thanks.
