### ISSUE TITLE
4.0.3 Windows install issue

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/haxe#9001]
Install 4.0.3 on Windows 8.1 64 bit issue. Unknown Publisher. 4.0.2 works
![image](https://user-images.githubusercontent.com/1771547/69886111-679a5b00-12ae-11ea-8b75-49994ad309f7.png)

**Comment by codeservice** [comment]
Better screenshot

![image](https://user-images.githubusercontent.com/1771547/69886364-9fee6900-12af-11ea-961b-a27347762b6d.png)

**Comment by RealyUniqueName** [comment]
Duplicates #7720
