### ISSUE TITLE
verbose abstract js naming, repeated name? Minor.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9003]
Noticed abstract having rather verbose names with lots of ugly '$' and the abstracts name repeated.
``` js
var flat__$Float32FlatRGBA_Float32FlatRGBA_$Impl_$ = {};
```
generated source:
https://github.com/nanjizal/Flat/blob/master/trial0/bin/test.js#L111
abstract concerned:
https://github.com/nanjizal/Flat/blob/master/src/flat/Float32FlatTriangle.hx#L7

not critical, mainly relevant in terms of outward impression for js developers. Probably not worth modifying unless easy ( Haxe Compiler 4.0.2 ).

It easily results in code that is nasty to read...
``` js
var this3 = new geom_structure_Mat1x4(flat__$Float32FlatTriangle_Float32FlatTriangle_$Impl_$.get_bx(this1),flat__$Float32FlatTriangle_Float32FlatTriangle_$Impl_$.get_by(this1),flat__$Float32FlatTriangle_Float32FlatTriangle_$Impl_$.get_bz(this1),1.);
```

**Comment by back2dos** [comment]
I wonder if it'd make sense to use `flat_Float32FlatTriangle` as class name in the generator. Since the abstract "occupies" that type path at compile time, it's safe to assume there's no class that could clash with it at runtime.

FWIW it can already be accomplished in a macro (typos ahead):

```haxe
Context.onGenerate(function (types) {
  for (t in types) switch t {
    case TInst(_.get() => cl = { kind: KAbstractImpl(_.get() => a) }, _):
      var name = a.pack.concat([a.name]).join('.');
      cl.meta.add(':native', [macro $v{name}], a.pos);
    default:
  }
});
```

Still, unless this causes problems, I think it'd be good to make this the default.

**Comment by RealyUniqueName** [comment]
I agree it could be just `flat_Float32FlatTriangle`.
But at all the compilation steps it should have a separate type path. Otherwise it may clash with the abstract itself in some situations during compilation.
So, maybe it's up to generators to decide on the final paths of abstracts implementations.

**Comment by nadako** [comment]
This is something I've thought about after showing people some abstract-generated code at the luxembourg haxeup. I think we can and should do this in genjs, although there might be some cases that we have to be careful about with @:coreTypes and whatnot (not sure which cases exactly atm).

**Comment by nanjizal** [comment]
Another **"Abstract JS"** aspect that has been playing on my mind, is related to the problem of generating libraries for Javascript developers where you may need your abstracts remapped to a class implementation, but operations are not something classes support so I am not sure how it might work, but currently I can't easily publish a JS library of some of my code because it relies on Haxe compiler doing magic with Abstracts, for JS users I don't really care... they can have snail version but do I implement separate version for them with a  #if snail_js_version switch between class and abstract implementations or can compiler provide -D no-Abstract feature?

If you feel it's something that I should open as evolution ( may need assistance with outlining proposal ) or just as an issue then let me know, again not really important to me specifically as my needs are not critical, but useful in enabling more Haxe JS use. Sorry - I know totally off topic and perhaps too messy or specialist to contemplate, but yer feel free to ignore if not interesting.
