### ISSUE TITLE
[cpp] String.lastIndexOf not working as expected in Haxe 4

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#9007]
After upgrading to Haxe 4 I was faced with some unexpected behaviors on the CPP target. I could strip one of the issues down to the following code:

```haxe
class Test {
    static function main() {
        var word1 = "FooBar";
        var word2 = StringTools.replace(word1, "oe", "ö"); // this should be a no-op because "oe" is not present in word1

        trace('word1: "$word1"');
        trace('word2: "$word2"');
        trace('word1 == word2: ' + (word1 == word2));
        trace("word1.lastIndexOf(\"Foo\"): " + word1.lastIndexOf("Foo"));
        trace("word2.lastIndexOf(\"Foo\"): " + word2.lastIndexOf("Foo"));
    }
}
```

which results in
```haxe
word1: "FooBar"
word2: "FooBar"
word1 == word2: true
word1.lastIndexOf("Foo"): 0
word2.lastIndexOf("Foo"): -1
```

so for some reason `lastIndexOf` does not work correctly anymore after `StringTools.replace()` was applied.

**Comment by jcward** [comment]
Hey, if you're thinking about CPP String issues, can you check out #8457. If not fixing `cpp.Lib.stringReference`, then perhaps just patching [`sys.ssl.Key.loadFile`](https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/_std/sys/ssl/Key.hx) to not use StringReference.

**Comment by sebthom** [comment]
The issue is not reproducible anymore with latest Haxe version.
