### ISSUE TITLE
c# Runtime.genericCast slower than direct cast

### ISSUE THREAD

**Issue by dyarosla** [HaxeFoundation/haxe#9020]
C# does a lot of implicit casts from `Array<object>` to `Array<T>` and back. This is fine normally. Problem is (as far as I can tell) that the Runtime.genericCast method creates quite a bit of overhead (~3x)

Runtime has this:
```
public static To genericCast<To>(object obj) {  
  if (obj is To)
    return (To) obj; 
  else if (obj == null)
    return default(To);
  if (typeof(To) == typeof(double))
    return (To)(object) toDouble(obj);
  else if (typeof(To) == typeof(int))
    return (To)(object) toInt(obj);
  else if (typeof(To) == typeof(float))
    return (To)(object)(float)toDouble(obj);
  else if (typeof(To) == typeof(long))
    return (To)(object)(long)toDouble(obj);
  else
    return (To) obj; 
}
```

And even if we simplify to the basic
```
public static To genericCast<To>(object obj)
{
  return (To)obj;
}
```

And compare usage of (A)
```
doSomething(genericCast<T>(obj));
```
vs (B)
```
doSomething((T)obj);
```

The time spent on (A) is ~3x larger.

Is there a reason to be calling `Runtime.genericCast<T>` in things like Array.cs instead of simply casting to (T)?

**Comment by RealyUniqueName** [comment]
I guess it's because of the additional checks carried on `genericCast`: 
https://github.com/HaxeFoundation/haxe/blob/ca6a5841fc20e22d7e74009c31852b9fb097dda5/std/cs/internal/Runtime.hx#L653-L671

**Comment by RealyUniqueName** [comment]
I guess it's because `genericCast<T>(value)` has different semantics than just `(T)value`.
Maybe @waneck could give a hint.
I'll take a closer look in the nearest future.

**Comment by Simn** [comment]
C#-specific optimizations problems like this are unlikely to be addressed, closing accordingly.
