### ISSUE TITLE
NEKOPATH env var not set after fresh install on Windows 10 ("missing neko.dll")

### ISSUE THREAD

**Issue by benblo** [HaxeFoundation/haxe#9021]
I just installed Haxe 4.0.3 for the first time ever, using the Win64 installer from the official site (https://haxe.org/download/file/4.0.3/haxe-4.0.3-win64.exe/), I did not use the suggested install path (C:\HaxeToolkit) but instead C:\Work\Haxe\HaxeToolkit.

Opened a terminal, ran haxe: not found, haxelib: not found. I navigated to the install path, saw the haxe subfolder, ran haxe from there: ok, ran haxelib: got a "missing neko.dll" error. 
Went to the neko folder, ran neko: ok.

Rebooted my PC, opened a terminal, ran haxe: ok, it's found now (the HAXEPATH env var must need a restart to properly propagate... meh), but when I ran haxelib I still got a "missing neko.dll" error.

So I manually set NEKOPATH = C:\Work\Haxe\HaxeToolkit\neko, then added %NEKOPATH% to PATH, rebooted again... finally, haxelib runs!

Not a big deal, but not a great first-time experience either :/ ...

**Comment by RealyUniqueName** [comment]
What's your windows version? 
Did you run the installer with admin privileges or did it ask the permission during the installation?

**Comment by RealyUniqueName** [comment]
Ok, I've found the reason. Fix incoming.
Thanks for the report.

**Comment by sugoidogo** [comment]
> So I manually set NEKOPATH = C:\Work\Haxe\HaxeToolkit\neko, then added %NEKOPATH% to PATH, rebooted again... finally, haxelib runs!

I found that `%NEKO_HOMEPATH%` was set and in the path, renaming it and its path entry to `%NEKOPATH%` fixed it for me.

**Comment by N1ckn1ght** [comment]
Still had similar issue - **I wasn't able to run haxelib**, but it was %NEKO_INSTPATH% that was set.

The more interesting thing is that **I was able to run haxelib before rebooting my machine**, but not afterwards.

Tried to fix this problem simply by reinstalling Haxe, but **it was just recreated** again.

After **I manually created %NEKOPATH% variable** with the same path, this problem was solved.
