### ISSUE TITLE
ObjectMap bug, js

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/haxe#9026]
```haxe
class Test {
    static function main() {
        var key = {};
        var map: Map<{}, Int> = new Map();
        map[key] = 10;
        map[key] = 20;
        trace(map);
    }
}
```
outputs: 
```
{{
	__id__ : 1
} => 20, {
	__id__ : 1
} => 20}
```

This is because in `ObjectMap.hx` first `assignId` returns `0`, which is treated as false in next call to expression `getId(key) || assignId(key)` and `assignId` is called again on the same object.
Tested with haxe 4.0.3.

**Comment by Simn** [comment]
-_-

**Comment by kLabz** [comment]
Worked with 3.4.4 (try.haxe.org)
