### ISSUE TITLE
Compilation server: inlined empty function

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/haxe#9029]
Create `src` folder with these files:
`Main.hx`:
```haxe
class Main {
	static function main() {
		final game = new Game();
	}
}
```
`Screen.hx`:
```haxe
class Screen {
	public function new() {
		_onUpdate();
	}

	inline function _onUpdate():Void {
		_onStart();
	}

	inline function _onStart():Void {
		onStart();
	}

	function onStart():Void {}
}
```
`Game.hx`:
```haxe
class Game extends Screen {
	override function onStart() {
		// trace(123);
	}
}
```
Create `build.hxml`:
```hxml
-cp src
-D analyzer-optimize
-js bin/main.js
-dce full
-main Main
```
Start server: `haxe -v --wait 6000`
Compile: `haxe --connect 6000 build.hxml`
Uncomment `trace(123);` in `Game.hx`
Compile again: `haxe --connect 6000 build.hxml`
You will get empty Main.main function generated in js file.
`new Game();` instead of `final game = new Game();` has different output, but bugged too.
Project: [compserver.zip](https://github.com/HaxeFoundation/haxe/files/3956720/compserver.zip)
Haxe 4.0.3, 4.0.0

**Comment by RblSb** [comment]
Alternative version, i guess this bug is not related to inlines:
`Screen.hx`
```haxe
class Screen {
	public function new() {
		onStart();
	}

	function onStart():Void {}
}
```
Other files and steps to reproduce are same.

**Comment by RealyUniqueName** [comment]
I can reproduce it with 4.0.5
But with the latest development I get a compilation error:
```
src/Game.hx:2: lines 2-4 : Impure field overrides/implements field which was explicitly marked as @:pure
src/Screen.hx:6: characters 2-28 : Pure field is here
```
Which the same as #9238

**Comment by RealyUniqueName** [comment]
`inline` functions should not be allowed to override in the first place.
But the second version of `Screen.hx` makes me think that analyzer does not check if `onStart` is overridded.

**Comment by Simn** [comment]
> inline functions should not be allowed to override in the first place.

Huh, I thought this was disallowed already...

**Comment by RealyUniqueName** [comment]
I checked and it is. Idk how did @RblSb managed to compile that.

**Comment by RealyUniqueName** [comment]
False alarm. I got confused by `_onStart` and `onStart`.
Back to the purity investigation.

**Comment by RealyUniqueName** [comment]
Reopening because of this: https://github.com/HaxeFoundation/haxe/commit/752edad5ab9d60997513d5b4033ad40df5a1be63#r37949526
