### ISSUE TITLE
Type.createInstance fails on Java for defaulted arguments

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#9031]
This is a regression from Haxe 3. The following code builds with Haxe 4.0.3 but crashes with `Exception in thread "main" Haxe Exception: Could not find any constructor that matches the provided arguments for class class haxe.root.Main` when run.

```
class Main
{
   public static function main()
   {
      Type.createInstance(Main, []);
   }

   public function new(message:String = "Testing")
   {
      trace(message);
   }
}
```

**Comment by RealyUniqueName** [comment]
This is unspecified, so you should not rely on it.
Here is the quote from `Type.createInstance()` doc:
> If cl or args are null, or if the number of elements in args does not match the expected number of constructor arguments, or if any argument has an invalid type, or if cl has no own constructor, the result is unspecified.
>
> In particular, default values of constructor arguments are not guaranteed to be taken into account.

**Comment by ckentgeorge** [comment]
It worked on Haxe 3 and the hscript library depends on it.

**Comment by jonasmalacofilho** [comment]
Additionally:

> Default values of constructors arguments are not guaranteed to be taken into account.

I agree that this is unfortunate for scripting applications (e.g. using hscript).  Do all other targets correctly handle this on Haxe 4?

**Comment by ckentgeorge** [comment]
We've only verified that it works on C++ and Javascript and not on Java.

**Comment by RealyUniqueName** [comment]
Could you please provide a sample, which works without any exceptions in Haxe 3.4?
The sample above throws a null pointer exception with Haxe 3.4.7.

**Comment by ckentgeorge** [comment]
I rolled back to do additional testing, and I think I spoke too hastily; I'm seeing this fail on Haxe 3 as well. Does the cost/benefit not measure up for this being cross-platform? I have found a work-around for my particular situation.

Thanks for taking the time to look into this!

**Comment by RealyUniqueName** [comment]
I think we should not fix it. 
It's clearly stated in the doc that this case is unspecified. It was unspecified because for some targets it's impossible or very costly to implement it. And If we start improving it, it's more likely people will rely on it making their code non-portable across targets.
