### ISSUE TITLE
Calling Dynamic callback fails on Java with defaulted arguments

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#9032]
The following code builds with Haxe 4.0.3 but crashes with `Exception in thread "main" java.lang.IllegalArgumentException: Wrong number of arguments` when run. Java crashes, C++ does not.

```
class Main
{
   public static function main()
   {
      var m = new Main();
      m.callback = cast (message = "Hello world!") -> trace(message);
      m.callback();
   }

   public var callback:Dynamic;

   public function new() {}
}
```

**Comment by Simn** [comment]
Going forward, we will not be spending much time and effort on fixing Java-specific problems. I have confirmed that this case works on the JVM target.
