### ISSUE TITLE
AST from Context.parse() won't use setters

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/haxe#9038]
So, this seems to be consistent behavior between Haxe 3.4.7 and Haxe 4.0.3, but it is unexpected and not mentioned in documentation.
In the following code, I use a setter to trace out a message when a property is assigned a value. This works fine when accessed directly, but if accessed via code generated by `Context.parse()` and assigned in a macro, the setter is bypassed.

If this is expected behavior, I think it needs to be added to the caveats in the documentation for `Context.parse()`.

```
package;
import haxe.macro.Context;
import haxe.macro.Expr;

@:autoBuild(MainMacro.build())
class Main
{
   public static function main():Void
   {
      var main = new Main();

      trace("This reports:");
      main.value = true;

      trace("This should report but doesn't:");
      main.clear();
   }

   public function new() {}

   public function clear():Void {}
   
   public var value(default, set):Bool;
   private function set_value(value:Bool):Bool
   {
      this.value = value;
      trace('   Value set to $value');
      return value;
   }
}


class MainMacro
{
   macro public static function build():Array<Field>
   {
      var fields = Context.getBuildFields();
      for (field in fields)
      {
         switch (field.name)
         {
            case "clear":
               switch (field.kind)
               {
                  case FFun(f):
                     f.expr = Context.parseInlineString("{ value = false; }", Context.currentPos());
                  default:
                     // Do nothing.
               }
            default:
               // Do nothing.
         }
      }
      return fields;
   }
}
```

**Comment by nadako** [comment]
That cannot be the case, as `Context.parse/parseInlineString` produces the same AST as one would've written by hand or by using [macro reification](https://haxe.org/manual/macro-reification.html) (which is more efficient and recommended btw).

I had to move `MainMacro` into a separate module, and replace `@:autoBuild` with `@:build` so it actually runs on the `Main` class, and I get the expected output, e.g. on JS:
```js
clear: function() {
	this.set_value(false);
}
```

So I'm afraid you're going to have to provide a proper example ^^

**Comment by ckentgeorge** [comment]
@nadako, you're correct. It seems I wrote a self-fulfilling prophecy. I'll check back in after I get to the root of what is really happening in my use-case.

**Comment by ckentgeorge** [comment]
Okay, so I totally fired a false alarm regarding `Contex.parse()`... (can it ever forgive me?) The real issue I was running into is that setters don't seem to be respected when accessing the owning object as `Dynamic`. In the code below, I am expecting the message "Value set to X" to appear twice. Once for `true` and once for `false`, but I only get the first one.

Now this is a very different bug, but before I go generate another bogus bug report, am I correct in expecting this to work?

```
class Main
{
   public static function main():Void
   {
      var main = new Main();

      trace("This reports:");
      main.value = true;
      trace('main.value = ${main.value}');

      trace("This should report but doesn't:");
      var me:Dynamic = main;
      me.value = false;
      trace('main.value = ${main.value}');
   }
   
   public var value(default, set):Bool;
   private function set_value(value:Bool):Bool
   {
      this.value = value;
      trace('   Value set to $value');
      return value;
   }

   public function new() {}
}
```

**Comment by ncannasse** [comment]
Accessing fields as Dynamic does not give cross platform guarantee that the setter will be called. Actually there is much more chance it _won't be_. You can use Reflect.setProperty to trigger the setter.
