### ISSUE TITLE
[Fault] exception, information=SyntaxError: Error #1132: Invalid JSON parse input. SWF

### ISSUE THREAD

**Issue by yohiphopja** [HaxeFoundation/haxe#9041]
Hello. When testing in swf, it gives a parsing error. I realized that this is due to the large amount of data, because in html everything works and the object is parsed. How can this be fixed?

**Comment by RealyUniqueName** [comment]
Provide a reproducible sample, please.

**Comment by RealyUniqueName** [comment]
@yohiphopja Have you managed to solve your issue?

**Comment by RealyUniqueName** [comment]
Closing due to lack of feedback and the initial message does not provide enough data to understand the issue.
