### ISSUE TITLE
[display] Goto Implementation

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9043]
Language Server Protocol (and VS Code) supports ["Goto Implementation"](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_implementation) feature. While I'm not sure what exactly it was designed for, to me it looks like something that could be used for the following things:

 - find child classes
 - find interface implementations
 - find method overrides
 - find interface field implementations

From the compiler standpoint to me this looks similar to "find references", so maybe it's not very hard to implement?

I can see this feature being very handy for us at @innogames, because we have quite an inheritance-heavy codebase and we often need to get an overview of what's going on across class hierarchies.

**Comment by nadako** [comment]
BTW I just checked how TypeScript employs this feature and it does exactly what I described here, so I guess that was the indeed the intent.

**Comment by Simn** [comment]
@RealyUniqueName Do you remember if `cl_descendants` can be relied upon for display purposes? I know we changed this a bit but I'm not sure what the current state is.

**Comment by RealyUniqueName** [comment]
I think, we can't rely on it for display. 
`cl_descendants` is populated upon filters step.

**Comment by Simn** [comment]
This indeed looks like it could be solved by using the statistics module with a different filter function afterwards.

I can work on the Haxe side, but as usual I'm unable to compile vshaxe so somebody else has to set that up.
