### ISSUE TITLE
[display] Find references vs method overrides

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9044]
Currently, "find references" requests only finds exact method calls, not including superclass/interface method calls in case of virtual method overriding. So with subclassing/interfaces, you often have to travel through the inheritance chain and do "find references" for the same method several times.

I understand that the current behaviour also might be desirable, so I think this should be somehow configurable. For example, IIRC, IntelliJ provides a selection on whether you want to see exact matches or include all the virtual calls. I'm not sure if VS Code supports this, but it could at least be a setting or some memento-stored switch.

Some code to illustrate the problem:
```haxe
class Main {
	static function main() {
		var b = new B();
		var a:A = b;
		var i:I = b;

		i.f();
		a.f();
		b.f();
	}
}

interface I {
	function f():Void; // only finds i.f()
}

class A implements I {
	public function f() {} // only finds a.f()
}

class B extends A {
	public function new() {}
	override function f() {} // only finds b.f()
}
```

This is quite unfortunate for inheritance-heavy codebases such as the one we have at @innogames :)

**Comment by Simn** [comment]
This likely requires some thought with regards to sorting. Our protocol returns an `Array<Location>`, so we already fucked up because we can't easily add more information.

I think that _all_ `Response` occurrences should carry a structure as type parameter, i.e. there shouldn't be `Response<Array<T>>` at all. However, we've made the Haxe 4 release so I don't know how to proceed with this now.

---

As for the actual issue, what direction is this about? I understand that for `B.f` you also want to find `A.f` and that for `A.f` you also want to find `I.f`, but your comment on `I.f` suggests that you would also like to have results in the other direction.

**Comment by Simn** [comment]
Right, #9043 is about the other direction, so I'm assuming the comment on `I.f` should be `// only finds i.f() (and that's a good thing)`.

**Comment by nadako** [comment]
I think #9043 is not related, because it's about finding overrides/implementations, not usages.

Regarding the direction, it's a good question actually. I _think_ what we usually want in practice is finding all calls in all directions. :)

So searching `I.f` should definitely include `A.f` and `B.f` calls, while for `A.f` and `B.f` it depends - this is where IntelliJ usually asks user whether they want to search this exact method or the type where it was first defined (root of hierarchy or interface, not sure about multiple interfaces with the same method tho).

I'll just summon @Gama11 since he usually knows how this things work in other IDEs and what would be the best way :)

**Comment by Gama11** [comment]
I don't think VSCode has any UI / special support for this atm (has anybody checked how it works with TS?).

"Find usages of base method" being "on" by default makes sense to me since that way you don't miss anything (having too few results seems worse than too many). There could be a setting to disable it if needed.

**Comment by nadako** [comment]
Just checked TS: looks like they simple search in all directions. Using "Find References" on any of the definitions give the same result:
![](https://i.imgur.com/Fr4QkSw.png)

**Comment by nadako** [comment]
We could do better and provide a way to configure it, but I'm not sure it should be a settings option. To me it looks like a toggle that you'd be switching often, so maybe some boolean in the memento that can be changed by invoking some command (from statusbar maybe).

**Comment by Gama11** [comment]
This is way too niche to have it crowd the status bar even more.... :)

It being a setting and being togglable via a command are not mutually exlusive. IMO settings are more transparent / flexible than some memento. But I probably wouldn't add anything anyway until there's a demand for it.

**Comment by Simn** [comment]
@nadako Please check the `reference_cleanup_2020` branch and see if that does what you want.

Note that this change only affects references. Do we also want to show `B.f` as an implementation for `I.f`? Conversely, do we want to show `A.f` as an, uh, "overridee" of `B.f`? Also, do we want to show `I.f` as whatever the hell it is called on `A.f`?

**Comment by Simn** [comment]
I'm talking about the code lens output by the way:

![Code_kjY5OLQhuN](https://user-images.githubusercontent.com/634365/71778009-5aa51180-2fa8-11ea-8bf7-26ca280453be.png)

I think this should be in line with reference finding in general, lest we have situations where it says "3 references" and then on "Find references" we get 6 results.

**Comment by Gama11** [comment]
Yeah, I think code lens should use the same definition of what a reference is.

**Comment by nadako** [comment]
> Do we also want to show `B.f` as an implementation for `I.f`?

I _think_ yes, it sounds useful and logical since it's an (overriden) implementation after all :)

> Conversely, do we want to show `A.f` as an, uh, "overridee" of `B.f`? Also, do we want to show `I.f` as whatever the hell it is called on `A.f`?

I haven't used code lenses at all, so it's hard for me to "make a decision here", but it would be very nice to have a way to go to the interface method definition from the implementation. For overrides we can already click on the `override` keyword, but for interface methods we don't have anything AFAIK. Not sure if it should be in the code lens tho, since usually it's a nice gutter icon.

**Comment by nadako** [comment]
> I think this should be in line with reference finding in general, lest we have situations where it says "3 references" and then on "Find references" we get 6 results.

Yeah, I don't think TS behaviour is ideal. It should be separated: "References" should show field accesses, and "go to implementation" should show overrides/implementations.

**Comment by nadako** [comment]
I'm confused, "find references" on the `Child.func` override definition is supposed to find usage in `Main.main`, but currently it doesn't. Was this broken at some point?

```haxe
class Child extends Base {
	public function new() {}

	override function func() {
		super.func();
	}
}

class Base {
	public function func() {}
}

class Main {
	static function main() {
		var base:Base = new Child();
		base.func();
	}
}
```

**Comment by RealyUniqueName** [comment]
It doesn't work with 4.0.5 either.
Was it ever working like that?
I think the compiler should only search for "direct" references where `func` is called on `Child` instances.
But an IDE should ask user if he wants to search for `Child.func` references or for base class `func` references. And in case of the latter make a request to find references on `Base.func` instead of `Child.func` (I suppose IDE knows a parent class of the current one)

**Comment by Gama11** [comment]
>I suppose IDE knows a parent class of the current one

haxe-language-server doesn't at least. This could just be a parameter for the request though.
