### ISSUE TITLE
@:generic function is creating dependencies blobs

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9046]
Given the following class:

```haxe
class Utils {
	@:generic public static function flatten<T>(arrs: Array<Array<T>>) {
		var ret = [];
		for(a in arrs)
			ret = ret.concat(a);
		return ret;
	}
}
```

Each call to flatten with an new type will create a new specialized method in Utils, referencing the type in question, which will be later gathered by `Codegen.update_cache_dependencies`.

As a result, the `Utils` class will contain references to all types using it. This means that it will force recompilation of all these types if a single of them changes.

Think it can't get worse ? Now imagine if the Utils class happens to also be imported as part of `import.hx`...

Suggestion : create instead an unique class with the method(s) in question -- there can be several generic in Utils. For instance calling   flatten<Entity>()  would generate a class `generics.Utils__Entity` that contains the specialized flatten method.

**Comment by ncannasse** [comment]
PS: would appreciate if this can be fixed quickly ;)

**Comment by Simn** [comment]
This is something we would have to think through, so I don't think it can be fixed quickly. Your suggestion seems fine for this particular situation where a class has a single `@:generic` method, but it gets messy for anything more involved.

**Comment by ncannasse** [comment]
I think it works well, as mentioned I already thought about multiple @:generic.

We already injects static methods this way. Instead of injecting them in the original class (incrementally) we just need to inject them in a generated per-type class that still depends on the original one so any change to it will correctly invalidates the generated one.

**Comment by RealyUniqueName** [comment]
We should think about per-field dependency management instead of per-module. 
The idea of per-field dependencies was already discussed multiple times in the past. And it will make much better impact on compilation speed.
I guess it will come up more and more as Haxe is becoming more popular and attracts "big" projects.
Would be great if we find a way to do it without rewriting the compiler :)

**Comment by RealyUniqueName** [comment]
Also, spawning a new class for generic method will break method shadowing std rely on:
https://github.com/HaxeFoundation/haxe/blob/3626435/std/java/Lib.hx#L101-L143

Other questions:
- what if the method is not static?
- what if the class is generic too?

**Comment by ncannasse** [comment]
per-field management would surely be better, but is also vastly harder to implement. I would prefer a solution that works right now for the reported issue.

- regarding java std : I was not aware of such horrifying hacks :D but well, we can exclude this class, or even mark the method with some extra metadata if you want, but it should not be the default

- if the class is generic we are anyway already creating a new class for this. This class should be in its own module so changing the type parameter class does not discard all generics version all together

- if the method is not static, we don't have much an option than to keep current behavior.

**Comment by Simn** [comment]
I don't mind adding this feature for statics, but I think we should be explicit about it by having a new metadata on the class. Don't ask me how to call this though.
