### ISSUE TITLE
Is there work being done on #3550

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/haxe#9053]
https://github.com/HaxeFoundation/haxe/issues/3550 (I know its closed but see last comment)

Response headers are still map

**Comment by RealyUniqueName** [comment]
I'll take a look in the nearest days.

**Comment by RealyUniqueName** [comment]
We can add a method like `function getResponseHeaderValues():Null<Array<String>>`, which would return an array of vallues or `null` if no such header exists.

**Comment by hoseyjoe** [comment]
If this is the best way to fix it, great! We worked around the issue for our part.
