### ISSUE TITLE
analyzer-optimize doesn't work in __init__

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#9065]
```haxe
// haxe -D analyzer-optimize -main Main -js test.js
class Main {
	static function main() {
		var a = 101;
		trace(a);
	}
	static function __init__() {
		var b = 101;
		trace(b);
	}
}
```
generated js:
```js
Main.main = function() {
	console.log("src/Main.hx:6:",101);
};
var b = 101;
console.log("src/Main.hx:10:",b);
Main.main();
```
I'm not sure, maybe this is by design.

**Comment by Simn** [comment]
Yes this is by design because most of the `__init__` functions in our standard library are a huge mess that relies on native semantics and whatnot. I'm not sure it's worthwhile to look into some sort of black/whitelisting for this.

**Comment by RealyUniqueName** [comment]
I don't think it's worth to do something here. `__init__` is executed once per app run. It wouldn't give any significant performance improvements.
And if it happened analyzer optimizations are improtant for your `__init__`, then you can move `__init__` body to a separate function and call it from the `__init__`. That function will be optimized.
