### ISSUE TITLE
False negative for abstract this modification through nested setters

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9067]
The following code snippet silently fails at runtime (prints 0 instead of 1) due to a missing `inline`:

```haxe
class Main {
	static function main() {
		trace(Foo.make()); // should trace 1, but traces 0
	}
}

abstract Foo(Int) from Int {
	public static function make():Foo {
		var foo:Foo = 0;
		foo.init();
		return foo;
	}

	var a(never, set):Int;
	var b(never, set):Int;

	/* inline */ function init():Foo {
		a = 1;
		return this;
	}

	inline function set_a(v)
		return b = v;

	inline function set_b(v)
		return this = v;
}
```

Removing `inline` from one of the setters produces the usual compile-time error as expected:

> Abstract 'this' value can only be modified inside an inline function.

But for `init()` this is not the case - possibly to be related to `this` being modified through (nested) setters somehow.

**Comment by RealyUniqueName** [comment]
This is actually a more complex case of #6340 
Apperantly, #8454 was not enough to fix it completely.
