### ISSUE TITLE
[Feature] Allow map key => value on arrays

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#9070]
This seems somewhat logical, with haxe 4 the syntax `for (key => value in map)`was introduced. My proposal is allowing this syntax for arrays as well, where `key` would return the array index position.
```haxe
var ages = [21, 32, 13, 54, 15];
var names = ["A", "B", "C", "D", "E"];
for (i => name in array) {
    trace('User $name is ${ages[i]} years old');
}
```
This shouldn't break any existing code and makes for a fairly decent QOL improvement to arrays in general

**Comment by Gama11** [comment]
This is already being worked on, see https://github.com/HaxeFoundation/haxe/pull/7422 and https://github.com/HaxeFoundation/haxe/issues/7395.
