### ISSUE TITLE
Using reserved expression in typedef

### ISSUE THREAD

**Issue by varadig** [HaxeFoundation/haxe#9076]
I need to use private and public keyword in typedef in nodejs extern class 
https://github.com/DevInFlow/google-cloud.hx/blob/master/src/google/cloud/storage/global/bucket/UploadOptions.hx#L20
I looking a macro solution to extend my typedef, but no luck.

How can use reserved expression in typedef like @:native("public") publicProp?

**Comment by Gama11** [comment]
There's no good solution to this yet, see:

- https://github.com/HaxeFoundation/haxe/issues/7722
- https://github.com/HaxeFoundation/haxe/issues/5105
- https://github.com/HaxeFoundation/haxe-evolution/pull/32

Probably the best you can do in the meantime is wrap the typedef in an abstract. That abstract could have `(get, set)` properties named `public_` / `private_` (or something else that's not a keyword) which use `Reflect.field()` / `setField()` under the hood.

**Comment by dpomier** [comment]
There is also some macro builder that can help. For instance with [json2object](https://lib.haxe.org/p/json2object/) you can do:
```hx
typedef Foo {
    @:alias("public") var publicProp:Bool;
}
```
