### ISSUE TITLE
Quick way to check if current macro is at display position.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9077]
Macros need to behave quite differently, when they contain display position. Checking that for each macro becomes expensive at scale.

It would be nice to have a function that tells whether display is requested at the `Context.currentPos()` (or better yet a function that takes a `Position` and returns a `Bool`).

**Comment by RealyUniqueName** [comment]
`Context.isWithinDisplayPosition(pos)` or `Context.containsDisplayPosition(pos)`?

**Comment by back2dos** [comment]
I guess the latter makes more sense ;)
