### ISSUE TITLE
Haxe Error: You cannot access the cpp package while targeting cross (for cpp.Lib) [Haxe 4.0.5]

### ISSUE THREAD

**Issue by SeaPeaMe** [HaxeFoundation/haxe#9078]
I was trying to set up Haxe, but this error faces me whenever I try to import a Library, whether it be js.Lib, cpp.Lib, etc. It always comes up with this error:

Error: You cannot access the cpp package while targeting cross (for cpp.Lib)

I've been trying to fix this for 2 days now, I'm going insane!

**Comment by back2dos** [comment]
You can only access cpp specific APIs when targeting cpp ... "targetting cross" usually means you have not set any compiler target (via e.g. `-js outputFile.js` or `-cpp outputDirectory`).

**Comment by Gama11** [comment]
Looks like @SeaPeaMe has already asked about this here: https://stackoverflow.com/questions/59709283/haxe-error-you-cannot-access-the-cpp-package-while-targeting-cross-for-cpp-lib

**Comment by RealyUniqueName** [comment]
Question is answered on stackoverflow
