### ISSUE TITLE
[display] toplevel completion filtering is bugged

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9082]
```haxe
function test() {
	var args = ["-cp", ".", "--interp"];

	vfs.putContent("org/Thing.hx", "package org; class Thing {}");
	vfs.putContent("AThing.hx", "class AThing {}");
	vfs.putContent("ThingB.hx", "class ThingB {}");
	runHaxeJson(args, Methods.Initialize, {maxCompletionItems: 2});
	runHaxeJson(args, ServerMethods.ReadClassPaths, null);

	var transform = Marker.extractMarkers("class C extends Thing{-1-}");
	vfs.putContent("C.hx", transform.source);
	runHaxeJson(args, DisplayMethods.Completion, {
		file: new FsPath("C.hx"),
		offset: transform.markers[1],
		wasAutoTriggered: true
	});
	var result = parseCompletion();
	assertHasCompletion(result, function(item) {
		return switch item {
			case {kind: Type, args: {path: {pack: ["org"], typeName: "Thing"}}}: true;
			case _: false;
		}
	});
}
```

I am not sure how reliable is this test, because it relies on `org.Thing` being in the list AFTER the `AThing` and `ThingB` which is the case on my machine/filesystem.

But the idea is that the `filter_somehow` function doesn't work well for large codebases, since it doesn't do any sorting/scoring and as a result it might happen that something that has 100% match against the filter string won't be added to the list just because it is unlucky to be placed too late in the input list.

In real world this can be very annoying. For example in the following gif, the `Mediator` class is not present in the completion even though the list contains some completely unrelated items that were "fuzzy-matched", just because it is placed in `org.robotlegs.blahblah` package which comes after the `de.innogames.blahblah` packages.

![](https://i.imgur.com/EyfWLtR.gif)

**Comment by Simn** [comment]
I have committed something that makes your tests pass, but it likely requires quite a bit of fine-tuning to get right.

**Comment by Gama11** [comment]
Is this 4.0_bugfix material, or too risky?

**Comment by Gama11** [comment]
With `"haxe.maxCompletionItems": 10`, I'd expect to see 10 items here (JS):

![](https://i.imgur.com/mQoeD5R.png)

The Haxe response contains some packages, but these seem to be filtered out on the VSCode side. Not sure why they're dropped completely, but there's definitely better matches available:

![](https://i.imgur.com/Fm4CSWL.png)

Maybe we need to take a closer look at the VSCode implementation again too make sure there's no huge mismatch between the two filter algorithms.

**Comment by Simn** [comment]
We only filter types on the Haxe side, so I don't really care about these cases where we have a very low `maxCompletionItems` setting.

**Comment by Gama11** [comment]
It's not really about having an extremely low `maxCompletionItems`, that's just an easier way to force the issue. Something like `maxCompletionItems: 100` should probably be expected to work too, and it seems possible to hit that limit with packages in a big project.

**Comment by Simn** [comment]
If you have a big project and set `maxCompletionItems` to 100 then I can't help you. I'll restrict the filtering to types unless somebody can show that this causes issues in a real world scenario.

**Comment by Gama11** [comment]
I'm still confused why any types are reported at all then with a limit of 10 if only types are filtered. Seems like that limit should already easily be hit with keywords, packages etc?

**Comment by Simn** [comment]
Well there aren't that many keywords that match `ele`.

**Comment by Gama11** [comment]
Well, yes, but that means that keywords _are_ filtered after all / not just types?

**Comment by Simn** [comment]
Right the terminology is confusing here. Everything is filtered in the sense that we check if it matches the subject and ignore it if it doesn't. What I meant was the _sorting_ that happens afterwards and only applies to types. The best-matching types are then used to fill the results up to `maxCompletionItems`, so if that limit is hit it also acts as a sort of filter.

**Comment by Gama11** [comment]
Ah, that's not how I thought you would implement this.

Isn't the initial "match / no match" filtering redundant once you have a ranking? Then you can just use the first `n` items with the best score. It seems like that would be simpler _and_ work better, or am I missing something?

**Comment by Simn** [comment]
It's the same operation, we just throw out everything that doesn't match at all, which we detect while determining the rank.

I don't think completely ignoring the completion item kind leads to better results, but we could try it.

**Comment by Gama11** [comment]
Yeah, not totally sure either.. To me it just seemed like Haxe should report roughly the same results for my first screenshot as it does for the second, because the things filtered out by VSCode didn't seem like good matches at all, while something like `AreaElement` seems like it should score pretty well against `ele`.

**Comment by Simn** [comment]
@nadako How does this behave now in a real codebase?

**Comment by nadako** [comment]
Fine for me so far, I guess we can close this and if something comes up, I'll make another report.

**Comment by Simn** [comment]
I'm not closing yet because I don't want to just dismiss @Gama11's concerns about the sorting. Though I still don't really know what to do with it either.

**Comment by Gama11** [comment]
I'm still curious if things would look any different if it's based purely on ranking, instead of that hybrid approach. Even if it ends up behaving the same, it should at least simplify the implementation?

**Comment by Simn** [comment]
I think you should be able to easily test this by commenting out this code in displayException.ml:

```ocaml
				match item.ci_kind with
				| ITType _ ->
					DynArray.add acc_types (item,index,cost);
				| _ ->
```

**Comment by Gama11** [comment]
Hm, ok, I'll give that a try when I get a chance (and get Haxe to compile again - though I can just check out a pre-eval-SSH commit for this :D).

**Comment by Gama11** [comment]
If I do that, I end up with this, and am even more confused:

![](https://i.imgur.com/ozMbHj7.png)

Does that imply that `EnumValue` ranks higher than `Element` (from my earlier screenshot)?

It would be nice to have the scores Haxe came up with in the JSON output for debug purposes (but only for debugging I guess).

**Comment by Simn** [comment]
Are you sure that JS is the active target?

**Comment by Gama11** [comment]
Yes, if I increase `maxCompletionItems`, `Element` starts showing up again.

**Comment by Simn** [comment]
Ok I see why, the logic needs more adjustments for this... Try commenting out this part as well:

```haxe
		| _ when DynArray.length ret >= !max_completion_items ->
			()
```

**Comment by Gama11** [comment]
But that just seems to disable the `max_completion_items` limit entirely? I have 576 items in my display response now rather than 10.

**Comment by Simn** [comment]
But is the sorting good? :D

I guess I'll have to review this more thoroughly...

**Comment by Gama11** [comment]
Ah, the list in the JSON response is sorted according to the score then? No, it's not, `EnumValue` is the first entry... :(

**Comment by Simn** [comment]
Man who wrote this shit...

Try also replacing `DynArray.add ret (CompletionItem.to_json ctx (Some index) item);` with `DynArray.add acc_types (item,index,cost);`. That should do it.

**Comment by Gama11** [comment]
Ah, yes, that's better:

![](https://i.imgur.com/ztpDdx6.png)

Even the other 5 results seem good, not sure why VSCode drops those...

**Comment by Simn** [comment]
That looks good indeed. I cannot remember why I wanted to have this special case for types... I guess we can drop it after all.

**Comment by Gama11** [comment]
Let's see what VSCode devs say about those other 5 items: https://github.com/microsoft/vscode/issues/91184
