### ISSUE TITLE
abstracts loose their type? minor inconvenience listed incase.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9086]
( haxe 4.0.2, mac 10.12.6 ).
It is annoying to need to do this...
``` haxe
    // generic passing attributes to shader.
    static inline function shaderInput<T>( gl:      RenderingContext
                                           , program: Program
                                           , name:    String
                                           , att:     Int
                                           , arr:     T
                                           , number:  Int ){
        var buffer = gl.createBuffer();
        var arrBuffer = RenderingContext.ARRAY_BUFFER;
        gl.bindBuffer( arrBuffer, buffer );
        if( number == RenderingContext.FLOAT ){ 
                gl.bufferData( arrBuffer, cast( arr, Float32Array ), RenderingContext.STATIC_DRAW );
        } else if( number ==  RenderingContext.INT){
                gl.bufferData( arrBuffer, cast( arr, Int32Array ), RenderingContext.STATIC_DRAW );
        } else if( number == RenderingContext.UNSIGNED_INT ){
                gl.bufferData( arrBuffer, cast( arr, Uint16Array ), RenderingContext.STATIC_DRAW );
        }
        var flo = gl.getAttribLocation( program, name );
        gl.vertexAttribPointer( flo, att, number, false, 0, 0 ); 
        gl.enableVertexAttribArray( flo );
        gl.bindBuffer( arrBuffer, null );
    }
```
Because Float32Array or similar does not seem to transfer as an abstract into the class properly when I don't use an if statement eg: see error and original approach ( full user/class path cropped as it's not relevant )
```
...hx:133: characters 9-70 : Could not find a suitable overload, reasons follow
...hx:133: characters 9-70 : Overload resolution failed for (target : Int, data : js.lib.ArrayBufferView, usage : Int) -> Void
...hx:133: characters 35-38 : shaderInput.T should be js.lib.ArrayBufferView
...hx:133: characters 35-38 : For function argument 'data'
...hx:133: characters 9-70 : Overload resolution failed for (target : Int, size : Int, usage : Int) -> Void
...hx:133: characters 35-38 : shaderInput.T should be Int
...hx:133: characters 35-38 : For function argument 'size'
...hx:133: characters 9-70 : Overload resolution failed for (target : Int, data : js.lib.ArrayBuffer, usage : Int) -> Void
...hx:133: characters 35-38 : shaderInput.T should be js.lib.ArrayBuffer
...hx:133: characters 35-38 : For function argument 'data'
...hx:133: characters 9-70 : End of overload failure reasons
compile: /projects/.../compile.hxml
```
Because this fails.
``` haxe    
// generic passing attributes to shader.
    static inline function shaderInput<T>( gl:      RenderingContext
                                           , program: Program
                                           , name:    String
                                           , att:     Int
                                           , arr:     T /*eg: Float32Array */
                                           , number:  Int ){
        var buffer = gl.createBuffer();
        var arrBuffer = RenderingContext.ARRAY_BUFFER;
        gl.bindBuffer( arrBuffer, buffer );
        gl.bufferData( arrBuffer, arr, RenderingContext.STATIC_DRAW );
        var flo = gl.getAttribLocation( program, name );
        gl.vertexAttribPointer( flo, att, number, false, 0, 0 ); 
        gl.enableVertexAttribArray( flo );
        gl.bindBuffer( arrBuffer, null );
    }
```
It's also a pain that I end up resorting to an 'if' structure - this is because it takes too much effort to work out how to express this with switch statements, switches use to be simpler to use.

Anyway minor issue - so not urgent to fix or change - as I guess it is limitation of abstracts, only really reporting so that it can be actioned if it has serious implications or is low hanging fruit, otherwise feel free to close.  Cheers ;J

**Comment by nanjizal** [comment]
Pehaps I need a constraint, but figured compiler could infer.

**Comment by Aurel300** [comment]
Out of curiosity, does it work if you do `untyped arr` in the `bufferData` call?

**Comment by RealyUniqueName** [comment]
Try adding `@:generic` meta to that method.

**Comment by nanjizal** [comment]
untyped arr works thanks, would it have any speed impact?
@:generic does not work. 

I have created a fairly minimal test, I hope this is useful ( hxml setup for opening browser on mac so may need tweak feel free to pull alternate hxml ).
https://github.com/nanjizal/bugs/tree/master/abstracts_loose_their_type

**Comment by nanjizal** [comment]
It might be ideal to have a similar repo that users could clone and pull issues against, ideally setup with travis or similar then if simpler examples are found they would just be committed instead, may need some consideration but since try haxe is out of date, we need a simple way to share possible bugs to minimize effort and if the bugs fail against travis or similar it's a good first check against your standard setup?

**Comment by Aurel300** [comment]
`untyped arr` should not cause any performance issues on JavaScript.

**Comment by RealyUniqueName** [comment]
There is no compiler issue here.
Inside of `shaderInput` method it is unknown what kind of `T` will be supplied to a method call at run time because type parameters is a compile time feature. That's why the compiler doesn't know which one of `bufferData` overloads to generate.

**Comment by RealyUniqueName** [comment]
Closing this as there is no compiler issue as explained in my previous comment.
Feel free to reopen if you have a suggestion or want to discuss compiler behavior in this case.

**Comment by nanjizal** [comment]
Seems the current AST approach is rather limited in some inferance situations, as a long time Haxe user I am expecting more Ocaml smarts, the type is defined within the calling code so telling me that the compiler can't tell is more a limitation of the current interpretation of the grammar implemented, could we not have some inference through T?  I guess the usual approach is giving the compiler a special hint..
```
@:inferType
static inline function shaderInput<T>
```
Perhaps it's more a problem from js target  implementation and for this use case it is probably not worth the effort of creating any work round - so closing the issue on that account is fine by me.

BUT in my mind it does leave a wider question on how Haxe does or does not approach inferance through T, inferance is not just icing it's critical part of Ocaml and also Haxe and when it can't be used it indicates a faux limitation that may need future consideration.  I don't have more generic example in mind so I can't know if it's a faux limitation but if feels like one.

**Comment by nanjizal** [comment]
Thanks guys for taking a look and the workround.
