### ISSUE TITLE
[java] line too long when multi java libraries

### ISSUE THREAD

**Issue by joydance** [HaxeFoundation/haxe#9088]
I want to try to develop an android with haxe's java target.
When I try, I encounter this issue:

java.io.IOException: line too long
        at java.util.jar.Attributes.read(Attributes.java:379)
        at java.util.jar.Manifest.read(Manifest.java:199)
        at java.util.jar.Manifest.<init>(Manifest.java:69)
        at sun.tools.jar.Main.run(Main.java:176)
        at sun.tools.jar.Main.main(Main.java:1288)

When I just android.jar, everything is ok, but when I add more AppCompact dependencies, it failed.
I suppose it's because I have too many java libraries in the build.hxml?

The project is here:
https://github.com/joydance/haxe-android-test

**Comment by RealyUniqueName** [comment]
Is it adding a specific library causes the exception? Or does it happen when you add one more library, no matter which one?

**Comment by joydance** [comment]
> Is it adding a specific library causes the exception? Or does it happen when you add one more library, no matter which one?

--java-lib lib\butterknife-10.2.1-api.jar
--java-lib lib\jetified-rxpermissions-0.10.2-api.jar
--java-lib lib\rxjava-2.2.17.jar
--java-lib lib\MPAndroidChart-v3.1.0-api.jar
--java-lib lib\butterknife-runtime-10.2.1-api.jar
--java-lib lib\butterknife-annotations-10.2.1.jar
--java-lib lib\core-1.0.0-api.jar
--java-lib lib\versionedparcelable-1.0.0-api.jar
--java-lib lib\collection-1.0.0.jar
--java-lib lib\lifecycle-runtime-2.0.0-api.jar
--java-lib lib\lifecycle-common-2.0.0.jar
--java-lib lib\core-common-2.0.0.jar
--java-lib lib\annotation-1.0.0.jar
--java-lib lib\reactive-streams-1.0.3.jar
--java-lib lib\retrofit-2.7.1.jar
#--java-lib lib\okhttp-3.14.4.jar
#--java-lib lib\okio-1.17.2.jar

I have make some test, when uncomment any of the last line, the compilation will fail, so I think it's not allow too long argument in the command line?

**Comment by RealyUniqueName** [comment]
Does it still work if you uncomment one of the last lines and comment out something in the middle?

**Comment by joydance** [comment]
> Does it still work if you uncomment one of the last lines and comment out something in the middle?

Yes，I've tried and it's no problem.

**Comment by RealyUniqueName** [comment]
Most likely you're using an outdated version of hxjava.
Try `haxelib update hxjava` and then build you project again. Works for me after updating to the latest `hxjava`.

**Comment by joydance** [comment]
> Most likely you're using an outdated version of hxjava.
> Try `haxelib update hxjava` and then build you project again. Works for me after updating to the latest `hxjava`.

Yes, you're right. Thank you!
