### ISSUE TITLE
[display] inconsistent goto implementations ranges

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9093]
For interface method implementations, the ranges cover just the method names like expected:

![](https://i.imgur.com/SeYVZl8.png)

For overrides, they cover entire methods, which doesn't look great:

![](https://i.imgur.com/8RqThjQ.png)

IIRC, this has always been an issue with code lens, so this probably comes from the code reuse there.

```haxe
class Main implements IMain {
	static function main() {}

	public function foo() {}
}

class Main2 extends Main {
	override function foo() {
		super.foo();
	}
}

class Main3 extends Main {
	override function foo() {
		super.foo();
	}
}

interface IMain {
	function foo():Void;
}
```

**Comment by RealyUniqueName** [comment]
This is how it looks for me with the latest Haxe and release version of vshaxe:
![overrides](https://i.imgur.com/Ra1ULEA.png)

**Comment by Gama11** [comment]
Yes, because we work around it in CodeLensFeature. :) Also, even there more than the identifier is highlighted.

https://github.com/vshaxe/haxe-language-server/blob/446bb53d78a33d2b9730c337ce71eeb63526be3d/src/haxeLanguageServer/features/CodeLensFeature.hx#L43
