### ISSUE TITLE
Removing `cl_overrides`

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#9104]
Given that we have `cf_flags` now, we could utilize it to replace `cl_overrides` without additional memory cost. For the most part, this comes down to replacing some `List.memq` with a flag check. However, there are some more involved operations on `cl_overrides` in the dark realms of gencommon which we would have to check.

For macro compatibility, we would have to iterate `cl_ordered_fields` and check for the override flag. This is more expensive, but I doubt that it could have a significant impact even for classes with hundreds of fields. Still, we should check this to make sure.

What do you think?

**Comment by RealyUniqueName** [comment]
Seems fine. 
In addition to macros that could affect completion performance too. But I doubt it would be significant.
Looking through the code I don't see any difficulties with replacing it with a flag.
