### ISSUE TITLE
SourceMaps broken when using inline

### ISSUE THREAD

**Issue by qwertykg** [HaxeFoundation/haxe#9105]
Hi,

We have run into an issue with debugging inline functions when transpiling to the js target. If we dont inline(by using the no-inline define) then there are no issues. We can set breakpoints in the would-be inlined functions. But if we don't use the no-inline define, then the functions that are now actually inlined are not debuggable. 

I've created a small class to demonstrate this:

```haxe
class Calculator
{
    public function new()
    {}

    public function addPositiveNumbers(numberOne:Int, numberTwo:Int)
    {
        if (isNegative(numberOne))
        {
            trace(numberOne + "Is negative");
        }

        if (isNegative(numberTwo))
        {
            trace(numberTwo + "Is negative");
        }

        if (isOdd(numberOne))
        {
            trace(numberOne + "Is odd");
        }

        if (isOdd(numberTwo))
        {
            trace(numberTwo + "Is odd");
        }

        return numberOne + numberTwo;
    }

    inline function isNegative(number)
    {
        return number < 0;
    }

    inline function isOdd(number)
    {
        return Std.int(number / 2) == 0;
    }

    static public function main()
    {
        var calc = new Calculator();

        var result1 = calc.addPositiveNumbers(2,3);
        var result2 = calc.addPositiveNumbers(2,-3);
        var result3 = calc.addPositiveNumbers(32,4353);

        trace(result1);
        trace(result2);
        trace(result3);
    }
}
```
This was compiled using these parameters:
```hxml
-cp src
-D source-map-content
-D analyzer
--js bin/index.js
--debug
-main Calculator
```

The end result on the browser is as follows:
<img width="551" alt="Screenshot 2020-01-21 at 22 33 49" src="https://user-images.githubusercontent.com/17964124/72842225-9cb89d80-3ca0-11ea-8d8d-89b542332897.png">

The actual inline functions cannot be debugged. Using no-inline(or dce no) results in this:
<img width="577" alt="Screenshot 2020-01-21 at 22 34 41" src="https://user-images.githubusercontent.com/17964124/72842301-c1147a00-3ca0-11ea-8d1b-6cf7c6cd535f.png">

Which is what we would want. In this case the functions allow for breakpoints. But in this case, these functions aren't inlined in the js code. 

Is there any way around this?

**Comment by Aurel300** [comment]
Did you accidentally upload two screenshots of the Haxe code rather than JS code?

**Comment by qwertykg** [comment]
No no 😄. Those screenshots are from the browser - Not from the code in my IDE. Those are the sourcemapped haxe files that the browser generates. the part thats different in the screenshots are the line numbers that are greyed out.

The ungreyed out line numbers are where the browser allows me to put breakpoints, I cant put breakpoints for the lines that have greyed out line numbers.

The first screenshot doesn't allow me to breakpoint below line 28. Which is problematic when you have inline functions doing something more complex than just one line, and you need to debug why the end result from those inline functions are incorrect.

The second screenshot are the sourcemaps from code that was either compiled with "dce no" or "no-inline". The compiled js has reference to the inline functions and so I can breakpoint inside my inline functions.

If it helps I can also post the compiled js code?

The compiled js looks exactly like whats generated here though: https://try.haxe.org/#E18FA

You can toggle "dce full" and "dce Std" to get the js output for the different scenarios

**Comment by RealyUniqueName** [comment]
By default inliner assign the position of a call to all the inlined expressions of that call. That's why you can set a breakpoint at the call position, but not in the inlined function body.

There is a flag to change that behavior since Haxe 4: `-D keep_inline_positions`. It makes inliner to keep original positions of inlined expressions.
Notice, there is no way to step over an inlined call during debugging. You will be automatically redirected to the inlined function body when stepping over an inlined call.

**Comment by qwertykg** [comment]
Ahh I didn't know about that - I tried it out and it definitely works better than before. I think this should be fine to close. Thanks @Aurel300 and @RealyUniqueName 😄
