### ISSUE TITLE
[python] make anonymous objects subscriptable

### ISSUE THREAD

**Issue by theJenix** [HaxeFoundation/haxe#9109]
This is more a feature request than an issue, but I think one that would make it more natural to include Haxe-generated python code in Python projects.  I would love it if the _hx_AnonObject were subscriptable, so I could treat those objects as if they were Python dictionaries (which is a common way of representing anonymous objects in Python).

I believe this is as straightforward as adding a `__getitem__` implementation to _hx_AnonObject in the Python code generated by the Haxe compiler; I'd be happy to submit a pull request if someone can point me roughly to the area of the compiler code that would need to be changed to support this.

**Comment by RealyUniqueName** [comment]
`_hx_AnonObject` is generated from here:
https://github.com/HaxeFoundation/haxe/blob/bf252aa/src/generators/genpy.ml#L2430-L2450
How would it impact performance of field access on anonymous objects?

**Comment by theJenix** [comment]
I don't think it would impact field access performance at all, and I think subscript access performance would be only marginally slower (if at all).  The change I am thinking about is:
```
def __contains__(self, item):
    return item in self.__dict__
def __getitem__(self):
    return self.__dict__[item]
```

Which just delegates to the __dict__ dictionary that is set in the constructor, and would behave the same as a Python dictionary (e.g. return the value if it exists, throw a KeyError if not).  I think it makes sense to add __contains__ as well so we can do 'x in obj' style tests.

**Comment by RealyUniqueName** [comment]
> throw a KeyError if not

But the semantics of Haxe anon objects is to return `null` in case of missing fields.

**Comment by theJenix** [comment]
Oh yea, my mistake, you're right.  Is it usually more desirable for target platform code to behave more like the platform?  Or should it be consistent with Haxe semantics?  If the latter, I can change my implementation to return None vs raise a KeyError.

**Comment by RealyUniqueName** [comment]
After thinking a bit more about it - I'm not sure.
Since it's for usage from the python side, then it probably should be consistent with native python behavior.

**Comment by theJenix** [comment]
That's usually my preference (trying to make it consistent with native python), but also, it looks like _hx_AnonObject's `__getattr__` method returns None in normal usage (vs raising an AttributeError, as per Python expectation), so maybe returning None here is better because it's more consistent with existing behavior.  In other words, should obj['missing'] behave like obj.missing for an anon object?

If you think this is something worth including, I can start to work on the PR while we figure out specific semantics here.

**Comment by RealyUniqueName** [comment]
I don't use python target myself, so I can't really tell, what's better here.
`__getattr__` is used for field access from the Haxe side, hence the behavior with `None`. 
IIUC `__getitem__` is for usage from the Python side, which has different specs.

**Comment by theJenix** [comment]
That's a fair point (and I think you do understand correctly)  Ok, I'll press forward with my original plan.
