### ISSUE TITLE
[js] Std.parseInt(Int) returns null

### ISSUE THREAD

**Issue by flashup** [HaxeFoundation/haxe#9112]
Hello.
```haxe
var value:Dynamic = 100;
trace(Std.parseInt(value)); // Haxe 4.0.0RC2 = 100, Haxe 4.0.5 = null
```
Html5 target on Haxe 4.0.5 returns `null`.
But cpp targets return 100, native js function Number.parseInt(100) also returns 100.

**Comment by Gama11** [comment]
Why are you trying to "parse" something as an integer that's already an integer? `parseInt()` expects a `String`.

**Comment by flashup** [comment]
I parse dynamic server response and I just want to be sure that I get an Integer value.

**Comment by Gama11** [comment]
You should probably do something like this then:

```haxe
var value:Dynamic = 100;

var int:Int = if (Std.is(value, Int)) {
    cast value;
} else if (Std.is(value, String)) {
    Std.parseInt(value);
} else {
    throw "unexpected type";
}
```

**Comment by kLabz** [comment]
The lazy alternative being `Std.parseInt(Std.string(value))`

**Comment by RealyUniqueName** [comment]
`Int` and `String` are completely unrelated types.
`Std.parseInt()` expects a string. A value of any other type is unspecified behavior.
It's up to you to validate your dynamic data. 
And the fact you get `Std.parseInt(100) == 100` in some targets is just an accident.

**Comment by derRaab** [comment]
Just a quick note:
I ran into that issue as well. Since this worked in Haxe 3.4.7 I wonder if this shouldn't be mentioned as breaking change for Haxe 4? Haxe 3 did simply return the integer again. That was quite handy to force a dynamic value to be an integer.

**Comment by nanjizal** [comment]
Would it improve Haxe user experience to add some **force** methods optimised per target, well anyway my js optimised forceInt function incase it's useful for derRaab  

https://gist.github.com/nanjizal/ca151e52b8aabd21ecb951d6463bca49  

```haxe
// js target specific code only based loosely on _std internals.
import js.Syntax;
class ForceIntTest {
    static function main() {
        var a = 0;
        var b = 0.1; // need to make sure it needs Float
        var c = '0';
        var d = true;
        var e = [];
        trace( checkBasic( a ) );
        trace( checkBasic( b ) );
        trace( checkBasic( c ) );
        trace( checkBasic( d ) );
        trace( checkBasic( e ) );
        trace( forceInt( a ) );
        trace( forceInt( b ) );
        trace( forceInt( c ) );
        trace( forceInt( d ) );
        trace( forceInt( e ) );
    }
    static inline 
    function checkBasic( v: Dynamic ): String { // arrays not converted.
        var s = js.Syntax.typeof(v); 
        if( s == "number" ){
            if( js.Syntax.strictEq(v | 0, v) == true ) {
                s = 'int';
            } else {
                s = 'float';
            }
        }
        return s;
    }
    static inline 
    public function forceInt( v: Dynamic ): Int {
        var s = checkBasic( v );
        var o: Int = 0;
        switch( s ){
            case "int":
                o = v;
            case "float":
                o = Std.int( v );
            case "string":
                o = Std.parseInt( v );
            case "boolean":
                if( v ){
                    o = 1; //??
                } else {
                    o = 0;
                }
            default:
                throw 'not possible to force to Int';
        }
        return o;
    }
}
```
