### ISSUE TITLE
Haxe 4.0.5 64 don't work for me on windows 10

### ISSUE THREAD

**Issue by Alama32** [HaxeFoundation/haxe#9114]
Hello, all be in the title..

**Comment by Aurel300** [comment]
Could you please provide more details?

Has it worked in the past? Are you using the installer? What is the error, if you can see any?

And so on, we can't help you if you don't tell us anything.

**Comment by Alama32** [comment]
Sorry, it'not an IDE, I was wrong, I installed the editor and it works now . : D
