### ISSUE TITLE
buggies in enum abstract

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9115]
```haxe
enum abstract A(String) {
	var A1;
	var A2;

	function f() {
		var a:A = cast this; // hovering `a` will print Dynamic
		switch (a) {
			// no exhaustiveness check
		}
	}
}
```

**Comment by Simn** [comment]
Something is wrong with the context, the typer thinks it's in a static function and chokes trying to type `this`.

**Comment by Simn** [comment]
It's about this piece of code:

```ocaml
					(match args with
					| ("this",_,_) :: _ -> FunMemberAbstract
					| _ when fst f.cff_name = "_new" -> FunMemberAbstract
					| _ -> FunStatic)
```

The argument is no longer named `this` so the function kind ends up being `FunStatic`. I tried checking for `@:impl` instead but that isn't set either for some reason.
