### ISSUE TITLE
Bug: Java/JVM Mixing Type Param with Type

### ISSUE THREAD

**Issue by piboistudios** [HaxeFoundation/haxe#9116]
It appears the Java/JVM target is getting confused with types and type parameters.

I am attempting to use Netty in Haxe, and the `io.netty.bootstrap.ServerBootstrap` class is defined like so:
`public class ServerBootstrap extends AbstractBootstrap<ServerBootstrap, ServerChannel>`
(and `AbstractBootstrap`: `public abstract class AbstractBootstrap<B extends AbstractBootstrap<B, C>, C extends Channel> implements Cloneable`)

Whenever I write the line : `var bootstrap = new io.netty.bootstrap.ServerBootstrap();`

I get this error when compiling:
> Constraint check failure for io.netty.bootstrap.AbstractBootstrapConfig.B
io.netty.bootstrap.AbstractBootstrap.B should be io.netty.bootstrap.AbstractBootstrap<io.netty.bootstrap.AbstractBootstrap.B, io.netty.bootstrap.AbstractBootstrap.C>

Seems like the compiler is inferring that the actual type `ServerBootstrap` is referring to the type parameter `B` of `AbstractBootstrap`, which is *technically* correct, just not in this context.

Imported with: `-java-lib netty-all-4.1.45.Final.jar` ; latest Netty build

**Comment by Simn** [comment]
This doesn't reproduce if written in Haxe code:

```haxe
class Channel {}

class ServerChannel extends Channel {}

class AbstractBootstrap<B:AbstractBootstrap<B, C>, C:Channel> {}

class ServerBootstrap extends AbstractBootstrap<ServerBootstrap, ServerChannel> {
	public function new() {}
}

class Main {
	static function main() {
		var bootstrap = new ServerBootstrap();
	}
}
```

This suggests that there's a problem with the .class reader...

**Comment by Simn** [comment]
After disabling the check I can see this in the dump file:

```
extern class io.netty.bootstrap.AbstractBootstrap<B : io.netty.bootstrap.AbstractBootstrap.B,C : io.netty.bootstrap.AbstractBootstrap.C> implements java.lang.Cloneable {
```

The type parameters are constrained to themselves somehow...

**Comment by Simn** [comment]
Never mind, this isn't actually a constraint print, the dump printer is just being stupid.
