### ISSUE TITLE
[js] EventLoop fires incorrectly due to wrong time units

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#9121]
Spotted while reading the code, not tested

setTimeout uses milliseconds whereas nextTick has units of seconds
https://github.com/HaxeFoundation/haxe/blob/67476abe10f750195dfd5d6ff005012ca347764f/std/haxe/EntryPoint.hx#L113

So run() could be called roughly 1000 times for each timed event. Practically not a major issue because it's very light but would be nice to be correct here

Will make PR if someone else agrees with the mistake

**Comment by RealyUniqueName** [comment]
I agree
