### ISSUE TITLE
Nightly builds windows64-installer is raising system error "The code execution cannot proceed because libgcc_s_seh-1.dll was not found"

### ISSUE THREAD

**Issue by Dimous** [HaxeFoundation/haxe#9131]
Hello!
Recent "latest" build throws exception: "The code execution cannot proceed because libgcc_s_seh-1.dll was not found" in the end of installation process, when running `Execute: "C:\Users\kasim\Documents\Haxe\haxe\haxe.exe" --cwd "C:\Users\kasim\Documents\Haxe\haxe" -x WinSetup.hx`

I'm on Windows 10 x64 Home edition.

There were no problems a couple of builds before.

**Comment by Dimous** [comment]
There were no problems a couple of builds before.

**Comment by Ilir-Liburn** [comment]
You need to install OCaml64 and add to your path
```
C:\OCaml64\usr\x86_64-w64-mingw32\sys-root\mingw\bin
```
I can only guess, compiler is getting plugins support, but you have to wait for Haxe team response to see if that have anything to do with plugins

**Comment by Simn** [comment]
Uhm, that shouldn't be the case. Must be some linking issue...

**Comment by RealyUniqueName** [comment]
@Simn Could this be a fallout of eval-ssl PR merge?

**Comment by Simn** [comment]
Yes it probably is, but I don't know why it happens yet.

**Comment by Simn** [comment]
The dependency comes from libmedcrypto.dll, so it looks like we actually have to package libgcc_s_seh-1.dll...

**Comment by Simn** [comment]
@Dimous Could you check if it works with this installer: https://build.haxe.org/builds/haxe/windows64-installer/haxe_2020-02-13_mbedtls_packacing_win_fix_0ee6229.zip

**Comment by Dimous** [comment]
It is working now.
