### ISSUE TITLE
[display] map literal vs completion

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9133]
Sorry, I don't have time for constructing proper unit tests at the moment, but here are some screenshots instead \o/

![](https://i.imgur.com/gudG15J.png)
![](https://i.imgur.com/cRZUuqo.png)
![](https://i.imgur.com/unLo7p8.png)

**Comment by Simn** [comment]
Fixed the first part, but I don't have time to commit it right now so here's a screenshot of it working instead:

![Code_q1VV7uVDUm](https://user-images.githubusercontent.com/634365/74335938-939d8680-4d9d-11ea-86f7-9279762b1343.png)

**Comment by Simn** [comment]
Fixed the third screenshot too. The second one is quite annoying because there's something wrong with the display position offset checking. It's also not about map literals in particular.
