### ISSUE TITLE
[display] "Find references" on a property field doesn't work

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9141]
Here if you "find references" on the `field` in `var field`, nothing will be found. One can use "find references" on `get`/`set` specifiers or `get_field`/`set_field` declarations instead, but it's a bit surprising that simply finding references on a field itself doesn't work. IMO it should find both read and write access.

```haxe
class Main {
	static function main() {
		var c = new C();
		var f = c.field;
		c.field = f;
	}
}

class C {
	public var field(get,set):Int;
	public function new() {}

	function get_field() return 10;
	function set_field(value:Int) return value;
}
```

**Comment by Simn** [comment]
This is in the same ballpark as the inlining problem. We could hack around it here by doing some name checking, but I would really prefer to solve this more elegantly somehow...

**Comment by Simn** [comment]
This is covered by the test for #9140.
