### ISSUE TITLE
[display] broken imports completely disables IDE features

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9142]
Subj. Easily reproducable with any example. :)

**Comment by RealyUniqueName** [comment]
What do you mean "broken imports"? Importing a non-existing module?

**Comment by nadako** [comment]
yes

**Comment by Simn** [comment]
Can probably be fixed by using `display_error` in some place that currently uses `error`. We should try to do that in as many places as possible for display support.
