### ISSUE TITLE
TypeTools.map and TypeTools.iter are inconsistent for TAnonymous

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9147]
It seems that [`map` does not in fact enter `TAnonymous`](https://github.com/HaxeFoundation/haxe/blob/67feacebc59d5cd9dce232058f12cb933622d619/std/haxe/macro/TypeTools.hx#L310). I suspect that's because it's not allowed to construct typed structures from within macros. Ideally, it would in fact work for `TAnonymous`, but if it can't be helped, the documentation should be updated, lest someone else spend the better part of an hour wondering if they forgot how to perform simple recursion.

**Comment by ncannasse** [comment]
That also does not match the documentation/specification.
