### ISSUE TITLE
Deprecate `php.Web`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#9153]
Let's deprecate them for 4.1 and move to hx3compat in 4.2

**Comment by jonasmalacofilho** [comment]
What is the rationale?

_(and let's no kid ourselves: code goes to hx3compat to die)_

**Comment by Simn** [comment]
It's out-of-scope for a standard library. At least one of our, uhm, size.

**Comment by RealyUniqueName** [comment]
Out of scope and it has very inefficient API to implement for PHP.

**Comment by Aurel300** [comment]
> Let's deprecate them for 4.1 and move to hx3compat in 4.2

Should it not technically go to `hx4compat`

**Comment by RealyUniqueName** [comment]
Yes, probably

**Comment by RealyUniqueName** [comment]
Deprecated.
Next step: move to hx4compat

**Comment by RealyUniqueName** [comment]
`neko.Web` should not be derpecated as there's no alternative.

**Comment by Simn** [comment]
Tracked in #11341.
