### ISSUE TITLE
[Haxe 4.0.1, JS] Overriding private method as public

### ISSUE THREAD

**Issue by CrazyFlasher** [HaxeFoundation/haxe#9156]
https://try.haxe.org/#Ea61e
Isn't it a bug that I can override private as public? Looks wierd.

**Comment by Simn** [comment]
No that's fine.

**Comment by CrazyFlasher** [comment]
Ok. But can you give a couple of words why it's fine? Many of us think, that it's not fine.
What is the best way to add compile-time check fr that?

**Comment by Simn** [comment]
Well, if you think there's a problem then the burden of proof is on you. Widening visibility in sub classes doesn't violate encapsulation because you cannot assign a parent class to a child class.
