### ISSUE TITLE
Function parameter equal to enum value

### ISSUE THREAD

**Issue by prnxdev** [HaxeFoundation/haxe#9157]
Hi,

I made some enum:
```hx
enum abstract VehicleModel(Int) {
  var Savanna = 567;
}
```
and class which is using this enum as type of one of param:
```hx
@:native('Vehicle')
extern class Vehicle {
  public var model: VehicleModel;

  @:native('create')
  public function new(model: VehicleModel, position: Vector3);
}
```
Question: how can I make it possible to allow anyone to pass value to this function which will be equal to enum value. Here's example:

This works well:
```hx
var vehicle = new Vehicle(VehicleModel.Savanna, ...);
```
.. and this not:
```hx
var vehicle = new Vehicle(567, ...);
```
but I want to

**Comment by kLabz** [comment]
This should work with 
```haxe
enum abstract VehicleModel(Int) from Int {
  var Savanna = 567;
}
```

But then it will work with any `Int`, not just `657`. I don't think you can have exactly what you want.

**Comment by nadako** [comment]
Technically it is probably possible with a macro `@:from`, but I wouldn't invoke macros for this. Also you can just write `new Vehicle(Savanna, ...);`, without prefixing :)

**Comment by prnxdev** [comment]
I didn't know that I don't need prefix. That's dope 👍. 

Is there any way to check if value is inside enum? I want to check if '567' is in 'VehicleTypes' and eventually get key (Savanna).

**Comment by Gama11** [comment]
Enum abstracts don't support reflection in that way. You would have to use a macro for that, see

- https://code.haxe.org/category/macros/enum-abstract-values.html
- or as a lib: https://lib.haxe.org/p/list-enum-abstract/

**Comment by Simn** [comment]
This isn't really an issue report.
