### ISSUE TITLE
[ci] windows installer fails to build

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9158]
The "Build Haxe" step in "BuildWin64" fails while still returning success, so the error is only raised when S3 deployment job cannot find the installer artifact.

See https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=2977&view=logs&j=9109c8e8-b628-5178-0f3d-e22df9a5e341&t=ae8642bd-c304-518b-1eb2-0ce0c900266b&l=100

```
Processing script file: "installer.nsi" (ACP)
Error: unterminated string parsing line at macro:_IncludeStrFunction:7
Error in macro _IncludeStrFunction on macroline 7
!include: error in script: "EnvVarUpdate.nsh" on line 49
Error in script "installer.nsi" on line 13 -- aborting creation process
make: *** [Makefile.win:107: package_installer_win] Error 1
```

Some NSIS version incompatibility I presume?

**Comment by andyli** [comment]
It was in fact due to an error of `choco install nsis` happened in an earlier step.
6c45ef609005ed06e6922bb95e847d9e82de8f43 should make it less confusing if it happen again.
