### ISSUE TITLE
[display] function and var are not in the completion for interface body

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9160]
![image](https://user-images.githubusercontent.com/49749/74860628-409d7380-5349-11ea-810f-acdd83f2bcdd.png)

**Comment by Gama11** [comment]
Actually, this completion is not from Haxe, but from the language server: https://github.com/vshaxe/haxe-language-server/blob/24f35a2e08b11ade989f733f18112c4c0a9aeb98/src/haxeLanguageServer/features/completion/CompletionFeature.hx#L272

For some reason I don't fully remember, it is (was) hard for Haxe to provide completion at member level, so I implemented it there. We might have to rethink that though, it would probably be better if it came directly from Haxe.

For function / var snippets etc, we probably need to add support for interfaces here: https://github.com/vshaxe/haxe-language-server/blob/master/src/haxeLanguageServer/features/completion/SnippetCompletion.hx

**Comment by nadako** [comment]
"transferred" to https://github.com/vshaxe/vshaxe/issues/421
