### ISSUE TITLE
[display] redundant unitinialized final error when the initialization expr does not type

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9171]
```haxe
class C {
	final x:Int;

	function new() {
		x = nonsense;
	}
}
```

```
src/Main.hx:11: characters 7-15 : Unknown identifier : nonsense
src/Main.hx:8: characters 2-14 : final field x must be initialized immediately or in the constructor
```

This is minor, but it would be nice if it didn't complain about that `final` field is not initialized, because obviously it is, it's just _ends up_ being unitialized due to the other error.

**Comment by Simn** [comment]
This is quite related to the `throw nonsense` issue vs. `return` that I've just found but now cannot find again.
