### ISSUE TITLE
[hl] values assigned inside of nested `catch` are discarded.

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#9174]
```haxe
class Main {
	static public function main() {
		var value = false;
		try {
			try {
				throw '';
			} catch(e:String) {
				value = true;
				trace('inner catch: value == $value');
				throw e;
			}
		} catch(e:String) {
			trace('outer catch: value == $value');
		}
	}
}
```
Actual output:
```
Main.hx:9: inner catch: value == true
Main.hx:13: outer catch: value == false
```
Expected output:
```
Main.hx:9: inner catch: value == true
Main.hx:13: outer catch: value == true
```

**Comment by ncannasse** [comment]
Interesting...
It comes from the optimizer which does not seem to deal correctly with catch clauses. In that precise case it doesn't "guess" that we can jump from catch1 to catch2, and thus "value" register is opt out.

**Comment by RealyUniqueName** [comment]
This is still reproducible.

**Comment by Simn** [comment]
This one looks pretty bad actually, I can see this causing some debugging sessions. Any chance to resolve this for 4.3?
