### ISSUE TITLE
Feature request : FreeBSD Port

### ISSUE THREAD

**Issue by devosalain** [HaxeFoundation/haxe#9176]
It would be nice if someone could port it.
gmake fails due to differences

/home/x/_haxe/haxe-4.0.5 x> $gmake
gmake -C libs/extlib-leftovers native && gmake -C libs/extc native && gmake -C libs/neko native && gmake -C libs/javalib native && gmake -C libs/swflib native && gmake -C libs/ttflib native && gmake -C libs/ilib native && gmake -C libs/objsize native && gmake -C libs/pcre native && gmake -C libs/ziplib native && true
gmake[1]: Entering directory '/usr/home/x/_haxe/haxe-4.0.5/libs/extlib-leftovers'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/_haxe/haxe-4.0.5/libs/extlib-leftovers'
gmake[1]: Entering directory '/usr/home/x/_haxe/haxe-4.0.5/libs/extc'
ocamlfind ocamlc -safe-string  extc_stubs.c
gmake[1]: ocamlfind: Command not found
gmake[1]: *** [Makefile:19: extc_stubs.o] Error 127
gmake[1]: Leaving directory '/usr/home/x/_haxe/haxe-4.0.5/libs/extc'
gmake: *** [Makefile:116: libs] Error 2

**Comment by Simn** [comment]
Please refer to https://community.haxe.org/ if you're having problems compiling Haxe. This repository is for issue reports.

**Comment by Aurel300** [comment]
Have you run `make opam_install`?

**Comment by devosalain** [comment]
I see i need to install additional ocaml packages.

**Comment by devosalain** [comment]
I installed:
ocaml-findlib
ocaml-extlib
pcre
pcre2
ocaml-pcre
Now gmake produces : 
$gmake                     
gmake -C libs/extlib-leftovers native && gmake -C libs/extc native && gmake -C libs/neko native && gmake -C libs/javalib native && gmake -C libs/swflib native && gmake -C libs/ttflib native && gmake -C libs/ilib native && gmake -C libs/objsize native && gmake -C libs/pcre native && gmake -C libs/ziplib native && true
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/extlib-leftovers'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/extlib-leftovers'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/extc'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/extc'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/neko'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/neko'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/javalib'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/javalib'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/swflib'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/swflib'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/ttflib'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/ttflib'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/ilib'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/ilib'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/objsize'
gmake[1]: Nothing to be done for 'native'.
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/objsize'
gmake[1]: Entering directory '/usr/home/x/haxe/haxe-4.0.5/libs/pcre'
ocamlc -safe-string  -I pcre pcre_stubs.c
pcre_stubs.c:56:10: fatal error: 'pcre.h' file not found
#include "pcre.h"
         ^~~~~~~~
1 error generated.
gmake[1]: *** [Makefile:20: pcre_stubs.o] Error 2
gmake[1]: Leaving directory '/usr/home/x/haxe/haxe-4.0.5/libs/pcre'
gmake: *** [Makefile:116: libs] Error 2
/home/x/haxe/haxe-4.0.5 x> $
-------------------------------------------------
Yet the perl regular expressions header file is present on my system in :
/usr/local/include/pcre.h
