### ISSUE TITLE
Arrow function return a wrong type in generated code

### ISSUE THREAD

**Issue by djaonourside** [HaxeFoundation/haxe#9181]
```haxe
class Main
{
	public static function main()
	{
		var result = produce((obj) -> {
			obj.id = 2;
		});
	}

	public static function produce<T>(producer: T -> Void): T
	{
		return null;
	} 
}
```
`producer` param of `produce` method is typed as returning `Void` but in generated code the callback returns obj:
```js
// Generated by Haxe 4.0.2
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var result = Main.produce(function(obj) {
		return obj.id = 2;
	});
};
Main.produce = function(producer) {
	return null;
};
Main.main();
})({});
```

**Comment by Gama11** [comment]
At the call-site, the arrow function is actually typed as `(obj : { id : Int }) -> Int` (you can check this by wrapping it in `$type()`). It's just that functions that return something unify with `-> Void` functions:

```haxe
class Main {
	public static function main() {
		var foo:() -> Int = () -> 0;
		var bar:() -> Void = foo;
		bar(); // compiles fine
	}
}
```

**Comment by RealyUniqueName** [comment]
@djaonourside does it cause any issues/bugs other than unnecessary `return` expression?

**Comment by djaonourside** [comment]
@RealyUniqueName In my case `produce` is  a member of js external type and it throws an error when `producer` returns something. I thought `->Void` notation would help me to control this thing:)

**Comment by Simn** [comment]
Huh, I thought we fixed the `return` generation when the expected type is `Void`.

**Comment by djaonourside** [comment]
Documentation really says unification `...-> Void`  and `...-> SomeType` is possible 
 https://haxe.org/manual/type-system-unification-function-return.html

**Comment by Simn** [comment]
Yes the unification is fine, but the return shouldn't be generated because we know that the expected non-type is `Void`.

**Comment by nadako** [comment]
that reminds me of https://github.com/HaxeFoundation/haxe/issues/6420, might be worth fixing while we're at it :)
