### ISSUE TITLE
[display] signature help doesn't (always) work in an overriden function

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9183]
```haxe
class A {
	function f(x:Int) {}
	function g(y:Int) {}
}

class B extends A {
	override function f(x:Int) {
		g(10);
	}
}
```

requesting signature help for the `g` call there doesn't work UNLESS the display file is invalidated, with the following error:
```
[Error - 13:55:21] Request textDocument/signatureHelp failed.
  Message: Field f should be declared with 'override' since it is inherited from superclass A
```

I guess this is some texpr-display edge case?

**Comment by RealyUniqueName** [comment]
@nadako I can't reproduce this neither with 4.0.5 nor with the latest dev Haxe

**Comment by nadako** [comment]
Hmm, now I cannot reproduce this as well... I get the signature help.

However the error (`Field f should be declared with 'override'`) still can be reproduced if you request signature help at position before `g` or after `;`, but also ONLY if display file is not invalidated (so any editing "fixes" it), so _something_ is still weird there.

**Comment by Simn** [comment]
This is fixed by replacing the `memq` check with one that compares field names, which suggests that the problem here is that fields lose their identity somewhere. 

What we should do is introduce `CfOverride` and get rid of that entire `cl_overrides` nonsense.
