### ISSUE TITLE
Typing hole regression

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9184]
After upgrading the compiler we started noticing that some errors are no longer displayed, resulting in successful compilation whereas some class fields actually didn't exist at all, leading to various runtime errors.

We bisect it to 72eb9c1d4c2fc440dbc2eaa9ac69f6a7a82d8512, please revert/rework @RealyUniqueName  ;)

**Comment by ncannasse** [comment]
I think the problem is that you might get some error in another class due to unification being performed lazily, and this error is totally unrelated to whereas the unification of the optional parameter was successful or not. So we simply cannot skip these errors.

**Comment by RealyUniqueName** [comment]
That commit fixes two other nasty issues.
Can you provide a sample for me to try to fix it without reverting the commit?

**Comment by Simn** [comment]
I think that `| WithTypeError (ul,p)->` is missing a check to see if the error position is actually about our current call. I think a completely different module could cause an unrelated `WithTypeError` which would then be muted here.

Maybe this can be reproduced with a nested call, where the outer one catches an error from the inner one.

**Comment by ncannasse** [comment]
Please revert immediately, I can't reproduce easily - only got it once on a very complex code base (whole northgard) but it's super nasty bug. Also, I stand by my earlier comment : you can't expect errors to be errors coming from the unification of the two modules.

In our case, it was "XXX has no field yyy" that was entirely ignored.

**Comment by ncannasse** [comment]
Also, the issues that this fixes are not at the same level of nastiness as some compiler errors just disappearing entirely.

**Comment by RealyUniqueName** [comment]
Reverted in fb6da3a5ea0c6d4143662b613245cbe4ba14d494
