### ISSUE TITLE
CPP target Json.parse utf8 bom not supported

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/haxe#9186]
Example

```haxe
Assets.loadText(assetReference.url).onComplete(onSingleComplete) //OpenFL ASync Load Text


private function onSingleComplete (pData:String) :Void 
{
      data = Json.parse(pData); //throws "Invalid char 65279 at position 0"
}
```

Files with utf8 boom cannot be parsed.
The problem is solved when the loaded text is converted to utf8.

**Comment by Aurel300** [comment]
BOM is something generally used in UTF-16, not UTF-8 (where endianness is not important). It also should not be handled by `Json.parse`. I would say if OpenFl has a signal that is meant to resolve with a string, UTF-16 BOM detection (and skipping) should be done in OpenFl.

**Comment by RealyUniqueName** [comment]
Duplicates #6930

**Comment by RealyUniqueName** [comment]
I mean, in #6930 it's decided to not make `haxe.Json` aware of BOM.
