### ISSUE TITLE
max thread count error.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9187]
```haxe
import haxe.MainLoop;

class Main {
	static function main() {
		trace("Hello, world!");

		var len:Int = 125970;
		var threadCounts:Int = 15;

		var eachCount:Int = Std.int(len / threadCounts);
		trace(eachCount);
		var sum:Int = 0;
		for (i in 0...threadCounts) {
			MainLoop.addThread(function() {
				var from = i * eachCount;
				var to = (i + 1) * eachCount;

				trace('from =$from  to=$to');
				for (k in from...to) {
					sum++;
				}

				if (sum == len)
					trace('sum=' + sum);//only windows hxcpp can print this result
			});
		}
	}
}
```

I did a test on windows and ubuntu, and build target both hxcpp and hl target.

and only get right result on windows's hxcpp target 

hl: both windows and ubuntu test fail,got the wrong result;

hxcpp: windows ok,but got the wrong result too.

ubuntu

![image](https://user-images.githubusercontent.com/748320/75620076-0fca0380-5bbf-11ea-89c0-201fa8023e83.png)

windows

![image](https://user-images.githubusercontent.com/748320/75620085-19536b80-5bbf-11ea-9d70-dd186a2bc0b9.png)

**Comment by haxiomic** [comment]
You’re reading and writing to a variable (sum) from multiple threads without any thread synchronisation mechanisms being used, the result is undefined behaviour

You might want to look into synchronisation primitives to make your example work https://dev.to/quantumsheep/basics-of-multithreading-in-c-4pam

Closing this issue, if you still have an problem when the example is corrected feel free to reopen

**Comment by sonygod** [comment]
thank you @haxiomic 

after add Mutex,it' s fixed.



	import haxe.MainLoop;
	import sys.thread.Mutex;

	class Main {
		static function main() {
			trace("Hello, world!");

			var len:Int = 125970;
			var threadCounts:Int = 15;

			var eachCount:Int = Std.int(len / threadCounts);
			trace(eachCount);
			var sum:Int = 0;
			var mute = new Mutex();
			for (i in 0...threadCounts) {
				MainLoop.addThread(function() {
					var from = i * eachCount;
					var to = (i + 1) * eachCount;

					trace('from =$from  to=$to');
					for (k in from...to) {
						mute.acquire();
						sum++;
						mute.release();
					}

					if (sum == len)
						trace('sum=' + sum);
				});
			}
		}
	}

**Comment by haxiomic** [comment]
Nice one :)
