### ISSUE TITLE
duplicate deprecation warnings

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9192]
Something I noticed while fixing positions in the TyperDotPath refactoring branch, but actually easily reproducable on current development:

```haxe
class Main {
	static function main() {
		A.field;
	}
}

@:deprecated
class A {
	public static final field = 3;
}
```

this will give two errors instead of one
```
src/Main.hx:3: characters 3-4 : Warning : Usage of this class is deprecated
src/Main.hx:3: characters 3-10 : Warning : Usage of this class is deprecated
```

I think this is because we recurse into the parent expression of a field while still checking the class, so we get class checked twice with two different positions and thus two errors.

**Comment by Simn** [comment]
We should just check for `pfile` + `pmin` instead of the whole range.
