### ISSUE TITLE
enumerators obscure classes

### ISSUE THREAD

**Issue by nspitko** [HaxeFoundation/haxe#9197]
Haxe helpfully will attempt to resolve naked enumerators where possible. This is a good behavior, but has the side-effect of obscuring classes that may share the name

The resolution order here should probably put enumerators at the bottom, since you can *always* qualify an enumerator, but some types can't be. As an example:

```haxe
enum Foo {
	Bar;
}

class Bar
{
	public static var someVar : String = "Yay";
}

class Main
{
	static function main()
	{
		Bar.someVar = "test";
	}
}
```

will produce the error `src/Main.hx:14: characters 8-15 : Foo has no field someVar`

In this case, we lose access to the `Bar` class entirely, as there's no more specific way to identify it. However, had the reverse been true we could have still accessed the enum via `Foo.Bar`

At a minimum this should at least produce a better error, since enums are often buried in imports (which still produce this behavior)

**Comment by RealyUniqueName** [comment]
I agree. Though if you have a package, you can access the class too: `pack.Bar.someVar = 'test'`.

**Comment by nadako** [comment]
I had this case before and it's indeed very annoying, I wonder if swapping these would create different conflicts? As a workaround you can `import as` or use fully qualified path (with `std.` for the root types).

Anyway not sure we can just change this in a minor release...

**Comment by Simn** [comment]
This is the documented resolution behavior. We definitely can't change it in a minor release and I don't think we could change it in a major release either.

**Comment by Gama11** [comment]
This behavior often leads to ugly workarounds / bad naming conventions, such as prefixing all enum constructors with something, which could be considered a form of hungarian notation... :(

I've previously wondered if there could at least be a meta to opt-into safer resolution for an enum. That would avoid breakage but still allow to have more sane behavior for enums that have particularly problematic constructor names (such as `String` or `Class` in LSP enums). Also seems messy though.

**Comment by ncannasse** [comment]
The workaround is  `std.Bar.someVar = "test"`
This std "root package" prefix is not very well documented and maybe misleading, I wonder what else could be used instead.

**Comment by 0b1kn00b** [comment]
How hard would it be to use a metadata tag on an Enum to prevent it's constructors being published nakedly? Would that help the situation?

**Comment by restorer** [comment]
Bump. I ran into a similar problem yesterday:

```haxe
enum Foo {
  Foo1;
  Foo2;
}

enum Baz {
  Foo;
  Bar;
}

class Test {
  static function main() {
    test(Foo.Foo1); // Obscure error: "Baz has no field Foo1"
    test(Foo.Bar); // More obscure error: "Baz has no field Bar"
    // test(Test.Foo.Foo1); // OK with package name
  }

  static function test(v: Foo): Void {
  }
}
```

https://try.haxe.org/#5e98E606

**Comment by Simn** [comment]
I just tried prioritizing types over enum constructors and immediately hit this:

```haxe
import haxe.macro.Type;

function main() {
	var t = TVar(null, null); // haxe.macro.TVar is not a value
}
```

This suggests to me that such a change would be quite brutal...

One way to handle this is to treat enum constructors and types at the same priority-level, and then consider lexical appearance with the last one winning. This would make the original example work, but still cause errors on @restorer's code. I don't really see how this can be avoided though.

The problem with that is that this requires quite a few internal changes to our identifier resolution handling. In particular, some fields on `typer_module` would have to be merged so that there's a defined order. That's not impossible to do, but also not exactly easy.

**Comment by Simn** [comment]
Here's a silly corner case:

```haxe
import String.fromCharCode as StringMap;
import haxe.ds.StringMap;

class Main {
	static function main() {
		$type(StringMap); // (code : Int) -> String
	}
}
```

This happens because the first import is delayed into `context_init` because it needs the type structure, which then means that it is added later and thus has higher priority.
