### ISSUE TITLE
tests/sys/genTestRes.py failed to run on OSX 10.14+

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#9199]
I was trying to replace the CI Mac agents from macOS 10.13 to 10.14, and found that genTestRes.py threw an error:

```
Changing directory to /Users/runner/runners/2.165.0/work/1/s/tests/sys/
Command: haxe [compile-macro.hxml,-D,azure,-D,Mac]
Traceback (most recent call last):
  File "genTestRes.py", line 57, in <module>
    os.mkdir(os.path.join(TESTDIR, data))
OSError: [Errno 92] Illegal byte sequence: 'test-res/\ud7ff'
Error: get_full_path
Command exited with 1 in 244s: haxe [compile-macro.hxml,-D,azure,-D,Mac]
```

I can reproduce it with my own Mac, which is using macOS 10.15. So, I assume there is something changed between 10.13 and 10.14.

**Comment by Aurel300** [comment]
`genTestRes` tries to create a number of files and directories with various Unicode test vectors as names. The one throwing the error for you is [`U+D7FF`](https://www.fileformat.info/info/unicode/char/d7ff/index.htm), which is "not a valid Unicode character". This works on HFS+, which is what I run locally, but perhaps not on APFS, the newer Mac filesystem. I can only assume the CI runners switched to APFS with the newer OS version.

I don't have an APFS machine to test things on. @andyli could you confirm you are using APFS locally where you reproduce the error? It might be that many of the test vectors in `genTestRes` will simply not be valid for APFS and will need to be deleted (and `tests/sys/src/UnicodeSequences` updated accordingly). I can make the changes if you let me know all the Unicode sequences in `genTestRes` that cause an error.

Unfortunately, this is really filesystem-dependent, not OS-dependent, and we have no way in the stdlib to check for filesystem information. In our test suite we can detect the newer OS easily in Python and we can pass compile-time flags to Haxe when compiling tests…

**Comment by andyli** [comment]
Yes, my Mac is using APFS.

> I can make the changes if you let me know all the Unicode sequences in genTestRes that cause an error.

This [doc](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html) looks helpful, but I lack the unicode knowledge to understand, maybe you can?

**Comment by RealyUniqueName** [comment]
What about wrapping those tests with something like this?
```haxe
catch(e:Dynamic) {
  if(Std.string(e).indexOf('Illegal byte') < 0) throw e;
}
```

**Comment by Aurel300** [comment]
@andyli That link is helpful, thanks.

@RealyUniqueName `genTestRes` is a vanilla Python script that is executed before the Unicode sys tests. We can catch exceptions there I'm sure, but the problem is that then we don't really have a "known" state of the generated directories, so we can't test it properly on the Haxe side. So we need some compile-time switches (depending on the current CI runner OS) to indicate to Haxe just what it should expect.
