### ISSUE TITLE
 [analyzer] Fails to compare enums with arguments and null inside a switch

### ISSUE THREAD

**Issue by dpomier** [HaxeFoundation/haxe#9200]
The following code will not compile with `-D analyzer-optimize`:
```haxe
enum Foo {
	Bar(_:Int);
}

class Test {
	static function main () {
		switch Bar(4) {
			case null: // commenting this line will make it work
			case Bar(s): trace(s);
		}
	}
}
```
The error message:
```
Test.hx:7: characters 15-21 : You cannot directly compare enums with arguments. Use either 'switch' or 'Type.enumEq'
```
https://try.haxe.org/#2cdD2

**Comment by RealyUniqueName** [comment]
Storing enum value to a variable also workarounds the error.

**Comment by RealyUniqueName** [comment]
But with analyzer+inlining this situation is very possible.

**Comment by Simn** [comment]
The real problem here is that `Bar(4) == null` fails. The compiler could optimize that to `{ 4; false; }` and subsequently to just `false`. But at the very least it shouldn't complain about it.
