### ISSUE TITLE
[jvm] Haxe-generated ADTs are not usable from Java

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9210]
javac fails to compile this because Haxe generates ADTs with the enum flag. `Some` is generated as a class that extends `enum Option`, which probably confuses javac - Java does not allow enum inheritance.

```haxe
import haxe.ds.Option;

public class Main {
    public static void main(String[] args) {
        Option option = haxe.ds.Option.Some("");
        if (option instanceof Option.Some) {
            
        }
    }
}
```

![](https://i.imgur.com/PzrhTwJ.png)

**Comment by Simn** [comment]
I have removed the enum flag so this should work now. Assigning to you to add a test for this (see unit/native_java).

**Comment by Gama11** [comment]
Hm, not sure `native_java` really fits for this, that buids a native Java jar to be used in Haxe, right? We want the opposite here (include a Haxe jar in native Java).

**Comment by RealyUniqueName** [comment]
Setup a project in `java/projects` and add java build commands as `--cmd` into `compile.hxml`
