### ISSUE TITLE
Compiler bug: Assertion failed when trying to build for Windows C

### ISSUE THREAD

**Issue by Simonrazer** [HaxeFoundation/haxe#9211]
I get this error message on my Project when trying to build for Windows C: 
```
File "_build/src/generators/hl2c.ml", line 549, characters 31-37: Assertion failed
```
When i do `set OCAMLRUNPARAM=b ` before building I get this: 
```
Fatal error: exception File "_build/src/generators/hl2c.ml", line 549, characters 31-37: Assertion failed
Raised at file "_build/src/generators/hl2c.ml", line 549, characters 31-43
Called from file "_build/src/generators/hl2c.ml", line 641, characters 20-33
Called from file "array.ml", line 124, characters 31-51
Called from file "_build/src/generators/hl2c.ml", line 715, characters 1-1023
Called from file "list.ml", line 106, characters 12-15
Called from file "list.ml", line 106, characters 12-15
Called from file "_build/src/generators/hl2c.ml", line 1692, characters 1-903
Called from file "_build/src/generators/genhl.ml", line 4068, characters 2-39
Called from file "_build/src/compiler/main.ml", line 343, characters 2-14
Called from file "_build/src/compiler/main.ml", line 1059, characters 25-62
Called from file "_build/src/compiler/main.ml", line 633, characters 3-11
Called from file "_build/src/compiler/main.ml", line 1220, characters 1-35
```
The problem occurs in an Armory project, so the Haxe version used is 4.0.0+c37e5ed23. I can not give a minimal project where this bug occurs because I have no idea what in the code of Armory/Kha/... causes it. I only know that it happens when trying to build for Windows C (or Android C) when using the Library colyseus.hx in the project. Here is the Armory project
[FPS.zip](https://github.com/HaxeFoundation/haxe/files/4301627/FPS.zip) .
Edit: I updated Armory's version of Haxe to 4.0.5 and this exact same thing persists.

**Comment by RealyUniqueName** [comment]
Could you provide a sample to reproduce the issue?

**Comment by Simonrazer** [comment]
The only example I can provide is the project I uploaded. Try building it with Armory for Windows C and you'll get the error. I'm sorry that I can't give a smaller example because I have no idea what actually causes this.

**Comment by Simn** [comment]
Since we don't; know how to reproduce this, I'll assume that this has been addressed at some point.
