### ISSUE TITLE
[jvm] generate final fields as final

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9212]
I think this shouldn't cause any issues, and would make interop nicer.

**Comment by nadako** [comment]
I'm still undecided on that topic, because of https://github.com/HaxeFoundation/haxe/issues/8263#issuecomment-501044107

**Comment by Simn** [comment]
#8263 makes me think that we shouldn't do this.

**Comment by RealyUniqueName** [comment]
Genphp already does that. Unless the field being `@:hack`ed.

**Comment by Simn** [comment]
Reading through #8263 again, I still agree with myself from three years ago in that we shouldn't do this.
