### ISSUE TITLE
[jvm] mark some implementation details as synthetic

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9213]
Such as `_hx_` fields in DynamicObject or the EmptyConstructor stuff. This should make interop nicer / hide those things from Java completion.

Probably need something like @:jvm.synthetic for this.

**Comment by Gama11** [comment]
`_hx_getKnownFields` in `DynamicObject` subclasses would be a candidate for this too.

**Comment by Simn** [comment]
Done, feel free to add it to more fields that you come across.
