### ISSUE TITLE
haxe.PosInfos.className in abstract types

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9214]
The following will output `src/Main.hx:3: _Main.A_Impl_`:

```haxe
abstract A(Int) {
	static function f(?p:haxe.PosInfos) {
		trace(p.className);
	}
	public static function g() {
		f();
	}
}
```

While it is technically correct (the **class** name is indeed `_Main.A_Impl_`), I am not sure if that's what we want here. Should it contain a path to the abstract type itself, not the impl class?

**Comment by nadako** [comment]
Actually, this is also a problem with private types. Maybe we should leave it as is then...

**Comment by nadako** [comment]
My WIP module-statics have the same issue and I decided not to do anything about it for now, and fix or not fix all of them at once in the scope of this issue.

**Comment by Simn** [comment]
Let's not try to change this.
