### ISSUE TITLE
abstract<typedef<T>> with operators hard/impossible to type 

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9215]
It's really tricky/impossible to properly type abstract typedef<T> structures so you can create generalised operators, for instance I failed here with my add function :

http://try-haxe.mrcdk.com/#A82Eb  ( select dev build option ).

```haxe
package;
typedef VectorType<T> = {
    public var x: Float; 
    public var y: Float;
    public var ?z: Float; 
    public var ?w: Float;
    //-------------------
    // Common operators  
    //-------------------
    function add( b: T ): T;
}
@:forward( add )
abstract VectorX<U:VectorType<T>,T>( VectorType<T> ) from VectorType<T> to VectorType<T> {
    public inline
    function new( m: VectorType<T> ){
        this = m;
    }
    @:generic
    @:op(A + B) public static
    function adder<U:VectorType<T>,T>( a: VectorX<U,T>, b: VectorX<U,T> ): VectorX<U,T> {
        var vt: VectorType<T> = a.add( b );
        var vx: VectorX<U,T> = vt;
        return vx;
    }
}
class Test {
  static function main() {
    trace("Haxe is great!");
  }
}
```
Seems the haxe typing system can easily become hard to use when trying to deal with generalised abstract structures and then back to implemented run time ones, it feels like there maybe holes in the theory, when you try to work round with some casting it still fails at runtime.
( - the T, I was aiming to wrap is set of abstracts, over set of struct class properties ( so matrix or vectors ) )

Abstracts don't allow operator overloading to be forwarded to abstracts that inherit and using typedef as an interface for abstracts is fraught with type complexity.

Would be nice for a non macro solution to my specific question, but beyond that from language design typing perspective it can get complex with these typedef/abstracts and the compiler errors like adder.T are rarely helpful enough, would be nice to have tools that make it more robust and viable, and improvements over complex cast uses.  

Perhaps some aspects are already implemented resolved and just need more docs around, but suspect not entirely yet?

Many thanks.

**Comment by Ilir-Liburn** [comment]
Maybe something "fishy" can be found here

```haxe
typedef VectorType<T> = {
    public var x: Float; 
    public var y: Float;
    public var ?z: Float; 
    public var ?w: Float;
    //-------------------
    // Common operators  
    //-------------------
    public function add( b:T ): T;
}

//@:forward( add ) -> not needed unless goes as a member of abstract
abstract VectorX<U:VectorType<T>, T>( U ) from U to U {
    public inline
    function new( m: U ){
        this = m;
    }
//  @:generic -> won't generate function, avoid it, use inline instead
    @:op(A + B) public inline
    function adder(b: T): VectorX<U,T> {
        return cast this.add( b );
    }
}

class VectorXYZW {
    public var x: Float; 
    public var y: Float;
    public var z: Float; 
    public var w: Float;
    public function new() {}
    public function add( b:VectorXYZW ): VectorXYZW { return b; }
}

class Test {
    public static function main() {
        var v1 = new VectorX(new VectorXYZW());
        var v2 = new VectorX(new VectorXYZW());
        $type(v1); // Warning : VectorX<VectorXYZW, Unknown<0>>
        $type(v2); // Warning : VectorX<VectorXYZW, Unknown<0>>
        $type(v1.adder); // Warning : (b : Unknown<0>) -> VectorX<VectorXYZW, Unknown<0>>
        $type(v2.adder); // Warning : (b : Unknown<0>) -> VectorX<VectorXYZW, Unknown<0>>
        trace(v1 + v2);
        trace(v2 + v1);
        $type(v1); // Warning : VectorX<VectorXYZW, VectorX<VectorXYZW, VectorXYZW>>
        $type(v2); // Warning : VectorX<VectorXYZW, VectorXYZW>
        $type(v1.adder); // Warning : (b : VectorX<VectorXYZW, VectorXYZW>) -> VectorX<VectorXYZW, VectorX<VectorXYZW, VectorXYZW>>
        $type(v2.adder); // Warning : (b : VectorXYZW) -> VectorX<VectorXYZW, VectorXYZW>
    }
}
```

**Comment by RealyUniqueName** [comment]
I don't see an issue here. 
Looking at your first sample I can see, why that could be confusing, but `T` and `VectorType<T>` in `adder` function are not the same or compatible types.
If you change `function add(b:T):T` to `function add(b:VectorType<T>):VectorType<T>` the error would disappear.

It's probably better to try and find a simpler solution to your problem instead of type parameters juggling. 
I understand it seems appealing to create  a  super-generic solution using type parameters and parameters constraints, but it quickly becomes confusing and hard to read and maintain.

**Comment by nanjizal** [comment]
> //@:forward( add ) -> not needed unless goes as a member of abstract
It was for abstracts, I wanted to create
**VectorX** ( Matrix1x2, Matrix1x3, Matrix1x4 ) 
and 
**MatrixX** ( Matrix2x2, Matrix3x3, Matrix4x3 ... )
https://nanjizal.github.io/geom/pages/geom/matrix/index.html
Theoretically it seemed like it should be possible for MatrixX and VectorX to provide operators, I still have not created full method coverage of **VectorType** and **MatrixType** but quite close.

But from experimenting it seems nothing as super-generic as this is possible using the current haxe typesystem, it's almost like Haxe needs some more magic so it is more viable and simpler.  Certainly it's almost like the compiler needs a bit more intuition around T and some more type smart alternatives to typedef cast.

I tried function add(b:VectorType<T>):VectorType<T> but then you can't get access to the add of Matrix1x4, it probably disappear as it's abstract so DCE'd? 
Honestly it feels like a minefield full of promise but just too hard to manipulate, even if there is currently a way... which I doubt, it's a long way from obvious to find it, and ideally it should be more obvious, not just for my problem but for similar super-generic manipulation, constraints and casts soon become impossible to navigate.
Anyway thanks for taking a look.

**Comment by Ilir-Liburn** [comment]
Well, since you are making 2D/3D transformations library, you should be careful while using abstracts. For example, decision to use VectorType typedef as underlying type seems to be a bad choice, because  access over typedef usually means: dynamic access. Here is an example how usage of your abstract looks in C#

```C#
object this1 = ((object) (new global::VectorXYZW()) );
object v1 = ((object) (this1) );
object this2 = ((object) (new global::VectorXYZW()) );
object v2 = ((object) (this2) );
object __temp_expr1 = ((object) (global::haxe.lang.Runtime.callField(v1, "add", 4846113, new object[]{v2})) );
```

First what you see is that arguments to add function are objects (Dynamic type in Haxe). Then you see a callField function which involves a lookup for add function, called using objects instead of specialized types for (much) better performance. In short: Reflection is used,

Here is an example how to change that

```haxe
typedef VectorType<T> = {
    public var x: Float; 
    public var y: Float;
    public var ?z: Float; 
    public var ?w: Float;
    //-------------------
    // Common operators  
    //-------------------
    public function add( b:T ): T;
}

@:forward( add )
abstract VectorX<T:VectorType<T>>( T ) from T to T {
    public inline
    function new( m: T ){
        this = m;
    }
//   @:generic -> won't generate function, avoid it, use inline instead
    @:op(A + B) public static inline
    function adder<T>(a:VectorType<T>, b) {
       return b = a.add( b );
    }
}

class Test {
    public static function main() {
        var v1 = new VectorX(new VectorXYZW());
        var v2 = new VectorX(new VectorXYZW());
        v1 + v2;
    }
}
```
 
which generates

```C#
global::VectorXYZW this1 = new global::VectorXYZW();
global::VectorXYZW v1 = ((global::VectorXYZW) (this1) );
global::VectorXYZW this2 = new global::VectorXYZW();
global::VectorXYZW v2 = ((global::VectorXYZW) (this2) );
{
	global::VectorXYZW b = v2;
	b = v1.@add(b);
}
```

No objects, no dynamic access. Just specialized type(s) and a direct call to add (no Reflection)

**Comment by RealyUniqueName** [comment]
Closing because there is no issue in the initial sample.
As I said earlier:
> `T` and `VectorType<T>` in `adder` function are not the same or compatible types. 

That's why compiler emits the error.
