### ISSUE TITLE
[jvm] crash but exit code is zero

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9225]
```haxe
class Main {
	static function main() {
		haxe.Timer.delay(function() trace(NonExistent), 1000);
	}
}

extern class NonExistent {}
```

It has to be in a Timer callback, I suspect it is about threads.

**Comment by Simn** [comment]
That's normal without any synchronization. See #8153.

**Comment by kevinresol** [comment]
actually this issue contains 2 problems:

1. code compiled without checking the existence of the class
2. thread crash leads to incorrect exit code

**Comment by Simn** [comment]
> code compiled without checking the existence of the class

I mean, it is an `extern`, so that's normal too.

**Comment by kevinresol** [comment]
alright

**Comment by Simn** [comment]
We should make `haxe.Timer.delay` consistent across targets, so if it waits on non-threaded ones it should wait on threaded ones as well. This requires addressing #8153 first and then making sure all targets use non-daemon threads for this.

**Comment by Simn** [comment]
This has already been addressed for the jvm target and I don't think it affects any other (important) targets.
