### ISSUE TITLE
immediately-bound constructor closures create redundant functions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9227]
We can do better when handling `.new.bind`, since that will currently create two closures (one for `.new` and one for `.bind`):

```haxe
class Main {
	function new(a:Int, b:Int) {}

	static function main() {
		var f = Main.new.bind(1);
		f(3);
	}
}
```

current output:
```js
var f = function(a,b) {
	return new Main(a,b);
};
var f1 = function(b1) {
	return f(1,b1);
};
f1(3);
```

could be:
```js
var f = function(b) {
	return new Main(1,b);
};
f(3);
```

Probably this could be solved with some more general local function folding optimization, but since `.new.bind` is relatively common case (e.g. we at innogames are embracing it for type-safe factories), it would be nice to have a specific handling for `.new.bind` chain soon-ish.

**Comment by RealyUniqueName** [comment]
I'll try to check it for 4.1.

**Comment by nadako** [comment]
Thanks, this is so much better now!
