### ISSUE TITLE
[server] compilation server false positive with @:pure

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9238]
Sorry that this is not isolated at all, but this seems like an important issue.

To reproduce:

- clone https://github.com/vshaxe/haxe-TmLanguage
- `npm install`
- if you like, change the Haxe version in `.haxerc` to a Haxe dev path, but it's already at a recent nightly
- start a compilation server with `npx haxe --wait 7000`
- run `npx lix run vshaxe-build -t tm-language-tests --connect 7000 -v` to produce the following error:

```
hxnodejs/12.0.0/haxelib/src/Sys.hx:136: lines 136-138 : Impure field overrides/implements field which was explicitly marked as @:pure        
haxe/std/haxe/io/Output.hx:85: characters 2-28 : Pure field is here
```

It does not reproduce if you change the Haxe version in `.haxerc` to 4.0.5, which makes this a regression. It also doesn't reproduce when compiling without `--connect`, which confirms it's a compilation server-specific problem.

**Comment by RealyUniqueName** [comment]
Duplicates #9029
