### ISSUE TITLE
Improve error message when trying to access a private type

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9243]
```haxe
private class Main {
	static function main() {
		trace("Test");
	}
}
```

```
>haxe -main Main
Module Main does not define type Main
```

I feel like the error here is slightly confusing / misleading: the module _does_ define the type, it's just not accessible. `Cannot access private type Main` would be nicer, just like the `Cannot access private field <name>` error we already have for fields.

**Comment by nadako** [comment]
Hmm, this probably does not error in my module-statics branch...
