### ISSUE TITLE
Fatal error: mbedtls/debug.h: No such file or directory

### ISSUE THREAD

**Issue by decahedron1** [HaxeFoundation/haxe#9251]
Hi there, I'm trying to build Haxe with OCaml 4.02.3 and dune 1.11.4. When I try running make however, I get this error:

```
File "libs/javalib/jData.ml", line 1:
Error: Some fatal warnings were triggered (2 occurrences)
    ocamlc libs/mbedtls/mbedtls_stubs.o (exit 2)
(cd _build/default/libs/mbedtls && /home/admin/.opam/4.02.3/bin/ocamlc.opt -g -ccopt -O -ccopt -fno-defer-pop -ccopt -Wall -ccopt -D_FILE_OFFSET_BITS=64 -ccopt -D_REENTRANT -ccopt -O -ccopt -fPIC -ccopt -g -o mbedtls stubs.o mbedtls stubs.c)
mbedtls_stubs.c:21:10: fatal error: mbedtls/debug.h: No such file or directory
  #include "mbedtls/debug.h"
                ^~~~~~~~~~~~
compilation terminated.
```

**Comment by RealyUniqueName** [comment]
If you're building on Windows, then you need this: https://github.com/Simn/mingw64-mbedtls

**Comment by decahedron1** [comment]
I'm building on Ubuntu 18.04 LTS.

**Comment by RealyUniqueName** [comment]
Huh, I'm building on Ubuntu 18.04 LTS too and I didn't have any issues. Do you have libmbedtls-dev installed? If you don't, try `$ sudo apt install libmbedtls-dev`

**Comment by NQNStudios** [comment]
I ran into this bug while trying to build on Windows, and the suggested fix worked after I figured out how to install it. This fix should probably be added to [BUILDING.md](https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md) -- I can do that myself after I sort through any other problems.

**Comment by Simn** [comment]
This is different though because he's on Ubuntu, which has nothing to do with the Windows-specific mess I've made.

**Comment by NQNStudios** [comment]
Right, it's a separate issue. Updating the docs would solve my problem but not the OP's.

**Comment by hlizard** [comment]
> 
> 
> If you're building on Windows, then you need this: https://github.com/Simn/mingw64-mbedtls

https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-mbedtls-2.16.5-1-any.pkg.tar.xz
I use this(unzip to cygwin64\usr\x86_64-w64-mingw32\sys-root\mingw), build passed too!

**Comment by rajhlinux** [comment]
I'm using windows getting the same error, how is everyone able to fix this error with those packages they are downloading?

I installed the make.exe and get errors.

Thanks.
