### ISSUE TITLE
[JVM] java.lang.reflect.Method has no field getParameterCount

### ISSUE THREAD

**Issue by Ilir-Liburn** [HaxeFoundation/haxe#9254]
java.lang.reflect.Method has no field getParameterCount (Suggestion: getParameterTypes)

```haxe
@:multiType
abstract Zero<T>(Null<T>) {
    public function new();

    @:to public static inline function toFloat(v:Float):Float return 0;
}

class Main {
    public static function main()  {
        var z:Zero<Float> = null;
        trace(z);
    }
}

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
```

**Comment by RealyUniqueName** [comment]
According to java docs `getParameterCount` was added in Java 1.8: https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Method.html#getParameterCount--

I have the same error and here is my `java -version`:
```
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

**Comment by Simn** [comment]
Can you confirm that it works if you replace it with `getParameterTypes().length` (in jvm/Jvm.hx)?

Also I think this means that @Ilir-Liburn's hxjava is outdated.

**Comment by RealyUniqueName** [comment]
> Can you confirm that it works if you replace it with getParameterTypes().length (in jvm/Jvm.hx)?

Yes, it works.

**Comment by Ilir-Liburn** [comment]
I have latest Haxe build on Windows and Linux, plus Java (openjdk 11 on Linux) and hxJava as well. Error I'm getting now is:

```
Error: Unable to initialize main class haxe.root.Main
Caused by: java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    haxe/root/Main.main()V @1: dstore_0
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @1
    flags: { }
    locals: { }
    stack: { null }
  Bytecode:
    0000000: 0147 b200 1326 b800 19bb 001b 5912 1d12
    0000010: 1f10 1312 20b7 0024 b600 2ab1
```

previously reported here https://github.com/HaxeFoundation/hashlink/issues/302 (I skipped JVM issue report due to early development stage)

**Comment by Gama11** [comment]
You might want to open a separate issue for that one.

**Comment by Ilir-Liburn** [comment]
Let's wait for @Simn and @RealyUniqueName before doing that
