### ISSUE TITLE
@:structInit default argument regression

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9258]
```haxe
@:structInit
class Main {
	function new(a:Int = 3, b:String = "Hi") {}

	static function main() {
		var a:Main = {};
		trace(a);
	}
}
```

will generate

```js
var Main = function(a,b) {
	if(b == null) {
		b = "Hi";
	}
	if(a == null) {
		a = 3;
	}
};
Main.main = function() {
	console.log("src/Main.hx:7:",new Main(3,3));
};
```

As said on Slack, I'm not sure why don't we generate `null` at the call sites, since I think optional arguments must always be "nullable" from the outside, so there might be something else wrong there as well.

**Comment by Simn** [comment]
Wasn't there some special situation regarding nullability and optional arguments on the Flash target?

**Comment by nadako** [comment]
> Wasn't there some special situation regarding nullability and optional arguments on the Flash target?

Yes that's what @RealyUniqueName mentioned as well, but without knowing the details this looks like an target inconsistency to me. On the other hand it should be safe to use call-site defaults for constructors anyway...
