### ISSUE TITLE
[cppia] segfault on null pointer

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#9261]
Since e15c0211300d81894308c1c7bed53d58991ca2bd cppia unit tests are segfaulting.
That change made analyzer to keep some code, which were previously removed.
I looked into diffs of `-D dump=pretty` before and after that change.

These lines are no longer eliminated by analyzer (assignments are compiled as property setters):
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/std/sys/Http.hx#L404
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/issues/Issue2750.hx#L33
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/issues/Issue3914.hx#L39
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/issues/Issue4987.hx#L8
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/TestIO.hx#L31
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/MyClass.hx#L225
Here `foo` call and `.length` field access are now kept (array access is not changed):
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/issues/Issue4986.hx#L7

Other than those there is a bunch of auto-generated `@:pure(true)` no longer generated. And a couple of additional temp vars in places of `+=`.

**Comment by RealyUniqueName** [comment]
Commenting out this line fixes segfault:
https://github.com/HaxeFoundation/haxe/blob/fbeac98f865bab5a21158117e1aad3b0bba77570/tests/unit/src/unit/issues/Issue4986.hx#L7

**Comment by RealyUniqueName** [comment]
Actually, just removing `foo` call fixes it. Committed a workaround for now.

**Comment by hughsando** [comment]
What is v[0] supposed to be - a null Array<Float> ?

**Comment by RealyUniqueName** [comment]
Yes, I think it should return `null`.

**Comment by RealyUniqueName** [comment]
So, it's a null pointer exception. Isn't debug build supposed to print a meaningful error message in such case?

**Comment by Simn** [comment]
See #8452

**Comment by RealyUniqueName** [comment]
That means ` -D HXCPP_CHECK_POINTER` and `-debug` has no effect on cppia behavior related to null pointers.

**Comment by Simn** [comment]
Should this be labeled as a regression?

**Comment by RealyUniqueName** [comment]
I guess it was always like that for cppia, so it's not a regression.
