### ISSUE TITLE
genericBuild broken when built with function in sub-type

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9271]
```haxe
// Main.hx
@:genericBuild(Main.build())
class Main {
	static function main() {
		var sub:Sub = null;
	}
}

@:genericBuild(Main.Sub.build())
class Sub {}

// Main.macro.hx
class Main {
	public static function build() {
		trace('build main');
		return macro:Dynamic;
	}
}

class Sub {
	public static function build() {
		trace('build sub');
		return macro:Dynamic;
	}
}
```

Expected to trace `build main` and `build sub`,
But traced `build sub` twice since 36fd5a811d52ad8cc073c7a690f8d95eab018c73

**Comment by nadako** [comment]
Should be fixed now, leaving the issue open because:
 - need to add test for it and
 - i don't understand yet how 36fd5a8 could break it. the issue seems to have always been there, and yet it all worked _somehow_ ^^

**Comment by nadako** [comment]
Oh and by the way, thanks for the perfect bug report \o/

**Comment by nadako** [comment]
> * i don't understand yet how [36fd5a8](https://github.com/HaxeFoundation/haxe/commit/36fd5a811d52ad8cc073c7a690f8d95eab018c73) could break it. the issue seems to have always been there, and yet it all worked _somehow_ ^^

I still don't understand this, but the weather is too good to spend time on this, so I just added a test \o/
