### ISSUE TITLE
[js] local var renaming regression

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9281]
(found in SauceLabs.hx)

```haxe
class Main {
	static function main() {
		var a = [1,2];
		function f() {
			var a = a;
			trace(a); // undefined, but should be [1,2]
		}
		f();
	}
}
```

I assume that because JS has this hoisting rules, `var a = a` is basically the same as `var a; a = a;`, so the `a` from outer scope is lost. We have to detect that and add a number in these cases.

**Comment by nadako** [comment]
Also, ES6 `let` has similar issue:
```js
let a = [1,2];
var f = function() {
	let a = a;
	console.log("src/Main.hx:6:",a);
};
f();
```
will fail with `ReferenceError: Cannot access 'a' before initialization`

**Comment by RealyUniqueName** [comment]
Note: ES6 also fails here:
```js
let a = [1,2];
var f = function() {
	console.log(a); // ReferenceError
	let a = 123;
	console.log(a);
};
f();
```
