### ISSUE TITLE
"Recursive inline is not supported" with null safety and vshaxe build server

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe#9287]
`pack/Main.hx`
```haxe
package pack;

class Main {
	static function main() {}
}
```

`build.hxml`
```hxml
--main pack.Main
--macro nullSafety("pack", Strict)
```

Running it at least twice will give
```
> Executing task: haxe --connect 6000 build.hxml <

(unknown) : Recursive inline is not supported
(unknown) : For optional function argument 'mode'
The terminal process terminated with exit code: 1
```

Changing `Strict` to `Loose` gives the same error, removing (`--macro nullSafety("pack")`) doesn't show the problem.

I cannot reproduce outside of vshaxe when manually running a compilation server.

Tested with haxe d6d4d3036adff61b50de780fe93b95d74339c68f and vshaxe 2.19.0

**Comment by RealyUniqueName** [comment]
Though I had the same error at some point, I can't reproduce it now neither with the latest dev Haxe nor with 4.0.5.
I'm using release version of vshaxe.
