### ISSUE TITLE
abstract `this` modification lost in tempvaring

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9290]
(sorry if this is a duplicate, I couldn't find a related issue)

```haxe
abstract A(Int) from Int {
	public var x(get,set):Int;
	extern inline function get_x() return this;
	extern inline function set_x(value) return this = value;
}

class Main {
	static var a:A = 1;

	static function main() {
		a.x += 2;
		trace(a);
	}
}
```

generated code (prints `1`, but should print `3` or emit a compile-time error):

```js
Main.main = function() {
	var _g = Main.a;
	_g = _g + 2;
	console.log("src/Main.hx:12:",Main.a);
};
```

In some other `this` modification cases we have this `Cannot modify the abstract value, store it into a local first` error, so if we can't make this "just work" it would be fair to raise this error in this case as well instead of silently generating wrong code.

**Comment by nadako** [comment]
FYI this is the same with `-D analyzer-optimize` (it just eliminates the `_g` and operations on it and leaves the `Main.a` trace).

**Comment by nadako** [comment]
This is a bit unfortunate for an abstract like `Color`, because something like `color.a += 0.3` will just not work.

**Comment by RealyUniqueName** [comment]
Same with Haxe 4.0.5 and 3.4.7. I wonder why such a basic usage issue was not reported earlier.
