### ISSUE TITLE
[cs] static methods from C# std dll are marked as final

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9292]
It doesn't make sense for static methods to be `final` in Haxe:

![](https://i.imgur.com/m8JhdZb.png)

from https://api.haxe.org/cs/system/collections/ArrayList.html

Same for completion:

![](https://i.imgur.com/NRaWdpw.png)

**Comment by RealyUniqueName** [comment]
Fixed in https://github.com/HaxeFoundation/haxe/commit/b51adecd2f87efa0ba23d0aee546241ae846869e
