### ISSUE TITLE
[display][cs] toplevel completion contains "PrivateImplementationDetails" classes

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9293]
Toplevel completion on the C# target seems to contain a lot of nonsense that should probably be hidden:

![](https://i.imgur.com/Whux3ok.png)

**Comment by nadako** [comment]
It's better now, however there's still this `<Module>` ending up in the completion. This requires looking into the DLL to figure out what else should be checked besides `CompilerGeneratedAttribute`.

![image](https://user-images.githubusercontent.com/49749/78691218-ad200200-78f8-11ea-9b51-b6ae369dec14.png)
