### ISSUE TITLE
Completion displayed while not requested

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9294]
I think this is similar to #8752, but using another case.

Calling `haxe.macro.Context.getType("")` in macro will give completion result instead of an error.

**Comment by RealyUniqueName** [comment]
Looks very similar to https://github.com/HaxeFoundation/haxe/issues/6499

**Comment by ncannasse** [comment]
Yes, except it was closed and it still reproduces ;)

**Comment by Simn** [comment]
Uhm, I wanted to rely on physical equality for this, but then I changed it back to structural equality in https://github.com/HaxeFoundation/haxe/commit/3e7f36879a9043112e55adc6cdb0bc8e4c2f8fdf for some reason...

**Comment by nadako** [comment]
Does `magic_type_path` have to be an empty-string-named one? if the idea was to use phyiscal equality, some unique string (e.g. `" - display - "` like for `magic_display_field_name`) would work as well.
