### ISSUE TITLE
[java/jvm] use java.security.MessageDigest for more haxe.crypto.classes

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9298]
Similarly to 1cd7785231885c9aaf8cf3df35eac5f0e23fc117 it should be done for at least Sha1 and Sha256, because it is a lot faster than the Haxe implementation.

Also we might want to profile what exactly makes Haxe implementation so slow, because improving it will benefit all the targets that don't use native functions.

**Comment by Simn** [comment]
It uses `Array<Int>`, which means boxing.

**Comment by nadako** [comment]
Hm, I wonder if `haxe.ds.Vector<Int>` is better. It should be, but I vaguely remember it was actually slower than Array on... JS?

**Comment by Gama11** [comment]
>A Vector is a storage of fixed size. It can be faster than Array on some targets, and is never slower.

Hm... :D

**Comment by Simn** [comment]
#8040

**Comment by nadako** [comment]
Gotta check if all the runtimes support SHA-224, because apparently the official spec only requires MD5, SHA-1 and SHA-256.

**Comment by nadako** [comment]
Oh well
