### ISSUE TITLE
js.lib.RegExpMatch extern misses `groups` member

### ISSUE THREAD

**Issue by sianahoret** [HaxeFoundation/haxe#9300]
RegExp in Javascript allows to use named capture groups. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges

If you do, the result should contain `groups` member.
It's missed in js.lib.RegExpMatch extern (https://github.com/HaxeFoundation/haxe/blob/4.0.5/std/js/lib/RegExp.hx#L44)

Example & proof:
```haxe
import js.lib.RegExp;

class TestRegexp {
  static public function main(): Void {
    var s = "Haxe EReg class does not support named capture groups";
    var re = new RegExp("(?<className>\\S*)\\s*class");
    var res = re.exec(s);

// Without `untyped` below the compiler will raise "Null<js.lib.RegExpMatch> has no field groups" error.
    untyped trace('Regular expressions in Haxe are implemented by ${res.groups.className} class.');
  }
}
```

**Comment by nadako** [comment]
I wonder if we should really add it, given that apparently [Firefox does not support it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility) (so it's not cross-platform at all)?

**Comment by Gama11** [comment]
Hm, it could perhaps still be useful in an environment like Node.

**Comment by sianahoret** [comment]
I don't consider the issue critical, 
I just was upset a bit (by the fact that neither EReg nor js.lib.RegExp allow to use the feature) and nothing more :)

**Comment by sianahoret** [comment]
Just FYI: https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2018.regexp.d.ts#L22

For ES5 it wasn't declared anyhow of course: https://github.com/microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L909

What's the Haxe approach to version-dependent features in extern classes declarations?

**Comment by nadako** [comment]
Well, we have `js_es` define that changes how some things are generated, but I'm not sure if it's a good idea to hide fields behind such a version check... Maybe we should add it and be done with it.

**Comment by nadako** [comment]
Oops, wrong button.

**Comment by nadako** [comment]
I'll reopen this because I want to add some documentation to the RegExp APIs.
