### ISSUE TITLE
Having macro instance suggestion

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9301]
Hej all !

I'm sorry, I don't know where to put suggestions, so I try here.
According to this question : https://community.haxe.org/t/macro-instance/2347/13
I would suggest if it's not too much work to have macro instances.
Kevin wrote "Technically speaking, you can have instances in the macro context. But there is no way (syntax) to interact with that in the normal context."

Thanks for reading

**Comment by ncannasse** [comment]
That should go with a formal proposal on https://github.com/haxeFoundation/haxe-evolution

**Comment by filt3rek** [comment]
Hi Nicolas, 
I hope you're going fine. 
I'm sorry I didn't know where to put that, thanks for your reply !
