### ISSUE TITLE
[js][es6] more issues with var renaming and ES6 let

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9308]
This one is pretty trippy and there are probably multiple issues here, even without ES6...

So the following code fails to load with `SyntaxError: Identifier '_g1' has already been declared` when compiled with `-D js-es=6`:

```haxe
enum E {
	A;
	B;
}

class Main {
	static var n:Int = 3;
	static var e:Null<E> = A;

	static function main() {
		switch (e) {
			case A:
				// commenting this trace makes it work...
				trace("hi");

				for (i in 0...n) {
					trace(i);
				}

			case B:
				for (i in 0...n) {
					trace(i);
				}

			// commenting this default removes the nullcheck for `e`
			// and makes it work...
			default:
		}
	}
}
```

The problematic generated code is (note the double `_g1` which is apprently not fine for ES6 `let`):
```js
static main() {
	let _g = Main.e;
	if(_g != null) {
		switch(_g._hx_index) {
		case 0:
			console.log("src/Main.hx:14:","hi");
			let _g = 0;
			let _g1 = Main.n;
			while(_g < _g1) {
				let i = _g++;
				console.log("src/Main.hx:17:",i);
			}
			break;
		case 1:
			let _g1 = 0;
			let _g2 = Main.n;
			while(_g1 < _g2) {
				let i = _g1++;
				console.log("src/Main.hx:22:",i);
			}
			break;
		}
	}
}
```

Now if we comment that `trace("hi")`, the renaming will be done correctly.
Also the renaming will be correct if we comment `default:`, but that will also remove the null check around the `switch` (same behaviour with ES5).

Note that with ES5, no matter what, there is no renaming inside switch branches going on:

```js
case 0:
	var _g = 0;
	var _g1 = Main.n;
	while(_g < _g1) {
		var i = _g++;
		console.log("src/Main.hx:14:",i);
	}
	break;
case 1:
	var _g = 0;
	var _g1 = Main.n;
	while(_g < _g1) {
		var i = _g++;
		console.log("src/Main.hx:19:",i);
	}
	break;
}
```

Which almost looks like some forgotten recursion step.

**Comment by RealyUniqueName** [comment]
There's no need for additional renaming in es5, because those vars don't overlap at runtime.
