### ISSUE TITLE
Importing a private type from the same module errors

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9309]
I'm not sure if it's correct that this produces an error, since we're in the same module and have access anyway:

```haxe
import Main.PrivateType;

class Main {
	static function main() {}
}

private class PrivateType {}
```

```
source/Main.hx:1: characters 8-24 : You can't import a private type
```

Sure, it's redundant and should produce an "unused import" diagnostic, but should it error?

**Comment by RealyUniqueName** [comment]
Idk... How do you even get in a situation like this?

**Comment by kevinresol** [comment]
Similar to https://github.com/HaxeFoundation/haxe/issues/8145 ?

**Comment by Gama11** [comment]
@RealyUniqueName I managed to break CI this way because there was a redundant import and I made the type private. :)

**Comment by RealyUniqueName** [comment]
Ok. Then I think it should not error.
