### ISSUE TITLE
[display] auto-triggered case completion vs string interpolation

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9311]
Originally reported at https://github.com/vshaxe/vshaxe/issues/426.

The expected result here is to get _no_ completion results if the completion was auto-triggered, so that you can press Enter without accidentally inserting a random keyword from completion.

Note: this is only an issue with auto-triggered completion, i.e. when typing the `:` rather than just pressing ctrl+space after it. The behavior for the latter case is correct.

___

```haxe
enum WsType {
	Connected;
}

class Main {
	static function main() {
		final type = Connected;
		trace('${type}'); // no problem with '$type'
		switch (type) {
			case Connected:
		}
	}
}
```
![image](https://user-images.githubusercontent.com/8753432/78689722-536f0600-78ff-11ea-8f16-6284e78da58e.png)

**Comment by RblSb** [comment]
This happens everytime now (after pressing `:`)
```haxe
class Main {
	static function main() {
		switch 0 {
			case 0|
		}
	}
}
```
<img width="377" alt="image" src="https://user-images.githubusercontent.com/8753432/165110774-f1602b17-5bbb-409d-8a81-419846407222.png">

**Comment by RblSb** [comment]
Fixed in https://github.com/vshaxe/haxe-language-server/pull/61
