### ISSUE TITLE
double final initialization possible with field init + constructor assignment

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9313]
This compiles, but it shouldn't because there's double final init.

```haxe
class A {
	final x = 1;
	function new(x) {
		this.x = x;
	}
}
```

I labelled this with `haxe-foundation-partner`, because we're seeing this a lot due to the state of our post-conversion code, but it's not blocking or urgent to fix.

**Comment by Gama11** [comment]
Not sure it's really a "bug", more of a design decision.

**Comment by nadako** [comment]
We discussed it on Slack before and IIRC the consensus was that this is an oversight that is a bit annoying to fix, I just never reported it.

**Comment by nadako** [comment]
Note that fixing this might break #7183, because I think that `@:structInit` currently kind of depends on this bug, e.g.:

```haxe
@:structInit
class C {
	final x:Int = 0;
}
```

will generate

```js
class C {
	constructor(x) {
		this.x = 0;
		if(x != null) {
			this.x = x;
		}
	}
}
```

while it should really generate

```js
class C {
	constructor(x) {
		if(x == null) {
			x = 0;
		}
		this.x = x;
	}
}
```

**Comment by Simn** [comment]
I don't consider this a bug. We've designed it so multiple assignments in constructors would be allowed and this is just a variant of that.

**Comment by nadako** [comment]
I vaguely remember discussions about multiple assignments, but was it really "design"? IMO this is not ideal, it should be single assignment per code path (a slightly modified unitialized var check might work?)

**Comment by nadako** [comment]
BTW:

> 09:16
simn This should error

**Comment by Simn** [comment]
I probably said this thinking that multiple assignments were already disallowed because your example focuses on a variable with an initialization instead of the much more straightforward `this.x = x; this.x = x;` case.

**Comment by Simn** [comment]
Reading this again, as long as duplicate initialization at expression-level is allowed, this version of it should be allowed as well.
