### ISSUE TITLE
[display] broken hover for inferred catch variable

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9319]
Related to #9269.

```haxe
class Main {
	static function main() {
		try {} catch (e) {}
	}
}
```

![](https://i.imgur.com/zP4lNiu.png)

I expected to see `e:haxe.Exception` on hover over `e`, instead the entire try-catch range is highlighted.

**Comment by nadako** [comment]
Gama11, man who ~shoots~ creates issues faster than his shadow

**Comment by Gama11** [comment]
Somehow I knew IDE support for this was going to be broken.. :D

**Comment by Gama11** [comment]
Wait... I had the wrong Haxe version selected. Nothing to see here...

(except, maybe good opportunity to add a test? x))

**Comment by RealyUniqueName** [comment]
A test of what?

**Comment by Gama11** [comment]
That you get `haxe.Exception` on hover here?
