### ISSUE TITLE
Specifying @:generic on the type parameter (feature)

### ISSUE THREAD

**Issue by ErikRikoo** [HaxeFoundation/haxe#9322]
This issue suggests a little feature on the @:generic metadata:

If you have a class with multiple generic types, you may need, for performance, to use the @:generic metadata, but only on one of the type parameters. 
We would need a way to specify that, like:
```haxe
class A<@:generic T1, T2> {}
```
Then, the class `A<Int, _>` would be different to the class `A<String, _>`.
But not `A<Int, Int>` and `A<Int, String>`

**Comment by Simn** [comment]
#6585
