### ISSUE TITLE
[lua] Error: attempt to index local '_g1' (a nil value)

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#9323]
When trying to build/test the [haxe-strings](https://github.com/vegardit/haxe-strings) library with lua, I am getting this [error](https://travis-ci.com/github/vegardit/haxe-strings/jobs/320533249#L171):
```
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
build-lua.4
> haxe -lua bin/lua/tests.lua -lib travix -lib haxe-strings tests.hxml
> lua bin/lua/tests.lua
lua: bin/lua/tests.lua:1818: attempt to index local '_g1' (a nil value)
stack traceback:
	bin/lua/tests.lua:1818: in function 'getBytes'
	bin/lua/tests.lua:71053: in function 'super'
	bin/lua/tests.lua:71048: in function 'new'
	bin/lua/tests.lua:71524: in function '_hx_static_init'
	bin/lua/tests.lua:71580: in main chunk
	[C]: in ?
```

The Haxe generated code that Lua fails to interprete is this:
```lua
__haxe_Resource.new = {}
__haxe_Resource.__name__ = "haxe.Resource"
__haxe_Resource.getBytes = function(name) 
  local _g = 0;
  local _g1 = __haxe_Resource.content;
  while (_g < _g1.length) do -- <<< error happens here
    local x = _g1[_g];
    _g = _g + 1;
    if (x.name == name) then 
      if (x.str ~= nil) then 
        do return __haxe_io_Bytes.ofString(x.str) end;
      end;
      do return __haxe_crypto_Base64.decode(x.data) end;
    end;
  end;
  do return nil end;
end
```

Any help is greatly appreciated.

**Comment by RealyUniqueName** [comment]
Which Haxe version are you using? If it's the latest development, please try 4.0.5.
This is probably caused by the recent var renaming change.

**Comment by nadako** [comment]
Well the code seems correct, it's `__haxe_Resource.content` that is apparently null.

**Comment by sebthom** [comment]
> Which Haxe version are you using? If it's the latest development, please try 4.0.5.
> This is probably caused by the recent var renaming change.

It is happening for 4.0.5 and development.

**Comment by jdonaldson** [comment]
I changed the initialization order in a recent commit.  Your test suite is still not passing, but perhaps the key blockers are addressed now.  https://github.com/HaxeFoundation/haxe/commit/adc9ed1b25d76575f6535e9d997324455d2319cb

**Comment by sebthom** [comment]
@jdonaldson looking at the latest [test run](https://travis-ci.com/github/vegardit/haxe-strings/jobs/321602925) I can see that this commit solves this issue. I see one test failure but that is not related and I have to track down the cause separately.

Thank you!

**Comment by sebthom** [comment]
@jdonaldson looking at the latest [test run](https://travis-ci.com/github/vegardit/haxe-strings/jobs/321602925) I can see that you commit solves this issue. I see one test failure but that is not related and I have to track down the cause separately.

Thank you!
