### ISSUE TITLE
@:using vs private (extension) class

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#9324]
Hi,
I'm not sure if I can call it a bug... 
But I found private modifier behavior a bit weird in case of `@:using` feature.

Check this sample:
```haxe
@:using(Dummy.DummyTools)
enum Dummy {
	Some(v:String);
	Else;
}

class DummyTools {
	public static function value(t:Dummy):String {
		return switch t {
			case Some(v): v;
			case Else: "";
		}
	}
}
``` 
And it will work fine! 
But in the current case, I prefer to keep `DummyTools` class private, because I won't use it anywhere else except the current module. 

But! If I'll do `private class DummyTools`, then it will not work because `@:using(Dummy.DummyTools)` will tell me that `Module Dummy does not define type DummyTools`. 
And it sounds reasonable, because `DummyTools` is private now and it cannot be visible as part of `Dummy`, but in another hand, it is weird because private classes should be visible in the current module... 

I don't know how hard it may be to implement, but it would be nice to accept private classes in `@:using`, which are defined in the same module.

Thank you!

**Comment by RealyUniqueName** [comment]
I agree this should work

**Comment by kevinresol** [comment]
#8145

**Comment by RealyUniqueName** [comment]
Closing as a duplicate
