### ISSUE TITLE
[display ]__o${dependencies.length} error

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9326]
haxe: dev 4-17 nightly build 
 
os:windows-7

    {
        "resource": "/d:/project/TEST/Error",
        "owner": "_generated_diagnostic_collection_name_#10",
        "code": "2",
        "severity": 8,
        "message": "\"__o${dependencies.length}\" is not a valid function argument name",
        "source": "diagnostics",
        "startLineNumber": 1,
        "startColumn": 1,
        "endLineNumber": 1,
        "endColumn": 1
    }

**Comment by Gama11** [comment]
How can this be reproduced?

**Comment by sonygod** [comment]
it's random show。I can't  reproduced.

**Comment by back2dos** [comment]
I bet this is one of the cases where string interpolation in macros stops working with compiler server.

**Comment by RealyUniqueName** [comment]
We still need more data to be able to do something.

**Comment by sonygod** [comment]
after https://github.com/HaxeFoundation/haxe/commit/717c4061d0db9e2160d36decd4753d1e755736f1

it seems fixed.
