### ISSUE TITLE
Work around lack of defined static initialization order for haxe.Resource.

### ISSUE THREAD

**Issue by jdonaldson** [HaxeFoundation/haxe#9329]
Haxe doesn't define static initialization order, and this causes some headache around defining some static resources through `haxe.Resource`.  

See https://github.com/HaxeFoundation/haxe/issues/9323 for more details.

**Comment by ncannasse** [comment]
Order is specified as :
`__init__` first (reserved for std library)
statics -- order is inferred but cannot be ordered with 100% accuracy
main()

I don't think that moving haxe.Resource from `__init__` to statics would improve things. Might as well make them worse ;)

**Comment by Gama11** [comment]
@ncannasse Huh, in what way is `__init__` reserved to the std lib?

**Comment by jdonaldson** [comment]
Let me update the lua target first then.  I have a note to myself indicating that `__init__` *needed* to go after static initialization, but perhaps I was somehow confused.

**Comment by ncannasse** [comment]
@Gama11 `__init__` is meant to run before any user code (static inits etc.) it can be used for various things such as actual initialization of a class (importing its value from some context etc.) or loading a native library, whatever. So it's not reserved for std per-se, but should not be used by user code.

**Comment by jdonaldson** [comment]
Closing this, the main issue for Lua is addressed.  I'm happy to talk about initialization order improvements, but that should first be a more general discussion.

**Comment by jdonaldson** [comment]
Closing this, the main issue for Lua is addressed.  I'm happy to talk about initialization order improvements, but that should first be a more general discussion.
