### ISSUE TITLE
[js] Constructible variable

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#9335]
This is a feature request that's come out of the dts2hx extern work. A very similar feature already exists in haxe: `@:selfCall`, the request is to add a sibling called `@:newCall` which generates slightly different code

In TypeScript anons and interfaces can have a 'construct' signature
```typescript
declare const Constructable: {
    new(): string;
}
// which enables
new Constructable()
```

To support this behavior when translating to haxe, it would be useful to haxe a new metadata `@:newCall`, so the externs would be implemented as
```haxe
var Constructable: {
    @:newCall construct(): String;
}
Constructable.construct(); // generates new Constructable()
```

The way @:selfCall currently works is
```haxe
var Example: {
    @:selfCall call(): String;
}
selfCall.call(); // generates Example()
```

So `@:newCall` would have the same implementation as `@:selfCall` but prepend `new`

**Comment by nadako** [comment]
I'm curious where it's actually useful, what does `new(): string` even mean? Could you provide a real-world example?

**Comment by nadako** [comment]
One tricky thing here is implementing closures on such functions.

**Comment by haxiomic** [comment]
It's a strangely common pattern in the typescript built-in types
https://github.com/microsoft/TypeScript/blob/7d4fc7333105ef426a5a6605a75b5febff2d40be/lib/lib.dom.d.ts#L4294

Top-level cases like that I can detect and promote to a class in haxe so we can avoid it there but the general case does seem to occur in the wild https://grep.app/search?q=new%5C%28%5B%5E%29%5D%2A%5C%29%5Cs%2A%3A&regexp=true&case=true&filter[lang][0]=TypeScript

**Comment by nadako** [comment]
Interestingly, this is another use-case for intersection types:

```ts
lexerCtor: {new(stream: CharStream): Lexer}
```

could be translated into

```haxe
lexerCtor: Class<Lexer & Constructible<(stream: CharStream)->Void>>
```

Also note that you cannot really use `@:newCall` for the things that you have to pass _from_ Haxe to JS, it only works when you want to use some native output and I'm still curious in which cases this is used in the wild :).

**Comment by haxiomic** [comment]
Constructible as an intersection types is a much better solution than `@:newCall`, I'll change the issue

**Comment by nadako** [comment]
Well this is a more general issue and I can't currently help much with it. Type intersections is something we all have to discuss first.

**Comment by benmerckx** [comment]
But the Type intersection doesn't help with constructing it from Haxe's side, does it?
https://try.haxe.org/#10739
As far as I know there's no way to construct something that Haxe considers a value right now (apart from js.Syntax.construct) so `@:newCall` is still useful I would think (and presumably a lot easier to implement).

**Comment by lublak** [comment]
You can theoretically use `Type.createInstance` https://api.haxe.org/Type.html#createInstance

https://try.haxe.org/#d6183

**Comment by haxiomic** [comment]
I've found the pattern occurs quite a few times in node.js

For example, node.js Buffer instances have a field called [`constructor`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cb19b1b38249b94d8ceeb2339d627c19972385bf/types/node/v11/globals.d.ts#L238), so you can do

```js
let secondBuffer = new firstBuffer.constructor()
```

I think in this case @:newCall could help (of course, something more sophisticated with Constructible would be ideal but that could be some way off)

In the meantime I'm going to try and find work arounds for the different constructor-type patterns used in TypeScript so we can avoid @:newCall all together and I'll update if I find a pattern that's impssible to work around

**Comment by haxiomic** [comment]
I think a generic build macro work around is possible so I'll close this in favor of that approach
