### ISSUE TITLE
Macro pos and line number pos

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9336]
Hej !

In the past (before Haxe 4), when using tink_template, and when an error occured in a template, the compiler reported the right line number in the template but since Haxe 4, it's not the case, it reports line number 1 and only the pos is right (the offset).

Juraj told that it's an compiler issue : "In macros, one can only specify file, start and end offset and it is the compiler that turns the character range into line/column." (whole discussion : https://community.haxe.org/t/html-templating/2381/9?u=filt3rek)

Can we make something to get it work again please ?

Cheers

**Comment by Simn** [comment]
Please provide a reproducible example.

**Comment by filt3rek** [comment]
This gives that error : `my_template.mtt:1: characters 32-35 : Unknown identifier : foo` (the line number isn't exact and before Haxe 4 it was good)
Main.hx :
```haxe
class Main {
    function main(){
        render();
    }
    @:template( "my_template.mtt" ) static function render();
}
```
my_template.hx :
```html
<div>&nbsp;</div>
::foo()::
```
build.hxml :
```
-lib tink_template
-main Main
-js app.js
```

**Comment by RealyUniqueName** [comment]
I've tried your sample with Haxe 3.4.7 and got the same error pointing to the first line. Are you sure the sample is correct for the issue?

**Comment by back2dos** [comment]
I've reduced it to this:

```haxe
class Main {
  #if !macro
  static function main(){
    fail();
  }
  #end
  static macro function fail() {
    var pos = haxe.macro.Context.makePosition({min: 21, max: 28, file: 'my_template.mtt' });
    trace(pos); // Main.hx:9: #pos(my_template.mtt:2: characters 2-9)
    haxe.macro.Context.parse('foo()', pos);
    trace(pos); // Main.hx:11: #pos(my_template.mtt:1: characters 21-28)
    return macro null;
  }
}
```

Seems to be the case since at least 3.2.1. 

With some random poking around, I was able to (unreliably) undo whatever side-effect `Context.parse` causes and I'd assume that the issue surfaced because some combination of changes in Haxe and tink impacted execution order.

**Comment by filt3rek** [comment]
Thanks for your help Juraj, I was lost at the end...

**Comment by RealyUniqueName** [comment]
General advice:
Don't use existing file names for `Context.parse` positions. The position data will be cached with the code parsed instead of the code in the real file.

**Comment by back2dos** [comment]
Could you elaborate on your advice please? After all, I do wish to point the position to the source file. What should I do instead?

**Comment by RealyUniqueName** [comment]
Ok, looks like it was another bug in `Context.parse`.
Now that advice relates only to `Context.parseInlineString`:
When you do `Context.parseInlineString(str, pos)`, and `pos.file` was not seen by the compiler yet, then the compiler will cache lines data obtained from `str` for the `pos.file` filename.
So, when you "stringify" any position involving that file, the compiler will report lines within `str`.
