### ISSUE TITLE
Allow multiple arguments in array access

### ISSUE THREAD

**Issue by ErikRikoo** [HaxeFoundation/haxe#9339]
**Changes:**
Currently, we can't have multiple arguments when we are accessing a variable with [].
It could be great if we could, at least in a macro.
In the standard library it would need a change in ExprDef, I propose this
```haxe
enum ExprDef {
   ...
   EArray(e1:Expr, e2:Expr);
   EArrayMultiple(e1:Expr, params:Array<Expr>);
   ...
}
```
Then it looks like the ExprDef for a function call. And we keep EArray for simple argument array access, then we don't break retro compatibility.

**Alternatives:**
- We could use a function call with multiple arguments but I think the purpose would be less clear than the array access. 
- We could also use chained array access but it would be less easy to know the count of array access.

**Remark:**
I don't propose to add the overloading of a multiple argument array access (even if it would be great), just changing the grammar to allow it. Then we could use it using macro.

**Comment by lublak** [comment]
Do you mean?:

```haxe
public static macro function someTestFn(expr:Expr) {
    // expr == EArrayMultiple(aFakeArray, [0, 1])
}
public static function main() {
    someTestFn(aFakeArray[0, 1]);
}
```

~Than you should use a function. An arrayaccess is always one expression (one index).~
~You say it is cleaner.~
~But what is the second argument, or the third or ....?~
~index1, index2, index3? This make no sence right?~

**Comment by Aurel300** [comment]
@lublak This type of indexing is often used e.g. in Python to express indexing into multi-dimensional structures. So `someMatrix[2, 5]` might express the 3rd row, 6th column of a matrix.

@ErikRikoo I think this might have to go through haxe-evolution? Most importantly, the change you propose is breaking for a lot of macros. A "softer" way (but still breaking) to do this might be to introduce `EArrayMultiple` (or similar) as an additional case; or adding an optional argument to `EArray` for the remaining indices …

**Comment by ErikRikoo** [comment]
Yes I edited my issue to keep EArray and an EArray multiple I think it would break less code. Because there is code that is dependant from EArray so adding a new argument to it would break some code.
I will write a proposal then and push it.
Thanks for your answers :)

Edit:
I created the [proposal](https://github.com/HaxeFoundation/haxe-evolution/pull/72).

**Comment by RealyUniqueName** [comment]
Closing this since there's now a proposal in haxe-evolution repo, and further discussion should go there.
