### ISSUE TITLE
Unusual variable names broken.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9340]
Greek symbols common in maths do not seem to be valid characters, is this something that could be easily changed if I collated suitable ascii codes or would this be really heavy to support?
```
var τ = 2*3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679;
```
Numerical.hx:17: character 9 : Invalid character 0x3C4

**Comment by lublak** [comment]
It is recommended not to use any special characters as variable or method names.
(Also in other languages).

Why do you want something like that? Just call it `tau`.
Its also easier to program with "simple names".

**Comment by Simn** [comment]
We have no plans to support this.

**Comment by nanjizal** [comment]
For future reference, this was quite quickly rejected, deeper discussion on the topic is covered here, if Go has this type of support it's not completely crazy concept but accept it may not be where Haxe wants to go.

https://news.ycombinator.com/item?id=1850938

- "Go supports unicode from the ground up. Strings are UTF-8, and any identifier can include unicode characters - you can name your Pi constant with the greek letter."
- "Perl 5 has been able to use UTF-8 identifiers for over a decade"
- "Perl 6, which both embraces Unicode and allows the programmer to create new operators from arbitrary collections of Unicode symbols."

- "Agda (http://wiki.portal.chalmers.se/agda). Not only does it allow the use of unicode in identifiers, but it uses them extensively throughout its standard library. After using Agda for a while, one quickly realises that most of the issues raised in this thread are rather unimportant. Having extra brackets, more equality symbols and greek letters available really does make code nicer to read when used judiciously."

- "Ω is a valid variable name in C#"

*My suggestion was to provide a limited subsection not all unicode I think for internal library algorithms it would be a useful expressive feature that allows for an algorithm to be more readable, but understand this is probably not a popular suggestion and is likely lots of effort to implement with potential future bugs*
