### ISSUE TITLE
UInt division inconsistent across targets

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9343]
I've only tested Flash and JS, so it might be a SWF-specific issue, but I don't know:

```haxe
class Main {
	static function main() {
		trace(getFloat()); // 1 on JS, -4294967295 on Flash
	}

	static function getFloat():Float {
		return getUInt() / 0xFFFFFFFF;
	}

	static function getUInt():UInt {
		return 0xFFFFFFFF;
	}
}
```

Changing `getFloat` body to `getUInt() / (0xFFFFFFFF : UInt)` makes it trace `1` consistently. On JS it is always `1` because generated code is always: `UInt.toFloat(Main.getUInt()) / UInt.toFloat(-1)`

**Comment by RealyUniqueName** [comment]
I think it only affects flash, because other targets use an abstract with `@:to function toFloat`

**Comment by RealyUniqueName** [comment]
Also affects C#

**Comment by Simn** [comment]
Flash and C# you say...
