### ISSUE TITLE
Python targeting ignored haxe class property `obj.value`, but force call `obj.get_value()` getter work.

### ISSUE THREAD

**Issue by healingdrawing** [HaxeFoundation/haxe#9348]
haxe class code.  
```haxe

package geometryxd;

/**
 * 3D dot object
 */
class Dot3D{
    /**
     * x coordinate of dot
     */
    var x:Float;
    /**
     * y coordinate of dot
     */
    var y:Float;
    /**
     * z coordinate of dot
     */
    var z:Float;
    
    /**
     * new 3D dot object.
     * @param x coordinate of dot
     * @param y coordinate of dot
     * @param z coordinate of dot
     */
    public function new(x:Float, y:Float, z:Float) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
    
    /**
     * array of dot coordinates `[x,y,z]`
     */
    public var value(get,never):Array<Float>;
    function get_value() {
        return [this.x,this.y,this.z];
    }
    
    /**
     * array of mirrored values of dot coordinates. If `value` = `[1,2,3]` then `valueM` = `[-1,-2,-3]`
     */
    public var valueM(get,never):Array<Float>;
    function get_valueM(){
        return AM.minus_F(value);
    }
}

```

python3 terminal output.  
```

Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from geo import geometryxd_Dot3D as Dot
GeometryXD is ready for use
>>> dot = Dot(1,3,3)
>>> dot.value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'geometryxd_Dot3D' object has no attribute 'value'
>>> dot.get_value()
[1, 3, 3]
>>> dot.x
1
>>> dot.y
3
>>> dot.z
3
>>> dot.valueM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'geometryxd_Dot3D' object has no attribute 'valueM'
>>> dot.get_valueM
<bound method geometryxd_Dot3D.get_valueM of <geo.geometryxd_Dot3D object at 0x7f615d848508>>
>>> dot.get_valueM()
[-1, -3, -3]

```

[link to github repo with full code](https://github.com/healingdrawing/gemm/tree/object-testing)

[property of Dot3D object which ignored](https://github.com/healingdrawing/gemm/blob/object-testing/GeometryXD/geometryxd/Dot3D.hx#L35)

[main class function which used Dot3D class](https://github.com/healingdrawing/gemm/blob/object-testing/GeometryXD/geometryxd/GeometryXD.hx#L1690)

kubuntu 18.04
haxe 4.0.5

**Comment by healingdrawing** [comment]
there is link to repo with full code
[githublink](https://github.com/healingdrawing/gemm/tree/object-testing)

**Comment by RealyUniqueName** [comment]
Haxe's properties are not supported by python runtimes.
At compile time Haxe compiler replaces `obj.value` by `obj.get_value`, but for the python runtime there is no relation between `obj.value` and `obj.get_value` so you have to manually use `obj.get_value` at python side.

**Comment by nadako** [comment]
We could support `@:python.property` to generate native python properties (IIRC it's `@property def value()` + `@value.setter def value()` or something like that). At this point I'm thinking that we need a generic framework for supporting target-native properties, because a lot of target languages have them.

**Comment by healingdrawing** [comment]
> We could support `@:python.property` to generate native python properties (IIRC it's `@property def value()` + `@value.setter def value()` or something like that). At this point I'm thinking that we need a generic framework for supporting target-native properties, because a lot of target languages have them.

sounds complex, for me. Just for case (i am sure 99% it out of my perception), can i look at file which convert haxe to python?
i tried search it, in the haxe repo, but no success.
First why i interesting uses python, because it very comfort for testing or fast trying something short, no need even browser and html as js case, just open terminal , and try things step by step.
Possibly haxe at this moment too have some terminal way uses some environments, which appear after 2016, and i miss it.

**Comment by nanjizal** [comment]
There is a gen class for each target that will deal with constructing classes and functions etc..
https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genpy.ml
standard parts of the core library are found here:
https://github.com/HaxeFoundation/haxe/tree/development/std/python
helpers within it:
https://github.com/HaxeFoundation/haxe/tree/development/std/python/internal
Python specific tests
https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/TestPython.hx

**Comment by healingdrawing** [comment]
thanx, as expected, i can do nothing helpful on my present level, just need observe from side, but now i am sure/understand it, and can relax and be quiet :+1:

**Comment by Aurel300** [comment]
@healingdrawing Just to point out if you want to quickly test small things, eval might be a better target – you just do `haxe --run Main` from the terminal and the code is compiled and immediately executed, without an in-between step involving another language.

**Comment by bendray** [comment]
May be this simple solution can works
```
#if python 
public static var value = python.Syntax.code("property(Dot3D.get_value, Dot3D.set_value)");
#else
```
