### ISSUE TITLE
[cs] Method type parameters drop nullability.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9351]
```haxe
class Main {
  static function main() {
    var x:Null<Int> = null;
    trace(eval(x));// 0
  }
  static function eval<X>(v:X) {
    return v;
  }
}
```

From this we get:

```cs
public class Main : global::haxe.lang.HxObject {
	
	public Main(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Main() {
		global::Main.__hx_ctor__Main(this);
	}
	
	
	public static void __hx_ctor__Main(global::Main __hx_this) {
	}
	
	
	public static void main() {
		global::haxe.lang.Null<int> x = default(global::haxe.lang.Null<int>);
		global::System.Console.WriteLine(((object) (global::Main.eval<int>((x).@value)) ));
	}
	
	
	public static X eval<X>(X v) {
		return v;
	}
	
	
}
```

The code has `Main.eval<int>` where it should probably have  `Main.eval<haxe.lang.Null<int>>`.

The easiest workarounds:

- `-D erase-generics` (if that's an option)
- use call site inlining (if that's an option)
- `var eval:Null<Int>->Null<Int> = eval` before making the call. Leads to `global::haxe.lang.Function eval = ((global::haxe.lang.Function) (new global::haxe.lang.Closure(typeof(global::Main), "eval", 1125936028)) );`, which is not exactly pretty, but behaves correctly

**Comment by RealyUniqueName** [comment]
Actually this is already fixed by a176acde2ea379b6625d1c43bb8b5190b1946f27
