### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by jstolarek** [HaxeFoundation/haxe#9352]
A quick question: what is the license for Haxe logo? Can I use it as an icon for my `exe` file?

**Comment by markknol** [comment]
It is not allowed to reuse the Haxe logo for a library or application for not edited by Haxe Foundation.

What kind of exe file are we talking about?

**Comment by jstolarek** [comment]
> What kind of exe file are we talking about?

This one: https://github.com/jstolarek/hashlink-launcher
At the moment it uses Haxe logo as an icon but if that is a violation of the license I will of course remove it.

**Comment by back2dos** [comment]
Some projects have a logo that is derived from the Haxe logo, yet clearly different, e.g. [hxdefold](https://github.com/hxdefold), [HaxeUI](https://github.com/haxeui), [HaxeFlixel](https://github.com/HaxeFlixel), [vshaxe](https://github.com/vshaxe), [NME](https://github.com/haxenme/nme/blob/master/README.md), etc. etc.

You can follow the same approach - in your case I wonder whether the Heaps / HashLink logo wouldn't make for a better candidate.

This is less a matter of "license", as it is of setting clear expectations for the user:

1. while related to the project that has the original logo, it's a different project (good for the users)
2. the authors of the original project take no responsibility for the derived tool (good for the authors)

If you take care to clearly distinguish your logo from the original to avoid confusion and yet let the origins be clear, everything is great. When in doubt, ask again - about the concrete derived logo ;)

**Comment by jstolarek** [comment]
Thanks. Allow me a few days to fix this up on my side.

> This is less a matter of "license"

I think this should be a matter of license, i.e. Haxe logos etc. should have their own separate license that specifies what is allowed and what is not. I think Firefox is a good example, where the source code is FOSS, but the Firefox name and the logos are trademarked. The result is that while it is allowed to modify and distribute application based on Firefox source code it is not allowed to refer to them as Firefox (hence Iceweasel on Debian). So essentially 2nd bullet in your reply :-)

**Comment by RealyUniqueName** [comment]
I'm closing this as there's no issue.

**Comment by RealyUniqueName** [comment]
Feel free to reopen or add comments.
