### ISSUE TITLE
[PHP] Std.random

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#9363]
I saw that `Std.random` is using `mt_rand` in PHP. Wouldn't it be better to use `random_int` here?
https://www.php.net/manual/en/function.mt-rand.php
https://www.php.net/manual/en/function.random-int.php

**Comment by RealyUniqueName** [comment]
`random_int` is at least two times slower.
And since `Std.random` is not specified to be cryptographically secure, I doubt we should change it.

**Comment by mockey** [comment]
Considering the random spec, you're probably right.
