### ISSUE TITLE
typedef get,set properties don't error but no way to use them?

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9365]
``` haxe
typedef Test = {    
    var pos( get, set ): Int;
    var size( get, set ): Int;
}
``` 
This is valid Haxe code but I can't seem to find a way to use them ( default will not allow below example to update size ), nearest I got was this test:
``` haxe
typedef AnyFoo = {
    public function get_pos(): Int;
    public function get_val(): Int;
    public function set_val( v: Int ): Int;
}
@:forward
abstract TAnyFoo( AnyFoo ) to AnyFoo from AnyFoo {
    public inline function new( f: AnyFoo ){
        this = f;
    }
    public var pos( get, never ): Int ;
    inline function get_pos(): Int {
        return this.get_pos();
    }
    public var val( get, set ): Int;
    inline function set_val( v: Int ): Int {
        this.set_val( v );
        return v;
    }
    inline function get_val():Int{
        return this.get_val();
    }
}
@:structInit
class Foo {
    public var v = 0;
    public var w = 0;
    function new( v: Int, w: Int ){
        this.v = v; 
        this.w = w;
    }
}
@:forward
abstract AFoo( Foo ) from Foo to Foo {
    public inline
    function new( f: Foo ){
    	this = f;
    }
    public var val( get, set ): Int;
    inline
    function get_val(): Int {
        return this.w;
    }
    inline
    function set_val( v: Int ): Int {
        this.v = v;
        this.w = v;
        return v;
    }
    public var pos( get, never ): Int;
    inline
    function get_pos(): Int {
        return this.v;
    }
}
class Test {
    @:access(AFoo)
    static function main() {
        var afoo: AFoo = { v: 10, w: 7 };
        var anyFoo: TAnyFoo = { get_pos: afoo.get_pos
                              , get_val: afoo.get_val
                              , set_val: afoo.set_val };
        anyFoo.val += 1;
        trace( anyFoo.pos );
        trace( anyFoo.val );
    }
}
```

**Comment by Simn** [comment]
You can create a compatible class and assign it to that structure.

**Comment by nanjizal** [comment]
I failed to find a way that worked, probably being stupid but no one on discord seemed to know either, so for anyone with similar issue my work round was to use an abstract, my full context use case:
An abstract wrapper
<https://github.com/nanjizal/trilateral2/blob/master/trilateral2/DrawAbstract.hx>
A typedef
<https://github.com/nanjizal/trilateral2/blob/master/trilateral2/DrawType.hx>
getting round the private original getter/setters
<https://github.com/nanjizal/trilateral2/blob/master/trilateral2/Pen.hx#L25>
Then you can use it just like a normal getter/setter
<https://github.com/nanjizal/trilateral2/blob/master/trilateral2/Regular.hx#L85>
It allowed me to render a die with cleaner code in webgl, unfortunately for certain rotations, I get some overlaps so current die approach seemed to work better.
<https://gist.github.com/nanjizal/47cb39d9c227f60dc189bf8ec6f652cf>
<img width="164" alt="dieeOverlap" src="https://user-images.githubusercontent.com/20134338/80477067-37c9af00-8943-11ea-9bc1-3896a66fbd54.png">
The reason for needing it was to allow decoupling of the array structures ( or object structures ) to provide minimal access, since Iron needs Integers for shaders but most toolkits likely work with Floats, and also don't want to confine the data store format tightly.
