### ISSUE TITLE
Uncaught exception Unbound variable

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9366]
Main.hx:
```haxe
import haxe.Constraints.IMap;
import haxe.Constraints.Constructible;
import haxe.ds.EnumValueMap;

class Main {
	static function main() {
		trace(foo());
	}

	public static macro function foo() {
		return macro $v{localVars.name()};
	}

	static final localVars:VarManager<En, EnumValueMap<En, String>> = new VarManager();
}

enum En {
	A;
}

@:generic class VarManager<K, M:IMap<K, String> & Constructible<Void->Void>> {
	final nameToVarKey:Map<String, K> = new Map();

	public function new() {}

	public function name() {
		var f = s -> nameToVarKey.exists(s);
		return '';
	}
}
```
build.hxml:
```hxml
-main Main
--interp
```

Accessing `nameToVarKey.exists` directly works, but in a closure doesn't. Doesn't happen outside of macro, and doesn't happen without the `M` type parameter.

**Comment by Simn** [comment]
An initial investigation suggests that the generated `this` variable has `v_capture=false` which causes Eval to look for it in the closure scope instead of the context.

The next question is why that is the case.

**Comment by Simn** [comment]
The problem here was that `run_expression_filters` ignores classes for which `is_removable_class` is true, which lead to `captured_vars` not being executed on `VarManager` itself (not the generic instance of it). Eval then still tried to generate that class, but because the filter didn't run, variables would have the wrong `v_capture` value.

**Comment by Simn** [comment]
Hmm, maybe it would be cleaner to make sure `remove_generic_base` is run in macro context as well. That one doesn't actually remove the class from the type list, it just sets `cl_extern <- true` which causes generators to ignore it.

The fact that this doesn't run in macro context also explains why the problem only reproduced in macro context.
