### ISSUE TITLE
`Context.typeof` fails on module sub-type

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9367]
```haxe
class Main {
	static function main() {
		foo();
	}

	static macro function foo() {
		haxe.macro.Context.typeof(macro Main.Foo);
		return macro {};
	}
}

class Foo {}
```
The `typeof` call fails with `Class<Main> has no field Foo`. Same behavior for sub-type in a different module.
I tracked it down to somewhere between https://github.com/HaxeFoundation/haxe/commit/d30eec2 (works) and https://github.com/HaxeFoundation/haxe/commit/b5b9d1e (does not).

**Comment by Simn** [comment]
That's gonna be https://github.com/HaxeFoundation/haxe/commit/55b45250f26bbca9d0608f2e43c768330b0fd6c2

**Comment by nadako** [comment]
Does this also fail without macros?

**Comment by Antriel** [comment]
Actually yes, `Type.typeof(Main.Foo);` fails too. New minimal example:
```haxe
class Main {
	static function main() {
		Type.typeof(Main.Foo);
	}
}
class Foo {}
```

**Comment by nadako** [comment]
*(in case I die from brain explosion while trying to fix this and won't be able to finish)* This is about falling back to current-package module resolution when there is a requested type in the current module context, but it does NOT have a requested field.

Similar issue is with this code: https://github.com/deepnight/deepnightLibs/blob/e21549d49d0da75578b45b88f092813ad76dace8/src/dn/heaps/Controller.hx#L83

**Comment by nadako** [comment]
Should work now, will close by adding a test.
