### ISSUE TITLE
[java] Type not found : java.lang.String

### ISSUE THREAD

**Issue by rhacking** [HaxeFoundation/haxe#9371]
Create a file src/Test.hx:
```haxe
import java.lang.String;

class Test {
    static public function main():Void {
    }
}
```

and build.hxml: 
```
-cp src
-main Test
-lib hxjava
--java bin
```

Running `haxe ./build.hxml` results in `src/Test.hx:1: characters 8-24 : Type not found : java.lang.String`

Tried using Haxe versions 4.0.5 and 4.1.0-rc.1+4450dfbb6, `javac 1.8.0_252` and latest hxjava and latest git master branch hxjava. 

Vshaxe does autocomplete `java.lang.String`, but it then also subsequently lints it with `Type not found : java.lang.String diagnostics(2)`.

**Comment by RealyUniqueName** [comment]
There's `java.NativeString`, which is `java.lang.String` at run time.
https://github.com/HaxeFoundation/haxe/blob/acaec1c8a0443b15537ee993b6c8031ad8c911be/std/java/NativeString.hx#L32-L33

**Comment by Simn** [comment]
Maybe adding a `typedef String = java.NativeString` in a `java.lang` package is a way to deal with this.

**Comment by RealyUniqueName** [comment]
I think it was made as `NativeString` to not shadow Haxe String.

**Comment by RealyUniqueName** [comment]
I'll go ahead and close this. Feel free to reopen.
