### ISSUE TITLE
[php] Feature request: add the `JsonSerializable` interface

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxe#9373]
The [`JsonSerializable` interface](https://www.php.net/manual/en/class.jsonserializable.php) is available since PHP 5.4. As of Haxe 4.0, the PHP target requires PHP 7.0, so this interface can now be safely included.

**Comment by RealyUniqueName** [comment]
It's already included: 
https://github.com/HaxeFoundation/haxe/blob/18b5e7d1058f97f457c1791296309fc4479d6f20/std/php/JsonSerializable.hx#L28-L31

Not sure why API docs are missing it.

**Comment by RealyUniqueName** [comment]
Ah, it was not available in 4.0.

**Comment by cedx** [comment]
OK, thanks @RealyUniqueName. I guess I have to wait for the next Haxe release...

**Comment by Gama11** [comment]
You don't _have_ to. https://build.haxe.org/builds/haxe/
