### ISSUE TITLE
Float should be EitherType<String, Float>

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#9376]
EitherType's to/from unification fails when it's used to type an object property

Tested with 3.4.7 to development

```haxe
typedef C = {
	width: haxe.extern.EitherType<String, Float>
}

class Main {

	static function main() {
		var c = {
			width: 400.0
		}

		$type(c); // { width: Float }

		var d: C = c;
		// ^ fails with `Float should be haxe.extern.EitherType<String, Float>`


		var e: C = { width: 400.0 }
		// ^ ok
	}

}
```

Error is:

```
Main.hx:20: characters 3-16 : error: Float should be haxe.extern.EitherType<String, Float>
Main.hx:20: characters 3-16 :  have: { width: Float }
Main.hx:20: characters 3-16 :  want: { width: haxe.extern.EitherType<..., ...> }
```

Reading the error, it looks like this _should_ work

**Comment by nadako** [comment]
I don't think it should work, because you could then assign a `String` to `c` through `d`, which is wrong...

**Comment by nadako** [comment]
Funny enough, it is a type hole in [TypeScript](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=5&pc=1#code/DYUwLgBAhgXBDeEAecB2BXAtgIxAJwgF8IBeBZOAZgAYiBuAKFEmzkRQgx3wgB8IAzmDwBLVAHMipaI2wA6JNIBEACxDBgAeyWMAxptQDNoOVvEAKMAE8ADiE0AzaAoCUjIA).

**Comment by haxiomic** [comment]
Ahhh, that's amazing, feel dumb for not seeing this, thanks for the education @nadako!

**Comment by nadako** [comment]
BTW I think this works for read-only/final fields.
