### ISSUE TITLE
Comparing method with null fails on many targets.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9379]
Minimal example:

```haxe
class Test {
  function items() {}
  function new() trace(this.items == null);
  static function main() new Test();
}
```

Throws on eval, php, java. On cs it doesn't compile. Works on js, neko and python, because it's not a problem at runtime. The code for cpp looks like it'll fail too, but can't confirm right now, because it bricked my compiler setup 😊

**Comment by RealyUniqueName** [comment]
I think it happens because `this.items` is compiled as `FInstance` instead of `FClosure`:
```
[Binop:Bool]
	[Field:Void -> Void]
		[Const:Main] this
		[FInstance:Void -> Void]
			Main
			items:Void -> Void
	==
	[Const:Void -> Void] null
```

**Comment by RealyUniqueName** [comment]
Oh, it's actually a regression since 4.0.

**Comment by Simn** [comment]
A bisect would be interesting.

**Comment by RealyUniqueName** [comment]
So, it's a consequence of #6297
I think changing `FClosure` to `FInstance` just to make genjs happy was a wrong move. 
Accessing a method without calling it should always be `FClosure`. And if a target wants cleaner output it's that target's concern to detect and handle edge cases.

@Simn  let's revert #6297 and handle that in genjs instead?

**Comment by Simn** [comment]
If that's the cause then it's not a regression since 4.0 though.

**Comment by RealyUniqueName** [comment]
It is. 
3.4.7 doesn't have this bug. And https://github.com/HaxeFoundation/haxe/commit/b2a3e37a0e7f9919171db2a1d9bb994101b8f866#diff-d9f788ff511f3c22dcae93956e997b38R1150 is the exact line, which changes that `FClosure` into `FInstance`

**Comment by Simn** [comment]
Then it's a regression since 3.4, not since 4.0. That makes a difference regarding the urgency of this.

However, I certainly agree that we should focus on correct code first and optimizations second. So reverting for now might be the best choice.
