### ISSUE TITLE
throwing haxe.macro.Expr.Error behaviour changed since 4.0

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9389]
```haxe
class Main {
	static function main() {
		f(123);
	}

	static macro function f(e) {
		throw new haxe.macro.Expr.Error("boop", e.pos);
	}
}
```

in 4.0.5, this code would show a compiler error (`boop`) at the position of `e` (like `Context.error`), in current `development` this shows a stacktrace like other exceptions, so there's no special handling anymore.

Probably related to haxe.Exception reworks?

**Comment by RealyUniqueName** [comment]
> Probably related to haxe.Exception reworks?

Yep
