### ISSUE TITLE
Not_Found when deleting @:genericBuild on Local Class

### ISSUE THREAD

**Issue by ErikRikoo** [HaxeFoundation/haxe#9391]
When trying to delete the @:genericBuild metadata from a class when calling the build macro we get an unexpected Not_Found error.
Reproductible exemple:
The exemple class + main:
```haxe
@:genericBuild(Builder.build())
class Foo<T> {

}

class Main {
	static function main() {
		var a:Foo<String>;
		var b:Foo<Int>;
	}
}
```
The build function:
```haxe
public static function build():ComplexType {
    var localClass = Context.getLocalClass().get();
    trace(localClass.meta.has(":genericBuild"));
    localClass.meta.remove(":genericBuild");
    return null;
  }
```

When compiling this code we get the given trace:
```
true
Not_found
```
But if we comment the line with `localClass.meta.remove(":genericBuild");`, we get:
```
true
true
```
So the metadata is still there but if we try to delete we get a Not_Found error, I tried to do the same with custom metadata but I don't get the error.
I have Haxe 4.0.5

**Comment by RealyUniqueName** [comment]
I suspect this is about compiling using compilation server.
