### ISSUE TITLE
[neko?] local renaming vs. package or something

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#9394]
Trying to run https://github.com/HaxeFoundation/code-cookbook/blob/master/CodeCookBook-neko.hxml errors:

```
C:\git\code-cookbook>haxe codecookbook-neko.hxml
src/Generator.hx:511: characters 15-27 : Warning : Std.instance() is deprecated. Use Std.downcast() instead.
src/Generator.hx:603: include directory: ./output/assets
src/Generator.hx:603: include directory: ./output/assets
src/Generator.hx:48: 79 articles
Called from ? line 1
Called from Main.hx line 8
Called from C:\git\haxe\std/haxe/Timer.hx line 161
Called from Main.hx line 24
Called from Generator.hx line 138
Uncaught exception - Invalid field access : TemplateData
Error: Command failed with error 1
```

This is fixed by renaming the local `data` on Generator.hx:138 to something else, so the problem is that it shadows the `data` package or something.

This is a recent regression.

**Comment by nadako** [comment]
We should check if this also breaks on JS with `js-unflatten` and adjust paltform settings? I think it's the `ReserveAllTopLevelSymbols` flag?
