### ISSUE TITLE
reification syntax survives typing

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9396]
This currently compiles (with just normal typing without any macro processing), but I don't think it should:

```haxe
var a = 1, b = ${a};
```

We should probably catch EMeta that starts with `$` (there's also `$b`, `$p` and any `$blahblah`, really) and raise a compile-time error.

Also just `$a` identifier survives until we get an `Unknown identifier : $a` error, while `var $a` and `o.$a` complain properly about using the dollar, we should do the same for the identifiers.

**Comment by kLabz** [comment]
Fixed by #10887 (nightlies, 4.3.x)
