### ISSUE TITLE
[lua] generated lua file omits call to main function

### ISSUE THREAD

**Issue by AlexHaxe** [HaxeFoundation/haxe#9402]
I was wondering why lua benchmarks for formatter where suddenly super fast and it turns out it just doesn't invoke formatter's `main` function.

Sample code:
```haxe
import haxe.Timer;

class Main {
	function new() {
		trace("hello lua");
	}

	static function main() {
		new Main();
	}
}
```
call with `haxe -lua main.lua -main Main && lua main.lua`

It works if you comment out `import haxe.Timer;`

broken somewhere between versions 18b5e7d1058f97f457c1791296309fc4479d6f20 and ef9469a1d4049bf2838c51d1a0debfc602a7f73d

18b5e7d1058f97f457c1791296309fc4479d6f20 prints trace from sample but also crashes with: 
```
lua: ./main.lua:746: attempt to call field 'gettimeofday' (a nil value)
stack traceback:
	./main.lua:746: in function 'time'
	./main.lua:893: in function 'tick'
	./main.lua:759: in function 'processEvents'
	./main.lua:767: in function 'run'
	./main.lua:996: in main chunk
	[C]: in ?
```
(lua version 5.2.4; lua-luv package version 1.9.1 on Ubuntu)

**Comment by piotrklibert** [comment]
I encountered the same issue, probably: the code which compiled ok before suddenly vanished after https://github.com/HaxeFoundation/haxe/commit/bde35a20d9c3bccd045caa52dce05a75de788537 - without any error from the compiler, the output file got deleted. Reverting to bec8e9e16 fixed the issue.

**Comment by jdonaldson** [comment]
@RealyUniqueName I took a look at the example, and it seems to be a problem in the AST construction.  The lua generator never sees the call to main when haxe.Timer is imported.

**Comment by RealyUniqueName** [comment]
@jdonaldson An issue is entry point expression is not necessary a call. I've changed genlua to generate any entry point expression, not only calls.

**Comment by jdonaldson** [comment]
That's clear to me now, thanks for the details and update.
