### ISSUE TITLE
Value escaping ($v) in reification only works inside macro context

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9403]
Example:

```hx
class Foo {
  public static macro function foo() {
    return macro $v{0};
  }
}

class Main {
  public static function main() {
    trace(Foo.foo()); // 0
    trace(macro 0);  // Expr of EConst(CInt(0))
    trace(macro $v{0}); // Uncaught exception Invalid expression
  }
}
```

All other escaping mechanisms (e/a/b/i/p) work outside macro call. Is there something in `$v` escaping that requires it to have access to macro context?

**Comment by back2dos** [comment]
It relies on [`haxe.macro.Context.makeExpr`](https://github.com/HaxeFoundation/haxe/blob/4.0.5/std/haxe/macro/Context.hx#L322). If you don't target eval or neko, you get a compiler error for this.

A cross platform implementation (based on `Type.typeof`) shouldn't be too hard, but the question is if its worth the trouble. If you want to deal with expressions at runtime, perhaps [hscript](https://github.com/HaxeFoundation/hscript) would make for a better choice?

**Comment by vonagam** [comment]
I do target eval. This is reproducible with `--run Main` or `--main Main --interp` on my machine.

**Comment by vonagam** [comment]
`Context.makeExpr(0, pos)` is working inside `Main.main`, so if this is the only requirement for `$v` then it should work too.

**Comment by Simn** [comment]
I think the "fix" here is to fence `makeExpr` in `#if macro`. That way you get a proper compiler error when using it outside macro-context.

**Comment by RealyUniqueName** [comment]
Do we really want to ban it outside of macros?
I think it could be useful for some code analyzing/generation tools.

**Comment by Simn** [comment]
We can always add `#else // implementation` later if anybody wants to contribute that. At the moment it's failing anyway, so I'd prefer to make it fail with a proper error message instead of whatever it is doing right now.

**Comment by vonagam** [comment]
But how i said `Context.makeExpr` is working outside of macro function in `Main.main`. It is usage of `makeExpr` through `$v` that has a problem for some reason.

**Comment by vonagam** [comment]
Ok, i think i found the problem.
1) `$v{value}` is [transformed](https://github.com/HaxeFoundation/haxe/blob/a0939ea090561e1e42a374bcbfed6b4be50c8e31/src/syntax/reification.ml#L345) into `haxe.macro.Context.makeExpr(value, position)`
2) Where `position` [is](https://github.com/HaxeFoundation/haxe/blob/a0939ea090561e1e42a374bcbfed6b4be50c8e31/src/syntax/reification.ml#L223-L226) result of `$__mk_pos__` call in macro context and simply a structure ouside.
3) `makeExpr` [calls](https://github.com/HaxeFoundation/haxe/blob/a0939ea090561e1e42a374bcbfed6b4be50c8e31/src/macro/macroApi.ml#L1638-L1639) `decode_pos` on `position`. And in macro context it works ok, but outside it fails (since it is not an encoded position, but a structure).
4) [Error message](https://github.com/HaxeFoundation/haxe/blob/a0939ea090561e1e42a374bcbfed6b4be50c8e31/src/macro/eval/evalDecode.ml#L103) is not good because `decode_pos` is used in `maybe_decode_pos` and `decode_pos_default` and they depend on catching `Invalid_expr`.

When i said that `Context.makeExpr` is working outside macro context i used it with `Context.makePosition` to get a `pos` value and it returns an encoded position.

So to fix it, `$v` reification should make second argument for `makeExpr` an encoded position in non-macro context too (through call to `makePosition` or other means if there is any).
