### ISSUE TITLE
Macro printer outputs invalid syntax for TExtend type

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9405]
Example:

```hx
import haxe.macro.Printer;

class Main {
  public static function main() {
    final type = macro : {> Foo, bar: Int, baz: Int};
    final printer = new Printer();
    final print = printer.printComplexType(type);
    trace(print); // {> Foo, var bar : Int, var baz : Int }
  }
}
```

`{> Foo, var bar : Int, var baz : Int }` is not valid since it uses class notation for fields but separates them with comma instead of semicolon and lacks trailing semicolon.

**Comment by haxiomic** [comment]
I've got a fix for this in another project. Plan to PR soon but in the meantime, feel free to copy this extension to Printer.hx into your project. Includes a number of fixes as well as improved formatting

https://github.com/haxiomic/dts2hx/blob/master/src/Printer.hx

**Comment by vonagam** [comment]
Yeah, i worked it around for myself too with this override (since i also prefer newer syntax of intersection):

```haxe
class Printer extends haxe.macro.Printer {
  public override function printComplexType(type: ComplexType) {
    return switch (type) {
      case TExtend(extended, fields):
        final types = extended.map(path -> TPath(path));
        if (fields.length > 0) types.push(TAnonymous(fields));
        final print = super.printComplexType(TIntersection(types));
        return print;
      case _: super.printComplexType(type);
    };
  }
}
```
