### ISSUE TITLE
4.10 ( first rev release ) occasional Error 1.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9414]
With haxe 4.1.0 ( the first iteration released ), was building lime project from terminal ( after many iterations without problem ).
Not sure if it's a weird timing error, it's only happened ONCE so far and it went away when I closed the associated terminal.
I was trying to run from a terminal hxml file with following:
```
-cmd npx kill-port 3000
-cmd haxe compile.hxml
```
which called another hxml with the following:
```
-cmd lime test html5
```
even if i just ran the second command after manually checking nodejs was not running it still would not work, so I had to close the mac terminal window and open a new one, I did not need to close terminal completely.  

I think Neko was perhaps stuck, sorry can't double check as error only happened once.

Error reported:
```
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 56
Called from lime/tools/HXProject.hx line 24
Called from a C function
Called from lime/tools/HXProject.hx line 291
Called from hxp/System.hx line 1428
Called from /usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx line 85
Called from a C function
Called from /usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx line 95
Uncaught exception - { __skipStack => 3, __previousException => null, __nativeException => ..., __exceptionMessage => Process creation failure : uname, value => Process creation failure : uname, __nativeStack => { skip => 1, stack => [[?,1],[CommandLineTools.hx,1895],[CommandLineTools.hx,22],null,[CommandLineTools.hx,56],[lime/tools/HXProject.hx,24],null,[lime/tools/HXProject.hx,291],[hxp/System.hx,1428],[/usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx,85],null,[/usr/local/lib/haxe/std/neko/_std/sys/io/Process.hx,95],[/usr/local/lib/haxe/std/neko/_std/haxe/Exception.hx,29],[/usr/local/lib/haxe/std/haxe/ValueException.hx,17],null,[/usr/local/lib/haxe/std/haxe/ValueException.hx,24],null,[/usr/local/lib/haxe/std/neko/_std/haxe/Exception.hx,42],[/usr/local/lib/haxe/std/neko/_std/haxe/NativeStackTrace.hx,21]] } }
Error: Command failed with error 1
```
It's not a problem for me as only happened once, just reporting incase it's relevant

**Comment by nanjizal** [comment]
Feel free to close, and only link to if others get similar error.

**Comment by kLabz** [comment]
Did you restart your compilation server(s) after updating to haxe 4.1?

**Comment by nanjizal** [comment]
This was a day or so after installing and I have been using Haxe quite a bit so it was not something that happened for some time and I have not seen it since, but I think had to restart my system within that time so probably yes, I have no idea on compilation server restarting. I will let you know if it appears again.

By the way well done on you guys speeding up JVM.

**Comment by RealyUniqueName** [comment]
> Process creation failure : uname

Looks like a random system failure not related to Haxe
