### ISSUE TITLE
lua support for code insertion via Syntax

### ISSUE THREAD

**Issue by dschmitt007** [HaxeFoundation/haxe#9416]
Haxe 4 added Syntax to javascript:
https://try.haxe.org/#77000
It would be nice if that idiom were standardized for all the languages.
(In this case, specifically Lua.)

**Comment by RealyUniqueName** [comment]
Yes, the plan is to gradually add `{target}.Syntax` module to other targets as well.
Meanwhile you can do the same thing with `untyped __lua__("{0} lua code {1} with args", arg1, arg2)`

**Comment by jdonaldson** [comment]
I'll add support for lua.Syntax and add a deprecation note for `__lua__`

**Comment by jdonaldson** [comment]
Tracking this issue here : https://github.com/HaxeFoundation/haxe/issues/9502
