### ISSUE TITLE
4.1.0 is not available for install on Ubuntu

### ISSUE THREAD

**Issue by posxposy** [HaxeFoundation/haxe#9419]
Hi, 

looks like there is no 4.1.0 version here: https://launchpad.net/~haxe/+archive/ubuntu/releases
So `sudo apt-get install haxe` installs old 4.0.5 version.

Thank you

**Comment by RealyUniqueName** [comment]
It takes some time to update all the distros.
But @andyli is going to do that: https://twitter.com/andy_li/status/1260716546378227713

**Comment by andyli** [comment]
done

**Comment by DeedeeBumbly** [comment]
Hello,
When attempting to install 4.1 from the ppa on ubuntu 18.04, it fails with the following 
```
 haxe : Depends: libmbedcrypto3 (>= 2.13) but it is not installable
        Depends: libmbedtls12 (>= 2.13) but it is not installable
```
Trying to install manually says that it has no installation candidate and when I searched for the packages I couldn't find these for versions below 19.

**Comment by andyli** [comment]
Thanks for reporting!
Indeed I should had made mbedtls available in the repo - just fixed it.
Please try again.

**Comment by DeedeeBumbly** [comment]
It works, many thanks
