### ISSUE TITLE
[ide] module target-specialization show up in toplevel completion

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9423]
I didn't have time to check if it's a haxe or vshaxe issue, but i suspect it comes from haxe, so I'll just report it here:

Consider we have these files:
 * `Mod.hx` containing `class Mod {}`
 * `Mod.whatever.hx` containing `class Mod {}`

Now if we autocomplete here:
```haxe
class Main {
	static function main() {
		Mod|
	}
}
```

We will get `Mod` (also reported as `imported` for some reason) and `Mod.whatever.Mod` (suggested auto-import from `Mod.whatever`):

![](https://user-images.githubusercontent.com/49749/82044661-0d4f5400-96ae-11ea-97f1-0064de6bb1ca.gif)

**Comment by RealyUniqueName** [comment]
I've committed a fix.
But the test I've added does not pass, even though the same setup in vscode works fine. 
I tried to figure out the test very hard, but gave up eventually.

Please, check if the fix works for you.

**Comment by nadako** [comment]
Yep, now it only shows just one class \o/
