### ISSUE TITLE
[Haxe 4.1] DateTools - haxe.Exception has no field thrown

### ISSUE THREAD

**Issue by Jarrio** [HaxeFoundation/haxe#9424]
`
/usr/local/lib/haxe/std/DateTools.hx:101: characters 5-10 : haxe.Exception has no field thrown
`
Running on OSX

**Comment by RealyUniqueName** [comment]
Looks like you're using an old std library with the new Haxe.

**Comment by RealyUniqueName** [comment]
Another guess: you're using [exception](https://lib.haxe.org/p/exception/) library, which shadows `haxe.Exception`. In this case you have to remove that library from your project.

**Comment by Jarrio** [comment]
> Another guess: you're using exception library, which shadows haxe.Exception. In this case you have to remove that library from your project.

This was it! I am using the `safety` lib which has `exception` as a dependency. Thanks!

**Comment by RealyUniqueName** [comment]
Safety lib is updated on github to avoid this issue. It's just not released to haxelib yet. I'm going to make a release now.

**Comment by RealyUniqueName** [comment]
Done: https://lib.haxe.org/p/safety/1.1.2/
