### ISSUE TITLE
Compiler doesn't terminate with dts2hx-generated VSCode externs

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9428]
See title - this is with latest HEAD (d5733b04433e9f41feb65a4b07dcdfa4a2cc177d), so it includes 8c254fb8372cfd3cce76cd52a1b105d909c6821f. The vshaxe test branch is at that commit too, but you can change `.haxerc` to a dev build if you want.

No isolated repro case yet, so these are the steps to reproduce:

```
git clone --recursive https://github.com/vshaxe/vshaxe --branch haxe-9428
cd vshaxe
npm install
npx lix run vshaxe-build -t client -v -- -v
```

There's no more output after this line, but `haxe.exe` is still using up one CPU core.

```
Typing vshaxe._HaxeMemento.HaxeMemento_Impl_.update
```

**Comment by haxiomic** [comment]
Edit: **Can** repo with 4.1.0 and 4.0.5 in the isolated case

I copied the generated externs from https://github.com/vshaxe/vshaxe # haxe-9428

And did

**Main.hx**
```haxe
import js.lib.Promise.Thenable;

abstract HaxeMemento(vscode.Memento) from vscode.Memento {
	public inline function update<T>(key:String, value:T):Thenable<Void> {
		return this.update(key, value);
	}
}

class Main {

	static function main() {
	}

}
```

**build.hxml**
```hxml
-cp externs/vscode
-main Main
-js main.js
```

[#9428-repro.zip](https://github.com/HaxeFoundation/haxe/files/4650867/9428-repro.zip)

**Comment by RealyUniqueName** [comment]
Minimal sample:
```haxe
typedef Rec1<T> = {
	function then<TResult>():Rec1<TResult>;
}

typedef Rec2<T> = {
	function then<TOut>():Rec2<TOut>;
}

class Main {
	static function main() {
		var r:Rec1<Void> = (null:Rec2<Void>);
	}
}
```

**Comment by RealyUniqueName** [comment]
And it works with Haxe 3.4.7

**Comment by RealyUniqueName** [comment]
This turned out to be two bugs in one issue :)
Another case:
```haxe
typedef Rec1<T> = {
	function then<TResult>():Rec1<TResult>;
}

abstract Rec2<T>(Rec2Struct<T>) from Rec2Struct<T> {}

typedef Rec2Struct<T> = {
	function then<TOut>():Rec2<TOut>;
}

class Main {
	static function main() {
		var r:Rec2<Void> = (null:Rec1<Void>);
	}
}
```

**Comment by haxiomic** [comment]
Nice debugging @RealyUniqueName, thank you :)
