### ISSUE TITLE
[cpp] Extending extern class with nativeGen one

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9431]
As i understand from #8300 it is not possible to extend an external class with a usual haxe class. You need to create a native cpp class which extends desired external class and has a member instance of a haxe class to which it delegates implementations.

I am trying to use `@:nativeGen` class to generate said native class. But right now extension of  extern class is not supported by `gencpp`.

Example input:
```haxe
@:include('Node.hpp')
@:native('namespaced::Node')
extern class Node {}

@:nativeGen
class MyNode extends Node {}
```

Problematic lines in outputted `MyNode.h`:
```cpp
...
#ifndef INCLUDED_namespaced::Node
#include <namespaced::Node.h>
...
class HXCPP_CLASS_ATTRIBUTES MyNode : public  namespaced::Node_obj
...
```

Fixes for those lines (speculation on my part):
- `add_include` should be called [here](https://github.com/HaxeFoundation/haxe/blob/c584d2844cb5d5efcae38c969034e5fa96be7a9e/src/generators/gencpp.ml#L6544) with `@verbatim` and `@:include` meta instead of a name if `super` is external.
- [`tcpp_to_string_suffix`](https://github.com/HaxeFoundation/haxe/blob/c584d2844cb5d5efcae38c969034e5fa96be7a9e/src/generators/gencpp.ml#L1626) should check if a class is external and not add `_obj` suffix in that case.

Can `@:nativeGen` class be allowed to extend external class or are there any problems that prevent that?

**Comment by vonagam** [comment]
Just to be clear, i would consider second bullet point as a serious bug, since it prevents usage of static fields lacking `@:native` meta of extern or native gen classes and prevents native gen classes from extending each other. Example:

```haxe
@:nativeGen
class Foo {
  public static function bar(): Void {}
}

@:nativeGen
class Baz extends Foo {}

class Main {
  public static function main() {
    Foo.bar();
  }
}
```

You will see that `Baz` will try to extend inexistent `Foo_obj` and that `Foo.bar()` turns into `::Foo_obj::bar()`. None of those issues are present in other targets supporting `nativeGen` meta.

To fix this `class_string`, `tcpp_to_string_suffix` and `cpp_class_name` methods should take into account that extern and native gen classes do not have haxe cpp naming convention.

**Comment by RealyUniqueName** [comment]
@hughsando could you please check this?
