### ISSUE TITLE
[display] no completion for out-of-bounds argument in call

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9435]
```haxe
class Main {
	static function main() {
		var i:Int;
		foo(i, )
	}

	static function foo(arg:Int) {}
}
```

Code completion for the second argument doesn't seem to work before it's been added to the declaration of `foo`. This is annoying because when I add additional arguments, I often start by modifying a call, no the declaration.

____

Works:

![](https://i.imgur.com/uUzDQaq.png)

Doesn't work (fallback to text-based completion because there are no Haxe results):

![](https://i.imgur.com/5l9ux15.png)

**Comment by nadako** [comment]
Happens to me from time to time and yep it is annoying :)
