### ISSUE TITLE
[ide] find references doesn't work for the FIRST module-static

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9446]
This one is different from #9440 and I suspect it has something to do with the `KModuleStatics` class position, which is the zero-range position of the first definition.

```haxe
final a = 1; // no "find references" :(
final b = 2; // works \o/

function main() {
	trace(a, b);
}
```

**Comment by nadako** [comment]
Sorry, wrong issue number.

**Comment by Simn** [comment]
What exactly is this about? I can find references on that `a`.

**Comment by nadako** [comment]
Oh, it was closed and I reopened it by mistake :)
