### ISSUE TITLE
cpp.RawConstPointer.addressOf gives error C2039: 'AddressOf': is not a member of 'hx'

### ISSUE THREAD

**Issue by intoxopox** [HaxeFoundation/haxe#9452]
In Haxe 4.1 and hxcpp 4.1.1 `cpp.RawConstPointer.addressOf` method produces this error:
`error C2039: 'AddressOf': is not a member of 'hx' `
I assume this to be related to this now closed issue: https://github.com/HaxeFoundation/haxe/issues/8543

**Comment by Simn** [comment]
Update hxcpp.

**Comment by intoxopox** [comment]
I did. 4.1.1 is the latest. I also tried latest from git, with last commit being 2 days ago. No change.

**Comment by Simn** [comment]
Hmm, according to http://nmehost.com/hxcpp/ the latest is 4.1.10.

**Comment by intoxopox** [comment]
Strange. 4.1.1 is latest according to haxelib. Like I said, I also tried from git and rebuilt. Changes.md doesn't seem entirely up to date, showing a not yet versioned one with previous being 4.0.64.

**Comment by Simn** [comment]
Right, these version numbers don't actually match. In that case I'm not sure. Assigning to @hughsando

**Comment by intoxopox** [comment]
Thx

**Comment by markknol** [comment]
There is a similar error in running dox for api.haxe.org (see https://travis-ci.org/HaxeFoundation/api.haxe.org)
```
Error: ./src/haxe/ds/GenericStack_templo__Converter_Block.cpp: In member function 'bool haxe::ds::GenericStack_templo__Converter_Block_obj::remove(templo::_Converter::Block)':
./src/haxe/ds/GenericStack_templo__Converter_Block.cpp:98:20: error: 'IsInstanceEq' is not a member of 'hx'
 HXLINE( 160)   if (::hx::IsInstanceEq( l->elt,v )) {
                    ^
Error: Build failed
````

**Comment by hughsando** [comment]
Is see that it uses: `haxelib install hxcpp 4.0.52 --always` whereas you really need to use the git version of hxcpp if you use the git version of haxe.
