### ISSUE TITLE
Haxe 4.2 - Evolution 24 and package class/method paths.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9457]
I thought I should just mention that currently Haxe 4.2 does not seem to allow you to clarify the function you want to use by short path only full path, **BUT see further down** worried that Haxe defaults to haxelib class/method which you may not know about rather than a project class/method.

## **1 ) Short names possible?** ##
_Algebra.hx_
``` haxe
package math;
inline
function lineAB( A: Matrix1x2, B: Matrix1x2, width: Float ): Quad2D {
// code to create 
    return quad2D;
}
```

_Shaper.hx_
``` haxe
import math.Algebra;
inline
function lineAB( drawType: DrawType
               , A: Matrix1x2, B: Matrix1x2
               , width: Float ): Int {
    var q = Algebra.lineAB( A, B, width );
    return quad( drawType, q );
}
```
**Shaper.hx:80: characters 13-20 : Type not found : Algebra**
instead it requires 
_Shaper.hx_
``` haxe
import Algebra;
inline
function lineAB( drawType: DrawType
               , A: Matrix1x2, B: Matrix1x2
               , width: Float ): Int {
    var q = math.Algebra.lineAB( A, B, width );
    return quad( drawType, q );
}
```
I guess it's like that to not confuse with a static but it seems more natural to define it **Algebra.lineAB**.

## **2) Haxelib taking priority ( even if not actually used )** ##
I noticed that in fracs I have a Test.hx main in the root package that clashes.
https://github.com/nanjizal/fracs/blob/master/src/Test.hx

Now if I create in my project 
_Test.hx_
``` haxe
package;
class Test {
public function new(){ trace('test local');
}
```
and 
_Main.hx_
``` haxe
function main(){
new Test();
}
```
Haxe compiler complains that I don't have a constructor, because it's looking at the **fracs** Test.hx defined in the hxml even though I don't even import it and use dce full.
```hxml
-js binWebGL/test.js
-cp src
-lib fracs
-main Main  
-D js-flatten 
-dce full
-D dump=pretty
--next
-cmd echo '<!DOCTYPE html><meta charset="UTF-8"><html><body><script src="test.js"></script></body></html>' >binWebGL/index.html
```

**Comment by nanjizal** [comment]
Note in regard to 1): If short names are allowed it saves refactoring code that uses the original class of static methods that is now just functions, it seems like a small thing but the reality is if you switch from class of static methods to just functions your file looks a lot cleaner but then you have to hunt down all use cases in code that uses that File ( ex class ).

The user than has to decide to either not prepend any package or to provide full qualified path.  Often the user would prefer to use the File name to aid readability, but not full package name on most occasions.

**Comment by RealyUniqueName** [comment]
1) @nadako ?

2) This behavior has not been changed for a long time. AFAIR if you swap lines for `-cp src` and `-lib fracs` then the `Test.hx` from `src` will take priority.

**Comment by nanjizal** [comment]
2) I was not sure, but I think there will be more clashes with evolution24 because classes and methods can now clash especially at the 'package;' level.  I think it would help if it was illegal to have a class or free function in a haxelib ( file that is included via -lib ) that does not have any associated namespace. It might seem annoying to add this constraint but the alternative is unpredictable and confusing to debug. So rather than documentation that users will surely miss you reduce the probability of a common clash by throwing an error if this happens that references the -lib for clarity.

**Comment by nadako** [comment]
1. Is consistent with type resolution, that's why it's like that. We could look into changing the rules here, but it shouldn't be specific to module-statics.

**Comment by nanjizal** [comment]
1) I don't aim to make more work for you guys, I just wanted to providing my user observations, on using Evolution24 in a non trivial use case.
  
In https://github.com/nanjizal/trilateral3, I have a _'there be dragons'_ **Contour.hx** class that is already too complex, not ideal but works well, where I have switched to module-statics ( free functions ) for **Algebra.hx** and **Shaper.hx**. This left me feeling unease because quite a few functions appear as magic without a clear source, definitely reminded my of when I have overly used 'using'.  The alternative is to swap to full path but then module-statics are making some code clean at the expense of other code, so the appeal is lost.  

Changing the rules in favour of being able to use _'file name specifiers'_ allows developers to provide more clarity when required so that complex classes don't have to appear to contain too much magic which is important in a language perception as being clear, and it also allows them to easily swap a Class full of static methods for a File of free functions without needing to change files where the methods are used.

Anyway food for thought prior to release of 4.2, I don't think changing the rule would adversely effect most user code, I presume this would be applied to enums, types etc.. but maybe this is huge modification, and I have no idea of side effects.

**Comment by nanjizal** [comment]
For instance a few **Shaper** functions like **circle** appear in **Contour**, but it's not easy to realise they come from **Shaper**.
https://github.com/nanjizal/trilateral3/blob/master/trilateral3/drawing/Contour.hx#L425
https://github.com/nanjizal/trilateral2/blob/master/trilateral2/Contour.hx#L424

Again another example in **Algebra** functions like **cubicCurve** appear in **Sketcher**, but it's not easy to realize they come from **Algebra**.
https://github.com/nanjizal/trilateral3/blob/master/trilateral3/drawing/Sketch.hx#L310
https://github.com/nanjizal/trilateral2/blob/master/trilateral2/Sketch.hx#L285

In both cases if the function could be pre-pended with the file name then "Contour" and "Sketcher" would also not need modifying when classes are swapped for module-statics.

Anyway hopefully that explains my reasoning but very aware I do not know the wider picture.

**Comment by RealyUniqueName** [comment]
I don't think we will change current behavior in a foreseeable future.
