### ISSUE TITLE
Inconsistent wording for unsupported module-static modifiers

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9461]
For `public` and `static`, this wording is used:

![image](https://user-images.githubusercontent.com/2620907/82552985-7f6ae180-9b63-11ea-8efa-132de3abae30.png)

For `extern` and `final`, it's this:

![image](https://user-images.githubusercontent.com/2620907/82553029-90b3ee00-9b63-11ea-87c2-22c9859802d8.png)

We should probably try to be consistent about this? Also about which term is used for these, module-statics? Module-level declarations? Module-level statics? Module-level fields...?

**Comment by nadako** [comment]
Regarding `public`/`static` - those are universally not supported for any module-level declaration, so the message seems accurate to me.

Regarding `extern`, I guess we should indeed decide on the naming but it is hard... I guess change it to `module-level fields` for now, but if anyone has a clear opinion on it - please speak up.

**Comment by nadako** [comment]
Should we just call them "module fields"? :)

**Comment by nadako** [comment]
See if you like this more :)

**Comment by Gama11** [comment]
I do. :)
