### ISSUE TITLE
[ide] modules should show up in workspace symbols

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9462]
(if they have no primary type with the same name as the module to avoid duplicates)

This has always been a bit annoying with "data type modules" like `Display.hx`, if you want to open that file through workspace symbols, you had to think of the name of one of the types it contains. I expect it's going to come up even more now with modules that only contain fields.

**Comment by Simn** [comment]
Not sure about the sorting, but that should be something for the consumer to figure out:

![Code_JTR17hCLYR](https://user-images.githubusercontent.com/634365/83838745-5ff2bd80-a6fa-11ea-8c52-31211ddcc769.png)

**Comment by Gama11** [comment]
Not sure that your screenshot even shows an example of this working, those all seem like "primary types"? (`Expr.hx` has a typedef called `Expr` for instance) :) Still seems to work though:

![image](https://user-images.githubusercontent.com/2620907/83849036-13fe4380-a70f-11ea-9723-e84cad941d9a.png)
