### ISSUE TITLE
`Context.getLocalTVars()` empty Metadata

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9468]
`Context.getLocalTVars()` gives me local variables, but their metadata is empty. Manual doesn't mention local variables being able to have metadata, only expressions. So is this `meta` field only for member variables, and I'm out of luck?

Alternatively I suppose I could find and get the whole method, and parse it out from there, but doing that from within an expression macro that's inside the method doesn't seem to be a good idea.
```haxe
class Main {
	static function main() {
		@:foo var bar = "foobar";
		trace(getMetas());// {bar => []}
	}
	static macro function getMetas() {
		var metas = [
			for (key => val in haxe.macro.Context.getLocalTVars())
				key => val.meta.get().map(m -> m.name)
		];
		return macro $v{metas.toString()};
	}
}
```

**Comment by Simn** [comment]
There's no syntax for it, but that's not a problem with `getLocalTVars`.

**Comment by Antriel** [comment]
I don't entirely understand what you mean, but basically there's no way to get metadata of local variables of a function from expression macro within that function?
I tried getting the expr of the function, to parse it out manually, but that (obviously) doesn't work.

**Comment by Simn** [comment]
You can get the metadata, but you can't add it in syntax. In your example, `@:foo` is added to the expression, not the local.

I was thinking about adding `var @:meta x = 1` syntax, but somebody would have to turn that into a proper feature request.

**Comment by Simn** [comment]
Since this isn't a problem with `getLocalTVars` I'll go ahead and close this. A haxe-evolution has been opened here: https://github.com/HaxeFoundation/haxe-evolution/pull/74
