### ISSUE TITLE
[ide] "find references" on class methods doesn't consider usage through interfaces

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9470]
Nothing will be found if we invoke "find references" on the definition of `C.f` here:

```haxe
interface I {
	function f():Void;
}

class C implements I {
	public function new() {}
	public function f() {}
}

function main() {
	(new C() : I).f();
}
```

**Comment by nadako** [comment]
(that is, with the default method used by vshaxe: `WithBaseAndDescendants`)

**Comment by RealyUniqueName** [comment]
I think we need a new method here. Maybe `WithInterfaceAndDescendants`?
Otherwise users may get a lot of noise when they want exactly `C.f`.

**Comment by nadako** [comment]
Well, vshaxe will use the one that returns everything anyway.

**Comment by RealyUniqueName** [comment]
I've pushed a fix. 
And again I failed to make the test pass, but the same request works fine with vshaxe. 
I've experienced the same problem with https://github.com/HaxeFoundation/haxe/issues/9423#issuecomment-631038061. Something is wrong with our test suite probably.

@nadako check if the fix works for you.

**Comment by nadako** [comment]
The test passes for me after 2a9ada3739ece129fda1d7dba372771c5f015d17, so there's nothing wrong with the test itself.
