### ISSUE TITLE
Wrong result after multiplication

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe#9479]
The following code failed on eval and hashlink , but works on javascript. Not tested on other targets.
```haxe
var fl:Float = 54237582*27764462+10097191*1715585+23865137*42003240+13297986*91340915+30308092*44409605;
trace(fl);
```
This will return 137887973, but correct value is 5086233553797349
Using Haxe  4.1.1 also test on 3.4.4 ( https://try.haxe.org/#48FB4 )

This example works correctly:
```haxe
  var fl:Float = 5086233553797349 + 1;
  trace(fl);
```

**Comment by nadako** [comment]
Looks like an 32-bit integer overflow in the arithmetics, try adding `.0` to the numbers to make them `Float` in the first place.

**Comment by flashultra** [comment]
Yes, with ```.0``` works , but every of this values is ```Int```  variable from my side, so the final result should be int64 .

Using something like ```var fl:Int64 =  54237582*2776446...``` will return same incorrect result  137887973

 I also try with ```cast(..)``` , but only this solution works :
 ```var fl:Float = (54237582+0.0)*(27764462+0.0).....```
or 
``` var fl:Int64 = Int64.fromFloat((54237582+0.0)*(27764462+0.0)....)```

Is it there any simple solution for multiplication / addition of Int values and as result to get Int64 ?

**Comment by kLabz** [comment]
Note: `var fl = Int64.fromFloat(54237582*27764462....)` should work too.

Edit: sorry, misread; was testing on JS

**Comment by flashultra** [comment]
No, I already tried it and give the wrong result , because it convert float result which is already wrong.
The only solution for the moment is to add ```0.0```

**Comment by nadako** [comment]
(I meant you write `54237582.0` instead of `54237582+0.0`) :)

**Comment by flashultra** [comment]
Well, my real program is more like this : 
```haxe
var r0:Int = 54237582;
var r1:Int = 27764462;
var r2:Int = 10097191;

var fl:Int64 =  Int64.fromFloat(( r0 +0.0)*( r1+0.0)....)
```
where r0,r1, r2 ... are calculated , so for me the only solution will be ```+0.0``` if Haxe doesn't support easy way to use Int64 after arithmetic operations with Int

**Comment by Aurel300** [comment]
Why not convert the `Int`s to `Int64`s and just multiply them?

**Comment by flashultra** [comment]
Using ```Int64.ofInt(..)``` works and it's really the most clear solution. Below is working example..
Thank you.

It's a little bit strange how hard is to use Int64 ot UInt comparing the other supported target - java , c#, c++,c , javascript  in Haxe.  If I recall correctly Nicolas was mention once about possible refactoring of UInt and large integer literals .  Hope so to see it in the future,

```haxe
       var r0:Int = 54237582;
       var r1:Int = 27764462;
       var r2:Int = 10097191;
       var r3:Int = 1715585;
       var r4:Int = 23865137;
       var r5:Int = 42003240;
       var r6:Int = 13297986;
       var r7:Int = 91340915;
       var r8:Int = 30308092;
       var r9:Int = 44409605;

       var fl:Int64 = Int64.ofInt(r0)*Int64.ofInt(r1)+Int64.ofInt(r2)*Int64.ofInt(r3)+Int64.ofInt(r4)*Int64.ofInt(r5)+Int64.ofInt(r6)*Int64.ofInt(r7)+Int64.ofInt(r8)*Int64.ofInt(r9);
```

**Comment by kLabz** [comment]
Is there a reason why you cannot do that? (as suggested by Aurel if I understood correctly)
```haxe
var r0:Int64 = 54237582;
var r1:Int64 = 27764462;
var r2:Int64 = 10097191;
var r3:Int64 = 1715585;
var r4:Int64 = 23865137;
var r5:Int64 = 42003240;
var r6:Int64 = 13297986;
var r7:Int64 = 91340915;
var r8:Int64 = 30308092;
var r9:Int64 = 44409605;

var fl:Int64 = r0 * r1 + r2 * r3 + r4 * r5 + r6 * r7 + r8 * r9;
trace(fl); // 5086233553797349 on eval at least
```

**Comment by flashultra** [comment]
Well , it' possible solution , but I need to be careful because I also use  shift operations. 
So to work I should shift only ```low``` part of the ```Int64```.
Maybe is feasible solution , because I use ```Vector``` and it's not possible to use ```Int64.ofInt(...)``` with ```Vector<Int>``` ( return 
```No @:arrayAccess function for haxe.ds.Vector<Int> accepts arguments of Int and haxe.Int64``` )

Thank you, I will try it.
