### ISSUE TITLE
Static var order initialization

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9482]
Hej,

I just ran into a strange error that I've never noticed before with this example : http://old.haxe.org/api/haxe/xml/proxy/examples/localisation
Of course, I've changed Hash into StringMap, but if you inverse order between `text`and `all`, php and js throw an error at runtime like "Cannot read property 'get' of undefined" (related to `all.get`)
Is order in statics important now ? Did that change recently or is this like that for long time and I've just not noticed that please ?

**Comment by Simn** [comment]
You've just not noticed that.
