### ISSUE TITLE
Unused TypeParamDecl.params

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9490]
`params` were added to `TypeParamDecl` 8 years ago in this commit - a6418590b1acca23157bc9cef55192aad7a9a4d5 - with message "allowed parametrized type parameters at syntax level".

But since then there was no use for this and syntax that `Printer` produces with those params present is invalid.

Is there a plan to introduce some usage for such syntax or may the property be removed in next major release?

**Comment by nadako** [comment]
Interesting. I assume the intended syntax is something like `class C<T<S>>`, but there was no parsing rules ever added for this and I'm curious what this would be useful for. @ncannasse?

**Comment by Simn** [comment]
I thought this parsed at some point, but looks like I was wrong. In that case there's nothing to change here for the time being.

**Comment by vonagam** [comment]
Well, i assumed that there wont be any usage of removal until next major version to be on a safe side, but why close issue now? I mean there is still no answer about why params were added or what is the plan about them and there is unused (only one to my knowledge so far) property present for 8 years, if you close this issue you might forget to do something about it when times comes...
