### ISSUE TITLE
Type.createEmptyInstance() can' get field value.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9492]
js target ,Haxe Compiler 4.2.0-rc.1+27c263eba 

```haxe
class Main {
	@:keep
	public var speed:Float = 1.0;

	public function new() {}

	public static function main() {
		var m:Main = Type.createEmptyInstance(Main); // new Main();//(Main);

		trace(m.speed); // undefined
	}
}
```

**Comment by nadako** [comment]
Because `createEmptyInstance` creates *empty* instance without any object initialization. It's good for deserializing, but you're probably looking for `Type.createInstance`.
