### ISSUE TITLE
[js es5] Super call missing when extending 2 levels

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#9501]
If we have two extern classes, one that extends the other, and we extend the top-most class in haxe, the constructor call is missing from the generated js (seems to be unrelated to dce)

Tested in 4.0.5 and latest master 24d7e79e37ed68f065315efb3e669acc54cfab3a

```haxe
extern class BaseExtern {
	function new(): Void;
}

extern class ExtendedExtern extends BaseExtern {
}

class HaxeClass
	extends ExtendedExtern // constructors are not called in js
	// extends BaseExtern // this works as expected
{
	
}

class Main {

	static function main() {
		trace('Expect "ExtendedExtern constructor called" followed by "BaseExtern constructor called"');
		new HaxeClass();
	}

}
```

The generated js for HaxeClass's constructpr looks like this
```js
var HaxeClass = function() { };
```
But I think it should look like this
```js
var HaxeClass = function() {
	ExtendedExtern.call(this);
};
```

Here's a repro

[haxe-extern-class-bug.zip](https://github.com/HaxeFoundation/haxe/files/4692007/haxe-extern-class-bug.zip)

**Comment by nadako** [comment]
Is this the same as #7837? does it fix #7836 as well by any chance? ^^
