### ISSUE TITLE
Syntax class for all targets

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe#9502]
Was reading [this page](https://haxe.org/manual/target-syntax.html) and looks like the nice type-safe and analyzer-friendly `Syntax` class isn't available for all targets and people still use "target magic". 

I think this targets might need a Syntax class:

 - [ ] C++
 - [ ] C#
 - [ ] Java
 - [ ] Lua

**Comment by nanjizal** [comment]
Also there does not seem to be any official polyfill provided?
I suggested something like this for Lime but instead Joshua added a complier switch in every required place, I guess simpler than checking how backwards compatible this might be, expect it would need more changes.
``` haxe
import haxe.extern.Rest;
@:access( js.Syntax.code )
extern class Syntax {
    #if( haxe >= "4.0.0" ) 
    public inline static function code(code:String, args:Rest<Dynamic>):Dynamic {
       return untyped js.Syntax.code( code, args );
    }
    #else
    public inline static function code(code:String):Dynamic {
        return untyped  __js__( code );
    }
    #end
}
```
I would expect changing C++ target without providing a polyfill that can be used for code that is required to be fairly haxe version intolerant is vital especially in the case of toolkits?

**Comment by nadako** [comment]
Note that the name `Syntax` doesn't make sense for bytecode targets, but we still might want to generate instructions directly.

**Comment by Aurel300** [comment]
We might call it `Syntax` for consistency, but a `Syntax.code` that takes a string makes no sense indeed. For something like HashLink we might make the "code" function consume a kind of assembly, but it seems like overkill.

**Comment by Simn** [comment]
I'm closing this issue because it's been inactive for a long time. I'm not against such a feature, but somebody would have to look into implementing it.
