### ISSUE TITLE
server/invalidate calls Path.UniqueKey.create for every cached module

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9509]
...which, as we figured, doesn't scale well when your project has thousands of modules :)

**Comment by nadako** [comment]
As @Neu2o mentioned, apparently, [what we use for `get_full_path` on Windows](https://github.com/HaxeFoundation/ocamllibs/blob/97e498e1b3bc2b3f08cfcae874b8529e4292bc3d/extc/extc_stubs.c#L410) is [not an actual filesystem access](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamea#remarks), but a string manupulation function, which explains why it's faster on Windows, unlike [realpath](https://www.man7.org/linux/man-pages/man3/realpath.3.html) on Unix, which resolves symlinks and such. It might make sense to find/write a simple path canonicalization function for unixes to make them faster there too. *(This is of course unrelated to the original issue, we still shouldn't do any syscalls there in the first place)*.

**Comment by RealyUniqueName** [comment]
@nadako I've pushed an implementation, which doesn't access file system. Could you please compare unix/windows again?

**Comment by nadako** [comment]
Will do when I have some time ^^

**Comment by RealyUniqueName** [comment]
This can't go into "Hotfix", because it already generates too many conflicts with 4.1_bugfix branch.

**Comment by RealyUniqueName** [comment]
However, I've cherry-picked ["m_file" change](https://github.com/RealyUniqueName/haxe/commit/3aa4bdc7a4ccd5bc916e246ca8c2bad4172bdf74) into "Hotfix" as it's a small and isolated change and it optimizes "server/invalidate" requests.
