### ISSUE TITLE
[lua] No output when trying to build a library

### ISSUE THREAD

**Issue by kyubuns** [HaxeFoundation/haxe#9511]
in 4.1.1 (All of them are working fine in haxe 4.0.5.)

LibTest.hx

```haxe
@:keep
@:expose
class LibTest {
    static function add(a: Int, b: Int) : Int {
        return a + b;
    }
}
```

lib_test_lua.hxml
```haxe
LibTest
-lua lib_test.lua
```

lib_test_js.hxml
```haxe
LibTest
-js lib_test.js
```

lib_test_cs.hxml
```haxe
LibTest
-cs lib_test_cs
```

lib_test_js.hxml and lib_test_cs.hxml are success.
However, lib_test_lua.hxml doesn't output anything.
no lib_test.lua and no error message.

All of them are working fine in haxe 4.0.5.

**Comment by nadako** [comment]
That's #9489

**Comment by kyubuns** [comment]
Oops, Sorry!
I searched for open issues, but I missed searching for closed ones!
I'll be careful.
