### ISSUE TITLE
[lua] When an Array is returned, the first element is lost

### ISSUE THREAD

**Issue by kyubuns** [HaxeFoundation/haxe#9512]
in Haxe4.1.1.

Sample.hx
```haxe
@:expose
class Sample {
    static function main(): Array<Int> {
        return [10, 20, 30];
    }
}
```

sample2.lua
```lua
fromHaxe = require 'sample'

print('native')
local a = { 10, 20, 30 }
for i, m in ipairs(a) do
  print(string.format("%d: %s", i, m))
end

print('haxe')
local b = fromHaxe.Sample.main()
for i, m in ipairs(b) do
  print(string.format("%d: %s", i, m))
end
```

run
```bash
haxe -main Sample -lib hxbit -lua sample.lua && lua sample2.lua
native
1: 10
2: 20
3: 30
haxe
1: 20
2: 30
```

I lost first element.

---

js returns the correct result. (Probably other languages too.)

```js
var fromHaxe = require('./sample')

console.log('native')
var a = [ 10, 20, 30 ]
for (var i = 0, len = a.length; i < len; ++i) {
  console.log(`${i}: ${a[i]}`);
}

console.log('haxe')
var b = fromHaxe.Sample.main()
for (var i = 0, len = b.length; i < len; ++i) {
  console.log(`${i}: ${b[i]}`);
}
```

```bash
haxe -main Sample -lib hxbit -js sample.js && node sample2.js
native
0: 10
1: 20
2: 30
haxe
0: 10
1: 20
2: 30
```

---

I thought it was a bug in haxe.io.Bytes.getData, but it was occurring in all of the arrays, so I rewrote this issue.

**Comment by vonagam** [comment]
Lua unlike most languages starts arrays indices at 1, not 0.
Haxe uses zero-based indexing.

So haxe compatible `Array` returned from `Sample.main` produces unexpected result when used with lua's `ipairs` which starts indexing from 1.

Return not `Array`, but `lua.Table` from `Sample.main` if you want to expose it for lua compatible usage. You can get a lua table from a haxe array with `lua.Table.fromArray`.

**Comment by kyubuns** [comment]
@vonagam 
Thanks for your response.
I'm sorry. This question did not solve the real question of my own.
It's understandable that I should return (lua-only) Table instead of Array.

haxe.io.Bytes.getData returns BytesData, this is an Array<Int> in lua.
Other languages return arrays that can be used natively, but only lua is difficult to use natively without converting the Array to a Table.
https://api.haxe.org/haxe/io/BytesData.html
How should this difference be contained?

**Comment by vonagam** [comment]
If you are talking about multiple compilations for different targets with same source code then you will need to remove return type and use conditional compilation to convert `BytesData` to a table only for lua, so your original method becomes:
```haxe
static function main() {
  var data = haxe.io.Bytes.ofHex('ffff0000ffff').getData();
  #if lua
  return lua.Table.fromArray(data);
  #else
  return data;
  #end
}
```

If you are asking if there is way to contain the difference in a sense to make it more comfortable to do this conversation automatically. I recommend using something like this abstract:
```haxe
import lua.Table;
import lua.PairTools;

@:forward abstract LuaArray<T>(Table<Int, T>) from Table<Int, T> to Table<Int, T> {
  @:from static inline function fromArray<T>(array: Array<T>): LuaArray<T> {
    return Table.fromArray(array);
  }

  @:to function toArray(): Array<T> {
    final array = new Array<T>();
    PairTools.ipairsEach(this, function(index, element) {
      array.push(element);
    });
    return array;
  }
}
```

So if you compile only for lua your original function can be converted to:
```haxe
static function main2(): LuaArray<Int> {
  var data = haxe.io.Bytes.ofHex('ffff0000ffff').getData();
  return data;
}
```

**Comment by kyubuns** [comment]
Thank you so much!!
The code is very usable.
Both answers were what I was asking.

and.
I guessed that Haxe has published an interface that can be used from NativeCode. (I found it different)
So I thought that it was wrong to publish Array<Int> to Lua using the standard library (io.Bytes.getData).
Do you have a reference page for Haxe's philosophy?

(Now that the problem is solved, I will close this issue. I'm sorry I took your time with my misunderstanding.)

**Comment by vonagam** [comment]
No problem, i was writing lua externs recently when i encountered the same unexpected discrepancy. For myself i solved it with `LuaArray` in return and arg types.

I don't think there is such page (about philosophy). Also different targets have different maintainers (as i understand) and they might have slight difference in views/style/implementations. Plus historical reasons (like something was introduced long ago in the past and now it is hard to introduce a breaking change).

Bonus: if you will use `LuaArray`, you may find this `LuaIndex` useful too when you need to return/receive an index in an array from lua code.

```haxe
abstract LuaIndex(Int) {
  inline function new(value: Int) {
    this = value;
  }

  @:from static inline function fromZeroBased(index: Int) {
    return new LuaIndex(index + 1);
  }

  @:to inline function toZeroBased() {
    return this - 1;
  }
}
```
