### ISSUE TITLE
Confusing error with --run without argument

### ISSUE THREAD

**Issue by peter-vano** [HaxeFoundation/haxe#9513]
Hello, after installed haxe 4.1.1 on my Mac and run "haxe --run" I got this to my console:

Haxe: 4.1.1; OS type: unix;
File "src/compiler/haxe.ml", line 820, characters 50-57
Called from file "arg.ml", line 267, characters 8-27
Called from file "src/compiler/haxe.ml", line 975, characters 3-86
Called from file "src/compiler/haxe.ml", line 1019, characters 1-21
Called from file "src/compiler/haxe.ml", line 632, characters 3-11
Called from file "src/compiler/haxe.ml", line 1233, characters 1-35
File "src/core/globals.ml", line 117, characters 1-7: Assertion failed

**Comment by Aurel300** [comment]
`--run` requires an argument. For example, if you have a file called `Foo.hx` in the current directory that contains:

```haxe
class Foo {
  public static function main() Sys.println("hello world");
}
```

Then you can execute it by running `haxe --run Foo` from the terminal.

I suggest we keep this issue open and add errors for argument mis-use.

**Comment by peter-vano** [comment]
Yeah, thanks for title updating of this issue
