### ISSUE TITLE
[java/jvm] Option to not copy jars to lib folder

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#9515]
Could we please get a compiler flag to avoid copying all the dependencies specified by --java-lib next to the build output? When developing something like an Android or web application where the Haxe-generated jar plugs into a larger framework, having the copied libs folder is unnecessary.

Having an option to avoid copying should speed up builds a bit, since it's not uncommon to have 100+ MB of jar libs.

**Comment by back2dos** [comment]
> Having an option to avoid copying should speed up builds a bit, since it's not uncommon to have 100+ MB of jar libs.

If that is the main concern, perhaps it could be generally avoided via an mtime check instead of making this an additional configuration option.

**Comment by Simn** [comment]
I'll just add `--java-lib-extern`. I would prefer to solve this as part of #7450 instead, but it looks like that one's gonna take a while to design right.

**Comment by aduros** [comment]
Just a heads up that this is in the change log for 4.1.2 but it doesn't actually seem to be present in the build at least on Linux.

**Comment by Simn** [comment]
@RealyUniqueName Could you check what happened there?

**Comment by RealyUniqueName** [comment]
My bad. 
Somehow I managed to add it to the change log without actually cherry-picking the commit. 
It's in 4.1_bugfix branch now for sure. Will be released with 4.1.3.
