### ISSUE TITLE
[Java] a few classes seem to get output to the wrong package

### ISSUE THREAD

**Issue by jedwards1211** [HaxeFoundation/haxe#9520]
I'm working on dumping all of the Haxe core classes into a JAR I can share between things.

I noticed a few packages that get output outside of the `haxe` root package: `_EnumValue`, `_UInt`, and `_Xml`.  Based on packages like `haxe._Int32` being present, it seems like these are supposed to be `haxe._EnumValue`, `haxe._UInt` and `haxe._Xml`.

![image](https://user-images.githubusercontent.com/1448194/83489788-96b7a200-a474-11ea-84c2-21b78575de49.png)

### My `build.hxml`
```hxml
-lib hxjava
-dce no

# it's necessary to exclude haxe.macro, otherwise we run
# into some errors for referencing macro API in non-macro context
--macro include("haxe", true, ["haxe.macro"])

# other packages / types you want can simply be listed as dot-paths
# (see https://code.haxe.org/category/compilation/compiling-libraries-without-main-class.html)
sys

# some toplevel types may need to be listed individually if there's
# no references to them within std (generated into haxe.root on JVM)
DateTools
# ...

# --jvm haxe-std.jar

-cp src
-main speleotica.Main
-java bin/java
```

**Comment by Simn** [comment]
Hmm, I think originally the whole `haxe.root` rewrite was done so the types could actually be referenced properly. However, I agree that it would be better to move these types into a `haxe` package as well to achieve better isolation.

In that case they should end up in `haxe.root._EnumValue` though.

**Comment by jedwards1211** [comment]
I see, looks like a lot of other types ended up as e.g. `haxe._Int32` rather than `haxe.root._Int32`.  I don't think this will cause me any difficulties at least.

**Comment by Simn** [comment]
That's because the module is `haxe.Int32`. Private types always become `package._Module.Type`.

**Comment by Simn** [comment]
I had already forgotten that we generate private types as nested classes in their containing module-class, if exists. We now get `haxe/root/Xml$XmlType_Impl.class`, which is correct.
