### ISSUE TITLE
[lua] String API is broken with `--no-inline`

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#9530]
```haxe
class Main {
	static function main() {
		var s = "sss";
		trace(s.lastIndexOf("s", 0));
	}
}
```
```
$ haxe -main Main --no-inline --lua bin/test.lua && lua bin/test.lua
Runtime Error: bin/test.lua:527: attempt to call a nil value (method 'lastIndexOf')
stack traceback:
        bin/test.lua:133: in function '_hx_error'
        bin/test.lua:527: in function <bin/test.lua:525>
        [C]: in function 'xpcall'
        bin/test.lua:829: in main chunk
        [C]: in ?
```

**Comment by jdonaldson** [comment]
I can't add proper field/method support to base runtime types like `string` in Lua.  It would mean altering the base prototype, which is a bad idea.  

I suppose the way to do this is just to check for string instance method invocation in the generator, and override that to a static method invocation?

**Comment by RealyUniqueName** [comment]
Yes. That's how it is handled in genphp7.
https://github.com/HaxeFoundation/haxe/blob/21cf1eb4a686a32ea85f41c8dc8be9da74c00837/std/php/Boot.hx#L743-L750

**Comment by jdonaldson** [comment]
Thanks I’ll check it out.

**Comment by RealyUniqueName** [comment]
Here's the generator part:
https://github.com/HaxeFoundation/haxe/blob/21cf1eb4a686a32ea85f41c8dc8be9da74c00837/src/generators/genphp7.ml#L2208-L2222

**Comment by piotrklibert** [comment]
Hello, I ran into this issue and decided to try fixing it. I think the fix on my branch should work - it simply rewrites `str.meth(args...)` to `String.prototype.meth(str, args...)`. What else do I need to do for it to be useful? Should I write a test for this somewhere? This is my first time contributing to Haxe, so I just started learning the ropes - any advice on how to proceed appreciated :)
