### ISSUE TITLE
Namespace and local variable name collision in try catch?

### ISSUE THREAD

**Issue by muchitto** [HaxeFoundation/haxe#9533]
So I have this little sample of code (this is supposed to work, right?):

`src/Main.hx`

```haxe
import errors.ErrorException;

function main () {
    var errors = "";
    try {
    } catch (e : ErrorException) {
        errors = e.message;
    }
}
```

`src/errors/ErrorException.hx`

```haxe
package errors;

import haxe.Exception;

class ErrorException extends Exception { }
```

Currently this code gives me a `Local variable errors is preventing usage of this type here` -error on the `catch`.

Using Haxe `4.2.0-rc.1+fea3d9384`

**Comment by nadako** [comment]
Huh, yeah this should work.

**Comment by nadako** [comment]
I believe this is also a regression?

**Comment by nadako** [comment]
> I believe this is also a regression?

I guess not though:) f27f60bdfe0b8bfcf85c923be407ee73e57b367d

**Comment by nadako** [comment]
Maybe this check is not needed anymore because of the smart variable renaming we have nowadays?

**Comment by muchitto** [comment]
Well that was fast :D
