### ISSUE TITLE
could type parameter constraints get output to Java?

### ISSUE THREAD

**Issue by jedwards1211** [HaxeFoundation/haxe#9536]
So I'm using this kind of funny generic pattern:

```hx
class UnitType<T:UnitType<T>> { ... }
class Unit<T:UnitType<T>> {
  public final type:T;
}
class Length extends UnitType<Length> { ... }
class Angle extends UnitType<Angle> { ... }
```

This is so that I can get compile-time errors if I try to use a `Unit<Length>` where a `Unit<Angle>` is expected.

The type parameter constraints don't survive in the output Java:

```java
public class Unit<T> extends haxe.lang.HxObject
```

However in the Java code I'm porting this from it would totally work:

```java
public class Unit<T extends UnitType<T>> extends haxe.lang.HxObject
```

Are the technical limitations that prevent Haxe from being able to output this?

When I wrote this same pattern in C++, templates actually worked way better for this than generic types do.  Maybe there's something similar I can do with Haxe macros to output templatized copies of these classes?

**Comment by Simn** [comment]
We are not going to update the Java code generator at this point.

I will however check what the JVM generator does here.

**Comment by jedwards1211** [comment]
No worries, after experimenting more with Haxe I think I'm going to have to try something else for my cross-platform libraries, neat as Haxe is.  We're also considering using C++ as a source language and Swig and Emscripten to generate wrappers to connect it to other languages.

**Comment by Simn** [comment]
I don't really know how to test this properly, but the generated signature looks fine when decompiled through IntelliJ.
