### ISSUE TITLE
analyzer-optimize and reference

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9543]
Example:

```haxe
class Main {
  public static function main() {
    var foo: Int = 0;
    var bar: cpp.Reference<Int> = foo;
    foo += 1;
    trace(bar);
  }
}
```

With `-D analyzer-optimize` will leave only `trace(0)` inside `main`, while without the optimisation the traced result will be 1.

(`cpp.Reference` typedef has `@:semantics(reference)`, don't know if it is relevant.)

**Comment by Simn** [comment]
Hmm, interesting. I thought we already dealt with this in the context of `cs.Ref` which should be the same thing. I'll have to check why it's not working for `cpp.Reference`.
