### ISSUE TITLE
Bug of feature: `implements Dynamic` with `resolve` field

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#9557]
We used to have a feature where a class with `implements Dynamic` would route field calls through a `resolve(name:String)` method. Since `implements Dynamic` is nowadays restricted to externs, I don't think that this feature makes sense anymore.

```haxe
extern class Extern implements Dynamic {
	public function resolve(s:String):Dynamic;
}

class Main {
	static public function main() {
		var e:Extern = null;
		trace(e.foo);
	}
}
```

Generated:

```js
Main.main = function() {
	console.log("source/Main.hx:8:",null.resolve("foo"));
};
```

Can we remove this `resolve` lookup? I can't imagine anyone using this intentionally. It also seems weird that adding such a method entirely changes typing.

**Comment by nadako** [comment]
Sounds safe to remove. It could make sense for externs for haxe-generated libraries, but since haxe doesn't have non-extern `implements Dynamic`, there's no way this is used/useful.

**Comment by Simn** [comment]
I've kept `AccResolve` because it is used by the magic `haxe.xml.Proxy` which apparently survived the Haxe 4 purge. I suppose I'll just randomly remove that at some point and see if somebody complains.
