### ISSUE TITLE
[java] use parameter names from -parameters when loading jars

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9573]
Since Java 8, `javac` has a `-parameters` flag which includes method parameter names in the bytecode, which Haxe doesn't seem to use: http://openjdk.java.net/jeps/118

Haxe already seems to extract parameter names from debug info (`javac`'s `-g` flag), but it should support both. We need to figure out how this info is stored exactly.

**Comment by Simn** [comment]
https://docs.oracle.com/javase/specs/jvms/se14/html/jvms-4.html#jvms-4.7.24

Could you point me to an example .jar that has this information?

**Comment by Gama11** [comment]
You could just use the test case from #9575 and replace `-g` with `-parameters` temporarily.
