### ISSUE TITLE
Add option to suppress "for function argument xyz" in errors.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9581]
I generally don't find it that useful, since nowadays IDE support is good and the position is 10 times more helpful than an argument name (especially if it's `x` or `s` or something).

Primarily I'm asking so that it can be avoided for macro generated calls, where it's useless at best, confusing at worst. Being able to slap `@:suppressArgNames` on a call (or even a more complex tree) would be nice.

**Comment by Gama11** [comment]
Maybe this would be obsolete if "related information"-errors were handled better? #9317

**Comment by Simn** [comment]
I agree that this additional information is obsolete. I never found it very useful in the first place because you can't see the function argument names at the call-site anyway.

Let's just remove it and see if it breaks anyone's workflow.

**Comment by RealyUniqueName** [comment]
Apparently it doesn't.
