### ISSUE TITLE
[ide] everything is red if a single struct in an array is missing a field

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9584]
```haxe
class Main {
	static function main() {
		final foo:Array<{x:Int, y:Int}> = [
			{x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1},
			{x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, y: 1}, {x: 0, }
		];
	}
}
```

This doesn't feel great if you have autosave and diagnostics enabled. While you're typing, whenever a field is missing, everything is red:

![image](https://user-images.githubusercontent.com/2620907/84598296-044ad180-ae6a-11ea-879d-ebb86ec306a5.png)

Instead, we should only highlight the range of the offending object literal if possible.

**Comment by RealyUniqueName** [comment]
The error is 
```
src/Main.hx:5: characters 74-82 : Object requires field y
src/Main.hx:3: lines 3-6 : { x : Int } should be { y : Int, x : Int }
src/Main.hx:3: lines 3-6 : { x : Int } has no field y
```
So it's the position of follow up messages is wrong.
