### ISSUE TITLE
parseInt of Int returns null

### ISSUE THREAD

**Issue by gene-pavlovsky** [HaxeFoundation/haxe#9587]
I don't know if the following is a bug or a feature.
```haxe
var data:Dynamic = 10;
trace(parseInt(data)); // null
```

This is a recent change, in haxe 3.x and 4.0.0-rc.3, parseInt returns the number as is.
We had some code that applies parseInt to data that comes from an RTMP network connection. The code suddenly stopped working after update to haxe 4.0.5. Turned out, the network service was actually supplying an integer (not as a string).

Looking at the documentation, the particular case seems a bit ambiguous. If this issue is indeed a "feature", and the compiler developers feel strongly about keeping it as is, then at least an explicit mention of this scenario should be added to the documentation.

**Comment by Gama11** [comment]
Relevant: https://github.com/HaxeFoundation/haxe/issues/9112

**Comment by gene-pavlovsky** [comment]
Heh, I searched first and didn't find that one.
I think @RealyUniqueName makes a fair point from a theoretical standpoint ("Std.parseInt() expects a string. A value of any other type is unspecified behavior.").
However as this worked in Haxe 3.x (by coincidence or otherwise), this is a breaking change indeed, and should be at least documented, if not reconsidered.

**Comment by Simn** [comment]
This is an invalid value being assigned via `Dynamic`. We cannot document every instance of that, and I'm pretty sure this wasn't generally working in Haxe 3 either. What target are you using?

Every bugfix can be called a breaking change if you try hard enough, so let's please remain pragmatic here.

**Comment by gene-pavlovsky** [comment]
@Simn yes you're right, I don't argue with the philosophy of your argument.

Target is `js`, and I think the case I mentioned is quite common (parsing data that came from a network service, so by it's nature dynamic). It's also sadly common for BE developers to sometimes send numbers as strings, and sometimes as numbers, so a FE developer using Haxe/JS might put Std.parseInt in there just in case (or it was string coming from BE, then BE guys change it to int, and no one notices). 

Then suddenly parsing breaks at run-time when updating to another Haxe version. That's not Haxe's fault per se. I wish parseInt of int would return null in 3.x, then it wouldn't be an issue. But it's a bit sad that the behavior changed. Was parseInt implementation somehow greatly improved, leading to the behavior change when an Int argument is passed? If not, would it be possible to return the old behavior in such cases? Or do you feel it's more correct to silently return null? An exception would be more healthy, I think, at least the failure in a case like I described will be more evident.

**Comment by Gama11** [comment]
Even if it was desirable to ease the Haxe 3 -> 4 migration by changing the implementation in some way, it's probably too late for that at this point. Stable releases are already at Haxe 4.1.x and most people probably already dealt with this in some way if it was an issue for them.

**Comment by Gama11** [comment]
(it could be added to https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-4.0.0 though)

**Comment by Simn** [comment]
If somebody wants to add it there I don't mind.

In general, this is well within the parameters of what's acceptable to change between two major versions. It now works more consistently across the targets, so there are no plans to change this behavior in any direction.
