### ISSUE TITLE
Constrained monomorph infers Float instead of Int sometimes

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#9594]
This worked before constrained monomorphs:

```haxe
class Test {
  static function main() {
    var arr:Array<Array<Int>> = [];
    arr.sort(sort);
  }

  static function sort(a, b) {
    if (a.length != b.length) return a.length - b.length;
    return 0;
  }
}
```

And now fails with:

```
Test.hx:4: characters 12-16 : error: Float should be Int
Test.hx:4: characters 12-16 :  have: (...) -> Float
Test.hx:4: characters 12-16 :  want: (...) -> Int
Test.hx:4: characters 12-16 : For function argument 'f'
```

**Comment by Simn** [comment]
I don't really understand what changed here. The compiler has always inferred typeless numeric binops to `Float`, so that `sort` function should have a `Float` return type due to the `return a.length - b.length`.  Where did the `Int` come from before...

**Comment by Simn** [comment]
Well, apparently I'm wrong because `$type(a.length - b.length)` says `Int`. What am I missing here...

**Comment by kLabz** [comment]
Do you want me to bisect this?

**Comment by Simn** [comment]
That's just gonna lead to the constrained monomorph PR.

The good news is that I just found a `(* TODO: check what this did exactly *)` in some code that's related.
