### ISSUE TITLE
[java][jvm] OutOfMemoryError with ~/\b/g.split()

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9601]
Splitting on a word boundary with the `g` flag seems to be a bad idea on the Java and JVM targets:

```haxe
function main() {
	trace(~/\b/g.split("Test"));
}
```

![image](https://user-images.githubusercontent.com/2620907/84817232-e1105580-b014-11ea-9121-fc86b9beadba.png)

Doesn't seem to be an issue on other targets (though it does give inconsistent results across targets, not sure this is specified?).

**Comment by Simn** [comment]
So what exactly should this do, other than not melting CPUs?

**Comment by Simn** [comment]
This can also be reproduced with `~/^/g` and probably any other zero-length match.

**Comment by Gama11** [comment]
>So what exactly should this do, other than not melting CPUs?

As mentioned, targets seem to disagree there:

- `[,T,e,s,t]` for eval
- `[,T,est]` for neko, cpp and hl
- `[,Test,]` for js, swf, python, php, lua and cs

The last one is also the result that makes the most sense to me.
