### ISSUE TITLE
[jvm] sqlite utf8  garbled.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9610]
// --java-lib bin/sqlite-jdbc-3.31.1.jar
// --jvm bin/main.jar

```haxe
class Main {
	static function main() {
		var cnx = sys.db.Sqlite.open("./backup.data");

		var xx = cnx.quote("豪鬼");

		trace(xx);
	}
}
```

D:\project\jj\cocosTools>java -jar bin/main.jar
src/Main.hx:9: @@HX_ESCAPE0_1@@

D:\project\jj\cocosTools>hl bin/main.hl
src/Main.hx:9: '豪鬼'

**Comment by Simn** [comment]
I think this is working as designed, but I'm completely unfamiliar with this API.

**Comment by Simn** [comment]
The implementation of `quote` is this:

```haxe
	public function quote(s:String):String {
		return "@@HX_ESCAPE" + id + "_" + escapes.push(s) + "@@";
	}
```

So this seems to do whatever it is supposed to do.
