### ISSUE TITLE
improve error reporting when accessing non-static fields as static

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9612]
When we access a static field through an instance, we get a nice "cannot access static" error message, however when we're doing vice-versa, accessing non-static field through the class, we're getting a "no such field" error. We could probably check if there's a non-static field with that name and emit a better error message here.

```haxe
class C {
	public function new() {}
	public function nonStaticMethod() {}
	public static function staticMethod() {}
}

function main() {
	new C().staticMethod(); // Cannot access static field staticMethod from a class instance
	C.nonStaticMethod(); // Class<C> has no field nonStaticMethod
}
```

*PS: Props to @RichardBray for his video about haxe access modifiers that made me notice this small issue ^^*

**Comment by RichardBray** [comment]
Really interesting find. Also glad my video could help you spot this. It's nice to know the content I make is going to goo use.
