### ISSUE TITLE
Is it possible to overload ternary operator?

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9613]
Example (tried with instance function too):
```haxe
abstract Foo(Int) from Int {
  @:op(A ? B : C) private static inline function op(value: Foo, truthy: Int, falsey: Int)
    return value != 0 ? truthy : falsey;
}

class Main {
  public static function main() {
    var foo: Foo = 1;
    var bar = foo ? 1 : 0; // Error here: Foo should be Bool
    trace(bar);
  }
}
```

If it is not possible, maybe there should be a warning like for assignment operator?

Also found some inconsistency, when checked if an implicit cast to bool will work:
```haxe
abstract Foo(Int) from Int {
  @:to private inline function toBool(): Bool
    return this != 0;
}

class Main {
  public static function main() {
    var foo: Foo = 1;
    var bar = foo ? 1 : 0; // No error here now
    if (foo) bar = 2; // Works too
    var baz = ! foo; // Error here: Foo should be Bool
  }
}
```
So ternary operator successfully did cast, but negation failed to do the same.

**Comment by nadako** [comment]
See also #6893

**Comment by vonagam** [comment]
Ok, from the code i see that there is `type_binop` and `type_unop`, but no `type_ternary` - it just uses typing of `if`, so that's why it is successful in casting to bool unlike other boolean operators.

**Comment by RealyUniqueName** [comment]
I think we should not allow `@:op` for ternary because it's essentially an `if..else` expression. And who knows, maybe we will remove ternary one day to unlock `?` for other syntax applications.

**Comment by vonagam** [comment]
Yes, i think that reasonable thing is to add a warning and close the issue. Not much gain from allowing overload. (Doubt though that ternary will ever be removed.)
