### ISSUE TITLE
[js] google closure vs var shadowing

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9617]
For some reason, the [closure compiler](https://developers.google.com/closure/compiler) absolutely hates this piece of code:

```haxe
function main() {
	try {
		throw false;
	} catch (e:Any) {
		switch process(e) {
			case null:
				trace(1);
			case e:
				trace(e);
		}
	}
}

function process(e) {
	return e;
}
```

Generated JS (note the double `_g`):
```js
function Main_main() {
	try {
		throw haxe_Exception.thrown(false);
	} catch( _g ) {
		var e = haxe_Exception.caught(_g).unwrap();
		var _g = Main_process(e);
		if(_g == null) {
			console.log("src/Main.hx:7:",1);
		} else {
			var e = _g;
			console.log("src/Main.hx:9:",e == null ? "null" : Std.string(e));
		}
	}
}
```

Minify with:
```
java -jar compiler.jar --js main.js --js_output_file main.min.js
```

I haven't found a way to suppress this error, I think it just doesn't support shadowing of a catch variable (other shadowing cases seems to be fine, like the `e` in the example), so maybe we should do something on Haxe side here...

**Comment by nadako** [comment]
I've added hf-partner because it's a bit blocking for us. I'll see what I can do on the haxe code side (it's in tink_core actually), but in general this feels like something haxe should work around (because closure is so popular).

**Comment by nadako** [comment]
(side-stepped in https://github.com/haxetink/tink_core/pull/137/commits/d96ea9ef9e5a5fca33d0621085acb7dc26a8a1d9 for now)

**Comment by RealyUniqueName** [comment]
We can add a flag to `var_scoping_flags` to avoid shadowing catch vars
