### ISSUE TITLE
Unable to compile when a package named `js.xxx.xxx` exists

### ISSUE THREAD

**Issue by cedx** [HaxeFoundation/haxe#9633]
See project: https://github.com/cedx/free-mobile.hx
It's a cross platform project.

I have inside a JS extern for package `node-fetch` wrapped in a `#if nodejs` condition:
https://github.com/cedx/free-mobile.hx/blob/main/src/js/npm/fetch/Fetch.hx

Previously, I've put this extern in a `fetch` package and everything worked fine:
https://github.com/cedx/free-mobile.hx/actions/runs/130218898

I decided to rename the `fetch` package to `js.npm.fetch`, and now all non-JS targets trigger the following error:
`(unknown) : You cannot access the js package while targeting XXX (for js.npm.fetch.Fetch)`

https://github.com/cedx/free-mobile.hx/actions/runs/142750481

All code consuming this extern is wrapped in a `#if nodejs` condition, so I don't understand why this error is raised. I've tried to use `#if js` conditions, but this does not change anything.

It seems that we can't have packages named `js.xxx.xxx` when targeting non-JS platforms even if conditional compilation exclude these packages. EDIT: after playing a bit, the sole existence of an empty `.hx` file in a `js` folder or subfolder is sufficient to trigger this issue.

Haxe: 4.1.2 on Windows x64.

**Comment by RealyUniqueName** [comment]
You can add `--macro allowPackage("js")`.
But if that's not absolutely necessary I recommend to choose another top-level package name.

**Comment by RealyUniqueName** [comment]
Nothing to fix here.
Feel free to reopen if you are not agree.

**Comment by cedx** [comment]
For me, this is clearly a bug: the compiler should not complain about the usage of a package that is not consumed by the target, whatever its name. But the fix is easy on my side: so let's keep this issue closed.

**Comment by RealyUniqueName** [comment]
It's a designed behavior.
Otherwise a misuse of API in `js` package while building for any other target would lead to runtime crashes or native compilation failures.

**Comment by cedx** [comment]
OK, thanks @RealyUniqueName for the clarification.
