### ISSUE TITLE
haxe.maco.Position is defined as a typedef, but doesn't behave like a typedef.

### ISSUE THREAD

**Issue by skylerparr** [HaxeFoundation/haxe#9635]
I checked the source code of `haxe.macro.Position` and it's defined as a typedef. https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/macro/Expr.hx#L32

But when I checked it it against a simple program: 
```haxe
package;

import haxe.macro.Expr;

typedef Foo = {
  file: String,
  min: Int,
  max: Int
}

class Main {

  macro public static function printContext(): Expr {
    var pos: Position = haxe.macro.Context.currentPos();
    trace(pos);
    trace(pos.file);
    trace(pos.min);
    trace(pos.max);

    var foo: Foo = {file: "file", min: 29, max: 10};
    trace(foo);
    trace(foo.file);
    trace(foo.min);
    trace(foo.max);

    return macro "worked";
  }

  public static function main() {
    trace(printContext());
    trace("hello world");
  }
}
```
When I ran it, this is my result:
```
$ haxe -cpp out -main Main && ./out/Main.exe
Main.hx:15: #pos(Main.hx:30: characters 11-25)
Main.hx:16: null
Main.hx:17: null
Main.hx:18: null
Main.hx:21: {min: 29, max: 10, file: file}
Main.hx:22: file
Main.hx:23: 29
Main.hx:24: 10
haxelib run hxcpp Build.xml haxe -Dhaxe="4.1.2" -Dhaxe3="1" -Dhaxe4="1" -Dhaxe_ver="4.102" -Dhxcpp_api_level="400" -Dhxcpp_smart_strings="1" -Dsource-header="Generated by Haxe 4.1.2" -Dstatic="1" -Dtarget.name="cpp" -Dtarget.static="true" -Dtarget.sys="true" -Dtarget.threaded="true" -Dtarget.unicode="true" -Dtarget.utf16="true" -Dutf16="1" -I"" -I"C:\\HaxeToolkit\\haxe\\extraLibs/" -I"C:\\HaxeToolkit\\haxe\\std/cpp/_std/" -I"C:\\HaxeToolkit\\haxe\\std/"
Main.hx:30: worked
Main.hx:31: hello world
```
As you can see, I created a typedef with the same fields and I got what I expected. But the position object just printed nulls. Whatever Context.currentPos() is supposed to be, it's also causing hscript to return `null` on the position info https://github.com/HaxeFoundation/hscript/blob/master/hscript/Macro.hx#L250

Running this on a windows 10 machine. 

Am I missing something?

**Comment by RealyUniqueName** [comment]
As you can see here
https://github.com/HaxeFoundation/haxe/blob/e89879a1b31bc50bf8ea1e898f7664a4bea0b937/std/haxe/macro/Expr.hx#L25-L32
Inside of a macro context `Position` is not a typedef. It's a direct reference to an internal ocaml structure. 
You can use [`haxe.macro.Context.getPosInfos`](https://api.haxe.org/haxe/macro/Context.html#getPosInfos) to get a Haxe structure out of it.

**Comment by skylerparr** [comment]
I see. Thank you for the response.
