### ISSUE TITLE
[ide] no completion for local var metadata

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9639]
```haxe
function main() {
	var @
}
```

```haxe
function main() {
	var @ test = 10;
}
```

There's no completion results after the `@` in either case.

(related to https://github.com/HaxeFoundation/haxe/issues/9618)

**Comment by Simn** [comment]
The second case is easy to fix. The first one seems somewhat problematic because we need some sort of AST for the variable...
