### ISSUE TITLE
Allow Any instead of Dynamic as type param in catch clauses

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9641]
Example:

```haxe
try {}
catch (a:Array<Dynamic>) {} // fine
catch (a:Array<Any>) {} // compiler error
```

With `Any` being preferable more often than not, it would be nice not to be forced to use `Dynamic` instead.

**Comment by nadako** [comment]
I wonder if that should just recursively follow to the underlying type and check if it's Dynamic in the end.

**Comment by Antriel** [comment]
A lot of time I can't use `Any` due to variance (I think?). Since it seems related to this, I'm gonna ask here:
```haxe
var a = [1];
var aa:Array<Any> = a; // error: Int should be Any
```
Can something be done here? I understand that if this worked, then `aa.push("str")` would compile, and is therefore dangerous. But the only solution to situations where this pattern is needed is doing `Array<Dynamic>`, which is even worse.

**Comment by RealyUniqueName** [comment]
You can use an abstract like this as a safe alternative to `Array<Dynamic>`:
```haxe
abstract AnyArray(Array<Dynamic>) from Array<Dynamic> {
	public var length(get,never):Int;
	inline function get_length():Int {
		return this.length;
	}

	@:from static public inline function from<T>(a:Array<T>):AnyArray {
		return a;
	}

	@:arrayAccess inline function get(index:Int):Any {
		return this[index];
	}
}
```
usage:
```haxe
var a = [1, 2];
$type(a); // Array<Int>
var b:AnyArray = a;
$type(b[0]); // Any
for(i in b) {
	$type(i); // Any
}
```

**Comment by Antriel** [comment]
Sure, handling it concretely isn't a problem. I'm looking for a general solution. `Any` allows storing anything, but requires a cast when going back. Which is perfect, but it stops working once it's a type parameter, and I always have to fall back to `Dynamic`.

**Comment by RealyUniqueName** [comment]
There was https://github.com/HaxeFoundation/haxe/pull/8450 but it didn't work out.
I think we need a separate issue for to discuss this.

**Comment by kevinresol** [comment]
@RealyUniqueName can we include this in the next patch release?

**Comment by RealyUniqueName** [comment]
Yes. The change is tiny and can't affect anything else, so I think it's ok.
