### ISSUE TITLE
My tetris code has stopped working it has been working since oct 2017.

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9646]
This error makes no sense, the code has been working for years I tried compiling to flash today and it errors on the abstract, I commented out as I think it's only used in a unit test, so it's not serious but thought I should flag.

https://github.com/nanjizal/PolyominoTriangles/blob/master/src/polyominoTriangles/game/RookAngle.hx#L119

Is this a bug, or have the rules changed on me again ? :)

../src/polyominoTriangles/game/RookAngle.hx:119: characters 18-31 : Abstract 'this' value can only be modified inside an inline function. 'clockRotate' modifies 'this'
../src/polyominoTriangles/game/RookAngle.hx:124: characters 18-35 : Abstract 'this' value can only be modified inside an inline function. 'antiClockRotate' modifies 'this'

```haxe
    public inline 
    function clockRotate(): RookAngle {
        return this = new RookAngle( this + 90 );
    }
    public inline 
    function antiClockRotate(): RookAngle {
        return this = new RookAngle( this - 90 );
    }
    public inline 
    function upsideDown(): RookAngle {
        return this = new RookAngle( this + 180 );
    }
    @:op(A++) public 
    function pp(): RookAngle {
         return clockRotate();
    }
    @:op(A--) public 
    function mm(): RookAngle {
         return antiClockRotate();
    }
```
Haxe Compiler 4.2.0-rc.1+308ed91e0 - (C)2005-2020 Haxe Foundation

Many thanks.

**Comment by Gama11** [comment]
That error was missing in some cases, so this is probably caused by a bugfix such as the one for #9295 or #9067.

In these cases, `inline` is required for the code to actually _work_. This just turns "silently failing at runtime" into a compile-time error.

**Comment by RealyUniqueName** [comment]
Gama11 is right.

**Comment by nanjizal** [comment]
No he is not exactly correct, since I can find no evidence of it ever failing silently at runtime, there are no related errors in any of the toolkit html examples that are still online and can be run from the readme.

I think the UnitTest may pull in all methods, but it was actually not used as far as I can tell so was likely DCE.

Yesterday was probably the first time I tried to compile it with flash for good reason.

Neko commented out so pretty sure it was built to neko, so any runtime error would likely have shown up, in neko or html5. But I think it was a feature I did not actually end up requiring.
https://github.com/nanjizal/PolyominoTriangles/blob/master/compile/polyominoTrianglesNME.hxml#L7

**Comment by RealyUniqueName** [comment]
It was not a runtime exception. It was a missing assignment. You can find more details  in the linked issues.

**Comment by nanjizal** [comment]
Thanks it's still not really clear, I am using haxe 4.2 ( version reference in report ), I noticed some commits related - but any changes that would make this possible to work are not working if that was the implication implied.

**Comment by nanjizal** [comment]
For future clarity of any googlers I presume this would be more suitable code.
```
@:op(A++) public 
    function pp(): RookAngle {
         return new RookAngle( this + 90 );
    }
```
