### ISSUE TITLE
[nullsafety] checked abstract over nullable fails unification with non-nullable

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9649]
Example:
```haxe
abstract Foo<T>(Null<T>) from Null<T> to Null<T> {}

@:nullSafety(Strict)
class MainA {
  public static function main() {
    var foo: Foo<Int> = null;
    var bar: Int = foo != null ? foo : 0; // works
    var baz: Int = 0;
    var qux: Int = foo != null ? baz = foo : 0; // error - cannot unify Foo<Int> with Int
    if (foo != null) baz = foo; // error - cannot unify Foo<Int> with Int
  }
}
```

One way to go about null-safety is to use an abstract over nullables like `Maybe<T>`. For some reason it successfully unifies with non-nullable type as a result of a conditional branch, but does not unifies with non-nullable inside said branch.

**Comment by RealyUniqueName** [comment]
Null checker performs unification checks only when a check for possible `null` values is passed successfully. So, I think it should allow such unifications when `Null<?>` is on the "top-level" of underlying type.

**Comment by vonagam** [comment]
Hm... so (as i understand) the issue is not about null-check, but about transitive cast (but it is produced only with null-safety enabled). As this is working:
```haxe
if (foo != null) baz = (foo: Null<Int>);
```
So, maybe ternary unifies `foo` and `0` into `Null<Int>` and then it is unified with `Int`, but  when you assign `Foo<Int>` to `Int` there is no direct cast and it becomes transitive (forbidden) one.

**Comment by vonagam** [comment]
Dismiss what i said above, didn't know about null safety (and its unification in particular).
