### ISSUE TITLE
unary plus operator

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9653]
There is `++/--a`, `a++/--`, `a+/-b`, `a+/-=b`, but only `-a` without `+a`.
It is allowed in js, c++, c#, java, python, c and others.
So there is an intuitive expectation of it being present.

It can be used to make a code a little more readable, aligned.
And it will add one more possible operator for overloading.
Also on c++ and c# it is possible that unary plus is overloaded in an external class, it will become easier to communicate.

One thing to think about here is numeric promotion functionality on static targets - should it be supported/kept or not (plus can be discarded for non-overloaded external usages so not to deal with it).

**Comment by nadako** [comment]
Here's what I've found: https://github.com/HaxeFoundation/haxe/blob/1c167d0375530372150caf2c70dcc14f0b32c7d9/src/syntax/grammar.mly#L1353-L1359

**Comment by vonagam** [comment]
Ok, so the removal was done in 8e96723, year 2011.
Based on the [changelog](https://github.com/HaxeFoundation/haxe/blob/7dc565e6335183ab1611704f7ce9510e352fc5a3/extra/CHANGES.txt#L1365) operator overloads were added to abstracts in 2013.

Without overloads i can understand the decision, since this removes 2 out of 3 pro points and leaves only formatting one against possible errors.

I think that having an additional short unary operator with existing opposite one is useful. As an example, for my use case i though about using `-` and `+` as shortcuts for null equality check in my variant of `Maybe` abstract:
```haxe
if (+value) trace('value is not null');
if (-value) trace('value is null');
```

I also see how some abstract can use it for an explicit cast to a number.

**Comment by Simn** [comment]
I don't see much value in adding this.

**Comment by vonagam** [comment]
No prob, but to repeat the value was in overloads, externs (c++, c#) and readability (alignment).
