### ISSUE TITLE
Sys.getChar on cpp target blocks indefinitely

### ISSUE THREAD

**Issue by skylerparr** [HaxeFoundation/haxe#9658]
Reproducible with
```
$  cat Main.hx
package;

class Main {
  public static function main() {
    trace("hello world");
    var char: Int = Sys.getChar(false);
    trace(char);
  }
}
```
Built with:
```
$ haxe -cpp out -main Main
```
No matter what I type, the char code is never printed and the program just hangs and never exits. Tested with threading and getting the same result.

Tested on windows 10 version 2004.
```
$ haxe
Haxe Compiler 4.1.2 - (C)2005-2020 Haxe Foundation

hxcpp: [4.1.1]
```

**Comment by RealyUniqueName** [comment]
Can't reproduce on Linux. So it's probably a windows-only bug.

**Comment by skylerparr** [comment]
Still an issue with hxcpp [4.1.15] and haxe 4.1.3

**Comment by skylerparr** [comment]
Figured it out. It's only an issue when running the application in git bash on windows.
