### ISSUE TITLE
Confusing error with redundant `return` in init expr of field

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9659]
`Main.hx`:

```haxe
function main() {
	Foo.Bar;
}
```

`Foo.hx`:

```haxe
final Bar = {
	return 0;
}
```

```
>haxe --main Main --interp 
Main.hx:2: characters 2-9 : Missing return: Int
```

Compiles fine when removing the `return`  in `Foo.hx`, even though the error points to `Main.hx`. In a real project, this can make the source of the error quite hard to find, since there's likely many layers of indirection between the two (as was the case in haxe-language-server where I isolated this from).

It's not related to module-level fields as I originally thought, when `main()` and `Bar` are wrapped into classes, the same thing happens.

**Comment by nadako** [comment]
This seems like `ctx.ret` is not being reset before typing `Foo.Bar`, but so far I don't know when that should be done.

**Comment by nadako** [comment]
Okay, doing `ctx.ret <- mk_mono ();` after `save_field_state` in `type_var_field` fixes the error, but then again there should be an error when typing var field init, if `return` is found, then we wouldn't even need to reset `ctx.ret`.
