### ISSUE TITLE
haxe/http/HttpNodeJs.hx:50: ..: Usage of this field is deprecated

### ISSUE THREAD

**Issue by nanjizal** [HaxeFoundation/haxe#9664]
/usr/local/lib/haxe/std/haxe/http/HttpNodeJs.hx:50: characters 19-36 : Warning : Usage of this field is deprecated
Haxe Compiler 4.2.0-rc.1+5d48282d2 - (C)2005-2020 Haxe Foundation

Easy to reproduce with this hxml
```haxe
-cmd haxelib git folderNode https://github.com/nanjizal/folderNode.git
-cmd cd folderNode
-cmd haxe generateJS.hxml
```
I have no idea if folderNode code still valid was just tidying up by adding dox, but presume the depreciation warning within a still valid std method needs issue raised so it's not forgotten.

**Comment by RealyUniqueName** [comment]
API to use instead: https://nodejs.org/api/url.html#url_constructor_new_url_input_base

**Comment by nanjizal** [comment]
@RealyUniqueName
Is this really a 4.1 patch issue because the code is in the current Std library, within a function that is not depreciated?
https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/http/HttpNodeJs.hx#L50

**Comment by RealyUniqueName** [comment]
Maybe. But it works, so I think it's a lower priority.

**Comment by RealyUniqueName** [comment]
If somebody will fix it, I'm ok to move it to "Hotfix"
