### ISSUE TITLE
Java naming/path clash?

### ISSUE THREAD

**Issue by skial** [HaxeFoundation/haxe#9675]
Targeting the java target with the following code:

```Haxe
// Main.hx
class Main {

    public static function main() {
        var foo:Foo<String> = 'bar';
        trace( foo, _foo.Foo.v );
    }

}
// Foo.hx
abstract Foo<T>(T) from T {}

// _foo/Foo.hx
package _foo;

abstract Foo<T>(T) {
    public static final v:Any = {};
}
```

Throws at runtime:

```
Exception in thread "main" java.lang.NoClassDefFoundError: _foo/_Foo/Foo_Impl_
        at haxe.root.Main.main(Unknown Source)
        at haxe.root.Main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: _foo._Foo.Foo_Impl_
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more
```

**Comment by Simn** [comment]
That doesn't reproduce for me.

Also, is this specific to `-java` or does it also affect `-jvm`?

**Comment by skial** [comment]
Just the `--java` target with Haxe `7dc565e`.

I'll look into it a bit more later to see if I can find any more info.

**Comment by Simn** [comment]
Moving forward we'll not look into fixing `-java`-specific issues and instead focus on the JVM target, so I'll close this as unresolved.

**Comment by skial** [comment]
Ok 👍 I wont look any further into it, its easy to get around.

**Comment by nanjizal** [comment]
Is there any example of setting up GL window for JVM or using Swing/JavaFX, just seems like JVM would get more testing if there was some starter example somewhere, ideally something showing getting a triangle on screen and maybe mouse/keyboard input?  At moment it does not seem an ideal swap - graphics for speed!  :)

**Comment by nadako** [comment]
@nanjizal I have this libgdx repo, recently adapted to Haxe 4.2 JVM: https://github.com/nadako/libgdx-haxe-example

**Comment by nanjizal** [comment]
is it running on mac?
