### ISSUE TITLE
provide more helpful error message for `final var`

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9676]
Subj. This mistake is quite common so the error could hint that one should write `final x` instead of `final var x`. This should be the same for module and class level fields and local vars.

**Comment by nadako** [comment]
Interesting, looks like `final var x` actually parses on the expression level and behaves as `var x` O_O

**Comment by Simn** [comment]
`final var x` no longer parses at expression-level, and  I agree we should have a better error message for `final var` in particular.

**Comment by RblSb** [comment]
For locals in display mode error is still not that great (`Unknown identifier : x` (before compilation)), but maybe you want to solve it in https://github.com/HaxeFoundation/haxe/issues/9923

**Comment by Simn** [comment]
Meh, yeah, it would be better to use `syntax_error` here...
