### ISSUE TITLE
priority of a forwarded static extension

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9680]
Example:
```haxe
@:using(Main.FooTools) 
class Foo {
  public function new() {}
}

@:using(Main.BarTools) 
@:forward 
abstract Bar(Foo) from Foo {}

class FooTools {
  public static function ext(that: Foo)
    trace('Foo');
}

class BarTools {
  public static function ext(that: Bar)
    trace('Bar');
}

class Main {
  public static function main() {
    var bar: Bar = new Foo();
    bar.ext(); // traces Foo, not Bar
  }
}
```

Right now resolution order for a field of abstract with forwarding is:
- a field of abstract
- a field of forwarded
- an extension for forwarded
- an extension for abstract

Shouldn't last two be other way around?

**Comment by RealyUniqueName** [comment]
I agree, they should.

**Comment by vonagam** [comment]
By the way, this will fix [an example in last comment of #5924](https://github.com/HaxeFoundation/haxe/issues/5924#issuecomment-470029199).

**Comment by Simn** [comment]
The original intent of `@:forward` was to allow forwarding field access to fields that actually exist on the underlying type. The interaction with static extensions seems pretty unfortunate, but at this point I don't think we should break it.

The behavior described here is an implementation detail which comes from the call stack. Given an abstract `A` over `U` with an unconditional `@:forward`, we start out like this:

```
actual field on A
recurse into U because of @:forward
static extension on A
... something about `this` and the underlying type that I don't understand right now (on A)
@:resolve on A
```

Expanding the recursion we then get this:

```
actual field on A
actual field on U
static extension on U
... something about `this` and the underlying type that I don't understand right now (on U)
@:resolve on U
static extension on A
... something about `this` and the underlying type that I don't understand right now (on A)
@:resolve on A
```

The question now is what we want instead. I think this actually goes beyond the static extension and both the mysterious `this` thing and `@:resolve` should be affected as well.

If we agree that static extensions on the abstract should take priority, then the only logical answer is to have this order:

```
actual field on A
actual field on U
static extension on A
static extension on U
... something about `this` and the underlying type that I don't understand right now (on A)
... something about `this` and the underlying type that I don't understand right now (on U)
@:resolve on A
@:resolve on U
```

Before we continue, we'll have to agree if this is indeed what we want. I don't have much intuition for this and merely go by the pattern here.

**Comment by Simn** [comment]
The weird `this` thing was originally added here:

https://github.com/Simn/haxe/commit/17ee33c8fb0b86be13811249c7f4b0ce87dc60a5

And then modified here:

https://github.com/Simn/haxe/commit/57784e997492077521a2f7688c53fb749d323ee1

I still don't get what this is doing because `this` should already be typed as the underlying type anyway.

**Comment by RealyUniqueName** [comment]
Now that there's no mysterious "this" thing involved the resolution order would look like this:
```
actual field on A
actual field on U
static extension on A
static extension on U
@:resolve on A
@:resolve on U
```
which makes sense to me.

**Comment by Simn** [comment]
That makes sense to me too, but it's not quite what #9682 implements, I think.

**Comment by vonagam** [comment]
Yes, #9682 didn't take into account existence of `@:resolve`.

So, to implement it, maybe we can go with some additional field in `TypeFieldConfig` that will contain a list of abstract wrappers above?

**Comment by vonagam** [comment]
With new priority for `@:using` the list should be updated like so (module includes global here):
```
actual field on A
actual field on U
type static extension on A
type static extension on U
module static extension on A
module static extension on U
@:resolve on A
@:resolve on U
```

Because if you simply wrap a type with a transparent (with forward and direct casts, optionally transitive) abstract, it shouldn't give `module static extension on U` more priority than `type static extension on U`. But it will if they are not split as above. If extensions are checked together it will be like so:
```
type static extension on A
module static extension on A (if A is transparent, then it is the same as "module static extension on U")
type static extension on U
module static extension on U
```
