### ISSUE TITLE
field cast function can beat direct cast for an abstract

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9688]
Example:
```haxe
typedef Foo = {x: Int, ?y: Int};

@:forward abstract Bar(Foo) from Foo {
  @:from public static inline function fromX(value: {x: Int}): Bar
    return {x: 1, y: 0};
}

class Main {
  public static function main() {
    var bar: Bar = {x: 0};
    trace(bar.x); // traces 1
  }
}
```

When `@:from` is removed, then zero is traced as expected. Seems like `{x: 0}` is not identified as valid `Foo` with the field cast function present.

Also if such `@:from` is added before `fromX` then it beats `fromX`, printing two:
```haxe
@:from public static inline function fromFoo(value: Foo): Bar
  return {x: 2, y: 0};
```

**Comment by vonagam** [comment]
Ok, this is how it works right now:

- First direct implicit casts are [checked](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/core/abstract.ml#L48) by [strict type equality](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/core/abstract.ml#L16) (not a unification) check.

- If no directs matched, then field implicit casts are [checked](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/core/abstract.ml#L51), this time with [a unification](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/core/abstract.ml#L24) check.

- If no fields matched, then direct implicit casts are [checked](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/core/tUnification.ml#L832) again as part of [full unification check](https://github.com/HaxeFoundation/haxe/blob/526bd66a61b9f93af55643132cc4e7424b78308d/src/context/abstractCast.ml#L101).

The fix is to use a unification check in first step for directs, not an equality check.

**Comment by kevinresol** [comment]
Does this help https://github.com/HaxeFoundation/haxe/issues/6961 ?
