### ISSUE TITLE
is operator compiles with variable on RHS if capitalized

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9692]
This probably shouldn't compile? :/

```haxe
function main() {
	var foo = "";
	trace("" is foo); // unexpected )

	var Foo = "";
	trace("" is Foo); // compiles and traces false
}
```

**Comment by nadako** [comment]
Well, `("" is Foo)` and `Std.isOfType("", Foo)` compiles fine as well, so I guess it's all about how we proceed with the `is` operator now. Related PR: #9689

**Comment by nadako** [comment]
For now, we could "fix" this specific case within #9689 by forcing second argument to be a `TTypeExpr` after typing.

**Comment by Gama11** [comment]
The problem is that I thought that the `is` operator provides a bit more "safety" here, but it looks like it was just a conincidence that it mostly doesn't work with variables because the parser doesn't allow lowercase identifiers here*. If you have some PascalCase'd enum abstract values, this can easily happen by accident.

*`unexpected )` isn't the best error message here either, maybe this should fail during typing too?

**Comment by nadako** [comment]
> *`unexpected )` isn't the best error message here either, maybe this should fail during typing too?

That's a general complextype/typepath parsing issue, we can probably improve something there and it would benefit other cases too (e.g. cast, typecheck, etc.).

**Comment by nadako** [comment]
Actually this is an interesting question... Maybe we actually want to parse RHS as an actual expression, not complex type? Argh this thing needs some discussion and design.
