### ISSUE TITLE
Purity inference regression

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9699]
```haxe
class EventDispatcher {
	public function dispatchEvent(event:Event) {}
}

class Event {
	public function new() {
		Math.NaN;
	}
}

var dispatcher:EventDispatcher;

function main() {
	var event = new Event();
	dispatcher.dispatchEvent(event);
}
```

generates:
```js
function Main_main() {
	var event = new Event();
	Main_dispatcher.dispatchEvent(event);
}
```

however if we comment out `Math.NaN` in `Event.new`, the `event` var will be fused into the call:

```js
function Main_main() {
	Main_dispatcher.dispatchEvent(new Event());
}
```

Happens in current development, but doesn't happen in 3ce45be. I assume it's related to to 1f9bf476ddf13e8d5bdbea12512faa51dac2327a, because it talks about (not) inlining `@:pure`, but something seems wrong there, because `Math.NaN` is defined explicitly `@:pure` on JS like this:

```haxe
static var NaN(get, null):Float;
@:pure private static inline function get_NaN():Float {
	return code("NaN");
}
```

**Comment by RealyUniqueName** [comment]
Uh... I totally forgot `@:pure` may have no arguments...
