### ISSUE TITLE
sqlite is stuck in transaction mode after performing one transaction

### ISSUE THREAD

**Issue by ProPuke** [HaxeFoundation/haxe#9700]
If you begin a transaction with sqlite and then end it with `commit` or `rollback` you will be placed into _another_ transaction instead of just ending the current and being back in autocommit mode.

The [source](https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/_std/sys/db/Sqlite.hx#L86) reads as follows:
```haxe
public function commit() {
	request("COMMIT");
	startTransaction(); // match mysql usage
}

public function rollback() {
	request("ROLLBACK");
	startTransaction(); // match mysql usage
}
```

I'm not sure what the meaning of "match mysql usage" is here;
Mysql doesn't put you back into another transaction after you end one

The `startTransaction()` lines seem like bugs
Do we know why they are there?

You don't want to always be in a transaction with sqlite. This breaks auto-commit once you've performed one transaction and means further changes aren't written to disk unless you perform another transaction after.
(While with mysql they are, as it does not have this behaviour)

**Comment by RealyUniqueName** [comment]
I guess it's just a copy-past from the neko implementation. It also got into hl implementation like that.
https://github.com/HaxeFoundation/haxe/blob/48c31bdfb9a141c3264dc2899db8f555b40cf460/std/neko/_std/sys/db/Sqlite.hx#L76-L79
We need tests...

**Comment by RealyUniqueName** [comment]
This is fixed in development branch now. 
While I think old behavior is a nonsense, I don't think it's a subject for a hotfix release because it changes an over a decade old behavior some projects most likely rely on.
