### ISSUE TITLE
Error range for invalid type names shouldn't include type parameters

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9705]
```haxe
typedef Foo = Arrey<{
	/**
	 * test
	 */
	var test:Int;
}>;
```

If the outer type is misspelled, the entire range is colored red, which can be confusing / make it hard to spot the source of the problem:

![image](https://user-images.githubusercontent.com/2620907/87189428-ea799e80-c2f0-11ea-8187-d0b54efd0472.png)

**Comment by Simn** [comment]
Fixed by #11405.
