### ISSUE TITLE
[php] new HxAnon objects cannot be serialized by php

### ISSUE THREAD

**Issue by mockey** [HaxeFoundation/haxe#9715]
The new way of creating anonymous objects in PHP (see #7916) creates "anonymous classes" which apparently cannot be serialized by the PHP serializer. This is done e.g. when storing objects to memcached. You get the error:
`Serialization of 'class@anonymous' is not allowed`
Is there a workaround for this?

**Comment by RealyUniqueName** [comment]
I don't think it's possible to workaround this.
I guess I'll have to revert `HxAnon` optimization.

**Comment by mockey** [comment]
There is a magic `__serialize` method (in 7.4 apparently).
https://www.php.net/manual/en/language.oop5.magic.php#object.serialize

Also there's a `Serializable` interface:
https://www.php.net/manual/en/class.serializable.php

**Comment by RealyUniqueName** [comment]
Both don't work for anonymous classes.

**Comment by mockey** [comment]
Yes, I was hoping that you can customize serialization with these, but apparently not :disappointed:
That's about as stupid as you might expect from PHP ...

**Comment by mockey** [comment]
I have the special case here that I use the memcache module and storing uses automatic PHP serialization. So if the performance of anonymous classes is really 50% better, it might be worthwhile to introduce a compiler flag?
For the time being I use haxe serialization before storing to and after reading from memcached. Not nice, but works.

**Comment by RealyUniqueName** [comment]
You can see the difference for an anon-heavy app here: https://benchs.haxe.org/mandelbrot_anon_objects/index.html#13;false;true;true;DataAndAverage;SMA;2020-05-30;2020-07-15;PHP;runtime;

**Comment by mockey** [comment]
`__serialize` actually sort of works when added to HxAnon. But it writes the classname as `class@anonymous/path/to/file:something` and the `@` causes an exception in `unserialize` and apparently that can't be changed. How stupid is that?

**Comment by RealyUniqueName** [comment]
Now anon structure declarations generate real classes.
For example
```haxe
var o = { hello: 'world' }
```
generates
```php
$o = new _HxAnon_Main0("world");
//and at the bottom of php file:
class _HxAnon_Main0 extends HxAnon {
  public function __construct($hello) {
    $this->hello = $hello;
  }
}
```
Now anon structs are serializable. And their creation became even slightly faster.

**Comment by RblSb** [comment]
I have ` Uncaught Error: Class '_HxAnon_Api5' not found in Api.php`, because structures generated at the end of file:
```
Boot::registerClass(Api::class, 'Api');
Boot::registerMeta(Api::class, new _HxAnon_Api5(<...>));
Api::__hx__init();

class _HxAnon_Api5 extends HxAnon {
	function __construct($obj) {
		$this->obj = $obj;
	}
}
```
Works if i move class at the top of file. Upd: #10041
