### ISSUE TITLE
analyzer-optimize removing variables used by cpp.Pointer

### ISSUE THREAD

**Issue by Aidan63** [HaxeFoundation/haxe#9732]
Hello,

I recently ran into some trouble with hxcpp externs and pointers when compiling with `analyzer-optimize`, digging into the generated cpp it seems the local variables are being too eagerly optimised away.

The below snippet will fail to compile at the cpp stage with haxe 4.1.2 and hxcpp 4.1.15 with `-D analyzer-optimize`, and compiles fine without.
```haxe
class Main {
	static function main() {
		final val = 7;
		final ptr = Pointer.addressOf(val);
	}
}
```
MSVC gives the following error.
```
./src/Main.cpp(34): error C2664: 'cpp::Pointer<int> cpp::Pointer_obj::addressOf<int>(T &)': cannot convert argument 1 from 'int' to 'T &'
        with
        [
            T=int
        ]
```
Looking at the generated cpp code its easy to see whats gone on.
```cpp
void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_7_main)
HXDLIN(   7)		::cpp::Pointer_obj::addressOf(7);
            	}
```
I was able to work around this by copy and pasting the cpp.Pointer type and changing addressOf and others to use `haxe.extern.AsVar` (which cpp.Pointer already imports but never uses?). Not sure if there are any side effects to this, but it seems to have worked for me.

Looking through the issues I found #9543 and it looks like they might be related? So sorry if this is a duplicate.

Cheers.

**Comment by RealyUniqueName** [comment]
Yes, it's a duplicate.
