### ISSUE TITLE
Wacky type parameter handling in type_field with abstract constraint

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#9760]
From old issue #2343:

```haxe
abstract MyInt(Int) from Int {
	public function work() {
		trace("MyInt.work()");
	}
}

abstract NotMyInt(Int) to MyInt {
	public function new() {
		this = 0;
	}

	public function work() {
		trace("NotMyInt.work()");
	}
}

class Foo<T:MyInt> {
	public var result:Int;

	public function new(val:T) {
		val.work();
	}
}

function main() {
	new Foo<NotMyInt>(new NotMyInt());
}
```

For some reason I thought this was fine 7 years ago, but it's clearly not. The `Foo` constructor is generated to explicitly call `MyInt.work(val)`, even though our concrete type is `NotMyInt`.

I think this entire part of `type_field` can just be removed. That's probably something you'll come across @vonagam.

**Comment by vonagam** [comment]
As i understand from this example `T` inside `Foo` will be used as `MyInt`, but for outside you can pick what you want `T` to be as long as it is unifiable with `MyInt`. With this example:

```haxe
class Foo<T:MyInt> {
	public var result:T; // inside result will be as MyInt

	public function new(val:T) {
                result = val;
		result.work();
	}
}

function main() {
	var foo = new Foo<NotMyInt>(new NotMyInt());
        foo.result.work(); // outside result will be whatever you want, NotMyInt in this case
}
```

An author of the type chose his utility wrapper for `Int` to work inside, but allowed a user of type to pick his own wrapper (or not wrapper at all) that he will work with.

Don't know how useful it is, but there is some value in it. You still want to remove it?

**Comment by RealyUniqueName** [comment]
I don't get why it's wrong.
You actually pass an "instance" of `MyInt` into `new Foo`. It's just casted from `NotMyInt` "instance", isn't it?

**Comment by RealyUniqueName** [comment]
Nvm, now I see.

**Comment by RealyUniqueName** [comment]
But following this logic, we can't allow `Int` as type param for `<T:Float>`

**Comment by Simn** [comment]
This isn't about unification, it's about structural access. The code looks like there would be some dynamic dispatch going on which ends up calling `NotMyInt.work()`, but dynamic dispatch does not exist for abstracts.

If you're the author of `Foo` and you truly want to call `MyInt.work()`, you can always just do `(val : MyInt).work()`. That then clearly communicates that you indeed want to call this particular function, and the cast is sound because of `T:MyInt`.

**Comment by vonagam** [comment]
But as an author of the type with `<T:MyInt>` what else do you expect to call with `T.work()`? I mean in editor it will be typed as `MyInt.work` there should be no surprise with that. No? (`NotMyInt` can have completely different signature for `work`, so you can't expect to call arbitrary static extension / abstract implementation that you don't know, as fields unifiability is not requirement for abstract unification.)

**Comment by vonagam** [comment]
Also right now there is some inconsistency regarding this. If you have `<T:MyInt>` then first static extensions are checked that unify with `MyInt` and only after that `MyInt` itself when you search `work` on `T`, that's should be other way around.

**Comment by Simn** [comment]
As the author of `Foo` you might expect it to call the method on the concrete type if you're not very familiar with how abstracts work.

And from the outside, it's even clearer that this is confusing:

```
new Foo<NotMyInt>
T = NotMyInt
val : T becomes val : NotMyInt
(val : NotMyInt).work() calls MyInt.work() // what?
```

**Comment by vonagam** [comment]
`val : T` stays the same, replacing like this is just simplified explanation of how constraints work.

> if you're not very familiar with how abstracts work

Well, that's the question here, to keep this in place to allow more experienced people to use this for their possible needs or to remove because it can cause confusion for novice users.

And actually removing this can cause more inconsistency/discomfort. For example, if we remove this should `T` inside `Foo` still be allowed to use module static extension for `MyInt`, i assume not, right?

**Comment by vonagam** [comment]
Well, i guess that that they will still be allowed as in you explanation `NotMyInt` as `T` is still unifiable with `MyInt` in possible extension. But the question then imagine that you have `MyIntTools` and `NotMyIntTools`, if you follow simple replacing logic then once you use `NotMyInt` then `NotMyIntTools` (preferably) should be matched instead of `MyIntTools`, but it will not happen.

It is the same with `<T:Parent>` and `ParentTools`/`ChildTools`, just because you put `Child` as `T` will not make `T` work with `ChildTools` inside your class, so this is not only about abstracts.

**Comment by Simn** [comment]
> It is the same with <T:Parent> and ParentTools/ChildTools, just because you put Child as T will not make T work with ChildTools inside your class, so this is not only about abstracts.

Yes, but in the case of static extensions it's already clear that we're dealing with static/compile-time dispatch. My problem here is that it _looks_ like dynamic dispatch, but is actually static dispatch. IMO this introduces a special case for no good reason.

Having said that, I have to acknowledge that this has been around for a long time and removing it at this point seems questionable. I stand by my opinion that this is wacky, but at the same time it's not really worth breaking is at this point. So I'll withdraw my complaint for the time being, let's keep this thing around.
