### ISSUE TITLE
neko Exception not catched

### ISSUE THREAD

**Issue by AdrianV** [HaxeFoundation/haxe#9780]
In the following neko code the exception thrown from DateTime.format is not catched

```haxe
class Main {
	static function main() {
		try {
			trace(DateTools.format(Date.now(), "%d.%m.%y %T"));
		} catch (e: Dynamic) {
			trace(e); // This line is never reached
		}
		trace("Hello, world!"); // This line is never reached
	}
}
```

**Comment by AdrianV** [comment]
Oops - it depends on the neko version. Must have an older neko on my machine. It works on another machine as expected

**Comment by RealyUniqueName** [comment]
Is it catchable on that older version with Haxe 4.0 or Haxe 3.4.7?

**Comment by AdrianV** [comment]
I will try

**Comment by AdrianV** [comment]
no I have the same problem with haxe 4 and haxe 3.4. 
Maybe its a problem of neko 32bit and jit, vs neko 64bit. On my linux with neko 64bit it works. On my windows I have neko in 32bit - but self compiled. 
I will check again.

**Comment by RealyUniqueName** [comment]
Related Neko change, which is probably the reason why older Neko crash: https://github.com/HaxeFoundation/neko/pull/195

**Comment by AdrianV** [comment]
I checked with 32 bit and 64 bit on windows. Both work. It is my self compiled neko version. Sorry for the noice.

**Comment by AdrianV** [comment]
It seems to be a neko problem on windows. I opened an issue there https://github.com/HaxeFoundation/neko/issues/211
