### ISSUE TITLE
overload modifier doesn't parse at module-level

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#9791]
```haxe
function main() {
	name();
	name(0);
}

overload function name() {
	trace("Hello");
}

overload function name(i:Int) {
	trace("Hello " + i);
}
```

```
source/Main.hx:6: characters 1-9 : Unexpected overload
```

(JVM target)

**Comment by Simn** [comment]
I've made it parse, but it doesn't work yet because there's a nominal duplication check for module statics.

@nadako Can we just remove that? I imagine duplicates would be picked up by the standard class field mechanisms.

**Comment by nadako** [comment]
Well it's supposed to also check name duplicates with type declarations. And I assume the error message would be less clear?

**Comment by Simn** [comment]
Right, so we have to check conflicts between fields and types, but defer conflicts between fields and fields to the class field handler.
