### ISSUE TITLE
@:native for extern enum entries

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#9806]
I think it is currently not supported

Suppose on java side there is a `enum Direction { LEFT; }`
and in haxe `extern enum Direction {LEFT;}` works
but `extern enum Direction {@:native('LEFT') Left;}` doesn't
and jvm gives runtime error `java.lang.NoSuchFieldError: Left`

**Comment by RealyUniqueName** [comment]
I think `@:native` is not implemented for enum constructors at all. Not only for jvm.
