### ISSUE TITLE
Callbacks supposedly returning Void occasionally get mistyped

### ISSUE THREAD

**Issue by grepsuzette** [HaxeFoundation/haxe#9813]
Following compiled fine with version `4.0.5`, 
and doesn't anymore with version `4.1.2` (Edit: also doesn't work with `4.1.3`):

```haxe
class Main {
    static var my : Int;
    var cb : Int->Void;

    function assignCb() {
        cb = n -> switch n {       // Error : Int should be Void
            case 1: my = 3; 
            case _: my = 12345678;
        };  
    }   
    static function main() {}
}   
```
It gives `Int should be Void`.

Yet this variant works:
```haxe
    function assignCb() {
        cb = n -> my = switch n {    // compiles
            case 1: 3; 
            case _: 12345678;
        };  
    }   
```

If the callback is supposed to return `Void`, should not both versions actually compile and understand the assignment is not the value to be returned?

**Comment by Simn** [comment]
@RealyUniqueName I'm having some trouble following our implicit return typing logic, so I'm assigning to you. Note that this works when using `function(n) return` instead of `n ->`, which is supposed to be equivalent.

**Comment by RealyUniqueName** [comment]
Regression was introduced in 93cd4bb90eeb8107bfacdc27ce4dac383016c12b
