### ISSUE TITLE
different TypedExpr result for eval vs js

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9815]
```haxe
class Main {
    public static function main() test();
    public static macro function test() {
        switch haxe.macro.Context.typeExpr(macro(Bar():Foo)) {
            case { expr: TParenthesis({ expr: TCast({ expr: TCall(e, el) }, _) }) }:
                trace(el);
            case _:
        }
        return macro { };
    }
}
enum Foo {
    Bar(?key:String);
}
```
For `--interp` this properly inserts `null` expr into the call arguments. For JS, the `el` array is empty. I didn't test other targets.

I use this to generate enum values from untyped expressions, but using `Type.createEnum` fails with `Invalid_argument("index out of bounds")` if the argument count isn't correct (i.e. empty instead of explicit null being passed in).

I suppose for JS this isn't really incorrect behavior, as the generated code for simply doing `Bar()` wouldn't insert null either. So maybe it's an issue with `Type.createEnum`?

**Comment by Simn** [comment]
That is the expected behavior. Some targets require null padding while others don't.

**Comment by Antriel** [comment]
Alright, thanks for confirming. I can probably inspect the enum type and insert null manually for `Type.createEnum`.
