### ISSUE TITLE
[display] wrong return type of overloaded function is shown

### ISSUE THREAD

**Issue by vonagam** [HaxeFoundation/haxe#9824]
```haxe
extern class Foo {
  static overload function foo(a: Int): Int;
  static overload function foo(a: Int, b: Int): String;
}

class Main {
  public static function main() {
    var x = Foo.foo(1,2);
  }
}
```
`x` is shown to be `Int` on hover, but compiles properly to `String`.

Also would be helpful if on hover of `.foo` a relevant overloaded signature were shown and not of the first defined.

**Comment by Simn** [comment]
This example also highlights a related problem if we modify it a little:

![Code_yc604cQnVo](https://user-images.githubusercontent.com/634365/99243792-73559900-2801-11eb-9071-75c37380b389.png)

We resolve the display result too eagerly, which ends up choosing the wrong overload.

The general problem here is that display handling is very lenient when it comes to typing errors, but being lenient is not very compatible with handling overloads.
