### ISSUE TITLE
Regression: storeTypedExpr of enum constructs seems broken.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9828]
Tested with 7a0b575

```haxe
import haxe.macro.Context.*;

class Main {
  #if !macro
  static function main() {
    trace(foo());
  }
  #end
  static macro function foo() {
    var t = typeExpr(macro {
      var x:haxe.ds.Option<String> = null;
      switch x {
        case Some(v): v;
        case None: '';
      }
    });
    return storeTypedExpr(t);// Uncaught exception Invalid expression
  }
}
```

I'm reasonably sure the error is raised here: https://github.com/HaxeFoundation/haxe/commit/bfe90107b37642499fddc69d38e6d3d0bf56ea69#diff-095f0d8bb566bc8865a1ab9df0392db4R1342

Is it possible that the `e_constrs` is not populated yet or something?

**Comment by Simn** [comment]
It's not that one, it's the other one because the `type` of a constructor with arguments is `TFun`.

**Comment by RealyUniqueName** [comment]
If `e_constrs` is not populated yet the field can't be found by `typeExpr`
