### ISSUE TITLE
typdef compilation to C#

### ISSUE THREAD

**Issue by sbialkowski-pixel** [HaxeFoundation/haxe#9842]
Hello, 

I have a question. I have 

`typedef Point = Array<Float>;`

which is implemented in https://github.com/pboyer/verb

And I try to compile to c#, but all _Points_ are changed to _object_.
How can i fix it?

I can change it to for example.:
`@:expose("core.Point")
class Point extends SerializableBase {

    public var x: float;
    public var y: float;

    public function new(x, y){
        this.x= x;
        this.y= y;
    }
}
`
But then all places where simple array of floats is used (almost 800 places in whole lib) will be incompatible.

Any help?

**Comment by Simn** [comment]
Please refer to https://community.haxe.org/ for questions like this.
