### ISSUE TITLE
Requesting build fields during field meta completion with only "@" hangs the compiler server.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9853]
Example: 

```haxe
#if !macro
  @:build(Main.build())
#end
class Main {
  #if !macro
  static var dummy = 123;
  static function main() {
  }
  #else
  static function build() {
    trace(Date.now());
    haxe.macro.Context.getBuildFields();
    return null;
  }
  #end
}
```

From there, I observe the following behavior:

![hang](https://user-images.githubusercontent.com/509501/90757578-1881d380-e2de-11ea-94c9-754b7e35985b.gif)

As soon as the `@` before `dummy` is entered on its own line, the server is gone (without the `trace` making it to the output). Without `haxe.macro.Context.getBuildFields();` I get metadata completion just fine.

**Comment by Simn** [comment]
This looks really crazy... I like it.
