### ISSUE TITLE
Oddity with `analyzer-optimize` flag and C# output

### ISSUE THREAD

**Issue by aartzrc** [HaxeFoundation/haxe#9871]
This might be an analyzer issue, but I've only had a problem with the C# output so far so I figured I would drop the issue here.

A quick example:  
```haxe
class NullIntTest {
    static function main() {
        var outArray:Array<String> = [];
        for(i in "1,2,3".split(",").map((s) -> Std.parseInt(s)).filter((i) -> i != null)) outArray[i] = "some object";
    }
}
```

If compiled without `-D analyzer-optimize` flag the assignment to `outArray` looks like this:
```cs
global::haxe.lang.Null<int> i2 = global::haxe.lang.Null<object>.ofDynamic<int>(intVals[_g4]);
outArray[(i2).@value] = "some object";
```
When `-D analyzer-optimize` is used the code gets shorter (yay!) but the compile fails, the output looks like:
```cs
outArray[global::haxe.lang.Null<object>.ofDynamic<int>(ret1[_g4++])] = "some object";
```
If it is adjusted like this it works:
```cs
outArray[global::haxe.lang.Null<object>.ofDynamic<int>(ret1[_g4++]).@value] = "some object";
```
Essentially the nullable type causes trouble during the optimization and the `@value` is lost somehow.  
Not a major problem and possibly someone already has a handle on this, but it was annoying enough I wanted to bring it up.  
As always thanks so much for maintaining the Haxe C# target, it is an essential part of my work!

**Comment by RealyUniqueName** [comment]
This looks like an issue in C# generator. It probably fails to detect this case when deciding on `.@value` generation on `Null<>`
