### ISSUE TITLE
[js] Javascript generator support

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#9873]
I would like to leverage JavaScript's [generator support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) from inside Haxe. Is this currently possible? How intensive would it be to implement such support?

**Comment by NQNStudios** [comment]
If not by generating `function*` declarations, it looks like Haxe's `js` module could provide access to this constructor: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction

This wouldn't be the ideal because the code of the generator body must be supplied as a string in that case.

**Comment by RealyUniqueName** [comment]
I doubt we can easily implement support for semantics of JS generators.
But we should support target native capabilities somehow...

**Comment by NQNStudios** [comment]
I'm thinking if there were a way for a macro to compile a Haxe expression object into javascript, then wrap it in the `function*` declaration, and insert that js directly into the output, that would at least be good enough for a workaround.

So, with a macro call like this:

```
js.GeneratorFunction([count: Int, text: String], {
    for (i in 0...count) {
        yield '$text $count';
    }
});
```

The macro would (hypothetically) do like this:

```
var body = compileHaxeToJs(bodyExpression); // would need to ignore undeclared variables count and text, and leave the yield statements alone although they aren't valid haxe

var argList = compileHaxeToJs(haxeArgList);

outputJs.append('function* $argList $body');
```

I have no idea if any such macro capabilities exist, though. This is just me trying to think of how I could hack support into my own library in the short term.

**Comment by Simn** [comment]
This would have to go through https://github.com/haxefoundation/haxe-evolution because it clearly requires someone to think this through properly.
