### ISSUE TITLE
abstract over IMap unification

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9874]
This might similar to some other issues, but maybe we should define which of these are supposed to work, because the behavior keeps changing (regression?). Tested on https://github.com/HaxeFoundation/haxe/commit/4259869e11a167faedb091b58e72cf0675836e3d, https://github.com/HaxeFoundation/haxe/commit/e344635380a2645e3801542a1c7ef86d0f06da54 and 4.1.3.
It would be nice if all of them could work, but I would hope for at least `m2` variant to work.
```haxe
import haxe.Constraints.IMap;
class Main {
    static function main() {
        var m:ArrayMap<String, String> = new Map(); // Errors on 4.1.3/4259869. Works on e344635.
        var m2:ArrayMap<String, String> = new Map<String, Array<String>>(); // Errors on 4259869. Works on 4.1.3/e344635.
        var m3:ArrayMap<String, String> = new haxe.ds.StringMap<Array<String>>(); // Works on 4.1.3/e344635/4259869.
    }
}
@:forward abstract ArrayMap<K, V>(IMap<K, Array<V>>) from IMap<K, Array<V>> to IMap<K, Array<V>> { }
```

**Comment by RealyUniqueName** [comment]
So, everything was working on e344635.
Broken since 75cbcc6a9e04d1327ed125c6b7a1e11ac041d4ca

**Comment by Antriel** [comment]
Hmm, alright, adding `@:transitive` to the abstract fixes it on https://github.com/HaxeFoundation/haxe/commit/4259869e11a167faedb091b58e72cf0675836e3d (all three variants work).
If that's desired behavior I guess we can close this. Is it considered transitive because `Map` (and whatever actual type it ends up being) has to be typed into `IMap` first? I'm not sure I fully understand what "transitive cast" is meant be.

**Comment by RealyUniqueName** [comment]
Ah, yes. I forgot about new `@:transitive` meta.
Yes, it's supposed to work like that now.
I think the meta should be added to `haxe.ds.Map` abstract.

**Comment by Antriel** [comment]
Adding it either there, or to the `ArrayMap` abstract works. So probably makes sense to add it to `haxe.ds.Map`.

**Comment by RealyUniqueName** [comment]
This line
```haxe
var m:ArrayMap<Int, Float> = new Map(); 
```
currently generates 
```haxe
var m:ArrayMap<Int,Float> = new haxe.ds.StringMap<Float>();
```
which is obviously wrong and errors out on all Haxe versions except development branch. So I'm going to comment out that line from the test
