### ISSUE TITLE
Confused by the C++ threading documentation

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/haxe#9876]
I started compiling my codebase which uses the Haxe 4 threading API to the C++ target. Then I stumbled onto [this page](https://haxe.org/manual/target-cpp-ThreadsAndStacks.html) in the manual and now I'm wondering if I need to add `cpp.vm.Gc.enterGCFreeZone()` calls before making blocking calls to my own functions. I don't really get what this looks like, or if it's only necessary for calls to system things that Haxe doesn't control. Some examples, or more explanation on this, would be nice.

**Comment by RealyUniqueName** [comment]
@hughsando ?

**Comment by hughsando** [comment]
The enter/exit blocking is usually best done from the native code, either side of code that is known not to allocate or throw. The cpp.vm version is not as useful. There are plenty of examples in the hxcpp runtime in the "libs" directory, eg https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/libs/std/File.cpp

If your code is going to call back into the hxcpp code, then things get a little more complicated.

**Comment by RealyUniqueName** [comment]
Nothing to do here.
