### ISSUE TITLE
Method closure sameness.

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/haxe#9878]
On most platforms we have `o.method == o.method` (except HL, right?) and on JavaScript this is accomplished via `$bind`. The main use case for this was EventDispatch/EventTarget/EventEmitter, where the handler is in fact used as a key. In many other cases it's not very good for performance. I was playing with topping some silly JS performance benchmark and I was able to drop memory usage ~25% rewriting a few method closures to anonymous functions (that capture `this`), which in turn caused a massive drop in minor GC runs (almost an order of magnitude). I'm also a little worried that it changes object shape, although I couldn't find that having much of an impact.

I'm worried about a potential `#if`-fest, because on other platforms the method closure might perform better (haven't found one yet, although I suspect for flash this might be the case - which is pretty irrelevant). 

I would like to have some type of `@:callable abstract NonUnique<T:Function>(T) from T {}`, so that I can use this in public APIs to give users the performance benefit, where possible. In the long run, I would propose the idea to flip the behavior (closure sameness being an opt-in via the callees signature), because using functions as keys is something that comes from a handful of libraries/externs and can be solved there.

**Comment by RealyUniqueName** [comment]
I doubt we will ever flip the behavior. 
But having such an option (via special abstract or somehow else) is a good idea.

**Comment by back2dos** [comment]
Well, in the end it's probably best to leave it as is, as changing it could silently introduce a lot of bugs. People will just have to optimize it where it actually matters.
