### ISSUE TITLE
Parser bug with comments in #if

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe#9894]
Works:
```haxe
#if (debug)
#end 
```

Doesn't work but seems like it should:
```haxe
#if (/* Hello */ debug)
#end 
```

Thanks!

**Comment by Simn** [comment]
This might be a bit tricky to fix because the parser operates in "raw" mode for these conditionals, which means that no token preprocessing takes place. Supporting this would require some kind of "almost raw" mode where it still discards comments.

**Comment by Simn** [comment]
Oh actually, we can do this at lexer level where we already discard whitespaces.
