### ISSUE TITLE
[jvm]:: strange behaviour with a conditional 

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/haxe#9897]
Playing with the jvm target and hit this kinda bizarre issue:

```haxe
package;

class Main {
    private static var f1:Null<Float>;
    private static var f2:Null<Float>;
    
	static function main() {
        f1 = 100;
        test(f1);
	}
    
    static function test(f:Null<Float>) {
        trace(f);
        trace(f2);
        trace(f != null);
        trace(f != f2);
        if (f != null && f2 != f) {
            trace("setting");
            f2 = f;
        } else {
            trace("eh?");
        }
    }
}
```

The output of which is:

```
src/Main.hx:13: 100
src/Main.hx:14: null
src/Main.hx:15: true
src/Main.hx:16: true
src/Main.hx:21: eh?
```

Ive tried the same code on other targets and it correctly traces "setting" (as it should).

`Haxe Compiler 4.2.0-rc.1+e34463538`

Cheers,
Ian

**Comment by ianharrigan** [comment]
Actually, this can be reduced even further:

```haxe
var f1:Null<Float> = 100;
var f2:Null<Float> = null;
trace(f1 != f2); // true
trace(f2 != f1); // false!?!?!
```

so the issue is "null != 100" (however that is represented in the generated bytecode ofc) 

Cheers,
Ian

**Comment by CanIGetaPR** [comment]
Decompiling the jar yielded the following java source code:

```java
public static void main() {
        Double f1 = (double)100L;
        Double f2 = (Double)null;
        Log.trace.invoke(f1 == null ? f2 == null : (f2 == null ? true : Jvm.toDouble(f1) != Jvm.toDouble(f2)), new Anon0("Main", "src/Main.hx", 13, "main"));
        Log.trace.invoke(f2 == null ? f1 == null : (f1 == null ? true : Jvm.toDouble(f2) != Jvm.toDouble(f1)), new Anon0("Main", "src/Main.hx", 14, "main"));
    }
```

When simplified, shows that the second trace fails as `f2 == null` is true which causes `f1 == null` to be returned which is false.

Source: `Log.trace.invoke(f2 == null ? f1 == null : (...));`

**Comment by ianharrigan** [comment]
Also, just a side note, the same code using the (deprecated?) hxJava yields code similar to this and a correct result (ive stripped the trace code for brevity):

```java
        boolean c1 = ( ! (haxe.lang.Runtime.eq(f1, f2)) );
        boolean c2 = ( ! (haxe.lang.Runtime.eq(f2, f1)) );
```

**Comment by CanIGetaPR** [comment]
Hey @RealyUniqueName  did you mean to close this? It shows up fixed in your haxe roundup to do list.

**Comment by Aurel300** [comment]
@CanIGetaPR Haxe roundup is not authoritative, nor was it @RealyUniqueName that added this issue to that list. It seems b7d4a1d did indeed fix this issue.
