### ISSUE TITLE
Inconsistent acceptable syntax on 'is' operator when combined with prefix and postfix operators

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/haxe#9899]
```haxe
        b = ints[0]++ is String;  //  <-- This works
        b = --ints[0] is String;  //  <-- This doesn't:  characters 15-32 : Invalid assign

        point.x++ is String;  //  <-- This works
        ++point.x is String;  //  <-- This doesn't:  characters 11-28 : Invalid assign

        b = ++i is String;    //  <-- This doesn't:  characters 15-26 : Invalid assign
        b = (++i) is String;  //  <-- This works
```

The problem appears to be that the precedence is not being honored with prefix operators.  While `val++ is String` is parsed as `(val++) is String`, the opposite is parsed as `--(val is String)`; as if it had right associativity.

Both increment and decrement operators are of higher precedence than 'is', so all of the statements above should be acceptable to the compiler.

Haxe version: 4.2.0-rc.1+5fdb1661b  (Nightly 2020-09-11)

**Comment by nadako** [comment]
Thanks for catching this and indeed you are correct :)
