### ISSUE TITLE
[lua] hx-lua-simdjson breaks -D lua-vanilla

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/haxe#9900]
Per my comment on #9885: when using `-D lua-vanilla` (binary/external deps are a no-go), the flag is not respected as it was previously, and I get failed requires.

There should be a fallback to the generic parser when this flag is in use. I've worked around the issue by copying the generic parser out of std for the time being.

**Comment by jdonaldson** [comment]
Thanks for your patience.  I do agree this is problematic and I need to support "vanilla" development more robustly.  I need to think through the design choices in more detail, I'm not sure if the "vanilla" flag is a good design pattern.

**Comment by inklit** [comment]
any update on this?
