### ISSUE TITLE
Issue with `haxe.EntryPoint`. Quick fix, I think.

### ISSUE THREAD

**Issue by 0b1kn00b** [HaxeFoundation/haxe#9901]
`processEvents` returns `-1` if there are no further events, but the new `EntryPoint.run` is `nextTick > 0`. See [here](https://github.com/HaxeFoundation/haxe/blob/3e4e6288f07c16828d1161c582b4dafedda88cac/std/haxe/EntryPoint.hx#L141)

**Comment by RealyUniqueName** [comment]
There's indeed an issue, but not only in that check.
The main issue is that on threaded targets `haxe.MainLoop` events may be added _after_ `EntryPoint.run` finished. 
I've tried to assemble a quick fix, but it turned out to be more involved than I expected.
Hopefully I'll manage to fix it today.

**Comment by 0b1kn00b** [comment]
Excuse me, I didn't look so deeply that I noticed anybody else's problem there. I've previously written a back-off algorithm to handle spinning where sub threads are busy, I don't know if that would be any help, would it?
