### ISSUE TITLE
Local variable _hx_tmp used without being initialized

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9905]
Breaks both on 4.0 and nightly. Tested on `--interp` and JS.
```haxe
class Main {
    static function main() {
        switch Foo.A(10) {
            case A(_ => val(_) => id): trace(id);
            //     ^^^^^^^^^^^^^^^^^ Error here.
        }
    }
    static inline function val(i:Int) {
        foo(i);
        return foo(i);
    }
    static inline function foo(id:Int) {
        var v = null;
        for (i in []) if (i == id) {
            v = "i";
            break;
        }
        return v;
    }
}
enum Foo {
    A(id:Int);
}
```
The following makes the error go away:
- Removing either inline.
- Not using pattern matching extractor, and rather doing the same in the case body.
- Calling `foo` only once.
- Not iterating an array in `foo`.
- Not breaking and/or having the condition in `foo` loop.

**Comment by RealyUniqueName** [comment]
The matcher produces a sane code.
It's an error somewhere in VarLazifier filter. Commenting it out fixes the issue.

**Comment by RealyUniqueName** [comment]
A bit "reduced":
```haxe
class Main {
	static function main() {
		var v = Std.random(10);
		switch v {
			case (
				_ =>
				({
					while(Std.random(2) == 0) {
						trace(_);
					}
					_;
				})
				=> v1
			):
				trace(v1);
		}
	}
}
```

**Comment by RealyUniqueName** [comment]
I think the matcher should be updated to make the filter unnecessary.
But it turned out to be too complex. So after some tests and trials I've ended up patching var lazifier filter.

**Comment by Simn** [comment]
I agree the filter should be unnecessary, but it was pretty difficult to get this right when I originally worked on it.
