### ISSUE TITLE
Heaps regression w/dev

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9911]
Not sure since then but there is a regression with latest dev wrt heaps:

https://travis-ci.org/github/HeapsIO/heaps/jobs/736018107

**Comment by nadako** [comment]
I had this locally as well when I was trying heaps with latest haxe, and I didn't understand this. Surely the expected type is an enum abstract type there. Maybe it gets lost somehow because `slides.shader` is a type parameter?

**Comment by RealyUniqueName** [comment]
This happens because the setter for `mode` is not type-hinted. And because of a `cast` the argument type and the return type of `set_mode` cannot be inferred:
```haxe
function set_mode(m) { smode = cast m; return m; }
```
https://github.com/HeapsIO/heaps/blob/06a72533183691e8857e52abde97e6c29229afab/h3d/shader/pbr/Slides.hx#L69-L69
AFAIR I did a change to infer getter/setter types based on the property type. That change was probably lost during recent monomorph changes.

**Comment by RealyUniqueName** [comment]
Reduced:
Enm.hx
```haxe
enum abstract Enm(String) {
	var Full;
}
```
Main.hx
```haxe
class Main {
	static var x(never,set):Enm;
	static function set_x(v) return v;

	static function main() {
		x = Full;
	}
}
```

**Comment by RealyUniqueName** [comment]
Bisected to 72e61e05db6b718fb0f6008b3ae969bfbcf0ede6

**Comment by RealyUniqueName** [comment]
Based on @Simn's comment in that commit I don't think we can fix this as it would toggle another issue.
Given how simple this is to workaround by type-hinting either an argument or return type of a setter I'm closing this as wontfix.

**Comment by ncannasse** [comment]
Should we not infer the setter argument to be of the type of the variable it binds ?
Would also allow completion in setter, without the need to type hint the variable.

**Comment by RealyUniqueName** [comment]
I struggle to find a solution for this.
At the `PConnectField` build pass the type for setter is `TLazy` and we should not resolve it according to @Simn's comment I linked earlier. At any earlier build pass there's no reliable way to detect property-setter relations.
So, the only way I see is to patch type hints for setters before initializing `tclass_field` instances in `init_class` ([here](https://github.com/HaxeFoundation/haxe/blob/7928a86/src/typing/typeloadFields.ml#L1533-L1534)). But this just looks like a dirty hack.

**Comment by RealyUniqueName** [comment]
Actually even hacking type-hints of setters in AST is not reliable because of overloading.
One could have a proper setter defined and an overloaded function without type hints, which would be unrelated to the property.

**Comment by Simn** [comment]
Alex's example compiles on latest development, and nobody here mentioned how this was failing in the first place... I'll assume that this is not something urgent to look into.

**Comment by kLabz** [comment]
> Should we not infer the setter argument to be of the type of the variable it binds ?
> Would also allow completion in setter, without the need to type hint the variable.

This reminds me of a change that was added to add some type inference to getters/setters, which I had to update because it was not checking if it was linked to an actual property.

So uh maybe this issue was actually addressed but not closed?

**Comment by Simn** [comment]
Ah yeah, it was probably #10569.
