### ISSUE TITLE
[server] Weird ECast Count when fatalError

### ISSUE THREAD

**Issue by R32** [HaxeFoundation/haxe#9918]
When the `fatalError` occurs, the `ECast` will nest itself when you press `ctrl+shift+b` to compile again

The following code shows the automatic increase of `ECast Count`:

```haxe
#if macro
import haxe.macro.Context;
import haxe.macro.Expr;
import haxe.macro.Type;
using haxe.macro.Tools;
#end

enum abstract Days(Int) to Int {
    var Sun = 0;
    var Mon;
    var Tue;
}
class Main {
    static function main() {
        Macros.weirdECast(Days);
    }
}
class Macros {
    macro public static function weirdECast( typePath : Expr ) {
        var type = Context.getType(typePath.toString());
        var text = "ECast Count: " + ecastCount(type);
        Context.fatalError(text, (macro {}).pos);
        trace(text);
        return macro {};
    }
#if macro
    static function ecastCount( type : Type ) {
        switch (type) {
        case TAbstract(_.get() => ab, _) if (ab.meta.has(":enum")):
            for (field in ab.impl.get().statics.get()) {
                var first = field.meta.get()[0];
                return strip(first.params[0], 0);
            }
        default:
        }
        return -1;
    }
    static function strip(e, acc) {
        return switch(e.expr) {
        case ECast(e, _):
            strip(e, acc + 1);
        case _:
            acc;
        }
    }
#end
}
```

**Comment by RealyUniqueName** [comment]
This is not reproducible with 4.1.4. So it's a regression in development branch.

**Comment by RealyUniqueName** [comment]
Bisected to b16cd4516f1b38d7f24bf240e286f068ecadfd56

**Comment by RealyUniqueName** [comment]
I can't find the root of the issue, but we can probably workaround it by checking if `ECast` already exists here:
https://github.com/HaxeFoundation/haxe/blob/cd359a2f0473298874710c0304f41c13e8eb6251/src/typing/typeloadFields.ml#L405-L409
I don't like that, but at this point I almost lost hope of finding the right solution.

**Comment by RealyUniqueName** [comment]
I figured it out finally.
Because of insertion of `AStatic` is removed from this line: https://github.com/HaxeFoundation/haxe/commit/b16cd4516f1b38d7f24bf240e286f068ecadfd56#diff-e2544755c5d08cd8fc6c37e9ff6fe4db0617aafa3eab6d25395e260e81e505e6L385
this check now always is evaluated to `true`: 
https://github.com/HaxeFoundation/haxe/blob/8ce5f05a6b703ecaa398f0af7dd4a8c5c767d95a/src/typing/typeloadFields.ml#L374
and `ECast` is inserted again and again on each build.
