### ISSUE TITLE
Local variable might be unitialized

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9919]
The following will complain about "local var might be unitialized foo", while it was not the case in Haxe 4.0

```haxe
var foo : Void -> Void;
foo = function() {
     trace("Hello");
     haxe.Timer.delay(foo,1);
};
```

(note : tested with 4.1.4)

**Comment by RealyUniqueName** [comment]
It's an intended change: #7447

**Comment by ncannasse** [comment]
Yes I'm aware of it, but I think this specific pattern could maybe be excluded, if it's not too hard to code.
We can be 100% sure there's no problem here Binop(OpAssign,Ident,Function)

**Comment by RealyUniqueName** [comment]
But we have named local functions for that pattern:
```haxe
function foo() {
  trace("Hello");
  haxe.Timer.delay(foo,1);
}
```

**Comment by RealyUniqueName** [comment]
@ncannasse Are you ok with named functions solution or do you think this should be changed for that specific case?
