### ISSUE TITLE
4.1.x HL Thread bugfix

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9920]
Here's a patch for 4.1.x branch in std/hl/_std/sys/thread/Thread.hx
A thread which ends will crash HL if it reaches dropThread without a getQueue() being called before that.

```haxe
	static inline function dropThread(handle:ThreadHandle) {
+	  	if( queue_mutex == null )
+ 			return;
		queue_mutex.acquire();
		for (i => tq in threads_queues) {
			if (tq.t == handle) {
				threads_queues.splice(i, 1);
				break;
			}
		}
		queue_mutex.release();
	}
```

I notice that in development the implementation has already been fixed by changes of implementation.

**Comment by RealyUniqueName** [comment]
Merged

**Comment by ncannasse** [comment]
thanks!
