### ISSUE TITLE
`final var x` parses successfully in expressions

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9923]
```haxe
function main() {
	final var x = 1; // parses
	x = 15; // behaves as non-final var
}
```

**Comment by Aurel300** [comment]
This errors out on 83ad82b8718986bd211552e6202059ef398290ef, so I assume it is a regression.

**Comment by nadako** [comment]
Hmm, actually this gives me `Missing variable identifier` when compiling without cache server, but with works if I compile through cache server, even though vscode initial caching build fails... WTF.

**Comment by RealyUniqueName** [comment]
The regression was introduced somewhere during 4.1 development.
The sample fails to compile through compilation server with 4.0.5, but compiles with 4.1.4.

**Comment by RealyUniqueName** [comment]
Bisected to 1ffaa6909df39920744a411734770a839b580bf7
Restoring this line fixes the issue:
https://github.com/HaxeFoundation/haxe/commit/1ffaa6909df39920744a411734770a839b580bf7#diff-06a045565ebb704abfdd69f5be519db8a4fdfd1f2991e19dce5b86e80c209e21L150

**Comment by Simn** [comment]
It hits the `cached, is intact display file` branch during diagnostics, which means that `pd_errors` is empty somehow.

**Comment by Simn** [comment]
This no longer parses, see linked issue.
