### ISSUE TITLE
[PHP] _SERVER var name

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9924]
Hej !

I'm on this "bug" for several days now it drove me crazy...
I've named a local variable "_SERVER", haxe transpilled that to $_SERVER and it has "overriden" the php _SERVER variable...
I don't know maybe something should be done for something like that ?

**Comment by RealyUniqueName** [comment]
It's a builtin global variable in PHP runtime.
Sure we can make compiler rename such variable names in the generated code, but I'm not sure if we should.
It's easy to workaround: just pick another name for your variable.

**Comment by filt3rek** [comment]
Thanks Aleksandr for your reply !
Yes I've renamed my var but reported that for the future because other people can do the same stupid think I've done and get headacke...
I'm sure it occurs also with others built in global vars.
Anyway, thanks for your attention !

**Comment by RealyUniqueName** [comment]
Another option is to emit a warning for such variable names.

**Comment by Aurel300** [comment]
> [...], but I'm not sure if we should.

Sure we should, how is this different from not generating `console`, `window`, etc on Javascript? The reserved variable is accessible via `php.SuperGlobal._SERVER`.

**Comment by RealyUniqueName** [comment]
I agree.
