### ISSUE TITLE
`switch $e` does not parse

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9930]
```haxe
static macro function foo() {
	var e = macro 0;
	return macro switch $e {
		case _:
	}
}
```
Results in `Unexpected case`. With parenthesis `switch ($e) { ...` it works.

**Comment by Simn** [comment]
That might not be about `switch` in particular but about the `$e {` part being interpreted as `$e{` (for reification syntax).

**Comment by Antriel** [comment]
Hmm, it does happen with any name starting with `$`, not just those used for reification. But I guess that makes it difficult to fix.

**Comment by RealyUniqueName** [comment]
We can probably emit a better error message during parsing if `switch` is followed by `$`.

**Comment by Simn** [comment]
I'm actually surprised that `$e {` works, I thought it had to be `$e{`.

**Comment by Simn** [comment]
On second thought, I don't think we should make this whitespace-sensitive if there's no good reason to do so.
