### ISSUE TITLE
[js][es5] Cannot extend es6 class

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/haxe#9934]
**Update:** I'm not sure this is possible to solve 100% correctly, but interested to hear if anyone else has ideas

If I extend an extern class that's defined with es6 syntax (without using `-D js-es=6`):
```js
// js
class ES6Class {
}
```
```haxe
// haxe
class Extension extends ES6Class {
    final extensionField = 1;
}
```

I will get a runtime error **Class constructor ES6Class cannot be invoked without 'new'**

This is because haxe generates the following when invoking a super-class constructor:

```js
// generated js
var Extension = function() {
    this.extensionField = 1;
    ES6Class.call(this);
   // ^ the above line fails because the constructor cannot be invoked without new
}
```

An example where this is a problem is extending three.js classes (recently three.js has moved to es6 class syntax)

I've tried a lot and I think it might be not possible to get it 100% correct

One solution is to create an instance of the super class and copy the fields:
```js
// generated js
var Extension = function() {
    this.extensionField = 1;
    var superInstance = new ES6Class();
    Object.assign(this, superInstance);
}
```
But having two instances could lead to subtle errors if `new ES6Class()` stores its instance somewhere

Another solution is to create a instance of the super class, treat it as `this` and return it, but that means `this` cannot be used before `super()`
```js
// js
var Extension = function(a, b) {
    var superInstance = new ES6Class(a, b);
    // `this` gets remapped to `superInstance`
    superInstance.extensionField = 1; 
    return superInstance;
}
```

Minimal repro project
[issue-9934-es6-extend.zip](https://github.com/HaxeFoundation/haxe/files/5441850/issue-9934-es6-extend.zip)

**Comment by RealyUniqueName** [comment]
I think if a project relies on libraries written with es6 syntax, then the project itself should be compiled with `-D js-es=6`.

**Comment by sonygod** [comment]
wow!,it's work!

**Comment by hansagames** [comment]
Other option is to convert threes to es5 using babel, I do it for other project where I have similar issues, after npm install run script that converts whole library to es5

**Comment by RealyUniqueName** [comment]
Nothing to do here.
