### ISSUE TITLE
[macro]can't generate  code when function body is empty.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9937]
haxe 4.1.4

    import haxe.macro.Context;
    import haxe.macro.Expr;

    class MyMacro {

    public static function build(d:String) {

          var fields=Context.getBuildFields();

          var c = macro class X {
            public static function main() {
        
              Cc.cl({name:"",extends2:""});//won't genearte code when Cc.cl function body is empty.
            }
          };
      
          fields.push(c.fields[0]);

          return fields;
      
    }

//-----------------------

 	@:build(TypeBuildingMacro.build("myFunc"))
	class Main {

		
	}

//------------

     class Cc {
    
    @:native("Class")
    public static function cl(d:Dynamic) {
        
        trace(d);//when I remove this line ,macro won't generate code .
    }
}

**Comment by RealyUniqueName** [comment]
What does "won't generate code" mean?
Do you see any errors emitted by the compiler?
What target are you compiling for?

**Comment by kLabz** [comment]
Sounds like `CC.cl(...)` call is being removed by the compiler because it does nothing, which is expected behavior.

**Comment by sonygod** [comment]
May be @kLabz  is right.
