### ISSUE TITLE
evaluation order of pattern match on multiple values

### ISSUE THREAD

**Issue by Antriel** [HaxeFoundation/haxe#9938]
```haxe
var arr = [0, 1, 2];
switch [arr.shift(), arr.shift(), arr.shift()] {
  case [a, b, c]: trace(a, b, c); // Prints "2, 1, 0".
}
```
Doing `var arr2 = [arr.shift(), arr.shift(), arr.shift()]; switch arr2 { ... }` has the expected result of "0, 1, 2".

Given that we don't have early-exit and every expression gets evaluated anyway, maybe it should be evaluated left to right? Although I suppose that's a breaking change. In either case, it should at least be documented.

**Comment by RealyUniqueName** [comment]
Here's the reason:
https://github.com/HaxeFoundation/haxe/blob/d04e678aa26e19b880e637b12ab81c4115b5e242/src/typing/matcher.ml#L1611-L1611
But simply commenting out that line breaks patterns compilation.

**Comment by Simn** [comment]
This entire thing looks like "someone" just added list reversals in random places until it worked...

**Comment by Simn** [comment]
This will cause some diff-erence. I've compared the JS output and it looks like expected: The order of temporary variables is now natural instead of reversed.
