### ISSUE TITLE
Counts refs to class field

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe#9939]
I have a macro that parses a pictures directory and builds a class by adding static fields into it (one field for each picture path  found).

I'm wondering if there is any way to know - at compile time - the count of refs to those fields so that  I know if some of them are unused or just how many times each of them are used.

**Comment by RealyUniqueName** [comment]
You can parse the final typed syntax tree in `haxe.macro.Context.onGenerate()`: https://api.haxe.org/haxe/macro/Context.html#onGenerate

**Comment by zabojad** [comment]
@RealyUniqueName if I understand it correctly, this will allow me to inspect the generated types.

What I'm looking for is rather how many times the static fields of my macro generated class are used/called elsewhere in my project.

Exemple: my macro generated class will look like:
```haxe
class MyPictures {
  static var myPicture01(get,null):String=js.lib.require("...");
  static public function get_myPicture01(){ return myPicture01; }
  
  static var myPicture02(get,null):String=js.lib.require("...");
  static public function get_myPicture02(){ return myPicture02; }

  static var myPicture03(get,null):String=js.lib.require("...");
  static public function get_myPicture03(){ return myPicture03; }

  static var myPicture04(get,null):String=js.lib.require("...");
  static public function get_myPicture04(){ return myPicture04; }
}
```

Now how to know how many times my code uses: `MyPictures.myPicture01`, `MyPictures.myPicture02`... ?

**Comment by RealyUniqueName** [comment]
You have to walk through all the expressions of generated type in a macro and count that by yourself.

**Comment by zabojad** [comment]
@RealyUniqueName ok... let me take an example:

In my project code, there is a class called `SearchFooterBtn` that uses one of those pictures. It might be not relevant but here is how it does that:

```haxe
class SearchFooterBtn {
	// ...
	static public function render(props:SearchFooterBtnProps) {
		return jsx('
			<TouchableOpacity onPress=${ searchCb.bind(props) }>
				<Image source=${MyPictures.myPicture01}  />
			</TouchableOpacity>
		');
	}
}
```

Now when I debug what we have in `haxe.macro.Context.onGenerate()`, I can find my `SearchFooterBtn` as a class:

```haxe
#if debug_pictures
		haxe.macro.Context.onGenerate(debugCb);
#end

// ...

#if debug_pictures

	static function debugCb(t:Array<Type>){
		trace("DEBUG PICTURES");
		for (tt in t) {
			switch(tt){
				// case TInst(t:Ref<ClassType>, params:Array<Type>):
				case TInst(t, params):
					if (t.toString() == "myproj.SearchFooterBtn") {
						trace("Found ref: ",t.toString());
						for (pp in params) {
							trace('pp = ',pp);
						}
						var c = t.get();
						// Here I have a `ClassType`. How can I determine that my class is using `MyPictures. myPicture01` from that?
					}
	
				default: //...
			}
		}
		trace("END DEBUG PICTURES");
	}
#end
```

Where would we find the dependency of SearchFooterBtn to MyPictures.myPicture01?

**Comment by RealyUniqueName** [comment]
You need to look through `ClassField.expr` of  `ClassType.statics`, `ClassType.fields` and `ClassType.constructor`

**Comment by Simn** [comment]
This isn't really a Haxe issue. Please use https://community.haxe.org/ for questions like this.
