### ISSUE TITLE
[cs?] untyped + bad identifier = ident not supported

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#9940]
Found this by making a typo. Got no error from haxe compiler, but C# compilation failed:

```haxe
class Main {
  public static function main() {
    untyped __cs__('System.Console.WriteLine({0})', missingIdentifier.someField);
    // => System.Console.WriteLine(global::haxe.lang.Runtime.getField([ ident not supported ], "someField", 968994086, true));
  }
}
```

**Comment by RealyUniqueName** [comment]
I think we can emit a compilation error in this case. Any other ideas?

**Comment by kLabz** [comment]
Yeah, catching the error on haxe side sounds great

**Comment by kLabz** [comment]
We might "just" need a proper `cs.Syntax.code()` to replace `untyped __cs__(...)`?

**Comment by RealyUniqueName** [comment]
That too. But `untyped __cs__` won't get removed in the nearest future anyway.
