### ISSUE TITLE
[java] Generated java code involving abstracts and dynamic typing seems to fail.

### ISSUE THREAD

**Issue by Marika-0** [HaxeFoundation/haxe#9942]
I've run into an issue with trying to run Java code produced by Haxe. This occurs with Haxe 4.1.4, and with Haxe Development version a16c00f (2020-11-06); with both versions 3.2.0 and 4.0.0-alpha of the hxjava library; while using OpenJDK 14.0.2 (2020-07-14).

The issue seems to occur when dynamically typing a type parameter of an abstract. Please see the attached [source.zip](https://github.com/HaxeFoundation/haxe/files/5504037/source.zip), which defines an abstract `SingleAssociationNode` (a node of a single-linked list containing a key-value pair) and attempts to iterate over its typed keys regardless of the type of its values.

Upon running generated code, the following error appears:
```
src/haxe/root/Main.java:45: error: incompatible types: SingleNode<Pair<String,Object>> cannot be converted to SingleNode<Pair>
			haxe.root.KeyIterator<java.lang.String> key = new haxe.root.KeyIterator<java.lang.String>(((haxe.root.SingleNode<haxe.root.Pair>) (head) ));
			                                                                                                                                  ^
src/haxe/root/KeyIterator.java:42: error: incompatible types: SingleNode<Pair> cannot be converted to SingleNode<Pair<K,Object>>
		K x = ((K) (_Main.SingleAssociationNode_Impl_.get_key(((haxe.root.SingleNode<haxe.root.Pair<K, java.lang.Object>>) (this.node) ))) );
		                                                                                                                   ^
  where K is a type-variable:
    K extends Object declared in class KeyIterator
src/haxe/root/KeyIterator.java:44: error: incompatible types: SingleNode<Pair> cannot be converted to SingleNode<Pair<K,Object>>
		this.node = ((haxe.root.SingleNode<haxe.root.Pair>) (_Main.SingleAssociationNode_Impl_.get_next(((haxe.root.SingleNode<haxe.root.Pair<K, java.lang.Object>>) (this.node) ))) );
		                                                                                                                                                             ^
  where K is a type-variable:
    K extends Object declared in class KeyIterator
3 errors
Compilation error
Native compilation failed
Error: Build failed
```
Which seems to refer to a lack/over-definition of type parameters (not sure of the specific Java term).

**Comment by RealyUniqueName** [comment]
Does it work with the jvm target?

**Comment by Marika-0** [comment]
Yes, it works as expected when compiled with
```
--main Main
--jvm ./jvm.jar

--cmd java -jar ./jvm.jar
```

**Comment by RealyUniqueName** [comment]
`KeyIterator.java` is generated with insufficient type parameters for `haxe.root.Pair`.

`haxe.root.SingleNode<haxe.root.Pair>` should be generated as `haxe.root.SingleNode<haxe.root.Pair<K, java.lang.Object>>` instead.

**Comment by Simn** [comment]
Going forward, we are only going to fix regressions on the Java target as our focus is on the JVM output. As I understand it, this is not a regression and the Java target is known to have many problems with type parameter generation. I'll go ahead and close this.
