### ISSUE TITLE
[cs]Compile with UnityEditor.dll error

### ISSUE THREAD

**Issue by xhfzcmt** [HaxeFoundation/haxe#9946]
with hxml

-net-lib /Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll     [OK]

-net-lib /Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll      [Fail]

PeReader.Error_message("Error reading compressed data. Invalid first byte: ff")

haxe version:4.1.4
hxcs version:3.4.0
unity version:2020.1.10

**Comment by RealyUniqueName** [comment]
What's the difference between "[OK]" and "[Fail]" lines?

**Comment by xhfzcmt** [comment]
> What's the difference between "[OK]" and "[Fail]" lines?

Sorry. should be

-net-lib /Applications/Unity/Unity.app/Contents/Managed/UnityEngine.dll [OK]

-net-lib /Applications/Unity/Unity.app/Contents/Managed/UnityEditor.dll [Fail]

**Comment by xhfzcmt** [comment]
two dll file from unity.app.

[UnityEngine And UnityEditor.zip](https://github.com/HaxeFoundation/haxe/files/5516171/UnityEngine.And.UnityEditor.zip)

**Comment by kLabz** [comment]
Edit: nevermind, had mixed up engine and editor

**Comment by kLabz** [comment]
Do you have `UnityEditor.xsd` too?

**Comment by xhfzcmt** [comment]
> Do you have `UnityEditor.xsd` too?

have not

![Screen Shot 2020-11-10 at 6 15 14 PM](https://user-images.githubusercontent.com/18002964/98660831-b4bcf300-2380-11eb-8730-ed3834a362f1.png)

**Comment by kLabz** [comment]
xml then please :)

**Comment by xhfzcmt** [comment]
[xml.zip](https://github.com/HaxeFoundation/haxe/files/5516617/xml.zip)


> xml then please :)

**Comment by kLabz** [comment]
Can you try with this [custom haxe version `*`](https://artprodsu6weu.artifacts.visualstudio.com/A92de5486-af68-44d2-a486-e3f509be4675/a44f6741-3a03-4a3f-a4c5-84e4584b58c6/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL0hheGVGb3VuZGF0aW9uL3Byb2plY3RJZC9hNDRmNjc0MS0zYTAzLTRhM2YtYTRjNS04NGU0NTg0YjU4YzYvYnVpbGRJZC82ODQxL2FydGlmYWN0TmFtZS9tYWNCaW5hcmllcw2/content?format=zip)? (mac release, that's what you need right?)

You should not be getting current error, but I'm not 100% sure it'll generate all types you'd need, and it might break later in the compilation. Knowing where it'd break would help me properly fix the issue.

> `*` Source : [artifacts](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=artifacts&type=publishedArtifacts) produced by [Haxe CI](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=results) for my [WIP PR](https://github.com/HaxeFoundation/haxe/pull/9948)

**Comment by xhfzcmt** [comment]
I saw your modification. thank you very much. How can I update to this version?

**Comment by xhfzcmt** [comment]
> 您可以尝试使用此[自定义haxe版本`*`](https://artprodsu6weu.artifacts.visualstudio.com/A92de5486-af68-44d2-a486-e3f509be4675/a44f6741-3a03-4a3f-a4c5-84e4584b58c6/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL0hheGVGb3VuZGF0aW9uL3Byb2plY3RJZC9hNDRmNjc0MS0zYTAzLTRhM2YtYTRjNS04NGU0NTg0YjU4YzYvYnVpbGRJZC82ODQxL2FydGlmYWN0TmFtZS9tYWNCaW5hcmllcw2/content?format=zip)吗？（mac版本，这就是您需要的吗？）
> 
> 您应该不会遇到当前错误，但是我不是100％确定它会生成所需的所有类型，并且它可能在以后的编译中中断。知道将在哪里中断将有助于我正确解决此问题。
> 
> > `*`来源：[Haxe CI](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=results)为我的[WIP PR](https://github.com/HaxeFoundation/haxe/pull/9948)制作的[文物](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=artifacts&type=publishedArtifacts)[](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=results)[](https://github.com/HaxeFoundation/haxe/pull/9948)

`private function compileHaxeToCSharp(mainProgram:String, outputFolder:String, ?cmdLinesFilter:(lines:Array<String>)->Array<String>):Void {
    if(unityEngineDLL == null) {
      FiLog.err('set FiUnityProject::unityEngineDLL first.');
      Sys.exit(1);
    }
    var compile_lines:Array<String> = [
      'haxe',
      '-cp src',
      '-D net-ver=40',
      '-D no_debug',
      '-net-lib=${unityEngineDLL}',
      '-net-lib=${unityEditorDLL}',  // <------------ It works 😊
      //'-D no-compilation',
      '-D real-position',
      '-D no_root',
      '-D rtti',
      '-D unity',
      '-D dll',
      '--main ${mainProgram}',
      '--cs ${outputFolder}',
    ];
    //if(pp) {
    //  compile_lines.push('-xml ${outputFolder}/xml/api.xml');
    //}
    if(cmdLinesFilter != null) {
      compile_lines = cmdLinesFilter(compile_lines);
    }
    this.syscommand(compile_lines.join(' '));
  }`


`package yrctnod.editor.setting;

import unityengine.*;

//-------------------------------------------------------------------------
//  Yesterday
//-------------------------------------------------------------------------
// @:native('UnityEditor.EditorWindow')
// private extern class EditorWindow {
//   public function Show():Void;
//   public function Hide():Void;
// }
// class SettingPanel extends EditorWindow {
//   public function OnEnable():Void {
//   }
//   public function OnDisable():Void {
//   }
//   public function OnGUI() {
//     var isDown:Bool = untyped __cs__('UnityEngine.GUILayout.Button("Apply")');
//     if(isDown) {
//       trace('Apply');
//     }
//   
//     
//   }
// }

//-------------------------------------------------------------------------
//  Today
//-------------------------------------------------------------------------
import unityeditor.*;
class SettingPanel extends EditorWindow {   // <------- It works too 😊
  public function OnEnable():Void {
  }
  public function OnDisable():Void {
  }
  public function OnGUI() {
    var isDown:Bool = untyped __cs__('UnityEngine.GUILayout.Button("Apply")');
    if(isDown) {
      trace('Apply');
    }
    
  }
}`

well done!!!!
thank you very mush.


Everything is working now.

**Comment by xhfzcmt** [comment]
> Can you try with this [custom haxe version `*`](https://artprodsu6weu.artifacts.visualstudio.com/A92de5486-af68-44d2-a486-e3f509be4675/a44f6741-3a03-4a3f-a4c5-84e4584b58c6/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL0hheGVGb3VuZGF0aW9uL3Byb2plY3RJZC9hNDRmNjc0MS0zYTAzLTRhM2YtYTRjNS04NGU0NTg0YjU4YzYvYnVpbGRJZC82ODQxL2FydGlmYWN0TmFtZS9tYWNCaW5hcmllcw2/content?format=zip)? (mac release, that's what you need right?)
> 
> You should not be getting current error, but I'm not 100% sure it'll generate all types you'd need, and it might break later in the compilation. Knowing where it'd break would help me properly fix the issue.
> 
> > `*` Source : [artifacts](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=artifacts&type=publishedArtifacts) produced by [Haxe CI](https://dev.azure.com/HaxeFoundation/GitHubPublic/_build/results?buildId=6841&view=results) for my [WIP PR](https://github.com/HaxeFoundation/haxe/pull/9948)

![Screen Shot 2020-11-11 at 10 32 30 AM](https://user-images.githubusercontent.com/18002964/98758238-4112f880-2409-11eb-8723-7bd40cb2792c.png)

![Screen Shot 2020-11-11 at 10 28 57 AM](https://user-images.githubusercontent.com/18002964/98758036-c0ec9300-2408-11eb-95fa-f4311aadb41e.png)


well done!!!!
thank you very mush.


Everything is working now.

**Comment by kLabz** [comment]
Ok, nice :) I'll keep looking for a proper fix (or a reason why this one is ok), please report any unexpected thing happening while working with UnityEditor.dll. I might ping you to try another custom release if I have a potential "real fix".

**Comment by xhfzcmt** [comment]
> Ok, nice :) I'll keep looking for a proper fix (or a reason why this one is ok), please report any unexpected thing happening while working with UnityEditor.dll. I might ping you to try another custom release if I have a potential "real fix".

OK ,I will.

**Comment by xhfzcmt** [comment]
> Ok, nice :) I'll keep looking for a proper fix (or a reason why this one is ok), please report any unexpected thing happening while working with UnityEditor.dll. I might ping you to try another custom release if I have a potential "real fix".

Dll work well Currently 👍 
1. Import classes in dll (OK)
2.Use unity meta(OK,  but need full path "`UnityEngine.HideInInspector`" instead "`HideInInspector`")
3.Compile a c# dll put it into unity project (OK, it works)

There are only minor problems.
1.Call functoin in dll that overload, can only use obscure writing("`untyped __cs__`")
 
![Screen Shot 2020-11-11 at 3 49 06 PM](https://user-images.githubusercontent.com/18002964/98909135-5e74bf00-24fc-11eb-9737-790f18f5bf49.png)
solution
![Screen Shot 2020-11-11 at 3 49 39 PM](https://user-images.githubusercontent.com/18002964/98909157-67659080-24fc-11eb-8a6b-05c9dd25eac2.png)

2.Call this "Main" function to start haxe main loop.  it will crash unity i don't know why
![Screen Shot 2020-11-12 at 3 34 17 PM](https://user-images.githubusercontent.com/18002964/98909256-89f7a980-24fc-11eb-9dda-879060999b06.png)
solution
![Screen Shot 2020-11-12 at 3 35 57 PM](https://user-images.githubusercontent.com/18002964/98909421-c4614680-24fc-11eb-85c9-23f658539260.png)

**Comment by xhfzcmt** [comment]
**There is a problem.**
![Screen Shot 2020-11-12 at 8 36 06 PM](https://user-images.githubusercontent.com/18002964/98940949-c9d38680-2526-11eb-86cd-918633c8b21e.png)

When I use `Mesh` class static method. I got an error.
```
untyped __cs__('UnityEngine.Mesh.DestroyImmediate({0})', _highlightCellMesh);// it works

```
[https://docs.unity3d.com/ScriptReference/Object.DestroyImmediate.html](url)

**Comment by kLabz** [comment]
Well it's a static from `Object`, not from `Mesh`. The xml file you provided says so, and the link in your message too.

**Comment by xhfzcmt** [comment]
> nd the link in your message to

Got it. 😄
`Object.DestroyImmediate(_highlightCellMesh);`

initial. I clicked in from the Mesh class api

**Comment by xhfzcmt** [comment]
[Test.zip](https://github.com/HaxeFoundation/haxe/files/5534411/Test.zip)

Toplevel `UnityEngine` And `UnityEditor ` cannot use.
For example:
function return type `UnityEngine.SceneManagement.Scene` got a compile error.

I uploaded a mini test project.

**Comment by kLabz** [comment]
Those are packages, which are lowercase in Haxe. Use `unityengine.scenemanagement.Scene` instead.

**Comment by xhfzcmt** [comment]
> Those are packages, which are lowercase in Haxe. Use `unityengine.scenemanagement.Scene` instead.

OK. thx.

**Comment by xhfzcmt** [comment]
Hello. I'm back.   :)

When I using **imagemagick dll** , I got an compiler error ('Defined in this class')
```
Type not found : imagemagick.IMagickImage_1
src/Main.hx:4: lines 4-9 : Defined in this class
Type not found : imagemagick.WarningEventArgs
[Finished in 0.5s with exit code 1]
```

test project zip
[Test.zip](https://github.com/HaxeFoundation/haxe/files/5571048/Test.zip)

@kLabz

**Comment by kLabz** [comment]
Sounds like a missing dependency (dll); I'd say [`Magick.NET.Core`](https://www.nuget.org/packages/Magick.NET.Core/) in your case. Net libs loading in haxe doesn't magically resolve dependencies, you have to add them yourself. Check on [nuget](https://www.nuget.org/) yourself what those are and add them too.

**Comment by xhfzcmt** [comment]
> Sounds like a missing dependency (dll); I'd say [`Magick.NET.Core`](https://www.nuget.org/packages/Magick.NET.Core/) in your case. Net libs loading in haxe doesn't magically resolve dependencies, you have to add them yourself. Check on [nuget](https://www.nuget.org/) yourself what those are and add them too.



Yes. I will try about .net core, 
I still have a little knowledge at the moment.
So far I have solved it like this.
**The only trouble is that I need to write extern class.**
I added the following lines into `.csproj` file. (It works)


```
<Reference Include="ImageMagick">
   <HintPath>/Users/***********/HaxeProject/TileEdit/dotnet/magick.net-q8-x64/7.22.2.1/lib/net40/Magick.NET-Q8-x64.dll</HintPath>
</Reference>

```


There is a very important point here,
`hxcs` compile will get an error.
```
haxelib run hxcs hxcs_build.txt --haxe-version 4104 --feature-level 1
Note: dmcs is deprecated, please use mcs instead!
src/TileEdit.cs(22,7): error CS0400: The type or namespace name `ImageMagick' could not be found in the global namespace. Are you missing an assembly reference?
```
but I compile use `msbuild TileEdit.csproj` , build succeeded.

**Comment by kLabz** [comment]
It's not about dotnet core, it's just that `Magick.NET-Q8` depends on a library named `Magick.NET.Core` (which happens to have ".NET.Core" in its name)

**Comment by xhfzcmt** [comment]
> pends on a library named

Ok.

**Comment by xhfzcmt** [comment]
> It's not about dotnet core, it's just that `Magick.NET-Q8` depends on a library named `Magick.NET.Core` (which happens to have ".NET.Core" in its name)

OK.  thank you.
