### ISSUE TITLE
[ide] no "generate object literal" snippet for @:structInit classes

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9955]
Could be a vshaxe issue, but I assume it's the compiler :)

```haxe
@:structInit class C {
	var x:Int;
}

function main() {
	var c:C = 
}
```

![image](https://user-images.githubusercontent.com/49749/99048072-62a0eb00-2595-11eb-8c77-1ba60fae2bfc.png)

**Comment by Simn** [comment]
Looks like there's not enough info for vshaxe:

```
                "expectedType": {
                    "kind": "TInst",
                    "args": {
                        "path": {
                            "pack": [],
                            "moduleName": "Main",
                            "typeName": "C",
                            "importStatus": 0
                        },
                        "params": []
                    }
                },
                "expectedTypeFollowed": {
                    "kind": "TInst",
                    "args": {
                        "path": {
                            "pack": [],
                            "moduleName": "Main",
                            "typeName": "C",
                            "importStatus": 0
                        },
                        "params": []
                    }
                }
```

**Comment by Simn** [comment]
So the simple/pragmatic solution here would be to send a `TAnonymous` structure as `expectedTypeFollowed`. This should "just work" without any vshaxe changes.

The alternative is sending this information as some separate entry.

**Comment by nadako** [comment]
I guess sending `TAnonymous` will make vshaxe say that the origin of the field is a structure instead of class? Could be a bit confusing.

UPD: I mean this `from class C` text here:
![image](https://user-images.githubusercontent.com/49749/99063358-ae0ec580-25a4-11eb-94ae-e702cc43b476.png)

**Comment by Simn** [comment]
I don't think that would be affected because it's not toplevel completion and thus has no expected type.

But yes it's certainly cleaner to separate this. Maybe we can generalize it as `compatibleTypes` or something, which then carries an array of stuff that would also work in the place of completion.

**Comment by Simn** [comment]
vshaxe change: https://github.com/vshaxe/haxe-language-server/commit/7f2bdddf3cd8edd884618f9c765a07f40c1c8f65
