### ISSUE TITLE
Line numbers / posInfos off by a lot (1000's)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe#9959]
I've seen this a couple times, randomly, only since upgrading my large JS project from Haxe 4.0.0-rc1 to 4.1.4:

![image](https://user-images.githubusercontent.com/2192439/99596104-f702b780-29b2-11eb-8373-fafc8c735605.png)

I've also seen it in the JavaScript console at runtime:

![image](https://user-images.githubusercontent.com/2192439/99596150-0bdf4b00-29b3-11eb-8ada-41903f19df76.png)

I don't have the tidiest codebase, but none of my files are 5000+ lines long x 6000+ columns. :smile:

Sorry I don't have better repro info at this point -- I'll see if any patterns or other clues emerge.

**Comment by Simn** [comment]
I'm not sure how this could happen. The compiler works with byte offsets internally and then converts those to line/column information by (essentially) counting newlines in the given file. I can see the column position being off if for some reason there are no newlines, but I have no idea how the line number could ever get this high.

Could you test this with a more recent Haxe version from https://build.haxe.org/ some time?

**Comment by RealyUniqueName** [comment]
Closing due to lack of info. Fell free to reopen.

**Comment by jcward** [comment]
(Sorry for the silence, I need to manage my notifications for other repos.)

Another data point on this - it might have to do with the compilation server. Kill & restart the compilation server gave a correct line number.

**Comment by jcward** [comment]
Oh, I'm not sure this is ide related, this is all from the command line. I meant compilation server as in `haxe --wait 6000` and later `haxe --connect 6000`.

I couldn't repro this in a small testcase. :frowning:

I tried the latest nightly build (haxe_2020-12-20_development_d9409e8.tar.gz), but it exploded with hundreds of these errors:

```
.hx:40: characters 5-55 : Macro functions must be called immediately
.hx:40: characters 5-55 : Invalid macro access
.hx:41: characters 5-61 : Macro functions must be called immediately
.hx:41: characters 5-61 : Invalid macro access
...
```

Hmm -- this looks like a bug, I'm going to file it separately (#10025).

I tried a few versions back to July, but they all had the above errors.

**Comment by jcward** [comment]
I can't get a small repro testcase, but I can show a screencast.

Here's what happens in this video:
1) 0:02 - My build watcher is running, and we see messed up line numbers (`StudentLoginPage.hx:3114: characters 14844-15833`)
2) 0:13 - Leaving my watcher running, I go to another tab to restart my `haxe --wait 6020` process
3) 0:24 - Trigger first build on this new haxe process
4) 0:41 - Build complete, line numbers correct (`StudentLoginPage.hx:412: lines 412-431`)
5) 0:48 - Trigger a second build on this haxe process
6) 1:04  - Build complete, line numbers messed up (`StudentLoginPage.hx:3114: characters 14844-15833`)

https://user-images.githubusercontent.com/2192439/106330560-ad4f0c80-6240-11eb-9dfd-79d03a02b717.mp4

Not shown: trigger another build: line numbers still messed up (but still `3114: characters 14844-15833`)

**Comment by kLabz** [comment]
This was likely fixed by https://github.com/HaxeFoundation/haxe/commit/e648d1b70adf8199d2d5f1d673c6ef90f5e5b221 when fixing #10763 (still open, need a test)
