### ISSUE TITLE
Setter won't work if it's called inside itself, working as intended?

### ISSUE THREAD

**Issue by AG-w** [HaxeFoundation/haxe#9962]
I found an old library probably from haxe 3.x.0 version era
I'm trying to edit it so it compatible with haxe 4.0
And then I found a bug (?)

so, basically, the library has a section of code not working as intended
I found it's trying to set a value inside its setter

Then I try to see if it's universal behavior on "Try Haxe"
and this is the result:
https://imgur.com/6ZNlxrS

TL,DR, setter function will be skipped if you are setting a value inside its setter,

**Comment by RealyUniqueName** [comment]
It works as designed.
If you need a recursive call to the setter, just invoke it directly:
```haxe
function set_value(v:Int):Int {
  if(v > 0)
    set_value(v - 1);
  return v;
}
```
