### ISSUE TITLE
abstract(Array<>) with @:forward(iterator, keyValueIterator) not considered Iterable

### ISSUE THREAD

**Issue by imfi-jz** [HaxeFoundation/haxe#9963]
The `Array` class contains fields `iterator` and `keyValueIterator` which if I understand the documentation correctly is what makes it conform the `Iterable` and `KeyValueIterator` interfaces and allows it to be looped over in a for(a in b){...} loop. 
Consider an abstract based on `Array<Float>`. When adding `@:forward(iterator, keyValueIterator)` to the abstract, it is accepted in (for) loops but is still not accepted as parameter value of type `Iterable<Float>` while a base `Array<Float>` is. Instead the compiler will say `(Typename) should be Null<Iterable<Float>>`. Manually adding `function iterator():Iterator<T>{...}` to the abstract has the same behavior.

I can give more details or a code example if needed. If I misunderstood anything let me know.

**Comment by RealyUniqueName** [comment]
> Manually adding function iterator():Iterator<T>{...} to the abstract has the same behavior.

You need to also add `@:to` meta to these fields.

**Comment by RealyUniqueName** [comment]
You need a field like this on your abstract:
```haxe
@:to inline function toIterable():Iterable<T>
    return this;
```

**Comment by imfi-jz** [comment]
> You need a field like this on your abstract:
> 
> ```hx
> @:to inline function toIterable():Iterable<T>
>     return this;
> ```

**Comment by imfi-jz** [comment]
> You need a field like this on your abstract:
> 
> ```hx
> @:to inline function toIterable():Iterable<T>
>     return this;
> ```

Thank you. I wasn't aware of implicit casting of abstracts. Adding `from Array<Float> to Array<Float>` was sufficient.

**Comment by player-03** [comment]
> ```hx
> @:to inline function toIterable():Iterable<T>
>     return this;
> ```

Or, equivalently, `to Iterable<T>`. (Oddly, you still need `@:forward(iterator)` in that case.)

But if the underlying type isn't iterable, [you're out of luck](https://try.haxe.org/#a0E71406). Oh well.
