### ISSUE TITLE
Haxelib error after installing via lix

### ISSUE THREAD

**Issue by prnxdev** [HaxeFoundation/haxe#9965]
I don't think it's problem related to lix package. After installing it via `npm i -g lix` I get this error:
![image](https://user-images.githubusercontent.com/5631954/100474269-8e1ced00-30e0-11eb-9167-013073e27cd6.png)
I allowed to execute commands via powershell and I have latest Windows version

**Comment by RealyUniqueName** [comment]
I don't think it's a Haxe issue. @back2dos ?

**Comment by back2dos** [comment]
Confirmed. Related: https://github.com/lix-pm/lix.client/issues/154
