### ISSUE TITLE
Heaps issue with Haxe dev

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#9967]
https://travis-ci.org/github/HeapsIO/heaps/jobs/746475298#L515

Seems like there's an issue with abstract enum inference here.

Works with 4.0 and 4.1 https://travis-ci.org/github/HeapsIO/heaps/builds/746475297

**Comment by Aurel300** [comment]
Isn't this the same as https://github.com/HaxeFoundation/haxe/issues/9911 ?

**Comment by RealyUniqueName** [comment]
Yep. It's duplicate.
