### ISSUE TITLE
haxe.CallStack.exceptionStack() does not work on Haxe 4.1.4, js target

### ISSUE THREAD

**Issue by TC218** [HaxeFoundation/haxe#9968]
https://gist.github.com/MT4000/d959fab5e88c47bc92bf042fb9077d0e

**Comment by RealyUniqueName** [comment]
I can't reproduce it neither with Haxe 4.1.4 nor with the latest development version.

**Comment by RealyUniqueName** [comment]
Fixed in db0fa95
