### ISSUE TITLE
extern class private constructor

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9978]
Hej,

I just saw that if I have a private constructor in an extern class, so I can call it anyway from anywhere as public one, compiler doesn't complain.
I don't know if it's a normal behaviour, I was surprised.

**Comment by Simn** [comment]
This isn't true, visibility is still respected on `extern` classes. However, the default visibility for those is `public`, so you'll have to make the constructor explicitly `private`.

**Comment by filt3rek** [comment]
Ah ok, didn't knew about that, sorry for this disturbance.
