### ISSUE TITLE
HXML file, several compilations Compiler picks the first configuration available

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#9979]
Hej,

I'm using VSHaxe plugin for  VSCode and it fades the code part that is unused (like not the target yet selected).
But, when I have a .hxml file like that :
```haxe
-lib ftk
--macro ftk.macro.Compiler.deleteRegexFiles( "www", "(app)([\\.0-9]*)(\\.min)*\\.js" )

--next

Client

-js www/app.js
```
VSHaxe fades here the js target even if it's selected, becuse of the first part that doesn't mention any target.
So my question is, could it be possible to pick the first compilation target that has an output please ?

I don't know if it's clear enough.

Anyway, thanks for reading,
Regards,
Michal

**Comment by Simn** [comment]
There's nothing else the compiler can do here. You'll need a better setup in your project in order to support this. I'd stay away from `--each` and `--next` entirely because they are (necessarily) terrible when it comes to IDE support.
