### ISSUE TITLE
require type hinting for abstract methods?

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#9984]
This currently compiles:
```haxe
abstract class C {
	abstract function f(a);
}
```
While this doesn't (`Type required`):
```haxe
interface I {
	function f(a);
}
```
This seems like it should be consistent and type should be also required for abstract methods.

**Comment by back2dos** [comment]
Typically, an abstract class directly depends on its abstract methods, e.g. `readByte` in `haxe.io.Input`. So typically, inference should allow to find the concrete signature within the abstract class itself - which is impossible for interfaces. In your example, the signature cannot be inferred, which then should arguably error.
